### ISSUE TITLE
optional argument to interpolation function for interpolating on new columns or indices

### ISSUE THREAD

**Issue by denfromufa** [pandas-dev/pandas#10020]
Here is a workaround how to achieve this manually:

```
import pandas as pd
import numpy as np
from numpy.random import rand

dfPP=pd.DataFrame(rand(3,5),columns=rand(5),index=rand(3))
nanarr=np.empty(dfPP.shape[0])
nanarr[:]=np.NAN
new_point=dfPP.columns.values.mean()
dfPP.loc[:,new_point]=nanarr
dfPP.sort(axis=1,inplace=True)
dfPP.head()
```

<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>0.211451507884</th>      <th>0.574409309122</th>      <th>0.626609642735</th>      <th>0.728622716072</th>      <th>0.752814445643</th>      <th>0.865750234955</th>    </tr>  </thead>  <tbody>    <tr>      <th>0.340822</th>      <td>0.451636</td>      <td>0.292137</td>      <td>NaN</td>      <td>0.162465</td>      <td>0.481506</td>      <td>0.384237</td>    </tr>    <tr>      <th>0.996621</th>      <td>0.997825</td>      <td>0.957920</td>      <td>NaN</td>      <td>0.728265</td>      <td>0.916599</td>      <td>0.286137</td>    </tr>    <tr>      <th>0.711955</th>      <td>0.091902</td>      <td>0.951715</td>      <td>NaN</td>      <td>0.363268</td>      <td>0.344484</td>      <td>0.661254</td>    </tr>  </tbody></table>

```
dfPP=dfPP.interpolate(method='values',axis=1)
dfPP.head()
```

<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>0.211451507884</th>      <th>0.574409309122</th>      <th>0.626609642735</th>      <th>0.728622716072</th>      <th>0.752814445643</th>      <th>0.865750234955</th>    </tr>  </thead>  <tbody>    <tr>      <th>0.340822</th>      <td>0.451636</td>      <td>0.292137</td>      <td>0.248244</td>      <td>0.162465</td>      <td>0.481506</td>      <td>0.384237</td>    </tr>    <tr>      <th>0.996621</th>      <td>0.997825</td>      <td>0.957920</td>      <td>0.880183</td>      <td>0.728265</td>      <td>0.916599</td>      <td>0.286137</td>    </tr>    <tr>      <th>0.711955</th>      <td>0.091902</td>      <td>0.951715</td>      <td>0.752529</td>      <td>0.363268</td>      <td>0.344484</td>      <td>0.661254</td>    </tr>  </tbody></table>

**Comment by jreback** [comment]
pls provide an example of what you are looking in the top of the issue

**Comment by denfromufa** [comment]
provided the example above, so the new optional arguments are the following:

DataFrame.interpolate(new_columns=[x,y,z], new_rows=[a,b,c], *args, **kwargs)

**Comment by mroeschke** [comment]
Thanks for the suggestion, but since there hasn't been much community or core dev interest in years going to close. Happy to reopen if there's renewed interest
