### ISSUE TITLE
Pandas ExcelWriter set_column fails to format numbers after DataFrame.to_excel used

### ISSUE THREAD

**Issue by phaefele** [pandas-dev/pandas#10112]
I have tried the example code found on the xlsxwriter webpage at http://xlsxwriter.readthedocs.org/en/latest/example_pandas_column_formats.html

However it does not format the columns as expected - they simply appear unformatted (no numeric rounding, percentages.)

It seems that calling set_column is being ignored. Is this because perhaps not to_excel() is doing some formatting itself which can't be overwritten?

**Comment by phaefele** [comment]
Actually, this seems to have been fixed in 16.0 according to the xlsxwriter website. See https://github.com/jmcnamara/XlsxWriter/issues/204

**Comment by phaefele** [comment]
I upgraded to Pandas 0.16.1 (2.7 Anaconda) and this issue still exists. The same code on the link above does not work. I can see the patch change in the excel.py file, so not sure whats wrong in this version.

**Comment by phaefele** [comment]
Oddly, it seems that I had changed the to_excel() method slightly while trying to get it working. So the bug is a little more specific.

So it seems that if you include 'header=False, index =False' in the to_excel() method, then the formatting fails in the example. If you exclude these parameters, then formatting works fine after to_excel().

**Comment by mroeschke** [comment]
Looks like the link doesn't lead to the reproducible example anymore. Happy to reopen if there's a reproducible example
