### ISSUE TITLE
BDay and bday confusion.

### ISSUE THREAD

**Issue by harshnisar** [pandas-dev/pandas#10144]
Are BDay and bday the same? Is one of them deprecated or something?

```
In [48]: pd.datetools.BDay?
Init signature: pd.datetools.BDay(self, n=1, normalize=False, **kwds)
Docstring:      DateOffset subclass representing possibly n business days
File:           c:\python27\lib\site-packages\pandas\tseries\offsets.py
Type:           type

In [49]: pd.datetools.bday?
Type:           BusinessDay
String form:    <BusinessDay>
File:           c:\python27\lib\site-packages\pandas\tseries\offsets.py
Signature:      pd.datetools.bday(self, other)
Docstring:      DateOffset subclass representing possibly n business days
Call signature: pd.datetools.bday(other)
```

**Comment by rockg** [comment]
They seem to be exactly the same--[see here](https://github.com/pydata/pandas/blob/master/pandas/core/datetools.py#L8).  In that file are many other aliases for the "real" date offsets.  Personally I don't see the reason for having these other names.

**Comment by jreback** [comment]
these are just aliases, I don't know exactly where they came from, but suspect ``scikit-timeseries``. In theory we should remove them. 

@harshnisar want to add deprecation warnings to all of these?

**Comment by harshnisar** [comment]
@jreback Would love too though you would need to help me a little. I have been waiting to find an entry point so that I could give back to Pandas. 

Will the warnings be thrown by the code when the particular method is called or a warning in the documentation?

**Comment by rockg** [comment]
The warnings will be thrown when the code is called.  We will only keep the ones in `tseries.offsets` so deprecate all the ones in datetools.  You should be able to just use `pandas.util.decorators:deprecate` to do this.  Also, for help on contributing look [here](http://pandas.pydata.org/pandas-docs/version/0.16.1/contributing.html).

**Comment by harshnisar** [comment]
@rockg 
I setup the environment and everything is working. 
I am currently doing this,
```
#day = DateOffset()
day = deprecate('day', DateOffset)
# bday = BDay()
bday = deprecate('bday', BDay)
# businessDay = bday
businessDay = deprecate('businessDay', BDay)
```
The commented code is the one the existed before. Is the the right way of doing it?

On calling bday, businessDay and day.
```
In [4]: pd.datetools.bday()
pandas\util\decorators.py:13: FutureWarning: bday is deprecated. Use BusinessDay instead
  FutureWarning)
Out[4]: <BusinessDay>

In [5]: pd.datetools.businessDay()
pandas\util\decorators.py:13: FutureWarning: businessDay is deprecated. Use BusinessDay instead
  FutureWarning)
Out[5]: <BusinessDay>

In [6]: pd.datetools.day()
pandas\util\decorators.py:13: FutureWarning: day is deprecated. Use DateOffset instead
  FutureWarning)
Out[6]: <DateOffset>
```
So, the user should be using pd.datetools.BusinessDay right?

**Comment by harshnisar** [comment]
So, I deprecated the other straight aliases too. 
Which are,
```
monthEnd = deprecate('monthEnd', MonthEnd)
yearEnd = deprecate('yearEnd', YearEnd)
yearBegin = deprecate('yearBegin', YearBegin)
bmonthEnd = deprecate('bmonthEnd', BMonthEnd)
bmonthBegin = deprecate('bmonthBegin', BMonthBegin)
cbmonthEnd = deprecate('cbmonthEnd', customBusinessMonthEnd)
cbmonthBegin = deprecate('cbmonthBegin', customBusinessMonthBegin)
bquarterEnd = deprecate('bquarterEnd', BQuarterEnd)
quarterEnd = deprecate('quarterEnd', QuarterEnd)
byearEnd = deprecate('byearEnd', BYearEnd)
week = deprecate('week', Week)
```

What should I do about these two sections?
```
# Functions/offsets to roll dates forward
thisMonthEnd = MonthEnd(0)
thisBMonthEnd = BMonthEnd(0)
thisYearEnd = YearEnd(0)
thisYearBegin = YearBegin(0)
thisBQuarterEnd = BQuarterEnd(0)
thisQuarterEnd = QuarterEnd(0)

# Functions to check where a date lies
isBusinessDay = BDay().onOffset
isMonthEnd = MonthEnd().onOffset
isBMonthEnd = BMonthEnd().onOffset
```
and,

```
try:
    cday = CDay()
    customBusinessDay = CustomBusinessDay()
    customBusinessMonthEnd = CBMonthEnd()
    customBusinessMonthBegin = CBMonthBegin()
except NotImplementedError:
    cday = None
    customBusinessDay = None
    customBusinessMonthEnd = None
    customBusinessMonthBegin = None
```

@jreback  @rockg  ?
Apologies, if these are completely naive questions.

**Comment by rockg** [comment]
Personally I think you can get rid of everything except isBusinessDay, isMonthEnd, isBMonthEnd.  Those are more esoteric than the others and I think it's worth having them around (unless there is something in `offsets` for those helper functions).

**Comment by harshnisar** [comment]
@rockg 
When I was trying to deprecate the following function I hit an error.
```
thisMonthEnd = MonthEnd(0)
```
The error which gets thrown, 
```
C:\Users\Personal\Programming\pandas-harshnisar\pandas\core\datetools.py in <module>()
     37
     38 # Functions/offsets to roll dates forward
---> 39 thisMonthEnd = deprecate('thisMonthEnd', MonthEnd(0))
     40 thisBMonthEnd = BMonthEnd(0)
     41 thisYearEnd = YearEnd(0)

C:\Users\Personal\Programming\pandas-harshnisar\pandas\util\decorators.pyc in deprecate(name, alternative, alt_name)
      7
      8 def deprecate(name, alternative, alt_name=None):
----> 9     alt_name = alt_name or alternative.__name__
     10
     11     def wrapper(*args, **kwargs):

AttributeError: 'MonthEnd' object has no attribute '__name__'
```

I was assuming that calling MonthEnd with 0 as a parameter probably returns another method which we want to reference with the variable thisMonthEnd. But looking at the code for MonthEnd, I am not sure what is really happening and how is it returning a method. These concepts are new to me, but it seems interesting!

Here is the MonthEnd function from offsets.py
```
class MonthEnd(MonthOffset):
    """DateOffset of one month end"""

    @apply_wraps
    def apply(self, other):
        n = self.n
        _, days_in_month = tslib.monthrange(other.year, other.month)
        if other.day != days_in_month:
            other = other + relativedelta(months=-1, day=31)
            if n <= 0:
                n = n + 1
        other = other + relativedelta(months=n, day=31)
        return other

    def onOffset(self, dt):
        if self.normalize and not _is_normalized(dt):
            return False
        days_in_month = tslib.monthrange(dt.year, dt.month)[1]
        return dt.day == days_in_month

    _prefix = 'M'
```

@rockg  can you help me just a tiny bit more?

**Comment by rockg** [comment]
The `deprecate` decorate won't work with this particular case as it returns an instance rather than a class.  For this specific instance, it may be worth putting a specific deprecation function in the datetools library for these.  Basically you just want to return `alternative` rather than calling `alternative(*args, **kwargs)`.  I don't think that will cause any consternation and it's just for the deprecation cycle.

**Comment by mroeschke** [comment]
Looks like the lowercase versions don't exist anymore, so closing
