### ISSUE TITLE
CLN: consolidate Series.quantile / DataFrame.quantile

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#10207]
these can be moved to `core.generic.NDFrame.quantile` (leave disabled for ndim > 2 though)
xref #10174

**Comment by jbrockmendel** [comment]
Series implementation now dispatches to DataFrame.  Looking at it, I don't think trying to combine them further would improve clarity.  Closable?

**Comment by TomAugspurger** [comment]
I think so.
