### ISSUE TITLE
API: Support Matrix Multiplication Ops (@)

### ISSUE THREAD

**Issue by sinhrks** [pandas-dev/pandas#10259]
Python 3.5 is being released on Sep.13. Maybe we can wait for v0.17?
- http://legacy.python.org/dev/peps/pep-0465/
- numpy fix: https://github.com/numpy/numpy/pull/5878/

**Comment by jreback** [comment]
we need Travis to support 3.5 before can do this
iirc for 3.4 this support took some time

**Comment by shoyer** [comment]
We can certainly test `@` by calling `__matmul__` explicitly.

But we certainly should wait until numpy 1.10 is out -- until then we don't even have a `np.matmul` implementation to use internally.

**Comment by charris** [comment]
Note that the current numpy implementation does not support object arrays.

**Comment by bnaul** [comment]
I was a bit surprised to find that this isn't already supported since I've gotten so used to `@` in numpy. This case seems a bit simpler since there's no analog of scalars; does that mean that just setting `__matmul__ = dot` is sufficient or am I missing some other subtlety?

**Comment by shoyer** [comment]
> does that mean that just setting __matmul__ = dot is sufficient or am I missing some other subtlety?

There is a small amount of subtlety in returning `NotImplemented` when the other argument is the wrong type (standard for binary operators), but yes this is should be pretty straightforward.

**Comment by charris** [comment]
Note that `@` and `dot` broadcast differently. I don't know if that means anything for pandas ...

**Comment by shoyer** [comment]
In pandas we only have 1D and 2D data structures (ignoring Panel, which is deprecated), so the broadcasting behavior is irrelevant.
