### ISSUE TITLE
BUG: week strftime %W, %U / Week dates

### ISSUE THREAD

**Issue by zefijsd** [pandas-dev/pandas#10315]
```
pd.DatetimeIndex(['1976-W53'])
--> DateParseError: unknown string format
```

I tried to solve this with many libraries (dateutil, arrow, chrono, dt8601) and no one worked excepted this one : http://www.egenix.com/products/python/mxBase/mxDateTime/

```
import mx
mx.DateTime.ISO.ParseWeek("1976-W53").pydatetime()
-->  datetime.datetime(1976, 12, 27, 0, 0)
```

And this one also : https://aniso8601.readthedocs.org/en/v1.0.0/

```
import aniso8601
aniso8601.parse_date('1976-W53')
--> datetime.date(1976, 12, 27)
```

As the guideline require it :

```
pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.2.final.0
python-bits: 64
OS: Darwin
OS-release: 12.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: fr_FR.UTF-8

pandas: 0.16.1
nose: 1.3.6
Cython: None
numpy: 1.9.2
scipy: 0.15.1
statsmodels: None
IPython: 3.1.0
sphinx: 1.3.1
patsy: 0.3.0
dateutil: 2.4.2
pytz: 2015.4
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.3.1
openpyxl: 1.8.6
xlrd: None
xlwt: None
xlsxwriter: 0.5.7
lxml: 3.4.3
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 0.9.9
pymysql: 0.6.2.None
psycopg2: 2.4.5 (dt dec pq3 ext)
```

**Comment by jreback** [comment]
this is not supported, but I suppose could be added. pull-requests welcome.

**Comment by hayd** [comment]
It's surprising that `%W` doesn't appear to work as a date directive (it just fails silently). Nor does `%U`!

I guess that's a slightly different bug, but you'd expect to be able to parse with:
```
In [22]: pd.to_datetime(['1976-W53'], format="%Y-W%U")
Out[22]: DatetimeIndex(['1976-01-01'], dtype='datetime64[ns]', freq=None)

In [23]: pd.to_datetime(['1976-W53'], format="%Y-W%W")
Out[23]: DatetimeIndex(['1976-01-01'], dtype='datetime64[ns]', freq=None)
```

**Comment by jreback** [comment]
@hayd its in the TimeRE table, but must not be tested.

**Comment by hayd** [comment]
@jreback Thanks for the pointer! So it works if the day of the week is specified:
```
In [30]: pd.to_datetime(['1976-W5-D3'], format="%Y-W%W-D%w")
Out[30]: DatetimeIndex(['1976-02-04'], dtype='datetime64[ns]', freq=None)
```
so I guess the workaround is to add -0 and parse that as %w.

---

this looks like a logic error here (should we set a default if one of dow or woy is -1) https://github.com/pydata/pandas/blob/5f524d61fd336b850d34f13d5ffb2b6136073f21/pandas/tslib.pyx#L3584-L3589

or should something like this raise? (certainly it should not just ignore the flag!)

```
In [33]: pd.to_datetime(['1976-D6'], format="%Y-D%w")
Out[33]: DatetimeIndex(['1976-01-01'], dtype='datetime64[ns]', freq=None)
```

**Comment by mroeschke** [comment]
I think these were added a while back when using format. 

```
base.__setitem__('W', base.__getitem__('U').replace('U', 'W'))
```

And a certain combination raises now

```
        if '%W' in fmt or '%U' in fmt:
            if '%Y' not in fmt and '%y' not in fmt:
                raise ValueError("Cannot use '%W' or '%U' without day and year")
            if '%A' not in fmt and '%a' not in fmt and '%w' not in fmt:
                raise ValueError("Cannot use '%W' or '%U' without day and year")
```

I think this is closeable but happy to reopen if not.
