### ISSUE TITLE
rolling_mean returns small negative value on Series with non-negative values

### ISSUE THREAD

**Issue by ahu2012** [pandas-dev/pandas#10319]
We came upon this issue today while trying to take a square root of a non-negative series. 

A quick search came up with this old issue: https://github.com/pydata/pandas/issues/2527.The issue was reproduced on 0.15 by tweaking the code from the previous report, which is below:

```
from pandas import date_range, Series
s = Series(index=date_range('1999-02-03','1999-04-05'))
s['1999-02-03'] = 0.00012456
s['1999-02-04'] = 0.0003
s['1999-04-04'] = -0.0
s['1999-04-05'] = -0.0
In [21]: s.rolling(1).mean()['1999-04-05']
Out[21]: -5.421010862427522e-20
```

which returns -5.4210108624275222e-20.

**Comment by jreback** [comment]
does seem odd, but the value is indistinguishable from 0. so this is probably a round effect somewhere in cython. I'll mark it, but would need someone to deep dive into the [code](https://github.com/pydata/pandas/blob/master/pandas/algos.pyx#L910)

```
In [43]: np.allclose([pd.rolling_mean(s, 1)['1999-04-05']],[0.0],atol=1e-20)
Out[43]: False

In [45]: np.allclose([pd.rolling_mean(s, 1)['1999-04-05']],[0.0],atol=1e-19)
Out[45]: True
```
