### ISSUE TITLE
Groupby with multiple frames

### ISSUE THREAD

**Issue by bwillers** [pandas-dev/pandas#10320]
Perhaps there is some canonical way of doing this that I'm not aware of, but from time to time I find myself wanting to group more than one frame by a key, and apply some function to the result. At the moment, I'm doing this in a somewhat roundabout way:

```
results = []
for key, t1 in table1.groupby(level='id'):
    try:
        t2 = table2.xs(key, level='id')
    except KeyError:
        t2 = None
    try:
        t3 = table3.xs(key, level='id')
    except KeyError:
        t3 = None
    # ... etc
    r = some_func(t1, t2, t3)
    results.append(r)
results = pd.concat(results)
```

I realize that often the easiest thing to do is just to merge the frames, but there are cases where that doesn't really make sense (e.g. non-compatible multiindexes that share one level). I imagine `pd.merge(t1, t2, on="id")` already does something like this to line up tables - do you guys think there is any value in exposing a standard way of doing this? Perhaps something like:

```
pd.multi_frame_groupby([t1, t2, t3, t4], level='id').apply(some_func)
```

Or, given that the full behaviour of such a groupby object is non trivial, perhaps just a generator for frame tuples?

```
gen = pd.multi_frame_groupby([t1, t2, t3, t4], level='id')
pd.concat([some_func(*t) for t in gen])
```

**Comment by jreback** [comment]
@bwillers perhaps show an example where you cannot merge the frames. That is the most canonical & efficient method. What you should above is really just a *for* loop, not taking advantage of any of pandas efficiencies.

**Comment by bwillers** [comment]
@jreback True it really just a for loop, but wasn't sure if this was something other people find themselves doing with any regularity.

Slightly contrived example with random numbers/domain:

    print(census)
                              bikes   cars  population
    city        neighborhood                          
    Mexico City awful         21704  28499       77729
                geography     22549  39323       65921
                is            34059  75053       53994
                my            35892   2669       19428
    Seattle     awful         28043  25532       21727
                geography     24914  -4245       84771
                is            25113  46743       74282
                my            32519  40379       50789

    print(weather)
                                rain      wind
    city        date                          
    Mexico City 2002-04-17  0.026612  0.669639
                2002-10-16  0.003745  0.251635
                2003-06-03  0.313699  0.275628
                2003-08-03  1.265956  0.204420
                2005-03-12  4.795716  0.016668
                2005-07-15  0.161919  0.026317
                2005-08-05  2.802568  1.781364
                2006-01-24  2.758856  0.298177
                2006-05-20  2.095423  1.155400
                2007-01-21  2.279899  0.050688
                2007-07-08  0.330846  0.696462
    Seattle     2002-02-13  1.295050  1.104200
                2003-05-05  0.166942  0.807315
                2003-09-07  1.673502  0.016926
                2004-09-05  0.832192  0.924529
                2004-12-10  0.402471  0.561248
                2005-04-10  5.945603  1.281094
                2007-09-16  0.964379  0.162256
                2008-09-18  0.054571  0.248187
                2009-07-08  0.363382  1.497879

Now, you could merge those by basically broadcasting across the missing level, but if one of these tables becomes large (in reality I'm dealing with 10M + rows), the amount of duplication involved in that broadcast becomes enormous.

**Comment by jreback** [comment]
can you put up a copy-pastable example of the setup code (can of course be completely random data, just the structure should be what you want), and example of output and your work-around.

**Comment by mroeschke** [comment]
Would need this request to be more well scoped with setup and example output. Closing for now but happy to have a new issue with details
