### ISSUE TITLE
CLN: Series.asof

### ISSUE THREAD

**Issue by bwillers** [pandas-dev/pandas#10343]
As discussed in #10266 `Series.asof` is effectively equivalent to `s.dropna().reindex(where, method='ffill')`.  The implementation of `Series.asof` uses `Index.asof_locs`, which is used no where else in the code, and is untested. So deprecating `Series.asof` might make sense.

Let's add the impls discussed (IOW, implement `.asof` in terms of reindexing internally). Further let's add tests for `.asof_locs` (though this maybe abel to tbe removed)

**Comment by jbrockmendel** [comment]
We have decent tests for Index.asof and DatetimeIndex.asof.  Closing.
