### ISSUE TITLE
doc/make.py only works for development build

### ISSUE THREAD

**Issue by pwm1234** [pandas-dev/pandas#10340]
doc/make.py contains the statement `os.environ['PYTHONPATH'] = '..'`, which means it will only work with an inplace build. I need to be able to contribute to pandas documentation using an installed version of pandas. When I comment out this line, I am able to build the html documentation from source. 

See this [SO question](http://stackoverflow.com/questions/30807270) for background and details.

**Comment by jorisvandenbossche** [comment]
@pwm1234 Does it work if you comment out that one line?

**Comment by pwm1234** [comment]
Yes, I am able to build the documentation using my installed pandas when I comment out that line.

**Comment by datapythonista** [comment]
Is this something we want to fix? I can add an option --no-local-pandas (or whatever name makes sense), and don't overwrite the python path, but I don't know if generating the documentation with a different version of pandas makes sense.
