### ISSUE TITLE
BUG: STD modifies groupby target column when as_index=False

### ISSUE THREAD

**Issue by jxrossel** [pandas-dev/pandas#10355]
xref #14547 for other tests

In pandas 0.16.2 (and already in 0.16.0), using std() for aggregation after a groupby( 'my_column', as_index=False) modifies 'my_column' by taking its sqrt(). Example:

``` python
df = pandas.DataFrame({
               'a' : [1,1,1,2,2,2,3,3,3],
               'b' : [1,2,3,4,5,6,7,8,9],
})
df.groupby('a',as_index=False).std()
Out[5]: 
          a  b
0  1.000000  1
1  1.414214  1
2  1.732051  1
```

The square root values of 'a' are returned instead of 1, 2, 3.
## INSTALLED VERSIONS

commit: None
python: 2.7.9.final.0
python-bits: 32
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 45 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: fr_CH

pandas: 0.16.2
nose: 1.3.4
Cython: 0.22
numpy: 1.9.2
scipy: 0.15.1
statsmodels: None
IPython: 3.0.0
sphinx: 1.3.1
patsy: 0.3.0
dateutil: 2.4.0
pytz: 2015.2
bottleneck: None
tables: 3.1.1
numexpr: 2.4
matplotlib: 1.4.3
openpyxl: None
xlrd: 0.9.3
xlwt: None
xlsxwriter: 0.7.1
lxml: None
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 0.9.9
pymysql: None
psycopg2: None

**Comment by jreback** [comment]
Something like this would fix it. care to do a pull-requests (and add some tests)?

```
diff --git a/pandas/core/groupby.py b/pandas/core/groupby.py
index 4abdd11..3fd2436 100644
--- a/pandas/core/groupby.py
+++ b/pandas/core/groupby.py
@@ -1812,6 +1812,10 @@ class BinGrouper(BaseGrouper):
         'min': 'group_min_bin',
         'max': 'group_max_bin',
         'var': 'group_var_bin',
+        'std': {
+            'name' : 'group_var_bin',
+            'f' : lambda func, a: np.sqrt(func(a)),
+            },
         'ohlc': 'group_ohlc',
         'first': {
             'name': 'group_nth_bin',
```

**Comment by jxrossel** [comment]
Hi,
I'm kind of a newbie here (and in Python in general). What do you mean by pull-request ?

**Comment by jreback** [comment]
see contributing docs [here](http://pandas.pydata.org/pandas-docs/stable/contributing.html)

**Comment by jxrossel** [comment]
woaw, I didn't consider becoming a code contributer when mentioning the bug. I don't think I would be the correct person for that. I'd probably do more damage than good.

**Comment by jreback** [comment]
best way to start! give it a shot.

**Comment by jorisvandenbossche** [comment]
Other case were it raises an error (when grouping by non-numerical columns): https://github.com/pandas-dev/pandas/issues/16799

**Comment by jreback** [comment]
I put a patch that might work, needs tests, see the contributing docs here:http://pandas-docs.github.io/pandas-docs-travis/contributing.html

**Comment by TakaakiFuruse** [comment]
This code returns  "ValueError: cannot insert a, already exists" error on pandas 0.22 with python 3.6.4.

```
import pandas as pd
df = pd.DataFrame({
               'a' : [1,1,1,2,2,2,3,3,3],
               'b' : [1,2,3,4,5,6,7,8,9],
})
df.groupby('a', as_index=False).agg({'a': 'count'})
```
Do you think the root cause is the same?

**Comment by TakaakiFuruse** [comment]
For https://github.com/pandas-dev/pandas/issues/10355#issuecomment-377673535, as I have found another similar behavior, I have created a new issue here https://github.com/pandas-dev/pandas/issues/20566.

**Comment by mukherjees** [comment]
I can confirm the same problem as reported by @TakaakiFuruse (see two posts above), with pandas 0.22 and python 3.6.2.  With the same example dataframe as he has, we see that the `describe()` command applied to the `groupby` object shows the correct results in the `std` columns for both `a` and `b`:
`df.groupby('a', as_index=False).describe()`
```
	a	a	a	a	a	a	a	a	b	b	b	b	b	b	b	b
	count	mean	std	min	25%	50%	75%	max	count	mean	std	min	25%	50%	75%	max
0	3.0	1.0	0.0	1.0	1.0	1.0	1.0	1.0	3.0	2.0	1.0	1.0	1.5	2.0	2.5	3.0
1	3.0	2.0	0.0	2.0	2.0	2.0	2.0	2.0	3.0	5.0	1.0	4.0	4.5	5.0	5.5	6.0
2	3.0	3.0	0.0	3.0	3.0	3.0	3.0	3.0	3.0	8.0	1.0	7.0	7.5	8.0	8.5	9.0
```

However, applying `std()` directly to the `groupby` object gives the wrong result for `a`:
`df.groupby('a', as_index=False).std()`
```
	a	b
0	1.0	1.0
1	1.4142135623730951	1.0
2	1.7320508075688772	1.0
```

Clearly, `std()` is not the same as `.apply(np.std, ddof=1)` [even though I thought that they were syntactically equivalent] because the latter again gives the right answer for both `a` and `b`:
`df.groupby('a', as_index=False).apply(np.std, ddof=1)`
```
	a	b
0	0.0	1.0
1	0.0	1.0
2	0.0	1.0
```
