### ISSUE TITLE
ENH: Add `categorize` method to Categoricals

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#10374]
I may be missing an existing method here. Didn't see anything though...

Given a Categorical

``` python
In [10]: s = pd.Series(['A', 'B', 'C', 'A'], dtype='category')

In [11]: s
Out[11]:
0    A
1    B
2    C
3    A
dtype: category
Categories (3, object): [A, B, C]
```

And some codes, `new_codes = pd.Series([0, 1, 0, 2], index=[4, 5, 6, 7])`, I'd like to easily categorize the new codes. I think this is essentially

``` python
In [22]: catmap = dict(enumerate(s.cat.categories))

In [23]: new_codes.map(catmap).astype('category')
Out[23]:
4    A
5    B
6    A
7    C
dtype: object
```

That's not quite the same (what if `new_codes` doesn't have every code from `s`, then it's "missing"? need to make sure the categories / codes are identical), but the basic idea is there.

---

My use-case here is going from Categorical -> codes -> scikit-learn classifier -> prediction (codes). It'd be nice if the column could easily transform that result back.

Naming wise, I'd say `categorize` or `decode`. Should we also add the symmetrical `encode` method for `category` to `code`?

If `new_codes` contains a previously unseen `code` I'd say raise, or maybe insert nan (perhaps an option here?)

**Comment by TomAugspurger** [comment]
Hmm, just saw `pd.Categorical.from_codes` in the docs. So it'd be `pd.Categorical.from_codes(new_codes, s.cat.categories)`, which isn't terrible to type. Just wasn't the first place I looked. I'll close this unless anyone else thinks adding essentially that method to the `.cat` accessor, just with `categories` already assigned, would be useful.

**Comment by jreback** [comment]
This is how I would do it (currently a bug reports here #10324) 

```
In [40]: new_codes.map(s)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-40-f6a8e88422bb> in <module>()
----> 1 new_codes.map(s)

/Users/jreback/pandas/pandas/core/series.pyc in map(self, arg, na_action)
   2010 
   2011             indexer = arg.index.get_indexer(values)
-> 2012             new_values = com.take_1d(arg.values, indexer)
   2013             return self._constructor(new_values,
   2014                                      index=self.index).__finalize__(self)

/Users/jreback/pandas/pandas/core/common.pyc in take_nd(arr, indexer, axis, out, fill_value, mask_info, allow_fill)
    829         out_shape[axis] = len(indexer)
    830         out_shape = tuple(out_shape)
--> 831         if arr.flags.f_contiguous and axis == arr.ndim - 1:
    832             # minor tweak that can make an order-of-magnitude difference
    833             # for dataframes initialized directly from 2-d ndarrays

AttributeError: 'Categorical' object has no attribute 'flags'
```

**Comment by kokes** [comment]
@jreback the bug has been resolved, so your proposed solution works just fine, should this be closed? Not sure if there's a need for additional APIs for this.

**Comment by jreback** [comment]
yep this looks good.
