### ISSUE TITLE
BUG: DataFrame.to_hdf doesn't pass along min_itemsize for index

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#10381]
Unless I'm seeing something wrong

``` python
In [21]: df = DataFrame(dict(A = 'foo', B = 'bar'),index=range(5)).set_index("A")

In [22]: df.to_hdf('store.h5', 'test', format='table', min_itemsize={'index': 10})

In [23]: store = pd.HDFStore('store.h5')

In [24]: store.get_storer('test').table
Out[24]:
/test/table (Table(5,)) ''
  description := {
  "index": StringCol(itemsize=3, shape=(), dflt=b'', pos=0),
  "values_block_0": StringCol(itemsize=3, shape=(1,), dflt=b'', pos=1)}   # <---- I think this should be 10
  byteorder := 'irrelevant'
  chunkshape := (10922,)
  autoindex := True
  colindexes := {
    "index": Index(6, medium, shuffle, zlib(1)).is_csi=False}
```

and FYI this raises (not sure if it should work)

``` python
In [25]: df.index.name = 'theindex'

In [26]: df.to_hdf('store.h5', 'test2', format='table', min_itemsize={'theindex': 10})
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
```

Just a report right now... no time.

**Comment by TomAugspurger** [comment]
FYI the solution [here](http://stackoverflow.com/questions/15988871/hdfstore-appendstring-dataframe-fails-when-string-column-contents-are-longer) works. Something like

```python
store.append('test', df, min_itemsize={'index': 30})
```

so it should just be a matter of passing along arguments.

**Comment by jreback** [comment]
I think maybe add to the docs a bit more [here](http://pandas.pydata.org/pandas-docs/stable/io.html#string-columns). This is like saying that the default for column A should be the same as B, which is not very explicit. 

That said it should work for ``min_itemsize=30`` (e.g. defaults all object columns)

**Comment by toobaz** [comment]
Notice that if I do

    ddf = pd.DataFrame([['a', 'b', 1],
                        ['a', 'b', 2]],
                        columns=['A', 'B', 'C']).set_index(['A', 'B'])

and then

    ddf['C'].to_hdf('/tmp/store.hdf', 'test',
              format="table",
              min_itemsize={'index' : 3})

(as far as I understand, the suggested workaround), I still get the error.

**Comment by toobaz** [comment]
Just for the records: the bug doesn't have to do with ``to_hdf()`` specifically, but rather with storing in ``table`` format without (explicitly) appending:

``store.put(df, 'key', format='table', min_itemsize={'index' : 10})``

will fail the same.

I'm pushing a PR in few seconds.
