### ISSUE TITLE
Incorrect usage of float16 in algos.pyx

### ISSUE THREAD

**Issue by FelipeLema** [pandas-dev/pandas#10382]
Hi, everyone

According to [documentation](http://docs.scipy.org/doc/numpy-dev/reference/c-api.coremath.html#half-precision-functions), `np.float16` should **not** be used in C code as it is right now in pandas/algos.pyx:38 (assigning `np.NINF` to a `np.float16` container in "cython-eventually-converted-to-C" code 

As a matter of fact, when this value/variable is exposed, it is exposed as `0.0`, and not `-inf`, either in C/C++ while using gdb or even with python.

Since `MINfloat6` it is not being used in all pandas code, I recommend eliminating this line and/or commentating the reason. I tried by using `np.float16(np.NINF)` but the problem is that a correct C `-inf` value is **still** being C-assigned to a please-don't-use-C-container.

Why is it that this is important to me/I got to find this error? I'm dealing with 3rd party code so I cannot get a configuration that allows me to do this assignment without raising SIGFPE.

No pull request? The two possible solutions to me is either using cython-kept-as-python code with just this variable (which would impact performance) or simply not using it at all. I think I don't have the authority for either.

**Comment by jreback** [comment]
xref #9220, #2511, #10046 

``np.float16`` is really not supported, so ok to simply remove it (I think it was just copy-pasted long time ago). But if you'd like to review the xref issues and provide a recommendation. thanks

**Comment by FelipeLema** [comment]
This is definately a duplicate of #10046. I just added another insight and a link to numpy's documentation.

**Comment by jreback** [comment]
@FelipeLema ok thanks!
