### ISSUE TITLE
Spline Interpolation Should Use InterpolatedUnivariateSpline

### ISSUE THREAD

**Issue by cancan101** [pandas-dev/pandas#10380]
The spline Interpolation should probably use `InterpolatedUnivariateSpline` rather than [`UnivariateSpline`](https://github.com/pydata/pandas/blob/821542fb1dfd55b0e0d25e55eb4fee6555d01cbd/pandas/core/common.py#L1737) as it does now.

For some discussion: https://github.com/scipy/scipy/issues/4975#issuecomment-112867854
Related: #10378

**Comment by jreback** [comment]
@TomAugspurger ?

**Comment by mroeschke** [comment]
Thanks for the request but it appears this hasn't gotten traction in a while so closing
