### ISSUE TITLE
Explore use of ReadStat for binary format read/write

### ISSUE THREAD

**Issue by jseabold** [pandas-dev/pandas#10517]
As mentioned in #4052. [ReadStat](https://github.com/WizardMac/ReadStat) is an MIT-licensed C library for reading and writing R, SAS, Stata, and SPSS binary files. [Haven](https://github.com/hadley/haven) uses it.

**Comment by jbrockmendel** [comment]
Closing and adding to a tracker issue #30407 for IO format requests, can re-open if interest is expressed.

**Comment by ofajardo** [comment]
[Pyreadstat](https://github.com/Roche/pyreadstat) is a python wrapper around Readstat to read and write SAS, Stata and SPSS. Actually pandas read_spss is already using it, therefore you could use it for SAS and Stata as well.
