### ISSUE TITLE
read_json from url, Accept Header?

### ISSUE THREAD

**Issue by MaxNoe** [pandas-dev/pandas#10526]
Today I tried to read json data from an url that checks the Accept-Header for 'application/json',
and only delivers json if this tag is higher ranked than 'text/html'.

See: [Flask: Handling Accept Headers](http://flask.pocoo.org/snippets/45/)
It seems, that the pandas request in '_url_open' has no such header at all.

This works:

``` python
import requests
import pandas
url = "http://localhost:5000/foo"
r = requests.get(url, headers={'Accept': 'application/json'})
data = pandas.DataFrame(r.json())
print(data.head())
```

This does not, and I checked the header in the flask webapp of the received request, it is empty:

``` python
import pandas
url = "http://localhost:5000/foo"
data = pandas.read_json(url)
print(data.head())
```

It would make sense if the `read_json` had `application/json` in its Accept-Header, correct?

**Comment by fconil** [comment]
Hi,

I have the same need for `read_csv` to use `text/csv` in `Accept-Header` when retrieving data from an URL.

Regards

**Comment by yuribak** [comment]
+1

**Comment by ron819** [comment]
It's more than that. There should be full support for header , data and verity
For example:
```
hed = {'Authorization': 'Bearer ' + auth_token, 'Accept': 'application/json'}
data = {"client_id": "...", "client_secret": "...",
            "grant_type": "client_credentials", "scope": "PublicApi"}
response = requests.get(url, data=data, headers=hed, verify=True)
```

The `read_json  `does not support this.

**Comment by albertonecosta** [comment]
https://zencash.miningpoolhub.com/index.php?page=api&action=getuserworkers&api_key=??????

**Comment by dmitrypol** [comment]
would be great if `read_json` supported passing headers.  Super useful to reading data from APs w/o having to leverage `requests`

**Comment by jreback** [comment]
close in favor of #36688
