### ISSUE TITLE
New feature: support timedelta as limit when using interpolate method=time

### ISSUE THREAD

**Issue by bertrandhaut** [pandas-dev/pandas#10533]
When we call the interpolate function based on time, it would be useful to be able to give a limit expressed as a timedelta (instead of a number of row).

Use case
- I've a time series measurement of temperature in function of time. The measurements are not performed at a constant frequency
- I want to interpolate missing data if the interpolation period is less than 1 hour.

**Comment by shoyer** [comment]
This is similar to the proposed `tolerance` argument for reindexing (#10411) -- I suspect the implementation would be pretty similar.

For now, you can work around this by first resampling to a constant time interval, and *then* applying the interpolation.

**Comment by mroeschke** [comment]
Seems like there hasn't been much interest in this feature over the years so closing
