### ISSUE TITLE
columns become "unlinked" from a DataFrame when a new row is created

### ISSUE THREAD

**Issue by parkus** [pandas-dev/pandas#10550]
...perhaps this is the desired behavior, but it is not at all what I expected and had me very confused for a good while as I tried to figure out why I suddenly couldn't change values in the DataFrame I was using like I always had before. 

Below is an MWE. Basically what happens is that if you assign a value to a row that did not previously exist, it get assigned to the row of that column, but then the DataFrame still seems to use the original column. That means that updating a value for a row that was in the original table doesn't update it in the DataFrame afterwards. 

```
>>> import pandas as pd
>>> from numpy import zeros
>>> df = pd.DataFrame(data=zeros([2,3]), index=['row1', 'row2'], columns=['col1' ,'col2', 'col3'])

>>> df
      col1  col2  col3
row1     0     0     0
row2     0     0     0

>>> df['col1']['row1'] = 1

>>> df
      col1  col2  col3
row1     1     0     0
row2     0     0     0

>>> df['col1']['row3'] = 2

>>> df
      col1  col2  col3
row1     1     0     0
row2     0     0     0

>>> df['col1']
row1    1
row2    0
row3    2
Name: col1, dtype: float64

>>> df['col1']['row2'] = 3

>>> df
      col1  col2  col3
row1     1     0     0
row2     0     0     0

>>> df['col1']
row1    1
row2    3
row3    2
Name: col1, dtype: float64
```

**Comment by sinhrks** [comment]
Thanks for the report. Pls use ``loc``:

```
df.loc['row3', 'col1'] = 2
df
#       col1  col2  col3
# row1     0     0     0
# row2     0     0     0
# row3     2   NaN   NaN
```

I think it should raise ``SettingWithCopyWarning``.

**Comment by jreback** [comment]
yes, this syntax of chained-indexing is NEVER recommended, and very hard to detect. It *maybe* is possible to show a ``SettingWithCopyWarning``, but ``.loc`` is the correct accessing method.

See the docs [here](http://pandas.pydata.org/pandas-docs/stable/indexing.html#returning-a-view-versus-a-copy)

**Comment by parkus** [comment]
Gotcha, one day I'll learn to read the docs! :)

Chained indexing just seemed so natural I didn't give it a second thought. Perhaps other light users will think the same?

Thanks for the responses! I'll leave it up to you folks if you want to leave this issue open or close it, but I consider it resolved on my end.

**Comment by mroeschke** [comment]
Closing as there are no guarantees with chained indexing
