### ISSUE TITLE
`Period(weekend_date, 'B')` returns Monday's Period

### ISSUE THREAD

**Issue by max-sixty** [pandas-dev/pandas#10575]
The [asof docs](http://pandas.pydata.org/pandas-docs/version/0.15.1/generated/pandas.Index.asof.html) state that the method should _return the most recent label up to and including the passed label_. For period indexes, this doesn't seem to be happening - if I supply a period of a weekend date to a weekday series, it returns the Monday, rather than the Friday. 

If I do the same on a DatetimeIndex, it behaves as expected

``` python
In [50]:
dates

Out[50]:
<class 'pandas.tseries.period.PeriodIndex'>
[1990-05-07, ..., 2015-07-13]
Length: 6568, Freq: B

In [51]:
dates_ts=dates.to_timestamp()
dates_ts

Out[51]:
<class 'pandas.tseries.index.DatetimeIndex'>
[1990-05-07, ..., 2015-07-13]
Length: 6568, Freq: None, Timezone: None

In [52]:
dates.asof('2015-07-11')

Out[52]:
Period('2015-07-13', 'B')

In [53]:
dates_ts.asof('2015-07-11')

Out[53]:
Timestamp('2015-07-10 00:00:00')
```

**Comment by sinhrks** [comment]
Thanks for the report!

Internally it uses ``get_loc`` and it also return different result. Because ``Period`` creates next valid date when passed date and freq is invalid, needs special handling in ``get_loc``. PR is appreciated:)

```
# DatetimeIndex
tidx = pd.date_range('2015-07-01', freq='B', periods=30)
tidx.get_loc('2015-07-19', method='pad')
# 12

# PeriodIndex
pidx = pd.period_range('2015-07-01', freq='B', periods=30)
pidx.get_loc('2015-07-19', method='pad')
# 13

pd.Period('2015-07-19', freq='B')
# Period('2015-07-20', 'B')
```

**Comment by maximilianr** [comment]
Is there a reason why it creates the next valid date rather than raising? While we could add a check in `get_loc`, the behavior we're correcting for seems unexpected.

**Comment by sinhrks** [comment]
I'm not sure whether there is a background of current ``Period`` behavior. It looks ``get_period_ordinal`` in ``period_helper.c`` doesn't care freqs with gaps.

@jreback @bjonen @cancan101 What do you think,  ```pd.Period('2015-07-20', 'B')``` (2015-07-20 is Saturday) should raise ``ValueError``?

**Comment by maximilianr** [comment]
@jreback @bjonen @cancan101, gentle follow up to @sinhrks's comment: do you have any thoughts here?

**Comment by maximilianr** [comment]
This hit us again today - @jreback do you have a view here? 
At worst "this isn't important" or "don't change anything" would be helpful!

**Comment by jreback** [comment]
Well, you have to have a policy for what to happend when you pass a non-supported freq to your frequency based ``Period``. I don't think rolling forward is that surprising. An alternative is what I gave in the other issue #10978 , e.g. move to a business day, then apply the op. ``to_period()`` just does this.

So I think ``.asof`` should as well, e.g. coerce the input to the appropriate frequency first.

**Comment by maximilianr** [comment]
OK. I agree with you for converting frequencies.

The concept of business days is a bit different - they have gaps. (I can't think of any other examples beyond business hours and some fanciful ones such as 'summer months'.)

So I don't think there's a concept of a business day representation of Saturday, while there is a month representation of '2010-01-01', or day representation of '2010-01'.

Although it may be that I'm alone in this view! If anyone else has thoughts + there's any consensus, happy to do a PR.

**Comment by mroeschke** [comment]
Period with "B" frequency is deprecated now so not sure if there are any action items here so closing
