### ISSUE TITLE
TST/BUG: some buggy windows tests

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#10631]
xref #10630 
- [x] csv parsing then turning into a recarray causing segfaults, only when run with the entire parsing tests (e.g. `test_parsing.py` (2 tests) (#13373)
- [ ] in `test_libsparse`, the test_intersect is segfaulting, not really sure why.
- [ ] in `test_ujson` with small exponentials, only on win-64 with 2.7.

**Comment by jreback** [comment]
cc @Komnomnomnom 
cc @mdmueller
cc @selasley

**Comment by jreback** [comment]
I don't think these are actually recent. Its also possible they only happen on my anaconda builds (these came to light when I turned on binstar). Though these ARE build with the correct visual studios, so not really sure what actually is the issue.

**Comment by chris-b1** [comment]
[`test_resample_group_info`](https://github.com/pydata/pandas/blob/master/pandas/tseries/tests/test_resample.py#L919)  and [`test_series_groupby_nunique`](https://github.com/pydata/pandas/blob/master/pandas/tests/test_groupby.py#L1619) fail for me on python 2.7 on win64 as below (passes on Travis); I haven't dug in to see what's going on.

    Attribute "dtype" are different
    [left]:  int32
    [right]: int64

**Comment by jreback** [comment]
@chris-b1 these are usually very easy changes. I have a windows ci, but don't always watch it.

if the tests does something like:

```
df = DataFrame({'A' : np.array(...)})
```

this will fail (say you are doing a resample or wahtever), because the ``np.array`` defaults to ``int32`` on windows. Soln is ``np.array(...., dtype='int64')``

**Comment by mroeschke** [comment]
Don't think this is relevant anymore.  `test_libsparse` isn't tested anymore and 2.7 isn't supported.
