### ISSUE TITLE
Output from get_dummies() should default to np.int8

### ISSUE THREAD

**Issue by johne13** [pandas-dev/pandas#10708]
The output columns from `get_dummies()` are binary by nature, changing this default from float64 to int8 would save 7 bytes per dummy.

```
df=pd.DataFrame({ 'x':[1,2,3] })
pd.get_dummies(df.x)
```

**Comment by bwillers** [comment]
Working on this now, hitting up against the fact that SparseDataFrame only supports floating point data... Shall we have it return uint8s for regular frames and float64s for sparse frames?

**Comment by Lunran** [comment]
Isn't this a duplicate of the following?
- BUG: dtype compat with get_dummies #8725
- BUG: int dtype for get_dummies #13796

**Comment by jreback** [comment]
yep looks that way.
