### ISSUE TITLE
COMPAT: see if we can use EnumCol to store Categoricals in HDFStore

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#10725]
http://www.pytables.org/usersguide/libref/declarative_classes.html#the-atom-class-and-its-descendants
- would have to ensure back-compat reading.
- `order` property would have to be retained in column meta data (IIRC this is how its done now)

**Comment by cel4** [comment]
I have put together a short proof of principle notebook: https://gist.github.com/cel4/efd78f79c4dbcb3acfd3

In principle this should just be a simple postprocessing step.

**Comment by mroeschke** [comment]
Appears this hasn't gotten traction in a while so closing
