### ISSUE TITLE
Pandas groupby histogram doesn't do transparant bars (alpha kwarg)

### ISSUE THREAD

**Issue by egpbos** [pandas-dev/pandas#10756]
I would expect the following code to produce a plot with transparent bars, but it doesn't.

``` python
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
plt.style.use('ggplot')

N = 1000

df = pd.DataFrame({
  'a': np.random.randint(0, 2, N),
  'b': np.random.random(N)
})

#df.groupby('a').b.hist(alpha=0.5)
df.groupby('a').b.plot(kind="hist", alpha=0.5)
plt.legend()
plt.show()
```

Neither the commented out `hist` command, nor the `plot` command works.

Version information from `pd.show_versions()`:
## INSTALLED VERSIONS

commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-46-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.16.2
nose: 1.3.7
Cython: 0.20.1post0
numpy: 1.9.2
scipy: 0.13.3
statsmodels: 0.5.0
IPython: 3.0.0
sphinx: None
patsy: 0.2.1
dateutil: 2.4.2
pytz: 2015.4
bottleneck: None
tables: 3.1.1
numexpr: 2.2.2
matplotlib: 1.4.3
openpyxl: 1.7.0
xlrd: 0.9.2
xlwt: 0.7.5
xlsxwriter: None
lxml: None
bs4: 4.2.1
html5lib: 0.999
httplib2: 0.8
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None

**Comment by TomAugspurger** [comment]
Thanks for the report. This works correctly for me in master. It seems like this was addressed in https://github.com/pydata/pandas/pull/8758 (which was pre 0.16.2, your version of pandas).

Could you try it out on master, and let me know if it's fixed for you? Otherwise, you can always iterate over the groupby object.

```python
gr = df.groupby('a').b
for k, v in gr:
    v.plot(kind='hist', alpha=.5, label=k)
```

**Comment by egpbos** [comment]
It doesn't work in master either.
![figure_1](https://cloud.githubusercontent.com/assets/6146598/9388403/5d6d44b2-4765-11e5-88f3-a6fced4c0058.png)

```
In [5]: pd.__version__
Out[5]: '0.16.2+385.g873bbc2'
```

**Comment by TomAugspurger** [comment]
![gh](https://cloud.githubusercontent.com/assets/1312546/9388575/f58e2b06-472b-11e5-9ce3-d1eb15254446.png) (from master pandas).

It's hard to say what's going on.

**Comment by egpbos** [comment]
Did you create that by pasting my code example or by using your suggestion of iterating over the groupby object? I tried now on three different systems (Ubuntu 14.04, Scientific Linux 6 and OS X 10.9.5) and it doesn't work on either (with my example). It does, indeed, work by iterating over the groupby object as you suggest. Still, I don't understand why it doesn't work for my code.

**Comment by TomAugspurger** [comment]
That was using your code.

**Comment by LindsayVass** [comment]
I have a very similar issue using a newer version of Pandas.

```
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
%matplotlib inline
plt.style.use('ggplot')

N = 1000

df = pd.DataFrame({
  'a': np.random.randint(0, 2, N),
  'b': np.random.random(N)
})

# alpha does not work
df.groupby('a').b.hist(alpha=0.5)
```

![image](https://cloud.githubusercontent.com/assets/11479770/13764119/6d89d97c-ea09-11e5-8bfa-5c439221031d.png)

```
# plot renders incorrectly
df.groupby('a').b.plot(kind = 'hist', alpha = 0.5);
```
![image](https://cloud.githubusercontent.com/assets/11479770/13764125/7ce3eff2-ea09-11e5-8a6c-3ee6763fd229.png)

```
# alpha works
df.groupby('a').b.plot.hist(alpha=0.5);
```
![image](https://cloud.githubusercontent.com/assets/11479770/13764129/87b73934-ea09-11e5-96b2-427510e55b28.png)


INSTALLED VERSIONS
------------------
commit: None
python: 2.7.10.final.0
python-bits: 64
OS: Darwin
OS-release: 14.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.17.1
nose: 1.3.7
pip: 8.0.2
setuptools: 19.2
Cython: 0.22.1
numpy: 1.10.4
scipy: 0.17.0
statsmodels: 0.6.1
IPython: 4.0.3
sphinx: 1.3.1
patsy: 0.3.0
dateutil: 2.4.2
pytz: 2013b
blosc: None
bottleneck: 1.0.0
tables: 3.2.0
numexpr: 2.4.3
matplotlib: 1.4.3
openpyxl: 1.8.5
xlrd: 0.9.3
xlwt: 1.0.0
xlsxwriter: 0.7.3
lxml: 3.4.4
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.5
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
Jinja2: None

**Comment by TomAugspurger** [comment]
@LindsayVass strange I still can't reproduce the bug :confused: 

Can you post a gist showing these rendering incorrectly? e.g. https://gist.github.com/2c7d666fd1c5d4bbe327

**Comment by LindsayVass** [comment]
@TomAugspurger So strange! Thanks for looking into this.

https://gist.github.com/LindsayVass/ed4aa46cf3223a7999a2

**Comment by TomAugspurger** [comment]
Ha, I had you make a notebook because I assumed you made a copy-paste error on your second graph. But nope :)

A couple things. It looks like that second graph with the crazy lines should be fixed by upgrading to pandas `0.18`.

For this bug, the `alpha` not taking, I've was able to reproduce it with python2 (matplotlib 1.4.3 or 1.50, pandas 0.17.2 or 0.18.0). I don't know offhand why that would matter. I won't have time to dig any more this week, but after that I'll follow up unless someone beats me to it.

**Comment by LindsayVass** [comment]
Haha, I would have assumed that too!

Confirm that upgrading to pandas 0.18 cleared up the problem with the crazy lines. New gist below.

https://gist.github.com/LindsayVass/0175d2f02e7e92b3013b

**Comment by egpbos** [comment]
On python3 `alpha` works for me as well.

However, I'm not sure if it's because of python3 or because I upgraded pandas to 0.18.0. I cannot exclude the latter, because I now get a segmentation fault (!) in python2 when I run `df.groupby('a').b.plot(kind="hist", alpha=0.5)`. I guess that's a separate issue from this one, though.

**Comment by egpbos** [comment]
Ok, seems like the segfault was related to #11487, reinstalling matplotlib fixed that.

Also in python2 `alpha` now works! Here are the changes to my updated package versions. Quite a few changes, so probably hard to say what eventually did the trick...

```diff
--- from_file
+++ commit: None
@@ -1,38 +1,44 @@
-python: 2.7.6.final.0
+python: 2.7.10.final.0
-OS-release: 3.13.0-46-generic
+OS-release: 4.2.0-35-generic

-pandas: 0.16.2
+pandas: 0.18.0
-nose: 1.3.7
+nose: None
-Cython: 0.20.1post0
+Cython: None
-numpy: 1.9.2
+numpy: 1.11.0
-scipy: 0.13.3
+scipy: 0.17.0
-statsmodels: 0.5.0
+statsmodels: None
-IPython: 3.0.0
+IPython: 4.0.0

+pip: 1.5.6
+setuptools: 20.4
+xarray: None

-patsy: 0.2.1
+patsy: None
-dateutil: 2.4.2
+dateutil: 2.5.2
-pytz: 2015.4
+pytz: 2016.3

+blosc: None

-tables: 3.1.1
+tables: None
-numexpr: 2.2.2
+numexpr: None
-matplotlib: 1.4.3
+matplotlib: 1.5.1
-openpyxl: 1.7.0
+openpyxl: None
-xlrd: 0.9.2
+xlrd: None
-xlwt: 0.7.5
+xlwt: None
-bs4: 4.2.1
+bs4: None
-httplib2: 0.8
+httplib2: None

+jinja2: 2.8
+boto: None
```

And here the complete output:

```
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.10.final.0
python-bits: 64
OS: Linux
OS-release: 4.2.0-35-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.18.0
nose: None
pip: 1.5.6
setuptools: 20.4
Cython: None
numpy: 1.11.0
scipy: 0.17.0
statsmodels: None
xarray: None
IPython: 4.0.0
sphinx: None
patsy: None
dateutil: 2.5.2
pytz: 2016.3
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None
```

**Comment by egpbos** [comment]
Actually, now I think about it, the problem might have been caused by using a virtualenv with `--system-site-packages`, I had problems with that before. I'm now using a clean virtualenv with `--no-site-packages` (as can be seen from the many `None` packages in the new list).

**Comment by prcastro** [comment]
@egpbos is this still an issue?

**Comment by egpbos** [comment]
Not sure, it's been a while, but probably not :)

**Comment by lstappen** [comment]
Unfortunately, it seems this issue is still existing:
    `df.groupby('labels').hist(ax=ax5, alpha=0.25)`
are overlapping but not transparent. I'm using jupyter which comes with anaconda and the issue is still there after reinstalling matplotlib/update all packages. Not sure what else I could try out to localise the problem...

> INSTALLED VERSIONS
> ------------------
> commit: None
> python: 2.7.14.final.0
> python-bits: 64
> OS: Linux
> OS-release: 4.10.0-37-generic
> machine: x86_64
> processor: x86_64
> byteorder: little
> LC_ALL: None
> LANG: en_GB.UTF-8
> LOCALE: None.None
> 
> pandas: 0.20.3
> pytest: 3.2.1
> pip: 9.0.1
> setuptools: 36.6.0
> Cython: 0.26.1
> numpy: 1.13.3
> scipy: 0.19.1
> xarray: None
> IPython: 5.4.1
> sphinx: 1.6.3
> patsy: 0.4.1
> dateutil: 2.6.1
> pytz: 2017.2
> blosc: None
> bottleneck: 1.2.1
> tables: 3.4.2
> numexpr: 2.6.2
> feather: None
> matplotlib: 2.1.0
> openpyxl: 2.4.8
> xlrd: 1.1.0
> xlwt: 1.3.0
> xlsxwriter: 1.0.2
> lxml: 4.1.0
> bs4: 4.6.0
> html5lib: 0.999999999
> sqlalchemy: 1.1.13
> pymysql: None
> psycopg2: 2.7.3.1 (dt dec pq3 ext lo64)
> jinja2: 2.9.6
> s3fs: None
> pandas_gbq: None
> pandas_datareader: None
>
