### ISSUE TITLE
to_cassandra(table, session)

### ISSUE THREAD

**Issue by rustyrazorblade** [pandas-dev/pandas#10765]
Adding cassandra support should be very similar to `to_sql()` but is different enough where I think it needs it's own call, as it wouldn't use SQLAlchemy or behave even remotely close.  

Python driver is here: https://github.com/datastax/python-driver 

Willing to help on this if it'll get pulled in.

**Comment by cpcloud** [comment]
This might be more suitable for ContinuumIO/odo. @rustyrazorblade thoughts on doing a PR there?

**Comment by rustyrazorblade** [comment]
Is all future work on interacting with different Databases going to the odo project?  I don't mind doing the PR there - I just want to make sure Cassandra is a first class citizen in the Pandas world.

**Comment by cpcloud** [comment]
> Is all future work on interacting with different Databases going to the odo project?

Not sure.

Pros:
* Odo's entire job is converting things to other things and is built with extensibility in mind. Pandas IO system isn't extensible without tacking on a new method.
* As soon as you hook into the odo graph you get conversion to nearly every other file format without having to write any additional code

Cons:
* Pandas has a lot of users, odo doesn't
* By extension, Pandas has familiar interface and odo doesn't

**Comment by rustyrazorblade** [comment]
I suspect having that functionality in odo is a good thing no matter what.  I'll take a look at it and see if I can get a PR in there for Cassandra.

**Comment by cpcloud** [comment]
@rustyrazorblade awesome! great to have more contributors there

**Comment by jreback** [comment]
@rustyrazorblade I think go ahead and contribute this to ``odo``. If it makes sense we can then port back to ``pandas``.

**Comment by jorisvandenbossche** [comment]
I think this is currently out of scope for core pandas, therefore closing this. 
But it would certainly make for a nice standalone package if someone is interested (and we may include some mechanism to plug such extension packages into pandas, see https://github.com/pandas-dev/pandas/issues/9378)

**Comment by kassett** [comment]
@mroeschke I see that the odo repository mentioned above has not been maintained for the last 7 or 8 years. I have personally implemented the to_cql functionality in several projects and think it would be tremendously useful to have it in Pandas, especially given that Cassandra has become very popular in the last few years. 
I have two questions
1. Can I implement this in Pandas?
2. Writing to Cassandra is incredibly slow if you don't implement multi-processing. Is this something that we are okay with doing in Pandas?

**Comment by mroeschke** [comment]
It's probably still too niche to belong in pandas, but if you create a Python package with it we can add it to the ecosystem docs
