### ISSUE TITLE
API: DatetimeIndex / TimedeltaIndex 2d slicing should result in Index

### ISSUE THREAD

**Issue by sinhrks** [pandas-dev/pandas#10774]
Following slices basically result in the same `Index`.

```
import pandas as pd
pd.Index([1, 2, 3])[:, None]
# Int64Index([[1], [2], [3]], dtype='int64')
pd.MultiIndex.from_tuples([('a', 1), ('b', 2)])[:, None]
# MultiIndex(levels=[[u'a', u'b'], [1, 2]],
#            labels=[[[0], [1]], [[0], [1]]])

pd.period_range('2011-01-01', freq='M', periods=3)[:, None]
# PeriodIndex(['2011-01', '2011-02', '2011-03'], dtype='int64', freq='M')
```

But `DatetimeIndex` and `TimedeltaIndex` doesn't because of following line.
- https://github.com/pydata/pandas/blob/master/pandas/tseries/base.py#L119

```
pd.date_range('2011-01-01', freq='M', periods=3)[:, None]
# array([['2011-01-31T09:00:00.000000000+0900'],
#        ['2011-02-28T09:00:00.000000000+0900'],
#        ['2011-03-31T09:00:00.000000000+0900']], dtype='datetime64[ns]')
pd.timedelta_range('1 days', freq='D', periods=3)[:, None]
# array([[ 86400000000000],
#        [172800000000000],
#        [259200000000000]], dtype='timedelta64[ns]')
```

I understand these must be `Index` also, or any reason for this?

**Comment by jreback** [comment]
prob an oversite

but not sure we should allow 2-d results at all
it's very odd (and I don't any utility)

**Comment by sinhrks** [comment]
Yep. Raise ``IndexError`` as the same as explicit 2 indices?

```
pd.Index([1, 2, 3])[:, 0]
# IndexError: too many indices for array
```

**Comment by jreback** [comment]
sounds right

**Comment by shoyer** [comment]
I noticed this the other day. I agree with @jreback that we should raise an IndexError if the result has two or more dimensions.

**Comment by MomIsBestFriend** [comment]
@jreback Since #31150 this is raising a Deprecation warning

https://github.com/pandas-dev/pandas/blob/b1214af3528319e31334ff098021c5a1a6d9ffcd/pandas/core/indexers.py#L263-L270

---

Should it raise an IndexError instead of a deprecation warning? (as was agreed above)

**Comment by mroeschke** [comment]
Since the 2D indexing behavior is currently deprecated, we should appropriately raise once this behavior is enforced. Closing but we can reopen if we don't get the correct behavior in the future.
