### ISSUE TITLE
TST/API: Simplify testing functions API

### ISSUE THREAD

**Issue by sinhrks** [pandas-dev/pandas#10788]
Derived from #10507. Consider better API for testing functions.
### 1. How to specify comparison tolerance

Current assert functions have `check_less_precise` and `check_exact` flags to specify how to compare values:
- `check_exact=True`: Use `assert_equal`, comparison using `==`.
- `check_exact=False` and `check_less_precise=False`: Use `assert_almost_equal`, comparing 5 digits after decimal points (default)
- `check_exact=False` and `check_less_precise=True`: Use `assert_almost_equal`, comparing 3 digits after decimal points

There can be single kw to specify above behaviors?
### 2. Make integrated assert  function

I think it's nice to have test functions which supports all `pandas` objects for users who is starting contribution / using pandas as their dependencies. Changing `assertEquals` and `assertAlmostEquals` to internally use current `assert_index/series/frame_equal` is one idea.
### 3. Remove `assert_almost_equal`

Remove `assert_almost_equal` and use class-based validation method. Also add input type validation to `numpy_assert_array_equal`.

xref #9895.

**Comment by kawochen** [comment]
I've seen multiple versions of 2 scattered across different test scripts, such as [this](https://github.com/pydata/pandas/blob/master/pandas/io/tests/test_packers.py#L31).  They might be good building blocks.

**Comment by jorisvandenbossche** [comment]
Regarding the **How to specify comparison tolerance**, I have two problems with the current interface:

- It is a bit clumsy, as you have two keywords that could perfectly fit into one keyword, making it a bit confusing.
- It is also not very flexible, as it only gives you the option to check all, 5 or 3 digits. For example, if you have values of different order in one frame (eg 0.0001 to 100), then the absolute number of digits cannot be used to check this but you need something relative. Therefore, you have to fall back to checking the `.values` with numpy.

Specifically for that last point, I think it is nice to look at [`np.testing.assert_allclose`](http://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.testing.assert_allclose.html) (which is now the recommended way in numpy according to the [`assert_array_almost_equal`](http://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.testing.assert_array_almost_equal.html) docstring), which uses both relative and absolute tolerance.

**Comment by sinhrks** [comment]
Added 3rd item, I think we should replace ``assert_almost_equal`` to precise functions as much.

**Comment by lucaslarios** [comment]
Take it

**Comment by mroeschke** [comment]
I think a lot of these have addressed in a meantime so closing
