### ISSUE TITLE
grouped.filter with dropna option

### ISSUE THREAD

**Issue by leo4183** [pandas-dev/pandas#10780]
in Pandas 0.16.2:

```
grouped = a.groupby(idx)
grouped.filter(lambda x: x.mean()>0.0, dropna=False)
```

in case there was no group whose `x.mean()` was larger than zero, an `AttributeError: 'list' object has no attribute 'astype'` would be raised (rather than returning an all `NaN` dataframe/serie in previous versions).

**Comment by jreback** [comment]
pls show a complete example that can be copy pasted

**Comment by leo4183** [comment]
a concrete example:

    row = 9
    a   = pd.Series(np.random.rand(row),index=np.repeat([1,2,3],3))
    gp  = a.groupby(level=0)
    empty_serie  = gp.filter(lambda x: x.mean()>1)
    error_raised = gp.filter(lambda x: x.mean()>1, dropna=False)

where `empty_list` would be an empty serie, meanwhile attribute error would be raised for the last line

**Comment by jreback** [comment]
hmm, that's not very friendly!. pull-requests to fix welcome!
