### ISSUE TITLE
PERF: follow up to ASV

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#10849]
xref #9715 
- [x] add docs on how to use / add tests (in contributing.md / contributing.rst)
- [x] add/update vbenches to current
- [x] whatsnew note (put in highlites that this is added)
- [ ] test on Windows (basicly works, but had to do some small adjustments)
- [x] get it working with python 3
- [ ] clean up autogenerated tests
  - [ ] fix failing tests
  - [ ] remove redundancy (by putting things in classes and reusing setup, .

cc @qwhelan

**Comment by jorisvandenbossche** [comment]
Added:

- test on Windows (basicly works, but had to do some small adjustments):
  - eg needs libpython to build -> I don't know how it is possible to specify something windows only in the yaml file
- clean up autogenerated tests:
  - fix failing tests
  - remove redundancy (by putting things in classes and reusing setup, ..)

Maybe I can find some people for this on the EuroScipy sprint if it is not yet done before that.

**Comment by jreback** [comment]
@jorisvandenbossche awesome!

**Comment by jreback** [comment]
note that I disabled the 3.4 support (was failing anyhow) for now.

**Comment by qwhelan** [comment]
I've fixed the translation script a bit to move functions from inside ```setup()``` to the class-level, so the majority of failures outside ```eval.py``` should be fixed.

I also have the suite running under Python 3 - I'll have to look into the current results in the morning but it looks promising.

**Comment by TomAugspurger** [comment]
Great. @qwhelan I'm curious what cause the py3 failures? Was it a change in how imports are handeled?

**Comment by qwhelan** [comment]
@TomAugspurger Partially, the changes were:
 * ```from pandas_vb_common import *``` -> ```from .pandas_vb_common import *```
 * Replace ```xrange``` with ```range``` and add ```from pandas.compat import range``` in ```pandas_vb_common```
 * Replace ```string.uppercase``` with ```string.ascii_uppercase```

There are probably a few others, but the vast majority seem to be working with the above changes.

**Comment by jorisvandenbossche** [comment]
@qwhelan could you push what you already did on this? Possibly there could be some people to sprint on this on Sunday, so then for that case best to start with your latest version!

**Comment by qwhelan** [comment]
@jorisvandenbossche Definitely, I'll squash down the commits tonight. There's a bit of updating of docs still needed and I don't want to waste any of the EuroScipy's folks' time reverse engineering my failure to document something, so I'll take care of that as well.

 Sorry about being spotty on this - job interviews have been sucking me dry lately.

**Comment by MaximilianR** [comment]
Is this closed? Some of the things like python3 work

**Comment by jorisvandenbossche** [comment]
The "clean up autogenerated tests" is not yet fully finished. I am not fully sure about windows.

**Comment by jbrockmendel** [comment]
the py3 checkbox must be fixed right?  auto-generated probably too

**Comment by mroeschke** [comment]
Yeah, I think we could close this issue and open up a separate issue about Windows if that's still an issue...
