### ISSUE TITLE
Idea - Integration with Data Packages

### ISSUE THREAD

**Issue by noelmas** [pandas-dev/pandas#10895]
Data Packages is a project that offers a standardized and extensible way of packaging up data. There is already a growing community around Data Packages and an increasing number of [core datasets](http://data.okfn.org/roadmap/core-datasets) which can easily be grabbed from a URL.

It would be great to see easy import and export to and from a Tabular Data Package - [see spec here](http://data.okfn.org/doc/tabular-data-package) -  into a Pandas DataFrame (e.g. pd.from_datapackage(...) & pd.to_datapackage(...)).

**Comment by TomAugspurger** [comment]
This would probably fit better in the (related) https://github.com/pydata/pandas-datareader repo. Care to open an issue there?

**Comment by noelmas** [comment]
Thanks @TomAugspurger - done!

https://github.com/pydata/pandas-datareader/issues/80

**Comment by jorisvandenbossche** [comment]
Related : https://github.com/trickvi/datapackage/issues/22

**Comment by jorisvandenbossche** [comment]
Closing as out of scope for core pandas
