### ISSUE TITLE
Matlab's grp2idx like function on a grouper

### ISSUE THREAD

**Issue by chanansh** [pandas-dev/pandas#10948]
I would like to have the group index of each instance.
I managed to do something like: 

```
labels = {idx:(groupKey) for groupKey,idxList in g.groups.items() for idx in idxList}
```

But I wish it would be part of pandas for other to use. How do I do that?
Maybe this function already exists and I am not aware of it?
I couldn't find any GroupBy object methods documentation online

**Comment by jreback** [comment]
not sure what you are looking for. pls show an example

**Comment by mroeschke** [comment]
Closing as an old issue, but feel free to reopen if could show an small example of the behavior you'd like to see.
