### ISSUE TITLE
consider supporting pandas DataFrame.to_json(orient='zipped') ?

### ISSUE THREAD

**Issue by jowens** [pandas-dev/pandas#10955]
I'm working with [vega-lite](https://github.com/uwdata/vega-lite) in a pipeline that goes from pandas to vega-lite. I would like to take a pandas DataFrame, output it as json, and incorporate it into a vega-lite JSON structure. Unfortunately none of pandas's DataFrame.to_json() "orient" options matches what vega-lite expects, so in the interest of better interoperability, I would like to request a 6th "orient" option, which I am calling 'zipped' but you could rename to anything.

Here is JSON for a vega-lite bar chart: https://github.com/uwdata/vega-lite#simple-bar-chart The "data" field is:

```
  "data": {
    "values": [
      {"x":"A", "y":28}, {"x":"B", "y":55}, {"x":"C", "y":43},
      {"x":"D", "y":91}, {"x":"E", "y":81}, {"x":"F", "y":53},
      {"x":"G", "y":19}, {"x":"H", "y":87}, {"x":"I", "y":52}
    ]
  },
```

I believe this is sort-of a dict(zip()) over a pandas DataFrame: every row in the DataFrame becomes one dict in the output list-of-dicts, with the keys in the dict equivalent to the column headings and the values in the dict equivalent to the values in the row associated with their respective column.

I am certainly aware that I could write code to manipulate an existing to_json() output, but it would seem this would be a useful output format for all.

**Comment by chris-b1** [comment]
Maybe I'm missing something, but is this any different than below?  You'd still have to serialize to JSON, but fundamentally, this doesn't seem any different than the `'records'` orient with some metadata?

     {'data': {'values': df.to_dict('records')}}

**Comment by jowens** [comment]
I think this is a productive direction. Thanks! Stay tuned, I will report back!

I do note that if df is a Series, to_dict doesn't take an orient argument, which is unfortunate, since orient='records' would seem to be useful there as well.

**Comment by jowens** [comment]
```to_dict('records')``` seems a little different than what I want. I'm assuming a DataFrame with one index (which I'm assuming is x) and one column (which I'm assuming is y); please tell me if I should simply use another DataFrame organization. (If it's not clear already, I'm a pandas n00b.)

- vega-lite wants a list of elements, where each element is a dict, and 'x' and 'y' are keys in that dict (e.g., ```{'x': xval, 'y': yval}```)
- ```to_dict('records')``` gives me a list of elements, which each element is a dict, but it doesn't incorporate the index at all; instead each element is {columnname, yval}, so columnname is replicated in every element. I like list-of-elements and each-element-is-a-dict, but it would be nice if a to_dict list-like orient could also incorporate the index.

**Comment by chris-b1** [comment]
Maybe something like `df.to_dict(orient='records', index=True)` would be reasonable, although it would have to handle cases where the index isn't named.  In your particular case, you could do this:

    df.index.name = 'x'
    df.reset_index()[['x', 'y']].to_dict('records')

**Comment by jowens** [comment]
Thanks to @chris-b1's suggestion, I am now getting what I need with:

```
df.index.name = 'x'
df = df.reset_index()
df.rename(columns={'old_y_name': 'y'}, inplace=True)
print df.to_dict(orient='records')
bar_chart["data"] = {"values" : df.to_dict(orient='records')}
```

Please feel free to offer any suggestions about how I can make the above code cleaner/simpler. And many thanks! I think you can close this out.

**Comment by fburanelli** [comment]
Hi, you should use `df.to_json(orient='records')` instead of `to_dict`, because the former produces a valid JSON using double quotes and the latter not.

Besides this, I believe this is not really a Pandas issue and would suggest after three years to close it. In fact `to_json(orient='records')` is all you need to create the vega-light values.
