### ISSUE TITLE
DOC: add 4th level to toc for various doc pages

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#11001]
[here](https://github.com/pydata/pandas/pull/10992) added 4th level menu items where appropriate in io.rst.

might pay to do this somewhat in some other sections just to break the sub-sections up a bit
- http://pandas-docs.github.io/pandas-docs-travis/dsintro.html

maybe other places as well

**Comment by jorisvandenbossche** [comment]
Now, in general, I would rather keep it to 3 levels, and split it in multiple files instead of keeping expanding the current files. See #10446

(but just for now making it better navigatable, having 4 levels is OK, for the long term I would go with #10446)

**Comment by jreback** [comment]
yes, it IS prob better to simply split io.rst up. Though it will still need to be 4 levels even if we do that :<

**Comment by jreback** [comment]
though was thinking in the Intro section, their are a lot of bullet points,, this is just some organization to it .... my 2c
