### ISSUE TITLE
read_csv: Inconsistent behaviour with parse_dates if the first row is short

### ISSUE THREAD

**Issue by jmopp** [pandas-dev/pandas#11019]
I suspect this is related to #6710.

```
import pandas
from io import StringIO
t = "a,b,c,d\n1970-01-01,2,3,4"
s2 = "a,b,c\n1970-01-01,2,3\n1980-01-01,2,3,4"
s = "a,b,c\n1970-01-01,2,3,4"
pandas.read_csv(StringIO(t), parse_dates=['a'])
pandas.read_csv(StringIO(s2), parse_dates=['a'])
pandas.read_csv(StringIO(s), parse_dates=['a'])
```

Calling `read_csv` with `parse_dates=['a']` does the correct thing for t, raises a CParserError for s2, and raises `TypeError:  'NoneType' object has no attribute '__getitem__'` for s. 

I would expect a CParserError for s as well.

Pandas version: 0.16.2

**Comment by jreback** [comment]
yep, could raise a better error message here. pull-requests are welcome.

**Comment by phofl** [comment]
This works as expected now. The s case is inferring the date as index, which happens if rows are longer than header. Also it is not parsed as date, so ok
