### ISSUE TITLE
Provide option to render HTML tags

### ISSUE THREAD

**Issue by iiSeymour** [pandas-dev/pandas#11062]
Exploring [in-lining plots](https://github.com/iiSeymour/sparkline-nb/blob/master/sparkline-nb.ipynb) in DataFrames I found it would be useful to have a display option for setting HTML escaping. This would avoid the work around of `HTML(df.to_html(escape=False))` every time you want to render the DataFrame.

I propose adding the option `display.escape_notebook_repr_html`.

**Comment by attack68** [comment]
HTML and latex escaping is now possible using either Styler or DataFrame.to-xxx
