### ISSUE TITLE
Passing colors to barplots with subplot=True

### ISSUE THREAD

**Issue by alvinwt** [pandas-dev/pandas#11100]
Is there a way to pass a list or dict of colors to a pandas barplot with subplot=True? The colors are used per plot instead of colors for individual bars. I would like to plot bar plots that have a different color per bar.

**Comment by jorisvandenbossche** [comment]
I don't think that is possible, and I also don't think we *want* to support that (it is more logical that you want different columns in different columns, and that is what is done by providing a list. I don't see a way to do both with a clean API)

But, you can always do it a bit more manual. If you make the subplots yourself, and plot each column separately on a subplot, then you can use a list to indicate the colors for each bar.

**Comment by alvinwt** [comment]
Hi @jorisvandenbossche thanks for the update. I adore the new layout and subplot features but sadly the colors within the bars mean something. Meanwhile I'll stick with a for loop for the subplots but I'm sure it less elegant that having everything done in one plot function.

**Comment by mroeschke** [comment]
Does sound like there's much appetite to implement this. Closing
