### ISSUE TITLE
Plot uses incorrect colors when columns have the same name

### ISSUE THREAD

**Issue by stevenmanton** [pandas-dev/pandas#11136]
It seems like the `plot` function jumbles up the colors when columns in a DataFrame have the same name:

``` python
pd.concat([pd.DataFrame({'b': [0, 1, 0], 'a': [1, 2, 3]}), pd.DataFrame({'a': [2, 4, 6]})], axis=1).plot();
```

![image](https://cloud.githubusercontent.com/assets/3666725/9942860/5770cf74-5d32-11e5-98b9-904ded128f57.png)

**Comment by jorisvandenbossche** [comment]
This seems to work correctly on current master. But we could add a test to make sure it keeps working.

**Comment by gabrielvf1** [comment]
I have checked and the code at the master really works fine, check the printscreen i tooked:

![pandasTest](https://user-images.githubusercontent.com/26471896/74880606-55c6d200-534a-11ea-8673-95843aa34614.png)

Now Im going to make a test to check if everything is correct at the graphic before it plots.
