### ISSUE TITLE
ENH: expanding_max/min for datetime types

### ISSUE THREAD

**Issue by bwillers** [pandas-dev/pandas#11130]
Docs currently explicitly mention float64 as the type of columns for `expanding_max` and `expanding_min`, and indeed, it does a conversion to float64 for other types:

```
In [6]: x = pd.date_range('2008/01/01', periods=3).to_series()

In [7]: x
Out[7]: 
2008-01-01   2008-01-01
2008-01-02   2008-01-02
2008-01-03   2008-01-03
Freq: D, dtype: datetime64[ns]

In [8]: pd.expanding_min(x)
Out[8]: 
2008-01-01    1.199146e+18
2008-01-02    1.199146e+18
2008-01-03    1.199146e+18
Freq: D, dtype: float64

In [9]: pd.expanding_max(x)
Out[9]: 
2008-01-01    1.199146e+18
2008-01-02    1.199232e+18
2008-01-03    1.199318e+18
Freq: D, dtype: float64    
```

It would probably be a good idea to implement this for other supported dtypes. Not all expanding functions will work with any dtype, but at least things like max/min for orderable types are pretty straightforward.

**Comment by jreback** [comment]
yep, this should prob raise ``NotImplemenetedError`` for now, until/unless implemented. (but granted this *should* work for some ops, e.g. ``min,max,first,last``) (and be disabled for the rest) for M8. for m8 should work for all ops (though needs some conversions).

@bwillers I'll put you down for this :)

**Comment by scls19fr** [comment]
Thanks to Chris answer on SO https://stackoverflow.com/questions/56662657/rolling-min-of-a-pandas-series-without-window I noticed that

`Series.expanding().min()` doesn't preserve type

```python
In [9]: s = pd.Series([10, 12, 14, 9, 10, 8, 16, 20])

In [10]: s
Out[10]:
0    10
1    12
2    14
3     9
4    10
5     8
6    16
7    20
dtype: int64

In [11]: s.expanding().min()
Out[11]:
0    10.0
1    10.0
2    10.0
3     9.0
4     9.0
5     8.0
6     8.0
7     8.0
dtype: float64
```

**Comment by mroeschke** [comment]
Thanks for the issue, but it appears this hasn't gotten traction in a while so closing
