### ISSUE TITLE
Passing a level argument to max/min prevents non-numeric columns from being dropped

### ISSUE THREAD

**Issue by ajcr** [pandas-dev/pandas#11164]
When passing a `level` argument and `numeric_only=True` to `max` and `min`, non-numeric columns are not dropped in the result:

```
>>> df = pd.DataFrame({'a': [1,1,2,2], 'b': [1,4,2,6], 
                       'c': [6,3,2,3], 'd': ['w','x','y','z']})
>>> df.set_index(['a', 'b'])
>>> df
     c  d
a b      
1 1  6  w
  4  3  x
2 2  2  y
  6  3  z

>>> df.max(level=0, numeric_only=True)
   c  d
a      
1  6  x
2  3  z
```

I would have expected that column 'd' would not be included here, as is the case if the `level` argument is omitted:

```
>>> df.max(numeric_only=True)
c    6
dtype: int64
```

**Comment by jorisvandenbossche** [comment]
Yes, that seems like a bug. PR always welcome!

**Comment by jreback** [comment]
The ``level`` arg dispatches to groupby, and because ``.max/.min``  handled for strings this 'works'.

So this may require explict filtering before dispatching to handle in a more uniform way. So ``_make_stat_function`` *might* want to do this (or maybe a simpler way)

**Comment by mroeschke** [comment]
The level keyword in aggregation functions was recently deprecated in https://github.com/pandas-dev/pandas/pull/40869 so I don't this this bug will be relevant in the future once this keyword is removed. Closing but happy to reopen if I misunderstood anything
