### ISSUE TITLE
TST: invalid generator tests in in test_internals.py

### ISSUE THREAD

**Issue by kawochen** [pandas-dev/pandas#11196]
`nosetests pandas/tests/test_internals.py:TestBlockManager.test_insert` runs successfully even when I tweak the `yield` statement to something false, such as `yield self.assertIs, 1, 2`.

This is because generator tests are not discovered inside subclasses of `TestCase`.

**Comment by jreback** [comment]
IIRC this is the same thing that you needed to do for ``msgpack/pickle`` tests, yes?

**Comment by kawochen** [comment]
Yes that's right (but I really only copied & pasted from the `pickle` tests).

**Comment by mroeschke** [comment]
I don't see a `yield` in this file anymore. Closing.
