### ISSUE TITLE
column-specific min_itemsize doesn't work with append_to_multiple 

### ISSUE THREAD

**Issue by BrenBarn** [pandas-dev/pandas#11238]
The `HDFStore.append_to_multiple` passes on its entire `min_itemsize` argument to every sub-append.  Because not all columns are in every append, it fails when it tries to set a min_itemsize for a certain column when appending to a table that doesn't use that column.  

Simple example:

```
>>> store.append_to_multiple({
...     'index': ["IX"],
...     'nums': ["Num", "BigNum", "RandNum"],
...     "strs": ["Str", "LongStr"]
... }, d.iloc[[0]], 'index', min_itemsize={"Str": 10, "LongStr": 100})
Traceback (most recent call last):
  File "<pyshell#52>", line 5, in <module>
    }, d.iloc[[0]], 'index', min_itemsize={"Str": 10, "LongStr": 100})
  File "c:\users\brenbarn\documents\python\extensions\pandas\pandas\io\pytables.py", line 1002, in append_to_multiple
    self.append(k, val, data_columns=dc, **kwargs)
  File "c:\users\brenbarn\documents\python\extensions\pandas\pandas\io\pytables.py", line 920, in append
    **kwargs)
  File "c:\users\brenbarn\documents\python\extensions\pandas\pandas\io\pytables.py", line 1265, in _write_to_group
    s.write(obj=value, append=append, complib=complib, **kwargs)
  File "c:\users\brenbarn\documents\python\extensions\pandas\pandas\io\pytables.py", line 3773, in write
    **kwargs)
  File "c:\users\brenbarn\documents\python\extensions\pandas\pandas\io\pytables.py", line 3460, in create_axes
    self.validate_min_itemsize(min_itemsize)
  File "c:\users\brenbarn\documents\python\extensions\pandas\pandas\io\pytables.py", line 3101, in validate_min_itemsize
    "data_column" % k)
ValueError: min_itemsize has the key [LongStr] which is not an axis or data_column
```

This apparently means that you can't use `min_itemsize` without manually creating and appending to each separate table beforehand, which is the kind of thing `append_to_multiple` is supposed to shield you from.

I think `append_to_multiple` should special-case `min_itemsize` and split it into separate dicts for each sub-append.  I don't know if there are other potential kwargs that need to be "allocated" separately to sub-appends, but if there are it might be good to split them too.

**Comment by jreback** [comment]
you can pass a dict for min_itrmsize with columns to sizes

**Comment by BrenBarn** [comment]
Yes, that's what I did in my example.  The problem is that `append_to_multiple` passes that entire dict to every `append`, so it tries to specify a `min_itemsize` for columns that don't exist in some of the multiple tables being appended to.

**Comment by BrenBarn** [comment]
I see this may be related to another thing I was just going to raise an issue about (namely that you can't specify data_columns for tables other than the "selector" with `append_to_multiple`).

**Comment by jreback** [comment]
ahh ok

as an aside there a couple of issues for doing a real column store (this is a hybrid, but the API is really not good here)

- interested?

**Comment by BrenBarn** [comment]
I saw some of those issues but I don't really know anything about those other backends that are being discussed for column stores.  I might be able to work something up to make the existing `append_to_multiple` approach a bit more flexible though.  See #11239 which I just created about a related limitation.

**Comment by jreback** [comment]
@BrenBarn can you show a complete copy-pastable example (IOW, show the creation of ``d`` as well). pls ``pd.show_versions()`` for the record as well.

**Comment by BrenBarn** [comment]
`d` is just like this:

```
import pandas
import numpy as np
import string

d = pandas.DataFrame({
    "IX": np.arange(1, 21),
    "Num": np.arange(1, 21),
    "BigNum": np.arange(1, 21)*88,
    "RandNum": np.random.randn(20),
    "Str": [chr(a) for a in np.random.randint(65, 81, 20)],
    "LongStr": [''.join(np.random.choice(list(string.lowercase), 5)) for a in xrange(20)]
})
```

Here is `show_versions()`, although I don't really think most of it is relevant for this issue (I removed a bunch of "None" ones):

```
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.8.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: AMD64 Family 16 Model 4 Stepping 3, AuthenticAMD
byteorder: little
LC_ALL: None
LANG: None

pandas: 0+unknown
nose: 1.3.7
pip: 7.1.2
setuptools: 5.7
Cython: 0.21.1
numpy: 1.9.2
scipy: 0.15.1
statsmodels: 0.6.1
IPython: 2.2.0
sphinx: None
patsy: 0.3.0
dateutil: 2.2
pytz: 2013b
blosc: None
bottleneck: None
tables: 3.1.1
numexpr: 2.4
matplotlib: 1.5.0rc2
```

The pandas version is built from the github repo as of a couple days ago.  I think it is revision 50aceeaa652c but I'm not sure because I pull it via hg-git and due to the issue I mentioned [here](https://groups.google.com/forum/#!searchin/pydata/__version__/pydata/4wpRuf-Vtbo/gPe5TMczECEJ) `pandas.__version__` does not appear to be updated correctly if git is not available when building.

**Comment by ron819** [comment]
Any chance this will be implemented soon?

**Comment by jreback** [comment]
a community pull request would make this happen
