### ISSUE TITLE
Cannot subclass MultiIndex

### ISSUE THREAD

**Issue by janmedlock** [pandas-dev/pandas#11267]
`MultiIndex` cannot be subclassed because in several spots, including `__new__`, the output class is hardcoded as `MultiIndex` rather than `cls`  or `self.__class__` or the like.

This code illustrates the problem:

``` python
$ python
Python 2.7.10 (default, Sep 13 2015, 20:30:50) 
[GCC 5.2.1 20150911] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> class MyMultiIndex(pandas.MultiIndex):
...     pass
... 
>>> multiindex = MyMultiIndex([['a'], ['b']],
...                           [[0], [0]])
>>> print type(multiindex)
<class 'pandas.core.index.MultiIndex'>
```

The last line should instead read

``` python
<class '__main__.MyMultiIndex'>
```

I have a patch in the works.

``` python
>>> pandas.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.10.final.0
python-bits: 64
OS: Linux
OS-release: 4.1.0-2-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.utf8

pandas: 0.16.2.dev
nose: 1.3.6
Cython: 0.23.2
numpy: 1.9.2
scipy: 0.14.1
statsmodels: 0.6.1
IPython: 2.3.0
sphinx: 1.3.1
patsy: 0.4.0
dateutil: 2.2
pytz: 2012c
bottleneck: None
tables: 3.1.1
numexpr: 2.4.3
matplotlib: 1.4.2
openpyxl: None
xlrd: 0.9.4
xlwt: 0.7.5
xlsxwriter: None
lxml: None
bs4: 4.4.0
html5lib: 0.999
httplib2: 0.9.1
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
```

**Comment by janmedlock** [comment]
I just submitted pull request #11268 to fix this.

**Comment by jreback** [comment]
can you provide a use-case for this (not objecting to the change though)

**Comment by janmedlock** [comment]
Sure.  I don't want to need to know the order of the indices in the MultiIndex.  E.g.
```python
mi = MultiIndex((('a', 'b'), ('A', 'B')),
((0, 0), (0, 1), (1, 0), (1, 1)), names=('foo', 'bar'))
df = Series(..., index = mi)
```
I want to be able to write something like
```python
df[mi(foo = 'a', bar = 'b')]
```
or similar to get the correct Series elements.

Maybe this functionality already exists in MultiIndex, but I didn't see it and decided to subclass.

**Comment by jreback** [comment]
we've had discussions [here](https://github.com/pydata/pandas/issues/4036)

```
mi = pd.MultiIndex.from_product([list('ab'),list('AB')],names=['foo','bar'])

In [5]: s = Series(range(4),index=mi)

In [6]: s
Out[6]: 
foo  bar
a    A      0
     B      1
b    A      2
     B      3
dtype: int64
```

to allow:

``s.loc[{'foo' : 'a', 'bar' : B'}]``

xray calls this ``.sel``, see [here](http://xray.readthedocs.org/en/stable/indexing.html)

or maybe
``s.loc[S(foo='a',bar='B')]`` where ``S`` is simply

```
class S(object):
    def __call__(self, *kwargs):
         return kwargs
```

if we allow the dict syntax

you wouldn't normally want to have to do:

``s[s.index(foo='a', bar='B')]``, although not terrible

so, you don't need to sub-class at all, simply patch it in

```
In [8]: MultiIndex.__call__ = lambda self, **kwargs: tuple([ (kwargs.get(n,slice(None))) for n in self.names ])

In [9]: s.loc[s.index(foo='b',bar='B')]
Out[9]: 3
```

kind of like that actually :)

cc @shoyer

**Comment by janmedlock** [comment]
Thanks for the answer!

**Comment by jrderuiter** [comment]
So this never got changed? Was there any special reason for not persuing this further?

**Comment by jreback** [comment]
the PR went stale. in principle it is ok if you'd like to pick it up; needs more testing
