### ISSUE TITLE
ABCGeneric instance checking is broken

### ISSUE THREAD

**Issue by berislavlopac** [pandas-dev/pandas#11270]
So, my issue was that pandas was throwing an error (about not having implemented `_constructor`) when I tried to use a custom object as a label for a column in `DataFrame`, even though that object's class was not a part of the pandas hierarchy. After some digging I have realized that pandas thinks this object is an instance of `ABCGeneric`, which I eventually tracked down to https://github.com/pydata/pandas/blob/master/pandas/core/common.py#L111, where it can be seen that any object implementing a `_data` attribute is considered an instance of `ABCGeneric`.

The simplest code to recreate the issue is this:

``` python
import pandas

class Foo(object):
    _data = None

foo = Foo()

df = pandas.DataFrame({foo: [1,2,3,4,5]})

df[foo]
```

This is clearly broken, as (like in my case) there are perfectly legitimate cases when other, non-pandas objects might have a `_data` attribute. Also, at least in this particular case `_data` is not the only item required from the object, as obviously it needs a `_constructor` as well. I would recommend changing this implementation either not to rely on the presence of `_data` only, or even better to look for an actual superclass, or, possibly the best, to use duck typing instead of relying on `isinstance`.

**Comment by jreback** [comment]
not sure what the issue is here. pandas objects by definition have this attribute, and we rely on it to check for typeness in some cases (to avoid circular import issues and such)

**Comment by jreback** [comment]
supporting actual objects (as opposed to string,ints) in an ``Index`` violates the pandas guarantees.

**Comment by berislavlopac** [comment]
The main issue, in my opinion, is an object having a certain attribute does not necessarily mean that it is an instance of a certain class, and this is a bad way to confirm the `isinstance` relationship. I'm fine with arbitrary objects not being supported, this is a wider issue here, as it allows for false positives without providing a clear explanation.

Additionally, it's obvious that simply having the `_data` attribute is not enough for an object to be supported, as at least `_constructor` is called as well, so it doesn't really do the job it's supposed to.

**Comment by jreback** [comment]
well, if you have a better soln, all ears.

**Comment by jreback** [comment]
actually I think we *could* blow away ``ABCGeneric`` and repacle with ``isinstance(PandasObject)``, this is somewhat older code, but their is a circular import issue to be solved. If you would like to work on that great.

**Comment by berislavlopac** [comment]
I like this idea, I might look into that when I catch some time, possibly this weekend.

**Comment by jreback** [comment]
@berislavlopac great thanks!

**Comment by jreback** [comment]
@berislavlopac any luck with this?

**Comment by berislavlopac** [comment]
First of all apologies for the long delay, I've had a crazy couple of weeks.

Second, I'd personally prefer using duck typing, so if the code needs the object to have `_constructor` and `_data` (as it does) I would check for their presence. But since pandas tends to use type checking throughout I guess it should be better to keep it here as well. I'm just looking at the code to see how to resolve the circular import issue.

**Comment by berislavlopac** [comment]
Heh, apparently using `PandasObject` is not enough, as some subclasses don't have `_data` property at all, e.g. `Categorical`. Personally I would refactor so that each group of types has its own way of determining `isnull` , but I'm not that familiar with the architecture of `pandas` to be confident about doing it (I see the method exists in some places, but I guess it's used for other purposes).

**Comment by jbrockmendel** [comment]
@jreback closeable?  We no longer check based on _data
