### ISSUE TITLE
implementation of from_julian_date()

### ISSUE THREAD

**Issue by sebhahn** [pandas-dev/pandas#11276]
`pandas.DatetimeIndex` supports a method called `to_julian_date()` would it be easily possible to support a function/method doing the opposite, i.e. `from_julian_date()`?

**Comment by chris-b1** [comment]
fyi, this is somewhat easy to do with the current `to_datetime`, just subtract the offset and specify that the unit is days.

```python
In [66]: julian_dates = pd.date_range('2014-1-1', periods=10).to_julian_date().values

In [67]: julian_dates
Out[67]: 
array([ 2456658.5,  2456659.5,  2456660.5,  2456661.5,  2456662.5,
        2456663.5,  2456664.5,  2456665.5,  2456666.5,  2456667.5])

In [68]: pd.to_datetime(julian_dates - pd.Timestamp(0).to_julian_date(), unit='D')
Out[68]: 
DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06', '2014-01-07', '2014-01-08',
               '2014-01-09', '2014-01-10'],
              dtype='datetime64[ns]', freq=None)
```

**Comment by sebhahn** [comment]
interesting solution, thank you very much for that!

**Comment by jreback** [comment]
I think this would not be unreasonable to have ``pd.to_datetime(....., ,unit='julian')``
I guess as long as making things up ``DatetimeIndex.astype('datetime64[julian]')`` prob a bit much


We don't have any ``from_*`` for this kind of thing

**Comment by sebhahn** [comment]
Good idea! So you plan to support this in the future?

**Comment by jreback** [comment]
@sebhahn if you'd like to do a PR with the ``unit='julian'`` I think would be reasonable to start.

**Comment by sumitbinnani** [comment]
@jreback @sebhahn 
Is this enhancement being included and is someone working on the same? If not, I would like to give it a try :-)

**Comment by sebhahn** [comment]
@sumitbinnani I haven't started yet, so feel free to implement it :smile:

**Comment by sumitbinnani** [comment]
@sebhahn: Thanks. Will soon submit a patch :-)

**Comment by sebhahn** [comment]
:+1:
