### ISSUE TITLE
Pandas.plot() fails to calculate the right xlims

### ISSUE THREAD

**Issue by AKuederle** [pandas-dev/pandas#11310]
While working with cyclic data, Pandas failed to calculate the right limits for the plot. I am not sure which exact characteristic of my data causes the problem, but I will observe if further when I have time for it. Until then, here is the notebook in which the error occurred:

http://nbviewer.ipython.org/gist/AKuederle/d7837facee0479beb6cf

The first plot is the pandas plot, which has the wrong x-limits.
The second plot is the same (or at least I thought) the same plot using matplotlib directly.
The third plot shows, that it padas issue is indeed the x-limits and not something else in plotting process

Edit:
Used package Versions:

```
commit: None
python: 3.4.3.final.0
python-bits: 64
OS: Windows
OS-release: 8
machine: AMD64
processor: AMD64 Family 16 Model 10 Stepping 0, AuthenticAMD
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.16.2
nose: 1.3.7
Cython: 0.23.3
numpy: 1.9.3
scipy: 0.16.0
statsmodels: 0.6.1
IPython: 4.0.0
sphinx: 1.2.3
patsy: 0.4.0
dateutil: 2.4.1
pytz: 2015.6
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.4
matplotlib: 1.4.3
openpyxl: 2.0.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.7.5
lxml: 3.4.4
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.8
pymysql: None
psycopg2: None
```

**Comment by jreback** [comment]
pls ``pd.show_versions()``
