### ISSUE TITLE
PERF: refactor ExcelFormatter

### ISSUE THREAD

**Issue by chris-b1** [pandas-dev/pandas#11355]
xref #11352
- [ ]  use `to_native_types` by block to yield already formatted cells
- [ ]  yield cells in row-oriented way  https://github.com/pydata/pandas/pull/11144#issuecomment-141966626

**Comment by jreback** [comment]
FYI, you might want to reach out to @jmcnamara w.r.t. ``xlsxwriter`` to see if they can input these on a columnar basis to make this faster, I know that the ``openpyxl`` guys  cc @Themanwithoutaplan are already working on this

**Comment by Themanwithoutaplan** [comment]
The output is row based so there has to be a conversion at some point from columns to rows. See https://bitbucket.org/snippets/openpyxl/jgbak for a barebones approach.

Will look to add support for Numpy types in a future version of openpyxl and using named styles for faster formatting.

**Comment by calvinwyoung** [comment]
Are there any plans to resolve this issue? We'd really love to be able to use `constant_memory` to output large XLSX files.

**Comment by Themanwithoutaplan** [comment]
@calvinwyoung this is possible in openpyxl using the dataframe_to_rows() function, which should also work with xlsxwriter. Having looked at the code for the Excelformatter I'm pretty sure that this will always be faster than using to_excel()

**Comment by jmcnamara** [comment]
@calvinwyoung One problem with using xlsxwriter's `constant_memory` mode from Pandas is that xlsxwriter doesn't support merged ranges across rows in that mode. As a result it would break the formatting for merged indices. If you specifically need `constant_memory` support you should probably look at writing the data from the dataframe yourself using xlsxwriter directly.

**Comment by calvinwyoung** [comment]
@Themanwithoutaplan @jmcnamara Thank you both for the feedback. It seems like neither `dataframe_to_rows()` nor `constant_memory` supports merged ranges across rows.

Is there a generally accepted strategy for supporting merged ranges *and* keeping memory consumption low? For our application, we're okay if the processing takes longer — it just so happens that the machines we're using are constrained by memory, and we aren't able to use swap.

**Comment by Themanwithoutaplan** [comment]
@calvinwyoung if you want to merge cells when writing straight to XML then you'll have to manage more of this yourself. Apart from the formatting it's not difficult. Details are out of scope for this ticket I think and should be discussed on the openpyxl mailing list.

**Comment by calvinwyoung** [comment]
Grea, thank you!

**Comment by mroeschke** [comment]
Seems like there's not been much development here and there doesn't seem to be a clear action item here so closing
