### ISSUE TITLE
pandas ewmcov with nan gives inconsistent results

### ISSUE THREAD

**Issue by jonathanng** [pandas-dev/pandas#11387]
I have a dataframe, and I want to calculate ewmcov. Sometimes the dataframe has missing values.

I've noticed that using the same dataframe, I get two different results with two separate calls of ewmcov.

Anyone have an idea on why this could be?

**Comment by jreback** [comment]
pls show a copy pastable example and pd.show_versions()

**Comment by mroeschke** [comment]
Feel free to reopen if you can post a copy pastable example.
