### ISSUE TITLE
DOC: add axes attributes to API docs

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#11407]
from [SO](http://stackoverflow.com/questions/33272411/is-there-an-online-source-of-complete-documentation-on-pandas-objects-classes-b)

People just jump to the API w/o actually reading ANY Introduction where this is convered in the first sentence

so API docs should be more complete

**Comment by jorisvandenbossche** [comment]
Do you know why `index` and `columns` are not listed there and other attributes such as `values` is? As these are generated automatically based on the sphinx/numpydoc inspection of the DataFrame class

**Comment by jorisvandenbossche** [comment]
`inspect.getmembers(pd.DataFrame)` does not include it (it includes it in the `__dict__` item, but not top-level). So the problem with how the `index` and `columns` attributes are defined in the DataFrame/NDFrame class

**Comment by kawochen** [comment]
@jorisvandenbossche https://github.com/pydata/pandas/blob/master/pandas/src/properties.pyx#L53

**Comment by kawochen** [comment]
```
In [1]: import pandas

In [2]: import inspect

In [3]: 'index' in [x[0] for x in inspect.getmembers(pandas.DataFrame)]
Out[3]: True

In [4]: 'columns' in [x[0] for x in inspect.getmembers(pandas.DataFrame)]
Out[4]: True
```

PY3 though.

**Comment by pdpark** [comment]
Looking for an easy documentation fix for my first contribution to an open source project and I came across this open Issue. However, after forking the repo and compiling the docs locally, this seems to be fixed - I see "columns" and "index" in the Attributes section now - albeit w/o any description.

It looks like it's fixed in the latest build: https://pandas-docs.github.io/pandas-docs-travis/generated/pandas.DataFrame.html#pandas.DataFrame

**Comment by TomAugspurger** [comment]
Ah, https://github.com/pandas-dev/pandas/pull/18196 fixed the error but didn’t add a docstring.

**Comment by mroeschke** [comment]
It appears `index` and `axis` appear in the API reference now with (brief) docstrings:

https://pandas.pydata.org/pandas-docs/stable/reference/series.html
https://pandas.pydata.org/pandas-docs/stable/reference/frame.html

I think this issue can be sufficiently closed
