### ISSUE TITLE
Unclear what chunksize represents in to_sql() docs

### ISSUE THREAD

**Issue by martinburch** [pandas-dev/pandas#11415]
From http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_sql.html

> **chunksize** _: int, default None_
> If not None, then rows will be written in batches of this size at a time. If None, all rows will be written at once.

"this size"? Sounds like it could be the max size in bytes. How about "this number of rows"?

I think that's right given read_sql() says:
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_sql.html

> **chunksize** _: int, default None_
> If specified, return an iterator where chunksize is the number of rows to include in each chunk.

If that's not right please let me know. Thanks!

**Comment by jorisvandenbossche** [comment]
That sounds good. Do you want to do a PR to change this?

Source code is here: https://github.com/pydata/pandas/blob/master/pandas/io/sql.py#L516 and here: https://github.com/pydata/pandas/blob/master/pandas/core/generic.py#L990

**Comment by martinburch** [comment]
Thanks! I'll put in the PR tomorrow

**Comment by rutgerhofste** [comment]
still not in the docs

**Comment by mroeschke** [comment]
It appears that this issue may have been solved as the `to_sql` docstring now states

> Specify the number of rows in each batch to be written at a time. By default, all rows will be written at once.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_sql.html

Going to close but can reopen if additional clarification is needed
