### ISSUE TITLE
regex for lineseparator read_csv

### ISSUE THREAD

**Issue by mas-dse-nbondugu** [pandas-dev/pandas#11467]
current lineseparator for pd.read_csv() takes only string with 1 char.
Please provide the facility to be able to break the lines based on regex pattern

**Comment by jreback** [comment]
pls show a usecase where this is actually necessary

**Comment by mas-dse-nbondugu** [comment]
Hi Jeff,

I am trying to analyze one of the common data bases.

http://kdd.ics.uci.edu/databases/kddcup98/epsilon_mirror/cup98lrn.zip

The file is a cvs file with "\n" line terminator. However there are more than 400 lines that have a "\x00" as terminator. read_csv gives error because it is not treating "\0" as line terminator.
I want to have "\n" or "\0" as line terminator.

Also even if i explicitly use lineterminator="\0" in read_csv(), looks like it is not treating "\0" as terminator

This lines below gives me the same error. (cup98LRN.txt is in the zip file). the file has "\n" as line terminator in most lines. about 400 lines has "\0" line terminator.

df = pd.read_csv('cup98LRN.txt')
df = pd.read_csv('cup98LRN.txt', lineterminator="\0")

**CParserError: Error tokenizing data. C error: Expected 481 fields in line 579, saw 96**
so it means adding line terminator has no effect.

1) I want to tell read_csv to treat "\0" along with "\n" as line terminator.

unix commands wc - l treats "\n" and "\0" as line terminator and gives me appropriate number of lines.

**Comment by jreback** [comment]
I suppose, though this would be some effort. If someone wants to submit a pull-requests great. 

you are probably better doing a replace on those errant tokens (or using a single lineterminator and setting ``error_bad_lines=False``), that is quite weird data.

**Comment by mas-dse-nbondugu** [comment]
I could use error_bad_lines=False but that wud ignore the lines.
I think handling "\0" as line terminator makes sense because it is a
default terminator in C.
also unix command wc -l treats it as lineterminator.

What do you think?

**Comment by jreback** [comment]
and ``\0`` is handled by default. You have a MIXED line-endings. So pick one, then just substitute the other when you read in the data.

This is just adding needless complexity to the parser which is already very complex. Of course pull-requests are welcome.

**Comment by mas-dse-nbondugu** [comment]
i think it has only \0 and \n

when i did test.replace('\0', '\n') it replaced all those and my read_csv
worked fine with all lines.

**pull-requests are welcome.**
What do you mean by pull-requests

**Comment by jreback** [comment]
I mean if you would like to contribute a code fix to support this, by all means, see [here](http://pandas.pydata.org/pandas-docs/stable/contributing.html)

**Comment by mroeschke** [comment]
Appears there hasn't been much activity or community support for this feature in a while so closing. Happy to reopen if there's renewed support
