### ISSUE TITLE
ERR: raise NotImplemented error if keywords are passed to read_excel which are not supported

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#11544]
xref #11527 
xref #10001

currently we pass thru keywords to the `TextReader` but some of these don't do anything. Should catch and raise on these.

**Comment by jorisvandenbossche** [comment]
Did #11870 close this fully? There are not other keywords that also should raise?

**Comment by jreback** [comment]
I think we need to change ``read_excel`` to have explict keywords, maybe 'accepting' some common ones where we raise ``NotImplementedError`` to give a nicer error messsage.

so let's reopen this one.

**Comment by jreback** [comment]
cc @grahamjeffries
