### ISSUE TITLE
Series.sort_values doesn't support a `by` keyword argument, but the documentation claims it does

### ISSUE THREAD

**Issue by mineo** [pandas-dev/pandas#11540]
pandas: 0.17.0

``` python
import pandas
s = pandas.Series([1,2,3])
s.sort_values(by=["a"])

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-4a7ccaa074a5> in <module>()
      1 import pandas
      2 s = pandas.Series([1,2,3])
----> 3 s.sort_values(by=["a"])

TypeError: sort_values() got an unexpected keyword argument 'by'
```

https://github.com/pydata/pandas/blob/1135ce34fc2fb995e239a7d36aee1b687ef69dd9/pandas/core/series.py#L1609 does indeed not support `by`, but [the docs](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.sort_values.html) list it as a supported keyword argument.

**Comment by jreback** [comment]
this is just using the super docs
want to do a pr to fix?

**Comment by mineo** [comment]
Frame.sort_values and NDFrame.sort_values support `by`, though, so I'm not sure how to fix them.

**Comment by jreback** [comment]
take the by out of the shared docs and then add back as part of the doc string for DataFrame and NDFrame

**Comment by mineo** [comment]
Important things first: I still think pandas is a really cool thing :sparkles:, but I give up :( Building the docs without conda is just too hard - installing everything from `ci/requirements_dev.txt` doesn't even get you into a state where `python make.py html` actually works, I had to install matplotlib manually and run `python setup.py build_ext --inplace`. The generated docs are now missing large parts of the API reference (including Series.sort_values). This might be fixed by installing everything in `ci/requirements_all.txt` but the package names in there differ from the package names on pypi and I don't have conda installed. I'm sorry, but I currently do not have the time to figure out how to use another tool for building python environments just to remove this one line of documentation, so don't expect a pull request from me.

**Comment by jreback** [comment]
@mineo 

this is a doc-string! not the actual docs, you don't actually need to build the docs.

you can simply examine them from ipython: ``Series.sort_values?``

though it IS pretty easy (but you should for sure use conda if you do), its just so much easier, see guidelines [here](http://pandas.pydata.org/pandas-docs/stable/contributing.html)

**Comment by jreback** [comment]
and you need cannot JUST install ``requirements_dev.txt`` that is just a minimal set. The docs are quite comprehensive on these points; you need quite a lot of deps to build the docs.

**Comment by varun-kr** [comment]
@jreback  If I take the by out from the shared docs and then add "by" parameter as part of the doc string for DataFrame and NDFrame, it will not include "by" in the parameter section. Right ?

In that case , should I remove sort_values from shared docs and add different doc strings in Frame.sort_values  and Series.sort_values ?

**Comment by pau1a** [comment]
I just came up against this tonight. I this just lingering? Is the documentation wrong or is this a bug?

**Comment by jorisvandenbossche** [comment]
This should actually already be fixed by https://github.com/pandas-dev/pandas/pull/13496 (released in 0.19.0) in the meantime. 
@pau1a what version of pandas are you using?

**Comment by iamlydialawal** [comment]
Yeah this was not fixed...might coerce back into a df

**Comment by Aka-shi** [comment]
BUMP. Is this fixed? Still facing the same issue with .sort_values()
