### ISSUE TITLE
Enhancement: add fuzzy join ability

### ISSUE THREAD

**Issue by lminer** [pandas-dev/pandas#11583]
Would be nice to be able to perform a fuzzy join between two dataframes based on string columns. This [thread](http://stackoverflow.com/questions/13636848/is-it-possible-to-do-fuzzy-match-merge-with-python-pandas) shows how to do it using difflib, but it may be nice to have this as built-in functionality.

**Comment by makmanalp** [comment]
Check out dedupe: https://github.com/datamade/dedupe

**Comment by d6tdev** [comment]
This is implemented in https://github.com/d6t/d6tjoin, see example https://github.com/d6t/d6tjoin/blob/master/examples-top1.ipynb

**Comment by mroeschke** [comment]
Seems like there hasn't been much interest in this feature over the years so closing
