### ISSUE TITLE
Time zone support with PeriodIndex

### ISSUE THREAD

**Issue by wesm** [pandas-dev/pandas#1159]
This might be quite a bit of work, maybe leave for post 0.8.0

**Comment by jbrockmendel** [comment]
It is clear what this means in the context of freq='s', 'ms', 'us', effectively lower-resolution Timestamps.  Is the idea here to also apply timezones to arbitrary frequencies, e.g. BQuarterEnd?

**Comment by wesm** [comment]
Closing as won't fix

**Comment by joooeey** [comment]
Why is this a won't fix? It's quite the surprise that when you create a PeriodIndex with time zone aware arguments all in the same time zone, the result will be naive and there is not even a warning.

**Comment by simonjayhawkins** [comment]
@joooeey can you add your comment to #45736 instead of this closed issue to help keep discussion in one place.
