### ISSUE TITLE
Time series branch, feature request for grouping by volume

### ISSUE THREAD

**Issue by jeffneuen** [pandas-dev/pandas#1161]
It looks like the time series branch already includes increased functionality for high performance time resampling between time frequencies.  Will there be support for converting from higher frequency data to other grouping methods, such as tick data or 1s bars to 1000 volume bars?  Perhaps this doesn't fall into true time series functionality.

**Comment by kokes** [comment]
I don't know the domain too well, but hasn't this been solved by `df.groupby(pd.cut(df.time_column, index))...`, where index is an `IntervalIndex`?

**Comment by jreback** [comment]
that and the ability to arbitrarily upsample snd downsample
