### ISSUE TITLE
Pandas automatically interprets string as datetime

### ISSUE THREAD

**Issue by tangfucius** [pandas-dev/pandas#11636]
I have a dataframe that looks like this:

| Index | IssueId | AppName | IssueStatus | IssueDescription | IssueCreatedTime |
| --- | --- | --- | --- | --- | --- |
| 9965 | 239578 | abc | New | 'Rewards' | 2015-11-15 14:25:40 |
| 9966 | 219878 | abc | Resolved | '\u0414' | 2015-10-27 13:35:03 |
| 9967 | 239580 | abc | New | 'I'm still having problems with the game I log out of Facebook and now it will not let me back in saying that my farm is already register with a Facebook account.' | 2015-11-15 14:28:07 |
| 9968 | 132141 | abc | In Progress | 'Where do you get capers' | 2015-07-08 00:20:40 |
| 9969 | 209387 | abc | Resolved | '3.3.0' | 2015-10-18 11:32:08 |

If I do this, the '3.3.0' gets recognized as a date for some reason, and I get the following:

```
ex2 = ex.groupby('IssueId').apply(lambda x: x.iloc[-1])
```

| IssueId | AppName | IssueStatus | IssueDescription | IssueCreatedTime |
| --- | --- | --- | --- | --- |
| 132141 | abc | In Progress |  | 2015-07-08 00:20:40 |
| 209387 | abc | Resolved | 2000-03-03 00:00:00 | 2015-10-18 11:32:08 |
| 219878 | abc | Resolved |  | 2015-10-27 13:35:03 |
| 239578 | abc | New |  | 2015-11-15 14:25:40 |
| 239580 | abc | New |  | 2015-11-15 14:28:07 |

If I drop the column 'IssueCreatedTime', everything is normal again. Is this a bug? How can I suppress this behavior?

**Comment by jreback** [comment]
pls show a copy-pastable example along with ``pd.show_versions()``
