### ISSUE TITLE
HTML styling set_precision should take subset

### ISSUE THREAD

**Issue by mattilyra** [pandas-dev/pandas#11656]
There's a problem in the way `.set_precision` currently works as it is being applied to all table cells indiscriminately. For instance a dataframe with means and standard errors cross validated across some parameter values the `set_precision` will easily hide a lot of detail in the results.

![screen shot 2015-11-20 at 12 03 14](https://cloud.githubusercontent.com/assets/1055719/11298401/ffdcccb6-8f7e-11e5-848c-be21bbd3eb2f.png)

The second parameter (2nd index) is not all zeros, they're just values in the range `[1e-4, 1e-3]`. Also while for the `mean` columns a precision of 2 is fine, for the standard error 4 might be more appropriate. So having a `subset=` keyword argument also for `.set_precision` would be great. 

![screen shot 2015-11-20 at 12 02 56](https://cloud.githubusercontent.com/assets/1055719/11298399/fc17f60a-8f7e-11e5-9691-58ef9c32847b.png)

---

code for making the df

```
import itertools
import pandas as pd
import numpy as np

jobs = itertools.product(['a', 'b', 'c', 'd'], np.arange(1e-4, 1e-3, .0003), range(10))
rows = []
for v, v2, itr in jobs:
    rows.append({'param_1': v, 'param_2': v2, 'iter': itr,
                 'score_1': np.random.randint(0, 100, size=(1,))[0],
                 'score_2': np.random.rand(1, )[0]})
df_multi = pd.DataFrame(rows)
agg = df_multi.groupby(by=['param_1', 'param_2'])[['score_1', 'score_2']].agg(['mean', 'sem'])
```

**Comment by jreback** [comment]
yep seems reasonable to me..

pull-requests are welcome!

**Comment by TomAugspurger** [comment]
This is a good addition, but might be a bit of work. Right now we

```python
                    {% if c.value is number %}
                        {{c.value|round(precision)}}
                    {% else %}
                        {{c.value}}
                    {% endif %}
```

c is a dict with {'type', 'value', 'class', 'props', 'selector'`} that's built in `Styler._translate`. The best way is probably to add a `precision` field to that.

**Comment by mattilyra** [comment]
I can take this, although I'll probably require some help as I've never looked at the `pandas` codebase. The above should get me started at least.

**Comment by TomAugspurger** [comment]
That'd be great if you want to take it. We're releasing `0.17.1` today sometime, so change probably won't make it. All of this stuff is in `pandas/core/style.py`.

Right now `styler.precision` is just an `int`. That will need to be converted to a dict of `{column: int}`s (but we should still accept a single `int` meaning "use this precision for everything". Then in the `._translate` step you'll need to add that "precision" field to `row_es`.

**Comment by mattilyra** [comment]
Ok, yeah this certainly won't make it 0.17.1 in that case. Any thoughts on how the precision would be applied to the `index`, or should we just leave the `index` alone for now.

**Comment by TomAugspurger** [comment]
I'd say leave index alone, at least to start with. That is all going to get an overhaul before the next release when we add support for styling Indexes.

**Comment by attack68** [comment]
this method is depecated and solutions are now available with Styler.format(precision)
