### ISSUE TITLE
ENH: add gzip/bz2 compression to read_pickle() (and perhaps other read_*() methods)

### ISSUE THREAD

**Issue by gfairchild** [pandas-dev/pandas#11666]
Right now, `read_csv()` has a `compression` option, which allows the user to pass in a gzipped or bz2-compressed CSV file directly into Pandas to be read. It would be great if `read_pickle()` supported the same option. Pickles actually compress surprisingly well; I have a 567M Pandas pickle (resulting from `DataFrame.to_pickle()`) that packs down to 45M with `pigz --best`. An order of magnitude difference in size is pretty significant. This makes storing static pickles long-term as gzipped archives a very attractive option. Workflow would be made easier if Pandas could natively handle my `dataframe.pickle.gz` files in the same way it does compressed CSV files.

More generally, a `compression` option should probably be allowed for most `read_*` methods. Many of the `read_*` methods involve formats that compress very well.

**Comment by jreback** [comment]
yeh, this wouldn't be hard for gzip/bz2

**Comment by jreback** [comment]
xref #5924

**Comment by MaxNoe** [comment]
Yes please. Especially for `read_json`!

**Comment by goldenbull** [comment]
I like xz/lzma2 format for pickle format :smile:

**Comment by jreback** [comment]
@goldenbull pull-requests are welcome! (this is not very difficult, more of a bit of code reorg to share the compression code)

**Comment by gfairchild** [comment]
Fantastic! @jreback, are there plans by chance to implement compression support across *all* `read_*` methods since most of the formats compress well?

**Comment by jreback** [comment]
@gfairchild what do you think is useful? keeping in mind ``read_csv`` already does this, ``read_hdf`` has in-line compression. ``read_sql`` doesn't support files. ``read_feather`` doesn't support it yet.

*maybe* ``read_excel`` I suppose. though wonder if that's common (as you can't generally have really large excel files so does this really matter).

**Comment by jreback** [comment]
ahh I c, ``read_json`` seems a great candidate here.

@gfairchild do you want to open a new issue (xref this one and the PR). for ``read_json`` (and ``read_excel`` if you think is useful).

**Comment by gfairchild** [comment]
After considering more closely, `read_json` is the only remaining format where this could definitely be useful. I've definitely stored large static gzipped JSON files before.

**Comment by gfairchild** [comment]
Since this issue does say "perhaps other `read_*` methods", could we just re-open this issue? If that's not kosher, I'm happy to create another issue for this in a few hours once I get out of some meetings.

**Comment by jreback** [comment]
yeah let's just create a new issue

**Comment by gfairchild** [comment]
Not a problem. I'll do that in a few hours.

**Comment by gfairchild** [comment]
Sorry for the delay, but I just created the issue: https://github.com/pandas-dev/pandas/issues/15644

**Comment by goldenbull** [comment]
@jreback I think `read_excel` is not neccessary because .xlsx is already a zip file by design.
