### ISSUE TITLE
ENH: implement __iter__ for window objects

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#11704]
xref #11603 

might be slightly non-trivial as the current impl does NOT use an explict iterator, rather does a sliding window in cython and marginal calcs.

**Comment by kawochen** [comment]
I don't know if this is too ambitious, but for custom rolling aggregation, if you can let users supply a `StateVariables` object which is initialized using the first window, and supports two methods, `evolve()` and `compute()`, then you may be able to retain the efficiency when the evolution of the state variables is governed by a simple set of equations. `__iter__` becomes a special case of this where the `StateVariables` contains the whole window, and `evolve` moves the window forward/replaces the old window with the new window, and `compute` just returns the data structure inside.

**Comment by selik** [comment]
Currently, iterating over a `pandas.core.window.Rolling` object will produce bizarre behavior. For DataFrames as it looks for columns named `0`, `1`, `2`, etc. until it hits a KeyError. For Series it raises AttributeError as it looks for a "columns" attribute.

Until the `__iter__` is implemented correctly, perhaps there should be a temporary measure of simply making it non-iterable by raising NotImplementedError.

**Comment by jreback** [comment]
@selik if you want to submit a PR to raise NotImplementedError would be great!

**Comment by antoinecomp** [comment]
Okay, how to cope with this problem then ?

I have an object, `EWM [com=9.5,min_periods=0,adjust=True,ignore_na=False,axis=0]` that I want to add to a dataframe:` predictions_df_list['ewma']` which raised this issue

**Comment by selik** [comment]
@antoinecomp Could you share a bit more of your code and the error message?

**Comment by antoinecomp** [comment]
@selik Sorry for answering so late. This is the code I used:

`predictions_df['ewma'] = pd.DataFrame.ewm(predictions_df["prices"], span=60)#, freq="D")`

And this is the error message: 

```
NotImplementedError                       Traceback (most recent call last)
<ipython-input-153-2a1b97ea7cf7> in <module>
----> 1 predictions_df['ewma'] = pd.DataFrame.ewm(predictions_df["prices"], span=60)#, freq="D")

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py in __setitem__(self, key, value)
   3117         else:
   3118             # set column
-> 3119             self._set_item(key, value)
   3120 
   3121     def _setitem_slice(self, key, value):

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py in _set_item(self, key, value)
   3192 
   3193         self._ensure_valid_index(value)
-> 3194         value = self._sanitize_column(key, value)
   3195         NDFrame._set_item(self, key, value)
   3196 

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py in _sanitize_column(self, key, value, broadcast)
   3385             value = _sanitize_index(value, self.index, copy=False)
   3386 
-> 3387         elif isinstance(value, Index) or is_sequence(value):
   3388             from pandas.core.series import _sanitize_index
   3389 

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\dtypes\inference.py in is_sequence(obj)
    470 
    471     try:
--> 472         iter(obj)  # Can iterate over it.
    473         len(obj)   # Has a length associated with it.
    474         return not isinstance(obj, string_and_binary_types)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\window.py in __iter__(self)
    184     def __iter__(self):
    185         url = 'https://github.com/pandas-dev/pandas/issues/11704'
--> 186         raise NotImplementedError('See issue #11704 {url}'.format(url=url))
    187 
    188     def _get_index(self, index=None):

NotImplementedError: See issue #11704 https://github.com/pandas-dev/pandas/issues/11704
```

**Comment by selik** [comment]
It looks like `is_sequence`'s test of `iter(obj)` catching `TypeError` and `AttributeError` is inconsistent with `__iter__` raising `NotImplementedError`.

https://github.com/pandas-dev/pandas/blob/caf462c2a7699daf4b149d49f5aeaff822700113/pandas/core/dtypes/inference.py#L495

Reverting to the old behavior won't fix this, because `iter(obj)` would cause a `KeyError`, which is also unexpected.

@topper-123 @evectant I'm not familiar with the `ewm` method. Is a NotImplementedError reasonable here?

@jreback Should `is_sequence` catch NotImplementedError in addition to TypeError and AttributeError when trying `iter(obj)`?

**Comment by TexFly** [comment]
I'm getting the same error in core/windows.py
 raise NotImplementedError("See issue #11704 {url}".format(url=url))

Any solution?
Thanks!

**Comment by selik** [comment]
@TexFly Are you trying to iterate over a window object? If so, it's as the error says: not implemented.

**Comment by yasersakkaf** [comment]
@antoinecomp Did you solve the error. I am getting the same.

**Comment by TomAugspurger** [comment]
There's a stalled branch at https://github.com/pandas-dev/pandas/pull/27399 if anyone wants to pick this up.

**Comment by fallenreaper** [comment]
I have a Dataframe i was planning to use with ewm, but it seems that when I say:

```dt["myCol"].ewm(span=21, ignore_na=true)```

it will tell me to come to this Github error.  Is there a new way we should be doing this, in either 0.25.0 or 1.0.1?

**Comment by harimohanshrm7** [comment]
@antoinecomp 
this error will go away if you use an aggregator function at the end of statement. 
e.g.
predictions_df['ewma'] = pd.DataFrame.ewm(predictions_df["prices"], span=60).mean()

**Comment by andrewm4894** [comment]
If i wanted to do something like this:

```
import pandas as pd

df = pd.DataFrame(
    [
        [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2]
     ],
    columns=['x', 'y']
)

cols_todo = ['x']
for col in cols_todo:
    df[f'{col}_pct_chg'] = df[col].pct_change()
    df[f'{col}_pct_chg_ma3'] = df[f'{col}_pct_chg'].rolling(3)
    df[f'{col}_pct_chg_ma5'] = df[f'{col}_pct_chg'].rolling(5)
```

Does anyone know what the best current workaround would be?

**Comment by banderlog** [comment]
In which pandas version it will appear?

The `pandas-1.04` still shows `NotImplementedError`

**Comment by TomAugspurger** [comment]
1.1 (See the "milestone" on this issue).
