### ISSUE TITLE
ENH: avro to/from serialization

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#11752]
discussed in #3525 

shiny new fast version of avro might be interesting: https://github.com/MaxPoint/cyavro/issues/1
by @mariusvniekerk

**Comment by jreback** [comment]
cc @wesm

**Comment by wesm** [comment]
any performance numbers on cyavro vs pyavroc vs fastavro?

**Comment by VelizarVESSELINOV** [comment]
:+1:

**Comment by manugarri** [comment]
:+1:

**Comment by Khrol** [comment]
👍

**Comment by manugarri** [comment]
any updates on this? I am willing to put time to implement this, however would need some pointers, specially regarding:

- Would we cast pandas dtypes into avro automatically? Or would we enforce a user defined schema? I believe the pandas approach would be the former, but it would be good (and easier) to allow for a specific schema. Casting the types would require some assumptions (avro has support for [a set of primitives](https://avro.apache.org/docs/1.2.0/spec.html#schema_primitive) that might not match pandas').

- Would `read_avro` support for headerless data (i.e. streaming data without the header)? Would make sense, to allow this feature as long as the user provides the schema.

**Comment by wesm** [comment]
One possible route for this is https://issues.apache.org/jira/browse/ARROW-1209 -- @mariusvniekerk has started working on this, and it would be easier to accommodate Avro's types in Arrow and deal with the marshaling to/from pandas DataFrame at a central location in Arrow-land.

**Comment by jbrockmendel** [comment]
Is this a live topic or is it subsumed by more recent arrow ecosystem developments?

**Comment by wesm** [comment]
Arrow-based Avro read/write isn't shipping yet, @emkornfield is interested in this as it relates to various Google services (among other uses). Hard to predict the timeline for that, though.

**Comment by emkornfield** [comment]
Yes, I'm hoping to make some progress on this towards the end of this month/early next month.

**Comment by jbrockmendel** [comment]
Closing and adding to a tracker issue #30407 for IO format requests, can re-open if interest is expressed.

**Comment by tswast** [comment]
Given that the tracker issue was closed in favor of the label, I think it makes sense to re-open this as it's the earliest request I can find for avro support.

Also, with the announcement of https://arrow.apache.org/blog/2025/10/23/introducing-arrow-avro/ , it seems that this issue might be easier to implement this now.
