### ISSUE TITLE
display.notebook_repr_html -> display.html.notebook

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#11784]
reorg on the html options, which I think we are going to need some more e.g. `df.style`.

This will make it more consistent with the option config style

need to deprecate the original and add new.

**Comment by jreback** [comment]
anyone want to do this one?

**Comment by TomAugspurger** [comment]
@rdk1024 do you have time / interest to do this? It'll be similar to your work in https://github.com/pandas-dev/pandas/pull/16970

We're doing a release candidate near the end of the week.

**Comment by jreback** [comment]
closing as just a cosmetic change for no real reason.
