### ISSUE TITLE
raise ValueError in DataFrame.groupby.apply when index is duplicated

### ISSUE THREAD

**Issue by quantchen** [pandas-dev/pandas#11810]
Exception is raised when the index is duplicated

Fro example:

```
df = pd.DataFrame([['a',1],['b',1],['a',2],['b',2]],columns=['c1','c2'], index=list('ccdd'))

df.groupby('c1').apply(lambda x:x)

raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis
```

This is a new issue affecting 0.17

**Comment by jreback** [comment]
this is untested path; this repros < 0.17.0 as well.

**Comment by rhshadrach** [comment]
This is fixed on master, just needs tests.

**Comment by DriesSchaumont** [comment]
@rhshadrach, I think this is fixed in https://github.com/pandas-dev/pandas/pull/30679 with duplicate issue https://github.com/pandas-dev/pandas/issues/30667

**Comment by rhshadrach** [comment]
Great find - thanks @DriesSchaumont!
