### ISSUE TITLE
API: Use different exception type when MultiIndex indexing fails due to index not being lexsorted

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#11897]
I'd like to be able to separately trap errors in indexing that are due to the lack of the `MultiIndex` being lexsorted.  Right now, a `KeyError` is raised, and the only way to tell if the error was due to the lack of a lexsort versus a missing key is to look at the text of the message.

So I'd like to avoid code like this:

``` python
try:
    subdf = df.loc['A':'D','Vals']
except KeyError as ker:
    if ker.args[0].startswith("MultiIndex Slicing requires the index to be fully lexsorted"):
        print ("Need to handle fact index not sorted")
    else:
        print ("Need to handle fact that key was missing")
```

I'd rather write something like:

``` python
try:
    subdf = df.loc['A':'D','Vals']
except UnsortedIndexError:
    print ("Need to handle fact index not sorted")
except KeyError:
    print ("Need to handle fact that key was missing")
```

So could the designers accept a change where a different error is raised in case the index is not lexsorted?  If so, I'll implement it.

**Comment by jreback** [comment]
pls show a complete example uptop

**Comment by Dr-Irv** [comment]
Here is an example:
```python
mi = pd.MultiIndex.from_tuples([('z','a'),('x','a'),('y','b'),('x','b'),('y','a'),('z','b')], names=['one','two'])
df = pd.DataFrame([[i,10*i] for i in range(6)], index=mi, columns=['one','two'])
print(df.loc(axis=0)['z',:])
```
The last line fails with:
`KeyError: 'MultiIndex Slicing requires the index to be fully lexsorted tuple len (2), lexsort depth (0)'`

Now consider where we do the sorting:
```python
df.sort_index(inplace=True)
print(df.loc(axis=0)['z',:])
print(df.loc(axis=0)['q',:])
```
The second line works because things are now sorted, but the last line fails with:
`KeyError: 'q'`

So I'd like to be able to surround all of the above code with ways of detecting the 2 different errors, which will make debugging easier.

**Comment by shoyer** [comment]
I like this idea. To preserve backwards compatibility, we might make it a KeyError subclass. Note that there are also some cases where indexing non-multiindexes can raise a KeyError because the index is unsourced (notably, when slicing).

**Comment by jreback** [comment]
would for sure have to be a ``KeyError`` for back-compat. (ideally this should be a ``ValueError``, but that boat has sailed).

**Comment by Dr-Irv** [comment]
@jreback So should I create the `UnsortedIndexError` code, test it, and do the pull request?

**Comment by jreback** [comment]
@Dr-Irv interested in working on this?

**Comment by Dr-Irv** [comment]
Yes, but it might be a while, as I've got some other pressing issues.
