### ISSUE TITLE
list recent Pandas tutorial in Wiki and webpage

### ISSUE THREAD

**Issue by stonebig** [pandas-dev/pandas#11919]
I found the excellent and excellently-recorded pycon 2015 pandas tutorial among a forest of tutorials.

wouldn't it be nice for newcomer to find a link to it (or other excellent ones) in the website or the Wiki ?

**Comment by MaximilianR** [comment]
This? https://www.youtube.com/watch?v=5JnMutdy6Fw
Looks good!

**Comment by stonebig** [comment]
yes,

**Comment by TomAugspurger** [comment]
http://pandas.pydata.org/talks.html (source is [here](https://github.com/pydata/pandas-website/blob/56778dbf4cd855fb306a6ecadb9d7e11e5795b7b/talks.rst))

**Comment by jorisvandenbossche** [comment]
And there is also this page in the docs: http://pandas.pydata.org/pandas-docs/stable/tutorials.html

**Comment by TomAugspurger** [comment]
Thoughts on consolidating it to one place? Probably in the docs I’d say, and link to that from the main site. It might not look the best to have that page so far out of date.

-Tom

**Comment by stonebig** [comment]
the tutorial section would need a refresh, unless there is nothing new since 2013

**Comment by jreback** [comment]
certainly would take updates to the tutorials section in the docs and/or updates to ``pandas.pydata.org`` , you can submit [here](https://github.com/pydata/pandas-website)

**Comment by stonebig** [comment]
argh, github doesn't help me find the "Tutorials" part , can you finger point it ?

**Comment by jreback** [comment]
http://pandas.pydata.org/pandas-docs/stable/tutorials.html in pandas docs

https://github.com/pydata/pandas-website/blob/master/talks.rst for the website (which prob should just point to the tutorials docs)

**Comment by stonebig** [comment]
Sorry being clueless: I still don't understand where/how to edit the "http://pandas.pydata.org/pandas-docs/stable/tutorials.html" page.

Talks is ok

**Comment by TomAugspurger** [comment]
The source for that is in `doc/source/tutorials.rst`

Some info [here](https://github.com/pydata/pandas/wiki#for-documentation-authors <https://github.com/pydata/pandas/wiki#for-documentation-authors>) on working with the docs.

**Comment by TomAugspurger** [comment]
A few more links if you want

Intro:
https://www.youtube.com/watch?v=TSsSWuhBpmY <https://www.youtube.com/watch?v=TSsSWuhBpmY>

https://www.youtube.com/watch?v=otCriSKVV_8 <https://www.youtube.com/watch?v=otCriSKVV_8>

Intermediate:

https://www.youtube.com/watch?v=2RW9zSQF1Sk <https://www.youtube.com/watch?v=2RW9zSQF1Sk>

**Comment by stonebig** [comment]
ok, I didn't thought about looking at the Wiki Section. (shame on me)

**Comment by stonebig** [comment]
I don't dare editing the Wiki 'Tutorial' part. In this MOOC-ridden world, shouldn't the Tutorial section contain :
   . videos+associated material focussed on Pandas only,
   . usefull tricks sheet (rename columns, ...)
   . usefull online resources sheet (api page, free online docker-prepared images) ,
   . small FAQ (concepts of Split / Apply / Combine, DPLYR/Pandas comparison notebook, ...)
   . MOOCs using Pandas (then 1 link per university, sort by country/university ?)
