### ISSUE TITLE
API: expose pd.to_time

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#11947]
xref: https://github.com/pydata/pandas/pull/11832 allows `pandas.tseries.tools.to_time` to parse `time` types (into `datetime.time`) objects. These are not first class within the pandas data structures. But still may want to expose this.

**Comment by jreback** [comment]
xref #8343

**Comment by ricardogando** [comment]
Hi, is this issue still valid? Thanks

**Comment by DriesSchaumont** [comment]
@jreback can is issue be closed?
