### ISSUE TITLE
DataFrame.boxplot() ignored figsize keyword

### ISSUE THREAD

**Issue by cswarth** [pandas-dev/pandas#11959]
The [DataFrame.boxplot](http://pandas.pydata.org/pandas-docs/version/0.17.1/generated/pandas.DataFrame.boxplot.html) reference documentation says I can change the size of a plot though the `figsize` keyword, but this appears not to work.

Using `df.plot(kind='box')` does respect `figsize`.

```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys

print("pandas version = {}".format(pandas.__version__))
print("python version = {}".format(sys.version))
df = pd.DataFrame(np.random.rand(10, 5), columns=['A', 'B', 'C', 'D', 'E'])
df.plot(kind='box', figsize=(12,8))
plt.show()

df.boxplot(return_type='axes', figsize=(12,8))
plt.show()
```

![screen shot 2016-01-04 at 6 02 34 pm](https://cloud.githubusercontent.com/assets/295428/12105825/6a9748c2-b30d-11e5-876c-9c4ade88976d.png)

**Comment by TomAugspurger** [comment]
Thanks for the report.

We are generally steering people towards the `df.plot` API, but I think `boxplot` has a couple quirks that haven't been handled from the .plot(kind=) side.

**Comment by cswarth** [comment]
Thanks Tom, I just ran across the note about this in the

**Comment by cswarth** [comment]
Thanks Tom, I just ran across the note about the [`df.plot` API ](http://pandas.pydata.org/pandas-docs/version/0.17.0/whatsnew.html#whatsnew-0170-plot) in the 0.17.0 release notes.

**Comment by lermana** [comment]
I also ran into this issue just now (I am using .19 Pandas) when using the _boxplot_ method. But following Tom's advice - using df.plot.box, as opposed to df.boxplot - solved the problem

**Comment by JimStearns206** [comment]
Two questions:
- Should boxplot's grid parameter default to True? (see def for boxplot() in _core.py). That does not appear to be the case with df.plot(kind='box').
- This is likely my newbie error, but: 
-- when I run the test program from PyCharm, df.boxplot() shows the correct (12,8) figsize. 
-- when I run the test program from the command line (i.e. "python test11959.py), df.boxplot() shows a figsize of (6.4, 4.8).
In both cases I believe the same dev environment pandas is being used (judging by pd.\_\_version__, pd.\_\_file__)

**Comment by TomAugspurger** [comment]
> Should boxplot's grid parameter default to True? (see def for boxplot() in _core.py). That does not appear to be the case with df.plot(kind='box').

I suppose it's been like that for a while. It should probably follow `axes.grid`...

> This is likely my newbie error, but:

I'm not sure why that would be. Keep in mind that the *default* hasn't changed, `df.boxplot` just respects it now. Is it possible that its two separate environments with different matplotlib versions? The matplotlib default figsize did change in 2.0

**Comment by TomAugspurger** [comment]
Closed by #16445

**Comment by JimStearns206** [comment]
> I suppose [boxplot showing grid lines, but plot(kind='box')] has been like that for a while. It should probably follow axes.grid...

plt.boxplot does not show gridlines by default. df.plot(kind='box') follows that convention, but df.boxplot() does not.  Pngs:
![plt_boxplot](https://user-images.githubusercontent.com/9705309/27016060-2d6baa50-4ed0-11e7-8752-050d3a81dc9e.png)
![pd_plot_kind_box](https://user-images.githubusercontent.com/9705309/27016063-3428c92c-4ed0-11e7-9925-d519d7577dd1.png)
![pd_boxplot](https://user-images.githubusercontent.com/9705309/27016065-37b2e56e-4ed0-11e7-8917-946d6b6bf1de.png)

Test program attached. Writing the test program revealed some more discrepancies:
* The color scheme for box border and quartile and median lines differs between matplotlib and pandas. But the color scheme within pandas is consistent, and better IMHO than matplotlib's, so I don't propose changing pandas here.
* pd.plot() supports keyword arguments such as title. pd.boxplot does not. (See "Side excursion" in attached test program). But neither does plt.boxplot(). So should pd.boxplot be consistent with pd.box(kind='box') or with plt.boxplot()? Dunno - your call.

If you agree that df.boxplot should follow the no grid line default of plt.boxplot(), I'll create an issue and fix it.

If you agree that df.boxplot should support keyword arguments, I'll add that to the same issue or create another issue, and fix that as well.

```
import matplotlib.pyplot as plt
import numpy as np
# Modify PYTHONPATH appropriately to find pandas development version.
import pandas as pd
import sys

print("pandas version = {}, from={}".format(pd.__version__, pd.__file__))
print("python version = {}".format(sys.version))

def is_grid_on(axes):
    """
    From pandas/tests/plotting/common.py._check_grid_settings._is_grid_on

    :return: True if plot has grid on else False
    """
    xoff = all(not g.gridOn
               for g in axes.xaxis.get_major_ticks())
    yoff = all(not g.gridOn
               for g in axes.yaxis.get_major_ticks())
    return not (xoff and yoff)


dataset = np.random.rand(10,5)
df = pd.DataFrame(dataset, columns=['A', 'B', 'C', 'D', 'E'])
figsize=(3,2)

# Matplotlib boxplot
fig = plt.figure(1, figsize=figsize)
ax = fig.add_subplot(111)
bp = ax.boxplot(dataset)
plt_boxplot = plt.boxplot(dataset)
plt.title("plt_boxplot")  # plt.boxplot() doesn't support title as keywd arg
fig.savefig('plt_boxplot.png')
# plt.show()
assert not is_grid_on(ax)

# Pandas plot(kind='box')
pd_plot_kind_box = df.plot(kind='box', figsize=figsize,
        title="pd_plot_kind_box.png")  # pd.plot() supports title keywd arg
pd_plot_kind_box.get_figure().savefig('pd_plot_kind_box.png')
# plt.show()
assert not is_grid_on(pd_plot_kind_box.axes)

# Pandas boxplot

# Side excursion: df.boxplot doesn't support title parameter. Should it?
try:
    pd_boxplot = df.boxplot(return_type='axes', figsize=figsize,
                            title='pd_boxplot.png')
except TypeError as te:
    assert te.args[0] == "boxplot() got an unexpected keyword argument 'title'"

pd_boxplot = df.boxplot(return_type='axes', figsize=figsize)
plt.title("pd_boxplot.png")
pd_boxplot.get_figure().savefig('pd_boxplot.png')
# plt.show()
assert not is_grid_on(pd_boxplot.axes)
```

**Comment by TomAugspurger** [comment]
I'm inclined to just leave it as is for now.
