### ISSUE TITLE
Docs: start a pandas style guide

### ISSUE THREAD

**Issue by wesm** [pandas-dev/pandas#11955]
Per things like #11954 it would be good to make a list of style preferences that are not officially a part of PEP8 or linting tools

**Comment by JanSchulz** [comment]
more a meta style: more internal docs :-) there are lots of internal functions which do not have docstrings and algorithm are also often missing comments, too. It would be nice if new code could improve on that.

**Comment by kawochen** [comment]
Cython code as well

**Comment by simonjayhawkins** [comment]
Some code standards and style guidlines are included in the contributing guide, https://dev.pandas.io/docs/development/contributing.html. Please feel free to open a new issue with any suggestions for improvement.
