### ISSUE TITLE
DOC: fully document Index types

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#11962]
- add to API.rst
  - [ ] `Int64Index`
  - [ ] `Float64Index`
  - [ ] `PeriodIndex`
  - [x] `MultiIndex` (#11893)
  - [ ] `RangeIndex` (#11892)
- add to main docs (`CategoricalIndex` / `Float64Index` described in MultiIndex / Advanced Indexing sections). Expand this section to include.
  - [ ] `Index`
  - [ ] `DatetimeIndex/TimedeltaIndex/PeriodIndex` (already in timeseries.rst/timedelta.rst, need to cross-link to new section)
  - [x] `Int64Index`
  - [x] `RangeIndex`

cross-link from internals.rst about the Index internals.

**Comment by jorisvandenbossche** [comment]
This is done in the meantime. All classes are added to api.rst (but without automatically all their methods), and the 'special' methods for each of the classes is listed manually.
