### ISSUE TITLE
separate sparsify for header and body

### ISSUE THREAD

**Issue by youlyst** [pandas-dev/pandas#11987]
hi
i would welcome if option `sparsify` could be set separately for header and body
as i want body without `sparsify=False` and head with `sparsify=True`
what do you think about it?

**Comment by jreback** [comment]
pls show an example of what you mean

**Comment by youlyst** [comment]
i mean `sparsify` parameter in DataFrame`to_html`  
`df.to_html(sparsify_head=True, sparsify_body=False)`

**Comment by jreback** [comment]
not sure what this would mean. can you show an example.

**Comment by youlyst** [comment]
if i well inderstand doc string
    sparsify : bool, optional
        Set to False for a DataFrame with a hierarchical index to print every
        multiindex key at each row, default True
each row means that above aplies also on columns
so it is imposible to handle use case with i.e to sparsify only rows and not columns in html header

**Comment by youlyst** [comment]
so maybe `sparsify` could be integer instead of bool, and it will allow to hold choices like:
0 - dont sparsify at all
1 - sparsify only header
2 - sparsify only body
3 - sparsify both header and body

**Comment by jreback** [comment]
xref #11610 

@youlyst I am inclined to have this done thru the new ``.style`` interface which allows customization of html repr. ``.to_html`` will use this at some point.

cc @TomAugspurger

**Comment by TomAugspurger** [comment]
Yeah I've been working on sparsify a bit. Should have something next week.

**Comment by attack68** [comment]
df.style.to-html can already do this. perhaps will extend to df.to-html when the redirection is in place.

**Comment by mroeschke** [comment]
Closing as this feature is available in Styler
