### ISSUE TITLE
COMPAT: add >= 2.7 features

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#11993]
xref #7718 
xref #11988 

since we recently removed 2.6 (and 3.3) support, we are now free to use some features of later releases.
Some of these may be useful. We should investigate and create individual issues.

see [here](https://docs.python.org/2/whatsnew/2.7.html)
- The syntax for set literals (`{1,2,3}` is a mutable set).
- Dictionary and set comprehensions (`{i: i*2 for i in range(3)}`).
- `io` library (#10470)
- `argparse` (rather then `optparse`)
- maybe dictviews
- memoryviews
- `sysconfig`
- automatic number in `.format`

```
>>> '{}:{}:{day}'.format(2009, 4, day='Sunday')
'2009:4:Sunday'
```
- using `assertRaises` as a context manager

```
with self.assertRaises(KeyError):
    {}['foo']
```
- lots of other improved testing goodies!

**Comment by kawochen** [comment]
xref #10470

**Comment by jbrockmendel** [comment]
@jreback closeable?

**Comment by jreback** [comment]
sure
though maybe nice to create a new issue of things that we might want to use but don’t have already (some of the latter on this list)
