### ISSUE TITLE
DOC: use RTD for doc builds / hosting

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#12003]
now RTD support conda, see [here](https://github.com/rtfd/readthedocs.org/issues/857).

for pure-python packages this is quite easy (e.g. @shoyer just added `xray` support).

We would have to build a conda package on travis. and push to our channel. Which is then pulled from RTD.

**Comment by shoyer** [comment]
We might even be able to build pandas on RTD -- compiling pandas only takes
a few minutes on my machine, and conda will let us install up to date
dependencies.

**Comment by jreback** [comment]
I wasn't aware that you could actually *compile* things on RTD, really?

**Comment by shoyer** [comment]
Yep, it runs setup.py. You just can't compile dependencies -- but now we'll be able to install matplotlib, scipy, pytables, etc with conda.

**Comment by jreback** [comment]
oh if that's the case, then great! 

your *next* project!

**Comment by jbrockmendel** [comment]
@datapythonista is this actionable/desirable?

**Comment by datapythonista** [comment]
I'm not the right person to tell, I don't understand our build system so well. But seems like this could make our lives easier, so I'll do some research while working on the documentation refactoring.

**Comment by jorisvandenbossche** [comment]
I think the main problem is that our docs take a long time to build (on travis often between 40 and 50 minutes), while https://docs.readthedocs.io/en/latest/builds.html mentions a limit of 15 min (I thought it was longer, but that is in any case way too short)

**Comment by shoyer** [comment]
It's 15 minutes, but RTD builds your docs with Sphinx at least 3 times. I'm
pretty sure it would be unworkable for pandas.

**Comment by jorisvandenbossche** [comment]
OK, let's close this then.
