### ISSUE TITLE
add indent support to `to_json` method

### ISSUE THREAD

**Issue by phretor** [pandas-dev/pandas#12004]
Sometimes you just want to have a quick look at your data in IPython and having `to_json` to support `indent` (as both `json.dumps` and `simplejson.dumps` do) would be very handy.

A workaround, which however doesn't always work, is to do `json.dumps(series.to_dict())`, which unfortunately is annoying when you don't have a JSON-serializable type (e.g., `numpy.bool_`).

I'm leaving this here as a food for discussion.

**Comment by ludaavics** [comment]
Another workaround: `df_json_pretty = json.dumps(json.loads(df.to_json()), indent=2)`

**Comment by devforfu** [comment]
Is it still on the list to be implemented?

**Comment by TomAugspurger** [comment]
Still open. Feel free to work on it if you want, but the current json isn't the friendliest.

**Comment by devforfu** [comment]
@TomAugspurger Ok, got it! I'll try to figure out if there is a straightforward way to deal with it.

**Comment by TomAugspurger** [comment]
Yep that sounds right. FYI, I think ripping out that JSON code and
replacing it with something more maintainable
(maybe based on Apache Arrow's JSON support) is on the medium to long-term
agenda.

**Comment by kylebarron** [comment]
Is the current JSON writer believed to be much faster than the Python standard library's JSON writer?

**Comment by TomAugspurger** [comment]
Yep. It also handles types not supported by the stdlib's json writer
(notably numpy types).

**Comment by botenvouwer** [comment]
I agree on this, JSON is also meant to be human readable. Right now this is just annoying.
