### ISSUE TITLE
BLD: make bottleneck a required dependency

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#12149]
xref #12141 

currently we have backup routines for everywhere we use bottleneck.

If we made it a requirement (rather than a highly recommended dep) we could forgo this.

its easily installable via `conda` and `pip` (wheels); this used to be an issue.

**Comment by jbrockmendel** [comment]
Time may be right for this.

**Comment by jreback** [comment]
sure would take a PR for this i think

**Comment by mroeschke** [comment]
Based on the discussion in https://github.com/pandas-dev/pandas/pull/24300. Seems like we'd prefer moving away from bottleneck and towards Numba. Closing.
