### ISSUE TITLE
TST: _reset_cache on any defined fixtures between tests

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#12150]
xref #12130 

we should clear() the _cache variable (set by `cache_readonly`) in between unit tests. same with the DataFrame tests.

this will prevent any tests from mutating these 'fixtures' and causing issues in later tests

**Comment by jreback** [comment]
cc @wesm

**Comment by jbrockmendel** [comment]
Our fixtures generally create new objects for each test.  I don't think there's anything to do here.  Closing.
