### ISSUE TITLE
Appending HDF5 store leads to crash

### ISSUE THREAD

**Issue by jpiabrantes** [pandas-dev/pandas#12166]
I am appending an HDF5 store with a pandas dataframe and Python crashes without any traceback.

``` python
chunk.to_hdf('all_data.h5', 'df',mode='a',format='table',append=True)
```

Discussion on stackoverflow:

http://stackoverflow.com/questions/31419768/pandas-appending-suing-to-hdf-now-crashes-after-updating-to-pytables-3-2

**Comment by TomAugspurger** [comment]
Could you post a snippet of code that causes this, and your [versions](https://github.com/pydata/pandas/blob/master/CONTRIBUTING.md#bug-reports-and-enhancement-requests)?

Note that HDF5 is not threadsafe for simultaneous writes.

**Comment by jpiabrantes** [comment]
My versions:
pandas.__version__ = 0.16.2
numpy.__version__  = 1.9.2
Python 2.7.10

the code is just:

```chunk.to_hdf('all_data.h5', 'df',mode='a',format='table',append=True)```
chunk is dataframe. It appends a couple of times until crashing

**Comment by TomAugspurger** [comment]
Thanks, you you post the output of `pd.show_version`?

What do you mean it appends a couple times? Chunk is defined in a for loop?  If I try pasting your code, `chunk` is undefined.

**Comment by jreback** [comment]
@jpiabrantes pls show a copy-pastable example that fails. as well as a comple ``pd.show_versions()``

**Comment by jpiabrantes** [comment]
@TomAugspurger sorry I meant to close this issue because I no longer have the reproducible example
