### ISSUE TITLE
"cumplyr"-like functionality

### ISSUE THREAD

**Issue by wesm** [pandas-dev/pandas#1220]
cc @johnmyleswhite

http://www.johnmyleswhite.com/notebook/2012/05/03/cumplyr-extending-the-plyr-package-to-handle-cross-dependencies/

**Comment by Compro-Prasad** [comment]
I tried to install the `cumplyr` package but found out that it was not updated for the latest R. Is there any suggestion? The package is very simple in itself as it has only 6 functions on the website: https://www.rdocumentation.org/packages/cumplyr/versions/0.1-1

Would be great if I could test it out.

**Comment by MarcoGorelli** [comment]
doesn't look like there's been any activity on this in >10 years, so I think we can close it now to reduce the queue?

**Comment by MarcoGorelli** [comment]
closing as per the above
