### ISSUE TITLE
Support Infinity, -Infinity and NaN in read_json

### ISSUE THREAD

**Issue by MaxNoe** [pandas-dev/pandas#12213]
While these special values are not strictly standard conform, most implementations do allow or use them.

For example Google's GSON Library or python's json module in the standard library.

**Comment by jreback** [comment]
nan's are already supported.

```
In [1]: df = DataFrame({'A' : [np.nan,1,np.inf,-np.inf]})

In [2]: df.to_json(None)
Out[2]: '{"A":{"0":null,"1":1.0,"2":null,"3":null}}'
```

**Comment by MaxNoe** [comment]
But not  `NaN` for reading: `pd.read_json('{"a": [NaN, Infinity, -Infinity]}`

**Comment by jreback** [comment]
that's not valid json

**Comment by MaxNoe** [comment]
I know, that's what I wrote in the first post. But it is a commonly used extension.

See the description in Google's GSON package:

>  Section 2.4 of JSON specification disallows special double values (NaN, Infinity, -Infinity). However, Javascript specification (see section 4.3.20, 4.3.22, 4.3.23) allows these values as valid Javascript values. Moreover, most JavaScript engines will accept these special values in JSON without problem. So, at a practical level, it makes sense to accept these values as valid JSON even though JSON specification disallows them.

Or python's json module:

> It also understands NaN, Infinity, and -Infinity as their corresponding float values, which is outside the JSON spec.

**Comment by MaxNoe** [comment]
Also interesting: the json specifications explicitly allow to accept extensions of the standard:
https://tools.ietf.org/html/rfc7159.html#section-9

>A JSON parser transforms a JSON text into another representation.  A
   JSON parser MUST accept all texts that conform to the JSON grammar.
   A JSON parser MAY accept non-JSON forms or extensions.

**Comment by mackaiver** [comment]
:+1: This would indeed be very helpful for interoperability between a pandas backend and a JS frontend.

**Comment by zls88** [comment]
I took a crack at this and discovered that the json library underlying read_json, [ujson](https://pypi.python.org/pypi/ujson/1.33), doesn't handle NaN nor infinity. In [previous discussions](https://github.com/esnme/ultrajson/issues/80) ([more](https://github.com/esnme/ultrajson/issues/146)) the authors of ujson resisted adding support because it's out of spec, and there's no way to specify a custom decodor nor encoder with ujson.

**Comment by maciejkula** [comment]
The newest master throws a `ValueError: Expected object or value` exception when trying to parse JSON containing `inf` of `nan` values. While I understand that these are not valid JSON, it might be helpful to throw more informative exceptions to help the user debug the issue.

Script to reproduce (using [Hypothesis](https://github.com/HypothesisWorks/hypothesis-python)):
```python
import json

from hypothesis import assume, example, given
import hypothesis.strategies as st

import pandas as pd

FAILING_EXAMPLES = (
    [{u'': float('inf')}],
    [{u'': float('nan')}],
)

@given(st.lists(st.dictionaries(st.text(),
                                st.floats() | st.booleans() | st.text() | st.none())))
@example([{u'': float('inf')}])
@example([{u'': float('nan')}])
def test_load_json(test_input):

    df = pd.read_json(json.dumps(test_input))
```

**Comment by MaxNoe** [comment]
Finally! Thanks to anyone involved in making this possible.
