### ISSUE TITLE
Assignment to mixed-type DataFrame with float32 coerce to float64

### ISSUE THREAD

**Issue by fnielsen** [pandas-dev/pandas#12255]
Assignment to mixed-type DataFrame with float32 numpy array coerce to float64

```
>>> import pandas as pd
>>> import numpy as np
>>> df = pd.DataFrame([[1, 2, 'a'], [3, 4, 'b']], dtype=np.float32)
>>> A = df.iloc[:, 0:1].values
>>> df.iloc[:, 0:1] = A
>>> df[0].dtype
dtype('float64')
```

Shouldn't the result be `dtype('float32')`?

See also http://stackoverflow.com/questions/35230388/why-does-pandas-coerce-my-numpy-float32-to-float64

**Comment by fnielsen** [comment]
It may be worth to note that float64 coercing with float32 can be considerably slow. I have another Stackoverflow question about that: 

http://stackoverflow.com/questions/35184681/assignment-of-pandas-dataframe-with-float32-and-float64-slow

The coercing here is over 10 times as slow.

**Comment by jreback** [comment]
This area of the code is quite complex and inference is pretty tricky, but I suppose.

```
In [13]: df.ix[:,0:1] = DataFrame(A)

In [14]: df
Out[14]: 
     0    1  2
0  1.0  2.0  a
1  3.0  4.0  b

In [15]: df.dtypes
Out[15]: 
0    float32
1    float32
2     object
dtype: object
```

**Comment by jreback** [comment]
submitting a PR would help move this along.

**Comment by jreback** [comment]
This is around [here](https://github.com/pydata/pandas/blob/master/pandas/core/indexing.py#L484)

**Comment by fnielsen** [comment]
The `DataFrame` trick does not work in all cases. If the columns are named 

    import pandas as pd
    import numpy as np
    columns = ['c0', 'c1', 'c2']
    df = pd.DataFrame([[1, 2, 'a'], [3, 4, 'b']], columns=columns, dtype=np.float32)
    A = df.ix[:, 0:1].values
    df.dtypes
    df.ix[:, 0:1] = pd.DataFrame(A)
    df.dtypes

The result yields a wrong datatype for the first column (c0) while the second column (c1) is correct:

    c0    float32
    c1    float32
    c2     object
    dtype: object
    c0    float64
    c1    float32
    c2     object
    dtype: object

This is contrary `df.ix[:, 0:1] = A` where all numerical columns wrongly coerce to float64.

**Comment by jreback** [comment]
This is not a *trick*, but a defined aligning operation. Assigning w/o the proper columns doesn't make much sense.

```
In [13]: df.ix[:, 0:1] = pd.DataFrame(A,columns=['c0'])

In [14]: df
Out[14]: 
    c0   c1 c2
0  1.0  2.0  a
1  3.0  4.0  b

In [15]: df.dtypes
Out[15]: 
c0    float32
c1    float32
c2     object
dtype: object
```

**Comment by rhshadrach** [comment]
The OP now raises. The closest I think we can do today is something like:

```
df = pd.DataFrame([[1, 2], [3, 4]], dtype=np.float32)
df[2] = 'a'
A = df.iloc[:, 0:1].values
df.iloc[:, 0:1] = A
print(df[0].dtype)
```

which results in float32. Not sure if this needs tests.

**Comment by mroeschke** [comment]
Since the original issue now raises as the indended behavior I think we can close this out
