### ISSUE TITLE
ENH: Make use of RangeIndex in DatetimeIndex 

### ISSUE THREAD

**Issue by kawochen** [pandas-dev/pandas#12272]
`DatetimeIndex` looks like it can benefit from `RangeIndex` #11892 .  
Use case 1: Evenly-spaced time-series analysis
Use case 2: I sometimes (ab)use `date_range` like a PY3 `range` in a for loop, which I think is quite neat.  It would be cooler if it were lazily evaluated.

**Comment by jreback** [comment]
@kawochen absolutely for 1 (might not even be that tricky as would simply need to move to sub-class from ``Int64Index`` to ``RangeIndex``

can you give a more full example for 2)?

**Comment by kawochen** [comment]
For 2) I just meant
```
for d in date_range('20110101', '20121225'):
    process(d)
```
It's much better than updating with some time delta, and quacks like `datetime.datetime`  enough that it serves all needs I have for the latter. 
It solves [this SO problem](http://stackoverflow.com/questions/1060279/iterating-through-a-range-of-dates-in-python) perfectly.

**Comment by jreback** [comment]
ah I c.

that brings up a good point actually. ``__iter__`` is NOT lazy ATM for ``Int64Index``, but for ``RangeIndex`` it certainly could/should be.

**Comment by MaximilianR** [comment]
+ `PeriodIndex`!

**Comment by mroeschke** [comment]
Looks like this idea never took off, and since it's possible for DatetimeIndex to be non-monotonic may make the complexity onerous so closing for now. Can reopen if there's interest
