### ISSUE TITLE
DOC: show how to use to_xarray then use xarray to perform analysis on Panels

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#12283]
I think we need a section to address this, not really sure where should put it. Also want to link from the doc-string.

also prob need some examples in the doc-string.

xref #11972

**Comment by jreback** [comment]
cc @MaximilianR 
@jorisvandenbossche 

not strictly necessary for 0.18.0 but if you can do something would be great.

**Comment by MaximilianR** [comment]
Yes, I have something for this, I will PR today or tomorrow

**Comment by jreback** [comment]
cc @MaximilianR

**Comment by MaximilianR** [comment]
D'oh! I wrote this back in Feb but forgot to PR. Just done that here: https://github.com/pydata/xarray/pull/832

**Comment by jorisvandenbossche** [comment]
@MaximilianR Would you like to add such a guide in the pandas docs as well? (not sure if it should be in both, but it feels like if we point users to xarray we should also give them some guidance)

**Comment by MaximilianR** [comment]
@jorisvandenbossche yes I can do that. Any feedback on the original PR?

**Comment by shoyer** [comment]
Note that this now appears in the xarray docs: http://xarray.pydata.org/en/stable/pandas.html#transitioning-from-pandas-panel-to-xarray

**Comment by jreback** [comment]
where should we add the link that @shoyer mentions in the pandas docs? (doc-strings).

ideally a PR!

now that https://github.com/pandas-dev/pandas/pull/15601 is getting close.

**Comment by jreback** [comment]
was added by #15601, certainly open to expanding docs if needed.
