### ISSUE TITLE
Unicode not suported in Style

### ISSUE THREAD

**Issue by rsdenijs** [pandas-dev/pandas#12312]
The styler does not seem to like unicode?

```
Reproduce by:
pd.DataFrame(['♚']).style

UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 0: ordinal not in range(128)
```

**Comment by jreback** [comment]
can you change the example so its copy-pastable (e.g. use the actual unicode code)

**Comment by gfyoung** [comment]
Indeed, an example would be useful, as I've used `Unicode` with `styler before without any issues.

**Comment by rsdenijs** [comment]
I updated it. 

The funny thing is, the problem only appears when it is a normal string, not with unicode
pd.DataFrame(['♚']).style -- > breaks
pd.DataFrame([u'♚']).style -- > works

Also,
pd.DataFrame(['♚']) 
is displayed correctly in the notebook (without .style)

**Comment by gfyoung** [comment]
Can you provide information on your `pandas` setup?  I was able to run that first line as well as the other two just fine on `0.17.1` using Python 2.7.11 on Ubuntu.

**Comment by rsdenijs** [comment]
python 2.7.6
pandas 0.17.1

**Comment by TomAugspurger** [comment]
This is how [Jinja works](http://jinja.pocoo.org/docs/dev/api/#unicode)


Here's a minimal example (python2)

```python
from jinja2 import Template

tpl = Template('{{ v }}')

tpl.render(v='♚')

UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-12-b262bfe8f233> in <module>()
      3 tpl = Template('{{ v }}')
      4 
----> 5 tpl.render(v='♚')

/Users/tom.augspurger/Envs/py27/lib/python2.7/site-packages/jinja2/environment.pyc in render(self, *args, **kwargs)
    987         except Exception:
    988             exc_info = sys.exc_info()
--> 989         return self.environment.handle_exception(exc_info, True)
    990 
    991     def stream(self, *args, **kwargs):

/Users/tom.augspurger/Envs/py27/lib/python2.7/site-packages/jinja2/environment.pyc in handle_exception(self, exc_info, rendered, source_hint)
    752             self.exception_handler(traceback)
    753         exc_type, exc_value, tb = traceback.standard_exc_info
--> 754         reraise(exc_type, exc_value, tb)
    755 
    756     def join_path(self, template, parent):

<template> in top-level template code()

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
```

whereas your example with u'♚' works. I'm not sure there's anything pandas can do here, you'll just have to make sure you're passing in `unicode` objects and not `str` objects (python2), In python3 these are the same.

**Comment by rsdenijs** [comment]
Probably the user does not need to no this quirk of jijnjas. 
Also, given the general level of confusion between unicode and str objects, it is also beocmes pretty frustrating.

Maybe pandas could raise its own exception? Something like

"RenderError: Render failed because the DataFrame contains characters that could not be decoded to unicode. Convert strings to unicode explicitely before using the Styler"

or at least say something in the docs?

**Comment by TomAugspurger** [comment]
I don't think we should just change a user's data from bytes to unicode strings without them explicitly telling us to, but I'm willing to be convinced otherwise if others think that's a good idea.

If you want python 3's behavior you can import `unicode_literals` from `__future__` (or use python 3).

Catching that exception and reraising with a nicer error message would be ok. We would need to worry about accidentally swallowing some other exception that raises a unicode error. A user could be doing some string formatting in a `style` function that raises a `UnicodeDecodeError` for other reasons. Interested in submitting a pull request?

**Comment by rsdenijs** [comment]
The problem is exactly as you say. If an error occurs for other reason, a "nicer" error message could actually be misleading. The best thing is maybe to just write it in the documentation that the use of unicode "strings" is recommended?

**Comment by TomAugspurger** [comment]
Sure, let's start with better docs and see how that goes.

**Comment by WillAyd** [comment]
This looks to be an old Py27 relic as I cannot reproduce on master with Py3
