### ISSUE TITLE
pandas-svn mailing list?

### ISSUE THREAD

**Issue by gfyoung** [pandas-dev/pandas#12429]
Upstream repositories like `numpy` and `scipy` have a `numpy-svn` and `scipy-svn` mailing list that is used to avert users of commits / merges to the `master` branch.  You can find those lists <a href="http://www.scipy.org/scipylib/mailing-lists.html">here</a> here.  I personally find it useful to get such emails because it allows me to make sure that my PR branches don't fall too far behind the `master` branch.  I see no reason why the `pandas` repository wouldn't benefit from such an emailing list either.

**Comment by gfyoung** [comment]
@jreback , @jorisvandenbossche : Are there any plans to do this in the near future?  Otherwise, I might just close this issue for the time being.

**Comment by jreback** [comment]
how is this different from github? if you have put up a PR then you will be notified of mentiones on that issue (or if you watch you get everything). This seems like something that may have been useful in the past, but not sure it makes sense here.

**Comment by gfyoung** [comment]
Adding a mailing notifies people whenever any PR gets merged into the code-base.  You don't necessarily have to be watching the PR to get notified as a result.  I found this to be useful to catch merge conflicts earlier because I got the notifications.

**Comment by jorisvandenbossche** [comment]
It's different as this gives you notifications of merges in master, not of messages on a PR/issue you are involved in. I can see some value of it, but as we are not using it ourselves, it will probably be not really a priority for us to do. 

@gfyoung Do you know how something like this could be set up? If it's easy, probably not a problem to do it.

**Comment by gfyoung** [comment]
@jorisvandenbossche : Hmmm...I think if you guys don't have much use for it, I'll close this for now.  I actually can't see any "easy" way to do this as I had previously imagined.

**Comment by jorisvandenbossche** [comment]
Do you know how numpy or scipy do it?

**Comment by gfyoung** [comment]
I was pretty sure it was a repository configuration, but I can't seem to find it anymore.
