### ISSUE TITLE
Panel resample fails for degenerate panels

### ISSUE THREAD

**Issue by killchr** [pandas-dev/pandas#12433]
#### Code Sample, a copy-pastable example if possible

```
import numpy as np
import pandas as pd

dr = pd.date_range('20100101','20151231',freq='T')
p1 = pd.Panel(items = dr, data=np.random.randn(len(dr),3,3))
#this works
p2 = p1.resample('D', axis=0, how='last')
p3 = pd.Panel(items = dr, data=np.random.randn(len(dr),1,1))
#this causes an error
p4 = p3.resample('D', axis=0, how='last')
```
## INSTALLED VERSIONS

commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.17.1
nose: 1.3.7
pip: 8.0.2
setuptools: 19.6.2
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.17.0
statsmodels: 0.6.1
IPython: None
sphinx: 1.3.1
patsy: 0.4.0
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.6
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.5.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.11
pymysql: None
psycopg2: None
Jinja2: 2.8

**Comment by jreback** [comment]
I think there is something messed up with the axis passing, related to #4905 

you can do this: (uses the new syntax in 0.18.0)

```
In [26]: p1.swapaxes(0,1).resample('D',axis=1).last().resample('D',axis=1).last()
Out[26]: 
<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 2191 (major_axis) x 3 (minor_axis)
Items axis: 0 to 2
Major_axis axis: 2010-01-01 00:00:00 to 2015-12-31 00:00:00
Minor_axis axis: 0 to 2
```

**Comment by jreback** [comment]
closing as Panel deprecated
