### ISSUE TITLE
BLD: Travis dedup via webhooks

### ISSUE THREAD

**Issue by kawochen** [pandas-dev/pandas#12438]
Came across this just now https://github.com/grosser/travis_dedup
It sounds like it cancels old builds on a PR.  It works via github webhooks.

**Comment by jreback** [comment]
oh that looks nice. ok i'll try this when I have some time.

**Comment by jreback** [comment]
ok I setup this webhook, let's monitor and see if this works

**Comment by gliptak** [comment]
@jreback I have seen builds cancelled for out-of-date (repushed) commits when working https://github.com/pydata/pandas/pull/12833

**Comment by jreback** [comment]
that was me :) sometimes I cancel the dups

**Comment by jorisvandenbossche** [comment]
For inspiration, there is a script in this PR on conda-forge to do something like this: https://github.com/conda-forge/staged-recipes/pull/2257

**Comment by jreback** [comment]
that's nice will steal!

**Comment by jreback** [comment]
https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation

on the day we push this feature....hahah

**Comment by jorisvandenbossche** [comment]
That's a timing :-)

Question is if they still run all jobs of a build once one job is started. Because if not, the script still has some use.

**Comment by jreback** [comment]
actual what they have is very nice
the second you push a new PR the original is completely cancelled

the script has to launch and it individually cancels - takes about 1 min per

**Comment by jreback** [comment]
and their feature allows cancellation on your own branch as well :>
