### ISSUE TITLE
ENH: add .dropinf() and/or .dropna(drop_inf=True) methods

### ISSUE THREAD

**Issue by adrivsh** [pandas-dev/pandas#12520]
There are known ways of droping inf and nan (.replace(np.inf, np.nan).dropna()) but still, the API could be expanded:

```
.dropinf(inplace=False) 

.dropna(drop_inf = False)
```

Are both self explanatory wishes and it is no stretch to see how they are usefull. 
Note for instance that today's API does not provide a one liner to drop inf in place while keeping nans.

Best

PS: not sure how to submit wishes.

**Comment by jreback** [comment]
```
In [1]: s = Series(np.random.randn(5))

In [2]: s[1] = np.nan

In [3]: s[2] = np.inf

In [4]: s[3] = -np.inf

In [5]: s
Out[5]: 
0    0.760816
1         NaN
2         inf
3        -inf
4    0.441029
dtype: float64

In [6]: s.dropna()
Out[6]: 
0    0.760816
2         inf
3        -inf
4    0.441029
dtype: float64
```

You can already do this
```
In [12]: with pd.option_context('use_inf_as_null',True):
   ....:     print(s.dropna())
   ....:     
0    0.760816
4    0.441029
dtype: float64
```

**Comment by TomAugspurger** [comment]
Using the context manager is OK, but I wouldn't want to encourage setting this option globally.

I'll typically use `s[np.isfinite(s)]` when I have infinities (which is often). This also doesn't make it clear that you're excluding NaNs (which apparently are defined to not be finite).

+0.5 on adding `dropinf` a method.

**Comment by jreback** [comment]
yep, just showing that as an example. I agree ``s[np.isifinite(s)]`` is pretty clear IMHO. maybe add to the docs? (could also add as a related example in ``.dropna`` doc-string)

**Comment by TomAugspurger** [comment]
The nice thing about `dropna` is you get the `how=any/all` and `axis=0/1` behavior too. If we go the doc route we should include examples on a DataFrame with those. And yeah, `np.isfinite`'s docstring states quite clearly that `NaN` is not finite.

**Comment by adrivsh** [comment]
I agree  s[np.isifinite(s)] is clear and works. So is  s[np.isnull(s)]. 
We nonetheless have dropna(). And we use dropna. It is convenient and pandaic. 
Why not also have dropinf() ? With all associated options: inplace, axis, how, etc.

**Comment by Zeroto521** [comment]
Hi, all.

In my work, I also need to handle `inf` and `NaN` separately.
I'm glad to implement `Series.dropinf` and `DataFrame.dropinf` methods.

Does these APIs still need?

**Comment by jreback** [comment]
a common idiom is

s.replace([-np.ing, np.inf], np.nan)

which is then daily dropped 

would be -1 on adding api

however happy to have additions to the doc-string of these idioms

**Comment by Zeroto521** [comment]
In some number type data.
`NaN` means missing value, I would like to use 0 to replace `NaN`.
`inf` means useless value because it is hard to reach such a big value in a specific condition. So I would like to remove `inf`.

> s.replace([-np.ing, np.inf], np.nan)

So I thought there better to handle `inf` and `NaN` separately.

**Comment by mroeschke** [comment]
Thanks for the suggestion but it appears there's not much support from the core team for this new feature so closing, but happy to reopen if there's renewed support
