### ISSUE TITLE
CLN: Cleanup plotting submodule

### ISSUE THREAD

**Issue by sinhrks** [pandas-dev/pandas#12548]
- Make `plotting` as subpackage
  - Split utility functions / non- `MPLPlot` classes to other files.
- Move tests under `plotting/*`
  - Add small unit tests to guarantee utility function APIs.
- Refactor `MPLPlot` class properties. Because `MPLPlot` now has lots of properties, split them to  `FigureProperties` and `AxesProperties` classes and delegates the logic.

This should makes #12547, #7670, #8018 easier.

**Comment by sinhrks** [comment]
Hopefully the cleanup should fix issues like #12565.

**Comment by TomAugspurger** [comment]
I've been wanting to do a cleanup for a while too :)

I won't really have time to take the lead on this, but I can at least commit to reviewing and testing everything.
