### ISSUE TITLE
CLN: hide all imported extensions

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#12588]
so most of these are in the top-level namespace, so let's rename to use `_` leading if not already like that.

e.g. `_lib` rather than `lib`

just requires some small changes in `setup.py`, but a fair number of imports need to be changed.
This is a slight API change, in that people could be relying upon it. So we _could_ create a deprecation warning if these names are accessed (and then have it work).

```
~/pandas]$ find pandas -name '*.so'
pandas/_period.so
pandas/_sparse.so
pandas/_testing.so
pandas/algos.so
pandas/hashtable.so
pandas/index.so
pandas/io/sas/saslib.so
pandas/json.so
pandas/lib.so
pandas/msgpack/_packer.so
pandas/msgpack/_unpacker.so
pandas/parser.so
pandas/tslib.so
```

**Comment by jorisvandenbossche** [comment]
This was closed by https://github.com/pandas-dev/pandas/pull/15537 and friends
