### ISSUE TITLE
Color by factor/group when plotting

### ISSUE THREAD

**Issue by GA-Goig** [pandas-dev/pandas#12639]
Hi everyone!

Sorry if this is not the correct place to write this, I'm new to GitHub.

I'm really enjoying pandas but I think there is a basic feature it does not implement, which is
easily color by factor when plotting a dataframe. At least I didn't be able to find how this could be done in a "Pythonic" way.

Say we have a dataframe with data records from weather stations. Different columns have the location of hundreds of stations and rows have measurements for different days of the month (say 30 rows). There is an additional column "Continent" that points which continent each weather station belongs to. Or maybe a separated Series object "as.type('categorical')"

The point is that it should be easy to plot this dataframe, keeping my data separated while coloring and labeling in legend with different colors for different groups, in this case 5 continents, so 5 colors and 5 legend labels.

I'm able to do this with some code, but I think it would be nice to have a feature like:

df.plot(color_by_group=df.Continent) or similar.

PD: Sorry if this, or anything really similar is already implemented.

**Comment by TomAugspurger** [comment]
I think you could already do this with the `color` parameter, if I understand your question correctly.

That said,  you're probably better off using seaborn. Most of it's plotting methods take a `hue` keyword, which would work for you.

**Comment by GA-Goig** [comment]
Thanks a lot for your help! However I'm not sure I made it clear before.
 
Let me show you a real example.

I have a dataframe of fluorescence values from a chemical reaction measured over 45 time points for many different samples. Having a dataframe where columns are samples and rows are measures for each of the 45 time points, a simple plot looks like this:

df.plot()
![figure_1](https://cloud.githubusercontent.com/assets/17823530/13814541/f3d232d0-eb86-11e5-98d4-4e4381efe4fe.png)

However each sample belongs to one of three groups. So I build a dictionary with colors for each one:

gcolors = {'Saliva': '#00B0F6', 'Blood': '#E58700', 'Feces': '#E76BF3'}

And then plot like TomAugspurger points, with color parameter:



df.plot(color=[gcolors[group] for group in SampleGroups])
\#SampleGroups was a column with group for each sample (something like df.Group)

![figure_2](https://cloud.githubusercontent.com/assets/17823530/13814757/d821adf8-eb87-11e5-9b91-f2f65cb05ff0.png)

It only remains to have a legend with just three labels "Saliva", "Blood", "Feces" with corresponding colors. (I don't know how to do this yet)

Anyway, here the point is that, if I am not wrong, it would be a nice simple feature to include in pandas since I think this a pretty common way of grouping and representing data.

**Comment by TomAugspurger** [comment]
I'd say pass `legend=False` and then add a legend manually. The 1-column=1-line=1-legend element is pretty central to the basic `DataFrame.plot`. There should be answers on stackoverflow for creating a custom matplotlib legend.

**Comment by jreback** [comment]
this is essentially implemented in https://github.com/pydata/pandas/pull/8018

**Comment by Ochirgarid** [comment]
@GA-Goig I think this issue is solved. Confirm and close the issue.
