### ISSUE TITLE
DOC: improve cross-links in docs between .expanding and .cum*

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#12651]
xref #12648 
- cross-link doc-strings for .cum\* to the .expanding().\* (for sum,prod,max,min, which are only supported).
- show an example (in computation.rst wher eexpanding is shown? or basics.rst (where cum\* are shown)) how these are related (w.r.t. NaN filling).

```
In [7]: s = Series([1,2,np.nan,3,np.nan,4])

In [8]: s.cumsum()
Out[8]: 
0     1.0
1     3.0
2     NaN
3     6.0
4     NaN
5    10.0
dtype: float64

In [9]: s.expanding().sum()
Out[9]: 
0     1.0
1     3.0
2     3.0
3     6.0
4     6.0
5    10.0
dtype: float64

In [10]: s.cumsum().ffill()
Out[10]: 
0     1.0
1     3.0
2     3.0
3     6.0
4     6.0
5    10.0
dtype: float64
```

**Comment by shawnheide** [comment]
@jreback I looked into this but am confused as to how to implement the cross-linking in the docstrings. The expanding function for dataframes and series don't have a doc page for .sum, .product, etc. As I understand it this is just chaining the .expanding method with the .sum method, so there shouldn't be a separate doc page right?

As an alternative we could just cross-link .expanding to all of the .cum* and vice-versa. But I'm not sure if that's what you were going for.

**Comment by jreback** [comment]
just show an example as indicated above
