### ISSUE TITLE
API: ban mutation within groupby.apply

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#12653]
xref https://github.com/pydata/pandas/issues/8662
xref #12652 

This makes pandas code jump thru hoops and is a complete anti-pattern for pandas. let's nuke it. users should _never_ do this.

**Comment by jbrockmendel** [comment]
agreed this is a footgun.  brainstorming how to implement:

- document that it isnt supported and be done with it
- maybe a contextmanager to make the relevant objects immutable within the relevant calls

**Comment by rhshadrach** [comment]
@jbrockmendel with the contextmanager, are you thinking doing a comparison after the apply call to see if the objects involved changed? Is there a way to avoid a copy here?

**Comment by jbrockmendel** [comment]
> with the contextmanager, are you thinking doing a comparison after the apply call to see if the objects involved changed? 

I am thinking of setting the `array.flags.writeable` to False for any ndarrays contained inside the DataFrame.  We'd need to implement something analogous for ExtensionArrays.

**Comment by rhshadrach** [comment]
I think of this issue apply to all UDF functions (apply, aggregate, transform, filter) on all pandas objects. @jbrockmendel - would you support just adding to the docs without the context manager? This would perhaps raise some awareness and I think doesn't require a deprecation, and gives a place we can point to when issues are reported.

**Comment by jbrockmendel** [comment]
> would you support just adding to the docs without the context manager

I think thats probably our best bet.  Something to point out when people inevitably open issues about this.

**Comment by rhshadrach** [comment]
I'm +1 on closing this, I don't believe the context manager is necessary.

**Comment by MarcoGorelli** [comment]
Looks like this has been clearly documented in https://pandas.pydata.org/pandas-docs/stable/user_guide/gotchas.html#gotchas-udf-mutation by https://github.com/pandas-dev/pandas/pull/39762 - closing then, but please let me know if I've misunderstood, or if you believe that just documenting this isn't enough of a solution
