### ISSUE TITLE
ERR: csv parsing error consistency of exceptions

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#12665]
xref https://github.com/pydata/pandas/pull/12551

a) change `CParserError` to an actual `ValueError`. this is used in a very small number of cases in the `engine='c'` parser.  (in #12551 it will inherit from `ValueError`)

b) So we either change ALL `ValueError` to `ParserError(ValueError)` (e.g. a custom exception) and make the changes in both the `engine='c'` and `engine='python'`.

**Comment by jreback** [comment]
cc @gfyoung @jorisvandenbossche 

thoughts?

**Comment by gfyoung** [comment]
xref #12506 as well

Hmmm...from a semantic point of view, I would prefer `ParserError` over the more generic `ValueError`.  That's all I have for the moment.

**Comment by gfyoung** [comment]
@jreback : Does the merged #12506 handle this issue sufficiently?

**Comment by jreback** [comment]
yes, ty.

closed by #12506

**Comment by jreback** [comment]
actually. What I eventually wanted was to make ALL parser exceptions the same, which is an API change.

**Comment by gfyoung** [comment]
By which you mean across both the `CParser` and the `PythonParser` or that they just always raise one exception whenever there is an error in the reading?

**Comment by jreback** [comment]
yes I think we need to have a single ``ParserException`` (which is just a ``ValueError``). (and remove the ``CParserException`` moniker, that's why its an API change.

**Comment by gfyoung** [comment]
Okay, that makes sense.  Just wanted to clarify!

**Comment by jorisvandenbossche** [comment]
@gfyoung You said this is only partially resolved by the merged PR?

**Comment by gfyoung** [comment]
@jorisvandenbossche : Hmm...not sure why I said that.  Should just be resolves.  Oh well. :smile:
