### ISSUE TITLE
DOC: 10 minutes - 'where' not used

### ISSUE THREAD

**Issue by scientist1642** [pandas-dev/pandas#12661]
[in pandas 0.18.0: doc](http://pandas.pydata.org/pandas-docs/stable/10min.html#boolean-indexing)
"where" is mentioned but not used, should it be df.where(df > 0)? It's the same in this case but anyway..

**Comment by jreback** [comment]
``df[df > 0]`` IS implemented using where. I suppose you could add a clarification / example (meaning how to actually use ``.where`` from the main docs).
