### ISSUE TITLE
ERR: invalid error reporting when comparing vs. None

### ISSUE THREAD

**Issue by aberdah** [pandas-dev/pandas#12689]
The "in" function does not work as expected in regard to a data frame. Let's say we have the following data frame :

`df = pd.DataFrame(np.random.randn(6,4), columns=list('ABCD'))`

We can test this data frame :

```
df is None
False
```

However we cannot test its presence in a list : 

```
df in [None]
TypeError: Could not compare [None] with block values
```

We would expect to get just False in this case.

(Pandas version 0.17.1)

**Comment by jreback** [comment]
This is coming from this, while useful (should simply be using ``df.isnull()``) to handle all dtypes.

```
In [3]: df==None
TypeError: Could not compare [None] with block values
```
is a bug and causes ``__nonzero__`` to fail I think.

This is an inherently ambiguous operation, see docs [here](http://pandas.pydata.org/pandas-docs/stable/basics.html#boolean-reductions)
```
In [22]: df['A'] in [None]
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**Comment by mroeschke** [comment]
This is raising the correct exception on master. Could use a test.

```
In [33]: df = pd.DataFrame(np.random.randn(6,4), columns=list('ABCD'))
    ...:
    ...:

In [34]: df in [None]
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [35]: pd.__version__
Out[35]: '0.26.0.dev0+684.g953757a3e'
```

**Comment by eddy-geek** [comment]
This seems to have unintended side-effects -- i.e. why should this seemingly innocuous code raise ValueError?:

```python
df_or_string = pd.DataFrame()
if df_or_string == 'foo':
    print('bar')
```
