### ISSUE TITLE
CLN: consolidate compression inference as much as possible

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#12688]
we have 3 copies of the compression inference routines in `parser.py, parser.py, and io/common.py`. See how much we can reduce this (_some_ is necessary as sometimes we need to actually return a file handle or need to read in and re-wrap).

xref #12175

**Comment by jreback** [comment]
cc @lababidi

**Comment by jreback** [comment]
@gfyoung if you are looking for something to do :>

I think we can blow away ``_wrap_compresed`` in parsers/io/parsers.py and incorporate any such functionaility in ``io/common.py/_get_handle``

there is also compression handling in ``parser.pyx`` but I think this might be harder to remove (in favor of ``_get_handle``, though maybe if we pass an argument might work).

xref #13317

**Comment by gfyoung** [comment]
Haha.  Thanks @jreback for the mention.  I'll take a closer look when I have the time. :smile:

**Comment by lababidi** [comment]
@jreback I got the following error when attempting to test:
```
TypeError: assert_almost_equal() got an unexpected keyword argument 'check_dtype'```

**Comment by jreback** [comment]
you need to rebuild extensions

``python setup.py build_ext --inplace``
