### ISSUE TITLE
Large multiindex dataframe shows only NaN values after selected rows are dropped

### ISSUE THREAD

**Issue by sylvaticus** [pandas-dev/pandas#12754]
_NOTE: This issue has been already [submitted to SO](http://stackoverflow.com/questions/36221441/why-large-pandas-dataframe-shows-only-nan-values-after-i-drop-selected-rows/36223039)  where the only person replying did replicate the behaviour in pandas 18.0._

Using the pandas library v. 17.1, I am trying to remove the rows from a large (882504 rows) dataframe named productDataNat where parName=='rt', but then all the other rows become NaN:
#### Code Sample, a copy-pastable example if possible

Importing and showing the multiaxis dataframe..

```
productDataNat = pd.read_csv('https://lobianco.org/temp/productData_P0-Mi-Ei.csv',sep=';',  dtype={'value': np.float64})
productDataNat = productDataNat.drop(['Unnamed: 8'],axis=1)
productDataNat.set_index(['scen','country','region','prod','freeDim','year','parName'], inplace=True)
productDataNat.head()
```

![screenshot from 2016-03-25 14 26 00](https://cloud.githubusercontent.com/assets/2077159/14168168/f3df1112-f720-11e5-8530-0ba4116e3df4.png)

Here I drop by same values in an internal axis.. all the remaning values are NaN!:
`productDataNat.drop('rt', level='parName', axis=0)`
![screenshot from 2016-03-25 14 29 30](https://cloud.githubusercontent.com/assets/2077159/14168189/1616534e-f721-11e5-9925-b8ef72fb6275.png)
#### Expected Output

When instead I play with an example dataframe it works as expected:

```
midx = pd.MultiIndex(levels=[['one', 'two'], ['x','y']], labels=[[1,1,1,0],[1,0,1,0]])
dfmix = pd.DataFrame({'A' : [1, 2, 3, 4], 'B': [5, 6, 7, 8]}, index=midx)
dfmix
```

![screenshot from 2016-03-25 14 32 51](https://cloud.githubusercontent.com/assets/2077159/14168195/2b956cd2-f721-11e5-8087-6091523c8727.png)

`dfmix.drop('x',level=1,axis=0)`
![screenshot from 2016-03-25 14 34 01](https://cloud.githubusercontent.com/assets/2077159/14168204/365c2a02-f721-11e5-806f-99cd2664ec41.png)
#### output of `pd.show_versions()`

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.3.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-83-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.17.1
nose: 1.3.1
pip: 1.5.4
setuptools: 3.3
Cython: None
numpy: 1.10.4
scipy: 0.13.3
statsmodels: None
IPython: 4.0.0
sphinx: 1.2.2
patsy: None
dateutil: 2.5.0
pytz: 2015.7
blosc: None
bottleneck: 1.0.0
tables: None
numexpr: 2.5
matplotlib: 1.3.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999
httplib2: 0.8
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
Jinja2: None
```

**Comment by jreback** [comment]
Ok so here is the repro. When dropping a level if ANOTHER level ends up with all ``nan``, then it borks. This is because internally a ``.reindex`` is done with the labels and these don't end up matching (on anything). Instead I think we can convert this to a positional indexer and just take and this will work.

So this is a bug.

```
In [70]: df = DataFrame({'A' : ['one','one','two','two'], 'B' : [np.nan,np.nan, 1.0, 2.0], 'C' : ['a','b','c','c'], 'D' : [1,2,3,4]}).set_index(['A','B','C']).sort_index()

In [71]: df
Out[71]: 
           D
A   B   C   
one NaN a  1
        b  2
two 1.0 c  3
    2.0 c  4

In [72]: df.drop('c',level='C')
Out[72]: 
            D
A   B   C    
one NaN a NaN
        b NaN
```

**Comment by charlie0389** [comment]
This bug is actually more serious - when dropping a level, if another level has *any* ``nan``, then it borks. It is *not* the case, as previously mentioned that another level has to have *all* ``nan``.

    >> df = pd.DataFrame({
        'A' : ['one','one','two','two'], 
        'B' : [pd.np.nan,0.0,1.0,2.0],
        'C' : ['a','b','c','c'], 
        'D' : [1,2,3,4]}).set_index(['A','B','C']).sort_index()

    >> df

               D
    A   B   C   
    one NaN a  1
        0.0 b  2
    two 1.0 c  3
        2.0 c  4

    >> df.drop('c', level='C')

                 D
    A   B   C     
    one NaN a  NaN
        0.0 b  2.0

**Comment by mroeschke** [comment]
This looks to work on master now. Could use a test:

```
In [211]: df.drop('c',level='C')
Out[211]:
           D
A   B   C
one NaN a  1
        b  2

In [215]: pd.__version__
Out[215]: '0.26.0.dev0+593.g9d45934af'
```
