### ISSUE TITLE
API/BUG/CLN: Index/Series common dtype handling

### ISSUE THREAD

**Issue by sinhrks** [pandas-dev/pandas#12758]
#### Code Sample, a copy-pastable example if possible

Some inconsistencies there.

```
# OK: specifying int dtype with float value coerces to int (same as numpy)
pd.Series([1, 2, 3.5], dtype=int)
#0    1
#1    2
#2    3
# dtype: int64

# OK
pd.Index(np.array([1, 2, 3.5], dtype=int))
# Int64Index([1, 2, 3], dtype='int64')

# NG: If list is given, dtype is ignored
pd.Index([1, 2, 3.5], dtype=int)
# Float64Index([1.0, 2.0, 3.5], dtype='float64')
```
#### Expected Output
- All list-like input should be handled by a consistent logic.
- If `dtype` is specified, the result must be the specified `dtype`. Otherwise raise.
  - To do this, merge base `Index` creation and `Series` sanitizing logic to use same `ndarray` `dtype` handling.
#### output of `pd.show_versions()`

Current master.

**Comment by jreback** [comment]
cc @gfyoung 

this is very much like #15187 

this might even be closable now, can you have a look?

**Comment by gfyoung** [comment]
Similar, but not the same.  This relates to how we coerce `dtype` in general (not the `uint64` corner case).  However, note that what @sinhrks contradicts what you were proposing in [12] of that issue.

**Comment by gfyoung** [comment]
I think what might be best is to open one issue that combines all of these `dtype` casting issues if that works with everyone.

**Comment by gfyoung** [comment]
@jreback : Opened #15832, which includes this issue.  I think we can close this one then.
