### ISSUE TITLE
BUG: unstacking with object columns defaults to None as a fill value

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#12815]
```
In [41]: df = DataFrame({'A' : [1,1,2], 'B' : list('aba'), 'C' : ['foo', np.nan, 'bar']}).set_index(['A','B'])

In [42]: df.unstack('B')
Out[42]: 
     C      
B    a     b
A           
1  foo   NaN
2  bar  None

In [43]: df.unstack('B', fill_value=np.nan)
Out[43]: 
     C     
B    a    b
A          
1  foo  NaN
2  bar  NaN
```

Introduced is this PR: https://github.com/pydata/pandas/pull/10246

you can make a case to do this as we DO support `None` as a fill value, but almost always even with object columns we use `np.nan`, unless very explicity set by the user.

**Comment by jreback** [comment]
cc @amcpherson

**Comment by amcpherson** [comment]
So the preferred functionality is?:

    In [42]: df.unstack('B')
    Out[42]: 
         C      
    B    a     b
    A           
    1  foo  NaN
    2  bar  NaN

default to None for object columns seems reasonable to me, but I can fix if nan is preferred.

**Comment by jreback** [comment]
yeah we just use nan even for object columns 
unless the user is very explicit about it

**Comment by mattayes** [comment]
Hey folks, I'm happy to pick this up if no one else is working on it. I'm fairly confident with what needs to change (thanks for linking to the original PR, @jreback).

**Comment by amcpherson** [comment]
@mattayes please go ahead.
