### ISSUE TITLE
Support for inplace argument for str.replace

### ISSUE THREAD

**Issue by joonro** [pandas-dev/pandas#12851]
It would be great if there is a support for `inplace` argument for `str.replace`, so I can do

``` python
addresses.str.replace('\s+\d{5}', '', inplace=True)
```

instead of 

``` python
addresses = addresses.str.replace('\s+\d{5}', '')
```

Thank you!

**Comment by jreback** [comment]
using ``inplace`` is not idiomatic pandas. I don't think we should be adding any more of this. But as it not pervades things,  so if someone wants to propose a patch, then ok I guess.

**Comment by mroeschke** [comment]
I think we are generally moving away from `inplace`. Closing
