### ISSUE TITLE
API: remove need for CustomBusiness freqs

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#12854]
I think we can move the functionaility to the regular `Business` freqs but just accepting 
the additional arguments from `CustomBusinesssDay`, IOW, expand `BusinessDay` with default args of `None` for `weekmask` and `holidays` (and just default them).

I think this can be done without any user changes at all. We can then deprecate `CustomBusiness*` in favor of simple `Business*` in 0.19.0.

**Comment by jbrockmendel** [comment]
BusinessDay and BusinessHour probably.  BusinessMonthEnd and BusinessMonthBegin will be tougher.

**Comment by jbrockmendel** [comment]
Closing as no action; there isn't a viable way of doing this that doesn't kill perf.
