### ISSUE TITLE
CLN/API: combine .swaplevel() into generic

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#12960]
xref #12943 

seems we have lots of implementations of the same routine with slightly different API.

`pd.DataFrame.swaplevel(self, i, j, axis=0, inplace=False)` (this is before the default args).

I would remove the `copy` arg from `Series` and use something like this.

**Comment by jreback** [comment]
cc @brandon-rhodes

**Comment by mroeschke** [comment]
Appears this hasn't gotten traction in a while so closing
