### ISSUE TITLE
option to suppress plotting of corresponding higher frequency reference

### ISSUE THREAD

**Issue by timmie** [pandas-dev/pandas#1300]
> In pandas 0.8.0, the time series plotting will be much improved (see
> attached example plot)
> What I'd love to see is an option to switch the reference time value off for aggregated time series.

Examples:
- I have an average of wind speeds created from 5 years of data --> plotting a year would not make sense
- daily maximum temperatures recoded during a single month --> depending on the case, showing the reference month or not could be desirable.

**Comment by jorisvandenbossche** [comment]
Closing this as there is no clear enhancement for pandas, and you can always change the default Formatter with matplotlib.
