### ISSUE TITLE
DEPR: pd.Series.between

### ISSUE THREAD

**Issue by colinalexander** [pandas-dev/pandas#13027]
deprecate `between` in favor of other indexing options (e.g. `loc`)

xref: https://github.com/pydata/pandas/issues/12398, #12402 (not merged)

**Comment by jreback** [comment]
I am not so sure about this. I kind of the like the ``between_time`` API and this is an extension of it, OTOH, this violates MTOWTDI.

**Comment by TomAugspurger** [comment]
This could use a decision one way or another. I don't have a strong opinion.

**Comment by mroeschke** [comment]
Since there really hasn't been too much favor either way, probably safer to lean on keeping at this point. Closing but can reopen if there's interest
