### ISSUE TITLE
More comprehensive testing for interp methods 'piecewise_polynomial' / 'from_derivatives'

### ISSUE THREAD

**Issue by jmwoloso** [pandas-dev/pandas#13075]
@jreback Just opening this up as the next step after pydata/pandas#12887.

**Comment by jmwoloso** [comment]
@jreback Sorry for the delay, I fully intend to get this done! Started a new job at the beginning of the month though and trying to get up to speed there.

**Comment by jorisvandenbossche** [comment]
No problem, when you have the time!

**Comment by mroeschke** [comment]
I see `test_interpolate_from_derivatives` and `test_interpolate_piecewise_polynomial` as well as a `nontemporal_method` fixture that includes these options. Since there hasn't been much movement on this issue, going to close for now. But if there's more detail what to specifically fix can reopen
