### ISSUE TITLE
TST: Start using py.test

### ISSUE THREAD

**Issue by MaximilianR** [pandas-dev/pandas#13097]
from https://github.com/pydata/pandas/pull/13091

Currently _most_ of the tests pass with pytest, but there are 69 that don't. Most of these look like they're pickle or SQL / external resources issues.

pytest output here: https://gist.github.com/MaximilianR/225a071337e335ebdcc1d17637126126

So this does need a champion who could work through those issues. That's probably not me at the moment, but you have my moral support!

mpl is converting!
https://github.com/matplotlib/matplotlib/pull/5405

**Comment by jreback** [comment]
those fails are because we abusing nose a bit to be more parameterized (by using yield).

**Comment by kawochen** [comment]
Did you mean generative tests?  pytest has a similar thing.

**Comment by jreback** [comment]
yes, but actually wouldn't do that. These really should be parameterized test in ``py.test``. This was a hack in nose to get it to work.

**Comment by par2** [comment]
I'd like to switch to pytests eventually, but 8/9 of my errors are related to `pandas._testing.assert_almost_equal`.  Can this be fixed too?

**Comment by jreback** [comment]
@par2 need someone to work thru all of these issues.
