### ISSUE TITLE
ENH: pd.read_feather/to_feather

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#13092]
conda packages are now available [here](https://github.com/wesm/feather/issues/134)

so this should be straightforward. a couple of things to note.
- should support the `LocalPath/PathLib` objects (easy as we do this in other `read_*`)
- non-supported on windows ATM. need to skip for testing. `feather-format` will just raise an `ImportError` for now.
- catch and re-raise for non-supported things, mainly object dtypes that are not all strings. Alternatively / maybe better to introspect these columns (via `lib.infer_dtype`) to prevent in the first place
- test unicode support / encoding (not sure supported as of yet)
- biggest issue is how / if to support `Series` and a `DataFrame` with a non-default index. As we need a facility to write/read meta-data within feather [see here](https://github.com/wesm/feather/issues/74). Both these can simply `.reset_index()`, but the problem is they can be stored but we don't know on read-back what to `.set_index()`. Can just raise for now.

**Comment by jreback** [comment]
@wesm

**Comment by wesm** [comment]
I'd prefer to put most of the heavy lifting in the feather Python library itself, unless you are worried about versioning synchronization issues? Of course we can have convenience APIs in pandas to import and invoke the appropriate feather functions.

**Comment by jreback** [comment]
@wesm no for sure. Just have an overlay of testing in pandas main I think.
