### ISSUE TITLE
[feature req] List tables function for sql

### ISSUE THREAD

**Issue by DSLituiev** [pandas-dev/pandas#13105]
Suggestion: introduce a function, something like `pandas.sql_list_tables(conn)` to look up available tables (shortcut for 
`pd.read_sql("SELECT * FROM sqlite_master WHERE type='table'", conn, index_col=["name"])` or 
`pd.read_sql("SELECT name FROM sqlite_master WHERE type='table'", conn)`). 

Like in [this `R` module](https://rstudio-pubs-static.s3.amazonaws.com/52614_1fa12c657ba7492092bd538205d7f02e.html)

**Comment by sornars** [comment]
I was looking into this and while implementing wondered if it was strictly necessary? If you're using an SQLAlchemy engine then you need to use the `engine.table_names` function to get this information. As far as I can tell the only DBAPI compatible interface supported is sqlite in which case you'd run the above query. 

Is the intention to wrap the `engine.table_names` in SQLDatabase, create an equivalent function in SQLIteDatabase which will call the query supplied by @DSLituiev and wrap both of these behind a wrapper in the `pandas.io.sql` module?

**Comment by DSLituiev** [comment]
thank you @sornars! Looks good to me.

**Comment by mroeschke** [comment]
Yeah pandas SQL functionality is to read or write data. Database introspection can be done with sqlalchemy so closing
