### ISSUE TITLE
enhancement: add optional row/col paramater to to_latex formatter

### ISSUE THREAD

**Issue by nbecker** [pandas-dev/pandas#13203]
I need to have to_latex formatter function know the row/col of the item being formatted, so it can modify the formatting of certain items, e.g., set some items in color of bold based on the values in the table.

To do this in a backward compatible way, I propose adding a keyword to to_latex - which would then cause the formatter function to be called as
formatter (element value, row#, col#)

**Comment by jorisvandenbossche** [comment]
@TomAugspurger How do you envision the new `Styler` formatting framework can be be used for other things than html? Could we in principle make a LatexStyler that adapts the template and the html specific methods? 
In that case that is maybe a better / more powerfull way forward to adapt styling.

@nbecker You know you already have to specify the column for `formatters`? So the question is only about also knowing the index of the element?

**Comment by nbecker** [comment]
I want to know the index so I can style certain elements according to some computation.  For example,
All elements in column N+1 > corresponding element in column N should be colored green
df['N+1'] > df['N'] -> green
to implement this, I need to formatter to be passed the index

**Comment by TomAugspurger** [comment]
I think the parts that can be reused are public API parts like `Style.format`, `Styler.render`, `Styler.apply` and `Styler.applymap`. That gives you iteration logic over every row, and every column in each row, including the style information attached to that item. Also the export / use functionality. Those items could be put in a base class pretty easily I think.

Other than that it'd be up to the subclass to implement

- the template (I don't think there's much that could be inherited from a base template), which wouldn't be terrible.
- the `_translate` method, which would be the bulk of the work
- Any builtin styles (like `.highlight_max`)

**Comment by TomAugspurger** [comment]
I've pushed a branch [here](https://github.com/TomAugspurger/pandas/commits/refactor-style) sketching out what the start of the refactor might look like.

- [HTMLStyler](https://github.com/TomAugspurger/pandas/commit/1105551377c7fbc890fa4c00d5a5a6f81d4e7539)
- [BaseStyler and load templates from file](https://github.com/TomAugspurger/pandas/commit/76e058837285203a1b30f66ad4615f581bc1aa7c)
- [Start LaTeX Template](https://github.com/TomAugspurger/pandas/commit/33ef5e8fab2a52973fbb330a383043982bcc523e)

At this point it's worth asking whether all this is still in scope for pandas? Other than LaTeX I'd say the big one is Markdown, which wouldn't be much code, so maybe it's OK to keep in pandas.

**Comment by jnothman** [comment]
Now that we have `Styler.to_excel`, I think the option of a similar `Styler.to_latex` export would be appropriate.

**Comment by jnothman** [comment]
Though note that Styler explicitly sets a style per cell. We won't be producing idiomatic TeX that way, in the sense that we won't control the formatting (justification etc) of entire columns, nor arbitrary macros to reformat a class of cells.
