### ISSUE TITLE
DOC: sas & R functionaility

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#13229]
http://blog.dominodatalab.com/using-r-and-python-for-common-sas-functions/?utm_source=&utm_medium=&utm_campaign=

might be interesting to update `comparison_with_SAS/R` with this.

**Comment by natethedrummer** [comment]
I am working on this.

**Comment by jorisvandenbossche** [comment]
I just merged one of the PRs. But now I see the original issue, shouldn't we ask the author if it is OK to include this first, rather than just copying his text? (I don't directly see a license indication on the blog)

**Comment by Srikanth421** [comment]
Page can't be found? What are we solving here?

**Comment by jorisvandenbossche** [comment]
I think this can be closed now, I also don't directly find the original blog post.
