### ISSUE TITLE
BUG: .transform('size') should be the same as .transform(len)

### ISSUE THREAD

**Issue by jhmuller** [pandas-dev/pandas#13220]
```
import pandas as pd
N = 6
df = pd.DataFrame(data={"size":[0.1]*N,
                             "group":[None]*N}, 
                       index=range(N))
gb = df.groupby(by=['group'])
d2 =  gb.transform('sum')
print d2
```
#### Expected Output

```
# not actually sure what should be returned, perhaps just the original values
Here is what I got
            size
0  2.605041e-316
1  6.899144e-310
2  2.584561e+161
3  1.485397e-313
4  1.916117e+214
5  3.075369e+203


#### output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Linux
OS-release: 3.2.0-54-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.0
setuptools: 20.7.0
Cython: 0.24
numpy: 1.11.0
scipy: 0.17.0
statsmodels: 0.6.1
xarray: 0.7.2
IPython: 4.2.0
sphinx: 1.3.6
patsy: 0.4.1
dateutil: 2.2
pytz: 2016.4
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5.2
matplotlib: 1.5.1
openpyxl: 2.2.0-b1
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.5
lxml: 3.6.0
bs4: 4.4.1
html5lib: 0.999
httplib2: None
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.39.0
pandas_datareader: None
```

**Comment by jhmuller** [comment]
The results are random, sometimes I get all zero values but other times very small floats and sometimes very large floats.  I think it is from grabbing an uninitialized chunk of memory with empty_like and treating it as float64.

**Comment by jreback** [comment]
This is in master.

```
In [23]: d2
Out[23]: 
   size
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
```

hmm, we dont' have great empty group support ATM. Can you recast your example to something that has a group (and another where the group is missing)?

**Comment by jhmuller** [comment]
will do

**Comment by jhmuller** [comment]
# ok, now with 1 non null group
# results vary with every run but larger N seems to be more reliably odd
import pandas as pd
N = 200
not_null = 1
df = pd.DataFrame(data={"size":[0.1]*N,
                             "group":[None]*(N-not_null) + ['red']*(not_null)}, 
                       index=range(N))
gb = df.groupby(by=['group'])
d2 =  gb.transform('sum')
print d2.min().values, d2.max().values, d2.median().values
pd.show_versions()

# output expected is [0.1] [0.1] [0.1] since there is only 1 valid group
#   and I think each None for group is in a group unto itself, 
# what I got was [ -7.96392207e+282] [  8.64293444e+263] [ 0.]
#  and again each time I get different results

# output from pd.show_version()
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Linux
OS-release: 3.2.0-54-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.0
setuptools: 20.7.0
Cython: 0.24
numpy: 1.11.0
scipy: 0.17.0
statsmodels: 0.6.1
xarray: 0.7.2
IPython: 4.2.0
sphinx: 1.3.6
patsy: 0.4.1
dateutil: 2.2
pytz: 2016.4
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5.2
matplotlib: 1.5.1
openpyxl: 2.2.0-b1
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.5
lxml: 3.6.0
bs4: 4.4.1
html5lib: 0.999
httplib2: None
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.39.0
pandas_datareader: None

**Comment by jreback** [comment]
I meant a short example something along these lines.

```
In [17]: df = pd.DataFrame({'group' : [np.nan, np.nan, 'foo', 'bar'], 'value' : [1, 2, 3, 4]})

In [18]: df
Out[18]: 
  group  value
0   NaN      1
1   NaN      2
2   foo      3
3   bar      4

In [19]: df.groupby('group').sum()
Out[19]: 
       value
group       
bar        4
foo        3

In [20]: df.groupby('group').transform('sum')
Out[20]: 
   value
0    NaN
1    NaN
2    3.0
3    4.0

# this is a BUG
In [21]: df.groupby('group').transform('size')
TypeError: Transform function invalid for data types

In [22]: df.groupby('group').transform('count')
Out[22]: 
   value
0    NaN
1    NaN
2    1.0
3    1.0
```

so [21] is a bug; I think other behavior is as expected. This is in master.

**Comment by jreback** [comment]
xref to #7570

**Comment by jreback** [comment]
What you are seeing in 0.18.1 is already fixed in master, so I suppose could do a validation tests (e.g. use the above example and write a tests that asserts this). otherwise this is a bug w.r.t. ``size`` not being accepted to ``.transform``

**Comment by jhmuller** [comment]
.. ok great, more compact example below
.. not .. code:: python

    import pandas as pd
    
    df = pd.DataFrame(data={"size":[0.1]*200,
                                 "group":[None]*(200-1) + ['red']*(1)}, 
                           index=range(200))
    d2 =  df.groupby(by=['group']).transform('sum')
    
    print d2.min().values, d2.max().values, d2.median().values


.. parsed-literal::

    [ -6.64080621e+188] [  9.95697526e+118] [  1.20943950e-316]

**Comment by jhmuller** [comment]
It is not obvious to me that the description ".transform('size') should be the same as .transform(len)" and its fix also apply to the issue I had which seemed more about groupby and transform with null values in the groupby variable.
However, I defer to your expertise.
Any rough estimate on when the next public released version will happen?
Thanks greatly,
   - john muller

**Comment by jreback** [comment]
prob a couple of weeks, not sure

**Comment by xyzjayne** [comment]
Following up on ``grouped.transform('size')`` bug not being resolved

**Comment by jreback** [comment]
> Following up on `grouped.transform('size')` bug not being resolved

@xyzjayne pls post a new issue with a full reproducible example and version info if something is not working

this one is very old
