### ISSUE TITLE
COMPAT: concat of PeriodIndex

### ISSUE THREAD

**Issue by max-sixty** [pandas-dev/pandas#13221]
https://github.com/pydata/pandas/blob/master/pandas/tseries/period.py#L920
`return Index(com._concat_compat(to_concat), name=name)`
now should reference `pandas.types.concat._concat_compat`

I _think_ this should probably fail - concat-ing a `PeriodIndex` with other index types?

**Comment by jreback** [comment]
this ultimately calls ``conat_datetime``, yes which should handle ``PeriodIndex``, but doesn't ATM.

cc @sinhrks

**Comment by jreback** [comment]
this is something @sinhrks will handle when ``period`` is a real-dtype

**Comment by MaximilianR** [comment]
Two separate issues
- A code breakage, because it's calling `com._concat_compat` which doesn't exist anymore
- Whether this should / does work in a conceptual sense

Not sure if you recognized the first issue here?

**Comment by jreback** [comment]
oh, that must not be tested :)

that has moved locations (though it *may* be aliased)

**Comment by TomAugspurger** [comment]
I think this is resolved.

concat([Period]) is a period type. concat([period, other]) is object.
