### ISSUE TITLE
Inconsistent default date ticks for data at different frequencies

### ISSUE THREAD

**Issue by marcinbielecki** [pandas-dev/pandas#13227]
When the data indexed with datetime are plotted via DataFrame.plot(), the default date ticks behave inconsistently depending on the frequency of the data index.

Here's a [short notebook](https://gist.github.com/marcinbielecki/9a8c1e3f7900a4761202769aecf746e0) that reproduces the issue. The data at daily, weekly and annual frequencies are plotted with ticks aligning to "round" years, in this example multiples of 5 (5n). However, data at monthly and quarterly frequencies are plotted with ticks aligning to 5n-1.

**Comment by jreback** [comment]
@TomAugspurger

**Comment by vfilimonov** [comment]
A comment for the recent issue explains this behaviour: https://github.com/pandas-dev/pandas/issues/20688 (see also: https://pandas.pydata.org/pandas-docs/stable/visualization.html#suppressing-tick-resolution-adjustment)

For those coming from google search: argument `x_compat=True` solves the issue

**Comment by mroeschke** [comment]
Here is the updated link of the section explaining `x_compat`. https://pandas.pydata.org/pandas-docs/stable/user_guide/visualization.html#suppressing-tick-resolution-adjustment

Since https://github.com/pandas-dev/pandas/issues/20688 is an issue to update the docs, closing this issue
