### ISSUE TITLE
PeriodIndex with float input inconsistency

### ISSUE THREAD

**Issue by sinhrks** [pandas-dev/pandas#13232]
#### Code Sample, a copy-pastable example if possible

```
pd.PeriodIndex([1.1], freq='M')
# ValueError: Given date string not likely a datetime.

pd.PeriodIndex(np.array([1.1]), freq='M')
# PeriodIndex(['1970-02'], dtype='int64', freq='M'
```
#### Expected Output

Consistently raise or coerce to `Period`
#### output of `pd.show_versions()`

0.18.1

CC: @MaximilianR

**Comment by MaximilianR** [comment]
ref https://github.com/pydata/pandas/pull/13079, which should fix

**Comment by MaximilianR** [comment]
@sinhrks @jreback closed by #13079

**Comment by jreback** [comment]
@MaximilianR if you think we need to add a note (and/or include these issues) in the whatsnew, pls do a PR.

**Comment by MaximilianR** [comment]
@jreback this seems like pretty deep in the internals - shall I still add one?

**Comment by jreback** [comment]
nah I looked again, its fine. thxs!

Periods really coming along!

**Comment by sinhrks** [comment]
@MaximilianR #13079 only checks `_shallow_copy` with normal float input right?

on current master (d2b581960168502b1f7dfd73cedfe03ffbf91aee):

```
pd.PeriodIndex(np.array([1.1, np.nan, np.inf]), freq='M')
# PeriodIndex(['1970-02', 'NaT', 'NaT'], dtype='int64', freq='M')

pd.PeriodIndex([1.1, np.nan, np.inf], freq='M')
# ValueError: Value must be Period, string, integer, or datetime
```

reopes.

**Comment by jreback** [comment]
```
In [2]: pd.PeriodIndex(np.array([1.1]), freq='M')
Out[2]: PeriodIndex(['1970-02'], dtype='int64', freq='M')
```

actually the original [2] should be an error as well (and ``ValueError`` is correct here)

**Comment by MaximilianR** [comment]
Apologies. Will PR

**Comment by MaximilianR** [comment]
Why a `ValueError` rather than `TypeError`?

**Comment by jreback** [comment]
oh these could be ``TypeError``, but we mostly raise ``ValueError`` now

**Comment by MaximilianR** [comment]
Looking through this, I think this is a pretty weird code path - only gets hit strings-that-coerce-to-ints are supplied... https://github.com/pydata/pandas/blob/master/pandas/tseries/period.py#L229

**Comment by jreback** [comment]
hmm, yeah that does seem weird; I prob would just try to ``astype('i8')`` if it fails take that path.
