### ISSUE TITLE
style format setting subset loses column titles

### ISSUE THREAD

**Issue by simonm3** [pandas-dev/pandas#13266]
See example below. There is no "sex" in the styled table.

```
from IPython.display import display as d
import pandas as pd
df=pd.DataFrame.from_dict(dict(survived=[1,0,0,0,1,1,1,1], sex=["Male", "Female", "Male", "Female", 
                                                                "Male", "Female","Female", "Female" ]))
table=pd.crosstab(df.survived, df.sex)
table.loc["rate"] = table.iloc[-1] / table.sum()
d(table)
ftable = table.style.format("{:.0%}", subset=pd.IndexSlice["rate",:])
d(ftable)
```

**Comment by TomAugspurger** [comment]
Can you post a copy-pastable example? What is `table` here? What version of pandas are you using? Thanks.

**Comment by simonm3** [comment]
version 18.1 in ipython

from IPython.display import display as d

def stable(*args, **kwargs):
    """ survival table showing counts and percentage
    """
    table = pd.crosstab(*args, **kwargs)
    table.index = ["died", "lived"]
    table.loc["rate"] = table.iloc[-1] / table.sum()
    ftable = table.style.format("{:.0%}", subset=pd.IndexSlice["rate",:])
    d(ftable)

stable(pd.Survived, pd.Sex)

**Comment by jreback** [comment]
@simonm3 can you post a copy-pastable example (e.g. create a frame then style)

**Comment by simonm3** [comment]
from IPython.display import display as d
import pandas as pd
df=pd.DataFrame.from_dict(dict(survived=[1,0,0,0,1,1,1,1], sex=["Male",
"Female", "Male", "Female",
                                                                "Male",
"Female","Female", "Female" ]))
table=pd.crosstab(df.survived, df.sex)
table.loc["rate"] = table.iloc[-1] / table.sum()
d(table)
ftable = table.style.format("{:.0%}", subset=pd.IndexSlice["rate",:])
d(ftable)

**Comment by TomAugspurger** [comment]
Maybe try with master, the output seems to be correct to me.

<img width="770" alt="screen shot 2016-05-24 at 9 02 19 am" src="https://cloud.githubusercontent.com/assets/1312546/15506718/45fb423a-218e-11e6-9fc5-831d3ccb330e.png">

**Comment by simonm3** [comment]
The first table says "sex" at the top left cell. The second table is
missing the sex.

**Comment by TomAugspurger** [comment]
Gotcha, that's the columns labels (`table.columns.name`) Would you mind searching if we already have an issue for that? If we don't already have one can you edit your original post and title to clearly demonstrate the problem? Thanks.

**Comment by nmontpetit** [comment]
Is there anything else that needs to be provided that will move this forward?  I thought the duplicate [issue](https://github.com/pydata/pandas/issues/13305) that I opened (and was closed) provided everything that has been requested.

**Comment by jreback** [comment]
@nmontpetit well a request would move this forward

**Comment by nmontpetit** [comment]
Thanks @jreback!  Assuming you mean a pull request, I took a look at the source code and realized I'm nowhere near being able to do that (I switched from SAS to pandas very recently, and don't have a lot of experience with Python).

And I'm new to submitting issues to pydata/pandas, so I'll rephrase my previous question.  Did the duplicate [issue](https://github.com/pydata/pandas/issues/13305) that I submitted include everything that is needed (from an issue report standpoint), and if so should I provide that information here?

I'm a newbie and I want to do it right, so your help is appreciated!

**Comment by jreback** [comment]
contributing docs are [here](http://pandas.pydata.org/pandas-docs/stable/contributing.html)

if you want to see this fixed soon then you should simply submit a pull-request. There are LOTS of issues.

**Comment by nmontpetit** [comment]
Got it.  Thanks!

**Comment by attack68** [comment]
this is fixed in master:
