### ISSUE TITLE
BUG: in read_csv, keep_date_cols doesn't result in correct dtype

### ISSUE THREAD

**Issue by Thomasillo** [pandas-dev/pandas#13378]
`>>> import pandas`
`>>> import io`
`>>> data = """A`
`20150908`
`20150909`
`"""`
`>>> t=pandas.read_csv(io.StringIO(data))`
`>>> t.dtypes`
`A    int64`
`dtype: object`
`>>> t=pandas.read_csv(io.StringIO(data),parse_dates={'date':['A']},keep_date_col=True)`
`>>> t.dtypes`
`date    datetime64[ns]`
`A               object`
`dtype: object`

The second time, the datatype of the column 'A' should also be int64.

**Comment by jreback** [comment]
@Thomasillo not sure the doc-string actually says that it should be parsed first. as it only applies to a list-lf-list-of dates. 

Not very many tests for this either.

So not clear if this is an issue or not.

cc @gfyoung

**Comment by gfyoung** [comment]
@jreback : I consider this behaviour a bug.  Casting should still be done if the column is being kept.
@Thomasillo : For the time being, try using Python engine instead.  It will correctly convert to `int64` for the retained parsed date column.

**Comment by gfyoung** [comment]
Again, this issue highlights a major issue between the two engines in that the order in which things are applied do not match.  As we can see here, the C engine applies the data conversions first before doing date conversions whereas the Python engine does it the other way around.  Another reason why the ordering needs to be aligned so that the behaviour can be fixed.

**Comment by gfyoung** [comment]
@jreback : IMO I think that the difficulty is at least "intermediate," as this issue is another manifestation of the larger issue I described above.

**Comment by jreback** [comment]
whomever fixed then will get 'intermediate' points (to be spent just like virtual cash:>)

**Comment by Thomasillo** [comment]
@gfyoung : Thanks. However, I had to solved the problem differently for now.

Am 06.06.2016 um 16:46 schrieb gfyoung <notifications@github.com>:

**Comment by gfyoung** [comment]
@jreback : fair enough : smile:

@Thomasillo : cool - thanks for bringing up the issue!

**Comment by holy-motors** [comment]
The reported bug is still present on version 0.24.1, but there is on activity here for the last three years. Shall we close it for now?

**Comment by gfyoung** [comment]
@holy-motors : It just means that no good solution has been found for it yet.  You are more than welcome to investigate if you like!
