### ISSUE TITLE
CLN: unify unicode file handle processing

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#13401]
xref https://github.com/pydata/pandas/pull/13351#issuecomment-224614415

We use `io/common/_get_handle` and `io/common/get_filepath_or_buffer` in various places in most of the io modules, need to unify encoding handling to a somewhat simpler interface (1 function).

**Comment by MaximilianR** [comment]
If this is backported from python 3.6, could it help? https://www.python.org/dev/peps/pep-0519/

**Comment by jreback** [comment]
we already support ``pathlib`` and ``py.path`` in an ok way ``_stringify_path``. This is more about providing a uniform interface that just works with encoding (and compression, though we are almost there for that). It is not far away, just needs some refactoring.

**Comment by jreback** [comment]
@aterrel want to submit more this so can proceed on #13351  ?

**Comment by aterrel** [comment]
Yeah I can look into it more. I worked around the issue in #13351, so I feel it could go in before this issue is fixed.

**Comment by mroeschke** [comment]
I think https://github.com/pandas-dev/pandas/issues/15008 encompasses this specific point. Close to close as a duplicate
