### ISSUE TITLE
read_sql_query parse_dates regression from 0.18.0 to 0.18.1

### ISSUE THREAD

**Issue by Moisan** [pandas-dev/pandas#13442]
Based on a sqlite database [my_database.zip](https://github.com/pydata/pandas/files/314395/my_database.zip) created from the file [source.zip](https://github.com/pydata/pandas/files/314358/source.zip) in a table `my_table`. I get different results when parsing the dates in the method `read_sql_query` between version 0.18.0 and 0.18.1.

The date format looks like this:  `"2015-05-01 00:00:00.000000"`
#### Code Sample, a copy-pastable example if possible

```
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine('sqlite:///my_database.db')
result = pd.read_sql_query('SELECT * from my_table;', engine, parse_dates={"RDD": 'D'})
```
#### Expected Output (0.18.0)

| RDD | QTY |
| --- | --- |
| 2015-05-01 | 1.0 |
| 2015-05-04 | 1.0 |
| 2013-12-03 | 1.0 |
| 2011-09-02 | 1.0 |
| 2010-09-01 | 20.0 |
#### Current Output (0.18.1)

| RDD | QTY |
| --- | --- |
| 2115-12-30 20:53:38.800017408 | 1.0 |
| 2115-12-30 20:53:38.800017408 | 1.0 |
| 2115-12-30 20:53:38.800017408 | 1.0 |
| 2115-12-30 20:53:38.800017408 | 1.0 |
| 2116-08-08 09:38:37.216342016 | 20.0 |
#### output of `pd.show_versions()`

commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.1
setuptools: 20.3
Cython: 0.23.4
numpy: 1.11.0
scipy: 0.17.0
statsmodels: None
xarray: None
IPython: 4.1.2
sphinx: None
patsy: None
dateutil: 2.5.2
pytz: 2016.3
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.1
openpyxl: None
xlrd: 0.9.4
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: 0.9.2
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
jinja2: 2.8
boto: None
pandas_datareader: None

**Comment by jorisvandenbossche** [comment]
Thanks for reporting! 

But a question: why are you using `parse_dates={"RDD": 'D'}` (where 'D' is the format string to parse the dates) when the dates already have a format like "2015-05-01 00:00:00.000000"? 
If I use `pd.read_sql_query('SELECT * from my_table;', engine, parse_dates=['RDD'])`, I get the desired result.

**Comment by Moisan** [comment]
Good to know! I use 'D' because the real precision of the data is daily. If I wanted to use a format string in this case, how should I use it?
Maybe the documentation should be more explicit on how to use this feature.

**Comment by jorisvandenbossche** [comment]
Well, the docstring says the following on using a dict for `parse_dates`:

```
Dict of {column_name: format string} where format string is strftime compatible
in case of parsing string times or is one of (D, s, ns, ms, us) in case of parsing
integer timestamps
```

which I think is rather explicit. But if you think of something to improve the explanation, certainly welcome!

In your case, the correct format string would be `parse_dates={"RDD": '%Y-%m-%d %H:%M:%S.%f'}`, but that is not necessary to specify this, as this is a ISO like date and is parsed correctly by default.

**Comment by Moisan** [comment]
I see. I would add to the docstring two things: 

- an example of a format string, such as the one gave,
- the fact that ISO like dates are parsed by default 

I can open a pull request if you agree.
