### ISSUE TITLE
PERF: large subset of block cast

### ISSUE THREAD

**Issue by chris-b1** [pandas-dev/pandas#13457]
from [SO](http://stackoverflow.com/questions/37845884/pandas-setting-column-subset-slow)

I'm guessing there's a lot of inference / checks along this path, but this is slower than I'd expect.

``` python
In [66]: df = pd.DataFrame(np.random.randint(0,1000, size=(10000, 1026)))
    ...: f = list(range(1024))
    ...: 

In [67]: %time df[f] = df[f].astype(float)
Wall time: 10.4 s
```

**Comment by jreback** [comment]
this is slow because this is done column by-column (that's ok), but then each column is deleted ,then added, prob with many consolidation steps in-between (each of which copy).

**Comment by mroeschke** [comment]
Looks like this performance is a lot better now so closing

```python
In [5]: df = pd.DataFrame(np.random.randint(0,1000, size=(10000, 1026)))

In [6]: f = list(range(1024))

In [7]: %timeit df[f] = df[f].astype(float)
251 ms ± 7.92 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
