### ISSUE TITLE
ENH: add errors='raise' option to rename

### ISSUE THREAD

**Issue by max-sixty** [pandas-dev/pandas#13473]
Is there a reason that `.rename` doesn't raise if keys are supplied that don't exist? This caught me out a couple of times:

``` python
In [14]: import pandas as pd

In [15]: df=pd.DataFrame({'a': [1,2], 'b': [3,4]})

In [16]: df
Out[16]: 
   a  b
0  1  3
1  2  4

In [17]: df.rename(columns={'a': 'c'})
Out[17]: 
   c  b
0  1  3
1  2  4
# ok

In [18]: df.rename(columns={'d': 'c'})
Out[18]: 
   a  b
0  1  3
1  2  4

# this should raise?
```

**Comment by TomAugspurger** [comment]
I suspect it is intentional. Either way, the behavior should be clarified in the docs. Missing keys (in columns but not in the dict) are explicitly documented.

I know I've used this in the past. For example a bunch of CSVs with variations on the same items. I'll make one dictionary with all the mappings

```python
renamer = {'zip': 'zip_code', 'postal code': 'zip_code', ...}`
```
And use that same `renamer` on many dataframes.

**Comment by MaximilianR** [comment]
OK. You know this better than me - do you think this is too much vs the increase in explicitness?

```python
df.rename(columns={col: renamer[col] for col in renamer if col in df.columns})
```

**Comment by jorisvandenbossche** [comment]
For `DataFrame.drop`, the `errors` keyword was added some time ago:

```
errors : {'ignore', 'raise'}, default 'raise'
    If 'ignore', suppress error and existing labels are dropped.

    .. versionadded:: 0.16.1
```

We could maybe add this to rename as well to have similar functionality? (although the default value would be different for rename)

**Comment by TomAugspurger** [comment]
Having a keyword to control this would be great. 

Another option is to revisit the "tell people to use `relabel` discussion". If we implemented it there we could have the default be to raise.

**Comment by apnewberry** [comment]
Is there a particular reason why the default value would be "ignore" for `rename`? If I'm renaming keys in a mapping but one isn't there, I normally anticipate a `KeyError`. A deprecation period would be necessary, of course -- I think a similar change has occurred recently with missing columns for `loc`.

**Comment by WillAyd** [comment]
Historical reasons. I think raising would be preferable though correct would require deprecation cycle

**Comment by TomAugspurger** [comment]
To be clear, I don't think there's a consensus for deprecating the current behavior. Just adding the option to raise when not present.

**Comment by bala-analytics** [comment]
This issue is closed but the problem still persists.

**Comment by TomAugspurger** [comment]
@bala-analytics the original example correctly raises with `df.rename(columns={'d': 'c'}, errors="raise")`.

**Comment by bala-analytics** [comment]
Thanks. Sorry missed that errors = ‘raise’ option
