### ISSUE TITLE
Series.sort_index does not accept kwargs kind and na_position.

### ISSUE THREAD

**Issue by IamJeffG** [pandas-dev/pandas#13589]
The sort_index method on DataFrame and NDFrame takes kwargs `kind` and `na_position`, but `Series` does not currently support it. (In addition their shared docstring says Series would support it.)

**Comment by sahildua2305** [comment]
Can I take this up? @IamJeffG @jreback

**Comment by jreback** [comment]
sure

**Comment by sahildua2305** [comment]
Thanks @jreback
