### ISSUE TITLE
API: pandas.api

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#13634]
In xref #13147

established a bit of a public api in `pandas.api`; ATM this only contains the type introspection routines.
## 1st question

Some disagreement on whether we should not do this, and rather just expose `pandas.types` directly.

I think `pandas.api` is actually very important because:

1) limits scope of what we choose to expose in the future; its not simply 'everything' that isnt nailed down (the case now). This does change pandas to make everything by default private, EXCEPT what is explicitly public.

2) a single entry point for other packages to use the pandas public API that is known / stable / maintained (will with c-API as well)

3) provide consistent naming externally (and allow us to fix / hide internally as needed)

4) namespaced. I only import _what_ I need as a user / other package, rather than _everything_
## ~~2nd question~~

 as discussed [here](https://github.com/pydata/pandas/pull/13147#discussion_r70594911), should these deprecated API functions should be `DeprecationWrarning` rather than `FutureWarning`?
-> done in https://github.com/pydata/pandas/pull/13990

Ideally we should resolve this before the end of 0.19.0 (or remove it).

**Comment by jreback** [comment]
@jorisvandenbossche @shoyer @wesm @TomAugspurger @sinhrks

**Comment by jreback** [comment]
@jorisvandenbossche updated the top section.

**Comment by jorisvandenbossche** [comment]
We have discussed this on some several places, recently also in the PR about the `errors` module (https://github.com/pandas-dev/pandas/pull/15541) and previously when `pandas.types` was created (https://github.com/pandas-dev/pandas/pull/13147#issuecomment-220199044 and comments below). 
For the exceptions, we now have a top-level `pandas.errors` module, for type-related we have a private `pandas.types` and public `pandas.api.types`.

With the risk of keeping a settled discussion alive, I would still like to see this discussed some more.

To repeat the comment of @shoyer:

> Ultimately, I don't think this matters too much, but given a choice between:
> 1. `pandas.*` indicates private namespace, `pandas.api.*` includes a public namespace, and
> 2. `pandas.*` includes public namespace, `pandas._internals` (and so forth) indicates private namespace
>
> I think the later (option 2) is more user friendly and consistent with the top level namespace `pandas` already being public facing. 
>
> On the other hand, it's true that option 2 is a little harder to transition to (for us), so maybe it's not worth the trouble.

We have recently added new submodules to the top-level namespace (`pandas.types`, `pandas.indexes`, `pandas.formats`, code that was before mainly in `pandas.core. ..`), but towards the user these should be regarded as private. IMO this is not the good direction. For new code / refactors, I think we should stick to: only what is public can go in the top-level namespace. 

Let's take the example of `types`. We now have a private `pandas.types` and a public `pandas.api.types`, so the less nested location is private, which I don't find ideal. 
If we use the approach of `pandas.api.types`, I think we should at least make the actual implementation in `pandas._types`, so you don't have the two publicly visible locations. 
The other option is to make put now what is in `pandas.api.types`, in `pandas.types` (while the exact implementation and organization in the different submodules of `pandas.types` remains a private implementation detail).

**Comment by jreback** [comment]
Here's my rationale:

We have 3 stakeholders.

- users: regular folks who do ``import pandas as pd``
- library builders / advanced users: folks who need more 'library' code
- implementation

``implementation``: this may seem strange to mention, but *pandas* is a large library. We need the flexibility to move code around, expand modules, rename and generally get stuff done internally, with out having to constantly deprecate things. This would be extremely disruptive to the public (not to mention burdensome).

For example. ``pandas.types`` exists with several sub-modules that are logically defined, simply named and concise. There is not reason for 'users' or 'library' writers to access this at all. It exists simply to organize the code. Sure they can reach in if they really want, but we want to discourage this. Making it ``pandas._types`` would surely do this, but that is an ugly name and since this is pure python code a bit misleading.

'users': they are served by the top-level ``pd`` namespace, supplemented by ``pandas.errors``. Everything that one could need is here (or as a method).

'library': these folks need code generally for instrospection that is just too cumbersome to be in a 'user' namespace. Things like ``is_integer_dtype`` is a canonicial way to introspect things in pandas. We *use* these internally and provide them as an external API to library writers.

I recently added ``pandas.api.lib`` with ``infer_dtype``, which is a useful routine, again to external library writers. This is (or another sub-module of ``pandas.api``) can also be the home of a c-api / development api.

So, everything as public is just fine. If someone wants to reach in and use a routine from ``pandas.format.*`` or whatever they should have no expectations that this is stable across releases.

For simplicity from a user AND a library pov, its much better to have a single namespace ``pandas.api`` that say: hey they routines are what I should use, they are documented and won't change

The example above is the 'duplication' of ``pandas.api.types`` and ``pandas.types``. Again I don't see an issue here at all. ``pandas.types`` is just a namespace of a bunch of things. In fact the implementation of things that are actually in ``pandas.api.types`` are split among several different sub-modules (again for simplicity / implementation ease). So this argument to me doesn't hold any water.

**Comment by shoyer** [comment]
I don't see a strong division between "users" and "advanced users". There is a continuum of use cases. Certainly we should group more things into submodules: this makes it easier to find related functionality.

One choice that would make this super clear is move all internal stuff into a top level submodule called `internals`, e.g., `pandas.internals.core`, `pandas.internals.indexes`, etc. Then if you're importing from `pandas.internals.something`, you know it's an internal routine. Otherwise, as a user it's not obvious whether `pandas.something` exists to as a namespace to logically group together the `something` routines or if it's an internal implementation detail.

**Comment by jorisvandenbossche** [comment]
> For example. pandas.types exists with several sub-modules that are logically defined, simply named and concise. There is not reason a for 'users' or 'library' writers to access this at all. It exists simply to organize the code. 

That is not fully what I meant. The `pandas.types` module could still have different sub-modules, but what I meant was that only the 'top-level' of `pandas.types` would be public, so we are still free to implement it as we like in the submodules. 
And sure, we will change things in the future, but whether we expose the public names in `pandas.api.types` or in `pandas.types` (top-level, not submodules) does not really matter for that? In both cases the functions will not actually be defined in that location.

> Making it pandas._types would surely do this, but that is an ugly name and since this is pure python code a bit misleading.

This is IMO not misleading at all, it is actually very explicit that it is internal. 
And I agree it is a bit uglier, but is only about a few import lines in each pandas file. I don't think it is that problematic there is a bit ugliness there, and IMO worth the clarity (if we use the `pandas.api` approach). 
The `internals` namespace is also a possiblity, but this is actually more or less what `core` is currently. So we could use it for that I think (although less explicit in name). But we moved `types`, `formats`, `indexes` out of core .., so this would be putting it back (but keeping the reorganization in submodules). 

> 'users': they are served by the top-level pd namespace, supplemented by pandas.errors. Everything that one could need is here (or as a method).

This is already not fully the case. There are public methods in `pandas.io.json`, `pandas.tseries.offsets`, `pandas.plotting` (when that PR is merged), ..

> I recently added pandas.api.lib with infer_dtype, 

Slightly of topic, but I personally would rather put this in `pandas.types`, as it is type related. And the fact that it is in our `lib` is more an implemenation detail for the user.

**Comment by jreback** [comment]
ok so plan is to:

- document that ``pandas.core`` is private
- potentially search on github to see if we should be deprecating things more explicity
- move out of ``pandas`` to ``pandas.core`` namspace
  - ``computation``
  - ``formats``
  - ``indexes``
  - ``sparse`` 
  - ``tools``
  - ``tseries``
  - ``types``
  - ``util`` (maybe)?

- going to leave ``stats`` (as when we remove the deprecations for things like ``pd.rolling_mean`` this will go away anyhow

cc @wesm 
@jorisvandenbossche 
@TomAugspurger

**Comment by jorisvandenbossche** [comment]
I started some search on github, but most of the things on the first pages were just internal imports in people who embedded the full pandas codebase in their repo ... Does anybody know of more advanced github search methods for such things?

**Comment by jreback** [comment]
>people who embedded the full pandas codebase in their repo 

who the *heck* does that????

**Comment by jorisvandenbossche** [comment]
Regarding the above list, I am not sure we can easily move `tseries`, there are too many public functions in that module (offsets and frequencies). So we should think how to organize that one.

For `tools`, I would take the opportunity to reorganize that a bit. For example add a `reshaping` submodule for stack/unstack/pivot etc functionality? (just an idea, the current 'tools' name is not very descriptive)

**Comment by jorisvandenbossche** [comment]
> I am shortly going to move a bunch of things around. But pandas.io is going to stay (pandas.formats will move).

Can you maybe first give some more details here, so we can discuss some things first before you do the work? (I also have some time this weekend to look at it)
See my questions above (tseries). Further, `formats` could maybe be moved to `io` instead of `core` ? 
Regarding `util` (your questionmark), I  would maybe leave `util` where it is (that feels more logically), but then state that this is also private (together with core) ?

**Comment by jreback** [comment]
quickly did #15997 (stil WIP), moving ``pandas.formats`` -> ``pandas.core.formats``.

I think easy to move ``.computation``, ``.types``. Let's do that (I can provide a proxy deprecation module if needed). Then go from there.

Further we will then have a big warning somewhere that ``pandas.core`` is now considered private.

**Comment by jreback** [comment]
``.util`` yes could leave there where it is.

I think we should also state that ``.tseries`` is private as well.

``.tools`` I will also move to ``.core``

``.formats`` belongs in ``.core`` its about printing core stuff (not *really* about io per se).

**Comment by jorisvandenbossche** [comment]
> formats belongs in .core its about printing core stuff (not really about io per se).

But if we expose certain aspects of it in `io` or `io.formats`, it seems logical to just move it there. It is about printing core objects, yes, but the line between output and repr is not that clear (to_html, to_string are basically used for both)

**Comment by jreback** [comment]
could move to io just as well. ok, i'll do that after @TomAugspurger merges then.

any problem with the others that I mentioned?

**Comment by jorisvandenbossche** [comment]
> I think we should also state that .tseries is private as well.

Then we first need a assessment on what exactly is public in tseries (as there certainly are public objects there) and how we expose this.

**Comment by jorisvandenbossche** [comment]
> could move to io just as well

I don't see the point. This is a good example as a separate submodule in pandas, and there are certainly a lot of imports in the wild using it (as there is public api there)

**Comment by jorisvandenbossche** [comment]
Sorry, forget that previous comment (will delete it for clarity), I had understood you wanted to move io to core, not that you were ok with moving formats to io

**Comment by jreback** [comment]
> Then we first need a assessment on what exactly is public in tseries (as there certainly are public objects there) and how we expose this.

there is *nothing* that is explicity public. people reach in.

**Comment by jorisvandenbossche** [comment]
> there is nothing that is explicity public. people reach in.

Frequencies and offsets are *explicitly* imported from there and used in our docs.

**Comment by jreback** [comment]
``pandas.offsets`` is a thing, maybe we should make ``pandas.frequencies`` as well.

**Comment by jorisvandenbossche** [comment]
> pandas.offsets is a thing, maybe we should make pandas.frequencies as well.

We can probably combine both? (the distinction is not always clear) 
(I thought we deprecated pandas.offsets, but apparently I am wrong, and of course could have un-deprecated it :-))

**Comment by TomAugspurger** [comment]
Here are the interesting uses of `tseries.*` in the docs:


```
source/timedeltas.rst:18:   from pandas.tseries.offsets import *
source/timeseries.rst:735:   from pandas.tseries.offsets import *
source/timeseries.rst:878:    from pandas.tseries.offsets import CustomBusinessDay
source/timeseries.rst:902:    from pandas.tseries.holiday import USFederalHolidayCalendar
source/timeseries.rst:917:    from pandas.tseries.offsets import CustomBusinessMonthBegin
source/timeseries.rst:1047:    from pandas.tseries.holiday import USFederalHolidayCalendar
source/timeseries.rst:1252:    from pandas.tseries.holiday import Holiday, USMemorialDay,\
source/timeseries.rst:1272:    from pandas.tseries.offsets import CDay
source/timeseries.rst:1306:    from pandas.tseries.holiday import get_calendar, HolidayCalendarFactory,\
source/timeseries.rst:1513:    from pandas.tseries.frequencies import to_offset
```

So I think `holiday` in addition to offsets and frequencies.

**Comment by jreback** [comment]
I actually don't have a problem with ``pandas.tseries`` per-se, its everything underneath it!

(which I *will* move (mostly to ``core``). So we *could* keep the namespace (and just move everything out and import what is needed in ``__init__).

**Comment by jreback** [comment]
maybe we leave those 3 modules, e.g. ``offsets, holiday, frequncies``? (they do make logical sense there).

**Comment by jreback** [comment]
We need to move ``pandas.indexes`` as well.

**Comment by TomAugspurger** [comment]
So to summarize the *public* parts other than stuff imported into the top-level namespace (feel free to edit / move into the top post)

- pandas.api
- pandas.errors
- pandas.io.api
- pandas.stats (but deprecated)
- pandas.tools.plotting
- pandas.tseries.offsets (or are these 3 .tseries modules going to move?)
- pandas.tseries.holiday
- pandas.tseries.frequencies
- pandas.util (but documented as private?)

Is there anything else public in pandas.tools? (hashing?)

I think `pandas.util.testing` has to be public right?
Anything in that list incorrect?

**Comment by jreback** [comment]
``pandas.util.testing``, maybe move to ``pandas.testing`` ? (though I suspect this is imported in the outside world a lot!)

**Comment by jreback** [comment]
> is there anything else public in pandas.tools? (hashing?)

yeah maybe I should move ``hashing`` -> ``pandas.util``

**Comment by jorisvandenbossche** [comment]
> pandas.util.testing, maybe move to pandas.testing ?

I would go for `pandas.testing`, see https://github.com/pandas-dev/pandas/issues/9895. Will do a PR for that.

**Comment by jreback** [comment]
@jorisvandenbossche cool. will need a depr_module for ``pandas.util.testing`` as well I think.

**Comment by jorisvandenbossche** [comment]
Unless we leave it like that? If we leave util in place, we will still use `pandas.util.testing` internally, and we could opt for not deprecating it but just documenting the public ones?

The PR I am doing now is just exposing a selection of `pandas.utils.testing` in `pandas.testing`.

Could also move everything to `pandas.testing`, but then it is more difficult to only have a subset of the testing functions public.

**Comment by jreback** [comment]
that sound pretty reasonable

**Comment by jreback** [comment]
leaving
- ``util``: leave for now I think
- ``stats``: deprecated and will be removed in next version

moving
- ``tools``:
- ``indexes``
- parts of ``tseries``: this is a bit tricky, but will move some of this (leaving those we discussed above).

**Comment by jorisvandenbossche** [comment]
I just saw that `pandas.tools` is not yet fully removed (apart from the compat shims) due to `hashing`. It's a bit pity to have to keep that submodule just for hashing, so maybe we can move that to `pandas.core.tools` or to `pandas.utils` ?

**Comment by jorisvandenbossche** [comment]
Ah, I just see @jreback mentioned this above:

> yeah maybe I should move hashing -> pandas.util

+1 then

Are the hashing functions considered as public? Dask uses them, so maybe we should then? 
I also think they are only added in 0.20dev, so we can change location without deprecation?

**Comment by jreback** [comment]
these are used by dask. They are semi-public.

**Comment by jorisvandenbossche** [comment]
Ah, it seems I am mistaken. Those were already added in 0.19.2? (but not mentioned in whatsnew)

**Comment by jreback** [comment]
yeah they are using in a private API (they do fallback though). This was never 'public'

**Comment by jorisvandenbossche** [comment]
So options: a) keep them as they are, b) move to util (see PR) but keep as semi-public, c) move to util and document as public function?

**Comment by jreback** [comment]
I think b) is fine for now. These should really be internal with a couple of things exposed via ``pandas.api.lib`` (e.g. just ``hash_pandas_object`` and ``hash_array``), so could do that as well, but b) allows us to do that *later*

**Comment by jorisvandenbossche** [comment]
(using this issue as the general public/private api discussion issue).

In the PR in dask to be compatible with 0.20.0rc1 (https://github.com/dask/dask/pull/2249), they had to change imports for:

- `pandas.computation.expressions.set_use_numexpr` (now in `core`)
- `pandas.formats.printing.pprint_thing` (now in `io.formats`)
- `pandas.algos.groupsort_indexer` (now in `_libs.algos`)
- `pandas.tseries.resample.Resampler` (now in `core.resample`)
- (`pandas.formats.format._put_lines` -> only in testing)

(and further some of the testing functionality which they changed to using directly pytest (what we are doing as well))

Would we want to expose some of those in a public location? So they can use it more safely ? Or do we keep those private (and usage "on own risk")

**Comment by jreback** [comment]
I am all for making deprecations, but we should be very narrow in the scope. non-common things *should* break. We cannot willy nilly just deprecate everything that was moved otherwise noone will ever pay attention until we actually remove it and that's essentially the same problem. better to provide target fine grained deprecation warnings.

**Comment by jreback** [comment]
*dask* IS using private API's (for perf), so I think its ok to specfically change things for them. IOW no guarantees if you update pandas but NOT dask.

**Comment by shoyer** [comment]
This is something to be said for supporting a low-level API for performance sensitive tasks (NumPy does this pretty nicely, for example).

That said, most of these specifics that dask was using feel like implementation details.

Probably `set_use_numexpr` at least should be public API, via the options interface.

**Comment by jreback** [comment]
closing, but if anyone finds another place that thinks needs deprecation pls comment / open a new issue.

**Comment by jorisvandenbossche** [comment]
We currently have a couple of public top-level submodules: `pandas.errors`, `pandas.plotting`, `pandas.testing` and parts of `pandas.io` (although there in further submodules), and `pandas.api.types` 

Looking at this again, I find that the `pandas.api.types` feels a bit at odds with the others. For consistency, why not just having a `pandas.types` to expose the public type-related functionality?

I know `pandas.api.types` was already introduced in the previous release, but this is a module we will carry on with pandas for a long time, so if we still would change it, it is now. 
I don't think changing it would have too much impact. Of course packages like pyarrow and dask would have to make a small update to their codebase, but the old location (at core.common for most of the functions) is still available, so it won't complicate their pandas-compat code (they can just change pandas.api.types with pandas.types)

**Comment by jreback** [comment]
what is the purpose of pandas.plotting?

**Comment by jorisvandenbossche** [comment]
It holds the non-method plotting functions like `scatter_matrix`

**Comment by jreback** [comment]
so what is the argument for having that as a top level module then?

**Comment by TomAugspurger** [comment]
> so what is the argument for having that as a top level module then?

plotting or types? Assuming you mean `types`, Joris is saying `pandas.types` is more consistent with `pandas.errors, pandas.plotting, pandas.testing`.

**Comment by jreback** [comment]
actually no, I mean I don't really see the purpose of the top-level ``pandas.plotting``.

further ``pandas.api.*`` will be expanded in the future. I see no reason to change this.

**Comment by jreback** [comment]
the more I look at this the more I don't think we need ``pandas.plotting`` at all. These are all methods on Series or DataFarme, with the exception of ``scatter_matrix``. 

Why do we need this again?

**Comment by TomAugspurger** [comment]
scatter_matrix, radviz, andrews_curves, parallel_coordinates,  and autocorrelation_plot are all available in pandas.plotting and not on DataFrame.

**Comment by jorisvandenbossche** [comment]
> `pandas.api.*` will be expanded in the future.

What do we envisage that will end up in there, apart from type related things?

**Comment by jorisvandenbossche** [comment]
@jreback To come back to the `hashing` utilities, I didn't respond yet to this (https://github.com/pandas-dev/pandas/issues/13634#issuecomment-296207814):

> I think b) is fine for now. These should really be internal with a couple of things exposed via pandas.api.lib (e.g. just hash_pandas_object and hash_array), so could do that as well, but b) allows us to do that later

We now exposed the public hashing functions in `pandas.util.hashing`, which means we should keep it (the public exposure) there, and not later move it somewhere else. 
If we are not sure the implementation will be kept in `util.hashing`, we could also expose the public method just in `pandas.util` instead of `pandas.util.hashing`

**Comment by jreback** [comment]
both of those are not great
this is purely a library exposed for other developers (dask) so it's public to them 
if it's moved we can adjust dask but ituis is not public in any other way

**Comment by TomAugspurger** [comment]
Thoughts from anyone else? I think the proposals on the table are

Option 1 (current master);

- `pd.api.types`
- `pd.errors`
- `pd.io` (`.formats`, `.json`, etc.)
- `pd.plotting`
- `pd.testing`

Option 2 (move types up):

- `pd.types`
- `pd.errors`
- `pd.io` (`.formats`, `.json`, etc.)
- `pd.plotting`
- `pd.testing`

Option 3 (?)

- `pd.api.types`
- `pd.api.errors`
- `pd.api.io` (`.formats`, `.json`, etc.)
- `pd.api.plotting`
- `pd.api.testing`

**Comment by shoyer** [comment]
I like option 2.

**Comment by jreback** [comment]
master is what it is
so -1 on any changes

**Comment by jorisvandenbossche** [comment]
@jreback Can you answer my comment above? https://github.com/pandas-dev/pandas/issues/13634#issuecomment-298700790 (if you have an idea of course)

I am ok with option 1 / master (pandas.api.types), *if* we have an idea of what else we would put in `pandas.api`

**Comment by jreback** [comment]
> @jreback Can you answer my comment above? #13634 (comment) (if you have an idea of course)

yes I think we should move hashing to ``pandas.api.lib`` (or something like that) and import the 2 functions (and I'll update dask as well).

**Comment by jreback** [comment]
``pandas.util`` is also a bunch of random code. these should also not really be exposed and should really go in ``pandas.core.util``

**Comment by jorisvandenbossche** [comment]
>  I think we should move hashing to pandas.api.lib

The objection I currently have against `pandas.api.lib`, is that I think that the fact that some functionality (eg in this case the hashing functions) are implemented in `_lib` is an implementation detail (if they were not in compiled code, they would not be there), and IMO this implementation detail is not need to 'leak' to the user API.

**Comment by jorisvandenbossche** [comment]
Another example is the `cache_readonly` decorator. I was thinking to use this one in geopandas, so it would be nice if there is a public exposure of it. It would also fit in `util` or `pandas.api.lib`, depending on this discussion.

Util is indeed a bunch of random things, but that is in its name, it is a bunch of various useful utility functions that don't really belong somewhere else. I think something like `cache_readonly` fits in that description.

**Comment by jreback** [comment]
ok what i could do is make everything in until private but leave the top level namespace to export certain functions as a flat namespace

**Comment by jorisvandenbossche** [comment]
>  make everything in until private but leave the top level namespace to export certain functions as a flat namespace

yes, that would be a nice idea to expose certain things (like eg the cache_readonly) in the util submodule

**Comment by jreback** [comment]
ok have a look for anything else 
maybe Appender, Substitution
