### ISSUE TITLE
Series.to_string ignores empty lines at the start/end when index=False

### ISSUE THREAD

**Issue by alberthdev** [pandas-dev/pandas#13653]
When running `to_string` on a Series with empty strings at the beginning and end of the Series data, the empty strings are removed from the resulting output. These empty strings should be included to represent the empty data.
#### Code Sample:

``` python
import pandas as pd
pd.Series(["", "Hello", "World", "", "", "Mooooo", "", ""]).to_string(index=False) 
```
#### Expected Output:

``` python
u'\nHello\nWorld\n     \n     \nMooooo\n\n'
```
#### Actual Output:

``` python
u'Hello\nWorld\n     \n     \nMooooo'
```
#### `pd.show_versions()`:

```
>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.8.final.0
python-bits: 64
OS: Linux
OS-release: 3.0.101-0.47.67-default
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.18.1
nose: 1.3.6
pip: 1.5.6
setuptools: 3.6
Cython: 0.24
numpy: 1.10.4
scipy: 0.17.0
statsmodels: 0.6.1
xarray: 0.7.2
IPython: 4.2.0
sphinx: 1.2.2
patsy: 0.3.0
dateutil: 2.3
pytz: 2015.4
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4
matplotlib: 1.5.1
openpyxl: 2.0.4
xlrd: 0.9.0
xlwt: 0.7.4
xlsxwriter: 0.7.3
lxml: 3.4.4
bs4: 4.3.2
html5lib: 1.0b8
httplib2: None
apiclient: None
sqlalchemy: 0.9.7
pymysql: 0.6.2.None
psycopg2: None
jinja2: 2.8
boto: 2.34.0
pandas_datareader: None
```

**Comment by TomAugspurger** [comment]
There are a couple `.strip`s in [here](https://github.com/pydata/pandas/blob/3f6d4bdd63d9a1ae27e587bd033e507f7a5e1109/pandas/formats/format.py#L605)

Want to look into that a bit, see if removing those fixes your problem, and if making those changes break any tests?

**Comment by alberthdev** [comment]
I think this line is the problem:
https://github.com/pydata/pandas/blob/3f6d4bdd63d9a1ae27e587bd033e507f7a5e1109/pandas/formats/format.py#L259

Changing `.strip()` to `.strip(' \t')` and adding on a `.replace('\n ', '\n')` at the end seems to get a somewhat more desired result:
```python
In [2]: pd.Series(["", "Hello", "World", "", "", "Mooooo", "", ""]).to_string(index=False)
Out[2]: u'\nHello\nWorld\n     \n     \nMooooo\n     \n'
```

Alternatively, we could also try something like this:

```result = "\n".join([s.strip() for s in self.adj.adjoin(3, fmt_values).split('\n')])```

That said, there might be more things done in terms of parsing the DataFrame. I think it might be useful to ensure that no padding is added if we're dumping it out to a string, unless otherwise specified... not sure how you guys want to handle it!

**Comment by dsaxton** [comment]
Looks fixed in master, could use a test if there isn't one already:
```python
[ins] In [1]: import pandas as pd

[ins] In [2]: print(pd.__version__)
1.2.0.dev0+518.g027f36541

[ins] In [3]: s = pd.Series(["", "Hello", "World", "", "", "Mooooo", "", ""])

[ins] In [4]: s.to_string(index=False)
Out[4]: '      \n Hello\n World\n      \n      \nMooooo\n      \n      '
```

**Comment by NomadicDaggy** [comment]
take
