### ISSUE TITLE
Decide recommended version of optional packages 

### ISSUE THREAD

**Issue by sinhrks** [pandas-dev/pandas#13681]
For these optional deps, pandas doesn't specify the supported versions. Therefore, pandas needs some codes to support older ones.
- scipy 
- matplotlib
- openpyxl

I don't think we need strict support version policy for these packages, but how about once decide "recommended versions", and show warnings if user env doesn't meet it (can remove legacy codes in future maybe).

**Comment by jreback** [comment]
closing, good enough for now
