### ISSUE TITLE
CLN: cleanup bench / scripts

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#13704]
now that we removed `sandbox` in #13670, some scripts remain that use this.
- [x] I think we could fully remove the `bench` sub-dir, taking care if we don't have asv's for anything there (I think we do but need to check). (PR https://github.com/pandas-dev/pandas/pull/16984)
- [x] `scripts` dir, we can blow windows_builder (PR #16984)
- [ ] `scripts` dir, we can blow away most of these with the exception of: `api_rst_coverage.py`, `find_undoc_args.py`, `merge-py.py`, `find_commits_touching_func.py`, again checking for any benchmark scripts and make sure we have asv.
- [ ] add README.md for `scripts` that documents purpose of these scripts
- [x] ~~move `pandas/build_dist.sh` and `pandas/release_stats.sh` to `scripts` (need to updat e commit checklist though and slightly modify).~~
- [x] ~~remove `pandas/test_perf.sh` and `pandas/Makefile`~~

**Comment by jreback** [comment]
cc @jorisvandenbossche

**Comment by jorisvandenbossche** [comment]
+1 for a clean-up. I think we can also remove the `vb_suite`? (just need to look back at the conversion PR to see if some parts didn't get converted)

For the `bench` dir, indeed need to check if there is content that could be moved to asv. Only the python vs R benchmarks would not be suited for that, but I am not sure if we have to keep that in the pandas repo.

I also want to clean-up the auto-converted asv bench (now a lot of duplicated setup things, which makes it difficult to get an overview of that)

**Comment by jorisvandenbossche** [comment]
Also the `test_perf.sh` can be removed. 

Do you actually use the ``Makefile``?

**Comment by jreback** [comment]
yes ``test_perf.sh`` can go. the ``Makefile`` I actually do use it, but no real objection to removing it; we use ``python setup.py build_ext --inplace`` is the default anyhow (and the Makefile doesn't work on windows).

**Comment by sinhrks** [comment]
wiki needs to be updated also:

- https://github.com/pydata/pandas/wiki/Performance-Testing

**Comment by jorisvandenbossche** [comment]
@jreback no, it's fine to keep `Makefile` if people use it (I use bashrc aliases for shortcuts for those things)

@sinhrks I think that wiki page can just be deleted (or, should check if there is still any explanatory content that can be moved to contributing.rst)

**Comment by jorisvandenbossche** [comment]
I already did part of this locally, but removing it from 0.19.0 milestone as it is not a blocker
