### ISSUE TITLE
Add tz kw to to_datetime, deprecate utc

### ISSUE THREAD

**Issue by sinhrks** [pandas-dev/pandas#13712]
xref #17603 - can be simplified when this issue is fixed

To be compat with `DatetimeIndex` kwds. The impl should be pretty straightforward.
- http://pandas.pydata.org/pandas-docs/stable/generated/pandas.to_datetime.html

**Comment by tacaswell** [comment]
bread crumbs back to https://github.com/pandas-dev/pandas/issues/6415

**Comment by mroeschke** [comment]
A patch (PR #17603) to address localizing naive datetime strings with a datetime64tz dtype can be simplified once this issue has been solved.

**Comment by mroeschke** [comment]
I'd be personally -1 on adding a `tz` since we have `tz_localize` and `tz_convert`. Since there hasn't been much activity on this issue I am going to close but open to feedback from others.
