### ISSUE TITLE
CI: setup 32-build linux build on travis

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#13715]
so if anyone is interested: https://github.com/matthew-brett/multibuild/tree/7abbd01f230be6067842f0510a98b06a6320ddf9

hosts the builder for the wheels, it does a 32-build on linux via a docker image. So we could just directly pull that same image and build (of master).

cc @matthew-brett 

xref #13584

**Comment by gfyoung** [comment]
> Azure does possibly support 32bit builds directly? (to check)

@jorisvandenbossche : My guess is probably not, but couldn't hurt to check.

@datapythonista : Who was your contact at Microsoft regarding Azure builds?

**Comment by gfyoung** [comment]
@datapythonista : Cool, thanks!

@vtbassmatt : Does Azure have support for 32-bit testing environments?

**Comment by vtbassmatt** [comment]
We don't offer hosted 32-bit environments but we do ship a 32-bit Windows
and Linux agent. You can set up private agents with that.

**Comment by gfyoung** [comment]
@vtbassmatt : That's good to know.  Thanks!

**Comment by jbrockmendel** [comment]
we've got a 32 bit build on azure.  closeable?
