### ISSUE TITLE
DOC: give read_clipboard a signature

### ISSUE THREAD

**Issue by chris-b1** [pandas-dev/pandas#13726]
Wouldn't necessarily need to add everything that `read_table` accepts, but at minimum adding a couple common ones like `delim_whitespace` and `sep` would make it nicer for argument completion in interactive use.

https://github.com/pydata/pandas/blob/master/pandas/io/clipboard.py#L6

**Comment by sinhrks** [comment]
Actually it is:) PR is appreciated.
