### ISSUE TITLE
API: add encoding for to_json()

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#13774]
xref #13351

[Here's the test](https://github.com/pydata/pandas/commit/964b7bba7f5878c79130479f75461c58dd0c4b3e), currently skipped

**Comment by jorisvandenbossche** [comment]
@aterrel Interested in doing this one?

**Comment by aterrel** [comment]
Yeah, I've been a bit of of pocket but I'll check it out this weekend

**Comment by WillAyd** [comment]
Outside of "closed systems" I think there is an established internet standard for JSON to be UTF-8. See section 8.1 in:

https://www.rfc-editor.org/info/rfc8259

Worth closing at this point?

**Comment by mroeschke** [comment]
Will brings up a good point in addition to not much traction on this enhancement request, closing
