### ISSUE TITLE
API: clean-up top-level namespace

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#13790]
Triggered by #13785, I looked at the top level namespace, and I was wondering if the following functions are needed:
- [ ] `pd.Expr`
- [ ] `pd.pnow()`: returns the current date as a Period with specified freq (https://github.com/pydata/pandas/issues/12641)
- [ ] `pd.info()`
- [ ] `pd.groupby()`
- [ ] `match`: "Compute locations of to_match into values" (imported from `core/api.py` from `\core\algorithms.py` together with `factorize`, `unique` and `value_counts`, but I don't think `match` is used anywhere in the docs)
- [ ] `pd.Term`

Quite a lot are already deprecated: `TimeSeries`, `SparseTimeSeries`, all `rolling_` and `expanding_` methods

I also learned the existence of `pd.lreshape` and `pd.plot_params` .. :-) (but the latter is mentioned in the docs, `lreshape` not).

**Comment by jreback** [comment]
I think there is an issue for pnow already

in any event I would make this a master issue and have checkboxes

**Comment by jorisvandenbossche** [comment]
Ah yes indeed: https://github.com/pydata/pandas/issues/12641 Good question :-)

Updated top comment
