### ISSUE TITLE
Feature suggestion: custom DataFrame HTML display (for IPython notebook)

### ISSUE THREAD

**Issue by nadavbra** [pandas-dev/pandas#13826]
I looked briefly at your new custom styling feature from version 0.17.1 (http://pandas.pydata.org/pandas-docs/stable/style.html). I'm excited about the possibilities of custom styling and all the benefits it would allow researchers, but I feel that the current interface is somewhat non-intuitive and limited.
I would like to suggest a single generic feature that has the potential to include almost all other existing features, and allow a lot more flexibility. The idea is to allow overriding the default function that "draws" the elements in the dataframe as HTML table cells.

Let's say that this drawing function is `df.style.draw_element` and it receives the following arguments:
- **value** (any object/dtype): the value of the element to display
- **column** (str): the name of the value's column
- **row** (pandas.Series): the value of the entire element's row (if one wants to make a context-dependent drawing)

Additionally you can also add **index** and **df** as arguments, if you want to allow even more flexible context-dependent drawing.

The default built-in implementation of this function is just:
`def draw_element(value, column, row): return str(value)`
(i.e. every element is just displayed as it is)

But now, it will allow users to override it and add their own cool functionality. For example, one could do the following:
`df.style.draw_element = lambda: value, column, row: str(value) if value >= 0 else '<div style = "background-color: red;">%s</div>' % str(value)`
This will highlight in red all the negative values in the table.

This trick is already achievable with the current interface, but here's another example for some cool application that I don't think can be achieved with the current interface. Suppose that a bioinformatician working with DNA sequences (made of the four letters A, C, G, T) is interested in drawing each DNA letter with a different color (although all the letters are part of a single sequence within the same element in the dataframe). Using the new interface she will be able to simply do the following:
`df.style.draw_element = lambda: value, column, row: ''.join(['<span style = "color: %s;">%s</span>' % (get_dna_letter_color(letter), letter) for letter in value]) if 'dna' in column.lower() else  str(value)`
How cool is that? :)

**Comment by TomAugspurger** [comment]
Hi,

> but I feel that the current interface is somewhat non-intuitive and limited.

I would love to hear what parts of that API you found non-intuitive / limited.
I know that the documentation can be improved.

I could be wrong, but one issue with your proposed API is that it doesn't allow for styles that are functions of entire rows / columns.
The `draw_element(value, col_name, row_name)` has no access to the column, row, or table that `value` came from. Indeed, my initial implementation was quite similar to what you've proposed, before I switched to the current API, which I think is more flexible.

Your first example is written as

```python
def color_negative_red(val):
    color = 'red' if val < 0 else 'black'
    return 'color: %s' % color

df.style.applymap(color_negative_red)
```

Which I think is readable and consistent with the general pandas API.

Could you show an example of the output from your second column. If I understand correctly, it would be a single column? The current API does limit the output of `.style` to be the same shape as the input. Though there's nothing to prevent you from collapsing the data to a single column before calling `.style`.

In general, I'm looking for use-cases and feedback on what parts are difficult, so please share and let me know if I got anything wrong.

**Comment by nadavbra** [comment]
I don't think that my second example can be implemented with the current API.

Suppose that you have the following simple 2X2 dataframe:
**dna_seq length**
ACGTGCA 7
ACC 3

My code above in intended to produce the following HTML output:
    &lt;table&gt;
        &lt;tr&gt;
            &lt;th&gt;dna_seq&lt;/th&gt;
            &lt;th&gt;length&lt;/th&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td&gt;&lt;span style = "color: blue;"&gt;A&lt;/span&gt;&lt;span style = "color: red;"&gt;C&lt;/span&gt;&lt;span style = "color: green;"&gt;G&lt;/span&gt;&lt;span style = "color: yellow;"&gt;T&lt;/span&gt;&lt;span style = "color: green;"&gt;G&lt;/span&gt;&lt;span style = "color: red;"&gt;C&lt;/span&gt;&lt;span style = "color: blue;"&gt;A&lt;/span&gt;&lt;/td&gt;
            &lt;td&gt;7&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td&gt;&lt;span style = "color: blue;"&gt;A&lt;/span&gt;&lt;span style = "color: red;"&gt;C&lt;/span&gt;&lt;span style = "color: red;"&gt;C&lt;/span&gt;&lt;/td&gt;
            &lt;td&gt;3&lt;/td&gt;
        &lt;/tr&gt;
    &lt;/table&gt;

**Comment by TomAugspurger** [comment]
Thanks for the example, here's how I would write that

```python
def formatter(v):
    cmap = {"A": "blue", "C": "red", "G": "green", "T": "yellow"}
    return ''.join(['<span style="color: {}">{}</span>'.format(cmap[s], s)
                   for s in v])
    

df.style.format({"dna_seq": formatter})
```

![screen shot 2016-07-28 at 8 44 46 am](https://cloud.githubusercontent.com/assets/1312546/17214643/94c90eda-549f-11e6-964c-0da6a84b7b1c.png)

[gist](https://gist.github.com/8e457dca4f490eee6d973362d52d626c)
 This does stretch the current API a bit, since `.apply` / `.applymap` assumes you're returning CSS, not generating new `div`s / `span`s each with their own style. One thing that might be impossible (at least more difficult) is if the `formatter` function needed to rely on any information not in the actual cell value. The row / column name or position for example.

**Comment by TomAugspurger** [comment]
One question on your API. Say I wanted to apply multiple styles to a single cell. If I do `df.style.draw_element = func1`, then `df.style.draw_element = func2`, is the first overridden? It'd be a bit strange to have assignment append rather than overwrite, but how would you layer styles?

**Comment by nadavbra** [comment]
Thank you for the code example you gave. I didn't understand from the documentation that you could use `df.style.format` to inject HTML code. This actually solves the main limitation I thought that existed in the API.

I've just faced another problem though (maybe it should be discussed in another thread): it seems that `df.style.format` works on the entire dataframe, and doesn't support compact display like the automatic behavior when you have large dataframes (i.e. I would expect it to call my custom function only for values it's going to present anyway). 

As for your question, according to the API I suggested, the whole point was to have a single global formatting function, so indeed in your example **func2** would override **func1**. If you want to have both, each for a different column, you could do the following:

```python
def draw_element(value, col_name, row_name):
    if col_name == 'col1':
        return func1(value, col_name, row_name)
    elif col_name == 'col2':
        return func2(value, col_name, row_name)
    else:
        return str(value)

df.style.draw_element = draw_element
```

Alternatively, you could expend the API further and supply **df.style** with a dictionary that maps each column to a different style function. Then each column will use its own specific **draw_element** function, or the default **draw_element** function if none is given for it.

**Comment by TomAugspurger** [comment]
> it seems that df.style.format works on the entire dataframe

Truncation isn't implemented yet, though would be welcome if anyone is interested in implementing it.

**Comment by jorisvandenbossche** [comment]
@nadavbra @TomAugspurger are still concrete issues open to solve remaining from this discussion?

**Comment by TomAugspurger** [comment]
I think everything is resolved as there's another issue for truncation. We could document the ability to inject arbitrary HTML in the `.format` method, but I'd rather not, in case we come across a better way of doing it (the current way feels hacky). Any unaddressed issues @nadavbra?
