### ISSUE TITLE
API: Add support for PEP 519

### ISSUE THREAD

**Issue by AnkurDedania** [pandas-dev/pandas#13823]
File System Path Protocol has been accepted and implemented into Python 3.6, a backwards compatibility layer to support the introduced PEP 519 for python version < 3.6.

**Comment by shoyer** [comment]
See this section for guidance relevant to pandas:
https://www.python.org/dev/peps/pep-0519/#backwards-compatibility

> Libraries wishing to support path objects and a version of Python prior to Python 3.6 and the existence of `os.fspath()` can use the idiom of `path.__fspath__() if hasattr(path, "__fspath__") else path` .

**Comment by flying-sheep** [comment]
so we add to `compat/__init__.py` (with extracted stuff from [here](https://github.com/pandas-dev/pandas/pull/11051/files))

```python
def fspath(path):
	if isinstance(path, (str, bytes)):
 		return path

	path_type = type(path)
	
	if _PATHLIB_INTSTALLED and isinstance(path, pathlib.Path):
		path = text_type(path)  # 3.4/3.5 compat
	if _PYPATH_INSTALLED and isinstance(path, LocalPath):
		path = path.strpath
	else:
		try:
			path = path_type.__fspath__(path)
		except AttributeError:
			if hasattr(path_type, '__fspath__'):
				raise
		else:
		if isinstance(path, (str, bytes)):
			return path
		else:
			raise TypeError("expected __fspath__() to return str or bytes, not " + type(path).__name__)

	raise TypeError("expected str, bytes, py.path.LocalPath or os.PathLike object, not " path_type.__name__)
	else:

**Comment by jreback** [comment]
there are already routines in io/common.py to handle pathlike things - they just need some updating
