### ISSUE TITLE
Feature suggestion: flexible merge by function

### ISSUE THREAD

**Issue by nadavbra** [pandas-dev/pandas#13825]
It would be really convenient to allow the **on**, **left_on** and **right_on** arguments of **pandas.merge** being a function, with the following suggested signatures:

Arguments:
- **index** (pandas.Index)
- **row** (pandas.Series)

They will return an hashable object (of any dtype) to be compared against the other dataframe when doing the merge.

For example, you will be able to the the following:
`pd.merge(df1, df2, on_left = 'first_name', on_right = lambda index, row: parse_first_name(row['full_name']))`
This way, although **df2** doesn't have a **first_name** column (only **full_name**), it will be mergable with **df1** without any preprocessing step.

I would also like to suggest that leaving **on**, **left_on** and **right_on** with **None** would result the full Cartesian product of the two dataframes.

**Comment by sinhrks** [comment]
I can't imagine what the suggested feature like.

When merging columns doesn't exists, we can pass ``array`` via ``xxx_on`` kw as below.

```
df1 = pd.DataFrame({'x': ['A', 'B']})
df2 = pd.DataFrame({'y': [1, 2]})

pd.merge(df1, df2, left_on='x', right_on=np.array(['B', 'A']))
#    x  y
# 0  A  2
# 1  B  1
```

Thus, your example looks to be covered by preparing vertorized function as below.

```
pd.merge(df1, df2, left_on = 'first_name', on_right = parse_first_name_vectorized(df2))
```

Is there anything can't be covered using current spec?

**Comment by nadavbra** [comment]
The current spec can indeed achieve this, but I believe that giving a function that works element-wise is more easy and intuitive than working in a vectorized fashion.

**Comment by sinhrks** [comment]
Unfortunately it sounds complex rather than intuitive (at least for me), but it may be possible for you to provide convenient usecases.

**Comment by mroeschke** [comment]
Closing as stale.
