### ISSUE TITLE
Series.loc/iloc[x, y] does not raise exception

### ISSUE THREAD

**Issue by pkch** [pandas-dev/pandas#13831]
#### Code Sample, a copy-pastable example if possible

```
df = pd.DataFrame({'a': [10]})
# df['a'] is a series, can be indexed with 1 index only

# will raise IndexingError, as expected
df['a'].iloc[0, 0]
df['a'].loc[0, 0]

# will raise nothing, not as expected
df['a'].iloc[0, 0] = 1000 # equivalent to pass
df['a'].loc[0, 0] = 1000 # equivalent to df['a'].loc[0] = 1000

```

See [this SO post](http://stackoverflow.com/a/38644472/336527)
#### Expected Output

Expected an IndexingError exception in every case where two values are used to index a Series.
#### output of `pd.show_versions()`

pandas version 0.18.1, python 3.5

**Comment by jreback** [comment]
this is a bug for a non-MultiIndex. (for ``.loc``). ``.iloc`` should raise as well.

BUT this IS valid for a MI.

In [10]: s = Series([1,2,3], index=pd.MultiIndex.from_tuples([(0,'a'),(0,'b'),(1,'a')]))

```
In [11]: s
Out[11]: 
0  a    1
   b    2
1  a    3
dtype: int64

In [12]: s.loc[0,'d'] = 4

In [13]: s
Out[13]: 
0  a    1
   b    2
1  a    3
0  d    4
dtype: int64
```

**Comment by jreback** [comment]
pull requests are welcome, keep in mind that there are hundreds of existing test cases that still must pass, so careful changing things.

Further note that you ARE chained indexing, and SETTING, which in this particular case is ok (as its a single dtype), but in general is NOT recommended, nor can you always detect it.

**Comment by jreback** [comment]
This does raise for a non-integer index already (for ``.loc``)

```
In [22]: s = Series([1,2,3], index=list('abc'))

In [23]: s.loc[0,1] = 5
KeyError: '[0 1] not in index'
```

so this could use some more comprehensive testing.

**Comment by simonjayhawkins** [comment]
the iloc setitem case now raises as expected. on 0.25.3 gave `IndexingError: Too many indexers` same as the getitem cases. but on master now gives `IndexError: too many indices for array`

the loc setitem still does not raise.

**Comment by DriesSchaumont** [comment]
take
