### ISSUE TITLE
BUG/API Series/Index integer floordiv/mod inconsistency

### ISSUE THREAD

**Issue by sinhrks** [pandas-dev/pandas#13843]
`Series` looks to be coerced to `float` if the result contains `NaN` or `inf`. Otherwise `Index` doesn't. Make it to be consistent in either way.
#### Code Sample, a copy-pastable example if possible

```
pd.Series([1]) // pd.Series([0])
#0    inf
# dtype: float64

pd.Index([1]) // pd.Index([0])
# Int64Index([0], dtype='int64')

np.array([1]) // np.array([0])
# array([0])
```

```
pd.Series([1]) % pd.Series([0])
#0   NaN
# dtype: float64

pd.Index([1]) % pd.Index([0])
# Int64Index([0], dtype='int64')

np.array([1]) % np.array([0])
# array([0])
```
#### output of `pd.show_versions()`

on current master.

**Comment by jreback** [comment]
this was set this way a while ago - Index should be the same

numpy is wrong as it doesn't coerce types

**Comment by sinhrks** [comment]
OK. Found inconsistencies between int/float ``Series`` also. Both should be ``inf`` as the same as ``truediv``?

```
np.__version__
# '1.11.1'

# OK
pd.Series([4]) // pd.Series([0])
# 0    inf
# dtype: float64

# NG
pd.Series([4.]) // pd.Series([0.])
# 0   NaN
# dtype: float64

# truediv, OK
# pd.Series([4.]) / pd.Series([0.])
# 0    inf
# dtype: float64
```

**Comment by jbrockmendel** [comment]
Added to the TODO list in #18824.  FWIW all of the examples above except for `pd.Series([4.]) // pd.Series([0.])` have been fixed.
