### ISSUE TITLE
DOC: link to install instructions in README.md

### ISSUE THREAD

**Issue by aseering** [pandas-dev/pandas#13870]
_edit: the install instructions in the github README.md are out of date. They should link to the install instructions on the website_

---

I'm not sure what the expectation is here, but it seems to me that something's not right...  The [installation instructions](https://github.com/pydata/pandas/#where-to-get-it) say that `easy_install` has access to binary packages.  However, `easy_install` fails if the appropriate compiler is not available.  Would it be possible to either clarify the instructions to explain that binary packages are not available via `easy_install`, or fix the package to work without a compiler?
#### Code Sample, a copy-pastable example if possible

```
C:\> easy_install.exe pandas
```
#### Expected Output

Pandas should be successfully installed
#### Actual Output

`error: Setup script exited with error: Microsoft Visual C++ 9.0 is required (Unable to require vcvarsall.bat).  Get it from http://aka.ms/vcpython27`
#### output of `pd.show_versions()`

`easy_install` is trying to install `pandas-0.18.1`.
However, it is not succeeding.  As a result, `import pandas as pd` throws `ImportError` and I cannot run this command.

**Comment by aseering** [comment]
For reference:  `easy_install.exe numpy` works fine on this machine.

**Comment by TomAugspurger** [comment]
Sorry that README is out of date. Install instructions are at http://pandas.pydata.org/pandas-docs/stable/install.html

does `pip install pandas` work for you?

**Comment by aseering** [comment]
Thanks @TomAugspurger for the reply!  Unfortunately, no -- `pip install pandas` hits the same error.

**Comment by TomAugspurger** [comment]
What are you Python and pip versions? Any semi-recent version of pip should work.

See this list of binary wheels at https://pypi.python.org/pypi/pandas/0.18.1, which is what `pip install pandas` fetches from.

**Comment by aseering** [comment]
Ah, that did it!  This machine has Python 2.7.9 and pip 1.5.6.  `pip install --upgrade pip` upgraded to pip 8.1.2.  After the upgrade, `pip install pandas` succeeds.

**Comment by jorisvandenbossche** [comment]
This was closed by https://github.com/pandas-dev/pandas/pull/13882
