### ISSUE TITLE
ERR: set errno in read_csv

### ISSUE THREAD

**Issue by Murmuria** [pandas-dev/pandas#13872]
The same is true for Pandas on Python 2.7 with except IOError and on Python 3.5 with OSError. The following is how to reproduce the bug on Python 3.5. 

Pandas is not reporting any errno within the exceptions. As a result, there is no way to differentiate between File Not Found Error (ENOENT) and other types of OSErrors. 
#### Code Sample

```
try:
    pd.read_csv("dummy_file")
except OSError as e:
    print(e.errno, errno.ENOENT)
```
#### Current Output

(None, 2)
#### Expected Output

(2, 2)
## INSTALLED VERSIONS

commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Darwin
OS-release: 15.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.2
setuptools: 23.0.0
Cython: 0.24
numpy: 1.11.1
scipy: 0.17.1
statsmodels: 0.6.1
xarray: None
IPython: 4.2.0
sphinx: 1.4.1
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: 1.1.0
tables: 3.2.2
numexpr: 2.6.0
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.2
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.40.0
pandas_datareader: None

**Comment by jreback** [comment]
I suppose. checking ``errno`` if quite non-pythonic. If you would like to submit a fix would take it though.

**Comment by jreback** [comment]
```
In [4]: pd.read_csv("dummy_file")
OSError: File b'dummy_file' does not exist
```
this is already a pretty useful error

**Comment by Murmuria** [comment]
Yes, the string error is fine. However, when you want to handle only the file does not exist error gracefully, and `raise` for all other errors, you always need to check the `e.errno`, something along these lines:

```
try:
    open("dummy_file")
except OSError as e:
    if e.errno != errno.ENOENT:  # errno.ENOENT = no such file or directory
    raise
```

**Comment by jreback** [comment]
its way more pythonic is to check for existence explicity then.
these errno's are a throwback to before exception checking.

as I said if you want to submit a patch, by all means.

**Comment by gfyoung** [comment]
@jreback : I agree with what you're saying about this and that error number isn't necessary without more justification.  Would vote to close unless more info can be provided.

**Comment by mroeschke** [comment]
This appears to work on master now. I suppose it could use a test

```
In [80]: import errno

In [81]: try:
    ...:     pd.read_csv("dummy_file")
    ...: except OSError as e:
    ...:     print(e.errno, errno.ENOENT)
    ...:
2 2
```
