### ISSUE TITLE
Pandas 0.18.1 groupby and resample with multilevel aggregation error

### ISSUE THREAD

**Issue by rwester** [pandas-dev/pandas#13964]
Initially posted here: http://stackoverflow.com/questions/38861244/pandas-0-18-1-groupby-and-resample-with-multilevel-aggregation-error

From the documentation at the below links, both df3_resample and df4_resample should return the same dataframe, however df4_resample throws an exception. 

http://pandas.pydata.org/pandas-docs/version/0.18.0/whatsnew.html#whatsnew-0180-breaking-resample

http://pandas.pydata.org/pandas-docs/version/0.18.1/whatsnew.html#groupby-syntax-with-window-and-resample-operations

```
df = pd.DataFrame(np.random.rand(10,4),
                  columns=list('ABCD'),
                  index=pd.date_range('2010-01-01 09:00:00', periods=10, freq='s'))
df['item'] = 'item_a' # add column for groupby

df3_resample = df.groupby('item').apply(lambda x: x.resample('2s').agg({'A': {'A_mean': np.mean, 'A_max': np.max}}))

df4_resample = df.groupby('item').resample('2s').agg({'A': {'A_mean': np.mean, 'A_max': np.max}})
```

**Comment by theultimatecrouton** [comment]
Taking a look

**Comment by jreback** [comment]
I think this is the same issues as with #13914

**Comment by mroeschke** [comment]
`df4_resample` no longer raises and error on master. Could use a regression test with the new agg syntax.

```
In [6]: df4_resample
Out[6]:
                                          A
       item
A_max  item_a 2010-01-01 09:00:00  0.695760
              2010-01-01 09:00:02  0.335017
              2010-01-01 09:00:04  0.126488
              2010-01-01 09:00:06  0.654628
              2010-01-01 09:00:08  0.248379
A_mean item_a 2010-01-01 09:00:00  0.370121
              2010-01-01 09:00:02  0.251890
              2010-01-01 09:00:04  0.081013
              2010-01-01 09:00:06  0.481055
              2010-01-01 09:00:08  0.164289
```

**Comment by mroeschke** [comment]
Actually looks multilevel aggregations are specifically not allowed, so I think the fact that this operation doesn't work is intended.

https://github.com/pandas-dev/pandas/blob/7c94949dc89c62cae1bc647acd87266d6c3a0468/pandas/core/base.py#L351
