### ISSUE TITLE
DataFrame with one column, which is categorical: single rows convert to scalars

### ISSUE THREAD

**Issue by ChickenProp** [pandas-dev/pandas#14011]
#### Code Sample, a copy-pastable example if possible

``` python
In [2]: pd.DataFrame({'x': pd.Categorical('a b c d e'.split())}).iloc[0]
Out[2]: 'a'
```
#### Expected Output

I think this should be a Series with one element:

``` python
0    a
dtype: category
Categories (5, object): [a, b, c, d, e]
```

by analogy with the non-Categorical case:

``` python
In [3]: pd.DataFrame({'x': 'a b c d e'.split()}).iloc[0]
Out[3]:
x    a
Name: 0, dtype: object
```

This bug also exhibits with `.loc[0]` and `.ix[0]`. It doesn't happen if the original dataframe has more than one column, even if they're all categorical.
## INSTALLED VERSIONS

commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Darwin
OS-release: 15.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.2
setuptools: 18.5
Cython: 0.23.4
numpy: 1.11.1
scipy: 0.18.0
statsmodels: 0.6.1
xarray: None
IPython: 4.0.1
sphinx: 1.3.1
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.6.1
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.6.0
matplotlib: 1.5.1
openpyxl: 2.2.6
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.7.7
lxml: 3.4.4
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.9
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.40.0
pandas_datareader: None

**Comment by mroeschke** [comment]
This looks to work on master. Could use a test.

```
In [112]: In [2]: pd.DataFrame({'x': pd.Categorical('a b c d e'.split())}).iloc[0]
     ...:
Out[112]:
x    a
Name: 0, dtype: category
Categories (5, object): [a, b, c, d, e]

In [113]: pd.__version__
Out[113]: '0.26.0.dev0+652.g30362ed82'
```

**Comment by ryankarlos** [comment]
@mroeschke had a go at this
