### ISSUE TITLE
unable to set xticks within bar() plotting function

### ISSUE THREAD

**Issue by evfro** [pandas-dev/pandas#14119]
#### Code Sample, a copy-pastable example if possible

In the code below:

``` python
pd.Series(range(10), index=range(10)).plot.bar(xticks=range(0, 11, 2))
```

`xticks` argument has no effect.  However, there's no such problem in line() plot.
#### Expected Output

Output plot is expected to have xticks defined by `xticks` argument, e.g. in the example above it should be set to [0, 2, 4, 6, 8, 10].
#### output of `pd.show_versions()`

commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.1
nose: None
pip: 8.1.2
setuptools: 23.0.0
Cython: None
numpy: 1.11.1
scipy: 0.17.1
statsmodels: None
xarray: 0.8.1
IPython: 5.0.0
sphinx: None
patsy: None
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None

**Comment by TomAugspurger** [comment]
We'd need to decide what to do if `len(series)` isn't equal to `len(xticks)`, I assume matplotlib will just throw and error, which is probably fine.

Mind stepping through `tools/plotting.py` to see what's going on?

**Comment by Evfro** [comment]
At first glance it doesn't look very straightforward. I'll look more closely a bit later.
