### ISSUE TITLE
Change DataFrame to_sql's first parameter to something more descriptive

### ISSUE THREAD

**Issue by jaradc** [pandas-dev/pandas#14129]
This is a high-level suggestion.

`DataFrame.to_sql(name, con, ...)`

It's not intuitive if `name` means name of database or name of table in database.

I think something like `table_name` or `tablename` would better explain what `name` is.

Yes, I know I can Google it every time and eventually after Googling it so many times I'll eventually learn it... but isn't the point to make it intuitive and easy-to-use? Others might not have this same minor issue.

**Comment by jreback** [comment]
I suppose you could, though this would mean a deprecation cycle for not much gain IMHO. by-definition a connection object is against a server/database, so this is clear.

**Comment by mroeschke** [comment]
Thanks for the suggestion but it appears that there isn't much appetite in this change. Going to close but happy to reopen if there is more community interest
