### ISSUE TITLE
Possibility to draw random markers in line plots

### ISSUE THREAD

**Issue by ckaldemeyer** [pandas-dev/pandas#14128]
#### Code Sample, a copy-pastable example if possible

I often have dataframes with many obervations and want to have a quick glance at the data using a line plot.

The problem is that the colors of the colormap are either repeated over X observations or hard to distinguish e.g. in case of sequential colormaps.

So my idea was to add random markers to the line plot which is where I got stuck.

Here's an example with one markerstyle:

```
# -*- coding: utf-8 -*-
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# dataframe with random data
df = pd.DataFrame(np.random.rand(10, 8))

# plot
df.plot(kind='line', marker='d')
plt.show()
```

So far, this only seems to be possible with additional matplotlib code as shown in my related question on stackoverflow:

http://stackoverflow.com/questions/39246115/pandas-dataframe-plot-show-random-markers#39247062
#### Expected Output

It would be nice if one could draw random markers in line plots via a flag, e. g.:

```
df.plot(kind='line', random_markers=True)
```
#### output of `pd.show_versions()`

commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-34-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8

pandas: 0.18.0
nose: 1.3.7
pip: 8.1.2
setuptools: 20.7.0
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.17.0
statsmodels: None
xarray: None
IPython: 4.1.2
sphinx: None
patsy: 0.4.0
dateutil: 2.5.1
pytz: 2016.2
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.39.0

**Comment by mroeschke** [comment]
Thanks for the suggestion but appears there hasn't been much traction or community interest in this feature so closing
