### ISSUE TITLE
NaT treatment in pandas groupby/nunique

### ISSUE THREAD

**Issue by pkch** [pandas-dev/pandas#14149]
#### Code Sample, a copy-pastable example if possible

Calling nunique on a column that contains NaT results in this FutureWarning from numpy:

```
 python35\lib\site-packages\pandas\core\groupby.py:2854
 FutureWarning: In the future, NAT != NAT will be True rather than False.
  inc = np.r_[1, val[1:] != val[:-1]]
```

It might be worth updating the relevant lines in a way that does not depend on != comparison of NaT, otherwise `nunique()` behavior will unexpectedly change when [numpy is upgraded to 1.13](http://docs.scipy.org/doc/numpy-dev/release.html#future-changes).
## INSTALLED VERSIONS

commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.2
setuptools: 26.1.1
Cython: 0.24.1
numpy: 1.11.0
scipy: 0.17.0
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: None
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.6.1
blosc: None
bottleneck: None
tables: 3.2.3
numexpr: 2.5.2
matplotlib: 1.5.1
openpyxl: 2.3.5
xlrd: None
xlwt: None
xlsxwriter: None
lxml: 3.6.4
bs4: None
html5lib: None
httplib2: 0.9.2
apiclient: 1.5.0
sqlalchemy: 1.0.14
pymysql: None
psycopg2: 2.6.2 (dt dec pq3 ext lo64)
jinja2: 2.8
boto: None
pandas_datareader: None

**Comment by jreback** [comment]
can you show a complete code example

**Comment by pkch** [comment]
```
df = pd.DataFrame({'a': [None, None], 'b': [1, 1]})
df.a = pd.to_datetime(df.a)
df.groupby('b').a.nunique(dropna=False).value_counts(dropna=False)
```

**Comment by jreback** [comment]
ok, so need to add a:

```
if needs_id_conversion(vals):
    val = vals.view('i8')
```

in groupby.nunique I think

**Comment by mroeschke** [comment]
This looks to not raise a warning anymore on master so I think we can close this issue

```
In [1]: df = pd.DataFrame({'a': [None, None], 'b': [1, 1]})
   ...: df.a = pd.to_datetime(df.a)
   ...: df.groupby('b').a.nunique(dropna=False).value_counts(dropna=False)
Out[1]:
1    1
Name: a, dtype: int64

In [2]: np.__version__
Out[2]: '1.20.1'

In [3]: pd.__version__
Out[3]: '1.3.0.dev0+1485.g6abb567cb1'
```
