### ISSUE TITLE
DOC: clarify dangers of fast apply in GroupBy apply docs

### ISSUE THREAD

**Issue by tambu-j** [pandas-dev/pandas#14180]
I recently had to solve an issue where some code was behaving inconsistently. Effectively, I tracked this issue to a function that was being passed to apply which occasionally, under certain circumstances, mutated the input for a group - and not always the first group. Because fast_apply only checks the first group this meant that the output was unreliable. It didn't take me long to work out, but from a user's point of view it would be good to extend the docs so that they clarify that mutating the input is either not a good idea, or it should occur consistently for each group (or at the very least always for the first group).

**Comment by jreback** [comment]
mutation is simply not a good idea on groupby
would appreciate a big doc warning (maybe sub section if u have a smallish example)

fast apply is an impl detail

**Comment by bashtage** [comment]
I think #13543 might be related, although the opposite problem (fast works as expected, slow does not)

**Comment by jbrockmendel** [comment]
fast_apply has been removed; closing
