### ISSUE TITLE
Add left_by/right_by and left_index/right_index to merge_asof()

### ISSUE THREAD

**Issue by chrisaycock** [pandas-dev/pandas#14253]
The current `merge_asof()` has only one parameter for `by`, assuming that both DataFrames have the same column name. It does have `left_on` and `right_on`, so perhaps something similar for `by` would be helpful.

Also, there is no `left_index` or `right_index` parameter in `merge_asof()`. Adding these might be helpful too.

For example:

```
pd.merge_asof(df1, df2,
              left_index=True, right_on='timestamp',
              left_by='Ticker', right_by='ticker')
```

**Comment by jreback** [comment]
@chrisaycock can you show an example where they are meaningful?

I did have them initially, but I couldn't come up with a good use case. In that the merge-asof is quite restricted in what you are doing with it and the API area pretty much covers it.

**Comment by chrisaycock** [comment]
The example I'm working through now is that my left table is indexed by timestamp and has a column called 'Ticker', whereas my right table has columns called 'timestamp' and 'ticker'. These are passed in, so I don't have control over what I get. I have to reshape the tables temporarily before calling `merge_asof()`, and then I have to undo the reshaping in the returned result.

**Comment by jreback** [comment]
@chrisaycock ahh I c. ok, can you update the topsection with an example of using that API then?

**Comment by chrisaycock** [comment]
@jreback Done.
