### ISSUE TITLE
BUG: Frequency not set for empty Series

### ISSUE THREAD

**Issue by jluttine** [pandas-dev/pandas#14320]
Pandas doesn't set frequency properly for empty series. This is probably related to #14313.
#### A small, complete example of the issue

It works for non-empty series:

``` python
>>> pd.Series(index=pd.DatetimeIndex(["2016-09-29 11:00"]), data=[3]).asfreq('H').index
DatetimeIndex(['2016-09-29 11:00:00'], dtype='datetime64[ns]', freq='H')
```

But for empty series, `freq` is `None`:

``` python
>>> pd.Series(index=pd.DatetimeIndex([]), data=[]).asfreq('H').index
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
```
#### Expected Output

I expected the following output:

``` python
>>> pd.Series(index=pd.DatetimeIndex([]), data=[]).asfreq('H').index
DatetimeIndex([], dtype='datetime64[ns]', freq='H')
```
#### Output of `pd.show_versions()`

<details>
## INSTALLED VERSIONS

commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.7.5-gnu-1
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.19.0rc1
nose: 1.3.6
pip: 8.1.2
setuptools: 27.3.0
Cython: 0.24.1
numpy: 1.11.1
scipy: 0.18.1
statsmodels: None
xarray: None
IPython: 5.0.0
sphinx: 1.4.5
patsy: None
dateutil: 2.5.3
pytz: 2016.6.1
blosc: None
bottleneck: None
tables: 3.2.3.1
numexpr: 2.6.1
matplotlib: 1.5.2
openpyxl: None
xlrd: 1.0.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.5.1
html5lib: None
httplib2: 0.9.2
apiclient: 1.5.1
sqlalchemy: 1.0.15
pymysql: None
psycopg2: 2.6.2 (dt dec pq3 ext lo64)
jinja2: 2.8
boto: None
pandas_datareader: None
</details>

**Comment by jreback** [comment]
https://github.com/pydata/pandas/blob/master/pandas/tseries/resample.py#L1347

should do: ``obj._shallow_copy(freq=to_offset(freq))``

**Comment by sahildua2305** [comment]
This will require defining `_shallow_copy` for `Series` right? Because as of now it gives error -
```
AttributeError: 'Series' object has no attribute '_shallow_copy'
```

**Comment by jreback** [comment]
no this is for an Index

**Comment by sahildua2305** [comment]
I tried `obj._shallow_copy(freq=to_offset(freq))` but it gets the above mentioned error.

**Comment by jreback** [comment]
create a copy of the obj then assign the series with a shallow copy

**Comment by sahildua2305** [comment]
I got this one! I will write tests to verify the expected behavior and create a PR. Thanks 😄
