### ISSUE TITLE
CLN: different way of doing nogil blocks in templates?

### ISSUE THREAD

**Issue by chris-b1** [pandas-dev/pandas#14341]
Right now we have blocks in the `pxi.in` files that look this, which are somewhat error prone to edit/write.

``` python
{{nogil_str}}
{{tab}}prev = arr[0]
{{tab}}for i in range(1, n):
{{tab}}    cur = arr[i]
{{tab}}    if timelike and cur == iNaT:
{{tab}}        is_monotonic_inc = 0
{{tab}}        is_monotonic_dec = 0
```

This is the best alternative I could come up with, where `maybe_nogil` is a formatting function; `tempita` uses `|` as a pipe operator.  It's somewhat annoying to look at in that the whole block gets syntax highlighted as a string, but may be cleaner and plays nicer with an editor than what's being done now - thoughts? cc @sinhrks 

``` python
{{'''
prev = arr[0]
for i in range(1, n):
    cur = arr[i]
    if timelike and cur == iNaT:
        is_monotonic_inc = 0
        is_monotonic_dec = 0
''' | maybe_nogil }}}



```

**Comment by sinhrks** [comment]
You're right, it looks clearer.

**Comment by shoyer** [comment]
Another option is to replace `{{nogil_str}}` with some dummy block, e.g., `if True:`, that the compiler will optimize out. Or we might not even need anything at all -- I think Python accepts mismatched indentation.

**Comment by chris-b1** [comment]
Oh, that's much nicer, I forgot you could over-indent like that.

**Comment by shoyer** [comment]
Over indentation doesn't always work:
```
a = 1
    b = 2
c = 3
```
```
  File "<ipython-input-82-d0b24758f554>", line 2
    b = 2
    ^
IndentationError: unexpected indent
```

**Comment by chris-b1** [comment]
OK, my test case was too simple!  I think the `if True:` block idea will work nicely.

**Comment by jbrockmendel** [comment]
Templating has mostly been replaced with fused types.  Is this issue closeable?

**Comment by WillAyd** [comment]
I think if anything we had already been using `if True:` to cover this. Closing but if anyone feels it needs to be readressed feel free to reopen
