### ISSUE TITLE
BUG: clipboard functions windows 10 py3.5

### ISSUE THREAD

**Issue by chris-b1** [pandas-dev/pandas#14362]
This seems to work ok in the current version of pyperclip, but is broken in our vendored version, so likely just need to update.

https://github.com/asweigart/pyperclip
https://github.com/asweigart/pyperclip/pull/41

```
# Your code here
In [1]: df = pd.DataFrame(np.random.randn(10, 2))

In [2]: df.to_clipboard()
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-1f8b11f0ff98> in <module>()
----> 1 df.to_clipboard()

c:\users\chris\documents\python-dev\pandas\pandas\core\generic.py in to_clipboard(self, excel, sep, **kwargs)
   1236         """
   1237         from pandas.io import clipboard
-> 1238         clipboard.to_clipboard(self, excel=excel, sep=sep, **kwargs)
   1239 
   1240     def to_xarray(self):

c:\users\chris\documents\python-dev\pandas\pandas\io\clipboard.py in to_clipboard(obj, excel, sep, **kwargs)
     96     else:
     97         objstr = str(obj)
---> 98     clipboard_set(objstr)

c:\users\chris\documents\python-dev\pandas\pandas\util\clipboard.py in _copyWindows(text)
     83                                  len(text.encode('utf-16-le')) + 2)
     84     pchData = d.kernel32.GlobalLock(hCd)
---> 85     ctypes.cdll.msvcrt.wcscpy(ctypes.c_wchar_p(pchData), text)
     86     d.kernel32.GlobalUnlock(hCd)
     87     d.user32.SetClipboardData(CF_UNICODETEXT, hCd)

OSError: exception: access violation writing 0x0000000000000000

In [4]: pd.read_clipboard()
<segfault>
```
#### Output of `pd.show_versions()`

<details>
# Paste the output here
## INSTALLED VERSIONS

commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.19.0+5.g855357b
nose: 1.3.7
pip: 8.1.2
setuptools: 23.0.0
Cython: 0.24.1
numpy: 1.11.1
scipy: 0.18.0
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.3.1
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: 1.0.0
tables: None
numexpr: 2.6.0
matplotlib: 1.5.3
openpyxl: None
xlrd: 1.0.0
xlwt: None
xlsxwriter: 0.9.3
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None
</details>

**Comment by gfyoung** [comment]
FWIW, I'm getting this exception too as far back as `0.18.1`.
