### ISSUE TITLE
Python pandas  use method of merge， return empty DataFrame

### ISSUE THREAD

**Issue by miaoxu9999** [pandas-dev/pandas#14385]
#### I use pd.merge to link two excel, but it returns empty dataFrame

```python
# 
  df1 = pd.read_excel('gz.xlsx')
  df2 = pd.read_excel('dyml.xlsx')
  pd.merge(df1, df2, on = 'name')


```

**Comment by bkandel** [comment]
Without a reproducible example it's hard to tell what's going on here. Once the dataframes are read in from Excel they are normal dataframes -- the fact that they originated from an Excel workbook doesn't matter. If you could post the content of the two dataframes and what the output of the `merge` is it would help debugging.

**Comment by miaoxu9999** [comment]
[c.xlsx](https://github.com/pydata/pandas/files/518737/c.xlsx)
[t.xlsx](https://github.com/pydata/pandas/files/518739/t.xlsx)

@bkandel  thanks for your reply ,below are my data .could you help me solve the problem?

**Comment by GeraintDuck** [comment]
The names column in c.xlsx has extra white-space surrounding the text. 

Try something like:

    df1 = pd.read_excel('c.xlsx')
    df1['name'] = df1['name'].str.strip()
    df2 = pd.read_excel('t.xlsx')
    df2['name'] = df2['name'].str.strip()
    df = pd.merge(df1, df2, on='name')

Note that the default merge is an inner join too.

**Comment by jorisvandenbossche** [comment]
@miaoxu9999 The github issues are meant for reporting issues that possibly are bugs, not for general questions and answers. For this, StackOverflow or the mailing list is a better place to ask (but of course, the line between both is not always clear)
