### ISSUE TITLE
Add decimal option to read_excel

### ISSUE THREAD

**Issue by bbirand** [pandas-dev/pandas#14403]
The `pd.read_csv()` function has a `decimal` option, which allows it to parse European dates very easily:

```
pd.read_csv("afile.csv", decimal=',')
```

This option is not present in `pd.read_excel()`, but it could also be very useful there.

It would be even more useful if this option was a list of characters to interpret as decimal delimiters, instead of a single character.

**Comment by jorisvandenbossche** [comment]
As far as I know excel, this shouldn't matter? As excel stores values, and how it is represented in what you see in the excel file depends on your language settings of excel.

**Comment by bbirand** [comment]
@jorisvandenbossche I think this might be the case if the cells are declares as "Number" but in our case, our database queries are returned with the cell type "General", and this becomes an issue then.

**Comment by jorisvandenbossche** [comment]
How do they get read in? As strings?

**Comment by bbirand** [comment]
Yes, they have the dtype "object", and they appear as strings.

**Comment by sven337** [comment]
This is something I am certainly interested in, as manually fixing up the data after parsing is annoying, and it is quite common to have that problem whenever you use a mix of US and European Excel files.

**Comment by WillAyd** [comment]
Thanks for the feedback @sven337 . Reopening for discussion since there is some interest, though I'd still vote against support something like this. Let's see what others think

**Comment by sven337** [comment]
I'm no pandas developer, but I don't really understand why the CSV reader would have the ability to interpret strings as decimal with a configurable decimal separator, while the Excel reader would have to only use a hardcoded "." decimal separator when reading strings.
The fact is that many Excel sheets have numbers of cell type "standard", and that works just fine on most people's computers (until you load them up with a different locale setting, which I do all of the time). Conceptually if "standard" is recorded as a string, but Pandas has the ability to interpret these as numbers, then this is the same thing as reading a CSV: you need to be able to specify the decimal separator, because all data doesn't use dot.

**Comment by WillAyd** [comment]
> I'm no pandas developer, but I don't really understand why the CSV reader would have the ability to interpret strings as decimal with a configurable decimal separator, while the Excel reader would have to only use a hardcoded "." decimal separator when reading strings.

Because a CSV format doesn't have offer column metadata nor locale insights that are available to you with an Excel file, so you have to guess.

**Comment by MortenHannemose** [comment]
> The fact is that many Excel sheets have numbers of cell type "standard", and that works just fine on most people's computers
Exactly this! Many documents are just stored as "standard" cell type, which causes no problems when the locale is similar. I know experienced several programs/websites that export the excel file in this way.

**Comment by egpbos** [comment]
It is indeed very common to find Excel files with "standard" cell types containing numbers. It's not always feasible to get these Excel data sources to use "proper" metadata. It would be really useful to have this, so you don't have to use a bunch of converters.

**Comment by maufadel** [comment]
I would also appreciate having this feature. Most excel files have "standard" or "general" for cell types with numbers, and when these numbers come from European locales that use a comma for decimal numbers, it's quite a headache. We can of course convert it manually as end users, but why can't we have the same feature as for CSVs?

**Comment by higoramf** [comment]
Hello, I'm from Brazil and we've had the same problem, I noticed that pandas removed the argument DECIMAL for pd.read_excel(), befeore it was possible but now again come up this issues. I found the follow solution

file = ['coloumn'] = file['coloumn'].str.replace(',', '.').astype('float')

**Comment by EwoutH** [comment]
Just chipping in that I would love having a option to define a separator and decimal separator just like with `.to_csv()` (i.e. `sep=';',decimal=','`)!

**Comment by oricou** [comment]
So at the end we had it in Pandas 1.0.3 and now it has been removed!

I can understant americans don't give a shit of this issue and declare Excel files should be perfect and use Number since it works with dot as decimal separator even if the Excel file does not use Number type. In Europe it is an issue. Open data provides Excel files made by the administration. These files are not perfect and guess what, sometime they are not perfect on purpose.  Now the question is can Pandas help us ? It did but now it doesn't want anymore.

"Be conservative in what you do, be liberal in what you accept from others."  Jon Postel

**Comment by jreback** [comment]
@oricou this is an open issue an you can contribute by opening a PR

**Comment by moijn001** [comment]
Yes, this feature is much needed from my side as well! Making a custom little str.replace(',', '.'). function in every file seems like a suboptimal solution. If anyone takes on the task you'll have my eternal gratitude. Working with European energy market data is a hassle when there's no consensus on decimal-point format.

**Comment by lithomas1** [comment]
If someone provides a simple test file, I could take this up. It seems like all that is needed to fix this is to pass-through the decimal kwarg to the textparser(which is also what is used in read_csv).

**Comment by moijn001** [comment]
> 
> 
> If someone provides a simple and minimal test file, and the expected output, I could take this up. It seems like all that is needed to fix this is to pass-through the decimal kwarg to the textparser(which is also what is used in read_csv).
[example_data_for_pandas.xlsx](https://github.com/pandas-dev/pandas/files/7449068/example_data_for_pandas.xlsx)

Absolutely! Here's a small excel sheet and a python code to load it: https://drive.google.com/drive/folders/1efN1ULki5EdiQPjhjol2N_85_3BJEufc?usp=sharing

**Comment by lithomas1** [comment]
This is what I get after adding in the decimal option. Does this look correct?
```
>>> pd.read_excel("pandas/tests/io/data/excel/test_decimal.xlsx", skiprows=2, decimal=",")
          Date    Hours    SYS    SE1      SE2      SE3    SE4
0   01-01-2021  00 - 01  24.74  24.95   4.9500  224.950  24.50
1   01-01-2021  01 - 02  24.28  24.20  24.3435   24.335  24.00
2   01-01-2021  02 - 03  23.90  23.98  23.9800   23.980  23.98
3   01-01-2021  03 - 04  23.61  23.72  23.7200   23.720  23.72
4   01-01-2021  04 - 05  23.66  23.73  23.7300   23.730  23.73
..         ...      ...    ...    ...      ...      ...    ...
76  04-01-2021  04 - 05  24.25  24.58  24.5800   24.580  24.58
77  04-01-2021  05 - 06  25.55  25.84  25.8400   25.840  25.84
78  04-01-2021  06 - 07  27.46  28.21  28.2100   28.210  28.21
79  04-01-2021  07 - 08  31.22  30.85  30.8500   30.850  49.76
80  04-01-2021  08 - 09  45.95  49.20  49.2000   49.200  54.42

[81 rows x 7 columns]
```

**Comment by oricou** [comment]
It seems fine. Could you do `df[['SYS', 'SE1', 'SE2', "SE3', "SE4']].sum()` to be sure.
Thanks a lot for this patch.

**Comment by moijn001** [comment]
Yes! Perfect Thomas! That's awesome!     all numbers are read correctly. I have compared to the original.

**Comment by moijn001** [comment]
> 
> 
> It seems fine. Could you do `df[['SYS', 'SE1', 'SE2', "SE3', "SE4']].sum()` to be sure. Thanks a lot for this patch.

Here's the sum of values I get in excell for each column:
`
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/anton/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/anton/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



SYS | SE1 | SE2 | SE3 | SE4
-- | -- | -- | -- | --
2244.690 | 2259.970 | 2240.114 | 2680.105 | 2839.500



</body>

</html>
`

**Comment by EwoutH** [comment]
Thanks for this effort! Could you test if your code works on the file below?

[Pandas-seperator-test.xlsx](https://github.com/pandas-dev/pandas/files/7459805/Pandas-seperator-test.xlsx)

**Comment by lithomas1** [comment]
@EwoutH Is there another kwarg(such as ``sep`` that I need to passs in)? Reading this with and without decimal gives the same result for me.

**Comment by lithomas1** [comment]
@moijn001 
```
>>> pd.read_excel("C:\\Users\\liwende\\Downloads\\example_data_for_pandas.xlsx", decimal=",", skiprows=2).sum()
Date     01-01-202101-01-202101-01-202101-01-202101-01-...
Hours    00 - 0101 - 0202 - 0303 - 0404 - 0505 - 0606 -...
SYS                                                2244.69
SE1                                                2259.97
SE2                                              2240.1135
SE3                                               2680.105
SE4                                                 2839.5
dtype: object
```
Seems correct.
