### ISSUE TITLE
Behavior change in Index.equals from 0.18.0 to 0.19.0 -- intentional?

### ISSUE THREAD

**Issue by njsmith** [pandas-dev/pandas#14411]
Traditionally, we have:

``` python
In [3]: pandas.__version__
Out[3]: '0.18.0'

In [4]: pandas.Index([1, 2]).equals([1, 2])
Out[4]: True
```

But this changed

``` python
In [4]: pandas.__version__
Out[4]: '0.19.0'

In [5]: pandas.Index([1, 2]).equals([1, 2])
Out[5]: False
```

Looks like it might not be intentional so FYI.

(Noticed because it broke a few tests in the patsy test suite.)

**Comment by jorisvandenbossche** [comment]
Well, we had some discussion about this, see https://github.com/pandas-dev/pandas/pull/13986#r74693208, but I think I lost the discussion for allowing this. 
Basically, to be equal to an index, you now have to be an index yourself (so a list can no longer be equal). But I see we didn't really explain this in the whatsnew docs.

**Comment by njsmith** [comment]
I can see the argument for the new behavior, but it was a backwards incompatible change with no deprecation, so wasn't sure what was going on.

I've already worked around it for patsy.
