### ISSUE TITLE
DEV: Update merge-pr.py script given repo rename

### ISSUE THREAD

**Issue by wesm** [pandas-dev/pandas#14439]
This is still pointing to pydata/pandas.git -- it is working fine presumably because of magic redirection

**Comment by gfyoung** [comment]
@wesm : IINM, we can also refactor this function <a href="https://github.com/pandas-dev/pandas/blob/7cad3f16bccd1d4702ef9d038b1ee0db33b9bb94/scripts/merge-py.py#L86">here</a> because we don't support 2.6 anymore?
