### ISSUE TITLE
Allow DataFrame.apply() to accept dict of funcs

### ISSUE THREAD

**Issue by mattayes** [pandas-dev/pandas#14464]
When using DataFrame.apply(), it would be helpful to be able to apply different functions to different columns. There's a nice workaround on [StackOverflow](http://stackoverflow.com/questions/26434123/pandas-apply-different-functions-to-different-columns):

``` python
import numpy as np
import pandas as pd

def multi_func(functions):
    def f(col):
        return functions[col.name](col)
    return f

df = pd.DataFrame(np.random.random((10, 2)), columns=['A', 'B'])
results = df.apply(multi_func({'A': np.mean, 'B': np.sum}))

results
A    0.401456
B    6.845529
dtype: float64
```

My guess is that the changes would be made in [pandas.core.frame.DataFrame](https://github.com/pandas-dev/pandas/blob/master/pandas/core/frame.py), potentially adding a new `_apply_X` method. Any thoughts/advice?

**Comment by jreback** [comment]
This is just a part of the API that ``.aggreate`` should do. see the original issue[here](https://github.com/pandas-dev/pandas/issues/1623). This should be consistent with the ``.groupby`` and ``.rolling``, ``.aggregate`` methods. Most of the machinery is already in place to do this. 

So I'll leave this open even those its a duplicate as it shows another usecase.

**Comment by mattayes** [comment]
Thanks @jreback!
