### ISSUE TITLE
RLS: v0.19.1

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#14474]
Been busy with other things last week, but next week I should have some more time for pandas and I could prepare for a 0.19.1 release (eg somewhere by the end of next week/beginning week after). Sounds OK?

Open issues/PRs: https://github.com/pandas-dev/pandas/milestones/0.19.1 
Some issues still that would be nice to get fixed next week before releasing.

@pandas-dev/pandas-core

**Comment by jorisvandenbossche** [comment]
We should also get the checks on PRs back working (currently only travis is working)

**Comment by jreback** [comment]
so appeyor looks to be building. but the status do not appear to be coming back to github. i flipped the webhook up and down, but not really sure why this is not reporting.

**Comment by jreback** [comment]
eg https://github.com/pandas-dev/pandas/pull/14481 just pushed by @jorisvandenbossche is building. may have to contact github to see how to fix this.

**Comment by jorisvandenbossche** [comment]
Will ask github about that (I already contacted them for the blocked PR issue, and it is since that is solved the appveyor status does not report)

**Comment by jreback** [comment]
ok, looks like appveyor is back on reporting status. I had to revoke / invoke the github access.

**Comment by jorisvandenbossche** [comment]
@jreback Thanks! the appveyor check is indeed back

**Comment by jorisvandenbossche** [comment]
Unless someone raises concerns or obstacles, I am planning to cut a 0.19.1 release this evening or tomorrow. Sounds fine? 
There is a 0.19.x branch with all relevant commits backported (this time it was not yet that useful to backport, as there only few commits that did not have to be included, but good test drive): https://github.com/pandas-dev/pandas/commits/0.19.x

The last PR I certainly want to get in is https://github.com/pandas-dev/pandas/pull/14545 and https://github.com/pandas-dev/pandas/pull/14567, but in its current form I think those are also fine to be merged.

**Comment by jreback** [comment]
sounds good @jorisvandenbossche 

as an FYI, pls update the release instructions with how you are doing the backporting (maybe new section)? 

could also think about a 0.19.2 bug fix release as well.

**Comment by jorisvandenbossche** [comment]
Release is tagged, docs and website updated, source dists on pypi (but still hidden), waiting until the conda-forge packages and wheels are built for sending the announcement

**Comment by jreback** [comment]
@jorisvandenbossche released thanks!
