### ISSUE TITLE
DataFrame Operations on Large Frames Seems To Crash Python Kernel on MacOS Yosemite At Random

### ISSUE THREAD

**Issue by jgoad** [pandas-dev/pandas#14471]
Apologies for not following the requested format, but there is no output for this error. Running the script from command line will occasionally execute without error, but often python will crash without error. This occurs with both python 3.5 and 2.7, and with pandas 0.18.1 and 0.19.0. 

The code came directly from a windows machine where it ran fine and now it does not run reliably on Mac... In one instance it happens when merging two large frame and in another it occurs when using groupby. 

I know this is extremely obscure but does anyone have any ideas?

**Comment by jorisvandenbossche** [comment]
Can you provide a reproducible example? (or one that does at least for you sometimes triggers the error?)

**Comment by jgoad** [comment]
Hey Joris. More than fair request. I will try to find time to create a random dataset that causes the error this week. Thanks!

**Comment by TomAugspurger** [comment]
Let us know if you can make a reproducible example.
