### ISSUE TITLE
CI: numpy dev started failing

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#14489]
https://travis-ci.org/pandas-dev/pandas/jobs/169382808

IIRC some issues w.r.t. int ** int. unrelated to this PR.

**Comment by jreback** [comment]
cc @shoyer

**Comment by gfyoung** [comment]
@jreback : The breaking PR is <a href="https://github.com/numpy/numpy/pull/8127">numpy/numpy #8127</a>.

**Comment by shoyer** [comment]
I think we should just fix the test. Negative integers to negative powers was already broken in previous versions of NumPy.

The other choice would be to coerce all arguments to floats before taking powers.
