### ISSUE TITLE
ERR: improve error message with unalignable label indexing

### ISSUE THREAD

**Issue by bluenote10** [pandas-dev/pandas#14491]
#### A small, complete example of the issue

Using a boolean index in a `pandas.Series` on a data frame with an string index fails with `Unalignable boolean Series key provided`:

``` python
import pandas as pd

# DF without string index
df = pd.DataFrame({"A": [0, 1, 2]})
df.loc[[True, True, True], :]               # works
df.loc[pd.Series([True, True, True]), :]    # works

# DF with string index
df = pd.DataFrame({"A": [0, 1, 2]}, index=["a", "b", "c"])
df.loc[[True, True, True], :]               # works
df.loc[pd.Series([True, True, True]), :]    # fails
```
#### Expected Output

Boolean indexing should work with a `pandas.Series` like it does with regular Python lists and boolean numpy arrays.
#### Output of `pd.show_versions()`

<details>
## INSTALLED VERSIONS

commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-98-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.18.1
nose: None
pip: 8.1.2
setuptools: 27.2.0
Cython: 0.24.1
numpy: 1.11.1
scipy: 0.18.0
statsmodels: None
xarray: None
IPython: 5.1.0
sphinx: None
patsy: None
dateutil: 2.5.3
pytz: 2016.6.1
blosc: None
bottleneck: 1.1.0
tables: None
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
boto: None
pandas_datareader: None
</details>

**Comment by jorisvandenbossche** [comment]
I think the error message is rather clear: "Unalignable boolean Series key provided" -> the index of the boolean series is not alignable with the index of the DataFrame you are trying to index. Lists or arrays don't have an index, so there is not an issue. If you want to ignore the index of the series, you can use `s.values` to index.

Not sure if this is documented somewhere thoroughly.

**Comment by bluenote10** [comment]
Understood, but then it is mainly the error message that is very confusing: A series of length 3 _is_ alignable intuitively with a length-3-dataframe, it is just not what Pandas considers alignable.

**Comment by jorisvandenbossche** [comment]
Ah yes, it is unalignable on the *labels* of the indices (although the length matches). That is what the term 'alignment' means in pandas-world. 
But we would maybe add in the error massage some more explanation.

**Comment by jreback** [comment]
ok will mark this for error message improvement @bluenote10 if you'd like to submit a PR.

I suppose you could mention that this is *label* alignment would be enough.
