### ISSUE TITLE
ENH: add np.nan* functions to map for groupby/rolling/resample aggregators

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#14518]
xref #14517 

[here](https://github.com/pandas-dev/pandas/blob/master/pandas/core/base.py#L275) we define mappings for numpy functions when they are used in aggregation functions, e.g. 

`df.groupby(...).apply(np.mean)` is mapped to `df.groupby(..).mean()`

these are much more performant when used this way and have more typical pandas semantics.

This issue is about adding the `np.nan*` functions (e.g. `np.nanmean`) and such.

The only thing tricky is that these must be conditionally added based on numpy version, and need testing! (currently tests for this type of mapping is spread across tests for groupby/rolling/resampling), so tests need to be added in various locations, with a possiblity of moving the common parts of this to a single location.

**Comment by wandersoncferreira** [comment]
@jreback I am willing to work on this problem. I will dig into the tests for this type of mappings shortly! Thanks

**Comment by VijayantSoni** [comment]
Hi @jreback , I think the [link](https://github.com/pandas-dev/pandas/blob/master/pandas/core/base.py#L275) you have added in issue description is no longer valid. If that's the case, can you please update it. I am trying to take this one up.
Thanks !

**Comment by chinmoysarangi** [comment]
Hi @jreback I am trying to work on this. Hope that's okay.

Thanks in advance! :)
Chinmoy.

**Comment by GaurangSharma44** [comment]
> Hi @jreback We are trying to work on this. Hope that's okay.
> 
> Thanks in advance! :)
> Chinmoy.

Take

**Comment by rhshadrach** [comment]
Closing due to #53974
