### ISSUE TITLE
Inconsistent error raising in indexing

### ISSUE THREAD

**Issue by cyrusmaher** [pandas-dev/pandas#14525]
#### A small, complete example of the issue

``` python
x = np.random.randn(2, 2)
y = pd.Series(range(2))
y.loc[range(2)] = x # succeeds
y.loc[:] = x # fails
```
#### Expected Output

Since we're assigning a 2D array to a 1D vector that is smaller than the raveled array, I would expect both assignments to fail.

**Comment by jreback** [comment]
sure if you want to jump into the deep end on indexing. yes this is prob not being checked.

**Comment by mroeschke** [comment]
Looks like both the previously successful assignment now fails. Could use a test.

```
In [118]: y.loc[range(2)] = x

ValueError: shape mismatch: value array of shape (2,2) could not be broadcast to indexing result of shape (2,)

In [119]: pd.__version__
Out[119]: '0.26.0.dev0+652.g30362ed82'
```
