### ISSUE TITLE
array_equivalent has disappeared from pandas.core.common in version 0.19, is this a mistake?

### ISSUE THREAD

**Issue by cleemesser** [pandas-dev/pandas#14555]
#### A small, complete example of the issue

```python
# Your code here
import pandas
import pandas.core.common as com
print com.array_equivalent
```

#### Expected Output
```python
# expect something like:
# <function array_equivalent at 0x000000000445A198>
# But I get
```
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-fc6fc07906df> in <module>()
----> 1 print com.array_equivalent

AttributeError: 'module' object has no attribute 'array_equivalent'
```
#### Output of ``pd.show_versions()``

<details>
# Paste the output here pd.show_versions() here
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.19.0
nose: 1.3.7
pip: 8.1.2
setuptools: 23.0.0
Cython: 0.24.1
numpy: 1.11.1
scipy: 0.17.1
statsmodels: 0.6.1
xarray: None
IPython: 4.1.2
sphinx: 1.3.5
patsy: 0.4.0
dateutil: 2.5.1
pytz: 2016.2
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.6.1
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.39.0
pandas_datareader: None
</details>

**Comment by jreback** [comment]
you can import it from ``pandas.types.missing``. its not really a public method. though @jorisvandenbossche and I did have this discussion.

**Comment by jorisvandenbossche** [comment]
Well, there are two aspect about this:

First, that we didn't add a deprecation warning for `array_equivalent` (as we did for the other functions in `pd.core.common`. This can be easily fixed.

Secondly about the fact that we currently don't plan to make this public (opposed to other functions in `pd.core.common`), and so it is not recommended to use it (although you can now import it from `pd.types.missing`, we don't guarantee this will keep working). 
But if it is regarded as useful functionality, we can consider to making it public.

**Comment by tomspur** [comment]
`array_equivalent` is already used in the [docs](http://pandas.pydata.org/pandas-docs/version/0.19.0/whatsnew.html#id77), which fails now with a traceback:
![image](https://cloud.githubusercontent.com/assets/303559/19924260/83691f66-a0eb-11e6-93fd-8574a7bce8dc.png)

**Comment by jorisvandenbossche** [comment]
@tomspur yes, we are aware of that (and I forgot to remove it from the docs for the 0.19.0 release)

**Comment by jorisvandenbossche** [comment]
This functionality should actually be rather available from numpy. But `np.array_equal` or `np.array_equiv` do not handle NaNs well. 
But I see that numpy 1.10 added a `equal_nan` keyword to `np.allclose`, so you can do:

```
>>> np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True)
True
```

https://docs.scipy.org/doc/numpy/reference/generated/numpy.allclose.html

We can probably recommend that as alternative

**Comment by jreback** [comment]
i don't think that handles object dtypes (with or w/o nans)

**Comment by jorisvandenbossche** [comment]
Ah, yes, and also no datetime64 values. OK, clearly not a full replacement

**Comment by jbrockmendel** [comment]
Is this actionable?  Closeable?

**Comment by jorisvandenbossche** [comment]
The `core.common` deprecations have already been removed before. And there has been no further discussion (or requests) to make `array_equivalent` public, so closing.
