### ISSUE TITLE
floats and ints missing as acceptable arguments for pandas.to_datetime in API Reference

### ISSUE THREAD

**Issue by PyDeq** [pandas-dev/pandas#14556]
#### A small, complete example of the issue

http://pandas.pydata.org/pandas-docs/version/0.19.0/generated/pandas.to_datetime.html says:
> **arg** : _string, datetime, list, tuple, 1-d array, Series_

While http://pandas.pydata.org/pandas-docs/version/0.19.0/timeseries.html#epoch-timestamps says that `int`s and `float`s are accepted as well.

#### Expected Output

`int` and `float` to be in the list

#### Output of ``pd.show_versions()``

```
pandas: 0.19.0
```

<details>

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-45-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.19.0
nose: None
pip: 7.1.0
setuptools: 18.0.1
Cython: None
numpy: 1.11.2
scipy: None
statsmodels: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.5.3
pytz: 2016.7
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
boto: None
pandas_datareader: None
```

</details>

**Comment by jorisvandenbossche** [comment]
That is correct. Pull request to update the docstring is very welcome!

**Comment by souravsingh** [comment]
I would like to work on the issue. Which files need updating?

**Comment by jorisvandenbossche** [comment]
you need to look for the source of the `to_datetime` function, this is located in tseries/tools (you can inspect the function to see that, just type `pd.to_datetime` in a console)

**Comment by patniharshit** [comment]
I would like to take this up. Just one doubt that I have to just update the doc string of to_datetime function to include integer and float as well ?

**Comment by jreback** [comment]
yep

**Comment by patniharshit** [comment]
First pull request in the world of open source. Guide me if anything is wrong.
