### ISSUE TITLE
CLN: move nanpercentile functionality to nanops

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#14562]
See comment https://github.com/pandas-dev/pandas/pull/14536#discussion_r85660330

Move the `_nanpercentile` functionality used in `quantile` in `internals.py` (https://github.com/pandas-dev/pandas/blob/52f31d470d779204e4c1388cdb56351c68332c3f/pandas/core/internals.py#L1319-L1393) to `nanops.py`.

**Comment by jorisvandenbossche** [comment]
Original comment of @jreback 

> I meant move ALL of this; the nanops do everything (based on dtype), are basically ufuncs per-dtype. Its ok for now if you want to merge (to fix the bug). But let's open a new issue to move this code. All of the rest of it is there (for other ops). We don't do very much inside the block managers, mainly just assemble blocks, actual calculations are pushed to other routines (numpy or pandas)

The reason that it is not just a copy paste, is that the current implementation makes use of the ``_try_coerce_args``, `_na_value` and `_try_coerce_result` methods of the `Block`, which you have to replace (but there is also functionality for that in nanops).

**Comment by jbrockmendel** [comment]
Closed by #24597
