### ISSUE TITLE
Missing marker when using `style=...`

### ISSUE THREAD

**Issue by tamasgal** [pandas-dev/pandas#14563]
There is an issue with the markers in the legend when working with the built-in matplotlib plot-wrapper in pandas. The problem is also in earlier versions and the only workaround I found is using matplotlib directly.

#### A small, complete example of the issue

```python
import pandas as pd
import matplotlib.pyplot as plt

df = pd.DataFrame({'A': [1, 2, 3, 4, 5, 6],
                   'B': [2, 4, 1, 3, 2, 4],
                   'C': [3, 3, 2, 6, 4, 2],
                   'X': [1, 2, 3, 4, 5, 6]})

fig, ax = plt.subplots()

for kind in 'ABC':
    df.plot('X', kind, label=kind, ax=ax, style='.')

plt.show()
```
![markers](https://cloud.githubusercontent.com/assets/1730350/19929894/f55dbd60-a105-11e6-980a-e105b841e518.png)

#### Expected Output
The markers in the legend are missing, except for the last label. It however works if I don't use `style=...`, but the default line-plot, like in this example:
```python
import pandas as pd
import matplotlib.pyplot as plt

df = pd.DataFrame({'A': [1, 2, 3, 4, 5, 6],
                   'B': [2, 4, 1, 3, 2, 4],
                   'C': [3, 3, 2, 6, 4, 2],
                   'X': [1, 2, 3, 4, 5, 6]})

fig, ax = plt.subplots()

for kind in 'ABC':
    df.plot('X', kind, label=kind, ax=ax)

plt.show()
```
![markers_with_lines](https://cloud.githubusercontent.com/assets/1730350/19929965/4d4cea46-a106-11e6-8b30-3d2f361186bb.png)

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Darwin
OS-release: 16.1.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.19.0
nose: None
pip: 8.1.2
setuptools: 25.2.0
Cython: 0.24.1
numpy: 1.11.2
scipy: 0.18.1
statsmodels: None
xarray: None
IPython: 5.1.0
sphinx: None
patsy: None
dateutil: 2.5.3
pytz: 2016.7
blosc: None
bottleneck: None
tables: 3.3.0
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None
</details>

**Comment by tamasgal** [comment]
I tracked down the problem to a single line in the sources.

This call is the final one, which sets the legends with the missing points except for the last ax when using `style='.'`
https://github.com/pandas-dev/pandas/blob/master/pandas/tools/plotting.py#L1293

If you change it from `ax.legend(handles, labels, loc='best', title=title)` to a plain `ax.legend()`, every marker is shown correctly in the legend. However, all optional settings are then of course skipped.

This line is the one which adds the legend handle in this case: https://github.com/pandas-dev/pandas/blob/master/pandas/tools/plotting.py#L1744

```self._add_legend_handle(newlines[0], label, index=i)```

However, I am still not able to figure out what is wrong there, the variable values look fine there too...

**Comment by charlesdong1991** [comment]
I cannot reproduce this on master anymore, seems to be fixed by #27808

![Screen Shot 2020-01-04 at 6 09 44 PM](https://user-images.githubusercontent.com/9269816/71769143-76afa100-2f1d-11ea-9136-db6a894e6390.png)

so i suggest to close this @TomAugspurger @jreback

**Comment by charlesdong1991** [comment]
![Screen Shot 2020-01-04 at 6 47 41 PM](https://user-images.githubusercontent.com/9269816/71769511-b6c55280-2f22-11ea-9a8b-d3cc6ba881c7.png)

work on master, previously uploaded wrong pic, sorry

**Comment by tamasgal** [comment]
Thanks!
