### ISSUE TITLE
pandas.Timestamp not in API Reference

### ISSUE THREAD

**Issue by PyDeq** [pandas-dev/pandas#14560]
#### A small, complete example of the issue

`pandas.Timestamp` cannot be found at http://pandas.pydata.org/pandas-docs/version/0.19.0/api.html

#### Expected Output

`pandas.Timestamp` to be there

#### Output of ``pd.show_versions()``

```
pandas: 0.19.0
```

<details>

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-45-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.19.0
nose: None
pip: 7.1.0
setuptools: 18.0.1
Cython: None
numpy: 1.11.2
scipy: None
statsmodels: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.5.3
pytz: 2016.7
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
boto: None
pandas_datareader: None
```

</details>

#### Additional info

1. It's a bit inconvenient for a newcomer to read [Time Series / Date functionality](http://pandas.pydata.org/pandas-docs/version/0.19.0/timeseries.html) over and over again in order to find out the API of the class.
2. I can get rid of messages such as `WARNING: po:obj reference target not found: pandas.Timestamp` coming from Sphinx.

**Comment by jorisvandenbossche** [comment]
See https://github.com/pandas-dev/pandas/issues/5218 for the reason.

What we could do is maybe at least add the methods that are additional compared to `datetim.datetime`.

Want to do a PR?

**Comment by PyDeq** [comment]
OH, I'd say that this is a duplicate of #5218 than :( I apologize for filing a duplicate. GitHub search engine does not find that if given "timestamp" and "documentation" keywords.

No promises but I may consider doing a PR in case of spare time, sure.
