### ISSUE TITLE
Reading bz2, zip, and xz-compressed files from URL fails

### ISSUE THREAD

**Issue by dhimmel** [pandas-dev/pandas#14570]
Previously, we've discussed reading tables form gzip-compressed URLs (see https://github.com/pandas-dev/pandas/issues/8685 and https://github.com/pandas-dev/pandas/pull/10649). This is an essential feature as data storage increasingly migrates to the cloud.

I now realize that the previous work only added support for gzipped URLs and not bz2, zip, or xz compression. However, [the documentation](http://pandas.pydata.org/pandas-docs/version/0.19.0/generated/pandas.read_csv.html) doesn't reflect this. See [this notebook](https://github.com/dhimmel/iris/blob/1418a9abe7608c3c1e821138c120e05aa8116ecb/pandas-bug.ipynb) to see the errors that are generated.

So :+1: for allowing URL locations for all supported compression formats.

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/issues/12688 is the base issue which needs fixing (there is a PR open on it, which is almost there). Once that is fixed almost everything else is just testing.

**Comment by dhimmel** [comment]
Thanks @jreback for the update. Excited for the pull request (#13340)!

**Comment by jreback** [comment]
that PR is a bit stalled - if u want to fix up and submit would be great
