### ISSUE TITLE
Floating point accuracy problems in `Timestamp.round` 

### ISSUE THREAD

**Issue by jeanmn** [pandas-dev/pandas#14572]
This is the same problem as described in  #14440 but with Timestamp, and the fix should be similar:

Probable source of error:
https://github.com/pandas-dev/pandas/blob/093aa8231eae92ff6cf7ef9564d62289b458aaff/pandas/tslib.pyx
(either L438 or L2804, I'm not sure which one is the cause, but both should probably be changed)

#### A small, complete example of the issue

```python
In [1] import pandas as pd
In [2]: ts=pd.Timestamp('2016-03-06 18:43:45.950000')
In [3]: ts.floor('10L')
Out [3]: Timestamp('2016-03-06 18:43:45.950000128')  
```

#### Expected Output

Timestamp('2016-03-06 18:43:45.950000')  

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: 093aa8231eae92ff6cf7ef9564d62289b458aaff
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.16.0-46-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.19.0+63.g093aa82
nose: 1.3.7
pip: 9.0.0
setuptools: 28.7.1
Cython: 0.25.1
numpy: 1.11.2
scipy: None
statsmodels: None
xarray: None
IPython: 5.1.0
sphinx: None
patsy: None
dateutil: 2.5.3
pytz: 2016.7
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
boto: None
pandas_datareader: None

**Comment by jreback** [comment]
duplicate

**Comment by jeanmn** [comment]
@jreback Issue link? I was on the verge of submitting a pull request to fix this

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/issues/14440 as u indicated

pr are welcome for this (it's an issue duplicate)

**Comment by jeanmn** [comment]
@jreback I see, thank you for the clarification.
I just wanted to make clear that this is a _similar issue but at a different location_ in the code due to duplication of internal rounding logic. I wouldn't be surprised if the same error is found in more locations.
FYI: The current affected classes (so far) are Timestamp, Timedelta and DatetimeIndex
