### ISSUE TITLE
ERR: tz_localize ambiguous ='infer'  

### ISSUE THREAD

**Issue by gwuillou** [pandas-dev/pandas#14585]
Hello, 

a problem concerning  DST with change time. My df has a index  for the year 2013 each 15 minutes. 

```python
df.index.tz_localize('Europe/Zurich',ambiguous = 'infer')
```
output:
 AmbiguousTimeError: 2013-10-27 02:00:00

The input DateTimeindex is:
...
              '2013-10-27 01:30:00', '2013-10-27 01:45:00',
              '2013-10-27 02:00:00', '2013-10-27 02:15:00',
               '2013-10-27 02:30:00', '2013-10-27 02:45:00',
               '2013-10-27 03:00:00', '2013-10-27 02:15:00',
               '2013-10-27 02:30:00', '2013-10-27 02:45:00',
               '2013-10-27 03:00:00', '2013-10-27 03:15:00',
               '2013-10-27 03:30:00', '2013-10-27 03:45:00',
...
 
I would like an output DateTimeindex like:
output:
...
               '2013-10-27 01:30:00+02:00', '2013-10-27 01:45:00+02:00',
               '2013-10-27 02:00:00+02:00', '2013-10-27 02:15:00+02:00',
               '2013-10-27 02:30:00+02:00', '2013-10-27 02:45:00+02:00',                   
               '2013-10-27 03:00:00+02:00', '2013-10-27 02:15:00+01:00',
               '2013-10-27 02:30:00+01:00', '2013-10-27 02:45:00+01:00', 
               '2013-10-27 03:00:00+01:00', '2013-10-27 03:15:00+01:00',
               '2013-10-27 03:30:00+01:00', '2013-10-27 03:45:00+01:00',
...

Thank you

```python
pd.show_versions()
```
<details>
output:
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Darwin
OS-release: 15.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: fr_CH.UTF-8
LOCALE: fr_CH.UTF-8

pandas: 0.19.1
nose: 1.3.7
pip: 8.1.2
setuptools: 21.2.1
Cython: None
numpy: 1.11.2
scipy: 0.17.1
statsmodels: None
xarray: None
IPython: 4.2.0
sphinx: None
patsy: None
dateutil: 2.5.3
pytz: 2016.7
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.1
openpyxl: None
xlrd: 1.0.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None
</details>

**Comment by jorisvandenbossche** [comment]
@gwuillou Can you provide a reproducible example that show the problem?

As I cannot reproduce it:

```
In [48]: idx = pd.date_range('2013-10-27 01:00', '2013-10-27 04:00', freq='15min', tz='Europe/Zurich')

In [50]: idx_naive = idx.tz_localize(None)

In [51]: idx_naive
Out[51]: 
DatetimeIndex(['2013-10-27 01:00:00', '2013-10-27 01:15:00',
               '2013-10-27 01:30:00', '2013-10-27 01:45:00',
               '2013-10-27 02:00:00', '2013-10-27 02:15:00',
               '2013-10-27 02:30:00', '2013-10-27 02:45:00',
               '2013-10-27 02:00:00', '2013-10-27 02:15:00',
               '2013-10-27 02:30:00', '2013-10-27 02:45:00',
               '2013-10-27 03:00:00', '2013-10-27 03:15:00',
               '2013-10-27 03:30:00', '2013-10-27 03:45:00',
               '2013-10-27 04:00:00'],
              dtype='datetime64[ns]', freq='15T')

In [52]: idx_naive.tz_localize('Europe/Zurich')
...
AmbiguousTimeError: Cannot infer dst time from Timestamp('2013-10-27 02:00:00'), try using the 'ambiguous' argument

In [53]: idx_naive.tz_localize('Europe/Zurich', ambiguous='infer')
Out[53]: 
DatetimeIndex(['2013-10-27 01:00:00+02:00', '2013-10-27 01:15:00+02:00',
               '2013-10-27 01:30:00+02:00', '2013-10-27 01:45:00+02:00',
               '2013-10-27 02:00:00+02:00', '2013-10-27 02:15:00+02:00',
               '2013-10-27 02:30:00+02:00', '2013-10-27 02:45:00+02:00',
               '2013-10-27 02:00:00+01:00', '2013-10-27 02:15:00+01:00',
               '2013-10-27 02:30:00+01:00', '2013-10-27 02:45:00+01:00',
               '2013-10-27 03:00:00+01:00', '2013-10-27 03:15:00+01:00',
               '2013-10-27 03:30:00+01:00', '2013-10-27 03:45:00+01:00',
               '2013-10-27 04:00:00+01:00'],
              dtype='datetime64[ns, Europe/Zurich]', freq='15T')
```

**Comment by rockg** [comment]
The issue here is that the 02:00 is not repeated, instead the repetition starts at 02:15 in the original example and continues to 02:30, 02:45, 03:00.  The repeated intervals should be 02:00, 02:15, 02:30, and 02:45 as you see in @jorisvandenbossche example.  It's almost as if it is 15-minute period ending times so I think those need to be adjusted back before any inference would work.

**Comment by gwuillou** [comment]
Yep , it is a complex problem! I am working with energy data with a frequency of 15 minutes. By definition in the energy field, the value associated to the timestamp is the mean value of the 15 minutes before the timestamp. It is why I have 03:00 which is repeated and not 02:00. If you can do something it will be great, but I can live with this problem.

Thank you for your answers
