### ISSUE TITLE
PERF: asv for select_dtypes

### ISSUE THREAD

**Issue by simonm3** [pandas-dev/pandas#14588]
Why is select_dtypes so slow?

`%timeit [col for col in df.columns if np.issubdtype(df[col].dtype, np.number)]`
453 microsecs per loop

`%timeit df.select_dtypes(include=[np.number])`
4.58 secs per loop

**Comment by jreback** [comment]
you would have to show a full example and pd.show_versions as the instructions indicate

**Comment by simonm3** [comment]
`df = pd.DataFrame(np.random.randn(100000, 4), columns=list('ABCD'))
%timeit [col for col in df.columns if np.issubdtype(df[col].dtype, np.number)]`

The slowest run took 13.72 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 35.5 µs per loop

`%timeit df.select_dtypes(include=[np.number])`

100 loops, best of 3: 3.41 ms per loop

#######################################################

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.19.0
nose: 1.3.7
pip: 8.1.2
setuptools: 28.7.1
Cython: 0.24
numpy: 1.11.2
scipy: 0.17.1
statsmodels: 0.8.0rc1
xarray: None
IPython: 4.2.0
sphinx: 1.3.1
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.7
blosc: None
bottleneck: 1.1.0
tables: 3.2.2
numexpr: 2.6.0
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.2
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.40.0
pandas_datareader: None

**Comment by TomAugspurger** [comment]
@simonm3 You might want to take a look at the definition in https://github.com/pandas-dev/pandas/blob/2e77536bdf90ef20fefd4eab751447918e07668f/pandas/core/frame.py maybe do some profiling to see where the time is spent.

Before you do any profiling / more benchmarking, make sure the results are equivalent. For example, `select_dtypes` also has an `exclude` argument that your version doesn't accept.

**Comment by jreback** [comment]
```
In [7]: %timeit df.select_dtypes(include=[np.number])
1000 loops, best of 3: 1.66 ms per loop

In [8]: %timeit df.select_dtypes(include=[np.float])
1000 loops, best of 3: 1.66 ms per loop

In [9]: %timeit df.select_dtypes(include=['float'])
1000 loops, best of 3: 1.7 ms per loop

In [10]: %timeit df.select_dtypes(include=['object'])
1000 loops, best of 3: 908 µs per loop

In [11]: %timeit df.copy()
1000 loops, best of 3: 585 µs per loop

In [12]: %timeit df.loc[:,df.columns]
1000 loops, best of 3: 893 µs per loop
```
on master (post 0.19.1)
so this at the end basically doing [12] (in this case). so its 2x slower, maybe something going on, but it seems very minor at best.

@simonm3 your comparison is not apt as you are not just selecting the column names, but the actual data itself.

all of that said, I will reprupose this issue to have some asv's for this

**Comment by hermidalc** [comment]
Still extremely slow as of pandas 0.25.3

**Comment by avinashpancham** [comment]
take
