### ISSUE TITLE
Can't combine (add) two indexes 

### ISSUE THREAD

**Issue by EP-Guy** [pandas-dev/pandas#14598]
I would like to interpolate a Series at new values (which itself doesn't appear to be supported), which can be accomplished by reindexing and interpolating. An example of this is

```python
s = pd.Series(np.random.rand(6), index= np.arange(20,140,20))

idx = pd.Index(np.arange(20,140,10))

s.reindex(s.index + idx).interpolate()
```

But the operation `s.index + idx` results in `ValueError: cannot evaluate a numeric op with unequal lengths`.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 30 Stepping 5, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en_US
LOCALE: None.None

pandas: 0.19.1
nose: 1.3.7
pip: 8.1.1
setuptools: 20.3
Cython: 0.23.4
numpy: 1.11.0
scipy: 0.17.0
statsmodels: 0.6.1
xarray: None
IPython: 4.1.2
sphinx: 1.3.1
patsy: 0.4.0
dateutil: 2.5.1
pytz: 2016.2
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5.2
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.39.0
pandas_datareader: None

</details>

**Comment by sinhrks** [comment]
``+`` operator no longer means union.  See:

- http://pandas.pydata.org/pandas-docs/version/0.19.0/whatsnew.html#whatsnew-0150-deprecations

you can use ``.union`` instead.

```
s.reindex(s.index.union(idx)).interpolate()
```
