### ISSUE TITLE
DOC: indexing with combination of row slice and column label

### ISSUE THREAD

**Issue by andreydung** [pandas-dev/pandas#14594]
What is the proper way to set value to a column ('widenGT'), for a range of rows (3:7)? How do I write code (specifically for the problem below) that does not generate the SettingWithCopyWarning: "A value is trying to be set on a copy of a slice from a DataFrame?".
In my production code, the behavior are not consistent, value are not set sometimes!!!

#### A small, complete example of the issue

```python
import pandas as pd
import numpy as np
print pd.show_versions()

df = pd.DataFrame(np.ones((10,2)), columns = ['A', 'B'])
print df

df['newColumn'] = 0

# set values using column label, and range of integer indexes
df.newColumn.iloc[3:7] = 2
print df

# set values using column label, and condition on another column
df.loc[df['newColumn'] == 2, 'A'] = 3
print df

```

#### Expected Output
```
A    B  newColumn
0  1.0  1.0          0
1  1.0  1.0          0
2  1.0  1.0          0
3  1.0  1.0          2
4  1.0  1.0          2
5  1.0  1.0          2
6  1.0  1.0          2
7  1.0  1.0          0
8  1.0  1.0          0
9  1.0  1.0          0
A    B  newColumn
0  1.0  1.0          0
1  1.0  1.0          0
2  1.0  1.0          0
3  3.0  1.0          2
4  3.0  1.0          2
5  3.0  1.0          2
6  3.0  1.0          2
7  1.0  1.0          0
8  1.0  1.0          0
9  1.0  1.0          0
```

#### Output of ``pd.show_versions()``

<details>
# Paste the output here pd.show_versions() here
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-63-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.2
setuptools: 27.2.0
Cython: 0.24.1
numpy: 1.11.1
scipy: 0.18.1
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.4.6
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.7
blosc: None
bottleneck: 1.1.0
tables: 3.2.3.1
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.3
lxml: 3.6.4
bs4: 4.5.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.42.0
pandas_datareader: None
None
</details>

**Comment by chris-b1** [comment]
The way to do this is currently is: 
```python
df.loc[df.index[3:7], 'newColumn'] = 2
```
Alternatively - a little more efficient but also potentially less clear:
```python
df.iloc[3:7, df.columns.get_loc('newColumn')] = 2
```

**Comment by chris-b1** [comment]
I think this could be a good doc example - this situation doesn't seem to be covered in the indexing section and I believe is semi-common.
http://pandas.pydata.org/pandas-docs/stable/indexing.html

**Comment by andreydung** [comment]
Thanks!
