### ISSUE TITLE
TST: indexes/test_base.py:TestIndex.test_format is flaky

### ISSUE THREAD

**Issue by evectant** [pandas-dev/pandas#14626]
`indexes/test_base.py:TestIndex.test_format` compares `index.format()` and `str(index[0])`, where `index = Index([datetime.now()])`. These won't match if the current timestamp ends with zeros:

```python
In [2]: i = pd.Index([pd.Timestamp('2012-01-01 00:00:00.111111')])

In [3]: j = pd.Index([pd.Timestamp('2012-01-01 00:00:00.111000')])

In [4]: i.format(), [str(i[0])]
Out[4]: (['2012-01-01 00:00:00.111111'], ['2012-01-01 00:00:00.111111'])

In [5]: j.format(), [str(j[0])]
Out[5]: (['2012-01-01 00:00:00.111'], ['2012-01-01 00:00:00.111000'])
```

Same thing for real: https://travis-ci.org/pandas-dev/pandas/jobs/173440088#L1355

**Comment by jreback** [comment]
yeah this does occasionally fail

it's not a great test, but is testing the default behavior so no easy way to control the formatting
maybe put this in a while loop and get a new time if the current time ends with 000 

put a show explaination there
