### ISSUE TITLE
API: set_axis does not have inplace=False

### ISSUE THREAD

**Issue by denfromufa** [pandas-dev/pandas#14636]
http://pandas.pydata.org/pandas-docs/version/0.19.1/generated/pandas.DataFrame.set_axis.html

**Comment by jreback** [comment]
this would be a trivial impl, e.g.

```
obj = obj.copy()
obj.set_axis(...)
return obj
```

so if you'd like to do a PR (keeping ``inplace=True`` as the default) would be ok.

**Comment by jreback** [comment]
I would not be upset by making this ``inplace=None`` and having a warning if not specified, so that we could make ``inplace=False`` the default (e.g. return a copy). We did a similar change in ``.eval`` IIRC in 0.18.0

**Comment by denfromufa** [comment]
@jreback Ok, I started the change to set_axis, why is flake not running in CI?

Here is eval change you mentioned that I'm going to use as a guide:

https://github.com/pandas-dev/pandas/pull/11149/files

**Comment by jreback** [comment]
https://travis-ci.org/pandas-dev/pandas/jobs/175772192

hmm, lint IS running, but its not failing the build....hmmm

@jorisvandenbossche

**Comment by jorisvandenbossche** [comment]
I think it was removed by accident here: https://github.com/pandas-dev/pandas/pull/14516/files, but you did already put in back https://github.com/pandas-dev/pandas/commit/52241a7d8a8be2cc1ae40cbde054b0983ac1f429 in the meantime?

**Comment by jreback** [comment]
yes lint should be good now
