### ISSUE TITLE
BUG: to_dense is broken

### ISSUE THREAD

**Issue by gfyoung** [pandas-dev/pandas#14647]
As of <a href="https://github.com/pandas-dev/pandas/tree/1d6dbb41b26a39121ec8c4f19f5da78bb0ab4af7/pandas">1d6dbb</a>, the behaviour, documentation, and signatures for `to_dense` are widely inconsistent:

<a href="https://github.com/pandas-dev/pandas/blob/1d6dbb41b26a39121ec8c4f19f5da78bb0ab4af7/pandas/sparse/array.py#L382">SparseArray</a>: documentation is incorrect (we are not converting a `SparseSeries`), and the `fill` parameter is not even respected if you trace the code.  Not sure why it was ever there in the first place.

<a href="https://github.com/pandas-dev/pandas/blob/1d6dbb41b26a39121ec8c4f19f5da78bb0ab4af7/pandas/sparse/series.py#L529">SparseSeries</a>: What is the purpose of `sparse_only`?  Not only is it not documented, but it also is inconsistent with `SparseArray` behaviour.

<a href="https://github.com/pandas-dev/pandas/blob/1d6dbb41b26a39121ec8c4f19f5da78bb0ab4af7/pandas/sparse/frame.py#L231">SparseDataFrame</a>: Perhaps the most intuitive of them all.  Documentation is correct, and it has no unnecessary parameters like the other two do.

I propose that we change the `to_dense` behaviour to match that of `SparseDataFrame`.  Take no arguments and just convert to a dense object with no questions asked.

**Comment by jreback** [comment]
yes I agree these should all be consistent as ``.to_dense()``

**Comment by sinhrks** [comment]
It's nice to once organize related definitions, including ``.values``, ``.get_values()``, ``internal_values()`` and ``external_values()``. maybe ``internals.rst``?
