### ISSUE TITLE
Extending Pandas Dataframe Documentation

### ISSUE THREAD

**Issue by achapkowski** [pandas-dev/pandas#14662]
Hello,

I am looking for documentation on how to extend the pandas dataframe object.  Can someone please point me to some documentation on how to do this?

Thank you

**Comment by TomAugspurger** [comment]
By extending, you mean subclassing? Those docs are [here](http://pandas.pydata.org/pandas-docs/stable/internals.html#subclassing-pandas-data-structures).

I'm going to close this issue for now, but if you come across specific places where the docs aren't clear than please do open new issues.

**Comment by achapkowski** [comment]
@TomAugspurger exactly what i needed thanks
