### ISSUE TITLE
xlrd required for read_excel put not a requirement in setup.py

### ISSUE THREAD

**Issue by kghose** [pandas-dev/pandas#14673]
I feel that requirements, such as 'xlrd' should be part of the setup.py file and installed when we install Pandas. Thanks!

#### A small, complete example of the issue

```python
# Your code here
import pandas as pd
pd.read_excel('srep10775-s2.xls', sheet=1)
```

#### Expected Output
... should be contents of excel file

#### Actual Output

```python
    218     def __init__(self, io, **kwds):
    219 
--> 220         import xlrd  # throw an ImportError if we need to
    221 
    222         ver = tuple(map(int, xlrd.__VERSION__.split(".")[:2]))

ImportError: No module named 'xlrd'
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Darwin
OS-release: 16.1.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.19.1
nose: 1.3.7
pip: 8.1.2
setuptools: 27.2.0
Cython: 0.24.1
numpy: 1.11.2
scipy: 0.18.1
statsmodels: None
xarray: None
IPython: 5.1.0
sphinx: 1.4.6
patsy: None
dateutil: 2.6.0
pytz: 2016.7
blosc: None
bottleneck: None
tables: 3.3.0
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None
</details>

**Comment by jreback** [comment]
``xlrd`` is an optional dependency. you can install it if you wish, but it is not required to use pandas. http://pandas.pydata.org/pandas-docs/stable/install.html#dependencies
