### ISSUE TITLE
Nit: In the documentation of DataFrame.any, the 'axis' argument is missing

### ISSUE THREAD

**Issue by jondo** [pandas-dev/pandas#14690]
The [current online documentation of `pandas.DataFrame.any`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.any.html) omits the `axis` keyword, as e.g. [described for concat](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html).

However, the following works:
```python
pd.DataFrame([[True, False]]).any(axis=1)
```

**Comment by jorisvandenbossche** [comment]
I see `axis` listed in the list of parameters (it's the first) in the link you provided ? Or do you mean that there is no explanation except for the possible values?

**Comment by jondo** [comment]
I'm sorry! How could I miss this! Well, some explanation text might have helped me not overlooking it :-)

**Comment by jorisvandenbossche** [comment]
Feel free to make a PR to add a line of explanation!
