### ISSUE TITLE
indexing with df.ix for slicing is inclusive for stop index

### ISSUE THREAD

**Issue by gmaclaur** [pandas-dev/pandas#14691]
#### A small, complete example of the issue

```python
df = pd.DataFrame({'this': np.arange(10), 'that': np.arange(10,20)})
df.iloc[:5, :]
df.ix[:5, :]
```

df.iloc and df.ix should return the same output. However, it appears that .ix is inclusive on the high end of the slice. This behavior is inconsistent with indexing in Python.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Darwin
OS-release: 14.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.0
nose: 1.3.4
pip: 8.1.2
setuptools: 20.7.0
Cython: 0.22
numpy: 1.11.1
scipy: 0.18.0
statsmodels: 0.6.1
xarray: None
IPython: 4.0.1
sphinx: 1.2.3
patsy: 0.3.0
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: None
tables: None
numexpr: 2.6.1
matplotlib: 1.4.3
openpyxl: 1.8.5
xlrd: 0.9.3
xlwt: 0.7.5
xlsxwriter: 0.6.7
lxml: 3.4.2
bs4: 4.3.2
html5lib: None
httplib2: 0.9.2
apiclient: 1.4.2
sqlalchemy: 0.9.9
pymysql: None
psycopg2: 2.6 (dt dec pq3 ext)
jinja2: 2.7.3
boto: 2.36.0
</details>

**Comment by jreback** [comment]
This is documented and specifically mentioned in indexing.
http://pandas.pydata.org/pandas-docs/stable/indexing.html#different-choices-for-indexing

``.ix`` is doing *label* indexing here, wihch always includes the stop index., ``.iloc`` is ALWAYS positional indexing.
