### ISSUE TITLE
pandas-qt appears to broken for python 3.x

### ISSUE THREAD

**Issue by draperjames** [pandas-dev/pandas#14703]
In the pandas [faq](https://github.com/pandas-dev/pandas/blob/master/doc/source/faq.rst) contains the following statement;

> "There is no support for such visualization in pandas. However, the external package pandas-qt does provide this functionality."

I have tested pandas-qt on in several python environments and I could not get pandas-qt to install. I have logged the this in the [pandas-qt issues](https://github.com/datalyze-solutions/pandas-qt/issues/17). So far none of the contributors have commented on this issue. The last commit on on the repo was two months ago leading me to believe that this project has gone dormant.  

So my suggestion is to change the above statement from the FAQ to read;

 > "There is no support for such visualization in pandas."

If anyone out there knows of a functional PyQt viewer for pandas please let me know.

Thanks!

**Comment by sinhrks** [comment]
Based on py-qt issues, it don't support py3 yet. I think the current doc is still usable pointer for py2 users?

**Comment by draperjames** [comment]
Possibly. Either way it would save some people time if that was reflected in the documentation.

**Comment by jorisvandenbossche** [comment]
@draperjames Do you want to do a PR to add a note saying "python 2 only" ?
