### ISSUE TITLE
DOC: pd.read_msgpack not in API index

### ISSUE THREAD

**Issue by skycaptain** [pandas-dev/pandas#14702]
If I have not overlooked anything, it seams that `pd.read_msgpack` does not show up in the [API reference index](http://pandas.pydata.org/pandas-docs/version/0.19.1/genindex.html#R).

**Comment by chris-b1** [comment]
Yep, PR to fix welcome!

**Comment by taraadiseshan** [comment]
If no one else is working on this, I'll start working on a PR!

**Comment by jorisvandenbossche** [comment]
@taraadiseshan Go for it! If you have any questions, just ask here or at https://gitter.im/pydata/pandas
