### ISSUE TITLE
groupby boxplot doesn't work if multiple by's are used

### ISSUE THREAD

**Issue by languitar** [pandas-dev/pandas#14701]
#### Code Sample, a copy-pastable example if possible

```python
data = pd.DataFrame({'A': [1, 1, 2, 2], 'B': ['a', 'b', 'a', 'b'], 'value': [1, 2, 3, 4]})
data.groupby(['A', 'B']).boxplot()
```
#### Problem description

This code fails with an obscure error message from the internals:

```
KeyError                                  Traceback (most recent call last)
<ipython-input-118-d3ffaf6e9196> in <module>()
----> 1 data.groupby(['A', 'B']).boxplot()

/home/languitar/miniconda2/envs/monitoring/lib/python2.7/site-packages/pandas/tools/plotting.pyc in boxplot_frame_groupby(grouped, subplots, column, fontsize, rot, grid, ax, figsize, layout, **kwds)
   3109                               rot=rot, grid=grid, **kwds)
   3110             ax.set_title(pprint_thing(key))
-> 3111             ret.loc[key] = d
   3112         fig.subplots_adjust(bottom=0.15, top=0.9, left=0.1,
   3113                             right=0.9, wspace=0.2)

/home/languitar/miniconda2/envs/monitoring/lib/python2.7/site-packages/pandas/core/indexing.pyc in __setitem__(self, key, value)
    137         else:
    138             key = com._apply_if_callable(key, self.obj)
--> 139         indexer = self._get_setitem_indexer(key)
    140         self._setitem_with_indexer(indexer, value)
    141

/home/languitar/miniconda2/envs/monitoring/lib/python2.7/site-packages/pandas/core/indexing.pyc in _get_setitem_indexer(self, key)
    124
    125         try:
--> 126             return self._convert_to_indexer(key, is_setter=True)
    127         except TypeError as e:
    128

/home/languitar/miniconda2/envs/monitoring/lib/python2.7/site-packages/pandas/core/indexing.pyc in _convert_to_indexer(self, obj, axis, is_setter)
   1227                 mask = check == -1
   1228                 if mask.any():
-> 1229                     raise KeyError('%s not in index' % objarr[mask])
   1230
   1231                 return _values_from_object(indexer)
```

There is no hint in the documentation that this could be an illegal operation.

#### Expected Output

It  should just print a boxplot for all groups, or if this really doesn't work, give a real hint why.

#### Output of ``pd.show_versions()``

<details>
```
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Linux
OS-release: 4.8.8-1-ARCH
machine: x86_64
processor:
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.19.0
nose: None
pip: 8.1.2
setuptools: 27.2.0
Cython: None
numpy: 1.11.2
scipy: 0.18.1
statsmodels: None
xarray: None
IPython: 5.1.0
sphinx: None
patsy: None
dateutil: 2.5.3
pytz: 2016.7
blosc: None
bottleneck: None
tables: 3.3.0
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None
```
</details>

**Comment by sinhrks** [comment]
Thx for the report. Current impl doesn't care multilevel group cases. PR is appreciated.

**Comment by shuq007** [comment]
**Groupby boxplot is not working even when a single by is used**

```
df = pd.DataFrame(np.random.randn(10, 2),
                  columns=['Col1', 'Col2'])
df['X'] = pd.Series(['A', 'A', 'A', 'A', 'A',
                     'B', 'B', 'B', 'B', 'B'])
boxplot = df.boxplot(by='X')
```

**Problem description**

This code fails with an obscure error message from the internals:
ValueError                                Traceback (most recent call last)
<ipython-input-20-c871af088cba> in <module>
      3 df['X'] = pd.Series(['A', 'A', 'A', 'A', 'A',
      4                      'B', 'B', 'B', 'B', 'B'])
----> 5 boxplot = df.boxplot(by='X')

~/.local/lib/python3.7/site-packages/pandas/plotting/_core.py in boxplot_frame(self, column, by, ax, fontsize, rot, grid, figsize, layout, return_type, backend, **kwargs)
    445         layout=layout,
    446         return_type=return_type,
--> 447         **kwargs,
    448     )
    449 

~/.local/lib/python3.7/site-packages/pandas/plotting/_matplotlib/boxplot.py in boxplot_frame(self, column, by, ax, fontsize, rot, grid, figsize, layout, return_type, **kwds)
    373         layout=layout,
    374         return_type=return_type,
--> 375         **kwds,
    376     )
    377     plt.draw_if_interactive()

~/.local/lib/python3.7/site-packages/pandas/plotting/_matplotlib/boxplot.py in boxplot(data, column, by, ax, fontsize, rot, grid, figsize, layout, return_type, **kwds)
    323             ax=ax,
    324             layout=layout,
--> 325             return_type=return_type,
    326         )
    327     else:

~/.local/lib/python3.7/site-packages/pandas/plotting/_matplotlib/boxplot.py in _grouped_plot_by_column(plotf, data, columns, by, numeric_only, grid, figsize, ax, layout, return_type, **kwargs)
    204         gp_col = grouped[col]
    205         keys, values = zip(*gp_col)
--> 206         re_plotf = plotf(keys, values, ax, **kwargs)
    207         ax.set_title(col)
    208         ax.set_xlabel(pprint_thing(by))

~/.local/lib/python3.7/site-packages/pandas/plotting/_matplotlib/boxplot.py in plot_group(keys, values, ax)
    289             ax.tick_params(axis="both", labelsize=fontsize)
    290         if kwds.get("vert", 1):
--> 291             ax.set_xticklabels(keys, rotation=rot)
    292         else:
    293             ax.set_yticklabels(keys, rotation=rot)

~/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_base.py in wrapper(self, *args, **kwargs)
     61 
     62         def wrapper(self, *args, **kwargs):
---> 63             return get_method(self)(*args, **kwargs)
     64 
     65         wrapper.__module__ = owner.__module__

~/anaconda3/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py in wrapper(*args, **kwargs)
    449                 "parameter will become keyword-only %(removal)s.",
    450                 name=name, obj_type=f"parameter of {func.__name__}()")
--> 451         return func(*args, **kwargs)
    452 
    453     return wrapper

~/anaconda3/lib/python3.7/site-packages/matplotlib/axis.py in _set_ticklabels(self, labels, fontdict, minor, **kwargs)
   1794         if fontdict is not None:
   1795             kwargs.update(fontdict)
-> 1796         return self.set_ticklabels(labels, minor=minor, **kwargs)
   1797 
   1798     @cbook._make_keyword_only("3.2", "minor")

~/anaconda3/lib/python3.7/site-packages/matplotlib/axis.py in set_ticklabels(self, ticklabels, minor, **kwargs)
   1716             if len(locator.locs) != len(ticklabels) and len(ticklabels) != 0:
   1717                 raise ValueError(
-> 1718                     "The number of FixedLocator locations"
   1719                     f" ({len(locator.locs)}), usually from a call to"
   1720                     " set_ticks, does not match"

ValueError: The number of FixedLocator locations (4), usually from a call to set_ticks, does not match the number of ticklabels (2).
**Note: ** This code was working in earlier versions of pandas...

**Expected Output**

It should just print a boxplot for all groups, or if this really doesn't work, give a real hint why.
Output of pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-90-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.5
numpy            : 1.19.5
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 21.3.1
setuptools       : 45.2.0.post20200210
Cython           : 0.29.15
pytest           : 5.4.3
hypothesis       : 5.5.4
sphinx           : 2.4.0
blosc            : None
feather          : None
xlsxwriter       : 1.2.7
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.12.0
pandas_datareader: 0.10.0
bs4              : 4.8.2
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.3.4
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : 6.0.0
pytables         : None
pytest           : 5.4.3
pyxlsb           : None
s3fs             : None
scipy            : 1.5.4
sqlalchemy       : 1.3.11
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.7
numba            : 0.48.0
