### ISSUE TITLE
TST: test_transactions for sqlite fallback fails on python 3.6

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#14719]
Skipped on travis for now: https://github.com/pandas-dev/pandas/commit/880de3054c7ce3a6c48e295837207787dc73350f

See also comment here: https://github.com/pandas-dev/pandas/issues/14679#issuecomment-261533205 (I can reproduce it locally by running the test, but not with a simple example mimicking the test)

**Comment by shreyateeza** [comment]
@jorisvandenbossche @jreback Can you please let me know how can I resolve this issue?

**Comment by jorisvandenbossche** [comment]
First step would be to try to reproduce the issue. If you run the test locally, does it fail? (when removing the skip)
