### ISSUE TITLE
Series.unique converts uint64 to int64 (with overflow)

### ISSUE THREAD

**Issue by dnspies** [pandas-dev/pandas#14721]
```
>>> import pandas as pd
>>> import numpy as np
>>> s = pd.Series([1,2,2**63], dtype=np.dtype('uint64'))
>>> s
0                      1
1                      2
2    9223372036854775808
dtype: uint64
>>> s.unique()
array([                   1,                    2, -9223372036854775808])

```

Series.unique should preserve whatever type the values are.  But instead it changes from uint64 to int64.

INSTALLED VERSIONS
------------------
...
python: 3.4.3.final.0
python-bits: 64
...

...
pandas: 0.17.1
numpy: 1.10.4
...

**Comment by jreback** [comment]
this is a sympton of #4471 in general ``uint64`` support is not great. PR's are welcome to fix that!

**Comment by gfyoung** [comment]
@jreback : IIUC, your statement is incorrect.  The bug traces back as follows:

When you call `Series.unique()`, it calls the super-class implementation <a href="https://github.com/pandas-dev/pandas/blob/4143b323f5f653c3f7168cef013f7b8ceeb5e27d/pandas/core/base.py#L966">here</a>.  That method then calls `unique1d()` <a href="https://github.com/pandas-dev/pandas/blob/4143b323f5f653c3f7168cef013f7b8ceeb5e27d/pandas/core/nanops.py#L790">here</a>.  The erroneous check is <a href="https://github.com/pandas-dev/pandas/blob/4143b323f5f653c3f7168cef013f7b8ceeb5e27d/pandas/core/nanops.py#L806">here</a>, which catches `np.uint64` but then incorrectly converts them to `int64`.

The correct patch I think is to change the check to `np.signedinteger` and then have a separate one for `np.unsignedinteger`.  However, I cannot find a proper implementation of a `uint64` hashtable.  In addition, things seem to get insanely complicated as we move to `hashtable.pyx` (and related helper `.pxi.in` files) `khash.pxd`, and `khash.h`, which setup all of the hashtable functionality.

The easy way out and less desirable way I think is to modify this branch <a href="https://github.com/pandas-dev/pandas/blob/4143b323f5f653c3f7168cef013f7b8ceeb5e27d/pandas/core/nanops.py#L809">here</a> and convert the resulting array back to the original dtype.

Thoughts?

**Comment by jreback** [comment]
@gfyoung I was pointing to a 'generic' issue with uint64. it doesn't work in lots of places!

**Comment by gfyoung** [comment]
@jreback : Ah, fair enough.  But thoughts about this?

**Comment by jreback** [comment]
>However, I cannot find a proper implementation of a uint64 hashtable. In addition, things seem to get insanely complicated as we move to hashtable.pyx (and related helper .pxi.in files) khash.pxd, and khash.h, which setup all of the hashtable functionality.

hmm

**Comment by gfyoung** [comment]
@jreback : If someone knows how to navigate through that swamp of hashtable code, then by all means, patch it! :smile: But yes, it's just a matter of adding another hashtable class.

**Comment by jreback** [comment]
you can use python hashing, no?

```
In [9]: hash(np.uint64(2**63+1))
Out[9]: 5

In [10]: hash(np.int64(2**63-1))
Out[10]: 3
```

**Comment by gfyoung** [comment]
@jreback : Perhaps, but then what's going on with this entire hashtable class?  Why was it implemented that way if Python hashing is feasible?

**Comment by jreback** [comment]
prob not that hard to write some klib type stuff in cython

**Comment by jreback** [comment]
klib is >> faster than python for the types of things we do (and doesn't have as much overhead for pyobjects)

**Comment by jreback** [comment]
or just add to the klib stuff (might be easier)

**Comment by gfyoung** [comment]
@jreback : I think adding to the klib is the best solution, but I don't really understand how all of it works.

**Comment by jreback** [comment]
me neither :<

**Comment by jreback** [comment]
its just template stuff in a header only library

**Comment by jreback** [comment]
you can prob copy int64 and just do a replace. (maybe)

**Comment by gfyoung** [comment]
@jreback : True that file is, but I have no idea how it gets populated.
