### ISSUE TITLE
Feature Request: Circular bins with pd.cut

### ISSUE THREAD

**Issue by ghost** [pandas-dev/pandas#14720]
pandas.cut and similar operate on the principle that bins start at one end of a line and finish at another. However, sometimes it is necessary to work with data that operates on a circular scale, for example compass directions.

It would be a great enhancement if pd.cut could deal with these cases. 
I do not know of anything in numpy or pandas that currently deals with this situation, but it would be very useful.

#### Current workaround
Currently this is accomplished by having a bin covering half of the real bin at each end of the scale, for example the bin 345° to15° would be covered by a bin of 0° to 15° and a bin of 345° to 360°. It is then necessary to assign the members of one category to the other, rename it, and then delete the unused category.

```python
data = pd.DataFrame(np.random.random(400) * 360, columns=["Direction"])
bins = np.array([-15,  15,  45,  75, 105, 135, 165, 195, 225, 255, 285, 315, 345, 375])
c = pd.cut(data.Direction, bins)
c[c=="(-15, 15]"] = "(345, 375]"
c = c.cat.remove_unused_categories()
cats = list(c.cat.categories)
cats[-1] = '(345, 15]'
c = c.cat.set_categories(cats)
```

#### Desired behaviour

Better would be accepting a parameter indicating at what point the scale loops, e.g. zeroat=360. Other solutions may be possible, such as taking the structure of the list of bins to indicate that the scale loops.

One issue is the order. How can the fact that 345 is both more than and less than 0 be dealt with, depending on what direction you are looking in? There is an order, but it isn't straight forward.

**Comment by jreback** [comment]
you can specify ``labels`` to ``pd.cut``.

how would a ``scale`` parameter work? why don't you just rescale the data first?

**Comment by blindmelon** [comment]
I don't understand your question about rescaling the data first.
As for the labels of pd.cut, that would be a decent solution if duplicates were possible - i.e. if I could do

```python
l = ['(345, 15]', '(15, 45]', '(45, 75]', '(75, 105]', '(105, 135]', '(135, 165]', '(165, 195]', '(195, 225]', '(225, 255]', '(255, 285]', '(285, 315]', '(315, 345]', '(345, 15]']
pd.cut(d.Direction, bins, labels=l)
```
and have anything falling into the first or last bin given the same category. But as it stands, that isn't possible and so doesn't change things.

**Comment by jreback** [comment]
@blindmelon you mentioned ``scale`` above. what did *you* mean by that?

**Comment by blindmelon** [comment]
By scale (using it as a noun), I mean the range of values that each data point must fall into. Specifically in my example, each value falls within the range 0 - 360, with 360 being equal to 0. Perhaps scale is the wrong word, but I can't think of an alternative.

**Comment by mroeschke** [comment]
This use case seem pretty domain specific. If `cut` could operate on a "Polar coordinate data type", that might be more appropriate, but until then closing for now.
