### ISSUE TITLE
DOC: document groupby.resample/rolling

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#14759]
examples are in the whatsnew: http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#groupby-syntax-with-window-and-resample-operations

but I think a section in groupby.rst with some xrefs in timeseries.rst (resample) and computation.rst (rolling) would be helpful. I wrote this and can barely find it!

plus the API reference is missing these functions

**Comment by wandersoncferreira** [comment]
hi @jreback I want to start contributing to pandas project and I think this could be a good entry for me. I use this two method all day long. 

Can you assign this to me? Thanks!
