### ISSUE TITLE
No TimeGrouper docs, Day-of-Week resampling?

### ISSUE THREAD

**Issue by naught101** [pandas-dev/pandas#14760]
TimeGrouper isn't really mentioned in the docs at all. In particular, it'd be nice to know what the grouping options are. I assume they're the same as resample's options? I also can't find a simple list of those.

In particular, weekly grouping is doable via `'W'`, but I can't find that listed in the docs anywhere.

It would also be really nice to have a `'DoW'` (Day of Week) grouping option - this can be really useful for any data with a human signal in it.

**Comment by jorisvandenbossche** [comment]
There are these docs for `Grouper`:

* http://pandas.pydata.org/pandas-docs/stable/groupby.html#grouping-with-a-grouper-specification
* http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Grouper.html

> In particular, weekly grouping is doable via 'W', but I can't find that listed in the docs anywhere.

The frequency options are listed here: http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases (and this is linked to at several places, but I see that the docstring of Grouper has a too general link to the timeseries page).

> It would also be really nice to have a 'DoW' (Day of Week) grouping option

This is not a frequency (it does not give you a timeseries). But such grouping is indeed very useful, and can be obtained with `df.groupby(df.index.dayofweak)`

@naught101 If you have specific points were those docs can be improved, we would really love to hear it (or get a PR to fix it :-)). More eyes give better docs.

**Comment by naught101** [comment]
None of those pages you linked to actually mentions 'TimeGrouper`. Nor does TimeGrouper appear in the 'API reference' section of the docs. It has built-in documentation, is there a reason that isn't included in the API docs?


Sorry, re-sampling was probably not the right word.. yes, that day of week works fine for my purposes..

**Comment by jreback** [comment]
``TimeGrouper`` is not a public interface (its orignal, so its not deprecated either), instead see docs: http://pandas.pydata.org/pandas-docs/stable/groupby.html#grouping-with-a-grouper-specification

**Comment by jorisvandenbossche** [comment]
@naught101 yes, sorry, forgot to mention that all my references were to `pd.Grouper`, which can be used instead of `pd.TimeGrouper`
