### ISSUE TITLE
TST: reorg groupby tests

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#14813]
see suggestions here: https://github.com/pandas-dev/pandas/pull/12607#issuecomment-265310458

we have lots and lots of groupby tests and so getting pretty unweidly

so should reorg to a sub-dir setup like we have for other things

eg.

pandas/tests/groupby/.....

**Comment by aileronajay** [comment]
@jreback so this change would involve relocating pandas/tests/test_groupby.py to the hierarchy pandas/tests/groupby/ and then breaking this file into other files (having tests of similar type)?

**Comment by jreback** [comment]
yes

**Comment by aileronajay** [comment]
I have created this PR for the change, https://github.com/pandas-dev/pandas/pull/14817/commits
