### ISSUE TITLE
DOC: DataFrame.resample docs could be improved

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#14843]
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.resample.html?highlight=dataframe%20resample#pandas.DataFrame.resample

These are the *same* docs for both Series & DataFrame. so might be nice to add some DataFrame examples (and use on / axis parameters). So may need to move these to a ``shared_docs`` template to suppport this.

**Comment by rishikksh20** [comment]
There is one more issue in this page where following link not formatted :
 To learn more about the offset strings, please see \` this link
<http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases>\`__.

I can take this issue. Please guide me little bit about docs and `shared_docs` template.

**Comment by jorisvandenbossche** [comment]
@jreback this might be closed by https://github.com/pandas-dev/pandas/pull/15627. But there we choose to just add example for DataFrame in the existing docstring (so have a unified docstring for Series and DataFrame with examples for both). 
But in principle we could also split off the examples and only add those relevant to Series or DataFrame (but not sure if I find this worth the complexity here).

**Comment by jreback** [comment]
in this case i think this is fine

resample is pretty much the same (meaning signature is the same), unlike say sort_values for Series/Dataframe
