### ISSUE TITLE
Data corruption in numerical DataFrame using joblib and shared memory

### ISSUE THREAD

**Issue by jbalfer** [pandas-dev/pandas#14840]
#### Code Sample, a copy-pastable example if possible

```python
import joblib
import multiprocessing
import numpy as np
import os
import pandas as pd
import tempfile

df = pd.DataFrame(np.random.random((1000,3)))

# df.head() is
# 0	1	2
# 0	0.204271	0.250022	0.333579
# 1	0.894605	0.262193	0.412623
# 2	0.260175	0.056537	0.084432
# 3	0.774219	0.824558	0.521398
# 4	0.414248	0.913390	0.735691

temp_folder = tempfile.mkdtemp()
filename = os.path.join(temp_folder, 'joblib_test.mmap')
if os.path.exists(filename): os.unlink(filename)
_ = joblib.dump(df, filename)
memmap = joblib.load(filename, mmap_mode='r') 

def myFunc(df) :
    return df

results = joblib.Parallel(n_jobs=2)(joblib.delayed(myFunc)(memmap) for _ in range(10))

# results[0].head() is
# 	0	1	2
# 0	1.105907e+169	5.745991e+169	5.298748e+180
# 1	3.036710e+213	9.708092e+189	5.587160e+238
# 2	2.379254e+233	7.281947e+223	1.278075e+161
# 3	7.658495e+151	1.452701e-253	6.235120e-85
# 4	6.240245e-85	6.340871e+160	9.041151e+271

np.allclose(results[0], df) # False!
```
#### Problem description

When a Pandas DataFrame is used as a shared memory object for parallel computing using ```joblib``` and ```multiprocessing```, the data gets corrupted.

In the above example, the column name and index stays correct, while the internal data (```df.values```) shows random values. However, if not a DataFrame but a NumPy array (simply ```df.values```) is stored in the memory map, everything works as expected.

We found that the error only occurs if all of the following criteria are met:
- a Pandas DataFrame is used
- the DataFrame contains numerical data (strings and other objects work as expected)
- the DataFrame has a certain size, e.g., the above example works as expected with small data 
- the DataFrame is stored and loaded using ```joblib.dump``` and ```joblib.load```
- more than one processor is used

#### Expected Output

We would expect that the all of the elements in results are the same as the original DataFrame and that 
```np.allclose(results[0], df)``` is True.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.8.12-moby
machine: x86_64
processor: 
byteorder: little
LC_ALL: C.UTF-8
LANG: C.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.19.1
nose: 1.3.7
pip: 8.1.2
setuptools: 27.2.0
Cython: 0.24.1
numpy: 1.11.1
scipy: 0.18.1
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.4.6
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.6.1
blosc: None
bottleneck: 1.1.0
tables: 3.2.3.1
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.3
lxml: 3.6.4
bs4: 4.5.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: 2.6.2 (dt dec pq3 ext lo64)
jinja2: 2.8
boto: 2.42.0
pandas_datareader: None
</details>

**Comment by jreback** [comment]
this is a joblib issue, probably with the way its serializing things.
