### ISSUE TITLE
df.info() returning negative byte value

### ISSUE THREAD

**Issue by apiszcz** [pandas-dev/pandas#14857]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
df.info()
dtypes: float64(9), int64(1), object(17)
memory usage: -611431520.0+ bytes
```
#### Problem description
Value returned is negative and should be positive.

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

#### Expected Output
Positive value > 4GB

#### Output of ``pd.show_versions()``

<details>
# Paste the output here pd.show_versions() here
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.19.1
nose: 1.3.7
pip: 9.0.1
setuptools: 20.10.1
Cython: 0.25.2
numpy: 1.11.2
scipy: 0.18.1
statsmodels: 0.6.1
xarray: 0.8.1
IPython: 5.1.0
sphinx: None
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2016.2
blosc: 1.4.4
bottleneck: 1.2.0
tables: None
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.3
lxml: 3.6.2
bs4: 4.5.1
html5lib: 0.9999999
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
jinja2: 2.8
boto: 2.39.0
pandas_datareader: None
</details>

**Comment by jreback** [comment]
pls show some more detail on the frame
how long , a sample
this is one windows yes? 
are these strings in the object columns or actual objects?

**Comment by apiszcz** [comment]
1. full info below
2. do you mean a row?
(Pdb) len(df.ix[0])
27
3. Yes, windows 10
4. Strings


(Pdb) df.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17053406 entries, 0 to 17053405
Data columns (total 27 columns):
WKT           object
Record_ID     int64
PLACE_ID      object
PLACE_NAME    object
PLACE_NA_1    object
LATITUDE      float64
LONGITUDE     float64
FEATURE_CL    object
FEATURE_CO    object
FIPS_COUNT    object
ISO2_COUNT    object
ISO3_COUNT    object
ADMIN_LEVE    object
ADMIN_LE_1    object
ADMIN_LE_2    float64
ADMIN_LE_3    float64
ADMIN_LE_4    float64
SOURCE        object
SOURCE_FEA    float64
SOURCE_NAM    float64
SCRIPT        object
PLACE_NA_2    float64
PLACE_ID_B    float64
NAME_TYPE     object
NAME_TYPE_    object
SplitCateg    object
SEARCH_ONL    object
dtypes: float64(9), int64(1), object(17)
memory usage: -611431520.0+ bytes

**Comment by jreback** [comment]
somethings overflowing

**Comment by apiszcz** [comment]
agreed, it also seems to be the case that the variable is a float, not an
unsigned 64 bit integer.

**Comment by jreback** [comment]
This is on windows 7 and master
```
In [8]: df3.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000000 entries, 0 to 19999999
Data columns (total 27 columns):
0      float64
1      float64
2      float64
3      float64
4      float64
5      float64
6      float64
7      float64
8      float64
a0     object
a1     object
a2     object
a3     object
a4     object
a5     object
a6     object
a7     object
a8     object
a9     object
a10    object
a11    object
a12    object
a13    object
a14    object
a15    object
a16    object
int    int64
dtypes: float64(9), int64(1), object(17)
memory usage: 4.0+ GB
```

so something peculiar about either windows 10 or your frame.
```
In [9]: df3.info(memory_usage='deep')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000000 entries, 0 to 19999999
Data columns (total 27 columns):
0      float64
1      float64
2      float64
3      float64
4      float64
5      float64
6      float64
7      float64
8      float64
a0     object
a1     object
a2     object
a3     object
a4     object
a5     object
a6     object
a7     object
a8     object
a9     object
a10    object
a11    object
a12    object
a13    object
a14    object
a15    object
a16    object
int    int64
dtypes: float64(9), int64(1), object(17)
memory usage: 27.5 GB
```

**Comment by apiszcz** [comment]
any way to send you the file to test locally?

**Comment by jreback** [comment]
sure, you can paste a link (if you are comfortable with that), or a link to jeffreback@gmail.com (put on a shared dropbox or something)

**Comment by jreback** [comment]
@apiszcz I tried both of your files and they imported fine for me (on master with windows 7).

It *could* be a windows10 diff I suppose.

**Comment by apiszcz** [comment]
I tested on Windows Server 2012, and Windows 10, same behavior.

**Comment by jreback** [comment]
@apiszcz can you send me a pickle of one of the files

**Comment by jreback** [comment]
also show me how you are reading in

**Comment by apiszcz** [comment]
>>> df=pd.read_csv(r'G:\file1.csv')
>>> df.info()
<snip>
memory usage: -1165288016.0+ bytes
>>> df=pd.read_csv(r'G:\file2.csv')
>>> df.info()
<snip>
memory usage: -1167786368.0+ bytes

**Comment by apiszcz** [comment]
Did you receive version?

**Comment by apiszcz** [comment]
Did you get the CSV files?

**Comment by Dr-Irv** [comment]
@jreback I have Windows 10, and ran your example above, and got the same result.

**Comment by jreback** [comment]
@Dr-Irv you mean negative?

**Comment by Dr-Irv** [comment]
@jreback no I mean I got the 4GB result in the example you created.

**Comment by jreback** [comment]
closing as not reproducible. but if you can find simple way to repro pls comment / create a new issue.
