### ISSUE TITLE
TST: timeseries tests reorg

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#14854]
Datetime
------------
- [x] We have *some* DatetimeIndex tests in [here](https://github.com/pandas-dev/pandas/blob/master/pandas/tseries/tests/test_timeseries.py) and some in [here](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/indexes/test_datetimelike.py) and *a lot* [here](https://github.com/pandas-dev/pandas/blob/master/pandas/tseries/tests/test_base.py) (PR #15266) 

we can separate these out to a single file in ``pandas/tests/indexes/test_datetime.py``
The ``Base`` class (which powers lots of tests for the sub-classes ``DatetimeIndex``, ``PeriodIndex``, ``TimedeltaIndex``), can move to ``pandas/tests/indexes/tests_datetimelike.py`` (and merge with the existing ``Datetimelike`` class).

- [ ] create a ``pandas/tests/scalar/test_timestamp.py`` with ``Timestamp`` specific tests
There are a lot of tests also in [tseries/test_tslib.py](https://github.com/pandas-dev/pandas/blob/master/pandas/tseries/tests/test_tslib.py), that can be merged into ``test_timestamp.py``

- [ ] the residuals (from ``tests_timeseries.py`` are Series tests speficially, these can move to ``pandas/tests/series/test_timeseries.py``

``Legacy Tests``
---------------
- [ ]  [timeseries_legacy](https://github.com/pandas-dev/pandas/blob/master/pandas/tseries/tests/test_timeseries_legacy.py) need a look, but can prob be deleted

``Period``
----------
- [ ] same idea with Period, the actual ``Period`` tests can be moved to ``tests/scalar/test_period.py``, but move the index tests to ``tests/indexes/test_period.py`` (which can be stripped from [here](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/indexes/test_datetimelike.py) and [here](https://github.com/pandas-dev/pandas/blob/master/pandas/tseries/tests/test_base.py))

``Timedelta``
-----------
- [ ] same idea with Timedelta, the actual ``Timedelta`` tests can be moved to ``tests/scalar/test_timedelta.py`` but move the index tests to ``tests/indexes/test_timedelta.py`` (which can be stripped from [here](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/indexes/test_datetimelike.py) and [here](https://github.com/pandas-dev/pandas/blob/master/pandas/tseries/tests/test_base.py))

**Comment by TrigonaMinima** [comment]
@jreback Is anyone working on this?

**Comment by jreback** [comment]
nope - go for it

do this is discrete mergeable pieces

**Comment by TrigonaMinima** [comment]
@jreback I have started with ```pandas/tests/indexes/test_datetime.py``` first. I am not that familiar with the codebase. I might ask a few questions here and there, if that's okay with you. Like, this [TestDateTimeIndexToJulianDate](https://github.com/pandas-dev/pandas/blob/master/pandas/tseries/tests/test_timeseries.py#L5622) class looks like it should be sent to ```test_datetime.py```. Is it okay to copy-paste the whole class and test it there?

**Comment by TrigonaMinima** [comment]
Will [these tests](https://github.com/pandas-dev/pandas/blob/master/pandas/tseries/tests/test_timeseries.py#L4068) come under ```test_datetimeindex_accessors()```?

**Comment by jreback** [comment]
@TrigonaMinima not sure what you mean.

Let me espouse the general idea here. Keep individual tests exactly the same (and classes as much as possible). We want to first simply move things around to group similar things together.

Next phases can dive deeper.
