### ISSUE TITLE
DOC: groupby.rst examples broken

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#14861]
the df for the groupby.resample examples are hiding the correct frame that was previously being used by the docs below 

http://pandas-docs.github.io/pandas-docs-travis/groupby.html#dispatching-to-instance-methods

**Comment by gr8h** [comment]
Can i contribute to this?

Should i use dff instead df since dff = pd.DataFrame({'A': np.arange(8), 'B': list('aabbbbcc')}) and we need to groupby A?

**Comment by gr8h** [comment]
I have renamed _resample()_ `df` to `df_re` under **New syntax to window and resample operations** section. [pull request](https://github.com/pandas-dev/pandas/pull/14863)
