### ISSUE TITLE
API: DataFrame.melt(), DataFrame.wide_to_long()

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#14876]
xref https://github.com/pandas-dev/pandas/pull/14779

So I think it might be nice to have these as convenience methods on DataFrame().
we can deprecate (``pd.melt`` & ``pd.wide_to_long``), though we *didn't* deprecate ``pd.pivot_table``, even though it exists on ``DataFrame``, so this can be a discussion point.

but if we do this, then maybe have a shorter / better name than ``wide_to_long``? (even though it is strictly speaking pretty informative).

**Comment by jreback** [comment]
cc @nuffe

**Comment by nuffe** [comment]
Yes the nomenclature could probably be a bit confusing. Hadley Wickham introduced `melt` ("long") and `cast` ("wide") in the `reshape2` package as a more user friendly interface to base R's `reshape`. However, one still have to resort to base R's `reshape` if one have more groups with common "stubs" like in `pd.wide_to_long`'s doc string examples.

`pd.melt` is the functional equivalent, and I think any combination of `unstack`/`reset_index` would mimic `cast`? (and I guess also the right combination of `stack`/`reset_index` would be able to mimic `pd.melt`?)

In the Stata camp there is just [reshape](http://www.stata.com/manuals13/dreshape.pdf) which takes an additional direction parameter (`wide` or `long`) and a list of stub names. `pd.wide_to_long` is really just solving the use case mentioned above (where R users have to go back to `reshape`) by mimicking the Stata approach. 

So in a "taxonomy of reshapes", `pd.wide_to_long` is just a special case of `pd.melt`, perhaps `pd.melt_stubs`? : P

**Comment by ResidentMario** [comment]
We didn't discuss `wide_to_long` in the lead-up to [PR#15521](https://github.com/pandas-dev/pandas/pull/15521). @jorisvandenbossche is there a consensus here that this ought to be done, but that the right method signature is still TBD?

**Comment by jreback** [comment]
closing this for #15521 was merged. We can discuss later what we are doing in `wide_to_long``
