### ISSUE TITLE
Create tests for reading compressed tables from S3 URLs

### ISSUE THREAD

**Issue by dhimmel** [pandas-dev/pandas#14875]
In https://github.com/pandas-dev/pandas/pull/14576, we consolidated compression code and expanded support for compressed URLs. While we added tests for compressed URLs, we did not add tests for compressed S3 files. First, someone will have to upload the compressed tables to Amazon: see https://github.com/pandas-dev/pandas/pull/14587#issuecomment-264674413.

Also tagging https://github.com/pandas-dev/pandas/issues/13137, a pull request which may want to also add these tests.

**Comment by TomAugspurger** [comment]
👍 I can add those in #13137.

**Comment by dhimmel** [comment]
@TomAugspurger great. I put the compressed URL tests in [`pandas/io/tests/parser/test_network.py`](https://github.com/pandas-dev/pandas/blob/b33a500120b63836d64f50c5f4e4504099160585/pandas/io/tests/parser/test_network.py#L19-L53). Adding the S3 tests there would probably not take too much additional code.

**Comment by mroeschke** [comment]
Looks like `test_network.py` has some tests that read S3 files that are compressed (gz and bz2), so I think that should suffice the spirit of this issue. Closing.
