### ISSUE TITLE
DEPR: change .astype(.., raise_on_error) -> errors

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#14878]
xref #14877 

this is inconsistent with our current API handling

so need to deprecate ``raise_on_error``, AFAICT, this is the only public use, and add
``errors='raise'|'ignore'``, with a default a ``raise``.

**Comment by m-charlton** [comment]
I can start to look at this one

**Comment by jreback** [comment]
sure, should be pretty straightforaward

**Comment by m-charlton** [comment]
I've noticed that the `DataFrame.where` method (`pandas/core/internals.py`) also
has a `raise_on_error` keyword argument. Should this be raised as a separate 
issue? I can get on with the changes to `astype`.

**Comment by jreback** [comment]
@m-charlton yes that would be fine (you can make an issue if you want to address later). if you want to put in the same PR that is ok too. (just indicate in the top-notes that 2 things are getting deprecated)

**Comment by m-charlton** [comment]
Thinking about it, I'l raise it as a separate issue and make the changes to `astype` first. That 
way, if I miss out anything on the deprecation of `raise_on_error` on `astype` I should not make the the same mistake on the second deprecation in the `where` method. When raising the new issue, I'll
link back to this one.
