### ISSUE TITLE
DataFrame constructor converts uint64 series to object series

### ISSUE THREAD

**Issue by hrichardlee** [pandas-dev/pandas#14881]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np

uint64s = pd.Series([9710005220884355087, 9710005220138399309], dtype=np.dtype('uint64'))
uint64s.dtype  # dtype('uint64')

df = pd.DataFrame({'viadict': uint64s})
df['viacolumn'] = uint64s

df.info()
# Data columns (total 2 columns):
# viadict      2 non-null object
# viacolumn    2 non-null uint64
```
#### Problem description
It seems like these ways of adding columns to a dataframe should have the same behavior.

#### Expected Output
```python
df.info()
# Data columns (total 2 columns):
# viadict      2 non-null uint64
# viacolumn    2 non-null uint64
```
(i.e. both columns are uint64s)

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 45 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
pandas: 0.18.1
nose: 1.3.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.1
numpy: 1.11.1
scipy: 0.18.0
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.4.1
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.6.1
blosc: None
bottleneck: None
tables: 3.2.2
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: None
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.2
lxml: None
bs4: 4.5.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.42.0
pandas_datareader: None
</details>

**Comment by chris-b1** [comment]
Yeah, uint64 support is generally spotty.  PR to fix welcome!

xref #14721, xref #4471
