### ISSUE TITLE
Incorrect index label displayed on MultiIndex DataFrame

### ISSUE THREAD

**Issue by fonnesbeck** [pandas-dev/pandas#14882]
I have a DataFrame with a hierarchical index as follows:

```python
MultiIndex(levels=[[30, 40, 50], [6, 12, 24], ['MRIgFUS', 'ablation', 'hysterectomy', 'iud', 'myomectomy', 'none', 'uae']],
           labels=[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2], [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6]],
           names=['age', 'followup', 'next intervention'])
```

Notice in particular the values of the first two levels, and that they are balanced in the labels. However, the display of the table is incorrect. Here is what it looks like:

![](http://d.pr/i/rFy8+)

Notice the second label of the first two levels of the hierarchical index are repeated (40 and 40 instead of 40 and 50, and 12 and 12 instead of 12 and 24).

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Darwin
OS-release: 16.3.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.19.1
nose: None
pip: 9.0.1
setuptools: 31.0.1
Cython: 0.25.2
numpy: 1.11.2
scipy: 0.18.1
statsmodels: None
xarray: None
IPython: 5.1.0
sphinx: 1.5.1
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: None
tables: None
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: None
xlrd: 1.0.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None
</details>

**Comment by fonnesbeck** [comment]
NB confirmed that this occurs in a build from the current master as well.

**Comment by fonnesbeck** [comment]
This issue disappears if I set `notebook_repr_html` to False. Does this make it a Jupyter issue?

![](http://d.pr/i/T09A+)

**Comment by TomAugspurger** [comment]
Probably a pandas issue.

I'm having trouble reproducing it with just

```python
from pandas import *

idx = MultiIndex(levels=[[30, 40, 50], [6, 12, 24], ['MRIgFUS', 'ablation', 'hysterectomy', 'iud', 'myomectomy', 'none', 'uae']],
           labels=[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2], [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6]],
           names=['age', 'followup', 'next intervention'])
df = pd.DataFrame({"A": 1}, index=idx)
df
```

I suspect it's related to the particular sorting of your index (do you have repr issues with `df.sort_index()`?) Could you maybe paste your `df.index.values.tolist()`?

**Comment by jorisvandenbossche** [comment]
It's a pandas bug (pandas creates the html that jupyter displays), and has probably something to do with the truncation code. Because when you set the number of rows higher `pd.options.display.max_rows = 100`, it displays correctly.

**Comment by Dr-Irv** [comment]
I'm attempting to chase this down. @jorisvandenbossche is correct.  It is the truncation code.
