### ISSUE TITLE
DOC : `build` isnt a valid argument to doc/make.py

### ISSUE THREAD

**Issue by rahulporuri** [pandas-dev/pandas#14897]
#### Code Sample, a copy-pastable example if possible

```
python make.py build
```

#### Problem description

the docs - http://pandas.pydata.org/pandas-docs/stable/contributing.html#building-the-documentation mention that in order to do a full clean build, we will have to do

```
python make.py clean
python.make.py build
```

but the `build` option doesn't seem to be supported, because running the command
raises the error

`Do not know how to handle build; valid args are ['all', 'latex', 'zip_html', 'latex_forced', 'upload_stable', 'build_pandas', 'upload_dev', 'upload_stable_pdf', 'upload_dev_pdf', 'auto_debug', 'html', 'clean', 'auto_dev']`

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Darwin
OS-release: 16.1.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.19.0
nose: None
pip: 9.0.1
setuptools: 23.1.0
Cython: None
numpy: 1.10.4
scipy: None
statsmodels: None
xarray: None
IPython: 4.1.2
sphinx: 1.4.1
patsy: None
dateutil: 2.5.2
pytz: 2016.3
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None
None
</details>

**Comment by jreback** [comment]
this is already fixed in #14890
