### ISSUE TITLE
DOC : setting dialect on pandas.read_table overrides a few other kwds

### ISSUE THREAD

**Issue by rahulporuri** [pandas-dev/pandas#14898]
#### Problem description

Correct me if I'm wrong but [TextFileReader](https://github.com/pandas-dev/pandas/blob/master/pandas/io/parsers.py#L691-L700) overwrites the `delimiter`, `quoting` etc kwds if the `dialect` kwarg is passed. But this isn't highlighted in the `pandas.read_table` documentation.

I don't know if this was implicit. Sorry for the noise if this is a known issue or if it isn't actually one.

**Comment by jreback** [comment]
can you give an example

**Comment by rahulporuri** [comment]
the data contained in the file `test_data_quoting.txt` is
```
1,False,1.0,"one",2015-01-01,"quote space"
2,True,2.0,"two",2015-01-02,noquote space
3,False,3.0,three,2015-01-03,"quote space"
4,True,4.0,four,2015-01-04,"escaped""quote"
```

and for an example of kwds being overridden - 

```python
In [24]: pandas.read_table('test_data_quoting.txt', header=None, delimiter=',', quotechar=None, quoting=csv.QUOTE_NONE)
Out[24]: 
   0      1    2      3           4                 5
0  1  False  1.0  "one"  2015-01-01     "quote space"
1  2   True  2.0  "two"  2015-01-02     noquote space
2  3  False  3.0  three  2015-01-03     "quote space"
3  4   True  4.0   four  2015-01-04  "escaped""quote"

In [25]: pandas.read_table('test_data_quoting.txt', header=None, delimiter=',', quotechar=None, quoting=csv.QUOTE_NONE, dialect='excel')
Out[25]: 
   0      1    2      3           4              5
0  1  False  1.0    one  2015-01-01    quote space
1  2   True  2.0    two  2015-01-02  noquote space
2  3  False  3.0  three  2015-01-03    quote space
3  4   True  4.0   four  2015-01-04  escaped"quote
```

Again, I'm not advocating to change the behavior or anything of those sorts. I just wanted to point out that I didn't find the behavior to have been documented.

**Comment by jreback** [comment]
hmm, ok though *maybe* we should raise / warn if these are not default parameters. That seems a bit unexpected.

cc @gfyoung 
@jorisvandenbossche 
?

**Comment by gfyoung** [comment]
I agree that behaviour should not be changed at this point but warn that we have conflicting options.  I sense that we may want to raise in the future though?

**Comment by jorisvandenbossche** [comment]
Mentioning this in the explanation of the keyword would also already be a start. Warning seems OK for me as well, not sure if raising is needed.
