### ISSUE TITLE
why pandas.expanding_max support adarray

### ISSUE THREAD

**Issue by wukaMM** [pandas-dev/pandas#14923]
#### Problem description
 I'm sorry, I'm a beginner with pandas.

In the document of 0.17.0, I found this,

pandas.expanding_max(arg, min_periods=1, freq=None, **kwargs)
arg : Series, DataFrame

It seems that expanding_max only support Series and DataFrame, but why it also works with adarray?

**Comment by TomAugspurger** [comment]
Python libraries will commonly use duck-typing instead of explicitly checking types.

Also `expand_max` is deprecated, so it's not worth updating the docs. You'll use `pd.Series(...).expanding().<method>` now.
