### ISSUE TITLE
pd.to_numeric(series, downcast='integer') does not prpoerly handle floats over 10,000

### ISSUE THREAD

**Issue by gryBox** [pandas-dev/pandas#14941]
Hi - I came across this issue in [stackoverflow ](http://stackoverflow.com/a/38983440/6041010)while testing pd.to_numeric()

> If all floats in column are over 10000 it loses precision and converts them to integers.

```
tst_df = pd.DataFrame({'colA':['a','b','c','a','z', 'q'],
                      'colB': pd.date_range(end=datetime.datetime.now() , periods=6),
                      'colC' : ['a1','b2','c3','a4','z5', 'q6'],
                      'colD': [10000.0, 20000, 3000, 40000.36, 50000, 50000.00]})

pd.to_numeric(tst_df['colD'],  downcast='integer')
```
![image](https://cloud.githubusercontent.com/assets/16763201/21388415/cc82243c-c741-11e6-9000-3eea48faa7ec.png)

This doesn't seem like the desired behavior.

**Comment by jreback** [comment]
so this is correct, it is effectively doing an ``.astype(int)``. though I suppose this is too aggressive and the downcast from float -> int should only succeed if they are actually equal.

@gfyoung thoughts

**Comment by gryBox** [comment]
Just so I am clear, this is the behavior expected? Not this?

```
tst_df = pd.DataFrame({'colA':['a','b','c','a','z', 'q'],
                      'colB': pd.date_range(end=datetime.datetime.now() , periods=6),
                      'colC' : ['a1','b2','c3','a4','z5', 'q6'],
                      'colD': [1000.0, 2000, 3000, 4000.36, 5000, 50000.00]})

pd.to_numeric(tst_df['colD'],  downcast='integer')
```
![image](https://cloud.githubusercontent.com/assets/16763201/21393444/11dd10d8-c75a-11e6-8f53-6b7abed54e93.png)

**Comment by jreback** [comment]
hmm, this looks buggy. if you want to have a look see inside and see what's going on would be great.

**Comment by gryBox** [comment]
@jreback  I will try - I am sort of new to this.  Is this the module I should be looking at?
[pandas/pandas/tools/util.py](https://github.com/pandas-dev/pandas/blob/5faf32a62b52912bc0c4a26622bfc3d72b5121ff/pandas/tools/util.py)

**Comment by jreback** [comment]
yes

**Comment by gfyoung** [comment]
@gryBox : First of all, thanks for pointing this out!  The bug traces <a href="https://github.com/pandas-dev/pandas/blob/5faf32a62b52912bc0c4a26622bfc3d72b5121ff/pandas/types/cast.py#L117">here</a>.You can see here yourself:
~~~python
>>> import numpy as np
>>>
>>> arr = [1000000]
>>> arr2 = [1000000.5]
>>>
>>> np.allclose(arr, arr2)  # This is what we do now
True
>>> np.allclose(arr, arr2, rtol=0)  # This is what we probably should do
False
~~~
I think if passing `rtol=0`, you should be able to patch this behavior.  It also explains why it breaks with large numbers (the numbers are so large `rtol` isn't small enough to indicate that they're not close).

**Comment by gryBox** [comment]
@gfyoung : The credit goes to [tworec](http://stackoverflow.com/users/3805131/tworec) at stack. 

Is there a reason why something like `np.is_integer(x)` can't be used?

**Comment by gfyoung** [comment]
@gryBox : I'm not sure there is such a method.  Also, `numpy` `dtype` checking is not 100% compatible with all of our `pandas` objects, hence we prefer to stay away from such methods.
