### ISSUE TITLE
BUG: maybe_convert_numeric fails with uint64

### ISSUE THREAD

**Issue by gfyoung** [pandas-dev/pandas#14982]
`master` at <a href="https://github.com/pandas-dev/pandas/commit/aba7d255a165bbc221be106839c59a876655c0c2">aba7d2</a>:
~~~python
>>> from pandas import lib, np
>>> arr = np.array([2**63], dtype=object)
>>> lib.maybe_convert_numeric(arr, set())
...
OverflowError: Python int too large to convert to C long
~~~
At first, I thought the patch would be similar to #14916, but there are several complications here:

* Handling an array with negative and `uint64` values: in `maybe_convert_objects`, we would just return `object` to avoid data truncation.  However, this function currently only returns numeric arrays.  And if we do decide to return non-numeric, should we then raise if `coerce_numeric=True` then?
* `uint64` has no convenient `na_value`, so what happens if a `uint64` is in `na_values`?

**Comment by jreback** [comment]
your two suggestions are fine

- a ``uint64`` array with negative values (or in ``na_values``) must be converted to ``object``.

so unfortunately ``maybe_convert_numeric`` gets more complicated :>
