### ISSUE TITLE
CLN/DEPR: Consistent naming for isnull, notnull, fillna, dropna

### ISSUE THREAD

**Issue by jpeacock29** [pandas-dev/pandas#15001]
In 2.0, these functions could be named more consistently, either all `*na` or `*null`. Or, to preserve backwards compatibility, `isna`, `notna`, `fillnull` and `dropnull` could be added as aliases. Either way, it would be helpful to take the guess work out of this.

Let me know if this is not the correct forum for such proposals.

**Comment by jorisvandenbossche** [comment]
If we add aliases, I would personally rather go for the *na ones instead of the adding the *null ones. Certainly if we are going to use NA as the universal missing value indicator for the different data types.

**Comment by wesm** [comment]
+1 to `isna` and `notna`. The null variants are quite ingrained -- I am neutral on deprecating/removing them

**Comment by sinhrks** [comment]
+1 for `na`, as some methods has args named `na_xxx`.
