### ISSUE TITLE
BUG: to_html misses truncation indicators (...) when index=False

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#15019]
When the html output is truncated (by using `mmax_rows=..`), you get `...` to indicate this, but not when using ``index=False``:

```python
df = pd.DataFrame(np.random.randn(5,2))
df.to_html(max_rows=4, index=False)
```

![screenshot from 2016-12-31 11-02-49](https://cloud.githubusercontent.com/assets/1020496/21576981/ecdd1b1a-cf48-11e6-85a9-a3cd50500cdc.png)

cc @TomAugspurger follow-up from #14999

**Comment by simonjayhawkins** [comment]
> to_html misses truncation indicators (...) when index=False

and when `index=True` and `max_rows=1` which is inconsistent with `max_cols=1` behavior:

![image](https://user-images.githubusercontent.com/13159005/45191109-4aa4e280-b239-11e8-9325-8dc696282efd.png)

**Comment by simonjayhawkins** [comment]
Reproducible code sample to use as test case:

#### Code Sample

```python
np.random.seed(seed=0)
df = pd.DataFrame(np.random.randn(5,2))
df.to_html(max_rows=4, index=False)
```

#### Output

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>0</th>
      <th>1</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1.764052</td>
      <td>0.400157</td>
    </tr>
    <tr>
      <td>0.978738</td>
      <td>2.240893</td>
    </tr>
    <tr>
      <td>0.950088</td>
      <td>-0.151357</td>
    </tr>
    <tr>
      <td>-0.103219</td>
      <td>0.410599</td>
    </tr>
  </tbody>
</table>

#### Expected Output

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>0</th>
      <th>1</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1.764052</td>
      <td>0.400157</td>
    </tr>
    <tr>
      <td>0.978738</td>
      <td>2.240893</td>
    </tr>
    <tr>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <td>0.950088</td>
      <td>-0.151357</td>
    </tr>
    <tr>
      <td>-0.103219</td>
      <td>0.410599</td>
    </tr>
  </tbody>
</table>
