### ISSUE TITLE
error in Cheat Sheet "pd." is "Pd."

### ISSUE THREAD

**Issue by hydrospanner** [pandas-dev/pandas#15017]
The [cheat sheet](https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf) refers to the panda module as "pd" (as in import pandas as pd), except in the table titled "Logic in Python (and pandas)", where it says "Pd.notnull(obj)". 

It probably got capitalized automatically.

**Comment by jreback** [comment]
can you do a PR to update?
