### ISSUE TITLE
Typing error in "ExcelFile class" example

### ISSUE THREAD

**Issue by ennemosc** [pandas-dev/pandas#15037]
Current example ExcelFile class [(see ExcelFile class pandas 0.19.2 documentation)](http://pandas.pydata.org/pandas-docs/stable/io.html#excelfile-class) :

> xlsx = pd.ExcelFile('path_to_file.xls)
> df = pd.read_excel(xlsx, 'Sheet1')

#### Problem description
The closing apostrophe is missing for 'path_to_file.xls'

#### Expected Output
xlsx = pd.ExcelFile('path_to_file.xls')
df = pd.read_excel(xlsx, 'Sheet1')

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en

pandas: 0.18.1
nose: 1.3.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.24.1
numpy: 1.11.3
scipy: 0.18.1
statsmodels: None
xarray: None
IPython: 5.1.0
sphinx: 1.5
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.10
blosc: None
bottleneck: 1.1.0
tables: 3.2.2
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.3
lxml: 3.6.4
bs4: 4.5.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.42.0
pandas_datareader: None

</details>

**Comment by jorisvandenbossche** [comment]
There is indeed a `'` missing. Want to do a PR to fix this?

**Comment by ennemosc** [comment]
Would be my first PR, I'm perfectly fine with contributing to the pandas community :-)
