### ISSUE TITLE
ERR: all nan grouping provides unfriendly error message

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15036]
https://github.com/pandas-dev/pandas/pull/14649/files#r94330188

This seems unfriendly, should instead b a ``DataError``
```
In [8]: s = Series([1,2,3],[np.nan,np.nan,np.nan])

In [9]: s.groupby(s.index).sum()
TypeError: unhashable type: 'Float64Index'
```

**Comment by Shekharrajak** [comment]
@jreback , what should be the output? I want to work on it.

**Comment by jreback** [comment]
actually on second thought this should just be s grouper that is empty (we skip all nan groups);
so if u fix the grouping it should just work

**Comment by Shekharrajak** [comment]
Thanks @jreback , I am trying.

**Comment by mroeschke** [comment]
I think this returns a reasonable output now (all groups are dropped). Could use a test

```
In [43]: s.groupby(s.index).sum()
Out[43]: Series([], dtype: int64)

In [44]: pd.__version__
Out[44]: '1.3.0.dev0+1485.g6abb567cb1'
```
