### ISSUE TITLE
Treat Series as 1-column dataframe in concat with dataframe

### ISSUE THREAD

**Issue by jcrist** [pandas-dev/pandas#15047]
When concatenating a dataframe and series along axis 1, [the docs](http://pandas.pydata.org/pandas-docs/stable/merging.html#concatenating-with-mixed-ndims) indicate that the series will be treated as a series with a single column matching the column name. Based on this, I'd expect similar behavior (or an error) when concatenating a named series with a dataframe along axis 0. However, this seems to result in a new numeric column for the named series instead of converting the series to a dataframe:

```python
In [10]: pd.__version__
Out[10]: '0.19.1'

In [11]: df = pd.DataFrame({'x': range(5), 'y': range(5), 'z': range(5)})

In [12]: pd.concat([df, df.x])
Out[12]:
     x    y    z    0
0  0.0  0.0  0.0  NaN
1  1.0  1.0  1.0  NaN
2  2.0  2.0  2.0  NaN
3  3.0  3.0  3.0  NaN
4  4.0  4.0  4.0  NaN
0  NaN  NaN  NaN  0.0
1  NaN  NaN  NaN  1.0
2  NaN  NaN  NaN  2.0
3  NaN  NaN  NaN  3.0
4  NaN  NaN  NaN  4.0

In [13]: pd.concat([df, df.x.to_frame()])
Out[13]:
   x    y    z
0  0  0.0  0.0
1  1  1.0  1.0
2  2  2.0  2.0
3  3  3.0  3.0
4  4  4.0  4.0
0  0  NaN  NaN
1  1  NaN  NaN
2  2  NaN  NaN
3  3  NaN  NaN
4  4  NaN  NaN
```

I'd expect either an error, or the behavior in out[13].

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/blob/master/pandas/tools/merge.py#L1580 is the reason this ends up 0, but I don't remember why that is.

Will mark this as a bug.

**Comment by sinhrks** [comment]
+1 for resulting in out[13] rather than error.

**Comment by jcrist** [comment]
Looks like with a recent commit, the line got bumped. Here's a [commit specific link](https://github.com/pandas-dev/pandas/blob/7c0b4a30f243dabec87015a3b457a79ba1d1091d/pandas/tools/merge.py#L1711)

Looking at the current logic (and trying it out), it seems that this is definitely a bug instead of a difference in expectations - since the series is always interpreted as a frame with name `0`, you get really unexpected behavior if there's a column also named `0`:

```python
In [23]: df = pd.DataFrame({'x': range(5), 'y': range(5), 0: range(5)})

In [24]: pd.concat([df, df.x])
/Users/jcrist/anaconda/envs/dask/lib/python3.5/site-packages/pandas/indexes/api.py:71: RuntimeWarning: unorderable types: str() > int(), sort order is undefined for incomparable objects
  result = result.union(other)
Out[24]:
     x  0    y
0  0.0  0  0.0
1  1.0  1  1.0
2  2.0  2  2.0
3  3.0  3  3.0
4  4.0  4  4.0
0  NaN  0  NaN
1  NaN  1  NaN
2  NaN  2  NaN
3  NaN  3  NaN
4  NaN  4  NaN
```

**Comment by sinhrks** [comment]
Looked into a little, and found current behavior is to replace empty ``Series`` name with number when ``concat(axis=1)``. Will send a PR to fix keeping current ``axis=1`` behavior.

- https://github.com/pandas-dev/pandas/blob/master/pandas/tools/tests/test_concat.py#L1253
