### ISSUE TITLE
weird Pandas version name after update with anaconda?

### ISSUE THREAD

**Issue by randomgambit** [pandas-dev/pandas#15061]
Hello there,

Happy new year! Just updated my `pandas` package using `anaconda` (`conda update --all`) and `pd.__version__ ` gives:
 `u'0.19.2+0.g825876c.dirty'`

```
pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: None.None

pandas: 0.19.2+0.g825876c.dirty
nose: 1.3.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.11.2
scipy: 0.18.1
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.5.1
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: 1.1.0
tables: 3.2.2
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: 2.4.0
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.6
lxml: 3.7.0
bs4: 4.5.3
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.1.4
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.45.0
pandas_datareader: None
```

Is that expected/normal?

**Comment by jorisvandenbossche** [comment]
This is not how it should be, however, we don't control the anaconda package. Can you report this at: https://github.com/continuumIO/anaconda-issues/issues

(package from the conda-forge channels seems to have a correct version number)

**Comment by randomgambit** [comment]
@jorisvandenbossche just a follow up. that was indeed a bug in anaconda and this has been fixed https://github.com/ContinuumIO/anaconda-issues/issues/1328
