### ISSUE TITLE
i have a problem with installing some packages on my pycharm

### ISSUE THREAD

**Issue by arionarvan** [pandas-dev/pandas#15103]
#

```python
  ###
```
#### Problem description
Hi.
i have a problem with installing some packages on my pycharm.
when i try to install a package for example "Pandas",on my pycharm,i got this error:
_RuntimeError: Broken toolchain: cannot link a simple C program_
i'm an amateur with programming,and i couldn't fix it for a week!
can you please help me and tell me what should i do?
i appreciate that,i search all internet for solution,but i can't find it.
thank you and eexcuse me for my bad english.
and i should say my pip is updated i guess!
i upload the screen shot of error:
![untitled](https://cloud.githubusercontent.com/assets/25045121/21830851/f780b5c6-d7b4-11e6-9507-b87c492ce09e.jpg)

</details>
proposed solution from program:
Try to run this command from the system terminal. Make sure that you use the correct version of 'pip' installed for your Python interpreter located at 'C:\Users\Arien Lupin\AppData\Local\Programs\Python\Python36-32\python.exe'.

**Comment by TomAugspurger** [comment]
You have two options:

1. [Download and install Anaconda](http://pandas.pydata.org/pandas-docs/stable/install.html#installing-pandas-with-anaconda) and then point pycharm to it
2. Upgrade your version of pip `pip install -U pip`. Recent versions of pip should find wheels, which don't require a C complier. Then reinstall NumPy and pandas.

**Comment by vivekf103** [comment]
$ sudo apt install python-xlib python-tk
$ pip install Image
$ pip install python-xlib
$ pip install Image
$ pip install pyautogui


FIrst you have to install all these dependencies then install 'pyautogui' in pycharm.
This work for me.
change pip to pip3 if you use pip3.

**Comment by leixiayang** [comment]
遇到了同样的错误，还是无法解决

**Comment by gurkay** [comment]
> $ sudo apt install python-xlib python-tk
> $ pip install Image
> $ pip install python-xlib
> $ pip install Image
> $ pip install pyautogui
> 
> FIrst you have to install all these dependencies then install 'pyautogui' in pycharm.
> This work for me.
> change pip to pip3 if you use pip3.

Perfect you man

**Comment by zeezee84** [comment]
Hi,
1. Install Anaconda and Update
2. On PyCharm  go to  File --> Settings --> Project Interpreter
3. from the left top corner click setting button and from dropdown select "Add"
4. ON new (Add Python Interpreter) window click Conda Enviroment --> Existing enviroment --> OK
5.  Then go back to Project Interpreter page and select Python Interpreter you created now(something like this:  Python3.7(blah blah blah ) C:\ Program Data\Anaconda3\......\....\...\.....
6. Then you will see Packages List. On the right handside click  "+"   and search for pandas.
7. Click install package

**Comment by kashave** [comment]
its working, thanks

**Comment by Hardmat** [comment]
> Hi,
> 
> 1. Install Anaconda and Update
> 2. On PyCharm  go to  File --> Settings --> Project Interpreter
> 3. from the right top corner click setting button and from dropdown select "Add"
> 4. ON new (Add Python Interpreter) window click Conda Enviroment --> Existing enviroment --> OK
> 5. Then go back to Project Interpreter page and select Python Interpreter you created now(something like this:  Python3.7(blah blah blah ) C:\ Program Data\Anaconda3..................
> 6. Then you will see Packages List. On the right handside click  "+"   and search for pandas.
> 7. Click install package

It has also work, thanks for your help @zeezee84

**Comment by sammy0231** [comment]
Hello,

> 1. Anaconda

is it mandatory to install anaconda?
because in python udemy course anaconda is not available .

and now I already installed all the package and pip latest version but still getting issue
![selenium by python](https://user-images.githubusercontent.com/63258257/78593330-16096a80-7864-11ea-8a5a-b14180b0290d.PNG)

kindly suggest me

**Comment by kashave** [comment]
@sammy0231
its mandatory to install Anaconda, otherwise pycharm will not work and follow the same step as above

**Comment by sammy0231** [comment]
ok

**Comment by sammy0231** [comment]
> @sammy0231
> its mandatory to install Anaconda, otherwise pycharm will not work and follow the same step as above

![image](https://user-images.githubusercontent.com/63258257/78665314-3df3df00-78f3-11ea-8b5f-08b91784d833.png)

done all the steps still getting same issue,

could you please review the screen and let me know if you got any issue.

check project path also.

what is missing from my end

**Comment by kashave** [comment]
project path is correct, after install please restart machine.
and for check correct working, please import  for testing purpose like

import numpy as np

X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
print(X)
y = np.array([1, 2, 3, 4])
print(y)

 and please check setting for correctly pointing

![Capture](https://user-images.githubusercontent.com/19545910/78668652-a98c7b00-78f8-11ea-97c3-9e9ee7d47df8.PNG)

**Comment by Melikadastranj** [comment]
> @sammy0231
> its mandatory to install Anaconda, otherwise pycharm will not work and follow the same step as above

No its not mandatory!
