### ISSUE TITLE
Pandas contains shebang pointing to /usr/bin/python which are problematic

### ISSUE THREAD

**Issue by ssalonen** [pandas-dev/pandas#15131]
#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

We are packaging pandas pre-installed in a virtualenv using a rpm. RPM has a "convenient" feature to automatically scan for script files with shebang and adding those as requirements of the resulting rpm. For more information, see [this blog post](http://www.legendiary.at/2013/03/20/rpmbuild-shebang-auto-required-packages/).

Most of the pandas scripts use

````bash
#!/usr/bin/env python
````

which rpm resolves to whatever is in the PATH.

However, some of the packages point to hard-coded path of python:
````bash
$ grep '^#!' **/*.py|grep -v '/usr/bin/env python'
pandas/tests/test_config.py:#!/usr/bin/python
pandas/tests/test_testing.py:#!/usr/bin/python
````

#### Proposed solution

I would propose that the above scripts would be changed to use `#!/usr/bin/env python`.

This change would make the rpm process resolve python and bash using whatever is in the path. For example, with CentOS 6, the system python (in `/usr/bin/python`) is python 2.6, although the `python` in PATH could very well be `python2.7` or newer. In our case the virtualenv is activated during the build, and thus `#!/usr/bin/env python` would resolve to the correct interpreter.

The additional benefit is that the scripts are more cross-platform.

I'm willing to submit a pull requests if you agree with the fix?

Numpy issue regarding the same matter: https://github.com/numpy/numpy/issues/8472
Scipy issue regarding the same matter: https://github.com/scipy/scipy/issues/6961

**Comment by jreback** [comment]
not sure I understand. These are all dev scripts, nothing is public.

**Comment by ssalonen** [comment]
Thanks for the reply!

I understand that these are just for development, and not meant to be called by end users.

Perhaps I need to open up the rpm packaging to give insight to the issue:

The rpm packaging we do is conceptually the same as [dh-virtualenv](http://dh-virtualenv.readthedocs.io/en/latest/) automates for debian systems. To put it simply, during the package build, a virtualenv is made with all the necessary packages, then packaged in a rpm. On install time the virtualenv is simply extracted to the define locations.

Since all test modules are installed as part normal pandas installation they will be incorporated inside the virtualenv. By default, the rpm macros scan for all script files inside the rpm (i.e. virtualenv) for shebangs, and add those binaries as rpm requirements for the resulting rpm.

In CentOS6 the `/usr/bin/python` gets resolved to python 2.6, even though the python in path points to something newer. Having the shebang lines pointing to `/usr/bin/env python` resolves the issue in our case.

Furthermore, I think it is good convention any way to use the `python` in PATH, for developers using virtualenv, for example.

One option would be to remove shebangs completely from test_modules, something that was proposed by member of scipy project -- in the end, wouldn't the test be run using nose/py.test whatever instead of calling them directly by the developer. But I leave this decision for you.

Please note that this proposed fix aligns the shebangs files in pandas -- majority of them are using `/usr/bin/env python` already:

````bash
# in site-packages/pandas 
$ grep '^#!' **/*.py
computation/eval.py:#!/usr/bin/env python
computation/tests/test_compat.py:#!/usr/bin/env python
computation/tests/test_eval.py:#!/usr/bin/env python
tests/plotting/common.py:#!/usr/bin/env python
tests/plotting/test_boxplot_method.py:#!/usr/bin/env python
tests/plotting/test_frame.py:#!/usr/bin/env python
tests/plotting/test_groupby.py:#!/usr/bin/env python
tests/plotting/test_hist_method.py:#!/usr/bin/env python
tests/plotting/test_misc.py:#!/usr/bin/env python
tests/plotting/test_series.py:#!/usr/bin/env python
tests/test_config.py:#!/usr/bin/python
tests/test_msgpack/test_buffer.py:#!/usr/bin/env python
tests/test_msgpack/test_case.py:#!/usr/bin/env python
tests/test_msgpack/test_except.py:#!/usr/bin/env python
tests/test_msgpack/test_format.py:#!/usr/bin/env python
tests/test_msgpack/test_limits.py:#!/usr/bin/env python
tests/test_msgpack/test_pack.py:#!/usr/bin/env python
tests/test_msgpack/test_seq.py:#!/usr/bin/env python
tests/test_msgpack/test_sequnpack.py:#!/usr/bin/env python
tests/test_msgpack/test_subtype.py:#!/usr/bin/env python
tests/test_testing.py:#!/usr/bin/python
````

Best,
Sami

**Comment by jorisvandenbossche** [comment]
@ssalonen You can just open a PR to change this, no problem (or even just remove the line, that would be fine as well). Those lines don't really serve a purpose as you typically don't execute the files in itself.

**Comment by ssalonen** [comment]
Thanks. Pull request submitted with shebangs removed from test modules.
