### ISSUE TITLE
Timedelta to_json with date_format='iso'

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#15137]
Is this formatting for timdelta columns intended / correct?

```python
In [12]: df = pd.DataFrame({"A": pd.date_range("2016", periods=4, freq='D'),
    ...:                    "B": pd.timedelta_range('1D', periods=4, freq='D')})

In [13]: df.to_json(date_format='iso')
Out[13]: '{"A":{"0":"2016-01-01T00:00:00.000Z","1":"2016-01-02T00:00:00.000Z","2":"2016-01-03T00:00:00.000Z","3":"2016-01-04T00:00:00.000Z"},"B":{"0":"1970-01-02T00:00:00.000Z","1":"1970-01-03T00:00:00.000Z","2":"1970-01-04T00:00:00.000Z","3":"1970-01-05T00:00:00.000Z"}}'
```

So a `pd.Timedelta('1D')` goes to `"1970-01-02T00:00:00.000Z"`.

The expected might be a [duration](https://en.wikipedia.org/wiki/ISO_8601#Durations) like

`"P1DT0H0M0S"`.

It seems to be reusing the logic for datetime columns and treating it as the equivalent int -> iso format. Ideally `to_json` will have a new paramater `timedelta_format` that takes the same values as `date_format`.

**Comment by TomAugspurger** [comment]
xref https://github.com/pandas-dev/pandas/pull/15136 and https://github.com/pandas-dev/pandas/pull/14904

I can work on this, if we determine that it should be changed.

**Comment by jreback** [comment]
yes this is probably unsupported you can pass a default_handler to deal with it, though prob better do it in the c-code.

**Comment by TomAugspurger** [comment]
I'm gonna attempt to do it in `objToJSON.c`, we'll see how that goes 😆

**Comment by jreback** [comment]
yeah looks like its the ``iso`` code :>

**Comment by ron819** [comment]
@TomAugspurger  any progress with this?

**Comment by jreback** [comment]
@ron819 why don’t you do a pull request for this? we have thousands of issues and very few core devs, who mostly do code review

**Comment by mroeschke** [comment]
Looks like this is solved on master by by: https://github.com/pandas-dev/pandas/pull/30903
