### ISSUE TITLE
DEPR: DeprecationWarning -> FutureWarning

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15152]
- [x] ``.ix`` #15113 (#26438) 
- [ ] ~~``.isnull/.notnull`` #16972 ``~~

Move to #6581 when converted to `FutureWarning`

**Comment by TomAugspurger** [comment]
FYI, thanks to https://github.com/statsmodels/statsmodels/pull/3525, statsmodels will be`.ix`-free in their next release.

**Comment by jreback** [comment]
think we ought to do this for 0.23? (``.ix``)

**Comment by jorisvandenbossche** [comment]
The other one, `isnull` / `notnull`, is actually not even deprecated, so the change of deprecationwarning -> FutureWarning is not even relevant there.

**Comment by jreback** [comment]
yep, will just remove them; I think we could always open a new issue IF we should remove them (but I think prob ok to just leave as an alias).
