### ISSUE TITLE
CI: invalidate cache when .pxi.in only changes

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15154]
In the following, *only* the ``.pxi.in`` were changed and ``setup.py`` correctly has dependencies on these, so local building is fine. However, on travis, the cython cache does not seem to be invalidation (and I had to resort to manually clearing it).

similar to my comment: https://github.com/pandas-dev/pandas/pull/14937#issuecomment-273270706

happened again on merging: #15139, see: https://travis-ci.org/pandas-dev/pandas/jobs/193092807

**Comment by jreback** [comment]
any ideas

cc @gfyoung 
@chris-b1

**Comment by chris-b1** [comment]
It's probably the same solution from https://github.com/pandas-dev/pandas/pull/14363 (which was `pxd`) - adding `pyx.in` to those ci scripts.

**Comment by jreback** [comment]
ahh that makes sense.

**Comment by gfyoung** [comment]
I wonder if you could log the timestamps and see what Travis is getting on the files. We have the logic to update those files in the setup, but it's not firing.
