### ISSUE TITLE
to_sql & cx_oracle

### ISSUE THREAD

**Issue by jmbertoncelli** [pandas-dev/pandas#15168]
Hello,

I am having the following error:

<type 'exceptions.TypeError'>
('expecting string, unicode or buffer object',)
expecting string, unicode or buffer object

but the issue is that this error occur only when the 'chunksize' is greater than 1.  I did try different value for this parameter without success.  Let me know how I can help solving this issue.  Last but not least it looks like that is linked with one of the recent libraries update... was working just fine before 1 or 2 weeks ago.

thanks in advance.

JM

**Comment by jreback** [comment]
you would need to show a reproducible example.

**Comment by jmbertoncelli** [comment]
Running it require an Oracle back end... the code is :

engine = create_engine(url,coerce_to_unicode=False,echo=False) # restart the engine
rs = engine.execute("DROP TABLE {0}".format(table))
df.to_sql(table,engine,schema=schema,if_exists='replace',index=False,chunksize=1,dtype=otypes)

I do not see how I could provide you with something that could be used to debug... I could provide the full Dataframe data as well as the dtypes if this could help.

let me know what do you need.

JM

**Comment by jreback** [comment]
@jmbertoncelli this almost certainly is a configuration issue on your side.

you can certainly ``pd.show_versions()`` and ``df.dtypes``, but in my experience that is the issue.

**Comment by jorisvandenbossche** [comment]
Does the error depend on the `coerce_to_unicode=False` you passed to engine?

But it would indeed be useful to see `pd.show_versions()` and the dataframe you are using.

See also http://docs.sqlalchemy.org/en/latest/dialects/oracle.html#unicode

**Comment by jorisvandenbossche** [comment]
@jmbertoncelli Closing this as we need more information to help or to see if there is a bug. But certainly still post more info! Then I will reopen.
