### ISSUE TITLE
to_excel should (optionally) freeze panes

### ISSUE THREAD

**Issue by jnothman** [pandas-dev/pandas#15160]
`DataFrame.to_excel()` is currently helpful in styling column and row headers distinctly from values. One other simple feature Excel provides to manage headers is "freeze panes". Panes can be frozen such that the column and row headers are fixed. This is achieved in openpyxl with `worksheet.freeze_panes = top_left_value_cell` and in xlwt with `worksheet.freeze_panes(bottommost_header_row, leftmost_header_col)`.

I think making this available, as an option or by default, would give a valuable usability boost to the exported Excel spreadsheets.

**Comment by jreback** [comment]
sure *lots* of thinks that pandas could do with the updates in the openpyxl style API. love to have PR's!

**Comment by chris-b1** [comment]
Here's the same for `xlsxwriter`.  My preference would be not have it as a default, but agree it would be a nice addition.

http://xlsxwriter.readthedocs.io/example_panes.html

**Comment by jnothman** [comment]
The other header display feature that might be woeth having as an option is
an AutoFilter.

**Comment by jnothman** [comment]
yay! thanks
