### ISSUE TITLE
bound method NDFrame: df.sample(n=ExpectedSize) returns df.size!=ExpectedSize

### ISSUE THREAD

**Issue by codingyourlife** [pandas-dev/pandas#15174]
I have this code (see screenshot for it's output)
```
#prerequisite: var X_first_neutral_data gets filled via csv read
print("got a var of type: " + str(type(X_first_neutral_data)) + " that I want to take 10 samples from")
print("size before: " + str(X_first_neutral_data.size))
X_first_neutral_data_less_data=X_first_neutral_data.sample(n=10)
print("size should be 10 now, right?!?! -> " + str(X_first_neutral_data_less_data.size))
print("original var still same: " + str(X_first_neutral_data_less_data.size))

print()

print(X_first_neutral_data.head)
```

#### Problem description
Type of variable is pandas.core.frame.DataFrame calling myvar=myvar.sample(n=10) does change the size of the variable but not to 10.
I don't think that my code is wrong because this code works as expected:

```
df=pd.DataFrame()
df=pd.DataFrame(np.random.randint(0,100,size=(10, 7)), columns=list('ABCDEFG'))
print(type(df))
print(df)
df=df.sample(3)
print(df)
```

Documentation of sample [here](http://pandas.pydata.org/pandas-docs/version/0.19.2/generated/pandas.DataFrame.sample.html) states:
n = Number of items from axis to return. Cannot be used with frac. Default = 1 if frac = None.

#### Expected Output
![pandasproblem](https://cloud.githubusercontent.com/assets/10122382/22130340/a130067e-deab-11e6-8e69-4e594d12080e.png)

I have the newest pandas version: pandas-0.19.2

Am I missing something or is this a bug?

**Comment by jreback** [comment]
pls show a reproducible example in code that can. be copy pasted

**Comment by codingyourlife** [comment]
Damn I confused size with len(df.index). Everything is working now
