### ISSUE TITLE
ENH: Display options for Decimal objects.

### ISSUE THREAD

**Issue by pmav99** [pandas-dev/pandas#15171]
This is a feature request

#### Code Sample, a copy-pastable example if possible

```python
import decimal 
import pandas as pd

pd.set_option('display.precision', 3)
ctx = decimal.getcontext()

def D(number):
    return ctx.create_decimal(str(number))

df = pd.DataFrame({
    "decimals": [D(1/9), D(1/11), D(1/13)],
    "floats": [1/9, 1/11, 1/13]
})
df.head()

```
#### Problem description

You cannot easily set the display options for `Decimal` objects. If you have lots of Decimal columns and you are working interactively, this can quickly get annoying.

#### Expected Output

IMHO at the very least, we should be able to set the display precision. Ideally we should be able to use a callable similar to `float_format`. If that is the case, we should then be able to use custom formatters like e.g. [moneyfmt](https://docs.python.org/3.6/library/decimal.html#recipes).

If no specific options for `Decimal` objects are present, I think that it makes sense to fall back to the float options. If that is not acceptable, I think that at least adhering to the precision option is reasonable.

#### Output of ``pd.show_versions()``

<details>INSTALLED VERSIONS
------------------
commit: None
python: 3.6.0.final.0
python-bits: 64
OS: Linux
OS-release: 4.8.13-1-ARCH
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.19.2
nose: None
pip: 9.0.1
setuptools: 33.1.1
Cython: None
numpy: 1.12.0
scipy: 0.18.1
statsmodels: None
xarray: None
IPython: 5.1.0
sphinx: None
patsy: None
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 2.0.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.9999999
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.4
boto: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
``Decimal`` in general are not very well supported as a dtype; they are purely ``object`` dtype, and thus pretty second-class. This would take some effort to even support inference at display time.  So if you want to propose a patch, by all means, but in this would take a champion to provide anything more than trivial support.

Furthermore ``Decimal`` is completely non-performant, so generally using this is not recommeded. I get that there are *some* cases where this is necessary, so as I say, patches are welcome.

**Comment by mroeschke** [comment]
It appears that there isn't much appetite from the pandas team or community for this feature. Thanks for your suggestion, but happy to reopen this issue if there's more community interest
