### ISSUE TITLE
BLD: numpy-dev causing some issues

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15199]
https://travis-ci.org/pandas-dev/pandas/jobs/194558937

https://github.com/numpy/numpy/pull/8279 was just merged, which broke our tests 

:>

**Comment by jreback** [comment]
cc @jcrist

**Comment by jcrist** [comment]
Looks like the issue is this line: https://github.com/pandas-dev/pandas/blob/master/pandas/core/ops.py#L453.

Before that numpy PR, that would always evaluate `lib.infer_dtype`, since `bool(scalar_dtype)` was always False.

**Comment by jreback** [comment]
yep, going to put a patch in shortly.
