### ISSUE TITLE
`lines` kwarg in `pd.read_json`

### ISSUE THREAD

**Issue by daviddliu** [pandas-dev/pandas#15194]
#### Code Sample, a copy-pastable example if possible

```python
    with open("clean.json", "r+") as data:
        df = pd.read_json(path_or_buf=data, lines=True)
```
#### Problem description

In the documentation, `lines` is a kwarg that can be used to specify whether the JSON file has multiple lines. This code worked a month ago, where `df` was a dataframe where each entry was a line of `clean.json`.

#### Output

Instead, I get `TypeError: read_json() got an unexpected keyword argument 'lines'`

**Comment by jreback** [comment]
you should check your version of pandas, lines was added in 0.19.0, I would guess that you now using an older version.

further you can simply use ``pd.read_json(path, lines=True)``, no need to open the file.
