### ISSUE TITLE
ENH: Allow elementwise coloring in background_gradient with axis=None

### ISSUE THREAD

**Issue by dhirschfeld** [pandas-dev/pandas#15204]
At present the axis argument to `background_gradient` only accepts 0 or 1 so that the resulting "heatmap" can only be applied columnwise or rowwise rather than to the whole table.
```
Signature: df.style.background_gradient(cmap='PuBu', low=0, high=0, axis=0, subset=None)

Parameters
----------
cmap: str or colormap
    matplotlib colormap
low, high: float
    compress the range by these values.
axis: int or str
    1 or 'columns' for colunwise, 0 or 'index' for rowwise
subset: IndexSlice
    a valid slice for ``data`` to limit the style application to
```
I propose that `axis=None` be allowed to mean applying a color gradient elementwise.

**Comment by dhirschfeld** [comment]
```
df = pd.DataFrame(np.sqrt((np.mgrid[0:11, 0:11]**2).sum(axis=0)))
```
Example of `axis=0` coloring whereas I would like the color gradient to be radially increasing like the numbers
![image](https://cloud.githubusercontent.com/assets/881019/22235047/960ec6c2-e248-11e6-940f-e37ebfb9d0df.png)

**Comment by dhirschfeld** [comment]
Note: This would be consistent with the axis argument to `apply`:
![image](https://cloud.githubusercontent.com/assets/881019/22235094/19078e6a-e249-11e6-9d7c-e3c0f199f8ac.png)

**Comment by dhirschfeld** [comment]
My workaround:
```python
def background_gradient(df, cvals=None, cmin=None, cmax=None, cmap='viridis', **css):
    from matplotlib.colors import rgb2hex
    if cvals is None:
        cvals = df.values.ravel().copy()
    else:
        assert cvals.shape == df.shape
        cvals = cvals.values.ravel().copy()
    cvals -= cmin or cvals.min()
    cvals /= cmax or cvals.max()
    styles = []
    for rgb in cm.viridis_r(cvals):
        style = [
            "{}: {}".format(key, value)
            for key, value in css.items()
        ]
        style.append("background-color: {}".format(rgb2hex(rgb)))
        styles.append('; '.join(style))
    styles = np.asarray(styles).reshape(df.shape)
    return pd.DataFrame(styles, index=df.index, columns=df.columns)
```
![image](https://cloud.githubusercontent.com/assets/881019/22238182/cddb49aa-e25b-11e6-88e3-eec420793280.png)

**Comment by jorisvandenbossche** [comment]
Sounds logical, PR certainly welcome I think! 
cc @TomAugspurger

**Comment by TomAugspurger** [comment]
Yep, that's be great if you could submit a PR.

**Comment by jreback** [comment]
this should be fairly generalized i think, iow where we accept axis

**Comment by jorisvandenbossche** [comment]
@dhirschfeld Interested to do a PR for this? (I also stumbled into a case where I would need this)

BTW, your ability to specify a vmin/vmax is also a nice feature I think.

**Comment by dhirschfeld** [comment]
@jorisvandenbossche  - I'd like to finish it up by submitting a PR but it's unlikely I'll have time in at least the next couple of weeks so I'd be happy for anyone else interested to pick it up. In the interim, my implementation posted above is available for anyone who finds it...

I  had a need to explicitly specify the cmin/cmax values so I implemented that directly rather than the high/low compression. I also thought the `**css` made for a very usable interactive api but concede that a case could be made that it was *too magic*
