### ISSUE TITLE
DEPS: drop numpy < 1.9

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15206]
this would provide some code cleanup possibilities. 

- [ ] use ``np.full`` (see https://github.com/pandas-dev/pandas/pull/17000 for example)

**Comment by jreback** [comment]
cc @shoyer 
cc @njsmith
cc @charris
cc @wesm

**Comment by tacaswell** [comment]
That seems a bit aggressive, mpl supports back to 1.7.1.

**Comment by wesm** [comment]
I don't have a problem with this. Upgrading NumPy is not as much of a hardship nowadays as it used to be.

**Comment by njsmith** [comment]
I think from the numpy perspective this can only be a good thing. We'd much
rather people be using the latest and greatest rather than carrying around
compatibility hacks.

**Comment by bashtage** [comment]
I'm not sure there are lots of gains from dropping NumPy 1.9.  1.7 and 1.8 probably do have some meaningful workarounds.

**Comment by jreback** [comment]
revising to 1.9, which should give us good gains from 1.7/1.8 compat, but still allow mpl 1.4.3 support.
