### ISSUE TITLE
DEPS: drop numexpr < 2.4.6

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15213]
since 2.4.4 is specifically exluded because of some multi-threading issues, this eliminates the pandas checks for this (as well as some compat code for earlier versions of numexpr).

**Comment by jreback** [comment]
cc @FrancescAlted

**Comment by FrancescAlted** [comment]
Yep.  I strongly suggest that to use newest 2.6.2 version that I just released.  It fixes several issues and adds initial support for the POWER architecture.  I can provide a PR for this.
