### ISSUE TITLE
Inconsistent behavior of loc and iloc for MultiIndex

### ISSUE THREAD

**Issue by kordek** [pandas-dev/pandas#15228]
```python
panel = pd.util.testing.makePanel(nper=2).to_frame()
panel.loc['2000-01-03']
panel.iloc[0]
```
#### Problem description
iloc returns only first row of the DataFrame, so it does not allow taking advantage of the multiple index levels.

#### Expected Output
I would expect iloc[0] to return all the elements that share the first value of the 0-level of the MultiIndex

**Comment by jreback** [comment]
no, ``.iloc`` is a strict positional indexer, it does not regard the structure at all, only the first actual behavior. OTOH, ``.loc`` *does* take into account the level behavior.
