### ISSUE TITLE
pandas.io.gbq.to_gbq creates duplicate rows, pandas==0.19.2

### ISSUE THREAD

**Issue by existeundelta** [pandas-dev/pandas#15236]
```python
df.to_gbq(data, dataset, chunksize=10000, verbose=False, reauth=False, if_exists='append', private_key=private_key)
```
#### Problem description
We only insert DataFrame one time
It seems is in insert because we also see duplicates in Bigquery WebUIConsole 
can be related with [https://github.com/pandas-dev/pandas/issues/5840](https://github.com/pandas-dev/pandas/issues/5840)?
<details>
pandas==0.19.2
</details>

**Comment by jreback** [comment]
w/o a reproducible example this is not useful

if you would like to add an example great
