### ISSUE TITLE
API: to_series/to_frame Index methods

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15230]
xref https://github.com/pandas-dev/pandas/pull/15216#issuecomment-275240736

``Index.to_series()``
``MultiIndex.to_frame()``

should we harmonize? (e.g. make both available to both? for compat), leave it like this?

should also prob add the ``index=True`` kw to ``.to_series()`` for compat.

**Comment by gfyoung** [comment]
I don't see why we shouldn't harmonize API.  It makes it easier to use (obviously, the behavior will be different but at least the functions can be called).

**Comment by jreback** [comment]
@gfyoung feel like diving in on these? (we may need to deprecate some things).

**Comment by gfyoung** [comment]
@jreback : Just going through the backlog here and finally got to this.  For starters, `MultiIndex.to_series` already exists thanks to inheritance with `Index`.  Thus, I don't see why we wouldn't want to have `to_frame()` for consistency for `Index`.  Quite simple to implement.
