### ISSUE TITLE
Timestamp.replace raises ValueError instead of TypeError when given wrong argument

### ISSUE THREAD

**Issue by sdementen** [pandas-dev/pandas#15240]
#### Code Sample, a copy-pastable example if possible

```python

from pandas import Timestamp
Timestamp("2012").replace(apple=3)
```
#### Problem description

The reimplementation of Timestamp.replace (https://github.com/pandas-dev/pandas/commit/f8bd08e9c2fc6365980f41b846bbae4b40f08b83#diff-05de2950b2c86c9828531957e02d1b87L662) raises a ValueError when a keyword argument does not exist.
Previous implementation used datetime.replace that raises a TypeError when an argument is not valid.
This is a regression and it is probably better to keep API compatibility with the datetime.replace function (modulo extra functionalities).
For autodocumentation/autocomplete purposes, it could also be useful to have explicitly in the function signature the keywords, so instead of::

`  def replace(self, **kwds):
`
have::
 
`  def replace(self, year=None, month=None, day=None, hour=None, minute=None, second=None, microsecond=None, nanosecond=None, tzinfo=None)
`

#### Actual Output
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pandas\tslib.pyx", line 715, in pandas.tslib.Timestamp.replace (pandas\tslib.c:14832)
ValueError: invalid name apple passed

#### Expected Output
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pandas\tslib.pyx", line 715, in pandas.tslib.Timestamp.replace (pandas\tslib.c:14832)
TypeError: 'apple' is an invalid keyword argument for this function

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.19.2
nose: None
pip: 9.0.1
setuptools: 27.2.0
Cython: None
numpy: 1.11.3
scipy: None
statsmodels: None
xarray: None
IPython: 5.1.0
sphinx: 1.5.2
patsy: None
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.4
boto: None
pandas_datareader: None
</details>

**Comment by jreback** [comment]
if you want to do a PR wouldn't be great

**Comment by sdementen** [comment]
I am having a try :-)
Could you tell me where I can add an additional test on Timestamp.replace ? I have a hard time locating the tests...

**Comment by sdementen** [comment]
I can't really test my patch on my machine (as I have not the tool suite necessary to compile pandas). Can I start a PR (even unfinished) to test via the Travis/Appveyor tests ? or is it "bad practice" ?

**Comment by jreback** [comment]
@sdementen the tests are exactly in the above link, IOW in pandas/tseries/test_timezones.py

I would recommend you install a proper dev version of pandas to test: http://pandas.pydata.org/pandas-docs/stable/contributing.html

**Comment by sdementen** [comment]
@jreback I can't find any test of the Timestamp.replace method (except tests testing the replace(tzinfo=xxx)). Are there specific tests for Timestamp.replace ? I was expecting/looking for tests like 
```
dt = pandas.Timestamp("2016")
tm.assert(dt.hour,0)
tm.assert(dt.replace(hour=3).hour,3)
```

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/blob/master/pandas/tseries/tests/test_timezones.py#L1170

you could add some in ``test_timeseries.py`` if you want (and just leave these for the actual timezone replacement), but doesn't really matter.

**Comment by AlexTheProgrammer** [comment]
Hi All, I've been looking to contribute to pandas for a while, so I've made a PR that I think closes this. followed the guide as best I could.
