### ISSUE TITLE
read_stata does not convert dates

### ISSUE THREAD

**Issue by fonnesbeck** [pandas-dev/pandas#15267]
Running Pandas 0.19.2 on Python 3.5.2 (macOS), the docstring for the `read_stata` function indicates that its function is to "Convert date variables to DataFrame time values"

<img width="754" alt="screenshot 2017-01-30 13 36 30" src="https://cloud.githubusercontent.com/assets/81476/22438376/58738822-e6f1-11e6-8e01-1cc3aca0cb99.png">

Yet, setting this to true does not perform this, nor does passing a list of date variables as an argument (as works with other `read_*` functions. The data type remains as an `object`:

![](http://d.pr/i/1d1a4+)

**Comment by jreback** [comment]
@fonnesbeck these are for stata encoded date variables. can you share the file?

cc @bashtage

**Comment by fonnesbeck** [comment]
Stata doesn't have a date type storage to disk, does it? I can't share the file because it is medical record information, but [here is the codebook](https://github.com/pandas-dev/pandas/files/740138/linelist_merge_codebook.txt).

**Comment by bashtage** [comment]
The codebook indicates that date of birth is a string or a %td float.
```
dob_final       float  %td                    Date of brith as numeric variable (SAS/Stata format)
dob_str         str10  %10s                   Date of birth as string variable (MM/DD/YYYY)
```

Are you sure you don't have the string one?

**Comment by bashtage** [comment]
`read_stata` reads the Stata file information for formatted dates (e.g. %td, %tc, etc) and converts these to pandas dates.  Other formats, such as strings, are not converted.

**Comment by fonnesbeck** [comment]
It was the `dob_final` field you cited, but it appears that it has some out-of-range years that cause it to fail. I will close this. Thank you!

**Comment by bashtage** [comment]
Makes sense - dates outside of 1600 - 2270 cannot be converted to `datetime[ns]` and so object is the only format that works.
