### ISSUE TITLE
to_json on multiindex does not escape strings properly

### ISSUE THREAD

**Issue by rs2** [pandas-dev/pandas#15273]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import datetime

pd.read_json(pd.DataFrame(True, index=pd.date_range(datetime.date(2017, 1, 20), datetime.date(2017, 1, 23)), columns=['foo', 'bar']).stack().to_json())

```
#### Problem description

The result of `pd.DataFrame(True, index=pd.date_range(datetime.date(2017, 1, 20), datetime.date(2017, 1, 23)), columns=['foo', 'bar']).stack().to_json()` contains 

`r'{"[1484870400000,"foo"]":true,"[1484870400000,"bar"]"'`,

#### Expected Output

Whereas it should be:
`r'{"[1484870400000,\"foo\"]":true,"[1484870400000,\"bar\"]"'`

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.5.final.0
python-bits: 32
OS: Windows
machine: AMD64
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.19.1
Cython: 0.25.1
numpy: 1.11.2
pandas_datareader: None

</details>

**Comment by jreback** [comment]
So this does seem wrong for the default of ``orient='columns'``, though ``split`` is ok.

```
In [18]: df.to_json(orient='split')
Out[18]: '{"name":null,"index":[[1484870400000,"foo"],[1484870400000,"bar"],[1484956800000,"foo"],[1484956800000,"bar"],[1485043200000,"foo"],[1485043200000,"bar"],[1485129600000,"foo"],[1485129600000,"bar"]],"data":[true,true,true,true,true,true,true,true]}'

In [19]: df.to_json(orient='columns')
Out[19]: '{"[1484870400000,"foo"]":true,"[1484870400000,"bar"]":true,"[1484956800000,"foo"]":true,"[1484956800000,"bar"]":true,"[1485043200000,"foo"]":true,"[1485043200000,"bar"]":true,"[1485129600000,"foo"]":true,"[1485129600000,"bar"]":true}'
```

**Comment by jreback** [comment]
cc @kawochen
cc @Komnomnomnom

pull requests welcome to fix!

**Comment by mroeschke** [comment]
This looks correct on master now. Could use a test

```
In [39]: pd.DataFrame(True, index=pd.date_range(datetime.date(2017, 1, 20), datetime.date(2017, 1, 23)), columns=
    ...: ['foo', 'bar']).stack().to_json()
Out[39]: '{"(Timestamp(\'2017-01-20 00:00:00\'), \'foo\')":true,"(Timestamp(\'2017-01-20 00:00:00\'), \'bar\')":true,"(Timestamp(\'2017-01-21 00:00:00\'), \'foo\')":true,"(Timestamp(\'2017-01-21 00:00:00\'), \'bar\')":true,"(Timestamp(\'2017-01-22 00:00:00\'), \'foo\')":true,"(Timestamp(\'2017-01-22 00:00:00\'), \'bar\')":true,"(Timestamp(\'2017-01-23 00:00:00\'), \'foo\')":true,"(Timestamp(\'2017-01-23 00:00:00\'), \'bar\')":true}'
```
