### ISSUE TITLE
BUG: pd.read_json with numpy=True coerces columns to int if the first column is an int

### ISSUE THREAD

**Issue by Michael-J-Ward** [pandas-dev/pandas#15284]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

print("pandas version", pd.__version__)

df = pd.DataFrame({'a': [0,0,0], 'b': [1.9995, 2.0005, 3.9995]})
print(df.dtypes)
df_json = df.to_json()

print("note that the `b` column is now a `int`")
df_from_json = pd.read_json(df_json, numpy=True)
print(df_from_json)
print(df_from_json.dtypes)

# and using dtype='float64' still rounds
df_from_json = pd.read_json(df_json, numpy=True, dtype='float64')
print(df_from_json)
print(df_from_json.dtypes)

# however, if the first column is a float, then the value is maintained
df2_json = df[['b', 'a']].to_json()
df2_from_json = pd.read_json(df2_json, numpy=True)
print(df2_from_json)
print(df2_from_json.dtypes)

```
#### Problem description

Setting `numpy=True` coerces column dtypes to `int64` if the "left / first" column is an int. This causes unexpected rounding errors and the behavior is not consistent: if the first column is a float then subsequent columns are not coerced to float.

#### Expected Output
```
   a       b
0  0  1.9995
1  0  2.0005
2  0  3.9995
```
#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-59-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.19.2
nose: 1.3.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.11.3
scipy: 0.18.1
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.5.1
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: 1.2.0
tables: 3.3.0
numexpr: 2.6.1
matplotlib: 2.0.0
openpyxl: 2.4.1
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.2
bs4: 4.5.3
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.1.5
pymysql: None
psycopg2: None
jinja2: 2.9.4
boto: 2.45.0
pandas_datareader: None

</details>

**Comment by jreback** [comment]
cc @Komnomnomnom 

why did we add the ``numpy`` (and ``dtype``) flag in the first place?

**Comment by mroeschke** [comment]
We are deprecating the `numpy` keyword, so I believe this bug will not be relevant in the future. Happy to reopen if related usage fails in the future
