### ISSUE TITLE
COMPAT: xarray 0.9.0

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15282]
https://github.com/pandas-dev/pandas/blob/master/pandas/tests/test_generic.py#L905

I believe should be changed to be version dependent, IOW, 0.9.0 https://github.com/pydata/xarray/issues/700 fixes this.

we should fix one of the builds at say 0.8.2, and let the others float (they all float now)

@shoyer ?

**Comment by shoyer** [comment]
This was fixed a while ago, I think probably by https://github.com/pydata/xarray/issues/875 (in xarray v0.8.0)
