### ISSUE TITLE
Github repository and topics

### ISSUE THREAD

**Issue by femtotrader** [pandas-dev/pandas#15292]
Hello,

Github recently add topics
see https://github.com/blog/2309-introducing-topics
https://help.github.com/articles/about-topics/

Maybe this repository should be tagged.

See also https://github.com/pydata/pandas-datareader/issues/278

Kind regards

**Comment by jreback** [comment]
I added some topics, if anyone wants to suggest / add pls. do.

**Comment by femtotrader** [comment]
Could you add some topics to pandas-datareader repository also?
see https://github.com/pydata/pandas-datareader#278

**Comment by femtotrader** [comment]
https://github.com/pydata/pandas-datareader/issues/278
