### ISSUE TITLE
sample can only pick items of length 1. should be able to choose arbitrary length.

### ISSUE THREAD

**Issue by chrism2671** [pandas-dev/pandas#15293]
#### sample can only pick items of length 1. should be able to choose arbitrary length.

sample is very useful for statistical bootstrapping, however, on time series data, it is frequently necessary to sample 'sections' from a Series/DataFrame. Each sample might be '50 days', hence 50 rows. This is a very common use case, which I've hacked into my projects several times already.

I am happy to try and edit this into pandas.generic.sample, but would appreciate some guidance as to how best to implement it, as unlike the current implementation, it will return a list of DataFrames (rather than the same type that was provided). Suggestions welcome.

**Comment by jreback** [comment]
pls show an example of what you mean.

**Comment by mroeschke** [comment]
Feel free to reopen if you can post a example of the behavior for this feature.
