### ISSUE TITLE
Travis doc build not run with master anymore

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#15311]
Since a few commits (but I don't think it is related to one of our commits, rather to conda or so), the docs are run with pandas 0.19.2, and not with master (giving a lot of errors for those code blocks that show new things, see eg [here](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#dtype-keyword-for-data-io))

The cause seems to be that the installing of `r` and `rpy2` seems to install pandas (https://travis-ci.org/pandas-dev/pandas/jobs/198582770, line 1233 in the log). Before that commit, the build log does not include pandas in that conda output. 
The strange thing is also that pandas appears in the conda output as a 'new' package, not one that is up or downgraded. Which seems to indicate that pandas was not yet installed, although the master version seemed to be installed correctly.

**Comment by jreback** [comment]
so a way to fix

install r things with a separate conda installl

and use --no-deps

**Comment by jorisvandenbossche** [comment]
They are already a separate conda install, and indeed, tried with ``--no-deps`` (test is running on travis, but still on my fork: https://travis-ci.org/jorisvandenbossche/pandas/builds/198665251). 
The strange thing is though why this changed (when I install r and rpy2 in a clean env locally, pandas is not added by default, so it's not that the conda-packagers added pandas as a dep of rpy2).

**Comment by jreback** [comment]
i would guess that rpy maybe is explicitly having pandas as a dep? (and maybe. it before)

another alternative could be to fix the versions 

also possible newer conda 'fixes' things (but actually we were relying on broken behavior before)

**Comment by jreback** [comment]
other thug is we do uninstall pandas as final step (so we will use the sec version)

for example xarray installs pandas as well

**Comment by jreback** [comment]
you just need this in ``ci/build-docs.sh``

This is what we do at the end of ``install_travis.sh``
```
    # remove any installed pandas package
    # w/o removing anything else
    echo "[removing installed pandas]"
    conda remove pandas --force
```

though what I would really do is put these lines in:

```
    source activate pandas
    conda install -n pandas -c r r rpy2 --yes

    time sudo apt-get $APT_ARGS install dvipng texlive-latex-base texlive-latex-extra
```

in here
```
(pandas) bash-3.2$ more ci/requirements-3.5_DOC_BUILD.sh 
#!/bin/bash

source activate pandas

echo "install DOC_BUILD"

conda install -n pandas -c conda-forge feather-format
```

This is an optional script that gets run to do post conda/pip requirements installs (when completely custom is needed).

**Comment by jorisvandenbossche** [comment]
Ah, yes, that seems like a better idea. In any case, the test with `--no-deps` failed as it actually needed some deps (which of course could be figured out which they are and include them in the install command. But if this works that will be easier and more consistent)

Test is here: https://github.com/pandas-dev/pandas/pull/15317

**Comment by jreback** [comment]
I also temp removed all builds except for this one to make faster (but won't merge that comit): https://travis-ci.org/jreback/pandas/builds/198847359

**Comment by jorisvandenbossche** [comment]
Ah OK, your commit is fine as well, but updated the PR as well.

**Comment by jreback** [comment]
yep go ahead with yours is fine.

**Comment by jorisvandenbossche** [comment]
And from the build on your fork, it seems to work now (the remaining errors in the doc build log are the 'expected' (await fixes as well))
