### ISSUE TITLE
ewmcorr - Input arrays must be of the same type! using numpy arrays

### ISSUE THREAD

**Issue by bmpalatiello** [pandas-dev/pandas#15327]
I am trying to use ewmcorr on a numpy array:

`rand_arr = np.random.random((50, 50))`
`test_corr = ewmcorr(rand_arr, span=10)`

and I get the following Exception:
`Exception: Input arrays must be of the same type!`

numpy arrays are acceptable arguments, I'm unsure why it is not working.

**Comment by jreback** [comment]
not sure this ever accepted arrays as an argument (must be a DataFrame), in any event you are using an old interface.

```
In [6]: df = DataFrame(np.random.randn(50,50))
In [7]: df.ewm(span=10).corr(df)
```

**Comment by jreback** [comment]
docs are here: http://pandas-docs.github.io/pandas-docs-travis/computation.html#exponentially-weighted-windows
