### ISSUE TITLE
How to question

### ISSUE THREAD

**Issue by BardiaAfshin** [pandas-dev/pandas#15325]
Hi there,

I want to select all the rows in my data frame where 'finished_processing_date' is not null.

I know I can do something like this to count the null fields

```python
df_not_finished_processing = df[df['finished_processing_date'].isnull()];
df_not_finished_processing.count()
```

but what about doing the opposite? Selecting all rows that the field is not null.

**Comment by TomAugspurger** [comment]
`.notnull` or use `~` on the mask you have to flip it.

FYI: the [pandas tag](http://stackoverflow.com/questions/tagged/pandas) on stackoverflow is the preferred forum for asking usage questions.

**Comment by BardiaAfshin** [comment]
exactly what I was looking for.
