### ISSUE TITLE
df.squeeze() doesn't support axis parameter

### ISSUE THREAD

**Issue by kernc** [pandas-dev/pandas#15339]
#### Code Sample, a copy-pastable example if possible

```python
>>> df = pd.DataFrame([1], columns=['A'])

>>> df 
   A
0  1

>>> df.squeeze()
1

>>> type(df.squeeze())
numpy.int64

>>> df.squeeze(axis=1)  # Only want to squeeze a single dimension, i.e. into a series
...
ValueError: the 'axis' parameter is not supported in the pandas implementation of squeeze()
```
#### Problem description

`np.squeeze` supports `axis` parameter and [this comment in the source](https://github.com/pandas-dev/pandas/blob/542c9166a6ceff4a4889caae3843c3a82a2301cd/pandas/compat/numpy/function.py#L217-L219) implies it should eventually be implemented.

#### Expected Output
```py
>>> df.squeeze(axis=1)  # Squeeze a single dimension, i.e. into a series
0    1
Name: A, dtype: int64

>>> df.squeeze(axis=0)
A    1
Name: 0, dtype: int64
```
#### Output of ``pd.show_versions()``

pandas: 0.19.0+416.ge1390cd

**Comment by jreback** [comment]
@kernc how is this actually useful though? numpy needs this because of n-dim shrinking to a lower dim. pandas generally has 2-dim max so this is not so important.

**Comment by kernc** [comment]
As the example shows, it is only useful to squeeze a 1x1 frame into a series instead of a scalar. :smiley:
