### ISSUE TITLE
DEPR: pd.Grouper key -> on

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15331]
xref https://github.com/pandas-dev/pandas/pull/15326#issuecomment-278008177

- when ``pd.Grouper`` was introduced, we used ``key`` to indicate the column which to group on
- ``.resample`` added the same idea as ``on``
- we use ``on`` in ``pd.merge`` (existing for a long time)
- ``.groupby`` uses ``by`` (though to be fair this can take lots of things and is not strictly a string column name).

So the proposal is to deprecate ``pd.Grouper(key=...)`` in favor of ``on=``.

**Comment by jreback** [comment]
@chrisaycock gives +1
@jorisvandenbossche -0
@jreback +1

**Comment by chrisaycock** [comment]
`pd.merge_asof()` has both `on` and `by` parameters.

**Comment by jreback** [comment]
any thoughts about whether we should do this (at some point)?

@TomAugspurger @jorisvandenbossche

**Comment by TomAugspurger** [comment]
No strong opinion.

**Comment by jbrockmendel** [comment]
Any clarity on this?

**Comment by jorisvandenbossche** [comment]
Since it's only about a possible future deprecation (not a deprecation that can be enforced in 1.0), there is not need to have this in 1.0 (we can deprecate things in any 1.x afterwards) and so I moved this off the 1.0 milestone.

**Comment by mroeschke** [comment]
Since we decided to keep Grouper (https://github.com/pandas-dev/pandas/issues/41297) and there is no strong leaning on this, probably best to keep it as necessary to the Grouper API. Closing but can reopen if we redecide.
