### ISSUE TITLE
DOC: Why do we have two README's for contributing?

### ISSUE THREAD

**Issue by gfyoung** [pandas-dev/pandas#15349]
This one under the documentation folder <a href="https://github.com/pandas-dev/pandas/blob/master/doc/source/contributing.rst">here</a> and this one under the `.github` folder <a href="https://github.com/pandas-dev/pandas/blob/master/.github/CONTRIBUTING.md">here</a>.

I think we should just have one point to the other to avoid having to maintain it in two different places.

**Comment by jreback** [comment]
I think you have a typo in the links (they are the same).

In any event, the canonical contributing guide is actually in the docs: http://pandas.pydata.org/pandas-docs/stable/contributing.html, but github has this 'feature' where they have a ``CONTRIBUTING.md``. Our docs are ``.rst`` so this is problem.

maybe best is to change ``.github/CONTRIBUTING.md`` to just point directly to the docs.

**Comment by jreback** [comment]
though maybe the ``.github/CONTRIBUTING.md`` is just a rendered version of the docs. 

We had a discussion about this a while back but I don't remember.

@jorisvandenbossche ?

**Comment by jorisvandenbossche** [comment]
As far as I know, the one just a conversion of the other (so the `.github/CONTRIBUTING.md` should never be updated directly). We just keep forgetting that :-) 

But, it is actually stated in the same docs .. See the note in http://pandas.pydata.org/pandas-docs/stable/contributing.html#about-the-pandas-documentation

**Comment by jorisvandenbossche** [comment]
We also have a wiki page about this: https://github.com/pandas-dev/pandas/wiki/Regenerating-CONTRIBUTING.md

I don't feel strongly between the current situation or just putting a link in the contributing.md file to the docs

**Comment by gfyoung** [comment]
@jreback : Good catch on the links.  I updated them.  In any case, I'm perfectly fine with just linking the `CONTRIBUTING.md` to the `.rst` version.  It seems easier to maintain.  How about that?

**Comment by jreback** [comment]
I don't think you can do that. github only renders the ``.md``. I think the current soln is pretty decent actually.

**Comment by gfyoung** [comment]
That's not what I meant.  I meant, we should just say, go read the canonical docs and provide the link to the file, that's all.

**Comment by jreback** [comment]
@jorisvandenbossche ?

**Comment by gfyoung** [comment]
@jorisvandenbossche : Thoughts on my proposal <a href="https://github.com/pandas-dev/pandas/issues/15349#issuecomment-278395500">above</a>?

**Comment by jorisvandenbossche** [comment]
I would be fine with a link to the main contributing docs, instead of having a copy of the full content (can't directly remember the reason why we originally did it like this.

But, I would do a bit more than just linking. Something like a *very* short summary, and linking to some different parts of the contributing docs.
For example directing people who want to submit a bug to the section on how to report an issue, and for people making a PR a checklist or link to checklist in the contributing docs (seems we actually don't have a good overview of what we expect currently).
