### ISSUE TITLE
MIGRATE: pandas-gbq

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15347]
I created the [pandas-gbq](https://github.com/pydata/pandas-gbq) package to migrate the guts of pandas/io/gbq.py. Once this is release and on PyPi and conda-forge. Then we can switch the internal interface to use this code. I think this will allow this package to grow.

**Comment by jreback** [comment]
I have add all pandas to the repo as well as @parthea . If you would like to be added, please ping.

**Comment by MaximilianR** [comment]
CC @clifton

**Comment by jorisvandenbossche** [comment]
Big +1 to have this as a separate package.

> Then we can switch the internal interface to use this code

@jreback What is your idea on how to approach this?

Let `read_gqb`/`to_gbq` call the external package and pass everything on?

Roughly like

```
def read_gbq(*args, **kwargs):
    from pandas_gbq import read_gbq
    return read_gbq(*args, **kwargs)

class DataFrame():
    ...
    def to_gbq(self, *args, **kwargs):
        from pandas_gbq import to_gbq
        to_gbq(self, *args, **kwargs)
```

(with of course some checking of the import etc)

**Comment by jreback** [comment]
exactly the internal pandas implementation becomes trivial

**Comment by jreback** [comment]
ok moved all of the docs, so will change that as well: http://pandas-gbq.readthedocs.io/en/latest/index.html#
