### ISSUE TITLE
BUG: conversion of uint64 to float when taking

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15362]
https://github.com/pandas-dev/pandas/pull/15245/commits/62fe71e8465d2876f8687731cd2275b3d46d5a6b#r100575113

```
# master
In [1]: pandas.core.algorithms.take_nd(np.array([0, 1], dtype='uint64'), np.array([0, -1]))
Out[1]: array([  0.,  nan])

# with this change above
In [5]: pandas.core.algorithms.take_nd(np.array([0, 1], dtype='uint64'), np.array([0, -1]))
Out[5]: array([                   0, 18446744073709551615], dtype=uint64)
```

mainly need some more testing w.r.t. this (e.g. ``pandas.types.cast._maybe_promote``).

**Comment by jreback** [comment]
cc @gfyoung

**Comment by jreback** [comment]
this is not going to work as lots of code relies on this. This is using the ``np.iinfo(np.uint64).max`` as the missing value value.

In any event we should do *something* here, maybe treat ``uint`` with a missing value as an ``object`` dtype for now.

**Comment by jreback** [comment]
I took a different path in https://github.com/pandas-dev/pandas/pull/15245

**Comment by jbrockmendel** [comment]
im not clear on what the bug is here.  the behavior looks correct (both in OP and master)

**Comment by mroeschke** [comment]
Agreed, closing as this looks like the correct behavior
