### ISSUE TITLE
clip inplace?

### ISSUE THREAD

**Issue by cnsgsz** [pandas-dev/pandas#15388]
Is it possible to support clip in place, just like numpy does? I assume that would speed up working with large dataframe/series as no extra copies will be needed.

If not, is that a workaround to achieve the same effect? I tried `np.clip(df.values,-clip_bounds.values, clip_bounds.values, out=df.values)`, but realized that df.values is actually an expensive call as it is merging  blocks underneath.

**Comment by jreback** [comment]
virtually all methods in pandas return new objects, exception are indexing. ``inplace`` does not provide ANY benefit, and should never have been added as it provides no utility and serves to confuse people.

so no, won't be adding any more inplace ops.

**Comment by jorisvandenbossche** [comment]
@jreback this clip function is actually one of rare methods where having an `inplace` arg actually would make sense, IMO.

And it would also not be difficult to add, as `DataFrame.where` (which is what clip uses under the hood) already supports `inplace`.

**Comment by jreback** [comment]
I am ok with it - @cnsgsz if you would like to do an implementation would be great

**Comment by guygoldberg** [comment]
Starting to work on it
