### ISSUE TITLE
Docathon - documentation hackaton - week of March 6th

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#15405]
I would like to register pandas to join the Docathon as a potential project (and will also reserve some time that week to review if there are contributions): https://bids.github.io/docathon/ 
OK about that?

For contributors:

- The general contributing docs can be found here: http://pandas.pydata.org/pandas-docs/stable/contributing.html (on how to set up a development environment, etc). 
  - There is also a section specific to contributing to the documentation: http://pandas.pydata.org/pandas-docs/stable/contributing.html#contributing-to-the-documentation
- In general, you can look for open issues with the `Docs` label: https://github.com/pandas-dev/pandas/issues?q=is%3Aopen+is%3Aissue+label%3ADocs
  - Within that label, you can also look for those issues tagged with "Difficulty - novice" or "Effort - low"

If you have any questions, welcome on the pandas-dev gitter channel: https://gitter.im/pydata/pandas

**Comment by story645** [comment]
Also hosting an NYC branch at the Graduate Center (CUNY)  March 6th 5:00-10:00 if anyone's local and would like to come.

**Comment by story645** [comment]
https://www.eventbrite.com/e/doc-a-thon-tickets-32309998074
