### ISSUE TITLE
Possible enhancement? Outlier detection

### ISSUE THREAD

**Issue by Kevin-McIsaac** [pandas-dev/pandas#15401]
For a project I'm working on I need to identify and remove outliers. After some searching I could not find anything in pandas (or other packages) so I wrote three functions to:
* find outliers using one of z-score, MAD and Quantiles
* plot these outliers on a timer series plot along with an optional trend line.
* replace the outliers with interpolated values.

Are these generally useful enough to warrant adding to pandas? 

This [notebook](https://github.com/Kevin-McIsaac/Nightlife/blob/master/Outlier%20Examples.ipynb) has some exmaples.

**Comment by jreback** [comment]
we had almost this exact discussion here: https://github.com/pandas-dev/pandas/issues/15111

so would welcome a doc-addition (maybe in ``missing.rst``). section.

**Comment by bashtage** [comment]
Statsmodels has a number of methods to perform outlier detection and outlier robust estimation

http://statsmodels.sourceforge.net/stable/diagnostic.html

**Comment by JamesTrick** [comment]
Was the conclusion on this, that statsmodel should implement, or would this be something implemented into pandas if someone builds it?

If it is something pandas would be interested in implementing, I'd be interested in taking a look at developing it!

**Comment by bashtage** [comment]
Should be in statsmodels IMO.  Or somewhere else, since not really a core, common feature of a data library (unlike say, basic statics like mean and std).

**Comment by jreback** [comment]
closing as out of scope
