### ISSUE TITLE
BUG: pd.cut with bins=1 and input all 0s

### ISSUE THREAD

**Issue by luca-s** [pandas-dev/pandas#15428]
#### Code Sample, a copy-pastable example if possible

```python
>>> import pandas as pd
>>> pd.__version__
u'0.19.2'

>>> s = pd.Series([0,0,0])
>>> pd.cut(s, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luca/.local/lib/python2.7/site-packages/pandas/tools/tile.py", line 119, in cut
    include_lowest=include_lowest)
  File "/home/luca/.local/lib/python2.7/site-packages/pandas/tools/tile.py", line 194, in _bins_to_cuts
    raise ValueError('Bin edges must be unique: %s' % repr(bins))
ValueError: Bin edges must be unique: array([ 0.,  0.])

>>> s = pd.Series([-1,-1,-1])
>>> pd.cut(s, 1)
0    (-1.001, -0.999]
1    (-1.001, -0.999]
2    (-1.001, -0.999]

>>> s = pd.Series([1,1,1])
>>> pd.cut(s, 1)
0    (0.999, 1.001]
1    (0.999, 1.001]
2    (0.999, 1.001]

```

#### Problem description

The special case of an input containing all 0s raises a ValueError. I had a look at the [code](https://github.com/pandas-dev/pandas/blob/master/pandas/tools/tile.py#L107) and it is straightforward to fix. I can provide a PR if requested.

#### Expected Output

```
>>> pd.cut(s, 1)
0    (-0.001, 0.001]
1    (-0.001, 0.001]
2    (-0.001, 0.001]
```

#### Output of ``pd.show_versions()``

<details>
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Linux
OS-release: 4.8.0-36-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.19.2
nose: 1.3.7
pip: 8.1.1
setuptools: 32.3.1
Cython: 0.23.4
numpy: 1.12.0
scipy: 0.18.1
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.5.1
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999
httplib2: 0.9.1
apiclient: None
sqlalchemy: 1.1.4
pymysql: None
psycopg2: None
jinja2: 2.8.1
boto: None
pandas_datareader: 0.2.1

</details>

**Comment by TomAugspurger** [comment]
Sure a fix would be great.
