### ISSUE TITLE
BUG: pd.qcut with q=1 and input with identical values

### ISSUE THREAD

**Issue by luca-s** [pandas-dev/pandas#15431]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
>>> pd.__version__
u'0.19.2'

>>> s = pd.Series([1,1,1])
>>> pd.qcut(s, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luca/.local/lib/python2.7/site-packages/pandas/tools/tile.py", line 175, in qcut
    precision=precision, include_lowest=True)
  File "/home/luca/.local/lib/python2.7/site-packages/pandas/tools/tile.py", line 194, in _bins_to_cuts
    raise ValueError('Bin edges must be unique: %s' % repr(bins))
ValueError: Bin edges must be unique: array([1, 1])

>>> s = pd.Series([1,1,2])
>>> pd.qcut(s, 1)
0    [1, 2]
1    [1, 2]
2    [1, 2]

>>> s = pd.Series([0,1,2])
>>> pd.qcut(s, 1)
0    [0, 2]
1    [0, 2]
2    [0, 2]

```
#### Problem description

If the input contains identical values pd.qcut fails even with q=1. I had a look at the [code](https://github.com/pandas-dev/pandas/blob/master/pandas/tools/tile.py#L209) and I can try to relax the check to allow this specific case to pass and avoid the exception, but then I have to make sure the code can handle a single edge.  

#### Expected Output

```
>>> s = pd.Series([1,1,1])
>>> pd.qcut(s, 1)
0    [0, 2]
1    [0, 2]
2    [0, 2]
```

#### Output of ``pd.show_versions()``

<details>
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Linux
OS-release: 4.8.0-36-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.19.2
nose: 1.3.7
pip: 8.1.1
setuptools: 32.3.1
Cython: 0.23.4
numpy: 1.12.0
scipy: 0.18.1
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.5.1
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999
httplib2: 0.9.1
apiclient: None
sqlalchemy: 1.1.4
pymysql: None
psycopg2: None
jinja2: 2.8.1
boto: None
pandas_datareader: 0.2.1

</details>

**Comment by jreback** [comment]
this is the same as #15428 so ideally let's solve in the same PR., just list it as a separate case there.

**Comment by luca-s** [comment]
I am not sure I am following your reasoning. From my point of view It's a different issue (totally different code bug) and they are also two different functions (qcut vs cut).
