### ISSUE TITLE
Adding Timedelta parameter to time-based .rolling()

### ISSUE THREAD

**Issue by chrisaycock** [pandas-dev/pandas#15440]
Starting with a simple DataFrame:

```python
n = 10
df = pd.DataFrame({'value': np.arange(n)},
                  index=pd.date_range('2015-12-24', periods=n, freq="D"))
```

I can invoke a time-based `.rolling()` with a string for the offset:

```python
df.rolling('3d').sum()
```

I would like to invoke it with a `Timedelta` since it is easier to arithmetically change the window length:

```python
df.rolling(pd.Timedelta(days=3)).sum()
```

**Comment by jreback** [comment]
hmm, it allows offsets already (in fact internally that's all its doing), so this must be just an oversight

```
In [7]: df.rolling(pd.tseries.frequencies.to_offset(pd.Timedelta(days=3))).sum()
Out[7]: 
            value
2015-12-24    0.0
2015-12-25    1.0
2015-12-26    3.0
2015-12-27    6.0
2015-12-28    9.0
2015-12-29   12.0
2015-12-30   15.0
2015-12-31   18.0
2016-01-01   21.0
2016-01-02   24.0
```

**Comment by chrisaycock** [comment]
Ah, I hadn't known about `to_offset()`! That's neat.

**Comment by fjanoos** [comment]
Thanks ! it would be great though if Timedelta were directly supported !

**Comment by jreback** [comment]
@fjanoos we *already* use ``to_offset`` internally

```
In [1]: from pandas.tseries.frequencies import to_offset

In [2]: to_offset(pd.offsets.Day(1)).nanos
Out[2]: 86400000000000

In [4]: to_offset(pd.Timedelta('1 day')).nanos
Out[4]: 86400000000000

```

this is just a matter if fixing the checking.

pull-requests are welcomed!

**Comment by fjanoos** [comment]
Is this change in the master branch now ?

**Comment by jreback** [comment]
yep closed via https://github.com/pandas-dev/pandas/pull/15443
