### ISSUE TITLE
pandas0.19.2 make  django1.10.4 not work

### ISSUE THREAD

**Issue by llfccc** [pandas-dev/pandas#15459]
#### Code Sample, a copy-pastable example if possible

```python

#coding=utf-8
from django.forms.models import model_to_dict  
from django.db import connection
import os,sys
import time,datetime
from .models import RegistrationTable
import pandas as pd

def insert_db(data,SupplierPaymentDict,company_name,chinese_name):
    return 0

```
#### Problem description

if i import pandas 0.19.2 into the programe ，only type 
import pandas  will make the error。
the error is ，if i use mod_wsgi4.4+apache2.4+django1.10.4 to run a website，i will got “127.0.0.1 is respording”，but if i use django‘runserver  like “ python manage.py runserver "，it will work well。

but if i roll back to 0.18.0，all is ok

#### Output of ``pd.show_versions()``

<details>
# Paste the output here pd.show_versions() here
>>> pandas.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 32
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.19.2
nose: 1.3.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.12.0
scipy: 0.18.1
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.5.1
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: 1.2.0
tables: 3.2.2
numexpr: 2.6.1
matplotlib: 2.0.0
openpyxl: 2.4.1
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.2
bs4: 4.5.3
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.1.5
pymysql: 0.7.9.None
psycopg2: None
jinja2: 2.9.4
boto: 2.45.0
pandas_datareader: None
</details>

**Comment by jorisvandenbossche** [comment]
This sounds similar to what is reported in https://github.com/pandas-dev/pandas/issues/14641. Can you take a look at that issues and the possible solutions proposed?

**Comment by jreback** [comment]
closing as duplicate
