### ISSUE TITLE
Series.rolling(3).quantile(10) segmentation fault

### ISSUE THREAD

**Issue by kernc** [pandas-dev/pandas#15463]
#### Code Sample, a copy-pastable example if possible

```python
>>> pd.Series(np.arange(10)).rolling(3).quantile(10)
[1]    20214 segmentation fault
```
#### Problem description

The value 10 is over the fraction of 1 which .quantile() works with, but I guess it still shouldn't crash my interpreter.

#### Expected Output
```text
ValueError: quantile value 10 not in [0, 1]
```
#### Output of ``pd.show_versions()``

pandas 0.19.0+479.g4842bc7

**Comment by jreback** [comment]
yep, not very friendly...PR's appreciated!

**Comment by csizsek** [comment]
Hi @kernc and @jreback , I'm thinking about fixing this issue. Any idea where to start?

**Comment by jreback** [comment]
you can add a validation right here ``0 <= quantile <= 1``: https://github.com/pandas-dev/pandas/blob/master/pandas/window.pyx#L1288, and raise a ``ValueError`` if not in range. please add some tests as well.

thanks!
