### ISSUE TITLE
ERR: better error message when using invalid indexer in iloc

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#15471]
Not the most important isssue, but I find the error message when doing label based indexing with strings in `iloc` not very clear:

```
In [12]: s = pd.Series(range(5), index=pd.date_range("2012-01-01", periods=5))

In [15]: s.loc["2012-01-02":"2012-01-04"]
Out[15]: 
2012-01-02    1
2012-01-03    2
2012-01-04    3
Freq: D, dtype: int64

In [16]: s.iloc["2012-01-02":"2012-01-04"]
...
TypeError: cannot do slice indexing on <class 'pandas.tseries.index.DatetimeIndex'> with
these indexers [2012-01-02] of <class 'str'>
```

So I by accident used iloc instead of loc, but the error message did not directly make my error clear to me. I think it should just say something about that strings are not allowed in iloc. Because I *can* do slice indexing with strings on a DatetimeIndex (as the error message says I cannot), only not with iloc :-)

(on pandas 0.19.2)

**Comment by jreback** [comment]
yes I agree here. Always a better message is nice.

**Comment by simonjayhawkins** [comment]
on master the message is now `TypeError: cannot do positional indexing on DatetimeIndex with these indexers [2012-01-02] of type str`

**Comment by jorisvandenbossche** [comment]
Yes, there have been some PRs related to this recently (eg I did a PR to improve the message (use 'positional' instead of slice, use the name of the class, @jbrockmendel also did some PRs cleaning up those cases), so I think this should also be covered by those PRs, and can be closed now.
