### ISSUE TITLE
DEPR: .consolidate() should be non-public

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15483]
no user reason to use this, and will eventually disappear in pandas 2.0 anyhow.

I would rename to ``_consolidate()`` and then provide a deprecation warning for ``.consolidate()``. Would need to change some internal code to use the renamed version.

xref https://github.com/pandas-dev/pandas/issues/15482#issuecomment-281986233

**Comment by GuessWhoSamFoo** [comment]
I'd be interested in working on this. Does renaming to `_consolidate()` mean that calling the method on a dataframe would be `df._consolidate()` ,or is there a way to change the name but still access with `df.consolidate()`?

**Comment by jorisvandenbossche** [comment]
@GuessWhoSamFoo You can rename the existing `consolidate` method to `_consolidate`, and then create a new `consolidate` method that has a deprecation warning and calls the `_consolidate` method.

**Comment by jreback** [comment]
@GuessWhoSamFoo the point is that a user should *never* need to call ``.consolidate()`` at all, this is an internal implementation detail. We call this a little bit in the pandas implementation code, IOW, in things like ``core/groupby``, ``core/generic`` and such. These should be changed to ``._consolidate``.
