### ISSUE TITLE
Repr-ing SparseDataFrame after setting a value

### ISSUE THREAD

**Issue by kernc** [pandas-dev/pandas#15488]
#### Code Sample, a copy-pastable example if possible

```python
>>> sdf = pd.SparseDataFrame(index=[0, 1], columns=[0, 1])
>>> sdf[0][0] = 1  # This warns; ignore
>>> sdf
AttributeError: 'NoneType' object has no attribute 'type'
```
#### Problem description

After some value is set on a copy of a SparseSeries, the enclosing SparseDataFrame can no longer be printed (raises AttributeError).

#### Expected Output
```py
>>> sdf
    0   1
0 NaN NaN
1 NaN NaN
```
#### Output of ``pd.show_versions()``

0.19.0+479.git

**Comment by jreback** [comment]
These are not implemented, so not sure that 

```
In [3]: sdf.loc[0,0] = 1
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
```

this should even work
