### ISSUE TITLE
ENH: BusinessHour to support multiple opening and closing times per day

### ISSUE THREAD

**Issue by jzwinck** [pandas-dev/pandas#15481]
BusinessHour supports arbitrary start and end times.  But some businesses open and close more than once per day.  Some examples:

 * Restaurants, who might want to analyze foot traffic or revenue, but excluding times they don't open.
 * Stock markets, several of which have a lunch break.
 * Mexico, where standard business hours are 07:00-14:00 and 16:00-18:00.

Many use cases could be satisfied by just two opens and two closes per day, but it might be just as well to support any amount.

**Comment by jreback** [comment]
can you give a pseudo code example of how this would work? (constructor, usage, etc), compared to using just one o/c

**Comment by jzwinck** [comment]
It could be done using arrays or lists for `start` and `end` in the `BusinessHour` and `CustomBusinessHour` constructors.  For example:

    mexico_hour = BusinessHour(start=['07:00', '16:00'], end=['14:00', '18:00'])

Or it could be done using a single 2D set of start and end times:

    mexico_hour = BusinessHour(open=[['07:00', '14:00'], ['16:00', '18:00']])

Personally I'd be happy with either.  Once constructed, usage should be exactly the same.  For example if I add one `mexico_hour` to `2017-02-23 13:30` I would expect to get `2017-02-23 16:30`, and if I add seven hours I would expect to get `2017-02-24 11:30`.

**Comment by jreback** [comment]
ok doesn't seem unreasonable. I had a brief look at the current impl. It does seem that this could be done in a back-compat way, though might be some semantic confusions, e.g. since open can now occur multiple times per day.

so would take a community PR to do this!

@sinhrks
