### ISSUE TITLE
DOC: docstrings of is_type_factory and is_instance_factory in config.py not accurate.

### ISSUE THREAD

**Issue by fumitoh** [pandas-dev/pandas#15485]
The validators returned by the functions don't return True, contrary to the docstrings' descriptions.

**Comment by jreback** [comment]
@fumitoh exactly what are you referring?

**Comment by fumitoh** [comment]
[here](https://github.com/pandas-dev/pandas/blob/b94186d4c58ee055656a84f55618be537db0095a/pandas/core/config.py#L750-L758) and [here](https://github.com/pandas-dev/pandas/blob/b94186d4c58ee055656a84f55618be537db0095a/pandas/core/config.py#L771-L772)

Both `inner` s return None.

**Comment by jreback** [comment]
but how is this incorrect?
the doc string says it's returning a function which it is; not the result of the function

**Comment by fumitoh** [comment]
The doc string says:

    Returns
    -------
    validator - a function of a single argument x , which returns the
                True if type(x) is equal to `_type`

The validator does not return True. It's just for raising an error when invalid type objects are passed.

**Comment by jreback** [comment]
ok if you'd like to do a PR to fix would be fine
