### ISSUE TITLE
Minor rounding error in Series.sum()

### ISSUE THREAD

**Issue by murizvi** [pandas-dev/pandas#15491]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame.from_dict({'date': ['20161024', '20161025', '20161026', '20161027', '20161028'],
                             'holding': [5, 10, 2, 4, 0],
                             'return': [1.035,-2,3.035,4.5, 1.5]})
df['return'].sum()
```
#### Problem description
The above code outputs 0.19500000000000003, which is certainly close, but obviously incorrect. The same issue still exists if small changes in the 'return' values are made (e.g. [0.0, 1.0, -0.7, 0.3, -0.1]).

#### Expected Output
0.195
#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS

------------------

commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.19.2
nose: 1.3.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.24.1
numpy: 1.11.3
scipy: 0.18.1
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.4.6
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.6.1
blosc: None
bottleneck: 1.1.0
tables: 3.2.2
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.3
lxml: 3.6.4
bs4: 4.5.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.42.0
pandas_datareader: None
</details>

**Comment by jreback** [comment]
you seem to have pasted the wrong number above.

```
In [1]: df = pd.DataFrame.from_dict({'date': ['20161024', '20161025', '20161026', '20161027', '20161028'],
   ...:                              'holding': [5, 10, 2, 4, 0],
   ...:                              'return': [1.035,-2,3.035,4.5, 1.5]})
   ...: df['return'].sum()
   ...: 
Out[1]: 8.07

In [2]: 1.035+-2+3.035+4.5+ 1.5
Out[2]: 8.07
```

In any event floating point numbers can not be exactly represented and only have a finite precision.

https://docs.python.org/3.5/tutorial/floatingpoint.html
