### ISSUE TITLE
ERR: better message for HDFStore date query with non date columns

### ISSUE THREAD

**Issue by chris-b1** [pandas-dev/pandas#15492]
When querying a `HDFStore` with a timestamp, on a column that (in my case, inadvertently) isn't a datetime, the error message isn't helpful; I think we can trap and show something better here.

```python

df = pd.DataFrame({'date': ['2014-01-01', '2014-01-02'], 'values': [1, 2]})

df.to_hdf('store.h5', 'df', format='t', data_columns=['date'])

ts = pd.Timestamp('2014-01-01')

In [18]: pd.read_hdf('store.h5', 'df', where='date > ts')
  File "<string>", line 1
    (date > 1970-01-01 00:00:01.388556)
                  ^
SyntaxError: invalid token
```

pandas 0.19.2

**Comment by jreback** [comment]
what you don't like ``SyntaxError`` :<? (hahha)

**Comment by jreback** [comment]
your change didn't fail any existing tests, interesting. ok thanks for the fix. merging.
