### ISSUE TITLE
TST: move pandas/tests/io/test_date_converters.py to pandas/tests/io/parsers/parse_dates.py

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15519]
see https://github.com/pandas-dev/pandas/pull/15378#issuecomment-282740398

we have centralized ``parse_dates`` testsing with all parsers. Need to move these tests appropriately.

**Comment by jaehoonhwang** [comment]
Can I take this? @jreback

**Comment by jreback** [comment]
sure!
