### ISSUE TITLE
VIS: plot method cannot handle new 'C0'-like colors (matplotlib 2.0)

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#15516]
matplotlib 2.0 introduced a few 2-character color abbreviations: C0, C1, C2, ... to refer to the colors of the current color cycle 
(very handy! this way you can refer to a color of the color cycle without hardcoding it, and use it as a shortcut for `color='tab:blue'` if you want the new blue instead of the ugly `color='b'`)

But, it seems pandas cannot handle this at the moment, as it tries to interpret it as multiple colors:

```
df = pd.DataFrame(np.random.randn(10,3), columns=['a', 'b', 'c'])
df.plot(color='C0')
```

gives `ValueError: 'C0' can be parsed as both single color and color cycle. Specify each color using a list like ['C0'] or ['C', '0']`

I know the error message already gives the solution (using `color=['C0']`), but I think it would be nice to special case those to have to working by default.

**Comment by GuessWhoSamFoo** [comment]
This one is pretty old, but I'd love to revive it. I'm not sure how tests will cover this change. Is it alright if I give it a try anyway?

**Comment by jreback** [comment]
sure!

try adding. test with the code as above (u will check this plot works)

**Comment by jbrockmendel** [comment]
@jorisvandenbossche we're now getting warnings about upper-case letters.  Do we want to support upper-case specifically?  If not, its an easy edit to get rid of the warnings in the CI logs.

**Comment by jorisvandenbossche** [comment]
Answered in the other thread, but to have it here as well: yes we want to support those upper-case ones specifically. They are a specific color naming scheme of matplotlib. 
I don't think they are what cause the warnings (although maybe how it is implemented to parse them causes warnings)
