### ISSUE TITLE
BUG: invalid dtypes should raise

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15520]
xref https://github.com/dask/dask/issues/1965

when an explict dtype is provided, we should raise if its not a valid ``numpy/pandas`` dtype.

```
In [1]: pd.Series([], name='time',dtype=pd.Timestamp)
Out[1]: Series([], Name: time, dtype: object)
```

**Comment by petioptrv** [comment]
Hi, I am looking into contributing to open source projects and this looks like a good first-time contibution to start with. I'd like to give it a try.

**Comment by jreback** [comment]
great

contributing docs are http://pandas.pydata.org/pandas-docs/stable/contributing.html

**Comment by trevorpburke** [comment]
Put in a pull request for this issue. This is my first contribution attempt, so please let me know if I'm way off base here.

**Comment by petioptrv** [comment]
Should be addressing this at the source of the problem (raise anytime a function passes a non-valid dtype), or should we raise only when this happens in a Series function call?

**Comment by petioptrv** [comment]
607ae9c38e7d8f85d3a7f0b161545d5437afd285

**Comment by petioptrv** [comment]
607ae9c38e7d8f85d3a7f0b161545d5437afd285

**Comment by petioptrv** [comment]
Here is my suggestion for this issue: 607ae9c38e7d8f85d3a7f0b161545d5437afd285

**Comment by petioptrv** [comment]
Here is my suggestion for this issue: 607ae9c38e7d8f85d3a7f0b161545d5437afd285
