### ISSUE TITLE
DEPS: drop matplotlib < 1.4.3

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15543]
xref https://github.com/pandas-dev/pandas/pull/15540

so we are technically still testing 1.3.1 (numpy 1.8.2).

But this should be reasonable to officially drop support for these older versions.

xref to #15206  (drop numpy < 1.10)

though mpl 1.4.3 is build on numpy 1.9

**Comment by jreback** [comment]
cc @tacaswell

**Comment by tacaswell** [comment]
:+1: (5 months late)
