### ISSUE TITLE
DOC: doc build on travis timing out

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#15559]
For some reason, the doc build on travis started timing out since a couple of commits. See eg https://travis-ci.org/pandas-dev/pandas/builds/206994038. It just takes so long it hits the "The job exceeded the maximum time limit for jobs, and has been terminated." (around 50 min), while before the doc build on travis took between 20 and 30 min.

It started with the FrozenList changes (https://github.com/pandas-dev/pandas/commit/37fe2c4edddbec2c08d561667897a1ef5a18771c), but I don't see how that could cause this. 

I also don't directly see any changes in the environment that is created on travis to build the docs (eg both using sphinx 1.5.1, no change there).

**Comment by jreback** [comment]
hmm that is odd. we have certainly had occasional failures but nothing like this.

**Comment by jorisvandenbossche** [comment]
I also see this locally. It seems to be keep hanging on building the timeseries.rst file.

**Comment by jorisvandenbossche** [comment]
So my local build just finished and it took 92 min, instead of the normal \~ 20 min

**Comment by jreback** [comment]
https://travis-ci.org/pandas-dev/pandas/jobs/207696130

looks like it built, but some issue in reshape

**Comment by jreback** [comment]
so I think this is somehow constantly doing ``import matplotlib as plt`` but not really sure why / how this happens. maybe its something in the import cycle.

**Comment by gfyoung** [comment]
Let's watch this, but this hasn't been an issue for awhile.
