### ISSUE TITLE
if the logic of both queries is the same, why are the results different?

### ISSUE THREAD

**Issue by sirajpresswala** [pandas-dev/pandas#15554]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
#query 1 (the second part of the query does not work accurately on the attached dataset)
contains = df.eq(3.2).any(axis=1)
not_contains = ~df.isin([0.1,1.2]).any(axis=1)
print(df[contains & not_contains])

#query 2 (works accurately)
a = df.values
df_out = df.iloc[(a == 3.2).any(1) & (((a!=0.1) & (a!=1.2)).all(1))]


```
#### Problem description
the above two pandas data slicing queries (query 1 & query 2) are suppose to produce same output (logically). However, for the given data they do not. Additionally, query 1 works properly on the subset of the data but not on the complete data without throwing any errors. On the other hand, query 2 works properly on the attached dataset. this issue was first raised here: http://stackoverflow.com/questions/42542790/pandas-slice-rows-based-on-joint-condition
[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

#### Output of ``pd.show_versions()``
<details>
# Paste the output here pd.show_versions() here
pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: None.None

pandas: 0.19.2
nose: None
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.12.0
scipy: 0.18.1
statsmodels: 0.8.0
xarray: None
IPython: 5.1.0
sphinx: 1.4.8
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2016.7
blosc: None
bottleneck: None
tables: 3.2.2
numexpr: 2.6.2
matplotlib: 2.0.0
openpyxl: None
xlrd: 1.0.0
xlwt: None
xlsxwriter: None
lxml: 3.7.2
bs4: 4.5.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None
</details>

[df.txt](https://github.com/pandas-dev/pandas/files/815046/df.txt)

**Comment by jreback** [comment]
pls only a copy-pastable example.

**Comment by jorisvandenbossche** [comment]
@sirajpresswala you can use the link (https://github.com/pandas-dev/pandas/files/815046/df.txt) github created for the file you uploaded, to recreate the `df`, and show that code.

**Comment by jreback** [comment]
closing; please comment if you have a reproducible example. or indicate a bug.
