### ISSUE TITLE
DOC: remove Panel4D from the API docs

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#15579]
Panel4D is deprecated, so I think we can remove it from the API docs.

There is still a small mention of it in the data structures page: http://pandas-docs.github.io/pandas-docs-travis/dsintro.html#panel4d-and-panelnd-deprecated. I think that is sufficient, and still building the API docs (and all its methods) just adds a lot of time to building the docs.

**Comment by yinleon** [comment]
Hi, I would like to give this a try as my first commit :) Been working on Matplotlib for Docathon.

**Comment by jorisvandenbossche** [comment]
Closed by https://github.com/pandas-dev/pandas/pull/15598
