### ISSUE TITLE
The "no installation required" instructions refer to outdated wakari.io service

### ISSUE THREAD

**Issue by mandel01** [pandas-dev/pandas#15595]
#### Problem description

The current [Trying out pandas, no installation required!](http://pandas.pydata.org/pandas-docs/stable/install.html#trying-out-pandas-no-installation-required) instructions point to wakari.io, a service that is now part of Anaconda Cloud. I do not think that the hosted notebooks are still part of the service.

To test this, I created an Anaconda Cloud account. I cannot find any instructions for a web notebook interface with `pandas` already installed. For example [these instructions](https://docs.continuum.io/anaconda-cloud/using.html#Notebooks) point to the need to install `pandas` locally.

#### Proposed solution

I propose to delete the following text in [install.rst](https://github.com/pandas-dev/pandas/blob/303541eba0797f30c6f10084acbd522220cbc56a/doc/source/install.rst). If this sounds good I'll submit a pull request.

```
Trying out pandas, no installation required!
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The easiest way to start experimenting with pandas doesn't involve installing
pandas at all.

`Wakari <https://wakari.io>`__ is a free service that provides a hosted
`IPython Notebook <http://ipython.org/notebook.html>`__ service in the cloud.

Simply create an account, and have access to pandas from within your brower via
an `IPython Notebook <http://ipython.org/notebook.html>`__ in a few minutes.
```

**Comment by TomAugspurger** [comment]
Thanks. Removing that section sounds good.
