### ISSUE TITLE
Broken link in cookbook for read_csv

### ISSUE THREAD

**Issue by memilanuk** [pandas-dev/pandas#15605]
The second link in the section http://pandas.pydata.org/pandas-docs/stable/cookbook.html#csv
is broken.

I.e. the link [read_csv in action](http://wesmckinney.com/blog/?p=635) is supposed to go to Wes McKinney's blog, but returns a 404 error.  

A cursory look at said blog didn't result in anything jumping out at me as far as what *should* be the correct entry to link to.

**Comment by jreback** [comment]
@wesm did this change? ``http://wesmckinney.com/blog/?p=635``

**Comment by wesm** [comment]
Yeah, i migrated to pelican. think tha tlink may be http://wesmckinney.com/blog/update-on-upcoming-pandas-v0-10-new-file-parser-other-performance-wins/

**Comment by LorenzoCestaro** [comment]
Hi guys, this is my first attempt to contribute to an open source project. I have a branch ready with the fix: I changed the broken link with the one provided by @wesm.
[This](https://github.com/LorenzoCestaro/pandas/commit/006eefa210fed693030a7fa50374441ef7ee90bf) is the commit with the change on my fork.

I'd like to know if it is ok if I go ahead and submit a PR, also let me know if there is something else I should do before opening the PR (tests, builds, ...).
Thanks!

**Comment by jreback** [comment]
nope, go ahead an make a PR
