### ISSUE TITLE
DOC: api display

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15632]
our API page shows lots of useful information: http://pandas-docs.github.io/pandas-docs-travis/api.html and is pretty browsable.

But the toctree is mostly useless and encumbered by ``pandas.Sereies.rdiv`` which is pretty long (these tend to wrap).

So ideas to fix are:

- limit toc tree depth (``:maxdepth: 2``) (we set to 4 higher)
- try to find a way to control the title on the toc tree items

**Comment by jreback** [comment]
this might be fixed / ameliorted by #15556 so should explore that first.

**Comment by mroeschke** [comment]
it appears that the new api reference docs look pretty good https://pandas.pydata.org/pandas-docs/stable/reference/index.html

Going to close but happy to reopen if this doesn't look good.
