### ISSUE TITLE
pytest-xdist not found by conda

### ISSUE THREAD

**Issue by linebp** [pandas-dev/pandas#15643]
#### Code Sample

```shell
$ conda create -n pandas_dev python=3 --file ci/requirements_dev.txt
Fetching package metadata .........




PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels: 
  - pytest-xdist


You can search for packages on anaconda.org with


    anaconda search -t conda pytest-xdist
```
#### Problem description
When following the documentation on how to contribute to the code, I ran into the above problem.  pytest-xdist is not to be found in the standard conda channels, you need to add the conda-forge channel. The documentation does not help you with this. See also this [discussion](https://groups.google.com/forum/#!topic/pydata/Tskyx64QmPM).

This can be resolved by either adding a note explaining the need to add conda-forge channel to conda or simply removing pytest-xdist as a requirement for a dev environment.

**Comment by jorisvandenbossche** [comment]
I would remove pytest-xdist from the requirements file (one thing less to explain to new contributors. It is explained in the section on testing how to install it). 
Would you want to do a PR for that?

**Comment by linebp** [comment]
yes, I can try that.
