### ISSUE TITLE
CLN: cleanup rank tests

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15640]
we have rank tests in:

Create a new ``pandas/tests/series/test_rank``
- ``pandas/tests/series/test_analytics``

Create a new ``pandas/tests/frame/test_rank``
- ``pandas/tests/frame/test_analytics``

- ``pandas/tests/test_algos``

Let's remove this and split among the other three
- ``pandas/tests/test_stats``

**Comment by rouzazari** [comment]
@jreback, just so I understand: the end result will have two files (`series/test_rank` and `frame/test_rank`), correct? 

The `rank`-related tests from all four source files (`series/test_analytics`, `frame/test_analytics`, `test_algos`, and `test_stats`) should end up in the relevant `test_rank` files. All unrelated (i.e. non-`rank`) tests should remain in the existing files.

**Comment by jreback** [comment]
yes though you might have some common tests in test_algos (if that makes sense)

**Comment by rouzazari** [comment]
Great. I submitted a PR. I believe the tests that remain in `test_algos` should remain there because those tests are not specifically related to `Series` or `DataFrame`; they seem to be related to testing `rank` in general.
