### ISSUE TITLE
How does the community feel about type hinting?

### ISSUE THREAD

**Issue by brmc** [pandas-dev/pandas#15661]
I know some people are philosophically opposed to it.  I'm not sure where the pandas community stands, but I feel pandas would significantly benefit from this.  return types at the very least would be especially helpful for the people using IDEs. If there are no objections, I'll get started on this

**Comment by jorisvandenbossche** [comment]
See https://github.com/pandas-dev/pandas/issues/14468 and https://github.com/pandas-dev/pandas2/issues/18. Let's continue further in those issues. But so I think we are certainly open to it, although there are some practicalities to work out.
