### ISSUE TITLE
~

### ISSUE THREAD

**Issue by ktoomey86** [pandas-dev/pandas#15673]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

```
#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

#### Output of ``pd.show_versions()``

<details>
# Paste the output here pd.show_versions() here

</details>

**Comment by jorisvandenbossche** [comment]
@ktoomey86 did you intend to open an actual issue? (if so, you can always edit this existing one instead of opening a new one)
