### ISSUE TITLE
Append Series to Series in place

### ISSUE THREAD

**Issue by egorf** [pandas-dev/pandas#15672]
#### As I can see, this is the intended way to append one Series to another

```python
import pandas
s = pandas.Series([0, 1, 2])
new_s = s.append(s)
```
#### Problem description

I think it is confusing that the append call does not modify the `s` Series instance in place, like it works with Python lists. 

Also, what is the intended way for extending a Series, if the data, like some kind of measurements,  is accumulated over time? 

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-28-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: ru_RU.UTF-8
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.19.2
nose: 1.3.7
pip: 9.0.1
setuptools: 20.7.0
Cython: 0.23.4
numpy: 1.11.0
scipy: 0.17.0
statsmodels: None
xarray: None
IPython: None
sphinx: 1.3.6
patsy: None
dateutil: 2.4.2
pytz: 2014.10
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.4.1
html5lib: 0.999
httplib2: None
apiclient: None
sqlalchemy: 1.1.3
pymysql: None
psycopg2: 2.7.1 (dt dec pq3 ext lo64)
jinja2: 2.8
boto: None
pandas_datareader: None
</details>

**Comment by jorisvandenbossche** [comment]
Almost all methods in pandas *return a new object*, instead of mutating in place, and this is not something we are going to change 
(there are a few where inplace=True, and those typically stem from being consistent with list/array, eg `Series.sort`, but we are rather deprecating those)

Also, what is the intended way for extending a Series, if the data, like some kind of measurements, is accumulated over time?

You can use `append` for that as you did in the example. More general is `concat` (you can concat multiple parts at once). Typically you first gather all pieces in a list, and only then concatenate them at once using `concat`.

**Comment by egorf** [comment]
Hi and thanks for the fast answer,

What would be the correct approach if I want to accumulate some data over time and, for example, know the standard deviation at each step?

I can't seem to find a way to calculate the **std** iteratively, as I need to recreate the Series every time new data comes along. 

Is this something pandas is not designed for?

**Comment by chris-b1** [comment]
@egorf - if the data is reasonably sized and you're not super performance bound, you can just keep recreating the `Series`.  Each recreation will take a copy of the underlying data, which as long as your number of iterations is reasonable, is pretty fast.

If that's an issue, the other option is create a large, empty array / series with a single allocation, then place data into it.  More complex, but something like this.

```
data = np.empty(100000)
data[:] = np.nan
s = pd.Series(data)

loc = 0
for new_data in source:  # your iterative data source
    n = len(new_data)
    s.iloc[loc:n+loc] = new_data
    loc += len(new_data)
    # iterative std
    new_std = s.iloc[:loc].std()
```

**Comment by egorf** [comment]
Thanks for the tip, but I decided to go with the [online algorithm](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Online_algorithm) instead and use for pandas for data storage and manipulation, rather than accumulation.
