### ISSUE TITLE
BUG: .iloc indexing with duplicates

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#15686]
#### Code Sample, a copy-pastable example if possible

```python
In [2]: df1 = pd.DataFrame([{'A': None, 'B': 1}, {'A': 2, 'B': 2}])
   ...: df2 = pd.DataFrame([{'A': 3, 'B': 3}, {'A': 4, 'B': 4}])
   ...: df = pd.concat([df1, df2], axis=1)
   ...: df.iloc[0, 0] = df.iloc[0, 2]
   ...: df
   ...: 
Out[2]: 
     A  B    A  B
0  3.0  1  3.0  3
1  2.0  2  4.0  4
```
#### Problem description

The third column shouldn't have changed type

#### Expected Output
``` python
Out[2]: 
     A  B  A  B
0  3.0  1  3  3
1  2.0  2  4  4
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: 32df1e6ae452f7ddd31dc41fa613992493eb51c4
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.7.0-1-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.utf8
LOCALE: it_IT.UTF-8

pandas: 0.19.0+597.g32df1e6ae
pytest: 3.0.6
pip: 9.0.1
setuptools: 33.1.1
Cython: 0.25.2
numpy: 1.12.0
scipy: 0.18.1
xarray: None
IPython: 5.1.0.dev
sphinx: 1.4.9
patsy: 0.3.0-dev
dateutil: 2.5.3
pytz: 2016.7
blosc: None
bottleneck: 1.2.0
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.0
openpyxl: 2.3.0
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.6
lxml: 3.7.1
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.8
s3fs: None
pandas_gbq: None
pandas_datareader: 0.2.1

</details>

**Comment by toobaz** [comment]
This looks very similar to #12991 , but it's a different bug: this is a bug in the indexing code (I know because I have a fix), #12991 is a bug in ``BlockManager``.

**Comment by toobaz** [comment]
(This is due to ``setter`` in ``pandas/core/indexing.py`` ultimately relying on ``obj[.]`` - and hence on labels - to set values)

**Comment by jreback** [comment]
yeah this should use an indexer
