### ISSUE TITLE
request for implementation of astropy.units

### ISSUE THREAD

**Issue by JWDobken** [pandas-dev/pandas#15698]
The astropy package is excellent for calculations with units!
Is there a method to pass the Units (from astropy import units as u) to a pandas Series or DataFrame?

Otherwise, would it be nice to implement this approach somehow?

**Comment by jreback** [comment]
see various discussion here: https://github.com/pandas-dev/pandas/issues/10349 (and linked).

this is not going to happen before pandas 2 as the lack of dtype flexibility within numpy. see https://github.com/pandas-dev/pandas2/issues/24 as well.

though even *with* a dtype this will require some work.

If you want to contribute would be greatly appreciated (even tests / examples / partial impl are helpful).
