### ISSUE TITLE
Infer Decimal dtype

### ISSUE THREAD

**Issue by dhirschfeld** [pandas-dev/pandas#15690]
```python
In [15]: from decimal import Decimal

In [16]: s = pd.Series([Decimal(3), Decimal(1), Decimal(4)])
    ...: s
Out[16]: 
0    3
1    1
2    4
dtype: object

In [17]: s.dtype
Out[17]: dtype('O')

In [18]: pd.lib.infer_dtype(s)
Out[18]: 'mixed'

In [19]: set(map(type, s))
Out[19]: {decimal.Decimal}
```
It would be nice if the `infer_dtype` function could determine if the column was all of decimal type which could be useful when working with databases which return data as decimal types

**Comment by jreback** [comment]
you can do this in master
```
In [2]: from pandas.types.common import is_decimal

n [4]: s.apply(is_decimal).all()
Out[4]: True
```

your suggestion is quite easy to do if you'd like to submit a PR! (FYI, ``pandas._libs/src/inference.pyx`` is the new home of ``infer_dtype``)

**Comment by margaret** [comment]
I'm going to work on this (pycon sprints)

**Comment by jorisvandenbossche** [comment]
@jreback Repeating my comment from on the PR: What I am wondering is what are potential consequences of such a change. As there are quite some places in the codebase where we wheck if the inferred type is 'mixed', so changing this would mean potential changes in the taken code path for Decimal objects (with potential changes in behaviour). 
But don't know if those cases in the code would be relevant for Decimal objects.

**Comment by jreback** [comment]
@jorisvandenbossche https://github.com/pandas-dev/pandas/pull/16426#issuecomment-303235278

after the PR is merged, should create an issue to *use* the new inference (though as I pointed, maybe not that useful ATM).
