### ISSUE TITLE
FUT: logging option for future changes

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15703]
https://github.com/pandas-dev/pandas2/issues/69

if we setup an option for a namespace ``pandas.options.future`` then can turn things on at some point to provide logging / warnings / raise for a compatibility layer.

the xref issue is about ``.values`` and how in the future we don't want to support this. So provide a way to log/warn about this way ahead of time.

**Comment by jbrockmendel** [comment]
closeable?  i dont see any interest
