### ISSUE TITLE
Inconsistent date range behaviour

### ISSUE THREAD

**Issue by ruidc** [pandas-dev/pandas#1573]
pandas.DatetimeIndex(start=datetime.datetime(2012, 2, 28), freq=pandas.offsets.YearEnd(month=2), periods=10)
works, but not 
pandas.DatetimeIndex(start=datetime.datetime(2012, 2, 20), freq=pandas.offsets.MonthEnd(day=20), periods=10)

**Comment by petehuang** [comment]
Hi all,

This issue was first discussed nearly 4.5 years ago. Have there been any developments since then? My feeling is no, but it also sounds like there wasn't much traction for this enhancement either. My gut instinct is to close this issue.

What do you think?

**Comment by jbrockmendel** [comment]
I think this is closed by #18226

**Comment by jorisvandenbossche** [comment]
Indeed, thanks

**Comment by jorisvandenbossche** [comment]
Closed by #18226
