### ISSUE TITLE
BUG: replace of numeric by string / dtype coversion

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15743]
xref #12747 

This was an item not closed by #12780 (but listed in #12747)

```
In [2]: pd.Series([1,2,3]).replace('1', np.nan)
Out[2]: 
0    NaN
1    2.0
2    3.0
dtype: float64
```

**Comment by ucals** [comment]
Output should be:
```
0    1.0
1    NaN
2    3.0
dtype: float64
```
right?

**Comment by jreback** [comment]
The result should be the same as this. IOW the *string* ``'1'`` is NOT found in the original dataset (its a numeric 1). So should return unchanged.  Step thru the code and you will see the modification happening, this is numpy behavior, but its not normal / natural in the real world :>

```
In [2]: pd.Series([1,2,3]).replace('10', np.nan)
Out[2]: 
0    1
1    2
2    3
dtype: int64

```
