### ISSUE TITLE
TST: full dtype tests for .drop_duplicates and .duplicated

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15752]
https://github.com/pandas-dev/pandas/pull/15738#issuecomment-287925070
xref #15738 

we exercise tests for ``.drop_duplicates`` &  ``.duplicated`` in various places

- for series -> ``pandas/tests/series/test_analytics.py``
- for dataframe -> ``pandas/test/frame/test_analytics.py``
- for index -> ``pandas/tests/test_base.py``
- ``datetimes`` -> ``pandas/tests//indexes/datetimes/test_ops.py``
- ``period`` -> ``pandas/tests//indexes/period/test_ops.py``
- ``categorical`` -> ``pandas/tests//test_categorical.py``
- ``timedelta`` -> ``pandas/tests//indexes/timedeltas/test_ops.py``

I think we are a little light on the ``categorical`` ones (esp need to exercise with categories of int, datetime, timedelta, bool)

``bool`` and a battery that covers all ``int`` & ``uint`` & ``float`` would be nice as well.

could certainly take multiple PR's to close this issue (if multiple people want to do this).

**Comment by tmnhat2001** [comment]
Hi, could someone take a look at the test cases added in PR 17974? The test cases are for Series. If they are OK, I'll do the same to the remaining tests.
#17974

**Comment by mroeschke** [comment]
I think we have testing for this now so closing
