### ISSUE TITLE
BUG: PandasAutoDateLocator num_days calculation is wrong

### ISSUE THREAD

**Issue by dadkins** [pandas-dev/pandas#15753]
This line in PandasAutoDateLocator looks like it's missing some parentheses.

https://github.com/pandas-dev/pandas/blob/master/pandas/tseries/converter.py#L264
        num_days = ((delta.years * 12.0) + delta.months * 31.0) + delta.days

I stepped through here and with a delta of 5 years, num_days was 60! It's easy enough to fix:

        num_days = (((delta.years * 12.0) + delta.months) * 31.0) + delta.days

**Comment by jorisvandenbossche** [comment]
That indeed seems to be the case.

Do you have a plot example that shows 'incorrect' behaviour because of this? That would make it possible to check that it actually changes the look in a positive way

**Comment by mroeschke** [comment]
Looks like [PR 14716](https://github.com/pandas-dev/pandas/pull/14716) addressed this but stalled.

**Comment by jorisvandenbossche** [comment]
Good catch. 
Maybe we should just merge it, without a test / example of visual change, as it is clearly a mistake in the code. Although a confirmation with an actual example which improves due to this change would still be useful.

**Comment by jorisvandenbossche** [comment]
Actually, looking at that code, I don't think we are going to find an example:

```
num_days = ((delta.years * 12.0) + delta.months * 31.0) + delta.days
num_sec = (delta.hours * 60.0 + delta.minutes) * 60.0 + delta.seconds
tot_sec = num_days * 86400. + num_sec

if abs(tot_sec) < self.minticks:
    ....
```

`tot_sec` (and thus `num_days`) is only used to check whether it is smaller than `minticks` which is typically a number like 5. So once you have hours, let alone years, of data, the `tot_sec` will always be a huge number. 
@mroeschke Or am I missing something?

**Comment by mroeschke** [comment]
Not too familiar with this section of the codebase, but agreed that this shouldn't have an obvious change. The `if abs(tot_sec) < self.minticks:` block just looks like it's adjusting the axis to plot data that spans maybe seconds(?), in which case `num_days` would be 0 if triggered (which occurs with the current code and the proposed change.)

**Comment by jorisvandenbossche** [comment]
I merged the PR, so this can be closed. 
@dadkins Thanks for the report

**Comment by dadkins** [comment]
Thank you for the quick fix.
