### ISSUE TITLE
CLN/DEPR: html.border option -> display.html.border

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15793]
xref #11784
 
```
html.border : int
    A ``border=value`` attribute is inserted in the ``<table>`` tag
    for the DataFrame HTML repr.
    [default: 1] [currently: 1]
```

should migrate this (by deprecation) and moving to a new option ``display.html.border`` to keep in-line with our namespacing.

**Comment by rdk1024** [comment]
I'll take a look at this during SciPy 2017 sprint weekend.
