### ISSUE TITLE
ERR: better error message for trying to concat non-pandas objects

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15796]
```
In [3]: pd.concat([Series(), 'foo'])
TypeError: cannot concatenate a non-NDFrame object
```

trivially ``non-NDFrame`` -> ``non-pandas``. but I think even better would be something like

```
In [4]: objs = [Series(), 'foo']

In [7]: "cannot concatenate [{pandas}] with non-pandas objects of type [{non_pandas}]".format(
   ...: pandas=','.join(set([str(o.__class__.__name__) for o in objs if isinstance(o, pandas.core.generic.NDFrame)])),
   ...: non_pandas=','.join(set([str(type(o)) for o in objs if not isinstance(o, pandas.core.generic.NDFrame)])))
Out[7]: "cannot concatenate [Series] with non-pandas objects of type [<class 'str'>]"
```

**Comment by petioptrv** [comment]
I would like to take care of this one. There could be more than two objects in the concatenation, so how about "cannot concatenate objects of type [<class 'str'>], all objects must be pandas objects"?

**Comment by jreback** [comment]
@petioptrv yes that's why I put the list comprehension and set things. Should work with many objects.

Its just meant to be more instructive to the user.

**Comment by jorisvandenbossche** [comment]
I think "pandas objects" is still a bit vague. Eg  an Index, or a Timestamp are also pandas objects, but cannot be concatenated. 
Are there other things than Series, DataFrame and Panel that can be concatenated? If not, let's just those in the error message?

TypeError: cannot only concatenate with Series, DataFrame or Panel objects, an object of type [<class 'str'>] was passed.

**Comment by higs4281** [comment]
Looking at this.
