### ISSUE TITLE
read_csv arguments: can we have skipcols and userows?

### ISSUE THREAD

**Issue by pseth** [pandas-dev/pandas#15799]
Is there a reason why `read_csv` has a `usecols` and `skiprows` as arguments, but not `skipcols` and `userows`? Is this to avoid parameter checks or something more fundamental than that?

It would be nice to have all four options to avoid clunky inversions of the type `usecols = columns.remove(unwanted_col)`.

**Comment by jreback** [comment]
this is essentially a duplicate of the now closed: https://github.com/pandas-dev/pandas/issues/10882

``usecols`` accepts a callable, to allow arbitrary evaluation of which columns to use.

in a similar vein, ``skiprows`` accepts a callable as well.

The defaults make the most sense here, e.g. generally you want to keep columns (out of a larger set) and skip (a small subset of rows).

I am not anti the counter parts, but this is just one more keyword and added complexity.

**Comment by gfyoung** [comment]
Yep, I'm in agreement with @jreback here.  Especially since we can accept callables for both inputs you can emulate `skipcols` and `userows` as follows:
~~~python
skipcols = [...]
userows = [...]
read_csv(..., usecols=lambda x: x not in skipcols,
              skiprows=lambda x: x not in userows])
~~~

**Comment by pseth** [comment]
@gfyoung Ah, I did not realise that was possible, the online documentation for [read_csv](pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) doesn't seem to be up to date. That is indeed a more elegant solution over possibly conflicting arguments.

**Comment by jreback** [comment]
This feature is in 0.20.0 which is not released yet, docs are in the dev-docs: http://pandas-docs.github.io/pandas-docs-travis/
