### ISSUE TITLE
Unable to initiate pandas library ..

### ISSUE THREAD

**Issue by skalyanapu-mtuity** [pandas-dev/pandas#15814]
Error : 

raceback (most recent call last):
  File "ForecastingModel.py", line 7, in <module>
    import statsmodels.api as sm
  File "/usr/lib/python2.7/site-packages/statsmodels-0.8.0-py2.7-linux-i686.egg/statsmodels/__init__.py", line 8, in <module>
    from .tools.sm_exceptions import (ConvergenceWarning, CacheWriteWarning,
  File "/usr/lib/python2.7/site-packages/statsmodels-0.8.0-py2.7-linux-i686.egg/statsmodels/tools/__init__.py", line 1, in <module>
    from .tools import add_constant, categorical
  File "/usr/lib/python2.7/site-packages/statsmodels-0.8.0-py2.7-linux-i686.egg/statsmodels/tools/tools.py", line 9, in <module>
    import pandas as pd
  File "/usr/lib/python2.7/site-packages/pandas-0.19.2-py2.7-linux-i686.egg/pandas/__init__.py", line 39, in <module>
    from pandas.core.api import *
  File "/usr/lib/python2.7/site-packages/pandas-0.19.2-py2.7-linux-i686.egg/pandas/core/api.py", line 32, in <module>
    from pandas.util.depr_module import _DeprecatedModule
  File "/usr/lib/python2.7/site-packages/pandas-0.19.2-py2.7-linux-i686.egg/pandas/util/depr_module.py", line 7, in <module>
    import importlib
ImportError: No module named importlib

This is what i see , when execute I the python file ..

1) Python version : 2.7.3
2) Installed importlib ib both ways using pip and executeable setup.pu file ..
    though I installed importlib and event mapped it to "/usr/lib/python2.7/site-packages" ..

Any suggestions please , let me know if i'm missing anything??

**Comment by jreback** [comment]
> Installed importlib ib both ways using pip and executeable setup.pu file ..
though I installed importlib and event mapped it to "/usr/lib/python2.7/site-packages" ..

``importlib`` is included in the standard library.

see installation instructions: http://pandas.pydata.org/pandas-docs/stable/install.html

your installation setup is not right. but not enough detail to say what is wrong. 

``pip install pandas`` should just work.

**Comment by skalyanapu-mtuity** [comment]
The response to pip install pandas 

root@yocto01:~# < pip install pandas >
Requirement already satisfied: pandas in /usr/lib/python2.7/site-packages/pandas-0.19.2-py2.7-linux-i686.egg
Requirement already satisfied: python-dateutil in /usr/lib/python2.7/site-packages (from pandas)
Requirement already satisfied: pytz>=2011k in /usr/lib/python2.7/site-packages (from pandas)
Requirement already satisfied: numpy>=1.7.0 in /usr/lib/python2.7/site-packages (from pandas)
Requirement already satisfied: six>=1.5 in /usr/lib/python2.7/site-packages (from python-dateutil->pandas)

OS  : yocto image ...
Still I get the same error : ImportError: No module named importlib ..

**Comment by jreback** [comment]
> OS : yocto image ...

what is this?

**Comment by skalyanapu-mtuity** [comment]
Sorry , linux yocto image ...

**Comment by jreback** [comment]
@skalyanapu-mtuity https://www.yoctoproject.org/ ?

is this fully compliant? does numpy work?

you might have to setup your path and such.

**Comment by jreback** [comment]
http://stackoverflow.com/questions/28223129/yocto-install-numpy

**Comment by jreback** [comment]
this is not a supported platform, though I think it should work. if you can provide a lot more detail its possible someone can help.
