### ISSUE TITLE
dtype issue

### ISSUE THREAD

**Issue by jmbertoncelli** [pandas-dev/pandas#15818]
Hello,  I am having an issue with pandas that is returning a mixed-integer dtype for a column.  The csv file has been exported from an hadoop environment using !hadoop fs -getmerge.  Now, the issue is that when I do groupby on the spark dataframe I get only one group with value 0 and that is exactly what I do expect.  When it comes to pandas reading the csv version then I get two groups...  the first group value is 0 and the second group value is 0 as well...  I cannot understand why I do have a mixed dtype for this column when the source system is correct.  Do you think that the hadoop fs -getmerge could introduce some unexpected behaviors?

 
1)
df[['f55_admin_address_same_spon_ind']].applymap(lambda x : str(x)).groupby('f55_admin_address_same_spon_ind').size()

return:
f55_admin_address_same_spon_ind
0                                  1125282
f55_admin_address_same_spon_ind        199
dtype: int64

2)

df[['f55_admin_address_same_spon_ind']].applymap(lambda x : x).groupby('f55_admin_address_same_spon_ind').size()

return:
f55_admin_address_same_spon_ind
0                                  314473
0                                  810809
f55_admin_address_same_spon_ind       199
dtype: int64

**Comment by jmbertoncelli** [comment]
FYI: I did apply a str() to convert to from unicode to ascii  (remove the mixed datatype) but this does not explain how the mixed datatype is pop-up from the CSV file.

**Comment by jreback** [comment]
@jmbertoncelli we need a reproducible example.

**Comment by jmbertoncelli** [comment]
I can give you the file but it is about 178Meg and the notebook as well.

**Comment by jreback** [comment]
no, you need to show code that you are using to read it, ``df.info()`` and ``df.head()`` as well as the first few lines of the file.

**Comment by jreback** [comment]
pls comment if you have a repro example
