### ISSUE TITLE
BUG: not propogating MultiIndex names when only some are set on slicing

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15826]
```
In [3]: df = pd.DataFrame(np.arange(4), columns=['value'], index=pd.MultiIndex.from_product([list('AB'), [0, 1]], names=['foo', 'bar']))

In [4]: df2 = pd.DataFrame(np.arange(4), columns=['value'], index=pd.MultiIndex.from_product([list('AB'), [0, 1]], names=['foo', None]))

In [5]: df
Out[5]: 
         value
foo bar       
A   0        0
    1        1
B   0        2
    1        3

In [6]: df.loc['A']
Out[6]: 
     value
bar       
0        0
1        1

In [7]: df.loc[['A']]
Out[7]: 
         value
foo bar       
A   0        0
    1        1

In [8]: df2.loc['A']
Out[8]: 
   value
0      0
1      1

In [9]: df2.loc[['A']]
Out[9]: 
       value
foo         
A   0      0
    1      1

```

So I would expect that [8] would be the same as [6]

**Comment by funnycrab** [comment]
Could you please be so kind as to say a little bit more about why you expect that [8] should be the same as [6]? Since df2 doesn't even know the index name 'bar', how can it print it out for ```df2.loc['A']```?

**Comment by jreback** [comment]
hmm, looking at this again, this is correct, meaning no issue. must have been something else.....

**Comment by jreback** [comment]
@jbrockmendel reopened i think was accidentally closed

(note this might be fixed as well)

**Comment by jbrockmendel** [comment]
I'm with 2017-era commenters: this looks right to me (both in the OP and in main).  Re-closing.
