### ISSUE TITLE
BUG: False Timestamp returned

### ISSUE THREAD

**Issue by erigaut** [pandas-dev/pandas#15823]
#### Code Sample, a copy-pastable example if possible

```python
In [3]: pd.Timestamp('2017-03-26 00:00', tz='Europe/Paris')
Out[3]: Timestamp('2017-03-26 00:00:00+0100', tz='Europe/Paris')

In [4]: pd.Timestamp('2017-03-26 01:00', tz='Europe/Paris')
Out[4]: Timestamp('2017-03-26 00:00:00+0100', tz='Europe/Paris')

In [5]: pd.Timestamp('2017-03-26 02:00', tz='Europe/Paris')
Out[5]: Timestamp('2017-03-26 01:00:00+0100', tz='Europe/Paris')

In [6]: pd.Timestamp('2017-03-26 03:00', tz='Europe/Paris')
Out[6]: Timestamp('2017-03-26 03:00:00+0200', tz='Europe/Paris')
```
#### Problem description

The timestamp returned are wrong

#### Expected Output

```python
In [3]: pd.Timestamp('2017-03-26 00:00', tz='Europe/Paris')
Out[3]: Timestamp('2017-03-26 00:00:00+0100', tz='Europe/Paris')

In [4]: pd.Timestamp('2017-03-26 01:00', tz='Europe/Paris')
Out[4]: Timestamp('2017-03-26 01:00:00+0100', tz='Europe/Paris')

In [5]: pd.Timestamp('2017-03-26 02:00', tz='Europe/Paris')
Out[5]: Timestamp('2017-03-26 02:00:00+0100', tz='Europe/Paris')

In [6]: pd.Timestamp('2017-03-26 03:00', tz='Europe/Paris')
Out[6]: Timestamp('2017-03-26 03:00:00+0200', tz='Europe/Paris')
```
#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.0.final.0
python-bits: 64
OS: Linux
OS-release: 4.8.0-42-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.19.2
nose: 1.3.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.11.3
scipy: 0.18.1
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.5.1
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: 1.2.0
tables: 3.3.0
numexpr: 2.6.1
matplotlib: 2.0.0
openpyxl: 2.4.1
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.2
bs4: 4.5.3
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.1.5
pymysql: None
psycopg2: None
jinja2: 2.9.4
boto: 2.45.0
pandas_datareader: None
</details>

**Comment by jreback** [comment]
this is the same as #15777 and linked issues. 

However, you should really localize these times.

```
In [9]: pd.Timestamp('2017-03-26 01:00').tz_localize('Europe/Paris')
Out[9]: Timestamp('2017-03-26 01:00:00+0100', tz='Europe/Paris')

In [10]: pd.Timestamp('2017-03-26 03:00').tz_localize('Europe/Paris')
Out[10]: Timestamp('2017-03-26 03:00:00+0200', tz='Europe/Paris')
```

note that [5] is not valid
```
In [19]: pd.Timestamp('2017-03-26 02:00').tz_localize('Europe/Paris')
NonExistentTimeError: 2017-03-26 02:00:00
```
