### ISSUE TITLE
API: groupby.transform()

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15831]
```
In [4]: df = pd.DataFrame({'A':[1,1,2,2],'B':[1,2,3,4]})

In [5]: df.groupby('A').transform('max')
Out[5]: 
   B
0  2
1  2
2  4
3  4
```

Might be nice to have a deferred ``.transform()`` object (notice it doesn't take any args).
```
In [7]: df.groupby('A').transform().max()
```

Pretty sure this could be back-compat.

**Comment by jbrockmendel** [comment]
It isn't clear to me that this would simplify things.  Unless that changes, I'm -1.

**Comment by rhshadrach** [comment]
Agreed - closing.
