### ISSUE TITLE
Validation order In read_gbp

### ISSUE THREAD

**Issue by KeiMae** [pandas-dev/pandas#15851]
I look the algolithm validate index_col's after connecting to bq. However I think this validation before connecting is convenience.

So
```python:pandas/pandas/io/gbq.py
        if index_col is not None:
            if index_col in final_df.columns:
                final_df.set_index(index_col, inplace=True)
            else:
                raise InvalidColumnOrder(
                    'Index column "{0}" does not exist in DataFrame.'
                    .format(index_col)
                )
```
line 713 to 720 move to line 697

**Comment by KeiMae** [comment]
Sorry my misunderstanding. It's optional...
However It don't work when I set nothing....

**Comment by jreback** [comment]
support for gbq has moved to https://github.com/pydata/pandas-gbq

you can file an issue there, though pls show a reproducible example.
