### ISSUE TITLE
another to_json float precision bug

### ISSUE THREAD

**Issue by funnycrab** [pandas-dev/pandas#15864]
#### Code Sample, a copy-pastable example if possible

```python
>>> pd.DataFrame([dict(a_float=0.95)]).to_json(double_precision=1)
'{"a_float":{"0":0.1}}'
>>> pd.DataFrame([dict(a_float=1.95)]).to_json(double_precision=1)
'{"a_float":{"0":1.1}}'
 >>> pd.DataFrame([dict(a_float=-1.95)]).to_json(double_precision=1)
'{"a_float":{"0":-1.1}}'
>>> pd.DataFrame([dict(a_float=0.995)]).to_json(double_precision=2)
'{"a_float":{"0":0.1}}'
>>> pd.DataFrame([dict(a_float=0.9995)]).to_json(double_precision=3)
'{"a_float":{"0":0.1}}'
```
#### Problem description

This issue is very similar to [#15716](https://github.com/pandas-dev/pandas/issues/15716). 

Just this one  reveals a more generalized pattern. 

#### Expected Output
```python
'{"a_float":{"0":1.0}}'
'{"a_float":{"0":2.0}}'
'{"a_float":{"0":-2.0}}'
'{"a_float":{"0":1.00}}'
'{"a_float":{"0":1.000}}'
```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 3.19.0-42-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_HK.UTF-8
LOCALE: en_HK.UTF-8

pandas: 0.19.2
nose: 1.3.7
pip: 8.1.2
setuptools: 27.2.0
Cython: 0.24.1
numpy: 1.11.3
scipy: 0.18.1
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.4.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2016.6.1
blosc: None
bottleneck: 1.1.0
tables: 3.2.3.1
numexpr: 2.6.2
matplotlib: 1.5.3
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.3
lxml: 3.6.4
bs4: 4.5.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.42.0
pandas_datareader: None
</details>

**Comment by funnycrab** [comment]
After a quick check, I believe this issue may not be related to [here](https://github.com/pandas-dev/pandas/blob/61f6f6333fb7bb2dedf82736aee6c9878382a06f/pandas/_libs/src/ujson/python/objToJSON.c#L2368) as pointed out in the [#15716](https://github.com/pandas-dev/pandas/issues/15716).

It seems to have something to do with rollover handling implemented [here](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/src/ujson/lib/ultrajsonenc.c#L826).

A [pull request](https://github.com/pandas-dev/pandas/pull/15865) has been submitted for fixing this issue. Please be so kind as to take a look.

**Comment by jreback** [comment]
these seem almost the same, simply roll them together.
