### ISSUE TITLE
Enable auto-cancellation on Travis

### ISSUE THREAD

**Issue by bashtage** [pandas-dev/pandas#15878]
Travis has rolled out a new feature (beta) that will automatically cancel builds when a new build appears in a branch. This can help shorten build time when someone commits a small number of small changes to an open PR.  This seems like a good feature of have on PRs (but not master) and can help with "push spam".

@jreback

**Comment by jreback** [comment]
1bcb671877287be731ce677aaf96686278b69f9a

already enabled! (this commit is for putting in our *own* auto-cancel).

note that you need to enable it on your *own* branch. I suppose we could document that.

**Comment by jreback** [comment]
actually its on master as well. because if you have an open PR, then you push again, we *need* and *want* it to cancel the previous one (on master).

**Comment by bashtage** [comment]
There is no way to tell what other repos settings are on Travis, so I though I would check that it was on.  Might help a lot.

**Comment by jreback** [comment]
yeah if you want to create an issue about updating: http://pandas-docs.github.io/pandas-docs-travis/contributing.html#test-driven-development-code-writing

IOW about CI interactions would be fine. (IOW the meaning of 'green' builds and such).

I find newbie are confused by this actually.
