### ISSUE TITLE
BUG: first() loses the timezone in groupby

### ISSUE THREAD

**Issue by chrisaycock** [pandas-dev/pandas#15884]
need a systematic test of all groupby methods here.

This works as expected:

```
pd.DataFrame({'time': [pd.Timestamp('2012-01-01 13:00:00+00:00')],
              'A': [3]}).groupby('A', as_index=False).head(1)
```

However, this loses the timezone:

```
pd.DataFrame({'time': [pd.Timestamp('2012-01-01 13:00:00+00:00')],
              'A': [3]}).groupby('A', as_index=False).first()
```

**Comment by jreback** [comment]
so this falls down: https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby.py#L1929

essentially ``.values`` is a DatetimeIndex at this point, not a numpy array. (because its passed ``block.values`` higher up). So this needs to be handled.

**Comment by mroeschke** [comment]
I believe the solution to this issue xrefs to #19026 [(here),](https://github.com/pandas-dev/pandas/blob/0.22.x/pandas/core/groupby.py#L1262) where `np.asarray` will convert the datetimetz dtype to just a datetime dtype.
