### ISSUE TITLE
DOC: document is_* type methods

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#15895]
Most of the methods in [here](https://github.com/pandas-dev/pandas/blob/master/pandas/core/dtypes/common.py) are exposed publicly thru ``pandas.api.types``.

We would like to write full doc-strings for these (and examples!).

Multiple people could work on this.

**Comment by gfyoung** [comment]
@jreback : Could you update the URL in the issue to point to `pandas.core.dtypes.common.py` now?

**Comment by jreback** [comment]
done
