### ISSUE TITLE
import error: ImportError: No module named 'pandas.tools'

### ISSUE THREAD

**Issue by apiszcz** [pandas-dev/pandas#15893]
Pandas 0.19.2, Windows Server 2012
Same setup runs ok elsewhere assume it is a missing library.

```
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib\pandas\__init__.py", line 39, in <module>
    from pandas.core.api import *
  File "lib\pandas\core\api.py", line 10, in <module>
    from pandas.core.groupby import Grouper
  File "lib\pandas\core\groupby.py", line 40, in <module>
    from pandas.core.frame import DataFrame
  File "lib\pandas\core\frame.py", line 72, in <module>
    from pandas.core.series import Series
  File "lib\pandas\core\series.py", line 2974, in <module>
    import pandas.tools.plotting as _gfx  # noqa
ImportError: No module named 'pandas.tools'
>>> quit()
```

**Comment by jreback** [comment]
usually this means you have an installation issue. I would uninstall / reinstall (via conda) or pip

**Comment by apiszcz** [comment]
concur, thanks.

**Comment by RubensZimbres** [comment]
In fact this may be another lind of issue. For instance:

`from pandas.tools.plotting import autocorrelation_plot`

Throws an error: `ModuleNotFoundError: No module named 'pandas.tools'`

However, `from pandas.plotting import autocorrelation_plot` works perfectly.

**Comment by srinibujjay** [comment]
Thanks

**Comment by BasmaRG** [comment]
Thanks, it works with me.

**Comment by vivekreddoorz** [comment]
> In fact this may be another lind of issue. For instance:
> 
> `from pandas.tools.plotting import autocorrelation_plot`
> 
> Throws an error: `ModuleNotFoundError: No module named 'pandas.tools'`
> 
> However, `from pandas.plotting import autocorrelation_plot` works perfectly.

work fine for me..thnx

**Comment by PalashSharma15** [comment]
> In fact this may be another lind of issue. For instance:
> 
> `from pandas.tools.plotting import autocorrelation_plot`
> 
> Throws an error: `ModuleNotFoundError: No module named 'pandas.tools'`
> 
> However, `from pandas.plotting import autocorrelation_plot` works perfectly.

This worked for me

**Comment by singularpse** [comment]
> In fact this may be another lind of issue. For instance:
> 
> `from pandas.tools.plotting import autocorrelation_plot`
> 
> Throws an error: `ModuleNotFoundError: No module named 'pandas.tools'`
> 
> However, `from pandas.plotting import autocorrelation_plot` works perfectly.

Thanks!

**Comment by sebassilverac** [comment]
> In fact this may be another lind of issue. For instance:
> from pandas.tools.plotting import autocorrelation_plot
> Throws an error: ModuleNotFoundError: No module named 'pandas.tools'
> However, from pandas.plotting import autocorrelation_plot works perfectly.

This was it thank you!

**Comment by jadecacho** [comment]
Use this in importing scatter_matrix

    from pandas.plotting import scatter_matrix

**Comment by K-tang-mkv** [comment]
> In fact this may be another lind of issue. For instance:
> 
> `from pandas.tools.plotting import autocorrelation_plot`
> 
> Throws an error: `ModuleNotFoundError: No module named 'pandas.tools'`
> 
> However, `from pandas.plotting import autocorrelation_plot` works perfectly.

But why can 'from pandas.plotting import autocorrelation_plot' work?

**Comment by nullpointxr** [comment]
Can confirm, `from pandas.plotting import autocorrelation_plot` worked for me too.

**Comment by PriyankuRahang** [comment]
> In fact this may be another lind of issue. For instance:
> 
> `from pandas.tools.plotting import autocorrelation_plot`
> 
> Throws an error: `ModuleNotFoundError: No module named 'pandas.tools'`
> 
> However, `from pandas.plotting import autocorrelation_plot` works perfectly.

worked!

**Comment by MarcoGorelli** [comment]
Glad this is working for everyone - no need to keep commenting "worked" though, if you run into any issues please open a new one
