### ISSUE TITLE
ENH: pandas read_* wildcard

### ISSUE THREAD

**Issue by wxl3322335** [pandas-dev/pandas#15904]
hi every one,i want to use in pandas like this
``df = pd.read_excel('*order list*.xlsx')``

could panda  wildcard？
thank you！

**Comment by TomAugspurger** [comment]
There's a link in our [cookbook](http://pandas-docs.github.io/pandas-docs-travis/cookbook.html#csv), which links to http://stackoverflow.com/questions/25210819/speeding-up-data-import-function-pandas-and-appending-to-dataframe/25210900#25210900

@wxl3322335 would you want to include the example from StackOverflow in the actual documentation, like some of the other examples?

**Comment by wxl3322335** [comment]
HI mr TomAugspurger ：
thanks for your help，but i am a new member here，i dont know how to do，i am sorry！

**Comment by wxl3322335** [comment]
@TomAugspurger could you tell how to use  wildcard in reading csv ？
thank you very much！

**Comment by wxl3322335** [comment]
@jreback  thanks for your help！

**Comment by dwkenefick** [comment]
I can take a crack at this - quick question:  Is the issue that all `read_*` functions should support globs (based on the ENH in the title) or is it that the docs should include an example of how to read multiple files (Based on the Docs label and comments)?

Happy to help either way, but I wanted to make sure I'm on the right page.

**Comment by jreback** [comment]
this is just doc examples. We don't directly support globs in paths. I think we *might* want to try to detect a glob and raise, we don't support it, so it shouldn't pass thru.

@TomAugspurger

**Comment by TomAugspurger** [comment]
@dwkenefick in `doc/source/cookbook.rst` there's a link to the stackoverflow answer http://stackoverflow.com/questions/25210819/speeding-up-data-import-function-pandas-and-appending-to-dataframe/25210900#25210900

Basically, we want include an example like that in our documentation. Ideally it would be runnable.

Then in the main IO docs in `io.rst` you can add a little section about reading multiple files and link to the example in `cookbook.rst`.
