### ISSUE TITLE
to_datetime drops 00:00:00 from output

### ISSUE THREAD

**Issue by cneerdaels** [pandas-dev/pandas#15942]
#### 

```python
import pandas as pd

print (pd.__version__)

data = pd.DataFrame({'Mbps':[10.0], 'Region':['NA'], 'CID':['gsdfd']})

x1 = pd.to_datetime('2017-02-02 00:00:00', format='%Y-%m-%d %H:%M:%S')
data['time1'] = x1
print (x1)
print (data.time1)

x2 = pd.to_datetime('2017-02-02 00:00:05', format='%Y-%m-%d %H:%M:%S')
data['time2'] = x2
print (x2)
print (data.time2)

```
#### Problem description

Regardless of the format specified, to_datetime drops the hours,mins, and seconds when they are all zeros (i.e 00:00:00). 

#### Expected Output
```
0.19.2
2017-02-02 00:00:00
0   2017-02-02 00:00:00
Name: time1, dtype: datetime64[ns]
2017-02-02 00:00:05
0   2017-02-02 00:00:05
Name: time2, dtype: datetime64[ns]
```

#### Actual Output
```
0.19.2
2017-02-02 00:00:00
0   2017-02-02
Name: time1, dtype: datetime64[ns]
2017-02-02 00:00:05
0   2017-02-02 00:00:05
Name: time2, dtype: datetime64[ns]
```

**Comment by jreback** [comment]
no its there. This will print this way if it can.

further, you don't generally need to specify a format if its ISO8601

``pd.to_datetime(...)`` is enough

**Comment by jreback** [comment]
```
In [7]: data['time1'].tolist()
Out[7]: [Timestamp('2017-02-02 00:00:00')]

```

**Comment by cneerdaels** [comment]
it may be there internally, but shortly afterwards when I write it to a csv with 
```
to_csv(out, index=False, encoding='utf-8', compression='gzip', header=False)
``` 
and then take that CSV and use it to import somewhere expecting a timestamp (like bigquery) its failing because the output was truncated. It all works at any other time of day, except for 00:00:00

**Comment by jreback** [comment]
if you *really* need a full formatted date, then you can simply specify the option when writing a csv. http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html?highlight=to_csv#pandas.DataFrame.to_csv

**Comment by cneerdaels** [comment]
awesome - thank you!
