### ISSUE TITLE
np.read_csv C parser uses _try_int64 when converting np.uint64 values

### ISSUE THREAD

**Issue by kirillsc** [pandas-dev/pandas#15950]
#### Code Sample

```python
#!/usr/bin/python
import numpy as np
import pandas as pd

df = pd.read_csv("test.data", sep=" ",
                names=["opcode", "msg_id", "verb", "time_ns", "src_port", "key"],
                dtype={"opcode":np.uint32, "msg_id":np.uint64, "time_ns":np.uint64},
                error_bad_lines=False,
                skip_blank_lines=True               
                )
print df
print "value  ", df.ix[2, "time_ns"]
print "max u43", np.iinfo(np.int64).max
print "max u64", np.iinfo(np.uint64).max
"""
> cat test.data 
5 49175 8 6369116884441 121 user5353376006837317496
5 87 8 6369116913924 120 user5020027490740379661
5 16476 5 9636911691583032832 1208 user2127153374092823212
5 49216 8 6369116917983 122 user3650346306886706056
5 64 8 6369117018969 123 user4432592802498709959
"""

```
#### Problem description

In the example above, I am specifying time_ns column to be of type np.uint64, however, it causes an overflow issue when reading the test.data file on the row[2]. As it follows from the trace, int64 is used instead of unsigned int64 which triggers the issue. 

A work around that works is to use python parser and convert uint64 column manually as follows:

```python
df = pd.read_csv("test.data", sep=" ",
                names=["opcode", "msg_id", "verb", "time_ns", "src_port", "key"],
                skip_blank_lines=True,
                engine="python"
                )
df["time_ns"] = df.apply(lambda x: np.uint64(x["time_ns"]), axis=1)
```

#### Actual Output 

> Traceback (most recent call last):
  File "./test.py", line 9, in <module>
    skip_blank_lines=True
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 645, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 400, in _read
    data = parser.read()
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 938, in read
    ret = self._engine.read(nrows)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1507, in read
    data = self._reader.read(nrows)
  File "pandas/parser.pyx", line 846, in pandas.parser.TextReader.read (pandas/parser.c:10364)
  File "pandas/parser.pyx", line 868, in pandas.parser.TextReader._read_low_memory (pandas/parser.c:10640)
  File "pandas/parser.pyx", line 945, in pandas.parser.TextReader._read_rows (pandas/parser.c:11677)
  File "pandas/parser.pyx", line 1047, in pandas.parser.TextReader._convert_column_data (pandas/parser.c:13111)
  File "pandas/parser.pyx", line 1091, in pandas.parser.TextReader._convert_tokens (pandas/parser.c:13856)
  File "pandas/parser.pyx", line 1145, in pandas.parser.TextReader._convert_with_dtype (pandas/parser.c:14775)
  File "pandas/parser.pyx", line 1749, in pandas.parser._try_int64 (pandas/parser.c:24581)
OverflowError: Overflow

#### Expected Output
   opcode  msg_id  verb              time_ns  src_port  \
0       5   49175     8        6369116884441       121   
1       5      87     8        6369116913924       120   
2       5   16476     5  9636911691583032832      1208   
3       5   49216     8        6369116917983       122   
4       5      64     8        6369117018969       123   

                       key  
0  user5353376006837317496  
1  user5020027490740379661  
2  user2127153374092823212  
3  user3650346306886706056  
4  user4432592802498709959  
value   9636911691583032832
max u43 9223372036854775807
max u64 18446744073709551615

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-31-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: C
LOCALE: None.None

pandas: 0.19.1
nose: 1.3.7
pip: 9.0.1
setuptools: 34.3.3
Cython: None
numpy: 1.12.1
scipy: 0.18.1
statsmodels: 0.6.1
xarray: None
IPython: 5.3.0
sphinx: None
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: None
tables: 3.2.2
numexpr: 2.4.3
matplotlib: 1.5.3
openpyxl: 2.3.0
xlrd: 0.9.4
xlwt: 0.7.5
xlsxwriter: None
lxml: 3.5.0
bs4: 4.4.1
html5lib: 0.999
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: 0.7.2.None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
almost certain this is fixed in master

cc @gfyoung

**Comment by gfyoung** [comment]
@jreback : Indeed it is.  In fact @kirillsc , you don't even need to specify `uint64` for "time_ns", `read_csv` will correctly deduce that the only integer `dtype` that can hold those numbers is `uint64` !

**Comment by kirillsc** [comment]
Great, thanks!
Should I upgrade to 0.19.2 or build 0.20.0 from source?

**Comment by gfyoung** [comment]
@jreback : Unless shown otherwise, I think this is safe to close.

**Comment by gfyoung** [comment]
@kirillsc : 0.20.0.  Increased `uint64` support is a relatively recent thing.

**Comment by gfyoung** [comment]
@jreback : Unless shown otherwise, I think this is safe to close.

**Comment by gfyoung** [comment]
@kirillsc : Also, it's `pd.read_csv`, not `np.read_csv` :smile:
