### ISSUE TITLE
FYI, if you build pandas release binaries with 3.6.1, they'll be broken on 3.6.0

### ISSUE THREAD

**Issue by njsmith** [pandas-dev/pandas#15961]
As a heads up: https://bugs.python.org/issue29943

Two possible workarounds:
* Make sure to use 3.6.0 if building release binaries (this way they'll work on 3.6.1 as well)
* add a `#ifdef PySlice_GetIndicesEx  #undef PySlice_GetIndicesEx  #endif` to `pandas/_libs/src/compat_helper.h` (but make sure to only enable this on 3.6, or you'll eventually get broken again

**Comment by jreback** [comment]
thanks

yeah easy enough to build wheels on 3.6.0

**Comment by jreback** [comment]
@chris-b1 you can have a look at this?

**Comment by mattip** [comment]
This broke the build for PyPy. See pull request #16192
