### ISSUE TITLE
Typo in documentation of pandas.DatetimeIndex.freq

### ISSUE THREAD

**Issue by caph1993** [pandas-dev/pandas#15975]
Just a small typo at http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DatetimeIndex.freq.html#pandas.DatetimeIndex.freq

It says "get/set the _frequncy_ of the Index" instead of "get/set the _frequency_ of the Index"

**Comment by jreback** [comment]
can you submit a PR?

**Comment by caph1993** [comment]
I don't think so, I'm new to github. Could you do that instead?

**Comment by TomAugspurger** [comment]
This is fixed in master (dev docs at http://pandas-docs.github.io/pandas-docs-travis/generated/pandas.DatetimeIndex.freq.html#pandas.DatetimeIndex.freq)

Thanks for the report though.
