### ISSUE TITLE
When using to_sql(), continue if duplicate primary keys are detected?

### ISSUE THREAD

**Issue by rosstripi** [pandas-dev/pandas#15988]
#### Code Sample, a copy-pastable example if possible

```python
df.to_sql('TableNameHere', engine, if_exists='append', chunksize=900, index=False)

```
#### Problem description

I am trying to append a large DataFrame to a SQL table. Some of the rows in the DataFrame are duplicates of those in the SQL table, some are not. But `to_sql()` completely stops executing if even one duplicate is detected. 

It would make sense for `to_sql(if_exists='append')` to merely warn the user which rows had duplicate keys and just continue to add the new rows, not completely stop executing. For large datasets, you will likely have duplicates but want to ignore them.

Maybe add an argument to ignore duplicates and keep executing? Perhaps an additional `if_exists` option like `'append_skipdupes'`?

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.0.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: English_United States.1252

pandas: 0.19.2
nose: None
pip: 9.0.1
setuptools: 28.8.0
Cython: None
numpy: 1.12.0
scipy: None
statsmodels: None
xarray: None
IPython: 5.3.0
sphinx: None
patsy: None
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999999999
httplib2: None
apiclient: None
sqlalchemy: 1.1.9
pymysql: None
psycopg2: None
jinja2: 2.9.5
boto: None
pandas_datareader: None

</details>

**Comment by rockg** [comment]
This should also support the "on duplicate update" mode as well.

**Comment by jorisvandenbossche** [comment]
@rosstripi I think the idea to have this would certainly be accepted, but AFAIK the main bottleneck is an implementation for this using sql/sqlalchemy in a flavor agnostic way. Some exploration how this could be done is certainly welcome!

**Comment by muniswamy89** [comment]
Hi did you figure out any workaround for this? Please let me know

**Comment by AlvaroPica** [comment]
Any update on this implementation? 

I am now facing this problem with PostgreSQL and SQLAlchemy and would love to have that "on duplicate update". 

Thanks for the work

**Comment by valewyss** [comment]
A workaround would be to remove the unique index in the database:

`sqlquery="ALTER 'TABLE DATABASE'.'TABLE' DROP INDEX 'idx_name'"
`
afterwards 
`df.to_sql('TableNameHere', engine, if_exists='append', chunksize=900, index=False)
`
can be executed. 

Just let your MySQL Server add the index again and drop the duplicates. 
`sqlquery="ALTER IGNORE TABLE 'DATABASE'.'TABLE' ADD UNIQUE INDEX 'idx_name' ('column_name1' ASC, 'column_name2'  ASC, 'column_name3'  '[ASC | DESC]')"`




Depending on your specific application, this can be helpful.
Anyway  `if_exists `option like `append_skipdupes` would be much better.

**Comment by cgi1** [comment]
`append_skipdupes` would be the perfect way to handle this.

**Comment by macdet** [comment]
yes, append_skipdupes +1

**Comment by jtkiley** [comment]
Agreed that it would be good to be able to deal with this with options in `df.to_sql()`.

Here's the workaround I use in sqlite:

```sql
CREATE TABLE IF NOT EXISTS my_table_name (
    some_kind_of_id INT PRIMARY KEY ON CONFLICT IGNORE,
    ...

```

Then, when I insert duplicates, they get silently ignored, and the non-duplicates are processed correctly. In my case, the data are (i.e. *should be*) static, so I don't need to update. It's just that the form of the data feed is such that I'll get duplicates that are ignorable.

**Comment by kjford** [comment]
I believe this is being addressed in #29636 with the `upsert_ignore` argument, which addresses #14553.

**Comment by iveteran** [comment]
append_skipdupes +1

**Comment by Arham-Aalam** [comment]
Agree 'append_skipdupes' should be added.

**Comment by rahullak** [comment]
Yes, please. 'append_skipdupes' should be added and not only for the Primary Key column. If there are duplicates among other Unique columns also it should skip appending those new duplicate rows.

**Comment by devashishnyati** [comment]
+1 for append_skipdupes

**Comment by rishabh-vij** [comment]
append_skipdupes +1

**Comment by mc55boy** [comment]
append_skipdupes +1

**Comment by IsraaMa** [comment]
+1 for append_skipdupes

**Comment by BuSHari** [comment]
Meantime you can use this https://pypi.org/project/pangres/

**Comment by kxbin** [comment]
+1 for append_skipdupes

**Comment by frostless** [comment]
+1 for append_skipdupes

**Comment by singhal2** [comment]
+1 for append_skipdupes. IMO, an option to update the duplicates would also be nice. Perhaps append_updatedupes.

**Comment by tombohub** [comment]
+1

**Comment by tombohub** [comment]
I have made small script for me to allow INSERT IGNORE

```python
    def _table_column_names(self, table: str) -> str:
        """
        Get column names from database table

        Parameters
        ----------
        table : str
            name of the table

        Returns
        -------
        str
            names of columns as a string so we can interpolate into the SQL queries
        """
        query = f"SELECT column_name FROM information_schema.columns WHERE table_name = '{table}'"
        rows = self.conn.execute(query)
        dirty_names = [i[0] for i in rows]
        clean_names = ', '.join(map(str, dirty_names))
        return clean_names
    

    def _insert_conflict_ignore(self, df: pd.DataFrame, table: str):
        """
        Saves dataframe to the MySQL database with 'INSERT IGNORE' query.
        
        First it uses pandas.to_sql to save to temporary table.
        After that it uses SQL to transfer the data to destination table, matching the columns.
        Destination table needs to exist already. 
        Final step is deleting the temporary table.

        Parameters
        ----------
        df : pd.DataFrame
            dataframe to save
        table : str
            destination table name
        """
        # drop in case it exists
        # TODO make random name instead of temp to allow concurrent writing
        drop_query = 'DROP TABLE IF EXISTS `temp`'
        self.conn.execute(drop_query)
        
        df.to_sql('temp',self.conn, index=False)
        columns = self._table_column_names(table='temp')
        insert_query = f'INSERT IGNORE INTO {table}({columns}) SELECT {columns} FROM temp'
        self.conn.execute(insert_query)
        
        # drop again temp after finish
        self.conn.execute(drop_query)
```

**Comment by tinglinliu** [comment]
+1 for append_skipdupes

**Comment by hyamanieu** [comment]
Rather than upvoting this issue which already has a lot of votes, someone could help with this pr: https://github.com/pandas-dev/pandas/pull/29636

**Comment by Mausy5043** [comment]
Instead of skipping duplicates an option to choose between `raise`, `ignore` and `replace` would be even better. This way you can choose to have an exception raised, skip the duplicate or have the duplicate row removed and the new data inserted.

**Comment by benboughton1** [comment]
> ```sql
> ONFLICT 
> ```

Is there a postgres equivalent for this?

**Comment by benboughton1** [comment]
> Agreed that it would be good to be able to deal with this with options in `df.to_sql()`.
> 
> Here's the workaround I use in sqlite:
> 
> ```sql
> CREATE TABLE IF NOT EXISTS my_table_name (
>     some_kind_of_id INT PRIMARY KEY ON CONFLICT IGNORE,
>     ...
> ```
> 
> Then, when I insert duplicates, they get silently ignored, and the non-duplicates are processed correctly. In my case, the data are (i.e. _should be_) static, so I don't need to update. It's just that the form of the data feed is such that I'll get duplicates that are ignorable.

Is there a postgresql equivalent for this?

**Comment by keivanipchihagh** [comment]
> > Agreed that it would be good to be able to deal with this with options in `df.to_sql()`.
> > Here's the workaround I use in sqlite:
> > ```sql
> > CREATE TABLE IF NOT EXISTS my_table_name (
> >     some_kind_of_id INT PRIMARY KEY ON CONFLICT IGNORE,
> >     ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then, when I insert duplicates, they get silently ignored, and the non-duplicates are processed correctly. In my case, the data are (i.e. _should be_) static, so I don't need to update. It's just that the form of the data feed is such that I'll get duplicates that are ignorable.
> 
> Is there a postgresql equivalent for this?

Unfortunately, I couldn't find an equivalent for this on PostgreSQL.

**Comment by bruppfab** [comment]
+1 for append_skipdupes

**Comment by chabazite** [comment]
+1 for append_skipdupes

**Comment by Magnum35puc** [comment]
+1 for append_skipdupes

**Comment by perofskite** [comment]
+1 for append_skipdupes

**Comment by ThomasAuriel** [comment]
+1 for append_skipdupes

**Comment by motishaku** [comment]
Does anyone know if its ever planned to be added?

**Comment by redreamality** [comment]
The official discussion in  #49246 suggest that this issue seems not to be  the current focus point of pandas, suggest closing.

https://github.com/pandas-dev/pandas/issues/15988#issuecomment-823602644 from [tombohub](https://github.com/tombohub) seems a workaround for it.  

For `upsert`, just replace `insert ignore`.

**Comment by felixmarch** [comment]
Perhaps it would be nice to add those `upsert` and `insert ignore` https://github.com/pandas-dev/pandas/issues/15988#issuecomment-823602644 as pandas' utility function? :thinking:

**Comment by nono-london** [comment]
I am guessing it works on a batch update basis, 
so easiest might be to have user decide "batch=False" and "ignore_error_on_duplicate_key=True".
These 2 are handleable in most databases. 
"update on duplicate" is usually more taylor made upon databases.
Just a thought, and thank you for the lib which is great!
Best

**Comment by keivanipchihagh** [comment]
I believe [this](https://stackoverflow.com/a/62379384) method would solve the problem until a native feature is built into the project.
