### ISSUE TITLE
Fast way to exclude columns

### ISSUE THREAD

**Issue by citynorman** [pandas-dev/pandas#15993]
It would be great to be able to exclude/slice columns like you can with np arrays.

```
df = pd.DataFrame(np.random.rand(4,4), columns = list('abcd'))
df[-('b')] #neat!
```
instead of
```
df.drop('b', axis=1)
df.ix[:, df.columns != 'b']
```
etc

see 
http://stackoverflow.com/questions/29763620/how-to-select-all-columns-except-one-column-in-pandas-using-ix
http://stackoverflow.com/questions/14940743/selecting-excluding-sets-of-columns-in-pandas

**Comment by TomAugspurger** [comment]
We're limited by python's syntax here. Not much else we can do. Your example is a `TypeError` for better or worse.
