### ISSUE TITLE
Follow-up #15954: public API for Styler

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#16009]
As a reminder that we need to address this for 0.20, follow-up for https://github.com/pandas-dev/pandas/pull/15954

- [ ] Decide on public API entry (the whatsnew in the PR mentions `pandas.io.api.Styler`, but it is in practice also added to top-level namespace (`pandas.Styler`), while the API docs still use it as `pandas.formats.style.Styler`)
- [ ] Depending on decision above (which may also depend on #13634), update docs
- [ ] Would it be needed to keep back compat shim at `pandas.formats.style.Styler` to deprecate? (not sure if many people would already used this object directly instead of through `df.style`)

**Comment by TomAugspurger** [comment]
Oh I forgot we did import * from pandas.io

I think we'll just del it from the top-level namespace.

I can add a shim if needed. Will get to this today.

**Comment by jorisvandenbossche** [comment]
I would also think about whether we would want to put this in either `pandas.io` directly or either in `pandas.io.style`/`pandas.io.formatting`/`pandas.io.formats`, instead of in `pandas.io.api`. This last one is not publicly used currently, but only to gather those that are exposed top-level, so it seems a bit inconsistent to then put it there.

**Comment by jreback** [comment]
I think ok to move ``pandas.formats`` -> ``pandas.io.formats``. Once I do that can then move this around / fix api wherever you need. probably ``pandas.io.Styler`` is fine for subclassing

**Comment by jorisvandenbossche** [comment]
This is now changed in the API docs to `pandas.io.formats.style.Styler` (other docs still needs updating)

But, this is maybe a bit too nested? For the other publics things in io, they are typically at the `pandas.io.module` level. 
So shall we expose it as `pandas.io.formats.Styler` ? 

(BTW, it is a bit longer but I actually found `pandas.io.formatting` better sounding)
