### ISSUE TITLE
API: Categorical constructor shouldn't accept scalar for categories

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#16022]
#### Code Sample, a copy-pastable example if possible

I was surprised to find that `Categorical` accepts scalars for `categories`.

```python
In [1]: import pandas as pd
In [2]: pd.Categorical([1, 2], categories=2)
Out[2]:
[NaN, 2.0]
Categories (1, int64): [2]
```

AFAICT, this isn't documented, though we explicitly test it [here](https://github.com/pandas-dev/pandas/blob/8daf9a7e45344dc5a247410e037dccb41b97a3db/pandas/tests/test_categorical.py#L252). Am I missing a use-case where this is desirable, or should we just depreciate it and simplify the constructor?

Anyone want to guess what the categories are on `pd.Categorical(['a', 'b'], categories='abcd')` :)

cc @janschulz

**Comment by jreback** [comment]
we generally do this, iow, accept scalars in list-like fields. So ok with this (also ok is to raise a ValueError). Maybe that would be better.

**Comment by janschulz** [comment]
Not sure, I tried to find out if I wrote a message but it's all part of a squashed commit (https://github.com/pandas-dev/pandas/commit/0165d1421dcb76351a99f8ef8bdff59c365b43ad), and none of the preserved comit messages show anything about it :-/ I think @jreback explaination is correct: it uses `levels = _convert_to_list_like(levels)`, so it's the same logic as elsewhere...

**Comment by jorisvandenbossche** [comment]
I would just raise an error on this, no reason to allow it IMO (and I would just regard it as a bug fix without deprecation, or would there be people doing this?)
