### ISSUE TITLE
DOC: styler warnings in doc-build

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#16033]
https://travis-ci.org/pandas-dev/pandas/jobs/222779268

```
/tmp/doc/source/generated/pandas.io.formats.style.Styler.rst:74: WARNING: failed to import template:
/tmp/doc/source/generated/pandas.io.formats.style.Styler.rst:74: WARNING: toctree references unknown document 'generated/template:'
```

cc @TomAugspurger @jorisvandenbossche 

I just pushed a change to fix the path of the imports (after ``pandas.formats`` change), but I think it still needs something.

**Comment by TomAugspurger** [comment]
Yeah saw that. I'll clean  up the warnings in the doc build today.

**Comment by TomAugspurger** [comment]
For this specific one, it seems like it tries to auto-doc all of these

```python
    Attributes
    ----------
    env : Jinja2 Environment
    template: Jinja2 Template
    loader : Jinja2 Loader

```

but `template` isn't a python module. I'll see if there's an easy way to skip just one.

**Comment by TomAugspurger** [comment]
For reference, there's the `:exclude-members: template` directive that might have worked. It's supposed to work with autodoc, but I haven't found anything about whether it works with autosummary. https://github.com/numpy/numpydoc/issues/69 might be involved

I've turned those attributes into properties with their own docstings, and the warning is fixed.

I'll bush a batch of doc fixes a bit later today.

**Comment by jreback** [comment]
FYI @TomAugspurger this was just an incorrect usage of ``pytest.warn`` rather than ``tm.assert_produces_warning``

**Comment by jreback** [comment]
sorry @TomAugspurger wrong issue.

**Comment by jorisvandenbossche** [comment]
I don't see those anymore in the doc build output on travis: https://travis-ci.org/pandas-dev/pandas/jobs/349024108, so closing
