### ISSUE TITLE
open h5 file error

### ISSUE THREAD

**Issue by laughing429** [pandas-dev/pandas#16041]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import h5py as h5
f = h5.File('test.h5', 'w')
f.create_dataset('da1', data = [1,2,3])
f.close()
import pandas as pd
pd.read_hdf('./test.h5', key='da1')
```
#### Problem description
when I use h5py module to create h5 file, but I can't read it by read_hdf function.
#### Output of ``pd.show_versions()``

<details>
# Paste the output here pd.show_versions() here
python: 2.7.12.final.0
pandas: 0.18.1
</details>

**Comment by jreback** [comment]
http://pandas.pydata.org/pandas-docs/stable/io.html#io-hdf5
HDF5 support is *only* for ``PyTables``.
