### ISSUE TITLE
TST: some unclosed files in parser testing?

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#16055]
https://travis-ci.org/pandas-dev/pandas/jobs/223491099

```
..................sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=0 mode='r' encoding='UTF-8'>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=1 mode='w' encoding='UTF-8'>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=0 mode='r' encoding='UTF-8'>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=1 mode='w' encoding='UTF-8'>
```

**Comment by jreback** [comment]
cc @gfyoung if you have a chance (this is the 3.6 build).

**Comment by TomAugspurger** [comment]
With https://pypi.python.org/pypi/pytest-warnings it looks like this might work

```
pytest -W ignore -W error::ResourceWarning
```

**Comment by gfyoung** [comment]
I can't seem to track it down.  Not sure where this is occurring.

**Comment by gfyoung** [comment]
I can't seem to track it down.  Not sure where this is occurring.  Interesting though, I broke a bunch of tests by including that test command @TomAugspurger provided (see <a href="https://travis-ci.org/gfyoung/pandas/jobs/223707626">here</a>).

**Comment by gfyoung** [comment]
Can anyone reproduce the warnings locally?  Although I got things to break as seen <a href="https://github.com/pandas-dev/pandas/issues/16055#issuecomment-295438196">above</a>, that's way too many to match the warnings seen originally.

**Comment by TomAugspurger** [comment]
I tried and was unable to reproduce them (python 3.6).

**Comment by gfyoung** [comment]
Hmm...without anyone able to reproduce this, it's very difficult to tell if this is a parser issue.  The thing that makes me weary about that is because the filename is `sys` instead of a Python file.

Thoughts on how to proceed?

**Comment by jreback** [comment]
make sure you define this: ``PANDAS_TESTING_MODE="deprecate"`` and ``-s`` when you run the tests. I *only* think this occurs on linux-64. doesn't repro on osx. will take a look tomorrow there. It *might* be because of the multiprocessing (in pytest-xdist), thought not sure.

**Comment by gfyoung** [comment]
@jreback : Any insights on this?  Just wondering.

**Comment by jreback** [comment]
nope. it shows on the travis build but I cannot repro locally. will just close this.
