### ISSUE TITLE
BUG/BLD: pytest not a runtime dep

### ISSUE THREAD

**Issue by chris-b1** [pandas-dev/pandas#16065]
on master - now that we've exposed a testing api, need to wrap the import of pytest

```
>>> import pandas

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Chris\Anaconda\envs\py361\lib\site-packages\pandas\__init__.py", line 60, in <module>
    import pandas.testing
  File "C:\Users\Chris\Anaconda\envs\py361\lib\site-packages\pandas\testing.py", line 7, in <module>
    from pandas.util.testing import (
  File "C:\Users\Chris\Anaconda\envs\py361\lib\site-packages\pandas\util\testing.py", line 22, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

**Comment by jreback** [comment]
actually is there a reason we are doing an ``import pandas.testing`` as all in ``__init__``?

@jorisvandenbossche ?

**Comment by jorisvandenbossche** [comment]
Ah, good catch, but the testing functions do not depend on pytest, so this should be solvable (although maybe a bit annoying to move all imports of pytest inline ..)

> actually is there a reason we are doing an import pandas.testing at all in __init__?

Because otherwise you cannot do `pd.testing.assert_frame_equal`, but have to explicitly import it (but I can certainly be wrong here!)

**Comment by jorisvandenbossche** [comment]
Hmm, there is quite a lot of usage of pytest, so inline the import would be very annoying ..

So if you remove the line in init, you get this:

```
In [1]: pd.testing.assert_frame_equal
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-08ffb5740461> in <module>()
----> 1 pd.testing.assert_frame_equal

AttributeError: module 'pandas' has no attribute 'testing'
```

but have to explicitly import it like `from pandas.testing import assert_frame_equal`

**Comment by jorisvandenbossche** [comment]
@jreback do you know how this does work for `errors` ? (because there directly assessing it does work)

**Comment by jreback** [comment]
> but have to explicitly import it like from pandas.testing import assert_frame_equal

I don't think this is a big deal.

we explicity *don't* want to import the testings into the main namespace. It *could* be fixed to isolate, but maybe let's do that later.

**Comment by jreback** [comment]
> @jreback do you know how this does work for errors ? (because there directly assessing it does work)

``.errors`` *defines* things (or imports from cython libs). 

I think we *could* do this in testing, but it would require hiding the ``pytest`` import & lots of other imports (prob not a big deal as they are std lib).
