### ISSUE TITLE
Feature Request: Provide dict object for pd.Series.to_dict()

### ISSUE THREAD

**Issue by jolespin** [pandas-dev/pandas#16122]
I frequently use the `.to_dict()` method and was wondering how difficult it would be to implement a `dict_obj` argument to specify what type of dictionary will be used.  For example, if one was interested in preserving the order: 

```
from collections import OrderedDict

pd.Series(list("abcd")).to_dict(dict_obj=OrderedDict)
```

**Comment by TomAugspurger** [comment]
The implementation of `to_dict` is just

```python
    def to_dict(self):
        """
        Convert Series to {label -> value} dict

        Returns
        -------
        value_dict : dict
        """
        return dict(compat.iteritems(self))
```

So, if you wanted to take an argument (`type`, `kind`?) with a default of `dict` I think that'd be fine.

**Comment by jolespin** [comment]
Thanks!  This will come in handy b/c a lot of my scripts I convert between dicts and series.  I'm not sure what keyword to use but I think `type` and `kind` sound great.  Others I thought of are `class`, `container`, `object`, etc.

**Comment by TomAugspurger** [comment]
`class` wouldn't work since that's a keyword. If you have a chance, you could skim through parts of the standard library that have something similar. Not much comes to my mind other than `argparse`, which IIRC uses a `type` keyword argument.

**Comment by jolespin** [comment]
Oh yea that's true, `type` does get temporarily repurposed in `argparse`.  The only other thing that comes to mind is in `matplotlib` with `format` like `fig.savefig(path, format="pdf")`

**Comment by dwkenefick** [comment]
I can take a crack at this one if we do want to implement it.  Quick questions:

1. Should we only allow certain types, e.g. `OrderedDict` and a few other easy ones from [`collections`](https://docs.python.org/3/library/collections.html#collections.ChainMap), like `deque`?  Some of the others might be a little odd, like `defaultdict`.
2. Do we want to implement this for `pd.DataFrame` too?  

I'll use `type` as the keyword - I couldn't find any strong precedent in the standard library.  `kind` is used elsewhere in pandas, for example `DataFrame.plot`, but that feels different.

@jolespin - You probably already know this but here is an easy way to do what you want:
```python
import pandas as pd
from collections import OrderedDict

series = pd.Series({'a': 1, 'b': 2})
OrderedDict(series)
```

**Comment by TomAugspurger** [comment]
`into` might be a decent name.

If we wanted to do checking, then we could check `issubclass(into, collections.Mapping)`, which is the ABC for dict-like objects.

It would be nice to do this for DataFrame as well.
