### ISSUE TITLE
0.20.0 gratuitously breaks backwards compatibility

### ISSUE THREAD

**Issue by dhirschfeld** [pandas-dev/pandas#16138]
PR #15998 removed the `pandas.types` module which AFAICT wasn't deprecated.

This breaks 3rd party libraries such as `dask` without giving them any warning or time to adjust to the new api.

IMHO a shim should be put in place with a deprecation warning to give 3rd party libraries a chance to adjust to the new api

**Comment by jreback** [comment]
pandas.types was never public
dash is already compat

**Comment by dhirschfeld** [comment]
In python private modules are denoted by a leading underscore so by that definition it wasn't private and if it was supposed to be was there ever any way for anyone to be able to tell that?

**Comment by dhirschfeld** [comment]
dask is only one such library which will break without warning

**Comment by jreback** [comment]
dask has already been fixed
they explicitly relied on some unstable apis and were willing to accept the risk
anything else is not going to be deprecated
the whatsnew is very clear

**Comment by jreback** [comment]
closed by https://github.com/pandas-dev/pandas/commit/075eca1fa085359b71f26d02c2f44156068e123c

@dhirschfeld if you find anything pls comment / open new issue.
