### ISSUE TITLE
reprs no longer return anything in the notebook

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#16168]
In https://github.com/pandas-dev/pandas/pull/14904 I added an `NDFrame._ipython_display_`, which handles publishing what the user has configured (html, table schema, latex, text).

An unintended consequence of that, is that our DataFrame and Series reprs invoked by the notebook no longer return anything, so there's no `Out[x]` and nothing is stored in the `Out` dictionary. [Here's a comparison notebook](http://nbviewer.jupyter.org/gist/TomAugspurger/6aee20f69aafdb70ae65ebef77bb12f0).

cc @rgbkrk

For the jupyter folks (maybe @Carreau if you have time), is there any way around this? Does using `_ipython_display_` mean you can't have a "real output" from a cell?

**Comment by Carreau** [comment]
> For the jupyter folks (maybe @Carreau if you have time), is there any way around this? Does using _ipython_display_ mean you can't have a "real output" from a cell?

Hum, I don't know. That's an interesting question. I'm unsure if there is a way to have a `_repr_` that just compute all mime bundles and return this.

**Comment by TomAugspurger** [comment]
I can raise an issue on the Jupyter side (IPython repo probably?) if necessary.

**Comment by Carreau** [comment]
Sure, that would be great !

**Comment by TomAugspurger** [comment]
Since `_repr_table_schema_` is the only one who really needs `_ipython_display_`, we *could* monkeypatch the current `_ipython_display_` onto `NDFrame` when the user sets `pd.options.display.html.table_schema` to True, and remove it when they set it to `False` (the default).

The default is `False`, so users who don't explicitly set that config value will get the `Out[x]` as before. Not a long-term solution, but perhaps good enough for now?

**Comment by rgbkrk** [comment]
Yeah I definitely didn't intend for us to break previous workflows. The monkey patching seems ok for now. It's too bad we don't have https://github.com/ipython/ipython/issues/10090.

**Comment by TomAugspurger** [comment]
Closed by https://github.com/ipython/ipython/issues/10491
