### ISSUE TITLE
Excel styles should default to using number format from display.precision option

### ISSUE THREAD

**Issue by jnothman** [pandas-dev/pandas#16161]
Excel output should be as close to the DataFrame html display as possible. Excel controls the display of each cell with a number format style attribute. Pandas controls it with the display.precision option. Excel export should adhere to the pandas option.

**Comment by rmhowe425** [comment]
@mroeschke I _think_  [this PR] (https://github.com/pandas-dev/pandas/pull/54302) satisfies the acceptance criteria for this issue.

If we all agree then we can probably close this issue.

**Comment by mroeschke** [comment]
Thanks. Yes I think this can be closed
