### ISSUE TITLE
Series `set_value()` won't allow update to a sequence

### ISSUE THREAD

**Issue by lia-simeone** [pandas-dev/pandas#16184]
#### Code Sample, a copy-pastable example if possible

```python
series1 = pd.Series([1, [7,8,9], 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
series2 = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])

series1.set_value('b', 2)
series2.set_value('b', [7,8,9])
```
#### Current Output

`ValueError: setting an array element with a sequence.`

#### Problem description

I want to update a singe value in a Series to a sequence. I find it confusing that I can update a sequence _to_ a single value, but I can't update a single value to a sequence.

#### Expected Output
```
a    1
b    [7, 8, 9]
c    3
d    4
e    5
dtype: object
```
#### Output of ``pd.show_versions()``

<details>
# Paste the output here pd.show_versions() here
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.3.final.0
python-bits: 64
OS: Darwin
OS-release: 16.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.19.2
nose: None
pip: 9.0.1
setuptools: 27.2.0
Cython: None
numpy: 1.11.3
scipy: None
statsmodels: None
xarray: None
IPython: 5.3.0
sphinx: None
patsy: None
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: None
tables: 3.3.0
numexpr: 2.6.2
matplotlib: None
openpyxl: 2.4.1
xlrd: 1.0.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999
httplib2: None
apiclient: None
sqlalchemy: 1.1.5
pymysql: None
psycopg2: 2.6.2 (dt dec pq3 ext lo64)
jinja2: 2.9.4
boto: None
pandas_datareader: None
</details>

**Comment by TomAugspurger** [comment]
Storing nested data inside a Series isn't very well supported, so you're going to run into issues like these all over the place. In this case, the issue is related to promoting the `int` values to `object`, so that you can insert a python list. As a workaround, you can do that yourself:

```pytyhon
series2 = series2.astype(object)
series2.loc['b'] = [7, 8, 9]  # or .set_value if you want
```

This probably won't be fixed any time soon, if at all.

**Comment by toobaz** [comment]
> I find it confusing that I can update a sequence to a single value, but I can't update a single value to a sequence.

You can have 3 different people born in the same year, but you can't have a person born in 3 different years.

**Comment by lia-simeone** [comment]
That'll do, thanks @TomAugspurger !
