### ISSUE TITLE
DOC: add redirects for moved api pages

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#16186]
Due to the changes in the directory layout, some API changes have moved. We should add redirects for those.

I think is this is mainly about `Resampler` (off the top of my head)

**Comment by jorisvandenbossche** [comment]
and the styler ones

**Comment by TomAugspurger** [comment]
@jorisvandenbossche do you have any info on how to do redirects with sphinx? I'm not finding much. Or would we do this at a different level/

**Comment by jorisvandenbossche** [comment]
We already have some machinery: https://github.com/pandas-dev/pandas/blob/master/doc/source/conf.py#L231 but you will have to adapt it a little bit (currently they are for top-level ones). Probably fine to remove the existing ones as well.
