### ISSUE TITLE
ENH: Add Series.to_latex() and _repr_latex_

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#16180]
Could be as simple as as `self.to_frame().to_latex(...)`. Or could move it to generic.py

This will help clean up logic in `NDFrame._ipython_display_`.

**Comment by sleepdeprivation** [comment]
Here I am again to try contributing.

Is this done or does work need to be done here?

**Comment by TomAugspurger** [comment]
That's be great. The issue is open, and not one else has said they want to work on it, so go right ahead.

Let us know if you have any troubles.

**Comment by bsweger** [comment]
@TomAugspurger I'll take a stab at this one during PyCon sprints. Thanks!
