### ISSUE TITLE
RangeIndex.append() should return RangeIndex when possible

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#16212]
#### Code Sample, a copy-pastable example if possible

```python
In [2]: i1, i2 = pd.RangeIndex(2), pd.RangeIndex(2, 4)

In [3]: i1.union(i2)
Out[3]: RangeIndex(start=0, stop=4, step=1)

In [4]: i1.append(i2)
Out[4]: Int64Index([0, 1, 2, 3], dtype='int64')
```
#### Problem description

It would be nice if appending consecutive ``RangeIndex`` returned a ``RangeIndex``.

This was briefly discussed [here](https://github.com/pandas-dev/pandas/pull/12289#r71085353).

#### Expected Output

Same as ``Out[3]:``

PR on its way.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: f1549668c84b481a67547bb46261d1394c8dd3e7
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.7.0-1-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.utf8
LOCALE: it_IT.UTF-8

pandas: 0.20.0rc1+49.gf1549668c
pytest: 3.0.6
pip: 9.0.1
setuptools: 33.1.1
Cython: 0.25.2
numpy: 1.12.0
scipy: 0.18.1
xarray: 0.9.1
IPython: 5.1.0.dev
sphinx: 1.4.9
patsy: 0.3.0-dev
dateutil: 2.5.3
pytz: 2016.7
blosc: None
bottleneck: 1.2.0
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.0
openpyxl: 2.3.0
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.6
lxml: 3.7.1
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.8
s3fs: None
pandas_gbq: None
pandas_datareader: 0.2.1

</details>

**Comment by jreback** [comment]
yep, should be straightforward to do this.
