### ISSUE TITLE
Different results with tzlib and dateutil_tz with "ambiguous" argument to tz_localize 

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#16234]
#### Code Sample, a copy-pastable example if possible

```python
In [2]: import pytz

In [3]: pytz_tz = pytz.timezone('US/Eastern')
   ...: dateutil_tz = pd._libs.tslib.maybe_get_tz('dateutil/US/Eastern')
   ...: 

In [4]: idx = pd.DatetimeIndex(['2011-11-06 01:00:00'])

In [5]: l1 = idx.tz_localize(pytz_tz, ambiguous=[1])

In [6]: l2 = idx.tz_localize(dateutil_tz, ambiguous=[1])

In [7]: l1 == l2
Out[7]: array([ True], dtype=bool)

In [8]: l1[0] == l2[0]
Out[8]: True

In [9]: str(l1[0]) == str(l2[0])
Out[9]: False

In [10]: l1, l2
Out[10]: 
(DatetimeIndex(['2011-11-06 01:00:00-04:00'], dtype='datetime64[ns, US/Eastern]', freq=None),
 DatetimeIndex(['2011-11-06 01:00:00-05:00'], dtype='datetime64[ns, tzfile('/usr/share/zoneinfo/US/Eastern')]', freq=None))
```
#### Problem description

I guess (and the existing tests suggest) the two should produce the same results.

#### Expected Output

``l1`` and ``l2`` should be perfectly equivalent I guess.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: 1002cc339d81591b280ec3ec3c8ac58ce157e3b6
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.7.0-1-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.utf8
LOCALE: it_IT.UTF-8

pandas: 0.20.0rc1+53.g1002cc339
pytest: 3.0.6
pip: 9.0.1
setuptools: 33.1.1
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.18.1
xarray: 0.9.1
IPython: 5.1.0.dev
sphinx: 1.4.9
patsy: 0.3.0-dev
dateutil: 2.5.3
pytz: 2016.7
blosc: None
bottleneck: 1.2.0
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.0
openpyxl: 2.3.0
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.6
lxml: 3.7.1
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.8
s3fs: None
pandas_gbq: None
pandas_datareader: 0.2.1

</details>

**Comment by jreback** [comment]
no, these are not equivalent in reality. yes in *theory* they should be but I doubt that there is actual equivalence between these different timezone databases. nor do we actually care. you can either use one or the other. anything else would be way too complicated.

if you want to offer a doc note somewhere I guess that would be ok.
