### ISSUE TITLE
DEPR: pandas.core, pandas.util.testing

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#16232]
xref #16223 

These are the only remaining 'public'-ish directories that are not explicitly exposed. In 0.20.0 we make these 'private' in documentation. We should actually deprecate these and move to ``_core`` and ``pandas.util.testing`` -> ``pandas.core.testing``

This will need a DeprecationWarning as likely lots of code that is out there that uses this.

**Comment by jorisvandenbossche** [comment]
I think this is for 0.21 ? (we shouldn't do deprecations in a bugfix release)

**Comment by jreback** [comment]
yep that was a typo

**Comment by jreback** [comment]
not sure can actually do this, but should try for 1.0

**Comment by jorisvandenbossche** [comment]
I am also not sure we can do `core`, but we might want to do `util.testing`, as we have `pandas.testing` as alternative. The probable problem is that we have only put few things there, and people are using other functionality from `util.testing` like the `make..` functions.

**Comment by TomAugspurger** [comment]
Is this any different from https://github.com/pandas-dev/pandas/issues/27522? I guess just `pandas.util.testing`, and leave https://github.com/pandas-dev/pandas/issues/27522 for `pandas.core`?
