### ISSUE TITLE
Add aggregate method to DataFrame

### ISSUE THREAD

**Issue by wesm** [pandas-dev/pandas#1623]
a la groupby-aggregate

**Comment by jreback** [comment]
should be easy after #11841

**Comment by nbonnotte** [comment]
This may be a silly question, but I'm gonna ask it: what should be the result of this `DataFrame.aggregate`?

For instance, let's consider `df.aggregate(np.sum)`.
Should the result be like `df.sum()`?
Or like `df.groupby(df.index).sum()`?
Or something else?

**Comment by jreback** [comment]
this would *work* like ``.groupby(...).agg(np.sum)`` in the sense that the aggregations will take the same form. But this is an aggregation on the frame itself.

e.g. imagine

``df.agg(['sum', 'count'])``
``df.agg({'A' : 'sum', 'B' : 'count'})``
``df.agg({'A' : ['sum','count'], 'B' : ['sum','mean']})``

**Comment by nbonnotte** [comment]
So there would be no grouping at all?

In a sense, it would be a generalisation of `DataFrame.apply`, except that it would work also with strings and be able to yield more complex output?

**Comment by jreback** [comment]
yes ``.apply`` and ``.aggregate`` are synonymous for ``.groupby``,``.rolling``.resample`` already, so having the same for ``NDFrame`` is a good idea (btw this is quite easy to implement as all of the machinery is already there).
