### ISSUE TITLE
Pandas 0.20 wheel on PyPI?

### ISSUE THREAD

**Issue by acarrillo** [pandas-dev/pandas#16246]
It looks like there were PyPI wheels for 0.20.0rc1 ([cache](https://webcache.googleusercontent.com/search?q=cache:EvqvAcMG_wYJ:https://pypi.python.org/pypi/pandas/+&cd=1&hl=en&ct=clnk&gl=us)), but 0.20.0 is just a source tarball. Will there be wheels...? My CI pipeline doesn't have the tools to compile pandas itself...

**Comment by jorisvandenbossche** [comment]
There will certainly be wheels, but the release was not yet fully ready. I hided it again.

**Comment by jorisvandenbossche** [comment]
@TomAugspurger best to hide the release until everything (or most) is up

**Comment by TomAugspurger** [comment]
Sorry about that; I did, but we also need to unhide the old release I guess. Thanks Joris.
