### ISSUE TITLE
API: Clean up dtypes/common.py

### ISSUE THREAD

**Issue by gfyoung** [pandas-dev/pandas#16242]
When I was developing #16237, I noticed that the API for checking `dtype` is quite messy.  We appear to have duplicate functionality, and the interface is not clear as to what we should accept.  

I propose that for all such `dtype` checking functions, we should accept ANY array-like and ANY `dtype` OR `type` object and cast any `list`-like object to `np.array`.

Also, I added several `TODO` in that same <a href="https://github.com/pandas-dev/pandas/blob/1a0c878f733c5fc2b37e6f6ab655e943685036f9/pandas/core/dtypes/common.py">file</a> that I was hoping to get some feedback on.  They stood out to me because they seemed either non-intuitive OR symptomatic of the API redundancy that I was referring to.

* `is_datetimetz` seems like a duplicate of `is_datetime64tz_dtype`.  Do we need it?
* `is_period` seems like a duplicate of `is_period_arraylike`.  Do we need it?
* Should `Period` be an instance of `PeriodDtype`?
* Should `Interval` be an instance of `IntervalDtype`?

**Comment by jreback** [comment]
> I propose that for all such dtype checking functions, we should accept ANY array-like and ANY dtype OR type object and cast any list-like object to np.array.

this is likely not desired. These are for unknown array-like *only* (e.g. Index,ndarray,Series), which can simply be introspected with NO computation. IOW anything that needs element-by-element detection is a no-no here.

**Comment by jreback** [comment]
can you post the TODO's here.

**Comment by gfyoung** [comment]
> this is likely not desired. These are for unknown array-like only (e.g. Index,ndarray,Series), which can simply be introspected with NO computation.

I'm confused, something like:

~~~python
def is_*_dtype(arr_or_dtype):
    if is_list_like(arr_or_dtype) and not hasattr(arr_or_dtype, dtype):
       arr_or_dtype = np.asarray(arr_or_dtype)
...
~~~

**Comment by gfyoung** [comment]
> can you post the TODO's here.

I edited the original issue to add them.

**Comment by jreback** [comment]
Should Period be an instance of PeriodDtype?
Should Interval be an instance of IntervalDtype?

yes but these would require quite some work
they only exists as Index currently

**Comment by gfyoung** [comment]
> they only exists as Index currently

What do you mean?

**Comment by jreback** [comment]
welll see what happens when you store a PeriodIndex as a column

**Comment by jbrockmendel** [comment]
@gfyoung closeable?  most of the topics mentioned in the OP look like they've been handled

**Comment by mroeschke** [comment]
Yup I think all the initial issues have been address so closing. We can open follow up issues targeting specific function if still necessary
