### ISSUE TITLE
Please release wheels with / before source

### ISSUE THREAD

**Issue by matthew-brett** [pandas-dev/pandas#16260]
I see that y'all have just released 0.20 to Pypi - congratulations!

But ... I see that you've released the source .tar.gz package, and the Windows wheels, but not yet the OSX and Linux wheels.

I wonder whether you would consider collecting the various wheels, and then releasing the source and wheels together, or the wheels before the source?

Otherwise, if you release the source before the wheels, users installing Pandas will, for a time, start to get a source install when they would previously have got a binary install, which is likely to be surprising, and might well fail.

In particular, this might have caused the travis-ci failure for matplotlib over here: https://travis-ci.org/matplotlib/matplotlib/jobs/229149439(

Thanks for considering.

**Comment by jreback** [comment]
yes we are going to release things all at once (have updated the release checklist). furthermore, we had an issue, so 0.20.1 is going to be the official (soon).

**Comment by TomAugspurger** [comment]
Sorry, that's my fault. I hiding the release was only on the UI side. I'll update our release process checklist to make it clear that the source and binary should be updated together.

**Comment by matthew-brett** [comment]
Ah - yes - I made the same mistake thinking that hiding release prevented pip from seeing it.

**Comment by jorisvandenbossche** [comment]
I suppose hiding the release does ensure that people don't download it with `pip install pandas`?

**Comment by TomAugspurger** [comment]
Actually, we should verify, with @cgohlke: When building the pandas wheels, do you fetch the release's source code from our Github releases page or PyPI?

**Comment by jorisvandenbossche** [comment]
>I suppose hiding the release does ensure that people don't download it with pip install pandas?

Not apparently. A bit unintuitive .. 
I just assumed this was the case, and therefore always already uploaded the source packages (I think in the beginning conda-forge also downloaded the source package from pypi instead of from github)

**Comment by cgohlke** [comment]
I usually build Pandas from Github releases.

**Comment by matthew-brett** [comment]
@jorisvandenbossche - ah no, hiding the release doesn't make any difference to `pip install pandas` - they still get the latest - 'hiding' only hides the release from the web UI.
