### ISSUE TITLE
Documentation for Styling has broken links

### ISSUE THREAD

**Issue by SimonBaron** [pandas-dev/pandas#16279]
I hope this is the right way to report this! It is an issue with the documentation rather than the code

#### Problem description

[http://pandas.pydata.org/pandas-docs/stable/style.html#Styling](http://pandas.pydata.org/pandas-docs/stable/style.html#Styling)

This is the first section, and contains a link to:
[http://nbviewer.jupyter.org/github/pandas-dev/pandas/blob/master/doc/source/html-styling.ipynb](http://nbviewer.jupyter.org/github/pandas-dev/pandas/blob/master/doc/source/html-styling.ipynb)

which gives me a 404 error.

Further down:
[http://pandas.pydata.org/pandas-docs/stable/style.html#Builtin-Styles](http://pandas.pydata.org/pandas-docs/stable/style.html#Builtin-Styles) 

As you can see, there is problem in the jupyter notebook where seaborn is not found. At least I assume you will see it - this is what I see:

![image](https://cloud.githubusercontent.com/assets/12841760/25799086/9aced5f0-33db-11e7-90f8-44336d996a5b.png)

error text
```
/Users/taugspurger/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/matplotlib/colors.py:494: RuntimeWarning: invalid value encountered in less
  cbook._putmask(xa, xa < 0.0, -1)
```

**Comment by jorisvandenbossche** [comment]
@SimonBaron Thanks, this is certainly the correct way to report such issues!

For the first issue, the incorrect link: the file name of the notebook has changed, and we didn't update the link apparently. Want to do a PR to correct this?

Second issue (seaborn not found) is because we apparenlty built the docs in an environment where seaborn was not installed. We will have to fix this and upload the docs again. Thanks for reporting.

**Comment by SimonBaron** [comment]
@jorisvandenbossche I think I've made a PR - I'm a bit of a GH noob, so thanks for your patience.

https://github.com/pandas-dev/pandas/pull/16280

**Comment by jorisvandenbossche** [comment]
Link is fixed, keeping this open for the seaborn issue

**Comment by TomAugspurger** [comment]
Thanks, rebuilding them now.

**Comment by jreback** [comment]
@TomAugspurger this is fixed?

**Comment by TomAugspurger** [comment]
Yeah, thanks to Joris.
