### ISSUE TITLE
how to load 0.19 MultiIndex into 0.20?

### ISSUE THREAD

**Issue by cfrancois7** [pandas-dev/pandas#16278]
I created some index in the 0.19 pandas I would reuse in the 0.20 without to recreate them from raw data in the pandas 0.20. I imported the relative numpy array but the index cannot be imported.
How I can import them in the new pandas version?

```python
pickle.load( open("index_pd.pkl", "rb" ) )
ModuleNotFoundError: No module named 'pandas.indexes'
```

**Comment by jreback** [comment]
you would have to show what versions you are using in both

what is in the pickle?

**Comment by jreback** [comment]
you need to use pd.read_pickle
