### ISSUE TITLE
ENH: Support pathlib.Path and LocalPath objects in all io functions

### ISSUE THREAD

**Issue by chris-b1** [pandas-dev/pandas#16299]
xref #16292 

Currently xfailing tests for (all should work)
 - [ ] SAS
 - [ ] msgpack
 - [x] stata 
 - [ ] HDFStore (#14705)

**Comment by jorisvandenbossche** [comment]
Some issues that could probably folded into this one (or are in the meantime fixed by your PR):

- https://github.com/pandas-dev/pandas/issues/14705 (HDFStore)
- https://github.com/pandas-dev/pandas/issues/14932 (pickle)

**Comment by bashtage** [comment]
stata looks fixed

**Comment by kszucs** [comment]
`read_json` and `to_json` also should support `pathlib.Path` objects

**Comment by jorisvandenbossche** [comment]
@kszucs I think `read_json` alredy supports pathlib objects? (quickly tried with master) 
Do you have a reproducible example?

**Comment by CircleOnCircles** [comment]
as 2019-Jul,
any updates?, I wish I could help with this topic.

**Comment by TomAugspurger** [comment]
We should be good. Let's open specific issues if any of the readers / writers don't support objects implementing the fspath protocol.
