### ISSUE TITLE
Documentation on Performance considerations

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#16310]
#### Problem description

We could use a section in the docs about performance considerations.  @TomAugspurger has a nice notebook with suggestions here:  http://nbviewer.jupyter.org/github/TomAugspurger/pandas-head-to-tail/blob/master/06-Performance.ipynb

An item to add relates to using `.assign()`, where, if you have a big DataFrame, it is more inefficient in time and memory to use `.assign()` as opposed to just creating each new column without the use of method chaining via the paradigm of 
```
    df['newcol1'] = df.a + df.b
    df['newcol2'] = df.c + df.d
```

**Comment by jreback** [comment]
see also #3871 and #8178

**Comment by andymaheshw** [comment]
Working on it at pycon2017 :)

**Comment by jorisvandenbossche** [comment]
There was also a presentation on PyCon about optimizing pandas: https://github.com/sversh/pycon2017-optimizing-pandas, which can probably be used as well for some inspiration

**Comment by mroeschke** [comment]
Looks like we have https://pandas.pydata.org/pandas-docs/stable/user_guide/enhancingperf.html so closing for now
