### ISSUE TITLE
Test against development version of bottleneck prior to 1.21

### ISSUE THREAD

**Issue by shoyer** [pandas-dev/pandas#16311]
See https://github.com/kwgoodman/bottleneck/issues/168#issuecomment-300290794

Anyone up for taking this on?

**Comment by jbrockmendel** [comment]
@shoyer you mentioned the maintainership if bottleneck is changing.  Is this issue still relevant?  Need updating?

**Comment by lithomas1** [comment]
Our minimum version of bottleneck is already 1.2.1 and this is reflected in CI. e.g. https://github.com/pandas-dev/pandas/blob/master/ci/deps/actions-37-minimum_versions.yaml
