### ISSUE TITLE
read_stata ignores `index` parameter

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#16342]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import pandas.util.testing as tm

In [19]: df = tm.makeDataFrame()

In [20]: df.to_stata('foo.stata')

In [21]: pd.read_stata('foo.stata', index='index')
Out[21]:
         index         A         B         C         D
0   2wIkgwAbVm  0.310317 -0.753652 -0.509405 -0.309492
1   59guDFHo0l  0.404983 -0.098995 -0.330786 -0.548584
2   5sX3JbPQjk  0.520377  1.379943  2.375164  1.475831
3   UsF3izOnQy -1.413272  0.668192  0.859581 -0.646165
...
```

It should be like `read_stata('foo.stata').set_index('index')`

Side-note, I think elsewhere we use `index_col` instead of `index`.

#### Output of ``pd.show_versions()``

master

**Comment by markhkim** [comment]
Isn't this fixable by adding
```python
if index in data.keys():
    data = data.set_index(index)
```
right before `return data` in the definition of `read_stata`? Am I missing something?

**Comment by VincentLa** [comment]
What is `tm.makeDataFrame()`?

**Comment by TomAugspurger** [comment]
@VincentLa Sorry, it's `import pandas.util.testing as tm` I'll fix it.

**Comment by stanleyguan** [comment]
Attempting to take a stab at this issue.

**Comment by TomAugspurger** [comment]
FYI I think @mogillies is working on this? Is that right?

**Comment by VincentLa** [comment]
Awesome. Anyone at Pycon Sprints right now who is working on this issue?

**Comment by stanleyguan** [comment]
Looking at Gitter discussions I think @mogillies is working on it. I will look for something else :)

**Comment by VincentLa** [comment]
@mogillies let me know if you're at Pycon right now and would be up for pairing!

**Comment by jorisvandenbossche** [comment]
@TomAugspurger if the `index` param is actually not working right now, shouldn't we change it to `index_col` at the same time?

**Comment by TomAugspurger** [comment]
@jorisvandenbossche oh yeah, I guess we won't be breaking backwards compat :D

**Comment by mogillies** [comment]
Should we change to Index_col?

**Comment by mogillies** [comment]
Sure.  I'm in the same room as you :)

**Comment by TomAugspurger** [comment]
@mogillies yeah, if you would `index_cols` (lowercase `i`)

**Comment by mogillies** [comment]
Sure.

**Comment by mogillies** [comment]
Just to clarify index param index not working
do you mean that first index not working or the second index not working
1.  index = index_cols
2.  index_cols = index_cols

if index is not None:
   data.set_index(index_cols)

or  (I don't think this is the case):
do you mean to use the function index_cols() in class Table?

if index is not None:
    data.index_cols()

**Comment by jorisvandenbossche** [comment]
Currently the keyword argument in `read_stata` to specify which colunm to set as the index is called `index`. And there are two issues:

- the fact that this parameter is not working
- the fact that it is a bit inconsistent with other read functions where we typically use `index_col`

You are trying to solve the first one. But what we suggest is to also fix the second one and rename the `index` keyword argument to `index_col` (but for now keeping `index` as an alias). The fact that the old keyword was not yet working just makes it a bit easier to do this change, as nobody could already rely on its behaviour.
