### ISSUE TITLE
DOC: dev docs authentication failing

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#16350]
https://travis-ci.org/pandas-dev/pandas/jobs/231962583

I regenerated the token but still not allowing the push

**Comment by jreback** [comment]
seems github/travis was compromised on may 8 and they revoked the old token for pandas-docs. I reauthenticated and trying new token. cross fingers.

**Comment by jreback** [comment]
so my regenerating is not working. if @jorisvandenbossche or @TomAugspurger have a go

@TomAugspurger having @wesm invite you to be in ``pandas-docs`` (as its a separate org)

**Comment by wesm** [comment]
i moved the repo over to pandas-dev

**Comment by TomAugspurger** [comment]
@jreback solved one issue, the `secure` entry in the `.travis.yml` was missing a `-`. 0f55de1b3 fixed that, but [still failed](https://travis-ci.org/pandas-dev/pandas/jobs/234111150#L5046). It was able to fetch, not push.

It looks like by default, team members don't get write access to the repository. I think you can either grant my account write access to the repository, or better yet we should make a deploy key that has write access (under settings/keys). I can do this, though I'll need admin rights on the repo.

**Comment by TomAugspurger** [comment]
Worked on the latest build now that the permissions issues are sorted out: https://travis-ci.org/pandas-dev/pandas/jobs/234744706

**Comment by jreback** [comment]
looks good. thanks @TomAugspurger
