### ISSUE TITLE
Odd behaviour of resample+mean+interpolate on int64 series

### ISSUE THREAD

**Issue by myyc** [pandas-dev/pandas#16361]
this issue is present on the latest stable release (as well as latest master at the time of this writing). for frames with only `int64` values, the following has strange behaviour

```python
df = {"a": [1,3,1,4]}
df = pd.DataFrame(df, index=pd.date_range("2017-01-01", "2017-01-04"))

# these two are not the same
df.resample("H").mean()["a"].interpolate("cubic")  # bad
df.resample("H")["a"].mean().interpolate("cubic")  # good

# this works
df.astype("float64").resample("H").mean()["a"].interpolate("cubic")
```

my workaround is more than enough for me but i figured i'd report it anyway...

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Darwin
OS-release: 16.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_IE.UTF-8
LANG: en_IE.UTF-8
LOCALE: en_IE.UTF-8

pandas: 0.21.0.dev+31.g0ea0f25bf
pytest: 3.0.7
pip: 9.0.1
setuptools: 35.0.2
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 6.0.0
sphinx: None
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.0.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by chris-b1** [comment]
Thanks for the report!  It looks like the in the first case the internal data structures are getting into an invalid state.

```
In [106]: s1 = df.resample("H").mean()["a"]

In [107]: s1._data.blocks[0]
Out[107]: IntBlock: 73 dtype: float64

In [108]: s2 = df.resample("H")["a"].mean()

In [109]: s2._data.blocks[0]
Out[109]: FloatBlock: 73 dtype: float64
```

**Comment by TomAugspurger** [comment]
@jreback I think this blocker for 0.20.2? I can take a look tomorrow if you don't have time.

**Comment by jreback** [comment]
hmm did this work on 0.19.2?

**Comment by TomAugspurger** [comment]
I think so

```python
In [6]: pd.__version__
Out[6]: '0.19.2'

In [7]: df = {"a": [1,3,1,4]}
   ...: df = pd.DataFrame(df, index=pd.date_range("2017-01-01", "2017-01-04"))
   ...:

In [8]: df.resample("H").mean()["a"]._data.blocks[0]
Out[8]: FloatBlock: 73 dtype: float64
```
