### ISSUE TITLE
panel.to_json() Not implemented

### ISSUE THREAD

**Issue by piperod** [pandas-dev/pandas#16376]
#### Code Sample, a copy-pastable example if possible

```python
panel.to_json(args["output"])

```
#### Problem description

I am trying to save a panel into a file. I have tried to_json(), to_csv(), but I always get an error. Are there others methods to save this structure into a file. Or should I be careful with the pandas version?

**Comment by TomAugspurger** [comment]
I believe it can be saved directly to HDF5: http://pandas-docs.github.io/pandas-docs-travis/io.html#hdf5-pytables

FYI, Panel is deprecated and is being removed in a future version: http://pandas.pydata.org/pandas-docs/version/0.20/whatsnew.html#whatsnew-0200-api-breaking-deprecate-panel

**Comment by TomAugspurger** [comment]
l
