### ISSUE TITLE
TST: test_mixed_freq_regular_first failing on master

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#16371]
Started with https://travis-ci.org/pandas-dev/pandas/builds/232766866, which clearly (I think?) isn't to blame.

I don't see any differences in dependencies between https://travis-ci.org/pandas-dev/pandas/jobs/232654666 and https://travis-ci.org/pandas-dev/pandas/jobs/232766873 will dig in more later.

**Comment by jreback** [comment]
looks like maybe mpl 2.0.2? (not sure how recent it was)

**Comment by jorisvandenbossche** [comment]
I cannot reproduce this locally, also not with matplotlib 2.0.2 (and also the succeeding travis build before it started failing already had 2.0.2)

**Comment by TomAugspurger** [comment]
@tacaswell shot in the dark here, but any guesses what's up with these kinds of failures? e.g. https://travis-ci.org/pandas-dev/pandas/jobs/236416092#L2162 No worries if you don't have any ideas.

I haven't been able to confirm it, but these failures are *consistent* with what would happen if we plot onto an existing figure with a different datetime frequency. All figures should be closed between tests, but who knows? Maybe something weird with pytest-xdist? Another failure: https://travis-ci.org/TomAugspurger/pandas/jobs/233810539

**Comment by tacaswell** [comment]
Collisions from the pyplot global state is plausible.  

Does it work if you restart the test?  

Flipping through the builds on master it looks like it sometimes passes and sometimes fails.  In the mpl test suite we have had issue where one tests is missing the clean up logic (which in this case I assume is taken care of in by the class?).  The dictionary iteration randomization means sometimes the sensitive test runs after a test that properly cleans up and sometimes not (at least I think that is the mechanism, have not dug too far into it).

**Comment by TomAugspurger** [comment]
> Collisions from the pyplot global state is plausible.

This is the best guess we have right now, thanks. I'll try to replace this
instances with explicit fig / axes creation.

> Does it work if you restart the test?

Yeah, it's failing like 20-30% of the time.

Thanks

On Sun, May 28, 2017 at 10:01 PM, Thomas A Caswell <notifications@github.com

**Comment by tacaswell** [comment]
Adding an explicit `clf()` might also help.
