### ISSUE TITLE
pandas retraive a hdf5 dataset with more values for fields 

### ISSUE THREAD

**Issue by MarcoMottola87** [pandas-dev/pandas#16377]
I'd like to retrieve a dataset from hdf5 in a pandas dataframe datastrucure. This dataset contains more values separated by coma for each columns, like as picture shows.
[https://i.stack.imgur.com/hT5f8.jpg](url)
I try with:

import pandas as pd

store=pd.HDFStore(path_file)

df=store[path_tree]
I get following error:

File "C:\Anaconda2\lib\site-packages\pandas\core\internals.py", line 86, in init len(self.values), len(self.mgr_locs)))

ValueError: Wrong number of items passed 5, placement implies 1

Does Pandas HDFstore suppot this type of object?
How can I retrieve this dataframe?

**Comment by TomAugspurger** [comment]
Can you make a copy-pastable example? Ideally some code to generate a fake dataset like yours, and then code to read it.

**Comment by TomAugspurger** [comment]
Let us know if you can make an example.
