### ISSUE TITLE
ENH: Add option for Parquet metadata to disambiguate index names that conflict with column names

### ISSUE THREAD

**Issue by wesm** [pandas-dev/pandas#16391]
As an improvement on the Parquet metadata https://github.com/pandas-dev/pandas/blob/master/doc/source/developer.rst, we should provide an option to specify an index as:

```
{'column_name': $SOME_UNIQUE_IDENTIFIER,
 'name': $INDEX_NAME}
```

If the metadata contains an index entry that is a string, then it is assumed that the column name in the Parquet file and the index name are the same. That way the current specification is forward compatible

**Comment by jorisvandenbossche** [comment]
This was closed by https://github.com/pandas-dev/pandas/pull/18201
