### ISSUE TITLE
DOC: add examples to docstrings

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#16416]
This often used functions lacks some illustrating examples

- [x] ``sort_values`` (#16437)
- [ ] ``reset_values``
- [x] ``set_index`` (#16467)
- [x] ``fillna`` (#16437)
- [x] ``drop`` (#16437)
- [x] ``pop`` (#16520)

**Comment by jorisvandenbossche** [comment]
Other docstrings that are in the top most viewed and lacking examples: `reset_index`, `set_index`, `fillna`, `drop`

**Comment by geoninja** [comment]
@jorisvandenbossche I'd like to take this one.

**Comment by VincentLa** [comment]
@geoninja any chance you're at Pycon doing sprints right now?

**Comment by VincentLa** [comment]
I can add some examples for `fillna` and `drop`.

**Comment by geoninja** [comment]
@jorisvandenbossche Both Vincent and I are at PyCon so we will split the work on this one

**Comment by geoninja** [comment]
I'm going to work on reset_values so we can close this issue.

**Comment by jreback** [comment]
if anyone at sprints wants to add to ``.reset_index()`` we can close this one

@TomAugspurger

**Comment by aernlund** [comment]
I'm working on .reset_index() example.
