### ISSUE TITLE
DOC:  Pandas Contribution Documentation:  Forking Instructions

### ISSUE THREAD

**Issue by puifais** [pandas-dev/pandas#16419]
#### Problem description

As a newbie contributing to an open source project for the first time, I find the[ instruction for forking](http://pandas.pydata.org/pandas-docs/stable/contributing.html#forking) a little difficult to follow. Specifically, on this line

```python
git clone git@github.com:your-user-name/pandas.git pandas-yourname
```

#### Output of ``git clone git@github.com:your-user-name/pandas.git pandas-yourname``

<details>
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

</details>

I was able to clone the repository by using the following code
```python
git clone https://github.com/your-user-name/pandas.git pandas-yourname
```

#### Expected Output

<details>
Cloning into 'pandas-username'...
remote: Counting objects: 124979, done.
remote: Total 124979 (delta 0), reused 0 (delta 0), pack-reused 124978
Receiving objects: 100% (124979/124979), 96.04 MiB | 1.89 MiB/s, done.
Resolving deltas: 100% (103137/103137), done.
</details>

I am hesitant on how best to edit the documentation because I know that for people who are more experience, they know automatically to set up a key when they see the ```git@github.com:your-user-name/``` part

**Comment by TomAugspurger** [comment]
I think your change makes sense (I usually use https)

Want to make a pull request updating that file?
