### ISSUE TITLE
DOC: add warning to append about inefficiency

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#16418]
In many cases, using `append` to add rows is not the best way to go, as this is very inefficient (certainly if you do this in a for loop, each time taking a copy)

If in a situation where you have this pattern of appending in a for loop, you typically want to append to a list and then concatenate all at once using `concat`.

Would by good to add a note about this in the `append` docstring.

**Comment by mogillies** [comment]
I'm working on it.

**Comment by shanral** [comment]
I've picked this up since it seems available again.

**Comment by mogillies** [comment]
Sorry I haven't completed as I am stuck with the testing.

Go ahead if you want to do it.  Can I see how you do it after you are done?

Mo
