### ISSUE TITLE
Add histtype argument to pandas.Series.plot.hist()

### ISSUE THREAD

**Issue by AllanLRH** [pandas-dev/pandas#16423]
Would be nice if pandas either 

1. Propagated keyword arguments to Matploblib hist (I believe there's an issue about it here: #14109 )
2. Explicitly took the `histtype` argument, since `histtype='stepfilled'` can  greatly speed up the histogram plot rendering.

**Comment by mzeitlin11** [comment]
Similar issue looks to have been closed in #23992 with #37063 testing usage of `histtype`.
