### ISSUE TITLE
DOC: Explain how our shared_docs system works

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#16446]
Enhance https://github.com/pandas-dev/pandas/blob/master/doc/source/contributing.rst with a discussion of how our `_shared_docs` system works.

- Why we do it (reduce duplicate docstrings, while still having some class-specific stuff)
- How it's done (Appender, _shared_docs dict, _shared_doc_kwargs)
- How to substitute values

**Comment by TheGhostHuCodes** [comment]
I was working with one of our fellow PyCon2017 sprinters figure out this system. I'll take a shot at writing this up in the docs.

**Comment by TomAugspurger** [comment]
Thanks. Post here or on gitter if you have any questions.

**Comment by AdamShamlian** [comment]
@TomAugspurger is there a "central" location where I can start to self-educate myself here? After a cursory glance through source, I couldn't seem to find a file that would be considered a "best starting place." Should I just start inferring patterns and usage by looking across source as a whole?

**Comment by TomAugspurger** [comment]
@AdamShamlian the best places to start are probably:

1. The definitions in `pandas/core/generic.py`: https://github.com/pandas-dev/pandas/blob/36c309ed51b98e97fb64238232ecdc795040ad24/pandas/core/generic.py#L61 where most of these are defined
2. The uses in `pandas/core/frame.py`, `pandas/core/series.py`, etc (search for `_shared_docs`)
3. The implementation in `pandas/util/_decorators.py`: https://github.com/pandas-dev/pandas/blob/36c309ed51b98e97fb64238232ecdc795040ad24/pandas/util/_decorators.py#L126 (maybe it'll help you understand whats going on).

Let me know if you have questioons!

**Comment by AdamShamlian** [comment]
Ok, thanks for the tips!
