### ISSUE TITLE
API/DOC: Specification for `names` parameter in read_csv

### ISSUE THREAD

**Issue by gfyoung** [pandas-dev/pandas#16469]
On `master` (<a href="https://github.com/pandas-dev/pandas/commit/04356a83c0dc8a749c84e168535e6673f2548ec6">04356a</a>), the documentation is unclear as to what a valid `names` parameter is for `read_csv`.

* Does it need to have the same length as the number of columns in the file? OR
* Does it need to have the same length as `usecols` if specified?

I find evidence in the test cases to support both (C engine allows both for example, but the Python engine disallows the former).  This point should also be clarified in the documentation.

xref #14671.

**Comment by gfyoung** [comment]
I suspect that I would towards using the latter, since why specify all of the column names if you're not going to use all of them?

**Comment by jreback** [comment]
is this covered?

**Comment by gfyoung** [comment]
@jreback : What do you mean by this?  This is just a behavior question that I'm still unsure about but was hoping to get some feedback before making any decisions.

**Comment by gfyoung** [comment]
Marking this as a bug because:

* It works on the C engine (but not the Python engine)
* This ambiguity doesn't exist when there is no existing header.  It works both ways for both engines.
