### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by oxhaowang** [pandas-dev/pandas#16473]
#### Problem Description

For latest 0.20.1 version I got: 

```python
>>> import pandas
Segmentation fault (core dumped)

```
When I rolled back to version 0.19.2, the import line works fine but not the test function, see:

```python
$ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> import pandas as pd
>>> pd.test()
Running unit tests for pandas
pandas version 0.19.2
numpy version 1.12.1
pandas is installed in /usr/local/lib/python3.5/dist-packages/pandas
Python version 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]
nose version 1.3.7
Segmentation fault (core dumped)
``` 
This might not be a pandas issue after all. I am posting this in case anyone got any clues.. 

*Other installed python3 modules on my machine are*

<details>
alabaster==0.7.10
apiclient==1.0.3
appdirs==1.4.3
apsw==3.9.2.post1
apturl==0.5.2
asn1crypto==0.22.0
astroid==1.5.2
astropy==1.3.2
Babel==2.4.0
beautifulsoup4==4.6.0
bleach==2.0.0
blinker==1.4
blosc==1.5.1
bokeh==0.12.5
boto==2.46.1
bottle==0.12.13
Bottleneck==1.2.1
branca==0.2.0
Brlapi==0.6.4
cffi==1.10.0
chardet==3.0.3
checkbox-support==0.33.0
colorama==0.3.9
command-not-found==0.3
corner==2.0.1
CProfileV==1.0.7
cryptography==1.8.1
cycler==0.10.0
Cython==0.25.2
decorator==4.0.11
defer==1.0.6
demjson==2.2.4
docutils==0.13.1
emcee==2.2.1
entrypoints==0.2.2
et-xmlfile==1.0.1
fbprophet==0.1.1
feedparser==5.2.1
flake8==3.3.0
folium==0.3.0
googlefinance==0.7
guacamole==0.9.2
h5py==2.7.0
html5lib==0.999999999
httplib2==0.10.3
idna==2.5
imagesize==0.7.1
inflection==0.3.1
ipykernel==4.6.1
ipython==6.0.0
ipython-genutils==0.2.0
ipywidgets==6.0.0
isort==4.2.5
jdcal==1.3
jedi==0.10.2
Jinja2==2.9.6
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.0.1
jupyter-console==5.1.0
jupyter-core==4.3.0
Keras==2.0.4
language-selector==0.1
lazy-object-proxy==1.3.1
line-profiler==2.0
louis==2.6.4
lxml==3.7.3
mahotas==1.4.3
Mako==1.0.6
Markdown==2.6.8
Markdown-Editor==1.0.3
MarkupSafe==1.0
matplotlib==2.0.2
mccabe==0.6.1
memory-profiler==0.47
mistune==0.7.4
more-itertools==3.0.0
nbconvert==5.1.1
nbformat==4.3.0
ndg-httpsclient==0.4.2
networkx==1.11
nltk==3.2.4
nose==1.3.7
notebook==5.0.0
numexpr==2.6.2
numpy==1.12.1
numpydoc==0.6.0
oauthlib==2.0.2
olefile==0.44
onboard==1.2.0
openpyxl==2.4.7
packaging==16.8
padme==1.1.1
pandas==0.19.2
pandas-datareader==0.4.0
pandocfilters==1.4.1
patsy==0.4.1
pep8==1.7.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.1.1
plainbox==0.34.0
prompt-toolkit==1.0.14
protobuf==3.3.0
psutil==5.2.2
psycopg2==2.7.1
ptyprocess==0.5.1
pyasn1==0.2.3
pycallgraph==1.0.1
pycodestyle==2.3.1
pycparser==2.17
pycups==1.9.73
pycurl==7.43.0
pyenchant==1.6.8
pyflakes==1.5.0
Pygments==2.2.0
pygobject==3.20.0
pygtkspellcheck==4.0.5
PyJWT==1.5.0
pylint==1.7.1
pymdown-extensions==3.2
PyMySQL==0.7.11
PyOpenGL==3.1.0
pyOpenSSL==17.0.0
pyparsing==2.2.0
PyQt5==5.8.2
pyqtgraph==0.10.0
pysmbc==1.0.15.5
pystan==2.15.0.1
python-apt==1.1.0b1
python-dateutil==2.6.0
python-debian==0.1.28
python-systemd==231
python-termstyle==0.1.10
pytz==2017.2
pyxdg==0.25
PyYAML==3.12
pyzmq==16.0.2
QtAwesome==0.4.4
qtconsole==4.3.0
QtPy==1.2.1
Quandl==3.1.0
rednose==1.2.2
requests==2.14.2
requests-file==1.4.2
requests-ftp==0.3.1
roman==2.0.0
rope-py3k==0.9.4.post1
scikit-fuzzy==0.2
scikit-learn==0.18.1
scipy==0.19.0
screen-resolution-extra==0.0.0
seaborn==0.7.1
sessioninstaller==0.0.0
simplegeneric==0.8.1
sip==4.19.2
six==1.10.0
sklearn==0.0
snowballstemmer==1.2.1
Sphinx==1.6.1
sphinx-rtd-theme==0.2.4
sphinxcontrib-websupport==1.0.1
spyder==3.1.4
SQLAlchemy==1.1.10
statsmodels==0.8.0
system-service==0.3
tables==3.4.2
tensorflow==1.1.0
terminado==0.6
termstyle==0.1.11
testpath==0.3
Theano==0.9.0
tornado==4.5.1
traitlets==4.3.2
tushare==0.5.0
typing==3.6.1
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
unity-scope-calculator==0.1
unity-scope-chromiumbookmarks==0.1
unity-scope-colourlovers==0.1
unity-scope-devhelp==0.1
unity-scope-firefoxbookmarks==0.1
unity-scope-gdrive==0.7
unity-scope-manpages==0.1
unity-scope-openclipart==0.1
unity-scope-texdoc==0.1
unity-scope-tomboy==0.1
unity-scope-virtualbox==0.1
unity-scope-yelp==0.1
unity-scope-zotero==0.1
urllib3==1.21.1
usb-creator==0.3.0
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.12.2
widgetsnbextension==2.0.0
wrapt==1.10.10
wxPython-Phoenix==3.0.3
xarray==0.9.5
xdiagnose==3.8.4.1
xkit==0.0.0
xlrd==1.0.0
XlsxWriter==0.9.6
xlwt==1.2.0

</details>
 
#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-78-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.19.2
nose: 1.3.7
pip: 9.0.1
setuptools: 35.0.2
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
statsmodels: 0.8.0
xarray: 0.9.5
IPython: 6.0.0
sphinx: 1.6.1
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: 1.5.1
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
matplotlib: 2.0.2
openpyxl: 2.4.7
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.3
bs4: 4.6.0
html5lib: 0.999999999
httplib2: 0.10.3
apiclient: None
sqlalchemy: 1.1.10
pymysql: 0.7.11.None
psycopg2: 2.7.1 (dt dec pq3 ext lo64)
jinja2: 2.9.6
boto: 2.46.1
pandas_datareader: 0.4.0

</details>

**Comment by jreback** [comment]
you have an installation problem.  pls read the instructions [here](http://pandas.pydata.org/pandas-docs/stable/install.html). ``conda install pandas`` or ``pip install pandas`` works.

**Comment by oxhaowang** [comment]
@jreback  I did installed with pip...

**Comment by blakeliu** [comment]
wjy@wjy-Z270X-UD3:~/blake/medical/test$ conda install  pandas
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /home/wjy/anaconda3:

The following NEW packages will be INSTALLED:

    pandas: 0.20.3-py35_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free

Proceed ([y]/n)? y

wjy@wjy-Z270X-UD3:~/blake/medical/test$ python
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> import pandas as pd
>>> pd.test()
running: pytest --skip-slow --skip-network /home/wjy/anaconda3/lib/python3.5/site-packages/pandas
============================ test session starts =============================
platform linux -- Python 3.5.2, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/wjy/anaconda3/lib/python3.5/site-packages/pandas, inifile: 
collecting 6594 items / 2 skipped段错误 (核心已转储)
