### ISSUE TITLE
DOC: filter method for *GroupBy objects

### ISSUE THREAD

**Issue by javidcf** [pandas-dev/pandas#16483]
There does not seem to be a reference to the `filter` method of `GroupBy`/`SeriesGroupBy`/`DataFrameGroupBy` objects in the [API documentation](https://pandas.pydata.org/pandas-docs/stable/api.html), even though it is mentioned in the [Group By documentation](http://pandas.pydata.org/pandas-docs/stable/groupby.html#filtration).

**Comment by VincentLa** [comment]
I can pick this up! If anyone is at pycon sprints in portland, happy to pair on this as well.

**Comment by VincentLa** [comment]
Well actually it looks like the example is defined here for [`SeriesGroupBy`](https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby.py#L3008) and here for [`NDFrameGroupBy`](https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby.py#L3826). So is the fix to this to just add it to [api.rst](https://github.com/pandas-dev/pandas/blob/master/doc/source/api.rst)?
