### ISSUE TITLE
read_csv read on the fly from 7z

### ISSUE THREAD

**Issue by cirmic** [pandas-dev/pandas#16482]
#### Only a suggest:

Is it possible to insert in the future versions the feature for read on the fly into a 7z file?

**Comment by chris-b1** [comment]
Just from a quick google it's not clear there's a great 7zip python library (maybe https://pypi.python.org/pypi/libarchive?)  - but to the extent there is a functioning one, would be easy enough to add - around here.

https://github.com/pandas-dev/pandas/blob/7271f50c234faeaaac177a4e1829b7401ea252ee/pandas/io/common.py#L374

**Comment by cirmic** [comment]
With Python 2.7.13 when I specify `compression="xz"` into read_csv method it returns `cannot import name lzma`.

I know that lzma is default library from Python 3.3, is there a way to use also into 2.7 ?

**Comment by chris-b1** [comment]
Yes, see docs here - need to install the backports version
http://pandas.pydata.org/pandas-docs/stable/install.html?highlight=lzma#optional-dependencies
