### ISSUE TITLE
to_html(index_names=False) still renders a row with index names

### ISSUE THREAD

**Issue by CRP** [pandas-dev/pandas#16493]
The index_names parameter is apparently ignored.
I tried to debug the code, and it looks like line 1291 of pandas/io/formats/format.py should contain "and self.fmt.show_index_names" in the if clause.

here is sample code:

```python
x=DataFrame(np.random.randn(3,4),columns=list('abcd'))
x.index.name='pippo'
print(x.to_html(index_names=False))
```
which produces the following output:
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>a</th>
      <th>b</th>
      <th>c</th>
      <th>d</th>
    </tr>
    <tr>
      <th>pippo</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1.715511</td>
      <td>-1.582624</td>
      <td>0.027399</td>
      <td>-0.276980</td>
    </tr>
    <tr>
      <th>1</th>
      <td>-0.003603</td>
      <td>-1.227605</td>
      <td>0.434763</td>
      <td>0.039167</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.246343</td>
      <td>-0.062897</td>
      <td>-0.724532</td>
      <td>-0.352672</td>
    </tr>
  </tbody>
</table>

the second row of the thead should not be there...

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Darwin
OS-release: 16.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.20.1
pytest: None
pip: 9.0.1
setuptools: 35.0.2
Cython: None
numpy: 1.12.1
scipy: 0.19.0
xarray: 0.9.5
IPython: 6.0.0
sphinx: None
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: None
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.7
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: None
bs4: None
html5lib: 0.999999999
sqlalchemy: 1.1.9
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by TomAugspurger** [comment]
May be as simple as also checking `self.fmt.index_names` in https://github.com/pandas-dev/pandas/blob/e41fe7f52a7ae6be962e683f40500624b2ba2cf6/pandas/io/formats/format.py#L1295 (and tests).

@CRP interested in submitting a fix?

**Comment by CRP** [comment]
just created pull requested. not sure if I did everything right...
