### ISSUE TITLE
DEPR: deprecation removals for 0.17/0.18 items

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#16506]
xref #6581 

We can selectively / maybe also do some 0.19 items (but let's leave them for now).

**Comment by gfyoung** [comment]
@jreback : Could we just mark which deprecations are removable in #6581?  That way we don't need to keep opening new issues every time?

**Comment by jreback** [comment]
all of them

**Comment by gfyoung** [comment]
@jreback : That's not what I meant.  I meant like saying at the top of each section (i.e. 0.17, 0.18...) that they are removable.

**Comment by jreback** [comment]
done

**Comment by gfyoung** [comment]
@jreback : Thanks!  So either we can leave the issue open as is, or close since the relevant information is recorded in #6581.

**Comment by jorisvandenbossche** [comment]
Let's close this, as the actual to do list is in #6581. Changed the milestone on the other issue
