### ISSUE TITLE
No API support for is_string_like

### ISSUE THREAD

**Issue by bashtage** [pandas-dev/pandas#16516]
#### Code Sample, a copy-pastable example if possible

```python
from pandas.api.types import is_string_like
```
#### Problem description

The deprecation message for `is_string_like` says:

`DeprecationWarning: pandas.core.common.is_string_like is deprecated. These are not longer public API functions, but can be imported from pandas.api.types.is_string_like instead`

Instead it is unavailable in 0.20.1 and an `ImportError` occurs instead.

#### Expected Output

Import `is_string_like`

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.20.1
pytest: 3.1.0
pip: 9.0.1
setuptools: 35.0.2
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
xarray: 0.9.5
IPython: 6.0.0
sphinx: 1.6.1
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: None
tables: 3.2.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: None
xlrd: 1.0.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.6.0
html5lib: 0.999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: 0.4.0
</details>

**Comment by jreback** [comment]
we removed this from the API, must not be included in the moved functions (IIRC in pandas.api.types)

**Comment by bashtage** [comment]
Is this supposed to go away and not be available or was it just not imported in the api.types module?

**Comment by jreback** [comment]
it's supposed to go away
it should have been deprecated

**Comment by TomAugspurger** [comment]
Do we have a guiding principal for stuff in `api.types`? Anything having to do with pandas-specific types should clearly be there, like `is_categorical_dtype`. I don't see why `is_bool` is there, but `is_string_like` isn't.

I have a strong preference for whether methods like `is_string_like` should be there or not.
On the one hand, there's nothing pandas-specific about it. On the other, it's annoying to have to write that code in my own projects, so I typically reach in to pandas for it. @bashtage do you have a preference here, as a contributor to and user of pandas?

**Comment by jreback** [comment]
> Do we have a guiding principal for stuff in api.types? Anything having to do with pandas-specific types should clearly be there, like is_categorical_dtype. I don't see why is_bool is there, but is_string_like isn't.

we expose type specific introspection methods. IIRC we took out ``is_string_like`` because it didn't match the patter of others. I guess should be renamed to ``is_string`` (e.g. meant to detect scalar strings). The ``is_string_like``.

So I guess this got dropped somehow.

**Comment by bashtage** [comment]
I used it because it was simple and I didn't need to worry about corner cases since these would be handled by pandas.  Ultimately it is a very simple function and so I have now just locally copied it.

In terms of public API, I would suggest that is makes most sense to only expose things that are used to detect Pandas types, which is similar to what was left exposed from `testing`.

**Comment by jbrockmendel** [comment]
is_string_like has been removed, since it is now just an alias for `isinstance(obj, str)`.  closing.  if there is something else to address here ping and we can re-open.
