### ISSUE TITLE
TST: pytest.raises vs. tm.assert_raises_regex

### ISSUE THREAD

**Issue by gfyoung** [pandas-dev/pandas#16521]
I'm wondering whether we should explicitly say in the docs that we prefer `tm.assert_raises_regex` over `pytest.raises` <em>unless</em> there is no error message to provide.  The former is a lot more informative from a dev-perspective as to why certain code should fail.

Thoughts?

(If we can agree that we do prefer the former, I also move to convert some of the tests to use `tm.assert_raises_regex` instead of `pytest.raises`).

**Comment by jreback** [comment]
I don't think this is necessary to *always* check the actual content of the error, unless the content of the message is relevant (maybe to distinguish cases).

**Comment by gfyoung** [comment]
@jreback : Fair enough, but I think in many cases, we can though.  One of my arguments for using `tm.assert_raises_regex` is that you can get a better idea of WHY code should fail beyond just the exception being raised.

So sure, I don't think all of them need to be converted, but I still do think `tm.assert_raises_regex` should be preferred by default.  @jreback how does that sound?

**Comment by TomAugspurger** [comment]
FWIW, I would like to avoid calling pytest-specific methods where possible, to make a migration away from pytest easier in the far future, if that's ever necessary.

We could add a `tm.assert_raises` context manager that simply wraps `pytest.raises` at the moment.

**Comment by gfyoung** [comment]
@TomAugspurger : That is possible, though `tm.assert_raises_regex(exc, None)` also does the trick.

**Comment by jreback** [comment]
> FWIW, I would like to avoid calling pytest-specific methods where possible, to make a migration away from pytest easier in the far future, if that's ever necessary.

I don't think this is a good reason. The good reason is that simply changing an error message can cause failures which are not immediately obvious (of course you *want* things to fail, but this mean that your regext could be too strict).

**Comment by gfyoung** [comment]
@jreback : I think @TomAugspurger was somewhat separate from the main discussion.  That being said, what you said is one reason why I think we should prefer `tm.assert_raises_regex` by default.

**Comment by gfyoung** [comment]
I'm going to close this, since I think there is sufficient discussion on this matter (at least for myself :smile:).  Can always revisit if need be.

**Comment by gfyoung** [comment]
@pandas-dev/pandas-core 

I'd like to re-open this in part because `pytest.raises` now supports regex matching (via the `match` parameter), which is exactly what `tm.assert_raises_regex` is designed to do.

IIUC, there is some effort to make things for `pytest`-idiomatic.  Thus, the question is: do we want to use `pytest.raises` across the board and drop `tm.assert_raises_regex` ?

I would bring up a similar question for `pytest.warns`, but I understand that it currently does not check stacklevel unlike our implementation --> I'll focus just on `tm.assert_raises_regex`.

**Comment by WillAyd** [comment]
I'd be +1 on this. Doesn't seem like a long term fit to maintain this method in our code base

**Comment by jorisvandenbossche** [comment]
Also +1 for using `pytest.raises` now it has all functionality (I think?) we need.

For `pytest.warns`, maybe it would a good idea if somebody finds the time to ask `pytest` if they would be interested in adding such a feature.

**Comment by TomAugspurger** [comment]
Opened https://github.com/pytest-dev/pytest/issues/4343 upstream in pytest.

**Comment by gfyoung** [comment]
The deed has been done!  See #23592.
