### ISSUE TITLE
DOC: html docs - style parameter box impacted by jupyter notebook

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#16548]
See eg http://pandas-docs.github.io/pandas-docs-travis/generated/pandas.read_csv.html#pandas.read_csv. The 'Parameters' is vertically aligned in the middle of the cell, and therefore not visible anymore. Also something of the coloring has changed, but not sure if that matters much.

**Comment by jorisvandenbossche** [comment]
@TomAugspurger so because the Parameter sections are actually tables, it uses the styling you added for the Style notebook. 

But I was thinking, would it make sense to add the 'dataframe' class the the `styler` html output, similar as to the conventional html notebook repr of a DatFrame? 
If we do that, we can just add the 'dataframe' class to the css styles you added. We can also solve this in another way, but adding the 'dataframe' class would maybe be nice anyway for consistency?

**Comment by TomAugspurger** [comment]
> But I was thinking, would it make sense to add the 'dataframe' class the the styler html output, similar as to the conventional html notebook repr of a DatFrame?

Yeah, that sounds good, but it could probably use a deprecation cycle.  The way you'd do this manually is

```python
df.style.set_table_attributes('class="dataframe"')
```

That'll give `<table id="T_5e651fba_460e_11e7_8396_186590cd1c87" class="dataframe">`

For now, I can add that to the `style.ipynb` and update the css. It'll be a bit of noise, but it'd be nice to fix the docs.

Or I guess we could update our sites CSS. The "Parameters" section is in the "docutils field-list" classes

**Comment by mroeschke** [comment]
The current read_csv docs at https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html looks okay. Not sure if this is still an issue so closing but can reopen if I'm misunderstanding
