### ISSUE TITLE
Old read_csv() & EOF character issue back

### ISSUE THREAD

**Issue by gaptekar** [pandas-dev/pandas#16559]
I recently updated from pandas 0.19.2 to 0.2
I am experiencing the exact same issue as this person did back in 2013
https://github.com/pandas-dev/pandas/issues/5500
"Error tokenizing data. C error: EOF inside string starting at line. 140"

Reverting back to 0.19.2 has fixed the issue. Can run the unit test that was created for this problem?
 https://github.com/gfyoung/pandas/commit/8c4cf85943e647cbb8a0e081ad1e6277dbd309b9

**Comment by jreback** [comment]
can you show a reproducible example.

**Comment by gorkemozkaya** [comment]
I'm having the same problem. Python 3, pandas 0.20.2

reproducible example:

import pandas as pd

with open('test.csv', 'wb') as fout:
    fout.write(b'c1,c2\r\n"test \x1a    test", test\r\n')

pd.read_csv('test.csv')

#ParserError: Error tokenizing data. C error: EOF inside string starting at line 1

**Comment by jorisvandenbossche** [comment]
Is this a windows issue? (cannot reproduce your example above on linux)

**Comment by gorkemozkaya** [comment]
Yes, it happened on a 64 bit Windows.

**Comment by jreback** [comment]
@gfyoung can you verfiy / see if you can fix?

**Comment by gfyoung** [comment]
A git bisection reveals that #16039 is the culprit.  PR coming soon.
