### ISSUE TITLE
IntervalIndex is_non_overlapping_monotonic is incorrect when endpoints are shared

### ISSUE THREAD

**Issue by jschendel** [pandas-dev/pandas#16560]
#### Code Sample, a copy-pastable example if possible

```python
In [2]: idx = pd.IntervalIndex.from_breaks(range(4), closed='both')

In [3]: idx
Out[3]:
IntervalIndex([[0, 1], [1, 2], [2, 3]]
              closed='both',
              dtype='interval[int64]')

In [4]: idx.is_non_overlapping_monotonic
Out[4]: True
```
#### Problem description
The intervals have an overlap in the endpoints, 1 is shared among `[0, 1], [1, 2]` and 2 is shared among `[1, 2], [2, 3]`, but `is_non_overlapping_monotonic` returns `True` indicating that the intervals are non-overlapping.

#### Expected Output
I'd expected `is_non_overlapping_monotonic` to return `False`.  

If my interpretation of "overlapping" is incorrect, and in this context means an interval overlap (i.e. not a point/has positive length), then it'd be nice if this were more explicitly stated.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.20.1
pytest: 3.0.7
pip: 9.0.1
setuptools: 34.4.1
Cython: 0.25.2
numpy: 1.13.0rc2
scipy: 0.18.1
xarray: 0.9.5
IPython: 5.3.0
sphinx: None
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: 1.4.4
bottleneck: 1.2.0
tables: 3.4.2
numexpr: 2.6.1
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.0
xlrd: 1.0.0
xlwt: None
xlsxwriter: None
lxml: 3.7.3
bs4: None
html5lib: None
sqlalchemy: 1.1.10
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: 0.1.6
pandas_datareader: 0.4.0
</details>

**Comment by jschendel** [comment]
At first glance, I think this amounts to using strict inequalities when `closed='both'`, and using the existing inclusive inequality code for [`is_non_overlapping_monotonic`](https://github.com/pandas-dev/pandas/blob/master/pandas/core/indexes/interval.py#L555-L560) otherwise.

**Comment by jreback** [comment]
``closed='both'`` is not very well tested. Almost all things exercise ``closed='right'``, which is the default. So for certain could add some tests.
