### ISSUE TITLE
Option for making pandas dataframe completely immutable

### ISSUE THREAD

**Issue by mitar** [pandas-dev/pandas#16567]
It seems currently there is no option similar to numpy's [setflags](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.setflags.html) to make pandas dataframe completely immutable (writeable=false). We are considering a design where we use immutability to know that we can cache objects. While we can still design a system like that, it would be great if we could enforce immutability to catch any errors.

**Comment by jreback** [comment]
This is not in-scope for pandas 1.x, it *could* be done in a sub-class.

Virtually all operations return new objects. Simply don't use ``inplace`` flags, nor do in-place indexing and you have de-facto immutability.

**Comment by jreback** [comment]
you can also use ``pandas.util.hash_pandas_object`` to make data hashes as well.

**Comment by mitar** [comment]
Oh. :-( As a subclass it is pretty tricky, because you have to make sure you shadow over Pandas methods which can potentially change internals. Hashing is also not enough. It can tell you that something changed, but not prevent changing.

**Comment by mitar** [comment]
Is there a way to tell pandas to create a pandas object using a subclass?

**Comment by jreback** [comment]
http://pandas-docs.github.io/pandas-docs-travis/internals.html

**Comment by fkromer** [comment]
@mitar @jreback  @TomAugspurger I know of this third party package addressing this issue: [static-frame](https://github.com/InvestmentSystems/static-frame). Do you know other packages as well?

**Comment by TomAugspurger** [comment]
Nope.

**Comment by fkromer** [comment]
Is there is also no tooling support (e.g. pylint extension) to ensure people don't introduce bugs into functionality which takes a dataframe as input, manipulates the dataframe and output the manipulated dataframes by mistake?

**Comment by fkromer** [comment]
For functions a workaround could be to implement a decorator for dynamic analysis: It would have to check which `args` and `kwargs` are dataframes or series. For e.g. a single dataframe it would have to calculate the hash of the input dataframe `df_in` before and after the wrapped function is called (`df_in_hash_before = pd.util.hash_pandas_object(df_in, index=True)`, `df_in_hash_after = pd.util.hash_pandas_object(df_in, index=True)`) and assert if the hashes differ (`pd.testing.assert_series_equal(input_df_hash, output_df_hash)`).

**Comment by mitar** [comment]
Yes, I gave up on this. I find it really sad because Pandas is almost there. Many methods have `in_place` argument and it would be great if you could just enforce this to be `False` and prevent any other modifications. Getting a copy every time by design (when enabled).

**Comment by fkromer** [comment]
To get this into `pandas` would be too optimistic I guess. I'm thinking about to implement the decorator and publishing it in a package `pytest-pandas`. This would allow to add dynamic anaysis of "mutability conformity" during tests.
