### ISSUE TITLE
BLD: PEP8 dev tag

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#16568]
```
/Users/jreback/miniconda3/envs/pandas/lib/python3.6/site-packages/setuptools/dist.py:333: UserWarning: Normalizing '0.21.0.dev+108.gee8346d' to '0.21.0.dev0+108.gee8346d'
  normalized_version,
```

see dev -> dev0. I guess this is PEP8? maybe next time we dev tag should fix.

just shows up on a ``make``

**Comment by jreback** [comment]
cc @TomAugspurger

**Comment by TomAugspurger** [comment]
From [pep 440](https://www.python.org/dev/peps/pep-0440/)

> Development release segment: .devN

So yeah, we should do that. I updated the release wiki.

**Comment by jreback** [comment]
great thanks!
