### ISSUE TITLE
Behaviour of "in" on a series

### ISSUE THREAD

**Issue by lengross** [pandas-dev/pandas#16594]
s = pd.Series([0,10,20,30])
l = [0,10,20,30]

val =  10
print( val," in l", val in l)
print( val," val in s", val in s)
print( val," in s.values", val in s.values)

val = 1
print( val," in l", val in l)
print( val," val in s", val in s)
print( val," in s.values", val in s.values)
```
#### Problem description
The fact that "in" operating on a Series checks the index and not the values is so unintuitive that I would call that a bug!  (Only some hair left after long session to track this behavior down.)  
Mostly venting here.


#### Expected Output
'in' should look at the values, like the equivalent list function.

#### Output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.19.1
nose: 1.3.7
pip: 9.0.1
setuptools: 20.3
Cython: 0.23.4
numpy: 1.11.1
scipy: 0.18.1
statsmodels: 0.6.1
xarray: None
IPython: None
sphinx: 1.3.1
patsy: 0.4.0
dateutil: 2.5.1
pytz: 2016.2
blosc: None
bottleneck: 1.0.0
tables: None
numexpr: 2.6.1
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.7.2
bs4: 4.4.1
html5lib: None
httplib2: 0.10.3
apiclient: 1.6.2
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.39.0
pandas_datareader: None

**Comment by TomAugspurger** [comment]
Looks like you figured it out. Did you see [this](http://pandas-docs.github.io/pandas-docs-travis/dsintro.html#series-is-dict-like) section in the docs? Anything about that that's unclear? We could call it out in the text and show `(val == s).any()`.

Series is list-like (more `ndarray`-like), but also dict-like since it has labels, so there's an design choice to make. Perhaps I'm just used to it, but I think `in` checking for keys makes more sense.

**Comment by lengross** [comment]
Hi Tom,

Thanks for quick response and insight.

I didn't even think to look at the docs for this, is was obvious (sic) what it should do.

I use a lot more lists than dictionaries so I got caught in wrong assumptions.

 

--Len
