### ISSUE TITLE
Google stock quotes break on some instances

### ISSUE THREAD

**Issue by kender99** [pandas-dev/pandas#16601]
#### Code Sample, a copy-pastable example if possible

```python
 import pandas as pd
 import pandas_datareader.data as web

# The following line retrieves the correct quote for the symbol GOOG, MSFT and others
quote  = web.get_quote_google(['GOOG'])   

#the following code breaks with AMZN  - note that it is now before market opening times in case this #has some relevance
 # error si ValueError: could not convert string to float: '1,006.73'
quote  = web.get_quote_google(['AMZN'])   

```
#### Problem description

The expected behaviour would be to retrieve the correct stock price for any given symbol. Especially if they are on the same stock exchange.
Some values seem to crash it.

#### Expected Output

Expected output would be a dataframe with index "quote"
and columns  'change_pct', 'last', 'time']

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.0.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.20.1
pytest: None
pip: 9.0.1
setuptools: 28.8.0
Cython: None
numpy: 1.12.1
scipy: None
xarray: None
IPython: 6.1.0
sphinx: None
patsy: None
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: 0.4.0

</details>

#### stacktrace``

<details>
ValueError                                Traceback (most recent call last)
<ipython-input-41-9a647e2e819f> in <module>()
----> 1 quote = web.get_quote_google(['AMZN'])

c:\websites\trader\venv\lib\site-packages\pandas_datareader\data.py in get_quote_google(*args, **kwargs)
     54 
     55 def get_quote_google(*args, **kwargs):
---> 56     return GoogleQuotesReader(*args, **kwargs).read()
     57 
     58 

c:\websites\trader\venv\lib\site-packages\pandas_datareader\base.py in read(self)
     67     def read(self):
     68         """ read data """
---> 69         return self._read_one_data(self.url, self.params)
     70 
     71     def _read_one_data(self, url, params):

c:\websites\trader\venv\lib\site-packages\pandas_datareader\base.py in _read_one_data(self, url, params)
     77         else:
     78             raise NotImplementedError(self._format)
---> 79         return self._read_lines(out)
     80 
     81     def _read_url_as_StringIO(self, url, params=None):

c:\websites\trader\venv\lib\site-packages\pandas_datareader\google\quotes.py in _read_lines(self, out)
     31         return pd.DataFrame([[float(x['cp']), float(x['l']),
     32                               np.datetime64(parse(x['lt']).isoformat())]
---> 33                              for x in result], columns=['change_pct',
     34                                                         'last', 'time'],
     35                             index=[x['t'] for x in result])

c:\websites\trader\venv\lib\site-packages\pandas_datareader\google\quotes.py in <listcomp>(.0)
     31         return pd.DataFrame([[float(x['cp']), float(x['l']),
     32                               np.datetime64(parse(x['lt']).isoformat())]
---> 33                              for x in result], columns=['change_pct',
     34                                                         'last', 'time'],
     35                             index=[x['t'] for x in result])

ValueError: could not convert string to float: '1,006.73'
</details>

**Comment by TomAugspurger** [comment]
Could you refile this on the pandas-datareader repo: https://github.com/pydata/pandas-datareader/issues Thanks.

**Comment by kender99** [comment]
Thanks. Seems someone else already posted it and it's been worked on
