### ISSUE TITLE
COMPAT: broken pickle compat from 0.19.2 -> 0.20.2 for UTC tz's

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#16608]
```
In [1]: pd.__version__
Out[1]: '0.19.2'

In [3]: df = pd.DataFrame({'A': [1, 2, 3]}, index=pd.date_range('20130101', periods=3, tz='UTC'))

In [4]: df.to_pickle('v0.19.2.pkl')
```

broken in 0.20.1/2
```
In [2]: pd.read_pickle('../v0.19.2.pkl')
IndexError: tuple index out of range
```

works fine for tz-aware but non-UTC (e.g. US/Eastern is fine).

**Comment by jreback** [comment]
@jorisvandenbossche @TomAugspurger any objection to doing a 0.20.3 in a few weeks?

**Comment by jorisvandenbossche** [comment]
No objection. I would just start tagging stuff as 0.20.3 and make a 0.20.3 whatsnew file. If we in the end decide that we don't find it worth to release (which probably will not be the case), we can easily move those things to 0.21 (it's just moving the whatsnew entries).

**Comment by TomAugspurger** [comment]
Fine by me as well.
