### ISSUE TITLE
CategoricalIndex.equals incorrectly considers category order when unordered

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#16603]
```python
>>> import pandas as pd
>>> pd.CategoricalIndex(['a', 'b'], categories=['a', 'b']).equals(
...     pd.CategoricalIndex(['a', 'b'], categories=['b', 'a']))
False
```

I fixed this for regular Categoricals in https://github.com/pandas-dev/pandas/pull/16339, but that didn't affect CategoricalIndex.equals. Do we want `.equals` to ignore order when `ordered=False` on both (I think we do)?

Discovered during my CategoricalDtype refactor, which does fix it so that order is ignored when `order=False`.

**Comment by jreback** [comment]
yes that sounds right

**Comment by naure** [comment]
Joining is broken because of this. This randomly broke a real world script depending on input data. Real headache to troubleshoot!

Test case:

```
# Same categories but in different order
Xi = pd.Categorical(["A"], categories=["A", "B"])
Yi = pd.Categorical(["B"], categories=["B", "A"])

x = pd.DataFrame(1, columns=["x"], index=Xi)
assert "B" not in x.index
y = pd.DataFrame(2, columns=["y"], index=Yi)
assert "B" in y.index

xy = x.join(y, how="inner")

print(x)
print(y)
print("Incorrect join:")
print(xy)

# It used the codes instead of the labels
assert x.index.codes == y.index.codes == xy.index.codes == [0]

assert len(xy) == 0, "Should be empty"  # Broken
assert "B" not in xy.index              # Broken
assert "B" not in xy                    # Actually passes somehow
```

Output:

```
   x
A  1

   y
B  2

Incorrect join:
   x  y
B  1  2

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-690-c66e71d6d8ba> in <module>()
     18 assert x.index.codes == y.index.codes == xy.index.codes == [0]
     19 
---> 20 assert len(xy) == 0, "Should be empty"  # Broken
     21 assert "B" not in xy.index              # Broken
     22 assert "B" not in xy                    # Actually passes somehow

AssertionError: Should be empty
```

**Comment by TomAugspurger** [comment]
@naure do you have time to submit a PR fixing this? I haven't had a chance,
and won't for a little while yet.

**Comment by naure** [comment]
I can have a look, where to start?

**Comment by TomAugspurger** [comment]
Thanks. CategoricalIndex is defined at https://github.com/pandas-dev/pandas/blob/master/pandas/core/indexes/category.py. It inherits the `union` / `intersection` methods from `Index`, defined in `indexes/base.py`.

I apparently started a branch for this, https://github.com/pandas-dev/pandas/compare/master...TomAugspurger:categorical-index-set-ops. I can't recall what was broken, but I suspect it was the set-ops issues with duplicates in https://github.com/pandas-dev/pandas/issues/13432

The basic idea in that branch was to override the set ops methods for `CategoricalIndex` with versions that do the regular set-ops *on the codes*. And then we construct a new CategoricalIndex based on the codes. Feel free to pick that up, or start fresh and ping if you have issues.

**Comment by naure** [comment]
No I think this is actually a regression in equality testing of Categorical, independently of the effort you mentioned. [Commit](https://github.com/pandas-dev/pandas/commit/e57f1894b55ecec3687a4484e119124d32ff942b?diff=split#diff-d295fd3c83b52dcaabdf13701ead1a41L2001).

Here is a monkey-patch for anyone who needs it safely working regardless of version.
This restores the behaviour of 0.20.1 regarding equality of Categorical and CategoricalIndex.
concat() & co will return regular Index and Series if categories are different in any way.

```
import pandas as pd

def Categorical_is_dtype_equal(self, other):
    """
    Returns True if categoricals are the same dtype
      same categories, and same ordered

    Parameters
    ----------
    other : Categorical

    Returns
    -------
    are_equal : boolean
    """

    try:
        return (self.categories.equals(other.categories) and
                self.ordered == other.ordered)
    except (AttributeError, TypeError):
        return False

pd.core.categorical.Categorical.is_dtype_equal = Categorical_is_dtype_equal
```

Test:
```
# Same categories but in different order
Xi = pd.Categorical(["A"], categories=["A", "B"])
Yi = pd.Categorical(["B"], categories=["B", "A"])
assert not Xi.categories.equals(Yi.categories)

x = pd.DataFrame(1, columns=["x"], index=Xi)
y = pd.DataFrame(2, columns=["y"], index=Yi)
assert not x.index.equals(y.index)

xy = x.join(y, how="inner")
assert len(xy) == 0, "Inner join should be empty"
```

@TomAugspurger Would like this as a PR?

**Comment by TomAugspurger** [comment]
> No I think this is actually a regression in equality testing of Categorical, independently of the effort you mentioned.

Why do you say that?

> It's not clear whether it should ultimately be equal or not, but if it does, that breaks a number of operations.

What is "it" in this case that's being compared?

That equality you linked to is on the CategoricalDtype, whose equality semantics are a bit strange especially around empty Categoricals.

**Comment by TomAugspurger** [comment]
Apologies for my slowness, I was looking at `CategoricalIndex.equals`, not `Categorical.equals`.

So, as you say, Categorical.equals should be defined as:

1. The dtypes are equal (categories match and ordering of categories is unimportant when both are unorderd)
2. The values are equal

The issue with the current definition is that it assumes dtype equality implies that codes match, which isn't always true. So I'd propose something like:

```python
if self.is_dtype_equal(other):
    if self.categories.equals(other.categories):
        # the fast case for codes aligning
        np.array_equal(self._codes, other._codes)
    else:
        # unorded categories with different order
        codes2 = _recode_for_categories(Yi.codes, Yi.categories, Xi.categories)
        return np.array_equal(self._codes, codes2)
return False
```

*then* we should be OK.  I'll submit that as a PR later today, unless you beat me to it :)
