### ISSUE TITLE
consolidate the duplicate definitions of NA values in code and docs (refactoring, cleaning)

### ISSUE THREAD

**Issue by OlegShteynbuk** [pandas-dev/pandas#16606]
pull request for the code  -  https://github.com/pandas-dev/pandas/pull/16589#pullrequestreview-41919702

**Comment by OlegShteynbuk** [comment]
docs - the file doc/source/io.rst repeats the same NA values in  in two places; keeping them in sync with the code might require an extra step of generating this file from a template file with placeholders.

**Comment by OlegShteynbuk** [comment]
if currently  docs consolidation is not realistic can split docs consolidation into a separate issue

**Comment by gfyoung** [comment]
@OlegShteynbuk : What you could do instead is reference the NA values in the first location when you get to the second location (and include a link to the location within the doc).

**Comment by OlegShteynbuk** [comment]
repetition of the same NA values in docs was removed; the first location has reference to the second location as suggested by gfyoung.

the na values should be consistent now.

**Comment by jorisvandenbossche** [comment]
This was closed by https://github.com/pandas-dev/pandas/pull/16589 I think
