### ISSUE TITLE
Docs are incpmplete for concat

### ISSUE THREAD

**Issue by ODemidenko** [pandas-dev/pandas#16622]
There is an issue with concat:
I expect it not to  add rows from a second df in case there are such indexes in a first one.
But this doesn't work for me. After a lot of search I found that this is because I have duplicate values in indexes in both df.
It would be great to warn about such a behavior in standard function documentation.

That is how I found that it is not a bug, but rather a feature:
https://stackoverflow.com/questions/24089922/merge-multiple-dataframes-with-non-unique-indices/24091063#24091063

Frankly speaking, I would prefer if there was an option to leave only "unique" indexes and in case they are present in first df - skip them all together during the concat

**Comment by chris-b1** [comment]
The first example in the docstring shows exactly this case, but certainly would welcome any improvements to make this clearer.  `DataFrame.combine_first` basically does what you want, although not on a collection.

```
In [46]: pd.concat?
<omitted>

Examples
--------
Combine two ``Series``.
>>> s1 = pd.Series(['a', 'b'])
>>> s2 = pd.Series(['c', 'd'])
>>> pd.concat([s1, s2])
0    a
1    b
0    c
1    d
dtype: object
```

**Comment by ODemidenko** [comment]
@chris-b1
Regarding concat I had wrong anticipation, should have read docstring there. Thanks!
Regarding combine_first - it doesn't work in case there are duplicates in the index in initial DFs (and that is the tricky thing with my DFs).

So, seems like the only way to union dataframes with duplicate values:
filter one of them to take indexes only missed in the other: ~index.isin(second_index), and then concat.
That is a clear way, although leaves confusion that no single standard operation can do it. But probably it is better to have simplified standard api, I don't know. Just was confused with the issue.

thank you for your time!
