### ISSUE TITLE
Import pandas with graphics disabled

### ISSUE THREAD

**Issue by dabliss** [pandas-dev/pandas#16628]
I'm running an analysis using the Sun Grid Engine.

However, in my code I import pandas, which causes this error to be raised:

`import pandas as pd`

> : cannot connect to X server :3026.0

*This is new.  Until recently, I was able to import and use pandas within the SGE.*

What I've gathered from some Googling and conversations with my sys admin is that pandas is trying to load graphics, and the SGE is not allowing this.

I don't want to do any plotting with pandas. I just want to use its DataFrame features.

Is there a way to load pandas with graphics disabled, so the SGE doesn't hiccup in this way?

**UPDATE:** This error is not raised when I use pandas version 0.18.  So it was introduced by one of the more recent versions.  (The version I tried that did raise the error was 0.20.)

Note, this question has been posted to stackoverflow: https://stackoverflow.com/questions/44424058/import-pandas-with-graphics-disabled

**Comment by jorisvandenbossche** [comment]
Can you check with the latest version? (0.20.2, bugfix released few days ago) Because I think this was related to the clipboard imports, which should have been fixed in the meantime.

**Comment by jorisvandenbossche** [comment]
The related issues I meant are https://github.com/pandas-dev/pandas/issues/16383 and https://github.com/pandas-dev/pandas/issues/16288, so this should indeed be fixed in 0.20.2.

Closing, but please check that updating solves the issue, and report back it it doesn't.
