### ISSUE TITLE
The query returns Empty array when i use Where in query string

### ISSUE THREAD

**Issue by mushtaque87** [pandas-dev/pandas#16636]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
aadhaar_data = pd.read_csv('/Users/philips/Downloads/aadhaar_data.csv')
aadhaar_data.rename(columns = lambda x: x.replace(' ', '_').lower(), inplace=True) #rename column
  query = "SELECT pin_code from aadhaar_data where state = 'Gujarat' "
    aadhar_queried_data = sqldf(query.lower(), locals())
    print(aadhar_queried_data)

```
#### Problem description

When i user normal query it returns a dataframe , But when i put an condition in a query like Where it returns an empty array 

Empty DataFrame
Columns: [pin_code]
Index: []

Data set     # https://s3.amazonaws.com/content.udacity-data.com/courses/ud359/aadhaar_data.csv

#### Output of ``pd.show_versions()``

<details>
# Paste the output here pd.show_versions() here

</details>

**Comment by jorisvandenbossche** [comment]
This seems like a `sqldf` issue, can you report it over there? I think https://github.com/yhat/pandasql/
