### ISSUE TITLE
CLN: private impl of OrderedDefaultDict can be removed

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#16668]
https://github.com/pandas-dev/pandas/blob/master/pandas/compat/__init__.py#L376

I think this was leftover from 2.6 compat.

**Comment by rosygupta** [comment]
@jreback So the private methods need to be made public? Is that all is required?

**Comment by jreback** [comment]
no i think it can just be removed

**Comment by TomAugspurger** [comment]
And replaced with an import `from collections import OrderedDict`.
