### ISSUE TITLE
Datetime and Timedelta operation throw TypeError

### ISSUE THREAD

**Issue by penghou620** [pandas-dev/pandas#16660]
#### Code Sample, a copy-pastable example if possible

```python
s = Series(date_range('2012-1-1', periods=3, freq='D'))

td = Series([ Timedelta(days=i) for i in range(3) ])

df = DataFrame(dict(A = s, B = td))

df['C'] = df['A'] + df['B']
```
#### Problem description

The last line throw an error `TypeError: data type "datetime" not understood`. The pandas version is 0.19.2.

 I tried the same code with pandas 0.20.2, it runs correctly.

#### Expected Output
               A          B                 C
    0 2012-01-01     0 days        2012-01-01
    1 2012-01-02     1 days        2012-01-03
    2 2012-01-03     2 days        2012-01-05

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Darwin
OS-release: 16.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.19.2
nose: None
pip: 9.0.1
setuptools: 27.2.0
Cython: None
numpy: 1.13.0
scipy: None
statsmodels: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
boto: None
pandas_datareader: None
</details>

**Comment by jreback** [comment]
since this runs in 0.20.2 this is not an issue. we don't backport across major versions. you are welcome to upgrade.
