### ISSUE TITLE
DOC: new mini-section on specifying formats on datetime parsing

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#16669]
We have a single note on how to use ``format=`` kw in ``timeseries.rst``: https://github.com/pandas-dev/pandas/blob/master/doc/source/timeseries.rst#L178

I think let's make this a min-sub-section and provide links (or *maybe* just replicate) [python strptime docs](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior) and show how to use the codings for specifying formats in some examples.

**Comment by ManrajGrover** [comment]
@jreback I can take this one up as a start to contribute to pandas.
