### ISSUE TITLE
Non-Disjoint GroupBy

### ISSUE THREAD

**Issue by gerigk** [pandas-dev/pandas#1667]
I think I once read something similar here or on the mailing list but I did not find it with these keywords.

Let's say I want to have aggregates over a groups that fulfill  any of a given set of conditions (e.g., a stock whose volatility is higher than x or the return lower than y  and I am interested in how many stocks I hold with vol > x and how many with return< y ).
so my df is something like

stock  vol return #of stocks

A       40  -10      10
B   20      10        1000

etc.
and I want the result 

condition     # of stocks
vol > x            n
return < y        m

where we have of course that m + n may be greater than  df[#of stocks].sum().

Now, my stocks are grouped into different portfolios so I may have a portfolio column and this functionality should allow to combine this kind of group by with a "normal " group by.  So 

portfolio  condition  # of stocks
P             vol > x        m
P             return < y    n
Q            vol >x          o
Q            return < y     p

Is this something that has been thought about?

**Comment by toobaz** [comment]
Extremely (memory-)inefficient, but I guess it could work as follows:

``` python
In [3]: def condgroupby(df, conditions):
   ...:     if isinstance(conditions, (str, list)):
   ...:         conditions = df[conditions]
   ...:     chunks = []
   ...:     for condition in conditions:
   ...:         chunk = df[conditions[condition]]
   ...:         chunk['_cat'] = condition
   ...:         chunks.append(chunk)
   ...:     tempdf = pd.concat(chunks)
   ...:     return tempdf.groupby('_cat')
   ...: 
```
To be used as follows:
``` python
In [4]: test = pd.DataFrame(np.random.randint(0, 5, (10,10)), columns=pd.MultiIndex.from_product([['data'], list(range(10))]))

In [5]: test['cond', 'first'] = test['data', 1] > test['data', 4]

In [6]: test['cond', 'second'] = test['data', 3] <= test['data', 8]

In [7]: gb = condgroupby(test, 'cond')
/usr/bin/ipython3:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  echo "Please install the python$VERSION package." >&2

In [8]: gb.mean()
Out[8]: 
            data                                                              \
               0         1         2         3         4         5         6   
_cat                                                                           
first   2.500000  2.000000  1.250000  3.500000  1.000000  2.500000  2.500000   
second  2.166667  1.333333  1.833333  1.333333  2.666667  1.833333  2.833333   

                                      cond         
               7     8         9     first second  
_cat                                               
first   2.250000  1.25  2.500000  1.000000   0.25  
second  2.333333  2.00  1.833333  0.166667   1.00  
```
... or as follows:

``` python
In [9]: test = pd.DataFrame(np.random.randint(0, 5, (10,10) ))

In [10]: test['first'] = test[1] > test[4]

In [11]: test['second'] = test[3] <= test[8]

In [12]: gb = condgroupby(test, ['first', 'second'])
/usr/bin/ipython3:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  echo "Please install the python$VERSION package." >&2

In [13]: gb.mean()
Out[13]: 
               0         1         2         3         4    5         6    7  \
_cat                                                                           
first   2.400000  3.400000  1.600000  1.800000  1.000000  2.2  3.000000  1.8   
second  2.428571  3.285714  1.714286  1.285714  1.714286  2.0  2.285714  2.0   

          8         9     first  second  
_cat                                     
first   2.6  3.600000  1.000000     0.8  
second  2.0  3.285714  0.571429     1.0  

```

(The warnings could be suppressed because they don't signal any real danger - ``chunk`` objects are disposable)

**Comment by kokes** [comment]
This sounds like you're looking for window functions, these are not supported in pandas. Well, `.transform` comes pretty close, but it's not quite there. The thing with aggregate functions (be it groupby.agg or transform) is that they work on columns, not the whole dataframe (or other columns), but there are workarounds.

I can think of at least two ways to achieve your goal.

We can index the original dataframe from within aggregations

```
df = pd.DataFrame({'stock': ['A', 'B'], 'vol': [40, 20], 'return': [-10, 10], 'num': [10, 1000]})                                                               
df.groupby('stock').agg({'vol': lambda g: df.loc[g.index].pipe(lambda x: x.loc[x.vol>30]).num.sum()}) 
```

Or we can aggregate based on our conditions separately and then join these together, using an outer join.

```
da = df.loc[df.vol > 30].groupby('stock').num.sum()                                                                                                        
db = df.loc[df['return'] > 0].groupby('stock').num.sum()                                                                                                   
```

Be careful, you'll need to reindex with df.stock.unique(), because some stocks may not satisfy either of the conditions and would be dropped from the joined dataframe. This limitation does not apply to the first solution.

**Comment by WillAyd** [comment]
Closing as a usage question; typically better served using SO for these types of questions
