### ISSUE TITLE
PERF: Unnecessary hash table with RangeIndex

### ISSUE THREAD

**Issue by chris-b1** [pandas-dev/pandas#16685]
Example
```python
def log_memory():
    import os
    import gc
    import psutil
    for i in range(3):
        gc.collect(i)
    process = psutil.Process(os.getpid())
    mem_usage = process.memory_info().rss / float(2 ** 20)
    print("[Memory usage] {:12.1f} MB".format(
        mem_usage
    ))

In [20]: df = pd.DataFrame({'a': np.arange(1000000)})

In [23]: log_memory()
[Memory usage]        132.4 MB

In [24]: df.loc[5, :]
Out[24]: 
a    5
Name: 5, dtype: int32

In [25]: log_memory()
[Memory usage]        172.2 MB
```

Rather than materializing the hash table, should directly convert labels into positions.  Low priority in my opinion, atypical to be using `loc` with a `RangeIndex`.

`pandas 0.20.2`

**Comment by jreback** [comment]
hmm ,this should not be creating a hash table at all (though it would if it morphed to an int64index)

**Comment by chris-b1** [comment]
The `_engine` for `RangeIndex` still points at the `Int64Index` one, so a hash table will be created if something calls `self._engine`.    So either need to make a simplified `RangeIndexEngine` or override the indexing methods.

https://github.com/pandas-dev/pandas/blob/2e24a8f8886a1481af8324d44224cddb2ee1b53c/pandas/core/indexes/range.py#L43

**Comment by jreback** [comment]
I think that ``_engine`` is purely for compat on some methods. might be easiest/best to create a pretty dummy RI Engine in cython.

**Comment by chris-b1** [comment]
> RangeIndex is not much more memory-efficient as a Int64Index (its big selling point I thought?) once the engine is created.

This is true, but I think it would be relatively rare for the engine to populated when a `RangeIndex` is being used - typically it is when someone doesn't care about the index at all, so would likely be using `iloc` if any indexing at all.
