### ISSUE TITLE
AttributeError: xcell.style.number_format.format_code = self.datetime_format

### ISSUE THREAD

**Issue by trvaughn** [pandas-dev/pandas#16694]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
def _createClientReportWithDivTemplate(df, destPath, templatePath):
    writer = pd.ExcelWriter(templatePath, engine= 'openpyxl')
    
    df.to_excel(writer, sheet_name = 'Accrual Breaks', \
                header= False, index= False, \
                startrow= 4, startcol= 0)
```
#### Problem description
Despite this code not throwing an exception for other engines ("xlwt"), this is failing for openpyxl and throwing the below exception:
 File "C:\Python27\lib\site-packages\pandas\io\excel.py", line 536, in write_cells
    xcell.style.number_format.format_code = self.datetime_format
AttributeError: 'str' object has no attribute 'format_code'

It looks like write_cells believes xcell is a str object.  After looking at the source code for write_cells, I am uncertain if the code should be looking for a number_format.format_code on a string object.  Seems like it does quality check for the format, so uncertain how it gets to this stage except for the fact that it's checking cell.val for a date format rather than xcell.

Not certain if relevant, but within the Excel file there is a merged cell above the starting point that is General, but implicitly treated as text, whereas the starting point is treated as a Date in the format *03/14/2001

#### Expected Output
Expected to write the below information into excel file (this correctly writes using to_csv; inserting as xlsx as csv documents are not support)

Dataframe data
[DailyDividendAccrualRec_06132017.xlsx](https://github.com/pandas-dev/pandas/files/1073246/DailyDividendAccrualRec_06132017.xlsx)

Excel output file
[DivAccrualClientReport_Template.xlsx](https://github.com/pandas-dev/pandas/files/1073250/DivAccrualClientReport_Template.xlsx)

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.6.final.0
python-bits: 32
OS: Windows
OS-release: 2008ServerR2
machine: AMD64
processor: Intel64 Family 6 Model 45 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.13.1
Cython: None
numpy: 1.8.1
scipy: 0.14.0
statsmodels: 0.5.0
IPython: 2.1.0
sphinx: 1.2.2
patsy: 0.2.1
scikits.timeseries: None
dateutil: 2.2
pytz: 2014.3
bottleneck: 0.8.0
tables: 3.1.1
numexpr: 2.4
matplotlib: 1.3.1
openpyxl: 2.3.0-b2
xlrd: 0.9.2
xlwt: 0.7.5
xlsxwriter: None
sqlalchemy: 0.9.4
lxml: 3.3.5
bs4: 4.3.2
html5lib: 0.999
bq: None
apiclient: None
None
</details>

**Comment by chris-b1** [comment]
Can you please make your example runnable?  Mock something up for `df` and reference the actual excel templates (can use the github urls)

**Comment by WillAyd** [comment]
Closing as this is not reproducible
