### ISSUE TITLE
CI: slowdown

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#16730]
something is happening on travis about 8 days ago. our builds took between 2 & 2.5 hrs.

2.5 hrs: https://travis-ci.org/pandas-dev/pandas/builds/241842849

now taking 3.5 hrs +, with very little changes in code.
3.5 hrs: https://travis-ci.org/pandas-dev/pandas/builds/241844274

It *seems* that the tests themselves are taking 2x longer.

any ideas?

**Comment by jorisvandenbossche** [comment]
The doc build is also slower (from on average 25 to 35 min, see my comment https://github.com/pandas-dev/pandas/pull/16704#issuecomment-308716181), I looked a bit into it, but didn't see a potential commit that could cause such a slowdown.

Maybe travis just got slower?

**Comment by jreback** [comment]
I reverted all the way to that commit: https://travis-ci.org/jreback/pandas/builds/244878059

(there is additional build time as not using cache on personal builds, so subtract 4 min from each build). but it could be that we are not getting real multiprocessing of xdist.

**Comment by TomAugspurger** [comment]
FYI: https://github.com/dask/dask/pull/2485 Bokeh and dask got some nice speedups by using the `trusty` image.
