### ISSUE TITLE
I am getting error installing Pandas on AWS Lightsail with Amazon Linux image.

### ISSUE THREAD

**Issue by prabhatM** [pandas-dev/pandas#16735]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

```
#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

#### Output of ``pd.show_versions()``

<details>
# Paste the output here pd.show_versions() here

</details>

**Comment by jreback** [comment]
well some actual details would be helpful.

**Comment by prabhatM** [comment]
Kindly ignore the earlier message. I was trying to install Pandas on AWS Lightsail with 512MB memory and it failed to install. With 1GB memory it installed fine. I will try again with 512MB memory with SWAP. Let's see if it installs or not.
Thank you for the response.

Regards

Prabhat

**Comment by SantoshGuptaML** [comment]
Were you trying to install on jupyter notebook? I tried and it disconnected, but worked when installing directly in the terminal.
