### ISSUE TITLE
Regression: .agg with dictionary return value in 0.20 does not work as intended

### ISSUE THREAD

**Issue by FlorianWilhelm** [pandas-dev/pandas#16741]
When I run the code below in 0.20.2

```python
import numpy as np
import pandas as pd

pd.show_versions()

np.random.seed(42)
df = pd.DataFrame({'uid': np.random.randint(0, 5, 20), 'color': np.random.randint(0, 5, 20)})
df.groupby('uid')['color'].agg(lambda x: x.value_counts().to_dict())
```
I got:
```
uid
0    <built-in method values of dict object at 0x10...
1    <built-in method values of dict object at 0x10...
2    <built-in method values of dict object at 0x11...
3    <built-in method values of dict object at 0x11...
4    <built-in method values of dict object at 0x11...
Name: color, dtype: object
```
Doing exactly the same in 0.19.2 I got as expected:
```
uid
0                {0: 1}
1    {0: 1, 2: 1, 4: 1}
2    {1: 1, 2: 1, 3: 3}
3          {1: 2, 2: 3}
4    {0: 2, 3: 2, 4: 2}
Name: color, dtype: object
```

This might be related to the closed issue #8735 where the same problem occurred once using `.apply` and dictionary return values. But in my case `.apply` works as expected only `.agg` misbehaves since version 0.20.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Darwin
OS-release: 16.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8
LOCALE: de_DE.UTF-8

pandas: 0.20.2
pytest: 2.8.5
pip: 9.0.1
setuptools: 32.1.2
Cython: 0.24.1
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 4.1.2
sphinx: 1.3.5
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.3.0
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: 2.6.2 (dt dec pq3 ext lo64)
jinja2: 2.8
s3fs: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
I suppose. This maybe non trivial to fix. Why would you do this anyhow? Storing non-scalar objects *inside* a pandas object is non-performant / generally has limited support.

```
In [7]: df.groupby('uid')['color'].value_counts()
Out[7]: 
uid  color
0    0        1
1    0        1
     2        1
     4        1
2    3        3
     1        1
     2        1
3    2        3
     1        2
4    0        2
     3        2
     4        2
Name: color, dtype: int64
```

**Comment by FlorianWilhelm** [comment]
@jreback Thanks for your fast reply. It seems that storing dictionaries in Pandas is allowed and internally I guess it will use some kind of pointer/reference to an outside object just like in the case of strings which makes it non-performant. Anyways, it used to work in version 0.19 and even in 0.20 it works for `apply` which makes it currently at least inconsistent. Also the step above is the final step of a UDAF (as explained below) and therefore there will be no future non-performant operations on these columns.

My actual use-case it that I am using Pandas inside a PySpark UDAF `mapPartitions` and in the end I want to construct a PySpark `Row` where each column is a `MapType`. It's easy to generate that object when you pass a dictionary to `Row` where the keys are the column names and the values are dictionaries which PySpark will convert automatically to `MapType` then. If I have in each Pandas column dictionaries as values as described above I can just call the `Row` constructor on each element of `df.to_dict('records')`.

**Comment by FlorianWilhelm** [comment]
@jreback How would you do it then in a more efficient way? Thanks for any hints.

**Comment by jreback** [comment]
use the code I gave above.

**Comment by FlorianWilhelm** [comment]
@jreback I started working on PR #16752

**Comment by FlorianWilhelm** [comment]
@jreback I fixed the bug and it is actually only half a line of code and a unit test. Don't you think that this could also be integrated in the next bugfix/minor release?
