### ISSUE TITLE
API: provide a to_enum method for Categorical dtypes?

### ISSUE THREAD

**Issue by chris-b1** [pandas-dev/pandas#16749]
xref #16015

This _might_ be something nice to provide.  Specific usecase I was thinking of is interacting with `numba` - it understands enums in nopython mode, so it would be a way to work with Categoricals there.

Partially working implementation below, doing something like [`namedtuple`](https://github.com/python/cpython/blob/3.6/Lib/collections/__init__.py#L303) with exec

```python
def categorical_to_enum(categorical, name):
    cats = categorical.categories

    template = """from enum import IntEnum
class {name}(IntEnum):
    NA = -1
{fields}
"""
    assert all(isinstance(x, str) and x.isidentifier()
               for x in cats)

    fields = '\n'.join('    {cat}={code}'.format(cat=cat, code=i)
                       for i, cat in enumerate(cats))
    ns = {}
    exec(template.format(name=name, fields=fields), ns)
    return ns[name]

# example usage
In [81]: c = pd.Categorical(['a', 'b', 'a', 'c'])

In [82]: MyEnum = categorical_to_enum(c, 'MyEnum')

In [83]: MyEnum.c
Out[83]: <MyEnum.c: 2>
```

**Comment by jreback** [comment]
I think you can just do this: https://stackoverflow.com/questions/33690064/dynamically-create-an-enum-with-custom-values-in-python

nice idea. mayb ``.to_enum()``

**Comment by mroeschke** [comment]
Thanks for the suggestion but it appears there hasn't been much engagement in this feature in years so closing
