### ISSUE TITLE
Documentation error in Visualization

### ISSUE THREAD

**Issue by Jaiimmortal** [pandas-dev/pandas#16754]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
In [85]: from pandas.plotting import andrews_curves

In [86]: data = pd.read_csv('data/iris.data')

In [87]: plt.figure()
Out[87]: <matplotlib.figure.Figure at 0x7f45a9d158d0>

In [88]: andrews_curves(data, 'Name')
Out[88]: <matplotlib.axes._subplots.AxesSubplot at 0x7f45a9d26128>
```
Taken from [Andrews Curves - Visualization, Documentation of pandas](https://pandas-docs.github.io/pandas-docs-travis/visualization.html#andrews-curves)

#### Problem description

Okay, here it goes I'm working on beautiful representations of iris.data came across the documentation but for some reason `from pandas.plotting import andrews_curves` didn't work but `from pandas.tools.plotting import andrews_curves` there is nothing wrong with the codebase just a documentation fix.

#### Expected Output

Plotting of the graph is the expected output according to documentation - [Image](https://pandas-docs.github.io/pandas-docs-travis/_images/andrews_curves.png)
Instead what I'm getting - [Error Image](https://ibb.co/bXLyL5) , sorry for hosting image on 3rd party site 
Fix : [Fix](https://ibb.co/fQMSDQ)

#### Output of ``pd.show_versions()``

<details>
# Paste the output here pd.show_versions() here

Some stupid reason I can't copy paste from cmd, so image again, sorry
[Image of Pandas version](https://ibb.co/nswutQ)

</details>

Thank You.

**Comment by TomAugspurger** [comment]
This was moved around in pandas 0.20, and it looks like you're running 0.19.2; http://pandas.pydata.org/pandas-docs/version/0.19.2/visualization.html#andrews-curves shows how to do it for that version, or you could update your version of pandas and use the new location.
