### ISSUE TITLE
Pandas style render set_uuid sets Multiple ids

### ISSUE THREAD

**Issue by JoshuaC3** [pandas-dev/pandas#16780]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame({'a': [1, 3, 5, 6], 'b': [2, 4, 12, 21]})
df.style.render(uuid='test')
## or same with df.style.set_uuid('test').render()

<style  type="text/css" >\n</style>  \n<table id="T_test" > \n<thead>    <tr> \n        <th class="blank level0" ></th> \n        <th class="col_heading level0 col0" >a</th> \n        <th class="col_heading level0 col1" >b</th> \n    </tr></thead> \n<tbody>    <tr> \n        <th id="T_test" class="row_heading level0 row0" >0</th> \n        <td id="T_testrow0_col0" class="data row0 col0" >1</td> \n        <td id="T_testrow0_col1" class="data row0 col1" >2</td> \n    </tr>    <tr> \n        <th id="T_test" class="row_heading level0 row1" >1</th> \n        <td id="T_testrow1_col0" class="data row1 col0" >3</td> \n        <td id="T_testrow1_col1" class="data row1 col1" >4</td> \n    </tr>    <tr> \n        <th id="T_test" class="row_heading level0 row2" >2</th> \n        <td id="T_testrow2_col0" class="data row2 col0" >5</td> \n        <td id="T_testrow2_col1" class="data row2 col1" >12</td> \n    </tr>    <tr> \n        <th id="T_test" class="row_heading level0 row3" >3</th> \n        <td id="T_testrow3_col0" class="data row3 col0" >6</td> \n        <td id="T_testrow3_col1" class="data row3 col1" >21</td> \n    </tr></tbody> \n</table> 

```
#### Problem description

I am told that a css id should be unique and therefore, when `<table id="T_test" >` and `<th id="T_test"...>` in the above HTML output have the same ids, this breaks my css and causes the settings on my ids to be ignored.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 3.16.0-4-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.20.2
pytest: 2.9.2
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.24.1
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 5.1.0
sphinx: 1.4.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.0
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.3
lxml: 3.6.4
bs4: 4.5.1
html5lib: 0.999999999
sqlalchemy: 1.0.13
pymysql: 0.7.9.None
psycopg2: None
jinja2: 2.8
s3fs: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
Thanks for the report. For reference the problem IDs are generated at

- https://github.com/pandas-dev/pandas/blob/65a0e642e1270791e6586c967758b362b865b6a8/pandas/io/formats/templates/html.tpl#L28
- https://github.com/pandas-dev/pandas/blob/65a0e642e1270791e6586c967758b362b865b6a8/pandas/io/formats/templates/html.tpl#L59

The second ones are supposed to be getting a `c.id` attribute, but apparently that isn't defined.

**Comment by JoshuaC3** [comment]
I see this is tagged as Novice and Effort Low. I would be happy to give this a try but I am not sure of the process to do this. Any tips/links would be great.

**Comment by jreback** [comment]
start here: http://pandas.pydata.org/pandas-docs/stable/contributing.html

create a test (e.g. the above), and see it fail. provide a fix, see your test pass.

**Comment by TomAugspurger** [comment]
I think the bug is somewhere around https://github.com/pandas-dev/pandas/blob/664348c440ccb4dab3d4c420d6aaee7c688c9b0e/pandas/io/formats/style.py#L235

**Comment by JoshuaC3** [comment]
I have setup my dev environment and written a the test,

```
def test_unique_ids():
    df = pd.DataFrame({'a': [1, 3, 5, 6], 'b': [2, 4, 12, 21]})
    test_str = df.style.render(uuid='test')
    a = re.findall('.*id=("T_test *\w*").*', test_str)
    assert len(set(a)) == len(a)
```

This successfully breaks when running pytest from my local pandas dir.

Since then I struggled to build and reinstall pandas with debugging breakpoints and `print()`. I assume this is the wrong way to go about it. Is there some further guidance on how to do this? Whatever I am doing has been hit and miss this far.

@TomAugspurger The problem areas were very helpful to get me started. It seems to me that [L284](https://github.com/pandas-dev/pandas/blob/664348c440ccb4dab3d4c420d6aaee7c688c9b0e/pandas/io/formats/style.py#L284) should have the an `id` attribute like [L308](https://github.com/pandas-dev/pandas/blob/664348c440ccb4dab3d4c420d6aaee7c688c9b0e/pandas/io/formats/style.py#L308). This is why the `<th id='T_test'>` I believe. Will continue this tomorrow.

**Comment by ri938** [comment]
Submitted pull request for fix for this issue.
