### ISSUE TITLE
PERF: Some asv tests take a long time to setup

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#16803]
I hacked asv to log the total execution time, including setup, for each benchmark. Some of these are parametrized over several cases, so they may not actually be slow. `time` is in seconds. 

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>time</th>
      <th>file</th>
      <th>klass</th>
      <th>method</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>68</th>
      <td>00:03:11.379267</td>
      <td>frame_ctor</td>
      <td>FrameConstructorDTIndexFromOffsets</td>
      <td>time_frame_ctor</td>
    </tr>
    <tr>
      <th>394</th>
      <td>00:01:01.671905</td>
      <td>inference</td>
      <td>to_numeric_downcast</td>
      <td>time_downcast</td>
    </tr>
    <tr>
      <th>199</th>
      <td>00:00:46.330012</td>
      <td>groupby</td>
      <td>GroupBySuite</td>
      <td>time_describe</td>
    </tr>
    <tr>
      <th>559</th>
      <td>00:00:24.698904</td>
      <td>replace</td>
      <td>replace_large_dict</td>
      <td>time_replace_large_dict</td>
    </tr>
    <tr>
      <th>204</th>
      <td>00:00:24.212386</td>
      <td>groupby</td>
      <td>GroupBySuite</td>
      <td>time_mad</td>
    </tr>
    <tr>
      <th>210</th>
      <td>00:00:22.481497</td>
      <td>groupby</td>
      <td>GroupBySuite</td>
      <td>time_pct_change</td>
    </tr>
    <tr>
      <th>215</th>
      <td>00:00:18.909368</td>
      <td>groupby</td>
      <td>GroupBySuite</td>
      <td>time_skew</td>
    </tr>
    <tr>
      <th>200</th>
      <td>00:00:18.732072</td>
      <td>groupby</td>
      <td>GroupBySuite</td>
      <td>time_diff</td>
    </tr>
    <tr>
      <th>212</th>
      <td>00:00:18.317290</td>
      <td>groupby</td>
      <td>GroupBySuite</td>
      <td>time_rank</td>
    </tr>
    <tr>
      <th>219</th>
      <td>00:00:16.845357</td>
      <td>groupby</td>
      <td>GroupBySuite</td>
      <td>time_unique</td>
    </tr>
  </tbody>
</table>

Ideally we could optimize the setup time on these as well. We could maybe modify the benchmark to do less work / run faster, but I'd like to avoid that if possible.

Link to the full CSV: https://gist.github.com/9d80aa45750224d7453863f2f754160d

**Comment by jorisvandenbossche** [comment]
One of the things I already have thought about before is that we probably can do less in the `setup` ? 
I mean, is it needed to create the DataFrames in a setup (which gets repeated a lot), or would it be sufficient to just create them once in the file? (as long as the benchmarks don't modify it)

Eg https://github.com/pandas-dev/pandas/blob/master/asv_bench/benchmarks/groupby.py#L399 we could do the actual creation of the frame outside setup, and in the setup only pick the right one based on the parameters.

**Comment by TomAugspurger** [comment]
There's also the setup_cache method, which executes once

**Comment by jreback** [comment]
is this actually a big deal?

**Comment by jbrockmendel** [comment]
Is there a measure of the relative importance of these benchmarks?  i.e. if I find improvements in subset A and slowdowns in subset B, when can this count as a win?

**Comment by jorisvandenbossche** [comment]
@jbrockmendel there is no 'measure' for that, apart from common sense. 

But note that this is issue is not about that, it is about the fact that some tests take a long time to run (not because of pandas being too slow, but because of the set-up of the test)

**Comment by jbrockmendel** [comment]
For some of these, e.g. reindex.Reindexing, there is a lot of unnecessary setup being done.  `df2` is constructed for every call of all three benchmarks, but is only used in one.  Same for `s1` and `s2`.  It isn't obvious how much mileage can be gained by trimming these down though.

**Comment by jbrockmendel** [comment]
@TomAugspurger  can you post the hack you used to measure setup time?  I'm poking at this instead of doing real work.

**Comment by TomAugspurger** [comment]
Happy to encourage productive procrastination :)

This is the diff in my local copy (which is based on a pretty old commit now)

```git
diff --git a/asv/benchmarks.py b/asv/benchmarks.py
index 60442b9..b3b96ba 100644
--- a/asv/benchmarks.py
+++ b/asv/benchmarks.py
@@ -89,6 +89,8 @@ def run_benchmark(benchmark, root, env, show_stderr=False,
 
         - `errcode`: Error return code.
     """
+    import time
+    t0 = time.time()
     name = benchmark['name']
     result = {'stderr': '', 'profile': None, 'errcode': 0}
     bench_results = []
@@ -230,6 +232,10 @@ def run_benchmark(benchmark, root, env, show_stderr=False,
             with log.indent():
                 log.error(result['stderr'])
 
+        t1 = time.time()
+        line = '{},{}\n'.format(name, t1 - t0)
+        with open("log.csv", "a") as f:
+            f.write(line)
         return result
 
 
@@ -535,7 +541,6 @@ class Benchmarks(dict):
               and be a byte string containing the cProfile data.
         """
         log.info("Benchmarking {0}".format(env.name))
-
         with log.indent():
             benchmarks = sorted(list(six.iteritems(self)))
 
```

**Comment by jbrockmendel** [comment]
Thanks, worked like a charm.  What _didn't_ work was my attempt to short-cut `setup` calls by defining attributes at the class level.

**Comment by jorisvandenbossche** [comment]
> Thanks, worked like a charm. What didn't work was my attempt to short-cut setup calls by defining attributes at the class level.

I think using 'global' data works, so defined on the module level (as long as it is only used for benchmarks that don't modify data). In some cases (if the module is not too long, something generic can be reused) that can be used I think.
