### ISSUE TITLE
Petition to set default value of pd.options.display.max_columns to something more reasonable

### ISSUE THREAD

**Issue by adamwlev** [pandas-dev/pandas#16800]
Hi, I would like to voice my frustration with the fact that the default setting for the maximum amount of columns to display of a DataFrame is 20. I think I understand the need to have this setting - to protect against printing an unreasonable amount of information on the screen in the case of a DataFrame having an extremely large amount of columns. However, I have now googled 'pandas set options max columns' about 100 times and even if I could bring myself to memorize this nested attribute location ('pd.options.display.max_columns'), it is still tiresome to have to write it every time after 'import pandas as pd'.

I am sure there are many people who agree with me on this one. Is there anyway to have a poll amongst users (does github have this functionality? through twitter maybe?) for what this default value should be? I would vote for 100 personally.

Thanks,
Adam Levin

**Comment by chris-b1** [comment]
Are you using `ipython` (either terminal or notebook)? I put these kind of things in a startup script.  There also was some discussion a few years ago about a "pandasrc" https://github.com/pandas-dev/pandas/issues/4907

**Comment by adamwlev** [comment]
Ok, @chris-b1 that makes a lot of sense. I just set up my config file ;)
