### ISSUE TITLE
BUG: Index.get_indexer_not_unique inconsistent return types vs get_indexer

### ISSUE THREAD

**Issue by ri938** [pandas-dev/pandas#16819]
See https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Index.get_indexer_non_unique.html where the return value of Index.get_indexer_non_unique indexer is stated to be ndarray whereas actually this is converted into a Index before it is returned 

indexer, missing = self._engine.get_indexer_non_unique(tgt_values)
return Index(indexer), missing

**Comment by jreback** [comment]
this is techincally wrong, it should return a platform ndarray as the indexer, see #16820 , similar to ``.get_indexer()``

**Comment by jreback** [comment]
actually repurposing this issue to fix the bug.

https://github.com/pandas-dev/pandas/pull/16820#issuecomment-312869214
need some tests in tests/indexes/test_base.py which exercise this comparison for all indexers

e.g. something like this will expose the bug

```
def get_indexer_consistency(self):

       for name, index in self.indices.items():
             expected = index.get_indexer(index[0:2])
             result, _ = index.get_indexer_non_unique(index[0:2])
             tm.assert_numpy_array_equal(result, expected)
```

**Comment by jreback** [comment]
@ri938 love to have a PR!

**Comment by ri938** [comment]
So you would like for conversion to index in "return Index(indexer)", from get_indexer_non_unique to be removed so this returns the correct type? (and tests)

**Comment by jreback** [comment]
yes I think that would work (see what breaks)

**Comment by ri938** [comment]
Created PR #16826
