### ISSUE TITLE
Crash of Jupyter Notebook on v0.20.2

### ISSUE THREAD

**Issue by ethydrane** [pandas-dev/pandas#16816]
Hello,

I updated my pandas from 0.19.2 to 0.20.2. Then my script I am running for a long time kept crashing on Jupyter, without any bug shown in the console.
I downgraded pandas, and it worked again.
Did someone have the same issue with pandas, associated with jupyter?

**Comment by jreback** [comment]
this is not a reproducible bug report 
you would need to provide a minimal example
