### ISSUE TITLE
Pandas multiplying columns each other faster. 

### ISSUE THREAD

**Issue by mrcavam** [pandas-dev/pandas#16828]
Hello I was using this 

df = df_base.copy() ...: 
for pair in combinations(df.columns, 3): ...
new_col = '*'.join(pair) ...: 
df[new_col] = df[pair[0]] * df[pair[1]]*df[pair[2]]

I was trying to multiply dataframe of 204 columns which is supposed to generate 1394204 columns. But in 2 hours It only generated 300420. Can someone tell how I make it faster?

**Comment by TomAugspurger** [comment]
Usage questions are typically answered quicker on stackoverflow. There's a lot of people watching that tag.

FYI, you probably could use NumPy for this, and you'll want to avoid iteration.

**Comment by mrcavam** [comment]
If I avoid iteration, how i will multiply 3 column each at a time.
