### ISSUE TITLE
plotting in pandas is not picking the list of colors passed, it only gets the first value

### ISSUE THREAD

**Issue by eyadsibai** [pandas-dev/pandas#16822]
#### Code Sample, a copy-pastable example if possible

```python
>>> df = pd.DataFrame({"A": range(4), "color": ['red', 'blue', 'blue', 'red']})
>>> ax = df.plot.bar(y='A', color=df['color'])
>>> [p.get_facecolor() for p in ax.patches]
[(1.0, 0.0, 0.0, 1.0),
 (1.0, 0.0, 0.0, 1.0),
 (1.0, 0.0, 0.0, 1.0),
 (1.0, 0.0, 0.0, 1.0)]
```
#### Problem description

It plots correctly but it does not pick the right color per bar. it only pick the color of the first value in the list.
it was working perfectly in pandas 0.19.2

#### Expected Output
 the plot should contain a different color as the list is being passed. Similar to matplotlib behavior and the old pandas version

#### Output of ``pd.show_versions()``

<details> 

pandas: 0.20.2
pytest: None
pip: 9.0.1
setuptools: 36.0.1
Cython: None
numpy: 1.12.1
scipy: 0.19.1
xarray: None
IPython: 5.4.1
sphinx: None
patsy: None
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.0.2
openpyxl: None
xlrd: 1.0.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.9999999
sqlalchemy: None
pymysql: None
psycopg2: 2.7.1 (dt dec pq3 ext lo64)
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by halflings** [comment]
I left a comment on #14757 which seems to be the culprit.

**Comment by TomAugspurger** [comment]
#14757 looks unrelated, that was for `.style`, not `.plot`. PRs welcome if you want to take a look.

**Comment by TomAugspurger** [comment]
The problem seems to be in `_get_colors`. I think that `BarPlot` should define a `_get_colors` that does something like

```
def _get_colors(self, num_colors=None, color_kwds='color'):
    color = self.kwds.get('color')
    if color is None:
        return super()._get_colors(self, num_colors=num_colors, color_kwds=color_kwds)
    else:
        num_colors = len(self.data)  # maybe? may not work for some cases
        return _get_standard_colors(color=kwds.get('color'), num_colors=num_colors)
````

will need tests and stuff too.

**Comment by TomAugspurger** [comment]
This is in https://github.com/pandas-dev/pandas/blob/9e55af2552664267ce27c7fc6c932acb0651c259/pandas/plotting/_style.py

**Comment by bcolsen** [comment]
@TomAugspurger This a regression bug that can crash matplotlib(see below). I think this might be a bigger deal than "next major release"

If you give a color as an RGB or RGBA tuple the dataframe plot command only forwards the first number and this(a single float) isn't a valid color so matplotlib crashes and plots a blank(broken really) graph.

```
user@user-comp:~$ ipython --pylab
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.
Using matplotlib backend: Qt5Agg

In [1]: import pandas as pd

In [2]: pd.__version__
Out[2]: '0.20.2'

In [3]: df = pd.DataFrame({"A": range(10)})

In [4]: df.plot(y='A', color=(0.3,0.4,0.4,1))
Out[4]: <matplotlib.axes._subplots.AxesSubplot at 0x7f90dbdea160>

In [5]: Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/matplotlib/colors.pa
    rgba = _colors_full_map.cache[c, alpha]
KeyError: (0.3, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/matplotlib/backendsg
    FigureCanvasAgg.draw(self)
  File "/home/user/anaconda3/lib/python3.6/site-packages/matplotlib/backendsw
    self.figure.draw(self.renderer)
  File "/home/user/anaconda3/lib/python3.6/site-packages/matplotlib/artist.pr
    draw(artist, renderer, *args, **kwargs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/matplotlib/figure.pw
    renderer, self, dsu, self.suppressComposite)
  File "/home/user/anaconda3/lib/python3.6/site-packages/matplotlib/image.pys
    a.draw(renderer)
  File "/home/user/anaconda3/lib/python3.6/site-packages/matplotlib/artist.pr
    draw(artist, renderer, *args, **kwargs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_baw
    mimage._draw_list_compositing_images(renderer, self, dsu)
  File "/home/user/anaconda3/lib/python3.6/site-packages/matplotlib/image.pys
    a.draw(renderer)
  File "/home/user/anaconda3/lib/python3.6/site-packages/matplotlib/artist.pr
    draw(artist, renderer, *args, **kwargs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/matplotlib/lines.pyw
    ln_color_rgba = self._get_rgba_ln_color()
  File "/home/user/anaconda3/lib/python3.6/site-packages/matplotlib/lines.pyr
    return mcolors.to_rgba(self._color, self._alpha)
  File "/home/user/anaconda3/lib/python3.6/site-packages/matplotlib/colors.pa
    rgba = _to_rgba_no_colorcycle(c, alpha)
  File "/home/user/anaconda3/lib/python3.6/site-packages/matplotlib/colors.pe
    raise ValueError("Invalid RGBA argument: {!r}".format(orig_c))
ValueError: Invalid RGBA argument: 0.3
```
works fine on 0.19
```
user@user-comp:~$ ipython --pylab
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.
Using matplotlib backend: Qt5Agg

In [1]: import pandas as pd

In [2]: pd.__version__
Out[2]: '0.19.2'

In [3]: df = pd.DataFrame({"A": range(10)})

In [4]: df.plot(y='A', color=(0.3,0.4,0.4))
Out[4]: <matplotlib.axes._subplots.AxesSubplot at 0x7fa95e159710>

In [5]: 
```

**Comment by jreback** [comment]
> @TomAugspurger This a regression bug that can crash matplotlib(see below). I think this might be a bigger deal than "next major release"

@bcolsen certainly a patch is welcome. We have 1900 issues, how does one prioritize?

**Comment by TomAugspurger** [comment]
The next minor release is tomorrow, so you may not have time to get a PR in.

**Comment by bcolsen** [comment]
@jreback Sorry for the bug triage suggestion...I clearly have no idea what your release scheduled is like.

I can't get a PR in by tomorrow, but will have a look at it. This is what i have so far.

Initially this line, seems to be the problem:
```
colors = list(color) if is_list_like(color) else color
```
https://github.com/pandas-dev/pandas/blob/9e55af2552664267ce27c7fc6c932acb0651c259/pandas/plotting/_style.py#L100 

but this code is in plotting.py in 0.19 and it works fine.

The difference is in 0.19 `_get_standard_colors` gets the color tuple wrapped as a list already so line 100 does:
```
[(0.3, 0.4, 0.4)] ->  [(0.3, 0.4, 0.4)]
```
in 0.20 `_get_standard_colors` gets just the tuple. So it does this.
```
(0.3, 0.4, 0.4) ->  [0.3, 0.4, 0.4]
```

**Comment by ryanshrott** [comment]
Any update?

**Comment by bcolsen** [comment]
I have a work around for people being affected by this:

Plot with color in an extra list:
```
df.plot(y='A', color=[(0.3,0.4,0.4,1)])
```
also fixes bar:
```
>>> df = pd.DataFrame({"A": range(4), "color": ['red', 'blue', 'blue', 'red']})
>>> ax = df.plot.bar(y='A', color=[df['color']])
>>> [p.get_facecolor() for p in ax.patches]
Out[35]: 
[(1.0, 0.0, 0.0, 1.0),
 (0.0, 0.0, 1.0, 1.0),
 (0.0, 0.0, 1.0, 1.0),
 (1.0, 0.0, 0.0, 1.0)]
```

**Comment by adesorme** [comment]
I'm still facing this issue...

**Comment by senjed** [comment]
I am still facing the same issue. Why is this closed?

**Comment by TomAugspurger** [comment]
https://github.com/pandas-dev/pandas/pull/17360 fixed this. It's possible that there was a regression, or you're getting the same error message from a different case. Either way, @senjed / @adesorme can you open a new issue with an example demonstrating the problem?

**Comment by RT-Tap** [comment]
Is it possible this issue crawled its way back in?  Im trying to use this on a bar plot and it only picks up the first color no matter what I do.  Any ideas/suggestions?

**Comment by Zartexo** [comment]
This problem still exists

**Comment by MarcoGorelli** [comment]
The example from the original posts looks fine in the latest pandas (1.4.2):

![Screenshot 2022-05-13 at 12 55 34](https://user-images.githubusercontent.com/33491632/168278172-48762907-6381-4f30-ac9c-a88f7de08371.png)

If anyone's still facing the issue, could you please open a new issue with a minimal reproducible example? Thanks

**Comment by alexdanilowicz** [comment]
In case this helps anyone, I was having this issue with `pandas==1.5.0` (and 1.4.2) because I was not passing `y` argument. 

For example: 

No `y=` :X: 

```python
        c = ['red', blue', 'green']
	ax = df.plot.barh(color=c)
	print([p.get_facecolor() for p in ax.patches])
```

vs 

With y= ✅ 
```python
        c = ['red', blue', 'green']
         # where A is a column name in your df
	ax = df.plot.barh(y="A", color=c)
	print([p.get_facecolor() for p in ax.patches])
```
