### ISSUE TITLE
BUG: number of keys for grouping equals axis length causing incorrect grouping

### ISSUE THREAD

**Issue by P-Tillmann** [pandas-dev/pandas#16843]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame([['foo','two', 0.371118],['foo','two', 0.765483]],columns=['first','second','one'])
df.set_index(['first','second'], inplace=True)

df.groupby(['first','second']).size()

df.reset_index().groupby(['first','second']).size()
```
#### Problem description
The output of the first groupby size gives me an output of:
```
first     1
second    1
```
#### Expected Output

rather then the expected output i get after i reset the index:
```
first  second
foo    two       2
```
The problem appears when the level of multiindex is equal the number of rows of the grouped dataframe (tested for 2 and 3 rows = levels). If the number of rows is smaller or bigger then the levels of the multiindex the problem does not occur.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 64
OS: Darwin
OS-release: 15.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.20.1
pytest: 3.0.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 5.3.0
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.3.0
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.7
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.3
bs4: 4.6.0
html5lib: 0.999
sqlalchemy: 1.1.9
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
so you have a non-unique MultiIndex, which generally isn't as well tested; not to mention is somewhat non-performant and not very useful. That said this looks like a bug.

If you'd dig in an see if you can find the issue would be great.

**Comment by P-Tillmann** [comment]
I'm not sure that i understood your last comment correctly. But i did some digging  and found that the bug is not ot related to the non unique multi-index, it rather happens with all dataframes with an equal amount of rows as levels of multi-index.
Digging into the code i found that for special cases in groupby.py in line 2640 the keys for the grouping are casted to a tuplesafe array (not really sure what that is) and put into a list as the sole element. Because of that the keys are not enumerated and in_axis is set to false in line 2695 (which should be true i guess).

Removing the outer list in line 2640 fixes the here raised problem but i don't know if it is there for a good reason.

Hope that helps.

**Comment by jreback** [comment]
well if u can send a PR that adds your example as a test and make your change and see what fails would be great

**Comment by P-Tillmann** [comment]
I think i found a solution which doesn't crash the groupby tests, but i stil have to run the full test suit and integrate my own test. Hope that i can make a PR tomorrow or the day after.

Thanks for the great work you're putting into pandas!

**Comment by P-Tillmann** [comment]
I hope i did everything right with my first pull request. I changed the title of the issue since it is not related to a non unique multiindex.
