### ISSUE TITLE
Series.plot misaligned for sparse DatetimeIndex

### ISSUE THREAD

**Issue by RobinFiveWords** [pandas-dev/pandas#16847]
#### Code Sample, a copy-pastable example if possible

```python
import os.path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

version = pd.__version__.replace('.', '-')

image_series = 'plot_series_{}.png'.format(version)
image_dataframe = 'plot_dataframe_{}.png'.format(version)

assert not os.path.exists(image_series), 'already ran this version'
assert not os.path.exists(image_dataframe), 'already ran this version'

idx = pd.date_range(start='2014-01-01', end='2016-12-31', freq='D')
np.random.seed(0)
ser = pd.Series(np.random.rand(idx.size) - 0.5, index=idx).cumsum()
rs = ser.resample('A').mean()
af = ser.asfreq('A')
df = pd.DataFrame({'ser': ser, 'rs': rs, 'af': af},
                  columns=['ser', 'rs', 'af'])

fig, ax = plt.subplots(1, 1)
ser.plot(ax=ax, style='o')
rs.plot(ax=ax, style='o')
af.plot(ax=ax, style='o')
fig.savefig(image_series)

fig, ax = plt.subplots(1, 1)
df.plot(ax=ax, marker='o')
fig.savefig(image_dataframe)
```
#### Problem description

When the date in a `DatetimeIndex` is December 31, and it is the only date for the year, `DataFrame.plot` positions the value at the end of the year (yellow = mean, green = last):
![plot_dataframe_0-20-2](https://user-images.githubusercontent.com/13019694/27940667-919cd34e-6291-11e7-971e-d1aaa927f8f3.png)
This is also how `matplotlib.pyplot.plot` works (not shown) when called directly with `x=s.index, y=s`.

`Series.plot`, on the other hand, positions the value at the start of the year:
![plot_series_0-20-2](https://user-images.githubusercontent.com/13019694/27940668-919ecfd2-6291-11e7-98fe-75a0e75c360f.png)

I went down the rabbit hole a bit but couldn't figure out where in the code the index is being converted for `Series` but not for `DataFrame`.

This appears to be consistent across 0.20.2, 0.20.1, and 0.19.2 (I stopped there). Windows and OS X.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Darwin
OS-release: 15.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.20.2
pytest: 2.9.2
pip: 9.0.1
setuptools: 23.0.0
Cython: 0.24
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 5.1.0
sphinx: 1.4.1
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: 1.2.1
tables: 3.3.0
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.2
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.8
s3fs: None
pandas_gbq: None
pandas_datareader: 0.2.1
None
</details>

**Comment by gfyoung** [comment]
cc @TomAugspurger

**Comment by RobinFiveWords** [comment]
I think I understand what's happening here. A "date" in a DatetimeIndex with an annual frequency is not really that date but the whole period covered by the frequency. The datapoint is plotted at the start of that period. Implementing it any other way seems impractical. So pandas is behaving as desired.

In the process of assembling the dataframe from the multiple series, all series are upsampled. When I do that manually, by chaining `.resample('D').asfreq()` when assigning `rs` and `af`, the resulting plots are the same (and what is desired/expected) even when plotted by series. And this same upscaling occurs implicitly when passing the index directly to matplotlib, because matplotlib doesn't deal with pandas objects and will interpret the values from the index as dates rather than periods.

Lesson: convert multiple Series to the same DatetimeIndex frequency before plotting on the same axis. Or put them all in a DataFrame and it will be done for you.
