### ISSUE TITLE
Is it possible to have sub-headers in Pandas?

### ISSUE THREAD

**Issue by sashml** [pandas-dev/pandas#16854]
Can someone please review and give answer if that is feature or not?
https://stackoverflow.com/questions/44973087/is-it-possible-to-create-dataframe-with-sub-headers-in-pandas

**Comment by TomAugspurger** [comment]
Looks like you've received an answer.

FYI, stackoverflow is the correct place for usage questions. No need to cross post to the issue tracker (for bugs reports, feature requests, etc.)

**Comment by preyash2047** [comment]
Here is the documentation for that" https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sub.html
