### ISSUE TITLE
FutureWarning Error

### ISSUE THREAD

**Issue by sbasumal** [pandas-dev/pandas#16866]
*# Your code here*
from tsfresh import extract_features
extracted_features = extract_features(timeseries, column_id="id", column_sort="time")

*Problem description*
I just installed the latest version of pandas and statmodels. When i run my code, i get this error:

"FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead."

 'e__agg_linear_trend__f_agg_"max"__chunk_len_50__attr_"stderr"'
 'e__agg_linear_trend__f_agg_"min"__chunk_len_50__attr_"stderr"'
 'e__agg_linear_trend__f_agg_"mean"__chunk_len_50__attr_"stderr"'
 'e__agg_linear_trend__f_agg_"var"__chunk_len_50__attr_"stderr"'] did not have any finite values. Filling with zeros.

Expected Output

Relevant features extraction

**Comment by jreback** [comment]
and?

**Comment by sbasumal** [comment]
I just updated my post. Sorry for not being clear before

**Comment by jreback** [comment]
where are you using pandas here?

it looks like some other module is using pandas under the hood - address your issue there
