### ISSUE TITLE
ENH: DataFrame.insert should allow for negative loc parameter

### ISSUE THREAD

**Issue by gandhis1** [pandas-dev/pandas#16872]
The insert method, which adds a new column, should accept a value such as -2 which would insert a new column before the second-to-last-column.

I am guessing this is probably a duplicate, but I wasn't able to locate another Issue with this feature request.

**Comment by jreback** [comment]
sure would take this an enhancement request!

**Comment by mroeschke** [comment]
Seems like there hasn't been much interest in this feature over the years so closing
