### ISSUE TITLE
BUG: coercing of bools in groupby transform

### ISSUE THREAD

**Issue by jongmmm** [pandas-dev/pandas#16875]
#### Code Sample
```python
df = pd.DataFrame({'A': [1.1,2.2], 'B':[1,2]})
df.groupby('B').A.transform(lambda x: True)
```
This returns
```
Out[3]:
0    1.0
1    1.0
Name: A, dtype: float64
```
#### Problem 
`groupby.transform` returns numeric values, not __bool__ . This is inconsistent
because `DataFrame.transform` behaves differently:

```python
In [5]: df.A.transform(lambda x:True)
Out[5]:
0    True
1    True
Name: A, dtype: bool
```
#### Additional

But please note that if the original data type is `int`, it works properly:
```python
In [9]: df = pd.DataFrame({'A': [1,2], 'B':[1,2]})
   ...: df.groupby('B').A.transform(lambda x: True)
   ...:
Out[9]:
0    True
1    True
Name: A, dtype: bool
```

**Comment by chris-b1** [comment]
Looks essentially the same as #10972, which was closed by #15430, but apparently didn't capture this case.  `apply` does do the right inference here:

```
In [2]: df.groupby('B').A.apply(lambda x: True)
Out[2]:
B
1    True
2    True
Name: A, dtype: bool
```
