### ISSUE TITLE
to_pickle() got an unexpected keyword argument 'protocol'

### ISSUE THREAD

**Issue by xenu256** [pandas-dev/pandas#16886]
#### Code Sample, a copy-pastable example if possible

```python
df.to_pickle(path=filename", compression='infer', protocol=2)
```
#### Problem description

````text
to_pickle() got an unexpected keyword argument 'protocol'
```

#### Expected Output

None.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-43-Microsoft
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.20.2
pytest: None
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.13.1
scipy: 0.19.1
xarray: None
IPython: None
sphinx: None
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: None
tables: 3.3.0
numexpr: 2.6.2
feather: 0.4.0
matplotlib: 2.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: 2.7.1 (dt dec pq3 ext lo64)
jinja2: None
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by jreback** [comment]
show the pandas version in the same session in which u r running

you are likely picking up an older version

**Comment by xenu256** [comment]
It is same session and same conda environment, updated with 0.20.2 now.

**Comment by xenu256** [comment]
OK, found where's problem. It definitely doesn't exist if installed via git (0.20.3), so probably conda's whl is broken.

**Comment by jreback** [comment]
whl don't exist for conda - that is a pip installation


closing as an installation issue u less it's repo on a new environment

**Comment by manangupta12** [comment]
> OK, found where's problem. It definitely doesn't exist if installed via git (0.20.3), so probably conda's whl is broken.

I am facing the same issue , can you please elaborate the solution to this. It will be a great help !
