### ISSUE TITLE
SUB-character in a csv causes read_csv() with C-Engine to detect EOF

### ISSUE THREAD

**Issue by Khris777** [pandas-dev/pandas#16893]
#### Problem description

If there is a SUB-character in a string in a csv, `read_csv()` with the standard C-engine returns
>ParserError: Error tokenizing data. C error: EOF inside string starting at line 0

The Python-engine can read the file fine.

It seems I can't put example data with a SUB-character here, so I pasted an example line here instead:
https://pastebin.com/x6QPY4Hf
Just paste the line into a csv and try to read it with `read_csv()`.

I don't know if this behaviour is expected or not since this character is indeed used as EOF in certain cases, however I see little sense in having a SUB character interpreted as EOF in the middle of a csv file.

<details>
commit: None

python: 3.6.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64

pandas: 0.20.2
</details>

**Comment by TomAugspurger** [comment]
Seems to work for me, could you try updating your version of pandas?

```
In [8]: pd.read_csv("foo.csv").columns
Out[8]: Index(['12456', 'XY', 'Pedfg', '234'], dtype='object')

In [9]: text = open('foo.csv').read()

In [10]: text
Out[10]: '12456,XY,"\x1aPedfg",234\n'
```

**Comment by Khris777** [comment]
Looks like 0.20.3 isn't on conda yet.

**Comment by TomAugspurger** [comment]
Ok, I'll check on that. It is available on conda-forge with `conda install
-c conda-forge pandas`

**Comment by gfyoung** [comment]
@Khris777 : Let us know if updating works for you.  In any case, a test in the code-base will be needed to confirm this.

**Comment by Khris777** [comment]
Can confirm that updating solves the problem.

**Comment by gfyoung** [comment]
@Khris777 : slow down there :smile: !  Even though the issue is resolved, we would prefer to add a test to ensure that this issue doesn't pop up.  Care to add your example code in a PR?

**Comment by Khris777** [comment]
PR = Pull Request?
I have never done something like this before here, honestly I don't know exactly what you are asking me to do here. :confused:

**Comment by gfyoung** [comment]
@Khris777 : yes, PR = pull request

Essentially, I am asking you to add your raw pastebin string as a test to the `read_csv` function, something like this format would work:

~~~python
def test_...(self):
    data = "12456,XY,"Pedfg",234"
    result = self.read_csv(StringIO(data))
    expected = <construct-expected-DataFrame-here>
    tm.assert_frame_equal(df, result)
~~~

The following <a href="https://github.com/pandas-dev/pandas/tree/9d13227345882daaa90f03078c09a9b44a18ce72/pandas/tests/io/parser">directory</a> has a lot of good examples that you can follow (you would likely add your test under `common.py`).  Here is also the <a href="https://pandas.pydata.org/pandas-docs/stable/contributing.html">link</a> containing general info about contributing to `pandas`.

If you would like to attempt contributing the code yourself, we'll be happy to help you out.  If you are unable to do so at this time, we can take care of adding the test ourselves, but more contributors are always preferred 😄

**Comment by Khris777** [comment]
Thanks for adding the test. Since I'm only here on weekdays you were faster than me. :)
