### ISSUE TITLE
Indexing TimedeltaIndex with np.timedelta64

### ISSUE THREAD

**Issue by shoyer** [pandas-dev/pandas#16909]
On pandas 0.20.2, `TimedeltaIndex.get_loc()` worked on np.timedelta64, even though DataFrame.loc fails:
```
In [2]: df = pd.DataFrame({'x': range(3)}, pd.to_timedelta(range(3), unit='days'))

In [3]: df.loc[df.index[0].to_timedelta64()]
TypeError: cannot do index indexing on <class 'pandas.core.indexes.timedeltas.TimedeltaIndex'> with these indexers [0] of <class 'numpy.timedelta64'>

In [5]: df.index.get_loc(df.index[0].to_timedelta64())
Out[5]: 0
```
Now, both raise `TypeError`. (This is similar to the issue in #16896)

I think some xarray users are were likely relying on this (we use `get_loc()` directly), but I think supporting this could also be useful for pandas users.

**Comment by jdeschenes** [comment]
Question: Should `get_loc`  only work on 'scalar' values?

**Comment by jreback** [comment]
``.get_loc`` by-definition is *only* on scalar values. a string and/or a np.timedelta64 are scalars (e.g. not lists/arrays)

``.get_indexer`` works on list-likes

**Comment by jreback** [comment]
here you can simply pass scalars to ``Timedelta()`` and then index
