### ISSUE TITLE
Panel.mean numeric_only=True raises NotImplementedError

### ISSUE THREAD

**Issue by danodonovan** [pandas-dev/pandas#16903]
```python
p = pd.Panel(data=np.zeros((2, 3, 3)))
p.mean(numeric_only=True)

<snip>
</snip>
NotImplementedError: Panel.mean does not implement numeric_only.
```
From the documentation it seems that `pandas.Panel.mean` should implement a `numeric_only` parameter - but it seems to be missing when `numeric_only=True`.

<details>

> INSTALLED VERSIONS
> ------------------
> commit: None
> python: 3.6.1.final.0
> python-bits: 64
> OS: Linux
> OS-release: 4.4.0-83-generic
> machine: x86_64
> processor: x86_64
> byteorder: little
> LC_ALL: None
> LANG: en_GB.UTF-8
> LOCALE: en_GB.UTF-8
> pandas: 0.20.2
> pytest: 3.1.2
> pip: 9.0.1
> setuptools: 27.2.0
> Cython: None
> numpy: 1.13.0
> scipy: 0.19.0
> xarray: None
> IPython: 6.1.0
> sphinx: None
> patsy: None
> dateutil: 2.6.0
> pytz: 2017.2
> blosc: None
> bottleneck: None
> tables: 3.4.2
> numexpr: 2.6.2
> feather: None
> matplotlib: 2.0.2
> openpyxl: None
> xlrd: None
> xlwt: None
> xlsxwriter: None
> lxml: None
> bs4: None
> html5lib: None
> sqlalchemy: None
> pymysql: None
> psycopg2: None
> jinja2: None
> s3fs: None
> pandas_gbq: None
> pandas_datareader: None

</details>

**Comment by jreback** [comment]
yes it probably should, but Panel is deprecated so closing (though of course if you wanted to submit a PR to fix would prob accept).
