### ISSUE TITLE
ERR: missing stacklevel in to_dict UserWarning

### ISSUE THREAD

**Issue by chris-b1** [pandas-dev/pandas#16927]
#### Code Sample, a copy-pastable example if possible

```python
In [4]: df = pd.DataFrame([[1,2,3]], columns=['a', 'a', 'b'])

In [5]: df
Out[5]:
   a  a  b
0  1  2  3

In [6]: df.to_dict()
C:\<snip>\pandas\core\frame.py:891:
UserWarning: DataFrame columns are not unique, some columns will be omitted.
  "columns will be omitted.", UserWarning)
Out[6]: {'a': {0: 2}, 'b': {0: 3}}
```

#### Problem description

warning should specific stacklevel to warn at calling site, xref #9584

**Comment by gfyoung** [comment]
In the future, we'll probably have to go back and find any other hanging warnings like these.

**Comment by chris-b1** [comment]
Yep, probably some others, a sufficiently clever grep might be able to turn them up. (basically whenever we call `warn(...)` without a stacklevel passed.

**Comment by jreback** [comment]
a lot of these prob don't have the correct stack_level; note that on most ``assert_raises_warnings`` we are passing ``check_stacklevel=False`` (so its not checking). certainly these could/should be changed.

**Comment by gfyoung** [comment]
That's true, we probably would need to go back and comb through those a bit.

**Comment by imih** [comment]
Should the [`@deprecate`](https://github.com/pandas-dev/pandas/blob/master/pandas/util/_decorators.py#L9) decorator be used for this? 

Additionally, we might want to add a keyword `stacklevel` to it.

**Comment by TomAugspurger** [comment]
@imih no I don't think so. That's for when we change the name of a keyword argument.

**Comment by imih** [comment]
@TomAugspurger You're refering to  `@deprecate_kwarg`. `@deprecate` is something else. https://github.com/pandas-dev/pandas/blob/master/pandas/util/_decorators.py#L9 and it's not currently in use in `pandas-dev`.
