### ISSUE TITLE
DOC: SyntaxError in pd.read_msgpack examples

### ISSUE THREAD

**Issue by PengFLyu** [pandas-dev/pandas#16922]
`In [319]: for o in pd.read_msgpack('foo.msg',iterator=True):`
`   .....:     print o`
`   .....: `
`  File "<ipython-input-319-a0f40395739e>", line 2`
`    print o`
`              ^`
`SyntaxError: Missing parentheses in call to 'print'`

**Comment by chris-b1** [comment]
Thanks, recently switched our doc build to python 3, PR to fix welcome!

**Comment by stevemontana1980** [comment]
Hi,
this appears to have been fixed in master: #16862

**Comment by TomAugspurger** [comment]
Thanks @stevemontana1980 you're correct.
