### ISSUE TITLE
Regression in s.loc._getitem_iterable(...)

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#16920]
#### Code Sample, a copy-pastable example if possible

```python
In [2]: s = pd.Series(range(9), index=pd.MultiIndex.from_product([['A', 'B', 'C'], ['foo', 'bar', 'baz']],names=['one', 'two']))

In [3]: s.loc._getitem_iterable(['A', 'E'], 0)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-62e87e14f902> in <module>()
----> 1 s.loc._getitem_iterable(['A', 'E'])

/home/pietro/nobackup/repo/pandas/pandas/core/indexing.py in _getitem_iterable(self, key, axis)
   1095             # if it cannot handle; we only act on all found values
   1096             indexer, keyarr = labels._convert_listlike_indexer(
-> 1097                 key, kind=self.name)
   1098             if indexer is not None and (indexer != -1).all():
   1099                 return self.obj.take(indexer, axis=axis)

/home/pietro/nobackup/repo/pandas/pandas/core/indexes/multi.py in _convert_listlike_indexer(self, keyarr, kind)
   1760             mask = check == -1
   1761             if mask.any():
-> 1762                 raise KeyError('%s not in index' % keyarr[mask])
   1763 
   1764         return indexer, keyarr

KeyError: "['E'] not in index"
```
#### Problem description

(Unless/until we change our general approach to this - related discussion is in #15747,) indexing with a list containing at least one valid key should not raise an error. Indeed, before https://github.com/pandas-dev/pandas/commit/05d70f4e617a274813bdb02db69143b5554aa106 , 

```python
In [2]: s = pd.Series(range(9), index=pd.MultiIndex.from_product([['A', 'B', 'C'], ['foo', 'bar', 'baz']],names=['one', 'two']))

In [3]: s.loc._getitem_iterable(['A', 'E'])
Out[3]: 
one  two
A    foo    0
     bar    1
     baz    2
dtype: int64
```

#### Expected Output

See above. This had already been reported [here](https://github.com/pandas-dev/pandas/pull/15615#issuecomment-287826997), opening an independent issue for clarity, as suggested by @gfyoung .

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-3-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.21.0.dev+231.g03cec7563
pytest: 3.0.6
pip: 9.0.1
setuptools: None
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 5.1.0.dev
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.2
openpyxl: None
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.6
lxml: None
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: 0.2.1

</details>

**Comment by toobaz** [comment]
For reference: although I cannot currently think of any code exposing the bug using only public methods, this is what makes PR #15615 fail tests.

**Comment by gfyoung** [comment]
cc @jreback (that was your commit AFAICT)

**Comment by phofl** [comment]
This is now the expected behavior
