### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#16933]
just turned this on: https://github.com/OrkoHunter/pep8speaks

let's see how it works, and if it needs configuration.....

**Comment by gfyoung** [comment]
Yes, it will need configuration.  These comments <a href="https://github.com/pandas-dev/pandas/pull/16935#issuecomment-315490874">here</a> are indicative of that (e.g. bare `except`, while true is not checked by `flake8`)

**Comment by TomAugspurger** [comment]
Ignoring the same errors as flake8 + the bare except (which should be fixed) I have

<details>
pandas/__init__.py:27:30: E128 continuation line under-indented for visual indent
pandas/__init__.py:28:30: E128 continuation line under-indented for visual indent
pandas/__init__.py:81:80: E501 line too long (93 > 79 characters)
pandas/tslib.py:7:32: E128 continuation line under-indented for visual indent
pandas/compat/__init__.py:96:13: W503 line break before binary operator
pandas/compat/__init__.py:222:1: E305 expected 2 blank lines after class or function definition, found 1
pandas/compat/__init__.py:246:80: E501 line too long (90 > 79 characters)
pandas/compat/__init__.py:298:80: E501 line too long (90 > 79 characters)
pandas/compat/__init__.py:338:1: E305 expected 2 blank lines after class or function definition, found 1
pandas/core/groupby.py:3445:13: E741 ambiguous variable name 'l'
pandas/core/indexing.py:524:17: E741 ambiguous variable name 'l'
pandas/core/indexing.py:682:21: E741 ambiguous variable name 'l'
pandas/core/indexing.py:1640:9: E741 ambiguous variable name 'l'
pandas/core/indexing.py:1657:9: E741 ambiguous variable name 'l'
pandas/core/indexing.py:1871:9: E741 ambiguous variable name 'l'
pandas/core/internals.py:696:9: E741 ambiguous variable name 'l'
pandas/core/resample.py:1114:9: E741 ambiguous variable name 'l'
pandas/core/dtypes/cast.py:530:5: E741 ambiguous variable name 'l'
pandas/core/indexes/base.py:2920:13: E741 ambiguous variable name 'l'
pandas/core/indexes/datetimes.py:1174:9: E741 ambiguous variable name 'l'
pandas/core/indexes/interval.py:785:17: E741 ambiguous variable name 'l'
pandas/core/indexes/interval.py:788:17: E741 ambiguous variable name 'l'
pandas/core/indexes/interval.py:797:16: E741 ambiguous variable name 'l'
pandas/core/indexes/interval.py:804:18: E741 ambiguous variable name 'l'
pandas/core/indexes/multi.py:643:9: E741 ambiguous variable name 'l'
pandas/core/indexes/range.py:536:13: E741 ambiguous variable name 'l'
pandas/core/reshape/merge.py:1491:5: E741 ambiguous variable name 'l'
pandas/errors/__init__.py:14:1: E302 expected 2 blank lines, found 1
pandas/errors/__init__.py:20:1: E302 expected 2 blank lines, found 1
pandas/io/api.py:22:1: E302 expected 2 blank lines, found 1
pandas/io/packers.py:189:9: E741 ambiguous variable name 'l'
pandas/io/pytables.py:4076:9: E741 ambiguous variable name 'l'
pandas/io/msgpack/__init__.py:20:1: E305 expected 2 blank lines after class or function definition, found 1
pandas/plotting/__init__.py:9:80: E501 line too long (80 > 79 characters)
pandas/tests/test_algos.py:391:9: E741 ambiguous variable name 'l'
pandas/tests/test_categorical.py:1724:9: E741 ambiguous variable name 'l'
pandas/tests/test_categorical.py:1730:9: E741 ambiguous variable name 'l'
pandas/tests/test_categorical.py:1751:9: E741 ambiguous variable name 'l'
pandas/tests/test_categorical.py:1764:9: E741 ambiguous variable name 'l'
pandas/tests/test_categorical.py:1769:9: E741 ambiguous variable name 'l'
pandas/tests/test_multilevel.py:2002:9: E741 ambiguous variable name 'l'
pandas/tests/api/test_types.py:70:9: E741 ambiguous variable name 'l'
pandas/tests/frame/test_block_internals.py:462:9: E741 ambiguous variable name 'l'
pandas/tests/frame/test_constructors.py:817:9: E741 ambiguous variable name 'l'
pandas/tests/frame/test_constructors.py:845:9: E741 ambiguous variable name 'l'
pandas/tests/frame/test_indexing.py:1886:9: E741 ambiguous variable name 'l'
pandas/tests/frame/test_operators.py:979:9: E741 ambiguous variable name 'l'
pandas/tests/groupby/test_groupby.py:3117:9: E741 ambiguous variable name 'l'
pandas/tests/indexes/datetimes/test_ops.py:572:22: E741 ambiguous variable name 'l'
pandas/tests/indexes/datetimes/test_ops.py:576:22: E741 ambiguous variable name 'l'
pandas/tests/indexes/datetimes/test_ops.py:581:41: E741 ambiguous variable name 'l'
pandas/tests/indexes/datetimes/test_ops.py:585:41: E741 ambiguous variable name 'l'
pandas/tests/indexes/period/test_ops.py:505:22: E741 ambiguous variable name 'l'
pandas/tests/indexes/period/test_ops.py:509:22: E741 ambiguous variable name 'l'
pandas/tests/indexes/period/test_ops.py:514:41: E741 ambiguous variable name 'l'
pandas/tests/indexes/period/test_ops.py:518:41: E741 ambiguous variable name 'l'
pandas/tests/indexes/timedeltas/test_ops.py:506:22: E741 ambiguous variable name 'l'
pandas/tests/indexes/timedeltas/test_ops.py:510:22: E741 ambiguous variable name 'l'
pandas/tests/indexes/timedeltas/test_ops.py:515:41: E741 ambiguous variable name 'l'
pandas/tests/indexes/timedeltas/test_ops.py:519:41: E741 ambiguous variable name 'l'
pandas/tests/indexes/timedeltas/test_ops.py:1016:17: E741 ambiguous variable name 'l'
pandas/tests/indexes/timedeltas/test_ops.py:1019:17: E741 ambiguous variable name 'l'
pandas/tests/indexing/test_indexing.py:651:19: E741 ambiguous variable name 'l'
pandas/tests/indexing/test_loc.py:583:13: E741 ambiguous variable name 'l'
pandas/tests/io/test_packers.py:492:9: E741 ambiguous variable name 'l'
pandas/tests/io/test_packers.py:498:9: E741 ambiguous variable name 'l'
pandas/tests/io/test_packers.py:506:9: E741 ambiguous variable name 'l'
pandas/tests/io/test_pytables.py:2216:13: E741 ambiguous variable name 'l'
pandas/tests/io/test_pytables.py:3864:13: E741 ambiguous variable name 'l'
pandas/tests/io/json/test_ujson.py:942:9: E741 ambiguous variable name 'l'
pandas/tests/io/json/test_ujson.py:1087:9: E741 ambiguous variable name 'l'
pandas/tests/plotting/common.py:262:24: E741 ambiguous variable name 'l'
pandas/tests/plotting/test_datetimelike.py:496:9: E741 ambiguous variable name 'l'
pandas/tests/plotting/test_datetimelike.py:511:9: E741 ambiguous variable name 'l'
pandas/tests/plotting/test_datetimelike.py:526:9: E741 ambiguous variable name 'l'
pandas/tests/plotting/test_datetimelike.py:545:9: E741 ambiguous variable name 'l'
pandas/tests/plotting/test_datetimelike.py:563:9: E741 ambiguous variable name 'l'
pandas/tests/plotting/test_datetimelike.py:594:9: E741 ambiguous variable name 'l'
pandas/tests/plotting/test_datetimelike.py:900:17: E741 ambiguous variable name 'l'
pandas/tests/plotting/test_datetimelike.py:913:17: E741 ambiguous variable name 'l'
pandas/tests/plotting/test_datetimelike.py:931:17: E741 ambiguous variable name 'l'
pandas/tests/plotting/test_datetimelike.py:945:17: E741 ambiguous variable name 'l'
pandas/tests/plotting/test_frame.py:294:9: E741 ambiguous variable name 'l'
pandas/tests/plotting/test_frame.py:302:9: E741 ambiguous variable name 'l'
pandas/tests/scalar/test_timedelta.py:690:24: E741 ambiguous variable name 'l'
pandas/tests/scalar/test_timedelta.py:691:20: E741 ambiguous variable name 'l'
pandas/tests/series/test_analytics.py:553:13: E741 ambiguous variable name 'l'
pandas/tests/series/test_analytics.py:996:13: E741 ambiguous variable name 'l'
pandas/tests/series/test_operators.py:1542:17: E741 ambiguous variable name 'l'
pandas/tests/series/test_operators.py:1545:17: E741 ambiguous variable name 'l'
pandas/util/testing.py:1267:9: E741 ambiguous variable name 'l'
</details>

Want to ignore any of those? I think silencing E741 is fine.

**Comment by gfyoung** [comment]
Silencing E741 is fine as well.  I think we can slowly silence whatever we don't catch with `flake8`.

**Comment by jreback** [comment]
sure, these need to go in the ``.pep8speaks.yml`` though.

**Comment by jreback** [comment]
@gfyoung if you want to try a PR or to tweak these settings would be great (IOW you can push it up and get the response)

**Comment by OrkoHunter** [comment]
Hello @jreback @gfyoung @TomAugspurger !

I am thrilled to see that you are experimenting with PEP8Speaks. I would be more than happy to help out with any configurations. Also, feel free to let me know of any feature request or anything I can do for the bot to be more productive.

Thanks again. :)

**Comment by jreback** [comment]
this seems reasonable now.
