### ISSUE TITLE
COMPAT: replace import of remove_na

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#16971]
https://travis-ci.org/pandas-dev/pandas/jobs/253985437

xref #16935

this breaks ``seaborn`` which is apparently using this private method.

So let's

- open an issue on seaborn about this (optionally they can simply use ``s[s.notnull()]`` instead of the import), prob would appreciate a PR
- add back the import to ``pandas.core.series`` and deprecate ``remove_na`` (which just can call ``remove_na_arraylike``

**Comment by jreback** [comment]
cc @gfyoung 
cc @jbrockmendel

**Comment by gfyoung** [comment]
@jreback : Sounds like a good plan here.

**Comment by jbrockmendel** [comment]
Should I do this in the old PR?

**Comment by jreback** [comment]
no, new PR for this.

**Comment by gfyoung** [comment]
Issue posted on `seaborn` <a href="https://github.com/mwaskom/seaborn/issues/1240">mwaskom/seaborn#1240</a>
