### ISSUE TITLE
DOC: Clarify .agg status

### ISSUE THREAD

**Issue by dsm054** [pandas-dev/pandas#16988]
The documentation for `.agg` is almost hilariously ambiguous:

> agg is an alias for aggregate. Use it.

What is "it" referring to?  Are we being told to use `aggregate` instead of `agg` because it's the fundamental name and `agg` is a mere alias?  Or are we being told that we can and should use `agg` because it's the canonical alias (in the same way that pd is the canonical alias for pandas)?

A quick scan of the codebase suggests that `.agg` is considerably more popular than `.aggregate` among pandas devs, FWIW..

**Comment by gfyoung** [comment]
The grammarian says "aggregate" because the last noun before the pronoun is "aggregate"

However, the correct reference is `agg`, which is why you see `.agg` being used more often.
