### ISSUE TITLE
BLD: ALL Travis CI tests are running on Python 3.5

### ISSUE THREAD

**Issue by cclauss** [pandas-dev/pandas#16985]
Look at any one of the Travis CI builds at https://travis-ci.org/pandas-dev/pandas

All builds are running on Python 3.5.3.  Even the builds that are marked 2.7 and 3.6 are running on Python 3.5.3.  Either I am missing something or there seems to be a configuration issue between tox.ini and .travis.yml.

**Comment by jreback** [comment]
no this is the env that run conda
which then creates and appropriate env based on passed
these are all controlled by variables

**Comment by jreback** [comment]
tox is only a local build tool and not used in ci
