### ISSUE TITLE
SUMPRODUCT Excel functionality

### ISSUE THREAD

**Issue by guyko81** [pandas-dev/pandas#16997]
Hi,

it's not a real issue, though I'm having some hard hours because of it. The simple SUMPRODUCT (=weighted average of columns) is not possible with current solutions, or I missed something. Whatever solution I used they all caused my computer to crash. The same amount of data can be calculated in Excel (100,000 rows and 30 columns).
I know I made errors during my implementations (because this amount of data shouldn't crash a comp), so can you help me writing a script that does this work?

Thanks
guyko

**Comment by jreback** [comment]
what are you reporting?

**Comment by gfyoung** [comment]
> I know I made errors during my implementations (because this amount of data shouldn't crash a comp), so can you help me writing a script that does this work?

I don't think this is an issue related to our repository.  Rather, it seems to be a request for us to write code for @guyko81 .  You could instead reach out to the mailing list to get assistance for this.

Closing this, but can reopen if it gets clarified.

**Comment by guyko81** [comment]
thanks, I missed the channel I think 👍
