### ISSUE TITLE
ValueError on df.columns.isin(pd.Series())

### ISSUE THREAD

**Issue by wikiped** [pandas-dev/pandas#16991]
#### Code Sample, a copy-pastable example if possible

```python
    df = pd.DataFrame(columns=list('ab'))
    s1 = pd.Series(['a'])
    s2 = pd.Series()
    df.columns.isin(s1)
    df.columns.isin(s2)

```
#### Problem description

The second call to `df.columns.isin(s2)` fails with 

    D:\Anaconda\envs\py3k\lib\site-packages\pandas\core\algorithms.py in <lambda>(x, y)
        402     # work-around for numpy < 1.8 and comparisions on py3
        403     # faster for larger cases to use np.in1d
    --> 404     f = lambda x, y: htable.ismember_object(x, values)
        405     if (_np_version_under1p8 and compat.PY3) or len(comps) > 1000000:
        406         f = lambda x, y: np.in1d(x, y)

    pandas\_libs\hashtable_func_helper.pxi in pandas._libs.hashtable.ismember_object (pandas\_libs\hashtable.c:30162)()

    ValueError: Buffer dtype mismatch, expected 'Python object' but got 'double'

#### Expected Output

    array([ False, False], dtype=bool)

#### Output of ``pd.show_versions()``

    INSTALLED VERSIONS
    ------------------
    commit: None
    python: 3.5.3.final.0
    python-bits: 64
    OS: Windows
    OS-release: 10
    machine: AMD64

    pandas: 0.20.3
    numpy: 1.13.1

Might be linked to [#16394](https://github.com/pandas-dev/pandas/issues/16394)

**Comment by gfyoung** [comment]
Reproduced on `master`.  That's a bug alright.  PR is welcome!

**Comment by gfyoung** [comment]
@jreback : I would like to tag this for `0.21` because we should be able to address this bug for the release.

**Comment by jreback** [comment]
i almost always tag with next release 

otherwise u end up moving them later back if they r not done 

just so many reports it's hard to judge what to tag unless there is an actual PR

**Comment by gfyoung** [comment]
> otherwise u end up moving them later back if they r not done

That's true.  I do have this one on my radar though, so when the time comes to release and this still hasn't been resolved, feel free to call me out on it :smile:
