### ISSUE TITLE
uninteded cast to float in pivot_table with margins=True

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#17013]
#### Code Sample, a copy-pastable example if possible

```python
In [2]: df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6], "C" : [7,8,9]})

In [3]: df.pivot_table('C', 'A', 'B', fill_value=0)
Out[3]: 
B  4  5  6
A         
1  7  0  0
2  0  8  0
3  0  0  9

In [4]: df.pivot_table('C', 'A', 'B', fill_value=0, margins=True)
Out[4]: 
B      4    5    6  All
A                      
1    7.0  0.0  0.0  7.0
2    0.0  8.0  0.0  8.0
3    0.0  0.0  9.0  9.0
All  7.0  8.0  9.0  8.0
```
#### Problem description

There is no reason why adding the totals row and column should cast to float.

#### Expected Output
```python
In [5]: df.pivot_table('C', 'A', 'B', fill_value=0, margins=True).astype(int)
Out[5]: 
B    4  5  6  All
A                
1    7  0  0    7
2    0  8  0    8
3    0  0  9    9
All  7  8  9    8
```
#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: 9e7666dae3b3b10d987ce154a51c78bcee6e0728
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-3-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.21.0.dev+265.g9e7666dae
pytest: 3.0.6
pip: 9.0.1
setuptools: None
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 5.1.0.dev
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.2
openpyxl: None
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.6
lxml: None
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: 0.2.1
</details>

**Comment by gfyoung** [comment]
@toobaz : Yep, that's a bug alright.  PR is welcome!
