### ISSUE TITLE
to_stata Crashing on large Datasets

### ISSUE THREAD

**Issue by rhysjohnmiller** [pandas-dev/pandas#17022]
I have a CSV file which is around 10 million records and I can read that fine into a dataframe but when I try to execute the command:

df.to_stata(outfile,write_index=False)

I get a Memory Error. 
Is there any way to overcome this issue? 

Thanks

**Comment by chris-b1** [comment]
In prepping the data to write, it looks like we take a copy, so at least 2x the frame size is needed in memory.  _Might_ be a way to avoid that and/or write the data in chunks, would definitely welcome any improvements if you want to have a look.
https://github.com/pandas-dev/pandas/blob/dd1852d59e51e28c2f9b589eefa1916ef5d9bdc9/pandas/io/stata.py#L2086

cc @bashtage

**Comment by bashtage** [comment]
IMO there are too many places where data format changes are needed to remove this copy operation.  This isn't really a `to_stata` problem so much as a data set is too big for the memory on the machine being used.

**Comment by mroeschke** [comment]
Thanks for the report. Appears this issue is too vague to be directly actionable so closing.
