### ISSUE TITLE
chunksize and iterator arguments for jsonlines reader

### ISSUE THREAD

**Issue by anotherbugmaster** [pandas-dev/pandas#17031]
#### Code Sample, a copy-pastable example if possible

```python
pd.read_json('data.jsonlines', lines=True, chunksize=4)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-f53b1190e88e> in <module>()
----> 1 pd.read_json('data.jsonlines', lines=True, chunksize=4)

TypeError: read_json() got an unexpected keyword argument 'chunksize'

```
#### Problem description

I have a jsonlines file which is too large to fit in my computer's RAM. It would be nice if this file could be transformed to iterator to solve my problem.

#### Expected Output

Something like that:

```python
<pandas.io.parsers.TextFileReader at 0x7f53b06f6f28>
```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-83-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.20.3
pytest: None
pip: 9.0.1
setuptools: 20.7.0
Cython: None
numpy: 1.13.1
scipy: 0.19.1
xarray: None
IPython: 6.1.0
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by gfyoung** [comment]
@anotherbugmaster : Yep, by all means we need to standardize the IO interface.  We have this pretty well-implemented in `read_csv` for the C engine.  PR is welcome to add it to JSON!

**Comment by anotherbugmaster** [comment]
I wanted to make a PR today, but it seems that someone else already implemented this feature. :)
