### ISSUE TITLE
cast to float when using ``groupby.agg`` with function returning ``int`` on ``float`` input

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#17035]
#### Code Sample, a copy-pastable example if possible

```python
In [2]: df = pd.DataFrame([[1], [2], [3.3]])

In [3]: df.groupby([1,1,1]).agg(len)
Out[3]: 
     0
1  3.0
```
#### Problem description

The result of ``len`` should be ``int``, regardless of the input. This is not specific to ``len``: ``lambda x : 3`` results in the same.

#### Expected Output

Compare to

```python
In [4]: df.apply(len)
Out[4]: 
0    3
dtype: int64

In [5]: df.groupby([1,1,1]).apply(len)
Out[5]: 
1    3
dtype: int64

In [6]: df.astype(int).groupby([1,1,1]).agg(len)
Out[6]: 
   0
1  3

```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: 9e7666dae3b3b10d987ce154a51c78bcee6e0728
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-3-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.21.0.dev+265.g9e7666dae
pytest: 3.0.6
pip: 9.0.1
setuptools: None
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 5.1.0.dev
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.2
openpyxl: None
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.6
lxml: None
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: 0.2.1
</details>

**Comment by jreback** [comment]
pls search for th duplicate issue of this

**Comment by toobaz** [comment]
> pls search for th duplicate issue of this

Here are similar issues I found:
- #7001 and (at least judging from your [suggestion](https://github.com/pandas-dev/pandas/issues/14873#issuecomment-286512473)) #14873 are specific to booleans
- #14423 applies to ``apply``, which in my case works fine
- #14849 applies to ``datetime``

The fix might actually the same. As far as I understand, the key lies in your [sentence](https://github.com/pandas-dev/pandas/issues/14873#issuecomment-266715451) ".groupby tries to cast back to the original types which is generally the correct result." - my impression is that we could instead feed the result to ``np.array`` and let it find the appropriate type, regardless of the original type. But then, I still didn't look at the code.

**Comment by jreback** [comment]
> feed the result to np.array and let it find the appropriate type, regardless of the original type. But then, I 

``np.array`` doesn't do anything. the issue is that we have a computation that works on floats. you *may* have integers as a result, so you *can* try to downcast (IOW and they are equal and no nans), and that is what we do.

for the particular case of ``len``, this could simply be intercepted and treated as ``.size()`` (we DO this generally, but maybe not for ``len``, I think we do it for builtin sum).

**Comment by toobaz** [comment]
> you may have integers as a result, so you can try to downcast

My point was that the result of ``len`` is an ``int``, and should _never_ become a float, so there should be no need to downcast (the fact that input data was ``float`` should be irrelevant). But I will probably just need to look at the code to understand what you mean.

**Comment by rhshadrach** [comment]
I ran into a similar issue with .transform('nunique'):

    df = pd.DataFrame([[1, 1.1], [1, 3.1], [2, 1.1]], columns=['a', 'b'])
    df.groupby('a').b.transform('nunique')

The resulting series I get are floats using 0.25.3. They become integers if column b values are integers, or if I replace .transform('nunique') with merely .nunique().
