### ISSUE TITLE
TST: tests comparison on numpy master

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#17046]
https://travis-ci.org/pandas-dev/pandas/jobs/256013691

this was working a few builds ago. I think maybe some random sorting details, IOW how exactly argsort works can make this fail with either '>' or '<'. so ok with changing test to accept either.

```
________________________ TestMixedIntIndex.test_argsort ________________________
[gw1] linux -- Python 3.6.2 /home/travis/miniconda3/envs/pandas/bin/python
self = <pandas.tests.indexes.test_base.TestMixedIntIndex object at 0x7fe54ca566a0>
    def test_argsort(self):
        idx = self.create_index()
        if PY36:
            with tm.assert_raises_regex(TypeError, "'>' not supported"):
>               result = idx.argsort()
pandas/tests/indexes/test_base.py:1850: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pandas/util/testing.py:2493: in __exit__
    return self.exception_matches(exc_type, exc_value, trace_back)
pandas/util/testing.py:2528: in exception_matches
    raise_with_traceback(e, trace_back)
pandas/compat/__init__.py:343: in raise_with_traceback
    raise exc.with_traceback(traceback)
pandas/tests/indexes/test_base.py:1850: in test_argsort
    result = idx.argsort()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = Index([0, 'a', 1, 'b', 2, 'c'], dtype='object'), args = (), kwargs = {}
result = array([0, 'a', 1, 'b', 2, 'c'], dtype=object)
    def argsort(self, *args, **kwargs):
        """
            Returns the indices that would sort the index and its
            underlying data.
    
            Returns
            -------
            argsorted : numpy array
    
            See also
            --------
            numpy.ndarray.argsort
            """
        result = self.asi8
        if result is None:
            result = np.array(self)
>       return result.argsort(*args, **kwargs)
E       AssertionError: "'>' not supported" does not match "'<' not supported between instances of 'str' and 'int'"
pandas/core/indexes/base.py:2102: AssertionError
```

**Comment by ysau** [comment]
I am new to the project, and I am interested in helping.  If I understood the problem, the test is trying to compare an int and an str.  Is this behavior well-defined or under-defined in previous builds where the test ran without errors?  I wonder if it is due to new implementation of error-checking. 
 Please let me know if there is something I can help.

**Comment by gfyoung** [comment]
@ysau : Awesome!  Thanks for taking this issue up.  The problem that @jreback is raising is that the error message we're checking for is not correct (probably a flakey test).

Thus, all you would need to do is go in and change the expected error message in that test (`TestMixedIntIndex.test_argsort`) in `pandas.tests.indexes.test_base.py` to something that would account for both us seeing '>' and '<' in the error message.

I think you can just replace `>` with `>|<` and everything should be fine.

Let us know if you have any other questions!

FYI: documentation for contributing can be found <a href="https://pandas.pydata.org/pandas-docs/stable/contributing.html">here</a>

**Comment by ysau** [comment]
@gfyoung : I am looking at the documentation linked from your post.  Thanks for offering guidance!

**Comment by ysau** [comment]
I have noticed in TestMixedIntIndex.test_numpy_argsort in the same file, a similar assert message, "'>' not supported" is used.  I think should be updated as well.  Do you agree?

**Comment by jreback** [comment]
it might be simpler to use "'(<|>)' is not supported" (though may have to deal with the proper escapes.

**Comment by ysau** [comment]
I have submitted a pull request for changes in both places.  Please let me know if I have made an error in the process.  Thanks!
