### ISSUE TITLE
Typo in _libs.src.properties?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#17052]
https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/src/properties.pyx#L1

```
from cpython cimport PyDict_Contains, PyDict_GetItem, PyDict_GetItem
```

Looks like `PyDict_SetItem` is used in the file but never defined.  No idea why cython isn't complaining about that.

**Comment by jreback** [comment]
see https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/lib.pyx

this is an include file to lib.pyx
