### ISSUE TITLE
Index/Series Convergence

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#17061]
There has been some discussion in #8162 and [pandas2#17](https://github.com/pandas-dev/pandas2/issues/17) about making `Index` behave more like a regular Series or DataFrame column(s).  Is there a consensus towards moving in that direction?  In particular, I'm thinking about:

- `DatetimeIndex`, `PeriodIndex`, `TimedeltaIndex` could have a property `dt` that returns `self`.  Then users can access `foo.dt` without having to check whether `foo` is a `Series` or `Index`.

- If `StringAccessorMixin` is deprecated (which can be done with a tiny subset of #17042), `Index` can have `_accessors`, `_dir_deletions`, and `_dir_additions` copy/pasted from `Series`.

- Less obvious so more of an implied question: `Index.map` seems to behave a lot like `Series.apply` and less like `Series.map`.  Any reason not to alias `Index.apply = Index.map`?

Related Index/MultiIndex compat, a non-multi Index could have `self.levels = [self]`, so users can iterate over levels without pre-checking.

**Comment by jreback** [comment]
I would rather add to the previous issues rather than creating a new one. Further there already is an issue w.r.t. ``.map/.apply``. see if you can link to it.
