### ISSUE TITLE
"TypeError: __init__() got an unexpected keyword argument 'engine' " with ExcelWriter

### ISSUE THREAD

**Issue by Aashit-Sharma** [pandas-dev/pandas#17106]
Code :
`writer = pd.ExcelWriter('pandas_simple.xlsx', engine='xlsxwriter', constant_memory=True)`

The error I get is 

> "TypeError: __init__() got an unexpected keyword argument 'engine' "

I have imported pandas as pd & xlsxwriter

to_excel works , using workbook with xlsxwriter and using its writer also works ,
but somehow the Pandas "ExcelWriter" doesn't recognize "engine"

**Comment by gfyoung** [comment]
@Aashit-Sharma : Could you post version information from `pandas.show_versions()`?

The `ExcelWriter` argument doesn't accept a `constant_memory` parameter, but it does most certainly accept an `engine` parameter (at least nowadays).

**Comment by gfyoung** [comment]
Closing as stale.  The docs definitely state that an `engine` parameter is accepted (also can't reproduce the error locally).
