### ISSUE TITLE
setitem on empty DataFrame / Series casts to RangeIndex

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#17101]
I thought we had an issue for this, but couldn't find it.

```python
In [41]: df = pd.DataFrame(columns=['A'])

In [42]: df.index.dtype
Out[42]: dtype('O')

In [43]: df['A'] = []

In [44]: df.index.dtype
Out[44]: dtype('int64')

In [45]: df.index
Out[45]: RangeIndex(start=0, stop=0, step=1)
```

I this should still be empty an empty `Index` (though see https://github.com/pandas-dev/pandas/pull/16961 which proposes change `pd.Series()` to have that use a range index. Not sure if that's a good idea or not).

xref https://github.com/dask/dask/issues/2564

**Comment by TomAugspurger** [comment]
It's possible that adding an `and len(value)` to the `if` statement in https://github.com/pandas-dev/pandas/blob/ee6b1318ff07806ead79dac8119ad9ce580afe1c/pandas/core/frame.py#L3386-L3389

will fix things. That plus a test would make a good first PR.

**Comment by SvoONs** [comment]
I would like to fix this as my first PR!
