### ISSUE TITLE
ENH: followup support for pd.read_parquet

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#17102]
after https://github.com/pandas-dev/pandas/pull/15838

- [ ] add dir support in pd.read_parquet
- [ ] push down filtering of row groups
- [x] The timestamps_to_ms used for pyarrow is planned for deprecation in https://issues.apache.org/jira/browse/ARROW-622 (#17438)

**Comment by wesm** [comment]
The `timestamps_to_ms` used for pyarrow is planned for deprecation in https://issues.apache.org/jira/browse/ARROW-622

**Comment by chris-b1** [comment]
Not sure if it should be on our side our or pyarrow's, but I think we should be raising a better message with Categoricals, the current one is somewhat cryptic.

```
In [3]: df_with_categorical.to_parquet('tmp.pq')
ArrowNotImplementedError: unhandled type
```

**Comment by wesm** [comment]
Could someone file a JIRA or submit a patch?

**Comment by wesm** [comment]
https://issues.apache.org/jira/browse/ARROW-1454

**Comment by jorisvandenbossche** [comment]
I think this issue can be closed. AFAIK reading a directory already works, and the filtering is done (or not) by the engines (and a `filters` keyword can already be passed through)
