### ISSUE TITLE
API documentation should state return types

### ISSUE THREAD

**Issue by fulldecent** [pandas-dev/pandas#17114]
As an example, let's see the documentation for `pandas.DataFrame.dtypes`:

Documentation:

> `DataFrame.dtypes`
> Return the dtypes in this object.
>
> https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.dtypes.html

This documentation is insufficient to describe the function. Perhaps a better documentation would state something like:

> `DataFrame.dtypes`
>
> Return a series of dtypes in this object.
> Return type is `pandas.core.series.Series` with elements of `numpy.dtype`.

And those two types should link to related to documentation if available.

**Comment by jreback** [comment]
sure there are doc strings that could use updating

**Comment by TomAugspurger** [comment]
This has been fixed.
