### ISSUE TITLE
DEPR: use_inf_as_null option not deprecated but removed

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#17115]
From PR #16972, apparently the old config was forgot to added back: https://github.com/pandas-dev/pandas/pull/16972/files#diff-bf1e3451cec528f37a6950523e97dfe9L410

```
In [24]: pd.set_option('use_inf_as_null', True)
...
OptionError: "No such keys(s): 'use_inf_as_null'"

In [25]: pd.options.mode.use_inf_as_null
...
KeyError: 'use_inf_as_null'
```

Those raise a deprecation warning instead

**Comment by jreback** [comment]
i deprecated this in the original PR
maybe got removed somehow
