### ISSUE TITLE
Feature Request: pd.DataFrame drop method to include function support

### ISSUE THREAD

**Issue by jolespin** [pandas-dev/pandas#17129]
I think it would be useful if the `pd.DataFrame`'s `drop` method could support a `lambda` or `function` that one can use as a filter such as below: 
Also, on a side note I noticed that masking requires an extra step in the newest pandas in that it requires the mask to be converted to an array and then to a boolean. Not sure if that warrants an issue in itself but just wanted to mention that.  It is also shown below:

![image](https://user-images.githubusercontent.com/9061708/28790400-bd7c1bf0-75dd-11e7-8af8-1a2231442081.png)

**Comment by gfyoung** [comment]
> Also, on a side note I noticed that masking requires an extra step in the newest pandas in that it requires the mask to be converted to an array and then to a boolean. Not sure if that warrants an issue in itself but just wanted to mention that.

@jolespin : Separate out into another issue, as it will be easier for us to organize.

**Comment by gfyoung** [comment]
Regarding your request for a `lambda` filter on `drop`, that seems reasonable given that we support this functionality for other functions like `read_csv`.  Feel to implement and submit as a PR!

**Comment by jolespin** [comment]
Working on it now!  How can I test the code to see if it works? I need to add a few things. 

https://github.com/jolespin/pandas/edit/master/pandas/core/generic.py

**Comment by gfyoung** [comment]
@jolespin : Install your branch and then run whatever code you used in this issue.  The following section on our website here might be useful for instructions:

https://pandas.pydata.org/pandas-docs/stable/contributing.html

**Comment by mroeschke** [comment]
Appears there hasn't been much activity or community support for this feature in a while so closing. Happy to reopen if there's renewed support
