### ISSUE TITLE
Should df.expanding(50).sample(500, replace=True).mean() work?

### ISSUE THREAD

**Issue by chrism2671** [pandas-dev/pandas#17120]
```python
df.expanding(50).sample(500, replace=True).mean()
```
#### Problem description
I can't let you do that, Dave:
`AttributeError: 'Expanding' object has no attribute 'sample'
`

It would be better if these windows operated in a more general way. In this case, I want to do an expanding window **bootstrap** mean on a timeseries.

#### Expected Output

A DataFrame containing a bootstrapped mean on an expanding window.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-83-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.19.2
nose: 1.3.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.11.3
scipy: 0.18.1
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.5.1
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: 1.2.0
tables: 3.3.0
numexpr: 2.6.1
matplotlib: 2.0.0
openpyxl: 2.4.1
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.2
bs4: 4.5.3
html5lib: None
httplib2: 0.10.3
apiclient: None
sqlalchemy: 1.1.5
pymysql: None
psycopg2: None
jinja2: 2.9.4
boto: 2.45.0
pandas_datareader: 0.4.0
</details>

**Comment by jreback** [comment]
I am not sure what you are trying to do here 
can you show an actual example

**Comment by jreback** [comment]
this is ornate implemented but i suppose could be

you can do this via .apply()

**Comment by mroeschke** [comment]
Closing as stale.
