### ISSUE TITLE
Strings are handled as null terminated in internal comparisons, causing problems when working with binary strings

### ISSUE THREAD

**Issue by zoharby** [pandas-dev/pandas#17122]
#### Code Sample, a copy-pastable example if possible

```python
import pandas
import struct
binary_strings = pandas.Series([struct.pack(">H", i) for i in range(256*256)])
print len(binary_strings.unique())
sorted(binary_strings.unique())[:10]
```
#### Problem description
The above creates a series of 65536 2-bytes strings. Their sorted unique should be the same as the original series, but isn't. Instead we get:
```len(binary_strings.unique()) == 65281```
The problem probably arises from internal C comparisons which treat the strings as null terminated, hence ```'\x00\x00' == '\x00\x01' == ... ''\x00\xff'```

I came to this issue when trying to do a groupby on binary data, which resulted in less groups than it should have.

#### Expected Output
```len(binary_strings.unique()) == 65536```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------------

commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.20.2
pytest: 2.7.0
pip: 7.1.0
setuptools: 34.1.0
Cython: None
numpy: 1.9.1
scipy: None
xarray: None
IPython: 5.4.1
sphinx: None
patsy: None
dateutil: 2.6.0
pytz: 2016.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 1.5.3
openpyxl: None
xlrd: 1.0.0
xlwt: None
xlsxwriter: 0.9.6
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: 0.1.2
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
this looks correct in python 3 as bytes and string are distinct types. The issue in py2 is this simply a string and not bytes. It possible these are getting encoded somewhere incorrectly. if you want to have a look would be great.

**Comment by zoharby** [comment]
The issue is most likely inside Pandas, because doing this:
```python
print len(set(binary_strings))
```
gives 65536 correctly. Only pandas.Series.unique suffers from the problem.

**Comment by jreback** [comment]
>  if you want to have a look would be great.

as i said above

**Comment by zoharby** [comment]
> if you want to have a look would be great.

Wasn't sure if you're referring to me or not 🙂 
Thanks

**Comment by topper-123** [comment]
This works correctly in Python3, and Python2 support is being dropped. So closing the issue,
