### ISSUE TITLE
Datetimeindex hour of year

### ISSUE THREAD

**Issue by pesap** [pandas-dev/pandas#17133]
#### Feature description
Do you know if it is possible to extract hour of the year from a DateTime index object?
I think it would be convenient to include it in the _datetimelike_ops.

Expected behaviour:
Input: datetime => Output: hour_of_year
2015-01-01 01:00:00 =>    1
2015-01-01 02:00:00 =>    2
2015-01-02 01:00:00 =>   25
2015-02-15 08:00:00 => 1088
2015-12-31 22:00:00 => 8758
2015-12-31 23:00:00 => 8759

**Comment by gfyoung** [comment]
cc @jreback

**Comment by jorisvandenbossche** [comment]
I don't think it is possible with a single attribute currently, but this is not that hard to calculate yourself:

```
In [76]: (idx.dayofyear - 1) * 24 + idx.hour
Out[76]: Int64Index([1, 2, 25, 1088, 8758, 8759], dtype='int64', name='datetime')
```

Given that, I am not sure I find it worth it to add a new attribute for this.

**Comment by jreback** [comment]
I don't think this is worth it. Note that the calculation above [76] is not entirely correct when a timezone is present (if you cross a DST transition).
