### ISSUE TITLE
can't pass '%' to pandas.DataFrame.add_prefix

### ISSUE THREAD

**Issue by pirsquared** [pandas-dev/pandas#17151]
#### Code Sample, a copy-pastable example if possible
From this stackoverflow [question](https://stackoverflow.com/q/45453508/2336654)

```python
import pandas as pd
df = pd.DataFrame(dict(A=[1]))
df.add_prefix('%')
```
#### Problem description
Current implementation uses old style string formatting and breaks when passing a percent sign

#### Expected Output

```
   %A
0   1
```
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.0.final.0
python-bits: 64
OS: Darwin
OS-release: 16.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.20.3
pytest: 3.0.5
pip: 9.0.1
setuptools: 36.2.0
Cython: 0.25.2
numpy: 1.13.1
scipy: 0.18.1
xarray: 0.9.5
IPython: 5.1.0
sphinx: 1.5.1
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.0
tables: 3.3.0
numexpr: 2.6.1
feather: 0.4.0
matplotlib: 2.0.0
openpyxl: 2.4.1
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.2
bs4: 4.5.3
html5lib: 0.9999999
sqlalchemy: 1.1.5
pymysql: None
psycopg2: None
jinja2: 2.9.4
s3fs: None
pandas_gbq: None
pandas_datareader: 0.4.0

</details>

**Comment by gfyoung** [comment]
@pirsquared : Thanks for the issue!  This seems a little unusual to me.  Has this behavior ever worked for you (or anyone) in the past?

**Comment by pirsquared** [comment]
I suspect it never has. But it seems as though it should.

**Comment by jschendel** [comment]
I can do this.  Should be pretty straightforward to switch the `add_prefix` and `add_suffix` methods from using old style string formatting to `.format`, which should handle strings like '%'.

**Comment by gfyoung** [comment]
@jschendel : Go for it!  PR to add this functionality is welcome.
