### ISSUE TITLE
When agg fails the error is cached?

### ISSUE THREAD

**Issue by lrargerich** [pandas-dev/pandas#17195]
Sorry if this is too hard to reproduce. It is driving me crazy.

#### Code Sample, a copy-pastable example if possible

```python
# This works fine
data.head(2245675).groupby(level = 'id', sort = False).agg(['count'])
# This fails (If someone can help me debug why I would appreciate it but is not the issue I'm reporting, error is pasted below)
data.head(2245676).groupby(level = 'id', sort = False).agg(['count'])
# Now I get the head of data
data2 = data.head(5)
# This works ok
data2.groupby(level = 'id', sort = False).count()
# but this FAILS!
data2.groupby(level = 'id', sort = False).agg(['count'])
```
#### Problem description

It seems agg is caching something and that makes things very difficult to debug because it fails with a very simple dataframe where count works fine.

In the following section I'm pasting the error, I don't know why the error happens, if you can help me determine what in my data can cause this error then thank you!

#### The error

```python
Traceback (most recent call last)
<ipython-input-116-b422fc0967b1> in <module>()
----> 4 df.groupby(level = 'id', sort = False).agg(['count'])

/home/user/anaconda3/lib/python3.6/site-packages/pandas/core/groupby.py in aggregate(self, func_or_funcs, *args, **kwargs)
   2798         if hasattr(func_or_funcs, '__iter__'):
   2799             ret = self._aggregate_multiple_funcs(func_or_funcs,
-> 2800                                                  (_level or 0) + 1)
   2801         else:
   2802             cyfunc = self._is_cython_func(func_or_funcs)

/home/user/anaconda3/lib/python3.6/site-packages/pandas/core/groupby.py in _aggregate_multiple_funcs(self, arg, _level)
   2867             # reset the cache so that we
   2868             # only include the named selection
-> 2869             if name in self._selected_obj:
   2870                 obj = copy.copy(obj)
   2871                 obj._reset_cache()

/home/user/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py in __contains__(self, key)
    905     def __contains__(self, key):
    906         """True if the key is in the info axis"""
--> 907         return key in self._info_axis
    908 
    909     @property

/home/user/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/multi.py in __contains__(self, key)
   1326         hash(key)
   1327         try:
-> 1328             self.get_loc(key)
   1329             return True
   1330         except LookupError:

/home/user/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/multi.py in get_loc(self, key, method)
   1964 
   1965         if not isinstance(key, tuple):
-> 1966             loc = self._get_level_indexer(key, level=0)
   1967             return _maybe_to_slice(loc)
   1968 

/home/user/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/multi.py in _get_level_indexer(self, key, level, indexer)
   2227         else:
   2228 
-> 2229             loc = level_index.get_loc(key)
   2230             if isinstance(loc, slice):
   2231                 return loc

/home/user/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2391             key = _values_from_object(key)
   2392             try:
-> 2393                 return self._engine.get_loc(key)
   2394             except KeyError:
   2395                 return self._engine.get_loc(self._maybe_cast_indexer(key))

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5239)()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:4881)()

pandas/_libs/index.pyx in pandas._libs.index._bin_search (pandas/_libs/index.c:8637)()

TypeError: '<' not supported between instances of 'numpy.ndarray' and 'str'
```

#### Output of ``pd.show_versions()``
[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Linux
OS-release: 4.10.0-28-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.20.1
pytest: 3.0.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 5.3.0
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.3.0
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.7
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.3
bs4: 4.6.0
html5lib: 0.999
sqlalchemy: 1.1.9
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by gfyoung** [comment]
@lrargerich : Thanks for the report!  Yeah...this is difficult to diagnose without knowing what `data` is in your code, though given the numbers I see you're using, I don't think my computer is going to be happy operating with it in memory :smile:

**Comment by lrargerich** [comment]
This is the format of data, a series with a multiindex. Date is a period in case it matters.

```
id       date      
3531364  2017-04-13    1
1550725  2017-02-21    1
1819411  2017-04-19    1
1636629  2016-12-28    1
3123152  2017-05-03    1
dtype: int64
```

If you run a groupby(level = 'id').agg(['count']) with this data it will work fine. However if a previous agg failed with the large data and this is the head then agg fails. 
( I don't drink.... yet)

**Comment by lrargerich** [comment]
Maybe a way to start if for someone to help me know when the Type Error can happen in agg.
`TypeError: '<' not supported between instances of 'numpy.ndarray' and 'str'`

**Comment by gfyoung** [comment]
Hmm...your numbers aren't powers of two, so not sure why your second aggregation would crash.  Unfortunately, hard to tell at this point if you can't provide us with what you used for `data`.

**Comment by lrargerich** [comment]
data is a Series like the one I pasted, maybe you can help me determine what in the data can cause the problem? I checked and I have no null values. Converting to_dict() produces:

```
{(1550725, Period('2017-02-21', 'D')): 1,
 (1636629, Period('2016-12-28', 'D')): 1,
 (1819411, Period('2017-04-19', 'D')): 1,
 (3123152, Period('2017-05-03', 'D')): 1,
 (3531364, Period('2017-04-13', 'D')): 1}
```

**Comment by lrargerich** [comment]
Update problem seems to be related to the number of rows in the data and not to the data itself. For example it fails with the first 3 million records or the last 3 million records but it works if I take 1 million records from head, tail or in the middle spanning records that failed before.

I have two questions that might help me:
1) Why is the TypeError: '<' not supported between instances of 'numpy.ndarray' and 'str' happening, is a numpy null array looming somewhere or something like that? Any pointers about how to debug what is in the string and what is the ndarray to see why this happens?
2) Is there any behaviour in groupby or agg that depends on the size of data? 

Thanks!

**Comment by gfyoung** [comment]
Your issue might be related to the actual content of data.  Try the same aggregations with different columns removed.  In particular, columns with the `object` dtype could be culprits.  More systematically:

~~~python
for col in data.columns:  # exclude columns necessary for the aggregation
    data_copy = data.drop([col], axis=1)
    ...rerun agg
~~~

**Comment by lrargerich** [comment]
I only have one column and is int64. Things I've tried:
* convert the series to a DataFrame, error still happens.
* reset_index and then do groupby('id').count(), error still happens

Do you have any other ideas to try and help me debug this?

I also believe the problem is in the data but I have no idea on how to debug it. Besides this there is what I believe is a bug in Pandas related to caching. Once agg(['count']) fails with this error then any agg(['count']) over the same data fails but .count() works fine. Any idea about that?

**Comment by jorisvandenbossche** [comment]
@lrargerich can you try to debug this with the python debugger to try to understand were the error is coming from? 
One was to do this us to activate debugging mode: eg in IPython you can use the `%pdb` magic, and then you will enter debugging mode when an error occurs.

Once inside the debugger, I would go up in the stack, and try to understand where the error is comibg from eg by looking at the values of varuables etc. Eg in the `__contains__` call, what are the variables involved there?

**Comment by jreback** [comment]
make sure that your dtypes of the index are correct, iow (int64, Period), otherwise this is not reproducible.

**Comment by lrargerich** [comment]
@jorisvandenbossche 
In the __contains__ the variables are the dataframe (self) and the name of the function: 'count' I tried to debug what self._info_axis, can that be the problem or something else?

**Comment by lrargerich** [comment]
@jreback the types of the index are correct. If the types were wrong then it would fail whenever a record with the wrong type is involved. As I sad it works for the first 2.5 million records or the last 2.3 million records or something in the middle including records that were in a failed run.

**Comment by lrargerich** [comment]
I've traced up to this:

In:
groupby.py(2869)_aggregate_multiple_funcs()
   2867             # reset the cache so that we
   2868             # only include the named selection
-> 2869             if name in self._selected_obj:
   2870                 obj = copy.copy(obj)
   2871                 obj._reset_cache()

name is 'count'
and self._selected_obj  is a series so when the code runs

ipdb> 'count' in self._selected_obj
*** TypeError: '<' not supported between instances of 'numpy.ndarray' and 'str'

Can this be the problem?

**Comment by lrargerich** [comment]
The problem seems to be here:

 # reset the cache so that we
            # only include the named selection
            if name in self._selected_obj:
                obj = copy.copy(obj)
                obj._reset_cache()
                obj._selection = name

What does this section of code do? why can this work for 1 million records but fail for 3 million? I think this is the key to the problem...

**Comment by jreback** [comment]
needs a definitive repro

**Comment by jorisvandenbossche** [comment]
> name is 'count'
  and self._selected_obj is a series so when the code runs
>
>  ipdb> 'count' in self._selected_obj
  *** TypeError: '<' not supported between instances of 'numpy.ndarray' and 'str'
>
> Can this be the problem?

What kind of series is it then? 
Can you see if you can make a reproducible example of just this step?

**Comment by jreback** [comment]
closing as not repro. if you think this is a bug, pls show a copy-pastable example with full version info.
