### ISSUE TITLE
[DOC] Clarify DataFrame.transform vs .applymap

### ISSUE THREAD

**Issue by cancan101** [pandas-dev/pandas#17212]
Add clarification about how `DataFrame.transform` and `DataFrame.applymap` differ. Reading the docs, It seems that with no `axis` specified for `transform` the result should be the same as `applymap`.

**Comment by gfyoung** [comment]
@cancan101 : You are more than welcome to submit a PR to clarify that! :smile:

**Comment by mroeschke** [comment]
applymap has been deprecated so closing
