### ISSUE TITLE
BUG: IntervalIndex.is_non_overlapping_monotonic returns numpy.bool_ instead of Python bool

### ISSUE THREAD

**Issue by jschendel** [pandas-dev/pandas#17237]
#### Code Sample, a copy-pastable example if possible

```python
In [1]: import pandas as pd
   ...: idx = pd.IntervalIndex.from_breaks(range(10))

In [2]: type(idx.is_non_overlapping_monotonic)
Out[2]: numpy.bool_
```
#### Problem description
This behavior is inconsistent with other Boolean attributes/methods, such as `is_monotonic` and `is_unique`:
```python
In [3]: type(idx.is_monotonic)
Out[3]: bool

In [4]: type(idx.is_unique)
Out[4]: bool
```

It also causes issues when using the `is` operator, e.g. `np.bool_(True) is True` evaluates to `False`.

#### Expected Output
I'd expect `is_non_overlapping_monotonic` to return a Python `bool`.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.20.3
pytest: 3.1.2
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.26
numpy: 1.13.1
scipy: 0.19.1
xarray: None
IPython: 6.1.0
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.2.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.7
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.3
bs4: 4.6.0
html5lib: 0.999
sqlalchemy: 1.1.9
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by gfyoung** [comment]
I don't see why we shouldn't return a regular Python `bool`.  Try doing that and see if it breaks anything.
