### ISSUE TITLE
Aggregator for questions regarding _libs

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#17234]
I don't see any entry for the cython code in `_libs` over on the [codecov](https://codecov.io/gh/pandas-dev/pandas/tree/master/pandas) page.  Is that measured somewhere else?

**Comment by jreback** [comment]
I don't think coverage is setup up to mark this. I suppose it could be added, though generally codecov is pretty poor.

**Comment by jbrockmendel** [comment]
I'm vaguely aware of long-term plans to overhaul things in pandas2.  Are there medium-term plans for `_libs`?  In particular, I'd be interested in:

- Implementing test coverage
- Identifying and removing unused code (e.g. I think offsets.pyx)
- Making it more accessible to those of us are only comfortable with python (more `import`, less `include` and `extern`)
- Avoiding `from xyz import *`
- Splitting up 5k line modules

**Comment by jreback** [comment]
@jbrockmendel there is an issue for removing ``offsets.pyx`` already
if you want to propose a change pls do so before actually implementing it. 

- Splitting up 5k line modules, not sure we have any of those (the ones that are are all templated code and auto-generated).
- ``from xyz import *`` is pretty standard in cython, but sure
- Making it more accessible to those of us are only comfortable with python (more import, less include and extern), well this is cython, so this is not worth doing at all.

**Comment by jbrockmendel** [comment]
> Splitting up 5k line modules, not sure we have any of those

You're right, looks like `tslib` is the only one.  It clocks in at 5740.  `lib` gets close if you count the `include`d files.

> from xyz import * is pretty standard in cython, but sure

This combined with `include` makes it really tough to figure out where names come from (especially when `*` is imported from more than one place).  A little bit of verbosity in these imports will make this a lot more accessible to newcomers (assuming that's desired).


> Making it more accessible to those of us are only comfortable with python (more import, less include and extern), well this is cython, so this is not worth doing at all.

To be clear, I'm not suggesting de-cythoning anything.  Just refactoring enough that modules can be imported independently (a comment in _libs/\_\_init\_\_.py suggests this desirable at some point).  At is it, a bunch of these pyx files import `tslib` in many cases just to get at `NaT`.

**Comment by jbrockmendel** [comment]
Ref: #11214

**Comment by jbrockmendel** [comment]
For kicks I tried implementing `datetime_helper.total_seconds` in native cython and was surprised that  it was appreciably faster than the existing version.  Are these measurements misleading somehow?  Is the C version preferred for some other reason?

```
cdef extern from "datetime_helper.h":
    double total_seconds(object)

from numpy cimport float64_t
cpdef float64_t ptotal_seconds(object obj):
    return total_seconds(obj)

cpdef float64_t total_seconds2(object td):
    cdef int microseconds, seconds, days, days_in_seconds

    microseconds = getattr(td, "microseconds", 0)
    seconds = getattr(td, "seconds", 0)
    days = getattr(td, "days", 0)
    days_in_seconds = days * 24 * 3600;
    return (microseconds + (seconds + days_in_seconds) * 1000000.0) / 1000000.0

import timeit
from datetime import timedelta
dt = timedelta(4)

def func0():
    return total_seconds(dt)

def func1():
    return ptotal_seconds(dt)

def func2():
    return total_seconds2(dt)

times = {}
times['total_seconds'] = timeit.timeit(func0)
times['ptotal_seconds'] = timeit.timeit(func1)
times['total_seconds2'] = timeit.timeit(func2)
```

Results:
```
{'ptotal_seconds': 0.21397995948791504,
 'total_seconds': 0.21534299850463867,
 'total_seconds2': 0.07924604415893555}
```

I get roughly the same results if I run a loop inside the file instead of calling `timeit.timeit`.  The fact that the wrapped `ptotal_seconds` is slightly faster than the not-wrapped `total_seconds` seems fishy.

**Comment by jbrockmendel** [comment]
It looks like `pandas_datetime_struct` is [identical](https://github.com/numpy/numpy/blob/master/numpy/core/include/numpy/ndarraytypes.h#L754) to `npy_datetimestruct`.  Is there a compelling reason to have a separate implementation?

It also looks like every single use of `pandas_datetimestruct_to_datetime` uses `PANDAS_FR_ns`.  For `pandas_datetime_to_datetimestruct` there is one use in `_get_datetime64_nanos` that does not use `PANDAS_FR_ns`.  Are the general cases used somewhere else I'm not seeing?

**Comment by jreback** [comment]
pandas was originally written before cython was really that compat so a fair amount of c was written. not sue why the perf differences are there, but usually things like this come down to certain ways given type conversions and some not. find a real world benchmark where this actually matters. 

```
In [2]: import datetime

In [3]: dt = datetime.timedelta(4)

In [4]: dt.total_seconds()
Out[4]: 345600.0

In [5]: %timeit dt.total_seconds()
182 ns +- 2.61 ns per loop (mean +- std. dev. of 7 runs, 10000000 loops each)

In [6]: from pandas._libs.tslib import tot_seconds

In [7]: %timeit tot_seconds(dt)
381 ns +- 3.46 ns per loop (mean +- std. dev. of 7 runs, 1000000 loops each)
```
this makes almost no difference.

**Comment by jreback** [comment]
we don't really need an explicit issue for this.

**Comment by jbrockmendel** [comment]
> we don't really need an explicit issue for this.

I'll keep posting not-quite-issue questions here as they come up unless you point me somewhere else.

**Comment by jbrockmendel** [comment]
Earlier I noted that `pandas_datetime_struct` appeared identical to `npy_datetimestruct`.  This makes sense now that I look at the comment at the top of the file saying it was derived from Numpy 1.7.  Is there some point at which we can just use the numpy versions?

**Comment by jorisvandenbossche** [comment]
> >  we don't really need an explicit issue for this.

> I'll keep posting not-quite-issue questions here as they come up unless you point me somewhere else.

Let's either keep this issue open, or either use gitter for those questions.

For me keeping it in this issue is fine (it is somewhat easier to keep track off than a gitter conversation), but let's avoid opening new issues for every question.

@jbrockmendel I can't answer your question regarding the datetime struct (I am not familiar with this part of the code). But, while digging into the the codebase, you are always welcome to better document what you are finding out! (to make it easier to grasp it for the next person)

**Comment by jbrockmendel** [comment]
@shoyer I'm trying to figure out how to "import" functions from https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/datetime_strings.h into _libs/src/ujson/python/objToJSON.c with no luck so far.  You were the last person to edit the np file, so I'm betting you're familiar with it.  What needs to be \#included (or [verb]ed) to get those functions from the numpy version instead of from the copy in pandas?

**Comment by shoyer** [comment]
@jbrockmendel I think these functions actually intentionally not exported as part of NumPy's C-API -- notice the `NPY_NO_EXPORT` macro. This could probably be reconsidered given that datetime64 is no longer as experimental as it once was, but would need to be brought up on the NumPy mailing list.

**Comment by jbrockmendel** [comment]
`Timestamp` subclasses `datetime.datetime`, but then overrides each of `year`, `month`, ..., `second` in such a way as to require re-computing these attributes on each access.  This is the reason why the performance [here](https://github.com/pandas-dev/pandas/pull/17297#pullrequestreview-57686247) behaves unexpectedly.

Does this do something helpful like lower the memory footprint?  The implementation of `_Timestamp` is explicitly documented as being a PITA, so it wouldn't be a huge surprise if the answer was "because that's the only/easiest way to make it Just Work".

**Comment by jbrockmendel** [comment]
Three questions regarding modernization in `tslib`.

From `tslib.convert_to_timedelta64` [docstring](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslib.pyx#L3554):

```
    # kludgy here until we have a timedelta scalar
    # handle the numpy < 1.7 case
```

I think <1.7 is no longer supported.  Is that accurate, and if so, can some kludge be removed?

From near the top of the [module](https://github.com/pandas-dev/pandas/blob/96f92eb1c696723b6465fdc273dc8406201c606a/pandas/_libs/tslib.pyx#L105):

```

# in numpy 1.7, will prob need the following:
# numpy_pydatetime_import
```

Is this a going concern?

Last, from `convert_to_tsobject` in the case [where](https://github.com/pandas-dev/pandas/blob/96f92eb1c696723b6465fdc273dc8406201c606a/pandas/_libs/tslib.pyx#L1492) input is a `datetime` (or subclass, including `Timestamp`):

```
        if tz is not None:
            # sort of a temporary hack
            if ts.tzinfo is not None:
                if (hasattr(tz, 'normalize') and
                    hasattr(ts.tzinfo, '_utcoffset')):
```

It looks like this "temporary hack" has been in place for at least 5 years (still trying to figure out how to recurse with `git blame`).  Any idea what the longer-term plan is/was?

**Comment by jreback** [comment]
> I think <1.7 is no longer supported. Is that accurate, and if so, can some kludge be removed?

sounds ok

> Is this a going concern?

well you can remove and see

> It looks like this "temporary hack" has been in place for at least 5 years (still trying to figure out how to recurse with git blame). Any idea what the longer-term plan is/was?

this is related to how the tz objects (``dateutil/pytz``). We still support somewhat older versions of these (that have these methods/properties). You can certainly check whether things pass when taking this out.

As always, do self-contained / related changes in a single PR.

**Comment by jbrockmendel** [comment]
>> I think <1.7 is no longer supported. Is that accurate, and if so, can some kludge be removed?

> sounds ok

I should have been more clear: what is the kludge?  It isn't obvious what the comment is referring to.

**Comment by jbrockmendel** [comment]
_libs/src/util.pxd gets a function `is_datetime64_object` that it gets from numpy_helper.h.  In numpy_helper it is defined as:

```
PANDAS_INLINE int is_datetime64_object(PyObject* obj) {
    return PyArray_IsScalar(obj, Datetime);
}
```

I have been unable to figure out how `Datetime` gets into the namespace or what it is.  Is this function equivalent to `isinstance(obj, np.datetime64)`?

**Comment by jreback** [comment]
yes these are equivalent but you need to use the c routines
