### ISSUE TITLE
CLN: remove have_pytz?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#17251]
From [tslib.pyx](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslib.pyx#L4083)

```
try:
    import pytz
    UTC = pytz.utc
    have_pytz = True
except:
    have_pytz = False

[...]
def tz_convert_single(int64_t val, object tz1, object tz2):
    [...]
    if not have_pytz:
        import pytz
```

From much [earlier](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslib.pyx#L63) in tslib.pyx
```
from pytz.tzinfo import BaseTzInfo as _pytz_BaseTzInfo
```

Is the try/except still necessary?  If so, is `import pytz` the right thing to do in `tz_convert_single`?

**Comment by gfyoung** [comment]
Reminds me of #17173.  We wouldn't deprecated anything but just remove the check if it is no longer necessary, but I suspect a more involved solution will be needed @jreback ?

**Comment by chris-b1** [comment]
`pytz` is a hard dependency so I think this could simply be removed.

**Comment by jbrockmendel** [comment]
> We wouldn't deprecated anything but just remove the check

Note to self: learn the difference between "deprecate" and "remove".

If there's a consensus, I'll make a PR to remove this check.  While we're at it, do we still need to check for dateutil versions?

**Comment by gfyoung** [comment]
@jbrockmendel : #17002 might be relevant for this.  I would refrain from this for the moment, but you can give it a shot in a separate commit to see.

**Comment by jbrockmendel** [comment]
There are also several try/excepts in src/inference.pyx for importing dateutil.parser

**Comment by jreback** [comment]
``pytz`` is a strict requirement, so this could be removed.
