### ISSUE TITLE
TST: Compression Inference Tests for read_*

### ISSUE THREAD

**Issue by gfyoung** [pandas-dev/pandas#17262]
xref: <a href="https://github.com/pandas-dev/pandas/pull/17206#issuecomment-322584420">#17206 (comment)</a>

cc @dhimmel

**Comment by dhimmel** [comment]
See https://github.com/pandas-dev/pandas/pull/17206#issuecomment-322586996. In short, not all `read_*` methods use functionality from `io.common`. This would be nice, see https://github.com/pandas-dev/pandas/issues/15008, but it's a huge task. If we tested compression inference for all `read_*` methods, many would likely fail... there's lot's of undesirable duplicated functionality across the read code.

**Comment by gfyoung** [comment]
Fair enough.  Perhaps you can testing whichever functions hit the `io.common` path and revise your `whatsnew` entry to reflect that.

**Comment by jreback** [comment]
> If we tested compression inference for all read_* methods, many would likely fail

@dhimmel but that's exactly the point. I am quite happy to have a comprehensive test, that xfails things that are not converted / implemented.

**Comment by dhimmel** [comment]
Looking through the source code, I believe `io.common.infer_compression` is only called in the following three places:

## `io.pickle.to_pickle()`

https://github.com/pandas-dev/pandas/blob/a46e5beed5ee0c2395f11ab325eb1b71e6d23c60/pandas/io/pickle.py#L38

## `io.pickle.read_pickle()`

https://github.com/pandas-dev/pandas/blob/a46e5beed5ee0c2395f11ab325eb1b71e6d23c60/pandas/io/pickle.py#L76

## `io.parsers._read()`

https://github.com/pandas-dev/pandas/blob/a46e5beed5ee0c2395f11ab325eb1b71e6d23c60/pandas/io/parsers.py#L395

The first two are for pickle IO. Tracking down where/how `io.parsers._read` gets used has been a bit more challenging. Will keep looking into it.

**Comment by dhimmel** [comment]
`io.parsers._read` is called by `io.parsers._make_parser_function`:

https://github.com/pandas-dev/pandas/blob/a46e5beed5ee0c2395f11ab325eb1b71e6d23c60/pandas/io/parsers.py#L660

`_make_parser_function` is then used in `io.parsers` to create `read_csv` and `read_table`

https://github.com/pandas-dev/pandas/blob/a46e5beed5ee0c2395f11ab325eb1b71e6d23c60/pandas/io/parsers.py#L667-L671

Therefore, I believe, at the current time, _infer_compression is only used by the user-facing IO functions of `read_pickle`, `write_pickle`, `read_csv`, and `read_table`?

@gfyoung @jreback: should I revise the What's New Entry for #17206 to list these four functions?

https://github.com/pandas-dev/pandas/blob/6fe68325de93a5f745ff49eac57589d33a1d53c1/doc/source/whatsnew/v0.21.0.txt#L129

**Comment by gfyoung** [comment]
@dhimmel : Agreed, part of your PR should be to revise the `whatsnew` and add tests for any affected functions

**Comment by jreback** [comment]
@dhimmel any interest in working on this one would be great.

**Comment by jreback** [comment]
@gfyoung can you evaluate this issue, e.g. tick boxes close, etc.

**Comment by gfyoung** [comment]
This looks good to go!  #17900 actually took care of this.
