### ISSUE TITLE
_Period if self is NaT

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#17263]
https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/period.pyx#L805

```
cdef class _Period(object):
   [...]
   def __sub__(self, other):
       if isinstance(self, Period):
       [...]
       elif isinstance(other, Period):
           if self is NaT:
               return NaT
       [...]
```

1) Is the `self is NaT` branch possible?

2) Are there any non-trivial cases where the `isinstance(self, Period)` is Falsey?

**Comment by jreback** [comment]
```
In [1]: pd.Period(pd.NaT)
Out[1]: NaT
```

**Comment by jbrockmendel** [comment]
```

In [2]: per = pd.Period(pd.NaT)
In [3]: isinstance(per, pd.Period)
Out[3]: False

In [4]: per.__sub__
Out[4]: <method-wrapper '__sub__' of NaTType object at 0x10fc21b50>
```

It is not clear to me how this method gets called in this case.

2. Can you elaborate?  The only way I see is if `self` is specifically a `_Period` object, but I don't where that class is used on its own.

**Comment by jreback** [comment]
you would have to step thru. if you think its a dead code path remove it and see
