### ISSUE TITLE
API: Use object dtype for empty Series

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#17261]
Currently an empty `Series` has a float dtype:

```python
In [15]: pd.Series().dtype
Out[15]: dtype('float64')
```

This is consistent with NumPy, but inconsistent with the rest of pandas:

```python
In [18]: pd.Index([]).dtype
Out[18]: dtype('O')

In [19]: pd.DataFrame(columns=['A']).dtypes
Out[19]:
A    object
dtype: object
```

I think it's best to just make all our containers treat empty as object dtype, unless explicitly told otherwise (excluding specialized containers like `Int64Index`).

**Comment by jreback** [comment]
xref https://github.com/pandas-dev/pandas/issues/1783

**Comment by TomAugspurger** [comment]
This will potentially fix https://github.com/pandas-dev/pandas/issues/16737 as well

**Comment by jreback** [comment]
> This will potentially fix #16737 as well

not at all, that is completely different, but #16961 is a PR for that issue.

**Comment by TomAugspurger** [comment]
Probably not getting to this for 0.24.

**Comment by TomAugspurger** [comment]
Pushing again :/ Maybe forever at this point?

**Comment by SaturnFromTitan** [comment]
I'm looking into this
