### ISSUE TITLE
Groupby().nth(0) disorder the original dataframe columns and potential bug with sort=False

### ISSUE THREAD

**Issue by Chet-Sheng** [pandas-dev/pandas#17273]
#### Code Sample, a copy-pastable example if possible
The original data used is too large to display and below I used a sampled toy data to reproduce:
### Data Used:
```python
# original dataframe is sorted by 'id', 'num_sess', 'datatime' with ascending = True:
# ie. data.sort_values(['id' ,'num_sess' ,'datetime'], inplace=True)
# data_base is a fraction of original dataframe data with id =1, 2, 52433:

data_base
```
output:
https://github.com/Chet-Sheng/My-Project/blob/master/data_base.csv

---
### Problem One:  
the groupby().nth() would disorder my columns sequence, making it different from original data frame's column sequence rather than just extract 3 columns as index. 
**Code:**
```python
data_base.groupby(['id','num_sess','product_id_CartStarted'],sort=True).nth(0)
```
**Output:**
https://github.com/Chet-Sheng/My-Project/blob/master/data_groupby_sortTrue.csv

---
### Problem Two:
As you can see from below csv, groupby(, sort=False) output has a row with id = 52433, and I have no idea why id = 52433 would appear after id = 1, given I have already sorted data_base before groupby. Actually that line data completely make no sense, because when I check data_base with id = 52433, num_sess= 4, product_id= 3997899, it never has its cart_firstTime same as groupby output. Looks like data_base.groupby(['id','num_sess','product_id_CartStarted'],sort=False).nth(0) created a row doesn't exist.

The reason that I am using sort=False is that I don't want the product_id to be sorted ascending. data_base was sorted by time and I want the product_id show up by time as well.
**Code**
```python
data_base.groupby(['id','num_sess','product_id_CartStarted'],sort=False).nth(0)
```
**Output:**
https://github.com/Chet-Sheng/My-Project/blob/master/group_by_data_base.csv

**Comment by gfyoung** [comment]
@Chet-Sheng : Could you provide code and description of what issue you're seeing?

**Comment by Chet-Sheng** [comment]
Thank you for your quick response, I published it by mistake. I am editing it now

**Comment by Chet-Sheng** [comment]
Description is updated now. Hope to get the answer soon. Many Thanks.

**Comment by gfyoung** [comment]
A couple of points:

1) It would be preferable if you could show us the entire `DataFrame`, though your first problem at least doesn't require that.  The second one is a little strange, but it's harder to tell without the entire table.

2) Could you provide output of `pd.show_versions` ?

**Comment by Chet-Sheng** [comment]
1.  The entire dataframe is too large to show. Shape of it is 286105 rows × 27 columns.

2.`pd.show_versions:`

INSTALLED VERSIONS

commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.64+
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.19.1
nose: None
pip: 9.0.1
setuptools: 36.0.1
Cython: 0.25.2
numpy: 1.13.0
scipy: 0.19.1
statsmodels: 0.6.1
xarray: None
IPython: 6.1.0
sphinx: None
patsy: 0.4.1
dateutil: 2.5.0
pytz: 2016.7
blosc: None
bottleneck: None
tables: 3.4.2
numexpr: 2.6.2
matplotlib: 1.5.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.6.0
html5lib: 0.999999999
httplib2: 0.10.3
apiclient: 1.5.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.48.0
pandas_datareader: None

**Comment by gfyoung** [comment]
1. I would be wary of sending us any of the original data.  We prefer not to handle potentially sensitive information.  If possible, can you replicating this issue with a smaller table and share that in the issue?

2. Are you able to upgrade your `pandas` installation?  That might be able to solve your problem right from the get-go.

**Comment by Chet-Sheng** [comment]
## Issue: 
**1. I have redo it with up-to-date pandas and the problem is still there.**
**2. I also redo it with a smaller data and below is the result:**
```python
# generate a smaller dataset by only taking part of columns
data_base=data_base[['id','num_sess','product_id_CartStarted','cart_firstTime','cart_lastTime','cart_startTime']]

# generate a smaller dataset by only taking part of id in [1,2,52433]
test1=data_base[data_base['id']==1]
test2=data_base[data_base['id']==2]
test3=data_base[data_base['id']==52433]
test=pd.concat([test1,test2,test3],axis=0)

# Use groupby
test.groupby(['id','num_sess','product_id_CartStarted'],sort=False).nth(0)
```
output:
<img width="1101" alt="screenshot 2017-08-18 00 17 36" src="https://user-images.githubusercontent.com/25270186/29437789-b783d7f8-83aa-11e7-831d-cf32f6c95290.png">

## Data Used:

**test1:**

 id | num_sess | product_id_CartStarted | cart_firstTime | cart_lastTime | cart_startTime
 -- | -- | -- | -- | -- | --
1 | 1 | 3838997.0 | 2017-05-19 08:02:53+00:00 | 2017-05-19 08:02:53+00:00 | 2017-05-19 08:02:51
1 | 2 | 3838997.0 | 2017-05-19 13:51:59+00:00 | 2017-05-19 13:51:59+00:00 | 2017-05-19 08:02:51
1 | 3 | 4096138.0 | 2017-06-02 21:40:06+00:00 | 2017-06-02 21:40:06+00:00 | 2017-06-02 21:40:06
1 | 4 | 4096138.0 | 2017-06-09 14:23:10+00:00 | 2017-06-09 14:23:10+00:00 | 2017-06-09 14:23:10

**test2:**

 id | num_sess | product_id_CartStarted | cart_firstTime | cart_lastTime | cart_startTime
 -- | -- | -- | -- | -- | --
2 | 1 | NaN | 2017-05-26 13:25:27+00:00 | 2017-05-26 13:25:27+00:00 | 2017-05-26 13:25:20
2 | 1 | 4009686.0 | 2017-05-26 13:25:27+00:00 | 2017-05-26 13:25:27+00:00 | 2017-05-26 13:25:20
2 | 2 | NaN | 2017-06-09 13:20:23+00:00 | 2017-06-09 13:20:23+00:00 | 2017-06-09 13:20:30
2 | 2 | 4085525.0 | 2017-06-09 13:20:23+00:00 | 2017-06-09 13:20:23+00:00 | 2017-06-09 13:20:30
2 | 3 | NaN | 2017-06-12 08:32:26+00:00 | 2017-06-12 08:32:26+00:00 | 2017-06-12 08:32:44

**test3:**

   id | num_sess | product_id_CartStarted | cart_firstTime | cart_lastTime | cart_startTime
-- | -- | -- | -- | -- | --
52433 | 1 | 3949698.0 | 2017-05-24 18:43:00+00:00 | 2017-05-24 18:48:37+00:00 | 2017-05-24 18:43:00
52433 | 2 | 4211595.0 | 2017-06-12 14:03:52+00:00 | 2017-06-12 14:03:52+00:00 | 2017-06-12 14:03:52
52433 | 3 | 4211595.0 | 2017-06-12 14:03:14+00:00 | 2017-06-12 14:03:52+00:00 | 2017-06-12 14:03:52
52433 | 4 | NaN | 2017-06-12 14:15:54+00:00 | 2017-06-12 14:28:26+00:00 | 2017-06-12 14:16:23
52433 | 4 | NaN | 2017-06-12 14:15:54+00:00 | 2017-06-12 14:28:26+00:00 | 2017-06-12 14:16:23

**Comment by Chet-Sheng** [comment]
Forgot to upload the test data used to GitHub, and here is the link
https://github.com/Chet-Sheng/My-Project

**Comment by gfyoung** [comment]
For starters, I see that the columns are no longer "incorrectly" ordered, so I think the upgrade has resolved your first issue.   As for the second one, I'm not sure as to why `pandas` chose the order that it did, but it probably has to do with the fact that you passed in `sort=False`.  What do you get when you pass in `sort=True` ?

**Comment by Chet-Sheng** [comment]
Thank you for your response. 
1. The first problem about the` groupby().nth() `disordering columns sequence still exists. Previous toy data is too small to reproduce the problem and I have created a sample data with more columns called 'data_base.csv', and it can reproduce the problem with following code:
```python
test.groupby(['id','num_sess','product_id_CartStarted'],sort=False).nth(0)
```

2. Without using `sort=False`: 
```python
test.groupby(['id','num_sess','product_id_CartStarted']).nth(0)
```
the strange row with `id= 52433` disappeared but the column disorder issue is still there. But I do need `sort=False`, because otherwise `product_id_CartStarted` would be sorted ascending within each `num_sess`, while I want to keep sequence of `product_id_CartStarted` same as how it firstly appeared in original data from top row to end row.

#### Sample data to reproduce above 2 problems:

https://github.com/Chet-Sheng/My-Project/blob/master/data_base.csv

#### Output of 
```python
test.groupby(['id','num_sess','product_id_CartStarted'], sort=False).nth(0)
```
is:
https://github.com/Chet-Sheng/My-Project/blob/master/group_by_data_base.csv

**Comment by gfyoung** [comment]
Gotcha.  Okay, so then I would consider your concern about the "disorder" of the columns to be somewhat moot, as you can't really say that the indices are out of order if you don't want to impose sorting on them (correct me if I'm wrong).

However, if you do want to sort the index afterwards, I would suggest using `.sort_index` after the `.nth` call.  As for your second issue, that still does sound a little strange.  Would you mind posting what you get as output when using this larger table?

**Comment by Chet-Sheng** [comment]
1. Column disorder problems still exist when using `sort=True`:

data used:
https://github.com/Chet-Sheng/My-Project/blob/master/data_base.csv

```python
data_groupby_sortTrue=data_base.groupby(['id','num_sess','product_id_CartStarted'], sort=True).nth(0)
```
output:
https://github.com/Chet-Sheng/My-Project/blob/master/data_groupby_sortTrue.csv

2. Yeah, second problem also confused me so much, and I think it may be a bug. I believe my previous post already showed the problem, data, code and output clearly, and I believe you can reproduce the problem as well. The perfect larger sample data would be around 300MB and I can shared it on google drive if you are interested.

*I updated previous comment a bit to make it clearer.

**Comment by jreback** [comment]
pls don't post pictures of data frames. Pls post a fully copy-pastable reproducible example.

**Comment by Chet-Sheng** [comment]
I edited the very first post and saved everything in csv. I believe it can be reproduced now.

**Comment by jreback** [comment]
this needs to be copy-pastable.

**Comment by Chet-Sheng** [comment]
Define the dataframe column by column to make it copy-passable? It is too large to do that. I didn't see what's the problem with csv file. I saw developers asked for data from online drive before.

**Comment by jreback** [comment]
show a small reproducible example that isolates it as much as possible.

**Comment by jreback** [comment]
closing as not reproducible. if you have a self-contained example that shows the problem great.
