### ISSUE TITLE
display.precision not honored for column headers

### ISSUE THREAD

**Issue by pblelloch** [pandas-dev/pandas#17280]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np
pd.options.display.precision = 3
labels = np.random.rand(10)
p = pd.DataFrame(np.random.randn(10,10),index=labels,columns=labels)
p

```
#### Problem description

The above code works just fine in a standard console, but in a jupyter notebook the float valued column headers are not displayed with a precision of 3.  This appears to be due to the notebook_repr_html option, since setting that to False again honors the precision.  Note that the same applies to other formatting options, and if I switch to a MultiIndex it looks fine. I posted this as a question on the pydata discussion site and Joris Van den Bossche confirmed that it was an issue and suggested that I report it here.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by jorisvandenbossche** [comment]
Thanks for reporting!

>  Note that the same applies to other formatting options

What do you mean exactly with this? That also other formatting options don't work with the notebook repr?

**Comment by pblelloch** [comment]
Yes. I couldn't remember them off the top of my head, but I think that there's a float_format option and an eng_float_format, or something like that. All behave the same way.

Thanks, Paul

Sent from my iPhone

On Aug 18, 2017, at 7:01 AM, Joris Van den Bossche <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for reporting!

Note that the same applies to other formatting options

What do you mean exactly with this? That also other formatting options don't work with the notebook repr?

-
