### ISSUE TITLE
DEPR: .as_blocks and .blocks

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#17302]
These shouldn't be public methods. Deprecate and make private (lead with ``_``) for now.

**Comment by jorisvandenbossche** [comment]
+ 1

(as long as we keep the private access like `df._data.blocks` stable, but I don't think we have any plans or incentives to change that in 1.x)

Is it even necessary to make them private? Eg internally we have exact one usage of `as_blocks`, which I suppose can easily be changes to go through `_data`

cc @pandas-dev/pandas-core

**Comment by jbrockmendel** [comment]
+1

Speaking of `_data`, is there (or could there be) an implicit convention that `foo._data` should always (with the possible exception of `Index._data`) point at a `BlockManager`?

**Comment by jreback** [comment]
> Speaking of _data, is there (or could there be) an implicit convention that foo._data should always 

its just the internal impl. For DataFrame/Series its a BlockManager. For Index its an ndarry (or another array-like type, e.g. Categorical).
