### ISSUE TITLE
feature wanted: pd.DataFrame.info() should show line numbers

### ISSUE THREAD

**Issue by musketeer191** [pandas-dev/pandas#17304]
#### Problem description

When we load data frames, sometimes there are warning of mixed types on some columns via index of columns. It will be then easier for us to check which column is it (by name) if the indices (i.e. line numbers) are shown in pd.DataFrame.info().

**Comment by TomAugspurger** [comment]
Can you give an example? Is this when loading the data, or calling `.info()`? By the time you have a DataFrame and call `.info` all the information about where it was loaded from will be gone.

**Comment by musketeer191** [comment]
Sorry, I may have confused you. What I mean is I wish for a handy feature of pd.DataFrame.info() which can show line numbers. For example, when we call it the result is sth like:
Data columns (total n columns): 
1. name type
2. name type
...
n. name type

**Comment by jreback** [comment]
I guess that is reasonable. If you would like to submit a PR would be ok.

**Comment by bashtage** [comment]
Should probably be 0 indexed.

**Comment by mukundm19** [comment]
Does this issue still need to be resolved? I would be happy to tackle this otherwise.
