### ISSUE TITLE
50 character limit for string variables when using mongodb query to create pandas DataFrame from nodechef

### ISSUE THREAD

**Issue by clairevgarnett** [pandas-dev/pandas#17316]
#### Code Sample, a copy-pastable example if possible

```
from pymongo import MongoClient
import pandas as pd
client = MongoClient("mongodb://xxxx.nodechef.com:xxx")
db = client.xxxx
users= pd.DataFrame(list(db['collection'].find()))

```
#### Problem description

I''m trying to import data from nodechef using MongoClient. I have been able to download a table for each specific collection using the above code.
However, in the dataframe that is returned, there appears to be a 50 character limit for the string variables so that they are not being returned in full.

{'email': '', 'question1': 1991, 'question3': ...
{'email': 'x', 'question1': 1980, 'question3':...
Each case for this variable in the dataframe is cut short. I've tried to find out how to extend this or remove potential character limits though have not been successful.

I think this might be to do with the .find() method and parameters within it though I don't understand which parameter or how it would need changing (or it's something else entirely!).

Thanks

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Darwin
OS-release: 14.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.20.3
pytest: 3.2.1
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.26
numpy: 1.13.1
scipy: 0.19.1
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.8
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.8
lxml: 3.8.0
bs4: 4.6.0
html5lib: 0.999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: 0.5.0

**Comment by jreback** [comment]
this is out of scope for pandas
should should file an issue with Mongo

**Comment by TomAugspurger** [comment]
Also, I'm guessing that it's just the text rerpr that is being truncated. If you check the actual value w/ `users.iloc[0, 0]` everything will probably be there.
