### ISSUE TITLE
inplace argument has no effect for rename_axis()

### ISSUE THREAD

**Issue by Zhang18** [pandas-dev/pandas#17317]
#### Code Sample, a copy-pastable example if possible

```python
	>>> df = pd.DataFrame([[1,2],[3,4]])
	>>> df
	   0  1
	0  1  2
	1  3  4
	>>> df.rename_axis('INDEX', inplace=True)
		0  1
	INDEX
	0      1  2
	1      3  4
	>>> df
	   0  1
	0  1  2
	1  3  4
	>>>

```
#### Problem description

The original dataframe is not changed even if the inplace argument is supplied.

#### Expected Output

            0  1
    INDEX
    0      1  2
    1      3  4

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-92-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.20.2
pytest: None
pip: 9.0.1
setuptools: 20.7.0
Cython: None
numpy: 1.13.0
scipy: 0.19.1
xarray: None
IPython: 6.1.0
sphinx: None
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: 0.7.3
lxml: None
bs4: 4.4.1
html5lib: 0.9999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
s3fs: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by gfyoung** [comment]
Oops...also confirmed on `0.20.3`.  We're actually considering deprecating this parameter (xref #16529).  That being said, I don't know if we want to do this immediately for this function.

Thus, we can either implement `inplace=True` OR we deprecate `inplace` immediately. @jreback ?

**Comment by TomAugspurger** [comment]
Already fixed in https://github.com/pandas-dev/pandas/pull/16505 :) (xref https://github.com/pandas-dev/pandas/issues/15704)
