### ISSUE TITLE
API: deprecate DataFrame.from_items ?

### ISSUE THREAD

**Issue by chris-b1** [pandas-dev/pandas#17320]
xref #4916, #17312

example of where it is needed
```python
items = [
 ('a', [1,2,3]),
 ('b', ['j', 'k', 'l'])
]

df = pd.DataFrame.from_items(items)
df
Out[3]: 
   a  b
0  1  j
1  2  k
2  3  l
```

We possibly could deprecate this to shrink the construction api - I find `DataFrame(dict(items))` easier to think about / remember (item is a pretty generic term), only downside I see is it discards order on <3.6

**Comment by bashtage** [comment]
What about `orient='index'? I used this just last week.
