### ISSUE TITLE
new html styling does not persist when converting from notebook to html file

### ISSUE THREAD

**Issue by doolingdavid** [pandas-dev/pandas#17330]
Hi,
I love the look of new default output of pandas dataframes in the new jupyter notebooks, but when I run

jupyter nbconvert notebook.ipynb 

and then open the resulting file notebook.html, the dataframes do not retain the very attractive new stylings. IS there anyway I can make that be the case?
Thank you!

**Comment by TomAugspurger** [comment]
I think this is just an nbconvert issue. I think I remember an issue about it, so it may already be fixed on their end.

You can work around it at the moment by specifying a custom CSS file with the CSS from the notebook.
