### ISSUE TITLE
DOC: Link broken in www.lambdafoundry.com in overview.rst

### ISSUE THREAD

**Issue by mmartini-usgs** [pandas-dev/pandas#17335]
#### Code Sample:

http://www.lambdafoundry.com/
This domain appears to be for sale.

#### Problem description

The pdf format of the documentation for Pandas, July 7, 2017
In the Credits, Section 4.4 on page 396
Also in the online html
"Since January 2012, Lambda Foundry, has been providing development resources, as well as commercial support, training, and consulting for pandas.  "

An automatic redirect leads to:
https://www.hugedomains.com/domain_profile.cfm?d=lambdafoundry&e=com

**Comment by chris-b1** [comment]
Yeah the whole overview doc page is quite out of date.  Should either update it to basically match the [about page](https://pandas.pydata.org/about.html) or get rid of it.

http://pandas.pydata.org/pandas-docs/stable/overview.html#credits

**Comment by iuliakhomenko** [comment]
Hi ! I will update it.

**Comment by gfyoung** [comment]
@iuliakhomenko : Go for it!  I don't think there's a PR this time that will make this issue moot 😄
