### ISSUE TITLE
Possible documentation problem in GroupBy section

### ISSUE THREAD

**Issue by td2014** [pandas-dev/pandas#17349]
Hi.  I'm not understanding the following section in the pandas doc regarding "Flexible apply" on the following page:  http://pandas.pydata.org/pandas-docs/stable/groupby.html:  Is the python error about missing parentheses (I suppose a v2 to v3 issue with print) intended to be the explanatory result?  If so, it seems confusing in this context.  Is this a bug in the code that is generating the example for the doc.  Thanks. 

<img width="735" alt="screen shot 2017-08-27 at 8 36 03 am" src="https://user-images.githubusercontent.com/3465912/29751641-f4a0ea2a-8b04-11e7-8fda-b1aa96d1935e.png">

**Comment by jreback** [comment]
this is an error in the docs which are built with py3

a PR to fix would be great

**Comment by td2014** [comment]
A bit more investigation shows that it looks like this parentheses matter was fixed in issue #16862 (https://github.com/pandas-dev/pandas/pull/16862) and merged to master, but the current pandas documentation is not reflecting the change:  http://pandas.pydata.org/pandas-docs/stable/groupby.html

**Comment by gfyoung** [comment]
@td2014 : That's because we don't build the docs daily (correct me if I'm wrong @jreback, and if we don't, maybe we should build a dev-version of the docs ?)

**Comment by jorisvandenbossche** [comment]
It's indeed fixed in the master docs. @td2014 the stable docs will be updated once a next release it out. Closing this then, but thanks for reporting!

**Comment by jorisvandenbossche** [comment]
dev docs is here: http://pandas-docs.github.io/pandas-docs-travis/groupby.html#flexible-apply
