### ISSUE TITLE
CLN: test_intersect_str_dates appears to have been mistakenly placed in tests/indexes/test_range.py

### ISSUE THREAD

**Issue by jschendel** [pandas-dev/pandas#17362]
#### Code Sample, a copy-pastable example if possible
https://github.com/pandas-dev/pandas/blob/36dadd70376c6033037af281a4669a360fc71cfa/pandas/tests/indexes/test_range.py#L642-L649

#### Problem description
The `test_intersect_str_dates` test within `tests/indexes/test_range.py` doesn't appear to have anything to do with `RangeIndex`.  It seems like this should be moved to `tests/indexes/test_base.py`?  Happy to submit a PR  if this is the case.

**Comment by gfyoung** [comment]
That seems like a pretty good home for it.  BTW, for reference, you probably could just have submitted a PR directly, as this is relatively trivial.

**Comment by jschendel** [comment]
Okay, will omit creating an issue for trivial stuff like this in the future.  Need to get my brain out of "every PR needs a corresponding issue" mode 😆

**Comment by gfyoung** [comment]
No worries!  I'm just saying this to make your life a little easier (or rather, to streamline the process for you to contribute).  We won't get mad if you follow the standard issue --> PR format. :smile:
