### ISSUE TITLE
Union of indexes of tuples is not sorted

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#17376]
#### Code Sample, a copy-pastable example if possible

```python
aidx1 = np.array([(1, 'A'), (2, 'A'), (1, 'B'), (2, 'B')],
                 dtype=[('num', int), ('let', 'a1')])
aidx2 = np.array([(1, 'A'), (2, 'A'), (1, 'B'),
                  (2, 'B'), (1, 'C'), (2, 'C')],
                 dtype=[('num', int), ('let', 'a1')])

idx1 = pd.Index(aidx1)
idx2 = pd.Index(aidx2)

idx1.union(idx2)
```

Result: ``Index([(1, b'A'), (2, b'A'), (1, b'B'), (2, b'B'), (1, b'C'), (2, b'C')], dtype='object')``

This was already known (the example above is copied from [the tests](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/indexes/test_base.py#L1332)), but I don't see it reported anywhere.

#### Problem description

The ``Index.union`` docs states the result is sorted if possible - and it is possible with the above.

#### Expected Output

``` python
In [4]: idx1.union(idx2).sort_values()
Out[4]: Index([(1, b'A'), (1, b'B'), (1, b'C'), (2, b'A'), (2, b'B'), (2, b'C')], dtype='object')
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: 0d676a3ccf1d7aa986416a7488b941496f936d98
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-3-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.21.0.dev+405.g0d676a3cc
pytest: 3.0.6
pip: 9.0.1
setuptools: None
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
pyarrow: None
xarray: None
IPython: 5.1.0.dev
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.2
openpyxl: None
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.6
lxml: None
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.2.1

</details>

**Comment by mroeschke** [comment]
Looks to work on master. Could use a test.

```
In [35]: aidx1 = np.array([(1, 'A'), (2, 'A'), (1, 'B'), (2, 'B')],
    ...:                  dtype=[('num', int), ('let', 'a1')])
    ...: aidx2 = np.array([(1, 'A'), (2, 'A'), (1, 'B'),
    ...:                   (2, 'B'), (1, 'C'), (2, 'C')],
    ...:                  dtype=[('num', int), ('let', 'a1')])
    ...:
    ...: idx1 = pd.Index(aidx1)
    ...: idx2 = pd.Index(aidx2)
    ...:
    ...: idx1.union(idx2)
Out[35]: Index([(1, b'A'), (1, b'B'), (1, b'C'), (2, b'A'), (2, b'B'), (2, b'C')], dtype='object')

In [36]: pd.__version__
Out[36]: '0.26.0.dev0+565.g8c5941cd5'
```

**Comment by dwhu** [comment]
I believe this test already exists: https://github.com/pandas-dev/pandas/blob/master/pandas/tests/indexes/test_base.py#L1866

```
@pytest.mark.parametrize(
        "method,expected,sort",
        [
            (
                "intersection",
                np.array(
                    [(1, "A"), (2, "A"), (1, "B"), (2, "B")],
                    dtype=[("num", int), ("let", "a1")],
                ),
                False,
            ),
            (
                "intersection",
                np.array(
                    [(1, "A"), (1, "B"), (2, "A"), (2, "B")],
                    dtype=[("num", int), ("let", "a1")],
                ),
                None,
            ),
            (
                "union",
                np.array(
                    [(1, "A"), (1, "B"), (1, "C"), (2, "A"), (2, "B"), (2, "C")],
                    dtype=[("num", int), ("let", "a1")],
                ),
                None,
            ),
        ],
    )
    def test_tuple_union_bug(self, method, expected, sort):
        index1 = Index(
            np.array(
                [(1, "A"), (2, "A"), (1, "B"), (2, "B")],
                dtype=[("num", int), ("let", "a1")],
            )
        )
        index2 = Index(
            np.array(
                [(1, "A"), (2, "A"), (1, "B"), (2, "B"), (1, "C"), (2, "C")],
                dtype=[("num", int), ("let", "a1")],
            )
        )

        result = getattr(index1, method)(index2, sort=sort)
        assert result.ndim == 1

        expected = Index(expected)
        tm.assert_index_equal(result, expected)
```

**Comment by mroeschke** [comment]
Thanks @dwhu. Yes looks like this case is covered.
