### ISSUE TITLE
Unreached/Unreachable(?) paths in tslib

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#17379]
in `tslib._Timedelta.__richcmp__` there is a path that is not reached in tests that I think may not be [reachable](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslib.pyx#L2625), seeking second opinions.  If there are corner cases where this can be reached, they should be added to the tests.

```
        if isinstance(other, _Timedelta):
            if isinstance(other, _NaT):
                return _cmp_nat_dt(other, self, _reverse_ops[op])
```

**Comment by gfyoung** [comment]
This looks reachable, given that `_NaT` subclasses `_Timedelta`.  If you can write a test that hits this branch of logic, go for it!  It seems feasible.

**Comment by jbrockmendel** [comment]
Are you [sure](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslib.pyx#L1357) `_NaT` subclasses `_Timedelta`?  If so, can you help me understand how?

```
cdef class _NaT(_Timestamp):
```

**Comment by gfyoung** [comment]
Oops, I misread it as `_Timestamp` :smile: .  My bad, yeah, I think you're probably right then, as I don't think `datetime.datetime` and `datetime.timedelta` inherit from one another (trace back the class inheritances for both `_Timedelta` and `_NaT`).

Double check and then try removing the check to see what happens.
