### ISSUE TITLE
dataframe loc setting str and unicode in python 2.7.11

### ISSUE THREAD

**Issue by rizac** [pandas-dev/pandas#17371]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
d = pd.DataFrame(columns=['bytes', 'str'], data=[['','']])
d.loc[0, ['bytes', 'str']] = ('\xc3\xb1\xc3', u'abc')  # <- raises UnicodeDecodeError

# My current workaround is to set each field separately (via loc or set_value), e.g.:
d.loc[0, 'bytes'] = '\xc3\xb1\xc3'
d.loc[0, 'str'] = u'abc'
```

#### Problem description
The cause to me is quite easy to understand, and is due to the bytes string '\xc3\xb1\xc3' having "non-ascii" characters. Further digging revealed that the line raising the exception is line 517 in `pandas.core.indexing.py`: ```np.array(('\xc3\xb1\xc3', u'abc'))```

The problem is that this prevents a user to set in a relatively fast and concise way
both bytes and unicode strings together. Is it a bug? Is the code posted bad practice (and in case why, and how should the problem be addressed? My current workaround seems clumsy and not efficient)

Thank you

#### Expected Output
```python
d = pd.DataFrame(columns=['bytes', 'str'], values=[['','']])
d.loc[0, ['bytes','str']] = ('\xc3\xb1\xc3', u'abc')  # <- simply should not raise
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Darwin
OS-release: 15.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.19.2
nose: None
pip: 9.0.1
setuptools: 32.3.1
Cython: None
numpy: 1.11.3
scipy: 0.18.1
statsmodels: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.1.4
pymysql: None
psycopg2: 2.7 (dt dec pq3 ext lo64)
jinja2: 2.9.3
boto: None
pandas_datareader: None

</details>

**Comment by gfyoung** [comment]
@rizac : Thanks for reporting this!  A couple of things:

* In the issue template, we recommend that you try upgrading to see if you're issue is still existing in the latest version of `pandas`.  I notice that you are using `0.19.2`, when we are at `0.20.3`.  Would upgrading to the newest version help you out?

* I run your code with Python 3.x without issues.  You can try importing `unicode_literals` in Python 2.x before running your sample to see if that changes things.

If neither works, ping us again, and we can revisit.

**Comment by rizac** [comment]
Thank you @gfyoung 

Yes the bug it's still there when upgrading to pandas 0.20.3. But you're right, it does not raise with python3x.

With `unicode__literals`, as long as I remember, I coerce python2 strings to be unicode, and if I correctly recall this is not the desired behaviour: I do want some columns to be bytes, and some to be unicode. Moreover, the 'bytes' data are bytes data downloaded from a web service (the example posted is for simplicity), and I do not see how the import should help

PS: I understand if the problem has not high priority (after all, it works in python3x and we are in 2017). If it will not be reported as a bug I'd like to know in any case if my workaround is the only feasible way or there is a more elegant one.

Thank you again

New pd.show_versions() output:
<details>
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Darwin
OS-release: 15.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.20.3
pytest: None
pip: 9.0.1
setuptools: 36.3.0
Cython: None
numpy: 1.13.1
scipy: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by gfyoung** [comment]
@rizac : Well 2017 is not 2020, so until then, Python 2.x compatibility must remain :smile: 

However, I think `unicode_literals` is your best way to go, as it works just fine, and if it's centering around a `numpy` array creation, that's something that's out of our control I think at this point.    The `ascii` character set is something that we cannot control.

True, you don't get `bytes`, but at least the code works, and you can always reconvert elements back to `bytes` if you need them to be so subsequently when handling them.

**Comment by topper-123** [comment]
This works in Python3 and Python2 support is being dropped. Closing.
