### ISSUE TITLE
Groupby with matching column and index name emits spurious warning

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#17383]
xref https://github.com/pandas-dev/pandas/pull/14432

Which of these should raise `FutureWarning`s? I think the idea was to use `pd.Grouper(name)` to disambiguate? In that case `In [21]` should not raise a warning?

```python
In [17]: df = pd.DataFrame({"A": [1] * 5 + [2] * 5, "B": ['a', 'b'] * 5, 'C': range(10)}, index=pd.Index(range(10), name='A'))

In [19]: _ = df.groupby('A').mean()
/Users/taugspurger/.virtualenvs/pandas-dev/bin/ipython:1: FutureWarning: 'A' is both a column name and an index level.
Defaulting to column but this will raise an ambiguity error in a future version
  #!/Users/taugspurger/Envs/pandas-dev/bin/python3.6

In [20]: _ = df.groupby(['A']).mean()
/Users/taugspurger/.virtualenvs/pandas-dev/bin/ipython:1: FutureWarning: 'A' is both a column name and an index level.
Defaulting to column but this will raise an ambiguity error in a future version
  #!/Users/taugspurger/Envs/pandas-dev/bin/python3.6

In [21]: _ = df.groupby(pd.Grouper('A')).mean()
/Users/taugspurger/Envs/pandas-dev/lib/python3.6/site-packages/pandas/pandas/core/groupby.py:1699: FutureWarning: 'A' is both a column name and an index level.
Defaulting to column but this will raise an ambiguity error in a future version
  return klass(obj, by, **kwds)

In [22]: _ = df.groupby([pd.Grouper('A')]).mean()
```

cc @jmmease

**Comment by jmmease** [comment]
Yeah, I think [21] shouldn't raise a warning

**Comment by jmmease** [comment]
I'll try to take a look at this soon.  Any reason why the `df.groupby(grp_expr)` operation shouldn't just always go down the `df.groupby([grp_expr])` path?  

I'd like to see if we could just always turn scalar `by` args into single element lists and get rid of the non-list logic. Thoughts?

**Comment by jreback** [comment]
scalar and list of a single arg should be the same
separate pr for that would be fine

**Comment by jmmease** [comment]
@jreback @TomAugspurger See #17843
FYI, I didn't end up needing to make the change discussed above (treating all groupers as lists)
