### ISSUE TITLE
Error while trying to use column values in a dataframe.query() as dictionary keys

### ISSUE THREAD

**Issue by ibrahmd** [pandas-dev/pandas#17389]
#### Code Sample, a copy-pastable example if possible

```python
#Does not work, raises: "TypeError: 'DataFrame' objects are mutable, thus they cannot be hashed "
df.query(' ITEM in @label.keys() and "H2O" in @label[ITEM]')

#Does not work, raises: " PandasExprVisitor' object has no attribute 'visit_ListComp' "
db.query(' ITEMID in [k for k,v in label.items() if "H2O" in v]')

# Works
df[df['item'].isin([k for k,v in label.items() if 'H2O' in v])]

# df header:

   SUBJECT_ID  ITEM
0           1     3
1           2     5
2           1     5
3           1     2
4           1     2

label:
{
 1: 'Coffee',
 2: 'Apple Juice',
 3: 'Soda',
 4: 'Tea',
 5: 'Sparkling H2O'
}
```
#### Problem description

As the code shows, I have a dataframe with item numbers whose labels are saved in another dictionary to save memory. I am trying to get all the rows that contain items who have a certain substring in their labels. Currently using query() to accomplish this will raise one of the two errors shown in the code. 

#### Expected Output
```
   SUBJECT_ID  ITEM
1           2     5
2           1     5
```
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.20.1
pytest: 3.0.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 5.3.0
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.2.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.7
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.3
bs4: 4.6.0
html5lib: 0.9999999
sqlalchemy: 1.1.9
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by chris-b1** [comment]
Referencing a column inside a bracketed expression isn't currently supported, I suppose it could be, or at minimum some better error reporting.

Probably more idiomatic to write your filter like this:
```python
df[df['ITEM'].map(label).str.contains('H2O')]
```

**Comment by jreback** [comment]
you can already do limited selection via:

```df.query('foo  in["A', "B", "C"]')``` IOW a list of values is supported. 

We are unlikely to expand the surface area of support for ``.query``.
