### ISSUE TITLE
python3 import zookeeper module    import

### ISSUE THREAD

**Issue by Nashcai** [pandas-dev/pandas#17390]
I recently import the zookeeper module in python 3,so when I finished my work, I made a mistake in testing the import of the zookeeper module.  

The error message is :
ImportError: /usr/local/lib/python3.5/dist-packages/zookeeper.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyInt_AsLong   
I'm using the system of linux-ubuntu.

I don't know how to solve this problem. Thanks!

**Comment by gfyoung** [comment]
@Nashcai : How does `zookeeper` relate to `pandas`?
