### ISSUE TITLE
ENH: to_json(index=False)

### ISSUE THREAD

**Issue by Suor** [pandas-dev/pandas#17394]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

df = pd.DataFrame([[1,2,3],[4,5,6]], columns=['a','b','c'])
df.to_json(orient='split')
# '{"columns":["a","b","c"],"index":[0,1],"data":[[1,2,3],[4,5,6]]}'
```

#### Problem description

Useless index data increases dump size. Affects only orients `'split'` and `'table'`.

#### Expected Output

```python
>>>  df.to_json(orient='split', index=False)
'{"columns":["a","b","c"],"data":[[1,2,3],[4,5,6]]}'
``` 
This resembles a bit how `.to_csv(index=False)` works.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 64
OS: Linux
OS-release: 4.10.0-28-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.20.3
pytest: 2.6.4
pip: 9.0.1
setuptools: 36.2.5
Cython: None
numpy: 1.13.1
scipy: 0.16.0
xarray: None
IPython: 5.4.1
sphinx: None
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: 2.6.2
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: 2.6 (dt dec pq3 ext lo64)
jinja2: 2.7.3
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by jreback** [comment]
this would be ok. a pull-request to implement would needed from the community for this.

**Comment by mpenkov** [comment]
I've started looking into this.
