### ISSUE TITLE
Series#rename(str) change the name of Series.

### ISSUE THREAD

**Issue by Eastsun** [pandas-dev/pandas#17407]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

ser = pd.Series(range(1, 6), index=pd.Index(range(2, 7), name='IntIndex'))

ser2 = ser.rename(str)

ser2.index
Out[5]: RangeIndex(start=2, stop=7, step=1, name='IntIndex')

ser2.name
Out[6]: str

```
#### Problem description
I deep into the code and find that pandas.core.series#is_list_like return True for str:
```python
In [22]: from pandas.core import series

In [23]: series.is_list_like(str)
Out[23]: True
```

The implementation of is_list_like:
```python
def is_list_like(obj):
    """
    Check if the object is list-like.
    """

    return (hasattr(obj, '__iter__') and
            not isinstance(obj, string_and_binary_types))
```

may should change to:
```python
def is_list_like(obj):
    """
    Check if the object is list-like.
    """

    return (hasattr(obj , '__iter__') and
            not isinstance(obj, string_and_binary_types) and not isinstance(obj, type))
```

#### Expected Output
```python
ser2.index
Out[20]: Index(['2', '3', '4', '5', '6'], dtype='object', name='IntIndex')

ser2.name 
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.20.3
pytest: 3.2.1
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.26
numpy: 1.13.1
scipy: 0.19.1
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
</details>

**Comment by jreback** [comment]
pls read the doc-string. you are renaming to a *callable* which is valid but weird. you generally need to use a string.

```
In [10]: ser = pd.Series(range(1, 6), index=pd.Index(range(2, 7), name='IntIndex'))

In [11]: ser
Out[11]: 
IntIndex
2    1
3    2
4    3
5    4
6    5
dtype: int64

In [12]: ser.rename('foo')
Out[12]: 
IntIndex
2    1
3    2
4    3
5    4
6    5
Name: foo, dtype: int64
```

**Comment by Eastsun** [comment]
However, I want to rename the index rather than the name of series. My expected output is Series with Index:
` Index(['2', '3', '4', '5', '6'], dtype='object', name='IntIndex')`

**Comment by jreback** [comment]
``ser.index.name = 'foo'``

this is clearly documented and does not interact with the index.

**Comment by TomAugspurger** [comment]
I think this is a bug. `str`, is a callable, so it should be altering the labels, not the name. FYI @Eastsun we're trying to clean up this API before 0.21, but for now this should work.

**Comment by TomAugspurger** [comment]
@Eastsun changing the check in `is_list_like` to check `isinstance(obj, Iterable)...`, works in this case. `Iterable` from the `collections` module. Would you mind seeing making that change breaks anything else, and submitting a PR with a fix + a test case?
