### ISSUE TITLE
TST: Some tests in indexes/datetimes/test_tools.py don't appear to run

### ISSUE THREAD

**Issue by jschendel** [pandas-dev/pandas#17403]
#### Code Sample, a copy-pastable example if possible
https://github.com/pandas-dev/pandas/blob/062f6f118fe4ea439ae255a8ff886a532e20ecdb/pandas/tests/indexes/datetimes/test_tools.py#L28-L30

https://github.com/pandas-dev/pandas/blob/062f6f118fe4ea439ae255a8ff886a532e20ecdb/pandas/tests/indexes/datetimes/test_tools.py#L337-L339

#### Problem description
None of the tests in the classes linked above appear to run.  I noticed this because there's a formatting typo that should have been caught by one of the tests:

https://github.com/pandas-dev/pandas/blob/062f6f118fe4ea439ae255a8ff886a532e20ecdb/pandas/core/tools/datetimes.py#L608

Renaming the classes to `TestTimeConversionFormats` and `TestToDatetimeUnit` makes them run locally for me, and the formatting typo gets caught.

I'd be happy to submit a PR to enable these tests and fix the formatting typo.  Wanted to check here first to make sure that these weren't purposefully disabled, and that I'm not missing something obvious.

**Comment by chris-b1** [comment]
This is not intentional but a left over from our conversion to pytest similar to #16478.  Please do submit a PR!
