### ISSUE TITLE
document groupby(mutated=True)

### ISSUE THREAD

**Issue by smoofra** [pandas-dev/pandas#17417]
#### Code Sample, a copy-pastable example if possible

```python
(Pdb) df = DataFrame(range(10), columns=['a'])
(Pdb) df
   a
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7
8  8
9  9

(Pdb) df.groupby(df.a + df.a % 2).apply(lambda x : x)
   a
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7
8  8
9  9

(Pdb) df.groupby(df.a + df.a % 2).apply(lambda x : "foo")
a
0     foo
2     foo
4     foo
6     foo
8     foo
10    foo

(Pdb) df.groupby(df.a + df.a % 2, mutated=True).apply(lambda x : x)
      a
a      
0  0  0
2  1  1
   2  2
4  3  3
   4  4
6  5  5
   6  6
8  7  7
   8  8
10 9  9

```
#### Problem description

`GroupBy.apply` is not consistent about whether or not it adds group keys to the index.   Sometimes it adds them, sometimes not, based on what it thinks is the right thing to do.

If you never want them added you can pass `group_keys=False`, but if you always want them added you must pass `mutated=True`, which is not documented.

**Comment by jreback** [comment]
this is not a public parameter and is just in the kwargs

**Comment by smoofra** [comment]
Why shouldn't it be a public parameter?   Is there a better way to tell groupby to always add the group keys?
