### ISSUE TITLE
Unnecessary attrs in NaTType?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#17429]
`NaTType.__new__` defines `_day` and `_month` attributes and sets them to -1.  What are these used for?

https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslib.pyx#L833

```
class NaTType(_NaT):
    """(N)ot-(A)-(T)ime, the time equivalent of NaN"""

    def __new__(cls):
        cdef _NaT base

        base = _NaT.__new__(cls, 1, 1, 1)
        base._day = -1
        base._month = -1
        base.value = NPY_NAT
```

**Comment by jreback** [comment]
NaT is a subclass of datetime
i think these are necessary but of course u can try to remove if u don't think so
