### ISSUE TITLE
API enhancement - change/alias Index.get_loc() to Index.get_iloc()

### ISSUE THREAD

**Issue by obarak** [pandas-dev/pandas#17428]
#### Code Sample, a copy-pastable example if possible
```python
df = pd.DataFrame([1, 2, 3], index = ['row1', 'row2', 'row3'])

# I want to get the row just before 'row3'
df.iloc[df.index.get_loc('row3') - 1]
```
#### Problem description & Expected Output
`iloc` is used for *integer selection* from a DataFrame, so it seems more natural to use `get_iloc()` to get the *integer location*  in that DataFrame. 
i.e. `df.iloc[get_iloc()]` makes more sense than `df.iloc[get_loc()]`. 
But (at least as of 0.20), the former doesn't exist.

**Comment by jreback** [comment]
.get_loc  by definition index only on value
so this is correct if u want the integer position then simply index e.g. df.index[3]
