### ISSUE TITLE
CLN: pyarrow 0.6.0 compat, we need to handle back-compat on this

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#17438]
/home/travis/miniconda3/envs/pandas/lib/python3.6/site-packages/pyarrow/pandas_compat.py:248: FutureWarning: timestamps_to_ms=True is deprecated
    warnings.warn('timestamps_to_ms=True is deprecated', FutureWarning)

**Comment by jreback** [comment]
cc @wesm

**Comment by wesm** [comment]
per discussion in https://github.com/apache/arrow/pull/1046, I think the correct fix is to remove usage of `timestamps_to_ms` in pandas and pass the right coercion option to `pyarrow.parquet.write_table`
