### ISSUE TITLE
UnicodeDecodeError when read_sas

### ISSUE THREAD

**Issue by MeetQingLiu** [pandas-dev/pandas#17446]
Hello there.
I tried to use the pd.read_sas method to import SAS7BDAT file into pandas but i got the following error.
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 0: invalid continuation byte
```
My SAS file is in utf-8 encoding and I specified ```encoding='utf-8'```in read_sas method,
howerver the error still exist.

Following the solution by [sas7bdat](https://stackoverflow.com/questions/38203988/encoding-in-sas7dbat), The error has been perfectly resolved.
However, I think there must be some bug in the read_sas method, so i raise this issue.
Thank you!.

**Comment by jreback** [comment]
your example is not reproducicle, plus you are using an older version of pandas, pls upgrade.

**Comment by MeetQingLiu** [comment]
Hi Jreback,
Thanks for your qucikly response.
I upgrade my pandas from 18.0 to 20.3, but still got the same error.

**Comment by jreback** [comment]
closing as not reproducible.
