### ISSUE TITLE
Wrong Computation: DataFrame.resample('B').apply('sum') 

### ISSUE THREAD

**Issue by shastri007** [pandas-dev/pandas#17460]
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randn(100, 3), index=pd.date_range('1/1/2012', freq='H', periods=100),    columns=['A', 'B', 'C']) # create a Dataframe of 100x3 with Names of Columns A,B,C.

df.resample('B').apply('sum').head(5)  # get first 5 rows of Business Days

```
#### Problem description
Result: 
Out[312]: 
                   A         B         C
2011-12-30  3.219887 -7.359861  1.601003
2012-01-02  5.608225  2.838693 -3.655628
2012-01-03 -3.711662 -5.036724 -1.955380
2012-01-04  3.408513  5.077044 -3.216348
2012-01-05  0.867961 -0.771305 -1.383478

2011-12-30 - is not in the Original DataFrame. 
Why this has come in the resultant DataFrame?

#### Expected Output
Out[312]: 
                   A         B         C
2012-01-02  5.608225  2.838693 -3.655628
2012-01-03 -3.711662 -5.036724 -1.955380
2012-01-04  3.408513  5.077044 -3.216348
2012-01-05  0.867961 -0.771305 -1.383478

#### Output of ``pd.show_versions()``
python: 3.5.2.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.2
setuptools: 27.2.0
Cython: 0.24.1
numpy: 1.11.1
scipy: 0.18.1
statsmodels: None
xarray: None
IPython: 5.1.0
sphinx: 1.4.6
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.6.1
blosc: None
bottleneck: 1.1.0
tables: 3.2.2
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.3
lxml: 3.6.4
bs4: 4.5.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.42.0
pandas_datareader: None
<details>

[paste the output of ``pd.show_versions()`` here below this line]
python: 3.5.2.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.2
setuptools: 27.2.0
Cython: 0.24.1
numpy: 1.11.1
scipy: 0.18.1
statsmodels: None
xarray: None
IPython: 5.1.0
sphinx: 1.4.6
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.6.1
blosc: None
bottleneck: 1.1.0
tables: 3.2.2
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.3
lxml: 3.6.4
bs4: 4.5.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.42.0
pandas_datareader: None
</details>

**Comment by gfyoung** [comment]
@shastri007 : Thanks for reporting this!  Can you try upgrading your `pandas` version first to see if the issue still persists?  We're currently at `0.20.3`.

**Comment by jreback** [comment]
@shastri007 this is correct. 12/30 is the first business day before 1/1.

**Comment by shastri007** [comment]
@jreback . '12/30 is the first business day before 1/1.'
 Issue is the original DataFrame does not have 12/30. Hence 12/30 is not supposed to be when we resample('B')
