### ISSUE TITLE
pandas_datareader.data: Google does no longer provide historical stock data?

### ISSUE THREAD

**Issue by paintdog** [pandas-dev/pandas#17466]
It seems that Google does no longer provide historical stock data respectively Google does no longer update the data. Is this correct? Is there a solution? Will there be any other sources (in the near future)?
```python
pandas_datareader.data
```

**Comment by chris-b1** [comment]
`pandas_datareader` is now a separate package, please see repo here for issues
https://github.com/pydata/pandas-datareader/issues
