### ISSUE TITLE
ENH: DataFrame.from_product to generate DataFrame from a Cartesian product

### ISSUE THREAD

**Issue by ibukanov** [pandas-dev/pandas#17495]
It would be nice to have a function like DataFrame.from_product with a interface similar to MultiIndex.from_product. For example, the following code:
```python
df = pd.DataFrame.from_product([np.linspace(1, 5, 2), np.linspace(1, 10, 3)], columns=['a', 'b'])
```

constructs the table:
```
     a    b
0  1.0  0.0
1  1.0  4.0
2  1.0  8.0
3  5.0  0.0
4  5.0  4.0
5  5.0  8.0
```

Currently to generate such table one can use:
```python
df = pd.DataFrame(list(itertools.product(np.linspace(1, 5, 2), np.linspace(0, 8, 3))), columns=['a', 'b'])
```
or rather hackish:
```python
df = pd.MultiIndex.from_product([np.linspace(1, 5, 2), np.linspace(1, 10, 3)], names=['a', 'b']).to_frame()
df.reset_index(drop=True, inplace=True)
```

Both are inefficient as they constructs a temporary to hold the Cartesian product before it is copied into the DataFrame.

**Comment by TomAugspurger** [comment]
I've never had a use for this, though I'm assuming you have @ibukanov?

Let's wait and here from others to see how wide-spread the demand is.

**Comment by jreback** [comment]
df = pd.DataFrame(list(itertools.product(np.linspace(1, 5, 2), np.linspace(0, 8, 3))), columns=['a', 'b'])


looks pretty good to me;  very pythonic

-1 as i don't see a good use case

**Comment by ibukanov** [comment]
My use case is to generate a table that covers points from some ranges of few parameters as an input to farther calculations. Later the table is joined with the results for farther analysis.

**Comment by CRiddler** [comment]
Correct me if I'm wrong, haven't gone too deep into pandas `from_records` but I know it accepts an iterator as its data. So in this case, the following code works as you want it.


	>>> import itertools
	>>> import numpy as np
	>>> import pandas as pd
	>>>
	>>> pd.DataFrame.from_records(itertools.product(np.linspace(1, 5, 2), np.linspace(0, 8, 3)), columns=['a', 'b'])
		 a    b
	0  1.0  0.0
	1  1.0  4.0
	2  1.0  8.0
	3  5.0  0.0
	4  5.0  4.0
	5  5.0  8.0

**Comment by ibukanov** [comment]
@CRiddler from_records is inefficient as it first copies each element of the iterator into a list before constructing the final array. That wastes a lot of memory when the resulting table is big. from_product can avoid that as it can allocate the final array directly from lengths of the product elements. Also, for the same reasoning MultiIndex.from_product is not necessary as one can use itertools with other constructs.

I also realized that I can implement a utility doing from_product efficiently using MultiIndex.from_product and a recently added to_frame method:
```python
>>> import numpy as np
>>> import pandas as pd
>>> pd.MultiIndex.from_product([np.linspace(1, 5, 2), np.linspace(0, 8, 3)], names=['a', 'b']).to_frame(index=False)
     a    b
0  1.0  0.0
1  1.0  4.0
2  1.0  8.0
3  5.0  0.0
4  5.0  4.0
5  5.0  8.0
```

but that seems rather awkward and DataFrame.from_product can be a nice counterpart for MultiIndex.from_product.

**Comment by IgorFobia** [comment]
As I read [here](https://stackoverflow.com/questions/13269890/cartesian-product-in-pandas), a trick is to create a dummy constant column in both dataframes and merge on that; here I use the column `key`
```python
a_df = pd.Series(np.linspace(1, 5, 2), name='a').to_frame()
b_df = pd.Series(np.linspace(1, 10, 3), name='b').to_frame()
c_df = pd.merge(a_df.assign(key=0), b_df.assign(key=0), on='key' ).drop('key', axis=1)
```

**Comment by Clementstore** [comment]
Thanks guys for all the input which I do really learn a lot.. I found another suggestion which i see maybe one good and fast solution for the captioned topic. Using MultiIndex.from_product without numpy and no merge or lamda etc.... 

a = [1, 2, 3]
b = ["a", "b", "c"]

index = pd.MultiIndex.from_product([a, b], names = ["a", "b"])
pd.DataFrame(index = index).reset_index()

I read it from here: https://stackoverflow.com/questions/13269890/cartesian-product-in-pandas

**Comment by jreback** [comment]
closing as there are good solutions already or this using a MI and we are -1 on expanding the DataFrame api at all
