### ISSUE TITLE
Duplicated sub-second datetime64 values?

### ISSUE THREAD

**Issue by zaks** [pandas-dev/pandas#17490]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np

s = pd.Series(np.random.randint(0, 1000000, size=100000).astype('datetime64[ns]')).sort_values()
s[s.duplicated()].head()
```
#### Problem description

Random output on my system:

70570   1970-01-01 00:00:00.000000159
90556   1970-01-01 00:00:00.000000248
28781   1970-01-01 00:00:00.000000274
73616   1970-01-01 00:00:00.000000276
31370   1970-01-01 00:00:00.000000409

I am not sure why I see duplicates for sub-second values. Adding small random nanosecond deltas seems like a perfect way to de-dupe an index. it does not seem to work though.

#### Expected Output

Empty.

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.20.3
pytest: None
pip: 9.0.1
setuptools: 18.7.1
Cython: None
numpy: 1.13.1
scipy: 0.15.1
xarray: None
IPython: 3.0.0
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 1.4.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.7.3
s3fs: None
pandas_gbq: None
pandas_datareader: None

**Comment by TomAugspurger** [comment]
Why are you not expecting any duplicates?

```python
In [17]: np.random.seed(0)

In [18]:
    ...: s = pd.Series(np.random.randint(0, 1000000, size=100000))

In [19]: s.nunique()
Out[19]: 95192
```

which is less than `len(s)`, so you have duplicates.

**Comment by zaks** [comment]
Ah-ha. Now I see, that duplicated() returns only a single occurence in a duplicated pair. Mystery solved. Thanks for the swift response Tom!
