### ISSUE TITLE
DOC: nice links / examples for setting with copy & aggregation

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#17505]
``SettingWithCopyWarning``
https://www.dataquest.io/blog/settingwithcopywarning/

``Aggregate/Filtering``
https://pythonforbiologists.com/when-to-use-aggregatefiltertransform-in-pandas/

I saw these nice blogs. At the very least we can add the links in our docs, maybe lift some text / examples.

**Comment by linebp** [comment]
I looked over the blogposts and they are very nice and clear. Did you mean to link them in [groupby](pandas/doc/source/groupby.rst) and [indexing](pandas/doc/source/indexing.rst)? And also in the api descriptions?

How much text and examples is it ok to lift before it would be stealing someone elses work?

**Comment by jreback** [comment]
> I looked over the blogposts and they are very nice and clear. Did you mean to link them in groupby and indexing? And also in the api descriptions?

yes whatever's appropriate

> How much text and examples is it ok to lift before it would be stealing someone elses work?

well you could argue the reverse is actually true :> I think linking to the blog is fine if you add some examples. The idea is NOT to replicate it at all, rather to provide a further place to read.
