### ISSUE TITLE
Series losts its name after set_categories

### ISSUE THREAD

**Issue by junjiecai** [pandas-dev/pandas#17509]
#### Code Works fine
``` python
(
    Series([1,2,3], name='A')
    .astype('category')
    .name
)
```
I get 'A'

#### Code in trouble
``` python
(
    Series([1,2,3], name='A')
    .astype('category')
    .cat.set_categories([1,2,3])
    .name
)
```
I get NoneType

I think its better to keep original name after set_categories()

**Comment by gfyoung** [comment]
@jreback : This seems to ring a bell for some reason.  Maybe it was regarding `Series` in general?

In any case, it seems reasonable that the name should be kept.  Feel free to investigate and see where things can be changed to create the desired behavior.

**Comment by TomAugspurger** [comment]
I wonder if https://github.com/pandas-dev/pandas/blob/f11bbf2f505d81900cc83ce387a6a1b1d2a2f866/pandas/core/categorical.py#L2071 should pass through `name=self.name`.

**Comment by TomAugspurger** [comment]
This would affect all of the delegated method:

-  'add_categories',
-  'as_ordered',
-  'as_unordered',
-  'remove_categories',
-  'remove_unused_categories',
-  'rename_categories',
-  'reorder_categories',
- 'set_categories'

@junjiecai mind submitting a pull request with [that change](https://github.com/pandas-dev/pandas/issues/17509#issuecomment-329238872) and a simple test for each of those to verify that the name is passed through?

**Comment by junjiecai** [comment]
@TomAugspurger Sure. I will do it this week.

**Comment by jreback** [comment]
note that #17517 is fixing this already.
