### ISSUE TITLE
Strings containing escape characters are processed differently than Python intends

### ISSUE THREAD

**Issue by joshjacobson** [pandas-dev/pandas#17518]
I am trying to accept a path from a user, and then load the spreadsheet at that path. Pandas, however, is seemingly handling escape character sequences improperly.

#### Code Sample:

```python
df_path = input('What is the file path?')
```
> C:\Data\166 - data\data.csv 
```python
print(df_path)

'C:\\Data\\166 - data\\data.csv'
```
```python
df = pd.read_csv(df_path, index_col=2)

FileNotFoundError: [Errno 2] No such file or directory: "C:\\Datav - data\\data.csv"
```

Pandas should not be processing the escape sequence `\\166` as `v`, since there's a double backslash.

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.20.1
pytest: 3.0.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 5.3.0
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.2.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.7
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.3
bs4: 4.6.0
html5lib: 0.999
sqlalchemy: 1.1.9
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None

**Comment by gfyoung** [comment]
@joshjacobson : Thanks for reporting this!  I can't seem to replicate this error (I created the same directories as you did).  Can you provide the version info on your machine (`pd.get_versions`)?

**Comment by joshjacobson** [comment]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.20.1
pytest: 3.0.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 5.3.0
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.2.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.7
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.3
bs4: 4.6.0
html5lib: 0.999
sqlalchemy: 1.1.9
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None

**Comment by gfyoung** [comment]
@joshjacobson : Try upgrading to `0.20.3` and see if that resolves your problem.  I'm running that version on Windows and can't replicate your issue.

**Comment by joshjacobson** [comment]
@gfyoung as an FYI, I've experienced this issue with `pd.read_stata` as well, in case you'd like to add that tag.

**Comment by Giftlin** [comment]
df_path = input('What is the file path?')
print(df_path)
import pandas as pd

df = pd.read_stata(df_path)

![image](https://user-images.githubusercontent.com/31629119/30397170-93b144d8-98e9-11e7-904d-9a9ccaada482.png)

**Comment by Giftlin** [comment]
import pandas as pd

df_path = "C:\\Data\\166 - data\\data.stata"
print(df_path)

print("__________________________")
df_path = input('What is the file path?')
print(df_path)


df = pd.read_stata(df_path)

![image](https://user-images.githubusercontent.com/31629119/30397613-08cfb622-98eb-11e7-8b93-6345933e2c15.png)


 This happens only when the path is got from input()

**Comment by Giftlin** [comment]
@gfyoung 

path = "C:\\Data\\166 - data\\data.stata"
path1 = input("what?")
print(path)
print(path1)

![image](https://user-images.githubusercontent.com/31629119/30398117-d7e76364-98ec-11e7-941f-a482c939beef.png)

**Comment by joshjacobson** [comment]
I'm going to close this issue while I ensure it's properly isolated.
