### ISSUE TITLE
AttributeError: module 'pandas' has no attribute 'plotting' with tox

### ISSUE THREAD

**Issue by cachitas** [pandas-dev/pandas#17520]
`pandas` 0.20.3 fails to import on every test when running tox.

- `tox` packages installed, besides my package:

`cycler==0.10.0, matplotlib==2.0.2, numexpr==2.6.2, numpy==1.13.1, pandas==0.20.3, py==1.4.34, pyparsing==2.2.0, pytest==3.2.2, pytest-travis-fold==1.2.0, python-dateutil==2.6.1, pytz==2017.2, scipy==0.19.1, six==1.10.0, tables==3.4.2`

- `platform linux -- Python 3.5.2, pytest-3.2.2, py-1.4.34, pluggy-0.4.0`

- all tests fail with the following error:

```
myfile.py:16: in <module>
    import pandas as pd
.tox/3.5-nocov/lib/python3.5/site-packages/pandas/__init__.py:51: in <module>
    plot_params = pandas.plotting._style._Options(deprecated=True)
E   AttributeError: module 'pandas' has no attribute 'plotting'
```

Testing the same import in a `virtualenv` without `tox` works correctly.

Looks like it is a problem with `pandas`, but could also be something regarding `tox` (or even `pytest`). Hopefully, someone more experienced with `tox` can guide me here.

#### Output of ``pd.show_versions()``

Taken from the `virtualenv` I created to test outside `tox`.

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-93-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: pt_PT.UTF-8

pandas: 0.20.3
pytest: 3.2.2
pip: 9.0.1
setuptools: 28.8.0
Cython: None
numpy: 1.13.1
scipy: 0.19.1
xarray: None
IPython: None
sphinx: 1.6.3
patsy: None
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None
None

</details>

**Comment by jreback** [comment]
you cannot run tox with a production installation, you need to clone the project and build, see the [contributing guide](http://pandas.pydata.org/pandas-docs/stable/contributing.html)

**Comment by cachitas** [comment]
Sorry I can't see how that helps.

I am not testing pandas itself. I am testing my own library with tox, where one of the dependencies is pandas. Previously, for `pandas==0.19.2` my tests would pass, but now with the latest pandas version they all fail when importing pandas, as explained above.

**Comment by TomAugspurger** [comment]
Can you post a minimal tox.ini that reproduces this?

**Comment by cachitas** [comment]
I am testing in Python 3.5 and 3.6, all outputting the same errors. Here you have an example just with one case.

```ini
[tox]
envlist =
    clean,
    3.5-nocov

; required by the docker image used
skipsdist = {env:TOXBUILD:false}

[testenv]
basepython =
    {clean,check,report,codecov,docs,spell}: python3.5
usedevelop = true
setenv =
    PYTHONPATH={toxinidir}/tests
    PYTHONUNBUFFERED=yes
passenv =
    *
deps =
    pytest
    pytest-travis-fold
commands =
    {posargs:py.test -vv --ignore=mypackage}

[testenv:clean]
commands = coverage erase
skip_install = true
usedevelop = false
deps = coverage

[testenv:3.5-nocov]
basepython = {env:TOXPYTHON:python3.5}
```

**Comment by TomAugspurger** [comment]
@cachitas that's not quite minimal. I meant something like

```
[tox]
envlist = py36

[testenv]
deps=
    pytest
    pandas
commands=pytest
```

Along with

```python
# file: test_foo.py
import pandas

def test_bar():
    pass
```

Here's the output of `tox`

```
GLOB sdist-make: /private/tmp/setup.py/setup.py
py36 inst-nodeps: /private/tmp/setup.py/.tox/dist/mypackage-5.2.0.zip
py36 installed: mypackage==5.2.0,numpy==1.13.1,pandas==0.20.3,py==1.4.34,pytest==3.2.2,python-dateutil==2.6.1,pytz==2017.2,six==1.10.0
py36 runtests: PYTHONHASHSEED='3595071649'
py36 runtests: commands[0] | pytest
================================================ test session starts =================================================
platform darwin -- Python 3.6.2, pytest-3.2.2, py-1.4.34, pluggy-0.4.0
rootdir: /private/tmp/setup.py, inifile:
collected 1 item

test_foo.py .

============================================== 1 passed in 0.30 seconds ==============================================
______________________________________________________ summary _______________________________________________________
  py36: commands succeeded
  congratulations :)
```

**Comment by cachitas** [comment]
Apologies for not being so concise, but I wanted to illustrate my `tox.ini` without omitting the potential source of the problem.

I already tested your example in my machine and it is working. 

So my next step was to build up step by step from that until I get the error reported, and it looks it comes from `pytest`.

I have the following configuration in `setup.cfg`:

```ini
[tool:pytest]
norecursedirs =
	.git
	.tox
	.env
	dist
	build
python_files =
	test_*.py
	*_test.py
	tests.py
addopts =
	-rxEfsw
	--strict
	--ignore=docs/conf.py
	--ignore=setup.py
	--ignore=.eggs
	--doctest-modules
	--doctest-glob=\*.rst
	--tb=short
```

After a quick test **I found that the `--strict` option the root of all evil**. This led me to #16852 and #16680. Apparently you have already tackled this issue. I just complicated it a lot more because I could not identify the problem immediately. Hopefully, this should be fixed in the next bugfix release.

**Comment by TomAugspurger** [comment]
Ahh, yeah that issue has been an unanticipated headache of switching to pytest.

I think there was a workaround where you add the change in https://github.com/pandas-dev/pandas/pull/16797/files to your conftest.py and pytest won't complain? Otherwise, the next release is in about 2 weeks, and things should work.
