### ISSUE TITLE
Error while reading stata, if the path is got from input() 

### ISSUE THREAD

**Issue by Giftlin** [pandas-dev/pandas#17523]
import pandas as pd

df_path = "C:\\Data\\166 - data\\data.stata"
print(df_path)

print("__________________________")
df_path = input('What is the file path?')
print(df_path)

df = pd.read_stata(df_path)

![image](https://user-images.githubusercontent.com/31629119/30397613-08cfb622-98eb-11e7-8b93-6345933e2c15.png)

 This happens only when the path is got from input()

**Comment by jschendel** [comment]
Looks like `input` automatically escapes backslash characters, so just use one:

```
In [1]: input('One backslash: ')
One backslash: C:\some folder\another\data.stata
Out[1]: 'C:\\some folder\\another\\data.stata'
```

**Comment by TomAugspurger** [comment]
I'm also sure how your `input` is working, since it doesn't look like you're passing in a string? Are you on python2?

**Comment by TomAugspurger** [comment]
Whoops, I was mistakenly in a python2 environment. But agreed with @jschendel.

**Comment by Giftlin** [comment]
Python3.5

**Comment by Giftlin** [comment]
But, for to_csv, from input() it is working perfectly fine. Only in to_stata this issue is coming.

**Comment by TomAugspurger** [comment]
How does python's os.path module handle cases like `os.path.exists('some dir\\\\file.txt')`, where there are extraneous backslashes? We should follow that.

**Comment by Giftlin** [comment]
Okay

**Comment by jschendel** [comment]
Looks like Windows ignores extra backslashes:

```python
In [1]: import os

In [2]: os.path.exists('C:\\test folder\\test.txt')
Out[2]: True

In [3]: os.path.exists('C:\\\\test folder\\\\test.txt')
Out[3]: True

In [4]: os.path.exists('C:\\\\\\test folder\\\\\\test.txt')
Out[4]: True
```

Also, I can't reproduce the `to_stata` error on Windows with Python 3.5:
```python
In [1]: import numpy as np
   ...: import pandas as pd
   ...: df = pd.DataFrame(np.random.random((4, 4)), columns=list('ABCD'), index=list('wxyz'))
   ...: df
   ...:
Out[1]:
          A         B         C         D
w  0.344244  0.072331  0.484127  0.019773
x  0.417736  0.145160  0.718806  0.416455
y  0.315311  0.060186  0.518319  0.414271
z  0.886203  0.000092  0.436284  0.202928

In [2]: out = input('output path: ')
output path: C:\\test folder\\test.stata

In [3]: out
Out[3]: 'C:\\\\test folder\\\\test.stata'

In [4]: df.to_stata(out)

In [5]: pd.read_stata(out)
Out[5]:
  index         A         B         C         D
0     w  0.344244  0.072331  0.484127  0.019773
1     x  0.417736  0.145160  0.718806  0.416455
2     y  0.315311  0.060186  0.518319  0.414271
3     z  0.886203  0.000092  0.436284  0.202928
```

**Comment by jschendel** [comment]
@Giftlin : Can you try reproducing your error, but also show the output of `os.path.exisits(df_path)`?  Would be nice to verify that `os` can see the file, but `pandas` can't.  Can you show the output of `pd.show_versions()` too?

**Comment by programminggeek1-0** [comment]
Pandas version was 0.19.2, now updated to the latest and no such issue anymore

**Comment by Giftlin** [comment]
Pandas version was 0.19.2, now updated to the latest and no such issue anymore
