### ISSUE TITLE
Documentation example for pd.read_msgpack throws exception

### ISSUE THREAD

**Issue by louispotok** [pandas-dev/pandas#17532]
The code example in the documentation for [read_msgpack](http://pandas.pydata.org/pandas-docs/stable/io.html#msgpack) throws a SyntaxError due to Python 2 syntax for printing:

```
In [319]: for o in pd.read_msgpack('foo.msg',iterator=True):
   .....:     print o
   .....: 
  File "<ipython-input-319-a0f40395739e>", line 2
    print o
          ^
SyntaxError: Missing parentheses in call to 'print'
```

This should be a simple fix but maybe someone can also search through the docs for other examples of the same problem.

**Comment by jorisvandenbossche** [comment]
Thanks for the report! 
In the meantime this has already been fixed on master (see nightly built docs: http://pandas-docs.github.io/pandas-docs-travis/io.html#msgpack), so therefore closing.
