### ISSUE TITLE
Creating a development environment doesn't work as expected in doc 

### ISSUE THREAD

**Issue by scls19fr** [pandas-dev/pandas#17544]
Hello,

I need to create a development environment for Pandas ( https://github.com/pandas-dev/pandas/issues/9154#issuecomment-329795314 )

So I try to follow https://pandas.pydata.org/pandas-docs/stable/contributing.html#creating-a-development-environment

```
$ conda create -n pandas_dev python=3 --file ci/requirements_dev.txt
Fetching package metadata .........

PackageNotFoundError: Packages missing in current channels:

  - moto

We have searched for the packages in the following channels:

  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch
```

Pinging @jorisvandenbossche

**Comment by scls19fr** [comment]
I copied `requirements_dev.txt` to `requirements_dev_py3.txt` and removed `moto` 
but this is maybe required

**Comment by jorisvandenbossche** [comment]
It's no problem for now (moto is only needed for testing, and only for certain tests), but we need to solve this in general. 

I suppose this is only available from conda-forge? cc @TomAugspurger

**Comment by TomAugspurger** [comment]
Yeah. We should update the docs to recommend conda-forge I think.

**Comment by jorisvandenbossche** [comment]
Would there be another way to specify this? 
(probably not with requirements.txt file? With environment.yml files I think you can specify the env?)

Because I don't fully like that we in that way somewhat enforce people to use the conda-forge channel (although I certainly recommend it as well), but there are still some incompatibilities between defaults and conda-forge.

**Comment by TomAugspurger** [comment]
> Would there be another way to specify this?

Yes, the `environment.yaml` file can contain a `channels` section.

**Comment by TomAugspurger** [comment]
More generally, we should think through the purpose of the various `requirements_*` files. I see a few use-caes:

- Someone wants to build pandas locally, with just the minimal deps (just our required dependencies + Cython)
- Someone wants to contribute to the docs (all build deps + doc deps)
- Someone wants to contribute to the codebase (all build deps + all test deps)
- Someone wants everything

Do we one one environment file for each of those? Are there any other use-cases? Conda environments can't do recursive includes (like `pip -r`), but I think that having some repetition is fine.

**Comment by jreback** [comment]
an easy way out of this is to make ``*.txt`` pip only and specify a ``.yml`` for the conda installs

**Comment by Dinh-Hung-Tu** [comment]
Hello everyone, I am new contributor to Pandas. In short, what should I do to solve the same problem stated in the first post?

**Comment by TomAugspurger** [comment]
`conda create -n pandas_dev python=3 -c conda-forge --file ci/requirements_dev.txt` should work for you.
