### ISSUE TITLE
numpy_helper.h alternatives

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#17551]
The build dependencies could be enormously simplified if we could remove the reliance of _libs/src/util.pxd on _libs/src/numpy_helper.h.  I've ported most of the functions directly to util.pxd, would like input on a few remaining ones.

```
PANDAS_INLINE PyObject* get_value_1d(PyArrayObject* ap, Py_ssize_t i) {
    char* item = (char*)PyArray_DATA(ap) + i * PyArray_STRIDE(ap, 0);
    return PyArray_Scalar(item, PyArray_DESCR(ap), (PyObject*)ap);
}
```

It looks like this just returns `ap[i]`.  Presumably more efficient in some way.  I'm guessing this was written before typed memoryviews were available in cython; there may be a less verbose plain-cython alternative available.

Alternatively, everything there except for `PyArray_DESCR` can cimported with a little effort.  If anyone knows of a way to get at this last piece, then both `get_value_1d` and `assign_value_1d` can be moved directly into `util`.

**Comment by chris-b1** [comment]
Typed memorviews won't be helpful, this code operates on a generic ndarray in python-land, regardless of dtype.

As you note, this is potentially performance sensitive stuff - it looks like the naive cython solution still has at least one layer of python indirection, though you'd have to follow the macro expansions to check for sure.
```
%%cython -a
cimport numpy as cnp

def get_1d(cnp.ndarray arr, Py_ssize_t i):
    return arr[i]

# generated code for
# arr[i]
__pyx_t_1 = __Pyx_GetItemInt(((PyObject *)__pyx_v_arr), __pyx_v_i, Py_ssize_t, 1, PyInt_FromSsize_t, 0, 1, 1);
```

So your best bet (other than leaving it alone, which might be perfectly acceptable!) is probably to wrap the `PyArray_DESCR` macro in cython.  Must be something strange with the refcount semantics on it, it is commented out in the cython includes with a comment to that effect.
https://github.com/cython/cython/blob/2c9641a749208dbc405209e367b8a23e1310564d/Cython/Includes/numpy/__init__.pxd#L411

**Comment by jbrockmendel** [comment]
Thanks for taking a look at this.  After diving into the numpy include files, I found a way to get at `PyArray_DESCR` and implement in cython:

```
cdef object get_value_1d(ndarray ap, Py_ssize_t i):
    cdef:
        char* item = <char*>PyArray_DATA(ap) + i * PyArray_STRIDE(ap, 0)
    return PyArray_Scalar(item, PyArray_DESCR(<PyArrayObject*>ap), ap)
```

The C code this generates is pretty verbose compared to the original:

```
static PyObject *__pyx_f_4pdsm_6tslibs_4util_get_value_1d(PyArrayObject *__pyx_v_ap, Py_ssize_t __pyx_v_i) {
  char *__pyx_v_item;
  PyObject *__pyx_r = NULL;
  __Pyx_TraceDeclarations
  __Pyx_RefNannyDeclarations
  PyObject *__pyx_t_1 = NULL;
  __Pyx_RefNannySetupContext("get_value_1d", 0);
  __Pyx_TraceCall("get_value_1d", __pyx_f[0], 188, 0, __PYX_ERR(0, 188, __pyx_L1_error));

  __Pyx_TraceLine(196,0,__PYX_ERR(0, 196, __pyx_L1_error))
  __pyx_v_item = (((char *)PyArray_DATA(__pyx_v_ap)) + (__pyx_v_i * PyArray_STRIDE(__pyx_v_ap, 0)));

  __Pyx_TraceLine(198,0,__PYX_ERR(0, 198, __pyx_L1_error))
  __Pyx_XDECREF(__pyx_r);
  __pyx_t_1 = PyArray_Scalar(__pyx_v_item, PyArray_DESCR(((PyArrayObject *)__pyx_v_ap)), ((PyObject *)__pyx_v_ap)); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 198, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_1);
  __pyx_r = __pyx_t_1;
  __pyx_t_1 = 0;
  goto __pyx_L0;
```

I'm kind of surprised that the verbatim version is so much more complicated than the version generated from `return arr[i]`.

> So your best bet (other than leaving it alone, which might be perfectly acceptable!)

Leaving it alone is likely the smart thing to do.  There have been a few recent threads regarding setup.py build dependencies.  I'm increasingly interested in minimizing the points of contact with non-.pyx files.

**Comment by chris-b1** [comment]
I think most of that generated code is line-tracing / profiling stuff.

**Comment by jbrockmendel** [comment]
src/headers/math.h looks like it exist to define `signbit` on Windows (really guessing here).  Is the version [baked in ](https://github.com/cython/cython/blob/master/Cython/Includes/libc/math.pxd)to cython not compatible?  That is accessible with `from libc.math cimport signbit`.

Similarly, if there is any chance that `compat_helper.h` or `helper.h` are no longer needed in this modern era of wonders, that would make my day.

**Comment by chris-b1** [comment]
Yeah, unfortunately that `math.h` shim and others are necessary to support Windows with python 2.7 - it is stuck using an old MSVC that has incomplete C99 support (e.g. no `stdint.h`).  The situation with modern MSVCs and  python 3 is much better, but nothing that can be done while we support 2.
https://www.microsoft.com/en-us/download/details.aspx?id=44266

```python
%%cython
from libc.math cimport signbit
def f(double v):
    return signbit(v)

error LNK2019: unresolved external symbol signbit referenced in function  __pyx_...
```

**Comment by jbrockmendel** [comment]
I'll run out of these before long...

1) What about src/numpy.pxd?  That file appears to be a (slightly out of date) duplicate of the version baked into cython.  `np.get_include()` is added to the `include_dirs` arg in setup.py in a wasn't-obvious-to-me way; it would be nice to disambiguate the different numpy inclusions.

2) Is the 3.6.1 issue described in compat_helper expected to be reverted at some point?

3) Is the definition of PANDAS_INLINE in skiplist.h redundant with helper.h?

BTW the reason I'm interested in reducing non-cython (aside from making the build less fragile) is the hopes of getting `Cython.Coverage` working.

**Comment by jbrockmendel** [comment]
From `_libs.window.pyx`:

```
cdef extern from "../src/headers/math.h":
    double sqrt(double x) nogil
    int signbit(double) nogil
```
Is that path right?  Is the ".." relative to the window.pyx file or something else?

**Comment by jbrockmendel** [comment]
Are the `libc.math` [bindings](https://github.com/cython/cython/blob/master/Cython/Includes/libc/math.pxd) provided by cython not portable?  (`signbit` is down at the bottom of that page.)

**Comment by chris-b1** [comment]
Answering the ones I know offhand

> Is the 3.6.1 issue described in compat_helper expected to be reverted at some point?

Would have to ref back to the original issue, but I believe this is fixed in 3.7.  But as long as we support 3.6 I believe it has to stay in to keep ABI compat across minor versions - in other words the wheels we build will work in any variation of 3.6.

> Are the libc.math bindings provided by cython not portable? (signbit is down at the bottom of that page.)

They are "portable" in the sense they work on any platform with a libc that provides those function, but entirely dependent on the libc.  C-extensions with Python 2.7 on Windows have a specific toolchain requirement (the MSVC 2008 I linked above) which doesn't provide that function.

**Comment by jbrockmendel** [comment]
util.pxd "imports" ("externs"?) `floatify` from numpy_helper.h, but I don't think floatify exists there.  AFAICT it is defined in parse_helper.h, and is externed into inference.pyx.  Wouldn't this cause a segfault if someone tried to access util.floatify?  Is this OK for a reason I'm missing?

**Comment by jbrockmendel** [comment]
Last one for today.  numpy_helper.h defines `get_timedelta64_value`:

```
PANDAS_INLINE npy_timedelta get_timedelta64_value(PyObject* obj) {
    return ((PyTimedeltaScalarObject*)obj)->obval;
}
```

After some tinkering, this function can be declared directly in cython:

```
cdef inline npy_timedelta get_timedelta64_value(PyObject* obj) nogil:
    return (<PyTimedeltaScalarObject*>obj).obval
```

and cythonizing produces the following C:

```
static CYTHON_INLINE npy_timedelta __pyx_f_4pdsm_6tslibs_9npy_dtime_get_timedelta64_value(PyObject *__pyx_v_obj) {
  npy_timedelta __pyx_r;
  __pyx_r = ((PyTimedeltaScalarObject *)__pyx_v_obj)->obval;
  goto __pyx_L0;
  /* function exit code */
  __pyx_L0:;
  return __pyx_r;
}
```

The cython-produced C is clearly more verbose than the numpy_helper version.  But is that cruft meaningful or does the compiler render the two versions equivalent?  If there is literally zero performance hit, then there is some upside to using the cython implementation.

**Comment by chris-b1** [comment]
Yes that likely compiles identically.  That said, only a matter of taste, but I actually find the c version as or more clear - cython isn't being used to any of its strengths (handling refcounts, translating to c-api calls) so not sure there's much benefit in moving it?

**Comment by jbrockmendel** [comment]
You're almost certainly right that leaving it alone is the best option.  The upsides that I have/had in mind are:

- cython handles dependencies and re-compiling internally, so the `depends`/`pxdfiles`/`sources`/`include` complexity/confusion in `setup.ext_data` could be reduced if pyx files had no non-pyx dependencies.

- Suppose hypothetically you wanted to build/test part of `_libs` in isolution (in my case `_libs.tslibs`).  Right now its a hassle.  It would be much easier if all the deps were cython.

- It would be really nice to get test coverage for `_libs`.  I haven't had much luck getting the Cython.Coverage plugin to work as advertised, but plan to put some time into it before long.

- As cython's pure-python mode becomes more compatible, flake8 and other tooling become viable for cython modules.

The questions here have been pretty thoroughly answered.  I appreciate it.  Feel free to close.
