### ISSUE TITLE
API: Deprecate Categorical fastpath argument

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#17562]
After https://github.com/pandas-dev/pandas/pull/16015 the `fastpath` argument to the Categorical constructor is unnecessary since you can skip the categorical validation by passing in a `CategoricalDtype`.l

**Comment by kaichogami** [comment]
Hi, I would like to work on this.

**Comment by TomAugspurger** [comment]
Cool. The argument is [here](
https://github.com/pandas-dev/pandas/blob/7e159aeec1d5d2e79311ca688c0e594f0fd5f709/pandas/core/categorical.py#L245).
You'll want to warn when it's used, and tell people to use a
CategoricalDtype.

The trickier part will be finding all the places the argument is currently
used, and pass or construct an instance of a `CategoricalDtype` there
instead.

**Comment by jreback** [comment]
closing in favor of #20110
