### ISSUE TITLE
DOC: Add a section on future 'whatsnew' files for documentation contributions

### ISSUE THREAD

**Issue by willingc** [pandas-dev/pandas#17601]
In PR #17580, there has been discussion on adding a section at the end of future 'whatsnew' files for "Documentation". Adding a section like this will encourage and recognize contributors to the documentation.

**Comment by jreback** [comment]
This is fine. We can put bigger changes here. We had been putting these in Other Enhancements, can just redirect them to Documentation.

@willingc can you add the whatsnew in #17580 & see if any existing notes (for 0.21.0 only) should be moved to that sub-section. 

Then can close this issue with that PR as well.

**Comment by TomAugspurger** [comment]
From https://github.com/pandas-dev/pandas/pull/17580#issuecomment-330510789

> My thoughts are
> 
> Pros:
> 
> pixels are cheap. Having more items in the whatsnew isn't a bad thing
> Contributors get to see their work reflected in the release notes
> Emphasizes that we value doc contributions, they don't have special rules
> Cons:
> 
>The whatsnew is a common source of merge conflicts, which can be tough for new contributors > (but we maintainers can handle them in the web UI with little difficulty, so not a big problem)
> Overall a 👍 from me

Only thing to add is that I'm like +100 on this, not just +1 :)

**Comment by gfyoung** [comment]
> Only thing to add is that I'm like +100 on this

@TomAugspurger : So you're really +101? ;)

Such passionate favoring of a proposal!
