### ISSUE TITLE
TST: Travis 3.6 Job Failing Across Multiple PR's

### ISSUE THREAD

**Issue by gfyoung** [pandas-dev/pandas#17617]
https://travis-ci.org/pandas-dev/pandas/jobs/278263195
https://travis-ci.org/pandas-dev/pandas/jobs/278232682

These are a couple of examples.  Seems like `numpy` is not compatible for some strange reason.

**Comment by jreback** [comment]
conda forge appears to have updated the numpy build ; i think other deps need updating (iow anything that depends on numpy)

you can check in there recently merged PR list to see

**Comment by gfyoung** [comment]
Hmm...`numpy` hasn't made a new release since July...that's pretty late to update on `conda`.

**Comment by jorisvandenbossche** [comment]
Isn't this is something we rather should report to conda-forge instead of that 'fix' ? (which can certainly be done temporarily) 
As conda should not just downgrade numpy?

**Comment by jreback** [comment]
no its not really conda-forge's issue. its the downstream packages that should update. and we use quite a lot of these (e.g. numexpr, pytables, pyarrow, netcdf4, matplotlib, statsmodels, bottleneck). IOW anything that specifically targets the ABI (like pandas does).

Whenever a new ABI version (or version), then the downstreams need to pin. Sure you can 'report' it if you want. I am going to temporarily pin to make our builds work (and will revert at some later point).
