### ISSUE TITLE
Add teardowns in asv benchmarks

### ISSUE THREAD

**Issue by louispotok** [pandas-dev/pandas#17616]
Per @jreback's comment [here](https://github.com/pandas-dev/pandas/pull/17168/files/f0089d14f219c302ab62af41c50218704d87d4fb#r139321194), we should have teardowns in asv benchmarks, especially in IO benchmarks where we are creating files.

**Comment by jreback** [comment]
to be clear, its mainly the io benchmarks or anything that generates an on-disk artifact.

**Comment by brychlicki-reef** [comment]
The [comment above](https://github.com/pandas-dev/pandas/issues/17616#issue-259582123) references [dead link](https://github.com/pandas-dev/pandas/pull/17168/files/f0089d14f219c302ab62af41c50218704d87d4fb#r139321194). 
So I spent some time familiarizing myself with the [original issue](https://github.com/pandas-dev/pandas/pull/17168) and looking for the comment that triggered this issue. [Found it](https://github.com/pandas-dev/pandas/pull/17168#discussion_r139321194), leaving as back reference. 

A PR for this is on its way from us.

**Comment by jreback** [comment]
@brychlicki-reef thanks! that would be great

**Comment by prudhv16** [comment]
if any one working on it, else could I try this please ?

**Comment by brychlicki-reef** [comment]
@prudhv16 
Hi, we have the code ready, it just waits for internal code review before sending, so that'd be a waste :), I'd rather you didn't

**Comment by prudhv16** [comment]
thank you very much @brychlicki-reef , I will try to find some easy one and try contributing to pandas.
