### ISSUE TITLE
wide_to_long does not convert integer suffixes to int

### ISSUE THREAD

**Issue by tdpetrou** [pandas-dev/pandas#17627]
#### Code Sample, a copy-pastable example if possible

```python
>>> df = pd.DataFrame({
                'A_1': [1.0, 2.0],
                'A_2': [3.0, 4.0],
                'X': ['X1', 'X2']})

   A_1  A_2   X
0  1.0  3.0  X1
1  2.0  4.0  X2

>>> df2 = pd.wide_to_long(df, stubnames='A', i='X', j='num', sep='_')
          A
X  num     
X1 1    1.0
X2 1    2.0
X1 2    3.0
X2 2    4.0

>>> df2.reset_index().dtypes
X       object
num     object
A      float64
dtype: object
```
#### Problem description

`wide_to_long` should attempt to coerce integer strings to ints. I have a pull request ready for this.

Additionally, I'd think it might be good to deprecate `wide_to_long` and `lreshape` in favor of expanded `melt` functionality.

#### Expected Output
```
>>> df2.reset_index().dtypes
X       object
num     int64
A      float64
dtype: object
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Darwin
OS-release: 15.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.20.3
pytest: 3.0.7
pip: 9.0.1
setuptools: 35.0.2
Cython: 0.25.2
numpy: 1.13.1
scipy: 0.19.0
xarray: None
IPython: 6.0.0
sphinx: 1.5.5
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.0
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.7
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.3
bs4: 4.6.0
html5lib: 0.9999999
sqlalchemy: 1.1.9
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: 0.3.0.post
</details>

**Comment by jreback** [comment]
xref https://github.com/pandas-dev/pandas/issues/15003

**Comment by jreback** [comment]
cc @TomAugspurger 

seems reasonble.

**Comment by tdpetrou** [comment]
One other thing...if the suffixes are floats and not ints, we could try to cast them to floats as well.
