### ISSUE TITLE
CategoricalDtype follows after #16015

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#17635]
- use ``display.max_categories`` in ``CagetegoricalDtype.__unicode__`` [here](https://github.com/pandas-dev/pandas/pull/16015/files#r140619601)
- use ``display.max_categories`` in ``Categorical.__unicode__``
- deprecate usage of ``fastpath`` in ``Categorical`` constructor (#17562)
- deprecate ``.astype(..., categories=)`` in favor of ``CategoricalDtype`` (https://github.com/pandas-dev/pandas/issues/17636)
- move hash type routines to ``hashing.py`` [here](https://github.com/pandas-dev/pandas/pull/16015/files#r137931284)
- validate that pyarrow is compat with changes

**Comment by jreback** [comment]
@TomAugspurger

**Comment by jreback** [comment]
cc @wesm 

I don't think pyarrow will be impacted by this; it is possible that knowing the categories upfront could be helpful though

**Comment by wesm** [comment]
I don't think it would be, but we should check anyway and see if there's any perf improvement opportunities

**Comment by mroeschke** [comment]
Looks like most of the associated issues are closed. Can open specific issues if there are specifics that were missed
