### ISSUE TITLE
BUG: overflow in Timedelta arithmetic

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#17637]
xref https://github.com/pandas-dev/pandas/pull/17318#issuecomment-331594273

This is not behaving on master, started after: https://github.com/pandas-dev/pandas/commit/b59f107a529ac9b1e2859217ea58f7e26b6749d0
```
In [1]: date_range(start='1/1/1700', freq='B', periods=100000)
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
OverflowError: Python int too large to convert to C long
Exception ignored in: 'pandas._libs.tslib._delta_to_nanoseconds'
OverflowError: Python int too large to convert to C long
Out[1]: DatetimeIndex(['1700-01-01', '1700-01-04', '1700-01-05', '1700-01-06', '1700-01-07'], dtype='datetime64[ns]', freq='B')

```

**Comment by jbrockmendel** [comment]
A sufficient condition to fix this particular error:

1) Revert `cpdef int64_t _delta_to_nanoseconds(delta):` --> `def _delta_to_nanoseconds(delta):`  (with or without cpdef, shouldn't matter)
2) In `_Timestamp.__add__` don't declare a type for `nanos`
3) Open an issue for a longer-term solution.

**Comment by jreback** [comment]
@jbrockmendel its actually much simpler than that.

3) there isn't really a good long term soln.

**Comment by jreback** [comment]
> 2. In _Timestamp.__add__ don't declare a type for nanos

not realistic, you *want* to declare types for things as you  actually want the overflow

**Comment by jbrockmendel** [comment]
> there isn't really a good long term soln. well there is, multi-unit timedelta types, but that is quite a lot of work and will have to wait for pandas2.

Yah.  I've spent enough time with np_datetime.c to know that numpy has implemented multi-unit datetime64, haven't looked at their timedelta64 implementation that closely.  I'll check if they've got anything that can be adapted.

**Comment by jreback** [comment]
There are actually 2 issues:

1) support multi-units (e.g. [s]) based Timedeltas. 
2) properly cast when overflowing (then cast back)

these are both useful but non-trivial.
