### ISSUE TITLE
DataTypeWarning: Unsupported type for attribute 'DIMENSION_LIST' in node 'd_lon'. Offending HDF5 class: 9

### ISSUE THREAD

**Issue by weiji14** [pandas-dev/pandas#17661]
#### Code Sample

```python
import os
import pandas as pd
h5file = os.path.join(os.getcwd(), "GLAH12_634_1102_001_0071_0_01_0001.H5")
tables.is_hdf5_file(h5file)
pd.read_hdf(h5file, key='/Data_40HZ/Geolocation/d_lon')
```
#### Problem description

pandas.read_hdf fails when the HDF5 file has a node with a user defined attribute that is of `None` type. Below is the capture from ViTables of the problematic user attribute.

![screenshot at 2017-09-25 13 36 12](https://user-images.githubusercontent.com/23487320/30788307-a7a83d96-a1f6-11e7-93a8-63377a485879.png)

Links to the code error points to:
- [pytables.py](https://github.com/pandas-dev/pandas/blob/3a7f956c30528736beaae5784f509a76d892e229/pandas/io/pytables.py#L728)
- [attributeset.py](https://github.com/PyTables/PyTables/blob/c71a525d5a8d643a57091a4f3ed51ddccd6b8f9a/tables/attributeset.py#L299)

```
/home/atom/.local/lib/python3.5/site-packages/tables/attributeset.py:299: DataTypeWarning: Unsupported type for attribute 'DIMENSION_LIST' in node 'd_lon'. Offending HDF5 class: 9
  value = self._g_getattr(self._v_node, name)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-73d62d05a23a> in <module>()
----> 1 pd.read_hdf(h5file, key='/Data_40HZ/Geolocation/d_lon')

~/.local/lib/python3.5/site-packages/pandas/io/pytables.py in read_hdf(path_or_buf, key, mode, **kwargs)
    370                                      'contains multiple datasets.')
    371             key = candidate_only_group._v_pathname
--> 372         return store.select(key, auto_close=auto_close, **kwargs)
    373     except:
    374         # if there is an error, close the store

~/.local/lib/python3.5/site-packages/pandas/io/pytables.py in select(self, key, where, start, stop, columns, iterator, chunksize, auto_close, **kwargs)
    726         # create the storer and axes
    727         where = _ensure_term(where, scope_level=1)
--> 728         s = self._create_storer(group)
    729         s.infer_axes()
    730 

~/.local/lib/python3.5/site-packages/pandas/io/pytables.py in _create_storer(self, group, format, value, append, **kwargs)
   1220                 else:
   1221                     raise TypeError(
-> 1222                         "cannot create a storer if the object is not existing "
   1223                         "nor a value are passed")
   1224             else:

TypeError: cannot create a storer if the object is not existing nor a value are passed
```

#### Expected Output
HDF5 file loads into a pandas DataFrame without any errors. Or there should be a way to bypass/ignore the problematic user attribute since it is a metadata issue only.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.4.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-96-generic
machine: x86_64
processor: 
byteorder: little
LC_ALL: C.UTF-8
LANG: C.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.20.3
pytest: None
pip: 9.0.1
setuptools: 36.5.0
Cython: None
numpy: 1.13.1
scipy: 0.19.1
xarray: 0.9.6
IPython: 6.2.0
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None

</details>

#### Attached HDF5 file:
[GLAH12_634_1102_001_0071_0_01_0001.H5.zip](https://github.com/pandas-dev/pandas/files/1327908/GLAH12_634_1102_001_0071_0_01_0001.H5.zip)

**Comment by jreback** [comment]
how was this file created?

this is not a pandas issue. it might be for pytables.
