### ISSUE TITLE
as_block depr warning on tab completion

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#17674]
```
In [13]: df = pd.Series([1, 2, 3])

In [14]: df.<TAB>
/Users/taugspurger/Envs/pandas-dev/lib/python3.6/site-packages/pandas/pandas/core/generic.py:3720: FutureWarning: as_blocks is deprecated and will be removed in a future version
  return self.as_blocks()
```

This came up before in https://github.com/pandas-dev/pandas/issues/16409 and the fix is in https://github.com/pandas-dev/pandas/pull/16414

**Comment by jreback** [comment]
hmm easy enough to remove deprecated functions from the __dir__ entirely (this is what _dir_deletions does)
