### ISSUE TITLE
Inherited DataFrame Class crashes on .append()

### ISSUE THREAD

**Issue by VDFaller** [pandas-dev/pandas#17699]
#### Code Sample, a copy-pastable example if possible

```python
class Test(pd.DataFrame):
    def __init__(self):
        super().__init__(columns=["A", "B"])
df = Test()
df2 = Test()
df.loc[0] = [1, 2.4]
df2.append(df)


```
#### Problem description

When I try to inherit a dataFrame, it makes it so I'm unable to append it.  
It Crashes with 

Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-66-97a561a127ae>", line 1, in <module>
    df2.append(df)
  File "F:\Anaconda3\lib\site-packages\pandas\core\frame.py", line 4645, in append
    verify_integrity=verify_integrity)
  File "F:\Anaconda3\lib\site-packages\pandas\core\reshape\concat.py", line 207, in concat
    return op.get_result()
  File "F:\Anaconda3\lib\site-packages\pandas\core\reshape\concat.py", line 412, in get_result
    return (cons._from_axes(new_data, self.new_axes)
  File "F:\Anaconda3\lib\site-packages\pandas\core\generic.py", line 332, in _from_axes
    return cls(data, **kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.20.1
pytest: 3.0.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 5.3.0
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.2.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.7
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.3
bs4: 4.6.0
html5lib: 0.999
sqlalchemy: 1.1.9
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None

**Comment by TomAugspurger** [comment]
Did you see the docs at http://pandas.pydata.org/pandas-docs/stable/internals.html#subclassing-pandas-data-structures?

**Comment by jreback** [comment]
read the big red warning box in the docs: http://pandas.pydata.org/pandas-docs/stable/internals.html#subclassing-pandas-data-structures

your init method is wrong

**Comment by VDFaller** [comment]
Crap.  Thanks.
