### ISSUE TITLE
ERR: Timestamp.__new__ accepts both tz and tzinfo

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#17690]
Why are there separate tz and tzinfo kwargs?  The following is not intuitive:

```
In [12]: pd.Timestamp('2017-09-25 21:23', tz='US/Eastern')
Out[12]: Timestamp('2017-09-25 21:23:00-0400', tz='US/Eastern')

In [13]: pd.Timestamp('2017-09-25 21:23', tzinfo='US/Eastern')
Out[13]: Timestamp('2017-09-25 21:23:00')
```

**Comment by jreback** [comment]
``tzinfo`` is the kw that ``datetime.datetime`` accepts. ``tz`` is much more inuitive (as its a string).

[13] ``tzinfo`` is invalid (so maybe should check this).

**Comment by jbrockmendel** [comment]
I'd be OK with a "well the user clearly intended..." approach or a raising approach, but don't like silently ignoring the input.

**Comment by jreback** [comment]
yeah this need some internal conversion.

**Comment by jbrockmendel** [comment]
Any preference between the raise for accept-when-unambiguous?  I lean slightly towards the latter.

**Comment by jreback** [comment]
tzinfo as a string is plain wrong and should raise
