### ISSUE TITLE
Revert "CI: Pin miniconda version"

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#17696]
https://ci.appveyor.com/project/pandas-dev/pandas/build/1.0.5024/job/vpdwnlx9je8a4sfw#L1273

https://travis-ci.org/pandas-dev/pandas/jobs/280513252#L1377

We want to revert #17700 pinning miniconda

We want to keep

- https://github.com/pandas-dev/pandas/pull/17700/commits/7bc883edf10370b2e2c227cac14dbceba4c6420e
- https://github.com/pandas-dev/pandas/pull/17700/commits/a33d078c96a8613b03222c893a8d747fbf2ad04b

The bzip2 conda package that started this has been fixed by a new build.

The only remaining issue should be the gcc that's picked up on linux. I'll keep an eye on https://github.com/conda/conda/issues/6030

**Comment by TomAugspurger** [comment]
[This](https://travis-ci.org/pandas-dev/pandas/jobs/280513252#L1388) warning is strange. Shouldn't that be an exception?

**Comment by jreback** [comment]
why would these be showing up now?

**Comment by TomAugspurger** [comment]
No idea. A new anaconda distribution was released today, which shouldn't directly affect us, but maybe a package update? I'm asking around internally to see if anyone knows what's up.

**Comment by jreback** [comment]
this is not an issue with bzip2
rather i think it's a new version of pytables

we have a default which i think just changed

**Comment by jorisvandenbossche** [comment]
> A new anaconda distribution was released today

I see in the changelog of Anaconda 5 that `libgccy` has been removed (which may be related)
