### ISSUE TITLE
TST: PR Test Builds Breaking Everywhere

### ISSUE THREAD

**Issue by gfyoung** [pandas-dev/pandas#17702]
https://travis-ci.org/pandas-dev/pandas/jobs/280745119

https://circleci.com/gh/pandas-dev/pandas/5103#tests/containers/2

https://ci.appveyor.com/project/pandas-dev/pandas/build/1.0.5046/job/rqh23ca31uaj8bih

Looks like some weird `gcc` error.  Anyone know what's going on with that?

xref #17696

**Comment by gfyoung** [comment]
@TomAugspurger : Does #17700 address this by any chance?

**Comment by TomAugspurger** [comment]
Yep, #17700 puts a temporary fix in.
