### ISSUE TITLE
pandas.core.window.EWM axis attribute is not used when cov()/corr() is called

### ISSUE THREAD

**Issue by QuentinLewes** [pandas-dev/pandas#17701]
I got a DataFrame `dff`, its shape 5×4 stands for 5 items and 4 days. I created a EWM `ewmm` and got EW moving average.

When it comes to correlation and covariance, a 4×5×5 shaped matrix is what I expected, but the result is shaped 5×4×4.

```python
In[59]: dff
Out[59]: 

   0  1  2  3
0  1  2  3  4
1  4  3  2  1
2  3  1  4  1
3  5  9  2  6
4  1  2  3  4
In[60]: ewmm = dff.ewm(span=2, axis=1)
In[61]: ewmm.mean()
Out[61]: 

     0     1         2      3
0  1.0  1.75  2.615385  3.550
1  4.0  3.25  2.384615  1.450
2  3.0  1.50  3.230769  1.725
3  5.0  8.00  3.846154  5.300
4  1.0  1.75  2.615385  3.550
In[62]: ewmm.corr()
Out[62]: 

<class 'pandas.core.panel.Panel'>
Dimensions: 5 (items) x 4 (major_axis) x 4 (minor_axis)
Items axis: 0 to 4
Major_axis axis: 0 to 3
Minor_axis axis: 0 to 3
In[63]: ewmm.cov()
Out[63]: 

<class 'pandas.core.panel.Panel'>
Dimensions: 5 (items) x 4 (major_axis) x 4 (minor_axis)
Items axis: 0 to 4
Major_axis axis: 0 to 3
Minor_axis axis: 0 to 3

```
#### Problem description

https://stackoverflow.com/a/46461806/7012118

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Windows
OS-release: 8.1
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.2
setuptools: 32.3.1
Cython: 0.24.1
numpy: 1.11.3
scipy: 0.18.1
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.4.6
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.6.1
blosc: None
bottleneck: 1.1.0
tables: 3.2.2
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.3
lxml: 3.6.4
bs4: 4.5.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: 0.7.9.None
psycopg2: None
jinja2: 2.8
boto: 2.42.0
pandas_datareader: 0.3.0.post
</details>

**Comment by jreback** [comment]
you need a copy-pastable example.

**Comment by jreback** [comment]
and you are using a pretty old version. current is 0.20.3
