### ISSUE TITLE
Accept dictionaries for mapping categories in Categorical Data

### ISSUE THREAD

**Issue by robertour** [pandas-dev/pandas#17719]
I am importing data that comes from other tools (SPSS, Excel) that handles categories, and these categories are represented by dictionary-like structures. Say, a column `Rate` would accept the following categories:

    valuelabels = {
        1 :  'High',
        2 :  'Medium',
        3 : 'Low',
        99999 : 'No idea',
    }

I would like to create a pandas `category` column that matches not only the `labels` (i.e. `'High'`, `'Good'`, ...), but also the `ids`, so that I could easily export back to the source format without reassigning ids (to be sure, I can do this by keeping external structures and such, but I think that this could be an improvement to pandas).

 A current possibility would be doing the following:

    values_of_column = [1,99999,3,1] # would correspond to 'High', 'No Idea', 'Low', 'High'
    labels = ['dummy0']  + ['Hight','Medium','Low'] + [ f'dummy{i}' for i in range(4,99999)] + ['No idea']
    s = pd.Series(pd.Categorical.from_codes( values_of_column , categories= labels ))

The above  is simply ugly, and unfortunately not enough, as I have already seen value labels with negative numbers:

    value_labels = {
        -999: 'n/a',
        -99: 'No answer',
        1 :  'High',
        2 :  'Medium',
        3 : 'Low',
        99999 : 'No idea',
    }

I can image other cases (tools different from SPSS) in which there is strings in both sides of the dictionary, say something like

    value_labels = {
        'a' : 'answer a',
        'b' : 'answer b',
        'no_answer': 'Doesn't know/Doesn't answer'
    } 

Ideally, using the last example, I would like to have the possibility of using the dictionaries directly:

   s = pd.Series(pd.Categorical.from_codes( ['a','b','no_answer','b'], categories=value_labels))

Given the 1:1 nature of this relation, *this could also be refined in order to have some dual representation of values, specially when one is dealing with similar data from different sources*. For example, one database use the 2 letter ISO country representation (e.g. 'US') and another 3 letter ISO country representation (e.g. 'USA').

**Comment by TomAugspurger** [comment]
I think your first example, under "A current possibility...", is incomplete?  IIUC, you want something like

```python
In [26]: values = ['High'] * 40 + ['Medium'] * 10 + ['Low'] * 5 + ['No idea'] * 5

In [27]: pd.Categorical(values)
Out[27]:
[High, High, High, High, High, ..., No idea, No idea, No idea, No idea, No idea]
Length: 60
Categories (4, object): [High, Low, Medium, No idea]
```

Two thoughts:

Having `categories` be a dict-like structure doesn't fit with how pandas represents them currently. I don't see a clean way of doing both.

For your `value_labels`, it seems like you have multiple values of "missing". Pandas has a single value for nulls, and for categoricals they're coded as -1. I think users should normalize their data before category encoding it.

> I can do this by keeping external structures and such, but I think that this could be an improvement to pandas

This seems OK to me. In my mind you would have a sandwich of

External dictionary -> pandas Categorical -> operations -> Export

**Comment by robertour** [comment]
> I think your first example, under "A current possibility...", is incomplete?

I missed the seconde parameter in `s = pd.Series(pd.Categorical.from_codes( values_of_column , categories= labels ))` (I corrected it now).

> For your value_labels, it seems like you have multiple values of "missing". Pandas has a single value for nulls, and for categoricals they're coded as -1. I think users should normalize their data before category encoding it.

I think so too, but unfortunately real life projects don't allow me to convince all ppl around me to keep things so consistently. They would insist that there is differences between 'no answer' and "doesn't apply"

> External dictionary -> pandas Categorical -> operations -> Export

That would be incomplete:

External dictionary -> pandas Categorical -> operations -> inverse dictionary > Export

The issue is that the users want to see the same ids for the codes, before and after the procedure, if 99999 means 'No Idea'; they want to see both, 'No Idea' (text) and 99999 (code). To be fair, some of the keep the 99999 accross projects and files, so it wouldn't be OK for me to just change it. 

Note that the above pipeline, i.e. External dictionary -> pandas Categorical -> operations -> inverse dictionary > Export, involves iterating over the data 3 times. If pandas would accept dictionaries, the conversion could be straight forward.

Finally, I would like to reiterate my last point: Given the 1:1 nature of this relation, this could also be refined in order to have some dual representation of values, specially when one is dealing with similar data from different sources. For example, one database use the 2 letter ISO country representation (e.g. 'US') and another 3 letter ISO country representation (e.g. 'USA').

**Comment by TomAugspurger** [comment]
Hmm, could you check your example again?

```python
values_of_column = [1,99999,3,1] # would correspond to 'High', 'No Idea', 'Low', 'High'
labels = ['dummy0']  + ['Hight','Medium','Low'] + [ f'dummy{i}' for i in range(4,99999)] + ['No idea']
s = pd.Series(pd.Categorical.from_codes( values_of_column , categories= labels ))
```

Seems strange since you end up with 4 values, but 100,000 categories. Typically the number of values is large, and the categories small.

> The issue is that the users want to see the same ids for the codes, before and after the procedure, if 99999 means 'No Idea'; they want to see both, 'No Idea' (text) and 99999 (code)

Who's the user here? Excel / SPSS users, or pandas? Pandas users don't get any control over the codes really, so I'll assume excel.

> ... involves iterating over the data 3 times.

I'm probably misunderstanding then. Once you have the data in a Categorical, I think you'd just be manipulating categories, which is fast.

Perhaps you could show an example with two datasets

```
data1 = 'country\nUSA\nUSA\nUSA\nAUS\nAUS\nAUS'
data2 = 'country\nUS\nUS\nUS\nAU\nAU\nAU'
df1 = pd.read_csv(StringIO(data1), dtype='category')
df2 = pd.read_csv(StringIO(data2), dtype='category')
```

What kind of operations are you hoping to do?

**Comment by robertour** [comment]
> Seems strange since you end up with 4 values, but 100,000 categories. 

I guess that is what I called ugly :). You can put as many values as you want in the example:

    values_of_column = [1,99999,3,2,1,1,2,2,2,1] # would correspond to 'High', 'No Idea', 'Low', 'High'
    labels = ['dummy0']  + ['Hight','Medium','Low'] + [ f'dummy{i}' for i in range(4,99999)] + ['No idea']
    s = pd.Series(pd.Categorical.from_codes( values_of_column , categories= labels ))

However, even if you add 1 000 000 values, you will end with only using 4 categories out of 100000. Notice that in order to add `['No idea']` with the code `99999`, I need to insert a lot of dummy values [ `f'dummy{i}' for i in range(4,99999)] `. 

To be sure, I am not doing the above (it would be just the possibility if I want to avoid the conversions of formats, hence I am also proposing the idea). I use an alternative to this, which is creating an inverse dictionary:

    >>> value_labels = {
        1 :  'High',
        2 :  'Medium',
        3 : 'Low',
        99999 : 'No idea',
    }
    >>> labels_values = { v: k for k, v in value_labels}
    labels_values = {
        'High': 1,
        'Medium': 2,
        'Low' : 3,
        'No idea' : 99999,
    }

Now let's say that `value_labels` and `values_of_columns` come from somewhere else (SPSS, Excel, or SQL - in SQL, 99999 could be a primary key in another table). Then, I do something like the following:

    value_labels = {1 :  'High', 2 :  'Medium',3 : 'Low',99999 : 'No idea',}
    values_of_column = [1,99999,3,2,1,1,2,2,2,1]
    labels_of_columns = [ value_labels[i] for i in values_of_column ]

    # Iteration 1: (usually I would be reading directly from the source, e.g. excel file)
    df = DataFrame(labels_of_columns,columns=['Rate'])

    # Iteration 2: replace the values (e.g. 99999) with the labels (e.g. 'No idea')
    df.replace({'Rate': value_labels})

    # Iteration 3: let pandas do the categories
    df["Rate"] = df["Rate"].astype('category')

    # operations; some could involve the use of the indeces (i.e. 999999)
    # an others the use of the strings (i.e. 'No idea')

    # And now save the dataframe back to the original source

    # Reverse the dictionary
    label_values = { v: k for k, v in value_labels}

    # Iteration 4: go back to the initial column made out of values
    df.replace({'Rate': label_values})

I actually needed 4 iterations (but one may be ignored as it corresponds to reading the file). In any case, I am looking to do something like:

    df = DataFrame(values_of_columns,columns=['Rate'])
    df['Rate'].as_category_using_dictionary(value_labels)

Internally, the dataframe would use the value_labels for the dual representation that it currently does with a list. In theory, there wouldn't be any need to iterate over the rows. In practice, it might be important to make sure that the dictionary `value_labels` does contain all the possible values, e.g. make sure that the value 99999 in `values_of_columns` exists in `value_labels`.

> Who's the user here? Excel / SPSS users, or pandas? Pandas users don't get any control over the codes really, so I'll assume excel.

The user is somebody to ask me to do complex operation in an SPSS/Excel file (presumably complicated to perform in those tools, or requiring a lot of clicks and they want it automatized). They, for example, want a new column based on others. I typically read the file, do the operation (based on some categorical columns) and save the file with the new column without affecting the current content of the file. This varies across formats: in SPSS there is the metadata associated to the column; in R, levels/factors; in Excel; usually other sheets; in SQL, primary keys to other tables.

The operations that the user needs could also involve using the values, i.e. 99999, or/and the labels, i.e. 'No idea'. The values can be associated to other tables (easier if you think in terms of SQL primary keys, although not necessarily the case), and the labels are string that might be used in the constructions of new columns. For some columns, I need the values, for others, the labels.

> I'm probably misunderstanding then. Once you have the data in a Categorical, I think you'd just be manipulating categories, which is fast.

Yes, this is a good idea! Now that I think about it, I could use this to create a better solution than my inverse dictionaries, meaning, saving iterations. However, this would also involve a tricky creation of consistent lists that matches the pandas indexes. 

IMHO, category columns depending on dictionaries seems a more intuitive and flexible approach than the current list index, which restricts the values to be ordered and continuing indexes that corresponds to entries in a list.

**Comment by robertour** [comment]
I recently improved some of the code by using an special implementation of a sparse list (based on [this](https://pypi.python.org/pypi/sparse_list) ). Internally, the sparse has a dictionary with the existent index-valuess that returns a default value (usually None) when the index list doesn't exist. In my case, I modify the implementation to return a unique dummy value (e.g. 'dummy_1') when there is no code-label ([L31](https://github.com/robertour/python_sparse_list/blob/master/sparse_list.py#L31) and [L61](https://github.com/robertour/python_sparse_list/blob/master/sparse_list.py#L61)).

This doesn't solve yet the problem with negative codes (or strings) as pandas restrict the values between -1 to len(categories). The current sparse list doesn't accept negative indexes either but that could be fixed.

Just an idea...

**Comment by mroeschke** [comment]
Thanks for the suggestion but it appears this features hasn't had much interest from the core devs and community over the years so closing. Can reopen if there's renewed interest
