### ISSUE TITLE
.truncate() fails on PeriodIndexes with duplicate values

### ISSUE THREAD

**Issue by kiwirob** [pandas-dev/pandas#17717]
Truncating a series with a PeriodIndex with unique entries works fine:
```python
In [4]: pdi = pd.PeriodIndex([pd.Period('2017-09-01'),
   ...:                       pd.Period('2017-09-02'),
   ...:                       pd.Period('2017-09-03')])
   ...: ser = pd.Series([1,2,3], index=pdi)
   ...: ser
Out[4]:
2017-09-01    1
2017-09-02    2
2017-09-03    3
Freq: D, dtype: int64

In [5]: ser.truncate(after='2017-09-02')
Out[5]:
2017-09-01    1
2017-09-02    2
Freq: D, dtype: int64
```
But truncating a series with a PeriodIndex with non-unique entries does not
```python
In [6]: pdi2 = pd.PeriodIndex([pd.Period('2017-09-02'),
   ...:                        pd.Period('2017-09-02'),
   ...:                        pd.Period('2017-09-03')])
   ...: ser2 = pd.Series([1,2,3], index=pdi2)
   ...: ser2
   ...:
Out[6]:
2017-09-02    1
2017-09-02    2
2017-09-03    3
Freq: D, dtype: int64

In [7]: ser2.truncate(after='2017-09-02')
```
This fails with a `TypeError: Cannot compare type 'Period' with type 'int'`. 

#### Expected Output
```python
2017-09-02    1
2017-09-02    2
Freq: D, dtype: int64
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 32
OS: Windows
OS-release: 7
machine: x86
processor: x86 Family 6 Model 42 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.20.1
pytest: 3.0.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 5.3.0
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.2.2
numexpr: 2.6.2
feather: 0.3.1
matplotlib: 2.0.2
openpyxl: 2.4.7
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.3
bs4: 4.6.0
html5lib: 0.999
sqlalchemy: 1.1.9
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by sinhrks** [comment]
Looks to be caused by a shortath of `_get_loc_duplicates`. Non-monotonic duplicates looks work.

```
pdi3 = pd.PeriodIndex([pd.Period('2017-09-03'),
                       pd.Period('2017-09-02'),
                       pd.Period('2017-09-03')])
ser3 = pd.Series([1,2,3], index=pdi2)
ser3.truncate(after='2017-09-02')
# 2017-09-03    1
# 2017-09-02    2
# Freq: D, dtype: int64
```
