### ISSUE TITLE
CI/BLD: Build Failures on CircleCI

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#17720]
Seeing these somewhat regularly now. The cythonize step fails with

    pandas/_libs/reshape.pyx:11:0: 'numpy/float16_t.pxd' not found

Examples:

- https://circleci.com/gh/pandas-dev/pandas/5122#tests/containers/3
- https://circleci.com/gh/pandas-dev/pandas/5176#tests/containers/3

cc @jbrockmendel if you have any ideas

**Comment by jbrockmendel** [comment]
Did it happen to start using cython 0.27 recently?  I had trouble when upgrading last week, downgraded to wait for 0.27.1

**Comment by TomAugspurger** [comment]
Perhaps, I'll see if I can find any failures like this with older cythons. I haven't been able to reproduce with cython 0.27

**Comment by jbrockmendel** [comment]
What happens if you go into setup.py and remove the `'include': []` key from the `ext_data` entry for `_libs.reshape`?

**Comment by jreback** [comment]
these look all ok now. FYI we have been testing with cython 0.27 on the numpy_dev build for a week or so (its not the problem).

**Comment by TomAugspurger** [comment]
Back in https://circleci.com/gh/pandas-dev/pandas/5265#tests/containers/3

**Comment by jbrockmendel** [comment]
@TomAugspurger this showed up in #17750, went away after [0b9fff321328af1b172659c0d361eb5b6227b2ba](https://github.com/pandas-dev/pandas/pull/17750/commits/0b9fff321328af1b172659c0d361eb5b6227b2ba)
