### ISSUE TITLE
Qtbindings clipboard conflict

### ISSUE THREAD

**Issue by dvincentwest** [pandas-dev/pandas#17722]
In the clipboard package, I see pandas is using pyperclip

the problem is that pyperclip uses PyQt4 when deciding to use Qt for the linux clipboard, which can create a conflict if trying to embed pandas into a PyQt5 or PySide application for example

I think the simplest solution is to use [qtpy from the Spyder](https://github.com/spyder-ide/qtpy) team, so replace:

```python
from PyQt4.QtGui import QApplication
```

with

```python
from qtpy.QtWidgets import QApplication
```

I am currently working on a PyQt5 based pandas data visualization program and this is a problem I have encountered in the past.

**Comment by sinhrks** [comment]
Thanks for the report. Do you have a link from Spyder team answer? Also, PR is appreciated.

**Comment by dvincentwest** [comment]
link added and I have created a pull request #17723 , which only touches 2 lines of code that I have used successfully with a different project
