### ISSUE TITLE
DOC: Instructions for generate_legacy_storage_files

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#17721]
The usage instructions at the top of `tests.io.test_pickle` are [inaccurate](https://github.com/pandas-dev/pandas/pull/17458#issuecomment-333027685).  Maybe something in contributing docs?

**Comment by sinhrks** [comment]
I think the issue should be solved by fixing `generate_legacy_storage_files.py`, but it's nice to add a document related to this.

**Comment by jreback** [comment]
see #17733, not averse to adding to contributing.rst, but this is a rather specific topic which doesn't come up all that often. The in-file documentation should be enough.
