### ISSUE TITLE
DOC: Python Package for Pandas Documentation

### ISSUE THREAD

**Issue by donpellegrino** [pandas-dev/pandas#17749]
#### Problem description

It would be a nice enhancement if the documentation for pandas could be installed with pip from a PyPI package. This would make it easier to maintain a local copy of the pandas documentation aligned with the installed version of the pandas library.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.5.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-693.2.2.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.utf8
LOCALE: None.None

pandas: 0.20.3
pytest: 3.2.2
pip: 9.0.1
setuptools: 36.5.0
Cython: None
numpy: 1.13.1
scipy: None
xarray: None
IPython: 5.5.0
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0b10
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
I'm not sure what that would look like. If you want a local version, you can either

- clone the repo and build from source
- Download the [html](http://pandas.pydata.org/pandas-docs/stable/pandas.zip) or [pdf](http://pandas.pydata.org/pandas-docs/stable/pandas.pdf) from the website

I think the second option is sufficient?

**Comment by donpellegrino** [comment]
A consequence of the second option is that when the pandas package is upgraded, the local documentation is no longer in sync. The user must manually remember to re-download the html or pdf from the website and replace the old local copy. The manual method also requires that the user find the download links and make a decision about where to put the local documentation files. Having the documentation managed by pip would be convenient.

One way to keep documentation coordinated with library would be to create an optional pandas-doc package using the "-doc" package style for larger programs, analogous to the Debian (https://www.debian.org/doc/#other) approach.

**Comment by mroeschke** [comment]
Thanks for the request, but appears this enhancement hasn't gotten much traction and the docs were recently moved from the distribution as well. Closing.
