### ISSUE TITLE
CI: Travis Slave Crashes on Master + PRs

### ISSUE THREAD

**Issue by gfyoung** [pandas-dev/pandas#17757]
https://travis-ci.org/pandas-dev/pandas/jobs/282616908

Looks like a `pytables` issue of some sort but not sure.

**Comment by jreback** [comment]
going to leave this issue open, so we can revert #17760 once conda-forge builds are good again.

**Comment by TomAugspurger** [comment]
Moving this off the 0.21 milestone, since it's not a blocker.

**Comment by jreback** [comment]
yeah its fine, we are pinned in any event.
