### ISSUE TITLE
DOC: Remove how parameter from resampling docs

### ISSUE THREAD

**Issue by tdpetrou** [pandas-dev/pandas#17788]
#### Problem description

In the time-series docs under the [basics of resampling section](http://pandas.pydata.org/pandas-docs/stable/timeseries.html#basics) there exists a couple of sentences that mention the now deprecated `how` parameter.

> The how parameter can be a function name or numpy array function that takes an array and produces aggregated values:

> Any function available via dispatching can be given to the how parameter by name, including sum, mean, std, sem, max, min, median, first, last, ohlc.

These sentences need to be replaced.

**Comment by jreback** [comment]
sure, want to do a PR?

**Comment by tdpetrou** [comment]
very busy at the moment but i do plan on working on fixes to all the issues I created in a couple weeks.
