### ISSUE TITLE
TST/MAINT: split up test_resample.py to make it more understandable

### ISSUE THREAD

**Issue by winklerand** [pandas-dev/pandas#17806]
As discussed in https://github.com/pandas-dev/pandas/pull/16153#issuecomment-315183678, test_resample.py grew sufficiently large (currently ~ 2.7 k sloc), so splitting it up should make it more understandable.

Proposal to split along the existing classes:

tests/resample (sub-dir)
|- common.py
|- test_resample_api.py
|- base.py
|- test_datetime.py
|- test_period.py
|- test_timedelta.py
|- test_resample_grouper.py
|- test_time_grouper.py

Moreover, readability of some test cases could be improved by using pytest features:
- Convert nested for loops and "quasi-parametrized" tests (multiple test methods calling the same test logic with different parameters) to make use of @pytest.mark.parametrize decorator
- Use pytest fixtures where appropriate

**Comment by jreback** [comment]
sgtm!

**Comment by simonjayhawkins** [comment]
Any objections to opening a new PR for this?

**Comment by jreback** [comment]
go for it

**Comment by mroeschke** [comment]
I think this file has been sufficiently split up. Cleanup can be a separate task.
