### ISSUE TITLE
DOC: add use cases / when to use PeriodIndex vs. DatetimeIndex

### ISSUE THREAD

**Issue by winklerand** [pandas-dev/pandas#17807]
Maybe it makes sense to improve the documentation on the distinction of PeriodIndex vs. DatetimeIndex, especially regarding resampling behaviour.

example: https://github.com/pandas-dev/pandas/issues/10449

**Comment by mroeschke** [comment]
Hopefully https://pandas.pydata.org/docs/user_guide/timeseries.html#periodindex-and-period-range and https://pandas.pydata.org/docs/user_guide/timeseries.html#timestamps-vs-time-spans are sufficient, so closing for now. Happy to reopen if there are particular items that are not clear
