### ISSUE TITLE
BUG: groupby with resample using on parameter errors when selecting column to apply function

### ISSUE THREAD

**Issue by tdpetrou** [pandas-dev/pandas#17813]
#### Code Sample, a copy-pastable example if possible

```python
>>> df = pd.DataFrame({'id':list('aabbb'), 
                       'date':pd.date_range('1-1-2016', periods=5), 
                       'data':1})
>>> df.groupby('id').resample('2D', on='date').sum() #correct
               data
id date            
a  2016-01-01     2
b  2016-01-03     2
   2016-01-05     1

>>> df.set_index('date').groupby('id').resample('2D')['data'].sum() #correct
id  date      
a   2016-01-01    2
b   2016-01-03    2
    2016-01-05    1
Name: data, dtype: int64

>>> df.groupby('id').resample('2D', on='date')['data'].sum() #error
KeyError: 'The grouper name date is not found'
```
#### Problem description

Using a `groupby` followed by `resample` with the datetime not in the index forces the use of the `on` parameter. Unfortunately, this produces a key error whenever selecting a column to apply a function to.

#### Expected Output
Same as second one from above.
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Darwin
OS-release: 15.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.20.3
pytest: 3.0.7
pip: 9.0.1
setuptools: 35.0.2
Cython: 0.25.2
numpy: 1.13.1
scipy: 0.19.0
xarray: None
IPython: 6.0.0
sphinx: 1.5.5
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.0
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.7
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.3
bs4: 4.6.0
html5lib: 0.9999999
sqlalchemy: 1.1.9
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: 0.3.0.post

</details>

**Comment by jreback** [comment]
similar to https://github.com/pandas-dev/pandas/issues/15072 & #16766 .

a pull request is welcome to fix.
