### ISSUE TITLE
apply(to_numeric) doesn't work with subset of columns selected using .loc

### ISSUE THREAD

**Issue by krzysztofarendt** [pandas-dev/pandas#17818]
#### Code Sample:

```python
import pandas as pd    
    
df = pd.DataFrame(index=pd.Index([1, 2, 3]))
df['X'] = ['a', 'a', 'b']
df['Y'] = [1, 2, 3]
df['Z'] = [4, 5, 6]
df['Y'] = df['Y'].astype(object)  # Column to be converted to numeric
df['Z'] = df['Z'].astype(object)  # Column to be converted to numeric

df.loc[:, ['Y', 'Z']] = df.loc[:, ['Y', 'Z']].apply(pd.to_numeric)  # DOESN'T WORK
df.loc[:, 'Y':'Z'] = df.loc[:, 'Y':'Z'].apply(pd.to_numeric)  # DOESN'T WORK 
df.loc[:, 'Y'] = df.loc[:, 'Y'].apply(pd.to_numeric)  # WORKS ON SINGLE COLUMN
df[['Y', 'Z']] =  df[['Y', 'Z']].apply(pd.to_numeric)  # WORKS WITHOUT .LOC
df[['Y', 'Z']] = df.loc[:, 'Y':'Z'].apply(pd.to_numeric)  # WORKS WITHOUT .LOC ON LEFT SIDE
```
#### Problem description

It seems that `apply(pd.to_numeric)` doesn't work with `.loc[:, list]` used on the left side of the assignment. The issue is described also on [StackOverFlow](https://stackoverflow.com/questions/46629493/apply-pandas-to-numeric-to-selected-subset-of-columns-using-loc-in-pandas-datafr/46629514#46629514), because I was not sure if it's a bug or not (still not 100% sure).

**Comment by jreback** [comment]
this is as expected. ``.loc[:, ....]`` has a crucial difference to ``[]`` in that it tries to keep the existing dtype of the rhs, while ``[]`` replaces. see the note http://pandas-docs.github.io/pandas-docs-travis/basics.html#astype

**Comment by krzysztofarendt** [comment]
Thanks! But why it works with `df.loc[:, 'Y']` then (with a single column)?
