### ISSUE TITLE
ENH: sort=bool keyword argument for index.difference

### ISSUE THREAD

**Issue by mcocdawc** [pandas-dev/pandas#17839]
I often want to remove certain elements from an index while retaining the original ordering of the index. For this reason a sort keyword in the ``index.difference`` method would be required:

```
In: index = pd.Index([0, 1, 2, 4, 3])
In: index.difference({1, 2})
Out: Int64Index([0, 3, 4], dtype='int64')
# It would be cool to have instead
In: index.difference({1, 2}, sort=False)
Out: Int64Index([0, 4, 3], dtype='int64')
```

I think that this usecase appears frequently and setting the default to ``sort=True`` doesn't affect existing code.

**Comment by TomAugspurger** [comment]
+1 for this (and all the other set-ops).

@mcocdawc are you interested in submitting a pull request?

**Comment by mcocdawc** [comment]
Interested definetely, but I don't have time for it now. :(

**Comment by Giftlin** [comment]
I am interested in submitting a pull request. Can I?

**Comment by jreback** [comment]
sure

**Comment by jreback** [comment]
this needs to be done for all Index set methods (union, difference, intersect) and tested systematically. Further there are several related issues here:

xref #17010, #17378, #17376

**Comment by Giftlin** [comment]
Intersection doesn't sort at all, as of now in d code.

**Comment by Licht-T** [comment]
Oops, I am almost done patching.
`difference` and `intersection` are okay, but I have a question do we really need `sort` option in `union`?

**Comment by Licht-T** [comment]
If the `sort` option needed in `union`, how do we define the unsorted `union` order?

**Comment by jbrockmendel** [comment]
The set methods all have sort keyword. Closing a complete.
