### ISSUE TITLE
API: deprecate rename_axis / reindex_axis ?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#17833]
Given we are adding the "labels, axis=0/1" idiom to `reindex` and `rename` itself (https://github.com/pandas-dev/pandas/issues/12392, PR https://github.com/pandas-dev/pandas/pull/17800), I think the specific `reindex_axis` and `rename_axis` will be superfluous.

Should be deprecate them?

**Comment by jreback** [comment]
yes

**Comment by TomAugspurger** [comment]
They aren't quite superfluous, as `DataFrame.rename_axis` can change `.index.name` and `.columns.name`:

```python
In [13]: df = pd.DataFrame({"A": [1, 2, 3]})

In [14]: df.rename_axis("foo")
Out[14]:
     A
foo
0    1
1    2
2    3

In [15]: df.rename_axis("foo", axis=1)
Out[15]:
foo  A
0    1
1    2
2    3
``` 

I'm really regretting the approach I took in https://github.com/pandas-dev/pandas/pull/11980 for overloading rename :/

**Comment by jorisvandenbossche** [comment]
For `rename_axis` that is true, and that is certainly useful. But we could deprecate the part that relabeling of the axis?

But I don't think it is the case for `reindex_axis` ?

> I'm really regretting the approach I took in #11980 for overloading rename :/

Yes, but that is still something else no? `s.name` vs `s.index.name` ?

**Comment by mm-manu** [comment]
I use `df = df.reindex_axis(sorted(df.columns), axis=1)` to sort columns alphabetically and got a FutureWarning once in the past.

> FutureWarning: '.reindex_axis' is deprecated and will be removed in a future version. Use '.reindex' instead.

The warning did not occur since then, so I wonder what the current state is.

**Comment by toobaz** [comment]
> I use `df = df.reindex_axis(sorted(df.columns), axis=1)` to sort columns alphabetically and got a FutureWarning once in the past.

Got the same problem in old code... solved with `df = df.loc[:, sorted(df.columns)]`
