### ISSUE TITLE
Adding an integer-location based "get" method

### ISSUE THREAD

**Issue by hyamanieu** [pandas-dev/pandas#17854]
#### Code Sample, a copy-pastable example if possible

```python
a = pd.Series(data=[0],index=['A'])
print(a.get(1))#expected behaviour: returns default, here None
a['B']=2
print(a.get(1))#expected behaviour: returns 2
a.loc['C']=3
print(a.get(1))#expected behaviour: returns 2
a.loc[1]=5
print(a.get(1))#What is it? 2 or 5? (answer: 5=> Integer location based)
print(a.get(0))#What is it? default or 0? (answer:0=> index-name location based)
```
#### Problem description
Sometimes it is necessary to return a value from a DataFrame or a Series without throwing an error if the index is not present. The "get" function does just that.
Unfortunately, the "get" method doesn't allow to use an integer-location based index except for Series. 

However, as shown in the example, the "get" method can return unexpected values.

I would suggest to add an "iget" method for both Series and DataFrames similar to the "get" method:
```python
def iget(self, key, default=None):
            """
            Get item from object for given index. Returns default value if not found.
            Parameters
            ----------
            key : object
            Returns
            -------
            value : type of items contained in object
            """
            try:
                return self.iloc[key]
            except (KeyError, ValueError, IndexError):
                return default
```
While it doesn't solve the unexpected behavior of "get" with Series, it allows for an integer-based get methods with expected behavior for both pandas classes.

#### Expected Output
```python
a = pd.Series(data=[0],index=['A'])
print(a.get(1))#returns default, here None
a['B']=2
print(a.get(1))#returns default, here None
a.loc['C']=3
print(a.get(1))#returns default, here None
a.loc[1]=5
print(a.get(1))#returns 5
print(a.iget(1))#returns 2
print(a.iget(0))#returns 0
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.3.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: None.None

pandas: 0.20.1
pytest: 3.0.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 6.0.0
sphinx: 1.3.1
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.2.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.7
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.3
bs4: 4.6.0
html5lib: 0.999
sqlalchemy: 1.1.9
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
this is just API spam. you can already use ``.iloc/.iat``. This is a relatively minor usecase (for ``.get`` in general) and am -1 on it.

You could also add a ``default=`` arg to ``.iloc`` itself to do this (but also -0 on that).

**Comment by jreback** [comment]
If you could open an issue to change ``.get`` to actually location based indexing (IOW the imple should be simply: ``.loc[key]`` rather than ``[]`` to clarify any ambiguity.
