### ISSUE TITLE
Categorical.from_codes does not allow categories to be a CategoricalIndex

### ISSUE THREAD

**Issue by jnothman** [pandas-dev/pandas#17884]
#### Code Sample, a copy-pastable example if possible

`Categorical.from_codes` requires `categories` to be specified, with documented type "index-like" but passing a `CategoricalIndex` raises an error.

```python
>>> pd.Categorical.from_codes([1, 2], pd.CategoricalIndex(['Hello', 'world', '!', '**'])
/Users/joel/anaconda3/envs/scipy3k/lib/python3.5/site-packages/pandas/core/categorical.py in get_values(self)
   1276         if is_datetimelike(self.categories):
   1277             return self.categories.take(self._codes, fill_value=np.nan)
-> 1278         return np.array(self)
   1279
   1280     def check_for_ordered(self, op):

ValueError: object __array__ method not producing an array
```

#### Problem description

It seems that being able to construct a categorical column with an existing `CategoricalIndex` would be a useful way to share `CategoricalIndex` int-string mappings. This would seem to be what `from_codes` aims to facilitate, but requires reconstructing the `CategoricalIndex`, which seems unnecessary to me.

The documentation also says index-like which seems underspecified if a CategoricalIndex is not accepted. At least, the error is not sufficiently informative.

**Comment by jorisvandenbossche** [comment]
That seems like a bug, as I don't think there is a reason why a CategoricalIndex shouldn't be allowed.

But, it also seems that the Categorical *is* constructed, but just so in an invalid way that printing it errors:

```
In [46]: res = pd.Categorical.from_codes([1, 2], pd.CategoricalIndex(['Hello', 'world', '!', '**']))

In [47]: res.codes
Out[47]: array([1, 2], dtype=int8)

In [48]: res.categories
Out[48]: CategoricalIndex(['Hello', 'world', '!', '**'], categories=['!', '**', 'Hello', 'world'], ordered=False, dtype='category')

In [49]: repr(res)
...
ValueError: object __array__ method not producing an array
```

This is certainly a bug.

**Comment by jorisvandenbossche** [comment]
Further, we have the exact same issue when in the normal constructor `pd.Categorical`, and also with passing a `Categorical` (instead of CategoricalIndex) as categories. 
Of course we could fix the bug in the repr code, but I would say that we should not allow the categories to be a CategoricalIndex (in the sense: we should convert a passes Categorical/CategoricalIndex under the hood to a normal Index).

**Comment by jnothman** [comment]
ahh, I misread the error. thanks for clarifying
