### ISSUE TITLE
Not clear which window is default for df.rolling()

### ISSUE THREAD

**Issue by dstansby** [pandas-dev/pandas#17893]
The docstring for `df.rolling()` doesn't say which window is the default (I assume it's boxcar?): https://pandas-docs.github.io/pandas-docs-travis/generated/pandas.DataFrame.rolling.html

**Comment by jreback** [comment]
the default is ``None``, you must actually specify a ``win_type`` for this to have an effect.

**Comment by jreback** [comment]
that said if you want to clarify the doc-string, would be ok.

**Comment by dstansby** [comment]
The value `None` is clear as the default, but it doesn't say which window this corresponds to which seems to me to be quite important.

**Comment by jreback** [comment]
@dstansby it doesn't, you must explicity specify. it if you want that 'kind' of window. Full documentation is: http://pandas.pydata.org/pandas-docs/stable/computation.html#rolling-windows

maybe should link to it.

**Comment by dstansby** [comment]
You don't have to explicitly specify it - according to the docs window is an optional keyword argument

```python
import pandas as pd
import numpy as np

ser = pd.Series(np.random.randn(10), index=pd.date_range('1/1/2000', periods=10))

print(ser.rolling(window=5, win_type='boxcar').mean())
print(ser.rolling(window=5, win_type=None).mean())
```

Both of those print statements give the same thing, which means that `win_type=None` uses a boxcar window, but reading the docs I don't think there is any way of knowing that.
