### ISSUE TITLE
Error when adding a column to a pandas dataframe - No module named '_strptime'

### ISSUE THREAD

**Issue by SteffenNa** [pandas-dev/pandas#17904]
#### Code Sample, a copy-pastable example if possible

```python
    data['range'] = np.absolute(np.diff(data.values, axis=1))
```
throws the following error:
ModuleNotFoundError: No module named '_strptime'
This has previously been working. Not exactly sure but i think the problem occurred since I updated from Py 3.6.2 to 3.6.3. The function itself works fine. It is the creation of the new column 'range' which triggers the error.

The input 'data' is a Dataframe looking like this:
```
             high    low
2017-10-11  2.352  2.332
2017-10-12  2.346  2.318
2017-10-13  2.332  2.273
2017-10-16  2.312  2.287
2017-10-17  2.329  2.302
```

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None

pandas: 0.20.3
pytest: None
pip: None
setuptools: None
Cython: None
numpy: 1.13.3
scipy: 0.19.1
xarray: None
IPython: 6.1.0
sphinx: None
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.0.2
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: 0.7.11.None
psycopg2: None
jinja2: None
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by jreback** [comment]
not really clear what you are doing as this is not a reproducible example.

**Comment by SteffenNa** [comment]
sorry to have bothered you with this. My installation was broken. A clean re-install of home-brew/python3 did the trick.
