### ISSUE TITLE
h5py driver='core' support for Pandas HDFStore.

### ISSUE THREAD

**Issue by apiszcz** [pandas-dev/pandas#17911]
Is it possible to use the driver argument for HDFStore? Pandas 0.21rc1.
THank you.

**Comment by TomAugspurger** [comment]
Could you give an example for those unfamiliar with what h5py drivers are?

pandas HDFStore is built around pytables, not h5py, so I suspect this won't be possible.

**Comment by apiszcz** [comment]
http://docs.h5py.org/en/latest/high/file.html

Thank you.

**Comment by jreback** [comment]
you can pass it as a kwarg on construction 

but h5py is incompat with PyTables at a link level
so likely won’t work

**Comment by apiszcz** [comment]
Got it, thanks, does tables have an in core equivalent, will look.
  File "tables\hdf5extension.pyx", line 324, in
tables.hdf5extension.File._g_new (tables\hdf5extension.c:3874)
ValueError: Invalid or not supported driver: 'core'
