### ISSUE TITLE
pivot_table not working as expected when having few types of values from groupby/count

### ISSUE THREAD

**Issue by JoelleFV** [pandas-dev/pandas#17919]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

raw_data = {'day' : ['Monday','Monday','Monday','Monday','Monday'], 
            'license':['A','A','B','B','B'],
            'uniqueid':[123,352,737,368,901]}
df = pd.DataFrame(raw_data).groupby(['day','license']).count()
pivot = df.pivot_table(index = 'day', columns = 'license', values = 'uniqueid')
pivot
```
Result : 
```python
         uniqueid
day             2
license         3
```
#### Problem description
This code structure returns the expected pivot table if you change, say, one 'B' license for a 'C' license. But with the data above, the numbers in the pivot table are right, but the column and index labels are not. It uses the title of the raw_data columns instead of their possible values as index/column labels.

#### Expected Output
```python
        uniqueid      
license        A  B 
day                   
Monday         2  3
```
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.13.6-1-ARCH
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_CA.UTF-8
LOCALE: en_CA.UTF-8

pandas: 0.20.3
pytest: None
pip: 9.0.1
setuptools: 36.4.0
Cython: None
numpy: 1.13.1
scipy: 0.19.1
xarray: None
IPython: 6.2.1
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0b10
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: 0.5.0

</details>

**Comment by bobhaffner** [comment]
In your example, `df` is a DataFrame with a multi index (day and license) with uniqueid being the value.  

```
print(df)
                              uniqueid
day         license          
Monday         A               2
               B               3
```

Also, it doesn't look like you're attempting any aggregations with `pivot_table` so I would recommend [unstack](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.unstack.html) as I don't believe pivot_table is meant to operate on indexes although I could be wrong.
```
print(df.unstack())

                uniqueid   
license          A  B
day                
Monday           2  3

```

**Comment by JoelleFV** [comment]
`df.unstack()` works perfectly, thanks for your help! I didn't know about this function because `pivot_table` had always worked fine for me for large groups of data (I got the same result as with `unstack()`). Isn't it weird that `pivot_table` changes behaviour depending on how different types of values you have?

**Comment by bobhaffner** [comment]
Ok, I see your point now

```
raw_data = {'day' : ['Monday','Monday','Monday','Monday','Monday'], 
            'license':['A','A','B','B','B'],
            'uniqueid':[123,352,737,368,901]}
df = pd.DataFrame(raw_data).groupby(['day','license']).count()
pivot = df.pivot_table(index = 'day', columns = 'license', values = 'uniqueid')
print(pivot)

         uniqueid
day             2
license         3
```
But if we change a value in raw_data['license'] to a 'C' we get a different format for pivot

```
raw_data['license'][4] = 'C'

df = pd.DataFrame(raw_data).groupby(['day','license']).count()
pivot = df.pivot_table(index = 'day', columns = 'license', values = 'uniqueid')
print(pivot)

license  A  B  C
day             
Monday   2  2  1
```

**Comment by bobhaffner** [comment]
This appears to be corrected in an upcoming release.  

```
import pandas as pd
print( pd.__version__)
'0.21.0.dev+600.ge63c935d5.dirty'

raw_data = {'day' : ['Monday','Monday','Monday','Monday','Monday'], 
         'license':['A','A','B','B','B'],
        'uniqueid':[123,352,737,368,901]}

df = pd.DataFrame(raw_data).groupby(['day','license']).count()
pivot = df.pivot_table(index = 'day', columns = 'license', values = 'uniqueid')
print(pivot)

license  A  B
day          
Monday   2  3
```

**Comment by JoelleFV** [comment]
Great! Thank you for your time once again. Should I close this issue or wait until it is released?

**Comment by bobhaffner** [comment]
Yes, please close it
