### ISSUE TITLE
Functions that rely on hash tables are incorrect for complex numbers

### ISSUE THREAD

**Issue by jschendel** [pandas-dev/pandas#17927]
It looks like various functions that rely on hash tables fail when complex numbers are present, as it appears they only use the real component.

Consider the following list of values:
```python
In [2]: x = [0, 1j, 1, 1+1j, 1+2j]

In [3]: x
Out[3]: [0, 1j, 1, (1+1j), (1+2j)]
```

Using `value_counts`:
```python
In [4]: pd.value_counts(x)
Out[4]:
(1+0j)    3
0j        2
dtype: int64
```

Using `unique`:
```python
In [5]: pd.unique(x)
Out[5]: array([ 0.,  1.])
```

Using `duplicated`:
```python
In [6]: pd.Series(x).duplicated()
Out[6]:
0    False
1     True
2    False
3     True
4     True
dtype: bool
```

Using `isin`:
```python
In [7]: pd.Series(x).isin([1j, 1+1j, 1+2j])
Out[7]:
0    False
1    False
2    False
3    False
4    False
dtype: bool

In [8]: pd.Series(x).isin([0, 1])
Out[8]:
0    True
1    True
2    True
3    True
4    True
dtype: bool
```

Using `factorize` fails as described in #16399, and multiple other functions fail in similar ways (`rank`, `nunique`,  `mode`, etc.).

Note that these appear to work if the `dtype` is explicitly set to `object` instead of `complex64`:
```python
In [9]: pd.Series(x, dtype=object).isin([0, 1])
Out[9]:
0     True
1    False
2     True
3    False
4    False
dtype: bool
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: 51c5f4d2a20179041114fac0262ef567d0b0373f
python: 3.6.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.21.0rc1+26.g51c5f4d
pytest: 3.1.2
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.13.1
scipy: 0.19.1
pyarrow: 0.6.0
xarray: 0.9.6
IPython: 6.1.0
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: None
tables: 3.4.2
numexpr: 2.6.2
feather: 0.4.0
matplotlib: 2.0.2
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 0.9.8
lxml: 3.8.0
bs4: None
html5lib: 0.999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: 0.1.0
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
yep, complex doesn't have much testing, nor likely is fully supported. nice first test.

**Comment by heckeop** [comment]
@jschendel 
https://github.com/pandas-dev/pandas/blob/f5cc0789ae5f5a9e5b251e94784f537f30e0b490/pandas/core/algorithms.py#L80

@jreback 
I can take a look (`uint8` as well) if nobody is assigned to this.

**Comment by jreback** [comment]
@heckeop sure

**Comment by heckeop** [comment]
After a bit of digging, it seems that the issue, at least for `value_counts`, boils down to implementing a way to hash complex numbers with `khash`. 
https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/src/klib/khash_python.h

* We could define `khcomplex64_t` and treat the 64 bits as `uint64` when hashing, much like the code base already does for `double` type.
https://github.com/pandas-dev/pandas/blob/f8ace5f2eb1d3b807f6de9b122e7b04763bc924a/pandas/_libs/src/klib/khash.h#L128-L136
https://github.com/pandas-dev/pandas/blob/f8ace5f2eb1d3b807f6de9b122e7b04763bc924a/pandas/_libs/src/klib/khash_python.h#L23-L37

* If 128 bit complex numbers are desired, maybe we can hash the 64 bits independently and hash the result pair.

We should then be able to add the complex type to 
https://github.com/pandas-dev/pandas/blob/f8ace5f2eb1d3b807f6de9b122e7b04763bc924a/pandas/_libs/hashtable_func_helper.pxi.in#L14-L19

Any other parts of the repository I should look at before giving it a go?

**Comment by joshlk** [comment]
As a quick fix, could we treat complex numbers as objects and use the generic hasher?

**Comment by heckeop** [comment]
@joshlk I'll try it out over the coming weekend and report back

**Comment by ieaves** [comment]
It looks like this is also affecting categorical dtypes, i.e.

```
pd.Series([complex(6, 0), complex(1, 2), complex(3, -1)], dtype="category")
-> 
0    6.0
1    1.0
2    3.0
dtype: category
Categories (3, float64): [1.0, 3.0, 6.0]
```

Might be another useful test case for @alimcmaster1 (which, thank you for taking this up).
