### ISSUE TITLE
Legends in plots of SeriesGroupBy lack markers

### ISSUE THREAD

**Issue by fuglede** [pandas-dev/pandas#17939]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
df = pd.DataFrame({'y': [2, 5, 6, 4, 4, 2], 'cat': list('ABABAB')})
df.groupby('cat')['y'].plot(style='-o', legend=True)
```

![actual2](https://user-images.githubusercontent.com/6169306/31855696-b7b50b78-b6b0-11e7-82b9-522e0cffdd9a.png)

#### Problem description

Only one of the two legends include the circular marker. This becomes particularly problematic if one uses `style='o'`:

![actual3](https://user-images.githubusercontent.com/6169306/31855728-391b50fa-b6b1-11e7-96c8-169dbb60a2cf.png)

#### Expected Output

The circular marker should appear for each of the groups.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Windows
OS-release: 8.1
machine: AMD64
processor: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.20.3
pytest: 3.2.1
pip: 9.0.1
setuptools: 34.1.0
Cython: 0.26
numpy: 1.13.1
scipy: 0.19.1
xarray: None
IPython: 6.1.0
sphinx: 1.6.2
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.2.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.8
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.8
lxml: 3.8.0
bs4: 4.6.0
html5lib: 0.9999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: 0.5.0

</details>

**Comment by TomAugspurger** [comment]
I *suspect* that this shares the same underlying issue as https://github.com/pandas-dev/pandas/issues/14958, but we'll leave this open too to make sure.

@fuglede do you have a chance to dig into the plotting code to see what's going wrong?

**Comment by jreback** [comment]
dupes #14563

**Comment by fuglede** [comment]
Indeed it does; apologies for the noise.
