### ISSUE TITLE
to_latex wrong \multicolumn count

### ISSUE THREAD

**Issue by Phibedy** [pandas-dev/pandas#17959]
#### Code Sample

```python
import pandas as pd

pd.DataFrame({"A":[1,2,3]}).to_latex(longtable=True)
```
#### Problem description

```
\begin{longtable}{lr}
\toprule
{} &  A \\
\midrule
\endhead
\midrule
\multicolumn{3}{r}{{Continued on next page}} \\
\midrule
\endfoot

\bottomrule
\endlastfoot
0 &  1 \\
1 &  2 \\
2 &  3 \\
\end{longtable}
```

It says ```\multicolumn{3}``` but it should be 2, it only fails with ```longtable=True```. Indeed it always writes 3 no matter what shape the table has.

#### Expected Output
```
\multicolumn{2}
```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.10.0-35-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.20.1
pytest: None
pip: 9.0.1
setuptools: 20.7.0
Cython: None
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 6.1.0
sphinx: None
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2013b
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.0.0
openpyxl: None
xlrd: 1.0.0
xlwt: None
xlsxwriter: 0.7.3
lxml: None
bs4: None
html5lib: 0.999999999
sqlalchemy: None
pymysql: None
psycopg2: 2.7.1 (dt dec pq3 ext lo64)
jinja2: 2.8
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by gfyoung** [comment]
> Indeed it always writes 3 no matter what shape the table has.

I'm not sure that should be the case...that being said, feel free to investigate and figure out the cause.

**Comment by Phibedy** [comment]
https://github.com/pandas-dev/pandas/blob/3c964a47d626a06a3f9c2d0795ee7d744dc72363/pandas/io/formats/format.py
line 945, the 3 is fixed, it might should be ```len(rows)```

**Comment by gfyoung** [comment]
Not sure why we are using hard-coded values.  Let's change to it (both in the source code and tests) to vary, and let's see how the output looks like when we do that (BTW, when I say "see how the output looks", I mean that we should also make sure that it renders properly when converted to PDF for example - that would have to be done somewhat manually)

**Comment by jreback** [comment]
is this issue related: https://github.com/pandas-dev/pandas/issues/14484

**Comment by gfyoung** [comment]
@jreback : Not as far as I can tell.
