### ISSUE TITLE
Concat single series along columns returns a DataFrame

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#17952]
This came up in dask, I wanted to confirm whether or not it's intentional before dask mirrors pandas:

```python
In [6]: import pandas as pd

In [7]: pd.concat([pd.Series([1, 2], name='foo')], axis='columns')
Out[7]:
   foo
0    1
1    2

In [8]: type(_)
Out[8]: pandas.core.frame.DataFrame
```

I think it's fine for `concat(..., axis=1)` to always return a DataFrame, but we should document that.

**Comment by jreback** [comment]
I wouldn't except this to do anything else.  if you want to add some docs go for it. this is long estallished behavior.

**Comment by jorisvandenbossche** [comment]
I agree, I think this is the sensible thing to do.
