### ISSUE TITLE
pd.to_datetime docstring needs upgrade

### ISSUE THREAD

**Issue by tdpetrou** [pandas-dev/pandas#17973]
#### Problem description

`pd.to_datetime` has a [very short non-descriptive docstring](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.to_datetime.html):  `Convert argument to datetime`.

Using the term datetime is horribly confusing as there is a Python datetime, a NumPy datetime64 and a pandas Timestamp. Although, there is better documentation under the parameters, this needs to be expanded to more than 4 words.

#### Expected Output

Along with a more thorough explanation, It would be nice if there was consistency with how pandas refers to the triple-headed monster, datetime, datetime64 and Timestamp.

**Comment by AdamShamlian** [comment]
I'd gladly chip in on the docstring, but I hesitate to contribute a larger handling of "the triple-headed monster." I'd rather leave that to a) another PR against general DOCS and b) someone with much greater context for where pandas has been and where its headed in that regard.

**Comment by mroeschke** [comment]
Closed by https://github.com/pandas-dev/pandas/pull/42494
