### ISSUE TITLE
Failures on Master

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#17986]
This is under the "Allowed failures" section:

Started on https://travis-ci.org/pandas-dev/pandas/jobs/292375734 and is present in https://travis-ci.org/pandas-dev/pandas/jobs/292574197

https://travis-ci.org/pandas-dev/pandas/jobs/292375734#L2913

Probably from https://github.com/numpy/numpy/pull/9487 (not a break on their part, we just have to update so a warning isn't emitted).

**Comment by jreback** [comment]
note, these are *never* actually allowed. this just makes the build run faster.
