### ISSUE TITLE
DataFrame.pivot_table doesn't accept a column of list variables

### ISSUE THREAD

**Issue by nathantheshark** [pandas-dev/pandas#17985]
#### Problem description

If i use the pivot_table on a dataframe where I want to keep a column of lists, I encounter and error.

```python
import pandas as pd

# this snippet works
df = pd.DataFrame({'lst_col': ['1', '2', '3', '2'], 
                   'grp_col': ['a', 'b', 'a', 'b'],
                   'val_col': [1, 2, 3, 4]})
df.pivot_table(values='val_col',
              index='lst_col',
              columns='grp_col')


# this snippet causes an error
df = pd.DataFrame({'lst_col': [['1', '2'], ['3', '4'], ['5'], ['3', '4']], 
                   'grp_col': ['a', 'b', 'a', 'b'],
                   'val_col': [1, 2, 3, 4]})
df.pivot_table(values='val_col',
              index='lst_col',
              columns='grp_col')

```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------------

pandas: 0.20.3
pytest: None
pip: None
setuptools: None
Cython: 0.25.2b0
numpy: 1.13.1
scipy: 0.19.1
xarray: None
IPython: 5.3.0
sphinx: None
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2014.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 1.5.3
openpyxl: 2.3.5
xlrd: 0.9.4
xlwt: None
xlsxwriter: None
lxml: 3.5.0
bs4: None
html5lib: 0.9999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by gfyoung** [comment]
If you look at the error message, it's because when we reshaping, we can't hash the list objects, which is a Python issue AFAICT.  IIUC, I don't think there's much we can do for this problem unfortunately...

@jreback @jorisvandenbossche : Other thoughts?

**Comment by mroeschke** [comment]
Agreed. Additionally nested data structures are not well supported. Closing
