### ISSUE TITLE
DOC: Add SparseDataFrame and SparseSeries to the API docs

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#17993]
We have some references them that don't resolve currently, since the classes aren't there.

Unfortunately it looks like adding `SparseDataFrame` causes a failure like

```
ValueError: %(klass)s.notna : boolean inverse of isna is not a item name
[70] > /Users/taugspurger/Envs/pandas-dev/lib/python3.6/site-packages/pandas/doc/sphinxext/numpydoc/docscrape.py(210)parse_item_name()
-> raise ValueError("%s is not a item name" % text)
(Pdb++) Building HTML failed.
```

**Comment by jorisvandenbossche** [comment]
I would first like to see a way to somehow limit the number of api pages (eg a way to only build pages for methods that are overwritten) before adding such a big new chunk to the api pages.

**Comment by TomAugspurger** [comment]
Yeah, we should only include the methods we actually refer to.
