### ISSUE TITLE
REF/INT: refactor concatenation of values in Block.concat_same_type

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#17997]
See comment https://github.com/pandas-dev/pandas/pull/17954#discussion_r147298282 and https://github.com/pandas-dev/pandas/pull/17728#discussion_r144095969 about suggestions to make the implementation of `concat_same_type` cleaner.

**Comment by jbrockmendel** [comment]
Block.concat_same_type is gone, is this closeable/updateable?

**Comment by jorisvandenbossche** [comment]
Yes, this can indeed be closed I think. The referenced comments are now also outdated with the introduction of the `get_common_dtype` interface used in the concat code.
