### ISSUE TITLE
CI: turn on debug builds on windows

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#18007]
see here https://github.com/pandas-dev/pandas/pull/18005#issuecomment-340081302

if we turn on debugging / heap checking can catch some more errors

**Comment by jbrockmendel** [comment]
is this still applicable without appveyor?

**Comment by cgohlke** [comment]
Pillow has [enabled page heap verification](https://github.com/python-pillow/Pillow/pull/4186/files) in AppVeyor and GitHub Actions.

**Comment by mroeschke** [comment]
Not sure if this is entirely applicable anymore so closing
