### ISSUE TITLE
BENCH: Index.take benchmark is measuring wrong thing

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#18000]
The `take` benchmarks `indexing.IndexingMethods.time_take_intindex` is benchmarking `take` on a boolean list, which take interprets as a [0, 1, 0, 1, ...] values, which is a bit silly to benchmark. 
We should add some actual benchmark on integers instead.

**Comment by sangramga** [comment]
@jorisvandenbossche  I would like to make this issue to be my first contribution. I have looked at the source code and ready tot take it up. 
Although I have unable to see as to why and how  a Boolean list <code>self.indexer <code> is  interpreted as integer [0,1,0,1,...] values?
Is it possible to resolve this issue by creatin a new indexer list like <code>self.int_indexer<int> for benchmarking? What do you have in mind?

**Comment by jorisvandenbossche** [comment]
> Is it possible to resolve this issue by creating a new indexer list like self.int_indexer for benchmarking? What do you have in mind?

Yes, although I think you can just replace the existing `self.indexer` with a new list of ints instead of bools (we don't need to keep the old bench of using booleans).

> Although I have unable to see as to why and how a Boolean list self.indexer is interpreted as integer [0,1,0,1,...] values?

If you try to run the code (or similar), you will see:

```
In [84]: s = pd.Series(range(5))

In [85]: s.take([True, False, True, False, True])
Out[85]: 
1    1
0    0
1    1
0    0
1    1
dtype: int64

In [86]: s.loc[[True, False, True, False, True]]
Out[86]: 
0    0
2    2
4    4
dtype: int64
```

so take interprets the True, False as 0, 1  and not as a mask (like is done in `loc`)

**Comment by sangramga** [comment]
I made the following changes in `indexing.IndexingMethods.time_take_intindex` 

Replaced the boolean list `indexer` with randomized integer list
`self.indexer = list(np.random.randint(0, 100000, size=100000))`
Does this resolve the issue?

**Comment by hardikpnsp** [comment]
It seems like the issue has been open for quite a while. I looked into the `take` benchmark, It is still using boolean values as `indexer`. Does not seem like anyone is working on the issue, I will quickly fix that.

**Comment by hardikpnsp** [comment]
take
