### ISSUE TITLE
Extra "in" in "Contributing to pandas" documentation

### ISSUE THREAD

**Issue by mattayes** [pandas-dev/pandas#18040]
#### Problem description

Section: Contributing to pandas
Subsection: About the _pandas_ documentation
Link: http://pandas.pydata.org/pandas-docs/version/0.21.0/contributing.html#about-the-pandas-documentation

The second sentence of the last paragraph contains an extra "in" (bolded):

> The utility script _scripts/api_rst_coverage.py_ can be used to compare the list of methods documented in _doc/source/api.rst_ (which is used to generate the API Reference page) and the actual public methods. This will identify methods documented **in in** _doc/source/api.rst_ that are not actually class methods, and existing methods that are not documented in _doc/source/api.rst_.

#### Expected Output

> The utility script _scripts/api_rst_coverage.py_ can be used to compare the list of methods documented in _doc/source/api.rst_ (which is used to generate the API Reference page) and the actual public methods. This will identify methods documented in _doc/source/api.rst_ that are not actually class methods, and existing methods that are not documented in _doc/source/api.rst_.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.21.0
pytest: None
pip: 9.0.1
setuptools: 36.6.0
Cython: None
numpy: 1.13.3
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: None
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.1.0
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0b10
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

Happy to make the change!

**Comment by jreback** [comment]
just send a PR, no need to make an issue for docs that you find confusing.

**Comment by mattayes** [comment]
@jreback Sounds good, will do.
