### ISSUE TITLE
BUG: method .nunique on categorical series in v0.21 with only NaNs gives ValueError

### ISSUE THREAD

**Issue by topper-123** [pandas-dev/pandas#18051]
#### Code Sample, a copy-pastable example if possible

```python
>>> ser = pd.Series(pd.Categorical([np.nan]))
>>> ser.nunique()
ValueError: buffer source array is read-only
```
#### Problem description

The above code gave 0 in v20.3 and is expected to give 0 also in v0.21. The problem is independent of if I set some categories.

**EDIT**: Actually this doesn't give error if I set categories. so this only happens if no categories are set. The use case for no categories in my case is programmatically reading in data, where some columns are empty and of dtype categorical.

#### Expected Output

0 (zero)

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: 81372093f1fdc0c07e4b45ba0f47b0360fabd405
python: 3.5.4.final.0
python-bits: 32
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.21.0
pytest: 3.2.3
pip: 9.0.1
setuptools: 36.5.0.post20170922
Cython: None
numpy: 1.13.3
scipy: None
pyarrow: None
xarray: None
IPython: 6.1.0
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: 2.4.8
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
this is a variation of https://github.com/pandas-dev/pandas/issues/10043, fixed by #10070 
and duplicated by #17192, though this is example is simple, so should fix.

PR's welcome!

**Comment by topper-123** [comment]
This individual issue can be fixed with a simple `ìf not len(self.cat.categories): return 0`` but that feels like bypassing the issue in the ``.unique`` method. Is that ok is something more involved required?

If this is something in cython or requires larger refactoring, this will be beyond my ability, I'm sorry.

**Comment by jreback** [comment]
no, this should be fixed in cython.

**Comment by topper-123** [comment]
Tthis is a regression from v0.20.3. Maybe this has something to do with the new CategoricalDtype, @TomAugspurger ?

**Comment by TomAugspurger** [comment]
I think it's more likely to be the changes to `take_nd`, but I may be wrong.

**Comment by ghasemnaddaf** [comment]
@topper-123  @TomAugspurger please review  #18279
