### ISSUE TITLE
search path of pandas read_csv function

### ISSUE THREAD

**Issue by ardeal** [pandas-dev/pandas#18063]
Hi 
read_csv funciton of pandas is able to read csv file in local folder, but it is not able to read the csv file in folder added by sys.path.append function.

Please check my test code:
data_1001_0001.csv file locates in C:\doc\datasets which is added by command sys.path.append

```python

import pandas as pd
import sys
sys.path.append(r'C:\doc\datasets')
# data_1001_0001.csv file locates in C:\doc\datasets 
df = pd.read_csv('data_1001_0001.csv')

```

Error is:
IOError: File data_1001_0001.csv does not exist

**Comment by TomAugspurger** [comment]
`sys.path` controls the directories searched by `import` statements: https://docs.python.org/3/library/sys.html#sys.path

**Comment by ardeal** [comment]
Thank you!

Is there any similar way to control the directories searched by read_csv of pandas?

**Comment by TomAugspurger** [comment]
I don't think so. I'd recommend writing a small function to discover the
correct absolute path before passing it to read_csv.

**Comment by ardeal** [comment]
Got it.
Thanks Tom!

**Comment by TianyiPeng** [comment]
I personally feel this should be a feature (`read_csv` searches paths in `sys.path`) as I also encountered it a few times. Out of curiosity, is there any reason to be against adding this as a feature?
