### ISSUE TITLE
TST: Scipy Installation Failures on AppVeyor

### ISSUE THREAD

**Issue by gfyoung** [pandas-dev/pandas#18073]
https://ci.appveyor.com/project/pandas-dev/pandas/build/1.0.6106/job/efus0uvvu38qmvo3

For some reason, the `conda` installation of `scipy` is failing to import.  Doesn't seem like a new version problem, as `scipy` is pushing `1.0.0` right now, but we're installing `0.19.1`.

Might be a `conda-forge` thing?

**Comment by jreback** [comment]
@gfyoung can you grab the installed versions the failed build and the last good build and see what the diff is?

**Comment by jreback** [comment]
ok i disabled scipy install on 3.6 on windows
prob a temp issue - will revert at some point
