### ISSUE TITLE
tz_localize_to_utc scalar version?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#18070]
This can be shunted into the tslibs todo list after it has been seen.

`tslibs.conversion.tz_localize_to_utc` has a comment `# Vectorized version of DstTzInfo.localize`.  Two of the places where `tz_localize_to_utc` are called are for a singleton `np.array([self.value], dtype='i8')`.   If there is a scalar version available, we can avoid array creation and iteration overhead.

**Comment by gfyoung** [comment]
@jbrockmendel : I don't know if there is a scalar version, but if there isn't, try implementing it and see whether performance is improved as a result.

**Comment by jreback** [comment]
this is a trivial overhead and prob not worth it to duplicate code
