### ISSUE TITLE
Pandas 0.21.0 requires old numpy 1.9.3

### ISSUE THREAD

**Issue by jiri-kulik** [pandas-dev/pandas#18107]
Hi,

when updating pandas in conda, i'm asked to downgrade numpy.

```
Jiris-MacBook-Pro:~ u$ conda update pandas
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /Users/jirikulik/miniconda3:

The following packages will be UPDATED:

    pandas: 0.20.3-py36hd6655d8_2 defaults --> 0.21.0-py36hd8e0503_0 defaults

The following packages will be DOWNGRADED:

    numpy:  1.13.3-py36h2cdce51_0 defaults --> 1.9.3-py36h60773e1_3  defaults

```
#### Problem description

When updating pandas, conda asks me to downgrade numpy to version 1.9.3. Is it intentional? I updated everything (via `conda update --all`) without any issues, pandas is the only package that didn't update to the latest version.

I'm on macOS 10.13.1 if that matters, output of pd.show_versions() pasted below.

Thank you
Jiri

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None

pandas: 0.20.3
pytest: None
pip: 9.0.1
setuptools: 36.5.0.post20170921
Cython: 0.26.1
numpy: 1.13.3
scipy: 0.19.1
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.1.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: 0.5.0

</details>

**Comment by jreback** [comment]
I think this is a newest conda issue. https://github.com/conda/conda/issues/6260

you can pin ``numpy=1.13`` to ameliorate (or use ``conda=4.2.16``)
