### ISSUE TITLE
BLD: since we already use setuptools, let's remove the optional logic in setup.py

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#18113]
no need to have the branching in setup.py we always have setuptools available.

**Comment by kchomski-reef** [comment]
Besides cleaning up `setup.py` does something else should be done? Are there any caveats regarding `pandas` build process?

**Comment by jreback** [comment]
no i think this all that is needed; we do sufficient testing on building in the CI

**Comment by kchomski-reef** [comment]
@jreback Do you think we could have `Build` subsection in `whatsnew` docs for `BLD` related entries? Or do they fall under one of existing subsections?

**Comment by jbrockmendel** [comment]
the try/except of `import setuptools` also includes `import pkg_resources`.  Is it also always the case that we always have pkg_resources?
