### ISSUE TITLE
enhancement request: support for MDF

### ISSUE THREAD

**Issue by coppolajj** [pandas-dev/pandas#18118]
It would be great to have support within pandas for the [MDF](https://vector.com/vi_mdf_en.html) format.  Something like [mdfreader](https://pypi.python.org/pypi/mdfreader/0.2.2).

**Comment by gfyoung** [comment]
Personally have used the format, but seems interesting.  Have a look at how we added support for `pyarrow` .  That should give you an idea of how you might incorporate `mdfreader`.

**Comment by jreback** [comment]
this is out of scope for pandas as it’s a pretty narrowly focused format
the package you linked seems just fine in any event

**Comment by danielhrisca** [comment]
You could also have a look at the alternative asammdf https://github.com/danielhrisca/asammdf
http://asammdf.readthedocs.io/en/latest/benchmarks.html

**Comment by jorisvandenbossche** [comment]
Always welcome to add it to the ecosystem.rst page in the docs listing pandas-related or pandas-interfacing packages

**Comment by danielhrisca** [comment]
Very nice. Thank you! MDF is a very popular format for automotive measurement systems.

**Comment by coppolajj** [comment]
My thought was to support it like HDF5 and the others found in [IO Tools](http://pandas.pydata.org/pandas-docs/stable/io.html#) via mdfreader (or I guess asammdf might work too).  And I agree, it's very popular, [matlab is able to read](https://www.mathworks.com/help/vnt/ug/read.html) this format.
