### ISSUE TITLE
TST: fix to_xarray xfails

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#18115]
not sure what is going on here, but I think we need to adjust / make a min for xarray in our tests.

xef #18114 

cc @shoyer

**Comment by shoyer** [comment]
@jreback can you point me to a build failure? Looking at #18114 everything on Travis is either cancelled or successful.

**Comment by jreback** [comment]
I have xfailed them, but here's the comparision.

I think when I originally wrote these tests we were on xarray < 0.9
```
In [1]: import xarray

In [2]: xarray.__version__
Out[2]: '0.9.6'

In [3]: pd.__version__
Out[3]: '0.22.0.dev0+61.g744dcd3'

In [6]: s = Series(range(6), list('abcdef'))

In [7]: s
Out[7]: 
a    0
b    1
c    2
d    3
e    4
f    5
dt

In [8]: s.to_xarray()
Out[8]: 
<xarray.DataArray (index: 6)>
array([0, 1, 2, 3, 4, 5])
Coordinates:
  * index    (index) object 'a' 'b' 'c' 'd' 'e' 'f'

In [9]: s.to_xarray().to_series()
Out[9]: 
index
a        0
b        1
c        2
d        3
e        4
f        5
dtype: int64

In [10]: s.to_xarray().to_series().index
Out[10]: 
MultiIndex(levels=[['a', 'b', 'c', 'd', 'e', 'f']],
           labels=[[0, 1, 2, 3, 4, 5]],
           names=['index'])
```

so I was testing for idempotency, e.g. [6] roundtrips to [9].

now it seems we get a MultiIndex back (rather than the original index).

**Comment by shoyer** [comment]
Gotcha, thanks. This was introduced by #17236 and fixed in xarray by https://github.com/pydata/xarray/issues/1548. That will be in our next release, which will come out very soon (we just issued a release candidate).

**Comment by jreback** [comment]
ahh ok great. then I will change the xfails to be < 0.10
