### ISSUE TITLE
Series.plot should label y axis with Series name

### ISSUE THREAD

**Issue by Eoksni** [pandas-dev/pandas#18124]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import matplotlib.pyplot as plt
ind = pd.Series(['first', 'second', 'third'], name='count')
s = pd.Series([1, 2, 3], index=ind, name='i should be a y label')
s.plot()
plt.show()
```
#### Problem description

So when you call Series.plot, xlabel is set to the name of the index, but ylabel is not set to the name of the series itself. To me it seems asymmetric and believe it should set ylabel automatically.
Also, if I plot it with `s.plot(kind='hist')`, I get ylabel "Frequency" but no xlabel, which I would expect to be the name of the series as well.

#### Expected Output

ylabel set to name of the series for usual plot, and xlabel set to name of the series for hist plot

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: AMD64 Family 16 Model 4 Stepping 3, AuthenticAMD
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.20.3
pytest: 3.2.1
pip: 9.0.1
setuptools: 36.5.0.post20170921
Cython: 0.26.1
numpy: 1.13.1
scipy: 0.19.1
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 0.9.8
lxml: 3.8.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by gfyoung** [comment]
cc @TomAugspurger

**Comment by TomAugspurger** [comment]
Seems reasonable to me.

@Eoksni are you interested in making a Pull Request?

**Comment by Eoksni** [comment]
I am, but can't make any promises. Will look into it if have spare time.

**Comment by Eoksni** [comment]
Thanks for the response

**Comment by shoyer** [comment]
I think one reason why we might not do this currently is that there are two ways to potentially label a series:
- On the y-axis (matplotlib's `set_ylabel()`)
- In a legend (matplotlib's `label=`)

**Comment by Eoksni** [comment]
ok, I see, so it sets up legend, but it doesn't show it by default, I need to call `plt.legend()` to show it, whereas with DataFrame.plot legend is shown automatically. I find it confusing that Series.plot doesn't have any info about what it is actually drawing; and having legend just for a single line plot seems like an overkill.

In my opinion, sensible defaults would be like so:
- if just a single Series is shown, then ylabel with its name makes perfect sense
- if there are several lines/scatter plots shown already, then ylabel should be empty and legend is shown instead

I don't know how it would actually work, like, if I do several Series.plot in a row
```python
s1.plot()
s2.plot()
s3.plot()
```
should it on the first `s1.plot` see that there is no lines yet, so it sets ylabel to the `s1.name`, then on the `s2.plot` it will see that other line is already shown, so it removes ylabel and shows legend instead, etc? Seems kinda confusing and 'fragile'.

May be this behavior should have some configuration parameter somewhere?

I, personally, use Series.plot only when I need to plot a single variable. I never do several Series.plot in the same axes. If I want to show several variables, I use DataFrame.plot. So as a workaround this little proxy function does great for me
```python
def mysplot(s, *kargs, kind='line', **kwargs):
    res = s.plot(*kargs, kind=kind, **kwargs)
    if s.name:
        if kind == 'hist':
            plt.xlabel(s.name)
        elif kind == 'line':
            plt.ylabel(s.name)
    return res
```
so if there is no ideal solution, I think we can just close it, I definitely don't find it as a very important one, and my workaround satisfies me enough.

**Comment by Eoksni** [comment]
Actually, I made my workaround even more convenient. I just have this snippet at the start of my python notebook, and then I can use Series.plot in ordinal way, but it now puts ylabel as I wanted.
```python
from functools import wraps

def monkey_patch_series_plot():
    """Makes Series.plot to show series name as ylabel/xlabel according to plot kind."""
    f = pd.Series.plot.__call__
    @wraps(f)
    def _decorator(*kargs, **kwargs):
        res = f(*kargs, **kwargs)
        s = kargs[0].__dict__['_data']
        if s.name:
            try:
                kind = kwargs['kind']
            except KeyError:
                kind = 'line'
            if kind == 'line' or kind == 'scatter':
                plt.ylabel(s.name)
            elif kind == 'hist':
                plt.xlabel(s.name)
        return res
    pd.Series.plot.__call__ = _decorator
monkey_patch_series_plot()
```
So, I'm entirely satisfied with this so I close the issue.

**Comment by yudai-nkt** [comment]
I was searching for a way for `pandas.Series.plot()` to automatically set its `name` to the y-axis label, and found this issue. I tried the workaround above, but

```python
from functools import wraps
import pandas as pd
import matplotlib.pyplot as plt


def monkey_patch_series_plot():
    """Makes Series.plot to show series name as ylabel/xlabel according to plot kind."""
    f = pd.Series.plot.__call__
    @wraps(f)
    def _decorator(*kargs, **kwargs):
        res = f(*kargs, **kwargs)
        s = kargs[0].__dict__['_data']
        if s.name:
            try:
                kind = kwargs['kind']
            except KeyError:
                kind = 'line'
            if kind == 'line' or kind == 'scatter':
                plt.ylabel(s.name)
            elif kind == 'hist':
                plt.xlabel(s.name)
        return res
    pd.Series.plot.__call__ = _decorator
monkey_patch_series_plot()


ind = pd.Series(['first', 'second', 'third'], name='count')
s = pd.Series([1, 2, 3], index=ind, name='i should be a y label')
s.plot()
plt.show()
```

yields the following error:
```console
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    s.plot()
  File "test.py", line 12, in _decorator
    s = kargs[0].__dict__['_data']
KeyError: '_data'
```

Are there any breaking changes since Pandas v0.20.3 or am I just doing something wrong? (By the way, I'd be glad if this can be accomplished out of the box to avoid internal tweaks that might cause these kind of errors in the future)

**Comment by Eoksni** [comment]
@yudai-nkt I don't think you are doing something wrong, your exact code piece worked flawlessly for me back in the days. I haven't been using pandas for a while and not exactly sure how it can be fixed for newer version.

As a suggestion, you can put a breakpoint before `kargs[0].__dict__` line and see what is inside and change the code accordingly. And yeah, all of this is fiddling with internal data structures and such structure probably can be changed even in minor releases as it is not part of public API.
