### ISSUE TITLE
one } too much

### ISSUE THREAD

**Issue by derestle-htwg** [pandas-dev/pandas#18130]
https://github.com/pandas-dev/pandas/blob/81372093f1fdc0c07e4b45ba0f47b0360fabd405/pandas/core/frame.py#L5116

should be   ...     df = df.append({'A': i}, ignore_index=True)
instead of   ...     df = df.append({'A'}: i}, ignore_index=True)

note the } after the 'A'

**Comment by gfyoung** [comment]
Will close formally in your PR #18131
