### ISSUE TITLE
Enable to restrict columns for pandas.read_parquet

### ISSUE THREAD

**Issue by hoffmann** [pandas-dev/pandas#18154]
#### Problem description

In pandas 0.21 the top level funtion read_parquet() was introduced. Both available engines fastparquet and pyarrow support the specifications of columns to read. If you are only interested in certain columns of a dataframe this reduces the io.

- Fastparquet https://github.com/dask/fastparquet/blob/master/docs/source/quickstart.rst#reading

- PyArrow http://pyarrow-xhochy.readthedocs.io/en/latest/pyarrow.parquet.html#pyarrow.parquet.read_table

It should be also possible to specify the columns in pandas.read_parquet().

**Comment by gfyoung** [comment]
Sounds good to me!

**Comment by jreback** [comment]
this is actually quite trivial, we just need to pass kwargs thru on the read. and then you can specify ``columns=``, which we could document as a formal kwarg.

PR's welcome!

**Comment by hoffmann** [comment]
@jreback have already attached a PR.

**Comment by jorisvandenbossche** [comment]
More in general, should we pass through `**kwargs` to the actual engine call?
