### ISSUE TITLE
DataFrame.to_records() converts DatetimeIndex to datetime object, not np.datetime64

### ISSUE THREAD

**Issue by jzwinck** [pandas-dev/pandas#18160]
This code: 
```python
df = pd.DataFrame([pd.to_datetime('2017-11-07')], [pd.to_datetime('2017-11-08')])
df.to_records()
```

Produces a totally different column type for the index vs the data:
```
rec.array([(datetime.datetime(2017, 11, 8, 0, 0), '2017-11-07T00:00:00.000000000')], 
          dtype=[('index', 'O'), ('0', '<M8[ns]')])
```

It should produce:
```
rec.array([('2017-11-08T00:00:00.000000000', '2017-11-07T00:00:00.000000000')], 
          dtype=[('index', '<M8[ns]'), ('0', '<M8[ns]')])
```

I'm using Pandas 0.20.3, NumPy 1.13.1, and Python 3.5.3.

**Comment by jreback** [comment]
seems buggy
would appreciate a PR

**Comment by jzwinck** [comment]
@jreback I just discovered this was broken by #1908 (commit 38333f42) which added the `to_records(convert_datetime64)` option with the horrible default of `True`!

It looks like the option was added in order to work around some now-ancient NumPy bug.  Setting `convert_datetime64=False` now works fine (for my test case and for the one in #1908).

What do you think about changing the default from `True` to `False`?  The current default loses precision and is inefficient.

**Comment by jreback** [comment]
i would be in favor of deprecating that option entirely

**Comment by jzwinck** [comment]
Does that require a DeprecationWarning first, then later removal, or should we just remove the option at once?

**Comment by jreback** [comment]
FutureWarning

**Comment by H0R5E** [comment]
I actually get a bad conversion with `to_records()` now unless I set `convert_datetime64=True`. Below
is the dataframe and the result from `to_records()` with the flag being set. The docs do say "By default, timestamps are converted to datetime.datetime".

>                          mass
> DateTime
> 2010-12-01 00:00:00  0.369716
> 2010-12-01 01:00:00  0.793288
> 2010-12-01 02:00:00  0.878291
> 2010-12-01 03:00:00  0.249779
> 2010-12-01 04:00:00  0.180695
> 2010-12-01 05:00:00  0.769502
> 2010-12-01 06:00:00  0.896044
> 2010-12-01 07:00:00  0.409012
> 2010-12-01 08:00:00  0.887009
> 2010-12-01 09:00:00  0.381467
> 2010-12-01 10:00:00  0.221725
> 2010-12-01 11:00:00  0.658643
> 2010-12-01 12:00:00  0.843174
> 2010-12-01 13:00:00  0.633107
> 2010-12-01 14:00:00  0.244581
> 2010-12-01 15:00:00  0.536001
> 2010-12-01 16:00:00  0.115684
> 2010-12-01 17:00:00  0.661129
> 2010-12-01 18:00:00  0.362796
> 2010-12-01 19:00:00  0.222668
> 2010-12-01 20:00:00  0.824834
> 2010-12-01 21:00:00  0.909061
> 2010-12-01 22:00:00  0.009120
> 2010-12-01 23:00:00  0.714579
> 2010-12-02 00:00:00  0.670255
> 2010-12-02 01:00:00  0.706622
> 2010-12-02 02:00:00  0.737824
> 2010-12-02 03:00:00  0.833261
> 2010-12-02 04:00:00  0.576808
> 2010-12-02 05:00:00  0.763618
> 2010-12-02 06:00:00  0.158969
> 2010-12-02 07:00:00  0.681836
> 2010-12-02 08:00:00  0.785189
> 2010-12-02 09:00:00  0.056726
> 2010-12-02 10:00:00  0.159796
> 2010-12-02 11:00:00  0.296958
> 2010-12-02 12:00:00  0.500573
> 2010-12-02 13:00:00  0.539012
> 2010-12-02 14:00:00  0.525445
> 2010-12-02 15:00:00  0.306927
> 2010-12-02 16:00:00  0.234188
> 2010-12-02 17:00:00  0.551214
> 2010-12-02 18:00:00  0.690883
> 2010-12-02 19:00:00  0.978113
> 2010-12-02 20:00:00  0.778883
> 2010-12-02 21:00:00  0.194913
> 2010-12-02 22:00:00  0.084815
> 2010-12-02 23:00:00  0.619407
> [(1291161600000000000L, 0.3697155242375313)
>  (1291165200000000000L, 0.7932883443384089)
>  (1291168800000000000L, 0.8782914750406063)
>  (1291172400000000000L, 0.2497787157480419)
>  (1291176000000000000L, 0.18069469169077823)
>  (1291179600000000000L, 0.7695017668962097)
>  (1291183200000000000L, 0.896043698548073)
>  (1291186800000000000L, 0.4090117647275069)
>  (1291190400000000000L, 0.8870092042037834)
>  (1291194000000000000L, 0.3814667592106017)
>  (1291197600000000000L, 0.22172471538560667)
>  (1291201200000000000L, 0.6586430628092982)
>  (1291204800000000000L, 0.8431741187716458)
>  (1291208400000000000L, 0.6331073448657422)
>  (1291212000000000000L, 0.2445806449524044)
>  (1291215600000000000L, 0.5360011487598739)
>  (1291219200000000000L, 0.11568432245506843)
>  (1291222800000000000L, 0.6611293755426051)
>  (1291226400000000000L, 0.3627962471495728)
>  (1291230000000000000L, 0.2226677351689964)
>  (1291233600000000000L, 0.8248344946838133)
>  (1291237200000000000L, 0.9090609525614272)
>  (1291240800000000000L, 0.00912041223873028)
>  (1291244400000000000L, 0.7145790785894172)
>  (1291248000000000000L, 0.6702547049372578)
>  (1291251600000000000L, 0.706621940631339)
>  (1291255200000000000L, 0.7378238557760849)
>  (1291258800000000000L, 0.8332608791555113)
>  (1291262400000000000L, 0.576808117745154)
>  (1291266000000000000L, 0.7636175881020281)
>  (1291269600000000000L, 0.15896906207087835)
>  (1291273200000000000L, 0.6818358685983911)
>  (1291276800000000000L, 0.7851892701964108)
>  (1291280400000000000L, 0.05672579370221542)
>  (1291284000000000000L, 0.15979586136206547)
>  (1291287600000000000L, 0.2969583513206824)
>  (1291291200000000000L, 0.5005727393914391)
>  (1291294800000000000L, 0.5390120440224903)
>  (1291298400000000000L, 0.5254446661469439)
>  (1291302000000000000L, 0.3069273851484682)
>  (1291305600000000000L, 0.23418794513098873)
>  (1291309200000000000L, 0.551213914585584)
>  (1291312800000000000L, 0.6908834132625609)
>  (1291316400000000000L, 0.9781126719977703)
>  (1291320000000000000L, 0.7788831195497523)
>  (1291323600000000000L, 0.1949126651536216)
>  (1291327200000000000L, 0.08481547250807209)
>  (1291330800000000000L, 0.6194067341663069)]

```
>conda info

     active environment : _dtocean_dev
    active env location : C:\Anaconda\envs\_dtocean_dev
            shell level : 1
       user config file : C:\Users\Work\.condarc
 populated config files : C:\Users\Work\.condarc
          conda version : 4.5.9
    conda-build version : 3.0.30
         python version : 2.7.14.final.0
       base environment : C:\Anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/dataonlygreater/win-64
                          https://conda.anaconda.org/dataonlygreater/noarch
                          https://conda.anaconda.org/t/<TOKEN>/topper/win-64
                          https://conda.anaconda.org/t/<TOKEN>/topper/noarch
          package cache : C:\Anaconda\pkgs
                          C:\Users\Work\AppData\Local\conda\conda\pkgs
       envs directories : C:\Anaconda\envs
                          C:\Users\Work\AppData\Local\conda\conda\envs
                          C:\Users\Work\.conda\envs
               platform : win-64
             user-agent : conda/4.5.9 requests/2.18.4 CPython/2.7.14 Windows/7 W
indows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False
```
```
> conda list
...
numpy                     1.11.3           py27he0c0ee4_9
...
pandas                    0.23.3           py27h39f3610_0
...
```

**Comment by reidy-p** [comment]
@H0R5E is this still an issue for you? If so, can you post a [reproducible example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) and I will try to see if I can find the problem.

**Comment by H0R5E** [comment]
@reidy-p, sure here you go:

```
import numpy as np
import pandas as pd

rng = pd.date_range('1/1/2011', periods=2, freq='H')
data = {"a": np.random.randn(len(rng)),
        "b": np.random.randn(len(rng))}
df = pd.DataFrame(data, index=rng)

type(df.to_records()[0][0]) # returns numpy.datetime64, expecting datetime.datetime
```

**Comment by H0R5E** [comment]
My point is that you've made a significant change of behaviour without correcting your docs. The examples show the expected output to be datetime.datetime. There is also no test for which type it should be.

> ```
>         By default, timestamps are converted to `datetime.datetime`:
>         >>> df.index = pd.date_range('2018-01-01 09:00', periods=2, freq='min')
>         >>> df
>                              A     B
>         2018-01-01 09:00:00  1  0.50
>         2018-01-01 09:01:00  2  0.75
>         >>> df.to_records()
>         rec.array([(datetime.datetime(2018, 1, 1, 9, 0), 1, 0.5 ),
>                    (datetime.datetime(2018, 1, 1, 9, 1), 2, 0.75)],
>                   dtype=[('index', 'O'), ('A', '<i8'), ('B', '<f8')])
> ```

I'm surprised I'm the only one to have been caught out by this.

**Comment by TomAugspurger** [comment]
@H0R5E could you submit a PR fixing the docs? Thanks.

**Comment by TomAugspurger** [comment]
You can remove `to_records` from this list too: https://github.com/pandas-dev/pandas/blob/92dcf5f4cce9c7221c8556f0251ec56095cc1b2b/ci/doctests.sh#L24 so that it's tested.
