### ISSUE TITLE
HDFStore Exception: cannot find the correct atom type with pandas to_hdf bug

### ISSUE THREAD

**Issue by nickeubank** [pandas-dev/pandas#18179]
I posted this on [StackOverflow](https://stackoverflow.com/questions/47186347/hdfstore-exception-cannot-find-the-correct-atom-type-with-pandas-to-hdf), but I'm increasingly convinced this is actually a bug, not just a user issue, so moving here. 

[EDIT:] If it helps, the table I read in required I set `encoding='latin-1'` in `read_table`.

#### Code Sample, a copy-pastable example if possible

```python
df['street_address_2010'] = df['street_address_2010'].astype('str')
df[['street_address_2010']].to_hdf('preprocessed.h5', 
                                   key='key', complevel=9, complib='blosc', 
                                   fletcher32=True,
                                   format='table')
```
#### Problem description

    Exception: cannot find the correct atom type -> [dtype->object,items ->Index(['street_address_2010'], dtype='object')] 

#### Expected Output

(none)

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.4.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0.dev0+61.gbc69dc69b
pytest: 3.2.3
pip: 9.0.1
setuptools: 36.6.0
Cython: 0.27.2
numpy: 1.13.3
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.6.5
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.1.0
openpyxl: 2.5.0b1
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: 2.7.3.1 (dt dec pq3 ext lo64)
jinja2: 2.9.6
s3fs: 0.1.2
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

#### Things I've tried

Checked all strings:

    dtypes = df.street_address_2010.apply(lambda x: type(x), convert_dtype=False)

    dtypes.value_counts(dropna=False)
    Out[120]: 
    <class 'str'>    7537988
    Name: street_address_2010, dtype: int64

Saved in chunks, no problems:

    for i in range(0, len(df), 10000):
        df['street_address_2008'].iloc[i:i+10005].to_hdf('preprocessed.h5',
                  key='key', complevel=9, complib='blosc', fletcher32=True,
                  format='table')

**Comment by jreback** [comment]
you can try with an encoding. 
your example is not reproducible by others.

**Comment by nickeubank** [comment]
what's it mean to "try with an encoding"?

Yup, not sure how to get reproducibility. Works for my other string columns in same data. Data file is technically public, but has some data I don't feel comfortable posting on github.

**Comment by jreback** [comment]
you can pass ``encoding='utf-8'`` for example

**Comment by nickeubank** [comment]
Oh, on the read-in (`read_table`) you mean? Throws an error if the encoding isn't set to `latin-1`.

**Comment by jreback** [comment]
no on the writing, but to be honest this is all a wag, w/o an example this is impossible. you can try stepping in yourself. good luck.

**Comment by jorisvandenbossche** [comment]
@nickeubank to make it reproducible: do you still get the error if you only try to write a small subset (a few rows)? (although I suppose not, as it works in chunks you mention) And also if you limit the number of columns (eg to the offensive one)? And then still if you obscure some of the data in? (eg only take part of the addresses, eg slice the first characters of all items in that column)

**Comment by nickeubank** [comment]
@jorisvandenbossche Thanks for the followup! 

Slicing the columns I think did point me to the problem: looks like some rows of the input document weren't parsing, leading to single strings that were millions of characters long. Apparently hdf has a string length limit? Or maybe those long ones have a special character. More experimenting to be done (the files are huge, so each test takes a long time :/ #bigdataproblems ), but if that turns out to be the issue I'll post for future people.

**Comment by dldx** [comment]
@nickeubank Did you manage to figure out your problem? I'm running into the same issue when I try to save a large data frame. If I limit it to only a few thousand rows, I don't have any issues.

**Comment by nickeubank** [comment]
@dldx sorry, was on vacation. My work around was this from above:

> looks like some rows of the input document weren't parsing, leading to single strings that were millions of characters long. Apparently hdf has a string length limit? 

It wasn't that I was looking at a few thousand rows, it's that in looking at a few thousand rows I was omitting the one row that basically had a full spreadsheet crammed into one cell. Check each row's string length and if one is crazy long try excluding it?

**Comment by dldx** [comment]
@nickeubank Thanks for the suggestion! I did try that but it didn't seem to be the issue for me. Very odd.
