### ISSUE TITLE
DataFrame.idxmax returns NaN if all entries are NaN, contradicts idxmax documentation

### ISSUE THREAD

**Issue by ghasemnaddaf** [pandas-dev/pandas#18206]
#### Code Sample, a copy-pastable example if possible

```python
(Pdb) df = pd.DataFrame({'a': [pd.np.nan]*10})
(Pdb) df.idxmax()
a   NaN
dtype: float64
(Pdb) df.idxmax(skipna=True)
a   NaN
dtype: float64
(Pdb) pd.__version__
'0.20.2'
```
#### Problem description

According to [DataFrame.idxmax documentation](https://pandas-docs.github.io/pandas-docs-travis/generated/pandas.DataFrame.idxmax.html): `If an entire row/column is NA, the result will be first index`

#### Expected Output
```
df.idxmax(skipna=True)
a     0
```
#### Output of ``pd.show_versions()``

<details>

------------------
commit: None
python: 3.4.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-4-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_CA.utf8
LOCALE: en_CA.UTF-8

pandas: 0.20.2
pytest: 2.9.1
pip: 9.0.1
setuptools: 36.2.7
Cython: None
numpy: 1.13.0
scipy: 0.19.0
xarray: None
IPython: 5.1.0
sphinx: None
patsy: None
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0b10
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
s3fs: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
the result is correct, its the documentation that is wrong. If you have an all NaN column we have no choice but to return NaN. 

@TomAugspurger

**Comment by ghasemnaddaf** [comment]
ok thanks @jreback for clarifying, I guessed so since series' `idxmax` doc. does not mention that clause.
I think I'll manually do `.fillna(df.apply(lambda x: x.index[0]))` in my code as a workaround

**Comment by jreback** [comment]
@ghasemnaddaf if you'd like to do a PR to clarify in the docs? (in Series as well) would be great.

**Comment by ghasemnaddaf** [comment]
https://github.com/pandas-dev/pandas/pull/18209

**Comment by jorisvandenbossche** [comment]
Given that you typically use the result of idxmax for indexing, I am not sure the NaN behaviour is necessarily that much better than 0

**Comment by jorisvandenbossche** [comment]
Funny thing is that the `idxmin` docstring correctly says the return value is NA if all values are NA.

> Given that you typically use the result of idxmax for indexing, I am not sure the NaN behaviour is necessarily that much better than 0

and given this behaviour has always been like this, I am fine with keeping it like this to be clear. I was just wondering the reason for 0. And you can always use `np.armax` on the values to get a valid indexer (that one does return 0 for the all NaN case)
