### ISSUE TITLE
Deprecate Series.from_array ?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#18213]
I just noticed we have a `Series.from_array` method (I was not conscientiously aware of that :-))

Is there any reason you would want to use that instead of the normal `pd.Series(..)` constructor ?

**Comment by TomAugspurger** [comment]
+1 for deprecating.

**Comment by jreback** [comment]
yep, didn't even know we had this.

**Comment by jorisvandenbossche** [comment]
Looking at the code: the thing it does differently compared to `Series` constructor is that it detects if a SparseArray is passed and in that case returns a SparseSeries. 
Is that a use case we care about?

Further, it is also overridden in SparseSeries. Not sure if it there has a better use case than on plain Series. 
(cc @sinhrks, or who are the Sparse experts nowadays?)

**Comment by jorisvandenbossche** [comment]
Looking at the sparse code, it just passes through exactly to the SparseSeries class constructor, so there it has even less use it seems.
