### ISSUE TITLE
Deprecate Index.summary

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#18217]
```python
In [88]: idx = pd.Index([1, 2, 3])

In [89]: idx.summary()
Out[89]: 'Int64Index: 3 entries, 1 to 3'
```

**Comment by jreback** [comment]
this is also a useless method and should be deprecated

**Comment by gfyoung** [comment]
Well, `Index` has no summary methods like `.info` or `.describe` (vs. `DataFrame` or `Series`).  Might be worthwhile to beef this up so that we can return more meaningful info.

**Comment by jorisvandenbossche** [comment]
I would also deprecate this, and separately we can think wether it is worth to add a `info()` method to Index.

**Comment by punzalan** [comment]
Apologies if any of this is super naive. I'm new.

Deleting the method and any tests directly targeting it isn't enough. There are other failures like

```
__ TestDataFrameReprInfoEtc.test_info_duplicate_columns_shows_correct_dtypes ___

self = <pandas.tests.frame.test_repr_info.TestDataFrameReprInfoEtc object at 0x7f34597891d0>

    def test_info_duplicate_columns_shows_correct_dtypes(self):
        # GH11761
        io = StringIO()

        frame = DataFrame([[1, 2.0]],
                          columns=['a', 'a'])
        frame.info(buf=io)
        io.seek(0)
        lines = io.readlines()
>       assert 'a    1 non-null int64\n' == lines[3]
E       AssertionError: assert 'a    1 non-null int64\n' == 'a    1 non-null float64\n'
E         - a    1 non-null int64
E         ?                 ^^
E         + a    1 non-null float64
E         ?                 ^^^^
```

The reason is the output of `summary` is included in the output of `pandas.DataFrame.info`.

```
In [11]: # pretend the variables in the test are available here

In [12]: lines
Out[12]: 
["<class 'pandas.core.frame.DataFrame'>\n",
 'RangeIndex: 1 entries, 0 to 0\n',
 'Data columns (total 2 columns):\n',
 'a    1 non-null int64\n',
 'a    1 non-null float64\n',
 'dtypes: float64(1), int64(1)\n',
 'memory usage: 96.0 bytes\n']
```

(That second element is the output from `summary`.)

Would it be more appropriate to
* replace `Index.summary` with `Index.info`,
* make `info` more useful (per above comments), and
* update tests?

**Comment by TomAugspurger** [comment]
I would

1. Rename `Index.summary` to `Index._summary`
2. Change anywhere in pandas where we currently use `Index.summary` to `Index._summary`
3. Make a new `Index.summary` that looks like

```python
def summary(self):
    warnings.warn("Index.summary is deprecated and will be removed in a future version")
    return self._summary()
```

**Comment by punzalan** [comment]
Thanks for the feedback. Works for me. I'll get to this soon.

**Comment by GGordonGordon** [comment]
@jreback & @TomAugspurger - Are we planning on just deprecating the Index summary method or the DateTimeIndex summary method as well?

**Comment by jorisvandenbossche** [comment]
@GGordonGordon yes, all Index subclasses would deprecate this
