### ISSUE TITLE
DataFrame.plot() produces incorrect legend labels when plotting multiple series on the same axis

### ISSUE THREAD

**Issue by scottlawsonbc** [pandas-dev/pandas#18222]
#### Code Sample, a copy-pastable example if possible
```python
import pandas as pd
import matplotlib.pyplot as plt
df = pd.DataFrame(data=[[1, 1, 1, 1], [2, 2, 4, 8]], columns=['x', 'r', 'g', 'b'])
fig, ax = plt.subplots(nrows=1, ncols=3)
# Left plot
df.plot(x='x', y='r', linewidth=0, marker='o', color='r', ax=ax[0])
df.plot(x='x', y='g', linewidth=1, marker='x', color='g', ax=ax[0])
df.plot(x='x', y='b', linewidth=1, marker='o', color='b', ax=ax[0])
# Center plot
df.plot(x='x', y='b', linewidth=1, marker='o', color='b', ax=ax[1])
df.plot(x='x', y='r', linewidth=0, marker='o', color='r', ax=ax[1])
df.plot(x='x', y='g', linewidth=1, marker='x', color='g', ax=ax[1])
# Right plot
df.plot(x='x', y='g', linewidth=1, marker='x', color='g', ax=ax[2])
df.plot(x='x', y='b', linewidth=1, marker='o', color='b', ax=ax[2])
df.plot(x='x', y='r', linewidth=0, marker='o', color='r', ax=ax[2])
# Produces correct output when uncommented:
# ax[0].legend()
# ax[1].legend()
# ax[2].legend()
plt.show()
```

#### Problem description
**Note:** Possibly related to #14958, #17939, #14563, however this issue discusses how the behaviour depends on the order in which `df.plot()` is called

- In certain situations, `df.plot()` may generate incorrect legend labels (see example)
- Incorrect legend labels may appear when `df.plot()` plots multiple series on the same axis
- Plotting only one series per axis always appears to produce the correct legend label
- When multiple series are plotted on the same axis:
    - Only the last `df.plot()` call will produce the correct legend label
    - Calling `ax.legend()` after the final `df.plot()` will produce the correct legend entry
- Calling `df.plot()` with `markerstyle=''` always appears produces the correct legend label for that series regardless of the order in which `df.plot()` is called, or the number of other series on the same axis

#### Expected Output
**This is the incorrect output produced by the sample code**
Note that in each plot, only the last series to be plotted has a correct legend label
![image](https://user-images.githubusercontent.com/2927085/32679354-07811222-c61b-11e7-9e3d-603e5a539875.png)
**This is the expected output**
![image](https://user-images.githubusercontent.com/2927085/32679601-cf13659c-c61b-11e7-9e45-d15e8120b8a7.png)

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.4.final.0
python-bits: 64
OS: Linux
OS-release: 4.10.0-37-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.21.0
pytest: None
pip: 9.0.1
setuptools: 36.5.0.post20170921
Cython: None
numpy: 1.13.3
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: 6.1.0
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.1.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by gfyoung** [comment]
cc @TomAugspurger 

@scottlawsonbc : Could you provide snapshots of what you're seeing currently?

**Comment by scottlawsonbc** [comment]
@gfyoung there are two screenshots under the expected output section

**Comment by gfyoung** [comment]
> there are two screenshots under the expected output section

Yes, I see that, but which, if any, represent what you are seeing currently?  Or are both snapshots representative of what you *would expect* to see?

**Comment by scottlawsonbc** [comment]
@gfyoung I understand your question now. I see how the plots are confusing and I should have explained their meaning in a way that is more clear.

At the bottom of my example code, I commented out several lines:

```
# Produces correct output when uncommented:
# ax[0].legend()
# ax[1].legend()
# ax[2].legend()
```

When these lines are commented out, the sample code produces a plot with **incorrect legend labels.** If you run the sample code exactly as I provided in the original issue, then it will produce the erroneous incorrect output.

When these lines are uncommented, the sample code produces a plot with the **correct legend labels.**

In the expected output section of my issue, the first plot shows the output which is incorrect, and the second plot shows what the correct output should be (intended as a reference).

Does this answer your question? I will update my issue to make this more clear.

**Comment by gfyoung** [comment]
Ah, okay.  That makes sense.  If you could update the issue to reflect your answer, that would be great.

**Comment by TomAugspurger** [comment]
@scottlawsonbc do you have time to debug where things are going wrong? https://github.com/pandas-dev/pandas/blob/7f4c960c7d0c100e5df9f0a3bc68401fc4eace4d/pandas/plotting/_core.py#L495 https://github.com/pandas-dev/pandas/blob/7f4c960c7d0c100e5df9f0a3bc68401fc4eace4d/pandas/plotting/_core.py#L384 may be good starting points (or maybe not, haven't touched that code in a while)

**Comment by timisid** [comment]
if you still using multiple series with one axis (like barplot with x,y, and hue options) and the legend still incorect, you can modified the legend using **get_texts()** after **df.plot()**
example:
line 1 ; **df.plot()**
next line : 
L=ax.legend()
L.set_title('modified legend')
**L.get_texts()[0].set_text('b')
L.get_texts()[1].set_text('r')
L.get_texts()[2].set_text('g')**

**Comment by jzlcdh** [comment]
If you need another example of this problem let me know

**Comment by MarcoGorelli** [comment]
Hi @jzlcdh - if you're aware of a new bug then please open a new issue, thanks
