### ISSUE TITLE
read.amazon.com stops working after enabling offline mode

### ISSUE THREAD

**Issue by ibukanov** [pandas-dev/pandas#18230]
After enabling the offline read mode Kindle cloud reader, read.amazon.com, the site stops working claiming the browser is not supported. This is with brave 0.19.80 on Linux.

To reproduce, do the following:

1. Open a new private tab
2. In the new private tab go to read.amazon.com
3. Login with an amazon acount
4. The site should ask about preparing for offline reading. Answer yes.
5. Go to any book.
6. When the book opens, do full reload via Shift-Reload
7. The page complains the the browser no longer supported.

**Comment by gfyoung** [comment]
@ibukanov : Hi there!  I believe you may have posted to he wrong repository.  Closing the issue.
