### ISSUE TITLE
CLN: Remove days, seconds and microseconds properties from timedelta.pyx

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#18242]
xref #18225 

The days, seconds and microseconds properties defined in timedelta.pyx could potentially be removed as they are defined in the Cython superclass. See Jeff's comments in the linked PR for caveats that need to be explored before totally committing to this.

**Comment by WillAyd** [comment]
Here's what I got from ASV after removing those properties. Note that there is no nanoseconds property in CPython's source, so that will need to remain here for the time being

       before         after       ratio
       215±4ns        167±4ns     0.78  timedelta.TimedeltaProperties.time_timedelta_days
       212±4ns        155±2ns     0.73  timedelta.TimedeltaProperties.time_timedelta_microseconds
       210±3ns        149±3ns     0.71  timedelta.TimedeltaProperties.time_timedelta_seconds

From a few runs it looks like me like savings could be 20-25%. You've called out before that this will make our docstrings inconsistent and its a little clunky since nanoseconds would still be around. On the flip side, its less code for pandas and gives a slight performance boost. Worth a PR?

**Comment by jreback** [comment]
``nanoseconds`` is unsupported in CPython, so that has to remain.

I am not sure the doc-strings are a big deal, ``Timedelta`` doc-strings are a bit sparse ATM as well :>

so if you want to do this change would be ok.
