### ISSUE TITLE
DEPR: deprecate get_ftype_counts

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#18243]
These are only to provide some inside into a sparse dtype. These should in theory be encoded in the dtypes (in pandas2), but in reality these are just cluttering the API and actually an implementation detail.

**Comment by jorisvandenbossche** [comment]
As context, you can put a sparse data in a normal dataframe:

```
In [10]: df = pd.DataFrame({'a': [1, 2, 3]})

In [11]: df['b'] = pd.SparseSeries([3, 4, 5])

In [12]: df
Out[12]: 
   a  b
0  1  3
1  2  4
2  3  5

In [13]: df.dtypes
Out[13]: 
a    int64
b    int64
dtype: object

In [14]: df.ftypes
Out[14]: 
a     int64:dense
b    int64:sparse
dtype: object

In [16]: df['b']
Out[16]: 
0    3
1    4
2    5
Name: b, dtype: int64
BlockIndex
Block locations: array([0], dtype=int32)
Block lengths: array([3], dtype=int32)
```

The question is: what is the alternative to easily check if a certain column is sparse ?

**Comment by grutts** [comment]
Happy to add the deprecation warnings for the usage of these. Is there something in particular that they should be replaced with, or just removed in a future version? Also, presuming .ftype is to be left as is?

**Comment by GGordonGordon** [comment]
The pull request only deals with deprecating .get_ftype_counts() and doesn't touch .ftypes since there was still some uncertainty around its deprecation.

xref #18262
