### ISSUE TITLE
RLS 0.21.1

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#18244]
closes https://github.com/pandas-dev/pandas/issues/18530

---

# Release Checklist

This template can be copied into the RLS issue for a release and checked off as you go.

## Pre-Release

- [x] Open a pre-release issue and mention related parties. (A few weeks before release) with this template.
- [x] Clear the bug queue
- [x] Run an ASV: `cd asv_bench; asv continuous -f 1.1 $(git describe --abbrev=0)..HEAD``
- [x] Review deprecations from previous releases [here](https://github.com/pandas-dev/pandas/issues/6581)
- [x] Review experimental features from previous releases [here](https://github.com/pandas-dev/pandas/issues/5049)
- [x] Clean up release.rst (contributors and stats will be done later)
- [x] Clean up whatsnew.rst
- [x]  Run a full doc build and make sure everything is clean
  ```
  ./make.py clean; ./make.py; ./make.py zip_html;  ./make.py latex_forced
  ```
    + [x] Check the output, check whatsnew and release.rst for formatting errors.
- [x] run ``build_dist.sh``, uninstall cython and make a test install of the tarball to ensure
  cython is not required for installation from tarball/pypi (now also part of travis scripts, but check).
- [x] Ensure you have SSH access to `pandas.pydata.org` (@TomAugspurger or [Andy Terrel](http://github.com/aterrel) should be able to get you an account).
- [x] Ensure you have upload rights to PyPI (Wes or Jeff)
- [x] Ensure you have commit rights on github.com/macPython/pandas-wheels/ and github.com/conda-forge/pandas-feedstock

### Final Pre-Release

To be done just before tagging the commit. This is optional for release-candidates.

- [x] Call a hold on master in the pre-release issue before you start.
- [x] Finalize the documentation by running the
    + [x] Run `scripts/announce.py` and add to `release.rst`
    + [x] Update the release date in `release.rst` and `whatsnew/<version>.rst`
- [x] Commit the doc changes

### Tag the Release

- [x] Create an empty commit: `git commit --allow-empty -m 'RLS: v0.20.0'`
    + For Release-Candidates, it's `-m 'RLS: v0.20.0.rc2'`
- [x] Create the tag: `git tag -a v0.20.0` -m "Version 0.20.0"

### Test the Release

Some local sanity tests before pushing, making the release official

- [x] Build the release
  + Conda:
```
# build a conda package
conda build ./conda.recipe --numpy 1.11 --python 2.7 -q --output

# fresh conda env
conda create -n pandas_0.18.2_test python=2.7 pandas nose

# build and install into that env
conda install -n pandas_0.18.2_test pandas --use-local

# switch to that env & test
source activate pandas_0.18.2_test
import pandas as pd
pd.test()
```
  + Pip

```
# build the wheel
python setup.py bdist wheel

# activate another environment
workon pandas-test
pip uninstall -y pandas
pip install <path/to/wheel>
python -c "import pandas; pandas.test()"
```
- [x] Build the docs. Check the version number and release notes

### Push the Release

This is where things become final. **No going back once the tagged commit is pushed**

- [x] Push the release
    + Major release: `git push upstream master --follow-tags`
    + Maintenance:   `git push upstream 0.20.x --follow-tags` 
  
### Build Source Distribution

- [x] `python setup.py sdist --formats=gztar` (TODO: update build_dist.sh to handle maintenance branches)

### Release on Github

- [x] Draft a new release [here](https://github.com/pandas-dev/pandas/releases/new)
- [x] If this is an RC, check the box saying it's a pre-release
- [x] Upload the `pandas-<version>.tar.gz` from the previous step as a "binary"
- [x] Generate the SHA256 for the release with `openssl dgst -sha256 dist/pandas-<version>.tar.gz`
  We use the SHA from our .tar.gz since the one auto-generated by Github isn't stable if the release page
  is later modified.

### Build Binary Distributions

Windows wheels are built automatically by Christoph Gohlke.

- [x] Open a PR for Mac and Linux wheels to update the `BUILD_COMMIT` [here](https://github.com/MacPython/pandas-wheels/blob/master/.travis.yml)
- [x] *Final Release Only* Open a PR for the [pandas-feedstock](https://github.com/conda-forge/pandas-feedstock)
    + [x] Update the version
    + [x] Update the SHA256
    + [x] Set the build number 5to 0

### Download Binary Distributions

Conda-Forge is handled automatically. We handle wheels.

- [x] Windows wheels from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#pandas)
- [x] Mac / Linux wheels with `python scripts/fetch_wheels.py`, from [here](http://wheels.scipy.org/)

### Upload to PyPI

**Upload the source and wheels simultaneously**. Uploading just the source may break some users'
workflows, if they trigger an update but don't have a C-complier

- [x] Assuming you've downloaded everything to `dist`: `twine upload dist/*`
- [x] You may want to hide the release until the docs are up and announcement is sent out

### Build and Upload the Docs

- [x] Build and upload
```
cd docs;
./make.py clean; ./make.py; ./make.py zip_html;  ./make.py latex_forced
python make.py upload 0.20.2
```

## Update the Website

- [x] clone the repo: ``https://github.com/pandas-dev/pandas-website.git``
- [x] *major only*: Move `latest.rst` to `previous.rst`
- [x] Update `latest.rst`
- [x] Update `releases.json` and `pre_release.json` (if RC, add to pre_release.json, else make it blank)
- [x] Update `_themes/pydata/layout.html` to have the most recent minor release of each major version
- [x] commit and push
- [x] build: `python make.py html`
- [x] upload: `python upload.py`  # TODO: verify this works
- [x] Verify it updated (maybe in an incognito browser to avoid caching)

## Announce 

- [x] Make sure everything is in place
  - [x] pypi binaries for windows, mac wheels, source
  - [x] docs built and published
  - [x] website updated
- [x] Send an ANN to the mailing list. include links to both release notes and whatsnew.
- send announcements to pydata@googlegroups.com, numpy-discussion@scipy.org, python-announce-list@python.org, scipy-user@scipy.org, pandas-dev@python.org

** Final Version**
  * [0.20.3](https://groups.google.com/d/msg/pydata/DNm4EjBHFq0/zessb6VUBAAJ)
  * [0.20.2](https://groups.google.com/d/msg/pydata/EklxoMXYYmU/HUOj8CeHAwAJ)
  * [0.20.1](https://groups.google.com/d/msg/pydata/N_D_3NQc_XI/5RP9bbsFBgAJ)
  * [0.19.2](https://groups.google.com/d/msg/pydata/-EhcScH5HBU/FWpIfs6RDwAJ)
  * [0.19.1](https://groups.google.com/d/msg/pydata/46op7I7NESc/qorGKhh5CAAJ)
  * [0.19.0](https://groups.google.com/forum/#!topic/pydata/czhBNkQZGFA)
  * [0.18.1](https://groups.google.com/forum/#!topic/pydata/VCvVVI0dKOM)
  * [0.18.0](https://groups.google.com/forum/#!topic/pydata/VXPVa4QVVMI)
  * [0.17.1](https://groups.google.com/forum/#!topic/pydata/dyZsC4SiolQ)
  * [0.17.0](https://groups.google.com/forum/#!topic/pydata/2nUh2UenY_o)
  * [0.16.2](https://groups.google.com/forum/#!topic/pydata/slgCenzHrZU)
  * [0.16.1](https://groups.google.com/forum/#!topic/pydata/rc9sZV81RtU)
  * [0.16.0](https://groups.google.com/forum/#!topic/pydata/4KKZFpxS_4o)
  * [0.15.2](https://groups.google.com/forum/#!topic/pydata/A48I-Mu6RUk)
  * [0.15.1](https://groups.google.com/forum/#!topic/pydata/NDY11PDTL9w)
  * [0.15.0](https://groups.google.com/forum/#!topic/pydata/6tG903k02KU)
  * [0.14.1](https://groups.google.com/forum/#!topic/pydata/kTDutuXEBs0)
  * [0.14.0](https://groups.google.com/forum/#!topic/pydata/wHM435aVjUw)
  * [0.13.1](https://groups.google.com/forum/#!topic/pydata/bp8bioTbDWM)
  * [0.13.0](https://groups.google.com/forum/#!searchin/pydata/ANN/pydata/7RT82JwDmbg/Pdw3MssGN3gJ)
  * [0.11.0](https://groups.google.com/forum/#!searchin/pydata/pandas$20release/pydata/g-8q58WZNvs/La7b5FvPP04J)

** Release Candidates **

  * [0.20.0rc1](https://groups.google.com/d/msg/pydata/je6H3GvVzng/v9JLLIm-AQAJ)
  * [0.18rc2](https://groups.google.com/forum/#!topic/pydata/XiyF7kpozqk)
  * [0.18rc1](https://groups.google.com/forum/#!topic/pydata/izaTcjLmY1g)
  * [0.17rc2](https://groups.google.com/forum/#!topic/pydata/k03SQiBG3jc)
  * [0.17rc1](https://groups.google.com/forum/#!topic/pydata/xeJWmewJboA)
  * [0.16rc1](https://groups.google.com/forum/#!topic/pydata/IahnI8gYD8o)
  * [0.15rc1](https://groups.google.com/forum/#!topic/pydata/36tu9MYhYmA)
  * [0.14rc1](http://groups.google.com/forum/#!topic/pydata/Bx8oiSAZwOc)
  * [0.13rc1](http://groups.google.com/forum/#!searchin/pydata/pandas00.13.00release/pydata/OHutLByJvK0/_Y6pD66eefwJ)

## Start the next release cycle

**Only after a major release**

When finishing a major release we have a few extra steps to ensure that
the development version is always ahead of the backports version.

- [ ] Create a backports branch off the release commmit, e.g. `git checkout -b 0.20.x master`
- [ ] Push that to upstream: `git push -u upstream 0.20.x`
- [ ] Switch back to master and make a new commit to start the next cycle
    - `git checkout master`
    - `git commit --allow-empty -m 'DEV: Start 0.21 cycle'`
    - `git tag -a v0.21.0.dev0 -m 'Version 0.21.0 start'`
    - `git push upstream master --follow-tags`
- [ ] Ensure that a whatsnew file is available for the next major and minor releases

## Finish

- [ ] Close the Milestone on github
- [ ] Close the RLS issue

Miscellany I haven't gotten to yet.

#### Update documentation
- Get commits since last release:  
  `git log v0.18.1.. --format='%an#%s' | grep -v Merge > commits`
- Include a summary by contributor in release notes (`release.rst`):  
  `cat commits | gawk -F '#' '{ print "- " $1 }' | sort | uniq`
- Run [release_stats.sh](https://github.com/pandas-dev/pandas/blob/master/release_stats.sh) to get number of contributors and commits.
- In release notes/whatsnew, update release date.
- Update release notes (`release.rst` with highlights of whatsnew).

**Comment by jorisvandenbossche** [comment]
> Do we want to include any / all of the items currently in 0.21.1.txt?

I would already include those things that are labeled for 0.21.1. We already had some regression fixed, so IMO it would be a bit stupid not to include this.

**Comment by jreback** [comment]
yes this should include amy backports

**Comment by jreback** [comment]
let’s wait till the meeting to discuss 

no really pressing PRs

**Comment by topper-123** [comment]
It there any chance someone could take a look at #18051 for 0.21.1?

The issue is that ATM, if you are not absolutely sure that all values in a categorical series are not ``nan``, you cannot use ``.unique`` and ``.nunique`` with series of categoricals, (or, you can wrap them in a ``try/except``statement, though is bit ugly and easy to forget the need of).

**Comment by shoyer** [comment]
Let's not forget:

- https://github.com/pandas-dev/pandas/issues/18301: Deprecate automatically registering matplotlib units (partial revert of 0.21.0)

**Comment by jorisvandenbossche** [comment]
> #18301: Deprecate automatically registering matplotlib units (partial revert of 0.21.0)

Yes, given the continuing stream of bug reports about that one, it would be nice to get a fix out as soon as possible. Although the sum needs some more time to discuss ...

**Comment by jorisvandenbossche** [comment]
So we should plan for the 0.21.1 release. @TomAugspurger has some time the coming days (and I am also available to help).

Regardless of the following questions, we can already start backporting and fixing the remaining issues https://github.com/pandas-dev/pandas/milestone/52. 

But the questions we need to answer:

- Do we release "0.21.1" (the first thing we release) as it is now (once everything tagged 0.21.1 is merged / backported), or do we include the `sum` change? (assuming we are going to change it, although this is still subject to the result of the discussion)

and depending on that we need to discuss whether we call that 0.21.1 or 0.22.0, but let's first decide on the above question (again, which is tied to the result of the discussion, so the question is maybe more: do we wait on that, or we think we are ready to decide on it now).

**Comment by jreback** [comment]
yeah the remaining issues I have only tagged if they are basically ready to merge. So I would say we could release at any time for 0.21.1 (obivously need to actually backport things :>) and prob some small doc cleanups in whatsnew. This should be 0.21.1. If/when we change the whole ``.sum()`` this would need to be a major release, and sit in master for a bit.

**Comment by jorisvandenbossche** [comment]
>  If/when we change the whole .sum() this would need to be a major release, and sit in master for a bit.

IMO we shouldn't let that sit in master for a bit, but release as quick as possible (and quick as possible might still mean a rc etc). 
And, I also think we should not include many other API changes. So even if we call it 0.22.0, I would do this release of the 0.21.x branch. Which means in practice re-purposing the existing 0.22 milestone as 0.23 (because the things we merged there can use some more time in master + because it will be easier to deal with downstream)

**Comment by jreback** [comment]
why?

we have a bug fix release already teed up. conflating a major change is just not a great idea. We have contentious small sample feedback, why would you exacerbate things?

**Comment by jorisvandenbossche** [comment]
Because, supposing we go for option 1, we are changing the behaviour *again*. The longer we wait with doing this, the more people start relying on the intermediate behaviour that will go away, the more packages will need to implement workarounds, etc.

**Comment by jreback** [comment]
and there is no consensus on option 1.

**Comment by jorisvandenbossche** [comment]
Then please take the time to answer on the mailing list

**Comment by TomAugspurger** [comment]
Since https://github.com/pandas-dev/pandas/issues/18678 seems to be stuck at the moment, I propose that we clear the 0.21.1 issue list and do a release today.

https://github.com/pandas-dev/pandas/pull/18629 should be mergable, https://github.com/pandas-dev/pandas/pull/18715 may have to wait for a fastparquet release.

**Comment by TomAugspurger** [comment]
Alright, everything has been backported. The only remaining issue is the bad wheels on PyPI, which will be fixed by the release.

@jreback, @shoyer, @gfyoung, @chris-b1, any objections to releasing 0.21.1 as is on the 0.21.x branch?

**Comment by jreback** [comment]
lgtm

**Comment by TomAugspurger** [comment]
Everything should be in place. I'll tag it tomorrow morning unless something comes up.

**Comment by TomAugspurger** [comment]
It seems like Christoph is building wheels against CPython 3.7 too: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pandas Unless anyone objects, I'll upload those to PyPI as well.

- Mac and Linux wheels are building: https://travis-ci.org/MacPython/pandas-wheels/builds/315499578
- Conda-Forge is building
- Anaconda defaults has already been updated

I'll send the announce out when the wheels are done.

**Comment by TomAugspurger** [comment]
Yep. I figure the two options are

1. We don't upload the wheels, and 3.7 users build from source. Stuff
either works or it doesn't.
2. We do upload the wheels, and users get the binary. Stuff either works or
it doesn't.

We know 0.21.1 builds on 3.7 on Windows, since Christoph was able to build
it. By uploading those
wheels, we get a bit more exposure to see if there are any issues with his
build system on 3.7, which
would be good to sort out early.

I don't know if uploading wheels for 3.7 is saying that "3.7 is officially
supported for pandas 0.21.1". I'd
say no.

**Comment by cgohlke** [comment]
> It seems like Christoph is building wheels against CPython 3.7 too: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pandas Unless anyone objects, I'll upload those to PyPI as well.

Better not. These wheels are built with Python 3.7a3 and Visual Studio 2017. They might not work with later 3.7 releases. I'm just starting to test the scipy stack with Python 3.7 and VS 2017.

**Comment by TomAugspurger** [comment]
Thanks for clarifying @cgohlke.

**Comment by gfyoung** [comment]
> we have no testing at all against 3.7

I think Travis has an image for Python 3.7, so maybe in the future, we could consider?

**Comment by jreback** [comment]
we don’t use the travis images at all

only conda

**Comment by TomAugspurger** [comment]
Wheels are done, announcement is sent. Thanks everyone.

**Comment by jorisvandenbossche** [comment]
@TomAugspurger Thanks a lot for the release!

**Comment by jreback** [comment]
thanks @TomAugspurger it seems so easy now with your checklist!! hahaha

**Comment by TomAugspurger** [comment]
Only a few dozen steps :)

**Comment by wesm** [comment]
thanks @TomAugspurger!

**Comment by shoyer** [comment]
Thanks!
