### ISSUE TITLE
pandas.MultiIndex.reorder_levels has no inplace argument

### ISSUE THREAD

**Issue by wmoreland** [pandas-dev/pandas#18246]
#### Code Sample
If I create a DataFrame with a MultiIndex like so:

```python
import pandas as pd
import numpy as np
midx = pd.MultiIndex(levels=[['zero', 'one'], ['x','y']], labels=[[1,1,0,0],[1,0,1,0]])
df = pd.DataFrame(np.random.randn(4,2), index=midx)
```
and then try to reorder the indices with `pd.MultiIndex.reorder_levels()` like so:

```python
df.reorder_levels([1, 0])
```
nothing happens. However, if I do:

```python
df = df.reorder_levels([1, 0])
```
then the indices are rearranged as expected.

#### Problem description
In other functions, such as `pd.DataFrame.set_index()`, there is the option to either reassign the DataFrame or carry out the function in place. There is no `inplace` argument for reorder_levels and this seems out of place with the rest of Pandas' functions.

It's obviously just my opinion but what do you think? Should reorder_levels not have an `inplace` argument?

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: AMD64 Family 16 Model 2 Stepping 3, AuthenticAMD
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.21.0
pytest: 3.2.3
pip: 9.0.1
setuptools: 36.6.0
Cython: 0.27.3
numpy: 1.13.3
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.6.5
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.1.0
openpyxl: 2.5.0b1
xlrd: 1.0.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.1
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jbrockmendel** [comment]
For the most part we're moving towards deprecating `inplace` args, so i doubt this is going to change

**Comment by mroeschke** [comment]
Agreed, there is a push to remove `inplace` so I would be -1 toward this change. Closing as there hasn't been much traction or support otherwise.
