### ISSUE TITLE
DEPS: drop 2.7 support

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#18241]
some sample text from numpy folks.

xref https://github.com/numpy/numpy/pull/10006

**Comment by jreback** [comment]
cc @charris 
cc @njsmith

**Comment by jorisvandenbossche** [comment]
We are already listed on the http://www.python3statement.org/ page, although of course very vague (without an explicit timeline, which means: no python2 support at latest from 2020). 
It might be good to have some similar statement in the pandas docs itself, although the exact practicalities of timeline might depend on how things go with pandas 1.0 / 2.0.

**Comment by jreback** [comment]
lol w did this!
