### ISSUE TITLE
_decorators.Substitition fails on class docstring

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#18284]
```
from pandas.util._decorators import Substitution

@Substitution('Jason')
class Foo(object):
	"""Author is %s"""
	def __init__(self):
		pass
```

--> `AttributeError: attribute '__doc__' of 'type' objects is not writable`

This shouldn't be hard to fix, just parking it here for now.  The motivating use case is over in statsmodels where Model subclass docstrings can be really repetitive.

**Comment by jorisvandenbossche** [comment]
FWIW, I don't think that statsmodels should be using a private helper function of pandas. If we think it is really useful for other projects, then let's discuss to expose it publicly. 
(but personally I wouldn't do that, statsmodels can also just copy paste the code)

**Comment by jbrockmendel** [comment]
Yah, statsmodels wasnt using it, just me in a branch.  IIUC pandas got some of these decorators from matplotlib, so there probably is enough community usefulness for _someone_ to make it public.  But totally fair to let that be someone else.

statsmodels copy/pasting all over the place is an entirely separate can of worms.

**Comment by jbrockmendel** [comment]
I may revisit this at some point, but no need to clog the issue tracker with a non-issue.  Closing.
