### ISSUE TITLE
ImportError: C extension: numpy.core.multiarray failed to import not built.

### ISSUE THREAD

**Issue by maestropandy** [pandas-dev/pandas#18281]
When I am installing devstack-single node openstack package, It needs pandas, while installing facing error as below

>  ImportError: C extension: numpy.core.multiarray failed to import not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.

If do manual installation of pandas by using "python setup.py build_ext --inplace --force" from source its running fine, but cannot instruct other dependencies software to clone and do it forcefully. 

it will be good if installed normally than force inplace

**Comment by maestropandy** [comment]
Here is the call from openstack script to install numpy


`# numpy compat
from pandas.compat.numpy import *

try:
    from pandas._libs import (hashtable as _hashtable,
                             lib as _lib,
                             tslib as _tslib)
except ImportError as e:  # pragma: no cover
    # hack but overkill to use re
    module = str(e).replace('cannot import name ', '')
    raise ImportError("C extension: {0} not built. If you want to import "
                      "pandas from the source directory, you may need to run "
                      "'python setup.py build_ext --inplace --force' to build "
                      "the C extensions first.".format(module))
`

**Comment by gfyoung** [comment]
@maestropandy : Thanks for reporting this!  Looks like a `numpy` issue though IIUC.  Not sure how `pandas` would help you out here?

**Comment by TomAugspurger** [comment]
@maestropandy for us to help, you'll need to provide more info on how you're installing things.

**Comment by samlcharreyron** [comment]
I have the same issue on OSX Sierra when using homebrew python and numpy and installing pandas via pip.

**Comment by jorisvandenbossche** [comment]
Yes, this is an issue with the wheels hosted on PyPI for 0.21.0 (our bad). You can pip install a new version of the wheels with the command specified here: https://github.com/pandas-dev/pandas/issues/18530#issuecomment-347478841

Closing this as it is covered by https://github.com/pandas-dev/pandas/issues/18530
