### ISSUE TITLE
DOC: Parquet IO docs don't match code

### ISSUE THREAD

**Issue by mattayes** [pandas-dev/pandas#18285]
#### Problem description

The [Parquet section of the IO docs](https://pandas-docs.github.io/pandas-docs-travis/io.html#parquet) mentions the following caveat:

> The format will NOT write an Index, or MultiIndex for the DataFrame and will raise an error if a non-default one is provided. You can simply .reset_index(drop=True) in order to store the index.

This conflicts with the [error messages](https://github.com/pandas-dev/pandas/blob/63e8527d32aaf6afe1cd4b2a7b3bfadb088c9a72/pandas/io/parquet.py#L149-L169), which recommends:

> you can .reset_index() to make the index into column(s)

#### Expected Output

AFAIK the error message is correct and the IO docs should remove `drop=True`:

> The format will NOT write an Index, or MultiIndex for the DataFrame and will raise an error if a non-default one is provided. You can simply .reset_index() in order to store the index.

I'm happy to submit a PR for this.

**Comment by jorisvandenbossche** [comment]
Yes, the `drop=True` indeed seems incorrect if the goal is to store the index (or you could mention both options: `drop=True` to ignore the index). PR very welcome!
