### ISSUE TITLE
get_value_box duplication

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#18299]
`tslib.get_value_box` seems out of place.  The only place it is used is in `base.index`.  Meanwhile `_libs.index.get_value_at` looks very similar but is never used.  (It also looks similar to a chunk of code in `IndexEngine.get_value`

Is it possible that `index.get_value_at` was intended to replace `tslib.get_value_box`?

**Comment by gfyoung** [comment]
@jbrockmendel : Have a look at the blame tab on GitHub for this file.  That might be of use, though other maintainers probably know better than I here.
