### ISSUE TITLE
DataFrame.unstack(label) accepts wrong labels if index is flat

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#18303]
#### Code Sample, a copy-pastable example if possible

```python
In [2]: df = pd.DataFrame(index=range(2), columns=pd.MultiIndex.from_product([range(2), range(2)]))

In [3]: df.unstack('mistake')
Out[3]: 
0  0  0    NaN
      1    NaN
   1  0    NaN
      1    NaN
1  0  0    NaN
      1    NaN
   1  0    NaN
      1    NaN
dtype: object


```
#### Problem description

An error should be raised.

#### Expected Output

``KeyError``

#### Output of ``pd.show_versions()``

<details>

In [4]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit: 63e8527d32aaf6afe1cd4b2a7b3bfadb088c9a72
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-3-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.22.0.dev0+131.g63e8527d3
pytest: 3.2.3
pip: 9.0.1
setuptools: 36.7.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.0dev
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.0
openpyxl: None
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.6
lxml: None
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.2.1

</details>

**Comment by gfyoung** [comment]
@toobaz : Do you know if there was a release where an error should have been raised, or are you suggesting that we change the API to raise `KeyError` in a situation like this?

**Comment by toobaz** [comment]
Yes, I'm suggesting it should raise a ``KeyError``, like ``pd.Index([]).get_level_values('mistake')`` does. 

By the way, I've always found the error message ``KeyError: 'Level mistake must be same as name (None)'`` raised by the latter confusing... I would suggest harmonizing with the error raised by ``MultiIndex.get_level_values("mistake")`` (that is, ``KeyError: 'Level "mistake" not found'``), and/or to add info on the available names (``KeyError: 'Level "mistake" not found in index level names ([None])'``).

**Comment by gfyoung** [comment]
@toobaz : Ah, okay, so not quite answering my question, BUT that's fine since your answer is pretty good justification for the issue anyhow.

As for your other point, yes, that's also fair.  If you want, you can open another issue for that OR just open a PR to patch the behavior if it's clear how to fix.
