### ISSUE TITLE
Assignment to uint series drops datatype

### ISSUE THREAD

**Issue by jeremywhelchel** [pandas-dev/pandas#18311]
Assigning a uint value to a slice of a uint series results in a dataframe of type int.

```python
s = pd.Series([1,2,3], dtype='uint64') # Also happens with other uint dtypes
s.loc[0] = 4
s
```
With Pandas 0.19.2, this returns:
```
0    4
1    2
2    3
dtype: uint64
```

With version 0.21.0, the dtype gets lost and replaced with int64:
```
0    4
1    2
2    3
dtype: int64
```

**Comment by gfyoung** [comment]
Yeah, `uint64` should get better treatment than that!  Feel free to do a `git bisect` to determine where the bug lies in this case.

**Comment by kokes** [comment]
`git bisect` gives me 4efe6560e07f28de6a1834fa90e31cef31b0fb18 as the first bad commit, and unfortunately, it's a big one.

**Comment by mroeschke** [comment]
Looks to work on master now. Could use a test:

```
In [70]: s
Out[70]:
0    4
1    2
2    3
dtype: uint64

In [71]: pd.__version__
Out[71]: '0.26.0.dev0+576.gde67bb72e'
```
