### ISSUE TITLE
pd.crosstab(s1, s2) keeps dummy MultiIndex as columns if both s1 and s2 have tuple name

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#18321]
#### Code Sample, a copy-pastable example if possible

```python
In [2]: s1 = pd.Series(range(3), name=('a', 'b'))

In [3]: s2 = pd.Series(range(3), name=('c', 'd'))

In [4]: pd.crosstab(s1, s2)
Out[4]: 
                   
('c', 'd')  0  1  2
(a, b)             
0           1  0  0
1           0  1  0
2           0  0  1

In [5]: list(pd.crosstab(s1, s2).columns)
Out[5]: [('', 0), ('', 1), ('', 2)]
```

#### Problem description

While the example is similar to that reported in #18304, the fix doesn't seem to be related. Reminder: test by expanding the test in #18309 .

#### Expected Output

``` python
In [5]: list(pd.crosstab(s1, s2).columns)
Out[5]: [0, 1, 2]
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: 9c799e2c4331e5e42cfda03323eef165feb5be1a
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-3-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.22.0.dev0+135.g9c799e2c4
pytest: 3.2.3
pip: 9.0.1
setuptools: 36.7.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.0dev
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.0
openpyxl: None
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.6
lxml: None
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.2.1

</details>

**Comment by blueTaxi** [comment]
Hi, I want to work on this.

**Comment by toobaz** [comment]
@blueTaxi I had this old branch around:

https://github.com/toobaz/pandas/tree/crosstab_tuple_names

... I didn't push it so I guess it didn't work... but you might want to try the trivial change.

**Comment by blueTaxi** [comment]
@toobaz thanks. I'll have a look!
