### ISSUE TITLE
Center rolling window that does not include center value

### ISSUE THREAD

**Issue by MathieuCliche** [pandas-dev/pandas#18328]
I need a way to apply a custom function on a rolling dataframe where the centered value is not included.  

This code below works well, but it does include the center value:

```
import pandas as pd
import numpy as np

mad = lambda x: np.mean(np.fabs(x - np.median(x)))

df = pd.DataFrame([1,1,1,10,1,1,1,2,2,2,2,2,20,2,2,2,2])

df.rolling(3, min_periods=3, center=True).apply(mad)
```

And this code below does not include the center, but only allows me to do mean or sum, no custom function:

```
import pandas as pd
import numpy as np

df = pd.DataFrame([1,1,1,10,1,1,1,2,2,2,2,2,20,2,2,2,2])

df.rolling(window=[1,0,1], win_type='boxcar', center=True, min_periods=3).mean()
```

Is there a way I am missing that would allow me to compute my custom function (mad) which does not include the center value?

**Comment by sinhrks** [comment]
When you specify a `window` kw, it returns `Window` class which doesn't have `apply` rather than `Rolling` . 

Is this what you want?

```
mad = lambda x: np.mean([1, 0, 1] * np.fabs(x - np.median(x)))
df.rolling(3, min_periods=3, center=True).apply(mad)
```

**Comment by MathieuCliche** [comment]
Oh yeah that works, didn't think about that.  Thanks!
