### ISSUE TITLE
TST: split out melt-tests in pandas/tests/reshape/test_reshape.py

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#18367]
since ``melt`` and friends were moved to ``pandas/core/reshape/melt.py`` want to follow suit with the tests.

if you want to go once further and split out the ``melt``, ``wide_to_long`` and ``lreshape`` tests to a new sub-module, e.g. ``pandas.tests.reshape.melt.test_melt, test_lreshape, test_wide_to_long`` would not object.

**Comment by jreback** [comment]
cc @tdpetrou

**Comment by tdpetrou** [comment]
Sure I can do this. I'll just keep it to one file `test_melt` for now.
