### ISSUE TITLE
We should have a test_requires

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#18364]
https://github.com/pandas-dev/pandas/pull/18349#discussion_r151851652

> we should have a test_requires, but that's separate. can you open an issue for that.

**Comment by jbrockmendel** [comment]
@jreback not sure how to make this actionable?  Still needed?

**Comment by jreback** [comment]
i think can add to setup.py ?

**Comment by jbrockmendel** [comment]
Pretty sure that was the original idea, but no idea what was supposed to go in it.
