### ISSUE TITLE
Using DataFrame.insert leads to the SettingWithCopyWarning

### ISSUE THREAD

**Issue by konstantinmiller** [pandas-dev/pandas#18360]
The last line in the following code generates a SettingWithCopyWarning while it obviously shouldn't.

```python
import pandas as pd

df = pd.DataFrame(data={'a': [1]})
df.insert(column='b', loc=0, value=pd.NaT)
df['a'].iloc[0] = 5
```

EDIT: If a non-null value is used instead of pd.NaT, no warning is generated.

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.0.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.20.2
pytest: 3.0.5
pip: 9.0.1
setuptools: 36.0.1
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.1
xarray: None
IPython: 6.1.0
sphinx: 1.5.1
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: 1.2.1
tables: 3.3.0
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.1
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.8.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.5
pymysql: None
psycopg2: None
jinja2: 2.9.4
s3fs: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
you are chained indexing: http://pandas.pydata.org/pandas-docs/stable/indexing.html#returning-a-view-versus-a-copy
