### ISSUE TITLE
REF: Rework core.dtypes.cast.maybe_promote

### ISSUE THREAD

**Issue by mattayes** [pandas-dev/pandas#18396]
#### Problem description

[xref #18313](https://github.com/pandas-dev/pandas/pull/18313#issuecomment-345540449)

> note if you are interested in cleaning some things up :>
>
> maybe_promote I think will pretty much ignore its fill value for almost all dtypes. So the question is, when is it not ignored, can we safely remove it (or really just make the default fill_value=None, and then when its not None actually do something.
>
> Not sure of the answer here.

**Comment by mattayes** [comment]
@jreback Could you expand on the options you're considering?

**Comment by jreback** [comment]
see how/when ``maybe_promote`` is called. I suspect we don't actually use the passed in fill arg. If so we can dispense with it. but maybe I am wrong and it *is* used. In that case, the default should be ``fill_value=None``, just makes it more clear.

**Comment by jbrockmendel** [comment]
Closed by #28913
