### ISSUE TITLE
resample() + value_counts() = "ValueError: operands could not be broadcast together with shape"

### ISSUE THREAD

**Issue by rmalouf** [pandas-dev/pandas#18393]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
from random import choice, randint

df = pd.DataFrame()
df['val'] = [choice(['a','b','c','d']) for _ in range(500)]
df['time'] = pd.to_datetime([randint(1511200000, 1511300000) for _ in range(500)], unit='s')
df = df.set_index('time')

df.resample('T')['val'].value_counts()
```

#### Problem description

The code above raises the exception:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-9d1392a98589> in <module>()
----> 1 df.resample('T')['val'].value_counts()

/opt/local/lib/python3.6/site-packages/pandas/core/groupby.py in value_counts(self, normalize, sort, ascending, bins, dropna)
   3400 
   3401         # multi-index components
-> 3402         labels = list(map(rep, self.grouper.recons_labels)) + [llab(lab, inc)]
   3403         levels = [ping.group_index for ping in self.grouper.groupings] + [lev]
   3404         names = self.grouper.names + [self._selection_name]

/opt/local/lib/python3.6/site-packages/numpy/core/fromnumeric.py in repeat(a, repeats, axis)
    396 
    397     """
--> 398     return _wrapfunc(a, 'repeat', repeats, axis=axis)
    399 
    400 

/opt/local/lib/python3.6/site-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     55 def _wrapfunc(obj, method, *args, **kwds):
     56     try:
---> 57         return getattr(obj, method)(*args, **kwds)
     58 
     59     # An AttributeError occurs if the object does not have

ValueError: operands could not be broadcast together with shape (1663,) (447,)
```
but

```python
df.resample('H')['val'].value_counts()
```
works as expected.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-693.5.2.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.21.0
pytest: 3.2.5
pip: 9.0.1
setuptools: 36.7.2
Cython: 0.27.3
numpy: 1.13.3
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.6.2
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: None
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.8
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: None
lxml: 3.7.3
bs4: 4.6.0
html5lib: 1.0b10
sqlalchemy: 1.1.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by gfyoung** [comment]
@rmalouf : How strange!  An investigation + PR to patch would be most welcome!

**Comment by jmunar** [comment]
@rmalouf, @gfyoung I don't think this is a bug. Any operation applied after resample should must return at least 1 row per date, otherwise the index can no longer be a DatetimeIndex with a frequency. The error means that 1663-447 dates are empty.
A more precise error message would help, though.

**Comment by rmalouf** [comment]
@jmunar Yeah, I'd just come to that conclusion myself.  A note in the documentation might save someone else some time, though.

Also, here's an alternative that gives me that I want:
```python
df.to_period('T').groupby('time')['val'].value_counts()
```
