### ISSUE TITLE
BUG: Index constructor doesn't coerce int-like floats to UInt64Index

### ISSUE THREAD

**Issue by jschendel** [pandas-dev/pandas#18400]
#### Code Sample, a copy-pastable example if possible
```python
In [2]: pd.Index([0., 1., 2.], dtype='uint64')
Out[2]: Int64Index([0, 1, 2], dtype='int64')
```

Note that this also impacts ancillary functions that rely on this behavior, like `UInt64Index.where`:
```python
In [3]: idx = pd.UInt64Index(range(5))
   ...: idx
   ...:
Out[3]: UInt64Index([0, 1, 2, 3, 4], dtype='uint64')

In [4]: idx.where(idx < 100, -1)
Out[4]: Int64Index([0, 1, 2, 3, 4], dtype='int64')
```
#### Problem description
The `Index` constructor does not coerce int-like floats to `UInt64Index` when `uint64` is passed as the dtype, and instead returns a `Int64Index`.

Required for #18398 but not directly caused by it; existing bug that was brought to light during implementation.

#### Expected Output
I'd expect a `UInt64Index` instead of `Int64Index`.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.21.0
pytest: 3.1.2
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.26
numpy: 1.13.3
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: 6.1.0
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.2.2
numexpr: 2.6.4
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.7
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.3
bs4: 4.6.0
html5lib: 0.999
sqlalchemy: 1.1.9
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by jreback** [comment]
can u search existing issues as well
almost certain we already have an issue (similar maybe) to this

**Comment by jschendel** [comment]
#15832 seems similar, though not this exact issue

**Comment by jreback** [comment]
right that’s the one
yeah a little different
