### ISSUE TITLE
Cannot build pandas on AS400

### ISSUE THREAD

**Issue by BlueDragon23** [pandas-dev/pandas#18445]
Running the command

```
python3 setup.py build_ext --inplace
```

fails on an AS400. I know this isn't a supported system, but the reason for failure doesn't appear to be operating system or architecture specific.

#### Problem Description

The output from the command is here
https://pastebin.com/hMyjhKmB

The last command run is 
```
g++ gcc -pthread -bI:/QOpenSys/QIBM/ProdData/OPS/Python3.4/lib/python3.4/config/python.exp -Wl,-brtl -Wl,-blibpath:/QOpenSys/QIBM/ProdData/OPS/tools/lib/libgcc-4.8.2:/QOpenSys/QIBM/ProdData/OPS/Python3.4/lib:/QOpenSys/QIBM/ProdData/OPS/tools/lib:/QOpenSys/QIBM/ProdData/SC1/zlib/zlib-1.2.3/lib:/QOpenSys/QIBM/ProdData/SC1/zlib/lib:/QOpenSys/QIBM/ProdData/SC1/OpenSSL/openssl-0.9.8j/lib:/QOpenSys/QIBM/ProdData/SC1/OpenSSL/lib:/QOpenSys/usr/lib -L/QOpenSys/QIBM/ProdData/OPS/tools/lib/libgcc-4.8.2 -L/QOpenSys/QIBM/ProdData/OPS/Python3.4/lib -L/QOpenSys/QIBM/ProdData/OPS/tools/lib -L/QOpenSys/QIBM/ProdData/SC1/zlib/zlib-1.2.3/lib -L/QOpenSys/QIBM/ProdData/SC1/zlib/lib -L/QOpenSys/QIBM/ProdData/SC1/OpenSSL/openssl-0.9.8j/lib -L/QOpenSys/QIBM/ProdData/SC1/OpenSSL/lib build/temp.os400-powerpc-3.4/pandas/io/msgpack/_packer.o -L/QOpenSys/QIBM/ProdData/OPS/Python3.4/lib -o /home/AG2/pandas/pandas/io/msgpack/_packer.so
```

This appears to be trying to use both g++ and gcc. It is also providing a flag `-bI:[...]`, which as far as I can tell doesn't exist. 

#### Version information
I'm using Python 3.4.7. I have Cython 0.27.3, numpy 1.13.3, and python-dateutil 2.6.1. I can provide more information as needed. Any advice or suggestions will be greatly appreciated.

**Comment by jreback** [comment]
3.4 is not supported in latest. If you want to debug the setup and provide a patch would be great. But this is a non-supported platform.
