### ISSUE TITLE
Install an old version of pandas must use newest version of numpy, but I need to use an old numpy.

### ISSUE THREAD

**Issue by sunqingmeteo** [pandas-dev/pandas#18442]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

```
#### Problem description
Install an old version of pandas must use newest version of numpy, but I need to use an old numpy.
I want install numpy==1.10.4 and pandas==0.17.1 in my computer.
But when I using 
pip install numpy==1.10.4
pip install pandas==0.17.1
The installation is fine.
There is an error:
>>> import pandas
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pandas/__init__.py", line 13, in <module>
    "extensions first.".format(module))
ImportError: C extension: umpy.core.multiarray failed to import not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.

When I upgrade numpy to newest version (1.13.3), import pandas works fine. 

I already uninstall numpy using apt-get remove python-numpy
and make sure the numpy version and pandas version is correct.

Can some one help me ?

**Comment by bashtage** [comment]
You should create an empty virtualenv and install it in this.  It is likely that somehow a different copy of NumPy is being found on your system before 1.10.4. 

The following worked for me

```bash
conda create -n old-numpy python=2.7
source activate old-numpy
pip install numpy==1.10.4
pip install pandas==0.17.1
python -c "import pandas;print(pandas.__version__)"
```

`0.17.1`

You can also just use conda

```
conda create -n old-numpy python=2.7 numpy=1.10.4 pandas=0.17.1
```

**Comment by sunqingmeteo** [comment]
Thanks so much. I didn't know virtualenv before.

**Comment by chaostheory** [comment]
Must pandas use the latest version of numpy? The reason I ask is because Jupyter doesn't always support the latest version of numpy, so I can't use it with pandas.

**Comment by bashtage** [comment]
Pandas work with older Numpy. You are probably getting upgraded due to pip defaults to upgrade all deps. You can pin numpy to your desired version.
