### ISSUE TITLE
COMPAT: statsmodel 0.9.0

### ISSUE THREAD

**Issue by tdpetrou** [pandas-dev/pandas#18452]
xref #18341 

In the currently released version of statsmodels module `statsmodels/discrete/discrete_model.py` does this:

```
from pandas.core.api import get_dummies
```

@TomAugspurger [fixed this here](https://github.com/statsmodels/statsmodels/commit/45e55d0180017fffd1c57e2b92143c6be0379d4d#diff-a494553e88130577065e0b012246ca51)

In #18264 we tried to remove the `get_dummies` import from `core.api` and put it in `core.reshape.api`. This caused statsmodels to fail. We kept `get_dummies` in `core.api` [with a TODO](https://github.com/pandas-dev/pandas/blob/master/pandas/core/api.py#L27) to remove it whenever statsmodels makes their next release.

We only have to delete this line as the import was kept in `core.reshape.api`

**Comment by TomAugspurger** [comment]
0.9 is out now.
