### ISSUE TITLE
CI: test_downstream failing due to geopandas install issue

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#18456]
5th travis build on master is currenlty failing: https://travis-ci.org/pandas-dev/pandas/builds/306469506

Issue opened here: https://github.com/conda-forge/fiona-feedstock/issues/62

**Comment by jreback** [comment]
if u want to skip that test for now would be great

**Comment by jorisvandenbossche** [comment]
Done in https://github.com/pandas-dev/pandas/pull/18457
