### ISSUE TITLE
BLD: numpy-dev build started failing

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#18469]
https://travis-ci.org/pandas-dev/pandas/jobs/306851065

on ``np_datetime_strings.c``

no obvious changes, but @jbrockmendel if you'd have a look.

**Comment by jbrockmendel** [comment]
segfault in "ld", first few stackoverflow results mention possible bugs in ld.  I'm out of my depth here.

```
collect2: error: ld terminated with signal 11 [Segmentation fault], core dumped
/home/travis/miniconda3/envs/pandas/compiler_compat/ld: .eh_frame/.stab edit: File truncated
```

**Comment by jreback** [comment]
this *just* started failing on no change in numpy master. seems odd.

**Comment by jreback** [comment]
seems to be working again.
