### ISSUE TITLE
DEPR: Series.get_values()

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#18474]
this was never meant to be exposed to the user, is not-documented, and is just plain confusing

**Comment by WillAyd** [comment]
Hmm I think this has some pretty far reaching impacts as it's used internally below:

https://github.com/pandas-dev/pandas/blob/7ed1f5371601f3300c8b4592c87159fb3eaec5cd/pandas/_libs/lib.pyx#L45

I suppose we could add some type of introspection there specific to `Series` but do you see this spilling over into other classes at some point as well?

**Comment by jreback** [comment]
no, want to completely remove this in favor of using ``_ndarray_values`` and ``.values`` as appropriate. too many ways of doing things. this will be easier once Sparse is an extension array.

**Comment by jreback** [comment]
duplicate of #19617
