### ISSUE TITLE
test needed: groupby(as_index=False, sort=False).aggregate formerly (?) gave unexpected results with a list-like function

### ISSUE THREAD

**Issue by bcdarwin** [pandas-dev/pandas#18473]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame({
  'group' : [str(x) for x in range(12)],
  'file'  : [str(x) for x in range(12)]})
#Out[20]: 
#   file group
#0     0     0
#1     1     1
#2     2     2
#3     3     3
#4     4     4
#5     5     5
#6     6     6
#7     7     7
#8     8     8
#9     9     9
#10   10    10
#11   11    11
df.groupby('group', as_index=False, sort=False).aggregate({ 'file' : lambda file : list(file)})
#Out[21]: 
#   group  file
#0      0   [0]
#1      1   [1]
#2      2  [10]
#3      3  [11]
#4      4   [2]
#5      5   [3]
#6      6   [4]
#7      7   [5]
#8      8   [6]
#9      9   [7]
#10    10   [8]
#11    11   [9]
```
#### Problem description

The aggregate obviously hasn't aggregated the correct thing, but rather seems to have assumed some incorrect sorting of the rows.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-87-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_CA.UTF-8
LOCALE: en_CA.UTF-8

pandas: 0.21.0
pytest: 3.2.2
pip: 9.0.1
setuptools: 28.8.0
Cython: 0.26.1
numpy: 1.13.3
...
</details>

**Comment by jreback** [comment]
The returning of a list is problematic. as this is ok
```
In [30]: df.groupby('group',as_index=False, sort=False).aggregate({ 'file' : lambda file : file})
Out[30]: 
   group file
0      0    0
1      1    1
2      2    2
3      3    3
4      4    4
5      5    5
6      6    6
7      7    7
8      8    8
9      9    9
10    10   10
11    11   11
```

If you want to have a look and see if you can pin-point where things are going wrong would be helpful. Note that this is pretty non-idiomatic, aggregating to a list.

**Comment by TomAugspurger** [comment]
Is this py2 only, or was it fixed in the interim?

```
In [10]: df.groupby('group', as_index=False, sort=False).aggregate({ 'file' : lambda file : list(file)})
Out[10]:
   group  file
0      0   [0]
1      1   [1]
2      2   [2]
3      3   [3]
4      4   [4]
5      5   [5]
6      6   [6]
7      7   [7]
8      8   [8]
9      9   [9]
10    10  [10]
11    11  [11]
```

**Comment by bcdarwin** [comment]
This was Python 3.5/3.6.  May inadvertently be working right now but perhaps a test case should be added before closing ...

**Comment by TomAugspurger** [comment]
Indeed, we'll want to add a test.
