### ISSUE TITLE
Index.map followups

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#18482]
xref #15081, a couple of issues

- [ ] ``IntervalIndex.map`` is xfailed
- [x] parametrize [indexex/common.py/test_map](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/indexes/common.py#L1009) similar to how ``indexex/datetimelike.py/test_map`` is done (IOW on dict / Series) (#18491)
- [x] resolve datetimelike with empty map [2] should be all ``NaT`` for the datetimelikes. (#18491)

```
In [2]: pd.date_range('20130101', periods=3).map({})
Out[2]: Float64Index([nan, nan, nan], dtype='float64')

In [3]: pd.Index([1,2,3]).map({})
Out[3]: Float64Index([nan, nan, nan], dtype='float64')
```

**Comment by jreback** [comment]
cc @jorisvandenbossche (point 3)
cc @jschendel (point 1)

**Comment by jschendel** [comment]
Regarding point 1: To be clear, the underlying issue referenced here is #16410, right?  `test_map` xpasses locally for me, and that was the closest thing I could find based on the xfail message.  The problem described in #16410 is still occurring, but I haven't immediately been able to produce any errors with `map` using a similar setup.

**Comment by jschendel** [comment]
Side note:  should mapping an empty dictionary against an `IntervalIndex` return an `IntervalIndex`?  Currently returns a `Float64Index`, which seems kind of strange:
```python
In [2]: pd.interval_range(0, 4).map({})
Out[2]: Float64Index([nan, nan, nan, nan], dtype='float64')
```

**Comment by jreback** [comment]
@jschendel I just noticed that ``test_interval.py/test_map`` is xfailed. It might have been disabled during this re-factoring. if that is the case, then just need to re-eable.

#18491 fixes all of the Indexes to return correctly there own type if ``{}`` is passed. I think II should do the same (but again still xfailed).

**Comment by jorisvandenbossche** [comment]
@jreback Is there a specific reason you pinged me for point 3 ? (apart from general attention)

**Comment by jreback** [comment]
@jorisvandenbossche no, you had raised the point in the original issue (note this is all now resolved by #18491)

**Comment by jorisvandenbossche** [comment]
Ah, I forgot that one :-)

**Comment by louispotok** [comment]
(I don't know if this is the right place to put this, happy to open a new issue if that's better.)

According to my reading of [this PR](https://github.com/pandas-dev/pandas/pull/15081), the following should work as of 0.22.0:

```
s = pd.Series({0:'a',1:'b'})
s.index.map(pd.Series({0:'c',1:'d'})) 
```

But for me it throws a ValueError. Whereas this works fine:

```
s = pd.Series({0:'a',1:'b'})
pd.Series(s.index).map(pd.Series({0:'c',1:'d'}))```

**Comment by jschendel** [comment]
@louispotok : The PR you linked to has a milestone of 0.23.0, so the behavior should only work as of that release (should be relatively soon):

```python
In [2]: pd.__version__
Out[2]: '0.23.0rc2'

In [3]: s = pd.Series({0:'a',1:'b'})

In [4]: s.index.map(pd.Series({0:'c',1:'d'}))
Out[4]: Index(['c', 'd'], dtype='object')
```

**Comment by louispotok** [comment]
Oh thanks @jschendel , my mistake: I saw [this event](https://github.com/pandas-dev/pandas/pull/15081#event-1348962084) putting it in the 0.22.0, and didn't see that the milestone was later moved.

**Comment by jschendel** [comment]
Ah, I was basing the 0.23.0 milestone off the right hand side summary at the top of the PR.  Probably moved to 0.23.0 after the fact; the 0.22.0 release happened pretty shortly after 0.21.x and only contained one major change.  Many things originally slated for 0.22.0 got moved to 0.23.0 after the being merged to accommodate the new plan for the 0.22.0 release.

**Comment by mroeschke** [comment]
@jschendel is this closable? I don't see an `xfail` on any `test_map` methods.

**Comment by jschendel** [comment]
Yes, I think this can be closed.
