### ISSUE TITLE
Initialization of Series from dict disregards np.nan key

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#18480]
#### Code Sample, a copy-pastable example if possible

```python
In [2]: pd.Series({1: 1, np.nan: 2, 2: 3})
Out[2]: 
NaN     NaN
 1.0    1.0
 2.0    3.0
dtype: float64
```

#### Problem description

While users could maybe live with this (although #17648 is related), we pass data through dicts so often in our codebase (e.g. #18455 ) that we probably need to support this.

#### Expected Output

```python
In [2]: pd.Series({1: 1, np.nan: 2, 2: 3})
Out[2]: 
NaN     2
 1.0    1
 2.0    3
dtype: int64
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: b45325e283b16ec8869aaea407de8256fc234f33
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-3-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.22.0.dev0+201.gb45325e28
pytest: 3.2.3
pip: 9.0.1
setuptools: 36.7.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.0dev
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.0
openpyxl: None
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.6
lxml: None
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.2.1

</details>

**Comment by toobaz** [comment]
Changed title as ``Series`` and ``DataFrame`` need separate fixes.

**Comment by jreback** [comment]
I think there is already an issue about this. can you search a bit.

**Comment by toobaz** [comment]
I could only find #17648, which is certainly related but not sure has a common fix.

**Comment by jreback** [comment]
xref https://github.com/pandas-dev/pandas/issues/12948 as well
