### ISSUE TITLE
TST: split out test_pytables.py to sub-module of tests

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#18498]
```
(pandas) bash-3.2$ wc -l pandas/tests/io/test_pytables.py 
    5674 pandas/tests/io/test_pytables.py
```
should make a sub-module
pandas/tests/io/pytables

and then split out into various categories of tests, 1 file per.

**Comment by mikebarkas** [comment]
I am working on this.

**Comment by mroeschke** [comment]
Looks like we have an `io/pytables` directory now. Closing.
