### ISSUE TITLE
Week.onOffset looks fishy

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#18510]
A Week offset with weekday=None behaves very much like a Tick offset.  The main difference is how they handle `onOffset`.  Assuming `normalize` is False, the `Week` object will always return `week.onOffset(other)` --> `False` while the `Day` object will always return `day.onOffset(other)` --> `True`.

Is this intentional?

**Comment by gfyoung** [comment]
@jbrockmendel : Would you mind posting a small code sample for this just for reference?

**Comment by jbrockmendel** [comment]
```
In [2]: week = pd.offsets.Week()
In [3]: day7 = pd.offsets.Day(n=7)
In [5]: ts = pd.Timestamp.now()
In [6]: ts
Out[6]: Timestamp('2017-11-27 13:03:35.592386')
In [7]: ts + day7
Out[7]: Timestamp('2017-12-04 13:03:35.592386')
In [8]: ts + week
Out[8]: Timestamp('2017-12-04 13:03:35.592386')
In [9]: week.onOffset(ts)
Out[9]: False
In [10]: day7.onOffset(ts)
Out[10]: True
In [12]: day7.rollforward(ts)
Out[12]: Timestamp('2017-11-27 13:03:35.592386')
In [13]: week.rollforward(ts)
Out[13]: Timestamp('2017-12-04 13:03:35.592386')
```

It isn't that the Week.onOffset behavior is _wrong_ per se, just that I don't see why it behaves this way.  In every other way it behaves like a Tick offset.

**Comment by gfyoung** [comment]
@jbrockmendel : Indeed, it's difficult for me to say that it's wrong when there is **ZERO** documentation on that function. :smile: (in fact, if you would like to add documentation to that method, be my guest!)

That being said, I do see what you mean re: consistency.  @jreback @jorisvandenbossche thoughts?

**Comment by jbrockmendel** [comment]
@jreback is it the case that `offset.onOffset(dt)` should always be the same as (the base class implementation) `(dt + offset) - offset == dt`?  If so, this is a bug and should be resolved before #18738.

**Comment by jbrockmendel** [comment]
@gfyoung mind changing the tag from Timedelta to Frequencies?

**Comment by gfyoung** [comment]
@jbrockmendel : done
