### ISSUE TITLE
Strange matching behaviour when using str.contains with escape characters

### ISSUE THREAD

**Issue by Khris777** [pandas-dev/pandas#18516]
Minimal example of a dataframe with a string with an escaped backslash. 

    import io
    import pandas as pd

    s1 = """X
    "\\x2f"
    """

    df = pd.read_csv(io.StringIO(s1))

Printing out the dataframe shows one backslash as expected:

    Out[13]: 
          X
    0  \x2f

The Command `df.X.str.contains("\\x")` throws the exception `error: incomplete escape \x` which is clearly unexpected since I can just normally assign that sequence to a string: `s = "\\x"`, and `print(s)` returns `\x` as expected.

To get the match correctly I need to use `df.X.str.contains(r"\\x")`, this returns `True` for the dataframe.

However `r"\\x"` is `'\\\\x'` or printed as `'\\x'` while the string I created the dataframe with is `"\\x2f"` which is printed as `'\x2f'` in the dataframe (`print(df.X.iloc[0])`).

Why does `'\\\\x'` match with `"\\x2f"`?

System:
- Windows 10
- Python 3.6.3
- Pandas 0.21.0
- IPython 6.2.1
- Spyder 3.2.4

**Comment by gfyoung** [comment]
Yeah, that's indeed a little odd.  Strings are not necessarily first-class citizens compared to numeric types in the `pandas` world unfortunately.

Have a look though and see what you can find out.  A PR would be greatly appreciated!

**Comment by Khris777** [comment]
It seems like `\x` is interpreted as hexadecimal escape in sre_parse.py which is a part of Python, the code just checks if the second character is `x` and then interprets it as a hex escape.
Haven't looked further for now.

```
def _escape(source, escape, state):
    # handle escape code in expression
    code = CATEGORIES.get(escape)
    if code:
        return code
    code = ESCAPES.get(escape)
    if code:
        return code
    try:
        c = escape[1:2]
        if c == "x":
            # hexadecimal escape
            escape += source.getwhile(2, HEXDIGITS)
            if len(escape) != 4:
                raise source.error("incomplete escape %s" % escape, len(escape))
            return LITERAL, int(escape[2:], 16)
...
```

**Comment by Khris777** [comment]
Okay, this is not a pandas issue, this behaviour stems straight from Python's own `re` module:

```
import re

pat = re.compile("\\x")
```
throws the same `incomplete escape \x` error.

But doing this:
```
pat = re.compile(r"\\x")
pat.search("\\x2f")
```
succeeds: `<_sre.SRE_Match object; span=(0, 2), match='\\x'>`

Same goes for `pat = re.compile("\\\\x")´.

And enough it doesn't matter if you match with `"\\x2f"` or `r"\\x2f"`

So in conclusion:

- Matching using `"\\x"`, or `r"\x"` results in an error as Python is recognizing `"\x"` as a hex escape. (`"\x"` throws a different error).
- Matching using `r"\\x"` or `"\\\\x"` circumvents this problem with the odd effect that it matches both `"\\x2f"` and `r"\\x2f"` (`"\\\\x2f"`).

The [docs](https://docs.python.org/3/library/re.html) say this:

> If you’re not using a raw string to express the pattern, remember that Python also uses the backslash as an escape sequence in string literals; if the escape sequence isn’t recognized by Python’s parser, the backslash and subsequent character are included in the resulting string. However, if Python would recognize the resulting sequence, the backslash should be repeated twice. This is complicated and hard to understand, so it’s highly recommended that you use raw strings for all but the simplest expressions.
