### ISSUE TITLE
Test long string formatting in to_string and to_html

### ISSUE THREAD

**Issue by httassadar** [pandas-dev/pandas#1852]
Start with a data frame -- large-ish number of rows

```
df = DataFrame({'a':['a1']*100+['a2']*100, 'b':['b']*200})
dfg = df.groupby(['a'])
dfg.aggregate(len) ## this gives right answer, every entry is of length 100
dfg.aggregate(lambda x: ', '.join(x.values)) ## this is wrong, the output string is somehow truncated?
```

It works fine if the string is not very long, eg start with 
    df = DataFrame({'a':['a1']_10+['a2']_10, 'b':['b']*20)

**Comment by jorisvandenbossche** [comment]
Closing as this is working as expected (and a matter of the repr, as noted above)
