### ISSUE TITLE
Leveraging find_packages in setup.py

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#18535]
Right now when creating new folders we have to also list them as packages in the setup.py file. Is there any reason why we have not considered using find_packages as suggested by the [Python Packaging User Guide](https://packaging.python.org/tutorials/distributing-packages/#packages) to take care of that? 

Happy to submit a PR just not an expert on packaging, so wanted to discuss what if any caveats are out there first before making any changes

**Comment by jreback** [comment]
no we should switch to find_packages

it didn’t exist in older setup tools (in theory we should have a min in setup tools but it can be pretty loose)
