### ISSUE TITLE
Timestamp.replace should take freq kwarg

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#18544]
```
>>> ts.replace(freq=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pandas/_libs/tslibs/timestamps.pyx", line 840, in pandas._libs.tslibs.timestamps.Timestamp.replace
    def replace(self, year=None, month=None, day=None,
TypeError: replace() got an unexpected keyword argument 'freq'
```

**Comment by jreback** [comment]
I suppose. though this mainly for compat with ``datetime.datetime``.

**Comment by jbrockmendel** [comment]
Fair enough.  I just put it on the list along with handling DST transition gracefully.  Closing (though leaving the DST one open since it would be nice to lock down.

BTW: I haven't seen much pandas2 discussion recently.  Has that migrated to somewhere (public) where I can follow it?

**Comment by jreback** [comment]
just did a talk yesterday: https://www.slideshare.net/JeffReback/future-of-pandas-82901487
