### ISSUE TITLE
array_to_datetime set seen_datetime consistently

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#18554]
From tslib.array_to_datetime

```
                try:
                    check_dts_bounds(&dts)
                    seen_datetime = 1
                except ValueError:
                    if is_coerce:
                        iresult[i] = NPY_NAT
                        continue
                    raise
```

If this raises, it gets caught and tries a different strategy, that strategy depending on `seen_datetime`.  This pattern shows up twice, and in each case, a date/datetime _has_ been seen regardless of whether `check_dts_bound`s raises.

Is there a reason why we're not setting `seen_datetime=1` unconditionally before the bounds check?

**Comment by jreback** [comment]
you would have to show an example. seen_datetime is only set if the bounds check doesn't raise

**Comment by jreback** [comment]
@jbrockmendel example?

**Comment by jbrockmendel** [comment]
I don't have one off the top, feel free to close.  I'll put this on a low rung of the todo list.
