### ISSUE TITLE
Minor documentation issue on pd.DataFrame.last_valid_index()

### ISSUE THREAD

**Issue by gabrielclow** [pandas-dev/pandas#18564]
Documentation says "first" on both first and last methods

![image](https://user-images.githubusercontent.com/9113853/33384362-f526c1b6-d50c-11e7-97b1-61b8c310301f.png)

![image](https://user-images.githubusercontent.com/9113853/33384382-04d2738a-d50d-11e7-93ac-5c76d3ff1d23.png)

Pandas version = 0.21.0

**Comment by jreback** [comment]
first -> last here: https://github.com/pandas-dev/pandas/blob/master/pandas/core/frame.py#L4317


can you do a PR?

**Comment by gabrielclow** [comment]
I've never done one but I will happily learn how to tonight

**Comment by gabrielclow** [comment]
Sorry I took too long. Pull request was sent. 😄
