### ISSUE TITLE
datetime comparison from pandas.core.seroes.Series to numpy.datetime64 fail for pandas 0.21

### ISSUE THREAD

**Issue by zippeurfou** [pandas-dev/pandas#18569]
#### Code Sample, a copy-pastable example if possible

pandas 0.20.3
![image](https://user-images.githubusercontent.com/4520383/33405027-a5151e48-d534-11e7-8052-d64a2948c9f5.png)

```python
import pandas as pd
rng = pd.DataFrame({ "A" : pd.date_range('1/1/2011', periods=720, freq='H')})
myvar = rng["A"] < rng["A"].values[3]
```
Works.
![image](https://user-images.githubusercontent.com/4520383/33404978-76cbb9ca-d534-11e7-8310-ca0248de483c.png)

pandas 0.21
![image](https://user-images.githubusercontent.com/4520383/33404865-e69641f4-d533-11e7-900e-c0974934f845.png)
exact same code:
![image](https://user-images.githubusercontent.com/4520383/33404901-04733434-d534-11e7-937e-287d33d2e248.png)

I am not sure why this would fail now?
Note: it might be fixed in #18188

**Comment by zippeurfou** [comment]
Closing as it works with the dev version
![image](https://user-images.githubusercontent.com/4520383/33406011-da4e8802-d538-11e7-8990-5a38c7d63a6c.png)
![image](https://user-images.githubusercontent.com/4520383/33406020-e54c31be-d538-11e7-9570-1a645e312b7c.png)

**Comment by jorisvandenbossche** [comment]
We should still make sure this works with 0.21.1

**Comment by jreback** [comment]
this is all well tested in #18188 with almost exactly this example. I see no reason to have this issue open.

**Comment by jorisvandenbossche** [comment]
Of course not, I was just reopening to ensure this was the case :-) (I didn't search yet where it could have been fixed)
