### ISSUE TITLE
Segmentation Fault on MacOS when running test_pickle.py

### ISSUE THREAD

**Issue by Themanwithoutaplan** [pandas-dev/pandas#18563]
#### Code Sample, a copy-pastable example if possible

```python
pytest -xrf pandas/tests/io/test_pickle.py -v

```
#### Problem description

Python crashes when running the Python 3.5.3 tests

#### Actual Ouput

`pandas/tests/io/test_pickle.py::test_pickles[0.17.0-0.17.0_x86_64_darwin_3.5.3.pickle] Segmentation fault: 11`

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: 2a0e54bc841f27164b116135ebda4b74bae2fc4a
python: 3.6.3.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8
LOCALE: de_DE.UTF-8

pandas: 0.22.0.dev0+251.g2a0e54bc8
pytest: 3.3.0
pip: 9.0.1
setuptools: 38.2.3
Cython: 0.27.3
numpy: 1.13.3
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: 1.6.5
patsy: None
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by jreback** [comment]
did you build the extensions?  works on an identical machine.

**Comment by Themanwithoutaplan** [comment]
I'm pretty sure I have. I suspect there is something I've overlooked somewhere.

```
python setup.py build_ext --inplace
running build_ext
skipping 'pandas/_libs/algos.c' Cython extension (up-to-date)
skipping 'pandas/_libs/groupby.c' Cython extension (up-to-date)
skipping 'pandas/_libs/hashing.c' Cython extension (up-to-date)
skipping 'pandas/_libs/hashtable.c' Cython extension (up-to-date)
skipping 'pandas/_libs/index.c' Cython extension (up-to-date)
skipping 'pandas/_libs/indexing.c' Cython extension (up-to-date)
skipping 'pandas/_libs/interval.c' Cython extension (up-to-date)
skipping 'pandas/_libs/join.c' Cython extension (up-to-date)
skipping 'pandas/_libs/lib.c' Cython extension (up-to-date)
skipping 'pandas/_libs/missing.c' Cython extension (up-to-date)
skipping 'pandas/_libs/parsers.c' Cython extension (up-to-date)
skipping 'pandas/_libs/period.c' Cython extension (up-to-date)
skipping 'pandas/_libs/properties.c' Cython extension (up-to-date)
skipping 'pandas/_libs/reshape.c' Cython extension (up-to-date)
skipping 'pandas/_libs/skiplist.c' Cython extension (up-to-date)
skipping 'pandas/_libs/sparse.c' Cython extension (up-to-date)
skipping 'pandas/_libs/tslib.c' Cython extension (up-to-date)
skipping 'pandas/_libs/tslibs/conversion.c' Cython extension (up-to-date)
skipping 'pandas/_libs/tslibs/fields.c' Cython extension (up-to-date)
skipping 'pandas/_libs/tslibs/frequencies.c' Cython extension (up-to-date)
skipping 'pandas/_libs/tslibs/nattype.c' Cython extension (up-to-date)
skipping 'pandas/_libs/tslibs/np_datetime.c' Cython extension (up-to-date)
skipping 'pandas/_libs/tslibs/offsets.c' Cython extension (up-to-date)
skipping 'pandas/_libs/tslibs/parsing.c' Cython extension (up-to-date)
skipping 'pandas/_libs/tslibs/resolution.c' Cython extension (up-to-date)
skipping 'pandas/_libs/tslibs/strptime.c' Cython extension (up-to-date)
skipping 'pandas/_libs/tslibs/timedeltas.c' Cython extension (up-to-date)
skipping 'pandas/_libs/tslibs/timestamps.c' Cython extension (up-to-date)
skipping 'pandas/_libs/tslibs/timezones.c' Cython extension (up-to-date)
skipping 'pandas/_libs/testing.c' Cython extension (up-to-date)
skipping 'pandas/_libs/window.c' Cython extension (up-to-date)
skipping 'pandas/io/sas/sas.c' Cython extension (up-to-date)
skipping 'pandas/io/msgpack/_packer.cpp' Cython extension (up-to-date)
skipping 'pandas/io/msgpack/_unpacker.cpp' Cython extension (up-to-date)
```

**Comment by jreback** [comment]
try ``make clean; make``

**Comment by Themanwithoutaplan** [comment]
That seems to have fixed it. Was I doing something wrong?

**Comment by jreback** [comment]
guessing you had a really old installation before. we fixed the dependency tree recently (IOW cython should recompile if a dep has changed its public ABI, not just a time-based dep). it may not be 100%. once we switch to cythonize this should be completely fixed.

**Comment by Themanwithoutaplan** [comment]
Possibly. The last time I worked on Pandas was in 2015… Thanks for the help!
