### ISSUE TITLE
ENH: Make corrwith ignore string columns when finding correlation with a Series

### ISSUE THREAD

**Issue by tdpetrou** [pandas-dev/pandas#18570]
#### Code Sample, a copy-pastable example if possible

```python
>>> df = pd.DataFrame({'a':np.random.rand(5), 
                   'b':np.random.rand(5),
                  'string_col':'some string'})
>>> df

          a         b   string_col
0  0.376004  0.761471  some string
1  0.402352  0.865937  some string
2  0.450365  0.715527  some string
3  0.445317  0.017645  some string
4  0.687363  0.903298  some string

>>> s = pd.Series(np.random.rand(100))

>>> df.corrwith(s)
TypeError: ("unsupported operand type(s) for /: 'str' and 'int'", 'occurred at index string_col')

```
#### Problem description

Pandas should silently drop the string columns. For now, you must do this:

#### Expected Output
```
>>> df.select_dtypes('number').corrwith(s)
a    0.161006
b   -0.000233
dtype: float64
```

**Comment by gfyoung** [comment]
@tdpetrou : Thanks for reporting this!  While your workaround isn't that hard to do, I don't see why we shouldn't just drop columns that have non-numeric `dtypes`.  We do that for `DataFrame.describe`.

@jreback @jorisvandenbossche : Thoughts?

**Comment by jreback** [comment]
sure this could be done, ``.corrwith`` is a numeric only operation. Would take a community pull request.
