### ISSUE TITLE
Overflow Error writing pandas 0.21.0 to_json in windows 7

### ISSUE THREAD

**Issue by gryBox** [pandas-dev/pandas#18606]
Hi - I recently upgraded to pandas version 0.21.0 from version 0.20.3 and got the following error writing a dataframe `to_json`:
`OverflowError: Unsupported UTF-8 sequence length when encoding string`.

The traceback looks like this:
![image](https://user-images.githubusercontent.com/16763201/33522468-2cad7276-d7b3-11e7-9e50-5b2778ab1892.png)

As you can see it fails on converting dates(?).  My dataframe has no dates.
Here is how my df looks:
![image](https://user-images.githubusercontent.com/16763201/33522655-3d33c70e-d7b7-11e7-8e50-d0cd10463187.png)

However `to_json` does work for these cases:
`df = pd.DataFrame(np.random.randint(0,100,size=(5, 4)), columns=list('ABCD'))` 
and also for a standard `string`
`df['some_string'] = 'blah'`

- The same exact dataframe **does not** throw an error in 0.20.3.

**Comment by gfyoung** [comment]
@gryBox : Thanks for reporting this!  Could you provide the exact `DataFrame` that you were using OR provide a smaller one that we can use to confirm this?

**Comment by gryBox** [comment]
@gfyoung Yes.  Would putting a link to a tiny ` .csv` work?

**Comment by gfyoung** [comment]
@gryBox : Yes, that would.

**Comment by gryBox** [comment]
@gfyoung Here you go (data)[https://github.com/gryBox/learning_map/blob/master/pd_jsn_tst.csv]

**Comment by gfyoung** [comment]
@gryBox : I can't replicate the error using this dataset:

~~~
df = read_csv("<your-data-file>")
df.to_json()   # No error
~~~

**Comment by gryBox** [comment]
@gfyoung I was afraid of that.  Can you try it via Jupyter notebook 5.2?  If not, I will do more digging.

**Comment by gfyoung** [comment]
> I was afraid of that

What do you mean?  Does this example raise for you when you try to execute?

As for Jupyter, I was unable to re-produce either.

**Comment by gryBox** [comment]
I meant that it could be my system environment.  Let me investigate some more.

**Comment by gfyoung** [comment]
Okay, sounds good.  Feel free to re-open if something turns up.
