### ISSUE TITLE
TST: split test_indexing

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#18614]
after #18497 ``pandas/tests/series/test_indexing.py`` and its frame equiv are getting large

we could consider splitting these out into a sub-dir, maybe similar to how we split ``pandas/tests/indexing``, which is parially by indexer type, e.g. ``.iloc/.loc`` with some split on dtype (datetimes/period).

**Comment by almaleksia** [comment]
Hi, has it been already taken by someone? If not I would be happy to do it.
