### ISSUE TITLE
TST: split up pandas/tests/indexes/test_multi.py

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#18644]
getting pretty long, could create a sub-dir and split out into separate files.

**Comment by sunilk747** [comment]
Hi @jreback  I would like to work on this issue. I am new to this repo, I think this would be a good issue to solve first.

**Comment by bhavitvyamalik** [comment]
@jreback I'm interested in working on this issue. Could you please elaborate what exactly has to be done? Thanks!

**Comment by jreback** [comment]
make a sub-dir
``pandas/tests/indexes/multi`` and move tests to files within that dir. we want to split this up into various files by type of tests, look at ``pandas/tests/indexes/datetimes`` for example (won't necessarily be the same names), idea is to group tests logically. you won't change any tests just move them (and get the setup/linting only as needed).

should have the same number of tests before and after.

**Comment by elmq0022** [comment]
@jreback it looks like @xchoudhury is unresponsive or unable to follow up with this item.  Is there an appropriate way to step in and help push the work to completion?  Thanks!

**Comment by xchoudhury** [comment]
@elmq0022 apologies! I got busy with the end of the school year and the start of my internship. If you want, you may completely take over for me. Thanks again!

**Comment by jreback** [comment]
sure - will close this but can take the existing commits and make a new PR

**Comment by elmq0022** [comment]
Thanks @xchoundhury.  I've cloned the work you've done so far and will work to incorporate @jreback 's comments from your previous pull request.

**Comment by elmq0022** [comment]
Hey @jreback. From the description this seems like it would be straight forward, but looking more closely at the code, the task is slightly more involved.  

Unfortunately the calls in test_multi.py inherits from the Base object in common.py which has around 60 tests of it's own.  If I was to break up multi.py and inherit from Base each time, I would create a mess where a duplicate set of the tests in Base is run for each new file created.  

Also, Base is referenced in datetimelike.py, test_base.py, test_category.py, and test_numeric.py besides test_multi.py.  So, touching anything in Base class is prohibited.  

Here's what I propose:

1.   Remove all the tests defined in test_multi.py from the TestMultiIndex class.  This leaves the inherited tests intact.   
2. Create a file of pytest fixture(s) for the MultiIndex specific tests.  
3. Logically group the tests removed in item 1 into separate files using the fixtures created in item 2 as needed.  

Please let me know if this approach works for you, or please suggestion modifications. 

Thanks!

**Comment by WillAyd** [comment]
I would suggest moving the things first that don't require the class hierarchy as it may reveal the easiest way to reveal with the remaining ones. Generally fixtures would be preferable.

**Comment by elmq0022** [comment]
Thanks @WillAyd.  That would be a very good first pass to see how things shake out.

**Comment by elmq0022** [comment]
I'm making good progress and will probably make a pull request sometime later this week.

**Comment by elmq0022** [comment]
Question:
Where does the data for indices come from in the file pandas/tests/indexes/common.py?
```python
def test_compat(self, indices):
   ...
```
There when I collect the test suite there are 13 different types of indices generated for the tests like the above.  I have been unsuccessful at finding the data or the functions that generate the data for these tests.  

My current solution is to pull all the new and overridden functions from test_multi.py and convert them to fixtures while leaving a class test suite that's a mashup of Base and TestMulti to handle the methods that are not overridden in test_multi.py which still pulls in the data.  

This way I still end up with the 377 tests in the original test suite for multi indexes and all tests continue to pass.  

I am missing something critical here and could use a little push over this speedbump.  Thanks!

**Comment by WillAyd** [comment]
That is a fixture that is defined in conftest.py within that package. Here's the location of it:

https://github.com/pandas-dev/pandas/blob/9e982e18678c47c83ce2bb5932f844e2d9ee21f3/pandas/tests/indexes/conftest.py#L25

**Comment by elmq0022** [comment]
Thanks William!  I didn't know that conftest.py was a convention in
pytest.
