### ISSUE TITLE
pandas read_csv is lower than R fread function

### ISSUE THREAD

**Issue by lw3259111** [pandas-dev/pandas#18659]
I want read 3w row and 87000 columns, use pandas read_csv cost 7h,but use R fread cost 9min. so, how can t use pandas or python quickly read my file?

**Comment by chris-b1** [comment]
For usage questions, you'll be better off asking on [StackOverflow](https://stackoverflow.com/questions/tagged/pandas) and typically will get more help with a reproducible example.
