### ISSUE TITLE
Feature Request/Idea Treat a DataFrame full of Series as a Multindex Dataframe

### ISSUE THREAD

**Issue by AKuederle** [pandas-dev/pandas#18658]
When using apply on a Series and having the apply return a Series itself, Pandas automatically treats the result as a DataFrame.

Example:
```
test = pd.Series(range(10))
result = test.apply(lambda x: pd.Series(range(x)))
type(result)

>>> pandas.core.frame.DataFrame
```

However, doing the same with a DataFrame does not increase the dimensionality:
```
test = pd.DataFrame([list(range(10))]*3)
result = test.applymap(lambda x: pd.Series((range(x))))
```
In this case the result is still a 2D DataFrame, but each element is now a Series.

It would be awesome, if a DataFrame, where each element is a Series, would be automatically "casted" to a DataFrame with a MultiIndex.

I don't know, if that would be easily implemented or if it has some obvious drawbacks, I am not thinking about, but for now this behavior seems like expected result.

If someone points me in the right direction, I would also be willing to make the changes myself.

**EDIT:** Fixed the first example

**Comment by jorisvandenbossche** [comment]
A bit beside your point, but what version of pandas are you using? Because I do not get a dataframe for the first example:

```
In [13]: test = pd.Series(range(10))

In [14]: result = test.apply(lambda x: (range(x)))

In [15]: result
Out[15]: 
0                             ()
1                            (0)
2                         (0, 1)
3                      (0, 1, 2)
4                   (0, 1, 2, 3)
5                (0, 1, 2, 3, 4)
6             (0, 1, 2, 3, 4, 5)
7          (0, 1, 2, 3, 4, 5, 6)
8       (0, 1, 2, 3, 4, 5, 6, 7)
9    (0, 1, 2, 3, 4, 5, 6, 7, 8)
dtype: object

In [16]: type(result)
Out[16]: pandas.core.series.Series
```

**Comment by AKuederle** [comment]
My bad.. I messed up the first example. Should work now as described

**Comment by TomAugspurger** [comment]
Can you say a bit more about why you want / would expect this? I'd think that for something like

```python
In [19]: df = pd.DataFrame({"A": [pd.Series([0, 1])], 'B': [pd.Series([1, 1])]})
```

pandas is currently doing the correct thing. Perhaps I misunderstand.

**Comment by AKuederle** [comment]
I guess the main reason is that the behavior felt inconsistent to the behavior of Series. I found it quite useful that returning a Series from an apply on Series automatically returns a DataFrame. This felt very natural. Applying the same concept to a DataFrame I kind of expected it to also "increase" its dimension. So basically from a 2D object to a 3D object.

Given your example, I can see that a default behavior of just creating a MultiIndex object might not always be obvious. So maybe a better solution for the idea I have would be on the side of the apply functionalatiy. If e.g. the applymap method had an "upcast" parameter that would try to create a MultiIndex object based on the return value. Or a method on the DataFrame itself, that tries to convert it into a MultiIndex object by checking if its individual value could be converted in a Series.

You can currently do the same by converting the DataFrame to a Series with an Multiindex:
```
test = pd.DataFrame([list(range(10))]*3)
result = test.unstack().apply(lambda x: pd.Series((range(x)))).unstack()
result
```

But that is not really straight forward

**Comment by mroeschke** [comment]
Thanks for the suggestion but it appears this features hasn't had much interest from the core devs and community over the years so closing. Can reopen if there's renewed interest
