### ISSUE TITLE
Add pivot (reshape) option to handle duplicate keys (e.g. take first or last obs)

### ISSUE THREAD

**Issue by wesm** [pandas-dev/pandas#1865]
http://stackoverflow.com/questions/11232275/pandas-pivot-warning-about-repeated-entries-on-index

**Comment by femtotrader** [comment]
+1

**Comment by codeisnotcode** [comment]
+1

**Comment by jorisvandenbossche** [comment]
This is `pivot_table`: http://pandas.pydata.org/pandas-docs/stable/generated/pandas.pivot_table.html
