### ISSUE TITLE
DataFrame.to_latex() outputs empty cells if MultiIndex names are empty strings

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#18669]
#### Code Sample, a copy-pastable example if possible

```python
In [2]: mi = pd.MultiIndex.from_product([[1, 2], [3,4]])

In [3]: df = pd.DataFrame(-1, index=mi, columns=range(4))

In [4]: df.index.names = ['', '']

In [5]: print(df.to_latex())
\begin{tabular}{llrrrr}
\toprule
  &   &  0 &  1 &  2 &  3 \\
\midrule
1 & 3 &    &    &    &    \\
  & 4 & -1 & -1 & -1 & -1 \\
2 & 3 & -1 & -1 & -1 & -1 \\
  & 4 & -1 & -1 & -1 & -1 \\
\bottomrule
\end{tabular}
```

#### Problem description

``df`` contains 4 rows; however the output of ``df.to_latex()`` only contains 3 rows of -1.

#### Expected Output

```python
\begin{tabular}{llrrrr}
\toprule
  &   &  0 &  1 &  2 &  3 \\
\midrule
1 & 3 & -1 & -1 & -1 & -1 \\
  & 4 & -1 & -1 & -1 & -1 \\
2 & 3 & -1 & -1 & -1 & -1 \\
  & 4 & -1 & -1 & -1 & -1 \\
\bottomrule
\end{tabular}
```

#### Output of ``pd.show_versions()``

<details>

In [7]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit: fdba133336c2ec8f1269eb15e73d48797840c48b
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-4-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.22.0.dev0+301.gfdba13333
pytest: 3.2.3
pip: 9.0.1
setuptools: 36.7.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.0dev
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.0
openpyxl: 2.3.0
xlrd: 1.0.0
xlwt: 1.3.0
xlsxwriter: 0.9.6
lxml: 4.1.1
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.2.1

</details>

**Comment by jreback** [comment]
does this dupe anything in: https://github.com/pandas-dev/pandas/issues?q=is%3Aopen+is%3Aissue+label%3A%22IO+LaTeX%22

**Comment by toobaz** [comment]
I couldn't find any previous bug in which ``to_latex()`` actually suppresses data.
