### ISSUE TITLE
read_csv() usecols behavior unclear

### ISSUE THREAD

**Issue by jeffrechten** [pandas-dev/pandas#18673]
#### Code Sample, a copy-pastable example if possible

```python
                     names= ['Date', 'CreamSupply', 'RawMilk', 'Protein', 'FatProtein', 'MilkFilterInlet' #...... 
],
usecols=
 [0,132,52,19,18,133,71,70,158,92,93,94,156,157,134,135,89,73,72,27,25,24,54,53,75,74,136]

```
#### Problem description

One would think that usecols would allow a user to select the columns (and due to the fact that it's a list), the order of the columns. Either this feature disrespects the order (bug) or it is intended and the documentation should reflect that.

Latest version.

**Comment by evanmiller29** [comment]
Hey, I'd be happy to update the docs and make this clearer?

**Comment by jeffrechten** [comment]
I would be happy to do it as well if I knew how. I haven't committed yet.
