### ISSUE TITLE
asv `goal_time` wrong attribute?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#18683]
The pandas benchmarks use a parameter `goal_time = 0.2`, but looking at the asv [docs](https://asv.readthedocs.io/en/latest/writing_benchmarks.html) and at the asv code itself, I don't see "goal_time" anywhere.  Should this be `sample_time` instead?  From the docs:

    sample_time: asv will automatically select number so that each sample takes
    approximatively sample_time seconds. If not specified, sample_time defaults to 0.1 seconds.

**Comment by TomAugspurger** [comment]
Apparently is was changed: https://github.com/airspeed-velocity/asv/pull/575

**Comment by gfyoung** [comment]
Didn't seen any deprecation cycle for that.  Good catch @jbrockmendel !

**Comment by jorisvandenbossche** [comment]
It only recently changed on master. Do we assume that we all use their master, or the released version?
Eg @TomAugspurger what do you use on the benchmark machine?

**Comment by TomAugspurger** [comment]
ASV master from when I set it up a while back:

(asv) pandas@pandabox:~$ asv --version
asv 0.3.dev1126+2320b0f8

**Comment by jbrockmendel** [comment]
Easy solution is just to specify both attributes.  asv doesn't do any checking.

**Comment by jorisvandenbossche** [comment]
Or to not specify it, the default is 0.1s, which I think is quite sensible.

**Comment by jreback** [comment]
yeah let's remove this, unless we really need it
