### ISSUE TITLE
pd.read_csv warn_bad_lines skipped too many lines.

### ISSUE THREAD

**Issue by libgy24** [pandas-dev/pandas#18694]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
temp = pd.read_csv(filepath, sep = '|', 
                     encoding = 'latin1', error_bad_lines = False, warn_bad_lines = True)
```
#### Problem description

When I tried to import a file with 2.7 million records with error_bad_liens = False, I only have 2.6 million records successfully read, and the warn_bad_lines only give 5 records warnings instead of 100, 000 warnings. 

The delimiter in the file is pipe, there are records with pipe in the data value, I am trying to use warn_bad_lines' warnings to locate the bad lines in the raw files and fix them.  I do not quite understand why i have 100k records missing from raw file. 

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 62 Stepping 4, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.20.1
pytest: 3.0.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 5.3.0
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.2.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.7
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.3
bs4: 4.6.0
html5lib: 0.999
sqlalchemy: 1.1.9
pymysql: None
psycopg2: 2.7.3.1 (dt dec pq3 ext lo64)
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
need a reproducible example

**Comment by TomAugspurger** [comment]
Let us know if you can make a reproducible example. http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports
