### ISSUE TITLE
Unable to run Sample Data

### ISSUE THREAD

**Issue by WinnieT2003** [pandas-dev/pandas#18701]
#### Code Sample, a copy-pastable example if possible
eemeter sample

```python
# Your code here
Going to analyze the sample data set

Running a meter for ABC NATURAL_GAS_CONSUMPTION_SUPPLIED
c:\users\wtran\appdata\local\continuum\anaconda3\lib\site-packages\eemeter\modeling\models\caltrack_daily.py:80: RuntimeWarning: invalid value encountered in maximum
  np.maximum(df.tempF - bp, 0),
c:\users\wtran\appdata\local\continuum\anaconda3\lib\site-packages\eemeter\modeling\models\caltrack_daily.py:84: RuntimeWarning: invalid value encountered in maximum
  np.maximum(bp - df.tempF, 0),
Failed computing derivative (series=Best-fit cooling coefficient, baseline period)
Failed computing derivative (series=Best-fit cooling coefficient, reporting period)
Normal year savings estimate:
  1217.526961
  68% confidence interval: (1164.475562, 1270.578359)
Reporting period savings estimate:
  1169.700996
  68% confidence interval: (1116.730092, 1222.671900)

Running a meter for ABC ELECTRICITY_CONSUMPTION_SUPPLIED
Normal year savings estimate:
  10465.511272
  68% confidence interval: (10297.508645, 10633.513899)
Reporting period savings estimate:
  10393.837948
  68% confidence interval: (10226.081027, 10561.594870)

```
#### Problem description
I installed Anaconda and am using the Anaconda Prompt to try to run the sample data.
There are error messages appeared below before the see the Normal year savings estimate for GAS Consumption. Is this normal or is there anything that I should be typed in the code before typing the eemeter sample code in the command line?

c:\users\wtran\appdata\local\continuum\anaconda3\lib\site-packages\eemeter\modeling\models\caltrack_daily.py:80: RuntimeWarning: invalid value encountered in maximum
  np.maximum(df.tempF - bp, 0),
c:\users\wtran\appdata\local\continuum\anaconda3\lib\site-packages\eemeter\modeling\models\caltrack_daily.py:84: RuntimeWarning: invalid value encountered in maximum
  np.maximum(bp - df.tempF, 0),
Failed computing derivative (series=Best-fit cooling coefficient, baseline period)
Failed computing derivative (series=Best-fit cooling coefficient, reporting period) 

Normal year savings estimate:
  1217.526961
  68% confidence interval: (1164.475562, 1270.578359)
Reporting period savings estimate:
  1169.700996
  68% confidence interval: (1116.730092, 1222.671900)

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by jreback** [comment]
need a reproducible example

**Comment by jreback** [comment]
actually doesn't even seem related to pandas

**Comment by WinnieT2003** [comment]
I did not know what is pandas; I am reporting this issue because I received an error in anaconda while running the eemeter sample! Please look into the detailed report.
