### ISSUE TITLE
VIS: don't modify matplotlib units registry globally

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#18720]
Possible follow-up for https://github.com/pandas-dev/pandas/pull/18307, see comment there: https://github.com/pandas-dev/pandas/pull/18307#issuecomment-347911487 and https://github.com/pandas-dev/pandas/pull/18307#issuecomment-345637950 for the details.

Idea would be to only register our converters when we are plotting ourselves, so people plotting directly with matplotlib (`plt.plot(..)` or `ax.plot(..)` don't use our converters by default (they can still register them manually with the option).

**Comment by jreback** [comment]
@TomAugspurger is this doable with the latest mpl release?

**Comment by TomAugspurger** [comment]
I'm not sure. I don't think it's a blocker for 0.24.0 though.

**Comment by TomAugspurger** [comment]
Pushing to 0.25

**Comment by jorisvandenbossche** [comment]
Leaving for after 0.25? (1.0)

**Comment by TomAugspurger** [comment]
Perhaps. We had at least one release where the warning was broken.

**Comment by jorisvandenbossche** [comment]
Anyway, given that is a quite annoying change (if you are relying on it), I don't think it hurts to wait a bit longer.

**Comment by TomAugspurger** [comment]
Can we do this for 1.0? Right now matplotlib is ~25% of our import time(?), and this is the only thing requiring a non-lazy import.

**Comment by jorisvandenbossche** [comment]
Yes, I think we should try do it for 1.0. We have been raising the deprecation warning for some time now.

**Comment by TomAugspurger** [comment]
OK. I'll try to get to it today.
