### ISSUE TITLE
read_excel kwarg for `comment`?

### ISSUE THREAD

**Issue by smsaladi** [pandas-dev/pandas#18735]
This is a feature request to add a `comment` kwarg to `pandas.read_excel` just like `pandas.read_csv` can accept a `comment` kwarg.

Sorry if this request should be placed somewhere else.

**Comment by chris-b1** [comment]
It turns out this works already, the `comment` kwarg gets passed down the generic parsing code, but isn't documented (or likely tested).  A PR to flesh this out would be welcome

```python
In [31]: df = pd.DataFrame({'a': ['1', '#2'], 'b': ['2', '3']})

In [32]: df.to_excel('tmp.xlsx', index=False)

In [33]: pd.read_excel('tmp.xlsx')
Out[33]: 
    a  b
0   1  2
1  #2  3

In [34]: pd.read_excel('tmp.xlsx', comment='#')
Out[34]: 
   a  b
0  1  2
```

**Comment by vertan** [comment]
I'd like to work on this!

**Comment by JanLauGe** [comment]
Hi @vertan, @chris-b1, I just submitted a PR referencing this, but I've only done the example for the docs. Perhaps there is more work to do here in terms of tests?
