### ISSUE TITLE
pytest.skip not working inside context manager?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#18733]
#18709 implements tests that uses `tm.set_timezone` context manager.  `set_timezone` begins with:

```
    if is_platform_windows():
        import pytest
        pytest.skip("timezone setting not supported on windows")
``` 

But that apparently isn't raising as expected: https://ci.appveyor.com/project/pandas-dev/pandas/build/1.0.7947/job/2fadgp6te7e95ysc

**Comment by WillAyd** [comment]
We may have conflicting development. I removed this from the context manager in #18693 and replaced it with a decorator in the functions where it was being used. 

I didn't your branch of ``revert_today`` having merged in my changes so I'm a little surprised to see the failure there but wanted to call that out nonetheless

**Comment by jbrockmendel** [comment]
That would explain it, thanks.  Closing.
