### ISSUE TITLE
new line char not showing up correctly in docs

### ISSUE THREAD

**Issue by smsaladi** [pandas-dev/pandas#18736]
Seems to be written "correctly" in the source:

https://github.com/pandas-dev/pandas/blob/4091f64d6e0dca3177f905b71f4d067bef8acd91/pandas/io/parsers.py#L251

and parsed correctly in the .rst file:

https://github.com/pandas-dev/pandas/blob/4091f64d6e0dca3177f905b71f4d067bef8acd91/doc/source/io.rst#L335

But doesn't show up correctly in the online docs:
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_excel.html

<img width="596" alt="screen shot 2017-12-11 at 2 58 56 pm" src="https://user-images.githubusercontent.com/2942215/33858363-21524abe-de84-11e7-9ea8-1926ab013c86.png">

**Comment by vertan** [comment]
The new line problem was fixed in #18412, and the missing named argument `comment` is added to the `read_excel` documentation in the proposed PR #18753.
