### ISSUE TITLE
How to iterate row from specific cell ? or how to give specific range in row iteration?

### ISSUE THREAD

**Issue by nariyapratik** [pandas-dev/pandas#18760]
Python Code

from mtranslate import translate
import pandas
import numpy as np

df = pandas.read_excel('english.xlsx')
df['Portuguese'] = np.nan
df['In English'] = np.nan
np.head()

for row in df.head(n=20).iterrows():
    for index in range(6, 9 + 1):
        english_ori = str(row[0])
        por_temp = translate(english_ori, 'pt')  # portuguese
        df['Portuguese'].loc[index] = por_temp
        english_out = translate(por_temp.encode('utf-8'), 'en')
        df['In English'].loc[index] = english_out
df.to_excel('english.xlsx')

```
#### Problem description

I want to start row iteration from specific given number like cell = 6 and after translating i want to write back to specific column.

https://pandas-docs.github.io/pandas-docs-travis/

**Comment by TomAugspurger** [comment]
Maybe try asking on StackOverflow with the pandas tag; we use that for usage questions, and github issues for bug tracking.
