### ISSUE TITLE
ENH: manylinux/macos wheel for Python 3.4

### ISSUE THREAD

**Issue by danielhrisca** [pandas-dev/pandas#18763]
#### Problem description

There seem to be Windows wheels for Python 3.4, but no wheels for linux or macos.

Is it possible to build and upload such wheels as well?

EDIT:

I was referring to the wheel available on [PyPI pandas page](https://pypi.org/project/pandas/#files)

**Comment by jreback** [comment]
3.4 support was dropped in 0.21.0

**Comment by danielhrisca** [comment]
Ok, in this case why are there Windows wheels for Python 3.4?

**Comment by jreback** [comment]
that’s an errror

@TomAugspurger

**Comment by TomAugspurger** [comment]
Whoops, removed the 34 wheels.
