### ISSUE TITLE
OverFlowError: Python int too large to convert to C unsigned long

### ISSUE THREAD

**Issue by apiszcz** [pandas-dev/pandas#18779]
Pandas 0.21
df.groupby('x').resample('50T').count()

x is type np.uint64

I'm guessing this is my problem and I need to use another representation for 'x', however there may be a problem.

Thank you.

**Comment by jreback** [comment]
pls show a copy-pastable example

**Comment by apiszcz** [comment]
Test case works fine, if I set value ...16 i get the message, I need to review my data.

```
import pandas as pd
import numpy as np
ui64 = np.iinfo(np.uint64); print(ui64.max)
df=pd.DataFrame([18446744073709551615,18446744073709551614,18446744073709551613],columns=['x'])
df['time']=pd.to_datetime([0,1,2],unit='s')
df=df.set_index(pd.DatetimeIndex(df['time']))
df.groupby('x').resample('15T').count()
```

		x	time
x	time		
18446744073709551613	1970-01-01	1	1
18446744073709551614	1970-01-01	1	1
18446744073709551615	1970-01-01	1	1
