### ISSUE TITLE
Standardize docstrings to use pd.DataFrame/pd.Series

### ISSUE THREAD

**Issue by tdpetrou** [pandas-dev/pandas#18770]
#### Problem description

All docstrings should be consistent with DataFrame/Series creation and use `pd.` to access them as this is what most users use. I was looking through pandas/core/frame.py and there are 9 instances of a docstring having `df = DataFrame(...)` vs 30 that have `df = pd.DataFrame(...)`.

It would be nice to standardize this and possibly other similar inconsistencies - but this is the largest one that stood out.

**Comment by jorisvandenbossche** [comment]
@tdpetrou This issue is closed by the PR, but I suppose the same will occur in different files.
