### ISSUE TITLE
geopandas install issue?

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#18780]
revert #18786 

https://travis-ci.org/pandas-dev/pandas/jobs/316397406

```
./../../miniconda3/envs/pandas/lib/python3.6/site-packages/geopandas/__init__.py:4: in <module>
    from geopandas.io.file import read_file
../../../miniconda3/envs/pandas/lib/python3.6/site-packages/geopandas/io/file.py:3: in <module>
    import fiona
../../../miniconda3/envs/pandas/lib/python3.6/site-packages/fiona/__init__.py:69: in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    import logging
    import os
    import warnings
    
    from fiona import compat
>   from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
E   ImportError: libpoppler.so.71: cannot open shared object file: No such file or directory
```

cc @jorisvandenbossche

**Comment by jorisvandenbossche** [comment]
@ocefpaf are you currently updating packages? In the sense of: is it just waiting on travis to finish building, or should I report it somewhere?

**Comment by jorisvandenbossche** [comment]
@jreback it's a bit a problem for our ci, but basically every time some of the dependencies in the gdal dependency chain have to be updated, there is a short moment that one is updated and the other not, and we get such failures.

**Comment by ocefpaf** [comment]
@jreback and @jorisvandenbossche did you guys tried only the default channel lately? @msarahan and others did an amazing job of getting the latest recipes from `conda-forge` and building them in a more consistent way with `conda-build 3`. Also, b/c they are not limited by CIs, when they update a dependency all the stack is updated at once and things will be consistent quicker than in `conda-forge`.

**Comment by jorisvandenbossche** [comment]
`gdal` is in a working state lately? (but it is a long time ago that I tried and had problems with it)

**Comment by jreback** [comment]
if its only temporary no problem.

**Comment by msarahan** [comment]
If gdal is not in a working state on defaults, please let me know.

**Comment by jorisvandenbossche** [comment]
It's probably two years ago that I tried (and at that time there were problems), so I should probably first have tried before saying something like that .. :-)

But, trying, and I notice it still tries to get `rtree`, `libspatialindex` and `geopandas` from conda-forge, so I assume those are not available in defaults. At the moment this is probably not a problem, as neither of those build against gdal or geos. 
But, shortly I hope, `geopandas` will start having geos as a build dependency, and then this mixing is probably more problematic. It is also a bit annoying to do the install to get the channel priority correct (but which is probably not a problem for our CI)

Anyhow, reading a simple shapefile is working fine.

**Comment by msarahan** [comment]
I can work on building those in near term.  Thanks for trying.
