### ISSUE TITLE
Series.__sub__(NaT) vs DatetimeIndex.__sub__(NaT)

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#18808]
One treats NaT result as datetime, other treats it as timedelta.

```
>>> dti  = pd.DatetimeIndex([pd.NaT, pd.Timestamp('19900315')])
>>> ser = pd.Series(dti)

>>> dti - pd.NaT
TimedeltaIndex([NaT, NaT], dtype='timedelta64[ns]', freq=None)

>>> ser - pd.NaT
0   NaT
1   NaT
dtype: datetime64[ns]
```

**Comment by gfyoung** [comment]
Hmmm...that does seem a little inconsistent.  Have a look as to why that's happening.

**Comment by jreback** [comment]
I would argue that the series is wrong here.

**Comment by jbrockmendel** [comment]
> I would argue that the series is wrong here. a sub operation with a DTI-like should always yield a TDI-like.

So I can change that and consider it a bugfix as opposed to a Breaking Change?

**Comment by jreback** [comment]
no its a breaking change, but you can still change it

**Comment by jbrockmendel** [comment]
Got a fix for this about ready.  Two questions.

One: there are a couple of tests in series.test_operators `test_datetime64_ops_nat` that specifically check for the return type to be datetime64.  Sure the behavior isn't intentional?

Two: also in `test_datetime64_ops_nat` are tests for `-pd.NaT + Series[datetime64]`.  Should that also be changed to return `Series[timedelta64]`?
