### ISSUE TITLE
Ipykernel QXcbConnection: Could not connect to display

### ISSUE THREAD

**Issue by hardianlawi** [pandas-dev/pandas#18813]
```python
import pandas as pd
df = pd.read_csv('oils.csv')
df.QXcbConnection: Could not connect to display
Aborted (core dumped)
```
#### Problem description

I was using `ipython` to run the codes above, and when I pressed `tab` after `df.` for auto-completion, it disconnected the `ipython` and showed the `QXcbConnection: Could not connect to display` error.

I am using `Python 3.6.3 :: Anaconda, Inc.`, pandas `0.20.3`, ipykernel `4.6.1`, and ipython `6.1.0`

Any advise?

**Comment by gfyoung** [comment]
My first guess is that this is a an `ipython` issue.  Did you try auto-completion anywhere else outside of `pandas`?

**Comment by hardianlawi** [comment]
Yes, I tried it some other modules and objects, but everything else works just fine except for the dataframe.

Even the `pd.` auto-completion works fine.

**Comment by gfyoung** [comment]
I wonder if it has to deal with how many elements are in the `dir` of the object.  Using `0.21.1`, I get 179 elements in the `dir` of `pd` and 454 elements in the `dir` of `df`.

**Comment by hardianlawi** [comment]
I just updated my `pandas` and checked the `dir`.

Below are the results:
```Python
In [3]: len(df.__dir__())
Out[3]: 456
In [4]: len(pd.__dir__())
Out[4]: 179
```

**Comment by jreback** [comment]
try 0.21.1

you are experiencing an unconnected xserver which was not handled gracefully

**Comment by hardianlawi** [comment]
@jreback Yes, I have tried it. It is still not working

**Comment by drevicko** [comment]
I have the same problem with pandas Python 3.6.2, ipython 6.1.0 and pandas 0.20.3 on a headless server (ie: no xserver). It seems there's information ipython is trying to get from a DataFrame for autocomplete that prompts the df to access the xserver. I'd have thought autocomplete just uses the __dir__() list, but perhaps it's doing more?

**Comment by jorisvandenbossche** [comment]
@drevicko Yes, that would be very helpful if you could test it with a more recent version of pandas.

**Comment by mroeschke** [comment]
Feel free to reopen if you can post a reproducible example.
