### ISSUE TITLE
TST: Coding Error in test_disallowed_nodes

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#18821]
See permalink below. I believe the ``engine`` parameter should be referencing the ``_engines`` global and not ``_parsers``

https://github.com/pandas-dev/pandas/blob/7a0ee19e95e29042c3373a1d912d2db27108c828/pandas/tests/computation/test_eval.py#L1803

**Comment by gfyoung** [comment]
That would seem logical to do.
