### ISSUE TITLE
How to read a continuous file that append data each second to end of file

### ISSUE THREAD

**Issue by rspadim** [pandas-dev/pandas#18830]
Hi guys, I have a program that open a file and start to write a stream data, in other words it's always writing sensor data (temperature), for example:

2017.12.18 22:37:54;37
2017.12.18 22:37:55;37
2017.12.18 22:37:56;37
2017.12.18 22:37:57;37

the problem is:
file is changing each second, and file can have more than 200MB, i want to read only the last data (i know how many lines was read the last time, and want to skip these lines to append it to my current open dataframe)

should this be possible? an optimized way to read files that is always appending (it don't remove, just append to end of file)

thanks guys!

**Comment by jreback** [comment]
you are likely to get more response from StackOverflow
