### ISSUE TITLE
asv tests for DataFrame constructor

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#18840]
After #18769 , the asv coverage of different possibilities of initialization values for ``Series()`` should be pretty good (see ``asv_bench/benchmarks/ctors.py`` ).

The coverage for ``DataFrame`` instead (see ``asv_bench/benchmarks/frame_ctor.py``) is more limited and should be expanded.

**Comment by moisesjsanchez** [comment]
Hello, I am a first-time contributor. If this issue is still open would it be okay for me to work on this?

**Comment by WillAyd** [comment]
@moisesjsanchez sure!

**Comment by jbrockmendel** [comment]
Closing as completed (albeit ongoing).
