### ISSUE TITLE
dataframe query inplace Error

### ISSUE THREAD

**Issue by hardianlawi** [pandas-dev/pandas#18867]
```python
import pandas as pd
import numpy as np
 
data = {'name': ['Alice', 'Bob', 'Charles', 'David', 'Eric'],
        'year': [2017, 2017, 2017, 2017, 2017],
        'salary': [40000, 24000, 31000, 20000, 30000]}
 
df = pd.DataFrame(data)
 
print(df)

df.query("salary>30000", inplace=True)

print(df)
```
#### Problem description

The first and second `print(df)` result in the same output which shouldn't be the case as `inplace` is set to `True`.

#### Expected Output

```
      name  salary  year
0    Alice   40000  2017
2  Charles   31000  2017
```
#### Real Output

```
      name  salary  year
0    Alice   40000  2017
1      Bob   24000  2017
2  Charles   31000  2017
3    David   20000  2017
4     Eric   30000  2017
```

```
      name  salary  year
0    Alice   40000  2017
1      Bob   24000  2017
2  Charles   31000  2017
3    David   20000  2017
4     Eric   30000  2017
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.5.2-040502-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_SG.UTF-8
LOCALE: en_SG.UTF-8

pandas: 0.21.0
pytest: None
pip: 9.0.1
setuptools: 37.0.0
Cython: None
numpy: 1.13.3
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: None
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.1.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: 0.7.3
lxml: None
bs4: None
html5lib: 0.999999999
sqlalchemy: 1.1.15
pymysql: None
psycopg2: None
jinja2: 2.8
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
Is your expected output incorrect? I suspect you want

```python
      name  salary  year
0    Alice   40000  2017
2  Charles   31000  2017
```

for the second one? That's what I get on master, if you want to try giving that a shot.

**Comment by hardianlawi** [comment]
@TomAugspurger Yes, but after doing this `df.query("salary>30000", inplace=True)`, I still get the output from the first `print(df)`

**Comment by bobhaffner** [comment]
Hi @hardianlawi I tested this against 0.21.0 (your version) and my output matches your expected output.  ie the inplace=True is doing it's job
