### ISSUE TITLE
BUG(?): Var of Timedelta with empty / NA

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#18880]
*edit*: it seems like the bug is that var returns numeric values for the operation, instead of timedeltas like `.std` (https://github.com/pandas-dev/pandas/issues/18880#issuecomment-353164903)

---

Working on the empty / all-NA stuff. This is related, but separate.

Currently for an all-NA series of timedelta's, we return `NaT` for `.var()` on an empty series (see Out[44]). I think this should be `NaN` since the reduction is returning numeric values, not timedeltas.

```python
In [40]: s = pd.Series(pd.timedelta_range(0, periods=12, freq='S'))

In [41]: s[0] = np.nan

In [42]: s.var()
Out[42]: 1.1e+19

In [43]: s.var(skipna=False)
Out[43]: nan

In [44]: s[:0].var()
Out[44]: NaT
```

I've just noticed some other buggy behavior with aggregations on timedeltas, so maybe this can become a meta-issue about timedeltas and numeric aggregations:

```python
In [57]: s.sum(skipna=False)
Out[57]: Timedelta('-106752 days +00:13:49.145223')
```

I'm guessing we improperly add the timedelta min here.

**Comment by TomAugspurger** [comment]
Ahh interesting, `.std` returns the units in timedelta's so maybe that's the bug that `.var` isn't handling dtypes correctly:

```python
In [11]: s.std()
Out[11]: Timedelta('0 days 00:00:03.316624')

In [12]: s[:0].std()
Out[12]: NaT
```

**Comment by jreback** [comment]
what would this be numeric? any reduction should stay the same dtype (except int-> float).

**Comment by jreback** [comment]
yeah it prob doesn't does handle the ufunc propertly (sqrt), e.g.

This works, but prob not what its doing.
```
In [7]: pd.Timedelta(np.sqrt(s.std().value))
Out[7]: Timedelta('0 days 00:00:00.000057')
```

**Comment by TomAugspurger** [comment]
Yeah, I was just saying numeric because the non-NA versions were numeric, but that's the real bug. I'll edit the original bug report.

**Comment by TomAugspurger** [comment]
I don't think so, do you? `Series[timedelta].var()` is still numeric for me, rather than a Timedelta.

**Comment by jbrockmendel** [comment]
Shouldnt `Series[timedelta].var()` raise?  `std()` makes sense.

**Comment by TomAugspurger** [comment]
> Shouldnt `Series[timedelta].var()` raise? `std()` makes sense.

Can you clarify this? The mean of std & var for timedeltas is a bit hazy to me, but why would one make sense and not the other?

**Comment by jbrockmendel** [comment]
> Can you clarify this? The meaning of std & var for timedeltas is a bit hazy to me, but why would one make sense and not the other?

The issue is the units.  `Var(td64ns)` would have to have unit `ns^2`, which we don't have a way to represent.

**Comment by TomAugspurger** [comment]
One more question, why do we not say that `Var(td64ns) <=>
Timedelta(Var(td64ns.asi8))`? IOW

```python
In [14]: values = [1000, 2000, 3000]

In [15]: pd.Series(values).std()
Out[15]: 1000.0

In [16]: pd.Series(values).var()
Out[16]: 1000000.0

In [18]: pd.Series(pd.to_timedelta(values)).std()
Out[18]: Timedelta('0 days 00:00:00.000001')  # = Timedelta(values.std())

In [19]: pd.Series(pd.to_timedelta(values)).std().value
Out[19]: 1000
```

I agreed that ns^2 isn't something we can represent, but what about
Timedelta(i8^2)? Like I said, this is hazy to me, so it may be meaningless.

**Comment by jbrockmendel** [comment]
```
i8values = np.array([1e9, 2e9, 3e9], dtype='i8')
tdi = pd.to_timedelta(i8values)
ser = pd.Series(tdi)

>>> ser.std()
Timedelta('0 days 00:00:01')
```

I think we're on the same page that `ser.std()` here makes sense.  If we _could_ do `ser.var()`, it would have to obey the identity `ser.var() == (ser.std())**2`.  But the right hand side we can't do.

Does this help?  Any way you do it, you need to get a ns^2 in there.
