### ISSUE TITLE
ENH: Timestamp constructor does not accept nanosecond arg

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#18898]

**Comment by jreback** [comment]
the kwargs are to mirror ``datetime.datetime``, but we should accept it.

**Comment by theperfectscript** [comment]
Hi, 
I would like to contribute. Can you point me to what needs to be done?

All the best

**Comment by jreback** [comment]
start https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslibs/timestamps.pyx#L526

need to add to the signature

**Comment by theperfectscript** [comment]
I am a bit confused about where i should put in the tests.

[Here https://github.com/pandas-dev/pandas/blob/master/pandas/tests/internals/test_internals.py#L290](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/internals/test_internals.py#L290) ?
@jreback

**Comment by jreback** [comment]
pandas/tests/scalar/test_timestamp

**Comment by bhavybarca** [comment]
hi can i take his as my good-first-bug ?

**Comment by jorisvandenbossche** [comment]
@bhavybarca There is already an open PR that is about to be merged: #19889

**Comment by bhavybarca** [comment]
@jorisvandenbossche is there anything  a newbie like me can do, i really want to contribute but cant find any first bugs.
A little help would be appreciated, thanks

**Comment by jorisvandenbossche** [comment]
You can go through other issues that are labeled with "good first issue". If you have any question about any of them, feel free to also ask at https://gitter.im/pydata/pandas or post on the issue
