### ISSUE TITLE
How to expand the output column limit

### ISSUE THREAD

**Issue by thesby** [pandas-dev/pandas#18890]
When I have a DataFrame object which contains many columns and I want to output it to screen, I find that it just output 4 columns and continue to output below it. How to modify the limit of 4 columns? My screen is very wide.

**Comment by bobhaffner** [comment]
You can check out https://pandas.pydata.org/pandas-docs/stable/options.html#frequently-used-options   for some options

In particular, `display.expand_frame_repr`
