### ISSUE TITLE
Groupby wrong behaviour (continued)?

### ISSUE THREAD

**Issue by Nemecsek** [pandas-dev/pandas#18908]
This is the continuation of #18866. 

The above issue has been closed and I don't understand yet why this is not considered a bug of pandas.
@jreback: I don't know how to ask for reopening #18866 and it is possible I didn't explain well what I mean. Here I try to rewrite it properly.

**Code sample**
```
import pandas as pd
from datetime import datetime

def legend(text, obj):
    print "\n" + "="*50 + "\n" + text
    print obj.head(1000)

df = pd.DataFrame({'dtime': [datetime(2017,01,01,1,5), 
                             datetime(2017,01,01,1,20)],
                   'val1': [11, None], 
                   'val2': [None, 31]  # returns a MultiIndex
                         # [31, None] <=== this returns a DateTimeIndex
                  })
legend("10 Original df", df)

df = (df.melt("dtime")
        .dropna()
        .set_index("dtime"))
legend("20 After melt", df)

group = df.groupby(pd.Grouper(freq="1H"))
legend("30 Group by dtime", group)

group = group["value"].apply(lambda x: x.sort_values(ascending=False))
legend("40 Find max 3 for each hour", group)

df = pd.DataFrame(group)
print "\n\nIndex info:", df.info()
```

**Problem description**
Swapping the elements in `val2`, groupby returns a different index type:

OK if `val2=[None, 31]`:
```
dtime                dtime              
2017-01-01 01:00:00  2017-01-01 01:20:00    31.0
                     2017-01-01 01:05:00    11.0
Name: value, dtype: float64
Index info:<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2 entries, (2017-01-01 01:00:00, 2017-01-01 01:20:00) to (2017-01-01 01:00:00, 2017-01-01 01:05:00)
```

Wrong with `val2=[31, None]`:
```
dtime
2017-01-01 01:05:00    31.0
2017-01-01 01:05:00    11.0
Name: value, dtype: float64
Index info:<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2 entries, 2017-01-01 01:05:00 to 2017-01-01 01:05:00
```

**Expected output**
As both `val2` meaningful times are in the same hour, I would expect that in the second case the hour-group is also combined with `dtime` to return a MultiIndex. 

I would expect it to return
```
dtime                dtime              
2017-01-01 01:00:00  2017-01-01 01:05:00    31.0
                     2017-01-01 01:05:00    11.0
Name: value, dtype: float64
Index info:<class 'pandas.core.frame.DataFrame'>
MultiIndex: ......
```

**Comment by TomAugspurger** [comment]
@Nemecsek could you clarify your example a bit? I don't see what melt has to do with anything. If it's just for constructing a DataFrame, perhaps you can construct it directly?

Also it's easier to follow if you don't overwrite variable. I think this should be the same as what you're doing, and the output looks correct. What did I miss?

```python
In [1]: paste
import pandas as pd
from datetime import datetime

df1 = pd.DataFrame({'dtime': [datetime(2017,1,1,1,5),
                             datetime(2017,1,1,1,20)],
                   'val1': [11, None],
                   'val2': [None, 31]
                  })

df2 = pd.DataFrame({'dtime': [datetime(2017,1,1,1,5),
                             datetime(2017,1,1,1,20)],
                   'val1': [11, None],
                   'val2': [31, None]
                  })



df12 = (df1.melt("dtime")
        .dropna()
        .set_index("dtime"))

df22 = (df2.melt("dtime")
        .dropna()
        .set_index("dtime"))


r1 = df12.groupby(pd.Grouper(freq="1h")).value.apply(lambda x: x.sort_values())
r2 = df22.groupby(pd.Grouper(freq="1h")).value.apply(lambda x: x.sort_values())

## -- End pasted text --

In [2]: r1
Out[2]:
dtime
2017-01-01 01:05:00    11.0
2017-01-01 01:20:00    31.0
Name: value, dtype: float64

In [3]: r2
Out[3]:
dtime
2017-01-01 01:05:00    11.0
2017-01-01 01:05:00    31.0
Name: value, dtype: float64
```

**Comment by Nemecsek** [comment]
@TomAugspurger , thank you for answering me. I have been on holiday and had no possibility to check your answer before. Sorry for the delay.

It took some time to understand what is strange, and it looks like it is the only thing you left out in your code: in `sort_values` you didn't add the `ascending=False` parameter.

When you add `ascending=False`,  `r1` reads:
```
dtime                dtime              
2017-01-01 01:00:00  2017-01-01 01:20:00    31.0
                     2017-01-01 01:05:00    11.0
Name: value, dtype: float64
```
and `r2`:
```
dtime
2017-01-01 01:05:00    31.0
2017-01-01 01:05:00    11.0
Name: value, dtype: float64
```

Why `r1` reads also the group time (`2017-01-01 01:00:00`, based on the hour) while `r2` doesn't? 
Is this just a representation problem?

**Comment by Nemecsek** [comment]
Hi Tom. After almosta  month of silence I went on asking again on stackoverflow and they probably fixed the point. [Last comment of muskrat](https://stackoverflow.com/questions/48280456/pandas-groupby-different-indexes-returned/48282033#48282033) is interesting indeed: 

> As stated, I don't think it's a bug. That said, I agree with you that it's not necessarily the most natural design choice, as it leads to strange differences like the one you've found.
