### ISSUE TITLE
DOC: is confusing for ddof parameter of sem, var and std functions

### ISSUE THREAD

**Issue by recontemplator** [pandas-dev/pandas#18903]
https://github.com/pandas-dev/pandas/blob/7bb204a05fee20c3c825e7da39ccaf39fbeb8ca5/pandas/core/generic.py#L7160-L7161

It states that _ddof_ is for degrees of freedom with default value of 1. But actually it is for "Delta degrees-of-freedom" (even the name of the parameter is abbreviation of that definition). The meaning is:  how many degrees of freedom **to adjust** relative to the population size. Default of 1 - means we need to **adjust** by one, not use one as a value of degrees of freedom (thats makes no sense). All functions are worked as expected, but documentation on _ddof_ parameter is confusing.

**Comment by sinhrks** [comment]
Yeah it should be fixed according to the latest numpy doc. PR is welcome!

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.std.html

**Comment by jreback** [comment]
sure @recontemplator would you like to do a PR

**Comment by butterflyskip** [comment]
Hi,
Newbie here, would like to take a stab at this.

txs
