### ISSUE TITLE
BUG: reindex(columns=..) after get_dummies raises TypeError: values must be SparseArray

### ISSUE THREAD

**Issue by ShadowGiraffe** [pandas-dev/pandas#18914]
#### Code Sample

```python
df = pd.DataFrame.from_items([('GDP', [1, 2]),('Nation', ['AB', 'CD'])])
df = pd.get_dummies(df, columns=['Nation'], sparse=True)  # SparseDataFrame
df.reindex(columns=['GDP'])  # Fails :/

TypeError: values must be SparseArray
```
#### Problem description

I'm doing a pandas upgrade from 0.19.x to 0.21.x for my project. The above code works under 0.19.x, but not under 0.21.x.

**Comment by jreback** [comment]
hmm that does look buggy.

cc @Licht-T

**Comment by jreback** [comment]
@ShadowGiraffe welcome for an investigation / PR

**Comment by hexgnu** [comment]
I think I figured out the problem. Inside of get_dummies not all columns are cast as sparse but are marked as such causing some interesting issues down the line when trying to reindex.

Added a PR for that fix.

**Comment by summerela** [comment]
I just ran into this issue with the latest version of pandas. Please let me know if you would like me to post my code.
