### ISSUE TITLE
MultiIndex.is_unique is inconsistent with Index.is_unique

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#18913]
#### Code Sample, a copy-pastable example if possible

```python
In [2]: pd.Index([1, .1]).is_unique
Out[2]: True

In [3]: pd.MultiIndex.from_product([[1, 1.], range(3)]).is_unique
Out[3]: False
```

#### Problem description

Again part of the #18519 saga.

#### Expected Output

The same in the two cases

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: 316acbf065f5d1e30fdc7fcced3a53a2f4b14655
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-4-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.22.0.dev0+412.g316acbf06
pytest: 3.2.3
pip: 9.0.1
setuptools: 36.7.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.0dev
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.0
openpyxl: 2.3.0
xlrd: 1.0.0
xlwt: 1.3.0
xlsxwriter: 0.9.6
lxml: 4.1.1
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.2.1

</details>

**Comment by jreback** [comment]
```
In [13]: pd.MultiIndex.from_product([[1, 1.], range(3)]).values
Out[13]: array([(1.0, 0), (1.0, 1), (1.0, 2), (1.0, 0), (1.0, 1), (1.0, 2)], dtype=object)

In [14]: pd.MultiIndex.from_product([[1, 1.], range(3)]).duplicated()
Out[14]: array([False, False, False,  True,  True,  True], dtype=bool)

```

looks ok to me.

**Comment by jreback** [comment]
This is a manifestation of ``np.array([1, 1.0])`` I think

**Comment by jreback** [comment]
this doesn't even preserve.
```
In [16]:  pd.MultiIndex.from_product([pd.Index([1, 1.], dtype=object), range(3)]).values
Out[16]: array([(1, 0), (1, 1), (1, 2), (1, 0), (1, 1), (1, 2)], dtype=object)
```

so this looks like a construction issue, rather than a pure indexing issue.

**Comment by toobaz** [comment]
My first example is all wrong, it should have been

```python
In [2]: pd.Index([1, 1.]).is_unique
Out[2]: False
```

@jreback the example [you give](https://github.com/pandas-dev/pandas/issues/18913#issuecomment-353748642) instead is indeed buggy, but I will open a new issue for clarity.
