### ISSUE TITLE
no module named pandas

### ISSUE THREAD

**Issue by Marols99** [pandas-dev/pandas#18939]
dict = {
    "country": ["brasil", "russland", "norge", ], 
    "capital":["brasillia", "moskva", "oslo"], 
    "area": [8.516, 17.10, 3.1], 
    "pupulation": [200.4, 143.5, 5.0]}

import pandas as pd   

brics = pd.DataFrame(dict)

print(dict)

Trying to run this in VS Code i get the error "no module named pandas". Running this in IDLE or terminal works fine.

**Comment by TomAugspurger** [comment]
You probably need to configure you're environment: https://code.visualstudio.com/docs/python/environments
