### ISSUE TITLE
Some interesting behavior from .groupby().apply( .to_records() )

### ISSUE THREAD

**Issue by alexlenail** [pandas-dev/pandas#18930]
Why is it that
```
df.groupby('A')[['B','C']].apply(lambda x: x.to_records())
```
throws: `TypeError: Series.name must be a hashable type` while
```
df.groupby('A').apply(lambda x: x[['B','C']].to_records())
```
works?

**Comment by jreback** [comment]
pls show a copy pastable example

**Comment by zfrenchee** [comment]
```
df = pd.DataFrame({'A':{'a':1,'b':2},'B':{'a':1,'b':2},'C':{'a':1,'b':2}})
df.groupby('A')[['B','C']].apply(lambda x: x.to_records())  # => TypeError
df.groupby('A').apply(lambda x: x[['B','C']].to_records(index=False))  # => Succeeds
```

**Comment by bobhaffner** [comment]
I had some time this morning so I looked at this.  Here's what I found out.

This looks like the line where things head south.
https://github.com/pandas-dev/pandas/blob/ee9c7e9b19a1fa3c4499d10885dec72f1d651832/pandas/core/series.py#L248

The successful line below has name = None
`df.groupby('A').apply(lambda x: x[['B','C']].to_records())  # => Succeeds`

and the line that errors has a name = ['B', 'C']  
`df.groupby('A')[['B','C']].apply(lambda x: x.to_records())  # => TypeError`

ps. swapping out `to_records` for something similar like `to_dict` does work
`df.groupby('A')['B','C'].apply(lambda x: x.to_dict())`

**Comment by jreback** [comment]
hmm, it maybe that the rec-array is not handled correctly.

**Comment by bobhaffner** [comment]
Here's what I'm thinking

Modify the `NDFrameGroupBy` class method called `_wrap_applied_output` to deal with recarrays

Maybe something like the following which fixes this issue and all current tests in `test_groupby.py` still pass.   

Any feedback?

```
git diff ..upstream/master -- pandas/core/groupby.py 

diff --git a/pandas/core/groupby.py b/pandas/core/groupby.py
index 6a2f49a89..041239ed0 100644
--- a/pandas/core/groupby.py
+++ b/pandas/core/groupby.py
@@ -3977,8 +3977,6 @@ class NDFrameGroupBy(GroupBy):
                         return self._concat_objects(
                             keys, values, not_indexed_same=True,
                         )
-                if isinstance(v, np.recarray):
-                    return Series(values, index=key_index)
 
                 try:
                     if self.axis == 0:

```

**Comment by jreback** [comment]
NO. don't specifically deal with recarrays, you can possibly handle an array separaly though (recarray is a sub-class).

**Comment by zfrenchee** [comment]
This is all above my pay-grade, but I'd like to suggest that part of the fix involves adding a test which covers this call pattern. From what I'm reading here, it sounds like this behavior isn't covered.

**Comment by bobhaffner** [comment]
Hi Jeff, thanks for the quick reply.  Let me attempt to add some context.   I was trying to follow the existing logic found [here](https://github.com/pandas-dev/pandas/blob/35443b517df127642b338e630fc05339b411eaa1/pandas/core/groupby.py#L3941)  

```
if isinstance(v, (np.ndarray, Index, Series)):
    if isinstance(v, Series):
        ...
    if isinstance(v, np.recarray):  #proposed addition
        return Series(values, index=key_index)                
```

**Comment by bobhaffner** [comment]
Hi @zfrenchee  probably above mine too  :-)

but yes, it's typical to add tests to cover additions.  Thanks for submitting this by the way.

**Comment by yarimiz** [comment]
Hey, are there any news regarding this issue? Currently, I'm facing is with this code
```df.groupby('type')[['c1', 'c2']].apply(lambda x: ((x.c1.shift(1) - x.c2) / x.c1))```

that is raising
```TypeError: Series.name must be a hashable type```

I haven't found a solution for that.

@jreback

**Comment by damon-chem-e** [comment]
I'm having the same issue
`small['ret'] = small.groupby('isin')[['closingprice_eur','price_lag']].apply(lambda g: (g.closingprice_eur-g.price_lag)/g.price_lag)`

raises
`TypeError: Series.name must be a hashable type`

**Comment by javiqm12** [comment]
Having same issue here :(
