### ISSUE TITLE
LINT: pandas/scripts

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#18949]
need to lint these & add a rule in ci/lint.sh to check.

**Comment by gfyoung** [comment]
Yeah, that directory could certainly benefit from a lot of clean-up.

**Comment by bhavybarca** [comment]
I would like to work on this as my first issue

**Comment by gfyoung** [comment]
@bhavybarca : Go for it!

**Comment by bhavybarca** [comment]
what all do i need to do, i am a beginner

**Comment by jreback** [comment]
you need to add a add ``pandas/scripts/`` to the ci/lint.sh script (make it a separate step)
then run this ``export LINT=1; ci/lint.sh`` and see what turns up, which needs fixing. you can use ``autopep8`` to fix most

**Comment by bhavybarca** [comment]
so first i need to make ci/lint.sh script and then copy the files to it ?

**Comment by jreback** [comment]
it’s aleady there just edit

**Comment by bhavybarca** [comment]
can you please simplify all this a bit am i just starting

**Comment by TomAugspurger** [comment]
This file: https://github.com/pandas-dev/pandas/blob/master/ci/lint.sh

You'll add another `flake8` line like the others, but for `scripts/` directory.

@bhavybarca are you on Windows or Mac or Linux? You'll set the `LINT` environment variable and then run `ci/lint.sh`, which will print out a list of errors that need to be fixed.

**Comment by TomAugspurger** [comment]
It'll be roughly like

```
$ flake8 scripts/
scripts/api_rst_coverage.py:24:1: E302 expected 2 blank lines, found 1
scripts/api_rst_coverage.py:64:80: E501 line too long (90 > 79 characters)
scripts/api_rst_coverage.py:70:80: E501 line too long (93 > 79 characters)
scripts/api_rst_coverage.py:78:80: E501 line too long (88 > 79 characters)
...
```

**Comment by gfyoung** [comment]
@TomAugspurger : I prefer to use `flake8 scripts/`.  No need to lint the entire repository for this issue.

**Comment by TomAugspurger** [comment]
yeah, agreed.

**Comment by datapythonista** [comment]
I think it makes sense to include as part of this ticket, couple of other things related to the scripts:
* Fix PEP-8 issues, and add check to lint (as originally requested on the ticket)
* Add documentation to scripts that don't have it (like find_undoc_args.py)
* Make all the scripts executable (chmod a+x and #! header)
* Create a section in contributing.rst with the available script and what they are used for
* Make the scripts work regardless of the current directory (announce.py needs to be called from the pandas home, api_rst_coverage.py from the scripts directory...)
* Follow the same convention in script names (rename merge-pr.py to merge_pr.py)

What do you think?

**Comment by bhavybarca** [comment]
@TomAugspurger  i m on linux 16.04, all this makes a lot of sense now thanks ,just last thing how do i setup lint environment to run lint.sh

**Comment by gfyoung** [comment]
@datapythonista : All of these are excellent ideas!  I think linting is a pretty big step as it is though, so might be worthwhile to just open another issue.

**Comment by datapythonista** [comment]
@bhavybarca I'll take this, if that's all right

**Comment by bhavybarca** [comment]
@datapythonista yeah sure!!

**Comment by gfyoung** [comment]
As a follow-up, we should document all of these functions (@datapythonista : no need to this in your open PR, but wanted to add that just so that we don't forget :smile: )
