### ISSUE TITLE
is_scalar should return True for DateOffset objects

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#18943]

**Comment by gitavi** [comment]
I am attempting this as a first issue.

I traced the `is_scalar` function back to its [implementation which is in Cython](https://github.com/pandas-dev/pandas/blob/e56794984f17d1651d74e6dbcdbf77fbec53d45f/pandas/_libs/lib.pyx#L101) and it uses checks imported from the CPython datetime library to check the for the listed datetime objects. DateOffset objects are specific to Pandas so what would my next steps be here? I imagine importing DateOffset from where ever it's defined and using `isinstance` is not the answer...

**Comment by jreback** [comment]
need to add a ``is_offset`` to ``pandas/_libs/src/inference.pyx``, then you can use this in ``isscalar``. this would look very similar to ``pandas/_libs/src/util.pxd/is_period_object`` (you don't need to define it *also* in util.pxd though).

``is_offset`` should also be imported / tested in ``pandas/core/dtypes/common.py``
