### ISSUE TITLE
DOC deprecation warning to_datetime

### ISSUE THREAD

**Issue by glemaitre** [pandas-dev/pandas#18957]
I was wondering if in the documentation on [Timeseries](http://pandas-docs.github.io/pandas-docs-travis/timeseries.html?highlight=to_datetime), the occurrences `to_datetime` should be changed to `to_pydatetime`.

If this is the case I can make a PR.

**Comment by gfyoung** [comment]
@glemaitre : All references to `to_datetime` should have been removed due to #18648.  Any remaining ones *should* be to `pd.to_datetime`.  If not, a PR is welcome!

**Comment by jreback** [comment]
closing as this is done @gfyoung pls check in any event.
