### ISSUE TITLE
Unreachable case in internals.make_block?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#18965]
https://github.com/pandas-dev/pandas/blob/master/pandas/core/internals.py#L2937

```
        elif issubclass(vtype, np.datetime64):
            if hasattr(values, 'tz'):
                klass = DatetimeTZBlock
            else:
                klass = DatetimeBlock
```

The `hasattr(values, 'tz')` condition is never True in tests.  I'm not aware of any scenario in which it could be.  Am I missing something?

**Comment by jreback** [comment]
pls just add to the issue where you are keeping a separate list. if you can remove the code w/o breaking anything and we have sufficient coverage , then can be removed.

**Comment by jbrockmendel** [comment]
There's no list for this.

**Comment by jreback** [comment]
you have a master list for timeseries stuff, just add on there (or add a TODO in the code on another PR).
