### ISSUE TITLE
0.21.1 Windows wheels broken for older (<1.13) numpy version

### ISSUE THREAD

**Issue by letmaik** [pandas-dev/pandas#18967]
`RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa`
(0xb corresponds to 1.13.x and 0xa to 1.10.x-1.12.x)

This happens when doing `import pandas` from a Python 3.6 installation having numpy 1.12.0 installed and pandas 0.21.1. On the README it says "NumPy: 1.7.0 or higher" so this should work, right?

In the [release checklist](https://github.com/pandas-dev/pandas/wiki/Release-Checklist) it says:
> Windows wheels are built automatically by Christoph Gohlke.

But I couldn't find any further information like build scripts to verify how the build is done.

**Comment by TomAugspurger** [comment]
From [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/):

> Many binaries depend on numpy-1.13+mkl

So I believe that projects using NumPy's C API are built against NumPy 1.13. Is that correct @cgohlke?

> On the README it says "NumPy: 1.7.0 or higher" so this should work, right?

I think it's 1.8 now (need to update the README.md), but that's if you're building from source.

**Comment by cgohlke** [comment]
> So I believe that projects using NumPy's C API are built against NumPy 1.13. Is that correct @cgohlke?

That's correct.

**Comment by letmaik** [comment]
@cgohlke Since many packages depending on numpy's C API/ABI don't actually need the latest version, why not use an older one to make things more compatible? I fully understand if this is out of scope, as you make your wheels available for testing and evaluation purposes only (should they be on PyPI then?). If that's the case, then maybe @matthew-brett can help out by extending https://github.com/MacPython/pandas-wheels to build the Windows wheels there as well via Appveyor, so that a more official and transparent way of building Windows wheels exists.

**Comment by jbrockmendel** [comment]
Closeable?

**Comment by jreback** [comment]
yep
