### ISSUE TITLE
CI: NumPy is being upgraded

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#18992]
Looks like NumPy is being upgraded behind our back on master: https://travis-ci.org/pandas-dev/pandas/jobs/322904433#L1313

That's what's causing the failures on the 0.22 backports branch. Master is currently failing with NumPy 1.10, but we aren't catching it.

I'll look into it now.

cc @jreback

**Comment by TomAugspurger** [comment]
I may just use this issue for fixing the test failures in https://travis-ci.org/pandas-dev/pandas/jobs/322911128#L1783

At the moment this seem to be related issues seem to be https://github.com/numpy/numpy /pull/8231 and https://github.com/pandas-dev/pandas/issues/15363 (power of integer array to integer array). This test is skipped on NumPy>=1.12

```python
(Pdb) df.A.values[:5]
array([17, 92, 17, 79, 54])
(Pdb) other.A.values[:5]
array([17, 92, 17, 79, 54])
(Pdb) df.A.values[:5] ** other.A.values[:5]
array([-9223372036854775808, -9223372036854775808, -9223372036854775808,
       -9223372036854775808, -9223372036854775808])
```

So I'm tempted to just remove `pow` from that test.

**Comment by jreback** [comment]
oh, yes we DO skip on `pow` in test_binary_ops already (though its hacky). prob same issue. my fix is too extreme.

**Comment by TomAugspurger** [comment]
Yeah, it's just `pow`. Opened https://github.com/pandas-dev/pandas/pull/18995 so that it's easy to backport.
