### ISSUE TITLE
TST: test_read_clipboard_infer_excel warning

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#19010]
```
pandas/tests/io/test_clipboard.py::TestClipboard::()::test_read_clipboard_infer_excel
  /home/travis/build/jreback/pandas/pandas/io/clipboards.py:63: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
    return read_table(StringIO(text), sep=sep, **kwargs)
```

**Comment by jreback** [comment]
cc @gfyoung  if you'd take a look

**Comment by gfyoung** [comment]
There are two ways to fix this:

1) Pass in `engine='python'`
2) Assert that a warning gets issued (out of our control if their data requires multi-char separator and their defaulting to `engine='c'` in `read_table)

Thoughts?

**Comment by jreback** [comment]
yeah I think the ``engine='python'`` default may be ok here to avoid the warning, though maybe only need to do this if we are passing in a non-whitespace delimiter.

**Comment by gfyoung** [comment]
> yeah I think the engine='python' default

I don't think the default should be changed.  Rather, we should just pass in `engine='python'` for the test.

**Comment by jreback** [comment]
sgtm
