### ISSUE TITLE
API: prohibit non-numeric dtypes in construction of IntervalIndex

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#19016]
xref #18997 

prohibit construction of non-numeric sub-types for ``IntervalIndex``, e.g. ``object`` and ``categorical``. Not clear utility and causes a messy implementation.

**Comment by jreback** [comment]
cc @zfrenchee 
cc @jschendel 
@shoyer @TomAugspurger @jorisvandenbossche

**Comment by jschendel** [comment]
To be clear, do we want to disallow non-numeric dtypes just for `IntervalIndex`, or for `Interval` as well?

**Comment by jreback** [comment]
yes

**Comment by shoyer** [comment]
In theory, it makes sense to have string intervals, e.g., the first and last name on each page of a phonebook. But our current IntervalIndex indexing (with the interval tree) does not support efficient lookups for non-numbers.
