### ISSUE TITLE
x in pd.MultiIndex.drop(x)

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#19027]
#### Code Sample, a copy-pastable example if possible

```python
In [2]: 2 in pd.MultiIndex.from_product([[1, 2], [3, 4]]).drop(2)
Out[2]: True
```

#### Problem description

#2770 was actually more complex than what I understood when I suggested to close it. While ``remove_unused_levels()`` did solve the problem of just resetting the ``.levels``, the above is still buggy. Ironically, the above is [even tested](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/frame/test_mutate_columns.py#L198).

#### Expected Output

``False``

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: 84335621ad0a0d83302a80b6911d3985c00b5cee
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-4-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.23.0.dev0+10.g84335621a
pytest: 3.2.3
pip: 9.0.1
setuptools: 36.7.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.0dev
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.0
openpyxl: 2.3.0
xlrd: 1.0.0
xlwt: 1.3.0
xlsxwriter: 0.9.6
lxml: 4.1.1
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.2.1

</details>

**Comment by jreback** [comment]
this is a defined behavior. why should this not be True? The point is we don't perform this optimization as we don't really know when to do it.

**Comment by toobaz** [comment]
It should not be ``True``... because it's not in the index: being in the ``.levels`` is an implementation detail.

And while I agree about not optimizing implicitly, then we must check both that 2 is in ``.levels[0]`` _and_ that the relative code is in the ``.labels[0]``. Or more simply: ``2 in a_multiindex`` should just be implemented as ``(2,) in a_multiindex``, which already returns the correct result.

**Comment by jreback** [comment]
ok I suppose this is inconsistent.

**Comment by toobaz** [comment]
Right!
