### ISSUE TITLE
Index(data=..., dtype=CategoricalDtype(...)) doesn't maintain dtype

### ISSUE THREAD

**Issue by topper-123** [pandas-dev/pandas#19032]
#### Code Sample, a copy-pastable example if possible

```pythonc
>>> c = pd.api.types.CategoricalDtype(categories=['German', 'English', 'French'],
...                                   ordered=True)
>>> pd.Index(['German', 'English', 'French'], dtype=c)
CategoricalIndex(['German', 'English', 'French'],
                 categories=['English', 'French', 'German'],
                 ordered=False, dtype='category')
```
#### Problem description

Notice that the index isn't ordered and the categories have changed location.

If construction goes through CategoricalIndex, everything is ok.

#### Expected Output

Expected output is ``CategoricalIndex(['German', 'English', 'French'], categories=['German', 'English', 'French'], ordered=True)``.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 32
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.21.1
pytest: 3.2.1
pip: 9.0.1
setuptools: 36.5.0.post20170922
Cython: 0.26.1
numpy: 1.11.3
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.1.0
sphinx: 1.6.5
patsy: None
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.1.0
openpyxl: 2.4.8
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by jreback** [comment]
thought we had an issue for this one, ok, IIRC cc @jschendel @jorisvandenbossche @TomAugspurger 
 discussed this on the last Cat PR.

**Comment by jschendel** [comment]
My previous PR's related to CDT were in the context of `.astype(CDT)`, so this case wasn't something that was covered.  Fix looks super simple though, `dtype` just isn't being passed through to the CI constructor here:

https://github.com/pandas-dev/pandas/blob/04beec77e5a713dd90ba31dcf7ad43fd64ac55bb/pandas/core/indexes/base.py#L198-L200

Will open a PR to fix it later today.

**Comment by topper-123** [comment]
Could you maybe also do the same for ``IntervalIndex``? That is, if the dtype is a ``pd.api.types.IntervalDtype``, the constructor should be passed to ``IntervalIndex``. (this doesn't do anything useful ATM, but as a principle (IMO) if ``dtype=IntervalDtype()`` should delegate to ``IntervalIndex``.

This should only be 2 lines more....

**Comment by TomAugspurger** [comment]
> Could you maybe also do the same for IntervalIndex?

FWIW, I'm thinking through this type of issue with https://github.com/pandas-dev/pandas/issues/18767

I'd recommend avoiding more

```
if isinstance(foo, extension_type_1): ...
elif isinstance(foo, extension_type_2): ...
```

blocks for now.

**Comment by jschendel** [comment]
> I'd recommend avoiding more blocks for now

The block is actually already there, so it's really just a matter of passing `dtype` through to the `IntervalIndex` constructor.  Won't do anything right now, as the `IntervalIndex` constructor accepts a `dtype` kwarg, but never actually uses it.

Planning to open an issue in the near future to allow subtype conversion for `IntervalIndex`, e.g. converting `interval[int64]` to `interval[float64]`, which currently isn't possible via the constructor or `astype`.  I believe this same issue would come into play then, so it'd need to be addressed at some point in the near term.  Can do it in this PR or later, doesn't really matter to me.

**Comment by TomAugspurger** [comment]
> The block is actually already there, so it's really just a matter of passing dtype through to the IntervalIndex constructor

👍 then.

**Comment by topper-123** [comment]
Great, thanks.

FYI, my use case is combining several series of the same dtype, and there may be several such groups. If I can pre-register the dtype, I can covert to the reault index simply by ``Index(..., dtype=my_type)``, while if I explicitly have to supply ``CategoricalIndex``, ``IntervalIndex`` also, it gets unneccarily complicated to do this kind of thing.
