### ISSUE TITLE
No blosc:snappy compression in new versions (0.21+) 

### ISSUE THREAD

**Issue by hnykda** [pandas-dev/pandas#19060]
I stumbled upon a weird behavior while saving compressed data in different versions of pandas. Sorry if I overlooked something. I tried to find some mentions about changes in HDF in changelogs, but haven't found anything relevant.

#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
pd.DataFrame([[1]*100 for i in range(1000)], dtype='int8').to_hdf('a.hdf', 'df')
```

Consider version `0.20.3`, running:

```
$ python -c "import pandas; df = pandas.read_hdf('a.hdf'); df.to_hdf('c.hdf', 'df', complib='blosc:snappy'); pandas.show_versions()"
```
produces a file `c.hdf` of size 11MB.

After installing version `0.22` (but it is the same on 0.21 as well) 

```
$ conda install pandas==0.22
$ python -c "import pandas; df = pandas.read_hdf('a.hdf'); df.to_hdf('b.hdf', 'df', complib='blosc:snappy'); pandas.show_versions()"
```
produces file `b.hdf` with almost same size as `a.hdf` (~67MB)

#### Problem description
Under pandas 0.21+, `blosc:snappy` reduction while saving to HDF is much worse than under `0.20.3`. 

#### Expected output
Reduced file. 
 

[Full gist](https://gist.github.com/hnykda/921eb78dfd9a33bf9c4565e333fdafad)

**Comment by jreback** [comment]
you don't appear to have blosc installed in either version.

**Comment by hnykda** [comment]
Thanks Jeff.

I did installed that through `conda install blosc` fine, but for some reason, it didn't get picked up even though I reactivate my env. Installing `blosc` using `pip install blosc` worked fine...

But shouldn't pandas raise if the library is not found, as is stated in the docs.

**Comment by jreback** [comment]
pytables is in charge of raising, but I don't think it actually will, rather it will ignore .

**Comment by hnykda** [comment]
I see.

[The sentence](https://github.com/pandas-dev/pandas/blob/v0.22.0/pandas/core/generic.py#L1462) `Specifying a compression library which is not available issues a ValueError` is then confusing though...

**Comment by jreback** [comment]
if it didn't raise, then its working.

**Comment by hnykda** [comment]
Well, the compression clearly didn't work before - the file size was the same (without an error) and after installation of blosc using pip, it reduced the filesize to 1/7th of the original file.
