### ISSUE TITLE
`(x + 1) % 1` inside test_multi.py

### ISSUE THREAD

**Issue by Mofef** [pandas-dev/pandas#19092]
#### Code Sample, a copy-pastable example if possible

https://github.com/pandas-dev/pandas/blob/93033151a8d8aaa650a81df9f41347758bf6c393/pandas/tests/indexes/test_multi.py#L170-L171

#### Problem description

I assume this is supposed to shift the labels cyclically by one. Then `% 4` and `% 2` should be used. Otherwise its at least weird to write `(x + 1) % 1` instead of `0`.

**Comment by jreback** [comment]
do you have an example where this is incorrect?

**Comment by Mofef** [comment]
No, i just wanted to raise the attention in case this is not on purpose.

**Comment by jreback** [comment]
I am still not clear on what the issue is? are you saying the test is wrong? you can certainly enhance it if you want

**Comment by gfyoung** [comment]
@jreback : @Mofef is saying that `(x + 1) % 1` seems a little weird given that it always should return 0.

**Comment by jreback** [comment]
this is fine.
