### ISSUE TITLE
Change "NUMfocus" to "NumFOCUS" on pandas.pydata.org

### ISSUE THREAD

**Issue by Dr-G** [pandas-dev/pandas#19099]
Hi,

Please replace instances of NUMFocus with NumFOCUS (note proper capitalization) on the website. I'm still very remedial on my GitHub skills and learning how to submit PRs and unfortunately wasn't able to sort this one out. :\

"You must be on a branch to make or propose changes to this file."

Thanks,
Gina
--
Dr. Gina Helfrich
Communications Director, NumFOCUS

**Comment by TomAugspurger** [comment]
Fixed the website in https://github.com/pandas-dev/pandas-website/commit/8e0a2c640f1b65a34da005fe3c7d73ff36ca4a4d so that should be fixed for the main site. https://github.com/pandas-dev/pandas/pull/19100 is fixing the references in http://pandas.pydata.org/pandas-docs/stable/.

**Comment by Dr-G** [comment]
Thank you, Tom!
