### ISSUE TITLE
Detect and remove features deprecated before 0.20.0

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#19111]
For what I could see, there is still some functionality deprecated before 0.20.0, but which hasn't been removed, as it was missing from #6581.

This includes among others:
* `Categorical.labels`, deprecated in 0.18.0
* The whole `pandas.stats` (rolling_mean...), deprecated in 0.18.0
* `pandas.core.datetools`, deprecated in 0.19.0
* `flavor` parameter of `SQLiteDatabase

I wrote a script that lists the version in which every `FutureWarning` was released (I think it makes sense adding it to pandas).

This is the output for versions older than 0.20.0:

> v0.18.0        3ef82867 600)    pandas/core/categorical.py
> v0.18.0        14cf67fb 132)    pandas/core/resample.py
> v0.18.0        14cf67fb 685)    pandas/core/resample.py
> v0.18.0        14cf67fb 700)    pandas/core/resample.py
> v0.18.0        67730ddf 685)    pandas/core/strings.py
> v0.18.0        3156395c 200)    pandas/stats/moments.py
> v0.18.0        3156395c 240)    pandas/stats/moments.py
> v0.18.1        e4df1ac7 2391)   pandas/util/testing.py
> v0.19.0        3f3839b6 17)     pandas/core/datetools.py
> v0.19.0        3f3839b6 67)     pandas/util/_depr_module.py
> v0.19.0        8acfad34 47)     pandas/io/sql.py
> v0.19.0        8acfad34 56)     pandas/io/sql.py
> v0.19.0        95541952 101)    pandas/util/_depr_module.py
> v0.19.0        b1bfd2fd 939)    pandas/io/parsers.py

Can you please confirm if am I right, and I'll submit a PR?

**Comment by jreback** [comment]
Categorical.labels, deprecated in 0.18.0
The whole pandas.stats (rolling_mean...), deprecated in 0.18.0

are already covered in #6581 (1st is available to do, 2nd is pending)

**Comment by jreback** [comment]
added the remaining 2. pls feel free to do a PR for the ones that are available in #6581

**Comment by jreback** [comment]
> I wrote a script that lists the version in which every FutureWarning was released (I think it makes sense adding it to pandas).

sure would take this!

**Comment by datapythonista** [comment]
Not sure if we also want to add to the list the `expand` parameter of `Series.str.extract`, which was set in 0.18.0 to change its default value from False to True with a deprecation warning.

Then, if I understood you correctly, everything I reported except `pandas.stats` can be removed, right?
