### ISSUE TITLE
DOC: period missing at end of the pandas.DataFrame docstring

### ISSUE THREAD

**Issue by jokuha** [pandas-dev/pandas#19141]
#### Problem description

There is a full stop missing at the end of the pandas.DataFrame docstring.

#### Code Sample

```python
import pandas as pd
help(pd.DataFrame)
```

#### Expected Output

Two-dimensional [...] The primary pandas data structure **.**

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
--------------–--
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Darwin
OS-release: 17.3.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: None
pip: None
setuptools: 36.8.0
Cython: 0.27.3
numpy: 1.13.3
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.6.5
patsy: None
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 0+unknown
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by gitavi** [comment]
I don't think the Numpy Docstring Standard explicitly requires periods. I took a quick look and other "core" classes (like `Index` and `MultiIndex`) are also missing periods at the end of their respective docstrings so if one wants to make this aesthetic change it would probably be best to write a script with the appropriate regular expression to put the periods where they aren't.
