### ISSUE TITLE
AttributeError: module 'pandas' has no attribute 'Data'

### ISSUE THREAD

**Issue by aeross77** [pandas-dev/pandas#19155]
import pandas as pd
dict={
    "country":["Brasil", "Russia", "India", "China", "South Africa"],
    "capital":["Brasilia", "Moscow", "New Delhi", "Beijing", "Pretoria"],
    "area":[8.51, 17.10, 3.28, 9.59, 1.22],
    "population":[200.4, 143.5, 1252,1357,52.98]
}

brics = pd.Data.Frame(dict)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-177bfca7127f> in <module>()
----> 1 brics = pd.Data.Frame(dict)  #no success but works fine in the terminal

AttributeError: module 'pandas' has no attribute 'Data'

#### Problem description
I get this message in anaconda/jupiter lab, however it works fine when using the terminal. I'd love to be bale to use Jupiter lab in the future. I have updated pandas and anaconda and still getting this attribute error message. 

I've tried using: (pandas) bash-3.2$ python -c "import pandas; print(pandas.plotting.scatter_matrix)"
<function scatter_matrix at 0x10f6b5a60>

--> however this doesn't run in my Mac. I'm just a python user and doesn't know much of IT. 

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Darwin
OS-release: 17.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.20.3
pytest: 3.2.1
pip: 9.0.1
setuptools: 36.5.0.post20170921
Cython: 0.27.3
numpy: 1.13.3
scipy: 1.0.0
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.1.0
openpyxl: 2.4.9
xlrd: 1.1.0
xlwt: 1.2.0
xlsxwriter: 1.0.2
lxml: 4.1.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None

**Comment by TomAugspurger** [comment]
`DataFrame`, not `Data.Frame`.

**Comment by Talionchik** [comment]
'brics = pd.Data.Frame(dict)' - Remove the dot.
![image](https://user-images.githubusercontent.com/83535100/195518450-3f560763-ccd0-45f5-aa95-08dda9056bd0.png)
