### ISSUE TITLE
groupby is retaining index info from source DataFrame, breaking reset_index

### ISSUE THREAD

**Issue by allanelder** [pandas-dev/pandas#19192]
#### Code Sample, a copy-pastable example if possible

```python
from datetime import datetime
from datetime import timedelta, date
import pandas as pd


def get_date(year, month, day):
    try:
        return date(year, month, day)
    except ValueError:
        return None


file_location = "sample.csv"
daily_df = pd.read_csv(file_location, index_col=["Date"], parse_dates=True)
current_year = datetime.now().year

max_df = daily_df.groupby(by=[daily_df.index.month, daily_df.index.day])  \
    .max()

#max_df.index.names = [None, None]
print(max_df.index.names)
print(max_df)

max_df = max_df.reset_index()
print("max_df.reset_index")
print(max_df)
```
#### Problem description

groupby seems to have a breaking change or a bug; if you look at the above code, you can see that I'm creating a df with using the column 'Date' as an index. I then do a groupby into a df called max_df - the issue is that the max_df retains the index name from the daily_df for each of the groupby columns. This means I can no longer do a reset_index and keep the Date column, as Pandas thinks that the Date column already exists. I can work around this for now by uncommenting the max_df.index.names = [None, None] line of code - you'll see everything works as expected at that point. 

This used to work under 0.18.1 - max_df.index.names would be [None, None] - it no longer works under 0.22.0

The sample data file is attached.
[sample.zip](https://github.com/pandas-dev/pandas/files/1624097/sample.zip)

#### Expected Output

df with the max values on monthly basis

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.0.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.22.0
pytest: 3.0.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.14.0
scipy: 0.18.1
pyarrow: None
xarray: None
IPython: 5.1.0
sphinx: 1.5.1
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: 1.2.0
tables: 3.2.2
numexpr: 2.6.1
feather: None
matplotlib: 2.0.0
openpyxl: 2.4.1
xlrd: 1.1.0
xlwt: 1.2.0
xlsxwriter: 1.0.2
lxml: 3.7.2
bs4: 4.5.3
html5lib: None
sqlalchemy: 1.1.11
pymysql: 0.7.11.None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
can you show a copy-pastable minimal example. no idea what you are trying to do.
