### ISSUE TITLE
IntervalIndex nbytes computation

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#19209]
Currently, it looks like `IntervalIndex.nbytes` just uses `IndexOpsMixin.nbytes`

```python
@property
def nbytes(self):
    """ return the number of bytes in the underlying data """
    return self._values.nbytes
```

Should it instead be `self.left.nbytes + self.right.nbytes`? This will be faster, and I think more correct.

**Comment by jschendel** [comment]
> Should it instead be self.left.nbytes + self.right.nbytes?

That makes more sense to me.  Not sure exactly what the use case of `nbytes` is though, so really just basing this off the docstring description.
