### ISSUE TITLE
categorical series with null converts ints to float

### ISSUE THREAD

**Issue by cstjean** [pandas-dev/pandas#19214]
```python
In [4]: import pandas as pd, numpy as np

In [5]: sr = pd.Series([1,2, np.nan], dtype="O").astype("category")
   ...: sr
   ...: 
Out[5]: 
0    1.0
1    2.0
2    NaN
dtype: category
Categories (2, int64): [1, 2]

In [6]: sr[0]
Out[6]: 1.0
```
Shouldn't it keep them as ints? Interestingly, `pd.Series(["a", 1,2, np.nan], dtype="O").astype("category")` doesn't do the conversion.

**Comment by jreback** [comment]
so ``.loc`` does this correctly, meaning we defer to the underlying data source for getting the values, rather than do the array conversion (which ``__getitem__``) does. So its buggy, changing this may not be easy though.

```
In [1]: sr = pd.Series([1,2, np.nan], dtype="O").astype("category")

In [2]: sr
Out[2]: 
0    1.0
1    2.0
2    NaN
dtype: category
Categories (2, int64): [1, 2]

In [3]: sr.loc[0]
Out[3]: 1
```

**Comment by jreback** [comment]
cc @toobaz 
cc @jschendel 

if you want to wade thru some indexing code!

**Comment by jreback** [comment]
> pd.Series(["a", 1,2, np.nan], dtype="O").astype("category")

this is as expected, the objs in the series are actually store (and not as a numpy array).
