### ISSUE TITLE
TST: split tests for windows to sub-modules

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#19228]
after #18723 

can split test_window.py to a sub-dir ``pandas/tests/window/`` and have
``test_rolling, expanding, emwa`` and prob ``test_window`` (for other)

**Comment by sunilk747** [comment]
@jreback Hello. I am new to pandas repo. I would really like to work on this issue. Can you please provide more details regarding what are the things to be done here.

**Comment by jreback** [comment]
we need to split test_window.py to 3 files in a subdir window

test_rolling
test_expanding
test_ewma

**Comment by gilbertoolimpio** [comment]
Hello @sunilk747 Are you still working on it?

**Comment by sunilk747** [comment]
@gilbertoolimpio No. I am not working on it. If you want to take up this issue please go ahead.

**Comment by gilbertoolimpio** [comment]
OK! @sunilk747 I will work on it!
