### ISSUE TITLE
TST: clean up all of the compression tests

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#19226]
we have tests for compression kwargs all over the code base, e.g. ``grep -r compression pandas/tests/``

I think *only* the json and parser network tests parametrize these. The others have copy-pasted code all over the place.

Needs to be consolidated, and the fixtures that are used in json/parser should be pushed to the very top level conftest.py

would accept incremental (multiple) PR's for this.

**Comment by reidy-p** [comment]
@jreback do you see any more compression tests that should be cleaned? There are some other compression tests that I haven't touched but I don't see any way to clean them up easily.

**Comment by jreback** [comment]
I think tests still in :pandas/tests/io/parser/compression.py and test_pickle

**Comment by jreback** [comment]
in test_pickle there is a TestCompression class, did that get missed?

**Comment by jreback** [comment]
@reidy-p anything remaining on this?

**Comment by reidy-p** [comment]
@jreback I think some of the tests in ``pandas/tests/io/parser/compression.py`` can be parametrized. I will try to submit a PR for this.

We could also move the ``compress_file`` function in ``pandas/tests/io/test_pickle.py`` to ``pandas/util/testing.py`` to make it closer to the ``decompress_file`` utility function and possibly re-use it for other tests.
