### ISSUE TITLE
can't import pandas unless press cntr-c

### ISSUE THREAD

**Issue by LittleLittleCloud** [pandas-dev/pandas#19222]
#### Problem description
I have to press ctrl-c to load pandas in python termination. Or it just stuck there.
It's too weird, Is there anyone meeting the same situation?
PS: the pandas version on my PC is pandas 0.20.3, OS is win10. I install it through anaconda.

**Comment by jreback** [comment]
you have a system issue which is impossible to diagnose w/o a reproducible exampel.
