### ISSUE TITLE
TimedeltaBlock.fillna treats int as second

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#19233]
Seems like assuming nanosecond would be more natural, or just refusing to assume.

https://github.com/pandas-dev/pandas/blob/master/pandas/core/internals.py#L1981

**Comment by jbrockmendel** [comment]
There's only one test that hits this and its benign because it happens to fill with 0.

**Comment by jreback** [comment]
yeah this is probably not idea, does this show up in user facing code?

**Comment by jbrockmendel** [comment]
Closed by #24694
