### ISSUE TITLE
_get_attributes_dict formalization

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#19249]
Index subclasses have a `_get_attributes_dict` method that would be useful to employ elsewhere (here I'm thinking of DateOffset subclasses and discussion in #19174).  Could/should that be defined in a Mixin class (say in core.base) so that pattern could be documented and used elsewhere?

**Comment by jreback** [comment]
we do things this also for groupby/rolling as well. I suppose it could be moved to the pandas/core/base.py/PandasObject which already mixes everything (well except for offsets)

**Comment by jbrockmendel** [comment]
Because offsets are perf-sensitive it might need to be implemented in cython.  That aside, rolling it into PandasObject makes a lot of sense.

`Block.make_block` looks a lot like `Index._shallow_copy`.  A bunch of the DatetimeIndexOpsMixin arithmetic/comparison (ones that I think @TomAugspurger agrees would go nicely in an Array-level class) use _shallow_copy.  Making the Block classes conform to the IndexOps name conventions would make that refactor a lot easier.

**Comment by jreback** [comment]
not sure we need an issue for this. if you want to do it great. Not sure make_block and _shallow_copy make sense to be combined, they are different animals.
