### ISSUE TITLE
DOC: NumFOCUS link broken at http://pandas.pydata.org

### ISSUE THREAD

**Issue by charlieahern** [pandas-dev/pandas#19267]
The links to NumFOCUS on the pandas web site are all broken.
 
Link on pages:
http://pandas.pydata.org
http://pandas.pydata.org/about.html
http://pandas.pydata.org/community.html
http://pandas.pydata.org/donate.html

is:
https://www.numfocus.org/open-source-projects.html

should be:
https://www.numfocus.org/project/pandas/
 - - - 
This is my first attempt at logging a 'bug' on GitHub, so I apologize if I'm using the wrong protocol in  the wrong place. I'm learning.

**Comment by TomAugspurger** [comment]
Thanks Charlie.

@Dr-G do you know if https://www.numfocus.org/open-source-projects.html used to be a valid URL that should be redirected? Either way, we'll update our docs to point to https://www.numfocus.org/sponsored-projects/.

The reference in `doc/source/overview.rst` will need to be updated. I think the rest need to be changed in http://github.com/pandas-dev/pandas-website.

**Comment by Dr-G** [comment]
Hi folks,
We're in process of a hand-off from the web designers to NumFOCUS staff after a site re-design, so I'll be able to fix it once I get my admin login back (hopefully today). We'd asked them to handle redirects but of course, things don't always go as you'd want them to. Thanks for your patience.

**Comment by charlieahern** [comment]
The links work now: [](https://www.numfocus.org/sponsored-projects/)
