### ISSUE TITLE
float precision issue with rolling sum

### ISSUE THREAD

**Issue by liuguangyu0220** [pandas-dev/pandas#19308]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
```

```python
df = pd.DataFrame({'foo': [1.0001] * 5 + [0.]*5})
```

```python
df
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>foo</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1.0001</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1.0001</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1.0001</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1.0001</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1.0001</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>6</th>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>7</th>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>8</th>
      <td>0.0000</td>
    </tr>
    <tr>
      <th>9</th>
      <td>0.0000</td>
    </tr>
  </tbody>
</table>
</div>

```python
df.rolling(2).sum()
```
<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>foo</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2.000200e+00</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2.000200e+00</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2.000200e+00</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2.000200e+00</td>
    </tr>
    <tr>
      <th>5</th>
      <td>1.000100e+00</td>
    </tr>
    <tr>
      <th>6</th>
      <td>4.440892e-16</td>
    </tr>
    <tr>
      <th>7</th>
      <td>4.440892e-16</td>
    </tr>
    <tr>
      <th>8</th>
      <td>4.440892e-16</td>
    </tr>
    <tr>
      <th>9</th>
      <td>4.440892e-16</td>
    </tr>
  </tbody>
</table>
</div>

#### Problem description

Rolling sum of zeros sometimes gives a very small negative number, which is not the desired behavior.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.4.final.0
python-bits: 64
OS: Linux
OS-release: 4.1.35-pv-ts2
machine: x86_64
processor: 
byteorder: little
LC_ALL: en_US.utf8
LANG: en_US.utf8
LOCALE: en_US.UTF-8

pandas: 0.20.3
pytest: 3.2.1
pip: 9.0.1
setuptools: 36.4.0
Cython: 0.26
numpy: 1.12.1
scipy: 0.19.1
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: None
xlsxwriter: 0.9.8
lxml: None
bs4: 4.6.0
html5lib: 0.9999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by mroeschke** [comment]
xref #13254

**Comment by jreback** [comment]
duplicate.

**Comment by jreback** [comment]
thanks for the report @liuguangyu0220 ideally we would use kahan summation to avoid this problem. welcome to take a PR to do so.
