### ISSUE TITLE
Series.nonzero(): Returns locations, not indices

### ISSUE THREAD

**Issue by tchekov-** [pandas-dev/pandas#19312]
#### Problem description
Documentation says

Series.nonzero(): Return the indices of the elements that are non-zero

while it actually seems to return the integer locations.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: AMD64 Family 21 Model 16 Stepping 1, AuthenticAMD
byteorder: little
LC_ALL: None
LANG: en
LOCALE: None.None

pandas: 0.21.0
pytest: None
pip: 9.0.1
setuptools: 36.5.0.post20170921
Cython: None
numpy: 1.13.3
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.1.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.9999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by TomAugspurger** [comment]
It'd be good to clarify that the return values is the integer locations.

**Comment by drorata** [comment]
What is the difference between indices and integer locations? It seems to me that the documentation is very clear.

**Comment by TomAugspurger** [comment]
Indices may be the index labels, which may or may not match the positions.

**Comment by drorata** [comment]
Make sense. I will stress this in the documentation and add an example.

**Comment by drorata** [comment]
Wait... even if the indices are not integers, the output of `nonzero`  can still be used for slicing:

```python
>>> import pandas as pd
>>> s = pd.Series([0, 3, 0, 4])
>>> s.index=['a', 'b', 'c', 'd']
>>> s.nonzero()
(array([1, 3]),)
>>> s.iloc[s.nonzero()[0]]
b    3
d    4
dtype: int64
```

Isn't it surprising?

**Comment by tchekov-** [comment]
Series.iloc is for selection by integer position (and supports slicing):
`s.iloc[[1,3]]` returns the 2nd and 4th value in s (regardless of the index).

The label based indexer is Series.loc: 
`s.loc[['b', 'c']]` returns the same elements.

**Comment by rahultelgote1989** [comment]
Hi,
I am new the pandas and this repository. My question is pandas.Series.nonzero() returns indices of the non zero elements whether you provide indexing or not is that the correct behavior? Should not it return the index values if the indexing is provided by user?

**Comment by TomAugspurger** [comment]
`.nonzero` is primarily for compatability with NumPy, so what want to return the integer positions.
