### ISSUE TITLE
pytables._version out of date?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#19314]
In pandas.io.pytables:

https://github.com/pandas-dev/pandas/blob/ca2d2611c5a657720661990e2f3016356e577d1d/pandas/io/pytables.py#L56

```
# versioning attribute
_version = '0.15.2'

[...]

    def set_object_info(self):
        """ set my pandas type & version """
        self.attrs.pandas_type = str(self.pandas_kind)
        self.attrs.pandas_version = str(_version)
        self.set_version()
```

It looks like `_version` is supposed to correspond to `pd.__version__` in which case it is way out of date and probably shouldn't be hard-coded.

**Comment by jreback** [comment]
not at all
this is the last time the version was actually changed

**Comment by jbrockmendel** [comment]
The usage suggests that _version corresponds to `pandas_version`.  Am I wrong in interpreting this as corresponding to `pd.__version__`?  Does this mean the last `pd.__version__` in which this file was changed?
