### ISSUE TITLE
Reduce distribution size

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#19320]
xref https://github.com/conda/conda/issues/6756#issuecomment-359107467

We include a bunch of SAS, CSV, pickle, etc. files in the distributions that are only used for testing. I think these could be excluded (and the tests rewritten to skip if the files aren't present).

**Comment by jreback** [comment]
can u see the total size
these are all very small

**Comment by TomAugspurger** [comment]
Yeah I had to run before finishing the post. I think it’s about 20% of the sdist. I’ll edit in details.

**Comment by jreback** [comment]
yeah i guess could trim the sas a bit
