### ISSUE TITLE
Index subclasses do not check parameters

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#19348]
#### Code Sample, a copy-pastable example if possible

```python
In [2]: pd.CategoricalIndex([1,2,3], asdasdsa=None)
Out[2]: CategoricalIndex([1, 2, 3], categories=[1, 2, 3], ordered=False, dtype='category')

In [3]: pd.PeriodIndex(['2012'], freq='Y', asdsadsa=None)
Out[3]: PeriodIndex(['2012'], dtype='period[A-DEC]', freq='A-DEC')

In [4]: pd.DatetimeIndex(['2012-02-02'], asdsadsa=None)
Out[4]: DatetimeIndex(['2012-02-02'], dtype='datetime64[ns]', freq=None)

In [5]: pd.MultiIndex([[]], [[]], asdsadsa=None)
Out[5]: 
MultiIndex(levels=[[]],
           labels=[[]])
```

#### Problem description

Compare to

```python

In [6]: pd.Categorical([1,2,3], asdadsads=None)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-cbc1bd28e752> in <module>()
----> 1 pd.Categorical([1,2,3], asdadsads=None)

TypeError: __init__() got an unexpected keyword argument 'asdadsads'

In [7]: pd.Int64Index([1,2,3], asdadsa=None)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-7395c56977ea> in <module>()
----> 1 pd.Int64Index([1,2,3], asdadsa=None)

TypeError: __new__() got an unexpected keyword argument 'asdadsa'

In [8]: pd.Series([1,2,3], asdasda=None)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-abfdb9dbe6f7> in <module>()
----> 1 pd.Series([1,2,3], asdasda=None)

TypeError: __init__() got an unexpected keyword argument 'asdasda'

```

Related to #19168

#### Expected Output

``TypeError``

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: c271d4dd0b014c41bd91048fa6e8d33c5bf27b44
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-5-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.23.0.dev0+121.gc271d4dd0
pytest: 3.2.3
pip: 9.0.1
setuptools: 36.7.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.0dev
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.0
openpyxl: 2.3.0
xlrd: 1.0.0
xlwt: 1.3.0
xlsxwriter: 0.9.6
lxml: 4.1.1
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.2.1

</details>

**Comment by cr458** [comment]
I could have a look at this if needed?

**Comment by toobaz** [comment]
@cr458 (I guess it would be great)

**Comment by gilbertoolimpio** [comment]
A newbie here! Would like to help! @cr458 Can I help you?
