### ISSUE TITLE
Shortcut functions in transform are not grouped

### ISSUE THREAD

**Issue by DiegoAlbertoTorres** [pandas-dev/pandas#19354]
```ipython
$ ipython3
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pandas as pd

In [2]: df = pd.DataFrame({'A': [1, 1, 2], 'B': [1, 2, 3]})

In [3]: df.groupby('A').transform('rank')
Out[3]: 
   B
0  1
1  1
2  2

In [4]: df.groupby('A').transform(lambda x: x.rank())
Out[4]: 
     B
0  1.0
1  2.0
2  1.0

```
#### Problem description
It seems like the functions provided through shorthand strings, such as 'rank', do not obey the groupings of data. For example, one would expect Out[3] and Out[4] to be the same in the code above. Instead, it seems like using `.transform('rank')` doesn't actually obey the grouping and just ranks independently. I've reproduced this with larger dataframes as well.

**Comment by chris-b1** [comment]
Thanks for the report.  It's not exactly that it ignores the grouping, but instead is falling through a fast-path, that assumes `rank()` is an aggregation - here:
https://github.com/pandas-dev/pandas/blob/2952fbd556e1bc4b5fac70c727652b5419e8e096/pandas/core/groupby.py#L4132

I think a quick-fix would be to add `'rank'` to the list of whitelisted transforms here, but might need to rethink/refactor this whole dispatch a bit
https://github.com/pandas-dev/pandas/blob/2952fbd556e1bc4b5fac70c727652b5419e8e096/pandas/core/groupby.py#L345

Also xref to #15779

**Comment by jreback** [comment]
xref https://github.com/pandas-dev/pandas/issues/14741 and #11759

@DiegoAlbertoTorres welcome for a fix here!

**Comment by mroeschke** [comment]
Looks like these match on master now. Could use a test

```
In [99]: In [1]: import pandas as pd
    ...:
    ...: In [2]: df = pd.DataFrame({'A': [1, 1, 2], 'B': [1, 2, 3]})
    ...:
    ...: In [3]: df.groupby('A').transform('rank')
Out[99]:
     B
0  1.0
1  2.0
2  1.0

In [100]: In [4]: df.groupby('A').transform(lambda x: x.rank())
     ...:
Out[100]:
     B
0  1.0
1  2.0
2  1.0

In [101]: df
Out[101]:
   A  B
0  1  1
1  1  2
2  2  3

In [102]: pd.__version__
Out[102]: '1.1.0.dev0+1974.g0159cba6e'
```
