### ISSUE TITLE
ipynb in document page is not actually ipynb format

### ISSUE THREAD

**Issue by xuboying** [pandas-dev/pandas#19357]
Document page for example: 
https://pandas.pydata.org/pandas-docs/stable/style.html
on top

> New in version 0.17.1
> 
> Provisional: This is a new feature and still under development. We’ll be adding features and possibly making breaking changes in future releases. We’d love to hear your feedback.
> 
> This document is written as a Jupyter Notebook, and can be viewed or **downloaded here.**

http://nbviewer.ipython.org/github/pandas-dev/pandas/blob/master/doc/source/style.ipynb

The target style.ipynb file is just exported HTML file, not the original ipynb(json) format

**Comment by TomAugspurger** [comment]
There's an option to download it in the top-right of the toolbar.
