### ISSUE TITLE
.isin implicitly converts data types

### ISSUE THREAD

**Issue by caerner** [pandas-dev/pandas#19356]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
pd.__version__
Out[1]: '0.22.0'

data = pd.Series([-9.0, 0.0])
data.isin([-9, -0.5])

Out[2]: 
0     True
1    False
dtype: bool

data = pd.Series([-9, 0])
data.isin([-9, -0.5])

Out[3]: 
0    True
1    True
dtype: bool


```
#### Problem description

.isin seems to implicitly convert the data type of what is passed in values depending on the data type of the Series. In the above example, I would expect the output to be (True, False) in both cases. There seems to have been a change in behavior after pandas version 0.19.2. With version 0.19.2 the output is in both cases (True, False).

#### Expected Output

```python
import pandas as pd
pd.__version__
Out[1]: '0.19.2'

data = pd.Series([-9.0, 0.0])
data.isin([-9, -0.5])

Out[2]: 
0     True
1    False
dtype: bool

data = pd.Series([-9, 0])
data.isin([-9, -0.5])

Out[3]: 
0    True
1    False
dtype: bool


```

**Comment by jreback** [comment]
cross data type conversion is hard.  Its somewhere: https://github.com/pandas-dev/pandas/blob/master/pandas/core/algorithms.py#L66. pull requests welcome.

**Comment by jdoepfert** [comment]
Will take a look today

**Comment by jreback** [comment]
this issue seems to overlap with: https://github.com/pandas-dev/pandas/issues/21804

cc @phofl @avinashpancham

**Comment by avinashpancham** [comment]
I see @phofl started earlier with the PR, so I dont mind leaving this to him.

**Comment by phofl** [comment]
Thx, I will look into this and give feedback if mine fixes both

**Comment by avinashpancham** [comment]
Issues look similar and (our proposed modifications too!), so I guess it will fix both :)

**Comment by phofl** [comment]
It is exactly the same :)
