### ISSUE TITLE
Python crashes when executing memory_usage(deep=True) on a sparse series

### ISSUE THREAD

**Issue by quale1** [pandas-dev/pandas#19368]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

s = pd.Series([None])
s.to_sparse().memory_usage(deep=True)

# crashes - Kernel died, restarting
```
#### Problem description

Executing the `memory_usage(deep=True)` method on a sparse series crashes Python. (With `deep=False` the method works as expected.)
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.22.0
pytest: 3.2.1
pip: 9.0.1
setuptools: 36.5.0.post20170921
Cython: 0.26.1
numpy: 1.13.3
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.1.0
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by jreback** [comment]
sparse is not fully test covered. a pull request to fix is welcome!

**Comment by hexgnu** [comment]
I hooked up gdb and tracked down the issue to inside of the lib.pyx which assumes that series's are of length > 0. I made a PR that _should_ fix it, though we'll see how the tests chooch.
