### ISSUE TITLE
Duplicate xstrtod implementations

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#19361]
In _libs/src/parse_helper.h and libs/src/parser/tokenizer.c

Not identical, comments suggest the tokenizer.c version may be more modern.

**Comment by chris-b1** [comment]
The core functionally is the same, differences are the tokenizer.c version handles a thousands separator, the parse_helper.c version has a `maybe_int` out variable, agree they could be combined.

**Comment by jbrockmendel** [comment]
@chris-b1 There are .gitignore and Makefile files in _libs/src/parser.  Are those used for something or remnants from the Old Days?

**Comment by chris-b1** [comment]
Yeah, definitely something very old, I think those could be cleaned out too.

**Comment by jbrockmendel** [comment]
It also looks like src/klib/ktypes.h and kvec.h are unused, though this should be checked by someone who understands C namespaces.

**Comment by chris-b1** [comment]
Yeah, those are unused as well - for good and bad C doesn't have namespaces, (or modules, or imports, etc) - all it can really do is textual inclusion, so if those aren't `#include`'ed somewhere, they aren't used.

**Comment by jbrockmendel** [comment]
_libs.groupby.kth_smallest_c almost identical to _libs.algos.kth_smallest

**Comment by jbrockmendel** [comment]
@chris-b1 hopefully a softball question: Currently util [gets its](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/src/util.pxd#L89) INT32_MAX etc constants from headers/stdint.h.  headers/stdint.h contains special-casing for windows systems.  Is that special casing relevant for UINT64_MAX etc, or can we use the (much more convenient for current purposes) `from libc.stdint cimport ...`?

**Comment by chris-b1** [comment]
Yes, that special casing is required - cython definitions look for a `'stdint.h'` which the Windows  toolchain for 2.7 doesn't have, so the build would fail.
https://www.microsoft.com/en-us/download/details.aspx?id=44266
