### ISSUE TITLE
More clean up of the scripts

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#19372]
In #18949, scripts have been improved, to respect PEP-8, to be executable, and a description on what they do has been added to the header. But some tasks are still pending:
* Replace old string formatting with `%` by new with `.format()`
* Review which scripts are still in use or can be useful
* Review which of the ones to keep work as expected (there are connections to GitHub API that could change, some were implemented for Python 2, and probably haven't been reviewed much since then)
* Add them to the documentation about contributing to pandas
* Unify the ones that make sense (the ones that look for issues with docstrings for example, or the ones that build the release)

Next are the available scripts.

**Scripts for the release manager**
* announce.py :  Script to generate contributor and pull request lists
* build_dist_for_release.sh : This builds the release cleanly & is building on the current checkout
* build_dist.sh : Build the distribution

**Script to check the docstrings**
* api_rst_coverage.py : Script to generate a report with the coverage of the API in the docs
* find_undoc_args.py : Script that compares the signature arguments with the ones in the docsting and returns the differences

**Other tools for developers**
* convert_deps.py : Convert the conda environment.yaml to a pip requirements.txt
* find_commits_touching_func.py : Search the git history for all commits touching a named method
* list_future_warnings.sh : Check all future warnings in Python files, and report them with the version where the FutureWarning was added (useful to find deprecated functions and methods that were supposed to be removed)
* merge-pr.py : Utility for creating well-formed pull request merges and pushing them to Apache?

**Comment by jreback** [comment]
``merge-pr.py`` is the way we merge PR's when not using the web interface.

**Comment by bhaveshpoddar94** [comment]
Beginner Here. Do you want to add this to the Documentation? I can take this up.

**Comment by ProsperousHeart** [comment]
I would also like to help. @datapythonista ? how can we get started on this for you?

**Comment by ProsperousHeart** [comment]
This issue shows to be closed?

**Comment by datapythonista** [comment]
@ProsperousHeart this issue is still open. I think a good start is to add the scripts to the documentation. Feel free to do it the way you think it's better, and send a pull request, so it can be some discussion on your code.

**Comment by ProsperousHeart** [comment]
So just so I understand ... the bullet points are the needs, and the scripts are what the needs are to be applied to? I think that's what is being mentioned here. I'll work on this. ^_^ Thank you!

**Comment by ProsperousHeart** [comment]
Unable to locate files in 2nd list of docs ... and the 1st list of scripts don't seem to have the issues for docs, though I did find one issue I don't know how to resolve ...

author_msg doesn't exist [here](https://github.com/pandas-dev/pandas/blob/master/scripts/announce.py#L110)

**Comment by abi-aryan** [comment]
@datapythonista @ProsperousHeart is still an open issue?

**Comment by jbrockmendel** [comment]
@datapythonista same suggestion w/r/t checkboxes

**Comment by datapythonista** [comment]
Yep, I think it can make sense here. Not sure what's the status of this, but the scripts are now in the linting, so they are probably better than when the issue was created.

Will have a look at the state of this next week, and I'll add the checkboxes or I'll create new issues for the pending tasks, so we can move forward with this.

**Comment by datapythonista** [comment]
Superseded by #31038 and #31039
