### ISSUE TITLE
Timedelta +/- timedelta64[no-unit] assumes ns

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#19388]
A test failure that only showed up on appveyor: https://ci.appveyor.com/project/pandas-dev/pandas/build/1.0.9563/job/b47phinjg410eiap

```
pd.Timedelta(hours=2) - np.timedelta64('NaT')

>   __sub__ = _binary_op_method_timedeltalike(lambda x, y: x - y, '__sub__')
E   TypeError: Cannot cast ufunc subtract input from dtype('<m8') to dtype('<m8[ns]') with casting rule 'same_kind'
```

On OSX this goes through without a hitch:

```
>>> pd.Timedelta(hours=2) - np.timedelta64(2)
numpy.timedelta64(7199999999998,'ns')
```

In this case the appveyor is probably right to raise instead of assuming nanos.

**Comment by jreback** [comment]
the raise is exactly correct for a non-NaT value, we don't accept unit-less datetimelikes. So need to allow nulls  thru this check.

**Comment by jbrockmendel** [comment]
I think to fix this (without introducing new inconsistencies) we'd have to disallow passing a unit-less td64 object to pd.Timedelta, which I'm not sure we want to do
