### ISSUE TITLE
DOC: Code snippet renders incorrectly in the Registering Custom Accessors subsection of developer.rst

### ISSUE THREAD

**Issue by jschendel** [pandas-dev/pandas#19392]
The code snippet rendering in the [Registering Custom Accessors](https://pandas-docs.github.io/pandas-docs-travis/developer.html#registering-custom-accessors) subsection of `developer.rst` looks off to me.  The class definition is split across multiple inputs, resulting in the indentation being slightly off, and the decorators and `plot` method are hidden entirely.

Currently looks like this for me:

![developer.rst](https://i.imgur.com/zcwooTo.png)

Looking at the source, I think the intention is for it to look like the code snippet in the API reference, e.g. for [`pandas.api.extensions.register_dataframe_accessor`](https://pandas-docs.github.io/pandas-docs-travis/generated/pandas.api.extensions.register_dataframe_accessor.html):

![accessor_api](https://i.imgur.com/deZlgw3.png)

**Comment by TomAugspurger** [comment]
Strange. We could just change the `..ipython:: python` to `..code-block:: python`.

**Comment by jschendel** [comment]
xref #19400
