### ISSUE TITLE
to_clipboard excel defaults to "None", but doc string says "True"

### ISSUE THREAD

**Issue by lidderupk** [pandas-dev/pandas#19404]
#### Problem description
I just started using python/pandas a couple of months ago. So this might be a misunderstanding on my part. The excel argument to the to_clipboard function defaults to "None", but doc string says "True".  If this is a simple docstring change, I would like to contribute :) 

https://github.com/pandas-dev/pandas/blob/a00154dcfe5057cb3fd86653172e74b6893e337d/pandas/core/generic.py#L1566-L1589

#### Expected Output
The docstring should be `defaults to None`
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: None
pip: 9.0.1
setuptools: 38.4.0
Cython: None
numpy: 1.14.0
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by chris-b1** [comment]
I think default arg in the function signature could be changed to `True` - want to try a PR?

**Comment by lidderupk** [comment]
https://github.com/pandas-dev/pandas/pull/19425

Thank you @chris-b1. I tried to follow the guidelines as best I could.
