### ISSUE TITLE
Remove rebasing from contributing guide

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#19412]
If I'm not wrong, now GitHub squashes commits automatically when merging pull requests [1]. In the pandas documentation there is a section about combining commits [2], that doesn't seem relevant anymore if that is being used.

Would it make sense to delete that section, and may be add a comment about using the title of the pull request for the "right" commit message that will end up in the git history? 

1. https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits
2. https://pandas.pydata.org/pandas-docs/stable/contributing.html#combining-commits

**Comment by jorisvandenbossche** [comment]
Yes, we need to update that section.

We had a discussion somewhat related to this some time ago on the pandas-dev mailing list, see https://mail.python.org/pipermail/pandas-dev/2017-November/000632.html (I just replied to that thread as well). 
So I think the explanation how to squash can be removed (or at least mentioned in what cases it could be useful), and we should add explanation about how to update a feature branch with master without doing a rebase/squash.

**Comment by willingc** [comment]
Sorry folks. I didn't see that the other PR was open. Feel free to close #20190 or ask me to just resubmit the changes related to 'documentation contributions' (which are unrelated to this issue but was seen when scanning down the doc file).

**Comment by jorisvandenbossche** [comment]
I would just update your PR to only include the other changes
