### ISSUE TITLE
ENH: Have Period/PeriodIndex inherit from Interval/IntervalIndex

### ISSUE THREAD

**Issue by jschendel** [pandas-dev/pandas#19419]
Since `Period` objects are inherently intervals of time, it seems like there should be a way to access `Interval` properties and methods.  Inheritance has been suggested in passing in other issues, and seems reasonable.

As an example benefit, #9089 suggests implementing `Period.duration`.  If `Period` were to inherit from `Interval`, this would already be implemented via the `Interval.length` property:

```python
In [2]: p = pd.Period('2018Q1', freq='Q')

In [3]: p_iv = pd.Interval(p.start_time, (p + 1).start_time, closed='left')

In [4]: str(p_iv)
Out[4]: '[2018-01-01, 2018-04-01)'

In [5]: p_iv.length
Out[5]: Timedelta('90 days 00:00:00')
```

Likewise for `PeriodIndex` inheriting from `IntervalIndex`.  Would be nice to have cross compatibility between the two, e.g. `IntervalIndex.overlaps(Period)` or `PeriodIndex.get_loc(Interval)`.

**Comment by jreback** [comment]
there is an existing issue about making Period inherit from Interval (and same with PI and II)

it might not be bad

**Comment by jschendel** [comment]
@jreback : I recall seeing that mentioned somewhere, but can't find a corresponding issue.  Do you happen to know where it is?

Also, would adding this method still be worthwhile if inheritance is implemented?  Maybe if someone wanted to add a non-compatible `Interval` to a `PeriodIndex`, they'd need convert to `IntervalIndex` first?  Not sure how common/useful that would be.  Might just close this if there's no clear benefit to having this in addition to inheritance.

**Comment by jreback** [comment]
i couldn’t find the issue but iirc some disscussiom on the II original issue maybe 

yeah inheritance would be nice here 

can repurpose this issue

**Comment by jbrockmendel** [comment]
After some thought, I'm -1 on this.  Assuming the Interval in question would have endpoints that are themselves `Timestamp`s, this would limit the range of Period/PeriodIndex to the same bounds as Timestamp.  Representing distant-past/future times is a use case that right now can only be done with Periods.

**Comment by jbrockmendel** [comment]
Closing based on the argument above.  Feel free to re-open for further discussion.
