### ISSUE TITLE
Conventions for DataFrame.__eq__?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#19426]
`DataFrame.__eq__` and `DataFrame.eq` don't appear to do alignment-checking.  This is surprising.  Is this intentional:

```
ser = pd.Series([1, 2])
df = pd.DataFrame([[1, 2], [3, 4]], index=['A', 'B'], columns=['foo', 'bar'])
>>> df == ser
       0      1    bar    foo
A  False  False  False  False
B  False  False  False  False
```

I'll check for related issues shortly.

**Comment by jreback** [comment]
there is already an issue for this IIRC see if you can find it.
