### ISSUE TITLE
timedelta cannot convert to monthly data.

### ISSUE THREAD

**Issue by effath** [pandas-dev/pandas#19443]
Timedelta cannot convert x minute timesereies to  monthly series.  Each time I try to use it will upsample x minute data to 1 minute data.  See 

https://stackoverflow.com/questions/48467042/dask-dataframes-time-series-partitions

**Comment by chris-b1** [comment]
`Timedelta` is only for fixed offsets (seconds, days, etc), it can't and won't handle months - [`DateOffset`](https://pandas.pydata.org/pandas-docs/stable/timeseries.html#dateoffset-objects) and subclasses handle any relative offsets.

That said, I do see the potential for confusion given the dual use of `'M'`, would at minimum take doc enhancements, maybe OK with a warning for `pd.Timedelta('xM')`?

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/issues/16344

we are already deprecating this. pull-requests are welcome!
