### ISSUE TITLE
ENH Adding read_* support for Google Cloud Storage gs:// URLs

### ISSUE THREAD

**Issue by vision-sbm** [pandas-dev/pandas#19454]
Would be great if pandas were to support reading directly from Google Cloud Storage URLs (gs://), similar to the way it supports AWS s3 URLs (s3://)

Ideally, one could write:
```python
df_csv = pd.read_csv('gs://my-bucket/super-cool-dataset.csv')
df_excel = pd.read_excel('gs://my-bucket/super-cool-dataset.xlsx')

```

I took a quick stab at it in https://github.com/pandas-dev/pandas/commit/4c9196ace8e70f83f81d84d921a73db2581453a4. Let me know if this makes sense and I can add some documentation/tests around it and open a pull request.

**Comment by TomAugspurger** [comment]
@vision-sbm we're certainly open to this. Making a PR will be the best move as far as code review goes.

FWIW, I think having an optional dependency on [gcsfs](https://github.com/dask/gcsfs) and then mirroring https://github.com/pandas-dev/pandas/blob/master/pandas/io/s3.py is the easiest way.
