### ISSUE TITLE
Dataframe w/ DatetimeIndex memory leak

### ISSUE THREAD

**Issue by ace-e4s** [pandas-dev/pandas#19459]
#### Code Sample, a copy-pastable example if possible

```python
import gc
import numpy as np
import pandas as pd
from memory_profiler import profile


@profile
def leaky_af():
    channels = ['Sonya Blade', 'Johnny Cage', 'Raiden', 'Scorpion', 'Kano']

    data_df = pd.DataFrame()  # w/ default index
    for channel in channels:
        data = pd.Series(data=np.random.random(50000),
                         index=pd.DatetimeIndex(np.arange(0, 50000)))
        data_df[channel] = data

@profile
def tight():
    channels = ['Sonya Blade', 'Johny Cage', 'Raiden', 'Scorpion', 'Kano']

    data_df = pd.DataFrame(index=pd.DatetimeIndex([]))  # w/ DatetimeIndex
    for channel in channels:
        data = pd.Series(data=np.random.random(50000),
                         index=pd.DatetimeIndex(np.arange(0, 50000)))
        data_df[channel] = data


if __name__ == '__main__':
    for i in range(50):
        tight()
        # leaky_af()
        gc.collect()

```
#### Problem description

Memory seems to leak when adding new Series with DatetimeIndex columns to an empty DataFrame (which was initialized with default index). However, if the DataFrame is initialized with an empty DatetimeIndex index, the leakage stops.

##### Good
![pandas tight](https://user-images.githubusercontent.com/18338679/35561333-39e99430-05b0-11e8-8fb3-bd06f46a3ddd.png)

##### Leak
![pandas leaky_af](https://user-images.githubusercontent.com/18338679/35561335-3ce0feda-05b0-11e8-95c0-6c58504e8e85.png)

#### Output of ``pd.show_versions()``

pandas 0.22.0
python 2.7.14 (not tested in python 3)

</details>

**Comment by jreback** [comment]
these don't leak. the 'leaky_af' continually creates and destroys objects. When a new column is added to the frame, the original index is reindexed, which causes a copy, while in the first one it is simply set with the added index. Since python doesn't release the actual memory, your usage grows. 

subsequent indices are equal to the first so no reindexing happens.

xref https://github.com/pandas-dev/pandas/issues/6046

**Comment by ace-e4s** [comment]
@jreback maybe I'm missing something here but, note that the leaky_af function is ran in a loop inside the main function; for every increment in the loop, leaky_af is ran only once (which may trigger copying, and that's fine).  However, when data_df is re-created in the next increment, all references to the old one are gone, so Python should release them from the memory. Instead, you see a steady increase in memory usage.

**Comment by ace-e4s** [comment]
@jreback I don't want to be a nuisance, but I urge you to take a second look at this case. I have altered the sample  code and description to clarify the issue. Furthermore, the i did exactly what you suggest in xref #6046, and ran the code inside a loop. The memory used increases steadily for every increment.

Again, thank you for your time and effort! Love Pandas, and just want to contribute. Cheers :)

**Comment by TomAugspurger** [comment]
@ace-e4s can you try on Py3? Here's my plot w/ your leaky version.

![figure_1](https://user-images.githubusercontent.com/1312546/35744949-5664dda0-0807-11e8-8ad3-62fabd9fd3f4.png)

**Comment by jorisvandenbossche** [comment]
I did that as well a few days ago and got a similar plot as @TomAugspurger (forgot to comment about it).

But that said, there is something strange in those plots about the timings. I don't see why the 'leaky_af' version would be so *much* slower.

**Comment by jorisvandenbossche** [comment]
OK, apparently adding a column to empty frame with already the correct type of index is much faster:

```
In [54]: %%timeit
    ...: data_df = pd.DataFrame(index=pd.DatetimeIndex([]))
    ...: data_df['channel'] = data
    ...: 
1.93 ms ± 122 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [55]: %%timeit
    ...: data_df = pd.DataFrame()
    ...: data_df['channel'] = data
    ...: 
110 ms ± 1.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

and since you repeat that many times in the memory profiler, that's a reason for the one taking a lot more time (I find it still strange that it is such a big difference though)

**Comment by jorisvandenbossche** [comment]
> @jreback: When a new column is added to the frame, the original index is reindexed, which causes a copy

That doesn't seem to be the case though (at least not on python 3):

```
In [65]: data = pd.Series(data=np.random.random(50000), index=pd.DatetimeIndex(np.arange(0, 50000)))

In [66]: data_df = pd.DataFrame()

In [67]: data_df['channel'] = data

In [68]: data.index.base is data_df.index.base
Out[68]: True

In [71]: data.index.base[0] = 5

In [72]: data_df.index[:5]
Out[72]: 
DatetimeIndex(['1970-01-01 00:00:00.000000005',
               '1970-01-01 00:00:00.000000001',
               '1970-01-01 00:00:00.000000002',
               '1970-01-01 00:00:00.000000003',
               '1970-01-01 00:00:00.000000004'],
              dtype='datetime64[ns]', freq=None)
```

@ace-e4s can you try to run the same in python 2 to see if you see any difference?

**Comment by ace-e4s** [comment]
@TomAugspurger I tried to run it with Python 3.6 and got similar results as you; memory usage is comparable between leaky_af and tight, but tight runs much faster.

May this be a case of circular referencing somewhere, and Python 2 garbage collector is failing to collect? (If I'm not wrong, Python 3.4 improved significantly in that respect.)

#### Python 3.6 leaky_af()
![pandas leaky_af - py36](https://user-images.githubusercontent.com/18338679/35756803-ebec0c4e-086c-11e8-918f-63d9c8c7e930.png)

**Comment by TomAugspurger** [comment]
That seems most likely.

Since it's python 2 only, I suspect we would gladly take a patch fixing the
behavior you're seeing, but I personally don't have any plans to look into
it :)

**Comment by ace-e4s** [comment]
@jorisvandenbossche , yes same behavior in python 2.

**Comment by ace-e4s** [comment]
Although it the memory issue may be limited to Python 2, the poor performance may be a symptom of the same underlying issue.

**Comment by jorisvandenbossche** [comment]
Likewise as @TomAugspurger but regarding the poor performance which also affects python 3: we gladly take a patch to solve it, but it isn't the most pressing issue as this usage pattern is not a typical way to do things if you care about performance.
