### ISSUE TITLE
Precision error when using Timedelta.total_seconds method 

### ISSUE THREAD

**Issue by nvgoldin** [pandas-dev/pandas#19458]
#### Code Sample
```python
>>> import pandas as pd
>>> block = pd.Timedelta('30S')
>>> block.total_seconds()
30.000000000000004
>>> 

```
#### Problem description
When using `Timedelta.total_seconds` I sometime encounter a small precision error (1e-15), which can be significant in some scenarios (for instance when later dividing the results and expecting an integer). The workaround is to always use a rounding method, which makes the code cumbersome.

#### Expected Output
A float or integer representing the seconds precisely.

#### Output of ``pd.show_versions()``

<details>

>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-5-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: en_US.utf8
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.22.0
pytest: None
pip: 9.0.1
setuptools: 38.4.0
Cython: None
numpy: 1.14.0
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
we are doing this. 
```
In [9]: pd.Timedelta('30S').value * 1e-9
Out[9]: 30.000000000000004
```

this would avoid the issue
```
In [11]: pd.Timedelta('30S').value / 1e9
Out[11]: 30.0
```

look in ``pandas/_libs/tslibs/timedelta.pyx`` for the code

would take a PR for this.

**Comment by CruiseDevice** [comment]
I would like to work on this. I am new here. Can you please guide me?

**Comment by CruiseDevice** [comment]
From the path to the file you gave i found the function i need to modify.

**Comment by jreback** [comment]
http://pandas.pydata.org/pandas-docs/stable/contributing.html

**Comment by nvgoldin** [comment]
@jreback, thanks for the references - why is the ```pd.Timedelta('30S').value / 1e9``` an issue? How would you expect it to be solved for both issues?

@CruiseDevice - LMK if your not taking it. I'll try freeing some time for it.

**Comment by CruiseDevice** [comment]
@nvgoldin Creating development environment on my machine took time. I have one question though Do i have to create a new branch for this? or should i make changes directly to my branch and then create a PR?

**Comment by CruiseDevice** [comment]
I would like to spend sometime on this. If i am not able to do it you can happily take this. I will let you know.

**Comment by CruiseDevice** [comment]
#19477

**Comment by CruiseDevice** [comment]
`
        rng = Timedelta('30S')
        expt = 30.0
        tm.assert_almost_equal(rng.total_seconds(), expt)
`
I wrote something like this. Is this correct?

**Comment by CruiseDevice** [comment]
@nvgoldin Hey. If you want you can take this issue. I am busy on something else.

**Comment by nvgoldin** [comment]
thanks!
