### ISSUE TITLE
API/ENH: Allow Interval to be a first-class type via an IntervalBlock internal type

### ISSUE THREAD

**Issue by jschendel** [pandas-dev/pandas#19453]
This has been mentioned in passing in a few other issues, so making an official issue to document this.  In the same spirit as `PeriodBlock` (#7964).

I've started working on an interval accessor, so it seems likely that there will be more exposure to `Interval` objects in a `Series`/`DataFrame`, hence this becoming more relevant.

xref #19272

**Comment by TomAugspurger** [comment]
FYI I have a branch doing this on top of the extension array stuff. Will make a PR in a couple days.
