### ISSUE TITLE
BUG: .dt accessor raises on a Series of Categorical Timestamps with repeats

### ISSUE THREAD

**Issue by jschendel** [pandas-dev/pandas#19468]
#### Code Sample, a copy-pastable example if possible
On master:
```python
In [2]: pd.__version__
Out[2]: '0.23.0.dev0+190.g238499a'

In [3]: dti = pd.DatetimeIndex(['20171111', '20181212']).repeat(2)

In [4]: s = pd.Series(pd.Categorical(dti))

In [5]: s
Out[5]:
0   2017-11-11
1   2017-11-11
2   2018-12-12
3   2018-12-12
dtype: category
Categories (2, datetime64[ns]): [2017-11-11, 2018-12-12]

In [6]: s.dt.year
---------------------------------------------------------------------------
ValueError: Wrong number of items passed 4, placement implies 2
```

Note that this works on 0.22.0:
```python
In [2]: pd.__version__
Out[2]: '0.22.0'

In [3]: dti = pd.DatetimeIndex(['20171111', '20181212']).repeat(2)

In [4]: s = pd.Series(pd.Categorical(dti))

In [5]: s
Out[5]:
0   2017-11-11
1   2017-11-11
2   2018-12-12
3   2018-12-12
dtype: category
Categories (2, datetime64[ns]): [2017-11-11, 2018-12-12]

In [6]: s.dt.year
Out[6]:
0    2017
1    2017
2    2018
3    2018
dtype: int64
```
#### Problem description
Previously valid behavior now raises.

#### Expected Output
I'd expect the output on master to be the same as on 0.22.0.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: 238499ab0a48a0ad4a2011e2ce1c6a02c86124eb
python: 3.6.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.0.dev0+190.g238499a
pytest: 3.1.2
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.13.3
scipy: 1.0.0
pyarrow: 0.6.0
xarray: 0.9.6
IPython: 6.1.0
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: None
tables: 3.4.2
numexpr: 2.6.4
feather: 0.4.0
matplotlib: 2.0.2
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 0.9.8
lxml: 3.8.0
bs4: None
html5lib: 0.999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: 0.1.0
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
Most likely the extension accessor stuff. Looking into it now.
