### ISSUE TITLE
CI: pymysql 0.8.0 compat

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#19462]
revert this: https://github.com/pandas-dev/pandas/pull/19461

**Comment by jreback** [comment]
cc @jorisvandenbossche @TomAugspurger @gfyoung

**Comment by jorisvandenbossche** [comment]
So the failures are for the tests with procedures (`test_read_procedure`). Might be related to:

```
* **BACKWARD INCOMPATIBLE** ``MULTI_STATEMENTS`` client flag is no longer
  set by default, while it was on PyMySQL 0.7.  You need to pass
  ``client_flag=CLIENT.MULTI_STATEMENTS`` when you connect to explicitly
enable multi-statement mode. (#590)
```

from their changelog notes https://github.com/PyMySQL/PyMySQL/blob/master/CHANGELOG
