### ISSUE TITLE
Build no longer caching lib.pyx

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#19467]
I think this is a fairly recent phenomenon.  `setup.py build_ext --inplace` is now taking 40-60 seconds even if nothing has changed since the last run.  It looks like lib.pyx is getting re-cythonized on each run.

**Comment by jreback** [comment]
yes this seems very recent

**Comment by jbrockmendel** [comment]
Looks like it was introduced in #19306.

**Comment by jbrockmendel** [comment]
setup.lib_depends still has 'reduce' in it.  PR coming up to delete it, fixes this locally.
