### ISSUE TITLE
Disentangle ujson from _lib/src/datetime

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#19486]
There are some non-trivial simplifications (and perf improvements) in tslibs.np_datetime available if ujson can be made to not call pandas_datetimestruct methods directly.  Is there a viable way to make the ujson code go through the tslibs cython instead of through src/datetime?

**Comment by jbrockmendel** [comment]
@chris-b1 any idea how to do a c-equivalent of:

with tm.set_timezone(“UTC”):

?  If that can be done then I think I have a fix for this issue.

**Comment by WillAyd** [comment]
@jbrockmendel what's the upside of doing this? I think potentially possible if we use the public keyword:

http://docs.cython.org/en/latest/src/userguide/external_C_code.html#public-declarations

But not sure on what it buys us as we'd just be adding an extra layer in between JSON and the date time conversion routines

**Comment by jbrockmendel** [comment]
IIRC the motivations were

- if np_datetime only needed to handle use cases getting called from within tslibs, then most of the non-nano code could be ripped out.  I think there were some other simplifcations i had in mind, but dont remember them ATM.
- some hope that by eliminating the dependencies in setup.py we might speed up compilation and/or reduce the compiled size
