### ISSUE TITLE
Doc: Incorrect exmaples for 'GroupBy.apply' functon

### ISSUE THREAD

**Issue by ZhuBaohe** [pandas-dev/pandas#19485]
Example 1 and Example 2 are both incorrect  for  'GroupBy.apply' functon in   [document](https://pandas-docs.github.io/pandas-docs-travis/generated/pandas.core.groupby.GroupBy.apply.html).

```python
>>>  df = pd.DataFrame({'A': 'a a b'.split(), 'B': [1,2,3], 'C': [4,6, 5]})
>>>  g = df.groupby('A') 
```
The following changes should be made.

Example1
```python 
>>> g[['B','C']].apply(lambda x: x / x.sum())  
          B    C
0  0.333333  0.4
1  0.666667  0.6
2  1.000000  1.0
```
Example2
```python 
>>> g[['B','C']].apply(lambda x: x.max() - x.min()) 
   B  C
A      
a  1  2
b  0  0
```

**Comment by jorisvandenbossche** [comment]
@ZhuBaohe Thanks for the report! You are correct. It was recently already reported here: https://github.com/pandas-dev/pandas/issues/19337, so closing this issue.
