### ISSUE TITLE
SegFault when using `to_parquet` with `flavor='spark'` when dataframe contains timestamps

### ISSUE THREAD

**Issue by clembou** [pandas-dev/pandas#19493]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
from io import StringIO

content = StringIO(
"""report_time_of_generation
2018-02-01 03:44:29
2018-02-01 03:44:29
2018-02-01 03:44:29
2018-02-01 03:44:29
2018-02-01 03:44:29
""")

dfs = pd.read_csv(content, parse_dates=['report_time_of_generation'])

print('data:')
print(dfs)
print('dtypes:')
print(dfs.dtypes)

print('writing the file using raw pyarrow works')
table = pa.Table.from_pandas(dfs)
pq.write_table(table, 'pyarrowviatable.parquet', flavor='spark')

print('using df.to_parquet segfaults')
dfs.to_parquet('viapandas.parquet', flavor='spark')
```

result:
```
data:
  report_time_of_generation
0       2018-02-01 03:44:29
1       2018-02-01 03:44:29
2       2018-02-01 03:44:29
3       2018-02-01 03:44:29
4       2018-02-01 03:44:29
dtypes:
report_time_of_generation    datetime64[ns]
dtype: object
writing the file using raw pyarrow works
using df.to_parquet segfaults
[1]    28905 segmentation fault  ./venv/bin/ipython
```
#### Problem description

`dfs.to_parquet('viapandas.parquet', flavor='spark')`  gives me a segfault on macos and linux with pandas 0.22.0 and pyarrow v0.8.0 ( latest at the time of writing).

I am filing the issue in the pandas repo since i am not hitting the issue when creating the file manually using pyarrow directly.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Darwin
OS-release: 17.3.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.22.0
pytest: 3.4.0
pip: 9.0.1
setuptools: 38.4.0
Cython: None
numpy: 1.13.3
scipy: None
pyarrow: 0.8.0
xarray: None
IPython: 6.2.1
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: None
tables: None
numexpr: 2.6.4
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.5.1
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: 2.7.3.2 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: 0.1.3
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
FYI, this fails in a call to https://github.com/pandas-dev/pandas/blob/35812eaaecebeeee0ddf07dee4b583c4eea07785/pandas/io/parquet.py#L119, so the actual segfault is in pyarrow (or parquet-cpp, not sure).

cc @cpcloud thoughts? Anything pandas is doing wrong here?

**Comment by jorisvandenbossche** [comment]
@clembou when doing it manually with `pyarrow`, can you try passing `compression='snappy',
coerce_timestamps='ms'` to `write_table` ? Do you then get a segfault with pyarrow as well? 
That seems the only difference with the internal pandas implementation and your code.

**Comment by clembou** [comment]
Yep it crashes too:
```python
pq.write_table(table, 'pyarrowviatablewithpandasoptions.parquet', flavor='spark', compression='snappy', coerce_timestamps='ms')
```
gives me `[1]    48095 segmentation fault  ./venv/bin/ipython`

Do you want me to open an issue on pyarrow instead?

**Comment by clembou** [comment]
ok, filed as https://issues.apache.org/jira/browse/ARROW-2082.

**Comment by jorisvandenbossche** [comment]
Thanks!
