### ISSUE TITLE
Documation: copy documenation is lacking detail for when deep=False

### ISSUE THREAD

**Issue by charlie0389** [pandas-dev/pandas#19505]
The DataFrame.copy documentation (for pandas 0.22.0) states:

```
deep : boolean or string, default True
Make a deep copy, including a copy of the data and the indices. 
With deep=False neither the indices or the data are copied.
Note that when deep=True data is copied, actual python objects 
will not be copied recursively, only the reference to the object. 
This is in contrast to copy.deepcopy in the Standard Library,
which recursively copies object data.
```
#### Problem description

The documentation does not state what *is* copied when ``deep=False`` (it doesn't copy data, it doesn't copy indices, what does it copy then?).

Searching for 'copy' suggests this has not been reported as an issue.

**Comment by ZhuBaohe** [comment]
The reference of   the data is copied with deep=False.

```python
df=pd.DataFrame([1,2,3])

df1=df.copy(deep=False)

df1.iat[0,0]=100

df1.index=[10,20,30]

df1
Out[188]: 
      0
10  100
20    2
30    3

df
Out[189]: 
     0
0  100
1    2
2    3
```

**Comment by MIsmailKhan** [comment]
Hi, I'd be happy to take this up! 

Would this suffice?

"
deep : boolean or string, default True
Make a deep copy, including a copy of the data and the indices. **With ``deep=False``(i.e. shallow copy), the data reference is copied.** Neither the indices or data are copied.
Note that when deep=True data is copied, actual python objects 
will not be copied recursively, only the reference to the object. 
This is in contrast to copy.deepcopy in the Standard Library,
which recursively copies object data.
"

**Comment by charlie0389** [comment]
Ok, I'm a little confused. What does a copy of the reference to the object mean? Isn't this the same operation as tagging an object  with a variable? i.e. 
Isn't
```
df2 = df1
```
the same as
```
df2 = df1.copy(deep=False)
```
?
Obviously if I was right this would be a little redundant, so I assume I'm not. But I think the documentation could outline with an example of when  ``deep=False`` is useful.

**Comment by MIsmailKhan** [comment]
I think this should cover the question: 
https://stackoverflow.com/questions/46327494/python-pandas-dataframe-copydeep-false-vs-copydeep-true-vs

As for whether df2 = df1 and df2 =df1.copy(deep=False) are the same. I wrote up a couple of lines and checked what happened to the above if I modified the original database(i.e. df2). They both yielded the same output so I'm guessing that they are the same.

http://nbviewer.jupyter.org/gist/MIsmailKhan/b5e2534636e526d840c231cebcca5761

**Comment by charlie0389** [comment]
Thankyou MismailKhan for the link and the example, its a bit clearer to me now. Unfortunately, neither of the StackOverflow answers articulate the difference between ``copy()`` and ``copy(deep=False)`` like your notebook example does.

However, as you acknowledge, it's still not clear why a ``copy(deep=False)`` operation is useful. It seems to me that if you are still operating on the same object, it's rather pointless just making a second reference to it - why not just use the same reference if the end result is the same...?

**Comment by MIsmailKhan** [comment]
I've added some lines to reflect why we'd want to use .copy(deep==False),
this should clear things out.
https://gist.github.com/MIsmailKhan/be2f51d60e61d1f77b92889d94b9b176

**Comment by charlie0389** [comment]
Thanks MismailKhan - thankyou for clearing that up.

**Comment by eamag** [comment]
So can we close this issue?

**Comment by jorisvandenbossche** [comment]
This will be closed by https://github.com/pandas-dev/pandas/pull/20261
