### ISSUE TITLE
Such thing as a scalar Categorical?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#19523]
`core.ops` has a check `elif is_categorical_dtype(y) and not is_scalar(y):`.

AFAICT the only case with `is_categorical_dtype` that _is_ scalar is `"category"`.  Am I missing a non-trivial case?

**Comment by jreback** [comment]
this is prob not used any longer, the ``is_categorical_dtype`` is enough.

**Comment by jbrockmendel** [comment]
In the tests this gets hit by `df.dtypes == 'category'`

**Comment by jreback** [comment]
can u make a comment to that effect in the code and tests

**Comment by jbrockmendel** [comment]
Yah, planning to handle the categorical_dtype case in core.ops after pinning down the canonical behavior in #19513 and debugging #19524.
