### ISSUE TITLE
API: let min_count parameter have its default value set in pd.options

### ISSUE THREAD

**Issue by topper-123** [pandas-dev/pandas#19533]
Pandas 0.22 changed how pandas treats aggregation of emty values, so in several cases, pandas returns 0 now, instead of NaN as previously. Specifically, the aggregation methods gained a ``min_count`` parameter, that defaults to 0. The old behaviour can be re-established by setting ``min_count=1``. From the discussion it seems clear that both defaults of 0 and 1 have their merits, but the discussion settled on ``min_count=0`` as the default. (My own preference is default of 1, but that ship has sailed...).

So, I propose setting the default value in ``pd.options.mode.min_count`` rather than in the method signatures, so users can change this default package-wide. The default value will be unchanged, i.e. 0.

My own use case is other users giving my framework a function, which is passed on to a aggregation function. In the majority of the cases ``min_count=1`` is the more logical default, but users should not be needed to understand the differences. I could of course add the default of ``min_count=1`` to my own code, but it would be much simpler for me (and others who like the same default as me) if they could set the default by setting ``pd.options.mode.min_count=1`` instead, so I'm throwing it out there, to see if others agree...

**Comment by jreback** [comment]
this was explicitly rejected in the original issue
as it creates to much confusion

**Comment by TomAugspurger** [comment]
This was discussed and rejected earlier. I think most of us have grown a distaste for global variables that affect the output of computations.

I'd be happy to see an alternative method that is equivalent to `.sum(min_count=1)`. I think the main issue is finding a good name for that.
