### ISSUE TITLE
Rank Mixes np.nan with np.inf values

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#19538]
#### Code Sample, a copy-pastable example if possible

```python
In []: df = pd.DataFrame([1, np.nan, np.inf, -np.inf, 25])
In []: df.rank()
Out []:
     0
0  2.0
1  NaN
2  NaN
3  1.0
4  3.0

In []: df.rank(ascending=False)
Out []:
     0
0  3.0
1  NaN
2  1.0
3  NaN
4  2.0
```
#### Problem description

``np.inf`` or ``-np.inf`` gets grouped with ``np.nan`` in the rank operation, depending on which direction the ranking occurs in. Ideally, ``np.inf`` would be entirely separate from ``np.nan``.

**Comment by jreback** [comment]
see #6945 / #17903 this was just done in master, is this another case?

cc @peterpanmj

**Comment by WillAyd** [comment]
Interesting...from glancing at it I think the problem is that PR only updated the `rank_1d_` methods in algos. This makes it so you get the desired functionality from a `Series` object but not from a `DataFrame` or `GroupBy` object. There's also a bug with how it handles values in descending order, all of which are highlighted below

```python
In []: df[0].rank()  # this works
Out[]: 
0    2.0
1    NaN
2    4.0
3    1.0
4    3.0

In []: df[0].rank(ascending=False)  # handles na appropriately, but incorrectly sets np.inf and -np.inf to equal
Out[]: 
0    3.0
1    NaN
2    1.0
3    1.0
4    2.0

In []: df['key'] = ['foo'] * 5
In []: df.groupby('key').rank()  # doesn't handle missing values appropriately
Out[]: 
     0
0  2.0
1  NaN
2  NaN
3  1.0
4  3.0
```

**Comment by peterpanmj** [comment]
It is the same issue as #6945. And, it seems that #17903 does not completely fix it when ascending is False. I will have a look into it.
Group by nan values is another thing .
```
In []: df['key'] = ['foo'] * 5
In []: df.groupby('key').rank()  # doesn't handle missing values appropriately
Out[]: 
     0
0  2.0
1  NaN
2  NaN
3  1.0
4  3.0
```
It should related to #3729

**Comment by WillAyd** [comment]
@peterpanmj whatever solution you come up with in `algos` it shouldn't be that different to move to the `groupby_helper.pyx.in` file to support GroupBy nan handling as well (I'm touching the latter in #19481). Ideally these would be consistent
