### ISSUE TITLE
CLN: Returned dtype of `_get_cython_function` unused

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#19557]
Minor code cleanup opportunity here. `_get_cython_function` in `core/groupby` returns a tuple containing a function and a `dtype_str`. While the latter is unpacked, it never appears to be used in code that calls it.

https://github.com/pandas-dev/pandas/blob/93c86aa13e1b7816c762b4ff372aef80a7830af8/pandas/core/groupby.py#L2243

As an alternate to removing it, it may serve some purpose if the below line is refactored to use it rather than creating its own local variable, but unless there's some other purposes I'd still just suggest cleaning up the `_get_cython_function` itself

https://github.com/pandas-dev/pandas/blob/93c86aa13e1b7816c762b4ff372aef80a7830af8/pandas/core/groupby.py#L2318

**Comment by jreback** [comment]
cleaning welcome! yeah the dtype_str is prob not needed
