### ISSUE TITLE
SparseDatafreme to_coo AttributeError

### ISSUE THREAD

**Issue by niknoproblems** [pandas-dev/pandas#19567]
#### Code Sample, a copy-pastable example if possible

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-379d3130de40> in <module>()
----> 1 df.to_coo()

~/anaconda3/lib/python3.6/site-packages/pandas/core/sparse/frame.py in to_coo(self)
    252         cols, rows, datas = [], [], []
    253         for col, name in enumerate(self):
--> 254             s = self[name]
    255             row = s.sp_index.to_int_index().indices
    256             cols.append(np.repeat(col, len(row)))

~/anaconda3/lib/python3.6/site-packages/pandas/core/sparse/frame.py in __getitem__(self, key)
    430             return self._getitem_array(key)
    431         else:
--> 432             return self._get_item_cache(key)
    433 
    434     def get_value(self, index, col, takeable=False):

~/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py in _get_item_cache(self, item)
   1841         if res is None:
   1842             values = self._data.get(item)
-> 1843             res = self._box_item_values(item, values)
   1844             cache[item] = res
   1845             res._set_as_cached(item, self)

~/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py in _box_item_values(self, key, values)
   2494         items = self.columns[self.columns.get_loc(key)]
   2495         if values.ndim == 2:
-> 2496             return self._constructor(values.T, columns=items, index=self.index)
   2497         else:
   2498             return self._box_col_values(values, items)

AttributeError: 'BlockManager' object has no attribute 'T'



```
#### Problem description

I tried convert Dataframe to sparse matrix and got this error

#### Expected Output
coo_matrix

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Darwin
OS-release: 17.3.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: ru_RU.UTF-8
LOCALE: ru_RU.UTF-8

pandas: 0.22.0
pytest: 3.2.1
pip: 9.0.1
setuptools: 38.4.0
Cython: 0.27.1
numpy: 1.14.0
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.2.0
xlsxwriter: 1.0.2
lxml: 4.1.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: 0.1.3
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
Can you provide a reproducible example for constructing `df`?
