### ISSUE TITLE
alias for slice(None)

### ISSUE THREAD

**Issue by denfromufa** [pandas-dev/pandas#19578]
Having bunch of `slice(None)` in multilevel indexes (>=3 levels) looks pretty unreadable.

Does it make sense to have an alias, maybe `pd.any`?

For example in numpy the `np.newaxis` is alias for `None`:

https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html#numpy.newaxis

**Comment by maxim-lian** [comment]
Have you checked out `pd.IndexSlice`?

**Comment by jreback** [comment]
this is fully documented here: http://pandas.pydata.org/pandas-docs/stable/advanced.html#using-slicers

**Comment by denfromufa** [comment]
I was not aware about IndexSlice! Thanks for the tip.
