### ISSUE TITLE
Pickle Compat Update

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#19581]
How far back do we want to continue supporting? It looks like we have some pickle files form 0.10.1?

Should identify some potential cleanups that we'd get from dropping various versions.

**Comment by jreback** [comment]
we only guarantee back thru 0.13 i think
we dropped in 0.21 iirc

should for sure remove any ones older than that from tests

**Comment by mroeschke** [comment]
Looks like older pickle files have been cleaned out. I see we're testing the following pickle files now

```
categorical.0.25.0.pickle
sparseframe-0.20.3.pickle.gz
sparseseries-0.20.3.pickle.gz
test_mi_py27.pkl
test_py27.pkl
```

We can reopen this issue when it's time to bump those files
