### ISSUE TITLE
non-64-bit Indexes?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#19609]
```
ser = pd.Series(np.arange(10, dtype=np.float128))
>>> ser.dtype
dtype('float128')

>>> pd.Index(ser).dtype
dtype('float64')
```

This makes dispatching Series ops for non-64 dtypes problematic.  Is there a reason for enforcing only-64?

**Comment by jreback** [comment]
we don’t support this as it’s somewhat platform dependent

**Comment by jreback** [comment]
not necessarily objecting, but this would be tremendous work for very little gain.

**Comment by toobaz** [comment]
See #16404
