### ISSUE TITLE
Add ExtesnsionDtype.empty classmethod

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#19600]
This would let us provide a default `construct_from_string` method.

> It seems we could have a default implementation for ExtensionDtype.construct_from_string ? (I now just copy pasted from the decimal example, and I think json example also has the same basic one)

The default would have to rely on `ExtensionDtype()` being constructable with no arguments, or an `ExtensionDtype.empty` method. For many that'll be

```python
@classmethod
def empty(cls):
    return cls()
```

which is easier than implementing `construct_from_string`. Maybe call it `from_empty`.

**Comment by jorisvandenbossche** [comment]
> The default would have to rely on ExtensionDtype() being constructable with no arguments

Why not just rely on that assumption directly for a default implementation of `construct_from_string` ? 
The we don't need a new method?

**Comment by TomAugspurger** [comment]
So if a class doesn't support `ExtensionDtype()` called with no arguments, we'll get an exception either way. My hope was that implementing `.empty` / `.from_empty` is easier than implementing `.construct_from_string`.
I suppose we get an exception either way...

**Comment by jreback** [comment]
EA should have this method
maybe make dtype required?

**Comment by jorisvandenbossche** [comment]
What has this to do with ExtensionArray itself ?

**Comment by jreback** [comment]
sorry thought the top was on empty on EA
