### ISSUE TITLE
Adding Non-US holidays in pandas.tseries.holiday

### ISSUE THREAD

**Issue by cjer** [pandas-dev/pandas#19615]
`pandas.tseries.holiday` has built-in only US holiday calendars. Is it possible to add other countries' holiday calendars to it? This US-centric module seems weird. 

Maybe add [holidays](https://pypi.python.org/pypi/holidays) module, so this is not hard-coded and maintained within pandas.

I could make a pull request for this if it sounds reasonable.

**Comment by jreback** [comment]
The point of the holidays is to be subclassed, this is only a sample implementation. see also #7070. things like this should live in an external package. they would need there own update frequency and maintainers.
