### ISSUE TITLE
[Feature Request]: df.plot(type='pca')

### ISSUE THREAD

**Issue by zfrenchee** [pandas-dev/pandas#19648]
Would a PCA macro be out of scope for pandas? 

Each time I want to generate a PCA plot to look at data in my dataframes, I go and find the little PCA snippet I use everywhere, which is rather verbose: 
```
pca = PCA(n_components=2)
Y = pca.fit_transform(StandardScaler().fit_transform(df))

with plt.style.context('seaborn-whitegrid'):
    for label, color in zip(("HC", "SLE"), ("blue", "red")):
        plt.scatter(Y[y==label, 0], Y[y==label,1], label=label, c=color) 
        
    plt.xlabel('Principal Component 1')
    plt.ylabel('Principal Component 2')
    plt.legend(loc='upper right',prop={'size':16})
    plt.tight_layout()
    print(''.join(['PC '+str(i+1)+': '+str(var*100)[:4]+'%   ' for i, var in enumerate(pca.explained_variance_ratio_)]))
    plt.show()
```
Imagine if instead I could do: 
```
df.plot.pca(colors='index')
```

If there exists a PCA python package which is intended for this use case -- a macro for doing PCA on pandas dataframes, then I'd love to know about it! (and we can probably close this issue) 

But otherwise, I think this might be a nice feature to add directly to pandas. However, I can imagine this is something of a slippery slope for adding more and more arbitrary visualization tools... If we feel too dangerous to risk I guess I can keep copy-pasting my little snippet everywhere...

(xref #19008)

**Comment by jreback** [comment]
out of scope

**Comment by jorisvandenbossche** [comment]
I agree this would be out of scope.
