### ISSUE TITLE
pandas.read_csv tries to convert "NaN" even when specifying dtype argument

### ISSUE THREAD

**Issue by jamesqo** [pandas-dev/pandas#19644]
#### Code Sample, a copy-pastable example if possible

```python
from pandas.compat import StringIO
import pandas as pd

t1 = """float
1
"""
t2 = """float
NaN
"""

for t in t1, t2:
    df = pd.read_csv(StringIO(t), dtype={'float': 'str'})
    print(type(df['float'][0]))
```
#### Problem description

Even when explicitly specifying `dtype` above, `read_csv` still converts values in the `float` column to a float when the string is "NaN". This behavior appears to be limited to "NaN" as it doesn't happen for regular numbers. Still, I unexpectedly ran across a "NaN" string in my application so it's blocking me.

**Comment by gfyoung** [comment]
So at the surface, `pandas` is actually respecting your wishes, as the `dtype` of the column is `object`.  However, it just so happens that the element contained in that column is not converted to a `str`.  That being said, I think it should convert to a string (the `NaN` itself).  PR to patch is welcome!

**Comment by gilbertoolimpio** [comment]
@gfyoung A newbie here! I would like to help with this problem! Any tips on where to start?

**Comment by gfyoung** [comment]
@gilbertoolimpio : Thanks for volunteering!  So `read_csv` is a somewhat tricky / convoluted function, but it's do-able to understand once you've worked with for long enough.

Head over to `parsers.pyx`.  That's where the bulk of the processing for the C engine is done.  Look at the `_read_rows` method.  There, you should be able to trace when we have finished reading the data and when we begin to transform data types of columns.

**Comment by gilbertoolimpio** [comment]
Ok @gfyoung! Thanks!

**Comment by gilbertoolimpio** [comment]
@jamesqo and @gfyoung the expected result would be <class 'str'> <class 'str'> and not <class 'str'> <class 'float'> ok?

**Comment by gfyoung** [comment]
Yes, that's correct!

**Comment by gilbertoolimpio** [comment]
@gfyoung and @jamesqo
Hello guys, researching on the NaN issue, in its specification says that it is treated as Float, so the behavior would be correct. However analyzing I found the following solution:

```python
from pandas.compat import StringIO
import pandas as pd

t1 = """float
1
"""
t2 = """float
NaN
"""

for t in t1, t2:
    df = pd.read_csv (StringIO (t)). astype (str)
    print(type(df['float'][0]))


```
Would that solve the problem?

**Comment by gilbertoolimpio** [comment]
for now you may want to use the solution below while not finding a solution. 
```python
df = pd.read_csv(StringIO(t), dtype={'float': 'str'}, engine='python')
```

I'm having trouble debugging the files pulls, could you give me a hint?

**Comment by gfyoung** [comment]
Debugging the files pulls?  What do you mean by that?

**Comment by gilbertoolimpio** [comment]
@gfyoung I'm sorry, I meant `pyx`, my spell-checker, made me fail!

**Comment by gfyoung** [comment]
@gilbertoolimpio : Hahaha, got it.  Debugging `pyx` files is kind of annoying, so I generally just add a ton of `print` statements wherever I can.

**Comment by jreback** [comment]
this is a duplicate of #15669 which needs discussion.

**Comment by jreback** [comment]
since NaN *are* by definition the missing value marker this is correct. you can comment on #15669 if you would like.

**Comment by jamesqo** [comment]
@jreback The value isn't missing, it's the string `"NaN"`.

**Comment by gfyoung** [comment]
If you read the first part of the issue in #15669, I can see why it's considered a duplicate.
