### ISSUE TITLE
DOC: Sphinx 1.7 compatability

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#19656]
I thought I posted this when the beta was out, but apparently not. We have a bit of work to do.

- [ ] Remove vendored IPython sphinxext (should be OK with https://github.com/ipython/ipython/pull/10907 released)
- [ ] Remove vendored numpydoc (work around https://github.com/numpy/numpydoc/pull/106#issuecomment-343220139)
- [ ] Check performance (better than 1.6, but still slower? https://github.com/sphinx-doc/sphinx/issues/4230)
- [ ] ...

**Comment by jorisvandenbossche** [comment]
I think most discussion is in https://github.com/pandas-dev/pandas/issues/18147 ?

**Comment by TomAugspurger** [comment]
Ah, indeed. Maybe that's why I didn't make a new issue earlier :)
