### ISSUE TITLE
CLN: Remove uses of Index._data

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#19658]
The type of `Index._data` is inconsistent across Index subclasses

class             | output
----------------- | ------
Index             | ndarray
PeriodIndex       | ndarray[int] (ordinals)
DatetimeIndex     | DatetimeIndex (?)
DatetimeIndex[tz] | ndarray[datetime64[ns]]
CategoricalIndex  | Categorical
IntervalIndex     | None

We should replace uses of `._data` with `._values` or `._ndarray_values`, which have more consistent behavior.

I don't think we can remove `._data` entirely though. It's used for quickly setting values in some places. Haven't looked too closely though.

**Comment by jorisvandenbossche** [comment]
I suppose that, once we have Array classes for all our own extension types, those `_data` attributes *in principle* (with some refactoring to get there) should be those arrays? And then, it should be the same as `_values`

**Comment by jbrockmendel** [comment]
actionable/closeable?  Now that we use _mgr instead of _data for BlockManager, foo._data is much less ambiguous

**Comment by mroeschke** [comment]
Agreed, the use of `_mgr` should make this more consistent now. Closing but happy to reopen if that's not the case
