### ISSUE TITLE
Ambiguous description in pandas.DataFrame.to_parquet documentation

### ISSUE THREAD

**Issue by pmlandwehr** [pandas-dev/pandas#19662]
#### Relevant Docstring

In the verson 0.22.0 [pandas.DataFrame.to_parquet documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_parquet.html), the **engine** kwarg is described as:
>"Parquet reader library to use. If ‘auto’, then the option ‘io.parquet.engine’ is used. If ‘auto’, then the first library to be installed is used."

The two descriptions of "auto" are in conflict, so the one that isn't correct should be removed.

**Comment by TomAugspurger** [comment]
Agreed that it's unclear, but they aren't in conflict. That's explaining the implementation more than the behavior.

This should read

    Parquet library to use. If 'auto', the value from ``io.parquet.engine`` is used. The
    default ``io.parquet.engine`` behavior is to try 'pyarrow', falling back to 'fastparquet' if
    'pyarrow' is unavailable.

PRs welcome!

**Comment by gilbertoolimpio** [comment]
I'll do this!
