### ISSUE TITLE
remove_unused_levels() mixes labels of a dataframe index

### ISSUE THREAD

**Issue by oakca** [pandas-dev/pandas#19665]

**Comment by TomAugspurger** [comment]
Can you say what exactly is incorrect? Using your `m.transmission.index`, I think everything looks OK

```python
In [40]: tm.assert_index_equal(idx1, idx1.remove_unused_levels())

In [41]: pd.Series(1, idx1)
Out[41]:
Site In  Site Out  Transmission  Commodity
BB       BE        hvac          Elec         1
BE       BB        hvac          Elec         1
         RP        hvac          Elec         1
         SH        hvac          Elec         1
RP       BE        hvac          Elec         1
SH       BE        hvac          Elec         1
dtype: int64

In [42]: pd.Series(1, idx1.remove_unused_levels())
Out[42]:
Site In  Site Out  Transmission  Commodity
BB       BE        hvac          Elec         1
BE       BB        hvac          Elec         1
         RP        hvac          Elec         1
         SH        hvac          Elec         1
RP       BE        hvac          Elec         1
SH       BE        hvac          Elec         1
dtype: int64

```

**Comment by oakca** [comment]
check this for more info https://stackoverflow.com/questions/48750866/pyomo-set-initiated-with-filtered-pandas-dataframe-error

**Comment by TomAugspurger** [comment]
Can you copy over the relevant information here?

**Comment by oakca** [comment]
After that I checked the `m.transmission` `(site = BE)` and it looks like this:

    >m.transmission

                                             eff  inv-cost  fix-cost  var-cost  
    Site In Site Out Transmission Commodity
    BB      BE       hvac         Elec       0.9   1650000     16500         0
    BE      BB       hvac         Elec       0.9   1650000     16500         0
            RP       hvac         Elec       0.9   1650000     16500         0
            SH       hvac         Elec       0.9   1650000     16500         0
    RP      BE       hvac         Elec       0.9   1650000     16500         0
    SH      BE       hvac         Elec       0.9   1650000     16500         0


Then I had to initialize a Pyomo Set with this data-frame with:

    m.tra_tuples = pyomo.Set(
        within=m.sit*m.sit*m.tra*m.com,
        initialize=m.transmission.index.remove_unused_levels(),
        doc='Combinations of possible transmissions, e.g. '
            '(South,Mid,hvac,Elec)')

I used `.remove_unused_levels()` because otherwise it normally gets other data frame levels(the ones which are removed after filtering with `.loc[]`) as init of the `m.tra_tuples` set.

But problem starts after this point, since `m.tra_tuples` has different values than expected.

    tra_tuples : Combinations of possible transmissions, e.g. (South,Mid,hvac,Elec)
                Dim=0, Dimen=4, Size=6, Domain=tra_tuples_domain, Ordered=False, Bounds=None
                [('BB', 'BB', 'hvac', 'Elec'), 
                 ('BE', 'BE', 'hvac', 'Elec'), 
                 ('BE', 'RP', 'hvac', 'Elec'), 
                 ('BE', 'SH', 'hvac', 'Elec'), 
                 ('RP', 'BB', 'hvac', 'Elec'), 
                 ('SH', 'BB', 'hvac', 'Elec')]

I don't understand why `m.tra_tuples` is not indexed like this:
  
    m.sit   m.sit    m.tra        m.com
    BB      BE       hvac         Elec
    BE      BB       hvac         Elec
            RP       hvac         Elec
            SH       hvac         Elec
    RP      BE       hvac         Elec
    SH      BE       hvac         Elec

instead I am getting `BB-BB` or `BE-BE`, etc... What I am doing wrong?

**EXPECTED OUTPUT**

    tra_tuples : Combinations of possible transmissions, e.g. (South,Mid,hvac,Elec)
                Dim=0, Dimen=4, Size=6, Domain=tra_tuples_domain, Ordered=False, Bounds=None
                [('BB', 'BE', 'hvac', 'Elec'), 
                 ('BE', 'BB', 'hvac', 'Elec'), 
                 ('BE', 'RP', 'hvac', 'Elec'), 
                 ('BE', 'SH', 'hvac', 'Elec'), 
                 ('RP', 'BE', 'hvac', 'Elec'), 
                 ('SH', 'BE', 'hvac', 'Elec')]

**Comment by oakca** [comment]
basically it tries to initialize a pyomo set, but if you use `remove_unused_levels() ` it initializes wrong, because the labels are broken after the `remove_unused_levels() `.

**Comment by TomAugspurger** [comment]
I'm not sure what pyomo is. Could you 

1. make a minimal reproducible example (it probably doesn't need any dependencies other than pandas), or
2. answer what about https://github.com/pandas-dev/pandas/issues/19665#issuecomment-365043078 looks wrong?

**Comment by oakca** [comment]
I don't know really where the index labels are used, other than pyomo initialitions. There is nothing wrong with your example, but what you are not checking is following:

    (Pdb) m.transmission.index
    MultiIndex(levels=[['BB', 'BE', 'BW', 'BY', 'HB', 'HE', 'HH', 'MV', 'NI', 'NW', 'OFF', 'RP', 'SH', 'SL', 'SN', 'ST', 'TH'], ['BB', 'BE', 'BW', 'BY', 'HB', 'HE', 'HH', 'MV', 'NI', 'NW', 'OFF', 'RP', 'SH', 'SL', 'SN', 'ST', 'TH'], ['hvac'], ['Elec']],
               labels=[[0, 1, 1, 1, 11, 12], [1, 0, 11, 12, 1, 1], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]],
               names=['Site In', 'Site Out', 'Transmission', 'Commodity'])

LEVELS:     
1st [**'BB'**, 'BE', 'BW', 'BY', 'HB', 'HE', 'HH', 'MV', 'NI', 'NW', 'OFF', 'RP', 'SH', 'SL', 'SN', 'ST', 'TH']      
2nd ['BB', **'BE'**, 'BW', 'BY', 'HB', 'HE', 'HH', 'MV', 'NI', 'NW', 'OFF', 'RP', 'SH', 'SL', 'SN', 'ST', 'TH']      
3rd [**'hvac**']     
4th [**'Elec'**]   

LABELS:
1st [**0**, 1, 1, 1, 11, 12]      
2nd [**1**, 0, 11, 12, 1, 1]       
3rd [**0**, 0, 0, 0, 0, 0] 
4th [**0**, 0, 0, 0, 0, 0]     

So first element of this pyomo set will be `BB-BE-hvac-Elec`, but after `remove_unused_levels()`, not-used levels are removed, but also labels are broken; so that I don't get `BB-BE-hvac-Elec` anymore.

SEE:

    (Pdb) m.transmission.index.remove_unused_levels()
    MultiIndex(levels=[['BB', 'BE', 'RP', 'SH'], ['BE', 'BB', 'RP', 'SH'], ['hvac'], ['Elec']],
               labels=[[0, 1, 1, 1, 2, 3], [1, 0, 2, 3, 1, 1], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]],
               names=['Site In', 'Site Out', 'Transmission', 'Commodity'])

[**'BB'**, 'BE', 'RP', 'SH']
['BE', **'BB'**, 'RP', 'SH'] 
[**'hvac'**] 
[**'Elec'**]

[**0**, 1, 1, 1, 2, 3]
[**1**, 0, 2, 3, 1, 1]
[**0**, 0, 0, 0, 0, 0]
[**0**, 0, 0, 0, 0, 0]

`BB-BB-hvac-Elec`

**Comment by TomAugspurger** [comment]
Could you post your pandas version and make a reproducible example, including DataFrame generation, like we ask in the template? Otherwise there's no way we can help you.

**Comment by oakca** [comment]
To be honest, I am reporting an issue, and not looking for help. It is up to you to decide, if it is worth it to spend time on. 

What I am saying is basically, the order of the labels and levels are breaking after `remove_unused_levels()`  is used on a dataframe, which is generated by filtering with `.loc[]` (see code above), and this causes issues when some other python lib item tries to use labels and levels to generate an object.

If you wanna reproducible example, you can try to generate a data frame, then generate another dataframe with filtering the previous dataframe via `.loc[]` (see code above).

After this you need to check if the `old.df.index` is equal to `filtered.df.index`

then use `remove_unused_levels()` on `filtered.df` and then compare it's index with the old `filtered.df.index`

The levels should be gone, but the labels would be mixed.

I got `pandas                    0.22.0           py36h6538335_0    anaconda`

**Comment by TomAugspurger** [comment]
OK, let us know if you can make a reproducible example, including dataframe
generation, that demonstrates the failure.
