### ISSUE TITLE
Unused util

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#19676]
util._doctools.TablePlotter is used only in it's own `__main__` block.  Does that need to exist?

_decorators.docstring_wrapper is unused.

**Comment by WillAyd** [comment]
It does appear that this is used in `merging.rst`. That said, do we have any tools to analyze and clean up unused code? Wonder if something like [vulture](https://github.com/jendrikseipp/vulture) is worth exploring for pandas

**Comment by jreback** [comment]
we mostly just use linting

but adding a cleanup tool (to be run in the ci) would be great!

**Comment by WillAyd** [comment]
I'll open a separate change for that. Running `vulture pandas --exclude pandas/tests` from the top level directory yields 469 items, and I imagine there has to be some false positives in there. 

If someone goes through the modules called out by the tool and can learn in more detail how the tool works it appears to be something that can get integrated with CI
