### ISSUE TITLE
formatting date with strict json

### ISSUE THREAD

**Issue by mbj047** [pandas-dev/pandas#19688]
```python
#!/usr/bin/python

import pandas as pd
import json

master_df = pd.read_csv('sg_main__test.txt', parse_dates={'$date' :['date', 'time']}, sep='\s+', encoding='utf-8')

out_file = master_df.to_json('sg_main__test.json', date_format='iso', orient='records')
```
#### Problem description

I need my data set to export to - "Timestamp" : {$date:"2018-02-12T01:50:37.000Z"} Currently its exporting as - {"$date":"2011-07-22T20:34:51.000Z"

From my digging this isn't currently possible?

**Comment by TomAugspurger** [comment]
Can you make a reproducible example? I don't think you need to read from a CSV to demonstrate `to_json`, you can just create the dataframe directly.

**Comment by mbj047** [comment]
So this is the original file sample. Which is just a log file. I just need to convert this to json with the date change.

`date time time-taken c-ip cs-username cs-auth-group x-exception-id sc-filter-result cs-categories cs(Referer) sc-status s-action cs-method rs(Content-Type) cs-uri-scheme cs-host cs-uri-port cs-uri-path cs-uri-query cs-uri-extension cs(User-Agent) s-ip sc-bytes cs-bytes x-virus-id
2011-07-22 20:34:51 282 ce6de14af68ce198 - - - OBSERVED "unavailable" http://www.surfjunky.com/members/sj-a.php?r=44864  200 TCP_NC_MISS GET text/html http www.surfjunky.com 80 /members/sj-a.php ?r=66556 php "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.696.65 Safari/534.24" 82.137.200.42 1395 663 -
2011-07-22 20:34:51 216 6154d919f8d56690 - - - OBSERVED "unavailable" http://x31.iloveim.com/build_3.9.2.1/comet.html  200 TCP_NC_MISS GET text/html;charset=UTF-8 http x31.iloveim.com 80 /servlets/events ?1122064400327 - "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2.18) Gecko/20110614 Firefox/3.6.18" 82.137.200.42 473 1129 -
2011-07-22 20:34:51 307 6d98469a3f1de6f4 - - - OBSERVED "unavailable" http://www.xnxx.com/  200 TCP_MISS GET image/jpeg http img100.xvideos.com 80 /videos/thumbsl/2/e/5/2e5fd679f1118757314fb9a94c0f626c.25.jpg - jpg "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.2; .NET4.0C)" 82.137.200.42 16188 415 -
2011-07-22 20:34:51 315 6d98469a3f1de6f4 - - - OBSERVED "unavailable" http://www.xnxx.com/  200 TCP_MISS GET image/jpeg http img100.xvideos.com 80 /videos/thumbsl/6/7/3/673aa65e4e891c1be0d21eac643222f1.23.jpg - jpg "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.2; .NET4.0C)" 82.137.200.42 12104 415 -`

This is the output -

`[{"$date":"2011-07-22T20:34:51.000Z","time-taken":282,"c-ip":"ce6de14af68ce198","cs-username":"-","cs-auth-group":"-","x-exception-id":"-","sc-filter-result":"OBSERVED","cs-categories":"unavailable","cs(Referer)":"http:\/\/www.surfjunky.com\/members\/sj-a.php?r=44864","sc-status":200,"s-action":"TCP_NC_MISS","cs-method":"GET","rs(Content-Type)":"text\/html","cs-uri-scheme":"http","cs-host":"www.surfjunky.com","cs-uri-port":80,"cs-uri-path":"\/members\/sj-a.php","cs-uri-query":"?r=66556","cs-uri-extension":"php","cs(User-Agent)":"Mozilla\/5.0 (Windows NT 6.1; WOW64) AppleWebKit\/534.24 (KHTML, like Gecko) Chrome\/11.0.696.65 Safari\/534.24","s-ip":"82.137.200.42","sc-bytes":1395,"cs-bytes":663,"x-virus-id":"-"},{"$date":"2011-07-22T20:34:51.000Z","time-taken":216,"c-ip":"6154d919f8d56690","cs-username":"-","cs-auth-group":"-","x-exception-id":"-","sc-filter-result":"OBSERVED","cs-categories":"unavailable","cs(Referer)":"http:\/\/x31.iloveim.com\/build_3.9.2.1\/comet.html","sc-status":200,"s-action":"TCP_NC_MISS","cs-method":"GET","rs(Content-Type)":"text\/html;charset=UTF-8","cs-uri-scheme":"http","cs-host":"x31.iloveim.com","cs-uri-port":80,"cs-uri-path":"\/servlets\/events","cs-uri-query":"?1122064400327","cs-uri-extension":"-","cs(User-Agent)":"Mozilla\/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2.18) Gecko\/20110614 Firefox\/3.6.18","s-ip":"82.137.200.42","sc-bytes":473,"cs-bytes":1129,"x-virus-id":"-"},`

But I need "$date":"2011-07-22T20:34:51.000Z"  to export to "Timestamp" : {$date:"2018-02-12T01:50:37.000Z"} for every iteration.

**Comment by TomAugspurger** [comment]
Can you make your example minimal? IOW, just construct the smallest
possible example that demonstrates the issue. You shouldn't need to read
from an external file.

**Comment by mbj047** [comment]
But that's where my data is coming from. I have a large data set in a weird log format that I am pulling in to Pandas to convert to json. 
In the very simplest form this is what I got...
`"$date":"2011-07-22T20:34:51.000Z",`

this is what I need

`"Whatever": {"$date": "2011-07-22T20:34:51.000Z"},`

and I'd I need to do it like a few million times

**Comment by jorisvandenbossche** [comment]
> But that's where my data is coming from.

For `to_json` (which is the function you have an issue with) it doesn't matter where the data is coming from, but what is inside the dataframe. So you can create manually with some code a DataFrame with similar content as when you read the data from file, but a bit smaller and that still shows the issue you want to raise.

**Comment by mbj047** [comment]
so something similar to this would work?

`df = pd.read_csv('SampleCsvFile.csv', dtype={
            "zipcode" : str,
            "date" : str,
            "state" : str,
            "val1" : str,
            "val2" : str,
            "val3" : str,
            "val4" : str,
            "val5" : str
        })

results = []

for (zipcode, state), bag in df.groupby(["zipcode", "state"]):
    contents_df = bag.drop(["zipcode", "state"], axis=1)
    subset = [OrderedDict(row) for i,row in contents_df.iterrows()]
    results.append(OrderedDict([("zipcode", zipcode),
                                ("state", state),
                                ("subset", subset)]))`

**Comment by jorisvandenbossche** [comment]
We still don't have 'SampleCsvFile.csv', so we cannot run your code.

**Comment by mbj047** [comment]
Here is the input test file - 
[sg_main__test.txt](https://github.com/pandas-dev/pandas/files/1728444/sg_main__test.txt)

**Comment by TomAugspurger** [comment]
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports gives some advice on writing minimal test cases. Let us know if you're able.
