### ISSUE TITLE
Allow list-like for `y` in `DataFrame.plot`.

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#19699]
In pandas 0.22 and earlier, we passing multiple values for `y` worked by accident. The code clearly assumed that `y` was a scalar, but things usually worked, perhaps with an incidental warning:

```python
In [12]: df = pd.DataFrame(np.random.uniform(size=(10, 2)), columns=['a', 'b'])

In [15]: df.plot(x='c', y=['a', 'b'])
/Users/taugspurger/miniconda3/envs/pandas-0.21.0/lib/python3.6/site-packages/pandas/plotting/_core.py:1714: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  series.name = label
Out[15]: <matplotlib.axes._subplots.AxesSubplot at 0x10f83b198>
```

On master, this will currently raise. I think that we should explicitly support list-likes for `y`.

Tagging for 0.23 since I think this should be a blocker.

xref https://github.com/pandas-dev/pandas/pull/18695 where we made the change.

**Comment by MasonGallo** [comment]
@TomAugspurger yes I would be happy to help once I get some time, hopefully later this week.

Can you give a bit more details on what you would expect to return in your example above (or a similar example where the user supplies multiple y columns)?

**Comment by TomAugspurger** [comment]
I think it should be equivalent to `df.set_index('c')[['a', 'b']].plot()`. So multiple lines, each plotted against the `x`.

**Comment by MasonGallo** [comment]
Gotcha - this only makes sense if `a` and `b` are on the "same" scale right?

The `plot` method has a `secondary_y` arg but I'm not sure it makes sense to use in a general case like this.

**Comment by MasonGallo** [comment]
> Accepting a list-like for `y` would allow for an arbitrary number of lines all with
the same y axis.

This makes sense to me & I think the usecase is clear.
