### ISSUE TITLE
pytest deprecation warning

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#19703]
```python
home/travis/miniconda3/envs/pandas/lib/python3.6/site-packages/_pytest/mark.py:73: RemovedInPytest4Warning: Applying marks directly to parameters is deprecated, please use pytest.param(..., marks=...) instead.
For more details, see: https://docs.pytest.org/en/latest/parametrize.html
  warnings.warn(MARK_PARAMETERSET_UNPACKING)
```

```
$ ag "pytest.mark.*\(.*\)\("
pandas/tests/test_base.py
1220:    pytest.mark.xfail(reason='PeriodArray not implemented')((
```

though there are probably others.

**Comment by bhaveshpoddar94** [comment]
Beginner Here. Can I look onto this?

**Comment by TomAugspurger** [comment]
It looks like https://github.com/pandas-dev/pandas/pull/17253/files fixed most of these.

https://github.com/pandas-dev/pandas/blob/a7a7f8c1101aed1a9d37abbbcd80f77da414f0a8/pandas/tests/test_base.py#L1227 may be the only one left.

You should change that to use something like

```python
    pytest.param(pd.PeriodIndex(['2017', '2018'], freq='D'),
                 np.array([17167, 17532]),
                 marks=pytest.mark.xfail(reason="Not implemented")),
```

instead.

**Comment by bhaveshpoddar94** [comment]
So I just replaced the code line on 1227 with 
`pytest.param(pd.PeriodIndex(['2017',` '2018'], freq='D'),
   np.array([17167, 17532]), marks=pytest.mark.xfail(reason="Not implemented")),`

Is that correct?

**Comment by TomAugspurger** [comment]
It seems like pytest temporarily un-deprecated the warning.

Anyway,  that seems about right. You can make a PR and we'll take a look.
