### ISSUE TITLE
Series.hasnans shouldn't be cached

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#19700]
Series.hasnans is as a cache_readonly inherited from IndexOpsMixin

```
ser = pd.Series([0, 1.0])
>>> ser.hasnans
False
ser.iloc[0] = np.nan
>>> ser.hasnans
False
```

**Comment by TomAugspurger** [comment]
I wonder if that's intended to be Index only? Might want to just deprecate it in favor of `.isna().any()`.

**Comment by jbrockmendel** [comment]
I was thinking of adding an `_immutable` flag to `Index`/`NDFrame`(/`Array`) and a decorator `cache_if_immutable` that acts like `cache_readonly` for if `obj._immutable` and like `property` otherwise.  There's a bunch of stuff (in datetimes/timedeltas/periods, where else) like this that could make use of it.
