### ISSUE TITLE
Incorrectly assigned Index ops/names

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#19716]
Index op naming and pinning is inconsistent:

 - no `Index.__rsub__`, https://github.com/pandas-dev/pandas/blob/master/pandas/core/indexes/base.py#L2200
- `__iadd__, __isub__` aren't getting pinned to `cls` https://github.com/pandas-dev/pandas/blob/master/pandas/core/indexes/base.py#L3998
- `__radd__, __rpow__, __rmul, ...` aren't getting the correct names (not such a big deal)
- numeric subclass methods names:

```
>>> pd.Int64Index.__add__.__name__
'_evaluate_numeric_binop'
>>> pd.Float64Index.__mul__.__name__
'_evaluate_numeric_binop'
>>> pd.DatetimeIndex.__radd__.__name__
'__add__'
```

**Comment by gfyoung** [comment]
I might also add that `_evaluate_numeric_binop` is not a particularly useful name.
