### ISSUE TITLE
CI: Builds timing out

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#19712]
3.6 times out fairly regularly: e.g. https://travis-ci.org/pandas-dev/pandas/jobs/341598742

It's running `pytest -s -m single --strict --cov=pandas --cov-report xml:/tmp/cov-single.xml --junitxml=/tmp/single.xml --skip-slow --skip-network pandas` and `pytest -s -n 2 -m not single --cov=pandas --cov-report xml:/tmp/cov-multiple.xml --junitxml=/tmp/multiple.xml --strict --skip-slow --skip-network pandas`.

I'm not sure why that second one would take so long...

[This](https://travis-ci.org/pandas-dev/pandas/jobs/341598745) build stalled on a conda command

And the [doc build](https://travis-ci.org/pandas-dev/pandas/jobs/341598748) timed out as well.

**Comment by jreback** [comment]
these are travis issues have been pretty u reliable lately
