### ISSUE TITLE
Code Clean Up - groupby_helper.pxi.in

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#19724]
A few of the methods in `groupby_helper.pxi.in` have a pattern that goes:

```python

    N, K = (<object> values).shape

    with nogil:

        if K > 1:
            # loop over j in range(K) and do stuff
            ...
        else:
            # do stuff with j=0
            ...
```

Unless I'm missing something simple I don't think there's a reason to have the conditional and duplicate code branches. In the case where K=1 (which is all the time?) then the `for j in range(K)` construct inherently sets `j=0`, bypassing the need for the conditional

**Comment by chris-b1** [comment]
I believe the `K > 1` would get used sometime, from what I remember some of the aggregations are done by-block, which means a 2d array of multiple columns could get passed down.
https://github.com/pandas-dev/pandas/blob/2fdf1e256e5e0b7f1fe909629e2f0b7893c8c7c3/pandas/core/groupby.py#L3736

It's probably a micro-micro optimization, but having it split like this may generate slightly better code for `K=1` case.  But welcome you to benchmark and if it doesn't matter, clean it up.
