### ISSUE TITLE
(Re)-deprecate order keyword in factorize

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#19727]
In https://github.com/pandas-dev/pandas/pull/6930 we deprecated `order`.

As of 0.18.1, the keyword was no-longer documented, and doesn't raise, but wasn't actually removed.

```python
In [3]: pandas.factorize([0, 1], order=True)
Out[3]: (array([0, 1]), array([0, 1]))

In [4]: pandas.__version__
Out[4]: '0.18.1'
```

**Comment by TomAugspurger** [comment]
I don't have a strong preference on deprecating vs. just removing. Probably best to deprecate for one release.

**Comment by jorisvandenbossche** [comment]
To be clear, it seems the order keyword does nothing (so it was forgotten to be removed from the signature).

**Comment by EricChea** [comment]
I can take this.  I'm made some mods to ``deprecate_kwargs`` in ``pandas/util/_decorators.py`` to accommodate and just need to write some tests.
