### ISSUE TITLE
DEPR: Index.get_value ?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#19728]
`Index.get_value` is a very strange (from user perspective), and completely undocumented method, so let's rename it to `_get_value` for internal usage and deprecate the public one?

Example usage to show its 'not-usefulness':

```
In [85]: idx = pd.Index([1, 2, 3])

In [87]: idx.get_value(np.array([0, 1, 2]), 2)
Out[87]: 1
```
(so you can index into another object based on the location of the key in the calling index)

**Comment by jreback** [comment]
iirc this is heavily used in indexing code 
renaming just causes bloat - rather deprecation and fixing are better

**Comment by jorisvandenbossche** [comment]
But what needs to be fixed? If it is heavily used in indexing code, it is probably useful? 
IMO, the only thing that needs to be fixed is the fact that it is a public method, and then simply renaming does the trick (indexing code can maybe use a refactor, but that's a totally different and much bigger issue)

**Comment by jreback** [comment]
no you are missing the point here. A lot of index methods *are* used internally to do indexing. But that does not necessarily mean they should be publicly exposed, though they are currently. If we are making first class extensions, then *all* methods should be public and pandas itself should not even internally rely on indexing methods (and if they do they would be private).

So its public now, deprecating the current function just causes one more method and that is just smelly. If you want to deprecate it, then it should be completely removed from the  internal API and just call public methods).

**Comment by jorisvandenbossche** [comment]
I was not speaking about extensions here. Do you think there are Index subclasses in the wild that rely on `get_value` ?

**Comment by jorisvandenbossche** [comment]
Ah, yes, based on @shoyer 's comment here https://github.com/pandas-dev/pandas/issues/15258, it's indeed needed at this moment to implement custom Index subclass.

**Comment by shoyer** [comment]
I don't think there are Index subclasses in the wild  that *rely* on `get_value`. There might be subclasses that *implement* `get_value`, but they should still work fine when it's removed.

**Comment by jorisvandenbossche** [comment]
>  There might be subclasses that implement get_value, but they should still work fine when it's removed.

@shoyer But if `Series.__getitem__` now uses its index `get_value`, and we would rename / remove that, doesn't that mean that a Series with such a subclassed index would no longer work for those cases where it was used?

**Comment by shoyer** [comment]
If I recall correctly, `index.get_value(series, key)` is basically equivalent to `series.iloc[index.get_loc(key)]` (but it possibly faster). Assuming that the Index subclass implements `get_loc` (which is basically required for meaningful indexing) it should work fine with this fall-back.
