### ISSUE TITLE
Consider adding ExtensionDtype.is_dtype_equal

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#19741]
We have `is_dtype` for checking whether the dtype / array's dtype is of the same kind as `self`. It may sometimes be useful to have an *exact* comparison for parametrized dtypes like `Categorical` and `Period`.

So

```python
>>> PeriodDtype('4D').is_dtype(PeriodDtype('5D'))
True
>>> PeriodDtype('4D').is_dtype_equal(PeriodDtype('5D'))
```

**Comment by jbrockmendel** [comment]
I guess this would be faster than `__eq__` bc it would assume we have a Dtype object and not a string

**Comment by phofl** [comment]
Yeah this works with __Eq__, so closing
