### ISSUE TITLE
qcut raising ValueError if NaT present

### ISSUE THREAD

**Issue by gulp21** [pandas-dev/pandas#19768]
#### Code Sample, a copy-pastable example if possible

```python
from io import StringIO
import pandas as pd

csv = 'Index,Date\n1,2013-01-01 23:00:00\n2,\n3,2013-01-01 23:00:01'
df = pd.read_csv(StringIO(csv), index_col=0, parse_dates=[1])
pd.qcut(df["Date"], 2)
```
#### Problem description
`qcut` raises a `ValueError`:

```
Traceback (most recent call last):
  File "mve.py", line 26, in <module>
    pd.qcut(df["Date"], 2)
  File "/tmp/test/env/lib/python3.5/site-packages/pandas/core/reshape/tile.py", line 208, in qcut
    dtype=dtype, duplicates=duplicates)
  File "/tmp/test/env/lib/python3.5/site-packages/pandas/core/reshape/tile.py", line 251, in _bins_to_cuts
    dtype=dtype)
  File "/tmp/test/env/lib/python3.5/site-packages/pandas/core/reshape/tile.py", line 344, in _format_labels
    labels = IntervalIndex.from_breaks(breaks, closed=closed)
  File "/tmp/test/env/lib/python3.5/site-packages/pandas/core/indexes/interval.py", line 370, in from_breaks
    name=name, copy=copy)
  File "/tmp/test/env/lib/python3.5/site-packages/pandas/core/indexes/interval.py", line 411, in from_arrays
    copy=copy, verify_integrity=True)
  File "/tmp/test/env/lib/python3.5/site-packages/pandas/core/indexes/interval.py", line 225, in _simple_new
    result._validate()
  File "/tmp/test/env/lib/python3.5/site-packages/pandas/core/indexes/interval.py", line 265, in _validate
    raise ValueError('missing values must be missing in the same '
ValueError: missing values must be missing in the same location both left and right sides
```

#### Expected Output

`qcut` returning something like

```
Index
1    (2013-01-01 22:59:59.999999999, 2013-01-01 23:00:01.0
2    NaT
3    (2013-01-01 22:59:59.999999999, 2013-01-01 23:00:01.0
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.13.0-32-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8
LOCALE: de_DE.UTF-8

pandas: 0.22.0
pytest: None
pip: 9.0.1
setuptools: 38.5.1
Cython: None
numpy: 1.14.0
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by gfyoung** [comment]
1) Could you rewrite your example to not use `read_csv` (i.e. just construct the `DataFrame` from scratch).

2) Yeah...that does look weird indeed.  Even the error message is confusing.  PR to patch is welcome!

**Comment by jschendel** [comment]
Issue looks to occur in the integer conversion here:

https://github.com/pandas-dev/pandas/blob/80241e6d4b469aa55f6105d15d0a4176718bcbaa/pandas/core/reshape/tile.py#L290-L291

This converts `NaT` to a negative integer value:

```python
In [2]: dti = pd.DatetimeIndex(['20180101', pd.NaT, '20180103'])

In [3]: dti
Out[3]: DatetimeIndex(['2018-01-01', 'NaT', '2018-01-03'], dtype='datetime64[ns]', freq=None)

In [4]: dti.view(np.int64)
Out[4]: array([ 1514764800000000000, -9223372036854775808,  1514937600000000000], dtype=int64)
```

So `NaT` is getting passed through as numeric, then looks to be assigned as the end point of an interval in the output after getting converted back to `NaT`, which is an invalid way to construct intervals.
