### ISSUE TITLE
CLN: Remove `counts` Argument from Cython GroupBy Aggregations

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#19778]
All of the Cython aggregation functions accept `counts` as their second argument. In theory, it looks as if this parameter could assist in the handling of `NaN` values within a group, as dictated by the below lines of code:

https://github.com/pandas-dev/pandas/blob/e022d9a0886b245afe4af4cc43904a112cd00882/pandas/core/groupby.py#L2398

~~However, `self._filter_empty_groups` from what I can tell is always `False`. The only place this really gets exposed is in the `BinGrouper` constructor, but that is an internal class and I don't see any invocations of it that override the default value, essentially making the code linked above a `noop`.~~

I'm assuming that is part of an abandoned implementation, and if that's the case there's a decent amount of code cleanup / simplification that can be had between `groupby.py` and `groupby_helpers.pxi.in` if we remove `counts`

**Comment by WillAyd** [comment]
I was wrong on my original comment about `self._filter_empty_groups` always being `False` - it is set to `True` in the `BaseGrouper` initialization if there is more than one grouping. 

That said, I think there's still something strange with the implementation here. The `counts` parameter is initialized to an array matching the `ngroups` parameter, which appears to exclude `NaN` values:

https://github.com/pandas-dev/pandas/blob/e022d9a0886b245afe4af4cc43904a112cd00882/pandas/core/groupby.py#L2378

In essence the, the `counts` variable local to the `_cython_operation` function will only give you the number of times that each non-`NaN` group label appears. Assuming that to be true, then the conditional in my original comment still doesn't serve a purpose because it has no notion of when `NaN` actually does occur

I noticed that #3729 is open and may impact how we go about this. Perhaps even some of this code was put here with the forward-looking intention of servicing that request? I would still lean towards removing the variable until that implementation actually happens to minimize the code-base. Curious if others have thoughts

**Comment by jreback** [comment]
there is an old impl that gets u nan groupings (ref from #3729) may want to have a look

**Comment by jbrockmendel** [comment]
@WillAyd did you ever look into this?  Worth looking into as part of the current groupby-Exception push?

**Comment by WillAyd** [comment]
Haven't looked in quite some time, but I think if it simplifies things would make sense to remove

**Comment by jbrockmendel** [comment]
Looking at this, this seems to boil down to determining whether the `if kind == "aggregate" and self._filter_empty_groups and not counts.all():` condition is ever satisfied.  it isn't in the tests that make it to codecov: https://codecov.io/gh/pandas-dev/pandas/src/master/pandas/core/groupby/ops.py#L547, but maybe in e.g. slow tests?

**Comment by rhshadrach** [comment]
counts is now used to implement `min_count`:

https://github.com/pandas-dev/pandas/blob/4fcee0e431135bf6fa97440d4d7e17a96630fe6e/pandas/core/groupby/ops.py#L492-L500

With that, can this be closed @WillAyd?
