### ISSUE TITLE
DOC: First impressions

### ISSUE THREAD

**Issue by max-sixty** [pandas-dev/pandas#19793]
I remember sometime in 2014 being told about pandas & numpy and trying to find out more about it. And some of my friends (who haven't coded before) are in a similar position now. And so I'm reminded that the first thing you see is not compelling to a typical new user (e.g. someone who knows Excel and a bit of SQL):

### First result when searching for 'pandas' on Google:

![image](https://user-images.githubusercontent.com/5635139/36438798-f01cf358-1638-11e8-9807-3ced6605e3ff.png)

# Some comparisons:

### Jupyter Notebook

![image](https://user-images.githubusercontent.com/5635139/36438931-5639069a-1639-11e8-80c7-cfc8d8c11ba5.png)

### Tensorflow, which is not exactly for beginners:

![image](https://user-images.githubusercontent.com/5635139/36438837-069f8230-1639-11e8-9214-86f65a7c4d4a.png)

### Tidyverse is a bit better:

![image](https://user-images.githubusercontent.com/5635139/36438880-31f799b8-1639-11e8-8a9a-ac04f5835711.png)

### Pandas' GitHub Readme is better, but still doesn't immediately tell you what you can achieve (and is overly bashful - I think pandas can say that it has hit that goal)

![image](https://user-images.githubusercontent.com/5635139/36439028-9f896074-1639-11e8-8e0e-0454ead8ae1e.png)

## Proposal
...what do people think about redoing the opening page to make it more immediately appealing to new users - particularly those who don't have an engineering background?

If so, what do people think should be included?

**Comment by chris-b1** [comment]
100% agree the homepage could use some love - I'm personally a bit skeptical of the overly sales-y style of, e.g. TensorFlow, but it also probably works.

Maybe could have different introductions for different audiences?  Like, a 'who are you?' question with X categories (just making these up)
- Excel/SQL/other data analysis tool user who wants to learn python/pandas
- Python user who wants to learn data science tools
- [numpy/scientific python user, never used pandas]
- [R user!]

**Comment by jorisvandenbossche** [comment]
> I think that introduction text has not been touched for 5 years or so .. :-)

Correction: git blame says not 5 but 6 years

**Comment by mroeschke** [comment]
The home page has undergone an overhaul since this issue so probably best to close this for now and open up specific issues with specific points to change: http://pandas.pydata.org/
