### ISSUE TITLE
DTI/TDI comparison ops with incompatible types

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#19804]
Timestamp and Timedelta comparisons against non-Timestamp/Timedelta-like others return False for `__eq__`, True for `__ne__` and raise `TypeError` for inequalities.  DatetimeIndex follows this convention in _some_ cases, but there are paths that will end up raising instead of returning True/False.  TimedeltaIndex doesn't follow this convention at all.

Is the current hodge-podge intentional?  If not I can put together a PR to ensure that `index.__cmp__(other) == np.array([index[n].__cmp__(other) for n in range(len(index))])`

**Comment by jreback** [comment]
the timestamp/timedelta behavior is correct

ne/eq should always work
inequality always raise

for non compat types
numpy and python both follow this

**Comment by jbrockmendel** [comment]
This got fixed a ways back
