### ISSUE TITLE
Doc build leaves behind a test.json file

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#19815]
I think from https://github.com/pandas-dev/pandas/blob/aa59954a217c8f856bb0980265520d37b85a80af/doc/source/whatsnew/v0.23.0.txt#L220.

It should be removed in a hidden ipython block afterwards.

```
.. ipython:: python
   :suppress:

   import os
   os.remove('test.json')
```

**Comment by gfyoung** [comment]
@TomAugspurger : Alternatively, you can write to an IO object (instead of an actual file) and then read that instead (no cleanup needed afterwards).

**Comment by TomAugspurger** [comment]
I think for newcomers writing to a path is more approachable than using an
`io.TextIO` buffer.

**Comment by gfyoung** [comment]
Sure, but I'm thinking about whether that's the best way to do it (meaning it might not be newcomer-friendly).  Mind you that `os.remove` is not the nicest of things on Windows, so if users try to build docs there, that could be problematic.

**Comment by TomAugspurger** [comment]
I wasn't aware of that. We use it elsewhere in the docs and I haven't seen
any issues reported.

**Comment by gfyoung** [comment]
That's fair.  If this is just a one-off patch (i.e. we cleanup files elsewhere I presume), then I suppose adding this clean-up is fine then.  I'm still personally in the IO object camp, but not going to fight over one simple use case in the docs. 😄

**Comment by jjames34** [comment]
I'm taking this on for HackIllinois!
