### ISSUE TITLE
Index formatting in online reference

### ISSUE THREAD

**Issue by Nemecsek** [pandas-dev/pandas#19812]
The tree index for the online reference is wrongly formatted on the page: as the tree column is not wide enough, most text in lists is split in multiple lines.  

As it is, it is very difficult to find something scrolling along the tree.
This is a issue for both the latest Firefox (58.0) and Chrome (64.0).
Is it possible to fix the CSS?

This is a screenshot of [https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_dict.html](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_dict.html)
![screenshot from 2018-02-21 12-16-36](https://user-images.githubusercontent.com/25978536/36477793-ca84643a-1702-11e8-956c-1624091461af.png)

**Comment by jreback** [comment]
we do have css that can be edited
but the issue here is that if u make this wider then we loose valuable real estate on the right

welcome to have it look nicer thpugh

**Comment by TomAugspurger** [comment]
It'd be nice to make the sidebar collapsible.

**Comment by jorisvandenbossche** [comment]
In my opinion, in this case we should also make the toc not that deep, so all the DataFrame methods are not shown

**Comment by gfyoung** [comment]
@jreback : How much real estate do you need on the righthand side?  I see a lot of gray.

**Comment by jorisvandenbossche** [comment]
We use a different doc theme now, so closing this issue
