### ISSUE TITLE
Ensure S3 tests are mocked

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#19825]
Anaconda owns the `pandas-test` S3 bucket that we use for some of our tests. They're doing some spring cleaning, and would like to remove this bucket sometime next week.

We'll need to make sure that all of our tests are mocked.

From what I can tell, `pandas/tests/io/parser/test_network::TestS3` is not mocked.

We also have an ASV benchmark that hits S3, whose goal is to ensure that we don't read the whole file when doing `read_csv(..., nrows=10)`. I think we could remove that and replace it with a mocked fixture that asserts something about the number of bytes read.

**Comment by jreback** [comment]
we could also sign up for an aws account with NuMFOCUS. would be minimal cost I think.

**Comment by TomAugspurger** [comment]
Yeah, it'd be good to have one non-mocked test under a bucket we have
control over.

**Comment by TomAugspurger** [comment]
We've temporarily set the pandas-test bucket to be unreadable, and it'll be going away entirely soon. Tests still pass for me locally, so hopefully things are OK.

There's one reference to `s3://pandas-test` in the docs, but that's in a non-executed code-block.
