### ISSUE TITLE
SettingWithCopyWaraning when modifying a column that is the aggregation of 2 others

### ISSUE THREAD

**Issue by jamesqo** [pandas-dev/pandas#19852]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame({'c1': [1, 2, 3], 'c2': [3, 4, 5]})
df['c3'] = df['c1'] / df['c2']
df['c3'][0] = 0
```

I haven't tested with other arithmetic operators but I'm guessing it would happen for them as well.

**Comment by ZhuBaohe** [comment]
use `df.loc[0,'c3'] = 99`

**Comment by jamesqo** [comment]
@ZhuBaohe `loc` is kind of slow though. I'm just curious why this warning happpens in the first place

**Comment by ZhuBaohe** [comment]
See [Why does assignment fail when using chained indexing?](http://pandas.pydata.org/pandas-docs/stable/indexing.html#why-does-assignment-fail-when-using-chained-indexing)

**Comment by jreback** [comment]
this is well documented, you are doing chained indexing.
