### ISSUE TITLE
Inccorect example in DataFrame.to_dict docstring

### ISSUE THREAD

**Issue by mbkupfer** [pandas-dev/pandas#19868]
`pandas.DataFrame.to_dict` documentation has incorrect example. In first example box, df.col2 is showing wrong data.

`df.col2` should = 
```
a    0.50
b    0.75
```

**Comment by TomAugspurger** [comment]
Thanks for the report! Interested in making a PR to fix it?

**Comment by mbkupfer** [comment]
Yes, I'm in interested, but I also don't know how to do it. If there are
simple instructions, then I'd be happy to give it a try.

Maxim

**Comment by rockg** [comment]
Look at the [contributing guide](https://pandas.pydata.org/pandas-docs/stable/contributing.html)

**Comment by mbkupfer** [comment]
Ok. I took a peek and the instructions are helpful and looks pretty
straightforward.  I'm on a business trip all next week though, ok if I do
this in a couple weeks?  I'd their a deadline on PR?

**Comment by TomAugspurger** [comment]
No deadline. Thanks.

________________________________
