### ISSUE TITLE
Feature Request: DataFrame.drop to use numpy indexing

### ISSUE THREAD

**Issue by raybellwaves** [pandas-dev/pandas#19878]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame( data = {'name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'], 
                                               'year': [2012, 2012, 2013, 2014, 2014], 
                                               'reports': [4, 24, 31, 2, 3]})
df
#Out[4]: 
#   name  reports  year
#0  Jason        4  2012
#1  Molly       24  2012
#2   Tina       31  2013
#3   Jake        2  2014
#4    Amy        3  2014 

df.drop([3])
#Out[19]: 
#   name  reports  year
#0  Jason        4  2012
#1  Molly       24  2012
#2   Tina       31  2013
#4    Amy        3  2014

df.drop([3:])
#               ^
#SyntaxError: invalid syntax
```
#### Problem description

I thought this would drop rows with index 3 and 4. I know row indexes can be labels but in my case it is just numbers.

The work around is:
```
df.drop(np.arange(3,len(df)))
```

I can see that using a `numpy.ndarray` may be preferable for indexing than using normal numpy indexing because labelling can be numbers or strings. Perhaps it could be implementing by checking if labels do not exist then making df.drop([3:]) a wrapper for df.drop(np.arange(3,len(df)))? (thinking out loud here)

#### Expected Output

```
df.drop([3:])
#   name  reports  year
#0  Jason        4  2012
#1  Molly       24  2012
#2   Tina       31  2013
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Darwin
OS-release: 17.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: 3.3.2
pip: 9.0.1
setuptools: 38.4.0
Cython: 0.27.3
numpy: 1.14.0
scipy: 1.0.0
pyarrow: None
xarray: 0.10.0
IPython: 6.2.1
sphinx: 1.6.6
patsy: 0.5.0
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.1.2
openpyxl: 2.4.10
xlrd: 1.1.0
xlwt: 1.2.0
xlsxwriter: 1.0.2
lxml: 4.1.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.1
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by TomAugspurger** [comment]
> df.drop([3:])

pandas can't do anything about the syntax error :) You can't do `__getitem__` on the parenthesis.

> Perhaps it could be implementing by checking if labels do not exist then making df.drop([3:]) a wrapper for df.drop(np.arange(3,len(df)))?

We've been moving away from trying to guess the users intention. It's caused more trouble and confusion that convenience.

**Comment by raybellwaves** [comment]
Ok thanks. Mind if I add a `np.arange` index example to the examples in the docs? https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.drop.html

**Comment by TomAugspurger** [comment]
I'm curious, if you're doing `df.drop(np.arange(3, len(df))` then presumably you have a sorted, monotonic, regularly spaced index? Wouldn't `df.iloc[:3]` always achieve the same thing then?

**Comment by raybellwaves** [comment]
Yes you're right. Thanks. No need for me to use `drop` at all.
