### ISSUE TITLE
Add doctest flags to setup.cfg

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#19934]
pytest let's you add common doctest settings to the `setup.cfg`. I think we should add

```
doctest_optionflags= NORMALIZE_WHITESPACE
```

Any reason not to do this? Any others we should add?

**Comment by jorisvandenbossche** [comment]
Yes, I think that is a good idea.

**Comment by TomAugspurger** [comment]
Closed by https://github.com/pandas-dev/pandas/pull/20284
