### ISSUE TITLE
pd.to_datetime('today') and pd.Timestamp('today') return different results

### ISSUE THREAD

**Issue by skaae** [pandas-dev/pandas#19935]
#### Code Sample, a copy-pastable example if possible

```python
pd.Timestamp('today')
pd.to_datetime('today')
```

#### Problem description

pd.to_datetime('today') returns a floored timestamp and pd.Timestamp('today') doesn't

```
In [13]: pd.Timestamp('now')
Out[13]: Timestamp('2018-02-28 09:43:20.060483')

In [17]: pd.Timestamp('today')
Out[17]: Timestamp('2018-02-28 09:43:48.628730')

In [19]: pd.to_datetime('today')
Out[19]: Timestamp('2018-02-28 00:00:00')

```

#### Expected Output
I would expect pd.Timestamp('today') to behave similarly to pd.to_datetime('today'). 

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-53-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: 3.2.1
pip: 9.0.1
setuptools: 36.5.0.post20170921
Cython: 0.26.1
numpy: 1.13.1
scipy: 0.19.1
pyarrow: 0.8.0
xarray: 0.9.6
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 0.9.8
lxml: 3.8.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.5.0

</details>

**Comment by jreback** [comment]
hmm, yeah this is a bit inconsistent.

cc @jbrockmendel

**Comment by jreback** [comment]
pull request to fix is welcome!

**Comment by shangyian** [comment]
It looks like pandas' `Timestamp.today()` is modelled after the `datetime` library's `datetime.today()`. Does it make sense to have a discrepancy between `datetime.today()` and `Timestamp.today()` if the latter gets changed to be a floored datetime?

**Comment by jreback** [comment]
@shangyian the fix is to change ``pd.todatetime`` for this is hits a different (incorrect path)

**Comment by jreback** [comment]
this is almost the same issue as #18705 meaning , both are consistent (but incorrect) in ``.to_datetime``

**Comment by shangyian** [comment]
Ok, that makes more sense now - I added a PR
