### ISSUE TITLE
DOC: Freeze old whatsnew notes?

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#19942]
Currently on master, we have a new failure from the `0.10.0.txt` whatsnew due to the `line_width` option being removed.

Rather than continuing to fix these old examples due to backwards comparability breaks in pandas, could we convert the old `..ipython:: python` blocks to regular `.. code-block:: python` examples so they aren't run anymore? Ideally we could write a script that runs them one last time, captures the output, and updates the `.rst`. Anyone have interest in seeing if that's possible?

**Comment by jorisvandenbossche** [comment]
Yes! And there is already an issue for that: https://github.com/pandas-dev/pandas/issues/6856

I at some point looked into a kind of 'text' sphinx builder that would output what we want, but never really figured it out. I think it should be somehow possible (eg numpydoc also emits the intermediate generated source code that is never saved in a file to build the actual docstring page when using very verbose mode)

**Comment by jorisvandenbossche** [comment]
Closing in favor of #6856
