### ISSUE TITLE
pandas.DataFrame.apply function calls func twice on the first column/row

### ISSUE THREAD

**Issue by Duanexiao** [pandas-dev/pandas#19946]
#### Code Sample, a copy-pastable example if possible

```python
addDf.apply(lambda x:addCredit(x['content_name'],x['content_value'],x['credit'],userCreditSession,creditAction,queryDate,creditReason,creditType),axis=1)
```
#### Problem description
In my code ,I want to use apply to add credit for some credit object.In the pandas.DataFrame.apply
function notes,it says "In the current implementation apply calls func twice on the first column/row to decide whether it can take a fast or slow code path.".But when I tried this function,I found not only the 
first column/row calls func twice. It calls func twice on the head 3 columns/rows.

execute result as below:
select score,date from xx.xxx where credit_object = '0.1.0c883dfe72da252ea181ab6ce5a1f22a.c9a6dc'
select score,date from xx.xxx where credit_object = '0.1.0ed09a1a5cd60674146b6b3e0315b919.9d983b'
select score,date from xx.xxx where credit_object = '0.0.c222af7998f36fe34e4cf82b4d879dc6.8d8583'
select score,date from xx.xxx where credit_object = '0.1.0c883dfe72da252ea181ab6ce5a1f22a.c9a6dc'
select score,date from xx.xxx where credit_object = '0.1.0ed09a1a5cd60674146b6b3e0315b919.9d983b'
select score,date from xx.xxx where credit_object = '0.0.c222af7998f36fe34e4cf82b4d879dc6.8d8583'
select score,date from xx.xxx where credit_object = '0.0.2bfe2fdaf657bd1f9339a6f9542919df.10e946'

code execute environment:
centos 6.4
python 2.7
pandas version: 0.19.2

look forward to your replying,many thanks!

**Comment by gfyoung** [comment]
@Duanexiao : Thanks for reporting this!  Unfortunately, this is very hard for us to replicate since we don't have all of the objects in your code defined.  Could you provide us a reproducible code example?

**Comment by Duanexiao** [comment]
Sorry for so late replying.You can have a try with operating cassandra database any select .My code have no any special setting.Thank you!

**Comment by WillAyd** [comment]
This is documented behavior - see the Notes on apply

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.apply.html
