### ISSUE TITLE
PeriodIndex.ravel returns ndarray[int64]

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#19956]
This came up while trying to de-duplicate some DataFrame vs Series arithmetic logic in core.ops.

**Comment by gfyoung** [comment]
That seems consistent with the docstring?

**Comment by jbrockmendel** [comment]
Sure, but it's not exactly useful behavior.

**Comment by gfyoung** [comment]
Why not?

**Comment by jbrockmendel** [comment]
The relevant context is the ongoing effort to ensure that Index/Series/DataFrame operations are consistent with one another.  The Index vs Series part is most of the way there, and I'm just starting in on Series vs DataFrame.

In core.ops, [Series](https://github.com/pandas-dev/pandas/blob/master/pandas/core/ops.py#L985) and [DataFrame](https://github.com/pandas-dev/pandas/blob/master/pandas/core/ops.py#L1443) arithmetic operations have _really_ similar error catching logic:

```
```

**Comment by gfyoung** [comment]
Ah, interesting...got it.  Well, this is an API change, so I'll open it up to @jreback @jorisvandenbossche .  Is there any reason why we always returned `ndarray` ?

**Comment by jbrockmendel** [comment]
@TomAugspurger possibly change this behavior in a follow up to PeriodArray?

**Comment by TomAugspurger** [comment]
Is the expected behavior an ndarray[object] with period object?

This could be done any time by defining PeriodIndex.ravel as `self.values.ravel()` instead of inheriting the base implementation.

**Comment by jbrockmendel** [comment]
For PeriodArray I’d expect it to return a 1-dim-reshaped view on itself.  So a no-op for EA since those are 1-dim to begin with.

**Comment by TomAugspurger** [comment]
That'll need a larger discussion then, since the other EA-backed indexes all return ndarrays for ravel.

**Comment by jorisvandenbossche** [comment]
Also for Series, `ravel` returns an ndarray. 

I think there is also something to be said for `ravel` always to be an ndarray. 
Or to simply deprecate the method, since if you want a ravelled ndarray, you can also do the much more explicit `np.asarray(val).ravel()`.

The question is: what do people use it for? It might be that it is used in cases where afterwards the code expects to now have a numpy array.

**Comment by jbrockmendel** [comment]
> The question is: what do people use it for?

The place that motivated this issue is in `core.ops` where we currently call ravel() on most things but specifically avoid calling it on `PeriodIndex`.  It's a pretty ugly special case.

**Comment by jorisvandenbossche** [comment]
And what's the reason we call it there? What do we want to end up with there?

**Comment by jbrockmendel** [comment]
> And what's the reason we call it there? What do we want to end up with there?

In that case we are calling `right.ravel()` because `right` is an array-like and we want to work with a flattened version of that array.

**Comment by jorisvandenbossche** [comment]
But if the object is array, Series or Index, why do we want to ravel? Because all those are already 1D? (or the array can be 2D?)

**Comment by TomAugspurger** [comment]
I think just checking `if y.ndim > 1: yrav = y.ravel()` is the way to go. Not so elegant, but it avoids the discussion of what "ravel" means for EA-backed Series, and inconsistencies between ndarray and ea-backed series.

**Comment by jorisvandenbossche** [comment]
Anyway, mainly what I am trying to ask about: in this specific case that motivated the proposal, there might be a very easy way to also avoid duplicated code, without needing `ravel` ? 
We can simply check the dimension for example?

**Comment by jorisvandenbossche** [comment]
Well, so exactly what @TomAugspurger said :-)

**Comment by jbrockmendel** [comment]
> But if the object is array, Series or Index, why do we want to ravel? Because all those are already 1D? (or the array can be 2D?)

The array can be 2D.

> I think just checking if y.ndim > 1: yrav = y.ravel() is the way to go.

This is fine.  The extant code also works fine.

> but it avoids the discussion of what "ravel" means for EA-backed Series

That is pretty much what the Issue is about.  We can certainly stick a pin in this, but long-term the method's behavior should match the standard usage of the term "ravel"

**Comment by TomAugspurger** [comment]
Yeah, we'll certainly need to resolve this, but I think it depends a bit on
the result of #19954, if you have any thoughts there.

**Comment by jbrockmendel** [comment]
I see the appeal of being consistent with Series, but dont like the idea of materializing RangeIndex/MultiIndex.
