### ISSUE TITLE
multiple value inside a cell in a csv file 

### ISSUE THREAD

**Issue by frior2** [pandas-dev/pandas#19969]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

```
#### Problem description
Hello I am new to python pandas and i am having a problem figuring out how i can merge multiple values inside a single cell into a one line.

Incorrect:
1644107,"Delete stub zones
map.com
map.net",completed

Correct format:
1644107,Delete stub zones map.com map.net,completed

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by gfyoung** [comment]
@frior2 : Thanks for submitting this.  I'm a little confused what you're trying to do, given that you don't have actual code to provide.  Could you provide code to setup the `DataFrame` you're trying to write?

**Comment by mroeschke** [comment]
Looks like this issue needs more information to clarify the specific ask. Since this issue has gone stale without a response, going to close for now, but happy to reopen once we get more info
