### ISSUE TITLE
np.int64 in pandas dataframes is not instance of np.int64

### ISSUE THREAD

**Issue by skaae** [pandas-dev/pandas#19961]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
x = np.int64(4)
print("input isinstance np.int64    ",isinstance(x, np.int64))
print( "input type:", type(x))
df = pd.DataFrame.from_dict({0: {'int64':x}}, orient='index')

print('output')
print("dataframe isinstance np.int64",isinstance(df.iloc[0], np.int64))   # does not evaluate to true
print('dataframe dtype:',df['int64'].dtype)
print("dataframe type", type(df['int64'].iloc[0]))

print("dataframe.values dtype", isinstance(df.values[0][0], np.int64))

```
#### Problem description
A np.int64 instance that is extracted from a dataframe is not an np.int64 instance even though pandas dtype says it is and the underlying value is. 

#### Expected Output
```
input isinstance np.int64     True
input type: <class 'numpy.int64'>
output
dataframe isinstance np.int64 False
dataframe dtype: int64
dataframe type <class 'numpy.int64'>
dataframe.values dtype True
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-53-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: 3.2.1
pip: 9.0.1
setuptools: 36.5.0.post20170921
Cython: 0.26.1
numpy: 1.13.1
scipy: 0.19.1
pyarrow: 0.8.0
xarray: 0.9.6
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 0.9.8
lxml: 3.8.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.5.0

</details>

**Comment by jreback** [comment]
this is by-definition and correct. extraction or iteration of a scalar will always be a python type
