### ISSUE TITLE
BLD: wheel building is now failing

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#19984]
start 3 days ago: https://travis-ci.org/MacPython/pandas-wheels/builds/348053404

I think something is showing a ``UserWarning`` that didn't before.

like between master and: 52559f535788b3c59c6c78d2cf987b03303b16f6

**Comment by jreback** [comment]
cc @jbrockmendel @WillAyd @Liam3851 @mroeschke @topper-123 

(you had non-trivial changes since then)

**Comment by jreback** [comment]
builds for wheels are on numpy 1.9.3

**Comment by WillAyd** [comment]
Kind of strange that the error getting thrown is a `ResourceWarning`. Checking the [Python docs](https://docs.python.org/3.6/library/warnings.html#default-warning-filters) this is typically ignored unless Python is built in debug mode. I don't see anything in the pandas codebase that would explicitly set that save when `PANDAS_TESTING_MODE` contains "deprecate" but I didn't see that in the applicable config.

**Comment by jbrockmendel** [comment]
Is it happening consistently?  Could be a file handle leak?  If so, maybe try just instantiating/reading the StringIO obj without the rest of the test?

**Comment by jreback** [comment]
no this is new

there is a warning that is not being caught

**Comment by jreback** [comment]
this is ok now
