### ISSUE TITLE
Unable to Build Documentation

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#20001]
```bash

python make.py html

Traceback (most recent call last):
  File "doc/make.py", line 23, in <module>
    import pandas
ModuleNotFoundError: No module named 'pandas'
```

I believe a slight bug was introduced by c8859b57b891701f250fb05f2cc60d2e6cae2d6b in including `import pandas` at the top of the script. Unless the user has pandas installed as a package I don't think this module would know where to find it without modifying the path or being more explicit on import

@jorisvandenbossche

**Comment by jorisvandenbossche** [comment]
The path is being modified somewhere else in the file make.py. If you inline the import inside the `_process_single_doc` method, does that fix the error?

**Comment by WillAyd** [comment]
I don't think that makes a difference. I looked but didn't see anywhere else in the file that added the project root to the import path - perhaps I'm overlooking it?

Otherwise adding something like the below fixes the issue:

```python
DOC_PATH = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.dirname(DOC_PATH))
import pandas
```

**Comment by jorisvandenbossche** [comment]
https://github.com/pandas-dev/pandas/blob/master/doc/make.py#L346

**Comment by jorisvandenbossche** [comment]
Can you actually try it? I hope it would work because it then comes after `os.environ['PYTHONPATH'] = args.python_path`, but not fully sure imports work that way.

**Comment by WillAyd** [comment]
Hmm OK I see what we are trying to do. I think setting `os.environ['PYTHONPATH']` gives sphinx access to the import path when it compiles the module externally, but doesn't help the import mechanism specifically within the module. 

I'll push a PR in a few that I think should serve both purposes
