### ISSUE TITLE
read_html providing title from a attribute as well as the text - in effect duplicating output

### ISSUE THREAD

**Issue by MikeWoodward** [pandas-dev/pandas#20027]
#### Code Sample

url = """https://en.wikipedia.org/wiki/List_of_winners_of_the_Boston_Marathon"""
tables = pd.read_html(url, header=0)
print(tables[0].head())

#### Problem description

The above code ''should' just extract the displayed text in the HTML table; what's in the dataframe should be what's displayed on screen. This isn't what happens. If the HTML contains a hyperlink with a title attribute, this is picked up and added to the dataframe, duplicating the data.

#### Expected Output

```
   Year                   Athlete  \
0  1897          John J. McDermott   
1  1898         Ronald J. MacDonald   
2  1899          Lawrence Brignolia   
3  1900         John "Jack" Caffery   
4  1901         John "Jack" Caffery   

                      Country/State     Time        Notes  
0                United States (NY)  2:55:10          NaN  
1                     Canada Canada  2:42:00          NaN  
2                United States (MA)  2:54:38          NaN  
3                            Canada  2:39:44          NaN  
4                            Canada  2:29:23  2nd victory 
```

#### Output

Here's the actual output, the duplication is in the Athlete and Country/State columns.

```
   Year                                  Athlete  
0  1897      McDermott, John J.John J. McDermott   
1  1898  MacDonald, Ronald J.Ronald J. MacDonald   
2  1899    Brignolia, LawrenceLawrence Brignolia   
3  1900         Caffery, JohnJohn "Jack" Caffery   
4  1901         Caffery, JohnJohn "Jack" Caffery   

                      Country/State     Time        Notes  
0  United States United States (NY)  2:55:10          NaN  
1                     Canada Canada  2:42:00          NaN  
2  United States United States (MA)  2:54:38          NaN  
3                     Canada Canada  2:39:44          NaN  
4                     Canada Canada  2:29:23  2nd victory 
```

**Comment by WillAyd** [comment]
Are you seeing the issue on any other sites? Just glancing at the source I would think this has to do more with the span elements with `display:none` that are on the Wikipedia than the links (see screenshot below_ but curious if there's another source that was leading you to think the link is responsible

<img width="691" alt="screen shot 2018-03-07 at 11 35 18 am" src="https://user-images.githubusercontent.com/609873/37113944-c4001772-21fb-11e8-978d-ae91fb8beb0d.png">

**Comment by MikeWoodward** [comment]
I think you're right, I think this is an error on my part and it's the display:none setting that's doing it. I need a bit more time to investigate and I'll post again when I have some results.

**Comment by WillAyd** [comment]
OK thanks Mike. For what it's worth I already put what I believe to be the fix here in #20047 - might want to give that a look

**Comment by MikeWoodward** [comment]
Confirmed, this is the display:none doing this. Here's some example HTML that shows the issue.

<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>Example</title>
  </head>
  <body> 
    <p></p>
    <h1>This is a H1</h1>
    <p></p>
    <p>This is a paragraph</p>
    <table style="width: 100%" border="1">
      <tbody>
        <tr>
          <th>Column1</th>
          <th>Column2</th>
          <th>Column3</th>
        </tr>
        <tr>
          <td><span style="display:none">Span text display attribute:none</span><a
              href="/wiki/John_McDermott_%28runner%29"
              title="John McDermott (runner)">John
              J. McDermott</a>Text not in span or a</td>
          <td>Plain text - no elements</td>
          <td>Plain text - no elements</td>
        </tr>
        <tr>
          <td><span>Span text no display attribute</span><a href="/wiki/John_McDermott_%28runner%29"
              title="John McDermott (runner)">John
              J. McDermott</a>Text not in span or a</td>
          <td>Plain text - no elements<br>
          </td>
          <td>Plain text - no elements </td>
        </tr>
      </tbody>
    </table>
    <p>Some text<br>
    </p>
    <p><br>
    </p>
    <p><br>
    </p>
    <p><br>
    </p>
  </body>
</html>

**Comment by WillAyd** [comment]
Great thanks. Feel free to mess around with the fix I put in the above PR. Targeting v0.23 if all works out
