### ISSUE TITLE
DOC: use different 'sections' in the docstring examples?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#20039]
For docstrings that have quite some examples, it might be useful to provide some more structure in there. 
The numpydoc parsing does not really allow actual sections, but by using for example a bold font, you can create a bit the 'sense' of subsections.

Is this something we would want to encourage in the docstring guide?

Example of the current examples section of `to_datetime`:

![screenshot from 2018-03-07 17-03-47](https://user-images.githubusercontent.com/1020496/37103194-f285b4fc-2229-11e8-965d-648cc9538bdb.png)

And one with 'subsections' (just for the idea, not necessarily perfect titles :)):

![screenshot from 2018-03-07 17-02-54](https://user-images.githubusercontent.com/1020496/37103198-f52a4678-2229-11e8-8b16-b721ae0aea56.png)

cc @datapythonista @jreback @TomAugspurger

**Comment by TomAugspurger** [comment]
👍

**Comment by gfyoung** [comment]
+1 from me as well.  We are by no means strictly wed to the numpy-doc standards.

**Comment by jorisvandenbossche** [comment]
Closing this as @datapythonista included it in the docstring guide (https://github.com/pandas-dev/pandas/pull/19704)
