### ISSUE TITLE
Document how to plot figures in generated docs from docstrings

### ISSUE THREAD

**Issue by dukebody** [pandas-dev/pandas#20052]
Follow up for #20015. We need to write documentation about how to do this using blocks like:
```
..plot:: 
    :context: close-figs
    >>> s = pd.Series([1, 3, 2])
    >>> s.plot.line()
```

Should this be part of https://pandas.pydata.org/pandas-docs/stable/contributing.html#contributing-to-the-documentation? Are we planning to move the contents of https://python-sprints.github.io/pandas/guide/pandas_docstring.html there in a close future?

**Comment by jorisvandenbossche** [comment]
@datapythonista added a basic explanation in https://python-sprints.github.io/pandas/guide/pandas_docstring.html#plots-in-examples. Can you have a look at that? Feel free to do a PR to improve the explanation (I already spotted an indentation error).

> Are we planning to move the contents of https://python-sprints.github.io/pandas/guide/pandas_docstring.html there in a close future?

Yes, this is https://github.com/pandas-dev/pandas/pull/19704. So idea is indeed that the sprint guide gets integrated in the pandas docs.

**Comment by jorisvandenbossche** [comment]
I am going to close this issue, as the short explanation already has been added to the PR as well (#19704)
