### ISSUE TITLE
DOC: Series.unique docstring can be moved to series.py

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#20075]
Note for the documentation sprint:

- The docstring of `Series.unique` is currently defined in `pandas/core/base.py`, but since the docstring is no longer shared but only used by `Series.unique`, the docstring can be moved to `pandas/core/series.py` as a normal docstring of the Series.unique definition

**Comment by kurtiskerstein** [comment]
First time contributor.  I will work on this!

**Comment by jorisvandenbossche** [comment]
Sorry, but I think it is better to leave this for the sprint tomorrow, if you did not yet start (otherwise there will be conflicts tomorrow)

**Comment by kurtiskerstein** [comment]
Sounds good.  I'm looking forward to the sprint tomorrow.

**Comment by Chitrank-Dixit** [comment]
Is anyone working on this issue ?, If not I want to work on this issue.

**Comment by jorisvandenbossche** [comment]
It is assigned to a local group of the pandas sprint
