### ISSUE TITLE
Mistake in pd.DataFrame.assign() docstring

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#20085]
The docstring for ``df.DataFrame.assign()`` starts with 

```
Assign new columns to a DataFrame, returning a new object
(a copy) with all the original columns in addition to the new ones.
```

... but in fact existing columns can be overridden as well.

Hopefully tomorrow somebody will fix this!

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-5-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.23.0.dev0+463.g94ed47b15
pytest: 3.2.3
pip: 9.0.1
setuptools: 36.7.0
Cython: 0.25.2
numpy: 1.14.1
scipy: 0.19.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.5.6
patsy: 0.5.0
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.0dev
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.0
openpyxl: 2.3.0
xlrd: 1.0.0
xlwt: 1.3.0
xlsxwriter: 0.9.6
lxml: 4.1.1
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.2.1

</details>

**Comment by HannahFerch** [comment]
I would like to take this on as my first open source contribution.

**Comment by toobaz** [comment]
@HannahFerch good idea! See https://pandas.pydata.org/pandas-docs/stable/contributing.html if you haven't already

**Comment by HannahFerch** [comment]
Thanks, this has been a great first experience!
