### ISSUE TITLE
ENH: add hourofyear to period

### ISSUE THREAD

**Issue by timmie** [pandas-dev/pandas#2020]
Please add to
https://github.com/pydata/pandas/blob/master/pandas/tseries/period.py
- hourofyear

BTW,
How is it possible for user to add further convenience functions like:
- minuteofday

**Comment by petehuang** [comment]
Hi,

This issue has been inactive for a while. Does this continue to represent a useful enhancement? If not, I recommend closing this issue.

**Comment by jreback** [comment]
yeah this is not very useful, and can easily be compute from existing attributes.
