### ISSUE TITLE
Running tests fails on fresh install of pandas in conda env

### ISSUE THREAD

**Issue by brussee** [pandas-dev/pandas#20305]
#### Problem description

`pd.test()` outputs errors:

```
running: pytest --skip-slow --skip-network /home/paul/anaconda3/envs/an/lib/python3.6/site-packages/pandas
==================================== test session starts =====================================
platform linux -- Python 3.6.4, pytest-3.4.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/paul, inifile:
plugins: remotedata-0.2.0, openfiles-0.2.0, doctestplus-0.1.2, arraydiff-0.2
collected 0 items / 1 errors                                                                 

=========================================== ERRORS ===========================================
_____________________________________ ERROR collecting  ______________________________________
anaconda3/envs/an/lib/python3.6/site-packages/_pytest/config.py:329: in _getconftestmodules
    return self._path2confmods[path]
E   KeyError: local('/home/paul/anaconda3/envs/an/lib/python3.6/site-packages/pandas/tests/io')

During handling of the above exception, another exception occurred:
anaconda3/envs/an/lib/python3.6/site-packages/_pytest/config.py:360: in _importconftest
    return self._conftestpath2mod[conftestpath]
E   KeyError: local('/home/paul/anaconda3/envs/an/lib/python3.6/site-packages/pandas/tests/io/conftest.py')

During handling of the above exception, another exception occurred:
anaconda3/envs/an/lib/python3.6/site-packages/_pytest/config.py:366: in _importconftest
    mod = conftestpath.pyimport()
anaconda3/envs/an/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
anaconda3/envs/an/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
anaconda3/envs/an/lib/python3.6/site-packages/pandas/tests/io/conftest.py:3: in <module>
    import moto
E   ModuleNotFoundError: No module named 'moto'

During handling of the above exception, another exception occurred:
anaconda3/envs/an/lib/python3.6/site-packages/py/_path/common.py:377: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
anaconda3/envs/an/lib/python3.6/site-packages/py/_path/common.py:429: in gen
    for p in self.gen(subdir):
anaconda3/envs/an/lib/python3.6/site-packages/py/_path/common.py:418: in gen
    dirs = self.optsort([p for p in entries
anaconda3/envs/an/lib/python3.6/site-packages/py/_path/common.py:419: in <listcomp>
    if p.check(dir=1) and (rec is None or rec(p))])
anaconda3/envs/an/lib/python3.6/site-packages/_pytest/main.py:411: in _recurse
    ihook = self.gethookproxy(path)
anaconda3/envs/an/lib/python3.6/site-packages/_pytest/main.py:315: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
anaconda3/envs/an/lib/python3.6/site-packages/_pytest/config.py:343: in _getconftestmodules
    mod = self._importconftest(conftestpath)
anaconda3/envs/an/lib/python3.6/site-packages/_pytest/config.py:368: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   _pytest.config.ConftestImportFailure: ModuleNotFoundError("No module named 'moto'",)
E     File "/home/paul/anaconda3/envs/an/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 213, in load_module
E       py.builtin.exec_(co, mod.__dict__)
E     File "/home/paul/anaconda3/envs/an/lib/python3.6/site-packages/pandas/tests/io/conftest.py", line 3, in <module>
E       import moto
!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!
================================== 1 error in 0.30 seconds ===================================
```

#### Expected Output

http://pandas.pydata.org/pandas-docs/stable/install.html#running-the-test-suite

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-6-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.utf8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: 3.4.2
pip: 9.0.1
setuptools: 38.5.1
Cython: 0.27.3
numpy: 1.14.1
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.7.1
patsy: 0.5.0
dateutil: 2.6.1
pytz: 2018.3
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.2.0
openpyxl: 2.5.0
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.4
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
I think this has been fixed. Can you try on master?

**Comment by TomAugspurger** [comment]
Let us know if that doesn't work.

**Comment by k-eugene** [comment]
Hi! I have the same problem (Win10x64)!

pd.test()
running: pytest --skip-slow --skip-network C:\anaconda\lib\site-packages\pandas
============================= test session starts =============================
platform win32 -- Python 3.6.4, pytest-3.4.2, py-1.5.2, pluggy-0.6.0
rootdir: C:\, inifile:
plugins: remotedata-0.2.0, openfiles-0.2.0, doctestplus-0.1.2, arraydiff-0.2
collected 0 items / 1 errors

=================================== ERRORS ====================================
______________________________ ERROR collecting  ______________________________
C:\anaconda\lib\site-packages\_pytest\config.py:329: in _getconftestmodules
    return self._path2confmods[path]
E   KeyError: local('C:\\anaconda\\lib\\site-packages\\pandas\\tests\\io')

During handling of the above exception, another exception occurred:
C:\anaconda\lib\site-packages\_pytest\config.py:360: in _importconftest
    return self._conftestpath2mod[conftestpath]
E   KeyError: local('C:\\anaconda\\lib\\site-packages\\pandas\\tests\\io\\conftest.py')

During handling of the above exception, another exception occurred:
C:\anaconda\lib\site-packages\_pytest\config.py:366: in _importconftest
    mod = conftestpath.pyimport()
C:\anaconda\lib\site-packages\py\_path\local.py:668: in pyimport
    __import__(modname)
C:\anaconda\lib\site-packages\_pytest\assertion\rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
C:\anaconda\lib\site-packages\pandas\tests\io\conftest.py:3: in <module>
    import moto
E   ModuleNotFoundError: No module named 'moto'

During handling of the above exception, another exception occurred:
C:\anaconda\lib\site-packages\py\_path\common.py:377: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
C:\anaconda\lib\site-packages\py\_path\common.py:429: in gen
    for p in self.gen(subdir):
C:\anaconda\lib\site-packages\py\_path\common.py:418: in gen
    dirs = self.optsort([p for p in entries
C:\anaconda\lib\site-packages\py\_path\common.py:419: in <listcomp>
    if p.check(dir=1) and (rec is None or rec(p))])
C:\anaconda\lib\site-packages\_pytest\main.py:411: in _recurse
    ihook = self.gethookproxy(path)
C:\anaconda\lib\site-packages\_pytest\main.py:315: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
C:\anaconda\lib\site-packages\_pytest\config.py:343: in _getconftestmodules
    mod = self._importconftest(conftestpath)
C:\anaconda\lib\site-packages\_pytest\config.py:368: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   _pytest.config.ConftestImportFailure: ModuleNotFoundError("No module named 'moto'",)
E     File "C:\anaconda\lib\site-packages\_pytest\assertion\rewrite.py", line 213, in load_module
E       py.builtin.exec_(co, mod.__dict__)
E     File "C:\anaconda\lib\site-packages\pandas\tests\io\conftest.py", line 3, in <module>
E       import moto
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!
=========================== 1 error in 1.02 seconds ===========================
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

C:\anaconda\lib\site-packages\IPython\core\interactiveshell.py:2918: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

**Comment by jonwtan** [comment]
Hi, I'm also encountering the same issue with pandas with miniconda. The error output is similar. Something to do with the lack of module 'moto'.

**Comment by TomAugspurger** [comment]
Should have mentioned that it's fixed on master. You can install the RC now
with

    conda install -c conda-forge/label/rc pandas

or wait a little bit for the final release.

**Comment by jonwtan** [comment]
Thanks. Will try again.
