### ISSUE TITLE
DOC: nbsphinx required for python doc/make.py --single but not in core dev requirements 

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#20304]
We asked during the sprint to check the html output with `python doc/make.py --single method_name`, but this requires `nbsphinx` to be installed (because it is in conf.py listed as extension). 

However, `nbsphinx` is not in the core `environment-dev.yaml` file (sphinx is), it's only listed in the "optional" dev requirements.

It would be nice if we could make the script run without nbsphinx (or add nbsphinx to the core dev requirements)

**Comment by jbrockmendel** [comment]
nbsphinx is now in environment.yml (and so also requirements-dev.txt).  closeable?
