### ISSUE TITLE
API/INT: why is to_pydatetime handled differently in Series.dt accessor?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#20306]
While reviewing: https://github.com/pandas-dev/pandas/pull/20198, I notices this was defined in the `DatetimeProperties` itself:

https://github.com/pandas-dev/pandas/blob/78ded2585efb3e4b5164af91c85927b99298f026/pandas/core/indexes/accessors.py#L114-L143

Is there any reason that we have it like that, while all others are just wrapped DatetimeIndex attributes/methods? 

Because that means this returns (a bit strangly) an ndarray instead of a Series of the datetime.datetime values (making it inconsistent with other methods)

cc @jbrockmendel @jreback

**Comment by jorisvandenbossche** [comment]
cc @jbrockmendel @jreback

**Comment by jreback** [comment]
yes that is the reason
though we could return an object dtype Index

**Comment by jbrockmendel** [comment]
Could change this for 2.0.  Hard to deprecate since there isn't a good "do X instead."
