### ISSUE TITLE
Integrate with https://developer.tdameritrade.com/ (ask tdameritrade for code contribution)

### ISSUE THREAD

**Issue by lszyba1** [pandas-dev/pandas#20339]
#### Would like to request an integration with https://developer.tdameritrade.com/

TDameritrade which recently merged with scottrade and now offers a new rest api set.
Would be great if panda integrates with their API.

https://developer.tdameritrade.com/

http://pandas-datareader.readthedocs.io/en/latest/remote_data.html

#### Solution description
option a) is to reach-out to tdameritrade and see if they are interested in making a code contribution.
option b) is to have people who are already working with their api and want to use pandas, relate to this ticket and add their comments on python code they used so far.

Thank you
Appreciate the great software !
Lucas

**Comment by jreback** [comment]
out of scope for pandas, you can try with https://github.com/pydata/pandas-datareader

**Comment by lszyba1** [comment]
https://github.com/pydata/pandas-datareader/issues/501
