### ISSUE TITLE
API: Add DataFrame.droplevel

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#20342]
As a way to make dropping an index level possible in an method chain.

```python
>>> df = pd.DataFrame(np.arange(12).reshape(4, 3), columns=['a', 'b', 'c']).set_index(['a', 'b'])
>>> df.droplevel(0)
```

roughly equivalent to 

```python
df2 = df.copy()
df2.index = df.index.droplevel(0)
df2
```

cc @twiecki

**Comment by ericmjl** [comment]
@woohoo! I'd love for this to come into pandas, so that I don't have to worry about implementing it in pyjanitor!

**Comment by ericmjl** [comment]
Also, a hacky implementation to hopefully kickstart things: https://github.com/ericmjl/pyjanitor/blob/index-manipulation/janitor/functions.py#L324

and

https://github.com/ericmjl/pyjanitor/blob/index-manipulation/janitor/dataframe.py#L57

**Comment by twiecki** [comment]
Thanks @TomAugspurger! This would be a great addition.

One could make the same case for all other Index methods that return an index besides `rename_axis` and `droplevel()`, too. I wonder if it's worth thinking about a more general solution. E.g. something along the lines of a forward of `df.index_*() -> df.index = df.index.*()`.

**Comment by jschendel** [comment]
Not against this, but will it have any different functionality than `reset_index` with `drop=True`?

Seems like that covers a lot of what you'd want to do:
```python
In [2]: df = pd.DataFrame(np.arange(16).reshape(4, 4), columns=list('abcd')).set_index(list('abc'))

In [3]: df
Out[3]:
           d
a  b  c
0  1  2    3
4  5  6    7
8  9  10  11
12 13 14  15

In [4]: df.reset_index(level=1, drop=True)
Out[4]:
        d
a  c
0  2    3
4  6    7
8  10  11
12 14  15

In [5]: df.reset_index(level='c', drop=True)
Out[5]:
        d
a  b
0  1    3
4  5    7
8  9   11
12 13  15

In [6]: df.reset_index(level=['a', 'c'], drop=True)
Out[6]:
     d
b
1    3
5    7
9   11
13  15
```

**Comment by TomAugspurger** [comment]
Ah, good point. I suspect that covers all the needs.

This would be good to document in reset_index and in MultiIndex.droplevel.

**Comment by tliu30** [comment]
Don't think it totally covers everything...sometimes find a need to drop a column-index level, and i don't think reset_index supports columns (for good reason)

**Comment by TomAugspurger** [comment]
@jschendel had a good point that this will overlap with `reset_index` with `drop=True`. The advantages of a dedicated `droplevel` being

* `droplevel` is just for dropping a level, whereas `reset_index` can drop or insert
* `droplevel` can drop on either axis.

I don't have a strong opinion on whether we should add it, or better document reset_index.
