### ISSUE TITLE
Add CSS formating for deprecated parameters / methods

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#20349]
These aren't especially noticeable in the HTML docs.

![screen shot 2018-03-14 at 1 13 58 pm](https://user-images.githubusercontent.com/1312546/37422695-c9165cc4-2789-11e8-9939-7b3626f066ab.png)

Adding this to our CSS should fix that

```
div.deprecated {
    background-color: #ffe4e4;
    border: 1px solid #f66;
}
```

cc @datapythonista @shoyer

**Comment by TomAugspurger** [comment]
https://github.com/pandas-dev/pandas/blob/master/doc/source/themes/nature_with_gtoc/static/nature.css_t is the CSS file I think.

**Comment by Imanflow** [comment]
I would like to take this as my first contribution.

**Comment by TomAugspurger** [comment]
👍 thanks.

I think if you modify the CSS file then run

```python
# in pandas/doc
python make.py --single=pandas.DataFrame.from_csv
```

you should be able to validate the output quickly.

**Comment by TomAugspurger** [comment]
What's `git remote -v`?

May have to add `pandas-dev/pandas` as a remote

```
git remote add upstream https://github.com/pandas-dev/pandas
```

Not sure about the dateutil error. Did you make an environment for pandas? Did you activate it?

**Comment by Imanflow** [comment]
I started the process again, and everything worked fine.

Here is the pull request: https://github.com/pandas-dev/pandas/pull/20357
