### ISSUE TITLE
DOC: ecosystem.rst: Altair

### ISSUE THREAD

**Issue by westurner** [pandas-dev/pandas#20355]
What should the header link and description be?

Src: https://github.com/altair-viz/altair
Docs: https://altair-viz.github.io

https://github.com/pandas-dev/pandas/blob/master/doc/source/ecosystem.rst

**Comment by westurner** [comment]
@jakevdp @ellisonbg

**Comment by TomAugspurger** [comment]
We should just remove Vincent (😢 @wrobstory)

**Comment by wrobstory** [comment]
Farewell old friend, you were a pretty ok library for a little while

![RIP](https://images.rapgenius.com/1eb9f27a049991a745e97891a277e58b.500x203x9.gif)

**Comment by westurner** [comment]
From https://github.com/altair-viz/altair : 

> Altair is a declarative statistical visualization library for Python.
With Altair, you can spend more time understanding your data and its
meaning. Altair's API is simple, friendly and consistent and built on
top of the powerful Vega-Lite JSON specification. This elegant
simplicity produces beautiful and effective visualizations with a
minimal amount of code.

\+ Altair works with Pandas DataFrames.

**Comment by jschendel** [comment]
Looks like this made it into the [docs](https://pandas-docs.github.io/pandas-docs-travis/ecosystem.html#altair) but wasn't linked from the associated PR.

**Comment by westurner** [comment]
Thanks!

**Comment by westurner** [comment]
I'm in favor of leaving this broken markup in place:
https://pandas-docs.github.io/pandas-docs-travis/ecosystem.html#jupyter-notebook-jupyter-lab
