### ISSUE TITLE
pandas.isnull does not recognize _lib.tslib.NaTType() as null

### ISSUE THREAD

**Issue by AnthonyGaruccio** [pandas-dev/pandas#20386]
#### Code Sample

```python
>>> import pandas as pd
>>> pd.isnull(pd._lib.tslib.NaTType())
False

```
#### Problem description

pandas.isnull does not recognize pandas._lib.tslib.NaTType() as null

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit: None
python: 3.4.7.final.0
python-bits: 64
OS: FreeBSD

processor: amd64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.21.0
pytest: None
pip: 9.0.1
setuptools: 38.2.5
Cython: 0.27.3
numpy: 1.13.3
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: 1.1.11
pymysql: None
psycopg2: 2.7.1 (dt dec pq3 ext lo64)
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
Why do you think it should, and did this cause an issue for you? It doesn't recognize `NoneType` as null either.

**Comment by AnthonyGaruccio** [comment]
Sorry I didn't provide more context, I think it is inconsistent because of the following example

creating an instance of the _lib.tslib.NaTType class directly does not register as null for pd.isnull()
```python
>>> import pandas as pd
>>> pd.isnull(pd._lib.tslib.NaTType())
False
```

but if we create a series, with an instance of the _lib.tslib.NaTType class inside of it, then it DOES register as null for pd.isnull()
```python
>>> a = pd.Series(['2018-01-01', pd.NaT], dtype="datetime64[ns]")
>>> a
0   2018-01-01
1          NaT
dtype: datetime64[ns]
>>> pd.isnull(a)
0    False
1     True
dtype: bool
```
and if we access the element inside the series, it still registers as null for pd.isnull()
```python
>>> type(a.iat[1])
<class 'pandas._libs.tslib.NaTType'>
>>> pd.isnull(a.iat[1])
True
```

**Comment by jreback** [comment]
``NaTType`` is a private class, in a private module, so you are reaching into the implementation. It is a singleton, though it actually doesn't enforce this pattern. We have exactly one ``NaT`` and that is defined (internally), then referenced at the top level of the pandas namespace.

so ``is`` comparison work.

I am going to close this, but if you wanted to submit a patch to make ``NaTType`` an actual singleton it would be accepted.
