### ISSUE TITLE
strange result when use dataframe.append

### ISSUE THREAD

**Issue by orbitalz** [pandas-dev/pandas#20384]
#### Code Sample, a copy-pastable example if possible

```python
aaa = ['date', 'time', 'list']
bbb = pd.DataFrame(columns=aaa)
new_data = np.ones(len(aaa))
ccc = bbb.append(pd.DataFrame(new_data))
```
#### Problem description

After running the script, I've got this warning.

**RuntimeWarning: '<' not supported between instances of 'str' and 'int', sort order is undefined for incomparable objects
  result = result.union(other)**

```print(ccc)```  will get the result as shown following.

date | time | list | 0
NaN | NaN | NaN | 1.0

Not sure that I code in a wrong way or not. please advise.

#### Expected Output

 date | time | list
NaN | NaN | NaN

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.22.0
pytest: 3.2.3
pip: 9.0.1
setuptools: 38.6.0
Cython: 0.27.2
numpy: 1.14.2
scipy: 1.0.0
pyarrow: 0.7.1
xarray: 0.10.0
IPython: 6.2.1
sphinx: 1.7.1
patsy: 0.5.0
dateutil: 2.7.0
pytz: 2018.3
blosc: 1.5.1
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.4
feather: 0.4.0
matplotlib: 2.2.0
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: 1.0.2
lxml: None
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.1.14
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: 0.1.3
pandas_gbq: None
pandas_datareader: 0.5.0

</details>

**Comment by TomAugspurger** [comment]
You're appending a single column dataframe.

```python
In [18]: pd.DataFrame(new_data)
Out[18]:
     0
0  1.0
1  1.0
2  1.0
```

```python
Append rows of `other` to the end of this frame, returning a new
object. Columns not in this frame are added as new columns.
```

So make sure your columns are what you want.

FYI, typically you'll want to use concat instead of append.

**Comment by orbitalz** [comment]
Thank you so much for the tip!
