### ISSUE TITLE
DOC: Update missing data

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#20387]
http://pandas.pydata.org/pandas-docs/stable/10min.html?highlight=missing#missing-data makes no mention of NaT for marking missing values in datetime data.

Is that too early in the docs to mention that complication (and inf as null)? If so, we should link to http://pandas.pydata.org/pandas-docs/stable/missing_data.html#values-considered-missing

**Comment by jreback** [comment]
http://pandas.pydata.org/pandas-docs/stable/missing_data.html#datetimes is a pretty big mention of this.

**Comment by TomAugspurger** [comment]
Oh whoops, I missed that we already have a link to that section in the 10 minute intro. Sorry.
