### ISSUE TITLE
ENH: Allow list of keys in Dataframe.xs for each level

### ISSUE THREAD

**Issue by harisbal** [pandas-dev/pandas#20397]
```
arrays = [np.array(['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux']),
            np.array(['one', 'two', 'three', 'two', 'one', 'two', 'one', 'two'])]

df = pd.DataFrame(np.random.randn(8, 4), index=arrays)
```
It would probably be nice to allow for 

`df.xs([['bar', 'baz'], ['one', 'three']], level=[0,1])`

**Comment by jreback** [comment]
you can already do this with slicers (and has been this way for a while) dohttp://pandas.pydata.org/pandas-docs/stable/advanced.html#using-slicers

likeley to deprecate ``.xs`` anyhow. 

```
In [3]: ix = pd.IndexSlice

In [4]: df.loc[ix[['bar', 'baz'], ['one', 'three']], :]
Out[4]: 
                  0         1         2         3
bar one    3.019096  0.096874 -0.832045  1.413082
baz three  1.357525  0.124628  0.116054  1.759177
```

**Comment by jreback** [comment]
related issue is: https://github.com/pandas-dev/pandas/issues/4036

certainly welcome help on these!

**Comment by harisbal** [comment]
I like the drop level parameter of xs and that's the main reason I use it. I realised though that passing lists could make impossible to drop the filtered levels and that why I closed the issue.
