### ISSUE TITLE
uint64 inferred as float64

### ISSUE THREAD

**Issue by chebee7i** [pandas-dev/pandas#20407]
I'm running into an issue with `read_csv` where a column is being inferred as a `float64` column when it should be `uint64`. There are no nulls or missing values. Unfortunately, I am unable to provide the data and I have been unable to reliably reproduce the error with a synthetic dataset.

I managed to reduce my CSV file to 5-columns, 131074 rows. If I drop any row at the beginning or end, then I get the correct dtype (uint64). If I reorder the rows of the CSV, then the problem goes away as well. If I drop (meaning, textually alter the CSV) all columns from the CSV except the problematic one, then the problem goes away too. Similarly, dropping all columns after the problematic one also makes the problem go away. If I manually specify the type as uint64, then I get the correct dtype.

So the situation seems to be that type inference is being affected by things that really shouldn't be affecting the type inference of this column. I didn't look at the source code for the inference, but I'm hoping this might be enough information to help identify the issue.  I'm running pandas 0.22.

**Comment by gfyoung** [comment]
@chebee7i : Thanks for reporting this!  Unfortunately, we're going to need a reproducible example (i.e. code that we can run) to replicate this issue if possible.

**Comment by chebee7i** [comment]
Sure, it's definitely more difficult to debug without the data. I'll keep trying to winnow it down, but at some point, it seems should it should be feasible for someone familiar with the codebase to diagnose the issue given the symptoms.

More details:  `engine=python` does not have the problem, while `engine=c` does. Some behavior:
```
>>>  pd.read_csv('test23.csv', skiprows=0, engine='python').dtypes[1]
dtype('uint64')
>>>  pd.read_csv('test23.csv', skiprows=0, engine='c').dtypes[1]
dtype('float64')
>>>  pd.read_csv('test23.csv', skiprows=1, engine='c').dtypes[1]
dtype('uint64')
```
This seems to implicate the first row. But if I go and delete a *random* row from the middle of the file, then the bad behavior goes away. Similarly, if I delete the last row (which happens to be the only row that has a value that is greater than 2**63), then the problem goes away too (expectedly, the inferred dtype is int64 instead of uint64).


There is nothing special about the first row from what I can see.  It is similar to the second row in that the number is smaller than `2**53` and clearly an integer (no decimal digits, as with the entire file). The last row is the only row in the file that is greater than `2**63`, which forces uint64.  Of course, if you go out and construct such a file with these characteristics, you probably won't see the issue.

**Comment by gfyoung** [comment]
> it seems should it should be feasible for someone familiar with the codebase to diagnose the issue given the symptoms.

I would not make that assumption.  Everyone's situation is different.  That's why we ask for a code sample at the top of the file.

**Comment by TomAugspurger** [comment]
Let us know if you can provide a reproducible example: http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports
