### ISSUE TITLE
Legend of point-style items go missing

### ISSUE THREAD

**Issue by highfestiva** [pandas-dev/pandas#20418]
#### Code Sample

```python
import pandas as pd
import matplotlib.pyplot as plt

df = pd.DataFrame(dict(x=[2,3,4],y=[5,7,6]))
_,ax = plt.subplots()
df.plot(style='v', ax=ax)
df.plot(ax=ax)
plt.show()
```
#### Problem description
The legend symbol entries of the first items (`style="v"`) go blank when other entries are added below/after.
<img src="https://i.imgur.com/E4IZf13.png"/>

#### Expected Output

I expect all legend symbols to show up, no matter which order I plot them in.

#### Output of ``pd.show_versions()``

<details>

commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.22.0
pytest: None
pip: 9.0.2
setuptools: 39.0.1
Cython: None
numpy: 1.14.2
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: 0.4.1
dateutil: 2.7.0
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.9999999
sqlalchemy: 1.2.5
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by MarcoGorelli** [comment]
Thanks @highfestiva - this was fixed in #27808
