### ISSUE TITLE
Bins from pd.cut are not of equal width

### ISSUE THREAD

**Issue by jamespreed** [pandas-dev/pandas#20423]
The first bin of the bins returned when `retbins=True` is used with an integer number of bins is not of the same width as the other bins.

```python
import pandas as pd
import numpy as np

x = np.random.randint(0, 3000, size=500000)
a, b = pd.cut(x, 1000, labels=list(range(1000)), retbins=True) 
# using include_lowest has no effect

b
# returns:
array([   -2.999,   2.999,   5.998, ..., 2993.002, 2996.001, 2999.])

np.diff(b)
# returns:
array([ 5.998,  2.999,  2.999, ...., 2.999,  2.999])

```

The first bin is nearly twice the size of the other bins in this example.   I would expect the output to be:

```
array([     0,   2.999,   5.998, ..., 2993.002, 2996.001, 2999.])
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.20.3
pytest: 3.2.1
pip: 9.0.1
setuptools: 36.5.0.post20170921
Cython: 0.26.1
numpy: 1.13.3
scipy: 0.19.1
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
matplotlib: 2.1.0
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
From the (new and improved) docstring for cut

```
bins : int, sequence of scalars, or pandas.IntervalIndex
    The criteria to bin by.

    * int : Defines the number of equal-width bins in the range of `x`. The
      range of `x` is extended by .1% on each side to include the minimum
      and maximum values of `x`.
 
```

So your lowest bin is extended by 0.001.

```
In [31]: x.min() - 0.001 * (x.max() - x.min())
Out[31]: -2.999
```

If you want to disable that you can provide the bins ahead of time, in which case no extending is done.

**Comment by mroeschke** [comment]
Closing as this appears to be the expected behavior
