### ISSUE TITLE
feature request: efficient "random access" DataFrame creation

### ISSUE THREAD

**Issue by ophiry** [pandas-dev/pandas#20435]
Currently, when trying to build a DataFrame in "random access" mode (adding rows \ columns dynamically) it's pretty slow, and the best practice is to build a python object (list of dicts, or something similar), and later convert it to a DataFrame

it would be convenient to have "DataFrame Builder" - an object that supports DataFrame indexing, but has a dictionary backend, which can later be converted to a regular data frame.

This is mainly syntactic sugar on top of current best practices, but it should make relevant code much clearer

**Comment by TomAugspurger** [comment]
This sounds like a large project, and I suspect is unlikely to be done within pandas. Perhaps I misunderstand though. A small concrete example may help people understand what you're asking for.

**Comment by mroeschke** [comment]
Feel free to reopen if you can provide a minimal example of this feature.
