### ISSUE TITLE
Pandas test fails in conda

### ISSUE THREAD

**Issue by k-eugene** [pandas-dev/pandas#20433]
Hi!
I have the problem with pandas testing (Win10x64)
All packages are updated:

pd.test()
running: pytest --skip-slow --skip-network C:\anaconda\lib\site-packages\pandas
============================= test session starts =============================
platform win32 -- Python 3.6.4, pytest-3.4.2, py-1.5.2, pluggy-0.6.0
rootdir: C:\, inifile:
plugins: remotedata-0.2.0, openfiles-0.2.0, doctestplus-0.1.2, arraydiff-0.2
collected 0 items / 1 errors

=================================== ERRORS ====================================
______________________________ ERROR collecting  ______________________________
C:\anaconda\lib\site-packages\_pytest\config.py:329: in _getconftestmodules
    return self._path2confmods[path]
E   KeyError: local('C:\\anaconda\\lib\\site-packages\\pandas\\tests\\io')

During handling of the above exception, another exception occurred:
C:\anaconda\lib\site-packages\_pytest\config.py:360: in _importconftest
    return self._conftestpath2mod[conftestpath]
E   KeyError: local('C:\\anaconda\\lib\\site-packages\\pandas\\tests\\io\\conftest.py')

During handling of the above exception, another exception occurred:
C:\anaconda\lib\site-packages\_pytest\config.py:366: in _importconftest
    mod = conftestpath.pyimport()
C:\anaconda\lib\site-packages\py\_path\local.py:668: in pyimport
    __import__(modname)
C:\anaconda\lib\site-packages\_pytest\assertion\rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
C:\anaconda\lib\site-packages\pandas\tests\io\conftest.py:3: in <module>
    import moto
E   ModuleNotFoundError: No module named 'moto'

During handling of the above exception, another exception occurred:
C:\anaconda\lib\site-packages\py\_path\common.py:377: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
C:\anaconda\lib\site-packages\py\_path\common.py:429: in gen
    for p in self.gen(subdir):
C:\anaconda\lib\site-packages\py\_path\common.py:418: in gen
    dirs = self.optsort([p for p in entries
C:\anaconda\lib\site-packages\py\_path\common.py:419: in <listcomp>
    if p.check(dir=1) and (rec is None or rec(p))])
C:\anaconda\lib\site-packages\_pytest\main.py:411: in _recurse
    ihook = self.gethookproxy(path)
C:\anaconda\lib\site-packages\_pytest\main.py:315: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
C:\anaconda\lib\site-packages\_pytest\config.py:343: in _getconftestmodules
    mod = self._importconftest(conftestpath)
C:\anaconda\lib\site-packages\_pytest\config.py:368: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   _pytest.config.ConftestImportFailure: ModuleNotFoundError("No module named 'moto'",)
E     File "C:\anaconda\lib\site-packages\_pytest\assertion\rewrite.py", line 213, in load_module
E       py.builtin.exec_(co, mod.__dict__)
E     File "C:\anaconda\lib\site-packages\pandas\tests\io\conftest.py", line 3, in <module>
E       import moto
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!
=========================== 1 error in 1.02 seconds ===========================
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

C:\anaconda\lib\site-packages\IPython\core\interactiveshell.py:2918: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

**Comment by TomAugspurger** [comment]
Fixed in master: https://github.com/pandas-dev/pandas/pull/18719
