### ISSUE TITLE
to_excel does not support emoj

### ISSUE THREAD

**Issue by thesby** [pandas-dev/pandas#20448]
when a string contains emoj, to_excel will fail. But excel 2013 support emoj, actually.

**Comment by TomAugspurger** [comment]
http://stackoverflow.com/help/mcve

is the failure in pandas or the excel writer?

**Comment by thesby** [comment]
sorry, I find a parameter to_excel('xxx.xls', encoding='utf-8') to solve the problem. I should assign the encoding.
