### ISSUE TITLE
Contributing to codebase with Codeblocks compiled pandas, tests for new features?

### ISSUE THREAD

**Issue by BLMeltdown** [pandas-dev/pandas#20451]
Hello
I would like to contribute to pandas codebase as I've (hopefully) had some expectedly nice features  ideas for it, but it is not easy to start;)
I am stuck at the time I have to compile my own pandas as Visual Studio 2017 refuses to install on my machine because of Net Framework 4.6.
It is unfortunate that MS assistance can't help here (their forums mark these topics as duplicate and send back to topics which have not been solved. Genius), so I tried to find some alternative
in Code::Blocks http://www.codeblocks.org/
Some compilers provided with the default Code::Blocks installation are GNU GCC (MinGW/Cygwin), MS Visual C++ Free Toolkit 2003, Borland's C++ Compiler 5.5, DigitalMars Free Compiler., OpenWatcom, Small Device C Compiler (SDCC) and others. 
Would it be fitting for working with Python and Pandas codebase?

What are alternative solutions?
I really want to contribute, but being stuck on the first steps is pitiful (but doesn't reflect my coding ability, I hope:)).

Do you know if there is a lighter /friendlier user contribution roadmap?
The document https://github.com/pandas-dev/pandas/blob/master/doc/source/contributing.rst#working-with-the-code is very complete but quite harsh to approach.
It is not very clear what should be installed from the start (I read about cpplint, clang, flake8, asv and pytest but I wonder why they don't come as an addition to pandas dependencies so you really create an environment with the complete tools).

Thanks by advance

**Comment by TomAugspurger** [comment]
Did any of the links on https://devguide.python.org/setup/#windows or http://pandas.pydata.org/pandas-docs/stable/contributing.html#installing-a-c-complier help? It's been a while since I tried to set up a windows development environment.

**Comment by TomAugspurger** [comment]
https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2017-compatibility-vs#net-framework claims .net framework 4.7 is compatible with 4.6 . Are you able to upgrade?

**Comment by BLMeltdown** [comment]
Thanks for your help, I could not re install VS2017 despite upgrading .Net Framework 4.7.
I ended up upgrading Visual C++ redistributable; I will try to compile from here for now (I could not progress on my tests)

**Comment by chris-b1** [comment]
@BLMeltdown, yes it is normal to have some conversion warnings, though eventually would like to have those cleaned up! (e.g. see #5385)

I haven't used codeblocks, but with windows you will want visual studio installed to build extensions compatible with python. If on python 2, the specific msvc 2008 linked above, for python 3.6 visual studio 2017.  (2015 for 3.5) If it's installed the normal way, setuptools should find it automatically and, e.g. `python setup.py build_ext -i` will work.
