### ISSUE TITLE
method .to_pydatetime() doesn't convert when used with .map()

### ISSUE THREAD

**Issue by danparshall** [pandas-dev/pandas#20478]
#### Code Sample, a copy-pastable example if possible

```python
# hourly increments, in milliseconds
millisecs = np.arange(0,13000000,3600000)

ts_df = pd.DataFrame(data={'times':millisecs})

# column of tz-aware pd.Timestamp
ts_df['ts'] = ts_df.millisecs.map(lambda x: pd.Timestamp(x, unit='ms', tz=dt.timezone.utc))

# should produce column of python dt.datetime objects
ts_df['bogus_pydt'] = ts_df.ts.map(lambda x: x.to_pydatetime() )  

# actual object is still pd.Timestamp
ts_df['bogus_pydt'][1] 


# workaround is to make a DatetimeIndex as an intermediate step
dti = pd.DatetimeIndex(df.ts)
ts_df['py_dt_obj'] = dti.to_pydatetime()

```
#### Problem description
Behavior of `.to_pydatetime()` is inconsistent here.  A single `pd.Timestamp` object is correctly converted, but here the array of objects remains unchanged.

#### Expected Output
`.to_pydatetime()` should produce `dt.datetime` object

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Linux
OS-release: 2.6.32-573.7.1.el6.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: 3.4.1
pip: 9.0.1
setuptools: 38.5.1
Cython: 0.27.3
numpy: 1.14.1
scipy: 1.0.0
pyarrow: 0.8.0
xarray: 0.10.1
IPython: 6.2.1
sphinx: 1.7.0
patsy: 0.5.0
dateutil: 2.6.1
pytz: 2018.3
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.1.2
openpyxl: 2.5.0
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.1
bs4: 4.6.0
html5lib: 0.9999999
sqlalchemy: 1.2.1
pymysql: 0.8.0
psycopg2: 2.7.3.2 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: 0.1.3
fastparquet: 0.1.4
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
it wouldn't make any sense to actually convert this as you are creating a new ``Series``, which holds only first class ``Timestamps``. you could store ``datetime``, but you would have to be quite explicit about it.

you could do this

```
In [16]: pd.Series([v.to_pydatetime() for v in ts_df.ts], dtype=object)
Out[16]: 
0    1970-01-01 00:00:00+00:00
1    1970-01-01 01:00:00+00:00
2    1970-01-01 02:00:00+00:00
3    1970-01-01 03:00:00+00:00
dtype: object
```

though there is no good reason as this is non-idiomatic, and competely non-performant. pandas is highly optimized to hold datetimes (with and w/o tz) already.
