### ISSUE TITLE
Assigning with partial indexing on columns and mixed type unnecessarily upcasts

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#20476]
#### Code Sample, a copy-pastable example if possible

```python
In [2]: df = pd.DataFrame(-1, index=range(3), columns=pd.MultiIndex.from_product([['A', 'B'], ['a', 'b', 'c']]))

In [3]: filler = pd.DataFrame([[1, 2, 3.]]*3, index=range(3), columns=['a', 'b', 'c'])

In [4]: filler
Out[4]: 
   a  b    c
0  1  2  3.0
1  1  2  3.0
2  1  2  3.0

In [5]: df['A'] = filler

In [6]: df
Out[6]: 
     A            B      
     a    b    c  a  b  c
0  1.0  2.0  3.0 -1 -1 -1
1  1.0  2.0  3.0 -1 -1 -1
2  1.0  2.0  3.0 -1 -1 -1
```

#### Problem description

Only one of the three columns had float dtype, but the two others have been upcasted.

My guess is that somewhere a ``.values`` is used inappropriately.

#### Expected Output

``` python
In [6]: df
Out[6]: 
   A          B      
   a  b    c  a  b  c
0  1  2  3.0 -1 -1 -1
1  1  2  3.0 -1 -1 -1
2  1  2  3.0 -1 -1 -1
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-5-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.23.0.dev0+653.g7273ea070
pytest: 3.2.3
pip: 9.0.1
setuptools: 38.5.2
Cython: 0.25.2
numpy: 1.14.1
scipy: 0.19.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.5.6
patsy: 0.5.0
dateutil: 2.7.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.0dev
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.0
openpyxl: 2.3.0
xlrd: 1.0.0
xlwt: 1.3.0
xlsxwriter: 0.9.6
lxml: 4.1.1
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.2.1

</details>

**Comment by jreback** [comment]
ok, might be tricky, setting is pretty messing inside

**Comment by proost** [comment]
No one working on, Could i look into this?
