### ISSUE TITLE
BUG: apply after pivot may get a bug.

### ISSUE THREAD

**Issue by xuanxiangyu** [pandas-dev/pandas#20470]
I think I got a bug here.
```python
import pandas as pd
df = pd.DataFrame({"A": [1, 2, 3, 4, 5], "B": [3.125, 4.12, 3.1, 6.2, 7.],"C":['a','a','b','b','a']})
a=df.pivot(index="A",columns="C",values="B")
b=a.copy()
def func(x):
    x['a']=3
a.apply(func,axis=1)
b.apply(func,axis=1)

In [2]: a
Out[2]:
C    a    b
A
1  3.0  NaN
2  3.0  NaN
3  3.0  3.1
4  3.0  6.2
5  3.0  NaN

In [3]: b
Out[3]:
C      a    b
A
1  3.125  NaN
2  4.120  NaN
3    NaN  3.1
4    NaN  6.2
5  7.000  NaN
```
First, I get `a` after call pivot on the  dataframe `df`, and `b,` which is a copy of `a`. Then I call apply on `a` and `b` respectively. Now we can see the `a` and `b` is different.

**Comment by jreback** [comment]
this is a mis-use of ``.apply``. you are mutating inside the function. It is an implementation detail if this works (it generally doesn't but depending on the memory layout it might). This is non-supported, and non-idiomatic.

**Comment by xuanxiangyu** [comment]
I didn't find the detail about this point in the document of this api. Could you please tell me where can I find the detail?
