### ISSUE TITLE
Python Panda df.loc successfully but the removed rows are still there

### ISSUE THREAD

**Issue by vnyennhi** [pandas-dev/pandas#20477]
#### Code Sample, a copy-pastable example if possible

```python
# df.loc[:,"Tobacco"].fillna('No involvement', inplace=True)
# df = df[df.loc[:,"Tobacco"] == 'No involvement']

```
#### Problem description

I have a normal csv file imported as panda df. Then I use those 2 line of code to select remove some rows from the df. I got this warning message (sometimes there is a warning, but sometimes I run it again and no warning)

> C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:3660:
> SettingWithCopyWarning:  A value is trying to be set on a copy of a
> slice from a DataFrame
> 
> See the caveats in the documentation:
> http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
> self._update_inplace(new_data)

The original df has 7084 rows. After running the code:
```python
# len(df) = 6834
# df.shape = (6834,52)
```
However, the removed rows are still there: print(df['Country']) gives me 7084 rows instead of 6834. 

I have tried different code like below but still no luck.

```python
# df.loc[].copy()
# df = df[df['Tobacco'] == 'No involvement']
```
I have tested this code on Anaconda Spyder with Python 3 on Windows and Linux, PyCharm on Linux, and native Python on Linux and get the same error.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: None.None

pandas: 0.20.3
pytest: 3.2.1
pip: 9.0.2
setuptools: 38.2.3
Cython: 0.26.1
numpy: 1.13.3
scipy: 1.0.0
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.1.0
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.0
bs4: 4.6.0
html5lib: 0.9999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by TomAugspurger** [comment]
Have a look at http://stackoverflow.com/help/mcve. We won't be able to help you in specific terms unless you have an example.

and the docs at http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy, and https://stackoverflow.com/questions/20625582/how-to-deal-with-settingwithcopywarning-in-pandas, and https://www.dataquest.io/blog/settingwithcopywarning/.
