### ISSUE TITLE
DOC: add ibis to pandas ecosystem

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#20483]
xref #20345 

http://docs.ibis-project.org/

**Comment by jreback** [comment]
cc @cpcloud @wesm

**Comment by westurner** [comment]
@wesm what should the description be?

From https://github.com/ibis-project/ibis :

> Ibis is a toolbox to bridge the gap between local Python environments, remote storage, execution systems like Hadoop components (HDFS, Impala, Hive, Spark) and SQL databases. Its goal is to simplify analytical workflows and make you more productive.

Should these be in the description block?:

> Apache Impala (incubating)
> Apache Kudu
> Hadoop Distributed File System (HDFS)
> PostgreSQL
> MySQL (Experimental)
> SQLite
> Pandas DataFrames (Experimental)
> Clickhouse
> BigQuery

**Comment by westurner** [comment]
@wesm I suppose this isn't technically blocking #20345 for 0.23

**Comment by cpcloud** [comment]
This shouldn't block the release.

**Comment by jreback** [comment]
it’s not
