### ISSUE TITLE
repr of dataframe bound methods includes the frame data

### ISSUE THREAD

**Issue by pyscripter** [pandas-dev/pandas#20494]
#### Code Sample
```python
>>>import pandas as pd
>>>df=pd.DataFrame([pd.Series(range(100))]*100)
>>> df.tail
<bound method NDFrame.tail of     0   1   2   3   4   5   6   7   8   9  ...  90  91  92  93  94  95  96  \
0    0   1   2   3   4   5   6   7   8   9 ...  90  91  92  93  94  95  96   
1    0   1   2   3   4   5   6   7   8   9 ...  90  91  92  93  94  95  96  
...
```
#### Problem description

The representation of a bound method is 127 lines long and repeats the frame data:
```python
>>> len(repr(df.tail).split('\n'))
127
```
I have no idea why for instance repr(df.tail) or for that matter the repr of any other method, includes a copy of the data. It sounds pointless to me.   Maybe I am missing something?

If you run the following script:

```python
import pandas as pd
df=pd.DataFrame([pd.Series(range(100))]*100)
count = 0
for i in dir(df):
    s = repr(getattr(df, i))
    count += len(s.split('\n'))
print(count)
```
you will see that the repr of all df members is 53317 lines for a moderate size frame!  This causes problems for IDE's that use introspection on live python objects.

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
commit: None
python: 3.6.4.final.0
python-bits: 32
OS: Windows
OS-release: 10
machine: x86
processor: x86 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.22.0
pytest: None
pip: None
setuptools: 38.4.0
Cython: None
numpy: 1.14.2
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.0
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

**Comment by TomAugspurger** [comment]
Do you know if bound methods have any control over their repr? AFAIK, that's defined in python, and can't (easily) be modified.

**Comment by pyscripter** [comment]
https://stackoverflow.com/questions/21344862/possible-to-change-a-python-methods-str-attribute
provides a couple of ways to do that.

**Comment by TomAugspurger** [comment]
We won't be making our classes descriptors for this. That has a decent amount of overhead IIRC, and it's a lot of complexity, when we already provide all our formatting options.

**Comment by pyscripter** [comment]
See for example the Variables view of Pyscripter inspecting a dataframe.  The data is repeated in every frame.
![capture](https://user-images.githubusercontent.com/1311616/37964575-a8c9d91e-31ca-11e8-8b43-6a6220618077.JPG)

**Comment by TomAugspurger** [comment]
How's it look when you set the options to use the info repr, with a low
number for max_info_columns?

**Comment by pyscripter** [comment]
>>> pd.set_option("display.max_rows", 1)

![capture1](https://user-images.githubusercontent.com/1311616/37965151-c1584266-31cc-11e8-91b9-348805af6000.JPG)

Pyscripter shows a shortened the repr anyway.

**Comment by pyscripter** [comment]
And with 
>>> pd.set_option("display.expand_frame_repr", False)
![capture2](https://user-images.githubusercontent.com/1311616/37965272-2c7db4d6-31cd-11e8-9791-a245aa391275.JPG)

**Comment by TomAugspurger** [comment]
That's esstentially our info repr

```
In [8]: pd.options.display.memory_usage = False

In [9]: pd.options.display.max_info_columns=1

In [10]: df.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Columns: 100 entries, 0 to 99
dtypes: object(100)
```

**Comment by TomAugspurger** [comment]
I suppose we could add additional options, like memory_usage, to control
the remaining pieces (if we don't already have them, not sure).

**Comment by pyscripter** [comment]
Oh!
The following realy helps:
```

>>> pd.options.display.memory_usage = False
>>> pd.options.display.max_info_columns=1
>>> pd.options.display.large_repr = "info"

```

**Comment by jreback** [comment]
i still don’t see why this is actually an issue

**Comment by pyscripter** [comment]
Repr of bound methods of dataframes should not include a copy of the data.   It does not cause problems in normal use but it slows down IDEs that provide live object introspection such as the one shown above and is confusing.

Since a workaround was found I am closing this issue.
