### ISSUE TITLE
DOC: io.rst uses deprecated Index.summary

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#20508]
https://github.com/pandas-dev/pandas/blob/cdfce2b0ad99f7faad57cc5247cf33aab5725bed/doc/source/io.rst (line 3979 at the moment).

Should probably just change it to `c`.

**Comment by mimikaTU** [comment]
i would like to work on the issue plz:)

**Comment by pulkitmaloo** [comment]
I also noticed that in many of the examples, the code is not PEP8 style compliant, can I work on this?

**Comment by TomAugspurger** [comment]
Sure. It'd be best to see if you can find a way to run the linter on the
code sections, so that
they stay fixed.
