### ISSUE TITLE
Move Wiki testing page to main docs?

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#20501]
Currently in contributing.rst we link to https://github.com/pandas-dev/pandas/wiki/Testing

Thoughts on having that as a separate page in the rst docs?

**Comment by jorisvandenbossche** [comment]
Yes, I think putting that in the developer section of the docs is a good idea (separate page, for now linked from the developer.rst page?)

**Comment by jreback** [comment]
yep
