### ISSUE TITLE
Weird Error Groupby : works with .sum(), but throws error with .rank()

### ISSUE THREAD

**Issue by ruhkog** [pandas-dev/pandas#20524]
I am working with a multiindex dataframe.

Applying:

    df.groupby(level).sum()

Works FINE

However, applying:

    df.groupby(level).rank()

throws me the following error:

    ValueError: Categorical categories must be unique

Important note: I am working with 4 levels. I am grouping by using the first 3 levels. 
The fourth level is a vector of dates, the same for all the index levels. 
To be as specific as possible, I have 90 different index levels.

The error is threw only when my overall multiindex dataframe exceeds 10000 rows. Meaning that each index levels as over or 112 days of data. 

Using tail(), I noticed that when it is 9990 rows (111 days per index level), it gives me the rank... adding an additional day throws me the error.

I checked the specific day, but it looks fine.

I then added additional layers in the first three levels, meaning that instead of having 90 index levels, I now have more. And the scenario repeats itself. It throws me the error when the multiindex dataframe len is > 10000. Below, it gives me the rank.

Anyone had this error before? I am having a very hard time understanding where it comes from.

**Comment by TomAugspurger** [comment]
Can you make a reproducible example? http://stackoverflow.com/help/mcve

**Comment by ruhkog** [comment]
Well, while trying to program a reproducible example, I kind of found a solution to my problem. But it still doesn't make any sense. And sharing the issue won't work as doing it cancels out the issue.

Basically, I was looking to put the data in an excel file then upload it on python to make sure you guys had it. While doing it, it solved the issue.

I then tried something.

Instead of doing 

    df.groupby(level).rank()

And facing my issue.

I am now doing this:

    df.reset_index().set_index(levels).groupby(levels).rank()

And it doesn't throw me any error. So I can't really share a reproducible example... But I am still very annoyed by the problem.

**Comment by tv3141** [comment]
Can you try to minimize the code and data that produce the exception?

**Comment by ruhkog** [comment]
Unfortunately it's complicated as I upload data from a DB, and the whole stuff is built within classes. Given that I've kind of solved the issue with this workaround, I will close the issue. Thanks to both of you
