### ISSUE TITLE
groupby.cumsum fails, groupby.apply(np.cumsum) works on Decimal column

### ISSUE THREAD

**Issue by postelrich** [pandas-dev/pandas#20539]
#### Problem description

Cumulative sum fails on a decimal column during a groupby. However if I apply `np.cumsum` to the same column, it works. Would expect cumsum to work on numeric object types.

#### Code Sample, a copy-pastable example if possible

```python
>>> import pandas as pd                                                                          
>>> df = pd.DataFrame({'x': ['a', 'b', 'a', 'b', 'a', 'b'], 'y': [10, 5, 20, 6, 30, 7]})         
>>> df.groupby('x').cumsum()
    y
0  10
1   5
2  30
3  11
4  60
5  18                          

>>> from decimal import Decimal                                                                  
>>> df['y'] = [Decimal(str(v)) for v in df['y'].tolist()]  
>>> df.groupby('x').cumsum()
---------------------------------------------------------------------------
DataError                                 Traceback (most recent call last)
<ipython-input-12-2d4e07f67976> in <module>()
----> 1 df.groupby(['x'])['y'].cumsum()

C:\Users\rpostelnik\AppData\Local\Continuum\miniconda3\envs\jsiops36\lib\site-packages\pandas\core\groupby.py in cumsum(self, axis, *args, **kwargs)
   1682             return self.apply(lambda x: x.cumsum(axis=axis, **kwargs))
   1683
-> 1684         return self._cython_transform('cumsum', **kwargs)
   1685
   1686     @Substitution(name='groupby')

C:\Users\rpostelnik\AppData\Local\Continuum\miniconda3\envs\jsiops36\lib\site-packages\pandas\core\groupby.py in _cython_transform(self, how, numeric_only)
    905
    906         if len(output) == 0:
--> 907             raise DataError('No numeric types to aggregate')
    908
    909         return self._wrap_transformed_output(output, names)

DataError: No numeric types to aggregate
                                   
>>> import numpy as np                                                                           
df.groupby('x')['y'].apply(np.cumsum) 
    y
0  10
1   5
2  30
3  11
4  60
5  18                                                                                                                                        
```
#### Expected Output

```python
>>> df.groupby('x')['y'].cumsum()
    y
0  10
1   5
2  30
3  11
4  60
5  18    
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS                                                                  
------------------                                                                  
commit: None                                                                        
python: 3.6.4.final.0                                                               
python-bits: 64                                                                     
OS: Windows                                                                         
OS-release: 7                                                                       
machine: AMD64                                                                      
processor: Intel64 Family 6 Model 45 Stepping 2, GenuineIntel                       
byteorder: little                                                                   
LC_ALL: None                                                                        
LANG: en_US.UTF-8                                                                   
LOCALE: None.None                                                                   
                                                                                    
pandas: 0.22.0                                                                      
pytest: 3.5.0                                                                       
pip: 9.0.1                                                                          
setuptools: 38.5.1                                                                  
Cython: None                                                                        
numpy: 1.14.2                                                                       
scipy: None                                                                         
pyarrow: None                                                                       
xarray: None                                                                        
IPython: 6.2.1                                                                      
sphinx: 1.7.1                                                                       
patsy: None                                                                         
dateutil: 2.7.0                                                                     
pytz: 2018.3                                                                        
blosc: None                                                                         
bottleneck: None                                                                    
tables: None                                                                        
numexpr: None                                                                       
feather: None                                                                       
matplotlib: None                                                                    
openpyxl: None                                                                      
xlrd: None                                                                          
xlwt: None                                                                          
xlsxwriter: None                                                                    
lxml: None                                                                          
bs4: None                                                                           
html5lib: 1.0.1                                                                     
sqlalchemy: 1.2.5                                                                   
pymysql: None                                                                       
psycopg2: 2.7.4 (dt dec pq3 ext lo64)                                               
jinja2: 2.10                                                                        
s3fs: None                                                                          
fastparquet: None                                                                   
pandas_gbq: None                                                                    
pandas_datareader: None                                                             

</details>

**Comment by javadnoorb** [comment]
Just in my input helps, this is seems to be true for a lot of functions (e.g. cumprod, mean, cummin, cummax, etc.).

Seems to me that if in this line `is_numeric_dtype` returns False the function skips calculations and throws an error:
https://github.com/pandas-dev/pandas/blob/c4b4a81f56205082ec7f12bf77766e3b74d27c37/pandas/core/groupby.py#L985

With objects like the one you have defined, the function `is_numeric_dtype` returns False as can be seen from the following test:
 
```
import pandas as pd
from pandas.core.dtypes.common import is_numeric_dtype
from decimal import Decimal     
df = pd.DataFrame({'x': ['a', 'b', 'a', 'b', 'a', 'b'], 'y': [10, 5, 20, 6, 30, 7]})         
print(df['y'].dtype,is_numeric_dtype(df['y']))
df['y'] = [Decimal(str(v)) for v in df['y'].tolist()]  
print(df['y'].dtype,is_numeric_dtype(df['y']))
```
which returns:
```
int64 True
object False
```

**Comment by WillAyd** [comment]
I don't think numpy supports Decimal as a type, representing it instead as an object. Object aggregations are by nature slower and come with a lot of caveats and I'm not sure it would really be worth the effort to support this.

Why are you even using Decimal in your example? All of the values are just as well represented as an int. If you need decimal places are there specific precision issues with float64 that you are encountering?

**Comment by jreback** [comment]
this is not likely to be supported as decimal is not a first class type in pandas. maybe after ``DecimalArray`` (via EA) this might be possible.
