### ISSUE TITLE
TST: Extract methods from TestXMySQL and TestXSQLite and remove

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#20536]
I haven't looked too closely, but in https://github.com/pandas-dev/pandas/pull/13611/files the `TestXMySql` tests were unconditionally skipped.

IIUC, these are the test using a DBAPI2 `Connection` object, which is deprecated? We should remove these tests if they aren't being run.

**Comment by jorisvandenbossche** [comment]
> IIUC, these are the test using a DBAPI2 Connection object, which is deprecated?

It's no longer deprecated, but actually removed (for mysql writing) or accepted (for sqlite, and in practice also for reading query's)

>  We should remove these tests if they aren't being run.

Yeah, IIRC those tests were old tests from before the sqlalchemy refactor, and kept for "we should actually clean up the tests (go through them, and keep the useful bits in case it is not yet covered in the other tests), but that is some work, so just leave them there for now" reasons

**Comment by TomAugspurger** [comment]
Gotcha, so the TODO here is to pick out the interesting tests, and move them to the _TestMySQLAlchemy class?:

**Comment by jorisvandenbossche** [comment]
Yep (but it might be there is actually nothing interesting)

**Comment by jorisvandenbossche** [comment]
And the same is true actually for `TestXSQLite` (which is not skipped), also for those it would be nice to better integrate them with the rest of the tests

**Comment by TomAugspurger** [comment]
One potential strategy for discovering which lines are tested in just TestX*:

1. Run just the `TestSQLiteAlchemy` tests with covereage
2. Run just the `TestXSQLite` tests with coverage

dif the two coverage reports (not sure if there's a tool to do this, or if you would do it manually).

**Comment by mroeschke** [comment]
I think the precursor ADBC work to refactor the sql tests addressed this so closing
