### ISSUE TITLE
API: deprecate range-generating keywords in DatetimeIndex

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#20535]
I was reviewing the PR on the DatetimeIndex docstring, and the list of parameters is horribly complex because you can both use it by passing `data` (with accompanying keywords like `copy`, `dtype`, ..) and by generating a range with optional `start`, `end`, `periods`. 

Since for generating ranges, we have the special purpose `pandas.date_range`, do we need to keep this functionality in the `DatetimeIndex` constructor as well?

Of course deprecating it will annoy people who use it (although I *think* the majority of usage of DatetimeIndex passed `data`), so the question is whether it is worth it.

**Comment by jreback** [comment]
yep should do this

**Comment by jorisvandenbossche** [comment]
We still need to do the same for PeriodIndex.

**Comment by TomAugspurger** [comment]
What's the plan for `fields`?  I don't actually know what that does.

**Comment by TomAugspurger** [comment]
Hmm, slight API change (I think it counts as a bug) when `start` / end is a Period with a non-daily freq.


```python
In [2]: start = pd.Period("2000", freq="B")

In [3]: pd.period_range(start, periods=4).freq
Out[3]: <Day>

In [4]: pd.PeriodIndex(start=start, periods=4).freq
Out[4]: <BusinessDay>
```

I think we want `Out[4]`. On master this is incorrect because the default value in `period_range` is `'D'`, not None.

**Comment by TomAugspurger** [comment]
On fields, I think that we should continue to accept them in the PeriodIndex constructor (at least, we shouldn't add them to `period_range`).
