### ISSUE TITLE
html5lib not in requirements

### ISSUE THREAD

**Issue by drdhaval2785** [pandas-dev/pandas#20547]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
fiddy_states = pd.read_html('https://simple.wikipedia.org/wiki/List_of_U.S._states')

```
#### Problem description

There is an import error. 
```python
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    fiddy_states = pd.read_html('https://simple.wikipedia.org/wiki/List_of_U.S._states')
  File "C:\Python27\lib\site-packages\pandas\io\html.py", line 915, in read_html
    keep_default_na=keep_default_na)
  File "C:\Python27\lib\site-packages\pandas\io\html.py", line 739, in _parse
    parser = _parser_dispatch(flav)
  File "C:\Python27\lib\site-packages\pandas\io\html.py", line 682, in _parser_dispatch
    raise ImportError("html5lib not found, please install it")
ImportError: html5lib not found, please install it
```

#### Expected Output

There should not be an import error.
It should be included in dependencies.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.9.final.0
python-bits: 32
OS: Windows
OS-release: 8
machine: AMD64
processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.22.0
pytest: 3.0.2
pip: 9.0.3
setuptools: 39.0.1
Cython: 0.24.1
numpy: 1.14.2
scipy: 0.18.0
pyarrow: None
xarray: None
IPython: None
sphinx: 1.6.5
patsy: None
dateutil: 2.7.2
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.5.1
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.6.0
</details>

**Comment by WillAyd** [comment]
This is documented pretty clearly as an optional dependency in the installation guide (amongst other html choices)

https://pandas.pydata.org/pandas-docs/stable/install.html#optional-dependencies

**Comment by jorisvandenbossche** [comment]
Yes, since this is an optional dependency, it is not installed by default by just installing pandas.

**Comment by drdhaval2785** [comment]
Apologies for false alarm.
