### ISSUE TITLE
COMPAT: Don't use re module's private type

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#20551]
https://github.com/pandas-dev/pandas/blob/c4b4a81f56205082ec7f12bf77766e3b74d27c37/pandas/core/dtypes/inference.py#L219

In 3.6+ there's `typing.re.Pattern`. Otherwise, there's `_re_type = type(re.compile(''))`.

**Comment by jreback** [comment]
is there a pep reference for this?

**Comment by TomAugspurger** [comment]
I assume not, since it's a private attribute.
