### ISSUE TITLE
API: Allow extension dtypes in NDFrame.astype

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#20557]
Do we want to support this? If so, how?

```python
In [22]: from pandas.tests.extension.decimal.array import DecimalArray, decimal, DecimalDtype

In [23]: ser = pd.Series(['1.0', '1.1'])
In [24]: ser.astype(...)
```

Some issues:

1. unlikely, but multiple extension types could have the same name, so `ser.astype('decimal')` might be ambiguous. Let's refuse to guess, and require that an instance or subclass of `ExtensionDtype` be provided. So `DecimalDtype`
2. How to go from dtype to array type? (we can currently go array to dtype, but not the other way around)
3. How to get the Array's "parser" (something like `to_decimal`).

A solution to 2 is to require that an `ExtensionDtype` have a property `array_type` that returns the class it's a type for.

```python
class DecimalDtype(ExtensionDtype):
    @property
    def array_type(self): return DecimalArray
```

I think that's fine. It means you can't use the same type for multiple arrays, but whatever.

A solution to 3 is a bit harder... Having an arbitrary "try to parse this sequence of things, maybe coercing / erroring" might be generally useful (e.g. reading in from a CSV). Thoughts here? I don't think this needs to block 0.23.

**Comment by jreback** [comment]
this is very likely up to the extension type to handle (or raise as to not handle). But not sure why this is not simple

``DecimalArray._constructor_from_sequence``. isn't that the point of this?

**Comment by TomAugspurger** [comment]
`_constructor_from_sequence` takes a sequence of instances of `ExtensiondType.type`. In the case of `DecimalDtype` that's instances of `Decimal`.

`.astype` is also able to coerce, e.g.

```python
In [3]: pd.Series(['2017', '2018']).astype('datetime64[ns]')
Out[3]:
0   2017-01-01
1   2018-01-01
dtype: datetime64[ns]
```

We would need something more flexible than `_constructor_from_sequence`.

**Comment by jreback** [comment]
This was my point from the getgo. I think you need to have the constructor be able to take multiple types of objects (if it can) in the construction step. So now you end up having to add more and more api.

**Comment by TomAugspurger** [comment]
Yeah, I think we understood you're argument, we just disagreed :)

**Comment by jreback** [comment]
hahha ok!

**Comment by jorisvandenbossche** [comment]
I personally don't find this very important to have. 

But, like you propose a property `array_type` on the dtype, you could also have a class method `astype` (or other name) that deals with the actual conversion. So that `Series([vals]).astype(DecimalDtype)` is converted to `Series(DecimalDtype.astype([vals]))`

**Comment by jbrockmendel** [comment]
we now have construct_array_type.  is there anything else to do here?

**Comment by jbrockmendel** [comment]
Closing as complete.
