### ISSUE TITLE
STYLE: Add additional flake8 plugins

### ISSUE THREAD

**Issue by jschendel** [pandas-dev/pandas#20588]
xref https://github.com/pandas-dev/pandas/pull/20563#issuecomment-377648415

Might be nice to add some additional `flake8` plugins to check various things:
  - Enforce using new-style classes?
     - The [hacking](https://github.com/openstack-dev/hacking) package looks to do this (cc @mroeschke)
     - Added a related check to `lint.sh` in #20563, which can be removed if this is added
  - Enforce PEP8 naming conventions for classes?
    - Doesn't look like this is currently enforced

Any other ideas are welcome.

**Comment by TomAugspurger** [comment]
Import order :)

Linters for the docstrings and code sections of the prose docs (flake8 or otherwise) would be great.

**Comment by jbrockmendel** [comment]
Couple of options for import order.
https://pypi.org/project/flake8-imports/
https://pypi.org/project/flake8-isort/
https://github.com/PyCQA/flake8-import-order  <-- tentatively looks like the best bet, need to figure out the config options

Docstrings (@datapythonista I'm going to back you up whatever your opinion is on this one)
https://pypi.org/project/flake8-docstrings/  <-- wraps pydocstyle
https://pypi.org/project/flake8-rst-docstrings/  <-- wraps docutils

Misc
https://pypi.org/project/flake8-self/  <-- check for private variable access
https://pypi.org/project/flake8-pep3101/  <-- old-style string formatting (514 hits ATM)
https://pypi.org/project/flake8-builtins/    <-- check for overriding built-in names
https://pypi.org/project/flake8-comprehensions/  <-- list/set/dict comprehensions (or do we already lint for that well enough?)

**Comment by mroeschke** [comment]
+1 for flake8-comprehensions. Would close #18464 and replace some ad hoc regexes to check for unnecessary comprehensions.

**Comment by jbrockmendel** [comment]
We've pushed pretty far down this road, and have been implementing custom linting for a while.  Is there anything else to do here, or closeable?

**Comment by MarcoGorelli** [comment]
IMO this can be closed, any extra plugins can be discussed individually
