### ISSUE TITLE
Wrong output on DataFrame.groupby min() max()

### ISSUE THREAD

**Issue by feldbergs** [pandas-dev/pandas#20586]
#### Code Sample, a copy-pastable example if possible

```python
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}
df = pd.DataFrame(data)

df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

df.groupby('Company').max()

Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340  # WRONG OUTPUT! Number 340 is correct but Person Vanessa is wrong. 

df.groupby('Company').min()

          Person  Sales
Company
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124 # WRONG OUTPUT! Number 124 is correct but Person Amy is wrong. 
```
#### Problem description
On the output of DataFrame.groupby().max() and min() the Sales numbers are correct, but they're matched up with wrong person.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.22.0
pytest: 3.3.2
pip: 9.0.1
setuptools: 38.4.0
Cython: 0.27.3
numpy: 1.14.0
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.6.6
patsy: 0.5.0
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.1.2
openpyxl: 2.4.10
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.1
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
I think you've misunderstood what `max` and `min` are doing. They're applied column-wise, and `Vanessa` is greater than `Amy`.

I suspect you want something like

```python
In [29]: df.groupby("Company").apply(lambda x: x.nlargest(1, columns='Sales')[['Person', 'Sales']])
Out[29]:
          Person  Sales
Company
FB      5  Sarah    350
GOOG    0    Sam    200
MSFT    2    Amy    340
```

**Comment by feldbergs** [comment]
You're right. I'm sorry.
