### ISSUE TITLE
CI: Add lgtm.com integration to pull requests

### ISSUE THREAD

**Issue by jschendel** [pandas-dev/pandas#20589]
Seems like [lgtm.com](https://lgtm.com) integration could be useful.  Was helpful in identifying an obscure potential issue fixed in #20563, and I've used it to find a couple other minor things.

Looks like both numpy and scikit-learn are using it as well.  Not sure exactly what their experience with it has been, but at the very least scikit-learn has kept it around for a while now.

**Comment by gfyoung** [comment]
Haven't used it before, but could be interesting to look into!  Perhaps a brief outline of the benefits (and how it has helped you previously) would be good.

**Comment by jhelie** [comment]
Hi @jschendel and @gfyoung and thanks for your interest in LGTM! I am one of LGTM devs and a big user of pandas so would love for you to give it a go.

In a nutshell: what sets us apart is our query language technology [QL](https://lgtm.com/help/ql/about-ql) that allows us to find complex issues with a low false positive rate. You can write your own queries in QL to look for anything you might be interested (see for instance [here](https://lgtm.com/help/ql/python/pointsto-type-infer) for a tutorial on points-to analysis).

At the moment PR integration means the standard set of queries is run but you can [customise](https://lgtm.com/help/lgtm/configuring-lgtm-analysis-project) what is analysed and turn queries on and off. And very soon it will be possible to add custom queries to the PR checks.

In addition to scikit-learn and numpy, matplotlib is also using it - and I hope scipy will join soon too :)

I see @jschendel has already been using lgtm.com but I'm happy to answer any questions you have!

**Comment by jbrockmendel** [comment]
Is this worth pursuing?

**Comment by mroeschke** [comment]
Looks like this never gained much traction. Going to close due to the staleness but happy to revive if there's continued interest
