### ISSUE TITLE
Potential bug in remove_var? 

### ISSUE THREAD

**Issue by jl45621** [pandas-dev/pandas#20609]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
cdef inline void remove_var(double val, double *nobs, double *mean_x,
                            double *ssqdm_x) nogil:
    """ remove a value from the var calc """
    cdef double delta

    # Not NaN
    if val == val:
        nobs[0] = nobs[0] - 1
        if nobs[0]:
            # a part of Welford's method for the online variance-calculation
            # https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance
            delta = val - mean_x[0]
            mean_x[0] = mean_x[0] - delta / nobs[0]
            ssqdm_x[0] = ssqdm_x[0] - ((nobs[0] + 1) * delta ** 2) / nobs[0]
        else:
            mean_x[0] = 0
ssqdm_x[0] = 0


nobs is a pointer to a double and is incremented and decrement accordingly as add_var and remove_var are called. if nobs == 0, then you want to reset mean_x and ssqdm_x to 0 as you do in the else condition. my question is this -- isn't it possible that nobs could be some epsilon value and not exactly equal to 0.0 ? I dont know floating point math that well, and it could be fine since all we do is incrememt by1 or decrement by 1 so it could be fine. just wondering in case this should be:
if abs(nbos[0]) < 1e-11 or something

thanks


```
#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by jl45621** [comment]
nobs is a pointer to a double and is incremented and decrement accordingly as add_var and remove_var are called. if nobs == 0, then you want to reset mean_x and ssqdm_x to 0 as you do in the else condition. my question is this -- isn't it possible that nobs could be some epsilon value and not exactly equal to 0.0 ? I dont know floating point math that well, and it could be fine since all we do is incrememt by1 or decrement by 1 so it could be fine. just wondering in case this should be:
if abs(nbos[0]) < 1e-11 or something

thanks

**Comment by chris-b1** [comment]
This seems to be fine, it appears that `nobs` is only ever incremented / decremented by whole integers.  I'm not deeply familiar with this code, but we are most likely using a double instead of an int here to prevent having to cast `nobs` when it is used in fp division - this is some old code that was carefully optimized long ago.

Please re-open if you see a case where this causes a problem, thanks for taking a look.
