### ISSUE TITLE
ExtensionArray isin

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#20617]
Some (many?) extension array *scalar* types will have a corresponding *container* type. For example,  `IPArray` defines `isin` to match the standard library's behavior where an address can be in a network.

https://github.com/ContinuumIO/cyberpandas/blob/054d3a37fe84a8d222795c31bbf99ef34be90fbf/cyberpandas/ip_array.py#L349-L388

Do we want to dispatch `isin` to Extension arrays? https://github.com/pandas-dev/pandas/pull/20522 is doing some work so that `pd.core.algos(categorical)` dispatches to a specialized (faster) `.isin`, so the additional work will be small.

**Comment by TomAugspurger** [comment]
@ma3axaka if you want to take a look at this, it should be pretty straightforward now that you did #20522.

**Comment by ma3axaka** [comment]
Sure. I will look at this.

**Comment by jbrockmendel** [comment]
I think of `ser.isin(vals)` as effectively `Series([any(x == y for y in vals) for x in ser], index=ser.index)`.  IIUC the IPArray example would have a pretty different semantic meaning, wouldn't it?

**Comment by jbrockmendel** [comment]
There is now an ExtensionArray.isin; closing.
