### ISSUE TITLE
Segfault calling ohlc on column-wise groupby 

### ISSUE THREAD

**Issue by carolemieux** [pandas-dev/pandas#20626]
#### Code Sample, a copy-pastable example if possible

```python
y = pd.DataFrame([1,2])
y.groupby(y.columns, axis=1).ohlc()
```
causes
```
Segmentation fault: 11
```

#### Problem description

Calling ohlc after column-wise groupby on a dataframe with more than one row causes a segfault. 

#### Expected Output

Not a segfault. Probably something like:

```
     0
  open high low close
0    1    2   1     2
```

#### Output of ``pd.show_versions()``

<details>

------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Darwin
OS-release: 15.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: None
pip: 9.0.3
setuptools: 39.0.1
Cython: None
numpy: 1.14.2
scipy: None
pyarrow: None
xarray: None
IPython: 6.3.0
sphinx: None
patsy: None
dateutil: 2.7.2
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
ok, want to have a look where things are going wrong?

**Comment by mroeschke** [comment]
FWIW, this works properly on Python 2.7

```
In [1]: y = pd.DataFrame([1,2])

In [2]: y.groupby(y.columns, axis=1).ohlc()
Out[2]:
     0
  open high low close
0    1    2   1     2

In [3]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.14.final.0
python-bits: 64
OS: Darwin
OS-release: 17.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.22.0
pytest: 3.4.0
pip: 9.0.3
setuptools: 38.5.2
Cython: None
numpy: 1.14.2
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 5.5.0
sphinx: None
patsy: None
dateutil: 2.7.2
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.1.0
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: 1.2.0
pymysql: None
psycopg2: 2.7.3.2 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
```

**Comment by mapehe** [comment]
It seems that the segfault is caused by `values` and `label` having different lengths here. I wasn't able to find out why that happens though.
https://github.com/pandas-dev/pandas/blob/2794474334cbd53315c248b605953579d010c693/pandas/core/groupby/groupby.py#L2540-L2542

**Comment by carolemieux** [comment]
The code above no longer causes a segfault for pandas 0.23.4 on Python 3.7.2. Assuming fixed.

Full versions:
<details>
commit: None
python: 3.7.2.final.0
python-bits: 64
OS: Darwin
OS-release: 15.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 3.7.4
pip: 10.0.1
setuptools: 40.2.0
Cython: 0.28.5
numpy: 1.15.1
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.5.0
sphinx: 1.7.8
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 2.2.3
openpyxl: 2.5.6
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.1.0
lxml: 4.2.4
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.11
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>
