### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous.

### ISSUE THREAD

**Issue by saxaholic** [pandas-dev/pandas#20622]
```python
            if (self.index_label and
                    isinstance(self.index_label, (list, tuple, np.ndarray,
                                                  Index))):
```
#### Problem description

self.index_label can be an array, list, Index or tuple, but boolean values of arrays are ambiguous. Should be changed to 

            if (self.index_label is not None and
                    isinstance(self.index_label, (list, tuple, np.ndarray,
                                                  Index))):

#### Expected Output

Formatted excel cell

#### Output of ``pandas/io/formats/excel.get_formatted_cells``

<details>
 in get_formatted_cells
    yield cell
 in _format_hierarchical_rows
    if (self.index_label and isinstance(self.index_label, (list, tuple, np.ndarray, Index))):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

</details>

**Comment by TomAugspurger** [comment]
Can you provide a copy-pastable code-snippet that produces an error?

What version of pandas?

**Comment by saxaholic** [comment]
dataFrame.index.values is a tuple

`    def DF2Excel(self, dataFrame, filename='output.xlsx'):
        writer = ExcelWriter(filename)
        names = dataFrame.index.values
        dataFrame.to_excel(writer,index_label=names,merge_cells=False)
        writer.save()`

**Comment by TomAugspurger** [comment]
See http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports for tips on writing a reproducible example. Let us know if you can provide one.
