### ISSUE TITLE
Will inplace save memory by avoiding x2?

### ISSUE THREAD

**Issue by enfeizhan** [pandas-dev/pandas#20639]
Hope this is the place to ask the developers this question directly. Always wondering which way saves memory. As an example, we use dropna:
```
df.drop('col', inplace=True, axis=1)
```
or
```
df = df.drop('col', axis=1)
```

**Comment by jreback** [comment]
no inplace creates a new copy then assigns the pointer 

these are equivalent from a memory perspective

**Comment by markroxor** [comment]
So effectively `inplace` reduces the extra step and that's the only difference? No gain in terms of resources used? @jreback
