### ISSUE TITLE
Handling NAs in aggregation

### ISSUE THREAD

**Issue by apnewberry** [pandas-dev/pandas#20631]
In pandas 0.22.0, 

```
import pandas as pd
import numpy as np
pd.Series([1.0, np.nan]).sum()
```
gives

```
1.0
```

This is dangerous behavior in data analysis. Users often do want to drop NA values, and having to specify `dropna=True` manually may be annoying, but doing it by default is fraught. 

Could this be an option -- perhaps  `pandas.set_option('warn_drop_na', True)`? The user may drop NAs consciously beforehand, or explicitly during the operation, if they want this behavior without a warning. 

For comparison:

In R,

```
> sum(c(1.0, NA))
[1] NA
> sum(c(1.0, NA), na.rm=TRUE)
[1] 1
```

The SQL specification says,

> If one or more null values are eliminated, then a completion condition is raised: warning- null value eliminated in set function.

**Comment by jreback** [comment]
this default has been with pandas since its inception and is probably one of the reasons it’s so friendly. returning na constantly would be quite annoying.

**Comment by apnewberry** [comment]
@jreback Apologies -- I'm asking for an option to issue a warning when that happens -- not to change the default behavior. I've edited my post to clarify my intent. Does this stand more of a chance?

**Comment by apnewberry** [comment]
The warning would be in line with the SQL standard, I think.

**Comment by jreback** [comment]
no this would be worse
an option so that users on different systems might have different results - not great

you are missing the point of what pandas does with missing values 


these propagate by default except on aggregations

s + s2

yields nan if either is nan
