### ISSUE TITLE
BUG: .at/.iat and Series.__setitem__ do not upcast int to float

### ISSUE THREAD

**Issue by jschendel** [pandas-dev/pandas#20643]
#### Code Sample, a copy-pastable example if possible
`Series.at` doesn't upcast to float:
```python
In [2]: s = pd.Series([0, 1, 2], index=list('abc'))

In [3]: s.at['b'] = 2.7

In [4]: s
Out[4]:
a    0
b    2
c    2
dtype: int64
```
`Series.iat` doesn't upcast to float:
```python
In [5]: s = pd.Series([0, 1, 2], index=list('abc'))

In [6]: s.iat[1] = 3.1

In [7]: s
Out[7]:
a    0
b    3
c    2
dtype: int64
```
`Series.__setitem__` doesn't upcast to float:
```python
In [8]: s = pd.Series([0, 1, 2], index=list('abc'))

In [9]: s[1] = 5.5

In [10]: s
Out[10]:
a    0
b    5
c    2
dtype: int64
```

Same story for `DataFrame.at` and `DataFrame.iat`:
```python
In [11]: df = pd.DataFrame({'A': [0, 1, 2]}, index=list('abc'))

In [12]: df.at['b', 'A'] = 3.14

In [13]: df
Out[13]:
   A
a  0
b  3
c  2

In [14]: df.iat[1, 0] = 7.77

In [15]: df
Out[15]:
   A
a  0
b  7
c  2
```

Note that `loc` and `iloc` do upcast to float for both `Series` and `DataFrame`:
```python
In [16]: s = pd.Series([0, 1, 2], index=list('abc'))

In [17]: s.loc['b'] = 2.7

In [18]: s
Out[18]:
a    0.0
b    2.7
c    2.0
dtype: float64

In [19]: df = pd.DataFrame({'A': [0, 1, 2]}, index=list('abc'))

In [20]: df.iloc[0, 0] = 5.5

In [21]: df
Out[21]:
     A
a  5.5
b  1.0
c  2.0
```
#### Problem description
`Series.at`, `Series.iat`, `Series.__setitem__`, `DataFrame.at`, and `DataFrame.iat` do not upcast integer data to float.

#### Expected Output
I'd expect the values of the `Series`/`DataFrame` to be upcast to float in all scenarios mentioned.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: e8f206d8192b409bc39da1ba1b2c5bcd8b65cc9f
python: 3.6.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.0.dev0+735.ge8f206d
pytest: 3.1.2
pip: 9.0.1
setuptools: 39.0.1
Cython: 0.25.2
numpy: 1.13.3
scipy: 1.0.0
pyarrow: 0.6.0
xarray: 0.9.6
IPython: 6.1.0
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: None
tables: 3.4.2
numexpr: 2.6.4
feather: 0.4.0
matplotlib: 2.0.2
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 0.9.8
lxml: 3.8.0
bs4: None
html5lib: 0.999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: 0.1.0
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by gfyoung** [comment]
Hmm...that does seem a little odd.  We should have consistency.

**Comment by srinivasreddy** [comment]
i would like to take this.

**Comment by gfyoung** [comment]
Go for it!

**Comment by jimmywan** [comment]
Note that this also affects what happens when you try to set a value to `None`:
```python
>>> s = pd.Series([0, 1, 2], index=list('abc'))
>>>  s.iat[0] = 5
>>> s
a    5
b    1
c    2
dtype: int64
```

Setting a value to `None` via `.iat` fails because `None` is not a valid value for an `int64` and it won't upcast.
```python
>>> s.iat[0] = None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "MYINSTALLDIR/site-packages/pandas/core/indexing.py", line 1886, in __setitem__
    self.obj._set_value(*key, takeable=self._takeable)
  File "MYINSTALLDIR/site-packages/pandas/core/series.py", line 965, in _set_value
    self._values[label] = value
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Setitng a value to `None` via `.iloc` succeeds because it will upcast to `float64`.
```python
>>> s.iloc[0] = None
>>> s
a    NaN
b    1.0
c    2.0
dtype: float64
```

**Comment by jbrockmendel** [comment]
This looks like it is working now, could use test
