### ISSUE TITLE
Drop If syntax

### ISSUE THREAD

**Issue by jseabold** [pandas-dev/pandas#2064]
Maybe there's already a way to do this, and there's certainly a safer and more robust/full-featured way to do this, but I just monkey-patched my DataFrames to have a dropif method because I got tired of typing.

```
def dropif(self, col, cond):
    return self.ix[~eval("self['%s']"%col +cond)]
```

In the spirit of Stata's drop and keep commands.

**Comment by petehuang** [comment]
A `dropif` functionality was presented in 0.13.0 via `DataFrame.query`. Should we close this issue?

Also tagging in @jreback for a more currently active maintainer:

**Comment by bashtage** [comment]
Is this still relevant?

**Comment by jreback** [comment]
pretty idiomatic
```
In [15]: df.loc[~((df.A > 0) & (df.E < 0))]
```
