### ISSUE TITLE
DataFrame.replace with dict behaves inconsistently for integers and strings

### ISSUE THREAD

**Issue by Coldsp33d** [pandas-dev/pandas#20656]
From [SO](https://stackoverflow.com/q/49775130/4909087)

DataFrame.replace does not behave consistently when replacing integers vs replacing strings.

Reproducible example:
```
df = pd.DataFrame({'A': [0, 1]})
df.A.replace({0: 1, 1: 0})
```
This yields the result:

````
    df
    A
    1
    0
````

However, when using the same commands for string values

````
df = pd.DataFrame({'B': ['a', 'b']})
df.B.replace({'a': 'b', 'b': 'a'})
````
This gives

````
df
B
a
a
````

But it should give

````
B
b
a

````

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.0.final.0
python-bits: 64
OS: Darwin
OS-release: 17.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: None
pip: 9.0.3
setuptools: 38.5.1
Cython: 0.28.1
numpy: 1.14.0
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: 2.6.4
feather: None
matplotlib: 2.1.2
openpyxl: None
xlrd: 0.9.4
xlwt: None
xlsxwriter: None
lxml: 3.8.0
bs4: 4.6.0
html5lib: 1.0b8
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by gfyoung** [comment]
@Coldsp33d : That is weird indeed.  PR to patch is welcome!

**Comment by Licht-T** [comment]
Same problem happens in `regex` mode, but we need much refactor to fix everything (https://github.com/Licht-T/pandas/commit/a1d141bd4f84ed0982fd4e983a1f4dd84abd4cc9). @gfyoung, is it okay to patch only *normal* `replace` for now?

**Comment by gfyoung** [comment]
Yeah, that's fine.

**Comment by peterpanmj** [comment]
@Licht-T Is there an issue for ``regex`` replace similar to this one ?

**Comment by peterpanmj** [comment]
@Licht-T I am working on this issue and I can solve for replace with string. Still, Regex replace is not solved. Maybe you can open another issue for regex replace. I think it takes more efforts to solve that.
