### ISSUE TITLE
BUG: Categorical.take and Series([Categorical]).take is inconsistent with other dtypes

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#20664]
Related to https://github.com/pandas-dev/pandas/pull/20582 and https://github.com/pandas-dev/pandas/issues/20640

`Categorical.take` does not do any bounds checking, so produces wrong results:

```
In [9]: cat = pd.Categorical(['a', 'b', 'a'])

In [12]: cat.take([3])
Out[12]: 
[0]                       # <--------- non-sensical result (produces invalid Categorical), should error instead
Categories (2, object): [a, b]

In [10]: cat.take([-1])
Out[10]: 
[NaN]                      # <--------- this is correct
Categories (2, object): [a, b]

In [15]: cat[:0].take([0])
Out[15]: 
[a]                             # <--------- should also error
Categories (2, object): [a, b]
```

`Series.take` with categorical data does not follow the numpy behaviour of "-1" (starting from end):

```
In [22]: s = pd.Series(cat)

In [24]: s.take([-1])
Out[24]: 
2    NaN            # <--------- wrongly NaN, because it dispatches to `Categorical.take` which returns this
dtype: category
Categories (2, object): [a, b]

In [25]: s.astype(object).take([-1])
astype
Out[25]: 
2    a
dtype: object
```

**Comment by jorisvandenbossche** [comment]
(at least the Series.take part is a regression from 0.20)

**Comment by TomAugspurger** [comment]
FYI, I'm working on this. Will have a PR tonight hopefully.

**Comment by TomAugspurger** [comment]
Ok, will make a PR once https://github.com/pandas-dev/pandas/pull/20814 is merged. One point to clarify, we only want to warn when the user passes negative values, correct?

```python
cat = pd.Categorical(['a', 'b'])
cat.take([0, -1])  # FutureWarning
cat.take([0, 1])  # no warning
```

**Comment by jorisvandenbossche** [comment]
> One point to clarify, we only want to warn when the user passes negative values, correct?

Yes. (I don't think there is any change in behaviour for the other case?)

**Comment by jorisvandenbossche** [comment]
Personally, I would even consider breaking it without deprecation (would people really use this?), but either is fine.
