### ISSUE TITLE
astype(str) does not cast to string when using future package in Python2.7

### ISSUE THREAD

**Issue by kdebrab** [pandas-dev/pandas#20682]
*Note: This issue only occurs in Python 2, and does not occur in Python 3.*

#### Problem description

```python
import pandas as pd
ser = pd.Series([1,7,3])
ser.astype(str).map(type)
```
returns (correctly):
```
0    <type 'str'>
1    <type 'str'>
2    <type 'str'>
dtype: object
```
However, when importing str from builtins (requires pip install future, used for Py2/Py3 compatibility, see http://python-future.org/compatible_idioms.html), then `astype(str)` doesn't cast anymore:
```
from builtins import str
ser.astype(str).map(type)
```
returns (in Python 2.7):
```
0    <type 'long'>
1    <type 'long'>
2    <type 'long'>
dtype: object
```

#### Expected Output

For comparision, the following works correctly:
```
from builtins import str
ser.map(str).map(type)
ser.apply(str).map(type)
```
which returns in Python2.7 correctly (twice):
```
0    <class 'future.types.newstr.newstr'>
1    <class 'future.types.newstr.newstr'>
2    <class 'future.types.newstr.newstr'>
dtype: object
```

I would expect the same output when using `astype(str)` as compared to `map(str)` or `apply(str)`.

As a sidenote, using `astype('str')` instead of `astype(str)` is not a solution as that casts to the (non-compatible) 'str' type:
```
from builtins import str
ser.astype('str').map(type)
```
```
0    <type 'str'>
1    <type 'str'>
2    <type 'str'>
dtype: object
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 32
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.22.0
pytest: None
pip: 9.0.3
setuptools: 36.4.0
Cython: None
numpy: 1.14.1
scipy: 1.0.0
pyarrow: None
xarray: 0.10.0
IPython: 5.3.0
sphinx: 1.6.3
patsy: 0.5.0
dateutil: 2.6.1
pytz: 2018.3
blosc: None
bottleneck: 1.2.1
tables: None
numexpr: None
feather: None
matplotlib: 2.1.2
openpyxl: 2.5.0
xlrd: 1.0.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.1
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.2.3
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
I suppose we might have some overly strict checks for this. You are welcome to submit a fix.

**Comment by mroeschke** [comment]
Closing as we dont support Python 2 anymore
