### ISSUE TITLE
get_dummies(dummy_na=True) treats int like float when creating dummy names

### ISSUE THREAD

**Issue by superxiao** [pandas-dev/pandas#20693]
`pd.get_dummies(pd.DataFrame({"id":[1,2,3]}), columns=["id"], dummy_na=True)`
will produce

| |id_1.0   | id_2.0   |  id_3.0  |   id_nan 
---|---|---|---|---
 0  |  1| 0| 0  | 0  
1 | 0  |1   |0   |0
  2| 0  |0   |1   |0

Which creates different column names from `pd.get_dummies(pd.DataFrame({"id":[1,2,3]}), columns=["id"])`

| |id_1   | id_2   |  id_3  |    
---|---|---|---|
 0  |  1| 0| 0  |   
1 | 0  |1   |0   |
  2| 0  |0   |1   |

It looks that this line
https://github.com/pandas-dev/pandas/blob/6c0c27730fb5b20978824fb380449cd3acef55f7/pandas/core/reshape/reshape.py#L909

converts the int array into float array because of `np.nan`.

**Comment by bobhaffner** [comment]
Hi @superxiao, it looks ok to me.   Both lines produce dataframes with all dtypes being `uint8`

I'm running 0.22.0

Please paste the output of `pd.show_verions()` like instructed below

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by gfyoung** [comment]
@superxiao : I supposed we could always cast to a non-numeric `dtype` to prevent this.

@bobhaffner : This looks like regression to me then.

**Comment by gfyoung** [comment]
@bobhaffner : I get the same result as @superxiao on `0.22`.

**Comment by bobhaffner** [comment]
@gfyoung Ok, yeah, I understand now that the title has changed.  I was looking at the values themselves and not the column names

**Comment by psinger** [comment]
Encountering the same "issue", any idea how to prevent this?

**Comment by gfyoung** [comment]
Not sure ATM.  The only workarounds I can think of:

1) Don't pass in `dummy_na=True`

2) Manually "convert" your columns after the fact.

🙁

**Comment by cjavier70** [comment]
Here's how I did the conversion....
