### ISSUE TITLE
Identity check fails even if two Series objects referring to same integer

### ISSUE THREAD

**Issue by ratnaparkhivivek10** [pandas-dev/pandas#20706]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
>>> a = pd.Series(data=[1,2,3])
>>> b = pd.Series(data=a, copy=False)
>>> 
>>> id(a[0])
1647956885080
>>> id(b[0])
1647956885080
>>> 
>>> id(a[0]) == id(b[0])
True
>>> 
>>> a[0] is b[0]
False
>>> 
```
#### Problem description
If both the series objects referring to the same integer object then upon checking identity with ```is```, it should return ```True```.

#### Expected Output
```
>>> a[0] is b[0]
True
```
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: English_United States.1252

pandas: 0.21.1
pytest: None
pip: 9.0.3
setuptools: 39.0.1
Cython: None
numpy: 1.14.2
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: 2.5.1
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: 4.2.0
bs4: 4.6.0
html5lib: 0.9999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by TomAugspurger** [comment]
https://stackoverflow.com/questions/306313/is-operator-behaves-unexpectedly-with-integers

**Comment by TomAugspurger** [comment]
`__getitem__` may return numpy.int64 objects, but the same idea applies. You should only use `is` for things like `None` and booleans.

**Comment by ratnaparkhivivek10** [comment]
Thanks @TomAugspurger for the information. Got more details from this thread: https://github.com/numpy/numpy/issues/10908
