### ISSUE TITLE
Installation of Latest Pandas 

### ISSUE THREAD

**Issue by jpoles1** [pandas-dev/pandas#20701]
I hope this is the right place to be posting this issue. I'm unsure if installation issues belong here, so if not I am sorry in advance.

Running `pip3 install --upgrade pandas` yields:

```
pdoc 0.3.2 has requirement markdown<2.5, but you'll have markdown 2.6.11 which is incompatible.
```

I am currently trying to upgrade from pandas 0.20.3 to the latest version using pip3 version 10.0.0. I have tried uninstalling markdown to allow pip to reinstall the proper version for pandas but then I get:

```
pdoc 0.3.2 requires markdown<2.5, which is not installed.
tensorboard 1.7.0 requires markdown>=2.6.8, which is not installed.
```

It seems like the dependencies for these two packages conflict.

**Comment by TomAugspurger** [comment]
Closing since this seems unlikely to be a pandas issue, but feel free to update.
