### ISSUE TITLE
DEPR: DatetimeIndex.offset

### ISSUE THREAD

**Issue by jschendel** [pandas-dev/pandas#20716]
`DatetimeIndex.offset` and `DatimeIndex.freq` refer to the same thing, and are used interchangeably throughout the code for `DatetimeIndex`:

https://github.com/pandas-dev/pandas/blob/4a344972722cc3c27250cbc8e382472b13e66bde/pandas/core/indexes/datetimes.py#L1729-L1732

Is there a reason for having both?  

`TimedeltaIndex` and `PeriodIndex` only have `freq`, so it seems like we could keep `freq` for consistency, deprecate `DatetimeIndex.offset`, and modify the `DatetimeIndex` code to only use `freq`.

**Comment by jorisvandenbossche** [comment]
+1 to deprecate `.offset` (will probably need some rework, as now it is `freq` that is calling `offset` which is used internally it seems)

**Comment by jreback** [comment]
note we deprecated ``Timestamp.offset`` in #13593

**Comment by subhrm** [comment]
If no one has started working on this, I would like to take this up.

**Comment by jschendel** [comment]
@subhrm : I've started some work on this as a precursor to fixes for #20678

**Comment by subhrm** [comment]
@jschendel Okay.
