### ISSUE TITLE
TST: failure on s3 mocking

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#20720]
master seems to fail recently: https://travis-ci.org/pandas-dev/pandas/jobs/367585545

on ``pandas/tests/iotest_parquet.py -k s3``.

works locally for me. very odd as this is mocked and shouldn't ever have a connection error.

In particular xfailing:  https://github.com/pandas-dev/pandas/commit/336fba7c0191444c3328009e6d4f9f5d00ee224b
- [ ] ``test_read_csv_chunked_download`` in ``pandas.tests.io.test_network.py``
- [ ] ``test_s3_roundtrip`` for fp & pyarrow in ``pandas.testsio.test_parquet.py``

**Comment by jreback** [comment]
@TomAugspurger any idea?

**Comment by TomAugspurger** [comment]
cc @mdurant, have you been dealing with moto / requests issues recently?

**Comment by martindurant** [comment]
The references issue causes anything based on requests to fail following the use of moto in some cases. In this particular case, though, the test **is** using moto, right?

The following fixed the problem with requests: https://github.com/dask/dask/blob/master/dask/bytes/tests/test_s3.py#L46

**Comment by spulec** [comment]
Hi all; I'm one of the maintainers of Moto.

Our most recent version had a regex bug in catching certain S3 urls to patch. We are releasing a new version in the next couple minutes that should resolve any issues (`1.3.3`).

Feel free to ping me if these issues don't seem to go away.

**Comment by jreback** [comment]
thanks @spulec!

**Comment by TomAugspurger** [comment]
Thanks @spulec, I can confirm that upgrading to 1.3.3 fixed things for me locally!

We still have some failures on our CI, though I *think* that this is fully pandas problem now: https://travis-ci.org/TomAugspurger/pandas/jobs/369087870. Working on it now.

**Comment by spulec** [comment]
Okay, let me know if it does end up pointing back to Moto.

**Comment by csolamx** [comment]
Hi @spulec!  I installed 1.3.5 today and it seems that it's mocking any requests not belonging to AWS.  Are there other updates to consider or workarounds?

Thanks!

**Comment by spulec** [comment]
@csolamx feel free to follow along at https://github.com/spulec/moto/issues/1567
