### ISSUE TITLE
Cannot read datetime columns back in from JSON with convert_dates

### ISSUE THREAD

**Issue by mhearne-usgs** [pandas-dev/pandas#20737]
#### Code Sample, a copy-pastable example if possible

```python
from datetime import datetime
import pandas as pd
import numpy as np

d = {'Time': [datetime(1900, 1, 1), datetime(2000, 1, 1)],
     'ID': ['thing1', 'thing2'],
     'Number': np.array([12.34, 25.67])}
df = pd.DataFrame(d)
print(df['Time'].dtype)
jstr = df.to_json()
df2 = pd.read_json(jstr, convert_dates=['Time'])
print(df2['Time'].dtype)

```
#### Problem description

I tried this with the most recent version of pandas available via conda (0.22.0), and I
get this result:

datetime64[ns]
int64

#### Expected Output
datetime64[ns]
datetime64[ns]
 (basically, I expect pandas to convert Time back to a time datatype)
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.5.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: None
pip: 9.0.1
setuptools: 38.5.2
Cython: None
numpy: 1.11.3
scipy: 0.17.1
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.0.0rc2
openpyxl: 2.5.0
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.5
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by mhearne-usgs** [comment]
Update: this works if you add date_format='iso' to the to_json() method call.

**Comment by jreback** [comment]
this is well documented; standard json is not a round tripp’s able format 

format=‘table’ is however (new on 0.23)
