### ISSUE TITLE
DOC: wiki testing page still refers to nose

### ISSUE THREAD

**Issue by mattip** [pandas-dev/pandas#20740]
On the wiki https://github.com/pandas-dev/pandas/wiki/Testing seems to need an update for the `pytest` testing framework.

**Comment by jorisvandenbossche** [comment]
Yes, that page should be updated. But, I think in general we should check if there is still content in there that is not in http://pandas-docs.github.io/pandas-docs-travis/contributing.html#test-driven-development-code-writing, and move that content over there.

**Comment by jreback** [comment]
dupe of #20501
