### ISSUE TITLE
A problem with pandas.read_sas

### ISSUE THREAD

**Issue by webbedfeet** [pandas-dev/pandas#20751]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd
d = pd.read_sas('lex1_3.sas7bdat')
```
#### Problem description

For a few sas7bdat files, which can be read in R with `haven::read_sas`, the pandas version either gives a segmentation fault or an AttributeError with the message "'bool' object has no attribute 'sum'"

#### Expected Output
A pandas DataFrame
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Darwin
OS-release: 17.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: 3.0.7
pip: 9.0.1
setuptools: 39.0.1
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
pyarrow: None
xarray: None
IPython: 5.3.0
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.3.0
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.8
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.3
bs4: 4.6.0
html5lib: 0.999
sqlalchemy: 1.1.9
pymysql: 0.7.9.None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.5.0

</details>

**Comment by jreback** [comment]
this is not reproducible

**Comment by jreback** [comment]
if you can provide a repro then someone could have a look
