### ISSUE TITLE
Index changes during pandas.Dataframe.merge()

### ISSUE THREAD

**Issue by sursu** [pandas-dev/pandas#20758]
I have 2 data frames:

```
df1 = pd.DataFrame({'A':[11,2,31,4,51],
                    'B':[1.2,3.14,1.41,1.7,2.2],
                    'C':['e','w','q','q','s']})
df1.set_index('A', inplace=True)
df1
```

A | B | C 
 -- | -- | --
11 | 1.20 | e
2 | 3.14 | w
31 | 1.41 | q
4 | 1.70 | q
51 | 2.20 | s

and

```
df2 = pd.DataFrame({'C':['e','w','q','s'],
                    'AB':[11,1.2,31,5.9],
                    'CAM':['A',1.2,'-',5.9]})
df2.set_index('C', inplace=True)
df2
```

C | AB | CAM
-- | -- | --
e | 11.0 | A
w | 1.2 | 1.2
q | 31.0 | -
s | 5.9 | 5.9

Notice: `'C'` is a column in `df1` and index in `df2`.

Now, merge these 2 data frames as shown next

`df1.merge(df2, left_on='C', right_index=True, how='left')`

Out:

A | B | C | AB | CAM
-- | -- | -- | -- | --
11 | 1.20 | e | 11.0 | A
2 | 3.14 | w | 1.2 | 1.2
31 | 1.41 | q | 31.0 | -
4 | 1.70 | q | 31.0 | -
51 | 2.20 | s | 5.9 | 5.9

Very much what one would expect.

Let's look at another instance, when `'C'` is a column in `df2` and not an index. 
To get there, reset the index: 
`df2.reset_index(inplace=True)`

and merge again:
`df1.merge(df2, on='C', how='left')`

Out:

 _   | B | C | AB | CAM
-- | -- | -- | -- | --
0 | 1.20 | e | 11.0 | A
1 | 3.14 | w | 1.2 | 1.2
2 | 1.41 | q | 31.0 | -
3 | 1.70 | q | 31.0 | -
4 | 2.20 | s | 5.9 | 5.9

#### Question: Why does the index change?
Isn't it sensical it to remain unchanged?

**Comment by jreback** [comment]
so [14] is just sugar for [15], so this makes sense. 
```
In [14]: df1.merge(df2.reset_index(), on='C', how='left')
Out[14]: 
      B  C    AB  CAM
0  1.20  e  11.0    A
1  3.14  w   1.2  1.2
2  1.41  q  31.0    -
3  1.70  q  31.0    -
4  2.20  s   5.9  5.9

In [15]: pd.merge(df1, df2.reset_index(), on='C', how='left')
Out[15]: 
      B  C    AB  CAM
0  1.20  e  11.0    A
1  3.14  w   1.2  1.2
2  1.41  q  31.0    -
3  1.70  q  31.0    -
4  2.20  s   5.9  5.9
```

**Comment by sursu** [comment]
What?
@jreback you must be tired, you just closed an issue with an amiss comment.
Please read carefully the question again, because from where I look, what is happening there is plain stupid.

If you don't think I have exposed the issue properly, here is from another user, on stackoverflow:
[How to keep index when using pandas merge[(https://stackoverflow.com/questions/11976503/how-to-keep-index-when-using-pandas-merge)

I cannot agree more with the first comment there:
> This has to be in the top 10 dumbest things about pandas... ...why would losing the index ever make sense? – Corone

**Comment by sursu** [comment]
@jreback Please reopen this issue. It is not resolved. If you think that it need not be resolved, why do you think so?

**Comment by sursu** [comment]
What is a non-meaningful index?

**Comment by TomAugspurger** [comment]
Something coming from the default range(N) index, but maybe filtered,
reordered, etc.

**Comment by sursu** [comment]
So, you are saying that 
`df1.merge(df2, left_on='C', right_index=True, how='left')`
changes the index of `df1` because its index is non-meaningful. You suspect so, right?

I don't see why the first case would preserve the index then.

Also, the documentation just describes the behavior which has been observed. It does not explain why it has to be like this. It should, I think, especially when it is non-intuitive. 
An example would do the job.

**Comment by TomAugspurger** [comment]
Agreed that an improved docstring would be nice. Do you have time to submit
a PR updating the documentation? One of the examples from
http://pandas.pydata.org/pandas-docs/version/0.23/merging.html#brief-primer-on-merge-methods-relational-algebra
could likely be adapted.

**Comment by sursu** [comment]
@TomAugspurger I would gladly, but I still think it is not being done satisfactorily.
None of the examples give a suitable explanation.

**Comment by TomAugspurger** [comment]
Right, a new one would have to be written to specifically demonstrate this.
