### ISSUE TITLE
Internal error when self joining DataFrame that has category column with null value

### ISSUE THREAD

**Issue by msalib** [pandas-dev/pandas#20763]
#### Code Sample, a copy-pastable example if possible

```import io
import pandas as pd
q=pd.read_csv(io.BytesIO(b'A5215,'), names=['l', 'c']).astype(dict(c='category'))
q.join(q.set_index('l'), on='l', how='inner', lsuffix='_A')
```
#### Problem description

This code doesn't raise exceptions but it does print these error messages:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
ValueError: Buffer dtype mismatch, expected 'Python object' but got 'double'
Exception ValueError: "Buffer dtype mismatch, expected 'Python object' but got 'double'" in 'pandas._libs.lib.is_bool_array' ignored
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
ValueError: Buffer dtype mismatch, expected 'Python object' but got 'double'
Exception ValueError: "Buffer dtype mismatch, expected 'Python object' but got 'double'" in 'pandas._libs.lib.is_bool_array' ignored
```

The documentation doesn't indicate that this functionality is unsupported.

#### Expected Output

It should not print the error message

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.14.final.0
python-bits: 64
OS: Linux
OS-release: 4.13.0-36-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.22.0
pytest: 3.4.2
pip: 9.0.1
setuptools: 38.4.0
Cython: None
numpy: 1.14.1
scipy: 1.0.0
pyarrow: None
xarray: 0.10.0
IPython: 5.5.0
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: None
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.1.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999999999
sqlalchemy: None
pymysql: None
psycopg2: 2.7.3.2 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: 0.1.4
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
This runs without an exception for me with pandas master.

```python
In [2]: import io

In [3]: import pandas as pd
   ...: q=pd.read_csv(io.BytesIO(b'A5215,'), names=['l', 'c']).astype(dict(c='category'))
   ...: q.join(q.set_index('l'), on='l', how='inner', lsuffix='_A')
   ...:
Out[3]:
       l c_A   c
0  A5215 NaN NaN

```

Can you try it out on master? We're doing a release in the next couple weeks.

**Comment by TomAugspurger** [comment]
Let us know if it's still failing with the latest version.
