### ISSUE TITLE
Pandas installation on arm architectures

### ISSUE THREAD

**Issue by Davidnet** [pandas-dev/pandas#20771]
#### Code Sample, a copy-pastable example if possible
I Haven't written any custom code.
#### Problem description
I'm trying to install Pandas with pip install pandas, and I'am encountering the following error:

```bash
nvidia@tegra-ubuntu:~/opt$ sudo -H pip install pandas
Collecting pandas
  Using cached https://files.pythonhosted.org/packages/08/01/803834bc8a4e708aedebb133095a88a4dad9f45bbaf5ad777d2bea543c7e/pandas-0.22.0.tar.gz
  Could not find a version that satisfies the requirement Cython (from versions: )
No matching distribution found for Cython
```
At first I tried to install Cython, then installing pandas, but the same behavior is encountered, my platfrom is arm-64 and is currently my bottleneck to develop.

```
$pip --version
```

**Comment by Davidnet** [comment]
I have found the error, new pip version with 10 requires dependencies in binary from instead of source compiling, unfortunately is a feature not a bug, it is resolved by returning to pip 9

**Comment by jorisvandenbossche** [comment]
Yes, this is indeed a problem with the new pip version. You can also pass the flag `--no-build-isolation` to use pip 10.

**Comment by jorisvandenbossche** [comment]
Closing as a duplicate of https://github.com/pandas-dev/pandas/issues/20775
