### ISSUE TITLE
Shift method doesn't keep data type

### ISSUE THREAD

**Issue by enfeizhan** [pandas-dev/pandas#20774]
#### Code Sample, a copy-pastable example if possible

```
df = pd.DataFrame([1, 2])
df.dtypes
0    int64
dtype: object
df.shift(-1).dtypes
0    float64
dtype: object
```
#### Problem description
After shifting the integer data type turns into float. I understand this is for incorporating na value as a result of shifting.

However, can we have a fillna parameter so na won't appear and therefore data type can stay as is?

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.13.0-38-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_AU.UTF-8
LOCALE: en_AU.UTF-8

pandas: 0.22.0
pytest: None
pip: 9.0.3
setuptools: 39.0.1
Cython: None
numpy: 1.14.2
scipy: 1.0.1
pyarrow: None
xarray: None
IPython: 6.3.0
sphinx: 1.7.2
patsy: 0.5.0
dateutil: 2.7.2
pytz: 2018.3
blosc: None
bottleneck: None
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
you would need to ``.fillna`` after if you want .
