### ISSUE TITLE
DOC: clean Index.set_name / .rename doc-strings

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#20787]
xref #20548 

MultiIndex.rename directly uses the .set_names doc-string (which is ok), but should be a touch more linked (e.g. See Also, maybe some more examples). Alt could de-couple these and make them more informative.

**Comment by jreback** [comment]
cc @arminv

**Comment by nmusolino** [comment]
Perhaps you meant to cross-reference issue #17334 ?

**Comment by VincentLa** [comment]
I can try working on this!
