### ISSUE TITLE
heap corruption in read_csv on 32-bit big-endian architectures

### ISSUE THREAD

**Issue by ginggs** [pandas-dev/pandas#20785]
While building pandas 0.22.0 for 32-bit big-endian architectures, the test suite crashes in **TestMultiLevel::test_unstack_odd_failure** with various errors:
```
realloc(): invalid next size
malloc(): smallbin double linked list corrupted
Segmentation fault
corrupted double-linked list
```
This happened to be the first test that calls **read_csv**, and I could reproduce this in the REPL by simply doing:
```
import pandas as pd
df = pd.read_csv('data.csv')
```
I narrowed it down to https://github.com/pandas-dev/pandas/commit/8d7d3fb545b4273cf9d1a61bf7ea3bfdde8a1199 and found https://github.com/pandas-dev/pandas/issues/17063 describing a similar problem introduced by the same commit affecting other 32-bit architectures.

**Comment by jreback** [comment]
you could submit a patch, but we have 0 support for big endian (no testing) and very little for 32-but arch (limited testing)
