### ISSUE TITLE
Make itertuples really an iterator/generator in implementation, not just return type

### ISSUE THREAD

**Issue by mitar** [pandas-dev/pandas#20783]
`itertuples` is not really an iterator/generator and constructs a copy of whole DataFrame in memory. Ideally it would return just an iterator and construct row by row as it is being iterated over.

**Comment by mitar** [comment]
That's just because you return a `zip`. But inside the function, you create whole list of values first. See [here](https://github.com/pandas-dev/pandas/blob/3e691a4cba566472bef03ef9bbaec701498670e1/pandas/core/frame.py#L826):

```
arrays.extend(self.iloc[:, k] for k in range(len(self.columns)))
```

It looks like iterator because of `zip(*arrays)`, but `arrays` is not an iterator. This is a problem.

**Comment by mitar** [comment]
You can test the issue here by doing:

```python
d = pandas.DataFrame({'a': range(100000000)})
for a in d.itertuples(index=False, name=None):
    print(a)
```

Do this in Python interpreter. Note the time it takes to create `d`. Now, when you press enter after `print` line, twice, note the time it takes to start producing anything. It takes this time because it is first creating all rows in memory, before iterating over them.

**Comment by jreback** [comment]
and if u want to fix it pls submit a PR
this is truly an iterator 

so what u describe is an implementation detail

**Comment by mitar** [comment]
Implementation detail which blows up memory and performance?

Anything can be made look like iterator. But if does not really behave like iterator, it is not an iterator.

I think this is a bug. Please reopen this. And then me or somebody else can make a pull request.

**Comment by mitar** [comment]
This goes even deeper. Also iterating over a series constructs a list internally:

```python
d = pandas.DataFrame({'a': range(100000000)})
for a in d['a']:
    print(a)
```

This will also have a large delay before starting sending results back.

**Comment by jorisvandenbossche** [comment]
I agree that ideally it would be more lazy the iteration (although not really a priority issue for me), and since we would accept a PR to fix, let's keep the issue open.

**Comment by jorisvandenbossche** [comment]
I agree that ideally it would be more lazy the iteration (although not really a priority issue for me), and since we would accept a PR to fix, let's keep the issue open.

**Comment by jreback** [comment]
@mitar you are welcome to submit a PR, however, this method follows exactly the pandas paradigm. We create a new copy of things then hand it back to you, here the handing back is an iterator. If you can optimize this, great, but you are fighting standard practice. Further you may slow things down by doing this in the common case.

**Comment by TomAugspurger** [comment]
This would be a welcome fix if possible.

@mitar one thing to watch out for, which we just hit with `Categorical.__iter__`. We need to watch two things

- Scalars have to be converted from NumPy scalars to Python scalars
- We need to avoid tons of calls to `Series/Frame.__getitem__`, as this is relatively slow

**Comment by mitar** [comment]
I made: #20796

**Comment by mitar** [comment]
> We need to avoid tons of calls to Series/Frame.__getitem__, as this is relatively slow

Calling `iloc` is OK? Or is this the same slow as `__getitem__`?

**Comment by mitar** [comment]
I think that the PR #20796 is ready to be reviewed.
