### ISSUE TITLE
Redshift IO Module

### ISSUE THREAD

**Issue by davidgasquez** [pandas-dev/pandas#20804]
Hey there! I've been working with Redshift for a long time now and I was wondering if it would make sense to add a `redshift` IO module in Pandas. 

Right now, I'm using a custom package that is adding a couple of methods to Pandas `DataFrame` class. That said, I would love to contributo te Pandas doing this an official way to interact with Redshift similar to [`gbq.py`](https://github.com/pandas-dev/pandas/blob/master/pandas/io/gbq.py).

Let me know if this makes sense and I'll work on it! :smiley:

**Comment by TomAugspurger** [comment]
This is probably out of scope for pandas. We don't have anything special for any other SQL flavors, and I don't think we really want to go special case anything / try to support everything.
