### ISSUE TITLE
A map method to work with many columns

### ISSUE THREAD

**Issue by oricou** [pandas-dev/pandas#20807]
Hi,

I would like to map a function expecting N arguments to a DataFrame of N columns. Today to do that I do:

```python
df = pd.DataFrame({"A": [1, 2, 3, 4], "B": [5, 6, 7, 8]})
def f(x,y):
     return x*y

df[['A', 'B']].apply(lambda x: f(*x), axis=1) 
```
So the `map` method for DataFrame would be:

```python
def map(self, f):
    return self.apply(lambda x: f(*x), axis=1)
```
if I am right. Then `df.map(f)` would produce a Serie.

Note that with 1 colummn and a 1 argument function `map` would work as `numpy.map` does.

Thanks,

Olivier.

ps: I edited this post after the talk I had with Tom, so it must seem strange now :smiley:

**Comment by TomAugspurger** [comment]
That would break compatibility.

**Comment by oricou** [comment]
What!? Is that a magic answer to close issues? I am sorry but you should explain how it would break compatibility and as far as I know breaking compatibility has been done before.

From my understanding all previous code will still work if you *add* this feature.

**Comment by TomAugspurger** [comment]
> and as far as I know breaking compatibility has been done before.

Sorry, I posted before finishing my comment. It'd break compat and I don't see the benefit. Could you maybe explain a bit further what you're trying to achieve with a runnable example?

> From my understanding all previous code will still work if you add this feature.

How would that be? Currently the function passed to `f` expects a column or row as it's first argument. With your proposal it would have to expect a positional argument for each row or column. Or am I misunderstanding?

**Comment by TomAugspurger** [comment]
For example, suppose we had

```python
In [10]: df = pd.DataFrame({"A": [1, 2, 3, 4], "B": [5, 6, 7, 8]})

In [11]: def f(row):
    ...:     return row.A * row.B
 ```

IIUC (which I may not) your proposal would break the following

```python
In [12]: df.apply(f, axis=1)
Out[12]:
0     5
1    12
2    21
3    32
dtype: int64
```

Since `f` would be called with two arguments instead of 1.

**Comment by oricou** [comment]
I want to apply a 2 arguments function to 2 columns of my DataFrame. As you said `apply` expect a vector (a column or a row) which means the function given to apply should have one argument. Imagine you have functions with N arguments and you want to map it on all the rows for the N columns you have selected. The best way I have found to do that is the use of a lambda function to call my function (as explained in my first post).

Now thinking about it, it may be more logic to use `map` instead of `apply` to do what I want. Map a function expecting N arguments to N columns would run row by row the function with the N values. It would behave the same than map with a 1 argument function applied to a Serie.

Example: 

```pyhon

df = pd.DataFrame({'A':[1,2], 'B':[3,4]})
df.apply(lambda x,y: x+2*y, axis=1)   # does not work

# what about having?
df.map(lambda x,y: x+2*y)
```

Since `map` does not exist for DataFrame, you are not going to break anything.

**Comment by oricou** [comment]
About your example, `apply` would detect that `f` expect 1 argument and there it would behave as it does now.

**Comment by TomAugspurger** [comment]
Thanks for the clarification. Perhaps you could update your original post with your new proposal.

> Since map does not exist for DataFrame, you are not going to break anything.

Indeed, this would be preferable. Then we'll have to decide whether the additional method is worth implementing, & maintaining. Especially since your workaround is relatively straightforward.

> About your example, apply would detect that f expect 1 argument and there it would behave as it does now.

In general, we try to avoid magic behavior like this. It often leads to surprising / difficult to debug behavior in unanticipated cases.

**Comment by oricou** [comment]
ok, I update the original post

**Comment by oricou** [comment]
BTW I think my workaround is not that easy, it implies you know *x and understand apply and axis. Many users know how to use `numpy.map` and would understand `df.map(f)` but not beeing to do my workaround.

**Comment by mroeschke** [comment]
Thanks for the suggestion but it appears this features hasn't had much interest from the core devs and community over the years so closing. Can reopen if there's renewed interest
