### ISSUE TITLE
TST: Cleanup tests/indexes/test_base.py

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#20812]
This module could use some major refactoring. Approach outlined with checkboxes below - will add or modify as we go through:

- [X] Parametrize the existing module where appropriate
    - [X] Pass 1: #20624
    - [X] Pass 2: #20813
    - [X] Pass 3: #20931
    - [X] Pass 4: #20979
- [ ] Replace any class methods / attributes with fixtures where appropriate
- [ ] Move tests into new modules / sub-modules (ex: https://github.com/pandas-dev/pandas/pull/20624#discussion_r180617229, https://github.com/pandas-dev/pandas/pull/20624#discussion_r180617681, https://github.com/pandas-dev/pandas/pull/20931#discussion_r185675690)
- [ ] Add fixture for fill arguments (see https://github.com/pandas-dev/pandas/pull/20931#discussion_r185675215)

**Comment by jbrockmendel** [comment]
All the PRs linked in the OP are merged, and I've done several passes on this file since then too.  Closing.
