### ISSUE TITLE
Established Standards for Tests

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#20820]
xref https://github.com/pandas-dev/pandas/pull/20813#discussion_r183850580 there is some inconsistency with how tests are built which we could standardize and cleanup. For example, all of the following may appear in any given test:

```python
# Short variable name notation
res = 'foo'
exp = 'bar'
assert res == exp

# Evaluation as operand
exp = 'bar'
assert some_func() == exp

# Full variable name notation
result = 'foo'
expected = 'bar'
assert result == expected
```

There are of course many more combinations in between but the above should cover the concept. With the assumption that the last is preferable, the proposal here is to explicitly document that somewhere (perhaps TESTING_README.md?) and beyond that perhaps set up LINTing rules to enforce the standard.

Thoughts?

**Comment by jbrockmendel** [comment]
Listing this sounds hard.  I think there is enough cleanup needed in tests in general that this is a non-issue.
