### ISSUE TITLE
Pandas problem    .str.replace

### ISSUE THREAD

**Issue by Object-v** [pandas-dev/pandas#20836]
Sample:
TempInfo = pd.DataFrame({'value': ['4', '1', '3', '2','9','11','5','10','14','7','13','12','8','6','15','unknown'],'Id': ['4.0','1.0','3.0','2.0','9.0','11.0','5.0','10.0','14.0','7.0','13.0','12.0','8.0','6.0','15.0','unknown']})
TempInfo
         Id    value
0       4.0        4
1       1.0        1
2       3.0        3
3       2.0        2
4       9.0        9
5      11.0       11
6       5.0        5
7      10.0       10
8      14.0       14
9       7.0        7
10     13.0       13
11     12.0       12
12      8.0        8
13      6.0        6
14     15.0       15
15  unknown  unknown

TempInfo['Id'] = TempInfo['Id'].str.replace(".0","")

TempInfo
         Id    value
0         4        4
1         1        1
2         3        3
3         2        2
4         9        9
5        11       11
6         5        5
7                 10
8        14       14
9         7        7
10       13       13
11       12       12
12        8        8
13        6        6
14       15       15
15  unknown  unknown

I just want to replace .0 why 0. was also replaced

**Comment by pybern** [comment]
Hi Object-v,

If you refer to the docs [here](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.str.replace.html), the string is replaced based on the regex pattern, and not the string literal, you can refer to more about python's regex pattern [here](https://docs.python.org/3.6/library/re.html).

Try running this, where "\.0" basically matches exactly just ".0".

`import pandas as pd

TempInfo = pd.DataFrame({'value'
                             : ['4', '1', '3', '2','9','11','5','10','14','7','13','12','8','6','15','unknown']
                         ,'Id': 
                         ['4.0','1.0','3.0','2.0','9.0','11.0','5.0','10.0','14.0','7.0','13.0','12.0','8.0','6.0','15.0'
                          ,'unknown']})

TempInfo['Id_replace'] = TempInfo['Id'].str.replace("\.0","")

TempInfo`

**Comment by Object-v** [comment]
Thank s  pybern ,
