### ISSUE TITLE
REF: Simplify JoinUnit.is_na for categorical

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#20833]
In JoinUnit.is_na we get the categories

https://github.com/pandas-dev/pandas/blob/6cacdde5630c593999059833b516e1fec60aaf72/pandas/core/internals.py#L5782-L5783

and then check if they're all not na. Categories can't have NA in them, so we can just return False (I think).

**Comment by jbrockmendel** [comment]
the categories cant have NAs, but the codes can have -1s
