### ISSUE TITLE
request for to_elastic method 

### ISSUE THREAD

**Issue by shantanuo** [pandas-dev/pandas#20838]
#### Problem description
There is to_csv or to_sql method. Since elasticsearch is an important database, I will request for to_elastic method. It is possible to import a module and export dataframe data to elasticsearch, but a native method will be useful.

#### Expected Output
to_elastic method built-in

**Comment by pybern** [comment]
Have you explored the [Python Elasticsearch API](https://elasticsearch-py.readthedocs.io/en/master/)?

I remember that it was quite intuitive to use pandas to_json and then the API to load export the dataframes.

**Comment by mroeschke** [comment]
Closing as it would be too niche for the pandas API.
