### ISSUE TITLE
str.cat inconsistent for CategoricalIndex

### ISSUE THREAD

**Issue by h-vetinari** [pandas-dev/pandas#20842]
The `str.cat`-accessor works for CategoricalIndex as target, but not as caller. This is inconsistent.

```
a = pd.Index(['a', 'b', 'a'])
b = pd.Index(['a', 'b', 'a'], dtype='category')
a.str.cat(b)
# Index(['aa', 'bb', 'aa'], dtype='object')
b.str.cat(a)
# AttributeError: Can only use .str accessor with string values (i.e. inferred_type is 'string', 'unicode' or 'mixed')
```

**Comment by WillAyd** [comment]
Why wouldn't you just rename your categories?

**Comment by h-vetinari** [comment]
@WillAyd 
this was just a toy example - if there's more to concatenate, it gets more unwieldy. Your argument could be similarly extended to argue why users should just work directly on numpy arrays - however, pandas functions often as an organisational layer and better user interface.

But more than that, it makes no sense that `a.str.cat(b)` works, but `b.str.cat(a)` doesn't.

**Comment by h-vetinari** [comment]
@WillAyd 
this was just a toy example - if there's more to concatenate, it gets more unwieldy. But more than that, it makes no sense that `a.str.cat(b)` works, but `b.str.cat(a)` doesn't.
