### ISSUE TITLE
Unexpected SettingWithCopyWarning after dropna() 

### ISSUE THREAD

**Issue by bobhaffner** [pandas-dev/pandas#20856]
I got an interesting one here regarding `SettingWithoutCopyWarning`

Scenario 1 (no issues)
```python
In [1]: import pandas as pd

In [2]: import numpy as np

In [3]: df_nans = pd.DataFrame({'A' : [1, np.nan], 'B' : [3, 6]})

In [4]: df_nans = df_nans.dropna()

In [5]: df_nans.__dict__
Out[5]: 
{'is_copy': <weakref at 0x1119b8c28; dead>, '_data': BlockManager
 Items: Index(['A', 'B'], dtype='object')
 Axis 1: Int64Index([0], dtype='int64')
 FloatBlock: slice(0, 1, 1), 1 x 1, dtype: float64
 IntBlock: slice(1, 2, 1), 1 x 1, dtype: int64, '_item_cache': {}}

In [6]: df_nans['C'] = 1
```

Scenario 2 (SettingWithoutCopyWarning).  

```
In [7]: df_nans_warning = pd.DataFrame({'A' : [1, np.nan], 'B' : [3, 6]})

In [8]: df_nans_warning  # the difference between the scenarios
Out[8]: 
     A  B
0  1.0  3
1  NaN  6

In [9]: df_nans_warning = df_nans_warning.dropna()

In [10]: df_nans_warning.__dict__
Out[10]: 
{'is_copy': <weakref at 0x111a58bd8; to 'DataFrame' at 0x1119efa58>,
 '_data': BlockManager
 Items: Index(['A', 'B'], dtype='object')
 Axis 1: Int64Index([0], dtype='int64')
 FloatBlock: slice(0, 1, 1), 1 x 1, dtype: float64
 IntBlock: slice(1, 2, 1), 1 x 1, dtype: int64,
 '_item_cache': {}}

In [11]: df_nans_warning['C'] = 1
/Users/bob/miniconda3/envs/data36/bin/ipython:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  #!/Users/bob/miniconda3/envs/data36/bin/python

```

The only difference between the scenarios is `[8]` where I output the DataFrame and the resulting __dict__ items prior to assignment of `C`

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: 3.5.0
pip: 9.0.3
setuptools: 39.0.1
Cython: None
numpy: 1.14.2
scipy: 1.0.1
pyarrow: None
xarray: None
IPython: 6.3.1
sphinx: 1.7.2
patsy: 0.5.0
dateutil: 2.7.2
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: 1.2.6
pymysql: None
psycopg2: 2.7.4 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: 0.1.5
pandas_gbq: None
pandas_datareader: None
</details>

Note: Same behavior exists in `'0.23.0.dev0+807.g563a6ad10.dirty'`

**Comment by jreback** [comment]
dropna is a filter operation so this is exactly like the doc examples
and is expected

you need to either copy or set the column first

**Comment by bobhaffner** [comment]
Although I understand what you mean, I was surprised that one scenario didn't produce the warning and the other did even though they're similar.

**Comment by TomAugspurger** [comment]
Is this because IPython stores a reference to all the variables in the Out dictionary?

**Comment by bobhaffner** [comment]
Yeah, perhaps.  I can recreate it on the REPL too.  It's a weird one

```
(data36) Bobs-MacBook-Pro:~ bob$ python
Python 3.6.4 |Anaconda, Inc.| (default, Mar 12 2018, 20:05:31) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> import numpy as np
>>> df_nans_warning = pd.DataFrame({'A' : [1, np.nan], 'B' : [3, 6]})
>>> df_nans_warning = df_nans_warning.dropna()
>>> df_nans_warning['C'] = 1
>>>
>>>
>>> df_nans_warning = pd.DataFrame({'A' : [1, np.nan], 'B' : [3, 6]})
>>> df_nans_warning  # the difference between the scenarios
     A  B
0  1.0  3
1  NaN  6
>>> df_nans_warning = df_nans_warning.dropna()
>>> df_nans_warning['C'] = 1
__main__:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
```

**Comment by TomAugspurger** [comment]
The regular repl stores just the last output. Can you add another output before doing the operation?

________________________________

**Comment by bobhaffner** [comment]
LIke this?   

Didn't get a warning this way

```
>>> df_nans_warning = pd.DataFrame({'A' : [1, np.nan], 'B' : [3, 6]})
>>> df_nans_warning 
     A  B
0  1.0  3
1  NaN  6
>>> df_nans_warning = df_nans_warning.dropna()
>>> df_nans_warning
     A  B
0  1.0  3
>>> df_nans_warning['C'] = 1
>>> 
```
