### ISSUE TITLE
What are these guys doing with this line?

### ISSUE THREAD

**Issue by xguse** [pandas-dev/pandas#20853]
I am using a pipeline that seems like it has not been updated in a while and when I run it in a modern environment with a modern pandas I get an exception that traces to this line:

```
grouped = series[series].groupby(level=level)
```

The lowest error is: 
```
File "pandas/_libs/src/inference.pyx", line 1581, in pandas._libs.lib.tuples_to_object_array
ValueError: Buffer dtype mismatch, expected 'Python object' but got 'double'
```

They tell me just to use a much 'older version of Anaconda'. This makes me suspect that the original author is gone and they are scared to touch anything bc they don't understand the code...

Can anyone help me understand what in the world they are doing in that line? I have never seen a series sliced with it's own object. What does that even mean?

**Comment by TomAugspurger** [comment]
Hard to say without a reproducible example. That should be roughly like `series.loc[series.values]`.

If you suspect this is a regression from a previous behavior then try to put together a reproducible example (http://stackoverflow.com/help/mcve). Otherwise, stackoverflow is the place to go fro general questions.

**Comment by michcio1234** [comment]
@xguse, maybe this will be helpful: `series[series]` is useful for selecting only True values of a boolean series.

**Comment by xguse** [comment]
Thank to both you guys.

@michcio1234: yeah I just realized that that would be a potential use for this over the weekend. That obj  IS a series of `bool` objs too.

And I will hit up SO next time. Sorry about that.
