### ISSUE TITLE
Problem Compiling Docs using make.py 

### ISSUE THREAD

**Issue by ThiviyanThanapalasingam** [pandas-dev/pandas#20862]
When there is a space in the name of a parent directory, make.py fails to run. 

```
$ python make.py html
```

This is the output of the command: 
```
usage: sphinx-build [OPTIONS] SOURCEDIR OUTPUTDIR [FILENAMES...]
sphinx-build: error: cannot find source directory (/Users/usr/Documents/Pandas Sprint/pandas/doc/Sprint/pandas/doc/build/doctrees)
```

However, when after removing the space from the directory name (i.e. change 'Pandas Sprint' to 'PandasSprint') the python script executed as expected. 

Hope this helps. 
Thiviyan

**Comment by ThiviyanThanapalasingam** [comment]
Thank you @jorisvandenbossche. I seem to have solved the issue by modifying 3 lines of code. As this will be my first contribution towards the Pandas project I am struggling to write a git commit message that can be readily understood by the community. Would the following message be fine?

**DOC: Fix whitespace in pathnames issue by wrapping paths with quotes (#20862)**

**Comment by jorisvandenbossche** [comment]
@ThiviyanThanapalasingam That sounds good!

**Comment by jorisvandenbossche** [comment]
Closed by https://github.com/pandas-dev/pandas/pull/20880
