### ISSUE TITLE
Docs Style: quoting paramter names in prose

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#20879]
Single or double backticks?

We use single for docstrings.

In the HTML rendering, single goes to italics. Double goes to code-formatting.

**Comment by WillAyd** [comment]
I'm +1 on single backticks - I think the look of italics rendered for these just flows better. Having a lot of code-formatting just for parameter references is distracting

**Comment by abi-aryan** [comment]
+1 on single backticks

**Comment by TomAugspurger** [comment]
We can fold this into https://github.com/pandas-dev/pandas/issues/19750
