### ISSUE TITLE
case sensitive merge

### ISSUE THREAD

**Issue by shantanuo** [pandas-dev/pandas#20896]
#### Problem description
By default Pandas merge method is case-sensitive.
There should be a way to merge 2 dataframes without considering upper/ lower case just like SQL joins.

#### Expected Output
May be a parameter case=True (default) that can be changed to case=False

**Comment by toobaz** [comment]
I don't think we want to get into this, for several reasons: in pandas (differently from SQL), column names are not necessarily strings; when possible, we want indexing to work the same everywhere (so we would need to support ``case=False`` in ``.loc``, ``concat`` too...); I guess we don't want to overload the API with ad hoc parameters that are easy to emulate (``df.rename({l : l.lower() for l in df}, axis=1``).

**Comment by TomAugspurger** [comment]
Was the proposal for case-insensitive merges on the column names, or on the values? Could you show an example @shantanuo could you clarify? If it's on the values, does calling `str.lower()` on both frames first suite your neds?

**Comment by shantanuo** [comment]
>> Was the proposal for case-insensitive merges on the column names, or on the values? 
on the values.

>> does calling str.lower() on both frames first suite your needs?
It does. But I thought having a parameter for this would be elegant.

**Comment by toobaz** [comment]
> on the values.

I might have misunderstood. Could you show an example?

**Comment by shantanuo** [comment]
https://stackoverflow.com/questions/45519132/merge-method-compared-with-sql-query

I guess case is not important when we compare 2 columns for merging. There should be an option (built-in) to disable case-sensitivity.

**Comment by TomAugspurger** [comment]
> It does. But I thought having a parameter for this would be elegant.

I'd prefer to keep things from getting too complex right now. I would like to see a small library that implements this, along with fuzzy joins, similar to http://varianceexplained.org/fuzzyjoin/

**Comment by toobaz** [comment]
> https://stackoverflow.com/questions/45519132/merge-method-compared-with-sql-query

Right, the workaround suggested there is also simpler than mine

**Comment by shantanuo** [comment]
I guess it should be mentioned in the documentation somewhere so that developers time can be saved.

**Comment by TomAugspurger** [comment]
Sure. Added a couple sentences to doc/source/merging.rst explaining that
would be welcome. Do you have time to make a pull request?

**Comment by Ekillz** [comment]
Comment on the official pandas.merge page would be even better.

**Comment by TomAugspurger** [comment]
Sure, and we're able to link between the two pages. Can you make a PR?

**Comment by SaneshmonSabu** [comment]
What if I want to retain former cases after merging? str.lower would require at least one side to be in lower case. 

What I am trying to achieve - merge "Pandas" with "PANDAS"
