### ISSUE TITLE
Pandas .assign function is consuming a lot of memory.

### ISSUE THREAD

**Issue by arslanhashmi** [pandas-dev/pandas#20894]
#### Code Sample, a copy-pastable example if possible

```python
    def add_attribute(self, new_attribute, condition_column, categories, category, code):
        """
        This function adds new attribute with new values depends on the values in the condition column replaced
        with specific code.
        :param new_attribute: new attribute needs to be added
        :param condition_column: dependency of new attricute
        :param categories: categories data frame (diagrnosis/treatment)
        :param category: specific category
        :param code: icd9code for treatment, icd10code for diagnosis
        """
        print('Going to make new attribute: {}'.format(new_attribute))
        kwargs = {
            new_attribute: lambda x: self.data_frame[condition_column].loc[self.data_frame[condition_column].isin(
                list(categories[category][code].values)
            )].replace(
                list(categories[category][code].values),
                list(categories[category]['category'].values)
            )
        }
        self.data_frame = self.data_frame.assign(**kwargs)
```
#### Problem description
Sorry the code is a bit complex.
^^^ I am doing this for almost 150+ new attributes (columns) And with every new attribute the memory usage by the program increases badly.
Particularly it worked in Mac book with 8GB ram but in windows with 64GM ram it is throwing MemoryError.
Thanks in advance.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.20.3
pytest: None
pip: 9.0.1
setuptools: 28.8.0
Cython: None
numpy: 1.13.1
scipy: 0.19.1
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.0.2
openpyxl: None
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: None
bs4: 4.6.0
html5lib: 0.9999999
sqlalchemy: None
pymysql: None
psycopg2: 2.7.3.1 (dt dec pq3 ext lo64)
jinja2: None
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by jorisvandenbossche** [comment]
Please provide a self-contained, reproducible example. Also your title indicates "apply", but I assume you are actually talking about "assign"?

**Comment by arslanhashmi** [comment]
Thank you very much for replying, yes it is assign.
I call it like this 
self.add_attribute(
                new_attribute='ccs_p_01',
                condition_column='diagnosis_main_01',
                categories=categories_diagnosis,
                category='Diagnoses',
                code='icd10code'
            )
^^^ here categories_diagnosis is a dictionary of small data frames.
The problem is only with assign with time the memory usages increases drastically.

**Comment by jorisvandenbossche** [comment]
If you want us to help you, you will at least need to start with providing a minimal reproducible example (http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports): a code snippet that we can just run and shows your problem.

**Comment by arslanhashmi** [comment]
I see, you are right i know. But i can't share complete code and data sets i've used as the information is confidential. But i can explain as much as you want me to explain. 
I have a class which has a data_frame and this contains around 1-1.5 GB of data. I am using the above function .assign(**kwargs) to add a new row into the actual data frame. I am doing this more than 150 times, but with every new call the memory usage increases.(There are no intermediary processes/code)  
A more easy version/example
kwargs = {
           new_attribute: lambda x: self.data_frame[condition_column].loc[self.data_frame[condition_column].isin(
                [1,2,3,4,5...]
            )]
        }
        self.data_frame = self.data_frame.assign(**kwargs)

**Comment by arslanhashmi** [comment]
@jorisvandenbossche Here is a simple reproducible example.
`import io
import requests
import pandas as pd


def add_attribute(data_frame, new_attribute, continent):
    kwargs = {
        new_attribute: lambda x: data_frame['Region'].loc[data_frame['Region']==continent].replace(continent, 1)
    }
    return data_frame.assign(**kwargs)


url="https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
s=requests.get(url).content
continents_info=pd.read_csv(io.StringIO(s.decode('utf-8'))).set_index('Country')
continents_info = add_attribute(continents_info, 'AFRICAN_COUNTRIES', 'AFRICA')
continents_info = add_attribute(continents_info, 'SOUTH_AMERICA_COUNTRIES', 'SOUTH AMERICA')

`

**Comment by arslanhashmi** [comment]
``
