### ISSUE TITLE
TST: Additional tests for concat(sort) argument

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#20909]
Followup to https://github.com/pandas-dev/pandas/pull/20613

Ideally, we would specify this everywhere we use concat internally. In many contexts, it will be irrelevant since things should be already sorted & aligned.

Need to determine the old behavior, and then match that.

**Comment by TomAugspurger** [comment]
Also this comment on a refactor to simplify https://github.com/pandas-dev/pandas/pull/20613#discussion_r185144259 `_unique_indices`

**Comment by jorisvandenbossche** [comment]
One case where this warning pops up from the pandas internals is the following example in the docs (http://pandas-docs.github.io/pandas-docs-travis/basics.html#mixed-dtypes):

```
In [1]: In [167]: mdf = pd.DataFrame({'A': [1, 2, 3],
   ...:    .....:                     'B': [1., 2., 3.],
   ...:    .....:                     'C': ['foo', 'bar', 'baz'],
   ...:    .....:                     'D': pd.date_range('20130101', periods=3)})
   ...:                     

In [2]:  mdf.agg(['min', 'sum'])
/home/joris/scipy/pandas/pandas/core/base.py:611: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  return concat(results, keys=keys, axis=1)
Out[2]: 
     A    B          C          D
min  1  1.0        bar 2013-01-01
sum  6  6.0  foobarbaz        NaT
```

**Comment by TomAugspurger** [comment]
Thanks. Pushing a test / fix now.

**Comment by jorisvandenbossche** [comment]
There are some other warnings as well in the doc build, but it might be most of those are OK with a `:okwarning:` (which is not urgent as it is not shown in the actual html docs). Will go through them.

**Comment by jorisvandenbossche** [comment]
So I think the other warnings are OK, it's mainly from concatting two dataframes with eg columns "A B C D" and "C D E F", where sort=True or sort=False does not matter for the actual result (both give the same).

**Comment by TomAugspurger** [comment]
I think we've enforced this deprecation, so considering this closed.
