### ISSUE TITLE
Explicit signature for NDFrame.to_hdf

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#20903]
Currently we have `to_hdf(self, path_or_buf, key, **kwargs)`

It'd be good to replace that with the actual signature (unless I'm missing a reason for the current implementation) and document it fully.

**Comment by abi-aryan** [comment]
I would love to help. How can I get started on this?

**Comment by TomAugspurger** [comment]
Great! General contributing guidelines are at http://pandas-docs.github.io/pandas-docs-travis/contributing.html

For this specific one, I would look at `to_hdf` in `pandas/pandas/io/pytables.py`. Anywhere we pass `kwargs` currently (`store.append` and `store.put`) we'll need to figure out the correct set of keyword arguments expected. Some like `mode`, `format`, etc. will be straightforward. Others will take some digging. Let us know if you get stuck.

**Comment by abi-aryan** [comment]
Cool. On it now.

**Comment by jbrockmendel** [comment]
Closed by #29957.
