### ISSUE TITLE
Fix warnings catching with python2

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#20914]
#20770 [introduced](https://github.com/pandas-dev/pandas/commit/901fc641e7bcdaf285fb582b3e450498f4552fba) two ``skipif``s because some warnings (related to ``.loc`` being passed a list with missing labels on a ``MultiIndex``, which is supported but deprecated) would not be detected.

Oddly, whether the warnings are detected or not depends on how the tests are invoked: for instance, each of the two affected files runs just fine if pytest is called on it alone, and even if they are called together, but they fail instead when the entire suite is run.

Under Python 3, tests work just fine.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: c4da79b5b322c73d8e61d1cb98ac4ab1e2438b40
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-6-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.23.0.dev0+824.gc4da79b5b.dirty
pytest: 3.5.0
pip: 9.0.1
setuptools: 39.0.1
Cython: 0.25.2
numpy: 1.14.1
scipy: 0.19.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.5.6
patsy: 0.5.0
dateutil: 2.7.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.0dev
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.0
openpyxl: 2.3.0
xlrd: 1.0.0
xlwt: 1.3.0
xlsxwriter: 0.9.6
lxml: 4.1.1
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.2.1

</details>

**Comment by jbrockmendel** [comment]
Closable?

**Comment by TomAugspurger** [comment]
I believe
