### ISSUE TITLE
Int Index.slice_locs Not Raising with Float Arguments

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#20915]
xref #4892 as I'm going through #20812 I am seeing tests which suggest that trying to call `slice_locs` with float arguments against an integer type Index should raise a TypeError:

https://github.com/pandas-dev/pandas/blob/c4da79b5b322c73d8e61d1cb98ac4ab1e2438b40/pandas/tests/indexes/test_base.py#L1350

While these tests are currently passing, I believe the `TypeError` is getting raised from the call to `pytest.raises` (specifically a `'list' object is not callable` for the third argument to `pytest.raises`) and not as a result of the actual `index.slice_locs` call.  

```python
>>> pd.__version__
'0.23.0.dev0+824.gc4da79b5b.dirty'
>>> index = pd.Index(np.array([0, 1, 2, 5, 6, 7, 9, 10], dtype=int))
>>> index.slice_locs(5.0, 10.0)
(3, 8)
>>> index.slice_locs(4.5, 10.5)
(3, 8)
```

**Comment by simonjayhawkins** [comment]
the `TypeError` message was added in #4850

https://github.com/jreback/pandas/blob/60efe85bc2ce9578e8f5e0c88907c5cc6b6b7b31/pandas/core/index.py#L526-L531

and has since been removed. int slicing with floats is now allowed.
