### ISSUE TITLE
Please, add sharey keyword to boxplot.

### ISSUE THREAD

**Issue by soerendip** [pandas-dev/pandas#20918]
#### Code Sample, a copy-pastable example if possible

```python
df.groupby('some feature').boxplot(sharey=False)
```
#### Problem description

Boxplot by default creates plots with shared y axis. The keyword `sharey=False` is not accepted. However, it would be consistent with df.plot(). This is unfortunate if you don't want to compare values across the subplots. There is a workaround mentioned [here](https://stackoverflow.com/questions/40148830/different-ylim-for-shared-axes-in-pandas-boxplot), but having the option to turn that "feature" off would be much simpler.  

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-17134-Microsoft
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: None
pip: 9.0.3
setuptools: 39.0.1
Cython: None
numpy: 1.14.2
scipy: 1.0.1
pyarrow: None
xarray: None
IPython: 6.3.1
sphinx: None
patsy: 0.5.0
dateutil: 2.7.2
pytz: 2018.4
blosc: None
bottleneck: None
tables: 3.4.3
numexpr: 2.6.4
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.9999999
sqlalchemy: 1.2.7
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

​
</details>

**Comment by spizwhiz** [comment]
Agreed that this feature would be an excellent additon!  Thanks.

**Comment by soerendip** [comment]
I made some changes in the code seems to work. Now, I can pass `sharey` and `sharex` to `df.groupby().boxplot()` and change the behavior. `pytest` is running without errors. Now, I would like to make a pull request. How do I add my changes to the documentation? Do I add the documentation before or after the pull request?

And (how) would you generate a test for the feature?
