### ISSUE TITLE
BLD: Lint for invalid files in wheels / packages

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#20926]
We should be able to catch things like https://github.com/conda-forge/pandas-feedstock/pull/41#issuecomment-385981073 as part of our CI.

**Comment by jbrockmendel** [comment]
is this about linting we do at PR-time or at release-time or [...]?

**Comment by TomAugspurger** [comment]
PR time I think.

**Comment by mroeschke** [comment]
I think this should largely be handled once we have cibuildwheel in place https://github.com/pandas-dev/pandas/issues/44027 (PR: https://github.com/pandas-dev/pandas/pull/48283) which also tests the wheels so I think we can close this as falling under that issue
