### ISSUE TITLE
ParserError on read_table/read_csv while reading CSV file

### ISSUE THREAD

**Issue by fbrundu** [pandas-dev/pandas#20935]
#### Code Sample, a copy-pastable example if possible

```python
In [137]: probes = pd.read_csv('example_pandas.csv', sep=',', index_col=0)
---------------------------------------------------------------------------
ParserError                               Traceback (most recent call last)
<ipython-input-137-09d372dee9b1> in <module>()
----> 1 probes = pd.read_csv('./full_matrix/GEO_matrix/example_pandas.csv', sep=',', index_col=0)

~/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, skipfooter, skip_footer, doublequote, delim_whitespace, as_recarray, compact_ints, use_unsigned, low_memory, buffer_lines, memory_map, float_precision)
    707                     skip_blank_lines=skip_blank_lines)
    708
--> 709         return _read(filepath_or_buffer, kwds)
    710
    711     parser_f.__name__ = name

~/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    453
    454     try:
--> 455         data = parser.read(nrows)
    456     finally:
    457         parser.close()

~/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pandas/io/parsers.py in read(self, nrows)
   1067                 raise ValueError('skipfooter not supported for iteration')
   1068
-> 1069         ret = self._engine.read(nrows)
   1070
   1071         if self.options.get('as_recarray'):

~/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pandas/io/parsers.py in read(self, nrows)
   1837     def read(self, nrows=None):
   1838         try:
-> 1839             data = self._reader.read(nrows)
   1840         except StopIteration:
   1841             if self._first_chunk:

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.read()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_low_memory()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_rows()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._tokenize_rows()

pandas/_libs/parsers.pyx in pandas._libs.parsers.raise_parser_error()

ParserError: Error tokenizing data. C error: Expected 2 fields in line 3, saw 3
```
#### Problem description

I am getting this ParserError while trying to load a CSV file. I prepared a minimal example to reproduce this error.

[example_pandas.csv.zip](https://github.com/pandas-dev/pandas/files/1969094/example_pandas.csv.zip)

 I have the latest version of Pandas on macOS 10.13.2 (17C205) - High Sierra.

I checked the example and it seems the CSV has the correct format, but maybe the problem is in the CSV itself.

#### Expected Output

The expected output should be a dataframe with only one column (the first CSV column is used as index).

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Darwin
OS-release: 17.3.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: None
pip: 10.0.1
setuptools: 39.1.0
Cython: None
numpy: 1.14.3
scipy: 1.0.1
pyarrow: None
xarray: None
IPython: 6.3.1
sphinx: None
patsy: 0.5.0
dateutil: 2.7.2
pytz: 2018.4
blosc: None
bottleneck: None
tables: 3.4.3
numexpr: 2.6.4
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by WillAyd** [comment]
This is not a pandas issue - you are missing a double quote at the end of the second row of data

**Comment by fbrundu** [comment]
Thank you @WillAyd , since the delimiter was the comma ',' I didn't know it was the problem. So pandas expects a second quote if it finds the first, right? I didn't find this on the documentation.. Btw, learned a new thing, thanks.

**Comment by ashwinij123** [comment]
same problem how to sol pls tell me

**Comment by PyMarcus** [comment]
> same problem how to sol pls tell me

open your csv file with comma only, after that, you can save and run the script.

**Comment by Ernesto-Alves67** [comment]
I tried every thing above and still having the problem.

**Comment by rhshadrach** [comment]
@Ernesto-Alves67 - if you believe there is an issue with pandas, please open a new report with a minimal example demonstrating it. If you are not sure how to use pandas to achieve your goal, ask a question on StackOverflow.
