### ISSUE TITLE
unclear error with  read_sas

### ISSUE THREAD

**Issue by kelent** [pandas-dev/pandas#20940]
#### Problem description

I'm using read_sas() to read sas7bdat file into python, some SAS file works while some encounter the following error. The files works fine in SAS so I want to know why it happen when I read it in python.

ValueError                                Traceback (most recent call last)
pandas/io/sas/sas.pyx in pandas.io.sas._sas.rle_decompress()

ValueError: Unexpected non-zero end_of_first_byte
Exception ignored in: 'pandas.io.sas._sas.Parser.process_byte_array_with_data'
Traceback (most recent call last):
  File "pandas/io/sas/sas.pyx", line 29, in pandas.io.sas._sas.rle_decompress
ValueError: Unexpected non-zero end_of_first_byte
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
pandas/io/sas/sas.pyx in pandas.io.sas._sas.rle_decompress()

ValueError: Unexpected non-zero end_of_first_byte
Exception ignored in: 'pandas.io.sas._sas.Parser.process_byte_array_with_data'
Traceback (most recent call last):
  File "pandas/io/sas/sas.pyx", line 29, in pandas.io.sas._sas.rle_decompress
ValueError: Unexpected non-zero end_of_first_byte
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
pandas/io/sas/sas.pyx in pandas.io.sas._sas.rle_decompress()

ValueError: Unexpected non-zero end_of_first_byte
Exception ignored in: 'pandas.io.sas._sas.Parser.process_byte_array_with_data'
Traceback (most recent call last):
  File "pandas/io/sas/sas.pyx", line 29, in pandas.io.sas._sas.rle_decompress
ValueError: Unexpected non-zero end_of_first_byte
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
pandas/io/sas/sas.pyx in pandas.io.sas._sas.rle_decompress()

ValueError: Unexpected non-zero end_of_first_byte
Exception ignored in: 'pandas.io.sas._sas.Parser.process_byte_array_with_data'
Traceback (most recent call last):
  File "pandas/io/sas/sas.pyx", line 29, in pandas.io.sas._sas.rle_decompress
ValueError: Unexpected non-zero end_of_first_byte

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.22.0
pytest: 2.9.2
pip: 10.0.1
setuptools: 27.2.0
Cython: 0.24.1
numpy: 1.13.1
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: 5.1.0
sphinx: 1.4.6
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.2.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.3
lxml: 3.6.4
bs4: 4.5.1
html5lib: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by WillAyd** [comment]
Please be sure to check the contributing guidelines before submitting a bug - you need to provide a *minimally* reproducible example 

https://pandas.pydata.org/pandas-docs/stable/contributing.html#bug-reports-and-enhancement-requests

**Comment by Winand** [comment]
Does this file has deleted observations? see #15963

**Comment by WillAyd** [comment]
@Winand just looking at the error messages that appears unrelated. 

@kelent if you can provide a reproducible example as requested above please reopen this

**Comment by chaseschuette** [comment]
I've also encountered this. I have not yet figured out what's going on.
