### ISSUE TITLE
pd.read_sql does not handle queries that return nothing

### ISSUE THREAD

**Issue by klemnnain** [pandas-dev/pandas#20943]
#### Code Sample, a copy-pastable example if possible

```python
import sqlite3
import pandas as pd
conn = sqlite3.connect('tmp')
df = pd.DataFrame({'a': [0,1,2]})
df.to_sql('df', conn)
pd.read_sql('INSERT INTO df (a) VALUES  (3);', conn)   # query that returns nothing (no row, no column)



TypeError                                 Traceback (most recent call last)
<ipython-input-1-> in <module>()
      4 df = pd.DataFrame({'a': [0,1,2]})
      5 df.to_sql('df', conn)
----> 6 pd.read_sql('INSERT INTO df (a) VALUES  (3);', conn)

\anaconda2\lib\site-packages\pandas\io\sql.pyc in read_sql(sql, con, index_col, coerce_float, params, parse_dates, columns, chunksize)
    398             sql, index_col=index_col, params=params,
    399             coerce_float=coerce_float, parse_dates=parse_dates,
--> 400             chunksize=chunksize)
    401 
    402     try:

\anaconda2\lib\site-packages\pandas\io\sql.pyc in read_query(self, sql, index_col, coerce_float, params, parse_dates, chunksize)
   1438         args = _convert_params(sql, params)
   1439         cursor = self.execute(*args)
-> 1440         columns = [col_desc[0] for col_desc in cursor.description]
   1441 
   1442         if chunksize is not None:

TypeError: 'NoneType' object is not iterable
```
#### Problem description

The behaviour is non generic and caused a unexpected bug in my program forcing me to use an alternative to pd.read_sql to connect to db. 

#### Expected Output
Return None with no error 

#### Output of ``pd.show_versions()``
<details>

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 32
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.20.3
pytest: 3.2.1
pip: 9.0.1
setuptools: 36.5.0.post20170922
Cython: 0.26.1
numpy: 1.13.1
scipy: 0.19.1
xarray: None
IPython: 5.4.1
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 0.9.8
lxml: 3.8.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: 2.7.4 (dt dec pq3 ext)
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

If you confirm that this behaviour is unexpected and that a fix is needed, I would be very pleased to help 😃

**Comment by WillAyd** [comment]
`read_sql` is used to **read** data from tables so this is just not supported (nor should it be).

**Comment by TomAugspurger** [comment]
I tend to agree with @WillAyd. What's the reason not to use something like `conn.execute`?
