### ISSUE TITLE
Failure to install pandas 0.22.x from source because of numpy 1.9.3

### ISSUE THREAD

**Issue by miguelmorin** [pandas-dev/pandas#20952]
#### Code Sample, a copy-pastable example if possible

I pulled the source code for branch `0.22.x` from GitHub, installed X-code command-line tools and miniconda3, and followed the steps [here](http://pandas.pydata.org/pandas-docs/stable/contributing.html#contributiong-dev-python) to install pandas:

```bash
conda env create -f ci/environment-dev.yaml
conda activate pandas-dev

# Build and install pandas
python setup.py build_ext --inplace -j 4
python -m pip install -e .

```
#### Problem description

The last line of the bash command above gives this error:

```
  Could not find a version that satisfies the requirement numpy==1.9.3 (from versions: 1.11.3, 1.12.0rc2, 1.12.0, 1.12.1rc1, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3)
No matching distribution found for numpy==1.9.3
```

But the source code in the `master` branch works fine. I found issue #20697 and added ` - pip==0.9.3` to `ci/environment-dev.yaml`, and now it works (even though `master` does not have `pip`). I'll submit a pull request to close this issue.

I'm new here, so tell me if you prefer a workflow other than opening an issue and closing it with a pull request.

#### Expected Output

```
Obtaining file:///Users/mmorin/Software/pandas
Requirement already satisfied: ...
...
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

#### Output of ``pd.show_versions()``

Note that this shows **after** I successfully installed pandas.

<details>

INSTALLED VERSIONS
------------------
commit: a00154dcfe5057cb3fd86653172e74b6893e337d
python: 3.6.5.final.0
python-bits: 64
OS: Darwin
OS-release: 17.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.22.0+0.ga00154dcf.dirty
pytest: 3.5.1
pip: 9.0.3
setuptools: 39.1.0
Cython: 0.28.2
numpy: 1.14.2
scipy: 1.0.1
pyarrow: 0.9.0
xarray: 0.10.3
IPython: 6.3.1
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.2
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.4
feather: 0.4.0
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.2.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: 0.8.0
psycopg2: None
jinja2: 2.10
s3fs: 0.1.4
fastparquet: 0.1.5
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
See https://github.com/pandas-dev/pandas/issues/20775.

You want `--no-build-isolation` in pip 10.

**Comment by miguelmorin** [comment]
I confirm. Following [these steps](http://pandas.pydata.org/pandas-docs/stable/contributing.html#creating-a-development-environment) and replacing 
```
python -m pip install -e .
```
with
```
python -m pip install --no-build-isolation -e .
```
solves the problem. Thanks @TomAugspurger !
