### ISSUE TITLE
Column can be extended beyond DataFrame's length

### ISSUE THREAD

**Issue by metazoic** [pandas-dev/pandas#20967]
#### Code Sample
```python
df = pd.DataFrame({'x':[1.0]})
df.x[1] = 2
df['x'][2] = 3
df.set_index('x', inplace=True)
```
#### Problem description
The final statement fails with
```python
ValueError: Length mismatch: Expected axis has 1 elements, new values have 3 elements
```
because `df.x` has been extended beyond the length of `df`. However, if the index was not numeric, then either assignment would fail appropriately with an out-of-bounds error.

#### Expected Output
I would not expect a DataFrame's column to extend beyond its length.

#### Output of ``pd.show_versions()``
<details>

commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.22.0
pytest: 3.5.1
pip: 10.0.1
setuptools: 39.1.0
Cython: 0.28.2
numpy: 1.14.2
scipy: 1.0.1
pyarrow: None
xarray: None
IPython: 6.3.1
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.2
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.4
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by asishm** [comment]
Just to add on - `df.set_index('x')` doesn't error out. It's the inplace that's causing the error (and appropriately). It's a different point as to whether 

```py
df.x[1] = 2
df['x'][2] = 3
```
should be allowed or not

**Comment by gfyoung** [comment]
Yikes!  PR to patch this is welcome!

**Comment by jreback** [comment]
this is not an accepted method of expanding a DataFrame, *only* loc is available on a ``DataFrame``, see the docs: http://pandas.pydata.org/pandas-docs/stable/indexing.html#setting-with-enlargement

The reason is you are actually doing 2 operations when you do:

``df.x[1]``, similar to how setting with copy is an undetectable condition. I don't know that you can actually detect that this is an expansion w/o a lot of gymnastics. So why this is observed undesirable behavior, it is not supported.

**Comment by metazoic** [comment]
I figured as much, but then shouldn't the assignments at least raise a warning like `SettingWithCopy` (https://pandas.pydata.org/pandas-docs/stable/indexing.html#why-does-assignment-fail-when-using-chained-indexing)?
