### ISSUE TITLE
DOC: Difficulty Novice tag in contributing section doesn't exist

### ISSUE THREAD

**Issue by mvinoba** [pandas-dev/pandas#20982]
The [`Difficulty Novice`](https://github.com/pandas-dev/pandas/issues?q=is%3Aopen+is%3Aissue+label%3A%22Difficulty+Novice%22) tag recommended in the [main README.md Contributing section](https://github.com/pandas-dev/pandas/blob/master/README.md#contributing-to-pandas-) doesn't seem to exist anymore. I think the right recommendation should be the [`good first issue`](https://github.com/pandas-dev/pandas/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) tag, just like it's in the [Where to start?](https://github.com/pandas-dev/pandas/tree/master/doc#where-to-start) section in the docs for contributing to the documentation. Same applies to [/doc/source/contributing.rst](https://github.com/pandas-dev/pandas/blob/8ddc0fd801d794fcd7735816790dff66d1c678e2/doc/source/contributing.rst#where-to-start).

I can work on this and open a PR if the issue is confirmed.

**Comment by WillAyd** [comment]
Seems logical - go for it!
