### ISSUE TITLE
Installation error on Windows 10 64 bit

### ISSUE THREAD

**Issue by danishnazir** [pandas-dev/pandas#21013]
Hi my configuration is as follows
1) i have cython installed
2) i have visual C++ 14.0 build tools installed
 But still, i am getting this annoying error its been week please help me here thanks
"Setup script exited with error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools"

**Comment by TomAugspurger** [comment]
Hard to say without a traceback.

Did you follow the guide at https://devguide.python.org/setup?

**Comment by danishnazir** [comment]
yes i followed the guide but unfortunately i didn't get it to work

**Comment by TomAugspurger** [comment]
Let us know if you figure anything out.

**Comment by danishnazir** [comment]
thanks for being helpful

**Comment by TomAugspurger** [comment]
👍 I'm on OSX. I think @chris-b1 might have access to a windows machine. It'd be good if you could post your solution here, and hopefully update our contributing guide if you're able to get it working.

**Comment by chris-b1** [comment]
Closing, but please re-open if you have a reproducible setup that produces this error
