### ISSUE TITLE
Feature: footer with aggregate function for pivoted dataframes 

### ISSUE THREAD

**Issue by dacoex** [pandas-dev/pandas#21023]
#### Problem description

It would be great to show aggregate values for pivot tables when exporting to CSV or Excel.

#### Expected Output

Something similar as in:

footer_func : {list of aggregation functions or single function}, optional

    A function or list of functions for summarizing each data column in the report. For example, ma.sum to get the sum of the column. If a list of functions is provided there must be exactly one function for each column. Be careful to ensure that the function properly handles masked values. Do not specify a function for the Date column.
 from:
http://pytseries.sourceforge.net/lib.report.html

**Comment by TomAugspurger** [comment]
Can you expand your example a bit? This would be writing an Excel file where some of the cells are actual formulas?

**Comment by dacoex** [comment]
@TomAugspurger thanks for the comment. I admit having edtered it a bit in a rush ;-)

> This would be writing an Excel file where some of the cells are actual formulas?
The resulting values of a aggregate function would be find.
I do not know if I can create Excel formulas from within pandas.

This basic functionality was in a predecessor library:
http://pytseries.sourceforge.net/lib.report.html#example-3-html-report

I will have to check the record if this was discarded by when the timeseries part of pandas was created and functionality was matched against existing pytseries.

So yes, adding a footer/header as a formula would be great:
https://xlsxwriter.readthedocs.io/working_with_formulas.html

**Comment by TomAugspurger** [comment]
I don't think this is in scope for pandas. `to_csv` / `to_excel` will write the contents of the dataframe to disk. For fancier things like forumulas, you'll need to use the underlying writer.

**Comment by dacoex** [comment]
>For fancier things like forumulas, you'll need to use the underlying writer.

Would it still be out of scope if we ditch the formla part and just write summaries?
How do you handle and metadata to the same files?
Usually, this is part of a file header.
