### ISSUE TITLE
to_csv fails with long file path

### ISSUE THREAD

**Issue by Damdinov** [pandas-dev/pandas#21028]
#### Code Sample

```python
df.to_csv('s' * 240 +  '.csv')

---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-60-8ab4f45083ab> in <module>()
----> 1 df.to_csv('s' * 240 +  '.csv')

C:\ProgramData\Anaconda2\lib\site-packages\pandas\core\frame.pyc in to_csv(self, path_or_buf, sep, na_rep, float_format, columns, header, index, index_label, mode, encoding, compression, quoting, quotechar, line_terminator, chunksize, tupleize_cols, date_format, doublequote, escapechar, decimal)
   1522                                      doublequote=doublequote,
   1523                                      escapechar=escapechar, decimal=decimal)
-> 1524         formatter.save()
   1525 
   1526         if path_or_buf is None:

C:\ProgramData\Anaconda2\lib\site-packages\pandas\io\formats\format.pyc in save(self)
   1635             f, handles = _get_handle(self.path_or_buf, self.mode,
   1636                                      encoding=encoding,
-> 1637                                      compression=self.compression)
   1638             close = True
   1639 

C:\ProgramData\Anaconda2\lib\site-packages\pandas\io\common.pyc in _get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text)
    385         if compat.PY2:
    386             # Python 2
--> 387             f = open(path_or_buf, mode)
    388         elif encoding:
    389             # Python 3 and encoding

IOError: [Errno 2] No such file or directory: 'ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss.csv'

```
#### Problem description
First, the exception message is entirely unhelpful.

Second, I do not understand why such of limitations exists. This error appear not only with long filenames, but also with short filename and long file path.

#### Output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.22.0
pytest: 3.2.1
pip: 10.0.1
setuptools: 36.5.0.post20170921
Cython: 0.26.1
numpy: 1.13.1
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: 5.4.1
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 0.9.8
lxml: 4.2.1
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

**Comment by TomAugspurger** [comment]
What's the result of the following?

```
open('s' * 240 +  '.csv', 'w')
```

IIRC different versions of windows have different path length limits.

**Comment by TomAugspurger** [comment]
Alright, seems like this is would be difficult to handle correctly within pandas. Hopefully people are able to find this issue and not lose too much time.
