### ISSUE TITLE
Problem with filename "prn.csv" in pd.DataFrame.to_csv()

### ISSUE THREAD

**Issue by ItachiUchiha91** [pandas-dev/pandas#21035]
**Code Sample:**

```
import pandas as pd
pd.DataFrame().to_csv("prn.csv")
```
gives me the error:
`FileNotFoundError: [Errno 2] No such file or directory: 'prn.csv'`

**Problem description:**

I have a problem with the simple code above. A code like the following works fine
```
import pandas as pd
pd.DataFrame().to_csv("123aaa.csv")

```

**Output of pd.show_versions():**
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.22.0
pytest: None
pip: 10.0.1
setuptools: 39.0.1
Cython: None
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.3.1
sphinx: None
patsy: 0.5.0
dateutil: 2.7.2
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: None
lxml: 4.2.1
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.6.0

**Comment by chris-b1** [comment]
This is a windows quirk - `prn` is reserved from long ago.
https://superuser.com/questions/613313/why-cant-we-make-con-prn-null-folder-in-windows

```python-traceback
In [4]: with open('prn.csv', 'wt') as f:
   ...:     f.write('stuff')
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
<ipython-input-4-1cdb70a485d2> in <module>()
----> 1 with open('prn.csv', 'wt') as f:
      2     f.write('stuff')

PermissionError: [Errno 13] Permission denied: 'prn.csv'
```
