### ISSUE TITLE
DOC: Update Contributing Guide to Point to Pandas Docstring Guide

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#21040]
I've seen a few PRs here and there that come in with the good intention of updating docstrings but don't follow the pandas docstring guide. Part of the problem may be that we don't explicitly point to this in the contributing guide, referencing instead still the NumPy standard:

https://pandas.pydata.org/pandas-docs/stable/contributing.html#about-the-pandas-documentation

Could be a simply fix for someone to update that section and reference the pandas docstring guide

https://python-sprints.github.io/pandas/guide/pandas_docstring.html

**Comment by TomAugspurger** [comment]
Ideally, this would be done automatically by a linter. We should maintain a list of passing docstrings and not allow those to regress (or a list that are allowed to fail, and whittle away at it).

But for now, fixing the docs to call out our format and tool would be good.

**Comment by cgopalan** [comment]
Shouldn't the document to point to be https://pandas.pydata.org/pandas-docs/stable/contributing_docstring.html and not https://python-sprints.github.io/pandas/guide/pandas_docstring.html ?

**Comment by cgopalan** [comment]
@WillAyd any confirmation on the question above? Then I can make the change.

**Comment by WillAyd** [comment]
@cgopalan yep that's probably a better idea. PRs welcome!

**Comment by WillAyd** [comment]
Hmm OK thanks for checking. If that's the case then I must have missed that update before opening this issue. Will go ahead and close out
