### ISSUE TITLE
Pandas Dataframe behaves differently when one column is a TimeSeries. 

### ISSUE THREAD

**Issue by chiiyeh** [pandas-dev/pandas#21045]
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import datetime 
import pandas as pd

#Creating a dataframe with timeseries
timenow = datetime.datetime.now()
timelater = timenow + datetime.timedelta(days = 1)
d = {'col1' : [timenow, timelater],'col2' : [1,2]}
dfTimeSeries = pd.DataFrame(d)

#Creating a dataframe without timeseries
d = {'col1' : [3,4],'col2' : [1,2]}
df = pd.DataFrame(d)

#Defining a function with a fixed list output
def stupidL(row):
    return [1,2,3]

df.apply(stupidL,axis = 1) # runs without error
dfTimeSeries.apply(stupidL,axis = 1) # fails to run
```
#### Problem description
The behavior of the DataFrame seems to differ when one of the columns is a TimeSeries, even when the code does not use that column. Running similar code seems to generate different results. 

This was also mentioned in this post <https://stackoverflow.com/questions/19628159/pandas-incorrect-shape-of-indices-passed-not-sure-how-to-fix-it>.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-43-Microsoft
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: None
pip: 10.0.1
setuptools: 39.0.1
Cython: None
numpy: 1.14.2
scipy: None
pyarrow: None
xarray: None
IPython: 6.3.1
sphinx: 1.7.4
patsy: None
dateutil: 2.7.2
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by mroeschke** [comment]
This particular example works in the latest version of pandas (v0.23.0).

```
In [11]: df.apply(stupidL,axis = 1)
Out[11]:
0    [1, 2, 3]
1    [1, 2, 3]
dtype: object

In [12]: dfTimeSeries.apply(stupidL,axis = 1)
Out[12]:
0    [1, 2, 3]
1    [1, 2, 3]
dtype: object

In [13]: pd.__version__
Out[13]: '0.23.0'
```

Always appreciate additional unit tests to prevent regressions. PRs welcome!

**Comment by jreback** [comment]
this is well covered by tests and functions as designed
