### ISSUE TITLE
Dataframe filtering duplicates columns

### ISSUE THREAD

**Issue by geriasd2** [pandas-dev/pandas#21047]
#### Code Sample, a copy-pastable example if possible

```python
import pandas
df = pandas.DataFrame(columns=['A', 'B'])
print(df.columns)
df = df.filter(items=['A', 'A', 'A'])
print(df.columns)
```
#### Problem description

Filtering a dataframe with a list which contains multiple times a column that is already inside the original dataframe results in a new dataframe, where the mentioned column is present multiple times. This problem might be fixed easily by converting the input list into a set.

#### Expected Output
A filtered dataframe which have only one column: 'A'.
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.22.0
pytest: None
pip: 9.0.1
setuptools: 28.8.0
Cython: None
numpy: 1.14.3
scipy: None
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0b10
sqlalchemy: 1.2.3
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by WillAyd** [comment]
Not sure this is a bug - why wouldn't you just pass a unique list in the first place instead of relying on pandas to take care of that for you?

**Comment by simonjayhawkins** [comment]
This issue hasn't had much engagement and I agree with @WillAyd that this is out of scope for pandas, so I think this issue can be closed.

---

I'm not sure about the value of the `.filter` method anyway. I think better to use the pandas indexing operations with listcomps as needed to replicate functionality that `regex` and  `like` parameters provide.

```
>>> df = pd.DataFrame(
...     np.array(([1, 2, 3], [4, 5, 6])),
...     index=["mouse", "rabbit"],
...     columns=["one", "two", "three"],
... )
>>> df
        one  two  three
mouse     1    2      3
rabbit    4    5      6
>>>
>>> # select columns by name
>>> df.filter(items=["one", "three"])
        one  three
mouse     1      3
rabbit    4      6
>>>
>>> df[["one", "three"]]
        one  three
mouse     1      3
rabbit    4      6
>>>
>>> # select columns by regular expression
>>> df.filter(regex="e$", axis=1)
        one  three
mouse     1      3
rabbit    4      6
>>>
>>> import re
>>> df[[col for col in df if re.search("e$", col)]]
        one  three
mouse     1      3
rabbit    4      6
>>>
>>> # select rows containing 'bbi'
>>> df.filter(like="bbi", axis=0)
        one  two  three
rabbit    4    5      6
>>>
>>> df.loc[[row for row in df.index if "bbi" in row], :]
        one  two  three
rabbit    4    5      6
>>>
```

The code with `.filter` may be more concise, but imo the indexing code is easier to grok and more flexible.

i'd be -1 on making any changes to `.filter` (other than deprecation or maybe making the interface more consistent with the built-in Python function, i.e. accept a function for the condition)

> This problem might be fixed easily by converting the input list into a set.

agreed.
