### ISSUE TITLE
Plotting: .hist() and .plot.hist()

### ISSUE THREAD

**Issue by mangecoeur** [pandas-dev/pandas#21048]
#### Code Sample, a copy-pastable example if possible

```python
cols = ['heat_total', 'area_density', 'mean_n_floors',
       'n_buildings', 'area_demand_density_grid', 'floor_demand_density']

plt.figure()
df[cols].plot.hist(
    bins=20,
    alpha=0.5
)

plt.figure()
df[cols].hist(
    bins=20,
    alpha=0.5
)

```
#### Problem description

`df.hist()` and `df.plot.hist()` give different plots: `.hist()` plots a grid of figures while `.plot.hist()` plots overlapping distributions.

Result of `df.hist()`

![hist](https://user-images.githubusercontent.com/743508/40050900-243630f4-5839-11e8-99cc-ff2f4421f8f6.png)

Result `df.plot.hist()`

![plothist](https://user-images.githubusercontent.com/743508/40050901-244fb114-5839-11e8-9676-846d8b9a90ba.png)

#### Expected Output

`.hist()` and `.plot.hist()` should give exactly the same results

#### Output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.22.0
pytest: 3.2.1
pip: 9.0.1
setuptools: 36.5.0.post20170921
Cython: 0.26.1
numpy: 1.14.2
scipy: 0.19.1
pyarrow: None
xarray: 0.10.0
IPython: 6.2.1
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.2.2
openpyxl: 2.4.9
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: 2.7.4 (dt dec pq3 ext lo64)
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

**Comment by TomAugspurger** [comment]
Closing in favor of #11053
