### ISSUE TITLE
BUG: Rename MultiIndex level destroys CategoricalIndex on other levels

### ISSUE THREAD

**Issue by kdebrab** [pandas-dev/pandas#21055]
When renaming some values in one of the levels of an index, any CategoricalIndex on other unrelated levels are suddenly no longer categorical.

#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
mi = pd.MultiIndex.from_tuples([[2,2],[2,1],[1,2],[1,1]], names=list('AB'))
mi = mi.set_levels(pd.CategoricalIndex(mi.levels[0], categories=[2,1]), level='A')
a = pd.Series([1,2,3,4], index=mi)
b = a.rename({1:5}, level='B')
b.index.get_level_values('A')
```
returns
```
Int64Index([2, 2, 1, 1], dtype='int64', name='A')
```

#### Problem description

Index level 'A' should remain a CategoricalIndex after renaming values on index level 'B'.

#### Expected Output

The same as what we get when displaying `a.index.get_level_values('A')` (before renaming):
```
 CategoricalIndex([2, 2, 1, 1], categories=[2, 1], ordered=False, name='A', dtype='category')
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None
pandas           : 0.25.1
numpy            : 1.17.1
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 39.0.1
Cython           : 0.29.4
pytest           : 4.2.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.1.2
lxml.etree       : 4.3.4
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 5.8.0
pandas_datareader: None
bs4              : 4.6.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.4
matplotlib       : 2.2.4
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.5.12
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.2.18
tables           : None
xarray           : 0.12.3
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.2

</details>

**Comment by theavey** [comment]
Found this same issue. Any progress on a fix or workaround?
