### ISSUE TITLE
pandas to_sql   mysql

### ISSUE THREAD

**Issue by Object-v** [pandas-dev/pandas#21076]
sql.to_sql(df,tablename,self.engine,flavor=None,schema=None,if_exists='append',index=False,chunksize=100000)  

Pandas this to_sql slow storage speed is not a good way, the amount of data per hour 140w now takes 10 minutes

**Comment by TomAugspurger** [comment]
0.23.0 includes an optimization for this. Our issue template asks you to include the output of `pandas.show_versions()`, so I'll have to assume that you're on an older version.

**Comment by Object-v** [comment]
pandas (0.20.1)

**Comment by TomAugspurger** [comment]
OK, this should be improved in 0.23
