### ISSUE TITLE
Any chance of a 32-bit manylinux wheel for 0.23 / Python 3.5?

### ISSUE THREAD

**Issue by matthew-brett** [pandas-dev/pandas#21086]
When building statsmodels wheels, I noticed there is no manylinux wheel for Python 3.5 / 32-bit - although there is for Python 3.6.  I guess this is just oversight?  Any chance of building / uploading one?

**Comment by jorisvandenbossche** [comment]
They are not in the build matrix apparently: https://github.com/MacPython/pandas-wheels/blob/dc73b8607a03e42ab5f44662f1ca83090470ba02/.travis.yml#L28-L45. But should be easy to add.

**Comment by matthew-brett** [comment]
I recommend this at the top of the `.travis.yml` file, in your `env`, `global` section:

```
      - MANYLINUX_URL=https://5cf40426d9f06eb7461d-6fe47d9331aba7cd62fc36c7196769e4.ssl.cf2.rackcdn.com
```

That directory has 32-bit numpy wheels, so you don't have to build them during the pandas build phase.
