### ISSUE TITLE
How to cause newline to escape as \n; fieldsep to escape as \n and \t

### ISSUE THREAD

**Issue by halfiron** [pandas-dev/pandas#21087]
Using pandas version 0.22 I would like to escape special characters in the output tsv as outputted by:
df.to_csv( outFn, sep='\t', escapechar='\\', quoting=csv.QUOTE_NONE, encoding='utf-8')

But I don't like the current escaping, which just puts a "\\" in front of the special char, I rather prefer the special char be replaced entirely, to make parsing of the outputted tsv files with simpler tools possible. 
The different version of escaping I propose are as follows:
* newline to "\n" (i.e. truly backslash, then the letter "n").
* tabchar to "\t" (i.e. truly  backslash, then the letter "t").

Ideally, it would implement something like this on each field value before outputting:
v = v.replace('\\','\\\\').replace('\n','\\n').replace('\t','\\t').replace('\r','\\r')

The reason is that we have some users of the tsv files downstream using tools other than pandas, like grep, perl, awk or python with csv module .. and they don't want records broken up over many lines when the there is a field with an internal newline char.   Some do the simple decoding with 'string_escape':   
vv = fp.readline().strip('\n\r').split('\t')
v = map(lambda v: v.decode('string_escape'), vv)

Thank you.

**Comment by mroeschke** [comment]
As a usage question we first recommend asking StackOverflow first. This forum is meant for bug reports and enhancements requests. If there is an enhancement that comes from a response from StackOverflow, this can be reopened specing that feature out. Closing for now.
