### ISSUE TITLE
DOC: error in 0.23.0 concat sort warning?

### ISSUE THREAD

**Issue by adbull** [pandas-dev/pandas#21101]
#### Problem description

Pandas 0.23.0 adds a new warning when calling `concat` with misaligned axes (#20613):

```
FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False
```

This seems strange; I'd assume that `sort=True` would give the current behaviour, and `sort=False` the future behaviour, as in the docs for `concat`: 

```
Explicitly pass sort=True to silence the warning and sort. Explicitly pass
sort=False to silence the warning and not sort.
```

I'm assuming the docs are right and the warning is wrong?

**Comment by TomAugspurger** [comment]
Whoops, you're correct. Mind making a PR to fix it? May have to update a test or two.
