### ISSUE TITLE
API: implement droplevels() for flat index

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#21115]
#### Code Sample, a copy-pastable example if possible

```python
In [2]: pd.Index([1, 2, 3]).droplevel([])
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-9172aa27c42a> in <module>()
----> 1 pd.Index([1, 2, 3]).droplevel([])

AttributeError: 'Int64Index' object has no attribute 'droplevel'
```

#### Problem description

Clearly the call above doesn't make too much sense, but there is no reason not to support it, and can help [write cleaner code](https://github.com/pandas-dev/pandas/pull/21016#issuecomment-389572566).

#### Expected Output

```python
In [2]: pd.Index([1, 2, 3]).droplevel([])
Out[2]: Int64Index([1, 2, 3], dtype='int64')
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: e033c0616158d3ba974456b4f84810492936b1fe
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-6-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.24.0.dev0+10.ge033c0616.dirty
pytest: 3.5.0
pip: 9.0.1
setuptools: 39.0.1
Cython: 0.25.2
numpy: 1.14.1
scipy: 0.19.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.5.6
patsy: 0.5.0
dateutil: 2.7.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.0dev
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.0
openpyxl: 2.3.0
xlrd: 1.0.0
xlwt: 1.3.0
xlsxwriter: 0.9.6
lxml: 4.1.1
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.2.1

</details>

**Comment by toobaz** [comment]
By the way: I'm sure there was an issue with a list of ``MultiIndex`` methods that should have been ported to ``Index`` too... but I wasn't able to find it.

**Comment by jschendel** [comment]
>issue with a list of `MultiIndex` methods that should have been ported to `Index`

xref #3268, which includes `droplevel`
