### ISSUE TITLE
Adding columns in groupby

### ISSUE THREAD

**Issue by wesm** [pandas-dev/pandas#2112]
Possible to simplify?

xref http://stackoverflow.com/questions/12389898/python-pandas-how-to-add-a-totally-new-column-to-a-data-frame-inside-of-a-group

**Comment by rhshadrach** [comment]
The SO posts are adding columns to the DataFrame in `groupby(...).apply` and `groupby(...).transform`. In general, mutating a container while iterating over it invalidates the iterators, this shouldn't be allowed, similar to #12653.
