### ISSUE TITLE
Assigning a timestamp value to a Series create an int instead

### ISSUE THREAD

**Issue by jimbasquiat** [pandas-dev/pandas#21143]
```
g = pd.Series(dict(a = 5, b =datetime(2018, 1,1)))
g['datetime'] = pd.Timestamp('2018-01-02')
```
g returns:

```
a                             5
b           2018-01-01 00:00:00
datetime    1514851200000000000
dtype: object
```

It seems this is a bug, [I asked the question on SO and found a workaround](https://stackoverflow.com/questions/50431592/pandas-assigning-a-timestamp-value-to-a-serie-create-an-int-instead), but might be useful to investigate further and fix the bug.

**Comment by mroeschke** [comment]
Thanks for the report. Users have reported this issue in #13910 and #18410. Investigation and pull requests are always welcome!
