### ISSUE TITLE
DataFrame.reindex() with MultiIndex doesn't fill missing values

### ISSUE THREAD

**Issue by holymonson** [pandas-dev/pandas#21147]
#### Code Sample, a copy-pastable example if possible

```python
pd.DataFrame([-1., -2.], [['a', 'a'], [1, 2]]).reindex([1, 2, 3], level=1)
#        0
# a 1 -1.0
#   2 -2.0
```
#### Problem description

`DataFrame.reindex()` with `level` specified doesn't  fill missing values.

#### Expected Output
```python
#      0
# a 1 -1.0
#   2 -2.0
#   3  NaN
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Darwin
OS-release: 17.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: zh_CN.UTF-8
LOCALE: zh_CN.UTF-8

pandas: 0.23.0
pytest: None
pip: 10.0.1
setuptools: 39.1.0
Cython: None
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: None
sphinx: 1.6.2
patsy: None
dateutil: 2.7.2
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: 1.0.5
lxml: None
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by gfyoung** [comment]
Indeed, such a behavior would work just fine with a single `Index`, but strangely not with `MultiIndex`.  Patch and PR are more than welcome!

**Comment by holymonson** [comment]
```python
idx, idxer = pd.Index(range(3)).reindex([0, 1, 4])
idx, idxer
# (Int64Index([0, 1, 4], dtype='int64'), array([ 0,  1, -1]))
idx.size
# 3

idx, idxer = pd.MultiIndex.from_arrays([['a']*3, range(3)]).reindex([0, 1, 4], level=1)
idx, idxer
# (MultiIndex(levels=[['a'], [0, 1, 4]],
#            labels=[[0, 0], [0, 1]]), array([0, 1]))
idx.size
# 2
```

In reindexing, `Int64Index` will be replace with the original target, while `MultiIndex` with the masked intersection only. Is it designed to be a special implement for `MultiIndex.reindex()` other than `Index.reindex()`? Seems no docs for that.

https://github.com/pandas-dev/pandas/blob/172ab7aee433fed7780bf96f0c723af284755324/pandas/core/indexes/base.py#L4014-L4019

**Comment by jorisvandenbossche** [comment]
@holymonson Thanks for the report. Going to close this in favor of:

- doc issue on `level` keyword: https://github.com/pandas-dev/pandas/issues/15590
- older issue that asks the same question: https://github.com/pandas-dev/pandas/issues/12319

But feel free to chime in on on those issues.
