### ISSUE TITLE
Rolling correlation for DataFrame with MultiIndex columns broken in Pandas 0.23

### ISSUE THREAD

**Issue by jjbarton** [pandas-dev/pandas#21157]
#### Code Sample

```
import numpy as np
import pandas as pd

index = range(5)
data = np.random.random(size=(len(index), 2))

simple_cols = ['M', 'N']
simple_df = pd.DataFrame(data, index=index, columns=simple_cols)

multi_cols = pd.MultiIndex.from_arrays([['M', 'N'], ['P', 'Q']], names=['a', 'b'])
multi_df = pd.DataFrame(data, index=index, columns=multi_cols)

# Works:
simple_df.rolling(3).corr()

# Fails
multi_df.rolling(3).corr()
```

#### Problem description

Since the Pandas 0.23 release it is no longer possible to calculate rolling correlation on a pd.DataFrame which has a pd.MultiIndex column index. An exception is raised in 0.23. In 0.22 a valid rolling correlation result is returned.

#### Expected Output

Pandas should return the same rolling correlation matrix as it returns for a data frame with simple index, but with the multi index levels in columns and index as they appeared in 0.22.

**Comment by WillAyd** [comment]
Thanks for the report! Investigation and PRs are always welcome

**Comment by andyshermanash** [comment]
hello, I am also having this same issue in 0.23, which has broken my working code that was previously using 0.22 @jjbarton were you able to solve this issue without reverting back to pandas 0.22?

**Comment by jjbarton** [comment]
Hi Andy

I worked around it in my code (by replacing the multi index with a simple
index and then mapping back once I'd calculated rolling correlation. I
don't think there's any progress otherwise, and my quick fix isn't a
suitable resolution.

Cheers
Joe
