### ISSUE TITLE
Sparsify MultiIndex in Styler

### ISSUE THREAD

**Issue by reedjosh** [pandas-dev/pandas#21155]
#### Merge Duplicate Cells for Easier Reading as a Styler Option
![image](https://user-images.githubusercontent.com/9508385/40321694-bfa0c072-5ce4-11e8-931a-1c608467c206.png)

At work we generate reports in Bi4 and via Python. In the Python reports we write, we use the new Styler object to generate conditionally formatted HTML. 

The generated HTML would be much more readable if there was a way to conditionally merge cells as in the Bi4 report shown above. I really hate Bi4, but the reports do look nicer. 

If this already exists, I apologize, and please kindly point me to the documentation. If not, then thank you for considering this enhancement request.

Best,

\- Joshua

**Comment by TomAugspurger** [comment]
Hmm, I think this is done actually? https://github.com/pandas-dev/pandas/pull/13775

Can you set the levels you want sparsified into a MultiIndex and render that?

**Comment by TomAugspurger** [comment]
Let us know if that isn't what you had in mind.

**Comment by reedjosh** [comment]
Hey, it is basically what I have in mind, but it appears to be not usable with a Styler object. 

![image](https://user-images.githubusercontent.com/9508385/40518315-cd13b0fc-5f6e-11e8-940f-eba48cc43267.png)

![image](https://user-images.githubusercontent.com/9508385/40518380-3199408c-5f6f-11e8-9fe9-08dea2303da7.png)


Am I doing something wrong? Is this something that's not implemented?

Thanks Again!

**Comment by TomAugspurger** [comment]
Correct, it’s not implemented for non unique indexes

________________________________
