### ISSUE TITLE
Request: Add a parameter to DataFrame.head() to control how many columns are printed

### ISSUE THREAD

**Issue by Khris777** [pandas-dev/pandas#21167]
`df.head()` is my favorite way to get a quick look of a dataframe.

Until now `options.display.max_columns` was usually set to 20 which was good for me. Now that behaviour has changed and it gets set to 0. While that makes DataFrame Output look tidier it makes the use of the `head()` function can be pretty pointless if I get to see 2 or 3 columns of 20 or 30.

So I want to propose that a parameter is added to `head()` that overwrites the setting for that call.

`head()` has already a parameter for how many lines should be printed, a second parameter telling it how many columns should be printed would make a lot of sense to me and having at least one easy way to look at a DataFrame without the constraint of the default setting would be very handy.

**Comment by Liam3851** [comment]
@Khris777 The proposed solution wouldn't solve your issue: ```head()``` doesn't do any display, it just returns a DataFrame with the given number of rows:
```
   def head(self, n=5):
        """
        Returns first n rows
        """
        return self.iloc[:n]
```

Display still goes through the usual display mechanism. So if you called your hypothetical
```
df.head(5, 20)
```
you would return a DataFrame with 20 columns, which in turn would have 2 or 3 of those columns displayed (or whatever depending on your screen width and the value of ```pd.options.display.max_columns```).

To fix the display, just set ```pd.options.display.max_columns``` to your preferred value at the beginning of your session, or set it in your ipython startup (see "Setting startup options in a python/ipython environment" in https://pandas.pydata.org/pandas-docs/stable/options.html).

**Comment by Khris777** [comment]
I see, thanks for the info.

**Comment by mroeschke** [comment]
Closing as modifying display option is more relevant
