### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by shakhawatnwpu** [pandas-dev/pandas#21179]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import sqlite3
import pandas as pd
cnx = sqlite3.connect('database.sqlite')
df = pd.read_sql_query("SELECT * FROM Player_Attributes", cnx)
```
#### Problem description
pandas.io.sql.DatabaseError: Execution failed on sql 'SELECT * FROM Player_Attributes': no such table: Player_Attributes
[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by jorisvandenbossche** [comment]
@shakhawatnwpu the github issues are meant for potential bugs / enhancement request, and not for general questions for help. It's better to ask such a question on a Q&A forum like StackOverflow (https://stackoverflow.com/questions/tagged/pandas) or the pydata mailing list.
