### ISSUE TITLE
adjust resample start/end dates

### ISSUE THREAD

**Issue by changhiskhan** [pandas-dev/pandas#2118]
so don't have to reindex twice.

http://stackoverflow.com/questions/13064400/resample-to-datetimeindex-raises-an-error

or furthermore, arbitrary non-reg freq resampling?

**Comment by OmerJog** [comment]
This can be nice to have!

**Comment by mroeschke** [comment]
I _think_ https://github.com/pandas-dev/pandas/pull/31809/files might have addressed this? Happy to reopen if this isn't the case
