### ISSUE TITLE
Python Pandas rolling mean DataFrame Constructor not properly called

### ISSUE THREAD

**Issue by kiann00** [pandas-dev/pandas#21206]
#### Code Sample, a copy-pastable example if possible

def py_TA_MA(v, n, AscendType):  
    df = pd.DataFrame(v, columns=['Close'])
    df = df.sort_index(ascending=AscendType) # ascending/descending flag
    M = pd.Series(df['Close'].rolling(n), name = 'MovingAverage_' + str(n))
    df = df.join(M)
    df = df.sort_index(ascending=True) #need to double-check this
    return df
```
#### Problem description

I am trying to create a simple time-series, of different rolling types. One specific example, is a rolling mean of N periods using the Panda python package.

I get the following error : ValueError: DataFrame constructor not properly called!

Below is my code :

**Comment by TomAugspurger** [comment]
Could you put together a reproducible example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

And post your pandas version info like requested.

**Comment by mroeschke** [comment]
Feel free to reopen when you get a chance to post a reproducible example.

**Comment by MAHMOUDZAHERZORO** [comment]
i think you should take a look for 'V' variable as pd.Dataframe() argument should be first transformed and be in array . 
for example :
 doc_array = (count_vector.transform(documents)).toarray()
frequency_matrix = pd.DataFrame(data=doc_array)
