### ISSUE TITLE
Bad rendering of VersionInfo in Pandas DataFrame

### ISSUE THREAD

**Issue by scls19fr** [pandas-dev/pandas#21208]
Hello,

I noticed that `VersionInfo` are rendered badly in Pandas DataFrame.
(see https://github.com/k-bx/python-semver/issues/87)

They are rendered as tuple.

```python
In [1]: import pandas as pd
In [2]: import semver
In [3]: versions = ['4.0.0', '5.0.0', '5.0.1', '10.0.0']
In [4]: df = pd.DataFrame(versions, columns=['versions'])
In [5]: df  # version as string
In [6]: df.sort_values(by='versions')  # so they are not ordered correctly
Out[6]:
  versions
3   10.0.0
0    4.0.0
1    5.0.0
2    5.0.1
In [7]: df['versions'] = df['versions'].map(semver.parse_version_info)  # parse versions as `VersionInfo`
In [8]: df.sort_values(by='versions')  # VersionInfo are ordered correctly but are badly rendered
Out[8]:
                 versions
0   (4, 0, 0, None, None)
1   (5, 0, 0, None, None)
2   (5, 0, 1, None, None)
3  (10, 0, 0, None, None)
```

I don't know what method Pandas use for rendering them.
What I see is that it's neither using `__str__` neither using `__repr__` method

```python
In [9]: v = df['versions'].iloc[-1]

In [10]: v
Out[10]: VersionInfo(major=10, minor=0, patch=0, prerelease=None, build=None)

In [11]: v.__str__()
Out[11]: '10.0.0'

In [12]: v.__repr__()
Out[12]: 'VersionInfo(major=10, minor=0, patch=0, prerelease=None, build=None)'
```

`VersionInfo` inherits from `namedtuples` so this is probably related.

Any idea?

Kind regards

**Comment by chris-b1** [comment]
This seems to be generic to our rendering of nametuples
```python
from collections import namedtuple
Thing = namedtuple('Thing', ['a', 'b'])
s = pd.Series([Thing(1,2), Thing(3, 4)])

s
Out[70]: 
0    (1, 2)
1    (3, 4)
dtype: object
```

Seems reasonable to instead print the python repr, somewhere in our printing logic is probably an `isinstance(..., tuple)` that could be specialized.

https://github.com/pandas-dev/pandas/blob/dc02831f7b267ef152c9bb6a1c8e39c652c1ac3c/pandas/io/formats/printing.py

**Comment by scls19fr** [comment]
I've found a workaround avoiding inheriting from `namedtuple`.

Should I close ?
