### ISSUE TITLE
Barh does not have "secondary_y" functionality

### ISSUE THREAD

**Issue by JoshuaC3** [pandas-dev/pandas#21219]
As seen in this stackoverflow [post](https://stackoverflow.com/a/49775042/4049396), you have two y-axes on a single bar plot by passing the name of a column to `secondary_y`. This makes a lots of sense.

When you try to do this to a barh plot, e.g. pass `secondary_y`, it has no effect on what would be the secondary_x axis.

Clearly there are nomenclature issues here (secondary_x vs y), as well as functionality issues, but it would be very nice to have the ability to plot barh with the secondary axis.

some more examples:

Horizontal Bar but with Poor Scaling:
![image](https://user-images.githubusercontent.com/11645712/40575325-f3500d52-60da-11e8-98b2-02b786a0053b.png)

Bar Chart with Good Scaling:
![image](https://user-images.githubusercontent.com/11645712/40575330-01c2cc26-60db-11e8-8af7-80e5f479f445.png)

Bar Chart with Poor Scaling:
![image](https://user-images.githubusercontent.com/11645712/40575340-18652fa0-60db-11e8-82b2-59c1c96b4675.png)

Cannot reproduce Horizontal Bar but with Good Scaling.

**Comment by mroeschke** [comment]
Thanks for the request but it appears this hasn't gotten traction in a while so closing
