### ISSUE TITLE
Pandas is returning two groups for the same unique id.

### ISSUE THREAD

**Issue by everestial** [pandas-dev/pandas#21229]
There is been an issue with `groupby` in pandas when the COLUMN has mixed data types. 
See this question on stackoverflow for details: 

https://stackoverflow.com/questions/50552448/pandas-groupby-is-returning-two-groups-for-the-same-unique-id/50552528?noredirect=1#comment88120185_50552528

**Comment by jorisvandenbossche** [comment]
Can you explain what exactly you think is the bug?

**Comment by WillAyd** [comment]
I read through your issue and it sounds like you are mixing ints and strings within an object and end up getting two distinct groups for 2 (one for the int, one for the string). If that’s the case then this is not a bug as those should be two distinct objects. 

If that’s not the case then further clarification would help

**Comment by everestial** [comment]
@WillAyd 
Yeah, that is the case. I am not mixing the ints and strs together. Actually that is the nature of the data.

    CHROM    POS    REF .............
    scaff_9      1          .............
    scaff_9      ...........................
    2      23    ................
    2      51    .....................
    1      11    ..................
    1      23    ......................

 So, when there is no `scaff_9` grouping happens nicely. When there is `scaff_9` in my input **csv or tab separated file** there is grouping problem with `CHROM = 2`, one small group of `2` and another large group of `2` again. So, it seems that `pandas` interprets `2` as string type because it was reading earlier `CHROM` values as string, but later switched to treating 2 as integer.

But, what ever be the type of data in `CHROM` field it should not treat few `2` as string and other as integer, rite ??  I am just reading the tab delimited file and doing grouping on the data frame, so I am not changing or specifiying what is in `CHROM` - pandas should be able to handle it automatically. 

But, if there is not `scaff_9` in my input data there is again not problem with `groupby`. I am saying, the mere presence of `scaff_9` as string type data earlier on the dataframe should not affect `groupby` operations on the rest of the data.

**Comment by jorisvandenbossche** [comment]
> So, it seems that pandas interprets 2 as string type because it was reading earlier CHROM values as string, but later switched to treating 2 as integer.

Ah, that sounds as it might have to do with the csv reading. Can you try with passing `low_memory=False` to `read_csv`? 
Is your data coming from a single csv file, or do you concatenate dataframes from multiple csv files?

> what ever be the type of data in CHROM field it should not treat few 2 as string and other as integer

It should, as it should treat strings and integers differently, as @WillAyd said. However, it is true that you normally shouldn't end up with such a mixture of types.

**Comment by everestial** [comment]
!) What would be most appropriate way of handling this problem ?

    my_data['CHROM'] = my_data['CHROM'].astype(str)  # after reading the data
    # vs. 
    my_data = read_csv(.... , low_memory=False)

2) Sometimes my data comes from single csv, but sometimes it merges with another csv (left merge) on the way - It depends on what arguments the user has passed. 

3) Shouldn't pandas recognize mixed data types automatically and handle it separately as required. I think the problem here is that pandas is identifying some `2` to string and some to `int`? I wouldn't mind an extra code of `.astype(str)`.

**Comment by everestial** [comment]
I think this issue can be closed, rite ?

**Comment by WillAyd** [comment]
I'm confused as to your examples - are you getting the issue when parsing just one file? If so then I'd say it's fine to keep open if you can provide a minimally reproducible example as the interpretation of data in one parse should stay consistent (i.e. if 2 is a string in the first X rows then it should still be a string in the last Y rows).

If however your issue pops up when joining multiple files together then this should be closed - I don't think there's a feasible way to guarantee that 2 should be a string when parsing file X just because file Y mixes it in with string values like "scaff_9"

**Comment by jorisvandenbossche** [comment]
@WillAyd see the note box at the end of this section: http://pandas.pydata.org/pandas-docs/stable/io.html#specifying-column-data-types, that's an explanation of what I suppose is happening. 
A rather tricky case to notice in your code if you are not aware of it ...

**Comment by jorisvandenbossche** [comment]
> What would be most appropriate way of handling this problem ?

Both are fine, whatever you prefer. Yet another option is to specify the dtype in `read_csv` with `dtype={'CHROM': str}`.
