### ISSUE TITLE
read_csv memory leak?

### ISSUE THREAD

**Issue by kuraga** [pandas-dev/pandas#21325]
### Code Sample, a copy-pastable example if possible

**UPDATED**

```python
with open('df.csv', 'wt') as f:
    f.write('item_id,user_id,region,city,parent_category_name,category_name,param_1,param_2,param_3,title,description,price,item_seq_number,activation_date,user_type,image,image_top_1,deal_probability\n')
    for n in range(10000):
        f.write("""ba83aefab5dc,91e2f88dd6e3,Ростовская область,Ростов-на-Дону,Бытовая электроника,Аудио и видео,"Видео, DVD и Blu-ray плееры",,,Philips bluray,"В хорошем состоянии, домашний кинотеатр с blu ray, USB. Если настроить, то работает смарт тв /
Торг",4000.0,9,2017-03-20,Private,b7f250ee3f39e1fedd77c141f273703f4a9be59db4b48a8713f112c67e29bb42,3032.0,0.43177\n""")

import psutil

print(psutil.Process().memory_info().rss / 1024**2)  #=> 11

import pandas as pd
df = pd.read_csv('df.csv')

print(df.shape)  #=> (4000, 14)
print(psutil.Process().memory_info().rss / 1024**2)  #=> 67

import gc
del df
gc.collect()

print(psutil.Process().memory_info().rss / 1024**2)  #=> 67
```

Old version (many columns): remove `\n` at the end of `f.write(...)`.

#### Problem description

Seems like `pd.read_csv` has a memory leak. ~~Moreover, reading this 2Mb-CSV takes 42 seconds.~~

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

pandas: 0.23.0
pytest: None
pip: 9.0.3
setuptools: 39.0.1
Cython: None
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: None
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.9999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by gfyoung** [comment]
@kuraga : Sorry for taking some time to get back.

Quick question: Was your intention to have this many columns?

**Comment by gfyoung** [comment]
As for the memory leak, I wanted to share this script for consideration:

~~~python
import psutil
print(psutil.Process().memory_info().rss / 1024**2)

import pandas as pd
df = pd.DataFrame(columns=["aaaaaa"] * 4000)

import gc

del df
gc.collect()

print(psutil.Process().memory_info().rss / 1024**2)
~~~

**Comment by kuraga** [comment]
@gfyoung Ahah... Sorry bery much I've lost a newline. Updated. Almost the same.

**Comment by gfyoung** [comment]
@kuraga : What about a newline on the first `f.write` (for where you write the headers) ?

**Comment by kuraga** [comment]
@gfyoung don't understand. I've updated first post with new code *and new results*.

**Comment by gfyoung** [comment]
@kuraga : What I'm saying is that the generated `DataFrame` still has too many column headers, judging from how you answered previously.  Try printing out `df.columns`.

**Comment by kuraga** [comment]
@gfyoung are you talking about 35 columns? Well, dataset this row came from has 35 columns (and 2003424 rows, and memory leak is ~800MB).

Ok I'll try to reduce columns number with saving the leak.

**Comment by kuraga** [comment]
@gfyoung oh, now I see. Updated.

**Comment by gfyoung** [comment]
Ah, that's much better now.  Did you try running the code snippet above?

https://github.com/pandas-dev/pandas/issues/21325#issuecomment-395291130

**Comment by kuraga** [comment]
@gfyoung 
```
11.38671875
65.84765625
```

P.S. Why this is important:  dataset this row came from has 2003424 rows and memory leak is ~800MB.

**Comment by gfyoung** [comment]
@kuraga : My point is that, is this really an issue with `read_csv` or potentially with `DataFrame` ?

**Comment by kuraga** [comment]
@gfyoung don't know. That's why I left a question mark in title :smile: 

BTW during working, memory gap after deleting all DataFrames is more then memory gap just after reading input data and deleting it (*as I see, maybe it's incorrect*). So it could be a DataFrame leak.

But now I see a problem... Memory leak is constant (54Mb) even with 10e8 x 1 shape. But my leak is 800Mb on dataset. So I got a wrong row example :-(

**Comment by kuraga** [comment]
Even with 1x1 :-( Ok, will try later...
