### ISSUE TITLE
describe() does not report first and last on tz-aware datetime Series

### ISSUE THREAD

**Issue by louispotok** [pandas-dev/pandas#21328]
#### Code Sample, a copy-pastable example if possible

```python
s = pd.Series(pd.date_range("2018-01-01","2018-01-05"))
s.describe() # includes first and last
s.dt.tz_localize('US/Eastern').describe() # does not include first and last
```
#### Problem description

The `describe` method on a timezone-naive datetime Series reports the "first" (min) and "last" (max) values. I would expect the same to be true for a timezone-aware datetime Series, since `min` and `max` are defined there as well.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Linux
OS-release: 4.13.0-43-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.0
pytest: 3.4.2
pip: 9.0.1
setuptools: 38.4.0
Cython: None
numpy: 1.14.3
scipy: 1.1.0
pyarrow: 0.9.0
xarray: None
IPython: 6.2.1
sphinx: 1.7.3
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: 0.4.0
matplotlib: 2.1.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: None
psycopg2: 2.7.4 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by mroeschke** [comment]
Thanks for the report; that definitely sounds reasonable. This block below needs some additional logic to handle timezone aware datetimes:

https://github.com/pandas-dev/pandas/blob/7dc6f7023ce439e8ef10ef336f314b10192911c5/pandas/core/generic.py#L8533-L8538

Pull requests are welcome!

**Comment by louispotok** [comment]
Right, looks like replacing that check with [`is_datetime64_any_dtype`](https://github.com/pandas-dev/pandas/blob/7dc6f7023ce439e8ef10ef336f314b10192911c5/pandas/core/dtypes/common.py#L1043) would catch the tz-aware ones.

Thanks, I'll try to get a PR in soon.
