### ISSUE TITLE
.any()  .all() behaviour in Empty DataFrame

### ISSUE THREAD

**Issue by gopaltirupur** [pandas-dev/pandas#21326]
#### Code Sample, a copy-pastable example if possible

```python
pd.DataFrame(columns=list('ABC')).any()
# for above getting all False, 

pd.DataFrame(columns=list('ABC')).all()
# for above getting all True.

```
#### Problem description

There is some gap logically, If any is false, obviously all should be false. But in actual it is True.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by jreback** [comment]
this is logically consistent with numpy (in fact what it is doing under the hood)
```
In [6]: pd.DataFrame(columns=list('ABC')).values.ravel().any()
Out[6]: False

In [7]: pd.DataFrame(columns=list('ABC')).values.ravel().all()
Out[7]: True

In [9]: np.array([]).any()
Out[9]: False

In [10]: np.array([]).all()
Out[10]: True

```
