### ISSUE TITLE
Pytest can't rewrite assertions in tests from imported modules

### ISSUE THREAD

**Issue by akaihola** [pandas-dev/pandas#21320]
```python
$ pytest -x pandas/tests/io/parser/test_parsers.py -k test_quoting
====================================== test session starts =======================================
platform linux -- Python 3.6.5, pytest-3.6.0, py-1.5.3, pluggy-0.6.0
rootdir: /tmp/pandas, inifile: setup.cfg
collected 840 items / 834 deselected                                                             

pandas/tests/io/parser/test_parsers.py F

============================================ FAILURES ============================================
_______________________________ TestCParserHighMemory.test_quoting _______________________________

self = <pandas.tests.io.parser.test_parsers.TestCParserHighMemory object at 0x7ff15a00d278>

    def test_quoting(self):
        bad_line_small = """printer\tresult\tvariant_name
    Klosterdruckerei\tKlosterdruckerei <Salem> (1611-1804)\tMuller, Jacob
    Klosterdruckerei\tKlosterdruckerei <Salem> (1611-1804)\tMuller, Jakob
    Klosterdruckerei\tKlosterdruckerei <Kempten> (1609-1805)\t"Furststiftische Hofdruckerei,  <Kempten""
    Klosterdruckerei\tKlosterdruckerei <Kempten> (1609-1805)\tGaller, Alois
    Klosterdruckerei\tKlosterdruckerei <Kempten> (1609-1805)\tHochfurstliche Buchhandlung <Kempten>"""  # noqa
        pytest.raises(Exception, self.read_table, StringIO(bad_line_small),
                      sep='\t')
    
        good_line_small = bad_line_small + '"'
        df = self.read_table(StringIO(good_line_small), sep='\t')
>       assert len(df) == 42
E       AssertionError

pandas/tests/io/parser/common.py:212: AssertionError
============================ 1 failed, 834 deselected in 0.41 seconds ============================
```
#### Problem description

In the above test case, I intentionally replaced the correct expected value with `42` to make the test fail. In Pytest output, the actual value of `len(df)` isn't displayed. This is because the actual test module is `test_parsers.py` but actual test code is in `common.py` which is imported into `test_parser.py`. Thus, Pytest doesn't know to rewrite the assertion and enhance the output.

#### Expected Output

```python
$ pytest -x pandas/tests/io/parser/test_parsers.py -k test_quoting
====================================== test session starts =======================================
platform linux -- Python 3.6.5, pytest-3.6.0, py-1.5.3, pluggy-0.6.0
rootdir: /tmp/pandas, inifile: setup.cfg
collected 840 items / 834 deselected                                                             

pandas/tests/io/parser/test_parsers.py F

============================================ FAILURES ============================================
_______________________________ TestCParserHighMemory.test_quoting _______________________________

self = <pandas.tests.io.parser.test_parsers.TestCParserHighMemory object at 0x7f090ab48240>

    def test_quoting(self):
        bad_line_small = """printer\tresult\tvariant_name
    Klosterdruckerei\tKlosterdruckerei <Salem> (1611-1804)\tMuller, Jacob
    Klosterdruckerei\tKlosterdruckerei <Salem> (1611-1804)\tMuller, Jakob
    Klosterdruckerei\tKlosterdruckerei <Kempten> (1609-1805)\t"Furststiftische Hofdruckerei,  <Kempten""
    Klosterdruckerei\tKlosterdruckerei <Kempten> (1609-1805)\tGaller, Alois
    Klosterdruckerei\tKlosterdruckerei <Kempten> (1609-1805)\tHochfurstliche Buchhandlung <Kempten>"""  # noqa
        pytest.raises(Exception, self.read_table, StringIO(bad_line_small),
                      sep='\t')
    
        good_line_small = bad_line_small + '"'
        df = self.read_table(StringIO(good_line_small), sep='\t')
>       assert len(df) == 42
E       assert 3 == 42
E        +  where 3 = len(  ...\n0 ...\n1 ...\n2 ...\n\n[3 rows x 3 columns])

pandas/tests/io/parser/common.py:212: AssertionError
============================ 1 failed, 834 deselected in 0.81 seconds ============================
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: 4274b840e64374a39a0285c2174968588753ec35
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.15-200.fc26.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: fi_FI.UTF-8
LOCALE: fi_FI.UTF-8

pandas: 0.24.0.dev0+51.g4274b840e.dirty
pytest: 3.6.0
pip: 9.0.3
setuptools: 37.0.0
Cython: 0.28.3
numpy: 1.14.3
scipy: None
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by akaihola** [comment]
Commit af8e068 above is an example of how to explicitly enable assert rewrites for a given module. If this solution is acceptable, I'm willing to copy it to all other test modules which share the same problem.

**Comment by jreback** [comment]
is this a documented pytest limitation?

**Comment by akaihola** [comment]
@jreback, yes it is. In Pytest documentation section *"The writing and reporting of assertions in tests"* under paragraph [Advanced assertion introspection](https://docs.pytest.org/en/latest/assert.html#advanced-assertion-introspection):

>`pytest` only rewrites test modules directly discovered by its test collection process, so asserts in supporting modules which are not themselves test modules will not be rewritten.
> [...]
> For further information, Benjamin Peterson wrote up [Behind the scenes of pytest’s new assertion rewriting](http://pybites.blogspot.com/2011/07/behind-scenes-of-pytests-new-assertion.html).

**Comment by mroeschke** [comment]
Looks like we don't have tests that exist in files that don't start with `test_*.py` so I don't think this is an issue anymore. Closing, but happy to reopen if necessary
