### ISSUE TITLE
how to group by date and unique each group and count each group

### ISSUE THREAD

**Issue by hoyeunglee** [pandas-dev/pandas#21338]
how to group by date and unique each group and count each group

currently only known group by, not know how to unique each group at mac address and then count
the number of mac address in each day

`pd.concat([df[['date','Client MAC']], df8[['date',"MAC address"]].rename(columns={"MAC address":"Client MAC"})]).groupby(["date"])
`

**Comment by TomAugspurger** [comment]
You  might try stackoverflow for usage questions. They're typically answered quickly and are easier to search for.
