### ISSUE TITLE
PeriodIndex.is_monotonic only for monotonic increasing

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#21335]
```
dti = pd.date_range('2016-01-01', periods=3)
pi = dti.to_period('D')

>>> pi.is_monotonic
True
>>> pi[::-1].is_monotonic
False
```

**Comment by gfyoung** [comment]
Oops.  Patch is most welcome!

**Comment by uds5501** [comment]
@jbrockmendel  I guess you would like to check out pandas 0.23.0 documentation where it is stated that **series.is_monotonic** returns  boolean if values in the object are monotonic_increasing.

If you want to check the monotnicity of the series, how about using this:
`>>> pi[::-1].is_monotonic_increasing or pi[::-1].is_monotonic_increasing`

**Comment by gfyoung** [comment]
@uds5501 : That's a good point.  I forgot about that myself 😂 

That being said, it does seem a little counter-intuitive, especially since we have *both* `is_monotonic_increasing` and `is_monotonic_decreasing`.
