### ISSUE TITLE
Timestamp.resolution returns timedelta(microseconds=1)

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#21336]
I hadn't even noticed that `resolution` was a `datetime` property until now, but it returns `timedelta(0, 0, 1)`.  `Timestamp` doesn't override that.  I expect the correct thing to do is to return `Timedelta(nanoseconds=1)`.  Pretty low priority.

**Comment by gfyoung** [comment]
> Pretty low priority.

@jbrockmendel : How easy would it be to patch?

**Comment by jbrockmendel** [comment]
super-duper easy.  Might merit a "Good First Issue" tag.

**Comment by gfyoung** [comment]
> Might merit a "Good First Issue" tag.

Then let's label as such.  Done.

**Comment by uds5501** [comment]
@jbrockmendel @gfyoung  Any guidance for the patch of the same?

**Comment by jbrockmendel** [comment]
You'll want to define a property on the `Timestamp` class that just returns `Timedelta(nanoseconds=1)`.  For the sake of thoroughness you'll need a super-simple test in `pandas.tests.scalar.timestamp.test_timestamp`.

**Comment by drewmassey** [comment]
So I'm looking [https://github.com/pandas-dev/pandas/blob/9d61ab5aae0dd4ca3f805275c6a8ebcaeef77d64/pandas/_libs/tslibs/timedeltas.pyx#L797](at the source) and I think fixing this would be breaking change ... it isn't hard to change the return values but is that really the desired behavior?

**Comment by mroeschke** [comment]
@drewmassey your snippet is looking at `timedeltas.pyx` (which has a relevant resolution issue open #21344). This issue would entail changing `timestamp.pyx`
