### ISSUE TITLE
to_period is dropping timezone information

### ISSUE THREAD

**Issue by mungojam** [pandas-dev/pandas#21333]
```python
localSeries = pd.date_range("2018-7-1", periods=1, freq="30T", tz="Europe/London")
print(localSeries.to_period("30T")[0].start_time)
#Timestamp('2018-07-01 00:00:00')
print(localSeries.to_period("30T")[0].start_time.tz)
#None
print(localSeries.to_period("30T")[0].end_time.tz)
#None
print(localSeries[0].tz)
#<DstTzInfo 'Europe/London' BST+1:00:00 DST>
```

While this may be useful for monthly/quarterly granularity data, it causes a problem for half-hourly data or similar around clock change, because the local times are used but the time-zone knowledge is dropped without warning.

**Comment by gfyoung** [comment]
In general, it seems that timezone is dropped, even when you just instantiate a `PeriodIndex`.  Not if that's by design.  If I piggy-back off your example:

~~~
pd.PeriodIndex([localSeries[0]], freq="30T")[0].start_time.tz
# None
~~~

cc @jreback

**Comment by mungojam** [comment]
While full timezone support would be nice, the bigger issue for us was the silent dropping of them. 

Everywhere else I've seen in Pandas timezones are treated very safely
