### ISSUE TITLE
usage question: can I concat rows using first value as additional index?

### ISSUE THREAD

**Issue by aabustamante** [pandas-dev/pandas#21349]
Hi, everyone.
I should probably start saying that **this is a usage question**.
Version: 0.23.0

honestly I have been trying to find out how to do this consulting the docs and looking for similar questions but didn't find anything.

I want to ask you for suggestions for next scenario:

The main goal is to filter data but my problem is that each register occupies 2 rows.

I have an html with next table structure:
headers at the top but every register has a second row where the first column value could be treated as a header:

| Father name  | Mother name | Married |
| ------------- | ------------- | ------ |
| John Doe  | Jane Doe  | 6 years |
| **Son name:**  | Junior Doe  | |
| John Doe 2  | Jane Doe 2 | 2 years |
| **Son name:**  | Junior Doe 2 | |

In this table we can observe the headers "Father name" and "Mother name" but also we can observe a cell with value: "Son name:" where its corresponding value would be the next column string like "Junior Doe".

After using `read_html` method I have something similar to:
| ---- | --------- | ------- | ------- |
| 0 | John Doe  | Jane Doe  | 6 years |
| 1 | **Son name:**  | Junior Doe  | nan |
| 2 | John Doe 2  | Jane Doe 2 | 2 years |
| 3 | **Son name:**  | Junior Doe 2 | nan |

So.. the problem is that the "Son name:" is that rows 0 & 1 should be treated as one register instead of two. same for 2 & 3.

I would like to get something like:
| 0 | John Doe  | Jane Doe  | 6 years | Junior Doe
| 1 | John Doe 2  | Jane Doe 2 | 2 years | Junior Doe 2

I've been trying to use Multi index but haven't had luck with it, maybe I'm using it wrong.
Do you have any suggestions for this scenario?

**Comment by WillAyd** [comment]
There are quite a few options but unfortunately this isn’t the right forum for questions like these. You are much better served putting something like this on StackOverflow where it can be voted and reviewed by a larger community.

 By contrast, this issue tracker is used for bug reports and enhancement requests, so I’m going to close this out
