### ISSUE TITLE
Incorrect implementation of the ExtensionArray API in tests

### ISSUE THREAD

**Issue by wisp3rwind** [pandas-dev/pandas#21343]
I believe that
https://github.com/pandas-dev/pandas/blob/0c65c57a279e755ab7093db925d1e580f9878dae/pandas/tests/extension/decimal/array.py#L48
should read
```python
        return cls(original.take(values))
```
Same as reported at https://github.com/ContinuumIO/cyberpandas/issues/33,  @TomAugspurger

**Comment by jorisvandenbossche** [comment]
I think the implementation is correct. `_from_factorized` does not get the integer*codes*, but the uniques. 
See the base implementation: 

https://github.com/pandas-dev/pandas/blob/0c65c57a279e755ab7093db925d1e580f9878dae/pandas/core/arrays/base.py#L454-L460

The reason that we need `_from_factorized` is that you might return different values in `_values_for_factorize` that have to be re-converted to actual extension array elements. 
But in the case of the DecimalArray it uses the default for `_values_for_factorize` which is the object array, and this then converts also back into a DecimalArray without anything special.

That said, the documentation (docstring of `from_factorized`) can certainly be improved to make this clearer.

**Comment by jorisvandenbossche** [comment]
See eg here for a more custom `_from_factorize`: https://github.com/geopandas/geopandas/pull/701/files#diff-f6d9d27a6d64f2c7bb9f16c4caf50eb5R502 (where I convert my geometries to binary blobs to factorize them, and thus in `_from_factorized` need to convert the binaries back to actual geometry objects)

**Comment by wisp3rwind** [comment]
Thanks for the explanation, that makes a lot more sense. You're right that I hadn't properly understood what these functions are supposed to do from the docstrings. Then I grepped for usage examples, ended up at `categorical.py` and misunderstood what that did.

An example just like

> where I convert my geometries to binary blobs to factorize them, and thus in _from_factorized need to convert the binaries back to actual geometry objects

would be great to have for clarification.

**Comment by jbrockmendel** [comment]
Is there anything left to do here?

**Comment by wisp3rwind** [comment]
> Is there anything left to do here?

No idea, I don't remember what my conclusion on all of this was. Given that no-one has commented here in years, probably all is fine?
