### ISSUE TITLE
CI: Enable spellcheck in docbuild

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#21354]
Followup to https://github.com/pandas-dev/pandas/pull/21109

We'll need to refactor `scripts/announce.py` to update the list of contributors on each build.

Then we can enable spellcheck in the Travis doc build.

**Comment by FabioRosado** [comment]
I would like to take on this since this is related to my previous PR 😄

**Comment by FabioRosado** [comment]
@daminisatya Apologies I had this tab open and your comment didnt show but you beat me to it so if you would like to take on this issue go ahead 😄 👍

**Comment by WillAyd** [comment]
@daminisatya since you marked interest in this and the JSON issue how about you tackle the JSON one as a first contribution and let @FabioRosado continue with this one, since this is a logical follow up to a change he just made?

**Comment by daminisatya** [comment]
Yes @WillAyd, I was about to comment the same :) @FabioRosado you can go ahead with the issue since you have already solved it you will have a better context than me! I took up another first-timer issue.

**Comment by FabioRosado** [comment]
I am having a bit of issue with this script, when I run the command `./announce.py $GITHUB v1.11.0..v1.11.1 > announce.rst` from the script folder I get the error message `announce.py: error: unrecognized arguments: v1.11.0..v1.11.1` but the example given in the file says that this should work.

Is the script broken at the moment or is just some issue that I am having?

**Comment by afeld** [comment]
Update: Appears this was added and then subsequently removed. In https://github.com/pandas-dev/pandas/pull/24287, the comment that:

> The spellcheck system was implemented, but with dependencies (i.e. `enchant`) that are no longer maintained, and there is no reasonable way to set them up.

doesn't seem to be true anymore. I'm seeing releases for both [enchant](https://github.com/AbiWord/enchant/releases) and [pyenchant](https://pypi.org/project/pyenchant/#history) in December 2020. In other words, I think we should consider adding spellcheck back in.

**Comment by afeld** [comment]
Currently we run [`codespell`](https://github.com/codespell-project/codespell) on the source code, minus the test suite. 

https://github.com/pandas-dev/pandas/blob/00ddacfa191734adcd7a062e336e5625ea65605f/.pre-commit-config.yaml#L202-L205

We could expand it to the docs and see how it compares…?

**Comment by MarcoGorelli** [comment]
@afeld yes, there's an open issue about that #38802

**Comment by afeld** [comment]
Seems like the issues are duplicates, so closing this one for now.
