### ISSUE TITLE
Revert changes to comparison between Series[datetime64ns] and datetime.date

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#21359]
Revert the changes in https://github.com/pandas-dev/pandas/pull/21361

- [ ]: Remove check in `core/ops.py`
- [ ]: Remove test `pandas/tests/tseries/test_arithmetic.py::TestTimestampSeriesComparison.test_dt64_ser_cmp_date_warning`
- [ ]: Reenable test `pandas/tests/tseries/test_arithmetic.py::TestTimestampSeriesComparison.test_dt64ser_cmp_date_invalid`

Target this for 0.24?

xref https://github.com/pandas-dev/pandas/issues/21152

**Comment by TomAugspurger** [comment]
@jreback @jorisvandenbossche can we do this for 0.24.0? That would mean

- <0.22 : compare equal
- 0.23.0 : compare unequal
- >=0.23.1,<0.24.0 : compare equal & warn
- 0.24.0 : compare unequal

**Comment by jreback** [comment]
that looks good to me

**Comment by jorisvandenbossche** [comment]
We typically have deprecations for longer than a single release. Is there a good reason to not do that here? 
(it's not that the current situation is actively harmful or so)

**Comment by TomAugspurger** [comment]
If this were the behavior in 0.23.0, I would agree with a longer deprecation cycle. Should the fact that 0.23.0 and 0.23.1 behave differently change our thoughts at all? (I'm not sure really)

**Comment by jorisvandenbossche** [comment]
I don't think that that is a reason to have a shorter deprecation cycle (at least it does not give any problems with the different behaviour, as if you already changed your code to the correct way when using 0.23.0, this will also work for the later versions with the reverted comparison op)

**Comment by jbrockmendel** [comment]
https://github.com/pandas-dev/pandas/issues/21359#issuecomment-395749008 looks like the plan was to implement the new behavior in 0.24.0.  Any objection to doing it now?
