### ISSUE TITLE
ENH: Add timetz attribute to DatetimeIndex and Timestamp

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#21358]
Currently `DatetimeIndex.time` returns a numpy array of local `datetime.time`s. In #18461, the resulting `datetime.time`s gained timezone information (but was an undocumented changed) and was subsequently reverted in #21281. Having `.time` return timezone information would still be a nice enhancement.

If we allow `DatetimeIndex.time` to return timezone information, [`timeseries.rst`](http://pandas.pydata.org/pandas-docs/stable/timeseries.html?highlight=weekofmonth#time-date-components) will need to be changed since it currently indicates that `.time` does not return timezone information.

**Comment by mroeschke** [comment]
Go for it @jquinon! The main job would be to undo the revision in #21281 make sure this change is documented.

**Comment by mroeschke** [comment]
So now `DatetimeIndex.time` matches `datetime.time()` (minus the property vs method difference) which is an ideal consistency.

However, there is a `datetime.timetz()` method that returns time with timezone information. We could match the api and have a `DatetimeIndex.timetz` method, but I am not the biggest fan of the name.

I would prefer instead having `DatetimeIndex.time(tz=False)` that would match the method-like `time` api of the standard library, but use a keyword arg to return tz information.

Thoughts?

**Comment by jreback** [comment]
yeah that would be ok except it’s current a property - not sure we can change this

**Comment by jorisvandenbossche** [comment]
I am not sure this (adding a tz keyword) is worth the API change. Changing from a attribute to method is a quite big change, as every use of the current attribute would be impacted.

**Comment by mroeschke** [comment]
Fair enough. Should we then mimic the standard library and add a `.timetz` property?

**Comment by jorisvandenbossche** [comment]
> Should we then mimic the standard library and add a .timetz property?

I personally don't really care about adding it, but also won't object if others want it.

**Comment by mroeschke** [comment]
Yeah `timetz` would probably 

@jquinon if you're up for a PR to add a `timetz` property to `Timestamp` and `DatetimeIndex`

**Comment by mroeschke** [comment]
@jquinon if you're interested to add a timetz property to `DatetimeIndex` and `Timestamp`

**Comment by jquinon** [comment]
If everyone is cool with it then sure. @jreback

**Comment by jreback** [comment]
yep this sounds ok
