### ISSUE TITLE
a suggestion on sort_index() in pandas

### ISSUE THREAD

**Issue by AsprinChina** [pandas-dev/pandas#21375]
```python
    # in lexsort_indexers() which is called in sort_index()
    # the original codes
    # if isinstance(orders, bool):
    #     orders = [orders] * len(keys)
    # elif orders is None:
    #     orders = [True] * len(keys)
    # the changed codes
    if orders:
        orders = [True] * len(keys)
    elif orders is None:
        orders = [True] * len(keys)
    else:
        orders = [False] * len(keys)

```
#### Problem description

Since there is "1==True" and "0==False" in Python,  I usually use 0/1 to replace False/True which is more convenient (Maybe this is not a good habit). In most case, it works as expected because the judge sentence is usually 
```python
       if bool:
              ……
       else:
             ……
```

As usual, I wrote "dataframe.sort_index(level=0, axis=1, ascending=0)" in my codes. However, there came an error this time. I checked the code and then found that the value of 'ascending' was passed to a variable named 'orders' which is a parameter of function "lexsort_indexer()" in sorting.py. 
The codes in lexsort_indexer() : 
```python
def lexsort_indexer(keys, orders=None, na_position='last'):
    from pandas.core.categorical import Categorical
    labels = []
    shape = []
    if isinstance(orders, bool):
        orders = [orders] * len(keys)
    elif orders is None:
        orders = [True] * len(keys)
    ……
```
Since 0 is neither bool type or None, th orders was unchanged and then there is an error. In order to make the code more compatible, I change the judge sentence as follows:
```python
    if orders:
        orders = [True] * len(keys)
    elif orders is None:
        orders = [True] * len(keys)
    else:
        orders = [False] * len(keys)
```
Will this suggestion be accepted in the next version of pandas?

#### Expected Output
dataframe.sort_index(level=0, axis=1, ascending=0)
0 error

**Comment by gfyoung** [comment]
@AsprinChina : Thanks for reporting this!  This is an interesting suggestion, but it would be a huge change admittedly, since we would have to propagate this across the entire codebase.

FWIW, it seems like `numpy` accepts boolean and integer (though not just 0 and 1) inputs for its boolean flags, for better or worse.

@jreback @jorisvandenbossche : Thoughts?

**Comment by jreback** [comment]
we are quite strict on this to avoid errors
we on purpose require bools as shown in the signature.
