### ISSUE TITLE
DOC: Pandas Logo

### ISSUE THREAD

**Issue by gfyoung** [pandas-dev/pandas#21376]
Several people have expressed interest.  Just collecting usernames here:

@joelostblom https://github.com/pandas-dev/pandas/issues/3825#issuecomment-392896641
@nunojesus https://github.com/pandas-dev/pandas/issues/21371
@tswast https://github.com/pandas-dev/pandas/issues/21376#issuecomment-475911516

To anyone else who encounters this and wants to express interest, just add a comment, and we'll add your name to this list!

**Comment by joelostblom** [comment]
@gfyoung Thanks for creating a new issue for this discussion!

Would you want us to go ahead and develop suggestions for the logo design or first await feedback from the dev community whether a new logo is wanted?

**Comment by gfyoung** [comment]
@joelostblom : Let's await feedback on this.  If there is interest, there probably will be additional input from others that would be useful in incorporating.

@jreback @jorisvandenbossche : Thoughts?

**Comment by tswast** [comment]
I'm interested in this, either contributing (though there are probably better designers than me interested) or just as someone who'd like to see a more beautiful logo.

**Comment by tswast** [comment]
In the meantime, I guess the favicon could be the de-facto logo when a square logo is needed?

![pandas_logo-export](https://user-images.githubusercontent.com/247555/54872684-0a482480-4d85-11e9-9685-ed517c068627.png)

**Comment by gfyoung** [comment]
@tswast : We're happy to take suggestions!  If you have ideas, please do share them here!
