### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nunojesus** [pandas-dev/pandas#21371]
Hi Hello I am looking for open source projects to contribute graphical design, I have done several jobs for free in opensource projects, I would like to know if you are interested that I make a logo for this your project ?.

Greetings

Nuno Jesus

**Comment by gfyoung** [comment]
@nunojesus : Thanks for the offer!  From the looks of https://github.com/pandas-dev/pandas/issues/3825, I'm not sure if there is a lot of interest, but perhaps it would be best to collect names of those who have expressed interest.

**Comment by gfyoung** [comment]
Closing in favor of #21376.
