### ISSUE TITLE
TST: add additional test cases for pivot_table with categorical data

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#21370]
xref https://github.com/pandas-dev/pandas/pull/21252#discussion_r191665246

Add additional test cases for:

Using the same definition of `df` as you used in your test, `columns`/`values` is incorrect:
```python
In [3]: pd.__version__
Out[3]: '0.23.0'

In [4]: df.pivot_table(columns='A', values='B')
Out[4]:
A  NaN  low
B  2.0  3.0
```

Similarly `index`/`columns`/`values` is incorrect:
```python
In [5]: df['AA'] = df['A']

In [6]: df.pivot_table(index='A', columns='AA', values='B')
Out[6]:
AA   NaN  low
A
NaN  2.0  NaN
low  NaN  3.0
```

**Comment by uds5501** [comment]
@jorisvandenbossche  if this issue is still open, I would like to take this one up!

**Comment by gfyoung** [comment]
@uds5501 : This is definitely still fair game.  Go for it!
