### ISSUE TITLE
Possible inconsistency between creation of Series and DataFrame with list of dicts

### ISSUE THREAD

**Issue by elDan101** [pandas-dev/pandas#21395]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd


# skip block when no sklean is installed

# I simply show where the list of dicts come from:
from sklearn.model_selection import ParameterGrid
par_grid = ParameterGrid({"x": [0,1,2,3]})
lod = list(par_grid)  
# Output:
# [{'x': 0}, {'x': 1}, {'x': 2}, {'x': 3}]

# end block

lod = [{'x': 0}, {'x': 1}, {'x': 2}, {'x': 3}]

pd.DataFrame(lod)

#Output:
#     x
# 0  0
# 1  1
# 2  2
# 3  3

pd.Series(lod)

# Output:
# 0    {'x': 0}
# 1    {'x': 1}
# 2    {'x': 2}
# 3    {'x': 3}
# dtype: object

```
#### Problem description

I am not sure whether this is actually an issue or wanted behaviour. But I expected for the two cases (DataFrame and Series) a similar output as below: 

#### Expected Output

```python
pd.Series([e["x"] for e in lod], name="x")
#or:
pd.DataFrame(lod).iloc[:, 0]

# Output:
# 0    0
# 1    1
# 2    2
# 3    3
# Name: x, dtype: int64

```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.13.0-43-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.0
pytest: None
pip: 10.0.1
setuptools: 39.2.0
Cython: None
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.4
patsy: None
dateutil: 2.7.2
pytz: 2018.3
blosc: None
bottleneck: None
tables: 3.4.3
numexpr: 2.6.4
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.9999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by WillAyd** [comment]
DataFrame and Series are two distinct objects with different shapes so no it shouldn't be expected for their constructors here to return the same exact object. If the Expected Output is what you want then you shouldn't be calling the DataFrame constructor at all, as your desired output is in fact a Series.

**Comment by elDan101** [comment]
> DataFrame and Series are two distinct objects with different shapes so no it shouldn't be expected for their constructors here to return the same exact object.

That was not my point and I am clear that this would not make sense. 

At the moment I have

```python
if dimension == 1:
   pd.Series(lod)
else:
   pd.DataFrame(lod)
```

The input is always a list of dicts (1D or nD) but the Series part is different to what I'd expect from a DataFrame.

But okay, I already use the code from the expected output as a workaround.
