### ISSUE TITLE
Resample function documentation does not explain 'how' argument 

### ISSUE THREAD

**Issue by MikeWoodward** [pandas-dev/pandas#21463]
Current documentation for resample function does not document 'how' argument:

[Resample documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.resample.html)

Previous versions of Pandas did document this argument:

[Old resample documentation](https://pandas.pydata.org/pandas-docs/version/0.17/generated/pandas.DataFrame.resample.html)

**Comment by WillAyd** [comment]
This was deprecated quite some time ago:

https://github.com/pandas-dev/pandas/commit/14cf67fbb25c1695fd126ab034af2218d04c154c
