### ISSUE TITLE
is_list_like missing implementation

### ISSUE THREAD

**Issue by G-Demleitner** [pandas-dev/pandas#21483]
in `pandas_datareader` file `fred.py`you find:
```
from pandas.core.common import is_list_like
```
but it is not implemented any more. Some software relies on it, p.e. Orange3 Time Series

**Comment by jorisvandenbossche** [comment]
The import from `pandas.core.common` was deprecated, and this is also already fixed on pandas-datareader in master. You can ask there when they will make a new release: https://github.com/pydata/pandas-datareader
