### ISSUE TITLE
not able to read the whole content of a cell

### ISSUE THREAD

**Issue by saivenkatthatikonda7** [pandas-dev/pandas#21488]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd
df = pd.read_excel('Financial Sample.xlsx')
print df


```
#### Problem description

My excel sheet has a column in which people can enter number of words but when i am reading it through pandas it is only taking up to 45 characters and the rest of it is printed as ". . ."

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Expected Output
The pandas ecel reader should read the whole cell in the excel file

#### Output of ``pd.show_versions()``
the output is like follows:

<details>

[paste the output of ``pd.show_versions()`` here below this line]
3    https://www.crowdfundinsider.com/2017/12/12589...  
where the dot's represent more data but it is not getting printed. 
</details>

**Comment by WillAyd** [comment]
It sounds like this is just a matter of how items are being displayed in your terminal, so I'd suggest messing around with display options to see what you want.

If however that's not the case please re-open with a reproducible example:

http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by saivenkatthatikonda7** [comment]
Thank you very much for your response, I tried different ways and tried in
different ide's but the read_excel function does not read more than 45
charecters. That is if a cell of the excel sheet has more than 45 letters
in it then the rest of the data is being printed as "...".  I will open the
issue like you said.
ᐧ

**Comment by saivenkatthatikonda7** [comment]
Thank you very much for your response, I tried different ways and tried in
different ide's but the read_excel function does not read more than 45
charecters. That is if a cell of the excel sheet has more than 45 letters
in it then the rest of the data is being printed as "..."
ᐧ
