### ISSUE TITLE
[question] Coverage when "slow" tests are disabled.

### ISSUE THREAD

**Issue by CDLuminate** [pandas-dev/pandas#21492]
We are going to disable those "slow" tests on non-x86 architectures for Debian, such that the package build time could be significantly reduced (e.g. armhf, with "slow" = 6 hrs, without "slow" = 2 hrs).

Does that affect the code coverage?

**Comment by CDLuminate** [comment]
@ginggs

**Comment by WillAyd** [comment]
Yes that would affect code coverage. 

^ don't mean that to be overly blunt just not sure how exactly else to answer :-)

**Comment by CDLuminate** [comment]
Thanks for the reply. So we should enable them as long as possible.

**Comment by WillAyd** [comment]
Yes - otherwise you will lose some test coverage. 

Closing this for now as I don't think there's any action needed on our end but if you disagree feel free to reopen
