### ISSUE TITLE
TST: Use numeric dtype fixtures for testing

### ISSUE THREAD

**Issue by jschendel** [pandas-dev/pandas#21500]
Some new numeric dtype fixtures were implemented in #21432:
https://github.com/pandas-dev/pandas/blob/9e982e18678c47c83ce2bb5932f844e2d9ee21f3/pandas/conftest.py#L183-L243

It would be nice to use these fixtures where appropriate in the existing tests, e.g.
https://github.com/pandas-dev/pandas/blob/9e982e18678c47c83ce2bb5932f844e2d9ee21f3/pandas/tests/indexes/datetimes/test_construction.py#L527-L528

Additional comments:
- These changes can be split across multiple PR's so no need to do all changes at once
  - Not how many instances of this will need to be replaced, so this will need to be investigated
- This might involve expanding the dtype coverage for some tests
   - The example test shown above could also be tested over uint dtypes
- Can probably drop `float16` dtypes from tests since it's barely supported
  - See https://github.com/pandas-dev/pandas/pull/21432#discussion_r194702410
- Might be necessary to create additional fixtures
   - Perhaps a fixture for the combination of float + signed integer + unsigned integer dtypes

**Comment by gfyoung** [comment]
They have propagated since this issue was opened.
