### ISSUE TITLE
read_excel function not reading the whole data in a cell if it has more than 45 charecters.

### ISSUE THREAD

**Issue by saivenkatthatikonda7** [pandas-dev/pandas#21505]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd
df =pd.read_excel('Financial Sample1.xlsx')
print (df)
```
#### Problem description
I have already posted my issue before. The read_excel function is not able to read the excel sheet is only reading a part of the cells which has more than 45 characters in it. for example if the excel cell has the data : " this is github and i am posting an issue here about pandas so i want the solution" then it reads as follows: "his is github and i am posting an issue here about pandas . . . ". so the data in the cells which has lot of characters is getting trimmed.
[sample.xlsx](https://github.com/pandas-dev/pandas/files/2107655/sample.xlsx).

I am attaching the excel file which i used for extracting data in which many cells have data more than 45 characters. 

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by mroeschke** [comment]
Please refer to @WillAyd explanation, https://github.com/pandas-dev/pandas/issues/21488#issuecomment-397500951

```
In [1]: data = [" this is github and i am posting an issue here
   ...: about pandas so i want the solution"]

In [2]: s = pd.Series(data)

In [3]: s
Out[3]:
0     this is github and i am posting an issue here...
dtype: object

In [4]: s.iloc[0]
Out[4]: ' this is github and i am posting an issue here about pandas so i want the solution'

In [5]: s.to_excel('test.xlsx')

In [6]: s1 = pd.read_excel('test.xlsx')

In [7]: s1
Out[7]:
                                                   0
0   this is github and i am posting an issue here...

In [8]: s1.iloc[0, 0]
Out[8]: u' this is github and i am posting an issue here about pandas so i want the solution'
```
