### ISSUE TITLE
[DOC]: Explain the choice of absolute/relative tolerance for check_less_precise in assert_almost_equal

### ISSUE THREAD

**Issue by rs2** [pandas-dev/pandas#21528]
The docstring in https://github.com/pandas-dev/pandas/blob/9e982e18678c47c83ce2bb5932f844e2d9ee21f3/pandas/util/testing.py#L226-L229 does not specify how the number of decimal digits is going to be used, yet https://github.com/pandas-dev/pandas/blob/9e982e18678c47c83ce2bb5932f844e2d9ee21f3/pandas/_libs/testing.pyx#L203-L210 switches between absolute and relative tolerance depending on the (hardcoded) magnitude on the number.

**Comment by gfyoung** [comment]
@rs2 : Good catch!  Would you like to submit a patch for the docs?

**Comment by gfyoung** [comment]
Marking for `0.23.2`, as this is a relatively trivial thing that we should be able to get in (I can bring this to the finish line if others are unable to do so).

**Comment by jorisvandenbossche** [comment]
@gfyoung removed the milestone. You are of course welcome to do a PR, but I want to keep the milestone focused on the ones that are important for 0.23.2
