### ISSUE TITLE
ENH: allow ranges to be set on Styler .bar()

### ISSUE THREAD

**Issue by psychemedia** [pandas-dev/pandas#21526]
When generating in table bar charts using the [Styler `.bar()`](https://github.com/pandas-dev/pandas/blob/master/pandas/io/formats/style.py):

- extreme outliers in a column mask differences in other values;
- comparisons across columns are not supported.

One solution would be to allow the setting of explicit bounds on the range of values used to limit the bar extrema using explicit values rather than `s.min()` and `s.max()`.

Cell values exceeding the range limits could be extending to the cell edge / maximum limit value and then coloured with an "overflow" colour.

**Comment by psychemedia** [comment]
Pandas version 0.23.0

In the following example a dataframe is created with a column containing two outlier values (`x1`) and two columns where it would be useful to depict and compare the values over the same range even though in this example the ranges differ:

```
import pandas as pd
import numpy as np

df=pd.DataFrame({'x1':list(np.random.randint(-10,10,size=10))+[-500,1000, -1000],
               'y1':list(np.random.randint(-5,5,size=13)), 'y2':list(np.random.randint(-2,3,size=13)) })

df.style.bar( align='zero', color=[ '#5fba7d','#d65f5f'])
```

In column `x1`, the outlier values set the max/min range values used to display the styled bar and the variation in the non-outlier values is masked. It would be useful to be able to set max / min limits to so that variation in the non-outlier values can be depicted. For example, setting `min,max=(-10,10)` and then colouring squares with outlier values [-500,1000, -1000] differently to show they are outside the depicted range.

For columns `y1` and `y2`, it may be desired to display the bars over the same range, for example `min,max=(-5,5)` so that a direct visual comparison can be made across columns `y1` and `y2`.

**Comment by soxofaan** [comment]
FYI: pull request #21548  now includes support for `vmin` and `vmax` arguments in `Styler.bar`

**Comment by domoritz** [comment]
Is there a way to set the color range in the currently released pandas version?

**Comment by soxofaan** [comment]
@domoritz  there is a `color` argument, see http://pandas.pydata.org/pandas-docs/stable/generated/pandas.io.formats.style.Styler.bar.html . Also: please specify which pandas version you are using ("currently released" doesn't say a lot).

**Comment by attack68** [comment]
this issue would appear to be solved by the above PRs and acceptance by OP.
