### ISSUE TITLE
Support set the key of index from "index" to df.index.name in df.to_dict() when orient="split"

### ISSUE THREAD

**Issue by DataMonk2017** [pandas-dev/pandas#21538]
#### Code Sample, a copy-pastable example if possible
When I use to_dict() to convert the dataframe to dict in "split" mode. I just found that the key of index can not be changed. Is that possibile that to add a support: change the key of index from "index" to df.index.name or any way that I can change the key of index?
```python
df.to_dict(orient="split")
#Now what looks like is 
#result is
{'columns': [something,],
 'data': [[something],
  [something],
  [something],
 'index': [something]}


#what I want is
df.index.name = "name" #or some other ways that I can change the "index"
 
{'columns': [something,],
 'data': [[something],
  [something],
  [something],
 'name': [something]}
```

**Comment by uds5501** [comment]
@DataMonk2017  If this is what I think it is ( A usage question for changing `df` index names) I'd like you to refer to the `df.rename` feature.
One example which could be useful for you : 
```python
df = pd.DataFrame([[0,1,"Foo"],["bar",2,3]], columns = ["yo","vo","zo"], index=["lol","zol"])
>>> df
      yo  vo   zo
lol    0   1  Foo
zol  bar   2    3

df.rename(index = {'lol' : 'red'}, inplace=True)
      yo  vo   zo
red    0   1  Foo
zol  bar   2    3
```

**Comment by DataMonk2017** [comment]
@uds5501 Please forgive my ambiguity. The problem I face is that I want to change the behavior of `to_dict(orient="split")`. If I use the function, the result should be like below. I want change this dict keys' name. In other words， 'columns','data','index' are keys of the dict below. I would like to change them to other drirectly using `to_dict(orient="split")`.
Data Result is
{**'columns'**: [something,],
 **'data'**: [[something],
  [something],
  [something],
 **'index'**: [something]}`

**Comment by WillAyd** [comment]
`orient='table'` will preserve your index name, so you should use that format instead

**Comment by janosh** [comment]
@WillAyd [From the docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_dict.html), it seems like `to_dict(orient='table')` is no longer supported?

```py
import pandas as pd

df = pd.DataFrame([[1, 2], [3, 4]], columns=["a", "b"]).set_index("a")

df.to_dict(orient='table')
>>> ValueError: orient 'table' not understood
```

What's the recommended way of retaining index names with `to_dict` now? My reason for asking is explained in this issue hackingmaterials/matminer#648
