### ISSUE TITLE
Unexpected behaviour of apply function

### ISSUE THREAD

**Issue by Rgitz-setuserv** [pandas-dev/pandas#21535]
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import pandas as pd

tmp = np.array([[1,1,1], [1,0,0], [1,1,0], [1,1,0]])
tmp_df = pd.DataFrame(tmp)

tmp_df.apply(lambda x: x[x==1].index.tolist() , axis=1) # throws ValueError [I]
Out[0]:
ValueError: could not broadcast input array from shape (2) into shape (3)

tmp_df.apply(lambda x: [x[x==1].index.tolist()] , axis=1) # This doesn't throw Error [II]
Out[1]: 
0    [[0, 1, 2]]
1          [[0]]
2       [[0, 1]]
3       [[0, 1]]
dtype: object

tmp2 = np.array([[1,0,0], [1,0,0], [0,1,1]])
tmp2_df.apply(lambda x: x[x==1].index.tolist(), axis=1)  # This works
Out[2]: 
0       [0]
1       [0]
2    [1, 2]
dtype: object

```
#### Problem description
my pandas version is v0.22.0 and numpy version is 0.14.0
The expected output of [I] is a Series containing a list in each row but it's throwing an ValueError. 

#### Expected Output
[I] should return,
0    [0, 1, 2]
1          [0]
2       [0, 1]
3       [0, 1]

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Darwin
OS-release: 17.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
pandas: 0.22.0
pytest: 3.4.0
pip: 9.0.1
setuptools: 38.5.1
Cython: 0.27.3
numpy: 1.14.0
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.7.0
patsy: 0.5.0
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: 1.2.1
tables: None
numexpr: 2.6.4
feather: None
matplotlib: 2.1.2
openpyxl: 2.5.0
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.9999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by uds5501** [comment]
@Rgitz-setuserv This is my output for your given code. And apparently everything is up and running

```python
>>> import numpy as np
>>> import pandas as pd
>>> tmp = np.array([[1,1,1], [1,0,0], [1,1,0], [1,1,0]])
>>> tmp_df = pd.DataFrame(tmp)
>>> tmp_df
   0  1  2
0  1  1  1
1  1  0  0
2  1  1  0
3  1  1  0

>>> pd.__version__
'0.24.0.dev0+122.g6131a59'
>>> tmp_df.apply(lambda x: x[x==1].index.tolist() , axis=1) # throws ValueError [I]
0    [0, 1, 2]
1          [0]
2       [0, 1]
3       [0, 1]
dtype: object

>>> tmp_df.apply(lambda x: [x[x==1].index.tolist()] , axis=1) # This doesn't throw Error [II]
0    [[0, 1, 2]]
1          [[0]]
2       [[0, 1]]
3       [[0, 1]]
dtype: object

>>> pd.DataFrame(tmp2).apply(lambda x: x[x==1].index.tolist(), axis=1)  # This works
0       [0]
1       [0]
2    [1, 2]
dtype: object
```

I guess nothing throws value error as of yet, I suggest you to upgrade to latest pandas version or build from `master`

@gfyoung  : Shall I add a test case for closing this issue?

**Comment by gfyoung** [comment]
@uds5501 : Yes, by all means!

**Comment by gfyoung** [comment]
Marking for `0.23.2`, as this should be relatively trivial to bring to the finish line (I can do so if @uds5501 or anyone else is unable to do so).

**Comment by Rgitz-setuserv** [comment]
@uds5501 @gfyoung I'll try upgrading to newer version n see if it helps

**Comment by uds5501** [comment]
@Rgitz-setuserv Sounds good! I shall now add the test cases

**Comment by Rgitz-setuserv** [comment]
@uds5501 sure

**Comment by jreback** [comment]
already fixed in master
