### ISSUE TITLE
to_csv decimal is not vorking

### ISSUE THREAD

**Issue by AndreiKeino** [pandas-dev/pandas#21556]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd
fname = 'data.csv'
df = pd.read_csv(fname, decimal=',')
df.to_csv('data2.csv', decimal='.', index=False)
```
#### Problem description

data.csv content:

1,41552492693104
1,41552492693104
1,9509035661854
0,763211694509166
0,705991235524791

data2.csv content after running the script:

1,41552492693104
1,41552492693104
1,9509035661854
0,763211694509166
0,705991235524791

i.e. decimal='.',  is not working

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: None.None

pandas: 0.23.1
pytest: 3.5.1
pip: 9.0.3
setuptools: 39.2.0
Cython: 0.28.2
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
I think you confused yourself when reading the data. You used `,` for both `sep` and `decimal`.

```
In [15]: df
Out[15]:
   1   41552492693104
0  1   41552492693104
1  1    9509035661854
2  0  763211694509166
3  0  705991235524791
```

You have two columns, neither of which are floating point.

---

Should pandas throw an error or warning when `sep` and `decimal` are the same?

**Comment by AndreiKeino** [comment]
No, this is incorrect, because with the call df.to_csv('data2.csv', decimal='.', index=False) 
there should be one - column output without the index. Take a look at the index=False parameter in the function call

**Comment by TomAugspurger** [comment]
Notice how you have two columns after `read_csv`, named    `1   41552492693104`.

Or, let's actually make this a minimal example:

```python
In [3]: df = pd.DataFrame({"A": [1, 2], "B": [3.0, 4.0]})

In [4]: print(df.to_csv(decimal='::'))
,A,B
0,1,3::0
1,2,4::0
```

**Comment by TomAugspurger** [comment]
> Should pandas throw an error or warning when sep and decimal are the same?

I suppose this would be OK if the fields are properly quoted, so we can't warn or error.

**Comment by AndreiKeino** [comment]
I find a solution already, as it stated in my previous comment. But thank you for your help anyway.
