### ISSUE TITLE
DOC: Wrong documentation rendering when a space is missing after backticks

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#21562]
It seems like the documentation is not rendering correctly when a space is not present after using backticks.

For example `making ``DataFrame`` render with monospace font` will work as expected.

But `using plural ``DataFrame``s does not have a space between `` and s` does not identify the closing backticks and the whole paragraph may render with monospace.

This image shows a real case in https://pandas.pydata.org/pandas-docs/stable/merging.html#ignoring-indexes-on-the-concatenation-axis:

![pandas_doc_render_backticks](https://user-images.githubusercontent.com/10058240/41671513-3d6231d0-74af-11e8-9596-29d8345b48d7.png)

Couldn't find a way to obtain the expected result (monospace text followed by normal text with a space in between). Not sure if there is a way, but if it's not possible, I think it would be better to use something like the next options (instead of the wrong rendering):
- Avoid having the `s` for plurals
- Leave a space before the `s`
- Use a single quote (e.g. ` ``DataFrame``'s `) which seems to be rendering correctly as ``DataFrame``'s.

**Comment by jorisvandenbossche** [comment]
More options:

- use "DataFrame objects" if you really want the plural and code-formatted "DataFrame"
- don't quote it at all, see https://github.com/pandas-dev/pandas/issues/19750
