### ISSUE TITLE
Support mean() for Timestamps.

### ISSUE THREAD

**Issue by sorenwacker** [pandas-dev/pandas#21583]
[Fitting a linear model to Timestamps currently does not work out of the box.](https://stackoverflow.com/questions/50979873/linear-fit-to-pandas-datetime64-values)
and pandas does not support the ols function any further. When using e.g. seaborn to make a fit it throws an error. 
> TypeError: reduction operation 'mean' not allowed for this dtype

I wonder whether the dtype can be change so that mean is supported? And whether this would make it compatible with other packages, such as scikit-learn, seaborn, etc. Also, the mean of some dates could be useful for other use cases. It does make sense to calculate the mean of some dates doesn't it?

**Comment by soerendip** [comment]
Note, how to fit a model using datetimes/timestamps comes up frequently on stackoverflow in different variations.

**Comment by gfyoung** [comment]
cc @jreback @jorisvandenbossche

**Comment by jreback** [comment]
i believe we have an issue for this - can you see if this is duplicate

**Comment by gfyoung** [comment]
@jreback : It's similar to #17382, but that's for `Timedelta` instead of `Timestamp`.

**Comment by mroeschke** [comment]
Some thoughts:

1) Would this change `describe()`? Currently we provide top, freq, first, last (categorical summary) for `Timestamp` data.

2) What about other ops? (`std`, `median`, `quantile`, etc.) For example `std` of  `Timestamp` data should probably return a `Timedelta` but how about skew and kurtosis (or do they not make sense)?

**Comment by soerendip** [comment]
I agree, median, std, quantiles etc would be very useful too. Also, subtraction of dates would be nice. Why are they called first and last if it could be min and max as well?

**Comment by jbrockmendel** [comment]
Is there anything left to do here?

**Comment by mroeschke** [comment]
Yes this appears to work now so we can close.
