### ISSUE TITLE
Support axis=None in all reductions

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#21597]
https://github.com/pandas-dev/pandas/pull/21486 is implementing support for `axis=None` for compatibility with NumPy 1.15's `all` / `any`.

The basic idea is to have `df.op(axis=None)` be the same as `np.op(df, axis=None)` for reductions like `sum`, `mean`, etc.

Getting there poses a backwards-compatibility challenge. Currently for some reduction functions like `np.sum` we interpret `axis=None` as

```python
In [11]: df = pd.DataFrame({"A": [1, 2]})

In [12]: np.sum(df)
Out[12]:
A    3
dtype: int64
```

The best I option I see is to just warn that the behavior will change in the future, without providing a way to achieve the behavior today. Then users can update things like `np.sum(df)` to `np.sum(df, axis=0)`. In a later version we'll make the actual change to interpret `axis=None` like NumPy.

**Comment by uds5501** [comment]
@TomAugspurger  @gfyoung , I am interested in this issue and would like to help. But could you guys guide me on how to display these `deprecate` messages?

**Comment by gfyoung** [comment]
~~~python
import pandas.util.testing as tm
import warnings

def f():
   warnings.warn("This is a deprecation warning", DeprecationWarning)

def test_f():
   # Might need to also pass in `check_stacklevel=False`.
   with tm.assert_produces_warning(DeprecationWarning):
      f()
~~~

**Comment by uds5501** [comment]
@gfyoung Thanks for the help!
Now regarding this issue, will the warning in the functions like `df.sum` and `df.mean`  etc : "The  behavior 'df.op(axis = None)` is going to change in the future versions " suffice for this issue?

**Comment by gfyoung** [comment]
@uds5501 : Describe (briefly) **how** the behavior would change in the message.

**Comment by uds5501** [comment]
@gfyoung Alright sure, would submit a PR soon :smile:

**Comment by uds5501** [comment]
@gfyoung I had one more query regarding this. If I am not wrong, we call `Dataframe.sum` from `generic.py` at core . So, am I supposed to place this error message in the function given below

https://github.com/pandas-dev/pandas/blob/1a23779f09abc6ebf908d66ee88b973b767e2e3c/pandas/core/generic.py#L9551-L9571

or make separate files for the same like these?

https://github.com/pandas-dev/pandas/blob/83e95e09a08b4f46643a49071edf40bbb3581e13/pandas/core/categorical.py#L1-L8

A little guidance would be appreciated!

**Comment by TomAugspurger** [comment]
FYI @uds5501, this is a rather large change that needs discussion first. If you're interested in working on it, then by all means, but you might want to wait for feedback from other maintainers before diving into it.

**Comment by uds5501** [comment]
@TomAugspurger  Sure sir! I have not yet begun either and conclusive discussions from maintainers who have better context regarding this are always welcome!

**Comment by jreback** [comment]
deprecation PR is #45072

**Comment by jreback** [comment]
@jbrockmendel if you can add this to the do-it-in-2.0 list

**Comment by rhshadrach** [comment]
Since the deprecation portion of this issue has been handled, I'm removing the deprecate label as it is now just an enhancement. I believe the enhancement portion still needs to be implemented.

**Comment by august-tengland** [comment]
We're looking at this (as part of a university project), might not lead to anything productive however.

**Comment by arv-77** [comment]
Hi @mroeschke , I would love to contribute to this issue. Can I work on implementing the remaining ops?

**Comment by jbrockmendel** [comment]
We suggest contributors start with an issue with the "good first issue" tag

**Comment by arv-77** [comment]
Ok, I'll start with some good first issue then. Thanks!

**Comment by jbrockmendel** [comment]
It looks like the remaining reductions didn't have the axis=None behavior deprecated, so we'll need to do a deprecation cycle and do the change in 3.0
