### ISSUE TITLE
Duplicate NaNs when using set() to a Pandas series

### ISSUE THREAD

**Issue by zh2196** [pandas-dev/pandas#21596]
#### Code Sample

```python
import numpy as np
import pandas as pd
S = pd.Series([np.nan,1.5,np.nan,2,np.nan,np.nan,np.nan,1,1,2,2,2,3])
print S; print; print set(S)
```
#### Problem description

The NaNs show up multiple times in set(S), which is not a problem if

```python
S = [np.nan,1.5,np.nan,2,np.nan,np.nan,np.nan,1,1,2,2,2,3]
```

is used instead. The multiple NaNs in set(S) also become very slow to run if

```python
S = pd.Series([np.nan,1.5,np.nan,2,np.nan,np.nan,np.nan,1,1,2,2,2,3] + [np.nan] * 100000)
```

is used. Without pd.Series it's a flash of a second.

**Comment by TomAugspurger** [comment]
Comparing pandas' behavior vs. a List isn't really apples to apples. The better comparison is to NumPy

```python
In [40]: set(np.array([np.nan, np.nan]))
Out[40]: {nan, nan}
```

In general, you can't rely on `np.nan` being a singleton, which is what `set` is relying on.

If you want unique values, you can use `pd.factorize`, which knows how to handle NaNs`.
