### ISSUE TITLE
In-place DataFrame.reindex

### ISSUE THREAD

**Issue by esafak** [pandas-dev/pandas#21598]
#### Code Sample, a copy-pastable example if possible

```python
df=DataFrame([[1,2],[3,4]], index=list('cd'))
df.reindex(list('dc'), copy=False)

>   0  1
 d  3  4
 c  1  2

df.index

> Index(['c', 'd'], dtype='object')
```
#### Problem description

The index is not re-ordered.

#### Expected Output

> Index(['d', 'c'], dtype='object')

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

TALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Darwin
OS-release: 17.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.1
pytest: 3.5.1
pip: 10.0.1
setuptools: 39.2.0
Cython: 0.28.3
numpy: 1.14.5
scipy: 1.1.0
pyarrow: 0.7.1
xarray: None
IPython: 6.4.0
sphinx: None
patsy: 0.5.0
dateutil: 2.6.1
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by TomAugspurger** [comment]
Two things

1. `copy=False` does not mean inplace2
2. as http://pandas-docs.github.io/pandas-docs-travis/generated/pandas.Series.reindex.html#pandas-series-reindex  `Return a new object, even if the passed indexes are the same`, so this is about copying when it isn't necessary, rather than not copying when it may or may not be necessary.

**Comment by uds5501** [comment]
@esafak 
Do look at @TomAugspurger , they provide a good overview at the situation
Also, try something like this to achieve your goal?

```python
>>> df = df.reindex(list('dc'))
>>> df
   0  1
d  3  4
c  1  2
>>> df.index
Index(['d', 'c'], dtype='object')

```

**Comment by esafak** [comment]
That is what I do @uds5501 I suppose I misinterpreted the parameter. Isn't this the kind of thing we should be able to do in-place? I would like to see it supported, if possible.

**Comment by TomAugspurger** [comment]
> Isn't this the kind of thing we should be able to do in-place?

In general, no. Even something like

```python
In [3]: arr = np.array([[0, 1], [1, 2]])

In [4]: arr[[1, 0]]
Out[4]:
array([[1, 2],
       [0, 1]])
```

is a copy and not a view.

**Comment by Mauz91** [comment]
I need to reindex several dataframes (a,b,c). I like to do that in a for-loop. Therefore, I am also looking for an inplace option for pandas.DataFrame.reindex. I have tried the following, but it is not working ...

dfs = [a,b,c]
for d in dfs:
    d = d.reindex(sorted(d.columns), axis=1)

Thanks for your help!
Andy
