### ISSUE TITLE
`allow_gaps` option in rank

### ISSUE THREAD

**Issue by changhiskhan** [pandas-dev/pandas#2160]
when there are ties, whether the next rank will be the nearest integer to the current rank or tie-count ranks away.

**Comment by ldconejo** [comment]
No additional updates on this one since November, 2013. The last comment seems to provide an alternate solution. Is this enhancement still required?

**Comment by jreback** [comment]
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.rank.html?highlight=rank#pandas.Series.rank

already supports these
