### ISSUE TITLE
RLS 0.23.2

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#21617]
Sometime before the sprint, ideally this week.

cc @pandas-dev/pandas-core

**Comment by TomAugspurger** [comment]
Python 3.7 was released yesterday.

Multibuild is added 3.7 support in https://github.com/matthew-brett/multibuild/pull/180
conda-forge issue for 3.7 at https://github.com/conda-forge/python-feedstock/issues/177

I'd propose we wait until those are ready, assuming it'll be sometime this week or early next week.

**Comment by cbrnr** [comment]
Multibuild is ready...

**Comment by jorisvandenbossche** [comment]
I am travelling tomorrow, we will probably get to it on Thursday

**Comment by TomAugspurger** [comment]
Work is still happening on conda-forge: https://github.com/conda-forge/python-feedstock/pull/183

We aren't likely to release before that's ready.

**Comment by jorisvandenbossche** [comment]
Do we necessarily have to wait on it? (if we have a release otherwise ready?) We can rebuild once 3.7 is there to add those packages? 
All people that reported / ran into the regressions we have fixed are not using python 3.7, so they can already benefit from a release.

**Comment by TomAugspurger** [comment]
> We can rebuild once 3.7 is there to add those packages?

Not necessarily, but if it's a matter of releasing Thursday vs. Friday / Saturday, then I think waiting makes sense.

**Comment by cbrnr** [comment]
And people not using conda-forge but Python 3.7 would also greatly benefit!

**Comment by TomAugspurger** [comment]
@cgohlke I notice that you have a `pandas‑0.23.2‑pp360‑pp360‑win32.whl` wheel. Is the `pp` python-tag for PyPy? Would you recommend uploading that wheel to PyPI?

**Comment by cgohlke** [comment]
> Is the pp python-tag for PyPy

Yes, pp360 is for pypy3-v6 from https://bitbucket.org/pypy/pypy/downloads/

> Would you recommend uploading that wheel to PyPI?

Probably not. I can `import pandas` and create DataFrames etc  but am unable to run the tests due to an `SystemError: unexpected internal exception` in pypy3.

**Comment by jorisvandenbossche** [comment]
Yes, I think uploading such wheels is giving like a sign that we officially support it, which is not yet the case I think.

**Comment by TomAugspurger** [comment]
Thanks!

All the wheels should be up now.

**Comment by TomAugspurger** [comment]
We'll need to rebuild on conda-forge once the 3.7 dependencies are all built.
