### ISSUE TITLE
TST: flaky test on 3.7

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#21636]
This is occasionally failing the CI.

running this multiple times will cause it to fail:
``pytest pandas//tests/groupby/test_categorical.py  --pdb -v -k apply -s``

not sure where the error is yet. xfailing for now.

**Comment by TomAugspurger** [comment]
👍 I'll look into it today.

**Comment by TomAugspurger** [comment]
Some brief notes:

It's seemingly related to some process-level state. With `pytest-repeat`, I run `pytest pandas/tests/groupby/test_categorical.py::test_apply --pdb -v --count=10`. I either get all failures, or all passes; never a mix.

**Comment by jreback** [comment]
yeah something is weird. not really sure.

**Comment by jbrockmendel** [comment]
I can't reproduce this failure on either OSX or Linux.  Re-opening.

**Comment by mroeschke** [comment]
Dont think the CI has been failing with this lately. We can reopen if it continues to be a problem
