### ISSUE TITLE
Import pandas error in Abaqus python environment 

### ISSUE THREAD

**Issue by gautham949** [pandas-dev/pandas#21632]
I was trying to import pandas library in Abaqus(Finite element software) python environment but it shows the following error. 

`import pandas`
`File "C:\ProgramData\Anaconda3\Lib\site-packages\pandas\__init__.py", line 23, in <module>
    from pandas.compat.numpy import *`
`File "C:\ProgramData\Anaconda3\Lib\site-packages\pandas\compat\numpy\__init__.py", line 24, in <module>
    'this pandas version'.format(_np_version))`
`ImportError: this version of pandas is incompatible with numpy < 1.9.0
your numpy version is 1.6.2.
Please upgrade numpy to >= 1.9.0 to use this pandas version`

I've tried updating my Anaconda and all the other packages included in it. The error still pops up. How do I go about it?

**Comment by gfyoung** [comment]
@gautham949 : Can you launch Python from `Command Prompt` and run the following code:

~~~python
import numpy as np
print(np.__version__)
~~~

What do you get?

**Comment by gautham949** [comment]
It shows the following error.

`AttributeError: 'module' object has no attribute '_version_'`

**Comment by rockg** [comment]
Are you using one underscore or two when you do that?

**Comment by kevbutler** [comment]
I'm also having a problem with numpy and pandas, and get the same error:
`AttributeError: module 'numpy' has no attribute '__version__'`

**Comment by Remnan13** [comment]
Did the dunder fix work, @gautham949 ?

**Comment by jbrockmendel** [comment]
closing as stale.  @gautham949 if you want to follow up on this we can re-open.
