### ISSUE TITLE
DEPS/DEPR: Allow import of feather through pyarrow

### ISSUE THREAD

**Issue by h-vetinari** [pandas-dev/pandas#21639]
Currently, `DataFrame.to_feather()` tries to `import feather`, which only works if `feather-format` is installed. The same capabilities could also be imported as follows: `import pyarrow.feather as feather`.

The issue is that `pyarrow` is more easily available (e.g. `conda install feather-format` doesn't work without specifying a specific channel; but `pyarrow` works), and is under more active development.

I asked if there is a preference between the two imports in wesm/feather#341, and Wes answered [my bold]:
> You can use either method; there is no explicit recommendation right now. **`import feather` is provided for backwards compatibility**

I think the import should at least try `import pyarrow.feather as feather` as well, if `import feather` fails.

**Comment by jreback** [comment]
would take a PR to use pyarrow.feather
i suppose should continue to accept feather-format but deprecate it as a dep
