### ISSUE TITLE
ENH: Enable multiple spaces in printing DF in IPython (through HTML)

### ISSUE THREAD

**Issue by h-vetinari** [pandas-dev/pandas#21642]
When displaying a DataFrame in IPython, multiple spaces (as well as leading/trailing spaces) get removed.

However, sometimes it is necessary though to show the data exactly _as is_. Cleaning up the strings like that is not a terrible default, but the user should have the option to display their data without mutation.

I posed this issue in ipython/ipython#11022, but there, @takluyver said:
> If there's a problem with how pandas dataframes display, you probably need to open an issue on pandas - the package generates the HTML, IPython just passes it on to the browser.

With this issue, I'm trying to follow up on that. As far as I can see, it's not just a pandas issue (which is why I tagged @takluyver). pandas strips the outer spaces, and IPython strips the inner ones.
```
df = pd.DataFrame({'col1': [' a ', 'b    b'], 'col2': [' c d ', 'e f   f   f   f']})
df
```
![1](https://user-images.githubusercontent.com/33685575/41929520-994ba2f6-7978-11e8-86ba-37bfd573ea97.png)

In string form, all spaces are there:
```
print(df)
#      col1             col2
# 0  a    a             c d 
# 1      b   e f   f   f   f
```
In HTML form, the inner spaces are still there; outer spaces have been stripped:
```
print(df.to_html())
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>col1</th>
      <th>col2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>a    a</td>
      <td>c d</td>
    </tr>
    <tr>
      <th>1</th>
      <td>b</td>
      <td>e f   f   f   f</td>
    </tr>
  </tbody>
</table>
```

Finally, quotes do not "escape" the string in some way - ipython continues stripping inner spaces:
```
df.apply(lambda x: x.apply(lambda y: f"'{y}'"), axis=1)
```
![2](https://user-images.githubusercontent.com/33685575/41929532-a0d46d3c-7978-11e8-99ef-5a7a1b892665.png)

As a possible solution, @rsclafani came up with the following in the ipython issue:
```
from IPython.core.display import display, HTML
display(HTML("<style>.rendered_html td { white-space: pre; }</style>"))
```
Maybe this could be wrapped in a kwarg `raw=True|False` in either pandas/ipython?

**Comment by h-vetinari** [comment]
@TomAugspurger Thanks for the response and info (I do admit that I was a bit lost as to who's doing what).

> I don't think we're interested in messing with the CSS. That's best left to others (with the defaults set by the notebook). 

For a casual user (including me for a long time), I believe it's a natural assumption that pandas is responsible for the rendering in IPython - even if that's an overly simplistic viewpoint. But as such, the first option a user will search for is adapting something _in pandas_. I can see why you don't want to mess with the defaults, but then I think there should be at least a `pd.set_option()` to switch off the whitespace-merging.

**Comment by takluyver** [comment]
Displaying HTML would effectively strip the spaces anyway. Try making a .html file with this in:

```html
<table style="border: 1px solid black;">
<tr><td>    a   bc  </td></tr>
</table>
```

You'll only see a box containing `a bc` - all the other spaces are collapsed.

To avoid this, pandas would have to replace spaces with non-breaking spaces `&nbsp;`. They aren't collapsed. That could cause problems for displaying longer strings, though, because it breaks wrapping.

**Comment by attack68** [comment]
Styler does not trim any whitespace.

```
df = pd.DataFrame([[' a b ', '  c   d e ']])
print(df.style.render())
```

```
      <td id="T_4b2d0_row0_col0" class="data row0 col0" > a b </td>
      <td id="T_4b2d0_row0_col1" class="data row0 col1" >  c   d e </td>
```

as @takluyver points out HTML is doing the stripping here.

I think if the user wants to influence the HTML represenation they need to add the correct HTML. i.e 

`df = pd.DataFrame([['&nbsp;&nbsp;a b&nbsp;', '  c   d e ']])`

Having pandas insert HTML non-breaking spaces feels forced. Might be scope if someone introduces a formatter option though..

**Comment by attack68** [comment]
we added a recent HTML escape option to the formatter, but this does not include whitespace, since it is ambiguous what a whitespace escaper would do - conclusion: I think this has to be explicitly added by the user.

additionally for the upcoming LaTeX styler I do not know how LaTeX handles whitespace but there is also a different escape char: '\;' instead of '&nbsp;'

**Comment by attack68** [comment]
For what its worth this is the solution:

```
df = pd.DataFrame([[' a b ', '  c   d e ']])
def whitespace(v):
    return re.sub("\s{2,}", lambda match: match.group().replace(" ", "&nbsp;"), v)
df.style.format(whitespace)
```

for LaTeX replace `&nbsp;` with `\\;`

**Comment by attack68** [comment]
closing as non-actionable
