### ISSUE TITLE
API: Unify compression-kwarg for IO-methods

### ISSUE THREAD

**Issue by h-vetinari** [pandas-dev/pandas#21640]
Currently, there's:
* `'compression'` in `to_csv`, `to_json`, `to_parquet`, `to_pickle`
* `'complib'` in `to_hdf` (also `'complevel'`)
* `'compress'` in `to_msgpack`

Those are all the writer-methods from https://pandas.pydata.org/pandas-docs/version/0.23.1/io.html which have compression.

Seems to me that the kwargs of `to_hdf` and `to_msgpack` should be unified with the other methods.

**Comment by gfyoung** [comment]
@jreback : This sounds very similar to #15862.

**Comment by h-vetinari** [comment]
@gfyoung Didn't know that PR, thanks. It has a much larger scope than this one - I just stumbled over this inconsistency when benchmarking several IO methods.

**Comment by mroeschke** [comment]
I think the the compression points are covered in https://github.com/pandas-dev/pandas/issues/15008 which seems to be our overarching IO consolidation issue. Going to close in favor of that issue
