### ISSUE TITLE
TST/CLN: remove MultiIndex compat

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#21654]
we have these 2 pickles

```
(pandas) bash-3.2$ ls pandas/tests/indexes/data/
mindex_073.pickle       multiindex_v1.pickle
```

should blow these away and the older MultiIndex formats. These are really really old.

note will conflict slightly with #21514 (IOW path will be different after)

**Comment by connormartin7** [comment]
Hey I'd like to take this one on!
