### ISSUE TITLE
Pandas dataframe column headers shows different behaviour on linux and windows platform 

### ISSUE THREAD

**Issue by chetanya1710** [pandas-dev/pandas#21679]
```python
import pandas as pd
d = {'poppys_play_house_bedroom': ['hello', 'bye'], 'assorted_colour_bird_ornament': ['good morning', 'good night']}
df = pd.DataFrame(data=d)
df
```
####
pandas dataframe shows a different behaviour when the same code is compiled on linux and windows.
what I observed is that when i make a dataFrame with column headers, on windows (consider the above code) it makes the columns in the same order as we entered it. Here in this case it would be like

 **poppys_play_house_bedroom | assorted_colour_bird_ornament.**
 
But when i run this same code on a linux machine it sorts my column headers automatically without my permission or any other extra command. the above code will give output with column headers as

**assorted_colour_bird_ornament | poppys_play_house_bedroom**
 
On large sets of data (100000 rows) if some computations are applied on even top rows then the whole results can vary on both the machines and that too with a large extent.
####

**Comment by chris-b1** [comment]
please show pandas and python versions for each

**Comment by chetanya1710** [comment]
Linux :
Python-3.6.5
Pandas-0.22.0

Windows :
Python-3.6.5
Pandas-0.23.0

**Comment by chris-b1** [comment]
See release not here - in 0.23+ we respect dict insertion order on python 3.6+, previously sorted
https://pandas.pydata.org/pandas-docs/version/0.23.1/whatsnew.html#instantiation-from-dicts-preserves-dict-insertion-order-for-python-3-6
