### ISSUE TITLE
`DataFrame.add` and `DataFrame.radd` are the same function

### ISSUE THREAD

**Issue by dragonator4** [pandas-dev/pandas#21672]
In 0.22 (and 0.23), there are two copies of the same function `DataFrame.add` and `DataFrame.radd`. The link in the documentation also points to the same function in the source code. Here are the documentation links for the two functions:

[`DataFrame.add`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.add.html)

[`DataFrame.radd`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.radd.html)

**Comment by gfyoung** [comment]
@dragonator4 : That's actually deliberate.  These functions are generated via that factory function that is highlighted in the documentation (this is true for many other `DataFrame` operations as well).  Admittedly, it's a little convoluted, but that's how things are for the time being.

I hope that clears things up!
