### ISSUE TITLE
[CLN] avoid internal usage of private functions

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#21698]
It would be easier to reason about the code if we did a better job of respecting cross-module private-ness.  e.g. `com._default_index`, `com._maybe_box_datetimelike`, `com._values_from_object` get used a lot, should either not be used or (more likely) should be de-privatized.

**Comment by bashtage** [comment]
Maybe these should be in private modules, e.g.,  _common rather than private functions.

**Comment by jreback** [comment]
yes these could be moved underneath

_libs (though which is all cython atm)
