### ISSUE TITLE
pd.read_csv returns incorrect number of rows

### ISSUE THREAD

**Issue by tastyminerals** [pandas-dev/pandas#21695]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
df = pd.read_csv("test.csv", sep="\t", index_col=None)
print(df.shape)  # (6851728, 8)

```
#### Problem description

"test.csv" file contains **10,321,311** rows.
Loading it via `read_csv` gives **6,851,728** rows.

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-6-amd64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: None
pip: 10.0.1
setuptools: 39.0.1
Cython: None
numpy: 1.14.2
scipy: 1.0.1
pyarrow: None
xarray: None
IPython: 6.3.1
sphinx: None
patsy: None
dateutil: 2.7.2
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.9999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

**Comment by tastyminerals** [comment]
Solved by adding `quoting=csv.QUOTE_NONE, escapechar="\\", encoding="utf-8"`.

**Comment by allenyllee** [comment]
> Solved by adding `quoting=csv.QUOTE_NONE, escapechar="\\", encoding="utf-8"`.

The working part is `quoting=csv.QUOTE_NONE`, according to the document:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html#pandas-read-csv
> quoting{0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL, 2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
Control field quoting behavior per csv.QUOTE_* constants. Default is csv.QUOTE_MINIMAL (i.e., 0) which implies that only fields containing special characters are quoted (e.g., characters defined in quotechar, delimiter, or lineterminator.

you need to import csv fisrt:
```python
import csv
import pandas as pd
df = pd.read_csv(file_path, quoting=csv.QUOTE_NONE)
```
or just use number
```python
import pandas as pd
df = pd.read_csv(file_path, quoting=3)
```
