### ISSUE TITLE
implicite typecast under python2 by access columns index

### ISSUE THREAD

**Issue by pf4sh** [pandas-dev/pandas#21718]
#### by looking on the columns you can't see wath you get, pandas 0.23.1

example with python2 string
```python
In [1]: df = pd.DataFrame()

In [2]: df['a'] = [1, 3]

In [3]: df.columns
Out[3]: Index([u'a'], dtype='object')

In [4]: print(type(df.columns[0]))
<type 'str'>
```
example with unicode
```python
In [1]: df = pd.DataFrame()

In [2]: df[u'a'] = [1, 3]

In [3]: df.columns
Out[3]: Index([u'a'], dtype='object')

In [4]: print(type(df.columns[0]))
<type 'unicode'>
```
#### Problem description

If you get a DataFrame, then you can't be shure what you get from the columns index, it looks like unicode, but it depends on the creation type.

**Comment by gfyoung** [comment]
cc @jreback

**Comment by TomAugspurger** [comment]
May want to look at https://github.com/pandas-dev/pandas/blob/master/pandas/io/formats/printing.py#L153

**Comment by jbrockmendel** [comment]
Closing since py2 is no longer supported.  Feel free to ping if the issue recurs in py3.
