### ISSUE TITLE
CategoricalDtype should be exposed in the top-level `pandas` namespace

### ISSUE THREAD

**Issue by edschofield** [pandas-dev/pandas#21713]
Proposal: expose `CategoricalDtype` in the top-level `pandas` namespace.

As of pandas 0.23.0, `.astype(..., categories=...)` raises a `FutureWarning` but `CategoricalDtype`, the recommended alternative, is still buried in `pandas.api.types`. This makes its use considerably more verbose than the old interface:

```
# previous use (prior to 0.23.0)
df['col'] = df['col'].astype('category', categories=my_categories)

# current use (0.23.0)
from pandas.api.types import CategoricalDtype
cat = CategoricalDtype(my_categories)
df['col'] = df['col'].astype(cat)

# proposed (0.24+)
df['col'] = df['col'].astype(pd.CategoricalDtype(my_categories))
```

**Comment by gfyoung** [comment]
That seems like a reasonable proposition:

cc @jreback

**Comment by TomAugspurger** [comment]
+1 from me, but we'll want to consider this in the wider context of all the extension dtypes and arrays that will soon be added.

We'll presumably have

* Categorical / CategoricalDtype
* IntervalArray / IntervalDtype
* DatetimeArray / DatetimeDtype(?)
* PeriodArray / PeriodDtype

**Comment by jbrockmendel** [comment]
CaategoricalDtype, IntervalDtype, DatetimeTZDtype, and PeriodDtype are all now exposed.  closeable?
