### ISSUE TITLE
Python plot giving errors when reading data through pandas

### ISSUE THREAD

**Issue by SanchitKratos** [pandas-dev/pandas#21736]
Issue Report Checklist
[v ] Searched the issues page for similar reports
[ v] Read the relevant sections of the Spyder Troubleshooting Guide and followed its advice
[v ] Reproduced the issue after updating with conda update spyder (or pip, if not using Anaconda)
[ v] Could not reproduce inside jupyter qtconsole (if console-related)
[ ]v Tried basic troubleshooting (if a bug/error)
[v ] Restarted Spyder
[ v] Reset preferences with spyder --reset
[ v] Reinstalled the latest version of Anaconda
[ v] Tried the other applicable steps from the Troubleshooting Guide
[ v] Completed the Problem Description, Steps to Reproduce and Version sections below
Problem Description
I am trying to get plots for my homework. Iuse the following code:

import matplotlib.pyplot as mp
import pandas as pd
import seaborn as sns;
import pylab
from matplotlib import rc
mp.rc('text', usetex = True)
mp.rc('font', **{'family' : "serif"})
params = {'text.latex.preamble' : [r'\usepackage{siunitx}', r'\usepackage{sfmath}']}
mp.rcParams.update(params)
mp.style.use('bmh')
D=pd.read_csv('EXTRA.csv')
A=D.values
colors = ["red","purple","red","chocolate","black","red","#ff5733","chocolate","orange","#800000","#ff5733"]
title=["Plutonium","No Material","Bismuth","3 percent Enriched UO2 Spectrum","5 percent Enriched UO2 Spectrum","Bismuth Spectrum","Pu Spectrum","Spectrum With no Material","Natural UO2 Spectrum","3 percent Enriched UO2 Spectrum","5 percent Enriched UO2 Spectrum","Bismuth Spectrum","Pu Spectrum","Spectrum With no Material","Natural UO2 Spectrum","3 percent Enriched UO2 Spectrum","5 percent Enriched UO2 Spectrum","Bismuth Spectrum" ]
title1=["Neutron Spectrum Comparison at location DP2","v","Neutron Spectrum Comparison at DP3","Gamma Spectrum Comparison at location DP1","Gamma Spectrum Comparison at location DP1","Gamma Spectrum Comparison at location DP1","v","Neutron Spectrum Comparison at location DP3"]
for i in range(1,3):#len(A[0,:])):
mp.plot(A[:,0],A[:,i],linewidth=0.8,color=colors[i],label=title[i-1])
mp.xlabel(r'\textit{Energy (MeV)}')
mp.ylabel(r'\textit{Percentage of particles}')
mp.title(title1[i-1])
mp.grid(True,which="both",ls="-")
mp.legend(loc='best')
mp.savefig("Sanchit3zx.png",dpi=300,format='png')

mp.show()

What steps reproduce the problem?
I get the following error:

What is the expected output? What do you see instead?
File "/home/anaconda3/lib/python3.6/site-packages/pandas/core/dtypes/common.py", line 853, in is_integer_dtype
tipo = _get_dtype_type(arr_or_dtype)

NameError: name '_get_dtype_type' is not defined

Paste Traceback/Error Below (if applicable)
File "/home/anaconda3/lib/python3.6/site-packages/pandas/core/dtypes/common.py", line 853, in is_integer_dtype
tipo = _get_dtype_type(arr_or_dtype)

NameError: name '_get_dtype_type' is not defined

**Comment by TomAugspurger** [comment]
Pandas version? 

Can you paste the full traceback?

**Comment by TomAugspurger** [comment]
Closing, let s know if yo can provide the requested info.
