### ISSUE TITLE
DOCS: Update import statements in docstrings

### ISSUE THREAD

**Issue by alphaCTzo7G** [pandas-dev/pandas#21749]
xref https://github.com/pandas-dev/pandas/pull/21731#pullrequestreview-134460126

- [ ] ./pandas/plotting/_converter.py|134 col 17| ">>> from pandas.plotting import register_matplotlib_converters"
- [ ] pandas/plotting/_misc.py|501 col 5| >>> from pandas import read_csv
- [ ] pandas/plotting/_misc.py|502 col 5| >>> from pandas.tools.plotting import parallel_coordinates
- [x] ./pandas/util/testing.py|602 col 5| >>> from pandas.util.testing import capture_stdout https://github.com/pandas-dev/pandas/pull/42979
- [x] ./pandas/util/testing.py|650 col 5| >>> from pandas.util.testing import capture_stderr https://github.com/pandas-dev/pandas/pull/42979
- [x] ./pandas/util/testing.py|2213 col 7| >>> from pandas.util.testing import network https://github.com/pandas-dev/pandas/pull/42979
- [x] ./pandas/util/testing.py|2214 col 7| >>> from pandas.io.common import urlopen https://github.com/pandas-dev/pandas/pull/42979
- [x] ./pandas/tseries/holiday.py|145 col 9| >>> from pandas.tseries.holiday import Holiday, nearest_workday https://github.com/pandas-dev/pandas/pull/45485
- [ ] ./pandas/tseries/holiday.py|146 col 9| >>> from pandas import DateOffset
- [ ] ./pandas/core/sparse/series.py|739 col 9| >>> from numpy import nan
- [ ] pandas/core/frame.py|2844 col 9| >>> from numpy.random import randn
- [ ] pandas/core/frame.py|2845 col 9| >>> from pandas import DataFrame
- [ ] ./pandas/core/algorithms.py|1519 col 5| >>> from pandas.api.extensions import take
- [x] ./pandas/core/dtypes/concat.py|285 col 5| >>> from pandas.api.types import union_categoricals https://github.com/pandas-dev/pandas/pull/45346
- [ ] ./pandas/io/pytables.py|457 col 5| >>> from pandas import DataFrame
- [ ] ./pandas/io/pytables.py|458 col 5| >>> from numpy.random import randn
- [ ] ./pandas/io/json/normalize.py|138 col 5| >>> from pandas.io.json import json_normalize
- [x] pandas/io/stata.py|2713 col 5| >>> from pandas.io.stata import StataWriter117 https://github.com/pandas-dev/pandas/pull/45346

**Comment by TomAugspurger** [comment]
What's this for?

**Comment by alphaCTzo7G** [comment]
This is related to this.. https://github.com/pandas-dev/pandas/pull/21731#discussion_r200216595

**Comment by gfyoung** [comment]
@TomAugspurger : I've updated the issue to clarify the purpose.

**Comment by jbrockmendel** [comment]
Do we have an idea which of these are still relevant?

**Comment by salomondush** [comment]
Take

**Comment by salomondush** [comment]
Hello, I was wondering if it's okay to take on this issue because I noticed that some statements still use the old form

**Comment by MarcoGorelli** [comment]
reopening as I don't think the linked PR closes all the items

**Comment by Varun270** [comment]
@salomondush Are you still working on this, as I wanted to work on this issue?

**Comment by salomondush** [comment]
I worked on some parts of it, but you can take the remaining check points

**Comment by Varun270** [comment]
take

**Comment by Varun270** [comment]
@salomondush Thank you so much this is my first time contributing to a big project. I might need your guidance.

**Comment by Varun270** [comment]
take

**Comment by Varun270** [comment]
@salomondush  Hey, Can you tell me how did you find the exact location of docstrings that require fix? I followed the file path but didn't found those import statements that require fixing.

**Comment by salomondush** [comment]
Most of them have been fixed, but if you use VS code, you should be able to search specific lines of code throughout all files.

**Comment by ko-ya346** [comment]
I will modify the documents in 
pandas/io/stata.py and pandas/core/dtypes/concat.py.

**Comment by mariana-LJ** [comment]
I'm addressing the following import update in the PR above:

./pandas/core/algorithms.py|1519 col 5| >>> from pandas.api.extensions import take

That's the only outdated import statement I could find. Does this mean all others have been addressed? Thanks!

**Comment by mroeschke** [comment]
Appears like https://github.com/pandas-dev/pandas/pull/45841 closed the last of the above checklist.

Closing, but if there are other leftover, individual issues can be opened instead
