### ISSUE TITLE
DOC: update parquet documentation categorical support

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#21747]
http://pandas-docs.github.io/pandas-docs-travis/io.html#parquet is a bit outdated, we should investigate a bit the current state of what support there is in pyarrow and fastparquet

**Comment by datapythonista** [comment]
I think this is superseded by #27955, should we close this?

**Comment by alimcmaster1** [comment]
Looks like this was addressed in https://github.com/pandas-dev/pandas/pull/28018 feel free to reopen if you feel otherwise Joris

**Comment by jorisvandenbossche** [comment]
That is indeed solved! Thanks for cleaning up
