### ISSUE TITLE
dataframe drop_duplicates method

### ISSUE THREAD

**Issue by Duanexiao** [pandas-dev/pandas#21743]
#### Code Sample, a copy-pastable example if possible
if os.path.exists(historyFile):
    df = pd.read_csv(historyFile)
    newDf = getDailyMpOrder(mysqlCon,checkDate)
    df = pd.concat([df,newDf])
    df = df.drop_duplicates()
else:
    checkDate = "20180101"
    df = getDailyMpOrder(mysqlCon,checkDate)

#### Problem description
the drop_duplicates() method does not drop the duplicate rows.when I save the last df into csv file,and read the csv file by read_csv method, then operate drop_duplicates() method,it works.

looking for your replying ,many thanks.

**Comment by WillAyd** [comment]
There’s nothing reproducible with your example. Please be sure to check out the pandas guide on crafting bug reports along with the below reference

http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

If you can craft a reproducible example please reopen
