### ISSUE TITLE
pd.wide_to_long() only recognises all numerical snubname suffixes

### ISSUE THREAD

**Issue by cbjrobertson** [pandas-dev/pandas#21751]
#### Code Sample, a copy-pastable example if possible

```
import pandas as pd
import numpy as np
np.random.seed(123)
df = pd.DataFrame({"test-a" : {0 : "a", 1 : "b", 2 : "c"},
                   "test-b" : {0 : "d", 1 : "e", 2 : "f"},
                   "test-c" : {0 : 2.5, 1 : 1.2, 2 : .7},
                   "test-d" : {0 : 3.2, 1 : 1.3, 2 : .1},
                   "X"     : dict(zip(range(3), np.random.randn(3)))
                  })
df["id"] = df.index
test1 = pd.wide_to_long(df, stubnames=['test-'], i="id", j="year")

df = pd.DataFrame({"test-1" : {0 : "a", 1 : "b", 2 : "c"},
                   "test-2" : {0 : "d", 1 : "e", 2 : "f"},
                   "test-3" : {0 : 2.5, 1 : 1.2, 2 : .7},
                   "test-4" : {0 : 3.2, 1 : 1.3, 2 : .1},
                   "X"     : dict(zip(range(3), np.random.randn(3)))
                  })
df["id"] = df.index
test2 = pd.wide_to_long(df, stubnames=['test-'], i="id", j="year")






>>>test1
Empty DataFrame
Columns: [X, test-c, test-a, test-d, test-b, test-]
Index: []

>>>test2
              X  test-
id year                
0  1    -1.085631     a
1  1     0.997345     b
2  1     0.282978     c
0  2    -1.085631     d
1  2     0.997345     e
2  2     0.282978     f
0  3    -1.085631   2.5
1  3     0.997345   1.2
2  3     0.282978   0.7
0  4    -1.085631   3.2
1  4     0.997345   1.3
2  4     0.282978   0.1
```
#### Problem description
This seems to be very obviously undesirable behaviour as it seems very likely that users will some times include non-numerical only characters in their suffixes. It should at least be in the docs.

#### Expected Output
```
>>>test1
              X  test-
id year                
0  a    -1.085631     a
1  a     0.997345     b
2  a     0.282978     c
0  b    -1.085631     d
1  b     0.997345     e
2  b     0.282978     f
0  c    -1.085631   2.5
1  c     0.997345   1.2
2  c     0.282978   0.7
0  d    -1.085631   3.2
1  d     0.997345   1.3
2  d     0.282978   0.1
```

#### Output of ``pd.show_versions()``
<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Darwin
OS-release: 17.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.1
pytest: 3.2.1
pip: 10.0.1
setuptools: 38.5.1
Cython: 0.28.2
numpy: 1.14.1
scipy: 0.19.1
pyarrow: 0.7.1
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: 0.4.0
matplotlib: 2.1.0
openpyxl: 2.4.8
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 1.0.2
lxml: 4.1.0
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by Liam3851** [comment]
@cbjrobertson This is the suffix parameter, documented at https://pandas.pydata.org/pandas-docs/stable/generated/pandas.wide_to_long.html. 

Using `suffix='\\w+'` gives you expected output:

```
test1 = pd.wide_to_long(df, stubnames=['test-'], i="id", j="year", suffix="\\w+")
```

**Comment by gfyoung** [comment]
@Liam3851 : Thanks for explaining this!  Closing as a result.

@cbjrobertson : If the explanation isn't satisfactory enough, feel free to continue commenting, and we can re-open this issue.
