### ISSUE TITLE
TST: unreliable parser test

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#21763]
this test is somehow non-deterministic and occasionally fails with a ``ResourceWarning``: https://circleci.com/gh/pandas-dev/pandas/15501#tests/containers/3

not really sure if this is a red-herring of something else

```
self = <pandas.tests.io.parser.test_parsers.TestPythonParser object at 0x7f90482356a0>

    def test_empty_with_dup_column_pass_dtype_by_indexes(self):
        # see gh-9424
        expected = pd.concat([Series([], name='one', dtype='u1'),
                              Series([], name='one.1', dtype='f')], axis=1)
    
        data = 'one,one'
        result = self.read_csv(StringIO(data), dtype={0: 'u1', 1: 'f'})
        tm.assert_frame_equal(result, expected, check_index_type=False)
    
        with tm.assert_produces_warning(UserWarning, check_stacklevel=False):
            data = ''
            result = self.read_csv(StringIO(data), names=['one', 'one'],
                                   dtype={0: 'u1', 1: 'f'})
>           tm.assert_frame_equal(result, expected, check_index_type=False)
```

**Comment by jreback** [comment]
cc @gfyoung

**Comment by gfyoung** [comment]
@jreback : My first inclination is that it's a red herring of something else outside of `test_parsers.py`.  When I run `pytest` on just `test_parsers.py`, I don't get that failure.  However, when I run the entire test suite, I do get the failure (occasionally).

**Comment by jreback** [comment]
yeah not really sure what is actually triggering this.

**Comment by gfyoung** [comment]
Going to monitor this test for the time being and will see if it rears its head again later on down the road.  If it doesn't, I feel okay with closing this since we *should* be able to figure out now where it's originating.
