### ISSUE TITLE
.rolling().std() only returns NaN in Python3.7

### ISSUE THREAD

**Issue by tweakimp** [pandas-dev/pandas#21786]
```python
import pandas as pd
d = {"col": [1, 23, 231, 231, 4, 353, 62, 3, 56, 43, 354, 43, 231, 21, 7]}
df = pd.DataFrame(data=d)
std = df["col"].std()
df["mean5"] = df["col"].rolling(5).mean()
df["std5"] = df["col"].rolling(5).std()

print(std)
print(df[["mean5", "std5"]])

# OUTPUT
130.20855066648528
    mean5  std5 
0     NaN   NaN
1     NaN   NaN
2     NaN   NaN
3     NaN   NaN
4    98.0   NaN
5   168.4   NaN
6   176.2   NaN
7   130.6   NaN
8    95.6   NaN
9   103.4   NaN
10  103.6   NaN
11   99.8   NaN
12  145.4   NaN
13  138.4   NaN
14  131.2   NaN
```

#### Problem description
`.std()` and `.rolling().mean()` work as intended, but `.rolling().std()` only returns NaN
I just upgraded from Python 3.6.5 where the same code did work perfectly.
I am now on Python 3.7, pandas 0.23.2

#### Expected Output
```python
130.20855066648528
    mean5        std5
0     NaN         NaN
1     NaN         NaN
2     NaN         NaN
3     NaN         NaN
4    98.0  108.855868
5   168.4  134.226078
6   176.2  126.458531
7   130.6  138.965607
8    95.6  131.085621
9   103.4  126.482568
10  103.6  126.877264
11   99.8  128.342355
12  145.4  126.337010
13  138.4  131.941805
14  131.2  137.803338
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.23.2
pytest: None
pip: 10.0.1
setuptools: 39.0.1
Cython: None
numpy: 1.14.5
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.6.0
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
None

</details>

**Comment by TomAugspurger** [comment]
Hmm I can't reproduce with Python 3.7 and pandas 0.23.2

```python
In [1]: paste
import pandas as pd
d = {"col": [1, 23, 231, 231, 4, 353, 62, 3, 56, 43, 354, 43, 231, 21, 7]}
df = pd.DataFrame(data=d)
std = df["col"].std()
df["mean5"] = df["col"].rolling(5).mean()
df["std5"] = df["col"].rolling(5).std()

print(std)
print(df[["mean5", "std5"]])

## -- End pasted text --
130.20855066648528
    mean5        std5
0     NaN         NaN
1     NaN         NaN
2     NaN         NaN
3     NaN         NaN
4    98.0  121.704560
5   168.4  150.069317
6   176.2  141.384936
7   130.6  155.368272
8    95.6  146.558180
9   103.4  141.411810
10  103.6  141.853093
11   99.8  143.491115
12  145.4  141.249071
13  138.4  147.515423
14  131.2  154.068816

In [2]: pd.__version__
Out[2]: '0.23.2'
```

**Comment by TomAugspurger** [comment]
<details>

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Darwin
OS-release: 17.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.2
pytest: None
pip: 10.0.1
setuptools: 39.2.0
Cython: None
numpy: 1.14.5
scipy: None
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
```

</details>

Perhaps someone else will be able to reproduce.

A couple questions

1. How'd you install pandas? Conda or pip?
2. Can you try with 0.23.1?

**Comment by tweakimp** [comment]
I use pip. When I try to install 0.23.1 I get the error `: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools` although I have it installed :/

**Comment by TomAugspurger** [comment]
Probably something with your path...

@chris-b1 any chance this is related to the C++ build stuff? Can you try on 3.7 with the wheels on PyPI?

**Comment by tweakimp** [comment]
Can you link me to a pandas version 0.23.1 for python 3.7? [Here](https://pypi.org/project/pandas/0.23.1/#files) I only find versions up to 3.6.

**Comment by TomAugspurger** [comment]
0.23.1 didn’t support python 3.7. There aren’t any 3.7 wheels for it.

________________________________

**Comment by tweakimp** [comment]
I can not try with 0.23.1 then because the error only happens with python 3.7 for me

**Comment by chris-b1** [comment]
I reproduce on Windows 10 with 3.7 and the 0.23.1 wheel on PyPI, or building from source of PyPI (`--no-binary pandas`) or off of tagged release from cython.

At first review I'm stumped - the rolling var calc seems to only use c-math / pointers, nothing from libc[++].
https://github.com/pandas-dev/pandas/blob/8bee97a81764c5211d719d61a62424b1edfacd80/pandas/_libs/window.pyx#L746

**Comment by tweakimp** [comment]
I found two more functions with the same problem:
```python
import pandas as pd

d = {"col": [1, 23, 231, 231, 4, 353, 62, 3, 56, 43, 354, 43, 231, 21, 7]}
df = pd.DataFrame(data=d)
f = lambda x: sum(x, 1)
funcs = [
    "sum()",
    "apply(f)",
    "std()",
    "mean()",
    "median()",
    "var()",
    "min()",
    "max()",
    "corr(df['col'])",
    "cov()",
    "skew()",
    "kurt()",
    "quantile(0.3)",
]
for func in funcs:
    df[func] = eval(f"df['col'].rolling(5).{func}")
print(df)

#OUTPUT
    col  sum()  apply(f)  std()  mean()  median()  var()  min()  max()  corr(df['col'])    cov()    skew()    kurt()  quantile(0.3)
0     1    NaN       NaN    NaN     NaN       NaN    NaN    NaN    NaN              NaN      NaN       NaN       NaN            NaN
1    23    NaN       NaN    NaN     NaN       NaN    NaN    NaN    NaN              NaN      NaN       NaN       NaN            NaN
2   231    NaN       NaN    NaN     NaN       NaN    NaN    NaN    NaN              NaN      NaN       NaN       NaN            NaN
3   231    NaN       NaN    NaN     NaN       NaN    NaN    NaN    NaN              NaN      NaN       NaN       NaN            NaN
4     4  490.0     491.0    NaN    98.0      23.0    NaN    1.0  231.0              NaN  14812.0  0.587119 -3.305015            7.8
5   353  842.0     843.0    NaN   168.4     231.0    NaN    4.0  353.0              NaN  22520.8 -0.090732 -2.160449           64.6
6    62  881.0     882.0    NaN   176.2     231.0    NaN    4.0  353.0              NaN  19989.7 -0.109094 -1.604385           95.8
7     3  653.0     654.0    NaN   130.6      62.0    NaN    3.0  353.0              NaN  24139.3  0.842433 -1.366722           15.6
8    56  478.0     479.0    NaN    95.6      56.0    NaN    3.0  353.0              NaN  21479.3  2.037207  4.293414           14.4
9    43  517.0     518.0    NaN   103.4      56.0    NaN    3.0  353.0              NaN  19997.3  2.083480  4.516549           45.6
10  354  518.0     519.0    NaN   103.6      56.0    NaN    3.0  354.0              NaN  20122.3  2.084439  4.519378           45.6
11   43  499.0     500.0    NaN    99.8      43.0    NaN    3.0  354.0              NaN  20589.7  2.125084  4.642654           43.0
12  231  727.0     728.0    NaN   145.4      56.0    NaN   43.0  354.0              NaN  19951.3  1.011649 -0.994251           45.6
13   21  692.0     693.0    NaN   138.4      43.0    NaN   21.0  354.0              NaN  21760.8  0.968473 -1.163467           43.0
14    7  656.0     657.0    NaN   131.2      43.0    NaN    7.0  354.0              NaN  23737.2  0.924385 -1.324084           25.4
```

```python
std = df["col"].std()
var = df["col"].var()
corr = df["col"].corr(df["col"])
print(std, var, corr)

#OUTPUT (work as intended without the rolling window)
130.20855066648528 16954.266666666666 1.0
```

**Comment by chris-b1** [comment]
Thanks @tweakimp - those both also call the same cython routine (`roll_var`), so the same problem.

I've got it partially figured out - seems this branch is being (incorrectly) optimized out on the latest MSVC, works again if I throw a printf in there.  Still trying to riddle out if it's a compiler bug, or some flag set wrong.

https://github.com/pandas-dev/pandas/blob/8bee97a81764c5211d719d61a62424b1edfacd80/pandas/_libs/window.pyx#L659

**Comment by chris-b1** [comment]
hmm, turning off the [`/GL`](https://msdn.microsoft.com/en-us/library/0zza0de8.aspx) flag does fix this locally, but may be some broader performance implications of that and still not sure it should be necessary

```diff
(pandas-dev37) λ git diff setup.py
diff --git a/setup.py b/setup.py
index 8018d71b7..5535dd23f 100755
--- a/setup.py
+++ b/setup.py
@@ -455,7 +455,8 @@ def pxd(name):


 if is_platform_windows():
-    extra_compile_args = []
+    extra_compile_args = ['/GL-']
```

**Comment by tweakimp** [comment]
Workaround:
```python
.apply(lambda x: pd.np.std(x))
```

```python
import pandas as pd

d = {"col": [1, 23, 231, 231, 4, 353, 62, 3, 56, 43, 354, 43, 231, 21, 7]}
df = pd.DataFrame(data=d)
df["std5"] = df["col"].rolling(5).apply(lambda x: pd.np.std(x))
print(df["std5"])
# OUTPUT (as expected)
0            NaN
1            NaN
2            NaN
3            NaN
4     108.855868
5     134.226078
6     126.458531
7     138.965607
8     131.085621
9     126.482568
10    126.877264
11    128.342355
12    126.337010
13    131.941805
14    137.803338
```

**Comment by chris-b1** [comment]
Yep, do note that `np.std` defaults to a ddof of 0, while pandas uses 1.

**Comment by psicktrick** [comment]
can anyone suggest a similar workaround for rolling correlation between two columns of a dataframe?

**Comment by psicktrick** [comment]
Will downgrading to msvc 2015 help my case?

**Comment by chris-b1** [comment]
@psicktrick - if you are building from source, yes using MSVC 2015 will solve this issue, or you can also build from master, which has a fix applied.  As far as I know, not an easy workaround for corr, but should be a release of 0.23.4 soon (#22128)

**Comment by sherwany** [comment]
Hi,
Wondering if someone can please help me.
I am getting the same issue - using pandas 1.0.3 as well as 0.23.2 -  I have tried with Python 3.7 and 3.6.5.
The workaround mentioned above i.e. .apply(lambda x: pd.np.std(x)) doesn't fix the issue for me.

![SampleData](https://user-images.githubusercontent.com/9343396/89613249-b5be2000-d879-11ea-813c-4d6f663601bb.jpg)

Is there any other workaround I could use?
