### ISSUE TITLE
ENH: add suffixes arg to concat

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#21791]
xref #18347

the case for using ``add_suffix/add_prefix`` is either:

1. modify the column labels (can use ``.str.columns + ....``
2. concat with annotation lables from there source frames (and not using a MultiIndex)

so this is an issue about adding support for 2., similar to the way ``pd.merge`` suffixes work.

**Comment by WillAyd** [comment]
See discussion in #29669 I don't think we actually want this
