### ISSUE TITLE
How to perform below task using pandas which is faster and does not give warning 'SettingWithCopyWarning'

### ISSUE THREAD

**Issue by nainadhingra2012** [pandas-dev/pandas#21819]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
dftime =df.time 
for i in range (len(dftime)):
    if i!=0:
        if dftime[i]==dftime[i-1]:
            dftime[i]=dftime[i]+2
        if dftime[i]<dftime[i-1]:
            dftime[i]=dftime[i-1]+2
```
#### Problem description

I am accessing the timestamp from the data. If several timestamps have same value, then changing them. In that case add 2 to the second timestamp if two are same. If three are same then add 2 to second and add 4 to third and so on. I get a warning /anaconda/lib/python3.6/site-packages/ipykernel/main.py:8: SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

My problem is: it takes too long to perform the task. I want to know if there is some specific way to perform the task in a more precise way in pandas. Please consider I am new to panda.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

#### Expected Output
if input is:
0          1464149874011
1          1464149874014
2          1464149874014
3          1464149874019
4          1464149874022
5          1464149874022
6          1464149874031
7          1464149874037
8          1464149874038
9          1464149874040
10         1464149874054

output should be:
0          1464149874011
1          1464149874014
2          1464149874016
3          1464149874019
4          1464149874022
5          1464149874024
6          1464149874031
7          1464149874037
8          1464149874038
9          1464149874040
10         1464149874054
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by mroeschke** [comment]
We recommend StackOverflow for usage questions regarding Pandas. This tracker is designated for bug reports and enhancement requests.
