### ISSUE TITLE
DOC: Series.mask() should point to Series.where() and vice versa

### ISSUE THREAD

**Issue by teoguso** [pandas-dev/pandas#21825]
In the docs page of `pandas.Series.mask()`, the _See also_ cell that should point to related methods (at least in my understanding) is linking to `pandas.DataFrame.where()` instead of `pandas.Series.where()`
(See [here](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.mask.html) for the latest doc page).  
The same issue appears in the doc page of  `pandas.Series.where()` where `pandas.DataFrame.mask()` is linked.

Following the logic of the doc pages of `pandas.DataFrame.where()/.mask()`, where the two methods link each other, I assume that `pandas.Series.mask()` should link to `pandas.Series.where()` and vice versa.

I offer to take care of this small issue if it is substantial.

This is still there in 0.24.devX at the time of writing. 0.23.3 is the current stable release.

**Comment by jschendel** [comment]
Thanks!  I'd have the "See Also" sections for the four methods in question point to all three of the other methods, e.g. the "See Also" section for `Series.where` should point to `Series.mask`, `DataFrame.where`, and `DataFrame.mask` (likewise for the other variations).

**Comment by Dr-Irv** [comment]
This should be straightforward.  Work was done in https://github.com/pandas-dev/pandas/pull/21840 but that was never finished, so it should be a good first issue for someone.
