### ISSUE TITLE
Suggestion: Add some hint (or code example) in the error information

### ISSUE THREAD

**Issue by lbdhr** [pandas-dev/pandas#21837]
#### Code Sample, a copy-pastable example if possible

```python error information
# A value is trying to be set on a copy of a slice from a DataFrame.

```
#### Problem description
It is better to add some hints beside this error, or this information will coufuse many people. Suggestion: you can add a sentence like "Maybe you should reset the index of the slice". It can be more clear to make modification.

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by WillAyd** [comment]
Resetting the index is unrelated. I personally find the current message pretty straightforward but do you have a suggested alternate?

**Comment by TomAugspurger** [comment]
I could be wrong, but I don't think there's a way for us to know the precise cause. It could be slicing columns, boolean indexing, etc.

The link to the docs hopefully explains this well enough, though we'd welcome improvments there if you have suggestions.
