### ISSUE TITLE
Expose ExcelWriter as part of the Generated API

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#21835]
It has a docstring already (though it could use some examples) and would cover usage questions like the below:

https://stackoverflow.com/questions/46173710/where-can-i-find-the-excelwriter-documentation

**Comment by gorbondiga** [comment]
Hey WillAyd, I am trying to star contributing to pandas, I think this ticket could be a good start point for me, could you assign it to me?

**Comment by WillAyd** [comment]
We don't use the assignment feature in GitHub but feel free to work on it

**Comment by gfyoung** [comment]
@WillAyd : I use it from time to time as a way to get pinged should PR's or issues fall to the way side (@jreback at times will do a cleaning of stale issues / PR's).  But in this case, @gorbondiga , no need to assign you.  It's clear from the conversation history that you wanted to work on this first 🙂

**Comment by illegalnumbers** [comment]
Is this still needing work?

**Comment by gfyoung** [comment]
@illegalnumbers : Indeed, it does!  Go for it, if you want.

**Comment by illegalnumbers** [comment]
I'll see if I can find some time in the next couple days!
