### ISSUE TITLE
SIGSEGV when calling .copy()

### ISSUE THREAD

**Issue by Krogsager** [pandas-dev/pandas#21831]
#### Problem description
I try to create a new dataframe _df_, with columns from the dataframe _dfCats_.
The three lists self.cat_vars, self.contin_vars and self.dlist contain column names.
I get the error

> Segmentation fault (core dumped)

From the code:
`df = dfCats[self.cat_vars + self.contin_vars + self.dlist].copy()`

But if I add the line

```
df = dfCats.copy()
df = dfCats[self.cat_vars + self.contin_vars + self.dlist].copy()

```
The error does not occur.
Why can I suddenly not make a copy of the dataframe like I used to?

#### Expected Output
No segmentation fault.

#### Output of ``pd.show_versions()``
```

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-104-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.3
pytest: 3.6.2
pip: 9.0.3
setuptools: 39.2.0
Cython: None
numpy: 1.14.5
scipy: 1.1.0
pyarrow: 0.8.0
xarray: None
IPython: 6.4.0
sphinx: 1.7.1
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: 3.4.2
numexpr: 2.6.4
feather: 0.4.0
matplotlib: 2.2.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
```

</details>

**Comment by WillAyd** [comment]
We will need a minimally reproducible example to take look:

http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by Krogsager** [comment]
I haven't been able to reproduce the error, but I have narrowed it down in my own data.
A column of dtype categorical: when I try to read from it the error occurs.
I don't know how to investigate the problem when I cannot read it. Any suggestions?

**Comment by Krogsager** [comment]
I've found the issue to be caused by another library and opend a ticket there
https://github.com/fastai/fastai/issues/616

**Comment by WillAyd** [comment]
OK with that being the case I'm going to close this out. If there's something you see specific to pandas in the future feel free to reopen with a reproducible example
