### ISSUE TITLE
Python Pandas Conditional Formatting

### ISSUE THREAD

**Issue by BlaueBerre** [pandas-dev/pandas#21832]
#### Code Sample, a copy-pastable example if possible

def color_negative_red(val):
    color = 'red' if val < 10 else 'green'
    return 'color: %s' % color

df=df.style.applymap(color_negative_red)
df

#### Problem description

Hello there,

I wrote a few lines to assing numbers one of two colors based on their value. The problem is it does not work with floating point numbers. If I use floating numbers I get the following:

TypeError: ("'<' not supported between instances of 'str' and 'int'")

I works with whole number though! Does anybody know how I can make it work with floating number?

Thanks in advance an greetings

**Comment by otro-mas1** [comment]
For three values, red, black blue

Can you try?

```
def color_negative_red(val):
    color = 'black'
    if val < -1 : color = 'red'
    if val > 1 :  color = 'blue'
    return 'color: %s' % color

```

**Comment by BlaueBerre** [comment]
Thanks for your suggestion. But it doesn´t work either.

**Comment by BlaueBerre** [comment]
Get´s me the same error as before.

**Comment by TomAugspurger** [comment]
Can you provide a minimal example? 
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

It's hard to say, but I suspect the `val` passed to your `color_negative_red` function is a string, not a float.

**Comment by BlaueBerre** [comment]
@TomAugspurger yo were rigth, the dataframe had a few colums with strings in it. It worked with subset. Thanks for the help.

Here a little example that worked:

import pandas as pd

d = {'col1': [1, 2], 'col2': ['hello', 'bye'], 'col3': [3.134, 5.1]}
df = pd.DataFrame(data=d)

def color_negative_red(val):
    color = 'black'
    if val < -1 : color = 'red'
    if val > 1 :  color = 'green'
    return 'color: %s' % color


df=df.style.applymap(color_negative_red, subset=['col3'])
df
