### ISSUE TITLE
Connect Timeout Install pandas 

### ISSUE THREAD

**Issue by aliridha1510** [pandas-dev/pandas#21842]
C:\Windows\system32>python -m pip install pandas
Collecting pandas
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002644EEE5860>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pandas/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002644EEE5D68>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pandas/

**Comment by TomAugspurger** [comment]
Looks like you're having trouble connecting to pypi.

I'd recommend waiting a bit before trying again. Otherwise it could be an issue with pip.

**Comment by aliridha1510** [comment]
python -m pip install pandas
Collecting pandas
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002420342A630>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pandas/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002420342A710>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pandas/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002420342A470>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pandas/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002420342A358>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pandas/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002420342A208>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/pandas/
  Co**uld not find a version that satisfies the requirement pandas (from versions: )
No matching distribution found for pandas**
