### ISSUE TITLE
Missing values when displaying Multi-index after groupby in notebook

### ISSUE THREAD

**Issue by bmaisonn** [pandas-dev/pandas#21857]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame({'a':[True, False, False, True], 'b':[True, True, False, False], 'c': [1,2,3,4], 'd':[1,1,1,1]})
df_count = df.groupby(['c','a','b']).count()
```
I get 

![image](https://user-images.githubusercontent.com/7989822/42571064-43d92ee8-8516-11e8-957f-b19ffad8b071.png)

which is correct

However if i unstack the two levels corresponding to 'a' and 'b'

```python
df_count.unstack([1,2])
```

I get this

![image](https://user-images.githubusercontent.com/7989822/42571153-85032aae-8516-11e8-9c27-abbbb9e62f4f.png)

#### Problem description

For an unknown reason the 'False' label is missing on the 'a' line and there's no shade to indicate a group so it make the result very difficult to interpret.

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.21.0
pytest: 3.5.1
pip: 10.0.1
setuptools: 28.8.0
Cython: None
numpy: 1.14.5
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.3.1
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.4
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.1
bs4: None
html5lib: 1.0.1
sqlalchemy: 1.1.15
pymysql: None
psycopg2: 2.7.4 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: 0.1.0
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by bmaisonn** [comment]
Ok my bad, i was misled by the shades.

**Comment by bmaisonn** [comment]
Re-opening as the issue occurs when untacking multi-index levels

**Comment by jschendel** [comment]
This is the expected behavior.  By default, `pandas` will sparsify contiguous higher levels of `MultiIndex` objects.  The reason you're seeing two instances of `True` is because your columns are not sorted.  Also note that your top level column, `'d'`, is only displayed once for this same reason.

Replicating your setup:
```python
In [2]: df = pd.DataFrame({'a':[True, False, False, True], 
   ...:                    'b':[True, True, False, False],
   ...:                    'c': [1,2,3,4],
   ...:                    'd':[1,1,1,1]})
   ...: df = df.groupby(['c','a','b']).count()
   ...: df = df.unstack([1,2])
   ...:                    

In [3]: df
Out[3]: 
      d                  
a True  False       True 
b True  True  False False
c                        
1   1.0   NaN   NaN   NaN
2   NaN   1.0   NaN   NaN
3   NaN   NaN   1.0   NaN
4   NaN   NaN   NaN   1.0
```
Sorting the columns sparsifies `True`:
```python
In [4]: df.sort_index(axis=1)
Out[4]: 
      d                  
a False       True       
b False True  False True 
c                        
1   NaN   NaN   NaN   1.0
2   NaN   1.0   NaN   NaN
3   1.0   NaN   NaN   NaN
4   NaN   NaN   1.0   NaN
```

This behavior can be controlled with `pd.options.display.multi_sparse`:
```python
In [5]: pd.options.display.multi_sparse = False

In [6]: df
Out[6]: 
      d     d     d     d
a True  False False True 
b True  True  False False
c                        
1   1.0   NaN   NaN   NaN
2   NaN   1.0   NaN   NaN
3   NaN   NaN   1.0   NaN
4   NaN   NaN   NaN   1.0
````

**Comment by bmaisonn** [comment]
Thx for the information !
