### ISSUE TITLE
read_csv fails when both escaped quote and comma are present

### ISSUE THREAD

**Issue by esdu** [pandas-dev/pandas#21862]
#### Code Sample, a copy-pastable example if possible

```python
import os
import pandas as pd

with open("/tmp/test.csv", "w") as f:
    f.write('''title,description
Jeans,"blue"
Jeans,"2\" seam"
Jeans,"2\" seam, blue"
''')
    
pd.read_csv("/tmp/test.csv")
```

#### Problem description

Ideally, this would output:

```
	title	description
0	Jeans	blue
1	Jeans	2" seam
2	Jeans	2" seam, blue
```

However, the code above outputs an error: 

> ParserError: Error tokenizing data. C error: Expected 2 fields in line 4, saw 3

If I just read up to the second line (excluding the `Jeans,"2\" seam, blue"` line), it reads it without error but the result is wrong:

```
	title	description
0	Jeans	blue
1	Jeans	2 seam"
```

A similar past issue is https://github.com/pandas-dev/pandas/issues/18382, but the fix doesn't work here. ie. this command:

```
pd.read_csv("/tmp/test.csv", escapechar='\\', quoting=csv.QUOTE_NONE)
```

Yields the same error.

#### Expected Output

See above.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Darwin
OS-release: 16.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_CA.UTF-8
LOCALE: en_CA.UTF-8

pandas: 0.23.3
pytest: None
pip: 10.0.1
setuptools: 36.0.1
Cython: None
numpy: 1.13.3
scipy: 0.19.0
pyarrow: None
xarray: None
IPython: 6.1.0
sphinx: None
patsy: None
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.6.0
html5lib: 0.9999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by Liam3851** [comment]
@esdu You need to escape the backslash in your example to actually write the backslashes to your file:

```python
with open("/tmp/test.csv", "w") as f:
    f.write('''title,description
Jeans,"blue"
Jeans,"2\\" seam"
Jeans,"2\\" seam, blue"
''')
```

then just read as 
```
pd.read_csv("/tmp/test.csv", escapechar='\\')
```

**Comment by esdu** [comment]
You're right! Thanks @Liam3851
