### ISSUE TITLE
pandas applying a method to a few selected columns in a dataframe

### ISSUE THREAD

**Issue by BlaueBerre** [pandas-dev/pandas#21875]
Hello there,

I would like to apply a little method to several columns in a Dataframe. The method color_negative can´t be applied to columns with strings, therefore I need to skip these columns somehow. I could think of two approaches to solve the problem, though sadly none is working.

In approach 1 I try so apply the method to every column one by one skipping the first one by using the index of the Dataframe and by setting the incrementing counter of the while loop to 1. When executing this approach I get the error, that the 'Series' object has no attribute 'style', so apparently I can´t apply a method to single column.

In approach 2 i try to use subset to apply the method only to those columns with numeric values, though I ´m not sure if I use subset correctly. When executing this approach I get the error that object of type 'Styler' has no len().

Here a simplified example:

```
import pandas as pd

d = {'col1': ['a', 'b'], 'col2': [21, 22], 'col3': [3, 51]}
df = pd.DataFrame(data=d)

def color_negative_red(val):
    color = 'black'
    if val < -1 : color = 'red'
    if val > 1 :  color = 'green'
    return 'color: %s' % color    
    
i=1
while i <= len(df):
    #Approach 1
    df.iloc[:, i] = df.iloc[:, i].style.applymap(color_negative_red)
    #Approach 2
    df = df.style.applymap(color_negative_red, subset = df.iloc[:, i])
    i+=1    

df
```
Has anyone a suggestion on how to solve this problem?

Thanks in advance and greetings

**Comment by TomAugspurger** [comment]
`subset` takes the columns to apply it to. It looks like you're passing a DataFrame.

Also, `df.style.applymap(color_negative_red, subset = df.iloc[:, i])` is going to return a Styler, not a DataFrame, so I don't think your `while` loop is doing what you're hoping.

You might try making a smaller example and asking on StackOverflow, since I don't think there's a bug here.
