### ISSUE TITLE
Incorrect error is shown

### ISSUE THREAD

**Issue by ron819** [pandas-dev/pandas#21876]
I have the following code:
`df.to_sql(sql_table, engine, None, sql_schema, if_exists='append', index=False)`

apparently someone updated the pandas version and it had effect of some of our scripts. The 'None' argument which used to be acceptable with older pandas versions (flavor) is not accepted anymore.

The thing is that the error raised for the code with Pandas 0.23.3 is:
`TypeError: to_sql() got multiple values for keyword argument 'if_exists'`

This is highly misleading and confusing. It took me a while to debug and understand that the error is related to the `None `argument. 
Python can raise errors for more argument than needed why isn't this error is shown? error about wrong number of argument can focus users to the actual problem.

**Comment by jreback** [comment]
Passing args by position for a large signature is fraught with risk. 

If you had been passing kwargs all along you would have gotten a more useful message.
```
In [3]: DataFrame().to_sql('table', 'engine', flavor=None, schema='sql_schema', if_exists='append', index=False)
TypeError: to_sql() got an unexpected keyword argument 'flavor'
```
