### ISSUE TITLE
First row left-truncated when appending to file object via DataFrame.to_csv()

### ISSUE THREAD

**Issue by phobson** [pandas-dev/pandas#21882]
#### Code Sample, a copy-pastable example if possible

```python
from io import StringIO
import pandas
df = pandas.read_csv(StringIO("""\
x,y
3192056,13904123
3192340,13904044
3192625,13903965
3192909,13903886
3193193,13903807
"""))

with open('test.out', 'w') as f:
    f.writelines(['## {1:d}, {0:d}\n'.format(454, 218)])
    df.to_csv(f, sep=' ', index=False, header=False,
              na_rep='NaN', float_format='%.3f')
```

Which writes:

```
$ cat test.out
## 218, 454
4123
3192340 13904044
3192625 13903965
3192909 13903886
3193193 13903807

```
#### Problem description

Ok, this one has me stumped.

If I open a file object, write a line to it, then pass the object to `.to_csv` the first few characters of the first line are removed.

#### Expected Output

```
$ cat test.out
## 218, 454
3192056 13904123
3192340 13904044
3192625 13903965
3192909 13903886
3193193 13903807

```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-43-Microsoft
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.1
pytest: 3.6.2
pip: 9.0.3
setuptools: 39.2.0
Cython: None
numpy: 1.14.2
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.5
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: 1.2.8
pymysql: None
psycopg2: 2.7.5 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by WillAyd** [comment]
Can you try on master?

**Comment by phobson** [comment]
@WillAyd 

Thanks for the responsive. It does appear that this is fixed in master.

```
$ conda create --name=pdtest python=3.6 pandas ipykernel cython
$ conda activate pdtest
$ python maybe_pdbug.py
$ cat test.out
## 218, 454
3192056 13904123
3192340 13904044
3192625 13903965
3192909 13903886
3193193 13903807
```

I tried a couple of incantations on 0.23.1. I won't list them all here since the bug is fixed in master. But for posterity, here is the current work around (that I could find).

```python
with open('test.out', 'w') as f:
    f.writelines(['## {1:d}, {0:d}\n'.format(454, 218)])
    
with open('test.out', 'a') as f:  # need 'a' mode here
    df.to_csv(f, sep=' ', index=False, header=False,
              na_rep='NaN', float_format='%.3f',
              mode='a')  # and need 'a' mode here too
```
