### ISSUE TITLE
Slowdown of str(record) of DataFrame.to_records() method

### ISSUE THREAD

**Issue by gitrus** [pandas-dev/pandas#21880]
#### Repo with sample

https://github.com/gitrus/sample-pandas/blob/master/src/sample-pandas/main.py

#### Problem description
pandas versions 0.22.0 - 0.23.3

Slowdown of str(record) of DataFrame method `to_records`. 
The method slows down 50 times, with any version of numpy> 1.14.0.

#### Output of ``pd.show_versions()``

First run:
<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.87-linuxkit-aufs
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.3
pytest: None
pip: 10.0.1
setuptools: 39.2.0
Cython: None
numpy: 1.14.0
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
None
</details>

Second run:
<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.87-linuxkit-aufs
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.3
pytest: None
pip: 10.0.1
setuptools: 39.2.0
Cython: None
numpy: 1.14.5
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
None

</details>

**Comment by WillAyd** [comment]
Hmm OK - it's not immediately apparent from your example if the difference would be a result of pandas or numpy (leaning towards the latter since that's what changes between your examples) but investigation and PRs are always welcome! 

At the very least looks like we don't have an ASV for `to_records` so would take that if you want to add

**Comment by mroeschke** [comment]
Looks like we have `to_records` benchmarks now and its not entirely clear this was due to pandas so closing for now
