### ISSUE TITLE
DEPR: Pandas 0.24.0 Deprecations

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#21894]
We'd like to have all these deprecations in place for 0.24.0, and enforced in 1.0

As a reminder, the plan is to have no new deprecations in 0.25.x and 1.0.0. So this is the last round of deprecations before 1.0.

- [ ] `Series.rename(scalar)` -> `Series.set_name` (xref https://github.com/pandas-dev/pandas/issues/14829)
- [ ] `NDFrame.filter`
- [ ] `NDFrame.between`? (https://github.com/pandas-dev/pandas/issues/13027)

cc @pandas-dev/pandas-core

**Comment by TomAugspurger** [comment]
@jorisvandenbossche @jreback do you know the current thoughts on deprecating filter? Just need someone to do it? I'm going to do `Series.rename(scalar)` now, will follow up with filter if so.

If people have thoughts on `.between`, discuss in https://github.com/pandas-dev/pandas/issues/13027 and I'll update here.

Feel free to add additional deprecations that we don't want to live with for 1.x.

**Comment by shoyer** [comment]
@TomAugspurger I hate to revisit things... but do you mind holding off for a little while on `Series.rename`? I'd like to take a look at #14829, maybe revisit some alternative APIs...

**Comment by TomAugspurger** [comment]
No worries. I think the decision on `Series.rename(scalar)` does depend on the decision in #14829.

**Comment by jorisvandenbossche** [comment]
As I said during the sprint, I am personally not in favor of deprecating the *full* `filter` method, but would rather like to deprecate the default axis, so we can keep it for the obvious behaviour (but need to look into it in more detail to explore if this is somewhat possible).

**Comment by TomAugspurger** [comment]
> but would rather like to deprecate the default axis

When you get a chance, can you write that up? I'm having trouble recalling the discussion.

**Comment by topper-123** [comment]
I think NDFrame.filter provides some nice functionality, but has an unfortunate name that can be mixed up with Groupby.filter.

I'd like to keep it, but rename it to something else perhaps.

**Comment by jreback** [comment]
I think between is ok (no deprecation)

what happened to the original list which was much longer?

**Comment by topper-123** [comment]
Older longer list: #18262

**Comment by h-vetinari** [comment]
~~Most likely too late to the game, but for completeness I'd like to add: if #21855 #21858 are solved for v0.24, then `combine_first` could be deprecated at the same time, see #21859~~

Edit: Skipped a step in my head - `combine_first` has no `DeprecationWarning` yet, so this suggestion was premature. I'll settle for post-1.0 ;-)

**Comment by TomAugspurger** [comment]
Sorry, I forgot about https://github.com/pandas-dev/pandas/issues/18262

Let's move this discussion there.
