### ISSUE TITLE
ABCClasses for DatetimeArray etc?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#21895]
There are a handful of places in the code where we check for for `isinstance(other, ABCDatetimeIndex)` or `getattr(other, '_typ', None) == "datetimeindex"` (and analogous places for TDI, PI).  In most of these cases DatetimeArray/TimedeltaArray/PeriodArray should be handled symmetrically.  Thoughts on what `_typ`s to give them?

**Comment by jreback** [comment]
we don’t have this notion for EA but we either should or alternatively just use isinstancs o the EA (iow don’t define ABCs

but if it makes it simpler i would make an ABC hierarchy that is distinct from the current ones

**Comment by jbrockmendel** [comment]
Well there is an `ABCExtensionArray`.  For some of it we can probably get away with changing e.g `isinstance(foo, ABCPeriodIndex)` to `is_period_dtype(foo)`.  The cython cases that explicitly check _typ will need special handling.

**Comment by jbrockmendel** [comment]
Closed by #23502
