### ISSUE TITLE
[EA] ExtensionArray should support ndim==2

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#21908]
There are a bunch of issues (indirectly) caused by the fact that we can't reshape a `DatetimeIndex[tz]` as 2D.

#13287, #17539, #19197, and each of the several issues about interpolation with `datetime64[tz]` dtypes.  At the end of `DataFrame._init_ndarray` is:

```
        if dtype is None and is_object_dtype(values):
            values = maybe_infer_to_datetimelike(values)

        return create_block_manager_from_blocks([values], [columns, index])
```

but in the relevant cases, `maybe_infer_to_datetimelike` returns a tz-aware `DatetimeIndex`, which `create_block_manager_from_blocks` raises on because it is expecting `values` to be 2D.

I cleanest way to fix this seems to be supporting 2D shapes for `DatetimeArray` (and ideally others for compat)

**Comment by jbrockmendel** [comment]
> We deliberately restricted it to 1D, and I think that is still the good way to go.

I'll try to track down this discussion and see the original reasoning.  AFAICT the main thing we get out of the 1D restriction is not having to worry about `axis` arguments, but we're paying for it by sacrificing a lot of the generality people think of with "array"s.

**Comment by jreback** [comment]
i agree that we should restrict to 1D and just move datetime to EA

**Comment by jbrockmendel** [comment]
> i agree that we should restrict to 1D and just move datetime to EA

We _are_ moving datetime to EA, that is currently in progress.  What I'm saying is that there are bugs that are caused by the inability to reshape e.g. `dtarr.reshape((N, 1))` and I'm not clear what we get in exchange for that restriction (still looking for the old discussion).

**Comment by jorisvandenbossche** [comment]
> What I'm saying is that there are bugs that are caused by the inability to reshape 

We will need to update the code to handle with 1D instead of 2D, for sure.

> AFAICT the main thing we get out of the 1D restriction is not having to worry about axis arguments, 

Yes, I think that is one of the main reasons. This fact is one of the things that make the current block manager really complex.

**Comment by jbrockmendel** [comment]
Fair enough.  Closing, will chime in in the appropriate place.
