### ISSUE TITLE
BLD: wheel building is broken

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#21927]
https://travis-ci.org/MacPython/pandas-wheels/jobs/401351130

seems this has been broken for 8 days

maybe the recent cython changes?

cc
@jbrockmendel

**Comment by jbrockmendel** [comment]
It isn't caused by the SSLError in downloading numpy?

**Comment by jbrockmendel** [comment]
Some of these are 32 bit builds which should be fixed by #21923.

**Comment by jbrockmendel** [comment]
8 days ago was when I noticed that Homebrew had updated from 3.6 to 3.7, looks like the actual rollout was 16 days ago.  Not quite sure how that could be relevant, but the timing makes it worth mentioning.

**Comment by xhochy** [comment]
I made a PR that fixes the problems with Cython: https://github.com/MacPython/pandas-wheels/pull/32

The two red builds there are due to the 32bit issue and unrelated to the Cython update.

**Comment by jreback** [comment]
thanks @xhochy I had already fixed this yesterday, builds not passing.
