### ISSUE TITLE
 categorical column bugs pivot_table

### ISSUE THREAD

**Issue by romainjouin** [pandas-dev/pandas#21931]
#### Code Sample, a copy-pastable example if possible

```python
test = pd.DataFrame({'closing_mois': {6483: 'juillet',
  19771: 'avril',
  19105: 'avril',
  8025: 'novembre',
  22642: 'mai',
  1216: 'juillet',
  21634: 'décembre',
  19230: 'décembre',
  11429: 'décembre',
  24755: 'juin'},
 'closing_week': {6483: 28,
  19771: 16,
  19105: 16,
  8025: 48,
  22642: 20,
  1216: 31,
  21634: 49,
  19230: 49,
  11429: 52,
  24755: 25},
 'montant': {6483: 15830,
  19771: 13637,
  19105: 28197,
  8025: 42671,
  22642: 41290,
  1216: 575,
  21634: 898,
  19230: 13814,
  11429: 2006,
  24755: 40633}})
test.groupby(["closing_mois", "closing_week"])["montant"].sum()
mois = OrderedDict({1:"janvier", 2:"février", 3:"mars", 4:"avril", 5: "mai", 6:"juin", 7:"juillet", 8:"août", 9:"septembre", 10:"octobre", 11:"novembre", 12:"décembre"})
cat  = pd.Categorical(list(mois.values()), ordered=True)
test.closing_mois = test.closing_mois.astype(cat)
test.pivot_table(index="closing_mois", columns="closing_week", values="montant", aggfunc=pd.Series.sum)

```
#### Problem description

The pivot table doesn't give the same output as the groupby. Leading to 2 differents output for the same logical calculus.

#### Expected Output
closing_week    16  20  25  28  31  48  49  52
closing_mois                                
juillet 41834.0 NaN NaN NaN NaN NaN NaN NaN
novembre    NaN NaN NaN NaN NaN NaN 14712.0 2006.0
décembre    NaN NaN NaN 15830.0 575.0   NaN NaN NaN
avril   NaN NaN 40633.0 NaN NaN NaN NaN NaN
mai NaN 41290.0 NaN NaN NaN NaN NaN NaN
juin    NaN NaN NaN NaN NaN 42671.0 NaN NaN

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Darwin
OS-release: 17.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: ”en_US.UTF-8″
LOCALE: None.None

pandas: 0.23.0
pytest: 3.5.1
pip: 10.0.1
setuptools: 39.2.0
Cython: 0.28.2
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.2.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by gfyoung** [comment]
@romainjouin : Thanks for this report!

When you do a `groupby`, any grouped on columns will form the index of the output `DataFrame`.  Thus, the `MultiIndex` on `"closing_mois"` and `"closing_week"` that you see from the `groupby` is expected in fact.

Hopefully that clarifies things!  Can always be re-opened if this is later determined to be an actual bug.

**Comment by romainjouin** [comment]
Hi,
thanks for your answer.
I am not sure I do understand it completely, but I have to precise that the result is different with pandas version 0.19 and 0.23.
On my point of view there is a bug on 0.23, and 0.19 is working fine.

I precised it here : https://stackoverflow.com/questions/51362044/pandas-categorical-column-bugs-pivot-table/51362304?noredirect=1#comment89697225_51362304

Is it expected to have different value on v 0.23 and 0.19  ?

**Comment by gfyoung** [comment]
Your SO post is confusing me a little because your setup code is different in the discussions.  <ul>Running the exact same code that you have posted here</ul>, what do you get when using `v0.19` vs. `v0.23`?

In any case, the output that I'm seeing from running your code looks fine to me.

**Comment by romainjouin** [comment]
My fault.
I put the bug as expected output  👎 

with v0.23 I have  the week 52 in june: 

closing_week    16  20  25  28  31  48  49  52
closing_mois                                
juillet 41834.0 NaN NaN NaN NaN NaN NaN NaN
novembre    NaN 41290.0 NaN NaN NaN NaN NaN NaN
décembre    NaN NaN 40633.0 NaN NaN NaN NaN NaN
avril   NaN NaN NaN 15830.0 575.0   NaN NaN NaN
mai NaN NaN NaN NaN NaN 42671.0 NaN NaN
juin    NaN NaN NaN NaN NaN NaN 14712.0 2006.0

while in v0.19 week 52 is really (as it should be) in december : 

closing_week       16       20       25       28     31       48       49  \
closing_mois                                                                
janvier           NaN      NaN      NaN      NaN    NaN      NaN      NaN   
février           NaN      NaN      NaN      NaN    NaN      NaN      NaN   
mars              NaN      NaN      NaN      NaN    NaN      NaN      NaN   
avril         41834.0      NaN      NaN      NaN    NaN      NaN      NaN   
mai               NaN  41290.0      NaN      NaN    NaN      NaN      NaN   
juin              NaN      NaN  40633.0      NaN    NaN      NaN      NaN   
juillet           NaN      NaN      NaN  15830.0  575.0      NaN      NaN   
août              NaN      NaN      NaN      NaN    NaN      NaN      NaN   
septembre         NaN      NaN      NaN      NaN    NaN      NaN      NaN   
octobre           NaN      NaN      NaN      NaN    NaN      NaN      NaN   
novembre          NaN      NaN      NaN      NaN    NaN  42671.0      NaN   
décembre          NaN      NaN      NaN      NaN    NaN      NaN  14712.0   

closing_week      52  
closing_mois          
janvier          NaN  
février          NaN  
mars             NaN  
avril            NaN  
mai              NaN  
juin             NaN  
juillet          NaN  
août             NaN  
septembre        NaN  
octobre          NaN  
novembre         NaN  
décembre      2006.0

**Comment by gfyoung** [comment]
@romainjouin : Sorry, but I can't replicate that output.  Week 52 for `juin` is `NaN` for me.
