### ISSUE TITLE
Summary Method Misleading for Unsorted TimeseriesIndex Object

### ISSUE THREAD

**Issue by missing-semicolon** [pandas-dev/pandas#21936]
#### Code Sample

```python
import pandas as pd
import numpy as np
np.random.seed = 12345

ts = pd.date_range(start='2018-01-01', end='2018-06-30', freq='M')
ts.summary()  # Works as expected
> 'DatetimeIndex: 6 entries, 2018-01-31 to 2018-06-30\nFreq: M'

ts_scrambled = np.random.choice(ts, len(ts), replace=False)
pd.DatetimeIndex(ts_scrambled).summary()  # Not good.
> 'DatetimeIndex: 6 entries, 2018-01-31 to 2018-04-30'

```
#### Problem description
This is an issue when a DataFrame's index is set via the `set_index` method and it is applied to an unsorted column. The summary output of the resulting index is misleading.

#### Expected Output
```
>'DatetimeIndex: 6 entries, 2018-01-31 to 2018-06-30\nFreq: M'
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.4.final.0
python-bits: 64
OS: Linux
OS-release: 4.1.35-pv-ts2
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.utf8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: 3.2.1
pip: 9.0.1
setuptools: 36.4.0
Cython: 0.26
numpy: 1.12.1
scipy: 0.19.1
pyarrow: 0.8.0
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: None
xlsxwriter: 0.9.8
lxml: None
bs4: 4.6.0
html5lib: 0.9999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by gfyoung** [comment]
I wouldn't necessarily call it misleading, but indeed, being able to extract more information, even though it's unordered, would be nice.

**Comment by jreback** [comment]
so you could add a modifier (sorted / unsorted) and use min / max i think 

though this might be itself misleading 
as it is displaying the first and last elements

**Comment by jbrockmendel** [comment]
Does this affect DataFrame.summary?  The Index method itself has been removed.

**Comment by mroeschke** [comment]
Looks like `summary` has been completely removed, so this issue is not longer relevant. Closing
