### ISSUE TITLE
Allow the other direction of df.drop

### ISSUE THREAD

**Issue by ron819** [pandas-dev/pandas#21945]
As mentioned here:
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.drop.html

```
>>> df = pd.DataFrame(np.arange(12).reshape(3,4),
...                   columns=['A', 'B', 'C', 'D'])
>>> df
   A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
```

panda allows to remove columns if specifying their names.

```
>>> df.drop(['B', 'C'], axis=1)
   A   D
0  0   3
1  4   7
2  8  11

```
Meaning the requested feature is:

```

>>> df.dropelse(['B', 'C'], axis=1)`
     B   C   
0   1   2   
1   5   6   
2   9  10 

```

I found out that for many approaches the opposite was is preferred - meaning specifying the columns that should stay and remove everything not on the list. This extremely helpful when you know the columns that you want but you have no idea what are the other column names.

**Comment by jreback** [comment]
this is just called slicing and already well established, adding additional api is just guaranteed to confuse even more.

**Comment by ron819** [comment]
@jreback @h-vetinari  Maybe a better solution is to add this example to the docs?
I asked this question on stackoverflow... over 8 different answers suggested stuff like defining two dataframes, create csv and use header for columns and many other things that are not a real solution. This means that many people doesn't know how to use it correctly.. so maybe just showing the above answer in the docs can solve such confusion :)

**Comment by jreback** [comment]
you can certainly submit a PR to do that if you think the docs are lacking in someway

**Comment by h-vetinari** [comment]
@ron819 If you point me to the SO question, I can answer it there. Not sure either what you're looking for in the docs, selecting columns is one of the most basic operations on a `DataFrame` (more so than `drop`-ing, I'd say).
