### ISSUE TITLE
reading file with empty first column result in odd behavior

### ISSUE THREAD

**Issue by streamnsight** [pandas-dev/pandas#21961]
#### Problem description

`read_excel(file, thousands=',', encoding='utf-8')` 

create a DataFrame with an index with all NaNs when the first column of the excel file is empty

#### Expected Output

a generated index [0,1,2,3,4,5,...]

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.10.final.0
python-bits: 64
OS: Darwin
OS-release: 17.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.23.3
pytest: None
pip: 10.0.1
setuptools: 39.2.0
Cython: None
numpy: 1.13.3
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: None
sphinx: 1.5.5
patsy: 0.5.0
dateutil: 2.6.1
pytz: 2015.7
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: 0.9.4
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: 2.7.3.2 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None</details>

**Comment by gfyoung** [comment]
@streamnsight : Can you provide a reproducible example?  Unfortunately, we can't run what you have provided here so far.

**Comment by gfyoung** [comment]
We just need you to create an Excel file that illustrates the problem.  No need to include proprietary data for this.

**Comment by streamnsight** [comment]
@gfyoung  Again, the file that was causing me problems is a file that was given to me. I tried to repo by creating a similarly featured file (i.e. an empty first column) with Numbers (on mac) and saving it as XLSX, but that didn't produce the problem. So if you have access to Excel and can try to repro, it's simple to create a file with an empty 1st column (i.e. no header, no data)

if that works, then it must be something else that is off with this file I have, but I don't know how to figure out what is wrong with it.

**Comment by WillAyd** [comment]
There's really no way to be able to reproduce this issue with the information given. If you can provide an Excel file without proprietary data then feel free to reopen
