### ISSUE TITLE
Feature Request: nested tables

### ISSUE THREAD

**Issue by chrber** [pandas-dev/pandas#21964]
Hi there,

I would like to see nested tables. Yes, I know, I could contribute and write it myself, but I contribute to other open source projects already.

I have this question on [Stackoverflow](https://stackoverflow.com/questions/51027339/dataframe-table-in-table-from-nested-dictionary) (All description can be found there)

which is concerning nested tables. It seems that I can not achieve exactly what I want with pandas. Maybe this is intentional, maybe not.

However, if others find it useful, maybe it can be added.

Thank you very much.
Kind regards.
Christian

**Comment by jreback** [comment]
well you are asking for a lot actually, a lot can be achieved today:

- embedded lists are supported, though not in a first class way
- JSON ExtensionArray type already supports nesting 
- you are actually asking about sparse displays, you can do this with a MultiIndex

**Comment by jreback** [comment]
closing as this question is way too broad and needs a specific example of what is required.
