### ISSUE TITLE
Feature: optional use seaborn as plot backend.

### ISSUE THREAD

**Issue by eromoe** [pandas-dev/pandas#21975]
#### Problem description

It is very easy to use `df.sale_count.plot(figsize=(16, 8 ), kind='bar', xticks=range(24), grid=True)` .
The only fly in the ointment is that it is not as beautiful as convenience .
People have to change their code, why not accept seaborn as another plot backend  ?

**Comment by TomAugspurger** [comment]
I don't think "backend" is the right word for what you want. Matplotlib is the plotting backend for pandas and seaborn.

Right now our suggestion is to use `pipe`: `df.pipe((sns.scatterplot, 'data'), ...)`.
