### ISSUE TITLE
iloc calls should not reach indexes code

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#21989]
Related to #21982, which however only fixes one particular case: there are more.

Will soon push a branch with more substantial changes - which however is still not ready (breaks some tests).

**Comment by toobaz** [comment]
This is the branch I was mentioning: https://github.com/toobaz/pandas/tree/iloc_with_non_int_round2

I'll try look at the broken tests in August.

**Comment by jbrockmendel** [comment]
@toobaz is this still an issue?  there's been quite some refactoring since it was opened

**Comment by toobaz** [comment]
@jbrockmendel I _think_ this is fixed. Mostly because #32477 fixed #15686 . What leaves me uncertain is that #32477 specifically mentions "with duplicates"... but I guess the non-duplicated cases was already fixed. And unfortunately I don't have time to do much research now.

(It would be cool to have a broken index class to pass to ``Series`` and ``DataFrames`` for testing ``iloc``, which would always raise an error when actually used for indexing!)

**Comment by jbrockmendel** [comment]
> (It would be cool to have a broken index class to pass to Series and DataFrames for testing iloc, which would always raise an error when actually used for indexing!)

That might be a nice way to test somethings.  For now I think this is closeable.
