### ISSUE TITLE
API: add `inplace` kwarg to NDFrame.droplevel

### ISSUE THREAD

**Issue by vbarda** [pandas-dev/pandas#21990]
```python
df.droplevel(level, axis=0)
```

vs

```python
df.droplevel(level, axis=0, inplace=False)
```

#### Problem description

Currently `.droplevel` DataFrame / Series does not expose `inplace` kwarg, and it defaults to False under the hood, in `NDFrame.set_axis` method

cc @jreback @TomAugspurger

**Comment by gfyoung** [comment]
@vbarda : Go for it!

**Comment by TomAugspurger** [comment]
I think there's still a bit of discussion to be had on whether we *want* to
add an inplace argument in new places.

Personally, I'm not sure.

**Comment by lithomas1** [comment]
This can be done inplace with Copy-on-Write, so closing.
(you would do something like ```df = df.droplevel(...)```
