### ISSUE TITLE
CategoricalIndex reidex duplicates values 

### ISSUE THREAD

**Issue by fjdiod** [pandas-dev/pandas#21999]
#### Code Sample, a copy-pastable example if possible

```python
>>> idx = pd.CategoricalIndex(['low', 'low', 'hi', 'hi'])
>>> idx.reindex(idx)[0].values
[low, low, low, low, hi, hi, hi, hi]
Categories (2, object): [hi, low]
```
I'm not sure that it is unexpected behavior, but it seems to be one of the reasons for #21809

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: 0a0b2b9fc56eb0753b6d07a55d497b970c8ccfe0
python: 3.6.6.final.0
python-bits: 64
OS: Linux
OS-release: 4.13.0-46-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.0.dev0+333.g0a0b2b9fc
pytest: 3.6.2
pip: 10.0.1
setuptools: 39.2.0
Cython: 0.28.3
numpy: 1.14.5
scipy: 1.1.0
pyarrow: 0.9.0
xarray: 0.10.7
IPython: 6.4.0
sphinx: 1.7.5
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.5
feather: 0.4.0
matplotlib: 2.2.2
openpyxl: 2.5.4
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.5
lxml: 4.2.2
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.8
pymysql: 0.8.1
psycopg2: None
jinja2: 2.10
s3fs: 0.1.5
fastparquet: 0.1.5
pandas_gbq: None
pandas_datareader: None
gcsfs: 0.1.0

</details>

**Comment by TomAugspurger** [comment]
We'll just keep #21809 open, since I suspect that Categorical.reindex is the only thing causing the original issue. To close that we'll test the output of Categorical.reindex and the Series / frame constructors with a CategoricalIndex

**Comment by TomAugspurger** [comment]
to be clear, duplicating is certainly not the expected behavior.
