### ISSUE TITLE
BUG: pd.DataFrame.equals return False for same values if different numpy type

### ISSUE THREAD

**Issue by JacquotLeHaricot** [pandas-dev/pandas#22012]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np
df_int32 = pd.DataFrame([0, 1], dtype=np.int32)
df_int64 = pd.DataFrame([0, 1], dtype=np.int64)
df_int32.equals(df_int64)  # False
```
#### Problem description

The docstring of `pd.DataFrame.equals` explains : "Determines if two NDFrame objects contain the same elements". Or the result here is not consistent with `(df_int32 == df_int64).all()[0]` that tries to do precisely what the docstring is describing.
This issue exists on the master branch. It is experimented whenever the `dtype`s of the two dataframes are different, not just for `int`s.

#### Expected Output
`True`

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-130-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: fr_FR.UTF-8
LOCALE: fr_FR.UTF-8

pandas: 0.23.3
pytest: 3.6.3
pip: 10.0.1
setuptools: 39.2.0
Cython: 0.28.3
numpy: 1.14.5
scipy: 1.1.0
pyarrow: 0.9.0
xarray: 0.10.7
IPython: 6.4.0
sphinx: 1.7.5
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.5
feather: 0.4.0
matplotlib: 2.2.2
openpyxl: 2.5.4
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.5
lxml: 4.2.2
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.8
pymysql: 0.9.1
psycopg2: None
jinja2: 2.10
s3fs: 0.1.5
fastparquet: 0.1.5
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by JacquotLeHaricot** [comment]
This seems to be a low-effort issue, as the machinery is already in the standard `pd.DataFrame.__eq__`.
I did not looked deeply into it, but I guess the idea would be to downcast the data block when possible. If that is ok, I would like to try to do a PR for this issue as my first contribution.

**Comment by jreback** [comment]
this is not correct

different dtypes are by definition not equal - this is an exact match

**Comment by JacquotLeHaricot** [comment]
Ok then ; maybe there would be a need to clarify the docstring ?

**Comment by KenHBS** [comment]
> this is not correct
> 
> different dtypes are by definition not equal - this is an exact match

When running `(df_int32 == df_int64).all().all()` we also check whether the values are equal and this does return `True`, unlike `df_int32.equals(df_int64)`. Perhaps it is possible to add an option to `equals()` that casts the types, essentially like `df_int32.equals(df_int64.astype(df_int32.dtypes))`.

The documentation for [pd.DataFrame.equals()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.equals.html) does point out that the data types have to be the same for `.equals()` to return `True` and provides an example of comparing floats with integers. However, I think it is worth documenting that this also extends to less obviously different data types, such as `np.int64` and `np.int32`.
