### ISSUE TITLE
AttributeError: 'Series' object has no attribute 'columns'

### ISSUE THREAD

**Issue by jasonachonu** [pandas-dev/pandas#22029]
Hi,

System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
NO
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Hugh Sierra
TensorFlow installed from (source or binary): I did pip install tensor flow
TensorFlow version (use command below): v1.9.0-0-g25c197e023 1.9.0
Python version: 3.6
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
Exact command to reproduce:
Please find below the error am having.

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
updated
Performing function: predict
on outcome: continuous_static_outcome_occupancy
Predicting for date 2017-01-01 00:00:00
Traceback (most recent call last):
  File "./src/NeirbiLSTM-occupancy.py", line 52, in <module>
    predict.run()
  File "/Users/jasonachonu/git/SeqHub_Summer2018/src/nblib/predict.py", line 51, in run
    [rawdata, var_type,var_timing,var_use,key] = preprocess.preprocess(rawdata,checks=False)
  File "/Users/jasonachonu/git/SeqHub_Summer2018/src/nblib/preprocess.py", line 29, in preprocess
    meta_data = np.core.defchararray.split(np.asarray(rawdata.columns).astype(str),sep="_")
  File "/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 4372, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'columns'

**Comment by WillAyd** [comment]
Please refer to our contributing guide on how to open bug reports:

https://pandas.pydata.org/pandas-docs/stable/contributing.html#bug-reports-and-enhancement-requests

Unfortunately there is no information to work off of here so closing for now, but feel free to reopen after going through the above and providing the appropriate information. The `AttributeError` being raised makes sense, though there's not much context to what's going on - if you are running a sample script from TF's repository then maybe that sample script is wrong?
