### ISSUE TITLE
Pytest and python setup.py build_ext --inplace --force fails. 

### ISSUE THREAD

**Issue by raguiar2** [pandas-dev/pandas#22048]
#### Problem description

I've been trying to write some test cases I have for a PR, but when I run `pytest pandas`, I get the error 

 ```in /Users/raguiar2/Desktop/pandas-raguiar2/pandas/_libs/tslibs/conversion.so not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.```

When I run `python setup.py build_ext --inplace --force`, however, I get the error
```
pandas/_libs/interval.c:36:2: error: unterminated conditional directive
#ifndef Py_PYTHON_H
 ^
pandas/_libs/interval.c:38013:40: error: expected '}'
  __pyx_t_5numpy_int64_t __pyx_v_point;
                                       ^
pandas/_libs/interval.c:38011:175: note: to match this '{'
  ...*__pyx_pw_6pandas_5_libs_8interval_32Float32ClosedNeitherIntervalNode_13__pyx_fuse_2query(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
                                                                                                                                                                   ^
1 warning and 2 errors generated.
error: command 'gcc' failed with exit status 1
```
Why would the setup be failing? Is this an issue with GCC?

**Comment by jbrockmendel** [comment]
What happens if you run python setup.py clean before the build ext command?

Is the pytest command running the same python version as the python setup.py command?

**Comment by raguiar2** [comment]
That worked! For future reference, why did that work?

**Comment by jbrockmendel** [comment]
>  For future reference, why did that work?

Hard to say exactly, best guess is something was rebased or run with a version mismatch and that caused the .c/.so files to get into an invalid state.  `setup.py clean` removes the generated .c/.so files so that `build_ext` starts from scratch.
