### ISSUE TITLE
Pandas Series: unexpected error while doing difference (`_maybe_match_name`)

### ISSUE THREAD

**Issue by pietrotortella** [pandas-dev/pandas#22041]
pandas version is 0.22.0, numpy version is 1.14.0

While performing the following:

```python
a = pd.Series([1, 2, 3])
a.name = np.int64(123)

b = pd.Series([4, 5, 6])
b.name = (123, 789)

a - b
```
I obtain the following error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-63-e4efbf202d3c> in <module>()
----> 1 one - two

~/venv/lib/python3.4/site-packages/pandas/core/ops.py in wrapper(left, right, name, na_op)
    727 
    728         if isinstance(rvalues, ABCSeries):
--> 729             name = _maybe_match_name(left, rvalues)
    730             lvalues = getattr(lvalues, 'values', lvalues)
    731             rvalues = getattr(rvalues, 'values', rvalues)

~/venv/lib/python3.4/site-packages/pandas/core/common.py in _maybe_match_name(a, b)
    137     b_has = hasattr(b, 'name')
    138     if a_has and b_has:
--> 139         if a.name == b.name:
    140             return a.name
    141         else:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by WillAyd** [comment]
Thanks for the report - this appears on master as well. 

I think the solution could be as simple as wrapping that comparison in a try...except to catch the `ValueError` - PRs are always welcome if you are up for it!

@toobaz @jorisvandenbossche I think one of you was looking at maintaining Series names recently so FYI

**Comment by TomAugspurger** [comment]
Mmm, I'm not sure this is worth trying to support.

@pietrotortella does your series name need to be a NumPy scalar? Did this come about from a pandas operation?

**Comment by pietrotortella** [comment]
Yes, the problem was originated by one of the two Series being a row in a DataFrame with MultiIndex, while the name of the other Series is assigned automatially after loading it from csv, with the command

```
b = pd.read_csv(path, header=None, sep='|', index_col=0, squeeze=True)
```

**Comment by jorisvandenbossche** [comment]
I thought we had something like this some time ago, but can't directly find it.

In any case, both names (a tuple and a numpy scalar) are things you can quite easily get with only pandas operations, so I think it is worth fixing.

**Comment by toobaz** [comment]
I also think that pragmatically this is easier to fix than to document ;-)

If we do not already have an internal method which tests equality and is numpy array-robust, we probably want to create it.

**Comment by TomAugspurger** [comment]
> In any case, both names (a tuple and a numpy scalar) are things you can quite easily get with only pandas operations, so I think it is worth fixing.

I think tuple is fine, right? It's just when you have things that are hashable but don't have the "right" equality semantics?

I'd propose changing `Series.name.setter` to extract the `item` from a NumPy scalar.

**Comment by TomAugspurger** [comment]
Well, maybe that's a dumb idea... Having an Int64Index for the columns ensure that scalar elements will be NumPy scalars...

**Comment by WillAyd** [comment]
@pietrotortella  if you want to push a PR with your change and tests we can probably move the discussion over to that. We obviously have some discussion on the implementation but the tests regardless will be of value, and we are here to help with the former
