### ISSUE TITLE
where method results in a different outputs when using the inplace kwarg

### ISSUE THREAD

**Issue by finete** [pandas-dev/pandas#22051]
I am getting different results when using the where method with  `inplace=False` vs `inplace=True`.

consider the following `dataframe`:

```ptyhon 
df = pd.DataFrame({'a':[1,None,3]})
df
    a
0   1.0
1   Nan
2   3.0
```
when using the where method with `inplace=False` (the default), i get the following result:

```python
df.where(pd.notnull(df), None)
    a
0   1.0
1   None
2   3.0
```
with `a` being converted to be of type `object`.

however if i do this:
```python
df.where(pd.notnull(df), None, inplace=True)
df
    a
0   1.0
1   Nan
2   3.0
```
`a` is of type `float64`

pandas version: 0.23.3 , numpy version: 1.14.5

reported because of my [question](https://stackoverflow.com/questions/51515563/pandas-where-method-results-in-a-different-outputs-when-using-the-inplace-kwarg) on SO

**Comment by TomAugspurger** [comment]
I suppose the issue is that `None` cannot be stored in a float64 array, so if you want to place it then the array needs to be coerced to object.

It'd be helpful if someone could see how we values coercion with `inplace=True` in other places. I could see this raising if the `other` requires coercing `self` and `inplace=True`.

**Comment by MosheVai** [comment]
I think the issue is specifically with `None`, because doing this:

```python
df.where(pd.notnull(df), 'st', inplace=True)
```
does change `a` to be of type `object`.

**Comment by mroeschke** [comment]
I think we consistently coerce `None` to `NaN` here now with inplace True/False (which I think is the expected behavior). Could use a test
