### ISSUE TITLE
Feature Idea: Hoeffding's Dependency for DataFrames, similar to .corr(method='spearman')

### ISSUE THREAD

**Issue by Dicklesworthstone** [pandas-dev/pandas#22086]
You can see the definition of this measure of statistical dependency here:

**http://support.sas.com/documentation/cdl/en/procstat/67528/HTML/default/viewer.htm#procstat_corr_details07.htm**

And here is a parallel implementation for Matlab:

https://stackoverflow.com/a/9322657

There is another version for R here:

https://www.rdocumentation.org/packages/Hmisc/versions/4.1-1/topics/hoeffd

This would be very useful to be able to do with DataFrames, especially for things like near-duplicate detection where you are looking at the relationship between on image fingerprint vector, and you want to compare it to every fingerprint in a database.

**Comment by gfyoung** [comment]
This seems like an interesting proposal.  Only concern I have is bloating DataFrame core API / maintenance in the long run.

cc @jreback @jorisvandenbossche

**Comment by jreback** [comment]
this is a fairly obscure statistic and doesn’t much general usage 
more suited to statsmodels or othe packages that use pandas

closing as out of scope
