### ISSUE TITLE
TST: remove skip for pytables build issue on numpy 1.15

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#22098]

**Comment by TomAugspurger** [comment]
NumPy 1.15.1 is out, and should include this fix.

Updating https://github.com/pandas-dev/pandas/blob/68273a7a8b05049b311ea207f78e6d6f30c6eaf5/pandas/tests/io/test_pytables.py#L2194-L2197 to skip if and only if the NumPy version is exactly 1.15.0 will make for a good first contribution.

**Comment by NikhilKumarM** [comment]
@TomAugspurger Could you please let me know if I have to make any changes. Thanks!!
