### ISSUE TITLE
read_fwf with colspec fails to read correctly the value of the 2nd column

### ISSUE THREAD

**Issue by pytoccaz** [pandas-dev/pandas#22103]
#my data file

```sh
echo "AAZZZ" > test.dat
```
#my python program
```python
import pandas as pd

data=pd.read_fwf("test.dat", colspecs=[(0, 2), (2, 3)], names=["col1", "col2"])
```
#### Problem description

Always tested in VirtualEnv

Same Issue on Windows (Python2.7, Python3.6) and Ubuntu16.4 (Python2.7)

col1 is always good, in my exemple value is AA.
col2 value is "Z" . Should be "ZZZ"

Using widths instead of colspecs gives the expected result:
```python
 
In [6]: data=pd.read_fwf("test.dat", widths=[ 2 , 3], names=["col1", "col2"])

In [7]: data
Out[7]:
  col1 col2
0   AA  ZZZ

```

<details>

[ pd.show_versions() on Ubuntu Python2.7 ]
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-1061-aws
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.23.3
pytest: None
pip: 18.0
setuptools: 40.0.0
Cython: None
numpy: 1.15.0
scipy: None
pyarrow: None
xarray: None
IPython: 5.7.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by WillAyd** [comment]
This isn't a bug - the `colspecs` parameter accepts a list of tuples containing the `[from, to[` ranges (as noted in documentation). 

If you wanted "ZZZ" your signature should be as follows:

```python
data=pd.read_fwf("test.dat", colspecs=[(0, 2), (2, 5)], names=["col1", "col2"])
```

**Comment by pytoccaz** [comment]
shame on me...
