### ISSUE TITLE
[DEPR] remove `skipna` kwarg from `infer_dtype`?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#22112]
All non-test usages of `lib.infer_dtype` have `skipna=False` (or more specifically, they don't pass the kwarg).  If we get rid of that option, a nontrivial chunk of inference.pyx can be simplified.

**Comment by jreback** [comment]
no this was specifically added as backwards compat

**Comment by jbrockmendel** [comment]
Ahh OK.
