### ISSUE TITLE
BUG: _cython_table bug (part 2)

### ISSUE THREAD

**Issue by topper-123** [pandas-dev/pandas#22156]
#22110 was supposed to fix a bug introduced by #21224, where xdist fails because fixtures have random order because dicts too do have random order for Python < 3.6.

If appears that this is not fixed after all, as I got the xdist bug in #21699 too. The issue is that it is not even enough to sort by function name, as several function have the same name ( ``sum`` has the same name as ``np.sum`` and so on).

I can make a fix where ``conftest._cython_table`` is ordered manually for the short term, but longer term it seems to me the chosen approach is a bit too messy. I'm however going on vacation tomorrow, so won't be able to work on this for a time, but I could put in the short term fix tonight and fix it long term when I'm back.

**Comment by gfyoung** [comment]
Let's get the short term fix down, and we can evaluate.

(and enjoy your vacation!)

**Comment by topper-123** [comment]
This has been fixed in #22157.
