### ISSUE TITLE
COMPAT: warnings on scalar comparisons

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#22154]
https://travis-ci.org/pandas-dev/pandas/jobs/410445444

I think these are new in numpy 1.15

```
pandas/tests/extension/integer/test_integer.py::TestDtype::()::test_check_dtype[UInt64Dtype]
  /home/travis/build/pandas-dev/pandas/pandas/core/ops.py:1235: DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.
    result = libops.scalar_compare(x, y, op)
  /home/travis/build/pandas-dev/pandas/pandas/core/ops.py:1235: DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.
    result = libops.scalar_compare(x, y, op)
```

**Comment by SaturnFromTitan** [comment]
@jreback I think this issue can be closed. I can't spot this warning in the CI outputs anymore. Also, we're on `numpy` 1.17 already, so this shouldn't already be deprecated.

**Comment by jreback** [comment]
@SaturnFromTitan we have backward compatibility thru 1.13

are these on the 3.5 compact build?

**Comment by SaturnFromTitan** [comment]
> we have backward compatibility thru 1.13

Where/How can I see the backward compatibility specs? The `environment.yml` states `numpy>=1.15`

[Here's](https://github.com/pandas-dev/pandas/pull/29419/checks?check_run_id=289766537) the compat build of a very recent PR. I don't see any warnings there.

**Comment by jreback** [comment]
look at the ci/deps

**Comment by TomAugspurger** [comment]
I don't see these warnings on a recent build on travis or azure. I think all of these have been addressed.
