### ISSUE TITLE
Concat empty series with mixed TZ doesn't coerce to object

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#22186]
Do we intentionally special case concatenating an empty series with a non-empty series here? I don't think we should. It'd be nice to statically know the output dtype of a `concat` without having to look into the values.

```python
In [2]: import pandas as pd

In [3]: pd.concat([pd.Series([], dtype='datetime64[ns, US/Central]'), pd.Series(['2018'], dtype='datetime64[ns, US/Eastern]')])
Out[3]:
0   2018-01-01 00:00:00-05:00
dtype: datetime64[ns, US/Eastern]

In [4]: pd.concat([pd.Series([], dtype='datetime64[ns, US/Central]'), pd.Series([], dtype='datetime64[ns, US/Eastern]')])
Out[4]: Series([], dtype: object)
```

I'd expect both of those to be object dtype.

**Comment by TomAugspurger** [comment]
Taking this over as a general concat issue
 
Currently `concat[SparseSeries]` uses the `fill_value` of the first array.

```python
In [13]: pd.concat([
    ...:     pd.SparseSeries([0, 0, None], fill_value=0),
    ...:     pd.SparseSeries([0, None, 0], fill_value=np.nan)
    ...: ]).fill_value
Out[13]: 0

In [14]: pd.concat([
    ...:     pd.SparseSeries([0, 0, None], fill_value=np.nan),
    ...:     pd.SparseSeries([0, None, 0], fill_value=0)
    ...: ]).fill_value
Out[14]: nan
```

Are we comfortable calling that a bug? What's the expected behavior, raising?

**Comment by TomAugspurger** [comment]
I guess this raises a general design question: what dtype coercion are we comfortable with concat doing?

1. We're clearly OK with concatenating a mix of ints and floats and getting floats.
2. There's the open issue of concat[categorical] using union categorical
...

**Comment by TomAugspurger** [comment]
For `concat([sparse, dense])` I'd propose that the result always be sparse.

Currently, we try to keep it sparse. e.g. `concat([ Sparse[float64], float64 ])` is `Sparse[float64]`.
But `concat([ Sparse[float64], object] )` is object. IMO it should be `Sparse[object]`.

**Comment by jreback** [comment]
prob should density if sparse and dense and both float

**Comment by TomAugspurger** [comment]
> prob should density if sparse and dense and both float

Hmm I don't think so. I think ever implicitly going from sparse to dense is problematic. And on master we currently sparsify the dense series, but we're inconsistent about it:

- Sparse[float] & float -> Sparse[float]
- Sparse[float] & object -> object (dense)
