### ISSUE TITLE
valid parameters check while reading data

### ISSUE THREAD

**Issue by shantanuo** [pandas-dev/pandas#22189]
Pandas seems to ignore the extra (invalid) parameters. For e.g.
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
df=pd.read_excel('myfile.xlsx', some_dummy_param=True)
```
Note that some_dummy_param does not throw an error.

#### Problem description

Is there any way to make sure only valid parameters are passed to read_excel method?

#### Expected Output
Since there is no such parameter called "some_dummy_param", I should get an error:

> TypeError: __init__() got an unexpected keyword argument 'some_dummy_param'

**Comment by TomAugspurger** [comment]
I thought we had another issue for this (https://github.com/pandas-dev/pandas/issues/17994 was aobut `sheet_name` vs. `sheetname`).

**Comment by TomAugspurger** [comment]
The most difficult part is that kwds is passed through to the underlying engine. We would want to reconcile the common keyword arguments, and then perhaps provide an `engine_kwargs` parameter that's a dict of engine-specific kwargs.

**Comment by TomAugspurger** [comment]
Yes, that issue was specifically for sheetname.

I'm not sure why a decorator would be useful, could you explain?

**Comment by shantanuo** [comment]
I just saw a decorator called "deprecate_kwarg" to deprecate a keyword argument of a function. I thought similar concept can be used for "validate_kwarg". Ignore this comment if that is not the case.

**Comment by shantanuo** [comment]
May be this function 

```
def validate_kwarg():
    def _validate_kwarg(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            expected_keys=['io', 'sheet_name','header', 'names', 'index_col', 'usecols', 'squeeze', 'dtype', 'engine', 
               'converters', 'true_values',  'false_values', 'skiprows', 'nrows', 'na_values', 'verbose', 'parse_dates',
               'date_parser', 'thousands', 'comment', 'skipfooter', 'convert_float']

            if set(kwargs.keys()).difference(set(expected_keys)): 
                raise ValueError('invalid parameter found')

            return func(*args, **kwargs)
        return wrapper
    return _validate_kwarg

```
and a decorater added in the file pandas/io/excel.py

@validate_kwarg()
@Appender(_read_excel_doc)
@deprecate_kwarg("parse_cols", "usecols")
@deprecate_kwarg("skip_footer", "skipfooter")
def read_excel(io,

**Comment by TomAugspurger** [comment]
I don't think a decorator is necessary here, since this is only being
applied to a single function.

I think the best path forward is to remove the need for **kwargs in
read_excel.

**Comment by mroeschke** [comment]
`engine_kwargs` is getting added in 1.3 to read_excel which I think fits the spirit of this issue.

https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.3.0.html#other-api-changes

Closing, but happy to reopen if there is more to this issue
