### ISSUE TITLE
[Feature Request] Providing a cache option for `pd.read_sql()`

### ISSUE THREAD

**Issue by Ouwen** [pandas-dev/pandas#22208]
#### Providing a cache option for `pd.read_sql()`

Is there any work being done to allow a cache mechanism for pandas sql queries? I typically connect pandas to a sql database in a jupyter notebook. However, when I re-run cells it would be nice if these queries were cached in a file unless cache busting is explicit.

```python

query = "SELECT * FROM table WHERE %(test)s = 'test';"

df = pd.read_sql(query, db, params={
    'test': 'name'
}, cache=True)
```

I would imagine the behavior would that the query string, db engine connection string, and params are hashed and saved as a file in some directory.

**Comment by WillAyd** [comment]
This would add quite a bit of code complexity that I don't think is worth managing. What would be the advantage of this over simply persisting the data yourself?

**Comment by gfyoung** [comment]
@WillAyd : I agree with you on this.  Hesitant to include this in the codebase, but I would recommend this in the cookbook (`doc/source/cookbook.rst`).  That way others can see how you extended `pandas` to include this functionality.

@Ouwen : Would you like to add a section about that?

**Comment by Ouwen** [comment]
@gfyoung sounds good to me!

**Comment by jbrockmendel** [comment]
did this ever make it into the cookbook?  closeable?

**Comment by mroeschke** [comment]
Would agree that caching for `read_sql` would be out of scope, so since there's not much interest in this feature for a few years going to close. Happy to reopen if there is more interest

**Comment by kristiyan-dimitrov** [comment]
Just thought of this and landed on this issue. +1 that this would be a useful feature.

I would expect functionality similar to [requests-cache](https://pypi.org/project/requests-cache/).

Idea is:
1) I run pd.read_sql_table and get a df.
2) Result is saved to local sqlite db.
2) I rerun the cell/query and it executes much quicker, because it's just fetching the results from the sqlite instead of querying the remote db.

**Comment by carterjfulcher** [comment]
Just ran into this also, would be useful!

**Comment by harrylojames** [comment]
Agree would be great to see!
