### ISSUE TITLE
pd.io.sql.to_sql  can't find the existing table

### ISSUE THREAD

**Issue by yanzhaojun7** [pandas-dev/pandas#22210]
this is my code:
pd.io.sql.to_sql(df, "TMP_ACCOUNT", con, if_exists='append', index=False)
this is my error:
(teradata.api.DatabaseError) (3803, "[42S01] [Teradata][ODBC Teradata Driver][Teradata Database] Table 'TMP_ACCOUNT' already exists. ") 

My database is teradata   ,and table "TMP_ACCOUNT" is a VOLATILE MULTISET  TABLE。Before i use pd.io.sql.to_sql i have created the table "TMP_ACCOUNT".  Anyone can fix my issue???thanks.

**Comment by gfyoung** [comment]
There's an `if_exists` parameter in `to_sql`.  By default, it will raise an error if the table already exists.  However, you can change it so that it either replaces existing table or appends to it.

Let us know if this answers your question!  Will be happy to revisit if need be.

**Comment by gfyoung** [comment]
This sounds like a `sqlalchemy` issue to me.  Here's a way to check: can you try a connection to an in-memory DB (use `sqlite3` and a subset of your data) and see if your code works then?

**Comment by extrospective** [comment]
I am having a similar issue with to_sql against Microsoft Parallel Data Warehouse.  It seems likely a sqlalchemy issue and may have to do with metadata implementation for some flavors of SQL.  Interested if others learn more.
