### ISSUE TITLE
ExtensionArray.astype and missing values

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#22216]
How should ExtensionArray.astype handle coercing values to dtype?

Currently, we seem to follow NumPy:

```python
In [19]: np.array([1, 2, np.nan]).astype('i8')
Out[19]: array([                   1,                    2, -9223372036854775808])

In [20]: pd.Categorical([1, 2, None]).astype('i8')
Out[20]: array([                   1,                    2, -9223372036854775808])
``` 

Do we want that behavior? SparseArray currently raises.

Note that at least for Categorical, this will require scanning the data for missing values, which is rarely a good idea.

**Comment by xhochy** [comment]
We had a similar discussion in Arrow and we concluded that this should raise by default: https://issues.apache.org/jira/browse/ARROW-2806

**Comment by jorisvandenbossche** [comment]
The discussion there was even a bit more complex with the distinction of NaN and NA. 
But yes, I also agree that the above should raise an error (since the target dtype does not support missing values).

**Comment by jorisvandenbossche** [comment]
> Note that at least for Categorical, this will require scanning the data for missing values, which is rarely a good idea.

But unavoidable I think (for Categorical in principle checking for -1 in the codes), for Series we have a `hasnans` property that is cached.

**Comment by jreback** [comment]
this seems ok, anything to do here?

**Comment by TomAugspurger** [comment]
Agreed. Perhaps a doc note guiding how pandas wants out of bounds values
cast, but nothing blocking for 0.24.0

**Comment by jorisvandenbossche** [comment]
Based on the discussion above, I would think the to do action is to actually 'fix' it to raise an error instead of creating garbage? (but since it is pre-existing behaviour, probably not a blocker for 0.24)

IntegerArray already correctly raises, DatetimeArray does not (similar as Catetogorical)

**Comment by TomAugspurger** [comment]
Pushing to 0.25, as I think changing the behavior will require a deprecation.

**Comment by TomAugspurger** [comment]
Note that the specific Categorical issue has been fixed, so I think this can be closed.
