### ISSUE TITLE
Integer NA Doc Updates

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#22220]
With some of the work being done in #21160 do we want to update the documentation section on Integer NA support, or do we feel it is still too experimental at the moment?

http://pandas.pydata.org/pandas-docs/stable/gotchas.html#support-for-integer-na

**Comment by gfyoung** [comment]
Seems reasonable to do so.  You can always qualify the documentation by stating that the behavior is not 100% stable (i.e. still somewhat experimental) if need be.

**Comment by jorisvandenbossche** [comment]
Yes, +1 on mentioning it there.

**Comment by PSY27** [comment]
i am will to do it
