### ISSUE TITLE
Consistent API for suffixes in merge / join

### ISSUE THREAD

**Issue by ksyme99** [pandas-dev/pandas#22231]
The way to add suffixes is inconsistent between join and merge:

```python
df1.merge(df2, suffixes=('left', 'right')
df1.join(df2, lsuffix='left', rsuffix='right')

```

I always have to look this up as I get it wrong every time! I do not have a strong preference for which to use, perhaps slightly prefer the merge syntax.

Can the API be updated to be consistent, with backwards support but deprecated?

**Comment by WillAyd** [comment]
I'd be +1 on the join syntax and deprecating merge. Let's see what others think

**Comment by rhshadrach** [comment]
Duplicate of #46046; there is a bit more discussion there (though not by much). Closing.
