### ISSUE TITLE
Incorrect tzinfo check in tslibs.parsing

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#22234]
https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslibs/parsing.pyx#L339

```            
    if isinstance(tzdata, datetime.tzinfo):
                tzinfo = tzdata
```

If this were ever hit it would raise an error because `datetime.tzinfo` refers to the tzinfo attached to a datetime object, _not_ the tzinfo class defined in the datetime module.

There's basically no path by which this would be reached because we never pass a `tzdata` to this function.  So two things should happen: fix this to check for the correct object, and either remove unreachable code or make it reachable.

**Comment by mroeschke** [comment]
The same check (bug?) exists in dateutil:

https://github.com/dateutil/dateutil/blob/99f5770e7c63aa049b28abe465d7f1cc25b63fd2/dateutil/parser/_parser.py#L1161

Also it looks like `tzdata` is defined right above this check in the `if/else` above.

However if there are no conditions where we ever hit this branch, I would vote nix it.

**Comment by jbrockmendel** [comment]
> The same check (bug?) exists in dateutil:

`dateutil.parser._parser` has `import datetime`, whereas `tslibs.parsing` has `from cpython.datetime cimport datetime` (roughly equivalent to `from datetime import datetime`)

**Comment by mroeschke** [comment]
Ah good catch. Looks like a copy-paste bug then.

But I think this branch will never be hit:

So `dateutil_parse` where this code lies in only called in one place

https://github.com/pandas-dev/pandas/blob/737b3297e2d03492acbbe74eca5dfc2eb62cf207/pandas/_libs/tslibs/parsing.pyx#L159-L160

And a default kwarg `tzinfos` will therefore always be `None` and this branch where this code lies will always be False:

https://github.com/pandas-dev/pandas/blob/737b3297e2d03492acbbe74eca5dfc2eb62cf207/pandas/_libs/tslibs/parsing.pyx#L334

**Comment by gfyoung** [comment]
I would just remove the logic and see if any tests break.  That would help to confirm 🙂

**Comment by jbrockmendel** [comment]
> However if there are no conditions where we ever hit this branch, I would vote nix it.

We briefly discussed at the sprint the idea of correctly parsing some timezone strings where the correct answer is unambiguous (e.g. "CEST" should always be "Central European Summer Time").  If we go down that road, it will be by passing `tzinfos` as a dict.

**Comment by mroeschke** [comment]
I see. In that case, makes sense to keep it for now.

To pay it forward though we can at least fix the `datetime.tzinfo` check and add some comments why that block is not getting hit (and what it will be useful for in the future).
