### ISSUE TITLE
Add groupby(level=0) example to Documentation

### ISSUE THREAD

**Issue by chunponglai** [pandas-dev/pandas#22239]
The definition is from the documentation is level: int, level name, or sequence of such, default None
If the axis is a MultiIndex (hierarchical), group by a particular level or levels.

But I still don't understand, can anyone provide a sample to explain what (level =) actually does?

**Comment by WillAyd** [comment]
I think this is technically fine to keep open and re-purpose as a documentation update. However, to get a direct answer for your question you should post on a Q&A site like StackOverflow; this board is for issue and enhancement requests

**Comment by NikhilKumarM** [comment]
I will take this task.

**Comment by NikhilKumarM** [comment]
So this should be added to the Dataframe.groupby right?

**Comment by WillAyd** [comment]
I think the docstring is shared as it comes from `generic.py` - where are you seeing that it differs for Series vs DataFrame? Can you link to that?

**Comment by NikhilKumarM** [comment]
In this webpage https://pandas.pydata.org/pandas-docs/stable/groupby.html, in section **GroupBy with MultiIndex**, there is an example of Series.groupby with level and below that, in **Grouping DataFrame with Index Levels and Columns** section, there is a Dataframe example with using df.groupby([pd.Grouper(level=1), 'A']).sum().

Am I right or looking in the wrong place?

I thought the example with level should be added in this webpage -  https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.groupby.html

**Comment by WillAyd** [comment]
@NikhilKumarM ah thanks for pointing that out. I originally was thinking this could be added to the docstring, but I think where it is documented currently makes just as much if not more sense. 

As such I'm going to close this out - thanks again for your review!
