### ISSUE TITLE
Groupby mean precision different than numpy

### ISSUE THREAD

**Issue by bear24rw** [pandas-dev/pandas#22240]
```python
import numpy as np
import pandas as pd

N = int(1e5)

x = np.random.rand(N)
n = np.random.rand(N)

x[n>0.9] = np.nan

df = pd.DataFrame()
df['value'] = x
df['group'] = 'a'

print(x.dtype)
print(df['value'].dtype)

print("numpy mean                : %.20f" % np.mean(x))
print("numpy nanmean             : %.20f" % np.nanmean(x))
print("numpy isfinite            : %.20f" % np.mean(x[np.isfinite(x)]))
print("numpy masked              : %.20f" % np.ma.masked_where(np.isnan(x),x).mean())
print("pd mean                   : %.20f" % df.mean(axis= 0).values[0])
print("pd groupby agg np.nanmean : %.20f" % df.groupby('group').agg(np.nanmean)['value'].values[0])
print("pd groupby agg np.mean    : %.20f" % df.groupby('group').agg(np.mean)['value'].values[0])
print("pd groupby mean           : %.20f" % df.groupby('group').mean()['value'].values[0])
```

```
float64
float64
numpy mean                : nan
numpy nanmean             : 0.49971556524766752583
numpy isfinite            : 0.49971556524766752583
numpy masked              : 0.49971556524766752583
pd mean                   : 0.49971556524766752583
pd groupby agg np.nanmean : 0.49971556524766752583
pd groupby agg np.mean    : 0.49971556524766741481
pd groupby mean           : 0.49971556524766741481
```
#### Problem description

When computing the mean of a series via groupby the precision seems to change.

Passing np.mean as the agg function also does not give me the expected result of NaN.

Why does computing the mean of the dataframe return a different result than the mean of a group?

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Darwin
OS-release: 17.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: None
pip: 10.0.1
setuptools: 39.2.0
Cython: 0.28.4
numpy: 1.15.0
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.5
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: 2.6.6
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.4
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: 1.2.9
pymysql: None
psycopg2: 2.7.5 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by WillAyd** [comment]
This shouldn't have to do with any of the algorithms as much as the limitations of floating point precision. To illustrate, here's your code run on my computer; note the variance appears in other calculations:

```sh
numpy mean                : nan
numpy nanmean             : 0.50050915620060021372
numpy isfinite            : 0.50050915620060032474
numpy masked              : 0.50050915620060021372
pd mean                   : 0.50050915620060454359
pd groupby agg np.nanmean : 0.50050915620060021372
pd groupby agg np.mean    : 0.50050915620060454359
pd groupby mean           : 0.50050915620060454359
```

Accuracy of floats in less than 16 digits, which is confirmed by your example
