### ISSUE TITLE
PERF: Apply on Series much slower than DataFrame when the function is related with scipy.stats.norm

### ISSUE THREAD

**Issue by tian-yu-ic** [pandas-dev/pandas#22250]
#### Code Sample, a copy-pastable example if possible

```
%%timeit
pd.Series([1.0]*1000).apply(lambda x: x**2)
771 µs ± 15.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%%timeit
pd.DataFrame([1.0]*1000).apply(lambda x: x**2)
1.8 ms ± 15.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%%timeit
pd.Series([1.0]*1000).apply(norm.pdf)
146 ms ± 3.45 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

%%timeit
pd.DataFrame([1.0]*1000).apply(norm.pdf)
2.08 ms ± 27.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
#### Problem description

Normally my guess would be that Series should work better than DataFrame or at least the same, if the data is the same, like what I presented using x**2 (Point it out if I am wrong). However, when it comes to scipy.stats.norm, something strange happens.

#### Expected Output

Time cost is similar for Series and DataFrame

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Windows
OS-release: 2008ServerR2
machine: AMD64
processor: Intel64 Family 6 Model 45 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.4
pytest: 3.2.1
pip: 9.0.1
setuptools: 36.5.0.post20170921
Cython: 0.26.1
numpy: 1.13.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.1.0
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

​

</details>

**Comment by gfyoung** [comment]
That sounds really odd!  Investigation would be greatly appreciated here.

**Comment by jbrockmendel** [comment]
Can you try constructing the series and dataframe outside the timed loop?  I doubt that is the issue, but it’s be good to rule out.

**Comment by tian-yu-ic** [comment]
start = time.time()
pd.Series([1.0]*1000).apply(lambda x: x**2)
print(time.time()-start)
0.0009999275207519531

start = time.time()
pd.DataFrame([1.0]*1000).apply(lambda x: x**2)
print(time.time()-start)
0.002000093460083008

start = time.time()
pd.Series([1.0]*1000).apply(norm.pdf)
print(time.time()-start)
0.18501853942871094

start = time.time()
pd.DataFrame([1.0]*1000).apply(norm.pdf)
print(time.time()-start)
0.004000663757324219

Same issue here. It seems that the timed loop is not the problem.

**Comment by jbrockmendel** [comment]
I communicated poorly.  Meant to ask for:

```
In [3]: ser = pd.Series([1.0]*1000)

In [4]: df = pd.DataFrame([1.0]*1000)

In [5]: %timeit ser.apply(norm.pdf)
1 loop, best of 3: 320 ms per loop

In [6]: %timeit df.apply(norm.pdf)
100 loops, best of 3: 4.59 ms per loop
```

seems to match your results.

**Comment by chris-b1** [comment]
`DataFrames` by default applies to function to each _column_ at a time, while `Series` applies to the rows (e.g. individual scalar value). 

So this is as expected - to match performance in the Series case, apply the function to the entire array at once.
```
pd.Series(norm.pdf(s.values), s.index)
```
