### ISSUE TITLE
Rolling with win_type='triang' strange results

### ISSUE THREAD

**Issue by WangWenQiang** [pandas-dev/pandas#22268]
in my env(mac, python3.6.1,pandas0.23.4)

```python
In [26]: df = pd.DataFrame({'B': [0, 1, 2, np.nan, 4]})
In [27]: df
Out[27]:
B
0 0.0
1 1.0
2 2.0
3 NaN
4 4.0

In [28]: df.rolling(2, win_type='triang').sum()
Out[28]:
B
0 NaN
1 0.5
2 1.5
3 NaN
4 NaN

In [29]: df.rolling(2, win_type='triang').mean()
Out[29]:
B
0 NaN
1 0.5
2 1.5
3 NaN
4 NaN
```

but in the docs,

```python
df.rolling(2, win_type='triang').sum()
B
0 NaN
1 1.0
2 2.5
3 NaN
4 NaN
```

q1: docs.sum and myenv.sum is different
q2:sum()'result is the same as means()'result

**Comment by WillAyd** [comment]
I assume these are the docs the OP is referring to:

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.rolling.html

@WangWenQiang in the future please use syntax highlighting when posting code as it makes it easier to read (I've done it for you this time around)

**Comment by WillAyd** [comment]
Might be quite a few issues here. I don't think the docs are correct, but I also don't think that `triang` should be returning the same value for `mean` and `sum`. 

Investigation and PRs certainly welcome

**Comment by ihsansecer** [comment]
@WillAyd I guess it is normal to get same results for `sum` and `mean` while using `triang` with window size 2. From [this line](https://github.com/pandas-dev/pandas/blob/v0.24.2/pandas/_libs/window.pyx#L1721), it seems sum means `sum(weights * values)` for each window. Since weights are `[0.5, 0.5]` for `signal.windows.triang(2)`, they are equivalent and there is nothing wrong. I can fix the document if it is ok.

**Comment by pjadzinsky** [comment]
Hi,

Thanks for a great package. 

I think there are still some issues here and this example should be added to the docs (or something similar)

```
df = pd.DataFrame({'A': [0, 0, 1, 0, 0]})
   A
0  0
1  0
2  1
3  0
4  0

r = df.rolling(3, 1, win_type='triang').sum()
      A
0  0.00
1  0.00
2  0.25
3  0.50
4  0.25
```
1. If the maximum weight is 1 (as per the docs), shouldn't the output be ?
```
      A
0  0.00
1  0.00
2  0.5
3  0.1
4  0.5
```
2. For time series analysis, I was (incorrectly) assuming this was 'half' the triangular window. How would you do something like ewm but with a triangular window? I want to get something like
```
      A
0  0.00
1  0.00
2  1.00
3  0.66
4  0.33
```
where my weights are (1/3, 2/3, 1). Would that be possible?
3. Or can we specify our own windows?
