### ISSUE TITLE
int64 objects returned from pandas.read_sql_query on windows with sqlalchemy engine

### ISSUE THREAD

**Issue by jl0000285** [pandas-dev/pandas#22263]
# Example pseudo code

~~~python
>> import pandas 
>> sql = "some_sql_statement"
>> engine="some_sqlalchemy_engine"
>> df = pandas.read_sql_query(sql, engine)
>> df.dtypes #Result contains several numpy.int64 objects, even on windows machines 
~~~

On macs (and perhaps other unix systems), pandas.read_sql_query() tends to return numpy.int64, objects. In this context this return result is fine, as numpy.int64 objects sublcass pythons native int object on macs. This same method also returns numpy.int64 objects on windows, which do not sublcass pythons native int object and thus cause errors whenever used with any other library. 

Proposed solution: Is it not possible for pandas to detect the current operating system and adjust the data types of its resulting data frame natively?

**Comment by jl0000285** [comment]
Scope closure, will post in numpy's issue board

**Comment by gfyoung** [comment]
@jl0000285 : I'm confused here: when you say, "cause errors whenever used with any other library" - can you provide examples to illustrate your point?

Second, IIUC, `DataFrame` can't hold Python `int` as a numeric dtype.  It will always end up using a `numpy` dtype to hold such data.

**Comment by TomAugspurger** [comment]
I wonder if in https://github.com/pandas-dev/pandas/blob/475e391eaa0c85c4615ad6da5f81dee9b890635b/pandas/io/sql.py#L884-L886

that should be `np.dtype(int).type`?

**Comment by gfyoung** [comment]
@TomAugspurger : That will still return a `numpy` integer dtype, not a native Python one, which is what I *think* @jl0000285 is concerned about.

**Comment by TomAugspurger** [comment]
I'm not quite sure what @jl0000285 is after, but we should be consistent with, e.g. `pd.Series(np.arange(10))`. Is that an int64 or int32 on Windows and Python2?

**Comment by jl0000285** [comment]
@gfyoung: Two places I've seen failure on windows builds are in the building of json graphs in networkx (json_graph.tree(G,root) where G is composed of dataframes from said pandas dataframe) and in database operations using objects from said dataframe (such as sqlalchemy/engine/defaults various cursor.execute(statement,parameters) statements where parameters are objects taken from a pandas dataframe). When the result of some operation that returns a pandas dataframe contains numpy.int64 objects on windows machines, these operations fail, because numpy.int64 objects are not numbers on windows machines (these same instructions work fine on macs and probably other unix systems as well)

@TomAugsperger: The thing I was asking/hoping you guys could implement is automatically returning the proper numpy object dependant on which operating system a dataframe is being crafted on, that is to say if an operation is carried out on a windows machine, rather than returning dataframes with numpy.int64 objects in them, the dataframe would contain numpy.int32 objects (as these actually subclass int on windows machines and thus do not cause type errors when passed to another library). At the moment im handling the error by manual application of df.astype(numpy.int32, errors='ignore') when ever I need to use pandas on the windows version of what I am working on but feel like this should be something thats handled within pandas itself, thus the bug report.

**Comment by gfyoung** [comment]
@jl0000285 : Hmm...I see.  Would @TomAugspurger proposed patch [above](https://github.com/pandas-dev/pandas/issues/22263#issuecomment-411887422) work for you then?

**Comment by TomAugspurger** [comment]
@jl0000285 thoughts on 
https://github.com/pandas-dev/pandas/issues/22263#issuecomment-412160035?

Could you also edit your original post to include a full example that would be suitable for a unit test?

**Comment by mroeschke** [comment]
We're happy to reopen this issue when we can validate the issue with a reproducible example
