### ISSUE TITLE
Allow to specify column names other than 'level_*' in reset_index()

### ISSUE THREAD

**Issue by AKuederle** [pandas-dev/pandas#22260]
#### Code Sample, a copy-pastable example if possible

```python
# Instead of
new_df = old_df.reset_index()
new_df = new_df.rename({'level_0': 'my_name', 'level_1': 'my_other_name'})

# it should be possible to do
new_df = old_df.reset_index(index_cols = ['my_name', 'my_other_name'])

```
#### Problem description
I often find myself renaming columns after resting the index. I think this could be easily done in one step (see above).

If there is interest in that, I could try to implement it for `Series` and `DataFrame`

**Comment by WillAyd** [comment]
`reset_index` is just going to take whatever names you have for your MultiIndex levels. For example:

```python
In [12]: mi = pd.MultiIndex.from_tuples((('a', 1), ('b', 2)), names=['foo', 'bar'])
In [12]: df = pd.DataFrame(index=mi)   
In [12]: df.reset_index()  
Out[12]: 
  foo  bar
0   a    1
1   b    2
```

You would be much better served having those names in place prior to the reset.

**Comment by gfyoung** [comment]
I'm ambivalent about this.  It's not a super huge ask for this function, but whether it fits semantically into the scope of this function is unclear.

cc @jreback

**Comment by AKuederle** [comment]
I personally find it strange, that the function forces defaults name on you without allowing you to change them. I think if we find a proper name for the additional parameter, it would make a nice small improvement

**Comment by AKuederle** [comment]
No col_fill only allows to specify the names of the other levels, if your colums are a Multiindex. However, the actual name of the new index column is not influenced and is set to the default values, if the original index did not have names.

**Comment by WillAyd** [comment]
I am -1 on a new keyword. Names can easily be set before so I don't see this as adding a lot of value

**Comment by WillAyd** [comment]
Thanks for the suggestion! However based on all previous core dev responses I think we can close this one

**Comment by jorisvandenbossche** [comment]
I personally find this a regular annoyance with `reset_index` that you have to a rename afterwards. I have actually an old open issue about this: https://github.com/pandas-dev/pandas/issues/6878 (so this issue is also kind of a duplicate)
