### ISSUE TITLE
Add 'table' as Allowed `orient` Value in to_json Docs

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#22272]
Right now the allowed values for Series and DataFrame objects are missing `table` as an allowed value for the `orient` parameter in to_json

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_json.html

**Comment by ArmlessJohn404** [comment]
Is it? Am I missing something?

![screenshot from 2018-08-10 14-44-51](https://user-images.githubusercontent.com/14118472/43972841-1bef8fd2-9cac-11e8-868d-1cdefdc95f97.png)

**Comment by WillAyd** [comment]
Yep - look a little further up in your screenshot at the subsection for Series and DataFrame.

Very minor / nuanced but good to clean up for consistency

**Comment by NikhilKumarM** [comment]
@WillAyd I have added 'table' as allowed to the docs. Could you please review my PR and let me know if I have to make any changes.
