### ISSUE TITLE
BUG: SeriesGroupBy.hist ignores input arguments in python2

### ISSUE THREAD

**Issue by javadnoorb** [pandas-dev/pandas#22285]
#### Code Sample, a copy-pastable example if possible

```python
%matplotlib inline
import numpy as np
import pandas as pd

N = 100
np.random.seed(0)
df = pd.DataFrame(np.append(np.random.randn(N), np.random.randn(N) / 10),
               columns=['rand'])
df['group'] = [0] * N + [1] * N
df.groupby('group')['rand'].hist(color='black')
```
#### Problem description

In Python2 the inputs to `GroupBy.hist` are ignored unless they are named arguments in:
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.hist.html
 
In python2 I get:
![image](https://user-images.githubusercontent.com/26352146/43995452-d8ab6266-9d7b-11e8-92ad-bd801eb52bd7.png)

In python3 I get:
![image](https://user-images.githubusercontent.com/26352146/43995486-585e77b4-9d7c-11e8-923a-b026203d9edd.png)

** There are other issues with `DataFrameGroupBy.hist` (#22241) as it shares code with series plots. Is there any reason that it is not consolidated with `DataFrameGroupBy.plot.hist`?

#### Expected Output
similar to python 3
#### Output of ``pd.show_versions()``

For py2:
<details>

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.15.final.0
python-bits: 64
OS: Darwin
OS-release: 13.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.24.0.dev0+428.gf488e88.dirty
pytest: 3.7.1
pip: 18.0
setuptools: 40.0.0
Cython: 0.28.5
numpy: 1.15.0
scipy: None
pyarrow: None
xarray: None
IPython: 5.8.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

For py3:
<details>
No module named 'dask'

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Darwin
OS-release: 13.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.0.dev0+428.gf488e88.dirty
pytest: 3.6.2
pip: 18.0
setuptools: 39.2.0
Cython: 0.28.3
numpy: 1.14.5
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.5
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.4
xlrd: 1.1.0
xlwt: 1.2.0
xlsxwriter: 1.0.5
lxml: 4.2.2
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.8
pymysql: 0.8.1
psycopg2: None
jinja2: 2.10
s3fs: 0.1.5
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: 0.1.0
</details>

**Comment by gfyoung** [comment]
cc @TomAugspurger

**Comment by TomAugspurger** [comment]
Not sure why that would be.

**Comment by javadnoorb** [comment]
I don't know what's going on. But looks like in py2 `kwargs` is not passed to the function wrapper:
https://github.com/pandas-dev/pandas/blob/d09db1fe8dc3bc08c5ca0eff97d43d2b30d5233e/pandas/core/groupby/groupby.py#L577

It's empty if you put a print statement inside:

```diff
diff --git a/pandas/core/groupby/groupby.py b/pandas/core/groupby/groupby.py
index 3f84fa0..ee53fe0 100644
--- a/pandas/core/groupby/groupby.py
+++ b/pandas/core/groupby/groupby.py
@@ -575,6 +575,7 @@ b  2""")
         f = getattr(type(self._selected_obj), name)
 
         def wrapper(*args, **kwargs):
+            print(kwargs)
             # a little trickery for aggregation functions that need an axis
             # argument
             kwargs_with_axis = kwargs.copy()
diff --git a/pandas/core/series.py b/pandas/core/series.py
index b841798..9728a63 100644
--- a/pandas/core/series.py
+++ b/pandas/core/series.py
@@ -4008,7 +4008,9 @@ class Series(base.IndexOpsMixin, generic.NDFrame):
 
     # ----------------------------------------------------------------------
     # Add plotting methods to Series
-    hist = gfx.hist_series
+    # hist = gfx.hist_series
+    def hist(self, **kwargs):
+        return kwargs
 
 
 Series._setup_axes(['index'], info_axis=0, stat_axis=0, aliases={'rows': 0},
```

**Comment by WillAyd** [comment]
Strange indeed. My guess is that in Py2 the unbound method is picking up default keyword arguments from the `hist_series` signature whereas Py3 would be picking up the `color` kwarg from the instance. Not sure what the resolution is but sharing in case it leads to any insights for others

**Comment by WillAyd** [comment]
We no longer support Python2 so closing this one
