### ISSUE TITLE
pd.read_csv  return wrong number of lines

### ISSUE THREAD

**Issue by ATPs** [pandas-dev/pandas#22281]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd
df_name = pd.read_csv(r"D:\linux\W\NCBI\taxonamy\names.dmp",sep = "\t", header=None)
print(df_name.shape)

```
#### Problem description
We can download a file of the taxonomy from NCBI (https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz). After extract the file, there is one file named "names.dmp". It is a file with 2704156 lines. When read it with pandas.read_csv with the code
```
df_name = pd.read_csv(r"D:\linux\W\NCBI\taxonamy\names.dmp",sep = "\t", header=None)
print(df_name.shape)
```
the print out is '(2704128, 8)'.
When read it with the code
```
df_name = pd.read_csv(r"D:\linux\W\NCBI\taxonamy\names.dmp",sep = "\t", header=None,engine ="python")
print(df_name.shape)
```
we got error message.  
```

  File "C:\P\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 2685, in _alert_malformed
    raise ParserError(msg)

ParserError: '	' expected after '"'
```
With the code
```
df_name = pd.read_csv(r"D:\linux\W\NCBI\taxonamy\names.dmp",sep = "\t|\t", header=None)
print(df_name.shape)
```
I got
```
__main__:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
(2704156, 8)
```
With the code 
```
df_name = pd.read_csv(r"D:\linux\W\NCBI\taxonamy\names.dmp",sep = "\t\|\t", header=None)
print(df_name.shape)
```
I got
```
__main__:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
(2704156, 4)
```

why some lines were missing in the first method?

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: None.None

pandas: 0.22.0
pytest: 3.3.2
pip: 9.0.1
setuptools: 38.4.0
Cython: 0.27.3
numpy: 1.14.0
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.6.6
patsy: 0.5.0
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.1.2
openpyxl: 2.4.10
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.1
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

and

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-862.6.3.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: zh_CN.UTF-8
LOCALE: zh_CN.UTF-8

pandas: 0.23.0
pytest: 3.5.1
pip: 10.0.1
setuptools: 39.1.0
Cython: 0.28.2
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by WillAyd** [comment]
Your line count is wrong (should be 2,704,355) as is your separator. If you use the correct separator the shape of the frame will match the number of lines in the file

**Comment by ATPs** [comment]
Thank you for the answer, but I didn't get it. 

What's the difference between separator "\t" and "\t|\t"? Based on my understanding, they are the same. 

As for the line count, I opened the file, and checked the line numbers in notepad++. 
"\t" can be used as a separator surely, but why some lines will be missing?
