### ISSUE TITLE
BLD: wheels for 3.6 failing

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#22309]
https://travis-ci.org/MacPython/pandas-wheels/jobs/415273186

looks like a test that is in a loop

**Comment by jreback** [comment]
cc @jbrockmendel

**Comment by jorisvandenbossche** [comment]
I restarted the build and now it is passing (I didn't see any error in the original log, it only timed out before completing all tests)

**Comment by jreback** [comment]
thanks

yeah i have done that a couple of times
ok then
