### ISSUE TITLE
DataFrame.corrwith doesn't warn user about potentially bad alignment

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#22300]
#### Code Sample

```python
import numpy as np
import pandas as pd

np.random.seed(2357)

df = pd.DataFrame(np.random.normal(size=(100, 3)))
s = pd.Series(np.random.randn(50))

df.corrwith(s)
```
#### Problem description

It might be desirable to have `corrwith` return a warning in situations like the above where the alignment of the two data sets is suspect (the two objects only happen to have an overlapping index).  Perhaps the warning should be triggered unless the two objects have the right shape *and* the indexes are equal?

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Darwin
OS-release: 17.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.0
pytest: 3.5.1
pip: 18.0
setuptools: 39.1.0
Cython: 0.28.2
numpy: 1.14.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.2.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by gfyoung** [comment]
By itself, it sounds like a viable suggestion, but whether that's consistent with what we do currently in situations like this one, I'm not entirely sure.

cc @jreback
