### ISSUE TITLE
pd.Timestamp(timestamp) looses freq

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#22311]
#### Code Sample, a copy-pastable example if possible

```python
In [2]: print(pd.Timestamp(pd.Timestamp('2010-08-08', freq='D')).freq)
None
```

#### Problem description

I expect a timestamp initialized from a timestamp to keep its properties. And indeeed:
```
In [3]: print(pd.Timestamp(pd.Timestamp('2010-08-08', tz='utc')).tz)
UTC
```

#### Expected Output
``'D'``

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: 9123f7d0be4d6cff6cd7455b039f556c4acd2275
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-6-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.24.0.dev0+457.g9123f7d0b
pytest: 3.5.0
pip: 9.0.1
setuptools: 39.2.0
Cython: 0.28.4
numpy: 1.14.3
scipy: 0.19.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.5.6
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.0dev
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.2.2.post1634.dev0+ge8120cf6d
openpyxl: 2.3.0
xlrd: 1.0.0
xlwt: 1.3.0
xlsxwriter: 0.9.6
lxml: 4.1.1
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.2.1
gcsfs: None

</details>

**Comment by alimcmaster1** [comment]
I  can potentially have a look at this @toobaz , unless you have already started?

**Comment by toobaz** [comment]
> I can potentially have a look at this @toobaz , unless you have already started?

Feel free, I didn't start, and don't plan to do so soon.
