### ISSUE TITLE
"closed" is reset to 'right' when interval is multiplied by scalar

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#22313]
#### Code Sample, a copy-pastable example if possible

```python
In [2]: pd.Interval(0, 2, closed='left') * 2
Out[2]: Interval(0, 4, closed='right')
```

#### Problem description

I see no reason why multiplying an ``Interval`` by a scalar should change its "direction".

#### Expected Output

```
Out[2]: Interval(0, 4, closed='left')
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: 9123f7d0be4d6cff6cd7455b039f556c4acd2275
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-6-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.24.0.dev0+457.g9123f7d0b.dirty
pytest: 3.5.0
pip: 9.0.1
setuptools: 39.2.0
Cython: 0.28.4
numpy: 1.14.3
scipy: 0.19.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.5.6
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.0dev
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.2.2.post1634.dev0+ge8120cf6d
openpyxl: 2.3.0
xlrd: 1.0.0
xlwt: 1.3.0
xlsxwriter: 0.9.6
lxml: 4.1.1
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.2.1
gcsfs: None

</details>

**Comment by jschendel** [comment]
Thanks, it looks like this happens for all arithmetic operations:

```python
In [2]: iv = pd.Interval(-1, 2, closed='both')

In [3]: iv + 2
Out[3]: Interval(1, 4, closed='right')

In [4]: iv - 2
Out[4]: Interval(-3, 0, closed='right')

In [5]: iv * 2
Out[5]: Interval(-2, 4, closed='right')

In [6]: iv / 2
Out[6]: Interval(-0.5, 1.0, closed='right')

In [7]: iv // 2
Out[7]: Interval(-1, 1, closed='right')
```
