### ISSUE TITLE
Pandas in QGIS - MAC

### ISSUE THREAD

**Issue by philippos86** [pandas-dev/pandas#22340]
I'm on MAC, and I want to import pandas into my QGIS V2.18.

I have tried following the steps of this answer [here](https://stackoverflow.com/questions/31532501/how-to-install-pandas-library-in-qgis-python/31533128#31533128)

Uninstalled and reinstalled pandas using pip, and confirm its added to the PATH, still not working.

How can I add pandas to my QGIS?

**Comment by TomAugspurger** [comment]
You'll need to post more info. What's the output of `pip install pandas`? what version of pip?

Since pandas uses standard distribution methods like conda and pip, it's probably something to do with the QGIS environment, which I'm not familiar with. You might try asking on their mailing list.

**Comment by philippos86** [comment]
Here's the output you asked about.

`pip -V
pip 18.0 from /Users/user/anaconda/lib/python2.7/site-packages/pip (python 2.7)
Users-MacBook-Air:QGIS user$ pip install pandas
Requirement already satisfied: pandas in /Users/user/anaconda/lib/python2.7/site-packages (0.23.4)
Requirement already satisfied: python-dateutil>=2.5.0 in /Users/user/anaconda/lib/python2.7/site-packages (from pandas) (2.6.0)
Requirement already satisfied: numpy>=1.9.0 in /Users/user/anaconda/lib/python2.7/site-packages (from pandas) (1.12.1)
Requirement already satisfied: pytz>=2011k in /Users/user/anaconda/lib/python2.7/site-packages (from pandas) (2017.2)
Requirement already satisfied: six>=1.5 in /Users/user/anaconda/lib/python2.7/site-packages (from python-dateutil>=2.5.0->pandas) (1.10.0)`

and I will check for QGIS environment soon ..

**Comment by TomAugspurger** [comment]
If you're in an anaconda env, you should use conda to install packages.

   pip uninstall -y pandas

maybe a few times to make sure.

Then conda install pandas.

**Comment by philippos86** [comment]
@TomAugspurger I am on Anaconda environment, and tried uninstalling pandas and reinstalling it through conda, but still getting the same problem.

**Comment by jorisvandenbossche** [comment]
I think the question is: what python installation is QGIS using? I think it is quite likely that is it not the Anaconda version (so you are installing pandas in a different python installation than the one QGIS is importing). But that is rather a question for a QGIS forum.

**Comment by TomAugspurger** [comment]
Indeed. If you find something out, then please post here in case others run into the same issue.

**Comment by philippos86** [comment]
I have contacted the QGIS community on this thread: 
http://osgeo-org.1560.x6.nabble.com/Pandas-in-QGIS-MAC-td5374454.html

and as @jorisvandenbossche said, my python of QGIS is the original MAC one, while pandas is installed on anaconda. 
However, I added the anaconda path to the original one in QGIS, and now I'm getting this error: 

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/hamouiphilip/anaconda/lib/python2.7/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/hamouiphilip/anaconda/lib/python2.7/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/hamouiphilip/anaconda/lib/python2.7/site-packages/pandas/core/groupby/__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/hamouiphilip/anaconda/lib/python2.7/site-packages/pandas/core/groupby/groupby.py", line 16, in <module>
    from pandas import compat
ImportError: cannot import name compat
```
Is this relevant to here or shall I keep following with QGIS forum?
