### ISSUE TITLE
TypeError: 'Series' objects are mutable, thus they cannot be hashed

### ISSUE THREAD

**Issue by Lefatse** [pandas-dev/pandas#22351]
def get_predict(user_id, title):
    return svd.predict(user_id, id_map.loc[title, 'movieId']).est

def watched (user_id, title):
    user_table = get_user_table(user_id)
    if len(user_table[user_table['title'] == title])>0:
        return 'Yes'
    else:
        return 'No'

def just_watch_it(user, rating_min):
    should_watch = pd.DataFrame([], columns=['title', 'predicted rating'])
    for i in range(len(id_map)):
        if watched (user, id_map.iloc[i].name) == 'No':
            predicted_rating = get_predict(user, id_map.iloc[i].name)
            if predicted_rating >= rating_min:
                should_watch.loc[len(should_watch.index)] = {'title':id_map.iloc[i].name, 
                                                            'predicted rating': predicted_rating}
    
    return should_watch

list_of_movies = just_watch_it(8, 4)

```
#### Problem description
The code snippet above was written in jupyter notebook. All the functions seem to be fine, but I get an TypeError when I run the last line of code : "list_of_movies = just_watch_it(8, 4)". The data is fetched from csv files. 


####This is the error I got
TypeError                                 Traceback (most recent call last)
<ipython-input-26-10f2f7e6568f> in <module>()
----> 1 list_of_movies = just_watch_it(8, 4)

<ipython-input-25-15ecb3df6b29> in just_watch_it(user, rating_min)
      3     for i in range(len(id_map)):
      4         if watched (user, id_map.iloc[i].name) == 'No':
----> 5             predicted_rating = get_predict(user, id_map.iloc[i].name)
      6             if predicted_rating >= rating_min:
      7                 should_watch.loc[len(should_watch.index)] = {'title':id_map.iloc[i].name, 

<ipython-input-17-7d30a8ba596e> in get_predict(user_id, title)
      1 def get_predict(user_id, title):
----> 2     return svd.predict(user_id, id_map.loc[title, 'movieId']).est

C:\ProgramData\Anaconda2\lib\site-packages\surprise\prediction_algorithms\algo_base.pyc in predict(self, uid, iid, r_ui, clip, verbose)
    138             iuid = 'UKN__' + str(uid)
    139         try:
--> 140             iiid = self.trainset.to_inner_iid(iid)
    141         except ValueError:
    142             iiid = 'UKN__' + str(iid)

C:\ProgramData\Anaconda2\lib\site-packages\surprise\trainset.pyc in to_inner_iid(self, riid)
    149 
    150         try:
--> 151             return self._raw2inner_id_items[riid]
    152         except KeyError:
    153             raise ValueError('Item ' + str(riid) +

C:\ProgramData\Anaconda2\lib\site-packages\pandas\core\generic.py in __hash__(self)
   1487     # ----------------------------------------------------------------------
   1488     # Iteration
-> 1489 
   1490     def __hash__(self):
   1491         raise TypeError('{0!r} objects are mutable, thus they cannot be'

TypeError: 'Series' objects are mutable, thus they cannot be hashed

**Comment by alimcmaster1** [comment]
Hi, going forwards do you mind giving as little code as possible to reproduce the problem. There is alot of detail above which is related to your use case ( movies watched )

See [Stackoverflow](https://stackoverflow.com/questions/29700552/series-objects-are-mutable-and-cannot-be-hashed-error) for a decent answer to this question

Thanks!

**Comment by WillAyd** [comment]
Please refer to the contributing guide for how to open a bug report:

https://pandas.pydata.org/pandas-docs/stable/contributing.html#bug-reports-and-enhancement-requests

As mentioned above there is a lot missing here. Perhaps the SO article solves your problem but if not refer to the link above and feel free to re-open with required info

**Comment by Lefatse** [comment]
#This is the the entire code snippet 
import pandas as pd
import numpy as np
from surprise import Reader, Dataset, SVD, evaluate
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
import warnings; warnings.simplefilter('ignore')

reader = Reader()

ratings = pd.read_csv('ratings.csv')
ratings.head()

data = Dataset.load_from_df(ratings[['userId', 'movieId', 'rating']], reader)
data.split(n_folds=5)

svd = SVD()
evaluate(svd, data, measures=['RMSE', 'MAE'])

from surprise.model_selection import cross_validate

cross_validate(svd, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

trainset = data.build_full_trainset()
svd.train(trainset)

links_small = pd.read_csv('links_small.csv')


def convert_int(x):
    try:
        return int(x)
    except:
        return np.nan

id_map = links_small[['movieId', 'tmdbId']]
id_map['tmdbId'] = id_map['tmdbId'].apply(convert_int)
id_map.columns = ['movieId', 'id']

md = pd. read_csv('movies_metadata.csv')
md.drop([19730, 29503, 35587], inplace=True)
md['id'] = md['id'].astype('int')

links_small = pd.read_csv('links_small.csv')

links_small = links_small[links_small['tmdbId'].notnull()]['tmdbId'].astype('int')
smd = md[md['id'].isin(links_small)]

id_map = id_map.merge(smd[['title', 'id']], on='id').set_index('title')

def get_user_table(num):
    def title(id_movie):
        return id_map[id_map['movieId'] == id_movie].index[0]
    
    user_tbl = ratings[ratings['userId'] == num][['userId', 'movieId', 'rating']]
    user_tbl['title'] = user_tbl.movieId.apply(title)

    return user_tbl

get_user_table(8).head()

def get_predict(user_id, title):
    return svd.predict(user_id, id_map.loc[title, 'movieId']).est

def watched (user_id, title):
    user_table = get_user_table(user_id)
    if len(user_table[user_table['title'] == title])>0:
        return 'Yes'
    else:
        return 'No'


def just_watch_it(user, rating_min):
    should_watch = pd.DataFrame([], columns=['title', 'predicted rating'])
    for i in range(len(id_map)):
        if watched (user, id_map.iloc[i].name) == 'No':
            predicted_rating = get_predict(user, id_map.iloc[i].name)
            if predicted_rating >= rating_min:
                should_watch.loc[len(should_watch.index)] = {'title':id_map.iloc[i].name, 
                                                            'predicted rating': predicted_rating}
    
    return should_watch

list_of_movies = just_watch_it(8, 4) #The error occurs when I execute this line
