### ISSUE TITLE
CLN: Simplify Block._astype

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#22369]
There's lots of nested logic there (plus 1 more level from https://github.com/pandas-dev/pandas/pull/22343). Would be good to simplify this.

The components:

1. argument validation (could maybe do this elsewhere, not a big deal)
2. astyping *to* categorical is special cased. We'll want to remove that in favor of a generic astype system
3. Determine target_dtype -> Block type
4. `_astype` currently takes a `values` argument, which complicates things. Why is that? Why isn't it just `self.values` always?

**Comment by jorisvandenbossche** [comment]
Personally, I think we rather need to rethink the full astype-mechanism/dispatching first (what we were discussing in the PR https://github.com/pandas-dev/pandas/pull/22343)

**Comment by jbrockmendel** [comment]
> _astype currently takes a values argument, which complicates things. Why is that? Why isn't it just self.values always?

It is always None.  It can't be removed until we get `**kwargs` out of `NDFrame.astype` https://github.com/pandas-dev/pandas/commit/221b493e6fc4fed9ef4a51eaea341f9d9c936de5#r34292758

**Comment by jbrockmendel** [comment]
I think this has been simplified as much as it can be (until deprecations are enforced in 2.0).  Closing.
