### ISSUE TITLE
Suggestion: implement Q-Q plots

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#22393]
I see that there was some discussion of this years ago (PR #1501), but was wondering if there are any plans of implementing these in the future.

One thought would be to have `qqplot` be a `Series` method which optionally takes another `Series` as an argument.  If this argument is missing then `qqplot` could fall back on the quantiles from some theoretical distribution (default Gaussian, say), perhaps imported from `statsmodels`.  Even without `statsmodels` integration a purely empirical method could be quite useful for providing a very fast way of comparing two distributions.

**Comment by gfyoung** [comment]
@dsaxton : Thanks for reporting this!  Do you mind referencing the original issue where you saw the original discussion?

cc @TomAugspurger

**Comment by TomAugspurger** [comment]
Since statsmodels already has Q-Q plots, I think further development should
happen there.

**Comment by dsaxton** [comment]
That seems fair, closing the PR.
