### ISSUE TITLE
df-df.mean(axis=1) gives Memory Error

### ISSUE THREAD

**Issue by toniatop** [pandas-dev/pandas#22407]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np
df=pd.DataFrame(np.random.rand(150000,2))
s=df-df.mean(axis=1)
MemoryError:
```
#### Problem description

The snippet above fails in a Linux machine with 32gb of memory. Unless I am missing something, there shouldn't be nothing exceptional in the code above.  The transposed equivalent works just fine:

`s=(df.T-df.T.mean()).T`

#### Expected Output
The result, not a Memory Error.

#### Output of ``pd.show_versions()``
Tested in both python 2.7 and 3.7 with latest pandas.
<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Linux
OS-release: 4.13.0-45-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_AU.UTF-8
LOCALE: en_AU.UTF-8

pandas: 0.23.4
pytest: None
pip: 10.0.1
setuptools: 39.2.0
Cython: None
numpy: 1.14.5
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: 1.2.8
pymysql: None
psycopg2: 2.7.5 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by jorisvandenbossche** [comment]
By default, pandas aligns the right series on the columns (axis 1) of the left dataframe. 
So if you try to do `shape(150000, 2) - shape(150000,)`, you get `shape(150000, 150000)`, hence the memory error.

If you want to specify the alignment, you can use the equivalent methods (instead of operator):

```
In [20]: df.sub(df.mean(axis=1), axis=0)
Out[20]: 
               0         1
0       0.020379 -0.020379
1       0.103582 -0.103582
2      -0.035321  0.035321
3       0.164272 -0.164272
...
```

**Comment by toniatop** [comment]
Forgot I could look for the `sub` method. Alright, make sense. Thanks for the explanation!
