### ISSUE TITLE
Documentation Error - pandas2ri causes ModuleNotFoundError

### ISSUE THREAD

**Issue by webartifex** [pandas-dev/pandas#22412]
#### Code Sample, a copy-pastable example if possible

Compare
https://pandas.pydata.org/pandas-docs/version/0.23.3/r_interface.html
with
https://pandas.pydata.org/pandas-docs/version/0.23.4/r_interface.html

```python
from rpy2.robjects import pandas2ri
...
```
#### Problem description

The import generates a ModuleNotFoundError

**Comment by WillAyd** [comment]
Not a pandas issue as rpy2 is a separate project, though the error points to that not even being installed

**Comment by WillAyd** [comment]
Sorry misread your issue - I see you are referring to the pandas docs and not an attempt to do this locally.

**Comment by webartifex** [comment]
I believe there is still a bug, but most likely it is in the rpy2 package.

When I install rpy2 version 2.8.* this ModuleNotFoundError does NOT occur.

However, with the latest 2.9.* release it does occur.

Explicitly pip installing the tzlocal package seems to fix it.

I conclude that tzlocal is not installed together with rpy2.

Maybe someone wants to confirm this behavior?

**Comment by jorisvandenbossche** [comment]
There is already an issue at rpy2: https://bitbucket.org/rpy2/rpy2/issues/458/tzlocal-dependency

Apparently, `tzlocal` is an *optional* dependency of rpy2 (just as pandas is as well), so the user (i.e. we, for the docs) is responsible to make sure to install it.

**Comment by TomAugspurger** [comment]
The docs are built with a this environment: https://github.com/pandas-dev/pandas/blob/master/ci/travis-36-doc.yaml

@webartifex can you make a PR adding tzlocal to that environment?
