### ISSUE TITLE
AttributeError: type object pandas._TSObject has no attribute __reduce_cython__

### ISSUE THREAD

**Issue by isanmu** [pandas-dev/pandas#22426]
#### Problem description

**First**
With pandas(0.23.4) imported, I use pyinstaller 3.3.1 to package my program, when open the .exe program, it reminded me error message as bellow and self-closing then.
`"   File "pandas\_libs\tslibs\conversion.pyx", line 222, in  init pandas._libs.tslibs.conversion
AttributeError: type object pandas._TSObject has no attribute __reduce_cython__"`

**Second**
When i changed the pandas(0.23.4) to pandas(0.20.3), the issue can be **solved**, but i prefer to the new features of pandas's new version, so how can i solve this issue with pandas(0.23.4)?  Waiting for your reply, thanks!

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 32
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.23.4
pytest: None
pip: 18.0
setuptools: 28.8.0
Cython: 0.28.5
numpy: 1.15.0
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
How'd you install pandas? Do you have a log of the pip or conda install?

> when open the .exe program

What program? Pandas or your own?

**Comment by isanmu** [comment]
@TomAugspurger 
Thanks for  your reply!

**1. I install pandas by Pycharm(Project Interpreter)**

- Here gives the pip information(have been installed by Pycharm).
`pip install pandas`
```
Requirement already satisfied: pandas in c:\users\win\pycharmprojects\test\venv32\lib\site-packages (0.23.4)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\win\pycharmprojects\test\venv32\lib\site-packages (from pandas) (2.7.3)
Requirement already satisfied: pytz>=2011k in c:\users\win\pycharmprojects\test\venv32\lib\site-packages (from pand
as) (2018.4)
Requirement already satisfied: numpy>=1.9.0 in c:\users\win\pycharmprojects\test\venv32\lib\site-packages (from pan
das) (1.15.0)
Requirement already satisfied: six>=1.5 in c:\users\win\
pycharmprojects\test\venv32\lib\site-packages (from python-
dateutil>=2.5.0->pandas) (1.11.0)
```

- Here give the pip information (reinstall pandas by pip in terminal, **this way can not solve the issue still**.)
`pip install pandas`
```
Collecting pandas
  Using cached https://files.pythonhosted.org/packages/a1/56/6abb1d552b37f58cfcc1cf5408
9af486b3d4825c38691809a93452527ba1/pandas-0.23.4-cp36-cp36m-win32.whl
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\win\pycharmproje
cts\test\venv32\lib\site-packages (from pandas) (2.7.3)
Requirement already satisfied: numpy>=1.9.0 in c:\users\win\pycharmprojects\test
\venv32\lib\site-packages (from pandas) (1.15.0)
Requirement already satisfied: pytz>=2011k in c:\users\win\pycharmprojects\test\
venv32\lib\site-packages (from pandas) (2018.4)
Requirement already satisfied: six>=1.5 in c:\users\win\pycharmprojects\test\ven
v32\lib\site-packages (from python-dateutil>=2.5.0->pandas) (1.11.0)
Installing collected packages: pandas
Successfully installed pandas-0.23.4
```

**2. The program is my own project that used pandas.**

**Comment by WillAyd** [comment]
I think there is an issue with pandas and pyinstaller 3.3 which was resolved in their 3.4 version. You can try upgrading to that if that's an option. Otherwise can you see if this SO answer helps?

https://stackoverflow.com/a/47501512/621736

**Comment by WillAyd** [comment]
Closing as issue is related to third party executable-creation tool

**Comment by isanmu** [comment]
@WillAyd 
Thanks for your reply!
1. Your first recommend is **worked**! I can open my program normally now.
2. Your second recommend have been tried before, but didn't work.

I still confused why pandas(0.20.3) can work with Pyinstaller(3.3.1) normally...

In a word, thanks for your recommends!

**Comment by WillAyd** [comment]
It looks like it started with some of the changes in 0.21.0. You can read up on it on the PyInstaller site if you want as it was discussed at length there. Here's the PR which fixed it as a starting point:

https://github.com/pyinstaller/pyinstaller/pull/2998
