### ISSUE TITLE
DataFrame query method - numexpr safety check fails 

### ISSUE THREAD

**Issue by machow** [pandas-dev/pandas#22435]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd
df = pd.DataFrame({'a': ['1','2','3'], 'b': [4,5,6]})
df.query("a.astype('int') < 2")
```

raises `TypeError: unhashable type: 'numpy.ndarray'`

#### Problem description

**Background**
When using numexpr, Pandas has an internal function,  `_check_ne_builtin_clash`, for detecting when a variable used in a method like query clashes with a numexpr built-in.

Here's an example of the function raising an error as intended..

```
df = pd.DataFrame({'abs': [1,2,3]})
df.query("abs > 2")
# Raises NumExprClobberingError: Variables ... overlap with builtins: ('abs')
```

Mostly, the names it protects again are math functions like `sin`, `cos`, `sum`, etc..

**Why my original example fails**

The trouble with my original code is that `check_ne_builtin_clash` is checking the name of both sides of the BinaryExpr AST node corresponding to `"a.astype('int') < 2"`.
It does this by putting them into a frozenset.
However, the LHS ends up being a Constant node, with the name `array([1,2,3])`, which is an ndarray, so is not hashable. 

**Solution**

It seems like the helper function `_check_ne_builtin_clash` should consider any name that is unhashable safe, since it can't conflict with the function names being searched for. If this seems like a reasonable behavior, let me know and I will submit a PR!

code for function:

https://github.com/pandas-dev/pandas/blob/b82253590a66b4a35ed682bca244f668f16c3e0b/pandas/core/computation/engines.py#L23-L38

code for var names it looks for:

https://github.com/pandas-dev/pandas/blob/master/pandas/core/computation/ops.py#L20-L26

#### Expected Output

```
> df.query("a.astype('int') < 2")
   a  b
0  1  4
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Darwin
OS-release: 15.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 3.2.1
pip: 9.0.1
setuptools: 40.0.0
Cython: 0.24
numpy: 1.15.0
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.5.0
sphinx: 1.4.9
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: 1.1.0
tables: 3.2.2
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.2
lxml: 4.2.2
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.10
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by ianozsvald** [comment]
I'd like to add another example to reinforce the above message. I came across this when using Pandas on a remote machine _with_ `numexpr` whilst using Pandas locally _without_ `numexpr` - the remote version failed, the local version ran.

Using the `df` in the parent comment both of the following will work if `numexpr` is not installed, they'll both fail the same way if it is installed:
```
import pandas as pd
df = pd.DataFrame({'a': ['1','2','3'], 'b': [4,5,6]}) # same as parent
df.query("a.astype('int') < 2") # same as parent
df.query('b.abs() < 5') # new example
```
Both of the `query` lines raise the same exception:

```
~/miniconda3/envs/.../pandas/core/computation/expr.py in names(self)
    786         if is_term(self.terms):
    787             return frozenset([self.terms.name])
--> 788         return frozenset(term.name for term in com.flatten(self.terms))
    789 
    790 
TypeError: unhashable type: 'numpy.ndarray'

```

I ran the above example locally without `numexpr`, then with (which fails), then without again (which succeeds again).

I'm using Pandas 1.0.3, Python 3.8, numexpr 2.7.1.

```
pd.show_versions()                                                                                                                                                                                                                    

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.6.7-050607-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.0.3
numpy            : 1.17.5
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 47.1.1.post20200529
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.15.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.2.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : 0.49.1

```

**Comment by machow** [comment]
I tested the example in my original post, and the one by the commenter above and both seem to work w/ v1.1. Going to close--thanks for all the work put into pandas!

**Comment by simonjayhawkins** [comment]
@machow i'll reopen this as this does not appear to be fixed in 1.1.0 or master. did you have numexpr installed?

**Comment by simonjayhawkins** [comment]
also we should generally add tests to prevent regression before closing issues.

**Comment by machow** [comment]
Ah, thanks @simonjayhawkins -- so much time elapsed from the time this was opened, and I didn't see a response from any pandas devs, so assumed it may have gone stale (I likely don't have time to submit a PR for this anymore, but am happy to test).

**Comment by AlexisMignon** [comment]
The following solution was proposed by @machow :

> **Solution**
> 
> It seems like the helper function `_check_ne_builtin_clash` should consider any name that is unhashable safe, since it can't conflict with the function names being searched for. If this seems like a reasonable behavior, let me know and I will submit a PR!

It is unfortunately not enough. I've replaced the code starting at https://github.com/pandas-dev/pandas/blob/c979bd8b84e95bab0f69b4be71d2cd340e71912f/pandas/core/computation/expr.py#L827:

```python
    @property
    def names(self):
        """
        Get the names in an expression.
        """
        if is_term(self.terms):
            return frozenset([self.terms.name])
        return frozenset(term.name for term in com.flatten(self.terms))
```
by

```python
    @property
    def names(self):
        """
        Get the names in an expression.
        """
        if is_term(self.terms):
            if self.terms.name.__hash__ is not None:
                return frozenset([self.terms.name])
            else:
                return frozenset()
        return frozenset(term.name for term in com.flatten(self.terms))
```
which is probably not the best way. It however allowed me to go further in the execution.

At some point:
https://github.com/pandas-dev/pandas/blob/c979bd8b84e95bab0f69b4be71d2cd340e71912f/pandas/core/computation/engines.py#L121

a string is passed to `numexpr.evaluate`. In my example above, this string is:
```
"'0    False\\n1    False\\nName: A, dtype: bool'"
```
It seems that the result of the expression parsing with `PandasExprVisitor is a `Constant` term associated with the evaluation of the expression. When passed to `ne.evaluate()` it's the string representation which is used.

**Comment by untanglereality** [comment]
If anyone is having trouble with `unhashable type` error when using Pandas `query`,  you can add `engine="python"` argument if the performance isn't a problem.

> You can pass `engine='python'` to evaluate an expression using Python itself as a backend. This is not recommended as it is inefficient compared to using `numexpr` as the engine. 
Source: [DataFrame.query documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)

**Comment by jiagengliu** [comment]
If anyone is having trouble with `unhashable type` error when using the Pandas query, you can **upgrade to pandas 1.4**.

``pip install pandas==1.4.3`` fixes the problem for me.
