### ISSUE TITLE
Add a function to draw sequential samples from a DataFrame

### ISSUE THREAD

**Issue by chrism2671** [pandas-dev/pandas#22445]
I've written this method that I use repeatedly on Pandas DataFrames. I'd like to propose it be included in Pandas core, either on its own, or as a modification to `DataFrame.sample()`. 

```python
def draw_sample(df, length=1):
    """Random sequential sample with replacement of the given length."""
    end_of_sample_selection_space = df.index.get_loc(df[-1:].index[0])-length
    s = np.random.choice(range(0, end_of_sample_selection_space))
    return df.iloc[s:s+length]
```

## Why do we need this?

There is already a function to sample with replacement from a df, however it will only select individual rows, not sequences of rows. If you work with sequential data, such as time series, it's often important to be able to sample sequences. The main reason you would do this is to apply the [statistical bootstrap](https://en.wikipedia.org/wiki/Bootstrapping_(statistics)).

Please let me know if there's any interest for inclusion, and if so, how it best be included.

**Comment by TomAugspurger** [comment]
Perhaps as a cookbook entry, but I don't think this warrants a new method or complicating an existing one, since other libraries like https://github.com/bashtage/arch implement bootstrap.

**Comment by MarcoGorelli** [comment]
closing as there hasn't been any uptake here
