### ISSUE TITLE
Provide single base class with all extension tests.

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#22442]
It's slightly annoying to have files like

```python
class TestMissing(base.BaseMissingTests):
    pass

class TestOps(base.BaseOpsTests):
    pass
```

for all the extension tests. It'd be nice to have a single base class. The problem is ensuring names don't clash. Python has a built-in mechansim, name mangling, for doing what we want, but it would involve an API breaking change for tests (there's probably a clever hack that could avoid breaking API).

```python
# test_foo.py
class A:
    def __test_bar(self):
        assert 1

class B:
    def __test_bar(self):
        assert 0


class BaseTests(A, B):
    pass



class TestIt(BaseTests):
    pass
```

and a `pytest.ini`

```
[pytest]
python_functions=_*__test*
```

I don't think we should, am curious to hear others' thoughts.

**Comment by jorisvandenbossche** [comment]
We could write a small test that checks all methods of the BaseExtension classes and checks that there are no duplicates. That is of course not a proper run-time test ensuring there are actually no clashes in the ran tests, but at least it would ensure that in the base tests we implement we don't put duplicates, without requiring a change in the tests.

**Comment by TomAugspurger** [comment]
Hmm that's better.

**Comment by jorisvandenbossche** [comment]
Thinking about it further, I think it would be good to provide something like this, but I am actually not sure I would use it myself. While working on the integer tests and on geopandas, I actually found it useful to easily run a specific subset of tests using the different classes.

**Comment by TomAugspurger** [comment]
Likewise. During development it’s nice to get the basics working first (interface) before moving on to higher level methods.

________________________________

**Comment by TomAugspurger** [comment]
Closing as probably not worthwhile.
