### ISSUE TITLE
EA concat_same_type vs Index concat_same_dtype?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#22443]
Working on making making the DatetimeLike ArrayMixin classes into full-fledged EA subclasses, I need to implement `_concat_same_type`.  The Index subclasses already have `_concat_same_dtype`, which looks like it implements the right thing.

Should we rename the Index method to match the EA name?  Or do these need to stay separate?

**Comment by TomAugspurger** [comment]
Index._concat_same_dtype seems to have a different signature (`name` as a required parameter). If it's not too much work, I would handle name outside the `Index._concat_same_dtype`, and change the name / signature to match `ExtensionArray._concat_same_type`

**Comment by jorisvandenbossche** [comment]
Since Index will not subclass the ExtensionArray, I don't think it is that essential to match the signatures. 

I would basically implement this in `ExtensionArray._concat_same_type`, and then the `Index._concat_same_dtype` can call that and do in addition the name handling
