### ISSUE TITLE
pd.Timestamp.utcfromtimestamp should return tzaware

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#22451]
ATM `pd.Timestamp.utcnow()` returns a UTC-localized `Timestamp` object, but `pd.Timestamp.utcfromtimestamp()` does not.  As a result, the following round-trip fails:

```
unow = pd.Timestamp.utcnow()
result = pd.Timestamp.utcfromtimestamp(unow.timestamp())
assert unow == result  # <-- TypeError because unow is tzaware and result is tznaive
```

Changing this would mean breaking with the stdlib, but our `utcnow` already breaks with the stdlib (see also #22450)

**Comment by mroeschke** [comment]
+1 I think breaking from the stdlib is fine since we offset rich support for timezones and we do not advertise `Timestamp` as a direct replacement for `datetime.datetime`

**Comment by jbrockmendel** [comment]
BTW, there is now a thread on the datetime stdlib SIG mailing list (https://mail.python.org/archives/list/datetime-sig@python.org/thread/PT4JWJLYBE5R2QASVBPZLHH37ULJQR43/) about changing datetime.utcnow and datetime.utcfromtimestamp behavior
