### ISSUE TITLE
Inconsistent keyword argument name for the 'periods' in pandas.Index.shift for a DatetimeIndex

### ISSUE THREAD

**Issue by MaximizedAction** [pandas-dev/pandas#22458]
The actual implementation of ``pandas.Index.shift`` for a datetime-like index takes a differently named parameter for the number of shifts than the base method.

It should be named ``periods``, which would also be consistent with the ``pandas.DataFrame.shift`` or ``pandas.Series.shift`` methods. But for a DatetimeIndex it's ``n``.

See:
https://github.com/pandas-dev/pandas/blob/v0.23.4/pandas/core/indexes/base.py#L2586
vs.
https://github.com/pandas-dev/pandas/blob/v0.23.4/pandas/core/indexes/datetimelike.py#L1021

With a DatetimeIndex, following the documentation leads to a
```
TypeError: shift() got an unexpected keyword argument 'periods'
```

If this is somehow intended, then it should be stated so in the docstring for ``pandas.Index.shift``.

pandas version is 0.23.4

**Comment by TomAugspurger** [comment]
They probably used to be separate classes, and then were merged. We could deprecate `n` and replace it with `periods`.

**Comment by TomAugspurger** [comment]
@arminv do you have any interest in doing the same for `PeriodIndex`? I think we should be consistent everywhere if possible. https://github.com/pandas-dev/pandas/blob/7343fd37f809feeb98844a34dc5854a08df2aa94/pandas/core/arrays/period.py#L322

**Comment by arminv** [comment]
@TomAugspurger yeah sure! I’ll start working on it
