### ISSUE TITLE
DOC: Update docstring of DataFrame/Series .equals() to explain the behavior with indices

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#22462]
Some work and some discussion happened at #19213.

`df1.equals(df2)` returns a single boolean value on whether the two dataframes contain the same values and indices. This includes types for the data, but not for the indices.

The docstring should be improved to follow all our standards, including:
- A `See Also` section that at least links to `.eq()`
- `Parameters`
- `Examples`
- `Notes` with the mentioned behavior about indices

**Comment by datapythonista** [comment]
Sure @seantchan , that's a great first issue if you're starting. Let me know if you need help.

**Comment by seantchan** [comment]
Thanks Marc - working on it now. The docstring is all typed up, just reviewing it now and setting up the dev environment.
