### ISSUE TITLE
Increasing HTML Table Size on DataFrames

### ISSUE THREAD

**Issue by achapkowski** [pandas-dev/pandas#22461]
I have a general question: When I display the `pd.DataFrame` in Jupyter Notebooks, I have lots of white space.

Example:

![image](https://user-images.githubusercontent.com/5131271/44465700-557e3700-a5ec-11e8-8cc8-eae84cae7246.png)

Is there a way to increase the font, and cell size?  During presentations it is hard to see the cells and tables.

**Comment by WillAyd** [comment]
For usage questions we suggest you post on Q&A sites like StackOverflow. This board is for bug reports and enhancement requests.

**Comment by achapkowski** [comment]
@WillAyd I did, and I haven't gotten any response, so I figured I'd go straight to the source.

**Comment by WillAyd** [comment]
If you want to cross reference the link to that here it won't hurt, though again you'll want the answer there. If anything there are quite a few ways to go about this not all of which are exclusive to pandas, hence why SO is a better forum for this

**Comment by achapkowski** [comment]
https://stackoverflow.com/questions/51967445/pandas-dataframe-display-in-jupyter-notebook
