### ISSUE TITLE
Change in behavior of DatetimeIndex + Offset

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#22465]
```python
import pandas as pd

offset = pd.tseries.offsets.Week(weekday=6)
idx = pd.DatetimeIndex(['1999-12-26', '2000-05-14']) 

assert (idx[0] + offset) == (idx + offset)[0]
```

bisected to https://github.com/pandas-dev/pandas/pull/18952

Before that the assertion was true, after it's false

```
# before
>>> idx + offset
DatetimeIndex(['2000-01-02', '2000-05-21'], dtype='datetime64[ns]', freq=None)

# after
>>> idx + offset
DatetimeIndex(['1999-12-26', '2000-05-14'], dtype='datetime64[ns]', freq=None)
```

cc @reidy-p is this an expected change due to #18952, or a new bug? If it's intentional, we should document that.

**Comment by TomAugspurger** [comment]
Hmm if I had to guess, https://github.com/pandas-dev/pandas/pull/18952/files#diff-63e1050a658278e30a3e7a744c4d6435R1324 is the line directly to blame, which seems pretty intentional :)

**Comment by reidy-p** [comment]
@TomAugspurger thanks for spotting this. It seems like the problem is a bit deeper than the line you're pointing to - I'll take a closer look and see if I can fix it.

**Comment by reidy-p** [comment]
@TomAugspurger Sorry, I'm just coming back to this now. Are you still able to reproduce this? It seems to be fixed for me on master.

**Comment by TomAugspurger** [comment]
Fails for me on master.

```python

In [1]: import pandas as pd
   ...:
   ...: offset = pd.tseries.offsets.Week(weekday=6)
   ...: idx = pd.DatetimeIndex(['1999-12-26', '2000-05-14'])
   ...:
   ...: assert (idx[0] + offset) == (idx + offset)[0]
   ...:
   ...:
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-1-8c110b991a5b> in <module>()
      4 idx = pd.DatetimeIndex(['1999-12-26', '2000-05-14'])
      5
----> 6 assert (idx[0] + offset) == (idx + offset)[0]

AssertionError:


```

are your C-extensions up to date?

**Comment by reidy-p** [comment]
@TomAugspurger Sorry that was a mistake on my part. Forgot that I had made some changes that I didn't stash before testing.
