### ISSUE TITLE
ExtensionDtype should be hashable

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#22476]
Using this for sparse in https://github.com/pandas-dev/pandas/pull/22325, it'd be good to have generally.

**Comment by TomAugspurger** [comment]
So, a safe and low-tech option is to have EA authors declare the meaningful attributes of their ExtensionDtype. For PeriodDtype, this is freq. For CategorcialDtype its the categories and order.


```python
class PeriodDtype(ExtensionDtype):
    _attributes = ['freq']

    def __eq__(self, other):
        if isinstance(other, compat.string_types):
            try:
                other = self._construct_from_string(other)
            except TypeError:
                return False
        if isinstance(other, type(self)):
            return all(
                getattr(self, attr) == getattr(other, attr)
                for attr in self._attributes
            )
        return False

    def __hash__(self):
        return hash(tuple(getattr(self, attr) for attr in self._attributes))
```

(in reality, `__hash__` and `__eq__` would go on the base ExtensionDtype class, not PeriodDtype.

That requires a couple things from all the `_attributes`.

1. Their `__eq__` returns a boolean
2. They're hashable

CategoricalDtype.categories fails on both those counts, so the default implementation would work for it, but that's fine. I think that's a less common case.

The downside is a tiny bit of duplication. We could do fancier things with metaclasses probably, but that seems like overkill.

**Comment by h-vetinari** [comment]
I guess I missed this somehow - my attempt at a SetArray (#22382) has been dormant for some time while other issues were more pressing. In any case, having hashability as a general requirement makes it impossible to implement an extension array for sets, unless there is a way to circumvent that requirement somehow.

**Comment by TomAugspurger** [comment]
I haven't looked at the details, but what about a SetDtype isn't hashable?
Keep in mind that this is for dtypes, not arrays (which can't be hashable,
since they're mutable).

**Comment by h-vetinari** [comment]
@TomAugspurger 
Thanks for the quick response. This was my misunderstanding - I read "Pandas now requires that extension dtypes be hashable" in https://pandas-docs.github.io/pandas-docs-travis/whatsnew/v0.24.0.html#extensiontype-changes, and got the wrong idea.

**Comment by TomAugspurger** [comment]
Hmm yes that is ambiguous. I'll rephrase it when I go through the docs
before the release.
