### ISSUE TITLE
Please add detail message instead of `Killed`

### ISSUE THREAD

**Issue by eromoe** [pandas-dev/pandas#22480]
#### Problem description

I have two large DataFrame to join,  console output `Killed` after join. I have  to add log to every function  to locate it is by pandas,.  You should really add a proper error message , to tell people where this error come from and why 

This https://github.com/dask/hdfs3/issues/168 may cause by same problem  too.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-91-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.3
pytest: None
pip: 18.0
setuptools: 38.5.1
Cython: None
numpy: 1.14.0
scipy: 1.1.0
pyarrow: 0.9.0
xarray: None
IPython: 6.2.1
sphinx: None
patsy: 0.5.0
dateutil: 2.6.1
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.1.2
openpyxl: 2.5.4
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: 4.2.3
bs4: None
html5lib: 1.0.1
sqlalchemy: 1.2.10
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jorisvandenbossche** [comment]
Can you provide a reproducible example that illustrates the problem? (see eg http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)

**Comment by jbrockmendel** [comment]
This sounds like the OOM Killer.  How big are these data frames and how much ram are you working with?

**Comment by eromoe** [comment]
There are multi duplicate datetimeindex in two dataframe, it is a mistake. 
I am here just want pandas to add a proper error message.

**Comment by jorisvandenbossche** [comment]
Yes, but for that we need a reproducible example. How can we otherwise know where a better error message needs to be added?

**Comment by eromoe** [comment]
I don't have sample data now. 
I have two datatime with DatatimeIndex . 

DatatimeIndex  is by hour , and have many duplicate .
For example, I have 400 unique [store_id, product_id] with sale_count at 2018-08-24 08:00:00 .
So there would have 400 duplicated DatatimeIndex .  That why merge get killed .

**Comment by jbrockmendel** [comment]
> console output `Killed` after join

There is no pandas code that gives that message, nor any that would intentionally close the process.  My hypothesis is that your system got RAM-constrained and the [OOM Killer](https://linux-mm.org/OOM_Killer) killed the process.  As I recall, `Killed` is precisely the message it leaves behind.

**Comment by WillAyd** [comment]
Closing for now as we cannot help without a reproducible example. If you can reconstruct one and share feel free to reopen
