### ISSUE TITLE
String method `.contains()` doesn't return True when it should

### ISSUE THREAD

**Issue by gianlucahmd** [pandas-dev/pandas#22481]
I found a string in a dataset with a sequence like this: "e+09". The string method `.contains()` returns True for subsets like `.contains("e+")` or `.contains("09")` but returns False for `.contains("e+09")`

See attached screenshot:

<img width="551" alt="screen shot 2018-08-23 at 12 03 51" src="https://user-images.githubusercontent.com/16074217/44519277-dad91880-a6cc-11e8-8b12-d17185e60346.png">

**Comment by TomAugspurger** [comment]
FYI, screenshots aren't very helpful, as they're hard to reproduce.

You want `.str.contains(..., regex=False)`.
