### ISSUE TITLE
Capture STDOUT For Validations Script Tests

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#22483]
See 
https://github.com/pandas-dev/pandas/pull/20061#issuecomment-415339418

**Comment by gfyoung** [comment]
The `capture_stdout` decorator in `pandas/util/testing.py` is a good place to start.

**Comment by gfyoung** [comment]
@rcromo : Thanks for wanting to contribute.  Let me answer your question:

`STDOUT` is not a variable.  It's the name of the location (or stream, rather) where anything you print goes.  What we want to do is redirect the `print` statements to another location that doesn't cause them to be displayed in the terminal output on Travis.

**Comment by rcromo** [comment]
@gfyoung Thanks for the response. I know the STDOUT isn't a variable, I meant to ask where specifically does it have to be redirected to.
