### ISSUE TITLE
DOC: ENH: Add a table of contents to the PDF documentation

### ISSUE THREAD

**Issue by dave-kirby** [pandas-dev/pandas#22485]
For python packages that I use a lot I like to have a PDF version of the documentation on my tablet for reference.  The PDF version of the Pandas doc is far less useful than most because it does not have a Table of Contents in the sidebar.  This makes it extremely difficult to quickly look up anything, especially as the first 450 pages are the change log.   

Compare the [Pandas PDF](https://pandas.pydata.org/pandas-docs/stable/pandas.pdf) with [Numpy](https://docs.scipy.org/doc/numpy-1.11.0/numpy-ref-1.11.0.pdf) or [Scipy](https://docs.scipy.org/doc/scipy-0.16.0/scipy-ref-0.16.0.pdf) PDFs to see what I mean.

**Comment by TomAugspurger** [comment]
Do you know what sphinx config controls this?

**Comment by dave-kirby** [comment]
I don't know much about sphinx, but this may help:  https://stackoverflow.com/questions/32335040/table-of-contents-sidebar-in-sphinx-latex-pdf

**Comment by Nikoleta-v3** [comment]
Hello. I investigated this a bit.

So locally after navigating to `docs` I can run the following command twice:

```
python make.py latex
```
and the table contents appears just fine. Having said that you already have a function implemented in `make.py` called `latex_force` which complies the file more than once. So (locally) 

```
python make.py latex_force 
```

does the trick and gives me this :smile: :

![screenshot from 2018-09-01 15-03-18](https://user-images.githubusercontent.com/19708408/44946481-6a817400-adfd-11e8-938c-ae42be181f0f.png)

**Comment by jorisvandenbossche** [comment]
And a follow-up on @Nikoleta-v3 's comment

We use `latex_forced` in the release script: 

https://github.com/pandas-dev/pandas-release/blob/b8e1afdb2bca2f8bc78c3d464d5ad67ac2a5b50b/scripts/build-docs.sh#L12

And also, if I look at a slightly older pdf, eg the one of 0.23.3, the table of contents is in there as expected: https://pandas.pydata.org/pandas-docs/version/0.23.3/pandas.pdf

So it seems to be an issue only with the latest build of 0.23.4 (maybe a change in sphinx version?)

**Comment by gepcel** [comment]
And the TOC is still missing in version 0.24.0, 0.25.0, 0.25.1.

**Comment by TomAugspurger** [comment]
May need someone to look into https://github.com/pandas-dev/pandas-release
/ https://github.com/pandas-dev/pandas-release/blob/master/Makefile#L97

**Comment by MarcoGorelli** [comment]
Closing as it seems the table of contents is indeed present in the current pdf version of the documentation https://pandas.pydata.org/docs/pandas.pdf
