### ISSUE TITLE
BLD: 3.7 wheels failing

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#22528]
I added hypothesis to fix the failing wheel builds. but still this 3.7 build is failing:

https://travis-ci.org/MacPython/pandas-wheels/builds/421519593

cc @TomAugspurger

**Comment by TomAugspurger** [comment]
Updated multibuild to the latest on master / daily.

Here's master: https://travis-ci.org/MacPython/pandas-wheels/builds/421692069 and the 3.7 build in particular: https://travis-ci.org/MacPython/pandas-wheels/jobs/421692071

Things seemed to pass fine.
