### ISSUE TITLE
Travis 27 SciPy Failures

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#22538]
As noted by @gfyoung in https://github.com/pandas-dev/pandas/pull/22515#issuecomment-416813428 something appears to be awry with the SciPy fixtures and the Travis 2.7 env

**Comment by TomAugspurger** [comment]
Two things compared to https://travis-ci.org/pandas-dev/pandas/jobs/421543071

1. mkl and nomkl are installed are installed, which seems strange.  https://travis-ci.org/pandas-dev/pandas/jobs/421777999#L1587. The numpy seems to have mkl, while the scipy one doesn't
2. libopenblas went from [0.2.20](https://travis-ci.org/pandas-dev/pandas/jobs/421543071#L1567) to [0.3.2](https://travis-ci.org/pandas-dev/pandas/jobs/421777999#L1573)

**Comment by WillAyd** [comment]
I noticed the build for scipy is also different when compared back to the working log you linked to. Do you know of a way to install the exact build from conda locally to see if that's it? I didn't see it in a `conda search scipy`

**Comment by TomAugspurger** [comment]
Running `conda env create --file = ci/travis-27.yaml` should get you most
of the way there, but there might still be some platform differences.

**Comment by TomAugspurger** [comment]
I'm taking a look at this now.

**Comment by TomAugspurger** [comment]
Seems like this package needs a blas metapackage constraint. The metadata is being fixed on anaconda's end.

**Comment by TomAugspurger** [comment]
This has been fixed. I restarted the build for https://travis-ci.org/pandas-dev/pandas/builds/422535976 and it's passing now.
