### ISSUE TITLE
 DatetimeIndex and loc method for ambiguous selecting

### ISSUE THREAD

**Issue by yutiansut** [pandas-dev/pandas#22583]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

In [1]: import pandas as pd

In [2]:

In [2]: data=pd.DataFrame([1,2,3,4],index=pd.to_datetime(['2018-08-01 09:30:00','2018-08-01 14:20:00','2018-08-02 10:00:00','2018-08-03 12:00:00'
   ...: ]))

In [3]: data
Out[3]:
                     0
2018-08-01 09:30:00  1
2018-08-01 14:20:00  2
2018-08-02 10:00:00  3
2018-08-03 12:00:00  4

In [4]: data.index
Out[4]:
DatetimeIndex(['2018-08-01 09:30:00', '2018-08-01 14:20:00',
               '2018-08-02 10:00:00', '2018-08-03 12:00:00'],
              dtype='datetime64[ns]', freq=None)


I remember in the last time , i can use loc/[] to select time ambiguously, for example


In [6]: data.loc['2018-08-01':'2018-08-02']

but now, it will raise an 'KEY Error', and the doc say using reindex, however, it doesn't work


```

#### WHAT I WANT:

i hope to get a method to ambiguously select the data (like i type the date, and return the min data in those day range, like former versions of pandas), thanks

#### Output of ``pd.show_versions()``

<details>

In [8]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.3
pytest: 3.6.4
pip: 18.0
setuptools: 39.1.0
Cython: 0.28.4
numpy: 1.14.5
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.5.0
sphinx: 1.7.6
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.4
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.5
lxml: 4.2.3
bs4: 4.6.1
html5lib: 0.9999999
sqlalchemy: 1.2.10
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by yutiansut** [comment]
@myles @jd @lebigot @hoffmann @parlarjb pls help~~ thanks again

**Comment by TomAugspurger** [comment]
See https://pandas.pydata.org/pandas-docs/stable/timeseries.html#partial-string-indexing.

You need to either pass a Timestamp to select a single item, or as high a resolution to select the items you want.

Your example doesn't raise a KeyError on master, haven't checked other versions.
