### ISSUE TITLE
dt accessor doesn't work with datetime.date

### ISSUE THREAD

**Issue by postelrich** [pandas-dev/pandas#22589]
#### Code Sample, a copy-pastable example if possible

```python
import datetime
import pandas as pd
x = pd.Series([datetime.date(2018, 9, 1)])
x.dt.strftime('%Y%m%d')
```
#### Problem description

Noticed that the dt accessor does not work with `datetime.date` objects. Why aren't dates supported?

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-327.10.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.23.2
pytest: 3.2.1
pip: 9.0.1
setuptools: 36.4.0
Cython: 0.28.1
numpy: 1.13.1
scipy: None
pyarrow: None
xarray: None
IPython: 6.1.0
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.9999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: 2.7.1 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by TomAugspurger** [comment]
NumPy doesn't have a datetime.date dtype, just datetime64. I'd recommend using datetime64 with the time set to midnight, or using a Period with daily frequency.

**Comment by chris-b1** [comment]
Yep - you'll have to pay a one term conversion cost, but once stored as a numpy array things will be faster, more memory efficient.

```python
In [36]: x = pd.Series([datetime.date(2018, 9, 1)] * 1_000_000)

In [37]: %timeit x_dt =  pd.to_datetime(x)
51.8 ms ± 533 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [49]: x_dt.memory_usage(deep=True) / x.memory_usage(deep=True)
Out[49]: 0.2000015999968
```

**Comment by jreback** [comment]
in theory an ExtensionArray could handle datetime.date
but IMHO not really worth the trouble
