### ISSUE TITLE
Invitation for comments / use: reading large fixed-width datasets efficiently

### ISSUE THREAD

**Issue by davclark** [pandas-dev/pandas#22592]
#### Code Sample, a copy-pastable example if possible

```python
import marketflow

sample = marketflow.TAQ2Chunks(sample_fname, chunksize=chunksize)
# Now you have quick access to TAQ data records in a chunked fashion
```

I think the code is fairly readable - core logic is [here](https://github.com/glass-bead-labs/marketflow/blob/master/marketflow/raw_taq.py).

For completeness, I will also mention this somewhat [odd ITCH parser](https://github.com/glass-bead-labs/marketflow/blob/master/marketflow/ITCHbin.py) that is currently geared towards reading into SAS via Python.

For the curious, here's a researcher-oriented description of [TAQ](https://wrds-www.wharton.upenn.edu/pages/support/data-overview/wrds-overview-taq/) and [ITCH](https://github.com/cswaney/prickle#nasdaq-itch-data). Those latter docs come from [an ITCH parser that is almost certainly better than mine](https://github.com/cswaney/prickle).

#### Problem description

My experience of read_fwf was that it was somewhat brittle and hard to work with for large data. So, I wrote my own approach with what were (to me) simpler ways of specifying column structure (separating an mmap'd recarray of bytes specification from a destination dtype specification), and working towards finding the most efficient way to effect translation from disk to "live" data.

The code is not complex and clearly doesn't support all of the features of read_fwf. That said, I think it would be straightforward to implement the general approach inside read_fwf. I'm also happy if other folks want to use the code outside of pandas. There are also experiments in the repo where I'm using dask or blaze which clearly don't belong in pandas, but which might inspire extension points for a good parser.

I'd been sitting on this for a while, and someone at the last JupyterCon recommended I put a placeholder issue here (their name is withheld to keep all the blame to myself!). So, if folks are interested in having part of this logic in pandas, or consolidating with other market data parsers, I'm happy to support that.

**Comment by chris-b1** [comment]
ref #6706 - didn't look closely at your approach, but certainly would welcome any performance improvements

**Comment by mroeschke** [comment]
Thanks for the suggestion but looks like this never took off so having it as a 3rd party library is sufficient for now so closing
