### ISSUE TITLE
plot.bar doesn't generate nice x-axis labels as plot.line does

### ISSUE THREAD

**Issue by bmironov** [pandas-dev/pandas#22594]
#### Code Sample, a copy-pastable example if possible

```python
# From Jupyter notebook

print ("Pandas", pd.__version__)
print ("Matplotlib", matplotlib.__version__)

Pandas 0.23.4
Matplotlib 2.2.3

prices_d.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 28 entries, 2018-07-25 00:00:00-04:00 to 2018-08-31 00:00:00-04:00
Data columns (total 9 columns):
open                  28 non-null float64
high                  28 non-null float64
low                   28 non-null float64
close                 28 non-null float64
volume                28 non-null int64
ln_return             27 non-null float64
stddev_cc             8 non-null float64
annualized_hv_cc      8 non-null float64
stddev_cc_smoothed    0 non-null float64
dtypes: float64(8), int64(1)
memory usage: 2.2 KB

prices_d['annualized_hv_cc']
timestamp
2018-07-25 00:00:00-04:00         NaN
2018-07-26 00:00:00-04:00         NaN
2018-07-27 00:00:00-04:00         NaN
2018-07-30 00:00:00-04:00         NaN
2018-07-31 00:00:00-04:00         NaN
2018-08-01 00:00:00-04:00         NaN
2018-08-02 00:00:00-04:00         NaN
2018-08-03 00:00:00-04:00         NaN
2018-08-06 00:00:00-04:00         NaN
2018-08-07 00:00:00-04:00         NaN
2018-08-08 00:00:00-04:00         NaN
2018-08-09 00:00:00-04:00         NaN
2018-08-10 00:00:00-04:00         NaN
2018-08-13 00:00:00-04:00         NaN
2018-08-14 00:00:00-04:00         NaN
2018-08-15 00:00:00-04:00         NaN
2018-08-16 00:00:00-04:00         NaN
2018-08-17 00:00:00-04:00         NaN
2018-08-20 00:00:00-04:00         NaN
2018-08-21 00:00:00-04:00         NaN
2018-08-22 00:00:00-04:00    0.078419
2018-08-23 00:00:00-04:00    0.078617
2018-08-24 00:00:00-04:00    0.074033
2018-08-27 00:00:00-04:00    0.073842
2018-08-28 00:00:00-04:00    0.070815
2018-08-29 00:00:00-04:00    0.068357
2018-08-30 00:00:00-04:00    0.069577
2018-08-31 00:00:00-04:00    0.068752
Name: annualized_hv_cc, dtype: float64

Actual code:
ax = prices['annualized_hv_cc'].dropna().plot.line(title=ticker+' Annualized Historical Close-to-Close Volatility', color='dodgerblue');

```
#### Problem description

If I use plot.line matplotlib produces nice major and minor x-axis ticks:
- 22 Aug 2018
- 23
- 24
- 25
...
- 31

If I use plot.bar, then matplotlib produces values of dataframe index instead:
- 2018-08-22 00:00:00-04:00
- 2018-08-23 00:00:00-04:00
- 2018-08-24 00:00:00-04:00
...
- 2018-08-31 00:00:00-04:00

I believe that "line" and "bar" chart types are interchangeable, similar to Excel. Therefore my expectation is to see different presentation of the data, but axis labels should work similar way

I didn't find reports of this issue. Sorry, if I missed something and it is a duplicate.

#### Expected Output

- 22 Aug 2018
- 23
- 24
- 25
...
- 31

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_CA.UTF-8
LOCALE: en_CA.UTF-8

pandas: 0.23.4
pytest: None
pip: 18.0
setuptools: 40.2.0
Cython: 0.28.5
numpy: 1.15.1
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.5.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by bmironov** [comment]
![image](https://user-images.githubusercontent.com/171609/45055547-1de8a380-b05e-11e8-93c2-567be36651fc.png)

**Comment by bmironov** [comment]
Same data as "bar". I rotated X labels, to keep them readable

![image](https://user-images.githubusercontent.com/171609/45055601-47a1ca80-b05e-11e8-9e1d-815d7f67a9fc.png)

**Comment by alimcmaster1** [comment]
Hey is this a pandas issues? Seems like you are describing more of a [matplotlib](https://github.com/matplotlib/matplotlib/issues) issue which you should raise with them, but I think its just a case of formatting the axis.

Its best if you reproduce you problem using minimal code. Brief guide to writing up issues is [here](https://pandas.pydata.org/pandas-docs/stable/contributing.html#bug-reports-and-enhancement-requests).

Hope that helps

**Comment by bmironov** [comment]
Just to keep track of possible matplotlib issue, here is the link: https://github.com/matplotlib/matplotlib/issues/12014

**Comment by TomAugspurger** [comment]
I don't think this is a matplotlib issue.

Pandas bar plot labels each point. Automatic labeling beyond that is out of scope for pandas I think.

If you want to reduce the labeling you can use matplotlib directly, or summarize the values somewhat (with a histogram for example).

**Comment by jgehrcke** [comment]
Related, might help some:
https://stackoverflow.com/q/30133280/145400
https://stackoverflow.com/q/50675920/145400
