### ISSUE TITLE
Set hypothesis HealthCheck

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#22593]
from https://github.com/pandas-dev/pandas/pull/22280#issuecomment-416407165

```
# add to pandas/conftest.py
from hypothesis import settings, HealthCheck

settings.default.suppress_health_check = (HealthCheck.TooSlow,)
                                       # HealthCheck.all() to disable all health checks
```

**Comment by alimcmaster1** [comment]
Perhaps we want to register a CI profile and another for dev similar to the examples [here ](https://hypothesis.readthedocs.io/en/latest/settings.html#default-settings). What do you think?

**Comment by jreback** [comment]
profiles sounds ok to me

**Comment by EzraBC** [comment]
I'm interested in working on this as my first issue. When perusing https://hypothesis.readthedocs.io/en/latest/healthchecks.html, it seems as though the argument should read `HealthCheck.too_slow`, am I missing something silly?

**Comment by alimcmaster1** [comment]
Thanks @EzraBC for being willing to contribute ! I’ve already raised a PR for this #22597 , but please take a look at other issues tagged with good first issue!
