### ISSUE TITLE
TypeError: object of type 'bool' has no len()

### ISSUE THREAD

**Issue by sam4u3** [pandas-dev/pandas#22604]
df = pd.DataFrame(self.Output_Data,index=False) 
df.to_excel(path) 

i want to generate excel without indexing column but it giving me below error

Traceback (most recent call last):

File "E:/Python_Projects/Scraptemplate/ProductCrawl.py", line 81, in Out_Excel
    df = pd.DataFrame(self.Output_Data,index=False)    #create dataframe of Dataout (list of dict)
  File "C:\ProgramData\Anaconda3\envs\Conda_env\lib\site-packages\pandas\core\frame.py", line 400, in __init__
    dtype=dtype)
  File "C:\ProgramData\Anaconda3\envs\Conda_env\lib\site-packages\pandas\core\frame.py", line 7359, in _arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
  File "C:\ProgramData\Anaconda3\envs\Conda_env\lib\site-packages\pandas\core\frame.py", line 7669, in _homogenize
    raise_cast_failure=False)
  File "C:\ProgramData\Anaconda3\envs\Conda_env\lib\site-packages\pandas\core\series.py", line 4159, in _sanitize_array
    if len(subarr) != len(index) and len(subarr) == 1:
TypeError: object of type 'bool' has no len()

provide best solution for this

**Comment by TomAugspurger** [comment]
Could you fill out the issue template? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by TomAugspurger** [comment]
The line `df = pd.DataFrame(Data,index=False)` is incorrect.

We now raise with a better error message.

```pytb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-aeb053d649e3> in <module>()
      2
      3 Data= [{'Produc Name': '', 'Product URL': '', 'Status': 'Done'}, {'Produc Name': '', 'Product URL': '', 'Status': 'Done'}, {'Produc Name': '', 'Product URL': '', 'Status': 'Done'}]
----> 4 df = pd.DataFrame(Data,index=False)
      5 df.to_excel('temp.xlsx')

~/sandbox/pandas/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    440
    441                     mgr = _arrays_to_mgr(arrays, columns, index, columns,
--> 442                                          dtype=dtype)
    443                 else:
    444                     mgr = self._init_ndarray(data, index, columns, dtype=dtype,

~/sandbox/pandas/pandas/core/frame.py in _arrays_to_mgr(arrays, arr_names, index, columns, dtype)
   7540         index = extract_index(arrays)
   7541     else:
-> 7542         index = ensure_index(index)
   7543
   7544     # don't force copy because getting jammed in an ndarray anyway

~/sandbox/pandas/pandas/core/indexes/base.py in ensure_index(index_like, copy)
   5064             index_like = copy(index_like)
   5065
-> 5066     return Index(index_like)
   5067
   5068

~/sandbox/pandas/pandas/core/indexes/base.py in __new__(cls, data, dtype, copy, name, fastpath, tupleize_cols, **kwargs)
    443                          **kwargs)
    444         elif data is None or is_scalar(data):
--> 445             cls._scalar_data_error(data)
    446         else:
    447             if tupleize_cols and is_list_like(data):

~/sandbox/pandas/pandas/core/indexes/base.py in _scalar_data_error(cls, data)
    906         raise TypeError('{0}(...) must be called with a collection of some '
    907                         'kind, {1} was passed'.format(cls.__name__,
--> 908                                                       repr(data)))
    909
    910     @classmethod

TypeError: Index(...) must be called with a collection of some kind, False was passed
```

**Comment by sam4u3** [comment]
I didn't get you...how to solved my issue?

**Comment by TomAugspurger** [comment]
It's not quite clear what you want. Usually we use Github issues for bug
reports. Perhaps try creating a minimal example of what your desired output
is and post it to StackOverflow?

**Comment by sam4u3** [comment]
Yah I understand...
I think it's a lib related issue because it's working without index=False.
But I don't want indexing in xlsx file.

**Comment by TomAugspurger** [comment]
Presumably you want `df.to_excel(index=False)`? You can't have a DataFrame
without an index.

**Comment by sam4u3** [comment]
import pandas as pd

Data= [{'Produc Name': '', 'Product URL': '', 'Status': 'Done'}, {'Produc Name': '', 'Product URL': '', 'Status': 'Done'}, {'Produc Name': '', 'Product URL': '', 'Status': 'Done'}]
df = pd.DataFrame(Data)
df.to_excel('temp.xlsx',index=False)


Is this right code?
