### ISSUE TITLE
Any chance of a Python 3.5 32-bit manylinux1 wheel?

### ISSUE THREAD

**Issue by matthew-brett** [pandas-dev/pandas#22607]
I'm testing statsmodels wheels, and the 32-bit manylinux Python 3.5 build is failing because there is no 32-bit wheel for Pandas 0.23.4. 

https://travis-ci.org/MacPython/statsmodels-wheels/jobs/424746182#L4815

There are 32-bit wheels for the other supported Python versions.  Any chance of a 32-bit wheel for Python 3.5?

Thanks in hope.

**Comment by TomAugspurger** [comment]
Do we just need to add an entry in https://github.com/MacPython/pandas-wheels/blob/master/.travis.yml for 32-bit manylinux?

**Comment by h-vetinari** [comment]
Duplicate (including author ;-) ) to #21086...?

**Comment by matthew-brett** [comment]
@TomAugspurger - yes - that's the trick.

**Comment by TomAugspurger** [comment]
Happy to upload the wheels to PyPI once they're ready, though I won't get
to it until later today. I'll update the build config unless someone beats
me to it ;)

**Comment by matthew-brett** [comment]
Beat you to it for the config!  (See https://github.com/MacPython/pandas-wheels/pull/35).  When merged it should generate the wheel.

@h-vetinari - sorry, I forgot #21086 - that was for 0.23.0.  There haven't been 3.5 wheels since then.

**Comment by jreback** [comment]
merged the pr

**Comment by TomAugspurger** [comment]
@matthew-brett uploaded the new wheel to PyPI. https://pypi.org/project/pandas/0.23.4/#files
