### ISSUE TITLE
TST: test that operations with Series(ExtensionArray) and list-likes work

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#22606]
xref https://github.com/pandas-dev/pandas/pull/22026/files#r212253565

Operations with Series holding an ExtensionArray and with a list as other operand work, eg:

```
In [29]: pd.Series([1, 2, 3], dtype='Int64') + [1, 2, 3]
Out[29]: 
0    2
1    4
2    6
dtype: Int64
```

but we should add an explicit test for it (now only test with other Series, and not for array / list)

**Comment by gfyoung** [comment]
@jorisvandenbossche : It's been about a year...how does coverage look on this now?

**Comment by gusostow** [comment]
Is this issue still open? I'm looking for a good first thing to PR.

**Comment by avinashpancham** [comment]
@gusostow are you still planning to work on this?

**Comment by avinashpancham** [comment]
take
