### ISSUE TITLE
Slicing bug/miss in multi-index dataframes

### ISSUE THREAD

**Issue by oricou** [pandas-dev/pandas#22603]
Here is a surprising SyntaxError:

```python
arrays = [['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
          ['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two']]
df = pd.DataFrame(np.random.randn(8, 4), index=arrays)

df

                0         1         2         3
bar one -0.137729 -1.483386  0.979922  1.112311
    two  0.195880 -2.259884 -1.190358  2.029524
baz one  1.088035 -0.148262  0.728808  0.041469
    two -0.536962 -0.151630  0.895403 -2.115085
foo one -2.529932  0.768011  0.065440  0.646090
    two  0.031193 -1.082045 -0.442452 -1.542591
qux one  0.149052 -0.049976  0.687854  0.241037
    two -0.595371 -0.409159 -0.424744  0.489551


df.loc[(:, 'two'), :]
  File "<ipython-input-22-94f06d46dd36>", line 1
    df.loc[(:, 'two'), :]
            ^
SyntaxError: invalid syntax

# but this works
df.loc[(df.index.levels[0], 'two'), :]
 
                0         1         2         3
bar two  0.195880 -2.259884 -1.190358  2.029524
baz two -0.536962 -0.151630  0.895403 -2.115085
foo two  0.031193 -1.082045 -0.442452 -1.542591
qux two -0.595371 -0.409159 -0.424744  0.489551
```

I don't see why the first `:` is not replaced by the index of level 0? Does someone has an explanation or it has just been forgotten?
 
BTW there is the same issue with multi-columns.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-20-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.utf8
LOCALE: fr_FR.UTF-8

pandas: 0.23.3
pytest: None
pip: 18.0
setuptools: 39.0.1
Cython: None
numpy: 1.14.5
scipy: 1.0.1
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.5
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.1.11
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.6.0+35.gdf98a72

</details>

**Comment by TomAugspurger** [comment]
Python doesn't allow colons inside parenthesis; it's just not valid syntax.

We provide `pd.IndexSlice` for this

```python

In [11]: df.loc[pd.IndexSlice[:, 'two'], :]
Out[11]:
                0         1         2         3
bar two -1.625189 -1.538230 -1.669829 -0.643785
baz two  1.311869  1.683415 -0.799813 -0.287212
foo two  1.598791  1.000706  1.005640 -0.937102
qux two  0.345888 -2.033805 -2.055528  2.178184

```

**Comment by oricou** [comment]
ok, thanks. Do you why multi-index chose to use parenthesis instead of brackets? We could have done

```python
df.loc[ [:,'two'],  :]
```

**Comment by TomAugspurger** [comment]
That's also invalid syntax.

**Comment by oricou** [comment]
Indeed... sorry :-)
