### ISSUE TITLE
Refactor test_sql.py

### ISSUE THREAD

**Issue by alimcmaster1** [pandas-dev/pandas#22624]
Off the back of discussion in this [PR](https://github.com/pandas-dev/pandas/pull/22515) we should consider refactoring [test_sql.py](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/io/test_sql.py) to use just [PyTest Fixtures](https://docs.pytest.org/en/latest/fixture.html) opposed to fixures and the [old xunit](https://docs.pytest.org/en/latest/xunit_setup.html) style setup.  

Thanks,

Alistair

**Comment by tnwei** [comment]
Looks like the last PR resolves this issue, suggest to close
