### ISSUE TITLE
read_excel ignores `sheet_name` parameter in PyInstaller EXE but not in Python interpreter

### ISSUE THREAD

**Issue by alexHolistX** [pandas-dev/pandas#22629]
#### Code Sample

```python
import pandas as pd

filepath = 'C:/Users/User/Documents/Development/Python/PandaTest/test1.xlsx'
df = pd.read_excel(filepath, sheet_name='Data Entry', index_col=1)
print(df.head())
```
#### Problem description
I'm using the Pandas `read_excel` function to import data from a spreadsheet. This works fine when run under the Python interpreter, but when I build an exe with PyInstaller it imports the wrong worksheet. This could be an obscure PyInstaller issue, but it's not obvious why the Pandas code behaves differently in the deployed .exe

#### Expected Output
```
           Subject Name Sex Date of birth
Sample ID
HTX-620622   John Smith   M    2018-09-07
HTX-714652     John Doe   M    2018-09-07
HTX-200862  Joe Average   M    2018-09-07
HTX-810530  Fred Bloggs   M    2018-09-07
HTX-925727   John Smith   M    2018-09-07

```
#### Output of PyInstaller .exe
```     
abd  ghi def
456  123  789
456  123  789
456  123  789
456  123  789
456  123  789
```
<details>

#### Output of PyInstaller .exe with first worksheet deleted
```
           Subject Name Sex Date of birth
Sample ID
HTX-620622   John Smith   M    2018-09-07
HTX-714652     John Doe   M    2018-09-07
HTX-200862  Joe Average   M    2018-09-07
HTX-810530  Fred Bloggs   M    2018-09-07
HTX-925727   John Smith   M    2018-09-07

```
</details>

**Comment by WillAyd** [comment]
Doesn’t sound like a pandas issue but also would be very surprising if this is a result of PyInstaller. Any warnings when creating the executable? Any other parameters seemingly ignored?

**Comment by joost823** [comment]
Your question on SO intrigued me, so I tried to replicate it as follows:

Make Book1.xlsx using excel, 2 sheets with different information

mysterious.py

    import pandas as pd
    filepath = 'C:/Users/joost/Desktop/pyinstaller_testing/Book1.xlsx'
    df = pd.read_excel(filepath, sheet_name='Sheet2', index_col=1)
    print(df.head())
    with open('out.txt', 'w') as fout:
        fout.write(str(df.head()))

on the command line:

    virtualenv venv
    venv\Scripts\activate
    pip install pandas
    pip install xlrd
    pip install pyinstaller
    echo hiddenimports = ['pandas._libs.tslibs.np_datetime', 'pandas._libs.tslibs.nattype', 'pandas._libs.skiplist'] > venv\Lib\site-packages\PyInstaller\hooks\hook-pandas.py
    pyinstaller -F mysterious.py
    dist\mysterious.exe
   
resulted in printing the information on the second page of the spreadsheet, as expected. So I can't replicate this issue.

Are you 100% sure that you've deleted the .spec file, the dist folder and the build folder before rebuilding? I didn't once during testing, and that also resulted in spooky behavior here.

**Comment by alexHolistX** [comment]
Hi @WillAyd, this is the only odd behaviour I've seen in a complex program that uses a lot of Pandas.
PyInstaller returns a **lot** of messages but none of them seemed obviously relevant to the issue at hand. The problem only appears to surface at runtime.

**Comment by alexHolistX** [comment]
@joost823 - many thanks for taking the time to look into this. From your comment and @WillAyd's maybe this _is_ more of a PyInstaller issue. Very interested in what you have done re: Pandas hidden imports and hooks, I will look into this PyInstaller configuration and see if that's the root cause.

**Comment by WillAyd** [comment]
Closing as assumed not to be a pandas issue, but if you find to the contrary feel free to reopen
