### ISSUE TITLE
why same modification without any intererst

### ISSUE THREAD

**Issue by Malouke** [pandas-dev/pandas#22623]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

```
#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

before with previous version we can sort the value of data frame  by row and affect theme inside data frame like update but i don't now why you forget to keep this tools to increase the fluidity of use.

data [[col1,col2,col3]]   =  data [[col1,col2,col3]].apply(lambda l : sorted(l),axis=1)
is no possible , even it simplify my life .

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by WillAyd** [comment]
For usage questions please post to StackOverflow - this board for bug reports and enhancement requests

**Comment by Malouke** [comment]
thank's for  your fast reply but for me it about the choice of update no about usage questions.
last version of pandas was better than actual one .
thank's again
