### ISSUE TITLE
DataFrame.agg() raises TypeError when passing list of functions and setting axis=1

### ISSUE THREAD

**Issue by somiandras** [pandas-dev/pandas#22685]
#### Code Sample, a copy-pastable example if possible

```python
>>> df = pd.DataFrame([[1, 2, 3], [4, 5, 6]], index=['row1', 'row2'], columns=['A', 'B', 'C'])
>>> df

      A  B  C
row1  1  2  3
row2  4  5  6

>>> df.agg(['mean', 'sem'], axis=0)

        A    B    C
mean  2.5  3.5  4.5
sem   1.5  1.5  1.5

>>> df.agg(['mean', 'sem'], axis=1)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/frame.py", line 5832, in aggregate
    return self.apply(func, axis=axis, args=args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/frame.py", line 6014, in apply
    return op.get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/apply.py", line 142, in get_result
    return self.apply_standard()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/apply.py", line 248, in apply_standard
    self.apply_series_generator()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/apply.py", line 277, in apply_series_generator
    results[i] = self.f(v)
TypeError: ("'list' object is not callable", 'occurred at index row1')
```
#### Problem description

When passing a list of functions into `DataFrame.agg()` and setting `axis=1` I get `TypeError: ("'list' object is not callable", 'occurred at index row1')`.

The aggregations are valid on their own and can be done in single steps, like `df.agg('mean', axis=1)`. According the documentation it is valid to pass the list of function names for column axis too (though in the examples sections there is no similar case).

#### Expected Output

It should give aggregation results by rows:

```python
>>> df.agg(['mean', 'sem'], axis=1)

         row1     row2
mean  2.00000  5.00000
sem   0.57735  0.57735

```

(or probably the transposed of this)

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None

pandas: 0.23.4
pytest: None
pip: 18.0
setuptools: 39.0.1
Cython: None
numpy: 1.15.0
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.5.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by jreback** [comment]
cc @topper-123 i believe you recently fixed this
can u check master and see if we have tests to cover

**Comment by topper-123** [comment]
Yeah, this is fixed and the example works as expected in master. The tests for list inputs to ``df.agg`` are in ``tests/frame/test_apply.py::TestDataFrameAggregate::test_agg_reduce``. 

@somiandras , until 0.24 is released, a workaround is to do ``df.T.agg(['sum', 'sem']).T``.
