### ISSUE TITLE
Meaning of BaseDtypeTests.test_array_type_with_arg

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#22688]
https://github.com/pandas-dev/pandas/pull/22666 removed that test as (I think) it wasn't functioning properly. The method doesn't take any parameters, so running it would always raise a `TypeError`. Subclasses had to override it, which ends up just duplicating `test_array_type`.

cc @jreback, if you recall the motivation for it.

**Comment by jorisvandenbossche** [comment]
Yep, agree this was duplicating `test_array_type` now. I think in an original implementation `construct_array_type` actually had an argument, so this is probably a left over.

**Comment by jorisvandenbossche** [comment]
(@jreback closing as I think it is rather clear now I look at it, but of course feel free to re-open if you disagree)
