### ISSUE TITLE
scripts/convert_deps.py doesn't handle exact pins correctly

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#22689]
This should be a double equals: https://github.com/pandas-dev/pandas/blob/857515f60ef39d13d943969f6958e922f1e9b430/ci/requirements-optional-pip.txt#L17

conda uses a single, while pip requirements files use double.

**Comment by mroeschke** [comment]
Since all the refactoring of the scrips, is this still an issue?

**Comment by TomAugspurger** [comment]
Yeah, I think it's been fixed.
