### ISSUE TITLE
CI: add use Azure

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#22690]
numba project added support for Azure CI pipelines: https://github.com/numba/numba/pull/3303

https://azure.microsoft.com/en-us/services/devops/pipelines/

looks like 10 parallel pipelines for open-source projects on mac, linux, windows OS.

we could replace appveyor with this I think.

cc @pandas-dev/pandas-core

**Comment by TomAugspurger** [comment]
@jreback did you (or someone else) grab the "pandas" organization name on azure devops? If not, I can grab pandas-dev before someone else does and add people to it.

**Comment by jreback** [comment]
nope feel free to grab

**Comment by jeremyepling** [comment]
I'm a product manager on Azure Pipelines. Let me know if you run into any issues.

**Comment by gfyoung** [comment]
@TomAugspurger : I have an account on Azure Devops.  Same email as the one you see on my commits.

**Comment by chrisrpatterson** [comment]
I am a PM on Azure Pipelines as well please feel free to ping me if you need any assistance.
