### ISSUE TITLE
Handle FutureWarning from NumPy in Series Construction

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#22698]
This is with NumPy dev.

```python
In [2]: pd.Series(['0', '1'], dtype=float)
/Users/taugspurger/sandbox/numpy/numpy/core/numeric.py:2468: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return bool(asarray(a1 == a2).all())
Out[2]:
0    0.0
1    1.0
dtype: float64

```

https://travis-ci.org/pandas-dev/pandas/jobs/427640030#L5344

this goes from `core.series._sanitize_array` -> `_try_cast` -> `maybe_cast_to_integer_array`.

**Comment by TomAugspurger** [comment]
Also want to look at `cmp_method` in `pandas/core/arrays/datetimelike.py`

**Comment by jorisvandenbossche** [comment]
The occurrences of that last one:

https://github.com/pandas-dev/pandas/blob/d765dfbd53a70b94bc8e22b664d9235959832fd6/pandas/core/arrays/datetimelike.py#L59-L63

https://github.com/pandas-dev/pandas/blob/857515f60ef39d13d943969f6958e922f1e9b430/pandas/core/arrays/integer.py#L508-L512

https://github.com/pandas-dev/pandas/blob/d39249ad8ffc201dc7e92b063e2c8c2823b1cdc7/pandas/core/indexes/base.py#L98-L102

**Comment by TomAugspurger** [comment]
Looking through this again, I'm concerned I was overly-zealous in my filtering in https://github.com/pandas-dev/pandas/pull/22699. In particular, the `cmp_method` ones are probably bad. We're silencing the following


```python
In [6]: pd.Index([1, 2]) == 'a'
/Users/taugspurger/sandbox/pandas/pandas/core/indexes/base.py:84: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = op(self.values, np.asarray(other))
Out[6]: False

In [7]: pd.Index([1, 2]) == 1
Out[7]: array([ True, False])

In [8]: pd.Index(['a', 'b']) == 'a'
Out[8]: array([ True, False])

In [9]: pd.Index(['a', 'b']) == 1
Out[9]: array([False, False])
```

Clearly `Out[6] is the odd one out, so we want NumPy's future behavior. I'm worried now that it'll change without warning, since NumPy was issuing the warnings but we caught them.

How should we handle this? Is it as simple as not filtering those warnings?

**Comment by TomAugspurger** [comment]
Though I think we're OK pushing this to 0.24.2 or 0.25, since NumPy just had a release.
