### ISSUE TITLE
API: reconsider or warn on the non-sorting of DataFrame(dict) on Python >= 3.6 ?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#22709]
I recently had a colleague that ran into a nasty bug, due to the fact that on Python >= 3.6 we no longer sort the columns when creating a DataFrame from a dict.

Eg on Python 3.5:

```
In [1]: df = pd.DataFrame({'B': [1, 2], 'A': [3, 4]})

In [2]: df
Out[2]: 
   A  B
0  3  1
1  4  2
```

On Python 3.6/3.7 this would keep the column order as `['B', 'A']`. 

If you write code that depends on the ordering of columns, like `df.columns = ['other', 'name']` (not the most robust way, but people do that), or like `df.iloc[..]`, you will silently get different results, leading to bugs.

---

Opening the issue mainly to discuss to see if we can somewhat alleviate such problem and what other people think (did other people similar problems), not necessarily to propose to completely revert the change (that would also be annoying given that is already out for some time).

But we could think about raising a warning in the specific case of using dict on Python >= 3.6 where the sorted column order and dict keys order does not match. 
But the annoying thing is that there is no easy way then for people to silence the warning, apart from adding a new keyword we then later would deprecate itself.

cc @topper-123 @TomAugspurger

**Comment by TomAugspurger** [comment]
Hmm... I hadn't considered that case.

>  But the annoying thing is that there is no easy way then for people to silence the warning, apart from adding a new keyword we then later would deprecate itself.

We could have an option instead, and just never deprecate the option. And people have the usual warnings controls.

I would also suggest that we only emit the warning once, if we decide to have one.

**Comment by jorisvandenbossche** [comment]
> I would also suggest that we only emit the warning once, if we decide to have one.

Yes, that would at least make it less annoying if you decide not to silence it.

> Anyone got percentages for downloads of pandas for python 3.5 relative to 3.6+? We dropped 3.4 support about a year ago without much fuss, so could 3.5 be dropped when we drop 2.7?

I don't think that matters much in this case. Because even if you are already using Python 3.6, you then run into this when upgrading pandas 0.22 -> 0.23.

> We could have an option instead, and just never deprecate the option

You mean a `sort` keyword, that can be specified to silence the warning, and since it is somewhat useful anyhow, we can keep it afterwards?

If we were still in the 0.23 development cycle, I think my ideal would have been a warning that it will change in the future, but I suppose now warning "be aware, the column order of your dataframe has changed ..." will probably be best

**Comment by TomAugspurger** [comment]
> You mean a sort keyword, that can be specified to silence the warning,
and since it is somewhat useful anyhow, we can keep it afterwards?

Sorry I meant an option to silence the warning. It'd basically be an alias
for adding the right filter to the warnings list.


```

import pandas as pd

pd.options.warnings.ignore_order = True  # silence the warning


pd.DataFrame({"b": [1, 2], "a"; [1, 2]})

# no warning

```

**Comment by jorisvandenbossche** [comment]
> My point was more that if pandas 0.25/1.0 would be python 3.6+ only, then this ambiguity would go away, as all dicts would be ordered and a warning then wouldn't be needed.

Well, but I tried to explain that I think this point is not necessarily relevant, as even pandas only supports 3.6+, people can still upgrade from pandas 0.22 to 0.24 (both on python 3.6), and then a warning would still be relevant.

**Comment by topper-123** [comment]
> Well, but I tried to explain that I think this point is not necessarily relevant, as even pandas only supports 3.6+, people can still upgrade from pandas 0.22 to 0.24 (both on python 3.6), and then a warning would still be relevant.

Ok I see that isn't solved just by using Python3.6... I didn't foresee this when I made the PR, sorry.

So a warning could to be added in 23.5 independently of python version and and removed in a later version when support for Python 3.5 is dropped, right?

**Comment by topper-123** [comment]
A question: What does “issue a non-visible warning when we detect that we changed from 0.22 (dict is not sorted)” mean? How would we know from within pandas if we changed from 0.22?

**Comment by TomAugspurger** [comment]
When we're in dict-mode, the warning would be issued when `sorted(dict) != list(dict)` (i.e. the inserted order of the keys is not the same as the sorted order).

**Comment by topper-123** [comment]
Ok, a heuristic on the sortedness of the dict. I think this is a reasonable response. +1.

**Comment by jreback** [comment]
we should just close this

**Comment by TomAugspurger** [comment]
Not sure about that, but I won't get to it to 0.24.0 unfortunately.

**Comment by jorisvandenbossche** [comment]
Let's decide the ship has sailed on this one?

**Comment by jreback** [comment]
yep
