### ISSUE TITLE
Feature request: add an optional values parameter to Styler.background_gradient

### ISSUE THREAD

**Issue by dclong** [pandas-dev/pandas#22727]
Sometimes we want to apply background_gradient to some columns according to values in another column. There's no easy way to do this currently. It can be made possible by adding an optional values parameter. And when the values parameter is specified, it is used to generate background colors.

**Comment by TomAugspurger** [comment]
Can you provide an example?

**Comment by dclong** [comment]
![image](https://user-images.githubusercontent.com/824507/45603288-7015c580-ba5d-11e8-8160-38af1c8ed142.png)

**Comment by TomAugspurger** [comment]
It's not clear to me what the API would look like. IIRC, there's nothing else in Styler where a property for a column is computed by the values in another array.

It is unfortunate that you needed to duplicate the code in `Styler._background_gradient` with you `bg_grad` function.

**Comment by attack68** [comment]
I think this is fairly easy to deal with with an introduction of a new argument. `gmap` or gradient map just overrides the data in the input series with the specifically provided `gmap`. That way you can style a whole dataframe along an axis using only one row (or column), and achieve the OP's intent. eg.

``df.style.background_gradient(cmap='PuBu', gmap=df['col1'], axis=0)``

I'll get around to this at some point..
