### ISSUE TITLE
BUG: read_table crashes Python on surrogates

### ISSUE THREAD

**Issue by Kojoley** [pandas-dev/pandas#22748]
#### Code Sample

```python
import io
import pandas as pd

b = io.BytesIO(b"\xB0")
t = io.TextIOWrapper(b, encoding='ascii', errors='surrogateescape')
pd.read_table(t)
```
#### Problem description

The `pd.read_table(t)` call crashes the interpreter.

#### Expected Output

At least it should throw an exception but not to crash the interpreter.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.4
pytest: None
pip: 18.0
setuptools: 39.0.1
Cython: None
numpy: 1.14.3
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by chris-b1** [comment]
ref #22610 on the writing side.  No idea what's actually going wrong here, but would welcome investigation/PR - probably start by looking at the backtrace on the crash.  Thanks for the simple reproducing case.
