### ISSUE TITLE
Azure CI followup

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#22766]
1. Move doc build, as it occasionally times out on travis. This may be tricky as I think we have an encrypted key on Travis to push the docs to http://pandas-docs.github.io/pandas-docs-travis/ (cc @jorisvandenbossche)
2. Setup https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=vsts&tabs=yaml

**Comment by chrisrpatterson** [comment]
@TomAugspurger the equivalent feature in Azure Pipelines to encrypted variables in Travis is secret variables. https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=yaml%2Cbatch#set-an-output-multi-job-variable

**Comment by jschendel** [comment]
Thoughts on adding some 32-bit builds to our azure builds?  It looks like there's an [architecture argument](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=vsts#yaml-snippet) that can be specified as x86.  Not entirely sure if I'm interpreting that correctly, but if so it would close #13715 and allow us to catch things like #22813 sooner.

**Comment by TomAugspurger** [comment]
32-bit would be great to have tested regularly. I don't have plans to do that short-term though.

**Comment by TomAugspurger** [comment]
Test publishing is done.

I believe building the docs on azure is in progress, but not blocking for 0.24.

**Comment by datapythonista** [comment]
I think all the tasks here are now completed. @TomAugspurger feel free to reopen if I misunderstood.
