### ISSUE TITLE
Something wroing in rpy2 / R interface in Official Guide

### ISSUE THREAD

**Issue by DataMonk2017** [pandas-dev/pandas#22777]
In Latest Version of Pandas, the code explanation is kind of misleading due to the lack of rpy2 dependency. Please see png below:
![error](https://user-images.githubusercontent.com/16098658/45799203-44097700-bcdf-11e8-9ab6-09428b1ba8d3.JPG)

Here is the link: 
https://pandas.pydata.org/pandas-docs/stable/r_interface.html

**Comment by TomAugspurger** [comment]
Moving to https://github.com/pandas-dev/pandas-release/issues/5

**Comment by jorisvandenbossche** [comment]
Related to https://github.com/pandas-dev/pandas/pull/22424

**Comment by TomAugspurger** [comment]
Oh cool, so I should just need to rebuild and reupload? I'll try to get to that today.
