### ISSUE TITLE
Memory error on large machine

### ISSUE THREAD

**Issue by dumbledad** [pandas-dev/pandas#22779]
I run the following on two of my machines:

```python
import os, sqlite3
import pandas as pd
import numpy as np
from feat_transform import filter_anevexp
db_path = r'C:\Users\timregan\Desktop\anondb_280718.sqlite3'
db = sqlite3.connect(db_path)
anevexp_df = filter_anevexp(db, 0)
```

On my laptop (with 8GB of RAM) this runs without issue (although the call out to `filter_anevexp` takes a few minutes). On my desktop (with 128GB of RAM) it fails in pandas with a memory error:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\timregan\source\MentalHealth\code\preprocessing\feat_transform.py", line 171, in filter_anevexp
>     anevexp_df = anevexp_df[anevexp_df["user_id"].isin(df)].copy()
>   File "C:\Users\timregan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\core\frame.py", line 2682, in __getitem__
>     return self._getitem_array(key)
>   File "C:\Users\timregan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\core\frame.py", line 2724, in _getitem_array
>     return self._take(indexer, axis=0)
>   File "C:\Users\timregan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\core\generic.py", line 2789, in _take
>     verify=True)
>   File "C:\Users\timregan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\core\internals.py", line 4539, in take
>     axis=axis, allow_dups=True)
>   File "C:\Users\timregan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\core\internals.py", line 4425, in reindex_indexer
>     for blk in self.blocks]
>   File "C:\Users\timregan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\core\internals.py", line 4425, in <listcomp>
>     for blk in self.blocks]
>   File "C:\Users\timregan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\core\internals.py", line 1258, in take_nd
>     allow_fill=True, fill_value=fill_value)
>   File "C:\Users\timregan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\core\algorithms.py", line 1655, in take_nd
>     out = np.empty(out_shape, dtype=dtype)
> MemoryError

Is there anything special I need to do to prevent errors (e.g. addressing errors) on machines with lots of memory?

**Comment by dumbledad** [comment]
I've submitted this as a StackOverflow question too: [pandas memory error on large RAM machine but not on smaller RAM machine: same code, same data](https://stackoverflow.com/q/52422544/575530)

**Comment by jreback** [comment]
the answer on SO is right
32 python on windows allows very little memory to the process (about 1GB max); try using 64 bit
