### ISSUE TITLE
BUG: Importing pandas with warnings("error") fails

### ISSUE THREAD

**Issue by jebob** [pandas-dev/pandas#22788]
#### Code Sample, a copy-pastable example if possible

```python
import warnings
warnings.simplefilter("error")  # causes below line to fail, comment out to succeed without warning
import pandas as pd  
```
#### Problem description

Enabling `warnings.simplefilter("error")` causes pandas to raise an error

```
Traceback (most recent call last):
  File "C:/Projects/aereseu/jebob/eu/models/bm.py", line 4, in <module>
    import pandas as pd
  File "C:\Python36\lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "C:\Python36\lib\site-packages\pandas\_libs\__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
  File "pandas\_libs\tslibs\conversion.pxd", line 11, in init pandas._libs.tslib
  File "pandas\_libs\tslibs\conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "pandas\_libs\tslibs\nattype.pyx", line 14, in init pandas._libs.tslibs.nattype
ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
```
Running python with the command line option `Werror` results in the same behaviour.

#### Expected Output

Pandas should not crash when being imported. This is relevant for my use case where I am doing unit testing with `-Werror` enabled.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.23.4
pytest: 3.8.0
pip: 18.0
setuptools: 38.4.0
Cython: 0.28.5
numpy: 1.15.1
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.3.1
sphinx: None
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.0
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None

</details>

**Comment by TomAugspurger** [comment]
Blocked by https://github.com/cython/cython/issues/1720 I think.

```
$ python -W error
>>> import warnings
>>> warnings.filterwarnings("ignore", category=ImportWarning)
>>> import pandas
```

If this is important to you, you could add a small script to our CI to ensure that pandas can be imported without warnings.

**Comment by jebob** [comment]
This solves my issue, thanks for the quick response.

**Comment by TomAugspurger** [comment]
Closing, but if someone wants to add a test for this that's probably OK.
