### ISSUE TITLE
merge_asof can't handle floats in by column?

### ISSUE THREAD

**Issue by rndeon** [pandas-dev/pandas#22794]
#### Code Sample, a copy-pastable example if possible

```python
df1=pd.DataFrame({"cat":5*[-5.0] + 5*[25.0] + 5*[65.0], "num": np.tile(np.linspace(100,200,5),3) + 10*(np.random.rand(15)-0.5)}).sort_values("num")
df2 = pd.DataFrame({"cat": 3 * [-5.0] + 3 * [25.0] + 3 * [65.0], "num": 3*[110.0,190.0,200.0],"val":np.arange(0,9)}).sort_values("num")
test = pd.merge_asof(df1,df2, by="cat", left_on="num", right_on="num", direction="nearest").sort_values(["cat","num"])

```
errors with 

> File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\reshape\merge.py", line 1443, in _get_join_indexers
>     tolerance)
> TypeError: 'NoneType' object is not callable

while
```python
df1=pd.DataFrame({"cat":5*[-5] + 5*[25] + 5*[65], "num": np.tile(np.linspace(100,200,5),3) + 10*(np.random.rand(15)-0.5)}).sort_values("num")
df2 = pd.DataFrame({"cat": 3 * [-5] + 3 * [25] + 3 * [65], "num": 3*[110.0,190.0,200.0],"val":np.arange(0,9)}).sort_values("num")
test = pd.merge_asof(df1,df2, by="cat", left_on="num", right_on="num", direction="nearest").sort_values(["cat","num"])

```
works fine
#### Problem description

`_asof_by_function(self.direction, on_type, by_type)` returns `None` when `on_type="double"` and `by_type="double"`. 
returns sensibly with `on_type="double"` and `by_type="int64_t"`.

#### Expected Output

Since regular pd.merge works on float types, I'd expect this one to as well, though it was a simple workaround once I understood. Maybe a clearer error message if you intend it not to work?

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.23.4
pytest: 3.7.1
pip: 18.0
setuptools: 40.0.0
Cython: 0.28.5
numpy: 1.15.0
scipy: 1.1.0
pyarrow: None
xarray: 0.10.8
IPython: 6.5.0
sphinx: 1.7.6
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.7
feather: None
matplotlib: 2.2.3
openpyxl: 2.5.5
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.5
lxml: 4.2.4
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.10
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by WillAyd** [comment]
Hmm seems kind of strange. If I had to guess the `float` type may just need to be sized like the `int` types in the `join_func_helper.pxi.in` template:

https://github.com/pandas-dev/pandas/blob/0480f4c183a95712cb8ceaf5682c5b8dd02e0f21/pandas/_libs/join_func_helper.pxi.in#L23

Welcome to take a look and submit a PR if you can get it to work
