### ISSUE TITLE
pip install pandas fails on TypeError: find_packages() got an unexpected keyword argument 'include'

### ISSUE THREAD

**Issue by lldean18** [pandas-dev/pandas#22837]
#### Code Sample, a copy-pastable example if possible

(virtualenv) USERNAME:~$ pip install pandas
Collecting pandas
  Using cached https://files.pythonhosted.org/packages/e9/ad/5e92ba493eff96055a23b0a1323a9a803af71ec859ae3243ced86fcbd0a4/pandas-0.23.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7gbQDb/pandas/setup.py", line 736, in <module>
        packages=find_packages(include=['pandas', 'pandas.*']),
    TypeError: find_packages() got an unexpected keyword argument 'include'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-7gbQDb/pandas/

#### Problem description

I am trying to install pandas on a linux machine for python version 2.7.15 on Ubuntu 14.04.5 and it keeps failing saying: TypeError: find_packages() got an unexpected keyword argument 'include'

I read here: https://stackoverflow.com/questions/29477456/find-package-errors-during-installing-package-via-pip/29477720 that I might need to update some of the dependent packages so have updated numpy, pip, python-dateutil and setuptools and all my installed package versions are below:

(virtualenv) USERNAME:~$ pip list
Package          Version
---------------- -------------
biom-format      1.3.1
cogent           1.5.3
Cython           0.28.5
distribute       0.6.28
docutils         0.11
emperor          0.9.3
gdata            2.0.17
ipython          3.0.0.dev0
Jinja2           2.7.2
MarkupSafe       0.23
matplotlib       1.3.1
mpi4py           1.2.2
MySQL-python     1.2.3
nose             1.3.3
numpy            1.15.2
pip              18.0
PrimerProspector 1.0.1-release
Pygments         1.6
pynast           1.2.2
pyparsing        2.0.2
pyqi             0.3.1
pysqlite         2.6.3
python-dateutil  2.2
pytz             2018.5
pyzmq            2.1.11
qcli             0.1.0
qiime            1.8.0
setuptools       40.4.3
six              1.6.1
Sphinx           1.0.4
SQLAlchemy       0.7.1
tax2tree         1.0
tornado          3.1.1
wheel            0.31.1

I have also tried running this first:
sudo apt-get build-dep python-pandas
to no avail. 

I need the pandas package to run a python file conversion script. Am new to python and linux in general and have been struggling with this for days! Any help much appreciated and if more information is needed I will endeavour to give it!

Thank you

**Comment by TomAugspurger** [comment]
This doesn't really make sense. The error message kind of hints at an outdated setuptools, but you seem to have a recent version of that (and pip and wheel).

> that I might need to update some of the dependent packages so have updated numpy, pip, python-dateutil and setuptools and all my installed package versions are below:


Did you re-run `pip install pandas` after updating those?

**Comment by TomAugspurger** [comment]
Any update @lldean18?

**Comment by lldean18** [comment]
So I managed to get the script to run by downloading python for Windows and
installing all the packages on a Windows machine but never fixed the
problem on our Unix server!

Thanks for getting back to me though!

Laura

**Comment by TomAugspurger** [comment]
OK, let us know if you think there's an issue with pandas.
