### ISSUE TITLE
General repr format for our internal ExtensionArrays

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#22846]
Triggered by the discussion I am having in https://github.com/pandas-dev/pandas/pull/22511/, I was also thinking we should look at our EAs reprs.

Currently we have for IntegerArray:

```
In [14]: pd.core.arrays.integer_array([1, 2, 3, None])
Out[14]: IntegerArray([1, 2, 3, nan], dtype='Int64')
```

which *looks* like code, but actually is not valid code (because the constructor needs an array, has no dtype argument, and nan is actually no defined).

So also here (since here we still have the freedom to choose something without the concern of changing something), I think we should have some discussion about what we ideally want.

**Comment by jorisvandenbossche** [comment]
So a similar random thought as I mentioned in https://github.com/pandas-dev/pandas/pull/22511/, one possible alternative:

```
<pandas.IntegerArray>
[1, 2, 3, nan, ..., 1, 2, 3]
Length: 400, dtype: Int64
```

**Comment by TomAugspurger** [comment]
That seems fine.

Would we update Categorical to include `<pandas.Catgegorical>`, or are we happy with its current repo?

**Comment by jbrockmendel** [comment]
This and some other common-but-not-necessary methods could go in a mixin in something like `core.arrays.common` and get mixed in to all of the pandas-internal EA subclasses.

**Comment by TomAugspurger** [comment]
PeriodArray is using a repr like 
https://github.com/pandas-dev/pandas/issues/22846#issuecomment-424880091.

```
In [19]: arr = pd.core.arrays.period_array(['2000', '2001'], freq='A')

In [20]: arr
Out[20]:
<PeriodArray>
['2000', '2001']
Length: 2, dtype: period[A-DEC]
```

I'd be happy with something similar for IntegerArray.

SparseArray can't share it, because it needs to indicate the sparse points. But I think it can be a bit more uniform, something like

```python
>>> pd.SparseArray([1, 0, 0, 4])
<pandas.SparseArray>
[1, 0, 0, 4]
Indicies: array([0, 3]), dtype: Sparse[int64, 0]
```

Categorical could maybe be updated, but not a big deal.

**Comment by jorisvandenbossche** [comment]
I personally like the fact that we have 'pandas' in the repr, like I did in the IntegerArray example above, or how you did the SparsArray (what PeriodArray doesn't have), to make it clear from it's repr it is a *pandas* array, without needing to check `type(..)`. 
Buf of course, if we don't add them to the top level API (which still needs to be discussed), then `<pandas.IntegerArray>` is a bit confusing.

**Comment by TomAugspurger** [comment]
> already have longstanding for all Index types

This is for arrays, not index. It's similar to Categorical.

>  doesn't have angle brackets

We don't know if the repr is code, so angle brackets are appropriate.

> properly separates commas

Do you have an example of https://github.com/pandas-dev/pandas/pull/23617
where commas aren't handled correctly?

> This is a huge, undesired breaking change

https://github.com/pandas-dev/pandas/pull/23617 is backwards compatible.

**Comment by jorisvandenbossche** [comment]
> This is a huge, undesired breaking change.

You may not like the proposed format, but it is not "breaking". Nothing will be broken as this only affects new API (the internal EAs), not the reprs of Index or Series.

> I am puzzled why you are arbitrarily changing formats here from what we already have longstanding for all Index types.

It is not arbitrarily. There are reasons to do this, mentioned somewhat in the original issue. 
You are correct this is deviating from the typical format we have been using for the Index reprs. And therefore, we indeed need to have good reasons to do things differently.

Trying to put the original reasoning a bit clearer:

- Index and Array are different objects. I don't think it is a problem that they have a visually distinct repr.
- The current Index repr also has some disadvantages (which we don't necessarily have to carry over to the Array repr): 
  - It tries to "look" like actual code, and is that in many cases, but not in all (eg when there are missing values, when it is truncated, ..). But specifically for EAs, those cases are much more common (see points below).
  - Minor other  points: when truncated, it has a `length=..., ` inside the repr, which I find looking odd in a repr that mimics a constructor.
- Specifically for EAs, we don't recommend to use the actual class constructors (as opposed to the different Index subclasses). I think therefore having a repr that does not look like a class constructor is more important for Array than Index.
- Specifically for EAs, we decided to keep the class constructor simple. This means that eg a repr of a DatetimeIndex like `DatetimeIndex(['2012-01-01'], dtype='datetime64[ns]', freq=None)` is actually a valid constructor for DatetimeIndex, but a similar repr for DatetimeArray would not be a valid constructor for DatetimeArray. So IMO the repr of mimicking python code as we do for Index, is much less fitting for Array.

Since the Array class is a new API, we have the opportunity to discuss more freely what repr we would like to have. So let's discuss that (that's the reason I originally opened this issue).

**Comment by jreback** [comment]
> Index and Array are different objects. I don't think it is a problem that they have a visually distinct repr.
The more things are different the more inconsistencies across the code base in code, testing, and user experience. This is such a jaring huge change you now done't know what the relationship between Index and Array is. This is a bad thing.

> The current Index repr also has some disadvantages (which we don't necessarily have to carry over to the Array repr):
It tries to "look" like actual code, and is that in many cases, but not in all (eg when there are missing values, when it is truncated, ..). But specifically for EAs, those cases are much more common (see points below).
Sure, this is the case, but it is not a reason to deviate.


> Minor other points: when truncated, it has a length=..., inside the repr, which I find looking odd in a repr that mimics a constructor.
Specifically for EAs, we don't recommend to use the actual class constructors (as opposed to the different Index subclasses). I think therefore having a repr that does not look like a class constructor is more important for Array than Index.
This is a problem for MultiIndex as well. Again I am all for changing *everything*, just not a part.

> Specifically for EAs, we decided to keep the class constructor simple. This means that eg a repr of a DatetimeIndex like DatetimeIndex(['2012-01-01'], dtype='datetime64[ns]', freq=None) is actually a valid constructor for DatetimeIndex, but a similar repr for DatetimeArray would not be a valid constructor for DatetimeArray. So IMO the repr of mimicking python code as we do for Index, is much less fitting for Array.
This is also not true for Index generally, e.g. Period, not sure why this is an issue here.

I thinking breaking this change (and adding associated hacky things like removing commas), is just bad code smell. I would be ok with adding the repr the *same* as Index. Then if you want to change the repr generally that is ok, but half and half does not fly.

**Comment by jreback** [comment]
I might be more accepting if the repr is not multi-lined by default, I think this is also the cause of the 'need to remove the commas'.

**Comment by jorisvandenbossche** [comment]
@jreback can you format your comment a bit? Seems to have gone a bit wrong

**Comment by jreback** [comment]
> @jreback can you try to explain why you don't like the fact it is multi-line? Once you have a bit longer index, our current index repr is also multi-line (IntervalIndex is even multi-line by default, but that one is a bit inconsistent with the others)

for a short repr this is very awkward. Sure when its get longer it is multi-line. The point is the separation of the class from the data. I personally think the Index repr is just fine. 

You need a much stronger argument to arbitrarily change it. and that is what you are proposing. Consistency is the king here. You are simply breaking this.

**Comment by TomAugspurger** [comment]
So

```python
In [2]: pd.core.arrays.period_array(['2000', '2001'], 'D')
Out[2]: <PeriodArray>['2000-01-01', '2001-01-01'], Length: 2, dtype: period[D]
```

rather than

```python
In [2]: pd.core.arrays.period_array(['2000', '2001'], 'D')
Out[2]:
<PeriodArray>
['2000-01-01', '2001-01-01']
Length: 2, dtype: period[D]
```

would move you to a +1 on 
https://github.com/pandas-dev/pandas/pull/23601?

**Comment by jreback** [comment]
Currently

```
In [1]: pd.core.arrays.period_array(['2000', '2001'], 'D')
Out[1]: 
<PeriodArray>
['2000-01-01', '2001-01-01']
Length: 2, dtype: period[D]

In [2]: pd.Index(pd.core.arrays.period_array(['2000', '2001'], 'D'))
Out[2]: PeriodIndex(['2000-01-01', '2001-01-01'], dtype='period[D]', freq='D')

```

so i see some departures here which just don't make sense. quoting on the dtype, the length (in the current EA); this only shows up if its too long for the display normally. its 1 line, and I just don't like the angle brackets.

**Comment by TomAugspurger** [comment]
> and I just don't like the angle brackets.

One thing at a time. Do we agree that angle brackets are appropriate for the base repr, since we don't know if the repr is code?

**Comment by jreback** [comment]
> One thing at a time. Do we agree that angle brackets are appropriate for the base repr, since we don't know if the repr is code?

again no i don't agree, we have not done that elsewhere and therefore this is a completely breaking change. from a user perspective

**Comment by TomAugspurger** [comment]
We haven't defined a repr for objects with arbitrary constructors though. This *is* different.

**Comment by jreback** [comment]
sure we already have this repr for example, so i would assert this is NOT different.
```
In [1]: pd.Categorical(list('abc'))
Out[1]: 
[a, b, c]
Categories (3, object): [a, b, c]
```

**Comment by TomAugspurger** [comment]
We defined `Categorical.__init__` though. We don't define `ExtensionArray.__init__`, so we can't know whether the repr is valid code. Remember, I'm talking about the base repr here.
