### ISSUE TITLE
Export styler doesn't seem to include hide_index()

### ISSUE THREAD

**Issue by aaronbarzilai** [pandas-dev/pandas#22851]
#### Code Sample, a copy-pastable example if possible

```python
# Code based on example in docs
def color_negative_red(val):
    """
    Takes a scalar and returns a string with
    the css property `'color: red'` for negative
    strings, black otherwise.
    """
    color = 'red' if val < 0 else 'black'
    return 'color: %s' % color

np.random.seed(24)
df = pd.DataFrame({'A': np.linspace(1, 10, 10)})
df = pd.concat([df, pd.DataFrame(np.random.randn(10, 4), columns=list('BCDE'))],
               axis=1)
df.iloc[0, 2] = np.nan

display(df.style)

style1 = df.style.applymap(color_negative_red).hide_index() #option 1 when testing
#style1 = df.style.hide_index() #option 2 when testing

display(style1)

thestyle = style1.export()
print(thestyle)

df2 = -df
df2

style2 = df2.style
style2.use(style1.export())

```
#### Problem description

I'm trying to reuse a style for a second table, following the model in the docs at https://pandas.pydata.org/pandas-docs/stable/style.html#Sharing-Styles

I find that when I use my "option 1" above with red and hide index, the output for df styles as I would hope.

![image](https://user-images.githubusercontent.com/15833991/46121187-acc18980-c1e0-11e8-8dec-c5a5a9437927.png)

Note that the hide index seems empty when I print the styler, but it seems to know a second style is applied through the chaining.

When I then show df2, it has exported the red, but not the hide index.

![image](https://user-images.githubusercontent.com/15833991/46121232-e7c3bd00-c1e0-11e8-9ffc-087b74344007.png)

If I repeat with "Option 2", the index is hidden for df but not df2

I think I'm doing this correctly given the docs, please let me know if I'm not calling it correctly or it is known that I can't export chained styles. If it's in the latter, is that in the documentation? I didn't see it.

Thanks, really appreciate all the effort on pandas,
Aaron

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

_I tried to check by searching issues, sorry if I missed it_

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

_I just did, see show_versions output_

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-34-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: None
pip: 9.0.3
setuptools: 39.0.1
Cython: None
numpy: 1.14.3
scipy: None
pyarrow: None
xarray: None
IPython: 6.3.1
sphinx: None
patsy: None
dateutil: 2.7.2
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
Styler.export / Styler.use don't take into account attributes like `self.hidden_index` , precision, etc. Basically anything that can be set in the constructor or one of the `set_*` (or I guess `hide_*`) methods. Some of these probably should be exported, others (like uuid?) maybe shouldn't.

So going forward, I would say

1. figure out which attributes make sense to export
2. Add a parameter to `Styler.export` to control whether attributes should be exported (False by default, for backwards compatibility)
3. Update `Styler.export` to 
    - copy `self.todo`
    - add additional tasks for setting things like hidden index, (e.g., `lambda x: x.hide_index` if hidden_index is True)

**Comment by aaronbarzilai** [comment]
Thanks Tom.  I wasn't sure, is there a simple workaround I should use in
the interim with hide_index? I wasn't sure if it can be done via one of the
set_* now as a kwarg.  Not crucial but would be great to know and have
posted here when other people google for it.

Appreciate it,
Aaron

**Comment by TomAugspurger** [comment]
The workaround for  now is

```
if style1.hidden_index:
    style2 = style2.hide_index()
```

**Comment by attack68** [comment]
linked to #40484 since simialr discussion/logic should probably be applied to what `copy` `clear` and `export` does.

**Comment by attack68** [comment]
Im going to link this to #40675  and then close it so that thread can itemise this issue as well as keep track of similars
