### ISSUE TITLE
Initializing a column with a **set** builds a cartesian product

### ISSUE THREAD

**Issue by Demetrio92** [pandas-dev/pandas#22856]
#### Problem description

Initializing a dataset using a `set` type of object results in pandas building a cartesian product. Which isn't great b/c:

- It's totally unexpected
- it's extremely inefficient and at first will just block the console until you figure out why
- it's not mentioned in the docs, it's not part of the pandas cheatsheet, most of the SO answers, etc. E.g. it's **astounishing**.

#### Example
```python
import pandas as pd

col1 = set([1, 2, 3])
col2 = [2, 3, 4]
pd.DataFrame({
    'col1': set(col1),
    'col2': col2
})
#         col1  col2
# 0  {1, 2, 3}     2
# 1  {1, 2, 3}     3
# 2  {1, 2, 3}     4
#
# ^ wait, what?...
```

#### Expected Behaviour:
```python
pd.DataFrame({
    'col1': list(col1),
    'col2': col2
})
#    col1  col2
# 0     1     2
# 1     2     3
# 2     3     4
```

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-24-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
pandas: 0.23.1
pytest: 3.7.1
pip: 18.0
setuptools: 39.1.0
Cython: 0.28.3
numpy: 1.14.5
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: None
tables: 3.4.4
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: 1.2.8
pymysql: None
psycopg2: 2.7.5 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by Creotor** [comment]
Sets are unordered.

**Comment by mroeschke** [comment]
Now this intentionally raises and I believe we have tests for this behavior

```
In [6]: import pandas as pd
   ...:
   ...: col1 = set([1, 2, 3])
   ...: col2 = [2, 3, 4]
   ...: pd.DataFrame({
   ...:     'col1': set(col1),
   ...:     'col2': col2
   ...: })
TypeError: 'set' type is unordered
```

therefore, closing
