### ISSUE TITLE
Series.combine and ExtensionArrays

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#22850]
Working on a PeriodArray. For the first thing I tried, `Series.combine` doesn't work.

In https://github.com/pandas-dev/pandas/blob/7343fd37f809feeb98844a34dc5854a08df2aa94/pandas/core/series.py#L2324-L2330 we catch a TypeError. Why is that just a TypeError, when in principal the EA constructor could throw any kind of exception? In my case a ValueError is `ValueError` since the freq can't be inferred.

I think that should be `except Exception` instead. Thoughts @Dr-Irv?

**Comment by jorisvandenbossche** [comment]
Yes, I think that can be broadened to general exception.

**Comment by Dr-Irv** [comment]
IMHO, I would just add the errors that you know that could occur. So if `ValueError` can be raised by `._from_sequence()`, then I think you should do `except TypeError, ValueError`.  If some other error is raised, then it might catch another issue in someone's code.

**Comment by TomAugspurger** [comment]
_from_sequence is completely up to the EA author and could raise anything.
