### ISSUE TITLE
date_range method doesn't work when start and end params are string and crossing month. Works fine when start and end are datetime objects

### ISSUE THREAD

**Issue by szemel** [pandas-dev/pandas#22876]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
z = len(pd.date_range(start='30/09/2018 20:00:00', end='1/10/2018 04:00:00', freq='min'))
```
#### Problem description
date_range method doesn't work when start and end params are string and crossing month. Works fine when start and end are datetime objects.
z variable value is 0. Should be 480. 

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Linux
OS-release: 4.13.0-38-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.22.0
pytest: None
pip: 9.0.1
setuptools: 38.4.0
Cython: None
numpy: 1.14.0
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0b8
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by jorisvandenbossche** [comment]
@TomAugspurger I think it are rather european dates than a negative freq :-)

@szemel if you specify the dates in an ISO format, it works with strings:

```
In [14]: pd.date_range(start='2018-09-30 20:00:00', end='2018-10-01 04:00:00', freq='min')
Out[14]: 
DatetimeIndex(['2018-09-30 20:00:00', '2018-09-30 20:01:00',
               '2018-09-30 20:02:00', '2018-09-30 20:03:00',
               '2018-09-30 20:04:00', '2018-09-30 20:05:00',
               '2018-09-30 20:06:00', '2018-09-30 20:07:00',
               '2018-09-30 20:08:00', '2018-09-30 20:09:00',
               ...
               '2018-10-01 03:51:00', '2018-10-01 03:52:00',
               '2018-10-01 03:53:00', '2018-10-01 03:54:00',
               '2018-10-01 03:55:00', '2018-10-01 03:56:00',
               '2018-10-01 03:57:00', '2018-10-01 03:58:00',
               '2018-10-01 03:59:00', '2018-10-01 04:00:00'],
              dtype='datetime64[ns]', length=481, freq='T')
```

pandas parses both dates separately, so the second was interpreted as the first of january (and hence back in time), using the American style of "month first" as the first thing to try.

**Comment by TomAugspurger** [comment]
Ah, I misread the dates, yes.

**Comment by stoff3l** [comment]
If no one else is working on this I'd like to give it a shot? This would be my first issue so I'd appreciate a pointer as to where to focus my attention?

**Comment by jorisvandenbossche** [comment]
Sorry, I should have removed the tag, as I don't think there is anything to fix.

Closing, @szemel please complain if you don't agree!
