### ISSUE TITLE
 The problem of merging multiple files  with contact

### ISSUE THREAD

**Issue by fangaofeng** [pandas-dev/pandas#22878]
#### Code Sample, a copy-pastable example if possible

```
import os
import  pandas as pd

li = []

df_empty = pd.DataFrame()

fpathe = 'J:/test/'

print("deal{} excel".format(fpathe))
writer = pd.ExcelWriter(os.path.join(fpathe,'alltest.xlsx'))
for fpath,dirs,fs in os.walk(fpathe):
    
    for file in fs:
        fname,extension = os.path.splitext(file)
        print(extension)
        if extension != '.xlsx':
            continue
        print("---- {} is start---".format(file))
        filepath = os.path.join(fpathe,file)
        dframe = pd.read_excel(filepath)

        li.append(dframe.astype(str))
        print("----{} is complete--- ".format(file))
#tabledata = pd.concat(li).astype(str)
result = df_empty.append(li)
result.to_excel(writer,'Sheet1',index=False)

writer.save()
writer.close() 
print("-{} is save--- ".format('alltest.xlsx'))
```
#### Problem description
original input is:73332200430110023232323   
After contact multiple files,
excel is :
73332200430110023232323
7.3332200430110e+18
7.3332200430110e+18
7.3332200430110e+18

some is 73332200430110023232323,other is 7.3332200430110e+18

#### Expected Output
73332200430110023232323

whent i test sigle file, is correct .
```
import os
import  pandas as pd
path = 'j:/test/5235/'
filename="05.xlsx"

filepath=os.path.join(path,filename)
dframe = pd.read_excel(filepath,dytype='object')
dframe = dframe.astype(str)
writer = pd.ExcelWriter(os.path.join(path,'5235.xlsx'))
dframe.to_excel(writer)
writer.save()
writer.close()
```
73332200430110023232323 is always 73332200430110023232323 
#### Output of ``pd.show_versions()``
<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.1
pytest: 3.3.0
pip: 10.0.1
setuptools: 38.2.4
Cython: None
numpy: 1.14.5
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 0.9.3
lxml: 4.2.3
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by WillAyd** [comment]
Unfortunately this issue is not reproducible in its current state so its not something we can really help with. If you can provide something reproducible and *minimal* then someone on the team could review in more detail; please see the contributing guide on how to do that:

https://pandas.pydata.org/pandas-docs/stable/contributing.html#bug-reports-and-enhancement-requests

I'll take a stab in the dark and say that the formatting of your cells in Excel may impact the representation of the cell values, but again that's just a guess. If you can provide a reproducible example as outlined above feel free to reopen
