### ISSUE TITLE
DOC: Fix and extend ParserError docstring

### ISSUE THREAD

**Issue by cancan101** [pandas-dev/pandas#22881]
[`ParserError` says](https://github.com/pandas-dev/pandas/blob/8e51fd38607e94524b66ba15002e2502240baa32/pandas/errors/__init__.py#L35):
>Exception that is raised by an error encountered in `pd.read_csv`

however, it seems to be raised at least by html parsing, and perhaps other parsers as well: https://github.com/pandas-dev/pandas/blob/486e626bd3e7282b3da9993807f6246ef3ddda76/pandas/tests/io/test_html.py#L820-L829

As higher level point, it would be great if the list of potential runtime exceptions raised by the the various parsers were documented in the docs.

**Comment by WillAyd** [comment]
Thanks for this - PRs to update documentation are certainly welcome!

**Comment by RjLi13** [comment]
Hey, can I contribute to help fix this issue if no one else has yet?

**Comment by thoo** [comment]
@RjLi13  Look like nobody is working on it. Go for it.
