### ISSUE TITLE
DOC: Fix the docstring of groupby in pandas/core/generic.py

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#22893]
pandas docstring are expected to follow the format defined in https://pandas.pydata.org/pandas-docs/stable/contributing_docstring.html

This includes among other things:
- There is a short description fitting in one line (there can be a longer one after that).
- The description of the parameters, the returns section, and the see also items, starts with a capital letter and ends with a period.
- In the Return section there is no name before the type (e.g. `transformed : Series`) but just the type (e.g. `Series`) in the first line.
- The examples are valid PEP-8 code, and when executed, they produce the shown input.

We should make the required adjustments in the docstring of the function `groupby` in `pandas/core/generic.py`.

We should validate the docstring with our validator (which does not validate all the formats, but some):
- `./scripts/validate_docstrings.py pandas.Series.groupby`

And we should validate the PEP-8 of the examples (note that the next command will validate the PEP-8 of all examples, just make sure that none of the shown is in the function being addressed, the rest will be fixed in separate issues):
- `flake8 --doctests pandas/core/generic.py`

**Comment by tonytao2012** [comment]
Would it be okay if I took this one?

**Comment by datapythonista** [comment]
Feel free to pick any that nobody is working on it @tonytao2012, but please just pick one at a time, I see you also said you'd work on resample. And those may be not as fast as you may thing. Let's leave it available for someone else for now if that's all right, and when you finish with resample, surely feel free to continue with this one if nobody is working on it.

Does this make sense?

**Comment by tonytao2012** [comment]
Whoops, sorry! Sounds good, but I can continue working on groupby instead of resample, as I'm farther ahead in this one.

**Comment by datapythonista** [comment]
No worries, not a problem at all, I was just explainng.

And absolutely, just have updated comments in both, so everybody knows which one are you working on, and which is free :)
