### ISSUE TITLE
DOC: Fix the docstring of to_stata in pandas/core/frame.py

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#22896]
pandas docstring are expected to follow the format defined in https://pandas.pydata.org/pandas-docs/stable/contributing_docstring.html

This includes among other things:
- There is a short description fitting in one line (there can be a longer one after that).
- The description of the parameters, the returns section, and the see also items, starts with a capital letter and ends with a period.
- In the Return section there is no name before the type (e.g. `transformed : Series`) but just the type (e.g. `Series`) in the first line.
- The examples are valid PEP-8 code, and when executed, they produce the shown input.

We should make the required adjustments in the docstring of the function `to_stata` in `pandas/core/frame.py`.

We should validate the docstring with our validator (which does not validate all the formats, but some):
- `./scripts/validate_docstrings.py pandas.DataFrame.to_stata`

And we should validate the PEP-8 of the examples (note that the next command will validate the PEP-8 of all examples, just make sure that none of the shown is in the function being addressed, the rest will be fixed in separate issues):
- `flake8 --doctests pandas/core/frame.py`

**Comment by leeyspaul** [comment]
Working on this issue, referenced from #228999.

**Comment by datapythonista** [comment]
@leeyspaul are you working on this? I don't think anyone else is finally working on it.

**Comment by ryankarlos** [comment]
@datapythonista is this issue still open ? I would like to work on it if it is - otherwise, any other ones still open (most DOC issues seem taken) ?

**Comment by ryankarlos** [comment]
@datapythonista Thanks. Just to clarify, I don't see a returns sections currently included in the to_stata docstring - did you want that added in presumably rather than modified ?

**Comment by ryankarlos** [comment]
Thanks, will do !

**Comment by ryankarlos** [comment]
@datapythonista Just submitted a PR, let me know if there are any modifications required.
