### ISSUE TITLE
DOC: Fix the docstring of itertuples in pandas/core/frame.py

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#22899]
pandas docstring are expected to follow the format defined in https://pandas.pydata.org/pandas-docs/stable/contributing_docstring.html

This includes among other things:
- There is a short description fitting in one line (there can be a longer one after that).
- The description of the parameters, the returns section, and the see also items, starts with a capital letter and ends with a period.
- In the Return section there is no name before the type (e.g. `transformed : Series`) but just the type (e.g. `Series`) in the first line.
- The examples are valid PEP-8 code, and when executed, they produce the shown input.

We should make the required adjustments in the docstring of the function `itertuples` in `pandas/core/frame.py`.

We should validate the docstring with our validator (which does not validate all the formats, but some):
- `./scripts/validate_docstrings.py pandas.DataFrame.itertuples`

And we should validate the PEP-8 of the examples (note that the next command will validate the PEP-8 of all examples, just make sure that none of the shown is in the function being addressed, the rest will be fixed in separate issues):
- `flake8 --doctests pandas/core/frame.py`

**Comment by leeyspaul** [comment]
Hi! I'd like to take this up if it's still open.

**Comment by datapythonista** [comment]
Sure, all yours! Let us know if you need help. Looking forward to your pull request.

**Comment by datapythonista** [comment]
Fixed in #22902
