### ISSUE TITLE
pd.read_json produces a dataframe that causes segfaults

### ISSUE THREAD

**Issue by Pastafarianist** [pandas-dev/pandas#22909]
#### Code Sample, a copy-pastable example if possible

Download [this dataset](https://www.dropbox.com/s/99az9n1b57qkd9j/arxivData.json.tar.gz?dl=1) ([alternative link](https://yadi.sk/d/_nGyU2IajjR9-w)). Unpack it. Then

```python
import pandas as pd
df = pd.read_json('arxivData.json')
print(df.head(n=1))
```

This causes a segfault on my machine. More generally, segfaults are triggered whenever I attempt to perform any operation on this dataframe.

#### Output of ``pd.show_versions()``

<details>

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Linux
OS-release: 4.14.71-1-MANJARO
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 3.8.0
pip: 18.0
setuptools: 40.2.0
Cython: 0.28.5
numpy: 1.15.1
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.5.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
```

</details>

**Comment by Pastafarianist** [comment]
I cannot easily test on other versions of Python as there is no easy mechanism on Arch to use multiple versions of Python simultaneously (similar to Gentoo's `eselect`), or I am not aware of such mechanisms.

**Comment by TomAugspurger** [comment]
You can use conda to manage multiple versions of python in userland: https://conda.io/miniconda.html

Let's assume it's the same as #22817, and we'll reopen if you can reproduce with other versions.
