### ISSUE TITLE
Avoid listifying left/right operand in ExtensionArray ops dispatching

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#22922]
We now have the follow code in the ExtensionArray ops dispatching:

https://github.com/pandas-dev/pandas/blob/2f1b842119bc4d5242b587b62bde71d8f7ef19f8/pandas/core/ops.py#L1169-L1192

There are a few places where we convert the values to a list, which should be avoided.

**Comment by TomAugspurger** [comment]
This specific case of `Series[EA] + EA`  (where the EAs are the same type) seems very easy to handle.

**Comment by jorisvandenbossche** [comment]
Looking at the code, it seems that that case is already working OK, *if* the `type(EA)` is equal.

**Comment by TomAugspurger** [comment]
Hmm is it? I thought that's what cased the NameError. I think we need something like `type(new_left) is type(right)`, where new_left has unboxed the EA from the Series. Haven't looked closely though.

**Comment by jorisvandenbossche** [comment]
Yes, it's what caused the NameError, but this is about the conversion to list?

**Comment by TomAugspurger** [comment]
Correct. I'm saying we shouldn't even reach that `elif` in the case of Series[EA] + EA.

```
elif is_extension_array_dtype(right) and type(new_left) == type(right):
    # EA + EA. This is new.
    new_right = right
elif is_extension_array_dtype(right) and type(left) != type(right):
    new_right = list(right)
```

**Comment by TomAugspurger** [comment]
Corner case in pandas master with object-dtype

```python
In [1]: import pandas as pd

In [2]: 1 ** pd.Series([None], dtype=object)
Out[2]:
0    NaN
dtype: object
```

That's supposed to be `1`, since `1 ** anything` is `1`

```python
In [4]: 1 ** pd.Series([np.nan])
Out[4]:
0    1.0
dtype: float64

```

**Comment by jorisvandenbossche** [comment]
@TomAugspurger is that related to the listifying?

**Comment by TomAugspurger** [comment]
Whoops, got my issues mixed up. That was for https://github.com/pandas-dev/pandas/issues/22022
