### ISSUE TITLE
BLD: wheel building failing

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#22924]
https://travis-ci.org/MacPython/pandas-wheels/jobs/435426572

cc @TomAugspurger

**Comment by jorisvandenbossche** [comment]
Issue is discussed here: https://github.com/matthew-brett/multibuild/issues/202

**Comment by bashtage** [comment]
Need to pin wheel to 0.31.1

**Comment by jreback** [comment]
build works now, only 32-bit failing: https://travis-ci.org/MacPython/pandas-wheels/builds/439958108
