### ISSUE TITLE
API: add a setattr method to NDFrame to assist with piping

### ISSUE THREAD

**Issue by topper-123** [pandas-dev/pandas#22933]
I frequently come into situations where I have to break up piping, because piping doesn't work on attributes:

```python
>>> new_df = (df.groupby(...)
...             .pipe(...)
>>> new_df.index.name = 'index_name'
>>> new_df.columns = pd.CategoricalIndex(new_df.columns)
>>> new_df = new_df.pipe(...)  # and so on...
```

I think it would be cleaner if NDFrame had a ``setattr`` method that returns ``self``. Then the above would become:

```python
>>> new_df = (df.groupby(...)
...             .pipe(...)
...             .setattr('index.name', 'index_name')
...             .setattr('columns', lambda x: pd.CategoricalIndex(x.columns))
...             .pipe(...)  # and so on...
...             )
```

The first argument to ``.setattr`` is a string and can be dot-seperated, and the second parameter is called with ``self`` as its first argument if a callable.

I think this would make piping cleaner in many cases.

Opinions?

**Comment by mroeschke** [comment]
There's already `rename_axis` and `set_axis` for your index naming and setting of columns examples respectively that can be chained.

Are there any other attributes that don't have a corresponding method? I can't think of one off the top of my head.

**Comment by topper-123** [comment]
``set_axis`` can not take a function with ``self`` as its argument, so various operations are not possible without breaking the pipe. Though a callable could of course be allowed in ``set_axis`` and that would work also.

So for example, I don't think (having a DateTimeIndex) ``new_df = df.pipe(...).setattr('index', lambda x: x.index.year)`` is possible currently without breaking the pipe?

**Comment by jschendel** [comment]
Can you do `set_axis` inside a `pipe` to achieve that?

```python
In [2]: df = pd.DataFrame({'A': pd.date_range('2017', periods=2, freq='A').repeat(2),
   ...:                    'B': range(4),
   ...:                    'C': [10, 20, -10, 5]})
   ...:

In [3]: df
Out[3]:
           A  B   C
0 2017-12-31  0  10
1 2017-12-31  1  20
2 2018-12-31  2 -10
3 2018-12-31  3   5

In [4]: new_df = df.groupby('A') \
   ...:            .pipe(lambda x: x.max() - x.min()) \
   ...:            .pipe(lambda df: df.set_axis(df.index.year, inplace=False)) \
   ...:            .rename_axis('foo') \
   ...:            .pipe(lambda df: df.set_axis(pd.Categorical(df.columns), axis=1, inplace=False))
   ...:

In [5]: new_df
Out[5]:
      B   C
foo
2017  1  10
2018  1  15

In [6]: new_df.columns
Out[6]: CategoricalIndex(['B', 'C'], categories=['B', 'C'], ordered=False, dtype='category')

In [7]: new_df.index
Out[7]: Int64Index([2017, 2018], dtype='int64', name='foo')
```

**Comment by mroeschke** [comment]
Overall I feel -1 on the idea of a generic `setattr` method. I would rather have `set_axis` (or any analogous method) to operate on `self` then have a `setattr` method able to modify _anything_ on the frame.

**Comment by topper-123** [comment]
Closing. I don't feel there is support for this.
