### ISSUE TITLE
Document module privacy

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#22942]
We should better document what in pandas is considered private.

http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#reorganization-of-the-library-privacy-changes should be captured somewhere more permanent than in a whatsnew release. source is at https://github.com/pandas-dev/pandas/blob/master/doc/source/whatsnew/v0.20.0.txt#L1194

I think a new section in http://pandas-docs.github.io/pandas-docs-travis/overview.html is the best place for it.

**Comment by pecey** [comment]
Hi. I can pick this up!

If I understand correctly, we want the "Modules Privacy Has Changed" section to go into a new section on the Overview page. Is my understanding correct?

**Comment by TomAugspurger** [comment]
That's correct. Some of the phrasing may need to be updated, and you don't have to say anything about "new location", since this is going in the stable docs.

**Comment by datapythonista** [comment]
Closing, see #23038
