### ISSUE TITLE
How to ignore the second white space in a row when the delimiter is set to whitespace

### ISSUE THREAD

**Issue by javedshaikm** [pandas-dev/pandas#22955]
```python
import pandas as pd
data = pd.read_csv('D:\\python\\python-cisco-status.txt', delim_whitespace=True, header=None)
for index, row in data.iterrows():
	if row[4] == 'administratively down' or row[4] == 'down':
		print(f"Interface {row[0]} is down in ")
```
#### Problem description
I am trying to read the below data frame in a text file, using whitespace as a delimiter in columns, but there is a extra white space in the rows due to which I am getting errors:

Interface              IP-Address      OK? Method          Status                          Protocol
GigabitEthernet1       10.10.20.48     YES NVRAM     up                                up      
GigabitEthernet2       unassigned      YES NVRAM   administratively down   down    
GigabitEthernet3       unassigned      YES NVRAM   administratively down   down   

The words "administratively down" in the column status need to be considered as a single word with a space in between both the adminstratively and down, however I am getting this error when reading this data in pandas:
pandas.errors.ParserError: Error tokenizing data. C error: Expected 6 fields in line 3, saw 7

#### Expected Output
I alm looking to read the above mentioned data in pandas, so I can read row by row and check if any interface is down.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 32
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.0
pytest: 3.5.1
pip: 18.0
setuptools: 39.1.0
Cython: 0.28.2
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
None
[Finished in 8.9s]

</details>

**Comment by jschendel** [comment]
Please use StackOverflow for all usage questions.  The GitHub issue tracker should be used for reporting bugs or requesting enhancements.
