### ISSUE TITLE
Assigning a value to a series with a tz-aware timestamp during DST switch raises AmbiguousTimeError

### ISSUE THREAD

**Issue by mirkoha** [pandas-dev/pandas#22989]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
series = pd.Series(data=[1,2,3], index=pd.DatetimeIndex(start='2017-10-29 00:30',
                                                        end='2017-10-29 1:30',
                                                        tz='Europe/Berlin',
                                                        freq='30 min'))
t=pd.Timestamp('2017-10-29 2:00+2:00', tz='Europe/Berlin')
series[t] = 1

# AmbiguousTimeError: Cannot infer dst time from '2017-10-29 02:00:00',
# try using the 'ambiguous' argument
```
#### Problem description

AmbiguousTimeError is raised when assigning a value to a new entry in a series although the timestamp is unique. This bug may be linked to #21761.

#### Expected Output
No error.
#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: None.None

pandas: 0.23.4
pytest: 3.2.5
pip: 10.0.1
setuptools: 39.2.0
Cython: None
numpy: 1.14.5
scipy: 1.1.0
pyarrow: None
xarray: 0.10.8
IPython: 6.5.0
sphinx: 1.7.5
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: 3.4.4
numexpr: 2.6.5
feather: None
matplotlib: 2.2.3
openpyxl: 2.5.6
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.8
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: 1.2.11
pymysql: None
psycopg2: 2.7.5 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by TomAugspurger** [comment]
Can you try on master/ That works for me.

```python
In [27]: import pandas as pd
    ...: series = pd.Series(data=[1,2,3], index=pd.DatetimeIndex(start='2017-10-29 00:30',
    ...:                                                         end='2017-10-29 1:30',
    ...:                                                         tz='Europe/Berlin',
    ...:                                                         freq='30 min'))
    ...: t=pd.Timestamp('2017-10-29 2:00+2:00', tz='Europe/Berlin')
    ...: series[t] = 1
    ...:

In [28]:

In [28]: series
Out[28]:
2017-10-29 00:30:00+02:00    1
2017-10-29 01:00:00+02:00    2
2017-10-29 01:30:00+02:00    3
2017-10-29 02:00:00+02:00    1
Freq: 30T, dtype: int64
```

**Comment by mirkoha** [comment]
Thanks for the quick reply. Using the current master solves this problem. Thank you.
