### ISSUE TITLE
API: Expose groupby API for fast custom calculations

### ISSUE THREAD

**Issue by tunnij** [pandas-dev/pandas#23008]
Currently code such as:
`df.groupby(['col1', 'col2']).mean()`

Is heavily optimized as it has access to the internal blocks and can use a cython based function to execute. If a custom calculation is required (for example root-mean-squared-error) then the only current option is to use:
`df.groupby(['col1', 'col2']).apply(my_func)`

It would be good to be able to supply a cythonized or numba jit compiled function which is given the numpy arrays for each group or even all the blocks so the looping can all happen in the compiled function.

The other current alternative is to take the values of the dataframe and implement your own grouping but I feel pandas already has this bit covered well.

**Comment by jreback** [comment]
``.apply`` already accepts a ufunc and defers to it, have you tried? can you show a complete usecase

**Comment by tunnij** [comment]
I'll come up with some runnable code but will take a look at ufunc and what I can do with the group indexers.

The original situation I had was that I had a large dataframe (approx. 40 million rows) and was trying to perform an idxmin() on the groups. The performance of idxmin() vs just a regular min() was quite quite large and so I wanted to see what I could do to speed it up.

The original code looked something like this (original_df has an int index a, b, c are strings, d is a float):
`original_df.loc[original_df.groupby(['a', 'b', 'c'])['d'].idxmin()]`

Two things that I observed:

1. the idxmin() call itself is quite slow. For my dataset approx. 1 minute vs running .min() taking approx. 10 seconds.
2. performing the .loc with the resulting multiindexed pd.Series is slow when compared to indexing with a pd.Series constructed from the ints with no index on it.

Number lead me to believe that as the implementation of groupby.min is cyhonized that I might be able to achieve similar performance with numba compiled func being given just the int index values and the values of my column 'd'.

**Comment by mroeschke** [comment]
Feel free to reopen when you can post a runable code example.
