### ISSUE TITLE
openpyxl depreciation warning

### ISSUE THREAD

**Issue by cychu5** [pandas-dev/pandas#23006]
With python 2.7.14, the following code

```df.to_excel('output.xlsx')```

produces the following warning:

`/Users/cychu/Library/Python/2.7/lib/python/site-packages/pandas/io/excel.py:784: DeprecationWarning: Call to deprecated function remove_sheet (Use wb.remove(worksheet) or del wb[sheetname]).
  self.book.remove_sheet(self.book.worksheets[0])`

**Comment by WillAyd** [comment]
Please refer to the contributing guide on effective bug reports:

https://pandas.pydata.org/pandas-docs/stable/contributing.html#bug-reports-and-enhancement-requests

There isn't enough info here to debug (mainly missing `pd.show_version()` but my assumption is that you are using openpyxl <= 2.4 which will hit the branch in code with the call to `remove_sheet`.

If that's not the case please reopen with the information per the contributing guideline.

Related to #15090
