### ISSUE TITLE
Make DataFrame.dtypes return Categorical

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#23017]
I found myself wanting to check if `df.dtypes` contained any integer dtypes.  The intuitive usage would be:

```
df.dtypes.kind == 'i'
```

There are easy workarounds for this, but it would be convenient if `df.dtypes` returned a Categorical so this could be made to work.

**Comment by jreback** [comment]
doesnt' ``.select_dtypes(incude=['integer'])`` work? and is more idiomatic? we are trying not to use the numpy idioms here (becuase they actually break), e.g. try doing ``df.dtypes=='int'`` with non-numpy dtypes
