### ISSUE TITLE
Bug in tseries.offsets.BDay

### ISSUE THREAD

**Issue by vss888** [pandas-dev/pandas#23012]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
minRangeDate = '2015-12-28'
maxRangeDate = '2016-01-04'
nDays=0
for date in pd.date_range(start=minRangeDate, end=maxRangeDate):
    dateRange = (date.date(), (date+pd.tseries.offsets.BDay(nDays)).date())
    #dateRange = (date, date+pd.tseries.offsets.BDay(nDays))
    print(str(dateRange[0]), str(dateRange[1]))
```

gives

> 2015-12-28 2015-12-28
> 2015-12-29 2015-12-29
> 2015-12-30 2015-12-30
> 2015-12-31 2015-12-31
> 2016-01-01 2016-01-01
> **2016-01-02 2016-01-04**
> **2016-01-03 2016-01-04**
> 2016-01-04 2016-01-04

#### Problem description

Adding zero number of business days to a date should not change the date.

#### Expected Output

`(date+pd.tseries.offsets.BDay(0))==date` for any input date

#### Output of ``pd.show_versions()``

<details>
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-693.17.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.utf-8
LANG: en_US.utf-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 3.3.2
pip: 18.0
setuptools: 39.0.1
Cython: 0.27.3
numpy: 1.14.5
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.6.6
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: None
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 3.0.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.9999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by JustinZhengBC** [comment]
Those two days are weekends, so it's understandable why this would occur. If a task "can be completed on the same business day" but is requested on a weekend, it won't be completed until Monday. This behaviour appears to be intended, according to [this test](https://github.com/pandas-dev/pandas/blob/8af8cdbc251c6268fc02a5af9b18e9196a9b6067/pandas/tests/tseries/offsets/test_offsets.py#L689).

**Comment by jschendel** [comment]
Yes, I believe this is the intended behavior. In addition to the test, this behavior is consistent with the [Anchored Offset Semantics](https://pandas.pydata.org/pandas-docs/stable/timeseries.html#anchored-offset-semantics) section of the docs.  Specifically, the last paragraph states:
>For the case when `n=0`, the date is not moved if on an anchor point, otherwise it is rolled forward to the next anchor point.
>```python
>In [218]: pd.Timestamp('2014-01-02') + MonthBegin(n=0)
>Out[218]: Timestamp('2014-02-01 00:00:00')
>
>In [219]: pd.Timestamp('2014-01-02') + MonthEnd(n=0)
>Out[219]: Timestamp('2014-01-31 00:00:00')
>
>In [220]: pd.Timestamp('2014-01-01') + MonthBegin(n=0)
>Out[220]: Timestamp('2014-01-01 00:00:00')
>
>In [221]: pd.Timestamp('2014-01-31') + MonthEnd(n=0)
>Out[221]: Timestamp('2014-01-31 00:00:00')
>```

**Comment by vss888** [comment]
This logic does not make any sense to me for n=0. It makes sense to skip weekend if n=1, but not not if n=0. Zero means zero, i.e. adding it should not change the input: a+0==a.

In your logic, zero is zero on weekdays, but it is one on weekends.

**Comment by hermanc1** [comment]
This is quite an important "gotcha". It should be added to the documentation.
