### ISSUE TITLE
Grouping Issue and gspread U

### ISSUE THREAD

**Issue by Arumugapandian** [pandas-dev/pandas#23027]
Hello Everyone,

Kindly find the image below represents the required input data and output requirement of my study.
![capture](https://user-images.githubusercontent.com/43292227/46584127-13fef980-ca7d-11e8-95b2-25ffc30e42ac.PNG)

I am using Pandas data frame to achieve my output requirement. Facing two major issues to find the solutions for my output sheet.
1. Grouping data-frame is working properly but how to achieve the size of grouping and sum of grouping 
2. Finally the grouped data are sent back to google sheets, it's working properly only for single actions either sum or size of files. How to do this for both?

Kindly find the code below which I used
############
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import pandas as pd

# use creds to create a client to interact with the Google Drive API
scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']
creds = ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope)
client = gspread.authorize(creds)

# Find a workbook by name and open the first sheet
# Make sure you use the right name here.
sheet=client.open("Status_Sheet_Final").sheet1
 
#extract columns, python starts counting at 0 but google sheets starts at 1
status_sheet = sheet.get_all_records()
print(status_sheet)

#delete the columns
df = pd.DataFrame(status_sheet)
del df ['End Time']
del df ['Start Time']
df

#group the data 
count1_df = df.groupby(['Employee']).count()
count1_df

#write the grouped data to google sheets
from df2gspread import df2gspread as d2g
wks_name = 'Daily'
spreadsheet_key = '#################'
d2g.upload(count1_df, spreadsheet_key, wks_name, credentials=creds, row_names=True)

**Comment by WillAyd** [comment]
This board is used for bug reports and enhancement requests. For usage questions you are better off asking on SO or Gitter

**Comment by Arumugapandian** [comment]
Thanks for your response
