### ISSUE TITLE
np.random.permutation(DatetimeIndex) modifies argument in numpy 1.15

### ISSUE THREAD

**Issue by frexvahi** [pandas-dev/pandas#23058]
I'm not sure whether this counts as a numpy bug or a pandas bug

#### Code Sample

```python
import numpy as np
import pandas as pd

index = pd.DatetimeIndex(start='2017-01-01', end='2017-02-01', freq='1d')
index_copy = index.copy(deep=True)
random_index = pd.DatetimeIndex(np.random.permutation(index))
pd.testing.assert_index_equal(index, index_copy)
```
#### Problem description

The behaviour with numpy 1.14 is correct - the original index is not modified. In numpy 1.15 the original index is modified and the `assert_index_equal` will fail.

When passing numpy arrays to `np.random.permutation` the input is not modified in either numpy version, this means that passing `index.values` instead of `index` to `np.random.permutation()` can be used as a workaround.

#### Output of ``pd.show_versions()`` in numpy 1.14 environment

<details><pre>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-34-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.23.4
pytest: 3.7.1
pip: 10.0.1
setuptools: 40.0.0
Cython: 0.28.5
numpy: 1.14.5
scipy: 1.1.0
pyarrow: None
xarray: 0.10.8
IPython: 6.5.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: 3.4.3
numexpr: 2.6.7
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</pre></details>

#### Output of ``pd.show_versions()`` in numpy 1.15 environment

<details><pre>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-34-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.23.4
pytest: 3.8.1
pip: 10.0.1
setuptools: 40.2.0
Cython: 0.28.5
numpy: 1.15.2
scipy: 1.1.0
pyarrow: None
xarray: 0.10.9
IPython: 7.0.1
sphinx: None
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.0
openpyxl: 2.5.8
xlrd: 1.1.0
xlwt: None
xlsxwriter: 1.1.1
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</pre></details>

**Comment by jschendel** [comment]
Looks to be fixed on the numpy side, and should be included in the 1.15.3 release: https://github.com/numpy/numpy/issues/11975

Closing as this has been resolved on the numpy side; feel free to reopen if you feel there's some modification we should make internally though.
