### ISSUE TITLE
Remove unused asv directives and verify in the CI that we are not using them

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#23075]
Some of the directives being used in our benchmarks (`asv_bench/benchmarks/`) are deprecated in asv. e.g. in `algorithms.py` each of the benchmark classes defines `goal_time` (e.g. https://github.com/pandas-dev/pandas/blob/master/asv_bench/benchmarks/algorithms.py#L18), but it looks like asv just ignores that: https://asv.readthedocs.io/en/stable/benchmarks.html#benchmark-attributes

We should update the benchmarks to not include unused asv directives, and we should add to `./ci/code_checks.py` a way to identify if unused ones are being used (ideally getting the list of expected directives from `asv` itself).

Originally from https://github.com/pandas-dev/pandas/issues/22884#issuecomment-425657882

@jbrockmendel can you review the issue description and edit if needed please

**Comment by jbrockmendel** [comment]
Looks right to me.  @pv any thoughts on how best to handle this?  Would it make sense to implement these checks within asv?

**Comment by eriknil** [comment]
I'll take a look at this

**Comment by cpcloud** [comment]
Working with @eriknil at PyData NYC 2018 mini-sprints.

I don't think that it's possible to determine whether unused directives are being used. The set of unused asv directives is infinite and includes any attribute on the object that isn't one that is recognized by asv.

Are you proposing limiting the class variables that can be defined?

For example, how is it possible to know that `goal_time` was intended to be used by asv and isn't just an attribute used by something else on the class?
