### ISSUE TITLE
operator overloading when a Pandas series  contains  objects (Pyomo Var or Expressions)

### ISSUE THREAD

**Issue by maajdl** [pandas-dev/pandas#23071]
### This inequality expression on a series triggers an exception:

```python
(stocks.decisions.decision <= 1000)
```
##### When the types of the objects are as follows:
```python
type(stocks.decisions)                  ==> pandas.core.frame.DataFrame
type(stocks.decisions.decision)         ==> pandas.core.series.Series
type(stocks.decisions.decision.loc[1])  ==> pyomo.core.base.var._GeneralVarData

```
#### By contrast, this sum expression works perfectly:

```python
(stocks.decisions.decision + 1000)
```
since it returns a series of  Pyomo   _SumExpression
```python
type((stocks.decisions.decision + 1000)[0])    ==>    pyomo.core.kernel.expr_coopr3._SumExpression
```
#### Note also that the following expression doesn't return an exception, but the result is unexpected:

```python
(stocks.decisions.decision == 1000)
```
as it returns a series of  False  boolean values.
Based on the previous behaviour, I would have expected a series of pyomo.core.kernel.expr_coopr3._EqualityExpression  .

### My expectations were:
that all expression tested above would return Pyomo expressions, just as in the case of an addition.
This would be consistent from my point of view.
And furthermore, this would be exactly what I wanted to do!
My aim was to create several series of  Pyomo  expressions built from Pandas queries and to use them to build a linear programming model.  (queries involving joins and longer expressions than above)

### My questions would be:

- For my understanding, should that be the correct behaviour of Pandas, of rather a bug?
- What should I do to work around this problem? Of course there are many solutions, but operator overloading would be far beter, because of more readable code this leads to.
- Would that be a bad idea if I created my own overloads? I think so, but expert advice would be nice.

Thanks!

Michel

PS

Same question posted on the Pyomo forum, but formulated from the Pyomo pov.
https://groups.google.com/forum/#!topic/pyomo-forum/wXYnfXlty4U

**Comment by TomAugspurger** [comment]
I'm not familiar with pyomo, but they should probably implement an ExtensionDtype and ExtensionArray: http://pandas-docs.github.io/pandas-docs-travis/extending.html#extension-types

Binary ops between data frames / series with ExtensionArrays should be supported correctly on master.

**Comment by TomAugspurger** [comment]
I'm going to close this, since I don't think there's anything specific for pandas to do. If you or someone else implements an extension array for pyomo, we can add it to http://pandas-docs.github.io/pandas-docs-travis/ecosystem.html#extension-data-types
