### ISSUE TITLE
It is not clear whether database connection need to be closed manually after calling pd.read_sql()

### ISSUE THREAD

**Issue by FukoH** [pandas-dev/pandas#23086]
The document does not mention it.

**Comment by verascity** [comment]
I think this is a good point. Maintainers, correct me if I'm wrong (I'm a new contributor), but I believe it does have to be manually closed. I had to search for a bit to verify that, though.

If confirmed, could I take on clarifying in the docs?

**Comment by CalmDownKarm** [comment]
If I understand correctly, you shouldn't need to manually close connections, sqlalchemy's create_engine() essentially handles connections through a connection pool automatically. calling dispose() on a create_engine()'d object will just replace it with an empty connection pool. [sqlalchemy docs](https://docs.sqlalchemy.org/en/latest/core/connections.html)

**Comment by CalmDownKarm** [comment]
@verascity are you planning on submitting a PR for this?

**Comment by verascity** [comment]
I'd like to, yes! Just wanted to get it pinned down before I do it.

**Comment by TomAugspurger** [comment]
I think we're OK for this specific issue: pandas doesn't do anything to open or close your database connections. That's left up to the user / underlying object. A link to the sqlalchemy docs on this subject should be included.

**Comment by emattiza** [comment]
I'll take a shot at getting this one documented!

**Comment by cruzzoe** [comment]
[https://github.com/pandas-dev/pandas/pull/29363](url)

**Comment by felipedmc** [comment]
Hey there! Some years later... no explict engine, conection or cursor, and my code goes something like:

lazydummy = pandas.read_sql(sql= 'SELECT * FROM somewhere, con= 'postgre://blablabla')
.
. #doing stuff with my dataframe
.
display(lazydummy.head() #BREAKPOINT HERE!
END OF SCRIPT

At the break point, I alt+tab to my pgadmin 4 and the conection was there, opened. Back to my phyton code, finished running it, gone back to pgadmin and the conection was not there anymore on my db dashboard. Guess it just autocloses when the script is over.
