### ISSUE TITLE
DatetimeIndex._use_cached_range, _cached_range not reachable

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#23080]
Because `freq._should_cache()` is always False.

My inclination would be to get rid of use_cached_range and cached_range (as opposed to enabling it)

**Comment by mroeschke** [comment]
I am partial to removing it as well (and possible some related cruft in `tseries/offsets.py`. But there's also an issue about re-enabling caching: https://github.com/pandas-dev/pandas/issues/17914
