### ISSUE TITLE
Improve doc/README.rst

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#23084]
The README within the doc directory still makes a reference to rebasing, though current preferred method is to merge in updates from master. Additionally there is a reference to `python make.py build` which doesn't do anything by default.

Items here can certainly be improved for clarification to new contributors

**Comment by alexander-l-stone** [comment]
Hey, I put in a PR with the git process updated. I am not sure it needs the command for setting the upstream, but I included it anyway.

**Comment by ChrisSeattle** [comment]
I tried to install based on the instructions in the doc/README.rst. Following the instructions from @alexander-l-stone helps move forward, but there seem to be additional errors in the "Building the documentation" section at this command: 
```python make.py html ``` 
After installing dependencies I eventually got an error that Pandoc was not installed after it was just installed.

**Comment by WillAyd** [comment]
@ChrisSeattle tough to say from that alone. Could you post the traceback?

**Comment by ChrisSeattle** [comment]
I am in a pipenv. 
```
$ python make.py html
Warning: Pandoc is not installed. Skipping notebooks.
Running Sphinx v1.8.1
sphinxcontrib.spelling failed to import with error "No module named 'sphinxcontrib.spelling'". `spellcheck` command is not available.

Extension error:
Could not import extension matplotlib.sphinxext.plot_directive (exception: No module named 'matplotlib')
```

**Comment by WillAyd** [comment]
We don't have instructions posted for pipenv. Should be possible though still tough to say without knowing more about your environment. I believe `sphinxcontrib.spelling` is a warning whereas the error at the end suggests you don't have Matplotlib installed in your virtual environment.

Have you tried the instructions on the more general contributing guide to set up your environment?

https://pandas.pydata.org/pandas-docs/stable/contributing.html#creating-a-python-environment

**Comment by datapythonista** [comment]
Closing in favor of #23828.
