### ISSUE TITLE
Implement/dispatch unary operations for ExtensionArrays

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#23087]
xref https://github.com/pandas-dev/pandas/pull/22325/files#r220580694

unary ops are not implemented by EAs and also not dispatched to EAs:

```
In [161]: s = pd.Series([1, 2, 3], dtype='Int64')

In [162]: -s
Out[162]: 
0    -1
1    -2
2    -3
dtype: object
```

**Comment by jorisvandenbossche** [comment]
Moved to 0.25.0 milestone

**Comment by TomAugspurger** [comment]
Probably not a blocker for 1.0 right?

**Comment by mroeschke** [comment]
Looks like this got implemented at some point. Probably good to see if there are tests

```
In [11]: s = pd.Series([1, 2, 3], dtype='Int64')

In [12]: -s
Out[12]:
0    -1
1    -2
2    -3
dtype: Int64
```

**Comment by jbrockmendel** [comment]
`__pos__`, `__neg__`, `__invert__`, `__abs__` all dispatch.  Closing.
