### ISSUE TITLE
astype_nansafe int to float with copy=False produces incorrect result

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#23092]
I haven't investigated this at all. Maybe it's expected

```python
In [6]: pd.core.dtypes.cast.astype_nansafe(a, float)
Out[6]: array([1., 2., 3.])

In [7]: pd.core.dtypes.cast.astype_nansafe(a, float, copy=False)
Out[7]: array([4.9e-324, 9.9e-324, 1.5e-323])
```

To whoever maybe fixes this in the future, `_sparse_array_ops` in `sparse/array.py` would like to use `copy=False` somewhere around

```python
        left = left.astype(ltype)
        right = right.astype(rtype)
        dtype = ltype.subtype
```

**Comment by GMarzinotto** [comment]
The docs for this function say

def astype_nansafe(arr, dtype, copy=True):
    """ return a view if copy is False, but
        need to be very careful as the result shape could change!
    Parameters
    ----------
    arr : ndarray
    dtype : np.dtype
    copy : bool, default True
        If False, a view will be attempted but may fail, if
        e.g. the itemsizes don't align.
    """

If nobody is working on this issue I can give it a try !

**Comment by jorisvandenbossche** [comment]
This was closed by https://github.com/pandas-dev/pandas/pull/38835
