### ISSUE TITLE
Pandas PDF documentation: Last page has missing reference question marks

### ISSUE THREAD

**Issue by 1kastner** [pandas-dev/pandas#23103]
#### Problem description

The last page of the pandas documentation (as a PDF) contains a broken reference in the `Python Module Index`, namely `pandas, ??`. Those two question marks don't belong there I guess.

See https://pandas.pydata.org/pandas-docs/stable/pandas.pdf

**Comment by TomAugspurger** [comment]
Any interest in investigating why that's showing up there? Do you think it's a pandas or sphinx issue?

**Comment by 1kastner** [comment]
I guess it is because latex is not run three times (the `force` option).
See https://github.com/pandas-dev/pandas/blob/master/doc/make.py
I do not really know how the PDF arrives at the website which is part of https://github.com/pandas-dev/pandas-website -- I guess the one who solves this should know about the pipeline how things get to the website.

**Comment by TomAugspurger** [comment]
That's all at https://github.com/pandas-dev/pandas-release.

https://github.com/pandas-dev/pandas-release/blob/master/scripts/build-docs.sh
should be doing forced, but I think there was an issue with the docs last
time I built them. Will check next time around.

**Comment by 1kastner** [comment]
After #23257 was resolved I had a brand new documentation with `latex_forced` in my hands.
On the last page there is the _PYTHON MODULE INDEX_ with one entry which is _pandas_ and a working reference.

**Comment by 1kastner** [comment]
I just checked https://pandas.pydata.org/docs/pandas.pdf and everything seems fine again.
