### ISSUE TITLE
pandas.pydata.org Display >pandas.DataFrame.sample

### ISSUE THREAD

**Issue by shuiyuejihua** [pandas-dev/pandas#23102]
####  pandas.pydata.org Display error
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sample.html

![image](https://user-images.githubusercontent.com/31531236/46865226-4af35780-ce4f-11e8-9a1e-e266829b5cc8.png)

the columns donnot match ,  should move to right 

in Google Chrome, win 7 , laptop

**Comment by jorisvandenbossche** [comment]
@shuiyuejihua Thanks for the report! 
The docstring seems to be rewritten in the meantime in the development version (see http://pandas-docs.github.io/pandas-docs-travis/generated/pandas.DataFrame.sample.html), and it seems to be no longer an issue there, so closing this issue.
