### ISSUE TITLE
msgpack for sparse dataframes

### ISSUE THREAD

**Issue by xag** [pandas-dev/pandas#23119]
#### Code Sample

```python
from pandas import SparseDataFrame
dfs = SparseDataFrame([[0, 0], [0, 1]])
import packers
packers.to_msgpack(None, dfs, compress='zlib')
# Returns: NotImplementedError: msgpack sparse frame is not implemented
```

#### Problem description

msgpack is much faster than pickle, which makes it highly relevant for sparse dataframes. Even "experimental" code is relevant. Speed in Python is often more relevant in experiments than in production, because code is run more frequently in a trial and errors process.

There is commented code in packers to encode / decode sparse dataframes.  What is the problem with it? What is the plan? What code snippet could we use? What alternatives do we have?

Problem is present in Master

Many thanks

**Comment by xag** [comment]
> Why do you say pickle is slow though? Have you measured that?

Yes on python 3.5.1. Then I tested on 3.6.6 and apparently the problems disappeared.

**Comment by xag** [comment]
> You could try adding sparse support

Naive question: how do I do this? Thanks

**Comment by jreback** [comment]
no objection to this though we are likely to deprecate some of these structures eg SparseDataFrame soon

**Comment by xag** [comment]
> we are likely to deprecate some of these structures eg SparseDataFrame soon

@jreback Does it mean a sparse DataFrame is treated as efficiently as a SparseDataFrame with the same data? Starting when? Thank you

**Comment by xag** [comment]
@jreback Too bad if you deprecate SparseDataFrame. (Un)pickling a large sparse SparseDataFrame is much faster than (un)pickling or (un)msgpack-ing the same sparse DataFrame.

```
import pandas as pd, scipy.sparse, time, pickle
dfs = pd.DataFrame(scipy.sparse.random(10000, 10000).toarray()).to_sparse(fill_value=0)
#dfs = pd.DataFrame(scipy.sparse.random(10000, 10000).toarray()) # try this too
start = time.time()
msg = list(pickle.dumps(dfs, protocol=4))
dfs = pickle.loads(bytes(msg))
stop = time.time()
stop - start
```

**Comment by TomAugspurger** [comment]
Pickle is just a protocol. For large datasets, there's no reason that msgpack would be much faster than pickle. You're welcome to profile pandas' pickle serialization to see if that can be improved.

**Comment by jreback** [comment]
marking this as won't fix.
