### ISSUE TITLE
DOC: Validate that the docstrings do not import pandas or numpy

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#23134]
`scripts/validate_docstrings.py` validates that the content of a docstring follows our standards. There are still some of those standards that the script does not validate, and this gives the users the wrong impression that the docstring is all right, when it's not really the case. All the missing validations are listed in #20298.

One of those standards is that we do not show the `import numpy as np` or `import pandas as pd` in the examples section, but we assume it's there. We should automatically validate that these imports do not exist in the examples.

For this issue is required:
- Change `scripts/validate_docstings.py` to give an error if the imports are found
- Add tests in `scripts/tests/test_validate_docstrings.py`
- Run the script for all docstrings (i.e. ./scripts/validate_docstings.py) and check in the resulting report how many of the docstrings in pandas have these imports. If any, remove them in the same PR.

**Comment by thoo** [comment]
@datapythonista I am a first time contributor. Can I work on this issue? Thanks.

**Comment by thoo** [comment]
@datapythonista  I don't find any import with `numpy` or `pandas`.

**Comment by datapythonista** [comment]
that makes sense, besides the unit tests you can add an import locally and see if your changes capture it
