### ISSUE TITLE
BLD: wheel building 

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#23151]
https://github.com/explosion/wheelwright

maybe we should investigate this for building multi platform wheels

though i think conda forge is also starting an effort to do this

**Comment by jbrockmendel** [comment]
The wheelwright repo isn't very active, makes it hard to tell how well this is maintained.  Do we know of any other projects using this?

**Comment by TomAugspurger** [comment]
We recently switched to using multibuild on azure pipelines. It's working well enough for now.
