### ISSUE TITLE
Getting error when i import pandas

### ISSUE THREAD

**Issue by SoumanPaul** [pandas-dev/pandas#23169]
### when i import pandas it shows me this error
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-7dd3504c366f> in <module>
----> 1 import pandas as pd

~/anaconda3/lib/python3.6/site-packages/pandas/__init__.py in <module>
     21 
     22 # numpy compat
---> 23 from pandas.compat.numpy import *
     24 
     25 try:

~/anaconda3/lib/python3.6/site-packages/pandas/compat/numpy/__init__.py in <module>
      8 
      9 # numpy versioning
---> 10 _np_version = np.__version__
     11 _nlv = LooseVersion(_np_version)
     12 _np_version_under1p10 = _nlv < LooseVersion('1.10')

AttributeError: module 'numpy' has no attribute '__version__'

**Comment by TomAugspurger** [comment]
Looks like you don't have numpy installed correctly.

I'd try creating a new environment and seeing if that works.

**Comment by TomAugspurger** [comment]
Feel free to keep posting, but I've closed this since it doesn't appear to be a pandas bug.
