### ISSUE TITLE
DataFrame.sort_values should have an algorithm with 'best' complexity for nearly sorted data

### ISSUE THREAD

**Issue by jondo** [pandas-dev/pandas#23181]
#### Problem description

I have got a large amount of data that is nearly sorted.
According to [these nice animations](https://www.toptal.com/developers/sorting-algorithms/nearly-sorted-initial-order), a simple insertion sort could be the fastest in this case.

So I suggest offering this as an additional algorithm for the 'kind' argument.

**Comment by TomAugspurger** [comment]
I think that'd be better suited for NumPy.

**Comment by jondo** [comment]
OK. Then I'd have to sort my index in NumPy, then reindex.

I have filed https://github.com/numpy/numpy/issues/12186.

**Comment by mroeschke** [comment]
Closing as a better scope for NumPy
