### ISSUE TITLE
Issues about the time index(which will chage the type)

### ISSUE THREAD

**Issue by xingyuezhiji** [pandas-dev/pandas#23196]
I found that if the time order is assending, the dataframe will change from pd.DataFrame to pd.Series automatically and vise versa.
 For example, df is the data i download from tushare and i set `df.set_index(['date'],inplace=True)`.
If the time index is assending, i cannot get `df['%Y-%m-%d']` like `df['2018-09-25']` because `type(df.loc['2018-09-25'])` is pd.Series. 
And if i change df into df[::-1], then the time order is decending and i can get `df['2018-09-25']` .What'more, the result of `type(df.loc['2018-09-25'])` is pd.DataFrame.

What should i do if i need the result of `type(df.loc['2018-09-25'])` is pd.DataFrame,no matter the time order is assending or decending.

**Comment by xingyuezhiji** [comment]
@TomAugspurger 
Here is the example：
`import tushare as ts
import pandas as pd
data=ts.get_k_data('sh',start='2017-01-03',end='2018-10-16')
print(data.date[::-1])
df = pd.DataFrame()
df['date'] = data.date
df['close'] = data.close
df.set_index(['date'],inplace=True)
print(df)
# df = df[::-1]
print((type(df.loc['2018-09-25'])))
`

**Comment by TomAugspurger** [comment]
You might want to read through http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by xingyuezhiji** [comment]
> You might want to read through http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

I’ve re-editted my post

**Comment by mroeschke** [comment]
Feel free to reopen when you can post a more minimal example (ideally without the 3rd party `tushare` library)
