### ISSUE TITLE
[Proposal] Allow open boundaries when some of them are undefined for DatetimeIndex

### ISSUE THREAD

**Issue by Adirio** [pandas-dev/pandas#23200]
#### Problem description
When creating a `DatetimeIndex` partially-bounded, i.e., only specifying either `start` or `end` the use of a `closed` parameter different from `None` was intended to be disallowed. This behaviour is bugged as shown in #23198. #23199 solves this bug.

Before #23199, the DatetimeIndex was successfully created. The result contained one less than the requested `periods` in some cases as shown in #23176.

After #23199, a `ValueError` will be raised as it seemed to be intended.

The proposal is to allow `closed` parameters different to `None` for partially-bounded `DatetimeIndex`es. The behaviour should be as defined in the following table

Periods | Ommited parameter | Closed | Current number of items | After #23199 | Proposed number of items
-|-|-|-|-|-
N | `end` | `None` | N | N | N
N | `end` | `"left"` | N-1 | `ValueError` | N
N | `end` | `"right"` | N | `ValueError` | N
N | `start` | `None` | N | N | N
N | `start` | `"left"` | N | `ValueError` | N
N | `start` | `"right"` | N-1 | `ValueError` | N

**Comment by jbrockmendel** [comment]
Can you give copy/pasteable examples of what behavior you want to change and what you want it changed to?

**Comment by Adirio** [comment]
**Note:** this issue refers to the arguments `start`, `periods`, `end` and `closed` which were deprecated in version 0.24.0 and are not present in the latest pandas version (1.1.2). Is there still any version receiving bug fixes that still implements these arguments?

The rest of this comment is using pandas version 0.23.4

I expected the following commands to give 10 results but some don't:

```python
from datetime import datetime, timedelta
import pandas as pd

n = 10
start = datetime.now()
end = start + timedelta(seconds=n-1)
pd.DatetimeIndex(freq='s', periods=n, start=start, closed=None)  # 1
pd.DatetimeIndex(freq='s', periods=n, start=start, closed='left')  # 2
pd.DatetimeIndex(freq='s', periods=n, start=start, closed='right')  # 3
pd.DatetimeIndex(freq='s', periods=n, end=end, closed=None)  # 4
pd.DatetimeIndex(freq='s', periods=n, end=end, closed='left')  # 5
pd.DatetimeIndex(freq='s', periods=n, end=end, closed='right')  # 6
```

Numbers 1, 2, 4 and 6 return:
```
DatetimeIndex(['2020-10-02 16:54:35.329660', '2020-10-02 16:54:36.329660',
               '2020-10-02 16:54:37.329660', '2020-10-02 16:54:38.329660',
               '2020-10-02 16:54:39.329660', '2020-10-02 16:54:40.329660',
               '2020-10-02 16:54:41.329660', '2020-10-02 16:54:42.329660',
               '2020-10-02 16:54:43.329660', '2020-10-02 16:54:44.329660'],
              dtype='datetime64[ns]', freq='S')
```

Number 3 returns:
```
DatetimeIndex(['2020-10-02 16:54:36.329660', '2020-10-02 16:54:37.329660',
               '2020-10-02 16:54:38.329660', '2020-10-02 16:54:39.329660',
               '2020-10-02 16:54:40.329660', '2020-10-02 16:54:41.329660',
               '2020-10-02 16:54:42.329660', '2020-10-02 16:54:43.329660',
               '2020-10-02 16:54:44.329660'],
              dtype='datetime64[ns]', freq='S')
```

Number 5 returns:
```
DatetimeIndex(['2020-10-02 16:54:35.329660', '2020-10-02 16:54:36.329660',
               '2020-10-02 16:54:37.329660', '2020-10-02 16:54:38.329660',
               '2020-10-02 16:54:39.329660', '2020-10-02 16:54:40.329660',
               '2020-10-02 16:54:41.329660', '2020-10-02 16:54:42.329660',
               '2020-10-02 16:54:43.329660'],
              dtype='datetime64[ns]', freq='S')
```

**Comment by jbrockmendel** [comment]
>  Is there still any version receiving bug fixes that still implements these arguments?

Use `pd.date_range`

**Comment by Adirio** [comment]
In version 1.1.2, `pd.date_range` has the exact same behavior as `pd.DatetimeIndex` in 0.23.4, so I guess this still aplies.

**Comment by mroeschke** [comment]
Thanks for the request, but it appears this feature request hasn't gain much traction in years so closing
