### ISSUE TITLE
Misleading "not" typo in assertion in pandas.concat in join_axes check

### ISSUE THREAD

**Issue by Ignalion** [pandas-dev/pandas#23204]
There is an assertion message in [concat.py](https://github.com/pandas-dev/pandas/blob/master/pandas/core/reshape/concat.py#L448):
```python

            if len(self.join_axes) != ndim - 1:
                raise AssertionError("length of join_axes must not be equal "
                                     "to {length}".format(length=ndim - 1))
```

From code (and from it's usage) it's obvious that word "**not**" is incorrect here and should be deleted.

**Comment by TomAugspurger** [comment]
Thanks for the report. Interested in submitting a PR fixing it?
