### ISSUE TITLE
DOC/TST: doctests leaving extraneous files

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#23201]
after running

``LINT=1 ci/code_check.sh``

we get some garbage left around

```
(pandas) bash-3.2$ git st
On branch PR_TOOL_MERGE_PR_23096
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        df.parquet.gzip
        df_info.txt
        output.xlsx
        output1.xlsx

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by jreback** [comment]
cc @datapythonista 

prob from some of the doc-tests

**Comment by datapythonista** [comment]
Didn't realize, but likely to be from the doctests. Not sure what's the best option here, what comes to my mind:
- Save to temp: `df.to_csv('/tmp/data.csv')`
- Remove the file after saving in the doctest (I don't like that it may be confusing and verbose to the users)
- Avoid saving to disk in the doctests (I don't like it, as we won't be able to show several methods)
- Saving to StringIO objects (probably too complex for beginners)
- Having a clean up function (we'll have to maintain the list of files, and we have several ways to run the doctests, so we can't run it automaitcally in all cases)

Any other idea? I think the first option is probably the best, even if it's not ideal.

**Comment by WillAyd** [comment]
Is using a tempfile / namedtempfile not an option?

**Comment by jreback** [comment]
yes these should use a named temp file i think

**Comment by TomAugspurger** [comment]
How about we add `doctest: +SKIP` to the lines writing to disk, and lines that read afterwards?

Writing to `/tmp` isn't great, since users may be copy-pasting and may not have a `/tmp` directory.

Anything with cleaning up or writing to a StringIO will, I think, just muddy the example. We shouldn't compromise on the documentation here.

**Comment by datapythonista** [comment]
+1 on `doctest: +SKIP`.

**Comment by RomainSa** [comment]
Working on it!
