### ISSUE TITLE
PERF: replace use of `isnan` once MSVC bug is fixed

### ISSUE THREAD

**Issue by chris-b1** [pandas-dev/pandas#23209]
ref #23182, #21813

MSVC bug tracker  - https://developercommunity.visualstudio.com/content/problem/294290/incorrect-codegen-for-double-equality.html

Once that bug is fixed in a widely available MSVC for python 3 builds we should redefine `isnan` / `notnan` to be based on an equality check here.
https://github.com/pandas-dev/pandas/pull/23182/files#diff-467e9a847ab859a085518bc17711fe57R20

Current code works around that MSVC bug by using the libc, `isnan`, which works, but can't be inlined, so likely has a little perf cost
https://godbolt.org/z/y550lB

**Comment by jbrockmendel** [comment]
@chris-b1 any idea if this has been addressed upstream?

**Comment by chris-b1** [comment]
That bug has been fixed in the most recent version of MSVC  - I'm a little disconnected form our build process to know if that's what were using.

**Comment by jbrockmendel** [comment]
> most recent version of MSVC

Do you know what that version is?  In _libs/src/cmath there is a comment "Place upper bound on this check once a fixed MSVC is released"

**Comment by TomAugspurger** [comment]
VS2019. It's mentioned in
https://developercommunity.visualstudio.com/solutions/477668/view.html.

**Comment by jbrockmendel** [comment]
do we have a way of checking if this is actionable?
