### ISSUE TITLE
Unable to merge pandas dataframe with categorical values.

### ISSUE THREAD

**Issue by sayankolay** [pandas-dev/pandas#23219]
master_frame = pd.merge(rounds2, companies, how='inner', on='permalink')

#### Problem description

Unable to merge pandas dataframe with categorical values. Only the dataframe headers get merged. the dataframe remains empty.

File 1 details (rounds2)
rounds2.dtypes
company_permalink           object
funding_round_permalink     object
funding_round_type          object
funding_round_code          object
funded_at                   object
raised_amount_usd          float64
permalink                   object
dtype: objec

File 2 details (companies)
companies.infer_objects().dtypes
permalink        object
name             object
homepage_url     object
category_list    object
status           object
country_code     object
state_code       object
region           object
city             object
founded_at       object
dtype: object

**Comment by sayankolay** [comment]
import pandas as pd
import numpy as np
companies = pd.read_csv("https://cdn.upgrad.com/UpGrad/temp/d934844e-5182-4b58-b896-4ba2a499aa57/companies.txt", sep='\t', encoding = "ISO-8859-1")
rounds2 = pd.read_csv("https://cdn.upgrad.com/UpGrad/temp/4c3b5ed0-e5dc-4838-89a2-173d8707d857/rounds2.csv", encoding = "ISO-8859-1")
rounds2['permalink'] = rounds2['company_permalink']
master_frame = pd.merge(rounds2, companies, how='inner', on='permalink')
master_frame.head()

**Comment by TomAugspurger** [comment]
Can you make a short example that doesn't rely on external data? E.g. if
that link goes away, we'd still want to reproduce the issue.

Could you post the traceback, expected output, and `show_versions` like
requested?

Also, it looks like you don't have any categorical columns.

**Comment by sayankolay** [comment]
Hi Tom,

Thanks for your prompt response.

I am facing this issue only on those 2 files, otherwise i can use the merge function well. 

This is the actual screenshot.. https://ibb.co/b2eubL

As you can see if i show head of the two dataframes i can see rows, but its once merged the new daraframe only has headers.

**Comment by sayankolay** [comment]
It was fixed by converting the column to lower case. merge function is case sensitive. 👍 

This is the code
companies['permalink_final'] = companies['permalink'].str.lower()
