### ISSUE TITLE
Expand .str to DataFrame

### ISSUE THREAD

**Issue by sorenwacker** [pandas-dev/pandas#23211]
#### Code Sample, a copy-pastable example if possible

```python
mask = df.str.match(re)
AttributeError: 'DataFrame' object has no attribute 'str'
```
#### Problem description

I always run into this. DataFrame has no method str. Though I should be easy to map this method to the Series.str  and call it for each Series. Is there any reason why this is not implemented, other than no one did it yet?

**Comment by jreback** [comment]
we don’t have any accessors for DataFrame

you could make this syntactic sugar for an .apply
no objection generally though this would have to be a general method that can work on all accessors

**Comment by mroeschke** [comment]
Thanks for the suggestion but I believe we have had other requests for this feature which was rejected because of the complexity of a DataFrame with potentially different dtypes working with an accessor meant for a specific dtype. Closing
