### ISSUE TITLE
Reindex error after df.loc + pd.pivot_table

### ISSUE THREAD

**Issue by Sobes76rus** [pandas-dev/pandas#23226]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np

df1 = pd.DataFrame(np.arange(9).reshape(3, 3), columns=['a', 'b', 'c'])
df2 = df1.loc[df1['a'] == 123]

df3 = pd.pivot_table(df2, 'a', 'b', 'c', aggfunc='sum')
df3.reindex(columns=['a', 'b', 'c'])
```
#### Problem description

`df3` is `Empty DataFrame`
```
Empty DataFrame
Columns: []
Index: []
```

`pd.DataFrame().reindex(columns=['a', 'b', 'c'])` executed correctly. 
So `df3.reindex(columns=['a', 'b', 'c'])` should be too, but instead raise exception

#### Expected Output
```
Empty DataFrame
Columns: [a, b, c]
Index: []
```

#### Output of ``pd.show_versions()``

<details>

commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-36-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 3.1.2
pip: 9.0.1
setuptools: 36.4.0
Cython: 0.28.5
numpy: 1.15.2
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: 1.0.5
lxml: None
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
Look at `df3.columns`, it's a MultiIndex. You need to reindex it with another MultiIndex or list of tuples, or pass `level`

```python
In [70]: df3.reindex(columns=['a', 'b', 'c'], level=1)
Out[70]:
Empty DataFrame
Columns: []
Index: []
```

**Comment by Sobes76rus** [comment]
You are right. Thank you. Sorry for bothering

**Comment by Sobes76rus** [comment]
But why `df3.columns` is MultiIndex?

```
import pandas as pd
import numpy as np

df1 = pd.DataFrame(np.arange(9).reshape(3, 3), columns=['a', 'b', 'c'])
df2 = df1.loc[df1['a'] == 0]

df3 = pd.pivot_table(df2, 'a', 'b', 'c', aggfunc='sum')
df3.reindex(columns=['a', 'b', 'c'])
```

In above example i change condition `df1['a'] == 123` to `df1['a'] == 0`.
Now `df2` is not `Empty DataFrame`
So df3 now
```
In [55]: df3
Out[55]: 
c  2
b   
1  0
```

And df3.reindex(columns=['a', 'b', 'c']) works correctly

**Comment by Sobes76rus** [comment]
```Python
In [72]: df3 = pd.pivot_table(pd.DataFrame(columns=['a', 'b', 'c']), 'a', 'b', 'c', aggfunc='sum')

In [73]: df3
Out[73]: 
Empty DataFrame
Columns: []
Index: []

In [74]: df3.columns
Out[74]: Index([], dtype='object')
```

If instead `df2` we take `Empty DataFrame` as `pd.DataFrame(columns=['a', 'b', 'c'])`
then `df3.columns` will be `Index`
