### ISSUE TITLE
Exception: 'Series' objects are mutable, thus they cannot be hashed

### ISSUE THREAD

**Issue by andrfgs** [pandas-dev/pandas#23243]
#### Problem

I am trying to explore the **[GDELT](https://blog.gdeltproject.org/gdelt-2-0-our-global-world-in-realtime/)** dataset. I read the file as a csv, having downloaded it from the website. Their initial csv file does not contain the header, but I *added them from the Google Big Query col names*. The header is correct, that I have confirmed multiple times, well, at least it containts the exact amount of columns it should.

When trying to search for any row given a column value, the program crashes with:

> 'Series' objects are mutable, thus they cannot be hashed

#### MInimal Running Example
```
import pandas as pd

python
csv_file_path = "C:\\Users\\and_s\\Downloads\\20181015143000.export.CSV\\20181015143000.export.CSV"

gdelt_data = pd.read_csv(csv_file_path, sep='\t', lineterminator="\n")
gdelt_data = gdelt_data.loc(gdelt_data['actor1_country_code'] == "ITA")
print(gdelt_data)
```

Is this a bug? Because AFAIK strings are hashable.

Also this doesn't work even if I remove null values, so that's not the problem.

**Comment by mroeschke** [comment]
`.loc` should be called with square brackets.

```
gdelt_data = gdelt_data.loc[gdelt_data['actor1_country_code'] == "ITA"]
```

**Comment by andrfgs** [comment]
*facepalm*

Sorry then. I must have misread somewhere. I am very sorry for not carefully read the documentation.

Just one more thing, is the following valid syntax:
`gdelt_data = gdelt_data[["actor1_country_code"] == "USA"]`

I know this can be used with integers but not with strings?

**Comment by mroeschke** [comment]
Technically yes, but it will not give you the result you want.

You can read more about boolean indexing here: https://pandas.pydata.org/pandas-docs/stable/indexing.html#boolean-indexing

**Comment by andrfgs** [comment]
Thank you very much for the answer.
