### ISSUE TITLE
What if I need to get columns with mixed types?

### ISSUE THREAD

**Issue by sanjok-bless** [pandas-dev/pandas#23246]
#### Problem description
According to the [documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.errors.DtypeWarning.html), we get DtypeWarning: Columns (0) have mixed types if the data contains integers and strings and it is suggested to set low_memory = False, and this removes the warning. But my task is the opposite: to define columns with mixed types!

At first, I thought to parse the DtypeWarning message so that I could understand which columns has mixed type, but I encountered many difficulties that prevent me from relying on DtypeWarning:

1. If you reduce the number of lines from 300,000 to 250,000, then DtypeWarning no longer appears, but I need it for at least 100,000 lines
2. Even for 300,000 rows, the column is not always determined with mixed types, for example I modify dataframe from [doc](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.errors.DtypeWarning.html):

```python
# From the docs:
>>> df = pd.DataFrame({'a': (['1'] * 100000 + ['X'] * 100000 +
...                          ['1'] * 100000),
...                    'b': ['b'] * 300000})
>>> df.to_csv('test.csv', index=False)
>>> df2 = pd.read_csv('test.csv')
... # DtypeWarning: Columns (0) have mixed types

# My case:
>>> df = pd.DataFrame({'a': (['1'] * 10000 + ['X'] * 10000 +
...                          ['1'] * 10000) * 10,
...                    'b': ['b'] * 300000})
>>> df.to_csv('test.csv', index=False)
>>> df2 = pd.read_csv('test.csv')
... # No warning
```
It still has mixed types, but warning doesn't appears. And if I analyze types, all of these are 'str'. Ie I can't analyze mixed types even by myself.

So, How I can get columns with mixed types? Is it possible to add the parameter  read_csv(mixed_types=True) and force the pandas not to hide mixed types for all datasets or for at least 100 000 rows? Or any ideas?

Thanks.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-137-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.23.4
pytest: None
pip: 18.1
setuptools: 40.2.0
Cython: 0.28.3
numpy: 1.14.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 5.8.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: 3.4.3
numexpr: 2.6.1
feather: None
matplotlib: 2.1.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
this is a usage question, try StackOverflow

you should use .select_dtypes to do this
