### ISSUE TITLE
Gaps in ExtensionArray test coverage

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#23241]
We need tests that assert

1. `fillna` raises when passed an array of the wrong length
2. `fillna` returns a copy when there are no missing value
3. `take` raises when passed an invalid object for `fill_value` (may be somewhat tricky to do in a base test).

These tests would go in https://github.com/pandas-dev/pandas/blob/master/pandas/tests/extension/base/methods.py and https://github.com/pandas-dev/pandas/blob/master/pandas/tests/extension/base/getitem.py

**Comment by thoo** [comment]
@TomAugspurger  I am going to work on this.

**Comment by TomAugspurger** [comment]
OK thanks. If writing a test for take seems difficult, feel free to just
fix the fillna ones.

**Comment by thoo** [comment]
@TomAugspurger  Thanks.

**Comment by thoo** [comment]
@TomAugspurger  It is not done yet. I just want to make sure I am on the right track. Could you please take a look? Thanks.
