### ISSUE TITLE
pandas.MultiIndex.set_levels does not accept generator

### ISSUE THREAD

**Issue by AntoineD** [pandas-dev/pandas#23273]
#### Code Sample, a copy-pastable example if possible

```python
index = pd.MultiIndex.from_tuples(((0,1), (0, 2)))
index.set_levels(map(int, (3,)), level=0)
```
#### Problem description
Raises
```python
TypeError: 'map' object is not subscriptable
```
Workaround by wrapping map with list.

#### Expected Output
MultiIndex(levels=[[3], [1, 2]],
           labels=[[0, 0], [0, 1]])

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Linux
OS-release: 4.18.14-200.fc28.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 3.8.2
pip: 10.0.1
setuptools: 40.4.3
Cython: None
numpy: 1.15.2
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.0.1
sphinx: 1.8.1
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by TomAugspurger** [comment]
It's documented to accept a sequence, which needs to implement `__getitem__`. We would probably take a PR that turns the iterable into a list.

**Comment by AntoineD** [comment]
Thanks a lot. :+1:
