### ISSUE TITLE
Error "buffer source array is read-only" when using unique() on df loaded with feather

### ISSUE THREAD

**Issue by eamag** [pandas-dev/pandas#23276]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import feather

df1 = pd.DataFrame([1,2,3,1,2,4], columns=['a'])
df1.a = df1.a.astype('category')
print(df1.a.unique())

df1.to_feather('a.feather')
df1 = feather.read_dataframe('a.feather')
df1.a.unique()
```

**Comment by TomAugspurger** [comment]
What version of pandas? This works for me on master (thats' why we ask you to fill out the issue template).

**Comment by xhochy** [comment]
This is fixed by https://github.com/pandas-dev/pandas/pull/21688 which is not in a released version yet.

**Comment by TomAugspurger** [comment]
Great, thanks @xhochy.
