### ISSUE TITLE
TST: rdivmod on EA Arrays

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#23287]
xref #23271 

I think we need to add a test case for rdivmod as its now defined on Series.

**Comment by jorisvandenbossche** [comment]
There are at least already tests for Series with scalar (but not Series/Series or Series/array), it seems:

https://github.com/pandas-dev/pandas/blob/8d8955e54bd5fc8fae070dd862f104dc17bee0b7/pandas/tests/extension/base/ops.py#L89-L96
