### ISSUE TITLE
How to use rolling_std with Pandas 0.23.4?

### ISSUE THREAD

**Issue by haimivan** [pandas-dev/pandas#23295]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame({"a": [1, 2, 3,4, 5, 6]})
print("pd.__version__:", pd.__version__)
# pd.__version__: 0.23.4
df['vola'] = pd.rolling_std(df['a'], window=2)
# AttributeError: module 'pandas' has no attribute 'rolling_std'
df['vola'] = df['a'].rolling_std(window=2)
#AttributeError: 'Series' object has no attribute 'rolling_std'

```
#### Problem description

As written in [http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#whatsnew-0180-enhancements](http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#whatsnew-0180-enhancements), the syntax for rolling_std might have changed.

With neither the old nor the new syntax I can calculate the `rolling_std` function.

Is this a bug or do I have to access it differently?

**Comment by TomAugspurger** [comment]
```
In [6]: df.rolling(2)
Out[6]: Rolling [window=2,center=False,axis=0]

In [7]: df.rolling(2).std()
Out[7]:
          a
0       NaN
1  0.707107
2  0.707107
3  0.707107
4  0.707107
5  0.707107
```
