### ISSUE TITLE
BUG: reducing ufuncs don't return a scalar

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#23312]
But are wrapped again in the Series or Index:

```
In [1]: s = pd.Series([1, 2, 3])

In [3]: np.add.reduce(s)
Out[3]: 
0    6
1    6
2    6
dtype: int64

In [4]: np.add.reduce(s.values)
Out[4]: 6
```

**Comment by jorisvandenbossche** [comment]
And for index it is even worse:

```
In [16]: idx = pd.Index([1, 2, 3])

In [17]: result = np.add.reduce(idx)

In [18]: result    # <-- repr is failing
...
TypeError: len() of unsized object

In [19]: type(result)
Out[19]: pandas.core.indexes.numeric.Int64Index

In [20]: result.values
Out[20]: array(6)
```

**Comment by jorisvandenbossche** [comment]
@shoyer I thought to fix this first / separately before the `__array_ufunc__` PR, but, the behaviour here is a little bit undefined. 
I suppose that *in principle*, a ufunc.reduce returns an array (or an object of the same array-like) with a reduced dimension. But in pandas, we of couse don't have a concept of 0-dim objects or in general variable dim objects. So I assume returning a 0-dim array is fine here (or just a scalar?), but seems a bit strange to ask this of an ExtensionArray (there a scalar might make more sense if it's something that otherwise needs to be wrapped in a 0-dim object array?).

**Comment by jorisvandenbossche** [comment]
@TomAugspurger I think this was closed by https://github.com/pandas-dev/pandas/pull/23293 ?

**Comment by jorisvandenbossche** [comment]
on master

```
In [63]: s = pd.Series([1, 2, 3])                                                                                                                                                             

In [64]: np.add.reduce(s)                                                                                                                                                                     
Out[64]: 6
```

**Comment by TomAugspurger** [comment]
Looks like it.
