### ISSUE TITLE
Can provide read_elastic and to_elastic support for dataframes using maybe elasticsearch-py?

### ISSUE THREAD

**Issue by anjsudh** [pandas-dev/pandas#23315]

**Comment by WillAyd** [comment]
Not sure we want to expand the API here but do you have an idea of the complexity of this request? Personally haven't used elastic search so not sure what this requires.

Here's a related SO article:

https://stackoverflow.com/questions/49726229/how-to-export-pandas-data-to-elasticsearch

**Comment by gfyoung** [comment]
Unless there's a pretty significant push for this, I'm hesitant to think that we would want to include this in core API.  That being said, I think an entry in the cookbook would be reasonable.

**Comment by jbrockmendel** [comment]
Closing and adding to a tracker issue #30407 for IO format requests, can re-open if interest is expressed.
