### ISSUE TITLE
Fix import formatting using isort

### ISSUE THREAD

**Issue by alimcmaster1** [pandas-dev/pandas#23334]
Following on from #23048. We now need to run isort on all *.py files in the codebase that we are ignoring  in CI see [here](https://github.com/pandas-dev/pandas/blob/master/setup.cfg). Information on Isort [here](https://pypi.org/project/isort/)

Useful commands:

To sort imports in files in pandas directory ( ignoring those explicitly mentioned in setup.cfg)
`isort --recursive pandas`

To check imports are formatted correctly:
`isort --recursive --check-only pandas`

Find a directory you wish to fix from the list below( larger directories by # of files)
And comment on here that you are working on fixing. To avoid duplicated efforts. 

Directories we need to cover:

- pandas/*.py ( in progress @alimcmaster1 )
- pandas/util/ ( in progress @alimcmaster1 )
- pandas/io/ ( in progress @alimcmaster1 )
- pandas/core/ ( in progress @alimcmaster1 )
- pandas/core/indexes/ ( in progress @alimcmaster1 )
- pandas/core/dtypes/  (@alexander-ponomaroff )
- pandas/core/groupby/ (@alexander-ponomaroff )
- pandas/core/reshape/ (@streeck)
- pandas/core/computation/ (@streeck)
- pandas/tests/indexes/ (@thoo)
- pandas/tests/indexes/multi
- pandas/tests/indexes/interval
- pandas/tests/indexes/timedeltas
- pandas/tests/series/ (@thoo)
- pandas/tests/arrays/ (@thoo)
- pandas/tests/util/  (@thoo )
- pandas/tests/extension/ (@mwoss )
- pandas/tests/io/parser/ (@mwoss )
- pandas/tests/io/formats/
- pandas/tests/io/msgpack/
- pandas/tests/io/*.py
- pandas/tests/scalar/
- pandas/tests/tslibs/
- pandas/tests/groupby/ (@sam-cohan )
- pandas/tests/plotting/ (@pvarshney1729 )
- pandas/tests/frame/ (@pvarshney1729 )
- pandas/tests/indexing/ (@amphy )

PRs must contain no more than 20 files.

For new contributors please first take a look at our [Contributing Guide](https://pandas.pydata.org/pandas-docs/stable/contributing.html)

Pandas-Dev: Could we please add the following labels "Style", "Good first Issue", Contributions Welcome" and any more you feel appropriate.

Thanks,
Alistair

**Comment by alexander-ponomaroff** [comment]
I would like to help out with this issue. Can I please work on the following directories?

- pandas/core/dtypes/
- pandas/core/groupby/
- pandas/core/reshape/
- pandas/core/computation/

**Comment by alimcmaster1** [comment]
Hey @alexander-ponomaroff thanks for looking to contribute! I've put you down for dtypes and groupby first so we can concentrate on getting those merged first. Then we can look into the others. Let us know on here if you need any help.

**Comment by thoo** [comment]
@alimcmaster1  I will be working on:
```
pandas/tests/indexes/
pandas/tests/series/
pandas/tests/arrays/
pandas/tests/util/
```

**Comment by pvarshney1729** [comment]
@alimcmaster1 This will be my first issue. I'll be working on
pandas/tests/plotting/
pandas/tests/frame/

**Comment by alimcmaster1** [comment]
thanks both @thoo and @pvarshney1729

**Comment by thoo** [comment]
@alimcmaster1 Do you want several PR from the same branch ?? I have more than 20 files.

**Comment by alimcmaster1** [comment]
I would recommend using separate branches so the PRs are independent of each other.

**Comment by alexander-ponomaroff** [comment]
@alimcmaster1 I've looked into dtypes and groupby, now waiting for CI checks to finish for those two pull requests. Could I now also look into the following directories that I previously requested?

- pandas/core/reshape/
- pandas/core/computation/

**Comment by mwoss** [comment]
Hi. I would like to help with this issue. May I work on:

- pandas/tests/extension/
- pandas/tests/io/parser/
- pandas/tests/io/formats/
- pandas/tests/groupby/

**Comment by amphy** [comment]
I would like to help out with this issue. I will be working on

- pandas/tests/indexing

**Comment by jreback** [comment]
so ok with more than 20 files, just don't go crazy, rather like to have logical groupings (like we have had already for some)

**Comment by alimcmaster1** [comment]
Sure @mwoss i've put you down for "pandas/tests/extension/" and "pandas/tests/io/parser/" focus on getting those two merged first. and thanks @amphy !

@alexander-ponomaroff - Mind if we wait to see if any other first time contributors are interested in taking a look - this issue has quite a low barrier to entry so it would be great to get as many new contributors as possible working on things! But if there is no response they are yours  :) Hope that makes sense!

**Comment by alexander-ponomaroff** [comment]
@alimcmaster1 That's no problem, just let me know when I can start working on the other two directories if nobody new comes in.

**Comment by streeck** [comment]
I would also like to help with this issue, I'll be working on:

- `pandas/core/reshape/`
- `pandas/core/computation/`
- `pandas/tests/io/formats/`
- `pandas/tests/groupby/`

**Comment by samcan** [comment]
@streeck Do you mind if I have one of those directories since those are the only ones left?

**Comment by streeck** [comment]
Sure @sam-cohan, grab the last one: `pandas/tests/groupby/` ;)

**Comment by samcan** [comment]
Thanks!

**Comment by alimcmaster1** [comment]
Thanks both @sam-cohan and @streeck for looking to contribute! @streeck put you down initially for `reshape` and `computation` to give others the chance to contribute like i've said above. Thanks,

**Comment by alimcmaster1** [comment]
Thanks all for the contributions so far! Added few more sections - please comment on here if you would like to work on one

**Comment by alimcmaster1** [comment]
@thoo still some remain in the below sections - do you still want to work on these? Thanks for your efforts so far

( ive split up indexes )

pandas/tests/series/
pandas/tests/arrays/
pandas/tests/util/

**Comment by thoo** [comment]
@alimcmaster1  Yes I can do them. Please assign me sections you want me to do.

**Comment by thoo** [comment]
@alimcmaster1 I had already submitted the PRs for those.

**Comment by alimcmaster1** [comment]
@thoo there is still a few files under those sections - from looking at setup.cfg on master - let us know if you  still want to look at these.

**Comment by thoo** [comment]
@alimcmaster1  Sorry. I misunderstood the instruction. Those files are all good. `isort` did nothing on them but I will submit a PR to remove filenames from setup.cfg.

**Comment by alimcmaster1** [comment]
Still a few files to be worked on here if anyone is interested. Full list in [setup.cfg](https://github.com/pandas-dev/pandas/blob/master/setup.cfg), post on here if anyone is interested.

**Comment by mwoss** [comment]
@alimcmaster1 
Hi. I will work on:

- pandas/tests/dtypes/
- pandas/tests/arithmetic/
- pandas/tests/plotting/

**Comment by simonjayhawkins** [comment]
@alimcmaster1  i think there could be an issue isorting asv_bench/benchmarks/, xref #22947

**Comment by alimcmaster1** [comment]
Thanks @mwoss and @thoo.

I will complete all the leftover files that havn't been mentioned above.

@simonjayhawkins we should just be able to force that import to the end using isort.

**Comment by gasparia405** [comment]
@alimcmaster1 Sorry, I missed that in the thread. It looks like the only ones left are the asv_bench/benchmark files, I'll take a crack at some of those. I saw the comment about keeping the setup imports at the bottom of the file, so I'll make sure to keep an eye out for that.

Thank you for responding so quickly before!

**Comment by jreback** [comment]
@simonjayhawkins actually let's create a new one with the remaining items.
