### ISSUE TITLE
Matplotlib v3

### ISSUE THREAD

**Issue by achapkowski** [pandas-dev/pandas#23330]
Matplotlib v3 seems to break pandas at v.23.x.  What version of matplotlib is required?

**Comment by alimcmaster1** [comment]
Hey - how do I reproduce the error you are seeing? Potentially related to #23319 looking at comments from @TomAugspurger

**Comment by TomAugspurger** [comment]
https://github.com/matplotlib/matplotlib/issues/12601

**Comment by TomAugspurger** [comment]
Downgrading your Python a point release, or upgrading to MPL master should fix it.
