### ISSUE TITLE
PERF: Investigate caching on PeriodArray

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#23359]
Start with benchmarks

1. ops on PeriodArray and PeriodIndex
2. ...

If we determine that caching attributes like `hasnans` and `isna` does help then we can investigate caching on PeriodArray.

**Comment by TomAugspurger** [comment]
We'll need to be especially careful here. The point of PandasArray
(formerly NumPyBackedExtensionArray) is to be a zero-copy view on some
other ndarray,
which makes failing to invalidate a cache more likely.

**Comment by jbrockmendel** [comment]
Been thinking about this recently, I think the view trouble is going to make caching on DTA/TDA/PA infeasible

**Comment by TomAugspurger** [comment]
Is the trouble PeriodArray taking a view on another array, or another array taking a view on the PeriodArray?

**Comment by jbrockmendel** [comment]
its one PeriodArray taking a view on another, so if the first does a setitem (that presumably invalidates the cache), the cache would need to be invalidated on the other

(this is also why im increasingly convinced that DTA/TDA need to have `freq` removed)

**Comment by TomAugspurger** [comment]
Gotcha. In theory, `PeriodArray.__init__` could create a weakref in both directions (view to orig and orig to view) and `__setitem__` would invalidate the caches of both. But that feels increasingly fragile.

**Comment by jbrockmendel** [comment]
Closing as not worth the trouble
