### ISSUE TITLE
issue regarding fill missing value

### ISSUE THREAD

**Issue by ayushpatidar** [pandas-dev/pandas#23354]
problem description : 
There is no function available in pandas which can fill missing value in dataframe according to column type i.e whether column is of categorical type or numeric type.
It will be easier if we provide a direct function which can fill missing value according to the type of column

**Comment by jreback** [comment]
pls show an example

**Comment by ayushpatidar** [comment]
#here we are reading the dataframe 
df = pd.read_csv("60tp.csv")

#a function that will fill missing value according to type of column
df.fill_missing(strategy_numeric="mean",strategy_cat="most_frequent", criteria=.1)

1. ..here strategy_numeric  indicates the strategy used to fill missing value for column which has continuous type of value.

2..here strategy_cat  indicates the strategy used to fill missing value for column which has categorical type value.

3.. if a column has value of string and object type then it is considered as categorical.
   if a column has value of int or float types then it is considered as numeric. but if a column is of numeric 
    type but have only two unique value it should be considered as categorical type rather than numeric 
   type so (the criteria parameter takes the percent of unique value to consider a columns as categorical 
   not numeric if it has integer type values)

**Comment by TomAugspurger** [comment]
FYI: http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports has tips on writing good bug examples

From what I can glean, your hypothetical `fill_missing` function sounds quite complicated. I'd recommend building a Series or dict with your fill values, and use that as an argument to `fillna`.

**Comment by ayushpatidar** [comment]
using dict or series to fill missing value fill not be feasible when the number of missing value are in huge amount. And most of the time filling missing value with mode,mean and median is more preferred.

**Comment by TomAugspurger** [comment]
Let us know if you can provide an example, so that we can discuss it effectively. I think we're talking past each other right now.
