### ISSUE TITLE
CLN: commented-out code in _libs/sparse.pyx

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#23371]
reindex_block, SparseCruncher, and (related) reindex_integer

**Comment by jbrockmendel** [comment]
BlockIntersection

get_reindexer appears unused

**Comment by gfyoung** [comment]
I'm all for removing commented-out code, since if there was a use for it, it would have been commented-in already awhile ago.

cc @jreback

**Comment by jbrockmendel** [comment]
Closed by #23583
