### ISSUE TITLE
tm.ensure_clean() does not create Temporary Directory. It only creates temporary files.

### ISSUE THREAD

**Issue by anjsudh** [pandas-dev/pandas#23373]
_Originally posted by @anjsudh in https://github.com/pandas-dev/pandas/pull/23321_

**Comment by anjsudh** [comment]
Will pick this up

**Comment by gfyoung** [comment]
@anjsudh : I'm hesitant to believe that we actually need this, largely in part because we often don't create that many files during testing for a single test.
