### ISSUE TITLE
read_parquet not working 

### ISSUE THREAD

**Issue by make-it-happen-p** [pandas-dev/pandas#23397]
#### Code Sample, a copy-pastable example if possible

```python
import os
import pandas
bio = pandas.read_parquet(os.path.join('data', 'bio.parquet') , engine='pyarrow')

```
#### Problem description
**
read_parquet not working on running in jupyter
**
![screenshot from 2018-10-28 16-47-40](https://user-images.githubusercontent.com/41293829/47615213-42974f80-dad2-11e8-87d2-b18aef671558.png)

**Comment by xhochy** [comment]
Which version of `pandas` are you using?

**Comment by make-it-happen-p** [comment]
0.23.02

**Comment by gfyoung** [comment]
> 0.23.02

@make-it-happen-p :

I presume you meant `0.23.2`  Can you show that that's the version in the Jupyter Notebook?  I suspect something is wrong with the installation, `read_parquet` is most certainly there.

**Comment by Piyushohri1** [comment]
I think something missing . Try to install **pyarrow** engine . If you have no engine to run parquet you can't do anything. 
for terminal command is : **conda install -c conda-forge pyarrow**

**Comment by make-it-happen-p** [comment]
The issue is resolved . thanks @Piyushohri1  for advice . Actually i have checked there was no engine to run the parquet command . I installed pyarrow and now the program runs just fine .
