### ISSUE TITLE
Support vmin and vmax for bars

### ISSUE THREAD

**Issue by domoritz** [pandas-dev/pandas#23403]
```python
plot.bar(colormap=cmap, vmin=0, vmax=5)
```
#### Problem description

`vmin` and `vmax` are not supported. https://github.com/pandas-dev/pandas/issues/21526 adds support in the styler but not the bar plotting itself. 

#### Expected Output

The color range should be set.

**Comment by TomAugspurger** [comment]
Can you make the example at the top a full one? That helps us know exactly what we need to achieve to close this issue.

**Comment by domoritz** [comment]
Ah, it's in color. Answer in https://github.com/pandas-dev/pandas/issues/21526#issuecomment-433836945.
