### ISSUE TITLE
Add a new function to pd.Datetime: Cross time indices 

### ISSUE THREAD

**Issue by meteoDaniel** [pandas-dev/pandas#23407]
I suggest a new function for pandas. 
Often people working with time series in different length and scales and want to compare these data to each other or do some operations on it. For this purpose the timestamps and datapoints have to match.

The code below works fine for the most use cases but some times its failing, too and it has to do with some bugs in intersection method. It would be great to have something similar in pandas. 
```
def cross_time_index(df1, df2):
    """
        cross Index of Dataframe or Series to get same timestamps
         in both variables
    :param df1:
        pandas.Dataframe or pd.Series
    :param df2:
        pandas.Dataframe or pd.Series
    :return:
    """
    series = pd.core.series.Series
    crossed_index = df1.index.intersection(df2.index)

    if type(df1) == series and type(df2) == series:
        df1 = df1[crossed_index]
        df2 = df2[crossed_index]
    elif type(df1) == series and type(df2) != series:
        df1 = df1[crossed_index]
        df2 = df2.loc[crossed_index, :]
    elif type(df1) != series and type(df2) == series:
        df1 = df1.loc[crossed_index, :]
        df2 = df2[crossed_index]
    else:
        df1 = df1.loc[crossed_index, :]
        df2 = df2.loc[crossed_index, :]
    return df1, df2
```

**Comment by jreback** [comment]
this is http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.align.html?highlight=align#pandas.DataFrame.align

would certainly welcome contributions to the doc string
