### ISSUE TITLE
TST: Reorganize Frame/Series ops tests

### ISSUE THREAD

**Issue by sinhrks** [pandas-dev/pandas#23417]
Currently, similar tests for DataFrame and Series are written in either `test_arithmetic.py` or `test_operators.py`.

How about merging them, or split them to based on operators (like `test_op_arithmetic`, `test_op_comparison` and `test_op_unary`).

**Comment by mbirdi** [comment]
@sinhrks  I'd like to take a shot at this one.  I'm not a developer, but I have been using pandas for a few years now, and would like to understand the tests more.  Before I start, two quick questions.  Would this be a good first issue?  Is merging better than splitting?

**Comment by mbirdi** [comment]
|	line_num	|	test_file	|	line	|
| 	------------- 	|	:-------------------:	|	:---------------------------:	|
|	209	|	test_operators.py	|	def _check_bin_op(op):	|
|	569	|	test_operators.py	|	def _check_unaligned_frame(meth, op, df, other):	|
|	216	|	test_operators.py	|	def _check_unary_op(op):	|
|	552	|	test_operators.py	|	def _test_op(df, op):	|
|	595	|	test_operators.py	|	def _test_seq(df, idx_ser, col_ser):	|
|	157	|	test_operators.py	|	def check(df, df2):	|
|	119	|	test_operators.py	|	def f():	|
|	124	|	test_operators.py	|	def f():	|
|	1165	|	test_operators.py	|	def test_alignment_non_pandas(self):	|
|	739	|	test_operators.py	|	def test_arith_alignment_non_pandas_object(self, values):	|
|	339	|	test_operators.py	|	def test_arith_flex_frame(self):	|
|	682	|	test_operators.py	|	def test_arith_flex_series(self):	|
|	442	|	test_operators.py	|	def test_arith_flex_zero_len_raises(self):	|
|	529	|	test_operators.py	|	def test_arith_getitem_commute(self):	|
|	519	|	test_operators.py	|	def test_arith_mixed(self):	|
|	713	|	test_operators.py	|	def test_arith_non_pandas_object(self):	|
|	455	|	test_operators.py	|	def test_binary_ops_align(self):	|
|	561	|	test_operators.py	|	def test_bool_flex_frame(self):	|
|	950	|	test_operators.py	|	def test_boolean_comparison(self):	|
|	1016	|	test_operators.py	|	def test_combine_generic(self):	|
|	746	|	test_operators.py	|	def test_combineFrame(self):	|
|	891	|	test_operators.py	|	def test_combineFunc(self):	|
|	808	|	test_operators.py	|	def test_combineSeries(self):	|
|	913	|	test_operators.py	|	def test_comp(func):	|
|	155	|	test_operators.py	|	def test_comparison_invalid(self):	|
|	941	|	test_operators.py	|	def test_comparison_protected_from_errstate(self):	|
|	906	|	test_operators.py	|	def test_comparisons(self):	|
|	76	|	test_arithmetic.py	|	def test_df_add_flex_filled_mixed_dtypes(self):	|
|	15	|	test_arithmetic.py	|	def test_df_boolean_comparison_error(self):	|
|	163	|	test_arithmetic.py	|	def test_df_div_zero_array(self):	|
|	153	|	test_arithmetic.py	|	def test_df_div_zero_df(self):	|
|	177	|	test_arithmetic.py	|	def test_df_div_zero_int(self):	|
|	193	|	test_arithmetic.py	|	def test_df_div_zero_series_does_not_commute(self):	|
|	53	|	test_arithmetic.py	|	def test_df_flex_cmp_constant_return_types_empty(self, opname):	|
|	44	|	test_arithmetic.py	|	def test_df_flex_cmp_constant_return_types(self, opname):	|
|	26	|	test_arithmetic.py	|	def test_df_float_none_comparison(self):	|
|	109	|	test_arithmetic.py	|	def test_df_mod_zero_array(self):	|
|	97	|	test_arithmetic.py	|	def test_df_mod_zero_df(self):	|
|	127	|	test_arithmetic.py	|	def test_df_mod_zero_int(self):	|
|	141	|	test_arithmetic.py	|	def test_df_mod_zero_series_does_not_commute(self):	|
|	220	|	test_arithmetic.py	|	def test_df_radd_str_invalid(self, dtype, data):	|
|	243	|	test_arithmetic.py	|	def test_df_radd_str(self):	|
|	33	|	test_arithmetic.py	|	def test_df_string_comparison(self):	|
|	205	|	test_arithmetic.py	|	def test_df_sub_datetime64_not_ns(self):	|
|	226	|	test_arithmetic.py	|	def test_df_with_dtype_radd_int(self, dtype):	|
|	235	|	test_arithmetic.py	|	def test_df_with_dtype_radd_nan(self, dtype):	|
|	671	|	test_operators.py	|	def test_dti_tz_convert_to_utc(self):	|
|	1033	|	test_operators.py	|	def test_inplace_ops_alignment(self):	|
|	1080	|	test_operators.py	|	def test_inplace_ops_identity(self):	|
|	1141	|	test_operators.py	|	def test_inplace_ops_identity2(self, op):	|
|	307	|	test_operators.py	|	def test_invert(self):	|
|	207	|	test_operators.py	|	def test_logical_operators(self):	|
|	252	|	test_operators.py	|	def test_logical_typeerror_with_non_valid(self, op, res):	|
|	257	|	test_operators.py	|	def test_logical_with_nas(self):	|
|	282	|	test_operators.py	|	def test_neg_numeric(self, df, expected):	|
|	290	|	test_operators.py	|	def test_neg_object(self, df, expected):	|
|	301	|	test_operators.py	|	def test_neg_raises(self, df):	|
|	88	|	test_operators.py	|	def test_operators_boolean(self):	|
|	129	|	test_operators.py	|	def test_operators_none_as_na(self):	|
|	34	|	test_operators.py	|	def test_operators(self):	|
|	251	|	test_arithmetic.py	|	def test_ops_frame_period(self):	|
|	75	|	test_operators.py	|	def test_ops_np_scalar(self):	|
|	315	|	test_operators.py	|	def test_pos_numeric(self, df):	|
|	325	|	test_operators.py	|	def test_pos_object(self, df):	|
|	333	|	test_operators.py	|	def test_pos_raises(self, df):	|
|	181	|	test_operators.py	|	def test_timestamp_compare(self):	|
|	65	|	test_arithmetic.py	|	def test_tz_aware_scalar_comparison(self, timestamps):	|

**Comment by mbirdi** [comment]
I think I answered my own question.  I don't think this is a good one for a beginner.  I did make a table for whoever picks this one up next.

**Comment by jbrockmendel** [comment]
These have been pretty thoroughly refactored since the OP, closing.
