### ISSUE TITLE
Series' .get method doesn`t fill missing values with defaults while multiple indexing

### ISSUE THREAD

**Issue by eugenbobrov** [pandas-dev/pandas#23428]
#### Code Sample, a copy-pastable example if possible

```python
x = pd.Series({'a':1, 'b':2, 'c':3, 'd':4})
x.get(['a', 'v'], default=-1)
```

#### Expected Output
```python
pd.Series({'a':1, 'v':-1})
```

#### Current Output
FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

```python
pd.Series({'a':1, 'v':NaN})
```

#### Problem description

I solve one NLP task, where it is need to get transformation from words to its indexes. And when algorithm meets unknown word, it should replace it by unk-symbol index. Here I find a bug for replacing missing values by its defaults. I get future warning about deprecation in using .loc and simple [ ] with missing values. But it`s not correct! Missing values should be replaced by defaults without any warnings and NaNs. Otherwise, any great advantages of Series like of vectorised dictionaries are missing. And warnings about .loc and [ ] is ambiguous, as there are no such methods in code.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-38-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 3.8.0
pip: 10.0.1
setuptools: 40.2.0
Cython: 0.28.5
numpy: 1.15.1
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.5.0
sphinx: 1.7.9
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 2.2.3
openpyxl: 2.5.6
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.1.0
lxml: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.11
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.7.0

</details>

**Comment by gfyoung** [comment]
cc @toobaz

**Comment by jreback** [comment]
``.get()`` is a very specific function, you are attempting to expand this to a full fledged indexer. we already have. too many.

try this for idiomatic pandas.

```
In [3]: x.reindex(['a', 'v'])
Out[3]: 
a    1.0
v    NaN
dtype: float64

In [4]: x.reindex(['a', 'v']).fillna(-1)
Out[4]: 
a    1.0
v   -1.0
dtype: float64
```
