### ISSUE TITLE
when using dark theme and background_gradient - font should go to black?

### ISSUE THREAD

**Issue by afonit** [pandas-dev/pandas#23429]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(0,5,size=(5, 4)), columns=list('ABCD'))

df.style.background_gradient(cmap='viridis')

df.style.background_gradient(cmap='Wistia')
```
#### Problem description
Currently when switching to jupyter lab's dark theme the pandas table output automatically switches to white text which is quite nice.
When applying a style with a color gradient, I have seen more often than not that a black font for the text would be nice.  

I don't think there is any right answer here - because at times even with a black font with some of the color maps it becomes un-readable for both light/dark themes.

Here are some images of color maps being applied side-by-side with the light/dark theme in jupyter lab:

![image](https://user-images.githubusercontent.com/1798497/47801495-b3be4900-dd04-11e8-8d81-c93e26f1992e.png)

Perhaps it would be nice to add a parameter that would enable the choosing of the font color, so one could specify white or black.   

I see from looking here:
https://pandas.pydata.org/pandas-docs/stable/style.html

That I can do this:
```python
df.style.set_properties(**{'color': 'black'}).background_gradient(cmap='Wistia')
```
which produces this:
![image](https://user-images.githubusercontent.com/1798497/47802163-19f79b80-dd06-11e8-84a5-fdf9b6e84fa9.png)

So perhaps
```python
.set_properties(**{'color': 'black'})
```
might be the best option here, but just thinking of doing quick analysis it might be more intuitive/nice to have:
```python
df.style.background_gradient(cmap='Wistia', font_color='black')
```

**Comment by WillAyd** [comment]
Have you tried the `low` and `high` parameters? These are documented as being helpful in these types of situations:

http://pandas.pydata.org/pandas-docs/stable/style.html#Builtin-Styles

**Comment by afonit** [comment]
@WillAyd Thank you for taking the time to educate me on that.
Given how I framed the question - the `low` and `high` parameters do resolve it so I will close the issue.

I do think it would be convenient to change the font color at times, I will see if there is a convenient way to make that a parameter and have that discussion in a pull request.

Thanks again for taking the time.
