### ISSUE TITLE
Parameter nrows is not documented in DataFrame.from_records()

### ISSUE THREAD

**Issue by chrism2671** [pandas-dev/pandas#23445]
`classmethod DataFrame.from_records(data, index=None, exclude=None, columns=None, coerce_float=False, nrows=None)`

The documentation is lacking an explanation for the nrows paramater.

http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.from_records.html

**Comment by jreback** [comment]
iirc this is a duplicate issue can u look

**Comment by chrism2671** [comment]
I did check before posting.

**Comment by gfyoung** [comment]
Seems like a relatively trivial documentation issue.  Should try to add before next release.

@chrism2671 : You are more than welcome to tackle this if you want!

**Comment by enian82** [comment]
I am going to try this one out.

**Comment by rookiedk** [comment]
Is this still open? I would love to make this my first pullrequest to pandas. What exactly does the nrows argument do?

**Comment by nmusolino** [comment]
This parameter is [now documented](https://github.com/pandas-dev/pandas/blob/5b0610b875476a6f3727d7e9bedb90d370c669b5/pandas/core/frame.py#L1468-L1594) in the master branch (for the forthcoming 0.24 release), and this issue can be closed.  

Link to master branch documentation:  http://pandas-docs.github.io/pandas-docs-travis/generated/pandas.DataFrame.from_records.html?highlight=from_records#pandas.DataFrame.from_records
