### ISSUE TITLE
Inconsistent date parsing between to_datetime / pd.Timestamp and slicing

### ISSUE THREAD

**Issue by wavexx** [pandas-dev/pandas#23449]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
tmp = pd.Series(index=pd.date_range('2018-01-01 00:00', '2018-12-31 00:00', freq='1d'))
print(len(tmp['2018-09-04 00:00':'2018-09-06 00:00']))
print(len(tmp[pd.Timestamp('2018-09-04 00:00'):pd.Timestamp('2018-09-06 00:00')]))
print(len(tmp[pd.to_datetime('2018-09-04 00:00'):pd.to_datetime('2018-09-06 00:00')]))
```
#### Problem description

In the sample code we generate a Series with a DatetimeIndex which has one value per day. We then try to index the same time range (provided in the same format) in three ways which should lead to identical results.

Unfortunately, the output is as follows:

```
62
3
3
```

String-based indexing using the most obvious method ``tmp['2018-09-04 00:00':'2018-09-06 00:00']`` parses the date in an inconsistent way (as %Y-%d-%m and not as %Y-%m-%d as everywhere else).

I didn't notice this odd parsing in any other place so far, and I didn't find any specific bug report about inconsistent parsing of strings without a time format. The specific format is irrelevant here: the key point is that it should be consistent everywhere.

Note also that the default locale of my system has ``LC_TIME=en_DK`` set, which uses ISO date formats in all programs that to time parsing/formatting using glib. I *also* expect python code to follow my locale settings when no format is provided.

#### Expected Output

The range should be 3 days.

#### Output of ``pd.show_versions()``

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Linux
OS-release: 4.18.0-2-amd64
machine: x86_64
processor:
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.3
pytest: None
pip: None
setuptools: 40.4.3
Cython: 0.28.4
numpy: 1.14.5
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 5.8.0
sphinx: None
patsy: 0.5.0+dev
dateutil: 2.7.3
pytz: 2018.7
blosc: None
bottleneck: None
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 2.2.2
openpyxl: 2.4.9
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: 4.2.5
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: 2.7.5 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
```

**Comment by wavexx** [comment]
Uhm, no, LC_TIME has nothing to do with it. However I noticed that I can reproduce the issue on a long-lived session, but not on a short-lived one. There's something else going on.. I'll dig deeper.

**Comment by mroeschke** [comment]
Feel free to reopen when you can provide more details.
