### ISSUE TITLE
pd.read_fwf ignoring a space when reading space delimited file

### ISSUE THREAD

**Issue by paulvija** [pandas-dev/pandas#23455]
#### Code Sample
```python
temperature_lst=
   41485    177.40357149    -39.01654000   13.000    13.92  .0100  .2000    -1.02  .0100  .2000          
   41489    171.56518149    -42.94461000  743.000     7.29  .0100  .3333      .51  .0100  .3333        
df = pd.read_fwf('./temperature_lst',names=['agn','longt','lat','v1','v2','v3', 'v4','v5','v6', 'v7'])

df.tail()
agn       longt       lat     v1     v2    v3      v4    v5    v6      v7
41485  177.403571 -39.01654   13.0  13.92  0.01  0.2000  1.02  0.01  0.2000
41489  171.565181 -42.94461  743.0   7.29  0.01  0.3333  0.51  0.01  0.3333
```
#### Problem description
temperature_lst is a space delimited file, when using read_fwf to read this in to a dataframe some space is truncated in column 'v5'. This results in '-1.02' becoming just '1.02'. 
Is this is a bug?

However, this works when 'widths' is defined. In my case, there are multiple files that are read in this way, so using 'widths' can be tedious.
 
```python
 df = pd.read_fwf('./11068_temperature_anom.lst',names=['agn','longt','lat','v1','v2','v3', 'v4','v5',
    ...: 'v6', 'v7'], widths=[8,16,16,9,9,7,7,9,7,7])
```

**Comment by dsaxton** [comment]
Can you rework your example so that it's valid code?  (In any case if I try creating a sample file with the contents of temperature_lst I seem to get a correct result, so it may be that the file you're referencing is malformed.)

**Comment by TomAugspurger** [comment]
See http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports for writing examples. You should be able to use StringIO to make an example, no need for a separate text file.

**Comment by TomAugspurger** [comment]
Closing, let us know if you think there's still something to be done @paulvija.
