### ISSUE TITLE
DOC: Template Timestamp & NaT docstrings

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#23458]
Currently some NaT's method docstrings directly mirror Timestamp's method docstrings via copy and pasting.

e.g.

https://github.com/pandas-dev/pandas/blob/4f717551b8e49ecd978bb4f5a985d6f6a96d86e9/pandas/_libs/tslibs/timestamps.pyx#L646-L650

https://github.com/pandas-dev/pandas/blob/4f717551b8e49ecd978bb4f5a985d6f6a96d86e9/pandas/_libs/tslibs/nattype.pyx#L368-L372

We don't want to import Timestamp into `nattype.pyx` to avoid a circular import. Ideally we should template the docstrings of both `Timestamps` and `NaT` methods to avoid this copy pasting.

**Comment by jbrockmendel** [comment]
I don’t think this is going to be viable anytime soon.  Maybe as a second-best we could have tests that they are in sync?

**Comment by mroeschke** [comment]
I think we already have tests that they are in sync, but this is just a nice to have for the future.

**Comment by jbrockmendel** [comment]
labelled as blocked, as i dont think anything Appender-like will play nicely with cython

**Comment by mroeschke** [comment]
Since we have a unit test ensuring these are the same. I think that's good enough so closing
