### ISSUE TITLE
Feature suggestion: unnest function for pandas

### ISSUE THREAD

**Issue by abhi-0396** [pandas-dev/pandas#23470]
It would really helpful if there's a function for unnesting  lists in columns into it's own row while repeating other rows on length of the unnest.  I know there are ways to solving this but a function would be a good idea.

A small example to demonstrate the unnest function.
```
## Sample dataframe.
df = pd.DataFrame({'id': [1,2,3],
              'name': [['test','test1','test2'],'test3','test4']})
print (df)

    id                 name
0   1   [test, test1, test2]
1   2                  test3
2   3                  test4

```
**To**,

```
## An example
unnest(df, on = 'name') 

    id   name
0   1    test
1   1   test1
2   1   test2
3   2   test3
4   3   test4

```

**Comment by jreback** [comment]
dupicate of https://github.com/pandas-dev/pandas/issues/16538

this is typically called expode. I suppose would take an implemetation.

**Comment by abhi-0396** [comment]
> duplicate of #16538
> 
> this is typically called expode. I suppose would take an implemetation.

Actually it's called as unnest in R so I've used that as reference. Thanks for pointing me to the duplicate. It's possible to solve but requires multiple chained functions to achieve and is less efficient. A generalized function would be really good to have in pandas.
