### ISSUE TITLE
Stale Bot for Old Issues and PR's?

### ISSUE THREAD

**Issue by gfyoung** [pandas-dev/pandas#23489]
https://probot.github.io/apps/stale/

cc @pandas-dev/pandas-core 

(looking at you @jreback in particular, given the herculean task you periodically undertake of closing and pinging stale PR's for further work or rebasing)

xref [PR Management Email Chain](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/pandas-core-team/yCQ5GA3jzpg/LXB9WYAcAQAJ) (internal)

**Comment by alimcmaster1** [comment]
+1 for something like this!

**Comment by TomAugspurger** [comment]
I’ve never been a fan of these bots when your issue is the one being closed. Do you know if it can be configured to only do pull requests? We have a big backlog of real issues, that just aren’t a priority.

________________________________

**Comment by alimcmaster1** [comment]
@TomAugspurger looking at the [docs](https://github.com/probot/stale) it can be limited to just PRs with something like:

```yml
# Limit to only `issues` or `pulls`
# only: pulls
```

**Comment by datapythonista** [comment]
I'm -1 on this. For the PRs labeled with "Docs" or "Style" (around one quarter of the total), the ones I usually monitor, I wouldn't like any bot to label them as stale or close it. The ones I think they are worth closing it doesn't give me any work to close. And it'd be annoying to have to reopen soon (there are many old ones that there is work going on, or I want to finish myself).

**Comment by jreback** [comment]
we could configure this to act in a limited fashion
though in reaity just having folks go thru older PRs occasionally is enough

**Comment by alimcmaster1** [comment]
Another potential option out there is gitmate which has features like [automatic label setting](https://docs.gitmate.io/Features/Auto_Labelling/) and [finding duplicate issues](https://docs.gitmate.io/Features/Duplicate_Issues/) - I don't have any first hand experience of using it -but could potentially be useful.

**Comment by gfyoung** [comment]
In response to many of the comments, I agree with @jreback that we can use it in a limited fashion.  For starters, there is a lag between when the bot adds the `stale` label and when it closes the PR.  Thus, if you are concerned about getting things auto-closed, you can delay the closing for some time.

**Comment by gfyoung** [comment]
Given the pushback, I'll close this.  Perhaps another day, another time. 🙂
