### ISSUE TITLE
CI: Azure not reporting the end of the build

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#23492]
I think it's not the first time that happens. In GitHub, Azure is supposed to be "In progress":

https://github.com/pandas-dev/pandas/pull/23471/checks?check_run_id=28679218

But in Azure, the job is actually finished:

https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=2351&view=logs

Is there anything that we can do about? I guess it's a bug in Azure. I'll leave that PR untouched for a while, in case it's useful to investigate.

CC: @vtbassmatt @chrisrpatterson

**Comment by vtbassmatt** [comment]
@DavidStaheli can you please take a look?

**Comment by datapythonista** [comment]
@DavidStaheli could you take a look? Will you loose the data to investigate if I commit to the PR?

**Comment by datapythonista** [comment]
I think this has been fixed.
