### ISSUE TITLE
CI: Documentation built but not published in PRs

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#23536]
I was taking a look at the build of the documentation, and it looks like in every PR it is built, but it's not being published:
```
From https://github.com/pandas-dev/pandas-docs-travis
 * [new branch]      gh-pages   -> origin/gh-pages
origin	https://@github.com/pandas-dev/pandas-docs-travis.git (fetch)
origin	https://@github.com/pandas-dev/pandas-docs-travis.git (push)
remote: Anonymous access to pandas-dev/pandas-docs-travis.git denied.
fatal: Authentication failed for 'https://@github.com/pandas-dev/pandas-docs-travis.git/'
```

On commits to master, looks like it's working as expected (we should probably update the url):
```
From https://github.com/pandas-dev/pandas-docs-travis
 * [new branch]      gh-pages   -> origin/gh-pages
origin	https://[secure]@github.com/pandas-dev/pandas-docs-travis.git (fetch)
origin	https://[secure]@github.com/pandas-dev/pandas-docs-travis.git (push)
remote: This repository moved. Please use the new location:        
remote:   https://github.com/pandas-docs/pandas-docs-travis.git        
To https://github.com/pandas-dev/pandas-docs-travis.git
 + 6f622be...de98643 gh-pages -> gh-pages (forced update)
```

Building the docs takes around 45 minutes, so I think we should probably build only when merging the PRs, and save some travis resources? Not sure how to do it, but I guess there is a way inside travis to know if we're in a PR or in a commit to master.

May be in the future we can consider publishing the docs for each PR, but that would require some development, as fixing the error here would publish all PRs into the same place, which is not very useful.

The relevant files are `.travis.yml` and `ci/build_docs.sh`.

CC: @TomAugspurger @jorisvandenbossche

**Comment by TomAugspurger** [comment]
I like building on every PR, since (in theory) we'll be able to fail
documentation builds when something is incorrect
https://github.com/pandas-dev/pandas/pull/22743

Scikit-Learn has a way to upload the built docs on every PR to a unique
URL: https://github.com/pandas-dev/pandas/issues/17921

**Comment by datapythonista** [comment]
Oh, sorry, I missed that PR. That makes sense, I didn't think about it.

Then, the first thing would be to move the docs outside of the allowed failures in travis, which I don't see discussed or implemented there, right?

**Comment by datapythonista** [comment]
Makes sense. Closing, as #22743 and #17921 already cover all what needs to be done.
