### ISSUE TITLE
how to use intervalindex with datetimes?

### ISSUE THREAD

**Issue by randomgambit** [pandas-dev/pandas#23535]
Hello there!

I am struggling with the amazing `intervalindex` new feature. 
Consider this simple example:

```
df = pd.DataFrame({'id' : ['pandas','peanuts'],
                  'inter_left' : [pd.to_datetime('2018-08-01 10:00:00'),
                                  pd.to_datetime('2018-08-01 17:00:00')],
                  'inter_right' : [pd.to_datetime('2018-08-01 12:00:00'),
                                  pd.to_datetime('2018-08-01 18:00:00')]})

Out[81]: 
        id          inter_left         inter_right
0   pandas 2018-08-01 10:00:00 2018-08-01 12:00:00
1  peanuts 2018-08-01 17:00:00 2018-08-01 18:00:00

df_other = pd.DataFrame({'id' : ['jeff','wes'],
                  'inter_left' : [pd.to_datetime('2018-08-01 11:00:00'),
                                  pd.to_datetime('2018-08-01 20:00:00')],
                  'inter_right' : [pd.to_datetime('2018-08-01 13:00:00'),
                                  pd.to_datetime('2018-08-01 22:00:00')]})

Out[85]: 
     id          inter_left         inter_right
0  jeff 2018-08-01 11:00:00 2018-08-01 13:00:00
1   wes 2018-08-01 20:00:00 2018-08-01 22:00:00
```

Here, each row in `df` identifies an individual, and `inter_left` and `inter_right` are the left and right boundaries of the interval at which `id` is observed.

I would like to 'merge' this dataframe with `df_other` with the understanding that an id from `df_other` is merged to an `id` from `df` only if its corresponding interval overlaps the one of `id`.

In the example, only `jeff`, who is there between 11 and 13, overlaps with `pandas`, who is there between 10 and 12.

My understanding is that `intervalindex` can do that. Despite my attempts, I wasnt able to make it work. Is this supposed to be doable?

Thanks!

**Comment by gfyoung** [comment]
cc @jreback

**Comment by randomgambit** [comment]
summoning @jreback :D

**Comment by jreback** [comment]
search on SO there is an example of this

**Comment by jreback** [comment]
https://stackoverflow.com/questions/46525786/how-to-join-two-dataframes-for-which-column-values-are-within-a-certain-range/46526249

**Comment by randomgambit** [comment]
haha @jreback wonderful!! thanks. Its crazy I was able to find https://stackoverflow.com/questions/46364710/finding-matching-intervals-in-pandas-intervalindex but not the pearl you found out.

**Comment by toobaz** [comment]
I guess this is solved
