### ISSUE TITLE
BUG: lib.infer_type broken for IntervalArray / PeriodArray

### ISSUE THREAD

**Issue by h-vetinari** [pandas-dev/pandas#23553]
While working on #23167, I found a regression in IntervalArray / PeriodArray - I'm guessing it's related to the whole EA effort. @jorisvandenbossche @TomAugspurger 

```
>>> import pandas as pd
>>> import pandas._libs.lib as lib
>>> s = pd.Series([pd.Period(2013), pd.Period(2018)], dtype='category')
>>> lib.infer_dtype(s.values.categories)
Traceback (most recent call last):
  File "pandas\_libs\lib.pyx", line 1166, in pandas._libs.lib.infer_dtype
    values = getattr(value, '_values', getattr(value, 'values', value))
TypeError: Cannot convert PeriodArray to numpy.ndarray
>>>
>>> t = pd.Series([pd.Interval(0, 1), pd.Interval(0, 2)], dtype='category')
>>> lib.infer_dtype(t.values.categories)
Traceback (most recent call last):
  File "pandas\_libs\lib.pyx", line 1166, in pandas._libs.lib.infer_dtype
    values = getattr(value, '_values', getattr(value, 'values', value))
TypeError: Cannot convert IntervalArray to numpy.ndarray
```
This was still working in `v0.23.4`:
```
>>> import pandas as pd
>>> import pandas._libs.lib as lib
>>> pd.__version__
'0.23.4'
>>> s = pd.Series([pd.Period(2013), pd.Period(2018)], dtype='category')
>>> lib.infer_dtype(s.values.categories)
'period'
>>>
>>> t = pd.Series([pd.Interval(0, 1), pd.Interval(0, 2)], dtype='category')
>>> lib.infer_dtype(t.values.categories)
'interval'
```

This is due to the fact that `lib.infer_dtype` tries
```values = getattr(value, '_values', getattr(value, 'values', value))```
and both `IntervalArray` / `PeriodArray` do not return a numpy array for `_values` anymore. For `PeriodArray`, it would work if `_values` and `values` were switched, but for `IntervalArray`, *both* `_values` and `values` return the same (non-numpy-array) result.

**Comment by gfyoung** [comment]
While technically not a regression for us (regression means that it broke in the most recent release but was working in the one before that), this should be "restored" to what it was before we release `0.24.0`.

**Comment by jorisvandenbossche** [comment]
Not that I want to discuss semantics too much, but this is for sure a regression :) 
Just one that does not need to end up in an actual release if we fix it now, thanks to @h-vetinari discovering it on master.

**Comment by TomAugspurger** [comment]
What's the expected dtype for

```python
>>> lib.infer_dtype(integer_array([1, np.nan]))
```

Should we basically expect `infer_dtype` to throw away `.dtype` information, and treat it the same as `[1, np.nan]` (so `mixed-integer-float`)?

cc @jreback I suspect you're the most familiar with this.

**Comment by jreback** [comment]
so for this example we would return Int64 (because it’s an actual array) but for a list i would expect the same as now (mixed integer float)

**Comment by jreback** [comment]
i think we could eventually add those
but the inference is used in indexing so i am not sure if changing it now would work

**Comment by h-vetinari** [comment]
milestone ping pong, haha. ;-)

Would this still be acceptable during RC phase? I might be able to make some time.
