### ISSUE TITLE
API: DataFrameGroupBy column subset selection with single list?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#23566]
I wouldn't be surprised if there is already an issue about this, but couldn't directly find one.

When doing a subselection of columns on a DataFrameGroupBy object, both a plain list (so a tuple within the `__getitem__` [] brackets) as the double square brackets (a list inside the `__getitem__` [] brackets) seems to work:

```
In [6]: df = pd.DataFrame(np.random.randint(10, size=(10, 4)), columns=['a', 'b', 'c', 'd'])

In [8]: df.groupby('a').sum()
Out[8]: 
    b   c   d
a            
0   0   5   7
3  18   6  12
4  16   6   9
6  10  11  11
9   3   3   0

In [9]: df.groupby('a')['b', 'c'].sum()
Out[9]: 
    b   c
a        
0   0   5
3  18   6
4  16   6
6  10  11
9   3   3

In [10]: df.groupby('a')[['b', 'c']].sum()
Out[10]: 
    b   c
a        
0   0   5
3  18   6
4  16   6
6  10  11
9   3   3
```

Personally I find this `df.groupby('a')['b', 'c'].sum()` a bit strange, and inconsistent with how DataFrame indexing works.

Of course, on a DataFrameGroupBy you don't have the possible confusion with indexing multiple dimensions (rows, columns), but still.

cc @jreback @WillAyd

**Comment by WillAyd** [comment]
I don't disagree here. There is a difference when selecting only one column (specifically returning a Series vs a DataFrame) but when selecting multiple columns it would be more consistent if we ALWAYS required double brackets brackets. I assume this would also yield a simpler implementation.

Maybe a conversation piece for 1.0? Would be a breaking change for sure so probably best served in a major release like that

**Comment by TomAugspurger** [comment]
I think the hope is for 1.0 to be backwards compatible with 0.25.x.

Do we have a chance to detect this case and throw a FutureWarning (assuming we want to change)?

**Comment by jorisvandenbossche** [comment]
Yeah, if we want, I would think it should be possible with a deprecation cycle.

**Comment by yehoshuadimarsky** [comment]
Can I take a crack at this or has it already been fixed?

**Comment by WillAyd** [comment]
Go for it!

**Comment by yehoshuadimarsky** [comment]
Thanks will do.

**Comment by yehoshuadimarsky** [comment]
take

**Comment by yehoshuadimarsky** [comment]
So this is my first time working on pandas code, and I'm a little confused here, so please bear with me. I'm also new to linking to code on GitHub.

As I understand, when an object calls `__getitem__` by using brackets, if you pass in several keys, they are implicitly converted to a tuple of one key. So `df['a','b']` is really `df[('a','b')]` under the hood.

I'm having trouble in tracing the code path to figure out where exactly the `__getitem__` on the `GroupBy` is actually implemented here:

1. `DataFrame.groupby` is called on the superclass `NDFrame` here https://github.com/pandas-dev/pandas/blob/master/pandas/core/generic.py#L7286
2. This eventually creates the specific DataFrame GroupBy object here https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/generic.py#L818
3. Which is a subclass of `GroupBy` https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/groupby.py#L1040
4. Which is a subclass of `_GroupBy` https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/groupby.py#L357
5. Which has the mixin named `SelectionMixin`, defined in https://github.com/pandas-dev/pandas/blob/master/pandas/core/base.py#L134
6. Which implements `__getitem__` here https://github.com/pandas-dev/pandas/blob/master/pandas/core/base.py#L220
7. Which, if the `key` is a list or tuple, returns `self._gotitem(list(key), ndim=2)`
8. `self._gotitem` needs to be implemented by the respective subclasses, which in this case is the `DataFrameGroupBy` object, and is implemented here https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/generic.py#L1575
9. But all this does is simply create an instance of itself (`DataFrameGroupBy` ) with the `key` (a list/tuple) passed as a slice to the `selection` parameter
10. The `selection` parameter is implemented in the parent `_GroupBy` object, which sets the internal `self._selection` attribute to the `key`
11. This is where I'm lost. How does this actually slice the object and only return a subset of it?

Any help here would be greatly appreciated. Thanks.

**Comment by yehoshuadimarsky** [comment]
@WillAyd @jorisvandenbossche are you able to help point me in the right direction? ☝️

**Comment by yehoshuadimarsky** [comment]
Just to close the loop on my earlier question, I never fully figured out how the slicing happens, but it seems it happens at some Cython layer via the `self._selected_obj` attribute and its `@cache_readonly` decorator. Happily, it didn't end up mattering, as all I needed to do was intercept the call on the `DataFrameGroupBy` to the `__getitem__` method of the `SelectionMixin` by adding its own `__getitem__` method to check if the keys are a tuple and raise the warning there.

**Comment by yehoshuadimarsky** [comment]
Although I will confess to being a bit surprised (disappointed?) in the total lack of response from the pandas developers to my question above. Pandas has a reputation as being a welcoming OSS community, and the question was well-researched and clearly stated, so I thought I'd get a bit more feedback than that. Guess I'll attribute it to the holiday season.

**Comment by jreback** [comment]
@yehoshuadimarsky we have 3000+ issues and constant comments - to be honest we barely have time to triage  on the PRs

even really important things are not necessarily  discussed at length

just like everyone else has limited time - the best way to prompt a discussion is to push a change

**Comment by yehoshuadimarsky** [comment]
Totally understand. Thanks for acknowledging, and more importantly, thanks for the incredibly important work you do in maintaining pandas.

**Comment by kusaasira** [comment]
@yehoshuadimarsky , this was closed, right?

**Comment by yehoshuadimarsky** [comment]
yes

**Comment by Thuoq** [comment]
Thanks for , I at version Pandas I using group[[colone_name,]] so it is  useful and clear code better
