### ISSUE TITLE
PERF: Deprecate casting of index of dates to DatetimeIndex

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#23598]
```python
In [5]: index = pd.Index([pd.Timestamp('2001'), pd.Timestamp('2002')], dtype=object)

In [6]: pd.Series(1, index=index).index
Out[6]: DatetimeIndex(['2001-01-01', '2002-01-01'], dtype='datetime64[ns]', freq=None)
```

This was the root cause of https://github.com/pandas-dev/pandas/pull/23591. Why are we doing that?

Note that this doesn't affect the case of `index=[pd.Timestamp(...), pd.Timestamp(...)]`, as that would have previously been converted to a DatetimeIndex. It seems be only when you have an Index of datetimes.

I'm going through our test cases that hit this now.

**Comment by TomAugspurger** [comment]
We do hit this when concating two series with DTIs with different timezones (at this point we're an object-dtype Index with different tzs). But that raises anyway.

It seems like tz-naive + tz-aware hits this, and actually goes through


```python
In [5]: a = pd.date_range('2000', periods=1, tz='US/Eastern')

In [6]: b = pd.date_range('2000', periods=1)

In [7]: pd.concat([pd.Series(1, a), pd.Series(2, b)])
> /Users/taugspurger/sandbox/pandas/pandas/core/series.py(355)_set_axis()
-> try:
(Pdb) c
Out[7]:
2000-01-01 00:00:00-05:00    1
2000-01-01 00:00:00          2
dtype: int64
```

But, presumably that's another opportunity for improving perf? We can fix this earlier in the `concat` by building a DatetimeIndex rather than an Index of Timestamps.

**Comment by TomAugspurger** [comment]
Ignore that last bit about tz-aware and tz-naive. That returns an object-dtype index.

**Comment by TomAugspurger** [comment]
Ohhhhhhh the dtype of the index depends on the order of arguments passed to concat.

```python
In [2]: a = pd.date_range('2000', periods=1, tz='US/Eastern')

In [3]: b = pd.date_range('2000', periods=1)

In [4]: pd.concat([pd.Series(1, a), pd.Series(2, b)]).index
> /Users/taugspurger/sandbox/pandas/pandas/core/series.py(355)_set_axis()
-> try:
(Pdb) c
Out[4]: Index([2000-01-01 00:00:00-05:00, 2000-01-01 00:00:00], dtype='object')

In [5]: pd.concat([pd.Series(1, b), pd.Series(2, a)]).index
> /Users/taugspurger/sandbox/pandas/pandas/core/series.py(355)_set_axis()
-> try:
(Pdb) c
Out[5]: DatetimeIndex(['1999-12-31 19:00:00-05:00', '2000-01-01 00:00:00-05:00'], dtype='datetime64[ns, US/Eastern]', freq=None)
```

**Comment by jorisvandenbossche** [comment]
In the original issue, I agree that we keep preserve the object dtype in the series constructor.

**Comment by jbrockmendel** [comment]
I think this is the main reason for Index.is_all_dates, so this would also allow #27744
