### ISSUE TITLE
Mixing strings and tuples in an index sometimes throws in an exception when selecting columns.

### ISSUE THREAD

**Issue by antomaly** [pandas-dev/pandas#23610]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
df = pd.DataFrame({"a":[1], ("b", "c"):[2]})
df[["a", ("b", "c")]]
```
results in 
```ValueError: setting an array element with a sequence```

#### Problem description

Arguably this is a bug with np.asarray() (https://github.com/numpy/numpy/issues/12359) but it may be possible to work around it in pandas, e.g. asarray_tuplesafe() seems to be intended to handle this, but in this case does not.

#### Expected Output

```
   a  (b, c)
0  1       2
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Linux
OS-release: 4.17.0-3rodete2-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.22.0
pytest: None
pip: None
setuptools: None
Cython: None
numpy: 1.13.3
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 2.0.0
sphinx: None
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2018.7
blosc: None
bottleneck: None
tables: 3.4.4
numexpr: 2.5
feather: None
matplotlib: None
openpyxl: None
xlrd: 0.9.3
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
why do u think this should actually work? this causes havoc with indexing as it becomes ambiguous

**Comment by antomaly** [comment]
I'm not sure what ambiguity you're referring to. If you mean that it's unclear whether `df[("a", "b")]` should refer to the two columns of `df` with indices `"a"` and `"b"` or to the one column of `df` with index `("a", "b")`, then pandas appears to have already decided that it refers to the latter, even when there is no column in `df` with index `("a", "b")`.
```python
import pandas as pd
df = pd.DataFrame({"a":[1], "b":[2]})
df[("a", "b")]
```
results in 
```
KeyError: ('a', 'b')
```

Pandas also already has the MultiIndex concept which is roughly like using tuples to index dataframes, but but with some extra features on top (and some wonkiness when the tuples have different lengths). So the practice of indexing rows/columns with tuples is built into pandas in one form already, and I assume the syntax is already ironed out to be as unsurprising as possible.

As far as I can tell, pandas is in principle fine with indices containing (immutable? hashable?) objects, you just end up with an `Index(..., dtype=object)` as the index of the dataframe. This would necessarily complicate some of the syntax if the objects are allowed to be lists (because pandas tries to work out whether you mean one column or several columns), but the case where they're tuples seems to be handled nicely already.

**Comment by jreback** [comment]
you are mixing scalars and tuples 
this almost no support

**Comment by gfyoung** [comment]
I would also add `MultiIndex` is considered more `pandas`-idiomatic.  In fact, some cases, we have been discouraging the use of tuples as indices (e.g. `read_csv`).

Given that push and @jreback pushback, I'll close this for now.  If this is decided to be a legitimate bug, we can always reopen.
