### ISSUE TITLE
Why does DatetimeIndex have _timezone in addition to _tz?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#23624]
Name seems redundant.  Can we document why it exists?

ref https://github.com/pandas-dev/pandas/pull/23587#issuecomment-437687293

**Comment by gfyoung** [comment]
Is there a good reason for that redundancy existing?  Otherwise, I might consider looking into deprecating one of them in favor of the other.

**Comment by jbrockmendel** [comment]
That's the question.  _tz is the one we actually use, so _timezone would be the one to remove
