### ISSUE TITLE
CI: Move linux builds from Azure to Travis?

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#23622]
I didn't check in detail, but I'd say that azure auto-cancel is now working (at least I didn't see any repeated PR, which the previous days happened frequently). But even with that, azure is significantly delayed compared to travis.

In #22854, I'm moving the docs build from travis to azure (takes more or less the same than a test suite). This will make things even less balanced (making azure be the bottleneck even more).

Not sure if I'm missing something, but would it make sense to move the 3 Linux jobs in azure to travis?

Also, I see in https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs-vsts?view=vsts#microsoft-hosted-cicd the next sentence: `Public project: Contact us to get your free tier limits increased.`. Does it make sense to check if that's an option?

CC: @TomAugspurger @jreback

**Comment by datapythonista** [comment]
Checked better, and auto-cancel is not yet working, but I think azure is still significantly slower, as when I checked there were no duplicate jobs.

**Comment by jreback** [comment]
yeah i am -1 on moving *more* to azure at this point. travis is pretty solid.

**Comment by datapythonista** [comment]
@jreback following up from whether we should add a new build to azure (https://github.com/pandas-dev/pandas/pull/22854#issuecomment-437691038). Taking a look at this now:

https://dev.azure.com/pandas-dev/pandas/_build?definitionId=1&_a=summary

And after manually cancelling duplicate builds in azure, I count 18 pending builds in azure, and 13 in travis at the time of writing this.

You'll know better, but what I'd do if I'm not missing something:
- Contact Azure to see if they're happy to increase our number of concurrent jobs (for the docs I linked, seems like they should do it)
- Move the 3 Linux builds to Azure (may be I'm missing something here, as I think @TomAugspurger did the opposite recently)
- Keep a single job for what I'm moving to Azure in #22854 (I think it makes sense to move that stuff to azure even if it's slow right now)

**Comment by jreback** [comment]
hmm we should have 10 concurrent in azure (same as in travis)

**Comment by jreback** [comment]
but we can certainly ask to have more :)

**Comment by TomAugspurger** [comment]
I recently moved 3 linux jobs from circle to azure. I'm fine with moving
some of those to Travis, especially if the
doc build is moving the other way.

**Comment by datapythonista** [comment]
Created issue 118111119329971 in Microsoft support, to see if we can get more concurrent jobs.

**Comment by datapythonista** [comment]
Got response, Azure is checking how many concurrent jobs they can give us, but they should be able to increase them. They asked me how many would we liked, those are my numbers:

If I'm not wrong we have 14 jobs in total (including travis...), and each takes around 30 minutes to complete. So, with 15 jobs (5 more than now) we would complete two builds per hour (assuming no other CI).

Yesterday we had 112 builds (this does not count the ones that should be auto-canceled when new commits are added to the same PR before the job is run). That's an average of 4.7 per hour.

So, as an approximate, I think with 30 jobs (4 builds per hour), with auto-cancel working, we'd do ok, even if we have everything in azure-pipelines.

If anyone has a different opinion, please let me know asap, so I can update Azure with it before they decide.

**Comment by jreback** [comment]
that sounds like a good number
though we r not going to switch too much more as we already have 10 concurrent in travis

**Comment by chrisrpatterson** [comment]
panda-dev has been updated to have 30 concurrent jobs now.  Let us know if that is not sufficient.

**Comment by datapythonista** [comment]
Closing, as now with the increase travis is significantly slower than azure-pipelines, so doesn't make sense anymore to move things from azure to travis (may be the other way round).
