### ISSUE TITLE
DOC: Add validation error when a docstring is missing

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#23648]
We have the script `scripts/validate_docstrings.py` that checks several formatting errors in the docstrings.

Currently, when a function, method... has no docstring at all, it fails few of the checks, but we don't have one specific to it. See for example:
```
$ ./scripts/validate_docstrings.py --prefix=pandas.Series.imag
pandas.Series.imag: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.Series.imag: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.Series.imag: No summary found (a short summary in a single line should be present at the beginning of the docstring)
```

What would be useful is to add a new check, that reports that the function does not have a docstring. And in the previous errors, check when the docstring is empty, and do not report them. So the previous call should report a single error with a text like `pandas.Series.imag: No docstring found`.

**Comment by avolkov** [comment]
I'm working on Pandas at PyconCa sprint I'll give it a go.
