### ISSUE TITLE
What is the practical significance of df.DataFrame.ewm?

### ISSUE THREAD

**Issue by zhouhao-learning** [pandas-dev/pandas#23667]
Hello, I met the pd. DataFrame. ewm. mean () function today, but I have done a lot of experiments and can't understand how the results are calculated.
The test code is like this:
```
x = pd.DataFrame([0.0, 1.0, 2.0])
print(pd.DataFrame.ewm(x, span=2).mean())
```
The output is like this:
```
          0
0  0.000000
1  0.750000
2  1.615385
```

I don't understand why this is the result. How did they calculate it? Can you give me some help? Thank you very much!!!

**Comment by WillAyd** [comment]
I'd suggest giving the documentation a look as the page for this has quite some detail, including links to further levels of detail.

Usage questions are better asked on SO. If there's an actual bug that you see in the implementation feel free to come back here with more details. You would want to read up on how to open a bug request first:

http://pandas.pydata.org/pandas-docs/stable/contributing.html#bug-reports-and-enhancement-requests
