### ISSUE TITLE
Fixtures for extension arrays

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#23664]
In https://github.com/xhochy/fletcher/pull/66, @xhochy had to redefine a fixture `box_in_series` that is used in the base test definitions. We should explore how pandas can properly "export" those test fixtures, possibly as a pytest plugin.

**Comment by alimcmaster1** [comment]
I think we should be able to do something like @ikonst suggests [here](https://gist.github.com/peterhurford/09f7dcda0ab04b95c026c60fa49c2a68), let me give it a go

**Comment by ikonst** [comment]
In fact, I wouldn't suggest that anymore, as per [pytest manual](https://docs.pytest.org/en/latest/writing_plugins.html#requiring-plugins-in-non-root-conftests). Instead, I'd import the fixtures into my conftest.py.

Here's how I import fixtures recursively in one of my projects (the 'fixtures' directory is where I keep all my fixtures):
```
from pkgutil import walk_packages

from . import fixtures

for package in walk_packages(fixtures.__path__, prefix=fixtures.__name__ + '.'):
    module = package.module_finder.find_module(package.name).load_module()
    globals().update({k: v for k, v in vars(module).items() if not k.startswith('_')})
```

**Comment by fjetter** [comment]
The way @alimcmaster1 suggested is also similar to how `dask.distributed` is doing it. There the fixtures and all util functions to construct them are exposed as a separate module. See https://github.com/dask/distributed/blob/master/distributed/utils_test.py

For example:

```
from distributed.utils_test import cluster_fixture
def test_something(cluster_fixture):
    assert True
```

or construct your own

```
import pytest
from distributed.utils_test import cluster
@pytest.fixture(scope='session')
def session_scoped_cluster():
    with cluster() as (scheduler, workers):
        yield (scheduler, workers)
```

**Comment by jbrockmendel** [comment]
is this no handled correctly by the extension tests?

**Comment by mroeschke** [comment]
> is this no handled correctly by the extension tests?

I believe so, so closing
