### ISSUE TITLE
DEPR: frequencies.getOffset

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#23672]
`tseries.frequencies` aliases `getOffset = get_offset`.  That has been around and unused for a while, should be deprecated and eventually removed.

`tseries.offsets.generate_range` has a kwarg `time_rule` with docstring description:
```
    time_rule : (legacy) name of DateOffset object to be used, optional
        Corresponds with names expected by tseries.frequencies.get_offset
```

If this is legacy behavior, it should be deprecated and eventually removed.

**Comment by mroeschke** [comment]
There's an issue to depreciate `get_offset` as well. https://github.com/pandas-dev/pandas/issues/4205

**Comment by jbrockmendel** [comment]
getOffset is gone, closing
