### ISSUE TITLE
DataFrame.reindex with specified fill method fails for MultiIndex

### ISSUE THREAD

**Issue by aberres** [pandas-dev/pandas#23693]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

i = pd.MultiIndex.from_tuples([('a', 'b'), ('d', 'e')])
df = pd.DataFrame([[0, 7], [3, 4]], index=i, columns=['x', 'y'])

print(df)
#      x  y
# a b  0  7
# d e  3  4

i2 = pd.MultiIndex.from_tuples([('a', 'b'), ('d', 'e'), ('h', 'i')])
# same behavior
#i2 = pd.MultiIndex.from_tuples([('a', 'b', 'c'), ('d', 'e', 'f'), ('h', 'i', 'j')])

print(df.reindex(i2, axis=0, method='ffill'))
#       x    y
# a b  3.0  4.0
# d e  NaN  NaN
# h i  0.0  7.0

```
#### Problem description

The reindexing operation above introduces a row to the `MultiIndex`. When no fill method is specified the new row is added and filled with NA as expected.

When `ffill` is specified the behavior is not explainable for me. The index is updated as expected but a NA row is added in the middle of the existing data.

#### Expected Output

Not sure if `ffill` for MultiIndexes is designed like this, but I was hoping for

```
#       x    y
# a b  3.0  4.0
# d e  0.0  7.0
# h i  0.0  7.0
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None

pandas: 0.23.4
pytest: 3.7.1
pip: 18.1
setuptools: 39.0.1
Cython: None
numpy: 1.15.0
scipy: None
pyarrow: 0.11.1
xarray: None
IPython: 6.5.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: 1.6.1
bottleneck: 1.2.1
tables: None
numexpr: 2.6.8
feather: None
matplotlib: 3.0.2
openpyxl: 2.5.5
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: 1.2.10
pymysql: None
psycopg2: 2.7.5 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: 0.1.6
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by aberres** [comment]
Interesting:

When the targe index has an additional level and the level 0 is unchanged things work:

```python
i = pd.MultiIndex.from_tuples([('a',), ('d',)])
df = pd.DataFrame([[0, 7], [3, 4]], index=i, columns=['x', 'y'])

i2 = pd.MultiIndex.from_tuples([('a', 'b'), ('a', 't'), ('d', 'e'), ('d', 'f')])
df.reindex(i2, axis=0, method='ffill')
```

When the level 0 is changed again wrong NA rows are introduced:

```python
i = pd.MultiIndex.from_tuples([('a', 'b'), ('d', 'e')])
df = pd.DataFrame([[0, 7], [3, 4]], index=i, columns=['x', 'y'])
i2 = pd.MultiIndex.from_tuples([('a', 'b'), ('a', 't'), ('d', 'e'), ('d', 'f')])
df.reindex(i2, axis=0, method='ffill')
```

**Comment by gfyoung** [comment]
cc @toobaz

**Comment by eddy-geek** [comment]
Here is another example of the almost-identical issue I stumbled onto:

```python
from io import StringIO
rparams = StringIO('''
a,timestamp,foo
A,2018-12-12,12
A,2019-01-02,2.1
A,2019-01-04,4.1
B,2019-01-02,2.2
B,2019-01-04,4.2
''')
rordr = StringIO('''
a,timestamp,bar
A,2019-01-01,1
A,2019-01-02,2
A,2019-01-03,3
A,2019-01-04,4
B,2019-01-01,1
B,2019-01-02,2
B,2019-01-03,3
B,2019-01-04,4
''')
dparams = pd.read_csv(rparams).set_index(['a','timestamp'])
dordr = pd.read_csv(rordr).set_index(['a','timestamp'])
aparams = dparams.reindex(index=dordr.index, method='ffill')

print(aparams)
```
Outputs:
```bash
              foo
a timestamp      
A 2019-01-01  nan     #right (although I'd prefer if it were "12")
  2019-01-02 2.10
  2019-01-03  nan     #wrong
  2019-01-04 4.10
B 2019-01-01 4.10     #right
  2019-01-02 2.20
  2019-01-03 4.10     #wrong
  2019-01-04 4.20
```

**Comment by eddy-geek** [comment]
Code entry-point (and interesting commit to bisect): #9019
