### ISSUE TITLE
pd.read_csv split 'names' string into chars when names is a string

### ISSUE THREAD

**Issue by thesby** [pandas-dev/pandas#23713]
```
pd.read_csv('xxx.csv', names='hello')
```
The columns will be ['h', 'e', 'l', 'l', 'o']
This is not expected.

**Comment by JustinZhengBC** [comment]
The [documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) says names should be an array-like, so passing a string would give undefined behaviour

**Comment by WillAyd** [comment]
As @JustinZhengBC notes this is the documented behavior. The parameter name of `names` would also imply this
