### ISSUE TITLE
pd.to_timedelta unit ignored for string input

### ISSUE THREAD

**Issue by jzwinck** [pandas-dev/pandas#23716]
```python
In : pd.to_timedelta(123456789, unit='s')
Out: Timedelta('1428 days 21:33:09') # ok

In : pd.to_timedelta('123456789', unit='s')
Out: Timedelta('0 days 00:00:00.123456') # oops!

In : pd.to_timedelta('123.45', unit='s')
Out: ValueError('no units specified') # ???
```
#### Problem description

Evidently, the `unit` parameter is ignored when the input is a string (yet strings that look like numbers are accepted as if they were actually numbers).

Reproduced in Pandas 0.21.1 and 0.23.4.

**Comment by gfyoung** [comment]
How odd!  Let's investigate and patch this.

**Comment by jreback** [comment]
ok look for  a similar issue to this one

**Comment by mroeschke** [comment]
xref #12136 https://github.com/pandas-dev/pandas/issues/16791
