### ISSUE TITLE
confusing default behavior of print for bound method

### ISSUE THREAD

**Issue by MLopez-Ibanez** [pandas-dev/pandas#23720]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd
x = pd.DataFrame([[0,1],[3,2]])
x.mean
```
#### Problem description

The above prints
```
<bound method DataFrame.mean of    0  1
0  0  1
1  3  2>
```

I don't see the point of printing the actual dataframe content. With large data frames, the output above is even more confusing. This is very confusing for beginners. 

#### Expected Output
```
<bound method DataFrame.mean>
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-33-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.23.1
pytest: None
pip: 18.1
setuptools: 40.5.0
Cython: None
numpy: 1.14.5
scipy: 0.17.0
pyarrow: None
xarray: None
IPython: 7.1.1
sphinx: 1.3.6
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: 3.2.2
numexpr: 2.4.3
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: 0.7.3
lxml: None
bs4: 4.4.1
html5lib: 0.999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
It doesn't seem like there's an easy way to change the repr of a bound method: https://stackoverflow.com/questions/21344862/can-i-change-a-python-bound-method-objects-str-attribute, or am I reading that wrong?

**Comment by MLopez-Ibanez** [comment]
NumPy seems to work-around this issue somehow:

```python
import numpy as np
a = np.array([1])
a.mean
```
prints
```
<function ndarray.mean>
```

**Comment by TomAugspurger** [comment]
Is that because ndarray is implemented in C?

**Comment by mroeschke** [comment]
Thanks for the issue, but it appears this hasn't gotten traction in a while so closing
