### ISSUE TITLE
DatetimeIndex.to_frame() inconsistent with dti.to_series().to_frame()

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#23728]
For TZ-aware DatetimeIndex, `to_series()` drops the timezone unless we pass `keep_tz=True`

```
>>> dti = pd.date_range('1977-04-15', periods=3, freq='MS', tz='US/Hawaii')

>>> dti.to_series().to_frame().dtypes
0    datetime64[ns]

>>> dti.to_frame().dtypes
0    datetime64[ns, US/Hawaii]
```

IIRC there has been discussion about deprecating the need for `keep_tz`; this should be another reason to do so.

**Comment by jbrockmendel** [comment]
Never mind, this was true in 0.23 but not in master.

**Comment by jbrockmendel** [comment]
Actually, it looks like the `keep_tz` kwarg is not allowed for `to_frame`, so there is an inconsistency, just not the one I first thought.

**Comment by mroeschke** [comment]
Would the idea then be for `to_series` to always preserve the timezone?

**Comment by jbrockmendel** [comment]
I think that's the most reasonable behavior yes.  IIRC there was a historical reason why it wasnt the default.  @jorisvandenbossche I think you've opened an issue about changing this behavior?

**Comment by mroeschke** [comment]
xref https://github.com/pandas-dev/pandas/issues/17832

**Comment by jorisvandenbossche** [comment]
Yes, we should deprecate `keep_tz` in `to_series`, that should make `to_series` and `to_frame` consistent. 
Since that is covered in #17832, I think this can be closed?

**Comment by jorisvandenbossche** [comment]
Opened a PR for it: https://github.com/pandas-dev/pandas/pull/23739
