### ISSUE TITLE
BUG: to_datetime with box=False returning DatetimeIndex with mixed naive and aware datetime.datetimes

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#23722]
xref https://github.com/pandas-dev/pandas/pull/23702#discussion_r233654696

```
In [1]: pd.__version__
Out[1]: '0.24.0.dev0+1022.ga23f90142'

In [2]: import pytz; import datetime

In [3]: pd.to_datetime([datetime.datetime(2018, 1, 1), datetime.datetime(2018, 1, 1, tzinfo=pytz.UTC)], box=False)
Out[3]: DatetimeIndex(['2018-01-01 00:00:00+00:00', '2018-01-01 00:00:00+00:00'], dtype='datetime64[ns, UTC]', freq=None)
```

The current output also is incorrect if `box=True` I believe since the first argument is getting coerced to UTC.

Expected Result

```
In [3]: pd.to_datetime([datetime.datetime(2018, 1, 1), datetime.datetime(2018, 1, 1, tzinfo=pytz.UTC)], box=False)
Out[3]:
array([datetime.datetime(2018, 1, 1, 0, 0),
       datetime.datetime(2018, 1, 1, 0, 0, tzinfo=<UTC>)], dtype=object)

In [4]: pd.to_datetime([datetime.datetime(2018, 1, 1), datetime.datetime(2018, 1, 1, tzinfo=pytz.UTC)], box=True)
Out[4]: Index([2018-01-01 00:00:00, 2018-01-01 00:00:00+00:00], dtype='object')
```

**Comment by jbrockmendel** [comment]
I'm pretty sure this ends up going through the datetime_to_datetime64 branch of to_datetime.  The fix is going to involve merging that into array_to_datetime and handling the tzinfo checks more carefully (like you already did for the string cases).

Did the issue with hashability of dateutil timezones ever get resolved?  I think we're going to need to use actual `set`s of tzinfo objects if extending that to the datetime cases.

BTW note that passing the list in the reversed order raises correctly.

**Comment by jbrockmendel** [comment]
If hashing is still a problem then sets are out; could we map tzinfo objects to unique strings and use a dict?  Actually we might even use the same dict that tslibs.timezones uses

**Comment by mroeschke** [comment]
That could work. We could have a function that does the reverse of `get_timezone` that returns a string from a timezone object and just continue using sets. Would be manageable now with just pytz and dateutil timezones but haven't though too hard about the feasibility.

**Comment by jorisvandenbossche** [comment]
Agreed that the boxing into an index is wrong, but the fact that it is actually parsed into datetime64, is that necessarily wrong? Or if we don't want to parse such a mixture of tz-aware/tz-naive, shouldn't the default be to raise an error?

**Comment by jbrockmendel** [comment]
The raise/not behavior should be determined by the `errors` kwarg I'd assume.  It would not be surprising if the behavior is not internally consistent

**Comment by jorisvandenbossche** [comment]
The expected behaviour is indeed not very well defined (at least not in the docstring). But there is the `errors` keyword, that is 'raise' by default and not 'ignore'.

Eg with out of range timestamps, by default it raises, but with 'ignore' it gives you back datetime.datetime objects:

```
In [10]: pd.to_datetime([datetime.datetime(1000, 1, 1)])
...
OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1000-01-01 00:00:00

In [11]: pd.to_datetime([datetime.datetime(1000, 1, 1)], errors='ignore') 
Out[11]: Index([1000-01-01 00:00:00], dtype='object')

In [14]: pd.to_datetime([datetime.datetime(1000, 1, 1)], errors='ignore', box=False)
Out[14]: array([datetime.datetime(1000, 1, 1, 0, 0)], dtype=object)
```

And as @jbrockmendel noted above, if you switch the order to put a tz-aware first, it also raises:

```
In [18]: pd.to_datetime([datetime.datetime(2018, 1, 1, tzinfo=pytz.UTC), datetime.datetime(2018, 1, 1)], box=False)
...
ValueError: Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True
```

Although here the `errors='ignore'` option does not work (it still raises the same error).

So there are clearly some inconsistencies that would be nice to solve.

**Comment by jorisvandenbossche** [comment]
And some more inconsistencies:

The equivalent with strings (one tz aware, one not), "works" as well (so this is similar as the case with datetime.datetime):
```
In [26]: pd.to_datetime(["2018-01-01 00:00:00+00:00", "2018-01-02 00:00:00"])                                                                                                                                       
Out[26]: DatetimeIndex(['2018-01-01 00:00:00+00:00', '2018-01-02 00:00:00+00:00'], dtype='datetime64[ns, UTC]', freq=None)
```

But now switching them in order returns datetime.datetime objects:
```
In [27]: pd.to_datetime(["2018-01-01 00:00:00", "2018-01-02 00:00:00+00:00"])                                                                                                                                       
Out[27]: Index([2018-01-01 00:00:00, 2018-01-02 00:00:00+00:00], dtype='object')

In [28]: _.values                                                                                                                                
Out[28]: 
array([datetime.datetime(2018, 1, 1, 0, 0),
       datetime.datetime(2018, 1, 2, 0, 0, tzinfo=tzutc())], dtype=object)

```

**Comment by jorisvandenbossche** [comment]
> these inputs can be "parsed" but shouldn't necessarily raise just because the inputs can't be nicely coerced to datetime64, so returning an array/Index of datetime.datetime objects is okay.

There's certainly some logic in there, but then from a user's standpoint: what's the point of returning those object dtype values (same as input)? I cannot do anything with it, I exactly passed them to `to_datetime` to make it proper datetime64 data. 

Or differently put: if not with `to_datetime`, how can I convert those values (for this example of mixed datetime.datetime values) to datetime64[ns] ?

**Comment by jorisvandenbossche** [comment]
> Or differently put: if not with to_datetime, how can I convert those values (for this example of mixed datetime.datetime values) to datetime64[ns] ?

To answer myself: by passing `utc=True` it should still work I suppose. 
But then, I personally find a default behaviour of raising an informative error message saying that you have mixed tz-aware/tz-naive data and that you can use `utc=True` more useful I think than silently returning the input objects.

**Comment by mroeschke** [comment]
> I cannot do anything with it, I exactly passed them to to_datetime to make it proper datetime64 data

So if this is the minimum assumption (which we should document) for `to_datetime` then yes, we shouldn't ever return `datetime.datetime` objects unless `errors='ignore'`. I can get on board with this behavior.

I have a slight suspicion some internals _may_ depend on retaining mixed timezone or mixed tz-aware/tz-naive values (e.g. I just changed this for parsing utc offsets: https://pandas-docs.github.io/pandas-docs-travis/whatsnew/v0.24.0.html#parsing-datetime-strings-with-timezone-offsets)

**Comment by jbrockmendel** [comment]
There are a number of overlapping issues involved here.  The OutOfBoundsDatetime behavior is a particularly difficult one.  To the extent possible, I think we should consider that separately for the time being.

boxing is currently done at several places inside `to_datetime`.  As a first/early step, can we trim that down to being down in just one place?

**Comment by jorisvandenbossche** [comment]
> boxing is currently done at several places inside to_datetime. As a first/early step, can we trim that down to being down in just one place?

+1

But, I think the original issue was not only about boxing, but also the question about should it return datetime64 data or object data (or raise).

In any case, if you have a mixture of tz-aware and tz-naive values, the behaviour should not depend on the order and which of the two happened to be the first value ..

**Comment by jorisvandenbossche** [comment]
> So if this is the minimum assumption (which we should document) for to_datetime then yes, we shouldn't ever return datetime.datetime objects unless errors='ignore'. I can get on board with this behavior.

I am not sure it will be best in all cases or what we would break when trying to do this, but I think it is at least a "clear" explanation: the function returns datetime64[ns] data (boxed or not), or raises that it cannot do that (by default, the keywords can then still influence it)

**Comment by jbrockmendel** [comment]
I just made a GH Project for to_datetime to collect all of these issues/discussions

**Comment by mroeschke** [comment]
Since `box` was deprecated and removed. This is no longer an issue. Closing
