### ISSUE TITLE
Merging on int64 and object columns, pandas 0.23.4

### ISSUE THREAD

**Issue by YanTianqi** [pandas-dev/pandas#23733]
#### Problem description
Hi, I was trying to merge 2 data frame based on a column named ID, which consists of integer.

In the case the ID column is of type numpy.int64 in one df, and of python native int in the other df. In the latest version of 0.23.4, I received this error 
```
ValueError: Your are tryign to merge on int64 and object columns, If you wish to proceed you should use pd.concat
```
Attached the screenshot of the problem

![image](https://user-images.githubusercontent.com/7760158/48596616-c8e9d780-e994-11e8-97c8-156c4d54634d.png)

I have never encountered this situation in earlier panda version such as 0.22.0. The same code ran without an issue.

May I know what is the purpose of adding this constraint in the upgraded version?

**Comment by TomAugspurger** [comment]
I think https://github.com/pandas-dev/pandas/issues/9780 is the relevant issue.

IIRC, trying to merge between object-dtype columns and more specialized types was causing issues.

**Comment by TomAugspurger** [comment]
Gotcha, I think this will be closed by https://github.com/pandas-dev/pandas/pull/21681, but upcasting to object.
