### ISSUE TITLE
Segfault in pandas.read_csv on bad input

### ISSUE THREAD

**Issue by rgeens** [pandas-dev/pandas#23778]
#### Code Sample

```python
from io import RawIOBase
import pandas as pd
from urllib3.response import HTTPResponse


class BadIO(RawIOBase):
    def read(self, size: int = ...):
        io = HTTPResponse()
        return io.stream()


if __name__ == "__main__":
    f = BadIO()
    pd.read_csv(f)
```
#### Problem description

Running the sample code will trigger a segfault on Linux. While I'm fairly sure that `BadIO` is not returning what it should, I'd expect an error message from pandas instead of a crash.

#### Expected Output

Error about what's wrong with the input.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-39-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: None
pip: 10.0.1
setuptools: 39.1.0
Cython: None
numpy: 1.15.4
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jbrockmendel** [comment]
It looks like `io.stream()` is returning a generator object.  The place you'd want to add a check for that is probably in pd._libs.parsers.  A PR would be welcome.

**Comment by srinivasreddy** [comment]
latest pandas give me this error, not a crash; Ofcourse error could be improved though

```
Traceback (most recent call last):
  File "sr.py", line 14, in <module>
    pd.read_csv(f)
  File "/home/dtdev/workspace/pandas/pandas/io/parsers.py", line 695, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/dtdev/workspace/pandas/pandas/io/parsers.py", line 423, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/dtdev/workspace/pandas/pandas/io/parsers.py", line 882, in __init__
    self._make_engine(self.engine)
  File "/home/dtdev/workspace/pandas/pandas/io/parsers.py", line 1109, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/dtdev/workspace/pandas/pandas/io/parsers.py", line 1799, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 541, in pandas._libs.parsers.TextReader.__cinit__
    self.header, self.table_width, self.unnamed_cols = self._get_header()
  File "pandas/_libs/parsers.pyx", line 742, in pandas._libs.parsers.TextReader._get_header
    self._tokenize_rows(hr + 2)
  File "pandas/_libs/parsers.pyx", line 946, in pandas._libs.parsers.TextReader._tokenize_rows
    raise_parser_error('Error tokenizing data', self.parser)
  File "pandas/_libs/parsers.pyx", line 2124, in pandas._libs.parsers.raise_parser_error
    raise exc_type(old_exc)
TypeError: bad argument type for built-in operation

```
In [1]: import pandas as pd                                                                                                                     

In [2]: pd.show_versions()                                                                                                                      

INSTALLED VERSIONS
------------------
commit: 20ae4543c1d8838f52229830bfae0cc8626801bb
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-862.14.4.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.0.dev0+1089.g20ae454
pytest: None
pip: 18.1
setuptools: 40.6.2
Cython: 0.29.1
numpy: 1.15.4
scipy: None
pyarrow: None
xarray: None
IPython: 7.1.1
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

**Comment by rgeens** [comment]
Can confirm the latest master gives a TypeError exception instead of a crash. Good enough for me.
