### ISSUE TITLE
pytables import broken

### ISSUE THREAD

**Issue by mullenkamp** [pandas-dev/pandas#23773]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

df1 = pd.DataFrame([[0,1,2,3]])
df1.to_hdf('test.h5', 'test')

```
#### Problem description

Something seems broken with either how pandas interacts with pytables or pytables itself.
Reading/writing hdf files produces an import error:

```python

ImportError: HDFStore requires PyTables, "DLL load failed: The specified module could not be found." problem importing

```

Using a fresh conda install of pandas and pytables on Windows 10:

```
conda create -n test1 python=3.6 pandas pytables
```
 

#### Expected Output

It doesn't fail and saves an hdf file.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.4
pytest: None
pip: 18.1
setuptools: 40.6.2
Cython: None
numpy: 1.15.4
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: None
tables: None
numexpr: 2.6.8
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by mullenkamp** [comment]
I was using pytables 3.4.4 for the example above.
Downgrading to pytables 3.4.2 works properly.
They must have broken something from 3.4.2 to 3.4.3.

**Comment by mroeschke** [comment]
Yeah I don't suspect this is a pandas issue. Feel free to reopen if the PyTables maintainers suspect it's a pandas issue.

**Comment by d-wasserman** [comment]
I am not sure this is a pandas issue, but wanted to report that installing pytables 3.4.2 fixed a problem I had with pandas interoperability with pytables 3.5.X.
