### ISSUE TITLE
(row) Index Name with to_html(header=False) is not displayed

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#23788]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np
df = pd.DataFrame(np.zeros((2, 2), dtype=int))
df.index.name = 'index.name'
df.to_html(header=False)
```
<table border="1" class="dataframe">
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

```python
import pandas as pd
import numpy as np
df = pd.DataFrame(np.zeros((2, 2), dtype=int))
df.index = pd.MultiIndex.from_product([['a'], ['b', 'c']], names=[
                'index.name.0', 'index.name.1'])
df.to_html(header=False)
```
<table border="1" class="dataframe">
  <tbody>
    <tr>
      <th rowspan="2" valign="top">a</th>
      <th>b</th>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>c</th>
      <td>0</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

#### Problem description

`to_html(header=False)` is not displaying the (row) Index names. The `header` parameter should be analogous to the `index` parameter and hide the columns Index only and leave the (row) Index names displayed.

to hide the display of the row Index names, the `index_names=False` parameter should be used.

the problem is due to an early return in the composition of the HTML header. the `to_html` parameter `header` should not be confused with the HTML header.

https://github.com/pandas-dev/pandas/blob/deb7b4d5003b939f47e525bcdaceeea48622a73a/pandas/io/formats/html.py#L196-L201

#### Expected Output

<table border="1" class="dataframe">
  <thead>
    <tr>
      <th>index.name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

<table border="1" class="dataframe">
  <thead>
    <tr>
      <th>index.name.0</th>
      <th>index.name.1</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="2" valign="top">a</th>
      <th>b</th>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>c</th>
      <td>0</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.0
pytest: 3.5.1
pip: 10.0.1
setuptools: 39.1.0
Cython: 0.28.2
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

cc @WillAyd

**Comment by gfyoung** [comment]
This isn't just restricted to HTML.  It's a bug across the board, even with `to_csv`.
