### ISSUE TITLE
PERF: series.map(arg) for category is slow if arg is a dict

### ISSUE THREAD

**Issue by colinfang** [pandas-dev/pandas#23785]
Are the following 2 methods equivalent? I have to introduce a `lambda` to gain additional performance when dealing with map of category.

```python
import pandas as pd
x = pd.Series(list('abcd') * 1000).astype('category')
mapper = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
%timeit x.map(mapper)
# 1000 loops, best of 3: 1.11 ms per loop
%timeit x.map(lambda a: mapper[a])
# 1000 loops, best of 3: 291 µs per loop
```

**Comment by gfyoung** [comment]
Interesting.  `x.map(mapper)` and `x.map(lambda a: mapper[a])` produce different results, likely because one recognizes the categorical nature and the other doesn't.

Not sure which result is correct though...

cc @jreback

**Comment by rtlee9** [comment]
Good guess @gfyoung. It looks like `x.map(mapper)` ignores the categorical nature and reindexes all values as opposed to just mapping the categories (see #26015 )
