### ISSUE TITLE
Strange group index in dataframe

### ISSUE THREAD

**Issue by SotiriosNikas** [pandas-dev/pandas#23795]
#### Code Sample, a copy-pastable example if possible

```python

#Use columns names for the dataframe
columns = ["file","kernel","launch","measurement","t","p"]

#Create dataframe
DATA = pd.read_csv(options.csvfile, delimiter=',', header=None, names=columns)

#Delete all the duplicated headers
DATA = DATA[DATA.file != 'kernel_file']

#Group data which have the same file name into different dataframes
df_list = [x[1] for x in DATA.groupby((DATA.file!=DATA.file.shift()).cumsum())]

if options.Data_Processing:
    print("Processing data...")
    #Open a new csv file, which will be used for merging data
    with open("post_processing_energy.csv", "w") as output:
        writer = csv.writer(output, dialect = "excel")
        #Create a header with the following columns 
        writer.writerow(["file","kernel_name","launch_seq","E-average","Power-peak","Power-average","samples","elapsed_time(us)","hum_read_el_time"])
        #Loop over each dataframe which has different filename
        for idx in range(len(df_list)):
            Grouped_Data = df_list[idx].groupby("launch")
            #Loop over all the existed groups
            for i, group in Grouped_Data:
                print(i)


```
#### Problem description

The last line is printing the following:
1
10
100
101
102
103
104
105
106
107
108
109
11
110
111
112
113
114
115
116
117
118
119
12
120
....

#### Expected Output
1
2
3
4
5
6
7
8
9
10
11
...

<details>
Finally, all the groups are shown. But their sequence is not the expected one. Any help, why this happens is welcome
.
I am using the 0.23.4 pandas version and ubuntu 16.04.

Let me know if you need more info.

</details>

**Comment by WillAyd** [comment]
Please see our guide for effective bug reports. Code provided should be *minimal* and *self contained* which is not the case here.

Closing for now but if you can provide a self contained example feel free to reopen
