### ISSUE TITLE
feature isda daycount

### ISSUE THREAD

**Issue by locojay** [pandas-dev/pandas#2379]
http://en.wikipedia.org/wiki/Day_count_convention

add day count convention to timeseries : busdayconvention, daycountconversion
assign : locojay

**Comment by petehuang** [comment]
Hi,

This issue has been inactive for a while. Does this continue to represent a useful enhancement? If not, I recommend closing this issue. Thanks!

**Comment by jreback** [comment]
this is simply a matter of using a bus day or custom timeseries. Closing, but a specific usecase might shed more light.
