### ISSUE TITLE
ENH: Add `pd.DataFrame.strformat` method for simplified string series construction

### ISSUE THREAD

**Issue by ArtinSarraf** [pandas-dev/pandas#23800]
Proposing a method that mimics the python string formatter that allows for simplfied construction of string series, based on existing dataframe columns. Currently, this can be done in one of two ways (probably more).
```python
    >>> df = pd.DataFrame([[1991,'09','05'],[1992,'04','06'],[2018,'12','25']],
                           columns=['year','month','day']) 
```
1) Vectorized concatenations using `df.Col.str.cat` or `df.Col.__add__`. This method can be verbose and cumbersome to read/write:
```python
    >>> df.year.astype(str) + '-' + df.month + '-' + df.day
```
2) Use `df.apply` with string formatting. This method is slow and not easy to read or write either
```python
    >>> df.apply(lambda row: '{year}-{month}-{day}'.format(**row.to_dict()), axis=1).
```

Proposed solution:
```python
    >>> df.strformat('{year}-{month}-{day}')
```

Implementation:

The implementation could look something like this, with some modifications to allow for error handling, positional arguments and format_specs (e.g. `{:.0f}`).

```python
from string import Formatter

def strformat(self, formatter):
    final = pd.Series('', index=self.index)
    for text, col, spec, conv in Formatter().parse(formatter):
        if spec:
            raise ValueError('\'format_spec\' currently not supported')
        if conv:
            raise ValueError('\'conversion\' currently not supported')
        final = final + text + df[col].astype(str)
    return final

pd.DataFrame.strformat = strformat

df.strformat('{year}-{month}-{day}')
```

**Comment by gfyoung** [comment]
Interesting proposal, but uncertain of how broad the use-case is...

cc @jreback

**Comment by jreback** [comment]
there are some issues about allowing a date format argument in .to_string()

but not sure what you are proposing is actually that useful in practice to warrant a new method

**Comment by ArtinSarraf** [comment]
Understood. I don't think there's really much use for it outside of formatting datetimes in the style above
