### ISSUE TITLE
df.any(axis=None) does not perform the expected reduction

### ISSUE THREAD

**Issue by Kimonode** [pandas-dev/pandas#23819]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
df = pd.DataFrame({"A": [1, 1], "B": [1, 0], "C": [0, 0]})
df.any(axis=None)
```
#### Problem description

df.any(axis=None) returns a series:
>A     True
B     True
C    False
dtype: bool

... while it should reduce that series to return a single scalar, as per the documentation.

#### Expected Output

True, as a single scalar

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-36-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: fr_FR.UTF-8
LOCALE: fr_FR.UTF-8

pandas: 0.21.1
pytest: None
pip: 9.0.1
setuptools: 39.0.1
Cython: None
numpy: 1.13.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by TomAugspurger** [comment]
Try upgrading you pandas. It was added in a more recent version than 0.21.1
