### ISSUE TITLE
Concat Series[datetimetz] & Series[category] loses timezone

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#23816]
```python

In [8]: a = pd.Series(pd.date_range('20170101', periods=4, tz='US/Pacific'))

In [9]: b = pd.Series(['a', 'b'], dtype='category')

In [10]: pd.concat([a, b], ignore_index=True)[0]
Out[10]: Timestamp('2017-01-01 08:00:00')

```

Out[10]  should have a tz like the following

```python
In [11]: pd.concat([a, b.astype(object)], ignore_index=True)[0]
Out[11]: Timestamp('2017-01-01 00:00:00-0800', tz='US/Pacific', freq='D')
```

**Comment by evangelineliu** [comment]
Hi,

Can my team and I contribute to this issue? 

Thanks.

**Comment by TomAugspurger** [comment]
Sure, you can give it a shot.

I'm not sure where the best place is for the fix yet. Somewhere in `core/dtypes/concat.py`, but it'll be a bit tricky to find the best time to convert to objects.

**Comment by evangelineliu** [comment]
Quick requirements question. When you say the output should have the following format: 

```
In [11]: pd.concat([a, b.astype(object)], ignore_index=True)[0]
Out[11]: Timestamp('2017-01-01 00:00:00-0800', tz='US/Pacific', freq='D')
```
What does "00:00:00-0800" mean? I understand that it would be hours:mins:secs but what is the dash 0800 for?

**Comment by evangelineliu** [comment]
Okay I'll take a look at the suggested change. Thanks!

**Comment by evangelineliu** [comment]
This should be closed

**Comment by jreback** [comment]
@evangelineliu things are closed with a merged pull request
