### ISSUE TITLE
pd.DataFrame.sub change the original dataframe order

### ISSUE THREAD

**Issue by Syhen** [pandas-dev/pandas#23822]
#### Code Sample, a copy-pastable example if possible

```python
df1 = pd.DataFrame([[2], [4], [4], [3]])
df1.index = [0, 1, 2, 1]
df2 = pd.DataFrame([[10], [12]])
df2.index = [1, 2]
df3 = df1 - df2
print(df3.index)
# output: [0, 1, 1, 2]
```
#### Problem description
with minus by index, the output change my index from [0, 1, 2, 1] to [0, 1, 1, 2], which change the order of my original DataFrame.

#### Expected Output
[0, 1, 2, 1]

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Darwin
OS-release: 17.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: zh_CN.UTF-8
LOCALE: zh_CN.UTF-8

pandas: 0.22.0
pytest: None
pip: 9.0.1
setuptools: 39.0.1
Cython: None
numpy: 1.14.2
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.3.1
sphinx: None
patsy: 0.5.0
dateutil: 2.7.2
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.1.0
openpyxl: 2.4.9
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: 4.1.1
bs4: 4.6.3
html5lib: 0.9999999
sqlalchemy: 1.2.4
pymysql: 0.8.0
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by WillAyd** [comment]
Hmm OK. Not sure if we really want to make guarantees about order here based off of the left hand side of an operation but open to investigation and a PR if it makes sense

**Comment by jbrockmendel** [comment]
> which change the order of my original DataFrame.

To be clear, this does _not_ change `df1` inplace.  Its just that the index you get on `df3` doesn't match the index on `df1`, which is not the behavior you want?

To make this work we would need to either change the behavior of `DataFrame.align` or special-case arithmetic behavior, neither of which seem likely (though you're welcome to make a case for it if you feel strongly about it)

Your best bet is to do `df2 = df2.reindex(df1.index)` before doing the subtraction operation

**Comment by mroeschke** [comment]
It appears this is more-or-less the expected behavior here since it would require changing the functionality of other methods. Going to close due to staleness, but happy to reopen if there are further opinions on this being the incorrect behavior
