### ISSUE TITLE
CI: Move CircleCI job to Azure pipelines

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#23821]
We've been moving our CI from other systems to Travis and Azure Pipelines, which makes things simpler, as we don't need to maintain several CI configuration files, and check for CI errors and logs in different environments.

We have almost everything in those two systems now, except one last job that is in CircleCI. This job requires PostgreSQL and MySQL databases, which hasn't been configured yet in Azure Pipelines. So, some research on how to set up them will be required.

In this issue we should create a new job in Azure Pipelines `ci/azure/linux.yml` equivalent to the one in CircleCI, and remove all CircleCI files `.circleci`.

CC: @TomAugspurger

**Comment by alexander-ponomaroff** [comment]
I would like to work on this.

**Comment by datapythonista** [comment]
That would be great, thanks!

**Comment by alexander-ponomaroff** [comment]
Hey @datapythonista , I’ve been doing some research needed for this issue and I would like to ask for some tips. From what I understand in .circleci, PostgreSQL and MySQL databases are configured through docker. When I was looking into doing this in Azure Pipelines, I found documentation on how to set up MySQL and PostgreSQL natively on linux/windows/mac Azure virtual machine. Also I found a way to build images with Docker, like it is done in .circleci folder, however I need to login using id and password by running “docker login” command. Source: https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=vsts&tabs=yaml.

Sorry if I’m misunderstanding the task, this is my first time working with CI and Docker, but I would like to learn and explore this. I would be grateful for any tips you have.

**Comment by datapythonista** [comment]
Unfortunately I'm not an expert myself in Azure Pipelines or docker. Setting  the db servers natively sounds good unless it's slow. If you want to explore that option, that would be great. I'd check the docker option if that one is too complex or too slow. But if you want to check it, we can see that login you need.

**Comment by alexander-ponomaroff** [comment]
@datapythonista I will try to explore both options and update you on what I decided to use. If you know somebody that may be able to give some tips on this. Please tag them if possible.

**Comment by TomAugspurger** [comment]
> I'm not quite sure if there is some other reason for which the tests that do hit the db are being skipped.

The tests are skipped when we can't connect to the database `pandas_nosetest`. I'm not sure exactly where in the class hierarchy that's done though. So I don't think  all the sql tests are running on azure.

**Comment by TomAugspurger** [comment]
If you go to https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=4052&view=ms.vss-test-web.test-result-details and filter the files for e.g. TestPostgreSQLAlchemy, you'll see skips like

```
<pandas.tests.io.test_sql.TestMySQLAlchemy object at 0x7f2eb6d6fc50> - can't connect to mysql server
```

**Comment by datapythonista** [comment]
That's good to know, I didn't see it when checking the code.

What I'd do for now is to move the CircleCI build to Travis, where the db is already set up. And in a separate PR may be move something that doesn't use the db from travis to azure, so travis builds finish faster.

How does this sound?

**Comment by TomAugspurger** [comment]
I don't really have a preference.

**Comment by datapythonista** [comment]
@alexander-ponomaroff if what I said makes sense to you, can you give it a try? I think it'll make things simpler to have 2 CI systems instead of 3, both for the set up, and when checking the results in a PR.

Related to this PR, I created this issue: #23928

**Comment by alexander-ponomaroff** [comment]
@datapythonista I will be looking into this today and tomorrow. Thanks.

**Comment by alexander-ponomaroff** [comment]
@datapythonista Do I need to move the whole build from CircleCI that happens in install_circle.sh into Travis? Or do I need to move specific tests that happen in CircleCI that don't happen in Travis already? Meaning that I will need to go through all TravisCI files and compare to what's going on in CircleCI.

**Comment by datapythonista** [comment]
I don't think there would be significant differences. I'm working in other PRs on standardizing the scripts used by the CI, so we can always use the same, but with different parameters. Didn't check the CircleCI ones in detail, but the `install_travis`  is not very different from the `setup_conda_environment` used in Azure. And the installation for circle looks very similar to `install_travis`.

So, in my opinion, the end result (not in this PR alone, but after all the cleaning) should be a single installation script used from any CI system. If in some cases we need to install the postgres client, and some others don't, I think the script should have a parameter, or use a environment variable, to be able to set in each call whether we want to install it or not.

In this PR, if you're able to use the travis scripts, with the required modifications, that would be great.

**Comment by datapythonista** [comment]
Just seen that #23924 has been merged, which may slightly affect you, as it standardize the two testing scripts used in the CI into one.

**Comment by datapythonista** [comment]
Finally moved to travis in #24449 and rebalanced the number of jobs later in #24460.
