### ISSUE TITLE
Series.map updates all copies of a DataFrame

### ISSUE THREAD

**Issue by lukas-a-olson** [pandas-dev/pandas#23824]
#### Code Sample

```python
df = pd.DataFrame({'foo':[0,1,2]})
new = df
new['foo'] = new['foo'].map({0:'zero', 1:'one', 2:'two'})

print(df)
```
output:
```
    foo
0  zero
1   one
2   two
```
#### Problem description
When using pd.Series.map on a column of a copied DataFrame, the copy is updated, but so are the original DataFrame and any other copies. This issue does not occur when map is applied to a copy of a Series, however.

#### Expected Output
The original DataFrame should remain unmodified:
```
   foo
0    0
1    1
2    2
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.4.9.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-514.16.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: None
pip: 18.1
setuptools: 40.2.0
Cython: 0.28.5
numpy: 1.15.1
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.5.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: 1.2.11
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
> When using pd.Series.map on a column of a copied DataFrame, the copy is updated

`new = df` doesn't copy. That adds a new reference to the same object `df` references.

**Comment by jreback** [comment]
of course these are references to the same frame
a list objects would do the same

**Comment by lukas-a-olson** [comment]
Why doesn't this happen for a series?
```python
s = pd.Series([0,1,2])
new = s
new = new.map({0:'zero', 1:'one', 2:'two'})
```

**Comment by TomAugspurger** [comment]
You're assigning the output of Series.map to the name `new`.

`s` still refers to the old name. https://nedbatchelder.com/text/names.html
may be helpful.
