### ISSUE TITLE
"map" and  "apply" is very slow for millions rows. Any native support with parallel computation?

### ISSUE THREAD

**Issue by thesby** [pandas-dev/pandas#23852]
"map" and  "apply" is very slow for millions rows. Any native support with parallel computation?

**Comment by jbrockmendel** [comment]
Can you comment on the use case?  What kind of function are you trying to map/apply?  What data dtype(s)?

**Comment by TomAugspurger** [comment]
Dupe of https://github.com/pandas-dev/pandas/issues/13111.

Parallelism is mostly out of scope right now, but that could change in the future.
