### ISSUE TITLE
DataFrame rename fails with TypeError when give a ChainMap instead of a dict

### ISSUE THREAD

**Issue by dave-kirby** [pandas-dev/pandas#23859]
Example code:
```
>>> from collections import ChainMap
>>> import pandas as pd
>>> df = pd.DataFrame({'A': range(1, 11), 'B': np.random.randn(10)})
>>> df.rename(ChainMap({'A': 'a'}, {'B':'b'}), axis='columns')
...
TypeError: 'ChainMap' object is not callable

# also fails if called with the columns parameter:
>>> df.rename(columns=ChainMap({'A': 'a'}, {'B':'b'}))
```
I am trying to rename columns in a DataFrame using mappings from two or more dicts combined using the collections.ChainMap class, but it fails with a TypeError.

The docs for `DataFrame.rename` says

>  mapper, index, columns : dict-like or function, optional
>     dict-like or functions transformations to apply to
>     that axis' values. Use either ``mapper`` and ``axis`` to
>     specify the axis to target with ``mapper``, or ``index`` and
>     ``columns``

the ChainMap class should definitely qualify as "dict-like" since it implements the Mapping protocol:

```
>>> from collections import Mapping
>>> issubclass(ChainMap, Mapping)
True
```

I am using Python 3.6.6 with Pandas 0.23.4.

**Comment by jreback** [comment]
we have an is_dict_like function for this
welcome a PR to fix here (we use this almost everywhere)

**Comment by dave-kirby** [comment]
OK, I will create PR when I have some free time.

**Comment by ma3axaka** [comment]
@dave-kirby I could fix the issue. I have some free time tomorrow.

**Comment by dave-kirby** [comment]
@ma3axaka sorry I am using my work GitHub account so did not see your message over the weekend.  If you still have some free time then go ahead.

**Comment by mroeschke** [comment]
Looks to work on master. Could use a test.

```
In [136]: >>> from collections import ChainMap
     ...: >>> import pandas as pd
     ...: >>> df = pd.DataFrame({'A': range(1, 11), 'B': np.random.randn(10)})
     ...: >>> df.rename(ChainMap({'A': 'a'}, {'B':'b'}), axis='columns')
Out[136]:
    a         b
0   1 -0.527207
1   2 -0.261854
2   3 -0.247372
3   4  0.522214
4   5  0.415626
5   6 -0.361259
6   7 -1.349333
7   8  1.096590
8   9  0.342080
9  10  1.911814

In [137]: >>> df.rename(columns=ChainMap({'A': 'a'}, {'B':'b'}))
     ...:
Out[137]:
    a         b
0   1 -0.527207
1   2 -0.261854
2   3 -0.247372
3   4  0.522214
4   5  0.415626
5   6 -0.361259
6   7 -1.349333
7   8  1.096590
8   9  0.342080
9  10  1.911814

In [138]: pd.__version__
Out[138]: '0.26.0.dev0+684.g953757a3e'
```
