### ISSUE TITLE
CLN: Fixes to conda environment names

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#23851]
We have some inconsistency regarding the names of the conda environment. At the moment, all environments for the CI are named `pandas`, and the environment created locally following the set up instructions (and using `environment.yml`) is named `pandas-dev`.

Then, inside several scripts (e.g. `ci/code_checks.sh`) we do a `source activate pandas`. Which means that the script works well in CI jobs, but it fails locally unless we also have a `pandas` environment locally.

Another thing is that in the CI config we use a `CONDA_ENV` environment variable, and we ignore the conda environment names in the yaml files.

What I would do is:
- Use `pandas-dev` as the environment name in all our conda yaml files
- Create the environments with the environment name in the used yaml file (do not override with `-n $CONDA_ENV` as we do now)
- Do not use `source activate` inside the scripts (use it in the steps in the CI config files when needed). This way when running scripts locally, the current environment will be used

@jreback @TomAugspurger @jorisvandenbossche any objection?

**Comment by jreback** [comment]
this is ok

**Comment by charlesdong1991** [comment]
i will take a look!

**Comment by charlesdong1991** [comment]
Hi, @datapythonista , sorry, i think i do need your help, following your explanation above, i did a small modification to change pandas to pandas-dev, not sure if it's the right place to do... and appreciate a lot if you could give more clarifications

**Comment by TomAugspurger** [comment]
You should be able to fix that with a jupyter kernelspec command. Kernel names don’t have to be tied to environment names, and I think python3 is the default.


________________________________

**Comment by h-vetinari** [comment]
@TomAugspurger Yes, of course, but I don't want my `python3` kernel spec to point to the dev environment. If we're already talking environment names (and the default from `environment.yml`), I think this is a reasonable adaptation.
