### ISSUE TITLE
CLN: fixturize & split test_base

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#23877]
it would be nice to use our ``indices`` fixture rather than the self.indices in ``pandas/tests/test_base.py`` as this is a bit cleaner and more flexible esp with subclasses. We also might consider splitting up test_base.py to some extent by function maybe splitting up to

test_construction
test_set_ops
test_reshaping
test_indexing

would accept multiple PR's to close this.

**Comment by charlesdong1991** [comment]
I would like to give a try if it hasn't been picked. 
And I will appreciate a lot if you could explain a bit clearer about the issue, i haven't found self.indices in `pandas/tests/test_base.py`.

**Comment by nixphix** [comment]
@charlesdong1991 I figured that we need to add fixture for [indexes](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/test_base.py#L170-L194). @jreback I made some changes to test_base could you pls let me know if thats what you wanted to do?

**Comment by SaturnFromTitan** [comment]
take
