### ISSUE TITLE
Initializing one row dataframe with a dictionary of scalars

### ISSUE THREAD

**Issue by MLopez-Ibanez** [pandas-dev/pandas#23876]
#### Code Sample, a copy-pastable example if possible

```python
# This code fails with an error ValueError: If using all scalar values, you must pass an index
client = pd.DataFrame(dict(age=27,
                           job='student',
                           marital='single',
                           education='tertiary'))
# This code works
client = pd.DataFrame([dict(age=27,
                           job='student',
                           marital='single',
                           education='tertiary')])

# This code works
client = pd.DataFrame(dict(age=[27],
                           job='student',
                           marital='single',
                           education='tertiary'))
```
#### Problem description

Perhaps there is a deep reason why the first code fails, but the meaning seems clear (the index should be 0) and the error seems arbitrary. 

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-33-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.23.1
pytest: None
pip: 18.1
setuptools: 40.5.0
Cython: None
numpy: 1.14.5
scipy: 0.17.0
pyarrow: None
xarray: None
IPython: 7.1.1
sphinx: 1.3.6
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: 3.2.2
numexpr: 2.6.8
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: 0.7.3
lxml: None
bs4: 4.4.1
html5lib: 0.999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by jreback** [comment]
why should the first succeed? you are passing all scalars as the message indicates 

this raises because it’s almost always a user error
if you mean a 0 index then pass one explicitly or use a list like construction

**Comment by MLopez-Ibanez** [comment]
With a list I cannot specify column names.

I'm not sure what a user may be expecting from the above code except a 1-row dataframe.
