### ISSUE TITLE
requirements-optional-conda.txt missing

### ISSUE THREAD

**Issue by developing-coder** [pandas-dev/pandas#23883]
[Creating a Python Environment](https://pandas.pydata.org/pandas-docs/stable/contributing.html#creating-a-python-environment) gives the following instructions.
```
# Install the rest of the optional dependencies
conda install -c defaults -c conda-forge --file=ci/requirements-optional-conda.txt
```
However, there is no `requirements-optional-conda.txt` in `ci/`. Build and install commands ran successfully and I can import pandas and print its' version number from `pandas-dev` Python environment.

**Comment by jreback** [comment]
this is revamped in master and new instructions are in the dev docs : http://pandas-docs.github.io/pandas-docs-travis/contributing.html#creating-a-python-environment
