### ISSUE TITLE
Output a pandas dataframe to .XLSB (Excel Binary Workbook) format

### ISSUE THREAD

**Issue by subhsaha** [pandas-dev/pandas#23892]
Output a pandas dataframe to .XLSB (Excel Binary Workbook) format.

**Comment by WillAyd** [comment]
Same concept as #8540

**Comment by subhsaha** [comment]
cool , is anyone working on it ? any idea

**Comment by WillAyd** [comment]
Doesn’t look like it. Would certainly take a PR if you are up for it

**Comment by subhsaha** [comment]
I believe i am not skilled enough , but am ready to take it up .  Might take longer duration if that is fine. 

Thanks
