### ISSUE TITLE
ExtensionArray.shift incorrect for periods larger than length of array

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#23911]
```python
In [9]: from pandas.tests.extension.decimal import to_decimal

In [10]: to_decimal([1, 2]).shift(4)
Out[10]:
DecimalArray(array([Decimal('NaN'), Decimal('NaN'), Decimal('NaN'), Decimal('NaN')],
      dtype=object))
```

The expected output is

```python
>>> to_decimal(['NaN', 'NaN'])
DecimalArray(array([Decimal('NaN'), Decimal('NaN')], dtype=object))
```

similar to categorical

```python
In [12]: pd.Categorical([1, 2]).shift(4)
Out[12]:
[NaN, NaN]
Categories (2, int64): [1, 2]
```

This will need a new base test in `tests/extension/base/methods.py` and a fix in https://github.com/pandas-dev/pandas/blob/a7b187ab42c48342478ed8664145f21578f50622/pandas/core/arrays/base.py#L430

**Comment by Devilmoon** [comment]
Hi,

I would like to try and tackle this issue to bite my teeth into the pandas codebase, however I'm not entirely sure about the expected behaviour of the shift method.

From what I understand, when shift is called, the first _period_ elements (up to the array's len) become NaN, and if period is smaller than the len of the array the original _len-period_ elements become the last _len-period_ elements, respecting the condition that _period_+_len-period_ == len of the original array.

Is this correct?

**Comment by TomAugspurger** [comment]
@Devilmoon thanks. I think your summary is correct.

The implementation is correct when `abs(period) < len(self)`. The only bug is when `periods` is larger (in absolute terms).

The issue is on https://github.com/pandas-dev/pandas/blob/a7b187ab42c48342478ed8664145f21578f50622/pandas/core/arrays/base.py#L454


That should be

```python
        empty = self._from_sequence(
            [self.dtype.na_value] * min(abs(periods), len(self)),
            dtype=self.dtype
        )
 ```

**Comment by varadgunjal** [comment]
@TomAugspurger I had added a similar fix for this yesterday. Except, I also added in code to handle the case where `self` is itself empty (and periods is non-zero).

**Comment by varadgunjal** [comment]
@TomAugspurger I'm trying to grok the correct way to put in a test for this.

I want to understand why a new base test is required under `tests/extension/base/methods.py` - wouldn't `test_container_shift` also cover testing the DecimalArray (generated by `to_decimal`) by casting it to a `Series`? Couldn't we just add the relevant test cases under `@pytest.mark.parametrize` and be done? Or am I thinking about this wrong?

**Comment by TomAugspurger** [comment]
We write base tests for things that should be true of all extension array implementations http://pandas-docs.github.io/pandas-docs-travis/extending.html#testing-extension-arrays

I think something like

```python
def test_shift_large_periods(self, data, na_value):
    data = data[:5]
    result = data.shift(10)
    expected = type(data)._construct_from_sequence([na_value] * 10)
    self.assert_extension_array_equal(result, expected)
```

should work, but I haven't tested it. Maybe also test for `periods=-10`.

**Comment by varadgunjal** [comment]
Understood. Different question, why then should it be in that particular file which contains tests under the `BaseMethodsTest` class that are meant for Series and DataFrame methods?

**Comment by TomAugspurger** [comment]
It could also go under the interface tests.

**Comment by varadgunjal** [comment]
I followed a slightly different approach for the tests in the PR. Please let me know if it is incorrect.
