### ISSUE TITLE
Cython language_level Warning - switch to Python3?

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#23927]
When compiling with Cython the following warning gets issued:

```bash
Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: clones/pandas/pandas/_libs/groupby.pxd
```

Haven't looked into the implications as of yet but probably worth switching to Python3, especially given the upcoming drop of Python2 support

**Comment by jbrockmendel** [comment]
Have you tried this locally?  For me it causes `python setup.py build_ext --inplace` to fail

**Comment by WillAyd** [comment]
Yea it failed pretty miserably. Just for the sake of explicitness I updated the setup.py to have the following line:

```python
directives = {'linetrace': False, 'language_level': 3}
```

Haven't looked in detail but assume it's an issue with how we are doing imports

**Comment by jreback** [comment]
no issue for 0.24.0, just saw the warnings and led me here :>
