### ISSUE TITLE
DataFrame: damage data integrity in conversion and iterations

### ISSUE THREAD

**Issue by ZHANGGU** [pandas-dev/pandas#23965]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd
d = {'col1': [1, 2, 3], 'col2': [4, 5+1j, 6]}
dftemp = pd.DataFrame(d)
dftemp['col2']
dstemp = pd.Series({'col2': [4, 5+1j, 6]})
```
#### Problem description

dftemp['col2'] shows all vaues as below are complex, but there was only one complex value originally

0    (4+0j)
1    (5+1j)
2    (6+0j)

dstemp shows consitent values as those in origin as below:

col2    [4, (5+1j), 6]

NB. once iterating the rows, the values in 'col1' is also converted to complex!

#### Expected Output
0    (4)
1    (5+1j)
2    (6)
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 32
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.4
pytest: None
pip: 18.0
setuptools: 40.5.0
Cython: None
numpy: 1.13.1
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: 1.2.9
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

**Comment by h-vetinari** [comment]
When I run your code, I already get a `col2` that is *all* complex:
```
>>> import pandas as pd
>>> d = {'col1': [1, 2, 3], 'col2': [4, 5+1j, 6]}
>>> dftemp = pd.DataFrame(d)
>>> dftemp
   col1    col2
0     1  (4+0j)
1     2  (5+1j)
2     3  (6+0j)
```
That said, the problem you describe is that the complex values of `'col2'` make `'col1'` complex as well, which is true:
```
>>> list(dftemp.iterrows())
[(0, col1    (1+0j)
col2    (4+0j)
Name: 0, dtype: complex128), (1, col1    (2+0j)
col2    (5+1j)
Name: 1, dtype: complex128), (2, col1    (3+0j)
col2    (6+0j)
Name: 2, dtype: complex128)]
```

The reason for this is that `iterrows` takes a single row of a DataFrame, which has to fit all its data into a single `dtype`. The highest common datatype in this case is complex.

This is expected behavior, but there are two easy solutions to your problem. Either use `.itertuples`, (which doesn't try to coerce everything into a Series of the same dtype, and just uses the values):
```
>>> list(dftemp.itertuples(index=False, name=''))
[(1, (4+0j)), (2, (5+1j)), (3, (6+0j))]
```

That still doesn't solve your case of the complex values where you don't want them in `'col2'`. For that, you would have to make sure that the `DataFrame` constructor does not try to find the best dtype for your column, but force it to use the data as-is.

```
>>> df = pd.DataFrame(d, dtype=object)
>>> # or, slightly better (because then 'col1' can be of dtype int:
>>> df = pd.DataFrame({'col1': [1, 2, 3], 'col2': np.array([4, 5+1j, 6], dtype=object)})
>>> df
   col1    col2
0     1       4
1     2  (5+1j)
2     3       6
>>>
>>> # in both cases:
>>> list(df.iterrows())
[(0, col1    1
col2    4
Name: 0, dtype: object), (1, col1         2
col2    (5+1j)
Name: 1, dtype: object), (2, col1    3
col2    6
Name: 2, dtype: object)]
```

**Comment by ZHANGGU** [comment]
Thanks. Please add this behavior to your documentation, as integrity expectation is always there.

**Comment by jorisvandenbossche** [comment]
@ZHANGGU Thank you for the reproducible example.

> Please add this behavior to your documentation, as integrity expectation is always there.

Can you check the docstring of `iterrows` (https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.iterrows.html), and potentially give ideas how to improve it? It is already clearly mentioned that it does *not* preserve dtypes (so data integrity should not be fully expected), and the example of int and float is given (although I agree that your example with complex is more surprising, but that our the upcasting rules of numpy).

**Comment by mroeschke** [comment]
We're happy to reopen this issue when we could get more information about how we could improve the `iterrows` documentation.
