### ISSUE TITLE
Unable to read large json file of 218MB

### ISSUE THREAD

**Issue by AVI18794** [pandas-dev/pandas#23967]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd
import matplotlib.pyplot as plt
import json
import dask.dataframe as dd
import time
df = pd.read_json('Studies\\01-10Aug.json',chunksize=4000,lines=True)
df=pd.DataFrame(df)
df
```
#### Problem description
While I am trying to load the json file which is of 218 mb  using the syntax 
df = pd.read_json('Studies\\01-10Aug.json',chunksize=4000) it says:- [chunksize can only be passed if lines=True] and while pass the argument line=True and then try to create the dataframe  its not working. Is there any way to load the large json or csv file  for data analysis using pandas.
[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.4
pytest: None
pip: 18.1
setuptools: 40.5.0
Cython: 0.29
numpy: 1.15.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.0.1
sphinx: None
patsy: None
dateutil: 2.7.4
pytz: 2018.6
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.9
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: 1.2.14
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by mroeschke** [comment]
For usage questions please refer to StackOverflow.

The docs state that `chunksize` is used to read in the data via iteration. 
>Return JsonReader object for iteration

You should be able to read in that json file without using `chuncksize` if your system has enough memory.
