### ISSUE TITLE
Wrong argument documentation for reindex_axis

### ISSUE THREAD

**Issue by dargueta** [pandas-dev/pandas#23960]
#### Problem description

The documentation for ``DataFrame.reindex_axis()`` has incorrect documentation for the arguments. The function signature is correct, but the description of ``fill_value`` is missing and  there's a description of a ``tolerance`` argument that isn't accepted by the actual method. This can cause crashes or bad data due to incorrect use of the method.

#### Expected Output

Documentation for the ``tolerance`` argument should be removed, and a description of the ``fill_value`` argument should be added.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Darwin
OS-release: 17.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: None
pip: 18.1
setuptools: 40.6.2
Cython: 0.29.1
numpy: 1.15.4
scipy: None
pyarrow: 0.11.1
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: None
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: 1.2.14
pymysql: None
psycopg2: 2.7.6.1 (dt dec pq3 ext lo64)
jinja2: None
s3fs: 0.2.0
fastparquet: 0.2.0
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by eahogue** [comment]
Hi, I can take care of this if no one else is working on it.

**Comment by eahogue** [comment]
Hm, just a clarification. I don't see a `fill_na` argument, but there is `fill_value` which doesn't have a description. Is that the argument you meant?

I'm looking [here](https://github.com/pandas-dev/pandas/blob/v0.23.4/pandas/core/frame.py#L3568-L3574).

**Comment by eahogue** [comment]
Please take a look. I am not very savvy with github so pls let me know if I should do anything differently.
