### ISSUE TITLE
(Suggestion) Alert user when passing %p and %H in same format

### ISSUE THREAD

**Issue by MrArca9** [pandas-dev/pandas#23977]
#### Code Sample, a copy-pastable example if possible

```python
child['Timestamp'] =  pd.to_datetime(child['Timestamp'], format='%d-%b-%y %H:%M:%S %p')
child.to_csv('test.csv')
```
#### Problem description

Short and sweet, when passing data into a formater 12 hour date time formats will pass when using a 24 hour parser. I don't think there is a way to catch this in code. Considering it will still pass, albeit incorrectly, my suggestion is to notify the user in the output window that they have passed %p (normally reserved for 12 hour formats) with an attempted 24 hour format parse.

###Example Data Conversion

10/27/2018  12:45:00 PM < 10/27/2018  12:45:00 PM
10/27/2018  1:00:00 AM < 10/27/2018  1:00:00 PM

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 32
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.23.4
pytest: None
pip: 18.0
setuptools: 39.0.1
Cython: None
numpy: 1.15.1
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: 1.2.12
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by mroeschke** [comment]
Thanks for the suggestion but it appears this features hasn't had much interest from the core devs and community over the years so closing. Can reopen if there's renewed interest
