### ISSUE TITLE
DatetimeIndex doesn't validate `dtype` argument

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#23986]
```python
In [2]: pd.DatetimeIndex([1, 2], dtype=object())
Out[2]: DatetimeIndex(['1970-01-01 00:00:00.000000001', '1970-01-01 00:00:00.000000002'], dtype='datetime64[ns]', freq=None)
```

this should probably raise.

**Comment by jbrockmendel** [comment]
I’ll work this in to the next PR ( after the current DTA constructor PR goes through).  There is a dtype validation step, but it is only checking that conflicting time zones aren’t being passed

**Comment by alexcwatt** [comment]
I believe this can be closed; @TomAugspurger's example does raise an exception now. The dtype is validated with `_validate_dt64_dtype` to ensure it is either `datetime64[ns]` or `DatetimeTZDtype`.

**Comment by mroeschke** [comment]
Probably worthwhile to add a regression test.
