### ISSUE TITLE
step option does not work for hist

### ISSUE THREAD

**Issue by orena1** [pandas-dev/pandas#23992]
#### Code Sample, a copy-pastable example if possible

```python
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
N = 1000
df = pd.DataFrame({
  'a': np.random.randint(0, 2, N),
  'b': np.random.random(N)
})
plt.figure()
df.groupby('a').hist(histtype='step', ax=plt.gca())
plt.legend()
plt.show()
```

This is what I get:
![image](https://user-images.githubusercontent.com/8983713/49219292-7d471d00-f3db-11e8-9b7a-a9d6c67c2dcf.png)

#### Problem description

This function should create a step hist which is unfilled

>     - 'step' generates a lineplot that is by default
>       unfilled.
> 

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.15.final.0
python-bits: 64
OS: Linux
OS-release: 4.14.65-gentoo
machine: x86_64
processor: Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
byteorder: little
LC_ALL: None
LANG: en_IL.US-ASCII
LOCALE: None.None

pandas: 0.23.4
pytest: 3.8.0
pip: 10.0.1
setuptools: 40.2.0
Cython: 0.28.5
numpy: 1.15.1
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 5.8.0
sphinx: 1.7.9
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 2.2.3
openpyxl: 2.5.6
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.1.0
lxml: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.11
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by orena1** [comment]
[____ ~]$ conda install pandas
Solving environment: done
# All requested packages already installed.

[____ ~]$ conda install matplotlib
Solving environment: done
# All requested packages already installed.


INSTALLED VERSIONS
------------------
commit: None
python: 2.7.14.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-514.26.2.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.23.4
pytest: 3.3.2
pip: 18.1
setuptools: 39.2.0
Cython: 0.27.3
numpy: 1.14.2
scipy: 1.1.0
pyarrow: 0.9.0
xarray: None
IPython: 5.4.1
sphinx: 1.6.6
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.5
feather: 0.4.0
matplotlib: 2.2.2
openpyxl: 2.4.10
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.2.3
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.9
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: 0.1.6
pandas_gbq: None
pandas_datareader: None

**Comment by TomAugspurger** [comment]
Ah, you're using python 2. Matplotlib 3 doesn't support python 2 (if that is indeed the problem).

**Comment by orena1** [comment]
Ok, but pandas should support python 2, right?

**Comment by TomAugspurger** [comment]
Yeah, for now. But we likely won't work around bugs in older versions if
matplotlib (if this is indeed the bug).

I'd recommend creating

1. a python 3 environment with pandas 0.23.4 and your old version of
matplotlib
2. a python 3 environment with pandas 0.23.4 and the latest matplotlib

then we can isolate the problem to py2 vs. py3 or pandas master vs 0.23.4
or old matplotlib vs new matplotlib.

**Comment by mroeschke** [comment]
Guessing this works on master now as Tom mentioned.

**Comment by avinashpancham** [comment]
Would like to help on this, but haven't written test for plots yet. First guess would be to use [pytest-mpl](https://github.com/matplotlib/pytest-mpl) or do you have any other ideas?

**Comment by sparkingdark** [comment]
Wan to work it on @jbrockmendel

**Comment by avinashpancham** [comment]
take
