### ISSUE TITLE
to_sql return inserted row count or list

### ISSUE THREAD

**Issue by pmkroeker** [pandas-dev/pandas#23998]
Potential feature, could `df.to_sql()` return the indexes of the inserted rows? Something like [knex.js Query Builder](https://knexjs.org/#Builder-insert)

```python
inserted = df.to_sql(con=engine, name=example_table, if_exists='replace', index=False)
```
#### Problem description
This would allow for more quickly knowing how many rows have been entered from your dataframe

#### Expected Output
Something like `inserted = 2` if 2 rows have been added. Even better would be `inserted = [24, 25]` where inserted is now a list of the inserted primary keys

**Comment by bobfang1992** [comment]
Is there any development towards this?

**Comment by selfcontrol7** [comment]
Looking forward.

**Comment by taiebnoe** [comment]
That'd be a nice feature!
