### ISSUE TITLE
str.split expand by row

### ISSUE THREAD

**Issue by adace123** [pandas-dev/pandas#24007]
#### Problem description
Currently, setting expand=True in str.split just creates new columns. 
While there is a solution [here](https://stackoverflow.com/questions/47571618/how-to-split-expand-a-string-value-into-several-pandas-dataframe-rows) to expand row-wise, it would be much more convenient if we could specify either 'rows' or 'columns' to the expand kwarg.

**Comment by WillAyd** [comment]
I'm -1 here; I don't think this belong as a keyword as it can be accomplished generally with reshaping

**Comment by mroeschke** [comment]
Thanks for the suggestion but given the lack of discussion and interest from the core team looks like this won't happen. Closing
