### ISSUE TITLE
type integrity failure astype vs read_csv

### ISSUE THREAD

**Issue by MGDMedia** [pandas-dev/pandas#24022]
I'm having a problem with pandas where dataframes loaded from csv seem to revert to their origional dtypes when I set their indexes after processing. Look at this:

```
#Both these dicts contain columns and column types.  They are the same
# except for two records - dtypesA lists columns ('ga:date', 'ga:minute')
# as dtype('O') and dtypesB lists columns ('ga:date', 'ga:minute') as 
# dtype('int64')
dtypesA = {'ga:source': dtype('O'), 'ga:deviceCategory': dtype('O'),
    'ga:country': dtype('O'), 'ga:metro': dtype('O'), 'ga:date': dtype('O'), 
    'ga:minute': dtype('O'), 'ga:channelGrouping': dtype('O'), 'ga:sessions': 
    dtype('int64'), 'ga:transactions': dtype('int64')}

dtypesB = {'ga:source': dtype('O'), 'ga:deviceCategory': dtype('O'),
    'ga:country': dtype('O'), 'ga:metro': dtype('O'), 'ga:date': dtype('int64'), 
    'ga:minute': dtype('int64'), 'ga:channelGrouping': dtype('O'), 'ga:sessions': 
    dtype('int64'), 'ga:transactions': dtype('int64')}

dfA = pd.read_csv("my.csv", dtype=dtypesA)
dfB = pd.read_csv("my.csv", dtype=dtypesB)

#So the only difference between dfA and dfB now is that
# dfA has columns ('ga:date', 'ga:minute') typed as strings
# and dfB has columns ('ga:date', 'ga:minute') typed as
# ints.

dfB = dfB.astype(dtypesA)
dfB.dtypes
>ga:source              object
>ga:deviceCategory      object
>ga:country             object
>ga:metro               object
>ga:date                object
>ga:minute              object
>ga:channelGrouping     object
>ga:sessions             int64
>ga:transactions         int64
>dtype: object

dfA.dtypes
>ga:source              object
>ga:deviceCategory      object
>ga:country             object
>ga:metro               object
>ga:date                object
>ga:minute              object
>ga:channelGrouping     object
>ga:sessions             int64
>ga:transactions         int64
>dtype: object

#now both df's have the same dtypes.

indexCols = ['ga:source', 'ga:deviceCategory', 'ga:country', 'ga:metro', 
    'ga:date', 'ga:minute', 'ga:channelGrouping']

dfA.set_index(indexCols, inplace=True)
dfB.set_index(indexCols, inplace=True)

dfA.reset_index().dtypes
>ga:source              object
>ga:deviceCategory      object
>ga:country             object
>ga:metro               object
>ga:date                object
>ga:minute              object
>ga:channelGrouping     object
>ga:sessions             int64
>ga:transactions         int64
>dtype: object

dfB.reset_index().dtypes
>ga:source              object
>ga:deviceCategory      object
>ga:country             object
>ga:metro               object
>ga:date                int64
>ga:minute              int64
>ga:channelGrouping     object
>ga:sessions             int64
>ga:transactions         int64
>dtype: object

#Aditionally if I do a simple left join, you'll see that
# the indexs of both files don't join:

dfB[len(dfB.columns)] = 1
t = dfA.merge(dfB, how="left", left_index=True, 
right_index=True, suffixes = ('','_y'))
	
t.iloc[:,-1].notnull().any()
>False

#my merge ended up with no '1' values in the column I
# added, mean no indexes matched.

#lastly looking through the pandas docs for 
# DataFrame.reset_index i can use the type detection 
# method there in to determine that the values in 
# my index columns have reverted.

list(enumerate(dfA.index))[1][1][4]
>20180110
list(enumerate(dfA.index))[1][1][5]
>20

list(enumerate(dfB.index))[1][1][4]
>'20180110'
list(enumerate(dfB.index))[1][1][5]
>'20'

#So you can see that the detection of the types
# is different even though i've set both to 
# dtype('0') prior to the .set_index() method.
```

#### Problem description

You can see from the above, that after the I reset the
index my index columns go back to their original
data type instead of the data type I set them to.
Obviously the inability to depend on type consistency is
a big issue.

#### Expected Output

Types remain as declared (astype('O')) when setting and 
resetting index.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.4
pytest: None
pip: 18.1
setuptools: 39.0.1
Cython: None
numpy: 1.15.1
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
>>> 

</details>

**Comment by chris-b1** [comment]
Can you reduce this to a minimal, runnable example?

**Comment by jmarshall9120** [comment]
@chris-b1: I am the OP, this is my personal account, I didn't realize that other account was logged on when I posted.

Here's a minimal I just tested:

Paste the below in a csv:

```
,ga:source,ga:deviceCategory,ga:country,ga:metro,ga:date,ga:minute,ga:channelGrouping,ga:sessions,ga:transactions
0,(direct),desktop,(not set),(not set),20180110,14,Direct,1,5
1,(direct),desktop,(not set),(not set),20180110,20,Direct,1,5
2,(direct),desktop,(not set),(not set),20180110,25,Direct,1,5
3,(direct),desktop,(not set),(not set),20180116,38,Direct,1,5
4,(direct),desktop,(not set),(not set),20180122,33,Direct,1,5
5,(direct),desktop,(not set),(not set),20180126,35,Direct,1,5
```

run this:

```
import pandas as pd
from numpy import dtype

dtypesA = {'ga:source': dtype('O'), 'ga:deviceCategory': dtype('O'),
    'ga:country': dtype('O'), 'ga:metro': dtype('O'), 'ga:date': dtype('O'), 
    'ga:minute': dtype('O'), 'ga:channelGrouping': dtype('O'), 'ga:sessions': 
    dtype('int64'), 'ga:transactions': dtype('int64')}

dtypesB = {'ga:source': dtype('O'), 'ga:deviceCategory': dtype('O'),
    'ga:country': dtype('O'), 'ga:metro': dtype('O'), 'ga:date': dtype('int64'), 
    'ga:minute': dtype('int64'), 'ga:channelGrouping': dtype('O'), 'ga:sessions': 
    dtype('int64'), 'ga:transactions': dtype('int64')}

# replace "my.csv" with the full path of your csv
csvPath = r'C:\Users\jmarshall\Desktop\my.csv'
dfA = pd.read_csv(csvPath, dtype=dtypesA)
dfB = pd.read_csv(csvPath, dtype=dtypesB)

indexCols = ['ga:source', 'ga:deviceCategory', 'ga:country', 'ga:metro', 
    'ga:date', 'ga:minute', 'ga:channelGrouping']

dfA.set_index(indexCols, inplace=True)
dfB.set_index(indexCols, inplace=True)

dfB[len(dfB.columns)] = 1
t = dfA.merge(dfB, how="left", left_index=True, 
right_index=True, suffixes = ('','_y'))
	
t.iloc[:,-1].notnull().any()
```

actual output:
`>False`

expected output:
`>True`

**Comment by chris-b1** [comment]
So I think here is a simpler repro of the fundamental problem
```
from io import StringIO

dfA = pd.read_csv(StringIO('a,b\n1,2'), dtype={'a': dtype('O')})
dfB = pd.reac_csv(StringIO('a,b\n1,2'), dtype={'a': dtype('int64')}).astype({'b': dtype('O')})

type(dfA['a'].values[0])
Out[162]: str

type(dfB['a'].values[0])
Out[163]: int
```

In read_csv `dtype=object` always means strings (pass through the data unparsed).  In astype, as it works in numpy, `dtype=object` boxes the individual values into the appropriate python type.  e.g. 
```python
type(np.array([1,2,3]).astype(dtype('O'))[0])
Out[169]: int
```

I think your best bet here, is to use `str` in place of `dtype('O')` - in both cases will then cast to strings.

**Comment by jmarshall9120** [comment]
Thanks, for the reply.

That's kind of a problematic solution.  In the case I've presented I know the data came from a .csv and is thus can cast to string.  But what if i didn't know where the data was coming from?

I think my real problem here is type consistency when setting indexes.  As it it the DataFrame tells me the data its dtype('O') and it becomes dtype('int64') just by calling `.set_index`.  So any data I use pandas for is now suspect.  

So I guess the question is, that if this isn't a bug, how do I inspect a DataFrame and cast the data types so I can be sure of the out come of `set_index`?

**Comment by chris-b1** [comment]
Casting (`astype`) to `dtype('O')` is almost always a bad idea (at least off the top of my head) - the issue isn't really `set_index` - it's that cast that put your data in an odd state - integer values boxed in a object dtype.

And it of course depends, but in the general use of pandas, there shouldn't be a lot of casting/dtype specifying required.  e.g., typically in read_csv you'd only specify a type if necessary to override the inference.

**Comment by mroeschke** [comment]
Sounds like overall this issue was a usage question discussion on object casting. Happy to reopen if there is a simple example of an underlying bug
