### ISSUE TITLE
Python3: Adding multicolumn rows in empty dataframe

### ISSUE THREAD

**Issue by himanshu720** [pandas-dev/pandas#24035]
#### My Code
import pandas as pd
data = pd.read_csv('input_file', header = None, delimiter="\t", names = ['chr', 'sTSS', 'eTSS', 'gene', 'clust1', 'clust2'])

row_filter_column_clust2_1 = pd.DataFrame(columns = data.columns, index=data.index)
row_filter_column_clust2_1.append(data.loc[0]) #Row is not appended
print(row_filter_column_clust2_1) #Nothing is printed

#### Problem description
I want to add the multicolumn rows from the imported file(input_file: see below) into the empty pandas dataframe using .loc function. 
 
#### input_file<tab separated>
chr2	166760255	166760255	Cse1l_tss10	52	5426
chr2	166760282	166760282	Cse1l_tss9	52	5426
chr2	166885599	166886548	IRF8	150.18	5431
chr2	166885925	166885925	Znfx1_tss1	52	5433

#### Expected Output<tab separated>
chr2	166760255	166760255	Cse1l_tss10	52	5426

**Comment by TomAugspurger** [comment]
IIUC, you're expecting `DataFrame.append` to be inplcae. It's not: http://pandas-docs.github.io/pandas-docs-travis/generated/pandas.DataFrame.append.html

You probably don't want to use append anyway.

**Comment by himanshu720** [comment]
@TomAugspurger 
Thank you for your reply. I tried as per the tutorial. I think I am using in the way given in the link you shared (please see below). But it is not working. I am biologist just started with Python. Your help is appreciated if you correct the code.

row_filter_column_clust2_1.append(data.loc[0])

**Comment by TomAugspurger** [comment]
I think you need to assign the output of that line to something, either a new variable or the same one.

**Comment by himanshu720** [comment]
Thank you for help. It is working fine now.
