### ISSUE TITLE
ENH: Support datetime.time objects with tzinfo in between_time and at_time

### ISSUE THREAD

**Issue by cozgenc** [pandas-dev/pandas#24043]
The functions for DataFrame, "between_time" and "at_time" are unfortunately not time zone aware.

I suggest adding a timezone parameter to these functions to clearly specify which time zone the requested time belongs to. The sampler should take into account the time zone of data frame, and the supplied time zone.

It will also be interesting to be able to sample at a specific time both daylight savings adjustment aware and agnostic. For example it will be interesting to sample at every 09:00 New York time (whether it is summer time or winter time, and irrespective of how we stored the time in our dataframe). For this a time zone parameter will not be sufficient, a time zone history will need to be supplied.

Time zone history for a specific city can be obtained by the user and supplied to the function:
https://www.timeanddate.com/time/zone/usa/new-york

**Comment by mroeschke** [comment]
`between_time` and `at_time` already function when the index is tz-aware (the specified times are local to that timezone). I'm also not clear of the primary concern.

```
In [1]: dti = pd.date_range('2018', periods=3, freq='H', tz='US/Pacific')

In [4]: df
Out[4]:
                           0
2018-01-01 00:00:00-08:00  0
2018-01-01 01:00:00-08:00  1
2018-01-01 02:00:00-08:00  2

In [5]: df.between_time('1:00', '2:00')
Out[5]:
                           0
2018-01-01 01:00:00-08:00  1
2018-01-01 02:00:00-08:00  2

In [6]: df.at_time('1:00')
Out[6]:
                           0
2018-01-01 01:00:00-08:00  1
```

**Comment by cozgenc** [comment]
Please tell me how you will be able to get the rows for US/Eastern 09:00am, if the dataframe time zone is set to Europe/Berlin for example?

You are simply creating dependency between the code that prepared the dataframe, the code that consumes the dataframe. If you add timezone parameter to these functions you may explicitly specify which time you are talking about. Time without a timezone doesn't represent a universal point in time.

**Comment by mroeschke** [comment]
When using `at_time` and `between_time`, specified arguments are assumed to be in the local time relative to the timezone of the DatetimeIndex. Therefore, you can use `tz_convert` to switch between timezones when indexing with these methods.

However, it appears that currently passing `datetime.time` objects with `tzinfo` are not supported yet, which would address your primary concern I believe:

```
In [3]: df
Out[3]:
                           0
2018-01-01 00:00:00-08:00  0
2018-01-01 01:00:00-08:00  1
2018-01-01 02:00:00-08:00  2

In [8]: t_eastern = time(4, tzinfo=pytz.timezone('US/Eastern'))

In [10]: df.at_time(t_eastern)
NotImplementedError: argument 'time' with timezone info is not supported
```
