### ISSUE TITLE
Python3: How to split the tuple generated by the .groupby function in pandas

### ISSUE THREAD

**Issue by himanshu720** [pandas-dev/pandas#24055]
####My Code
data = pd.read_csv('input_file', header = None, delimiter="\t", names = ['chr', 'sTSS', 'eTSS', 'gene', 'clust1', 'clust2'])

dup_clust2 = data.groupby('clust2').filter(lambda x: len(x) > 1)

for element in dup_clust2.groupby('clust2'): 
    print(element)

####Required Output:
split tuple in two lines**
(0    chr2    166760255    166760255    Cse1l_tss10    52.0    5426) 
(1    chr2    166760282    166760282    Cse1l_tss9    52.0    5426)

####Output of my code
(5426,    chr    sTSS    eTSS    gene    clust1    clust2    
0    chr2    166760255    166760255    Cse1l_tss10    52.0    5426    
1    chr2    166760282    166760282    Cse1l_tss9    52.0    5426)

#### Problem description
How to split the tuple generated by the .groupby function in pandas on the basis of new line. Further append all the lines in new tuple

**Comment by mroeschke** [comment]
For usage questions, please use StackOverflow. The issues tracker is for software bugs or enhancement requests.
