### ISSUE TITLE
TST: Implement tests for Date/TimelikeOps directly on array

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#24064]
followup to https://github.com/pandas-dev/pandas/pull/24038, blocked by #24024.

Once #24024 we should move the majority of the tests hitting Date/TimelikeOps over to using the array class, and then have a few tests ensuring that the index index wrapping still works.

**Comment by charlesdong1991** [comment]
has it been picked up? would like to work on it once the PR 24024 is finished

**Comment by TomAugspurger** [comment]
No ones working on it yet. It'll be 1-2 weeks before #24024 is done.

**Comment by charlesdong1991** [comment]
thank you very much for your quick response @TomAugspurger , I will keep an eye on 24024, and then take a shot!

**Comment by jbrockmendel** [comment]
the layout of the test suite is moving away from this being necessary, closing
