### ISSUE TITLE
Explicitly include "private" ExtensionArray methods in API docs

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#24067]
Seems like the developer methods like `_values_for_facotrize` are excluded from autodoc.

http://pandas-docs.github.io/pandas-docs-travis/generated/pandas.api.extensions.ExtensionArray.html#pandas.api.extensions.ExtensionArray

We should be able to explicitly list out the methods / attributes that are public.

May have to change the template to `autosummary/class_without_autosummary.rst` like Categorical.

**Comment by tq0** [comment]
I'll take a look at this one.
