### ISSUE TITLE
TST: Implement lock decorator for single tests

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#24081]
At the moment in the CI, for every build, we run our tests twice, one with a filter to run the tests marked as `single` (`@pytest.mark.single`) and the second one the ones NOT marked as `single` (we call them `multi`).

The reason for this, is that we usually run the tests in parallel (we can use 2 processes in the CI servers), but the tests marked as `single` can't run in parallel, as they need to use resources exclusively (like the clipboard or databases). So, in the run of the `single` tests, we just use one process.

While this approach is working well, it adds some extra complexity to the CI. I think we could avoid this complexity, if we create a decorator that uses `filelock` (https://github.com/benediktschmitt/py-filelock) or something similar that makes sure those `single` tests are not run in parallel.

This way we should be able to call pytest normally and just once.

@jreback @TomAugspurger does this make sense?

**Comment by jreback** [comment]
sure it might make it slightly simpler for the test code but this is not about file contention per say but singular reaources - a database or an Xbuffer

the reason we have marks is to do exactly this kind of splitting

you could maybe run the single in other builds than the multiple but then u lose coverage of running in different kinds of builds
so -1 on this

**Comment by datapythonista** [comment]
Thanks for the feedback, I guess I'm missing something... what's the advantage (or how is it different) of what we've got now?

Now we always run both single and not single, and the single run in a sequential way without being concurrent with any other test.

If we use a lock (a file lock is probably the only reasonable option), we'd always run both single and not single too, and the single won't be concurrent with the other single tests in the same class (because of the lock).

Should the single avoid concurrency also with the not single? Or am I missing something else?

**Comment by jreback** [comment]
@datapythonista you are welcome to try. My point is that when we had these tests running in anything but single threaded / single process mode, we would get occasional failures. This is not great and a source of confusion. Its pretty simple now, and we are using built in features of pytest. Using something else, where its not necessarily designed may or may not work and is sure to add complexity. So i don't see much gain here.

**Comment by datapythonista** [comment]
Fair enough, just wanted to make sure I understood your point.

**Comment by datapythonista** [comment]
@jreback have you seen that `pytest-xdist` has an argument `--dist` that can be used to group tests (for example all the ones in the same file), and it would be guaranteed that they run in the same process.

Do you think using that option will be enough to solve the concurrency problems of the `single` tests? (btw, seems like in `pytest` they use the `serial` marker for what we call `single`)

Docs are here: https://github.com/pytest-dev/pytest-xdist#speed-up-test-runs-by-sending-tests-to-multiple-cpus

**Comment by jreback** [comment]
those options look pretty new to me ; give it a shot!
