### ISSUE TITLE
`pd.Timestamp() + pd.TimedeltaIndex()` drops timezone

### ISSUE THREAD

**Issue by ismell** [pandas-dev/pandas#24094]
#### Code Sample, a copy-pastable example if possible

```python

td = pd.TimedeltaIndex(['00:00:00.059000', '00:00:00.156700'])
start_time = pd.Timestamp('2018-11-30 16:55:21-0700')

idx = start_time + td
# DatetimeIndex(['2018-11-30 23:55:21.059000', '2018-11-30 23:55:21.156700'], dtype='datetime64[ns]', freq=None)

```
#### Problem description
The values are converted to UTC, but the UTC timezone isn't set in the new index. If a timezone conversion is going to occur, it should set the new timezone if one was provided.

#### Expected Output

```python
idx = pd.DatetimeIndex([start_time + td[0], start_time + td[1]])

# DatetimeIndex(['2018-11-30 16:55:21.059000-07:00', '2018-11-30 16:55:21.156700-07:00'], dtype='datetime64[ns, pytz.FixedOffset(-420)]', freq=None)

```

#### Output of ``pd.show_versions()``

<details>

pd.DatetimeIndex([start_time + td[0], start_time + td[1]])
DatetimeIndex(['2018-11-30 16:55:21.059000-07:00', '2018-11-30 16:55:21.156700-07:00'], dtype='datetime64[ns, pytz.FixedOffset(-420)]', freq=None)
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Linux
OS-release: 4.17.0-3rodete2-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: None
pip: 18.1
setuptools: 40.6.2
Cython: None
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jbrockmendel** [comment]
This is fixed in master.  Closing.
