### ISSUE TITLE
BigInt save by to_excel ,the value has changed.

### ISSUE THREAD

**Issue by fcfangcc** [pandas-dev/pandas#24122]
BigInt save by to_excel ,the value has changed, sometimes the value is -8.

```python
In [2]: aaa=pd.DataFrame([947722267893174272,947871269024436488])

In [3]: aaa
Out[3]:
                    0
0  947722267893174272
1  947871269024436488

In [4]: aaa.to_excel('bbb.xlsx')

In [5]: bbb=pd.read_excel('bbb.xlsx')

In [6]: bbb
Out[6]:
                    0
0  947722267893174272
1  947871269024436480
```
#### Problem description

947871269024436488 is change to 947871269024436480

#### Output of ``pd.show_versions()``

<details>

[INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Darwin
OS-release: 17.3.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: zh_CN.UTF-8
LOCALE: zh_CN.UTF-8

pandas: 0.22.0
pytest: None
pip: 18.0
setuptools: 40.0.0
Cython: None
numpy: 1.14.2
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 5.3.0
sphinx: None
patsy: 0.4.1
dateutil: 2.7.0
pytz: 2018.3
blosc: None
bottleneck: 1.2.1
tables: None
numexpr: None
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.9
xlrd: 1.0.0
xlwt: 1.3.0
xlsxwriter: 1.1.1
lxml: 3.7.1
bs4: 4.5.1
html5lib: 0.9999999
sqlalchemy: 1.1.4
pymysql: 0.7.11.None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None]

</details>

**Comment by WillAyd** [comment]
Sounds like overflow. Do you know the size limits for numeric types in Excel?

**Comment by WillAyd** [comment]
IIUC excel only guarantees precision of 15 digits, so this is just a limitation of the tool.

https://support.office.com/en-us/article/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3
