### ISSUE TITLE
Incorrect Timestamp Parsing for ISO8601-like Format

### ISSUE THREAD

**Issue by nathanielatom** [pandas-dev/pandas#24137]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
string = '2016-06-01T02-01-00+00-00'
pd.Timestamp(string)
# Timestamp('2016-06-01 02:00:00+0000', tz='UTC')
```
#### Problem description

The minute is parsed incorrectly. I know this isn't exactly an ISO8601 formatted timestamp, but it comes from a filename which doesn't support the use of colons. I was caught a bit off-guard by the silently incorrect value, I think raising a ValueError would be preferable. But the resulting timestamp is _pretty_ close, so full parsing support would be nice.

#### Expected Output

Timestamp('2016-06-01 02:01:00+0000', tz='UTC')

#### Output of ``pd.show_versions()``

<details>

In [9]: pd.show_versions()                                                                                                                                                                   

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_CA.UTF-8
LOCALE: en_CA.UTF-8

pandas: 0.23.4
pytest: 4.0.1
pip: 18.1
setuptools: 40.2.0
Cython: 0.28.5
numpy: 1.14.5
scipy: 1.1.0
pyarrow: None
xarray: 0.10.9
IPython: 7.1.1
sphinx: 1.8.1
patsy: 0.5.0
dateutil: 2.7.5
pytz: 2018.5
blosc: None
bottleneck: None
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.0
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: 1.0.7
lxml: None
bs4: 4.6.0
html5lib: 0.9999999
sqlalchemy: 1.2.8
pymysql: 0.8.1
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by mroeschke** [comment]
This datetime string is most likely hitting our dateutil parser which gives the same result:

```
In [2]: dateutil.parser.parse('2016-06-01T02-01-00+00-00')
Out[2]: datetime.datetime(2016, 6, 1, 2, 0, tzinfo=tzutc())
```

You may want to raise this example with dateutil since pandas is just passing through at this point. pandas will only raise if the datetime string is totally unparseable.

For your use case, you should specify the `format` directly with `to_datetime`

```
In [8]: pd.to_datetime('2016-06-01T02-01-00', format='%Y-%m-%dT%H-%M-%S')
Out[8]: Timestamp('2016-06-01 02:01:00')
```

**Comment by nathanielatom** [comment]
Thanks, created https://github.com/dateutil/dateutil/issues/845. The timestamp is created in a function that accepts arbitrary input for timestamp format, this is just one format example.
