### ISSUE TITLE
Alternative implementation for `.where` on EA-backed Indexes

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#24144]
Followup to https://github.com/pandas-dev/pandas/pull/24114.

Right now `Categorical.where` and `IntervalIndex.where` involve converting to objects.

We could use an alternative implementation that copies the underlying array and sets the values. 
https://github.com/pandas-dev/pandas/pull/24114#issuecomment-444571081 should give a rough idea of the kinds of speedups you'd get.

**Comment by charlesdong1991** [comment]
would like to take a shot, but not sure if i am capable of finishing it... in old `where`, it uses `np.where` along with `cond` and `other` to get values first, and then assign a `Categorical`, so the alternative i understand is to create the `Categorical` first, and directly set value based on `cond` and `other` so as to get rid of `np.where`? is it correct?

**Comment by charlesdong1991** [comment]
I am sorry to bother, could I ask you a question, each time when i tried to do the pytest, even with no change at all after git rebase, I got `ImportError while loading conftest '/Users/kaiqi/pandas/pandas/tests/indexes/conftest.py'.
pandas/tests/indexes/conftest.py:21: in <module>
    tm.makeCategoricalIndex(100),
pandas/util/testing.py:1902: in makeCategoricalIndex
    return CategoricalIndex(np.random.choice(x, k), name=name, **kwargs)
pandas/core/indexes/category.py:129: in __new__
    dtype)
pandas/core/indexes/category.py:192: in _create_categorical
    dtype=dtype)
pandas/core/arrays/categorical.py:413: in __init__
    raise NotImplementedError("> 1 ndim Categorical are not "
E   NotImplementedError: > 1 ndim Categorical are not supported at this time` error, but i tested on pandas-dev/ci, there is no such problem. Do you have any idea where this problem might come from and how can I fix it locally? thank you so much!!

**Comment by TomAugspurger** [comment]
Did you rebuild the C extensions? `python setup.py build_ext -i`

**Comment by charlesdong1991** [comment]
ahh, it works... @TomAugspurger thanks so much!! i will keep this in mind!!!

**Comment by jbrockmendel** [comment]
Index.where now dispatches to Index.putmask, which has a non-object-casting implementation on ExtensionIndex.  closing.
