### ISSUE TITLE
DOC: update usage of randn in io.rst

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#24148]
In the IO page of the docs (https://github.com/pandas-dev/pandas/blob/master/doc/source/io.rst), there are some occurrences of direct calls to `randn` instead of using the properly imported `np.random.randn` in full, which makes the examples not reproducible if you only imported `import numpy as np`.

A PR that replaces `randn` with `np.random.randn` would thus be very welcome.

**Comment by aliberkhsl** [comment]
Hello,I would work on this issue if possible?

**Comment by charlesdong1991** [comment]
might because randn has been assigned to np.random.randn at very beginning in the import part? `randn = np.random.randn`

**Comment by jorisvandenbossche** [comment]
> randn has been assigned to np.random.randn at very beginning in the import part? 

Yes, that is the reason it currently works in our docs. But, that import is hidden to the viewer of the docs, and is not a standard numpy import. So therefore we want to fix this, with the goal to be able to remove this `randn = np.random.randn`

**Comment by charlesdong1991** [comment]
ok, i see... i will make a small pr on it...
