### ISSUE TITLE
Inside rolling apply idxmax and idxmin on Datetime Index do not work as expected

### ISSUE THREAD

**Issue by dimitar-petrov** [pandas-dev/pandas#24151]
#### Code Sample, a copy-pastable example if possible

```python
ipdb> df
timestamp
2018-07-01 00:01:25.746187    6399.5
2018-07-01 00:01:26.349274    6400.0
2018-07-01 00:01:26.746187    6401.5
2018-07-01 00:01:27.319575    6399.5
2018-07-01 00:01:29.679575    6393.0
dtype: float64
ipdb> df.index
DatetimeIndex(['2018-07-01 00:01:25.746187', '2018-07-01 00:01:26.349274',
               '2018-07-01 00:01:26.746187', '2018-07-01 00:01:27.319575',
               '2018-07-01 00:01:29.679575'],
              dtype='datetime64[ns]', name='timestamp', freq=None)
ipdb> df.index.is_monotonic_increasing
True
ipdb> df.idxmin()
Timestamp('2018-07-01 00:01:29.679575')
ipdb> df.idxmax()
Timestamp('2018-07-01 00:01:26.746187')
ipdb> df.reset_index()
                   timestamp       0
0 2018-07-01 00:01:25.746187  6399.5
1 2018-07-01 00:01:26.349274  6400.0
2 2018-07-01 00:01:26.746187  6401.5
3 2018-07-01 00:01:27.319575  6399.5
4 2018-07-01 00:01:29.679575  6393.0
ipdb> 
```
#### Problem description

Using rolling apply with timedelta offset, starts breaking idxmin and idxmax unexpectedly by returning the opposite value.
Could not isolate simple example but I am able to put a BP and investigate the state of the live objects.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
ipdb> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Linux
OS-release: 4.18.16-arch1-1-ARCH
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 4.0.0
pip: 18.1
setuptools: 40.6.2
Cython: None
numpy: 1.15.4
scipy: 1.1.0
pyarrow: 0.11.1
xarray: 0.11.0
IPython: 7.1.1
sphinx: 1.8.2
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.7
blosc: 1.6.2
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: 0.1.6
pandas_gbq: None
pandas_datareader: 0.7.0

</details>

**Comment by TomAugspurger** [comment]
Can you reproduce this outside of rolling?

```python
In [16]: index = DatetimeIndex(['2018-07-01 00:01:25.746187', '2018-07-01 00:01:26.349274',
    ...:                '2018-07-01 00:01:26.746187', '2018-07-01 00:01:27.319575',
    ...:                '2018-07-01 00:01:29.679575'],
    ...:               dtype='datetime64[ns]', name='timestamp', freq=None)
    ...: s = pd.Series(1, index=index)

In [17]: s.idxmin()
Out[17]: Timestamp('2018-07-01 00:01:25.746187')

```

looks fine on master.

**Comment by mroeschke** [comment]
Feel free to reopen if you can post a reproducible example.
