### ISSUE TITLE
Hashing ExtensionArrays which factorize to scalar objects with __getitem__ attr fails

### ISSUE THREAD

**Issue by andrewgsavage** [pandas-dev/pandas#24167]
```python
import pint
import numpy as np

from pandas._libs import hashing
ureg = pint.UnitRegistry()
encoding='utf8'
hash_key='0123456789123456'

vals=np.array([(i*ureg.kilogram) for i in range(0,3)],dtype=object)
vals
```

array([<Quantity(0, 'kilogram')>, <Quantity(1, 'kilogram')>,
       <Quantity(2, 'kilogram')>], dtype=object)

```python

hashing.hash_object_array(vals.astype(str).astype(object), hash_key, encoding)
```

----> 1 hashing.hash_object_array(vals.astype(str).astype(object), hash_key, encoding)

ValueError: setting an array element with a sequence

#### The issue here is in this part:

```python

vals.astype(str)
```

----> 1 vals.astype(str)

ValueError: setting an array element with a sequence

#### Problem description

The scalar objects held by an ExtensionArray cannot have a `__getattr__` method, else coercing the array of scalars to string will fail. This is an issue when creating an ExtensionArray for pint, which uses the same object to hold scalars and arrays. For more info see https://github.com/hgrecco/pint/issues/743

This is a known numpy bug. See https://github.com/numpy/numpy/issues/9441

**Comment by andrewgsavage** [comment]
Oops yea, missed that.

_values_for_factorize returns an array of quantity objects. Quantity
objects being necessary to prevent losing the units.

So I think I should be hitting that branch. The merge request makes the
hashing tests pass for pint.

**Comment by TomAugspurger** [comment]
> _values_for_factorize returns an array of quantity objects.

The default is to return an object-dtype ndarray, but ideally that would be avoided.

I'll need to familiar myself with `PintArray`, but is the idea that the entire array has the same `unit`? If so, I *suspect* that `_values_for_factorize` could return something like the underlying `._data`. Maybe take a look at how `pandas.Categorical` does it. Since `factorize` returns the `labels, uniques` tuple, the `uniques` has all the type information we need to preserve things (the units in your case).

**Comment by TomAugspurger** [comment]
@andrewgsavage here's what I meant.

```diff
diff --git a/pint/compat/__init__.py b/pint/compat/__init__.py
index 1fc438d..6fbf616 100644
--- a/pint/compat/__init__.py
+++ b/pint/compat/__init__.py
@@ -126,9 +126,9 @@ if not HAS_PROPER_BABEL:
 
 try:
     import pandas as pd
-    HAS_PANDAS = True
+    HAS_PROPER_PANDAS = HAS_PANDAS = True
     # pin Pandas version for now
-    HAS_PROPER_PANDAS = pd.__version__.startswith("0.24.0.dev0+625.gbdb7a16")
+    # HAS_PROPER_PANDAS = pd.__version__.startswith("0.24.0.dev0+625.gbdb7a16")
 except ImportError:
     HAS_PROPER_PANDAS = HAS_PANDAS = False
 
diff --git a/pint/pandas_interface/pint_array.py b/pint/pandas_interface/pint_array.py
index 935cc42..1d3dba7 100644
--- a/pint/pandas_interface/pint_array.py
+++ b/pint/pandas_interface/pint_array.py
@@ -72,6 +72,11 @@ class PintArray(ExtensionArray, ExtensionOpsMixin):
             assert self._dtype.type._REGISTRY == values._REGISTRY
         self._data = self._coerce_to_pint_array(values, dtype=dtype, copy=copy)
 
+    def _values_for_factorize(self):
+        from pandas.core.dtypes.missing import na_value_for_dtype
+        arr = np.asarray(self._data)
+        return arr, na_value_for_dtype(arr.dtype)
+
     def _coerce_to_pint_array(self, values, dtype=None, copy=False):
         if isinstance(values, self._dtype.type):
             return values
```


With that, things seemingly work

```python

In [1]: paste
>>> import pandas as pd
>>> import numpy as np
>>> import pint
>>> from pint.pandas_interface import PintArray

>>> ureg = pint.UnitRegistry()
>>> Q_ = ureg.Quantity
>>> torque = PintArray(Q_([1, 2, 2, 3], "lbf ft"))
>>> angular_velocity = PintArray(Q_([1000, 2000, 2000, 3000], "rpm"))
>>> df = pd.DataFrame({"torque": torque, "angular_velocity": angular_velocity})
## -- End pasted text --

In [2]: pd.util.hash_pandas_object(df.torque)
Out[2]:
0    14639053686158035780
1     3869563279212530728
2     1687604933839263903
3     7587835399775615123
dtype: uint64
```


`pandas.core` is private, so you shouldn't use that. We could maybe add `na_value_for_dtype` to the public API in `api.types`.

That does cause warnings. Presumably there's a way to turn a pint array to an ndarray without that.

And it seemingly broke `factorize`. I haven't looked yet at why, but `_from_factorize` will presumably need to be updated.

**Comment by andrewgsavage** [comment]
Cheers that worked after modifying _from_factorize. Can use np.NaN there so no need to add that to the public API.

There's a few other imports from pandas.core that I guess need changing now I'm aware.

**Comment by TomAugspurger** [comment]
I think no action is needed here right now.
