### ISSUE TITLE
DOC: Fix all flake8 issues and warning in the documentation pages

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#24173]
This issue is to track the pending work in making the `.rst` documentation pages be free of PEP-8 and other flake8 issues, and to not generate warnings.

| Page                         | flake8 | warnings |
|------------------------------|--------|----------|
| `10min.rst`                  | FAIL: #24174 | FAIL |
| `advanced.rst`               | OK: #24182 | FAIL |
| `api.rst`                    | OK | FAIL |
| `basics.rst`                 | FAIL | FAIL |
| `categorical.rst`            | OK: #24182 | FAIL |
| `comparison_with_r.rst`      |  OK    | FAIL |
| `comparison_with_sas.rst`    | OK: #24182 | FAIL |
| `comparison_with_sql.rst`    | OK: #24182 | FAIL |
| `comparison_with_stata.rst`  | OK: #24182 | FAIL |
| `computation.rst`            | OK     | FAIL |
| `contributing.rst`           | OK: #24182 | FAIL |
| `contributing_docstring.rst` | FAIL | FAIL |
| `cookbook.rst`               | OK: #23794 | FAIL |
| `developer.rst`              | OK     | FAIL |
| `dsintro.rst`                | FAIL: #24175 | FAIL |
| `ecosystem.rst`              | OK     | FAIL |
| `enhancingperf.rst`          | FAIL: #24176 | FAIL |
| `extending.rst`              | OK: #24182 | FAIL |
| `gotchas.rst`                | OK     | FAIL |
| `groupby.rst`                | FAIL: #24178 | FAIL |
| `index.rst`                  | OK     | FAIL |
| `indexing.rst`               | PR: #24089 | FAIL |
| `install.rst`                | OK     | FAIL |
| `internals.rst`              | OK     | FAIL |
| `io.rst`                     | OK: #23791 | FAIL |
| `merging.rst`                | FAIL: #24179 | FAIL |
| `missing_data.rst`           | PR: #24089 | FAIL |
| `options.rst`                | PR: #24089 | FAIL |
| `overview.rst`               | OK     | FAIL |
| `r_interface.rst`            | OK     | FAIL |
| `release.rst`                | PR: #24089 | FAIL |
| `releases.rst`               | OK     | FAIL |
| `reshaping.rst`              | FAIL: #24180 | FAIL |
| `sparse.rst`                 | OK     | FAIL |
| `text.rst`                   | OK     | FAIL |
| `timedeltas.rst`             | OK     | FAIL |
| `timeseries.rst`             | OK     | FAIL |
| `tutorials.rst`              | OK     | FAIL |
| `visualization.rst`          | FAIL: #24181 | FAIL |

After this issue is closed, we shouldn't have any file (other than the whatsnew pages) in the `exclude` section of `flake8-rst` in `setup.cfg`, and we should be able to enable the `-W` flag for `sphinx-build` in `doc/make.py`.

CC: @FHaase

**Comment by steveayers124** [comment]
Now working on this for #PandasHack2019:
Fernando Salazar, Shreeram Vaidhayanathan, Steve Ayers

**Comment by jbrockmendel** [comment]
@datapythonista id like to update this table.  is there a command i can run to do the appropriate checks?

**Comment by datapythonista** [comment]
I think we are already calling `sphinx-build` with `-W`, I think we fixed the warnings in the docs a long time ago (#26852 seems to be the PR).

For pep8 in the docs, the command is `flake8-rst`, which seems to be called without exclusions: https://github.com/pandas-dev/pandas/blob/master/ci/code_checks.sh#L80

So, I guess the whole table should be set to OK, and we can close this issue. I see all the issues in the table are already closed.
