### ISSUE TITLE
DOC: Fix flake8 issues in doc/source/visualization.rst

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#24181]
We didn't start validating the format of PEP8 and other code standards in the documentation examples until recently. We still have some files with errors, that we need to skip, and that we should fix, so we can start validating them.

The first step of this issue would be edit `setup.cfg` in the pandas home, and in the `flake8-rst` section, remove from the `exclude` list the file `doc/source/visualization.rst`

After that, running the next command will report the errors in the file (note that syntax error usually prevent to validate other errors, and the list of errors to fix can become much longer when the syntax error is fixed (please make sure that you are using `flake8-rst` version `0.7.0` or higher):

```
$ flake8-rst doc/source/visualization.rst 
doc/source/visualization.rst:132:22: E225 missing whitespace around operator
doc/source/visualization.rst:132:22: E999 SyntaxError: invalid syntax
doc/source/visualization.rst:132:26: E225 missing whitespace around operator
doc/source/visualization.rst:166:25: E702 multiple statements on one line (semicolon)ator
```

Once all the errors are addressed, please open a pull request with the fixes in the file, and removing the file from `setup.cfg`. If you need to do something that feels wrong to fix an error, please ask in a comment to this issue. Please avoid other unrelated changes, which can be addressed in a separate pull request.

**Comment by addisonlynch** [comment]
Will take this one as well.

**Comment by addisonlynch** [comment]
@datapythonista would you like me to finish the rest of the issues which are not yet taken and create a single PR for them? Looks like 

```
enhancingperf.rst
dsintro.rst
10min.rst
```

**Comment by datapythonista** [comment]
Please take one at a time from the issues list. May be simpler for you to address all them at the same time, but makes our life more complicated when reviewing and merging.
