### ISSUE TITLE
DOC: Fix flake8 issues in doc/source/reshaping.rst

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#24180]
We didn't start validating the format of PEP8 and other code standards in the documentation examples until recently. We still have some files with errors, that we need to skip, and that we should fix, so we can start validating them.

The first step of this issue would be edit `setup.cfg` in the pandas home, and in the `flake8-rst` section, remove from the `exclude` list the file `doc/source/reshaping.rst`

After that, running the next command will report the errors in the file (note that syntax error usually prevent to validate other errors, and the list of errors to fix can become much longer when the syntax error is fixed (please make sure that you are using `flake8-rst` version `0.7.0` or higher):

```
$ flake8-rst doc/source/reshaping.rst 
doc/source/reshaping.rst:21:7: E111 indentation is not a multiple of four
doc/source/reshaping.rst:22:7: E111 indentation is not a multiple of four
doc/source/reshaping.rst:25:7: E111 indentation is not a multiple of four
doc/source/reshaping.rst:26:7: E111 indentation is not a multiple of four
doc/source/reshaping.rst:374:28: W504 line break after binary operator
doc/source/reshaping.rst:375:83: E501 line too long (80 > 79 characters)
doc/source/reshaping.rst:400:83: E501 line too long (80 > 79 characters)
doc/source/reshaping.rst:724:83: E501 line too long (89 > 79 characters)
doc/source/reshaping.rst:739:13: E999 SyntaxError: invalid syntax
```

Once all the errors are addressed, please open a pull request with the fixes in the file, and removing the file from `setup.cfg`. If you need to do something that feels wrong to fix an error, please ask in a comment to this issue. Please avoid other unrelated changes, which can be addressed in a separate pull request.

**Comment by charlesdong1991** [comment]
i will make a small pr on it

**Comment by charlesdong1991** [comment]
Hi, @datapythonista , that's cool!! I am pretty new to this community, so i am not subscribed to pandas-dev mailing list.. and i just subscribed it, and interested in hearing more details about it!
