### ISSUE TITLE
TST: Add missing test case for test_register_option when the key is a reserved key

### ISSUE THREAD

**Issue by ywpark1** [pandas-dev/pandas#24192]
I am new to Python and Pandas. I was checking the  <a href="https://codecov.io/gh/pandas-dev/pandas/src/master/pandas/core/config.py#L441">codecov</a> and found that there was a missing test case for a reserved key under `test_register_option` in the file `test_config.py`.

I would like to try working on this test case if you do not mind!
Thanks

**Comment by jreback** [comment]
duplicate test
