### ISSUE TITLE
pandas.rolling.max() shut down

### ISSUE THREAD

**Issue by kid3night** [pandas-dev/pandas#24195]
[####](https://github.com/kid3night/pandas_issue_rolling/blob/master/sample_data.h5) Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd
z = pd.read_hdf('sample_data.h5', key='d')
z.rolling('9S', closed='left').max()

#https://github.com/kid3night/pandas_issue_rolling/blob/master/sample_data.h5
#(link of sample_data.h5)

```
#### Problem description
I got a sample data and want to use it to get the rolling max, min, sum etc.
But every time I did rolling max/min on it, the python kernal would shut down and shows 'python.exe has stopped working' I have uploaded the sample data, and the link is https://github.com/kid3night/pandas_issue_rolling/blob/master/sample_data.h5

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.0
pytest: 3.5.1
pip: 10.0.1
setuptools: 39.1.0
Cython: 0.28.2
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: 0.1.6
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by jreback** [comment]
needs an actual copy pastable example one can run w/o a data input file

**Comment by kid3night** [comment]
> needs an actual copy pastable example one can run w/o a data input file

The raws of the data are 1.8m+ and hard to paste.

**Comment by jreback** [comment]
@kid3night and how would you expect anyone to replicate this? pls reopen if you can show a reproducible example.

**Comment by kid3night** [comment]
> @kid3night and how would you expect anyone to replicate this? pls reopen if you can show a reproducible example.

I put the sample data link on it. So you mean the data link is not acceptable?

**Comment by jreback** [comment]
links are not acceptable. a copy pastable example that replicates is needed.
