### ISSUE TITLE
Unexpected Slicing Behavior for DateTimeIndex

### ISSUE THREAD

**Issue by joseortiz3** [pandas-dev/pandas#24197]
#### Code Sample, a copy-pastable example if possible

```python
>>> dt_idx = pd.DatetimeIndex(['2015-09-14 09:30:00', '2015-09-14 10:00:00',
...                '2015-09-14 10:30:00', '2015-09-14 11:00:00'])

>>> start_t = dt_idx[1]

>>> end_t = dt_idx[-1]

>>> pd.Series(index=dt_idx)[start_t:end_t].index # Behavior 1

DatetimeIndex(['2015-09-14 10:00:00', '2015-09-14 10:30:00',
               '2015-09-14 11:00:00'],
              dtype='datetime64[ns]', freq=None)

>>> dt_idx[start_t:end_t] # Behavior 2

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Joey\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexes\datetimelike.py", line 428, in __getitem__
    result = getitem(key)
TypeError: slice indices must be integers or None or have an __index__ method
```
#### Problem description

Not a problem, just unexpected behavior: DateTimes have been used to slice DateTimeIndexes on Series and Dataframes for a long time (Behavior 1). Thus the same slicing behavior is expected for just a DateTimeIndex by itself, but that's not the case (Behavior 2).

Then again, it may be harder to code this behavior than its worth (involving behavior dependent on type of slice index). Thanks for the consideration.

#### Expected Output

Consistency between slicing an index on a Dataframe or Series, vs by itself.

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.4
pytest: None
pip: 18.1
setuptools: 39.0.1
Cython: None
numpy: 1.15.3
scipy: 1.1.0
pyarrow: None
xarray: 0.11.0
IPython: None
sphinx: None
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.6
blosc: None
bottleneck: None
tables: None
numexpr: 2.6.8
feather: None
matplotlib: 3.0.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.6.3
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
this is a very clear error message
Indexes are only sliceable by position

**Comment by joseortiz3** [comment]
![image](https://user-images.githubusercontent.com/18585219/49731113-7fa94280-fc37-11e8-8845-a17eca9f1969.png)
