### ISSUE TITLE
Possible bug noticed in pandas excel function

### ISSUE THREAD

**Issue by mdivk** [pandas-dev/pandas#24210]
**I am using Python 2.7 from Anaconda in Linux, no same issue found in Windows.**

pandas version: 0.18.1

Here is the case:

`First dataframe: product = pd.DataFrame()`

Intend to read in sheet_name=4, indeed the first sheet was read in:

`product = pd.read_excel(excelfile, nrows=1, header=None, usecols=[1], sheet_name=4)`

Check the element for this sheet:

```
product.loc[0,1]
u'CD Long-Term WAMP'
```

Check the memory address of this dataframe:

```
hex(id(product))
'0x7f326453ecd0'
```

Now create a new dataframe, confirmed it has a different memory address:

> product = pd.DataFrame()
> hex(id(product))
> '0x7f326453ee10'

Read in the sheet_name=5:

> product = pd.read_excel(excelfile, nrows=1, header=None, usecols=[1], sheet_name=5)

Check the memory address again, no change:

> hex(id(product))
> '0x7f3265ff6e10'

Check the element: for some reason it is showing the previous dataframe's data:

> product.loc[0,1]
> u'CD Long-Term WAMP'

So you can see the sheet_name option in pd.read_excel is always pointing to the first sheet.

Am I missing anything here?

Thank you.

**Comment by WillAyd** [comment]
This example isn't reproducible and is from a version that is almost 3 years old. If you notice the behavior on a recent version please be sure to check the contributing guide on how to file a bug report and feel free to open a new one with required information
