### ISSUE TITLE
Rename DatetimeArrayMixin / TimedeltaArrayMixin

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#24231]
To `DatetimeArray` and `TimedeltaArray`.

Just so we don't forget this before the release :)

**Comment by TomAugspurger** [comment]
@jbrockmendel do you have any WIP PRs that you want reviewed / merged before this is done/

**Comment by jbrockmendel** [comment]
No, go for it.  Looking forward to seeing this done.
