### ISSUE TITLE
[Feature Request] Add name attribute to pd.DataFrame

### ISSUE THREAD

**Issue by jolespin** [pandas-dev/pandas#24244]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
pd.DataFrame(data, index=sample_labels, columns=iris_features, name="iris")
```
Please let me know if this is out of scope.  I think it could be a useful feature to have since `pd.Index`, `pd.Series`, `xr.DataArrays`, and `xr.Dataset` has them.  I usually deal with dataframes from 2 different populations where I keep them organized by dictionaries.  I know that I could still do `df.name = "iris"` but I think an official name argument would benefit people too.

**Comment by jreback** [comment]
see discussions here https://github.com/pandas-dev/pandas/issues/447

this would add quite some complexity for not a lot of gain
