### ISSUE TITLE
BUG: pd.date_range gives wrong overflow error type when freq='B'

### ISSUE THREAD

**Issue by topper-123** [pandas-dev/pandas#24252]
#### Code Sample, a copy-pastable example if possible

```python
>>> date = pd.Timestamp.max.floor("D").to_pydatetime().date()  # datetime.date(2262, 4, 11)
>>> freq = 'B'
>>> pd.date_range(date, periods=1, freq=freq)
OverflowError: int too big to convert
>>> freq = 'D'
>>> pd.date_range(date, periods=1, freq=freq)
OutOfBoundsDatetime: Cannot generate range with start=9223286400000000000 and periods=1
```
#### Problem description

These two date_range overflows return different error types. Both should reasonablyreturn ``OutOfBoundsDatetime``.

<details>

INSTALLED VERSIONS
------------------
commit: 8221ee91d15b01a190d73ea10d47af81de296c90
python: 3.7.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.0.dev0+1257.g8221ee91d
pytest: 4.0.0
pip: 18.1
setuptools: 40.6.2
Cython: 0.29
numpy: 1.15.4
scipy: None
pyarrow: 0.11.1
xarray: None
IPython: 7.1.1
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: 0.4.0
matplotlib: 3.0.1
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by mroeschke** [comment]
I suspect that generally `Tick` based offset will raise the later error while `DateOffset` based offsets will raise the former.

Additionally the `OutOfBoundsDatetime` looks like it can be improved; it's probably more beneficial to specify the date instead of the nanoseconds epoch time.

**Comment by topper-123** [comment]
Hey, @mroeschke, did your PR resolve this issue?

I'm in doubt, as the second example now raises a OverflowError, while I assumed the correct solution would be for both to raise a OutOfBoundsDatetime.

**Comment by mroeschke** [comment]
I don't think @jbrockmendel solved this issue. On master the first example still raises an `OverflowError` while the 2nd example actually returns something on master

```
In [5]: >>> freq = 'D'
   ...: >>> pd.date_range(date, periods=1, freq=freq)
Out[5]: DatetimeIndex(['2262-04-11'], dtype='datetime64[ns]', freq='D')
```

**Comment by jbrockmendel** [comment]
@mroeschke just opened #26651 that addresses the example here.  I had trouble coming up with an example to test non-overflow at the bottom of the overflow range.  Suggestions welcome.

**Comment by mroeschke** [comment]
This seems a little suspicious toward the bottom of the overflow range (on master):

```
In [5]: end = pd.Timestamp.min.ceil("D").to_pydatetime()

In [6]: end
Out[6]: datetime.datetime(1677, 9, 22, 0, 0)

In [7]: rng = pd.date_range(start=None, end=end, periods=-1, freq='B')

In [8]: rng
Out[8]: DatetimeIndex([], dtype='datetime64[ns]', freq='B')

In [11]: rng = pd.date_range(start=None, end=end, periods=1, freq='-1B')
OverflowError: Python int too large to convert to C long
```

**Comment by jbrockmendel** [comment]
@mroeschke under #24252 [8] above is unchanged but [11] returns `DatetimeIndex(['1677-09-22'], dtype='datetime64[ns]', freq='-1B')`.  The latter looks right to me, while the empty DatetimeIndex still looks wrong.  Does that match what you expect?  If so, I'll add a test to 24252 for [11].

**Comment by mroeschke** [comment]
I think [7] and [11] should both raise an `OutOfBoundsDatetime` as well since they are both (essentially) equivalent to `pd.Timestamp.min - pd.Timedelta('1D')`
