### ISSUE TITLE
potential BUG, pandas raise unexpected Exception for setting values to a new column with null index

### ISSUE THREAD

**Issue by wxianxin** [pandas-dev/pandas#24250]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.read_excel("../../Desktop/Book1.xlsx")
idx = df['a'] > 0
df.loc[idx, "d"] = "ddd"
```
#### Problem description
Recreate the problem:
1. Create a dataframe from reading an Excel file with only field names but no data populated, e.g.
<img width="332" alt="screen shot 2018-12-12 at 10 18 54" src="https://user-images.githubusercontent.com/13245897/49879208-82eb2c80-fdf7-11e8-8a71-b81b437ba022.png">
2.You can't set a new value to a new column even if your index is all false.

This would just break the process. IMO it should not break but instead create a new, empty column.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1.final.0
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 3.9.2
pip: 10.0.1
setuptools: 39.0.1
Cython: 0.29
numpy: 1.15.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.0.1
sphinx: 1.8.2
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: 2.5.9
xlrd: 1.1.0
xlwt: None
xlsxwriter: 1.1.2
lxml: None
bs4: None
html5lib: None
sqlalchemy: 1.2.12
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by WillAyd** [comment]
Not entirely clear on the issue and the code sample is not self contained (i.e. fully copy / pastable to reproduce).

If you are trying to assign a new column just do `df['d'] = 'ddd'`

**Comment by wxianxin** [comment]
This is a bug. At lease a behavior that is not consistent. @WillAyd Why don't you try to replicate before you close it?
You **cannot** replicate the issue by creating a dataframe using 
`df = pd.DataFrame(columns=['a', 'b', 'c'])` because it will fail and prompt you in add the argument `index`.

You **cannot** reproduce the bug **without** using the Excel file as input.
Reading an empty Excel file you can create a dataframe without index.
To be more specific, this bug is about `.loc`.
In this case, I expect the following two lines of code have the same behavior, but they are not. 
```
df.loc[idx, "d"] = "ddd"
```
and 
```
df["d"] = "ddd"
```
They should both add a column `d` to the empty dataframe. However the first one breaks the program.
