### ISSUE TITLE
df(condition).any() is True returns False even when condition satisfies

### ISSUE THREAD

**Issue by saarahrasheed** [pandas-dev/pandas#24262]
#### Code Sample, a copy-pastable example if possible

```python
def test_1():
    x = pd.Series([1,2,3,4,5,6,7,8,9,10])
    x = pd.Series()
    if (x > 5).any() is True:
        return True
    else:
        return False 

def test_2():
    x = pd.Series([1,2,3,4,5,6,7,8,9,10])
    x = pd.Series()
    if (x > 5).any() == True:
        return True
    else:
        return False 

```
#### Problem description
So I am using .any() method to compare if a Series has any value greater than 5. When I use "is True" to compare bool value it returns False. When I use "== True" it returns True. I know the better way to compare would be to use x.max() > 5, but for the case in consideration, is that a issue?
Using latest pandas version: 0.23.4 and Python 3.6.5

#### Expected Output
Ideally, in both cases it returns True 
```
test_1()
True
test_2()
 True
```
#### Actual Output
But I get False in test_1()

```
test_1()
False
test_2()
True
```

**Comment by ArtinSarraf** [comment]
If you check the type of pd.Series.any() you’ll find that it’s an instance of `numpy.bool_` not the builtin python bool. In general the following:

    if <some boolean expression> == True:
        return True
    else:
        return False

Should usually just be written as:

    return <some boolean expression>

**Comment by jreback** [comment]
closing as usage question
