### ISSUE TITLE
DOC: Series.nlargest sorts index with duplicates

### ISSUE THREAD

**Issue by dataseller** [pandas-dev/pandas#24268]
I think the description of this method is incorrect. The effect of parameter "keep" says, if we pass "first" to it, means to take the first duplicate value, while we pass "last" to it, means to take the last duplicate value.
However, its real effect is to sort the duplicate values by their indexes.
Hope we put it right soon.

**Comment by songmoo** [comment]
can I try to fix it?

**Comment by nfreundlich** [comment]
> can I try to fix it?

did you take the issue?

**Comment by Omnomnominous** [comment]
@thoo I think the description is correct insofar as it is order of the items in the index array. It's possible that it could be reworded to be a bit more clear like so:
```
            - ``first`` : return the first n occurrences in given index order
            - ``last`` : return the last n occurrences in reverse index order
```
@chris-b1 One thing that I noticed while looking into this is that when you call `s.nlargest(2,keep="last")` it doesn't return the items sorted by index, but in reverse order by index. For example:
```
>>>s = pd.Series([3, 1, 3, 2, 3,], index=['e', 'a', 'c', 'b', 'd'])
>>>s.nlargest(3, keep='last')
d    3
c    3
e    3
```
I feel as if this is a bug in it's own way and that it should instead be returning in the original index order i.e.
```
//should return
e    3
c    3
d    3
```
