### ISSUE TITLE
Add ExtensionArray._scalar_from_string

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#24261]
the DatetimeArray PR is adding a `_scalar_from_string` for the datelike arrays. We could consider something similar for the EA interface.

```python
In [6]: pd.core.arrays.DatetimeArrayMixin(np.array([], dtype='i8'))._scalar_from_string("2000")
Out[6]: Timestamp('2000-01-01 00:00:00')

```

**Comment by jbrockmendel** [comment]
this seems like overkill.  Should that be acccessible via the dtype or box_func?

**Comment by TomAugspurger** [comment]
Probably not the dtype. `box_func` isn't part of the interface either.

**Comment by jbrockmendel** [comment]
The part that is unclear to me is why DTA needing method X necessarily implies the EA interface needs method X.
