### ISSUE TITLE
DOC/API: PeriodIndex sub/add with Integers: update docs or undo deprecation

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#24305]
Creating an issue of my comment on the PR that deprecated PeriodIndex add/sub with integers (https://github.com/pandas-dev/pandas/pull/22535):

@jbrockmendel what was actually the rationale of deprecating it for Periods as well? 
The issue that is closed by this (https://github.com/pandas-dev/pandas/issues/21939, cc @jreback @mroeschke) discusses it for DatetimeIndex/TimedeltaIndex, but I think says to keep it for PeriodIndex for now. 

In any case, for PeriodIndex, this was an explicitly documented behaviour (in several places throughout the docs), and the documentation is now no longer up to date (you can check the doc build to see the deprecation warnings being raised). 

But instead of updating the docs, I think we should maybe also reconsider the deprecation (given that is was a clearly documented behaviour). Or at least provide a clear alternative way.

(and to be clear: I fully agree with the deprecation for DatetimeIndex / TimedeltaIndex!)

**Comment by jbrockmendel** [comment]
> I think we should maybe also reconsider the deprecation 

I'm open to this.  The part I care about is the TS/TD/DTI/TDI
