### ISSUE TITLE
Fixtures making IntNA tests difficult to run interactively

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#24326]
Trying to run tests.arrays.test_integer TestArithmeticOps.test_error in the REPL, need to produce the `data` arg that gets passed to `test_error`.  `data` is defined in a fixture:

```
@pytest.fixture(params=[Int8Dtype, Int16Dtype, Int32Dtype, Int64Dtype,
                        UInt8Dtype, UInt16Dtype, UInt32Dtype, UInt64Dtype])
def dtype(request):
    return request.param()


@pytest.fixture
def data(dtype):
    return integer_array(make_data(), dtype=dtype)
```

Trying to do this manually:

```
>>> from pandas.tests.arrays.test_integer import *
>>> dtype = Int64Dtype
>>>
>>> d = make_data()
>>> dat = integer_array(d, dtype=dtype)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pandas/core/arrays/integer.py", line 104, in integer_array
    values, mask = coerce_to_array(values, dtype=dtype, copy=copy)
  File "pandas/core/arrays/integer.py", line 159, in coerce_to_array
    raise ValueError("invalid dtype specified {}".format(dtype))
ValueError: invalid dtype specified <class 'pandas.core.arrays.integer.Int64Dtype'>
```

What am I missing here?  Figuring out exactly what is tested _should_ be really easy.

**Comment by TomAugspurger** [comment]
You need to call the dtype.

`dat = integer_array(d, dtype=dtype())`

I think having an actual repr for instances of that dtype may help. with the confusion. We could also check in `coerce_to_array` whether the `dtype` is a class, rather than an instance.

**Comment by jbrockmendel** [comment]
thanks

**Comment by TomAugspurger** [comment]
Might leave this open to see how things can be improved.

I think part of the confusion is that NumPy's top-level `np.<dtype>` functions / classes are kinda weird. You're expected to pass the class in places where we expect the dtypes.

```python
pd.Series([1, 2], dtype=np.int32)
```

rather than `np.int32()` which returns... something.

pyarrow's `pa.array()` expects instances of its top-level types, rather than the class, so we're consistent with pyarrow here.
