### ISSUE TITLE
Doc on pandas.read_parquet says path is a string / File path but io.ByteIO also works

### ISSUE THREAD

**Issue by enricorotundo** [pandas-dev/pandas#24321]
#### Code Sample, a copy-pastable example if possible

```python
pd.read_parquet(url_to_public_parquet_file_on_azure_blob)
```
#### Problem description

[The doc](https://pandas-docs.github.io/pandas-docs-travis/generated/pandas.read_parquet.html?highlight=read_parquet#pandas.read_parquet) says `path` parameter is `string File path`, but could be an `io.BytesIO` as the code above works well. Anybody else ran into this case of reading a remote parquet file? Is this worth a PR?

**Comment by TomAugspurger** [comment]
I think the correct type is similar to `get_filpath_or_buffer`.

```
    filepath_or_buffer : a url, filepath (str, py.path.local or pathlib.Path),
                         or buffer
```

although even that should be updated to something like str, URL, or any object implementing `__fspath__`.
