### ISSUE TITLE
Timestamp.to_pydatetime() cannot be applied to an entire Series

### ISSUE THREAD

**Issue by YanTianqi** [pandas-dev/pandas#24348]
#### Problem description
When I tried to compare 2 columns of date in one dataframe, if one column has type pandas._libs.tslib.Timestamp while the other is python datetime, a mere comparison will return an error of  `Cannot change data-type for object array.`

To compare, I have to convert Timestamp to datetime. According to the API, I can use the function to_pydatetime(). However, this only works on one Timestamp value, but cannot be applied to the entire column as shown in the screenshot

![image](https://user-images.githubusercontent.com/7760158/50213914-f4a81500-03b9-11e9-8c65-712b8e33ed0e.png)

Is there an alternative solution to this? Thanks

**Comment by jreback** [comment]
pls show a complete copy pastable example
no screenshots

**Comment by jreback** [comment]
```
In [1]: df = pd.DataFrame({'A': pd.date_range('20180101', periods=3), 'B': pd.date_range('20180101', periods=3, freq='s')})

In [2]: df
Out[2]: 
           A                   B
0 2018-01-01 2018-01-01 00:00:00
1 2018-01-02 2018-01-01 00:00:01
2 2018-01-03 2018-01-01 00:00:02

In [3]: df.dtypes
Out[3]: 
A    datetime64[ns]
B    datetime64[ns]
dtype: object

In [4]: df.A == df.B
Out[4]: 
0     True
1    False
2    False
dtype: bool

In [5]: df.A.dt.to_pydatetime()
Out[5]: 
array([datetime.datetime(2018, 1, 1, 0, 0),
       datetime.datetime(2018, 1, 2, 0, 0),
       datetime.datetime(2018, 1, 3, 0, 0)], dtype=object)
```
you almost always will NOT want to do the conversion in [5] as its non-performant.
