### ISSUE TITLE
Pandas build time is very slow on big iron PPC (binary wheel not available)

### ISSUE THREAD

**Issue by mzpqnxow** [pandas-dev/pandas#24344]
#### Problem description

There is currently no straightforward way to perform a parallel build of pandas. This is a problem for me as  I need to build virtual environments quite often and there is no binary package for my platform:
```
$ cat /proc/cpuinfo
....
processor	: 159
cpu		: POWER8NVL (raw), altivec supported
clock		: 2061.000000MHz
revision	: 1.0 (pvr 004c 0100)

timebase	: 512000000
platform	: PowerNV
model		: 8335-GTB
machine		: PowerNV 8335-GTB
firmware	: OPAL v3
```
`LSB Version:	security-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-ppc64el`

I have a big iron PPC machine runnining Ubuntu with 160 cores, and would like to parallelise the build process if possible. I have tried `CONCURRENCY_LEVEL=140 make` and `make -j` but they don't make a difference. I admit I know very little about how Pandas is built and what the internal dependencies are, so I am not able to go much further than this.

I have also tried the following to no avail (I am ignorant about what this actually does, it was a shot in the dark)

```
diff --git a/setup.py b/setup.py
index cb52db9..beebc46 100755
--- a/setup.py
+++ b/setup.py
@@ -724,7 +724,7 @@ setup(name=DISTNAME,
       version=versioneer.get_version(),
       packages=find_packages(include=['pandas', 'pandas.*']),
       package_data={'': ['templates/*', '_libs/*.dll']},
-      ext_modules=maybe_cythonize(extensions, compiler_directives=directives),
+      ext_modules=maybe_cythonize(extensions, compiler_directives=directives, nthreads=148),
       maintainer_email=EMAIL,
       description=DESCRIPTION,
       license=LICENSE,
```
Current build time is ~ 9 minutes

Just to be clear, I am talking about the *build* of Pandas not the runtime performance of Pandas.

I am currently testing this on the latest master.

Is there hope for a straightforward parallel build of Pandas via an environment variable that pip could pass along? Or is there some issue that makes parallelising the build difficult (or impossible) ?

If anyone has any commentary I would appreciate it.

Thanks

**Comment by jbrockmendel** [comment]
That build time seems similar to what I see on a much less beefy machine, so there is likely room for improvement.

The build process pretty much all goes through cython; they will have more expertise on how to tune the compiler arguments.

**Comment by jreback** [comment]
this platform is not supported in any way; that said would take a patch

**Comment by mzpqnxow** [comment]
@jreback I am not surprised ... I did not choose this machine by the way :>

**Comment by mzpqnxow** [comment]
@chris-b1 	I got a 20% improvement with ccache.. probably all I can do for now, thanks for the suggestion, I hadn't thought of it

**Comment by mzpqnxow** [comment]
Closing as this does not seem to be a Pandas issue and even if it was, ppc64le is not supported
