### ISSUE TITLE
Unpin travis-3.6 build

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#24359]
https://travis-ci.org/pandas-dev/pandas/jobs/470161644#L2601

**Comment by TomAugspurger** [comment]
Here are the differing packages between 
https://travis-ci.org/pandas-dev/pandas/builds/470122716 and 
https://travis-ci.org/pandas-dev/pandas/builds/470140296

package                 | old version    | old hash       |  new version    | new hash
----------------------- | -------------- | -------------- | --------------- | --------------
cryptography            | 2.3.1          | py36hc365091_0 | 2.4.2           | py36h1ba5d50_0  
curl                    | 7.61.0         |     h84994c4_0 | 7.63.0          |  hbc83047_1000  
fiona                   | 1.7.12         | py36h3f37509_0 | 1.7.10          | py36h48a52f0_0  
hdf5                    | 1.10.2         |     hba1933b_1 | 1.8.18          |     h6792536_1  
json-c                  | 0.13.1         |     h1bed415_0 | 0.12.1          |     ha6a3662_2  
libcurl                 | 7.61.0         |     h1ad7b7a_0 | 7.63.0          |  h20c2e04_1000  
libgdal                 | 2.2.4          |     h6f639c0_1 | 2.2.2           |     h6bd4d82_1  
libnetcdf               | 4.6.1          |     h10edf3e_1 | 4.4.1.1         |     h97d33d9_8  
libpq                   | 10.5           |     h1ad7b7a_0 | 11.1            |     h20c2e04_0  
openssl                 | 1.0.2p         |     h14c3975_0 | 1.1.1a          |     h7b6447c_0  
proj4                   | 5.0.1          |     h14c3975_0 | 4.9.3           |     hc8507d1_7  
psycopg2                | 2.7.5          | py36hb7f436b_0 | 2.7.6.1         | py36h1ba5d50_0  
python                  | 3.6.6          |     h6e4f718_2 | 3.6.7           |     h0371630_0  
qt                      | 5.9.6          |     h8703b6f_2 | 5.9.7           |     h5867ecd_1  


some packages also had their build number incremented, but the version didn't change.

**Comment by TomAugspurger** [comment]
In 
https://github.com/pandas-dev/pandas/pull/24360 we pinned Python to 3.6.6. We should remove that pin once liberal and openssl have been updated for 3.6.7.

**Comment by mroeschke** [comment]
Looks like the pin went away in the travis builds. Closing
