### ISSUE TITLE
DataFrame constructor ignores integer dtype when dict-data and non-overlapping columns

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#24386]
This is close to https://github.com/pandas-dev/pandas/issues/24385, but we don't have a test saying otherwise, so I'm actually going to fix this one :)

```python
In [21]: pd.DataFrame({"a": [1, 2]}, columns=['b'], dtype=int).dtypes
Out[21]:
b    float64
dtype: object

In [22]: pd.DataFrame({"a": [1, 2]}, columns=['b'], dtype='datetime64[ns]').dtypes
Out[22]:
b    datetime64[ns]
dtype: object
```

Out[21] should be int64.

**Comment by chengsoonong** [comment]
It also seems to happen when constructing using index and columns only (no data).
```
pd.DataFrame(index=[0], columns=['b'], dtype=int).dtypes
```
returns
```
b    float64
dtype: object
```

**Comment by mroeschke** [comment]
This looks to be fixed on master. Could use a test

```
In [17]: In [21]: pd.DataFrame({"a": [1, 2]}, columns=['b'], dtype=int).dtypes
Out[17]:
b    int64
dtype: object

In [18]: pd.__version__
Out[18]: '1.1.0.dev0+1313.g1c0cc62e3'
```

**Comment by avinashpancham** [comment]
take

**Comment by avinashpancham** [comment]
take

**Comment by zabdorff** [comment]
I'm still seeing the issue @chengsoonong raised, in 1.2.4.  

> It also seems to happen when constructing using index and columns only (no data).
> 
> ```
> pd.DataFrame(index=[0], columns=['b'], dtype=int).dtypes
> ```
> 
> returns
> 
> ```
> b    float64
> dtype: object
> ```
