### ISSUE TITLE
Implement min, argmin, max, argmax on ExtensionArrays?

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#24382]
We already have `ExtensionArray.argsort` as part of the EA interface, so we should be able to to do min, argmin, max, and argmax as a composition of `argsort` and `__getitem__`. Do we want to do this?

**Comment by jreback** [comment]
i think this is a nice idea; shows a nice benefit of shared EA infrastructure

**Comment by TomAugspurger** [comment]
One thing I notice though, our docs on _values_for_argsort don't mention
missing data at all. I think we may need to adjust the API there to return
a tuple of (values, mask), where the mask indicates missing values?

**Comment by makbigc** [comment]
When `nan` is invloved, `argsort` behaves in two ways.

The element of index 1 is always `nan` in the following.
1. Putting the `nan` in the beginning

```
In [27]: arr = integer_array([1, np.nan, 2])                                    

In [28]: arr                                                                    
Out[28]: 
<IntegerArray>
[1, NaN, 2]
Length: 3, dtype: Int64

In [29]: arr.argsort()                                                          
Out[29]: array([1, 0, 2])

```

2. Putting the `nan` in the end
```

In [20]: arr1 = integer_array([1, np.nan, 0], dtype='uint8')                    

In [21]: arr1                                                                   
Out[21]: 
<IntegerArray>
[1, NaN, 0]
Length: 3, dtype: UInt8

In [22]: arr1.argsort()                                                         
Out[22]: array([2, 0, 1])

In [23]: idx = pd.Index([1, np.nan, 2])                                         

In [24]: arr = idx.array                                                        

In [25]: arr                                                                    
Out[25]: 
<PandasArray>
[1.0, nan, 2.0]
Length: 3, dtype: float64

In [26]: arr.argsort()                                                          
Out[26]: array([0, 2, 1])


```

Should we standardize where `nan` to be placed? `_values_for_argsort` returns different value for `nan` in different EA.

**Comment by jorisvandenbossche** [comment]
@makbigc there indeed still some inconsistencies there ... I opened https://github.com/pandas-dev/pandas/issues/21801 for that some time ago. Can you move your comment there?
