### ISSUE TITLE
check overwrite mode in to_csv and other writers.

### ISSUE THREAD

**Issue by jessehoff** [pandas-dev/pandas#24390]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

```
#### Problem description

Quick suggestion if possible, maybe more of an issue for python core library, but it would be terrific if there was an option within the various writers (to_csv, etc) to check for existence of file and throw error if it already exists.

This is desirable for notebook users who repeatedly re-munge data and may accidently rerun cells with an output step erroneously. I can't imagine it'd create much of a performance cost. 

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.20.3
pytest: 3.2.1
pip: 18.0
setuptools: 36.5.0.post20170921
Cython: 0.26.1
numpy: 1.13.3
scipy: 0.19.1
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.7.2
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.1.0
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.2.0
xlsxwriter: 1.0.2
lxml: 4.1.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by h-vetinari** [comment]
This is a pandas issue, not a python one - it would be easy to stat the file for existence before writing. Could do it e.g. with an `overwrite={'warn'|'raise'|'ignore'}`-keyword, that's set to `'warn'` by default.

**Comment by WillAyd** [comment]
-1 here as I don’t think this is a lot of value add for pandas. Why not use use pathlib?

**Comment by jessehoff** [comment]
Certainly there are plenty of ways to avoid it, but many users often prefer to use single line implementations of pandas, rather than wrapping in more python functionality. And i'd probably default overwrite to "ignore' to keep behavior typical.

Again, the use case here is a typical pandas using data science project in a notebook where a cell may be errantly executed without thinking.

The value add is certainly not enormous, and of course someone wishing to be careful could write the check themselves, still, would be convenient

**Comment by jreback** [comment]
this is just scope creep in pandas, closing.
