### ISSUE TITLE
Allowing custom function for merge as_of "direction"

### ISSUE THREAD

**Issue by ProxyCausal** [pandas-dev/pandas#24399]
This is an idea:

The suggestion is to allow the user to define a function specifying how they want the merge "on" to be done.
For example, the best I can do now with the predefined "nearest" is to match the "nearest" value on one column, but let's say I wanted to match the "nearest value" for a function of the values from two columns e.g. distance from x and y coordinates this is not possible.

I think my only other option would be the much less efficient method of iterating through my two dataframes.

**Comment by mroeschke** [comment]
Could you demonstrate your proposal with a small toy example? 

As stated, it sounds like you could create another column with distances and use `merge_asof` on that column?

**Comment by enmatics** [comment]
Dataset A
               ID       Date   Latitude  Longitude
0        10000092 2015-03-18  41.891399 -87.744385
4        10000097 2015-03-18  41.878065 -87.743354
12       10000109 2015-03-18  41.738563 -87.552679
24       10000123 2015-03-18  41.880934 -87.764879
29       10000130 2015-03-18  41.737129 -87.649728
48       10000159 2015-03-18  41.986392 -87.656701
72       10000197 2015-03-18  41.810671 -87.621248
170      10000620 2015-03-18  41.916994 -87.756245
863      10002132 2015-03-18  41.964745 -87.714849
87584    10000043 2015-03-18  41.748223 -87.653678
87595    10000055 2015-03-18  41.657912 -87.603407
87596    10000056 2015-03-18  41.897922 -87.737011
87605    10000069 2015-03-18  41.748089 -87.650033
87607    10000072 2015-03-18  41.851645 -87.716575
733795    9999383 2015-03-18  41.780144 -87.684886
1794523  10000037 2015-03-18  41.681269 -87.642024
1794550  10000132 2015-03-18  41.871038 -87.735139
3816482   9998641 2015-03-18  42.005648 -87.673190
3816655   9999262 2015-03-18  41.795449 -87.660979
3816731   9999389 2015-03-18  41.675289 -87.626187
3816860   9999683 2015-03-18  41.880102 -87.773762
3816999   9999862 2015-03-18  41.878463 -87.755787
3817032   9999905 2015-03-18  41.886976 -87.711185
3817039   9999914 2015-03-18  41.691295 -87.655119
3817062   9999941 2015-03-18  41.964797 -87.649998
3817070   9999949 2015-03-18  41.768885 -87.620200
3817074   9999953 2015-03-18  41.756697 -87.563901
3817099   9999986 2015-03-18  41.878797 -87.731600
3817104   9999992 2015-03-18  41.790614 -87.622362

Dataset B
       incident_id        date  latitude  longitude
61471       309335  2015-03-18   41.9858   -87.6571
61476       309205  2015-03-18   41.6925   -87.6547
61498       309327  2015-03-18   41.7471   -87.6367
61513       309241  2015-03-18   41.9640   -87.6503
61517       309214  2015-03-18   41.7792   -87.6849
61526       309221  2015-03-18   41.8917   -87.7436
61528       309227  2015-03-18   41.8773   -87.7109
61529       309229  2015-03-18   41.7908   -87.6228
61566       309348  2015-03-18   41.8979   -87.7360
61568       309343  2015-03-18   41.8109   -87.6217
61573       309346  2015-03-18   41.7377   -87.6501

I thought about just creating another column with distances but that would require iterating through all the rows of B for each row in A

I made an algorithm that does this to return the minimum of distances between each tuple pair of coordinates, the results of which you can do below.
However, this has to be done for all dates (notice that the data all comes from one date) and I believe there must be a more efficient way to do this with pandas.

`[[9999914, 309205, 0.0012757383610987416],
 [9999383, 309214, 0.0009441380113328591],
 [10000092, 309221, 0.0008403749608524236],
 [9999905, 309227, 0.009679920072949632],
 [9999992, 309229, 0.000476269822717683],
 [9999941, 309241, 0.0008523078755048443],
 [10000109, 309327, 0.08445394759315526],
 [10000159, 309335, 0.0007144599351652924],
 [10000197, 309343, 0.0005064995323302126],
 [10000130, 309346, 0.0006815301691388357],
 [10000056, 309348, 0.0010117006889607903]]`

**Comment by mroeschke** [comment]
Thanks for the suggestion. As mentioned before, I think this use case is a little niche to warrant a new keyword on `merge_asof`

Closing as there hasn't been much traction on this feature request.
