### ISSUE TITLE
DEPR: box argument in to_datetime and to_timedelta

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#24416]
Following @jreback https://github.com/pandas-dev/pandas/issues/24415#issuecomment-449766969, we should deprecate the `box` argument in `to_datetime` and `to_timedelta` and only return pandas data structures. There already exists options to convert to numpy data structures via `.values` or `to_datetime64`/`to_timedelta64`

**Comment by shoyer** [comment]
We find the option `box=False` quite useful in xarray, to let us leverage pandas for converting inputs into NumPy's timedelta64 and datetime64 dtypes.

I would be a little sad to see it go away, though of course coercing into NumPy arrays is pretty orthogonal to the goals of pandas.

**Comment by jreback** [comment]
use .to_numpy() if you must

**Comment by jorisvandenbossche** [comment]
You cannot use `to_numpy` for scalars, as the example of @shoyer is in https://github.com/pandas-dev/pandas/issues/24957#issue-403499764

(with 0.23.4)
```
In [58]: pd.to_timedelta('NaT', box=False)
Out[58]: numpy.timedelta64('NaT','ns')

In [59]: pd.to_timedelta('NaT', box=True)
Out[59]: NaT

In [60]: type(pd.to_timedelta('NaT', box=True))
Out[60]: pandas._libs.tslibs.nattype.NaTType
```

**Comment by jorisvandenbossche** [comment]
OK, but I see there is https://github.com/pandas-dev/pandas/issues/24653 for adding `to_numpy` to scalars as well. 

For the specific case above, however, the problem is that we don't have a NaT for timedelta, so you would still get `np.datetime64('NaT', 'ns')`
