### ISSUE TITLE
DOC: Add offsets methods to the API reference

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#24436]
The methods of classes in `pandas.tseries.offsets` are not in the API reference. Not sure if there is a reason for it, or it just needs to be implemented.

We have the classes added to:
https://pandas-docs.github.io/pandas-docs-travis/api.html#date-offsets

But most of the attributes and methods are not in `api.rst`, so their pages are not generated. See for example:
https://pandas-docs.github.io/pandas-docs-travis/generated/pandas.tseries.offsets.MonthEnd.html#pandas.tseries.offsets.MonthEnd

Can they simply be added? Or is there a reason not to, or it's more complex than it looks like?

CC: @jbrockmendel @mroeschke

**Comment by mroeschke** [comment]
I'd be good to at least add the methods and attributes for `DateOffset` as the rest of the offsets inherit  from that class; there may be a lot of redundancy if we add the methods and attributes from _all_ the offsets.

**Comment by datapythonista** [comment]
I don't think the redundancy is great, but it's probably the best in this case.

If we don't add the attributes/methods for all offset classes, we have two problems:
- Warnings in the docs (we'll make the doc build fail for warnings soon)
- We won't have the links in the pages of the offset classes (e.g. https://pandas-docs.github.io/pandas-docs-travis/generated/pandas.tseries.offsets.MonthEnd.html#pandas.tseries.offsets.MonthEnd)

Not sure if there is an option with the best of both worlds. May be we can render `api.rst` as we do with `index.rst`, and generate them with a jinja loop?

**Comment by mroeschke** [comment]
Got it. I would be okay with the redundancy to maintain doc stability and/or avoid any hacky solution with rendering.

Moreover, I think some offsets have special methods of their own that would be difficult to render-control for, so I think the easiest thing is to display all methods and attributes.

**Comment by jreback** [comment]
i think we have an open issue about this FYI
yes we should add these (and reference them in time series.rst)

**Comment by datapythonista** [comment]
I search for it, but I couldn't find the issue. Let me know if you do, we can close this.

I'll take care of it.
