### ISSUE TITLE
DOC: Add dateutil to intersphinx

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#24437]
Looks like we'ree using `dateutil` items in the `See Also` section, for example:
https://pandas-docs.github.io/pandas-docs-travis/generated/pandas.tseries.offsets.DateOffset.html

But, for sphinx to generate the links, we need `dateutil` configured as an intersphinx item in `doc/source/conf.py`.

**Comment by benjaminr** [comment]
Happy to have a look at this one.
