### ISSUE TITLE
Imprecision when converting Period to timestamp

### ISSUE THREAD

**Issue by mkuklik** [pandas-dev/pandas#24444]
#### Code Sample, a copy-pastable example if possible

```python
pd.Period("2000-12-31 23:59:59.999").to_timestamp()
```
returns: 2000-12-31 23:59:59.998999999
instead of 2000-12-31 23:59:59.999
It works correctly for other dates, e.g.
```python
pd.Period("2000-12-31 23:59:59.99").to_timestamp()
```
returns correctly "2000-12-31 23:59:59.990000"

#### Problem description
incorrect conversion of Period to Timestamp, see above.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None

pandas: 0.23.4
pytest: None
pip: 18.1
setuptools: 39.1.0
Cython: None
numpy: 1.15.4
scipy: 1.2.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: None
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
on master. looks ok to me
```
In [10]: p = pd.Period('2000-12-31 23:59:59.99')

In [11]: p.freq
Out[11]: <Milli>

In [12]: pd.Period('2000-12-31 23:59:59.99').to_timestamp()
Out[12]: Timestamp('2000-12-31 23:59:59.990000')

In [13]: pd.Period('2000-12-31 23:59:59.99').to_timestamp(how='end')
Out[13]: Timestamp('2000-12-31 23:59:59.990999998')

In [14]: pd.Period('2000-12-31 23:59:59.99').to_timestamp(how='start')
Out[14]: Timestamp('2000-12-31 23:59:59.990000')

In [15]: pd.Period('2000-12-31 23:59:59.99').to_timestamp(how='end') - pd.Period('2000-12-31 23:59:59.99').to_timestamp(how='start')
    ...: 
Out[15]: Timedelta('0 days 00:00:00.000999')
```

@mkuklik can you explain why you think this should be different

**Comment by gfyoung** [comment]
I wonder if this is symptomatic of an intrinsic Python rounding issue?

**Comment by mkuklik** [comment]
How is it fine if 2000-12-31 23:59:59.998999999 != 2000-12-31 23:59:59.999

this conversion should be consistent across all the values without having
to round up in some cases.

**Comment by mroeschke** [comment]
Looks to work on master now. Could use a test

```
In [4]: pd.Period('2000-12-31 23:59:59.999').to_timestamp()
   ...:
Out[4]: Timestamp('2000-12-31 23:59:59.999000')

In [5]: pd.__version__
Out[5]: '1.1.0.dev0+1536.ga7fb88fd5'
```

**Comment by OlivierLuG** [comment]
Hello, 

I've went through examples and review my tests. I think indeed it is not solved.
I think there are issues with `microsecond` == 10^-6s and `nanosecond` == 10^-9s.


```
In [1]: Period("2000-12-31 23:59:59.999999").to_timestamp(freq='ms').microsecond
Out[1]: 999000
```
expected was `999999`
```
In [2]: Period("2000-12-31 23:59:59.123456", freq='ms').to_timestamp().microsecond
Out[2]: 123000
```
expected was `123456`
```
In [3]: Period("2000-12-31 23:59:59.123456").to_timestamp().microsecond
Out[3]: 123456
```
This last example is working, if I do not give the `freq` argument.

Perhaps another bug, the `nanosecond` is not throwing any warning, but always return `0`:
```
In [4]: Period("2000-12-31 23:59:59.123456789").to_timestamp().nanosecond
Out[4]: 0
```
