### ISSUE TITLE
allow detection of whether a csv file contains a header row or not

### ISSUE THREAD

**Issue by Iddoyadlin** [pandas-dev/pandas#24440]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame({'A':[0,1,2,3], 'B':[0.5,0.2,0.3,0.2], 'C':['a','b','c','d']})
df.to_csv('file.csv', header=True, index=False)
hd= HeaderDetector()
df = pd.read_csv('file.csv', detect_header_obj=hd, detect_header=True) 
return list(df.columns)
```
#### Problem description

There are cases where you do not have time to check whether the csv you want to read contains a header row or not (i.e. performing fully automatic analytics on a large amount if files). 
I suggest allowing to pass an object which will be responsible for detecting whether a file has a header row or not. the object will implement has_header in a similar manner to the csv.Sniffer module.

#### Output of the snippet above

<details>

['A', 'B', 'C']

</details>

**Comment by WillAyd** [comment]
I am -1 here as I don't think this is ever really something you can guarantee so it would add a large amount of complexity, but let's see what others think

**Comment by mail2saiky** [comment]
if i understand the issue correctly, some csv files may not contain header row but most of the csv files will contain header row. Why not there be a function that reads all the header rows(user specified) in all the csv files irrespective of whether it contains it or not, and then finally use the mostly occurring row.

final_header = MostOf (list_of_all_header_rows)

**Comment by gfyoung** [comment]
> Why not there be a function that reads all the header rows(user specified) in all the csv files irrespective of whether it contains it or not, and then finally use the mostly occurring row.

I'm not sure I fully understand this?

In terms of the broader discussion, I am indeed wary of adding more parameters to the `read_csv` function given how bloated it is.  In reality, we should be trying to condense it! 🙂 

Also, as was mentioned earlier, the way it would interact with the myriad other parameters we have makes the potential maintenance issue of this parameter somewhat daunting to me.

> If you find this feature interesting, I am willing to work on a pull request for this matter.

@Iddoyadlin : I don't think we disagree that a feature would be nice, but we are very much concerned about how it would integrate with the existing implementation.

@TomAugspurger @WillAyd : That being said, perhaps we could fit something about this in the docs (or cookbook)?  Though I have not experienced it, the concern does not sound super unreasonable to me.

**Comment by MarcelRobitaille** [comment]
> Is there any reason not to use the builtin CSV sniffer, and pass the output
> 
> ```python
> with open("file.csv") as f:
>     header = csv.Sniffer(f).has_header(1024)
> 
> pd.read_csv("file.csv", header=header)
> ```
> 
> On its own that doesn't seem too bad. I worry about the explosion in complexity you get when you have all of pandas' other keywords / capabilities (how would that work for network files? How does it interact with row-based things like `skiprows`?, etc.)

For anyone else coming across this, the syntax has changed slightly:
```python
with open("file.csv") as f:
    header = csv.Sniffer().has_header(f.read(1024))

pd.read_csv("file.csv", header=header)
```

**Comment by mroeschke** [comment]
Sounds like generally this feature would add a lot of complexity into an already complex `read_csv` function and doesn't have much support from other core devs. Thanks for the suggestion though, closing.
