### ISSUE TITLE
`.unique()` for datetime columns returns values that fail equality test for `in` statements

### ISSUE THREAD

**Issue by esvhd** [pandas-dev/pandas#24457]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

s = pd.date_range('2018-01-01', '2018-01-10')
ss = pd.Series(s)

x = ss.unique()
x.dtype
# dtype('<M8[ns]')

ss.dtype == x.dtype
# True

[z in ss for z in x]
# [False, False, False, False, False, False, False, False, False, False]

[z in ss.values for z in x]
# [True, True, True, True, True, True, True, True, True, True]


```
#### Problem description

In `pandas 0.23.4`, `.unique()` returns `np.ndarray` with `dtype='datetime64[ns]`, but the values fails equality tests with the original `pd.Series` of the same `dtype`.

#### Expected Output

`[z in ss for z in x]` and `[z in ss.values for z in x]` should have the same output. In this case, all `True`.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.4
pytest: 4.0.2
pip: 10.0.1
setuptools: 40.6.3
Cython: 0.28.2
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: 0.11.0
IPython: 7.0.1
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.2.2
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.2.0
xlsxwriter: 1.0.2
lxml: 4.1.0
bs4: 4.6.0
html5lib: 0.9999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by mroeschke** [comment]
`Series` is dict-like, so the `in` operators compares against the index. You may want to use something like `.isin` instead.

https://pandas.pydata.org/pandas-docs/version/0.23.4/dsintro.html#series-is-dict-like

```
In [15]: ss
Out[15]:
0   2018-01-01
1   2018-01-02
2   2018-01-03
3   2018-01-04
4   2018-01-05
5   2018-01-06
6   2018-01-07
7   2018-01-08
8   2018-01-09
9   2018-01-10
dtype: datetime64[ns]

In [16]: 0 in ss
Out[16]: True

In [17]: ss.isin([ss[0]])
Out[17]:
0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool
```
