### ISSUE TITLE
Read_excel signature cleanup

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#24487]
Follow up to #24423 and related to #11544 the signatures of functions for parsing excel have slight nuances to them and allow for the passing of keyword args, which may not necessarily be useful.

There's some cleanup here which could be done to align signatures and (maybe) remove keyword arguments

**Comment by ahawryluk** [comment]
Was this issue resolved when when **kwds was removed from pd.read_excel in #34464?

**Comment by rhshadrach** [comment]
That's my take as well @ahawryluk. @WillAyd if you think there is more to do here, please reopen.
