### ISSUE TITLE
CI: Simplify and unify environment creation

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#24498]
When creating a pandas environment for the CI, we currently have two separate systems, one for Travis and one for Azure. Summarizing, those are the involved steps.

**travis**
```
ci/prep_cython_cache.sh
ci/install_travis.sh         -> locale, download/install conda, ccache, create env, setup.py develop
ci/submit_cython_cache.sh
ci/install_db_travis.sh      -> create dbs
ci/before_script_travis.sh   -> xvfb (clipboard)
```

**azure**
```
ci/incremental/install_miniconda.sh          -> download/install conda
ci/incremental/setup_conda_environment.sh    -> create env, locale
ci/incremental/build.sh                      -> setup.py build_ext
```

Except for the cython cache, I think all the rest could be unified in a single file `ci/setup_env.sh` that performs all the steps.

This would simplify and avoid duplicate code and inconsistencies. As well as making future changes simpler.

**Comment by saurav2608** [comment]
@datapythonista - Can I take a shot at this?

**Comment by datapythonista** [comment]
sure, go ahead

**Comment by datapythonista** [comment]
Afaik, `setup.py develop` installs the package locally (compiling and with dependencies), `setup.py build_ext` is just the compiling part.

Not sure about the reasoning here, may be things changed in the setuptools/pip since this was first set up. I think `setup.py develop` is not used much nowadays. When not using conda, `pip install -e .` is usually the preferred way, as `pip` is smarter than `setuptools` with dependencies. If we're using conda, I think `setup.py develop` should be unnecessary, but may be there is a reason I don't know in this case.
