### ISSUE TITLE
Add ad-hoc indexing to DataFrame

### ISSUE THREAD

**Issue by wesm** [pandas-dev/pandas#245]
Not necessarily set row labels but enable fast selections by some criteria

**Comment by levithomason** [comment]
Whew, might need a bot to do some old issue scrubbing :)

**Comment by jorisvandenbossche** [comment]
@wesm Can you give an example of what you exactly mean (not familiar with `data.table`), or otherwise close if it is not relevant anymore?

**Comment by wesm** [comment]
I don't think there is a well-defined scope here given pandas 2.0 discussions. Closing
