### ISSUE TITLE
Cannot build documents

### ISSUE THREAD

**Issue by thoo** [pandas-dev/pandas#24505]
#### Code Sample, a copy-pastable example if possible

```python
python setup.py build_ext --inplace -j 4
python -m pip install -e .
python make.py --single pandas.read_excel
```
#### Problem description
```sh
/Users/johndoe/pandas/doc/source/index.rst:110: WARNING: toctree references excluded document 'generated/pandas.read_excel'
```

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: c4ac0d68b2418e261f2fd8f3a9f8eca0d5e20474
python: 3.6.6.final.0
python-bits: 64
OS: Darwin
OS-release: 18.0.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.0.dev0+1419.gc4ac0d68b
pytest: 4.0.2
pip: 18.1
setuptools: 40.4.3
Cython: 0.28.5
numpy: 1.15.2
scipy: 1.1.0
pyarrow: 0.9.0
xarray: 0.10.9
IPython: 6.5.0
sphinx: 1.8.1
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: 1.6.2
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: 0.4.0
matplotlib: 3.0.0
openpyxl: 2.5.5
xlrd: 1.1.0
xlwt: 1.2.0
xlsxwriter: 1.1.1
lxml.etree: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.12
pymysql: 0.9.2
psycopg2: None
jinja2: 2.10
s3fs: 0.1.6
fastparquet: 0.1.6
pandas_gbq: None
pandas_datareader: None
gcsfs: 0.1.2
</details>

**Comment by alimcmaster1** [comment]
Should be able to close ##24506 addresses this
