### ISSUE TITLE
DOC: Missing PandasArray methods in API

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#24507]
We've got warning in sphinx because we don't have the `PandasArray` methods in the API:
```
/home/mgarcia/src/pandas/doc/source/api/generated/pandas.arrays.PandasArray.all.rst: WARNING: document isn't included in any toctree
/home/mgarcia/src/pandas/doc/source/api/generated/pandas.arrays.PandasArray.any.rst: WARNING: document isn't included in any toctree
/home/mgarcia/src/pandas/doc/source/api/generated/pandas.arrays.PandasArray.kurt.rst: WARNING: document isn't included in any toctree
/home/mgarcia/src/pandas/doc/source/api/generated/pandas.arrays.PandasArray.max.rst: WARNING: document isn't included in any toctree
/home/mgarcia/src/pandas/doc/source/api/generated/pandas.arrays.PandasArray.mean.rst: WARNING: document isn't included in any toctree
/home/mgarcia/src/pandas/doc/source/api/generated/pandas.arrays.PandasArray.median.rst: WARNING: document isn't included in any toctree
/home/mgarcia/src/pandas/doc/source/api/generated/pandas.arrays.PandasArray.min.rst: WARNING: document isn't included in any toctree
/home/mgarcia/src/pandas/doc/source/api/generated/pandas.arrays.PandasArray.prod.rst: WARNING: document isn't included in any toctree
/home/mgarcia/src/pandas/doc/source/api/generated/pandas.arrays.PandasArray.sem.rst: WARNING: document isn't included in any toctree
/home/mgarcia/src/pandas/doc/source/api/generated/pandas.arrays.PandasArray.skew.rst: WARNING: document isn't included in any toctree
/home/mgarcia/src/pandas/doc/source/api/generated/pandas.arrays.PandasArray.std.rst: WARNING: document isn't included in any toctree
/home/mgarcia/src/pandas/doc/source/api/generated/pandas.arrays.PandasArray.sum.rst: WARNING: document isn't included in any toctree
/home/mgarcia/src/pandas/doc/source/api/generated/pandas.arrays.PandasArray.var.rst: WARNING: document isn't included in any toctree
```

I guess those are public and should be added. But I'm not quite sure where we should have them, we have some related stuff in two different places:

- https://pandas-docs.github.io/pandas-docs-travis/api/series.html#arrays
- https://pandas-docs.github.io/pandas-docs-travis/api/extensions.html

Not sure if we need to reorganize those. @TomAugspurger

**Comment by TomAugspurger** [comment]
I might support moving all the extension arrays to a single page, but I
haven't looked closely at what we have right now.

We could include PandasArray on that page.

**Comment by enisnazif** [comment]
I'm taking a look at this as part of the pandas sprint in London

**Comment by enisnazif** [comment]
Possibly related to this issue - but it seems that on https://pandas-docs.github.io/pandas-docs-travis/reference/api/pandas.arrays.PandasArray.html

The same functions that aren't included in a toctree also don't have any docstrings

**Comment by jorisvandenbossche** [comment]
Another option is to add a PandasArray page but without any methods/attributes listed (or only a chosen subset), as we do for other array types (see eg https://pandas-docs.github.io/pandas-docs-travis/reference/api/pandas.arrays.IntervalArray.html or https://pandas-docs.github.io/pandas-docs-travis/reference/api/pandas.Categorical.html)

**Comment by rhshadrach** [comment]
This has been renamed to NumpyExtensionArray and that is in the API docs.

https://pandas.pydata.org/docs/dev/reference/api/pandas.arrays.NumpyExtensionArray.html

Closing.
