### ISSUE TITLE
DatetimelikeArray._reduce signature doesn't match base class

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#24514]
We have

```
def _reduce(self, name, axis=0, skipna=True, **kwargs):
```

the base class has

```
def _reduce(self, name, skipna=True, **kwargs):
```

Any reason to include axis=0 there?

**Comment by TomAugspurger** [comment]
cc @jbrockmendel

**Comment by TomAugspurger** [comment]
Can we also remove `*args` and `**kwargs` from min / max?  We should be able to do `min(self, axis=None, out=None, keepdims=None, initial=None)` and everything will be validated

**Comment by jreback** [comment]
we use *args and **kwargs and everything is validate now

changing this would involve changing virtually every user api in pandas - so no go here

**Comment by TomAugspurger** [comment]
It's just for DatetimeArray, not every user API.

**Comment by jreback** [comment]
inconsistent means special cases and that’s -1

**Comment by TomAugspurger** [comment]
What's the reason for *args, **kwargs in the first place?

**Comment by jreback** [comment]
to allow np.min(..)

and avoiding having to specify all of the optional kwargs as that pollutes the signature too much

**Comment by jbrockmendel** [comment]
There is no longer a mismatch.  Closing.
