### ISSUE TITLE
Unable to read first n rows from parquet file.

### ISSUE THREAD

**Issue by san089** [pandas-dev/pandas#24511]
```python
df = pd.read_parquet(path= 'filepath', nrows = 10)

```
#### Problem description

I have a parquet file and I want to read first n rows from the file into a pandas data frame. I did not find any way to do this in the documentation. I tried the 'nrows' and 'skiprows' parameter, but it did not work with the read_parquet() method. Do let me know if there is any way to achieve it that is not mentioned in the documentation.

Alternatively, I can read the complete parquet file and filter the first n rows, but that will require more computations which I want to avoid.

**Comment by TomAugspurger** [comment]
Does pyarrow or fastparquet allow reading a subset of the file?

**Comment by TomAugspurger** [comment]
Perhaps raise issues upstream to see if there's interest in support this
feature. Once the engines support it we'll be able to add a keyword.

**Comment by jreback** [comment]
closing as out of scope; we would need the engines to do this. Note that you might be able to simply filter by row groups.

**Comment by TomAugspurger** [comment]
You would need to raise that with fastparquet or pyarrow. I don't whether
or not the parquet format supports that.

**Comment by fny** [comment]
I want to reopen this issue. PyArrow now supports many of the required operations to make `nrows` possible and even `usecols`.

<img width="739" alt="image" src="https://user-images.githubusercontent.com/346068/189361279-0a7d80c8-e7a8-442e-9c09-2312953c79d3.png">
