### ISSUE TITLE
DEPR: deprecate pandas/io/date_converters.py

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#24518]
This file contains one function that is used elsewhere in the code base (that can be moved), and the rest is unused and not advertised in the api.

Raising this issue to gauge whether we should outright remove it or deprecate this file since its technically public in `io`

**Comment by jreback** [comment]
yeah let's do it. I also think you can just remove the ``generic_parser`` branch entirely (meaning just fully deprecate this), I think ``to_datetime`` handles all of these cases

**Comment by jorisvandenbossche** [comment]
Yes, I think the original idea behind this was to have functions that could be passed to `read_csv`'s `date_parser` function. But there are much better ways to do that (`to_datetime`, or a way to provide a date format in `read_csv` that is discussed elsewhere). 
So happy to see it deprecated

**Comment by jbrockmendel** [comment]
definitely go for it.

**Comment by jbrockmendel** [comment]
Is any of this user-facing (i.e.need deprecation cycle) or can we just rip it out?

**Comment by mroeschke** [comment]
The conservative thing to do is go through a deprecation cycle, but since this is not advertised anywhere ripping it out _might_ be okay.

**Comment by jorisvandenbossche** [comment]
This is documented (https://dev.pandas.io/docs/user_guide/io.html#date-parsing-functions), so certainly needs to be deprecated first I think

**Comment by avinashpancham** [comment]
take
