### ISSUE TITLE
Examples for Series ops should be specific to each method.

### ISSUE THREAD

**Issue by timgeb** [pandas-dev/pandas#24589]
The code example for [Series.divmod](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.divmod.html) uses `Series.add` and I'm not sure what this is supposed to convey.

In addition, "Equivalent to `series divmod other`" and "See also: `Series.None`" look strange to me.

**Comment by dsaxton** [comment]
It looks to me like this is a larger problem with the `Series` operations documentation in general:

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.gt.html
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.lt.html
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.eq.html
...

**Comment by timgeb** [comment]
What's more, trying to make an example I could not get the `divmod` method to work at all in 0.23.4.

**Comment by timgeb** [comment]
I think each method deserves an example.

**Comment by khizirsiddiqui** [comment]
Hi!
If no one is assigned to this issue, I would want to work on this as my first issue.
[Line 473 here](https://github.com/pandas-dev/pandas/blob/0409521665bd436a10aea7e06336066bf07ff057/pandas/core/ops.py#L473) hard-codes this.

**Comment by TomAugspurger** [comment]
Repurposing this for a general "fix all the Series ops examples".

It'd be helpful if someone could make a checklist on GitHub with all the Series ops (add, divmod, etc.) that need examples. And we can check them off as we go (one PR per op).

**Comment by danielplawrence** [comment]
Hi all, first contributor here

Looks like the list of affected cases is [here](https://github.com/pandas-dev/pandas/blob/0409521665bd436a10aea7e06336066bf07ff057/pandas/core/ops.py#L403-462)

Checklist:

- [ ] [pandas.Series.sub](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.sub.html)
- [ ] [pandas.Series.mul](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.mul.html)
- [ ] [pandas.Series.mod](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.mod.html)
- [ ] [pandas.Series.pow](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.pow.html)
- [ ] [pandas.Series.truediv](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.truediv.html)
- [ ] [pandas.Series.floordiv](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.floordiv.html)
- [ ] [pandas.Series.divmod](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.divmod.html)
- [ ] [pandas.Series.eq](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.eq.html)
- [ ] [pandas.Series.ne](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.ne.html) 
- [ ] [pandas.Series.lt](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.lt.html) 
- [ ] [pandas.Series.le](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.le.html)
- [ ] [pandas.Series.gt](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.gt.html)
- [ ] [pandas.Series.ge](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.ge.html)

A quick script for comparing Series method docstring content: [link](https://gist.github.com/danielplawrence/afc16cc1434fb9329ffa0519d9bbb3a8)

**Comment by danielplawrence** [comment]
So my understanding is that we will need to:
- Remove the examples under "Examples:" in [__flex_doc_SERIES](https://github.com/pandas-dev/pandas/blob/master/pandas/core/ops.py/#L476-L520).
- Modify the _flex_doc_SERIES template and _make_flex_doc to allow injection of method-specific examples via str.format(). It looks like this was already implemented for dataframes in [this revision](https://github.com/pandas-dev/pandas/blob/0409521665bd436a10aea7e06336066bf07ff057/pandas/core/ops.py#L623-L661)
- Write examples for each method (e.g. _divmod_example_SERIES etc.) and add a key to  [_op_descriptions](https://github.com/pandas-dev/pandas/blob/master/pandas/core/ops.py#L387-L417) (e.g. 'series_examples') to be passed to _make_flex_doc and added to the output docstring.

**Comment by danielplawrence** [comment]
Opened initial PR [here](https://github.com/pandas-dev/pandas/pull/25524), please let me know if this approach makes sense. Do we have any guidelines for writing examples?

**Comment by Ran363** [comment]
Hi all, first timer here.
would love to give a hand,
where can I see what needs to be done?

**Comment by TomAugspurger** [comment]
https://github.com/pandas-dev/pandas/pull/25524 may give some insight. That did add and sub. 

https://github.com/pandas-dev/pandas/blob/045880c29e4d40dc0458d2a3272d145174b5122d/pandas/core/ops/docstrings.py#L236 has the list. Items there where `df_examples` is None need to be updated.

**Comment by avimiller** [comment]
I would like to add series examples for "gt", "lt", and "eq" if that is okay.

**Comment by TomAugspurger** [comment]
@sullivanbt after https://github.com/pandas-dev/pandas/pull/32704, is divmod the only one remaining?

**Comment by sullivanbt** [comment]
@TomAugspurger Yes, `divmod` was the only one remaining after #32704
