### ISSUE TITLE
int is detected as an object

### ISSUE THREAD

**Issue by orena1** [pandas-dev/pandas#24586]
#### Code Sample, a copy-pastable example if possible

```python
exp_data = pd.DataFrame(columns=['a','b', 'c']); i=0
exp_data.loc[i] =['test',90,2.0];i+=1
exp_data.dtypes

a     object
b     object
c    float64
dtype: object

#now when I want to plot it as a scatter I get an error:
exp_data.plot.scatter('b','c')
ValueError: scatter requires x column to be numeric
```
#### Problem description
Should the table detect b as an **int** or a **float**? why it detects it as an object?

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.14.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-514.26.2.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.23.4
pytest: 3.3.2
pip: 18.1
setuptools: 39.2.0
Cython: 0.27.3
numpy: 1.14.2
scipy: 1.1.0
pyarrow: 0.9.0
xarray: None
IPython: 5.4.1
sphinx: 1.6.6
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.5
feather: 0.4.0
matplotlib: 2.2.2
openpyxl: 2.4.10
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.2.3
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.9
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: 0.1.6
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
When you create the empty data frame in the first line all the columns are object dtype

```python
In [53]: exp_data.dtypes
Out[53]:
a    object
b    object
c    object
dtype: object
```

Pass empty ndarrays or series if you want column-specific dtypes.
