### ISSUE TITLE
COMPAT: IntegerXXDtypes string repr cause numpy deprecation warnings

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#24593]
The 'numeric-style' type codes are deprecated in numpy, but they clash with our pandas integer dtypes strings (with the capital):

```
In [7]: np.dtype('Int64')                                     
/home/joris/miniconda3/envs/dev/bin/ipython:1: DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.
  #!/home/joris/miniconda3/envs/dev/bin/python
Out[7]: dtype('int64')
```

This causes some deprecation warnings in `pd.core.dtypes.common._get_dtype_type`, which surfaces those through eg `is_integer_dtype`:
```
In [1]: import warnings                                      

In [2]: warnings.simplefilter('always', DeprecationWarning)

In [3]: pd.api.types.pandas_dtype('Int64')                                                
Out[3]: <pandas.core.arrays.integer.Int64Dtype at 0x7fa8dc28c518>

In [4]: pd.core.dtypes.common._get_dtype_type('Int64')                                             
/home/joris/scipy/pandas/pandas/core/dtypes/common.py:1864: DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.
  return _get_dtype_type(np.dtype(arr_or_dtype))
Out[4]: numpy.int64

In [6]: pd.api.types.is_integer_dtype('Int64')                         
/home/joris/scipy/pandas/pandas/core/dtypes/common.py:1864: DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.
  return _get_dtype_type(np.dtype(arr_or_dtype))
Out[6]: True
```

**Comment by jorisvandenbossche** [comment]
"Strange" thing here is that this is not being raised on the numpy-dev build on Azure, which should be failing when there are uncatched numpy warnings (so either there is a reason that they are not raised there, or there is a problem with the "fail-on-warning" mode)

**Comment by TomAugspurger** [comment]
Do you know what test this is hit in?

It's possible that the warnings are being elevated to errors in the numpydev build, but whatever code is calling this may be catching the exception.

**Comment by jorisvandenbossche** [comment]
Would still be good to investigate why Azure dev build was not failing.

@TomAugspurger do you remember on what is is supposed to fail? On any warning? Or only DeprecationWarning/FutureWarnings? Only from specific packages? Or only from pandas? 

It is a bit fishy that in the azure build there is no warning at all, while in all travis builds there are plenty of warnings (both from numpy and pandas). Which seems to indicate that just no warnings are reported at all with pytest on azure.

**Comment by TomAugspurger** [comment]
It should fail on any warning from any package.

Checking in https://github.com/pandas-dev/pandas/pull/24616.

It's possible that the warnings (from numpy / pandas) are only hit on code
that's not run as part of the numpydev build.

**Comment by jorisvandenbossche** [comment]
It's running `pytest -m "not single and not slow and not network"`, so I would find that strange. Although maybe a lot of tests are skipped if no optional dependencies are installed

**Comment by jorisvandenbossche** [comment]
> Although maybe a lot of tests are skipped if no optional dependencies are installed

Which might be the case, as only numpy ans scipy are installed (so no plotting, not any optional IO, ..)
