### ISSUE TITLE
DOC: remove okwarning once pyarrow 0.12 is released

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#24617]
TODO: Revert https://github.com/pandas-dev/pandas/pull/24591 once pyarrow is released

**Comment by jbrockmendel** [comment]
Do we have a minimal pyarrow we support?  environment.yml lists pyarrow>=0.7.0.  There are some special cases in internals.blocks for pyarrow compat that would be nice to get rid of eventually.

**Comment by jreback** [comment]
not averse to bumping

**Comment by jbrockmendel** [comment]
It looks like the commit that removed pyarrow's deprecated usage was 2018-01-25 https://github.com/apache/arrow/commit/6bb1d1b35f21ce34327cf92893bda417c2a9a4f1.  The first release after that looks like 0.9.0 on 2018-03-16

**Comment by jreback** [comment]
bump to 0.9.0 would be fine

**Comment by jorisvandenbossche** [comment]
I am also fine with bumping to 0.9.0. 
That is however unrelated to the original issue here, though. @jbrockmendel can you open a new issue for that?
