### ISSUE TITLE
BLD: 32-bit builds failing

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#24613]
https://travis-ci.org/MacPython/pandas-wheels/jobs/475157492

failing with

```
Exception ignored in: 'pandas._libs.tslibs.conversion.tz_convert_single'
Traceback (most recent call last):
  File "pandas/_libs/tslibs/conversion.pyx", line 663, in pandas._libs.tslibs.conversion._tz_convert_dst
ValueError: Buffer dtype mismatch, expected 'int64_t' but got 'int'
Traceback (most recent call last):
  File "pandas/_libs/tslibs/conversion.pyx", line 663, in pandas._libs.tslibs.conversion._tz_convert_dst
ValueError: Buffer dtype mismatch, expected 'int64_t' but got 'int'
Exception ignored in: 'pandas._libs.tslibs.conversion.tz_convert_single'
```

**Comment by jreback** [comment]
cc @mrocklin @qwhelan I think the perf enhancement changed this

**Comment by jorisvandenbossche** [comment]
I suppose you meant to tag @mroeschke instead of @mrocklin  :)

It's about this PR: https://github.com/pandas-dev/pandas/pull/24491

**Comment by jreback** [comment]
yep thanks

**Comment by qwhelan** [comment]
@jreback Certainly seems like my PR is to blame - I'll take a look

**Comment by qwhelan** [comment]
So what's happening is:
- `np.searchsorted()` always returns a result of type `np.intp`, which is 32-bit on 32, 64 on 64
- `int64_t[:] pos` needs to be `intp_t[:] pos` as a result
- Seems we've always been unable to properly index into an array of size greater than int32 on 32-bit via `np.searchsorted`. I'm guessing there's no test coverage for something like this, but would be easy to construct a test case for.

Just opened #24621 to implement the above.
