### ISSUE TITLE
TST: deprecation warnings

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#24611]
```
pandas/core/arrays/datetimes.py:1112
  /home/travis/build/pandas-dev/pandas/pandas/core/arrays/datetimes.py:1112: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
    "will drop timezone information.", UserWarning)
```
on master

**Comment by jreback** [comment]
cc @jbrockmendel @TomAugspurger 

not sure what test, maybe we need to increase the stacklevel as well.

**Comment by TomAugspurger** [comment]
Which build is this in?

**Comment by jreback** [comment]
I think all:https://travis-ci.org/pandas-dev/pandas/jobs/475224535 for example

**Comment by TomAugspurger** [comment]
Thanks. Taking a look now.

**Comment by jreback** [comment]
any idea on this @TomAugspurger @jbrockmendel

**Comment by TomAugspurger** [comment]
IIRC, I wasn't able to reproduce locally.

**Comment by gfyoung** [comment]
https://travis-ci.org/pandas-dev/pandas/builds/482169977

https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=7127

@jreback : I checked the output of all of these builds, and that warning is no longer there.

We can keep a watch for it, but I think the original issue was resolved at some point.
