### ISSUE TITLE
COMPAT: alias .to_numpy() for scalars

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#24653]
I think we achieve a bit more consistency in our interfaces if we alias ``.to_numpy()`` to ``.to_datetime64()`` and ``.to_timedelta64()`` for ``Timedelta`` and ``Timestamp`` respectively.

xref https://github.com/pandas-dev/pandas/pull/24486/files#diff-26a6d2ca7adfca586aabbb1c9dd8bf36L235

**Comment by jbrockmendel** [comment]
Could do the same for to_py, I think arrow does this

**Comment by cbertinato** [comment]
What should we do for the `to_numpy()` keyword arguments?  Neither `dtype` nor `copy` make sense in the case of a scalar.  Just let it raise the TypeError if either is passed, or accept the arguments and do nothing?

**Comment by jreback** [comment]
i think it’s ok to have them i. the signature for compatibility (default to None); but they will be ignored
