### ISSUE TITLE
DEPR:  copy argument in DataFrame/Series.tz_localize/tz_convert

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#24667]
ref: https://github.com/pandas-dev/pandas/pull/24657#issuecomment-451959299

The `copy` argument in these methods should be deprecated in favor of `inplace` to be consistent with other methods.

**Comment by jorisvandenbossche** [comment]
Whether we want to do this or not might depend on the discussion in https://github.com/pandas-dev/pandas/issues/16529

**Comment by jbrockmendel** [comment]
the future of 'copy' depends on CoW, but i think we're agreed against implementing _more_ `inplace` keywords.  closeable?

**Comment by mroeschke** [comment]
Yeah agreed that probably shouldn't be replaced with `inplace` but `copy` here should get the same treatment as your similar PRs for methods that only effect the index?

**Comment by jbrockmendel** [comment]
> but copy here should get the same treatment as your similar PRs for methods that only effect the index?

Not sure what you mean.  tz_convert/tz_localize already make shallow copies when copy=False

**Comment by mroeschke** [comment]
Ah gotcha. Nonetheless your original point stands as `copy` should be kept in favor of `inplace`
