### ISSUE TITLE
Segmentation fault after set_categories()

### ISSUE THREAD

**Issue by henlue** [pandas-dev/pandas#24675]
#### Code Sample, a copy-pastable example if possible

```python
>>> import pandas as pd
>>> s = pd.Series(['A', 'B']).astype('category').cat.set_categories(['A'], rename=True)
>>> print(s)
Segmentation fault
```
#### Problem description

The segmentation fault occurs,
 - if `set_categories()` is called with fewer new categories than original categories
 - and rename is set true
 - as soon as the data is accessed.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-957.1.3.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: None
pip: 18.1
setuptools: 40.6.3
Cython: None
numpy: 1.15.4
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by WillAyd** [comment]
Thanks for the report. Investigation and PRs are always welcome!

**Comment by jschendel** [comment]
Simplifying a little, the same thing happens when working directly with a `Categorical`:
```python
pd.Categorical(['A', 'B']).set_categories(['A'], rename=True)
```
