### ISSUE TITLE
DOC: add "experimental" warning to some new array-related features?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#24673]
I would propose to add some "experimental" warnings in certain docstrings / parts of the whatsnew for the new array-related functionality we are adding in 0.24.0. Thoughts about that?

And if we do that, where should we add it? I was thinking about `IntegerArray`, `pd.array`, `PandasArray`, maybe `.array` attribute

**Comment by TomAugspurger** [comment]
Fine by me. What do we anticipate changing? I could see some corner cases in `pd.array`.

 Probably `PandasArray` as well, (and so perhaps `Series/Index.array` by extension).

**Comment by mroeschke** [comment]
Not sure what warnings ended up being issued in 0.24.0, but if we need to add more warnings to other features for EA related in a future release we can do so. Closing
