### ISSUE TITLE
ValueError when using multi-level sum on Pandas DataFrame with empty columns

### ISSUE THREAD

**Issue by nheeren** [pandas-dev/pandas#24671]
#### Code Sample

```python
df = pd.DataFrame(np.random.randn(3, 8),
                  columns=pd.MultiIndex.from_arrays((['A','A','A', 'A', 'B', 'B', 'B', 'B'], 
                                                     ['a', 'b', 'c', 'd', 'a', 'b', 'c', 'd'], 
                                                     ['i', 'ii', 'i', 'ii', 'i', 'ii', 'i', 'ii'])))
df.loc[:, ('A','b','ii')] = None
df.sum(level=[1,2], axis=1)

ValueError: No axis named 1 for object type <class 'pandas.core.series.Series'>
```
#### Problem description

See also: https://stackoverflow.com/q/54081566/2075003

The issue are empty columns in the Dataframe. Using `df.fillna(0).sum(level=[1,2], axis=1)` is a workaround but removes `None` values (obviously). Using `df.transpose().sum(level=[1,2], axis=1).transpose()` is another workaround, but very slow.

#### Expected Output

A summed df.

```python
df.sum(level=[1,2], axis=1)

          a         b         c         d
          i        ii         i        ii
0 -0.696007 -0.152525 -2.330206 -2.211354
1  1.509300  0.094021  1.511495  1.732159
2 -0.068290 -3.596403  0.959772  0.711497
```

#### Output of ``pd.show_versions()``

  INSTALLED VERSIONS
    ------------------
    commit: None
    python: 3.7.2.final.0
    python-bits: 64
    OS: Darwin
    OS-release: 16.7.0
    machine: x86_64
    processor: i386
    byteorder: little
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8
    LOCALE: en_US.UTF-8
    pandas: 0.23.4
    pytest: None
    pip: 18.1
    setuptools: 40.6.3
    Cython: None
    numpy: 1.15.4
    scipy: 1.2.0
    pyarrow: None
    xarray: None
    IPython: 7.2.0
    sphinx: None
    patsy: None
    dateutil: 2.7.5
    pytz: 2018.7
    blosc: None
    bottleneck: None
    tables: None
    numexpr: None
    feather: None
    matplotlib: 3.0.2
    openpyxl: 2.5.12
    xlrd: 1.2.0
    xlwt: 1.3.0
    xlsxwriter: None
    lxml: None
    bs4: None
    html5lib: None
    sqlalchemy: None
    pymysql: None
    psycopg2: None
    jinja2: None
    s3fs: None
    fastparquet: None
    pandas_gbq: None
    pandas_datareader: None

**Comment by nheeren** [comment]
Seems identical to https://github.com/pandas-dev/pandas/issues/24251 – sorry

**Comment by WillAyd** [comment]
Thanks for the report. Investigation and PRs are always welcome!

**Comment by ikramersh** [comment]
Looks like this works in pandas v1.3.4

**Comment by mroeschke** [comment]
Doesn't look like this issue is relevant anymore since the `level` keyword was deprecated and removed in 2.0 so closing
