### ISSUE TITLE
Why does pandas.read_csv converts strings to NaN?

### ISSUE THREAD

**Issue by tastyminerals** [pandas-dev/pandas#24681]
#### Code Sample, a copy-pastable example if possible

```python
def get_char_vocab(words: Sequence[str], size: int = 200) -> Dict[str, int]:
    return get_vocab("".join(words), size)

vocab = pd.read_csv(data_file, index_col=['id'], header=0, delimiter='\t', quoting=csv.QUOTE_NONE) 
char_vocab = get_char_vocab(vocab["word"])
```
#### Problem description

data_file is a huge csv file with `\t` delimited 8 columns. 
This file contains the following several rows.

```csv
b1338cd0-feed-11e8-946e-e5be960a5987	<para>	<para>	73.557	688.67	0	0	0
b1338cd0-feed-11e8-946e-e5be960a5987	test/ok	test/ok	73.557	689.059	1	0	0
b1338cd0-feed-11e8-946e-e5be960a5987	n/a	N/A	108.195	688.865	1	1	0
b1338cd0-feed-11e8-946e-e5be960a5987	n/a	N/A	130.378	688.865	1	1	0
b1338cd0-feed-11e8-946e-e5be960a5987	test2	test2	154.508	688.865	1	0	0
b1338cd0-feed-11e8-946e-e5be960a5987	test3	test3	170.27	688.865	1	0	0
b1338cd0-feed-11e8-946e-e5be960a5987	<unk>	Szx	200.043	688.67	1	0	0
```

Once pandas read this csv the data the second column starts to look the following way:

```csv
b1338cd0-feed-11e8-946e-e5be960a5987         <para>
b1338cd0-feed-11e8-946e-e5be960a5987        test/ok
b1338cd0-feed-11e8-946e-e5be960a5987            NaN
b1338cd0-feed-11e8-946e-e5be960a5987            NaN
b1338cd0-feed-11e8-946e-e5be960a5987           test2
b1338cd0-feed-11e8-946e-e5be960a5987         test3
b1338cd0-feed-11e8-946e-e5be960a5987          <unk>
```

Why on earth does pandas convert two "n/a" strings into `NaN`?

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Linux
OS-release: 4.14.91-1-MANJARO
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 4.0.0
pip: 18.1
setuptools: 40.4.3
Cython: 0.29
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.0.1
sphinx: 1.8.2
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jorisvandenbossche** [comment]
> Why on earth does pandas convert two "n/a" strings into NaN?

Because on earth, "n/a" is often used as the specifier for missing data, and in pandas NaN is used for missing data.

If you want to disable those default strings to be parsed as NaN, you can use the `keep_default_na=False, na_values=[""]` keyword arguments. See here for more details: https://pandas.pydata.org/pandas-docs/stable/io.html#na-values

**Comment by tastyminerals** [comment]
It sounds like a serious argument. Sincerely hope you did research and do have data to support the argument. And even if you did, it should have been not `keep_default_na=False` but `treat_special_strings_as_na=True`.
