### ISSUE TITLE
Disk increase extremly after modify DataFrame instance and copy its np.ndarray to list

### ISSUE THREAD

**Issue by Antsypc** [pandas-dev/pandas#24696]
#### Code Sample
Versions: `python 3.6.5`, `pandas 0.23.0`, `numpy 1.14.3`, `macOS 10.14.1`

```python
from scipy.stats import zscore

def generate_dataset(df_data, feature_name, continuous_range, normalize=True, time_step=3):
    """
    Args:
         df_data: DataFrame, shape=(20000, 61)
         feature_name: list of string, length is 60
         continuous_range: list of tuple (int, int), you can simply set it to [(0, 19990)]
    """
    if normalize:
        # modify every column by z-score normalization
        df_data.loc[:, feature_name] = df_data[feature_name].apply(zscore)

    feats = []  # list of ndarray, shape of ndarray is (time_step, 60)
    for start, end in continuous_range:
        for i in range(start, end - time_step + 1):
            feats.append(df_data[feature_name].iloc[i: i + time_step].values)
```

#### Problem description
As for-loop code above, I copy numpy.ndarray values from DataFrame instance to a list, then my computer disk increase rapidly from 50G left to 2G left, finally my laptop crashed!

However, if I don't modify `df_data.loc[:, feature_name]`(It means I don't execute if block codes above), everything is OK. If there are not so many rows in `df_data`, I think everything ganna be ok.

Could you guys please explain why this happened? How to write this function in a right way, especially handle large DataFrame object? I just want to modify df_data and copy a series values to a list.

THANKS.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------

commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.0
pytest: 3.5.1
pip: 10.0.1
setuptools: 39.1.0
Cython: 0.28.2
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.2.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by jreback** [comment]
needs to be a self-contained reproducible example

**Comment by Antsypc** [comment]
@jreback Here is a reproducible example that errors happened in my enviroment.
Versions: `python 3.6.5`, `pandas 0.23.0`, `numpy 1.14.3`, `macOS 10.14.1`

```
from scipy.stats import zscore
import pandas as pd
import numpy as np

def generate_dataset(df_data, feature_name, continuous_range, normalize=True, time_step=3):
    """
    Args:
         df_data: DataFrame, shape=(20000, 61)
         feature_name: list of string, length is 60
         continuous_range: list of tuple (int, int), you can simply set it to [(0, 19990)]
    """
    if normalize:
        # modify every column by z-score normalization
        df_data.loc[:, feature_name] = df_data[feature_name].apply(zscore)

    feats = []  # list of ndarray, shape of ndarray is (time_step, 60)
    for start, end in continuous_range:
        for i in range(start, end - time_step + 1):
            feats.append(df_data[feature_name].iloc[i: i + time_step].values)
    return feats


if __name__ == "__main__":
    _names = ['x_%s'%i for i in range(60)]
    data = pd.DataFrame(np.random.randn(20000, 60), columns=_names)
    generate_dataset(data, _names, [(0, 19990)])
```

**Comment by WillAyd** [comment]
Have you isolated the issue to a particular line in your code? We typically ask for bug reports to be minimal so as to avoid time wasted on conflating factors

**Comment by Antsypc** [comment]
@WillAyd In my code example above that I have tested, if I don't execute `df_data.loc[:, feature_name] = df_data[feature_name].apply(zscore)`, `feats.append()` works well. However as I modify `df_data.loc[:, feature_name] ` and do `feats.append()`, my disk space run out.

**Comment by Antsypc** [comment]
@WillAyd Actually, If I normalize `df_data` and save it to disk, then `pd.read_csv` without modification, just do `feats.append()`, disk space run out again. It's very weird. I cannot figure out why this is related to disk, I think all computaion in the merroy. There is nothing about disk stuff. Is that right?

**Comment by Antsypc** [comment]
@WillAyd I'm sorry for my expression. I'm not sure the error stems from pandas either.

The main code are line `df_data.loc[:, feature_name] = df_data[feature_name].apply(zscore)` and line `feats.append(df_data[feature_name].iloc[i: i + time_step].values)`.  Details what happened to these codes I explain above.

So far I think the error happen or not, it depends on np.ndarray in the pandas instance, it dosen't matter modify DataFrame or not. Maybe you can run it in your enviroment. My friends ran code example above for me, they also got the same error.

Here are some test cases.
- disk run out: `python 3.6.5`, `pandas 0.23.0`, `numpy 1.14.3`, `macOS 10.14.1`, `16G RAM`
- disk run out: `python 3.6.5`, `pandas 0.23.0`, `numpy 1.14.3`, `windows 10`, `8G RAM`
- OOM: `python 3.6.1`, `pandas 0.20.1`, `numpy 1.12.1`, `windows 10`, `8G RAM`
- success, no memory error, no disk change: `python 3.7.1`, `pandas 0.23.4`, `numpy 1.15.4`, `centOS 7`, `256G RAM`

**Comment by WillAyd** [comment]
Going to close this as unfortunately there's nothing that really indicates a pandas error here (feel free to reopen if you can pinpoint). AFAICT you are continually generating rather large slices of your data frame in a loop, so it's certainly possible that your machine doesn't have the memory to contain all of those objects and flushes to disk.

Not sure the end goal with the function you have but there may be a more holistic design approach you can consider to greatly reduce the memory footprint here and avoid running out of resources, totally agnostic to pandas
