### ISSUE TITLE
core\common.py:496: ModuleNotFoundError

### ISSUE THREAD

**Issue by dickreuter** [pandas-dev/pandas#24690]
In circumstances that I cannot reproduce in a small code example, I get the following error:

When looking at common.py, it seems that __main__ does indeed not exist. Does anybody know why and under what circumstances this is called?

```

_tcp\work\win-na-x64-release\py3\mre_venv3\lib\site-packages\pandas\core\base.py:61: in __str__

    return self.__unicode__()

_tcp\work\win-na-x64-release\py3\mre_venv3\lib\site-packages\pandas\core\frame.py:659: in __unicode__

    width, _ = console.get_console_size()

_tcp\work\win-na-x64-release\py3\mre_venv3\lib\site-packages\pandas\io\formats\console.py:68: in get_console_size

    if com.in_interactive_session():

_tcp\work\win-na-x64-release\py3\mre_venv3\lib\site-packages\pandas\core\common.py:503: in in_interactive_session

    return check_main()

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

 

    def check_main():

>       import __main__ as main

E       ModuleNotFoundError: No module named '__main__'

 

_tcp\work\win-na-x64-release\py3\mre_venv3\lib\site-packages\pandas\core\common.py:496: ModuleNotFoundError

```

**Comment by dickreuter** [comment]
I’m using pandas 0.23.4, which I think is the latest in anaconda.

**Comment by TomAugspurger** [comment]
Under what circumstances is `__main__` not defined? If necessary, we can
but that import in a `try / except` block.

**Comment by dickreuter** [comment]
In my case I’m running pytest. When I run it individually on the failing test it passes, but then I run it in conjunction with a pylint test, then I get this error.

**Comment by TomAugspurger** [comment]
> but then I run it in conjunction with a pylint test, then I get this
error.

What do you mean by "pylint test"?

Does `__main__` not existing seem strange to anyone else? If it happen as
part of a normal workflow, then
it'd be fine to catch that exception. But it's abnormal, I'd like to not
catch it to avoid hiding a potentially real issue.

**Comment by dickreuter** [comment]
WIth pylint test I mean something like the attached. It's a test that runs pylint. The pandas error occurs in a different test, but it only occurs when this pylint test is active.

![image](https://user-images.githubusercontent.com/1256318/50997678-1e69dd00-151d-11e9-97fd-84ca86c76a03.png)

**Comment by TomAugspurger** [comment]
Thanks for looking. So it's only an issue on Python2?

**Comment by dickreuter** [comment]
No it's python3 in my case
