### ISSUE TITLE
Timezone information lost when slicing a DataFrame column

### ISSUE THREAD

**Issue by Flix6x** [pandas-dev/pandas#24703]
#### Code Sample, a copy-pastable example

```python
from datetime import datetime
from pytz import timezone
from pandas import DataFrame, show_versions

# Initialise timezone-aware data
aware_datetime = timezone(zone="UTC").localize(datetime(2018, 3, 1, 14))
df = DataFrame(data={"A": [aware_datetime]})
# 0   2018-03-01 14:00:00+00:00
# Name: A, dtype: datetime64[ns, UTC]

# Timezone is lost (unexpected behaviour)
print(df["A"].values)
# array(['2018-03-01T14:00:00.000000000'], dtype='datetime64[ns]')
print(df["A"].values[0] == aware_datetime)
# False

# Timezone is kept (expected behaviour)
print(df.values)
# DatetimeIndex(['2018-03-01 14:00:00+00:00'], dtype='datetime64[ns, UTC]', freq=None))
print(df.values[0] == aware_datetime)
# True
```
#### Problem description

Slicing a timezone-aware datetime column from a DataFrame creates a timezone-naive Series. The timezone is lost unexpectedly.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.23.4
pytest: 3.5.1
pip: 10.0.1
setuptools: 39.1.0
Cython: 0.28.2
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: None
psycopg2: 2.7.5 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
NumPy doesn't have a native tz-aware datetime.

In 0.24 we're recommending you avoid `.values` for reasons like this. Use either `.array` to get the underlying array, `.to_numpy()` to convert to M8[ns], and `to_numpy(dtype='object')` to convert to an ndarray of Timestamps, which retains the tz.

```python
In [8]: df.A.array
Out[8]:
<DatetimeArray>
['2018-03-01 14:00:00+00:00']
Length: 1, dtype: datetime64[ns, UTC]

In [9]: df.A.to_numpy()
Out[9]: array([Timestamp('2018-03-01 14:00:00+0000', tz='UTC')], dtype=object)

In [10]: df.A.to_numpy(dtype='object')
Out[10]: array([Timestamp('2018-03-01 14:00:00+0000', tz='UTC')], dtype=object)

```


See http://pandas-docs.github.io/pandas-docs-travis/whatsnew/v0.24.0.html#accessing-the-values-in-a-series-or-index and http://pandas-docs.github.io/pandas-docs-travis/whatsnew/v0.24.0.html#converting-timezone-aware-series-and-index-to-numpy-arrays
