### ISSUE TITLE
Make bracket selection syntax support numpy-like simultaneous row and column choice

### ISSUE THREAD

**Issue by cciccole** [pandas-dev/pandas#24720]
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import pandas as pd

# Consider this Numpy 2D array and the equivalent Pandas dataframe
nmat = np.array([[1,2,3],[4,5,6],[7,8,9]])
pmat = pd.DataFrame(nmat)

# numpy implements simultaneous selection of rows and columns within a single bracket as mat[r,c]
# r and c can be range notations or list-like structures of indices.
nmat[0:2, 0:2] # selects first two rows and first two columns

# trying the same with the Pandas dataframe of gives an error
pmat[0:2,0:2] # TypeError: unhashable type: 'slice'

# the workflow can be accomplished with the desired syntax using iloc()
pmat.iloc[0:2,0:2]

```
#### Problem description
The code sample pretty much says it all, but it would be nice if bracket notation on dataframe was expanded to support simultaneous selection / indexing of rows and columns. This could be a new addition to the current behavior instead of it simply throwing an error.

Having this functionality would be convenient such that code that does simple filtering and selection operations could accept Pandas or Numpy matrix objects and not have to worry about which type it is. As far as I know, there isn't any equivalent syntax/function for these types of basic operations?

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: None
pip: 18.1
setuptools: 40.5.0
Cython: 0.29.2
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.8.3
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by WillAyd** [comment]
Bracket notation is typically reserved for selection by column label. The problem with trying to support something like this generally I think is going to be ambiguity with slices as to whether or not they refer to positions or indexes of particular elements, which would be especially problematic with non-ordered numeric row labels

**Comment by TomAugspurger** [comment]
You can select a range of columns with .iloc.

I don't think we have any appetite for making `__getitem__` more complicated that in already is.

**Comment by WillAyd** [comment]
Yea I don't think this is something we can or want to support so closing as such. Regardless thanks for the input @cciccole !
