### ISSUE TITLE
Doc make.py clean

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#24727]
@jorisvandenbossche @datapythonista currently `_sphinx_build` in `doc/make.py` always calls `clean`. Do you know why that was added?

My doc-build process in https://github.com/pandas-dev/pandas-release assumes that I can do `make.py html` and `make.py latex_forced`.

An option to not clean would be fine by me.

**Comment by jorisvandenbossche** [comment]
It seems to have been added recently in https://github.com/pandas-dev/pandas/pull/24428

@datapythonista was there a technical reason for that PR (for the faster building of single pages) that it was needed?

I would personally prefer to not always clean by default, but an option is fine as well.

**Comment by datapythonista** [comment]
Sorry about that. Yes, I added it. It's not required, but I thought it made more sense to just leave the files that were built in the last run, mainly for the single pages. I had some cases where I wasn't sure what was built and what was already there. But it's perfectly fine to remove it, and call `make.py clean` explicitly, I just didn't think it would be a problem for anyone.
