### ISSUE TITLE
conditionals do not propagate missing data

### ISSUE THREAD

**Issue by seanv507** [pandas-dev/pandas#24722]
#### Code Sample, a copy-pastable example if possible

```python
a=pd.Series([0, 1, np.NaN])
b = a>0
b
```
#### Problem description
The missing value becomes false
```python
0    False
1     True
2    False
dtype: bool
```

I expect missing values to be propagated in a conditional expression.  It should at least be highlighted in the documentation on handling missing data.

#### Expected Output
```python
b.iloc[2] = np.NaN
b
Out[194]: 
0    0.0
1    1.0
2    NaN
dtype: float64
```
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-43-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.23.4
pytest: 4.0.2
pip: 9.0.3
setuptools: 40.6.3
Cython: 0.29
numpy: 1.15.3
scipy: 1.1.0
pyarrow: 0.7.1
xarray: None
IPython: 6.5.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.7.5
pytz: 2014.10
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.6
feather: None
matplotlib: 2.2.2
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.0
bs4: 4.4.1
html5lib: 0.9999999
sqlalchemy: 1.0.14
pymysql: None
psycopg2: 2.7.1 (dt dec pq3 ext lo64)
jinja2: 2.7.3
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by WillAyd** [comment]
This is not a pandas thing as much as how floating point arithmetic is designed. Should be able to find plenty of info out there on it already - here's a good SO post as an example:

https://stackoverflow.com/questions/1565164/what-is-the-rationale-for-all-comparisons-returning-false-for-ieee754-nan-values
