### ISSUE TITLE
read_excel and read_csv doesn't read the entire file (3121/5063 rows)

### ISSUE THREAD

**Issue by HarveySummers** [pandas-dev/pandas#24734]
#### Code Sample, a copy-pastable example if possible

```python
ML_df = pd.read_excel('gex-globalexplorer-ML_df.xlsx',error_bad_lines=False)
ML_df = pd.read_table('gex-globalexplorer-ML_df.csv', error_bad_lines=False)

```

[gex-globalexplorer-ML_df.xlsx](https://github.com/pandas-dev/pandas/files/2753283/gex-globalexplorer-ML_df.xlsx)

[gex-globalexplorer-ML_df.csv.txt](https://github.com/pandas-dev/pandas/files/2753286/gex-globalexplorer-ML_df.csv.txt)

#### Problem description

read_excel and read_csv doesn't read the entire file (3121/5063 rows). 

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: en_US_UTF-8
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.23.4
pytest: 4.0.2
pip: 18.1
setuptools: 40.6.3
Cython: 0.29.2
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.8.2
patsy: 0.5.1
dateutil: 2.6.1
pytz: 2018.7
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.2
openpyxl: 2.5.12
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.2
lxml: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: 0.2.0
fastparquet: None
pandas_gbq: None
pandas_datareader: [None]

</details>

**Comment by gfyoung** [comment]
@HarveySummers : Thanks for reporting this!  Do you mind doing two things here:

* Uploading CSV and XLSX versions of the data?  As it stands, reading this issue is VERY long 🙂 

For CSV, just upload as a `.txt` file.  XLSX is natively [supported](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/).

* Could you explain the error / issue that you're running into when you try to read either file?

**Comment by HarveySummers** [comment]
Done.  There are no error messages, even when error_bad_lines set to true.  

As crazy as it sounds, it seems like its just not reading the file. And I can't explain why. I open the file in Notepad++ and there is 5063 lines, no spurious characters and no iso code issues.. It fails in both read_excel and read_table with both the 'c' and 'python' engines.

I'm truly bifflesnickered on this.

**Comment by gfyoung** [comment]
@HarveySummers : Thanks for doing this!  This might sound a little strange, but Can you confirm that every single line in your CSV has data?  Here's why:

~~~python
from pandas import read_csv
filename = "gex-globalexplorer-ML_df.csv.txt"

for skip_blank_lines in [True, False]:
    print("Skip Blank Lines:", skip_blank_lines)
    df = read_csv(filename, skip_blank_lines=skip_blank_lines)
    print("Row count:", len(df))
    print("Unique values:", df[df.columns[0]].unique(), "\n")
~~~

This outputs:

~~~
Skip Blank Lines: True
Row count: 3121
Unique values: ['Retain' 'Revoke']

Skip Blank Lines: False
Row count: 5062
Unique values: ['Retain' nan 'Revoke']
~~~

Note that one row from your file is allocated to the header, hence the maximum number of rows in your `DataFrame` can be 5062.  However, as you can see, `pandas` believes that you have empty data in approximately 2000 of your lines.

**Comment by WillAyd** [comment]
I believe @gfyoung has pointed out the answer here in that you are most likely looking for `skip_blank_lines=False` based off of your input files and comments.

If that's not the case feel free to reopen

**Comment by HarveySummers** [comment]
@gfyoung Yes, this solved the problem.  Thanks for the help.

I want to dig deeper on this to find out how many blank lined pandas will encounter before deciding that its the end of the file.  Odd that I've never encountered this problem in the 5 years I've been working with pandas and large data files.  Once I figure it out I'll post my findings for others to learn from.

Many thanks for the help and to the entire team for pandas in its support. You folks rock.

**Comment by gfyoung** [comment]
> I want to dig deeper on this to find out how many blank lined pandas will encounter before deciding that its the end of the file.

@HarveySummers : What's actually happening is that `pandas` is reading your entire file, but for any line that it finds to be blank, it's not returning it in the final result.

**Comment by aakhmetz** [comment]
Hello all, 

I have had a quite similar issue recently, but my excel is very short and pandas skip all rows with NAs. I tried to write some parameters, but it did not work. 

The excel file is here: [incdat.xlsx](https://github.com/pandas-dev/pandas/files/3993819/incdat.xlsx)

Specifically, the following code:
```python
pd.read_excel("../../data/incdat.xlsx", na_values="NA", verbose=True)
```
gave only 25 rows:
![Screenshot from 2019-12-23 14-59-29](https://user-images.githubusercontent.com/2173206/71338979-4408be80-2595-11ea-9fe1-df60f9cac1ab.png)

While if I do it with ```openpyxl``` package, everything reads fine:
```python
import openpyxl

workbook = openpyxl.load_workbook("../../data/incdat.xlsx")
ws = workbook.active
data = []
for row in ws.rows:
    data_ = []
    for cell in row:
        data_.append(cell.value)
    data.append(data_)
    
pd.DataFrame(data[1:], columns=data[0])
```
which gives:
![Screenshot from 2019-12-23 14-59-47](https://user-images.githubusercontent.com/2173206/71339015-6ac6f500-2595-11ea-99d9-f2070258f05b.png)

Could you advice me how I can adjust the code for pandas? 

Please excuse me if I miss something which is very obvious. Thank you in advance

**Comment by AbdolvakilFazli** [comment]
Hi, I tried your code, but seems that the row counts in both cases (skip blank line False/True is the same).
My problem is that the df has only 104978 rows while my original csv file has nearly 640000. It just doesn't read the remaining. What should I do?
