### ISSUE TITLE
23 seems to be the new 42: exception if concatenating list of row-multi-indexed DataFrames at index 23

### ISSUE THREAD

**Issue by J4nJ4nsen** [pandas-dev/pandas#24742]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
In[63]: type(lab.values)
Out[64]: list

In[65]: len(lab.values)
Out[66]: 56

In[67]: pd.concat([lab.values[i].head(1) for i in range(22)])
Out[68]: 
               R                        ...                                                                   geometry
1+e  #                                  ...                                                                           
4.00 0  182033.0                        ...                          (LINESTRING (444893.6045354116 5669896.7770191...
1.25 0  171259.0                        ...                          (LINESTRING (444893.6045354116 5669896.7770191...
1.14 0  175412.0                        ...                          (LINESTRING (444893.6045354116 5669896.7770191...
1.08 0  168703.0                        ...                          (LINESTRING (444893.6045354116 5669896.7770191...
1.10 0  177851.0                        ...                          (LINESTRING (444893.6045354116 5669896.7770191...
1.12 0  170799.0                        ...                          (LINESTRING (444893.6045354116 5669896.7770191...
2.20 0  182468.0                        ...                          (LINESTRING (444893.6045354116 5669896.7770191...
1.20 0  183579.0                        ...                          (LINESTRING (444893.6045354116 5669896.7770191...
1.09 0  171523.0                        ...                          (LINESTRING (444893.6045354116 5669896.7770191...
1.80 0  187341.0                        ...                          (LINESTRING (444893.6045354116 ...
... (shortened output)
[22 rows x 6 columns]

In[69]: pd.concat([lab.values[i].head(1) for i in range(23)])
Traceback (most recent call last):
  File "/home/jan/miniconda/envs/stable/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-67-8d7a714156ca>", line 1, in <module>
    pd.concat([lab.values[i].head(1) for i in range(23)])
  File "/home/jan/miniconda/envs/stable/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 229, in concat
    return op.get_result()
  File "/home/jan/miniconda/envs/stable/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 420, in get_result
    indexers[ax] = obj_labels.reindex(new_labels)[1]
  File "/home/jan/miniconda/envs/stable/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 2236, in reindex
    target = MultiIndex.from_tuples(target)
  File "/home/jan/miniconda/envs/stable/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 396, in from_tuples
    arrays = list(lib.tuples_to_object_array(tuples).T)
  File "pandas/_libs/lib.pyx", line 2274, in pandas._libs.lib.tuples_to_object_array
TypeError: Expected tuple, got str

In[70]: lab.values[22].head(1)
Out[70]: 
             swa                        ...                                                                           
               R                        ...                                                                   geometry
1+e  #                                  ...                                                                           
1.02 0  166588.0                        ...                          (LINESTRING (444893.6045354116 5669896.7770191...
[1 rows x 6 columns]

```
#### Problem description

The pd.concat method don't throws exception for this the last year, all was good. Now it complains exactly at position 23 in the list, but all entrys have the same structure of a dataframe.

With Version 0.23.4 the above commands still worked, the output for the last command in the code above just prints the dataframe.

Extremely strange behaviour that with computation of entry 23 (so index 22) throws this exception, and below all is ok.
Since its not even a potential of 2, there must be some wrong typed numbers in some math evaluation or some other non-structural, rather latent error.

#### Expected Output
(trivial) ...concatenated DataFrame like the first outputs in code above!
#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-43-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
pandas: 0.24.0rc1
pytest: 4.1.0
pip: 18.1
setuptools: 40.6.3
Cython: 0.29.2
numpy: 1.15.4
scipy: 1.2.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: None
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: 1.2.1
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: 1.2.0
xlwt: None
xlsxwriter: None
lxml.etree: 4.2.5
bs4: None
html5lib: None
sqlalchemy: 1.2.15
pymysql: None
psycopg2: 2.7.6.1 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by J4nJ4nsen** [comment]
if you mean a atomic example with arbitrary, e.g. random data, i won't get the time to do the next few weeks. But i can post the part of the data for which this error arised as attachement if needed?

Otherwise i will surely try digging deeper inside the end of february if this error is still present at this time.
Thank you for your immediate reply anyway...

**Comment by WillAyd** [comment]
Closing for now. @J4nJ4nsen ping to reopen if you can provide the self contained example as requested above
