### ISSUE TITLE
CategoricalAccessor.categorical removed in 0.24.0rc1

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#24751]
Previously, CategoricalAccessor set `.categorical` in `__init__`. I don't think this was intended to be the way to access things like `.ordered`, but it wasn't prefixed with an underscore, so we should deprecate before removing

0.23.4

```python
In [11]: pd.Series(['a', 'b'], dtype='category').cat.categorical.ordered
Out[11]: False
```

0.24.0rc1

```python
In [3]: pd.Series(['a', 'b'], dtype='category').cat.categorical.ordered
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-e5c7f0300480> in <module>
----> 1 pd.Series(['a', 'b'], dtype='category').cat.categorical.ordered

AttributeError: 'CategoricalAccessor' object has no attribute 'categorical'
```

We can deprecate with

```python
def categorical(self):
    warnings.warn(...)
    return self._parent
```

in https://github.com/pandas-dev/pandas/blob/33f91d8f9f2e84f2b5f3ac3f0481b691c977c427/pandas/core/arrays/categorical.py#L2472

We should do the same for `.index` and `.name`.

**Comment by benjaminr** [comment]
Will take a look at this one.

**Comment by TomAugspurger** [comment]
It wasn't prefixed with an underscore.

**Comment by jreback** [comment]
> It wasn't prefixed with an underscore.

lots of things are not prefixed with underscored. ``.categoricals`` is not a valid construction, nor was this ever advertised / documented. This is taking deprecations too far.

**Comment by TomAugspurger** [comment]
We made a mistake and the data was made public. We need a deprecation.


________________________________

**Comment by jreback** [comment]
@TomAugspurger not convinced, we have*many* places where you can access attributes; and we have changed any of these. This is a very very minor case. I don't think the deprecation is worth it.

**Comment by TomAugspurger** [comment]
I think it is.


________________________________

**Comment by jorisvandenbossche** [comment]
It is very simple to deprecate it (it's not adding complexity to the non-deprecated code), so let's just do it. 

@benjaminr can you re-open your PR?

**Comment by benjaminr** [comment]
@jorisvandenbossche sure thing 👍
