### ISSUE TITLE
CI: azure failing

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#24755]
https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=6880

```
doc/source/comparison_with_sas.rst(754,-22): error F821: undefined name 'get_ipython'
Bash exited with code '1'.
```

**Comment by jreback** [comment]
azure seems to be failing on master, with the above. not sure where its coming from.

cc @datapythonista

**Comment by datapythonista** [comment]
Let me take a look.

**Comment by datapythonista** [comment]
Seems like a problem in the latest release of `flak8-rst`. It's been reported an internal error of `flake8-rst` as if it was in our documentation.

@FHaase should I create an issue in `flake8-rst` or can you take a look?

Opened #24756
