### ISSUE TITLE
DataFrame.mean includes datetime64[ns] dtypes in 0.24.0rc1

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#24752]
I think this isn't deliberate.

```python
# 0.23.4
In [1]: import pandas as pd

In [2]: pd.DataFrame({"A": pd.date_range('2000', periods=12)}).mean()
Out[2]: Series([], dtype: float64)
```

```python
# 0.24.0rc1
In [2]: pd.DataFrame({"A": pd.date_range('2000', periods=12)}).mean()
Out[2]:
A   2124-07-04 18:21:24.687506176
dtype: datetime64[ns]
```

We continue to raise on `Series[datetime64[ns]].mean()`

**Comment by jreback** [comment]
hmm i think we did enable this recently

**Comment by jbrockmendel** [comment]
> I think this isn't deliberate.

Certainly returning a nonsense answer isn't deliberate.  IIRC we made nanops.nanmean accept datetime64[ns] but didn't yet enable it in the Index/EA subclasses.

I've got a couple of branches implementing reductions; I'll rebase and see if any of them are near ready.

**Comment by jbrockmendel** [comment]
The weird result is happening in DataFrame._reduce when `nanops.nanmean` is called on `df.values`:

```
>>> nanops.nanmean(self.values, axis=0)
array(['2124-07-04T18:21:24.687506176'], dtype='datetime64[ns]')
```

If we weren't passing axis=0, we would get a more reasonable-looking:

```
>>> nanops.nanmean(self.values, axis=None)
Timestamp('2000-01-06 12:00:00')
```

**Comment by jreback** [comment]
this didn't work correctly before, so its not a blocker

**Comment by jorisvandenbossche** [comment]
It did work correctly before:

```
In [17]: pd.__version__
Out[17]: '0.23.4'

In [18]: pd.DataFrame({'a': [1, 2, 3], 'b': pd.date_range('2000', periods=3)}).mean()
Out[18]: 
a    2.0
dtype: float64
```

vs

```
In [29]: pd.__version__                                                                                                                                                                                             
Out[29]: '0.24.0rc1+58.gc588437f1.dirty'

In [30]: pd.DataFrame({'a': [1, 2, 3], 'b': pd.date_range('2000', periods=3)}).mean()                                                                                                                               
Out[30]: 
a                      2
b    2000-01-02 00:00:00
dtype: object
```

This is a clear change in behaviour. Or did we change the meaning of `numeric_only` ?

**Comment by jreback** [comment]
yes it’s likely that it’s now picking this up as a numeric column (which is incorrect);
we did not support mean of a date time colum previously

**Comment by jreback** [comment]
not currently, we don't have an implementation (yet), there is a PR by @jbrockmendel. I suppose we could just merge that and this would work.

**Comment by jorisvandenbossche** [comment]
According to the comment there (https://github.com/pandas-dev/pandas/pull/24757#issuecomment-454152059), that does not close this issue (but not sure if that is up to date).

To me, the question still is in general whether datetimes should be considered as "numeric". We didn't do that in the past.

**Comment by TomAugspurger** [comment]
This is fuzzy enough that I'd prefer to not change the default behavior.

**Comment by jorisvandenbossche** [comment]
The docstring is saying this:

```
numeric_only : bool, default None
    Include only float, int, boolean columns. If None, will attempt to use
    everything, then use only numeric data. Not implemented for Series.
```

So before: it tried and failed on all columns, so did `numeric_only=True` in practice. Now it does not fail anymore on datetimes, so includes them. 
So in some sense you could say this is consistent with the description, but it is for sure a change in behaviour.

**Comment by TomAugspurger** [comment]
Taking a look now.

**Comment by jorisvandenbossche** [comment]
Do you know where this mean is calculated for M8 under the hood. What tests would fail if we just raise an error there?

**Comment by TomAugspurger** [comment]
See https://github.com/pandas-dev/pandas/pull/24907.

**Comment by jorisvandenbossche** [comment]
Ah, so exactly what you did :-)

I am +1 on that, to disable mean for datetime again. At least for now, we can re-evaluate when we have more time.
