### ISSUE TITLE
python-project-packaging-with-pandas

### ISSUE THREAD

**Issue by harshitgoyal** [pandas-dev/pandas#24779]
#### Problem description
I have created a Spark project in Python in which I am using the module pandas and packaged the spark project using wheel as per the these steps: -
>pip wheel -r requirements.txt -w dist
it will create 'wheel' files for all explicit and implicit dependencies from our 'requirement.txt' file and put them into 'dist' directory.
To build our project artifacts.
>python setup.py bdist_wheel
This will create another 'wheel' (zip file underneath) in 'dist' directory with our application files. Renamed our 'wheel' files as zip files and provide them to '--py-files' option to submit the spark job.
This is spark submit command I am submitting to execute my job.
>spark-submit --py-files certifi-2018.11.29-py2.py3-none-any.zip,findspark-1.3.0-py2.py3-none-any.zip,idna-2.8-py2.py3-none-any.zip,kafka-1.3.5-py2.py3-none-any.zip,Logr-0.2.2-cp27-none-any.zip,mysql_connector-2.1.6-cp27-cp27mu-linux_x86_64.zip,panda-0.3.1-cp27-none-any.zip,py4j-0.10.7-py2.py3-none-any.zip,python_dateutil-2.7.5-py2.py3-none-any.zip,pytz-2018.7-py2.py3-none-any.zip,req-1.0.0-py2.py3-none-any.zip,requests-2.21.0-py2.py3-none-any.zip,setuptools-40.6.3-py2.py3-none-any.zip,six-1.12.0-py2.py3-none-any.zip,urllib3-1.24.1-py2.py3-none-any.zip,zope.interface-4.6.0-cp27-cp27mu-manylinux1_x86_64.zip,configparser-3.5.0-py2-none-any.zip,pandas-0.23.4-cp27-cp27mu-manylinux1_x86_64.zip,numpy-1.15.4-cp27-cp27mu-manylinux1_x86_64.zip,test_spark_submit-0.1.zip  driver.py test_spark_submit.subfolder.spark_script parameter_to_pass_to_module
Issue is when we fire this command it is failing with error while all other module dependencies are working fine (like kafka, findspark and etc.). 
It seems pandas is dependent on numpy and even numpy(numpy-1.15.4-cp27-cp27mu-manylinux1_x86_64.zip) is given in command but still it is not referring this.

> File "/home/harry/pandas-0.23.4-cp27-cp27mu-manylinux1_x86_64.zip/pandas/__init__.py", line 19, in <module>
ImportError: Missing required dependencies ['numpy']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/harry/DataIngestionTool_dist/driver.py", line 44, in <module>
    raise Exception("Exception::Job %s failed with msg %s" %(args.job_name, str(e)))
Exception: Exception::Job dataIngestionTool.dataPrepartion.dataIngestion failed with msg Missing required dependencies ['numpy']
 
####
* I want to package in this way as I can manage all the dependencies effectively.
Please help me to resolve this issue.

#### Could you please check on pandas/__init__.py", line 19,  why module is null.

**Comment by harshitgoyal** [comment]
Or may be another way to package the project/application where we can manage the all dependent modules effectively. 

Thanks in advance.  :)

**Comment by WillAyd** [comment]
Not sure I fully understand the issue but admittedly not familiar with Spark either. What makes you think this issue is with pandas and not Spark?

**Comment by harshitgoyal** [comment]
> Not sure I fully understand the issue but admittedly not familiar with Spark either. What makes you think this issue is with pandas and not Spark?
This is the Spark documentation is saying "Spark 2.3.0 works with Python 2.7+ or Python 3.4+. It can use the standard CPython interpreter, so C libraries like NumPy can be used. It also works with PyPy 2.3+."
I have written the python code to submit the spark job using spark-submit. In code I have used the pandas lib. but the code is failing in python and hence it seems a pandas issues.
if you want to replicate it , I can share the more details.


> It looks like it is complaining about numpy being missing? Is that not installed?
pandas internally uses numpy and the error show that the error is in pandas/init.py", line 19.
File "/home/harry/pandas-0.23.4-cp27-cp27mu-manylinux1_x86_64.zip/pandas/init.py", line 19, in 
ImportError: Missing required dependencies ['numpy'] 
Also while submitting the spark-submit command in --py-files numpy dependency is given.

**Comment by WillAyd** [comment]
If you removed pandas from your application and just tried to package numpy do you get the same error? I actually ran into a similar issue yesterday with PyInstaller which I traced back to this:

https://github.com/pyinstaller/pyinstaller/issues/3982

I see you have Numpy 1.15.4 and the issue says 1.16 but I am even seeing it with 1.15.3 in a virtual environment, so same issue may apply

**Comment by mroeschke** [comment]
Not sure if there's any action to be done on pandas' side. Closing.
