### ISSUE TITLE
Drop Duplicates Subset - Doesn't check if column exists

### ISSUE THREAD

**Issue by aditsanghvi94** [pandas-dev/pandas#24785]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame()
df['Person Name'] = [1,2,3,4,5,6,7,8]
df['ID'] = [1,1,1,1,1,1,1,1]
df.drop_duplicates(['ID','PersonName'])
```
#### Problem description
When we provide a subset of columns to pandas drop duplicates, it only requires *1* of those columns to exist in the dataframe. 
If the other columns don't exist, it will just perform the drop considering only duplicates on the columns that do exist.
This can be a major issue when there is a typo in one of the column names - "Person Name" vs "PersonName". 
The output from the above command is just one row, where it should throw an error

#### Output
	Person Name	ID
	1	        1

#### Expected Output
ValueError : Column "PersonName" does not exist

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Linux
OS-release: 4.12.10-coreos
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.22.0
pytest: None
pip: 9.0.1
setuptools: 38.5.1
Cython: 0.29
numpy: 1.14.1
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 5.5.0
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.1.2
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.9999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by TomAugspurger** [comment]
This raises now (with a KeyError, which I think is appropriate). I don't recall whether it was added in 0.23 or 0.24
