### ISSUE TITLE
Bug: plot.bar() plots very incorrect values for some rows

### ISSUE THREAD

**Issue by phdoerfler** [pandas-dev/pandas#24790]
#### Code Sample, a copy-pastable example if possible

```python
js = '{"sym7":2.1686229706,"sym6":2.1717643738,"sym8":2.1743240356,"sym11":2.1787643433,"sym10":2.193561554,"sym4":2.1955757141,"sym14":2.2099514008,"sym13":2.2126140594,"sym16":2.2139530182,"sym9":2.2200069427,"sym5":2.2284069061,"sym17":2.2318115234,"sym20":2.2440624237,"sym3":2.2460422516,"rbio6.8":2.2678699493,"bior2.6":2.3199291229,"rbio5.5":2.3794841766,"sym2":2.3801040649,"rbio4.4":2.3808612823,"db16":2.4352874756,"sym19":2.4434349537,"db8":2.4964580536,"bior2.4":2.4989709854,"bior5.5":2.5395958424,"coif9":2.5409469604,"bior4.4":2.5421423912,"bior6.8":2.5627846718,"coif6":2.6053543091,"bior2.8":2.6874725819,"rbio2.8":2.7051467896,"sym18":2.7677249908,"bior2.2":2.7736589909,"bior3.9":2.7752864361,"bior3.7":2.7995326519,"sym15":2.8378477097,"bior3.3":2.8417224884,"sym12":2.940946579,"db27":2.9858455658,"rbio2.4":3.0840065479,"db29":3.1267776489,"db36":3.1449165344,"bior3.5":3.2562236786,"haar":3.3101139069,"bior1.3":3.3731975555,"rbio2.6":3.3877735138,"bior3.1":3.4522609711,"bior1.5":3.4605770111,"bior1.1":3.5266208649,"coif10":3.7042503357,"db11":3.7277202606,"db17":3.8645591736,"db24":3.886182785,"db34":4.0353851318,"db33":4.082701683,"rbio3.9":4.0892801285,"rbio2.2":4.6584186554,"db28":4.8967075348,"rbio3.7":4.9149179459,"rbio3.5":5.3063430786}'
seb = pd.read_json(js, typ='series')
seb.plot.bar()
plt.tight_layout()
plt.show()
```
#### Problem description

Resulting image:
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/163428/51213518-7ccafd00-191b-11e9-913a-ad8eb686f93d.png">

The values in the series `seb` are sorted:

<details>
<pre>
sym7       2.168623
sym6       2.171764
sym8       2.174324
sym11      2.178764
sym10      2.193562
sym4       2.195576
sym14      2.209951
sym13      2.212614
sym16      2.213953
sym9       2.220007
sym5       2.228407
sym17      2.231812
sym20      2.244062
sym3       2.246042
rbio6.8    2.267870
bior2.6    2.319929
rbio5.5    2.379484
sym2       2.380104
rbio4.4    2.380861
db16       2.435287
sym19      2.443435
db8        2.496458
bior2.4    2.498971
bior5.5    2.539596
coif9      2.540947
bior4.4    2.542142
bior6.8    2.562785
coif6      2.605354
bior2.8    2.687473
rbio2.8    2.705147
sym18      2.767725
bior2.2    2.773659
bior3.9    2.775286
bior3.7    2.799533
sym15      2.837848
bior3.3    2.841722
sym12      2.940947
db27       2.985846
rbio2.4    3.084007
db29       3.126778
db36       3.144917
bior3.5    3.256224
haar       3.310114
bior1.3    3.373198
rbio2.6    3.387774
bior3.1    3.452261
bior1.5    3.460577
bior1.1    3.526621
coif10     3.704250
db11       3.727720
db17       3.864559
db24       3.886183
db34       4.035385
db33       4.082702
rbio3.9    4.089280
rbio2.2    4.658419
db28       4.896708
rbio3.7    4.914918
rbio3.5    5.306343
dtype: float64
</pre>
</details>

#### Expected Output

I expect the bar plot to not have wrong values plotted.
The series is sorted, however the bar plot clearly is not.
In the series the largest value is 5.3 but the bar plot suggests there exist values around 7.
The first apparent deviation from the series occurs with `sym3` which has a value of 2.246042 but is plotted with a value of about 2.5.
It gets worse from thereon with the worst offender being `coif9` with a value of 2.540947 that is plotted with a value of about 7.
After this, starting with `bior4.4` the bar plot is rendered with more sensible values.

#### Output of ``pd.show_versions()``

<details>
<pre>
pd.show_versions()
None
Python 3.7.0 (default, Jun 28 2018, 07:39:16) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 7.2.0
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8<br />
pandas: 0.23.4
pytest: 4.0.1
pip: 18.1
setuptools: 40.6.2
Cython: 0.29
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</pre>
</details>

**Comment by TomAugspurger** [comment]
Can you try on master / 0.24.0rc1 and see if it's still an issue? I get a different output from you.

**Comment by phdoerfler** [comment]
I can try, I never built a package with anaconda. Does pandas have a [conda build recipe](https://conda.io/docs/user-guide/tasks/build-packages/recipe.html)?

**Comment by TomAugspurger** [comment]
There's a release candidate out now, so you don't have to build. `conda
install -c conda-forge/label/rc pandas>=0.24.0`

**Comment by phdoerfler** [comment]
Thanks! That's even better. Let me get right to it.

**Comment by phdoerfler** [comment]
With a slight change to your cmd line I installed the RC:

```
conda install -c conda-forge/label/rc 'pandas=0.24.*'
```

<details><pre>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8<br/>
pandas: 0.24.0rc1
pytest: 4.0.1
pip: 18.1
setuptools: 40.6.2
Cython: 0.29
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None</pre></details>

and sure enough I now get a different output, too:

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/163428/51221719-f58d8180-193a-11e9-852b-f2673ae72a0a.png">

Though really it's the same thing in ~~green~~ blue.

**Comment by phdoerfler** [comment]
I run this through VS Code. This is how it's started:

```
cd /Users/phi/Documents/workspace/FAUGitlab/spiht ; env "PYTHONPATH=src/python:src/test/python:src/main/cython:target/cython" "PYTHONFAULTHANDLER=Yeah" "PYTHONIOENCODING=UTF-8" "PYTHONUNBUFFERED=1" /usr/local/miniconda3/envs/spiht_pandas_rc/bin/pythonw /Users/phi/.vscode/extensions/ms-python.python-2018.12.1/pythonFiles/ptvsd_launcher.py --default --nodebug --client --host localhost --port 62059 /Users/phi/Documents/workspace/FAUGitlab/spiht/src/evaluation/stats.py
```

I'll try tomorrow whether starting it with pythonw from the cmdline outside of VS code has any effect.

**Comment by phdoerfler** [comment]
Nope, the behaviour is still the same even if I start it like this:

```
(spiht_pandas_rc)  spiht (master) $ env "PYTHONPATH=src/python:src/test/python:src/main/cython:target/cython" "PYTHONFAULTHANDLER=Yeah" "PYTHONIOENCODING=UTF-8" "PYTHONUNBUFFERED=1" pythonw /Users/phi/Documents/workspace/FAUGitlab/spiht/src/evaluation/stats.py
```

**Comment by TomAugspurger** [comment]
Strange. It's a bit of a long shot, but could you try upgrading your python to the next point release (3.7.2 is out now). IIRC 3.7.0 had some issues around float parsing, but I don't recall details right now.

**Comment by phdoerfler** [comment]
Turns out it was a layer 8 error, mea culpa.
An earlier line of code:

```
se[:,:,:,'ACA',:].groupby('Photo').min().mode().plot.bar()
```

**without** an accompanying `plt.show()` caused this.
