### ISSUE TITLE
Aggregate on multiple columns with one attribute at the agg function

### ISSUE THREAD

**Issue by PoeteMaudit** [pandas-dev/pandas#24801]
See here please: https://stackoverflow.com/questions/54217753/aggregate-on-multiple-columns-with-one-attribute-at-the-agg-function.

**Comment by TomAugspurger** [comment]
Can you fill out the requested info, rather than linking to SO (in case that question is deleted)?

**Comment by TomAugspurger** [comment]
FYI: The keys in a dictionary have to be hashable.

No I don't think it's possible to apply an aggregation to a subset like that. It's probably easiest to generate the dict of aggfuncs if you're worried about typing them all out.

**Comment by PoeteMaudit** [comment]
Yes, I know. I edited the post. It was just an example to show what I meant.
