### ISSUE TITLE
Adding native support to query azure data explorer

### ISSUE THREAD

**Issue by toshetah** [pandas-dev/pandas#24818]
Hello,

My name is Tomer, and I am a developer working at Microsoft.
I am part of [Azure Data Explorer](https://azure.microsoft.com/en-us/services/data-explorer/), and maintaining our [python packages](https://github.com/Azure/azure-kusto-python).
We have many customers that are using pandas, and we were thinking of how to ease their usage.
We would like to expose/contribute something similar to the following:

import pandas as pd
pd.read_azure_data_explorer("query", con=connection_string)

I think that adding the ability to read Azure Data Explorer directly into pandas could potentially help many of our customers who are accustomed to pandas.
I would like to hear what do you guys think about that.

Thanks,
Tomer

**Comment by jschendel** [comment]
I suspect this would be more appropriate as a separate package, similar to [`pandas-gbq`](https://pandas-gbq.readthedocs.io/en/latest/) (xref #15347).  Then, if we were to add this as a top-level `pd.read_azure_data_explorer`, it would just be implemented as a wrapper around the package, e.g. [`io/gbq.py`](https://github.com/pandas-dev/pandas/blob/master/pandas/io/gbq.py).

**Comment by TomAugspurger** [comment]
Mostly agreed with @jschendel. Functionality-wise, I don't think it makes a
difference whether this is implemented in
pandas vs. a third-party package.

Given that the azure data explorer team are better-equipped to develop and
maintain the functionality, so I'd lean towards doing
it as a third-party package.

As far as promotion / informing people about this functionality, I'd
suggest starting with adding it to the "pandas ecosystem" page in
the pandas docs.

**Comment by WillAyd** [comment]
Thanks for the request! I'd also lean towards this being in a separate package and given the other feedback I am going to close this. 

If you end up building the package let us know and can point to it from the ecosystem docs. Can certainly reach out with questions as well on the mailing list or Gitter
