### ISSUE TITLE
pandas EWMA documentation possible error

### ISSUE THREAD

**Issue by jamesoliverh** [pandas-dev/pandas#24814]
I believe there might be an error in the documentation for the pandas EWM method at 

http://pandas.pydata.org/pandas-docs/stable/user_guide/computation.html#exponentially-weighted-windows

in particular, in the following line:

> When adjust=True we have y0=x0 and from the last representation above we have yt=αxt+(1−α)yt−1, therefore there is an assumption that x0 is not an ordinary value but rather an exponentially weighted moment of the infinite series up to that point.

shouldn't "adjust=True" be replaced with "adjust=False"? 

cf. the discussion here:
https://github.com/pandas-dev/pandas/issues/8861.

I might be wrong, in which case apologies. Thanks for your help.

**Comment by wuliang727** [comment]
I'm also confused about the name "adjust". I would suggest using the default which "adjust=True", since it is basically the same as my textbook: https://otexts.com/fpp2/ses.html (Section 7.1, Simple exponential smoothing).

**Comment by xgdgsc** [comment]
And the link to detail should be http://pandas.pydata.org/pandas-docs/stable/user_guide/computation.html#exponentially-weighted-windows instead.

**Comment by jamesohamp** [comment]
> And the link to detail should be http://pandas.pydata.org/pandas-docs/stable/user_guide/computation.html#exponentially-weighted-windows instead.

@xgdgsc Thank you, duly edited

**Comment by jamesoliverh** [comment]
Proposed correction (and minor clarifications) to EWMA documentation, pull request here: https://github.com/pandas-dev/pandas/pull/26422.
Comments and/or suggestions welcome.
