### ISSUE TITLE
Question regarding Series.argsort documentation

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#24816]
`Series.argsort` has three arguments, `axis`, `kind` and `order`, but only `kind` is actually used.  Should the other two be removed from the documentation? (I'm guessing they were once used and are left in the code for compatibility reasons?)

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.argsort.html

**Comment by TomAugspurger** [comment]
I believe axis and order are needed to match the signature of `np.argsort`,
which dispatches to objects with a `.argsort` method,

**Comment by benjaminr** [comment]
Happy to look at updating the documentation to reflect his.
