### ISSUE TITLE
TST: test_constructors.py::TestSeriesConstructors::test_constructor_dtype_datetime64

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#24827]
xref https://github.com/pandas-dev/pandas/pull/24812#discussion_r248656502. follow-up PR required.

**Comment by charlesdong1991** [comment]
shouldn't it then raise a TypeError?

**Comment by gfyoung** [comment]
@charlesdong1991 : It looks the correct error is raised, but the message is not quite right.

**Comment by charlesdong1991** [comment]
yeah, will take a closer look
