### ISSUE TITLE
pandas.Series.ne Documentation has Series.add as example

### ISSUE THREAD

**Issue by Ishkatan** [pandas-dev/pandas#24824]
#### Code Sample, a copy-pastable example if possible
```python
# Your code here
Wrong example in:
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.ne.html#pandas.Series.ne
and  pandas.Series.le 
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.le.html

```
#### Problem description

The documentation for pandas.Series.ne and le uses pandas.Series.add as an example.  Shouldn't it be something using a.ne or a.le ?

#### Output of ``pd.show_versions()``

<details>
Example is:

>>> a.add(b, fill_value=0)
a    2.0
b    1.0
c    1.0
d    1.0
e    NaN
dtype: float64

</details>

**Comment by mroeschke** [comment]
Essentially a dup of https://github.com/pandas-dev/pandas/issues/24589. An example for `add` is essentially hardcoded for all these ops, but specific examples certainly welcome to improve the documentation for each method,
