### ISSUE TITLE
Concatenating unordered CategoricalIndex overrides indices

### ISSUE THREAD

**Issue by HagaiHargil** [pandas-dev/pandas#24845]
A very similar bug to #20425, but with `CategoricalIndex` instead of `Categorical`:

#### Code Sample

```python
cat1 = pd.CategoricalIndex(
    ["a", "a",],
    categories=["a", "b"],
    ordered=False)
cat2 = pd.CategoricalIndex(
    ["b", "b"],
    categories=["b", "a"],
    ordered=False)

df1 = pd.DataFrame({"A": [1, 2]}, index=cat1)
df2 = pd.DataFrame({"A": [3, 4]}, index=cat2)
print(pd.concat((df1, df2)))  # cat2 disappeared from index
#    A
# a  1
# a  2
# a  3
# a  4
```
#### Problem description

When the indices are unordered, a concatenation operation may yield wrong indices for the resulting DataFrame. If `cat2`'s categories were `["a", "b"]` the concatenation operation would've been successful.

#### Expected Output
```python
cat3 = pd.CategoricalIndex(
    ["a", "a", "b", "b"], 
    categories=["a", "b"], 
    ordered=False)
print(pd.DataFrame({"A": [1, 2, 3, 4]}, index=cat3))
#    A
# a  1
# a  2
# b  3
# b  4
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Linux
OS-release: 4.18.0-13-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 3.8.1
pip: 18.1
setuptools: 40.2.0
Cython: 0.28.5
numpy: 1.15.4
scipy: 1.2.0
pyarrow: None
xarray: 0.11.0
IPython: 7.0.1
sphinx: 1.8.1
patsy: 0.5.1
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by mukundm19** [comment]
Is someone working on this issue? If not I would like to look into this.
