### ISSUE TITLE
"ValueError: num must be 1 <= num <= 0, not 1" when trying to plot a histogram of datetimes

### ISSUE THREAD

**Issue by khpeek** [pandas-dev/pandas#24857]
#### Code Sample, a copy-pastable example if possible

```python
import random
import dateutil.parser
import pandas as pd
import matplotlib.pyplot as plt

start = dateutil.parser.parse("1 January 2019")
end = dateutil.parser.parse("3 January 2019")

data = [start + (end - start) * random.random() for _ in range(100)]

df = pd.DataFrame(data, columns=['Time'])

hist = df.hist(column='Time')

# df['Time'].hist()

plt.show()

```
#### Problem description

When I try to run the code snippet above, I get the following error message:

```
$ python3 pandas_histogram.py
Traceback (most recent call last):
  File "pandas_histogram.py", line 13, in <module>
    hist = df.hist(column='Time')
  File "/usr/local/lib/python3.7/site-packages/pandas/plotting/_core.py", line 2408, in hist_frame
    layout=layout)
  File "/usr/local/lib/python3.7/site-packages/pandas/plotting/_tools.py", line 238, in _subplots
    ax0 = fig.add_subplot(nrows, ncols, 1, **subplot_kw)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/figure.py", line 1367, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axes/_subplots.py", line 60, in __init__
    ).format(maxn=rows*cols, num=num))
ValueError: num must be 1 <= num <= 0, not 1
```

#### Expected Output
If I run `df['Time'].hist()` instead (the commented-out line in the snippet), it works fine and I see a histogram:

![image](https://user-images.githubusercontent.com/6617594/51455849-4ec13080-1d00-11e9-9fad-250a953fbe14.png)

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
In [2]: pd.show_versions()                                                                     

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1.final.0
python-bits: 64
OS: Darwin
OS-release: 17.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 4.0.2
pip: 18.1
setuptools: 40.5.0
Cython: None
numpy: 1.16.0
scipy: None
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by nd7141** [comment]
Same issue.

**Comment by ijmiller2** [comment]
Was getting a similar error. Recasting the data as with `df.astype('float64')` solved my problem. Even though each row entry seemed to be recognized as a float, the column was being treated as type "object." Probably because of how I built the data frame.

**Comment by mroeschke** [comment]
This might have been fixed on master in the meantime. If you're still having issues with the latest version of pandas, feel free to reopen.
