### ISSUE TITLE
ExtensionDtype.construct_array_type is not optional

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#24860]
Currently, the `ExtensionDtype` docstring says:

```
Optionally one can override construct_array_type for construction
with the name of this dtype via the Registry. See
:meth:`pandas.api.extensions.register_extension_dtype`.

* construct_array_type
```

However, it seems that in practice this is  used for more than just supporting string dtypes. Eg I also need to implement it to have `groupby` working.

Eg cyberpandas does not yet implement it, and there ``df.groupby('ipaddresses').size()`` fails with a NotImplementedError.

I assume we are fine with requiring this (assuming a 1-1 mapping of dtype and array), and a doc update is enough?

**Comment by jbrockmendel** [comment]
I see the usefulness here, but there is a non-trivial downside that this prevents core.dtypes from being self-contained (w/r/t the rest of core).

**Comment by jorisvandenbossche** [comment]
And I suppose changing the implementation from NotImplementedError to AbstractMethodError ?
