### ISSUE TITLE
IntervalArray not documented in What's New for 0.24.0rc1

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#24870]
#### Problem description

The new type `IntervalArray` is in the API reference, but is not mentioned in What's New in the docs for v0.24.0rc1 .  The existence of the new type is probably something people would like to know about.

http://pandas.pydata.org/pandas-docs/version/0.24.0rc1/api/arrays.html#interval-data has it listed there, but in http://pandas.pydata.org/pandas-docs/version/0.24.0rc1/whatsnew/v0.24.0.html it appears in an example, and that there is a new method for the type.

Not sure if @TomAugspurger or @jschendel should look at that.

**Comment by TomAugspurger** [comment]
IMO, the most important thing is that interval data can be stored in Series, which is covered by http://pandas.pydata.org/pandas-docs/version/0.24.0rc1/whatsnew/v0.24.0.html#storing-interval-and-period-data-in-series-and-dataframe.

**Comment by jschendel** [comment]
At the very least it might be nice to reword things slightly to explicitly mention `IntervalArray` (and `PeriodArray`) and include links to the api reference in the section mentioned by @TomAugspurger above.

**Comment by TomAugspurger** [comment]
Yeah noting IntervalArray and PeriodArray in that section would be an improvement.
