### ISSUE TITLE
Adding a column via `assign` or `__setitem__` on an empty DataFrame changes index type, removes index name

### ISSUE THREAD

**Issue by p-himik** [pandas-dev/pandas#24878]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

d = pd.DataFrame(dict(a=[]), index=pd.Series([], name='my_index'))
d2 = d.assign(b=[])

d.index
# Float64Index([], dtype='float64', name='my_index')

d2.index
# RangeIndex(start=0, stop=0, step=1)

d['b'] = []
d.index
# RangeIndex(start=0, stop=0, step=1)
```
#### Problem description
I don't think that adding a new column to a DataFrame should change index in any way, let alone change its type and remove its name. It doesn't matter if there's no actual data - it still forces the user to write special checks.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1.final.0
python-bits: 64
OS: Linux
OS-release: 4.18.0-13-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: None
pip: 18.1
setuptools: 40.6.3
Cython: None
numpy: 1.15.4
scipy: None
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
The bug in is in `DataFrame.__setitem__`, not assign.

```python
In [23]: df = pd.DataFrame({'a': []}, index=pd.Index([], name='my_index'))

In [24]: df['b'] = []

In [25]: df.index
Out[25]: RangeIndex(start=0, stop=0, step=1)

```

Can you check if we have an issue for this? It sounds familiar.

**Comment by p-himik** [comment]
@TomAugspurger Didn't check `__setitem__` before opening the issue. You're right: #22060

**Comment by TomAugspurger** [comment]
Thanks for checking. I renamed that issue title to hopefully be a bit more
searchable.
