### ISSUE TITLE
read_sql had got stuck

### ISSUE THREAD

**Issue by wsty** [pandas-dev/pandas#24898]
I used 'pd.read_sql()' to query data from redshift tables, but met a strange problem, it had blocked on one of the tables.But I can query the table on SQLWorkbecnchJ. What could be the reason?
---------------------------------
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: zh_CN.UTF-8
LOCALE: zh_CN.UTF-8

pandas: 0.23.3
pytest: 4.0.0
pip: 18.1
setuptools: 39.1.0
Cython: 0.28.5
numpy: 1.15.0
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.1.1
sphinx: 1.8.2
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.5
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.0
openpyxl: 2.5.9
xlrd: 1.1.0
xlwt: 1.2.0
xlsxwriter: 1.1.2
lxml: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.11
pymysql: 0.9.2
psycopg2: 2.7.5 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

**Comment by showkeyjar** [comment]
pandas 1.4.4 has same problem. I notice that happened after someone changed database, but I dont know what changed. maybe some meta data can not read or other things?
