### ISSUE TITLE
infer_index fails for Monthly series

### ISSUE THREAD

**Issue by graml** [pandas-dev/pandas#24891]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
pd.infer_freq(pd.to_datetime(pd.Series(['2018-10-03', '2018-11-03', '2018-12-03'])))
```
#### Problem description

I'm using pandas.infer_freq to infer the frequency of a time series. This works fine when the frequency is daily, for instance. It fails when the frequency is monthly.

`pd.infer_freq(pd.to_datetime(pd.Series(['2018-10-03', '2018-10-04', '2018-10-05'])))` returns 'D' (which is correct)
`pd.infer_freq(pd.to_datetime(pd.Series(['2018-10-03', '2018-11-03', '2018-12-03'])))` returns None

#### Expected Output
For the above series I expect the output to be 'M' (or maybe '1M'), but I get `None` returned from infer_freq

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Darwin
OS-release: 17.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: None
pip: 18.1
setuptools: 39.0.1
Cython: None
numpy: 1.16.0
scipy: None
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by trendelkampschroer** [comment]
As far as I understand this is the correct behaviour. The important thing here is the following: "M" refers to *end of month*. The following example will return "M":

```
import pandas as pd
pd.infer_freq(pd.to_datetime(pd.Series(['2018-10-31', '2018-11-30', '2018-12-31'])))

```

another example that shows that your dates do not conform to freq = "M"  is

```
import pandas as pd
pd.DatetimeIndex(["2018-10-03", "2018-11-03", "2018-12-03"], freq="M")

```

which will raise a ValueError!

**Comment by TomAugspurger** [comment]
Thanks @trendelkampschroer, I believe your explanation is correct.
