### ISSUE TITLE
File saved with different user on Linux

### ISSUE THREAD

**Issue by AntonioSecchi** [pandas-dev/pandas#24901]
#### Code Sample, a copy-pastable example if possible

```python

import dataframe ... then ..
dataframe.to_excel('path_to_save.xlsx')

# Your code here

```
#### Problem description

I'm executing an easy **foo.py** script containing 1 simple function.
1) Read a xlsx file, via pd.read_excel
2) Save it again. 

While I'm running the foo.py file on linux machine by **root01** user, I see that the new saved .xlsx file **is not owned by me**, but by **root**. So in other scripts, following this foo.py, I got in troubles, due to this change of ownerships happened inside foo.py writing phase.]

**Comment by TomAugspurger** [comment]
Does this match the behavior of `open("file", "w")` in the same python process?

**Comment by AntonioSecchi** [comment]
Can you be a little be more precise? I'm not understanding your question.

The problem is still existing, within my foo.py, executed on Linux machine by root01 user, is generating an output.xlsx file owned not by root01, but root instead.

Causing an error in the next parts of foo,py, where I need to re-load and manipulate this output.xlsx data.

Thanks

**Comment by TomAugspurger** [comment]
If you run

```python
with open('foo.txt', 'w') as f:
    f.write('test')
```

who owns the file foo.txt?

**Comment by WillAyd** [comment]
Closing due to age and lack of info
