### ISSUE TITLE
Pandas 0.24 - cannot install with python 3.6.8

### ISSUE THREAD

**Issue by grzadr** [pandas-dev/pandas#24936]
New release of pandas cannot be installed via conda. It results in error:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - pandas==0.24.0 -> python[version='>=2.7,<2.8.0a0'] -> openssl=1.0
  - pandas==0.24.0 -> python[version='>=2.7,<2.8.0a0'] -> readline=6.2
  - pandas==0.24.0 -> python[version='>=2.7,<2.8.0a0'] -> sqlite=3.13
  - pandas==0.24.0 -> python[version='>=2.7,<2.8.0a0'] -> tk=8.5
  - python==3.6.8
```

**Comment by TomAugspurger** [comment]
How'd you install pandas? 0.24.0 hasn't been pushed anywhere yet.

**Comment by TomAugspurger** [comment]
Unless the conda-forge packages just finished.

**Comment by TomAugspurger** [comment]
And what platform?

Looks like a few of the packages have finished, but not all. https://anaconda.org/conda-forge/pandas/files?version=0.24.0

**Comment by grzadr** [comment]
Ok, I tried one more time. All dependencies are satisfied.
