### ISSUE TITLE
ADMIN: Policy on Maintenance Branches?

### ISSUE THREAD

**Issue by gfyoung** [pandas-dev/pandas#24943]
@pandas-dev/pandas-core 

With `0.24.0` just released, what's the policy exactly for maintenance branches (e.g. `0.23.x`) i.e. how many do we keep (e.g. three major releases)?  I ask because I see that we're still holding on to [0.19.x](https://github.com/pandas-dev/pandas/tree/0.19.x), which is 5 (!) major releases ago now...

Just a question.  Once it has an answer, feel free to close.

**Comment by jreback** [comment]
we only backport to the latest series (0.24.x)

the others are just there but don’t really hurt anything so can leave alone
