### ISSUE TITLE
Comparison with NaN should yield NaN?

### ISSUE THREAD

**Issue by cbrnr** [pandas-dev/pandas#24947]
I know that there has been some discussion on whether an empty series should sum to 0 or NaN, and apparently by default this now sums to 0 (because `skipna=True`) or `nan` if `skipna=False`. This is consistent with R behavior.

Today I was a bit surprised to see something that may or may not be related to the sum behavior. When you compare values in a series containing `nan`s, e.g.

```
x = pd.Series([1, 2, np.nan, 3])
x == 1
```

the result is

```
0     True
1    False
2    False
3    False
dtype: bool
```

It seems a bit odd that `nan == 1` is `False`, because if `nan` is really a missing value, the result should also be `nan`. This is also what R does:

```
x <- c(1, 2, 3, NA)
x == 1
```

which yields

```
[1]  TRUE FALSE FALSE    NA
```

This would also be possible with pandas if an extended datatype for bool that also includes missing values was used. What do you think?

**Comment by WillAyd** [comment]
This follows the IE 7544 specification for NaN comparison so not something I think we will be changing

https://stackoverflow.com/questions/1565164/what-is-the-rationale-for-all-comparisons-returning-false-for-ieee754-nan-values

**Comment by cbrnr** [comment]
I think this misses the point a bit when NaN is used to represent missing values.

**Comment by jorisvandenbossche** [comment]
@cbrnr I agree with you that this can be somewhat strange or surprising behaviour for missing values. But, NaN in numpy is not really a missing value indicator, and in pandas we are somewhat *mis*using NaN for that (for lack of good alternative in numpy).

So given that there are good historical reasons, ànd it has been long standing behaviour, it is not that easy (or even desired) to change.

In my ideal world, where we have proper NA support for all dtypes, we should probably reconsider this. 
But currently we eg don't even have a boolean type that can hold missing data, as you mentioned.

Another question is what boolean indexing should do with missing values (raise? What does R do here?)

**Comment by jreback** [comment]
we actually make this a NaN in the comparison then immediately fill(False) because otherwise indexing would have to check for nulls because indexing with a null unsupported by numpy and this would require quite a bit of code to support 

and it’s just plain convenient (always filling) - that is the practical reason
