### ISSUE TITLE
BUG: to_timedelta('NaT', box=False) returns datetime64('NaT')

### ISSUE THREAD

**Issue by shoyer** [pandas-dev/pandas#24957]
On pandas 0.23 (correct):
```
In [2]: pd.to_timedelta('NaT', box=False)
Out[2]: numpy.timedelta64('NaT','ns')
```

But on pandas 0.24:
```
In [2]: pd.to_timedelta('NaT', box=False)
Out[2]: numpy.datetime64('NaT')
```

The result is a datetime, not a timedelta.

**Comment by jreback** [comment]
looks like a bug; note that box parameter is going away in any event

**Comment by shoyer** [comment]
> looks like a bug; note that box parameter is going away in any event

I hope there's a deprecation cycle planned? (We use `box` downstream in xarray.)

**Comment by jreback** [comment]
yes there is an issue about this

**Comment by gfyoung** [comment]
xref #24416

**Comment by jbrockmendel** [comment]
I’m pretty sure one of my recent PRs broke this, will make a fix shortly.

**Comment by jbrockmendel** [comment]
@shoyer we're about to remove the `box=False` option for `to_timedelta` in #30177, will this break things for xarray?
