### ISSUE TITLE
Rendering in Jupyter Lab issue for 0.24.0

### ISSUE THREAD

**Issue by ecatkins** [pandas-dev/pandas#24979]
After installing 0.24.0, I have seen the behavior screen-shot below across several of my existing Jupyter Lab notebooks, when trying to call `df.head()`. Along with the error message, it still renders a version of the dataframe, but not the nice formatting expected.

![image](https://user-images.githubusercontent.com/8319226/51850387-a575ce00-22ef-11e9-9f38-457dd17465e4.png)

**Comment by TomAugspurger** [comment]
What's the value of 


```python
ip = get_ipython()
front_end = (
    ip.config.get('KernelApp', {}).get('parent_appname', "") or
    ip.config.get('IPKernelApp', {}).get('parent_appname', "")
) 
```

in your jlab session?

**Comment by TomAugspurger** [comment]
see https://github.com/pandas-dev/pandas/issues/25036
