### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by matthiasroder** [pandas-dev/pandas#24981]
I am not sure where to post this. The following page is missing a "do" in the last sentence of the second paragraph.

The sentence should read: "In the apply step, we might wish to DO one of the following."

http://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html

**Comment by mroeschke** [comment]
Nice catch. PRs welcome!

**Comment by mroeschke** [comment]
Closed by https://github.com/pandas-dev/pandas/pull/25038
