### ISSUE TITLE
0.24.0 DateTimeIndex: union() got an unexpected keyword argument 'sort'

### ISSUE THREAD

**Issue by bilalkamoon** [pandas-dev/pandas#24994]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
index1 = pd.DataFrame(index=pd.to_datetime(['19900101'])).index
index2 = index1.copy()
index1.union(index2, sort=False)
TypeError: union() got an unexpected keyword argument 'sort'
```
#### Problem description
The 'sort' argument works with 'difference' and 'intersection' but fails on 'union' for DateTimeIndex.

**Comment by TomAugspurger** [comment]
xref #24966 (that's for intersection, just TimedeltaIndex).

cc @reidy-p.

**Comment by reidy-p** [comment]
@TomAugspurger thanks.

This is just not implemented yet for ``DatetimeIndex``. I have started work on implementing this for ``DatetimeIndex.union`` and it is quite straightforward except in the case where ``this._fast_union(other)`` is called:
https://github.com/pandas-dev/pandas/blob/ece58cb39f2afa6dbc0c64f701847f7efd718a58/pandas/core/indexes/datetimes.py#L479-L501

I'm still trying to figure out whether we can do the sorting inside of ``_fast_union``.
