### ISSUE TITLE
No rectangles showing up in heatmap

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [pandas-dev/pandas#25031]
#### Code Sample, a copy-pastable example

```python

import pandas as pd
from pandas.plotting import autocorrelation_plot
from bokeh.models import ColumnDataSource, LinearColorMapper, BasicTicker, ColorBar
from bokeh.plotting import figure, show, output_notebook, output_file
from bokeh.palettes import mpl
from bokeh.transform import transform

a = pd.DataFrame([
               [64,16,0.],
               [64,32,100.],
               [64,64,200.],
               [128,16,300.],
               [128,32,400.],
               [256,16,500.],
               [256,64,600.],
              ],columns=['n_v', 'n_w','q'])

palette=mpl["Plasma"][256]
mapper = LinearColorMapper(palette=palette, low=a.q.min(), high=a.q.max())

TOOLS = "hover,save,pan,box_zoom,reset,wheel_zoom"

# Define a figure
p = figure(
    plot_width=800,
    plot_height=300,
    title="My plot",
    x_range=list(str(x) for x in a.n_v.drop_duplicates()),
    y_range=list(str(x) for x in a.n_w.drop_duplicates()),
    toolbar_location=None,
    tools="",
    x_axis_location="above")

source = ColumnDataSource(a)

# # Create rectangle for heatmap
p.rect(
    x="n_v",
    y="n_w",
    width=1,
    height=1,
    source=source,
    line_color=None,
    fill_color=transform('q', mapper)
)

# Add legend
color_bar = ColorBar(
    color_mapper=mapper,
    location=(0, 0),
    ticker=BasicTicker(desired_num_ticks=len(palette)))

p.add_layout(color_bar, 'right')

output_notebook()
show(p)

```
#### Problem description

I am on the latest bokeh, 1.0.4, and trying to get a heatmap based on the examples in the docs. However, I have no rectangles showing up in the output, just the plain figure and colorbar.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-43-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: None
pip: 9.0.1
setuptools: 40.6.2
Cython: 0.28.5
numpy: 1.16.0
scipy: 1.2.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by WillAyd** [comment]
Looks like this was closed on the Bokeh end as Usage Question so doing the same here
