### ISSUE TITLE
Add Excel IO to Coverage Builds

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#25052]
Right now AFACIT neither of the builds which generate the code coverage report hit pandas.io.excel, so that entire module is missing from the reports.

Not sure if there's historical reason for doing that and how we want to handle the various engines, but figure its worth getting at least some sort of coverage here built into the CI

**Comment by gfyoung** [comment]
I don't see why we don't.  Let's just add it.

**Comment by jreback** [comment]
the coverage report now is not very useful

we are covering pandas.io.excel but codecov is not good at reporting it - welcome general fixing of coverage

**Comment by fangchenli** [comment]
Excel IO has 90.95% coverage in the codecov report.
