### ISSUE TITLE
Segmentation fault while creating dataframe from list of mixed-type rows

### ISSUE THREAD

**Issue by selik** [pandas-dev/pandas#25075]
```python
In [2]: pd.DataFrame([
   ...:     [1, 2],
   ...:     (3, 4)
   ...: ])
Segmentation fault: 11
```

I'd like to see a `TypeError` here, instead of a segfault.

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.2.final.0
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.0
pytest: None
pip: 19.0.1
setuptools: 40.7.1
Cython: None
numpy: 1.15.4
scipy: 1.2.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by Vibhu-Agarwal** [comment]
Seems a bit odd that the error shows no traceback of function calls because whenever there is an exception, python always show the traceback of exception.
This behavior could be because it's directly printed somewhere after catching the exception OR there's some error in API Calling to CPython Code.

**Comment by Vibhu-Agarwal** [comment]
I would like to work on this issue and solve it.
