### ISSUE TITLE
plot() Has Visual Error When Combing Bar & Line Graphs

### ISSUE THREAD

**Issue by aslobodnik** [pandas-dev/pandas#25100]
#### Code Sample, a copy-pastable example if possible

```
import matplotlib
import pandas as pd

df = pd.DataFrame({'A':[1,2,3],'B':[0.1,.2,.4]})

print(df)

df.A.plot.bar()
df.B.plot(secondary_y=True,style='g')
```
![image](https://user-images.githubusercontent.com/4892978/52173840-9b652c80-2740-11e9-8426-98ee1a27c5b1.png)

#### Problem description

The first & last bar graph of series is on top of the Y axis. 

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.2.final.0
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.0
pytest: None
pip: 18.1
setuptools: 40.6.3
Cython: None
numpy: 1.16.1
scipy: None
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by TomAugspurger** [comment]
You might just want to use matplotlib directly if you're layering plots like this.

Otherwise, you may be able to adjust the limits afterwords by capturing the axes object and updating the limits.

**Comment by lodagro** [comment]
out of date,  for reference:

```
ax = df.A.plot.bar()
xlim = ax.get_xlim()
df.B.plot(secondary_y=True,style='g')
ax.set_xlim(xlim)
```
Or change the order of the plots, the A plot has the widest x-limits.

```                                                                                                                                                                           
df.B.plot(secondary_y=True,style='g')
df.A.plot.bar()
```

Both snippets result in the following plot.

![image](https://user-images.githubusercontent.com/1094464/75258883-6dd5a000-57e7-11ea-84ea-0ebdcbde512d.png)

@aslobodnik Are you ok to close this?

**Comment by aslobodnik** [comment]
Thank you.
