### ISSUE TITLE
Excluding validation error type `PR10` from code base

### ISSUE THREAD

**Issue by stijnvanhoey** [pandas-dev/pandas#25104]
#### Problem description

In order to have a continuous check by the CI on validation error `PR10`, tackling them from the current code base enables the addition to the CI for automated testing in the future.

After checking an [overview of the errors](https://gist.github.com/stijnvanhoey/dfec0f89a58f493bdddd2b463ad7b6e3) (all credits to @datapythonista for the introduction during europandas sprint), the `PR10` has just 3 occurrences, so tackling them should be feasible during the sprint.

|                                              |   deprecated | section                          | type               |
|:---------------------------------------------|-------------:|:---------------------------------|:-------------------|
| pandas.set_option                            |            0 | Working with options             | CallableDynamicDoc |
| pandas.ExcelWriter                           |            0 |                                  | ABCMeta            |
| pandas.core.groupby.DataFrameGroupBy.boxplot |            0 | Computations / Descriptive Stats | function           |

Todo:
* [ ] get rid of the errors in the code base
* [ ] update the `code_check.sh` script to take into account the `PR10` type of errors

**Comment by victormoron** [comment]
I'll take it
