### ISSUE TITLE
assert_*_equal issues

### ISSUE THREAD

**Issue by AntoineD** [pandas-dev/pandas#25135]
The function `assert_almost_equal` may return the return value of another functions like `assert_frame_equal` or `assert_series_equal`.
But `assert_frame_equal` does not return any value explicitly, hence it shall always return None.
Also, `assert_series_equal` may or may not return a value explicitly.

Are those assertion functions usable or am I overlooking something?

**Comment by chris-b1** [comment]
`assert_almost_equal` is not part of the public API, can you please show an example of what's wrong?

**Comment by AntoineD** [comment]
I was not sure about how to use `assert_almost_equal`, despite the name starting with `assert` I have looked at the code and have seen return statements, so I figured out I should check the truth of the returned value.
May be the docstring could specify that an `AssertionError` is raised when the assertion fails.

If that's not a public function, then please ignore this issue.

Nevertheless, I think a public function on par with the numpy allclose would be very useful (with the ability to combine absolute and relative errors).

**Comment by chris-b1** [comment]
That function is not public - but it does look like the return statements are redundant so will keep this open as a code cleanup issue.  Also would take that improvement to the docstring.

**Comment by TrigonaMinima** [comment]
@chris-b1 could you point me to the file where the changes are to be made?

**Comment by TrigonaMinima** [comment]
@chris-b1 if I understand this correctly, the assertions part (```assert_frame_equal``` and `assert_series_equal`) will remain as is, but their return values need not be returned?
