### ISSUE TITLE
Concat/append doesn't sort warning should give location of issue

### ISSUE THREAD

**Issue by cepbrian** [pandas-dev/pandas#25144]
I'm upgrading pandas, and am now experiencing the "concat doesn't sort" warning. The problem is that the warning doesn't say where the issue that it's complaining about is, so it's impossible to take the action that it suggests. 

The warning also doesn't mention that "append" is also affected. 

Basically, I have a large body of code, and it calls append and concat a lot, but almost all of the time, it's using List.append, or some other concat. So, the only way to deal with the warning is to do a global search for "append" and carefully look at each line to determine if it's appending to a DF or a list. Just saying the file/line number that is causing the warning, like other warnings, would make this much easier.

**Comment by TomAugspurger** [comment]
As you’ve noticed, the behavior affects both concat and append. I believe the stacklevel is targeted for concat. If not, that’s a bug.

If you’re interested, a PR passing through the desired stacklevel, to ensure the correct line for both, is welcome. 


You can add a warning filter to elevate warnings to errors, and run under pdb to find the exact lines with issues.

**Comment by mroeschke** [comment]
Since we use `find_stack_level` now, I believe this is fixed so closing
