### ISSUE TITLE
An extra single quotation marks (') in cheat sheet/ Subset Variables (Columns)/regex (Regular Expressions) Examples 

### ISSUE THREAD

**Issue by z1yuan** [pandas-dev/pandas#25156]
#### Problem description
https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf

In Pandas_Cheat_Sheet/ Subset Variables (Columns)/ regex (Regular Expressions) Examples
#### ''^(?!Species$).*' Matches strings except the string 'Species'
The second ' in regex is unnecessary.
#### Expected Output
execute sucessfully

#### Actual result:  
```python
# features = data_df.filter(regex=''^(?!SalePrice$).*')
```
  File "<ipython-input-168-4e3c4f16b4c5>", line 5
    features = data_df.filter(regex=''^(?!SalePrice$).*')
                                        ^
SyntaxError: invalid syntax

#### should be:
```python
# features = data_df.filter(regex='^(?!SalePrice$).*')
```

**Comment by gfyoung** [comment]
Good catch!

cc @TomAugspurger @Dr-Irv 

xref #20366
