### ISSUE TITLE
Imputing values while joining dataframes

### ISSUE THREAD

**Issue by vlavorini** [pandas-dev/pandas#25158]
## description

Currently, as specified in the [documentation](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html), the standard action for concatenations in case of missing columns is to fill them with a `NaN`:

```python
df3 = pd.DataFrame([['c', 3, 'cat'], ['d', 4, 'dog']],
                   columns=['letter', 'number', 'animal'])
df1 = pd.DataFrame([['a', 1], ['b', 2]],
                   columns=['letter', 'number'])
joined = pd.concat([df1, df3], sort=False)

```

Output:

|    | letter   |   number | animal   |
|---:|:---------|---------:|:---------|
|  0 | a        |        1 | nan      |
|  1 | b        |        2 | nan      |
|  0 | c        |        3 | cat      |
|  1 | d        |        4 | dog      |

It would be nice to have the possibility of specifying the value to be used for the imputations.
This will avoid another operation for changing the `nan` with the desired imputation, but also operations of upcasting  and subsequent downcasting.

As example, say the colum which will be imputed with `nan` originally hosted integers; since `np.nan` is a float, with the actual imputation the column in the joined dataframe will host floats. But maybe we actually want that column to stick with integers, and so we have firstly to change the nans with (say) `0`, and then downcast again to integers.

## desired behavior

To specify the imputation for each column. Something like:

    imputation_dict = {'animal' : "mammal",
                      'number' : 0}
    joined = pd.concat([df1, df3], sort=False, imputations=imputation_dict)

to obtain as result:

|    | letter   |   number | animal   |
|---:|:---------|---------:|:---------|
|  0 | a        |        1 | mammal      |
|  1 | b        |        2 | mammal      |
|  0 | c        |        3 | cat      |
|  1 | d        |        4 | dog      |

**Comment by chris-b1** [comment]
We do have a `fill_value` parameter in a few places, but I'm not sure this is much better than a fillna?

```python
pd.concat([df1, df3], sort=False).fillna({'animal': 'mammal'})

  letter  number  animal
0      a       1  mammal
1      b       2  mammal
0      c       3     cat
1      d       4     dog

```

**Comment by vlavorini** [comment]
Actually, in many cases this is enough.

But still, this makes the double operation of 1) filling with NA and 2) changing NA with the desired value.

And, following the example of the `int` column introduced before, also an upcasting from `int` to `float`. And eventually a downcasting operation, if the user really need ints.

**Comment by gfyoung** [comment]
A `fill_value` in `concat` sounds interesting.  I don't see why not actually...

cc @jreback

**Comment by jreback** [comment]
- this is quite complicated as you generally cannot use the same diol value across dtypes (except for nan)
- i don’t this adds any readibility (actually makes it less so)
- has almost no effect on perf
- all pandas operations fill with nan by default (with very few exceptions and though are explicit operations); where we do have a full option it is on a SINGLE column
- it’s just one more option, making the function harder to grok


so -1 on this

**Comment by mroeschke** [comment]
Thanks for the suggestion, but it doesn't seem there's much interest from the core team or the community for this feature. Closing.
