### ISSUE TITLE
Intersection of MultiIndexes reports incorrect lexsort_depth

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#25169]
#### Code Sample, a copy-pastable example if possible

```python
In [2]: mi1 = pd.MultiIndex(levels=[['2018', 'a', 'c', 'e', 'num', 'oan', 'vol'],
   ...:                             [1970, '']],
   ...:            codes=[[3, 6, 4, ],
   ...:                   [1, 1, 1]],
   ...:            names=['variable', 'cit_year'])
   ...:            

In [3]: mi2 = pd.MultiIndex(levels=[['e', 'num', 'oan', 'vol', 'year'],
   ...:                             ['']],
   ...:            codes=[[3, 1, 4, 1, 0],
   ...:                   [0, 0, 0, 0, 0]],
   ...:            names=['variable', 'cit_year'])
   ...:            

In [4]: mi_int = mi1.intersection(mi2)

In [5]: mi_int.lexsort_depth
Out[5]: 2

In [6]: list(mi_int)
Out[6]: [('num', ''), ('vol', ''), ('e', '')]

In [7]: mi_int.is_monotonic
Out[7]: False
```

#### Problem description

For a 2-levels ``MultiIndex``, ``lexsort_depth=2`` means sorted. This is clearly not the case for ``mi_int``.

#### Expected Output

0 at ``Out[5]:``.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: e3b095074c5c3b29ec25a994cd204349b872d961
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-8-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.25.0.dev0+66.ge3b095074
pytest: 3.5.0
pip: 9.0.1
setuptools: 39.2.0
Cython: 0.28.4
numpy: 1.14.3
scipy: 0.19.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.5.6
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.0dev
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.2.2.post1634.dev0+ge8120cf6d
openpyxl: 2.3.0
xlrd: 1.0.0
xlwt: 1.3.0
xlsxwriter: 0.9.6
lxml.etree: 4.1.1
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.2.1
gcsfs: None

</details>

**Comment by toobaz** [comment]
By the way: this popped up in code which used to run just fine. So I think it is a regression.

**Comment by mroeschke** [comment]
Looks to work on master. Could use a test

```
In [1]: In [2]: mi1 = pd.MultiIndex(levels=[['2018', 'a', 'c', 'e', 'num', 'oan', 'vol'],
   ...:    ...:                             [1970, '']],
   ...:    ...:            codes=[[3, 6, 4, ],
   ...:    ...:                   [1, 1, 1]],
   ...:    ...:            names=['variable', 'cit_year'])

In [2]:
   ...: In [3]: mi2 = pd.MultiIndex(levels=[['e', 'num', 'oan', 'vol', 'year'],
   ...:    ...:                             ['']],
   ...:    ...:            codes=[[3, 1, 4, 1, 0],
   ...:    ...:                   [0, 0, 0, 0, 0]],
   ...:    ...:            names=['variable', 'cit_year'])

In [3]: In [4]: mi_int = mi1.intersection(mi2)

In [4]: In [5]: mi_int._lexsort_depth
Out[4]: 0
```

**Comment by jackgoldsmith4** [comment]
take
