### ISSUE TITLE
Convention for same-directory imports

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#25178]
In most places we use absolute imports, e.g. `from pandas.foo.bar import baz`.  In a small number of places (the one I noticed being `core.dtypes.cast`, `core.dtypes.missing`),  we use relative imports for same-directory imports (`from .common import foo, bar, baz`)

We should either get rid of these special cases, or explicitly allow same-directory imports to be relative.

I happen to like the relative imports because they are much less verbose, make it easy to see when most/all of a module's imports are from the same directory.  IIRC `isort` supports arranging same-directory imports in their own section.

**Comment by jbrockmendel** [comment]
Just checked, isort doesn't recognizes same-directory as LOCALFOLDER without relative import

**Comment by gfyoung** [comment]
I would prefer absolute as well if possible, for similar reasons as @WillAyd described above.

**Comment by jreback** [comment]
yeah i think this just adds mental overhead; you have to know what is local and what is not; let’s just be consistent and use absolute

**Comment by jbrockmendel** [comment]
If someone can figure out a way to make isort respect the local-directory rule with absolute imports that'd go a fair way towards solving my gripes.

If we (well, the rest of you really) want absolute-only, this may merit a lint rule.
