### ISSUE TITLE
Error when read_json created by to_json with orient='table and index=False

### ISSUE THREAD

**Issue by albertvillanova** [pandas-dev/pandas#25170]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
df = pd.DataFrame({'a': [1, 2], 'b': [3, 4]})
dfjson = df.to_json(orient='table', index=False)
result = pd.read_json(dfjson, orient='table')
```
#### Problem description
An error is raised while the original DataFrame should be recovered:
```shell
pandas/io/json/table_schema.py in parse_table_schema(json, precise_float)
    315     df = df.astype(dtypes)
    316 
--> 317     df = df.set_index(table['schema']['primaryKey'])
    318     if len(df.index.names) == 1:
    319         if df.index.name == 'index':

KeyError: 'primaryKey'
```

My pandas version is 0.24.0.

#### Expected Output
The expected output `result` should be the original DataFrame `df`.

#### Output of ``pd.show_versions()``

<details>
pandas/util/_print_versions.py in <lambda>(mod)
     78         ("blosc", lambda mod: mod.__version__),
     79         ("bottleneck", lambda mod: mod.__version__),
---> 80         ("tables", lambda mod: mod.__version__),
     81         ("numexpr", lambda mod: mod.__version__),
     82         ("feather", lambda mod: mod.__version__),

AttributeError: module 'tables' has no attribute '__version__'
</details>

**Comment by WillAyd** [comment]
Thanks for the report. Investigation and PRs are always welcome.
