### ISSUE TITLE
DOC: DataFrame.mask() uses df.where in the examples section

### ISSUE THREAD

**Issue by miguelfg** [pandas-dev/pandas#25187]
In the stables doc page of `pandas.DataFrame.mask()` in the bottom section of 'Examples', is showing executions of using `pandas.DataFrame.where()` method instead of mask. I refer to this [page](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.mask.html)

**Comment by gfyoung** [comment]
Yeah, we should change those to use `mask` instead of `where`.  Good catch!

**Comment by gfyoung** [comment]
@jreback : I noticed that we use `_shared_docs` on `where` and `mask`.  Is there a reason for doing this?  I do understand they're pretty related, so I guess I can (sort of) see why they share doc examples...

**Comment by Regexp96** [comment]
can I work on this issue?

**Comment by poralo** [comment]
I would like to update this doc, however should I modify the `_shared_docs` to match the `where` and `mask` methods only or create an independent docstring for both?
