### ISSUE TITLE
CLN: Remove pd.util._depr_module?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#25200]
AFAICT it isn't used anywhere

**Comment by gfyoung** [comment]
Hold onto this for now.  We used it for deprecating entire modules.  I doubt that such a use case will not come along in the future.

**Comment by jreback** [comment]
i think we used this to deprecate datetools 

+.25 with removing its potentially useful

**Comment by gfyoung** [comment]
> i think we used this to deprecate datetools

@jreback : Yes, that's right.  This was a pretty nifty way of doing so, so I'm not really inclined to remove it any time soon given its usefulness.

**Comment by jbrockmendel** [comment]
Could we move it somewhere outside of the pandas/ directory?  It adds noise to coverage stats #26877.

**Comment by gfyoung** [comment]
Is it possible to ignore coverage for those lines?  I would prefer that.  The reason is that this is a really useful utility that we may want to reuse in the future.
