### ISSUE TITLE
Remove python 2.7 testing

### ISSUE THREAD

**Issue by tdamsma** [pandas-dev/pandas#25216]
Python 2.7 support is now dropped for 0.25, but the CI tests are still run against python 2.7

**Comment by mroeschke** [comment]
https://github.com/pandas-dev/pandas/pull/24942 is already in motion converting the 2.7 builds to 3.5 compatibility builds.

**Comment by tdamsma** [comment]
I really tried to look for a similar issue but somehow missed it. Will close
