### ISSUE TITLE
BUG: object dtype & Int64Dtype equality comparison issue

### ISSUE THREAD

**Issue by danj1974** [pandas-dev/pandas#25213]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

d = {'int': [1, 2, 3], 'str': ['a', 'b', 'c']}
df = pd.DataFrame(d)

print(df['int'].dtype == pd.core.arrays.integer.Int64Dtype)
print(df['str'].dtype == pd.core.arrays.integer.Int64Dtype)
```
Example output:
```python
In [1]: import pandas as pd                                                                                                              

In [2]: d = {'int': [1, 2, 3], 'str': ['a', 'b', 'c']}                                                                                   

In [3]: df = pd.DataFrame(d)                                                                                                             

In [4]: df.dtypes                                                                                                                        
Out[4]: 
int     int64
str    object
dtype: object

In [5]: df['int'].dtype == pd.core.arrays.integer.Int64Dtype                                                                             
Out[5]: False

In [6]: df['str'].dtype == pd.core.arrays.integer.Int64Dtype                                                                             
Out[6]: True
```

#### Problem description

I want to process columns of a dataframe according to their type and have a list of numeric dtypes that I'm interested in (one of which is the newer `Int64` type).  However, I'm getting an issue with columns of  `object` dtype which also appears to be `in` this list of numeric types.
The simplified code above shows why I'm getting this problem - when the dtype is `object` the equality check against `Int64Dtype` evaluates to `True`.  Is this expected behaviour, or a bug?

I'm going to solve my use case in another way (using `pandas.api.types.is_numeric_dtype`), but I'd like to find out whether this is a bug or whether I need improve my understanding!

#### Expected Output

```
Out[5]: False
Out[6]: False
```

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-43-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.24.1
pytest: None
pip: 19.0.1
setuptools: 40.6.2
Cython: None
numpy: 1.16.1
scipy: None
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by jreback** [comment]
directly comparing dtypes is never recomended, use the is_* functions and/or use ``.select_dtypes()``

**Comment by jreback** [comment]
``df['str'].dtype == pd.core.arrays.integer.Int64Dtype``
this might be suspect, but I am not sure we can actually change this as its a numpy dtype comparison

**Comment by jorisvandenbossche** [comment]
You have a difference in behaviour between the class and an instance:

```
In [38]: pd.core.arrays.integer.Int64Dtype == np.dtype(object)                                                                                                                  
Out[38]: True

In [39]: pd.core.arrays.integer.Int64Dtype() == np.dtype(object)                                                                                                                
Out[39]: False
```

You get the same with any class (which might be a strange behaviour in numpy comparison of object dtype)

**Comment by danj1974** [comment]
Thanks for the responses.  I think the first one pretty much nails it - the `is_*` functions are much better suited to this purpose, and the third one helps to explain why comparing dtypes directly is not a good approach.
