### ISSUE TITLE
Pandas read_html loses comma

### ISSUE THREAD

**Issue by Code4SAFrankie** [pandas-dev/pandas#25218]
#### Code Sample

```python
import pandas as pd
table_list = pd.read_html("https://af.wikipedia.org/wiki/Lys_van_lande_volgens_geletterdheidskoers")
df = table_list[0].copy()

# Make the first row of the table the column headers.
new_header = df.iloc[0]    # Grab the first row for the header.
df = df[1:]    # Take the data less the header row.
df.columns = new_header    # Set the header row as the df header.

df
```
#### Problem description

The last column (Geletterdheidskoers) has a value for the country Togo that is 532 instead of 53,2. This might be related to the fact that the row before that (for Jemen) incorrectly uses a period instead of a comma to indicate the decimal point. 

#### Expected Output

53,2

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.4
pytest: 4.0.0
pip: 19.0.1
setuptools: 40.6.2
Cython: 0.28.5
numpy: 1.15.4
scipy: 1.1.0
pyarrow: 0.10.0
xarray: 0.10.8
IPython: 6.5.0
sphinx: 1.7.7
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: 1.5.1
bottleneck: 1.2.1
tables: None
numexpr: None
feather: 0.4.0
matplotlib: 3.0.2
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: 1.0.7
lxml: 4.2.4
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.11
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: 0.1.6
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by WillAyd** [comment]
The source table is definitely a little wonky but sure I don't think this should just ignore the decimal point. Investigation and PRs certainly welcome

**Comment by rbenes** [comment]
sign ```,``` is handled as a thoushand separator (see https://github.com/pandas-dev/pandas/blob/master/pandas/io/parsers.py#L2920 where ```self.thousands = ','``` )

**Comment by Code4SAFrankie** [comment]
It might be that this can be solved by just adding a parameter to not interpret numbers and rather just leave them as strings which can then be cleaned up manually later.

**Comment by rbenes** [comment]
add setup of thousands to ```read_html()``` ```thousands=None```  and it works:

```
import pandas as pd
table_list = pd.read_html("https://af.wikipedia.org/wiki/Lys_van_lande_volgens_geletterdheidskoers",
                          thousands=None)
df = table_list[0].copy()

# Make the first row of the table the column headers.
new_header = df.iloc[0]    # Grab the first row for the header.
df = df[1:]    # Take the data less the header row.
df.columns = new_header    # Set the header row as the df header.

print(df)
```

**Comment by Code4SAFrankie** [comment]
Thanks that did the trick.
