### ISSUE TITLE
read_csv() drops randomly datapoints (lines)

### ISSUE THREAD

**Issue by Joapfel** [pandas-dev/pandas#25228]
```
df_test = pd.read_csv('utterances_test.txt', sep='\t', names=['id', 'label'])
```
Above code results in "df_test" having 19988 lines, but the original file "utterances_test.txt" has exactly 20000 lines.

This can be confirmed by running 
```
cat utterances_test.txt | wc -l
```
in the terminal.

Also reading the file in myself with python also results in 20000 lines.

Above file attached.

[utterances_test.txt](https://github.com/pandas-dev/pandas/files/2845609/utterances_test.txt)

**Comment by otro-mas1** [comment]
I usually use \ t as a separator precisely to avoid confusion with '  " , ; 

I was surprised by the behavior. In case you're worth it, I've tried a workaround

`
df_test = pd.read_csv('utterances_test.txt', sep='\n' , engine='python', header=None, verbose=True, names=['line'])

df_test.shape

df_test=df_test['line'].str.split('\t', expand=True)
df_test.columns=['id', 'line']

df_test.info(memory_usage='deep')
`

**Comment by chris-b1** [comment]
You have quotes in your data - use the `quoting` param to control this - docs [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html)

```python
In [201]: import csv

In [202]: df_test = pd.read_csv(f, sep='\t', names=['id', 'label'], quoting=csv.QUOTE_NONE)

In [203]: len(df_test)
Out[203]: 20000
```
