### ISSUE TITLE
Pandas mapper enhancement

### ISSUE THREAD

**Issue by gnilrets** [pandas-dev/pandas#25251]
I wrote a package that monkey patches pandas to allow support of writing concise error-trapping field transformations (https://github.com/inside-track/pandas-mapper).  Would there be any interest in integrating this directly in pandas (or any objection)?

**Comment by gfyoung** [comment]
cc @jreback

**Comment by nmusolino** [comment]
As a genuine question, how does this compare to using `DataFrame.assign()`?  For example, the zero-to-one, one-to-one, and many-to-one examples:

```
df.mapping([None, 'five', transform=5])
df.mapping([('num', 'translated', translate)])
df.mapping([(['num', 'name'], 'num-name', lambda row: '-'.join(row.apply(str)))])
```

could be written:

```
df.assign(**{
    'five': 5,
    'translated': translate(df['num']),
    'num-name': df['num'].astype(str) + df['name'],
})
```

(`assign` also takes callables for cases where the dataframe is an intermediate value.)

I could see some cool possibilities if the mapper objects represented deferred operations, and only computed the new columns on an as-needed basis or something like that.

**Comment by gnilrets** [comment]
@nmusolino - This most important difference between mapping and assign is that mapping can redirect records that have errors.  I use pandas for a lot of ETL work, and when we get garbage or unexpected data in one field, we don't necessarily want that to prevent transforming and loading data for all the other records.  So instead, records with mapping errors are redirected to an error reporting mechanism.

One of the more common scenarios I run into is poorly formatted dates:

```
df = pd.DataFrame({'my_date_str': ['2017-01-03','garbage data','2017-03-22']})
mapped_df = df.mapping(
    [
        ('my_date_str', 'my_date', lambda v: datetime.datetime.strptime(v, '%Y-%m-%d'))
    ],
    on_error='redirect'
)

print(mapped_df.mapped)
#                my_date
# 0  2017-01-03 00:00:00
# 2  2017-03-22 00:00:00

print(mapped_df.errors)
#     my_date_str                                          __error__
# 1  garbage data  {'msg': 'ValueError(garbage data): time data '...
```

Additionally, something just rubs me wrong about having to reference the dataframe variable in so many places when using assign.  I  try to give my variables descriptive names, and sometimes they can get long, so writing something like this can be cumbersome:

```
my_really_important_df.assign(**{
    'five': 5,
    'translated': translate(my_really_important_df['num']),
    'num-name': my_really_important_df['num'].astype(str) + my_really_important_df['name'],
})
```

... in which case, you'll usually end up creating temporary variables or something (`tmp_df = my_really_important_df` which is equally as icky.

**Comment by nmusolino** [comment]
Sorry for the delayed reply.  Please note that I write all this as a pandas user, not as someone with any authority in the project.

I like the declarative look of the library, and the organized error reporting.  

Pandas already has a few ways to compute/insert things in DataFrames, like [`DataFrame.apply()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html), [`DataFrame.assign()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.assign.html), and [`DataFrame.eval()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.eval.html).

I'd also add that error reporting needs (saving error info in containers, versus logging, versus raising for particular exceptions) will be different for everyone.  It's probably hard for pandas to provide an error-handling mechanism that is fully general, other than simply letting users employ the full range of Python language facilities.

One implementation note is that the current mapper library seems to operate row-wise (I could be wrong), while pandas generally tries to steer users to column-wise operations.

Overall, I think it's great to build a library like this on top of pandas.  Let a thousand flowers bloom, and if this kind of tool is helpful for organizing ETL operations with occasional failures, I think it's totally fine to have it as a supplemental tool for working with pandas.

PS, some good news about `DataFrame.assign()`:  you can actually pass a callable (e.g. a lambda), which allows a user to add columns to frames without using their name.  

```python
my_important_df.reset_index().assign(**{'num-name': lambda df: df['num'].astype('str') + df['name']})
```

**Comment by mroeschke** [comment]
Thanks for the suggestion but it doesn't seem like there's much interest from the core team to integrate this library, and generally pandas is trying to reduce its API surface area. Closing.
