### ISSUE TITLE
Compat: re-write legacy files for io tests

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#25250]
#25238 introduced a kludge in test_pickle and test_msgpack to ignore the Panel objects when unpickling/unpacking files produced using older versions.  The right way to do this is to re-write those files without Panels in them to begin with.

**Comment by gfyoung** [comment]
Unless we plan to explicitly drop support for older files, I don't think all of them should be rewritten.  Most of them sure, but we should leave a couple of tests to ensure backwards compatibility of some sort.

**Comment by jreback** [comment]
the idea is to rewrite them with the older version of pandas but with the generate from master

this ensures that Panels are not written but ensures backward compat

**Comment by jbrockmendel** [comment]
AFAICT this is a blocker for removing Panel.  I was unable to find a way to patch the pickle tests to not raise if Panel does not exist.

**Comment by WillAyd** [comment]
Just so I'm clear on expectation we don't need to go back and change all of the historical pickle files do we? We have some of these going back to 0.10.1 - I'm assuming older ones we can just let be historical artifacts? Do we just now need one file per OS?

**Comment by jbrockmendel** [comment]
I think the idea is to re-write the historical ones using old pandas but up-to-date generate_files_whatever.py

(For orthogonal reasons I'd be +1 on trimming how many old versions we support for pickle compat)

**Comment by WillAyd** [comment]
closed by #27082
