### ISSUE TITLE
replace method with comma separator does not work in pandas 0.24.1

### ISSUE THREAD

**Issue by mr-yoo** [pandas-dev/pandas#25259]
### The latest version (0.24.1) does not replace comma separator, but 0.23.4 does.

```python
import pandas as pd

df = pd.DataFrame({'one': ["1,000", "2,000"], 'two': ["3,000", "4,000"]})
df = df.replace({',': ''}, regex=True)

print(pd.__version__)
print(df)
```

```
0.23.4
    one   two
0  1000  3000
1  2000  4000
```

```
0.24.1
     one    two
0  1,000  3,000
1  2,000  4,000
```

If other characters are used with a comma, it works normally
```
df = df.replace({'1,': ''}, regex=True)
```
```
     one    two
0    000  3,000
1  2,000  4,000
```

**Comment by PetitLepton** [comment]
Hi, it is not related to commas. In your example @mr-yoo, if you try to replace `,0`, it also fails. The replacement works only if the pattern is the beginning of the string
```
df.replace({',0': ''}, regex=True)
```

```
0.23.4
   one  two
0  100  300
1  200  400
```

```
0.24.1
     one    two
0  1, 000  3,000
1  2,000  4,000
```

Can it be related to
```
op = np.vectorize(lambda x: bool(re.match(b, x)) if isinstance(x, str)
                  else False)
``` 
in managers.py? 

`re.match` checks only if the beginning of the string matches. Should it be `re.search`? From my tests, it seems to reproduce the previous behaviour.

**Comment by WillAyd** [comment]
@PetitLepton seems logical, so maybe introduced as part of https://github.com/pandas-dev/pandas/issues/20656

Would certainly welcome a PR to fix if you are up for one
