### ISSUE TITLE
Numpy 1.16 and pickle retrocompatibility

### ISSUE THREAD

**Issue by SylvainLan** [pandas-dev/pandas#25269]
Hi, 

I don't really know if this matter should be posted in pandas but here is the issue I noticed. 

If you save a DataFrame into pickle (using `to_pickle`) on a virtualenv that has `numpy>=1.16` and want to open it with another virtualenv with `numpy<=1.15.4`, the following error is thrown : 
```
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
```

Which is a feature of `numpy=1.16`. This issue could be of interest because the numpy version downloaded through anaconda is still 1.15.4 (unless you use conda-forge) while it is 1.16 using pip.

My pandas version is `0.24.1` in both cases.

**Comment by TomAugspurger** [comment]
I don't think there's anything pandas can do to work around this (though let me know if I'm wrong).

**Comment by jreback** [comment]
yeah this should be pushed upstream to numpy i think; they shouldn't break pickle compat like this

**Comment by SylvainLan** [comment]
OK I'll post something on numpy then, sorry for that !

**Comment by jorisvandenbossche** [comment]
Not sure it is something numpy can do something about either. In pandas, we also don't guarantee such backwards compatibility for plain pickles (and actually not even with the `to_pickle`/`read_pickle` interface, where we have more control, we only guarantee forward compatibility).
