### ISSUE TITLE
Python 2: pandas.Series.eq() crashes with unicode data

### ISSUE THREAD

**Issue by joaoe** [pandas-dev/pandas#25287]
#### Code Sample

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import pandas as pd
weird_string = u"føøbår"
x = pd.DataFrame({"a" : [weird_string, "xx"]})
bool_series = (x["a"].eq(weird_string))
print(x[bool_series].to_string())
assert len(x[bool_series]) == 1
```

#### Problem description

The code snippet above crashes. This makes querying dataframes with non-ascii text quite difficult.

Exception
```
bug.py
    bool_series = (x["a"].eq(weird_string))
.env\lib\site-packages\pandas\core\ops.py:1728: in wrapper
    (is_extension_array_dtype(other) and not is_scalar(other))):
.env\lib\site-packages\pandas\core\dtypes\common.py:1749: in is_extension_array_dtype
    registry.find(dtype) is not None)
.env\lib\site-packages\pandas\core\dtypes\dtypes.py:89: in find
    return dtype_type.construct_from_string(dtype)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 2: ordinal not in range(128)
```

I'm using pandas 0.24.1

#### Expected Output

No crash :)

#### Output of ``pd.show_versions()``

<details>
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.15.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.1
pytest: 4.2.0
pip: 19.0.1
setuptools: 40.7.3
Cython: None
numpy: 1.15.4
scipy: 1.2.0
pyarrow: None
xarray: 0.11.3
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.9
blosc: None
bottleneck: None
tables: 3.4.4
numexpr: 2.6.9
feather: None
matplotlib: 2.2.3
openpyxl: 2.5.14
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by joaoe** [comment]
The culprit line https://github.com/pandas-dev/pandas/blob/master/pandas/core/dtypes/dtypes.py#L701
```
raise TypeError(msg.format(string))
```
`str.format` will crash if any of the arguments is a unicode string with non-ascii chars.

A simple fix is to replace it with
```
msg = "Could not construct DatetimeTZDtype from '%s'"
...
raise TypeError(msg % string)
```
mecause `str.__mode__` can cope with unicode strings and will convert the whole string to unicode if needed.

**Comment by TomAugspurger** [comment]
We use `{}` string formatters through the codebase, so that patch won't quite work.

We really shouldn't be calling `is_extension_dtype` on data if we can avoid it. That would ideally only be called on dtypes. I'm not sure if that's possible here.

**Comment by joaoe** [comment]
Btw, workaround for who might need. Pick one of the following:
1. `pip install pandas==0.23.4`
2. Put this in some place where it always runs in your project
```
import sys
reload(sys)
sys.sys.setdefaultencoding("utf-8")
```
This way you can keep the newer pandas, but you have been warned that this will bite you https://stackoverflow.com/questions/3828723/why-should-we-not-use-sys-setdefaultencodingutf-8-in-a-py-script

**Comment by topper-123** [comment]
This works correctly in Python3 as it's unicode by default, and pandas is dropping Python2 support, so closing this issue.
