### ISSUE TITLE
OO Optimization Failure

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#25293]
The travis logs have been failing recently as a result of -OO optimization failure. I cannot reproduce this locally so may just be a Windows issue?

https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=8270&view=logs&jobId=ae5f5554-4e02-5fb5-2f57-d6e8aefc10c0&taskId=1f8b548e-2577-5189-1750-f82ca6ecc932&lineStart=690&lineEnd=691&colStart=1&colEnd=1

**Comment by WillAyd** [comment]
cc @datapythonista for any insights. I think this is more an issue with the Azure environment than the codebase itself but hard to say

**Comment by jreback** [comment]
I guess let's temporarily xfail that test on windows / py2.7 to avoid failing all PRs; if someone wants to push a PR.

**Comment by jreback** [comment]
closed by #25323
