### ISSUE TITLE
Row assignment by multi-index label not working in 0.24.1

### ISSUE THREAD

**Issue by stuz5000** [pandas-dev/pandas#25290]
#### Code Sample, a copy-pastable example if possible

I uses to be able to assign to a series like so:

```
import pandas as pd
pd.Series()["aaa"]= True        # regular indexing
pd.Series().loc["aaa"]= True        # regular indexing
pd.Series()[("aaa",123)]= True  # Multi indexing
pd.Series().loc[("aaa",123)]= True  # Multi indexing
```

but in pandas 0.24.1:

```
pd.Series()[("aaa",123)]= True
pd.Series().loc[("aaa",123)]= True
```

both give me:

```
KeyError: u"None of [Index([u'aaa', 1], dtype='object')] are in the [index]"
```
Was assignment of new rows by multiindex intentionally removed?

#### Problem description

Assignment by multiindex no longer works after upgrading from 0.24.1 from 0.22.0

#### Expected Output

Should not assert.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.15.candidate.1
python-bits: 64
OS: Linux
OS-release: 4.15.0-45-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.24.1
pytest: None
pip: 18.1
setuptools: 40.6.2
Cython: 0.29.1
numpy: 1.16.1
scipy: 1.2.0
pyarrow: None
xarray: None
IPython: 5.0.0
sphinx: None
patsy: 0.5.1
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: None
tables: None
numexpr: 2.6.8
feather: None
matplotlib: 2.1.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: 4.2.1
bs4: 4.6.0
html5lib: 0.9999999
sqlalchemy: 1.2.17
pymysql: None
psycopg2: 2.7.7 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by jorisvandenbossche** [comment]
cc @toobaz

**Comment by gfyoung** [comment]
@jorisvandenbossche : This also doesn't work in `0.23.4` (which is why I dropped the milestone), and I can't test on `0.22.0` at the moment.

**Comment by jorisvandenbossche** [comment]
Hmm, I thought I tested it in 0.22 (which is why I added the milestone, even if it is from one release before it might be worth fixing short term if it was not done on purpose), but, now I actually can't replicate it on 0.22:

```
In [15]: pd.__version__
Out[15]: '0.22.0'

In [16]: s = pd.Series()

In [17]: s[('a', 1)] = True
...
KeyError: "['a' 1] not in index"

In [18]: s.loc[('a', 1)] = True
...
KeyError: "['a' 1] not in index"
```

@stuz5000 It does work for you in 0.22? Can you show actual output (like the above)?

**Comment by stuz5000** [comment]
>>> pd.__version__
u'0.22.0'
>>> import panads as pd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named panads
>>> import pandas as pd
>>> pd.Series()[(1,1)] = 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/series.py", line
793, in __setitem__
    setitem(key, value)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/series.py", line
769, in setitem
    self.loc[key] = value
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/indexing.py",
line 193, in __setitem__
    indexer = self._get_setitem_indexer(key)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/indexing.py",
line 179, in _get_setitem_indexer
    return self._convert_to_indexer(key, is_setter=True)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/indexing.py",
line 1269, in _convert_to_indexer
    .format(mask=objarr[mask]))
KeyError: '[1 1] not in index'

**Comment by jorisvandenbossche** [comment]
@stuz5000 so it is raising an error in 0.22 as well? 
Above you said "Assignment by multiindex no longer works after upgrading from 0.24.1 from 0.22.0". So but what exactly stopped working?

**Comment by mroeschke** [comment]
Appears that it's unclear which version this behavior was buggy. Additionally these are relatively older version of pandas. Closing for now but feel free to open a new issue if this still persists.
