### ISSUE TITLE
BLD: pandas-wheels timing out

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#25302]
anyone know why the wheel building is timing out, not all of them though: https://travis-ci.org/MacPython/pandas-wheels. I have restarted on multiple days.

cc @TomAugspurger @matthew-brett

**Comment by xhochy** [comment]
`nipy.bic.berkeley.edu` is no longer alive, this PR fixes it: https://github.com/matthew-brett/multibuild/pull/165/files

We need to update the multibuild hash in `pandas-wheels` and it should work again.

**Comment by jreback** [comment]
trying this

**Comment by jreback** [comment]
this is fixed
