### ISSUE TITLE
pandas.Series.eq docs page example doesn't feature eq

### ISSUE THREAD

**Issue by mikeyford** [pandas-dev/pandas#25301]
The current stable documentation page for eq doesn't actually feature eq in the example:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.eq.html

I presume the last execution in the example should be something like this, rather than the add example. 

```
>>> a.eq(b)
a     True
b    False
c    False
d    False
e    False
dtype: bool
```

**Comment by TomAugspurger** [comment]
I think we have another issue for this. Can you search for it?

**Comment by mikeyford** [comment]
I could only find this issue and commit https://github.com/pandas-dev/pandas/pull/24774 which fixes the DataFrame.eq docs.

It doesn't look to me like that will address the Series.eq docs, although I may be missing something.

**Comment by TomAugspurger** [comment]
I was thinking of https://github.com/pandas-dev/pandas/issues/24589.

We can lump this in with that.

**Comment by mikeyford** [comment]
ah, that makes sense. Cheers.
