### ISSUE TITLE
Missing required dependencies ['numpy'] on pandas 0.24.1

### ISSUE THREAD

**Issue by Skeletrox** [pandas-dev/pandas#25316]
#### Code Sample with obtained output

```python
import pandas as pd
# --------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-7dd3504c366f> in <module>
----> 1 import pandas as pd

~/.local/lib/python3.6/site-packages/pandas/__init__.py in <module>
     17 if missing_dependencies:
     18     raise ImportError(
---> 19         "Missing required dependencies {0}".format(missing_dependencies))
     20 del hard_dependencies, dependency, missing_dependencies
     21 

ImportError: Missing required dependencies ['numpy']

```
#### pip3 show outputs

```bash
➜ pip3 show pandas
Name: pandas
Version: 0.24.1
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: http://pandas.pydata.org
Author: None
Author-email: None
License: BSD
Location: /home/skeletrox/.local/lib/python3.6/site-packages
Requires: numpy, python-dateutil, pytz

➜ pip3 show numpy
Name: numpy
Version: 1.16.1
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /home/skeletrox/.local/lib/python3.6/site-packages
Requires: 

```

#### System

* Linux Mint 19.1 Tessa
* `pip3 --version` output: `pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)`

#### Problem description

Recently updated pandas using `pip3 install -U pandas` and tried running the code again, leading to the above issue.

#### Attempted Fixes

Tried reinstalling both numpy and pandas, and cleared cache so as to force `pip3` to pull from remote.
```
➜ pip3 uninstall pandas && pip3 uninstall numpy && pip3 install numpy && pip3 install pandas
```

yet the issue remains consistent.

#### Expected result

Successful import of pandas

**Comment by Skeletrox** [comment]
Issue fixed; was an issue with multiple instances of numpy installed. Resolving that issue by repeatedly running `pip3 uninstall numpy` until none remained and then running `pip3 install numpy` allowed pandas to import it without  any issues

**Comment by hc85** [comment]
I'm facing the same problem. However, the work around is not working.

```
$ pip3 show pandas
Name: pandas                                                                                                                                                                                                      
Version: 0.24.2                                                                                                                                                                                                   
Summary: Powerful data structures for data analysis, time series, and statistics                                                                                                                                  
Home-page: http://pandas.pydata.org                                                                                                                                                                               
Author: None                                                                                                                                                                                                      
Author-email: None                                                                                                                                                                                                
License: BSD                                                                                                                                                                                                      
Location: /home/helder/.local/lib/python3.6/site-packages                                                                                                                                                         
Requires: pytz, python-dateutil, numpy                                                                                                                                                                            

$ pip3 show numpy
Name: numpy                                                                                                                                                                                                       
Version: 1.16.2                                                                                                                                                                                                   
Summary: NumPy is the fundamental package for array computing with Python.                                                                                                                                        
Home-page: https://www.numpy.org                                                                                                                                                                                  
Author: Travis E. Oliphant et al.                                                                                                                                                                                 
Author-email: None                                                                                                                                                                                                
License: BSD                                                                                                                                                                                                      
Location: /home/helder/.local/lib/python3.6/site-packages                                                                                                                                                         
Requires:
``` 

Any thoughts?

**Comment by hc85** [comment]
I fixed it!

First I had to uninstall pandas and numpy:
`$ pip3 uninstall numpy && pip3 uninstall pandas`

and then I went to the folder: `/home/helder/.local/lib/python3.6/site-packages/`
and removed all folders of pandas and numpy.

Finally I installed all them again:
`$ pip3 install numpy && pip3 install pandas`

After that everything is working!

**Comment by bluenote10** [comment]
This issue is especially annoying, because the standard venvs in Travis CI have a pre-installed version of `numpy==1.13.3`. Using pandas within Travis is therefore broken out-of-the box. The problem seems to apply to 0.24.2 as well.

To make Travis work again had to prefix all jobs with `pip uninstall -y -q numpy` (don't forget the `-y` otherwise pip prompts for verification and the job gets stuck).

**Comment by arunhpatil** [comment]
> This issue is especially annoying, because the standard venvs in Travis CI have a pre-installed version of `numpy==1.13.3`. Using pandas within Travis is therefore broken out-of-the box. The problem seems to apply to 0.24.2 as well.
> 
> To make Travis work again, I had to prefix all jobs with `pip uninstall -y -q numpy`; don't forget the `-y` otherwise pip prompts for verification and the job gets stuck.



> I fixed it!
> 
> First I had to uninstall pandas and numpy:
> `$ pip3 uninstall numpy && pip3 uninstall pandas`
> 
> and then I went to the folder: `/home/helder/.local/lib/python3.6/site-packages/`
> and removed all folders of pandas and numpy.
> 
> Finally I installed all them again:
> `$ pip3 install numpy && pip3 install pandas`
> 
> After that everything is working!

Thank you @helco88.  
This solution works, however, if there are multiple versions of python3 installed i.e., python3.6 and python3.8 or similar then this will not work no matter how many times we try this. It is better to install these packages for the specific or the current python version in use. 

```
python --version
python3.8 -m pip install pandas
python3.8 -m pip install numpy 
```

**Comment by boumpteryx** [comment]
I just uninstalled my only numpy and reinstalled it and now everything works !! thanks a lot !

**Comment by varagur** [comment]
Hi All ,

     I followed this steps but none worked for me . what to do ?
     
   when i run the below command i get below output , 
# python3 --version
Python 3.4.10
# python --version
Python 2.7.18

Moreover am unable to install pandas and numpy using pip3
i installed using pip

# python3.6 -m pip install pandas
Requirement already satisfied: pandas in /xx/lib64/python3.6/site-packages (1.1.5)
Requirement already satisfied: pandas in /xx/lib64/python3.6/site-packages (1.1.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /xx/lib/python3.6/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /xx/lib/python3.6/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.15.4 in/xx/lib64/python3.6/site-packages (from pandas) (1.19.5)
Requirement already satisfied: six>=1.5 in /xx/lib/python3.6/site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)

still i get 
    import pandas as pd
  File "/xx/lib/python3.6/site-packages/env/pandas/__init__.py", line 13
    missing_dependencies.append(f"{dependency}: {e}")
                                                   ^
SyntaxError: invalid syntax

**Comment by arunhpatil** [comment]
Hi @varagur,

What Operating system do you use (is it Mac iOS)? 
Can you test the following on the command line:
1. which python 
    - This will you the path where the Python is installed, for example /usr/local/bin/python 
2. Executing python version with its path from the above command:
    - for example `/usr/local/bin/python --version` 
    - This will tell what python version is currently running. If it is python 2.7, then you need to set python3.6 as your default python. That is done as described [How to Make Python 3 the Default in MacOS](https://osxdaily.com/2022/02/15/make-python-3-default-macos/).   
3. Once done with stpe 3: you can confirm the python version by `python --version` and make sure this gives you 3.6
4. Once that is done, try installing pandas and other packages as `pip install pandas`.

I hope this is easy to follow and let us know if you come across other issues. 

Thank you,
Arun.

**Comment by varagur** [comment]
Hi Arun ,

       Tx for replying. Am on a linux machine , can i try this https://www.baeldung.com/linux/default-python3 ? or any this better approach ?
