### ISSUE TITLE
.isin() includes unwanted string value in a column with 0 instead of dropping them

### ISSUE THREAD

**Issue by StevenLi-DS** [pandas-dev/pandas#25319]
#### Code Sample, a copy-pastable example if possible

```python
[in]:
import pandas as pd
import seaborn as sns
df = sns.load_dataset('tips')
df.day.value_counts()

[out]:
Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64

[in]:
days = ['Sat', 'Sun', 'Thur']
df1 = df[df.day.isin(days)]
# or
# df1 = df.loc[df.day.isin(days)]
df1.day.value_counts()

[out]:
Sat     87
Sun     76
Thur    62
Fri      0
Name: day, dtype: int64
```
However, I expect `.isin()` returns
```python
Sat     87
Sun     76
Thur    62
Name: day, dtype: int64
```
Here's a side affect while plotting using seaborn:
```python
sns.boxplot(x='day', y='total_bill', data=df1)
```
![download](https://user-images.githubusercontent.com/33796896/52788431-e92a4080-302e-11e9-8b45-5b51d6b71bbe.png)

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------

commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.1
pytest: 3.7.1
pip: 18.1
setuptools: 40.2.0
Cython: 0.29.4
numpy: 1.15.4
scipy: 1.2.0
pyarrow: None
xarray: 0.11.0
IPython: 7.1.1
sphinx: 1.7.6
patsy: 0.5.1
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.9
feather: None
matplotlib: 3.0.2
openpyxl: 2.5.5
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.5
lxml.etree: 4.2.4
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.2.10
pymysql: None
psycopg2: 2.7.6.1 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by TomAugspurger** [comment]
That's the expected behavior for categorical variables. See `pandas.Categorical.value_counts`.

Convert to a different dtype, or use `.remove_unused_categories` if you don't want to include the unobserved categories.

**Comment by StevenLi-DS** [comment]
I got `SettingWithCopyWarning` sometimes while using `cat.remove_unused_categories()`. 

I only used `.value_counts()` to show the behavior of `isin()`, and the problem is not `.value_counts()` but `.isin()` as you can see from the side effect above.

Maybe, pandas should automatically recategorize the variable after apply `.isin()`

This is a bit confusing since the [doc][1] didn't mention anyting about dtypes. Please consider reopening the issue to at least add this detail about dtypes in the doc.


[1]: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.isin.html

**Comment by TomAugspurger** [comment]
> and the problem is not `.value_counts()` but `.isin()` as you can see from the side effect above.

Can you clarify your confusion about `isin`?  That returns a boolean array of values that are or aren't in the passed values. What's your expected output for `isin`?

**Comment by StevenLi-DS** [comment]
Sorry for the late reply. `.isin()` instead didn't return any undesired rows, but I'd expect that a categorical variable will be modified (unused categories will be drop) in place.  Thanks for the clarification and now I understand how it behaves.
