### ISSUE TITLE
Pandas graphing time series issue

### ISSUE THREAD

**Issue by bran112299** [pandas-dev/pandas#25312]
```

import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
%matplotlib qt


exampl = [4.4,5.1,6.1,6.2,6.1,6.1,5.7,5.2,4.7,4.1,3.9,3.5]
dates = pd.date_range('2016/10/29 5:30pm', periods = 12, freq='H')

series = pd.Series(exampl, dates)


series15m = series.resample('15min').interpolate(method = 'cubic')

series15m.plot()
series.plot()
plt.legend()
plt.show()
```

#### Problem description

I tried this code and the graph it ends up is messed up, I figured it was matplotlib and I asked them for help and the lead developer told me it probably wasn't matplotlib.

![helppanda](https://user-images.githubusercontent.com/15021936/52758694-41355880-2fd7-11e9-80f4-c83dad6fa938.PNG)

**Comment by WillAyd** [comment]
Hi - it's not clear what you are describing here. Going to close for now as this doesn't have any of the required information but if it persists please read through the guide on crafting bug reports:

https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#bug-reports-and-enhancement-requests

And feel free to reopen with required info from there

**Comment by bran112299** [comment]
> Hi - it's not clear what you are describing here. Going to close for now as this doesn't have any of the required information but if it persists please read through the guide on crafting bug reports:
> 
> https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#bug-reports-and-enhancement-requests
> 
> And feel free to reopen with required info from there

Run the plots individually, Then run the plots at the same time and there is clearly a date range issue that causes the graph to mess up.

**Comment by WillAyd** [comment]
Can you post screenshots of what you are seeing?
