### ISSUE TITLE
np.sum(TimedeltaIndex) should return a Timedelta, not np.timedelta64

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#25335]
ditto TimedeltaArray.  xref #25329.

I think the relevant method is `__array_ufunc__`, @jorisvandenbossche any idea about this?

**Comment by TomAugspurger** [comment]
> I think the relevant method is `__array_ufunc__`, @jorisvandenbossche any idea about this?

The datetimelike indexes and arrays don't implement `__array_ufunc__` yet, do they? Or are you saying that the fix is to implement it?

The old (pre-numpy 1.13) way of doing this would be with `__array_ufunc__`.

**Comment by jorisvandenbossche** [comment]
> The old (pre-numpy 1.13) way of doing this would be with `__array_ufunc__`, which is defined on our indexes.

I suppose you mean `__array_wrap__` ?

**Comment by jorisvandenbossche** [comment]
See also https://github.com/pandas-dev/pandas/issues/22798 and https://github.com/pandas-dev/pandas/pull/23293 (that last one is a PR that started implementing this, I hope to find some time soon to pick it up again).

**Comment by TomAugspurger** [comment]
Yes, sorry.
