### ISSUE TITLE
[SOLVED - NOT BUG] DataFrame.rename method changing the datetime format.

### ISSUE THREAD

**Issue by rickymal** [pandas-dev/pandas#25348]
The Rename Method from DataFrame convert de datetime format in the original form.
I have a datetime in the format %Y-%m-%d in a DataFrame. Before I use de rename method this DataFrame change the format to %Y-%m-%d 00:00:00. This is a Bug? isn't correct rename the index too. I think that this method should only rename de columns that i put

A Example:

![image](https://user-images.githubusercontent.com/25715921/52919335-3b45bd00-32e0-11e9-8417-f5adbabb4919.png)

**Comment by TomAugspurger** [comment]
Do you have a minimal example?
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by rickymal** [comment]
Sorry, I put the imagem right now.

**Comment by rickymal** [comment]
I found the problem, the index parameter nedd to be None, not str as I put. Sorry

**Comment by mroeschke** [comment]
We follow the same conventions as `datetime.datetime`

```
In [2]: str(datetime.datetime(2019, 1, 1))
Out[2]: '2019-01-01 00:00:00'
```
