### ISSUE TITLE
Argument 'fastpath' in 'Categorical' not documented

### ISSUE THREAD

**Issue by david-cortes** [pandas-dev/pandas#25345]
In documentaion for `pandas.Categorical`:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Categorical.html

Argument `fastpath` which can be passed to the class constructor is not documented on the docstring:
https://github.com/pandas-dev/pandas/blob/master/pandas/core/arrays/categorical.py

**Comment by jreback** [comment]
see https://github.com/pandas-dev/pandas/issues/20110

we would actually like to remove these

**Comment by timhoffm** [comment]
At least a short note "deprecated" or "to be deprecated" or "internal only" on the parameter would help so that users know they don't have to bother with this parameter.
