### ISSUE TITLE
general dataframe combine doc

### ISSUE THREAD

**Issue by wangfengming** [pandas-dev/pandas#25359]
#### Problem description

https://github.com/pandas-dev/pandas/blob/master/doc/source/getting_started/basics.rst#general-dataframe-combine

```python
def combiner(x, y):
    np.where(pd.isna(x), y, x)
df1.combine(df2, combiner)
```
the code above should be:

```python
def combiner(x, y):
    return np.where(pd.isna(x), y, x)
df1.combine(df2, combiner)
```

**Comment by gfyoung** [comment]
cc @ywpark1 @jorisvandenbossche 

This was introduced in #23802.  Nice catch!
