### ISSUE TITLE
DatetimeIndex.to_frame('ds')  doesn't change column name to 'ds'

### ISSUE THREAD

**Issue by eromoe** [pandas-dev/pandas#25367]
#### Code Sample, a copy-pastable example if possible

```python
from datetime import datetime, timedelta
import pandas as pd
periods = 7
today = datetime.now()
future_ds = pd.date_range(today.strftime('%Y-%m-%d'), (today + timedelta(days=periods)).strftime('%Y-%m-%d') )

future_ds.to_frame('ds')
```

#### Problem
`.to_frame('ds')` on DatetimeIndex didn't work.
Have to convert to series at first  `future_ds.to_series().to_frame('ds')`

#### Output

```
In [12]: future_ds.to_frame('ds')
Out[12]:
                    0
2019-02-19 2019-02-19
2019-02-20 2019-02-20
2019-02-21 2019-02-21
2019-02-22 2019-02-22
2019-02-23 2019-02-23
2019-02-24 2019-02-24
2019-02-25 2019-02-25
2019-02-26 2019-02-26
```

#### Expected Output

```
In [12]: future_ds.to_frame('ds')
Out[12]:
                    ds
2019-02-19 2019-02-19
2019-02-20 2019-02-20
2019-02-21 2019-02-21
2019-02-22 2019-02-22
2019-02-23 2019-02-23
2019-02-24 2019-02-24
2019-02-25 2019-02-25
2019-02-26 2019-02-26
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 45 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.4
pytest: 3.5.1
pip: 19.0.1
setuptools: 39.1.0
Cython: 0.28.2
numpy: 1.14.3
scipy: 1.1.0
pyarrow: 0.12.0
xarray: None
IPython: 7.2.0
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.6.1
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 3.0.1
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: None
psycopg2: 2.7.6.1 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: 0.1.6
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by mroeschke** [comment]
The second argument sets the column name. The first argument is a boolean that sets the original index as the index of the df ('ds' happens to be truthy).

```
In [2]: pd.DatetimeIndex(['2019']).to_frame(True, 'ds')
Out[2]:
                   ds
2019-01-01 2019-01-01
``` 

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.to_frame.html
