### ISSUE TITLE
Missing license file on linux wheels

### ISSUE THREAD

**Issue by rahulporuri** [pandas-dev/pandas#25374]
#### Problem description

The manylinux1 wheels for cp36 pandas 0.24.1 don't have License files. See https://files.pythonhosted.org/packages/e6/de/a0d3defd8f338eaf53ef716e40ef6d6c277c35d50e09b586e170169cdf0d/pandas-0.24.1-cp36-cp36m-manylinux1_x86_64.whl for example.

**Comment by rahulporuri** [comment]
Note that the wheels for pandas 0.23.4 + cp36 have license files missing on both macosx and manylinux1.

**Comment by TomAugspurger** [comment]
Are they just missing for the 3.6 wheels?

**Comment by rahulporuri** [comment]
> Are they just missing for the 3.6 wheels?

I did a full audit of 0.24.1 wheels and all of the manylinux1 (686, 64) (2.7, 3.5, 3.6, 3.7) wheels are missing the license file in the `dist-info` dir.

**Comment by TomAugspurger** [comment]
Thanks. Interested in looking into why it's not being included?

**Comment by rahulporuri** [comment]
It looks like https://github.com/pandas-dev/pandas-release is the infrastructure used to create wheels for manylinux. If it is, I can try looking at why the files are missing over the week.

**Comment by TomAugspurger** [comment]
Correct. For manylinux, we use multibuild.

I would start by looking here, to ensure that a simple `python setup.py
bdist_wheel` on master produces a wheel with the license file.

**Comment by rahulporuri** [comment]
That's weird. `python setup.py bdist_wheel` doesn't produce a wheel with the license file either. But the License file is listed in the manifest so i'm not sure what's going on. Investigating.

```
...
adding 'pandas/util/_validators.py'
adding 'pandas/util/testing.py'
adding 'pandas-0.25.0.dev0+138.g2909b830f.dist-info/DESCRIPTION.rst'
adding 'pandas-0.25.0.dev0+138.g2909b830f.dist-info/metadata.json'
adding 'pandas-0.25.0.dev0+138.g2909b830f.dist-info/top_level.txt'
adding 'pandas-0.25.0.dev0+138.g2909b830f.dist-info/WHEEL'
adding 'pandas-0.25.0.dev0+138.g2909b830f.dist-info/METADATA'
adding 'pandas-0.25.0.dev0+138.g2909b830f.dist-info/RECORD'
```

**Comment by mroeschke** [comment]
I don't think this is an issue with our CI BuildWheel setup for newer versions of pandas so closing. Can reopen if this issue shows up again
