### ISSUE TITLE
pandas.DataFrame.rolling¶ - Bad Documentation

### ISSUE THREAD

**Issue by PoeteMaudit** [pandas-dev/pandas#25387]
Many things are unclear at the docs of the pandas.DataFrame.rolling.

A couple of them are the following:
1) 
What is an offset?

2) 
What is the position of the current value at the window?

From what I see is that the current value (of your pandas series to be processed) is the last of the rolling window.  (This is not clear at all)

If you set center as True then it becomes the center value.

If I am not very clear then apologies but I cannot explain things that should have been clear at the docs.

**Comment by WillAyd** [comment]
Thanks for the issue! So I would say there are one of two routes here:

  1. If you have actual updates you'd like to make to the documentation then a PR to update would always be welcome!
  2. If you are unclear on the usage of the feature your best bet is to ask on StackOverflow

I *think* this falls into the second categorization so going to close as this board is mostly reserved for actual bug and enhancement requests; SO's Q&A format is much better for usage questions and helps others with the same question in the future
