### ISSUE TITLE
Putting an Arrow table into a Pandas series takes a long time

### ISSUE THREAD

**Issue by mrocklin** [pandas-dev/pandas#25389]
It takes a surprisingly long time to put a list containing a PyArrow table object into an object-dtype Pandas series

```python
In [1]: import numpy as np, pandas as pd, pyarrow as pa

In [2]: df = pd.DataFrame({'x': np.arange(1000000)})

In [3]: %time t = pa.Table.from_pandas(df)
CPU times: user 5.36 ms, sys: 3.22 ms, total: 8.58 ms
Wall time: 7.47 ms

In [4]: %time s = pd.Series([t], dtype=object)
CPU times: user 2.7 s, sys: 114 ms, total: 2.82 s
Wall time: 2.81 s
```

Originally reported downstream in https://github.com/dask/distributed/issues/2521 by @randerzander

**Comment by jreback** [comment]
this is essentially a duplicate of #25384

**Comment by mrocklin** [comment]
Ah, my apologies.  I'm not seeing exactly how, but I'm more than happy to
trust your interpretation here :)

Happy to close if desired.

**Comment by WillAyd** [comment]
I think that reference should be #25364

**Comment by jreback** [comment]
i had a typo in the issue number ; check again

**Comment by mrocklin** [comment]
Thanks.  Posted there.  Closing.
