### ISSUE TITLE
to_sql(method='multi') returns COUNT field incorrect or syntax error

### ISSUE THREAD

**Issue by nickwan** [pandas-dev/pandas#25391]
Using `to_sql(method=None)` works, but even with all of the speed ups wrt `fast_executemany` and `@event.listens_for(engine, 'before_cursor_execute')` I'm not discovering a speed up for writing up to my Azure DB. `to_sql(method='multi')` seemed promising, but this error pops up 

```python
Error: ('07002', '[07002] [Microsoft][ODBC Driver 17 for SQL Server]COUNT field incorrect or syntax error (0) (SQLExecDirectW)')
```

Here's a notebook where the error is hopefully reproducible (the error log is output in the notebook)  
https://github.com/nickwan/pandas_sql_multi/blob/master/pandas_sql_multi.ipynb

Perhaps relevant information:
Ubuntu 16.04.5 LTS
pandas:  0.24.1
numpy:  1.15.2
pyodbc:  4.0.25
sqlalchemy:  1.2.18

**Comment by mroeschke** [comment]
`'multi'` is not necessarily supported by all DBs. pandas leverages SQLAlchemy for the inserts. See 

https://docs.sqlalchemy.org/en/latest/core/dml.html#sqlalchemy.sql.expression.Insert.values.params.*args 

https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-sql-method

**Comment by jayvoy** [comment]
Nick - did you ever find a fix to write your data faster to your Azure DB?
