### ISSUE TITLE
pd.Interval default closed='right'?

### ISSUE THREAD

**Issue by smsaladi** [pandas-dev/pandas#25396]
In my trying to use pd.Intervals/pd.IntervalIndex (which are terrific additions), I've become somewhat perplexed with the default of `closed='right'`. Python slicing is inclusive-exclusive, so I thought `pd.Interval`s might have the same default. I imagine there is a reason for this that I haven't quite understood.

I tried searching through the issue tracker for more information but wasn't really successful ... although I imagine it's pretty likely that I've missed the relevant issue.

**Comment by gfyoung** [comment]
cc @jreback

**Comment by jbrockmendel** [comment]
cc @jschendel ?

**Comment by mroeschke** [comment]
Thanks for the suggestion but changing the default would probably induce a lot of churn for not much gain so closing
