### ISSUE TITLE
No module named 'pandas.tslib''

### ISSUE THREAD

**Issue by qqkl662** [pandas-dev/pandas#25401]
i cannot import the module named qtpandas,this module is based on pandas.
the problem is 'ModuleNotFoundError: No module named 'pandas.tslib''
how to solve this problem?
i have install the qtpandas and pandas
![360 20190221231955910](https://user-images.githubusercontent.com/42534003/53179726-445fc280-362f-11e9-91ec-c072842ff563.jpg)

**Comment by jreback** [comment]
this was deprecated multiple versions ago and removed in 0.24.x 

not sure what you are trying to do

**Comment by TomAugspurger** [comment]
`pandas.tslib` was deprecated, and removed in 0.24.0.

qtpandas will need to be updated, or you'll need to downgrade your version of pandas.

**Comment by chris-b1** [comment]
You would need to report that issue to [qtpandas](https://github.com/draperjames/qtpandas) - it is a separate module/repo, not supported by pandas
