### ISSUE TITLE
Dataframe replace empty string casts Int64 columns to float

### ISSUE THREAD

**Issue by miroli** [pandas-dev/pandas#25438]
#### Code Sample

```python
df = pd.DataFrame({
    'a': [1, 2, 3, np.nan], 
    'b': ['some', 'strings', 'here', 'he']
})

df['a'] = df['a'].astype('Int64')

df.replace('', np.nan).dtypes  # Column a is now float

```
#### Problem description

The new Int64Dtype does not behave as expected here. If you do a global replacement of empty strings to NaN's, it seems weird that this would have the side effect of casting ints to floats.

#### Expected Output

Expected:

```
a     Int64
b    object
dtype: object
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Darwin
OS-release: 18.0.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.1
pytest: None
pip: 10.0.1
setuptools: 39.2.0
Cython: None
numpy: 1.16.1
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: 2.4.11
xlrd: 1.2.0
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: 1.0.1
sqlalchemy: 1.2.12
pymysql: None
psycopg2: 2.7.5 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by jreback** [comment]
since this is an optional dtype currently there are number of edge cases - welcome a PR to fix this

**Comment by TomAugspurger** [comment]
I think we have other issues about replace on extension arrays. Can you
search for them and close this issue if you find a duplicate?
