### ISSUE TITLE
Can't write output using ExcelWriter

### ISSUE THREAD

**Issue by alvipranandha** [pandas-dev/pandas#25443]
#### Code Sample, a copy-pastable example if possible
```python
file_A.shape
writer = pd.ExcelWriter(filename, engine='xlsxwriter', options={'strings_to_urls': False})
file_A.to_excel(writer)

```
#### Problem description

Hi i have an issue that related to pd.ExcelWriter (the code example above). I can't write the output of excel file using that pandas. I Thought this is kind of bug, I have tried to reinstall jupyter notebook but it didn't well and still the same. 

#### Expected Output

result.xlsx

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.1
pytest: 4.0.2
pip: 18.1
setuptools: 40.6.3
Cython: 0.29.2
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.8.2
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.2
openpyxl: 2.5.12
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.2
lxml.etree: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by WillAyd** [comment]
You’d have to explicitly close or save your ExcelWriter for the object to persist, though best way to do this is using the context manager as shown in its documentation:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.ExcelWriter.html#pandas.ExcelWriter
