### ISSUE TITLE
Rename droplevel to drop_level

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#25442]
For PEP8 compliance and better method naming consistency

**Comment by vaibhavhrt** [comment]
I will get this done. PR coming in a day ortwo.

**Comment by vaibhavhrt** [comment]
@WillAyd I guess you are talking about `core.generic.NDFrame.droplevel`. Should I just rename the function, or create a new function `drop_level` with same stuff as `droplevel`. Then add depreciation warning in `droplevel`?

**Comment by jorisvandenbossche** [comment]
Can we have some more discussion about this first? 

In *general*, I am not sure this kind of renames just for style are worth the breakage / code churn for users. 
We also have quite some others that do not follow this style (`groupby`, `fillna`, `isna`, `swaplevel`, ...), which I don't suppose we are going to change all of them. So what would be an argument for changing `droplevel` and not others?

I suppose one argument could be that `droplevel` is probably less used (so renaming it has less impact), and that we also have a `reorder_levels`. But, then we should also rename `swaplevel`?

**Comment by WillAyd** [comment]
I don’t think this is critical for now. IIRC opened this up as someone was asking for all names to follow PEP8 but I don’t think this is important for now. 

Closing but if someone else feels strongly feel free to reopen
