### ISSUE TITLE
read_excel na_filter undocumented?

### ISSUE THREAD

**Issue by fiendish** [pandas-dev/pandas#25453]
#### Problem description

Empirically, `pandas.read_excel(foo, na_filter=False)` works as expected, but the na_filter argument doesn't appear to be mentioned in the read_excel docs.

**Comment by gfyoung** [comment]
Indeed, it does seem to be supported.  A lot of arguments to `read_excel` get passed into `read_csv` mechanisms (which support `na_filter`), so this is not entirely surprising to see.
