### ISSUE TITLE
dropna(inplace=True) doesn't work when loading csv in chunks

### ISSUE THREAD

**Issue by osterburg** [pandas-dev/pandas#25451]
```python
chunksize = 100000
reader = pd.read_csv(in_file, chunksize=chunksize, encoding='utf-8', engine='python', compression='gzip')

for chunk in reader:
    train, valid = np.split(chunk.sample(frac=1).reset_index(drop=True), [int(.8 * len(chunk))])
    
    train.dropna(inplace=True)
    
    if not valid_file.exists():
        train.to_csv(train_file, index=False)
    else:
        train.to_csv(train_file, index=False, mode='a', header=False)

```
#### Problem description

When loading a large data csv file using chunksize dropna inplace doesn't work. In order to make it work you have to 

```python
    train = train.dropna()
```

**Comment by gfyoung** [comment]
@osterburg : Thanks for reporting this!  Could you please update your issue with the following:

* The output of `pd.show_versions()`
* A sample file for the `in_file` variable that illustrates the issue.

For what it's worth, I tried your code on a small file of my own (with missing values of course) and could not reproduce your problem.

**Comment by osterburg** [comment]
`pd.show_versions()`

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.1
pytest: 4.2.1
pip: 19.0.1
setuptools: 40.7.3
Cython: 0.29.4
numpy: 1.15.4
scipy: 1.2.0
pyarrow: 0.11.1
xarray: None
IPython: 7.2.0
sphinx: None
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml.etree: 4.2.6
bs4: None
html5lib: 1.0.1
sqlalchemy: 1.2.17
pymysql: None
psycopg2: 2.7.6.1 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: 0.2.0
fastparquet: 0.2.1
pandas_gbq: None
pandas_datareader: None
gcsfs: None

**Comment by osterburg** [comment]
[sample.csv.zip](https://github.com/pandas-dev/pandas/files/2909036/sample.csv.zip)

**Comment by osterburg** [comment]
Please be aware that I uploaded a zip file not a gzip and it is much smaller, only 1000 lines.
Hope that helps.
Thanks.

**Comment by gfyoung** [comment]
Sorry for taking so long to reply, but I can't replicate this issue with the file you provided on `master`.

**Comment by osterburg** [comment]
I will try to isolate it on my side and keep you posted. Thx.

**Comment by osterburg** [comment]
Sorry for taking so long to reply, super busy at the moment with other stuff. I will try to find time over the weekend to replicate it - hopefully. Thanks.

**Comment by osterburg** [comment]
I need more coffee. Sorry for the mess above.

Sorry for taking so long to reply, super busy at the moment with other stuff. I will try to find time over the weekend. Thanks.

**Comment by mroeschke** [comment]
Feel free to reopen when you have a moment to debug further.
