### ISSUE TITLE
Support tuples in iloc

### ISSUE THREAD

**Issue by d8w** [pandas-dev/pandas#25456]
#### Code Sample, a copy-pastable example if possible

```python
data = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
data.iloc[:, (1,)] # or data.iloc[:, tuple([1])]

## Below is the stack trace
## I removed personal information in the python path.

IndexingError                             Traceback (most recent call last)
<ipython-input-3-a2992a163015> in <module>()
----> 1 data.iloc[:, (1,)]

/path/to/lib/python2.7/site-packages/pandas/core/indexing.pyc in __getitem__(self, key)
   1492             except (KeyError, IndexError, AttributeError):
   1493                 pass
-> 1494             return self._getitem_tuple(key)
   1495         else:
   1496             # we by definition only have the 0th axis

/path/to/lib/python2.7/site-packages/pandas/core/indexing.pyc in _getitem_tuple(self, tup)
   2141     def _getitem_tuple(self, tup):
   2142 
-> 2143         self._has_valid_tuple(tup)
   2144         try:
   2145             return self._getitem_lowerdim(tup)

/path/to/lib/python2.7/site-packages/pandas/core/indexing.pyc in _has_valid_tuple(self, key)
    221                 raise IndexingError('Too many indexers')
    222             try:
--> 223                 self._validate_key(k, i)
    224             except ValueError:
    225                 raise ValueError("Location based indexing can only have "

/path/to/lib/python2.7/site-packages/pandas/core/indexing.pyc in _validate_key(self, key, axis)
   2072             # a tuple should already have been caught by this point
   2073             # so don't treat a tuple as a valid indexer
-> 2074             raise IndexingError('Too many indexers')
   2075         elif is_list_like_indexer(key):
   2076             # check that the key does not exceed the maximum size of the index

IndexingError: Too many indexers
```
#### Problem description

According to the [current document](https://pandas.pydata.org/pandas-docs/version/0.24.1/reference/api/pandas.DataFrame.iloc.html), `iloc[]` support a list or array of integers as inputs.
Could you add support for tuples?
Or is there a particular reason to not allow tuples as inputs? If so, you may want to consider documenting it in that link.

#### Expected Output

```python
	b
0	4
1	5
2	6
```

#### Output of 0.24.1

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.14.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-957.1.3.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.24.1
pytest: None
pip: 9.0.1
setuptools: 40.8.0
Cython: None
numpy: 1.16.1
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 5.5.0
sphinx: None
patsy: 0.4.1
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.3
openpyxl: None
xlrd: 1.2.0
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: 0.9999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by gfyoung** [comment]
cc @toobaz @jreback

**Comment by jorisvandenbossche** [comment]
A particular reason to not allow this, is that for `loc`, tuples have a specific meaning that differs from lists (lists and tuples are not interchangeable there). 

On the other hand, it is also good to keep the semantics of `.iloc` quite similar to plain numpy indexing, and there tuples are regarded as lists.

**Comment by toobaz** [comment]
>  Could you add support for tuples?

Definitely not, sorry.

As discussed many times - but unfortunately still not documented properly - tuples are not list-likes in pandas, mostly for the reason explained by @jorisvandenbossche .

**Comment by toobaz** [comment]
@d8w Yes, you're right, the docs do need a fix. But I think this is already discussed elsewhere. If not, feel free to open an issue about the docs not describing what a list-like is. Thanks!

**Comment by jorisvandenbossche** [comment]
@toobaz note that for `iloc`, there can never be any ambiguity (so for me, it's not a "definitely not", although I am OK with not allowing it, despite the inconsistency with numpy, as it is not really needed; the user can simply convert it to a list)

**Comment by toobaz** [comment]
> note that for `iloc`, there can never be any ambiguity

@jorisvandenbossche my argument was just of consistency with ``loc`` (and others cases in which there is ambiguity). I meant "we have a general rule" (which I think is something core devs more or less agree on), rather than "the OP suggested behavior is inconsistent".

This said, tuples as list-likes do slightly increase the scope for ambiguity in ``iloc`` too, because then one could think that
```python
data.iloc[(1,2)]
```
looks at rows 1 and 2, while it looks at row 1 and column 2. But admittedly this is not my main point.
