### ISSUE TITLE
Literal nan string stored in dataframe using json_normalize for null value in string metadata column

### ISSUE THREAD

**Issue by joetl** [pandas-dev/pandas#25468]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd
data = [{"name": "test","address": [{"add": "add1"}]},{"address": [{"add": "add2"}]}]
df = pd.io.json.json_normalize(data,"address","name",errors="ignore")
df
```
#### Problem description

In Json_normalize if the metadata column is nullable with option errors set as ignore the null values in dataframe are literal nan string and not numpy.nan 

#### Expected Output
Expecting to see numpy.nan for null metadata string column values instead of nan string

Pandas version 0.24.1

**Comment by WillAyd** [comment]
Makes sense. Investigation and PRs are always welcome

**Comment by antoineviscardi** [comment]
Hi there, 

I can take care of this. Would we want this to be the only behavior or optional by introducing a new named parameter?

**Comment by WillAyd** [comment]
@antoineviscardi this should be the only behavior
