### ISSUE TITLE
"SpecificationError: nested dictionary is ambiguous in aggregation" in a certain case of groupby-aggregation

### ISSUE THREAD

**Issue by Khris777** [pandas-dev/pandas#25471]
All of these examples for using `agg` work fine:
```
import pandas as pd
df = pd.DataFrame({"A":['A','A','B','B','B'],
                   "B":[1,2,1,1,2],
                   "C":[9,8,7,6,5]})
df.groupby('A')[['B','C']].agg({'B':'sum','C':'count'})
df.groupby('A')[['B','C']].agg({'B':['sum','count'],'C':'count'})
df.groupby('A')[['B']].agg('sum')
df.groupby('A')['B'].agg('sum')
```
This one throws a future warning as mentioned [here](https://github.com/pandas-dev/pandas/pull/15931):
```
df.groupby('A')['B'].agg({'B':['sum','count']})
```
This one works just fine:
```
df.groupby('A')[['B','C']].agg({'B':'sum'})
```
But this one throws an error (I'm aware this expression isn't necessary):
```
df.groupby('A')[['B']].agg({'B':'sum'})
```
> SpecificationError: nested dictionary is ambiguous in aggregation

Why does it throw this error?

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 79 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: None.None

pandas: 0.24.1
pytest: 3.9.1
pip: 19.0.1
setuptools: 40.8.0
Cython: 0.29.5
numpy: 1.15.4
scipy: 1.2.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.8.4
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.9
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.9
feather: None
matplotlib: 3.0.2
openpyxl: 2.6.0
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.2
lxml.etree: 4.3.1
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.2.18
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: 0.2.1
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by TomAugspurger** [comment]
Not sure, probably a bug. If you're interested in debugging further, let us know.

**Comment by stuarteberg** [comment]
I can confirm in pandas 0.25.0.

These work fine:

```
In [27]: df = pd.DataFrame({'x': [1,1,2], 'y': [3,4,4]})

In [28]: df
Out[28]:
   x  y
0  1  3
1  1  4
2  2  4

In [29]: df.groupby('x').agg({'x': 'sum'})
Out[29]:
   x
x
1  2
2  2

In [30]: df.groupby('y').agg({'x': 'sum'})
Out[30]:
   x
y
3  1
4  3
```

But this raises an error:

```
In [31]: df.groupby('y')[['x']].agg({'x': 'sum'})

...

SpecificationError: nested dictionary is ambiguous in aggregation

```

And the `.agg()` call only requires a single column, but you provide more than one column when you select columns from the `groupby`, then you get a weird result. (Why does the result below include a `y` column at all?)

```
In [34]: df.groupby('y')[['x', 'y']].agg({'x': 'sum'})
Out[34]:
   x
   x  y
y
3  1  3
4  3  8
```

**Comment by SaiSridhar783** [comment]
df.groupby('A')['B'].agg({'B':['sum','count']})

Here, the column 'B' is returned as a series so aggregation is not possible.

**Comment by mroeschke** [comment]
Looks to work on master now. Could use a test

```
In [26]: import pandas as pd
    ...: df = pd.DataFrame({"A":['A','A','B','B','B'],
    ...:                    "B":[1,2,1,1,2],
    ...:                    "C":[9,8,7,6,5]})

In [27]: df.groupby('A')[['B']].agg({'B':'sum'})
Out[27]:
   B
A
A  3
B  4
```

**Comment by lakmalpin** [comment]
We are a university team looking for a good first issue.

**Comment by talukder-sowrov** [comment]
We are a university team looking for a good first issue.

**Comment by talukder-sowrov** [comment]
Take
