### ISSUE TITLE
Typo in release page link

### ISSUE THREAD

**Issue by javad94** [pandas-dev/pandas#25470]
#### Problem description
There is a typo in *full whatsnew* link in [pandas 0.24.1 release page](https://github.com/pandas-dev/pandas/releases/tag/v0.24.1) that point to [this page](http://pandas.pydata.org/pandas-docs/version/0.24.2/whatsnew/v0.24.2.html) which doesn't exist.

#### Expected Output
It should point to:
http://pandas.pydata.org/pandas-docs/version/0.24.1/whatsnew/v0.24.1.html

**Comment by WillAyd** [comment]
Thanks for calling this out. @TomAugspurger OK to just edit that here in GH or does that have other implications?

**Comment by javad94** [comment]
Your welcome. Thanks for your pandas :)

**Comment by TomAugspurger** [comment]
In the past, editing the release description changed the SHA of the release generated by GitHub, which broke our conda-forge builds. In theory, we should be OK now that the release manager uploads their own locally built sdist, which shouldn't change.

So if you're feeling adventurous, go for it :)

**Comment by WillAyd** [comment]
Feeling lucky today - I'll give it a shot in say an hour unless any objections

**Comment by WillAyd** [comment]
Just changed this @javad94 if you'd like to confirm. Will keep open for a few days to make sure no unknown impacts

**Comment by javad94** [comment]
I can confirm it's ok now. Thanks.
