### ISSUE TITLE
New Feature Request: df.style.hide_index() to hide a particular index level

### ISSUE THREAD

**Issue by samcha1996** [pandas-dev/pandas#25475]
#### Problem description

The present implementation of `df.style.hide_index()` removes the complete index while rendering html. 
It would be better to have an optional input of index level and hide only that index level while rendering.
example  `df.style.hide_index(level=1)`
It provides more option and flexibility to user. 

 Sorry to post this as an issue, but I didn't find any option for suggesting new features.

**Comment by TomAugspurger** [comment]
> Sorry to post this as an issue, but I didn't find any option for suggesting new features.

An issue is fine for feature requests, but we need a simple example what the request is.

**Comment by sambhavcha** [comment]
```
In[15]: df
Out[15]: 
                0         1         2         3
bar1 one  0.624257 -1.919695 -0.608513  1.460487
bar2 two -0.609755  0.874438  0.169402 -1.236653
baz1 one  0.694922  0.585993 -0.871894 -0.240299
baz2 two -0.158941 -1.604056 -0.517174  0.551289
foo1 one -1.606837  1.009960 -1.026319  1.377517
foo2 two -1.062810 -0.041552 -0.423098  0.438010
qux1 one  1.082581  0.182992 -1.910832  0.156215
foo2 two -0.255548  0.419918 -0.668972 -0.586820
```
Now doing df.style.hide_index().set_table_attributes('border=1').render() and opening in browser gives 
`https://www.w3schools.com/code/tryit.asp?filename=G1MGWU5COD4H`. 
Open the link and press run.

I want that there should be an option for level in hide_index() like 
`df.style.hide_index(level=1).set_table_attributes('border=1').render()` which gives output like 
`https://www.w3schools.com/code/tryit.asp?filename=G1MH0SRAWPMS`
Open the link and press run.

**Comment by TomAugspurger** [comment]
Thanks. Note that MultiIndex support in `.style` is pretty limited right now. It doesn't look especially easy to add this to the current implementation.

**Comment by sambhavcha** [comment]
Okay. Just thought that it would be a good to have feature in pandas.style .
Thanks

**Comment by TomAugspurger** [comment]
Indeed. Let us know if you're interested in working on it.

**Comment by sambhavcha** [comment]
Yeah of course i would love to work on it. And I would also like to know more about the implementations of pandas too.

**Comment by TomAugspurger** [comment]
OK, it's all at
https://github.com/pandas-dev/pandas/blob/master/pandas/io/formats/style.py
and
http://pandas-docs.github.io/pandas-docs-travis/development/contributing.html
has the contributing guide. Let us know where you get stuck.

**Comment by sambhavcha** [comment]
Great. Thanks for the quick response.
