### ISSUE TITLE
value_counts() counting wrong categories

### ISSUE THREAD

**Issue by npfernandeztheillet** [pandas-dev/pandas#25476]
#### Code Sample, a copy-pastable example if possible

```python
def getHourOfTime(myString):
    return int(myString[0:2:1])

import pandas as pd    
import numpy as np   
e = np.random.randint(24, size=100)  
e_dataframe = pd.DataFrame(e)      
e_dataframe = e_dataframe.rename(index=str, columns={0:'Time_x'})


x=e_dataframe
x['hour'] = e_dataframe['Time_x'].dropna().apply(lambda x: getHourOfTime(str(x)))

display(x['hour'].head(10))

x['TimeCategory']= pd.cut(x['hour'],bins=[0,6, 9, 16, 19, 24], 
                   labels=['MORNING', 'MPH', 'DAY', 'EPH', 'NIGHT'],
                   include_lowest=True)

x['TimeCategory'] = x['TimeCategory'].replace('MORNING', 'NIGHT')

fdf = x[x['TimeCategory'] != 'MORNING']

display(x[x['TimeCategory'] != 'MORNING'].head(5))

fdf['TimeCategory'].value_counts()

```
#### Problem description
After replace, value_counts() count MORNING category label

DAY        59046
EPH        29039
NIGHT      25687
MPH        22847
MORNING        0

  | Time_x | hour | TimeCategory
-- | -- | -- | --
14 | 14 | DAY
23 | 23 | NIGHT
11 | 11 | DAY
1 | 1 | NIGHT
7 | 7 | MPH

I have install all the latest versions of panda, numpy, jupyter notebooks, et.c

#### Expected Output

DAY        59046
EPH        29039
NIGHT      25687
MPH        22847

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
NSTALLED VERSIONS
------------------
commit: None
python: 3.7.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.4
pytest: 4.0.2
pip: 18.1
setuptools: 40.6.3
Cython: 0.29.2
numpy: 1.15.4
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.8.2
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.2
openpyxl: 2.5.12
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.2
lxml: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by TomAugspurger** [comment]
Looks like `dfmerged` isn't reproducible. See http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports for help with writing bug reports.

You can also delete the rest of the issue template, after filling out the expected output..

**Comment by mroeschke** [comment]
Feel free to reopen when you can posted a reproducible example.
