### ISSUE TITLE
read_excel from jupyter notebook for file in github

### ISSUE THREAD

**Issue by ItsMeLarry** [pandas-dev/pandas#25489]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

```
#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by gfyoung** [comment]
@ItsMeLarry : Thanks for opening the issue!  Do you mind explaining more what you're trying to do, and if possible, share any relevant code?

**Comment by WillAyd** [comment]
This looks like maybe an errant issue given it's just the template (?)

Closing as a result though feel free to reopen if there is actually something awry

**Comment by ItsMeLarry** [comment]
Something is wrong someplace.  I have other things to do right now, but
will provide info requested by gfyoung.  Simply, the code I used to
download from FBI UCR space, as well as other code, failed when I attempted
same thing from Github.  I'm sure it is something about my own space in
Github, but I am clueless at the moment.  Will be back later today.
Larry

**Comment by ItsMeLarry** [comment]
I successfully downloaded a number of xls files from FBI site, then ran into trouble trying to download from Github.  A little more background: I needed data from Census, but couldn't find place to copy URLs for files, so did their auto-download to my desktop, then uploaded from my desktop to Github.  Couldn't load into Jupyter Notebook from desktop directly because of another issue about Jupyter acting like it was partitioning my disk.  That's another problem I'm pursuing.  So, here's the code:

dls = "https://github.com/ItsMeLarry/Coursera_Capstone/blob/master/five.xls"
resp = requests.get(dls)
output = open('five.xls', 'wb')
output.write(resp.content)
chkthis=pd.read_excel('five.xls',sheet_name=0,index_col=False)
chkthis.head()

The error message:
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'\n\n\n\n\n\n<!'

Good luck.  And thanks.

**Comment by TomAugspurger** [comment]
You probably want the "raw" link for binaries from Github:
https://github.com/ItsMeLarry/Coursera_Capstone/blob/master/five.xls?raw=true

FYI, we usually steer usage questions to StackOverflow since search engines
typically find them better than GitHub issues (which we use for bug reports
/ feature requests).

**Comment by ItsMeLarry** [comment]
Aha!!!  I just got it to work!  Do the Ctl-Click and copy at the 'download' button on 'Read Raw' page, and get the URL that works.  The difference is directory "Raw" instead of "blob".  Frabjous Day!

Neva mind.
