### ISSUE TITLE
 module 'pandas.tseries' has no attribute 'index'

### ISSUE THREAD

**Issue by GavinMoreYoung** [pandas-dev/pandas#25493]
#### version
python:3.6.8
tstables 0.0.15
pandas:0.24.1

#### code 
h5.close()
import tstables as tstab
class ts_desc(tb.IsDescription):
    timestamp = tb.Int64Col(pos=0)  
    ts1 = tb.Float64Col(pos=1)  
    ts2 = tb.Float64Col(pos=2)  
    ts3 = tb.Float64Col(pos=3)  
h5 = tb.open_file(path + 'tstab.h5', 'w')   
ts = h5.create_ts('/', 'ts', ts_desc)  
%time ts.append(df)  

#### Problem description
AttributeError                            Traceback (most recent call last)
<timed eval> in <module>

c:\users\admin\.virtualenvs\python_for_finance_mastering_data_driven_f-hf8uuk7i\lib\site-packages\tstables\tstable.py in append(self, rows, convert_strings)
    237             if rows.empty:
    238                 return # Do nothing if we are appending nothing
--> 239             if rows.index.__class__ != pandas.tseries.index.DatetimeIndex:
    240                 raise ValueError('when rows is a DataFrame, the index must be a DatetimeIndex.')
    241 

AttributeError: module 'pandas.tseries' has no attribute 'index'

I can not solve it, i hope your help, thanks.

**Comment by WillAyd** [comment]
Your traceback implies this is an issue with tstables, so best to open as an issue on their tracker

**Comment by Salman412412** [comment]
You should use this code before your first import:
`pip install git+https://github.com/yhilpisch/tstables.git`
with this version of tstables, your code works well.

**Comment by GavinMoreYoung** [comment]
收到，会尽快给您回复。
