### ISSUE TITLE
BUG: DataFrame.apply() returns  something strange if use str as a function. Series works fine.

### ISSUE THREAD

**Issue by mahajrod** [pandas-dev/pandas#25494]
#### Code Sample, a copy-pastable example if possible

```python
tttt = pd.DataFrame([5,6,7])
tttt.apply(str)

```
#### Problem description

Output is very strange:
0    0    5\n1    6\n2    7\nName: 0, dtype: int64
dtype: object

#### Expected Output
DataFrame of strings
#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-139-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.24.1
pytest: None
pip: 18.0
setuptools: 24.3.0
Cython: 0.28.3
numpy: 1.13.0
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: 5.1.0
sphinx: None
patsy: 0.5.0
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: 0.9999999
sqlalchemy: 1.2.10
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by chris-b1** [comment]
This is working as expected - `DataFrame.apply` by default goes column by column, so what you've written is the same as `str(pd.Series([5, 6, 7])`
