### ISSUE TITLE
(api) function names: pct_change, diff

### ISSUE THREAD

**Issue by hottwaj** [pandas-dev/pandas#25500]
Hi, first of all thanks for the amazing library everyone!

This is a minor issue I'm sure, but I find it impossible to remember the name of the `.pct_change()` function.

Partly this is because of confusion with the existing .diff() function which is easy to remember - I always try things like:
- pctdiff()
- pct_diff()
- percent_diff()

Normally after a couple of goes I admit defeat and Google it yet again :)

So this is a request for an additional function with the name `.pct_diff()` (or whatever spelling is preferred) that replicates/calls `.pct_change()`, in order to standardise the API.

Thanks!

**Comment by chris-b1** [comment]
This is where tab-completion can be very useful!  So that's one thing to consider, is your IDE/whatever setup.

In general we try (with mixed success) to follow the python there should only be one way to do things idea - so don't love having duplicate functions.  You could always monkey-patch what you want.

```python
import pandas as pd
pd.DataFrame.pct_diff = pd.DataFrame.pct_change
pd.Series.pct_diff = pd.DataFrame.pct_change

s = pd.Series([1, 1.1, 1.2])
s.pct_diff()
Out[225]: 
0         NaN
1    0.100000
2    0.090909
dtype: float64
```

**Comment by hottwaj** [comment]
Good suggestion, thanks!

**Comment by WillAyd** [comment]
Somewhat related (though not directly) to the conversation in #20752 . This has been around some time and I'm not sure there is much to gain from a change here, much like was stated in the linked discussion

**Comment by mroeschke** [comment]
Agreed that this function has been around for a while and probably not worth aliasing and undergoing churn for users.

Since there hasn't been much other support for this deprecation, closing. Happy to reopen if there's renewed interest
