### ISSUE TITLE
BLD: numpy 1.16.1 failing builds

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#25511]
looks like our builds are failing as we are now picking up numpy 1.16.1; I belive 1.16.2 fixes this, so once this is fully pushed should be ok.

These failures manifest with pytables. https://travis-ci.org/pandas-dev/pandas/jobs/500453356

cc @pandas-dev/pandas-core 

let's hold off merging for now / we could simply pin numpy=1.15.* as well (again for now), if someone wants to do this.

**Comment by gfyoung** [comment]
People were already noticing this issue back in #24839.

**Comment by jreback** [comment]
I understand, but our master builds just picked this up. I suspect because now all packages are actually available for numpy 1.16 (which wasn't the case before; this takes some time, esp in default)

**Comment by gfyoung** [comment]
@jreback : Right.  I just wanted to link this issue to that one for reference.

**Comment by gfyoung** [comment]
`1.16.2` is available via the `conda-forge` <a href="https://anaconda.org/conda-forge/numpy">channel</a>
