### ISSUE TITLE
Data dependent bug in mode aggregation

### ISSUE THREAD

**Issue by DavidMertz** [pandas-dev/pandas#25527]
#### Code Sample, a copy-pastable example if possible

The first line is the problem, the others given for context.  My goal in the function this comes from is to remove non-modal ("atypical") items per `key`.  The task should, and does, allow multi-modal targets per group (there are other techniques to pick a unique, but arbitrary mode, but I want all of them).

```python
# Your code here
modes = pd.DataFrame(df.groupby('key').value.agg(pd.Series.mode))
df.set_index('key', inplace=True)
df = df.join(modes, rsuffix='_mode')
df = df[df.apply(lambda row:row.value in row.value_mode, axis=1)]
```

The below uses a DataFrame smaller than the one where the problem was encountered.  As discussed in a comment below, the precise sampling of the original data and the precise anonymization of groupby keys used has an unpredictable effect on the problem being accidentally fixed or continuing to occur.

```python
>>> import pandas as pd
>>> import gzip
>>> import pickle
>>> df = pickle.load(gzip.open('modal-crash.pkl.gz'))
>>> modes = df.groupby('key').value.agg(pd.Series.mode)
Traceback (most recent call last):
  File "<ipython-input-13-4fe1f0dd3977>", line 1, in <module>
    modes = df.groupby('key').value.agg(pd.Series.mode)
  File "/anaconda3/envs/boldmetrics-analysis/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 778, in aggregate
    result = self._aggregate_named(func_or_funcs, *args, **kwargs)
  File "/anaconda3/envs/boldmetrics-analysis/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 909, in _aggregate_named
    raise Exception('Must produce aggregated value')
Exception: Must produce aggregated value

```

[modal-crash.pkl.gz](https://github.com/pandas-dev/pandas/files/2923871/modal-crash.pkl.gz)

#### Problem description

In a manner sensitive to the exact data, but not following any obvious pattern I have discerned, the `modes = ...` line can produce 3-4 levels of nested exceptions leading to `Exception: Must produce aggregated value`.

I have checked the "problem" data to make sure there are no missing values in `df.value`.  All values are present and are an expected (string) value.  This particular task has to do with a target that is a clothing size.  E.g. when run correctly, `modes` will resemble this:

```
             value
key
ddhhmttmvv   [L, M]
dfdavpqthh      [S]
ddfadjqqhd      [M]
ddvjmatfvm      [M]
... 160k more rows ...
```

The code succeeds for **most** initial DataFrames.  In fact, adding `df = df.iloc[:-1]` or `df = df.iloc[1:]` makes the operation succeed for every "problem" DataFrame I have encountered.

I have identified a hack/fix to the problem, but it's ad hoc and ugly:

```python
def mode(s):
    return list(pd.Series.mode(s))
modes = pd.DataFrame(df.groupby('key').value.agg(mode))
```

#### Expected Output

Expected output shown in the problem description.  The DataFrame generated after the filtering is just a subset of rows in the original, but the problem only occurs in finding the mode per group.

#### Output of ``pd.show_versions()``

<details>
% python -c "import pandas; pandas.show_versions()"
/anaconda3/envs/boldmetrics-analysis/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1.final.0
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.1
pytest: None
pip: 19.0.3
setuptools: 40.8.0
Cython: 0.29.5
numpy: 1.16.1
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.3.0
sphinx: 1.8.4
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: 2.6.9
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: 4.3.1
bs4: None
html5lib: None
sqlalchemy: 1.2.18
pymysql: None
psycopg2: 2.7.7 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by mroeschke** [comment]
We would need a reproducible (copy-pasteable) example to help identify the potential issue (and eventually unit test) http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by DavidMertz** [comment]
Yes, I recognize the deficit in the details. I have encountered the error several times, but always on large and confidential data. I'm hoping someone experienced in Pandas might have some ideas on how to go about replicating it on a small artificial DataFrame.

It's really unclear to me what properties the DataFrames I tried have that cause the error. Any ideas where to look?

**Comment by DavidMertz** [comment]
Here's some confusing details.  The crash is dependent on the specific **values** of the `.groupby()` column.  Not just their types, but the values.  My example has integers I am grouping by.  I was trying to prepare an anonymized version of the data, and that accidentally fixes the problem:

```python
>>> df = sklearn.externals.joblib.load('modal-crash.joblib')[['_member_key','TARGET']]
>>> try:
...     modes = pd.DataFrame(df.groupby('_member_key').TARGET.agg(pd.Series.mode))
... except Exception as err:
...     print(err)
...
Must produce aggregated value
>>> len(df._member_key.unique())
8017
>>> df['_member_key'] = df._member_key % 1234567890
>>> len(df._member_key.unique())
8017
>>> # The translated keys remain distinct, no collision
>>> try:
...     modes = pd.DataFrame(df.groupby('_member_key').TARGET.agg(pd.Series.mode))
... except Exception as err:
...     print(err)
...
>>> df.head(3)
   _member_key TARGET
0   1133588599      M
1   1133588599      M
2   1133588599      M
```

**Comment by DavidMertz** [comment]
@mroeschke ... OK, as I mention in comment above, **some** modifications of the groupby column make the error disappear, while other modifications do not resolve it.  I tried a variety of add/multiply/modulo/divide/etc of the integer keys, and see no obvious pattern of what fixes the problem and what does not.

I *do* feel that I need to obscure the keys that relate to a particular client (possibly in an abundance of caution since the member numbers are not inherently meaningful.  Simply converting the integers to strings keeps the problem I'm trying to replicate.  And *some* modifications of those strings make the problem go away while other modifications keep the problem.  Again, no obvious pattern.

Continuing that, *some* subselection of rows to get a smaller working DataFrame resolve the problem, while others retain the problem.  It is also not at all obvious what that pattern is.  I took every tenth row for the attached data; if I took every 15th the issue is somehow fixed, as it is if I take every tenth but exclude the first few thousand to reduce the size.  I am certain what is attached is not the *minimal* possible demonstration, but it is a reproducible demonstration.

```python
>>> import pandas as pd
>>> import gzip
>>> import pickle
>>> df = pickle.load(gzip.open('modal-crash.pkl.gz'))
>>> modes = pd.DataFrame(df.groupby('key').value.agg(pd.Series.mode))
Traceback (most recent call last):
  File "<ipython-input-11-e565c12aa473>", line 1, in <module>
    modes = pd.DataFrame(df.groupby('key').value.agg(pd.Series.mode))
  File "/anaconda3/envs/boldmetrics-analysis/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 778, in aggregate
    result = self._aggregate_named(func_or_funcs, *args, **kwargs)
  File "/anaconda3/envs/boldmetrics-analysis/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 909, in _aggregate_named
    raise Exception('Must produce aggregated value')
Exception: Must produce aggregated value
```

[modal-crash.pkl.gz](https://github.com/pandas-dev/pandas/files/2923871/modal-crash.pkl.gz)

**Comment by neonfuzz** [comment]
This is also affecting me with no immediately obvious pattern.

I made some test code that has a _very high_ probability of failing (~90%). When changing `make_name` to use `string.ascii_letters` instead of `string.printable` the code still fails, but less often. I would wager that there are multiple bugs present, but one of them has to do with special characters in the `groupby` Series (here `'name'`).

```
import string

import numpy as np
import pandas as pd


N_USERS = 150000
N_SAMPLES = 2 * N_USERS
N_CATEGORIES = 10


def make_name(length=20):
    chars = np.random.choice(list(string.printable), length)
    return ''.join(chars)


names = [make_name() for _ in range(N_USERS)]
idx = pd.Index(np.random.choice(names, N_SAMPLES), name='name')
samples = np.random.randint(0, N_CATEGORIES, N_SAMPLES)
df = pd.DataFrame(samples, index=idx)

df.groupby('name').agg(pd.Series.mode)
```

**Comment by neonfuzz** [comment]
In an update:

I ran the posted code in a clean instance of ipython, and it worked just fine _every time_. I started a new instance and it went back to failing ~90% of the time. I have _no idea_ what that means, but it's a data point?

Also after a little testing, the code above seems to **work** about 90% of the time it's run for the _first time_. After that it seems to **fail** about 90% of the time. Except sometimes it just **works** 100% of the time.

**Comment by jreback** [comment]
so this is reproucible if you add ``np.random.seed(0)`` for example.

the issue is that if you have groups of size 1 this would return a different sized result

```
In [30]: g = df.groupby('name')                                                                                                                                                                                                                                                    

In [31]: g_filtered = df.groupby('name').filter(lambda x: len(x) ==1).groupby('name')                                                                                                                                                                                              

In [32]: g.agg(Series.mode)                                                                                                                                                                                                                                                        
Exception: Must produce aggregated value

In [33]: g_filtered.agg(Series.mode)                                                                                                                                                                                                                                               
Out[33]: 
                         0
name                      
\t\tS(e`I_bZ`M4<&=T+#9   2
\t\tU s'y:*G0HWKgxuyg0   3
\t\tVJ{!mA884I\r}v[YXO0  0
\t\t}g$\n%t-o8L p9+&Gdv  4
\t\n\t;y@Z`fV\1]+6U}a23  2
...                     ..
~}:pTaDj6S"i%%k/g{_M     6
~}F;Q\nzjk=>d}i>!$pPK    4
~}G@%@sGchumTtVRNt\r(    3
~}\1nV,*_5Y7'f"/o<e!     2
~~|rJWG$V/!ibL?n2M4Y     2

[40808 rows x 1 columns]
```
so you can do ``df.groupby('name').apply(lambda x: Series.mode(x)[0])``

or *much* better (and way faster)

```
In [35]: g[0].value_counts()                                                                                                                                                                                                                                                       
Out[35]: 
name                     0
\t\t
VEbY%Xy"OD<{g:OYQ   0    1
                         2    1
                         6    1
\t\t )b0=(x((F7J\t`.SG>  6    1
                         9    1
                             ..
~~nQ29d>-bPi3  @(3|1     5    1
~~pO{hP%'_~rB4L5N!1L     1    1
                         3    1
                         9    1
~~|rJWG$V/!ibL?n2M4Y     2    1
Name: 0, Length: 271873, dtype: int64
```
