### ISSUE TITLE
uploading data into dataframe

### ISSUE THREAD

**Issue by eswara3202** [pandas-dev/pandas#25522]
#### Code Sample as entered in jupyter notebook with python 3.7 
---------------------------------------------------------------------
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
df = pd.read_csv('tstdatapanda.csv', delimiter=',', encoding="utf-8-sig")

X = df['sensex','nifty']
y = df['Last_Trade_Price']
X
--------------------------------------------------------
#### Problem description
i am unable to display X it gives the below error
--------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
D:\python\base.py in get_loc(self, key, method, tolerance)
   3077             try:
-> 3078                 return self._engine.get_loc(key)
   3079             except KeyError:

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: ('sensex', 'nifty')

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-1-5ee89fa30c8d> in <module>
      4 df = pd.read_csv('tstdatapanda.csv', delimiter=',', encoding="utf-8-sig")
      5 #df.drop_duplicates(subset=['S', 'T'])
----> 6 X = df['sensex','nifty']
      7 y = df['nifty']
      8 #X1.drop_duplicates(keep=False)

D:\em\education\python\anaconda\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   2686             return self._getitem_multilevel(key)
   2687         else:
-> 2688             return self._getitem_column(key)
   2689 
   2690     def _getitem_column(self, key):

D:\em\education\python\anaconda\lib\site-packages\pandas\core\frame.py in _getitem_column(self, key)
   2693         # get column
   2694         if self.columns.is_unique:
-> 2695             return self._get_item_cache(key)
   2696 
   2697         # duplicate columns & possible reduce dimensionality

D:\em\education\python\anaconda\lib\site-packages\pandas\core\generic.py in _get_item_cache(self, item)
   2487         res = cache.get(item)
   2488         if res is None:
-> 2489             values = self._data.get(item)
   2490             res = self._box_item_values(item, values)
   2491             cache[item] = res

D:\em\education\python\anaconda\lib\site-packages\pandas\core\internals.py in get(self, item, fastpath)
   4113 
   4114             if not isna(item):
-> 4115                 loc = self.items.get_loc(item)
   4116             else:
   4117                 indexer = np.arange(len(self.items))[isna(self.items)]

D:\em\education\python\anaconda\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3078                 return self._engine.get_loc(key)
   3079             except KeyError:
-> 3080                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   3081 
   3082         indexer = self.get_indexer([key], method=method, tolerance=tolerance)

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: ('sensex', 'nifty')
----------------------------------------------------------------------------------------------------

#### Output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.4
pytest: 4.0.2
pip: 18.1
setuptools: 40.6.3
Cython: 0.29.2
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.8.2
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.2
openpyxl: 2.5.12
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.2
lxml: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

[tstdatapanda.zip](https://github.com/pandas-dev/pandas/files/2923280/tstdatapanda.zip)

**Comment by TomAugspurger** [comment]
Hard to say without a minimal example, but I believe you want `X = df[['sensex','nifty']]` (notice the double square brackets) to select the two columns. Otherwise, you're trying to select a single column with the label `('sensex', 'nifty')`.

**Comment by eswara3202** [comment]
Got it, thanks a lot Tom
