### ISSUE TITLE
read_excel only loading first 11 rows

### ISSUE THREAD

**Issue by ksap1** [pandas-dev/pandas#25539]
```python
# data = read_excel(data.xlsx, nrows=100)

```
#### Problem description

I'm currently trying to open a 46 MB xlsx file with around 1700 rows and 26 columns. Everytime I load the dataset through read_excel, the DataFrame only contains 11 rows. I've tried this on multiple ipython notebooks with the same problem. Even loading specific sizes (nrows) of the dataset only results with 11 rows being loaded. Is this a common bug? Am I missing something?

**Comment by ksap1** [comment]
I used the following notebooks: Jupyter, Google Colaboratory

**Comment by WillAyd** [comment]
That seems like an inordinantly large file given the dimensions. In any case would need a small sample file to reproduce the issue

**Comment by TomAugspurger** [comment]
@ksap1 can you provide a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by ksap1** [comment]
There were multiple sheets in the file which I didn't realize. This required the use of ExcelFile() which fixed my problem.
