### ISSUE TITLE
DOC: Make the sidebar index more useful in the docs

### ISSUE THREAD

**Issue by dpitch40** [pandas-dev/pandas#25534]
My team recently upgraded the version of Pandas we use, and while the improved functionality of the module itself is great, I'm finding the docs annoying to use. Previously the sidebar index showed (if anything) too much; now it shows too little. Compare, for example, the Essential Basic Functionality docs in [0.20.3](http://pandas.pydata.org/pandas-docs/version/0.20/basics.html) vs. [0.24.0](http://pandas.pydata.org/pandas-docs/version/0.24/getting_started/basics.html). The 0.20.3 version is a little long, but makes it fairly easy to navigate to any part of the lengthy page to find the section you need. The index for 0.24.0, only shows links that were already on the front page and is virtually useless for navigating the page I find myself in.

On the other hand, the index for the [0.20.3 API Reference doc page](http://pandas.pydata.org/pandas-docs/version/0.20/api.html) is actually longer than the page itself (at least on my browser, due to wrapping) and thus equally useless for navigation, and I find the [0.24.0 version](http://pandas.pydata.org/pandas-docs/version/0.24/reference/index.html) more useful.

Surely there is a happy medium between showing too little in the sidebar index and showing too much. I expect I'll be continuing to refer to the Pandas docs on a daily basis for the foreseeable future, and the sidebar could be making them much easier to navigate than they currently are.

**Comment by TomAugspurger** [comment]
We have another issue for this. Can you search for duplicates, close this
one, and add your comment there?
