### ISSUE TITLE
Plotting: secondary y axis can not be set to log scale

### ISSUE THREAD

**Issue by johan12345** [pandas-dev/pandas#25545]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.Series(np.random.random(1000)).plot(logy=True)
pd.Series(np.random.random(1000)).plot(secondary_y=True, logy=True)
plt.show()
```

#### Problem description

When I plot some data and set both the `secondary_y` and `logy` parameters to `True`, the `logy` parameter is not respected. Instead, the secondary y axis still uses linear scaling.

![logtest](https://user-images.githubusercontent.com/5310424/53807388-bb5e5a80-3f4f-11e9-8ae5-a897961ef821.png)

#### Expected Output

The secondary y axis should use logarithmic scaling.

![logtest](https://user-images.githubusercontent.com/5310424/53807551-29a31d00-3f50-11e9-8db0-8300dcb61013.png)

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.19.0-2-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8
LOCALE: de_DE.UTF-8
pandas: 0.24.1
pytest: 4.1.1
pip: 18.1
setuptools: 40.6.3
Cython: None
numpy: 1.16.1
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 5.8.0
sphinx: 1.8.3
patsy: None
dateutil: 2.7.3
pytz: 2018.9
blosc: None
bottleneck: None
tables: 3.4.4
numexpr: 2.6.9
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: 4.3.1
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by TomAugspurger** [comment]
Thanks for the report. Interested in working on a fix?

**Comment by johan12345** [comment]
Yep, I'll have a look in the next few days :)
