### ISSUE TITLE
DOC: more specific str.split() explanation

### ISSUE THREAD

**Issue by RuMcClu** [pandas-dev/pandas#25549]
In the docs we see:
![screen shot 2019-03-05 at 14 17 32](https://user-images.githubusercontent.com/16627482/53811498-73403780-3f51-11e9-9591-8489096218b1.png)
but in fact the default behaviour of `str.split()` is more complicated than using `str.split(" ")` as detailed in the [python 3 documentation](https://docs.python.org/3/library/stdtypes.html#str.split). Perhaps linking to this explanation of the splitting algorithm would be preferable or writing something slightly more verbose would be preferable? Even saying "consecutive  whitespace" would probably be enough.

**Comment by TomAugspurger** [comment]
The docs do contain a link to str.split under the "See Also":
http://pandas-docs.github.io/pandas-docs-travis/reference/api/pandas.Series.str.split.html?highlight=str.split#pandas.Series.str.split

Does that suffice?

**Comment by davidwales** [comment]
I think this is a code issue, rather than a docs issue. The docs describe the way the code should work, but it doesn't quite work that way. As I mentioned in #32835, the problem may be summarised as follows:

> [Looking at the code](https://github.com/pandas-dev/pandas/blob/v1.0.3/pandas/core/strings.py#L1479-L1496), the current (undocumented) logic is:
> 
> - If the pattern is `None`, or has length 1, it's a string split.
> - Else it's a regex split.
> 
> However, the Python built-in `str.split` function accepts string patterns with length greater than 1, and doesn't accept regex patterns at all. Updating the function to include a `regex=True/False` argument would make this explicit, and allow string splits on delimiters with length greater than 1.

**Comment by markopy** [comment]
Was bitten by this too when using a string as separator with `Series.str.split()`. The documentation explicitly claims it is equivalent to python's `split()` which is obviously not true. Pandas treats any separator with more than one character as regular expression. Python uses the literal string.

+1 for adding a `regex=True/False` parameter. Or at least updating the docs and removing the "equivalent to python's split()" claim.
