### ISSUE TITLE
pd.concat removes column names when not using index

### ISSUE THREAD

**Issue by david-cortes** [pandas-dev/pandas#25547]
If I merge two data frames by columns ignoring the indexes, it seems the column names get lost on the resulting object, being replaced instead by integers. Example:
```python
import numpy as np, pandas as pd

np.random.seed(1)
df1 = pd.DataFrame(np.random.random(size = (10,5)), columns = ['col1', 'col2', 'col3', 'col4', 'col5'])
df2 = pd.DataFrame(np.random.poisson(5, size = (10, 3)), columns = ['cl1', 'cl2', 'cl3'])
df2 = pd.concat([df2, df1], axis = 1, ignore_index = True)
df2.columns
```
Returns:
```RangeIndex(start=0, stop=8, step=1)```

When using `ignore_index = False` however, the column names remain in the merged object:
```python
import numpy as np, pandas as pd

np.random.seed(1)
df1 = pd.DataFrame(np.random.random(size = (10,5)), columns = ['col1', 'col2', 'col3', 'col4', 'col5'])
df2 = pd.DataFrame(np.random.poisson(5, size = (10, 3)), columns = ['cl1', 'cl2', 'cl3'])
df2 = pd.concat([df2, df1], axis = 1, ignore_index = False)
df2.columns
```
Returns:
```Index(['cl1', 'cl2', 'cl3', 'col1', 'col2', 'col3', 'col4', 'col5'], dtype='object')```

**Comment by TomAugspurger** [comment]
That's the meaning of `ignore_index` in http://pandas-docs.github.io/pandas-docs-travis/reference/api/pandas.concat.html?highlight=concat

> If True, do not use the index values along the concatenation axis. The resulting axis will be labeled 0, …, n - 1. This is useful if you are concatenating objects where the concatenation axis does not have meaningful indexing information. Note the index values on the other axes are still respected in the join.

You're the second person to run into this recently. What about the documentation did you find unclear?

**Comment by david-cortes** [comment]
Oh sorry, hadn't noticed the part about _concatenation_ index in the documentation. Although I think it would be nice if there were an option that would be equivalent to reseting the indexes (`df.index`) in each input before concatenating - at least for me, that's what I usually want to do when using `concat` rather than `merge`.
