### ISSUE TITLE
Design of DataFrame.where() is potentially counter-intuitive

### ISSUE THREAD

**Issue by scwilkinson** [pandas-dev/pandas#25552]
#### Code Sample

```python
>>> s = pd.Series(range(5))
>>> s.where(s > 1, 10)
0    10
1    10
2    2
3    3
4    4
dtype: int64
```
#### Problem description

This is a purely design-related issue!

I think that the behavior of the `DataFrame.where()` is potentially confusing, and can easily be misunderstood. The core of the issue is the use of the `other` parameter. 

The behavior when `other`  is set by the user can be confusing,

```python
>>> s = pd.Series(range(5))
>>> s.where(s > 1, 10)
0    10
1    10
2    2
3    3
4    4
dtype: int64
```

Reading `s.where(s > 1, 10)`, I think the logical way to read that, or to use a function called `.where()`, is:

> Replace values in `s` where `s > 1` is `True` with `10`

While the proper use of `other` may make sense if you're fully familiar with the default behavior of `.where()`, it can be confusing to those reading it for the first time.

I think this boils down to the function being,

> Replace values where the condition is **False**

Instead of,

> Replace values where the condition is **True**

which I think is the expected behavior based on the function name.

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

#### Expected Output

Changing the behavior of `.where()` to be:

> Replace values where the condition is **True**

This would then give,

```python
>>> s = pd.Series(range(5))
>>> s.where(s > 1, 10)
0    0
1    1
2    10
3    10
4    10
dtype: int64
```

So, to replicate the output of the initial snippet,

```python
>>> s = pd.Series(range(5))
>>> s.where(s < 2, 10)
0    10
1    10
2    2
3    3
4    4
dtype: int64
```

#### Output of ``pd.show_versions()``

Not applicable

**Comment by TomAugspurger** [comment]
Are you familiar with `numpy.where`?

We won't be changing this, but I'd be happy to see proposed improvements to the documentation.

**Comment by scwilkinson** [comment]
I am, and I would argue that the desire to match the behavior of `numpy.where()` exactly results in a great degree of confusion.

The way it's constructed in numpy is to be used explicitly,

`numpy.where(cond, x, y)`

Which logically reads as,

```python
if cond is True:
    return x
else:
    return y
```

I would argue that the pandas is more implicit,

`DataFrame.where(cond, other)`

I think this logically reads as,

```python
if cond is True
    return other
else:
    return <DataFrame value>
```

I think the logical way to read arguments is,

```
function(cond, <True value>, <False value>)
```

And this is what numpy implements.

The pandas implementation forces you to read this as,

```
function(cond, <False value>)
```

I think that the result is that `DataFrame.where(cond, other)` as currently implemented is very difficult to read.

**Comment by scwilkinson** [comment]
@TomAugspurger What about a new method, perhaps `where_true`, with the behavior that I've described?

```
>>> s = pd.Series(range(5))
>>> s.where_true(s > 1)
0    0
1    1
2    NaN
3    NaN
4    NaN
dtype: int64
>>> s.where_true(s > 1, 10)
0    0
1    1
2    10
3    10
4    10
dtype: int64
```

**Comment by Liam3851** [comment]
@scwilkinson There's already ```DataFrame.mask``` that does what you suggest, so I don't think we really need another alias in the library? You could perhaps monkey patch
```
pd.Series.where_true = pd.Series.mask
```
if you find the name confusing. 

Personally, I usually think of ```DataFrame.where``` like the python ternary operator, if that mnemonic helps. The ternary operator has form:
```
true_value if cond else false_value
```

which well matches
```
df.where(cond, false_value)
```

**Comment by scwilkinson** [comment]
@Liam3851 I embarrassingly didn't know that's what `mask` did. I always assumed it had something to do with masked arrays in numpy for some reason, and never had a need for it in pandas so never read the docs!

That mnemonic is actually really helpful, thank you for sharing! I'm just going to use `mask` from now on since it behaves how I expect `where` to and matches more closely the way I think about filtering data.

I do wonder if the existence of both `mask` and `where` is redundant. I still think that `where` is confusing to read. I've asked several colleagues how they expect it to behave, and none were able to guess correctly.

**Comment by miaojingang** [comment]
I also find the behavior of `DataFrame.where()` counter-intuitive.
