### ISSUE TITLE
pandas.cut() behaving unexpectedly

### ISSUE THREAD

**Issue by codeprimate123** [pandas-dev/pandas#25566]
```
In: df.shape
Out: (125298, 6)

In: len(interval_index)
Out: 8958

In: len(df['position_start'])
Out: 125298

In: pd.cut(df['position_start'], interval_index)
 ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-ec9733045e49> in <module>
----> 1 pd.cut(df['position_start'], interval_index)

~/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/tile.py in cut(x, bins, right, labels, retbins, precision, include_lowest, duplicates)
    235 
    236     return _postprocess_for_cut(fac, bins, retbins, x_is_series,
--> 237                                 series_index, name)
    238 
    239 

~/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/tile.py in _postprocess_for_cut(fac, bins, retbins, x_is_series, series_index, name)
    496     """
    497     if x_is_series:
--> 498         fac = Series(fac, index=series_index, name=name)
    499 
    500     if not retbins:

~/anaconda3/lib/python3.7/site-packages/pandas/core/series.py in __init__(self, data, index, dtype, name, copy, fastpath)
    260                             'Length of passed values is {val}, '
    261                             'index implies {ind}'
--> 262                             .format(val=len(data), ind=len(index)))
    263                 except TypeError:
    264                     pass

ValueError: Length of passed values is 125719, index implies 125298
```
I might be missing something, but it seems to me something isn't right. 
I tried to google the error message but nothing useful came out.
I tried to reproduce the error on a minimal case to provide runnable code but I couldn't get this same error. In other ways my df is behaving as expected.

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None

pandas: 0.23.4
pytest: 4.0.2
pip: 18.1
setuptools: 40.6.3
Cython: 0.29.2
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.8.2
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.2
openpyxl: 2.5.12
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.2
lxml: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by codeprimate123** [comment]
I found out that the problem isn't in the cut() but was in my interval index, some intervals were overlapping when they weren't expected.

**Comment by TomAugspurger** [comment]
Can this be closed then?
