### ISSUE TITLE
value error when multiply two large numbers

### ISSUE THREAD

**Issue by RosyRomance** [pandas-dev/pandas#25562]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

```
#### Problem description
data
Out[24]: 
      code  volume
0   000559    7400
1   000559    3500
2   002415    4000
3   002415    5200
4   600622    4300
5   000559    9340
6   000559    9200
7   600622    3700
8   600622   11700
9   600622    3800
10  600622   22800
11  600622    4200
12  002415    4000
13  000559   21600
14  000559   21900
15  002415    6900
16  002415    4000
17  002415    2200
18  000559   21900
19  002415    4000
20  600622    6000
21  002415    4000
22  600622    3300
23  600622    2400
24  000559   10900
25  600622    3900
26  600622    4000
27  600622    6200
28  000559    5100
29  600622   13900
..     ...     ...
32  002415    4000
33  600622   29500
34  600519    2800
35  000559   10900
36  000559    5200
37  000559   10900
38  000559   15051
39  600622    3200
40  600622    2400
41  600622    2800
42  000559    8100
43  600622   14000
44  600622    2400
45  000559   21900
46  600622   10600
47  600622   14700
48  600622    5700
49  600622    5900
50  000559   21900
51  600519    2100
52  000559   10900
53  000559   11000
54  600622   14700
55  600622    4500
56  600622    9200
57  600622   14200
58  000559   21900
59  000559   21900
60  600622   14700
61  600622    5900

data.volume * 1000000
Out[26]: 
0    -1189934592
1     -794967296
2     -294967296
3      905032704
4        5032704
5      750065408
6      610065408
7     -594967296
8    -1184901888
9     -494967296
10    1325163520
11     -94967296
12    -294967296
13     125163520
14     425163520
15   -1689934592
16    -294967296
17   -2094967296
18     425163520
19    -294967296
20    1705032704
21    -294967296
22    -994967296
23   -1894967296
24   -1984901888
25    -394967296
26    -294967296
27    1905032704
28     805032704
29    1015098112
   
32    -294967296
33    -564771072
34   -1494967296
35   -1984901888
36     905032704
37   -1984901888
38   -2128869184
39   -1094967296
40   -1894967296
41   -1494967296
42    -489934592
43    1115098112
44   -1894967296
45     425163520
46    2010065408
47    1815098112
48    1405032704
49    1605032704
50     425163520
51    2100000000
52   -1984901888
53   -1884901888
54    1815098112
55     205032704
56     610065408
57    1315098112
58     425163520
59     425163520
60    1815098112
61    1605032704

When a positive number multiply with a very large number, the result become negative. I think this is caused by data error. The numbers should be changed to double before calculate. 
However I have only few knowledge about C language. Can anybody fig this problem/

**Comment by jreback** [comment]
show a reproducible example and pandas.show_versions() like the trackers asks

**Comment by c-kennedy** [comment]
Here are some more details/examples:

```
>>> import pandas as pd
>>> S = pd.Series([2**63-1])
>>> S*2
0   -2
dtype: int64
```
`S` has dtype: int64, so `S*2` has value -2 instead of 18446744073709551614.

Similarly:
```
>>> S = pd.Series([2**63])
>>> S*2
0   0
dtype: uint64
```

Any larger and you get dtype: object, so the problem disappears:
```
>>> S = pd.Series([2**64])
>>> S*2
0    36893488147419103232
dtype: object
```

There are similar issues when pandas thinks you're sticking to dtype: int32:

```
>>> S = pd.Series([2**31-1]).astype('int32')
>>> S*2
0   -2
dtype: int32
```

This can definitely happen by accident, if something else besides pandas sets the dtype:

```
>>> from numpy.random import random_integers
>>> S = pd.Series(random_integers(0,2**31-1,10))
>>> S
0    1065050882
1    1127918465
2     197142247
3     403230013
4    1873834559
5     816542214
6    2115518126
7     124630489
8     459542413
9    1656918711
dtype: int32
>>> S*2
0    2130101764
1   -2039130366
2     394284494
3     806460026
4    -547298178
5    1633084428
6     -63931044
7     249260978
8     919084826
9    -981129874
dtype: int32
```

My version info:
```
>>> pd.show_versions()
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: English_United States.1252

pandas: 0.23.4
pytest: None
pip: 19.0.3
setuptools: 40.6.2
Cython: None
numpy: 1.15.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.6.3
html5lib: None
sqlalchemy: 1.3.1
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
```

**Comment by jreback** [comment]
not sure if your point here

multiplication can overflow - this is exactly what numpy does (in fact this is numpy under the hood)

**Comment by c-kennedy** [comment]
Right. Yeah, checking my numpy settings, it's supposed to warn about overflows but often doesn't (even for purely numpy operations), and that seems to be a known machine-dependent error ([numpy issue #11117](https://github.com/numpy/numpy/issues/11117)). Sorry for the confusion.

**Comment by alimcmaster1** [comment]
Closing since issue has been raised in numpy.
