### ISSUE TITLE
How to convert pandas dataframe to a database table?

### ISSUE THREAD

**Issue by lexmi7** [pandas-dev/pandas#25572]
I am using plpython to create functions in postgresql. Is it possible to use DataFrame.to_sql() within postgresql to convert a dataframe to a table ? Here I want to convert df into a database table

**Comment by WillAyd** [comment]
Yes you can do this. The documentation for to_sql is here:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_sql.html

If you have further usage questions please post to a Q&A site like StackOverflow, which is better indexed for these types of things and helps future readers out who may have the same question. This board is reserved for just bug reports and enhancement requests. Thanks!

**Comment by lexmi7** [comment]
But here they are accessing the database through python connectivity. I want to use the function within postgresql.

create or replace  function test()
returns void as $$
import numpy as np;
import pandas as pd;
a=np.matrix([[1,2,3],[4,5,6],[7,8,9],[0,0,0]]);
r,c=a.shape;
df=pd.DataFrame(data=a,index=np.array(range(1, r+1)),columns=np.array(range(1, c+1)))

$$language plpython2u;

**Comment by WillAyd** [comment]
Oh OK thanks for clarifying - I honestly wasn't even aware that existed. In any case I'd still suggest starting on StackOverflow or maybe Gitter to see if any has experience from a usage perspective rather than posting here
