### ISSUE TITLE
Remove makePanel Calls in Docs

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#25609]
As a follow up to #25231 some exceptions are getting raised when building the docs as a result of calls to makePanel lingering around. Here's at least one section where this is occurring:

http://pandas-docs.github.io/pandas-docs-travis/getting_started/dsintro.html#deprecate-panel

Would want to remove these references and possibly the entire section surrounding to clean up doc build

**Comment by ArtificialQualia** [comment]
I can work on this
