### ISSUE TITLE
Malformed dict created from squeezed dataframe

### ISSUE THREAD

**Issue by lucasbracher** [pandas-dev/pandas#25621]
[error_dict.txt](https://github.com/pandas-dev/pandas/files/2948709/error_dict.txt)

```python
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> error_dict = pd.read_csv("error_dict.txt")   #github doesn't support attach csv
>>> dict(error_dict.set_index('FIELD').squeeze())

```

This outputs a malformed dict:

{'Q89': 'category',
 'Q90': 'category',
 'Q91': 'category',
 'Q92': 'category',
 'Q93': 'category',
 'Q94': 'category',
 'Q95': 'category',
 'Q102': 'category',
 'Q103': Q103    category
 Q103    category
 Name: TYPE, dtype: object,
 'Q104': Q104    category
 Q104    category
 Name: TYPE, dtype: object,
 'Q105': 'category',
 'Q106': 'category',
 'Q107': 'category',
 'Q108': 'category',
 'Q109': 'category',
 'Q110': 'category',
 'Q111': 'category',
 'Q112': 'category',
 'Q113': Q113    category
 Q113    category
 Name: TYPE, dtype: object,
 'Q41': 'category',
 'Q42': 'category',
 'Q101': 'category',
 'Q24': 'category',
 'Q39': 'category',
 'Q37': 'category',
 'Q38': 'category'}

#### Expected Output

{'Q89': 'category',
 'Q90': 'category',
 'Q91': 'category',
 'Q92': 'category',
 'Q93': 'category',
 'Q94': 'category',
 'Q95': 'category',
 'Q102': 'category',
 'Q103': 'category',
 'Q104': 'category',
 'Q105': 'category',
 'Q106': 'category',
 'Q107': 'category',
 'Q108': 'category',
 'Q109': 'category',
 'Q110': 'category',
 'Q111': 'category',
 'Q112': 'category',
 'Q113': 'category',
 'Q41': 'category',
 'Q42': 'category',
 'Q101': 'category',
 'Q24': 'category',
 'Q39': 'category',
 'Q37': 'category',
 'Q38': 'category'}

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Linux
OS-release: 4.18.0-16-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: fr_FR.UTF-8
LOCALE: pt_BR.UTF-8

pandas: 0.24.1
pytest: None
pip: 9.0.1
setuptools: 39.0.1
Cython: 0.29.6
numpy: 1.16.2
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.3.0
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: 4.3.2
bs4: 4.7.1
html5lib: 0.999999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by WillAyd** [comment]
The idiomatic approach here would be to use the `to_dict` method:

```python
error_dict.set_index('FIELD').squeeze().to_dict()
```

Not sure if we really makes guarantees about the mapping protocol of Series (hence why the `to_dict` method exists) though welcome to investigate

**Comment by mroeschke** [comment]
Appears there hasn't been much activity or community support for this feature in a while so closing. Happy to reopen if there's renewed support
