### ISSUE TITLE
CLN: final Panel cleanup

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#25632]
I think we can take the final step an remove all remaining references to Panel.

```
(pandas) bash-3.2$ grep -r Panel pandas --exclude '*.pickle' --exclude *.msgpack --include '*.py' |wc
     146     911   11617
```
note that the pickle  & msgpack files will stay.

TODO
- [ ] Have `_constructor_expanddim` raise a `Notimplementederror`

**Comment by jreback** [comment]
anything left on this

cc @pandas-dev/pandas-core

**Comment by datapythonista** [comment]
I opened #26627, I couldn't find anything else.

**Comment by jbrockmendel** [comment]
Were the pickle/msgpack files ever recreated without Panel?

**Comment by WillAyd** [comment]
@jbrockmendel is that all we need to do is basically re-save those test files?

**Comment by jbrockmendel** [comment]
> is that all we need to do is basically re-save those test files?

Using the older pandas versions, yah.  When I tried to do this a few months ago it didn't go great, don't remember off the top of my head what went wrong.

**Comment by jbrockmendel** [comment]
@WillAyd #25250

**Comment by simonjayhawkins** [comment]
there seems a small bit of panel specific code in to_xarray in core.generic.

it's not tested for self.ndim> 2, ok to remove?
