### ISSUE TITLE
Support of read_excel password protected files

### ISSUE THREAD

**Issue by prathamshah9** [pandas-dev/pandas#25650]
#### Problem description
Most of the times the excel files are password protected and hence unable to be read by the read_excel unless some sort of pre-processing or manual work. Need support for reading the excel files through win32com or different API.

#### Output of ``pd.show_versions()``
<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-1072-aws
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.3
pytest: None
pip: 18.0
setuptools: 40.4.1
Cython: 0.24.1
numpy: 1.11.1
scipy: 0.18.1
pyarrow: 0.8.0
xarray: None
IPython: 2.2.0
sphinx: None
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.6.1
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 1.5.3
openpyxl: 2.3.2
xlrd: 1.2.0
xlwt: None
xlsxwriter: None
lxml: 3.6.4
bs4: None
html5lib: 0.999
sqlalchemy: None
pymysql: None
psycopg2: 2.6.2 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by WillAyd** [comment]
Pandas relies on third party libraries to read excel files; currently this is just xlrd, though openpyxl has a PR supporting it. 

xlrd claims this is unlikely to ever be done:

https://github.com/python-excel/xlrd

openpyxl has this on hold:

https://bitbucket.org/openpyxl/openpyxl/issues/26/open-password-protected-workbook

In either case closing as this isn't something pandas would handle directly

**Comment by WillAyd** [comment]
One other reference for openpyxl:

https://bitbucket.org/openpyxl/openpyxl/issues/193/can-i-open-password-protected-excel-files

**Comment by KelvinPiVan** [comment]
> New python library, works great, read encrypted, write decrypted.
> 
> https://github.com/nolze/msoffcrypto-tool

proven works fine!:

`import msoffcrypto
import io
import pandas as pd

file = msoffcrypto.OfficeFile(open("encrypted.xlsx", "rb"))

# Use password
file.load_key(password="Passw0rd")

decrypted = io.BytesIO()
file.decrypt(decrypted)

df = pd.read_excel(decrypted)
print(df)`
