### ISSUE TITLE
Rolling.apply documentation not clear

### ISSUE THREAD

**Issue by js3711** [pandas-dev/pandas#25656]
The current documentation for [rolling.apply](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.window.Rolling.apply.html) states:

> func : function
> Must produce a single value from an ndarray input if raw=True or a Series if raw=False.

This makes it sound like a series consisting of multiple values can be returned by the apply func.  This is not true.  The following error results:

Pandas v 0.24.1
```python
samples = roll.apply(lambda x: pd.Series([1]), raw=True)
example = pd.Series(np.random.rand(10000,))
example.rolling(100).apply(lambda x: pd.Series([1,2,3,4]), raw=False)

~/anaconda3/envs/pandas/core/series.py in wrapper(self)
     91             return converter(self.iloc[0])
     92         raise TypeError("cannot convert the series to "
---> 93                         "{0}".format(str(converter)))
     94 
     95     wrapper.__name__ = "__{name}__".format(name=converter.__name__)
TypeError: cannot convert the series to <class 'float'>
```

**Comment by WillAyd** [comment]
The `func` argument is documented as follows:

```
Must produce a single value from an ndarray input if raw=True or a Series if raw=False.
```

So the problem is that your expression doesn't reduce to a scalar. 

What distinction are you trying to make with Series here? This will fail if you replace with a NumPy array as well (though admittedly with a different error message)

**Comment by js3711** [comment]
Yup, that makes it clearer.  It initially read as though multiple values could be returned through the Series

**Comment by lycanthropes** [comment]
> The `func` argument is documented as follows:
> 
> ```
> Must produce a single value from an ndarray input if raw=True or a Series if raw=False.
> ```
> So the problem is that your expression doesn't reduce to a scalar.
> 
> What distinction are you trying to make with Series here? This will fail if you replace with a NumPy array as well (though admittedly with a different error message)

I want to realize some ideas like this:
df.groupby('stock_code').rolling(window=12).apply(wavg,'column1',weight_variable)
this means  applying a given weight variable to a rolling  column (here it is df.column1). But I can not design a available wavg function .My wavg function is:
def wavg(group, avg_name):
    d = group[avg_name]
    w = pd.Series(data=[0,0,0.5**3,0,0,0.5**2,0,0,0.5,0,0,1])
    d=d.reset_index(drop=True)
    try:
        return (d * w).sum() / w.sum()
    except ZeroDivisionError:
        return np.nan
But when I run the code : df.groupby('stock_code').rolling(window=12).apply(wavg,'column1',weight_variable), it always return a TypeError: wavg() missing 1 required positional argument: 'avg_name'
