### ISSUE TITLE
Dataframe filtering fails with UnicodeEncodeError on Python 2.7 and unicode character above 128

### ISSUE THREAD

**Issue by MaozGelbart** [pandas-dev/pandas#25673]
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import pandas as pd

df = pd.DataFrame(dict(a=np.repeat(unichr(170),1)))
df[df["a"]==unichr(170)]

# Traceback (most recent call last):
#  File "pandas/core/ops.py", line 1728, in wrapper
#    (is_extension_array_dtype(other) and not is_scalar(other))):
#  File "pandas/core/dtypes/common.py", line 1749, in is_extension_array_dtype
#    registry.find(dtype) is not None)
#  File "pandas/core/dtypes/dtypes.py", line 89, in find
#    return dtype_type.construct_from_string(dtype)
#  File "pandas/core/dtypes/dtypes.py", line 699, in construct_from_string
#    raise TypeError(msg.format(string))
# UnicodeEncodeError: 'ascii' codec can't encode character u'\xaa' in position 0: ordinal not in range(128)

```
#### Problem description
The above comparison should not fail. The problem was introduced in 0.24 and 0.24.1 for Python 2.7 in the ``construct_from_string`` methods of the new datatypes DateTimeTZDtype, IntegerArray and SparseDtype, when trying to ``msg.format(string)`` containing a unicode character above the 128 ascii range, as Python 2.7 is trying to get it ascii encoded by default. 

I guess that changing the raised ``TypeError`` not to print the target string with format (as the case with other ``construct_from_string`` methods) may be a way of fixing this.  

#### Expected Output
Having the input dataframe.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-514.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.24.1
pytest: 2.8.5
pip: 9.0.1
setuptools: 20.3
Cython: 0.23.4
numpy: 1.13.0
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: 4.1.2
sphinx: 1.3.5
patsy: 0.4.0
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml.etree: 3.6.0
bs4: 4.4.1
html5lib: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by jetpack** [comment]
I think this is the same: https://github.com/pandas-dev/pandas/issues/25287

**Comment by MaozGelbart** [comment]
That's right, thanks!
