### ISSUE TITLE
Can't merge if NaNs are present in Int64 columns

### ISSUE THREAD

**Issue by kristian-telepathy** [pandas-dev/pandas#25674]
#### Code Sample

```python
import pandas as pd
import numpy as np 

data1 = pd.DataFrame.from_dict({
    'id': [1],
    'A' : [np.nan]
    }).astype({'id':"int64", "A":"Int64"})
        
data2 = pd.DataFrame.from_dict({
    'id': [1],
    'B' : [3]
    }).astype({'id':"int64", "B":"Int64"})
 
data1.merge(data2, on="id")
```
#### Problem description

My apologies if this has been posted before I didn't see it. I don't seem to be able to merge dataframes if there is a NaN present in an 'Int64' column (note the capitol I). The example above throws with "TypeError: data type not understood".

I would expect the merge to work normally and simple have the column with a NaN there.

#### Expected Output

pd.DataFrame.from_dict({
    'id': [1],
    'A' : [np.nan]
    'B' : [3]
    }).astype({'id':"int64", "A":"Int64", "B":"Int64"})

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.2.final.0
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.1
pytest: None
pip: 9.0.3
setuptools: 39.2.0
Cython: None
numpy: 1.16.1
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: 4.3.1
bs4: 4.7.1
html5lib: None
sqlalchemy: 1.2.18
pymysql: 0.9.3
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by TomAugspurger** [comment]
Seems to be fixed on master.

```python
In [10]: import pandas as pd
    ...: import numpy as np
    ...:
    ...: data1 = pd.DataFrame.from_dict({
    ...:     'id': [1],
    ...:     'A' : [np.nan]
    ...:     }).astype({'id':"int64", "A":"Int64"})
    ...:
    ...: data2 = pd.DataFrame.from_dict({
    ...:     'id': [1],
    ...:     'B' : [3]
    ...:     }).astype({'id':"int64", "B":"Int64"})
    ...:
    ...: data1.merge(data2, on="id")
    ...:
Out[10]:
   id    A  B
0   1  NaN  3

In [11]: _.dtypes
Out[11]:
id    int64
A     Int64
B     Int64
dtype: object
```
