### ISSUE TITLE
df[i, j] as an alias to df.loc[i, j]

### ISSUE THREAD

**Issue by gatsoulis** [pandas-dev/pandas#25677]
Long shot (and apologies if duplicate, but nothing came up). It would be great if there was an "alias" to the `df.loc[i, j]` in the form of `df[i, j]`.

**Comment by TomAugspurger** [comment]
I don't think so. That would lead to ambiguous cases with selecting the column whose label is the tuple `(i, j)`. I think the general agreement is that our `__getitem__` is too complex as is https://github.com/pandas-dev/pandas/issues/9595

**Comment by gatsoulis** [comment]
Thanks for the reply and fair enough after reading the linked issue thread :). For the record from a user's perspective, I agree with @shoyer's comment https://github.com/pandas-dev/pandas/issues/9595#issuecomment-77514752 , it would be an improvement in terms of usability.
