### ISSUE TITLE
Option for reshape order in lreshape

### ISSUE THREAD

**Issue by wesm** [pandas-dev/pandas#2567]
Currently is "F"-like ordering

**Comment by petehuang** [comment]
Hi,

This issue hasn't been touched for a few years. Does this continue to represent a useful enhancement?

**Comment by wesm** [comment]
The function is still here https://github.com/pandas-dev/pandas/blob/master/pandas/core/reshape.py#L812, though 4 years later I'm not sure what my intent with this issue was. I would vote to close

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/issues/4920 is the original issue for the very-similar ``pd.wide_to_long``. Think we should remove / consolidate this API.
