### ISSUE TITLE
Series[Sparse].to_dense not converting to dense.

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#25680]
```python
In [1]: import pandas as pd

In [2]: s = pd.Series([1, 2], dtype='Sparse[int]')

In [3]: s.to_dense()
Out[3]:
0    1
1    2
dtype: Sparse[int64, 0]
```

**Comment by jorisvandenbossche** [comment]
+1 (I suppose the historical reason was for compat with the method on SparseSeries) ?

**Comment by TomAugspurger** [comment]
More likely, I just didn't understand what this function was doing :)

But yes, pre-SparseArray is an extension array, `concat([Series[sparse]])`
would return a
SparseSeries rather than a Series with sparse values.

**Comment by jorisvandenbossche** [comment]
Closing this in favor of  #26557
