### ISSUE TITLE
Fix flaky stata test

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#25707]
The test `test_write_fspath_all` in https://github.com/pandas-dev/pandas/blob/86879ac9af524adc684bec77c621d27b19a36ca0/pandas/tests/io/test_common.py#L256 asserts that two files are byte-for-byte identical. This can fail for files like stata, which encode other information like the current timestamp, in the binary data.

DataFrame.to_stata provides a keyword `time_stamp` to control whether the timestamp is written in the binary file.

To avoid spurious test failures from writing the first file at timestamp 1, and the second file at timestamp 2, we should pass that keyword through by adding `{'time_stamp': False}` to the dict in https://github.com/pandas-dev/pandas/blob/86879ac9af524adc684bec77c621d27b19a36ca0/pandas/tests/io/test_common.py#L254

**Comment by jorisvandenbossche** [comment]
Closed by https://github.com/pandas-dev/pandas/pull/25714
