### ISSUE TITLE
Dateoffset - month offset shows incorrect result 

### ISSUE THREAD

**Issue by PrateekGupta1819** [pandas-dev/pandas#25705]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
(Pdb) dr[29:32]
DatetimeIndex(['2015-07-30', '2015-07-31', '2015-08-01'], dtype='datetime64[ns]', freq='D')
(Pdb) dr[29:32]-pd.DateOffset(months=3)
*** ValueError: Inferred frequency None from passed values does not conform to passed frequency D
(Pdb) dr[29:32]-pd.DateOffset(months=4)
DatetimeIndex(['2015-03-30', '2015-03-31', '2015-04-01'], dtype='datetime64[ns]', freq='D')
(Pdb) dr[29:32]-pd.DateOffset(months=2)
DatetimeIndex(['2015-05-30', '2015-05-31', '2015-06-01'], dtype='datetime64[ns]', freq='D')


```
#### Problem description

Not able to offset 3 months

Using pandas - 0.24.1 

#### Expected Output

DatetimeIndex(['2015-05-01', '2015-05-02', '2015-05-03'], dtype='datetime64[ns]', freq='D')

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None

pandas: 0.24.1
pytest: 4.3.0
pip: 19.0.3
setuptools: 40.8.0
Cython: 0.29.5
numpy: 1.15.4
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.3.0
sphinx: 1.8.4
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.9
feather: None
matplotlib: 3.0.2
openpyxl: 2.6.0
xlrd: 1.2.0
xlwt: 1.2.0
xlsxwriter: 1.1.5
lxml.etree: 4.3.0
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.2.18
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by mroeschke** [comment]
This is the expected behavior since 2015-07-31 minus 3 months would give 2015-04-31 which doesn't exist and therefore the date is rolled back to the prior date.

```
In [3]: d = pd.DatetimeIndex(['2015-07-30', '2015-07-31', '2015-08-01'], dtype='datetime64[ns]')

In [4]: d - pd.DateOffset(months=3)
Out[4]: DatetimeIndex(['2015-04-30', '2015-04-30', '2015-05-01'], dtype='datetime64[ns]', freq=None)
```

And since a freq of `'D'` was specified, this frequency can no longer be maintained in the output.
