### ISSUE TITLE
concat([sparse]) should be a Series / DataFrame

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#25702]
I messed up the logic somewhere along the way.

```python
In [11]: df = pd.DataFrame({"A": pd.SparseArray([0, 1])})

In [12]: type(pd.concat([df, df]))
Out[12]: pandas.core.sparse.frame.SparseDataFrame
```

That should be a DataFrame with sparse values.

When should concat return a SparseSeries/Frame?

a.) When *any* of the inputs are `SparseSeries` / `SparseDataFrame`
b.) When *all* of the inputs are SparseSeries/Frame.

Option b is probably least disruptive. Implementing it isn't a pain.

**Comment by WillAyd** [comment]
What's the downside to option a? I admittedly don't use these objects a lot but to cast a vote in there that seems more intuitive to me

**Comment by TomAugspurger** [comment]
For 0.25.0, I want to ensure that pandas only returns a SparseDataFrame if
you're already using them. I hoped we
did that for 0.24.0, but I missed this case apparently.

Option a is a (slightly) larger API-breaking change.

**Comment by TomAugspurger** [comment]
Note that this only affects DataFrame. `concat(List[Series[Sparse]])` has the desired behavior of returning a Series with sparse values.

```python
In [4]: type(pd.concat([pd.Series(pd.SparseArray([0, 1]))] * 2))
Out[4]: pandas.core.series.Series
```
