### ISSUE TITLE
Plot Dataframe by month match gives KeyError: 0L

### ISSUE THREAD

**Issue by ShadyHanafy** [pandas-dev/pandas#25700]
I need your kind help in an issue that I face with plotting. I have an excel sheet with data for couple of months, Im trying to plot graphs based on one month at a time (line chart over days of that month). For this I let the pandas read from the excel and create a dataframe which include a column for all dates (sorted) and column for the corresponding data values. Whenever I match the first month in the dataframe time column, the plot works fine but when i try to choose any following month in the dataframe time column, the plot function throws a KeyError: 0L

Here is my code that I use trying to match the data by month to plot it:

file = "D:\\Raw.xlsx"
df = pd.read_excel(file, 0)
df['timestamp'] = pd.to_datetime(df.timestamp)
df = df[df['timestamp'].dt.month == 2]
fig, ax = plt.subplots()
df['timestamp'] = df['timestamp'].dt.strftime('%#m/%d/%y')
df.plot(ax=ax, xticks=df.index, figsize=(15, 5), rot=45)
ax.tick_params(axis='x', labelsize=9)
ax.set_xticklabels(df.timestamp)
plt.grid(True)
plt.show()

**Comment by WillAyd** [comment]
Hi - for usage questions like this you are better served asking on a Q&A site like StackOverflow. This tracker is reserved for bug reports and enhancement requests
