### ISSUE TITLE
Iterating over chunks from HDFStore with where condition doesn't break loop.

### ISSUE THREAD

**Issue by jdhayhurst** [pandas-dev/pandas#25703]
```python
with pd.HDFStore(hdf) as store:
    chunks = store.select(key, chunksize=20, where='position > 14599 & position < 14605')
    for chunk in chunks:
        print(chunk)
    print('end')


```
#### Problem description

When iterating through chunks from an HDFStore, the loop runs ok but never breaks when a condition is provided in the select statement e.g. in the above example the chunks are printed but it doesn't print 'end'.  If I omit the 'where' condition, it works as expected, i.e. the chunks are printed and the loop breaks.

#### Expected Output

```
#chunks 
end
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.24.1
pytest: 3.5.1
pip: 10.0.1
setuptools: 39.1.0
Cython: 0.28.2
numpy: 1.15.2
scipy: 1.1.0
pyarrow: 0.11.1
xarray: None
IPython: 6.4.0
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.2.0
xlsxwriter: 1.0.4
lxml.etree: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by chris-b1** [comment]
Please make this a reproducible example.  (i.e. some sample data for a store)

**Comment by TomAugspurger** [comment]
Let us know if you can give an example @jdhayhurst and we'll reopen.
