### ISSUE TITLE
astype conversion to str converts NaN object to literal nan string

### ISSUE THREAD

**Issue by joetl** [pandas-dev/pandas#25716]
```python
# Your code here
import pandas as pd
from numpy import nan
df = pd.DataFrame([{'sample': nan }])
df.iloc[0].sample
df.astype('str').iloc[0].sample
```
#### Problem description
When converting any datatype column to string using astype('str') null values (NaN object) is converted to literal nan string
Instead of remaining as null object value

**Comment by TomAugspurger** [comment]
Dupe of https://github.com/pandas-dev/pandas/issues/25353, and probably others.
