### ISSUE TITLE
Make public `start`, `stop` and `step` attributes for RangeIndex

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#25710]
This may be useful to downstream projects (e.g. https://github.com/apache/arrow/pull/3868).

Initially, I think the idea was for RangeIndex to be a drop-in optimized replacement for the equivalent Int64Index. Other libraries might want public access to the same optimizations.

**Comment by jschendel** [comment]
+1, this would additionally make `RangeIndex` more consistent with the Python 3 `range` type, which has these attributes publicly available:
```python
In [1]: rng = range(2, 11, 3)

In [2]: rng.start
Out[2]: 2

In [3]: rng.stop
Out[3]: 11

In [4]: rng.step
Out[4]: 3
```

Will open a PR for this later tonight.

**Comment by jorisvandenbossche** [comment]
Personally, I am not really sure we need them (if downstream projects that need it are fine with using the private ones, we can guarantee there stability).

From a user perspective, I think the idea was to have it as a drop in replacement for int index. And you also quickly loose the presence of the RangeIndex, eg by doing a filtering operation, and then at once those attributes don't exist anymore.

But not feeling strongly about it (it's maybe just I would rather see dataframes with an optional index :))

**Comment by jschendel** [comment]
@jorisvandenbossche : I opened a PR to implement this, but I don't have strong feelings either way. Been having power issues today so didn't see the notification for your comment until I basically had the all the content of the PR complete.  Wouldn't be offended if the PR got closed.
