### ISSUE TITLE
BUG: pd.to_datetime

### ISSUE THREAD

**Issue by Jie-Yuan** [pandas-dev/pandas#25722]
![image](https://user-images.githubusercontent.com/20265321/54338922-3de0cb80-466e-11e9-836f-a806d329d534.png)

**Comment by Jie-Yuan** [comment]
WHY?

**Comment by TomAugspurger** [comment]
See http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports for submitting bug reports, and our issue template.

**Comment by mroeschke** [comment]
The example as is looks like it has nothing to do with pandas (the `to_datetime` call is not assigned to anything). Feel free to reopen if you have a reproducible example.
