### ISSUE TITLE
CLN: remove PY2

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#25725]
master issue for removing all vestigaes of Python 2.

After merging: #24942 (removing the PY2 CI jobs) and #25554 (bump numpy to 1.13.3), we will be ready to remove PY2 code, tests, and doc references.

Let's do this in bite sized pieces. IOW don't do a PR with changes for everything.

cc @pandas-dev/pandas-core

**Comment by TomAugspurger** [comment]
Have we discussed whether we continue to support 3.5? Matplotlib master seems to be on 3.6.

**Comment by WillAyd** [comment]
I think it would be great to jump to 3.6 eventually for better typing support, f-strings, dict ordering, etc... but at the same time I think it makes sense to rip out the Py27 chunks first before going that route, as there will be plenty as is to clean up

**Comment by jreback** [comment]
step by step here. Let's remove PY2 first. Agree not against dropping 3.5 but should not do all at once.

**Comment by TomAugspurger** [comment]
CF seems to have deprecated 3.5 building?
http://conda-forge.org/docs/user/introduction.html#pinned-announcements

Anaconda has stopped building 3.5 packages.

**Comment by TomAugspurger** [comment]
That's actually affecting @h-vetinari's other PR; pytest wasn't being bumped correctly on the 3.5 build (since Anaconda doesn't have new enough 3.5 packages for it).

**Comment by jreback** [comment]
ok merged the removal of the CI jobs for PY2: https://github.com/pandas-dev/pandas/pull/24942

open season on PY2 removals. but let's do this in a measured way.

cc @pandas-dev/pandas-core

**Comment by h-vetinari** [comment]
Before it's open season, I'd suggest to at least merge #25752 first - currently the CI is much reduced from what it was due to the requested hard deletion of PY2-jobs in #24942 (instead of replacing them with new CI jobs).

Another possible candidate to wait for is #25554.

**Comment by jschendel** [comment]
After #26047 is merged the `pandas.compat` related code removals should be complete, but there are still a few odds and ends left:
- `pandas.compat` can still be cleaned up a bit, and some items can be moved elsewhere
- There are a few explicit TODO(PY2) or TODO(py27) comments that should be addressed, e.g.
  https://github.com/pandas-dev/pandas/blob/19626d2567487f8e698174de835c28c900784ed3/pandas/core/arrays/categorical.py#L1511
- There looks to be one import of `six` still around that can be removed:
  - After removing it do we also want to remove `LICENSES/SIX`?
 https://github.com/pandas-dev/pandas/blob/19626d2567487f8e698174de835c28c900784ed3/scripts/merge-pr.py#L33
- @jreback mentioned that `UserDict` can also be changed in https://github.com/pandas-dev/pandas/pull/25957#discussion_r271257819
   - Not exactly sure what this entails though
- Additional Cython modifications?
  - Not well versed enough in that part of the codebase to say if we've addressed everything there
- There are various comments referring to Python 2 that we can edit/address
  - I doubt all of them are actionable, and some probably just need to be deleted

I don't think we necessarily need to completely resolve every item in the list above before closing this issue, e.g. addressing all the Python 2 comments could probably be done on an "as we see it" basis.  I might also be forgetting something, so feel free to add to the list.

**Comment by jreback** [comment]
do we have anything left of this? 

cc @pandas-dev/pandas-core

**Comment by gfyoung** [comment]
@topper-123 went berserk on this issue, so probably he's a good one to judge this 🙂

**Comment by topper-123** [comment]
- pandas.core.base.StringMixin is still there, I've given up on removing that one. If someone could take a look?
- There are still comments containing the regex ``python2|python 2|PY2|PY 2`` (52 instances total). The related code should be looked through for simplifications. Likewise the similar regiex for Python3

Else I don't see much systematic, but on a code base of this size, there is bound to be fragments here and there that people will just have to remove upon encountering them.

**Comment by topper-123** [comment]
BTW, I don't necessarily see the above as blockers for a 0.25 release, but more like "things that should be cleaned up in order to have a tidy and modern code base". And doing them while there is a focus on python2/3 compat will probably be better than doing it "later".

**Comment by jreback** [comment]
this is not blocking 0.25; just seeing if we can close it :)

**Comment by jorisvandenbossche** [comment]
Since it is not blocking, moving this from the 0.25 milestone

**Comment by jbrockmendel** [comment]
closable?

**Comment by jreback** [comment]
sure

i don’t think we have anything concrete left that we want to remove
