### ISSUE TITLE
Incorrect example in wide_to_long docstring

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#25733]
The last example at https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.wide_to_long.html is incorrect.

```
>>> df = pd.DataFrame({
...     'famid': [1, 1, 1, 2, 2, 2, 3, 3, 3],
...     'birth': [1, 2, 3, 1, 2, 3, 1, 2, 3],
...     'ht_one': [2.8, 2.9, 2.2, 2, 1.8, 1.9, 2.2, 2.3, 2.1],
...     'ht_two': [3.4, 3.8, 2.9, 3.2, 2.8, 2.4, 3.3, 3.4, 2.9]
... })
>>> df
>>> l = pd.wide_to_long(df, stubnames='ht', i=['famid', 'birth'], j='age',
                        sep='_', suffix='\w')
>>> l
```

locally, `l` is an empty dataframe

```python
Empty DataFrame
Columns: [ht_two, ht_one, ht]
Index: []
```

I think the `suffix` should be `\w+`.

**Comment by cmorph1** [comment]
Hi, Is this still open?

**Comment by WillAyd** [comment]
@cmorph1 it is still open. There was a PR against it which may have been stalled (no updates in over 2 weeks) so feel free to pick up where that left off

**Comment by cmorph1** [comment]
@WillAyd excellent, I'll get to work on this today.
