### ISSUE TITLE
Setting to multi-index np array break the data

### ISSUE THREAD

**Issue by dddping** [pandas-dev/pandas#25749]
#### To re-produce

```python
# create single/multi index DataFrame
df_s = pd.DataFrame(np.arange(12).reshape(3, 4),columns=list('ABCD'),index=['bar', 'baz', 'foo'])
df_m = pd.DataFrame(np.arange(24).reshape(6, 4),columns=list('ABCD'),index=[
np.array(['bar', 'baz', 'foo','bar', 'baz', 'foo']),np.array(['one','one','one','two','two','two'])])

idx_s=df_s.index.to_numpy()
# change label to other value
idx_s[0]='qux'
# normal
assert df_s.loc['qux','A']==0
assert df_s.index.to_numpy()[0]=='qux'


idx_m=df_m.index.to_numpy()
# change label to other value
idx_m[0]=('qux','one')
# it get change from to_numpy return value
assert df_m.index.to_numpy()[0]==('qux','one')
# however indexing for ('qux','one') raise key error
assert df_m.loc('qux','one'),'A']==0 <-key error

```
#### Problem description

It is already mention from https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.to_numpy.html
**For NumPy dtypes, this will be a reference to the actual data stored in this Series or Index (assuming copy=False). Modifying the result in place will modify the data stored in the Series or Index (not that we recommend doing that).**

However it is really confusing that the label is in index.to_numpy() but it can't access using loc.

**Note**: I am new to Pandas. I start reading Getting started and User Guide from last week. It is a very good resource for newcomer. For the above issue, I don't have any suggestion, just feeling strange...

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.1
pytest: 4.1.0
pip: 10.0.1
setuptools: 39.0.1
Cython: None
numpy: 1.16.2
scipy: None
pyarrow: None
xarray: None
IPython: 7.3.0
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.3
openpyxl: None
xlrd: 1.2.0
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: 4.7.1
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by jbrockmendel** [comment]
> idx_m=df_m.index.to_numpy()

With a MultiIndex, what you are getting here is _not_ a view on the data in the MultiIndex.  So when you do `idx_m[0]=('qux','one')`, you aren't changing `dfm.index` at all.
