### ISSUE TITLE
ERR: Raise a better message when mixing positional and label indexing in loc/iloc

### ISSUE THREAD

**Issue by LucaPaterlini** [pandas-dev/pandas#25753]
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np

data = DataFrame(np.arange(16).reshape((4, 4)),
    index=['Ohio', 'Colorado', 'Utah', 'New York'],
    columns=['one', 'two', 'three', 'four'])

data[data < 5] = 0


print(data.iloc[['Colorado', 'Utah'], [3, 0, 1]])
# .ix is deprecated. Please use
# .loc for label based indexing or
# .iloc for positional indexing


print(data.iloc[['Colorado', 'Utah'], [3, 0, 1]])
#TypeError: cannot perform reduce with flexible type

print(data.loc[['Colorado', 'Utah'], [3, 0, 1]])
#KeyError: "None of [Int64Index([3, 0, 1], dtype='int64')] are in the [columns]"
```
#### Problem description
I followed the suggesion to move the ix to iloc and this is what I have got
I have used python 3.7.2 on an elemntary os 18.04

**Comment by mroeschke** [comment]
Mixing positional and label based indexing is not allowed in `loc` or `iloc`.

So either `data.iloc[[1, 2], [3, 0, 1]]` or `data.loc[['Colorado', 'Utah'], ['four', 'one', 'two]]`

**Comment by simonjayhawkins** [comment]
@mroeschke : the error message `TypeError: cannot perform reduce with flexible type` does not appear helpful. perhaps this should be raised as a seperate issue.

**Comment by LucaPaterlini** [comment]
I am happy with the answer provided.
Just unhappy for this decion becouse It would potentially brake old code as soon as ix will be fully deprecated. 

The example cames from data analysis with python and can be easily reproduced.

**Comment by mroeschke** [comment]
Fair. `iloc` and `loc` could have a better error messages with mixed positional/label indexing.

The decision to deprecate `ix` was made was because its indexing operation was too flexible and not explicit compared to the other multitude of indexers.
