### ISSUE TITLE
values not fetching from excel sheet in read_excel

### ISSUE THREAD

**Issue by Tejeshwarabm** [pandas-dev/pandas#25763]
#### Code Sample, a copy-pastable example if possible

```python
data = pd.read_excel('abcd.xlsx', sheet_name='Sheet 1')
print(data.head())

```
#### Problem description

Some of the columns showing NaN, even though it contains value in excel sheet.

#### Expected Output
       a           b            c        d
0    12       NaN        NaN    523.1
1    24       NaN        NaN    123.1 
2    24      NaN        NaN    213.1
3    45      NaN        NaN    231.1
4    67      NaN        NaN    222.1

#### Output of ``pd.show_versions()``
       a           b            c        d
0    12       12.24      2354   523.1
1    24       122.24      2364   523.1 
2    24       132.24      7354   523.1
3    45       112.24      6354   523.1
4    67       412.24      2854   523.1
<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
commit: None
python: 3.7.0.final.0
python-bits: 32
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.1
pytest: None
pip: 9.0.1
setuptools: 39.1.0
Cython: None
numpy: 1.16.2
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: 2.5.4
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.1.0
lxml.etree: None
bs4: 4.6.3
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
None
</details>

**Comment by WillAyd** [comment]
Can you share the file?

**Comment by Tejeshwarabm** [comment]
Sorry for not sharing excel sheet, due to discrepancies.
But I can explain it

1. due to the formula in some of the fields in excel sheet, It is showing NaN

2. This issue started, when I had updated some fields from openpyxl python packages, for the same excel.
3. The issue will resolve when I open excel and do manually edit.

**Comment by WillAyd** [comment]
Can you not share a smaller version of the excel file? There's unfortunately not a lot to be done here if the error cannot be reproduced

**Comment by WillAyd** [comment]
Closing given this cannot be reproduced but feel free to reopen if you can provide a sample file

**Comment by scku208** [comment]
Hi, @WillAyd. Thanks for the help, here I provided a sample file from my NAS share:
https://ku88.xyz/drive/d/f/629839667719615474

The B2 cell contains a formula =100-1:
![image](https://user-images.githubusercontent.com/10119552/124847429-6de5d280-dfcd-11eb-90ad-d1a3ac9b6a42.png)

and C2 cell is a formula  =A2:
![image](https://user-images.githubusercontent.com/10119552/124847470-8655ed00-dfcd-11eb-86de-05466e70621e.png)

These 2 cells were read as nan:
```
>>> import pandas as pd
>>> df = pd.read_excel('./test_formula.xlsx')
>>> df
   A   B   C
0  1 NaN NaN
```

pd.show_verions():
```
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : f00ed8f47020034e752baf0250483053340971b0
python           : 3.9.1.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 11, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Traditional)_Taiwan.950

pandas           : 1.3.0
numpy            : 1.21.0
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 20.3.1
setuptools       : 51.0.0.post20201207
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
```
