### ISSUE TITLE
pandas.read_table fails to detect data type right and fails with to deserialized NA values

### ISSUE THREAD

**Issue by mindej** [pandas-dev/pandas#25779]
Input file:
```
col1	col2
736372420181101	736372420190314
736718220181101	736718220190314
738542020181101	738542020190314
751412120181101	751412120190314
779315420181101	779315420190314
	807519420190301
	800573920190115
751412120181101	751412120190314
736718220181101	
738542020181101	
751412120181101	751412120190314
779315420181101	779315420190314
```
First problem where there is no dtype defined all values are converted to float64
Example code:
```
import pandas as pd
test1 = pd.read_table( 'test1.txt')
test1.info()
```
Second problem when I am forcing data type to int64 it fails on NA values:
```
import pandas as pd
test1 = pd.read_table( 'test1.txt', dtype={'col1': 'int64', 'col2': 'int64'})
test1.info()
```
Error msg: 
`ValueError: Integer column has NA values in column 0`

**Comment by WillAyd** [comment]
By default integers cannot intermix with NA values, hence why this is getting cast to float. 

It sounds like you want to use the new Int64 dtype that came with v0.24:

http://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.24.0.html#optional-integer-na-support

**Comment by mindej** [comment]
Thank you very match I will update my pandas.
