### ISSUE TITLE
Using corr with callable gives 1 on diagonals where the result should be NaN

### ISSUE THREAD

**Issue by fabianrost84** [pandas-dev/pandas#25781]
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import pandas as pd
from scipy.stats import pearsonr

df = pd.DataFrame(np.zeros((2,2)))

df.corr(method=lambda x, y: pearsonr(x, y)[0])
```
gives:
```python
     0    1
0  1.0  NaN
1  NaN  1.0
```

#### Problem description

This is a follow up on #25726. In the example above the self-correlation is returned as 1.0. However, it should actually be `nan`. I would argue the diagonal elements of the correlation matrix should be calculated instead of setting them to 1 here:
https://github.com/pandas-dev/pandas/blob/cb00deb94500205fcb27a33cc1d0df79a9727f8b/pandas/core/frame.py#L7025-L7026

`df.corr()` gives the output I expected:

#### Expected Output

```python
df.corr()
```
```python
    0   1
0 NaN NaN
1 NaN NaN
```
#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.165-81-default
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 4.1.1
pip: 18.1
setuptools: 40.6.3
Cython: 0.29.3
numpy: 1.15.4
scipy: 1.2.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.8.3
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.9
blosc: None
bottleneck: None
tables: 3.4.4
numexpr: 2.6.9
feather: None
matplotlib: 3.0.2
openpyxl: 2.4.0-b1
xlrd: 1.2.0
xlwt: None
xlsxwriter: None
lxml.etree: 4.3.0
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by peterpanmj** [comment]
take
I met the same problem #43494, I can come up with a solution.

**Comment by jreback** [comment]
closing from discussion in https://github.com/pandas-dev/pandas/pull/43569
