### ISSUE TITLE
AttributeError: 'BlockManager' object has no attribute 'empty'

### ISSUE THREAD

**Issue by iamabigstone** [pandas-dev/pandas#25787]
#### Code Sample, a copy-pastable example if possible

```python

concated_data_frame = concat([self, other], axis=0, ignore_index=True)

```
#### Problem description

I am trying to concat two instance of a subclass of pandas.DataFrame. 

The base class looks like:

```
class BaseTestResult(DataFrame):
    def __new__(cls, data_df, *args, **kwargs):
        # check if an empty DataFrame is passed in; reassign the data_df
        if data_df.empty:
            ...
        return super(BaseTestResult, cls).__new__(cls, data_df, *args, **kwargs)

    def __init__(self, data_df, file_paths=None, *args, **kwargs):
        # pylint: disable=keyword-arg-before-vararg
        super(BaseTestResult, self).__init__(data_df, *args, **kwargs)
        self.validate_input_paths(file_paths)
        self._file_paths = defaultdict(set)
        self.file_paths = defaultdict(set) if not file_paths else file_paths
        self.validate()
...
```
it raise AttributeError:
```
Traceback (most recent call last):
  File "/Users/leijiang/.p2/pool/plugins/org.python.pydev.core_6.4.3.201807050139/pysrc/_pydevd_bundle/pydevd_exec.py", line 3, in Exec
    exec exp in global_vars, local_vars
  File "<console>", line 2, in <module>
  File "/Users/leijiang/pyperf/ENV/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 229, in concat
    return op.get_result()
  File "/Users/leijiang/pyperf/ENV/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 431, in get_result
    return (cons._from_axes(new_data, self.new_axes)
  File "/Users/leijiang/pyperf/ENV/lib/python2.7/site-packages/pandas/core/generic.py", line 332, in _from_axes
    return cls(data, **kwargs)
  File "/Users/leijiang/pyperf/pyPerf/test_results/base_test_result.py", line 130, in __new__
    if data_df.empty:
AttributeError: 'BlockManager' object has no attribute 'empty'
```

#### Expected Output

It should pass

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
>>> pandas.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.10.final.0
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.0
pytest: 3.8.2
pip: 9.0.3
setuptools: 40.8.0
Cython: None
numpy: 1.16.1
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: 1.8.0
patsy: None
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by WillAyd** [comment]
Did you also follow the instructions for subclassing per the documentation?

http://pandas.pydata.org/pandas-docs/stable/development/extending.html#subclassing-pandas-data-structures

**Comment by iamabigstone** [comment]
@WillAyd Just tried following the instructions, **still getting the same AttributeError**:

```
    ...
    _internal_names = DataFrame._internal_names + \
        ['file_paths', 'allowed_src_tgt_objs', 'attachable_files', 'obj_schema']

    @property
    def _constructor(self):
        return BaseTestResult
    ...
```

**Comment by iamabigstone** [comment]
@WillAyd Any idea 

> Did you also follow the instructions for subclassing per the documentation?
> 
> http://pandas.pydata.org/pandas-docs/stable/development/extending.html#subclassing-pandas-data-structures

**Comment by iamabigstone** [comment]
@WillAyd Any suggestion on how to fix this?

**Comment by WillAyd** [comment]
Did you subclass all of the properties? Your code above only shows one

**Comment by iamabigstone** [comment]
Ok, got it solved by adding
```
    _internal_names = DataFrame._internal_names + \
        ['file_paths', 'allowed_src_tgt_objs', 'attachable_files', 'obj_schema']

    @property
    def _constructor(self):
        return BaseTestResult
```
to each subclass of the base class
