### ISSUE TITLE
Creating DataFrame from mixed list of lists and arrays causes sys exit

### ISSUE THREAD

**Issue by mch56** [pandas-dev/pandas#25783]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np

data = [['A','B'],np.array([1,2])] 

df = pd.DataFrame(data)

```
#### Problem description

The above code causes my kernel to crash with no error message. 

I believe the reason for this can be found in the following method:

https://github.com/pandas-dev/pandas/blob/c8ba766fca0b7e91f57c64fdb1e2c2a00a643d27/pandas/core/internals/construction.py#L423

It appears this method only looks at the data type of the first entry of list and then assumes that the remainder of the list is the same type. Hence, since the second entry is a numpy array we crash the kernel.

If we change the order of the entries in the data list, (ie. make an array first) we do not get an error. eg. this does not crash

```python
import pandas as pd
import numpy as np

data2 = [np.array(['A','B']),[1,2]] 

df2 = pd.DataFrame(data2)

```

#### Expected Output

If mixed type lists cannot be handled in a consistent manner, then an exception should be thrown rather than a crash with no logging.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.0
pytest: None
pip: 18.1
setuptools: 40.6.3
Cython: None
numpy: 1.15.4
scipy: 1.2.0
pyarrow: 0.9.0
xarray: None
IPython: 7.2.0
sphinx: 1.8.2
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: 0.4.0
matplotlib: 3.0.2
openpyxl: 2.5.12
xlrd: 1.2.0
xlwt: None
xlsxwriter: 1.1.2
lxml.etree: None
bs4: 4.7.1
html5lib: None
sqlalchemy: 1.2.16
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by jreback** [comment]
check this on 0.24.2

**Comment by mch56** [comment]
No issues in 0.24.2
