### ISSUE TITLE
value_counts: name and index'es name

### ISSUE THREAD

**Issue by kuraga** [pandas-dev/pandas#25795]
Good day!

```python
s = pd.Series(np.arange(10), name='items')
c = s.value_counts()

c.name  #=> 'items'

c.index.names  #=> None
```

IMHO that's very strange. Values of `c` are quantities/counts/etc. not "items". "Items" are represented in `c.index`. No?

What do you think?

Thanks!

**Comment by WillAyd** [comment]
The name here is simply being carried over from the originating Series. Are you asking for a particular enhancement that differs from that?

**Comment by kuraga** [comment]
@WillAyd , yes:

```python
c.name  #=> 'counts'
c.index.names  #=> 'items'
```

**Comment by MarcoGorelli** [comment]
Thanks @kuraga for the report - not sure why you closed this, but I've opened a new issue to take your suggestion forwards https://github.com/pandas-dev/pandas/issues/49497
