### ISSUE TITLE
TST: split up tests/frame/test_indexing.py

### ISSUE THREAD

**Issue by h-vetinari** [pandas-dev/pandas#25798]
Based on [review](https://github.com/pandas-dev/pandas/pull/25633#pullrequestreview-216493057) of @jreback in #25633:
> frame/test_indexing.py is actually pretty huge. so pls change according to my comments, and open an issue to split this to separate smaller files (after)

**Comment by jbrockmendel** [comment]
Appears done (though this is a never-ending battle).  Closing.
