### ISSUE TITLE
Hope for a merge function for the Series.value_counts()

### ISSUE THREAD

**Issue by HuoJnx** [pandas-dev/pandas#25794]
## Code Sample, a copy-pastable example if possible

```python
df_strain=df["strain"].value_counts()
DF(df_strain)
```
![image](https://user-images.githubusercontent.com/40828030/54656452-9d245d00-4b00-11e9-924c-be45235749f7.png)

## Problem description
Hello masters, thanks for your concern.
As the code and image show, I'm using the value_count function. 
The function is very convient~ But I found that if I want to merge the rows which count is lower than 5, I have to do it manually like:
```python
series_dict={}
others_sum=0
for index in df_strain.index:
    count=df_strain.at[index]
    if count>=5:
        series_dict.setdefault(index,count)
    else:
        others_sum+=count
series_dict.setdefault("others",others_sum)
DF(Series(series_dict))
```
![image](https://user-images.githubusercontent.com/40828030/54657255-b8dd3280-4b03-11e9-96f3-ffe9c5eb62a1.png)

## Expected Output
My question is that: Is there any more convenient way to implement the emergence according to my conditions?
Thank you for your time~

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.2
pytest: None
pip: 18.1
setuptools: 39.2.0
Cython: 0.28.5
numpy: 1.15.0
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.5.0
sphinx: None
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.0
openpyxl: 2.5.9
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml.etree: 4.3.1
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by mroeschke** [comment]
For usage question like this, please consult StackOverflow. Github issues is used for bug reports and enhancement requests.

**Comment by HuoJnx** [comment]
> For usage question like this, please consult StackOverflow. Github issues is used for bug reports and enhancement requests.

I'm sorry but, I mean, this may be a point for further enhancement -- The merge function of value_counts, with which I can merge the rows matched the conditions I set.

**Comment by mroeschke** [comment]
I think that use case is too narrowly scoped to include in the `value_count` function.

You can achieve the same functionality by calculating `value_counts` first then use boolean indexing to filter and reassign values.

**Comment by HuoJnx** [comment]
> I think that use case is too narrowly scoped to include in the `value_count` function.
> 
> You can achieve the same functionality by calculating `value_counts` first then use boolean indexing to filter and reassign values.

@mroeschke Thanks a lot for your patient response and detailed instruction, I will keep learning for some better advice in the future.
