### ISSUE TITLE
dataframe.to_excel openpyxl multilpe sheets 

### ISSUE THREAD

**Issue by StefanoGITA** [pandas-dev/pandas#25800]
#### Code to test the issue, you need a csv file

```python
import os
from math import ceil
import pandas


def csv_to_xls(csvfile):
    def write_ws(p_writer, p_min, p_max, p_sheetname):
        df.loc[p_min:p_max].to_excel(p_writer, sheet_name=p_sheetname, index=False)

    MAX_XLSX_ROWSIZE = 1024 ** 2 - 1
    csvfilename = os.path.basename(csvfile)
    xlsxfilename = '{0}.xlsx'.format(os.path.splitext(csvfilename)[0])
    df = pandas.read_csv(filepath_or_buffer=csvfile, header=0)

    if len(df.index) < MAX_XLSX_ROWSIZE:
        df.to_excel(xlsxfilename, index=False)
    else:
        writer = pandas.ExcelWriter(xlsxfilename, engine='openpyxl')
        # writer = pandas.ExcelWriter(xlsxfilename, engine='xlsxwriter')
        for i in range(1, ceil(len(df.index) / MAX_XLSX_ROWSIZE)+1):
            # lmin = (i-1)*(MAX_XLSX_ROWSIZE + 1)
            # lmax = i*MAX_XLSX_ROWSIZE
            # Debug
            lmin = (i-1) * (1000 + 1)
            lmax = i * 1000
            # #####
            sheetname = f'Sheet{i}'
            # comment next 2 rows with xlsxwriter
            if sheetname not in writer.book.sheetnames:
                writer.book.create_sheet()

            write_ws(writer, lmin, lmax, sheetname)
        writer.save()
        writer.close()
    return xlsxfilename

source_dir = 'source'
lcsvfilename = 'smartweb.csv'
lcsvfile = os.path.join(source_dir, lcsvfilename)
lxlsxfilename = csv_to_xls(lcsvfile)

print(f"Creato file {lxlsxfilename}")

```
#### Problem description
I need to split a CSV on multiple xls worksheets.
If I use as writer **xlsxwriter** all goes fine, but if I use **openpyxl**:
- If i don't create the worksheet, the writer overrides the worksheet just created and gives it the new name and the new data
- If I create a worksheet the writer creates another new worksheet with the same name and adds to it the suffix 1

#### Output of ``pd.show_versions()``
<details>
pandas: 0.24.2
pytest: None
pip: 10.0.1
setuptools: 39.1.0
Cython: None
numpy: 1.16.2
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: 2.6.1
xlrd: 1.2.0
xlwt: None
xlsxwriter: 1.1.5
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by WillAyd** [comment]
Please refer to the contributing guide on opening bug reports - the key thing here is to provide something minimal:

https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#bug-reports-and-enhancement-requests

FWIW you have a lot of custom code therein which may be the confounding factor, but again tough to say as the example isn't minimal. If you are trying to write multiple sheets to excel you should follow the instructions in the `to_excel` documentation:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_excel.html#pandas-dataframe-to-excel

Closing for now but if the above doesn't work and you can isolate to a minimal example feel free to reopen
