### ISSUE TITLE
Cannot use categorical IntervalIndex as index when creating pivot_table

### ISSUE THREAD

**Issue by peterpanmj** [pandas-dev/pandas#25814]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame({"A":[1, 1, 2, 2], "B":[1,2,3,4]})
df['C'] = pd.cut(df['A'],[0,2])
df.pivot_table(index='C', values='B', aggfunc=np.sum)

```
#### Problem description
Cannot use IntervalIndex as index when creating  pivot_table. It works fine on 0.23.4.

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\interval.py in _get_prev_label(label)
     75     else:
     76         raise TypeError('cannot determine next label for type {typ!r}'
---> 77                         .format(typ=type(label)))
     78 
     79 

TypeError: cannot determine next label for type <class 'str'>

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: zh_CN.GBK@cjknarrow
LOCALE: None.None

pandas: 0.24.2
pytest: 4.0.2
pip: 18.1
setuptools: 40.6.3
Cython: 0.29.2
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.8.2
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.2
openpyxl: 2.5.12
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.2
lxml.etree: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: Nonetput of ``pd.show_versions()`` here below this line]

</details>

**Comment by jschendel** [comment]
Thanks for the report.  I can confirm that this is broken on master:

```python
In [1]: import numpy as np; import pandas as pd; pd.__version__
Out[1]: '0.25.0.dev0+294.gfbe252333'

In [2]: df = pd.DataFrame({"A":[1, 1, 2, 2], "B":[1,2,3,4]}) 
   ...: df['C'] = pd.cut(df['A'],[0,2]) 
   ...: df
Out[2]: 
   A  B       C
0  1  1  (0, 2]
1  1  2  (0, 2]
2  2  3  (0, 2]
3  2  4  (0, 2]

In [3]: df.pivot_table(index='C', values='B', aggfunc=np.sum)
---------------------------------------------------------------------------
TypeError: cannot determine next label for type <class 'str'>
```

Interestingly, this works when `df['C']` is a plain `IntervalArray`:
```python
In [4]: df['C'] = pd.arrays.IntervalArray([pd.Interval(0, 2)] * 4)
   ...: df
Out[4]: 
   A  B       C
0  1  1  (0, 2]
1  1  2  (0, 2]
2  2  3  (0, 2]
3  2  4  (0, 2]

In [5]: df.pivot_table(index='C', values='B', aggfunc=np.sum)
Out[5]: 
         B
C         
(0, 2]  10
```

I can also confirm that this worked on 0.23.4:
```python
In [1]: import numpy as np; import pandas as pd; pd.__version__
Out[1]: '0.23.4'

In [2]: df = pd.DataFrame({"A":[1, 1, 2, 2], "B":[1,2,3,4]}) 
   ...: df['C'] = pd.cut(df['A'],[0,2]) 
   ...: df
Out[2]: 
   A  B       C
0  1  1  (0, 2]
1  1  2  (0, 2]
2  2  3  (0, 2]
3  2  4  (0, 2]

In [3]: df.pivot_table(index='C', values='B', aggfunc=np.sum)
Out[3]: 
         B
C         
(0, 2]  10
```
