### ISSUE TITLE
Slow read_parquet in version 0.24.1 vs 0.23.3

### ISSUE THREAD

**Issue by alokgogate** [pandas-dev/pandas#25819]
Below is my code: 

import pandas as pd
df = pd.read_parquet("/data/train.parquet"

The time taken to read this file (size 8GB) is about 3 min with pandas version 0.24.1. This took less than 1 min with pandas version 0.23.3. 

Any clue as to why this may happen?

Thanks!

**Comment by jreback** [comment]
show your versions in both installations

pandas just defers to other libraries to actually do this

**Comment by alokgogate** [comment]
Versions of other libraries for both pandas 0.23.3 and 0.24.1 are as follows:
pytz (2017.3)
numpy (1.14.2)
python-dateutil (2.6.1)
six (1.11.0)

**Comment by jreback** [comment]
show for pyarrow and fastparquet ehich actually implement this

**Comment by alokgogate** [comment]
I dont have fastparquet installed, should I do that? Default engine taken is pyarrow correct?
Pyarrow version is 0.12.1

**Comment by jreback** [comment]
you can report a reproducible example to the arrow tracker if you want
