### ISSUE TITLE
Plotting pd.Series object does not show year correctly

### ISSUE THREAD

**Issue by matias6942** [pandas-dev/pandas#25825]
I am graphing the results of the measurements of a humidity sensor over time.
I'm using Python 3.7.1 and Pandas 0.24.2.

I have a list called dateTimeList with date and time strings:

```
dateTimeList = ['15.3.2019 11:44:27', '15.3.2019 12:44:33', '15.3.2019 13:44:39']
```

I wrote this code where `index` is a DatetimeIndex object and `humList` is a list of floats.

```python
	index = pd.to_datetime(dateTimeList, format='%d.%m.%Y %H:%M:%S')
	ts = pd.Series(humList, index)

	plt.figure(figsize=(12.80, 7.20))
	ts.plot(title='Gráfico de Humedad en el Tiempo', style='g', marker='o')
	
	plt.xlabel('Tiempo [días]')
	plt.ylabel('Humedad [V]')
	plt.grid()
	plt.savefig('Hum_General'+'.png', bbox_inches='tight')
	plt.show()
```

And I have this two results, one with data from February[1] and the other one with data from March[2].

The problem is that in March instead of leaving the year 2019, sequences of 00 12 00 12 appear on the x axis. I think it is important to note that this only happens on the data of March, since February is ok, and the data of both months have the same structure. Day and Month are shown correctly on both plots.

  [1]: https://www.dropbox.com/s/ckv6zeqb0psh6ih/Hum_General_Febrero.png?dl=0
  [2]: https://www.dropbox.com/s/nzvbwnuf5fkuim1/Hum_General_Marzo.png?dl=0

I also tried with:

```
index = [ pd.to_datetime(date, format='%d.%m.%Y %H:%M:%S') for date in dateTimeList]
```

Now `index` is a list of Timestamps objects. Same Results.

Full Code, Data and Outputs:
[CodeandData.zip](https://github.com/pandas-dev/pandas/files/2997619/CodeandData.zip)

**Comment by WillAyd** [comment]
Can you provide screenshots of what you are seeing along with pd.show_versions?

**Comment by matias6942** [comment]
`print(str(pd.show_versions()))` shows:

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-46-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 4.0.2
pip: 18.1
setuptools: 40.6.3
Cython: 0.29.2
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.8.2
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.3
openpyxl: 2.5.12
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.2
lxml.etree: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
None

```

**Comment by matias6942** [comment]
Finally I solved the problem using matplotlib tools:

```
index = pd.to_datetime(dateTimeList, format='%d.%m.%Y %H:%M:%S')
ts = pd.Series(humList, index)

plt.figure(figsize=(12.80, 7.20))
ts.plot(title='Gráfico de Humedad en el Tiempo', style='g', marker='o')
	
xfmt = mdates.DateFormatter('%Y-%m-%d')
ax = plt.gca()
ax.xaxis_date()
ax.xaxis.set_major_formatter(xfmt)

plt.xlabel('Tiempo [días]')
plt.ylabel('Humedad [V]')
plt.grid()
plt.savefig('Hum_General'+'.png', bbox_inches='tight')
plt.show()
```

**Comment by matias6942** [comment]
The 00 and 12 sequences means 12:00 hrs and 24:00 hrs for each day. The plotted data is ok.
