### ISSUE TITLE
pandas read_sql con use sqlalchemy engine slow much than pymysql connection

### ISSUE THREAD

**Issue by sparo-jack** [pandas-dev/pandas#25821]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import pymysql
import time
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

connect = pymysql.Connect(
    host=host,
    port=port,
    user=user,
    passwd=passwd,
    db=db,
    charset='utf8'
)
cursor = connect.cursor()
sql = """SELECT * FROM table WHERE id = 1;"""

start_time = time.time()
cursor.execute(sql)
for row in cursor.fetchall():
    print(row)
end_time = time.time()
print("sql execute time:%s" % (end_time - start_time))

start_time = time.time()
df_mysql = pd.read_sql(sql, con=connect)
end_time = time.time()
print("sql execute time:%s" % (end_time - start_time))

con_url = "mysql+pymysql://{0}:{1}@{2}:{3}/{4}?charset={5}"
engine = create_engine(con_url.format(user, passwd, host, port, db, charset))
DBSession = sessionmaker(bind=engine)
session = DBSession()
start_time = time.time()
raw_data_df = pd.read_sql(sql, session.bind)
end_time = time.time()
print("sql execute time:%s" % (end_time - start_time))

```
#### Problem description
pandas read_sql con use sqlalchemy engine slow much than pymysql connection

#### Expected Output

sql execute time:0.02592611312866211
sql execute time:0.028751611709594727
sql execute time:0.5061156749725342

#### Output of ``pd.show_versions()``
pandas ==0.23.0

**Comment by WillAyd** [comment]
What times are you experience if you use the connections directly instead of pandas? It's not clear from this what overhead if any pandas may be adding

**Comment by jorisvandenbossche** [comment]
@sparo-jack that's an interesting observation. Normally there should be almost no slowdown when using sqlalchemy.

But I see that you are using a session object. Do you also see this slowdown in you directly pass the sqlalchemy `engine` ? 
So something like this:

```
con_url = "mysql+pymysql://{0}:{1}@{2}:{3}/{4}?charset={5}"
engine = create_engine(con_url.format(user, passwd, host, port, db, charset))
start_time = time.time()
raw_data_df = pd.read_sql(sql, engine)
end_time = time.time()
print("sql execute time:%s" % (end_time - start_time))
```

**Comment by sparo-jack** [comment]
@jorisvandenbossche I test different ways and got following results:
pd.read_sql(sql, engine) > pd.read_sql(sql, session.bind)  > pd.read_sql(sql, con=engine.connect()) >

**Comment by jorisvandenbossche** [comment]
Can you give the exact timings as you did above? Do you also see such a large difference between using the raw mysql connection object and the sqlalchemy engine?

I don't have mysql, but with a test for sqlite and postgresql, I only see a limited slowdown when going from raw connection to sqlalchemy engine (27 to 30 ms for sqlite, 58 to 64 ms for postgres, using a database of 6 columns and 10000 records). See https://nbviewer.jupyter.org/gist/jorisvandenbossche/15ff4454e695892b549b625ae16f6273 for the notebook.

**Comment by ieipi** [comment]
@sparo-jack , is there any conclusion here?
