### ISSUE TITLE
Use Substitution Decorator for CustomBusinessMonthEnd

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#25828]
This is a follow up to https://github.com/pandas-dev/pandas/pull/21093/files#r188805397 which wasn't working with Py27. Now that that is a thing of the past we should be able to use the more idiomatic Substitution approach to generating this docstring

**Comment by Batalex** [comment]
Hi,
I would like to give it a try as a first contribution.
It does not seem to be very complex when looking at the contributing guide
