### ISSUE TITLE
python3.7  pip install pandas==0.22.0 error

### ISSUE THREAD

**Issue by nankaimy** [pandas-dev/pandas#25832]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
pip install pandas==0.22.0
```
#### Problem description
  ----------------------------------------
Command "c:\myprogram\anaconda37\python.exe c:\myprogram\anaconda37\lib\site-packages\pip install --ignore-installed --no-user --prefix C:\Users\qiaj\AppData\Local\Temp\pip-build-env-ls0v0cdg\overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools Cython "numpy==1.9.3; python_version=='3.5'" "numpy==1.12.1; python_version=='3.6'" "numpy==1.13.1; python_version>='3.7'"" failed with error code 1 in None
[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by jreback** [comment]
0.22.0 is somewhat old at this point and no futher backports will happen. try with 0.24.2
