### ISSUE TITLE
bug!!when `json_normalize` string has `null`

### ISSUE THREAD

**Issue by gitbobo** [pandas-dev/pandas#25830]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd
inp= [{'c1null':10,'cols':{'c2':20,'c3time':null}, 'c4':'41'}, {'c1null':11,'cols':{'c2':null,'c3time':'2014-05-24 19:20'},'c4':'42'}, {'c1null':12,'cols':{'c2':20,'c3time':'2016-06-24 19:20'},'c4':'43'}]
df=pd.io.json.json_normalize(inp)
print(df)
```
#### Problem description
NameError: name 'null' is not defined

When use `read_sql` to get dataframe from mysql database.,the JSON string always includes `null`.The `null` in mysql same as `NaN` or `NaT` in pandas.  
Then `json_normalize` should turn `null` to `NaN` or `NaT`.

#### Expected Output
    c1null   c4      cols.c2           cols.c3time
    0    10  41       20                  NaT
    1    11  42       NaN             2014-05-24 19:20
    2    12  43       20              2016-06-24 19:20 
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-514.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: None
pip: 19.0.3
setuptools: 40.8.0
Cython: None
numpy: 1.16.2
scipy: None
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.8.5
patsy: None
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by WillAyd** [comment]
Not completely following the issue - the code sample you've provided should fail as there is no variable named `null`, which is exactly what the NameError is telling you

**Comment by gitbobo** [comment]
@WillAyd ,`null` is one of `json` value,but pandas doesnot recognize `null`
http://www.json.org/

**Comment by WillAyd** [comment]
The error in the code you've provided has nothing to do with pandas. This alone fails:

```python
inp= [{'c1null':10,'cols':{'c2':20,'c3time':null}, 'c4':'41'}, {'c1null':11,'cols':{'c2':null,'c3time':'2014-05-24 19:20'},'c4':'42'}, {'c1null':12,'cols':{'c2':20,'c3time':'2016-06-24 19:20'},'c4':'43'}]
```

It's simply an error in your code trying to reference a variable that doesn't exist, which is exactly what the Python
