### ISSUE TITLE
read_csv and dates: different date formats within the same column (one row month-day-year, anoher day-month-year)

### ISSUE THREAD

**Issue by garfieldthecat** [pandas-dev/pandas#25847]
#### Code Sample:

```python
import numpy as np
import pandas as pd
df=pd.DataFrame()
df['day'] =np.arange(1,32)
df['day']=df['day'].apply(lambda x: "{:0>2d}".format(x)  )
df['month']='01'
df['year']='2018'
df['date']=df['day']+'/'+df['month']+'/'+df['year']
df.to_csv('mydates.csv', index=False)

#same results whether you use parse_dates or not
imp = pd.read_csv('mydates.csv',parse_dates=['date'])
imp['day extracted']=pd.DatetimeIndex(imp['date']).day
print(imp)

```
#### Problem description

**If you import a csv containing dates with read_csv(), pandas may assign different date formats within the same column, i.e. one row may be dd-mm-yyyy and another mm-dd-yyyy** . This is shown in the example above by extracting the day. This happens also when the date column is not ambiguous, i.e. when it contains days from 1st to the 31st. With a column containing only 1-1-2000 or 3-4-2010 you can't infer which is the day and which the month, but with columns containing days till the 31st there cannot be any ambiguity.

The only way I have found to fix this is to declare the date format, either explicitly or "semi-explicitly" with dayfirst. However, it is a BIG problem because it means I must explicitly declare every single date format, even when there shouldn't be any ambiguity.

This happens to me with pandas 0.23.4 and Python 3.7.1 on Windows 10. For reasons I don't understand, conda doesn't update pandas to 0.24.2

The same issue has been reported on stackoverflow: https://stackoverflow.com/questions/55309199/pandas-read-csv-can-apply-different-date-formats-within-the-same-column-is-it?noredirect=1#comment97348008_55309199 but I haven't found it mentioned in github.

#### Expected Output

The column 'day extracted' should have been identical to the column 'day' created with np.arange()

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
byteorder: little
LC_ALL: None
LANG: en
LOCALE: None.None

pandas: 0.23.4
pytest: 4.0.2
pip: 18.1
setuptools: 40.6.3
Cython: 0.29.2
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.8.2
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.2
openpyxl: 2.5.12
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.2
lxml: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
None

</details>

**Comment by jreback** [comment]
pls search the issue tracker this is a long requested issue

**Comment by garfieldthecat** [comment]
Could you please share a link to where this was already raised and discussed? Like I said, I DID search github before posting, but couldn't find anything. This is not a big issue, it's a gigantic issue because it means that years of code may have been wrong :( I am simply shocked - it's the first time I see a language that allows different date formats within the same column.

Do you know if this happens only with read_csv() or also with other functions that create dates, eg pd.to_datetime()?

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/issues/12585

**Comment by garfieldthecat** [comment]
Thanks!
