### ISSUE TITLE
ImportError: cannot import name 'register_extension_dtype'

### ISSUE THREAD

**Issue by hmmerino** [pandas-dev/pandas#25849]
#### Code Sample
I'm using /anaconda3/bin/python
3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
pandas                    0.24.2 
```python
import pandas as pd

```
#### Problem description
 when running "import pandas as pd" I get:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-29-7dd3504c366f> in <module>()
----> 1 import pandas as pd

/anaconda3/lib/python3.6/site-packages/pandas/__init__.py in <module>()
     40 import pandas.core.config_init
     41 
---> 42 from pandas.core.api import *
     43 from pandas.core.sparse.api import *
     44 from pandas.tseries.api import *

/anaconda3/lib/python3.6/site-packages/pandas/core/api.py in <module>()
      5 import numpy as np
      6 
----> 7 from pandas.core.arrays.integer import (
      8     Int8Dtype,
      9     Int16Dtype,

/anaconda3/lib/python3.6/site-packages/pandas/core/arrays/integer.py in <module>()
     14     is_bool_dtype, is_float, is_float_dtype, is_integer, is_integer_dtype,
     15     is_list_like, is_object_dtype, is_scalar)
---> 16 from pandas.core.dtypes.dtypes import register_extension_dtype
     17 from pandas.core.dtypes.generic import ABCIndexClass, ABCSeries
     18 from pandas.core.dtypes.missing import isna, notna

ImportError: cannot import name 'register_extension_dtype'

Any Advice? thank you

**Comment by WillAyd** [comment]
I think you are mixing python environments as the executable you reference at the top doesn't match your traceback.

Can you try in a clean Conda environment and ensure it is activated?

**Comment by hmmerino** [comment]
thank you...I did and it helped... but now getting 
ModuleNotFoundError: No module named 'tweepy' when trying to import tweepy... is probably the same issue, thank you for your assistance.
