### ISSUE TITLE
`read_sas` with encrypted sas7bdat file

### ISSUE THREAD

**Issue by scottgigante** [pandas-dev/pandas#25855]
#### Code Sample, a copy-pastable example if possible

```python
>>> import pandas as pd
>>> pd.read_sas("filename.sas7bdat")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/pandas/io/sas/sasreader.py", line 61, in read_sas
    chunksize=chunksize)
  File "/usr/lib/python3.7/site-packages/pandas/io/sas/sas7bdat.py", line 98, in __init__
    self._get_properties()
  File "/usr/lib/python3.7/site-packages/pandas/io/sas/sas7bdat.py", line 114, in _get_properties
    raise ValueError("magic number mismatch (not a SAS file?)")
ValueError: magic number mismatch (not a SAS file?)
```
#### Problem description

I have a SAS file I would like to read with `pandas`. The author of the dataset encrypted it with a password, which I have been given; however, I do not have SAS and as such want to read this file with pandas.

The command to load this file in SAS is

```
libname in "<file location>";

proc contents data=in.filename (read=my_password);
run;
```

There appears to be no equivalent argument in the pandas `read_sas` function to include this password.

#### Output of ``pd.show_versions()``

<details>

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1.final.0
python-bits: 64
OS: Linux
OS-release: 4.14.85-1-lts
machine: x86_64
processor:
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 3.10.1
pip: 18.0
setuptools: 40.6.2
Cython: 0.29
numpy: 1.15.0
scipy: 1.2.1
pyarrow: 0.11.1
xarray: None
IPython: 6.5.0
sphinx: 1.8.4
patsy: 0.5.0
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: 1.2.1
tables: None
numexpr: 2.6.8
feather: 0.4.0
matplotlib: 3.0.2
openpyxl: 2.5.9
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: None
lxml: 4.2.5
bs4: None
html5lib: 1.0.1
sqlalchemy: 1.2.14
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.7.0
```

</details>

**Comment by WillAyd** [comment]
Here's the specification for sas7bdat files:

https://cran.r-project.org/web/packages/sas7bdat/vignettes/sas7bdat.pdf

As noted in the "SAS7BDAT Header" section there is no publicly available information regarding file format w.r.t. how passwords are managed so I don't think this is possible.

If you can find some other spec regarding this feel free to reopen

**Comment by scottgigante** [comment]
Sad to hear it, but thanks for looking into it. I'll bump if I find out anything about how SAS decrypts these files.
