### ISSUE TITLE
Inconsistent behavior of Series.str.replace() for unicode characters

### ISSUE THREAD

**Issue by joonro** [pandas-dev/pandas#25854]
#### Code Sample, a copy-pastable example if possible

```python

In[11]: import pandas as pd
           test = pd.Series(data=r'Tech \u0026 Innovation', index=range(2))

# can replace a string directly
In[11]: test[0].replace('\\u0026', '&')
Out[11]: 'Tech & Innovation'

# str.replace does not work with the same code:
In[12]: test.str.replace('\\u0026', '&')
Out[12]: 
0    Tech \u0026 Innovation
1    Tech \u0026 Innovation
dtype: object

# it works when I use r''
In[13]: test.str.replace(r'\\u0026', '&')
Out[13]: 
0    Tech & Innovation
1    Tech & Innovation
dtype: object
```
#### Problem description

I just found an inconsistent behavior of `Series.str.replace()` when I try to replace a unicode character. As shown in the example above, I can replace the character `\u0026` with `.replace('\\u0026', '&')` for a string, but `Series.str.replace()` only works when I add `r` in front of the string (`.str.replace(r'\\u0026', '&')`)

#### Expected Output

```python
In[11]: import pandas as pd
           test = pd.Series(data=r'Tech \u0026 Innovation', index=range(2))

In[11]: test[0].replace('\\u0026', '&')
Out[11]: 'Tech & Innovation'

In[12]: test.str.replace('\\u0026', '&')
Out[12]: 
0    Tech & Innovation
1    Tech & Innovation
dtype: object
```

#### Output of ``pd.show_versions()``

<details>

pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.4
pytest: 3.2.1
pip: 19.0.3
setuptools: 38.4.0
Cython: 0.26.1
numpy: 1.13.3
scipy: 1.0.0
pyarrow: None
xarray: 0.9.6
IPython: 6.2.1
sphinx: 1.6.6
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.1.0
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by WillAyd** [comment]
Hi there! This doesn't have anything to do with pandas but is simply a matter of how raw strings work with regular expressions. You'll notice the same behavior in the standard library:

```python
>>> re.sub('\\u0026', '&', r'Tech \u0026 Innovation')
'Tech \\u0026 Innovation'
>>> re.sub(r'\\u0026', '&', r'Tech \u0026 Innovation')
'Tech & Innovation'
```

**Comment by joonro** [comment]
Thanks for the quick reply. So I guess the issue was that str.replace() was using regex by default?

**Comment by WillAyd** [comment]
Ah OK I can see a point of confusion there. Yes Series.str.replace defaults to regex=True, though perhaps confusing as DataFrame.replace defaults to regex=False, so that may be where you got tripped up on this. 

There should be an open issue already for that misalignment

**Comment by joonro** [comment]
Sounds great. Thank you again for your quick replies.
