### ISSUE TITLE
BUG: add date_format to read_csv / Date parsing mistake. read_csv

### ISSUE THREAD

**Issue by John-Colvin** [pandas-dev/pandas#2586]
`date_format` keyword could take the format, dict of columns to format, or list of formats (and could then obviate the need for parse_dates)

Sometimes months and days get mixed up.

E.g.
test.csv:

a,b
27.03.2003 14:55:00.000,1
03.08.2003 15:20:00.000,2

read_csv("/home/john/Documents/test.csv",index_col=0, parse_dates=True)
                     b
a  
2003-03-27 14:55:00  1
2003-03-08 15:20:00  2

There doesn't appear to be any continuity in the date parsing over the rows. As well as meaning things can easily get switched around, this makes date parsing VERY slow. Once you know the format, using the datetime constructor with string slicing as a parser makes read_csv 20x faster on my machine.

I think there needs to be some more parameters for specifying date formats. seeing as in the general case dates a string of dates can be ambiguous (see above).

A possible approach: Have a few default formats to choose from, as well as a more general format string approach. Obviously the defaults could use the datetime constructor with string slicing, which is very fast.

Perhaps have a dayfirst and yearfirst flag that gets passed to dateutil.parser.parse to solve ambiguities when using automatic parsing.

**Comment by jbrockmendel** [comment]
@mroeschke has this been addressed?  Closeable?

**Comment by mroeschke** [comment]
Doesn't appear so. `read_csv` has a `date_parser` argument that accepts a generic parsing function but I think the ask is for a `format` argument like `pd.to_datetime(..., format='...')`

But given that you can also just pass `pd.read_csv(..., date_parser=lambda x: pd.to_datetime(x, format='...'))` as a suitable alternative, I am not sure how on board I am with added a separate `format` argument to `read_csv`. I'd be more clean, but it would grow the already large number of kwargs.

**Comment by jorisvandenbossche** [comment]
Yep, agreed that given the huge amount of keywords, we should maybe not add yet another one (although I would personally find a `format` keyword more useful than the current `date_parser`)

**Comment by WillAyd** [comment]
I still think is useful. Having to provide a lambda in the current state is rather wonky from an end user perspective and an explicit format keyword could probably enable much better performance on larger datasets

**Comment by alexbk66** [comment]
Just had this problem in my code - 
```
dayfirst = True,
infer_datetime_format = True
```
still gets "2010-10-01" for "10/01/2010"

**Comment by jorisvandenbossche** [comment]
@alexbk66 that seems like a bug (maybe `dayfirst` is not passed through correctly somewhere), as this combination works fine with `to_datetime`:

```
In [81]: pd.to_datetime("10/01/2010", infer_datetime_format=True)                                                                                                                                                   
Out[81]: Timestamp('2010-10-01 00:00:00')

In [82]: pd.to_datetime("10/01/2010", infer_datetime_format=True, dayfirst=True)                                                                                                                                    
Out[82]: Timestamp('2010-01-10 00:00:00')
```

**Comment by gfyoung** [comment]
What do you guys think about expanding `date_parser` to be the following:

* callable: custom date parser
* kwargs: parameters to pass to default date converter

This would address the need for greater customized keyword arguments without bloating or requiring wonky lambda arguments.  Also, if we allow `date_parser` to be `kwargs`, we could then deprecate / remove `dayfirst` and `infer_datetime_format` from the signature and require them to be passed as a `dict` via `date_parser`.

**Comment by WillAyd** [comment]
Is the only downside to having a dedicated `format` argument that we already have enough keywords? I still think that as a dedicated keyword is best here, especially given we already have that in `to_datetime`

**Comment by gfyoung** [comment]
API bloat isn't the only reason.  Another benefit of this consolidation is that the `read_csv` API becomes agnostic to the signature of `to_datetime`.  We could have 20 keyword arguments for `to_datetime`, but we wouldn't have to change the signature of `read_csv` to accommodate.  That's what we're running into now.

**Comment by MarcoGorelli** [comment]
Solved as of PDEP4, let's close

```python

In [53]: data = """a,b
    ...: 27.03.2003 14:55:00.000,1
    ...: 03.08.2003 15:20:00.000,2"""

In [54]: read_csv(io.StringIO(data),index_col=0, parse_dates=True)
Out[54]: 
                     b
a                     
2003-03-27 14:55:00  1
2003-03-08 15:20:00  2
```

**Comment by MarcoGorelli** [comment]
Sorry, I was too fast

This is only solved when it's not the index column that's being parsed:
```python
In [56]: read_csv(io.StringIO(data), parse_dates=True)
Out[56]: 
                         a  b
0  27.03.2003 14:55:00.000  1
1  03.08.2003 15:20:00.000  2
```

**Comment by MarcoGorelli** [comment]
Only took 10 years and 5 days, but this is actually fixed now:
```python
In [1]: data = """a,b
   ...:     27.03.2003 14:55:00.000,1
   ...:     03.08.2003 15:20:00.000,2"""

In [2]: read_csv(io.StringIO(data),index_col=0, parse_dates=True)
<ipython-input-2-1174b5f5763d>:1: UserWarning: Parsing dates in     %d.%m.%Y %H:%M:%S.%f format when dayfirst=False was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  read_csv(io.StringIO(data),index_col=0, parse_dates=True)
Out[2]: 
                     b
a                     
2003-03-27 14:55:00  1
2003-08-03 15:20:00  2
```

As the saying goes - "in open sources, bugs get fixed...eventually"

🥳

**Comment by jorisvandenbossche** [comment]
While the original use case in the top post (specific example dates that got silently inconsitently parsed with day first vs last) has been resolved (we are now strict, i.e. PDEP-4), the general discussion here was about how we can expose a `format` keyword (or a more general mechanism to expose `to_datetime` keywords in `read_csv`). And I don't think that is already resolved?

Of course, with the fact that with PDEP-4 we now try to guess the format  by default, there is probably less need to pass custom `to_datetime` keywords. But for the subset where you still need to specify a keyword, having a mechanism to pass it through _could_ still be useful.

For example, for the specific case here, the new warning message says *"... or specify a format to silence this warning"*. But you can't actually specify a format through `pd.read_csv`

**Comment by MarcoGorelli** [comment]
I read this as "here's a date parsing mistake, and a possible solution would be to add a `date_format` argument" - as the parsing mistake is addressed, that's why I considered it closed

You can already pass `date_parser = lambda x: to_datetime(x, format=fmt)`, not sure there needs to be a separate argument

> (if we still want to consider this feature request, it might be better to open a new, dedicated issue about it though, and keep this one closed)

I think that'd be better, the conversation here has already got quite long and many comments are now outdated - I've opened https://github.com/pandas-dev/pandas/issues/50528

**Comment by MarcoGorelli** [comment]
I've looked into this further, and I'll take back

> You can already pass date_parser = lambda x: to_datetime(x, format=fmt), not sure there needs to be a separate argument

As mentioned in https://github.com/pandas-dev/pandas/issues/50601, `date_parser` is actually a net negative (if anyone has a counter-example, please do bring it up) - so, I'd be totally onboard with adding `date_format`, and deprecating `date_parser`

Let's take the conversation over to #50601 then - closing again, sorry for the open/close ping pong here
