### ISSUE TITLE
Unexpected behaviour of groupby.apply with Datetime types

### ISSUE THREAD

**Issue by c-thiel** [pandas-dev/pandas#25877]
Pandas Version: 0.24.1

#### Code Sample:
```python
import pandas as pd
import numpy as np
import datetime

def to_compact(df):
    return pd.Series({'measurment_value': df['measurment_value'].values,
                      'measurement_time': df['measurement_time'].values})
    
    

data = [[0, 1.2, datetime.datetime(2019, 1, 1, 8, 1)],
        [0, 1.3, datetime.datetime(2019, 1, 1, 8, 2)],
        [0, 1.6, datetime.datetime(2019, 1, 1, 8, 3)],
        [1, 1.2, datetime.datetime(2019, 1, 1, 8, 1)],
        [1, 1.2, datetime.datetime(2019, 1, 1, 8, 2)],
        [1, 1.2, datetime.datetime(2019, 1, 1, 8, 3)],
       ]
df = pd.DataFrame(data=data, columns=['feature', 'measurment_value', 'measurement_time'])
df.groupby('feature').apply(to_compact)
```
#### Problem description
Although the returned series of our `to_compact` function is perfectly fine, the return wrapper of `pandas.apply` tries to coerce the type of `measurement_time` to datetime, which obviously failes for arrays.

I argue that this is unexpected, as the dtype of for example floats, ints and other more standard types, changes just as expected in the resulting dataframe to object (Just like in the series).

Please note that this can simply be resolved by renaming the output fields in the `pd.Series`:
```python

def to_compact(df):
    return pd.Series({'measurment_value': df['measurment_value'].values,
                      'measurement_time2': df['measurement_time'].values})
```

This clearly shouldn't have any effect on the output.

#### Actual Output

 feature | measurment_value | measurement_time
-- | -- | --
0 | [1.2, 1.3, 1.6] | NaT
1 | [1.2, 1.2, 1.2] | NaT

#### Expected Output

 feature | measurment_value | measurement_time
-- | -- | --
0 | [1.2, 1.3, 1.6] | [2019-01-01T08:01:00.000000000, 2019-01-01T08:...
1 | [1.2, 1.2, 1.2] | [2019-01-01T08:01:00.000000000, 2019-01-01T08:..

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-20-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: de_DE.UTF-8

pandas: 0.24.1
pytest: 4.2.0
pip: 19.0.1
setuptools: 40.7.3
Cython: 0.29.4
numpy: 1.16.2
scipy: 1.2.0
pyarrow: 0.12.1
xarray: None
IPython: 7.2.0
sphinx: 1.8.4
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.9
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.9
feather: None
matplotlib: 3.0.3
openpyxl: 2.5.14
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.2
lxml.etree: 4.3.0
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.2.17
pymysql: None
psycopg2: 2.7.7 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: 0.2.0
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by jreback** [comment]
a patch was just merged on master for this
pls try

**Comment by c-thiel** [comment]
Just retried with pandas 0.25.0: works as expected!
