### ISSUE TITLE
[BUG] dataframe.copy(deep=True) does not create a copy of dict objects

### ISSUE THREAD

**Issue by jgv7** [pandas-dev/pandas#25872]
#### Code Sample, 

```
# Create some example data
records = []
for i, x in enumerate(list('abcdefg')):
    record = {
        'id': i,
        'letter': x
    }
    records.append(record)
    
df = pd.DataFrame({'data': records})


def _update_key_inplace(x):
    # Modifies the dictionary object in-place
    x['letter'] = 'foo'
    
before1 = copy.deepcopy(df)   ## No better results for this
before2 = df.copy(deep=True)
df['data'].apply(_update_key)
```

#### Problem description

Running the code above will update the 'letter' key of the dictionaries for all instances (before1, before2 and df).

#### Expected Output

before1 and before2 are deep copies and should be unchanged.

**Comment by jreback** [comment]
pls read the doc-string: http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.copy.html?highlight=copy#pandas.DataFrame.copy

python objects are not copied.
