### ISSUE TITLE
Empty dataframe creation

### ISSUE THREAD

**Issue by 0x0L** [pandas-dev/pandas#25887]
Hello,

Creating an empty dataframe with specified columns
```python
pd.__version__
# '0.24.2'

%timeit pd.DataFrame([], columns=['a'])
# 1.57 ms ± 20.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
is way slower than it should be:
```python
%timeit pd.DataFrame([])
# 184 µs ± 1.68 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

%timeit pd.DataFrame([[1]], columns=['a'])
# 343 µs ± 3.33 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

**Comment by jreback** [comment]
this is premature optimization

why does this matter in the real world?

**Comment by 0x0L** [comment]
I'm reading from batch records from an API and batches can be empty.
It's just a surprising behavior. Once you noticed, it's nothing that can't be fixed one way or another...

**Comment by jreback** [comment]
if u think can be fixed w/on adding complexity then pls submit a PR

**Comment by simonjayhawkins** [comment]
can also use examples from OP of #28188 as additional benchmarks.
