### ISSUE TITLE
Epplus adds extra rows with duplicates to the spreadsheet

### ISSUE THREAD

**Issue by william3n** [pandas-dev/pandas#25885]
![epplus_duplicates](https://user-images.githubusercontent.com/17203487/55029028-16c3bb80-4fd7-11e9-9042-0f34c31541dc.png)
SqlDataReader reader = myCommand.ExecuteReader(CommandBehavior.CloseConnection);
                    int row_index = 2;
                    while (reader.Read())
                    {
                        worksheet.Cells[row_index, 1].Value = reader["Header1"].ToString();
                        worksheet.Cells[row_index, 2].Value = reader["Header2"].ToString();
                        worksheet.Cells[row_index, 3].Value = reader["Header3"].ToString();
                        row_index += 1;
                    }
                    reader.Close();
                    conn.Close();
                    p.Save();

**Comment by mroeschke** [comment]
This doesn't look related to pandas. You probably want to post this in the Epplus issues: https://github.com/JanKallman/EPPlus
