### ISSUE TITLE
Fix Type Annotations in pandas/_config/config.py

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#25899]
Part of #25882

Current errors are as follows:

```sh
pandas/_config/config.py:60: error: Need type annotation for '_deprecated_options'
pandas/_config/config.py:61: error: Need type annotation for '_registered_options'
pandas/_config/config.py:62: error: Need type annotation for '_global_config'
```

Should add annotations and remove this module from mypy.ini - think this is straightforward so community PR is certainly welcome!

**Comment by vaibhavhrt** [comment]
I will take care of this too.

**Comment by vaibhavhrt** [comment]
The problem with these three are that they already have a comment describing what these variables do. If I add type comment too the line becomes too long:

    _deprecated_options = {}  # type: Dict[str, str]  # holds deprecated option metdata

How should I split it to multiple lines

**Comment by WillAyd** [comment]
This comment doesn’t really add much over code so I’d just delete. In other cases could move to a different line.
