### ISSUE TITLE
Fix Type Annotations in pandas.core.generic

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#25901]
Part of #25882

Current errors are as follows:

```sh
pandas/core/generic.py:116: error: Need type annotation for '_accessors'
pandas/core/generic.py:119: error: Need type annotation for '_metadata'
```

Both of these are containers which should contain strings, so just need proper annotation and this module can be removed from mypy.ini

**Comment by WillAyd** [comment]
Also makes sense to clean up a similar error in the frame module:

```sh
pandas/core/frame.py:368: error: Need type annotation for '_accessors'
```

**Comment by vaibhavhrt** [comment]
Hi, I tried `_metadata: Container[str] = []` but now pep8 gives me error that:

> pandas/core/generic.py:120:14: E701 multiple statements on one line (colon)

Should I use the the comment syntax `# type: Container[str]` or can we ignore this error?

**Comment by WillAyd** [comment]
Yea for local variables need comment syntax as we still support Py35 and that didn’t come until Py36. 

Should use List here

**Comment by vaibhavhrt** [comment]
Thanks, I will fix this and open a pull request. There are some other open issues related to Type Annotation, should I fix them too in the same PR, or you want different PR for each one?

Also looking at the code `_metadata` looks like a list to me, should I use `List[str]` or `Container[str]`

**Comment by WillAyd** [comment]
Use List and one PR per issue for now

**Comment by vaibhavhrt** [comment]
ok. You said list in your last comment, sorry I missed that, my bad. I was looking at your very first comment which said both are containers.
