### ISSUE TITLE
Inner dictionaries are not displaying in insertion order

### ISSUE THREAD

**Issue by boardtc** [pandas-dev/pandas#25911]
#### Code Sample
```python
newspapers = {'Jim':{'Mon':15,'Tue':17,'Wed':21,'Thu':16,'Fri':19},\
     'Tony':{'Mon':8,'Tue':15,'Wed':11,'Thu':16,'Fri':13}, \
     'Colin':{'Mon':13,'Tue':17,'Wed':19,'Thu':17,'Fri':20} \
    }
newspapers_df = pd.DataFrame(newspapers)

print(newspapers_df)
```
#### Problem description

I am using a recent download of Anaconda with Python 3.7.1 & pandas 0.23.4
The [pandas doc](https://pandas-docs.github.io/pandas-docs-travis/getting_started/dsintro.html) says:

> When the data is a dict, and an index is not passed, the Series index will be ordered by the dict’s insertion order

I instantiate a pandas DataFrame from a dict with no index passed, and print outputs:

#### Expected Output

```python
     Jim  Tony  Colin
Mon   15     8     13
Tue   17    15     17
Wed   21    11     19
Thu   16    16     17
Fri   19    13     20
```

#### Output of `0.23.4``

```python
      Jim  Tony  Colin
Fri   19    13     20
Mon   15     8     13
Thu   16    16     17
Tue   17    15     17
Wed   21    11     19
```

**Comment by mroeschke** [comment]
Could you test this on the latest version of pandas (0.24.2) and master?

I suspect this check is too strict and should be checking for >PY36

https://github.com/pandas-dev/pandas/blob/31b4019ef290bc55855e079b2b7dddcc39a16fc4/pandas/core/common.py#L230

**Comment by alexander-ponomaroff** [comment]
@mroeschke I tested and this also exists on master. I believe that PY36 check also checks for anything above Python 3.6 from what I remember.

I found what causes this issue and will be making a PR later tonight with a fix for this. One of the functions that gets called has a parameter to sort the Index, this is what is causing the order to be sorted here.

**Comment by WillAyd** [comment]
Discussed this in associated PR but this isn't something we want to make guarantees about. Closing as won't fix / no change

**Comment by boardtc** [comment]
> Discussed this in associated PR but this isn't something we want to make guarantees about. Closing as won't fix / no change

Why is the community happy to keep a bug in the code?

The logic in the PR is incorrect.  [From a python-dev message by GvR](https://mail.python.org/pipermail/python-dev/2017-December/151283.html): "Dict keeps insertion order"
