### ISSUE TITLE
Remove pandas.io.stata from Typing Blacklist

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#25932]
Here's the list of current errors:

```sh
pandas/io/stata.py:32: error: Module 'pandas' has no attribute 'DatetimeIndex'
pandas/io/stata.py:32: error: Module 'pandas' has no attribute 'concat'
pandas/io/stata.py:32: error: Module 'pandas' has no attribute 'isna'
pandas/io/stata.py:32: error: Module 'pandas' has no attribute 'to_datetime'
pandas/io/stata.py:32: error: Module 'pandas' has no attribute 'to_timedelta'
pandas/io/stata.py:1730: error: Name 'data_label' already defined on line 1052
```

For the former we should just use absolute imports instead of pulling from top level pandas object (per discussion in #25923). The last issue I think is just a method shadowing a instance variable which I think can safely be removed

**Comment by ryankarlos** [comment]
Ill make a PR for this as well since I've already done similar for #25934 and  #25933

**Comment by bashtage** [comment]
@WillAyd I think this can be closed.
