### ISSUE TITLE
Add Test to Explicitly Check Private Modules Exposed via API

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#25930]
This is a follow up to this conversation:

https://github.com/pandas-dev/pandas/pull/25884#discussion_r270638199

Want to update test_api to explicitly check private modules that may also be in the namespace

**Comment by ryankarlos** [comment]
@WillAyd Can I have a go at this ?  If I understand correctly, the current test checks exclude private modules in the namespace - does the additional test need to go in pandas/tests/api/test_api.py or a separate file with a new Base class which only checks for private modules in the namespace ?  Alternatively i'm guessing a new method check_private could be included with the existing Base class and another test added in the same file ?

**Comment by WillAyd** [comment]
@ryankarlos for sure! I think you can just remove the exclusion of private modules and list them out explicitly as part of the existing test

**Comment by ryankarlos** [comment]
@WillAyd Thanks, will work on it !
