### ISSUE TITLE
Feature suggestion: nullif method

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#25944]
I know that the `pandas` API is already fairly saturated with methods, but I think one that many users might like would be `nullif` (analogous to the Postgres `nullif` function) as a sort of inverse to `fillna`.  Idea being that if you have a `DataFrame` or `Series` and there are certain values that should be treated as `np.nan` that aren't (e.g., sentinel values, impossible values, etc.), you could call `Series.nullif(value)` to return a new `Series` with any instance of `value` set to `np.nan`.  Optionally you could pass in an array of values to set all elements of the array to null, or a boolean-valued function that sets to null any elements that evaluate to `True` (e.g., all negative numbers of a column that should be non-negative, non-numeric values in a numeric column).

Of course this could be done with existing methods like `map` or `applymap` so this would more or less be a syntactic / conceptual shortcut (as in the case of `fillna`).

**Comment by jreback** [comment]
http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.where.html?highlight=where#pandas.Series.where

i suppose we could have a reference to a sql method in the doc string if u were so inclined
