### ISSUE TITLE
pytables tslib change in 0.24.2

### ISSUE THREAD

**Issue by mschatzow** [pandas-dev/pandas#25963]
I have a  HDFStore that is being generated by pandas0.16.3 and  is attempting to be read by current pandas.  it works in 0.23.4 but in 0.24. it says no module named tslib.  what causes this?

for 0.24.2,
I get this error:

/anaconda/4.5.12/lib/python2.7/site-packages/tables/vlarray.pyc in read(self, start, stop, step)
    823         atom = self.atom
    824         if not hasattr(atom, 'size'):  # it is a pseudo-atom
--> 825             outlistarr = [atom.fromarray(arr) for arr in listarr]
    826         else:
    827             # Convert the list to the right flavor

/anaconda/4.5.12/lib/python2.7/site-packages/tables/atom.pyc in fromarray(self, array)
   1225         if array.size == 0:
   1226             return None
-> 1227         return six.moves.cPickle.loads(array.tostring())

ImportError: No module named tslib

**Comment by jbrockmendel** [comment]
@mschatzow is this still a problem?

Best guess is we used to import tslib into io.pytables and don't anymore
