### ISSUE TITLE
pip install error on arm7l (beaglebone)

### ISSUE THREAD

**Issue by jimmyswimmy** [pandas-dev/pandas#25979]
Hi,

Pandas install fails on a beaglebone (I know, I know, use miniconda, but I would like to not do that). It dies with some kind of utter gcc failure building pandas/_libs/join.c which... does not exist.

$ sudo pip install pandas
[see pastebin for full log](https://pastebin.com/PqEdW0Hs)
    building 'pandas._libs.join' extension
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-QMv3zq/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ipandas/_libs/src/klib -Ipandas/_libs/src -I/usr/local/lib/python3.5/dist-packages/numpy/core/include -I/usr/include/python3.5m -c pandas/_libs/join.c -o build/temp.linux-armv7l-3.5/pandas/_libs/join.o -Wno-unused-function
    In file included from /usr/local/lib/python3.5/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                     from /usr/local/lib/python3.5/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /usr/local/lib/python3.5/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from pandas/_libs/join.c:619:
    /usr/local/lib/python3.5/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it with " \
      ^~~~~~~
    arm-linux-gnueabihf-gcc: internal compiler error: Killed (program cc1)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 4

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-y1n9_kq7/pandas/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-j3wf4k_9/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-y1n9_kq7/pandas/

For reference:
$ python3 --version
Python 3.5.3

$ pip freeze
Cython==0.29.6
dateutils==0.6.6
future==0.17.1
iso8601==0.1.12
numpy==1.16.2
python-dateutil==2.8.0
pytz==2018.9
PyYAML==5.1
serial==0.0.97
six==1.12.0

I'm going to try to find the pip flag that doesn't delete its cache or partial installation so I can see a little more. Presumably this is something bad with gcc, maybe running out of memory, I haven't gotten further. This install/compile takes a long time.

**Comment by jreback** [comment]
we have 0 support for arm, that said would take patches if they are compabitle.

**Comment by jimmyswimmy** [comment]
OK, I thought I read an issue where you decided to maintain 32 bit compatibility because of a perceived importance of the rpi/beagle/other communities. In any event the installation failure derives from the compiler losing its mind when it runs out of memory, and giving a useless error. Adding some temporary swap lets pandas 0.24.2 install fine. Thanks for the support.
