### ISSUE TITLE
Unexpected behaviour of numpy.ufuncs for all NaN DataFrame

### ISSUE THREAD

**Issue by trendelkampschroer** [pandas-dev/pandas#25972]
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import pandas as pd
x = pd.DataFrame(index=[0, 1, 2], columns=[0, 1])
np.log(x)
>>> AttributeError: 'float' object has no attribute 'log'
np.sum(df)
>>> 0    0.0
>>> 1    0.0
dtype: float64

y = pd.DataFrame(index=[0, 1, 2], columns=[0, 1, dtype=float])
np.log(y)
>>>     0   1
>>> 0 NaN NaN
>>> 1 NaN NaN
>>> 2 NaN NaN

```
#### Problem description
The AttributeError raised by calling a numpy.ufunc on a DataFrame with object columns containing NaN values is completely uninformative about the problem. 

The error suggest that the namespace `np` is assigned to a float during execution of that numpy.ufunc. This shouldn't happen in any case.

The error can be observed for ufuncs: `exp`, `log`, `sin`, `cos`, etc.

It is also confusing that the ufunc `sum` can be applied to `x` resulting in the expected output for a DataFrame of dtype=float.

The second example, where the dtype is explicitly set to float, passes as expected.

#### Expected Output
An appropriate exception stating that the numpy.ufunc cannot be applied to a frame with (all) object columns.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None

pandas: 0.23.4
pytest: None
pip: 10.0.1
setuptools: 39.2.0
Cython: None
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.5.0
sphinx: None
patsy: 0.5.1
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.3
openpyxl: None
xlrd: 1.2.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
Check your dtypes: you're basically doing

```python
In [10]: np.log(np.array([1.0], dtype=object))
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-7874cc824001> in <module>
----> 1 np.log(np.array([1.0], dtype=object))
```

which isn't valid.

**Comment by jorisvandenbossche** [comment]
This is the behaviour of numpy with object dtype. A pure numpy example:

```
In [42]: a = np.array([1, 2], dtype=object)                                                                                                                                     

In [43]: np.log(a)                                                                                                                                                              
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-43-89b6b8e53c58> in <module>
----> 1 np.log(a)

AttributeError: 'int' object has no attribute 'log'
```

This can certainly be more confusing from the pandas side (eg if you are not aware that you have object dtype data), but as @TomAugspurger says, in the end this is a numpy issue. 

Although, I suppose if we implement `__array_ufunc__`, we could in principle raise another error for object dtypes (simply saying that it is not supported for this dtype, or something)

**Comment by trendelkampschroer** [comment]
Thanks for your quick reply. You are completely right this is coming form the numpy side. Also my interpretation of the `np` namespace getting overwritten was completely wrong. It seems that numpy dispatches all ufunc calls to the array element if `dtype=object`. This is why this raises `AttributeError`.
