### ISSUE TITLE
Fix Type Annotation in pandas.compat.pickle_compat

### ISSUE THREAD

**Issue by vaibhavhrt** [pandas-dev/pandas#25988]
Part of #25882 

Current errors are as follows:

>mypy pandas/compat/pickle_compat.py

    pandas\compat\pickle_compat.py:141: error: Name 'pkl._Unpickler' is not defined

**Comment by vaibhavhrt** [comment]
PR coming as soon as figure out how to fix this.

**Comment by vaibhavhrt** [comment]
Looks like a bug with mypy because `_Unpickler`is certainly a class in module `pickle`.
Similar to https://github.com/python/mypy/issues/6383
Only solution I can find is:

    class Unpickler(pkl._Unpickler):  # type: ignore

@WillAyd what should I do?

**Comment by WillAyd** [comment]
I don't think it's a bug - the stdlib just doesn't have annotations for pickle yet and that private class is not exposed in Typeshed. I think ignore is the only option for now

**Comment by vaibhavhrt** [comment]
Ok, I will open a PR
