### ISSUE TITLE
[ERROR] [1554376470.080690740]: Timeout or error while sending command

### ISSUE THREAD

**Issue by AshWan13** [pandas-dev/pandas#25987]
Hi, I have been trying to set-up terabee multiflex sensors and had encountered this error. 
Hope to get some help in solving this. Thank you!

** Just some background information, I have been trying to modify from the kobuki_bringup launch file and adapting the use of the multiflex to the application of my robot.

![problem ask](https://user-images.githubusercontent.com/49274559/55552542-357d2d00-5710-11e9-8d64-5a8d2b7f4d96.png)

**Comment by jreback** [comment]
nothing to do with pandas

**Comment by AshWan13** [comment]
Sorry, I'm new here. Didn't realized the mistake. Thanks!
