### ISSUE TITLE
Leap year bug in tseries/holiday.py

### ISSUE THREAD

**Issue by mj1856** [pandas-dev/pandas#26007]
Hello.  I found a leap year bug for you.  Hopefully you can fix before Feb 29th 2020 comes around.

https://github.com/pandas-dev/pandas/blob/181f972d2f4e6bd5c8c33721175f68188cfa1a0d/pandas/tseries/holiday.py#L251-L255

The problem here is that if either `start_date.year - 1` or `end_date.year + 1` give a *common* year, and `self.month` is `2` and `self.day` is `29`, then the `datetime` constructor will return a `ValueError`.

**Comment by jreback** [comment]
pls show a reproducible example
and show_versions()

**Comment by mj1856** [comment]
Will provide a failure case example soon.  Just wanted to log it with you in the meantime before I forgot.  Thanks.

**Comment by peekmeister** [comment]
I was looking at the code with the problem you asserted in mind and I wonder if it would be bad practice/feasible to wrap that code in a try/except block. If a ValueError is raised, the date can be checked and possibly change the day to 28 if it is in fact a common year.

**Comment by alimcmaster1** [comment]
hey @mj1856 mind show a repo / use case + show_versions as Jeff mentioned above - thanks!

**Comment by mj1856** [comment]
Hey, sorry.  I've just been too busy to deal with this.  It came up in a broader scan.

Looking closer, I think it would only be problematic if someone was specifically defining Leap Day (Feb 29th) as a holiday.  So probably not a big deal.

**Comment by alimcmaster1** [comment]
Closing as stale - feel free to reopen if you have an example. Thanks!
