### ISSUE TITLE
Set pandas options without importing pandas or editing library code

### ISSUE THREAD

**Issue by williamsmj** [pandas-dev/pandas#26006]
Does pandas provide a way to set its options without importing the module?

I've seen the advice to add something like this to the iPython startup:
```
import pandas
pandas.options.display.some_pandas_option = 42
```
this works in iPython and notebooks, but has a couple of problems for my use case:

1. It doesn't help for scripts run with `$ python my_pandas_script.py` because `python` obviously doesn't run the iPython startup stuff.
2. It leaves `pandas` in the `globals()` of the user's iPython session, which I don't want to do (I'm trying to set defaults for a multiuser environment, but I otherwise want things to feel as usual). I know I can add `del pandas` to that startup script and it will work (i.e. the option will be set correctly for the user if they import pandas), but ...
3. It just _feels_ ugly (and `import pandas` is non-zero (but not trivial) startup overhead).

Patching the pandas library itself is not an option in this context (the user is free to upgrade it).

Do I have any other options? e.g. environment variables, dotfiles, etc., etc.?

**Comment by WillAyd** [comment]
I think you are looking for the feature requested in #4907 so feel free to contribute to that conversation. Closing this as a duplicate
