### ISSUE TITLE
Question. how to  reshape in pandas dataframe?

### ISSUE THREAD

**Issue by Lay4U** [pandas-dev/pandas#26001]
Dataframe looks like below

![image](https://user-images.githubusercontent.com/31833270/55626163-bb1edc80-57e5-11e9-9807-ebc69ff5915a.png)

I have dataframe like above.  which I want to a~t reshape `(a~t, 1)`

I want to reshape dataframe like below ( b~t column is go to under the a column)

```


날짜		역번호	역명	구분    a

2018-01-01	150	서울역	승차	379

2018-01-01	150	서울역	승차	287

2018-01-01	150	서울역	승차	371

2018-01-01	150	서울역	승차	876

2018-01-01	150	서울역	승차	965

....
2008-01-01	152	종각	승차	2920

2008-01-01	152	종각	승차	2290

2008-01-01	152	종각	승차	802

2008-01-01	152	종각	승차	1559
```

like `df = df.reshape(len(data2)*a~t, 1)`

i tried pd.melt but It does not work well.

```
df2 = pd.melt(df, id_vars=["날짜", "역번호", "역명", "구분"], value_name="t")
```
is remove b ~ t but i want insert b~t behind a

dataset is https://drive.google.com/file/d/1Upb5PgymkPB5TXuta_sg6SijwzUuEkfl/view?usp=sharing

**Comment by jorisvandenbossche** [comment]
@Lay4U the github issues are meant for reporting potential bugs / enhancement requests, and not for general questions for help (but of course, the line between both is not always clear). For general usage questions, a Q&A forum like [StackOverflow](https://stackoverflow.com/questions/tagged/pandas) or the [pydata mailing list](https://groups.google.com/forum/#!forum/pydata) is a better place to ask.

Further, I also recommend you to provide a minimal, reproducible example (see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports for more explanation), also if you ask the question in one of the other fora.
