### ISSUE TITLE
Enhancement: Merge two time series and apply a function to overlapping dates

### ISSUE THREAD

**Issue by MattConflitti** [pandas-dev/pandas#26035]
Enhancement description
A standard way to take two dataframes that have a DateTimeIndex and do a time series join where same dates will be together on the same day and allow me to apply a function to it in order to choose which value to take if more than one fall on the same day.

If this functionality doesn't exist, can we open an enhancement request?

Expected Behavior
Time Series 1:
```
Date | Value
------------
1-1-2019 | 1
1-2-2019 | 2
1-3-2019 | 3
```
Time Series 2:
```
Date | Value
------------
1-3-2019 | 4
1-4-2019 | 5
1-5-2019 | 6
```
Then,
```python
#default to taking 'right' time series value on overlapped days
ts1.time_series_join(ts2, overlap_func='right')
```
or
```python
#apply lambda applies to overlapped days
ts1.time_series_join(ts2, overlap_func=lambda x,y: max(x,y))
```
which would return (defaulting to a left join behavior as far as keeping the index goes):
```
Date | Value
------------
1-1-2019 | 1
1-2-2019 | 2
1-3-2019 | 4
```
I haven't seen anything like this on my data processing adventures and think this would be a great feature. A similar feature is implemented in SparkTS for RDDs. Right now, I have resorted to doing some gross looping and utilizing the `.at[]` selector to update overlapping values.

Thanks!

**Comment by WillAyd** [comment]
Not sure this is worth the extra API bloat. You could do this pretty easily with a left join:

```python
df = pd.merge(ts1, ts2, on='Date', how='left')
df['value'] = np.where(df['value_y'].isna(), df['value_x'], df['value_y'])
df = df.drop(columns=['value_x', 'value_y'])
```

**Comment by mroeschke** [comment]
Agreed that this is better served with the example provided above instead of adding a whole new API for this feature. Thanks for the suggestion, but due to lack of activity and lack of interest from the core team closing this issue

**Comment by Hauntingbraeden** [comment]
@mroeschke https://rickeydessert613.github.io/dtd/
