### ISSUE TITLE
Reverse Arithmetic operations between pandas series and custom objects

### ISSUE THREAD

**Issue by prakhar987** [pandas-dev/pandas#26033]
#### Code Sample, a copy-pastable example if possible

```python
class MyObject():
    __array_priority__ =1000  # So __radd__ of this class is called
    def __init__(self,s=None):
        if s is None:
            self.s = pd.Series([1,2,4])
    
    def __radd__(self,other):
        print("Series is passed as :",type(other))
        self.s = self.s + other
        print("After operation, self.s is", self.s)  # a pandas series
        return self  # I want to return object of type:MyObject

custom_obj = MyObject()
s = pd.Series([5,6,7])
s + custom_obj  # Making pd.Series interact with my custom object (reverse add)

```
#### Current Output
```python
Series is passed as : <class 'numpy.ndarray'>
After operation, self.s is 
0     6
1     8
2    11
dtype: int64
0    <__main__.MyObject object at 0x7f6ebbb365f8>
1    <__main__.MyObject object at 0x7f6ebbb365f8>
2    <__main__.MyObject object at 0x7f6ebbb365f8>
dtype: object
```
#### Problem description
The returned object is inserted into a series which has same index as original series.
Is there a better way to make pandas objects interact with custom objects.

Currently a np.ndarray is passed to __radd__. I know there is a way to make pass the series itself (using extension type??) but I am not sure.

#### Expected Output
The operation s + custom_obj should return an object of type MyObject

<details>
pd.version:0.24
</details>

**Comment by jreback** [comment]
this is out of scope for standard pandas; you could create an ExtensionArray for this this but would be some work

why would you actually do this? what is the use case

**Comment by prakhar987** [comment]
A use case could be creating a wrapper on top of pandas objects like pd.Series. So my object built on top of pandas series, should also be able to interact with pandas series directly like i mentioned in the example.

Just the way pandas builds around numpy..i want to build something around pandas.

**Comment by prakhar987** [comment]
For example if pandas is a wrapper on top of numpy...it can support something like addition of a numpy array with a pandas series directly.

Inappropriate for pandas and numpy (indexes and all) but if the wrapper on top of pandas is very minimal then probably i should be able to directly interact it with pandas objects.

**Comment by jreback** [comment]
you would almost certainly need to subclass, not a great idea. This is out of scope for pandas. However if you have patches that make it work then happy to take them.
