### ISSUE TITLE
drop_duplicates: is return value a full new DataFrame object?

### ISSUE THREAD

**Issue by pauljohn32** [pandas-dev/pandas#26044]
#### Code Sample

I want to sort a data frame by a series that has both string and numeric values.  Today I have a sequence of commands that seems to 'work', except when the .drop_duplicates method is used. Along the way I had some trouble because a series that has both letters and numbers cannot be used to sort, and I thought that was causing my problem. However, I realized later that drop_duplicates() does not return a fully workable DataFrame. 

Here I have drop_duplicates to create a second DataFrame object, and the new thing df2 just doesn't work well:

```python
x = pd.Series([1, 1, 2, 2, 2, 3, "."])
y = pd.Series([1, 1, 2, 2, 2, 3, np.nan])
df = pd.DataFrame({"old": x, "new": y})
df2 = df.drop_duplicates()
df2['oldsort'] = df2['old']
## causes error sorting, must convert oldsort to string
## df2.sort_values(by = ["oldsort"], axis = 0)
df2['oldsort'] = df2['oldsort'].astype(str)
df2.sort_values(by = ["oldsort"], axis = 0)
```
#### Problem description

Output is littered with warnings like this:

```
/home/pauljohn/LinuxDownloads/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:312: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
```

Eventually I traced problem back to `drop_duplicates`. Although it seems to be a data frame object, it does not respond well to anything I want to do. Here is an alternative method I use to achieve same purpose:

```{python}
x = pd.Series([1, 1, 2, 2, 2, 3, "."])
y = pd.Series([1, 1, 2, 2, 2, 3, np.nan])
df = pd.DataFrame({"old": x, "new": y})
df['oldsort'] = df['old'] 
df['oldsort'] = df['oldsort'].astype(str)
df.sort_values(by = ["oldsort"], axis = 0)
df.drop(['oldsort'], axis=1)
df2 = df.drop_duplicates()
```

I'm not confident that the output from drop_duplicates() is actually a full data frame, however, so I don't trust the last step very much :)

#### Expected Output

a new data frame in which columns can be copied and altered.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.18.0-16-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 4.3.1
pip: 19.0.3
setuptools: 40.8.0
Cython: 0.29.6
numpy: 1.16.2
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.4.0
sphinx: 1.8.5
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: 1.2.1
tables: 3.5.1
numexpr: 2.6.9
feather: None
matplotlib: 3.0.3
openpyxl: 2.6.1
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.5
lxml.etree: 4.3.2
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.3.1
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by mroeschke** [comment]
A few things.

1) The `SettingWithCopyWarning` is just a warning about this possibility. https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#indexing-view-versus-copy

2) `df2.sort_values(by = ["oldsort"], axis = 0)` does not operate inplace by default (i.e. doesn't modify `df2`). Either specify `inplace=True` or `df3 = df2.sort_values(..)`
