### ISSUE TITLE
date_range() option for closed='both' documented but not implemented

### ISSUE THREAD

**Issue by eai-eo** [pandas-dev/pandas#26040]
#### Problem description

The docstring for `pandas.date_range()`'s `closed` argument says:     
```
closed : {None, 'left', 'right'}, optional
        Make the interval closed with respect to the given frequency to
        the 'left', 'right', or both sides (None, the default).
```
Basically, this argument sets whether the date range includes or excludes the start and end dates. But I think 'both' is not possible. 

Either the docstring needs changing or (preferably) a 'both' option should be added.

#### Links to the relevant code

Here's the `date_range()` function (whose docstring I copied above):
https://github.com/pandas-dev/pandas/blob/master/pandas/core/indexes/datetimes.py#L1403
it passes `closed` to `DatetimeArray._generate_range()`

which is here:
https://github.com/pandas-dev/pandas/blob/master/pandas/core/arrays/datetimes.py#L421
and which passes `closed` to: `dtl.validate_endpoints(closed)`

which is here, and is where the `validate_endpoints(closed)` would need changing to add a 'both' option, or to allow 'left' and 'right' to be set simultaneously:
https://github.com/pandas-dev/pandas/blob/master/pandas/core/arrays/datetimelike.py#L1471-1501 

Thanks!

**Comment by Liam3851** [comment]
Both sides closed is the default, as noted in your document snip above:
```
both sides (None, the default)
```

So to get a closed interval on both sides you either don't specify the closed parameter at all, or you specify `closed=None`.

You cannot specify 'both' as a string, that's true, but I don't know why you would want to since it's the default behavior. 

Alternatively, are you trying to create an open interval rather than a closed interval? That currently isn't supported directly but you can probably do `date_range(...)[1:-1]` depending on your use case.

**Comment by eai-eo** [comment]
I see, thank you. I did mean that I wanted an open interval. My confusion came from imagining that `closed=None` means not closed, ie open. 

Currently I do have something like `date_range(...)[1:-1]`, but it seemed odd that only three of the four combinations are supported. I'm happy for the issue to be closed if this is not a priority though.

**Comment by mroeschke** [comment]
As @Liam3851 mentions, `None` means closed on both sides. I don't think it's worth adding a `'both'` alias for that.

Likewise, having an `'open'` alias for `date_range(...)[1:-1]` doesn't seem that compelling either since the post-indexing operation is fairly clear and straightforward as well.
