### ISSUE TITLE
sort_index throws IndexError for some permutations

### ISSUE THREAD

**Issue by soerenwolfers** [pandas-dev/pandas#26053]
#### Code Sample

```python
df = pd.DataFrame(list(range(8)))
a.index = pd.MultiIndex.from_product([[0,1]]*3)
a.sort_index(level=[1,2,0])
```
#### Problem description

This throws an `IndexEror: pop index out of range`. 
If I change the order to `[2,0,1]`, it doesn't.

python: 3.6.6.final.0
pandas: 0.24.2
numpy: 1.15.4

**Comment by WillAyd** [comment]
Please provide fully reproducible code - it's not clear what `a` here is

**Comment by jayanthkaturi** [comment]
```python
## a -> df
df = pd.DataFrame(list(range(8)))
df.index = pd.MultiIndex.from_product([[0,1]]*3)
df.sort_index(level=[1,2,0])
```

**Comment by WillAyd** [comment]
OK thanks for clarifying. The both seem to fail:

```python
df.sort_index(level=[2,1,0])
df.sort_index(level=[1,2,0])
```

`sort_remaining` doesn't appear to have an impact. One pattern that may be apparent there is that both failures use all of the level and have the initial level as the last of the sort.

May or may not be related to issue - in any case investigation and PRs are always welcome!
