### ISSUE TITLE
can we execute sql on dataframe like spark?

### ISSUE THREAD

**Issue by gwy1995** [pandas-dev/pandas#26056]
Like spark-sql,can we execute sql on dataframe to transform data ?
for example:
```python
import pandas as pd
df=pd.DataFrame({"a":[1,1,2],"b":[2,3,4]})
df
# 		a	b
# 	0	1	2
# 	1	1	3
# 	2	2	4
df.create_temp_view("t")
result=df.sql("select a, sum(b) from t group by a")
result
# 		a	sum(b)
# 	0	1	5
# 	1	2	4

```

**Comment by jorisvandenbossche** [comment]
This is not available in pandas (and also out of scope at the moment, I would say). 
But there are some external packages that do this, like https://github.com/yhat/pandasql
