### ISSUE TITLE
pd.to_hdf throws AttributeError: module 'tables' has no attribute '__version__'

### ISSUE THREAD

**Issue by mfittere** [pandas-dev/pandas#26052]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd                                                     
                                                                         
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]},index=['a', 'b', 'c'])
df.to_hdf('data.h5', key='df', mode='w')               
```
#### Problem description

[The standard example (see above) throws the following error:
```python
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    df.to_hdf('data.h5', key='df', mode='w')
  File "/zpool/software/apps/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 1996, in to_hdf
    return pytables.to_hdf(path_or_buf, key, self, **kwargs)
  File "/zpool/software/apps/anaconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 278, in to_hdf
    complib=complib) as store:
  File "/zpool/software/apps/anaconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 491, in __init__
    self.open(mode=mode, **kwargs)
  File "/zpool/software/apps/anaconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 576, in open
    tables = _tables()
  File "/zpool/software/apps/anaconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 249, in _tables
    if LooseVersion(tables.__version__) < LooseVersion('3.0.0'):
AttributeError: module 'tables' has no attribute '__version__'
```
I did a fresh install of anaconda version 4.6.11 and the output of 
```
conda list pytables
```
is
```
pytables                  3.4.4            py37ha205bf6_0
```
=> pytables version should be bigger than 3.0.0
]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-47-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 4.3.1
pip: 19.0.3
setuptools: 40.8.0
Cython: 0.29.6
numpy: 1.15.1
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.4.0
sphinx: 1.8.5
patsy: 0.5.0
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: 1.2.1
tables: None
numexpr: 2.6.8
feather: None
matplotlib: 2.2.3
openpyxl: 2.6.1
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.5
lxml: 4.3.2
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.3.1
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
]

</details>

**Comment by chris-b1** [comment]
This should be working - do you maybe have another module `tables` in your environment/script? Try this:
```python
import tables
print(tables.__file__)
```

**Comment by mfittere** [comment]
This was the issue! I had a module called tables in another python packages. I had added the path recently to my python path.

I apologize for reporting it as a bug and wasting your time. Thanks a lot for your help! I am closing the issue also.
