### ISSUE TITLE
Pandas to_csv not writing correctly to nas but working on lokal folders

### ISSUE THREAD

**Issue by Detzi88** [pandas-dev/pandas#26057]
I wrote a function which should remove duplicate lines from all .csv files in a certain path. When i run the skript on lokal ressources it works fine but when i enter a target in my nas the skript finds and states to process all files but does not drop any duplicate lines. Instead it messes up some lines and occasionally a reprocessing throws: "CRITICAL:root:'utf-8' codec can't decode byte 0xa0 in position 0: invalid start byte"
which seems also to be caused by through the skript messed up data.

I tried os.chdir(path) to make the execution path the target path - No change. I tried file as filename only and as full path - No change. if i read the file from the nas and save it locally, it works again.
I am using Win7 x64

my function looks like this:
```python
compress(path):
    codec='utf-8'
    file=path+name
    df = pd.read_csv(file, sep=';',lineterminator='\n', encoding=codec, index_col=0)
    df.drop_duplicates(subset=None, keep='first', inplace=True)
    df.to_csv(file, header=True, sep=';',line_terminator='\n', encoding=codec, mode='w')
    return 0
``` 

``` 
My Data look like:
;a;b;c;d;e
0;1;1;1;1;1
1;1;1;1;1;1
2;1;1;1;1;1
3;1;1;1;1;1
4;1;1;1;1;1

out comes:

;a;b;c;d;e
0;1;1;1;1;1

1;1;1;1;1;1
2;1;1;1;1;1
3;1;1;1;1;1
4;1;1;1;1;1

I would expect:

;a;b;c;d;e
0;1;1;1;1;1
``` 
Which is also the result when the data are stored localy and not in the nas. Whats wrong here?

**Comment by gfyoung** [comment]
@Detzi88 : Let me try to understand what's happening here:

* Which operation is raising the error?  `read_csv` or `to_csv`?
* When `read_csv` works, what does `df` look before you call `df.to_csv` ?

**Comment by Detzi88** [comment]
- to_csv is misbehaving but does not throw an error.

when reading the data with read_csv() logging.warning(df) returns:
 a  b  c  d  e\r
0  1  1  1  1    1
1  1  1  1  1    1
2  1  1  1  1    1
3  1  1  1  1    1
4  1  1  1  1    1

after dropping logging.warning(df) returns:
a  b  c  d  e\r
0  1  1  1  1    1

up until this point it makes no difference between HDD an NAS but when wrote to the nas by to_csv the out.csv file looks like:
;a;b;c;d;e
0;1;1;1;1;1

1;1;1;1;1;1
2;1;1;1;1;1
3;1;1;1;1;1
4;1;1;1;1;1

**Comment by gfyoung** [comment]
Ah, okay, so the NAS issue lies with `to_csv`.  Alright: so what happens if you try writing to a different file instead of `file` ?  Do you get the output that you expect?  Trying to widdle down the issue here.

**Comment by Detzi88** [comment]
Yes, creating a new files gives me a a .csv with the correct contents:
;a;b;c;d;e
0;1;1;1;1;1

**Comment by Detzi88** [comment]
Ok, when i open say "in.csv" the file with Notepad++ and insert:
;a;b;c;d;e
0;1;1;1;1;1
1;1;1;1;1;1
2;1;1;1;1;1
3;1;1;1;1;1
4;1;1;1;1;1

save, close and reopen it has suddenly become:
;a;b;c;d;e
0;1;1;1;1;1
1;1;1;1;1;1
2;1;1;1;1;1
3;1;1;1;1;1
4;1;1;1;1;1
;1.12;1.13;1.14;1.15;1
4;1.16;1.17;1.18;1.19;11;1.20;1

Oo wtf? Maybe it isn't pandas after all? Now i am really confused!

**Comment by gfyoung** [comment]
That's really weird indeed!  The code example you gave...did you run that with `file` already existing?  Can you try deleting the file located at wherever `file` is and run the code again?

**Comment by Detzi88** [comment]
For the test i made above, i created a seperate path in the NAS. The files used were created right before running the skript.

**Comment by gfyoung** [comment]
@Detzi88 : So if I'm understanding you correctly, the files already existed prior to running the script?  What happens if they don't exist before you run the script?

**Comment by Detzi88** [comment]
@gfyoung : No the files i created to test the script were new ones in a freshly creatd path . I had just made them, pasting in the same data i posted here.

**Comment by gfyoung** [comment]
To confirm: does `out.csv` have the correct result if you do that?

**Comment by Detzi88** [comment]
Yes as i already said, if i let the skript create a new file, the output is correct.

**Comment by gfyoung** [comment]
Alright, so it looks like something is weird with trying to overwrite an existing file...unclear whether it's a NAS issue or a `pandas` issue though.

**Comment by Detzi88** [comment]
So i have to diffrent types of "NAS" one are hooked up USB drives to my Netgear router is a "Readyshare" thing. This is the one that makes the trouble. I luckily have also a "WD Mycloud" which is also a samba share but if i copy the data to this drive and run the skript everything seems to work.

Im now at loss with my "readyshare" if i open say a logs deleting its content and reopening, the content hasn't been deleted and is magicaly restored. I get no errors whatsoever and resetting accesspermission does't work either. This sucks.
