### ISSUE TITLE
DOC: clipboard library missing in doc env on travis

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#26075]
The doc builds sees the following failure: 

```
PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.org 
```

which is happening since the refactor of the CI envs in https://github.com/pandas-dev/pandas/pull/24632. In unifying things we might have by accident removed some clipboard related things for the doc build.

cc @saurav2608 if you want to take a look at this, always welcome

**Comment by jorisvandenbossche** [comment]
Going through the diff of that PR, I actually don't notice anything related to clipboard (no occurrence of xclip or xsel, ..)

But according to the travis logs, it is still that commits that started to fail (of course can also be something unrelated to the diff, but I don't directly see any change in library versions), https://travis-ci.org/pandas-dev/pandas/jobs/515983449 vs https://travis-ci.org/pandas-dev/pandas/jobs/515983803

**Comment by saurav2608** [comment]
Definitely introduced post #24632 . I will investigate and confirm.

**Comment by jorisvandenbossche** [comment]
Thanks for taking a look!

**Comment by jorisvandenbossche** [comment]
@jreback this can stay on the 0.25 milestone. Currently we show an error in the docs. Last resort, we just convert it to a plain code block before the release, to at least *show* the expected behaviour.

**Comment by jreback** [comment]
sure np
