### ISSUE TITLE
TST: consolidate set_op tests across indexes

### ISSUE THREAD

**Issue by fdroessler** [pandas-dev/pandas#26077]
#### Problem description

Following up from a discussion in: https://github.com/pandas-dev/pandas/pull/25913#discussion_r272157952

Currently `set_ops` are not tested across all indexes and should probably be consolidated in a new file maybe `pandas/tests/indexes/test_setops.py` pulling tests from subdirectories and relevant tests from `pandas/tests/indexes/test_base.py` and potentially other files together.

@jreback Would be good to get your input as well. I know that @reidy-p wanted to have a look at reorganising tests as well.

I'll start looking into this and adding to this issue with an idea of how to proceed but input would be welcome.

**Comment by jbrockmendel** [comment]
We're moving in the other direction.  Closing.
