### ISSUE TITLE
Reading pdf tables directly using Pandas

### ISSUE THREAD

**Issue by hishamsajid** [pandas-dev/pandas#26073]
Would be pretty neat if you could read tables directly from pdf into a pandas dataframe

**Comment by jreback** [comment]
see https://github.com/euske/pdfminer

out of scope for pandas

**Comment by jorisvandenbossche** [comment]
Another one is https://github.com/socialcopsdev/camelot

An addition to the ecosystem.rst page in the documentation to mention some of those libraries is certainly welcome.
