### ISSUE TITLE
Dtype attributes (eg PeriodDtype.freq) should not be settable

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#26096]
You can currently do this:

```
In [2]: pdt = pd.PeriodDtype(freq='D')

In [3]: pdt
Out[3]: period[D]

In [4]: pdt.freq = 'F'  

In [5]: pdt  
...
AttributeError: 'str' object has no attribute 'freqstr'
```

I think in general it would be good to make those dtype specific attributes not settable (this is already the case for DatetimeTZDtype.unit/tz, but not yet for the above case of PeriodDtype, and also not eg for IntervalDtype.subtype).

**Comment by jbrockmendel** [comment]
Only/mainly for internal dtypes or also for downstream EA dtypes?

Defining them in cython is the strongest way to make these immutable, but can introduce circular dependencies which are the worst.

Patching setattr like we do for DateOffset is another option

**Comment by jorisvandenbossche** [comment]
We only control our own dtypes, so I was talking about that (in principle a downstream EA dtype author can do what he/she wants?)

> Defining them in cython is the strongest way to make these immutable,

Just making them a property instead of attribute in Python should also suffice? That's what I am doing in #26067, and is also already done in CategoricalDtype / DatetimeTZDtype.

**Comment by TomAugspurger** [comment]
This was fixed by https://github.com/pandas-dev/pandas/pull/26067
