### ISSUE TITLE
export a R-compatible msgpack file?

### ISSUE THREAD

**Issue by randomgambit** [pandas-dev/pandas#26092]
Hello the dream team

Please have a look here https://stackoverflow.com/questions/55578378/how-to-exchange-msgpack-files-between-python-and-r

Would it be possible/doable to have `pandas` export a `msgpack` file that can be read in `R`?

What do you think?
Thanks!

**Comment by jreback** [comment]
magpack has very little support; this is also a custom protocol

much better to use arrow

**Comment by randomgambit** [comment]
fair enough @jreback , fair enough. Only issue we still dont have an R `read_parquet()` function... :(
