### ISSUE TITLE
Improve documentation for assert_frame|series_equal

### ISSUE THREAD

**Issue by qris** [pandas-dev/pandas#26101]
#21528 improved the documentation for assert_almost_equal, but this is actually an undocumented function (not listed in the Pandas docs) and the same issue seems to apply to both `assert_series_equal` and `assert_frame_equal`, which are documented.

Could we apply the same change as #21580 to those methods too, i.e. add the following text:

> When comparing two numbers, if the first number has magnitude less than 1e-5, we compare the two numbers directly and check whether they are equivalent within the specified precision. Otherwise, we compare the **ratio** of the second number to the first number and check whether it is equivalent to 1 within the specified precision.

**Comment by WillAyd** [comment]
Makes sense - a PR from you would certainly be welcome

**Comment by sandepp123** [comment]
I want to work on this, as it looks like it is good for first timer.
