### ISSUE TITLE
TypeError on while retrieving values from a Series

### ISSUE THREAD

**Issue by rsaim** [pandas-dev/pandas#26107]
```python
In [37]: import pandas as pd
    ...: import numpy as np
    ...: from pandas.core.indexes.datetimes import DatetimeIndex
    ...:
    ...: data = np.ma.array(data=DatetimeIndex(['2011-01-01']))
    ...: s = pd.Series(data=data)
    ...: s.values # FAILS
OUTPUT:
TypeError                                 Traceback (most recent call last)
<ipython-input-37-b6f50d56e315> in <module>
      5 data = np.ma.array(data=DatetimeIndex(['2011-01-01']))
      6 s = pd.Series(data=data)
----> 7 s.values # FAILS

/home/user1/python3.7/site-packages/pandas/core/series.py in values(self)
    472                '2013-01-03T05:00:00.000000000'], dtype='datetime64[ns]')
    473         """
--> 474         return self._data.external_values()
    475
    476     @property

/home/user1/python3.7/site-packages/pandas/core/internals/managers.py in external_values(self)
   1545
   1546     def external_values(self):
-> 1547         return self._block.external_values()
   1548
   1549     def internal_values(self):

/home/user1/python3.7/site-packages/pandas/core/internals/blocks.py in external_values(self)
   2234
   2235     def external_values(self):
-> 2236         return np.asarray(self.values.astype('datetime64[ns]', copy=False))
   2237
   2238

TypeError: astype() got an unexpected keyword argument 'copy'
```
#### Problem description

This breaks with **0.24.2** but not with **0.23.4**.

#### Expected Output
masked_array(data=['2011-01-01T00:00:00.000000000'],
             mask=False,
       fill_value=numpy.datetime64('NaT'),
            dtype='datetime64[ns]')

OR

['2011-01-01T00:00:00.000000000']

#### Output of ``pd.show_versions()``
<details>
In [38]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.rsaim.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 4.4.0
pip: 10.0.1
setuptools: 39.0.1
Cython: 0.29.5
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.3.0
sphinx: 2.0.0
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2017.3
blosc: 1.8.1
bottleneck: None
tables: 3.4.4
numexpr: 2.6.9
feather: None
matplotlib: 2.2.3
openpyxl: 2.6.2
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.5
lxml.etree: 3.6.0
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.2.5+4.rsaim
pymysql: None
psycopg2: 2.7.7 (dt dec pq3 ext)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by jreback** [comment]
try upgrading numpy

**Comment by rsaim** [comment]
The issue actually is the incompatible code in **pandas 0.24.2** with **numpy 1.14.3**. [This commit](https://github.com/numpy/numpy/commit/22404c9ddd505015fd019773619a755fd2e61959#diff-e85f023d9c07df014a190b485db72c3d) added the `copy` argument to `MaskedArray.astype` which **pandas 0.24.2** (wrongly?) assumes exists in all **numpy** versions.

FTR, this works fine with **numpy 1.15.0**. Thanks to Jeff for this pointer.

**Question**: Is it possible to add checks in pandas code to not make the incorrect assumption about `MaskedArray.astype` pointed above?

**Comment by MarcoGorelli** [comment]
closing as the minimum version of numpy is now 1.16.5
