### ISSUE TITLE
Should assert_frame_equal allow for a 'None' diff when there is actually a difference?

### ISSUE THREAD

**Issue by lovemeblender** [pandas-dev/pandas#26118]
#### Code Sample, a copy-pastable example if possible

From this module used in dataframes' comparison [here](https://github.com/pandas-dev/pandas/blob/master/pandas/util/testing.py#L829).

#### Problem description

First of all, great job, I am excited to be using Pandas and thanks for everything! :)

While asserting for dataframe equality in PyTest using PyCharm I get a message that some values are different (100.0%) but the diff is None (diff = None). This is rather confusing and since there is no obvious difference between these values I struggle to find it. 

#### Expected Output
If diff is none, I would expect for `assert_frame_equal` method to not throw an exception and return true. If the assertion is false and an exception is being raised I would expect it to always have some diff to show. If for any reason, having a "diff" is not feasible, I would expect this to be injected in the output message.

#### Output of ``pd.show_versions()``

<details>
Latest
</details>

**Comment by WillAyd** [comment]
Please provide a code sample to reproduce what you are talking about

**Comment by lovemeblender** [comment]
Thanks for the answer @WillAyd. 

I am afraid I can't share the data I tested this against. However, it can already be seen in the [code](https://github.com/pandas-dev/pandas/blob/master/pandas/util/testing.py#L829) that `msg` is being populated unconditionally, which means that there is a possibility of failing the equal frames tests but `diff` can be `None`.

**Comment by WillAyd** [comment]
Would still just need some kind of code sample to confirm what you are looking for. It doesn't necessarily need to be the data you have if it's confidential, just something else to reproduce.

This guide might be helpful:

http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by lovemeblender** [comment]
Cool, I'll try to do my best given that I can't provide the actual data.

I am unit testing a python function using pytest: essentially running the actual method and storing the result in a variable called `actual_df` and testing this against an expected result from fixtures and storing it as `expected_df`. As suspected these are both Pandas dataframes.

Finally I am testing equality as:
`pd.testing.assert_frame_equal(expected_df, actual_df, check_exact=False`

The output is roughly (just replaced the actual data parts with random names:

> obj = 'DataFrame.iloc[:, 3]'
message = 'DataFrame.iloc[:, 3] values are different (100.0 %)'
left = "[{'key_1': 'False', 'key_2': 'message'... \nmore messages ... , 'key_n': 'value_n'}]"
right = '[{"key_1": "False", "key_2": "message"... \\nmore messages ... , "key_n": "value_n"}]"
diff = None
...

There are two issues here:
1. While left and right are roughly equal, the assertion fails because of single/double quotes differences and new line symbols. While it would be nice for an extra flag to be added ignoring the above (not sure if it already exists!), this is not the reason I opened the issue.
2. More importantly, seeing that values are different 100% is confusing for two reasons:
  a. Clearly they are not 100% different, and
  b. If they are 100% different, how come the diff is None.

**Comment by mroeschke** [comment]
We're happy to reopen this issue when we can validate the issue with a reproducible example

**Comment by dschneiderch** [comment]
here is an example:
why do I get `None` if the dataframes are equal?

when I run my test with `pytest` I get 
```
>       assert assert_frame_equal(snapshotdf, TEST_DF)
E       assert None
E        +  where None = assert_frame_equal(                                                              cameralabel  ...                                        ...019-03-12 00:09:11 2019-03-12       PSII0  ...  C6-GoldStandard_PSII-20190312T000911-PSII0-15.png\n\n[1 rows x 3 columns],                                                               cameralabel  ...
                              ...019-03-12 00:09:11 2019-03-12       PSII0  ...  C6-GoldStandard_PSII-20190312T000911-PSII0-15.png\n\n[1 rows x 3 columns])

tests\test_data.py:50: AssertionError
```

## function
```
# -*- coding: utf-8 -*-
import os
import glob
import re as re
from datetime import timedelta
import pandas as pd

def get_imagemetadata(fns):
    '''
    Get image filenames and metadata from filenames
    Input:
        fns: filenames of image files
    Returns:
        snapshotdf: pandas dataframe with snapshot metadata
    '''

    flist = list()
    for fn in fns:
        f = re.split('[-]', os.path.splitext(os.path.basename(fn))[0])
        f.append(fn)
        flist.append(f)

    try:
        fdf = pd.DataFrame(flist,
                            columns=[
                                'plantbarcode', 'experiment', 'timestamp',
                                'cameralabel', 'frameid', 'filename'
                            ])
    except ValueError as e:
        raise ValueError('The filenames did have correctly formated metadata separated by "-".') from e

    # convert date and time columns to datetime format
    fdf['datetime'] = pd.to_datetime(fdf['timestamp'])
    fdf['jobdate'] = fdf.datetime.dt.floor('d')

    #create a jobdate to match dark and light measurements. dark experiments after 8PM correspond to the next day's light experiments
    fdf.loc[fdf.datetime.dt.hour >= 20,
            'jobdate'] = fdf.loc[fdf.datetime.dt.hour >= 20,
                                    'jobdate'] + timedelta(days=1)

    # convert image id from string to integer that can be sorted numerically
    fdf['frameid'] = fdf.frameid.astype('uint8')
    fdf = fdf.sort_values(['plantbarcode', 'datetime', 'frameid'])

    fdf = fdf.set_index(['plantbarcode', 'experiment', 'datetime',
                         'jobdate']).drop(columns=['timestamp'])

    return fdf
```

## test
```
import pytest
from pandas.testing import assert_frame_equal
from pandas import DataFrame
from pandas import Timestamp


def test_get_imagemetadata():
    TEST_FNS = ['C6-GoldStandard_PSII-20190312T000911-PSII0-15.png']
    TEST_DF = DataFrame({
        'cameralabel': {
            ('C6', 'GoldStandard_PSII', Timestamp('2019-03-12 00:09:11'),
             Timestamp('2019-03-12 00:00:00')):
            'PSII0'
        },
        'frameid': {
            ('C6', 'GoldStandard_PSII', Timestamp('2019-03-12 00:09:11'),
             Timestamp('2019-03-12 00:00:00')):
            15
        },
        'filename': {
            ('C6', 'GoldStandard_PSII', Timestamp('2019-03-12 00:09:11'),
             Timestamp('2019-03-12 00:00:00')):
            'C6-GoldStandard_PSII-20190312T000911-PSII0-15.png'
        }
    })
    TEST_DF.index.names = ['plantbarcode', 'experiment', 'datetime', 'jobdate']
    TEST_DF['frameid'] = TEST_DF.frameid.astype('uint8')

    snapshotdf = get_imagemetadata(TEST_FNS)
    assert assert_frame_equal(snapshotdf, TEST_DF)
```

**Comment by jreback** [comment]
@dschneiderch 

these functions actually assert under the hood, otherwise they return `None` as is typical for a function that doesn't return anything, e.g. 

```
In [284]: result = tm.assert_frame_equal(pd.DataFrame(), pd.DataFrame())                                                                                           

In [285]: type(result)                                                                                                                                             
Out[285]: NoneType
```
you don't need to assert the assert
