### ISSUE TITLE
pandas.Series.shift 1 sample error

### ISSUE THREAD

**Issue by Caballero93** [pandas-dev/pandas#26120]
#### Code Sample, a copy-pastable example if possible

```python
# Creating pandas>Series with timedeltas as index - 1 microsecond step:
import numpy as np
import pandas as pd
time = np.arange(0,1, 1e-6)
time_index = pd.to_timedelta(time, unit='s')
values = np.ones(len(time_index))
sig = pd.Series(data=values, index=time_index)
# shift signal for 1000 samples
sig_shifted_2 = sig.shift(1000)
print("Sample 0: {}".format(sig_shifted_2[0]))
print("Sample 999: {}".format(sig_shifted_2[999]))
print("Sample 1000: {}".format(sig_shifted_2[1000]))
print("Sample 1001: {}".format(sig_shifted_2[1001]))

```
#### Problem description
When signal is shifted for 1000 samples, what is expected is that samples from 0 to 999 have nan value, while sample 1000 should have value form index 0 on non-shifted signal. For 10 microsecond step it works like expected, but with 1 microsecond step index 1000 still has nan value, as can be seen on the output:
![image](https://user-images.githubusercontent.com/25043401/56288627-749f7b00-611f-11e9-9893-9bb2bd0d08b9.png)
Version 0.24.2 is used

#### Expected Output
Output if 10 microsecond step is used
![image](https://user-images.githubusercontent.com/25043401/56288320-d0b5cf80-611e-11e9-9b72-bf2b51bb2345.png)

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.24.2
pytest: 4.4.0
pip: 10.0.1
setuptools: 38.5.1
Cython: 0.28.2
numpy: 1.14.3
scipy: 1.0.1
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.6
patsy: None
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.1.1
openpyxl: 1.7.0
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

**Comment by WillAyd** [comment]
The problem here is with how you are indexing the resulting data frame. To get the element at position 1000 use `sig_shifted_2.iloc[1000]`
