### ISSUE TITLE
to_html(index = False) not dropping df.columns.name in the html output

### ISSUE THREAD

**Issue by benpap24** [pandas-dev/pandas#26126]
```
df = pd.DataFrame({'A': [1,2],
                   'B': [3,4]})

df.columns.name = 'Test'

df.to_html(index = False)

#Output

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>Test</th>
      <th>A</th>
      <th>B</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th></th>
      <td>1</td>
      <td>3</td>
    </tr>
    <tr>
      <th></th>
      <td>2</td>
      <td>4</td>
    </tr>
  </tbody>
</table>
```
#### Problem description

I recently updated one of my projects from 0.23.4 to 0.24.1 and the html output  of ```df.to_html(index = False)``` changed when there is a column name (ie. one generated from when you create a pivot table).

Previously, ```df.to_html(index = False)```  would drop the column name, however now it creates an empty column with the column name.

I've also confirmed reverting to 0.23.4 fixes the issue.

#### Expected Output
```
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>A</th>
      <th>B</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>3</td>
    </tr>
    <tr>
      <td>2</td>
      <td>4</td>
    </tr>
  </tbody>
</table>
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.1
pytest: 3.8.0
pip: 10.0.1
setuptools: 40.2.0
Cython: 0.28.5
numpy: 1.16.0
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.5.0
sphinx: 1.7.9
patsy: 0.5.1
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.0
openpyxl: 2.5.6
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.1.0
lxml.etree: 4.3.0
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.11
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by WillAyd** [comment]
This is intentional. See #23788
