### ISSUE TITLE
pd.Timestamp.isoformat does not implement keyword timespec

### ISSUE THREAD

**Issue by MaximeWeyl** [pandas-dev/pandas#26131]
## Code Sample

**[IN]**
```python
import pandas as pd
now = pd.Timestamp.utcnow()
help(now.isoformat)
```
**[OUT]**
    Help on method isoformat in module pandas._libs.tslibs.timestamps:
    
    isoformat(sep='T') method of pandas._libs.tslibs.timestamps.Timestamp instance
        [sep] -> string in ISO 8601 format, YYYY-MM-DDT[HH[:MM[:SS[.mmm[uuu]]]]][+HH:MM].
        sep is used to separate the year from the time, and defaults to 'T'.
        timespec specifies what components of the time to include (allowed values are 'auto', 'hours', 'minutes', 'seconds', 'milliseconds', and 'microseconds').
    
    

**[IN]**
```python
now.isoformat(timespec="seconds")
```

**[OUT]**
    ---------------------------------------------------------------------------

    TypeError                                 Traceback (most recent call last)

    <ipython-input-8-3626478eeb62> in <module>
    ----> 1 now.isoformat(timespec="seconds")
    

    pandas\_libs\tslibs\timestamps.pyx in pandas._libs.tslibs.timestamps.Timestamp.isoformat()
    

    TypeError: isoformat() got an unexpected keyword argument 'timespec'

**[IN]**
```python
now.to_pydatetime().isoformat(timespec="seconds")
```

**[OUT]**
    '2019-04-18T07:38:50+00:00'

## Problem description

The help method has given me the feeling that I can use timespec just like I can with standard datetime objects (since python 3.6).

## Expected Output

We could mimic standard datetime.isoformat behavior, or at least remove this false information from the help message.

## Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: fr_FR.UTF-8
LOCALE: None.None

pandas: 0.24.2
pytest: 4.4.1
pip: 19.0.3
setuptools: 41.0.0
Cython: None
numpy: 1.16.2
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.4.0
sphinx: 2.0.1
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: 4.3.3
bs4: 4.7.1
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by WillAyd** [comment]
@mroeschke @jbrockmendel

**Comment by mroeschke** [comment]
`isoformat` is one function that `Timestamp` doesn't just directly inherit. I don't see why the `timespec` keyword argument can't be incorporated in as well.

One thing to note is that if we mirror  `timespec` from `datetime.datetime`, our implementation also should handle `'nanoseconds'` as an argument

**Comment by jbrockmendel** [comment]
Might be helpful to have a test checking compatibility of all the signatures between datetime vs timestamp.

**Comment by MaximeWeyl** [comment]
I have another remark : the help message is very different when looking at the Timestamp class or at the instance : 


```python
import pandas as pd
```


```python
help(pd.Timestamp.isoformat)
```

    Help on cython_function_or_method in module pandas._libs.tslibs.timestamps:
    
    isoformat(self, sep='T')
    
    


```python
help(pd.Timestamp(2019).isoformat)
```

    Help on method isoformat in module pandas._libs.tslibs.timestamps:
    
    isoformat(sep='T') method of pandas._libs.tslibs.timestamps.Timestamp instance
        [sep] -> string in ISO 8601 format, YYYY-MM-DDT[HH[:MM[:SS[.mmm[uuu]]]]][+HH:MM].
        sep is used to separate the year from the time, and defaults to 'T'.
        timespec specifies what components of the time to include (allowed values are 'auto', 'hours', 'minutes', 'seconds', 'milliseconds', and 'microseconds').

**Comment by 77QingLiu** [comment]
update this apli, please

**Comment by jreback** [comment]
> update this apli, please

@77QingLiu 
you are welcome to submit a PR to patch this

**Comment by boringow** [comment]
Hello, I am still having this same issue.

**Comment by jreback** [comment]
@boringow this is an open issue
you are welcome to submit a PR
there is an open PR but it is stale

**Comment by boringow** [comment]
How can I do a PR in this issue? can someone assign it to me please?

**Comment by boringow** [comment]
@phofl Hi again and sorry to bother, I need to be a triage member to do PR. How can I become one?

**Comment by phofl** [comment]
Everyone can open a Pull Request. I think you did one a few days back?

**Comment by boringow** [comment]
@phofl sorry, I could no do it from the mobile. I do it right now. Can you asign this task to me so I deal with it? Although I do not know git/github I have experiences with pandas and developing and I think I can solve it.

**Comment by phofl** [comment]
Assigned it to you. You can self assign through posting take in the future

**Comment by boringow** [comment]
Okay, I need some help in here as I am lacking some knowledge.
I did the same but simple quick code to start with the issue:

`import pandas as pd
import pdb

now=pd.Timestamp.utcnow()

print(now)
pdb.set_trace()
a=now.isoformat(sep="seconds")
print(a)`

To start, the keyword ' timespec ' is not defined, only the keyword 'sep' is defined, as the documentation indicates, but it is also not working.
For some reason, the debugging does not go into the: pandas._libs.tslibs.timestamps Module, 
If I try to debug the error, it says there is an error on the python codecs. 
>C:\user\python\python38-32\lib\codecs.py(309)__init__()
-> def __init__(self, errors='strict'):

TypeError: isoformat() argument 1 must be a unicode character, not str.

If we see the .isoformat method (https://github.com/pandas-dev/pandas/blob/d558bce8e9d5d4adfb0ab587be20b8a231dd1eea/pandas/_libs/tslibs/timestamps.pyx#L548)
We will always get the base, as nanoseconds from a timestamp.now() will always be zero.
How does pandas handle nanoseconds but datetime does not? I think the error is in there, But I need help.

**Comment by simonjayhawkins** [comment]
The PR for issue #38550 was closed as stale. review comments there could be useful. contributions welcome
