### ISSUE TITLE
register_index_accessor Question

### ISSUE THREAD

**Issue by achapkowski** [pandas-dev/pandas#26130]
When implementing a index accessor, does it overwrite the default ‘index’ property, or is there a way to create a custom index class to pass into index?  How could I make it iloc or loc compatible?

Additionally, the register_index_accessor, besides the init, what else is needed to properly work?  

My goal is to use an rtree index to find my content.

**Comment by WillAyd** [comment]
The accessor should just wrap the existing index so it wouldn't overwrite anything about it.

As far as a custom index class goes you probably want to use an ExtensionArray as the Index, which is discussed in #22861 but not yet implemented. Would certainly take contributions and PRs if it's something you are interested in.

@TomAugspurger

**Comment by TomAugspurger** [comment]
Agreed with @WillAyd

**Comment by achapkowski** [comment]
@WillAyd and @TomAugspurger Thank you for the suggestion, let me review the ExtensionArray as an Index and get back.  
If I read #22861, all I need to do is ensure groupby work against my custom logic for an Index?

**Comment by TomAugspurger** [comment]
I don't think that's correct. I think pandas would need to implement
support for ExtensionIndexes first. There's a stalled PR if you want to
pick it up.

**Comment by achapkowski** [comment]
Which PR?

**Comment by TomAugspurger** [comment]
I think it's referenced in the ExtensionIndex issue.
