### ISSUE TITLE
Doc for HDFStore compression unclear on what the default value of None does

### ISSUE THREAD

**Issue by chrish42** [pandas-dev/pandas#26139]
The doc for the `HDFStore` class mentions:

```    
complevel : int, 0-9, default None
            Specifies a compression level for data.
            A value of 0 disables compression.
```

That doesn't actually answer the question of what compression level is used when the default (None) is used, though. Is None translated further down to 0? it turns out yes, but you have to dig in the code to actually figure that out. And it could as well have been translated eventually to any other value.

Two options:
1. Actually change the default in the `complevel` argument to be "0". (It's an immutable object, so it's fine as a default value for a function argument.)
2. Just adjust the doc in some way.

When the right solution is decided, I can do a pull request with it. Thanks!

**Comment by WillAyd** [comment]
I think either option would be fine

**Comment by swyoon** [comment]
It seems like `complevel=None` is translated into `0`. I will add this to the docstring.
https://github.com/pandas-dev/pandas/blob/cb00deb94500205fcb27a33cc1d0df79a9727f8b/pandas/io/pytables.py#L484
