### ISSUE TITLE
Option to give service account in case of Google buckets

### ISSUE THREAD

**Issue by prateek2408** [pandas-dev/pandas#26149]
#### Code Sample, a copy-pastable example if possible

Parameters like project, token should be taken and added if provided in case of GCP buckets.

```
def get_filepath_or_buffer(filepath_or_buffer, encoding=None,
                           compression=None, mode=None, project=None, token=None):

    if mode is None:
        mode = 'rb'

    fs = gcsfs.GCSFileSystem(project=project, token=token)
    filepath_or_buffer = fs.open(
        filepath_or_buffer, mode)  # type: gcsfs.GCSFile
return filepath_or_buffer, None, compression, True
```

#### Problem description

Currently if you do a read_csv in pandas with a google bucket URL like  'pd.read_csv('gs://abc/def.csv')', there is no way you can provide service account or token details for authorization.

The library that supports reading from gcp buckets [here](https://github.com/pandas-dev/pandas/blob/master/pandas/io/gcs.py) should take **'token'** parameter as well, as shown above 

#### Output of ``pd.show_versions()``

[paste the output of ``pd.show_versions()`` here below this line]

>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-862.11.6.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 3.3.1
pip: 19.0.3
setuptools: 41.0.0
Cython: 0.27.3
numpy: 1.16.2
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.4.0
sphinx: 1.6.5
patsy: None
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: 4.7.1
html5lib: None
sqlalchemy: 1.2.0
pymysql: None
psycopg2: 2.7.3.2 (dt dec pq3 ext lo64)
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: 0.2.1

</details>

**Comment by WillAyd** [comment]
There are already a large amount of keyword arguments in read_csv so we are typically hesitant to add more, especially when they are specialized to niche data sources.

Have you tried calling open on the GCSFileSystem directly with the arguments you need and passing that to read_csv instead? Should work just as well

**Comment by prateek2408** [comment]
Yes as a workaround I can import gcsfs directly and after reading the file provide it to read_csv , it works in this case.

however this way we are not using the inbuilt functionality of supporting gcsfs in pandas

**Comment by WillAyd** [comment]
Right but this is a niche application for an optional third party dependency, and with our general direction to try and fine tune the API adding another keyword would be moving us in the opposite direction.

Closing for now as no action; can reopen in the future if ever revisited
