### ISSUE TITLE
Fix Type Annotation in pandas/core/accessor.py

### ISSUE THREAD

**Issue by vaibhavhrt** [pandas-dev/pandas#26146]
Part of #25882 

Current errors are:

    pandas\core\accessor.py:14: error: Need type annotation for '_accessors'

PR coming soon

**Comment by vaibhavhrt** [comment]
@WillAyd `pandas.core.apply` is in mypy.ini but mypy shows no errors in that file. Should I just remove it from mypy.ini in same PR for this issue or should I open a new issue and PR

**Comment by WillAyd** [comment]
Just remove is fine
