### ISSUE TITLE
Plotting ExtensionArrays

### ISSUE THREAD

**Issue by andrewgsavage** [pandas-dev/pandas#26173]
I'd like to plot data from an ExtensionArray. This currently results in an error `TypeError: Empty 'DataFrame': no numeric data to plot`

This is because the EA data is filtered out. Adding the ExtensionDtype to the filter criteria makes the plot work.
https://github.com/pandas-dev/pandas/blob/master/pandas/plotting/_core.py#L367 

```python3
numeric_data = data.select_dtypes(include=[np.number,
                                               "datetime",
                                               "datetimetz",
                                               "timedelta", 
                                               pint.PintType])

```

Could we get a property of the ExtensionDtype that flags the dtype as holding plotable numeric data?

**Comment by andrewgsavage** [comment]
related issue https://github.com/hgrecco/pint-pandas/issues/9

**Comment by TomAugspurger** [comment]
What version of pandas?

https://github.com/pandas-dev/pandas/pull/25590 coerces EAs to ndarray before plotting. If `np.asarray(your_array)` returns a numeric type then it should be passed through to matplotlib, though it'll be a regular NumPy dtype, not your extension dtype. Does that suffice?

**Comment by andrewgsavage** [comment]
'0.25.0.dev0+430.gc79b7bb' - from a few days ago with that merge included.

`np.asarray(your_array) ` return an object dtype, so is filtered out by select_dtypes, eg:
`np.array(df.length)`
`array([<Quantity(1, 'meter')>, <Quantity(2, 'meter')>], dtype=object)`

so no it doesn't suffice. 

Passing quantity objects as opposed to floats to matploblib will allow the units converting part of matplotlib to work.*

*with some changes to pint.

**Comment by andrewgsavage** [comment]
@TomAugspurger have you had a chance to look at this?

**Comment by TomAugspurger** [comment]
Most likely DataFrame.select_dtypes(include=[np.number]) should include
extension array types whose .dtype._is_numeric is True.

**Comment by andrewgsavage** [comment]
fixed by https://github.com/pandas-dev/pandas/pull/38246
