### ISSUE TITLE
Add Type and Final pandas._typing

### ISSUE THREAD

**Issue by vaibhavhrt** [pandas-dev/pandas#26175]
Since we are not merging #25975 `Type` and `Final` needs to be added to `pandas._typing` module.

`Final` is required for PR #25961 
`Type` is required to stay compatible with python 3.5.1 as `Type` was added in 3.5.2 [python docs](https://docs.python.org/3/library/typing.html#typing.Type)

**Comment by vaibhavhrt** [comment]
PR on the way...

**Comment by vaibhavhrt** [comment]
On second thought it looks too complicated and time consuming for me. Someone else please pick it up. @TomAugspurger maybe you would be interested in it.

**Comment by jreback** [comment]
you can pretty much just directly vendor  typing_extensions

**Comment by vaibhavhrt** [comment]
@jreback I think you mean copy paste the relevant parts from the source code of typing_extensions. I took a look at their source code but it's a bit complicated for me. I will take a look at it again after a few days when I get some time and see what I can do.

**Comment by TomAugspurger** [comment]
What benefit do we get from adding Final to these annotations?

**Comment by WillAyd** [comment]
Final would just indicate that a variable is not supposed to be subsequently modified.

FWIW I consider it to be a nice to have but not a blocker in the PR where it is mentioned. If we consider bumping min Python version to 3.5.2 then alternately we don’t need to vendor anything

**Comment by gfyoung** [comment]
My preference is to vendor for now.  Bumping min Python version, not matter how small, is still a relative big change to codebase.

**Comment by TomAugspurger** [comment]
My preference is to just not add these annotations.

**Comment by WillAyd** [comment]
> My preference is to just not add these annotations.

Final is fine to ignore. I think Type[] is very useful though and that didn't appear until 3.5.2 along with a few (less critical IMO) items:

https://docs.python.org/3.5/whatsnew/changelog.html#id28

> My preference is to vendor for now. Bumping min Python version, not matter how small, is still a relative big change to codebase.

Have we bumped bug fix releases in the past? We are already dropping Py27 this release so wondering if moving to 3.5.2 from there is adding incremental risk

**Comment by gfyoung** [comment]
I don't recall if we have done incremental bumps in the past, but if there is interest, I think that should discussion should be handled separately in another issue / PR.

**Comment by WillAyd** [comment]
Closing this as is. Can discuss move to 3.5.2 in another issue
