### ISSUE TITLE
Exception: Prophet object can only be fit once. Instantiate a new object.

### ISSUE THREAD

**Issue by ShahWaseem** [pandas-dev/pandas#26174]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import pystan
from fbprophet import Prophet

plt.style.use('fivethirtyeight')
y = [t1_tmax['date'], t1_tmax['value']]
import pandas as pd
df = pd.DataFrame({'date': y[0], 'value': y[1]})

df.dtypes

df = df.rename(columns={'date': 'ds','value': 'y'})
df

my_model = Prophet(interval_width=0.95)
my_model.fit(df) 

```
#### Problem description

I have installed the latest Pystan and fbprophet versions:
pystan 2.17.1.0
fbprophet 0.4.post2

Currently, I'm using conda 4.6.14 with Python 3.6.7 version as suggested after uninstalling 3.7 in other threads!

#### Output of ``my_model.fit(df) ``

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-134-2eba425e3c88> in <module>
      2 #with weekly_seasonality=True
      3 #instantiate Prophet
----> 4 my_model.fit(df) #fit the model with your dataframe

~\Anaconda3\Anaconda\lib\site-packages\fbprophet\forecaster.py in fit(self, df, **kwargs)
   1010         """
   1011         if self.history is not None:
-> 1012             raise Exception('Prophet object can only be fit once. '
   1013                             'Instantiate a new object.')
   1014         if ('ds' not in df) or ('y' not in df):

Exception: Prophet object can only be fit once. Instantiate a new object.

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by jreback** [comment]
this is the pandas tracker and not related to Prophet in any way

**Comment by ShahWaseem** [comment]
> this is the pandas tracker and not related to Prophet in any way

Okay cool thanks
