### ISSUE TITLE
Creating an empty dataframe with columns names fails in python 3.7, works in python 3.6

### ISSUE THREAD

**Issue by Iwontbecreative** [pandas-dev/pandas#26184]
#### Code Sample, a copy-pastable example if possible

```python
data = []
pd.DataFrame(data, columns=['col'])
```

#### Problem description

The expected behaviour should be the 3.6 one on both cases. Failing that, it should be consistent for 3.6 and 3.7.

np version 1.15.2 ; pandas version 0.23.4 

#### Expected Output

Expected: Empty dataframe with one col named 'col' in both cases.
Python 3.6: above
Python 3.7: `TypeError: int() argument must be a string, a bytes-like object or a number, not '_NoValueType'`

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Darwin
OS-release: 17.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 4.4.0
pip: 19.0.3
setuptools: 40.8.0
Cython: None
numpy: 1.16.2
scipy: 1.2.0
pyarrow: None
xarray: None
IPython: 7.3.0
sphinx: None
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: 1.2.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by WillAyd** [comment]
Can you try on master? Just worked fine for me with the below:

<details>

INSTALLED VERSIONS
------------------
commit: 947bd7662afa8b6dc4406ec52cefc39d76d2d6cd
python: 3.7.2.final.0
python-bits: 64
OS: Darwin
OS-release: 18.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.25.0.dev0+448.g947bd7662
pytest: 4.3.0
pip: 19.0.3
setuptools: 40.8.0
Cython: 0.29.5
numpy: 1.15.4
scipy: 1.2.1
pyarrow: 0.11.1
xarray: 0.11.3
IPython: 7.3.0
sphinx: 1.8.4
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.9
feather: None
matplotlib: 3.0.2
openpyxl: 2.6.0
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.5
lxml.etree: 4.3.1
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.2.18
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: 0.2.0
fastparquet: 0.2.1
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by Iwontbecreative** [comment]
On a fresh environment on master, it does not seem to crash. I think it might have been an interaction with `autoreload` in notebooks. Can be closed for now and if I can find a good way to reproduce I'll re-open. 

Thanks for the quick answer
