### ISSUE TITLE
AWS_S3_HOST environment variable no longer available

### ISSUE THREAD

**Issue by jakobkogler** [pandas-dev/pandas#26195]
In the [What's New - Other enhancements](https://pandas.pydata.org/pandas-docs/version/0.21/whatsnew.html#whatsnew-0180-enhancements-other) section from the 18.0 release it says that you can define the environment variable `AWS_S3_HOST`. 

Therefore, when setting this environment variable, together with `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` I expected the following code to work.

```python
import pandas as pd
df = pd.DataFrame(dict(a=[1, 2, 3], b=[4, 5, 6]))
df.to_csv(fs.open('s3://bucket/key', mode='w'))
```

The script crashes with:

```
Exception ignored in: <bound method S3File.__del__ of <S3File bucket/key>>
Traceback (most recent call last):
  File "/home/xxx/.local/share/virtualenvs/xxx/lib/python3.6/site-packages/s3fs/core.py", line 1518, in __del__
    self.close()
  File "/home/xxx/.local/share/virtualenvs/xxx/lib/python3.6/site-packages/s3fs/core.py", line 1496, in close
    raise_from(IOError('Write failed: %s' % self.path), e)
  File "<string>", line 3, in raise_from
OSError: Write failed: bucket/key
```
This is the exact same error as when I don't specify the variable `AWS_S3_HOST` at all.

I managed to get a working solution by directly interacting directly with `s3fs`:
```python
import os
import pandas as pd
import s3fs

fs = s3fs.S3FileSystem(client_kwargs={'endpoint_url': os.environ["AWS_S3_HOST"]})
df = pd.DataFrame(dict(a=[1, 2, 3], b=[4, 5, 6]))
df.to_csv(fs.open('s3://bucket/key', mode='w'))
```

Looks like this feature got (accidentally?) removed in `https://github.com/pandas-dev/pandas/commit/dc4b0708f36b971f71890bfdf830d9a5dc019c7b#diff-a37b395bed03f0404dec864a4529c97dL94`, when they switched from `boto` to `s3fs`.
Is it planned to support this environment variable again?
I'm sure that many companies, e.g. like the one I work for, hosts their own s3 server, e.g. with Minio, and don't use Amazon.

**Comment by WillAyd** [comment]
This is pretty similar to #16662 - I don't think this is something we'd generally offer support for so using the file system directly as you have in your solution is probably the way to go.

@TomAugspurger in case he has differing thoughts

**Comment by xieqihui** [comment]
+ Support for this feature. It would be good to support customised S3 endpoint as it is widely used.

**Comment by MarcoGorelli** [comment]
Closing because, as I gather from the discussion in #29050, this would be out-of-scope for pandas (please ping me if I've misunderstood and I'll reopen)

**Comment by TomAugspurger** [comment]
You can do this now with storage_options. See how we do it in our tests: https://github.com/pandas-dev/pandas/blob/132e19173265ad95e6b92dc46aa2b045c1073b81/pandas/tests/io/conftest.py#L36-L67

If anyone wants to turn that into a doc example we'd welcomed it.

**Comment by kvn4** [comment]
take

**Comment by kvn4** [comment]
Hi @TomAugspurger I just wanted to clarify a few things as I am taking the issue. I was thinking of updating this in [this pandas user_guide section](https://pandas.pydata.org/docs/user_guide/io.html?highlight=storage_options#reading-writing-remote-files) does this look like the right place to you? Also, is the fix that we are setting the endpoint url in the s3so function or that we are explicitly defining the environment variables (endpoint_port and endpoint_uri) in the s3_base function? In addition, it is not quite clear to me why the worker_id code is duplicated.

**Comment by TomAugspurger** [comment]
I think that's the right spot to document this.

If I understand things, this is documented in s3fs at https://s3fs.readthedocs.io/en/latest/index.html?highlight=host#s3-compatible-storage. So we're likely just summarizing that section and linking to it.
