### ISSUE TITLE
dropping non-existing entries - handling improvement

### ISSUE THREAD

**Issue by lobpcg** [pandas-dev/pandas#26191]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame({'a': [1, 2]})
df.drop(4)
```
#### Problem description
Dropping non-existing entries results in error, like
```KeyError: '[4] not found in axis'```

#### Expected Output
An empty output or no action if inplace. Possibly a warning, but surely not an error. 

What is wrong with trying to drop the entries that are already not present? Ghost-busting should be legal. 

#### Output of ``pd.show_versions()``

<details>
pandas: 0.24.2
</details>

**Comment by WillAyd** [comment]
You can use the errors argument to get the behavior you want. This is documented in the API entry page for drop

**Comment by lobpcg** [comment]
Sorry to waste your time... Indeed:
```
df.drop(4, errors='ignore')
```
does the trick.
