### ISSUE TITLE
wrong data after calling func pd.to_numeric

### ISSUE THREAD

**Issue by tianruoliang** [pandas-dev/pandas#26192]
`Python3.7.2` | `Pandas == 0.24.1`

```shell
pd.show_versions()
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.2.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 62 Stepping 4, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.24.1
pytest: None
pip: 19.0.3
setuptools: 40.6.2
Cython: None
numpy: 1.16.2
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: 2.6.1
xlrd: 1.2.0
xlwt: None
xlsxwriter: 1.1.5
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
```

### code:
```python
    df = pd.read_csv(...)
    selected_df = df.select_dtypes(include=["float"])
    df.loc[:, selected_df.columns] = selected_df.apply(
        pd.to_numeric, downcast="float"
    )
```
### df before:

|...|x|...|
|-|-|-|
|...|354000000000000.00000|...|
|...|354000000000000.00000|...|
|...|...|...|

### df after:

|...|x|...|
|-|-|-|
|...|353999995797504.00000|...|
|...|353999995797504.00000|...|
|...|...|...|

### debug:
...\venv\Lib\site-packages\pandas\core\tools\numeric.py
line 171
```python
    if is_series:
        a = pd.Series(values, index=arg.index, name=arg.name)  # added for debug
        return pd.Series(values, index=arg.index, name=arg.name)
```

### I can't understand.
variable values is correct,  variable a is wrong, but a._values is correct

**Comment by WillAyd** [comment]
Please provide pd.show_versions()

**Comment by Liam3851** [comment]
This is expected behavior. The given code specifies ```downcast='float'```. Per doc, downcast='float' gives "smallest float dtype (min.: np.float32)". x after is the same as x before within a factor of 10^-8:

```python
In [4]: (354000000000000.00000 - 353999995797504.00000) / 354000000000000.00000
Out[4]: 1.1871457627118644e-08
```

This is within the error range of np.float32 which only has accuracy to 6 sig figs. And in fact, both float32 values are equal:

```python
In [7]: np.float32(354000000000000.00000)
Out[7]: 354000000000000.0

In [8]: np.float32(353999995797504.00000)
Out[8]: 354000000000000.0

In [9]: np.float32(353999995797504.00000) == np.float32(354000000000000.00000)
Out[9]: True
```

Since the original code is explicitly trying to downcast 64-bit floats to 32-bit floats (it's selecting float columns and calling pd.to_numeric with downcast) I'm not sure what else could be expected.

**Comment by tianruoliang** [comment]
> Please provide pd.show_versions()

I added to the original submission.

**Comment by tianruoliang** [comment]
> Please provide pd.show_versions()

I added to the original submission : ) @WillAyd

**Comment by tianruoliang** [comment]
Hi @Liam3851,
Thank you for your reply.

Does this mean that for numbers that are large enough, I can only use np.float64?

**Comment by Liam3851** [comment]
@tianruoliang 354000000000000 > 2 **32. So if you need accuracy to within one integer, there is literally no way it can be encoded accurately in a 32-bit number. You can use a 64-bit float or 64-bit int if the numbers are integers

As I noted above, as 32-bit floats, those values are _literally the same_. The string representation used by a given package is irrelevant.

**Comment by WillAyd** [comment]
Thanks @Liam3851
