### ISSUE TITLE
Improve ujson test coverage or clean up dead code

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#26212]
I've been spending some time cleaning up the integration with ujson in our source code. After enabling some debugging directives and running the test suite I noticed that there were quite a few places in objToJSON.c which were not being hit. This can point to either dead code or a lack of test coverage, so these can be whittled down.

In my own repo I have a branch of this where each of the items are commented with `// not hit in tests` which you can see here:

https://github.com/WillAyd/pandas/blob/dead-json/pandas/_libs/src/ujson/python/objToJSON.c

Planning to go through these individually and see what we can do. Extra set of eyes would certainly be welcome

**Comment by WillAyd** [comment]
@jbrockmendel you might be interested

**Comment by TomAugspurger** [comment]
I’m hopeful that we can eventually remove all of this and use arrow and it’s JSON support. Given that, it may not be worthwhile spending too much time here.

**Comment by jbrockmendel** [comment]
@TomAugspurger any idea what "eventually" means in this context?  i.e. are we talking months or years?

**Comment by TomAugspurger** [comment]
https://issues.apache.org/jira/browse/ARROW-694 was the initial blocker, and that just landed in arrow 0.13.0. So, with a good amount of effort, months seems reasonable.

**Comment by jbrockmendel** [comment]
> Extra set of eyes would certainly be welcome

Yah, there's definitely some remove-able stuff in there.
- [ ] L65-67 is a check for py<2.5
- [ ] L163-167 is a PY3 check
- [ ] is the NPY_API_VERSION < 0.7 check on L729 removable?
- [ ] i have no idea what the semantics are for L737-753
- [ ] L648 when would obj.size be negative?
- [ ] is the PyLong_Check on 1785 redundant with the check on L1771?

**Comment by WillAyd** [comment]
Yep thanks @jbrockmendel . FYI some of the compat stuff I already ripped out in #26211

**Comment by WillAyd** [comment]
This has been / is being tackled elsewhere
