### ISSUE TITLE
ValueError: fill value must be in categories--I dont know why aren't versions compatible.

### ISSUE THREAD

**Issue by sunrisehang** [pandas-dev/pandas#26235]
The project I used is this website:https://github.com/ShichenXie/scorecardpy

You  can install it by 'pip intall scorecardpy'.

This is my code:

```
# Traditional Credit Scoring Using Logistic Regression
import scorecardpy as sc

# data prepare ------
# load germancredit data
dat = sc.germancredit()

# filter variable via missing rate, iv, identical value rate
dt_s = sc.var_filter(dat, y="creditability")

# breaking dt into train and test
train, test = sc.split_df(dt_s, 'creditability').values()

# woe binning ------
bins = sc.woebin(dt_s, y="creditability")
# sc.woebin_plot(bins)

# binning adjustment
# # adjust breaks interactively
# breaks_adj = sc.woebin_adj(dt_s, "creditability", bins) 
# # or specify breaks manually
breaks_adj = {
    'age.in.years': [26, 35, 40],
    'other.debtors.or.guarantors': ["none", "co-applicant%,%guarantor"]
}
bins_adj = sc.woebin(dt_s, y="creditability", breaks_list=breaks_adj)

# converting train and test into woe values
train_woe = sc.woebin_ply(train, bins_adj)
test_woe = sc.woebin_ply(test, bins_adj)
```
When I use 0.23 pandas, it works.
but I use 0.24.2 pandas, it reports this error:

The error:
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "E:\anancode\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "E:\anancode\lib\multiprocessing\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "E:\anancode\lib\site-packages\scorecardpy\woebin.py", line 953, in woepoints_ply1
    dtx = dtx.fillna('missing').assign(rowid = dtx.index).sort_values('rowid')
  File "E:\anancode\lib\site-packages\pandas\core\frame.py", line 4034, in fillna
    downcast=downcast, **kwargs)
  File "E:\anancode\lib\site-packages\pandas\core\generic.py", line 6123, in fillna
    downcast=downcast)
  File "E:\anancode\lib\site-packages\pandas\core\internals\managers.py", line 525, in fillna
    return self.apply('fillna', **kwargs)
  File "E:\anancode\lib\site-packages\pandas\core\internals\managers.py", line 395, in apply
    applied = getattr(b, f)(**kwargs)
  File "E:\anancode\lib\site-packages\pandas\core\internals\blocks.py", line 1834, in fillna
    values = values.fillna(value=value, limit=limit)
  File "E:\anancode\lib\site-packages\pandas\util\_decorators.py", line 188, in wrapper
    return func(*args, **kwargs)
  File "E:\anancode\lib\site-packages\pandas\core\arrays\categorical.py", line 1784, in fillna
    raise ValueError("fill value must be in categories")
ValueError: fill value must be in categories
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-12-6d5e8b7b4a92> in <module>
      1 # converting train and test into woe values
----> 2 train_woe = sc.woebin_ply(train, bins_adj)
      3 test_woe = sc.woebin_ply(test, bins_adj)

E:\anancode\lib\site-packages\scorecardpy\woebin.py in woebin_ply(dt, bins, no_cores, print_step)
   1062         )
   1063         # bins in dictionary
-> 1064         dat_suffix = pool.starmap(woepoints_ply1, args)
   1065         dat = pd.concat([dat]+dat_suffix, axis=1)
   1066         pool.close()

E:\anancode\lib\multiprocessing\pool.py in starmap(self, func, iterable, chunksize)
    296         `func` and (a, b) becomes func(a, b).
    297         '''
--> 298         return self._map_async(func, iterable, starmapstar, chunksize).get()
    299 
    300     def starmap_async(self, func, iterable, chunksize=None, callback=None,

E:\anancode\lib\multiprocessing\pool.py in get(self, timeout)
    681             return self._value
    682         else:
--> 683             raise self._value
    684 
    685     def _set(self, i, obj):

ValueError: fill value must be in categories
---------------------------------------------------------------------------

I dont know why aren't versions compatible.

**Comment by WillAyd** [comment]
Can't speak to what the third party library is doing but from the traceback it appears it is trying to fill categorical data with a category that doesn't exist, which would be an error as expected. The third party library would have to be updated to handle that
