### ISSUE TITLE
Is the IEX Data Reader going to lose stock symbols this june 2019 

### ISSUE THREAD

**Issue by kabonker** [pandas-dev/pandas#26246]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
stock_df = web.DataReader(stock,'iex', start_time, now_time)
```
#### Problem description

I visited the IEX website?  https://iextrading.com/developer/
It has a notice on the website: 

IEX API will sunset non-Investors Exchange (IEX) data on June 1, 2019. See Version 1.0 Docs.
On June 1, 2019, IEX API will sunset all non-IEX data. IEX Cloud, a non-Exchange platform, will continue to provide access to third-party data sources.

Does this mean the Pandas DataReader service for IEX will have limited stock tickers?  Is this api the source of the data for this Data Frame?

https://iextrading.com/trading/eligible-symbols/

I use this list to get the tickers...

<details>

[paste the output of ``pd.show_versions()`` here below this line]
NSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.4
pytest: 4.0.2
pip: 19.1
setuptools: 41.0.1
Cython: 0.29.2
numpy: 1.16.2
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.8.2
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.2
openpyxl: 2.5.12
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.2
lxml: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.7.0

</details>

**Comment by jreback** [comment]
see the pandas-datareader project
