### ISSUE TITLE
Add midrules to multicolumns in to_latex() output

### ISSUE THREAD

**Issue by flutefreak7** [pandas-dev/pandas#26245]
I propose adding midrules under headers for multicolumn headers.

See https://tex.stackexchange.com/a/180372 for examples of the latex feature.

Below is a code snippet for how I alter pandas.to_latex() output to include midrules for headers with 2 levels:

```python
        latex = latex.replace(r'{l}', r'{c}')

        offset = int(index)
        midrule_str = ''
        for i, col in enumerate(df_table.columns.levels[0]):
            indices = np.nonzero(np.array(df_table.columns.codes[0]) == i)[0]
            hstart = 1 + offset + indices[0]
            hend = 1 + offset + indices[-1]
            midrule_str += rf'\cmidrule(lr){{{hstart}-{hend}}} '

        # Ensure that headers don't get colored by row highlighting
        midrule_str += r'\rowcolor{white}'

        latex_lines = latex.splitlines()
        latex_lines.insert(3, midrule_str)
        latex = '\n'.join(latex_lines)
```

I also have a gist with my complete function of pandas/latex improvements to see the snippet in context of a working function:
https://gist.github.com/flutefreak7/50ffd291eaa348ead35c9794587006df

**Comment by WillAyd** [comment]
If you have an easy solution and want to make a PR would certainly consider!

**Comment by WillAyd** [comment]
@toobaz

**Comment by attack68** [comment]
`DataFrame.to_latex` has been migrated to the `Styler.to_latex` implementation which handles `midrules` differently. Perhaps this now has a solution, or the issue may need to be modified. In any, closing as not planned for now. Anyone is welcome to reopen with further info.
