### ISSUE TITLE
Pandas 0.24.2 upgrade ERROR

### ISSUE THREAD

**Issue by SigmaBid** [pandas-dev/pandas#26256]
python --version -       Python 3.4.9
pip3 install pandas==0.24.2
ERROR: No matching distribution found for pandas==0.24.2

Hi, We are trying to upgrade Pandas to 0.24.2 using pip 19.1 but it says matching distribution not found. Any ideas? Thanks!

**Comment by WillAyd** [comment]
3.4 support was dropped back in v0.21
