### ISSUE TITLE
DataFrame.sample()

### ISSUE THREAD

**Issue by omonfared** [pandas-dev/pandas#26265]
DataFrame.sample(n=None, frac=None, replace=False, weights=None, random_state=None, axis=None)[source]

It seems like the function of 'replace' is the other way around than what is explained in the documentation.

The documentation reads
"replace : bool, default False
Sample with or without replacement."

Whereas in reality it should be 
"replace : bool, default False
Sample without or with replacement."

False --> without replacement
True--> with replacement

**Comment by gfyoung** [comment]
@omonfared : Thanks for opening this!

It's actually fine as is.  Standard is to write the true result and then the false result when there's an or statement regarding a boolean variable like this.
