### ISSUE TITLE
Segfault in `pandas.DataFrame.from_records`

### ISSUE THREAD

**Issue by jcrist** [pandas-dev/pandas#26262]
The following causes `pandas.DataFrame.from_records` to segfault:

```python
pd.DataFrame.from_records(
    ([(1, 2, 3), (4, 5, 6)],),
    columns=['a', 'b', 'c']
)
```

The above is invalid and should error (a trailing comma led a list to accidentally be a 1-tuple containing a list, which is how I came upon this).

<details><summary>Version Information</summary>

```python
In [2]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Darwin
OS-release: 17.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: None
pip: 19.1
setuptools: 41.0.1
Cython: None
numpy: 1.16.3
scipy: None
pyarrow: None
xarray: None
IPython: 7.5.0
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: 1.2.0
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
```

</details>

**Comment by WillAyd** [comment]
Can you try on master? I wasn't able to reproduce

**Comment by jcrist** [comment]
Yeah, things work on master, but segfault on 0.24.2. I checked a few different builds of pandas 0.24.2 (conda defaults, conda-forge, and pypi) as well as a few numpy builds just to be sure it wasn't environment specific. I'm sufficiently convinced this is fixed on master, closing.
