### ISSUE TITLE
Dataframe.to_csv treats decimal.Decimal as string instead of numeric type and the 'decimal' sign parameter has no effect

### ISSUE THREAD

**Issue by 3f0c4** [pandas-dev/pandas#26276]
#### Code Sample

(float output is prepared for the sake of comparison to Decimal)

```python
# ----------------------------------
### imports

import pandas as pd
import decimal as dc

# ----------------------------------
### definitions

value_str = '2.445'

# ----------------------------------
### instantiations

#df_float = pd.DataFrame(data=[float(value_str)])
df_decimal = pd.DataFrame(data=[dc.Decimal(value_str)])

# ----------------------------------
### exports

# csv
#df_float.to_csv('float' + '.csv', sep=';', decimal=',')
df_decimal.to_csv('decimal' + '.csv', sep=';', decimal=',')

```
#### Observed Output
;0
0;2.445

#### Expected Output
;0
0;2,445

#### Problem description

Since Decimal represents a numeric type, one would expect that it gets treated as such and 'decimal' character replacement is applied, just like with floats.

Float values are converted to string followed by replacement of the default decimal sign '.' by the 'decimal' function parameter value ','.

Decimals are just treated as text, the replacement does not take place.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Windows
OS-release: 2012ServerR2
machine: AMD64
processor: Intel64 Family 6 Model 79 Stepping 0, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.2
pytest: None
pip: 10.0.1
setuptools: 39.1.0
Cython: None
numpy: 1.16.2
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.2
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: 2.6.2
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
None

</details>

**Comment by jschendel** [comment]
This is not natively supported by `pandas`, as`Decimal` objects do no fit into the `numpy` dtype system.  As such, `Decimal` objects do not represent a numeric dtype in `pandas`/`numpy`, but rather an `object` dtype.  For example, see the dtypes of `df_decimal`:
```python
In [3]: df_decimal.dtypes
Out[3]: 
0    object
dtype: object
```
This would take a ton of special casing for us to support, which is a maintenance burden we probably do not want to take on.  Unless you have a very specific usecase for using `Decimal` objects, you're probably best off using the default `float64` dtype.

If you really need to use `Decimal` objects and want this behavior, the easiest workaround is probably to do some quick preprocessing to convert to commas as appropriate before using `to_csv`.  Something like:
```python
In [6]: df_decimal[0] = df_decimal[0].map(lambda x: str(x).replace('.', ','))

In [7]: df_decimal
Out[7]: 
       0
0  2,445
```
It should be noted that native support for `Decimal` objects could likely be achieved via the `pandas` extension array protocol.  We actually have a basic version of a `DecimalArray` [in our test suite](https://github.com/pandas-dev/pandas/blob/8ac31233f376291c231a286b69851526552348ed/pandas/tests/extension/decimal/array.py).  This implementation does not work with the `decimal` parameter of `to_csv`, and I don't know off the top of my head how support for this would be added.

**Comment by 3f0c4** [comment]
@jschendel 
Thank you for the suggested workaround.

I use DECIMAL for financial calculations and precise number representation as well as for proper commercial rounding (half away from zero). I found it hard to achieve this with floats and chose to use DECIMALs instead of floats.

If DECIMALs are the way to go in this field of financial applications I would love to see pandas support for DECIMALs growing some day in the future.
