### ISSUE TITLE
Naming a Coulumn "name" leads to unexpected behaviour

### ISSUE THREAD

**Issue by marhofmann** [pandas-dev/pandas#26274]
The "name" column returns the index of the series

```
import pandas as pd
animals = ["name", "animal", "date_of_birth"]
frame = pd.DataFrame(columns=animals)

frame.loc[len(frame)] = ["Rita"]+["Elephant"]+["02.03.2008"]
frame.loc[len(frame)] = ["Alfred"]+["Mouse"]+["03.02.2018"]
for index, row in frame.iterrows():
    print("Animal: " + str(row.animal))
    print("Date of birth: " + str(row.date_of_birth))
    print("Name: " + str(row.name))

```

**Comment by jreback** [comment]
show the pandas version
try on master this is fixed

**Comment by marhofmann** [comment]
I have Version 0.24.2

**Comment by WillAyd** [comment]
Thanks for the report. So this isn't unexpected as much as it is ambiguous - `.name` accessor conflicts with `Series.name` property.  These types of issues are outlined in the Warnings in the Attribute Access section of the docs:

http://pandas-docs.github.io/pandas-docs-travis/user_guide/indexing.html#attribute-access

To avoid ambiguity here you'd have to use standard indexing:

```python
for index, row in frame.iterrows():
    print("Animal: " + str(row['animal']))
    print("Date of birth: " + str(row['date_of_birth']))
    print("Name: " + str(row['name']))
```

Which would generally be preferred anyway
