### ISSUE TITLE
Links on resample documentation page are broken

### ISSUE THREAD

**Issue by larsrinn** [pandas-dev/pandas#26275]
I meant to open an issue about inconsistent behaviour of resampling for sub- and super-daily intervals. When I was almost done, I discovered it's already been reported/discussed #9586

Figuring all of this out myself wasted a couple of hours, that could have been saved by a clearer documentation on the `resample` page: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html

Some things to change here:
* The links under *Notes* are "broken" in a sense that the headers on the page they link to seem to be non-existing anymore. I guess the link labeled *this link* should go here: http://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#dateoffset-objects  I'm unsure to which header *user guide* should link to.
* The docstring for the `rule` parameter is confusing. It's type annotation says it's supposed to be a `str` but the description is *The offset string or object representing target conversion.* What kind of object can it be if not a string? And shouldn't this be in the type annotation then? Is it possible to link to some more information on this directly from the description of the parameter so it becomes immediately clear what the options are?

**Comment by WillAyd** [comment]
PRs to improve documentation are always welcome if you'd like to work on this!
