### ISSUE TITLE
Add Annotations to assert_*_equal functions

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#26302]
Follow up to https://github.com/pandas-dev/pandas/pull/25462#issuecomment-489862882 want to add annotations for parameters. 

Would ideally probably want to add NoReturn but that requires 3.5.4 at a minimum so may want to explore other options

**Comment by samuelsinayoko** [comment]
Am going to try and pick this one up. Am interested to help with mypy and I have worked on assert utils as part of https://github.com/pandas-dev/pandas/pull/25462#issuecomment-489862882.

**Comment by samuelsinayoko** [comment]
Have added types to all assert_*_equal functions in this PR https://github.com/pandas-dev/pandas/pull/29364

**Comment by avinashpancham** [comment]
made an overview of the functions in `_testing/asserters.py`. I will start with `assert_frame_equal`

- [ ] assert_almost_equal
- [ ] assert_dict_equal
- [ ] assert_index_equal
- [ ] assert_class_equal
- [ ] assert_attr_equal
- [ ] assert_categorical_equal
- [ ] assert_interval_array_equal
- [ ] assert_period_array_equal
- [ ] assert_datetime_array_equal
- [ ] assert_timedelta_array_equal
- [ ] assert_numpy_array_equal
- [ ] assert_extension_array_equal
- [ ] assert_series_equal
- [ ] assert_frame_equal
- [ ] assert_equal
- [ ] assert_sp_array_equal

**Comment by mroeschke** [comment]
I see a lot of these methods are typed now so closing
