### ISSUE TITLE
FutureWarning difficult to identify source

### ISSUE THREAD

**Issue by david-waterworth** [pandas-dev/pandas#26329]
This is a suggestion, not a bug. The following resulted in a `FutureWarning`

    df = df.assign(block=(df.index.to_series().diff() != pd.Timedelta(15,'m')).cumsum())

> FutureWarning: The default of the 'keep_tz' keyword will change to True in a future release. You can set 'keep_tz=True' to obtain the future behaviour and silence this warning.

It wasn't in any way obvious why since the warning doesn't mention the method name and there's no stack trace (and futures warnings are only printed once). I had to search the source (which was also difficult as the message was split to maintain a character limit per line).

It would be nice if future warnings were more explicit, i.e. name the class and method as well as the argument. 

(In this case it's the `to_series()` method, which ideally wouldn't be required but `DateTimeIndex` doesn't yet implement diff())

**Comment by TomAugspurger** [comment]
FYI, you can use the warnings module to elevate warnings to errors so that you get a traceback:

```pytb
In [14]: warnings.simplefilter('error', FutureWarning)

In [15]: pd.date_range(2000, periods=4, tz='utc').to_series()
---------------------------------------------------------------------------
FutureWarning                             Traceback (most recent call last)
<ipython-input-15-0d004c39654b> in <module>
----> 1 pd.date_range(2000, periods=4, tz='utc').to_series()

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/indexes/datetimes.py in to_series(self, keep_tz, index, name)
    725                           "to True in a future release. You can set "
    726                           "'keep_tz=True' to obtain the future behaviour and "
--> 727                           "silence this warning.", FutureWarning, stacklevel=2)
    728             keep_tz = False
    729         elif keep_tz is False:

FutureWarning: The default of the 'keep_tz' keyword will change to True in a future release. You can set 'keep_tz=True' to obtain the future behaviour and silence this warning.
```.

Changing the message to note something like

    The default of the 'keep_tz' keyword in DatetimeIndex.to_series ...

seems OK. Are you likely to work on this?
