### ISSUE TITLE
BUG: ngroups and len(groups) do not equal when grouping with a list of Grouper and column label

### ISSUE THREAD

**Issue by lixuwen1991** [pandas-dev/pandas#26326]
#### Code

```python
m_index = pd.MultiIndex.from_product([['Mona', 'Dennis'], ['good', 'great']], names=['name', 'desc']) 
df = pd.DataFrame({'foo': [1, 2, 1, 2], 'bar': np.random.randn(4)},  index=m_index)
n1 = df.groupby([pd.Grouper(level='name'), 'foo']).ngroups
n2 = len(df.groupby([pd.Grouper(level='name'), 'foo'])) 
n3 = len(df.groupby([pd.Grouper(level='name'), 'foo']).groups) 
print(n1, n2, n3)
# 4 2 2

```
#### Problem description

I grouped a DataFrame by a list of pandas.Grouper object and column label, the length of groups or group keys should be 4, but I checked the length of GroupBy object as n2, it is 2, why? Thanks for your answer in advance.

<details>

ommit: None
python: 3.7.3.final.0
python-bits: 64
OS: Darwin
OS-release: 18.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: zh_CN.UTF-8
LOCALE: zh_CN.UTF-8

</details>

**Comment by shantanu-gontia** [comment]
`len(groubByObject)` returns the number of groups in that object.

**Comment by shantanu-gontia** [comment]
`len(<groupByObject>)` returns the number of groups as does calling the length on the `groups` property as in `n3`

`ngroups` on the other hand 

```
 def ngroups(self):
        return len(self.result_index)
```

returns the `result_index` which is a `MultiIndex` object. For the above example, the `result_index` output is the following `MultiIndex`

```
MultiIndex(levels=[['Dennis', 'Mona'], [1, 2]],
           codes=[[0, 0, 1, 1], [0, 1, 0, 1]],
           names=['name', 'foo'])
```

As of **pandas 0.24.2**, the `MultiIndex` `__len__` method is implemented as

```
def __len__(self):
        return len(self.codes[0])
```

so it returns the length of the first set of codes in the `MultiIndex`. Hence, `ngroups` outputs 4.'

---------

The groups that are formed in the example's `groupby` operation are

```
{('Dennis', 1): MultiIndex(levels=[['Dennis', 'Mona'], ['good', 'great']],
            codes=[[1], [0]],
            names=['name', 'desc']),
 ('Mona', 2): MultiIndex(levels=[['Dennis', 'Mona'], ['good', 'great']],
            codes=[[1], [1]],
            names=['name', 'desc'])}
```

Then `__len__` property in the groupby object calls the `__len__` property on its `groups`. which simply returns the number of elements in the above dictionary which is 2.

--------

Not sure if this is appropriate behaviour though.

**Comment by WillAyd** [comment]
This is pretty tricky. I'm surprised to see a difference between the below as well:

```python
>>> df.groupby([pd.Grouper(level=0), 'foo']).grouper.groups.keys()
dict_keys([('Dennis', 1), ('Mona', 2)])

>>> df.reset_index(level=1).groupby(['name', 'foo']).grouper.groups.keys()
dict_keys([('Dennis', 1), ('Dennis', 2), ('Mona', 1), ('Mona', 2)])

>>> df.groupby([pd.Grouper(['Mona', 'Mona', 'Dennis', 'Dennis']), 'foo']).grouper.groups.keys()
dict_keys([('Dennis', 1), ('Dennis', 2), ('Mona', 1), ('Mona', 2)])
```

I think the problem starts here:

https://github.com/pandas-dev/pandas/blob/ee6b1318ff07806ead79dac8119ad9ce580afe1c/pandas/core/groupby/ops.py#L261

Where the groups are getting constructed from the individual groupings (here the first grouping is the `pd.Grouper(level='name')` and the second grouping is the Series containing the values for `foo`).

The problem is that with the former iteration only goes over the unique values (here 'Dennis' and 'Mona') which is why your length calculations are getting truncated to 2:

https://github.com/pandas-dev/pandas/blob/ee6b1318ff07806ead79dac8119ad9ce580afe1c/pandas/core/groupby/grouper.py#L348

Not sure the best resolution off the top of my head but if you'd like to investigate further and try your hand at a PR would certainly be welcome!

**Comment by shantanu-gontia** [comment]
I'll investigate this further. Another possible source of error might be possible in the construction of the `Grouping` at
```
 ping = (Grouping(group_axis,
                         gpr,
                         obj=obj,
                         name=name,
                         level=level,
                         sort=sort,
                         observed=observed,
                         in_axis=in_axis)
if not isinstance(gpr, Grouping) else gpr)
```

**Comment by shantanu-gontia** [comment]
Adding to the above discussion,

>>> dfGroupby.grouper.groupings[0].grouper.groupings[0].grouper
Index(['Mona', 'Mona', 'Dennis', 'Dennis'], dtype='object', name='name')

**Comment by lixuwen1991** [comment]
Thanks for the bug confirmation, will use combination of labels to groupby instead.
As a beginner of pandas and even Python, I am trying to understand the codes and logic you mentioned above.😂
