### ISSUE TITLE
sum aggregation with columns of strings after groupby

### ISSUE THREAD

**Issue by jttoivon** [pandas-dev/pandas#26338]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd
df = pd.DataFrame([["c", "a", 1, 2], ["c", "b", 3, 4]])
df.groupby(0).sum()
```
#### Problem description

I expect the sum aggregation after groupby to work
similarly to normal aggregation: df.sum().
However, the columns containing strings don't
concatenate, but are ignored.

But, if I give the sum method any keyword parameter,
it works as expected.

For example, the following works:
df.groupby(0).sum(whatever=1)

#### Expected Output
```
    1  2  3
0          
c  ab  4  6
```

#### Output of ``pd.show_versions()``

<details>
I have tried the latest Pandas version 0.24.2, but the
same issue is with older Pandas releases.

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-48-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.24.2
pytest: 4.0.1
pip: 18.1
setuptools: 40.6.2
Cython: 0.29
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.8.2
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.1
openpyxl: 2.5.11
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.1.2
lxml.etree: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.14
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

[
</details>

**Comment by jschendel** [comment]
This is the expected behavior.  See the docs for additional information: https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#automatic-exclusion-of-nuisance-columns

**Comment by jttoivon** [comment]
Ok, dropping object columns may be expected behaviour, but
I think it is totally unexpected that given any keyword parameter,
the object columns are aggregated, for example with df.groupby(0).sum(whatever=1).

For example, I would expect that df.groupby(0).sum() would have the same behaviour
as df.groupby(0).sum(axis=0). But it is not. I did not see this explained in the documentation.
