### ISSUE TITLE
CI: Use bash for Windows scripts on Azure

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#26344]
Azure now supports using bash in windows scripts, so I _think_ we can de-duplicate some of the windows-specific shell scripts.  cc @datapythonista

**Comment by gfyoung** [comment]
Might even help with #26345

**Comment by TomAugspurger** [comment]
Don't think there was a reason. I just copied Numba's.

**Comment by datapythonista** [comment]
I think it wasn't possible to use bash in Windows until now, so using power shell scripts made sense. My question was if you saw any reason why not to unify now that it's possible, sorry I wasn't clear. I understand you don't.

@saurav2608 do you want to give this a try? It's related to #24632

**Comment by saurav2608** [comment]
I have very less time last few months to contribute here. But I will have a look at this and if I can quickly finish off, I will work on this.

**Comment by alimcmaster1** [comment]
Its great that azure now supports this - @jbrockmendel I assume you are referring to these power shell scripts implemented here: #26344 that currently live in: `ci/azure` directory i'm happy to take a look as migrating them
