### ISSUE TITLE
Can't compare time index to a time instance

### ISSUE THREAD

**Issue by zyxue** [pandas-dev/pandas#26351]
#### Code Sample, a copy-pastable example if possible

```python
Python 3.7.3 (default, May  8 2019, 05:28:42) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> import datetime
>>> df = pd.DataFrame([[datetime.time(1, 1, 0), 1]], columns=['time', 'num'])
>>> df.set_index('time', inplace=True)
>>> df.index > datetime.time(1, 1, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 84, in cmp_method
    result = op(self.values, np.asarray(other))
TypeError: '>' not supported between instances of 'int' and 'datetime.time'
>>> pd.__version__
'0.24.2'

```

The above code works on my local MacOS but doesn't inside a container `FROM python:3.7.3`. Same python version, same pandas version.

But locally, python is from the miniconda.

What could be the reason please?

**Comment by zyxue** [comment]
I found it's probably due to packages of  [mkl_fft](https://github.com/IntelPython/mkl_fft) and [mkl_random](https://github.com/IntelPython/mkl_random), which can't be installed with pip.

I uninstall them locally, and reproduced the above problem. :(

Still very interested in knowing why

**Comment by zyxue** [comment]
it may just be a problem on my end

**Comment by gfyoung** [comment]
cc @mroeschke 

I'm also using Miniconda, but that doesn't work either locally.  Can you share the result of `pandas.show_versions()` for both your Docker container and local?

**Comment by jreback** [comment]
``datetime.time`` are not first class citizens and are not supported except as an object-dtype ``Index``; comparisions don't generally for things this.
