### ISSUE TITLE
Fix type annotations for pandas.core.indexes.base

### ISSUE THREAD

**Issue by vaibhavhrt** [pandas-dev/pandas#26363]
Part of #25882 

Current errors are:

    pandas\core\indexes\base.py:9: error: Module 'pandas._libs' has no attribute 'join'

**Comment by vaibhavhrt** [comment]
The line with the error is:

    from pandas._libs import (
        algos as libalgos, index as libindex, join as libjoin, lib)

A `join.pyx` file does exists in the `_libs` directory but mypy is still giving error. The other imports `algos`, `index` and `lib` are also `.pyx` file but there is no error for them.
@WillAyd some help here please. Do we need a `.pyi` file?

**Comment by WillAyd** [comment]
You can just move the join as alias to a separate line - Mypy doesn’t seem to like that all being on one line and we’ve done that elsewhere

**Comment by vaibhavhrt** [comment]
@WillAyd you mean like this? :point_down: 

    from pandas._libs import (
        algos as libalgos, index as libindex, lib)
    from pandas._libs import join as libjoin

**Comment by vaibhavhrt** [comment]
No matter how I import it makes no difference. Still same error.

**Comment by WillAyd** [comment]
That’s right

**Comment by gwrome** [comment]
Try `import pandas._libs.join as libjoin`.

**Comment by vaibhavhrt** [comment]
@gwrome thanks, it works.
