### ISSUE TITLE
Pandas import breaks when setting filterwarnings

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#26367]
With released pandas (tested with 0.23.4), you get the following:

```
>>> import warnings
>>> warnings.filterwarnings('error')
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joris/miniconda3/lib/python3.7/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "/home/joris/miniconda3/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
  File "pandas/_libs/tslibs/conversion.pxd", line 11, in init pandas._libs.tslib
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/nattype.pyx", line 14, in init pandas._libs.tslibs.nattype
ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
```

(you also get a long output with `warnings.filterwarnings('always')`).

This is not happening any more on master, so the reason seems to be fixed. 
But I was wondering, do we want to guarantee that this does not happen? (to the extent possible of course, meaning that we try to test this)

**Comment by TomAugspurger** [comment]
This looks like https://github.com/cython/cython/issues/1720. It's possible that 0.23.4 was compiled with older Cython versions?

(you probably know this, but you can add another filter that ignores warnings with that message).

**Comment by jorisvandenbossche** [comment]
Ah, that's quite likely the reason. 
And that's also a good reason that we might not want to test it, as it is quite dependent on other packages to not generate warnings when pandas is imported (although testing it might catch such issues early).

> (you probably know this, but you can add another filter that ignores warnings with that message).

yep, but the issue came from ``buildbot`` doing this. And just importing something from buildbot made the pandas import break like that, which gives you something hard to debug. So the solution is for sure adding an ignore filterwarnings (which is what buildbot is already doing for a bunch of things they import themselves)

**Comment by alexantoinefortin** [comment]
This problem is also present in 0.24.2 and 0.24.1

**Comment by TomAugspurger** [comment]
Can you post the command you're running and the output you see?  How'd you
install pandas? I believe this will depend on the version of Cython used to
compile things.

**Comment by jbrockmendel** [comment]
This is not present in master.  I guess we could make a test for it with a specific error message asking users to let us know if it fails?

**Comment by avinashpancham** [comment]
take

**Comment by TomAugspurger** [comment]
This is tested at https://github.com/pandas-dev/pandas/blob/37662ea387e17a4aca1f83445daeea977e145a9b/ci/code_checks.sh#L252.
