### ISSUE TITLE
Feature requests: pandas.DataFrame.quantile with exclusive/inclusive of median

### ISSUE THREAD

**Issue by chitown88** [pandas-dev/pandas#26370]
There seems to always be the debate when calculating the 1st and 3rd quartiles in statistics about whether the median is included or not included in calculating the q1, q3. Some calculations include the median, while other exclude it. Regardless of the "correct" way to calculate this out, it would be nice if pandas could accommodate both scenarios, with a parameter of some sort, maybe `include_median = False` to get the results.

For example:

Looking at this series of values:

```
s = pd.Series([.0022, .0032, .0043, .0043, .0059])
s.quantile([0.25,0.5,0.75])
```

yields a result of:

```
Out[41]: 
0.25    0.0032
0.50    0.0043
0.75    0.0043
dtype: float64
```

Which is the median of the lower and upper halves (including the median value)
When I am looking for the results of, something along the lines of:

`s.quantile([0.25,0.5,0.75], include_median = False)`

```
0.25    0.0027
0.50    0.0043
0.75    0.0051
dtype: float64
```

which would be the medians of the lower and upper halves (excluding the median value from those sets)

**Comment by mroeschke** [comment]
> Some calculations include the median, while other exclude it

Can you provide an example of a quantile implementation that excludes it? It appears `statistics.median` and `numpy.median` includes it. We tend to mirror numpy analytical functions so I'd be hesitant to add this.

**Comment by chitown88** [comment]
Yes, you are correct both `statistics.median` and `numpy.median` includes the median in their calculations of Q1 and Q3. But that's my point. There are numerous papers and institutions that express the Q1 and Q3 as the median of the lower half, and upper half (with the lower and upper halves NOT inclusive of the median). I'm not debating which is the "correct" way, but there are 2 methods of deriving Q1 and Q3, and since both methods (choosing to include or exclude the median) is acceptable, I can not find a library that allows for that distinction of which method I would like to use (and I actually am needing it calculate the Q1 and Q3 with the non-inclusion of the median method).

But, here are a few references that express the Q1 and Q3 as the upper and lower halves not including the median. I can supply many more if needed, as well as references to mathematics professors if needed: 

http://www.stats.gla.ac.uk/steps/glossary/presenting_data.html#quart
from Valerie J. Easton and John H. McColl's Statistics Glossary v1.1 (as references in Yale's website http://www.stat.yale.edu/Courses/1997-98/101/boxplot.htm)

Minnesota State University
http://web.mnstate.edu/peil/MDEV102/U4/S36/S363.html

Boston University
http://sphweb.bumc.bu.edu/otlt/mph-modules/bs/bs704_summarizingdata/bs704_summarizingdata7.html

University of Nothern Iowa
http://www.cs.uni.edu/~campbell/stat/loc.html

**Comment by mroeschke** [comment]
Thanks for the suggestion, but it appears that this enhancement never got much traction from the community and I still believe pandas should align with numpy. Closing due to staleness but happy to reopen if there's further interest from the devs and the community
