### ISSUE TITLE
Converting json to csv

### ISSUE THREAD

**Issue by PasupulaHarish** [pandas-dev/pandas#26389]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
 dirs = os.listdir(path)
        frame = pandas.DataFrame()
        #frame = frame.astype(str)
        output_folder_time_stamp = str(datetime.datetime.now()).replace(":", " ").rsplit(".", 1)[0]
        final_output_path = outputpath + str(output_folder_time_stamp)
        try:

            for filename in dirs :
                subdirs=path + filename
                subdirs = os.listdir(subdirs)
                if len(subdirs)>0:
                    for jsonfilename in subdirs :
                        root, ext = os.path.splitext(jsonfilename)
                        if ext == '.json':
                            tmp_frame = pandas.read_json(path+filename+"/"+jsonfilename)
                            frame = frame.append(tmp_frame, ignore_index=True)

                    
                    if not os.path.exists(final_output_path):
                        os.makedirs(final_output_path)                                
                    
                    frame.to_csv(final_output_path +"/"+ filename +"_"+output_folder_time_stamp+'.csv',encoding='utf-8',index=False,header=True, columns=["FILE NAME","PROPERTY VALUE"])
                    
                    
                    frame = pandas.DataFrame()
                    tmp_frame=''
```
#### Problem description
In Json as 
[{"FILE NAME": "EXP_data.xml", "PROPERTY VALUE": "3-4"}]

PROPERTY VALUE": "3-4" converting as "4-Mar" in CSV

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Expected Output
PROPERTY VALUE": "3-4"
#### Output of ``pd.show_versions()``
PROPERTY VALUE": "4-Mar"
<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by TomAugspurger** [comment]
Can your bug report be simplified?

**Comment by PasupulaHarish** [comment]
json value "3-4" converting as "4-Mar" in CSV instead of "3-4"

**Comment by PasupulaHarish** [comment]
json value "3-4" converting as "4-Mar" in CSV instead of "3-4"

**Comment by TomAugspurger** [comment]
See http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by TomAugspurger** [comment]
@PasupulaHarish if you can provide a minimal example we'll reopen.
