### ISSUE TITLE
[BUG] groupby apply would get first group twice !

### ISSUE THREAD

**Issue by eromoe** [pandas-dev/pandas#26382]
#### Code Sample, a copy-pastable example if possible

```python
In [1]: import pandas as pd

In [2]: import numpy as np

In [3]: pd.DataFrame({'a': np.random.randint(0, 3, 10)}).groupby('a').apply(lambda x:print(x.name))
0
0
1
2
In [4]: pd.__version__
Out[4]: '0.24.2'

```
#### Problem description

Above code show the problem

#### Expected Output

```
In [3]: pd.DataFrame({'a': np.random.randint(0, 3, 10)}).groupby('a').apply(lambda x:print(x.name))
0
1
2
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 45 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.2
pytest: 4.4.1
pip: 19.0.3
setuptools: 41.0.0
Cython: 0.29.6
numpy: 1.16.2
scipy: 1.2.1
pyarrow: 0.12.0
xarray: None
IPython: 7.5.0
sphinx: 2.0.1
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.9
feather: None
matplotlib: 3.0.3
openpyxl: 2.6.1
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.6
lxml.etree: 4.3.3
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.3.2
pymysql: None
psycopg2: None
jinja2: 2.10.1
s3fs: 0.2.0
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by jreback** [comment]
this is already fixed in master

**Comment by eromoe** [comment]
This happened at least since 0.23.4 .
When will the fixed version be uploaded to pypi ?
