### ISSUE TITLE
Inconsistent datetime conversion within column with dd/mm format

### ISSUE THREAD

**Issue by matthew-brett** [pandas-dev/pandas#26387]
#### Code Sample, a copy-pastable example if possible

```python
>>> pd.to_datetime(['30/04/19', '01/05/19'])
DatetimeIndex(['2019-04-30', '2019-01-05'], dtype='datetime64[ns]', freq=None)
```
#### Problem description

The converter should infer the same format for both values - so it should infer that both values are in dd/mm/yy format, as must be so for the first value.  Otherwise `to_datetime` will give dangerous and unusable results for `dd/mm` format dates, because the months / days will reverse within a column. 

#### Expected Output

```
DatetimeIndex(['2019-04-30', '2019-05-01'], dtype='datetime64[ns]', freq=None)
```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Darwin
OS-release: 18.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.24.0
pytest: 4.1.1
pip: 19.0.3
setuptools: 40.8.0
Cython: None
numpy: 1.16.0
scipy: 1.2.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.8.4
patsy: None
dateutil: 2.7.5
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: 4.3.3
bs4: 4.7.1
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: Non
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by jreback** [comment]
see https://github.com/pandas-dev/pandas/issues/12585
