### ISSUE TITLE
Holiday based on the lunar calendar?

### ISSUE THREAD

**Issue by Sumeun** [pandas-dev/pandas#26393]
I happened to notice that pandas.tseries.offsets.CustomBusinessDay can not handle holidays based 
 on the lunar calendar.

I think it would be great if the class CustomBusinessDay support the lunar holidays in Korea, China, etc.

**Comment by alimcmaster1** [comment]
I think https://pypi.org/project/holidays/ would be a more appropriate project to implement this kind of logic.

Thanks!
