### ISSUE TITLE
Inconsistent Constructor Behavior 

### ISSUE THREAD

**Issue by nhartwic** [pandas-dev/pandas#26418]
#### Code Sample, a copy-pastable example if possible

```python
DF = pandas.DataFrame
S = pandas.Series
ll = [list(range(5)) for i in range(10)]
print(DF(ll).shape)
ld = [{j: j for j in range(5)} for i in range(10)]
print(DF(ld).shape)
dd = {i: {j: j for j in range(5)} for i in range(10)}
print(DF(dd).shape)
dl = {i: list(range(5)) for i in range(10)}
print(DF(dl).shape)
ls = [S(list(range(5))) for i in range(10)]
print(DF(ls).shape)
ds = {i: S(list(range(5))) for i in range(10)}
print(DF(ds).shape)
ss = S([S(list(range(5))) for i in range(10)])
print(DF(ss).shape)
sl = S([list(range(5)) for i in range(10)])
print(DF(sl).shape)
sd = S([{j: j for j in range(5)} for i in range(10)])
print(DF(sd).shape)
```
#### Problem description
There are kind of two separate issues here...

1. It seems strange to me that when a two dimensional object is passed to the DataFrame constructor, whether or not the object is interpreted as row by col or col by row is determined by whether or not the outer object is a dict or a list. If the outer object is a Dict, an MxN object will create an NxM dataframe. If the outer object is a list, an MxN object will create an MxN dataframe

2. It seems strange to me that the DataFrame constructor works well with lists of series and dicts of series but doesn't work with series of dicts, series of lists, or series of series.

#### Expected Output
Naively, I would expect the resultant DataFrame to be structured in the same way regardless of whether the object passed to the DataFrame constructor is a dict of lists, a dict of dicts, a list of lists, etc... All of the above calls to pandas.DataFrame should return equivalent dataframes IMO.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.2
pytest: None
pip: 19.0.3
setuptools: 41.0.0
Cython: None
numpy: 1.16.3
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.4.0
sphinx: None
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: 2.6.2
xlrd: 1.2.0
xlwt: None
xlsxwriter: 1.1.7
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by shantanu-gontia** [comment]
When passed a list of list, the constructor assumes a simple tabular format.

```python
In [1]: import pandas as pd

In [2]: ll = [['a', 'b', 'c', 'd'], [1, 2, 3, 4]]

In [3]: df_ll = pd.DataFrame(ll)

In [4]: df_ll
Out[4]:
   0  1  2  3
0  a  b  c  d
1  1  2  3  4
```

When you pass a list of dictionaries, each element of the list is treated as a row, just like when you pass a list of lists. However, the difference is when dictionaries are involved you have a `key`-`value` pair, where the key corresponds to the column name. Hence, the constructor puts the `value` in the column corresponding to the `key`. As far as it is concerned, you are explicitly trying to tell it where to put the value.


```python
In [5]: ld = [ {0: 'a', 1: 'b', 2: 'c', 3: 'd'}, {0: 1, 1: 2, 2: 3, 3: 4} ]

In [6]: df_ld = pd.DataFrame(ld)

In [8]: df_ld
Out[8]:
   0  1  2  3
0  a  b  c  d
1  1  2  3  4
```
Dictionaries unlike lists are unordered objects. So you cannot expect the same order every time you access the dictionaries keys or values (However, I think this is not so in python 3). But regardless to me, a `key-value` pair with the `key` corresponding to the column name seems a more natural choice. As later I can simply construct a dictionary without knowing the order of columns in the `DataFrame` to insert a new row.

Just like atomic objects, we can also pass lists inside of the dictionary values in order to add rows to a `DataFrame`, where the `key` again correspond to columns of the `DataFrame` and the `values` from each key make a up a row. This also seems more natural to me to construct a `DataFrame` when I know what the column names must be and their corresponding values. However, I guess here we can argue that, we can do the same thing by passing a list of lists and specifying the columns parameter.

**Comment by nhartwic** [comment]
> As far as it is concerned, you are explicitly trying to tell it where to put the value.

When we are making a dataframe, we are always explicitly stating where to put values. The only difference between lists and dictionaries in this regard is that lists specify locations positionaly and dictionaries specify locations by index. There is a second difference in the constructer in which an outer list is assumed to represent rows while an outer dictionary is assumed to represent columns for some reason.


All I'm pointing out here (beyond the fact that pandas dataframes don't handle series well by default) is that if I have a dict of lists or dict of dicts of size M x N, I end up with an N x M dataframe. Where as if if I have an M x N list of dicts or list of lists, I end up with an M x N dataframe. It seems obvious to me that if I pass an M x N object to pandas, I should end up with an M x N object, but pandas seems to disagree. In the grand scheme this isn't all that big a deal since transposing dataframes is so easy, but I just don't see the reason to have this behavior.

Do we really think its intuitive that the following two objects produce different dataframes when passed to the DataFrame constructor?
```
dl = {
    0: [0, 1, 2, 3, 4],
    1: [0, 1, 2, 3, 4],
    2: [0, 1, 2, 3, 4],
    3: [0, 1, 2, 3, 4],
    4: [0, 1, 2, 3, 4],
    5: [0, 1, 2, 3, 4],
    6: [0, 1, 2, 3, 4],
    7: [0, 1, 2, 3, 4],
    8: [0, 1, 2, 3, 4],
    9: [0, 1, 2, 3, 4]
}
ld = [
    {0: 0, 1: 1, 2: 2, 3: 3, 4: 4},
    {0: 0, 1: 1, 2: 2, 3: 3, 4: 4},
    {0: 0, 1: 1, 2: 2, 3: 3, 4: 4},
    {0: 0, 1: 1, 2: 2, 3: 3, 4: 4},
    {0: 0, 1: 1, 2: 2, 3: 3, 4: 4},
    {0: 0, 1: 1, 2: 2, 3: 3, 4: 4},
    {0: 0, 1: 1, 2: 2, 3: 3, 4: 4},
    {0: 0, 1: 1, 2: 2, 3: 3, 4: 4},
    {0: 0, 1: 1, 2: 2, 3: 3, 4: 4},
    {0: 0, 1: 1, 2: 2, 3: 3, 4: 4}
]
```

**Comment by TomAugspurger** [comment]
I think that for most of these we're not likely to change the behavior.

> DataFrame constructor works well with lists of series and dicts of series but doesn't work with series of dicts, series of lists, or series of series.

Can you clarify this? Series are 1-dimensional, so they should have the same behavior as a 1-d ndarray.

**Comment by nhartwic** [comment]
> Can you clarify this? Series are 1-dimensional, so they should have the same behavior as a 1-d ndarray.

Lists and dictionaries are one dimensional objects as well, and yet when you pass a list of lists to a dataframe, it is interpreted as a 2d object. Similarly, lists of Series and dicts of Series are interpretted as 2d objects. Series of list, Series of Dicts, and Series of Series are all interpretted as Nx1 dimensional objects.

I agree that a series is one dimensional, so why does the pandas constructor treat a series passed to it as if it were a two dimensional Nx1 object? Consider the difference between the following

```
d = dict(zip(range(5), range(5)))
s = pandas.Series(d)
# the following works but produces an 5x1 shaped dataframe even though there is no information
# in the series regarding the second dimension of the dataframe.
pandas.DataFrame(s)
# the following produces an error due to some combination of the input being 1 dimensional and
# pandas assuming that dicts represent column: value mappings
pandas.DataFrame(d)
```
The objects s and d above represent the same information and have the same dimensionality and are handled differently by pandas. Lists and series are treated more similarly by comparison but again, the behavior seems counter intuitive

```
l = list(range(5))
s = pandas.Series(l)
# this will make a 5x1 dataframe
pandas.DataFrame(l)
# this will also make a 5x1 dataframe
pandas.DataFrame(s)

# once we add a dimension to our data, behavior diverges
ll = [list(range(10)) for i in range(5)]
ss = pandas.Series([pandas.Series(list(range(10))) for i in range(5)])

# this will create a 5x10 dataframe
pandas.DataFrame(ll)

# This will STILL create a 5x1 dataframe
pandas.DataFrame(ss)
```

It seems to me that pandas isn't treating Series objects as one dimensional, it is treating them as two dimensional Nx1 objects which is just kind of weird to me. Maybe I'm the strange one in all this though and its all perfectly intuitive to everyone else.

**Comment by mroeschke** [comment]
Thanks for the request, but as mentioned I think these behaviors are probably not likely to change so closing
