### ISSUE TITLE
Deprecate py.path support

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#26450]
Since our min version is Py35 path lib is guaranteed to be installed. However we have a few functions that accept py.path.LocalPath objects for compatability

Not sure if we need an explicit deprecation cycle or if this is implied with moving minimum support to Py35

**Comment by jreback** [comment]
we should deprecate as have accepted these for a long time and they work py 3

**Comment by nandahkrishna** [comment]
If possible, I'd like to contribute to this. Should I search for functions with LocalPath and deprecate them accordingly?

**Comment by WillAyd** [comment]
@nandahkrishna that's great! And yes you've got it right. You might want to check out other PRs labeled Deprecate that have been merged to see how we typically handle as well

**Comment by nandahkrishna** [comment]
> You might want to check out other PRs labeled Deprecate that have been merged to see how we typically handle as well

Sure, I'll do that. Thanks!

**Comment by nandahkrishna** [comment]
I took a look at previous PRs labeled deprecate. I got a fair idea of how it works, but I couldn't seem to find a case that deprecated an external library (might have missed my eye?) so just confirming:
1. Visit functions where py.path.local has been used
2. Add a DeprecateWarning with a suitable message
3. Add tests for the warning
Is this right?

**Comment by WillAyd** [comment]
That's right!

**Comment by TomAugspurger** [comment]
Does py.path implement the __fspath__ protocol? If so, then no need to deprecate. We can just remove the py.path specific code.

**Comment by WillAyd** [comment]
> Does py.path implement the __fspath__ protocol? If so, then no need to deprecate. We can just remove the py.path specific code.

I think so from https://github.com/jaraco/path.py/issues/123. The problem however is we internally don't fully operate using the `__fspath__` protocol, especially since that didn't become standard until 3.6. The PR by @nandahkrishna shows an example where we special case for `py.path`.

So would your suggestion be to just defer any kind of deprecation and work towards full fspath support when we drop 3.5?

**Comment by TomAugspurger** [comment]
I’m not sure, but I think objects implementing fspath will work fine, even for python 3.5 and earlier. In theory, we can just remove the py.path-specific code and things will work.
