### ISSUE TITLE
Replace Union annotations with TypeVar

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#26453]
Had a revelation after https://github.com/python/mypy/issues/6847#issuecomment-493715355 and I think we've been using Union too liberally in places where a TypeVar may make more sense (especially in pandas._typing) so would be good to go back and swap those out.

@gwrome @vaibhavhrt

**Comment by vaibhavhrt** [comment]
@WillAyd we are almost done with removing all ignored modules from mypy.ini Once that's done I will take a look where we have used Union and see if we can use TypeVar instead.

**Comment by vaibhavhrt** [comment]
@WillAyd I will look for Unions in `pandas._typing` and after fixing that will for Unions in other files.
Just to be sure typeVar for `Union[str, float]` would be `Something = TypeVar('Something', str, float)`, right?
Also can please provide some explanation on when to use TypeVar and when to use Union.

**Comment by WillAyd** [comment]
TypeVar is going to be more suitable for parametrization and generic functions. In the case of containers I think the difference between:

```python
T = TypeVar('T', str, float)
List[T]
```

and
```python
List[Union[str, float]]
```

Would be that the former could only accept `[1, 2]` and `['a', 'b']` but not `[1, 'a']`. The latter would accept all of those.

Looking at functions:

```python
def foo(something: T) -> T:
    ...
```

Would basically mean that if `foo` accepts a string it also returns a string, and if it accepts a float it returns a float, but that it cannot accept a string and return a float. By contrast:

```python
def foo(Union[str, float]) -> Union[str, float]:
    ...
```

Would allow all of those combinations, so it could accept 'a' and return 1.

We've used Union throughout so far but more often than not I think parametrization of the Type is actually what we want.

**Comment by vaibhavhrt** [comment]
Nice, thanks for explaining, I will replace all unions in `pandas._typing` today.

**Comment by jreback** [comment]
does #26588 fully close this?

**Comment by WillAyd** [comment]
Yep
