### ISSUE TITLE
Non-expected NaN numbers behavior for  .dropna function in 0.24.2

### ISSUE THREAD

**Issue by Uiuran** [pandas-dev/pandas#26472]
Unfurtunately i cant provide the data iam using (since it's enterprise privative), but it has a lot of NaN values. 

I do:
df = df.dropna(axis=0,thresh=1)

Returns a DataFrame with nan values, i can confirm this looping through the DataFrame and applying np.isnan.

Then i do:
df = df.fillna(0)

The new DataFrame has no more NaN. Why is this that dropna cant see all NaNs and fillna can ?

Thankyou in advance.

```
#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Expected Output

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by TomAugspurger** [comment]
Presumably, the issue doesn't depend on the exact data. See http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by gustavolinari** [comment]
Probably because of the thresh parameter. Remove it and all NaN will be gone.

**Comment by Uiuran** [comment]
i will try it thank you in advance

**Comment by Uiuran** [comment]
Without thresh it does works. Strange behaviour that of this parameter though
