### ISSUE TITLE
mergebug

### ISSUE THREAD

**Issue by skysunsun** [pandas-dev/pandas#26478]
#### My code

```python
def mer_new():
    data1 = read_file.reduce_mem_usage(pd.read_csv('E:\\skysun\\JDA\\jdata\\jdata_action.csv', sep=',', nrows=6000000,
                                                   dtype={'acoustic_data': np.int16, 'time_to_failure': np.float64}))
    data1 = data1[['user_id', 'sku_id', 'action_time', 'type']]
    print('行为数据:%d' % len(data1))
    print('\n')
    data2 = read_file.reduce_mem_usage(pd.read_csv('E:\\skysun\\JDA\\jdata\\jdata_comment.csv', sep=',', nrows=6000000,
                                                   dtype={'acoustic_data': np.int16, 'time_to_failure': np.float64}))
    data2 = data2[['sku_id', 'good_comments', 'bad_comments']]
    print('评论数据:%d' % len(data2))
    print('\n')
    data = pd.merge(data1, data2, how='left', on='sku_id')
    print('合并数据：%d'%len(data))
    # data =pd.concat([data1,data2],axis=1,join='outer')
    data = data.drop_duplicates()
    data.to_csv('data/action_comment.csv', mode='w', index=False)
mer_new()
```
#### Problem description

when I merge two table,I set the 'how='left'', so the length of original data should be equal the length of merge data.(the second table's length is 1774233)

But it return

len(data1):6000000
len(data)：284428008
It does not equal!!!! Why???

**Comment by WillAyd** [comment]
> when I merge two table,I set the 'how='left'', so the length of original data should be equal the length of merge data.(the second table's length is 1774233)

That wouldn't be true if the merge key appears multiple times in the right data frame

**Comment by skysunsun** [comment]
> > 当我合并两个表时，我设置'how ='left''，因此原始数据的长度应该等于合并数据的长度。（第二个表的长度是1774233）
> 
> 如果合并键在右侧数据框中多次出现，则情况并非如此

Thank you very much!
