### ISSUE TITLE
df.groupby on a column with complex numbers is broken

### ISSUE THREAD

**Issue by basnijholt** [pandas-dev/pandas#26475]
Currently, grouping by a key that has complex numbers is broken, see the following example

```python
import pandas as pd
df = pd.DataFrame([dict(a=1, b=1 + 1j), dict(a=1, b=1 + 2j)])
df.groupby("b").groups
```
output:
```
{1.0: Int64Index([0, 1], dtype='int64')}
```

expected:
```
{0: Int64Index([0], dtype='int64'), 1: Int64Index([1], dtype='int64')}
```

Related https://github.com/pandas-dev/pandas/issues/10921

**Comment by jschendel** [comment]
Probably the same underlying issue as #17927

**Comment by rhshadrach** [comment]
I'm now seeing `{(1+1j): [0], (1+2j): [1]}` from the OP. Could likely use tests.

**Comment by xiaohuanlin** [comment]
Hi @rhshadrach, can I take this question? I think the expection for this question is to create a unittest to prevent it happen again, is it right?

**Comment by aram-cinnamon** [comment]
take

**Comment by aram-cinnamon** [comment]
Ah sorry @xiaohuanlin, I already picked up this issue on Sunday (You can refer to our slack channel). Next time I'll `take` early so there's no confusion.
