### ISSUE TITLE
Set single cell of Multindex DataFrame to array

### ISSUE THREAD

**Issue by giacomopareschi** [pandas-dev/pandas#26488]
I am creating a Multindex DataFrame but I don't know in advance how many rows I will have, since I reading from a pool of files. I basically want to append a new row every time. The best way I found is:

```python
idx = pd.MultiIndex(levels=[[],[]], codes=[[],[]], names=['level0', 'level1'])
df = pd.DataFrame(columns=['Categorical', 'Integer', 'Vector'], index=idx)
df.loc[('a',0),:] = ['apple', 1, 2.3]
df.loc[('a',1),:] = ['banana', 1, 3.4]
```
this works fine. But then I want to set ```df.loc[('a',1),'Vector]``` to an array, not a single value. By trying either
```python
df.loc[pd.IndexSlice['a', 1], 'Vector'] = [1,2]
```
or
```python
df.loc[('a',1), 'Vector'] = [1,2]
```
I get
```python
~\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\indexing.py in _setitem_with_indexer(self, indexer, value)
    491                         value) and lplane_indexer != len(value):
    492 
--> 493                     if len(obj[idx]) != len(value):
    494                         raise ValueError("cannot set using a multi-index "
    495                                          "selection indexer with a different "
TypeError: object of type 'float' has no len()
```
#### Expected Output
I would like the vector [1,2] to be set as a single element at [('a',1), 'Vector']
I don't want to expand the vector as a new level of the Multindex since it's usually thousands of element.
I have no work around that can accomplish that. I believe it's an issue because Pandas tries to align the vector along some levels of the Multindex, but it fails to do so. Pandas should understand that my vector cannot be aligned along the Mutlindex since I am setting it on a single row and a single column.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.5.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.2
pytest: 3.0.7
pip: 19.0.3
setuptools: 40.8.0
Cython: 0.25.2
numpy: 1.15.2
scipy: 1.1.0
pyarrow: 0.12.1
xarray: 0.10.7
IPython: 6.2.1
sphinx: 1.3.1
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.4
feather: None
matplotlib: 2.2.2
openpyxl: 2.4.7
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml.etree: 3.7.3
bs4: 4.6.0
html5lib: 0.999
sqlalchemy: 1.1.9
pymysql: None
psycopg2: 2.7.7 (dt dec pq3 ext lo64)
jinja2: 2.9.6
s3fs: None
fastparquet: 0.2.1
pandas_gbq: None
pandas_datareader: None
gcsfs: None

**Comment by topper-123** [comment]
You can archive the desired result by doing ``df.at[('a',1), 'Vector'] = [1, 2]``.

``.at`` is the scalar version of ``.loc``, so clearly communicates that this is an intended result. ``.loc`` is typically used for non-scalar operations, and using it to add a list (a non-scalar value) to a single (scalar) cell sounds confusing. You typically don't want to a higher dimension value into a lower-dimension cell(s).

So, I'm ok with the current behaviour, though the error message could be improved.

**Comment by giacomopareschi** [comment]
Thank you for the helpful answer.
I agree that the error message could be improved.

**Comment by topper-123** [comment]
Alright:-) And if you want to contribute a better error message, you'd be welcome.
