### ISSUE TITLE
Remove StringMixin from code base

### ISSUE THREAD

**Issue by topper-123** [pandas-dev/pandas#26495]
I`m thinking about making a PR to remove ``StringMixin`` from the code base in order to make pandas use more standard string output methodology (putting the base string representations in __repr__ , as is standard in python3, instead of in  __str__).

Any objections to this? This is backwards compatible for users of Pandas, but may be slightly backwards incompatible for subclasses of Pandas classes located in external packages, e.g. If a downstream package did this:

```python
>>> class MyFrame(pd.DataFrame):
...    def __str__(self):
...        return “abc”
```

the repr would output an unexpected string.

Would this e.g.  affect Geopandas, @jorisvandenbossche?

**Comment by jorisvandenbossche** [comment]
GeoPandas does not modify the repr, so it would not be affected. 

I don't really use or know of other packages that subclass pandas, but to me it seems OK to change this, if we really want to.
