### ISSUE TITLE
Cannot map column values based on column index

### ISSUE THREAD

**Issue by mitar** [pandas-dev/pandas#26508]
#### Code Sample, a copy-pastable example if possible

```python
df.iloc[:, 0] = df.iloc[:, 0].map(lambda x: x + 1)

```

#### Problem description

The above raises a warning:

```
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
```

I have not found a way where I could map values in a column, but that column would be identified by the column index and that it would work with columns with non-unique column names.

#### Output of ``pd.show_versions()``

<details>

Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
pd.show_versions()>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Linux
OS-release: 4.18.0-20-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: None
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 4.5.0
pip: 19.0.3
setuptools: 41.0.1
Cython: 0.29.7
numpy: 1.15.4
scipy: 1.2.1
pyarrow: 0.13.0
xarray: None
IPython: None
sphinx: 1.6.7
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2018.3
blosc: None
bottleneck: 1.2.1
tables: None
numexpr: 2.6.9
feather: None
matplotlib: 3.1.0
openpyxl: 2.5.14
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: None
lxml: 4.3.3
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: 2.8.2 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jschendel** [comment]
You're likely making a copy elsewhere in your code, as a minimal version of what you're describing does not trigger the `SettingWithCopyWarning`:
```python
In [1]: import pandas as pd; import numpy as np

In [2]: df = pd.DataFrame(np.zeros((3,5)), columns=list('AABBC'))

In [3]: df
Out[3]:
     A    A    B    B    C
0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0

In [4]: df.iloc[:, 0] = df.iloc[:, 0].map(lambda x: x + 1)

In [5]: df
Out[5]:
     A    A    B    B    C
0  1.0  0.0  0.0  0.0  0.0
1  1.0  0.0  0.0  0.0  0.0
2  1.0  0.0  0.0  0.0  0.0
```
For an example of making a copy:
```python
In [6]: df2 = df[['A', 'C']]

In [7]: df2
Out[7]:
     A    A    C
0  1.0  0.0  0.0
1  1.0  0.0  0.0
2  1.0  0.0  0.0

In [8]: df2.iloc[:, 0] = df2.iloc[:, 0].map(lambda x: x + 1)
SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame
```

**Comment by mitar** [comment]
Yes, but that is preselection. I do something like:

```python
import pandas as pd; import numpy as np

def preselect(df):
    return df.iloc[:, [0,1,2]]

def df_map(df):
    df.iloc[:, 0] = df.iloc[:, 0].map(lambda x: x + 1)
    return df

df = pd.DataFrame(np.zeros((3,5)), columns=list('AABBC'))

subset_df = preselect(df)

df = df_map(subset_df)
```

**Comment by mitar** [comment]
The issue is that `preselect` and `df_map` are in two completely separate modules and do not know anything about each other and `df_map` does not know if input has went through `preselect` or not.

How can I make it so that `preselect` really just returns a new value without this side-effect?

**Comment by mitar** [comment]
So for me `preselect` should be returning a new object. Assigning to returned value should not be modifying original input to `preselect`.

**Comment by mitar** [comment]
OK, 

```python
def preselect(df):
    return df.iloc[:, [0,1,2]].copy()
```

Is the solution.

Thanks.
