### ISSUE TITLE
IntervalIndex.get_indexer "method" options are not implemented but documentation implies they are

### ISSUE THREAD

**Issue by lucianoviola** [pandas-dev/pandas#26506]
#### Problem description

`IntervalIndex.get_indexer` returns `NotImplementedError` if `method` is any of the ones shown in the docstring and documentation (except for 'method=None'). I understand that they are not implemented yet, but that is not clear from the docstring.  It presents the 5 available options as if they are implemented. 

Wouldn't it be better to remove `method`, if none of the options are available? Or at least make it more clear in the documentation. 

Documentation: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.IntervalIndex.get_indexer.html

Exception is raised here:
https://github.com/pandas-dev/pandas/blob/master/pandas/core/indexes/interval.py#L811

**Comment by timgates42** [comment]
I see the documentation has already been forked for the get_loc method of IntervalIndexer I'll apply the same pattern for the get_indexer call and send through a PR

**Comment by lucianoviola** [comment]
I'm not sure what is the pandas core team thinks its the best approach for this. It might be the case that nothing needs to be done. Eles, I would like to work on the issue.

**Comment by timgates42** [comment]
I can’t speak for the pandas core team but that was sort of my assumption - I put a quick fix in to the documentation that the method parameter options were not yet implemented and that if the pandas core team agree an implementation would come and remove the documentation change.

**Comment by jreback** [comment]
closed by #26519
