### ISSUE TITLE
Merge fails when the dataframe contains an empty UInt/Int column

### ISSUE THREAD

**Issue by alvarodemig** [pandas-dev/pandas#26507]
```python

import pandas as pd
import numpy as np
df = pd.DataFrame({'a': [np.nan, np.nan], 'b': [np.nan, 1], 'c': [0,1]}, dtype='Int8')
df['c'] = df.c.astype(int)

df.merge(df, on ='a')  # Does not work
df.merge(df, on ='b')  # Does not work
df.merge(df, on ='c')  # Does not work
df.merge(df, right_index = True, left_index = True)  # Works

df[['b']].merge(df[['b']], on ='b')  #Works
df[['a']].merge(df[['a']], on ='a')  #Does not work

df[['b', 'c']].merge(df[['b', 'c']], on ='b')  #Works
df[['b', 'c']].merge(df[['b', 'c']], on ='c')  #Works

df[['a', 'c']].merge(df[['a', 'c']], on ='a')  #Does not work
df[['a', 'c']].merge(df[['a', 'c']], on ='c')  #Does not work

```
#### Problem description

Merge fails returning `TypeError: data type not understood` when you try to merge a dataframe that contains an empty Int/UInt column and you don't use the index for the merge.

It seems to work if you use the index to merge, but it will fail if you use any other, no matter the type of the column

#### Expected Output

It is expected to complete the merge.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Darwin
OS-release: 17.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.1
pytest: None
pip: 19.1
setuptools: 41.0.1
Cython: None
numpy: 1.14.1
scipy: 1.0.0
pyarrow: 0.10.0
xarray: None
IPython: 7.2.0
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2019.1
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.1.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: 1.1.7
lxml.etree: 4.3.3
bs4: 4.6.3
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: 2.7.3.2 (dt dec pq3 ext lo64)
jinja2: 2.10.1
s3fs: 0.1.4
fastparquet: 0.2.1
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by WillAyd** [comment]
Can you try on master? I wasn't able to reproduce any issue here

**Comment by TomAugspurger** [comment]
I can't reproduce either. Let us know if you can provide more info.
