### ISSUE TITLE
MAINT: port numpy#13188 for np_datetime simplification

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#26500]
our _libs/tslibs/src/np_datetime.c is based off of the numpy version.  A recent PR there made a pretty nice simplfication to the relevant code.  We should do the same.

https://github.com/numpy/numpy/pull/13188/files

**Comment by xcz011** [comment]
If possible, I’d like to contribute this. I may need some help since this is my first contribution. Thanks!

**Comment by jbrockmendel** [comment]
Great, a PR is welcome.  If you're comfortable with C, it's just a matter of making sure we haven't changed anything that would make that patch inapplicable, then copy/paste, with appropriate attribution.
