### ISSUE TITLE
CLN: modernize describe_categorical_1d

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#26510]
https://github.com/pandas-dev/pandas/pull/26474/files#diff-03b380f521c43cf003207b0711bac67fL9898

This is very hacky way of processing datetimelikes. Also this likely doesn't properly handle categoricals that have other things as categories (Timedelta, Extension scalars)

**Comment by enisnazif** [comment]
Happy to take a look at this

**Comment by mroeschke** [comment]
The current `describe_categorical_1d` looks a lot cleaner now and doesn't have any special dtype casing. I think the function has been sufficiently modernized so closing.
