### ISSUE TITLE
Allow Keyword Aggregation in DataFrame.agg and Series.agg

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#26513]
Followup to https://github.com/pandas-dev/pandas/pull/26399

```python
In [2]: df = pd.DataFrame({"A": [1, 2, 1, 2], "B": [1, 2, 3, 4]})

In [3]: df
Out[3]:
   A  B
0  1  1
1  2  2
2  1  3
3  2  4

In [4]: df.agg(foo=("B", "sum"))
```

Expected Output

```python
In [13]: df.agg({"B": {"foo": "sum"}})
/Users/taugspurger/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/frame.py:6284: FutureWarning: using a dict with renaming is deprecated and will be removed in a future version
  result, how = self._aggregate(func, axis=axis, *args, **kwargs)
Out[13]:
      B
foo  10
```

without the warning. Similar for `Series.agg`

```python
In [16]: df.B.agg({"foo": "sum"})  # allow foo="sum"
Out[16]:
foo    10
Name: B, dtype: int64
```

**Comment by TomAugspurger** [comment]
Is this a blocker for 0.25.0? Is anyone interested in working on it? I'm not.

cc @zertin, @smcateer, @pirsquared, who seemed interested in this for the GroupBy.agg context (this is for DataFrame/Series.agg).

**Comment by zertrin** [comment]
I am not sure what this follow-up corresponds to.

As blocker, I remember the multiple lambda problem, for which I believe you said you had a WIP.

Which of the blocker remaining issues this issue corresponds to? The description is unclear to me.

**Comment by TomAugspurger** [comment]
Multiple lambdas is at https://github.com/pandas-dev/pandas/pull/26905 (tagged for 0.25, but needs review).

This issue is about supporting the new named aggregation syntax in DataFrame.agg, rather than just DataFrameGroupBy.agg (likewise for Series). Ideally, these two wouldn't diverge in behavior.

```python
In [2]: df = pd.DataFrame({"A": [1, 2, 1, 2], "B": [1, 2, 3, 4]})

In [3]: df
Out[3]:
   A  B
0  1  1
1  2  2
2  1  3
3  2  4

In [4]: df.agg(foo=("B", "sum"))
      B
foo  10
```

**Comment by TomAugspurger** [comment]
Would be nice, but not a blocker. Pushing.

**Comment by christopherzimmerman** [comment]
@TomAugspurger I'm going to look into this, just had a question about desired behavior.

Currently, if you aggregate different functions on different series with `DataFrame.agg`, you still get a Series back:

```python
In [16]: df = pd.DataFrame({"A": [1, 2, 1, 2], "B": [1, 2, 3, 4]})

In [17]: df
Out[17]:
   A  B
0  1  1
1  2  2
2  1  3
3  2  4

In [18]: df.agg({"A": "sum", "B": "mean"})
Out[18]:
A    6.0
B    2.5
dtype: float64
```

For the example you provided above, it would seem the result would be something like:

```python
In [18]: df.agg(foo=("B", "mean"), bar=("A", "sum"))
Out[18]:
       A    B
foo    6  NaN
bar  NaN  2.5
```
 
When something like:

```
foo    6.0
bar    2.5
dtype: float64
```

Would be the closest to current behavior.  Any thoughts?

**Comment by TomAugspurger** [comment]
You're probably right about the expected output being a Series there.
