### ISSUE TITLE
Merge on key idenfitied by column index is not possible

### ISSUE THREAD

**Issue by mitar** [pandas-dev/pandas#26532]
#### Code Sample

```python
>>> import pandas
>>> a = pandas.DataFrame([[1,2,3], [4,5,6], [7, 8, 9]], columns=['a', 'b', 'a'])
>>> b = pandas.DataFrame({'a': [1,1,1], 'c': [10,11,12]})
>>> a
   a  b  a
0  1  2  3
1  4  5  6
2  7  8  9
>>> b
   a   c
0  1  10
1  1  11
2  1  12
>>> b.merge(a, left_on=0, right_on=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mitar/.virtualenv/test/lib/python3.6/site-packages/pandas/core/frame.py", line 6929, in merge
    copy=copy, indicator=indicator, validate=validate)
  File "/home/mitar/.virtualenv/test/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 46, in merge
    validate=validate)
  File "/home/mitar/.virtualenv/test/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 534, in __init__
    self.join_names) = self._get_merge_keys()
  File "/home/mitar/.virtualenv/test/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 875, in _get_merge_keys
    right._get_label_or_level_values(rk))
  File "/home/mitar/.virtualenv/test/lib/python3.6/site-packages/pandas/core/generic.py", line 1741, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 0
```

#### Problem description

If column names are not unique (which happens to us much more often than one would hope for, for example, when reading multiple CSV files and horizontally concatenating them together) merge operation cannot operate on them. If you try, you get `ValueError: The column label 'a' is not unique.` exception. Which is understandable, because it is not possible to know on which column really you want to do the merge.

But there is also no other way currently. You cannot merge by specifying the index of the column you want to do join on. I would suggest such an option/argument should be added.

#### Expected Output

```
   a   c  b  a
0  1  10  2  3
1  1  11  2  3
2  1  12  2  3
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Linux
OS-release: 4.18.0-20-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.25.0.dev0+610.gd2beaf3c8
pytest: None
pip: 18.1
setuptools: 40.7.1
Cython: 0.29.7
numpy: 1.15.4
scipy: 1.2.0
pyarrow: 0.13.0
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by jreback** [comment]
this us likely out of scope; we don’t generally want to specify things like merge keys by position as this is extremely fragile (in fact any use of positional indicators outside of indexing is out of scope)

you have to be careful of duplicate indices and take care yourself

**Comment by jreback** [comment]
closing as similar to #26530 and out of scope

**Comment by mitar** [comment]
So in our case (where we are building ML pipelines as part of a larger AutoML system) it is much more common that column names are duplicated and not meaningful.

But column index is the only stable way to at a given moment identify a column in unique way. So you have a DataFrame, you scan columns, you decide you want to do some operation on some column. At that time column index is the best way to identify it and do the operation. I mean, this is probably also why you have `iloc` in the first place. If you support `iloc`, you should also support all other operations to be by index. There is no other current way to uniquely identify a column and operate on it.

**Comment by jreback** [comment]
pandas is all about alignment of operations
duplicate indexes are a second class citizen generally and you should use MultiIndexes or remove duplicates before doing other operations

this is a fairly standard workflow and pandas is not going to increase scope to do already supoorted thjngs

**Comment by mitar** [comment]
Why is then Pandas even supporting duplicate column names? (I am talking about duplicate columns, not duplicate indexes, but maybe I am missing terminology here.)

**Comment by jreback** [comment]
@mitar you are missing the point

pandas supports having duplicate column names because they can easily arise from some operations ; the resolution of these cannot be automatic so a user needs to take care 
using positional indexing is not a good solution generally (but it is one possibility here)
