### ISSUE TITLE
Drop by column index does not exist

### ISSUE THREAD

**Issue by mitar** [pandas-dev/pandas#26530]
#### Code Sample

```python
>>> import pandas
>>> a = pandas.DataFrame({'a': [1,2,3], 'b': [4,5,6]})
>>> a = pandas.concat([a, a], axis=1)
>>> a
   a  b  a  b
0  1  4  1  4
1  2  5  2  5
2  3  6  3  6
>>> a.drop(0, axis=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mitar/.virtualenv/aika36/lib/python3.6/site-packages/pandas/core/frame.py", line 3697, in drop
    errors=errors)
  File "/home/mitar/.virtualenv/aika36/lib/python3.6/site-packages/pandas/core/generic.py", line 3111, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/mitar/.virtualenv/aika36/lib/python3.6/site-packages/pandas/core/generic.py", line 3162, in _drop_axis
    raise KeyError('{} not found in axis'.format(labels))
KeyError: '[0] not found in axis'
```
#### Problem description

It does not seem to be an easy way to drop a column by its column index. This makes it hard to drop columns when there are duplicate column names in the DataFrame.

#### Expected Output

```
   b  a  b
0  4  1  4
1  5  2  5
2  6  3  6
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Linux
OS-release: 4.18.0-20-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 4.4.1
pip: 19.0.3
setuptools: 40.4.3
Cython: None
numpy: 1.15.4
scipy: 1.1.0
pyarrow: 0.13.0
xarray: None
IPython: None
sphinx: 1.8.1
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.9999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment]
I don’t think we would want to implicitly fall back to location-based here.

**Comment by jreback** [comment]
agree this is out of scope

you can use .index[0]

**Comment by mitar** [comment]
I would not want to fallback to location-based, but it could be something like `a.drop(by_column_index=0, axis=1)`.

> you can use .index[0]

Can you elaborate? How can I use that to drop column by index?

**Comment by jreback** [comment]
adding more options is not worth it hear as it adds too much api complexity

**Comment by mitar** [comment]
OK, but is there any other way to drop a column by index? (And if so, it would be useful to mention/reference it inside `drop` documentation.)

**Comment by jreback** [comment]
you can simple select the other columns eg

df.iloc[:, 1:]

**Comment by mitar** [comment]
`df.iloc[:, 1:]` only works to drop the first one. But not to drop the second column, for example.

**Comment by jreback** [comment]
the selection syntax is very flexible
you can specify a slice, list or use composition operators
eg np.s_

**Comment by mitar** [comment]
Does not work for me:

```
>>> a.iloc[:, np.s_[0, 2:]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mitar/.virtualenv/test/lib/python3.6/site-packages/pandas/core/indexing.py", line 1498, in __getitem__
    return self._getitem_tuple(key)
  File "/home/mitar/.virtualenv/test/lib/python3.6/site-packages/pandas/core/indexing.py", line 2152, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/home/mitar/.virtualenv/test/lib/python3.6/site-packages/pandas/core/indexing.py", line 221, in _has_valid_tuple
    self._validate_key(k, i)
  File "/home/mitar/.virtualenv/test/lib/python3.6/site-packages/pandas/core/indexing.py", line 2078, in _validate_key
    raise IndexingError('Too many indexers')
pandas.core.indexing.IndexingError: Too many indexers
```
