### ISSUE TITLE
same .tsv file, get different data-frame structure using engine 'python' and 'c'

### ISSUE THREAD

**Issue by Jane-Eyre** [pandas-dev/pandas#26545]
In my Mac, I have a Tab-Separated values file with encoding UTF-8, and the version of pandas is 
0.24.2.
[74872_zh_CN_UI.txt](https://github.com/pandas-dev/pandas/files/3227255/74872_zh_CN_UI.txt)

when I use read_csv function with engine 'python' like this:
`b = pd.read_csv("/Users/GHIBLI/Documents/vmware-L10n/bert/zh_CN/74872_zh_CN_UI.tsv",
                engine="python", delimiter="\t")`
` print(b.shape)`
I got (8, 1)

if with default engine:
`b = pd.read_csv("/Users/GHIBLI/Documents/vmware-L10n/bert/zh_CN/74872_zh_CN_UI.tsv",
                delimiter="\t")`
` print(b.shape)`
I got (8,22)

In contrast to 'C' engine, this 'python' engine seems that is not as simple as  just 'feature-complete' I think.

**Comment by Liam3851** [comment]
I cannot reproduce using pandas 0.24.2 on either Ubuntu or Windows -- both show the shape as (8, 22) using both engines. It could be a Mac-specific issue, though it would be odd that the Python-engine implementation would behave differently based on the OS.

**Comment by WillAyd** [comment]
I can reproduce this on master. If you would like to take a deeper look and see what's going on would certainly appreciate it!

**Comment by Liam3851** [comment]
@WillAyd Are you using a Mac? I can't reproduce on master using Windows/python 3.7.3 (I suppose perhaps this could also be a python version difference, rather than an OS difference)

```python
In [1]: import pandas as pd

In [2]: pd.__version__
Out[2]: '0.25.0.dev0+615.g998a0deea'

In [3]: pd.read_csv('74872_zh_CN_UI.txt', delimiter='\t', engine='python').shape
Out[3]: (8, 22)
```

**Comment by WillAyd** [comment]
Yes macOS on master

**Comment by LuckyDenis** [comment]
I was able to play on linux 19.04 Python 3.7 Pandas 0.24.2

**Comment by LuckyDenis** [comment]
Good afternoon, I found where in what a mistake. But have not yet figured out how best to fix it. Do you mind if I take this task?
