### ISSUE TITLE
Deprecate xlwt

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#26552]
Similar to the conversation in #26487 xlwt isn't maintained. If we deprecate this could open up the path to simplify our Excel writers / extensions and supported file types going forward.

I would think this is also much easier than deprecating xlrd since we have other writers already implemented.

**Comment by jorisvandenbossche** [comment]
That would also mean deprecating the `xls` format? (or can the other engines write such files as well?)

I don't think I necessarily mind (fro writing, as long as we can still read old formats), but just to make it clear?

**Comment by WillAyd** [comment]
That's correct - xlwt and xlrd are the only engines that support the .xls format

**Comment by jbrockmendel** [comment]
Is there any value in getting this (and the other excel-related deprecations) done for 1.0?  If we're not enforcing the deprecations until 2.0, im tempted to just ignore all DEPR issues until [2 releases before 2.0]

**Comment by WillAyd** [comment]
Probably worth getting #29375 in before 1.0

**Comment by jreback** [comment]
cc @pandas-dev/pandas-core if anyone wants to do this for 1.2

**Comment by rhshadrach** [comment]
@jreback Is this something we could potentially do during the rc phase for 1.2? I can take this up, but not for another 2 days.

**Comment by jreback** [comment]
yeah i think this would be fine during rc

**Comment by rhshadrach** [comment]
Based on the decisions made in #35029, I'm not sure there is anything to do here. For reading, when a user specifies ``engine="xlrd"`` or the extension is `.xls`, the xlrd engine is used and no warning is emitted. I think we want to parallel that behavior for writing, and as far as I can tell, that is already the case. 

Namely, we get the config `f"io.excel.{ext}.writer"` where `ext` is the file extension (defaults to "xlsx" if path is not a string). This config defaults to "auto" which uses the following logic to determine the engine based on the extension.

```
    _default_writers = {
        "xlsx": "openpyxl",
        "xlsm": "openpyxl",
        "xls": "xlwt",
        "ods": "odf",
    }
    xlsxwriter = import_optional_dependency(
        "xlsxwriter", raise_on_missing=False, on_version="warn"
    )
    if xlsxwriter:
        _default_writers["xlsx"] = "xlsxwriter"
```

So a user will only be using `xlwt` if they specify ``engine="xlwt"``, have overridden the default config, or if the path is a string with the extension `xls`. I think in each of these cases, we do not want to emit a warning.

**Comment by rhshadrach** [comment]
Ahh, I see. I think we want to deprecate writing `xls` but not reading `xls`, so a DeprecationWarning should be emitted anytime `xlwt` is used regardless of how we got there.
