### ISSUE TITLE
Default string to be treated as missing value in a series.

### ISSUE THREAD

**Issue by vaibhawc** [pandas-dev/pandas#26559]
Hi, this is more of a question than an issue.
I wanted to use default string as a representation for missing values for my project. Is there a way to incorporate inside my pandas lib or implementing it in the project is the only way to do?
For example :  I want to use '?' to show that my some value in my datetime type series is missing, instead of pd.NaT. Now pd.NaT will respond to addition operation but '?' won't. Can I make '?' to be treated as missing value and if yes is there a way to do inside pandas? This should also mean that <series> is retained as datetime type and not object.

**Comment by jreback** [comment]
- you could write your own extension array for this
- you can configure missing values for some io routines (to_csv(indicators 
- simply fill na when needed

but generally pandas is not that configurable as the implementation does drive this (datetimea for example are represented as integers so mixing types is non performant)

if u you really really need this then an extension array is prob best

**Comment by vaibhawc** [comment]
Sure, thanks!
