### ISSUE TITLE
read_excel and ExcelFile engine conflict

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#26566]
This is currently valid code:

```python
>>> xl = pd.ExcelFile('foo.xlsx', engine='xlrd')
>>> pd.read_excel(xl, engine='openpyxl')
Empty DataFrame
Columns: []
Index: []
```

Though ambiguous as to which engine is actually being used. I think we should be raising if an engine is specified in `read_excel` when the target is a `pd.ExcelFile`, as the latter is a lower level construct and will already have an engine in place.

@simonjayhawkins

**Comment by WillAyd** [comment]
To clarify I suppose this isn’t ambiguous now since xlrd is our only reader but will be once that doesn’t hold true. May be a similar issue on the write side

**Comment by alimcmaster1** [comment]
Makes sense to me - happy to take a look

**Comment by sumanau7** [comment]
Isn't this a documentation issue, because only when input to `read_excel` is not an instance of `ExcelFile`, then only engine argument given to `read_excel` will be used, in all other cases, engine argument has no impact whatsoever. @WillAyd

**Comment by alimcmaster1** [comment]
I think Will is suggesting it should throw some kind of error - otherwise it’s ambiguous ( without reading the docs ) what the engine is . But a doc update would be welcome too - I can do that as part of the PR
