### ISSUE TITLE
BUG: pivot_table with margins=True and numeric columns is buggy

### ISSUE THREAD

**Issue by jschendel** [pandas-dev/pandas#26568]
#### Code Sample, a copy-pastable example if possible
Setup:
```python
In [1]: import pandas as pd; pd.__version__
Out[1]: '0.25.0.dev0+620.ga91da0c94e'

In [2]: df = pd.DataFrame([['a', 'x', 1], ['a', 'y', 2],
   ...:                    ['b', 'y', 3], ['b', 'z', 4]])

In [3]: df
Out[3]:
   0  1  2
0  a  x  1
1  a  y  2
2  b  y  3
3  b  z  4
```

When `index=0` and `columns=1` the `'All'` row has zeros instead of the sums:
```python
In [4]: df.pivot_table(index=0, columns=1, values=2,
   ...:                aggfunc="sum", fill_value=0, margins=True)
Out[4]:
1    x  y  z  All
0
a    1  2  0    3
b    0  3  4    7
All  0  0  0   10
```
If the `index` parameter is not 0 or -1 an `IndexError` is raised, but only if `margins=True`:
```python
In [5]: df.columns = [10, 20, 30]
   ...: df.pivot_table(index=10, columns=20, values=30,
   ...:                aggfunc="sum", fill_value=0, margins=True)
---------------------------------------------------------------------------
IndexError: Too many levels: Index has only 1 level, not 11

In [6]: df.pivot_table(index=10, columns=20, values=30,
   ...:                aggfunc="sum", fill_value=0)
Out[6]:
20  x  y  z
10
a   1  2  0
b   0  3  4
``` 
This works fine for non-numeric columns:
```python
In [7]: df.columns = ['foo', 'bar', 'baz']
   ...: df.pivot_table(index='foo', columns='bar', values='baz',
   ...:                aggfunc="sum", fill_value=0, margins=True)
Out[7]:
bar  x  y  z  All
foo
a    1  2  0    3
b    0  3  4    7
All  1  5  4   10
```
It also works fine if `index=0` and the `columns` parameter is a numeric value other than 1:
```python
In [8]: df.columns = [0, 2, 1]
   ...: df.pivot_table(index=0, columns=2, values=1,
   ...:                aggfunc="sum", fill_value=0, margins=True)
Out[8]:
2    x  y  z  All
0
a    1  2  0    3
b    0  3  4    7
All  1  5  4   10
```

#### Problem description

The output of `pivot_table` with `margins=True` is inconsistent for numeric column names

#### Expected Output
I'd expect the output to be consistent with `Out[7]` / `Out[8]`

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: a91da0c94e541217865cdf52b9f6ea694f0493d3
python: 3.6.8.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.25.0.dev0+620.ga91da0c94e
pytest: 4.2.0
pip: 19.0.1
setuptools: 40.6.3
Cython: 0.28.2
numpy: 1.16.2
scipy: 1.2.1
pyarrow: 0.6.0
xarray: 0.9.6
IPython: 7.2.0
sphinx: 1.8.2
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.9
feather: 0.4.0
matplotlib: 2.0.2
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 0.9.8
lxml.etree: 3.8.0
bs4: None
html5lib: 0.999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: 0.1.5
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by mroeschke** [comment]
This looks to work on master. Could use a test

```
In [9]:
   ...: In [2]: df = pd.DataFrame([['a', 'x', 1], ['a', 'y', 2],
   ...:    ...:                    ['b', 'y', 3], ['b', 'z', 4]])

In [11]: In [5]: df.columns = [10, 20, 30]
    ...:    ...: df.pivot_table(index=10, columns=20, values=30,
    ...:    ...:                aggfunc="sum", fill_value=0, margins=True)
Out[11]:
20   x  y  z  All
10
a    1  2  0    3
b    0  3  4    7
All  1  5  4   10
```

**Comment by simonjayhawkins** [comment]
the first example is not fixed, The totals for the columns is zero.

```
>>> pd.__version__
'1.4.0.dev0+266.gbe9ffce14a'
>>> 
>>> df = pd.DataFrame([["a", "x", 1], ["a", "y", 2], ["b", "y", 3], ["b", "z", 4]])
>>> 
>>> df.pivot_table(index=0, columns=1, values=2, aggfunc="sum", fill_value=0, margins=True)
1    x  y  z  All
0                
a    1  2  0    3
b    0  3  4    7
All  0  0  0   10
>>> 
```

**Comment by bgollop** [comment]
take
