### ISSUE TITLE
Remove gtk imports from codebase

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#26563]
We have a few "import gtk" imports in the clipboards part of the code base but I cannot find any information as to what these actually are, so I assume these are especially outdated given our drop of Py27 support.

I *think* this used to be a part of PyGTK, but links to that (like http://www.pygtk.org/) seem to redirect now to PyGObject which has different import machinery anyway

**Comment by xcz011** [comment]
Hi @WillAyd, I just give a PR, and hope I understand you correctly. If not, please feel free to correct me. Thanks.
