### ISSUE TITLE
Clip Could take Series/DataFrames

### ISSUE THREAD

**Issue by rhaskett** [pandas-dev/pandas#2657]
I was a little surprised when clip would not take other pandas objects as parameters.  I hacked a little something below, but for readability I thought I might suggest that this feature be added.

```
df1 = DataFrame(ones((2, 2)))
data = ones((2, 2))
data[0, 0] = 0
data[1, 1] = 2
df2 = DataFrame(data)
print df2.clip(1.5, 0.5)

df3 = df2.copy()
df3[df2 > df1 * 1.5] = (df1 * 1.5)[df2 > df1 * 1.5]
df3[df2 < df1 * .5] = (df1 * .5)[df2 < df1 * .5]
print df3
```

**Comment by kokes** [comment]
Isn't this a duplicate of #6966? I've just tested the second example and it does work.

**Comment by jreback** [comment]
yep

**Comment by brandon-rhodes** [comment]
I was commenting on Pandas issues back in 2013 — five years ago? Wow, I've used Pandas for a long time!

I'm happy to hear that clipping against series is now possible!
