### ISSUE TITLE
BLD: wheel building failing for install issue

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#26589]
https://travis-ci.org/MacPython/pandas-wheels/jobs/539541488
https://travis-ci.org/MacPython/pandas-wheels/builds/539541484 (the builds)

just started failing

cc @pandas-dev/pandas-core

**Comment by TomAugspurger** [comment]
New cryptography release

old:

```
Collecting cryptography>=2.3.0 (from moto)
  Downloading https://files.pythonhosted.org/packages/93/1a/69ddcb02759b4e196ab3785315fc87ec6246427effd360bcb373206842ea/cryptography-2.6.1-cp34-abi3-manylinux1_i686.whl (2.1MB)
```

new:

```
Collecting cryptography>=2.3.0 (from moto)
  Downloading https://files.pythonhosted.org/packages/c2/95/f43d02315f4ec074219c6e3124a87eba1d2d12196c2767fadfdc07a83884/cryptography-2.7.tar.gz (495kB)
```

Seems like there are manylinux wheels for 2.7, and 3.4 but not 3.6 (failing build). https://pypi.org/project/cryptography/2.7/#files

Aside: do you get notifications for these failures @jreback?

**Comment by TomAugspurger** [comment]
Wait I'm confused now. The failing job is for python 3.6, but it seems like for cryptography 2.6.1 it downloaded the  wheel with the `-cp34-abi3-manylinux1`... i.e. the wheel for CPython 3.4

**Comment by TomAugspurger** [comment]
I restarted the build, to ensure that the wheels were actually present when we tried to fetch them. It did indeed fail.

When I create a linux py36 environment locally, and `pip install cryptography`, I do get the `cryptography-2.7-cp34-abi3-manylinux1` wheel.

**Comment by TomAugspurger** [comment]
Ah the difference is probably the platform. That build is 32-bit.

https://cryptography.io/en/latest/changelog/

> BACKWARDS INCOMPATIBLE: We no longer distribute 32-bit manylinux1 wheels. Continuing to produce them was a maintenance burden.

So for now let's include `--binary-only=cryptography` for this.

**Comment by jreback** [comment]
yes i get notification from pandas-wheels on failures

not sure how though
