### ISSUE TITLE
Compression keyword for Stata and others?

### ISSUE THREAD

**Issue by ozak** [pandas-dev/pandas#26599]
Hi,

I was trying to open zipped Stata files and thought one could do it as in ``read_csv``using  the ``compression='zip'`` keyword option. Is this not implemented? Saw #15644 and follow ups, but at the time it seems the discussion was about output not input files. In many cases providers give Stata files in zip format, which e.g. in my case may mean 1000's of different zipped archives containing Stata + other files. #12103 seems to have added the functionality more generally, but at least in ``pd.__version__=0.23.4`` it still complains when passing the ``compression`` keyword. I do not see the option in ``pandas/io/stata.py`` although in ``common.py`` the option seems to be there. Any pointers? I am happy to contribute if I can figure out where and how this is implemented for other formats.

**Comment by WillAyd** [comment]
Related issue #21640

**Comment by bashtage** [comment]
Compression on io function is for native compression.  csv can be gziped so this looks like a native (and common) compression.  Stata dta files do not support compression.  All you need to do is to use `zipfile.ZipFile` to traverse the `.dta` files, and then you can read them into DataFrames using `read_stata`.  This doesn't require (or justify) adding an option to `read_stata` that is supporting something that is orthogonal to the dta file format.

**Comment by ozak** [comment]
Since all kinds of files can be zipped and are distributed like that, it seems strange to implement it in one kind and not others. In any case, you are right that any zip file can be unzipped and loaded into a ``pandas`` data frame using ``zipfile``.

**Comment by MaxGhenis** [comment]
This distinction also seems strange to me; Stata files are commonly zipped (e.g. the Federal Reserve's Survey of Consumer Finances, where zipping reduces filesize by 90%), and since it's possible, it seems more convenient to offer the same interface provided to `read_csv`.

I asked how to do this and got a couple answers using `zipfile.ZipFile`: https://stackoverflow.com/questions/59122596/read-a-zipped-stata-file-from-url-into-pandas

**Comment by jzwinck** [comment]
I agree, it's not nice that `read_csv` and `read_json` and `read_pickle` all understand compression but `read_stata` does not.  Zipped Stata files are popular, and there's a `zipsave` package to create and load them in their native habitat: https://ideas.repec.org/c/boc/bocode/s446702.html

Pandas should support this.  @WillAyd would you consider re-opening this?

**Comment by MaxGhenis** [comment]
Friendly ping, I got the same error messages as [above](https://github.com/pandas-dev/pandas/issues/26599#issuecomment-678586608) in pandas 1.2.0.

**Comment by bashtage** [comment]
@MaxGhenis it has not been added to `StataReader`, so this is the expected outcome.

**Comment by MaxGhenis** [comment]
@bashtage would adding that be a separate issue? Or is there another way to read a zipped stata file now?

**Comment by jreback** [comment]
pls create a new issue
