### ISSUE TITLE
CI: Use azure-pipelines reporting for pytest data

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#26601]
Azure Pipelines can show errors and warnings clearer, by adding some specific syntax to the log.

We are already using this for the linting, where we output flake8 errors like `##vso[task.logissue type=error;sourcepath=%(path)s;linenumber=%(row)s;columnnumber=%(col)s;code=%(code)s;]%(text)s` (see `ci/code_checks.sh`).

This makes it easier to find the errors in the logs, as they appear in the summary. See for example the `Checks_and_docs` build in https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=12078

We should be using the same for tests, and also "upload" to Azure pipelines the summary of the tests.

This is implemented in this pytest plugin: https://github.com/tonybaloney/pytest-azurepipelines

I guess the best option is to install the plugin (may be install in the azure yaml files, as the dependency is not useful outside of azure). The plugin is quite simple, if it makes sense we may prefer to implement something specific to our needs based on the plugin code: https://github.com/tonybaloney/pytest-azurepipelines/blob/master/pytest_azurepipelines.py

**Comment by TomAugspurger** [comment]
I use this for dask-ml and it seems to work well.
