### ISSUE TITLE
CI failing - All builds are failing on python 3.5 on pytest 4.6

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#26614]
https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=12138

cc @pandas-dev/pandas-core

**Comment by WillAyd** [comment]
Might be a result of the jump from pytest 4.5 to 4.6, though wasn't able to reproduce locally

**Comment by h-vetinari** [comment]
It is a pytest issue: pytest-dev/pytest#5358. Would help to pin "pytest<4.6" for now.

**Comment by jreback** [comment]
we can pin those builds specifically

**Comment by simonjayhawkins** [comment]
just about to submit PR, may have the syntax wrong though

    # universal
    - pytest>=4.0.2,!=4.6.0

**Comment by jreback** [comment]
use<4.6 (or for those older builds just pin directly to a single version
