### ISSUE TITLE
All builds are failing on python 3.5

### ISSUE THREAD

**Issue by topper-123** [pandas-dev/pandas#26618]
It seems like all PRs are currently failing on "macOS py35_macos" and "Linux py35_compat".

I assume this must be a Python 3.5 failure, though I haven't been able to verify that, as I can't seem to be able to build pandas with Python 3.5 locally. (So I can't fix this either, as everything works fine on my Python3.7).

**Comment by simonjayhawkins** [comment]
duplicate of #26614
