### ISSUE TITLE
Appender Causing MyPy Issues

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#26629]
ref https://github.com/pandas-dev/pandas/pull/26414#issuecomment-498224395 it appears that mypy and the Appender may not be playing nice together. A solution to this may be tucked away in https://github.com/python/mypy/issues/3157

**Comment by jbrockmendel** [comment]
Whats the win condition here?  i.e. how can i check whether this is fixed?

**Comment by WillAyd** [comment]
Closing this in favor of #27404 - there is more details therein

**Comment by WillAyd** [comment]
Though should have been solved by #28128
