### ISSUE TITLE
Investigate performance regression in TimeSeries.infer_freq

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#26640]
A whole bunch of them: 

- [ ] InferFreq: http://pandas.pydata.org/speed/pandas/index.html#timeseries.InferFreq.time_infer_freq?commits=9c5165e26260483ae64300c4d98939bf575aab7e-8154efb0c1a64295cf54e00025b4ab09bcd02752&p-freq=%27D%27
- [ ] DatetimeIndex http://pandas.pydata.org/speed/pandas/index.html#timeseries.DatetimeIndex.time_timeseries_is_month_start?commits=9c5165e26260483ae64300c4d98939bf575aab7e-8154efb0c1a64295cf54e00025b4ab09bcd02752&p-index_type=%27repeated%27
- [ ] offsets.ApplyIndex: http://pandas.pydata.org/speed/pandas/index.html#offset.ApplyIndex.time_apply_index?p-offset=%3CMonthEnd%3E&commits=9c5165e26260483ae64300c4d98939bf575aab7e-8154efb0c1a64295cf54e00025b4ab09bcd02752
- [ ] io.json.ToJSON.time_delta_int_tstamp: http://pandas.pydata.org/speed/pandas/index.html#io.json.ToJSON.time_delta_int_tstamp?p-orient=%27columns%27&commits=9c5165e26260483ae64300c4d98939bf575aab7e-8154efb0c1a64295cf54e00025b4ab09bcd02752
- [ ] index_object.Indexing.time_get('String')?: http://pandas.pydata.org/speed/pandas/index.html#index_object.Indexing.time_get?commits=9c5165e26260483ae64300c4d98939bf575aab7e-8154efb0c1a64295cf54e00025b4ab09bcd02752&p-dtype=%27String%27
- [ ] http://pandas.pydata.org/speed/pandas/index.html#groupby.GroupByMethods.time_dtype_as_group?commits=9c5165e26260483ae64300c4d98939bf575aab7e-8154efb0c1a64295cf54e00025b4ab09bcd02752&p-method=%27all%27&p-application=%27transformation%27&p-dtype=%27datetime%27
- [ ] http://pandas.pydata.org/speed/pandas/index.html#gil.ParallelDatetimeFields.time_datetime_to_period?commits=9c5165e26260483ae64300c4d98939bf575aab7e-8154efb0c1a64295cf54e00025b4ab09bcd02752

Unfortunately, the benchmark machine was down for ~1 week (we lost power during a storm, and I forgot to turn it back on). The window is https://github.com/pandas-dev/pandas/compare/9c5165e26260483ae64300c4d98939bf575aab7e...8154efb0c1a64295cf54e00025b4ab09bcd02752.

**Comment by TomAugspurger** [comment]
Candidates, based on commit messages

- https://github.com/pandas-dev/pandas/commit/ebe6b9135c1b17f990b9d38dbee5fc07b34ffa85
- ...

**Comment by TomAugspurger** [comment]
Not a blocker for the RC, but is a blocker for the final release I think.

**Comment by mroeschke** [comment]
Given this issue is with an unsupported version of pandas now, going to close.
