### ISSUE TITLE
PERF: asv for import time

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#26663]
Not entirely sure how to do it with asv, but at the command line its just `python3 -X importtime -c "import pandas"`

- [ ] import time with `python3 -X importtime -c "import pandas"`
- [ ] import size with something like `import pandas, psutil; psutil.Process().memory_info()`

**Comment by WillAyd** [comment]
Yea I think this would be a good idea. Maybe create a subprocess in setup and load pandas in the subprocess call

**Comment by jbrockmendel** [comment]
https://github.com/airspeed-velocity/asv/pull/487

**Comment by alimcmaster1** [comment]
Here is something similar numpy did: https://github.com/numpy/numpy/pull/8159/files - do we just want to benchmark `import pandas` or test some sub packages too?

**Comment by WillAyd** [comment]
Makes sense to me. I think we'd take a PR for something like that if you'd like to post one

**Comment by TomAugspurger** [comment]
Ideally, the setup would ensure that matplotlib and numexpr  (really, all our optional deps) aren’t in the Python env running the benchmark.

**Comment by jbrockmendel** [comment]
No opinion on numexpr, but for matplotlib I'd rather it be installed.  I'm pretty sure some effort has been put in to making matplotlib imports lazy.  This would help ensure that we don't accidentally undo that (this was motivated by exactly this happening in statsmodels)

**Comment by TomAugspurger** [comment]
Matplotlib has to be imported by default right now because we register formatters. That’s deprecated, and then we can ensure it’s lazily imported. 

We have a separate CI check ensuring that certain packages aren’t imported with pandas (search for import time)

**Comment by TomAugspurger** [comment]
https://github.com/pandas-dev/pandas/blob/c7748ca057cad4a80a6c4cbf8b49c5d9f3e7ea1c/ci/code_checks.sh#L192

**Comment by jbrockmendel** [comment]
Thanks for pointing that out.  Is there a particular reason that was used instead of the approach here https://github.com/statsmodels/statsmodels/pull/5831 ?

**Comment by TomAugspurger** [comment]
You mean a separate check, not run as part of the pytest test suite? Probably no reason; seems easier to me that it be separate since it isn’t really a traditional unit test.
