### ISSUE TITLE
PERF: use lazy imports on py37 to speed up import

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#26666]
IIUC py37 supports patching of module-level `__getattr__`.  One of the big uses cases for that is lazy imports.  This might be nice to use for some lesser-used modules, e.g. in `io`.

Not sure how much trouble it will be to do this conditionally for py37+ only.

**Comment by WillAyd** [comment]
https://www.python.org/dev/peps/pep-0562/

**Comment by WillAyd** [comment]
Do you have a specific application in mind?

**Comment by jbrockmendel** [comment]
> Do you have a specific application in mind?

Delaying imports of e.g. matplotlib or pandas.io until they are needed.  I'd add pytz (10% of total import time) if it werent needed in the cython code.

**Comment by jbrockmendel** [comment]
Closing, will re-open once we're closer to py37+.  By that time I expect there will be some `six`-like standard way of doing this.
