### ISSUE TITLE
CI: Remove isort from CI dependencies

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#26661]
In #25455 we added `isort` as a dependency to all our builds. Looks like the CI was failing, and adding `isort` fixed the problem. Not sure what the problem is, but `isort` is something we should only have in `environment.yml`, as it's only used in `ci/code_checks.sh` and locally.

We should remove `isort` from all files in `ci/deps/` and if the CI complains, find out what's the problem, and fix it.

**Comment by alimcmaster1** [comment]
Currently taking a look :)
