### ISSUE TITLE
integrate method for Series and DataFrame

### ISSUE THREAD

**Issue by scls19fr** [pandas-dev/pandas#26681]
Hello,

Similar to #26680 when dealing with sensors data such as power meter or flow meter and having such data in a `DataFrame` (or in a `Series`) it can be convenient to easily calculate integral of values ie calculate energy consumption from power usage, volume consumption from flow rate for example.

Maybe `Series` and `DataFrame` could have an `integrate` method.

Similar question have been asked on StackOverflow

https://stackoverflow.com/questions/50239878/pandas-dataframe-column-numerical-integration

Maybe it could be worth to provide a better integration with Scipy and make use of `Scipy.integrate.trapz`.

Kind regards

PS : related issue may be #3759

**Comment by jreback** [comment]
same rationale as here: https://github.com/pandas-dev/pandas/issues/26680#issuecomment-499263027

these are not core to pandas, but could be easily added via another package and hook into the accessor api.
