### ISSUE TITLE
Replace flat columns with hierarchical while merge

### ISSUE THREAD

**Issue by dinya** [pandas-dev/pandas#26699]
Is there is any standard method to replace flat columns with hierarchical while merge the dataframes?

I mean something like:

```python
def columns_as_multiindex(df, inplace=False):
    """Replace flat (:obj:`pandas.Index`) columns with hierarchical (:obj:`pandas.MultiIndex`).

    Parameters
    ----------
    df : pandas.DataFrame
        Dataframe wich contains the columns to be converted to MultiIndex.
    inplace : bool (default False)
        If ``True``, do operation inplace and return ``None``.

    Returns
    -------
    pandas.DataFrame or None
        Returns dataframe with modifed columns or ``None`` (depends on `inplace` parameter value).

    Examples
    --------
    >>> df0 = pd.DataFrame([[1,2], [10, 20], [100, 200]], columns=["A", "B"])
    >>> df0
    ...      A    B
    ... 0    1    2
    ... 1   10   20
    ... 2  100  200

    >>> columns = pd.MultiIndex.from_tuples([("C", "C0"), ("D", "D0")])
    >>> df1 = pd.DataFrame([[1,3], [10, 30], [100, 300]], columns=columns)
    >>> df1
    ...      C    D
    ...     C0   D0
    ... 0    1    3
    ... 1   10   30
    ... 2  100  300

    Merging ``df0`` with ``df1`` returns the dataframe contains tuples in the column names

    >>> df = pd.merge(df0, df1, left_on="A", right_on=[("C", "C0")])
    >>> df
    ...      A    B  (C, C0)  (D, D0)
    ... 0    1    2        1        3
    ... 1   10   20       10       30
    ... 2  100  200      100      300

    It's a bit ugly. Let's beautify the header

    >>> columns_as_multiindex(df)
    >>> df
    ...      A    B    C    D
    ...               C0   D0
    ... 0    1    2    1    3
    ... 1   10   20   10   30
    ... 2  100  200  100  300
    """
    columns = df.columns.tolist()
    columns = [(c,) if isinstance(c, str) or not np.iterable(c) else c for c in columns]
    max_len = max([len(c) for c in columns])
    columns = [tuple(c + ("",) * (max_len - len(c))) for c in columns]
    columns = pd.MultiIndex.from_tuples(columns)
    if inplace:
        df.columns = columns
    else:
        df_new = df.copy()
        df_new.columns = columns
        return df_new
```

**UPD 2019-06-13** A bit more robust function on input data.

**Comment by WillAyd** [comment]
Can you provide sample data frames and the expected result?

**Comment by dinya** [comment]
@WillAyd 

> Can you provide sample data frames and the expected result?

See doctring of ``columns_as_multiindex``, ``Example`` section.

Compare  the output of ``df`` (just after merging) and ``columns_as_multiindex(df)`` (expected).

![screenshot](https://user-images.githubusercontent.com/2182222/59104627-78939080-894b-11e9-8a9e-3e74711e4817.png)

**Comment by WillAyd** [comment]
Any reason you don't just do `df.columns = pd.MultiIndex.from_tuples(df.columns.tolist())`? 

I think this overlaps already with existing functionality some -1 on the request but @toobaz might have some input

**Comment by dinya** [comment]
@WillAyd 

> Any reason you don't just do ``df.columns = pd.MultiIndex.from_tuples(df.columns.tolist())``?

It's not the same as result of ``columns_as_multiindex`` and you still need to modify the index of ``df``:

![screenshot](https://user-images.githubusercontent.com/2182222/59150211-2e88d880-8a39-11e9-8898-2d8887ff69c2.png)

**Comment by WillAyd** [comment]
Thanks for the response. I still don't see this being generally more useful than what is already available so still -1 but let's see what others think

**Comment by dinya** [comment]
Add check for columns names overlapping and optional renaming (something like [``pd.merge(df1, df2, suffixes=...)``](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html))

See example https://gist.github.com/dinya/06e374721993fd387db19ee7f83065a5

**Comment by mroeschke** [comment]
Appears that this suggestion never got any further approval from other core devs. Thanks for the suggestion, but going to close with interest haven gotten stale. Happy to reopen if there's further interest from the core devs and community

**Comment by lruhlen-ripple** [comment]
FWIW, this functionality would be quite helpful to me :-)
