### ISSUE TITLE
Deprecate Series.ftype / DataFrame.ftypes

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#26705]
With the `ftype(s)` property, you could check if data was sparse:

```
In [26]: df = pd.DataFrame({'a': pd.SparseArray([1, np.nan, 1])})

In [27]: df
Out[27]: 
     a
0  1.0
1  NaN
2  1.0

In [28]: df.dtypes
Out[28]: 
a    Sparse[float64, nan]
dtype: object

In [29]: df.ftypes
Out[29]: 
a    float64:sparse
dtype: object
```

But now that the dtype itself is a EA SparseDtype, I don't think those `ftype` and `ftypes` attributes serve any good purpose. So let's deprecate them.

**Comment by jreback** [comment]
this is on my let’s deprecate ticket

**Comment by jorisvandenbossche** [comment]
Yes, but wanted to highlight it specifically given all the sparse deprecations we are doing for 0.25.0, and small separate issues are easier taken up by contributors.

**Comment by jreback** [comment]
totally fine pls link it though

**Comment by ThiviyanThanapalasingam** [comment]
Hi @jreback @jorisvandenbossche,

I was looking for a good first issue to contribute to this project and came across this thread. Would you guys like any help with this issue?

**Comment by simonjayhawkins** [comment]
@ThiviyanThanapalasingam go for it!

**Comment by ThiviyanThanapalasingam** [comment]
`Series.ftype`, `Series.ftypes` and `DataFrame.ftypes` have been deprecated. I have also updated the docstrings for the sphinx documentation and updated the unit tests to test for deprecation warnings when these features are used. Check out pull request #26744. Please let me know know if I have overlooked anything. Any feedback would be appreciated :-)
