### ISSUE TITLE
Broken benchmarks

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#26709]
The benchmarks are currently broken, and are making red the CI of all PRs that modify something in `asv_bench` (we run the CI check for benchmarks when something is modified in that directory).

This has probably been caused by #26225. But it's strange that the CI for that PR wasn't red, since it run the benchmark checks.

This is blocking #26414, #26703. The error can be seen here: https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=12407

```
[ 16.10%] ··· ...ervalIndexMethod.time_intersection_duplicate         1/3 failed
[ 16.10%] ··· ========== ==========
                param1             
              ---------- ----------
                 1000     1.76±0ms 
                100000    73.3±0ms 
               10000000    failed  
              ========== ==========
```

**Comment by TomAugspurger** [comment]
Taking a look now.

**Comment by qwhelan** [comment]
It appears this large `N` never worked. I have a fix that yields a large speedup (`~10x+`) but possibly changes the intent of this benchmark: https://github.com/pandas-dev/pandas/pull/26711
