### ISSUE TITLE
Pandas Bar Plot xlim failure

### ISSUE THREAD

**Issue by renjiege** [pandas-dev/pandas#26719]
#### Code Sample

```python
df['Quarter'] = pd.PeriodIndex(df['date'], freq='Q')
fig, ax = plt.subplots(figsize=(10,5))
df.plot.bar(x='Quarter', y ='ape', ax=ax, xlim=('2015Q1', '2019Q1'), color="tab:green").grid(alpha=.4)
```
#### Problem description

for bar plot, xlim option fails and always gives the same range; line plot works though.

**Comment by TomAugspurger** [comment]
Do you have a reproducible example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by TomAugspurger** [comment]
@renjiege if you can provide a minimal example we'll reopen.
