### ISSUE TITLE
Performance for TimedeltaArray.__iter__ and PeriodArray.__iter__

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#26713]
Right now `DatetimeArray.__iter__` does it's boxing in chunks. We could do something similar for TimedeltaArray and possibly PeriodArray.

**Comment by jbrockmendel** [comment]
There is a `tslibs.timedeltas.ints_to_pytimedelta(arr.asi8, box=True)` that will make this easy to do for Timedelta; nothing analogous for Period
