### ISSUE TITLE
Import pandas is stopping python service

### ISSUE THREAD

**Issue by RamrajSekar** [pandas-dev/pandas#26728]
#### Code Sample, a copy-pastable example if possible
```python
import pandas as pd
```
#### Problem description
I just imported the pandas library which is restarting the shell and throwing an alert pop up stating PYTHON HAS STOPPED WORKING and this is in win 10[64bit]

Version:
C:\>python --version
Python 3.7.0a2

NOTE: I tried with IDLE,IDE and Command prompt all is resulting the same, So kindly help me on this.

Kindly refer the snapshot below,
![image](https://user-images.githubusercontent.com/28296747/59142766-919a5100-89e0-11e9-94ec-cf257b22bd82.png)

**Comment by WillAyd** [comment]
Looks like you are using an alpha version of Python. Please try with a stable release and let us know if you still get it then

**Comment by WillAyd** [comment]
Closing as alpha Python versions are not supported, though as mentioned please reopen if a stable release doesn't fix this
