### ISSUE TITLE
Series.round behavior with ExtensionArrays

### ISSUE THREAD

**Issue by pilkibun** [pandas-dev/pandas#26730]
@TomAugspurger, in your blog post [Moral Philosophy for pandas or: What is .values?](https://tomaugspurger.github.io/pandas-moral-philosophy.html) you wrote

> In pandas 0.24, we'll (hopefully) have a good answer for what series.values is: a NumPy array or an ExtensionArray. For regular data types represented by NumPy, you'll get an ndarray. For extension types (implemented in pandas or elsewhere) you'll get an ExtensionArray. If you're using Series.values, you can rely on the set of methods common to each.

I just ran into an issue because this doesn't happen in some places.

[pint](https://github.com/hgrecco/pint) is a popular package for working with units, useful for engineering/sci calculations. Recently they introduced an EA called [pint-pandas](https://github.com/hgrecco/pint-pandas) for better interaction with pandas,
it's still a little rough, but very promising.

Here's an failure example:
```
In [2]: from pandas import Series 
   ...: import pint
   ...: from chemtools import Ch, UREG as ureg
   ...: from pint import UnitRegistry
   ...: 
   ...: ureg=UnitRegistry()
   ...: grams=ureg.g
   ...: 
   ...: s=Series((1.5*grams,2.5*grams),dtype='pint[g]')
   ...: s.round()
<...>
AttributeError: 'numpy.ndarray' object has no attribute 'rint'
```

The problem is that `Series.round()` calls `com.values_from_object(self)` instead of the EA-aware `self.values`.  
https://github.com/pandas-dev/pandas/blob/cf25c5cd3ab1f647f780167df622c74b737fa8f5/pandas/core/series.py#L2054-L2085

`com.values_from_object(self)` percolates down to ExtensionBlock.to_dense():

https://github.com/pandas-dev/pandas/blob/cf25c5cd3ab1f647f780167df622c74b737fa8f5/pandas/core/internals/blocks.py#L1729-L1730

Which calls `np.asarray(self.values)`, this convert the underlying `PintArray` in to a numpy array with object dtype, which is not numeric, and so numpy complains that `rint`  isn't implemented. If `Series.round()` would invoked `round()` on `self.values` directly, the underlying EA implementation would get a chance to implement a suitable method, or delegate to numpy in an appropriate way.

You may want to make life easier for EA developers, by providing a default implementation for things like round(), I suppose it may work in some cases, but then there still needs to be a way for an EA to provide its own implementation of functions like `round`. Many `Series` methods use `com.values_from_object(self)`, and its the the same problem everywhere.

cc @hgrecco (pint developer)

**Comment by TomAugspurger** [comment]
I think NumPy's new `__array_interface__` provides an elegant solution here. If an EA implements `__array_interface__` then Series.round just needs to call `np.round(self.array)` and things will be fine.

In the meantime, I'm not sure what's best. I'm not sure that adding an `ExtensionArray.round` method is warranted.

**Comment by pilkibun** [comment]
I'm not sure `__array_interface__ ` can solve this problem. Think of PintArray as "tagged" numeric arrays. You can do all the numeric stuff with them, but you have to preserve the tag (unit) information.
For example, we want to have `round: PintArray[grams] -> PintArray[grams]`.

But, afaict `__array_interface__` will always return a numpy array which means we either
- convert to numeric dtype, and lose the unit information
- convert to object dtype, and numpy doesn't provide numeric ops (the current case, since PintArray implements `__array__`.

It looks to me like several (most? all?) the Series/DataFrame numeric ops implementations don't allow for this case. Am I wrong?

Here's the current impl
```
Class Series():
...
def round():
         nv.validate_round(args, kwargs)
        result = com.values_from_object(self).round(decimals) 
        result = self.values.round(decimals)
        result = self._constructor(result, index=self.index).__finalize__(self)
        return result
```

I don't see a way for this code path can ever produce an EA-backed series.

**Comment by TomAugspurger** [comment]
Sorry, I miswrote earlier. I said `__array_interface__` when it should have been `__array_function__`: https://www.numpy.org/neps/nep-0018-array-function-protocol.html

In that case, Series.round simply becomes `return np.round(self.array)`. If the backing array defines `__array_function__` then they get to take control, otherwise NumPy's implementation (including coercing to an ndarray) takes over.

**Comment by pilkibun** [comment]
yeah, that looks like the right solution. Still requires changes on pandas side though, no?

**Comment by TomAugspurger** [comment]
Correct. And that's experimental in NumPy, and it requires work on the part
of the EA author to implement it. This is all very new :)

I'm not sure what a good short-term solution is. Possibly removing the call
to com.values_from_object in Series.round and seeing whether any tests
break?

**Comment by pilkibun** [comment]
I just coded it up, turned on experimental support in numpy 1.16.4 and it works (:balloon:).
`s/com.values_from_object/self.values` Doesn't seem to break any tests.

However, `com.values_from_object` basically just calls `self.get_values()` and the docstring says
```python 
Docstring: Same as values (but handles sparseness conversions); is a view.
```

and yet:
```
In [25]: s.get_values()
Out[25]: array([<Quantity(2.0, 'gram')>, <Quantity(3.0, 'gram')>], dtype=object)

In [26]: s.values
Out[26]: PintArray([2.0 gram, 3.0 gram], dtype='pint[gram]')
```

so maybe the `get_values` impl is out of date after the EA changes and that's needs to be fixed instead of changing  the calling methods?

**Comment by TomAugspurger** [comment]
> so maybe the get_values impl is out of date after the EA changes and needs to be fixed instead of changing the calling methods?

Indeed, @jorisvandenbossche does your recent work on `get_values` affect `Series.round`?

**Comment by jorisvandenbossche** [comment]
I think it is the docstring of `get_values` that is out of date, as it is assumed to always return some numpy array representation of the values.

> does your recent work on get_values affect Series.round?

No, as that is using `com.values_from_object`. My work was to let that behave the same as it does today (it is used in too many places), but to refactor its implementation to no longer rely on `get_values`.

I agree the long term solution is that we want to use the numpy function protocol. In principle, I think we could already switch to `np.round(self.array)` for EAs now, to enable people to experiment with this.

**Comment by pilkibun** [comment]
> I think it is the docstring of get_values that is out of date, as it is assumed to always return some 
> numpy array representation of the values.

I understand it to say that `values` and `get_values` are supposed to be compatible in terms of return type, `get_values` was not updated to handle the new EA, so now they are not compatible, and that's why this bug occurs. 

> No, as that is using `com.values_from_object`. My work was to let that behave the same as it does today 
> (it is used in too many places), but to refactor its implementation to no longer rely on get_values.

But `com.values_from_object` just calls `get_values`. 

`get_values` behavior with EA is just a side-effect because it was implemented before EA existed.
Keeping that behavior after having changed `values` to special-case EAs seems like an odd choice. 
 

So I'm confused. Basically, can you explain what are the different cases handled handled by each
of  `values` vs. `get_values` vs. `com.values_from_object`?

**Comment by jorisvandenbossche** [comment]
The work I have been doing that Tom referenced is about getting rid of (first deprecating) `get_values`, exactly to avoid such confusion .. ;) 
See https://github.com/pandas-dev/pandas/pull/26409

`com.values_from_object` is used internally where we need numpy arrays. 

`get_values` is a confusing mix of behaviour (and also different depending on the calling object (eg Series vs Block)), and moreover unneeded in the public API, so therefore I was trying to deprecate that. A main usage is currently in `com.values_from_object`, so part of the referenced PR is updating `com.values_from_object` to no longer rely on `get_values`.

> get_values was not updated to handle the new EA, so now they are not compatible, and that's why this bug occurs.

The reason of the bug is not necessarily `get_values` not working with EAs (it is doing what it is expected to do, returning a numpy array), but that we simply never checked `round` with EAs, and so that was not updated to work with EAs.

**Comment by pilkibun** [comment]
That makes things clearer, thanks. So I understand `get_values` will eventually disappear.

The `get_values` docstring suggests it handles sparse arrays while  `values` doesn't. Is that still the case?

**Comment by jorisvandenbossche** [comment]
> The get_values docstring suggests it handles sparse arrays while values doesn't. Is that still the case?

Yes, `.values` will return the SparseArray, while `get_values` returns the densified numpy array.

Similarly, for most EAs, `.values` will also return the EA and not a numpy array. But since this is not fully consistent, `.values` is no longer recommended but kept for backwards compatibility.

**Comment by pilkibun** [comment]
wait what. `get_values` is on its way out and `.values` is no longer recommended? what's left?

**Comment by jorisvandenbossche** [comment]
See http://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.24.0.html#whatsnew-0240-values-api, which was kind of the follow-up on the blog post you mentioned in the first post. 

Want an EA -> use `.array`. Want to get a numpy array -> use `np.asarray(..)` or `.to_numpy()`

**Comment by pilkibun** [comment]
> I think we could already switch to np.round(self.array) for EAs now, to enable people to experiment with this.

ok. time for a PR?

**Comment by pilkibun** [comment]
aside, shoyer in https://github.com/numpy/numpy/issues/13759#event-2406615089 pointed out this  [section](https://www.numpy.org/neps/nep-0018-array-function-protocol.html#partial-implementation-of-numpy-s-api) in NEP-18.

Quote:
```
With the current design, classes that implement __array_function__ to overload at least one function
implicitly declare an intent to implement the entire NumPy API. It’s not possible to implement only
np.concatenate() on a type, but fall back to NumPy’s default behavior of casting with np.asarray() 
for all other functions.
```

That's a lot of boilerplate burden on EA developers, which tom mentioned earlier.

**Comment by jorisvandenbossche** [comment]
But I suppose that you can still "fallback" inside `__array_function__` to the numpy implementation by manually doing a `np.asarray` and calling the numpy function on that?

**Comment by TomAugspurger** [comment]
If there's too much boilerplate for EA authors, we could perhaps provide a Mixin class implementing the fallback behavior.

**Comment by pilkibun** [comment]
@jorisvandenbossche, kind of, since you can't always convert your array to  numeric without losing information, so you can do the arithmatic with numpy but then you have to rewrap it possibly on a case-by-case basis. For example in the case of units, `product`, `sum`, and `pow` of an array are all different cases in terms of how the final unit is calculated. And needs to fail sanely with NA. But for most cases, probably not as finicky.

@TomAugspurger, in the case where a generic mixin will do the job, it's probably also the case that
`__array_function__` doesn't need to beimplemented and just providing `__array__` will be sufficient.

Series.count()` needs the same treatment I think. We'll se if the PR passes the tests.

```python
In [14]: import pandas as pd
    ...: from pandas import Series
    ...: import numpy as np
    ...: from pint import UnitRegistry
    ...: 
    ...: ureg=UnitRegistry()
    ...: grams=ureg.g
    ...: s=Series((np.nan,2.75*grams),dtype='pint[g]')

In [15]: s.count()
Out[15]: 2

In [16]: pd.core.series.notna(s.get_values()).sum()
Out[16]: 2

In [17]: pd.core.series.notna(s.array).sum()
Out[17]: 1
```

**Comment by pilkibun** [comment]
I'm missing a few things in the API:
1. a way to ask an EA if it is "numeric" in some sense
2. if yes, a way to ask it for a ndarray of its values with a numeric dtype
3. perhaps a way to find the nearest common ancestor dtype of two EA. numpy will do that for us when we use its functions, but if we want to implement our own implementation that's a common building block you wouldn't want to rewrite from scratch each time.

The problem originally was the call to `np.array(com.get_values)` which ended up generating object arrays, we work around that by using `__array_function__` (which may not be viable in the end) so that we know our own type, but we hit the same issue in  `__array_function__`  when we deal with mixed-dtype cases and encounter an EA of a different type. If the API doesn't provide a way to query that EA about its numeric nature, we have to punt to object again and we have the same problem again.

mixed-dtype EA usage seems like an unusual case, but eventually someone will probably need it,
and I think the EA API should provide the means for it.

**Comment by MichaelTiemannOSC** [comment]
Ugh.  I read through this thread 2x and followed a few of the links.  Am I to understand that the solution is "don't use `round`"?  Or is there a groovy idiomatic way to do so that I've simply missed?

cc @hgrecco (pint developer)
