### ISSUE TITLE
PLOT: Split plotting tests

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#26745]
#26414 splitted the pandas plotting code into two different modules:
- `pandas.plotting`: Generic plotting framework that defined an API (with docs) and is able to plot with a selectable backend (will be selectable with a pandas option)
- `pandas.plotting._matplotlib`: Matplotlib backend

Our tests in `pandas/tests/plotting` are currently testing both together (calling the pandas plotting framework, which will call the matplotlib backend). But ideally we'd like to have two different groups of tests:
- One with the current code but calling the matplotlib backend directly
- A test set of the generic pandas plotting framework, using a mock backend (needs to be implemented)

@jreback let me know if this makes sense to you

**Comment by jorisvandenbossche** [comment]
> One with the current code but calling the matplotlib backend directly

Why should we need to call the matplotlib backend directly instead of keep testing it through the user-facing API?

**Comment by jbrockmendel** [comment]
@datapythonista is this still worth pursuing?

**Comment by datapythonista** [comment]
> @datapythonista is this still worth pursuing?

Probably not, thanks for triagging this. Closing.
