### ISSUE TITLE
clean or remove header format after convert to excel

### ISSUE THREAD

**Issue by yyz20002008** [pandas-dev/pandas#26774]
#### Code Sample, a copy-pastable example if possible

```python
`import pandas as pd
import pandas.io.formats.excel
mypath = <Filepath>
#print(mypath)
from os import listdir
from os.path import isfile, join
#print (listdir(mypath))
textfiles = [ join(mypath,f) for f in listdir(mypath) if '.TXT' in  f]

print(textfiles)

for textfile in textfiles:
    df = pd.read_csv(textfile,sep='|', dtype=str)
    #df.dtypes
    #df.ROW = df.ROW.astype(str)
    df.io.formats.excel.header_style = None
    filename=textfile.split('.')[0]
    df.to_excel(filename+'.xlsx', 'Sheet1', index=False) # if your file is tab delimited
    
    `


```
#### Problem description

'df.io.formats.excel.header_style = None' doesn't work any more. 

#### Expected Output
How can I clean header format after convert to excel.
#### Output of ``pd.show_versions()``
Currently header is bold and has a border.

**Comment by yyz20002008** [comment]
I read #22773 and #25398.It seems like no good solution yet

**Comment by WillAyd** [comment]
This is a dup of the other issue you commented on. Would need a community PR to make this happen

**Comment by yyz20002008** [comment]
@WillAyd does pandas have this functionality right now?
