### ISSUE TITLE
DOC: Fix doc warning "Code input with no code"

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#26788]
xref #24173

When building the documentation `./doc/make.py html`, among other warnings we find the next:

```
/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/IPython/sphinxext/ipython_directive.py:1020: UserWarning: Code input with no code at /home/travis/build/pandas-dev/pandas/doc/source/user_guide/advanced.rst, line 724
  warnings.warn(message)
/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/IPython/sphinxext/ipython_directive.py:1020: UserWarning: Code input with no code at /home/travis/build/pandas-dev/pandas/doc/source/user_guide/cookbook.rst, line 1300
  warnings.warn(message)
```

All code blocks seem to have code, so it's not obvious why we get the issues. Also, the reported lines aren't probably correct. We should research why this is failing, and fix the problem.

**Comment by ThiviyanThanapalasingam** [comment]
I'm on it 👍

**Comment by jorisvandenbossche** [comment]
> Also, the reported lines aren't probably correct. We should research why this is failing, and fix the problem.

You need to substract 15, then the number matches the line numbers in the rst files. That's because of the header that gets injected (something I mentioned at that point as annoying for the header approach, but I don't really have a good alternative)

**Comment by TomAugspurger** [comment]
I noticed a couple had `%timeit`, not sure about all of them.

In a tiny example, `%timeit` worked OK (but maybe that was at the top of the input).

**Comment by jorisvandenbossche** [comment]
- In case of the advanced.rst, it is due to a `%timeit` I think. The output in the online docs stops after the first block with timeit calls.
- In case of the cookbook one, it is a code block with a function, where the function is cutted after a first blank line within the function definition (compare http://pandas-docs.github.io/pandas-docs-travis/user_guide/cookbook.html#correlation with the actual rst source)

**Comment by TomAugspurger** [comment]
I think a custom directive may be able to handle the header throwing off of
line numbers, but that's quite a bit more complex.

**Comment by jorisvandenbossche** [comment]
BTW, the issue for the problem with the IPython directive is here: https://github.com/ipython/ipython/issues/11362
