### ISSUE TITLE
Explanation of assign by list to filtered DataFrame

### ISSUE THREAD

**Issue by jesrael** [pandas-dev/pandas#26783]
Based by [this question](https://stackoverflow.com/q/56544290/2901002):

Why if assign scalar and Series in list, error is raised:

    wert = 2.5
    df = pd.DataFrame([['Test', 12, None, None], ['Test2', 15, None, None]], columns=['A','B','C','D'])
    
    mask = (df['A'] == 'Test2')
    df.loc[mask, ['C', 'D']] = [1, df['B'] * wert]

>ValueError: cannot set using a list-like indexer with a different length than the value

But if filter in both side it working nice?

    mask = (df['A'] == 'Test')
    df.loc[mask, ['C', 'D']] = [1, df.loc[mask, 'B'] * wert]
    print (df)
           A   B     C     D
    0   Test  12     1    30
    1  Test2  15  None  None

Error is correct? 

Thank you.

**Comment by mroeschke** [comment]
`df.loc[mask, ['C', 'D']] = ...` is setting the value of one row. `df['B']` has length 2 so it will try to set it across 2 rows.

```
In [5]: df.loc[mask, 'B']
Out[5]:
0    12
Name: B, dtype: int64

In [6]: df['B']
Out[6]:
0    12
1    15
Name: B, dtype: int64
```
