### ISSUE TITLE
DOC: MultiIndex from levels and codes example fails

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#26789]
In the whatsnews page, the example for the new "MultiIndex constructed from levels and codes" is failing:

https://pandas-docs.github.io/pandas-docs-travis/whatsnew/v0.25.0.html#multiindex-constructed-from-levels-and-codes

The example was added in #26408, @jiangyue12392 can you have a look please?

**Comment by jorisvandenbossche** [comment]
This is already fixed in https://github.com/pandas-dev/pandas/pull/26780
