### ISSUE TITLE
Improvement: DataFrame.to_html() to create hyperlinks

### ISSUE THREAD

**Issue by michaelaye** [pandas-dev/pandas#2679]
When the data value is a string that represents an URL, have DataFrame.to_html() create hyperlinks out of them in the resulting html file.

**Comment by tdas14** [comment]
Working on this one!

**Comment by jdejoode** [comment]
Any new on this issue? Has this been implemented?

**Comment by xuyannus** [comment]
Any new on this issue? Has this been implemented?
