### ISSUE TITLE
Inconsistency between pd.Categorical(x) and x.astype('category')

### ISSUE THREAD

**Issue by thequackdaddy** [pandas-dev/pandas#26801]
#### Code Sample, a copy-pastable example if possible

So in pandas 0.24.2, this gave you the identical response...

```python
ipomPython 3.7.3 (default, Mar 27 2019, 16:54:48)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pandas as pd

In [2]: x = pd.Series(['a', 'b', 'c'], name='foo')

In [3]: pd.get_dummies(x.astype('category'))
Out[3]:
   a  b  c
0  1  0  0
1  0  1  0
2  0  0  1

In [4]: pd.get_dummies(pd.Categorical(x))
Out[4]:
   a  b  c
0  1  0  0
1  0  1  0
2  0  0  1

In [5]: pd.__version__
Out[5]: '0.24.2'
```

In pandas 0.25.0 dev, I see some differences. 

```python
Python 3.7.3 (default, Mar 27 2019, 16:54:48)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pandas as pd

In [2]: x = pd.Series(['a', 'b', 'c'], name='foo')

In [3]: pd.get_dummies(x.astype('category'))
Out[3]:
foo  a  b  c
0    1  0  0
1    0  1  0
2    0  0  1

In [4]: pd.get_dummies(pd.Categorical(x))
Out[4]:
   a  b  c
0  1  0  0
1  0  1  0
2  0  0  1

In [5]: pd.__version__
Out[5]: '0.25.0.dev0+718.gdeffee680'
```

***Notice that the `astype` method now results in the index having a name. That didn't happen before.***

#### Problem description

So in 0.24.2, these 2 ways of converting a series of strings to categoricals to a dummies resulted in the same answer. 

It now appears that they are different with one having a named index and the other not.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

In [6]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Darwin
OS-release: 18.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.25.0.dev0+718.gdeffee680
pytest: 4.5.0
pip: 19.1.1
setuptools: 41.0.1
Cython: 0.29.8
numpy: 1.16.4
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.5.0
sphinx: 2.1.0
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.1.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: 4.3.3
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by TomAugspurger** [comment]
IIUC, pandas 0.24.2 incorrectly dropped the Series name in `get_dummies`. That's been fixed.

`pd.Categorical(Series)` necessarily drops the series name, since Categoricals don't have names.

**Comment by thequackdaddy** [comment]
Thanks! I couldn’t find a PR/bug fix with that, but wanted to make sure that was intentional.
