### ISSUE TITLE
Multiplying nd.array by series returns incorrect result in pandas 0.23.0-0.23.4 (but is fixed in 0.24)

### ISSUE THREAD

**Issue by dburkhardt** [pandas-dev/pandas#26812]
#### Code Sample, a copy-pastable example if possible

```python
In [1]: import numpy as np
   ...: import pandas as pd
   ...:
   ...: mat = np.random.random(size = (100,100))
   ...: arr = np.random.random(size=100)
   ...:
   ...: df = pd.DataFrame(mat)
   ...: ser = pd.Series(arr)
   ...:
   ...: print((mat @ arr)[:5])
   ...: print((mat @ ser)[:5])
   ...: print((df @ ser).values[:5])
   ...:
   ...: print(np.__version__)
   ...: print(pd.__version__)
[25.58954419 27.14049632 29.35058172 25.60100699 28.81915819]
[25.23415259 27.21156925 25.54180341 24.80747474 27.19878459] # !!!!!!!
[25.58954419 27.14049632 29.35058172 25.60100699 28.81915819]
1.16.4
0.23.4
```

#### Problem description

I'm not sure why this happens, but if you multiply an nd.array by a pd.Series, you get the wrong result returned in pandas `0.23.0 - 0.23.4`. It fails silently, which is *bad*. Even throwing a warning when this happens for `0.23` would be useful, because it takes some packages a while to get up to date with the major API changes in 0.24.

The problem no longer occurs with an upgrade to 0.24

I have tried this with numpy versions as far back at `1.15.0` and all fail in this manner. I have reproduced on Linux and MacOS machines.

Although this is fixed in an update, the silent return of a numerically incorrect result feels like it should be addressed.

#### Expected Output

The correct result.

#### Output of ``pd.show_versions()``
This is for the Macbook Pro, although error still occurs on Linux.
<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Darwin
OS-release: 18.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: None
pip: 19.0.3
setuptools: 40.8.0
Cython: 0.29.2
numpy: 1.15.0
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 6.1.0
sphinx: 1.8.5
patsy: None
dateutil: 2.6.0
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: 2.6.4
feather: None
matplotlib: 3.0.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by scottgigante** [comment]
A bump on this - because of many breaking changes in 0.24, some people (like me!) are yet to upgrade code bases to be compatible and as such are still running 0.23. It would be good to get a backport of the fix on this to an 0.23.4.post1 or a 0.23.5 if possible.

**Comment by TomAugspurger** [comment]
We typically don't do bugfix releases like this. Do you know what commit
fixed things? Perhaps you can apply that commit locally?

**Comment by scottgigante** [comment]
Looks like it might be https://github.com/pandas-dev/pandas/commit/7d8626dfabef595245af44bf74d329f251ce42ca . I'll give that a go and report back for anyone else hitting the same issue.

**Comment by scottgigante** [comment]
That was it. Here's a functional monkey patch for anyone interested:

```
import numpy as np
import pandas as pd

def __rmatmul__(self, other):
    """ Matrix multiplication using binary `@` operator in Python>=3.5 """
    return self.dot(np.transpose(other))

pd.core.series.Series.__rmatmul__ = __rmatmul__
```

**Comment by jreback** [comment]
thanks @scottgigante 

0.23.x (and 0.24.x) have seen the final releases
