### ISSUE TITLE
Unreachable statement found by LGTM.com

### ISSUE THREAD

**Issue by AlexTereshenkov** [pandas-dev/pandas#26828]
I see an issue that was found by LGTM.com:

https://lgtm.com/projects/g/pandas-dev/pandas/snapshot/fe32cc08cf2e4dbdfa4aad33f3a74fada201600f/files/scripts/merge-pr.py?sort=name&dir=ASC&mode=heatmap#L54

The `merge-pr` utility script, https://github.com/pandas-dev/pandas/blob/429078b01af47b356084c1da270b5b275fbf50f4/scripts/merge-pr.py, has `auth_required` variable. My understanding that unless someone edits the source code before running the script, the GitHub authentication will never happen as `auth_required` will always be `False`. Am I wrong?

https://github.com/pandas-dev/pandas/blob/429078b01af47b356084c1da270b5b275fbf50f4/scripts/merge-pr.py#L51-L55

One could perhaps add the `auth_required` as a parameter to a script (either with plain `sys.argv` or using fancier `argparse`) so that one could call the script picking how the authorization should occur instead of editing the source code file if this is what people do.

**Comment by jreback** [comment]
this is a rarely used committee only script can ignore it
