### ISSUE TITLE
TypeError while put df with single level multiindex  into HDFStore

### ISSUE THREAD

**Issue by BeforeFlight** [pandas-dev/pandas#26821]
```python
df = pd.DataFrame([1,2,3],
                  pd.MultiIndex.from_arrays([range(3)]))
with pd.HDFStore('test.h5') as store:
    store.put('df', df, 't')
```
```python
TypeError                                 Traceback (most recent call last)
<ipython-input-46-1057478f5fa5> in <module>
      2                   pd.MultiIndex.from_arrays([[1,2,3]]))
      3 with pd.HDFStore('test.h5') as store:
----> 4     store.put('df', df, 't')

~/Coding/Python/_venvs_/main/lib/python3.7/site-packages/pandas/io/pytables.py in put(self, key, value, format, append, **kwargs)
    887             format = get_option("io.hdf.default_format") or 'fixed'
    888         kwargs = self._validate_format(format, kwargs)
--> 889         self._write_to_group(key, value, append=append, **kwargs)
    890 
    891     def remove(self, key, where=None, start=None, stop=None):

~/Coding/Python/_venvs_/main/lib/python3.7/site-packages/pandas/io/pytables.py in _write_to_group(self, key, value, format, index, append, complib, encoding, **kwargs)
   1413 
   1414         # write the object
-> 1415         s.write(obj=value, append=append, complib=complib, **kwargs)
   1416 
   1417         if s.is_table and index:

~/Coding/Python/_venvs_/main/lib/python3.7/site-packages/pandas/io/pytables.py in write(self, obj, axes, append, complib, complevel, fletcher32, min_itemsize, chunksize, expectedrows, dropna, **kwargs)
   4015         self.create_axes(axes=axes, obj=obj, validate=append,
   4016                          min_itemsize=min_itemsize,
-> 4017                          **kwargs)
   4018 
   4019         for a in self.axes:

~/Coding/Python/_venvs_/main/lib/python3.7/site-packages/pandas/io/pytables.py in create_axes(self, axes, obj, validate, nan_rep, data_columns, min_itemsize, **kwargs)
   3558                 name = obj._AXIS_NAMES[i]
   3559                 index_axes_map[i] = _convert_index(
-> 3560                     a, self.encoding, self.errors, self.format_type
   3561                 ).set_name(name).set_axis(i)
   3562             else:

~/Coding/Python/_venvs_/main/lib/python3.7/site-packages/pandas/io/pytables.py in _convert_index(index, encoding, errors, format_type)
   4552 
   4553     if isinstance(index, MultiIndex):
-> 4554         raise TypeError('MultiIndex not supported here!')
   4555 
   4556     inferred_type = lib.infer_dtype(index, skipna=False)

TypeError: MultiIndex not supported here!
```
Same error with `.from_product()` and `.from_tuples`. It is unexpected because at the same 2-level indexes (as example) works:
```python
df = pd.DataFrame([1,2,3],
                  pd.MultiIndex.from_arrays([range(3), range(3)]))
with pd.HDFStore('test.h5') as store:
    store.put('df', df, 't')
```
Doesn't produce any error.

Suggestion: it rather not a problem of `HDFStore` but `.from_arrays` `.from_product`, `.from_tuples` with single array in input should produce simple index not multiindex:
```python
type(pd.MultiIndex.from_arrays([[1,2,3]]))
```
```
pandas.core.indexes.multi.MultiIndex
```

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Linux
OS-release: 5.0.0-16-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 4.5.0
pip: 19.1.1
setuptools: 41.0.1
Cython: 0.29.7
numpy: 1.16.4
scipy: 1.2.1
pyarrow: None
xarray: 0.12.1
IPython: 7.2.0
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: 3.5.1
numexpr: 2.6.9
feather: None
matplotlib: 3.0.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by jreback** [comment]
single level multi indexes have very little support generally

closing as wont fix (hence the error message)

**Comment by BeforeFlight** [comment]
But why not just set single level multiindex into plain index by default (my suggestion above)? I.e. avoid even possibility of having them? For example as here:
```python
pd.MultiIndex.from_arrays([[1,2,3],[1,2,3]]).droplevel(0)
```
Returns `Int64Index` directly
```python
Int64Index([1, 2, 3], dtype='int64')
```

**Comment by TomAugspurger** [comment]
I don't think we should silently convert between 1-level MI to a regular
index, either when writing or in from_arrays, etc. They're different enough
that doing things silently is likely to cause issues.

**Comment by BeforeFlight** [comment]
> I don't think we should silently convert between 1-level MI to a regular index

But it had been already done in `.droplevel` for example. And seems like had not produced any issues.

#### Why bother

There are 2 points of view - users and programmers. 
- For users 1-level MI (MI_1) are useless - everything may be done with regular index (RI). Besides MI_1 takes more `RAM` and is just less comfortable and well-known as RI. 
- For developers MI_1 is just a bit more overhead and more cases should be taken into account in each function with indexes (like initial topic of this issue). 

So if this is correct - only benefits from both sides. But should be noted that for users benefits rather not consequential (I don't think someone really using MI_1 at all). As for programmers - this is for one to decide. 
So the first thing here - _are this little benefits enough for change something_?

#### Issues
> They're different enough that doing things silently is likely to cause issues.

As all existed functions that _recieves_ indexes as input should be written first for RI and only than for MI (1-level, or more), correct me if I wrong here. Other words they wouldn't fail if instead of df with MI_1 input becomes df with RI. Also there is no need to remove or amend MI_1 checking (whether it raises error like in current issue, or somehow process it) or even do `conversions to RI silently`. This functions should only work with RI. Changes in functions that _produce_ indexes are enough. So I think here shouldn't be any issues.

#### Changes

My suggestion is only about acquiring MI_1 somehow. I.e. form instantiating MI `pd.MultiIndex.from_*()`,  `pd.MultiIndex()`, or from other functions like `df.set_index()`, `pd.MultiIndex.droplevel()` and maybe `pd.MultiIndex.remove_unused_levels()` but I haven't tested it (in fact there may be others way to construct MI_1 but I can't devise any for now). `.droplevel` and `.set_index` seem like already satisfied this - one will receive RI not MI_1. As for changing functions that still produces MI_1 - it may not be done silently, the warning that RI instead of MI_1 has been constructed may be raised. And corresponding examples in documentation added.


P.s.: as for me - 'why bother' section is the main point here. Honestly I don't think MI_1 infers a lot, but I don't know internals much. Maybe only from developers point of view (again current issue is example - it was the point prompted me to start this topic). So if it not big deal here - easier to leave things as is.
