### ISSUE TITLE
requirements-dev.txt: "Could not find a version that satisfies the requirement pyqt"

### ISSUE THREAD

**Issue by jgehrcke** [pandas-dev/pandas#26838]
I followed the contributors guide and set up the dev environment without anaconda. Generally works, except for a small problem in

```
python -m pip install -r requirements-dev.txt
```
which fails with
```
Could not find a version that satisfies the requirement pyqt
```

`pyqt` is not known on PyPI and I resolved the problem by replacing it with `pyqt5`, i.e. with the following patch:

```
From a284ac89a43237784d663b2a475eead953e8a64d Mon Sep 17 00:00:00 2001
From: Jan-Philip Gehrcke <jgehrcke@googlemail.com>
Date: Wed, 12 Jun 2019 20:04:06 +0200
Subject: [PATCH] BUG: requirements-dev: Could not find ... pyqt

As of today 'pyqt' is not a valid PyPI project.

This results in the error message

    Could not find a version that satisfies the requirement pyqt

when running

    python -m pip install -r requirements-dev.txt

from the contributors guide.
---
 requirements-dev.txt | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/requirements-dev.txt b/requirements-dev.txt
index 46e857f2e9e..73b591ce8f6 100644
--- a/requirements-dev.txt
+++ b/requirements-dev.txt
@@ -44,7 +44,7 @@ html5lib
 lxml
 openpyxl
 pyarrow>=0.9.0
-pyqt
+pyqt5
 tables>=3.4.2
 python-snappy
 s3fs
@@ -52,4 +52,4 @@ sqlalchemy
 xarray
 xlrd
 xlsxwriter
-xlwt
\ No newline at end of file
+xlwt
```

But that does not pass CI because of
```
requirements-dev.txt(,): error : `requirements-dev.txt` has to be generated with `ci/../scripts/generate_pip_deps_from_conda.py` after `environment.yml` is modified.
```

From here I am "giving up" but I would at least like to leave this report.

**Comment by jgehrcke** [comment]
(seen in https://github.com/pandas-dev/pandas/pull/26818).

**Comment by dhirensr** [comment]
@jgehrcke : We can either put pyqt5 package in the requirement.txt but it's supported only in python3 .
as stated here https://github.com/pypa/pip/issues/5014 ,pyqt for python2 needs to compiled manually.
what are your suggestions?

**Comment by TomAugspurger** [comment]
We're python3 only now.

**Comment by TomAugspurger** [comment]
What's bringing in the qt dependency? The clipboard tests?

**Comment by dhirensr** [comment]
yup and in this commit https://github.com/jgehrcke/pandas/commit/c3b5a24607754c34d2f1d4d61e2a485f51eb3c22 pyqt5 is misspelled and maybe they rolledback due to that reason. 
it can be added as PyQt5 in the list and then it works

**Comment by jgehrcke** [comment]
>  in this commit jgehrcke@c3b5a24 pyqt5 is misspelled and maybe they rolledback due to that reason.


@dhirensr in my patch shown in _this_ PR's PR description (first comment above) you can see:
```
-pyqt
+pyqt5
```
What's misspelled here? Mhm. 

As I wrote above this breaks the pandas CI with

```
requirements-dev.txt(,): error : `requirements-dev.txt` has to be generated with `ci/../scripts/generate_pip_deps_from_conda.py` after `environment.yml` is modified.
```
which, I suppose, can be fixed easily -- it just wasn't my priority, and instead I opened this issue.

**Comment by dhirensr** [comment]
@jgehrcke : i mean it should be PyQt5 and not pyqt5 anyways.Note p and q are capital

**Comment by TomAugspurger** [comment]
capitalization shouldn't matter for pip. pip will normalize them.

The TODO for this issue is to

1. Find out what the PyPI package name for Conda's pyqt is (probably https://pypi.org/project/PyQt5/)
2. update `generate_pip_deps_from_conda.py` to map `pyqt` to `pyqt5`. See `pytables` / `tables`.
