### ISSUE TITLE
BUG: Series.Count() miscounts NA values in ExtensionArrays

### ISSUE THREAD

**Issue by pilkibun** [pandas-dev/pandas#26835]
#### Code Sample, a copy-pastable example if possible

```python
In [9]: import numpy as np
   ...: import pandas as np
   ...: from pandas.tests.extension.decimal.array import to_decimal
   ...: ser = pd.Series(to_decimal([1,2,3]))
   ...: ser[0]=np.nan
   ...: ser.count()
3
```

**Comment by TomAugspurger** [comment]
Should be able to change the values_from_object to `self.notna().sum()`.
Interested in making a PR?

**Comment by pilkibun** [comment]
already have one lined up, just opened this for a whatsnew reference. we mentioned this in #26730
