### ISSUE TITLE
Segfault when creating DataFrame from tuple

### ISSUE THREAD

**Issue by arpheno** [pandas-dev/pandas#26847]
```python
import pandas as pd

meta = pd.DataFrame(([0],), columns=['status', ])
```
#### Problem description

Not sure what the desired behaviour is in this case but above code throws a
``` 
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```
which is not very user friendly
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None

pandas: 0.24.2
pytest: 4.4.0
pip: 19.0.3
setuptools: 39.1.0
Cython: 0.29.7
numpy: 1.16.1
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.4.0
sphinx: None
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: 0.2.0
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

Python 3.7.3

MAC OS Mojave 10.14.5 (18F132)

**Comment by TomAugspurger** [comment]
This was fixed on master a little while back

```
In [1]: import pandas as pd
meta = pd.DataFrame(([0],), columns=['status', ])

In [2]: meta = pd.DataFrame(([0],), columns=['status', ])
```

we'll have a release before too long.
