### ISSUE TITLE
CI/TST: flaky sorting test on Windows

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#26842]
Regularly see a failure on one of the Windows builds on Azure:

```
Worker 'gw0' crashed while running 'pandas/tests/test_sorting.py::TestSafeSort::test_labels_out_of_bound[-1]'
```

Eg https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=12703&view=logs or https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=12839&view=logs&jobId=077026cf-93c0-54aa-45e0-9996ba75f6f7

**Comment by mroeschke** [comment]
Doesn't appear we have `TestSafeSort::test_labels_out_of_bound` anymore. Closing, but can reopen if this test was moved/refactored somewhere
