### ISSUE TITLE
DOC: errors in documentation > Tutorial > IO Tools > CSV >skiprows

### ISSUE THREAD

**Issue by SonoDavid** [pandas-dev/pandas#26844]
#### Original code in documentation now
```python
data = ('col1,col2,col3\n'
   ...:         'a,b,1\n'
   ...:         'a,b,2\n'
   ...:         'c,d,3')
   ...: 
```

### Code that should be added
```python
data = ''.join(data)

```
#### Explanation
In the tutorial, I found that the code doesn't work in a python terminal. A StringIO object expects to receive one string only as an input. This is why i would add the join operation in the middle (for clearness, as one can also just type one string).
Found this in https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html .

**Comment by WillAyd** [comment]
This is a string with implicit continuation so the join shouldn't do anything. Did this change something for you?

**Comment by SonoDavid** [comment]
I thought the first was a tuple of strings, and the second command fixed that. So it is not a tuple?

**Comment by SonoDavid** [comment]
I was able to read in the string into the StringIO object.

**Comment by WillAyd** [comment]
Great!
