### ISSUE TITLE
values.tolist() inconsistend datetime output depending on number of columns in dataframe

### ISSUE THREAD

**Issue by datatravelgit** [pandas-dev/pandas#26851]
#### Code demonstrating different tolist outputs
The following code demonstrate that a **values.tolist()** function return a different output if a dataframe has a single datetime column or more than one column 

```
import pandas as pd
df = pd.DataFrame({'dt': [pd.datetime(2019, 1, 1), pd.datetime(2019, 1, 2)], 'value': [1, 2]})

df
Out[8]: 
          dt  value
0 2019-01-01      1
1 2019-01-02      2

df.values.tolist()
[[Timestamp('2019-01-01 00:00:00'), 1], [Timestamp('2019-01-02 00:00:00'), 2]]
df[['dt', 'value']].values.tolist()
[[Timestamp('2019-01-01 00:00:00'), 1], [Timestamp('2019-01-02 00:00:00'), 2]]

df[['dt']].values.tolist()
[[1546300800000000000], [1546387200000000000]]
df['dt'].values.tolist()
[1546300800000000000, 1546387200000000000]
```

#### Problem description
The values.tolist() should be consistent regardless of the number of columns selected. 

#### Expected Output

```
df[['dt']].values.tolist()
[[Timestamp('2019-01-01 00:00:00')], [Timestamp('2019-01-02 00:00:00')]]
df['dt'].values.tolist()
[Timestamp('2019-01-01 00:00:00')], [Timestamp('2019-01-02 00:00:00')]
```

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

pd.show_versions()
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.24.1
pytest: 4.3.0
pip: 10.0.1
setuptools: 39.1.0
Cython: None
numpy: 1.16.2
scipy: 1.2.1
pyarrow: None
xarray: 0.12.1
IPython: 7.5.0
sphinx: None
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.3
openpyxl: None
xlrd: 1.2.0
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by simonjayhawkins** [comment]
@datatravelgit thanks for the report.

the `.tolist` method is a numpy method.

the pandas operations gives

```python
>>> import pandas as pd
>>> df = pd.DataFrame({'dt': [pd.datetime(2019, 1, 1), pd.datetime(2019, 1, 2)], 'value': [1, 2]})
>>> df[['dt', 'value']].values
array([[Timestamp('2019-01-01 00:00:00'), 1],
       [Timestamp('2019-01-02 00:00:00'), 2]], dtype=object)
>>> df['dt'].values
array(['2019-01-01T00:00:00.000000000', '2019-01-02T00:00:00.000000000'],
      dtype='datetime64[ns]')
>>>
```

the numpy array is object dtype with the mixed DataFrame and datetime64 for the single dtype.

This I believe is the correct behaviour from pandas.

**Comment by WillAyd** [comment]
Note that tolist is a red herring here - it's really the ambiguity of `.values` that makes this messy.

You can read more about this on the v0.24 whatsnew:

http://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.24.0.html#accessing-the-values-in-a-series-or-index

Or @TomAugspurger has a great writeup of it:

https://tomaugspurger.github.io/pandas-moral-philosophy.html
