### ISSUE TITLE
possible error in documentation

### ISSUE THREAD

**Issue by karpanGit** [pandas-dev/pandas#26865]
The page

https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html#string-regular-expression-replacement

seems to have an example that can be improved. The page lists

```python
df.replace([r'\.', r'(a)'], ['dot', '\1stuff'], regex=True)
```
as an example. However '\1' is ignored because the replacement regex is not a raw string. I think what you mean is likely

```python
df.replace([r'\.', r'(a)'], ['dot', r'\1stuff'], regex=True)
```

if my understanding is correct please consider updating the page.

Regards,

Panos Karamertzanis

**Comment by topper-123** [comment]
Thanks.. You are probably right (don`t have the computer right here to double check). A contribution on this would be welcomed.

**Comment by Kischy** [comment]
From what I tested the line should be
`df.replace([r'\.', r'(a)'], ['dot', 'stuff'], regex=True)`

Only then I get the output the documentation requires:

`import numpy as np
import pandas as pd


#pd.show_versions()


d = {'a': list(range(4)), 'b': list('ab..'), 'c': ['a', 'b', np.nan, 'd']}
df = pd.DataFrame(d)

print(df)
print("-------------")
print(df.replace([r'\.', r'(a)'], ['dot', 'stuff'], regex=True))
`

**Comment by topper-123** [comment]
Both versions work, but the original example was meant to show a regex -> regex grouped replacement, so if you just make the string a raw string as you originally suggested, that will fix the error.

**Comment by Kischy** [comment]
If i do it as originally sugested, than the output is

Output:
```
df.replace([r'\.', r'(a)'], ['dot', r'\1stuff'], regex=True)

Code: 
```python

d = {'a': list(range(4)), 'b': list('ab..'), 'c': ['a', 'b', np.nan, 'd']}
df = pd.DataFrame(d)

print(df)
print("-------------")
print(df.replace([r'\.', r'(a)'], ['dot', r'\1stuff'], regex=True))

**Comment by karpanGit** [comment]
In my view the example intends to demonstrate the regex -> regex transformation. The original dataframe is

```python
d = {'a': list(range(4)), 'b': list('ab..'), 'c': ['a', 'b', np.nan, 'd']}
df = pd.DataFrame(d)
```

i.e. the original data frame is

   a  b    c
0  0  a    a
1  1  b    b
2  2  .  NaN
3  3  .    d

with the *intended* example

```python
df.replace([r'\.', r'(a)'], ['dot', r'\1stuff'], regex=True)
```

we would like to replace '.' with 'dot' and also replace 'a' with 'astuff'. Indeed, the above code does exactly this and yields:

   a       b       c
0  0  astuff  astuff
1  1       b       b
2  2     dot     NaN
3  3     dot       d

that is what the example intends to show.

**Comment by topper-123** [comment]
Agree with @karpanGit on the example's intention.

Having said that, the used strings have no meaning, it you want to find an example where the strings/regex operation give better meaning, that could help people understand the example better.

**Comment by karpanGit** [comment]
I agree with you @topper-123.

One naive question: how does it work with improving the documentation? Are users like myself supposed to make concrete proposals or only report observations?

Many thanks and apologies for my ignorance on how things work.

**Comment by topper-123** [comment]
If you asking specifically about the process on how an issue is resolved in pandas, then it's all on volunteer basis, and no one is obliged to fix a bug that you've reported. So in practice the best way to get things fixed is to submit a pull request yourself :-). And contributions are always welcome, as I mentioned.

**Comment by Kischy** [comment]
Okay, if that is intended, than the correct line (without giving it more meaning) is
`print(df.replace([r'\.', r'(a)'], ['dot', r'\1stuff'], regex=True))`

**Comment by topper-123** [comment]
Yes, that`s right.

**Comment by Kischy** [comment]
Perfect, is the pull request correct the way I did it?

**Comment by topper-123** [comment]
Yes.
