### ISSUE TITLE
REF: avoid using `concat` in __repr__

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#26863]
ATM `DataFrame.__repr__` takes a path through `io.formats.format.DataFrameFormatter._chk_truncate` that can call `core.reshape.concat.concat`.  Similar for `Series.__repr__`. It would be really nice if we could avoid that and find a simpler way to do this.

**Comment by jorisvandenbossche** [comment]
Can you explain a bit more why you think this is bad?

**Comment by jbrockmendel** [comment]
> Can you explain a bit more why you think this is bad?

In the motivating example, in a WIP branch I managed to screw up `DataFrame.__repr__` and debugging it was made more complicated by the use of concat.

My intuition is that concat is overkill for this particular usage and we can simplify the dependency structure here.

**Comment by jorisvandenbossche** [comment]
I am not sure that is desirable / possible to avoid in practice. The concat ensures that the values above and below the truncation are formatted together, which is important for a consistent formatting (I remember bugs about this). 
Of course you could also concat on the array level and not series/dataframe level, but not sure what the advantage of that would be.

**Comment by jreback** [comment]
you might be able to use an iloc /
take here instead (maybe) rather than concat

**Comment by jbrockmendel** [comment]
I trust Joris if he says this is needed; closing.  @jorisvandenbossche could use your input on #26864.
