### ISSUE TITLE
DOC: Reference to type 'pd_table' in IO Tools User Guide

### ISSUE THREAD

**Issue by oguzhanogreden** [pandas-dev/pandas#26868]
Insertion Method section of the reference refers to "pd_table" in the function signature. This is the only place it is used in the whole documentation. Search engines results for "pd_table" are mostly examples where it's used to refer to pd.DataFrame, so it's rather confusing.

Not sure what's the best way to make this clear but the signature should refer to `pandas.io.SQLTable()`.

This was added in #21401. I came across this while working on #26795.

**Comment by WillAyd** [comment]
Great research into this! I think this is where annotations will make things more clear though; if you add annotation for pd_table to be a SQLTable I think that should help a lot - did you have something else in mind?

**Comment by oguzhanogreden** [comment]
Thanks! 

That seems to cause a circular import problem. See tests of #26795 and my comment [here](https://github.com/pandas-dev/pandas/pull/26795#issuecomment-502364672). I may be missing an obvious solution there...
