### ISSUE TITLE
STY: rename `filter` kwarg in `replace` methods

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#26873]
Overlaps with builtin `filter`.

Could use e.g. https://pypi.org/project/flake8-builtins/ to check for other cases like this, xref #22122

**Comment by topper-123** [comment]
I don't see that kwarg in e.g. ``DataFrame.replace``. Could you be more specific where you see this.

**Comment by jbrockmendel** [comment]
Block.replace, Block._replace_single, BlockManager.apply
