### ISSUE TITLE
BUG: no attribute when the column name contains an "ϵ"

### ISSUE THREAD

**Issue by cynddl** [pandas-dev/pandas#26885]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame({'col1': [0, 1]})
df['α'] = df['col1']
df['ϵ'] = df['col1']
```

This line is executed correctly:
```python
df.α
```
but this one yields `AttributeError: 'DataFrame' object has no attribute 'ε'`:
```python
df.ϵ
```

#### Problem description

With pandas 0.24.2, dataFrame columns can often be accessed as attributes, except when they contain specific unicode characters (at least "ε"). I managed to reproduce this issue when loading a CSV file with an ε inside the header, but _sometimes_ not when creating a DataFrame object from a dictionary:

This yields no exception when accessing `df.ϵ`:
```
df = pd.DataFrame(dict(α=[0, 1], ϵ=[0, 1]))
```
but this one does:
```
df = pd.DataFrame({'α': [0, 1], 'ϵ': [0, 1]})
```

**Comment by cynddl** [comment]
More information! I looked at `__getattr__` in _generic.py_.

Running `df.ϵ` converts the attribute name to `b'\xce\xb5'` (U+03B5) while running `getattr(df, 'ϵ')` converts the attribute name to `b'\xcf\xb5'` (U+03F5). This happens both with IPython and the default repl. 😕 

Note that I'm not incorrectly typing \varepsilon instead of \epsilon (or vice versa). The IPython autocompletion for instance incorrectly uses the wrong epsilon.

Potentially related to https://github.com/JuliaLang/julia/issues/14751 and https://github.com/ipython/ipython/pull/6380

**Comment by TomAugspurger** [comment]
thanks for following up. Sounds like a bug outside of pandas then.
