### ISSUE TITLE
CI: Improve codecov reporting

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#26896]
Codecov is adding two comments to our PRs after the tests are successfully run. Which makes us receive two messages. Personally I don't find these useful. I see that other projects have codecov in the checks, next to the builds (expand the "All checks have passed" in https://github.com/xhochy/fletcher/pull/74 to see an example).

Is other people finding those comments/messages useful? Would be enough for you to just have the info in the list of checks and no emails?

xref #12634

**Comment by jreback** [comment]
+1 on this 
the messages are confusing / less than useful

**Comment by jorisvandenbossche** [comment]
+1

Additionally, codecov gives simply useless / wrong feedback more often than not. 
Many times that I want to check the code coverage of a PR, it often even doesn't load on their website.
