### ISSUE TITLE
pandas.DataFrame.insert error

### ISSUE THREAD

**Issue by galen5hk** [pandas-dev/pandas#26898]
#### Code Sample,
try to use DataFrame.inset() and get error   pd.__version__ = 0.24.2
![error](https://user-images.githubusercontent.com/15775816/59591870-6d95e880-9121-11e9-90bb-bfef15aa4fab.JPG)
![good](https://user-images.githubusercontent.com/15775816/59591871-6e2e7f00-9121-11e9-9550-d3f41f9b1e57.png)

```python
# Your code here
df = pd.DataFrame(data = np.random.randn(6,2), index=['a', 'b','c','d','e','f'], columns=['X', 'Y'])
df.insert(1, 'Z', np.random.randn(6), allow_duplicates=True)  # works good
df.insert(loc=1, 'Z', np.random.randn(6), allow_duplicates=True) # Error here
```
#### Problem description
when add 'loc=' before 1, it shows error

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by jreback** [comment]
please read the error message 
you have a syntax error
you cannot have keyword args before positional args

**Comment by galen5hk** [comment]
got it, thank you very much.
