### ISSUE TITLE
Usability: TAB completion no longer works with accessors

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#26899]
When doing the following in the IPython console:

```
In [1]: pd.Series.str.<TAB>
```

or 

```
In [2]: s = pd.Series(['a', 'b']) 

In [3]: s.str.<TAB>
```

this used to give the list of available methods on the `str` accessor (the same for eg `dt`). But with latest master / latest IPython this no longer works. This is quite a usability regression, I typically used it when giving workshows to show a way to interactively check what methods are available.

The non working case is with pandas 0.24.2 + IPython 7.5.0. I checked it with another environment with pandas 0.22.0 + IPython 5.8.0 where it is working. 
So it could be either due to a change in pandas or a change in IPython (or one of its dependencies for this).

**Comment by jorisvandenbossche** [comment]
It seems to be an IPython issue rather than pandas, at first sight. Possibly related: https://github.com/ipython/ipython/issues/11546

**Comment by TomAugspurger** [comment]
FWIW, this seems OK to me with IPython 7.5.0, Jedi 0.13.0, & pandas master.

**Comment by jorisvandenbossche** [comment]
I tested in an environment I set up last week with:

```
ipython                   7.5.0            py37h24bf2e0_0    conda-forge
jedi                      0.13.3                   py37_0    conda-forge
pandas                    0.24.2           py37hb3f55d8_0    conda-forge
```

also on master (with same versions of ipython/jedi) it's also failing.

Does it work for you for both described cases?

**Comment by TomAugspurger** [comment]
Sorry, just the second is working. Completion of the accessor on a class like `pd.Series.str` is not working. I didn't realize that it did in the past.

**Comment by jorisvandenbossche** [comment]
BTW, I notice it really depends on small details what you did before. 

Eg 

```
In [1]: s = pd.Series(['a'])

In [2]: s.str.<TAB>  # does not work

In [2]: s.str
Out[2]: <pandas.core.strings.StringMethods at 0x7fa202512128>

In [3]: s.str.<TAB>  # now works
```

or 

```
In [1]: s = pd.Series(['a'])                                                                                                                                                                                       

In [2]: s.s<TAB> # complete to 'str'

In [2]: s.str.<TAB> # now also works
```

(note for each test I restart an IPython session)

**Comment by jorisvandenbossche** [comment]
And with `ipython --IPCompleter.use_jedi=False`, both cases work nicely (as I remember they once did)

**Comment by davidhalter** [comment]
This was fixed in https://github.com/davidhalter/jedi/issues/1299.

Though, I would like to point out that this was never a bug, it was a safety feature that should make it less likely that you guys shoot yourself in the foot. Now it's gone and I think that's fine, but it was actually work to "protect" you guys.

Next time, please participate in the discussion in Jedi, I wasn't aware for a long time that this was such a big issue for a lot of people.

Use Jedi 0.15.0.

This can be closed.
