### ISSUE TITLE
Series doesn't implement floor/ceil ops (+EA support needed)

### ISSUE THREAD

**Issue by pilkibun** [pandas-dev/pandas#26892]
```python
In [19]: import pandas as pd
    ...: s=pd.Series([1,2])
    ...: s.floor() 
AttributeError: 'Series' object has no attribute 'floor'
```

**Comment by TomAugspurger** [comment]
I'd prefer users just `.apply(np.floor)`. I don't think these are broadly useful enough to warrant a method, especially as they don't work for all dtypes.

**Comment by pilkibun** [comment]
Reasonable, but another case to consider for EA.

```python
s=pd.Series(DecimalArray(to_decimal([1,2,3])))
s.apply(np.floor)

pandas/core/series.py in apply(self, func, convert_dtype, args, **kwds)
   3705         with np.errstate(all='ignore'):
   3706             if isinstance(f, np.ufunc):
-> 3707                 return f(self)
   3708 
   3709             # row-wise access

AttributeError: 'decimal.Decimal' object has no attribute 'floor'
```

I think this calls `__array__` on the array, which converts ito tobject,
and then the `np.floor` ufunc sees an object, and tries to all `floor` on it,
which fails. and yet `math.floor(decimal)` returns an int, (which might
be also be cast to decimal by the EA). 

So I think right now, `s.apply(np.floor)` doesn't work for EA,
and can't without changes to pandas.

**Comment by TomAugspurger** [comment]
What specifically do you mean by changes to pandas?

DecimalArray is a test-only extension array. It’s not part of the public API. So changes to it aren’t necessary for this issue.

More generally, a user could apply a floor function appropriate for their data.

**Comment by pilkibun** [comment]
Well, I was using Decimal as a concrete example. EA of its "kind" aren't handled gracfully in this situation
in that `s.apply(np.floor)` works for numpy dtypes but not EA.

> More generally, a user could apply a floor function appropriate for their data.

Yes, but in the case of something like pint, that means accessing an internal array
two attribute levels deep, and casting back to the proper EA, and wrapping by a Series ctor,
or something about as cumbersome.  I though the purpose of EA was to have them as 
seamless as "native" pandas dtypes.

**Comment by TomAugspurger** [comment]
Ok, let’s try rephrasing. Assuming we don’t add a Series.floor, what exactly needs to change in pandas to support your use case?

**Comment by TomAugspurger** [comment]
One important point: pandas makes no assumptions about how the EA is stored, so things like “works for numpy dtypes but not EA” probably isn’t correct. A specific EA may or may not work with NumPy’s API.

**Comment by pilkibun** [comment]
> A specific EA may or may not work with NumPy’s API.

whether or it chooses to *implement* a numpy api is a separate issue. Whether pandas actually *invokes* that implementation when the series method is called is another. And I'm talking about  
the latter. 

In particular, all series methods/ops which work by calling `np.asarray(self)` or relying on the default `EA.__array__` (which calls `np.asarray(self.array)`), fail this test.

I think `apply` fails it. So for example. not only `np.floor(s)` fail for an EA, but also `np.cos(s)`
and the other trig functions.

**Comment by TomAugspurger** [comment]
Does apply call asarray?

**Comment by pilkibun** [comment]
`Series.apply(ufunc)` calls `ufunc(self)` which invokes `Series.__array__` to get something it get work on, which calls `np.asarray(self.array, dtype)`. The result is an object ndarray.

**Comment by TomAugspurger** [comment]
https://github.com/pandas-dev/pandas/pull/23293 would seem to solve that. I
hope to finish that up for the 0.25 release.

**Comment by TomAugspurger** [comment]
As a short demo, consider the following incomplete `Series.__array_ufunc__`.

```python
diff --git a/pandas/core/series.py b/pandas/core/series.py
index eaef1f525..2bc1dfe1a 100644
--- a/pandas/core/series.py
+++ b/pandas/core/series.py
@@ -701,6 +701,11 @@ class Series(base.IndexOpsMixin, generic.NDFrame):
     # ----------------------------------------------------------------------
     # NDArray Compat
 
+    def __array_ufunc__(self, ufunc, method, *inputs, **kwargs):
+        arrays = tuple(x.array for x in inputs)
+        result = getattr(ufunc, method)(*arrays)
+        return self._constructor(result, index=self.index).__finalize__(self)
+
     def __array__(self, dtype=None):
         """
         Return the values as a NumPy array.
```

The basic idea is to extract the arrays from the series, apply the ufunc, and box the result in a Series. For Series[Sparse], we dispatch to SparseArray which implements `__array_ufunc__`

```python
In [1]: import pandas as pd; import numpy as np

In [2]: s = pd.Series(pd.SparseArray([-1, 0, 1]))

In [3]: np.sin(s)
Out[3]:
0   -0.841471
1    0.000000
2    0.841471
dtype: Sparse[float64, 0.0]

In [4]: s.apply(np.sin)
Out[4]:
0   -0.841471
1    0.000000
2    0.841471
dtype: Sparse[float64, 0.0]
```

On master, that's dense.

**Comment by pilkibun** [comment]
Yes, that's fine in that if the EA implements its own `__array_ufunc__` it can take over. But I'm very unhappy by the patchwork frankenstein way in which different classes of methods rely on different mechanisms for EA authors to implement them. While other (cumprod, for example) some simply don't allow it. See how horrible it looks when documented https://github.com/pandas-dev/pandas/pull/26918.
I've opened https://github.com/pandas-dev/pandas/issues/26935 suggesting something better needs to take shape.

**Comment by TomAugspurger** [comment]
> See how horrible it looks when documented

Please don't dismiss the work we've put into it.

**Comment by pilkibun** [comment]
Apologies, I didn't mean that at all.

**Comment by pilkibun** [comment]
>  I don't think you've actually worked on that issue in particular

well, that's another bad error on my part, I now realize after reading more of the back issues on the subject. It was inconsiderate of me and I'm sorry. The numpy dispatch mechanisms still seem very complex to me, for example the minutiae in the `__array_ufunc__` PR ... it's a little intimidating.
Writing a generic, correct `__array_ufunc__` or `__array_function__` is not an easy job and I'm not sure to to what extent the details can be effectively hidden from EA developers. Is there a WIP for putting this logic in `ExtensionArray` or a mixin for reuse by EA developers? I'd like to get a better sense of the future for writing EAs.

**Comment by pilkibun** [comment]
> #23293 would seem to solve that.
