### ISSUE TITLE
DEPR: Timestamp, NaT, TimedeltaIndex, DatetimeIndex resolution

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#26906]
We recently made Timedelta.resolution match the stdlib timedelta.resolution behavior (#26839), should make all our others use consistent naming.

**Comment by sameshl** [comment]
@jbrockmendel I would love to work on this. Could you elaborate on what needs to be done here?

**Comment by jbrockmendel** [comment]
@sameshl great!  Take a look at what we did in #26839 for Timedelta, and then we need to do the same thing for Timestamp, NaT, TimedeltaIndex, and DatetimeIndex.

**Comment by jbrockmendel** [comment]
This is done for Timestamp and NaT, not worth worrying about for the indexes.  Closing.
