### ISSUE TITLE
Tabular numbers should be used on tables

### ISSUE THREAD

**Issue by dansondergaard** [pandas-dev/pandas#26917]
**Describe the bug**
Tables rendered in Jupyter Lab (likely also Jupyter Notebook), e.g. from pandas, do not use tabular numbers. This causes sorted columns to look unsorted and makes numbers harder to read and compare.

**To Reproduce**

Create a table like this:

<img width="299" alt="Screenshot 2019-06-14 at 08 38 42" src="https://user-images.githubusercontent.com/204911/59488447-dc541700-8e7f-11e9-8aff-50274888859c.png">

**Expected behavior**

With tabular numbers applied through CSS:

<img width="302" alt="Screenshot 2019-06-14 at 08 41 07" src="https://user-images.githubusercontent.com/204911/59488557-3228bf00-8e80-11e9-917d-62e6024233bf.png">

CSS used to apply tabular numbers:

```
table { font-variant-numeric: tabular-nums; }
```

**Screenshots**

Screenshots attached above.

**Desktop (please complete the following information):**

- OS: Any
- Browser: Any
- JupyterLab: Tested on 0.35.6, but probably applies to any version of Jupyter Lab

**Comment by TomAugspurger** [comment]
IIRC Jupyterlab provides the CSS. Shouldn't they add the `table { font-variant-numeric: tabular-nums; }`?

**Comment by dansondergaard** [comment]
I submitted the issue to Jupyter Lab first, but they think that it's up to pandas to render the table correctly (https://github.com/jupyterlab/jupyterlab/issues/6570#issue-456092602).

**Comment by kevinglasson** [comment]
Just looking into this.

It is not a problem in Jupyter Notebook.

![Screen Shot 2019-07-01 at 11 47 10 pm](https://user-images.githubusercontent.com/22187575/60449633-a9b96500-9c5a-11e9-9d4a-b7ac1be28177.jpg)

The style mentioned above ```table { font-variant-numeric: tabular-nums; }``` is nowhere in sight in the notebook, so I don't know 'how' it's working.

Adding it to jupyter-lab manually does however rectify the problem

**Comment by ramantehlan** [comment]
Hey @dansondergaard, 

I tried reproducing the issue, but I wasn't able to, here are the results I got.

1. Notebook

![notebook](https://user-images.githubusercontent.com/29037312/68338534-ba964d80-0108-11ea-8786-4d5217148080.png)

2. Lab

![lab](https://user-images.githubusercontent.com/29037312/68338637-f29d9080-0108-11ea-9c2d-a609d3372fdf.png)

3. Browser, using the `.to_html` output.

![browser](https://user-images.githubusercontent.com/29037312/68338847-5d4ecc00-0109-11ea-8774-0674c239556e.png)


Can you confirm if you are still getting this issue?

**Comment by dansondergaard** [comment]
@ramantehlan, I just installed the most recent Jupyter Notebook version in a clean environment and it indeed seems to be fixed. Thanks!
