### ISSUE TITLE
Should Pandas adopt a naming convention for its protocol methods

### ISSUE THREAD

**Issue by pilkibun** [pandas-dev/pandas#26915]
numpy has defined various protocol extensions over the years, and has consistently
named them with an array prefix, and "dunder" notation: 
- `__array__`
- `__array_prepare__`,  `__array_wrap__`, [Subclassing ndarray](http://docs.python.org/doc/numpy/user/basics.subclassing.html)
- `__aray_ufunc__` [NEP13](https://www.numpy.org/neps/nep-0013-ufunc-overrides.html
)
- `__array_function__` [NEP18](https://www.numpy.org/neps/nep-0018-array-function-protocol.html)

pandas has't been as diligent. The one example I've been dealing with, is `_reduce`. Originally an internal Series method (not a protocol), it now dispatches to `_reduce` for subclasses of `ExtensionArray`. https://github.com/pandas-dev/pandas/blob/baa77c33fb71c29acea21ba06adaf426ed4cb561/pandas/core/series.py#L3743-L3745

When reading the code for a new EA project, its hard to pick out that _reduce is actually an override of the parent class, instead of just an internal function written by the EA author. Something like `__pandas_reduce__` would have made this clearer.

Due to inexperience with EA, I lost a bit of time figuring out why `s.sum()` wasn't invoking  the EA implementation I thought it would.

Granted, it's not exactly a protocol. For the forseeable future, this will always be an `ExtensionArray` subclass, rather than a duck typed object. But, for readability,
and while EA is experimental, this might be the right time to clean it up.

**Comment by TomAugspurger** [comment]
Typically dunder methods are associated with a top-level method intended for users to call. Since there isn't a single `reduce` method that corresponds to `ExtensionArray._reduce`, I don't think a dunder method is appropriate.

**Comment by jorisvandenbossche** [comment]
Note that this is partly also historically. Until recently with the EAs, we never had candidates for such methods. And the specific example of `_reduce`: this already existed internally before it was exposed as part of the EA interface, so this was mainly added to the EA interface to quickly have something that EAs can tap into.

But I think I agree with @TomAugspurger that at this moment, a full dunder method is maybe not warranted. It are indeed only overrides of the parent class, not actual protocols (and good documentation / comments in the source code can make this clear I think).

**Comment by pilkibun** [comment]
> Typically dunder methods are associated with a top-level method intended for users to call.

not so. `__array__`? `__array_ufunc__`? none of the numpy methods have to do with top level methods. As I see it, duner methods are about protocols and/or duck typing.

> I don't think a dunder method is appropriate.

@TomAugspurger. Not necessarily a dunder method (though I think it fits), but a rename to indicate association with pandas. `_reduce` is rather generic.

> so this was mainly added to the EA interface to quickly have something that EAs can tap into.

sure, but now should it stay that way?

Remember, this is the first time where pandas extensions have been externally developed. Numpy looks for specific methods in an external object to detect support, pandas EA does the same (well, it just calls it). I think it should be thought of as a protocol.

**Comment by TomAugspurger** [comment]
I'm OK with the current setup.

**Comment by pilkibun** [comment]
#26935

**Comment by jorisvandenbossche** [comment]
> > Typically dunder methods are associated with a top-level method intended for users to call.
>
> not so. __array__? __array_ufunc__? none of the numpy methods have to do with top level methods. As I see it, duner methods are about protocols and/or duck typing.

They are (but with *functions*, not methods as Tom said, that was maybe confusing): `__array__` is a way to tap into `np.(as)array(..)`, `__array_ufunc__` are a way to tap into `np.add`, `np.subtract`, .. top-level ufuncs.

I don't think we are ready at all to make official dunder methods. It took many years for numpy to get to this. Let's first further experiment with what we have, and for sure, look into what is still missing for other numerical ops (the things being discussed in the other issues you opened)

**Comment by pilkibun** [comment]
hmm. So `np.sum` but `ndarray.sum` is not and therefore `series.sum` is not? and yet when we implement `__array_function__` we do so in order to perform `Series.sum()`. I'm not sure I follow the logic, but I don't really care about having dunder naming in particular. Call it `_pandas_reduce`.

The point I'm arguing is that when numpy interacts with extenal objects, it detects specific interfaces via specially named methods, which are explicitly named to declare themselves as numpy interface functions. 

This issue is not actually about `_reduce`, but about the suggestion in https://github.com/pandas-dev/pandas/pull/26918, that we build a single dispatch interface which unifies all the series methods,
against which EA authors develop. Something like `__pandas_method__` with or without the dunders, and not necessarily copying the design of NEP18 (which I do not like). perhaps something more like
a `pandas` accessor, which the EA implements, and under that clearly labeled and isolated namespace, they put the series method implementation they care about. No confusion with numpy,
no legacy constraints on keywords, no mixing between pandas methods and internal EA methods.
We could provide a mixin, or a bunch of them by "categories" of EA. I've been gradually building up an idea of how this might look, as the solution suggested in https://github.com/pandas-dev/pandas/issues/26935.

**Comment by jorisvandenbossche** [comment]
> This issue is not actually about _reduce, but about the suggestion in #26935, that we build a single dispatch interface which unifies all the series methods,

Well, but the example we were discussing *was* `_reduce`. And we have many similar other methods that are part of our "EA interface", such as `_from_sequence`, `_from_factorized`, `_concat_same_type`, ... I don't think there is any point to start renaming those *at this point*.

To be clear, that is not to say the discussion in #26935 is not worth having. Absolutely not, that are problems we need to find a solution for. But just that the starting to rename the already existing methods is currently not that useful, I think (not that we could have chosen better names if we would start over). So closing this, let's continue the discussion about the actual method dispatch problem in #26935.
