### ISSUE TITLE
ENH: Add circular statistics methods for DataFrames and Series

### ISSUE THREAD

**Issue by petebachant** [pandas-dev/pandas#26928]
Let me know if this is out of scope, but it would be nice to perform typical statistics calculations on circular quantities with a similar interface as, e.g., `mean` --> `circmean`, including the `level` arg. It would also be great to be able to note that the input is in degrees to avoid having to convert back and forth from radians.

```python
mean_dir = df.direction_deg.circmean(degrees=True, level="time")
```

**Comment by TomAugspurger** [comment]
I've never heard of a circular mean, which is some evidence that it's too niche to be included in pandas :)

**Comment by jorisvandenbossche** [comment]
Yes, I agree with @TomAugspurger 's assessment, I also never heard of circular statistics.

**Comment by petebachant** [comment]
Fair enough. For the record, these would be methods done on something like an angle, since the non-circular mean of 355 degrees and 5 degrees is not halfway between the two on a circle.
