### ISSUE TITLE
Link from, for e.g., version/0.22/generate, to stable/reference

### ISSUE THREAD

**Issue by dumbledad** [pandas-dev/pandas#26922]
Google often drops me in specific documentation from a single release, rather than the stable reference. For example the google search [pandas groupby aggregate](https://www.google.com/search?safe=active&rlz=1C1CHBD_en-GBIE841IE842&ei=4eMIXbCFKaXD8gKrzJLoBg&q=pandas+groupby+aggregate&oq=pandas+groupby+aggregat&gs_l=psy-ab.3.0.0i67j0l9.4663.11142..13900...1.0..0.52.506.10......0....1..gws-wiz.......0i71j35i39j0i20i263.BPBJmUg8WD8) had these two as top results:

- https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.core.groupby.DataFrameGroupBy.agg.html
- https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.core.groupby.DataFrameGroupBy.agg.html

Neither of those pages include an easy way to get back to the main version of the page (is it https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.agg.html ?)

It would be useful if it were easier to get from a specific version of the docs to the stable reference version.

**Comment by dumbledad** [comment]
(N.B. See discussion [here](https://github.com/pandas-dev/pandas-website/issues/72))

**Comment by jorisvandenbossche** [comment]
Note that the specific example here (where the url path also changed in general, and not only the "/version/0.22/" vs "/stable/" part is different) is probably more difficult to solve.

But in general an easier link to the the latest documentation would be very welcome.

There are some other sphinx based projects doing similar things that might be worth looking into. 
Eg the python docs have a dropdown (https://docs.python.org/3.6/, which at least makes it more accessible). 
The readthedocs theme has a similar pop-up where you can choose from other versions, and they also automatically include a note in documentation pages of older versions that you are not looking at the latest page, see eg https://geopandas.readthedocs.io/en/v0.2/. They might have a javascript extension for that, as it is not part of the html source of the page. Possible interesting to reuse.

**Comment by mroeschke** [comment]
Now that there's a dropdown to switch to different versions, I think that satisfies the necessary requirement. Closing.
