### ISSUE TITLE
A unified method dispatch protocol for ExtensionArrays

### ISSUE THREAD

**Issue by pilkibun** [pandas-dev/pandas#26935]
Having written #26918, I'm considering whether perhaps the whole current Series dispatch mechanism needs work, in that there really isn't one. It's just a motley collections of disparate bits which predate EAs, when all the ugliness was limited to internal code.

Currently, into to suport series methods,  in their `ExtensionArray` need to implement:
1. `_reduce` for pandas. which duplicates many but not all numpy ufuncs, Extends them, but has incompatible signatures with them.
2. `__array_ufunc__` for numpy ufunc
3. Either a slew of individual methods like round, `__array_func__` or use a clever `__getattr__` hack to support non-ufunc numpy functions. And that still doesn't address adding future Series methods, or current methods like cumprod, which aren't simply wrappers around a single call to a numpy function (in the skipna=True case). 
4. Other methods are neither pure wrappers of numpy, nor dispatch to an overridable method (like `_reduce`), so in the current (lack of) "model" they cannot be overriden by EA authors at all. For example `Series.cumprod(skipna=True)` (and all others cum functions which rely on `_make_cum_function` in  `pd.core.generic` for `skipna` support since np.putmask requires an ndarray as argument and so this approach will not dispatch to the EA<del>(`accum_func` is `np.prod.accumulate`, which uses numpy's dispatch logic)</del> https://github.com/pandas-dev/pandas/blob/d47947a79099d650b4bb981a38ce09881ec6f43d/pandas/core/generic.py#L11017-L11022
NA are handled with a call to `np.putmask`, which requires a true ndarray. Incompat with EA.

Even after having done that, many methods currently don't work because they haven't been updated to support EA, and contain either explicit or hidden casting to object dtypes. That is fixable, but indicates that the whole issue hasn't comprehensively been addressed yet. I've been trying to fix individual methods, and what I've realized is that even doing that would lead to something ugly, complex, partially broken, non future-proof.

The way things are, supporting series methods (even selectively), places a major burden on EA authors, which have to deal with 3 different mechanisms to implement methods. To make matters worse,  with all that work, there's still no solution for future series methods, or even some existing methods. 

I think this is a vitally important issue, and a big job.
 
What I'd like to have is:
1. a single, unified interface for dispatching Series methods
2. which supports EA
3. for all methods
4. and allows every method to be overrided by EA, as-needed
5. supports NA
6. doesn't require EA authors to implement some methods to signature-compatible with numpy (`round`), and signature compatible with a competing pandas version in other (`sum` via `_reduce`)
7. Clearly namespaces pandas functions, which also indicates cooperation/opt-in (perhaps via duck typing), so that 
7a. its clear which methods implements pandas interface
7b. there are no methods which are named like a numpy method, but with a pandas signature, or vice versa
7c. when reading an EA's code, you don't have to guess or figure out which code is 
a pandas method and which is an internal method for the EA (like the poorly named `_reduce`)
8. provides a good, clear error message report unimplemented methods, instead of relying on AttributeError Guardrails from numpy's innards.
9. Optionally, icecream. And other things.

The above is as much a list of failing of the current model as it is of what I'd like to see replace it.

**Comment by jorisvandenbossche** [comment]
(sidenote: it is great that you are exploring all those things, really! That is very welcome, and also needed, as you will have noticed many areas here are still not fully explored (the current EAs we ourselves worked with mostly don't need those numpy funcs). But I would recommend slowing down a bit the number of *discussion* issues you are opening (bug reports is something else of course), and try to focus our energy to the current open discussions. We all have limited time, and having yet another new issue before we had time to respond to the previous one will not help in that, and it will also frustrate you of having to wait more. This is not always an easy aspect of open source, but a reality we have to cope with!)

**Comment by jorisvandenbossche** [comment]
Some comments on the analysis side first:

> _reduce for pandas. which duplicates many but not all numpy ufuncs, Extends them, but has incompatible signatures with them.

`_reduce` does not cover ufuncs, but it covers a bunch of reductions (so they rather overlap with numpy's method-name-based dispatch and now `__array_function__`. 
They indeed have an incompatible signature (we have eg `skipna`), and for that reason I think we cannot rely on a numpy dispatch method here.

> Other methods are neither pure wrappers of numpy, nor dispatch to an overridable method (like _reduce), so in the current (lack of) "model" they cannot be overriden by EA authors at all. For example Series.cumprod(skipna=True) (accum_func is np.prod.accumulate, which uses numpy's dispatch logic) 

I don't think `np.prod.accumulate` exists? (prod is not a ufunc) You mean `np.mutliply.accumulate` ? 
But to the actual issue: this is certainly something we didn't yet really think about.

**Comment by pilkibun** [comment]
> I don't think np.prod.accumulate exists?
You're right thanks, take `cummin` and `np.minimum.accumulate` the example instead, but its actually
the way `skipna=True` is handled via `_make_cum_func` in the snippet, which only works with ndarrays.

> _reduce does not cover ufuncs, but it covers a bunch of reductions (so they rather overlap with 
> numpy's method-name-based dispatch and now __array_function__.
> They indeed have an incompatible signature (we have eg skipna), and for that reason I think we 
> cannot rely on a numpy dispatch method here.

There are two seperate arguments I'm making:
1. Overiding/Providing implementation relies on too many different mechanisms (1 for ufunc via one numpy NEP, 1 for non-ufunc using another numpy convention, and 1 from pandas via `_reduce`)
2. That dispatch right now works at all is a historical fluke. From the pandas side `_reduce` is a legacy carry-over, and you yourself (or tom?) refered to it as a hack. And the rest only works because numpy has complex dispatch logic for its own functions, which only works if a method is a pure wrapper around a call to numpy (and not for example for `_make_cum_function` generated functions like `cumprod`. 

Of course I understand why `_reduce` was needed, pandas needed more control for NA handling (among other things). Still, that was long before EAs were introduced. Now, it should be possible to provide a single interface for EA authors to hook their implementations into, rather than requiring knowledge of three, and then still supporting only some Series methods, and with no path for future expansion. 

So that, along with the rest of the points in my wishlist, is why I think the current situation isn't satisfactory.

**Comment by pilkibun** [comment]
Copied from https://github.com/pandas-dev/pandas/issues/26915#issuecomment-503638960:

> This issue is not actually about _reduce, but about the suggestion in #26935, that we build a single 
> dispatch interface which unifies all the series methods,
> against which EA authors develop. Something like __pandas_method__ with or without the dunders, 
> and not necessarily copying the design of NEP18 (which I do not like). perhaps something more like
> a pandas accessor, which the EA implements, and under that clearly labeled and isolated namespace, > they put the series method implementation they care about. No confusion with numpy,
> no legacy constraints on keywords, no mixing between pandas methods and internal EA methods.
> We could provide a mixin, or a bunch of them by "categories" of EA. I've been gradually building up an > idea of how this might look, as the solution suggested in #26935.

**Comment by jorisvandenbossche** [comment]
> The point holds though, it's the way skipna=True is handled via _make_cum_func in the snippet, which only works with ndarrays, because of the use of np.putmask which required ndarrays.

I suppose `np.putmask` would also fall under `__array_function__` protocol, so could be made to work on an EA?

**Comment by pilkibun** [comment]
I just checked, yes `np.putmask` triggers `__array_function__`.

**Comment by pilkibun** [comment]
Which is surprising, since before adding it to the list I checked, and method-dispatch doesn't seem to work for it. I've asked numpy about it: https://github.com/numpy/numpy/issues/13806.

**Comment by pilkibun** [comment]
I get the feeling that `ExtensionArray` were a great opportunity to reduce the coupling between pandas and numpyand, instead, with the trajectory dispatch is taking, more and more of numpy's conventions and legacy is being baked in to a new generation of pandas extension. :(

**Comment by pilkibun** [comment]
zero interest from the pandas team. closing.
