### ISSUE TITLE
ufunc[Series, Series] should align before aplying the ufunc?

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#26945]
Should this align before doing the ufunc?

```python
In [1]: import numpy as np

In [2]: import pandas as pd

In [3]: s1 = pd.Series([1, 2, 3])

In [4]: s2 = s1.iloc[[0, 2, 1]]

In [5]: np.add(s1, s2)
Out[5]:
0    2
1    5
2    5
dtype: int64
```

IMO, the expected output should be 

```
In [6]: np.add(*s1.align(s2))
Out[6]:
0    2
1    4
2    6
dtype: int64
```

cc @shoyer, @jbrockmendel, @jorisvandenbossche

**Comment by TomAugspurger** [comment]
We should also think about what this implies for binary ufuncs involving Series and DataFrame.

**Comment by jorisvandenbossche** [comment]
I think it could also be a reasonable thing to say in general that "when using numpy functions, no alignment is performed". 

Not sure if I personally have a preference for one of both "rules" though.

**Comment by TomAugspurger** [comment]
One argument in favor of alignment: then `np.add(s1, s2)` is closer (the same as?) `s1.add(s2)`. There are still things like fill_value that the ufunc can't support, but still that may be good to argue for.

The alternative "`ufunc(series)` is essentially `Series(ufunc(series.array))` is absolutely compelling. I just think alignment better aligns (hah) with pandas usual behavior.

**Comment by TomAugspurger** [comment]
Xarray's docs: http://xarray.pydata.org/en/stable/generated/xarray.apply_ufunc.html

> The function will be mapped over the data variable(s) of the input arguments using xarray’s standard rules for labeled computation, including alignment, broadcasting, looping over GroupBy/Dataset variables, and merging of coordinates.

```python
In [10]: a = xr.DataArray([1, 2, 3], coords=[('x', [0.1, 0.2, 0.3])])
    ...: b = xr.DataArray([2, 1, 3], coords=[('x', [0.2, 0.1, 0.3])])

In [11]: np.add(a, b)
Out[11]:
<xarray.DataArray (x: 3)>
array([2, 4, 6])
Coordinates:
  * x        (x) float64 0.1 0.2 0.3
```

so it seems to align.

**Comment by jreback** [comment]
agree these should align

**Comment by shoyer** [comment]
Yes, I think pandas should definitely align before applying ufuncs.

The other reason for this is that NumPy requires that `np.add(x, y)` and `x + y` be equivalent, at least if `x` is a numpy array.

**Comment by jorisvandenbossche** [comment]
Yeah, I am also fine with alignment, didn't think much about it. It certainly makes sense to follow xarray's example.

**Comment by jorisvandenbossche** [comment]
> The other reason for this is that NumPy requires that np.add(x, y) and x + y be equivalent, at least if x is a numpy array.

That's indeed certainly a good argument to keep those two also in pandas exactly equivalent.

**Comment by jbrockmendel** [comment]
What's the use case that would cause someone to use `np.add(x, y)` instead of `x+y`?  There are a number of places where we test that these are equivalent, which is what I would expect to be the case everywhere.

**Comment by jorisvandenbossche** [comment]
> There are a number of places where we test that these are equivalent,

But apparently only with already aligned objects, as more non-aligned they are currently not equivalent (with the example of Tom above):

```
In [17]: s1 + s2                                                                                                                                                                                                   
Out[17]: 
0    2
1    4
2    6
dtype: int64

In [18]: np.add(s1, s2)                                                                                                                                                                                            
Out[18]: 
0    2
1    5
2    5
dtype: int64
```

**Comment by jbrockmendel** [comment]
closeable?

**Comment by TomAugspurger** [comment]
Indeed.
