### ISSUE TITLE
to_csv header=False not working

### ISSUE THREAD

**Issue by mkagenius** [pandas-dev/pandas#26948]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
 c = a.apply(fixsub, axis=1)
 c = c.fillna("nan")
 c.to_csv('solution2.csv', header=False, index=False)
```
#### Problem description

Even after putting header=False, header keeps coming in the csv

#### Expected Output

no header should come in the csv file

#### Output of ``pd.show_versions()``
0.24.2

### How to fix

culprit code in pandas/io/formats/csvs.py

```python

    def _save_header(self):

        writer = self.writer
        obj = self.obj
        index_label = self.index_label
        cols = self.cols
        has_mi_columns = self.has_mi_columns
        header = self.header
        encoded_labels = []

        has_aliases = isinstance(header, (tuple, list, np.ndarray,
                                          ABCIndexClass))
        if not (has_aliases or self.header): ## BUG HERE FIX NEEDED
            return

```

[paste the output of ``pd.show_versions()`` here below this line]
0.24.2
</details>

**Comment by WillAyd** [comment]
Can you provide a fully reproducible code example? It's not clear from what you have provided what `a` and `c` are

**Comment by mroeschke** [comment]
We're happy to reopen this issue when we could validate the issue with a reproducible example
