### ISSUE TITLE
pandas.read_hdf leaves file open when requested data key does not exist

### ISSUE THREAD

**Issue by RomanKoziolek** [pandas-dev/pandas#26943]
#### Code Sample, a copy-pastable example if possible

```python
import pandas

data = pandas.read_hdf(<h5_file_name>, mode='r', key=key)

```
#### Problem description

When trying to read HDF5 file and the requested key object does not exist in the file, pandas pytables raises `KeyError('No object named {key} in the file'.)` and does not close the opened file. I would expect that the HDF5 file is closed after trying to read the key object, whether it was successful or not.
Trying to write to the file which is opened in read mode fails with exception.
The problematic code is in `pandas.io.pytables.py` file, method `select`, line 712.

#### Workaround
Check if the key exists before trying to read it from file.
```python
import h5py
key_exists = True
with h5py.File(<h5_file_name>, mode='r') as file:
    group = file.get(key)
    if not group:
       key_exists = False

if key_exists:
    ...
```

Should you need more details, please let me know.

**Comment by WillAyd** [comment]
What version of pandas are you using? Have you tried on master? IIRC was fixed recently

**Comment by RomanKoziolek** [comment]
I'm using 0.24.1 but I see the same code is on master. The `select` method just raises exception, does not close the file.

**Comment by WillAyd** [comment]
Do you mind trying on master?

**Comment by RomanKoziolek** [comment]
yes, I'll verify that on Friday

**Comment by rbenes** [comment]
I fixed very similar issue (maybe the same) few weeks ago https://github.com/pandas-dev/pandas/issues/25766  (it will be in next release)

**Comment by RomanKoziolek** [comment]
@rbenes your fix solves my issue.
@WillAyd, @rbenes thank you guys!
