### ISSUE TITLE
TypeError: to_html() got an unexpected keyword argument 'line_width'

### ISSUE THREAD

**Issue by piofel** [pandas-dev/pandas#26956]
While the documentation [https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.DataFrame.to_html.html](https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.DataFrame.to_html.html) promises the parameter `line_width` (at the bottom of the parameters list), using this parameter throws the error: `TypeError: to_html() got an unexpected keyword argument 'line_width'`

**Comment by simonjayhawkins** [comment]
@piofel Thanks for the report.

The `line_width` argument is not relevant to `to_html`. The documentation is misleading due to shared code with `to_string`.

Investigation and PRs welcome.

**Comment by gfyoung** [comment]
@piofel : Your issue is for an outdated version of the documentation.  If you check the latest version:

https://pandas-docs.github.io/pandas-docs-travis/

You will see that that parameter is not listed.  Are you specifically using `0.22.0` for your work?

**Comment by piofel** [comment]
@simonjayhawkins @gfyoung I use Pandas 0.24.2, I just missed that I used an outdated documentation in the heat of coding :) Thank you both!
