### ISSUE TITLE
CI: Fix Azure Pipelines problem with PATH

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#26962]
We should be able to set the environment variable `PATH` in an Azure Pipelines job with `echo '##vso[task.prependpath]$HOME/miniconda3/bin'`. See https://github.com/pandas-dev/pandas/blob/master/azure-pipelines.yml#L27

But that didn't work when we implemented it, so we ended up setting the path manually in every step (e.g. https://github.com/pandas-dev/pandas/blob/master/azure-pipelines.yml#L48).

This is adding noise to our CI configuration, making it harder to see what every step is doing. We should try to understand what's the problem with setting the `PATH`, and fix it.

This also applies to `ci/azure/posix.yml` (besides `azure-pipelines.yml` in the root).

**Comment by bhavaniravi** [comment]
I would like to work on this. Since I have gone through this part in the mentoring side, I feel confident and it is indeed an interesting problem to solve

**Comment by datapythonista** [comment]
Thanks a lot @bhavaniravi. Let me know if you need help.

**Comment by bhavaniravi** [comment]
Just one question for now, How do you test the changes in CI? I can think of setting an azure-pipeline for my forked repo? Is that a way to go?

**Comment by datapythonista** [comment]
I think that's quite smart. It took me couple of months to realize, waiting for the pandas CI to run jobs (some times there is a long queue in the CI). There is something weird, because in my fork's CI some things fail that don't fail in pandas, and that shouldn't happen. But regardless of that, I think it's the best approach if you plan to do significant work in the CI.
