### ISSUE TITLE
pprint_thing for sequences

### ISSUE THREAD

**Issue by jamesmyatt** [pandas-dev/pandas#26970]
I am using a custom dataclass as in the index of a DataFrame, which works fine. However, since it implements the Sequence protocol, pprint_thing is rendering every element, rather than the object itself. I would rather use the __str__ method that I have written. I know I can avoid this by changing "pprint_nest_depth" option to 0, but it would be nice to have a direct way of achieving this.

My main question is why the presence of a "__next__" attribute is used as the indicator that the correct output is the result of "str" (
https://github.com/pandas-dev/pandas/blob/cfd65e98e694b2ad40e97d06ffdd9096a3dea909/pandas/io/formats/printing.py#L207)

This is related to #17695, #18843 and #22333.

**Comment by WillAyd** [comment]
Can't speak to history but isn't this dispatching to your str implementation anyway? 

This isn't technically part of the API but if you see a more reasonable way of going about things and want to submit a PR with tests would take a look!

**Comment by jamesmyatt** [comment]
You're right. By manually changing a setting in every notebook, I can force it to use `str` for *everything*. However, until it's clear why `hasattr(thing, '__next__')` is a special case, it's not going to be possible to submit a suitable PR.

**Comment by simonjayhawkins** [comment]
> This is related to #17695, #18843 and #22333.

labelled as duplicate and closing.

**Comment by rajeee** [comment]
Does anyone have an answer for @jamesmyatt 's question about why the presence of __next__ attribute is used as a special case to determine if the str method should be used?

**Comment by simonjayhawkins** [comment]
@rajeee the open issue for this discussion is #18843. you may want to continue the discussion there.
