### ISSUE TITLE
algos.take calling validate_indices incorrectly?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#26976]
https://github.com/pandas-dev/pandas/blob/master/pandas/core/algorithms.py#L1528

In core.algorithms.take:

```
    if allow_fill:
        # Pandas style, -1 means NA
        validate_indices(indices, len(arr))
        result = take_1d(arr, indices, axis=axis, allow_fill=True,
fill_value=fill_value)
```

It looks to me like the `validate_indices` call should be `validate_indices(indices, arr.shape[axis])`.

Found while attempting to simplify #26914.

**Comment by jreback** [comment]
yes this looks to be incorrect
