### ISSUE TITLE
Series with MultiIndex "at" function raises "TypeError"

### ISSUE THREAD

**Issue by ndamclean** [pandas-dev/pandas#26989]
#### Code Sample

```python
# Your code here
import pandas as pd
s = pd.Series(index=pd.MultiIndex.from_tuples([('a', 0)]))
s.loc['a', 0]  # loc function works fine, no complaints here
s.at['a', 0]  # raises TypeError
```

#### Stack Trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 2270, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
TypeError: _get_value() got multiple values for argument 'takeable'
```
#### Problem description

I would expect the `at` function to either return the values given by the indexers or raise a `KeyError`. In the above example, the index value exists, so `at` should return the value from the series at that index (`nan`). 

The `at` function works fine for series with normal indexes. There is nothing in the documentation indicating it should not work for multi-indexes.

#### Expected Output

```
nan
nan
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-50-generic
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 3.4.2
pip: 19.1.1
setuptools: 41.0.1
Cython: 0.29.10
numpy: 1.16.4
scipy: 1.3.0
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2019.1
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by WillAyd** [comment]
Makes sense - if you'd like to take a look and submit a PR would certainly be welcome

**Comment by Seemachopra22** [comment]
try this option:
s.loc['a'].at[0]

**Comment by ndamclean** [comment]
@Seemachopra22 That seems like a reasonable workaround, but I still think this is a bug that should be fixed. I'll work on a PR if I have time.

**Comment by rhshadrach** [comment]
I stumbled upon the same issue and did a little digging into the code. Please forgive any errors that are to follow - I am quite new to looking at the Pandas internals.

It seems like the issue is line 2087 of this block of code within _ScalarAccessIndexer (similar issues for the getter methods):

https://github.com/pandas-dev/pandas/blob/844dc4a4fb8d213303085709aa4a3649400ed51a/pandas/core/indexing.py#L2085-L2091

When I run this on a series with a multi index, e.g.

    s = pd.DataFrame([['x', 'y', 1], ['z', 'w', 2]], columns=['a', 'b', 'c']).set_index(['a', 'b']).c
    s.at['x', 'y'] = 5

self.ndim is 1 whereas key is ('x', 'y'), which leads to raising the value error. What I can't tell is whether self.ndim here should be 2, or if perhaps this check is not correct.

**Comment by rhshadrach** [comment]
If self.ndim is the same as [pd.Series.ndim](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.ndim.html), then self.ndim must be 1 and I believe this check can be removed.
