### ISSUE TITLE
Can't read cvs using Pandas

### ISSUE THREAD

**Issue by zialecuyer** [pandas-dev/pandas#26991]
variable = pandas.read_csv(r"C://Users/zialecuyermorison/Desktop/data/iris.csv")

header.sepal_length( )

```python
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-61-ef9a5393d1d5> in <module>
----> 1 variable = pandas.read_csv(r"C://Users/zialecuyermorison/Desktop/data/iris.csv")

/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    700                     skip_blank_lines=skip_blank_lines)
    701 
--> 702         return _read(filepath_or_buffer, kwds)
    703 
    704     parser_f.__name__ = name

/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    427 
    428     # Create the parser.
--> 429     parser = TextFileReader(filepath_or_buffer, **kwds)
    430 
    431     if chunksize or iterator:

/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py in __init__(self, f, engine, **kwds)
    893             self.options['has_index_names'] = kwds['has_index_names']
    894 
--> 895         self._make_engine(self.engine)
    896 
    897     def close(self):

/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py in _make_engine(self, engine)
   1120     def _make_engine(self, engine='c'):
   1121         if engine == 'c':
-> 1122             self._engine = CParserWrapper(self.f, **self.options)
   1123         else:
   1124             if engine == 'python':

/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
   1851         kwds['usecols'] = self.usecols
   1852 
-> 1853         self._reader = parsers.TextReader(src, **kwds)
   1854         self.unnamed_cols = self._reader.unnamed_cols
   1855 

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: [Errno 2] File b'C://Users/zialecuyermorison/Desktop/data/iris.csv' does not exist: b'C://Users/zialecuyermorison/Desktop/data/iris.csv'

```
#### Problem description

I inputted the following code into JupyterLab and I know the path is right and I've tried switching / for \ using // and adding r in front of the C. I still get the following error. I also tried reloading the pandas library. 

#### Expected Output

to pull up the data on Jupyterlab notebook in a table like format hopefully.
![image](https://user-images.githubusercontent.com/51931191/59947558-c1a71280-942a-11e9-94f9-2630ff38fde7.png)

**Comment by WillAyd** [comment]
What happens if you use the builtin `open` function on this?

**Comment by Seemachopra22** [comment]
Please try this:
import pandas as pd
import os
variable = pandas.read_csv(r"C:\Users\zialecuyermorison\Desktop\data\iris.csv")

**Comment by zialecuyer** [comment]
I've tried the open function and it says there's no such file or directory as an error message? maybe my code is off or i'm not formatting the command right..? I am still very new to coding and pretty much trying to teach myself how to use Jupyter labs from scratch. I have also tried doing this:

import pandas as pd
import os
variable = pandas.read_csv(r"C:\Users\zialecuyermorison\Desktop\data\iris.csv")
and get the same original error message. I really appreciate your guy's help I'll keep messing with it and hopefully find something that works!
Thank you

**Comment by Dharni0607** [comment]
@zialecuyer, Please make sure that your path is correct. 

I tired all four ways:

import pandas
variable1 = pandas.read_csv(r"C:/Users/user/Desktop/check/testFile.csv")
variable2 = pandas.read_csv(r"C://Users/user/Desktop/check/testFile.csv")
variable3 = pandas.read_csv(r"C:\Users\user\Desktop\check\testFile.csv")
variable4 = pandas.read_csv(r"C:\\Users\user\Desktop\check\testFile.csv")

And all of them gave correct output:

	value
0	6.7
1	8.3
2	7.9

**Comment by Dharni0607** [comment]
@zialecuyer, Please make sure that your path is correct.

I tired all four ways:

import pandas
variable1 = pandas.read_csv(r"C:/Users/user/Desktop/check/testFile.csv")
variable2 = pandas.read_csv(r"C://Users/user/Desktop/check/testFile.csv")
variable3 = pandas.read_csv(r"C:\Users\user\Desktop\check\testFile.csv")
variable4 = pandas.read_csv(r"C:\Users\user\Desktop\check\testFile.csv")

And all of them gave correct output:

     value
0	6.7
1	8.3
2	7.9

**Comment by vadella** [comment]
easiest way would be to use `pathlib.Path`. It should handle all (sane) variations of /  and \\.

```
from pathlib import Path
input_file = Path("C:/Users/zialecuyermorison/Desktop/data/iris.csv")
assert input_file.exists()
pd.read_csv(input_file)
```

This can happen when the

**Comment by TomAugspurger** [comment]
Closing since this doesn't appear to be an issue with pandas. Feel free to carry on the conversation.
