### ISSUE TITLE
Non-Deep copy for Categorical?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#26995]
Categorical.copy passes `values=self._codes.copy()`, and doesn't have a `deep=False` kwarg (which the base ExtensionArray does).  This is causing trouble in #26954.  Is this intentional @TomAugspurger?

Pandas-internal EAs with `copy` behavior not respecting `deep` kwarg:
- [ ] Categorical (no kwarg at all)
- [ ] DatetimeLike (ignores kwarg)
- [ ] PandasArray

IntegerArray, IntervalArray, and SparseArray look correct.

**Comment by TomAugspurger** [comment]
Probably a bug.

**Comment by jorisvandenbossche** [comment]
In general, we never really properly defined the expected semantics for EA.copy (or exposed it through eg Series.copy) -> https://github.com/pandas-dev/pandas/issues/22314 

Also currently, the default of `deep` is False, but I assume this should actually be True (if you use the same meaning as for Series). Or, we could just remove this keyword altogether for EAs (eg ndarray also has no deep argument)

**Comment by TomAugspurger** [comment]
Agreed that it should be deep by default.

**Comment by jorisvandenbossche** [comment]
Is there a use case for a non-deep one?

**Comment by jreback** [comment]
actually need to be careful with this

we don’t normally deep copy the cells of object array
eg day you have dicts or lists inside a Series cell

as that is not python default behavior

however it has causes some bugs over time

**Comment by jorisvandenbossche** [comment]
@jbrockmendel we don't get notified of edits of the first post, but I think your updated information is relevant for the discussion: basically none of the EAs implement this. 

So before actually starting to implement this, to repeat my previous questions:

- shouldn't `deep=True` be the default?
- is there actually a use case for `deep=False`, or can we just remove this keyword alltogether?

**Comment by jbrockmendel** [comment]
> shouldn't deep=True be the default?

I would be +1 on this.

> is there actually a use case for deep=False, or can we just remove this keyword alltogether?

The only thing that comes to mind is that this is kind of like a view that could be used for some copy-on-write behavior, but if that's the idea then we should just use `view`.  I'd be on board with removing the kwarg.

**Comment by jbrockmendel** [comment]
> is there actually a use case for deep=False, or can we just remove this keyword alltogether?

Come to think of it, we don't have a non-copying `view` method, which would be helpful for `reshape`.

**Comment by jorisvandenbossche** [comment]
@jbrockmendel can you explain a bit more how that would work? (why is a non-copy view needed there?)
