### ISSUE TITLE
Show astype example with dict in docs

### ISSUE THREAD

**Issue by stevennic** [pandas-dev/pandas#26990]
It would be useful to be able to change a column dtype inline.

For example with a DataFrame-level astype() overload:
Assuming `df` has a column called `str_col` that is a string (object),
`df.astype(col='str_col', dtype='int').head()`

The use case that brought me here is to numerically sort a string column without permanently changing it. What I was hoping to do is
`df.astype(col='str_col', dtype='int').sort_values(by='str_col')`

Instead, I had to do this:
`df = df.assign(int_col = lambda x: x['str_col'].astype('int')).sort_values(by='int_col').drop('int_col', axis = 'columns')`

The method would also support dictionaries for multiple column type changes:
`df.astype({'col1':'type1', 'col2':'type2'})`

**Comment by TomAugspurger** [comment]
DataFrame.astype already accepts a dictionary of columns to dtypes, your last form. IMO, accepting `**kwargs` makes sense because it conflicts with other keyword arguments.

**Comment by stevennic** [comment]
I hadn't noticed that! Thanks Tom. I see it in the documentation now, though perhaps it would be good to include at least one code example in the doc showing the dictionary form. I agree it's better to keep it in **kwargs even for one column to keep the method signature streamlined.

**Comment by WillAyd** [comment]
@stevennic improvements to documentation are almost always welcome. Would you like to make a PR?

**Comment by stevennic** [comment]
Sure, that'll be my compensation for taking up resources here :)
