### ISSUE TITLE
AssertionError with DataFrame.from_records() when it should create column of nulls

### ISSUE THREAD

**Issue by d-tork** [pandas-dev/pandas#27003]
https://github.com/pandas-dev/pandas/blob/cb00deb94500205fcb27a33cc1d0df79a9727f8b/pandas/core/frame.py#L1430-L1556

I passed a list of data with 5 columns but a column header list of 6 items. The documentation for `pd.DataFrame.from_records()` says:

> any names not found in the data will become all-NA columns

However, instead I get:
```python
AssertionError: 6 columns passed, passed data has 5 columns
```

If I am interpreting this wrong or using this method the wrong way, I'm welcome to any suggestions too. Code to reproduce: 
```python
>>> import pandas as pd
>>> data = [list(range(1,6))]
>>> data
[[1, 2, 3, 4, 5]]
>>> col_headers = 'A B C D E F'.split()
>>> col_headers
['A', 'B', 'C', 'D', 'E', 'F']
>>> df = pd.DataFrame.from_records(data=data, columns=col_headers)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dtorkelson/miniconda3/envs/branker/lib/python3.7/site-packages/pandas/core/frame.py", line 1512, in from_records
    coerce_float=coerce_float)
  File "/Users/dtorkelson/miniconda3/envs/branker/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 404, in to_arrays
    dtype=dtype)
  File "/Users/dtorkelson/miniconda3/envs/branker/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 436, in _list_to_arrays
    coerce_float=coerce_float)
  File "/Users/dtorkelson/miniconda3/envs/branker/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 492, in _convert_object_array
    con=len(content)))
AssertionError: 6 columns passed, passed data had 5 columns
>>> col_headers.pop(5)
'F'
>>> df = pd.DataFrame.from_records(data=data, columns=col_headers)
>>> df
   A  B  C  D  E
0  1  2  3  4  5
``` 

The extra column name is passed because this code is being used to create many dataframes in a loop, which are being appended to each other. Many have data in the sixth column, but for those that don't, I was hoping (and thinking) that pandas would fill it in with nulls.

**Comment by WillAyd** [comment]
Hmm the documentation would suggest that but I think the documentation if anything is wrong - normal construction doesn't offer this so don't think we would special case `from_records`:

```python
>>> pd.DataFrame([[0, 1]], columns=list('abc'))
ValueError: 3 columns passed, passed data had 2 columns
```

Want to update the docs?

**Comment by d-tork** [comment]
> Want to update the docs?
If you mean dropping that sentence from this class method, I'll give it a try. But I've never done a fork or PR for any public-facing project like this, might take me a while.

**Comment by Seemachopra22** [comment]
This is one of the solutions for the issue:
import pandas as pd
data = list(range(1,6))
print(data)

col_headers = 'A B C D E F'.split()
print(col_headers)
df = pd.DataFrame({'data': pd.Series(data), 'col_headers': pd.Series(col_headers)})
print(df)

**Comment by d-tork** [comment]
Appreciate the try @Seemachopra22, and I'll probably post this on StackOverflow anyway, but one thing missing from your solution is that the data is a _list of_ lists, where each inner list is a row of data. I'm playing around with it now though, perhaps you're onto something.

**Comment by jorisvandenbossche** [comment]
BTW, I don't think the docs suggest that a column of NaNs should be added. The "(any names not found in the data will become all-NA  columns) " is specificaly about the case where the data have names in them.

For example:

```
In [29]: data = [{1: "foo", 2: "bar"}]  

In [30]: pd.DataFrame.from_records(data, columns=[1, 2, 3]) 
Out[30]: 
     1    2   3
0  foo  bar NaN
```

which fits with the documentated behaviour.

For me, what is the actual bug in the original reported example here is that we should not report AssertionErrors to the user. I think it is fine to raise an error if the number of names passed to `columns` does not match the data, but it should be a informative ValueError

**Comment by mroeschke** [comment]
Looks like this raises a ValueError instead of an AssertionError now. Per this comment in the code

```
# GH#26429 do not raise user-facing AssertionError
    raise ValueError(err) from err
```

Closing as this seems addressed
