### ISSUE TITLE
Improve DataFrame.to_string()

### ISSUE THREAD

**Issue by darkdragon-001** [pandas-dev/pandas#27002]
Add the following options:
- Draw borders: specify border characters and which ones to draw _(similar to [texttable](https://pypi.org/project/texttable/))_
  - Allow multi-line cells for long strings instead of truncation (they are visually separated by the borders)
- ~~Use [Markdown table format](https://help.github.com/en/articles/organizing-information-with-tables). This could also be implemented in a separate `to_markdown()` function.~~ _(Duplicate of #11052)_

**Comment by TomAugspurger** [comment]
Can you make your request more explicit? As is, it'll be hard to tell whether this issue is in scope, or when it is closable.

**Comment by darkdragon-001** [comment]
@TomAugspurger I updated the issue. Is it better now?

**Comment by TomAugspurger** [comment]
A `to_markdown()` is discussed in https://github.com/pandas-dev/pandas/issues/11052. That seems to cover all of your usecases, right? I don't think that `to_string` is likely to gain support for delimiters. It's already quite complex.

**Comment by darkdragon-001** [comment]
Thanks for the hint to the `to_markdown()` discussion.

Multi-line cells would still be nice though, but don't make sense without delimiter support.

**Comment by WillAyd** [comment]
Thanks for the suggestion! I'll be frank in that I'm slightly against this as I don't see it being generally super useful for the complexity I think it would add to the code base

**Comment by TomAugspurger** [comment]
I don’t think you can do multilingual without delimiters, so this all sounds like a to_markdown
