### ISSUE TITLE
Support MyPy New Semantic Analyzer

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#27018]
MyPy recently released a new semantic analyzer in v0.710:

https://mypy-lang.blogspot.com/2019/06/mypy-0710-released-new-semantic-analyzer.html

This will likely be the default in the next mypy release so would be good to get a head start on support. This currently causes a few errors in our code base:

```sh
$ mypy --new-semantic-analyzer pandas
pandas/core/arrays/interval.py:574: error: Name 'dtype' already defined on line 129
pandas/core/indexes/timedeltas.py:308: error: Name '_box_func' already defined on line 173
pandas/io/json/__init__.py:5: error: Name 'json' is not defined
pandas/io/json/__init__.py:5: error: Name 'normalize' is not defined
pandas/io/json/__init__.py:5: error: Name 'table_schema' is not defined
```

**Comment by alimcmaster1** [comment]
Interesting I can take a look @WillAyd we can validate in CI too so this doesn't regress between now and next mypy release

**Comment by WillAyd** [comment]
Great!
