### ISSUE TITLE
TST: fixture names for REPL usability

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#27012]
The pytest docs (https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly) suggest a pattern that would make fixturized tests a zillion times less frustrating to troubleshoot when they fail.

Instead of
```
@pytest.fixture
def whatever():
```

We use

```
def whatever():

@pytest.fixture(name="whatever")
def whatever_fixture():
    return whatever()
```

This way, when a test fails, I can recreate it in the repl with

```
from pandas.tests.extensions.test_categorical import *
data = data()
```

instead of having to copy-and-paste the contents of the `data` fixture like a savage.

**Comment by kykosic** [comment]
I can take this if no one else is working on it.
