### ISSUE TITLE
TST: dont break ABCPandasArray checks

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#27014]
Apparently tests.extension.tests_numpy patches PandasArray._typ so as to break all `isinstance(obj, ABCPandasArray)` checks.  Learning this in the process of troubleshooting failing tests is really frustrating.  This is a code smell and should be removed.

**Comment by TomAugspurger** [comment]
Can you clarify? The patch is leaking between tests?

**Comment by jbrockmendel** [comment]
The patch caused a bunch of failures while putting together #27015 (eventually I had to just disable the entire test file).  What is the compelling reason to change the behavior for these tests?

**Comment by jorisvandenbossche** [comment]
> What is the compelling reason to change the behavior for these tests?

Because we currently don't allow actually storing them, I think (and that hack is then a way to test them being stored)

**Comment by jbrockmendel** [comment]
> Because we currently don't allow actually storing them, I think (and that hack is then a way to test them being stored)

So we want to test that if we allow something that we dont allow, then that thing is allowed?

**Comment by TomAugspurger** [comment]
We want to test that PandasArray correctly implements the EA interface, part of which requires allowing it to be stored in a Series / DataFrame.
