### ISSUE TITLE
fillna not throwing error when limit is not positive

### ISSUE THREAD

**Issue by williamma12** [pandas-dev/pandas#27042]
#### Code Sample

```python
import pandas as pd
import numpy as np
# Your code here
NCOLS = 3
NROWS = 50
data = {"col{}".format(int((i - NCOLS / 2) % NCOLS + 1)): np.random.randint(
            -100, 100, size=(NROWS)
        )
        for i in range(NCOLS)
}
df = pd.dataframe(data)
df.fillna(0, limit=-5)
```
#### Problem description

I am currently on pandas 0.24.2 and running the above code does not throw an error even though the limit is less than or equal to zero. This error does not arise when the `data` is made up of floats instead of ints (replace `np.random.randint` with `np.random.uniform`).

#### Expected Output

`ValueError: Limit must be greater than 0`

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Darwin
OS-release: 18.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 4.3.0
pip: 19.0.3
setuptools: 40.8.0
Cython: 0.29.7
numpy: 1.15.0
scipy: 1.2.1
pyarrow: 0.14.0.RAY
xarray: 0.12.0
IPython: 7.3.0
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: 0.2.0
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by TomAugspurger** [comment]
Thanks for the report. The validation should probably occur somewhere around https://github.com/pandas-dev/pandas/blob/c9182df84736ce060c30d386c9f3a97614ca7778/pandas/core/generic.py#L6036.

**Comment by Inevitable-Marzipan** [comment]
@TomAugspurger  I will try and take a look at this, I'm thinking of a change to validate_fillna_kwargs to take an extra argument limit and raise appropriate errors in there.

**Comment by Inevitable-Marzipan** [comment]
I've had a bit of a look and it appears that when randint is used, the fillna method in pandas/core/internals/blocks.py has self._can_hold_na set to false and returns before running the checks on limit, hence not raising the errors. Not entirely sure how _can_hold_na is set but it may have something to do with whether the DataFrame contains any NAs or not, as when I set one element in the above example to np.nan the error is thrown correctly.

**Comment by TomAugspurger** [comment]
We'll want to raise on invalid arguments, even if there aren't / can't be
any missing values.

**Comment by Inevitable-Marzipan** [comment]
I've drilled into it a little bit more and it appears that _can_hold_na is set at the class level and is set to True for FloatBlock and False for IntBlock which is causing the difference in behaviour. I propose a change to the function: 
https://github.com/pandas-dev/pandas/blob/6119d0253e013b31de7d050a52af2226e864d304/pandas/util/_validators.py#L325
such that it takes an additional arugment limit, and performs the necessary checks in there. These checks would be those that are already implemented at 
https://github.com/pandas-dev/pandas/blob/a7f1d69b135bbbf649cf1af9a62d79acb963e47c/pandas/core/internals/blocks.py#L355
Would this make sene?

**Comment by TomAugspurger** [comment]
That seems reasonable.
