### ISSUE TITLE
Inconsistent behavior on aggregate after resample

### ISSUE THREAD

**Issue by rareal** [pandas-dev/pandas#27047]
```python
import pandas as pd
df = pd.DataFrame({'a': range(0, 10), 'b': range(0, 10), 'c': [False, True]*5},
                  index=pd.to_datetime(['01:00', '01:01', '01:02', '01:03', '01:04',
                                        '01:31', '01:32', '01:33', '01:34', '01:35']))
df.resample('15min').agg({'a': 'sum', 'b': 'mean', 'c': 'first'})
# Out[5]: 
#                       a    b    c
# 2019-06-26 01:00:00  10  2.0  0.0
# 2019-06-26 01:15:00   0  NaN  NaN
# 2019-06-26 01:30:00  35  7.0  1.0
```
#### 

One problem I think is the creation of the empty group (01:15), but if `sum` would produce `nan` as does `mean` and `first` it would be easily solved with `dropna` after, but `sum` produces zeros. It's obviously more annoying if the column contains zeros before resampling.

Is there a simple way to include a parameter in resample or aggregate to avoid the empty group creation in this case?

As a small note, why does `first` converts `bool` to `int`? I'd think it should keep the output as `bool`.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.24.2
pytest: None
pip: 19.1.1
setuptools: 41.0.1
Cython: 0.29.10
numpy: 1.16.4
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.5.0
sphinx: None
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: 3.5.2
numexpr: 2.6.9
feather: None
matplotlib: 3.1.0
openpyxl: None
xlrd: 1.2.0
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: 4.7.1
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by jreback** [comment]
this is by-definition for what resample & sum do. resample gives you all intervals whether there are points are not and as of 0.22.0, sum will return 0 even in the presence of all-NaN. you can control this with the ``min_count`` kwarg.

```
In [2]: df.resample('15min').agg({'a': lambda x: x.sum(min_count=1), 'b': 'mean', 'c': 'first'})
Out[2]: 
                        a    b    c
2019-06-26 01:00:00  10.0  2.0  0.0
2019-06-26 01:15:00   NaN  NaN  NaN
2019-06-26 01:30:00  35.0  7.0  1.0
```

**Comment by jreback** [comment]
``bool`` is upcast to float in the prescence of NaNs currently (eventually when we have a Bool type this may work as excepted)
