### ISSUE TITLE
ENH: add Series.set_index

### ISSUE THREAD

**Issue by pilkibun** [pandas-dev/pandas#27058]
```python
import pandas as pd
 
dates=[
"2001-01-01 23:50",
"2001-01-02 14:00", 
"2001-01-03 00:08"] 
 
ser=pd.Series(range(3),pd.DatetimeIndex(dates))
```

sometimes when writing a sequence of operation, you want to replace the index of the object you're working on. Say, quantizing the dates. I can't find the .method way of doing
``
ser.index= expr
``
So that I can't write something like
```
(ser
      .replace_index(ser.index.floor("D"))    # < this doesn't exist
      .rolling("5d")
       .sum()
```

Things that don't solve this:
- `reindex` is aligning, so if your new index permutes the indexes, it isn't suitable. 
- `set_index` <del>takes a column name, not an expression</del>, and isn't available on series. **update** works for frames, though you must provide an arraylike, not a listlike.
- `reindex_like` expects a PandasObject instead of a listlike, and is aligning
- `reset_index` does not take a values argument

```
In [1]: [_ for _ in dir(ser) if 'index' in _ and not _.startswith("_")]
Out [1]: 
['first_valid_index',
 'index',
 'last_valid_index',
 'reindex',
 'reindex_axis',
 'reindex_like',
 'reset_index',
 'sort_index']
```

**Comment by Liam3851** [comment]
You can do this in a chain now by converting the Series to DataFrame, using `set_index`, and then converting back to Series, since `DataFrame.set_index` accepts an arraylike to use as the new index:

```python
In [21]: ser.to_frame() \
    ...:    .set_index(ser.index.floor('D')) \
    ...:    .iloc[:, 0] \
    ...:    .rolling('5D') \
    ...:    .sum()
    ...:
Out[21]:
2001-01-01    0.0
2001-01-02    1.0
2001-01-03    3.0
Name: 0, dtype: float64
```

Perhaps there is a case for `set_index` on Series that would provide the arraylike functionality of `DataFrame.set_index` without requiring conversion to/from DataFrame?

**Comment by pilkibun** [comment]
Thanks, you're right. I updated the OP.

**Comment by pilkibun** [comment]
It turns out that the `set_axis` method has existed since 0.21 for doing this, but it seems it's not very well-known. That solves my problem. I've opened a PR to add a comptabile `series.set_index` to be immediately deprecated and redirecting to `set_axis`. We'll see if that gets anywhere.

Closing for now, as this is a dupe of #21684, even though that issue has become scorched earth.
