### ISSUE TITLE
Feature request: make read_parquet support reading a list of paths

### ISSUE THREAD

**Issue by dclong** [pandas-dev/pandas#27069]
Currently `pandas.read_parquet` supports reading either a parquet file or all parquet files under a directory. It would be great if it supports reading a list of paths (to parquet files).

**Comment by TomAugspurger** [comment]
Note that none of our readers support lists of arguments, or glob patterns.

If possible, I would prefer we design an API and semantics that work well
for all readers. We don't need
to implement them all at once, but it'd be nice to aim for consistency
ahead of time.

Many of the options in `read_csv` will need to be re-examined in a
multi-file context (nrows, chunksize, etc).

**Comment by mroeschke** [comment]
We have an existing issue regarding a similar issue for other IO methods (will link it when I can find it). But agreed this should be ideally generalized if supported. Closing as I think we have another issue that discusses this further
