### ISSUE TITLE
DOC/TST: provide documentation & testing on groupby filtering & aggregation ops for EA

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#27078]
#27071 allows for the preservation dtype for filtering type of ops in groupby (first, last, min, max). This *should* work for all EA (though was fixing Categorical).

We should

- test all EA more generally for groupby filtering type ops & potentially other aggregations
- document what works / what doesn't work.

**Comment by kidrahahjo** [comment]
@jreback will it be okay to close this issue? Or some work is required to be done here?

**Comment by jreback** [comment]
yep i think this is good
