### ISSUE TITLE
DEPR: msgpack

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#27084]
msgpack uses the internal format on the wire. this makes for *only* pandas producers and consumers, but with ``pyarrow`` support now fully handling this case (and better performing), it is time to deprecate msgpack.

**Comment by UlionTse** [comment]
😂 
`Deprecated since version 2.0: The custom serialization functionality is deprecated in pyarrow 2.0, and will be removed in a future version. Use the standard library pickle or the IPC functionality of pyarrow (see Streaming, Serialization, and IPC for more).`

**Comment by chuongmep** [comment]
> 😂 `Deprecated since version 2.0: The custom serialization functionality is deprecated in pyarrow 2.0, and will be removed in a future version. Use the standard library pickle or the IPC functionality of pyarrow (see Streaming, Serialization, and IPC for more).`

so what is good format to follow with pandas library now ?

**Comment by UlionTse** [comment]
@chuongmep https://arrow.apache.org/docs/python/pandas.html

**Comment by chuongmep** [comment]
@UlionTse , but we can't save mutiple dataframe to one file.
