### ISSUE TITLE
Enhancement: The shift function should have an optional argument allowing to extend the dataframe i.e. for forecasts

### ISSUE THREAD

**Issue by KIC** [pandas-dev/pandas#27091]
I believe using pandas dataframes to work with forecasts is a pretty standard use case. Therefore I am missing a convenient method to extend the dataframe in its length while shifting, instead of loosing values. Currently the only way to do this is something like:

```python

    df_ext = pd.DataFrame(index=pd.date_range(df.index[-1], periods=8, closed='right'))
    df2 = pd.concat([df, df_ext], axis=0, sort=True)
    df2["forecast"] = df2["some column"].shift(7)

```

My proposal would be to add an extra argument to the shift function i.e. something along the lines:

```python
df["x"].shift(7, inplace=True, extend_index_freq='D')
```

**Comment by WillAyd** [comment]
Extending something inplace seems pretty perilous - do you have a minimal data sample you can provide here to show expected inputs and outputs?

**Comment by KIC** [comment]
the current situation is:
```
import pandas as pd
import numpy as np
df = pd.DataFrame({"some_value": np.arange(0.1, 10)}, index=pd.date_range('2019-01-01', periods=10))
df["some_value_shifted"] = df["some_value"].shift(2)

df

	some_value	some_value_shifted
2019-01-01	0.1	NaN
2019-01-02	1.1	NaN
2019-01-03	2.1	0.1
2019-01-04	3.1	1.1
2019-01-05	4.1	2.1
2019-01-06	5.1	3.1
2019-01-07	6.1	4.1
2019-01-08	7.1	5.1
2019-01-09	8.1	6.1
2019-01-10	9.1	7.1
```

What I would need is that the values do not get lost, which can be achieved by this workaround:
```
import pandas as pd
import numpy as np

shifted = 2
df = pd.DataFrame({"some_value": np.arange(0.1, 10)}, index=pd.date_range('2019-01-01', periods=10))

# workaround for a functionality which should be provided
df_ext = pd.DataFrame(index=pd.date_range(df.index[-1], periods=shifted))
df = pd.concat([df, df_ext], axis=0, sort=True)
df["some_value_shifted"] = df["some_value"].shift(shifted)

df

	some_value	some_value_shifted
2019-01-01	0.1	NaN
2019-01-02	1.1	NaN
2019-01-03	2.1	0.1
2019-01-04	3.1	1.1
2019-01-05	4.1	2.1
2019-01-06	5.1	3.1
2019-01-07	6.1	4.1
2019-01-08	7.1	5.1
2019-01-09	8.1	6.1
2019-01-10	9.1	7.1
2019-01-10	NaN	8.1
2019-01-11	NaN	9.1
```

**Comment by WillAyd** [comment]
Hmm OK I see. shift is generically a transforming function, the goal of which is to match back to the original index. I'm not sure this would fit the goals of that function.

Your "workaround" is a pretty good solution

**Comment by WillAyd** [comment]
@KIC you may also be interested in the `DataFrame.tshift` function

**Comment by mroeschke** [comment]
Thanks for the suggestion but agreed the workaround solution is pretty idiomatic and this keyword would be pretty niche. Since this enhancement hasn't gotten a lot of traction from the community or other core devs, going to close. Happy to reopen if this get more traction
