### ISSUE TITLE
Clean Up Testing of Excel Engine Option Setting for Readers/Writers

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#27096]
Follow up to this https://github.com/pandas-dev/pandas/pull/25092#issuecomment-506752805

Right now for readers we test directly setting `engine=` as a keyword argument, whereas in the writer tests we set the global option. I *think* we should consistently set the keyword argument and simply have a test on both reading / writing that setting the option will actually trigger that keyword argument to improve coverage and keep things simple

**Comment by jbrockmendel** [comment]
Has this been addressed?  IIRC we did quite some refactoring of excel tests in late 2019

**Comment by WillAyd** [comment]
It's open ended - let's close for now can come back if there's something concretely actionable
