### ISSUE TITLE
Change in column name creates an empty output for wide_to_long function

### ISSUE THREAD

**Issue by SelvaSathappan** [pandas-dev/pandas#27093]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame({'person_id' :[1,2,3],'date1': 
['12/31/2007','11/25/2009','10/06/2005'],'val1': 
[2,4,6],'date2': ['12/31/2017','11/25/2019','10/06/2015'],'val2':[1,3,5],'date3': 
['12/31/2027','11/25/2029','10/06/2025'],'val3':[7,9,11]})


pd.wide_to_long(df, stubnames=['date', 'val'], i='person_id', 
j='grp').sort_index(level=0)
```
#### Problem description

winde_to_long retruns zero output when I change the column name format. The same code works when I have a different column name format. Please refer this post in SO for more details on list of column names that you can try. Replace the sample column names given in code with the column names in screenshot

https://stackoverflow.com/questions/56807104/wide-to-long-returns-empty-output-python-dataframe?noredirect=1#comment100169905_56807104

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by TomAugspurger** [comment]
Hard to say from the example, but it looks like you're issue is that you have names like `<col>_00<d>`. IIRC wide_to_long uses a regex to identify groups so the leading 0s may mess up the default.

We can reopen if you provide a [minimal example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)
