### ISSUE TITLE
API: Add NDFrame property to disallow duplicates

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#27108]
edit: see https://github.com/pandas-dev/pandas/issues/27108#issuecomment-527633246

---

I'd like to be able to have an index, and ensure that no operation introduces duplicates.

```python
idx = pd.Index(..., allow_duplicates=False)
s = pd.Series(..., index=idx)
```

From here, any pandas operation that introduces duplicates (e.g. `s.loc[['a', 'a']]`) would raise, rather than return an Index with two values.

**Comment by jorisvandenbossche** [comment]
Discussion we had about this: should this "property" live on the Index, or on the DataFrame/Series object?

**Comment by TomAugspurger** [comment]
Yeah, my example kinda exposes that difficulty, as the new index in `s.loc[['a', 'a']]` isn't the original index. So maybe it would be better on the dataframe?

**Comment by TomAugspurger** [comment]
I played with this a bit today.

For a user-API, I think it makes the most since to have an `allow_dupcliate_labels` keyword that can be passed to Series / DataFrame. IOW,

```python
>>> pd.Series(data, index, allow_duplicate_labels=False)
```

rather than

```python
>>> pd.Series(data, pd.Index(..., allow_duplicate_labels=False))
```

While the duplicate detection is done in the Index, it seems more ergonomic to have it on NDFrame.

A potential downside is that you can't disallow duplicates in the columns while allowing duplicates in the index. If we really wanted that, we can support setting `allow_duplicate_labels=True/False/rows/columns`. But let's leave that aside for now.

---

For an implementation, it seems like `metadata` offers a non-invasive solution. Without having to touch `rename`, the following is possible

```python
In [1]: import pandas as pd

In [2]: df = pd.DataFrame(index=['a', 'A'], allow_duplicate_labels=False)

In [3]: df
Out[3]:
Empty DataFrame
Columns: []
Index: [a, A]

In [4]: df.rename(str.upper)
---------------------------------------------------------------------------
DuplicateLabelError                       Traceback (most recent call last)
<ipython-input-4-17c8fb0b7c7f> in <module>
----> 1 df.rename(str.upper)

~/sandbox/pandas/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    233         @wraps(func)
    234         def wrapper(*args, **kwargs) -> Callable[..., Any]:
--> 235             return func(*args, **kwargs)
    236
    237         kind = inspect.Parameter.POSITIONAL_OR_KEYWORD

...

~/sandbox/pandas/pandas/core/indexes/base.py in _maybe_check_unique(self)
    562             # TODO: position, value, not too large.
    563             msg = "Index has duplicates."
--> 564             raise DuplicateLabelError(msg)
    565
    566     # --------------------------------------------------------------------

DuplicateLabelError: Index has duplicates.

```

Likewise for `concat`, `__getitem__`, `.loc`, etc. These all call `__finalize__`. Since I think we want propagation by default, it does exactly what we want.

The changes are at https://github.com/pandas-dev/pandas/compare/master...TomAugspurger:unique-index?expand=1, but all I've needed so far is

1. Adding `allow_duplicate_labels` to the NDFrame constructors
2. Adding a getter / setter `NDFrame.allows_duplicate_labels`
3. Adding `allows_duplicate_labels` to the `NDFrame._metadata`

**Comment by TomAugspurger** [comment]
This was closed by https://github.com/pandas-dev/pandas/pull/28394.
