### ISSUE TITLE
Add Index.__array_ufunc__

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#27133]
We can probably move `Series.__array_ufunc__` to `core/base.py` (once it's in)

The primary difference is that `ufunc(Index, Series)` should defer to `Series` by returning NotImplemented. This may be as easy as excluding `Series` from `Index._HANDLED_TYPES` and including `Index` in `Series._HANDLED_TYPES`.

**Comment by simonjayhawkins** [comment]
closing in favour of #32411
