### ISSUE TITLE
BUG: Timedelta repr doesn't show nano

### ISSUE THREAD

**Issue by pilkibun** [pandas-dev/pandas#27134]
xref #9309, though that's about consistency, not just missing info.

```python
In [7]: pd.Timedelta(nanoseconds=1)
Out[7]: Timedelta('0 days 00:00:00.000000')

In [8]: pd.Timestamp("2000-01-01")-pd.Timedelta(nanoseconds=1)
Out[8]: Timestamp('1999-12-31 23:59:59.999999999')
```

@jorisvandenbossche, recall we discussed using "roles" for repr? this might be a good use case, considering https://github.com/pandas-dev/pandas/issues/9309#issuecomment-70958154.

**Comment by jorisvandenbossche** [comment]
Closing as a duplicate, and renamed https://github.com/pandas-dev/pandas/issues/9309 to make it clear that it is about timedelta no showing nanoseconds

> recall we discussed using "roles" for repr? this might be a good use case, considering #9309 (comment).

Yes, although here it is more related to the fact that for Series/Index we need to define the resolution for the full series, not per formatting the individual scalars (which is already what is happening right now, but it would be good to generalize this for EAs).
