### ISSUE TITLE
INT: the json C code should not deal with blocks

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#27164]
PR https://github.com/pandas-dev/pandas/pull/26409 introduced a `get_block_values` to get the values of the Block, used in https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/src/ujson/python/objToJSON.c

Ideally, the JSON C code should not deal with blocks (eg by converting to a numpy array before passing the data to the C code).

So to do item for this issue: update the JSON code so the call from objToJSON.c to `get_block_values` can be removed.

**Comment by WillAyd** [comment]
Took a look and I think getting rid of this really simplifies the code. Have one failure I haven't seen yet and need to check for memory leaks but will post a PR for you to review

**Comment by jbrockmendel** [comment]
+1 on this idea.  IIRC there was a discussion a few months ago about trying to get internals out of the ujson code and the conclusion was "wait and see if we can use the arrow parser instead".  Since the latter is a non-starter for the moment, making this code more maintainable would be great.

**Comment by jbrockmendel** [comment]
just noticed that get_block_values is just an alias for get_values.  Any reason not to just use get_values (until block usage can be removed entirely)?

**Comment by jorisvandenbossche** [comment]
Experiments of @WillAyd related to this: https://github.com/pandas-dev/pandas/pull/27166, https://github.com/pandas-dev/pandas/pull/32343
