### ISSUE TITLE
good to have bin size option for pandas value_counts function

### ISSUE THREAD

**Issue by rahulparmar21** [pandas-dev/pandas#27176]
New Feature Request: good to have bin size option for pandas value_counts function

Use Case: Most of the times it's hard to determine the number of bins that would  fit my data uniformly. Instead if I pass the bin size, based on bin size the function should determine how many bins must be created for the data.

Ex: If my data ranges from 0-100 and if I pass bin size as 2 the function must return a pandas series of 50 bins starting from 0. for ex: 0 and 1 would be in bin1 and so on.

**Comment by jreback** [comment]
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.cut.html?highlight=cut#pandas.cut
