### ISSUE TITLE
DOC: Parameters name and fastpath of Series are not documented

### ISSUE THREAD

**Issue by timhoffm** [pandas-dev/pandas#27178]
#### Problem description

At https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html
the parameters *name* and *fastpath* are not explained.

*Edit*: See #20110 for *fastpath* - at least a short note "deprecated" or "to be deprecated" or "internal only" would help that users don't have to bother with this parameter.

**Comment by TomAugspurger** [comment]
A PR documenting `name` would be great.

We'll need to look at how we document fastpath elsewhere. It's internal-only / deprecated I think.

**Comment by Adam-Klaum** [comment]
Happy to take a shot at this if that's ok.

**Comment by rmunjal29** [comment]
https://github.com/pandas-dev/pandas/pull/27964

**Comment by mroeschke** [comment]
Looks like this was closed by https://github.com/pandas-dev/pandas/pull/27964
