### ISSUE TITLE
Older Pandas dep pulling in newest Numpy that is py2 incompat

### ISSUE THREAD

**Issue by Chris2048** [pandas-dev/pandas#27206]
## Problem description

I have the following dep listed in my py2 project on a LINUX machine:
> pandas==0.17.1

Since Pypi has no linux wheels until pandas v0.18.1 ( https://pypi.org/simple/pandas/ ),
pip install -r <reqs>
Will download and attempt to build pandas from source.

I have numpy 1.16.4 installed, but get this error:

> run_setup
> ...
>   File "/tmp/easy_install-cXiZ1Y/numpy-1.17.0rc1/setup.py", line 31, in <module>
>     from setuptools import setup, Command
> RuntimeError: Python version >= 3.5 required.

I believe that the pandas build is pulling in numpy itself in order to build numpy/pandas binaries from source (correct?), rather than use the installed numpy version.

HOWEVER, it pulls in the latest numpy, which ASOF is numpy-1.17.0r, where 1.17 is the first numpy to drop support for py27.

If my assumptions are correct, is it possible to set a numpy "max_version" to prevent the py27 incompatible numpys from being pulled in for older pandas being built on py27?

**Comment by TomAugspurger** [comment]
I think this is something that pyproject.toml would fix for new releases. Nothing we can do about 0.17.1.

When not using pyproject.toml, I believe the recommendation from the PyPA is to manually install the correct version of numpy first.

Closing in favor of https://github.com/pandas-dev/pandas/issues/20775.
