### ISSUE TITLE
CLN: Revert internal CategoricalDtype.ordered -> CategoricalDtype._ordered references 

### ISSUE THREAD

**Issue by jschendel** [pandas-dev/pandas#27203]
xref https://github.com/pandas-dev/pandas/pull/26403#discussion_r299144624

This will need to be done as part of the process for changing the default value of `CategoricalDtype.ordered` from `None` to `False`, which should be part of the 1.0 release.  Opening this issue to serve as a reminder.

**Comment by TomAugspurger** [comment]
@jschendel are you likely to have time for this for 1.0?

**Comment by jschendel** [comment]
Yes, I can do this for 1.0
