### ISSUE TITLE
Why does pandas dataframe.var() method return unbiased variance by default??

### ISSUE THREAD

**Issue by YuhkiYano** [pandas-dev/pandas#27202]
Why does pandas dataframe.var() method return "unbiased variance" by default?
I think variance implies "sample variance" in general.
Off course, I know this method can return "sample variance" if we provide ddof=0 option.
However, this setting option is very confusing. 
Why don't you add new methods sample_var() and unbiased_var() or return "sample variance" by default?
Other data analysis OSS such as numpy, R and so on, their method return "sample variance" by default.
I think pandas is outstanding library for data analysis with Python! Therefore, I would like to know about this confusing specification.

**Comment by jorisvandenbossche** [comment]
As far as I know, the `var` method in pandas does calculate the sample variance (it has a default of `ddof=1`, `providing `ddof=0` gives you the population variance). This is equivalent with the default behaviour of `var` in R (it does contrast with numpy, though, that uses `ddof=0` by default).

**Comment by YuhkiYano** [comment]
@jorisvandenbossche 
Thank you very much for your comment.
You mean var() method of pandas return
![image](https://user-images.githubusercontent.com/30323722/60625053-b63bea00-9e21-11e9-8f73-e13108ce9d21.png)
by default??

As far as I know, this method return
![image](https://user-images.githubusercontent.com/30323722/60625254-2e0a1480-9e22-11e9-980e-5e1ec63ca37f.png)
"unbiased variance" by default.
This means unbiased estimator of population variance.

**Comment by jorisvandenbossche** [comment]
> As far as I know, this method return "unbiased variance" by default. This means unbiased estimator of population variance.

And this is the "sample variance" you are asking for (and which is the same as the default in R). 

(closing as this is not something to fix in pandas, but feel free to ask for further clarification. Or indicate what can be improved in the docs to make this clearer)

**Comment by YuhkiYano** [comment]
@jorisvandenbossche 
OK, I understand thank you.
