### ISSUE TITLE
The release notes link for v0.25.0rc0 release announcement is broken

### ISSUE THREAD

**Issue by a-marinin** [pandas-dev/pandas#27225]
**Title**: The "release notes" link for v0.25.0rc0 release announcement is broken
**Version**: v0.25.0rc0 pre-release
**Steps to reproduce**:
1. Open your browser,
2. Navigate to pandas releases page (https://github.com/pandas-dev/pandas/releases),
3. Click on the "release notes" link for the v0.25.0rc0 pre-release.

**Actual results**: 404 Not Found (https://pandas.pydata.org/pandas-docs/version/0.25/whatsnew/v0.25.0.html)

**Expected results**: The release notes for the v0.25.0rc0 should be shown.

![image](https://user-images.githubusercontent.com/33235310/60656808-d76bfd00-9e58-11e9-9c30-104c7373ce02.png)

**Comment by simonjayhawkins** [comment]
@a-marinin Thanks for the report.

i think the docs will get created later today https://github.com/pandas-dev/pandas/issues/24950#issuecomment-508339437 @TomAugspurger

**Comment by TomAugspurger** [comment]
I haven't pushed the docs yet. Will do later today or tomorrow.
