### ISSUE TITLE
Wish: Write support for Open Document Spreadsheet (ODS)

### ISSUE THREAD

**Issue by solstag** [pandas-dev/pandas#27222]
Ni!

This is a follow up to #2311 which has been closed after read support was implemented in  #25427 .

People whose work flow involve outputting ODS files would benefit from write support.

.~´

**Comment by LakshyAAAgrawal** [comment]
Hey..
I would like to contribute to this issue, if somebody could guide me on the steps to be undertaken.

**Comment by roberthdevries** [comment]
take
