### ISSUE TITLE
Preserve data types in pandas.DataFrame.mean()

### ISSUE THREAD

**Issue by darkdragon-001** [pandas-dev/pandas#27234]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame([[1,1+1j,True],[1,0,False],[1,1j,True]])
df.mean()
```

#### Received output

```
0                                      (1+0j)
1    (0.3333333333333333+0.6666666666666666j)
2                     (0.6666666666666666+0j)
dtype: complex128
```

#### Expected output

```
0                                           1
1    (0.3333333333333333+0.6666666666666666j)
2                          0.6666666666666666
dtype: object
```

#### Problem description

When `mean()` is applied column-wise it should handle data types column-wise.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Linux
OS-release: 5.0.0-20-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: None
pip: 19.1
setuptools: 41.0.1
Cython: 0.29.7
numpy: 1.15.4
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.5.0
sphinx: None
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: None
numexpr: 2.6.9
feather: None
matplotlib: 3.0.3
openpyxl: None
xlrd: 1.2.0
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: 4.7.1
html5lib: None
sqlalchemy: 1.3.3
pymysql: None
psycopg2: None
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by TomAugspurger** [comment]
Same as https://github.com/pandas-dev/pandas/issues/27185

**Comment by TomAugspurger** [comment]
Closing in favor of https://github.com/pandas-dev/pandas/issues/27185
