### ISSUE TITLE
Line Length Specification in Contributing Documentation

### ISSUE THREAD

**Issue by WillKoehrsen** [pandas-dev/pandas#27232]
Reading the [contributing documentation section on pep8](https://github.com/pandas-dev/pandas/blob/master/doc/source/development/contributing.rst#python-pep8), I noticed the acceptable line-length for Python code is given as 79 characters as [specified in pep8](https://www.python.org/dev/peps/pep-0008/#maximum-line-length). 

> we restrict line-length to 79 characters to promote readability

However, looking at setup.cfg, I see that the maximum line length is [specified as 88 characters](https://github.com/pandas-dev/pandas/blob/master/setup.cfg#L15) and flake8 is set up to ignore line length errors. 

```
[flake8]
max-line-length = 88
ignore =
    E501,  # longer line length
```

Is the contributing documentation out-of-date, or am I making an incorrect interpretation of `setup.cfg`?

**Comment by jreback** [comment]
setup.cfg should be changed (this was changed previously but not changed back), PR welcome

black enforces this now so the flake check doesn’t really do anything (for like length)

**Comment by jorisvandenbossche** [comment]
I opened https://github.com/pandas-dev/pandas/issues/27226 for updating the contributing guide (and initial PR: https://github.com/pandas-dev/pandas/pull/27233)
