### ISSUE TITLE
ENH: Ignore flattening certain keys in `json_normalize`

### ISSUE THREAD

**Issue by bhavaniravi** [pandas-dev/pandas#27241]
Sub issue of #23843 

#### Code Sample, a copy-pastable example if possible

```python
data = [{"CreatedBy":{"Name": "User001"}, 
        "Lookup":{"TextField":"Some text"},
        "Image":{"a":"b"}}]
json_normalize(data).to_json(orient="records")
```
#### Current Output
```
[{"CreatedBy.Name":"User001",
"Image.a":"b",
"Lookup.TextField":"Some text"}]
```
#### Problem description

A usecase where I don't want to flatten they dict under the key `Image`

#### Expected Output

```
[{"CreatedBy.Name":"User001",
"Image:{a":"b}",
"Lookup.TextField":"Some text"]
```

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
pandas: 0.23.4
pytest: None
pip: 18.1
setuptools: 39.1.0
Cython: None
numpy: 1.15.1
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

**Comment by bhavaniravi** [comment]
I would like to contribute the same as I did for #26876

**Comment by WillAyd** [comment]
Sounds good - PRs welcome!

**Comment by mroeschke** [comment]
Thanks for the request, but it appears this feature request hasn't gain much traction in years so closing
