### ISSUE TITLE
how can i read 'null' as a real str in read_excel

### ISSUE THREAD

**Issue by 394659383** [pandas-dev/pandas#27240]
#### Code Sample, a copy-pastable example if possible

```python
na_values = pandas.io.common._NA_VALUES.difference({'null','NULL'})
excelbook = pandas.read_excel(configpath,sheet_name=sheetIndex,index_col=False,na_values=na_values)
```
#### Problem description
there's a word 'null' in my excel file.but it become a NaN when pandas read it out.
then i cut 'null' from my own na_values and used it at pandas.read_excel,but it seems like it is invalid in read_excel because it still changed 'null' to NaN in result.

Dose it is a bug or i used it at a wrong way?

my environment:
python version:3.7.3
pandas version:0.24.2
system:windows7

Received output:
0 ......
1 ......
2 ......
3 ......
4 [1 5 '25' nan 10000 100000 25 1000]

Expected output:
0 ......
1 ......
2 ......
3 ......
4 [1 5 '25' 'null' 10000 100000 25 1000]

**Comment by WillAyd** [comment]
You probably want to use `keep_default_na=False` as well

Closing as this board is reserved for bug reports and enhancement requests. For future usage questions please use StackOverflow
