### ISSUE TITLE
Broken usage of NDFrameIndexer in geopandas

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#27258]
xref https://github.com/pandas-dev/pandas/pull/27223#issuecomment-508828776

The change in that PR broke a test in geopandas. We are using some indexing internals in geopandas that were relying on an InvalidIndexError being catched there (and the PR changed it to only TypeError and KeyError.

A small reproducible example without needing geopandas (but it is dummy code, not doing something useful):

```
from pandas.core.indexing import _NDFrameIndexer

class _CoordinateIndexer(_NDFrameIndexer):

    def _getitem_tuple(self, tup):
        obj = self.obj
        xs, ys = tup
        return obj[xs][ys]

pd.Series._create_indexer('cx', _CoordinateIndexer)

s = pd.Series(range(5))
s.cx[:, :]
```

The below passes on 0.24.2, but gives an error now on master.

The actual code in geopandas is:

https://github.com/geopandas/geopandas/blob/7c66c93f0f76de53615c02810e817ef57fb6a8de/geopandas/base.py#L734-L761

I know this is quite internal code of pandas that is being used here, so we should think about making this cleaner, but short term it would be nice to fix this.

**Comment by jbrockmendel** [comment]
Could we come up with a just-pandas test case where we should catch InvalidIndexError there?

**Comment by jorisvandenbossche** [comment]
With `ix` it seems possible. With the Series from above, `s.ix[:, :]` should give a "too many indexers" error (which it does not 0.24.2), but now gives InvalidIndexError. But yeah, since we are going to remove ix, that's also not a very good test :) 

All the other indexers override this base `__getitem__`, so I don't there is anything else than ix in pandas that uses it.

**Comment by topper-123** [comment]
@jorisvandenbossche Is there a status on this? I'm working on #30690, where ideally I'd like to remove the ``_create_index`` method.
