### ISSUE TITLE
pandas 0.24.2 problem on python 3.4.8: 'colletions' has no attribute 'abc' in pandas/combat/__init__.py line 139.

### ISSUE THREAD

**Issue by Chayeen** [pandas-dev/pandas#27263]
#### Code Sample

```python
import pandas as pd
path = "./demo.dat"
data = pd.read_table(path,header=None,names=["id","label2","text"],sep='\s+')
```
#### Problem description
I install pandas 0.24.2 in Python 3.4.8. When I just import pandas, there is a bug. I open the `/usr/lib64/python3.4/site-packages/pandas/compat/__init__.py` and find something wrong.
I download the source file from [https://pypi.org/project/pandas/#files](https://files.pythonhosted.org/packages/b2/4c/b6f966ac91c5670ba4ef0b0b5613b5379e3c7abdfad4e7b89a87d73bae13/pandas-0.24.2.tar.gz) and check again. The code are same.
Finally, I modify the `/usr/lib64/python3.4/site-packages/pandas/compat/__init__.py` and delete the `abc`. The code run well.

![image](https://user-images.githubusercontent.com/33770463/60758160-7a359e80-a046-11e9-9cbd-a1c42ce699e3.png)
![image](https://user-images.githubusercontent.com/33770463/60758187-e1535300-a046-11e9-8175-7fe9b81d9f30.png)
![image](https://user-images.githubusercontent.com/33770463/60758190-f03a0580-a046-11e9-96f7-f0c43bbed2f8.png)
![image](https://user-images.githubusercontent.com/33770463/60758219-5030ac00-a047-11e9-9ee6-bedaa09fb204.png)
![image](https://user-images.githubusercontent.com/33770463/60758165-91748c00-a046-11e9-8ffd-60581115a932.png)

**I don't know why. Is there something wrong?**

**Comment by jreback** [comment]
python 3.4 is not supported in 024.x

IIRC 0.23.4 should work or update your python

**Comment by KAROUIHAMZA** [comment]
I don't understand how you change the support for Py3.4 without any announcement or changing in version. This is not acceptable for a library used in some cases in production. Learn devOps guys !

**Comment by jreback** [comment]
actually this was dropped quite a while: https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.21.0.html#dependencies-have-increased-minimum-versions

@KAROUIHAMZA we have kept support around for older version for quite a long time. I am not sure how you expect to have a newer version of pandas on a python version that is quite old w/o paid support.

**Comment by jorisvandenbossche** [comment]
Additionally, this is properly set in setup.py, so if you use pip, it should refuse to install those recent versions of pandas on old pythons.
