### ISSUE TITLE
pd.DataFrame.append sort=True does not sort columns

### ISSUE THREAD

**Issue by cryptobhc** [pandas-dev/pandas#27290]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
df = pd.DataFrame({'a':1}, index = [1]) 
print(df.append(pd.DataFrame(data={'a':0}, index=[0]), sort=False))
print(df.append(pd.DataFrame(data={'a':0}, index=[0]), sort=True))

```

#### Problem description

The sort kwarg in pd.DataFrame.append does not provide any sorting, regardless of the boolean value which it is assigned. 

#### Expected Output
sort=True:
    a
0  0
1  1

sort=False:
    a
1  1
0  0

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-52-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.24.2
pytest: 4.5.0
pip: 19.1.1
setuptools: 41.0.1
Cython: 0.29.7
numpy: 1.16.3
scipy: 1.2.1
pyarrow: None
xarray: 0.12.1
IPython: 7.5.0
sphinx: 2.0.1
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: 1.2.1
tables: None
numexpr: 2.6.8
feather: None
matplotlib: 3.0.3
openpyxl: 2.6.2
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.8
lxml.etree: 4.3.3
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.3.3
pymysql: None
psycopg2: 2.7.6.1 (dt dec pq3 ext lo64)
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by Liam3851** [comment]
From the [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.append.html):

> 
> sort : boolean, default None
> Sort columns if the columns of self and other are not aligned. The default sorting is deprecated and will change to not-sorting in a future version of pandas. Explicitly pass sort=True to silence the warning and sort. Explicitly pass sort=False to silence the warning and not sort.
> 
> New in version 0.23.0.
> 

The sort parameter sorts column names. It has no effect here because you only have one column.

```python
In [3]: import pandas as pd
   ...: df = pd.DataFrame({'b':1}, index = [1])
   ...: print(df.append(pd.DataFrame(data={'a':0}, index=[1]), sort=False))
   ...: print(df.append(pd.DataFrame(data={'a':0}, index=[1]), sort=True))
   ...:
     b    a
1  1.0  NaN
1  NaN  0.0
     a    b
1  NaN  1.0
1  0.0  NaN
```

**Comment by cryptobhc** [comment]
In append, sort is passed to concat
https://github.com/pandas-dev/pandas/blob/cb00deb94500205fcb27a33cc1d0df79a9727f8b/pandas/core/frame.py#L6692
It is then passed via _Concatenator to _get_objs_combined_axis
https://github.com/pandas-dev/pandas/blob/c64c9cb44222a42f7b02d4d6007919cd0645f1be/pandas/core/reshape/concat.py#L529
in _get_objs_combined_axis docstring, sort kwarg is now described as:

    sort : bool, default True
            Whether the result index should come out sorted or not.

sort is now passed to _get_combined_index
https://github.com/pandas-dev/pandas/blob/c64c9cb44222a42f7b02d4d6007919cd0645f1be/pandas/core/indexes/api.py#L93

In which it is used to determine whether or not to sort the index, not the columns: 

    if sort:
        try:
            index = index.sort_values()
        except TypeError:
    pass

Am I mistaken? Could you point me to where the value of the sort kwarg causes an operation on the order of the columns?

**Comment by TomAugspurger** [comment]
@Liam3851 is correct.

> The sort parameter sorts column names.

It doesn't affect the row labels.

**Comment by Liam3851** [comment]
@cryptobhc If you're still curious exactly how this works, check out concat.py 492:497. Line 529 you cite above is only called for axes _other_ than the concatenation axis. In this case, the columns of the DataFrame.
