### ISSUE TITLE
Numpy requirement needs upper version limit for PY2 compatibility

### ISSUE THREAD

**Issue by philnagel** [pandas-dev/pandas#27293]
The pandas 0.24.x series is [intended](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.24.2.html) to be supported under Python 2. However, when installing pandas 0.24.2 via pip, one of the requirements is the latest version of `numpy >= 1.13.3`.
The current version of numpy that pip will attempt to install is 1.17.0, which is no longer Python 2 compatible.
The setup.py requirements should include an upper limit for the numpy version to resolve this (i.e. `numpy >= 1.13.3,<1.17.0`

**Comment by TomAugspurger** [comment]
> The current version of numpy that pip will attempt to install is 1.17.0, which is no longer Python 2 compatible.

Is that always true? NumPy sets their `python_requires>=3.5`. So pip shouldn't be pulling in NumPy 1.17.

**Comment by philnagel** [comment]
I believe you're right. This was happening on a specific machine for me - I think the reason was that pip was quite outdated in that environment. Things work as expected on some other machines I tested. 
Upgrading pip seems to have resolved this. Sorry for opening a spurious issue.
