### ISSUE TITLE
BUG: pandas merge creating duplicate row 

### ISSUE THREAD

**Issue by rachelvuu** [pandas-dev/pandas#27314]
#### Code Sample, a copy-pastable example if possible

```python
query = """
SELECT risk_state_code, COUNT(*) as num_records
FROM EDW.vw_policy_coverage_deductible_transaction
GROUP BY risk_state_code
"""
bquery = pd.read_sql(query, bvt_conn)
pquery = pd.read_sql(query, prod_conn)
merged = pd.merge(bquery, pquery, on='risk_state_code', how='outer')
merged
```

#### Problem description

When performing pandas merge on categorical column name, it duplicates unique values (different outcome every time I run the cell). Have tried in multiple environments, pandas is updated to latest version.
*Executing the **SAME** code produces different outputs pictured below.

![image](https://user-images.githubusercontent.com/32352509/60923060-f6043680-a252-11e9-9138-f2689c7c6af5.png)

![image](https://user-images.githubusercontent.com/32352509/60923062-f8669080-a252-11e9-9a21-430f733606a9.png)

Here are the dataframes being merged:
![image](https://user-images.githubusercontent.com/32352509/60923756-6cedff00-a254-11e9-8fc0-e7c590c44321.png)

#### Expected Output

![image](https://user-images.githubusercontent.com/32352509/60923048-eab10b00-a252-11e9-8a91-8ce523fd290c.png)

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.2
pytest: 4.3.1
pip: 19.0.3
setuptools: 40.8.0
Cython: 0.29.6
numpy: 1.16.2
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.4.0
sphinx: 1.8.5
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: 1.2.1
tables: 3.5.1
numexpr: 2.6.9
feather: None
matplotlib: 3.0.3
openpyxl: 2.6.1
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.5
lxml.etree: 4.3.2
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.3.1
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by WillAyd** [comment]
Can you provide a self-contained copy/pastable example to reproduce? Screenshots unfortunately aren't very helpful

FWIW I tried with the example above and couldn't reproduce:

```python
>>> bquery = pd.DataFrame([['OR', 142934], ['WA', 2042254]], columns=['risk_state_code', 'num_records'])
>>> pquery = pd.DataFrame([['OR', 144742], ['WA', 2955151]], columns=['risk_state_code', 'num_records'])
>>> bquery
  risk_state_code  num_records
0              OR       142934
1              WA      2042254
>>> pquery
  risk_state_code  num_records
0              OR       144742
1              WA      2955151
>>> pd.merge(bquery, pquery, on='risk_state_code', how='outer')
  risk_state_code  num_records_x  num_records_y
0              OR         142934         144742
1              WA        2042254        2955151
```

**Comment by rachelvuu** [comment]
Thanks for the quick response. This is most likely a bigger issue that has to do with using an SQL server connection. It looks like making a copy of the dataframes being merged fixes the issue, which I will do for now.
