### ISSUE TITLE
Solving merge conflicts in whatsnew once and for all

### ISSUE THREAD

**Issue by pilkibun** [pandas-dev/pandas#27312]
[towncrier](https://github.com/hawkowl/towncrier), as used by `pipenv`,

```
towncrier is a utility to produce useful, summarised news files for your project. 
Rather than reading the Git history as some newer tools to produce it, or 
having one single file which developers all write to, towncrier reads 
“news fragments” which contain information useful to end users.
```

if the package itself is not option, you may still want to adpot its approach of assembling  issuenum named fragment files together.  For an example, see
https://github.com/pypa/pipenv/tree/master/news

**Comment by WillAyd** [comment]
Do you have an example of this in released docs?

**Comment by pilkibun** [comment]
See https://docs.pipenv.org/en/latest/changelog/, top item came from https://github.com/pypa/pipenv/blob/5402384425208d911aae56fc2c58a6dac03d2649/news/3178.bugfix.rst

**Comment by WillAyd** [comment]
Cool. I think worth considering as simple merge conflicts definitely can slow down PR reviews. 

Let’s see what others think.

**Comment by jorisvandenbossche** [comment]
Matplotlib is also considering this: https://github.com/matplotlib/matplotlib/pull/14589 (so we could also first see how it goes for them)

Is it compatible with the way that we have additional sections for PRs (instead of only bullet points)?

**Comment by WillAyd** [comment]
Looks like dateutil has been using it so @jbrockmendel might have some thoughts

**Comment by pilkibun** [comment]
It looks like they generate the release notes as part of the release process and then purge the fragment directory.

> Is it compatible with the way that we have additional sections for PRs (instead of only bullet points)?

not sure, but it looks like fragments are rendered into a [template](https://github.com/pypa/pipenv/blob/5402384425208d911aae56fc2c58a6dac03d2649/news/towncrier_template.rst), so directory per numbered section and the template traverses in order?

**Comment by jreback** [comment]
i am not in favor of this

we have integrated whatsnew already with categories and sections
furthermore we only occasionally have merge conflicts

this doesn’t allow AFAIK very fine grained control over assembly
which is the point of our integrated notes

**Comment by jorisvandenbossche** [comment]
> this doesn’t allow AFAIK very fine grained control over assembly

It does allow quite fine grained control, we could have all section with bullet points as we have today (you can specify your own sections). 

But I think the main problem is that it seems to work only for bullet points, which is of course a good reason to not use it for pandas.

**Comment by pilkibun** [comment]
> furthermore we only occasionally have merge conflicts

In practice what happens is that asking for a whatsnew has become the last step of the review, when the user is active and the reviewer is poised to merge. So there's only a small window for conflicts.

Maybe that's good enough. The Issue template doesn't reflect this flow though.

**Comment by datapythonista** [comment]
I'm -1 on this. Conflicts in whatsnews files are trivial to fix. And this packages adds too much complexity for almost no value (new dependency, new thing to learn, possible bugs...).

**Comment by TomAugspurger** [comment]
I'm also OK with the low-tech current solution. Thanks for raising, but we'll pass @pilkibun.
