### ISSUE TITLE
Assigning with .loc throws SettingWithCopyWarning despite following instructions in warning

### ISSUE THREAD

**Issue by david-cortes** [pandas-dev/pandas#27327]
Happens with some data frames only. I cannot produce a minimal reproducible example, but can pickle the data frame in question if it helps.
![warning_with_loc](https://user-images.githubusercontent.com/11860098/61002969-6dc58480-a36b-11e9-8655-607d20f664a9.png)

**Comment by WillAyd** [comment]
Do you get this if you just use the label instead of `df.columns[0]` on the left hand side of the expression?

**Comment by david-cortes** [comment]
> Do you get this if you just use the label instead of `df.columns[0]` on the left hand side of the expression?

Yes, still happens even if I put the column name as a hard-coded string in both sides.

**Comment by WillAyd** [comment]
Can you provide a reproducible example somehow? Not clear from screenshot what is going on. df itself could be a copy

**Comment by david-cortes** [comment]
> Can you provide a reproducible example somehow? Not clear from screenshot what is going on. df itself could be a copy

It is a shallow copy indeed - managed to make a simple example:
```python
import numpy as np, pandas as pd
df0 = pd.DataFrame({
    "c1" : [1, 2, 3],
    "c2" : ['a', 'a', 'b'],
    "c3" : ['f', 'g', 'h']
})
df1 = df0[["c2", "c3"]]
df1.loc[:, df1.columns[0]], aaa = pd.factorize(df1[df1.columns[0]])
```

**Comment by WillAyd** [comment]
So the problem is it's not entirely clear if the operation will / should modify `df0` (this is the point of the warning)

If you don't care for that to propagate back a simple `.copy` call will get rid of the warning

```python
import numpy as np, pandas as pd
df0 = pd.DataFrame({
    "c1" : [1, 2, 3],
    "c2" : ['a', 'a', 'b'],
    "c3" : ['f', 'g', 'h']
})
df1 = df0[["c2", "c3"]].copy()  # note .copy here
df1.loc[:, df1.columns[0]], aaa = pd.factorize(df1[df1.columns[0]])
```

**Comment by david-cortes** [comment]
> So the problem is it's not entirely clear if the operation will / should modify `df0` (this is the point of the warning)
> 
> If you don't care for that to propagate back a simple `.copy` call will get rid of the warning
> 
> ```python
> import numpy as np, pandas as pd
> df0 = pd.DataFrame({
>     "c1" : [1, 2, 3],
>     "c2" : ['a', 'a', 'b'],
>     "c3" : ['f', 'g', 'h']
> })
> df1 = df0[["c2", "c3"]].copy()  # note .copy here
> df1.loc[:, df1.columns[0]], aaa = pd.factorize(df1[df1.columns[0]])
> ```

But what if I want it to propagate back or don't care about the original? (copy will add some overhead) I guess I can do `pd.options.mode.chained_assignment = None`, but there has to be some better alternative. Also I think the warning message could be improved for cases like this.

**Comment by WillAyd** [comment]
> But what if I want it to propagate back or don't care about the original?

Just work with the original directly then

```python
df0['c1'], _ = pd.factorize(df0['c1'])
```

Or am I missing something?

**Comment by david-cortes** [comment]
Issues for me are:
* The warning tells me to use `.loc` to avoid the warning, but I still get it after changing to `.loc`.
* I'm passing around this data frame to functions that modify it. In the original context it was creating sub-dataframes by selecting columns according to their dtype and passing them to different functions.

**Comment by jreback** [comment]
you can provide a more informative docs if you'd like, but they go thru this exact case. you are doing a classic operation where you are working on a view and pandas can't tell what you want. The copy is a reasonable way around this.
