### ISSUE TITLE
Automatically remove invalid characters from Bigquery identifiers in df.to_gbq()

### ISSUE THREAD

**Issue by ensslen** [pandas-dev/pandas#27333]
#### Code Sample, a copy-pastable example if possible

```python
# BQ supports limited characters in names
import pandas as pd
import os
from google.oauth2 import service_account
credentialPath = os.path.join('build','keys','build.json')
df = pd.DataFrame({'good_name':[1,3,5,7,4,5,6,4,7,8,9], '*bad*name*':[3,5,6,2,4,6,7,8,7,8,9]})
df.to_gbq(destination_table='dataset_name.table_name',credentials=credentials)

```
#### Problem description
Bigquery responds with an error
```
pandas_gbq.gbq.GenericGBQException: Reason: 400 POST https://www.googleapis.com/bigquery/v2/projects/poco-analytics-experimental/datasets/dataset_name/tables: Invalid field name "*bad*name*". Fields must contain only letters, numbers, and underscores, start with a letter or underscore, and be at most 128 characters long.
```

#### Expected Output

It would be nice if pandas either removed all of the invalid characters or replaced them with underscores (which are the only permitted punctuation character) so that identifiers match https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#identifiers
ie.
```
 import re
 df.columns = [re.sub(r'[^A-Za-z_0-9]', '_', cn) for cn in df.columns]
 table=re.sub(r'[^A-Za-z_0-9]', '_', '{}.{}'.format(dataset, tableName))
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Darwin
OS-release: 18.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.24.2
pytest: 5.0.1
pip: 19.1.1
setuptools: 41.0.1
Cython: None
numpy: 1.16.4
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: 1.2.0
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: 0.10.0
pandas_datareader: None
gcsfs: None
</details>

**Comment by jreback** [comment]
you can request to the pandas-gbq project
