### ISSUE TITLE
CI checks doesn't catch commit subject whitespace errors

### ISSUE THREAD

**Issue by pilkibun** [pandas-dev/pandas#27345]
```
$ git log --format="%s" | head -n 10
CLN: revisit build warnings in cython templates
 ENH: Raise ValueError for unsupported Window functions (#27275)
BUG: fix inserting tz-aware datetime to Series, closes #12862 (#27322)
CLN: requested follow-ups (#27332)
BUG: Consistent division by zero behavior for Index/Series (#27321)
TST: suppress rolling warnings correctly for raw= (#27330)
CLN: replace usage internally of .iteritems with .items (#26114)
BUG: appending a Timedelta to Series incorrectly casts to integer (#27303)
CLN: Split test_window.py (#27305)
check early for non-scalar default_fill_value (#27302)
```
```
$ git log --format="%s" | grep "^ " | wc -l
44
```
There are multiple recent instances.

**Comment by WillAyd** [comment]
Is this a common thing to check for?

**Comment by pilkibun** [comment]
Does it matter? either you want to or you don't. I don't mind either way, I just noticed it and am pointing it out. I think it makes git log ugly and the pandas checks are pedantic in other ways as well.

**Comment by jorisvandenbossche** [comment]
How would it be checked? If you have multiple commits, the commit message comes from the github PR title. So you would need a github app / bot that checks that.

**Comment by pilkibun** [comment]
First of all, I just found out yesterday that azure merges the PR into master before testing (A good thing). It's possible that on CI, the merge commit (according to Github setting) is present.

If not, hmm. 

See https://github.com/pandas-dev/pandas/pull/27171 (no leading space in title, and no title renames)
vs.
https://github.com/pandas-dev/pandas/commit/7ec7c9eecab5720a88e659fd0993 (no leading space in title)
vs.
```
# git log --format="%s" 7ec7c9eecab5720a88e659fd0993eaab47d0c33b -n 2
 CLN: convert argument in .take method (#27171)
Fix build warnings (#27157)
```

So where did the leading space come from?

**Comment by jorisvandenbossche** [comment]
> So where did the leading space come from?

No idea, but if not from the PR title and not from the commit message, then human error when merging is the only thing I can think of. And we will not be able to have a CI check for human error ;)

**Comment by pilkibun** [comment]
What about #26648/e8132a2901 which you merged. Did you push it manually?

**Comment by pilkibun** [comment]
Doesn't seem like you want to bother. That's ok.
