### ISSUE TITLE
INT: avoid accessing self.loc._foo outside of indexing.py

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#27344]
grepping for `.loc.` and `.iloc.` I see two uses of `self.loc._convert_to_indexer` and two uses of `self.loc._setitem_with_indexer` in core.frame, and two uses of `obj.loc._getitem_axis` in `io.pytables`

**Comment by topper-123** [comment]
This reminds me: the indexers all have their name prepebded wirh a ``_``:
* ``_LocIndexer``
* ``_IlocIndexer``
* ``_AtIndexer``
* ``_IatIndexer``
* etc.

They are not actually private, so sholdnt we rename them (drop the ``_``)?
