### ISSUE TITLE
DEPS: make a package for the ci/code_checks.sh

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#27342]
I think it might be nice to put the ci/code_checks.sh into its own repo / library where others could use these.

I think we have quite sophisticated doc string validations, potentially these could migrate to numpydoc.

cc @datapythonista

**Comment by jorisvandenbossche** [comment]
Unless there is a concrete demand, I think moving them to a separate repo will only be cumbersome. Because (IIUC) if you do a clean-up of some code + a change in the scripts, you need to do two PRs that need to be coordinated.

**Comment by WillAyd** [comment]
I would be a +1 on moving these out. Particularly with docstring validation it seems like a very strange thing to take on and maintain within pandas

**Comment by jbrockmendel** [comment]
i agree with all three of you.

**Comment by jorisvandenbossche** [comment]
> i agree with all three of you.

Are you aware that I basically gave a -1 and Will a +1 ..? ;)

**Comment by datapythonista** [comment]
I think in `ci/code_checks.sh` there is mainly the validation of the docstrings that it's worth considering. There are few more things, like the grep which fails when the text is found (grep does the opposite) or the sync between conda and pip deps, but I think they are too small to be worth a package.

I agree that the validation of docstrings should be in numpydoc, even if as Joris says this will come at an extra cost for us. But I'd say our validation starts to be quite mature, and I don't expect important changes, may be just some new rules, and those could be implemented without much coordination I think.

But probably the issue should be more for the numpydoc repo. They need to make a decision whether they want to make their standards more strict. I thought that I asked that in the numpy distribution list a while ago, but it looks like I didn't. I'll propose it when I have time, and depending on their interest we can decide.

**Comment by gfyoung** [comment]
As long as the checks remain configurable / overridable if put into `numpydoc`, I don't see why we don't externalize these scripts.  They have been relatively stable for a bit now.

**Comment by TomAugspurger** [comment]
Agreed with Marc that moving (just) the docstring validation is best, if
numpydoc is interested in maintaining it.

**Comment by datapythonista** [comment]
I started the discussion in the numpydoc repo (there was already an issue about having a stricter standard), and also in numpy-discussion. Will post here any update.

**Comment by jbrockmendel** [comment]
Looks like part of this was done in #28822.  Not much interest since then.  I think this has served its purpose.  Closing.
