### ISSUE TITLE
DEPR: .take(..., is_copy=True); rename is_copy -> copy

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#27357]
this is more in-line with our other signatures. ideally would do this for 0.25

**Comment by mpmoran** [comment]
I can take a crack at this.

**Comment by jorisvandenbossche** [comment]
Or simply deprecate this without replacement? A `take` operation is in principle always a copy

**Comment by jreback** [comment]
you can try to deprecate it entirely if that works

**Comment by jorisvandenbossche** [comment]
So the special case for "no copy" is when the result is exactly the same as the caller. Personally, I don't think we need to provide this special case (if the user cares about the performance in that corner case, they can do the check themselves)

**Comment by chrisstpierre** [comment]
I opened a PR to deprecate it in 0.25.2. is_copy is supposed to be [removed all-together in 1.0.0](https://github.com/pandas-dev/pandas/issues/6581). 

take always returns a copy

https://github.com/pandas-dev/pandas/blob/c4489cbfa5f93e69301486e1ef867caed9f4eb9e/pandas/core/generic.py#L3437

https://github.com/pandas-dev/pandas/blob/c4489cbfa5f93e69301486e1ef867caed9f4eb9e/pandas/core/internals/managers.py#L1394

https://github.com/pandas-dev/pandas/blob/c4489cbfa5f93e69301486e1ef867caed9f4eb9e/pandas/core/internals/managers.py#L1222

**Comment by jorisvandenbossche** [comment]
@chrisstpierre can you open a new PR against master? (using the same branch, but not selecting the 0.25.x branch when opening the PR) 
I looked at the commit you added, and that by itself looks good!

**Comment by chrisstpierre** [comment]
@jorisvandenbossche just did that.

But I still have `.. deprecated:: 0.25.2`.

Should it be 1.0.0 ?

**Comment by TomAugspurger** [comment]
There's a stalled PR at https://github.com/pandas-dev/pandas/pull/28751 that provides a nice starting point.

**Comment by ryankarlos** [comment]
take

**Comment by jorisvandenbossche** [comment]
Reopening this issue (to have an issue with a milestone) to track the discussion in the merged PR: https://github.com/pandas-dev/pandas/pull/30615#issuecomment-571637550

I *think* that the current deprecation is keeping the "wrong" behaviour, as in my head, the result of `take` is always a copy, so we shouldn't set `_is_copy` IMO. 
(but I also might be wrong, it's pretty confusing, and the `is_copy` keyword has also a very confusing name and unclear explanation of what it is actually intended to do)

**Comment by TomAugspurger** [comment]
@jorisvandenbossche do you think this is a blocker for the RC?

**Comment by jorisvandenbossche** [comment]
Ah, forgot this one, we should have discussed it yesterday on the call ..

Well, I personally think the merged PR is a step in the wrong direction. It's easy to revert that, but IMO the better solution is to make `take` do a proper copy. But that is 1) something that needs to be discussed and 2) is more work to implement.

**Comment by jorisvandenbossche** [comment]
Given the lack of input of others, shall we revert the PR for the RC?

**Comment by jreback** [comment]
not sure what exactly is the issue you are bringing up here; we deprecated is_copy and you reopened exactly why?

**Comment by jorisvandenbossche** [comment]
> not sure what exactly is the issue you are bringing up here; we deprecated is_copy and you reopened exactly why?

Right now, after the deprecation, we will keep `is_copy=True`, while I think it should be `is_copy=False` that becomes the default. Please read https://github.com/pandas-dev/pandas/issues/27357#issuecomment-571639242 and https://github.com/pandas-dev/pandas/pull/30615#issuecomment-571637550

**Comment by jorisvandenbossche** [comment]
Example consequence of the PR. Using `sample()` can now give a false-positive warning:

```
In [11]: df = pd.DataFrame(np.random.randn(10,3), columns=['a', 'b', 'c'])   

In [12]: df2 = df.sample(3)  

In [14]: df2['d']= 1   
/home/joris/miniconda3/envs/dev/bin/ipython:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  #!/home/joris/miniconda3/envs/dev/bin/python
```

The above is on master, on 0.25.3 this did not raise a warning.
