### ISSUE TITLE
Improve docs on formatting Excel sheets using xlsxwriter

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#27356]
#### Code Sample, a copy-pastable example if possible

N/A

#### Problem description

I'd like to suggest that the documentation about formatting Excel sheets in the I/O tools page here: https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html?highlight=xlsxwriter#style-and-formatting be improved by putting in a reference to the numerous examples provided by the xlsxwriter documentation here: 

https://xlsxwriter.readthedocs.io/pandas_examples.html

I'm willing to do a PR, but I didn't know if there was some reason for not including the external reference on that particular page.

#### Expected Output

N/A

#### Output of ``pd.show_versions()``

pandas 0.24.2

**Comment by WillAyd** [comment]
Makes sense to me - is there something similar for openpyxl?

**Comment by Dr-Irv** [comment]
@WillAyd I think you can do formatting with `openpyxl`, but the documentation on how it interacts with pandas is very thin compared to what I pointed to above for `xlsxwriter`, where they have lots of examples.  Didn't see those kinds of examples in the `openpyxl` docs.

**Comment by WillAyd** [comment]
Cool thanks for checking! For sure if you have a PR will take a look
