### ISSUE TITLE
Feature Request: Transform excepting dicts and lists after groupby

### ISSUE THREAD

**Issue by Make42** [pandas-dev/pandas#27379]
@WillAyd 
Just so I'm clear, you're suggesting something like: 
`test.groupby('groups').transform({'value1': [np.mean, max], 'value2': max})` which should return something like:

```
                    value1     value2    
                      mean max   max
2012-02-01 14:00:00      2   3    30
2012-02-01 14:01:00      2   3    30
2012-03-05 14:04:00      2   3    30
2012-03-05 14:01:00      5   6    60
2012-03-10 14:02:00      5   6    60
2012-03-11 14:07:50      5   6    60
```

_Originally posted by @brianhuey in https://github.com/pandas-dev/pandas/issues/17309#issuecomment-429669023_

Exactly this is my feature request.

**Comment by WillAyd** [comment]
If you have a PR for the issue linked feel free to push.

Closing this as duplicate (don't need a new issue)
