### ISSUE TITLE
Discuss: transformation vs. aggregation in `agg` vs. `transform`

### ISSUE THREAD

**Issue by ghost** [pandas-dev/pandas#27389]
There have been multiple issues regarding
- Confusion about relative respective roles of `agg` and `transform` (and `apply`).
https://github.com/pandas-dev/pandas/issues/26960, https://github.com/pandas-dev/pandas/issues/18103 in both the DataFrame and Grou
- `transform('rank')` and others returning the wrong answer (first issue from 2016): https://github.com/pandas-dev/pandas/issues/14274, https://github.com/pandas-dev/pandas/issues/19354, https://github.com/pandas-dev/pandas/issues/22509, 

I'd like to prepare a PR to fix this, but I need to know what the consensus is first.

## 1. should `Groupby/DataFrame/Series.agg` disallow transformations?
 
https://github.com/pandas-dev/pandas/issues/14741#issuecomment-262953242 about `Groupby.agg`
```
you need to use .transform. .agg is by definition a reducer.
```
`agg` currently accepts transformations as well.

`DataFrame.agg` was merged in #27389 despite repeated objections to mixing transformations and aggregations, https://github.com/pandas-dev/pandas/pull/14668#issuecomment-260893757 and https://github.com/pandas-dev/pandas/pull/14668#issuecomment-269468649.

## 2. What should `transform('rank')` return?

**updated**

```
g.min               # one value per group. ok.
g.transform('min')  # one value per group, broadcasted. ok.
g.rank()            # like-index result. Ok
g.transform('rank') # Currently, a nonsense result.
```
 
 
On the one hand, users have been told that transformations don't belong in `transform` (!):  https://github.com/pandas-dev/pandas/issues/22509#issuecomment-501937245, https://github.com/pandas-dev/pandas/issues/14274#issuecomment-248760874. This makes sense if you think of the `transform('name')` form as solely for broadcasting aggregations.

On the other hand, the documentation for `transform`, as well as  Wes Mckinney's excellent pandas book portray `transform` as the dedicated tool for shape-preserving operations, so excluding them from the `transform('name')` case would be a little surprising.

Personally, I'm +0 for deprecating `transform('rank')` and with a warning to use `g.rank()`, as well as for the other transformation ops.

**Comment by WillAyd** [comment]
I would be fine with the first point to ensure agg reduces. I'm not clear on what issue points 2 and 3 are trying to solve

**Comment by TomAugspurger** [comment]
> I would be fine with the first point to ensure agg reduces

Agreed. We should deprecate  the current behavior with a warning.

I also don't understand point 2.

> 3. Is broadcasting a transformation result useful in some other cases?

Yes, I find this useful.

**Comment by pilkibun** [comment]
I'm not clear on what issue points 2 and 3 are trying to solve
> I also don't understand point 2.

`transform('rank')` currently returns the wrong result because it is mistakenly treated like an aggregation. The `transform('name')` form currently mixes
- aggregations ops (max, mean) for which the result is broadcast to the entire group
- transformation ops (ffill, rank etc') for which currently the wrong answer is returned.

point 2 asks if transformation ops should be deprecated with a warning when passed as `name`, or whether they should be fixed to return the same result as `g.name()`.

Point 3 asks if, despite my intution, ther's a case for having `g.transform('rank') != g.rank()` for example.

> Yes, I find [broadcasting a single value from the result of a transformation] useful.

Ok, could you give an example? because this doesn't even work right now afaict.

**Comment by pilkibun** [comment]
>  I'm not clear on what issue points 2 and 3 are trying to solve

>  I also don't understand point 2.

What should `g.transform('rank')` return? should it be the same as `g.rank()`? currently it returns nonsense.

**Comment by pilkibun** [comment]
> Agreed. We should deprecate the current behavior with a warning.

Good. But how does that sit with 25.0 being released and the deprecation policy during this release cycle coming up on 1.0? Can we do it?

**Comment by TomAugspurger** [comment]
Discussion on the mailing list: https://mail.python.org/pipermail/pandas-dev/2019-July/001030.html

I think the plan was to be light on new deprecations for 1.0. But I don't know how wedded we are to that idea.

**Comment by mroeschke** [comment]
I think the more recent discussion of this has moved to https://github.com/pandas-dev/pandas/issues/35725, so closing in favor of that issue.
