### ISSUE TITLE
Add 'how' option to 'first_valid_index'

### ISSUE THREAD

**Issue by schneiderfelipe** [pandas-dev/pandas#27397]
This is a suggestion to include a `how` option to [`first_valid_index`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.first_valid_index.html#pandas-dataframe-first-valid-index) ([similar to `dropna`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html#pandas-dataframe-dropna)), such that the first index having at least one non-`nan` value (`how="any"`, current behaviour), or no `nan` value (`how="all", new behavious), is returned.

#### Code Sample, a copy-pastable example if possible

Currently, this can be accomplished as follows:

```python
df.dropna().first_valid_index()  # would become df.first_valid_index(how="all")
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-54-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: pt_BR.UTF-8
LOCALE: pt_BR.UTF-8

pandas: 0.22.0
pytest: 3.3.2
pip: 9.0.1
setuptools: 39.0.1
Cython: None
numpy: 1.13.3
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: 5.5.0
sphinx: 1.6.7
patsy: 0.4.1+dev
dateutil: 2.6.1
pytz: 2018.3
blosc: 1.4.4
bottleneck: None
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.1.1
openpyxl: 2.4.9
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: 4.2.1
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by mroeschke** [comment]
Thanks for the suggestion but I believe chaining `dropna` is pretty idiomatic already as the library is not trying to add multiple ways of doing things. Since there hasnt been much interest for this feature from the community or other core devs, going to close as stale. Happy to reopen if there's further interest
