### ISSUE TITLE
f-strings vs @ syntax in `.query` call? A suggestion for a deprecation

### ISSUE THREAD

**Issue by ianozsvald** [pandas-dev/pandas#27405]
This is not a problem but an observation and possibly something for a deprecation (as discussed with @datapythonista at PyDataLondon this weekend).

Pandas supports a `.query` syntax including the `.query("my_col < @some_var")` syntax to bring in a local `some_var`. This predates Python's f-string syntax which was introduced in Python 3.6. 

I wonder if Python's f-string syntax is a more standard way to tackle variable substitution going forwards? The equivalent would be `.query(f"my_col < {some_var}")`.

The benefit would be to reduce the amount of code that's custom to Pandas and to stick to a more-standard (IMHO) approach to variable substitution.

#### Code Sample, a copy-pastable example if possible

```python
In [4]: df = pd.DataFrame({'col': [1, 2, 3, 4]})
In [5]: value = 3

In [6]: df.query("col < @value")
Out[6]: 
   col
0    1
1    2

In [7]: df.query(f"col < {value}")
Out[7]: 
   col
0    1
1    2
```

#### Output of ``pd.show_versions()``

<details>

In [10]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.2.final.0
python-bits: 64
OS: Linux
OS-release: 5.0.0-19-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.23.4
...
</details>

**Comment by datapythonista** [comment]
Not familiar with that code, but I'm +1 on this, after we stop supporting Python 3.5, which I guess will be in the next version after 0.25.

**Comment by TomAugspurger** [comment]
IIUC, this wouldn't work in general. I believe that f"col < {value}"
interpolate the string repr of `value` in to a string, which is then passed
to `.query`.

If `value` was instead something like a Series, then you'd have

```
In [6]: value = pd.Series([1, 2, 3]) In [7]: f'col < {value}'
Out[7]: 'col < 0 1\n1 2\n2 3\ndtype: int64'
```

So you'd be executing the query

```
df.query('col < 0    1\n1    2\n2    3\ndtype: int64')
```

**Comment by datapythonista** [comment]
you're right, didn't realize, and just saw that even for string values quotes would be needed `f'col < "{value}"'` which is more complex for the user than the `@` syntax. Not sure if without being an f-string, the syntax `df.query("col < {value}")` could be more familiar to Python users than `df.query("col < @value")`, but probably not worth breaking code for that.

**Comment by ianozsvald** [comment]
@TomAugspurger hey there Tom! Thanks for the input. I had no idea that `query` worked with a `Series` input! My use case is typically with filtering by 1 variable with a few bits of logic. I agree that the f-string won't work in this case. I'm going to close this thread.

For completeness in case someone comes along, here's a longer code snippet showing the above.

```
In [21]: value = pd.Series([0, 2, 2, 5])

In [22]: df.query("col < @value")
Out[22]: 
   col
3    4

In [23]: df.query(f"col < {value}")
---------------------------------------------------------------------------
ValueError                             
...
ValueError: multi-line expressions are only valid in the context of data, use DataFrame.eval
```
