### ISSUE TITLE
Feature Request: Include SSPipe Functionality

### ISSUE THREAD

**Issue by jtelleria** [pandas-dev/pandas#27400]
Could pandas include as a submodule "SSPipe" Package?

https://pypi.org/project/sspipe/
https://sspipe.github.io/

DataFrame object already has a .pipe() method, but the objective is to make the "pipe" (Equivalent to R's magrittr %>% functional pipe) a standard that can be extrapolated to all Python objects and casuistics.

**Comment by WillAyd** [comment]
So you are basically asking to replicate the behavior of the `pipe` method with the `|` operator?

**Comment by jtelleria** [comment]
Plus a "px" object, which stands as a pipeable object. 

In R's magrittr, after using a pipe %>%, objects can be accessed from any argument using a dot (.):

https://cran.r-project.org/web/packages/magrittr/vignettes/magrittr.html

**Comment by jtelleria** [comment]
You could simply import SSPipe as a submodule as a start :) 

And take care of it's maintenance. Fast and easy.

**Comment by TomAugspurger** [comment]
Even if we did want this, we wouldn't be able to since we already use `__or__` for elementwise or.

**Comment by jtelleria** [comment]
Just rename it, I would call such operator %>%, just as R's magrittr pipe.

More familiar for Data Scientist with a R Background.

**Comment by TomAugspurger** [comment]
You can't define custom operators in Python.

**Comment by jtelleria** [comment]
Couldn't __or__ function be called `%>%`?

**Comment by TomAugspurger** [comment]
I don't understand what you're proposing.

**Comment by jtelleria** [comment]
Add SSPipe as a Pandas submodule:

https://pypi.org/project/sspipe/
https://sspipe.github.io/

And make it work by fixing the issue with `__or__` in the submodule internals:

https://github.com/JulienPalard/Pipe/blob/master/pipe.py

https://github.com/sspipe/sspipe/blob/master/sspipe/pipe.py

**Comment by WillAyd** [comment]
Thanks but I don't think taking over maintenance of another package is something we want to do so closing for now.

**Comment by TomAugspurger** [comment]
I don't think we'd make that kind of change.

**Comment by jtelleriar** [comment]
@wesm What do you think about the pipe `%>%` Topic?
