### ISSUE TITLE
Support Decorators Maintaining Signatures of Generic Functions

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#27404]
As a follow up to #27393 I think I made a mistake in just typing some of the return values to be `Callable`. The following script highlights that issue:

```python
from pandas.util._decorators import Appender

def func1(num: int) -> int:
    return num

@Appender("")
def func2(num: int) -> int:
    return num

reveal_type(func1)
reveal_type(func2)
```

If you run that from the project root you'll get something like the following:

```sh
$ mypy foo.py
foo.py:10: note: Revealed type is 'def (num: builtins.int) -> builtins.int'
foo.py:11: note: Revealed type is 'def (*Any, **Any) -> Any'
```

We probably want to maintain the types of the signature for `func2` so I think need to use TypeVar for generic support. 

More info on the mypy side in:

https://github.com/python/mypy/pull/3113
https://github.com/python/mypy/issues/1551

So I think need something like:

```python
T = TypeVar('T', bound=Callable[..., Any])
# then decorators can return
-> Callable[[T], T]
```

**Comment by topper-123** [comment]
Does ``reveal_type`` return the proper types if this change is made?

**Comment by topper-123** [comment]
Possibly related to #13875.

**Comment by simonjayhawkins** [comment]
@WillAyd I'm reopening this as #28128 did not close this issue. solved for `Appender` and `Substitution` only

https://github.com/pandas-dev/pandas/commit/dd957415cb367056a6f58a776090c5efb581735e will fix `deprecate_kwarg` and probably similar for `rewrite_axis_style_signature`

**Comment by WillAyd** [comment]
Sounds good - thanks for taking a look

**Comment by jbrockmendel** [comment]
Does being py37+ make this any more solvable?

**Comment by WillAyd** [comment]
This should already be resolved here:

https://github.com/pandas-dev/pandas/blob/6f2c60ea99fd17e40d3e67195eebacddc2e445cb/pandas/_typing.py#L101
