### ISSUE TITLE
read_csv memory leak

### ISSUE THREAD

**Issue by xiahaohuan001** [pandas-dev/pandas#27414]
#### Code Sample, a copy-pastable example if possible

```python
import sys
import pandas as pd
_dir = r'D:\Python\data'
file_name = pd.read_csv(_dir + r'\dblist.csv', index_col=0)
file_name.loc[:, 'code'] = [x.upper() for x in file_name['code']]
file_name.loc[:, 'name'] = [x.upper() for x in file_name['name']]
file_name.loc[:, 'date'] = [str(x) for x in file_name['date']]

file_name11 = pd.read_csv(_dir + r'\dblist.csv', index_col=0)
file_name11.loc[:, 'code'] = [x.upper() for x in file_name11['code']]
file_name11.loc[:, 'name'] = [x.upper() for x in file_name11['name']]
file_name11.loc[:, 'date'] = [str(x) for x in file_name11['date']]

from copy import deepcopy
open_file1 = file_name.loc[file_name['name'] == 'IC1601', ['path', 'date']]
open_file11 = open_file1.copy()


for i2, fi in enumerate(open_file11['path']):
    # fi0 = r'D:\Python\data\Full\2016\f_c201601dn\zc\20160104\IC1601_20160104.csv'
    print('file_name0:', sys.getsizeof(file_name))
    data = pd.read_csv(fi)# (fi = r'D:\Python\data\Full\2016\f_c201601dn\zc\20160104\IC1601_20160104.csv',type:str)
    print('file_name1:', sys.getsizeof(file_name))
    del open_file2
    print('file_name2:', sys.getsizeof(file_name))
del open_file1
```
#### Problem description
I found a memory leak issue when I use pd.read_csv to read a csv file.
As the code shows,when I pd.read_csv(**fi**) the **file_name** add 104 byte memory everytimes.And the **file_name**'s shape is not change.The situation is not change when I write enumerate(open_file1).But when I use a static const str fi0,same content and type with fi,just pd.read_csv(**fi0**)memory is normal.I'm not sure it's a read_csv memory leak or not.My English is poor,I hope that I have already expressed my meaning.

output:
file_name0: 141473975
file_name1: 141474079
file_name2: 141474079
file_name0: 141474079
file_name1: 141474183
file_name2: 141474183
file_name0: 141474183
file_name1: 141474287
file_name2: 141474287

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 15 Stepping 11, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.24.2
pytest: None
pip: 19.1.1
setuptools: 41.0.1
Cython: None
numpy: 1.16.4
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.3
openpyxl: None
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: None
lxml.etree: 4.3.3
bs4: 4.7.1
html5lib: None
sqlalchemy: 1.3.3
pymysql: 0.9.3
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by jbrockmendel** [comment]
Can you trim this down to an example that we can verify by copy/pasting?

**Comment by xiahaohuan001** [comment]
You can use any csv file to test it.The problem is '\' in file path.The issue is disappear when I change '\' to '\\'.

**Comment by mroeschke** [comment]
Please post a self-contained, copy-pastable example when you get a chance. We'll reopen this issue at that time.
