### ISSUE TITLE
BUG: to_datetime with multiple timezones does not coerce if invalid string in input

### ISSUE THREAD

**Issue by JosuaKrause** [pandas-dev/pandas#27422]
#### Code Sample

```python
import pandas as pd

se = pd.Series(["2019-01-01 03:00:00-0500", "abc", "2019-01-01 03:00:00-0100"])
assert type(pd.to_datetime(se, errors="coerce").iloc[0]) == str
```

Note that the type of the first element (`"2019-01-01 03:00:00-0500"`) is `str` *after* the "conversion".

```python
import pandas as pd

se1 = pd.Series(["2019-01-01 03:00:00-0500", "abc", "2019-01-01 03:00:00-0100"])
pd.to_datetime(se1, errors="coerce")
# 0    2019-01-01 03:00:00-0500
# 1                         abc
# 2    2019-01-01 03:00:00-0100
# dtype: object

se2 = pd.Series(["2019-01-01 03:00:00-0500", "2019-01-01 03:00:00-0100"]) 
pd.to_datetime(se2, errors="coerce")
# 0    2019-01-01 03:00:00-05:00
# 1    2019-01-01 03:00:00-01:00
# dtype: object
```

#### Problem description

If the input to `to_datetime` contains both dates with multiple timezones and invalid strings *no conversion* (the input strings will be returned) will happen when running with `errors="coerce"`. This is a problem as the (documented) expected output type is a date-like type. Note, that if the incorrect string is not present the dates will convert but the overall dtype will be object.

In previous versions (< 0.24) the function would convert the dates into timezone unaware timestamps which is a far more predictable behavior (the output can easily be converted into the desired timezone).

#### Expected Output

Output in 0.23

```python
import pandas as pd

se1 = pd.Series(["2019-01-01 03:00:00-0500", "abc", "2019-01-01 03:00:00-0100"])
pd.to_datetime(se1, errors="coerce")
# 0   2019-01-01 08:00:00
# 1                   NaT
# 2   2019-01-01 04:00:00
# dtype: datetime64[ns]

se2 = pd.Series(["2019-01-01 03:00:00-0500", "2019-01-01 03:00:00-0100"]) 
pd.to_datetime(se2, errors="coerce")
# 0   2019-01-01 08:00:00
# 1   2019-01-01 04:00:00
# dtype: datetime64[ns]
```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Darwin
OS-release: 18.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 3.7.3
pip: 19.1.1
setuptools: 39.1.0
Cython: 0.29.7
numpy: 1.16.4
scipy: 1.0.0
pyarrow: 0.13.0
xarray: None
IPython: 6.2.1
sphinx: None
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: 1.2.1
tables: 3.5.2
numexpr: 2.6.9
feather: None
matplotlib: 2.2.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: 4.2.4
bs4: None
html5lib: 1.0.1
sqlalchemy: 1.3.0
pymysql: None
psycopg2: 2.7.4 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by Liam3851** [comment]
This is a documented change: https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.24.0.html#parsing-datetime-strings-with-timezone-offsets

Per the link:

> Passing utc=True will mimic the previous behavior but will correctly indicate that the dates have been converted to UTC

**Comment by JosuaKrause** [comment]
as per the documentation:
```
ret : datetime if parsing succeeded.
Return type depends on input:

list-like: DatetimeIndex
Series: Series of datetime64 dtype
scalar: Timestamp
In case when it is not possible to return designated types (e.g. when any element of input is before Timestamp.min or after Timestamp.max) return will have datetime.datetime type (or corresponding array/Series).
```
The expected output is some date-like type not `str`

**Comment by mroeschke** [comment]
Could you try your example on the 0.25.0rc? I am getting reasonable outputs on master

```
In [1]: pd.__version__
Out[1]: '0.25.0rc0+62.g269d36814'

In [3]: se = pd.Series(["2019-01-01 03:00:00-0500", "abc", "2019-01-01 03:00:00-0100"])
   ...:

In [4]: pd.to_datetime(se, errors="coerce").iloc[0]
Out[4]: datetime.datetime(2019, 1, 1, 3, 0, tzinfo=tzoffset(None, -18000))

In [5]: se1 = pd.Series(["2019-01-01 03:00:00-0500", "abc", "2019-01-01 03:00:00-0100"])
   ...: pd.to_datetime(se1, errors="coerce")
Out[5]:
0    2019-01-01 03:00:00-05:00
1                          NaT
2    2019-01-01 03:00:00-01:00
dtype: object

In [6]: se2 = pd.Series(["2019-01-01 03:00:00-0500", "2019-01-01 03:00:00-0100"])
   ...: pd.to_datetime(se2, errors="coerce")
Out[6]:
0    2019-01-01 03:00:00-05:00
1    2019-01-01 03:00:00-01:00
dtype: object
```

**Comment by JosuaKrause** [comment]
Yeah, looks like 0.25.0rc has a correct behavior. I guess I will have to wait until it's released then.

**Comment by mroeschke** [comment]
`0.25.0rc` is already out. 0.25.0 should be out fairly soon; hopefully by the end of the month.

**Comment by JosuaKrause** [comment]
cool! thank you!
