### ISSUE TITLE
CI: Compatibility with pytest-azurepipelines

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#27421]
https://github.com/pandas-dev/pandas/pull/27416#issuecomment-511922995

Failing on the prerelease at https://pypi.org/project/pytest-azurepipelines/1.0.0a1/

**Comment by datapythonista** [comment]
I don't think `pytest-azurepipelines` is adding as much value as expected. I thought besides the warnings it'd highlight the pytest error, which was the main reason to suggest it.

If it's causing problems, I'm happy to get rid of it.

**Comment by jbrockmendel** [comment]
is this active/actionable/closeable?

**Comment by TomAugspurger** [comment]
Let's assume closable.
