### ISSUE TITLE
DataFrame with MultiIndex raises `TypeError` instead of `KeyError` for inexistent keys 

### ISSUE THREAD

**Issue by epassaro** [pandas-dev/pandas#27420]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

a = {'A': [1, 2, 3, 4], 'B': [5, 6, 7, 8], 'C': [9, 10, 11, 12]}

df = pd.DataFrame.from_records(a, index=['A', 'B'])

df.loc[(1,6)]
```
#### Problem description

When a non existent key `.loc` raises `TypeError`. Is this the intended behavior?

#### Expected Output

Maybe should raise `KeyError`

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Linux
OS-release: 4.18.0-25-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 4.5.0
pip: 19.0.3
setuptools: 41.0.0
Cython: 0.29.12
numpy: 1.16.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.6.1
sphinx: 1.5.6
patsy: None
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: 3.5.2
numexpr: 2.6.9
feather: None
matplotlib: 3.1.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.3.5
pymysql: None
psycopg2: None
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by TomAugspurger** [comment]
I think you need to be explicit about where the index labels end. `df.loc[(1, 6)]` is equivalent to `df.loc[1, 6]`

```python
In [23]: df.loc[(1, 6), :]
```

which rasies

```pytb
~/sandbox/pandas/pandas/core/indexes/multi.py in get_loc_level(self, key, level, drop_level)
   2814                         return (self._engine.get_loc(key), None)
   2815                     except KeyError as e:
-> 2816                         raise KeyError(key) from e
   2817                 else:
   2818                     return partial_selection(key)

```

**Comment by jbrockmendel** [comment]
This now raises a KeyError on master

**Comment by epassaro** [comment]
> This now raises a KeyError on master

Yes, that's right.
