### ISSUE TITLE
df.describe.min(), max(), count() etc.  produce results inconsistent with describe

### ISSUE THREAD

**Issue by joleenf** [pandas-dev/pandas#27433]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

df = pd.DataFrame({'data': []})

print (df.describe())

print ('Dataframe mean: {}'.format(df['data'].describe().mean()))
print ('Dataframe min: {}'.format(df['data'].describe().min()))
print ('Dataframe count: {}'.format(df['data'].describe().count()))

```
#### Problem description

This problem occurred when bringing in data from a file which was filled with NaN data values.  It is easy to solve using df.empty first and then checking for min/max if df.empty is false.  The unexpected problem was that while df.describe() method properly reported the NaN values in the file, the methods of min, mean, count, etc. applied to the describe method produced the wrong values ( i.e., instead of NaN, the result is 0 and instead of a count of 0, the result is 1).   

#### Expected Output
<details>

```print ('Dataframe mean: {}'.format(df['data'].describe().mean()))```
Dataframe mean: NaN

```print ('Dataframe min: {}'.format(df['data'].describe().min()))```
Dataframe min: NaN

```print ('Dataframe count: {}'.format(df['data'].describe().count()))```
Dataframe count:  0 

#### Output of ``pd.show_versions()``
</details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Darwin
OS-release: 14.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: en_US.UTF-8
pandas: 0.24.2
pytest: None
pip: 19.1
setuptools: 41.0.1
Cython: None
numpy: 1.16.3
scipy: 1.2.1
pyarrow: None
xarray: 0.12.1
IPython: 7.5.0
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: 4.3.3
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

**Comment by mroeschke** [comment]
`describe().mean/count/min()` is applying the function to the _result_ of the describe operation. I think you want to index into the result instead `df.describe().loc['count'/'mean'/'min', 'data']`

So for example, `describe().count()` should return 1 since there is only 1 non null value after the _result_ of `describe()`
