### ISSUE TITLE
Feature request: add option to disable columns.levels autosorting

### ISSUE THREAD

**Issue by MCM-Math** [pandas-dev/pandas#27431]
I am trying to develop general code to access specific columns in the order they are displayed by index.  However, columns.levels resorts alphabetically automatically, and doesn't seem to have an option to have it... not do that.  It would be useful if there was an option to have it remember the original order, to allow better referencing capabilities.

**Comment by mroeschke** [comment]
Thanks for the suggestion but appears that this feature has not garnered much interest from the community or other core devs. Additionally a feature request would need a full API proposal in order to pursue. Closing but happy to reopen if there's further interest from the community or core devs
