### ISSUE TITLE
Add 'key' keyword argument to max/min methods, akin to python's builtin max/min

### ISSUE THREAD

**Issue by Strilanc** [pandas-dev/pandas#27441]
See https://docs.python.org/3/library/functions.html#max

Specifying a `key=` function F to use indicates you want to return the `val` with the largest `F(val)`, as opposed to returning the largest val or returning the largest F(val).

The following code should work:

```
>>> pd.DataFrame([1, 3, 5, 7]).max(key=lambda e: e % 3)
5
```

For the same reason that this works:

```
>>> max([1, 3, 5, 7], key=lambda e: e % 3)
5
```

Currently, it is necessary to use workarounds such as create temporary copies of the output of the function:

```
>>> df = pd.DataFrame([1, 3, 5, 7])
>>> k = df.apply(lambda e: e % 3).idxmax()
>>> df[0][k]
5
```

**Comment by jreback** [comment]
this is just

s.map(f).max()

so and pretty unfamiliar to the avg numpy/pandas user so prob -0

**Comment by Strilanc** [comment]
This is not `s.map(f).max()`. That returns the maximum function output, instead of the input that produces the maximum function output.

That being said, I guess this is an alternative name for `argmax`. Except `argmax` doesn't appear on DataFrame like `max` and `idxmax` do.

**Comment by Strilanc** [comment]
A more complicated example of what I would like to work:

```
best_a = df.groupby('a').argmax(lambda group: some_function(group))
```

**Comment by Strilanc** [comment]
I'm going to close this until I'm more certain I understand the semantics of the pandas values I'm suggesting changes for.
