### ISSUE TITLE
`Dataframe.sample()` isn't validating `frac`

### ISSUE THREAD

**Issue by ddebernardy** [pandas-dev/pandas#27451]
Minor/trivial bug:

https://github.com/pandas-dev/pandas/blob/master/pandas/core/generic.py#L4960

Shouldn't `sample()` check that `frac` is between 0 and 1 somewhere?

Doc improvement suggestion:

Could anyone confirm that `replace=True|False` means allowing|disallowing sampling the same row more than once?

Methinks the docs could use an update to make what `replace` does clearer for newcomers - or at least for those who aren't familiar with `numpy`.

**Comment by jschendel** [comment]
> Shouldn't `sample()` check that `frac` is between 0 and 1 somewhere?

We don't want to restrict the upper bound of `frac` because we allow oversampling when sampling with replacement.  Also note that validation is performed against the resulting `n` that's derived from `frac` for cases where an invalid `frac` is passed:

```python
In [2]: df = pd.DataFrame({'A': list('abc')})

In [3]: df.sample(frac=2, replace=True)
Out[3]: 
   A
1  b
0  a
1  b
2  c
2  c
2  c

In [4]: df.sample(frac=2, replace=False)
---------------------------------------------------------------------------
ValueError: Cannot take a larger sample than population when 'replace=False'

In [5]: df.sample(frac=-0.5)
---------------------------------------------------------------------------
ValueError: A negative number of rows requested. Please provide positive value.
```

> Could anyone confirm that replace=True|False means allowing|disallowing sampling the same row more than once?

Correct.

> Methinks the docs could use an update to make what `replace` does clearer for newcomers - or at least for those who aren't familiar with `numpy`.

Improvements to the docs are always welcome!

**Comment by ddebernardy** [comment]
@jschendel I've created a pull request to fix the doc issue and add a check for `frac <= 0`. No idea what the three items that are missing are about, but given the change I presume they'll all pass so I'll let you pick it up from here.
