### ISSUE TITLE
missing.cpython-35m-x86_64

### ISSUE THREAD

**Issue by alex067** [pandas-dev/pandas#27457]
Every once in a while, one of my scripts are failing and initially I thought it was due to a memory leak somewhere. After reading the error carefully, it looks like it's from a missing dependency:

```
7fecaeb6d000-7fecaeb7f000 r-xp 00000000 08:04 3021138                    /home/lib/python3.5/site-packages/pandas/_libs/missing.cpython-35m-x86_64-linux-gnu.so

7fecaeb7f000-7fecaed7f000 ---p 00012000 08:04 3021138                    /home/lib/python3.5/site-packages/pandas/_libs/missing.cpython-35m-x86_64-linux-gnu.so

7fecaed7f000-7fecaed81000 rw-p 00012000 08:04 3021138                    /home/lib/python3.5/site-packages/pandas/_libs/missing.cpython-35m-x86_64Aborted
```

In the library directory for pandas, in _libs, there is a file titled: missing.cpython-35m-x86_64-linux-gnu.so 

I can just guess this is some low level dependency that probably didn't get installed when pandas was initially installed. 

I updated pandas to ensure it's on the latest version, I believe 0.24? 

At this point should I just uninstall & reinstall pandas?

**Comment by jbrockmendel** [comment]
> At this point should I just uninstall & reinstall pandas?

Yes please.

**Comment by jbrockmendel** [comment]
@alex067 any word?

**Comment by alex067** [comment]
@jbrockmendel  

So far it seems to have resolved it. Looks like a reinstall did the trick.

**Comment by jbrockmendel** [comment]
OK.  I'm going to close this.  If the issue re-occurs, feel free to ping and I'll re-open.

**Comment by alex067** [comment]
@jbrockmendel 

It looks like the reinstall did not fix the issue. 

The last couple terminal outputs:
```
7f8e30f04000-7f8e30f0e000 rw-p 00069000 08:04 5374592                    /lib/python3.5/site-packages/pandas/_libs/lib.cpython-35m-x86_64-linux-gnu.so

7f8e30f0e000-7f8e30f10000 rw-p 00000000 00:00 0

7f8e30f10000-7f8e30f22000 r-xp 00000000 08:04 5374601                    /lib/python3.5/site-packages/pandas/_libs/missing.cpython-35m-x86_64-linux-gnu.so

7f8e30f22000-7f8e31122000 ---p 00012000 08:04 5374601                    /lib/python3.5/site-packages/pandas/_libs/missing.cAborted

```
