### ISSUE TITLE
Feature Request: Binomial Standard Deviation?

### ISSUE THREAD

**Issue by pmlandwehr** [pandas-dev/pandas#27458]
#### Problem description

We often work with large quantities of simulated data, and it would be convenient if we could get binomial standard deviation with a `.binom_std()` method (or with an optional argument to `.std()`.

**Comment by jreback** [comment]
this is likely out of scope for pandas; we have been moving away from adding additional statistical measures. But for clarify, how is this calculation done?

**Comment by pmlandwehr** [comment]
The equation is `sqrt( p * (1 - p) / n)` where *p* would be the expect probability and *n* is the number of probabilities. Th

**Comment by jreback** [comment]
I think this is out of scope for main pandas

**Comment by pmlandwehr** [comment]
dang, but thanks for the quick turnaround!
