### ISSUE TITLE
pd.to_datetime() flaw mixed behavior yielding inconsistant results

### ISSUE THREAD

**Issue by go2sree** [pandas-dev/pandas#27454]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
str1='05-01-2019 00:37' 
date1=pd.to_datetime(str1).date()
print(date1)

# output  2019-05-01


str2='15-01-2019 00:37' 
date2=pd.to_datetime(str2).date()
print(date2)

# output   2019-01-15

```
#### Problem description

pd.to_datetime( ) is giving inconsistant out put,  in the first piece of code where 01 is month and 05 is date after conversion these values have interchanged 01 as date and 05 as month.

but for similar code where the string value has 15 as date and 01 as month after conversion remained the same as expected.

I have tried .astype(‘datetime64’)   and this also yielded the same wrong values as above code

![image](https://user-images.githubusercontent.com/44897925/61456323-5f86f200-a983-11e9-8648-62e8f05afd0a.png)

![image](https://user-images.githubusercontent.com/44897925/61456389-88a78280-a983-11e9-86e8-6b3de726cc96.png)

![image](https://user-images.githubusercontent.com/44897925/61456419-9c52e900-a983-11e9-9d74-0eb3835f6fcd.png)

Is this a known Issue and please provide workaround

**Comment by jbrockmendel** [comment]
to_datetime uses datetutil under the hood, which has to try to infer whether an input uses dayfirst or monthfirst style dates.  For 15-01-2019 it is unambiguously dayfirst, but for 05-01-2019 it could be either, and it defaults to monthfirst.  Passing the arg `monthfirst=True` with `to_datetime` should resolve this.
