### ISSUE TITLE
missing pandas.core.config in v0.25

### ISSUE THREAD

**Issue by Borda** [pandas-dev/pandas#27471]
### Problem description

I need a print table with several columns by default for automatic test purposes while the default number of columns changed from version v0.23. I was using a simple check
```python
if 'display.max_columns' in pandas.core.config._registered_options:
    pandas.set_option('display.max_columns', 20)
```
but this was broken from v0.25 since the config is missing
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pandas.core' has no attribute 'config'
```
I have checked the [release notes](https://pandas-docs.github.io/pandas-docs-travis/whatsnew/v0.25.0.html) but I dd not find any info about moving this property...

### Code Sample

```python
.core.config._registered_options
```

### Expected Output

Extending the columns to be shown

### Output of ``pd.show_versions()``

```
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-54-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.0
numpy            : 1.15.4
pytz             : 2018.7
dateutil         : 2.7.5
pip              : 19.1.1
```

**Comment by jreback** [comment]
pandas.core has been private for quite a while

i would just call the pd.set_option()

**Comment by Borda** [comment]
@jreback well and `pd.set_option()` is there since when? what does it mean "quite a while"?

**Comment by jreback** [comment]
> @jreback well and `pd.set_option()` is there since when? what does it mean "quite a while"?

years

**Comment by Borda** [comment]
does not say anything since we need some legacy `pandas` versions...

**Comment by jreback** [comment]
you are using kong private api

use at your own risk

**Comment by Borda** [comment]
sorry, but `pandas.core.config` does not look like private... :-D

**Comment by TomAugspurger** [comment]
Unfortunately, it's only documented as private: https://pandas.pydata.org/pandas-docs/stable/reference/index.html

Changing it to `_core` would likely be too disruptive at this stage.

**Comment by jreback** [comment]
> Unfortunately, it's only documented as private: https://pandas.pydata.org/pandas-docs/stable/reference/index.html
> 
> Changing it to `_core` would likely be too disruptive at this stage.

i disagree 

i am going to deprecate this 

otherwise we will never get out of this hole

**Comment by TomAugspurger** [comment]
May be worth trying (starting with a DeprecationWarning, right?) Then
moving to FutureWarning?

**Comment by jreback** [comment]
> May be worth trying (starting with a DeprecationWarning, right?) Then moving to FutureWarning?
> […](#)

yeah maybe
