### ISSUE TITLE
BUG: Groupby.transform('cumcount') fails

### ISSUE THREAD

**Issue by ghost** [pandas-dev/pandas#27472]
Adding tests for #27467 surfaced some bugs:

```python
from pandas import *
df = DataFrame(dict(a=[0, 0, 0, 1, 1, 1], b=range(6)))
g = df.groupby(np.repeat([0,1], 3))
# ok
g.cumcount()
# fails
g.transform('cumcount')
AttributeError: ("'Series' object has no attribute 'cumcount'", 'occurred at index a')
```

`cumcount` is a cythonized function.

**Comment by jreback** [comment]
rather than make an issue for each one of .transform()
just create a checkbox list in one issue

**Comment by pilkibun** [comment]
Ok, but not all of these are the same bug though.

**Comment by jreback** [comment]
that’s fine you can edit the top and mark them off individually
they are just must easier to find / grok

**Comment by TomAugspurger** [comment]
Stalled PR at https://github.com/pandas-dev/pandas/pull/27858, if anyone wants to update.

Removing from the 1.0 milestone, but if a PR comes in we would certainly take it for 1.0.

**Comment by mroeschke** [comment]
I think this works on master now. Could use a test

```
In [3]: from pandas import *
   ...: df = DataFrame(dict(a=[0, 0, 0, 1, 1, 1], b=range(6)))
   ...: g = df.groupby(np.repeat([0,1], 3))
   ...: # ok
   ...: g.cumcount()
   ...: # fails
   ...: g.transform('cumcount')
Out[3]:
0    0
1    1
2    2
3    0
4    1
5    2
dtype: int64
```

**Comment by saehuihwang** [comment]
take
