### ISSUE TITLE
BUG: Missing documentation for read_spss()

### ISSUE THREAD

**Issue by isantolin** [pandas-dev/pandas#27476]
#### Problem description

New added feature read_spss() #26537 doesn´t still have any kind of documentation about it http://pandas-docs.github.io/pandas-docs-travis/user_guide/io.html

**Comment by TomAugspurger** [comment]
We'll want to add

1. an entry in the table in `user_guide/io.rst`
2. A small doc section in `user_guide/io.rst` explaining things
3. API docs in `reference/io.rst`

**Comment by yanglinlee** [comment]
I'll take this task.

**Comment by mgrout81** [comment]
Where can one find the documentation? It is not appearing here at this time: https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html.

**Comment by isantolin** [comment]
@mgrout81 not appears because is not released on stable branch yet. Please check at https://dev.pandas.io/user_guide/io.html
