### ISSUE TITLE
BUG: Groupby.quantile segfaults for quantile > 1

### ISSUE THREAD

**Issue by pilkibun** [pandas-dev/pandas#27470]
Adding tests for #27467 surfaced some bugs:

```python
from pandas import *
df = DataFrame(dict(a=[0, 0, 0, 1, 1, 1], b=range(6)))
g = df.groupby(np.repeat([0,1], 3))
# ok
g.quantile(50)
<segfault>
```
quantile accepts floats in `[0,1]` or arrays of floats. It appears not to validate the range though.

**Comment by jbrockmendel** [comment]
Apparently this is platform specific.  Works fine for me on OSX with numpy 1.16.4, segfaults on Ubuntu 18.04 with numpy 1.16.2

**Comment by pilkibun** [comment]
Thanks for investigating
