### ISSUE TITLE
REF: Define ExtensionDtype subclasses in consistent locations

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#27487]
`CategoricalDtype`, `DatetimeTZDtype`, `PeriodDtype`, and `IntervalDtype` are defined in `core.dtypes.dtypes`. `_IntegerDtype`, `PandasDtype`, and `SparseDtype` are defined in `core.arrays.*`.  We should be consistent about where these are defined.

My hobby horse right now is the dependency structure.  `core.dtypes` is _almost_ independent of the rest of `core`, and the code would be appreciably easier to reason about if that separation were strict.  To make that work we would need to either

a) move SparseDType etc into `core.dtypes.dtypes` and deal with the handful of imports that the Dtype classes require
b) move CategoricalDType etc over to the `core.array` modules and find a way to avoid the need for these DType classes in `dtypes.common` functions.

a) sounds significantly easier to me.

**Comment by TomAugspurger** [comment]
Either arrangement sounds fine to me. If collecting the dtypes in a common
location makes other things easier then lets go with that.

**Comment by jbrockmendel** [comment]
Another option in b) category in the spirit of @jorisvandenbossche 's goal of treating internal/external EAs symmetrically would be to remove the functions in dtypes.common that use our ExtensionDTypes directly and instead implement something like `is_dtype(obj, name)` that is hooked in to by `register_extension_dtype`
