### ISSUE TITLE
ASV Benchmark for read_excel

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#27485]
Right now we don't benchmark performance of read_excel across the various engines (xlrd, openpyxl and odfpy) so would gladly accept contributions to improve benchmark coverage on those

**Comment by sameshl** [comment]
@WillAyd I would like to work on this. 
Correct me if I am wrong but aren't we doing exactly that by seeing this [code](https://github.com/pandas-dev/pandas/blob/5bd57f90c3e8a714c77ca559d63409644c36c5ef/asv_bench/benchmarks/io/excel.py#L7-L36) ?

**Comment by WillAyd** [comment]
We don't actually parametrize `read_excel` in those benchmarks so they run continuously for xlrd. Need to leverage the parametrization by at a minimum doing `engine=engine` in the read_excel test, but then also may need to account for the various file formats

**Comment by f6v** [comment]
I'll prepare a PR for this.
