### ISSUE TITLE
BUG: Groupby.transform(name) should only accept valid names

### ISSUE THREAD

**Issue by pilkibun** [pandas-dev/pandas#27486]
https://github.com/pandas-dev/pandas/pull/27467#discussion_r305439508

Examples:
- `g.transform('invalid_name')`
- `g.transform('agg')`, attribute exists but isn't appropriate agg/transformation.

**Comment by Lucas-Marchand** [comment]
jreback, if this isn't already being worked on I would like to give it a shot at resolving this issue and contributing to the project

**Comment by pilkibun** [comment]
@Lucas-Marchand  #27467 is supposed to close this.

**Comment by Lucas-Marchand** [comment]
good to know that these issues are actively being worked on! I will look around for other issues I can help contribute to.
