### ISSUE TITLE
Nanosecond resolution in time indexing

### ISSUE THREAD

**Issue by p5a0u9l** [pandas-dev/pandas#27497]
I have a dataframe with `DatetimeIndex`. I note the following difference of behavior in `0.24.2` against `0.25.0`. 

For equivalent Timestamp indices, `0.25.0` returns an empty Series, while `0.24.2` returns one value. 

```python
print(start)
Timestamp('2019-06-24 16:56:11.200999936')
print(stop)
Timestamp('2019-06-24 16:56:11.200999936')

# pandas 0.24.2
df2.loc[start:stop, ["time"]]
                        time
time
2019-06-24 16:56:11.201  NaT

# pandas 0.25
df2.loc[start:stop, "time"]
Series([], Name: time, dtype: datetime64[ns])
```

I expect this is actually a good thing as before, indicated above, time indexes didn't respect upper-bound exclusivity and now they do. 

### Question 1

I looked through release notes for `0.25.0` and didn't find anything mentioning this particular behavior change. Is this upper-bound exclusivity expected for DatetimeIndex frame slicing?

### Question 2

Sometimes I want to ensure a slice is upper-bound inclusive. To adapt, I'm attempting to add a nanosecond to the `stop` variable above. 

```python
ipdb> df2.loc[start:stop + pd.Timedelta(nanoseconds=1), ["time"]]
Empty DataFrame
Columns: [time]
Index: []
```
But this returns an empty dataframe. It doesn't produce the expected behavior until I set `nanoseconds=70`. 

Is this actually expected? What is the mechanism for producing a distinct Timestamp slice?

**Comment by jbrockmendel** [comment]
Can you post code that can be copy/pasted to reproduce the behavior?

**Comment by p5a0u9l** [comment]
Relevant to Question 2 - 

```python
import numpy as np
import pandas as pd

print(f"Pandas: v{pd.__version__}")

df = pd.DataFrame(
    {
        "r_tr": {
            pd.Timestamp("2019-06-24 16:56:11.050000"): np.nan,
            pd.Timestamp("2019-06-24 16:56:11.111000"): np.nan,
            pd.Timestamp("2019-06-24 16:56:11.162000"): np.nan,
            pd.Timestamp("2019-06-24 16:56:11.200999936"): 162.305,
            pd.Timestamp("2019-06-24 16:56:11.213000"): np.nan,
            pd.Timestamp("2019-06-24 16:56:11.274000"): np.nan,
            pd.Timestamp("2019-06-24 16:56:11.325000"): np.nan,
            pd.Timestamp("2019-06-24 16:56:11.386000"): np.nan,
        }
    }
)

start = pd.Timestamp("2019-06-24 16:56:11.200999936")
stop = pd.Timestamp("2019-06-24 16:56:11.200999936")

print(df.loc[start:stop, ["r_tr"]])
```

Unfortunately, for me, this produces the same results on both mentioned versions. I attempted to extract a representative sample from the dataframe that was causing above results, but maybe I missed something.

**Comment by jbrockmendel** [comment]
re question 2: pandas slicing with `loc` should be upper-bound-inclusive, so `df.loc[start:stop]` should be giving a single-row DataFrame.  This is what I get on master.  It sounds from your second comment that you are now getting the expected result here?

**Comment by jbrockmendel** [comment]
@p5a0u9l is there a remaining issue to be addressed here?

**Comment by p5a0u9l** [comment]
I think there may well be, but I’m unable to reproduce. I am fine if you
want to close this issue.

**Comment by mroeschke** [comment]
Feel free to open another issue if you rediscover the incorrect behavior.
