### ISSUE TITLE
Timestamp unit is not respected

### ISSUE THREAD

**Issue by david-cortes** [pandas-dev/pandas#27490]
Timestamps always get returned in nanoseconds regardless of the unit I specify:
```python
import numpy as np, pandas as pd
np.datetime64("2018-01-01").astype("datetime64[s]").astype(int)
>>> 1514764800
pd.Series(np.datetime64("2018-01-01")).astype("datetime64[s]")
```
```
0   2018-01-01
dtype: datetime64[ns]
```
```python
pd.Series(np.datetime64("2018-01-01")).astype("datetime64[s]").astype(int)
```
```
0    1514764800000000000
dtype: int64
```

**Comment by TomAugspurger** [comment]
Pandas doesn't support non-ns resolution.

As of pandas 0.21, we raised on the `Series[datetime64[ns]].astype('datetime64[s]')`. It seems we don't raise any more, which may be a bug.

**Comment by marceloid** [comment]
Can confirm that as of pandas 1.2.3 the `Series[datetime64[ns]].astype('datetime64[s]')` doesn't raise any exception, and it still returns ns values.

**Comment by jbrockmendel** [comment]
In 2.0 pandas supports s, ms, us, and ns.  Closing.
