### ISSUE TITLE
Remove DataFrame.append from the 10min intro

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#27518]
We show it https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html#append.

I don't think we should recommend it there, especially without providing context that the complexity of DataFrame.append is very different from list.append.

**Comment by sameshl** [comment]
@TomAugspurger I understand what you mean. But don't you think that for a new user `append` function might be useful?

**Comment by TomAugspurger** [comment]
No I don't think so. I think for that use case we should recommend building
up a list of rows, then wrapping in a Series / DataFrame, then appending.
I'm not sure whether something like that belongs in a 10-minute
introduction though.

**Comment by sameshl** [comment]
Yeah, you are right. `dataframe.append` is not as trivial as `list.append`. I could fix this issue then

**Comment by ParfaitG** [comment]
Agreed with @TomAugspurger . Occasionally on StackOverflow, you see new users running `DataFrame.append`  inside a loop in same fashion as they would with `list.append` , leading to the hazardous quadratic copy. Therefore, leaving it out of an intro to new users may be beneficial:

```python
# INITIALIZE AN EMPTY DATA FRAME
df = pd.DataFrame()

for i in range(5):
    # GROW DATA FRAME IN LOOP
    df = pd.DataFrame({'int': np.random.randint(1, 10, 500),
                       'num': np.random.uniform(0, 1, 500)
		       })
    df = df.append(df)
```

As the numpy/pandas guru, @unutbu admonishes: [Never call DataFrame.append or pd.concat inside a for-loop. It leads to quadratic copying.](https://stackoverflow.com/a/36489724/1422451)
