### ISSUE TITLE
Inconsistent SettingWithCopyError behaviour

### ISSUE THREAD

**Issue by kasparthommen** [pandas-dev/pandas#27524]
Consider the following minimal example:

```python
import pandas as pd

if __name__ == '__main__':
    pd.options.mode.chained_assignment = 'raise'

    # two identical data frames
    df1 = pd.DataFrame(data=[[1, 2], [3, 4]], columns=['c1', 'c2'])
    df2 = pd.DataFrame(data=[[1, 2], [3, 4]], columns=['c1', 'c2'])

    # manipulate df1 a bit
    df1 = df1[~df1.c1.isin([3])]
    df1['c3'] = 'foo'

    # a function doing the exact same manipulations
    def f(df):
        df = df[~df.c1.isin([3])]
        df['c3'] = 'foo'

    # call that function with df2 - boom
    f(df2)
```
#### Problem description

Note that the manipulations on `df1` execute with no issues. The function call `f(df2)`, however, which does the exact same thing, fails with a SettingWithCopyError.

#### Expected Output
1. I don't see why that error should be thrown in the first place because I don't see a 'chained assignment'.

2. It's inconsistent that the behavior for df1 and df2 is different despite the same code being executed on those two identical data frames.

3. If I'm wrong and the error does indeed make sense for the function call for whatever reason then I wonder how I'm supposed to perform these manipulations in a function without the error being thrown and without unnecessarily calling `.copy()` after each manipulation step.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.2
pytest: None
pip: 19.1
setuptools: 41.0.1
Cython: None
numpy: 1.16.3
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.5.0
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.3
openpyxl: None
xlrd: 1.2.0
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: 4.7.1
html5lib: None
sqlalchemy: 1.3.3
pymysql: None
psycopg2: 2.8.2 (dt dec pq3 ext lo64)
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by TomAugspurger** [comment]
> I don't see why that error should be thrown in the first place because I don't see a 'chained assignment'.

When you assign to `df1['c3'] = 'foo'`, that `df1` may or may not be a view on the original `df1`.

> It's inconsistent that the behavior for df1 and df2 is different despite the same code being executed on those two identical data frames.

I believe pandas uses weakrefs for detecting references to the data. It's possible python's function machinery adds a reference. Can you take a look?

**Comment by kasparthommen** [comment]
@TomAugspurger Thanks for your reply.

> When you assign to `df1['c3'] = 'foo'`, that `df1` may or may not be a view on the original `df1`.

Fair enough. Would you mind answering the following question then please:

**What is the official way to perform multiple filtering and manipulation steps (including adding columns) in a function while avoiding the SettingWithCopyError issues then?**

I have tried using the usual `.loc` approach, but that didn't help. I hope the solution isn't to append `.copy()` to every other manipulation step because I'm typically working with big data frames...

> I believe pandas uses weakrefs for detecting references to the data. It's possible python's function machinery adds a reference. Can you take a look?

Not quite. The weakref gets assigned during the construction of the "new" `df1` when performing the first filter operation, and it points to the "original" `df1`. Later on, in this code section,

https://github.com/pandas-dev/pandas/blob/0.24.x/pandas/core/generic.py#L3244-L3248

the GC  is called to see if the reference still exists, which it doesn't (as the original `df1` is gone), so no issue. However, in the function call case with `df2` the reference to the original `df2` remains intact because it still lives outside the function. Therefore the GC call doesn't remove the link, and the issue arises.

So it's not that the "function machinery adds a reference" but rather that a genuine reference between the unmodified `df2` in `main()` and the modified `df2`in `f()` survives the GC call.

I tried changing the last line to:

```df2 = f(df2)```

in the hope that the interpreter might realize that the original `df2` reference won't be needed anymore after the function call has ended, but that doesn't work.

I have also tried the latest 0.25.0 version which handles reference resolution a bit more smartly (no GC call), but the issue remains the same.

**Comment by TomAugspurger** [comment]
On Tue, Jul 23, 2019 at 2:05 AM kasparthommen <notifications@github.com>
wrote:

> @TomAugspurger <https://github.com/TomAugspurger> Thanks for your reply.
>
> When you assign to df1['c3'] = 'foo', that df1 may or may not be a view
> on the original df1.
>
> Fair enough. Would you mind answering the following question then please:
>
> *What is the official way to perform multiple filtering and manipulation
> steps (including adding columns) in a function while avoiding the
> SettingWithCopyError issues then?*
>
A copy before assigning is probably safest.

**Comment by kasparthommen** [comment]
Thanks, I'll do that.

So is this behavior considered a feature, not a bug, despite the inconsistent behavior between inline manipulation and manipulations in a function? To be filed as acceptable false positive warning?

**Comment by TomAugspurger** [comment]
I'm not sure what's going on in the function vs. top-level cases.

**Comment by kasparthommen** [comment]
As I wrote in https://github.com/pandas-dev/pandas/issues/27524#issuecomment-514082035 the reference from an updated data frame object to its original is dropped in the inline case because the original get overwritten and thus GC'ed, so no reference to worry about. In the function case, however, the updated data frame continues to reference the original data frame outside the function, making the logic think it's a chained invocation, which it isn't.

**Comment by jreback** [comment]
@kasparthommen SettingwithCopyWarning is a work around to avoid other bad things because of limitations in python and no copy on write.

This is not a bug as there is a reference inside the closure.

**Comment by jreback** [comment]
You can certainly have a look to see if it’s possible to avoid in this case, while preserving all other cases and performance. good luck this is very thorny.

**Comment by kasparthommen** [comment]
Closing as "feature, not bug".
