### ISSUE TITLE
STY: add pandas._typing to the known_pre_core block for isort

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#27534]

**Comment by sameshl** [comment]
I looked into the `isort` section of `setup.cfg` and was not able to identify which is the no-dependencies block. Can you help me out ?

**Comment by jbrockmendel** [comment]
Good question, by "no-dependencies" I meant "known_pre_core".  I'll update the issue name to clarify.  If you want to jump on this, go for it!

**Comment by sameshl** [comment]
Thanks for the help! I will take this up :smile:

**Comment by alimcmaster1** [comment]
take
