### ISSUE TITLE
memory usage of index changes after access

### ISSUE THREAD

**Issue by jp68138743541** [pandas-dev/pandas#27540]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np

index = list(range(1000))
df = pd.DataFrame(data=np.random.rand(1000,10), index = index)
df.head()

print("This is the memory usage before accessing the DataFrame:")
print(df.memory_usage(index=True))

_ = df.loc[df.first_valid_index(),:] # Accessing the DataFrame without modifying it

print("This is the memory usage after accessing the DataFrame:")
print(df.memory_usage(index=True))
```
Output:
```
This is the memory usage before accessing the DataFrame:
Index    8000
0        8000
1        8000
2        8000
3        8000
4        8000
5        8000
6        8000
7        8000
8        8000
9        8000
dtype: int64
This is the memory usage after accessing the DataFrame:
Index    48960
0         8000
1         8000
2         8000
3         8000
4         8000
5         8000
6         8000
7         8000
8         8000
9         8000
dtype: int64
```
#### Problem description

The memory usage increases after accessing the dataframe, although the access should not modify the index at all. I expected the memory usage not to change.

#### Expected Output
```
This is the memory usage before accessing the DataFrame:
Index    8000
0        8000
1        8000
2        8000
3        8000
4        8000
5        8000
6        8000
7        8000
8        8000
9        8000
dtype: int64
This is the memory usage after accessing the DataFrame:
Index    8000
0         8000
1         8000
2         8000
3         8000
4         8000
5         8000
6         8000
7         8000
8         8000
9         8000
dtype: int64
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.125-linuxkit
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 5.0.1
pip: 19.1.1
setuptools: 41.0.1
Cython: 0.29.11
numpy: 1.16.4
scipy: 1.2.1
pyarrow: None
xarray: 0.12.1
IPython: 7.6.1
sphinx: None
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: 3.5.2
numexpr: 2.6.9
feather: None
matplotlib: 3.1.0
openpyxl: None
xlrd: 1.2.0
xlwt: None
xlsxwriter: 1.1.8
lxml.etree: 4.3.4
bs4: 4.7.1
html5lib: None
sqlalchemy: 1.3.5
pymysql: None
psycopg2: 2.7.6.1 (dt dec pq3 ext lo64)
jinja2: 2.10.1
s3fs: None
fastparquet: 0.3.0
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by jreback** [comment]
this is as expected. accessing an index creates a c-level hash table for looking things up. if you just hold indexes you just see memory requirements of holding it and not using it for indexing.
