### ISSUE TITLE
Adhere to the standard for dropping Python versions

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#27557]
Maintainers from several scientific Python projects are defining a standard to for all projects to drop support of old Python versions in a synchronized way. The standard is defined in this PR: https://github.com/numpy/numpy/pull/14086

I think pandas is already quite synchronized with the rest of the ecosystem, and I think the timeline of the standard matches what we have in mind in the short term (stopping support of Python 3.5 in the next release).

I create this issue to have a discussion in case anyone has comments. And I propose that if there is agreement, we adhere to the standard formally.

**Comment by TomAugspurger** [comment]
+1 to adopting it.

**Comment by jorisvandenbossche** [comment]
+1 as well

**Comment by jbrockmendel** [comment]
Works for me.

**Comment by simonjayhawkins** [comment]
from https://numpy.org/neps/nep-0029-deprecation_policy.html#implementation

Implementation
We suggest that all projects adopt the following language into their development guidelines:

This project supports:

All minor versions of Python released 42 months prior to the project, and at minimum the two latest minor versions.

All minor versions of numpy released in the 24 months prior to the project, and at minimum the last thee minor versions.

In setup.py, the python_requires variable should be set to the minimum supported version of Python. All supported minor versions of Python should be in the test matrix and have binary artifacts built for the release.

Minimum Python and NumPy version support should be adjusted upward on every major and minor release, but never on a patch release.

**Comment by mroeschke** [comment]
Thing all that's left is documenting that we mirror numpy in https://pandas.pydata.org/docs/development/policies.html

**Comment by Sadin** [comment]
Hello all, what needs to be updated? Docs?

**Comment by MarcoGorelli** [comment]
That's right

**Comment by JosephParampathu** [comment]
take
