### ISSUE TITLE
`OptionError` raised by top-level function `pandas.set_option` is private

### ISSUE THREAD

**Issue by huandzh** [pandas-dev/pandas#27553]
#### Code Sample

```python
import pandas as pd
from pandas.errors import OptionError 
# or from pandas import OptionError
option = ('noexist', 1)
try:
    pd.set_option(*option)
except OptionError as e:
    print('Ignore invaild option: {}'.format(option))
```
#### Problem description

`OptionError` is raised by top-level function `pandas.set_option`, but can only be imported from private module `pandas._config.config`.

Sample code will failed when importing it from `pandas.errors`  :

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-62b92256ce5f> in <module>
      1 import pandas as pd
----> 2 from pandas.errors import OptionError # or from pandas import OptionError
      3 option = ('noexist', 1)
      4 try:
      5     pd.set_option(*option)

ImportError: cannot import name 'OptionError' from 'pandas.errors' (/home/abc/.local/share/virtualenvs/abc-jIQt2SYy/lib/python3.7/site-packages/pandas/errors/__init__.py)
```

#### Expected Output

```
Ignored invaild option: ('noexist', 1)
```

Expected behavior : `OptionError` can be imported from `pandas.errors` or `pandas`. And other custom exceptions raised by top-level functions are also available in the same public namespace.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.4.0-17763-Microsoft
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.0
numpy            : 1.16.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.1.1
setuptools       : 41.0.1
Cython           : 0.29.12
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.6.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None

</details>

**Comment by huandzh** [comment]
see also #19790

**Comment by simonjayhawkins** [comment]
@huandzh Thanks for the report.

**Comment by huandzh** [comment]
@simonjayhawkins Glad to help.

**Comment by jorisvandenbossche** [comment]
cc @jbrockmendel I think you recently put effort in separating the `_config` module from the rest of pandas I think? So putting the error in `pandas.errors` and importing that in `pd._config.config` would break that pattern?

(we could also easily, for such case, import the error from pandas._config.config into pandas.errors)

**Comment by jorisvandenbossche** [comment]
See also https://github.com/pandas-dev/pandas/issues/27656, I made a general issue for all custom errors/warnings.

**Comment by jbrockmendel** [comment]
The idea for _config is to treat it as entirely upstream of the rest of pandas, so yah, importing it into pandas.errors is teh way to go.
