### ISSUE TITLE
BUG: dir(IntervalIndex()) raises

### ISSUE THREAD

**Issue by pilkibun** [pandas-dev/pandas#27571]
```python

In [8]: ix=pd.IntervalIndex.from_breaks([0,1,2])
   ...: dir(ix)
...
ValueError: cannot infer type for <class 'NoneType'>

```

**Comment by jschendel** [comment]
Thanks for the report @pilkibun! I can confirm this behavior.  Interestingly, `dir(pd.IntervalIndex)` is fine, it's just a constructed `IntervalIndex` that fails.

**Comment by jbrockmendel** [comment]
Looks like in it is calling `ix.str` and taht calls `lib.infer_dtype` which raises because its not looking at an ndarray

**Comment by vishwakftw** [comment]
I'm new to the project, but from a cursory glance of the documentation `pd.IntervalIndex.from_breaks` only accepts array-likes, and `range(3)` is not an array-like (based on `pd.core.dtypes.inference.is_array_like`.

So, isn't `range(3)` technically an incorrect input?

**Comment by TomAugspurger** [comment]
@vishwakftw the docs for IntervalIndex.from_breaks should maybe be updated to require "list-like" rather than "array-like". I haven't looked closely.

That said, I think that's separate from the issue @pilkibun reported.
