### ISSUE TITLE
Add a new DataFrame.dti accessor

### ISSUE THREAD

**Issue by ghost** [pandas-dev/pandas#27581]
There's the `dt` accessor on Series which operates on the Series values:
``` 
pd.Series([1,2,3]).dt.day 
#exists. But checks that series *values*  datetime64[ns]

pd.Series([1,2,3]).day
# doesn't exist
```

There's a top-level method `df.first`:
```
Convenience method for subsetting initial periods of time series data
based on a date offset.
```
which looks like it should live behind `dti` accessor on DataFrame.
```
pd.DataFrame().first(0) 
# method is applicable only for datetime, but is in the top DataFrame namespace
```

There's currently no datetime accessor on dataframe. Would it make sense to move it below a `dti` accessor on DataFrame?  

There's also an unfortunate unfortunate name collision between`Groupby().first`
```
Compute first of group values.
```
and `DataFrame.first`:
```
Convenience method for subsetting initial periods of time series data
based on a date offset.
```
Adding a `dti` accessor to DataFrame would clean that up as well.

**Comment by WillAyd** [comment]
Not sure about the idea of a data frame accessor. In the Series world when thinking about an accessor it operates on the values; this would essentially operate on the index of the object so I think not super clean from an API perspective.

Agreed though the naming of `first` isn't intuitive and does clash with other items in the API. Have you thought of anything outside the accessor? Maybe we just need to rename the function (the more verbose `first_offset`?)

**Comment by pilkibun** [comment]
That's a good point. I was thinking of accessors as a way to offer methods conditionally, which fits here. But I agree that the convention is for accessors to operate on the object they are extending.

For one method, doing this wouldn't make sense. I'll see if there are others, and if not perhaps a name change really is the simplest solution. Thanks.

**Comment by WillAyd** [comment]
Yea my wording was slightly off but I think we are on the same page. If you find others lmk otherwise maybe we just repurpose this issue to focus solely on the `first` naming inconsistency

**Comment by pilkibun** [comment]
ok, sounds good.

**Comment by pilkibun** [comment]
```
first       
asfreq
asof 
at_time
between_time
tshift 
tz_convert
tz_localize 
```

all the above are DataFrame methods which are candidates for moving beneath a dti accessor. 

We might want to rename `first` even if it were moved.

**Comment by mroeschke** [comment]
Thanks for the suggestion, but sounds like the community and other core devs have not expressed further interest in a dti accessor. Closing but happy to reopen if theres further interest
