### ISSUE TITLE
Add NumPy Stubs

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#27589]
We use ndarray often in our annotations, but it always just resolves to `Any` since it doesn't have any annotations natively. It looks like numpy has a separate Numpy-stubs repo under development:

https://github.com/numpy/numpy-stubs

Might be worth considering that as a development dependency. Certainly would like to find issues with ndarray usage sooner than later

@shoyer

**Comment by jbrockmendel** [comment]
MIght be a pipedream, but it would be nice if we could have numpy annotations consistent with the existing cython syntax, e.g. `ndarray[np.float64, ndim=1]`.  Both for the consistency and the specificity.

**Comment by shoyer** [comment]
Yes, it's much bigger project to figure out a type system from
multidimensional arrays. Some of the mypy devs are working on it.
.
Right now numpy-stubs could use some love. It would be great to get some
contributions there.

**Comment by simonjayhawkins** [comment]
@WillAyd With numpy types imminent, I think we can now close this issue. feel free to reopen if disagree.
