### ISSUE TITLE
merge_asof parameters "index", "prefix"

### ISSUE THREAD

**Issue by darkdragon-001** [pandas-dev/pandas#27582]
Add convenience parameter `index` which sets both `left_index` and `right_index`. This should default to `True` when no `on` parameter is set.

Further, add parameter `prefix` with the same behavior as `suffix` but instead add this before the original label.

**Comment by WillAyd** [comment]
Joining by index is what `.join` does - is that what you are asking for with the first request?

W.r.t prefix I don't know if we really want to add another keyword for that; our API is already rather bloated so we tend to not add one-off things unless they provide a lot of value

**Comment by darkdragon-001** [comment]
> Joining by index is what `.join` does - is that what you are asking for with the first request?

I have two dataframes with indices of type `pd.Timestamp`. I want to merge with `direction='backward'` to match the previous timestamp.

Therefore, I use the following code currently:

    pd.merge_asof(df, df2, left_index=True, right_index=True, direction='backward')

Since I think adding the `direction` parameter to `.join` would contradict the join semantics, I suggest adding the `index` parameter. It would also match the current APIs structure since `on` and `by` both have versions with `left_` and `right_` prefixes, so only index is missing.

**Comment by mroeschke** [comment]
Thanks for the suggestion but agreed that this appears like a niche keyword and providing the values of `left_*` and `right_*` is more explicit and provides one clear way to do things. Since there hasn't been much support for this feature from other core devs or the community, closing, but happy to reopen if there's further interest from both parties.
