### ISSUE TITLE
[DOC] Tautological/recursive `See also` link

### ISSUE THREAD

**Issue by rs2** [pandas-dev/pandas#27609]
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isnull.html#pandas.DataFrame.isnull

Please assign to me.

**Comment by topper-123** [comment]
I don't think this is self-referencing: The first ``pandas.DataFrame.isnull`` references the page, while the second ``pandas.DataFrame.isnull`` references the anchor inside the page.

I'm closing, but yu can open again, if you misunderstand each other.
