### ISSUE TITLE
'cx_Oracle.LOB‘ object is not subscriptable

### ISSUE THREAD

**Issue by liyizhecn** [pandas-dev/pandas#27605]
> ENV
```
centos 7
python3.6  64-bit
cx-Oracle==7.2.0
pandas==0.24.2
Oracle client  12.1
Oracle 12.1
ORACLE_HOME=/usr/lib/oracle/12.1/client64
NLS_LANG=SIMPLIFIED CHINESE_CHINA.UTF8
```
> CODE
```python
import pandas as pd
import cx_Oracle as co

con = co.connect(client, mode=co.SYSASM)
sql = f"select * from {table}"
df = pd.read_sql(sql, con)
data = df.select_dtypes(include=['object'])
```

> ERROR
```
'cx_Oracle.LOB‘ object is not subscriptable
```

> Q
```
How to use pandas to get values for other fields that are not of type LOB
```
> LINK

[the discuss of cx_Oracle forum](https://github.com/oracle/python-cx_Oracle/issues/336)

**Comment by Liam3851** [comment]
pandas read_sql [does not support DBAPI2 connections for databases other than sqlite](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_sql.html). Try the [SQLAlchemy connector to Oracle](https://docs.sqlalchemy.org/en/13/dialects/oracle.html#module-sqlalchemy.dialects.oracle.cx_oracle) instead.

**Comment by jorisvandenbossche** [comment]
@liyizhecn can you give the full error traceback?

**Comment by jorisvandenbossche** [comment]
(sidenote: it is correct that we only support sqlalchemy connections (except for sqlite) in theory, but in practice  `read_sql` with a query has mostly worked with raw connections as well (as opposed to `read_sql_table` / `read_sql` with a table name / `to_sql` which for sure require sqlalchemy). So I am still curious what is going wrong here.

**Comment by liyizhecn** [comment]
> pandas read_sql [does not support DBAPI2 connections for databases other than sqlite](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_sql.html). Try the [SQLAlchemy connector to Oracle](https://docs.sqlalchemy.org/en/13/dialects/oracle.html#module-sqlalchemy.dialects.oracle.cx_oracle) instead.

I'm sure it's not a connection problem, because I'm using this code to handle a large number of tables, and only a small percentage of the tables report this error.

**Comment by liyizhecn** [comment]
> (sidenote: it is correct that we only support sqlalchemy connections (except for sqlite) in theory, but in practice `read_sql` with a query has mostly worked with raw connections as well (as opposed to `read_sql_table` / `read_sql` with a table name / `to_sql` which for sure require sqlalchemy). So I am still curious what is going wrong here.

I am sorry that I only recorded the problem at the time. 
The database is on other company intranets and I will travel again soon.
Sample data and a full stack are available at that time.

**Comment by mroeschke** [comment]
@liyizhecn please post the full stack trace when you get the chance. We'll reopen this issue at that time.
