### ISSUE TITLE
Disable codecov

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#27602]
I figured worth opening a dedicated issue since I've seen it come up in conversations. We don't really get a lot out of codecov right now and it tends to just be a distraction in CI. I think best to remove from CI unless anyone objects or we have a plan to better utilize

Note this would supersede #12634

**Comment by jbrockmendel** [comment]
The posts it makes in PRs I usually ignore, but I've been using it to identify unused code following the Panel removal.

**Comment by TomAugspurger** [comment]
We've had issues uploading codecov output from Travis recently: https://travis-ci.org/pandas-dev/pandas/jobs/574712678

**Comment by jbrockmendel** [comment]
Disabling seems like a reasonable stopgap.  I didn't find anything helpful on the codecov support pages

**Comment by TomAugspurger** [comment]
Although.... this may be a config issue with our CI. Note that there's no output to the command in https://travis-ci.org/pandas-dev/pandas/jobs/574509202#L2778

**Comment by jbrockmendel** [comment]
Can/should we revert #28065?  Having 20-day old results on codecov is not great

**Comment by TomAugspurger** [comment]
Having it enabled would be preferred, as long as it's not breaking things.

**Comment by jbrockmendel** [comment]
@WillAyd closable?

**Comment by jbrockmendel** [comment]
re-opened, since codecov looks like it hasnt updated in 9 days

**Comment by jbrockmendel** [comment]
re-closed by #30380, codecov appears back up
