### ISSUE TITLE
Feature request: add the option of empty query to pandas.DataFrame.query

### ISSUE THREAD

**Issue by mariolovric** [pandas-dev/pandas#27608]
#### 
The idea is to give query the option to return the full dataframe, via some kind of "emtpy query".
I need this functionality quite often, since I am iterating on different querys.

Had an stackoverflow question on this here:
https://stackoverflow.com/questions/55933958/how-to-pass-an-empty-pandas-query/56982068#56982068

```python
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))

print(df.head())
#current option from stackoverflow
col = df.columns[0]
returned_df = df.query(f"{col}.isnull() or {col}.notnull()")

returned_df.head()

```

**Comment by TomAugspurger** [comment]
Initially, I'm slightly against special cases in `expr` just for this.

**Comment by mroeschke** [comment]
Thanks for the suggestion but agreed that this probably isn't worth a special case no-op. Since the community or other core devs haven't provided more support for this feature going to close. Happy to reopen if there's further interest from both parties
