### ISSUE TITLE
pandas.ExcelWriter has abstract methods

### ISSUE THREAD

**Issue by mhooreman** [pandas-dev/pandas#27634]
#### Code Sample, a copy-pastable example if possible

```python
"""Lorem ipsum"""

import pandas as pd


def demo():
    """Demo for the false positive"""
    with pd.ExcelWriter("demo.xlsx") as writer:
        print(writer)
```

#### Problem description

The code shown above gives pylint: ``abstract-class-instantiated(E0110): test.py:8:9: demo: Abstract class 'ExcelWriter' with abstract methods instantiated``

#### Expected Output

No pylint issue: no abstract method left

#### Output of ``pd.show_versions()``

<details>

```
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-54-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.0
numpy            : 1.16.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.2.1
setuptools       : 40.8.0
Cython           : 0.29.12
pytest           : 5.0.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.3.4
html5lib         : None
pymysql          : None
psycopg2         : 2.8.3 (dt dec pq3 ext lo64)
jinja2           : 2.10.1
IPython          : 7.6.1
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.4
matplotlib       : 3.1.1
numexpr          : 2.6.9
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.0
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : 1.1.8

```
</details>

**Comment by TomAugspurger** [comment]
cc @WillAyd. Is this a problem in practice?

**Comment by mhooreman** [comment]
Thanks @TomAugspurger 
Well, it's an exception in my code quality control checks which is difficult to justify. This is especially true because the abstract methods are documented nowhere, so that it is not under control.

**Comment by TomAugspurger** [comment]
@mhooreman you don't actually get back an object with abstract methods though.

```python
In [46]: f = pd.ExcelWriter('./foo.xlsx')

In [47]: type(f)
Out[47]: pandas.io.excel._xlsxwriter._XlsxWriter

In [48]: f.supported_extensions
Out[48]: ('.xlsx',)
```

So I'd rather say this is a limitation of pylint, that doesn't / can't introspect objects defining `__new__`.

**Comment by MarcSkovMadsen** [comment]
I have the same issue. Should this issue be reported to pylint instead?

**Comment by mhooreman** [comment]
Hi Mark,

Yes, indeed. But I didn't found time to do it now. Can you take it over ...
or wait a bit?

Thanks.

Le mar. 13 août 2019 à 15:14, Marc Skov Madsen <notifications@github.com> a
écrit :

**Comment by TomAugspurger** [comment]
Can you link back here with what you find from the pylint issue?

FWIW, this sounds somewhat difficult to do in practice. I'm not sure how pylint could know that the object returned by `ExcelWriter` is an instance of a subclass without actually executing code. I'm not sure whether they execute code or not.

**Comment by mhooreman** [comment]
@TomAugspurger , I don't really understand what you say. The code sample at the top of the thread shows the issue and, yes, it seems related to pylint.
I'll open the ticket on the pylint side, with a link to this one.

**Comment by mhooreman** [comment]
Created pylint ticket: https://github.com/PyCQA/pylint/issues/3060

**Comment by MarcSkovMadsen** [comment]
Sure I can wait. I have found my way around it. Thanks for the great work with the ExcelWriter.

**Comment by vule24** [comment]
If you feel that it's really annoying, add ` # pylint: disable=abstract-class-instantiated` right after `with` line: 

`with pd.ExcelWriter("demo.xlsx") as writer:  # pylint: disable=abstract-class-instantiated `

Pylint will temporarily ignore that line.

**Comment by mhooreman** [comment]
I know vule24, but it’s a workaround, and I don’t consider a good practice to disable tests which are enabled in the project.

Those disabling are even part of the metrics I have defined.

**Comment by mroeschke** [comment]
Looks like this issue is more related to pylint as opposed to pandas. Closing but happy to reopen if there's anything additional to do on the pandas side
