### ISSUE TITLE
Add a "scope" document

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#27649]
e.g. https://numpy.org/neps/scope.html

Some random thoughts

1. Focus on "user API for working with tabular data" (de-emphasize things like in-memory format, array library, algorithms)
2. Focus on "spirit" rather than strict rules.
3. Single-machine (but not necessarily single-core?)
4. In-memory only?
5. Visualization?
6. What readers / writers are in-scope?
7. What future extension types are in scope?

**Comment by jbrockmendel** [comment]
Discussed a couple of dev meetings back.  Consensus was this was poorly defined and a moving target.  Closing as no-action.
