### ISSUE TITLE
DataFrame.apply(to_numeric) breaks when `errors` arg is given

### ISSUE THREAD

**Issue by 4n4nd** [pandas-dev/pandas#27648]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

import pandas as pd

my_list = [["654645", "54854"], ["1654151", "1564484"]]
df = pd.DataFrame(my_list, columns=["ds", "y"])
df = df.apply(pd.to_numeric, args=({"errors": "coerce"}))
print(df)
```
#### Problem description
Running the above code in v0.25.0 raises an exception like:
```
Traceback (most recent call last):
  File "trash.py", line 5, in <module>
    df = df.apply(pd.to_numeric, args=({"errors":"coerce"}))
  File "/home/anand/miniconda3/envs/prophet-env/lib/python3.6/site-packages/pandas/core/frame.py", line 6906, in apply
    return op.get_result()
  File "/home/anand/miniconda3/envs/prophet-env/lib/python3.6/site-packages/pandas/core/apply.py", line 186, in get_result
    return self.apply_standard()
  File "/home/anand/miniconda3/envs/prophet-env/lib/python3.6/site-packages/pandas/core/apply.py", line 292, in apply_standard
    self.apply_series_generator()
  File "/home/anand/miniconda3/envs/prophet-env/lib/python3.6/site-packages/pandas/core/apply.py", line 321, in apply_series_generator
    results[i] = self.f(v)
  File "/home/anand/miniconda3/envs/prophet-env/lib/python3.6/site-packages/pandas/core/apply.py", line 112, in f
    return func(x, *args, **kwds)
  File "/home/anand/miniconda3/envs/prophet-env/lib/python3.6/site-packages/pandas/core/tools/numeric.py", line 114, in to_numeric
    raise ValueError("invalid error value specified")
ValueError: ('invalid error value specified', 'occurred at index ds')
```
The error persists for any value for the `errors` arg.
This worked fine in v0.24.2

#### Expected Output
```
        ds        y
0   654645    54854
1  1654151  1564484
```
#### Output of ``pd.show_versions()``

<details>

Working setup:
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Linux
OS-release: 5.1.18-300.fc30.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: None
pip: 19.1.1
setuptools: 41.0.1
Cython: 0.29.11
numpy: 1.16.4
scipy: None
pyarrow: None
xarray: None
IPython: 7.6.1
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.1.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: 1.3.5
pymysql: None
psycopg2: None
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

Breaking setup:
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.1.18-300.fc30.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.0
numpy            : 1.16.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.1.1
setuptools       : 41.0.1
Cython           : 0.29.11
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.6.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.5
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by TomAugspurger** [comment]
The old way didn't work. It was silently swallowing an error in your call. In pandas 0.24.2 this happened

```python
In [8]: my_list = [["654645", "54854"], ["1654151", "1564484a"]]
   ...: df = pd.DataFrame(my_list, columns=["ds", "y"])
   ...: df = df.apply(pd.to_numeric, args=({"errors": "raise"}))

In [9]: df
Out[9]:
        ds        y
0   654645  54854.0
1  1654151      NaN
```

notice that that should have raised with `errors='raise`'.

`args` is supposed to be a tuple of positional arguments. So you would want `args=('raise',)`. But I would recommend using `df.apply(pd.to_numeric, errors="raise")` instead.

**Comment by 4n4nd** [comment]
oh okay thanks for your help!
