### ISSUE TITLE
copy() method doesn't work as expected

### ISSUE THREAD

**Issue by marcmontb** [pandas-dev/pandas#27641]
#### Code Sample, a copy-pastable example if possible

```python

A = pd.DataFrame(data = {'variable':[{'k0':'v0'}, {'k1':'v1'}]})
B = A.copy()
B.loc[0,'variable']['k0'] = 'v2'

A
##         variable
##  0	 {'k0': 'v2'}
##  1	 {'k1': 'v1'}

B
##         variable
##  0	 {'k0': 'v2'}
##  1	 {'k1': 'v1'}

```
#### Problem description

 When modifying specific values of a dictionary type variable copy() method doesn't work as expected. It modifies both, the object's copy and the original object, instead of just modifying the copy.

#### Expected Output

```python

A
##         variable
##  0	 {'k0': 'v0'}
##  1	 {'k1': 'v1'}

B
##         variable
##  0	 {'k0': 'v2'}
##  1	 {'k1': 'v1'}


#### Output of ``pd.show_versions()``

<details>

pandas: 0.24.2

</details>

**Comment by TomAugspurger** [comment]
This is documented: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.copy.html#pandas.DataFrame.copy

I'd recommend calling `copy.deepcopy` on each element, possibly by `applymap` if you need to recursively copy python data structures.
