### ISSUE TITLE
Index vs. MultiIndex behavior on slices of DataFrames (and Series)

### ISSUE THREAD

**Issue by SandiMusic** [pandas-dev/pandas#27658]
#### Code Sample, a copy-pastable example if possible

```python
import random as rd

df_single = pd.DataFrame(data={"Col1": rd.sample(range(1, 100), 25)}, index=rd.sample(range(1, 100), 25))
single_slice = df_single[:9]
single_slice.index

df_multi = pd.DataFrame(data={"Col1": rd.sample(range(1, 100), 25)}, index=[["a" for _ in range(10)] + ["b" for _ in range(15)], rd.sample(range(1, 100), 25)])
multi_slice = df_multi[:9]
multi_slice.index

```
#### Problem description

When slicing the single index df, the index of the slice is returned in the order it appears in the single df. However, when slicing the multi index df, the index attribute of the slice will return the index of the complete (unsliced) df.

This seems inconsistent to me and is quite inconvenient in several different cases. Is this intentional? (if yes, what is the reasoning?)

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by TomAugspurger** [comment]
You may have been confused by the old MultiIndex repr (it's hard to say since you didn't fill out the entire issue template). If you use pandas 0.25 or newer you'll see that the index has been sliced, or call `list` on the sliced index.

```
In [5]: multi_slice.index
Out[5]:
MultiIndex([('a', 84),
            ('a', 14),
            ('a', 17),
            ('a', 76),
            ('a', 11),
            ('a', 78),
            ('a', 69),
            ('a', 61),
            ('a', 93)],
           )

In [6]: df_multi.index
Out[6]:
MultiIndex([('a', 84),
            ('a', 14),
            ('a', 17),
            ('a', 76),
            ('a', 11),
            ('a', 78),
            ('a', 69),
            ('a', 61),
            ('a', 93),
            ('a', 65),
            ('b', 32),
            ('b', 57),
            ('b', 95),
            ('b', 22),
            ('b', 16),
            ('b',  5),
            ('b', 19),
            ('b', 43),
            ('b', 88),
            ('b', 71),
            ('b', 36),
            ('b', 68),
            ('b', 58),
            ('b', 34),
            ('b', 73)],
           )
```

If I misunderstood, could you fill out the full issue template and we'll reopen?
