### ISSUE TITLE
Cheat sheet link is broken in docs

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#27666]
#### Code Sample, a copy-pastable example if possible

N/A

#### Problem description

The cheat sheet link at https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf is broken

#### Expected Output

The cheat sheet should show up.

#### Output of ``pd.show_versions()``

v0.25 docs.  Link to it is at https://pandas.pydata.org/pandas-docs/version/0.25/getting_started/tutorials.html

**Comment by WillAyd** [comment]
Might be misreading but that link appears to work for me - still an issue?

**Comment by Dr-Irv** [comment]
Now it works.  Myself and a colleague had an issue two days ago, so who knows what happened.
