### ISSUE TITLE
How and where in the source code is .loc defined?

### ISSUE THREAD

**Issue by michaels011235** [pandas-dev/pandas#27681]
Hi, been browsing through the source code of pandas for the last couple of days, looking for:

**How and where in the source code is `.loc` like in `df.loc['foo']` defined?** 

I found out that the type of a Dataframe `.loc` attribute is `pandas.core.indexing._LocIndexer` but how and where is that implemented?

**Comment by TomAugspurger** [comment]
`pandas/core/indexing.py`

**Comment by jschendel** [comment]
The supported indexers are defined here:
https://github.com/pandas-dev/pandas/blob/313665ab41ebef44e093730ac05927cd632395ae/pandas/core/indexing.py#L33-L42

And added to the `NDFrame` class here:
https://github.com/pandas-dev/pandas/blob/313665ab41ebef44e093730ac05927cd632395ae/pandas/core/generic.py#L11678-L11680

**Comment by michaels011235** [comment]
@jschendel Thanks a lot :) 
I did not see the lines below `#install the indexes`
