### ISSUE TITLE
DOC: Contributors section is empty in v0.25.0 Release Notes

### ISSUE THREAD

**Issue by albertvillanova** [pandas-dev/pandas#27687]
#### Problem description

There is no content in the Contributors section of the pandas v0.25.0 Release Notes: https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.25.0.html#contributors

**Comment by jgehrcke** [comment]
Huhu! Just noting that this is still empty: https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.25.0.html#contributors. I see that #27689 did some work on that front, but what's the goal and did we achieve it? CC @TomAugspurger

**Comment by TomAugspurger** [comment]
Thanks, not sure whats up. I may not have had the tag when I built the
docs? Will take a look later.

**Comment by TomAugspurger** [comment]
Sorry, I misread. The 0.25.0 contributors should be `0.24.x..0.25.0` @jgehrcke are you interested in adding that to your other PR?

**Comment by jgehrcke** [comment]
> The 0.25.0 contributors should be 0.24.x..0.25.0 @jgehrcke are you interested in adding that to your other PR? 

doing that now!
