### ISSUE TITLE
`to_sql` does not correctly load data into snowflake

### ISSUE THREAD

**Issue by lucasludewigsamaro** [pandas-dev/pandas#27684]
#### Code Sample, a copy-pastable example if possible

```python
""" Insert dataframe into table."""
    if not df1.empty:
        df1['source'].str.lower()
        df1 = df1.replace(r'^\s*$', 0, regex=True)
        df1.to_sql(config['table_name'], schema='ecs_marketing',
                   con=conn, chunksize=200, index=False, if_exists='replace',
                   dtype={'date': sqlalchemy.types.Date,
                          'cost': sqlalchemy.types.Numeric(8, 3)})

```
#### Problem description

I am importing data from Google Sheets. 
So I create a dataframe with the spreadsheet content.
Then, I perform some data transformations. Until here, everything normal.

The problem appears when I try to load the data into Snowflake using to_sql command.
I receive the error:

```
(snowflake.connector.errors.ProgrammingError) 090105 (22000): Cannot perform SELECT. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.
[SQL: 
SELECT /* sqlalchemy:get_columns */
       ic.table_name,
       ic.column_name,
       ic.data_type,
       ic.character_maximum_length,
       ic.numeric_precision,
       ic.numeric_scale,
       ic.is_nullable,
       ic.column_default,
       ic.is_identity,
       ic.comment
  FROM information_schema.columns ic
 WHERE ic.table_schema=%(table_schema)s
   AND ic.table_name=%(table_name)s
 ORDER BY ic.ordinal_position
]
[parameters: {'table_schema': 'dev_raw.ecs_marketing', 'table_name': 'DIRECT_AFFILIATES'}]
(Background on this error at: http://sqlalche.me/e/f405)
```

I immediately noted that on error "parameters" dictionary, table_schema is in lower case and table_name is upper case. **Would that be a bug?**

Then I started to dig in. And figured out that to_sql looks for table DDL when `if_exists`='replace'.
If `if_exists`='append', I don't face the problem. Unfortunately, I need to replace.

If I call the function with schema=<database_name>.ecs_marketing also doesn't work.

So, **should to_sql accept also a database parameter, in case of snowflake?**

#### Expected Output

Able to insert my data into Snowflake, without snowflake errors.

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-55-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : pt_BR.UTF-8

pandas           : 0.25.0
numpy            : 1.17.0
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.2.1
setuptools       : 41.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.6
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by jorisvandenbossche** [comment]
The relevant part might be "Cannot perform SELECT. This session does not have a current database. Call 'USE DATABASE', or use a qualified name."

How did you create the connection? (sqlalchemy engine)

**Comment by lucasludewigsamaro** [comment]
Hi, @jorisvandenbossche 

Context:
we don't want to pass the database parameters into connection configs (connection creation), because:

1. we have prod and dev databases
2. this treatment is done somewhere else in the code
3. the correct database should be passed via schema_name

Setting schema='prod_raw.ecs_marketing' also doesn't work.

So, basically I have 3 questions:

1. why is it performing an select in information_schema?
2. why table schema is in lower case and table_name in upper case in SELECT statement?
3. why it works with `if_exists = replace`, and not when `if_exists = append`?

**Comment by kjford** [comment]
> why is it performing an select in information_schema?

I'm guessing you're using `snowflake-sqlalchemy`.  It looks like this method is being called when doing the metadata reflection that runs when you check the existence of a table. 
 See https://github.com/snowflakedb/snowflake-sqlalchemy/blob/master/snowdialect.py#L320 that is called by https://github.com/snowflakedb/snowflake-sqlalchemy/blob/master/snowdialect.py#L401.  You may want to read into the caching of column metadata here: https://github.com/snowflakedb/snowflake-sqlalchemy#cache-column-metadata.

> why table schema is in lower case and table_name in upper case in SELECT statement?

Snowflake displays objects (like table names) in all caps, though object name assignment is case-insensitive unless you quote it (https://docs.snowflake.net/manuals/sql-reference/identifiers-syntax.html).  In this case, the table name was probably pulled from metadata reflection, whereas the schema was pushed down from the `to_sql` arguments.

> why it works with if_exists = replace, and not when if_exists = append?

You difference lies here: https://github.com/pandas-dev/pandas/blob/master/pandas/io/sql.py#L649
On a `replace`, it must run a `drop_table`.  This method ends up doing a metadata reflection mentioned above.

To get at the main issue here, it appears you are passing a connectable that does not have a database assigned.  It shouldn't be the job of pandas to take this assignment, but rather of your connectable.  According to the `snowflake-sqlalchemy` docs, you can change the connection parameters after login, though I couldn't get this to work.  A work around is to just create a new connection with the connection parameters from the pre-configured one, but set the database:
```
# assume you have a sqlalchemy `Engine` as `eng` with basic connection
from sqlalchemy import create_engine

database = 'prod_raw'
eng_set = create_engine(f'snowflake://{eng.url.username}:{eng.url.password}@{eng.url.host}/{database}'
```

**Comment by mroeschke** [comment]
From the explanation above, it seems that is not an issue with pandas. Going to close for now but happy to reopen if there is a pandas related issue
