### ISSUE TITLE
BUG: Indexes still include values that have been deleted

### ISSUE THREAD

**Issue by darindillon** [pandas-dev/pandas#2770]
Using pandas 0.10. If we create a Dataframe with a multi-index, then delete all the rows with value X, we'd expect the index to no longer show value X. But it does.
   Note the apparent inconsistency between "index" and "index.levels" -- one shows the values have been deleted but the other doesn't.

``` python
import pandas

x = pandas.DataFrame([['deleteMe',1, 9],['keepMe',2, 9],['keepMeToo',3, 9]], columns=['first','second', 'third'])
x = x.set_index(['first','second'], drop=False)

x = x[x['first'] != 'deleteMe'] #Chop off all the 'deleteMe' rows

print x.index #Good: Index no longer has any rows with 'deleteMe'. But....

print x.index.levels #Bad: index still shows the "deleteMe" values are there. But why? We deleted them.

x.groupby(level='first').sum() #Bad: it's creating a dummy row for the rows we deleted!
```

We don't want the deleted values to show up in that groupby. Can we eliminate them?

**Comment by robertmuil** [comment]
I'm afraid I don't understand why there is no easy way of instructing the dataframe to drop absent levels.

For a clear use-case: counting the number of unique levels present in a data series is a computationally intensive task: if it can be done once, when `drop` or similar is called, then one need only look at the `index.levels` to determine the unique levels, rather than use the clunky, and slow, `data.index.get_level_values(level='whatever').unique()`.

I know this has been discussed considerably, but I did not see any mention of this 'unique counting' use-case, which I see as rather important.

**Comment by jreback** [comment]
@robertmuil this is an efficiency argument. It *can* be done on selection, the problem is the user may be doing multiple things (e.g.. selections or whatnot), and it is inefficient to do it then (this *can* be an expensive operation). So it is completely up to the user to rebuild or not.

**Comment by robertmuil** [comment]
@jreback I see, that makes a lot of sense. Would it not be possible, though, to provide a flag to the `drop` function which causes this rebuild to occur? Even if `drop` is used under the hood by the slicing / selection operators, as long as the default is not to rebuild, this shouldn't have any impact at all, just allow the user to specify it when they are dropping the items, and thus get a more intuitively consistent DataFrame from the drop operation.

It is also unclear to me what the recommended way to rebuild the levels of the index is: is it by `reset_index().set_index(...)`?

Thanks very much for your quick response, by the way.

**Comment by jreback** [comment]
can you put up a simple example of what you are doing?

**Comment by robertmuil** [comment]
Sure:

    > x = pandas.DataFrame([['deleteMe',1, 9],['keepMe',2, 9],['keepMeToo',3, 9]], columns=['first','second', 'third'])
    > x.set_index(['first', 'second'], inplace=True)

Before dropping levels, the following are consistent:

    > len(x.index.levels[0])
    3
    > len(x.index.get_level_values(level='first').unique())
    3

But afterward, not:

    > x.drop('deleteMe', level='first', inplace=True)
    > len(x.index.levels[0])
    3
    > len(x.index.get_level_values(level='first').unique())
    2

And this can be important, because the `get_level_values().unique()` is **hundreds** of times slower. So, I thought that a possibility would be to allow the drop() function to explicitly be told to reindex:

    > x.drop('deleteMe', level='first', inplace=True, reindex=True)
    > len(x.index.levels[0])
    2

**Comment by jreback** [comment]
@robertmuil 

sorry, forgot to respond to you.

Here is an easy way to do this

create the new frame
(FYI in general doing things ``inplace`` IMHO is confusing to the user and doesn't help with speed at all)
```
In [43]: dropped = x.drop('deleteMe', level='first')

In [44]: dropped
Out[44]: 
                  third
first     second       
keepMe    2           9
keepMeToo 3           9

In [46]: dropped.index.get_level_values(level='first').unique()
Out[46]: array(['keepMe', 'keepMeToo'], dtype=object)
```

This returns a new frame (You can assign alternatively if you want)
```
In [47]: dropped.set_index(pd.MultiIndex.from_tuples(dropped.index.values))
Out[47]: 
             third
keepMe    2      9
keepMeToo 3      9
In [50]: dropped.set_index(pd.MultiIndex.from_tuples(dropped.index.values)).index.get_level_values(level=0).unique()
Out[50]: array(['keepMe', 'keepMeToo'], dtype=object)

# has only the new values
In [51]: dropped.set_index(pd.MultiIndex.from_tuples(dropped.index.values)).index.levels[0]                         
Out[51]: Index([u'keepMe', u'keepMeToo'], dtype='object')
```

This is pretty cheap to do (though not completely free).

I suppose you could add this as an option to ``drop`` if you'd like. (and I would say ``reindex`` would be a fine kw for this).

like to do a pull-request?

**Comment by pjadzinsky** [comment]
Hi,
I know this is a somewhat old thread but I wanted to pitch in since I see some inconsistencies and wanted to learn whether this is my misunderstanding of something fundamental or this should be treated as a bug

Here is a simple example.

```
In [22]: df = pd.DataFrame(np.random.randint(0,4,(3,2)))

In [23]: df2 = pd.concat([df,df,df], keys=['a','b','c'], names=[1,2])

In [24]: df2
Out[24]: 
     0  1
1 2      
a 0  2  0
  1  0  2
  2  2  0
b 0  2  0
  1  0  2
  2  2  0
c 0  2  0
  1  0  2
  2  2  0
```


And now if I do:
```
In [27]: df2.loc[['a']].index
Out[27]: 
MultiIndex(levels=[[u'a'], [0, 1, 2]],
           labels=[[0, 0, 0], [0, 1, 2]],
           names=[1, 2])

In [28]: df2.loc[['a','b']].index
Out[28]: 
MultiIndex(levels=[[u'a', u'b', u'c'], [0, 1, 2]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]],
           names=[1, 2])
```
I was expecting the Multiindex to be either identical in both cases (based on the discussion on this thread) or that the last one (Out[28]) should be like this:
```
[MultiIndex(levels=[[u'a', u'b'], [0, 1, 2]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]],
           names=[1, 2])
```

Thanks in advance for clarifying my question and for an awesome package.

**Comment by jreback** [comment]
@pjadzinsky this is an implementation detail ATM. 

```
# this is what you are expecting
In [81]: df2.loc[[('a',0)]].index
Out[81]: 
MultiIndex(levels=[['a', 'b', 'c'], [0, 1, 2]],
           labels=[[0], [0]],
           names=[1, 2])

# this is able to get an entire level so it takes a different path
In [82]: df2.loc[['a']].index
Out[82]: 
MultiIndex(levels=[['a'], [0, 1, 2]],
           labels=[[0, 0, 0], [0, 1, 2]],
           names=[1, 2])

```

**Comment by wesm** [comment]
That is slightly odd that in one case the levels are modified in one case but not the other

**Comment by toobaz** [comment]
I think this can be closed: the default behavior is as intended, and the method ``MultiIndex.remove_unused_levels()`` has been added as a simple fix for whoever doesn't like the default behavior.

**Comment by jreback** [comment]
yep this is now the accepted soln.

**Comment by vldbnc** [comment]
How this ```MultiIndex.remove_unused_levels()``` could be accepted solution?
You might filter dataframe based on level and create new df or series

`df_new = df[df.index.isin(['VALUE'], level=0)]`

Newly created `df_new` will correctly show Mutliindex with `df_index.index` having only 'VALUE' on level=0 but `df_new.index.levels[0]` are showing all levels from original `df`.
