### ISSUE TITLE
Set to_csv(index=False) by default

### ISSUE THREAD

**Issue by adecourcy** [pandas-dev/pandas#27718]
By default, the optional "index" parameter of the "to_csv" method is set to True. However, I would argue this violates the principal of least surprise. That is to say, when calling this method I, as a user, would expect that my data frame is converted into a CSV format as is, with no data added or removed that I did not explicitly add or remove myself.

Adding an index column without the user specification is kind of weird, unexpected behavior. Not unlike adding a column for type of reference hashing, or dropping a random column from the data frame without the user specifying this in advance. Thus, I would argue that the "index" parameter should be set to False by default.

**Comment by TomAugspurger** [comment]
The index is part of the pandas data model. It's included in all our IO methods by default (including string / the repr).

**Comment by adecourcy** [comment]
While I appreciate that, I don't really think it negates my point. While I use Pandas, I'm not a heavy user and I think I can confidently state that this is quite surprising, unexpected, and undesirable behavior. I shouldn't have to understand the underlying data model of a program to predict the behavior of an end user function. It should just do what I, as an end user, expect it to do. Without understanding your underlying data model, there is no reason for me as the end user to expect Pandas to add or remove anything at all from my data frame when converting it to a CSV format.

Or, to put it another way, why would you think a user who is unfamiliar with Pandas would expect an index to be added to a CSV when calling this method, if the user hasn't directly specified that this index should be added?

**Comment by tbagnoli** [comment]
> The index is part of the pandas data model
@TomAugspurger why, though? In 3 years as a data scientist I haven't yet encountered an example in which I wanted to use (and therefore attach meaning to) something that can be altered as easily as with a `reset_index()` operation. I'm always using the non-default option and I'd say it's legitimate to ask ourselves whether the community actually desires this behaviour?

**Comment by TomAugspurger** [comment]
I think the dsintro page may explain why.

**Comment by TomAugspurger** [comment]
We have another issue discussing index subclasses that don’t trigger alignment, etc. for these indexes, it may make sense to not write them out, but I’m not sure if that’s been discussed.

**Comment by TomAugspurger** [comment]
I think we'll pass on this, thanks.
