### ISSUE TITLE
use DataFrame.style and can't get [cellstyle] as expected

### ISSUE THREAD

**Issue by whatagain** [pandas-dev/pandas#27729]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
df = DataFrame(np.arange(60).reshape(15,4),columns=['a','b','c','d'])
df1 = df>50

def b_color(val):
    color = 'red' if val ==True else ''
    return 'color: %s' % color
    
h_df = df1.style.applymap(b_color)
h_df._translate()['cellstyle']
```
#### Problem description

i'm using DataFrame.style and i want to extract the 'cellstyle'
but the props are all showed empty

the output is like this:
'cellstyle': [{'props': [], 'selector': 'row0_col0'},
  {'props': [], 'selector': 'row0_col1'},
  {'props': [], 'selector': 'row0_col2'},
  {'props': [], 'selector': 'row0_col3'},

however, the output of h_df is normal and the color is applyed at the right position 

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: AMD64 Family 21 Model 16 Stepping 1, AuthenticAMD
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.4
pytest: 3.2.1
pip: 9.0.1
setuptools: 36.5.0.post20170921
Cython: 0.26.1
numpy: 1.15.1
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.1.0
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

**Comment by TomAugspurger** [comment]
I think you need to call render first.

**Comment by attack68** [comment]
This is a user code error, **not a bug**, solved with:
```print(h_df._compute()._translate()['cellstyle'])```
Output:
```
[{'props': [('color', ' ')], 'selectors': ['row0_col0', 'row0_col1', 'row0_col2', 'row0_col3', ...]},
 {'props': [('color', 'red')], 'selectors': ['row1_col0', 'row1_col1', 'row0_col2', 'row1_col3', ...]}]
```

Issue should be closed imo.
