### ISSUE TITLE
Object dtype for int64 and Int64 values in column

### ISSUE THREAD

**Issue by Zoynels** [pandas-dev/pandas#27731]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np
df1 = pd.DataFrame({"id": ["1", "2", "3", "4", "5"]}, columns=["id"]).astype('float64').astype('int64')
df2 = pd.DataFrame({"id": ["1", "2", "3", "4", "5"]}, columns=["id"]).astype('float64').astype('Int64')

df3 = pd.concat([df1, df2], axis="index", sort=False)

for col in df3.columns:
    for i in df3[col]:
        print(f"[{i}] has type: {type(i)}")
print("df1: " + str(df1['id'].dtype))
print("df2: " + str(df2['id'].dtype))
print("df3: " + str(df3['id'].dtype))
```
#### Problem description

What is the difference between "Int64" and "int64"?
After concat it has "object" dtype.

#### Real Output
```python
[1] has type: <class 'int'>
[2] has type: <class 'int'>
[3] has type: <class 'int'>
[4] has type: <class 'int'>
[5] has type: <class 'int'>
[1] has type: <class 'int'>
[2] has type: <class 'int'>
[3] has type: <class 'int'>
[4] has type: <class 'int'>
[5] has type: <class 'int'>
df1: int64
df2: Int64
df3: object
```

#### Expected Output
```python
[1] has type: <class 'int'>
[2] has type: <class 'int'>
[3] has type: <class 'int'>
[4] has type: <class 'int'>
[5] has type: <class 'int'>
[1] has type: <class 'int'>
[2] has type: <class 'int'>
[3] has type: <class 'int'>
[4] has type: <class 'int'>
[5] has type: <class 'int'>
df1: int64
df2: int64
df3: int64
```
or 
```python
[1] has type: <class 'numpy.int64'>
[2] has type: <class 'numpy.int64'>
[3] has type: <class 'numpy.int64'>
[4] has type: <class 'numpy.int64'>
[5] has type: <class 'numpy.int64'>
[1] has type: <class 'numpy.int64'>
[2] has type: <class 'numpy.int64'>
[3] has type: <class 'numpy.int64'>
[4] has type: <class 'numpy.int64'>
[5] has type: <class 'numpy.int64'>
df1: Int64
df2: Int64
df3: Int64
```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.0
numpy            : 1.16.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.0.3
setuptools       : 41.0.0
Cython           : None
pytest           : 5.0.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.3.4
html5lib         : None
pymysql          : 0.9.3
psycopg2         : 2.8.3 (dt dec pq3 ext lo64)
jinja2           : 2.10.1
IPython          : 7.6.1
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : 0.3.1
gcsfs            : 0.3.0
lxml.etree       : 4.3.4
matplotlib       : 3.1.1
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : 0.14.0
pytables         : None
s3fs             : None
scipy            : 1.3.0
sqlalchemy       : 1.3.5
tables           : None
xarray           : 0.12.3
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.8
</details>

If there are no difference between them, thed dtype recognize uncorrecter, but if it is different, then may be need to change "name", case sensitive type I think is very bugy.

**Comment by TomAugspurger** [comment]
One is a nullable integer dtype. The other is a numpy dtype.  Check the arrays page of the API docs.

Right now concat of multiple dtypes coerces to object. That may change in the future.
