### ISSUE TITLE
to_csv has changed the number

### ISSUE THREAD

**Issue by shanhong** [pandas-dev/pandas#27771]
#### Code Sample, a copy-pastable example if possible

```python
df1 = pd.read_csv("./data/test.csv")
print(df1)
df1.to_csv("./data/test1.csv")

test.csv has only one column "a" and one number is "656.964"，when I prepare to use "to_csv" then it has changed to 656.9639999. 
I hope you can help solve this problem.

**Comment by tseth92** [comment]
this is floating point precision problem . See this issue already raised and closed.:
https://github.com/pandas-dev/pandas/issues/2069
So, most you can do is pass an argument in to_csv with **float_format='%.3f'** which will restrict your output to 3 decimal places

**Comment by alimcmaster1** [comment]
@tseth92 answer should solve your problem. Feel free to reopen @shanhong
