### ISSUE TITLE
ENH: allow new column names argument in DataFrame arithmetic ops

### ISSUE THREAD

**Issue by charlesdong1991** [pandas-dev/pandas#27778]
Right now, for arithmetic operations like `add`, `div`, `pow` etc, the default is to rewrite input columns with new values (which are processed by those arithmetic operations), e.g.
```python
df = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
df.div(10)
```
And this will return something like
```
|  a | b  |
|----|----|
| 0.1 | 0.4 | 
| 0.2 | 0.5 | 
| 0.3 | 0.6 |  
```
And we could also assign it to new cols by:
```python
df[['c', 'd']] = df.div(10)
```
But it's gonna be good to have something like
```python
df = df.div(10, new_cols=['c', 'd'])
```
So that the chaining can be used afterwards and in practice I feel very useful to have this enhancement.
If it's okay, I would be very glad to implement this feature.

**Comment by jorisvandenbossche** [comment]
I understand the reasoning to some extent to want something like this, but, we don't have such a keyword argument anywhere in pandas right now (I think). So might need to think a bit more on how this can fit into the pandas API in general.

**Comment by TomAugspurger** [comment]
I think my preference is to keep those as two distinct operations.

**Comment by charlesdong1991** [comment]
ok, thanks for your answers, make sense to me and I will close the issue then @TomAugspurger @jorisvandenbossche thanks!
