### ISSUE TITLE
groupby().ffill() column disappeared in pandas==0.25.0

### ISSUE THREAD

**Issue by fujiaxiang** [pandas-dev/pandas#27797]
#### Code Sample

```python
import pandas as pd
df = pd.DataFrame([[1, 1], [2, 2], [1, None], [2, None]], columns=['a', 'b'])
df.groupby('a').ffill()
```
#### Problem description
Dataframe df itself:
```
   a    b
0  1  1.0
1  2  2.0
2  1  NaN
3  2  NaN
```

Output of ```df.groupby('a').ffill()``` in 0.25.0:
```
     b
0  1.0
1  2.0
2  1.0
3  2.0
```

Output of ```df.groupby('a').ffill()``` in 0.24.2:
```
   a    b
0  1  1.0
1  2  2.0
2  1  1.0
3  2  2.0
```
The output of the above code in pandas==0.25.0 drops columns "a", which is kind of weird and also different from 0.24.2. I believe people would expected column "a" to be still there as a column or as an index. The behavior in 0.24.2 is intuitive, natural and easy to use.

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

#### Expected Output
```
   a    b
0  1  1.0
1  2  2.0
2  1  1.0
3  2  2.0
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.0
numpy            : 1.16.2
pytz             : 2018.9
dateutil         : 2.8.0
pip              : 19.0.3
setuptools       : 41.0.1
Cython           : 0.29.6
pytest           : 4.3.1
hypothesis       : None
sphinx           : 1.8.5
blosc            : None
feather          : None
xlsxwriter       : 1.1.5
lxml.etree       : 4.3.2
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.7.6.1 (dt dec pq3 ext lo64)
jinja2           : 2.10
IPython          : 7.4.0
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.2
matplotlib       : 3.0.3
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.6.1
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.2.1
sqlalchemy       : 1.2.19
tables           : 3.5.1
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.5
</details>

**Comment by jreback** [comment]
https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.25.0.html#dataframe-groupby-ffill-bfill-no-longer-return-group-labels

**Comment by fujiaxiang** [comment]
Should have carefully read through the docs. Sorry about that.
