### ISSUE TITLE
DOC: clarify that read_parquet accepts a directory path

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#27820]
The current documentation (both docstring https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_parquet.html and user guide https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#partitioning-parquet-files) don't make it very clear that the file path can also be a directory name that contains multiple (partitioned) parquet files (in addition to single file path).

**Comment by lucaionescu** [comment]
Hi, I'd like to fix on this one.

**Comment by HawkinsBA** [comment]
Hi, could I pick this issue up if it isn't still being worked on?
