### ISSUE TITLE
Series.str.extract not return pandas.Index object

### ISSUE THREAD

**Issue by xinbinhuang** [pandas-dev/pandas#27848]
#### Code Sample, a copy-pastable example if possible

```python
# extract certain part of the column names
df = pd.DataFrame({'a1': 1, 'b2':2, 'c3': 3}, index=[0])

df.columns = df.columns.str.extract(r'([0-9])')

df
# Out[]: 
#    (1,)  (2,)  (3,)
# 0     1     2     3


# Series object is returned instead of index
cols = pd.Index(list('abc'))

cols.str.extract(r'(.*)')

# Out[]:
#    0
# 0  a
# 1  b
# 2  c

pd.__version__
# Out[]: '0.25.0'
```
#### Problem description

I am dealing with files extracted from our Hive warehouse, and most of the time the column names follow this format `<table_name>.<col-name>`. To have a better workflow on downstream analysis, I would like to only keep the `<col_name>` part. So I use something like below this to replace the column names.
```python
df.colums = df.columns.str.extract(r'\.(.*)')
```
However, as the example shown above, the column names would be messed up again because `Series` is returned instead of `Index`. 

#### Expected Output
When the Input data type for `str.extract` is `Index`, `Index` shoul be returned.
#### Output of ``pd.show_versions()``

<details>

pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.0.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.6.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_CA.UTF-8
LOCALE           : en_CA.UTF-8

pandas           : 0.25.0
numpy            : 1.17.0
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.1
setuptools       : 40.4.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 1.0.1
pymysql          : 0.9.2
psycopg2         : 2.7.6.1 (dt dec pq3 ext lo64)
jinja2           : 2.10
IPython          : 6.5.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.0.0
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.1.0
sqlalchemy       : 1.2.12
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by Liam3851** [comment]
I think you want `df.columns.str.extract(r'\.(.*)', expand=False)`. By default pandas expands to handle potential multiple matches in the same regex.

```python3
In [14]: cols = pd.Index(['a.b', 'c.d', 'e.f'])

In [15]: cols.str.extract(r'\.(.*)', expand=False)
Out[15]: Index(['b', 'd', 'f'], dtype='object')
```

**Comment by TomAugspurger** [comment]
@Liam3851 is correct.

We want the default of `expand=True` to be consistent between Index.str.extract and Series.str.extract, which requires returning a DataFrame.
