### ISSUE TITLE
read_excel throws XLRD error when used in a for loop but not when used outside of one.

### ISSUE THREAD

**Issue by brandonsimpson21** [pandas-dev/pandas#27850]
I have a folder full of excel files if I go

for i in range(0,len(os.listdir())):
    x=pd.read_excel(os.listdir()[i])

I get an xlrd error that reads "Unsupported format, or corrupt file: Expected BOF record; found b'\x00\x00\x00\x01Bud1'"

but if I go

x=pd.read_excel(os.listdir()[0])

I don't get an error

**Comment by alimcmaster1** [comment]
Hi - could you please give an example which we could use to reproduce the issues? Perhaps a link to the example csv?

**Comment by TomAugspurger** [comment]
@brandonsimpson21 can you provide an example? It sounds like you have a bad excel file if xlrd can't open it.

If you can provide an example we'll reopen.
