### ISSUE TITLE
DOC: Documentation says Series.items(), Series.iteritems() are equivalent to DataFrame.items(), but they're not.

### ISSUE THREAD

**Issue by bthayer2365** [pandas-dev/pandas#27859]
Documentation says `Series.items()`, `Series.iteritems()` are equivalent to `DataFrame.items()` for DataFrames, but they're not. Instead, they are equivalent to `DataFrame.iterrows()`

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.items.html

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.iteritems.html

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.items.html

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iterrows.html

**Comment by jorisvandenbossche** [comment]
I think this is more a semantic discussion about what "equivalent" means here, but feel free to propose a better description of the relation between `Series.items()` and `DataFrame.items()`

**Comment by TomAugspurger** [comment]
Right. They're equivalent in the sense that you get an iterator over "key, value" pairs.

I think this is fine, but would certainly accept a PR clarifying things. I don't think we necessarily need an open issue for this.
