### ISSUE TITLE
DOC: Use of "Yields" vs "Returns" for documentation of DataFrame.items() and DataFrame.iteritems() 

### ISSUE THREAD

**Issue by bthayer2365** [pandas-dev/pandas#27860]
`DataFrame.items()` says it "Yields" the label and content of the columns whereas `DataFrame.iteritems()` says it "Returns" the label and content of the columns

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.items.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iteritems.html

**Comment by TomAugspurger** [comment]
Yields is the correct one.

**Comment by jorisvandenbossche** [comment]
There is some discussion about this here: https://github.com/pandas-dev/pandas/pull/26114#discussion_r302264466

cc @topper-123

**Comment by topper-123** [comment]
Yeah, ``yield`` is correct, though very technically, I think ``items`` is a generator (it yields) while ``iteritems`` *returns* a generator (it returns something that yields).

But that is a useless distinction, so I agree both could be marked as yielding.

**Comment by bthayer2365** [comment]
@topper-123 Not quite. When a function "yields", it is actually returning a generator object. The net effect is that both are functions and both return generators.
```
>>>def gen():
>>>    for i in range(100):
>>>        yield i
>>>print(type(gen))

<class 'function'>

>>>print(type(gen()))

<class 'generator'>

>>>def return_gen():
>>>    return gen()
>>>print(type(return_gen))

<class 'function'>

>>>print(type(return_gen()))

<class 'generator'>
```

**Comment by jorisvandenbossche** [comment]
In any case, both return exactly the same:

```
In [8]: df = pd.DataFrame({'a': [1, 2, 3]})                                                                                                                                                   

In [9]: df.iteritems()                                                                                                                                                                        
Out[9]: <generator object DataFrame.items at 0x7f4a143e7840>

In [10]: df.items()                                                                                                                                                                           
Out[10]: <generator object DataFrame.items at 0x7f4a143e7660>
```

so I am not fully sure why the doc validation thinks there is a difference between both.
