### ISSUE TITLE
DOC: Standardize use of "Iterate" and "Iterator" in the documentation for DataFrame and Series iterators

### ISSUE THREAD

**Issue by bthayer2365** [pandas-dev/pandas#27861]
Documentation for `DataFrame.items()` and `DataFrame.iteritems()` say 
"Iterator over..."
while other iterators for `DataFrame` and `Series` say
"Iterate over..."

All of these methods return an iterator, so I think it would make sense to have them all say "Iterator over...", although the documentation for 4/6 of the iteration methods already use "Iterate over...".

I'm not sure if there are other methods that also create iterators that we can use to justify one over the other.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.items.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iteritems.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iterrows.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.itertuples.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.items.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.iteritems.html

**Comment by jorisvandenbossche** [comment]
According to our docstring guidelines, the sentence should start with an infinite verb: https://dev.pandas.io/development/contributing_docstring.html#section-1-short-summary

So according to that it should be "Iterate over .." or "Return iterator over .." ?
