### ISSUE TITLE
DOC: See also for DataFrame.iterrows() should say Dataframe.x() instead of just .x()

### ISSUE THREAD

**Issue by bthayer2365** [pandas-dev/pandas#27862]
See also for DataFrame.iterrows() currently has a "See also" section that lists
```
itertuples
items
```
while DataFrame.itertuples() shows
```
DataFrame.iterrows
DataFrame.items
```
We should change DataFrame.iterrows() to be like DataFrame.itertuples()

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iterrows.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.itertuples.html

**Comment by jorisvandenbossche** [comment]
Do you want to do a PR do change this?

**Comment by Ankit-Dhankhar** [comment]
If this issue is not assigned I would like to make PR for this :)

**Comment by bthayer2365** [comment]
I'm not working on it. Go for it!
