### ISSUE TITLE
DOC: read_fwf not appears on IO Formats table as function

### ISSUE THREAD

**Issue by isantolin** [pandas-dev/pandas#27884]
#### Problem description
I Think that needs to appear on that table because is not clearly documented

![image](https://user-images.githubusercontent.com/264640/62899533-67417880-bd2e-11e9-99e3-f33b659aed03.png)

**Comment by TomAugspurger** [comment]
Thanks, the source is at `doc/source/user_guide/io.rst` if you're interested in submitting a PR.
