### ISSUE TITLE
Issue with str.contains output

### ISSUE THREAD

**Issue by ashishstats** [pandas-dev/pandas#27898]
#### Code Sample, a copy-pastable example if possible
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

csv1="multiple_responses.csv"
df1 = pd.read_csv(csv1, index_col='id' , na_values = [' '] , low_memory=False)

## creating a list containing 8 family planning method names
method_names = ['female_condoms', 'emergency', 'male_condoms', 'pill', 'injectables', 'iud', 'male_sterilization', 'female_sterilization']
for method in method_names:
    print(method)

for method in method_names:
    df1[method]=df1["methods_discussed"].str.contains(pat = method) 
df1.head(10)

## output
id | methods_discussed | female_condoms | emergency | male_condoms | pill | injectables | iud | male_sterilization | female_sterilization
1 | emergency | FALSE | TRUE | FALSE | FALSE | FALSE | FALSE | FALSE | FALSE
2 | female_sterilization | FALSE | FALSE | FALSE | FALSE | FALSE | FALSE | _**TRUE**_ | TRUE
3 | male_sterilization | FALSE | FALSE | FALSE | FALSE | FALSE | FALSE | TRUE | FALSE
4 | iud | FALSE | FALSE | FALSE | FALSE | FALSE | TRUE | FALSE | FALSE
5 | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN
6 | injectables male_condoms | FALSE | FALSE | TRUE | FALSE | TRUE | FALSE | FALSE | FALSE
7 | male_condoms | FALSE | FALSE | TRUE | FALSE | FALSE | FALSE | FALSE | FALSE
8 | female_sterilization male_sterilization | FALSE | FALSE | FALSE | FALSE | FALSE | FALSE | TRUE | TRUE
9 | injectables | FALSE | FALSE | FALSE | FALSE | TRUE | FALSE | FALSE | FALSE
10 | iud male_condoms | FALSE | FALSE | TRUE | FALSE | FALSE | TRUE | FALSE | FALSE

#### Problem description
I used CSV file
[multiple_responses.zip](https://github.com/pandas-dev/pandas/files/3496001/multiple_responses.zip)
 which contains two columns "id" and "methods_discussed". After running above code the ouput shown is wrong as at index [2] column male_sterilization shows TRUE (I have made it bold and italic. It should be FALSE as "methods_discussed" contains only female_sterilization.

#### Expected Output

id | methods_discussed | female_condoms | emergency | male_condoms | pill | injectables | iud | male_sterilization | female_sterilization
1 | emergency | FALSE | TRUE | FALSE | FALSE | FALSE | FALSE | FALSE | FALSE
2 | female_sterilization | FALSE | FALSE | FALSE | FALSE | FALSE | FALSE | **_FALSE_** | TRUE
3 | male_sterilization | FALSE | FALSE | FALSE | FALSE | FALSE | FALSE | TRUE | FALSE
4 | iud | FALSE | FALSE | FALSE | FALSE | FALSE | TRUE | FALSE | FALSE
5 | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN | NaN
6 | injectables male_condoms | FALSE | FALSE | TRUE | FALSE | TRUE | FALSE | FALSE | FALSE
7 | male_condoms | FALSE | FALSE | TRUE | FALSE | FALSE | FALSE | FALSE | FALSE
8 | female_sterilization male_sterilization | FALSE | FALSE | FALSE | FALSE | FALSE | FALSE | TRUE | TRUE
9 | injectables | FALSE | FALSE | FALSE | FALSE | TRUE | FALSE | FALSE | FALSE
10 | iud male_condoms | FALSE | FALSE | TRUE | FALSE | FALSE | TRUE | FALSE | FALSE

I have also used str.match but it did not work for me.
Any idea if I don't want to generate values if methods_discussed contains NaN.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.2
pytest: 5.0.1
pip: 19.1.1
setuptools: 41.0.1
Cython: 0.29.12
numpy: 1.16.4
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.6.1
sphinx: 2.1.2
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: 1.2.1
tables: 3.5.2
numexpr: 2.6.9
feather: None
matplotlib: 3.1.0
openpyxl: 2.6.2
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.8
lxml.etree: 4.3.4
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.3.5
pymysql: None
psycopg2: None
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

**Comment by TomAugspurger** [comment]
Can you make the example simpler? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

Do you think there's a bug in pandas? Otherwise, we prefer issue reports go on StackOverflow with the #pandas tag.

**Comment by ashishstats** [comment]
@TomAugspurger reason for uploading the link of CSV was to make raw data available so that actual output can verified with expected output.
It is not a bug in pandas as got the solution on StackOverflow.
the right code is 

for method in method_names:
    df1[method]=df1["methods_discussed"].str.contains(pat = r"\b{}\b".format(method), na="")
