### ISSUE TITLE
DataFrame.groupby.fillna(method='bfill) not equal as DataFrame.groupby.bfill()

### ISSUE THREAD

**Issue by RainFung** [pandas-dev/pandas#27897]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame({
    'A': [1, 1, 2, 2],
    'B': [2, 4, None, 3],
    'C': [None, None, None, 1],
    'D': [0, 1, 5, 4]
    },
    columns=['A', 'B', 'C', 'D'])

df.groupby(['A']).fillna(method='bfill')
     B    C  D
0  2.0  NaN  0
1  4.0  NaN  1
2  3.0  1.0  5
3  3.0  1.0  4

df.groupby(['A']).bfill()
   A    B    C  D
0  1  2.0  NaN  0
1  1  4.0  NaN  1
2  2  3.0  1.0  5
3  2  3.0  1.0  4
```
#### Problem description
`DataFrame.groupby.bfill()` contains groupby col ['A'] while DataFrame.groupby.fillna(method='bfill) dont have it . Same problem in `ffill`.

#### Output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-693.5.2.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: zh_CN.utf8
LANG: None
LOCALE: zh_CN.UTF-8

pandas: 0.24.2
pytest: 5.0.1
pip: 18.1
setuptools: 41.0.1
Cython: 0.29.10
numpy: 1.17.0
scipy: 1.1.0
pyarrow: 0.14.1
xarray: None
IPython: 7.2.0
sphinx: 2.1.2
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: 1.2.1
tables: 3.5.1
numexpr: 2.6.9
feather: 0.4.0
matplotlib: 3.1.1
openpyxl: 2.6.1
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.8
lxml.etree: 4.2.5
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.3.5
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

**Comment by charlesdong1991** [comment]
try upgrading to 0.25? cannot replicate this issue somehow:
![Screen Shot 2019-08-13 at 10 58 05 AM](https://user-images.githubusercontent.com/9269816/62928670-42461780-bdb9-11e9-9aec-5e4ae3b7009e.png)

**Comment by TomAugspurger** [comment]
Yeah, this changed in 0.25 to be more consistent.
