### ISSUE TITLE
Tab completion triggers deprecation warnings with latest Jedi (0.15.1)

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#27900]
I reported it at Jedi: https://github.com/davidhalter/jedi/issues/1383 
But opening an issue here as well in case there are workarounds we need to do in pandas itself (last time we did do something: https://github.com/pandas-dev/pandas/pull/16414)

**Comment by TomAugspurger** [comment]
Sounds like we'll want to put in a workaround to silence these, since we may be releasing before Jedi.

**Comment by TomAugspurger** [comment]
I briefly looked into this. Didn't see an easy way to avoid the warnings.

**Comment by jorisvandenbossche** [comment]
@TomAugspurger last time you did something like 

```
    def __dir__(self):
        # Avoid IPython warnings for deprecated properties
        # https://github.com/pandas-dev/pandas/issues/16409
        rv = set(dir(type(self)))
        rv.discard("labels")
        return sorted(rv)
```

That did not work this time? 
It seem Thomas Kluyver is doing something similar here https://github.com/h5py/h5py/pull/1316

**Comment by jorisvandenbossche** [comment]
This actually seems to be working, will do a PR (we already have the infrastructure set up, but the base list of deprecations was not passed properly to Series)

**Comment by jorisvandenbossche** [comment]
OK, done in https://github.com/pandas-dev/pandas/pull/28524
