### ISSUE TITLE
Move `.github` files to the organization level

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#27901]
Described in https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization, we can make a `.github` repo under pandas-dev. Then all the "community" files (code of conduct, funding, security, etc) will apply to every repo in the organization. This makes it clear that these policies apply everywhere, but we don't have to worry about copying / updating the files to every repo.

**Comment by jreback** [comment]
lgtm.

**Comment by jbrockmendel** [comment]
Is this literally just creating a repo and moving the files, or is there something more to it?
