### ISSUE TITLE
Functions allowed in DataFrameGroupby.transform are not all tested

### ISSUE THREAD

**Issue by charlesdong1991** [pandas-dev/pandas#27905]
e.g. `fillna`, `tshift`and `corrwith` are all allowed in `group.transform()`, but looking at `pandas/tests/groupby/test_transform.py`, they are not tested. There are more, and I will add to here and make a PR to tests these cases.

**Comment by TomAugspurger** [comment]
Looks like https://github.com/pandas-dev/pandas/pull/27974 was closed as stale. Marking as a good first issue, if anyone wants to pick it up based on that PR.

**Comment by lfiedler** [comment]
Hi, I would like to work on this.

**Comment by echozzy629** [comment]
Hi, I would like to work on this.

**Comment by simonjayhawkins** [comment]
@echozzy629 Thanks for the interest. #32069 has been submitted to address this issue.

**Comment by simonjayhawkins** [comment]
superseded by #32293 , #31269 , #27472 and #32344
