### ISSUE TITLE
why when i read data from '.xlsx',values of one colum which type is 'str' with hyHyperlink be read as 0 

### ISSUE THREAD

**Issue by qfs1998** [pandas-dev/pandas#27924]
#### Code Sample, a copy-pastable example if possible

```python
`import pandas as pd

df=pd.read_excel('C:\\Users\\c50007919\\Downloads\\问题单_RouterV800R012C00_20190815 2019-08-15 11_19_50.xlsx')
df`
```
#### Problem description
my pandas version is  0.25.0
I do not know why that happened,  I have a excel with one column whose type is str with hyperlink,when I use the read_excel function to read it ,that column data become 0,and its type is int64,  that is strange. And if I open the excel to delete the hyperlink of just one cell of that columns ,this problem is solved.
Actually I do not know is it really the hyperlink make this problem。
How can I just read it as str without open my excel to cancel the hyperlink?
And I really don't know why it is become 0 and int64.
Thanks

**Comment by mroeschke** [comment]
Try specifying `dtype=object` to not infer types. We would need a reproducible example to debug further. Feel free to reopen if you have a reproducible example and the issue still persists.
