### ISSUE TITLE
Series.div raises TypeError: unsupported operand type(s)

### ISSUE THREAD

**Issue by connesy** [pandas-dev/pandas#27930]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
kmPerMinute = df['mileageInKm'].div(df['driveDurationInMinutes'])

Traceback (most recent call last):
 File "/app/src/report_trip.py", line 215, in check_car
   kmPerMinute = df['mileageInKm'].div(df['driveDurationInMinutes'])
 File "/home/python/.local/lib/python3.6/site-packages/pandas/core/ops.py", line 1870, in flex_wrapper
   return self._binop(other, op, level=level, fill_value=fill_value)
 File "/home/python/.local/lib/python3.6/site-packages/pandas/core/series.py", line 2459, in _binop
   result = func(this_vals, other_vals)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```
#### Problem description
I can't see how I could even get this error. It would require that `this_vals is None` in `series.py:_binop()`, which I don't see how could ever happen.

#### Expected Output

A `pandas.Series` with the result of the division.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Linux
OS-release: 4.14.127+
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.1
pytest: None
pip: 19.2.1
setuptools: 41.0.1
Cython: None
numpy: 1.16.3
scipy: 1.3.1
pyarrow: 0.13.0
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2019.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: 2.5.12
xlrd: 1.2.0
xlwt: None
xlsxwriter: 1.1.2
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: 1.2.16
pymysql: 0.8.1
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by charlesdong1991** [comment]
what does your data look like? And which version of pandas are you using?
I have a test on a simple case and it seems all work fine.

![Screen Shot 2019-08-15 at 2 03 36 PM](https://user-images.githubusercontent.com/9269816/63093454-a1488f80-bf65-11e9-8f77-11d8851176f1.png)

**Comment by jorisvandenbossche** [comment]
You can get this if the calling series is of object dtype with None in it:

```
In [4]: pd.Series([None, 1, 2], dtype=object).div(pd.Series([.1, .2, .3]))                                                                                                                                         
...
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

**Comment by connesy** [comment]
> You can get this if the calling series is of object dtype with None in it:
> 
> ```
> In [4]: pd.Series([None, 1, 2], dtype=object).div(pd.Series([.1, .2, .3]))                                                                                                                                         
> ...
> TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
> ```

Thank you!
