### ISSUE TITLE
DOC: Save File Image not found when generating Docs in parallel

### ISSUE THREAD

**Issue by bhavaniravi** [pandas-dev/pandas#27971]
#### Problem description

As a part of #27804 I tried adding `num-jobs=4` while generating docs. But the doc generation part fails since `doc/source/whatsnew/v0.7.3.rst` file refers to an image in `../savefig/scatter_matrix_kde.png` which is not generated from `doc/source/user_guide/visualization.rst`

#### Proposed solutions

Few solutions from the top of my mind
1. We can move these referenced files and have a static copy in `_static`(there are only 4 files we need to copy)
2. Remove these references from the `v0.7.3` since it is outdated

Discussing this with @datapythonista open to the community's thought on this.

**Comment by datapythonista** [comment]
Since 0.7.3 is more than 7 years old, I think removing the 3 plots from the release notes is all right: https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.7.3.html

CC @TomAugspurger

**Comment by TomAugspurger** [comment]
Sounds good.
