### ISSUE TITLE
Feature request: DataFrame.mse()

### ISSUE THREAD

**Issue by alik604** [pandas-dev/pandas#28004]
#### Code Sample
```python
def sample_MSE_implementation(df):
    from sklearn.metrics import mean_squared_error
    # If the user wish,they can pass the normalized df as a parameter
    # df=(df-df.min())/(df.max()-df.min()) 
    Matrix = [[round(mean_squared_error(df.iloc[:, row],df.iloc[:, col]),6) for row in range(df.columns.size)] for col in range(df.columns.size)] 

    cols = df.columns
    mse_df = pd.DataFrame(Matrix, columns=cols, index=cols)
    return mse_df
```

#### Problem description

I think there is a need for a `df.mse()`, similar to how there is a `df.corr()`. I have attached my own code and output to illustrate output and a very elementary implementation.

_My apologies if this is not the proper way to submit a feature requests. I would have made this a pull, however, I doubt the quility of my code_

#### Expected Output

![image](https://user-images.githubusercontent.com/29245410/63230121-75bfe200-c1bd-11e9-898d-e71cec9ba05d.png)
![image](https://user-images.githubusercontent.com/29245410/63230308-bf113100-c1bf-11e9-93c9-7a781c4e4914.png)

#### Output of ``pd.show_versions()``

<details>
please note that I am using colab.research.google.com

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Linux
OS-release: 4.14.79+
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 3.6.4
pip: 19.2.1
setuptools: 41.0.1
Cython: 0.29.13
numpy: 1.16.4
scipy: 1.3.1
pyarrow: 0.14.1
xarray: 0.11.3
IPython: 5.5.0
sphinx: 1.8.5
patsy: 0.5.1
dateutil: 2.5.3
pytz: 2018.9
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.9
feather: 0.4.0
matplotlib: 3.0.3
openpyxl: 2.5.9
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: None
lxml.etree: 4.2.6
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.3.6
pymysql: None
psycopg2: 2.7.6.1 (dt dec pq3 ext lo64)
jinja2: 2.10.1
s3fs: 0.3.3
fastparquet: None
pandas_gbq: 0.4.1
pandas_datareader: 0.7.4
gcsfs: None
</details>

**Comment by TomAugspurger** [comment]
Probably out of scope for pandas. We don't really do statistical modeling inside pandas.

**Comment by alik604** [comment]
Does anyone knows of any good utility libraries which already have, or would make a good fit for [MSE, MAD....]? I might as well pull this into a preexisting library, rather than diluting the ecosystem with _yet another library_  

I just came back to this issue since I needed my past code
