### ISSUE TITLE
Add Styler.applyformat to set values instead of styles

### ISSUE THREAD

**Issue by jamsden** [pandas-dev/pandas#28013]
I have a DataFrame that has multiple pairs of columns that are are title and URL. I would like to be able to render this table by converting the title to an anchor: `<a href=URL>title</a>`. 

Styler.format doesn't support this because the function only provides one value for a column and the format spec string doesn't support URL links.

Here's what I'd like to be able to do:
```
def to_href(title, url):
    return pd.Series([f"<a href={url[i]}>{title[i]}</a>" for i in range(len(title))])

ewm = client.executeSparql(query) # a DataFrame from a SPARQL result set
ewm.columns = ['Capability', 'Capability URL', 'Capability Status', 'Plan Item', 'Plan Item URL', 'Plan Item Status', 'Risk', 'Work Item', 'Work Item URL', 'Work Item Status']
ewmStyler = ewm.style 
ewmStyler.applyformat(to_href, axis=0, url=ewm['Capability URL'], subset='Capability')                
ewmStyler.hide_columns(['Capability URL','Plan Item URL', 'Work Item URL'])
HTML(ewmStyler.render())
```
That is, applyformat works just like apply, but set the values, not the style.

**Comment by TomAugspurger** [comment]
Can you make a minimal example? Does this require whatever your `client` is?

**Comment by jamsden** [comment]
client isn't relevant to the proposal, just copied from my example.

I'll make up another example that is minimal.

**Comment by jamsden** [comment]
```
data = [
    ['IBM', 'http://www.ibm.com', 'large'],
    ['Microsoft', 'http://www.microsoft.com', 'large'],
    ['Apple', 'http://www.apple.com', 'large'],
    ['OASIS', 'http://www.oasis-open.org', 'small'],
]
df = pd.DataFrame(data, columns=['Company', 'URL', 'Size'])
for i in range(len(df.index)):
    df.at[i, 'Company'] = f"<a href='{df.at[i, 'URL']}'>{df.at[i, 'Company']}</a>"
df.drop('URL',axis=1, inplace=True)
HTML(df.to_html(escape=False))
```
	Company	Size
0	IBM	large
1	Microsoft	large
2	Apple	large
3	OASIS	small

**Comment by jamsden** [comment]
Note that I am very new to Python and jupyter notebooks, so there may be a better way to do what I'm trying to accomplish.

**Comment by TomAugspurger** [comment]
Thanks. I don't understand the bug / feature request (which is it?). What isn't working properly?

DataFrame.style is for displaying the results. If you're wanting to change the values, that should be done before calling `.style`.

**Comment by jamsden** [comment]
Its a new feature request: Styler.applyformat method with the same signature as Styler.apply, but effects the data displayed, not the style used to display the data.

Most Styler methods effect the CSS style applied on an element when its rendered, not the element itself. Styler.format can change the format of the element's value, but it doesn't have access to multiple column values, and doesn't have a format spec string that supports HTML generation. I need something more flexible.

The example above does indeed work correctly, but it changes the data in the DataFrame, it doesn't just calculate how that data should be displayed. I don't really want to change the data, I just want to combine a couple of columns when formatting the output for display.

**Comment by attack68** [comment]
The Styler is designed to function based on the DataFrame, so if you want to style different underlying data, modify the data and then apply Styler.

As an example for your case you can modify the data on a Styler (which is added at instantiation) whilst maintaining the raw data:

```
data = [
    ['IBM', 'http://www.ibm.com', 'large'],
    ['Microsoft', 'http://www.microsoft.com', 'large'],
    ['Apple', 'http://www.apple.com', 'large'],
    ['OASIS', 'http://www.oasis-open.org', 'small'],
]
df = pd.DataFrame(data, columns=['Company', 'URL', 'Size'])
s = df.style
for i in range(len(s.data.index)):
    s.data.at[i, 'Company'] = f"<a href='{s.data.at[i, 'URL']}'>{s.data.at[i, 'Company']}</a>"
s.data.drop('URL',axis=1, inplace=True)
s
```
<table id="T_d269eb8e_d8a2_11ea_80e5_0c4de9c14f5b"><thead>    <tr>        <th class="blank level0"></th>        <th class="col_heading level0 col0">Company</th>        <th class="col_heading level0 col1">Size</th>    </tr></thead><tbody>
                <tr>
                        <th id="T_d269eb8e_d8a2_11ea_80e5_0c4de9c14f5blevel0_row0" class="row_heading level0 row0">0</th>
                        <td id="T_d269eb8e_d8a2_11ea_80e5_0c4de9c14f5brow0_col0" class="data row0 col0"><a href="http://www.ibm.com">IBM</a></td>
                        <td id="T_d269eb8e_d8a2_11ea_80e5_0c4de9c14f5brow0_col1" class="data row0 col1">large</td>
            </tr>
            <tr>
                        <th id="T_d269eb8e_d8a2_11ea_80e5_0c4de9c14f5blevel0_row1" class="row_heading level0 row1">1</th>
                        <td id="T_d269eb8e_d8a2_11ea_80e5_0c4de9c14f5brow1_col0" class="data row1 col0"><a href="http://www.microsoft.com">Microsoft</a></td>
                        <td id="T_d269eb8e_d8a2_11ea_80e5_0c4de9c14f5brow1_col1" class="data row1 col1">large</td>
            </tr>
            <tr>
                        <th id="T_d269eb8e_d8a2_11ea_80e5_0c4de9c14f5blevel0_row2" class="row_heading level0 row2">2</th>
                        <td id="T_d269eb8e_d8a2_11ea_80e5_0c4de9c14f5brow2_col0" class="data row2 col0"><a href="http://www.apple.com">Apple</a></td>
                        <td id="T_d269eb8e_d8a2_11ea_80e5_0c4de9c14f5brow2_col1" class="data row2 col1">large</td>
            </tr>
            <tr>
                        <th id="T_d269eb8e_d8a2_11ea_80e5_0c4de9c14f5blevel0_row3" class="row_heading level0 row3">3</th>
                        <td id="T_d269eb8e_d8a2_11ea_80e5_0c4de9c14f5brow3_col0" class="data row3 col0"><a href="http://www.oasis-open.org">OASIS</a></td>
                        <td id="T_d269eb8e_d8a2_11ea_80e5_0c4de9c14f5brow3_col1" class="data row3 col1">small</td>
            </tr>
    </tbody></table>

whilst:

```df```

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Company</th>
      <th>Size</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>&lt;a href='http://www.ibm.com'&gt;IBM&lt;/a&gt;</td>
      <td>large</td>
    </tr>
    <tr>
      <th>1</th>
      <td>&lt;a href='http://www.microsoft.com'&gt;Microsoft&lt;/a&gt;</td>
      <td>large</td>
    </tr>
    <tr>
      <th>2</th>
      <td>&lt;a href='http://www.apple.com'&gt;Apple&lt;/a&gt;</td>
      <td>large</td>
    </tr>
    <tr>
      <th>3</th>
      <td>&lt;a href='http://www.oasis-open.org'&gt;OASIS&lt;/a&gt;</td>
      <td>small</td>
    </tr>
  </tbody>
</table>

**Comment by attack68** [comment]
I agree with Tom that `Styler` is an instantiation that is supposed to work on the finalised DataFrame and display it.

If you have a similar routine that you perform repeatedly you may want to re factor it, or subclass it into the Styler creation, creating an additional column which is redundant from the raw data persepctive but useful for displaying.

`Styler` access the raw data from `Styler.data` and you could manipulate the content there (e.g. adding the column you want to display), and then hiding the data which was used in the construction.

A very simple example:

```
df = pd.DataFrame(data=[[1,2],[3,4]], columns=['A','B'])
s = Styler(df)
s.data['C'] = s.data['A'] + s.data['B']
s.hide_columns(subset=['A', 'B'])
s
```

**Comment by bala-analytics** [comment]
> This should demonstrate what I'm looking for. I want to use applyformat to combine the Company with its URL to form a link in the resulting DataFrame
> 
> ```
> data = [
>     ['IBM', 'http://www.ibm.com', 'large'],
>     ['Microsoft', 'http://www.microsoft.com', 'large'],
>     ['Apple', 'http://www.apple.com', 'large'],
>     ['OASIS', 'http://www.oasis-open.org', 'small'],
> ]
> df = pd.DataFrame(data, columns=['Company', 'URL', 'Size'])
> for i in range(len(df.index)):
>     df.at[i, 'Company'] = f"<a href='{df.at[i, 'URL']}'>{df.at[i, 'Company']}</a>"
> df.drop('URL',axis=1, inplace=True)
> HTML(df.to_html(escape=False))
> ```
> 
> Company	Size
> 0	[IBM](http://www.ibm.com)	large
> 1	[Microsoft](http://www.microsoft.com)	large
> 2	[Apple](http://www.apple.com)	large
> 3	[OASIS](http://www.oasis-open.org)	small

Not able  to reproduce this example.  Getting
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-ef84cee80b48> in <module>
      9     df.at[i, 'Company'] = f"<a href='{df.at[i, 'URL']}'>{df.at[i, 'Company']}</a>"
     10 df.drop('URL',axis=1, inplace=True)
---> 11 HTML(df.to_html(escape=False))

NameError: name 'HTML' is not defined

**Comment by attack68** [comment]
I understand what you are trying to do. However, I'm -1 on adding API for this specific case since it can be simulated very easily by manipulation of the underlying data and hiding columns:
![Screen Shot 2021-02-10 at 21 00 01](https://user-images.githubusercontent.com/24256554/107565907-800d4180-6be4-11eb-9337-c9a58b7575c8.png)

And alternatively since format accepts a function you can curry one (if it needs args) with functools partial and achieve exactly what you are after without impacting the underlying data:
![Screen Shot 2021-02-10 at 21 17 10](https://user-images.githubusercontent.com/24256554/107566655-71735a00-6be5-11eb-9ef2-8a09af4dba65.png)

**Comment by jamsden** [comment]
Agree, thanks for the great answer.
