### ISSUE TITLE
[Feature Request] pd.DataFrame.schema iterable

### ISSUE THREAD

**Issue by dazza-codes** [pandas-dev/pandas#28022]
#### Code Sample, a copy-pastable example if possible

```python
# feature request
schema = df.schema  # include all the index columns and the df.columns
for column in schema:
    print(column.name, column.dtype)  # plus other attributes?
```

Currently this is only available by using a pyarrow table, e.g.
```python
import pyarrow as pa
table = pa.Table.from_pandas(df)
schema = table.schema
schema_types = [[s.name, str(s.type).upper()] for s in schema]
```

It requires extra code to distinguish between index columns and other columns.
```python
# assuming schema from above pyarrow table
schema_dict = dict([[s.name, str(s.type).upper()] for s in schema])
# then iterate on df.index.names and df.columns to filter the schema_dict, e.g.
schema_index = dict([[name, schema_dict[name]] for name in df.index.names])
```

#### Problem description

- the df.info() is not iterable, it just prints information
  - also, it has no dtypes for the index columns

- the df.dtypes is a Series but it's not all columns, with index columns, e.g.

```python
types = df.dtypes
type(types)
# <class 'pandas.core.series.Series'>
types.index  # df.columns but not df.index columns
for idx in types.index:
    print(idx, types[idx])
```

- feature request for an iterable schema data structure

```python
schema = df.schema  # include all the index columns and the df.columns
for column in schema:
    print(column.name, column.dtype)

# the column object may have other attributes too:
column.name  # str
column.dtype  # numpy.dtype ?
column.is_index  # boolean

df.schema.to_dict()  # column.name as keys, column object as value
df.schema.to_sql()   # just DDL output
```

Similar schema are available if the DataFrame is serialized to parquet and read with pyarrow, but the pyarrow table schema is not iterable in the manner requested here.

Also note that `MultiIndex` has no dtypes, this feature request implicates new features for an index object.

**Comment by TomAugspurger** [comment]
Would a `DataFrame.dtypes(include_index=True)` solve this for you?

Though, in general, I agree that a simple schema data structure would be nice to have.

**Comment by darrenleeweber** [comment]
Yes, good suggestion if that is easier to implement, like `DataFrame.dtypes(include_index=True)` gets far enough to a fix for this, although the details might add more API options or attributes on the `dtype` object returned, e.g.

```python
dtypes = DataFrame.dtypes(include_index=True)
dtype_obj = next(dtypes)
dtype_obj.is_index  # boolean

# Alt-API with defaults
dtypes = DataFrame.dtypes(columns=True, index=False)
dtype_obj = next(dtypes)
dtype_obj.is_index  # boolean

# Other options might be like
pd.to_schema(df)
pd.to_sql(df, schema=True, values=False)
```

Not particularly opinionated about the naming of `dtype_obj` vs. `schema_obj`, although `pyarrow` is using a `schema` concept and token.  The feature request for pandas does not require compatibility with `pyarrow` but it might help.

**Comment by jreback** [comment]
we have long had https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.select_dtypes.html?highlight=select_dtypes and have the .dtypes attribute so -1 in adding anything else

**Comment by darrenleeweber** [comment]
@jreback - good catch, but note how the docs do not illustrate whether or not this includes any index dtype data - the bet is that it does not, and, if so, the feature request stands (or implies that it should support index dtypes too).  Also, does it support the `is_index` attribute?  The `schema` concept and API is, IMO, an obvious go-to feature.

**Comment by TomAugspurger** [comment]
@darrenleeweber I don't think adding a `.is_index` attribute to a NumPy dtype is possible (or necessarily desirable).

**Comment by darrenleeweber** [comment]
Right, agreed.  Perhaps it's something like this:

```python
class SchemaItem(NamedTuple):
    name: str
    dtype: np.dtype
    is_index: bool = False

def schema(self):
    types = df.dtypes
    for idx in types.index:
        schema_item = SchemaItem(name=idx, dtype=types[idx])
        if schema_item in self.index:
            schema_item.is_index = True
        yield schema_item
```

**Comment by TomAugspurger** [comment]
So I guess the thing to do now is to make a convincing case why this is
better than current options
for making a schema defining a pandas object. Right now, the best option is
probably an empty
DataFrame with the right dtypes, names, indexes, etc.

There's a lot of complexity to a DataFrame (even in your simple example,
`name: str` is incorrect since a
column name need not be a string), so we'll need some compelling use cases
and benefits to taking
on this API.

**Comment by mroeschke** [comment]
Thanks for the suggestion but it appears this features hasn't had much interest from the core devs and community over the years so closing. Can reopen if there's renewed interest
