### ISSUE TITLE
SettingWithCopyWarning in pandas code

### ISSUE THREAD

**Issue by msAlcantara** [pandas-dev/pandas#28033]
#### Code Sample, a copy-pastable example if possible

```python
df.loc[:, 'column'] = value

```
#### Problem description

`SettingWithCopyWarning` in pandas code

#### Output

```
/home/matheus/dev/my-project/venv/lib/python3.6/site-packages/pandas/core/indexing.py:362: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/home/matheus/dev/my-project/venv/lib/python3.6/site-packages/pandas/core/indexing.py:480: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s
```

#### Output of ``pd.show_versions()``
<details>

In [2]: pd.show_versions()                                                                                                                                    

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-58-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.0
numpy            : 1.17.0
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.2
setuptools       : 40.6.2
Cython           : None
pytest           : 4.4.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.0.5
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.3 (dt dec pq3 ext lo64)
jinja2           : None
IPython          : 7.5.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : 2.7.0
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : 3.4.3
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : 1.0.5

</details>

**Comment by TomAugspurger** [comment]
It's not clear what you're reporting. http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by msAlcantara** [comment]
It's a problem in code example
