### ISSUE TITLE
REGR: Index.union should pick correct dtype for combinations of tstamps with different tzones

### ISSUE THREAD

**Issue by zogzog** [pandas-dev/pandas#28034]
Here's a pdb session showing the issue:

```python
ipdb> basei
DatetimeIndex(['2017-10-28 23:00:00+00:00', '2017-10-29 00:00:00+00:00',
               '2017-10-29 01:00:00+00:00', '2017-10-29 02:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq=None)
ipdb> diffi
DatetimeIndex(['2017-10-29 02:00:00+01:00', '2017-10-29 03:00:00+01:00',
               '2017-10-29 04:00:00+01:00', '2017-10-29 05:00:00+01:00'],
              dtype='datetime64[ns, Europe/Paris]', freq=None)
ipdb> basei.union(diffi)
Index([2017-10-28 23:00:00+00:00, 2017-10-29 00:00:00+00:00,
       2017-10-29 01:00:00+00:00, 2017-10-29 02:00:00+00:00,
       2017-10-29 04:00:00+01:00, 2017-10-29 05:00:00+01:00],
      dtype='object')

```
With pandas 0.24 I got back an index with a `dtype='datetime64[ns, UTC]'`

This looks a bit like a cousin of https://github.com/pandas-dev/pandas/issues/26778

**Comment by TomAugspurger** [comment]
I think that was a deliberate change: https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.25.0.html#incompatible-index-type-unions.

cc @ArtinSarraf if you recall whether mix of datetimetz was discussed.

**Comment by zogzog** [comment]
I've seen the "incompatible types" discussion but I feel like this is going too far. Admittedly this is an edge case.

**Comment by TomAugspurger** [comment]
The ints and float case is a reasonable analogy. But with ints & floats
it's not clear (to me) that the loss
of precision for integers is the best outcome. You could make a similar
argument for datetimetz and
daylight savings issues, when combining multiple timezones.

**Comment by mroeschke** [comment]
I agree that this is a deliberate change in the right direction as to prevent the loss of original timezone information akin to this change back in 0.24.0: https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.24.0.html#parsing-datetime-strings-with-timezone-offsets

You can always `to_datetime(..., utc=True)` to coerce your result to UTC.

**Comment by zogzog** [comment]
Timezone information, as far as I am concerned, is a _presentation_ information, a bit like the 'freq' attribute. Two timestamps in differing timezones are fundamentally compatible, and losing timezones is about dropping display information. Are there situations where this would be wrong ?

Another point: it already cost me an hour to write code to paper over the issue. I have a non-indecent test base, but real world tests reveal that I have non-handled edge cases. So it's not just a matter of .tz_converting the offending index and the cost of reimplementing myself what .union did previously is going to mount.

**Comment by jreback** [comment]
> Timezone information, as far as I am concerned, is a _presentation_ information, a bit like the 'freq' attribute. Two timestamps in differing timezones are fundamentally compatible, and losing timezones is about dropping display information. Are there situations where this would be wrong ?
> 

this is not the case at all in pandas; time zones are first class; turning them to UTC is losing information; we have deliberately tried not to do this generally

mixing times zones while possible is often a bug in user code; it’s possible but very likely not something you want library code to do, rather it becomes a burden of the user code

> Another point: it already cost me an hour to write code to paper over the issue. I have a non-indecent test base, but real world tests reveal that I have non-handled edge cases. So it's not just a matter of .tz_converting the offending index and the cost of reimplementing myself what .union did previously is going to mount. In other words, this is a _breaking_ change.

not really sure what is your point here. pandas has lots of users; api changes are a fact of life

**Comment by zogzog** [comment]
mixed time zones a bug in user code ? can you expand ?

**Comment by ArtinSarraf** [comment]
@TomAugspurger - yes, this exact case was discussed explicitly.

https://github.com/pandas-dev/pandas/pull/23538#discussion_r238116253

**Comment by zogzog** [comment]
@ArtinSarraf can you expand on your dst transition ambiguity example ? For my personal education I'd like to understand the issue (if only because I currently believe tz-aware stamps don't have ambiguity issues).

**Comment by ArtinSarraf** [comment]
Ignore my comment, what I was thinking of wasn't an issue with already tz-aware date ranges, but rather the ambiguity than can occur from localizing a non tz-aware date range.

**Comment by zogzog** [comment]
The very fact tz-aware tstamps are non-abiguous is the reason I think this is a regression. The actual timezones are _display_ information (just like `freq`). There is no _fundamental_ information loss when the time zone is aligned to UTC.

**Comment by jreback** [comment]
@zogzog pls read my comments again. there is loss of information as pandas keeeps the tz meta data as part of the dtype; so by definition you are losing information.

**Comment by zogzog** [comment]
I've read your comment. "By definition" doesn't cut it. Did you read mine and try to understand the argument and address it ?

**Comment by zogzog** [comment]
@mroeschke thanks, but I had perfectly well understood. I stand by my position that this is a benign loss, in fact a complete non-issue. Apart from the principled position you take (which of course I'm not opposed to in abstract), I would love to know where _in practice_ this would cause issues. Did the previous design cause real-world issues ? Do you have real-world data, like bug reports, indicating that it is wrong to switch the time zone ?

**Comment by mroeschke** [comment]
I imagine any piece of logic that is trying to detect the original timezone and suddenly getting UTC would be impacted by automatic coercion to UTC.

As mentioned above, this was a deliberate API change and this is a move toward maintaining original data types. Going to close this issue as there's not much appetite to go the other direction
