### ISSUE TITLE
Does read_hdf() in v0.25 really support "file-like object" as it claims?

### ISSUE THREAD

**Issue by huangsongjue** [pandas-dev/pandas#28057]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd
 
pd.read_hdf('housing.h5')
f=open('housing.h5', 'r')
pd.read_hdf(f)
```
#### Problem description
 https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_hdf.html says:

> path_or_buf : str, path object, pandas.HDFStore or file-like object
            By file-like object, we refer to objects with a read() method, such as a file handler (e.g. via builtin open function) or StringIO.
> 

#### Somehow when I was trying to  use a 'file-like object', just as in pd.read_csv(), I encountered error  below:

NotImplementedError                       Traceback (most recent call last)
<ipython-input-5-25a431458ef6> in \<module\>()
----> 1 pd.read_hdf(f)

~/anaconda3/lib/python3.6/site-packages/pandas/io/pytables.py in read_hdf(path_or_buf, key, mode, **kwargs)
    368         if not isinstance(path_or_buf, str):
    369             raise NotImplementedError(
--> 370                 "Support for generic buffers has not " "been implemented."
    371             )
    372         try:

NotImplementedError: Support for generic buffers has not been implemented.

#### Expected Output
Out[3]: 
      MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  Longitude  Price
0     3.1327      24.0  4.665122   1.020857      2264.0  2.623407     36.93    -121.75  2.181
1     3.6000      48.0  4.988920   0.977839      1071.0  2.966759     36.92    -121.75  1.945
2     2.4615      46.0  4.465574   1.052459      1068.0  3.501639     36.92    -121.75  1.778
3     3.2216      36.0  5.319797   1.038071      1454.0  3.690355     36.92    -121.76  2.383
4     3.4125      46.0  3.587121   0.973485      1120.0  4.242424     36.92    -121.76  1.607
...      ...       ...       ...        ...         ...       ...       ...        ...    ...
2058  4.1250      37.0  7.285714   1.214286        29.0  2.071429     39.12    -121.52  0.720
2059  2.1667      36.0  6.573099   1.076023       504.0  2.947368     39.18    -121.43  0.938
2060  3.0000       5.0  6.067797   1.101695       169.0  2.864407     39.13    -121.32  1.625
2061  2.5952      19.0  5.238462   1.079487      1018.0  2.610256     39.10    -121.48  0.924
2062  2.0943      28.0  5.519802   1.020902      6912.0  3.801980     39.12    -121.39  1.083

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-957.5.1.el7.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.0
numpy            : 1.17.0
pytz             : 2018.4
dateutil         : 2.7.3
pip              : 19.2.1
setuptools       : 41.0.1
Cython           : 0.28.5
pytest           : 3.5.1
hypothesis       : None
sphinx           : 1.7.4
blosc            : None
feather          : None
xlsxwriter       : 1.0.4
lxml.etree       : 4.2.5
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10
IPython          : 6.4.0
pandas_datareader: 0.7.4
bs4              : 4.6.0
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.2.5
matplotlib       : 2.2.2
numexpr          : 2.6.5
odfpy            : None
openpyxl         : 2.5.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.1.0
sqlalchemy       : 1.2.7
tables           : 3.4.3
xarray           : None
xlrd             : 1.1.0
xlwt             : 1.3.0
xlsxwriter       : 1.0.4
</details>

**Comment by jreback** [comment]
this is only implemented for a proper PyTables file like object
opening a file in an arbitrary way is not supported
