### ISSUE TITLE
ValueError: buffer source array is read-only on DatetimeIndex with one element

### ISSUE THREAD

**Issue by mir06** [pandas-dev/pandas#28055]
#### Code Sample

```python
# Your code here
import pandas as pd
import numpy as np
times = np.array([np.datetime64('2012-02-15T12:00:00.000000000')])
times.setflags(write=False)

[d for d in pd.to_datetime(times)]
```
#### Problem description

The above code raises a `ValueError: buffer source array is read-only` during the iteration over the `DatetimeIndex`.

**Note**: This code snippet is just for demonstration. Read-only arrays are generated e.g. from an xarray `broadcast`.

This did not happen for pandas<=0.25.0

#### Expected Output
```python
[Timestamp('2012-02-15 12:00:00')]
```

#### Output of ``pd.show_versions()``

```shell
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.0-5-amd64
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.0
numpy            : 1.17.0
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.2
setuptools       : 41.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.7.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
```

**Comment by TomAugspurger** [comment]
May need a fix similar to https://github.com/pandas-dev/pandas/pull/27946/files, but in `ints_to_pydatetime`. Care to submit a PR?

**Comment by jbrockmendel** [comment]
Looks like in pd._libs.tslib.ints_to_pydatetime the argument `int64_t[:] arr` needs to be changed to `const int64_t[:] arr`.  PR welcome.

**Comment by TomAugspurger** [comment]
FYI @jorisvandenbossche I'm probably doing the release todayish, so I'm going to move this off the 0.25.1 milestone.

**Comment by jorisvandenbossche** [comment]
I prefer to keep those issue on *a* milestone. If you want to get the queue clear on 0.25.1, it can be 0.25.2 (but for me just a 0.25.x milestone could also do). If not for 0.25.1/2, then 1.0. By default, I think we should mark regressions for the next milestone, even if nobody is directly going to work on it.

**Comment by TomAugspurger** [comment]
Sounds good.
