### ISSUE TITLE
Circular reference warning after subsetting data frame AND AFTER COPY

### ISSUE THREAD

**Issue by yusosov** [pandas-dev/pandas#28094]
# PLEASE READ AND RUN BEFORE CLOSING

it is after subsetting that the warning appears no meter if copy is used  

# WARNING AFTER SUBSETTING no matter if COPY was used
import pandas
import numpy

df1 = pandas.DataFrame(numpy.array([[1, '123', 3], [4, 'dE1', 6], [7, 'gH2', 9]]), columns=['a', 'b', 'c'])
df2 = df1[['a', 'b']]
df2['b']=df2['b'].apply(str.lower) .copy(deep=True) 
df2

# or

df1 = pandas.DataFrame(numpy.array([[1, '123', 3], [4, 'dE1', 6], [7, 'gH2', 9]]), columns=['a', 'b', 'c'])
df2 = df1[['a', 'b']]
df2['b']=df2['b'].apply(str.lower).copy(deep=False)
df2

# or

df1 = pandas.DataFrame(numpy.array([[1, '123', 3], [4, 'dE1', 6], [7, 'gH2', 9]]), columns=['a', 'b', 'c'])
df2 = df1[['a', 'b']]
df2['b']=df2['b'].apply(str.lower)
df2

# COMPARE: NO WARNING:

import pandas
import numpy

df1 = pandas.DataFrame(numpy.array([[1, '123', 3], [4, 'dE1', 6], [7, 'gH2', 9]]), columns=['a', 'b', 'c'])
df1['b']=df1['b'].apply(str.lower).copy(deep=True)
df1

# or

df1 = pandas.DataFrame(numpy.array([[1, '123', 3], [4, 'dE1', 6], [7, 'gH2', 9]]), columns=['a', 'b', 'c'])
df1['b']=df1['b'].apply(str.lower) .copy(deep=False)
df1

# or

df1 = pandas.DataFrame(numpy.array([[1, '123', 3], [4, 'dE1', 6], [7, 'gH2', 9]]), columns=['a', 'b', 'c'])
df1['b']=df1['b'].apply(str.lower)
df1

no matter if I use copy or not I always get the same warning:
/home/owner/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

#### Output of ``pd.show_versions()``

<details>
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.0.0-26-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.0
numpy            : 1.17.0
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.2
setuptools       : 41.0.1
Cython           : 0.29.13
pytest           : 5.0.1
hypothesis       : None
sphinx           : 2.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.4.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.7.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.0
matplotlib       : 3.1.0
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.3.6
tables           : 3.5.2
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.8
</details>

**Comment by jreback** [comment]
try this, as i said you didn’t read the comments; copying decouples the start frame (df1) from a reference (df2)

df1 = pandas.DataFrame(numpy.array([[1, '123', 3], [4, 'dE1', 6], [7, 'gH2', 9]]), columns=['a', 'b', 'c'])

this is the copy that matters
df2 = df1[['a', 'b']].copy()

a copy here doesn’t matter 
df2['b']=df2['b'].apply(str.lower) .copy(deep=True)
df2

**Comment by yusosov** [comment]
I got it. Thank you.
But, I do not want to copy the whole subset  df1[['a', 'b']]. In reality my data is LARGE.
I need to spare memory. This is why I wanted to assign a copy of just one column.
I hope df.copy(deep=False) creates just new refs. This "workaround" is rather unnatural.
Thanks again anyway.

**Comment by yusosov** [comment]
@jreback
I am sorry to come up with a question again, but still I do not see any logic here:

this seem not to create circular references:

import pandas
import numpy

df1 = pandas.DataFrame(numpy.array([[1, '123', 3], [4, 'dE1', 6], [7, 'gH2', 9]]), columns=['a', 'b', 'c'])
df2 = df1[['a', 'b']].copy()
# seems ok, no warning
df2['b']=df1['b'].apply(str.lower)
df2

but the next seem to clearly create circular references df2 to itself, but it works properly, gives no warnings:

df1 = pandas.DataFrame(numpy.array([[1, '123', 3], [4, 'dE1', 6], [7, 'gH2', 9]]), columns=['a', 'b', 'c'])
df2 = df1[['a', 'b']].copy()
# seems ok, no warning
df2['b']=df2['b'].apply(str.lower)
df2

I mean what is going on here is "not natural".
