### ISSUE TITLE
Circular reference warning after subsetting data frame

### ISSUE THREAD

**Issue by yusosov** [pandas-dev/pandas#28093]
# NO WARNING:

import pandas
import numpy
df1 = pandas.DataFrame(numpy.array([[1, '123', 3], [4, 'dE1', 6], [7, 'gH2', 9]]), columns=['a', 'b', 'c'])
df1['b']=df1['b'].apply(str.lower) #.copy(deep=True)#.copy(deep=False)
df1

# WARNING
import pandas
import numpy
df1 = pandas.DataFrame(numpy.array([[1, '123', 3], [4, 'dE1', 6], [7, 'gH2', 9]]), columns=['a', 'b', 'c'])
df2 = df1[['a', 'b']]
df2['b']=df2['b'].apply(str.lower) #.copy(deep=True) #.copy(deep=False)
df2

no matter if I use copy or not I always get the same warning:
/home/owner/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

#### Output of ``pd.show_versions()``

<details>
[the output of ``pd.show_versions()`` below:]

commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.0.0-26-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.0
numpy            : 1.17.0
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.2
setuptools       : 41.0.1
Cython           : 0.29.13
pytest           : 5.0.1
hypothesis       : None
sphinx           : 2.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.4.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.7.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.0
matplotlib       : 3.1.0
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.3.6
tables           : 3.5.2
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.8
</details>

**Comment by jreback** [comment]
you need to copy before you assign otherwise you have a reference

**Comment by yusosov** [comment]
@ jreback 
PLEASE READ 
NO MATTER IF I COPY OR DEEPCOPY I GET THIS WARNING

**Comment by jreback** [comment]
@yusosov pls don’t shout

read my comment again - you need to copy before you assign the column
your text shows you copying after

**Comment by yusosov** [comment]
@ jreback

do you mean like:

df1 = pandas.DataFrame(numpy.array([[1, '123', 3], [4, 'dE1', 6], [7, 'gH2', 9]]), columns=['a', 'b', 'c'])
df2 = df1[['a', 'b']].copy()
df2['b']=df1['b'].apply(str.lower)
df2

it works, in this example, but in reality what I have to copy is LARGE and I do not want to spend extra memory. and I do not see any other fast way to apply a function to a column in pandas.

**Comment by jreback** [comment]
so ithe way to do this is to overwrite in the original (df1)
then subset

or just .copy() which actually is pretty cheap

also you should use
df1.b.str.lower()
