### ISSUE TITLE
Pandas ExcelWriter append fails to preserve images in other sheets.

### ISSUE THREAD

**Issue by tsieczko** [pandas-dev/pandas#28106]
```python
import pandas

df = pandas.DataFrame([[1,2,3],[4,5,6]])

with pd.ExcelWriter('input_excel.xlsx', mode='a') as writer:
	df.to_excel(writer, sheet_name='PandasTestSheet')

```
#### Problem description

'input_excel.xlsx' contains one sheet with some data in cells and an image added via excel's insert picture from file function. When I attempt to append a dataframe to a second new sheet, the resulting excel file no longer has the image in the first sheet.

#### Expected Output

The first sheet should be untouched with the image still there. The second sheet should contain the contents of the dataframe.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.0
numpy            : 1.16.4
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.2
setuptools       : 41.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 2.1.2
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 2.5.14
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by WillAyd** [comment]
Does openpyxl maintain these objects on open / save?

**Comment by tsieczko** [comment]
```python
import sys
from openpyxl import load_workbook

input_file = sys.argv[1]

# open a workbook
wb = load_workbook(input_file)

# add sheet and write to cells
ws = wb.create_sheet('TestSheet')
ws['A1'] = 1
ws['A2'] = 2
ws['A3'] = 3

# write workbook
wb.save('out.xlsx')
```

It appears that openpyxl does the same thing. Images are not preserved in existing sheets. I guess this is an issue with openpyxl since pandas uses it for appending right?

**Comment by WillAyd** [comment]
Any chance upgrading to 2.6 helps? I see in the changelog for that a bug fix regarding the preservation of images

https://openpyxl.readthedocs.io/en/stable/changes.html#id23

**Comment by WillAyd** [comment]
Though might also be a limitation per warning in current docs:

https://openpyxl.readthedocs.io/en/latest/usage.html#read-an-existing-workbook

If you would like to investigate and see if there's a reasonable way to support this I think would be useful.

**Comment by tsieczko** [comment]
Just tried 2.6.2. Not working unfortunately. I'll investigate openpyxl. Thanks!

**Comment by WillAyd** [comment]
Sure - closing for now as I think this is just a limitation of the underlying library, but feel free to ping back if there ever becomes a way to make this work
