### ISSUE TITLE
to_datetime errors='ignore' unexpected behavior

### ISSUE THREAD

**Issue by stephanievela** [pandas-dev/pandas#28120]
I'm trying to apply pd.to_datetime on an integer column to convert integers (including missing indicators) to datetimes. In order to preserve all the missing indicators, ideally, I would prefer setting the "errors" parameter to "ignore" to keep all the invalid parsings. But then I noticed that setting errors='ignore' not only preserved the missing indicators, but kept everything the same, even the dtype of the input column. See below for more details.  
 
```python
print(dt_col)
```
<Outputs>
0    20181223

1    20161017
2      -99998
3    20171220
4    20170511
Name: dt_col, dtype: int64
</Outputs>

```python
pd.to_datetime(dt_col, format='%Y%m%d', errors='ignore')
```
<Outputs>
0    20181223

1    20161017
2      -99998
3    20171220
4    20170511
Name: dt_col, dtype: int64

</Outputs>

```python
pd.to_datetime(dt_col, format='%Y%m%d', errors='coerce')
```
<Outputs>
0   2018-12-23

1   2016-10-17
2          NaT
3   2017-12-20
4   2017-05-11
Name: dt_col, dtype: datetime64[ns]

</Outputs>

Pandas version: 
- pandas==0.25.1

Is anyone else seeing the same behavior?

**Comment by TomAugspurger** [comment]
>  I would prefer setting the "errors" parameter to "ignore" to keep all the invalid parsings.

What's your expected output here? You can't have non-datetime64 values inside a datetime64 column.

**Comment by stephanievela** [comment]
That’s fair. I get your point. But I’m expecting at least the 0, 1, 3, 4-indexed integers being converted to date times, and -99998 can be left as-is. Is that something I should be anticipating?

**Comment by WillAyd** [comment]
This does seem a little counter intuitive so I think a bug. If you'd like to investigate would certainly take a PR to fix

**Comment by jreback** [comment]
not a bug this is doing exactly as advertised 
-99998 is not a valid date and hence not converted

we do not construct object arrays here (which would allow you to hold this value); this would be extremely inefficient

**Comment by WillAyd** [comment]
Hmm so is there any real point to ignore? I was expecting it to mimic what you would get from:

```python
In [32]: ser = pd.Series(["20181223", "-99998"])

In [33]: pd.to_datetime(ser, format="%Y%m%d", errors="coerce").fillna(ser)
Out[33]:
0    2018-12-23 00:00:00
1                 -99998
dtype: object
```

Instead of just returning the caller

**Comment by mroeschke** [comment]
It sounds like from the discussion that this is the expected behavior therefore closing. If there is further discussion on what the behavior should be we can reopen
