### ISSUE TITLE
New characteristic to cumsum

### ISSUE THREAD

**Issue by josephnowak** [pandas-dev/pandas#28127]
Hi, I would like to know if is possible to add to the cumsum method the option to make an operation (multiplication of a constant for example or a lambda function) while it is making every sum to get something like this: https://stackoverflow.com/questions/34182755/cumulative-addition-multiplication-in-numpy, I know this could look a little unnecesarry but this kind of cumulative sum appears in a lot of formulas of economic indexs and I think there are other cases where this can be useful. The reason of this request is that when the data is very big use a normal python loop is not a nice option due to the time it take, or even using the solution of the link is not a good idea due to the precision of the floats number.

**Comment by jbrockmendel** [comment]
Doing this with a general-case lambda I don't think we could implement anything any faster than the loop described in the stackoverflow link.  For that particular use case, the answers given there look pretty well optimized.

Are there other cases you have in mind?  e.g. some parametrized class of functions?

**Comment by josephnowak** [comment]
The solution in the link is a very fast solution the problem is for example if you are working with percetage, so in that case will lead to this "Please be mindful that for extremely huge input array cases if the b elements are such small fractions, because of cummulative operations, the initial numbers of b_rev_cumprod might come out as zeros resulting in NaNs in those initial places." that is the last part of the link which is exactly what happen to me, in fact I use a constant with a value of 0.03 and when I run this in a df with 5003 rows it has to calculate (0.03)^5003 which converge to  NaN. I was thinking if there is possible to implement at least the for loop in cython to speeds up the calculus but if this is not possible there is no problem, Important: If the lambda is not an option should be useful pass another Series for example or a numpy array.

**Comment by WillAyd** [comment]
Is there a general purpose application like this that you may have come across in other languages? Might be a little too niche for pandas

**Comment by mroeschke** [comment]
Agreed that this may be too niche for pandas as #4567 also discusses that this is out of scope for pandas. Thanks for the suggestion but closing since there's not enough vetted supported from the core devs
