### ISSUE TITLE
Get nth group of groups

### ISSUE THREAD

**Issue by abbazs** [pandas-dev/pandas#28138]
I would like to request a method similar to `GroupBy.get_group(self, name, obj=None)` [(documentation)](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.GroupBy.get_group.html), a method that can return a group by its index say call it as `GroupBy.get_nth_group(self, nth)`. 
If there are 10 groups by calling `get_nth_group(4)` shall return the 4th group.

**Comment by simonjayhawkins** [comment]
see also https://github.com/pandas-dev/pandas/issues/9397#issuecomment-418898264

**Comment by jreback** [comment]
this is a duplicate
