### ISSUE TITLE
Document that Pandas 0.25.2 should be compatible with Python 3.8

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#28147]
https://github.com/pandas-dev/pandas/pull/28101 gets things passing with Python 3.8 locally.

Ideally, we'd have 3.8 actually tested on CI before releasing 0.25.2. Hopefully once https://github.com/conda-forge/python-feedstock/pull/271 is up, we can do that (and maybe build our deps from source).

Once we're tested, we should add a note to the whatsnew saying that pandas 0.25.2 is compatible with Python 3.8

**Comment by shafaypro** [comment]
Yes Indeed.

**Comment by TomAugspurger** [comment]
Reran with Python 3.8b4. Things seem OK, but a bunch of plotting tests are failing.

**Comment by lizsaret** [comment]
@TomAugspurger can i work on this?

**Comment by TomAugspurger** [comment]
This is currently blocked by https://github.com/conda-forge/python-feedstock/pull/271. I'm a bit hesitant to state that we're 3.8 compatible until we're actually testing on CI.

**Comment by jreback** [comment]
agreed we have no testing on 3.8 yet
