### ISSUE TITLE
Series construction: _try_cast typo, function often taking slow route?

### ISSUE THREAD

**Issue by machow** [pandas-dev/pandas#28145]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
from pandas.core.internals.construction import _try_cast

arr = np.arange(0, 10, dtype = "int64")

# should return early
_try_cast(arr, None, False, False)
```
#### Problem description

During series construction, a function, `sanitize_array` attempts to use `_try_cast`, to cast the input to a better type. `_try_cast` is fairly slow to run, so it tries to avoid casting in common cases. However, due to a missing `not` keyword, it appears `_try_cast` **runs for the cases it wants to avoid (like the one above)**.

Here are the relevant lines of `_try_catch`:

https://github.com/pandas-dev/pandas/blob/master/pandas/core/construction.py#L511-L513

Should this be `not maybe_castable(arr)`? 

It is very surprising that lines like this would intentially create an array, and then try to cast it, even when the dtype option passed is None.

https://github.com/pandas-dev/pandas/blob/master/pandas/core/construction.py#L429-L432

#### Expected Output

`_try_cast` not run during `sanitize_array` for common types (e.g. int64). However, from looking at it with `%%prune`, and running pdb, I can see functions like `maybe_cast_to_datetime` are called.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 17.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.16.1
pytz             : 2018.9
dateutil         : 2.8.0
pip              : 19.1.1
setuptools       : 39.0.1
Cython           : None
pytest           : 4.4.2
hypothesis       : None
sphinx           : 2.0.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : 0.9.3
psycopg2         : 2.8.2 (dt dec pq3 ext lo64)
jinja2           : 2.10.1
IPython          : 7.5.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.0
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.2.1
sqlalchemy       : 1.3.4
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by WillAyd** [comment]
Is there something from a user-facing perspective that you see impacted by this? The linked code you have just points to the range section which may or may not be what your question is limited to - would be helpful to clarify that

**Comment by machow** [comment]
Hey @WillAyd thanks for your prompt response! It appears that `_try_cast` comprises about 30% of Series construction time, so if this is a bug, then fixing will greatly speed this up.

![image](https://user-images.githubusercontent.com/2574498/63659727-0891eb00-c781-11e9-8c0e-47db59a693dd.png)

I would say there are 2 other related cases that will benefit

* Series constructed during simple operations, like `ser + 1`.
* Internal Series construction. For example, in `some_grouped_df.some_col.transform`

(If this isn't a bug, my apologies! :)

**Comment by WillAyd** [comment]
Cool thanks. I'm personally not super familiar with this part of the code so can't say for certain but seems reasonable. You can try it and run the test suite to see if nothing breaks and if not submit a PR

Also would be worth confirming with an ASV. I only see one for a datetime constructor in asv_bench/benchmarks/series_methods.py which might not be applicable, but could add one if not covered

**Comment by machow** [comment]
Okay, thanks for the quick feedback--I'll try adding a `not` and check whether any tests break. As far as I can tell, an "int64" array will never make it through, when the dtype arg to `_try_cast` is None.

On the other hand, it seems like this behavior is a couple years old, so I wouldn't be surprised if I'm missing something.

**Comment by machow** [comment]
Alright, I'm having a bit of trouble running the full suite of tests, but ran the tests below.

```
pytest pandas/tests/{groupby,series,dtypes,internals,tseries} --cov=pandas -r sxX --strict
```

There were 7 failures, related to the change stopping `_try_cast` from converting numpy arrays with dtype "O".  It makes sense to try to cast them, and looking through the code, it appears that it's the only case any casting will happen.

https://github.com/pandas-dev/pandas/blob/5d9fd7e3b226b68e695d87121f584202aa6d4abc/pandas/core/construction.py#L521

https://github.com/pandas-dev/pandas/blob/5d9fd7e3b226b68e695d87121f584202aa6d4abc/pandas/core/dtypes/cast.py#L932-L934

I'll take another pass at the tests, hopefully in the next couple days!

**Comment by jbrockmendel** [comment]
Changing `if maybe_castable` to `if not maybe_castable` in construction._try_cast breaks  140 tests for me.  Based on skimming it looks like datetime64TZ dtypes are involved in most of the failures.
