### ISSUE TITLE
Inconsistency with ints and floats

### ISSUE THREAD

**Issue by vlbrown** [pandas-dev/pandas#28155]
#### Problem description

   1. pandas statistics sometimes produce numpy data types and sometimes not. This is inconsistent.
   2. json_dumps cannot serialize int64 (not a pandas issue but that's how I got here)

 I created a dictionary containing pandas stats.  The input is a pandas series, s, dtype float64.

The methods used are
```
s.count()
s.max()
s.min()
s.mean()
s.median()
s.mode()[0]
s.std()
```

Apparently, pandas returns numpy ints and numpy floats (sometimes).
```
count 564 <class 'numpy.int64'>
max 33.46 <class 'float'>
min 7.36 <class 'float'>
mean 24.727588652482286 <class 'float'>
median 26.28 <class 'float'>
mode 25.6 <class 'numpy.float64'>
std 5.857237135129123 <class 'float'>
````
Note:

This discrepancy matters because  `json.dump` cannot currently serialize objects of type int64. 

Apparently pandas DataFrame.to_json() method has no such issues. Converting the dictionary to a dataframe and then writing it out to JSON works without error.

Perhaps pandas could share the `to_json` code with the Python json library devs, resolving [Python issue 24313](https://bugs.python.org/issue24313)

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 15.6.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.0
numpy            : 1.16.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.1.1
setuptools       : 41.0.1
Cython           : 0.29.12
pytest           : 5.0.1
hypothesis       : None
sphinx           : 2.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.3.4
html5lib         : 1.0.1
pymysql          : 0.9.3
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.7.0
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.4
matplotlib       : 3.1.0
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.0
sqlalchemy       : 1.3.5
tables           : 3.5.2
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.8
</details>

**Comment by MarcoGorelli** [comment]
@vlbrown is this what you're referring to?
```
>>> import pandas as pd
>>> import numpy as np
>>> s = pd.Series(np.random.randn(10))                                      
>>> type(s.count())                                                         
numpy.int64

>>> type(s.max())                                                          
float
```

**Comment by mroeschke** [comment]
We're happy to reopen this issue when we can validate the issue with a reproducible example.
