### ISSUE TITLE
DOC: User Guide - enhancing performance - using ndarray

### ISSUE THREAD

**Issue by iwpnd** [pandas-dev/pandas#28167]
```python 
In [11]: %prun -l 4 apply_integrate_f(df['a'].to_numpy(),
   ....:                              df['b'].to_numpy(),
   ....:                              df['N'].to_numpy())
   ....: 
  File "<ipython-input-11-613f5c6ec02d>", line 2
    df['b'].to_numpy(),
    ^
IndentationError: unexpected indent
```

#### Problem description

Code example in documentation for [enhancing performance](http://pandas-docs.github.io/pandas-docs-travis/user_guide/enhancingperf.html#using-ndarray) is erroneous. Shows intendation error instead of %prun timing.

#### Expected Output

Expected to see %prun timing.

**Comment by datapythonista** [comment]
This is already fixed in master, was taken care of in #28029

You can see the latest docs in: https://dev.pandas.io/user_guide/enhancingperf.html#using-ndarray

If you see anything wrong there, please let me know, and I'll reopen the issue.
