### ISSUE TITLE
comparison_with_sql document: adding a calculated column

### ISSUE THREAD

**Issue by DavidRosen** [pandas-dev/pandas#28162]
https://pandas-docs.github.io/pandas-docs-travis/getting_started/comparison/comparison_with_sql.html

In section "SELECT", the important use case of adding a calculated column is omitted.

I suggest adding something like the following:

select *, tip/total_bill as tip_rate from tips

pd.concat([tips, pd.Series(tips.tip/tips.total_bill, name='tip_rate')], axis=1)

**Comment by TomAugspurger** [comment]
Dev guide is at https://dev.pandas.io/development/contributing.html#

**Comment by DavidRosen** [comment]
Come to think of it, why do we even need .assign() ?  How about just:

`tips['tip_rate'] = tips['tip'] / tips['total_bill']`

BTW, this also has the advantage that the linter won't prohibit spaces around the "=" as it did when we used .assign() (because "=" was for a keyword argument).

**Comment by lucassa3** [comment]
Hi @TomAugspurger Tom, I just referenced this issue in a PR a while ago. I'm relatively new to contributing to open source projects, so I'd like you to review if this is what was proposed in this Issue.

Best,

Lucas

**Comment by TomAugspurger** [comment]
Hi @lucassa3. I think David submitted a PR but didn’t reference the issue. So we won’t need your PR for this issue. 

It looks like you made your PR against *your* master branch. In the future you should target pandas’ master branch. Let us know if you need help finding another issue.

**Comment by lucassa3** [comment]
Yes, I accidentally forgot to change merge target when opening the PR. I'll check other issues around, but thanks for the feedback Tom!

**Comment by TomAugspurger** [comment]
Closed by https://github.com/pandas-dev/pandas/pull/28182.
