### ISSUE TITLE
pd.to_datetime() does not respect exact format string ,when I use '%Y-%m-%d'

### ISSUE THREAD

**Issue by CrystalWindSnake** [pandas-dev/pandas#28193]
#### Code Sample, a copy-pastable example if possible

```python
pd.to_datetime('xx 2019-8-1 xxx',format='%Y-%m-%d',exact=False)
```
#### Problem description
ValueError: time data xx 2019-8-1 xxx doesn't match format specified

#### Expected Output
Timestamp('2019-08-01 00:00:00')

####
Normal when executing the following code：
```python
pd.to_datetime('xxa2019-8-1axxx',format='a%Y-%m-%da',exact=False)
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.0
numpy            : 1.16.2
pytz             : 2018.9
dateutil         : 2.8.0
pip              : 19.0.3
setuptools       : 40.8.0
Cython           : 0.29.6
pytest           : 4.3.1
hypothesis       : None
sphinx           : 1.8.5
blosc            : None
feather          : 0.4.0
xlsxwriter       : 1.1.5
lxml.etree       : 4.3.2
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10
IPython          : 7.4.0
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.2
matplotlib       : 3.0.3
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.6.1
pandas_gbq       : None
pyarrow          : 0.13.0
pytables         : None
s3fs             : None
scipy            : 1.2.1
sqlalchemy       : 1.3.1
tables           : 3.5.1
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.5

</details>

**Comment by wangxin1194** [comment]
You probably need to write format as 'xx %Y-%m-%d xxx'

**Comment by CrystalWindSnake** [comment]
> You probably need to write format as 'xx %Y-%m-%d xxx'

But I want to do fuzzy matching，so I set exact=False

**Comment by jreback** [comment]
under the hood this is doing a regex match which likely fails on the whitespace as it’s a special token

it might be possible to improve this if you want to look, though generallly would recommend using .str ops to clean the dates first instead as you have full control

**Comment by CrystalWindSnake** [comment]
> under the hood this is doing a regex match which likely fails on the whitespace as it’s a special token
> 
> it might be possible to improve this if you want to look, though generallly would recommend using .str ops to clean the dates first instead as you have full control

I got it, thank you for your reply.
