### ISSUE TITLE
Feature request: groupby on columns with overlapping column combinations

### ISSUE THREAD

**Issue by delica1** [pandas-dev/pandas#28190]
Currently I am not able to use groupby on columns to produce groupings that contain combinations of same columns. Let's say I have a dataframe with columns A, B , C and D. I would like to create groups that contain [A,B], [A,C] and [B,D]. 

One obvious way to implement this would be to allow as argument a dictionary of lists, where the keys are output labels and the lists are the column labels to be grouped. 

I am aware that currently grouping via dictionary works the opposite way, i.e. the key is the input label and the value is the output label, but at least to me this seems somewhat less useful than the reverse.

**Comment by delica1** [comment]
```
import pandas as pd
df = pd.DataFrame({'A':[1,2,3], 'B':[1,2,3], 'C':[1,2,3]})
g = {'A': 'SUM1','B': 'SUM1'}
df.groupby(g, axis=1).sum()
```

Above works as expected and creates a sum of A+B.

I would like to be able to be able to create another group that contains A+C and produces a SUM2, but I don't have a way of doing this with groupby,

```
g = {'A': 'SUM1','B': 'SUM1', 'A': 'SUM2','C': 'SUM2'}
df.groupby(g, axis=1).sum()
```
This of course cannot work since I am overwriting 'A', but if I could use a dictionary with output labels as keys (SUM1, SUM2) and input labels as a list, that would work.

So, in my example a syntax like this would work if implemented:
```
g = {'SUM1': ['A','B'], 'SUM2': ['A','C']}
df.groupby(g, axis=1).sum()
```

**Comment by jreback** [comment]
pls read the docs here: https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.25.0.html#groupby-aggregation-with-relabeling

grouping like this has no support at all

**Comment by delica1** [comment]
> pls read the docs here: https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.25.0.html#groupby-aggregation-with-relabeling
> 
> grouping like this has no support at all

I appreciate using dictionaries is deprecated but my request is not about using dictionaries, but about having any ability at all to have groups with overlapping columns.

**Comment by delica1** [comment]
@TomAugspurger perhaps I can try to make the example clearer but it's already quite minimal. 

This is to create a small dataframe with three columns A,B and C:

```
import pandas as pd
df = pd.DataFrame({'A':[1,2,3], 'B':[1,2,3], 'C':[1,2,3]})
```

My expected output using groupby would be to produce two series: SUM1 and SUM2.

I want the inputs for SUM1 to be columns A and B.
I want the inputs for SUM2 to be columns A and C.

My problem is that there is no combination of groupby arguments or a groupby function that I could write that can do this.

The reason why this is so, is because groupby does not provide any grouping mechanism that allows the same column (in this case A) to be included in 2 groups at the same time.

**Comment by TomAugspurger** [comment]
What's the repr of the expected output?

**Comment by delica1** [comment]
In this case both SUM1 and SUM2 should be: [2, 4, 6]

**Comment by TomAugspurger** [comment]
And the index and columns?

**Comment by delica1** [comment]
Sorry I am not sure how to post a well formatted table here, but let me try:

```
   SUM1  SUM2
0     2     2
1     4     4
2     6     6
```

**Comment by TomAugspurger** [comment]
@delica1 thanks. IIUC, this pretty fundamental changes the groupby model, so I think we'll pass. I'd recommend writing a small helper function that takes your mapping of outer names to groupings, apply each groupby operation, and then concatenate the results.

**Comment by jreback** [comment]
this is also easily accomplished by doing 2 independent groupbys and then concatting the result which imho is much more clear anyhow

**Comment by delica1** [comment]
@TomAugspurger the only way I can see how to do this right now would be to use a regular python loop and then within the loop use df.filter to capture the columns I want and create a new named series on each iteration. So if I was using a dictionary like a I suggested above it might work something like this:

```
g = {'SUM1': ['A','B'], 'SUM2': ['A','C']}
for in, out in g.items():
    res = pd.DataFrame()
    res[out] = df.filter(items=in, axis=‘columns’).sum()

```

But doing this over a few million series is very, very slow. 

I appreciate now that this would be a big change for the groupby method, but at this point I would be quite happy with any alternative suggestion that speeds this up. 

@jreback yes, this can be cleaner unless you are working with several million series, in this case working out that there are no overlaps withing groups becomes another challenge.

**Comment by TomAugspurger** [comment]
I'm not sure how it would be sped out, but if you figure something out you might post it here for others.

**Comment by delica1** [comment]
@TomAugspurger well, my only option at this point is taking all of my inputs and outputs, working out how many independent groupbys I need to create out of those and then doing that. That will work, but at that point I am creating some sort of mapping plan for groupby, that I feel should be a pandas internal thing, and I really did not want to be in that kind of business.

But again, I appreciate now this would be a fundamental change for groupby so is unlikely. At least not as a function of the groupby interface. 

Having said all of that, maybe a good time think about add another interface? :) 'agg_map' is not taken yet.

**Comment by TomAugspurger** [comment]
I'm not sure, but my initial reaction is that this belongs outside of
pandas.

**Comment by delica1** [comment]
Well, here's to hoping this may still change. It seems to me at least that aggregating with such overlaps would be a somewhat common scenario. Please let me know if I can help in any way.

**Comment by mroeschke** [comment]
Thanks for the suggestion, but it sounds like generally this type of grouping should belong outside of pandas or can be achieved with building on existing pandas operations. Closing.
