### ISSUE TITLE
dataframe's index is blank,

### ISSUE THREAD

**Issue by ChandlerBBT** [pandas-dev/pandas#28191]
![image](https://user-images.githubusercontent.com/17948924/63857928-26588d80-c9d7-11e9-9a4f-1454979d6723.png)

![image](https://user-images.githubusercontent.com/17948924/63857961-3a03f400-c9d7-11e9-8e41-efcd684293e1.png)

a daraframe have valida shape number, but its index is a blank list, which start from 0,end at 0. it is so weird!!!

**Comment by jreback** [comment]
pls show a reproducible example not images

**Comment by ChandlerBBT** [comment]
> pls show a reproducible example not images

are you saying offer related data? sorry, I can't, this is our company's data.
if you are referring to offer code, the image it is.
I encounter this weird situation last night, can not use for loop on a valid dataframe for its index is blank

however, even me can't reproduce this bug again on other toy dataframe....

btw, my pandas vesion is 0.23

**Comment by ChandlerBBT** [comment]
# 2.1 check not yet activate merchants
        in_time_stat_but_not_yet_act = in_time_stat[in_time_stat.F_activate_time.isnull()]
        in_time_stat_but_not_yet_act_list = in_time_stat_but_not_yet_act.F_merchant_id.tolist()  # 这个列表有可能是None对象
        
        if in_time_stat_but_not_yet_act_list is not None:
            # 2.1.1 check user's activate time
            in_time_stat_but_not_yet_act_now_act = df[df.F_merchant_id.isin(in_time_stat_but_not_yet_act_list)].groupby(
                "F_merchant_id", as_index=False).agg({"F_time": "min"}).rename(columns={"F_time": "F_activate_time"})
            in_time_stat_but_not_yet_act_now_act = in_time_stat_but_not_yet_act_now_act[[
                "F_merchant_id", "F_first_trade_time", "F_activate_time"]]
            # 2.1.2 check user's last trade time
            in_time_stat_but_not_yet_act_last_trade = all_last_trade[all_last_trade.F_merchant_id.isin(
                in_time_stat_but_not_yet_act_list)]
            # 2.1.3 merge
            in_time_stat_but_not_yet_act_act_last = pd.merge(in_time_stat_but_not_yet_act_now_act,
                                                             in_time_stat_but_not_yet_act_last_trade,
                                                             on="F_merchant_id", how="outer")
            # 2.1.4 update date into database
            in_time_stat_but_not_yet_act_act_last.index = range(len(in_time_stat_but_not_yet_act_act_last))
            # in_time_stat_but_not_yet_act_act_last.fillna("", inplace=True)
            for _ in range(len(in_time_stat_but_not_yet_act_act_last)):
                update_sql = """update hsy_merchants_time_stat set F_activate_time = '{}',
                    F_last_trade_time = '{}' where F_merchant_id = '{}'""".format(
                    in_time_stat_but_not_yet_act_act_last.loc[_, "F_activate_time"],
                    in_time_stat_but_not_yet_act_act_last.loc[_, "F_last_trade_time"],
                    in_time_stat_but_not_yet_act_act_last.loc[_, "F_merchant_id"])
                cur.execute(update_sql)
            db.commit()

**Comment by ChandlerBBT** [comment]
# 2.1 check not yet activate merchants
        in_time_stat_but_not_yet_act = in_time_stat[in_time_stat.F_activate_time.isnull()]
        in_time_stat_but_not_yet_act_list = in_time_stat_but_not_yet_act.F_merchant_id.tolist()  # this list might be None
        
        if in_time_stat_but_not_yet_act_list is not None:
            # 2.1.1 check user's activate time
            in_time_stat_but_not_yet_act_now_act = df[df.F_merchant_id.isin(in_time_stat_but_not_yet_act_list)].groupby(
                "F_merchant_id", as_index=False).agg({"F_time": "min"}).rename(columns={"F_time": "F_activate_time"})
            in_time_stat_but_not_yet_act_now_act = in_time_stat_but_not_yet_act_now_act[[
                "F_merchant_id", "F_first_trade_time", "F_activate_time"]]
            # 2.1.2 check user's last trade time
            in_time_stat_but_not_yet_act_last_trade = all_last_trade[all_last_trade.F_merchant_id.isin(
                in_time_stat_but_not_yet_act_list)]
            # 2.1.3 merge
            in_time_stat_but_not_yet_act_act_last = pd.merge(in_time_stat_but_not_yet_act_now_act,
                                                             in_time_stat_but_not_yet_act_last_trade,
                                                             on="F_merchant_id", how="outer")
            # 2.1.4 update date into database
            in_time_stat_but_not_yet_act_act_last.index = range(len(in_time_stat_but_not_yet_act_act_last))
            # in_time_stat_but_not_yet_act_act_last.fillna("", inplace=True)
            for _ in range(len(in_time_stat_but_not_yet_act_act_last)):
                update_sql = """update hsy_merchants_time_stat set F_activate_time = '{}',
                    F_last_trade_time = '{}' where F_merchant_id = '{}'""".format(
                    in_time_stat_but_not_yet_act_act_last.loc[_, "F_activate_time"],
                    in_time_stat_but_not_yet_act_act_last.loc[_, "F_last_trade_time"],
                    in_time_stat_but_not_yet_act_act_last.loc[_, "F_merchant_id"])
                cur.execute(update_sql)
            db.commit()

**Comment by ChandlerBBT** [comment]
> # 2.1 check not yet activate merchants
> ```
>     in_time_stat_but_not_yet_act = in_time_stat[in_time_stat.F_activate_time.isnull()]
>     in_time_stat_but_not_yet_act_list = in_time_stat_but_not_yet_act.F_merchant_id.tolist()  # this list might be None
>     
>     if in_time_stat_but_not_yet_act_list is not None:
>         # 2.1.1 check user's activate time
>         in_time_stat_but_not_yet_act_now_act = df[df.F_merchant_id.isin(in_time_stat_but_not_yet_act_list)].groupby(
>             "F_merchant_id", as_index=False).agg({"F_time": "min"}).rename(columns={"F_time": "F_activate_time"})
>         in_time_stat_but_not_yet_act_now_act = in_time_stat_but_not_yet_act_now_act[[
>             "F_merchant_id", "F_first_trade_time", "F_activate_time"]]
>         # 2.1.2 check user's last trade time
>         in_time_stat_but_not_yet_act_last_trade = all_last_trade[all_last_trade.F_merchant_id.isin(
>             in_time_stat_but_not_yet_act_list)]
>         # 2.1.3 merge
>         in_time_stat_but_not_yet_act_act_last = pd.merge(in_time_stat_but_not_yet_act_now_act,
>                                                          in_time_stat_but_not_yet_act_last_trade,
>                                                          on="F_merchant_id", how="outer")
>         # 2.1.4 update date into database
>         in_time_stat_but_not_yet_act_act_last.index = range(len(in_time_stat_but_not_yet_act_act_last))
>         # in_time_stat_but_not_yet_act_act_last.fillna("", inplace=True)
>         for _ in range(len(in_time_stat_but_not_yet_act_act_last)):
>             update_sql = """update hsy_merchants_time_stat set F_activate_time = '{}',
>                 F_last_trade_time = '{}' where F_merchant_id = '{}'""".format(
>                 in_time_stat_but_not_yet_act_act_last.loc[_, "F_activate_time"],
>                 in_time_stat_but_not_yet_act_act_last.loc[_, "F_last_trade_time"],
>                 in_time_stat_but_not_yet_act_act_last.loc[_, "F_merchant_id"])
>             cur.execute(update_sql)
>         db.commit()
> ```

this bug pop up in the line "        in_time_stat_but_not_yet_act_act_last.index = range(len(in_time_stat_but_not_yet_act_act_last))" , even I rebuild the DataFrame's index manually, still fail to iterate on it, saying the df have empty index !

**Comment by jreback** [comment]
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by Mlawrence95** [comment]
It's tough to follow but perhaps try df.reset_index(drop=True)

**Comment by ChandlerBBT** [comment]
> It's tough to follow but perhaps try df.reset_index(drop=True)

yep,that's my first try, but hard to believe this also fail.

I tried below ways:

1. reset_index()
2. reset_index(drop=True)
3. reindex()
4. index = range(len(df))

however, all fail on this particular dataframe.

**Comment by ChandlerBBT** [comment]
> We're looking at two different dataframes here. That may be the problem?

Gee... what a shame! I will try to re-go this situation again to see if bug will happen on same df. Frankly say, I am afraid it is my mistake...   

After all, I hv learned my lesson, don' put the object's name too long to distinguish

**Comment by TomAugspurger** [comment]
Let us know if you think there's a pandas bug and we'll reopen.
