### ISSUE TITLE
Localizing dates to a timezone with dls after 2038 does not work (2038 Problem)

### ISSUE THREAD

**Issue by kurt-rhee** [pandas-dev/pandas#28207]
#### Code Sample, a copy-pastable example if possible

```python
pandas version 0.24.2

dates = pd.date_range(start='1/1/2037 00:00:00', end='12/31/2038 23:00:00', freq='h')
test = pd.to_datetime(dates, infer_datetime_format=True)
test = test.tz_localize('Etc/GMT+8').tz_convert('America/Los_Angeles')

```
#### Problem description

[Current behavior correctly dls corrects years before 2038.  It is necessary for forecasting applications (and other applications) to have dls corrections after 2038]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: None.None

pandas: 0.24.2
pytest: None
pip: 19.0.3
setuptools: 40.8.0
Cython: None
numpy: 1.15.4
scipy: None
pyarrow: None
xarray: None
IPython: 7.3.0
sphinx: 1.8.5
patsy: None
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: 2.6.1
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by mroeschke** [comment]
We need a minimally reproducible example: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by kurt-rhee** [comment]
> We need a minimally reproducible example: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

Hey @mroeschke, apologies for that.  I have edited my question to include a minimally reproducible example as requested.  Please note that running the code snippet above results in all hours in 2038 and after remaining in UTC-8, while the dls correction works fine for years before 2038.

Thanks!

**Comment by Liam3851** [comment]
This is unrelated to pandas. I can reproduce with pure pytz and datetimes:

```python3
import pytz
z = pytz.timezone('America/Los_Angeles')
# indicates one-hour offset
z.dst(datetime.datetime(2037, 6, 30, 8, 0))
# indicates no tz-offset
z.dst(datetime.datetime(2038, 6, 30, 8, 0))
```

You might want to put in a feature request over at pytz if the predictions of far-future DST changes matter to you.

**Comment by kurt-rhee** [comment]
@Liam3851 

Ah I see, thank you for the help.  I will post over on pytz.
