### ISSUE TITLE
使用pivot_table传入values报错KeyError: 0.0

### ISSUE THREAD

**Issue by HecateSilly** [pandas-dev/pandas#28211]
#### Code Sample, a copy-pastable example if possible
#发现了一个问题：
位置pandas\core\reshape\pivot.py 58行
源代码：
    values_passed = values is not None
    if values_passed:
        if is_list_like(values):
            values_multi = True
            values = list(values)
        else:
            values_multi = False
            values = [values]

        # GH14938 Make sure value labels are in data
        for i in values:
            if i not in data:
                raise KeyError(i)

在经过测试：
import numpy as np
import pandas as pd

tmp_df = pd.DataFrame(np.zeros(shape=(5,5),dtype='int8'),columns=['A','B','C','D','E'])
print(tmp_df)
for i in tmp_df['A']:
    print(i in tmp_df,end=' ')
print()
for i in tmp_df['A']:
    print(i in tmp_df.values,end=' ')
   A  B  C  D  E
0  0  0  0  0  0
1  0  0  0  0  0
2  0  0  0  0  0
3  0  0  0  0  0
4  0  0  0  0  0
False False False False False 
True True True True True 
希望可以得到修改

**Comment by wj-c** [comment]
“i in tmp_df” roughly equals to "i in tmp_df.columns", which checks whether tmp_df contains a column NAMED "i".  It is completely different from "i in tmp_df.values" (or "i in tmp_df.to_numpy()").

In the example, "i" always equals to 0, which is not a column name of DataFrame tmp_df.

智障

**Comment by HecateSilly** [comment]
> “i in tmp_df” roughly equals to "i in tmp_df.columns", which checks whether tmp_df contains a column NAMED "i". It is completely different from "i in tmp_df.values" (or "i in tmp_df.to_numpy()").
> 
> In the example, "i" always equals to 0, which is not a column name of DataFrame tmp_df.
> 
> 智障



> “i in tmp_df” roughly equals to "i in tmp_df.columns", which checks whether tmp_df contains a column NAMED "i". It is completely different from "i in tmp_df.values" (or "i in tmp_df.to_numpy()").
> 
> In the example, "i" always equals to 0, which is not a column name of DataFrame tmp_df.
> 
> 智障

**Comment by HecateSilly** [comment]
thanks
