### ISSUE TITLE
I think I submitted a pull request to this effect a few months ago, but it looks like you are still using the old donation link from Flipcause. The new donation link to salsa is here: https://numfocus.salsalabs.org/donate-to-pandas

### ISSUE THREAD

**Issue by lisamartin72** [pandas-dev/pandas#28212]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

```
#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by TomAugspurger** [comment]
Hi @lisamartin72, can you point me to where you saw the old link? https://pandas.pydata.org/donate.html has the new one (I think).

**Comment by lisamartin72** [comment]
Hi Tom,

I am new to using GitHub! My husband is usually around to consult, but he
is out of town this week.

I looked at your repo because we were still getting a donation or two
coming in for pandas via Flipcause. When I went on GitHub to see if you
still had the old link up I saw what I screen shot below. You must have the
old link up somewhere because I think it was a new donation, not a
recurring one.

Please let me know if you have any other questions. I am happy to help.

Best,

Lisa Martin
[image: Screen Shot 2019-08-29 at 10.27.09 AM.png]

**Comment by TomAugspurger** [comment]
It looks like your screen shot didn't attack correctly, sorry.

I haven't found any references to flipcause here or in the repository for the website pandas.pydata.org. So Hopefully we've found them all.
