### ISSUE TITLE
I have a problem about upgrading my packages in pycharm

### ISSUE THREAD

**Issue by antarctiqueN** [pandas-dev/pandas#28214]
I am trying to upgrade the versus of BeautifulSoup4 from 4.6.0 to 4.8.0 and pip from 18.0 to 19.2.3 which are newest versions. 

So via the terminal, I used `python -m pip install -U bs4` and `pip install --upgrade pip`. The thing is these two packages are actually installed successfully, but the upgrading is failed. 

As the terminal showed, the old version is already installed in the specific location and cannot be simply uninstalled:

>Found existing installation: pip 18.0
    Not uninstalling pip at /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6, as it is in the standard library.
    Can't uninstall 'pip'. No files were found to uninstall.

>Found existing installation: beautifulsoup4 4.6.0
    Not uninstalling beautifulsoup4 at /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6, outside environment /Users/niejiaqi/PycharmProjects/URLDemo2/venv
    Can't uninstall 'beautifulsoup4'. No files were found to uninstall.

How can I update those packages?

**Comment by mroeschke** [comment]
Not sure how this is pandas related; nonetheless, please consult StackOverflow for usage questions.
