### ISSUE TITLE
Implement str.contains for Dataframes so it can be used on multiple columns at once

### ISSUE THREAD

**Issue by masangster** [pandas-dev/pandas#28222]
Hi all,

I would like to be able to utilise str.contains to return a boolean of all of the cells in a DataFrame that at least partially match a certain string. Currently this can only be applied for a single column at a time as it is only implemented for Series, and my searching has not found an elegant solution for this over multiple columns simultaneously.

Thanks!

**Comment by jreback** [comment]
just apply over the columns of interest and any/all

i am -1 on having these act on Dataframe

**Comment by TomAugspurger** [comment]
Also -1 here. I think the semantics about what to do with non-str columns and how to join together the output of `.str` ops that return a DataFrame would make this too confusing.

This would make for a nice cookbook entry, like "How do I perform string operations on multiple columns?"

**Comment by masangster** [comment]
Thanks all - reasoning understood. For now I am simply adding `astype(str)` in front of the `str.contains` to avoid issues with non-string columns, which I understand may not be easy to generalise/ provide expected behaviour for all use cases.
