### ISSUE TITLE
.to_csv in jupyter notebook giving "unexpected keyword argument 'tupleize_cols' " error

### ISSUE THREAD

**Issue by YvesJacquot** [pandas-dev/pandas#28234]
#### Code Sample
```
# df.to_csv('output_file.csv')
```

#### Problem description
In Jupyter notebook, the to_csv method does not work anymore since I upgraded pandas to version 0.25.1
It gives the following error message:
> TypeError: __init__() got an unexpected keyword argument 'tupleize_cols'

#### Output of ``pd.show_versions()``

<details>

commit           : None
python           : 3.6.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 17.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 0.25.1
numpy            : 1.17.1
pytz             : 2018.9
dateutil         : 2.6.1
pip              : 19.2.3
setuptools       : 41.1.0
Cython           : None
pytest           : 3.3.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.3.3
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10
IPython          : 6.2.1
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.3
matplotlib       : 3.0.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : 0.11.0
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.2.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
</details>

**Comment by WillAyd** [comment]
Can you post the full traceback?

**Comment by jreback** [comment]
https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.25.0.html#removal-of-prior-version-deprecations-changes

tupelize_cols has long been deprecated and was removed

**Comment by YvesJacquot** [comment]
Sure, here it is...

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-157-b8e1ffd17387> in <module>()
----> 1 df.to_csv('output_file.csv')

/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/generic.py in to_csv(self, path_or_buf, sep, na_rep, float_format, columns, header, index, index_label, mode, encoding, compression, quoting, quotechar, line_terminator, chunksize, tupleize_cols, date_format, doublequote, escapechar, decimal)
   3017             If buf is None, returns the resulting LateX format as a
   3018             string. Otherwise returns None.
-> 3019 
   3020         See Also
   3021         --------

TypeError: __init__() got an unexpected keyword argument 'tupleize_cols'
```

**Comment by YvesJacquot** [comment]
@jreback  
thanks for your reply, but how do I fix this? what is the "tupelize_cols" argument?

**Comment by jreback** [comment]
you need to remove the argument

**Comment by WillAyd** [comment]
It might be a problem with one of the third party libraries if you aren’t using it directly. If you search closed issues I think this was raised once or twice before and came back to third party versions

**Comment by YvesJacquot** [comment]
@jreback I do not have that argument in
@WillAyd Thanks. Yes I saw one mentioning a numpy upgrade, which I did, but it did not solve the issue

**Comment by WillAyd** [comment]
You don't have a problem calling that outside of a notebook right? Not sure what would be wrapping that function but seems to be doing so incorrectly. Was hoping the traceback would provide more insight but doesn't look like it, so maybe try upgrading jupyter if nothing else works.

Unfortunately not a pandas issue though, so might need to search StackOverflow or something else to see which library might be causing your issue

**Comment by YvesJacquot** [comment]
I upgraded jupyter notebook to the latest version (6.0.1.) and it solved the issue.
Thanks for you help!
