### ISSUE TITLE
to_record fails on aggregate DataFrame

### ISSUE THREAD

**Issue by liquidscorpio** [pandas-dev/pandas#28242]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd
import numpy as np

df = pd.DataFrame([{
    'uid': '1345a',
    'category': 'Automobile',
    'amount': 40050.12
}, {
    'uid': 'b7345',
    'category': 'Hovercraft',
    'amount':279215.00
}, {
    'uid': '0u1325',
    'category': 'Automobile',
    'amount': 124895.12
}])

agg_df = df.groupby(['category', 'uid']).agg({
    'category': 'first',
    'uid': 'first',
    'amount': np.sum
})

agg_df.to_records()
```
#### Problem description

The `to_records` call should output a proper data structure. Instead, it fails with the following stacktrace:

```python
ValueError                                Traceback (most recent call last)
<ipython-input-8-39fc977374b6> in <module>
     22 })
     23 
---> 24 agg_df.to_records()

~/Studio/Local/myapp/venv/lib/python3.7/site-packages/pandas/core/frame.py in to_records(self, index, convert_datetime64, column_dtypes, index_dtypes)
   1822                 raise ValueError(msg)
   1823 
-> 1824         return np.rec.fromarrays(arrays, dtype={"names": names, "formats": formats})
   1825 
   1826     @classmethod

~/Studio/Local/myapp/venv/lib/python3.7/site-packages/numpy/core/records.py in fromarrays(arrayList, dtype, shape, formats, names, titles, aligned, byteorder)
    616 
    617     if dtype is not None:
--> 618         descr = sb.dtype(dtype)
    619         _names = descr.names
    620     else:

ValueError: name already used as a name or title
```
However, `agg_df.to_dict(orient='records')` works returning a list of dicts. 

**Note**: Also fails on (along with the version in the details section below):
- pandas 0.24.2
- numpy 1.16.2 

#### Expected Output
A python list of dict with aggregated data.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-58-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB
LOCALE           : en_GB.utf8

pandas           : 0.25.1
numpy            : 1.17.1
pytz             : 2018.9
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : 0.29.7
pytest           : None
hypothesis       : None
sphinx           : 1.8.4
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.3.2
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.7.7 (dt dec pq3 ext lo64)
jinja2           : 2.10
IPython          : 7.3.0
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.2
matplotlib       : 3.0.3
numexpr          : None
odfpy            : None
openpyxl         : 2.5.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by vignesh96** [comment]
I think because the index is included in the data frame as the default, you are getting this issue. Fixed this by setting index=False in to_records() function. Let me know if this the desired solution.

**Comment by liquidscorpio** [comment]
Thanks, @vignesh96! Either of the options - `index=False` or renaming index columns work. 

Closing.
