### ISSUE TITLE
Fix PR06 errors in docstrings ('Parameter "{param_name}" type should use "{right_type}" instead of "{wrong_type}"')

### ISSUE THREAD

**Issue by danielplawrence** [pandas-dev/pandas#28253]
[link to original issue](https://github.com/pandas-dev/pandas/issues/27977 (27977))

The output of `python scripts/validate_docstrings.py --errors=PR06` returns 257 instances of 'Parameter "{param_name}" type should use "{right_type}" instead of "{wrong_type}'

Given the large number of cases, it probably makes sense to break them out by class:

- [x] pandas.Series
- [ ] pandas.Timestamp
- [ ] pandas.Timedelta
- [ ] pandas.Period
- [ ] pandas.arrays
- [ ] pandas.Categorical
- [ ] pandas.SparseArray
- [ ] pandas.read* (inc. all 'read' methods e.g. read_sql, read spss etc.)
- [ ] pandas.HDFStore
- [ ] pandas.io.stata
- [ ] pandas.core.resample
- [ ] pandas.testing
- [ ] pandas.api
- [ ] pandas.melt
- [ ] pandas.pivot
- [ ] pandas.pivot_table
- [ ] pandas.qcut
- [ ] pandas.merge_asof
- [ ] pandas.to_numeric
- [ ] pandas.to_datetime
- [ ] pandas.date_range
- [ ] pandas.bdate_range
- [ ] pandas.period_range
- [ ] pandas.timedelta_range
- [ ] pandas.infer_freq
- [ ] pandas.interval_range
- [ ] pandas.eval
- [ ] pandas.util
- [ ] pandas.Index
- [ ] pandas.CategoricalIndex
- [ ] pandas.IntervalIndex
- [ ] pandas.MultiIndex
- [ ] pandas.DatetimeIndex
- [ ] pandas.TimedeltaIndex
- [ ] pandas.PeriodIndex
- [ ] pandas.Grouper
- [ ] pandas.core
- [ ] pandas.io
- [ ] pandas.DataFrame

**Comment by danielplawrence** [comment]
I'll have a go at the first 10 here

**Comment by Kanter666** [comment]
I can join on this and take the second 10 (from pandas.core.resample up to pandas.to_datetime).

**Comment by danielplawrence** [comment]
Thanks Adam!

A lot of these should be straightforward, but I've noticed there are some cases where we will want to change validate_docstrings.py -- for example, it fails on parameter type 'basestring' because the validation is done with a simple 'in' test, and 'string' in 'basestring == True.

Additionally, the tests for validate_docstrings.py are not being executed as part of the main pytest target (not sure if this should be changed), so we need to run test_validate_docstrings.py explicitly with pytest to check any changes to the script are working properly.

**Comment by TomAugspurger** [comment]
> it fails on parameter type 'basestring' because the validation is done with a simple 'in' test, and 'string' in 'basestring == True.

Just FYI, we can remove all references to basestring. That's a Python 2 thing which we've removed.

**Comment by willpeppo** [comment]
take

**Comment by willpeppo** [comment]
The output of python `scripts/validate_docstrings.py --errors=PR06` returns  12 instances of 'Parameter "{param_name}" type should use "{right_type}" instead of "{wrong_type}' (4 in pandas.Timestamp and 8 in pandas.Timedelta.

**Comment by mroeschke** [comment]
Closing as https://github.com/pandas-dev/pandas/issues/28724 covers this specific case.
