### ISSUE TITLE
Add support for reading Stata .dta file format 119

### ISSUE THREAD

**Issue by chrisyeh96** [pandas-dev/pandas#28250]
Please add functionality to read format 119 `.dta` Stata files! See file format here: https://www.stata.com/help.cgi?dta#versions

Currently, even though Pandas can _write_ format 119 files (https://github.com/pandas-dev/pandas/blob/612d3b23da5b99f6c5642be574fb08713a45d7d1/pandas/io/stata.py#L2663), it seems unable to _read_ format 119 files (https://github.com/pandas-dev/pandas/blob/612d3b23da5b99f6c5642be574fb08713a45d7d1/pandas/io/stata.py#L49-L53).

**Comment by TomAugspurger** [comment]
Do we support writing 119? We raise when trying to use `version=119` from DataFrame.to_stata` cc @bashtage

**Comment by bashtage** [comment]
No support for 119.

**Comment by bashtage** [comment]
I don't think writing for 119 has been implemented either, unless there have been some commits I haven't seen.

**Comment by bashtage** [comment]
https://github.com/pandas-dev/pandas/blob/612d3b23da5b99f6c5642be574fb08713a45d7d1/pandas/io/stata.py#L2663

Is only a comment about the StrL formatting, which was forward compat.  The actual writer is not.

**Comment by TomAugspurger** [comment]
OK, that's my understanding too.

We'll keep this open as a general "support Stata 119" issue.

@chrisyeh96 are you interested in working on it? Even just sketching out what needs to be done would be helpful.

**Comment by chrisyeh96** [comment]
As much as I would love to contribute, unfortunately I won't have time for the next couple of months. I think it's probably better if someone else who actually has experience working with Stata file formats (I have zero experience on this matter) gives this a shot.

**Comment by TomAugspurger** [comment]
Certainly, but at this point you've expressed the most interest in this
issue :) It may not be a priority for any of the past contributors to the
stata code.
