### ISSUE TITLE
pandas.read_parquet cause OOM, it's a 200MB file, 600M rows.

### ISSUE THREAD

**Issue by cupen** [pandas-dev/pandas#28263]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

# query from db
datalist = ...      # 600M rows, 4 fields(string string string datetime) every row.
df = pd.from_dict(datalist)
df.to_parquet("test.pq")
df = pd.read_parquet("test.pq")  # OOM
```
#### Problem description
> df.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6741512 entries, 0 to 6741511
Data columns (total 5 columns):
index        int64
_id          object
wxOpenID     object
channel      object
createdAt    datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 257.2+ MB

It have 600M rows writed to disk(a parquet file).the file just 200MB.
then, I read it from the parquet file, it causes a OOM.

#### Expected Output
do not make OOM.

#### Output of ``pd.show_versions()``

<details>

 pd.show_versions()                                                                                                                                                                           

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-957.5.1.el7.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.17.1
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 40.6.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 2.6.3
pandas_gbq       : None
pyarrow          : 0.14.1
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

**Comment by TomAugspurger** [comment]
Do you think this is a pandas issue, or an issue with the underlying parquet engine (fastparquet or pyarrow?)

Can you paste the traceback from the OOM error?

**Comment by cupen** [comment]
I know this is probably a problem with parquet engine, but it's so obvious that I think there should be an `pandas-usage` issue to record it.  :) 
You can add a tag for this issue.    'usage problem' or 'RTFM'

I'll try to get the traceback then, before it killed by os.

**Comment by TomAugspurger** [comment]
OK, typically we only leave issues open that are well-defined and have a
concrete action we can take. In this case, it's not clear whether it's a
bug (in pandas or elsewhere) or a usage issue or something else. Please
post additional details when you can.

**Comment by jbrockmendel** [comment]
@cupen the `df.info()` output says you have about 6M rows, not 600M.  Is that referring to a different DataFrame?

How much memory is on your machine?

Do you get the same OOM if you only try to load a subset of the parquet file?  (loading only a subset of columns is my favorite feature)

**Comment by cupen** [comment]
@jbradish  Sorry, you are right, it's 6M rows.  My machine is 16GB, the OS was archlinux.

I don't know how to get the traceback from a process which killed by oom-killer, it has no coredump. But I am try to reduce the rows to 1M, and repreducing the problem.  
Yes, it's a problem about pyarrow, it used too many memory.

I made a little parquet file `test.pq`, 1M rows, 13MB file size. 
```
import pyarrow.parquet as pq
table = pq.read_table('test.pq')   # it used too many memory
```
The other engine `fastparquet` just works fine.

**Comment by cupen** [comment]
@jbrockmendel  Sorry, you are right, it's 6M rows.  My machine is 16GB, the OS was archlinux.

I don't know how to get the traceback from a process which killed by oom-killer, it has no coredump. But I am try to reduce the rows to 1M, and repreducing the problem.  
Yes, it's a problem about pyarrow, it used too many memory.

I made a little parquet file `test.pq`, 1M rows, 13MB file size. 
```
import pyarrow.parquet as pq
table = pq.read_table('test.pq')   # it used too many memory
```
The other engine `fastparquet` just works fine.

**Comment by cupen** [comment]
@TomAugspurger  @jbrockmendel  Thanks. It's ok now.  I'll create a issue for pyarrow.
