### ISSUE TITLE
pivot_table(..., values='a')  and  pivot_talbe(...)['a'] yield different output

### ISSUE THREAD

**Issue by xwhuaduo** [pandas-dev/pandas#28278]
#### Code Sample

```python
aaa = pd.pivot_table(data=human, index='patient_ID', columns='Hugo_Symbol', fill_value=0, values='RNA.alt.fra')
bbb = pd.pivot_table(data=human, index='patient_ID', columns='Hugo_Symbol', fill_value=0)['RNA.alt.fra']

print(aaa.shape)
>>> (39, 4553)
print(bbb.shape)
>>> (39, 4556)
```
#### Problem description

`pivot_table` with `values='a'` assigned works faster, but in my case, it drop off three columns. 

Any ideas why this is happenning?
Thanks!

**Comment by TomAugspurger** [comment]
@xwhuaduo I'm guessing you haven't gotten a reply becuase you haven't provided a reproducible example. http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

And is this a usage question or bug report? For usage questions, we recommend using stackoverflow.

**Comment by mroeschke** [comment]
Feel free to reopen when you can provide a fully reproducible example.
