### ISSUE TITLE
to_numeric(errors='ignore') doesn't work with leading zeros

### ISSUE THREAD

**Issue by amarvin** [pandas-dev/pandas#28271]
#### Code Sample, a copy-pastable example if possible

```python
s = pd.Series([1, 1.0, '1', '1.0', ' 1', ' 1.0', '01', '01.0'])
pd.to_numeric(s, errors='ignore')
# returns [1, 1, 1, 1.0, 1, 1.0, '01', '01.0']
# but expected [1, 1, 1, 1.0, 1, 1.0, 1, 1.0]
```
#### Problem description

The `to_numeric` function doesn't work as expected if the string contains leading zeros.

#### Expected Output

I would expect that `'01'` gets converted to `1`, just like in the leading whitespace case of `' 1'` converting to `1`.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.0.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.1
numpy            : 1.17.0
pytz             : 2018.5
dateutil         : 2.7.3
pip              : 18.1
setuptools       : 40.2.0
Cython           : 0.28.5
pytest           : 3.8.0
hypothesis       : None
sphinx           : 1.7.9
blosc            : None
feather          : None
xlsxwriter       : 1.1.0
lxml.etree       : 4.2.5
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.8.2 (dt dec pq3 ext lo64)
jinja2           : 2.10
IPython          : 6.5.0
pandas_datareader: None
bs4              : 4.6.3
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.2.5
matplotlib       : 2.2.3
numexpr          : 2.6.8
odfpy            : None
openpyxl         : 2.5.6
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.2.11
tables           : 3.4.4
xarray           : None
xlrd             : 1.1.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.0

</details>

**Comment by amarvin** [comment]
Note that
```python
pd.to_numeric(s, errors='coerce')
# returns [1, 1, 1, 1, 1, 1, 1, NaN]
```
which is also surprising.

**Comment by TomAugspurger** [comment]
Can you try on master? I don't recall this changing, but I see

```
In [4]: s = pd.Series([1, 1.0, '1', '1.0', ' 1', ' 1.0', '01', '01.0'])
   ...: pd.to_numeric(s, errors='coerce')
   ...:
   ...:
Out[4]:
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
5    1.0
6    1.0
7    1.0
dtype: float64

In [5]: s = pd.Series([1, 1.0, '1', '1.0', ' 1', ' 1.0', '01', '01.0'])
   ...: pd.to_numeric(s)
Out[5]:
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
5    1.0
6    1.0
7    1.0
dtype: float64

```
