### ISSUE TITLE
NDFrame.sum ignores min_count for object dtype

### ISSUE THREAD

**Issue by mbkupfer** [pandas-dev/pandas#28274]
#### Code Sample, a copy-pastable example if possible

```python
>>> index = pd.MultiIndex.from_product([['a'], ['foo', 'bar']])
>>> s = pd.Series([np.nan] * 2, index=index)
>>> s.astype('O').sum(level=1, min_count=1)
foo    0
bar    0
dtype: int64

```
#### Problem description

Using sum with a multiindex and dtype set to object will force all answers to 0, and not `nan` as is expected. This is confusing, since pandas automatically coerces np.nan when this isn't the case, see below.

```python
>>> s = pd.Series([np.nan])
>>> s.astype('O').sum(min_count=1)
nan

```

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.16.3
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.2.1
setuptools       : 41.0.1
Cython           : None
pytest           : 5.0.1
hypothesis       : None
sphinx           : 2.1.2
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.5.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.0
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.6
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
</details>

**Comment by TomAugspurger** [comment]
Thanks for the report. Interested in debugging it further? We can point you to the spot to look if you're interested.

**Comment by mbkupfer** [comment]
That sounds good, let me know. I'm also a bit swamped on a project, but I'll have time next week.

**Comment by jschendel** [comment]
Looks like this hits the following line of code as a fallback for `object` dtype and the `min_count` kwarg isn't being passed through:

https://github.com/pandas-dev/pandas/blob/bfff080275b4456b28d71f0c7b4ec9e678d4270c/pandas/core/groupby/groupby.py#L1378

Not as simple as just passing in `min_count` there though, as `np.sum` is the function being wrapped here, which doesn't accept `min_count` (and other functions are being wrapped that don't accept `min_count`):
https://github.com/pandas-dev/pandas/blob/bfff080275b4456b28d71f0c7b4ec9e678d4270c/pandas/core/groupby/groupby.py#L1420

Finally, note that the issue described also applies to `prod`, so a similar fix will need to be applied for that as well.

**Comment by TomAugspurger** [comment]
FWIW, I'm perfectly fine with this raising, saying that `min_count` isn't
supported for object dtype. Though I'm not sure how easy that is to do
either.

**Comment by mbkupfer** [comment]
@jschendel thanks for sharing. I'll probably set a trace and walk through the source, but it would still help if you could give some background on what is going on in the `groupby_function` and how we got there. With a monolithic library like pandas, orienting oneself could take a while.

Another option, which is my current solution, is casting using `astype`. This looks and feels clunky though. Would it be possible to simply build this type of casting into the backend? For instance, add a check if all items in series are NaN and if so, cast to float.

**Comment by TomAugspurger** [comment]
I don't think we would want to cast implicitly.

**Comment by mroeschke** [comment]
As levels has been deprecated, the groupby version work as expected and I believe we have tests for this behavior already. Therefore closing

```
In [3]: s.astype("O").groupby(level=1).sum(min_count=1)
Out[3]:
bar    NaN
foo    NaN
dtype: object
```
