### ISSUE TITLE
Issue with pandas delimiter

### ISSUE THREAD

**Issue by melissabarnett** [pandas-dev/pandas#28270]
#### Code Sample, a copy-pastable example if possible

```python
from census import Census
import pandas as pd
from sqlalchemy import create_engine
import csv
import sys


filename = 'C:/Users/APIlist2.csv'
with open(filename) as f:
    reader = csv.reader(f)

    try:
        for row in reader:
            print(row)
    except csv.Error as e:
        sys.exit('file {}, line {}: {}'.format(filename, reader.line_num, e))


def getdata(mylist, tablename, schema):
    #  Create db engine#  #       
    engine = create_engine('postgresql://blahblah/melissa', convert_unicode=True)
    # Census parameters
    # state_fips = '*'
    state_fips = [str(i).zfill(2) for i in range(1, 56)]
    county_fips = '*'
    tract = '*'
    c = Census('key', year=2017, session=None)  # replace ca.... with your api key from census
    #  print(state_fips)
    # Extract data
    for s in state_fips:
        x = c.acs5.state_county_tract(mylist, s, county_fips, tract)  # mylist is a list of census variable names
        df = pd.DataFrame(x)  # convert data to data frame
        df.to_sql(tablename, engine, schema=schema, if_exists='append')


def main():
    # mylist = ['B01001_001E']
    # above B01001 is the table is required by the Python census library;001 is the variable in the table; and E =estimate.
    # two lines below will read from a CSV file. variable names must be stored in a column called Code
    df = pd.read_csv('C:/Users/APIlist2.csv', header=0, encoding='unicode_escape', delimiter=',', lineterminator='\n')
    mylist = df['Code'].values.tolist()
    tablename = '2017acs5b'
    getdata(mylist, tablename, 'census')


main()


```
#### Problem description
I am reading from column 'Code' and the line with more than one variable is not returning a delimiter with ',' instead each line is one variable therefore the variable is """"census.core.CensusException: error: error: unknown variable ''""""
[['Code', 'Description']
[**'C24060_003E'**, 'Administrative n emergency services']
[**'B99171_003E, B01003_001E'**, 'Percent living in poverty']
[**'B26103_005E, B01003_001E'**, 'Per capita residents in nursing homes,']
[**'B26103_005E**', 'Number of people living in group quarters']
[**'B26001_001E, B09001_001E'**, 'Percent population living group quarters']
['B25121_077E, B25122_001E', 'Percent of households earning more than 75000, ']
['B25032_013E, B00002_001E', 'Percent renter-occupied housing units']
['B25024_010E, B00002_001E', 'Percent of housing units that are mobile homes, ']
['B25024_007E, B25024_008E, B25024_009E, B25001_001E', 'Percent of housing units with 10 or more units']
['B25024_007E, B25024_008E, B25024_009E', 'Number of housing units with 10 or more units']
['B25003_003E, B00002_001E', 'Percent of renter-occupied housing units']]

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Expected Output
['Code', 'Description']
['C24060_003E', 'Administrative n emergency services']
['B99171_003E', 'B01003_001E', 'Percent living in poverty']
['B26103_005E', 'B01003_001E', 'Per capita residents in nursing homes,']
['B26103_005E', 'Number of people living in group quarters']
['B26001_001E', 'B09001_001E', 'Percent population living group quarters']
['B25121_077E', 'B25122_001E', 'Percent of households earning more than 75000, ']
['B25032_013E', 'B00002_001E', 'Percent renter-occupied housing units']
['B25024_010E', 'B00002_001E', 'Percent of housing units that are mobile homes, ']
['B25024_007E', 'B25024_008E', 'B25024_009E', 'B25001_001E', 'Percent of housing units with 10 or more units']
['B25024_007E', 'B25024_008E', 'B25024_009E', 'Number of housing units with 10 or more units']
['B25003_003E', 'B00002_001E', 'Percent of renter-occupied housing units']
#######I need to have a delimiter after every comma

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None
pandas           : 0.25.1
numpy            : 1.17.1
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.0.3
setuptools       : 40.8.0

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None
pandas           : 0.25.1
numpy            : 1.17.1
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.0.3
setuptools       : 40.8.0

**Comment by TomAugspurger** [comment]
Can you create a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by melissabarnett** [comment]
@TomAugspurger 
def main():
    

    df = pd.read_csv('~
[APIlist2 (1).xlsx](https://github.com/pandas-dev/pandas/files/3570977/APIlist2.1.xlsx)
[APIlist2 (1).xlsx](https://github.com/pandas-dev/pandas/files/3570979/APIlist2.1.xlsx)

/Documents/APIlist2.csv', header=0, encoding='unicode_escape', delimiter=',', lineterminator='\n')
    mylist = df['Code'].values.tolist()
    tablename = '2017acs5b'
    getdata(mylist, tablename, 'census')


main()

**Comment by TomAugspurger** [comment]
@melissabarnett a minimal example *probably* doesn't need the actual data your using :) Ideally it could be reproduced with data that is similar to yours, but small enough to demonstrate the essence of the problem.

Do you think there's a bug in pandas? If so, what do you think it is?

**Comment by melissabarnett** [comment]
import pandas as pd
df = pd.DataFrame({'Code':  ['API variable, API variable',\n'API variable']}), header='Code' , encoding='unicode_escape', delimiter=',', lineterminator='\n' ) <---- this line produces the error

**Comment by TomAugspurger** [comment]
Sorry, do you mean `pd.read_csv` rather than `pd.DataFrame` in your example here? https://github.com/pandas-dev/pandas/issues/28270#issuecomment-527598627

**Comment by melissabarnett** [comment]
@TomAugspurger  yes was following the link you had provided

**Comment by melissabarnett** [comment]
delimiter=',' does not work 
lineterminator='\n' does not work

**Comment by mroeschke** [comment]
Feel free to reopen when you can provide a copy pasteable example of the issue you are seeing.
