### ISSUE TITLE
Index.drop - add inplace option

### ISSUE THREAD

**Issue by eladtann** [pandas-dev/pandas#28284]
I have a Pandas.Index object which i want to delete some of the indices stored in it.
Since currently inplace=True is not available, i am forced to declare a new variable to hold the result which seems cumbersome.

currently i need to write:
#drop all columns with only 1 unique value.
nunique=df.apply(pd.Series.nunique)
cols_to_delete=nunique[nunique == 1].index
#do not delete column named 'label' even if it has only 1 unique value
cols_to_delete=cols_to_delete.drop('label')
df.drop(cols_to_delete, axis=1,inplace=True)

desired syntax:
cols_to_delete.drop('label', inplace=True)

instead of:
cols_to_delete=cols_to_delete.drop('label')

</details>

**Comment by TomAugspurger** [comment]
Indexes are immutable, so I don't think an `inplace` option is appropriate.
It gives the impression that the operation is done without copy.

**Comment by eladtann** [comment]
sorry, i missed the immutable wording in the documentation.
i will close the issue

thanks for your quick reply
