### ISSUE TITLE
MultiIndex.set_levels() unexpected behaviour

### ISSUE THREAD

**Issue by pepicello** [pandas-dev/pandas#28295]
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.rand(3, 3), columns=pd.MultiIndex.from_tuples([(1, 2), (1, 4), (5, 6)]))
df.columns = df.columns.set_levels([1, 2, 3], level=0)
```

Output:
```python
          1                   2
          2         4         6
0  0.729667  0.816939  0.763848
1  0.534183  0.571790  0.368467
2  0.983884  0.277658  0.256763
```

#### Problem description

Slightly different setup of #28294, but different issue. Here a level in a MultiIndex dataframe has duplicates to start with and a level with unique values is set afterwards, but the values are incorrect. It seems to work fine if the starting dataframe has unique level values.

#### Expected Output

```python
          1         2         3
          2         4         6
0  0.729667  0.816939  0.763848
1  0.534183  0.571790  0.368467
2  0.983884  0.277658  0.256763
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.1
numpy            : 1.16.4
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.2
setuptools       : 41.0.1
Cython           : 0.29.13
pytest           : 5.1.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : None
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.3.7
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : 1.1.8

</details>

**Comment by toobaz** [comment]
See https://github.com/pandas-dev/pandas/issues/28294#issuecomment-528456052
