### ISSUE TITLE
df.style.highlight_max() crashes if DataFrame is empty, but has some metadata

### ISSUE THREAD

**Issue by 0anton** [pandas-dev/pandas#28292]
#### Code Sample, a copy-pastable example if possible

```python
print(df.columns)
Index([], dtype='object', name='MONTH')
df.style.highlight_max(axis=1).format("{:.0f}")
```
#### Problem description

Pandas crashes with the trace shown below, when styler applied to an empty dataframe, which contains some meta-data. Expected output - empty output without crash.

```
IndexError                                Traceback (most recent call last)
c:\cygwin64\home\antongolubev\.venv\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

c:\cygwin64\home\antongolubev\.venv\lib\site-packages\pandas\io\formats\style.py in _repr_html_(self)
    162         Hooks into Jupyter notebook rich display system.
    163         """
--> 164         return self.render()
    165 
    166     @Appender(

c:\cygwin64\home\antongolubev\.venv\lib\site-packages\pandas\io\formats\style.py in render(self, **kwargs)
    518         self._compute()
    519         # TODO: namespace all the pandas keys
--> 520         d = self._translate()
    521         # filter out empty styles, every cell will have a class
    522         # but the list of props may just be [['', '']].

c:\cygwin64\home\antongolubev\.venv\lib\site-packages\pandas\io\formats\style.py in _translate(self)
    331             index_header_row.extend(
    332                 [{"type": "th", "value": BLANK_VALUE, "class": " ".join([BLANK_CLASS])}]
--> 333                 * (len(clabels[0]) - len(hidden_columns))
    334             )
    335 

IndexError: list index out of range
```
#### Expected Output

Expected empty output (no exception), like it is correctly happenes with freshly initialized dataframe.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_US.utf8
LOCALE           : None.None

pandas           : 0.25.1
numpy            : 1.16.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.1.1
setuptools       : 40.8.0
Cython           : None
pytest           : 5.0.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.3.4
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.6.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.4
matplotlib       : 3.1.0
numexpr          : None
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.0
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by WillAyd** [comment]
Can you provide a self-contained code example? With what you have `df` is not defined

**Comment by 0anton** [comment]
df came out as a result of complex processing. I cannot unfortunately recreate it. I can only say that it was an empty dataset (no rows) with this special index (see above). You can see the empty brackets in its definition. Was that an index column w/o name? Feel free to close if it is not important. I just thought that Styler shall now fail on empty dataset.

**Comment by TomAugspurger** [comment]
@0anton does the issue reproduce with something like the following?

```python
df = pd.DataFrame()
df.style.highlight_max(axis=1).format("{:.0f}")
```

That's what we mean by reproducible.

**Comment by 0anton** [comment]
Hi Tom,

Identical index metadata indeed can be rebuild with:

````python
df = pd.DataFrame()
df.index.name = 'MONTH'
df.index
Index([], dtype='object', name='MONTH')
```
But it does not reproduce the problem. It was probably something specific in the metadata of the DataFrame itself, which caused the highlight_max() to fail. I've to admit that we've probably fail to reproduce the issue. I should have pickled the object instantly for the repro. I'll do it next time I see this crash. My hope was that looking on stack (see above) the code owner will immediately know what was happened. Probably some check is missing in highlight_max() so it starts working on empty dataset.

If you wish we can close it as not reproduceable. I think it is still a real, but a minor issue. Practically, you are a caller can always check if the DataFrame is empty, before applying the style (what was my workaround).

**Comment by TomAugspurger** [comment]
OK, we'll close this for now but if you are able to reproduce it then we'll certainly reopen and look into a fix.
