### ISSUE TITLE
Different behavior of read_csv on Windows with Anaconda and Ubuntu 18

### ISSUE THREAD

**Issue by jumpingfella** [pandas-dev/pandas#28293]
Hello, 

I'm experiencing different behavior of the following script:
https://stackoverflow.com/questions/57791115/forecast-produced-by-gluon-ts-example-is-around-0

on Windows with Anaconda and on Ubuntu 18. It works as expected on Windows, but doesn't on Ubuntu 18 (produces plot around 0)

This seems to have something to do with `df = pd.read_csv(url, header=0, index_col=0)`

**Comment by TomAugspurger** [comment]
Can you make a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by jbrockmendel** [comment]
@jumpingfella we'd like to help, but need you to provide some more information.  can you take a look at the link Tom posted

**Comment by WillAyd** [comment]
Closing for lack of info, but certainly can reopen if provided
