### ISSUE TITLE
DataFrame.corr(method="kendall") calculation is slow

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#28329]
```python
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randn(1000, 300))

df.corr(method="kendall")
# 21.6 s ± 686 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

`DataFrame.corr(method="kendall")` doesn't scale particularly well, perhaps because it's the only named correlation method that isn't Cythonized at the moment (we just call `kendalltau` from `scipy` repeatedly in a Python for loop: https://github.com/pandas-dev/pandas/blob/master/pandas/core/frame.py#L7454).  It may be worthwhile to try to implement something more efficient within `_libs/algos.pyx`.

Relevant discussion: https://github.com/pandas-dev/pandas/pull/28151

**Comment by spindriftur** [comment]
Working on it 😃

**Comment by lithomas1** [comment]
take

**Comment by Alvaro-Kothe** [comment]
Since #39132 was reverted, this should be reopened.
