### ISSUE TITLE
read_json default date parsing behavior is unexpected

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#28325]
Generally the `pandas` readers (e.g., `read_csv`, `read_table`, `read_excel`) do not parse dates by default, so users might be surprised that `read_json` _will_ try to parse dates if they don't specify otherwise.  I would expect `read_json` to behave the same as the other IO functions in this regard.

**Comment by WillAyd** [comment]
Can you provide code samples to illustrate?

**Comment by dsaxton** [comment]
```python
import io
import pandas as pd

json_str = io.StringIO('{"date": ["2018/01/01", "2018/06/01"]}')
df = pd.read_json(json_str)
df.dtypes
# date    datetime64[ns]
# dtype: object

csv_str = io.StringIO('date\n2018/01/01\n2018/06/01')
df = pd.read_csv(csv_str)
df.dtypes
# date    object
# dtype: object
```

It's admittedly a little nitpicky, but for consistency's sake (and to avoid confusion for those used to the behavior of the other IO functions) I think you'd either want to always parse or always not parse by default (the latter seems safer and is already the convention for the other readers) rather than making an exception for `read_json`.

**Comment by jreback** [comment]
JSON is a well define format and it is very convenient to do this; not sure why consistency with csv matters at all

**Comment by dsaxton** [comment]
I guess it isn't so much consistency with `read_csv` but the fact that date parsing can be a little dubious sometimes:
```python
import io
import pandas as pd

json_str = io.StringIO('{"date": ["06/01/2018", "2018"]}')
df = pd.read_json(json_str)
df
# date
# 0	2018-06-01
# 1	2018-01-01
```
How does `read_json` know that the first date is June 1st and not January 6th, and should `"2018"` necessarily become January 1st of that year?  I'm not sure if you'd want this behavior to happen silently and automatically.

**Comment by WillAyd** [comment]
While not part of the spec I think JSON more typically represents dates as ISO, which could justify why the first date is June 01 and not January 06. I don't think Excel / CSV have as much of a pseudo-standard when it comes to date parsing

So I'd say generally I'm indifferent to any changes here. I don't necessarily see a problem but if you have a concrete proposal and PR I think could be considered

**Comment by dsaxton** [comment]
If there's a reasonable expectation that dates in JSON will tend to be well-formed, I guess it doesn't matter too much.  Thanks for the feedback.
