### ISSUE TITLE
`pivot_table` with `margins=True` shows `NaN` with `Period` columns

### ISSUE THREAD

**Issue by lucatrv** [pandas-dev/pandas#28323]
The following code reproduces the issue:

```python
import pandas as pd

df = pd.DataFrame(
    {
        "a": [1, 1, 2, 2],
        "b": [
            pd.Period("2019Q1"),
            pd.Period("2019Q2"),
            pd.Period("2019Q1"),
            pd.Period("2019Q2"),
        ],
        "x": 1.0,
    }
)

df.pivot_table(index="a", columns="b", values="x", margins=True)
```

Output:

```
b 	2019Q1 	2019Q2 	All
a 			
1 	1.0 	1.0 	1.0
2 	1.0 	1.0 	1.0
All	NaN 	NaN 	1.0
```
Expected output:

```
b 	2019Q1 	2019Q2 	All
a 			
1 	1.0 	1.0 	1.0
2 	1.0 	1.0 	1.0
All	1.0 	1.0 	1.0
```

**Comment by WillAyd** [comment]
Thanks for the note. If you'd like to investigate and submit a PR would certainly welcome that

**Comment by christopherzimmerman** [comment]
Issue looks to be [here](https://github.com/pandas-dev/pandas/blob/master/pandas/core/reshape/pivot.py#L241) in `add_margins`.  For this example, the index of `row_margin` retains the `Period` dtype, while the columns of `result` coerce to strings, which results in a bad reindex.
