### ISSUE TITLE
numbers automatically turn into floats

### ISSUE THREAD

**Issue by codeman101** [pandas-dev/pandas#28335]
#### Code Sample, a copy-pastable example if possible

```python
no code to show it's just the behavior of the csv_read method. 

```
#### Problem description
If there's a dataframe that has a bunch of ints but a blank in between for example

> 1
> 2
> 3
> 
> 4

pandas will turn it into 

> 1.0
> 2.0
> 3.0
> 
> 4.0

I may be a little off on remembering the exact decimal (it might be 1.1 but you get the point)

**Comment by WillAyd** [comment]
By default `nan` values must be expressed in a float array (this behavior matches numpy). You can try specifying `dtype="Int64" to get an int array that can also hold NA values

**Comment by codeman101** [comment]
@WillAyd Bet it was originally an int array that was converted to a float array. Are you trying to imply that nan values can only exist in a float array not int array because of how numpy works? If so, I'll raise the issue on the numpy github because there's no reason for that behavior to be intended.

**Comment by jreback** [comment]
@codeman101 you should read this: https://pandas.pydata.org/pandas-docs/stable/user_guide/gotchas.html#nan-integer-na-values-and-na-type-promotions
