### ISSUE TITLE
Feature request: extend `pandas.DataFrame.replace`

### ISSUE THREAD

**Issue by lucatrv** [pandas-dev/pandas#28332]
The following code examples explain this feature request.

The following code works:
```python
df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
df.rename(columns=str.lower)
```
however the following ones do not work:
```python
df.rename(columns=str.upper.str.lower)
```
```python
df.rename(columns=str.upper().str.lower())
```
```python
df.rename(columns=str.strip())
```
```python
df.rename(columns=str.replace("A", "C"))
```

**Comment by grge** [comment]
In the first (working) example, you are correctly passing in a callable to `columns`. To make your other examples work, just wrap the transformation in a function:

```python
df.rename(columns=lambda x: x.replace("A", "C"))
```

**Comment by lucatrv** [comment]
Yes I agree, but the feature request is to have that happen automatically, because it would be more convenient to just write:
```python
df.rename(columns=str.replace("A", "C"))
```

**Comment by WillAyd** [comment]
What you are asking for unfortunately doesn't work as the expression would get evaluated immediately. This is just a *limitation* of the Python language

**Comment by lucatrv** [comment]
I see. Would it be possible to use string expressions, similarly to `pandas.DataFrame.query`, for instance:

```python
df.rename(columns="str.strip().str.lower().str.replace(' ', '_')")
```
This would be syntactic sugar for [method chaining](https://www.dataschool.io/future-of-pandas/#methodchaining), for instance:

```python
df = (
    pd.read_excel("file.xlsx")
    .rename("str.strip().str.lower().str.replace(' ', '_')", axis="columns")
    .query("a.str.startswith('1') | a.str.startswith('2')")
)
```

**Comment by jreback** [comment]
-1 on using any string expressions; they are not discoverable, not syntactic and generally a bad idea (.query included)

**Comment by lucatrv** [comment]
IMHO uniformity in SW design is very important, so either string expressions are removed also from `query`, which would require to write something like:
```python
df.query(lambda df: df.a.str.startswith('1') | df.a.str.startswith('2'))
```
or otherwise they are allowed for `rename` too. Mixed behavior is confusing.

**Comment by TomAugspurger** [comment]
I don't think that'd be a good direction for the library. Thanks though @lucatrv.
