### ISSUE TITLE
"No such keys(s): 'display.html.border'"

### ISSUE THREAD

**Issue by fengshenme** [pandas-dev/pandas#28348]
Ndarray was converted to DataFrame times incorrectly, python3.7 was used, python3.6 was not reported until rolled back, and centos7 system was used
将ndarray转为DataFrame时报错了"No such keys(s): 'display.html.border'",使用的是python3.7,
回滚python3.6才没报错,用的centos7

**Comment by TomAugspurger** [comment]
Can you provide more information? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by fengshenme** [comment]
It is a waste of time to repeat this problem, so submit this problem to increase the weight. When this problem encounters more, please revise it.
It should be a python version change, just go back to the original version, and wait for the next version to be good again
复现这个问题太浪费时间了,提交这个问题增加权重,等到这个问题碰到多了,那麻烦在修改下,
应该是python版本变动,退回原来版本就好,等下下个版本又好了

**Comment by jreback** [comment]
@fengshenme that is not a
helpful comment

pls
revise the top section with a
full and complete example

**Comment by AndyMac541** [comment]
Just a quick comment that I got this error while using Jupyter. 
Python: 3.7.4
ipython: 7.8.0  

Loaded a df in via psycopg2, and then ```display(my_loaded_df)``` caused the error. It was solved by starting a new Jupyter session, which means I sadly can't reproduce.

For if others run into the error under similar circumstances.

**Comment by nourani** [comment]
I also encountered this error in Jupyter after upgrading pandas in the background. Restarting the jupyter alleviates this error. It must have something to do with the module being loaded by jupyter while the version on the disk being changed.
