### ISSUE TITLE
pandas.DataFrame.boxplot(by="class", ...) doesn't plot correctly

### ISSUE THREAD

**Issue by yuriikoval1997** [pandas-dev/pandas#28365]
#### Problem description
**pandas=0.24.2**
I uploaded the jupyter notebook file on [my GitHub account](https://github.com/yuriikoval1997/pandas0.24.2-has-a-problem-with-cyrillic/blob/master/pandas%20bugs.ipynb), so here I will be short.
For some reason, pandas.DataFrame.boxplot(by="class") method doesn't work correctly with Cyrillic letters in the table.

```python
for col in list(dataSetCyrillic.columns[:-1]):
    fig, ax = pyplot.subplots(figsize=(6, 6))
    dataSetCyrillic.boxplot(column=[col], 
                        by="class", 
                        ax=ax, 
                        widths=0.5)
    tmp = map(lambda x: x.replace(" ", "\n", 1), dataSetCyrillic["class"].unique())
    ax.set_xticklabels(tmp, fontsize="20")
    ax.set_yticklabels(ax.get_yticks(), fontsize="xx-large")
    ax.set_title(label=col, fontsize="xx-large", fontstyle="oblique", fontweight="bold")
    pyplot.xlabel("")
    pyplot.suptitle("")
    fig.tight_layout()
```

**Comment by TomAugspurger** [comment]
Do you have a reproducible example? Ideally with the equivalent Matplotlib code that plots things correctly?

**Comment by yuriikoval1997** [comment]
I uploaded the code on my GitHub account - [jupyter notebook file](https://github.com/yuriikoval1997/pandas0.24.2-has-a-problem-with-cyrillic/blob/master/pandas%20bugs.ipynb). Did you try to run it?

**Comment by TomAugspurger** [comment]
Can you inline the small example here? We need to be able to check whether the issue is fixed, even if that repo goes away.

**Comment by yuriikoval1997** [comment]
I don't have Matplotlib code for those plots. If it helps, I will attach the code that uses seaborn and builds works properly.
```python
for col in list(dataSetCyrillic.columns[:-1]):
    fig, ax = pyplot.subplots(figsize=(6, 6))
    seaborn.set(style="whitegrid")
    seaborn.boxplot(x="class", y=col, data=dataSetCyrillic, width=0.4)
    tmp = map(lambda x: x.replace(" ", "\n", 1), dataSetCyrillic["class"].unique())
    ax.set_xticklabels(tmp, fontsize="20")
    ax.set_yticklabels(ax.get_yticks(), fontsize="xx-large")
    ax.set_title(label=col, fontsize="xx-large", fontstyle="oblique", fontweight="bold")
    ax.set_xlabel("")
    ax.set_ylabel("")
    fig.suptitle("")
    fig.tight_layout()
```
Also, I could attach some pickle files and images to this comment, but I don't think it is possible.

**Comment by TomAugspurger** [comment]
Just FYI, this will be a pretty low priority until we get a reproducible example in the issue that follows the issue template.

**Comment by mroeschke** [comment]
We're happy to reopen this issue when we can validate the issue with a reproducible example
