### ISSUE TITLE
tm.makeObjectSeries returns a Series with dtype="datetime64[ns]"

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#28378]
```python-traceback
>>> import pandas.util.testing as tm
>>> tm.makeObjectSeries()
...
t1Q4jcW3nW   2000-02-09
ElZCr3WTz2   2000-02-10
p43Nqg7u4D   2000-02-11
dtype: datetime64[ns]
```

@jbrockmendel and I were both surprised that calling `makeObjectSeries` returns a Series with a datetime dtype. I think it would be more logical for this function to actually return an object dtype Series

**Comment by WillAyd** [comment]
xref https://github.com/pandas-dev/pandas/pull/27838/files#r322964878

**Comment by jmg7173** [comment]
Is it okay to change filling data as `datetime64[ns]` to `String` with `dtype: object`?

**Comment by jbrockmendel** [comment]
> Is it okay to change filling data as datetime64[ns] to String with dtype: object?

Probably, yes.  The one thing I want to double-check is that we aren't losing coverage for cases where we actually _do_ want a datetime64 Series, which I think might be the case in the arithmetic test.

@WillAyd thoughts on how to track this down more generally?  grepping shows only 11 usages of makeObjectSeries, but some of those are in fixtures.

**Comment by jmg7173** [comment]
As I searched, there is no usecase that `objectSeries` used just for `datetime` excluding arithmetic test.

I searched it including `object_series` fixture and instance of `TestData`(`TestData.objSeries`).
I hope I found everything :)

**Comment by WillAyd** [comment]
> @WillAyd thoughts on how to track this down more generally? grepping shows only 11 usages of makeObjectSeries, but some of those are in fixtures.

Yea I think @jmg7173 if you can search for the fixture where this is used and check that as well would be helpful.

Mostly could just change and see what breaks though. The naming of this obviously means the intent is to deal with object data, so I don't think should break too much actually making this return an object dtype

**Comment by jmg7173** [comment]
>  Yea I think @jmg7173 if you can search for the fixture where this is used and check that as well would be helpful.

Here's list where this is used:
* As function `makeObjectSeries` itself:
```
pandas/tests/arithmetic/test_object.py L144 test_objarr_add_invalid
pandas/tests/dtypes/test_missing.py L94-101 test_isna_isnull
pandas/tests/dtypes/test_missing.py L51-59 test_notna_notnull
pandas/tests/generic/test_generic.py L703-704 test_squeeze
pandas/tests/generic/test_generic.py L746 test_transpose
pandas/tests/generic/test_generic.py L768 test_take
pandas/tests/io/test_packers.py L459 test_basic at TestSeries (defined as self.d["object"])
pandas/tests/io/json/test_pandas.py L885-890 test_series_from_json_to_json at TestPandasContainer (defined as self.objSeries)
```

* As return of method `objSeries` at class `TestData`:
```
Defined:
pandas/tests/series/common.py  L23 as method objSeries of class TestData
(TestData fixture defined at pandas/tests/series/indexing/conftest.py)

Used:
pandas/pandas/tests/series/test_repr.py L74 (in test_repr)
pandas/tests/series/indexing/test_indexing.py L92 test_getitem_get
pandas/tests/series/indexing/test_indexing.py L121 test_getitem_fancy
pandas/tests/series/indexing/test_indexing.py L559 test_slice
```

* As fixture `object_series`:
```
Defined:
pandas/tests/series/conftest.py L26 as object_series

Used:
pandas/tests/series/test_combine_concat.py L14 test_append as object_series fixture

```

> Mostly could just change and see what breaks though. The naming of this obviously means the intent is to deal with object data, so I don't think should break too much actually making this return an object dtype

As you say, there is no breaks at test.

Even though tests are passed, I think `test_objarr_add_invalid` should be checked whether it used as right way.

I'll make PR about this issue!

**Comment by WillAyd** [comment]
Awesome - thanks for digging into this
