### ISSUE TITLE
Move helper methods for Named Aggregation out of groupby/generic

### ISSUE THREAD

**Issue by christopherzimmerman** [pandas-dev/pandas#28380]
Related to #28333 and #26513 

There are several helper methods to help with named aggregations, that are found in [`pandas.core.groupby.generic`](https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/generic.py), namely:

- [`_is_multi_agg_with_relabel`](https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/generic.py#L1704)
- [`_normalize_keyword_aggregation`](https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/generic.py#L1729)
- [`_make_unique`](https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/generic.py#L1793)

If this functionality gets standardized across aggregations other than just `groupby`, it would make sense to have these moved out of this file.

**Comment by WillAyd** [comment]
Makes sense. I think would take a PR if you have something concrete to propose

@TomAugspurger

**Comment by TomAugspurger** [comment]
Yeah. I'd recommend making a branch that does everything (moving the helpers, implementing NamedAgg for window), to prove things work, and then split the moving of helpers to its own PR.

**Comment by jbrockmendel** [comment]
These now live in core.apply, closing as complete.
