### ISSUE TITLE
DEPR: Move rarely used I/O connectors to third party modules

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#28409]
Related to #26804 (and indirectly related to #15862, #15008 if we standardize I/O connectors as part of this)

The recent survey shows that several of our  I/O connectors (Stata, SPSS, SAS and GBQ) are rarely used (from the chart I'd say around 3% of respondents said they used them):

![pandas_survey_io](https://user-images.githubusercontent.com/10058240/64779479-12279b00-d556-11e9-9154-9c8b1c03cb12.png)

While afaik all them are just wrappers around other libraries, and don't contain much code to maintain, I see few main immediate advantages:
- Allow an ecosystem of third-party modules
- Reduce the complexity and time of the CI
- Not commit to the connector API

**I/O ecosystem**

While the number of widely used formats is quite limited, the number of possible I/O connectors is huge. Several new connectors have been requested in the past, like markdown (#11052), avro (#11752), docx (#22518), and there are surely plenty of specialized and internal formats that didn't make sense to propose adding to pandas, but that people would appreciate having and using the same standard API (`pandas.read_*` / `DataFrame.to_*`) we have. And there may also be alternative versions of the connectors we provide (see for example this lightning talk by @dutc dicussing about an unsafe `pandas.read_csv`: https://youtu.be/QkQ5HHEu1b4?t=1554).

**CI**

For the CI, those modules include dependencies that need to be downloaded for every build. We also have files in `pandas/tests/io/data` that eventually we may need to update. For GBQ in particular, we have to store the password for the account we use to test, and those tests fail from time to time for connectivity problems. For the clipboard (not proposing to move to a third-party yet, but is a good candidate too), we require to emulate an X system in our tests (need to check if we finally fixed the tests, but they weren't running for a while because of problems on the CI set up).

And of course our test suite is taking some extra time to test all these connectors.

**API changes**

Being part of our public API, I think we need to commit to the API of those connectors, in the same way as we do with the rest of our API. But, for whatever reason it may make sense to discontinue some of these connectors (e.g. Google releasing a replacement for GBQ...), or make important changes to their parameters, and probably it makes sense to have different release cycles for them.

This also applies to connectors not yet in pandas, but that we may include if we keep the policy of adding to our code base the connectors for all the formats / services we consider relevant.

I know timing is not great, but because of this API commitment, I'd personally remove Stata, SPSS, SAS and GBQ before pandas 1.0.

**Comment by TomAugspurger** [comment]
I'm not sure how to square these two

> Just to be clear, there is no discussion on removing those connectors from pandas

> users would have to add another dependency (e.g conda install pandas-stata) and possibly an extra import in their code

The questions of "where is this developed" and "how do I install this" can be separated. We're able to

1. develop things in one repo and install them in one package (today's setup)
2. split things into separate repos and package as one
3. split things into separate reops and package separately

Which of those (if any) are you proposing?

**Comment by datapythonista** [comment]
Good point, I'm proposing 3.

But probably worth clarifying my priorities:

1. Allow an ecosystem of I/O connectors (without monkey patching, and with the same API than the ones we ship).
2. Make our connectors follow a standard API (e.g. subclass a base class and implement certain methods), the same than for third-party connectors
3. Move GBQ to a third party library, because the complexity it adds to the CI
4. Move out the other connectors that make sense

To me, 1 and 2 are quite important, they will empower users and simplify our code. 3 would be really nice, but not as important. I think 4 makes a lot of sense, but if people who actually maintain those less used connectors prefer to have them in pandas, I think it's not optimal, but it's surely all right.

**Comment by jreback** [comment]
> Good point, I'm proposing 3.
> 

the main issue is maintainers (who is going to maintain these)  and infrastructure

it’s not trivial to build wheels in all platforms

> But probably worth clarifying my priorities:
> 
> 1. Allow an ecosystem of I/O connectors (without monkey patching, and with the same API than the ones we ship).
> 2. Make our connectors follow a standard API (e.g. subclass a base class and implement certain methods), the same than for third-party connectors
> 3. Move GBQ to a third party library, because the complexity it adds to the C

this is already a 3rd party library;we just test

> 4. Move out the other connectors that make sense
> 
> To me, 1 and 2 are quite important, they will empower users and simplify our code. 3 would be really nice, but not as important. I think 4 makes a lot of sense, but if people who actually maintain those less used connectors prefer to have them in pandas, I think it's not optimal, but it's surely all right.

**Comment by datapythonista** [comment]
> this is already a 3rd party library;we just test

Thanks for the info, I totally missed that. I thought it was a wrapper around a generic gbq library, I see now that it's a third-party connector already, and we basically have the documentation.

Do you think it's worth testing it in every pandas PR? I guess there is a reason, but seems like adding a nightly build to pandas_gbq that tests with the latest pandas (release candidates, or may be master) should be enough. I think having it well decoupled (moving the tests there) would make things simpler, not only for the CI.

**Comment by jreback** [comment]
wouldn’t object to having a nightly build test
but otoh it’s simpler to have everything in a single well tested build(s)

**Comment by datapythonista** [comment]
I think the preference is to keep all I/O connectors in the pandas main repo. Closing.
