### ISSUE TITLE
test_cross_engine_pa_fp fails locally.

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#28422]
```
___________________________ test_cross_engine_pa_fp ___________________________

df_cross_compat =    a  b    d      e          f
0  a  1  4.0   True 2013-01-01
1  b  2  5.0  False 2013-01-02
2  c  3  6.0   True 2013-01-03
pa = 'pyarrow', fp = 'fastparquet'

    def test_cross_engine_pa_fp(df_cross_compat, pa, fp):
        # cross-compat with differing reading/writing engines

        df = df_cross_compat
        with tm.ensure_clean() as path:
            df.to_parquet(path, engine=pa, compression=None)

>           result = read_parquet(path, engine=fp)

pandas\tests\io\test_parquet.py:232:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pandas\io\parquet.py:293: in read_parquet
    return impl.read(path, columns=columns, **kwargs)
pandas\io\parquet.py:198: in read
    return parquet_file.to_pandas(columns=columns, **kwargs)
..\..\..\Anaconda3\envs\pandas-dev\lib\site-packages\fastparquet\api.py:421: in to_pandas
    check_column_names(self.columns + list(self.cats), columns, categories)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

columns = ['a', 'b', 'd', 'e', 'f']
args = (['a', 'b', 'd', 'e', 'f', {'kind': 'range', 'name': None, 'start': 0, 'step': 1, ...}], None)
arg = ['a', 'b', 'd', 'e', 'f', {'kind': 'range', 'name': None, 'start': 0, 'step': 1, ...}]

    def check_column_names(columns, *args):
        """Ensure that parameters listing column names have corresponding columns"""
        for arg in args:
            if isinstance(arg, (tuple, list)):
>               if set(arg) - set(columns):
E               TypeError: unhashable type: 'dict'

..\..\..\Anaconda3\envs\pandas-dev\lib\site-packages\fastparquet\util.py:92: TypeError
```

<details>

INSTALLED VERSIONS
------------------
commit           : 0ab32e88481440bfb4a102bb7731cbde2e5ceafe
python           : 3.7.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : None.None

pandas           : 0.25.0+339.g0ab32e884
numpy            : 1.16.4
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.2
setuptools       : 41.0.1
Cython           : 0.29.13
pytest           : 5.0.1
hypothesis       : 4.32.2
sphinx           : 1.8.5
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : 0.3.0
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : 0.13.0
pytables         : None
s3fs             : 0.2.1
scipy            : 1.3.1
sqlalchemy       : 1.3.7
tables           : 3.5.2
xarray           : 0.12.1
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.8

</details>

**Comment by simonjayhawkins** [comment]
> I think this was just fixed in [9bb82b3](https://github.com/pandas-dev/pandas/commit/9bb82b3539be03befa5473f92dccfea2ddf0baf9) ?

in that commit, `test_cross_engine_fp_pa` was changed. does `test_cross_engine_pa_fp` need to change as well?

**Comment by jorisvandenbossche** [comment]
Ah, those small differences :)

What versions of pyarrow and fastparquet do you have? 
This is related to handling the serialized index metadata, which I would assume is handled properly in the latest fastparquet release (at least they now also write it)

**Comment by jmg7173** [comment]
I'm currently using `fastparquet=0.3.0` and `pyarrow=0.13.0`.

**Comment by jorisvandenbossche** [comment]
Would you be able to try with the latest release 0.3.2 ? 
The code to deal with the updated metadata was only included in the last release I think.

**Comment by jmg7173** [comment]
It works well!

How about fix requirements.txt fastparquet as `fastparquet>=0.3.2`?

**Comment by jorisvandenbossche** [comment]
I maybe wouldn't directly increase the requirements, as it is only the combination of certain versions of pyarrow and fastparquet that give this problem (nothing directly related to the pandas code itself, so eg pandas works fine with fastparquet 0.3.0). 
It's of course annoying for users, and for the tests we can in principle skip them if we detect that combination.

> I made my environment 2weeks ago, but it installs fastparquet==0.3.0 in default.

That's strange, not directly sure why (0.3.0 is relatively recent, but there was already a 0.3.1 a few months back as well). Are you using conda? Maybe the default channel lacks a bit behind in versions (on conda-forge it is certainly available).

**Comment by jmg7173** [comment]
Yes, I'm using conda. I checked default channel of conda(https://repo.anaconda.com/pkgs/main/), it uses 0.3.0. Is it different between this channel and conda-forge?

By the way, I'm working on OSX (Mojave 10.14.6). Is there any possibility about such problems because of using OSX? Because, I have other problems about test. In my environment, pytest fails at `pytest pandas` but some failed tests pass at single pytest run such as `pytest pandas/tests/io/test_parquet.py`

**Comment by 0xF4D3C0D3** [comment]
@jmg7173 As you said, I also tried a single test by `pytest pandas/tests/io/test_parquet.py` . However, I still get the same failure as below:

```
====================================================== FAILURES =======================================================
_______________________________________________ test_cross_engine_pa_fp _______________________________________________

df_cross_compat =    a  b    d      e          f
0  a  1  4.0   True 2013-01-01
1  b  2  5.0  False 2013-01-02
2  c  3  6.0   True 2013-01-03
pa = 'pyarrow', fp = 'fastparquet'

    def test_cross_engine_pa_fp(df_cross_compat, pa, fp):
        # cross-compat with differing reading/writing engines

        df = df_cross_compat
        with tm.ensure_clean() as path:
            df.to_parquet(path, engine=pa, compression=None)

>           result = read_parquet(path, engine=fp)

pandas\tests\io\test_parquet.py:232:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pandas\io\parquet.py:293: in read_parquet
    return impl.read(path, columns=columns, **kwargs)
pandas\io\parquet.py:198: in read
    return parquet_file.to_pandas(columns=columns, **kwargs)
C:\ProgramData\Anaconda3\envs\pandas-dev\lib\site-packages\fastparquet\api.py:421: in to_pandas
    check_column_names(self.columns + list(self.cats), columns, categories)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

columns = ['a', 'b', 'd', 'e', 'f']
args = (['a', 'b', 'd', 'e', 'f', {'kind': 'range', 'name': None, 'start': 0, 'step': 1, ...}], None)
arg = ['a', 'b', 'd', 'e', 'f', {'kind': 'range', 'name': None, 'start': 0, 'step': 1, ...}]

    def check_column_names(columns, *args):
        """Ensure that parameters listing column names have corresponding columns"""
        for arg in args:
            if isinstance(arg, (tuple, list)):
>               if set(arg) - set(columns):
E               TypeError: unhashable type: 'dict'

C:\ProgramData\Anaconda3\envs\pandas-dev\lib\site-packages\fastparquet\util.py:92: TypeError
============================== 1 failed, 45 passed, 4 skipped, 1 xfailed in 5.19 seconds ==============================
``` 
Perhaps it would pass because you had upgraded _fastparquet_ to 0.3.2, not because of a single test.
And of course, I have passed the test too after the upgrade.
I'm gonna try this again tomorrow at the office with OSX as well.

<details>

INSTALLED VERSIONS
------------------
commit           : 3f0e8162e2866411bc98d7317ffc76105b5f2af5
python           : 3.7.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.26.0.dev0+352.g3f0e8162e
numpy            : 1.16.5
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.2
setuptools       : 41.0.1
Cython           : 0.29.13
pytest           : 5.0.1
hypothesis       : 4.32.2
sphinx           : 1.8.5
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : 1.2.1
fastparquet      : 0.3.0
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : 0.13.0
pytables         : None
s3fs             : 0.2.1
scipy            : 1.3.1
sqlalchemy       : 1.3.7
tables           : 3.5.2
xarray           : 0.12.1
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.8
</details>

**Comment by 0xF4D3C0D3** [comment]
The result was the same in OSX too.

```
 donghojung@Andrew  ~/Desktop/pandas-0xF4D3C0D3   master  pytest pandas/tests/io/test_parquet.py                                                                                     1 ↵  4880  17:35:05
============================================================================================= test session starts ==============================================================================================
platform darwin -- Python 3.7.4, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
hypothesis profile 'ci' -> deadline=timedelta(milliseconds=500.0), suppress_health_check=[HealthCheck.too_slow], database=DirectoryBasedExampleDatabase('/Users/donghojung/Desktop/pandas-0xF4D3C0D3/.hypothesis/examples')
rootdir: /Users/donghojung/Desktop/pandas-0xF4D3C0D3, inifile: setup.cfg
plugins: hypothesis-4.32.2, xdist-1.28.0, cov-2.7.1, mock-1.10.4, forked-1.0.2
collected 51 items

pandas/tests/io/test_parquet.py .....Fx.........s...s..................s.s.........                                                                                                                      [100%]

=================================================================================================== FAILURES ===================================================================================================
___________________________________________________________________________________________ test_cross_engine_pa_fp ____________________________________________________________________________________________

df_cross_compat =    a  b    d      e          f
0  a  1  4.0   True 2013-01-01
1  b  2  5.0  False 2013-01-02
2  c  3  6.0   True 2013-01-03, pa = 'pyarrow', fp = 'fastparquet'

    def test_cross_engine_pa_fp(df_cross_compat, pa, fp):
        # cross-compat with differing reading/writing engines

        df = df_cross_compat
        with tm.ensure_clean() as path:
            df.to_parquet(path, engine=pa, compression=None)

>           result = read_parquet(path, engine=fp)

pandas/tests/io/test_parquet.py:232:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pandas/io/parquet.py:293: in read_parquet
    return impl.read(path, columns=columns, **kwargs)
pandas/io/parquet.py:198: in read
    return parquet_file.to_pandas(columns=columns, **kwargs)
../../anaconda3/envs/pandas-dev/lib/python3.7/site-packages/fastparquet/api.py:421: in to_pandas
    check_column_names(self.columns + list(self.cats), columns, categories)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

columns = ['a', 'b', 'd', 'e', 'f'], args = (['a', 'b', 'd', 'e', 'f', {'kind': 'range', 'name': None, 'start': 0, 'step': 1, ...}], None)
arg = ['a', 'b', 'd', 'e', 'f', {'kind': 'range', 'name': None, 'start': 0, 'step': 1, ...}]

    def check_column_names(columns, *args):
        """Ensure that parameters listing column names have corresponding columns"""
        for arg in args:
            if isinstance(arg, (tuple, list)):
>               if set(arg) - set(columns):
E               TypeError: unhashable type: 'dict'

../../anaconda3/envs/pandas-dev/lib/python3.7/site-packages/fastparquet/util.py:92: TypeError
========================================================================== 1 failed, 45 passed, 4 skipped, 1 xfailed in 5.49 seconds ==========================================================================
```

<details>

INSTALLED VERSIONS
------------------
commit           : 3f0e8162e2866411bc98d7317ffc76105b5f2af5
python           : 3.7.4.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.26.0.dev0+352.g3f0e8162e
numpy            : 1.16.5
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.2
setuptools       : 41.0.1
Cython           : 0.29.13
pytest           : 5.0.1
hypothesis       : 4.32.2
sphinx           : 1.8.5
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : 1.2.1
fastparquet      : 0.3.0
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : 0.13.0
pytables         : None
s3fs             : 0.2.1
scipy            : 1.3.1
sqlalchemy       : 1.3.7
tables           : 3.5.2
xarray           : 0.12.1
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.8
</details>

**Comment by alimcmaster1** [comment]
Looks like we now have `fastparquet>=0.3.2` in our `dev-requirements.txt`. Feel free to reopen if this is an issue for anyone.
