### ISSUE TITLE
DOC: Series.between() can take arguments that are Series, not just scalars

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#28435]
#### Code Sample, a copy-pastable example if possible

```python
In [1]: import pandas as pd

In [2]: s = pd.Series([4,5,6])
   ...: s1 = pd.Series([3,6, 5])
   ...: s2 = pd.Series([8,8,8])
   ...: s.between(s1, s2)
Out[2]:
0     True
1    False
2     True
dtype: bool

```
#### Problem description

The docs for `Series.between()` at https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.between.html indicate that the `left` and `right` arguments are scalars, but it is possible (as shown above) to use a `Series` as either argument.

The docs should be updated to reflect this, including the examples.

#### Expected Output

N/A

#### Output of ``pd.show_versions()``

<details>

C:\Anaconda3\lib\site-packages\xarray\core\merge.py:17: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.1
numpy            : 1.16.4
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.2
setuptools       : 41.0.1
Cython           : 0.29.12
pytest           : 5.0.1
hypothesis       : None
sphinx           : 2.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : 0.9.3
psycopg2         : 2.7.6.1 (dt dec pq3 ext lo64)
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.3.7
tables           : 3.5.2
xarray           : 0.12.1
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.8
</details>

**Comment by TomAugspurger** [comment]
Does this align by series before doing the operaiotn?

**Comment by Dr-Irv** [comment]
No, if the indices don't perfectly align (or you don't use a scalar), you get
```
ValueError: Can only compare identically-labeled Series objects
```

**Comment by TomAugspurger** [comment]
Ok, so the arguments can be scalar or any list-like with the same number of elements as self?

**Comment by Dr-Irv** [comment]
Yes. Basically for `s.between(a,b)`, if `a < s` and `s < b` are valid, then `s.between(a,b)` is valid
