### ISSUE TITLE
PERF: use numpy.random.Generator

### ISSUE THREAD

**Issue by thrasibule** [pandas-dev/pandas#28440]
Numpy 1.17 introduced a new random module with faster PRNGs, and which drops the strict reproducibility of random streams guarantee, which allows some algorithmic improvements. In particular, the choice method is now a lot faster in the replace=False case. Would it make sense for ``random_state`` to return a np.random.Generator instead of a np.random.RandomState when numpy version >= 1.17 here: https://github.com/pandas-dev/pandas/blob/master/pandas/core/common.py#L408. This would automatically speed up the DataFrame.sample method for instance.
I can write a PR, but I'm not sure how to handle the different numpy versions. Should I just do the tests inside ``random_state`` or is something that needs to go inside numpy.compat?

**Comment by WillAyd** [comment]
There should already be `_np_version_under1p17` from NumPy compat which you can use internally

**Comment by TomAugspurger** [comment]
We’ll need to discuss what API guarantees we make about the seeds. I don’t think the output should change when a use provides an integer seed, for example.

What happens now if the user passes a new  random Generator instance?

**Comment by jamesmyatt** [comment]
`ValueError`!

**Comment by jamesmyatt** [comment]
Guarantee-wise, it would be probably be best to match [NEP 19](https://numpy.org/neps/nep-0019-rng-policy.html)

**Comment by mroeschke** [comment]
Our sample APIs take numpy random generators now so closing
