### ISSUE TITLE
[TST] Revise test_astype_str_map

### ISSUE THREAD

**Issue by makbigc** [pandas-dev/pandas#28454]
follow up https://github.com/pandas-dev/pandas/pull/28176#pullrequestreview-286089893

Right now, `astype(str)` converts `np.nan` into string. 
```
In [3]: pd.Series(['foo', np.nan]).astype(str)
Out[3]: 
0    foo
1    nan
dtype: object
```

After merging #28176, `astype(str)` will preserve `np.nan`.

Review `test_astype_str_map` in pandas/tests/series/test_dtypes.py to get rid of any `skipna` keyword argument.

**Comment by bhuvanakundumani** [comment]
I am interested in working on this.

**Comment by NumberPiOso** [comment]
take

**Comment by NumberPiOso** [comment]
I am trying to define necessary actions to correct this. Please follow

https://github.com/pandas-dev/pandas/pull/28176#issuecomment-1027292485

**Comment by mroeschke** [comment]
Looks like there is no `skipna` kwargs in this test now so closing. Happy to reopen if misunderstood
