### ISSUE TITLE
pd.read_csv does not allow passing valid delimiters when using sep=None

### ISSUE THREAD

**Issue by dmitrygalperin** [pandas-dev/pandas#28458]
#### Code Sample, a copy-pastable example if possible

Using a sample file of:
```
email
test@gmail.com
test2@yahoo.com
test3@microsoft.com
```

```python
import pandas as pd

pd.read_csv('email.txt', sep=None)

Out[24]: 
                          e  ail
test@g               ail.co  NaN
test2@yahoo.co          NaN  NaN
test3@          icrosoft.co  NaN

```
#### Problem description

There is no way to pass the 'delimiters' argument to csv.Sniffer.sniff when using pd.read_csv(sep=None) causing an invalid detection of the delimiter in files with only a single column.

#### Expected Output
```python
                 email
0       test@gmail.com
1      test2@yahoo.com
2  test3@microsoft.com
```

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.1
numpy            : 1.16.1
pytz             : 2017.3
dateutil         : 2.6.1
pip              : 19.0.1
setuptools       : 40.6.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 1.7.6
blosc            : None
feather          : None
xlsxwriter       : 1.0.4
lxml.etree       : 4.1.1
html5lib         : 1.0b10
pymysql          : None
psycopg2         : None
jinja2           : 2.10
IPython          : 7.2.0
pandas_datareader: None
bs4              : 4.6.0
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.1.1
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 2.5.14
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.8
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : 1.0.4
</details>

**Comment by WillAyd** [comment]
Looks buggy though I'm a little confused by the title and problem description. I didn't see the CSV Sniffer handling this any more appropriately - am I overlooking something?

```python
In [20]: data = """email
    ...: test@gmail.com
    ...: test2@yahoo.com
    ...: test3@microsoft.com"""
In [20]: dialect = csv.Sniffer().sniff(data)
In [20]: reader = csv.reader(io.StringIO(data), dialect)
In [25]: for row in reader:
    ...:     print(row)
    ...:
['', 'mail']
['t', 'st@gmail.com']
['t', 'st2@yahoo.com']
['t', 'st3@microsoft.com']
```

**Comment by dmitrygalperin** [comment]
Sorry if I was a bit vague. Sniffer certainly does handle it appropriately given the dataset, but say I wanted to limit the possible valid delimiters. With the csv module I can do:

```python
data = """email
    ...: test@gmail.com
    ...: test2@yahoo.com
    ...: test3@microsoft.com"""

csv.Sniffer().sniff(data, delimiters='\t,')
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-10-75a782c3a02f> in <module>
----> 1 csv.Sniffer().sniff(data, delimiters='\t,')

c:\python\lib\csv.py in sniff(self, sample, delimiters)
    186 
    187         if not delimiter:
--> 188             raise Error("Could not determine delimiter")
    189 
    190         class dialect(Dialect):

Error: Could not determine delimiter
```

That way I can limit the possible valid delimiters and implement a fallback when the delimiter cannot be determined. Otherwise, the detected delimiter is 'e', which logically makes no sense given the dataset.

read_csv does not allow passing the 'delimiters' argument down to csv.Sniffer.sniff

**Comment by mribeirodantas** [comment]
I'm also interested in it. It would be really useful if I could pass valid delimiters (and in order of precedence) to read_table, just like we can do to the sniff function. read_table can not properly guess the separator in my file but with sniff I can due to the delimiters.

**Comment by phofl** [comment]
Event without passing the delimiter through, we get your expected result:

```
data = """email
test@gmail.com
test2@yahoo.com
test3@microsoft.com"""

pd.read_csv(StringIO(data), sep=None, delimiter='\t,', engine="python")
```

```
                 email
0       test@gmail.com
1      test2@yahoo.com
2  test3@microsoft.com
```

Is this your expected result?

**Comment by phofl** [comment]
Labelling as closing candidate. Please adress my previous comment @dmitrygalperin, otherwise we will close

**Comment by mroeschke** [comment]
Closing as it appears this issue is not directly actionable.
