### ISSUE TITLE
DataFrame.to_html should validate that formatters has the correct length

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#28469]
The length of `formatters` should match the number of columns

Both of these should error with a nice message.

```python
In [2]: df = pd.DataFrame(columns=['a', 'b', 'c'])

In [3]: df.to_html(formatters=['{}'.format])


In [4]: df.to_html(formatters=['{}'.format] * 5)
```

Currntly `In [4]` succeeds, silently ignoring the bad input. `In[3]` values with a vague `IndexError: list index out of range`.

**Comment by guipleite** [comment]
Hi! Can @hugoecarl and @gabriellm1 and I work on this?

**Comment by WillAyd** [comment]
@guipleite for sure - would certainly take a PR from you all

**Comment by gabriellm1** [comment]
So in case `In[3]` and `In[4]` the result error should be the same as `formatters list not same length as Dataframe` ? If so, where in the project should this be made?

**Comment by TomAugspurger** [comment]
Possibly in `DataFrameFormatter.__init__`? Not really sure.
