### ISSUE TITLE
GroupBy idxmin gives incorrect result on single-row data frame

### ISSUE THREAD

**Issue by sejsingffdc** [pandas-dev/pandas#28473]
#### Code Sample, a copy-pastable example if possible

```python
    def test_idxmin(self):
        df = pd.DataFrame({'accountid': ['12345'], 'createddate': [pd.Timestamp(2019, 1, 1)]})
        min = df.groupby('accountid')[['createddate']].idxmin(axis=1)
        print(min)

        df2 = pd.DataFrame({'accountid': ['12345', '23456'], 'createddate': [pd.Timestamp(2019, 1, 1), pd.Timestamp(2019, 2, 1)]})
        min2 = df2.groupby('accountid')[['createddate']].idxmin(axis=1)
        print(min2)

```
#### Problem description

The first print statement shows:
                     0
accountid             
12345      createddate

Current behavior appears to swap the column name and minimizer value.

The second print statement shows the correct result:
           createddate
accountid             
12345                0
23456                1

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None

pandas           : 0.25.1
numpy            : 1.15.2
pytz             : 2018.7
dateutil         : 2.7.5
pip              : 19.0.3
setuptools       : 40.5.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.7.5 (dt dec pq3 ext lo64)
jinja2           : 2.10
IPython          : 5.0.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : 0.3.0
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.0.1
numexpr          : None
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : 0.11.0
pytables         : None
s3fs             : None
scipy            : 1.1.0
sqlalchemy       : 1.2.12
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by TomAugspurger** [comment]
Looks buggy. Not sure where things are going wrong though.

**Comment by BrunaKimura** [comment]
I will look into this!

**Comment by TomAugspurger** [comment]
Great! FWIW, on master I get a different exception now

```pytb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/sandbox/pandas/pandas/core/groupby/groupby.py in apply(self, func, *args, **kwargs)
    734             try:
--> 735                 result = self._python_apply_general(f)
    736             except TypeError:

~/sandbox/pandas/pandas/core/groupby/groupby.py in _python_apply_general(self, f)
    753         return self._wrap_applied_output(
--> 754             keys, values, not_indexed_same=mutated or self.mutated
    755         )

~/sandbox/pandas/pandas/core/groupby/generic.py in _wrap_applied_output(self, keys, values, not_indexed_same)
   1280                         # GH 8467
-> 1281                         return self._concat_objects(keys, values, not_indexed_same=True)
   1282

~/sandbox/pandas/pandas/core/groupby/groupby.py in _concat_objects(self, keys, values, not_indexed_same)
   1007
-> 1008             result.name = self._selection_name
   1009

~/sandbox/pandas/pandas/core/generic.py in __setattr__(self, name, value)
   5086             object.__getattribute__(self, name)
-> 5087             return object.__setattr__(self, name, value)
   5088         except AttributeError:

~/sandbox/pandas/pandas/core/series.py in name(self, value)
    446         if not is_hashable(value):
--> 447             raise TypeError("Series.name must be a hashable type")
    448         object.__setattr__(self, "_name", value)

TypeError: Series.name must be a hashable type

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-6-6213974c2c6c> in <module>
      4
      5 df2 = pd.DataFrame({'accountid': ['12345', '23456'], 'createddate': [pd.Timestamp(2019, 1, 1), pd.Timestamp(2019, 2, 1)]})
----> 6 min2 = df2.groupby('accountid')[['createddate']].idxmin(axis=1)

~/sandbox/pandas/pandas/core/groupby/groupby.py in wrapper(*args, **kwargs)
    642
    643             try:
--> 644                 return self.apply(curried)
    645             except TypeError as err:
    646                 if not re.search(

~/sandbox/pandas/pandas/core/groupby/groupby.py in apply(self, func, *args, **kwargs)
    744
    745                 with _group_selection_context(self):
--> 746                     return self._python_apply_general(f)
    747
    748         return result

~/sandbox/pandas/pandas/core/groupby/groupby.py in _python_apply_general(self, f)
    752
    753         return self._wrap_applied_output(
--> 754             keys, values, not_indexed_same=mutated or self.mutated
    755         )
    756

~/sandbox/pandas/pandas/core/groupby/generic.py in _wrap_applied_output(self, keys, values, not_indexed_same)
   1279                     if not all_indexed_same:
   1280                         # GH 8467
-> 1281                         return self._concat_objects(keys, values, not_indexed_same=True)
   1282
   1283                 if self.axis == 0 and isinstance(v, ABCSeries):

~/sandbox/pandas/pandas/core/groupby/groupby.py in _concat_objects(self, keys, values, not_indexed_same)
   1006         if isinstance(result, Series) and self._selection_name is not None:
   1007
-> 1008             result.name = self._selection_name
   1009
   1010         return result

~/sandbox/pandas/pandas/core/generic.py in __setattr__(self, name, value)
   5085         try:
   5086             object.__getattribute__(self, name)
-> 5087             return object.__setattr__(self, name, value)
   5088         except AttributeError:
   5089             pass

~/sandbox/pandas/pandas/core/series.py in name(self, value)
    445     def name(self, value: Label) -> None:
    446         if not is_hashable(value):
--> 447             raise TypeError("Series.name must be a hashable type")
    448         object.__setattr__(self, "_name", value)
    449

TypeError: Series.name must be a hashable type
```

**Comment by rhshadrach** [comment]
I have a fix for the exception that is currently raised in master that @TomAugspurger  reported. I'm seeing different output than what @sejsingffdc has, and I'm wondering what the desired result is. Here is the result from df (in the code above):

````
                     0
accountid             
12345      createddate
````

And here is the result from df2:

````
accountid   
12345      0    createddate
23456      1    createddate
dtype: object
````

It seems to me that df2 is correct - it has for each group and each row the name of the column which has the minimum. I think it is desired for df to have the same shape - namely it should come out as:

````
accountid             
12345      0    createddate
dtype: object
````

Does that seem right?

**Comment by TomAugspurger** [comment]
I'm not actually sure what the expected output is. It's not clear to me what is being passed to idxmin.

**Comment by sejsingffdc** [comment]
@rhshadrach yes exactly, that's my expectation. The shape of the resulting DataFrame should be independent of the number of groups.

**Comment by rhshadrach** [comment]
> I'm not actually sure what the expected output is. It's not clear to me what is being passed to idxmin.

@TomAugspurger The dataframe appears in the top post, so I think you're talking about some intermediate value that gets passed internally. I'd be happy to dig it out and post it here, but I'm not sure what you're after.

Just wanted to share some things I've found so far. Master currently fails due to this line:

https://github.com/pandas-dev/pandas/blob/69ffb018a230c50eec10e2f303bc11251457c159/pandas/core/groupby/groupby.py#L975

Adding "and not isinstance(self._selection, list)" to the condition there will fix.

The difference in shape is because of the condition

https://github.com/pandas-dev/pandas/blob/69ffb018a230c50eec10e2f303bc11251457c159/pandas/core/groupby/generic.py#L1285-L1287

This evaluates to True when there is more than one group. Adding "or not not_indexed_same" to this condition gives the output the shape I believe as desired, and passes all tests. While perhaps being confusing, not_indexed_same is not the same as "not all_indexed_same". The former is passed in from mutated here:

https://github.com/pandas-dev/pandas/blob/69ffb018a230c50eec10e2f303bc11251457c159/pandas/core/groupby/groupby.py#L749-L754

Still, I'm not sure it is a correct fix, mostly because I do not understand all of the branching that happens in _wrap_applied_output.

If the condition above is to be left alone, another possible place I think may be appropriate is here:

https://github.com/pandas-dev/pandas/blob/69ffb018a230c50eec10e2f303bc11251457c159/pandas/core/groupby/generic.py#L1318-L1323

If we do not unstack, the desired shape is again obtained. Making it so that the unstack is done only if all_indexed_same is False again passes all tests, but I really don't know if doing so is correct either.

**Comment by rhshadrach** [comment]
axis=1 is deprecated and will be removed in pandas 3.0. Closing.
