### ISSUE TITLE
_normalize_keyword_aggregation` named agg helper function should be made public

### ISSUE THREAD

**Issue by arpit1997** [pandas-dev/pandas#28472]
Slightly related to #28380 

Currently an issue in Dask https://github.com/dask/dask/issues/5294 for implementing Named Aggregation (introduced in pandas 0.25.0) is open. To implement this it needs to use `_normalize_keyword_aggregation` and `_is_multi_agg_with_relabel`. 

Making it public would be useful for frameworks like [dask](https://github.com/dask/dask) [mars](https://github.com/mars-project/mars)

cc: @TomAugspurger

**Comment by TomAugspurger** [comment]
And as an alternative to making it part of the official public API for end-users, we could add a test to ensuring that it's implementation doesn't move, so that projects like dask can rely on it.

That last option conflicts a bit our desire to deprecate all of `pandas.core` though.

**Comment by zbrookle** [comment]
@TomAugspurger Could I work on this? I'm interested in seeing this moved forward since I need the named aggregation feature in Dask to incorporate it into the dataframe_sql framework that I'm building

**Comment by TomAugspurger** [comment]
That sounds good.

**Comment by jbrockmendel** [comment]
@rhshadrach  these now live in core.apply, so im declaring this your call.

**Comment by rhshadrach** [comment]
The linked issue is now closed, with dask implementing it using `reconstruct_func` (which calls `normalize_keyword_aggregation`). With this, I'm okay with considering `reconstruct_func` public and adding tests, but I don't think we should adding it to the API.

cc @mroeschke for any thoughts.

**Comment by jbrockmendel** [comment]
+1 for something pseudo-public

**Comment by mroeschke** [comment]
+1 as well for exposing this publicly somehow

**Comment by rhshadrach** [comment]
What would be the reason for moving them?

**Comment by rhshadrach** [comment]
This is not wildly know, but the API documentation (https://pandas.pydata.org/pandas-docs/dev/reference/index.html) states:

> The pandas.core, pandas.compat, and pandas.util top-level modules are PRIVATE. Stable functionality in such modules is not guaranteed.

As such, to ensure we don't accidentally break dask, I think it would be sufficient to add a test for just `reconstruct_func` within `pandas/tests/apply` with a comment to the effect of "Test is to ensure this method isn't moved; it is used by other libraries (e.g. dask)"
