### ISSUE TITLE
Naming Convention for Type Aliases

### ISSUE THREAD

**Issue by vaibhavhrt** [pandas-dev/pandas#28480]
A consistent naming convention should be used for type aliases.
Maybe CamelCase as the stdlib typing module is in Camel Case, but suggestions are welcome.

Inconsistent names could be found in `pandas.io.formatters.formatter`, `formatters_type` and `float_format_type`. Look for other similar names too and fix them all.

**Comment by vaibhavhrt** [comment]
I will open a PR after a few days. Meanwhile someone else is welcome to pick it up.

**Comment by mroeschke** [comment]
Thanks for the request, but it appears this hasn't gain traction in a while so closing
