### ISSUE TITLE
Matplotlib's ConciseDateFormatter-like formatter in pandas.plotting._matplotlib.converter.py

### ISSUE THREAD

**Issue by EBenkler** [pandas-dev/pandas#28485]
Matplotlib has a nice formatter class named matplotlib.dates.ConciseDateFormatter, which is a candidate to become Matplotlib's default date formatter in future versions (as of MPL 3.1.1, see 
[Matplotlib documentation](https://matplotlib.org/gallery/ticks_and_spines/date_concise_formatter.html)).

It would be nice if the converters defined in pandas.plotting._matplotlib.converter.py
could provide the same date formatting, especially regarding the pandas data types like Period.

**Comment by TomAugspurger** [comment]
Possibly. Do you have a proposal for what using this would look like?

In general, I think we'd like to remove the need to maintain our own locators / formatters.

**Comment by EBenkler** [comment]
Sorry, I don't understand what you are exactly asking for by 
> Do you have a proposal for what using this would look like?

Are you asking why I think this would be good to have? Well, as I wrote, I like the ConciseDateFormatter and it will likely become the default in future versions of matplotlib.

Anyway, if you would like to get rid of own locators/formatters and other rather complex maintenance: Why not just implement the plotting via rather simple wrappers of generic matplotlib functions?
This means just to call e.g. matplotlib.pyplot.plot_dates(df.index, df.data, *args,**kargs) when df is a Pandas DataFrame and df.plot(*args, **kargs) is called (and so on with matplotlib.pyplot.plot if df.index contains numeric data). I don't see any side-effects, but we would get full functionality of matplotlib with a minimum of maintenance necessary even when something changes in matplotlib.

**Comment by EBenkler** [comment]
It seems that this has been fixed meanwhile, maybe by changes in Matplotlib. Anyway, I will close the issue as it became irrelevant.
