### ISSUE TITLE
Reindexing overlapping IntervalIndex throws KeyError

### ISSUE THREAD

**Issue by cedias** [pandas-dev/pandas#28496]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

df = pd.DataFrame({"start": ["2017-01-01 13:09:01", "2017-01-01 13:09:04", "2017-01-01 13:09:12"],
         "end":    ["2017-01-01 13:09:05", "2017-01-01 13:09:09", "2017-01-01 13:09:14"],
         "status": ["OK", "ERROR", "OK"]})


# create an IntervalIndex from start/end
iv_idx = pd.IntervalIndex.from_arrays(pd.to_datetime(df['start']), pd.to_datetime(df['end']), closed='both')

# generate the desired index of individual times
new_idx = pd.date_range(df['start'].min(), df['end'].max(), freq='1s')

# set the index of 'status' as the IntervalIndex, then reindex to the new index
result = df['status'].set_axis(iv_idx, inplace=False).reindex(new_idx)
result
```

#### Problem description

If the interval is overlapping, it throws a key error:

```
pandas/_libs/intervaltree.pxi in pandas._libs.interval.IntervalTree.get_loc()
KeyError: 1483276150000000000

```

#### Expected Output

Something less cryptic ?

Reindexing on an overlapping intervalIndex  with a DatetimeIndex should probably be checked by using `is_overlapping` 

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.14.138-89.102.amzn1.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 3.5.1
pip: 10.0.1
setuptools: 39.1.0
Cython: 0.28.4
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 3.0.3
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.4
lxml.etree: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.11
pymysql: None
psycopg2: 2.7.5 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: 0.1.5
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by TomAugspurger** [comment]
I think this is fixed on master to give a bit nicer error message.

```python
ValueError: cannot reindex from an overlapping axis
```
