### ISSUE TITLE
sample from Series should never return empty series

### ISSUE THREAD

**Issue by roelhogervorst** [pandas-dev/pandas#28495]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

# pandas 0.25
sample_data = pd.Series([1, 2])
result = sample_data.sample(frac=0.2)
result.empty

```
#### Problem description
When I sample with a fraction I always expect a result, returning an empty series is unexpected.

I found this issue in an older version of pandas, but it also happens in pandas 0.25

#### Expected Output
```python
Series([1], dtype: int64) # or 2 but not empty
```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.8.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8
pandas           : 0.25.1
numpy            : 1.17.2
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 18.1
setuptools       : 40.6.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
</details>

**Comment by TomAugspurger** [comment]
Can you check the PR where this was implemented to see if this case was discussed?

**Comment by dsaxton** [comment]
I would think this is the expected output since always selecting a fraction of zero is more correct than always selecting half.  If you want a positive count you can always provide a value for `n` (maybe setting it to the ceiling of `frac * len`).

**Comment by roelhogervorst** [comment]
@TomAugspurger I don't actually know how to find that PR. 
 Thanks for the suggestion @dsaxton, I have indeed worked around this issue, so my question is maybe more philosophical: 

- if I take a sample of bananas is it okay to return no bananas?

This feels wrong to me, but I can not articulate what the problem is exactly.

**Comment by TomAugspurger** [comment]
You might be able to find it with GitHub search or git blame.

Regardless, I'm not sure that we'll actually want to change anything at
this point. That's likely to be more
disruptive than it's worth.

We would of course welcome docs noting that the result can be empty,
depending on the number of row and frac.

**Comment by roelhogervorst** [comment]
Fair enough. Let me create a PR with a small doc update

**Comment by MarcoGorelli** [comment]
> Fair enough. Let me create a PR with a small doc update

Doesn't look like there's any traction here, so closing for now (IMO there's nothing surprising about a sample being empty)
