### ISSUE TITLE
Sparse DataFrame Transposes to Dense

### ISSUE THREAD

**Issue by asistradition** [pandas-dev/pandas#28504]
I am migrating my `SparseDataFrame`s to `DataFrames` with sparse columns. I can no longer transpose this DataFrame and have it stay sparse. The behavior I was expecting was to have a fully sparse DataFrame maintain sparsity when transposed.

```python
>>> arrs = scipy.sparse.coo_matrix(np.random.randint(2,size=(10000,1000)))

>>> pd.DataFrame.sparse.from_spmatrix(arrs).dtypes
0      Sparse[int64, 0]
             ...       
999    Sparse[int64, 0]

>>> pd.DataFrame.sparse.from_spmatrix(arrs.transpose()).dtypes
0       Sparse[int64, 0]
             ...       
9999    Sparse[int64, 0]

>>> pd.DataFrame.sparse.from_spmatrix(arrs).transpose().dtypes
0       int64
        ...  
9999    int64

>>> pd.SparseDataFrame(arrs).transpose().dtypes
0       Sparse[int64, nan]
               ...        
9999    Sparse[int64, nan]
```

> INSTALLED VERSIONS
> ------------------
> commit           : None
> python           : 3.6.8.final.0
> python-bits      : 64
> OS               : Linux
> 
> pandas           : 0.25.1
> numpy            : 1.17.1
> scipy            : 1.3.1

**Comment by jorisvandenbossche** [comment]
@asistradition thanks for the report! That's indeed a usability regression for DataFrame[sparse].

@TomAugspurger you mentioned something earlier today about transpose being possible in certain cases for ExtensionArrays?

**Comment by jorisvandenbossche** [comment]
Actually, looking at the old implementation:

https://github.com/pandas-dev/pandas/blob/171c71611886aab8549a8620c5b0071a129ad685/pandas/core/sparse/frame.py#L844-L855

it seems this went through the dense 2D values, and then sparsified it again. So although possible, it was not a very useful implementation in a "sparse" context.

**Comment by asistradition** [comment]
Ahh - yeah, that's not what I thought it was doing. I guess this is a feature request for a sparse transpose now (I can sparsify a dense matrix myself so I don't think reimplementing this behavior is necessary).

**Comment by TomAugspurger** [comment]
I don't think a true sparse transpose is really feasible for us, given the
SparseArray data model (I could be mistaken though).

**Comment by jorisvandenbossche** [comment]
But in principle it should be possible to avoid densifying the full dataframe. On the minimum, we could convert to scipy sparse, transpose, and convert back. That might not be very efficient, but at least not densify. 
(with some effort I suppose you could do a custom transpose based on our internal sparse index + values, but that might need some contributed effort)

**Comment by asistradition** [comment]
I chose to do that in the short term:

`pd.DataFrame.sparse.from_spmatrix(df.sparse.to_coo().transpose(), index=df.columns, columns=df.index)`

It profiles to have about the same runtime as going through a dense array for anything that's 50%> sparse with the memory usage decreasing accordingly as it gets more sparse. I'm going to close this.
