### ISSUE TITLE
DEPR: Deprecate numpy argument in read_json

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#28512]
I've never really been clear on the purpose of the `numpy` argument in to_json. Some digging brought me here https://github.com/pandas-dev/pandas/pull/3876#issuecomment-19390383 where it is explained that this maintains some kind of sequence to elements. To illustrate the only difference I could find

```python
>>> pd.read_json('[{"a": 1, "b": 2}, {"b":2, "a" :1}]',numpy=False, orient='records')
   a  b
0  1  2
1  1  2

>>> pd.read_json('[{"a": 1, "b": 2}, {"b":2, "a" :1}]',numpy=True, orient='records')
   a  b
0  1  2
1  2  1
```

I might be missing the point but I don't understand why this would be useful. Objects in JSON are by definition not ordered, so this is non-compliant and I think just plain confusing.

So I think good to deprecate unless anyone has objections.

**Comment by WillAyd** [comment]
Should also note there are not tests that I can see that actually test `numpy=True` making any kind of difference

**Comment by lucaionescu** [comment]
Hi, I'd like to work on this one. What would be the best way to go? Removing the argument from the function and adding a deprecation warning to the next release notes?

**Comment by WillAyd** [comment]
Yea you should be able to apply the `decorate_kwarg` decorator to read_json:

https://github.com/pandas-dev/pandas/blob/bd8dbf906e4352567094637c9c824c350dae3ad2/pandas/util/_decorators.py#L104

And then update tests in pandas.tests.io.json . Right now this argument is used for parametrization but doesn't actually change anything, so could probably just remove parametrization

**Comment by WillAyd** [comment]
Don't remove the argument yet though just add warning

**Comment by alimcmaster1** [comment]
@WillAyd 

According to user_guide/io.rst there are also some performance considerations.

Are we still good to deprecate do you think?

```
If ``numpy=True`` is passed to ``read_json`` an attempt will be made to sniff
an appropriate dtype during deserialization and to subsequently decode directly
to NumPy arrays, bypassing the need for intermediate Python objects.

This can provide speedups if you are deserialising a large amount of numeric
data:
```
```python
   randfloats = np.random.uniform(-100, 1000, 10000)
   randfloats.shape = (1000, 10)
   dffloats = pd.DataFrame(randfloats, columns=list('ABCDEFGHIJ'))
   jsonfloats = dffloats.to_json()
   
   pd.read_json(jsonfloats) 
   pd.read_json(jsonfloats, numpy=True)
```

**Comment by WillAyd** [comment]
Yea should still deprecate
