### ISSUE TITLE
WEB: Improve new website styles

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#28519]
The css of the new website needs some care. I think there are two separate things:
- General styles (headers, paragraphs, code blocks...)
- Home page

And I see the next options to move forward:
- We do it ourselves
- The designer donated by Indeed propose a style (send us an image on how the website needs to look like) and we implement it
- We hire a designer to implement the changes to the css (they can implement the design, or we can still ask the designer from Indeed to propose one)

**Comment by jorisvandenbossche** [comment]
Yes, I think this are indeed the three options. To start doing anything concrete, we should probably wait on the new logo? I think it would be useful to have the designer of Indeed to create some images of how things can look. 
Then, I am personally in favor of trying to hire someone to do this properly.

**Comment by datapythonista** [comment]
I'm spending a bit of time on making things look a bit better than with the bootstrap defaults. Something very basic, but I think getting the easy gains will help us decide what's best later.

**Comment by datapythonista** [comment]
I think we're happy enough with the website for now. Closing this, we can always open new issues for more specific actions.
