### ISSUE TITLE
BUG: groupby quantile fails with multiple quantiles

### ISSUE THREAD

**Issue by Connossor** [pandas-dev/pandas#28525]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

df = pd.DataFrame({'grp': [1, 1, 2, 2],
                   'x': [1, 2, 3, 4]})

print(df.groupby(['grp']).quantile([.2, .4]))

```
#### Problem description

The quantile aggregation accepts a parameter `q` which which be a single quantile, or an array of multiple quantiles. According to the [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.DataFrameGroupBy.quantile.html) q should be "float or array-like".

Since the update to 0.25.0, I get a TypeError when q is a list or array.

#### Expected Output ( 0.24.2 )

```
           x
grp         
1   0.2  1.2
    0.4  1.4
2   0.2  3.2
    0.4  3.4
```

#### Error traceback ( 0.25.0 )

```

TypeErrorTraceback (most recent call last)
<ipython-input-1-b8366902885c> in <module>
      4                    'x': [1, 2, 3, 4]})
      5 
----> 6 print(df.groupby(['grp']).quantile([.2, .4]))

~/.conda/envs/bifrost-test-pandas25/lib/python3.7/site-packages/pandas/core/groupby/groupby.py in quantile(self, q, interpolation)
   1906             post_processing=post_processor,
   1907             q=q,
-> 1908             interpolation=interpolation,
   1909         )
   1910 

~/.conda/envs/bifrost-test-pandas25/lib/python3.7/site-packages/pandas/core/groupby/groupby.py in _get_cythonized_result(self, how, grouper, aggregate, cython_dtype, needs_values, needs_mask, needs_ngroups, result_is_index, pre_processing, post_processing, **kwargs)
   2246                 func = partial(func, ngroups)
   2247 
-> 2248             func(**kwargs)  # Call func to modify indexer values in place
   2249 
   2250             if result_is_index:

pandas/_libs/groupby.pyx in pandas._libs.groupby.group_quantile()

TypeError: must be real number, not list

```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-862.14.4.el7.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.0
numpy            : 1.16.5
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.2
setuptools       : 41.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.8.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by TomAugspurger** [comment]
Fixed on master. We're doing a 0.25.2 release soonish with this fixed.

**Comment by Connossor** [comment]
Thanks @TomAugspurger for the very speedy response!
