### ISSUE TITLE
read_excel with opened data set

### ISSUE THREAD

**Issue by bgarbin** [pandas-dev/pandas#28526]
My issue is partially reported here:
https://stackoverflow.com/questions/57993351/unicodedecodeerror-cant-decode-byte-solved-by-writing-and-reading-with-panda

Ultimately I would like to use pandas.read_excel on already opened data (without having to save on the disk and re-open).

Tracing it into panda's depth I found that adding a test in excel.ExcelFile __init__ method was doing the trick.

```python
        if engine == 'xlrd' and isinstance(io, xlrd.Book):
            self.book = io
        elif not isinstance(io, xlrd.Book) and hasattr(io, "read"):
            # N.B. xlrd.Book has a read attribute too
            data = io.read()
            self.book = xlrd.open_workbook(file_contents=data)
        **elif not isinstance(io, xlrd.Book) and not hasattr(io, "read"):
            # N.B. xlrd.Book has no read attribute
            self.book = xlrd.open_workbook(file_contents=io)**
        elif isinstance(io, compat.string_types):
            self.book = xlrd.open_workbook(io)
        else:
            raise ValueError('Must explicitly set engine if not passing in'
                             ' buffer or path for io.')
```
Is there any other way to do it?

Thanks in advance for your help.

**Comment by WillAyd** [comment]
When you say `opened data` do you just mean bytes? If so I think very unlikely to support, but you can always open once with the `ExcelFile` object and reuse for reads from there

**Comment by bgarbin** [comment]
Yes, I mean bytes.
Actually, I am using pandas' powerful decoding functions (in xlrd) to decode acquired data. I would like to avoid writing the data to the disk to speed up the process and I  am not re-using the same data after but acquiring new ones.

**Comment by WillAyd** [comment]
Any chance you can get the same to work with `openpyxl`? `xlrd` is no longer maintained and the previous maintained has asked us a few times to remove it from pandas, so we aren't likely to add features that rely on `xlrd` implementation details

**Comment by bgarbin** [comment]
I don't know ```openpyxl``` yet. Do you have any idea on where to start from my side?

**Comment by WillAyd** [comment]
I don't know how to tackle your specific use case, but openpyxl is the only library we support for both read and write so there should be some kind of mechanisms in there to do both

**Comment by WillAyd** [comment]
As mentioned above I don't think we will add support for things you can do with `xlrd` internals so going to close - if you see the same issue pop up with other engines though ping and can certainly reopen.
