### ISSUE TITLE
Pip installation instruction wrong on Pandas homepage

### ISSUE THREAD

**Issue by dauntilus** [pandas-dev/pandas#28536]
On https://pandas.pydata.org under the `v0.25.1 Final (August 22, 2019)` heading, the PyPi installation link is

`python -m pip install –upgrade pandas`

The double hyphen in front of `upgrade` got converted to `'\u2013'` and pasting that into a terminal does not work.

**Comment by TomAugspurger** [comment]
Thanks. That's over at https://github.com/pandas-dev/pandas-website/blob/master/latest.rst if you're interested in updating it.

**Comment by TomAugspurger** [comment]
Closed by https://github.com/pandas-dev/pandas-website/pull/83 and updated.
