### ISSUE TITLE
CI: Move last builds from Travis to Azure

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#28545]
I think this makes sense, and it will simplify things having a single CI system.

If I'm not missing anything, there are few challenges:
- The number of jobs (I think we should get 10 extra concurrent jobs in Azure, since the CI is ok but will be too slow)
- Setting up databases in Azure (I think we currently set up Postgres and MySQL, and may be in the future we want SQL server too #9097)
- I think we have some encrypted stuff in azure for GBQ (probably can be easily moved to Azure secrets)

If there is any objection, let me know, otherwise I'll move forward with this.

CC: @bhavaniravi

**Comment by WillAyd** [comment]
I am +1 on this

**Comment by jbrockmendel** [comment]
Update on this?  Has maintaining Travis been burdensome?

**Comment by jreback** [comment]
azure has better visibility on individual builds and we have more capacity but this is not so burdensome anymore

also travis does things that are hard in azure: databases, 3.9

so ok to close

**Comment by simonjayhawkins** [comment]
travis-ci.org will be officially closed down completely on December 31st, 2020 https://docs.travis-ci.com/user/migrate/open-source-repository-migration see https://github.com/MacPython/pandas-wheels/pull/99#issuecomment-692193092

**Comment by jreback** [comment]
how is this relevant @simonjayhawkins 

travis ci already has access to all of the repos - has been the case since the very beginning and we can migrate trivially 

i am not sure why numpy is having an issue

this issue itself is about moving off of travis - which we cannot do as i outlines in a prior comment, nor is there a good reason

**Comment by simonjayhawkins** [comment]
right. closing again.
