### ISSUE TITLE
pd.read_json With convert_axes Produces Different Index Type than Empty Frame

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#28558]
Another edge case brought up by #28510 . I'm not sure if we have a definite stance on this and there are probably a few other issues that are similar, though couldn't find anything exactly matching this

Note the index types for an empty data frame

```python
>>> df = pd.DataFrame()
>>> df.index
Index([], dtype='object')
>>> df.columns
Index([], dtype='object')
```

In `read_json` with `convert_axes` the axes labels end up with a different dtype

```python
>>> for orient in ["columns", "index", "records", "values", "split"]:
...     print(pd.read_json("{}", orient=orient, convert_axes=True).columns)
...
Float64Index([], dtype='float64')
Float64Index([], dtype='float64')
Float64Index([], dtype='float64')
Float64Index([], dtype='float64')
Float64Index([], dtype='float64')
```

**Comment by mroeschke** [comment]
This looks to match the empty case now. Could use a test

**Comment by mcgeestocks** [comment]
@mroeschke I could take that. I'm on the hunt for a good first issue, test writing seems like a great place to start.
