### ISSUE TITLE
pd.read_json May Not Maintain Numeric String Index

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#28556]
```python
>>> df = pd.DataFrame(range(3), index=list("123"))
>>> df.to_json(orient="split")
'{"columns":[0],"index":["1","2","3"],"data":[[0],[1],[2]]}'
>>> pd.read_json(df.to_json(orient="split"), orient="split").index
Int64Index([1, 2, 3], dtype='int64')
```

Note that the string nature of the values should be preserved via roundtrip here, but ends up being lossy anyway. Noted during refactor of #28510

**Comment by jmg7173** [comment]
Can I work on this issue?

**Comment by jmg7173** [comment]
The reason why `pd.read_json` converts dtype of `object` index into `int64` is as belows.
https://github.com/pandas-dev/pandas/blob/f08a1e62e31fc11e7e5bd7bec72b7e6d86473423/pandas/io/json/_json.py#L916-L923

Do we need to convert `object` typed data as coarsed type like `float`, `int64` and so on?

If I comment out this line, it breaks tests so much.

**Comment by jmg7173** [comment]
How about change default value of `convert_axes` as `False` at this condition of `read_json`?

https://github.com/pandas-dev/pandas/blob/c4de906a1068ffb00bdc613bfcecaa92d9687e42/pandas/io/json/_json.py#L580-L581

**Comment by sathyz** [comment]
@jmg7173 are you still looking at this?

**Comment by scratchmex** [comment]
I'm sorry but, why the strings values should be preserved by default? It isn't more comfortable to parse string numbers as integers?

**Comment by jmg7173** [comment]
@sathyz No, you can take this issue.

**Comment by theoniko** [comment]
As far as i understood mainting string index means expected output Index(['1', '2', '3'], dtype='object').
What about adding     

>    if axis_name == "index":
>                 continue

after line 852 since we only need to preserve the index type? Does you agree with this solution?

https://github.com/pandas-dev/pandas/blob/e744559585d689bd3c60cfe57c7c97609412f516/pandas/io/json/_json.py#L852-L855

**Comment by theoniko** [comment]
Hello @WillAyd,
Would it be possible to review my pr and give feedback? 
Thanks in advace.
