### ISSUE TITLE
DataFrame[list[Series[datetime64ns, tz]]] drops timezone information

### ISSUE THREAD

**Issue by Koojav** [pandas-dev/pandas#28552]
#### Code Sample, a copy-pastable example if possible

```
s = pd.Series([pd.to_datetime('2018-10-08 13:36:45+00:00')])


Output:
0   2018-10-08 13:36:45+00:00
dtype: datetime64[ns, UTC]
```

```
pd.DataFrame([s]).min()


Output:
0   2018-10-08 13:36:45
dtype: datetime64[ns]
```

#### Problem description

When using `DataFrame().min()` method timezone information gets removed but it should remain untouched just like when using `Series().combine(...,min)`. Example:

```
s.combine(s, min)


Output:
0   2018-10-08 13:36:45+00:00
dtype: datetime64[ns, UTC]
```

#### Expected Output
```
0   2018-10-08 13:36:45+00:00
dtype: datetime64[ns, UTC]
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-64-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.0
numpy            : 1.17.0
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.1
setuptools       : 40.6.3
Cython           : 0.27.3
pytest           : 3.0.7
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.2.6
html5lib         : None
pymysql          : None
psycopg2         : 2.7.3.2 (dt dec pq3 ext lo64)
jinja2           : 2.10
IPython          : 7.2.0
pandas_datareader: None
bs4              : 4.6.3
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.2.6
matplotlib       : 2.0.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : 0.11.0
pyarrow          : 0.13.0
pytables         : None
s3fs             : None
scipy            : 1.0.0
sqlalchemy       : 1.3.7
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by randomstuff** [comment]
Actually this, is the `DataFrame` creation which is dropping timezone, not `min()`:

```python
import pandas as pd
s = pd.Series([pd.to_datetime('2018-10-08 13:36:45+00:00')])
print(pd.DataFrame([s])[0])
# => 0   2018-10-08 13:36:45
# => Name: 0, dtype: datetime64[ns]
```

**Comment by randomstuff** [comment]
But this works fine:

```python
pd.DataFrame({"x":s}).min()
# => x   2018-10-08 13:36:45+00:00
# => dtype: datetime64[ns, UTC]
```

**Comment by mroeschke** [comment]
This looks fixed on master and could use a test:

```
In [12]: print(pd.DataFrame([s])[0])
0   2018-10-08 13:36:45+00:00
Name: 0, dtype: datetime64[ns, UTC]

In [13]: print(pd.DataFrame([s])[0].dt.tz)
UTC

In [14]: pd.__version__
Out[14]: '1.1.0.dev0+1027.g767335719.dirty'
```

**Comment by dair-targ** [comment]
What timezone should be used for, let's say, `mean` if the series contains datetimes with different timezones?

**Comment by jreback** [comment]
you should convert to UTC if interoperating between time zones
