### ISSUE TITLE
Pandas Enhancement Proposals?

### ISSUE THREAD

**Issue by h-vetinari** [pandas-dev/pandas#28568]
I was wondering if there has been discussion about having dedicated RFC / Proposals for larger changes to pandas? 

For example, after a rather heated discussion in #24046, @wesm [asked](https://github.com/pandas-dev/pandas/issues/24046#issuecomment-515492965):
> I question whether GitHub issues was the appropriate venue for this discussion compared with some form of RFC / design document.

I wanted to come back to this and maybe write such a design document, and therefore wanted to check what the thoughts of the core team are about this? Needless to say, the obvious candidates to model this after would be Python's [PEPs](https://www.python.org/dev/peps/) or NumPy's [NEPs](https://numpy.org/neps/), but maybe there could/should be pandas-specific departures.

I think this could benefit several high-impact design questions (e.g. around extension arrays or release plans). Actually, I have 2-3 other bigger PRs that eventually stalled in design discussion (and a few ideas of similar magnitude), where I could imagine that such a vessel would help move the discussion forward.

**Comment by TomAugspurger** [comment]
We have a new section in our roadmap that I think covers this: https://dev.pandas.io/docs/development/roadmap.html#roadmap-evolution

**Comment by h-vetinari** [comment]
> That proposal may then be submitted as a GitHub issue

In the case of #24046, it was exactly this point that was in question, and why I opened this issue here. I admit I hadn't seen that section about the roadmap/evolution, but the question remains (to me): has some more formal process been considered? I think pandas is big enough to warrant it.

The way I see it, there's a flood of issues and PRs, and with scarce core-dev resources, any given issue PR will mostly only receive as much attention as is absolutely necessary (which is fine; no judgement about that). But this means that for larger topics, it's very hard to fully lay out a proposal and discuss its merits, because people jump into threads (that get longer and longer) at different points, and it's way too easy to get caught up in discussions about semantics or other side issues, so that eventually, it's very hard to keep track of what the status is, and people spend their scarce time elsewhere.

A PEP-like format could take a longer approach, where feedback is requested on the whole proposal, and not just the latest comment on the GH issue. Maybe I'm too naive about how this would work out, but it seems to work reasonably well for PEPs/NEPs.

Don't get me wrong, live would go on without PAEPs, but I'd be more hesitant about investing my time for (re-)running the gauntlet in the format that has failed (from my POV) several times already.

**Comment by TomAugspurger** [comment]
You can check the discussion on the roadmap PR where the evolution process was discussed a bit. I'm not sure what all was proposed as alternatives to design issues.

**Comment by toobaz** [comment]
PEPs/NEPs are not a bad thing in absolute, clearly, but I don't see how they would increase the free time of devs, which is the real scarce thing. If any, a new procedure will increase the burden.

@h-vetinari You start from the assumption that #24046 would have benefited from more attention from the devs, but it really got a lot.

Something I would be happy to recommend would be, in any API-related issue, a comment (e.g., the second of the discussion) which is always updated to reflect the status of the current proposal(s). But I wouldn't make the process more formal than this.

I perfectly understand the frustration when you feel you have wasted time. The way I (slowly learned to) try to avoid this in my pandas contributions which affect user behaviour is i) first discuss, then propose a PR ii) try to proceed one step at a time (first settle one point, then another). There are plenty of issues on github that require limited discussion: some instead do - and notice they are not necessarily more important, they are just more complicated.
