### ISSUE TITLE
Getting KeyError when accessing one row by string in a DateTimeIndex with 1 element

### ISSUE THREAD

**Issue by rp-alevato** [pandas-dev/pandas#28565]
#### Brief Description
I'm getting a KeyError when trying to access a row by string in a DateTimeIndex. This only happens if I use 'YYYY-MM-DD HH:MM:SS' format. If I use 'YYYY-MM-DD' it works. Also if I add another element before accessing using the more complete format the exception vanishes. This will get more clear with the codes below.

#### Testing Code
```python
import pandas as pd

example = pd.DataFrame(columns=['Date', 'Price', 'Amount'])
example = example.set_index('Date')
example.loc[pd.to_datetime('2019-09-19 23:00:10')] = [100, 200]
print('Checking the value was added')
print(example)
print('\nNow I try to access by index')
print(example['2019-09-19 23:00:10'])
```
#### Expected Output
```bash
Checking the value was added
                    Price Amount
Date                            
2019-09-19 23:00:10   100    200

Now I try to access by index
                    Price Amount
Date                            
2019-09-19 23:00:10   100    200
```
#### Error Output
```bash
Checking the value was added
                    Price Amount
Date                            
2019-09-19 23:00:10   100    200

Now I try to access by index
Traceback (most recent call last):
  File "/home/rpa/anaconda3/envs/datas/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '2019-09-19 23:00:10'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testing_error_pandas.py", line 10, in <module>
    print(example['2019-09-19 23:00:10'])
  File "/home/rpa/anaconda3/envs/datas/lib/python3.7/site-packages/pandas/core/frame.py", line 2980, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/rpa/anaconda3/envs/datas/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '2019-09-19 23:00:10'
```

However if I use 'YYYY-MM-DD' like in the code below it works fine.

```python
import pandas as pd

example = pd.DataFrame(columns=['Date', 'Price', 'Amount'])
example = example.set_index('Date')
example.loc[pd.to_datetime('2019-09-19 23:00:10')] = [100, 200]
print('Checking the value was added')
print(example)
print('\nNow I try to access by index')
print(example['2019-09-19'])
```

Also if I add another entry before checking the first condition, it also works fine like in the code below.

```python
import pandas as pd

example = pd.DataFrame(columns=['Date', 'Price', 'Amount'])
example = example.set_index('Date')
example.loc[pd.to_datetime('2019-09-19 23:00:10')] = [100, 200]
example.loc[pd.to_datetime('2019-09-19 17:45:20')] = [50, 75]
print('Checking the value was added')
print(example)
print('\nNow I try to access by index\n')
print(example['2019-09-19 23:00:10'])
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.4.0-53-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.16.5
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.2
setuptools       : 41.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by koushikgk** [comment]
Hey @rp-alevato Is anyone working on this? If not I would  like to. Thanks!

**Comment by mroeschke** [comment]
Go for it @koushikgk!

**Comment by jbrockmendel** [comment]
AFAICT the case where this raises is correct, and the case where it doesn't raise are incorrect.

`example[key]` should be doing a lookup on _columns_, to do any kind of indexing with a datetime-like string you should need to do `example.loc[key]`.

A corollary wrong-looking behavior is `example.loc[:, key[:-3]]` which incorrectly returns `example.loc[key[:-3]]`

**Comment by jbrockmendel** [comment]
... or maybe this behavior is intentional.  `example[key[:-3]]` goes down the path in `DataFrame.__getitem__`:

```
        # Do we have a slicer (on rows)?
        indexer = convert_to_index_sliceable(self, key)
        if indexer is not None:
            # either we have a slice or we have a string that can be converted
            #  to a slice for partial-string date indexing
            return self._slice(indexer, axis=0)
```

**Comment by jbrockmendel** [comment]
This usage is deprecated

**Comment by mroeschke** [comment]
Closing as indexing with a date-like string like this is deprecated
