### ISSUE TITLE
Inconsistent SettingWithCopyWarning

### ISSUE THREAD

**Issue by TonyCongqianWang** [pandas-dev/pandas#28581]
#### Code Sample, a copy-pastable example if possible

```
import os, io, math
import numpy as np, pandas as pd

performance_df = pd.DataFrame()
performance_df["GAP"] = np.random.randn(75)
performance_df["SETTINGS"] = [['default', 'MLrank', 'MLselect'][int(i/25)] for i in range(75)]
performance_df["INSTANCE_NAME"] = [i%25 for i in range(75)]


performance_df = pd.read_csv("/home/twang/Ausarbeitung/rootperformance.csv", header=0)

default_df = performance_df[performance_df["SETTINGS"].str.match('default')]
rank_df = performance_df[performance_df["SETTINGS"].str.match('MLrank')]
select_df = performance_df[performance_df["SETTINGS"].str.match('MLselect')]

compare_df = default_df.drop(["SETTINGS"], axis=1).merge(
                                  rank_df.drop(["SETTINGS"], axis=1), on=["INSTANCE_NAME"], validate="1:1", suffixes=("","_MLrank")).merge(
                                  select_df.drop(["SETTINGS"], axis=1), on=["INSTANCE_NAME"], validate="1:1", suffixes=("_default","_MLselect") ).copy(deep=True)




gap_compare = compare_df.query("GAP_default<=9e19 and GAP_MLrank<=9e19", inplace=False)#.copy(deep=True)


gap_compare.loc[:,("GAP_MLselect")] = gap_compare.loc[:,["GAP_MLselect"]].where(gap_compare["GAP_MLselect"].values.reshape(-1,1) <= 9e19, np.random.randn(gap_compare.shape[0], 1), inplace=False, axis=0)
```

#### Problem description
I receive a SettingWithCopyWarning when loading the dataframe from my csv. But creating the df doesn't trigger a warning. I would expect it to be indifferent whether I load a csv or create df in python.  Using deep copy at the second place, prevents the warning. But the first deep copy doesn't.

**Comment by mroeschke** [comment]
Appears that this example isn't fully reproducible (the csv is not available). We've also had several issues about this warning and are moving toward a copy-on-write model which should hopefully alleviate this in a future version. Closing.

**Comment by matt-barker94** [comment]
Hi,

I've just encountered a similar issue with DataFrame.query, here's an MWE on pandas 1.3.4
`
import pandas as pd
df = pd.DataFrame([[1, 2, 3], [4, 5, 6]], columns=['A', 'B', 'C'])
df1 = df.query('A < 2') # According to docs this should return a copy
df2 = df.query('A > 2') # According to docs this should return a copy

df1['A'] = df1['A'] / df2['A']  # Throws SettingWithCopyWarning 
`

The SettingWithCopy warning is thrown even if I add `.copy()` to `df1['A'] / df2['A']`
The SettingWithCopyWarning is not thrown if I add `.copy()` to `df.query('A < 2')` and `df.query('A > 2')`, but I don't want to sprinkle my code with `.copy()` everywhere.

**Comment by MarcoGorelli** [comment]
@matt-barker94 this looks expected - `df1` is a copy, and `df['A']` is a slice of a copy.

You can either add `.copy` when you create `df1`, or silence the warning

**Comment by matt-barker94** [comment]
Ahh okay, I think I need to wrap my head around SettingWithCopy - I was thinking that if I had defined `df1` and knew it was a copy of a previous data frame, then setting something in `df1` itself shouldn't throw the warning? 

Thanks for the help though, I'm currently trying to minimise the number of times I explicitly have to `.copy` a data frame when I create a new one by manipulating an existing frame.
