### ISSUE TITLE
DOC: do we want type hints in signature on API pages?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#28585]
With the type hints that are being added in a lot of places, the question comes up if we want to have them in the docs.

Currently, this actually happens. See eg https://dev.pandas.io/docs/reference/api/pandas.DataFrame.to_string.html#pandas.DataFrame.to_string

![image](https://user-images.githubusercontent.com/1020496/65465611-080e7200-de5d-11e9-8866-a43de6bfc046.png)

But personally, I am not sure the having the type hints in the signature like above is an improvement. It makes the signature very hard to read and interpret, while we (in principle) already have the type information in textual form in the Parameter listing.

**Comment by WillAyd** [comment]
I think these are good to have; serving as a form of documentation is one of the motivators for annotations

**Comment by TomAugspurger** [comment]
Closing in favor of https://github.com/pandas-dev/pandas/issues/33025, which has a couple links to workarounds.
