### ISSUE TITLE
Allow users to pass backend option to `.plot()`

### ISSUE THREAD

**Issue by jsignell** [pandas-dev/pandas#28619]
Once you have installed another plotting library with a pandas.plotting entrypoint it would be nice to be able to toggle back and forth between different backends even within on session.

## What currently exists
```python
pd.options.plotting.backend = 'holoviews'
```

## Proposed additional API

```python
df.plot(backend='holoviews')

```

This would be particularly useful when a particular backend doesn't support a certain type of plot, or you need to use a backend to get some specific functionality but don't want to use if for your whole notebook.
 
@datapythonista - @TomAugspurger mentioned that you might have opinions on this.

**Comment by datapythonista** [comment]
I'm ok with this, sounds reasonable.
