### ISSUE TITLE
combine_first changes datatype

### ISSUE THREAD

**Issue by mohitanand001** [pandas-dev/pandas#28613]
```python
df_1 = pd.DataFrame(data = {'A' : [1, 2, 3], 'B' : [4, 5, 6]})
df_2 = pd.DataFrame(data = {'A' : [1, 20, 30], 'B' : [40, 50, 60], 'C' : [12, 34, 65]})
df_1.combine_first(df_2).dtypes
A      int64
B      int64
C    float64
dtype: object
```
#### Problem description

The combine_first changes the datatype of the the column C to float64 from int64. Is this
an expected behavior

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.1.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.0
numpy            : 1.16.2
pytz             : 2018.7
dateutil         : 2.7.5
pip              : 18.1
setuptools       : 40.6.3
Cython           : 0.29.2
pytest           : 4.0.2
hypothesis       : None
sphinx           : 1.8.2
blosc            : None
feather          : 0.4.0
xlsxwriter       : 1.1.2
lxml.etree       : 4.2.5
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.8.3 (dt dec pq3 ext lo64)
jinja2           : 2.10
IPython          : 7.2.0
pandas_datareader: None
bs4              : 4.6.3
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.2.5
matplotlib       : 3.0.2
numexpr          : 2.6.8
odfpy            : None
openpyxl         : 2.5.12
pandas_gbq       : None
pyarrow          : 0.13.0
pytables         : None
s3fs             : None
scipy            : 1.1.0
sqlalchemy       : 1.2.15
tables           : 3.4.4
xarray           : None
xlrd             : 1.0.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.2
</details>

**Comment by thirug13** [comment]
@mroeschke I would like to work on this issue. Is this issue suitable for 1st time contributors and if so, could I get more more details on the problem and suggestions on how to fix the issue?

**Comment by mroeschke** [comment]
We have a `good first issue` label that indicates issues that are good for first time contributors

https://github.com/pandas-dev/pandas/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by mroeschke** [comment]
This looks fixed on master. Could use a test

```
In [6]: df_1 = pd.DataFrame(data = {'A' : [1, 2, 3], 'B' : [4, 5, 6]})
   ...: df_2 = pd.DataFrame(data = {'A' : [1, 20, 30], 'B' : [40, 50, 60], 'C' : [12, 34, 65]})
   ...: df_1.combine_first(df_2).dtypes
Out[6]:
A    int64
B    int64
C    int64
dtype: object
```

**Comment by goyal-aman** [comment]
@mroeschke I would like to work on it. Though this would be my first contribution. Can you suggest how to go about doing this?

**Comment by goyal-aman** [comment]
@mroeschke Hi, does this make any sense?
`    
def test_combine_first_dtype_stay_same_int(self):
        df_1 = pd.DataFrame(data = {'A' : [1, 2, 3], 'B' : [4, 5, 6]})
        df_2 = pd.DataFrame(data = {'A' : [1, 20, 30], 'B' : [40, 50, 60], 'C' : [12, 34, 65]})
        result = df_1.combine_first(df_2)

        exp = pd.DataFrame(data = {
            'A':[1, 2, 3],
            'B':[4, 5, 6], 
            'C':[12, 34, 65]
        })        
        tm.assert_equal(result.dtypes, exp.dtypes)
`
