### ISSUE TITLE
dataframe index not showing up bold after conda update

### ISSUE THREAD

**Issue by rdmtinez** [pandas-dev/pandas#28620]
```python
import numpy as np
import pandas as pd
%config InteractiveShell.ast_node_interactivity='all'

df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))

df

```
#### Problem description

During my work today I decided to update conda when I started getting some random errors which I can't recall anymore. After the update I noticed that the indeces in the printouts of my dataframes were no longer bold. Its not a big deal, buts it is visually unappealing. If possible I'd like to fix this (if it is an issue with pandas), but I've never contributed a fix to anything before :) and I don't even know where to start hunting for the bug. 

#### Expected Output

Indeces should be bold, just like column names---at least they've always were before the conda update.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.0.0-29-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.16.5
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : 0.29.13
pytest           : 5.1.2
hypothesis       : None
sphinx           : 2.2.0
blosc            : None
feather          : None
xlsxwriter       : 1.2.1
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 2.6.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.3.8
tables           : 3.5.2
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.1
</details>

**Comment by WillAyd** [comment]
I'm not sure pandas would have done this (AFAIK something like this was asked in #18066 but never implemented) - are you sure it wasn't a third party library?

**Comment by rdmtinez** [comment]
I looked up information about styling which is what that thread is about, but I'm interested in styling specific values or the index itself besides having it bold. I imagine I can do it myself with the resources I found online, but that would mean extra lines of code every time i start a new notebook. I also don't think it was done in pandas, but I'm not sure where to begin looking for the 'bug'. I can't find the pandas resource for manipulating the DataFrame construction.... anyone, anyone

**Comment by alan-barzilay** [comment]
I'm having the same problem on my clean OS install. I'm currently in a fresh venv virtual environment  and installed everything through pip.
Would also love to help but not sure where to start hunting for this 'bug'

<details><summary>Details</summary>
<p>
 

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-65-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.17.2
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 9.0.1
setuptools       : 39.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 0.999999999
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.8.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
</p>
</details>

**Comment by jolespin** [comment]
I'm also having this same problem.  I'll post my environment tomorrow when I get to lab.

**Comment by rdmtinez** [comment]
After I opened this issue, I had to go back and reinstall my environment to include updates. I'm fairly certain there were some dependency issues, but I just didn't have the time to hunt the bug. I'm closing this issue as I don't think its due to pandas.
