### ISSUE TITLE
BUG: DataFrame.reindex not following limit - 方法参数的错误

### ISSUE THREAD

**Issue by french-home** [pandas-dev/pandas#28631]
Python版本: 3.6.5
版本:pandas == 0.24.2
```python
import pandas as pd

Data = [
    ["A", "A", "A"],
    ["B", "B", "B"],
    ["C", "C", "C"],
    ["D", "D", "D"],
]
test1 = pd.DataFrame(Data)
print(test1)
print("------------")
test1 = test1.reindex([0, 1, 2, 3, 4, 5], method="ffill", limit=1)
print(test1)
```
![reindex_bug](https://user-images.githubusercontent.com/10058240/65697799-f4782c80-e051-11e9-9c5d-0bf303535d54.png)

limit参数限制数据继续向后填充

版本:pandas==0.25.1
```python
import pandas as pd

Data = [
    ["A", "A", "A"],
    ["B", "B", "B"],
    ["C", "C", "C"],
    ["D", "D", "D"],
]
test1 = pd.DataFrame(Data)
print(test1)
print("------------")
test1 = test1.reindex([0, 1, 2, 3, 4, 5], method="ffill", limit=1)
print(test1)
```
![reindex_bug_2](https://user-images.githubusercontent.com/10058240/65697820-fc37d100-e051-11e9-9fd3-6fedb7c12c61.png)

limit参数并没有限制数据继续向后填充

**Comment by 0xF4D3C0D3** [comment]
speak in English, please?

**Comment by datapythonista** [comment]
谢谢 @french-home for reporting this. It'd be very useful if you can provide what's the output in both versions. Thanks!

**Comment by french-home** [comment]
Can I send it to you by mail?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Marc Garcia"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月26日(星期四) 晚上10:02
收件人:&nbsp;"pandas-dev/pandas"<pandas@noreply.github.com&gt;;
抄送:&nbsp;"French"<1109527533@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [pandas-dev/pandas] BUG DataFream.rindex方法参数的错误 (#28631)




谢谢 @french-home for reporting this. It'd be very useful if you can provide what's the output in both versions. Thanks!

**Comment by datapythonista** [comment]
Isn't it easier to simply copy it in a comment here? You can send it by email if that's a problem, but I think that can be easier.

**Comment by french-home** [comment]
Due to regional restrictions, it is difficult to access Github in China, so I can only send it to you by email.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Marc Garcia"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月26日(星期四) 晚上10:18
收件人:&nbsp;"pandas-dev/pandas"<pandas@noreply.github.com&gt;;
抄送:&nbsp;"French"<1109527533@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [pandas-dev/pandas] BUG DataFream.rindex方法参数的错误 (#28631)




Isn't it easier to simply copy it in a comment here? You can send it by email if that's a problem, but I think that can be easier.

**Comment by datapythonista** [comment]
Sure, please send it to garcia.marc@gmail.com and I'll update the description for you.

**Comment by french-home** [comment]
I have sent the question to the email address you provided, please check it out!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Marc Garcia"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月26日(星期四) 晚上10:22
收件人:&nbsp;"pandas-dev/pandas"<pandas@noreply.github.com&gt;;
抄送:&nbsp;"French"<1109527533@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [pandas-dev/pandas] BUG DataFream.rindex方法参数的错误 (#28631)




Sure, please send it to garcia.marc@gmail.com and I'll update the description for you.

**Comment by datapythonista** [comment]
Thanks a lot @french-home, it does look like a bug. I updated the description with your output, will have a look to see what's wrong when I have time.

Thanks for reporting it. If you'd like to research what's the problem yourself, and you need help with that, please let me know, happy to help.

**Comment by jorisvandenbossche** [comment]
So to make it a bit more explicit. Older versions correctly apply the "limit"

```
In [8]: pd.__version__  
Out[8]: '0.24.2'

In [9]: test1.reindex([0, 1, 2, 3, 4, 5], method="ffill", limit=1)
Out[9]: 
     0    1    2
0    A    A    A
1    B    B    B
2    C    C    C
3    D    D    D
4    D    D    D
5  NaN  NaN  NaN
```

while 0.25 / master does not:

```
In [22]: pd.__version__   
Out[22]: '0.26.0.dev0+418.g1cfba0a87'

In [23]: test1.reindex([0, 1, 2, 3, 4, 5], method="ffill", limit=1)
Out[23]: 
   0  1  2
0  A  A  A
1  B  B  B
2  C  C  C
3  D  D  D
4  D  D  D
5  D  D  D
```

So this is a regression.

**Comment by jorisvandenbossche** [comment]
So this boils down to `RangeIndex.get_indexer` no longer taking the limit keyword into account:

```
In [42]: idx = pd.Index(range(4))                                                                                                                                                                                  

In [43]: target = pd.Index([0, 1, 2, 3, 4, 5])                                                                                                                                                                     

In [44]: idx.get_indexer(target, method='pad', limit=1)                                                                                                                                                            
Out[44]: array([0, 1, 2, 3, 3, 3])
```
while the last element in that result should be -1.

This seems to be cause by https://github.com/pandas-dev/pandas/pull/27119 (cc @toobaz )

**Comment by toobaz** [comment]
> This seems to be cause by #27119 (cc @toobaz )

Definitely. I forgot to forward the ``limit`` argument here:
https://github.com/pandas-dev/pandas/blob/e9f6f6ba09fa6c817026e3805731542790bb969d/pandas/core/indexes/range.py#L354
