### ISSUE TITLE
AttributeError: 'Categorical' object has no attribute '_ordered'

### ISSUE THREAD

**Issue by jorwoods** [pandas-dev/pandas#28640]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
x = pd.Series(list('abcdadcb'))

category = pd.Categorical(x.values, ordered=True, categories=list('abcd'))

x.astype(category)

```
#### Problem description

Trying to assign a variable an ordered category type failes with 
`AttributeError: 'Categorical' object has no attribute '_ordered'`

#### Expected Output

The operations completes successfully and yields a series of categorical dtype that is ordered.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : None.None

pandas           : 0.25.1
numpy            : 1.16.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.1.1
setuptools       : 41.0.1
Cython           : 0.29.12
pytest           : 5.0.1
hypothesis       : 4.34.0
sphinx           : 2.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.3.4
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.7.0
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.4
matplotlib       : 3.1.0
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : 0.11.1
pytables         : None
s3fs             : None
scipy            : 1.3.0
sqlalchemy       : 1.3.5
tables           : 3.5.2
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.8

</details>

**Comment by jorisvandenbossche** [comment]
In principle, you should pass a dtype to `astype`:

```
In [18]: x.astype(category.dtype)
Out[18]: 
0    a
1    b
2    c
3    d
4    a
5    d
6    c
7    b
dtype: category
Categories (4, object): [a < b < c < d]
```

But, it is correct that this worked before (eg on 0.24). However, I am not sure this was on purpose or only accidentally.

**Comment by jorwoods** [comment]
@jorisvandenbossche Ah. Well, the documentation still reflects the methodology I used.

https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html

**Comment by jorwoods** [comment]
I can, however, confirm that by referencing the `.dtype` attribute/property in my code, it works.

**Comment by jorwoods** [comment]
My mistake. `raw_cat` is making a series of the categorical, not assigning type. Further down the page it does it via `CategoricalDtype` which is what I meant to use. 

Closing the issue.
