### ISSUE TITLE
Stream compatibility on newest Python IO 

### ISSUE THREAD

**Issue by Deamoner** [pandas-dev/pandas#28660]
Python version 3.7.3 or 3.7.4

#### Code Sample, a copy-pastable example if possible

```    decoded = base64.b64decode(content_string)
    try :
        if 'dm.xpt' in filename :
            # df_dict['dm'] = pd.read_sas(filename,encoding="latin1")

            df_dict['dm'] = pd.read_sas(io.BytesIO(decoded),format='xport',encoding='latin1')
```
#### Problem description

'bytes' do not have attribute 'encode"

**How to fix: 
 commenting out L279-L282 in Python37\lib\site-packages\pandas\io\sas\sasreader.py**

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by alimcmaster1** [comment]
Do you have a minimal reproducible example? Can you give the output of pd.show_versions() ?

**Comment by mroeschke** [comment]
We're happy to reopen this issue when we can validate the issue with a reproducible example
