### ISSUE TITLE
value_counts with dropna=False gives differing results

### ISSUE THREAD

**Issue by anttttti** [pandas-dev/pandas#28676]
#### Code Sample, a copy-pastable example if possible

```python

df[col].value_counts(dropna=False, normalize=True)

```
#### Problem description

Doing df[col].value_counts(dropna=False, normalize=True) gives different results on different x64 machines. Updated both machines to latest version of Python (3.7.4), Numpy (1.17.2), Scipy (1.3.1) and Pandas (0.25.1), and the problem still occurs. Regardless of version updates, the two machines produce slightly different orderings of value counts when null-values are present, the only difference being hardware differences.

**Comment by 0xF4D3C0D3** [comment]
```python3
import pandas as pd
from pandas.core.algorithms import (is_extension_array_dtype,
                                    _value_counts_arraylike
                                   )

df = pd.DataFrame({'a': [1, 2, None, 3, 4] * 3,
                   'b': ['foo', 'bar']*7 + ['baz']},
                   [1, 2, 3] * 5)

print(pd.show_versions())

name = getattr(df['a'], "name", None)

flag_extension_array_dtype = is_extension_array_dtype(df['a'])
print('is_extension_array_dtype:', flag_extension_array_dtype, '\n')

if flag_extension_array_dtype:
    result = pd.Series(df['a'])._values.value_counts(dropna=False)
    print('Series(values)._values.value_counts(dropna=dropna):\n', result, '\n')
    result.name = name
    counts = result.values
else:
    keys, counts = _value_counts_arraylike(df['a'], dropna=False)
    print('_value_counts_arraylike(values, dropna):\n', keys, counts, '\n')
    
    keys = pd.Index(keys)
    
    result = pd.Series(counts, index=keys, name=name)
    
    print('result:\n', result, '\n')
    
print('normalized:\n', result / float(counts.sum()))
```
can you show me the above result on each machines?

**Comment by anttttti** [comment]
Both machines print out the same result:

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.0.0-29-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_NZ.UTF-8
LOCALE           : en_NZ.UTF-8

pandas           : 0.25.1
numpy            : 1.17.2
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : 0.29.13
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
None
is_extension_array_dtype: False 

_value_counts_arraylike(values, dropna):
 [ 1.  2. nan  3.  4.] [3 3 3 3 3] 

result:
 1.0    3
2.0    3
NaN    3
3.0    3
4.0    3
Name: a, dtype: int64 

normalized:
 1.0    0.2
2.0    0.2
NaN    0.2
3.0    0.2
4.0    0.2
Name: a, dtype: float64

**Comment by simonjayhawkins** [comment]
Thanks @anttttti for the report.

see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports detailing how to provide the necessary information for us to reproduce your bug.

I'll close this. please open a new issue using the bug report template.
