### ISSUE TITLE
Pandas tries to do something with indexes while only supposed to work with values.

### ISSUE THREAD

**Issue by RD193** [pandas-dev/pandas#28672]
#### Code Sample, a copy-pastable example if possible

```python
ra = pd.read_excel("Edata.xlsx", sheet_name="r-a").astype(float)

```
```python
d[i].min().min()

```
#### Problem description
Traceback (most recent call last):
  File "E:/загрузки/учеба/лабы/H2lab/Search.py", line 4, in <module>
    ra = pd.read_excel("Edata.xlsx", sheet_name="r-a").astype(float)
  File "E:\python\lib\site-packages\pandas\core\generic.py", line 5882, in astype
    dtype=dtype, copy=copy, errors=errors, **kwargs
  File "E:\python\lib\site-packages\pandas\core\internals\managers.py", line 581, in astype
    return self.apply("astype", dtype=dtype, **kwargs)
  File "E:\python\lib\site-packages\pandas\core\internals\managers.py", line 438, in apply
    applied = getattr(b, f)(**kwargs)
  File "E:\python\lib\site-packages\pandas\core\internals\blocks.py", line 559, in astype
    return self._astype(dtype, copy=copy, errors=errors, values=values, **kwargs)
  File "E:\python\lib\site-packages\pandas\core\internals\blocks.py", line 643, in _astype
    values = astype_nansafe(vals1d, dtype, copy=True, **kwargs)
  File "E:\python\lib\site-packages\pandas\core\dtypes\cast.py", line 729, in astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: could not convert string to float: '4→0'

---------------

Traceback (most recent call last):
  File "E:/загрузки/учеба/лабы/H2lab/Search.py", line 23, in <module>
    mins[i] = d[i].min().min()
  File "E:\python\lib\site-packages\pandas\core\generic.py", line 11620, in stat_func
    f, name, axis=axis, skipna=skipna, numeric_only=numeric_only
  File "E:\python\lib\site-packages\pandas\core\series.py", line 4083, in _reduce
    return op(delegate, skipna=skipna, **kwds)
  File "E:\python\lib\site-packages\pandas\core\nanops.py", line 123, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)
  File "E:\python\lib\site-packages\pandas\core\nanops.py", line 843, in reduction
    result = getattr(values, meth)(axis)
  File "E:\python\lib\site-packages\numpy\core\_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
TypeError: '<=' not supported between instances of 'str' and 'int'
I encountered this problem i new version of pandas. It seems like pandas when coverting values to float or searching for min, tries to operate with indexes(which strings) as well.  I know it because "4→0" is a name of row or column. I can provide any fether info if you need it. It works ok with pandas 0.23.4

#### Expected Output
everything working without mistakes
#### Output of ``pd.show_versions()``

<details>
This convig works prety fine:
[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.23.4
pytest: None
pip: 19.1.1
setuptools: 39.0.1
Cython: 0.29.7
numpy: 1.15.1
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.0.1
sphinx: 1.8.1
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.0
openpyxl: 2.6.3
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: 4.3.3
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

------------------------------------------

This doesn't:
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.0.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None
pandas           : 0.25.1
numpy            : 1.15.1
pytz             : 2018.5
dateutil         : 2.7.3
pip              : 19.1.1
setuptools       : 39.0.1
Cython           : 0.29.7
pytest           : None
hypothesis       : None
sphinx           : 1.8.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.3.3
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10
IPython          : 7.0.1
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.3
matplotlib       : 3.0.0
numexpr          : None
odfpy            : None
openpyxl         : 2.6.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.1.0
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : 1.1.0
xlwt             : None
xlsxwriter       : None

</details>

**Comment by RD193** [comment]
Updated: figures out that proplem was not in operations. Looks like now function read_excel works other way now. 0.23.4 takes left column of r-a for instance as indexes(which is true). New versions think that this is part of data.
[Edata.xlsx](https://github.com/pandas-dev/pandas/files/3667883/Edata.xlsx)

**Comment by mroeschke** [comment]
Sounds like everything worked as expected now?

Going to close due to inactivity. However, if you are still experiencing issues with the latest version of pandas, feel free to open up a new issue with a minimal example.
