### ISSUE TITLE
HDF Store – How to select from table with multiindex?

### ISSUE THREAD

**Issue by oyibor** [pandas-dev/pandas#28682]
I want to update data within a HDF table that has a multiindex.
This should be done in two steps:
- Remove the data from the HDF Store where the multiindex equals the multiindex of an update table (=> store.remove)
- Insert the new data into the HDF Store  (=> store.append)

The problem is that I do not find a way to select the multiindex.
I would need something like this:
store.remove(‘table_name’, where="index in df_update.index")

Is there a way to select a multiindex from a HDF store?

**Comment by nrebena** [comment]
Yes there is. You can use the level name in the `where` argument from `select` (or `remove`). The level name default to level_0, level_1 and so on if there were not defined in the index.

```
import pandas as pd
index = pd.MultiIndex.from_product([['a', 'b'], [1, 2]])
df = pd.DataFrame(range(4), index=index)
store = pd.HDFStore('store.h5')
store.append('dataframe', df)

store.select('dataframe', where="level_0 in 'b' and level_1 in 2")

Out[]: 
     0
b 2  3
```

If you have named levels in your index, you can use those.

```
import pandas as pd
index = pd.MultiIndex.from_product([['a', 'b'], [1, 2]], names['letter', 
                                                               'number'])
df = pd.DataFrame(range(4), index=index)
store = pd.HDFStore('store.h5')
store.append('dataframe', df)

store.select('dataframe', where="level_0 in 'b' and level_1 in 2")

Out[12]: 
               0
letter number   
b      2       3
```

**Comment by oyibor** [comment]
Thank you nrebena,

if I try to select a part of the stored table I get an error which says I have to select the whole table because it has a fixed format:

store = pd.HDFStore(file_name)
idx_0 = df_update.index.get_level_values(0)
idx_1 = df_update.index.get_level_values(1)
result = store.select('table_name', where='symbol in idx_0 and date in idx_1')

or

store = pd.HDFStore(file_name)
idx = df_update.index
result = store.select('table_name', where='(symbol, date) in idx')

both methods raise the error:

TypeError: cannot pass a where specification when reading from a Fixed format store. this store must be selected in its entirety

**Comment by oyibor** [comment]
Hello nrebena,

Thank you for your help. It works perfect.
Simply amazing!!!

store = pd.HDFStore(file_name)
idx_0 = df_update.index.get_level_values(0)
idx_1 = df_update.index.get_level_values(1)
result = store.select('table_name', where='symbol in idx_0 and date in idx_1')

**Comment by oyibor** [comment]
Hello nrebena,
I am now able to slice a stored table by the different index levels.
But how can I perform an inner join of the indices of the original table and the updating table?
This is what I need to identify the data that have to be removed from the original table.

Example:

If a multiindex of a stored table equals the index of an update table
these indices have to be removed. This would give me the expected result of rows to be removed from the table:
`remove_v1 = store[table_name][store[table_name].index.isin(df_update.index)]`
this is different from the return of the select function using the where clause on the index levels:
`remove_v2 = store.select(table_name, where='level_0 in idx_0 and level_1 in idx_1')`

Is it possible to get the rows that have to be removed from the original table by using select/remove with the where clause?

**Comment by nrebena** [comment]
I am not sure what you are trying to achieve here. Do you have a more concrete (and copy pastable) example maybe.
if you wanna now the row in a store that are also in df_update, you could try something like this

```
import pandas as pd
index = pd.MultiIndex.from_product([['a', 'b'], [1, 2]], names=['letter', 
                                                               'number'])
df = pd.DataFrame(range(4), index=index)
store = pd.HDFStore('store.h5')
store.append('dataframe', df)

df2 = df.loc[('a', slice(None)),:] 

store.select('dataframe', where='letter in df2.index.get_level_values(0) and number in df2.index.get_level_values(1)')
```

**Comment by oyibor** [comment]
Hello nrebena,

I have attached a text file with an example:
[upsert_example.txt](https://github.com/pandas-dev/pandas/files/3689445/upsert_example.txt)

I want to update and insert data into an existing table.
This can be done in one line like this:

store[table_name] = df_update.combine_first(store[table_name])

That approach works well for small tables. With bigger tables I have huge problems. It can take very long time to update and even freeze my system on large tables.
I think the problem is that even if df_update is a small data set to update the whole (large) table will be overwritten using the above method.
Now I want to replace this method by using store.remove and store.append.
Unfortunately, I am not able to select the correct data to be updated/removed in the existing table. 

store[table_name] = df_update.combine_first(store[table_name])

is different from:

idx_0 = df_update.index.get_level_values(0)
idx_1 = df_update.index.get_level_values(1)
store.remove(table_name, where='symbol in idx_0 & date in idx_1')
store.append(table_name, df_update)

**Comment by nrebena** [comment]
Ok I see, your are missing a step here when using the store if you wanna combine the data.
```
idx_0 = df_update.index.get_level_values(0)
idx_1 = df_update.index.get_level_values(1)
df_store = store.select(table_name, where='symbol in idx_0 & date in idx_1')
store.remove(table_name, where='symbol in idx_0 & date in idx_1')
df_update.combine_first(df_store)
store.append(table_name, df_update)
```

**Comment by oyibor** [comment]
Hello nrebena,
Thank you very much for your help and effort.
This method works, too. (except that combine_first does not work inplace)
```
idx_0 = df_update.index.get_level_values(0)
idx_1 = df_update.index.get_level_values(1)
store = pd.HDFStore(file_name, mode='a', complib='blosc',complevel=9)
df_store = store.select(table_name, where='symbol in idx_0 & date in idx_1')
store.remove(table_name, where='symbol in idx_0 & date in idx_1')
df_update_mod = df_update.combine_first(df_store).astype(np.int64)
store.append(table_name, df_update_mod)
```
Nevertheless, does this method delete and insert much more data than required.
Imagine if your updating table holds one common date for each symbol and you would add a new symbol with dates starting from the beginning to the end. 
In this case "where symbol in idx_0" would select all symbols and "where date in idx_1" would select all dates. The result would be that the whole existing table would be selected and overwritten. This is what I need to avoid.
The store.select method should select the inner join of the multi index for the existing and the updating table. That would be the most efficient solution.
Do you see my concerns here?

**Comment by jreback** [comment]
@oyibor you likely should just use a database
HDFStore is not designed for updating efficiently 

in any event this is out of scope for the issue tracker

**Comment by oyibor** [comment]
This issue has been closed. 
Nevertheless, here is a workaround to my described problem that uses a similar approach like nrebena has described before.
I have not checked the performance on large tables, yet. Maybe it is useful in some cases, maybe not or maybe a database solution is the better choice in others cases...

```
idx_0 = df_update.index.get_level_values(0)
idx_1 = df_update.index.get_level_values(1)
store = pd.HDFStore(file_name, mode='a', complib='blosc',complevel=9)
df_store = store.select(table_name, where='symbol in idx_0 & date in idx_1')
coord_prelim = store.select_as_coordinates(table_name, ['symbol in idx_0 & date in idx_1'])
df_coord = pd.DataFrame(coord_prelim, index=df_store.index, columns=['coord'])
coord = df_coord.join(df_update, how='inner', rsuffix='_y')['coord'].values
store.remove(table_name, where=coord)
store.append(table_name, df_update)
```
