### ISSUE TITLE
Read long text from a cell

### ISSUE THREAD

**Issue by SenseiBunny** [pandas-dev/pandas#28683]
So I have very long text in excel cell, when I want to read this it only shows a few lines. How to get all text from a cell?

        tekst=self.alco.loc[self.alco['Name']=='Vodka', 'description']    
        tekst=tekst.to_string(index=False)
        print(tekst)

Output:
Vodka is a distilled beverage composed primari...

**Comment by SenseiBunny** [comment]
This worked for me! - https://stackoverflow.com/a/52691689/10666495

**Comment by WillAyd** [comment]
This is probably already solved by #28052 - can you check on master?

**Comment by MarcoGorelli** [comment]
Closing as it looks like it's been fixed, but please reopen if you disagree
