### ISSUE TITLE
Add Note About Referencing GH Issue Number to Test in Contrib Guide

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#28703]
We often ask people to add the GH Issue number as a comment to new tests, but that requirement isn't explicitly spelled out in the contributing guide. Might save some back and forth if that is added to the `Writing Tests` section:

https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#writing-tests

**Comment by dmswl6310** [comment]
Can I try it??

**Comment by KiranAkadas** [comment]
I want to work on this!
