### ISSUE TITLE
DOC: Add docstring to fixture "frame" in "tests/io/excel/conftest.py"

### ISSUE THREAD

**Issue by dayoreke** [pandas-dev/pandas#28726]
#### Problem description

Add docstring to fixture "frame" in "tests/io/excel/conftest.py" as it is not clear what the method does.

**Comment by simonjayhawkins** [comment]
xref #26784

**Comment by simonjayhawkins** [comment]
@dayoreke i'll close this and just xref https://github.com/pandas-dev/pandas/pull/26579#pullrequestreview-245987920 in the PR.
