### ISSUE TITLE
Groupby count doesn't accept sort= keyword

### ISSUE THREAD

**Issue by mrocklin** [pandas-dev/pandas#28755]
Many groupby aggregations like sum, min, max, mean, and so on take a `sort=` keyword.  Count doesn't for some reason.

```python
In [1]: import pandas as pd

In [2]: df = pd.DataFrame({"x": [3, 4, 1, 3, 4, 1], "y": [1, 2, 3, 4, 5, 6]})

In [3]: df.groupby("x").y.sum(sort=False)
Out[3]:
x
1    9
3    5
4    7
Name: y, dtype: int64

In [4]: df.groupby("x").y.count(sort=False)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-76e5507e57cb> in <module>
----> 1 df.groupby("x").y.count(sort=False)

TypeError: count() got an unexpected keyword argument 'sort'
```

Is this intentional?  Is it a bug?  I was trying to turn off sorting intermediate results in dask dataframe by default to speed things up a bit (it's also for cudf/RAPIDS work) and ran into this.  The inconsistency makes things slightly inconvenient.

**Comment by jreback** [comment]
we accept **kwargs in these, IIRC mainly to accomodate pandas options like ``min_count``, but these don't do anything and should be removed

```
In [7]: df.groupby('A').sum(sort=False, bar=True)                                                                                                                                             
Out[7]: 
   B
A   
1  3
2  3
```

**Comment by kkraus14** [comment]
Wouldn't you pass the `sort` parameter to the groupby call here as opposed to the aggregation call?

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html

**Comment by jsignell** [comment]
Just came across this while trying to close out some old dask PRs. You can pass a sort kwarg into the groupby and it is on by default. By turning it off you can see that the `sort` in `sum` has no impact.

```python
In [1]: import pandas as pd 
   ...:  
   ...: df = pd.DataFrame({"x": [3, 4, 1, 3, 4, 1], "y": [1, 2, 3, 4, 5, 6]}) 
   ...: df                                                                      
Out[1]: 
   x  y
0  3  1
1  4  2
2  1  3
3  3  4
4  4  5
5  1  6

In [2]: df.groupby("x", sort=False).y.sum(sort=False)                           
Out[2]: 
x
3    5
4    7
1    9
Name: y, dtype: int64

In [3]: df.groupby("x", sort=False).y.sum(sort=True)                            
Out[3]: 
x
3    5
4    7
1    9
Name: y, dtype: int64
```

If pandas can't catch invalid kwargs because it's passing them along, then I think this issue should be closed.

**Comment by DiSchi123** [comment]
I got another issue - groupby. last doesn't accept "min_count" keyword even though the doc says so

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.resample.Resampler.last.html#pandas.core.resample.Resampler.last

Is that a bug? Happy to open a bug, just wanted to add the question here first.

**Comment by arw2019** [comment]
I'm not very familiar with that part of the codebase but since the docs say you should be able to pass the arg I'd say that's a bug.

**Comment by DiSchi123** [comment]
Ok I'll report it

**Comment by rhshadrach** [comment]
groupby functions such as `sum` no longer take kwargs from #31473. `groupby(...).last` and `resample(...).last` now takes `min_count` and is functional from #37870.
