### ISSUE TITLE
API: ops alignment behavior inconsistencies

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#28759]
In both Series and DataFrame ops, we have inconsistent behavior for when we call `self.align` vs when we raise.  Everything discussed here is for non-flex ops.

Case 1: consider `op(ser1, ser2)` for two Series with non-matching indexes.
- arithmetic ops call `self.align(other)`
- comparison ops raise `ValueError("Can only compare identically-labeled Series objects")`
- logical ops call `self.align(other)`

Case 2: consider `op(df1, df2)` for two DataFrames with non-matching axes
- arithmetic ops call `self.align(other)`
- comparison ops raise `ValueError("Can only compare identically-labeled DataFrame objects")`
- logical ops call `self.align(other)`

Case 3) consider `op(df, ser)`.  This always aligns, with comparison not being treated differently from the other two.

The policy (and code) would be simpler if we changed this so that either:
a) the comparison op in case 3 doesn't align, matching cases 1 and 2
b) comparison ops always align, matching arithmetic and logical ops

**Comment by jorisvandenbossche** [comment]
The (non-)alignment of comparison ops (for the first two cases) is something we discussed long time ago, I recall, and was at that time decided consciously. To be clear: not saying that it is therefore the best behaviour, just meaning it is not an accidental, historical inconsistency, as far as I recall. So worth digging up the reasoning (will try to look for relevant issues later).

**Comment by jbrockmendel** [comment]
@jorisvandenbossche thanks.  As long as its intentional, its fine by me.  If you do stumble on the old thread, pls LMK and I'll add a comment in the code pointing back to it for the next time I forget.

**Comment by jreback** [comment]
actually i would like to see case 3)’have the non-align for comparisons (raise)
for consistency

**Comment by jorisvandenbossche** [comment]
So #36795 fixed the inconsistency for df/ser comparisons compared to the others. Shall we close this then? 
Otherwise, if someone further wants to look at changing the inconsistency between arithmetic and comparison ops, you will need to dig up the old discussions about this to find out the reasoning.
