### ISSUE TITLE
to_string() does not have an "encoding" parameter.

### ISSUE THREAD

**Issue by farziengineer** [pandas-dev/pandas#28766]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame(data = {'Japanese' : 'こんにちは', 'English' : 'Hello'}, index = [0])
df.to_string()

```

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.1.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.0
numpy            : 1.16.2
pytz             : 2018.7
dateutil         : 2.7.5
pip              : 18.1
setuptools       : 40.6.3
Cython           : 0.29.2
pytest           : 4.0.2
hypothesis       : None
sphinx           : 1.8.2
blosc            : None
feather          : 0.4.0
xlsxwriter       : 1.1.2
lxml.etree       : 4.2.5
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.8.3 (dt dec pq3 ext lo64)
jinja2           : 2.10
IPython          : 7.2.0
pandas_datareader: None
bs4              : 4.6.3
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.2.5
matplotlib       : 3.0.2
numexpr          : 2.6.8
odfpy            : None
openpyxl         : 2.5.12
pandas_gbq       : None
pyarrow          : 0.13.0
pytables         : None
s3fs             : None
scipy            : 1.1.0
sqlalchemy       : 1.2.15
tables           : 3.4.4
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.2

</details>

**Comment by mroeschke** [comment]
Can you give an example of the expected behavior and API parameters?

**Comment by farziengineer** [comment]
Just like to_csv() and to_excel() have an "encoding" parameters, we can have an encoding parameter in string for consistency. 
python
```
df.to_stiring(encodig = "iso-8859-1")

**Comment by WillAyd** [comment]
Might not be thinking straight today but wouldn't this only make sense if it were a `to_bytes` method? Not applicable for `to_string`, no?

**Comment by TomAugspurger** [comment]
Agreed with Will. An encoding is only necessary when going between strings
and bytes. But we're converting from a Python object to a string.

**Comment by farziengineer** [comment]
https://github.com/pandas-dev/pandas/issues/28663#issuecomment-536322605

**Comment by TomAugspurger** [comment]
Forgot about the `buf` argument accepting a string path.

In that case, accepting an `encoding` makes sense, for specifying the encoding for the newly created file. We should raise when encoding is specified and it's `buf` isn't a string path.
