### ISSUE TITLE
DataFrame.replace inconsistent behaviour with regex and nan

### ISSUE THREAD

**Issue by jaksiprejak** [pandas-dev/pandas#28767]
When replacing a string with a `nan`, in a dataframe of strings, using a regex. The rest of the strings are replaced with `nan` as well.

When `to_replace` is a simple string, only the target values are replaced with `nan`

```python
import numpy as np
import pandas as pd
import re

df = pd.DataFrame([['1', '2'], ['**', '5']])

print(df.replace('**', np.nan))  # works as expected
#      0  1
# 0    1  2
# 1  NaN  5

print(df.replace(re.compile(r'\**'), np.nan))
#     0   1
# 0 NaN NaN
# 1 NaN NaN

print(df.replace(r'\**', np.nan, regex=True))
#     0   1
# 0 NaN NaN
# 1 NaN NaN


```

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.24.2
pytest: 4.3.1
pip: 19.1.1
setuptools: 41.0.1
Cython: 0.29.6
numpy: 1.16.4
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.5.0
sphinx: 1.8.5
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: 1.2.1
tables: 3.5.1
numexpr: 2.6.9
feather: None
matplotlib: 3.1.0
openpyxl: 2.6.1
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.5
lxml.etree: 4.3.2
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.3.5
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by dsaxton** [comment]
This is behaving as expected because your regex matches _any_ string (it looks for the character `*` zero or more times).  You'd need to escape both characters: `df.replace(r"\*\*", np.nan, regex=True)`.

**Comment by jaksiprejak** [comment]
Damn, I feel stupid, Should be `r'\*+'`

Thank you.
