### ISSUE TITLE
DataFrame.append with empty list raises IndexError

### ISSUE THREAD

**Issue by joaoe** [pandas-dev/pandas#28769]
#### Code Sample

```python
>>> import pandas
>>> pandas.DataFrame().append([])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".env\lib\site-packages\pandas\core\frame.py", line 7108, in append
    elif isinstance(other, list) and not isinstance(other[0], DataFrame):
IndexError: list index out of range
>>> pandas.__version__
'0.25.1'
```
#### Problem description

Crash when passing empty sequence to `DataFrame.append`

#### Expected Output

No crash.
The source DataFrame is returned intact.

#### Version

Version 0.25.1. Happens in master.
Problem line 
https://github.com/pandas-dev/pandas/blob/master/pandas/core/frame.py#L7014

**Comment by jbrockmendel** [comment]
What output are you hoping to see here?  Still an empty DataFrame?

**Comment by joaoe** [comment]
I guess the empty DataFrame() is expected since an empty sequence is just...empty ? 

This produces an empty DataFrame
```
pandas.DataFrame().append([pandas.DataFrame()])
```

**Comment by jbrockmendel** [comment]
Seems reasonable.  A PR would be welcome.
