### ISSUE TITLE
DOC: wrong formatting of the set_option docs

### ISSUE THREAD

**Issue by alimcmaster1** [pandas-dev/pandas#28780]
https://pandas-docs.github.io/pandas-docs-travis/reference/api/pandas.set_option.html

Notes section of the set_option docs seem to have lost some formatting/spacing on master.

PR coming to fix!

Ali

**Comment by joshz123** [comment]
Is this issue still open? I am new to open source and would like to contribute

**Comment by alimcmaster1** [comment]
@glemaitre is already looking - but there is many other Good First Issues :)
