### ISSUE TITLE
QST: Backstick is not working in Python 3

### ISSUE THREAD

**Issue by miguelangel** [pandas-dev/pandas#28808]
#### Code Sample, a copy-pastable example if possible
```python
# Your code here
import pandas as pd
df = pd.DataFrame({'A': range(1, 6), 'B': range(10, 0, -2), 'C C': range(10, 5, -1)})
df.query('B == `C C`')
```
#### Problem description
Hi,
In the link below, it is mentioned to use _backstick_ with _.query()_ method when the column name contains spaces.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.query.html

Unfortunately, the sample code does not work anymore with Python 3.0 becayse if backstick deprecation.

I was wondering if you could please tell me how to reproduce the example below (taken from the link above) in Python 3.

**Comment by jreback** [comment]
you would have to show your version
this is correct with 0.25.1
