### ISSUE TITLE
0.25.1 Possible bug in 'DataFrame.duplicated' method

### ISSUE THREAD

**Issue by Hex-Liu** [pandas-dev/pandas#28806]
```python
dt_mrc[dt_mrc.flag.eq('UnKnown')&dt_mrc.duplicated(subset=['id','cln_nm'],
keep=False)&dt_mrc.cln_nm.notna()]

```
#### Problem description

It's a simple contact table, slicing using 3 boolean expressions including duplicated. When try to slice those with duplicated id(contact id)-cln_nm(cleaned name) pair using 'duplicated' method **with the 'keep=False' parameter**, the return seems wrong with the last 2 rows clearly not duplicated on this pair. Could you pls check this out? Thx

![image](https://user-images.githubusercontent.com/45284886/66267096-2419f800-e7fb-11e9-9628-066c618f3d37.png)

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Expected Output

![image](https://user-images.githubusercontent.com/45284886/66267234-73acf380-e7fc-11e9-8994-071b419c5fdc.png)

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.17.2
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 1.0.1
pymysql          : 0.9.3
psycopg2         : 2.8.3 (dt dec pq3 ext lo64)
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.3.8
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
</details>

**Comment by jreback** [comment]
pls post a copy passable example; do not show screenshots
