### ISSUE TITLE
bug: style.applymap + style.highlight_null() results in extra colons in the CSS

### ISSUE THREAD

**Issue by zepaz** [pandas-dev/pandas#28812]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np

np.random.seed(24)
df = pd.DataFrame({'A': np.linspace(1, 10, 10)})
df = pd.concat([df, pd.DataFrame(np.random.randn(10, 4), columns=list('BCDE'))],
               axis=1)
df.iloc[0, 2] = np.nan

def color_negative_red(val):
    """
    Takes a scalar and returns a string with
    the css property `'color: red'` for negative
    strings, black otherwise.
    """
    color = 'red' if val < 0 else 'black'
    return 'color: %s' % color

print(df.style.applymap(color_negative_red).highlight_null(null_color='red').render())
```
Code is taken from the [user_guide](https://pandas.pydata.org/pandas-docs/stable/user_guide/style.html) 

#### Problem description
If you combine a style.applymap() with style.highlight_null() cells which are not NULL receive an extra colon in the ID in the CSS. This can cause render issues (especially Outlook) when trying to display the HTML. 

ie:

```
<style  type="text/css" >
    #T_7854aabc_e8c0_11e9_b09d_f2f0444bd885row0_col0 {
            color:  black;
            : ;
        }    #T_7854aabc_e8c0_11e9_b09d_f2f0444bd885row0_col1 {
            color:  black;
            : ;
        }    #T_7854aabc_e8c0_11e9_b09d_f2f0444bd885row0_col2 {
            color:  black;
            background-color:  red;
...
```

#### Expected Output
```
<style  type="text/css" >
    #T_7854aabc_e8c0_11e9_b09d_f2f0444bd885row0_col0 {
            color:  black;
        }    #T_7854aabc_e8c0_11e9_b09d_f2f0444bd885row0_col1 {
            color:  black;
        }    #T_7854aabc_e8c0_11e9_b09d_f2f0444bd885row0_col2 {
            color:  black;
            background-color:  red;
...
```
Or in words, the expected output is that if a value is non Null that the CSS ID block does not have a colon added. 

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.14.71-21.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.0
numpy            : 1.15.4
pytz             : 2018.9
dateutil         : 2.7.5
pip              : 19.2.3
setuptools       : 40.7.3
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 1.8.4
blosc            : None
feather          : None
xlsxwriter       : 1.1.4
lxml.etree       : 4.3.1
html5lib         : 1.0.1
pymysql          : 0.9.3
psycopg2         : None
jinja2           : 2.10
IPython          : 7.2.0
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.1
matplotlib       : 3.0.2
numexpr          : 2.6.9
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.14.0
pytables         : None
s3fs             : 0.2.0
scipy            : 1.2.1
sqlalchemy       : 1.2.17
tables           : 3.4.4
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : 1.1.4
</details>

**Comment by attack68** [comment]
Lots of changes in the recent versions. This is no longer an issue.
