### ISSUE TITLE
.at not setting value

### ISSUE THREAD

**Issue by ma00** [pandas-dev/pandas#28816]
#### Code Sample, a copy-pastable example if possible

```python
# ff= 20
# df['B'] = 0
# df.at[4, 'B'] = -ff/100
# df.at[4, 'B']
#0

```
#### Problem description

the function Dataframe.at is not setting the value if passed as variable, instead if it's passed as number, it works

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
python           : 3.5.6.final.0
pandas           : 0.25.1

</details>

**Comment by Mandeep0001** [comment]
Hi,

Can you share one code snippet which shows the above problem?

I have tried below code snippet in which im passing variable in .at method and its working fine.
############################################################
############################################################
import pandas as pd  
  
# reading csv file from url   
data = pd.read_csv("https://media.geeksforgeeks.org/wp-content/uploads/nba.csv")  
  
# creating position and label variables 
position = 2
label = 'Name'
      
# calling .at[] method 
output = data.at[position, label] 
  
# display 
print(output)

**Comment by ma00** [comment]
did you try to set a value ?

`data.at[position,` label] = 'Michael'

**Comment by Mandeep0001** [comment]
data.at[position, label] = 'Michael', this one also working.

**Comment by mroeschke** [comment]
This works on master and I believe we have sufficient tests for this:

```
In [1]: df = pd.DataFrame()

In [2]: ff= 20

In [3]: df['B'] = 0

In [4]: df.at[4, 'B'] = -ff/100

In [5]: df
Out[5]:
     B
4 -0.2
```
