### ISSUE TITLE
DOC: fix code-block in the reshaping docs

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#28819]
The code block at this location:

https://dev.pandas.io/docs/user_guide/reshaping.html#pivoting-with-single-aggregations

is not rendered correctly, as we accidentally try to render it as a note. The `.. note::` should be replaced with `.. code-block::`

**Comment by espatatis** [comment]
Can I get this issue assigned ?

**Comment by jorisvandenbossche** [comment]
@espatatis sorry, there was already a PR opened by someone else: https://github.com/pandas-dev/pandas/pull/28820
