### ISSUE TITLE
Improve PandasSeriesGroupby operations performance

### ISSUE THREAD

**Issue by gcoimbra** [pandas-dev/pandas#28810]
#### Code Sample
```
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randint(0,10000,size=(10000, 4)), columns=list('ABCD'))
df2 = df.groupby('B')
df2.apply(lambda x: numpy.array(x.A).mean() ) # Operation 1
df2.apply(lambda x: x.A.mean()) # Operation 2
```

#### Problem description
First operation takes 600 ms, second takes 900 ms.
For smaller arrays (10 elements), first  operation takes 1.86 ms and second takes 2.26 ms.

It takes longer to use the native pandas mean on a SeriesGroupBy object than converting to a numpy array and then calculating the mean. Converting to a Series object won't make much difference.

I think it's because the native/pandas solution accesses the array that were fragmented in the memory in consequence of the groupby operation. 

The slowdown occurs also with the max function it's not exclusive of mean. 

I expected that the native operation would be as fast as the native one.
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.2.11
machine          : x86_64
processor        : Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
byteorder        : little
LC_ALL           : None
LANG             : pt_BR.UTF-8
LOCALE           : pt_BR.UTF-8

pandas           : 0.25.1
numpy            : 1.14.5
pytz             : 2019.2
dateutil         : 2.7.2
pip              : 19.1
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by jreback** [comment]
neither of these 2 operations are interesting when using using python loop (which is what .apply is), as compared to an actual vectorized soln ([6])
```
In [4]: %timeit df2.apply(lambda x: numpy.array(x.A).mean() )                                                                                                                                                                                                                 
512 ms ± 10.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [5]: %timeit df2.apply(lambda x: x.A.mean())                                                                                                                                                                                                                               
442 ms ± 30.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [6]: %timeit df2.A.mean()                                                                                                                                                                                                                                                  
522 µs ± 25.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [7]: df2.A.mean().equals(df2.apply(lambda x: x.A.mean()))                                                                                                                                                                                                                  
Out[7]: True
```

**Comment by gcoimbra** [comment]
@jreback 
I know, but in my case the apply was necessary because a lot other operations were being made.
Do you know why this is happening?

**Comment by gcoimbra** [comment]
It wasn't just other operations. In my application, I am creating a dataframe from the original grouped. This new dataframe has n rows that is calculated from the groups of the bigger one.

**Comment by jreback** [comment]
@gcoimbra no idea; use the vectorized operations or live with perf of the apply

**Comment by gcoimbra** [comment]
@jreback 
I don't think apply is the source of the problem. Try this instead:
```
In [125]: import pandas as pd 
     ...: import numpy as np 
     ...: df = pd.DataFrame(np.random.randint(0,100,size=(100000, 4)), columns=list('ABCD')) 
     ...: df2 = df.groupby('B') 
     ...: x = df2.get_group(99) 
     ...:  
     ...:  
     ...: %timeit -n 100 x.A.values.mean()  # Operation 1 
     ...: %timeit -n 100 x.A.mean() # Operation 2                                                                                      
39.7 µs ± 641 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)
154 µs ± 41.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

```
