### ISSUE TITLE
Faster SQL implementation in d6stack library

### ISSUE THREAD

**Issue by JulianWgs** [pandas-dev/pandas#28817]
#### Code Sample

https://github.com/d6t/d6tstack/blob/master/examples-sql.ipynb

#### Problem description

In the example it currently takes 28s to upload data to an SQL database. With the d6stack implementation it only takes 4.7s with postgres and 7.1s with mysql which is 4 to 6 times faster than standard pandas.

#### Expected Output

Improved speed uploading data to an SQL database right out of the box.

**Comment by TomAugspurger** [comment]
What's the actual next step here? You'll need to flesh out your proposal before we can decide whether it's a good idea / worth doing.

**Comment by jorisvandenbossche** [comment]
The important piece of information is also to know what they do differently to achieve this better performance, to know if this is something we can do in pandas.

**Comment by rockg** [comment]
From looking at the code it uses the bulk insert operations for the respective database types.So it writes a csv file and then loads that into the database using `LOAD DATA`, `BULK INSERT`, etc. See [here](https://github.com/d6t/d6tstack/blob/7b6c5851b53bdd221466facfb7aebdc96006bf41/d6tstack/utils.py#L146). I know I created something similar as loading through insert statements is so slow.

**Comment by WillAyd** [comment]
I think this issue is too open ended so should refine the ask or close out. You can already write your own bulk load command as shown in the documentation:

https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#insertion-method

Though that has type preservation downsides

**Comment by JulianWgs** [comment]
There is already a parameter called method to switch between normal and multi insert. Im assuming that multi is not an implementation of bulk insert? Then I would propose a new value, where you can choose to use "bulk".

The if-statement for the different methods can be found here:
https://github.com/pandas-dev/pandas/blob/bee17d5f4c99e6d1e451cf9a7b6a1780aa25988d/pandas/io/sql.py#L724

Implementing this should be done within Pandas, because the d6stack library is a big dependency and implementing shouldn't lead to too many duplicate lines of code.

**Comment by JulianWgs** [comment]
d6stack implements database specific function ([Link](https://github.com/d6t/d6tstack/blob/master/d6tstack/utils.py))

- postgres implementation uses raw_connection
- mysql and mssql use local file

I don't think it is worth to implement these for the gain in performance.

The issue can be closed, if the pandas maintainers agree.

**Comment by mroeschke** [comment]
Looks like the project is fairly inactivate and not much interest from the core team. Closing as it seems not worth pursuing.
