### ISSUE TITLE
read_csv  improvement

### ISSUE THREAD

**Issue by jeremy-rutman** [pandas-dev/pandas#28818]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.read_csv(f,sep='\t')

```
#### Problem description
Not so much a problem as a feature possibility - when reading without the encoding= parameter, the default can be made a bit smarter; since utf-16 seems to generally start with unique characters 0xFF 0xFE hex , if those chars start a file then it should be read as utf-16 (either after reading as utf-8 fails or as a first option) 
I am not so familiar with the pandas code and will try to implement this if someone can point me to where these changes would go - the  [pandas.io.parsers](https://github.com/pandas-dev/pandas/blob/master/pandas/io/parsers.py) is a bit opaque for me.

**Comment by espatatis** [comment]
I'd like to get this issue assigned ?

**Comment by mroeschke** [comment]
Here's the default encoding logic:

https://github.com/pandas-dev/pandas/blob/9db7f3eff3ec01f32806967fe372d60cfe75184b/pandas/io/parsers.py#L963

Not sure if how I feel about more inference since it can lead to bugs. If the ` 0xFF 0xFE` are absolute rules for utf-16, adding logic for that case may be okay.

**Comment by WillAyd** [comment]
I personally think detecting the encoding of files is out of scope for pandas. Can you not use charted or another library for this?

**Comment by WillAyd** [comment]
see also #27655 which had a similar request but was also deemed out of scope. Closing this one as such though if any maintainers disagree can reopen

**Comment by jeremy-rutman** [comment]
in case its of interest i used chardet as suggested in the below which uses it if encoding is not specified, reading the first kB to determine encdoing

```
import chardet
import pandas as pd

def read_csv_multiformat(f,**kwargs):
    if not 'encoding' in kwargs:
        with open(f, 'rb') as fp:
            bin_dat = fp.read(1000)
            char_info = chardet.detect(bin_dat)
            print(char_info)
            if 'encoding' in char_info and 'confidence' in char_info and char_info['confidence'] > 0.6:
                kwargs['encoding'] = char_info['encoding']
    df = pd.read_csv(f,**kwargs)
    return df

f = 'utf16.csv'
df=read_csv_multiformat(f,sep='|')
print(df.head())
```

**Comment by JobCollins** [comment]
It's pretty cool to see this issue is raised seems like a common issue with pandas users.
In issue #27655 I used the following workaround especially once the error is generated:
`import pkgutil
import encodings
import os

def all_encodings():
    modnames = set([modname for importer, modname, ispkg in pkgutil.walk_packages(
        path=[os.path.dirname(encodings.__file__)], prefix='')])
    aliases = set(encodings.aliases.aliases.values())
    return modnames.union(aliases)

text = b'\xa0'  #given by the error message
for enc in all_encodings():
    try:
        msg = text.decode(enc)
    except Exception:
        continue
    if msg == 'ñ':
        print('Decoding {t} with {enc} is {m}'.format(t=text, enc=enc, m=msg))
    else:
        print('Decoding {t} with {enc} is {m}'.format(t=text, enc=enc, m=msg))`
