### ISSUE TITLE
Feature Request: Population Covariance Calculation with ddof parameter for DataFrame.cov()

### ISSUE THREAD

**Issue by chrisyeh96** [pandas-dev/pandas#28823]
I propose adding a `bias` parameter in [`DataFrame.cov()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.cov.html). Currently, Pandas v0.25.1 does not have such a parameter.

The default would be `bias=False`, which would compute sample covariance with a `N-1` factor in the denominator. When `bias=True`, this would compute population covariance with `N` in the denominator.

This follows the same semantics as the [`numpy.cov()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cov.html) function. Since `DataFrame.cov()` uses `numpy.cov()`, I hope this would not be too hard to implement.

**Comment by jbrockmendel** [comment]
In other methods we have a `ddof` parameter.  Would setting that to 0 be equivalent to bias=True?

**Comment by chrisyeh96** [comment]
Yes, the `ddof` parameter in `DataFrame.std()` is similar. Setting it to 0 would indeed be equivalent to `bias=True`. Actually, I just realized that `numpy.cov()` also has a `ddof` parameter, and it definitely seems to be a more flexible parameter.

I've changed the issue name to reflect this.

**Comment by smartswdeveloper** [comment]
It seems that most of the work has already been done here:
https://github.com/pandas-dev/pandas/pull/16227
but it got stalled.
Is it possible to make it re-use the good work that has already been done?

**Comment by jreback** [comment]
you can certainly make a new PR with the original code changes, updated and tested as indicated
