### ISSUE TITLE
NameError: name 'tempita' is not defined when building extensions with old cython

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#28836]
#### Code Sample, a copy-pastable example if possible

```python
pietro@debiousci:~/nobackup/repo/pandas_temp$ python3 setup.py build_ext --inplace 
Traceback (most recent call last):
  File "setup.py", line 813, in <module>
    ext_modules=maybe_cythonize(extensions, compiler_directives=directives),
  File "setup.py", line 541, in maybe_cythonize
    build_ext.render_templates(_pxifiles)
  File "setup.py", line 127, in render_templates
    pyxcontent = tempita.sub(tmpl)
NameError: name 'tempita' is not defined
```

#### Problem description

If cython is too old/missing, the nice error reporting of the setup.py do not work.

Until few minutes ago I had never heard about ``tempita``, but my understanding is that it is required (used in ``build_ext.render_templates``) while ``cython`` is not:
https://github.com/pandas-dev/pandas/blob/bee17d5f4c99e6d1e451cf9a7b6a1780aa25988d/setup.py#L74

Hence, whether the check for ``tempita`` is made should not depend on whether ``cython`` is found: instead, this is what currently happens, given that ``tempita`` is checked in the ``else`` clause of the ``try...except`` check of ``cython``:
https://github.com/pandas-dev/pandas/blob/bee17d5f4c99e6d1e451cf9a7b6a1780aa25988d/setup.py#L76

Notice that this means the above error pops out despite ``tempita`` being installed in my system.

#### Expected Output

None

#### Output of ``pd.show_versions()``

<details>

Commit: bee17d5f4c99e6d1e451cf9a7b6a1780aa25988d

</details>

**Comment by toobaz** [comment]
(By the way: my command above will fail anyway because of the missing cython, but my understanding is that, because of this bug, ``setup.py`` will fail even when cython files are provided - and hence cython is not needed)

**Comment by jreback** [comment]
we bumped cython recently; conda update cython should be enough
this is a dev only dep and only if not creating a new from a new env

**Comment by toobaz** [comment]
Yep, sorry for not mentioning I had already solved my local problem.

**Comment by jorisvandenbossche** [comment]
I suppose this is caused by https://github.com/pandas-dev/pandas/pull/28374 when we now require cython for sdists. Before, we only called cythonize when `if cython`, but now we assume cython is installed in `maybe_cythonize`. We can add a check there if cython/tempita is installed and otherwise raise a better error message?

**Comment by toobaz** [comment]
I _think_ (but I'm quite ignorant of how the ``setup.py`` works) that just moving the following ``try..except``
https://github.com/pandas-dev/pandas/blob/bee17d5f4c99e6d1e451cf9a7b6a1780aa25988d/setup.py#L76

... out of the ``else`` should fix this...

**Comment by WillAyd** [comment]
I think that block could be simplified - the `pip install Tempita` command I don't believe is valid any longer.

I generally think anything to simplify setup.py would be great. I would be hesitant to add more logic

**Comment by jorisvandenbossche** [comment]
@toobaz I don't think that should be moved out of the else clause, as in theory you don't need tempita to run `setup.py` (eg sdist does not need it). 

But I think @WillAyd is correct that the `import tempita` / `pip install tempita` is no longer needed, it might stem from a time that we still supported cython versions that did not include tempita

**Comment by toobaz** [comment]
> @toobaz I don't think that should be moved out of the else clause, as in theory you don't need tempita to run `setup.py` (eg sdist does not need it).

Right, it would need also a variable where we remember whether tempita is present, like for cython.

> But I think @WillAyd is correct that the `import tempita` / `pip install tempita` is no longer needed, it might stem from a time that we still supported cython versions that did not include tempita

Again, I'm not an expert, but my understanding is that if you have ``tempita`` but not ``cython``, the ``setup.py`` still tried to allow you to take a pandas provided with ``cython`` files and compile them to C. But then, this is a very marginal use case, so maybe not worth the effort.

**Comment by jorisvandenbossche** [comment]
> if you have tempita but not cython, the setup.py still tried to allow you to take a pandas provided with cython files and compile them to C

tempita itself is not enough to compile cython file to C (tempita only generates cython files from the templates, not C files), so that use case doesn't sound possible to me.

So I think it should be fine to just rely on tempita provided by cython?

**Comment by toobaz** [comment]
> tempita itself is not enough to compile cython file to C (tempita only generates cython files from the templates, not C files), so that use case doesn't sound possible to me.

OK sorry, now understand, and sure, checking ``tempita'' is useless.
