### ISSUE TITLE
BUG: DataFrame.equals() wrongly returns True in case of identical blocks with different locations

### ISSUE THREAD

**Issue by SadanLucifer** [pandas-dev/pandas#28839]
#### Code Sample, a copy-pastable example if possible

```python
  version: 3.6.8
# Your code here
  df3 = pd.DataFrame({'a': [1, 2], 'b': ['s', 'd']})
  df4 = pd.DataFrame({'a': ['s', 'd'], 'b': [1, 2]})
  df3.equals(df4)
```
#### Problem description

![image](https://user-images.githubusercontent.com/20040007/66388224-3745e700-e9f8-11e9-8fe6-589add23177d.png)

When I read the source code, I did a simple test on it, and then failed.

#### Expected Output
I expected it return False
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.0
numpy            : 1.16.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.2.2
setuptools       : 40.6.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.3.3
html5lib         : None
pymysql          : 0.9.3
psycopg2         : 2.8.3 (dt dec pq3 ext lo64)
jinja2           : 2.10.1
IPython          : 7.5.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.3
matplotlib       : 3.1.0
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.4
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None

</details>

**Comment by jorisvandenbossche** [comment]
Yes, that's clearly a bug. Thanks for finding that!

We seem to check the equality block by block. But that way we ignore the block locations .. (and thus how they map to column names)

**Comment by bhuvanakundumani** [comment]
I am interested in working on this .

**Comment by jorisvandenbossche** [comment]
@bhuvanakundumani Super, that would be very welcome! If you have any question or need a pointer, let me know.

**Comment by bhuvanakundumani** [comment]
@jorisvandenbossche - I am reading more about BlockManger here :  https://github.com/pydata/pandas-design/blob/master/source/internal-architecture.rst.
Hope am in the right direction. thanks

**Comment by jorisvandenbossche** [comment]
@bhuvanakundumani that's a document describing a potential refactor of the internal BlockManager, so although it contains some description of the current sate, I think it is not the best document to read to understand the current implementation. I think in general we don't really have a good documentation of this, sorry ..

The code where I would start looking is at

https://github.com/pandas-dev/pandas/blob/58d34d91bc92ce5eb4023bfcdbff916cef5ef5f0/pandas/core/internals/managers.py#L1398-L1420

We might need an additional check that the block locations are also equal.

**Comment by bhuvanakundumani** [comment]
@jorisvandenbossche thanks for the info. will look into it.

**Comment by TomAugspurger** [comment]
Pushing off the 1.0 milestone. Would certainly take a PR for 1.0 if anyone is able to get to it in time.

**Comment by Reksbril** [comment]
I will look into it
