### ISSUE TITLE
Migrate 32-bit linux build

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#28842]
Right now our 32-bit build only happens on a Linux VM in azure pipelines. Anaconda no longer builds 32-bit linux packages, and conda-forge never built 32-bit packages. So that build is likely to cause problems over time.

We should migrate to either

1. Use a 32-bit windows build, which Anaconda still builds packages for.
2. Use a non-conda environment on 32-bit linux VM.

1 is probably preferable since it aligns with the rest of our CI infra. I don't know if Azure provides 32-bit images (last I checked the didn't). IIRC, you can trick conda into installing 32-bit packages on a 64-bit machine, but I'm not sure how robust that is.

**Comment by WillAyd** [comment]
I think this could be possible on Azure:

https://docs.microsoft.com/en-us/azure/devops/release-notes/2018/sprint-142-update#build-on-linuxarm-and-windows-32-bit-platforms

And maybe even still with linux, which would probably be preferable to minimize moving parts

**Comment by jbrockmendel** [comment]
status here?

**Comment by jbrockmendel** [comment]
This doesn't seem to have become a problem.  Closing.
