### ISSUE TITLE
STY: # TODO, # FIXME, # XXX, others?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#28846]
When looking for things that need attention, I usually grep for `# FIXME:` followed by `# TODO`.  But every so often I see a `# XXX: ` which will be missed by this heuristic.  This raises two questions:

1) Are there other common usages besides "XXX" that I'm not aware of?
2) Should we standardize on some usage patterns?

<b>Update</b> Also: comments with "?" but no TODO/FIXME label that might merit TODO

**Comment by WillAyd** [comment]
Those are the two I've seen. I don't care either way, though if we want to use either I think they should always have an issue number associated with them. Otherwise they can just hang around forever; not that an issue necessarily solves that, but makes it clearer I think

**Comment by jbrockmendel** [comment]
> I think they should always have an issue number associated with them. 

This sounds like it is probably Best Practice, but I think I am likely an offender in not doing this.  I definitely add "TODO/FIXME" comments as I go and don't open new issues for all of them.  If we can get to a point where these all have associated issues, then grep-ability should be irrelevant.  Otherwise, having few/defined enough variants that I can grep for them is my main concern.

Note: Updating OP to include comments with no label but ambiguous "?"
