### ISSUE TITLE
Support for Nested HTML Tables?

### ISSUE THREAD

**Issue by smsaladi** [pandas-dev/pandas#28851]
#### Problem description

Sometimes I encounter html tables that I need to parse where cells contain full-tables themselves. When using `pd.read_html` itself, this does not work quite that well. With a simple call to pd.read_html, each of these nested tables are parsed and then "inserted"/"concatenated" as rows.

```python
import pandas as pd
df_up = pd.read_html("up_pf00344.test.html", attrs = {'id': 'results'})
```

Screenshot of output as parsed:
![image](https://user-images.githubusercontent.com/2942215/66417012-f4fab680-e9b3-11e9-9630-2670d1a9a1e7.png)

#### Expected Output

I think a more natural parsing would be to parse each nested tables into their own pd.DataFrames and be inserted as objects as the value of the corresponding column.

Screenshot of table as rendered in html:
![image](https://user-images.githubusercontent.com/2942215/66417039-02b03c00-e9b4-11e9-8561-54c27f993c3e.png)

Link to file: https://gist.github.com/smsaladi/6adb30efbe70f9fed0306b226e8ad0d8

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-862.14.4.el7.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.utf8
LANG             : en_US.utf8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.17.2
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by smsaladi** [comment]
SO User Stef suggested rolling my own html parser [here](https://stackoverflow.com/a/58284784/2320823):

I wonder if something similar would be a useful improvement to `pd.read_html`'s functionality:

```python
import pandas as pd
import bs4

with open('up_pf00344.test.html') as f:
    html = f.read()
soup = bs4.BeautifulSoup(html, 'lxml')
results = soup.find(attrs = {'id': 'results'})

# get first visible header row as dataframe headers
for row in results.thead.find_all('tr'):
    if 'display:none' not in row.get('style',''):
        df = pd.DataFrame(columns=[col.get_text() for col in row.find_all('th')])
    break

# append all table rows to dataframe
for row in results.tbody.find_all('tr', recursive=False):
    if 'display:none' in row.get('style',''):
        continue
    df_row = []
    for col in row.find_all('td', recursive=False):
        table = col.find_all('table')
        df_row.append(pd.read_html(str(col))[0] if table else col.get_text())
    df.loc[len(df)] = df_row
```

Result:
```raw
Result of df.iloc[0].map(type):                                                           <class 'str'>
Entry                                                       <class 'str'>
Organism                                                    <class 'str'>
Protein names                                               <class 'str'>
Gene names                                                  <class 'str'>
Length                                                      <class 'str'>
Cross-reference (Pfam)                                      <class 'str'>
Cross-reference (InterPro)                                  <class 'str'>
Taxonomic lineage IDs                                       <class 'str'>
Subcellular location [CC]                                   <class 'str'>
Signal peptide                                              <class 'str'>
Transit peptide                                             <class 'str'>
Topological domain                  <class 'pandas.core.frame.DataFrame'>
Transmembrane                       <class 'pandas.core.frame.DataFrame'>
Intramembrane                       <class 'pandas.core.frame.DataFrame'>
Sequence caution                                            <class 'str'>
Caution                                                     <class 'str'>
Taxonomic lineage (SUPERKINGDOM)                            <class 'str'>
Taxonomic lineage (KINGDOM)                                 <class 'str'>
Taxonomic lineage (PHYLUM)                                  <class 'str'>
Cross-reference (RefSeq)                                    <class 'str'>
Cross-reference (EMBL)                                      <class 'str'>
e                                                           <class 'str'>
```

Bonus: As your table rows have an id, you could use it as index of your dataframe:

```python
df.loc[row.get('id')] = df_row instead of df.loc[len(df)] = df_row
```

**Comment by jbrockmendel** [comment]
I'm inclined to avoid adding this complexity to the pandas html table reader, but if you have a robust solution, we could definitely add a link to it in the docs.

BTW for non-pandas work I've tried to implement a more general html parser and usually regretted it.  I'd be interested in seeing a parser that can elegantly handle these:

- Nested table, but the outer table is pretty much just a title https://www.ngdc.noaa.gov/nndc/struts/results?ge_23=&le_23=&type_15=Like&query_15=&op_30=eq&v_30=&type_16=Like&query_16=&op_29=eq&v_29=&type_31=EXACT&query_31=None+Selected&le_17=&ge_18=&le_18=&ge_17=&op_20=eq&v_20=&ge_7=&le_7=&bt_24=&st_24=&ge_25=&le_25=&bt_26=&st_26=&ge_27=&le_27=&type_13=Like&query_13=&type_12=Exact&query_12=&type_11=Exact&query_11=&display_look=50&t=102557&s=50
- whoever wrote this really likes `<br>` tags: https://www.nber.org/cycles.html

**Comment by TomAugspurger** [comment]
I'm also against adding too much complexity.

**Comment by jreback** [comment]
closing. i suppose we'd take a PR if it was straightforward, but not a priority.
