### ISSUE TITLE
Pandas Documentation: PDF formatting/organization

### ISSUE THREAD

**Issue by solxero** [pandas-dev/pandas#28855]
Would it be possible to have a proper table of contents and index added to the pdf version of the documentation? The pdf doc for verion 0.25.1 has a section labeled contents; however, the TOC is missing. Also, consider relagating the previous version documentation to an appendix this would allow a inclusion of an index for the current version documentation only. 

The reason this change is requested is because I do not have full access to a computer system and/or its environment. The only documentation I have access to must be physical. Having such a large document necessitates being able to navigate it efficiently. 

Thank you.

**Comment by TomAugspurger** [comment]
Duplicate of https://github.com/pandas-dev/pandas/issues/22485.

We would need someone to look into the environment used to generate the PDF.

**Comment by jorisvandenbossche** [comment]
On the topic of off-line navigation, you can also download the zipped html version.
