### ISSUE TITLE
Default for "Q" is not the same default for QuarterEnd

### ISSUE THREAD

**Issue by jseabold** [pandas-dev/pandas#2885]
related #4804

I don't know if it's worth filing an issue or this is just how it is now, but I find it odd that "Q" is not a default offset like `QuarterEnd` or `quarterEnd`. Makes things a little tricky for statsmodels since I've been treating "Q" as `quarterEnd`.

```
pandas.datetools.to_offset("Q")
#<1 QuarterEnd: startingMonth=12, kwds={'startingMonth': 12}, offset=<3 MonthEnds>>

pandas.datetools.quarterEnd
#<1 QuarterEnd: startingMonth=3, offset=<3 MonthEnds>>

pandas.datetools.QuarterEnd(month=12)
#<1 QuarterEnd: startingMonth=3, kwds={'month': 12}, offset=<3 MonthEnds>>
```

**Comment by mroeschke** [comment]
I don't think this API is entirely relevant anymore. `quarterEnd` no longer exists and `month` is not specifiable anymore. Going to close out this issue
