### ISSUE TITLE
DEPR: deprecate Index.to_native_types() ?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#28867]
We currently have a public `Index.to_native_types()` method (https://dev.pandas.io/docs/reference/api/pandas.Index.to_native_types.html) that somehow formats the values of the index.

Example:
```
In [3]: pd.date_range("2012", periods=3).to_native_types() 
Out[3]: array(['2012-01-01', '2012-01-02', '2012-01-03'], dtype=object)
```

I don't think this needs to be in the public API?

**Comment by jbrockmendel** [comment]
+1

**Comment by topper-123** [comment]
+1 from me too.
