### ISSUE TITLE
Suffixes not applied to join columns in pd.merge

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#28860]
```python
import pandas as pd

left = pd.DataFrame({"a": [1.0, 2.0]})
right = pd.DataFrame({"a": [1.0]})

pd.merge(left, right, how="left", on="a", suffixes=("_left", "_right"))
#      a
# 0  1.0
# 1  2.0
```

#### Problem description

The documentation for `suffixes` in `pd.merge` reads:
```
suffixes : tuple of (str, str), default (‘_x’, ‘_y’)
Suffix to apply to overlapping column names in the left and right side, respectively. To raise an exception on overlapping columns use (False, False).
```
but it seems that the join columns themselves are ignored.  I'm guessing this is by design, but if so should the docstring be updated to reflect this?

#### Expected Output

```python
#    a_left  a_right
# 0     1.0      1.0
# 1     2.0      NaN
```

**Comment by jreback** [comment]
by definition join columns do not have suffixes
i think the docs are clear but if u do not then can submit a PR

your example is wrong

**Comment by dsaxton** [comment]
> by definition join columns do not have suffixes
> i think the docs are clear but if u do not then can submit a PR
> 
> your example is wrong

Can you elaborate on which part is wrong?  The expected output would be the standard behavior in SQL.

**Comment by jreback** [comment]
> by definition join columns do not have suffixes

you example shows suffixes on join keys which is wrong

**Comment by mroeschke** [comment]
Suffixes only apply to column that are not the join axis. `how='left'` is equivalent to a left join in SQL.

```
In [1]: left = pd.DataFrame({"a": [1.0, 2.0], 'b': [2, 3]})
   ...: right = pd.DataFrame({"a": [1.0], 'b': [2]})

In [2]: pd.merge(left, right, how="left", on="a", suffixes=("_left", "_right"))
   ...:
Out[2]:
     a  b_left  b_right
0  1.0       2      2.0
1  2.0       3      NaN
```

**Comment by WillAyd** [comment]
IIUC @dsaxton you are trying to emulate something like

```sql
SELECT tbl1.a AS "a_x", tbl2.a AS "a_y" 
    FROM tbl1 LEFT OUTER JOIN tbl2 on tbl1.a = tbl2.a
```

Which merge doesn't really allow for, since the merged column(s) are provided back as is. You could however utilize the `indicator` argument to specify if the field was available on both sides of the join or just the left side which maybe gets you what you are after

**Comment by WillAyd** [comment]
> This happens natively in SQL

I don't think that is generally true. I think the above snippet would raise an ambiguous reference error in DBs like postgres
