### ISSUE TITLE
read_json should support json pagination 

### ISSUE THREAD

**Issue by BartlomiejBartnicki** [pandas-dev/pandas#28877]
#### Problem description
Many web service return data divided in subsets. Common conventrion is return data as dict:
```
{"count":78,
"next":"link to next part of data or null",
"previous":null,
"results":[
    {"name":"John"surname":"Smith"},
    {"name":"Bob"surname":"Black"},
]}
```
Could you consider to add to read_json flag paggination=False, if flag is set to True then json shoulde be compose by sum of results:
```
url = "..."
results = []
while url is not None:
    _json = json.load(requests.get(url).content)
    results += _json['results']
    url = _json['next']
```
There is same question on StackOverflow about this, so I think this feature will be helpfull for many users.

**Comment by WillAyd** [comment]
I think this is out of scope for read_json as the interaction with the web service will rely on a third party library (here you are using requests)

You can use `pd.concat` to combiner these together similar to your second code block

**Comment by WillAyd** [comment]
Closing as out of scope for pandas but can be reopened if anyone disagrees
