### ISSUE TITLE
Series <replace> api  

### ISSUE THREAD

**Issue by sunnyjiechao** [pandas-dev/pandas#28889]
#### Code Sample, a copy-pastable example if possible

```python
# code
df_sam = pd.DataFrame([["a", 'b'], ["", "c"], ["c","d"], ["", "s"]], columns=["col1", "col2"])
```
df_sam dataframe:

| col1 | col2 |
| --- | --- |
| a | b |
|  |  c|
| c | d |
|  | s |

#### the expected result is
```python
df_sam.col1.replace("", None)
```
0    a
1    None
2    c
3    None
Name: col1, dtype: object

#### the actual result is
```python
df_sam.col1.replace("", None)
```
0    a
1    a
2    c
3    c
Name: col1, dtype: object

any idea why the actual result is not what i expected, wondering this isuue is a bug or not?

**Comment by mroeschke** [comment]
The default positional arguments of the first 2 values are `None`. The docstring has an example of how to replace with `None`: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.replace.html

```
In [5]: df_sam.replace({'': None})
Out[5]:
   col1 col2
0     a    b
1  None    c
2     c    d
3  None    s
```
