### ISSUE TITLE
A question about pd.qcut

### ISSUE THREAD

**Issue by Janhonho** [pandas-dev/pandas#28892]
code:
t = [1]*4782+[2]*1030+[3]*251+[4]*122+[5]*177
t = pd.Series(t)
result = pd.qcut(t,50,duplicates = 'drop').value_counts()

problem:
print(result), we get
(0.999, 2.0]    5812
(2.0, 3.0]       251
(4.0, 5.0]       177
(3.0, 4.0]       122

t.value_counts(), we get
1    4782
2    1030
3     251
5     177
4     122

why 1 and 2 combines in the same bin?

**Comment by dsaxton** [comment]
I think what's happening is the first bin is defined as the interval spanning the minimum and the _next smallest unique quantile_, which makes sense except in extreme cases like in this example.  Personally I would use `cut` instead of `qcut` when quantile-based bins aren't very well-defined.

**Comment by mroeschke** [comment]
This issue sounds like a usage question. Hopefully a sufficient answer has been given. Happy to reopen if not
