### ISSUE TITLE
Failing multiplication if both dataframes contain the (seemingly) identical categorical column

### ISSUE THREAD

**Issue by harmbuisman** [pandas-dev/pandas#28896]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

pop = pd.read_pickle('pop.pcl')
a = pd.read_pickle('rates_all.pcl')
b = pd.read_pickle('rates_main.pcl')

print('####### Dataframes #######')
print(pop)
print(a)
print(b)

print('\n####### Indices #######')
print(b.index.get_level_values(1))
print(a.index.get_level_values(1))
print(pop.index.get_level_values(0))

print('\n####### Output #######')
# the following works
print(pop.mul(b))

# the following fails
pop.mul(a)
```

Output:
```python
####### Dataframes #######
Age group 5-yrs to 90  PROVINCIE 
 0-4                   Drenthe        801402
                       Flevoland      740024
                       Friesland     1118421
                       Gelderland    3443051
                       Groningen      907168
Name: Population, dtype: int32
All tumors  Age group 5-yrs to 90
-1           0-4                     0.000198
             5-9                     0.000112
            10-14                    0.000123
            15-19                    0.000211
            20-24                    0.000329
dtype: float64
Main tumor group  Age group 5-yrs to 90
0                  0-4                     3.727047e-07
                   5-9                     2.410106e-07
                  10-14                    3.438238e-07
                  15-19                    6.399917e-08
                  20-24                    1.843772e-07
dtype: float64

####### Indices #######
b: Index([' 0-4', ' 5-9', '10-14', '15-19', '20-24'], dtype='object', name='Age group 5-yrs to 90')
a: CategoricalIndex([' 0-4', ' 5-9', '10-14', '15-19', '20-24'], categories=[' 0-4', ' 5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39', ...], ordered=True, name='Age group 5-yrs to 90', dtype='category')
pop: CategoricalIndex([' 0-4', ' 0-4', ' 0-4', ' 0-4', ' 0-4'], categories=[' 0-4', ' 5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39', ...], ordered=True, name='Age group 5-yrs to 90', dtype='category')

####### Output #######
Age group 5-yrs to 90  PROVINCIE   Main tumor group
 0-4                   Drenthe     0                   0.298686
                       Flevoland   0                   0.275810
                       Friesland   0                   0.416841
                       Gelderland  0                   1.283241
                       Groningen   0                   0.338106
 5-9                   NaN         0                        NaN
10-14                  NaN         0                        NaN
15-19                  NaN         0                        NaN
20-24                  NaN         0                        NaN
dtype: float64
```

#### Problem description
The above code needs the following files:
[Analysis.zip](https://github.com/pandas-dev/pandas/files/3712866/Analysis.zip)

Running it leads to an error "TypeError: No matching signature found" in the last call.

The pop dataframe has a category column 'Age group 5-yrs to 90' in the multi-index. In dataframe b the index column 'Age group 5-yrs to 90' has type object. Multiplying both dataframes succeeds. Dataframe a also has a category column 'Age group 5-yrs to 90', but multiplying it with pop fails because it cannot find a matching signature.

#### Expected Output
I would expect the output of pop.mul(a) to be similar to the pop.mul(b) call, without an error.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.1
numpy            : 1.16.4
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.2
setuptools       : 41.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.7.6.1 (dt dec pq3 ext lo64)
jinja2           : 2.10.1
IPython          : 7.7.0
pandas_datareader: None
bs4              : None
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.3.7
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
</details>

**Comment by mroeschke** [comment]
Sorry for the lack of response, but it would be great if we could have a more minimal example (without) pickle so we could include a unit test for the erroneous behavior: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by MarcoGorelli** [comment]
closing for now, please do ping if you can provide a reproducible example (as directed above) and will reopen
