### ISSUE TITLE
No metadata preventing installs of other packages

### ISSUE THREAD

**Issue by LizMcQuillan** [pandas-dev/pandas#28902]
I'm trying to install a few packages (spacy, scattertext, etc) and keep getting this pandas error

```
No metadata found in ./anaconda3/lib/python3.7/site-packages
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/Users/lmcquillan/anaconda3/lib/python3.7/site-packages/pandas-0.25.1.dist-info/METADATA'
```

Haven't been able to find a solution yet. I've tried uninstalling/reinstalling to no avail.

**Comment by WillAyd** [comment]
How are you installing pandas?

**Comment by LizMcQuillan** [comment]
I previously installed pandas using conda. I attempted to uninstall and reinstall with both pip and conda.

**Comment by LizMcQuillan** [comment]
> How are you installing pandas?

I previously installed pandas using conda. I attempted to uninstall and reinstall with both pip and conda.

**Comment by TomAugspurger** [comment]
Does this happen in a new environment?

**Comment by LizMcQuillan** [comment]
> Does this happen in a new environment?
> […](#)

yes, I've tried in 2 environments

**Comment by TomAugspurger** [comment]
Can you post the full sequence of commands and output?

**Comment by LizMcQuillan** [comment]
I ended up solving this by manually deleting all pandas files/folders from terminal and reinstalling. The uninstaller wasn't actually completing the uninstall because it couldn't find the missing file to delete.
