### ISSUE TITLE
DataFrame.to_html col_space parameter to change width of a specific column only

### ISSUE THREAD

**Issue by questglobal-bom** [pandas-dev/pandas#28917]
#### Problem description

Currently `col_space` changes width of all columns that are present in the dataframe. There must be a way to change the width of a specific column only while converting dataframe to html.

#### Expected Output
`col_space` to accept a list or dict where we can mention the column name to change only a specific column's width.

**Comment by VijayantSoni** [comment]
Hi, I would like to work on this. Seems a good issue for beginners.

**Comment by JeremiahKamama** [comment]
I'd love to take a look at this

**Comment by yixinxiao7** [comment]
Is this still being worked on? If not I'd like to take a look at this as well.
