### ISSUE TITLE
REF: get rid of register_dtype

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#28911]
AFAICT the only reason we need register_dtype is so that we can have a list of extent EA Dtypes to iterate over when doing is_extension_array_dtype.  Is that inaccurate?

If so, let's just use `ExtensionDtype.__subclasses__()` and avoid some globals and decorators.

**Comment by jreback** [comment]
yes though we have to be careful of the ordering

meaning if you have more than one subclass that has the same name for instance which do u choose? or maybe just raise ; we don’t have an easy way of resolving this

so explicit is better here i think

**Comment by jorisvandenbossche** [comment]
> the only reason we need register_dtype is so that we can have a list of extent EA Dtypes to iterate over when doing is_extension_array_dtype

To be complete: it's used to convert a string to a dtype object (so not only in `is_extension_array_dtype`).

Not that that changes your proposal, as for that conversion we also loop over the dtypes, so a list of extension dtypes is all that is needed for that functionality.

**Comment by jorisvandenbossche** [comment]
Currently this recognition of strings as `dtype` arguments is opt-in. It might be good to preserve this somehow (but could maybe also be done in other ways). Right now you can choose for a string representation that clashes with one of the existing dtypes, or one defined in other packages.

Another complication is that `__subclasses__` only gives you direct subclasses, so you need a recursive loop to get all of them. Which is not difficult, but that means you also get the "base" dtypes that are not meant to be used.
