### ISSUE TITLE
PERF: asv's for non-int64 merges

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#28922]
in #28875 we enabled non-int64 merges between all integer types. I think we need asv's to see how performant these are: https://github.com/pandas-dev/pandas/pull/28875#issuecomment-541037953

**Comment by yogendrasoni** [comment]
pandas/asv_bench/benchmarks/join_merge.py  already has a method time_on_int32.

  def time_on_int32(self, direction):
            merge_asof(self.df1d, self.df2d, on="time32", direction=direction)
Not sure if this covers. Let me know it anything is needed.

**Comment by jreback** [comment]
hmm was this asv just not working before?

can u show these asvs here (pls run them)

**Comment by jjlkant** [comment]
I think the main thing to note in regards to #28875 is that the change there only affected situations in regards to merge_asof when a `tolerance`  value is set. Nothing changed on other merge cases.

None of the benchmarks currently defined here currently make use of this tolerance value, maybe that is something to add to the asv's? https://github.com/pandas-dev/pandas/blob/54b1151a5b8be5a59323faa1047685e90aad023e/asv_bench/benchmarks/join_merge.py#L317-L332

Would be willing to take this up on monday if nobody else wants to do it in the meantime

**Comment by jjlkant** [comment]
> can u show these asvs here (pls run them)

The output of `asv run -e -E existing -b ^join_merge.MergeAsof`:
```bash
· Discovering benchmarks
· Running 5 total benchmarks (1 commits * 1 environments * 5 benchmarks)
[  0.00%] ·· Benchmarking existing-pyc__users_jjlkant_anaconda3_envs_pandas-dev_python.exe
[ 10.00%] ··· Running (join_merge.MergeAsof.time_by_int--)...
[ 40.00%] ··· Running (join_merge.MergeAsof.time_on_int--)..
[ 60.00%] ··· join_merge.MergeAsof.time_by_int                                             ok
[ 60.00%] ··· =========== ==========
               direction
              ----------- ----------
                backward   81.8±3ms
                forward    148±7ms
                nearest    214±4ms
              =========== ==========

[ 70.00%] ··· join_merge.MergeAsof.time_by_object                                             ok
[ 70.00%] ··· =========== ==========
               direction
              ----------- ----------
                backward   93.6±3ms
                forward    162±4ms
                nearest    217±5ms
              =========== ==========

[ 80.00%] ··· join_merge.MergeAsof.time_multiby                                             ok
[ 80.00%] ··· =========== ==========
               direction
              ----------- ----------
                backward   639±6ms
                forward    747±10ms
                nearest    834±30ms
              =========== ==========

[ 90.00%] ··· join_merge.MergeAsof.time_on_int                                             ok
[ 90.00%] ··· =========== ============
               direction
              ----------- ------------
                backward   27.6±0.5ms
                forward    30.5±0.6ms
                nearest    34.6±0.5ms
              =========== ============

[100.00%] ··· join_merge.MergeAsof.time_on_int32                                             ok
[100.00%] ··· =========== ============
               direction
              ----------- ------------
                backward   28.2±0.6ms
                forward    29.1±0.3ms
                nearest    34.7±0.9ms
              =========== ============
```

**Comment by jreback** [comment]
ok it think if can paramerize these asvs by tolerance would be great

**Comment by jjlkant** [comment]
Alright, I'll see what I can do!

Do you also want to include uint as a reference, for example uint64 and uint32?

**Comment by jreback** [comment]
sure could also add uint64
