### ISSUE TITLE
Add cut as a Series method

### ISSUE THREAD

**Issue by JoshuaC3** [pandas-dev/pandas#28925]
#### Problem description

It would be to have `cut` as a series method so that we can method chain. Currently, we must use `pd.cut`, for example,

```
filled_series = df.some_series.fillna(0)
pd.cut(filled_series, 10).mean()
```

it would be nice to do,

```
df.some_series.fillna(0).cut(10).mean()
```

This would also help hugely with tab completion.

#### Expected Output

To have a tab-completed series method for `cut`.

**Comment by mroeschke** [comment]
I'd be -0 on adding `cut` as a method. `cut` can currently return an ndarray, tuple, Categorical, or Series which is not conducive to chaining which would be an advantage of having `cut` as a method.

**Comment by JoshuaC3** [comment]
@mroeschke cut, the pandas function, behaves like this, but could cut, the series method, not just have a subset of behaviours. If you're using the cut method on a series you aren't likely bothered about it returning anything other than a series.

If I'm reading the docs correctly, it is always series in - series out, given `retbins` is `False` (which is the default).

What are your thoughts on this?

**Comment by R4HMATT** [comment]
take

**Comment by mroeschke** [comment]
Thanks for the suggestion, but as expressed in the original PR https://github.com/pandas-dev/pandas/pull/32834#issuecomment-601384878 and my sentiments here, I don't think this feature would be worthwhile and lead to API inconsistencies. Using `apply` in tandem with `cut` should suffice in this case. Closing.
