### ISSUE TITLE
DOC: search doesn't seem to work on dev docs

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#28923]
search seems to take the term and just disappear. https://dev.pandas.io/docs/whatsnew/v1.0.0.html? doesn't seems page specific (didn't work anywhere)

cc @jorisvandenbossche @datapythonista

**Comment by simonjayhawkins** [comment]
maybe related, doc build failed on preceding commit https://github.com/pandas-dev/pandas/runs/256072954

**Comment by jorisvandenbossche** [comment]
This is tracked in https://github.com/pandas-dev/pandas-sphinx-theme/issues/24

**Comment by jorisvandenbossche** [comment]
Should be working now! https://dev.pandas.io/docs/user_guide/index.html

**Comment by jreback** [comment]
yes looks great! thanks @jorisvandenbossche
