### ISSUE TITLE
REF: Move _shallow_copy from SelectionMixin to Window

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#28938]
SelectionMixin._shallow_copy is only used by Window/Rolling/... subclasses.  Since SelectionMixin is mixed into NDFrame, it would be nice to narrow down the namespace.  Thoughts @mroeschke ?

**Comment by mroeschke** [comment]
Make sense to me if it's only used by Window/Rolling. Happy to move it there.
