### ISSUE TITLE
No module named typing

### ISSUE THREAD

**Issue by sairamgubba94** [pandas-dev/pandas#28936]
<img width="1034" alt="Screenshot 2019-10-12 at 2 40 53 PM" src="https://user-images.githubusercontent.com/26581021/66698759-52696d00-ecfe-11e9-95b3-225984f3cd6a.png">
I have installed pandas using conda and I am getting no module named typing error. I installed typing package separately but got a syntax error there..

python version: 3.7.3

**Comment by simonjayhawkins** [comment]
can you paste the output of ``pd.show_versions()``

**Comment by simonjayhawkins** [comment]
> I installed typing package separately but got a syntax error there..

This doesn't look like a pandas issue. `typing` is part of the standard library from 3.5 onwards. https://docs.python.org/3/library/typing.html
