### ISSUE TITLE
pct_change with multi index behaves different than other functions (resolved)

### ISSUE THREAD

**Issue by jacosmuts** [pandas-dev/pandas#28941]
My first issue and I was going to get this right.

I've just spent two hours replicating and explaining the issue, just to realize it is fixed in 0.25.1

After all that time, I have to at least raise something. So I'm just raising a thank you guys for a great tool.

**Comment by jreback** [comment]
is there an issue number?

**Comment by jacosmuts** [comment]
Will close issue now

Sorry to create noise - just annoyed at myself. pct_change was breaking column multi-index.

Was working so hard to document the issue properly, and along the way figured out it was resolved - don't now the issue number, but I will close this one.

Thank you
Jaco
