### ISSUE TITLE
BUG: np.min on DataFrame with a non-ordered Categorical col

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#28949]
Discovered while debugging the try/excepts in groupby:

```
cat = pd.Categorical(['a', 'b', 'c', 'b'], ordered=False)
ser = pd.Series(cat)
df = ser.to_frame()
>>> np.min(cat)   # <-- correctly raises
>>> np.min(ser)   # <-- correctly raises
>>> np.min(df)     # <-- incorrectly returns Series(['a'])
```

**Comment by rohitsanj** [comment]
@jbrockmendel Thanks for submitting this issue. Are you working on a patch? I'd like to take this up.

**Comment by rohitsanj** [comment]
I think this is more of a numpy issue than pandas? @WillAyd @simonjayhawkins

**Comment by jbrockmendel** [comment]
Definitely a pandas issue.  It's going to be in `DataFrame.__array_ufunc__` or something like that calling `\.values`
