### ISSUE TITLE
BUG: groupby rolling ignoring min number of values

### ISSUE THREAD

**Issue by FCheda** [pandas-dev/pandas#28968]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd
import numpy as np


#set folder 
folder_processed=" your folder here "

files=[
'B0005_discharge.csv',
'B0006_discharge.csv',
'B0007_discharge.csv',
'B0018_discharge.csv',
]
def loadData(folder=folder_processed,files=files):
    df=None
    for file in files:
        if df is None:
            print(file)
            df=pd.read_csv(folder+file)
            df["battery_id"]=file
        else:
            print(file)
            foo=pd.read_csv(folder+file)
            foo["battery_id"]=file
            df=pd.concat([df,foo],axis=0)
    return df    
df= loadData()


def group_rolling(df,columns=["battery_id","cicle_id"]):                                                  
    df['Voltage_measured_mean_5'] = df.groupby(columns)[['Voltage_measured']].rolling(5).mean().astype("float32").reset_index()['Voltage_measured']
    return df 

foo=group_rolling(df)

foo[foo["internal_cicle_possition_id"]<5]
```

#### Problem description

I’m trying to do rolling windows over a grouped dataset using 2 columns for the groupby. 

With a rolling window of 5, pandas should return NaNs in the first 4 rows of each group.

This works correctly for each of my files individually, for random datasets, and for a group of multiple files, even using replicated ones (f1,f1copy1,f1copy2...). 

My last file “'B0018_discharge.csv'” works ok by itself, but if I load it next to any other file, only the first group (cicle_id) gets the NaNs, while the other groups of that file return a numeric mean value in the positions where it should not.

Files are all generated in the same way, from the discharge values in nasa Li-Ion Dataset

 https://data.nasa.gov/dataset/Li-ion-Battery-Aging-Datasets/uj5r-zjdb

I’m not including the conversion code from .mat files to .csv but I’m attaching a zip with the .csv files. [shared.zip](https://github.com/pandas-dev/pandas/files/3723349/shared.zip)

I’ve looked into the last file, and see no reason for this weird behaviour.

#### Expected Output

The first 4 rows in any (cicle-id,battery_id) group should be NaN as we are looking for 5 to make the mean.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.1
numpy            : 1.16.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.1.1
setuptools       : 41.0.1
Cython           : 0.29.12
pytest           : 5.0.1
hypothesis       : None
sphinx           : 2.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.3.4
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.8.3 (dt dec pq3 ext lo64)
jinja2           : 2.10.1
IPython          : 7.6.1
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.4
matplotlib       : 3.1.1
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.2.1
sqlalchemy       : 1.3.5
tables           : 3.5.2
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.8
Type Markdown and LaTeX:  α2
</details>

**Comment by mroeschke** [comment]
Could you most a more minimal example of the buggy behavior? https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by FCheda** [comment]
Hi !, I wasn't able to reproduce the error in less code when i was working at the company ( have changed positions since then).

Still, I understand than linking data is not something you like so I'll try it generating data from numpy and minimicing the code.

If I'm able to reproduce the error that way I'll post again.

Also, sorry for the delay

**Comment by simonjayhawkins** [comment]
> If I'm able to reproduce the error that way I'll post again.

@FCheda  Thanks for the report. closing as not actionable at this time.  ping to reopen
