### ISSUE TITLE
Add arm64 builds to CI

### ISSUE THREAD

**Issue by siddhesh** [pandas-dev/pandas#28986]
#### Problem description

Travis now has support for arm64 CI[1] and it would be great to have a CI job in place to ensure that builds and tests are run on arm64 to ensure that it works OK.  This will also help ensure that in future undefined behaviour such as #28918 do not get silently introduced into pandas.

[1] https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support

**Comment by siddhesh** [comment]
cc @jreback

**Comment by gfyoung** [comment]
Given that this is still relatively new (alpha phase), I think this would be a good opportunity to give this a try and provide feedback along the way to the Travis CI folks.

**Comment by mroeschke** [comment]
Looks like this issue wasn't closed when https://github.com/pandas-dev/pandas/pull/30641 was merged
