### ISSUE TITLE
local test failure test_pickle_ordered_from_sentinel

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#28997]
```
================================== FAILURES ===================================
__ TestCategoricalDtypeParametrized.test_pickle_ordered_from_sentinel[True] ___

self = <pandas.tests.dtypes.test_dtypes.TestCategoricalDtypeParametrized object at 0x0000020497621B08>
ordered = True

    @pytest.mark.parametrize("ordered", [True, False, None, ordered_sentinel])
    def test_pickle_ordered_from_sentinel(self, ordered):
        # GH 27295: can remove test when _ordered_from_sentinel is removed (GH 26403)
        dtype = CategoricalDtype(categories=list("abc"), ordered=ordered)

        warning = FutureWarning if ordered is ordered_sentinel else None
        with tm.assert_produces_warning(warning, check_stacklevel=False):
>           dtype_from_pickle = tm.round_trip_pickle(dtype)

pandas\tests\dtypes\test_dtypes.py:923:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <contextlib._GeneratorContextManager object at 0x0000020497621D88>
type = None, value = None, traceback = None

    def __exit__(self, type, value, traceback):
        if type is None:
            try:
>               next(self.gen)
E               AssertionError: Caused unexpected warning(s): [('DeprecationWarning', DeprecationWarning("Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working"), 'C:\\Users\\simon\\Anaconda3\\envs\\pandas-dev\\lib\\site-packages\\botocore\\vendored\\requests\\packages\\urllib3\\_collections.py', 1)].

..\Anaconda3\envs\pandas-dev\lib\contextlib.py:119: AssertionError

```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 8c5941cd57e260f4c3552769e79d8d6dbd6283d9
python           : 3.7.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : None.None

pandas           : 0.26.0.dev0+565.g8c5941cd5
numpy            : 1.16.5
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 41.4.0
Cython           : 0.29.13
pytest           : 5.2.1
hypothesis       : 4.36.2
sphinx           : 2.2.0
blosc            : None
feather          : None
xlsxwriter       : 1.2.1
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : 0.3.2
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 3.0.0
pandas_gbq       : None
pyarrow          : 0.15.0
pytables         : None
s3fs             : 0.3.4
scipy            : 1.3.1
sqlalchemy       : 1.3.9
tables           : 3.5.1
xarray           : 0.13.0
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.1

</details>

**Comment by jbrockmendel** [comment]
That looks like it depends on your installed version of requests.  does bumping that fix it?

**Comment by simonjayhawkins** [comment]
This failure disappeared shortly after but has started failing again locally. currently on 0.26.0.dev0+851.g07efdd444

> That looks like it depends on your installed version of requests. does bumping that fix it?

on latest  2.22.0

**Comment by mroeschke** [comment]
`test_pickle_ordered_from_sentinel` doesn't exist in our test suite anymore, so I think we can close this issue
