### ISSUE TITLE
CI: Integrate 3.8 builds

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#29001]
3.8 uses Python from Travis-CI.

Once conda packages are built for 3.8 we want to use our usual system.

**Comment by farziengineer** [comment]
> RemoveError: 'setuptools' is a dependency of conda and cannot be removed from conda's operating environment.

New commits to pull requests shows this error in Travis CI. Is this related.??

**Comment by TomAugspurger** [comment]
I doubt it.
