### ISSUE TITLE
Use standalone conda.exe

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#29011]
We might want to start using conda's standalone exes at https://repo.anaconda.com/pkgs/misc/conda-execs/, as an alternative to downloading and running miniconda.sh and creating a base environment that's otherwise unused.

See https://github.com/conda/conda-prefix-replacement/blob/master/.travis.yml#L9-L14

In theory, we just need to download the right exe for the platform, make it executable, and `conda.exe env create -f ...`

This may be blocked by #28842, since Anaconda doesn't provide 32-bit Linux standalone exes.

**Comment by fangchenli** [comment]
The setup script is outdated since all the CIs we are using all have some kind of miniconda integration. Azure has miniconda installed by default now, so we actually don't need to install it every time. And we are using conda-incubator in GitHub actions.
