### ISSUE TITLE
Lack of existence of exponential smoother for irregularly spaced time-series

### ISSUE THREAD

**Issue by sam-cohan** [pandas-dev/pandas#29019]
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import pandas as pd
size = 10
df = pd.DataFrame(
    {"A": np.random.uniform(size=size),
     "ts": pd.date_range('2019-01-01', periods=size, freq='1min')}
)
df["ts"] += pd.to_timedelta(df["A"] * 60, unit="s")
df = df.set_index("ts")
# StreamExponentialSmoother is defined elsewhere...
streaming_smoother = StreamExponentialSmoother(halflife=60)
df["A_ewma"] = [
    streaming_smoother.consume(val, int(ts.to_datetime64())/1e9)
    for ts, val in df.A.iteritems()
]
```
#### Problem description

I would like to calculate exponential moving average for the values but it seems all builtin pandas functions assume regular time values. Does pandas have a good way to deal with this?

I have already tried resampling the series, but that is not ideal because I want the ewma at the irregular points not sampled regular points. Also, I have written a custom streaming object which I can apply to the values but it requires iterating over the series timestamps and values and is not fast enough. Ideally I want a builtin pandas function which can do ewma taking into account the time index.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

Not relevant.

</details>

**Comment by jreback** [comment]
this would need a detailed example with implementation

**Comment by sam-cohan** [comment]
Here is a gist of what I am doing:
https://gist.github.com/scgalois/c9aff545c1e841b5835330b26b6bc9bb
