### ISSUE TITLE
rolling.apply extremely slow

### ISSUE THREAD

**Issue by sam-cohan** [pandas-dev/pandas#29018]
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import pandas as pd
size = 100000
df = pd.DataFrame(
    {"A": np.random.uniform(size=size)},
    index=pd.date_range('2019-01-01', periods=size, freq='1min'))
df.rolling("1H").mean()  # 2.32 ms ± 54.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
df.rolling("1H").apply(lambda x: np.nanmean(x), raw=True)  # 2.93 s ± 68.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
df.rolling("1H").apply(lambda x: np.nanmean(x), raw=False) # 20.9 s ± 283 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
df.rolling("1H").apply(lambda x: x.iloc[0], raw=False)  # 11.2 s ± 76.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
#### Problem description
I am not sure why the builtin rolling mean 1000x faster than calling np.mean using apply but it makes it pretty useless for anything custom. What makes things worse is that I often need to use `raw=False` because I want to make use of the timestamps to scale returns and that is fully 10,000x slower!

#### Expected Output

I just want it to be faster or want a solution that allows me to approach the performance of the builtin `mean` even if it is to somehow compile some cython code...

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
```
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.0.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.17.2
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 39.0.1
Cython           : None
pytest           : 4.4.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.2 (dt dec pq3 ext lo64)
jinja2           : 2.10.1
IPython          : 7.5.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.2.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
```
</details>

**Comment by dsaxton** [comment]
Relevant work from @mroeschke: https://github.com/twosigma/pandas/blob/feature/generalized_window_operations/doc/source/development/rolling_operations_with_numba.rst

**Comment by mroeschke** [comment]
`apply` generally just performs a for loop over your data. With `raw=False` is especially slow since it's treating everything as a python object. It's best to set up your dataframe as much as possible to use the built in rolling methods.

**Comment by mroeschke** [comment]
The work @dsaxton linked may help your work down the line (or feel free to fork the work and test it out!). The Numba rolling apply implementation described there though assumes that your function can be jittable.
