### ISSUE TITLE
Python 3.8 build terminates on Travis CI.

### ISSUE THREAD

**Issue by farziengineer** [pandas-dev/pandas#29029]
https://travis-ci.org/pandas-dev/pandas/jobs/598457821

**Comment by EwoutH** [comment]
On Arm instances it doesn't even download ([example job](https://travis-ci.com/EwoutH/multi-agent-emergence-environments/jobs/248609315)). It probably just needs to be uploaded for Aarch64.
```
Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/18.04/aarch64/python-3.8.tar.bz2
0.47s$ curl -sSf -o python-3.8.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 404 
Unable to download 3.8 archive. The archive may not exist. Please consider a different version.
```

**Comment by jreback** [comment]
its possible something was flakey
master looks good now
