### ISSUE TITLE
boolean_format parameter to to_csv

### ISSUE THREAD

**Issue by miroli** [pandas-dev/pandas#29026]
#### Code Sample

```python
df.to_csv('data.csv', boolean_format='lower')
```
#### Problem description

It would be nice if there was an option on formatting boolean values when saving to CSV. Possible options `{'lower', 'upper', 'title'}`.

**Comment by gabriellm1** [comment]
Just to check if I understood, this option would format every Boolean variable of the df to ex: true, TRUE or True when saving to CSV? If so, may I take his issue?

**Comment by miroli** [comment]
> Just to check if I understood, this option would format every Boolean variable of the df to ex: true, TRUE or True when saving to CSV?

Yes, that's what I had in mind.

**Comment by gabriellm1** [comment]
I'll try my best to make it happen!

**Comment by rushabh-v** [comment]
Is this a potential feature? @jbrockmendel . If yes, then I would like to work on this.

**Comment by jreback** [comment]
-1 in expanding the api in its current form of to_csv; we already have a lot of keywords

would need deprecation / refactoring to generalize the way options are specified for formats

-0 in this particular option - this i suppose makes the csv more human readable

**Comment by mroeschke** [comment]
Thanks for the suggestion, but agreed that this probably doesn't require a new keyword. Also the booleans in the Dataframe can be processed into strings and have lowering/uppering applied. Closing.
