### ISSUE TITLE
max() function - returns wrong value with categorical Series

### ISSUE THREAD

**Issue by stefansimik** [pandas-dev/pandas#29039]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

# Create demo data for package delivery
df = pd.DataFrame({'package_id': [1, 1, 1, 2, 2, 3],
                   'status': ['Waiting', 'OnTheWay', 'Delivered', 'Waiting', 'OnTheWay', 'Waiting']})

# Status column: Make ordinal
delivery_status_type = pd.CategoricalDtype(categories=['Waiting', 'OnTheWay', 'Delivered'], ordered=True)
df['status'] = df['status'].astype(delivery_status_type)

# Way 1: Looks correct
max1 = df['status'].max()
print(max1)

# Way 2: Incorrect. Prints bad value 'Waiting' instead of correct value 'Delivered'
max2 = max(df['status'])
print(max2)

>>> Delivered      # (is OK)
>>> Waiting        # (is WRONG)
```
#### Problem description

Generic function `max()` return incorrect result on categorical Series.

#### Expected Output

Way 2 (in code) should return correct value `Delivered`,
not bad value `Waiting`

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.1
numpy            : 1.16.5
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 41.4.0
Cython           : None
pytest           : 5.0.1
hypothesis       : None
sphinx           : 2.2.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.8.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.0
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None

</details>

**Comment by jorisvandenbossche** [comment]
I don't think there is a way to fix this. The built-in `max` function will convert the input to a list (or iterate through the input), which means that the `max` function just sees strings, and does have no knowledge about the order of the categories.

**Comment by jorisvandenbossche** [comment]
There is no "category object". We only have the array-like (Categorical) for categorical values, but the scalars values you get out of this are plain scalars (depending the type of the categories. So if you have string categories, scalar values are strings, if you have integer categories, scalar values are integers)

**Comment by stefansimik** [comment]
Clear, thank you.
Closing issue, because there is no solution probably.
