### ISSUE TITLE
About "fillna()"...kind like a bug?

### ISSUE THREAD

**Issue by Jumpo-523** [pandas-dev/pandas#29048]
Actually I wanna replace NaN with "mode" value of the variable.
But the following code doesn't work.
```python
# Your code here
a = df.Embarked.mode()
df.Embarked[df.Embarked.isna()].replace(a.values[0], inplace=True)
df.Embarked[df.Embarked.isna()]
>>>61     NaN
829    NaN
Name: Embarked, dtype: object
```

**Comment by Jumpo-523** [comment]
I don't know why fillna() doesn't work....
Let me know if this is a bug or my error :(

**Comment by MarcoGorelli** [comment]
Hi Jumpo-523 :)

First, what's `df.Embarked`? You're typically expected to write examples that others can reproduce. For example:

> ```
> import pandas as pd 
> import numpy as np 
> 
> df = pd.DataFrame({'Embarked': [1, 2, np.nan]}) 
> a = df.Embarked.mode() 
> df.Embarked[df.Embarked.isna()].replace(a.values[0], inplace=True) 
> df.Embarked[df.Embarked.isna()]                                         
> ```
> 
> Actual output:
> ```
> 2   NaN
> Name: Embarked, dtype: float64
> ```
> 
> Expected output: empty Series.

Second, it's often useful to know what versions you're using, so if you could fill out this part of the issue template, I think people here will appreciate it:
```
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>
```

**Comment by Jumpo-523** [comment]
I'm so sorry!
The part of data is like the following. Maybe you could replicate it. 

```
[1]data = pd.DataFrame({"PassengerId":{"50":51,"51":52,"52":53,"53":54,"54":55,"55":56,"56":57,"57":58,"58":59,"59":60,"60":61,"61":62,"62":63,"63":64,"64":65,"65":66,"66":67,"67":68,"68":69},
    "Embarked":{"50":"S","51":"S","52":"C","53":"S","54":"C","55":"S","56":"S","57":"C","58":"S","59":"S","60":"C","61":np.nan,"62":"S","63":"S","64":"C","65":"C","66":"S","67":"S","68":"S"}})
[2]data.Embarked.fillna(data.Embarked.mode(), inplace=True)
[3]data
>>>   PassengerId Embarked
50           51        S
51           52        S
52           53        C
53           54        S
54           55        C
55           56        S
56           57        S
57           58        C
58           59        S
59           60        S
60           61        C
61           62      NaN
62           63        S
63           64        S
64           65        C
65           66        C
66           67        S
67           68        S
68           69        S
[4]pd.__version__
>>>'0.25.1'
```

If you don't mind it, please try it.

SIncerely

**Comment by Jumpo-523** [comment]
First of all, I tried to use "fillna" but doesn't work then I tried "replace" and either does't work...
So I understood the mode() function returns pd.Series.

**Comment by TomAugspurger** [comment]
Thanks @MarcoGorelli.
