### ISSUE TITLE
Multiple dateoffsets in Holiday raises a TypeError

### ISSUE THREAD

**Issue by hantusk** [pandas-dev/pandas#29049]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
from pandas.tseries.holiday import Holiday, USThanksgivingDay
blackfriday = Holiday('Black Friday', month=USThanksgivingDay.month, day=USThanksgivingDay.day, offset=[USThanksgivingDay.offset, pd.DateOffset(1)])
cybermonday = Holiday('Cyber Monday', month=blackfriday.month, day=blackfriday.day, offset=[blackfriday.offset, pd.DateOffset(3)])
min_date, max_date = [pd.to_datetime(x) for x in ['2017-11-1', '2018-11-30']]

blackfriday.dates(min_date, max_date) # OK!
cybermonday.dates(min_date, max_date) # TypeError: unsupported operand type(s) for +: 'DatetimeIndex' and 'list'
```
#### Problem description
The current behaviour is a problem, because it should be possible always to define Holidays relative to other holidays, instead of finding the "mother" Holiday without a dateoffset.

Expected output would be no error

A potential solution could be to sum consecutive dateoffsets (timedeltas) in the offset list, when a Holiday is constructed.

#### Expected Output
DatetimeIndex(['2017-11-27', '2018-11-26'], dtype='datetime64[ns]', freq=None)

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None

pandas: 0.24.1
pytest: None
pip: 19.3
setuptools: 41.4.0
Cython: 0.29.13
numpy: 1.15.4
scipy: 1.1.0
pyarrow: 0.15.0
xarray: None
IPython: 7.8.0
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2019.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: 0.4.0
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: 1.3.10
pymysql: None
psycopg2: None
jinja2: 2.10.3
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by dontgoto** [comment]
take
