### ISSUE TITLE
single row DataFrame to Series conversion

### ISSUE THREAD

**Issue by vograno** [pandas-dev/pandas#29045]
#### Code Sample, a copy-pastable example if possible

```python
# prepare data
s = pd.Series(np.arange(4), index=pd.MultiIndex.from_product([list('ab'), list('cd')]))
# note the index 'i' is constant so that groupby would produce a single group
df = pd.DataFrame.from_dict({'i': [True, True, True, True], 'x': np.arange(4), 'y': list('abcd')}).set_index(['i'])

# indexing: irreversible loss of dtype info
# There is no way to compute 'dataframe' result from the 'series' one.
>>> df.iloc[0].dtype                # series
dtype('O')
# vs
>>> df.iloc[[0]].dtypes             # dataframe (desirable output)
x     int64
y    object

# unstack: unexpected shape of double-unstack (should be one-row dataframe) 
>>> s.unstack()          # this produces expected output
   c  d
a  0  1
b  2  3
>>> s.unstack().unstack()           # this should be a one-row dataframe, not series
c  a    0
   b    2
d  a    1
   b    3
dtype: int64

# aggregate; same loss of dtype info as in indexing
>>> def get_1st_row(x):
...:     return x.iloc[0]

>>> df.aggregate(get_1st_row).dtype     # lost type info
dtype('O')
>>> df.groupby('i').aggregate(get_1st_row).dtypes   # desirable output
x     int64
y    object
dtype: object
>>> 

# doesn't play well with iterators.
# There should be no difference between iteration over groups
# in the groupby object, and the aggregation of the groupby object.
# The following two computations are morally equivalent, yet
# their results differ
>>> df2 = pd.concat({k: df for k in range(2)})
>>> df2.groupby(level=0).aggregate(get_1st_row)   # desirable output
   x  y
0  0  a
1  0  a
# vs
>>> pd.concat((_df.aggregate(get_1st_row) for k, _df in df2.groupby(level=0)))  # unexpected output
x    0
y    a
x    0
y    a
dtype: object
```
#### Problem description

Whenever pandas is to return a single-row dataframe it, conventionally, returns a series instead.
Examples of such operations include: a) indexing a single row, b) unstacking, c) dataframe aggregation, and d) groupby aggregation vs iteration over groups.

This leads to loss of dtype information, unexpected output shapes, and shape mismatch between two morally equivalent computations. 

My proposal is to add a new dataframe-row class DFRow(DataFrame) and return an instance of that class instead of returning Series in indexing, aggregation, transposition, and unstack-ing.
Returning a single-row DataFrame w/o casting it to DFRow would create ambiguity in unstack-ing:
DFRow should not be unstack-able (just as Series is not stack-able), but a generic single-row DataFrame should be unstack-able until its index levels are exhausted, at which point unstack() should return DFRow.

**UPDATE**
It turned out there is an existing way of controlling the shape of the output. Here is a workaround:
```
>>> df.aggregate([get_1st_row])
             x  y
get_1st_row  0  a
>>> pd.concat((_df.aggregate([get_1st_row]) for k, _df in df2.groupby(level=0)))
             x  y
get_1st_row  0  a
get_1st_row  0  a
```

**Comment by jreback** [comment]
not sure I really get your point here. if you want a one row frame then use the indexing syntax that does that, meaning dt.iloc[[0]]. if you want a Series then don’t.

by definition putting non homogeneous dtypes in a Series will be object dtype; you are getting exactly what you asked for.

trying to add another container class would add tremendous complexity and i don’t see any advantage to it. with huge disadvantages.

**Comment by vograno** [comment]
@jreback , dt.iloc[[0]] does provide a workaround for the iloc indexing. However no such workaround is available for other cases described above, most notably groupby().aggregate() vs iteration over groupby().groups()
As to the complexity of adding adding another container class it could be as simple as this
```
class DFRow(DataFrame):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.shape[0] == 1:
            raise Exception(f'too many rows={self.shape[0]} in DFRow.__init__')
```
with T(), stack(), unstack() overloaded.
Fixing the indexing, i.e. `loc`, `iloc`, `take`, is easy too by modifying `_LocationIndexer. __getitem__(self, key)`. The most difficult part is to prevent return of Series in aggregate(), it seems to be deeply hardwired into the code.

Regarding the benefits, I had been repeatedly bumping into loss of dtype info in aggregations until I took a break to research the subtleties of where it comes from. Before that it was a constant struggle to anticipate the shapes and types of the results. And even now, with full understanding, it feels like working around a bug. I assume there are other people like me.

**Comment by jreback** [comment]
if you have a clearly identified specific bug would take a PR
but am not moved by your example

nothing ‘simple’ labout adding a new container
this would increase complexity massively for IMHO 0 gain

**Comment by vograno** [comment]
How about just returning a single-row DataFrame, instead of Series, in aggregate()? This would prevent dtype info loss and would fix the groupby().aggregate() vs iteration over groupby().groups() dichotomy, which to me is the biggest annoyance.

**Comment by TomAugspurger** [comment]
Also -1 on adding a container. 

The aggregation problem can be solved with a keepdims-style keyword.

**Comment by vograno** [comment]
@TomAugspurger what is keepdims-style keyword? Did you mean adding keepdims=False to aggregate()?

**Comment by TomAugspurger** [comment]
keepdims in the NumPy sense, where reductions like mean don't reduce
dimensionality.

**Comment by jreback** [comment]
actually we use ``result_type=`` now in ``.apply``, so not averse to these types of adds.

**Comment by vograno** [comment]
Actually, while reading the `test_demo` in `test_apply.py` I found a workaround that satisfied my needs. I updated the original post to include the workaround.
Thank you everyone for the discussion.

**Comment by mroeschke** [comment]
Sounds like there isn't much enthusiasm for this feature from the core devs. Thanks for the suggestion but going to close.
