### ISSUE TITLE
Feature request: improve behavior of ambiguous='infer' of tz_localize()

### ISSUE THREAD

**Issue by phaabe** [pandas-dev/pandas#29056]
[I first thought it was a bug, but it is actually a missing feautre.](https://github.com/pandas-dev/pandas/issues/29031)

When I apply `tz_localize()` I run in the following error:

    AmbiguousTimeError: There are %i dst switches when there should only be 1.

Here is my code to reproduce the error. Note that from 2am to 3am every datetime is a duplicate due to daylight saving time.

    index = pd.DatetimeIndex(['2018-10-28 01:00:00', '2018-10-28 01:15:00',
                              '2018-10-28 01:30:00', '2018-10-28 01:45:00',
                              '2018-10-28 02:00:00', '2018-10-28 02:00:00',
                              '2018-10-28 02:15:00', '2018-10-28 02:15:00',
                              '2018-10-28 02:30:00', '2018-10-28 02:30:00',
                              '2018-10-28 02:45:00', '2018-10-28 02:45:00',
                              '2018-10-28 03:00:00', '2018-10-28 03:15:00',
                              '2018-10-28 03:30:00', '2018-10-28 03:45:00',
                              '2018-10-28 04:00:00'], freq='infer')
    
    data = list(range(len(index)))
    
    df = pd.DataFrame(data=data,index=index)
    df.index = df.index.tz_localize('Europe/Berlin', ambiguous='infer')

I propose to improve the behavior of `infer`. The problem here is daylight saving time. 
I propose: With respect to the order, duplicates are identified as winter or summer time.

The result should be an index looking like this:
```
2018-10-28 01:00:00+02:00
2018-10-28 01:15:00+02:00
2018-10-28 01:30:00+02:00
2018-10-28 01:45:00+02:00
2018-10-28 02:00:00+02:00
2018-10-28 02:00:00+01:00
2018-10-28 02:15:00+02:00
2018-10-28 02:15:00+01:00
2018-10-28 02:30:00+02:00
2018-10-28 02:30:00+01:00
2018-10-28 02:45:00+02:00
2018-10-28 02:45:00+01:00
2018-10-28 03:00:00+01:00
2018-10-28 03:15:00+01:00
2018-10-28 03:30:00+01:00
2018-10-28 03:45:00+01:00
2018-10-28 04:00:00+01:00
```
I think this is "easily" possible and it's logical: 
For example 2am occurs two times, than the "earlier 2am" must be `2018-10-28 02:00:00+02:00` and the "later 2am" must be `2018-10-28 02:00:00+01:00`

I can help with further explanations.
This is my first feature request.
I have never done a pull request, but I might do one -- let me know if that makes sense. I am not the most experienced python developer but I don't know how to find out wheather I can contribute.

**Comment by Liam3851** [comment]
Is it reasonable to infer that the data is out-of-order in real time and referring to unique timestamps, rather than having a duplicate index? Note the current code works just fine if the timestamps are monotonic in time order, not lexical order:

```python
In [5]: index = pd.DatetimeIndex(['2018-10-28 01:00:00', '2018-10-28 01:15:00',
   ...:                           '2018-10-28 01:30:00', '2018-10-28 01:45:00',
   ...:                           '2018-10-28 02:00:00', '2018-10-28 02:15:00',
   ...:                           '2018-10-28 02:30:00', '2018-10-28 02:45:00',
   ...:                           '2018-10-28 02:00:00', '2018-10-28 02:15:00',
   ...:                           '2018-10-28 02:30:00', '2018-10-28 02:45:00',
   ...:                           '2018-10-28 03:00:00', '2018-10-28 03:15:00',
   ...:                           '2018-10-28 03:30:00', '2018-10-28 03:45:00',
   ...:                           '2018-10-28 04:00:00'], freq='infer')
   ...:
   ...: data = list(range(len(index)))
   ...:
   ...: df = pd.DataFrame(data=data,index=index)
   ...: df.index = df.index.tz_localize('Europe/Berlin', ambiguous='infer')
```

I mean, given these timestamps in this order:
```python 
2:00
2:00
2:15
2:15
2:30
2:30
2:45
2:45
```

this change would infer that they represent the following _non-monotonic_ times in UTC:
```python
0:00
1:00
0:15
1:15
0:30
1:30
0:45
1:45
```

It seems just as natural, though, to assume that the data entered is monotonically increasing in time, but with duplicate entries: two entries at 2:00, two entries at 2:15, etc. After all if the data isn't monotonically increasing in time, why should we assume that the first 2:00 necessarily came before the second 2:00?

**Comment by mroeschke** [comment]
Agreed with @Liam3851's assessment here. `infer` only really works if we assume monotonicity throughout the index. Non-monotonic results are hard to assume from the user and hence why `ambiguous` accepts an array of `True/False` values so the user can clarify the intent.

**Comment by mroeschke** [comment]
Thanks for the suggestion @phaabe, but I don't think we want to have `infer` assume anything about non-monotonic  results.

**Comment by BigTava** [comment]
What is the solution to solve the error: AmbiguousTimeError: There are %i dst switches when there should only be 1? This should happen whenever the dataframe has a step other than 1h. For example: 15 min, as shown in the first post.
