### ISSUE TITLE
BUG/compat: accum funcs changed in numpy 1.18

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#29058]
#29057 xfails some tests that are broken with numpy 1.18, which changes the behavior of np.minimum.accumulate on dt64/td64 arrays:

```
s = pd.Series(
            pd.to_datetime(["NaT", "2000-1-2", "NaT", "2000-1-1", "NaT", "2000-1-3"])
        )

>>> np.minimum.accumulate(s.values)  # numpy 1.17
array([                          'NaT', '2000-01-02T00:00:00.000000000',
       '2000-01-02T00:00:00.000000000', '2000-01-01T00:00:00.000000000',
       '2000-01-01T00:00:00.000000000', '2000-01-01T00:00:00.000000000'],
      dtype='datetime64[ns]')

>>> np.accumulate.minimum(s.values)  # numpy 1.18
array(['NaT', 'NaT', 'NaT', 'NaT', 'NaT', 'NaT'], dtype='datetime64[ns]')
```

This will need to be addressed in core.generic._make_cum_function (maybe other places too, not sure)

**Comment by jbrockmendel** [comment]
@MomIsBestFriend the cleanup PRs you're making are great, but I'd encourage you to look at more issues as you get more experienced.  A few issues that you might think about working on are this #29058, #28507, #27829, #23929, #24115, #22218, #27613.

**Comment by MomIsBestFriend** [comment]
Thank you so much! @jbrockmendel
