### ISSUE TITLE
ValueError: DataFrame columns must be unique for orient='records'

### ISSUE THREAD

**Issue by santhoshnumberone** [pandas-dev/pandas#29074]
#### Code Sample

```python
# Extract particular column
selected_dataUrl_columns = pd.DataFrame(dataTableSession.query(dataTable).filter(dataTable.c.dataId.in_(media_id_list)).all())['dataUrl'].reset_index(drop=True)

# combine the column with the active_campaign dataframe
campaign_info = pd.concat([active_campaign[['id','fromdate','todate']].reset_index(drop=True),selected_dataUrl_columns], axis=1)

# convert the dataframe into json
campaign_info_json = campaign_info.to_json(orient='records')
```
I tried 
```
#even with this same error
campaign_info_json = campaign_info.reset_index(drop=True).to_json(orient='records')
```
#### Problem description

[I used `.reset_index(drop=True)` to ` pd.concat` ]

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.1
numpy            : 1.17.3
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 41.4.0
Cython           : 0.29.13
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.3.10
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
</details>

**Comment by WillAyd** [comment]
The records orient writes out the column labels to a dictionary. You can't have duplicate keys in a dictionary, which is why this error gets raises
