### ISSUE TITLE
DOC: mad description incorrectly includes 'numeric_only'

### ISSUE THREAD

**Issue by stackedsax** [pandas-dev/pandas#29079]
#### Problem description

I noticed a small mismatch between the function signature of `mad` and its description here:

* https://pandas-docs.github.io/pandas-docs-travis/reference/api/pandas.DataFrame.mad.html?highlight=mad#pandas.DataFrame.mad

The function signature is correct:

> DataFrame.mad(self, axis=None, skipna=None, level=None)

The description, meanwhile, includes 'numeric_only':

> numeric_only : bool, default None
> Include only float, int, boolean columns. If None, will attempt to use everything, then use only numeric data. Not implemented for Series.

Passing the `numeric_only` parameter to `mad` will throw an error, as one would expect.

It looks like both `mad` and `compound` are using the `@Appender(_num_doc)` decorator, which points to a description that includes the `numeric_only` parameter even though neither of those methods use `numeric_only`.  

The `compound` method is being deprecated, so that may be less of an issue.

There are a couple of different ways I could think to fix it, but I just wanted to confirm that I had this right before I did anything.

**Comment by r0cketr1kky** [comment]
Hi, I would like to work on this.
Does this mean I have to remove the `numeric only` parameter from the mad function in the docs?

**Comment by stackedsax** [comment]
Hi @r0cketr1kky.  As I understand it, yes.  I was just checking that I understood it correctly, though!

**Comment by r0cketr1kky** [comment]
Thanks a lot @stackedsax
