### ISSUE TITLE
df[:0] returns KeyError when index is float64 and non-monotonic

### ISSUE THREAD

**Issue by ghost** [pandas-dev/pandas#29082]
#### Code Sample, a copy-pastable example if possible

```python
>>> df = pd.DataFrame({'a': [3.0, 1.0, 2.0], 'b':[5, 6, 7]}).set_index('a')
>>> df[:0]

KeyError: 0.0
```
#### Problem description

In many cases `df[:0]` effectively returns the metadata for a dataframe, i.e. 
```
Empty DataFrame
Columns: [b]
Index: []
```
However if the dataframe index has type `Float64Index` and is not monotonic then it returns `KeyError`.

#### Expected Output

```
Empty DataFrame
Columns: [b]
Index: []
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 17.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 0.25.1
numpy            : 1.17.3
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 41.4.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by sa02045** [comment]
df=pd.DataFrame({'a': [3.0, 1.0, 2.0], 'b':[5,6,7]})
df.set_index('a') 
it works

**Comment by tjperr** [comment]
TIL, thanks @phofl 🎉

**Comment by mroeschke** [comment]
Closing as the expected behavior described in https://github.com/pandas-dev/pandas/issues/29082#issuecomment-734501986
