### ISSUE TITLE
Running pytest locally 

### ISSUE THREAD

**Issue by farziengineer** [pandas-dev/pandas#29090]
When I run 
```python
 pytest pandas
```
locally, I get the following error.
```python
ImportError while loading conftest '/Users/mohitanand/pandas/pandas/conftest.py'.
pandas/conftest.py:13: in <module>
    import pandas.util._test_decorators as td
pandas/util/_test_decorators.py:183: in <module>
    _skip_if_has_locale(),
pandas/util/_test_decorators.py:101: in _skip_if_has_locale
    lang, _ = locale.getlocale()
../anaconda3/envs/pandas-dev/lib/python3.7/locale.py:587: in getlocale
    return _parse_localename(localename)
../anaconda3/envs/pandas-dev/lib/python3.7/locale.py:495: in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
E   ValueError: unknown locale: UTF-8
```
How do I solve it.
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
pandas           : 0.26.0.dev0+598.g93e8b11e7
numpy            : 1.17.2
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 41.4.0
Cython           : 0.29.13
pytest           : 5.2.1
hypothesis       : 4.36.2
sphinx           : 2.2.0
blosc            : None
feather          : None
xlsxwriter       : 1.2.1
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : 1.2.1
fastparquet      : 0.3.2
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 3.0.0
pandas_gbq       : None
pyarrow          : 0.15.0
pytables         : None
s3fs             : 0.3.4
scipy            : 1.3.1
sqlalchemy       : 1.3.9
tables           : 3.5.1
xarray           : 0.13.0
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.1

</details>

**Comment by TomAugspurger** [comment]
Do you see `('en_US', 'UTF-8')` in the output of

```
import locale

locale.locale_alias
```

Actually... it looks like `locale. getlocale()` is failing? If so there are probably some deeper issues with your Python install / your OS. I'm not sure how to resolve those.

**Comment by farziengineer** [comment]
It is a problem with MacOS. https://stackoverflow.com/questions/38916461/valueerror-unknown-locale-utf-8-when-importing-pandas-in-python-2-7

**Comment by farziengineer** [comment]
`export LC_ALL=en_US.UTF-8`
`export LANG=en_US.UTF-8`
`source ~/.bash_profile`
Solves the issue.

**Comment by alimcmaster1** [comment]
Closing as resolved by user
