### ISSUE TITLE
DataFrame.corrwith(otherDataFrame) has confusing behavior and potential bug

### ISSUE THREAD

**Issue by JiaRu2016** [pandas-dev/pandas#29091]
### Code Sample

```python
import pandas as pd
import numpy as np


f = lambda: np.random.normal(0, 1, n)

df_x = pd.DataFrame({'x1':f(), 'x2':f(), 'x3':f()})
df_y = pd.DataFrame({'y1':f(), 'y2':f()})

df_x.corrwith(df_y)
```
output is 
```
x1   NaN
x2   NaN
x3   NaN
y1   NaN
y2   NaN
dtype: float64
```

### Problem description

[document](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.corrwith.html?highlight=corrwith#pandas.DataFrame.corrwith) of `DataFrame.corrwith` says it "compute pairwise correlation between ... DataFrame with ... DataFrame" and the return type of this method is `Series`.  It is not clear how the pairs of columns/row is choosen to compute correlation.
Moreover, the value it returns are all NaN.

### Expected Outputs

According to this description, I expect it return a DataFrame like this:

|      | x1   | x2   | x3   |
| ---- | ---- | ---- | ---- |
| y1   |      |      |      |
| y2   |      |      |      |

whose `['y1', 'x1']` element is `correlation(df_x['x1'], df_y['y1'] )`

or a multi-indexed Series like this:

| index    | correlation |
| -------- | ----------- |
| (x1, y1) |             |
| (x1, y2) |             |
| (x2, y1) |             |
| (x2, y2) |             |
| (x3, y1) |             |
| (x3, y2) |             |

### Output of pd.show_versions()

<details><summary>details</summary>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.4.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 16.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.14.1
pytz             : 2018.3
dateutil         : 2.6.1
pip              : 19.0.3
setuptools       : 41.0.1
Cython           : 0.29.2
pytest           : 5.1.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10
IPython          : 7.1.1
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.0.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.2.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by TomAugspurger** [comment]
`n` is undefined in your example.

---

The inputs are aligned before computing the correlation. I think the docstring makes this clear.

> DataFrames are first
aligned along both axes before computing the correlations.

```
In [16]: df_x.corrwith(df_y.rename(columns=lambda x: x.replace('y', 'x')))
Out[16]:
x1   -0.590813
x2    0.259464
x3         NaN
dtype: float64
```

Happy to have improvements to the docs, but closing this since I think it's working as expected.
