### ISSUE TITLE
What's new link in the 0.25.2 release description is broken

### ISSUE THREAD

**Issue by dmitriyshashkin** [pandas-dev/pandas#29092]
Not sure whether this should be reported here or in the documentation repository.

"Whatsnew" link in the release description here https://github.com/pandas-dev/pandas/releases leads to the following url https://pandas.pydata.org/pandas-docs/version/0.25/whatsnew/v0.25.2.html which return 404 error.

**Comment by TomAugspurger** [comment]
The docs aren’t up yet. Will be later today.
