### ISSUE TITLE
Misleading error messages when opening inexistent json file

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#29102]
When opening a json file that doesn't exist with `read_json`, we get a `ValueError` with error messages like:

```python
>>> import pandas
>>> pandas.read_json('no_file.json')
ValueError: Unexpected character found when decoding 'null'

>>> pandas.read_json('a_dir/no_file.json')
ValueError: Expected object or value
```

It'd probably be better to raise an exception like:
```
FileNotFoundError: No such file: 'no_file.json'
```

**Comment by farziengineer** [comment]
Hi, @datapythonista can I take this up?

**Comment by datapythonista** [comment]
sure, thanks

**Comment by deepandas11** [comment]
Hi! Would like to work on this if it is still open.

**Comment by sathyz** [comment]
take

**Comment by kevin-meyers** [comment]
Hey @sathyz if you don't finish it by the end of the month I think I'll give it a shot.

**Comment by devjeetr** [comment]
take

**Comment by vampypandya** [comment]
Is this issue still open? Can I take it?

**Comment by cheungje** [comment]
Hi, I would like to to take this issue if it's still not resolved.

**Comment by cheungje** [comment]
take

**Comment by mohitanand001** [comment]
Anyone willing to take this up might want to go through this thread once. 
https://github.com/pandas-dev/pandas/pull/29104
I had taken this 2 years back, but it was closed after some discussion.

**Comment by janosh** [comment]
Would a PR for this still be welcomed? Reading @29104 makes it sounds like the conclusion was there is no good solution but tbh I don't understand why not.

**Comment by MarcoGorelli** [comment]
If I've understood the discussion correctly, then I think that at least for extensioned json files, it should be possible to assume user intent and raise an informative error message if the file doesn't exist

**Comment by janosh** [comment]
@MarcoGorelli So if I submit a PR that raises `FNFError`

```py
if (
    isinstance(filepath_or_buffer, str)
    and filepath_or_buffer.lower().endswith(('.json', '.json.gz', '.json.bz2'))
    and not isfile(filepath_or_buffer)
)

```

that would be acceptable? Seems like a definite improvement over current behavior to me.

**Comment by MarcoGorelli** [comment]
TBH that would look good to me, I often run into this error when trying to read json files - cc @gfyoung @WillAyd any further thoughts on this?
