### ISSUE TITLE
conflict

### ISSUE THREAD

**Issue by logan-lieou** [pandas-dev/pandas#29123]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

df = pd.read_csv('file.csv')
```
#### Problem description

The problem I ran into is that it's telling me that read_csv is not a thing, I'm not sure what's going on here.

![image](https://user-images.githubusercontent.com/20232318/67173824-922af700-f385-11e9-8c8e-0dd3c03049e4.png)

#### Expected Output
?
#### Output of ``pd.show_versions()``

![image](https://user-images.githubusercontent.com/20232318/67174042-3dd44700-f386-11e9-8584-bd0fa750cfd6.png)
<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by WillAyd** [comment]
This appears that you have a file called `pandas.py` that is most likely getting imported instead. If you rename that file should be OK
