### ISSUE TITLE
NDFrame.interpolate(): variable 'ax' not assigned when axis='index'

### ISSUE THREAD

**Issue by ellequelle** [pandas-dev/pandas#29132]
The `NDFrame.interpolate` function fails when passing a string as axis. Example:

```python
>>> import numpy as np
>>> import pandas as pd
>>> df = pd.DataFrame(np.zeros((3,2)), columns=['a','b'])
>>> df.iloc[1] = np.nan
>>> df
     a    b
0  0.0  0.0
1  NaN  NaN
2  0.0  0.0
>>> df.interpolate(axis=0)
     a    b
0  0.0  0.0
1  0.0  0.0
2  0.0  0.0
>>> df.interpolate(axis='index')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lehanson/anaconda3/envs/plots/lib/python3.7/site-packages/pandas/core/generic.py", line 7006, in interpolate
    ax = _maybe_transposed_self._get_axis_number(ax)
UnboundLocalError: local variable 'ax' referenced before assignment
```

From the documentation and from the function itself, it looks like `df.interpolate(axis='index')` was intended to work, but that maybe someone accidentally deleted a line in generic.py? The function seems to work properly if I add `ax = axis` in the else block here: 
https://github.com/pandas-dev/pandas/blob/171c71611886aab8549a8620c5b0071a129ad685/pandas/core/generic.py#L6998-L7006

I am using pandas version 0.25.1

**Comment by TomAugspurger** [comment]
Thanks for the report, confirmed on master.

We should have an `axis = self._get_axis_number(axis)` at the start of `NDFrame.interpolate` (and a whatsnew note & test to ensure we don't regress).

**Comment by gabriellm1** [comment]
I'll happily take that issue

**Comment by ellequelle** [comment]
@TomAugspurger do you mean something like this? Also: there doesn't seem to be a whatsnew file since 0.25.2, does this go into v0.25.3.rst?

```
axis = self._get_axis_number(axis)
if axis == 0:
    ax = self._info_axis_name
    _maybe_transposed_self = self
elif axis == 1:
    _maybe_transposed_self = self.T
    ax = 1
else:
    ax = axis
    _maybe_transposed_self = self
ax = _maybe_transposed_self._get_axis_number(ax)
```

**Comment by TomAugspurger** [comment]
whatsnew will go in v1.0.0.rst

**Comment by coderkalyan** [comment]
Hi, I'm new to pandas development (but a fan). Can I try this as part of #hacktoberfest, and where do I start?
