### ISSUE TITLE
DOC: contributors section for v0.24.0 shows too many contributors

### ISSUE THREAD

**Issue by jgehrcke** [pandas-dev/pandas#29151]
Found my name in https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.24.0.html#contributors. Did not contribute to that release. Contributed to 0.25.0 (that section is empty, though, see https://github.com/pandas-dev/pandas/issues/27687).

In the `doc/source/whatsnew/v0.24.0.rst` the culprit seems to be `contributors:: v0.23.4..HEAD`, let's change `HEAD` to `v0.24.0`?

**Comment by jorisvandenbossche** [comment]
Closed by https://github.com/pandas-dev/pandas/pull/29152
