### ISSUE TITLE
ImportError: Can't determine version for bottleneck

### ISSUE THREAD

**Issue by mlangiu** [pandas-dev/pandas#29181]
```
conda create -n PANDAS pandas
activate PANDAS
python
```
```python
import pandas
```
Gives me
```python
ImportError: Can't determine version for bottleneck
```

#### Output of conda list
<details>
# Name                    Version                   Build  Channel
blas                      1.0                         mkl

ca-certificates           2019.10.16                    0

certifi                   2019.9.11                py37_0

icc_rt                    2019.0.0             h0cc432a_1

intel-openmp              2019.4                      245

mkl                       2019.4                      245

mkl-service               2.3.0            py37hb782905_0

mkl_fft                   1.0.14           py37h14836fe_0

mkl_random                1.1.0            py37h675688f_0

numpy                     1.16.5           py37h19fb1c0_0

numpy-base                1.16.5           py37hc3f5095_0

openssl                   1.1.1d               he774522_3

pandas                    0.25.2           py37ha925a31_0

pip                       19.3.1                   py37_0

python                    3.7.4                h5263a28_0

python-dateutil           2.8.0                    py37_0

pytz                      2019.3                     py_0

setuptools                41.4.0                   py37_0

six                       1.12.0                   py37_0

sqlite                    3.30.0               he774522_0

vc                        14.1                 h0510ff6_4

vs2015_runtime            14.16.27012          hf0eaf9b_0

wheel                     0.33.6                   py37_0

wincertstore              0.2                      py37_0

</details>

**Comment by mlangiu** [comment]
Realized I wasn't running `python` but `ipython`, probably with an old version.
`conda install ipython` solved this problem for me.

**Comment by boardtc** [comment]
I did a conda update pandas at the anaconda prompt today to update from 0.23.x to 0.25.3 and now I get this error in Spyder importing pandas

**Comment by adamdbenson** [comment]
I had the same message but found installing it `[conda|pip] install Bottleneck` fixed it

**Comment by kknjio** [comment]
I solved it using conda install --all.
