### ISSUE TITLE
CI Linux py36_locale_slow Hanging

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#29198]
Seems to be hanging on miniconda install script:

https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=19314&view=logs&jobId=5ddd427e-1f95-5998-4195-7ffbeb9b114d&taskId=2d75e2dd-4c84-5053-e835-c449aeb02662&lineStart=256&lineEnd=257&colStart=1&colEnd=1

Interestingly enough the Linux py36_locale_slow_old_np seems to be OK

**Comment by jbrockmendel** [comment]
the local_slow_old_np is hanging in some builds too, I'm seeing 
```
E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gcc-9/libx32quadmath0_9.1.0-2ubuntu2~16.04_amd64.deb  404  Not Found [IP: 91.189.95.83 80]
```

I get the same 404 when I try to access it locally

**Comment by WillAyd** [comment]
Makes sense as that version doesn't appear there anymore (looks like 9.2)

http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gcc-9/

Of course the debug build I have seems to run OK, so maybe a temporary issue working its way through CI? Not sure

**Comment by WillAyd** [comment]
The 36 builds were failing before. Now it looks like the 37 build is?

Wonder if there's just something going on on the conda side that we need to wait out in terms of resolving these URLs

**Comment by WillAyd** [comment]
I think this is just a temporary blip in the radar probably need to wait out
