### ISSUE TITLE
MyPy Error Codes

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#29197]
mypy 0.73 came with support for error codes:

http://mypy-lang.blogspot.com/2019/09/mypy-730-released.html

I think we should add these to CI and update docs to require these going forward for any `type: ignore` statements

@simonjayhawkins

**Comment by simonjayhawkins** [comment]
i did this in https://github.com/pandas-dev/pandas/pull/28339/commits/32f1780356a446f8d8b5432cb8562a54221caec5 but causes F821 errors and needs to be silenced.

reverted after a couple of weeks in https://github.com/pandas-dev/pandas/pull/28339/commits/34bf08cdd3a6097421268addd2ef67c0bcf3ed2b as frustrating not having F821 linting in the ide.

so -1 and revisit once flake8 supports mypy errors codes
