### ISSUE TITLE
In read_excel parse_date=False is not working

### ISSUE THREAD

**Issue by ajphukan** [pandas-dev/pandas#29217]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
df = pd.read_file('filename.xlsx', header= None, skiprows=1, parse_dates=False)

```
#### Problem description

In read_excel   parse_date default value is False , but still it is parsing the date. 
 

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.2
numpy            : 1.14.4
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 41.4.0
Cython           : None
pytest           : 5.2.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.0.8
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None

</details>

**Comment by hwalinga** [comment]
Can you maybe share the file (or something we can reproduce this with) that causes this problem?

The `parse_dates` can only be used in a specific case. Citing the documentation:

>But if you have a column of strings that _look_ like dates (but are not actually formatted as dates in excel), ...

So, this can only be used for columns that have strings that might be interpreted as dates, and not for column that are already the date type in excel itself.

**Comment by ajphukan** [comment]
Input sample you can use combination of date and simple string 
`
col
--
aaaa
12/10/2019
ppp
cc
12/10/2019

`

Output  that I am getting:
`
                    0
0                 aaaa
1  2019-12-10 00:00:00
2                  ppp
3                   cc
4  2019-12-10 00:00:00
`

**Comment by hwalinga** [comment]
I was looking for the actual binary file 'filename.xlsx'.

**Comment by gfyoung** [comment]
My guess is that the Excel file is defining the data format as date:

https://github.com/pandas-dev/pandas/blob/bc020f638a88778c289cdfd20a660f25ad843dd5/pandas/io/excel/_xlrd.py#L59-L83

For those types of cells, we are rendering those as date because Excel told us to do so.  `parse_dates` applies to entire columns i.e. we convert the entire column of data to `date`.

**Comment by ajphukan** [comment]
@gfyoung Yes the problem is with the microsoft excel, It is  detecting the cell type automatically to date, I had to convert it to Text to avoid the auto parsing of cell to date type. 

Can we include this Info in the doc so that new users can get the answer without raising issue ..

**Comment by gfyoung** [comment]
@ajphukan : You are more than welcome to contribute something!

**Comment by hvp004** [comment]
@ajphukan , are you working on it? If not, I would like to. @gfyoung

**Comment by vishwasshrikhande** [comment]
I want to help, how do i start by adding this info to the doc? Any help

**Comment by hwalinga** [comment]
https://pandas.pydata.org/pandas-docs/stable/development/contributing.html

**Comment by biddwan09** [comment]
Hi @hwalinga can I work on this issue ?
