### ISSUE TITLE
CI: include pyarrow 0.15.0 / latest release in one of the builds

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#29223]
From a quick look, it seems we are not testing the latest version of pyarrow on our CI.

**Comment by alimcmaster1** [comment]
Any particular build you suggest adding this to? Or are you thinking a new one? @jorisvandenbossche

**Comment by jorisvandenbossche** [comment]
@alimcmaster1 sorry, forgot to answer here. I don't have a particular one in mind (but probably we need conda-forge for a recent version, which might complicate things). Looking into this now.
