### ISSUE TITLE
ml.plots.stresses() transforms input series Evaporation

### ISSUE THREAD

**Issue by marcovanbaar** [pandas-dev/pandas#29253]
The original series is transformed with the parameter "recharge_f"
While I expect te function ml.plots.stresses() to plot the original series.

**Comment by simonjayhawkins** [comment]
I assume this should have been logged at https://github.com/pastas/pastas. if not ping and i'll reopen

**Comment by marcovanbaar** [comment]
Sorry, wrong Pastas 😀

Op ma 28 okt. 2019 15:25 schreef Simon Hawkins <notifications@github.com>:
