### ISSUE TITLE
Fix SS06 Issues in docstrings

### ISSUE THREAD

**Issue by profwacko** [pandas-dev/pandas#29254]
Fix docstrings where summary should fit in a single line. 

From: #27977, most of these errors should just be formatting issues where there are no single line summaries. After setting up and generating the SS06 errors with `python scripts/validate_docstrings.py --errors=SS06`, the workflow I would suggest is: 

0. **Read through comments on this issue to check and see if you are doing any duplicate work.** 
1. Pick around 10 docstrings to work on and comment those particular docstrings here
1. search for the specific function docstrings in the documentation (https://pandas.pydata.org/pandas-docs/stable/index.html)  
1. search for the corresponding lines in the *.py that need to be edited
1. edit summary to fit on one line
1. double check changes with `python scripts/validate_docstrings.py <your-function-or-method>` 

Here are all the current errors after running `python ./scripts/validate_docstrings.py --errors=SS06 `, will place a check once your PRs referencing this issue have been merged:
- [ ] `pandas.tseries.offsets.CustomBusinessDay: Summary should fit in a single line`
- [ ] `pandas.tseries.offsets.SemiMonthEnd: Summary should fit in a single line`
- [ ] `pandas.tseries.offsets.SemiMonthBegin: Summary should fit in a single line`
- [ ] `pandas.tseries.offsets.LastWeekOfMonth: Summary should fit in a single line`
- [ ] `pandas.tseries.offsets.FY5253Quarter: Summary should fit in a single line`
- [ ] `pandas.tseries.offsets.BDay.base: Summary should fit in a single line`
- [ ] `pandas.tseries.offsets.BMonthEnd.base: Summary should fit in a single line`
- [ ] `pandas.tseries.offsets.BMonthBegin.base: Summary should fit in a single line`
- [ ] `pandas.tseries.offsets.CBMonthEnd.base: Summary should fit in a single line`
- [ ] `pandas.tseries.offsets.CBMonthEnd.apply_index: Summary should fit in a single line`
- [ ] `pandas.tseries.offsets.CBMonthBegin.base: Summary should fit in a single line`
- [ ] `pandas.tseries.offsets.CBMonthBegin.apply_index: Summary should fit in a single line`
- [ ] `pandas.tseries.offsets.CDay: Summary should fit in a single line`
- [ ] `pandas.tseries.offsets.CDay.base: Summary should fit in a single line`
- [ ] `pandas.tseries.frequencies.to_offset: Summary should fit in a single line`
- [ ] `pandas.Series.to_period: Summary should fit in a single line`
- [ ] `pandas.Series.transform: Summary should fit in a single line`
- [ ] `pandas.Series.describe: Summary should fit in a single line`
- [ ] `pandas.Series.kurt: Summary should fit in a single line`
- [ ] `pandas.Series.skew: Summary should fit in a single line`
- [ ] `pandas.Series.kurtosis: Summary should fit in a single line`
- [ ] `pandas.Series.is_monotonic: Summary should fit in a single line`
- [ ] `pandas.Series.is_monotonic_increasing: Summary should fit in a single line`
- [ ] `pandas.Series.is_monotonic_decreasing: Summary should fit in a single line`
- [ ] `pandas.Series.align: Summary should fit in a single line`
- [ ] `pandas.Series.first: Summary should fit in a single line`
- [ ] `pandas.Series.last: Summary should fit in a single line`
- [ ] `pandas.Series.reindex: Summary should fit in a single line`
- [ ] `pandas.Series.filter: Summary should fit in a single line`
- [ ] `pandas.Series.argsort: Summary should fit in a single line`
- [ ] `pandas.Series.unstack: Summary should fit in a single line`
- [ ] `pandas.Series.explode: Summary should fit in a single line`
- [ ] `pandas.Series.update: Summary should fit in a single line`
- [ ] `pandas.Series.slice_shift: Summary should fit in a single line`
- [ ] `pandas.Series.dt.date: Summary should fit in a single line`
- [ ] `pandas.Series.dt.timetz: Summary should fit in a single line`
- [ ] `pandas.Series.dt.tz_localize: Summary should fit in a single line`
- [ ] `pandas.Series.str.center: Summary should fit in a single line`
- [ ] `pandas.Series.str.decode: Summary should fit in a single line`
- [ ] `pandas.Series.str.encode: Summary should fit in a single line`
- [ ] `pandas.Series.str.extractall: Summary should fit in a single line`
- [ ] `pandas.Series.str.find: Summary should fit in a single line`
- [ ] `pandas.Series.str.index: Summary should fit in a single line`
- [ ] `pandas.Series.str.len: Summary should fit in a single line`
- [ ] `pandas.Series.str.ljust: Summary should fit in a single line`
- [ ] `pandas.Series.str.normalize: Summary should fit in a single line`
- [ ] `pandas.Series.str.replace: Summary should fit in a single line`
- [ ] `pandas.Series.str.rfind: Summary should fit in a single line`
- [ ] `pandas.Series.str.rindex: Summary should fit in a single line`
- [ ] `pandas.Series.str.rjust: Summary should fit in a single line`
- [ ] `pandas.Series.str.translate: Summary should fit in a single line`
- [ ] `pandas.Series.str.wrap: Summary should fit in a single line`
- [ ] `pandas.Series.str.get_dummies: Summary should fit in a single line`
- [ ] `pandas.Series.str: Summary should fit in a single line`
- [ ] `pandas.Index.str: Summary should fit in a single line`
- [ ] `pandas.Series.plot: Summary should fit in a single line`
- [ ] `pandas.Timestamp.resolution: Summary should fit in a single line`
- [ ] `pandas.Timestamp.fromordinal: Summary should fit in a single line`
- [ ] `pandas.Timestamp.isoweekday: Summary should fit in a single line`
- [ ] `pandas.Timestamp.normalize: Summary should fit in a single line`
- [ ] `pandas.Timestamp.now: Summary should fit in a single line`
- [ ] `pandas.Timestamp.to_julian_date: Summary should fit in a single line`
- [ ] `pandas.Timestamp.today: Summary should fit in a single line`
- [ ] `pandas.Timestamp.tz_localize: Summary should fit in a single line`
- [ ] `pandas.Timestamp.weekday: Summary should fit in a single line`
- [ ] `pandas.Timedelta.isoformat: Summary should fit in a single line`
- [ ] `pandas.Period.strftime: Summary should fit in a single line`
- [ ] `pandas.Interval.closed: Summary should fit in a single line`
- [ ] `pandas.arrays.IntervalArray.left: Summary should fit in a single line`
- [ ] `pandas.arrays.IntervalArray.right: Summary should fit in a single line`
- [ ] `pandas.arrays.IntervalArray.closed: Summary should fit in a single line`
- [ ] `pandas.arrays.IntervalArray.length: Summary should fit in a single line`
- [ ] `pandas.arrays.IntervalArray.is_non_overlapping_monotonic: Summary should fit in a single line`
- [ ] `pandas.arrays.IntervalArray.set_closed: Summary should fit in a single line`
- [ ] `pandas.read_msgpack: Summary should fit in a single line`
- [ ] `pandas.ExcelWriter: Summary should fit in a single line`
- [ ] `pandas.HDFStore.append: Summary should fit in a single line`
- [ ] `pandas.io.stata.StataReader.value_labels: Summary should fit in a single line`
- [ ] `pandas.io.stata.StataReader.variable_labels: Summary should fit in a single line`
- [ ] `pandas.core.resample.Resampler.transform: Summary should fit in a single line`
- [ ] `pandas.core.resample.Resampler.pipe: Summary should fit in a single line`
- [ ] `pandas.plotting.andrews_curves: Summary should fit in a single line`
- [ ] `pandas.plotting.plot_params: Summary should fit in a single line`
- [ ] `pandas.errors.EmptyDataError: Summary should fit in a single line`
- [ ] `pandas.errors.UnsortedIndexError: Summary should fit in a single line`
- [ ] `pandas.errors.UnsupportedFunctionCall: Summary should fit in a single line`
- [ ] `pandas.api.types.union_categoricals: Summary should fit in a single line`
- [ ] `pandas.api.types.infer_dtype: Summary should fit in a single line`
- [ ] `pandas.api.types.is_datetimetz: Summary should fit in a single line`
- [ ] `pandas.melt: Summary should fit in a single line`
- [ ] `pandas.pivot_table: Summary should fit in a single line`
- [ ] `pandas.crosstab: Summary should fit in a single line`
- [ ] `pandas.qcut: Summary should fit in a single line`
- [ ] `pandas.merge_ordered: Summary should fit in a single line`
- [ ] `pandas.merge_asof: Summary should fit in a single line`
- [ ] `pandas.concat: Summary should fit in a single line`
- [ ] `pandas.unique: Summary should fit in a single line`
- [ ] `pandas.bdate_range: Summary should fit in a single line`
- [ ] `pandas.period_range: Summary should fit in a single line`
- [ ] `pandas.timedelta_range: Summary should fit in a single line`
- [ ] `pandas.infer_freq: Summary should fit in a single line`
- [ ] `pandas.Index: Summary should fit in a single line`
- [ ] `pandas.Index.is_monotonic_increasing: Summary should fit in a single line`
- [ ] `pandas.Index.is_monotonic_decreasing: Summary should fit in a single line`
- [ ] `pandas.Index.copy: Summary should fit in a single line`
- [ ] `pandas.Index.identical: Summary should fit in a single line`
- [ ] `pandas.Index.reindex: Summary should fit in a single line`
- [x] `pandas.Index.where: Summary should fit in a single line`
- [ ] `pandas.Index.unique: Summary should fit in a single line`
- [ ] `pandas.Index.astype: Summary should fit in a single line`
- [ ] `pandas.Index.to_series: Summary should fit in a single line`
- [ ] `pandas.Index.join: Summary should fit in a single line`
- [ ] `pandas.Index.difference: Summary should fit in a single line`
- [ ] `pandas.Index.asof_locs: Summary should fit in a single line`
- [ ] `pandas.Index.get_indexer: Summary should fit in a single line`
- [ ] `pandas.Index.get_indexer_non_unique: Summary should fit in a single line`
- [ ] `pandas.Index.get_value: Summary should fit in a single line`
- [ ] `pandas.Index.slice_indexer: Summary should fit in a single line`
- [ ] `pandas.Int64Index: Summary should fit in a single line`
- [ ] `pandas.UInt64Index: Summary should fit in a single line`
- [ ] `pandas.Float64Index: Summary should fit in a single line`
- [ ] `pandas.IntervalIndex.left: Summary should fit in a single line`
- [ ] `pandas.IntervalIndex.right: Summary should fit in a single line`
- [ ] `pandas.IntervalIndex.closed: Summary should fit in a single line`
- [ ] `pandas.IntervalIndex.length: Summary should fit in a single line`
- [ ] `pandas.IntervalIndex.is_non_overlapping_monotonic: Summary should fit in a single line`
- [ ] `pandas.IntervalIndex.get_indexer: Summary should fit in a single line`
- [ ] `pandas.IntervalIndex.set_closed: Summary should fit in a single line`
- [ ] `pandas.MultiIndex.set_levels: Summary should fit in a single line`
- [ ] `pandas.MultiIndex.set_codes: Summary should fit in a single line`
- [ ] `pandas.MultiIndex.to_hierarchical: Summary should fit in a single line`
- [ ] `pandas.MultiIndex.sortlevel: Summary should fit in a single line`
- [ ] `pandas.MultiIndex.remove_unused_levels: Summary should fit in a single line`
- [ ] `pandas.MultiIndex.get_loc: Summary should fit in a single line`
- [ ] `pandas.MultiIndex.get_loc_level: Summary should fit in a single line`
- [ ] `pandas.MultiIndex.get_indexer: Summary should fit in a single line`
- [ ] `pandas.MultiIndex.get_level_values: Summary should fit in a single line`
- [ ] `pandas.DatetimeIndex: Summary should fit in a single line`
- [ ] `pandas.DatetimeIndex.date: Summary should fit in a single line`
- [ ] `pandas.DatetimeIndex.timetz: Summary should fit in a single line`
- [ ] `pandas.DatetimeIndex.inferred_freq: Summary should fit in a single line`
- [ ] `pandas.DatetimeIndex.indexer_at_time: Summary should fit in a single line`
- [ ] `pandas.DatetimeIndex.indexer_between_time: Summary should fit in a single line`
- [ ] `pandas.DatetimeIndex.tz_localize: Summary should fit in a single line`
- [ ] `pandas.DatetimeIndex.to_perioddelta: Summary should fit in a single line`
- [ ] `pandas.DatetimeIndex.to_pydatetime: Summary should fit in a single line`
- [ ] `pandas.DatetimeIndex.to_series: Summary should fit in a single line`
- [ ] `pandas.TimedeltaIndex: Summary should fit in a single line`
- [ ] `pandas.TimedeltaIndex.components: Summary should fit in a single line`
- [ ] `pandas.TimedeltaIndex.inferred_freq: Summary should fit in a single line`
- [ ] `pandas.TimedeltaIndex.to_pytimedelta: Summary should fit in a single line`
- [ ] `pandas.TimedeltaIndex.to_series: Summary should fit in a single line`
- [ ] `pandas.PeriodIndex: Summary should fit in a single line`
- [ ] `pandas.Grouper: Summary should fit in a single line`
- [ ] `pandas.core.groupby.GroupBy.pipe: Summary should fit in a single line`
- [ ] `pandas.core.groupby.GroupBy.nth: Summary should fit in a single line`
- [ ] `pandas.core.groupby.DataFrameGroupBy.describe: Summary should fit in a single line`
- [ ] `pandas.core.groupby.DataFrameGroupBy.filter: Summary should fit in a single line`
- [ ] `pandas.core.groupby.DataFrameGroupBy.idxmax: Summary should fit in a single line`
- [ ] `pandas.core.groupby.DataFrameGroupBy.idxmin: Summary should fit in a single line`
- [ ] `pandas.core.groupby.DataFrameGroupBy.nunique: Summary should fit in a single line`
- [ ] `pandas.core.groupby.DataFrameGroupBy.skew: Summary should fit in a single line`
- [ ] `pandas.core.groupby.SeriesGroupBy.is_monotonic_increasing: Summary should fit in a single line`
- [ ] `pandas.core.groupby.SeriesGroupBy.is_monotonic_decreasing: Summary should fit in a single line`
- [ ] `pandas.core.groupby.DataFrameGroupBy.corrwith: Summary should fit in a single line`
- [x] `pandas.io.formats.style.Styler.from_custom_template: Summary should fit in a single line`
- [ ] `pandas.io.formats.style.Styler.env: Summary should fit in a single line`
- [ ] `pandas.io.formats.style.Styler.template: Summary should fit in a single line`
- [ ] `pandas.io.formats.style.Styler.loader: Summary should fit in a single line`
- [x] `pandas.io.formats.style.Styler.apply: Summary should fit in a single line`
- [x] `pandas.io.formats.style.Styler.applymap: Summary should fit in a single line`
- [x] `pandas.io.formats.style.Styler.where: Summary should fit in a single line`
- [x] `pandas.io.formats.style.Styler.set_properties: Summary should fit in a single line`
- [x] `pandas.io.formats.style.Styler.clear: Summary should fit in a single line`
- [x] `pandas.io.formats.style.Styler.background_gradient: Summary should fit in a single line`
- [x] `pandas.io.formats.style.Styler.use: Summary should fit in a single line`
- [ ] `pandas.DataFrame: Summary should fit in a single line`
- [ ] `pandas.DataFrame.transform: Summary should fit in a single line`
- [ ] `pandas.DataFrame.corrwith: Summary should fit in a single line`
- [ ] `pandas.DataFrame.describe: Summary should fit in a single line`
- [ ] `pandas.DataFrame.kurt: Summary should fit in a single line`
- [ ] `pandas.DataFrame.kurtosis: Summary should fit in a single line`
- [ ] `pandas.DataFrame.skew: Summary should fit in a single line`
- [ ] `pandas.DataFrame.align: Summary should fit in a single line`
- [ ] `pandas.DataFrame.drop_duplicates: Summary should fit in a single line`
- [ ] `pandas.DataFrame.duplicated: Summary should fit in a single line`
- [x] `pandas.DataFrame.filter: Summary should fit in a single line`
- [x] `pandas.DataFrame.first: Summary should fit in a single line`
- [x] `pandas.DataFrame.idxmax: Summary should fit in a single line`
- [x] `pandas.DataFrame.idxmin: Summary should fit in a single line`
- [x] `pandas.DataFrame.last: Summary should fit in a single line`
- [x] `pandas.DataFrame.reindex: Summary should fit in a single line`
- [x] `pandas.DataFrame.pivot_table: Summary should fit in a single line`
- [x] `pandas.DataFrame.reorder_levels: Summary should fit in a single line`
- [x] `pandas.DataFrame.unstack: Summary should fit in a single line`
- [x] `pandas.DataFrame.melt: Summary should fit in a single line`
- [x] `pandas.DataFrame.slice_shift: Summary should fit in a single line`
- [x] `pandas.DataFrame.to_period: Summary should fit in a single line`
- [x] `pandas.DataFrame.plot: Summary should fit in a single line`
- [x] `pandas.DataFrame.sparse.density: Summary should fit in a single line`
- [x] `pandas.DataFrame.style: Summary should fit in a single line`
- [x] `pandas.Series.as_blocks: Summary should fit in a single line`
- [x] `pandas.Series.ix: Summary should fit in a single line`
- [x] `pandas.Series.ptp: Summary should fit in a single line`
- [x] `pandas.DataFrame.as_blocks: Summary should fit in a single line`
- [x] `pandas.DataFrame.ix: Summary should fit in a single line`

**Comment by profwacko** [comment]
I'll start with the bottom 10 errors:

- [ ]  pandas.DataFrame.slice_shift: Summary should fit in a single line
- [ ]  pandas.DataFrame.to_period: Summary should fit in a single line
- [ ]  pandas.DataFrame.plot: Summary should fit in a single line
- [ ]  pandas.DataFrame.sparse.density: Summary should fit in a single line
- [ ]  pandas.DataFrame.style: Summary should fit in a single line
- [ ]  pandas.Series.as_blocks: Summary should fit in a single line
- [ ]  pandas.Series.ix: Summary should fit in a single line
- [ ]  pandas.Series.ptp: Summary should fit in a single line
- [ ]  pandas.DataFrame.as_blocks: Summary should fit in a single line
- [ ]  pandas.DataFrame.ix: Summary should fit in a single line

**Comment by mcalingo** [comment]
Hope you don't mind if I work on the next 10 (from the bottom)

- [ ] pandas.DataFrame.filter: Summary should fit in a single line
- [ ] pandas.DataFrame.first: Summary should fit in a single line
- [ ] pandas.DataFrame.idxmax: Summary should fit in a single line
- [ ] pandas.DataFrame.idxmin: Summary should fit in a single line
- [ ] pandas.DataFrame.last: Summary should fit in a single line
- [ ] pandas.DataFrame.reindex: Summary should fit in a single line
- [ ] pandas.DataFrame.pivot_table: Summary should fit in a single line
- [ ] pandas.DataFrame.reorder_levels: Summary should fit in a single line
- [ ] pandas.DataFrame.unstack: Summary should fit in a single line
- [ ] pandas.DataFrame.melt: Summary should fit in a single line

**Comment by profwacko** [comment]
I'll take in the next bottom 10 for another PR:

- [ ]  pandas.DataFrame: Summary should fit in a single line
- [ ]  pandas.DataFrame.transform: Summary should fit in a single line
- [ ]  pandas.DataFrame.corrwith: Summary should fit in a single line
- [ ]  pandas.DataFrame.describe: Summary should fit in a single line
- [ ]  pandas.DataFrame.kurt: Summary should fit in a single line
- [ ]  pandas.DataFrame.kurtosis: Summary should fit in a single line
- [ ]  pandas.DataFrame.skew: Summary should fit in a single line
- [ ]  pandas.DataFrame.align: Summary should fit in a single line
- [ ]  pandas.DataFrame.drop_duplicates: Summary should fit in a single line
- [ ]  pandas.DataFrame.duplicated: Summary should fit in a single line

**Comment by deepandas11** [comment]
Working on 9, as my first contribution to pandas.

- [ ]  pandas.DataFrame: Summary should fit in a single line
- [ ]  pandas.DataFrame.corrwith: Summary should fit in a single line
- [ ]  pandas.DataFrame.describe: Summary should fit in a single line
- [ ]  pandas.DataFrame.kurt: Summary should fit in a single line
- [ ]  pandas.DataFrame.kurtosis: Summary should fit in a single line
- [ ]  pandas.DataFrame.skew: Summary should fit in a single line
- [ ]  pandas.DataFrame.align: Summary should fit in a single line
- [ ]  pandas.DataFrame.drop_duplicates: Summary should fit in a single line
- [ ]  pandas.DataFrame.duplicated: Summary should fit in a single line

**Comment by profwacko** [comment]
Hi @deepandas11, looks like we edited the same issues in two different pull requests

**Comment by deepandas11** [comment]
Yes. I noticed this now. Sorry for the trouble and the suggestion makes complete sense.

**Comment by MomIsBestFriend** [comment]
@profwacko I forgot to mention the ones I'm working on, my [PR](https://github.com/pandas-dev/pandas/pull/29283) already got approved the items I was working on are:

- [x] pandas.io.formats.style.Styler.from_custom_template
- [x] pandas.io.formats.style.Styler.apply
- [x] pandas.io.formats.style.Styler.applymap
- [x] pandas.io.formats.style.Styler.set_properties
- [x] pandas.io.formats.style.Styler.clear
- [x] pandas.io.formats.style.Styler.background_gradient
- [x] pandas.io.formats.style.Styler.use
- [x] pandas.io.formats.style.where

Sorry I forgot to say what I was working on, I'm really new to this.

**Comment by ericmariasis** [comment]
The following are still unchecked but appear to be fixed or obsolete.

- [ ]  pandas.tseries.offsets.CustomBusinessDay: Summary should fit in a single line

- [ ]  pandas.Series.describe: Summary should fit in a single line

- [ ] pandas.Series.kurt: Summary should fit in a single line

- [ ]  pandas.Series.skew: Summary should fit in a single line

- [ ] pandas.Series.kurtosis: Summary should fit in a single line

- [ ] pandas.core.groupby.SeriesGroupBy.is_monotonic_increasing: Summary should fit in a single line

- [ ] pandas.Series.is_monotonic_increasing: Summary should fit in a single line

 
- [ ] pandas.Series.align: Summary should fit in a single line

 

- [ ] pandas.Series.first: Summary should fit in a single line

 

- [ ] pandas.Series.last: Summary should fit in a single line
