### ISSUE TITLE
[Minor Fix][Doc]What's New in 1.0.0

### ISSUE THREAD

**Issue by sara-02** [pandas-dev/pandas#29274]
#### Problem description
Minor typo under the [Dedicated-string-data-type](https://dev.pandas.io/docs/whatsnew/v1.0.0.html#dedicated-string-data-type) warning, it should be `StringDtype is currently considered experimental.` instead of `StringDtype` ~and~ `is currently considered experimental.`

**Comment by mroeschke** [comment]
Good catch. PR's welcome!

**Comment by sara-02** [comment]
@mroeschke Done https://github.com/pandas-dev/pandas/pull/29281
but IDK how to run tests and `black pandas` for the PR.
