### ISSUE TITLE
Reduce Benchmark Times of stat_ops, particularly kendall correlation

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#29270]
ref #29165  the stat_ops benchmarks add a significant amount of time to the ASV runs. The "kendall" correlation method in particular takes over 10 seconds per run in some cases, and there are at least 4 occurrences of this. So for that method alone 40s across 4 runs per benchmark suite would be close to 3 minutes just for those benchmarks

There are a few others mixed in there as well that can be tuned. I think a .2 ms runtime would be ideal:

https://pandas.pydata.org/speed/pandas/#summarylist?sort=1&dir=desc

Of course making that method faster to be in line with the rest of the correlation methods is an option as well and this is mentioned by @dsaxton in #28329. Depending on how much effort that is might be OK to move the benchmark first and align back if ever improved

**Comment by deepandas11** [comment]
Hello! I would like to work on this. I understand that we can change the number of times it is called in the asv setup, but I am not really sure what you mean by moving the benchmark?

Sorry for the extra trouble. I am really new at this.

**Comment by WillAyd** [comment]
kendall is much slower than all of the other methods, so it might make sense to break that off from the parametrization if it makes the runtime more reasonable, at least until the performance of it gets improved
