### ISSUE TITLE
combination of groupby & nlargest gives different results based on the number used

### ISSUE THREAD

**Issue by aalloul** [pandas-dev/pandas#29284]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
# out is a dataframe with columns A,B,C,D (all integers) and has 390,846 rows
#  this is the result of a out.head()

# 46.0               276   76514.0  5.293944e+07
# 46.0               276   23564.0  3.330653e+07
# 46.0               276   70229.0  3.065462e+07
# 46.0               276   43472.0  1.868458e+07
# 46.0               276   72654.0  1.825354e+07

for _ in range(3, 12):
    t = out \  
        .set_index("A") \
        .groupby(["B", "C"]) \
        .D \
        .nlargest(_) \
        .reset_index()
   print(t.shape[1])
```
#### Problem description
if you run the above with my dataset (`out.shape = (390846, 4)`) you will see that from `_=10` , the method`nlargest` only returns 2 columns and drops the 2 index columns. This doesn't happen between for `_` in the range [1,9] .

#### Expected Output
Seen that I'm just printing the number of columns, the expected output is 4 throughout the loops. 

#### Output of ``pd.show_versions()``

<details>

NSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.2.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8
pandas           : 0.25.2
numpy            : 1.16.2
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 41.4.0
Cython           : 0.29.13
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.1
html5lib         : None
pymysql          : None
psycopg2         : 2.7.7 (dt dec pq3 ext lo64)
jinja2           : 2.10.3
IPython          : 7.8.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : 2.6.1
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.2.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None

</details>

**Comment by mroeschke** [comment]
Sorry for the lack of response but we would need a fully reproducible, copy-paste example (`out` is not well defined here).
Going to close in the meantime, but would be happy to have a second look with the provided info.
