### ISSUE TITLE
i was confused with qcut function

### ISSUE THREAD

**Issue by yuylyp** [pandas-dev/pandas#29308]
I was confused with **qcut** after runing the following codes:
```python
s = pd.Series(range(19))
qc = pd.qcut(s,
            q=[0., .1, .3, .7, .9, 1.],
            labels=[.8, .9, 1., 1.1, 1.2])
qc.to_numpy()
```
#### Problem description
after running above codes, I get the result.( **please note, there is two 1.2, seven 1.**)
```python
array([0.8, 0.8, 0.9, 0.9, 0.9, 0.9, 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1.1, 1.1, 1.1, 1.1, 1.2, 1.2])
```

As my supposed, the results should be:( **one 1.2, eight 1.**)
```python
array([0.8, 0.8, 0.9, 0.9, 0.9, 0.9, 1., 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1.1, 1.1, 1.1, 1.1, 1.2])
```
so, could you please help me to get the expected result?
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.2
numpy            : 1.17.3
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 41.6.0
Cython           : None
pytest           : 5.2.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.2.2
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.9.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 3.0.0
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.2

</details>

**Comment by hwalinga** [comment]
17 / 18 = 0.94, so it falls in the 0.9 --- 1.0 range. That is why in the 0.9 --- 1.0 range (labeled 1.2) fall 17 and 18. That's the reason why you got two 1.2. You can change the q parameter to go from .95 to 1. instead if you want that.

**Comment by yuylyp** [comment]
> 
> 
> 17 / 18 = 0.94, so it falls in the 0.9 --- 1.0 range. That is why in the 0.9 --- 1.0 range (labeled 1.2) fall 17 and 18. That's the reason why you got two 1.2. You can change the q parameter to go from .95 to 1. instead if you want that.

ok, I got it and will try your suggestion.
however, based on my understanding, it should use the size to calculate rather than (size-1).
maybe its a bug?
