### ISSUE TITLE
PERF: regression in MultiIndex get_loc indexing performance

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#29311]
From our benchmarks (`GetLoc` class in https://github.com/pandas-dev/pandas/blob/master/asv_bench/benchmarks/multiindex_object.py):

```
In [65]: mi_med = pd.MultiIndex.from_product( 
    ...:     [np.arange(1000), np.arange(10), list("A")], names=["one", "two", "three"] 
    ...: ) 

In [66]: %timeit mi_med.get_loc((999, 9, "A"))   
9.58 µs ± 106 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [67]: pd.__version__  
Out[67]: '0.25.0'
```

vs

```
In [18]: mi_med = pd.MultiIndex.from_product( 
    ...:     [np.arange(1000), np.arange(10), list("A")], names=["one", "two", "three"] 
    ...: )

In [19]: %timeit mi_med.get_loc((999, 9, "A"))  
34.7 µs ± 454 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [20]: pd.__version__
Out[20]: '0.26.0.dev0+691.g157495696'
```

Not directly sure what recently changed related to MultiIndexes. 
And the benchmark suite is giving a rather broad range: https://github.com/pandas-dev/pandas/compare/2b284543...7c8c8c81 (because the benchmarks were not running for a while I suppose)

**Comment by jorisvandenbossche** [comment]
From a quick profile, seems to be related to shallow copying the levels.

With 0.25, it's mainly the actual engine:

![image](https://user-images.githubusercontent.com/1020496/67949669-66f7a180-fbe8-11e9-838e-f67d3aa885cc.png)

On master there is a big chunk of "levels" related time:

![image](https://user-images.githubusercontent.com/1020496/67949732-88588d80-fbe8-11e9-85a5-d033fc3819a2.png)

So potentially related to the `MI.levels` changes (https://github.com/pandas-dev/pandas/pull/27242, https://github.com/pandas-dev/pandas/pull/29061)

**Comment by jorisvandenbossche** [comment]
cc @topper-123

**Comment by topper-123** [comment]
When copying the names in ``_shallow_copy(names=names)``, there's a lot of unnecessary validation going on for the names (when the names exist already, the name must have been validated already). It's a good guess that's where the problem lies.  I'm planning on optimize that after #27138 (which was more demanding than anticipated, but is close to ready for review now)
