### ISSUE TITLE
WEB: about/index has the extension wrong

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#29325]
xref: https://github.com/pandas-dev/pandas/issues/28580#issuecomment-548876428

Looks like the file `web/pandas/about/index.html` has the wrong extension `.html`, since it's a markdown file and should be `.md`. This is causing that the file is not rendered as html but left untouched in the website: https://dev.pandas.io/about/index.html

**Comment by est271** [comment]
mind if I take a shot at this issue?

**Comment by datapythonista** [comment]
Please go ahead @est271, thanks for helping with this.
