### ISSUE TITLE
MemoryError when using `.drop_duplicates()`

### ISSUE THREAD

**Issue by Mikerah** [pandas-dev/pandas#29381]
#### Code Sample, a copy-pastable example if possible
Calling `.drop_duplicates()` on a large dataframe say of over 1 million rows with sufficient duplicate values should suffice
#### Problem description
I have a very large data frame object ( a little less than 10 million rows). It has 5 columns, most of which at this time are empty. However, for the non-empty columns, there are duplicate values. I have used both `drop_duplicates` and `duplicated` to attempt removing these duplicates. For every variation of these methods, I always get a `MemoryError`. I am running pandas in a jupyter notebook using Python3 on an AWS instance. The AWS instance has 16 GB of RAM.

How can I solve this issue?

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.14.146-120.181.amzn2.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.17.2
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 9.0.3
setuptools       : 38.4.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : 0.11.0
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by mroeschke** [comment]
Can you post a copy pastable example of what failed in your case?

**Comment by Mikerah** [comment]
@mroeschke Is it okay if I post the code directly? I have code in there in which it won't run as it assumes that you have a Google BigQuery table and the associated credentials.

**Comment by mroeschke** [comment]
We prefer copy pastable examples: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

There may be way to emulate the data that you are pulling from BigQuery.

**Comment by Mikerah** [comment]
It's actually quite hard to generate a copy-pastable example with randomly generated data. I get the same error when trying to create data frames of several million values. I'm not sure if having a copy-pastable example of this process would help but here goes:
```python
import pandas as pd
N = 10000000
s_arr = pd.util.testing.rands_array(20, N) # Line at which I get a MemoryError attempting to create a copy-pastable example.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.7/site-packages/pandas/util/testing.py", line 419, in rands_array
    np.random.choice(RANDS_CHARS, size=nchars * np.prod(size))
  File "mtrand.pyx", line 867, in numpy.random.mtrand.RandomState.choice
MemoryError: Unable to allocate array with shape (200000000,) and data type <U1

```

**Comment by Mikerah** [comment]
Update: I actually just reran the code as I did previously and it seems to work now. I'm not sure what is causing this but I will close this issue as I am no longer experiencing this error.
