### ISSUE TITLE
Formatting issues with column width truncation for numerical columns

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#29409]
placeholder.

will update with reproducible example in a couple of days

![image](https://user-images.githubusercontent.com/13159005/68189048-7b4dec80-ffa2-11e9-997c-047c8dfef4ce.png)

**Comment by mroeschke** [comment]
Does this still have a reproducible example that can be tested?

**Comment by mroeschke** [comment]
Let us know if you can still provide the reproducible example, and we can reopen.
