### ISSUE TITLE
pd.to_datetime should_cache errors with deque

### ISSUE THREAD

**Issue by dxe4** [pandas-dev/pandas#29403]
```python
from collections import deque
pd.to_datetime(deque([Timestamp('2010-06-02 09:30:00')] * 51))
```

core.tools.datetimes.should_cache gives `sequence index must be integer, not 'slice` at  `unique(arg[:check_count])`

if deque is not expected it would make more sense to give a better message, otherwise support?

looks like a "good first issue" ?

version 0.25+ (i think it works on 0.24 but i only tested 0.25)

**Comment by mroeschke** [comment]
I supposed this should work as a `deque` is list-like.

**Comment by nathalier** [comment]
Hi,
deque slice can be taken through itertools.islice() .

Which would be better - to implement slicing for deque as well or return False from core.tools.datetimes.should_cache whenever a sequence is not slicable with [:] ?

**Comment by mroeschke** [comment]
I think slicing the deque is preferable to not caching when the user passes a deque. Caching should be available for all inputs ideally.
