### ISSUE TITLE
TST: make subdirs in pandas/tests/io/data

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#29439]
we should group the test files in pandas/tests/io/data into sub directories, e.g. for stata, excel, html, csv etc.

**Comment by alimcmaster1** [comment]
+1 - would you prefer 1 large PR or separate PRs per group?

**Comment by jreback** [comment]
a single PR would be ok here

**Comment by alimcmaster1** [comment]
Sure - happy to do this.

**Comment by jorisvandenbossche** [comment]
Closed by #29513
