### ISSUE TITLE
TST: group unstack / stack tests into new hierarchy

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#29440]
we have a mix of stack / unstack based tests in various places: pandas/tests/frame/test_reshape.py and pandas/tests/test_multilevel.py

would be nice to consolidate these into pandas/tests/reshape

**Comment by tolaa001** [comment]
@jreback are you happy for me to work on this?

**Comment by jbrockmendel** [comment]
these are now mostly in test_stack_unstack.  closing.
