### ISSUE TITLE
DataFrame.groupby doesn't preserve _metadata

### ISSUE THREAD

**Issue by pandichef** [pandas-dev/pandas#29442]
I'm following the 0.25.3 [documentation](https://pandas.pydata.org/pandas-docs/stable/development/extending.html#subclassing-pandas-data-structures) on using _metadata.

```python
sdf = SubclassedDataFrame2(my_data_as_dictionary)
sdf.added_property = 'hello pandas'
df = sdf.groupby('mycategorical')[['myfloat1', 'myfloat2']].sum()
print(df.added_property)
```
The above output produces the result:
AttributeError: 'DataFrame' object has no attribute 'added_property'

**added_property** is _not_ being "passed to manipulation results" as described in the documentation.

**Comment by TomAugspurger** [comment]
FYI, this is likely fixed as part of https://github.com/pandas-dev/pandas/pull/28394, where I'm calling `__finalize__` in more places.

**Comment by pandichef** [comment]
Ok.  I'll check it out.  Are you saying that
SubclassedDataFrame.groupby.sum would now return a  SubclassedDataFrame
instead of a regular DataFrame?  That's the only way I could the metadata
being preserved.


ᐧ

**Comment by pandichef** [comment]
Fyi, this is still an issue on pandas 1.0.3.  @TomAugspurger I think there is a relatively quick fix that I'm using in a personal project... in DataFrameGroupBy, you have access to self.obj.  So you can write a class decorator to implement the following logic at the end of every method in DataFrameGroupBy:

if isinstance(method_result, DataFrame) and issubclass(self.obj.__class__, DataFrame):
    return self.obj.__class__(result)  # 
elif isinstance(method_result, Series) and issubclass(self.obj.__class__, Series):
    return self.obj.__class__(result)
etc.

**Comment by TomAugspurger** [comment]
The PR I linked to earlier has stalled a bit. It'd be best to address
calling groupby in a dedicated pull request if you're interested.

**Comment by pandichef** [comment]
Sure.  I’d be happy to.  But I’d like to make sure that my solution is
acceptable at a high level before I start coding.  Some might consider the
decorator approach to be somewhat of a hack.  Alternatively, I could
manually change every “return DataFrame” into “return self.obj.__class__”.
  Please let me know what you think.

**Comment by TomAugspurger** [comment]
I'm not sure offhand.

**Comment by Japanuspus** [comment]
It appears that the commit responsible for the groupby regression is [#34214](https://github.com/pandas-dev/pandas/pull/34214), where object creation is done with `type(self)(...)` which does not call `__finalize__` (or checks `_constructor`), which should be done according to the [docs].

I will try to implement this internally and submit a pull request.

[docs]: https://pandas.pydata.org/pandas-docs/stable/development/extending.html#override-constructor-properties

**Comment by simonjayhawkins** [comment]
heads up: moved off 1.1.1 milestone

**Comment by simonjayhawkins** [comment]
moved off 1.1.2 milestone (imminent release) as associated PR #35688 not yet ready.
