### ISSUE TITLE
xticks unnecessarily rotated

### ISSUE THREAD

**Issue by thehalftruth** [pandas-dev/pandas#29460]
#### Code Sample
```python
import pandas as pd
import matplotlib.pyplot as plt
from io import StringIO

csv_string = """x,y1,y2
0, 1, 1
1, 1, 2
2, 1, 3
3, 4, 2
4, 2, 4
5, 3, 3
"""

data = pd.read_csv(StringIO(csv_string))
dataframe = pd.DataFrame(data)

dataframe.plot(x="x",
               y=["y1", "y2"],
               kind="line",
               subplots=True,
               sharex=True,
               marker=",",
               linewidth=0.5,
               title="Title"
               )

plt.show()
```
#### Problem description
The xticks are unnecessarily rotated:
![grafik](https://user-images.githubusercontent.com/9128021/68378413-5c8b5980-014c-11ea-9d5e-6226ff4cc10f.png)
Also the title overlaps the subplot, but I will create a new issue for that.

#### Expected Output
The xticks shouldn't be rotated.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.2.final.0
python-bits      : 32
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.3
numpy            : 1.17.3
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 41.6.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
import sys; print('Python %s on %s' % (sys.version, sys.platform))
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32
</details>

**Comment by MarcoGorelli** [comment]
Thanks @thehalftruth for the report

Seems this only happens when `subplots=True`

**Comment by MarcoGorelli** [comment]
take
