### ISSUE TITLE
CI: Move documentation build to GitHub actions

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#29472]
GitHub actions is out of beta, and should have much better integration with GitHub than pipelines.

I'm thinking on giving it a try for the documentation build, and see if we can get an improvement on current CI problems:
- Too many steps from the PR page to the logs (#26895)
- Notify with a comment on the PR when there are problems (#26930)
- Publish the documentation for a PR so it can be seen

Any objection? Depending on how things go with the doc build, I think it may make sense to give other builds a try to.

**Comment by alimcmaster1** [comment]
+1 to publishing the docs for a PR!
