### ISSUE TITLE
Improve fname documentation for to_parquet

### ISSUE THREAD

**Issue by larroy** [pandas-dev/pandas#29476]
#### Code Sample, a copy-pastable example if possible

Should to_parquet without file behave the same way than to_json in which if no file is specified we return the buffer?

**Comment by TomAugspurger** [comment]
Probably not, since parquet isn't a plaintext format.

**Comment by WillAyd** [comment]
Think I am agreed with Tom. Having all to_* functions return the same thing is also a non-goal, as it just doesn't make sense in all cases (to_sql comes to mind)

**Comment by larroy** [comment]
Thanks for your answers.

**Comment by WillAyd** [comment]
The documentation can be improved but you can pass an io.BytesIO object if you don't want to write to disk. I think path-like objects work as well - any interest in updating the docs?

**Comment by larroy** [comment]
Sure, I would be happy to update them. I will link the PRs here. Thank you.

**Comment by alimcmaster1** [comment]
@larroy you still interested in working on this?

**Comment by larroy** [comment]
Sorry was caught up with other things, let me have a look at this this week.
