### ISSUE TITLE
Bump NumPy to 1.15

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#29486]
Follow up to #29212 we should bump Numpy to 1.15

**Optional**: we hit CI failures in the PR above on Python 3.6.0 related to Numpy. We bumped Python to 3.6.1 but if we bump numpy instead 3.6.0 might work, if we even care

**Comment by gfyoung** [comment]
Just from an operational perspective, I agree with the comments in #29212 that we should follow the NEP and bump to 1.15.  I don't know what functional benefits `pandas` gains from this, but as long as there are not any negative side effects, I think I'm okay with this.

**Comment by WillAyd** [comment]
Closing in favor of #29512
