### ISSUE TITLE
DataFrame.plot docs broken

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#29489]
Not showing anything useful  currently. I think the regression came between 0.24 and 0.25

0.25.0 docs:

https://pandas.pydata.org/pandas-docs/version/0.25.0/reference/api/pandas.DataFrame.plot.html

0.24.2 docs:
https://pandas.pydata.org/pandas-docs/version/0.24.2/reference/api/pandas.DataFrame.plot.html

**Comment by datapythonista** [comment]
This is a duplicate of #27748. I'm going to close that one, as contributors usually don't check old issues.

**Comment by JacksonDagger** [comment]
I'm gonna take a crack at this if no one else is working on it!

**Comment by JacksonDagger** [comment]
I'm still looking into this. I've discovered that this issue also affects [Series.plot.](https://pandas.pydata.org/pandas-docs/version/0.25.0/reference/api/pandas.Series.plot.html) Both plot classes use the PandasAutosummary class in conf.py and [PlotAccessor](https://github.com/pandas-dev/pandas/blob/v0.25.0/pandas/plotting/_core.py#L504-L1533)

**Comment by datapythonista** [comment]
I don't think the docstring was removed, so it should be only a question of setting it to the right object (which was probably unset during a big refactoring we did).

**Comment by chrisateen** [comment]
I noticed that in pandas.core.series.py and pandas.core.frame.py that both the DataFrame.plot method and the Series.plot method is create dynamically. See line 8146 for the Dataframe.plot and line 4393 for the Series.plot. For example on line 8146 in the pandas.core.frame.py file we have the code

`plot = CachedAccessor("plot", pandas.plotting.PlotAccessor)`

The documentation that is needed for both the series and the dataframe is in the pandas.plotting._core.py file where the class PlotAccessor is defined (line 543)

How can one set the documentation considering that the plot and series method is create dynamically?

**Comment by lithomas1** [comment]
take
