### ISSUE TITLE
Cannot convert string to Int64

### ISSUE THREAD

**Issue by maresb** [pandas-dev/pandas#29488]
```python
pd.Series(['1']).astype(float).astype('Int64')  # succeeds
pd.Series(['1']).astype('Int64')  # fails with:
# TypeError: object cannot be converted to an IntegerDtype
```
#### Problem description

Unlike with the other numeric data types, It doesn't seem to be possible to parse a string as `Int64`.  A decent workaround seems to be converting first to float, but that's rather awkward.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-1052-aws
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.17.2
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.2.1
setuptools       : 41.0.1
Cython           : 0.29.13
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : 3.0.0
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.3.8
tables           : None
xarray           : 0.14.0
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
</details>

**Comment by mroeschke** [comment]
See https://github.com/pandas-dev/pandas/issues/28599.

We recommend using `to_numeric` on object data first before astyping to `Int64`.
