### ISSUE TITLE
to_clipboard

### ISSUE THREAD

**Issue by Jackblackpearl** [pandas-dev/pandas#29501]
#### Code Sample, a copy-pastable example if possible

 df[df['Delivery'].notnull()]['Delivery'].astype(int).to_clipboard(excel=True, sep=',',index=False)

```
#### Problem description

Works fine when I run the program in spyder or jupyter but after taking the build using Pyinstaller the the data from clipboard is not pasting to respective screen. 

Is there anything needs to added or removed before taking the build.
Thanks in advance.

**Comment by jreback** [comment]
you should address with pyinstaller

**Comment by Jackblackpearl** [comment]
Thanks for the update. Will raise the same question over there. 
But I do like to know that to_clipboard is worked well after taking the build(.exe)
