### ISSUE TITLE
Flakey Test in CI - Unclosed File Handle

### ISSUE THREAD

**Issue by alimcmaster1** [pandas-dev/pandas#29514]
Seen this in a few pipelines today:

https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=20521
https://github.com/pandas-dev/pandas/runs/295247988

```
______________ test_chunks_have_consistent_numerical_type[python] ______________
[gw0] linux -- Python 3.6.1 /home/vsts/miniconda3/envs/pandas-dev/bin/python

all_parsers = <pandas.tests.io.parser.conftest.PythonParser object at 0x7f635d65e470>

    def test_chunks_have_consistent_numerical_type(all_parsers):
        parser = all_parsers
        integers = [str(i) for i in range(499999)]
        data = "a\n" + "\n".join(integers + ["1.0", "2.0"] + integers)
    
        # Coercions should work without warnings.
        with tm.assert_produces_warning(None):
>           result = parser.read_csv(StringIO(data))

pandas/tests/io/parser/test_common.py:1204: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <contextlib._GeneratorContextManager object at 0x7f631f91c8d0>
type = None, value = None, traceback = None

    def __exit__(self, type, value, traceback):
        if type is None:
            try:
>               next(self.gen)
E               AssertionError: Caused unexpected warning(s): [('ResourceWarning', ResourceWarning("unclosed file <_io.BufferedReader name='test1.xlsx'>",), 
```

**Comment by WillAyd** [comment]
Pretty interesting the warnings are only for .xlsx and .xlsm files, so maybe something with the openpyxl reader; would think .xls would show as well if it were xlrd

**Comment by 0xF4D3C0D3** [comment]
I'm suffering from the same issue too. fwiw, below is my test order in which PythonParser is used:

<details>

pandas/tests/io/parser/test_common.py::test_url[python]
pandas/tests/io/parser/test_common.py::test_local_file[python]
pandas/tests/io/parser/test_common.py::test_path_path_lib[python]
pandas/tests/io/parser/test_common.py::test_path_local_path[python]
pandas/tests/io/parser/test_common.py::test_nonexistent_path[python]
pandas/tests/io/parser/test_common.py::test_missing_trailing_delimiters[python]
pandas/tests/io/parser/test_common.py::test_skip_initial_space[python]
pandas/tests/io/parser/test_common.py::test_utf16_bom_skiprows[python-utf-16-,]
pandas/tests/io/parser/test_common.py::test_utf16_bom_skiprows[python-utf-16-	]
pandas/tests/io/parser/test_common.py::test_utf16_bom_skiprows[python-utf-16le-,]
pandas/tests/io/parser/test_common.py::test_utf16_bom_skiprows[python-utf-16le-	]
pandas/tests/io/parser/test_common.py::test_utf16_bom_skiprows[python-utf-16be-,]
pandas/tests/io/parser/test_common.py::test_utf16_bom_skiprows[python-utf-16be-	]
pandas/tests/io/parser/test_common.py::test_utf16_example[python]
pandas/tests/io/parser/test_common.py::test_unicode_encoding[python]
pandas/tests/io/parser/test_common.py::test_trailing_delimiters[python]
pandas/tests/io/parser/test_common.py::test_escapechar[python]
pandas/tests/io/parser/test_common.py::test_int64_min_issues[python]
pandas/tests/io/parser/test_common.py::test_parse_integers_above_fp_precision[python]
**pandas/tests/io/parser/test_common.py::test_chunks_have_consistent_numerical_type[python]**
pandas/tests/io/parser/test_common.py::test_warn_if_chunks_have_mismatched_type[python]
pandas/tests/io/parser/test_common.py::test_integer_overflow_bug[python- ]
pandas/tests/io/parser/test_common.py::test_integer_overflow_bug[python-\s+]
pandas/tests/io/parser/test_common.py::test_catch_too_many_names[python]
pandas/tests/io/parser/test_common.py::test_ignore_leading_whitespace[python]
pandas/tests/io/parser/test_common.py::test_chunk_begins_with_newline_whitespace[python]
pandas/tests/io/parser/test_common.py::test_empty_with_index[python]
pandas/tests/io/parser/test_common.py::test_empty_with_multi_index[python]
pandas/tests/io/parser/test_common.py::test_empty_with_reversed_multi_index[python]
pandas/tests/io/parser/test_common.py::test_float_parser[python]
pandas/tests/io/parser/test_common.py::test_scientific_no_exponent[python]
pandas/tests/io/parser/test_common.py::test_int64_overflow[python-None]
pandas/tests/io/parser/test_common.py::test_int64_overflow[python-int64]
pandas/tests/io/parser/test_common.py::test_int64_overflow[python-uint64]
pandas/tests/io/parser/test_common.py::test_int64_uint64_range[python-18446744073709551615]
pandas/tests/io/parser/test_common.py::test_int64_uint64_range[python-9223372036854775807]
pandas/tests/io/parser/test_common.py::test_int64_uint64_range[python--9223372036854775808]
pandas/tests/io/parser/test_common.py::test_outside_int64_uint64_range[python-18446744073709551616]
pandas/tests/io/parser/test_common.py::test_outside_int64_uint64_range[python--9223372036854775809]
pandas/tests/io/parser/test_common.py::test_numeric_range_too_wide[python-exp_data0]
pandas/tests/io/parser/test_common.py::test_numeric_range_too_wide[python-exp_data1]
pandas/tests/io/parser/test_common.py::test_empty_with_nrows_chunksize[python-True]
pandas/tests/io/parser/test_common.py::test_empty_with_nrows_chunksize[python-False]
pandas/tests/io/parser/test_common.py::test_eof_states[python-whitespace-line]
pandas/tests/io/parser/test_common.py::test_eof_states[python-eat-line-comment0]
pandas/tests/io/parser/test_common.py::test_eof_states[python-eat-crnl-nop]
pandas/tests/io/parser/test_common.py::test_eof_states[python-eat-comment]
pandas/tests/io/parser/test_common.py::test_eof_states[python-skip-line]
pandas/tests/io/parser/test_common.py::test_eof_states[python-eat-line-comment1]
pandas/tests/io/parser/test_common.py::test_eof_states[python-in-field]
pandas/tests/io/parser/test_common.py::test_eof_states[python-eat-crnl]
pandas/tests/io/parser/test_common.py::test_eof_states[python-escaped-char]
pandas/tests/io/parser/test_common.py::test_eof_states[python-escape-in-quoted-field]
pandas/tests/io/parser/test_common.py::test_eof_states[python-in-quoted-field]
pandas/tests/io/parser/test_common.py::test_uneven_lines_with_usecols[python-None]
pandas/tests/io/parser/test_common.py::test_uneven_lines_with_usecols[python-usecols1]
pandas/tests/io/parser/test_common.py::test_uneven_lines_with_usecols[python-usecols2]
pandas/tests/io/parser/test_common.py::test_read_empty_with_usecols[python--kwargs0-None]
pandas/tests/io/parser/test_common.py::test_read_empty_with_usecols[python--kwargs1-None]
pandas/tests/io/parser/test_common.py::test_read_empty_with_usecols[python-,,-kwargs2-expected2]
pandas/tests/io/parser/test_common.py::test_read_empty_with_usecols[python--kwargs3-expected3]
pandas/tests/io/parser/test_common.py::test_trailing_spaces[python-kwargs0-expected0]
pandas/tests/io/parser/test_common.py::test_trailing_spaces[python-kwargs1-expected1]
pandas/tests/io/parser/test_common.py::test_raise_on_sep_with_delim_whitespace[python]
pandas/tests/io/parser/test_common.py::test_single_char_leading_whitespace[python-True]
pandas/tests/io/parser/test_common.py::test_single_char_leading_whitespace[python-False]
pandas/tests/io/parser/test_common.py::test_empty_lines[python-,-True-exp_data0]
pandas/tests/io/parser/test_common.py::test_empty_lines[python-\s+-True-exp_data1]
pandas/tests/io/parser/test_common.py::test_empty_lines[python-,-False-exp_data2]
pandas/tests/io/parser/test_common.py::test_whitespace_lines[python]
pandas/tests/io/parser/test_common.py::test_verbose_read[python]
pandas/tests/io/parser/test_common.py::test_verbose_read2[python]
pandas/tests/io/parser/test_common.py::test_iteration_open_handle[python]
pandas/tests/io/parser/test_common.py::test_euro_decimal_format[python]
pandas/tests/io/parser/test_common.py::test_inf_parsing[python-True]
pandas/tests/io/parser/test_common.py::test_inf_parsing[python-False]
pandas/tests/io/parser/test_common.py::test_infinity_parsing[python-True]
pandas/tests/io/parser/test_common.py::test_infinity_parsing[python-False]
pandas/tests/io/parser/test_common.py::test_raise_on_no_columns[python-0]
pandas/tests/io/parser/test_common.py::test_raise_on_no_columns[python-1]
pandas/tests/io/parser/test_common.py::test_raise_on_no_columns[python-2]
pandas/tests/io/parser/test_common.py::test_raise_on_no_columns[python-3]
pandas/tests/io/parser/test_common.py::test_raise_on_no_columns[python-4]
pandas/tests/io/parser/test_common.py::test_raise_on_no_columns[python-5]
pandas/tests/io/parser/test_common.py::test_memory_map[python]
pandas/tests/io/parser/test_common.py::test_null_byte_char[python]
pandas/tests/io/parser/test_common.py::test_temporary_file[python]
pandas/tests/io/parser/test_common.py::test_read_csv_utf_aliases[python-utf-{0}-8]
pandas/tests/io/parser/test_common.py::test_read_csv_utf_aliases[python-utf-{0}-16]
pandas/tests/io/parser/test_common.py::test_read_csv_utf_aliases[python-utf_{0}-8]
pandas/tests/io/parser/test_common.py::test_read_csv_utf_aliases[python-utf_{0}-16]
pandas/tests/io/parser/test_common.py::test_read_csv_utf_aliases[python-UTF-{0}-8]
pandas/tests/io/parser/test_common.py::test_read_csv_utf_aliases[python-UTF-{0}-16]
pandas/tests/io/parser/test_common.py::test_read_csv_utf_aliases[python-UTF_{0}-8]
pandas/tests/io/parser/test_common.py::test_read_csv_utf_aliases[python-UTF_{0}-16]
pandas/tests/io/parser/test_common.py::test_internal_eof_byte[python]
pandas/tests/io/parser/test_common.py::test_internal_eof_byte_to_file[python]
pandas/tests/io/parser/test_common.py::test_sub_character[python]
pandas/tests/io/parser/test_common.py::test_file_handle_string_io[python]
pandas/tests/io/parser/test_common.py::test_file_handles_with_open[python]
pandas/tests/io/parser/test_common.py::test_binary_mode_file_buffers[python-test1.csv-utf-8]
pandas/tests/io/parser/test_common.py::test_binary_mode_file_buffers[python-unicode_series.csv-latin-1]
pandas/tests/io/parser/test_common.py::test_binary_mode_file_buffers[python-sauron.SHIFT_JIS.csv-shiftjis]
pandas/tests/io/parser/test_common.py::test_invalid_file_buffer_class[python]
pandas/tests/io/parser/test_common.py::test_invalid_file_buffer_mock[python]
pandas/tests/io/parser/test_common.py::test_valid_file_buffer_seems_invalid[python]
pandas/tests/io/parser/test_common.py::test_error_bad_lines[python-warn_kwargs0-kwargs0]
pandas/tests/io/parser/test_common.py::test_error_bad_lines[python-warn_kwargs0-kwargs1]
pandas/tests/io/parser/test_common.py::test_error_bad_lines[python-warn_kwargs1-kwargs0]
pandas/tests/io/parser/test_common.py::test_error_bad_lines[python-warn_kwargs1-kwargs1]
pandas/tests/io/parser/test_common.py::test_error_bad_lines[python-warn_kwargs2-kwargs0]
pandas/tests/io/parser/test_common.py::test_error_bad_lines[python-warn_kwargs2-kwargs1]
pandas/tests/io/parser/test_common.py::test_warn_bad_lines[python]
pandas/tests/io/parser/test_common.py::test_suppress_error_output[python]
pandas/tests/io/parser/test_common.py::test_filename_with_special_chars[python-sé-es-vé.csv]
pandas/tests/io/parser/test_common.py::test_filename_with_special_chars[python-ru-sй.csv]
pandas/tests/io/parser/test_common.py::test_filename_with_special_chars[python-中文文件名.csv]
pandas/tests/io/parser/test_common.py::test_read_csv_memory_growth_chunksize[python]
pandas/tests/io/parser/test_common.py::test_read_table_equivalency_to_read_csv[python]
pandas/tests/io/parser/test_common.py::test_first_row_bom[python]
</details>

**Comment by 0xF4D3C0D3** [comment]
I'm suffering from this too #28681 . what can I do to help? I want to help... but I don't know where to start. It would be nice if I can help something.

**Comment by alimcmaster1** [comment]
https://travis-ci.org/pandas-dev/pandas/jobs/631970657?utm_medium=notification&utm_source=github_status Looks like this test is still an issue

**Comment by alimcmaster1** [comment]
Also see `test_legacy_sparse_warning` causing issues [here](https://travis-ci.org/pandas-dev/pandas/jobs/632023359?utm_medium=notification&utm_source=github_status)

**Comment by jorisvandenbossche** [comment]
Is this a blocker for 1.0 ?

**Comment by TomAugspurger** [comment]
I don't think so.

**Comment by mroeschke** [comment]
Don't think we've seen this in a while. Closable @alimcmaster1?

**Comment by alimcmaster1** [comment]
Yeah can't see this test in any recent build failures - do see a different done though...
```
_________________ TestNestedToRecord.test_deprecated_import ___________________
[gw0] linux -- Python 3.6.10 /home/travis/miniconda3/envs/pandas-dev/bin/python
self = <pandas.tests.io.json.test_normalize.TestNestedToRecord object at 0x7f329239d668>
    def test_deprecated_import(self):
        with tm.assert_produces_warning(FutureWarning):
            from pandas.io.json import json_normalize
    
            recs = [{"a": 1, "b": 2, "c": 3}, {"a": 4, "b": 5, "c": 6}]
>           json_normalize(recs)
pandas/tests/io/json/test_normalize.py:742: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <contextlib._GeneratorContextManager object at 0x7f329239dac8>
type = None, value = None, traceback = None
    def __exit__(self, type, value, traceback):
        if type is None:
            try:
>               next(self.gen)
E               AssertionError: Caused unexpected warning(s): [('ResourceWarning', ResourceWarning("unclosed <socket.socket fd=33, family=AddressFamily.AF_INET, 
```

https://travis-ci.org/github/pandas-dev/pandas/jobs/677027259

Will try take a look

**Comment by TomAugspurger** [comment]
Here's the smallest reproducer I could get for the unhanlded ResourceWarning

```python
pytest pandas/tests/io/json/test_pandas.py::TestPandasContainer::test_read_s3_jsonl pandas/tests/io/json/test_pandas.py::TestPandasContainer::test_deprecate_numpy_argument_read_json
```

**Comment by smithto1** [comment]
Just reporting that I've had this error twice today on Travis. 

https://travis-ci.org/github/pandas-dev/pandas/jobs/708801493
