### ISSUE TITLE
DEPS: Minimum numpy version for pandas 1.0

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#29512]
There has been some discussion about dropping numpy 1.13, and require 1.15 for pandas 1.0. See https://github.com/pandas-dev/pandas/pull/29212#issuecomment-551856248

I think that'd be nice to reduce our matrix of builds for the CI, other than that I'm not sure what advantages this will have in our code base.

Any opinions @pandas-dev/pandas-core ?

**Comment by alimcmaster1** [comment]
Related: https://github.com/pandas-dev/pandas/issues/29486

**Comment by gfyoung** [comment]
Just from an operational perspective, I agree with the comments in #29212 that we should follow the NEP and bump to 1.15. I don't know what functional benefits pandas gains from this, but as long as there are not any negative side effects, I think I'm okay with this.

**Comment by jbrockmendel** [comment]
closeable?

**Comment by TomAugspurger** [comment]
Yeah, we're just following NEP-29 now.
