### ISSUE TITLE
Support of command line tools in IO

### ISSUE THREAD

**Issue by miaojingang** [pandas-dev/pandas#29575]
#### Code Sample, a copy-pastable example if possible

```python
R's data.table::fread() supports command line tools, which provides a lot of flexibility. 

Example below taken from [stackoverflow](https://stackoverflow.com/questions/35763574/fastest-way-to-read-in-100-000-dat-gz-files/35786076#35786076):

fread('cat *dat.gz | gunzip | grep -v "^Day"')

This becomes important for example if the whole data does not fit into RAM and one wants to filter it down while reading it in.


Is it possible to add this to pandas?

**Comment by datapythonista** [comment]
I think that makes more sense in R than in Python, since Python let you implement this easily (I guess R doesn't).

For example, You can open a file with `open`, use the `csv` module to get a generator over it, create a `filter`, and then use the generator to read the data. I think the needed resources should be similar to bash, and this would be more readable than using bash commands as a parameter.

What do you think @miaojingang ?

**Comment by miaojingang** [comment]
Hi Marc, agreed that iterator solves the big file problem. In fact, that's
what I have been using.

The command line toolbox is just so rich and powerful, and I doubt python
has convenient & efficient ways of doing all.

Just one example: I once got a huge csv file, where one string variable had
carriage return characters. This messed up both pandas.read_csv and
data.table::fread. The sed command removed these characters blazing fast at
a rate of more than 2GB per second.

I totally understand if this may be low on the priority list, but I do
believe it would open up a lot of opportunities, especially for those who
are already fluent in command line.

**Comment by datapythonista** [comment]
Thanks for the feedback. Do you want to give a try to implement this as a third-package? I don't think it needs to live in pandas, at least initially. Something like next should be quite ok I think:
```python
import yourpackage

df = pandas.read_csv(yourpackage.cmd('cat *dat.gz | gunzip | grep -v "^Day"'))
```

`read_csv` accepts a file descriptor, so you can just return one that runs the command in a lazy way and returns it.

We've got a Ecosystem page where we can list your projects, so others can use it: https://dev.pandas.io/community/ecosystem.html

And in the future, we may make the IO magic a set of plugins that can be extended. We currently have:
- Download urls
- Uncompress files

Adding to the list running bash commands seems like an option. I'd personally let users decide which magic they want, and be able to have them implemented in packages separate from pandas. So, if you implement this, we may be able to better integrate with your package in future versions of pandas.

**Comment by jreback** [comment]
https://medium.com/@zwinny/writing-shell-scripts-in-python-with-a-funny-lib-plumbum-777dddc82bfa

there are lots of ways to do this

**Comment by miaojingang** [comment]
Thanks Jeff.

It seems we can leave it for the user to do outside of pandas. subprocess seems like a good option.

Closing this for now. Thank you both again!
