### ISSUE TITLE
pandas.DataFrame.to_gbq missing method of writting

### ISSUE THREAD

**Issue by OmerJog** [pandas-dev/pandas#29598]
BigQuery support 3 different types of load methods:
WRITE_EMPTY, WRITE_TRUNCATE, WRITE_APPEND
https://cloud.google.com/bigquery/docs/reference/auditlogs/rest/Shared.Types/WriteDisposition

this parameter needs to be controlled by loading job.

**Comment by TomAugspurger** [comment]
Does pandas-gbq support this?

**Comment by OmerJog** [comment]
@TomAugspurger yes
https://pandas-gbq.readthedocs.io/en/latest/writing.html#writing-to-an-existing-table
"Use the if_exists argument to dictate whether to 'fail', 'replace' or 'append' if the destination table already exists. The default value is 'fail'."

**Comment by TomAugspurger** [comment]
So we just need to add a keyword and pass it through? We'll need to take
some care to
give a nice error message if the user has too old a version.

Are you interested in working on this?

**Comment by OmerJog** [comment]
@TomAugspurger yes. It's just exposing this parameter in the to_gbq function.

I currently don't have the time to do work on this. Maybe i'll be able to in a few months so if someone want to pick it up - be my guest.

**Comment by charlesdong1991** [comment]
emm, but seems pandas already supports `if_exists`? or do you mean this argument is not functioning correctly?

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_gbq.html

@OmerJog
