### ISSUE TITLE
About `pandas.to_datetime`'s origin parameter

### ISSUE THREAD

**Issue by CharMingF** [pandas-dev/pandas#29590]
#### Code Sample, a copy-pastable example if possible

```python
pd.to_datetime([1.5,2.5], unit='D', origin=pd.Timestamp("2015-12-31 12:00:00"))

```

#### Problem description
I set the origin to hour format ,but the result is not correct.:

DatetimeIndex(['2016-01-01 12:00:00', '2016-01-02 12:00:00'], dtype='datetime64[ns]', freq=None)

#### Expected Output

DatetimeIndex(['2016-01-02 00:00:00', '2016-01-03 00:00:00'], dtype='datetime64[ns]', freq=None)
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en
LOCALE           : None.None

pandas           : 0.25.1
numpy            : 1.17.1
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 2.2.0
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.4.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 2.6.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : 3.5.2
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : 1.1.8
</details>

**Comment by susan-shu-c** [comment]
Hi, I am able to reproduce the behavior. However, I think this is the intended behavior, as there is no "rounding up" of the day. If it has not reached the next day, it is the current day. As an example:

Days don't round up - for example, the results for incrementing 1.3 days and 1.7 days are the same.
```
>>> pd.to_datetime([1.3,2.3], unit='D', origin=pd.Timestamp("2015-12-31 12:00:00"))
DatetimeIndex(['2016-01-01 07:12:00', '2016-01-02 07:12:00'], dtype='datetime64[ns]', freq=None)

>>> pd.to_datetime([1.7,2.7], unit='D', origin=pd.Timestamp("2015-12-31 12:00:00"))
DatetimeIndex(['2016-01-01 16:48:00', '2016-01-02 16:48:00'], dtype='datetime64[ns]', freq=None)
```

Only when 2 full days have been incremented does it count as Jan 02.

```
>>> pd.to_datetime([2,3], unit='D', origin=pd.Timestamp("2015-12-31 12:00:00"))
DatetimeIndex(['2016-01-02', '2016-01-03'], dtype='datetime64[ns]', freq=None)
```

**Comment by mroeschke** [comment]
Thanks for the explanation @susan-shu-c! Correct, "half days" are supported as units so this is the intended behavior.
