### ISSUE TITLE
Line plot is not displaying correctly using pandas

### ISSUE THREAD

**Issue by Ashutosh341** [pandas-dev/pandas#29612]
I have installed latest pandas version

Now I am trying to plot a bar plot by using pandas but it is giving me this Figure

![Capture line plot](https://user-images.githubusercontent.com/54778459/68828240-07f75980-06cb-11ea-8c50-5c2ffd53cb9b.PNG)
.png)

I am learning pandas from Udemy and when trainer was plotting bar plot , it was plotting correctly
![Capture112](https://user-images.githubusercontent.com/54778459/68828495-e2b71b00-06cb-11ea-8704-9e6cb45eae26.PNG)

**Comment by hwalinga** [comment]
Can you maybe share the full code (not a screenshot of your code please) and input data?
