### ISSUE TITLE
Boolean string methods on empty Series return object dtype

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#29624]
#### Code Sample, a copy-pastable example if possible

```python
In [7]: pd.Series([], dtype=object).str.isalnum()
Out[7]: Series([], dtype: object)
```
#### Problem description

On empty series, we return an object-dtype result, rather than bool. I might expect
this to be a boolean dtype to match the non-empty case.

#### Expected Output

```python
In [14]: pd.Series([], dtype=object).str.isalnum()
Out[14]: Series([], dtype: bool)
```

**Comment by TomAugspurger** [comment]
Given that other boolean-returning methods do return a bool dtype for empty Series, I'm comfortable calling this a bug:

```python
In [5]: pd.Series([], dtype=object).str.contains("a")
Out[5]: Series([], dtype: bool)
```

**Comment by ellequelle** [comment]
It looks to me like this can be solved by adding `dtype=bool` as an argument to `_noarg_wrapper` for the "ismethods" the StringMethods class:

```
isalnum = _noarg_wrapper(
    lambda x: x.isalnum(),
    name="isalnum",
    docstring=_shared_docs["ismethods"] % _doc_args["isalnum"],
    returns_string=False,
    dtype=bool,
)
```
