### ISSUE TITLE
Using .iloc on a sparse DataFrame results in a copy

### ISSUE THREAD

**Issue by swt2c** [pandas-dev/pandas#29647]
```python
df = pd.DataFrame({'A': [0.1, 0.2, 0.3], 'B': [1.0, 2.0, 3.0]}, dtype='Sparse[float64, nan]')
df1 = df.iloc[0]
df1._is_view
```
#### Problem description

When calling `.iloc` on a sparse DataFrame, it seems to return a copy rather than a view.  Is this expected behavior?

#### Expected Output

Getting a view back would be preferred.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-66-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.3
numpy            : 1.17.4
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 9.0.1
setuptools       : 39.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 0.999999999
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : 0.2.1
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by TomAugspurger** [comment]
I think that's impossible given the current design. Each column is stored independently.

**Comment by jorisvandenbossche** [comment]
BTW, you will see exactly the same behaviour for a non-sparse dataframe if not all columns have the same dtype or do not use a plain numpy dtype.

**Comment by TomAugspurger** [comment]
Thanks for the report, not something we can support right now.
