### ISSUE TITLE
CI: postgresql job failing

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#29643]
e.g. https://travis-ci.org/pandas-dev/pandas/jobs/612501204

```
installing dbs

psql: could not connect to server: No such file or directory

	Is the server running locally and accepting

	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

The command "ci/setup_env.sh" failed and exited with 2 during .

Your build has been stopped.
```

**Comment by jbrockmendel** [comment]
is "hope it goes away on its own" a viable option?

**Comment by datapythonista** [comment]
I had a look, but I don't see where the database is set up. Do we install it somewhere, or does travis provide a database automatically for the builds?

I see this setting: https://docs.travis-ci.com/user/database-setup/#mysql

May be until now this was coming by default, and now we need to specify it?

**Comment by alimcmaster1** [comment]
Error report on the below looks the exact same - might be helpful

https://github.com/travis-ci/travis-ci/issues/5491
