### ISSUE TITLE
CI: Clipboard Test Failures on Travis

### ISSUE THREAD

**Issue by alimcmaster1** [pandas-dev/pandas#29676]
```
[gw1] linux -- Python 3.6.6 /home/travis/miniconda3/envs/pandas-dev/bin/python
data = '👍...'
    @pytest.mark.single
    @pytest.mark.clipboard
    @pytest.mark.skipif(not _DEPS_INSTALLED, reason="clipboard primitives not installed")
    @pytest.mark.parametrize("data", ["\U0001f44d...", "Ωœ∑´...", "abcd..."])
    def test_raw_roundtrip(data):
        # PR #25040 wide unicode wasn't copied correctly on PY3 on windows
        clipboard_set(data)
>       assert data == clipboard_get()
E       AssertionError: assert '👍...' == ''
E         - 👍...
pandas/tests/io/test_clipboard.py:264: AssertionError
```
Examples:

https://travis-ci.org/pandas-dev/pandas/jobs/613141276?utm_medium=notification&utm_source=github_status

https://travis-ci.org/pandas-dev/pandas/builds/613153224?utm_source=github_status&utm_medium=notification

Potentially related change:
https://github.com/pandas-dev/pandas/pull/28531

**Comment by TomAugspurger** [comment]
I'll try to look into this now.

**Comment by jreback** [comment]
@alimcmaster1 can you confirm everything working and if so close

**Comment by TomAugspurger** [comment]
I think not a blocker for 1.0 (RC / final) but would be nice to have.
