### ISSUE TITLE
ENH: Group some columns in subplots with DataFrame.plot

### ISSUE THREAD

**Issue by NicolasHug** [pandas-dev/pandas#29688]
`df.plot(subplots=True)`  will create one subplot per column. Is there a way to group multiple columns on the same subplot (and leave the rest of the column separated)?

I'd be happy to submit a PR if that's something you'd consider? In terms of API  `subplot` could accept a list of tuples where each tuple indicates which columns should be grouped together.

**Comment by TomAugspurger** [comment]
Just to make sure I understand, `df.plot(subplots=[('a', 'b'), ('d', 'e', 'f')])` would have two axes?

I'm not sure, but I'm guessing it'd be somewhat complicated to work that into our current `subplots` logic. At glance, it looks like we assume `subplots=True` -> one axes per column in several places.

**Comment by NicolasHug** [comment]
> `df.plot(subplots=[('a', 'b'), ('d', 'e', 'f')])` would have two axes?

Yes that's the idea. My motivation is that sometimes some columns are comparable, in which case it would make sense to plot them together.
