### ISSUE TITLE
sort_index on a multiindexed DataFrame with sparse columns fills with NaNs

### ISSUE THREAD

**Issue by MisterKeefe** [pandas-dev/pandas#29735]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
from scipy.sparse import csr_matrix

f = pd.DataFrame.sparse.from_spmatrix(csr_matrix((4, 4)), index=pd.MultiIndex.from_product([[1, 2], [1,2]]))

f
f.sort_index(level=0)
```
#### Problem description

When I create a MultiIndexed DataFrame with sparse columns, then call `sort_index()`, in the result `0.0` (the sparse fill value) has been replaced with `NaN` -- but it seems like only for columns which are all the fill value. 

It seems like this might also be an issue with `RangeIndex` as well, since if I make a simpler `DataFrame` and call `sort_index`, without any arguments it's ok but adding `level=0` (or in fact `level=(anything)` as a kwarg will cause the frame to be filled with `NaN` without raising any kind of warning 

I would expect the following behaviour: 

- Values preserved for `MultiIndex` 
- For `RangeIndex`, the level keyword should either be totally ignored (no impact on output) or should not be valid to pass in.

I don't think this is a duplicate, I searched the tracker but the combination of sparse + multiindex seems to be rare

#### Expected Output
```python
>>> f.sort_index(level=0)
       0    1    2    3
1 1  0.0  0.0  0.0  0.0
  2  0.0  0.0  0.0  0.0
2 1  0.0  0.0  0.0  0.0
  2  0.0  0.0  0.0  0.0
```

#### Actual Output

```python
>>> f.sort_index(level=0)
      0   1   2   3
1 1 NaN NaN NaN NaN
  2 NaN NaN NaN NaN
2 1 NaN NaN NaN NaN
  2 NaN NaN NaN NaN
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.0.0-36-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 0.25.3
numpy            : 1.17.4
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.2.2
setuptools       : 41.0.1
Cython           : 0.29.14
pytest           : 3.10.1
hypothesis       : None
sphinx           : 2.2.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.9.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.2
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by MisterKeefe** [comment]
I am not a pandas expert, but it seems the issue might be with the `fill_value` of the underlying `Block` object for sparse columns. I would expect the `fill_value` of the block to be the same as the `fill_value` of the column wrapping the block in a `SingleBlockManager`.

**Comment by MisterKeefe** [comment]
https://github.com/pandas-dev/pandas/blob/master/pandas/core/internals/blocks.py#L1723 

This seems to be the offending line -- for an `ExtensionBlock`, the `na_value` from the dtype is used for the `fill_value`. Perhaps it should read `return self.values.dtype.fill_value`? This would fix my immediate problem but probably break something else

**Comment by Dr-Irv** [comment]
In version 1.1.1, this does not happen.

**Comment by Dr-Irv** [comment]
A PR that creates a test case would be welcomed.

**Comment by ylin00** [comment]
take
