### ISSUE TITLE
CI: Action to assign issues fails when quotes are present

### ISSUE THREAD

**Issue by ivirshup** [pandas-dev/pandas#29768]
So, this is a little weird. Apparently I left such a bad comment on an issue, it failed CI 😄. 

I'm not sure how it got triggered, but looks like it's from a recently added workflow. The CI error has the contents of my comment, and I got an email that looks like this:

<details>
<summary> Notification email </summary>

------------

Run failed for master (6d11aa8)

Repository: pandas-dev/pandas
Workflow: Assign
Duration: 16.0 seconds
Finished: 2019-11-21 05:41:26 UTC

[View results](https://github.com/pandas-dev/pandas/commit/6d11aa89fc06ebc55519507f6652dcfcba35a302/checks)

Jobs:
[cb4db6dd-e658-55b7-b337-8761517bc1a3](https://github.com/pandas-dev/pandas/runs/313172123) failed (1 annotation)
—
You are receiving this because this workflow ran on your branch.
Manage your GitHub Actions notifications here.

-------------------

</details>

* [CI failure](https://github.com/pandas-dev/pandas/runs/313172123) - [Raw log](https://pipelines.actions.githubusercontent.com/xZyE9jtmkxWlfCAbyu1SHPJOlsa2huNFYcxohSTomy6EbdNZT9/_apis/pipelines/1/runs/857/signedlogcontent/3?urlExpires=2019-11-21T06%3A00%3A03.3232502Z&urlSigningMethod=HMACV1&urlSignature=vlq2JBJLcoJ3pFQnugH8M9AcGnopXrvuooUOaeU2eAA%3D)
* [The comment](https://github.com/pandas-dev/pandas/issues/14177)

Looks like this might be related to #29648, @datapythonista?

**Comment by WillAyd** [comment]
This isn't coming from pandas but your local branch right? We did add GH actions recently so it might fail on your branch if not set up

**Comment by datapythonista** [comment]
Thanks for reporting this @ivirshup. We have an action that assigns issues if a comment with the exact text `take` is written. Looks like it fails when comments that are evaluated are compared, since quotes are not escaped.

**Comment by tigerey3** [comment]
I would like to work on this issue given that it's still unassigned!

**Comment by datapythonista** [comment]
Sure, thanks for the help! It's assigned to you, you can assign issues to yourself by writing a comment with just `take`

**Comment by datavizard** [comment]
take

**Comment by lithomas1** [comment]
Is anyone still working on this? If not, I can take it.

**Comment by datapythonista** [comment]
I don't think anyone is working on this, and should be a fast task. Unassigned the issue.

**Comment by lithomas1** [comment]
take
