### ISSUE TITLE
GroupBy Doesn't Always Maintain Column Index Name

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#29764]
Just as a follow up to #29124 discovered during #29753 - looks like the column name is dropped for any/all and transformation functions in groupby

```python
>>> df = pd.DataFrame([[1]], columns=pd.Index(["a"], name="idx"))
>>> df.groupby([1]).sum()
idx  a
1    1
>>> df.groupby([1]).any()
      a
1  True
>>> df.groupby([1]).shift()
    a
0 NaN
```

**Comment by marco-neumann-jdas** [comment]
Reading through the code example, I think this should be "GroupBy Doesn't Always Maintain **Index** Name".

**Comment by WillAyd** [comment]
Thanks! Updated to clarify
