### ISSUE TITLE
sort_values order ignored when sorting multiple columns

### ISSUE THREAD

**Issue by dzanaga** [pandas-dev/pandas#29769]
I am having issues sorting multiple columns in reverse order:

```
x_vals = [0, 0, 2, 0, 1, 0, 0, 1, 1, 1]
y_vals = [1, 2, 2, 2, 2, 0, 2, 1, 1, 2]

df = pd.DataFrame({'x': x_vals, 
                   'y': y_vals})

df0 = df.sort_values(['y', 'x'])
df1 = df.sort_values(['y', 'x'], ascending=['False', 'True'])
df2 = df.sort_values(['y', 'x'], ascending=['False', 'False'])
df3 = df.sort_values(['y', 'x'], ascending=['True', 'False'])

print(np.all(df0 == df1),
        np.all(df1 == df2),
        np.all(df2 == df3))

```
returns `True True True`, e. g. I cannot manage to sort by `'y'` in reverse order. I would expect the comparisons to return `False False False`. The columns dataframes are always sorted in ascending order. 

If I do `df.sort_values('y', ascending=False)` then it works as expected and the y values are sorted in descending order.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-693.el7.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.3
numpy            : 1.17.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.2.3
setuptools       : 41.6.0.post20191101
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.9.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.0
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : None
xarray           : 0.13.0
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by krunal-shah** [comment]
True and False are keywords, use them without the quotations and it will work. So you want to write

```
x_vals = [0, 0, 2, 0, 1, 0, 0, 1, 1, 1]
y_vals = [1, 2, 2, 2, 2, 0, 2, 1, 1, 2]

df = pd.DataFrame({'x': x_vals, 
                   'y': y_vals})

df0 = df.sort_values(['y', 'x'])
df1 = df.sort_values(['y', 'x'], ascending=[False, True])
df2 = df.sort_values(['y', 'x'], ascending=[False, False])
df3 = df.sort_values(['y', 'x'], ascending=[True, False])

df0.equals(df1)
df1.equals(df2)
df2.equals(df3)
```
Additionally, if you want to use ```df0 == df1```, you will have to use ```df0 = df0.reset_index(drop = True)``` for all the data frames to make the sorted indices match, play around and you'll know what I mean.

**Comment by dzanaga** [comment]
@krunal-shah thanks for spotting it. I am gonna close this and go jump from a bridge :)
