### ISSUE TITLE
df.to_hdf(), HDF5 files containing strings generated by pandas are not usable by other software

### ISSUE THREAD

**Issue by seanngpack** [pandas-dev/pandas#29780]
#### Code Sample
```python

df = pd.DataFrame()
df = pd.read_csv(csv_file)
df.to_hdf('example.h5', '/data', complib='zlib', complevel=9)

Example csv file:
|   | col1  | col2     |   
| 0 | hello | the      |   
| 1 | world | computer |   
| 2 | lol   | is       |   


```
#### Problem description
**HDF5 files containing strings generated by pandas are not usable by software other than pandas**
When writing a csv file containing strings to a hdf5 file, the output is unreadable by other software because it outputs python code representation of the strings.

#### Step to reproduce
* Make a .csv file with the table I provided
* run the code I have provided
* use hdfviewer to see the dataset
* copy and paste the output:
<details>
  <summary>output</summary>
  (128, 4, 149, 185, 0, 0, 0, 0, 0, 0, 0, 140, 21, 110, 117, 109, 112, 121, 46, 99, 111, 114, 101, 46, 109, 117, 108, 116, 105, 97, 114, 114, 97, 121, 148, 140, 12, 95, 114, 101, 99, 111, 110, 115, 116, 114, 117, 99, 116, 148, 147, 148, 140, 5, 110, 117, 109, 112, 121, 148, 140, 7, 110, 100, 97, 114, 114, 97, 121, 148, 147, 148, 75, 0, 133, 148, 67, 1, 98, 148, 135, 148, 82, 148, 40, 75, 1, 75, 3, 75, 2, 134, 148, 104, 3, 140, 5, 100, 116, 121, 112, 101, 148, 147, 148, 140, 2, 79, 52, 148, 75, 0, 75, 1, 135, 148, 82, 148, 40, 75, 3, 140, 1, 124, 148, 78, 78, 78, 74, 255, 255, 255, 255, 74, 255, 255, 255, 255, 75, 63, 116, 148, 98, 136, 93, 148, 40, 140, 5, 104, 101, 108, 108, 111, 148, 140, 3, 116, 104, 101, 148, 140, 5, 119, 111, 114, 108, 100, 148, 140, 8, 99, 111, 109, 112, 117, 116, 101, 114, 148, 140, 3, 108, 111, 108, 148, 140, 2, 105, 115, 148, 101, 116, 148, 98, 46)

</details>

* run the output through an ascii to text generator
* here's the final result: `¹numpy.core.multiarray_reconstructnumpyndarrayKCbR(KKKhdtypeO4KKR(K|NNNJÿÿÿÿJÿÿÿÿK?tb](hellotheworldcomputerlolisetb`

**Comment by jreback** [comment]
see the section on external compatibility in https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-hdf5

this format is designed internal compatibility and may or may not work externally

**Comment by jreback** [comment]
storing in a fixed format is pickling things which likely doesn’t work externally

try using .appemd
