### ISSUE TITLE
Update logo in GitHub organization

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#29823]
Just realized that we still have the old logo in the GitHub organization: https://github.com/pandas-dev/

We probably want to have the [new one](https://dev.pandas.io/static/img/pandas_mark.svg), but I don't have permissions to do that.

May be an admin of the organization can make the change?

**Comment by TomAugspurger** [comment]
I think that's just @jreback or @wesm.

**Comment by jorisvandenbossche** [comment]
I seemed to have permissions for it, so updated it

**Comment by datapythonista** [comment]
Thanks!
