### ISSUE TITLE
deleting index column but index=False not working

### ISSUE THREAD

**Issue by aggraced** [pandas-dev/pandas#29835]
#### Code Sample, a copy-pastable example if possible

```python
df_new.to_excel('Misclassification.xlsx',index=False)
df.to_excel(output_file_name,index=False)

```
#### Problem description

I tried to export the dataframe into excel, and wanted to avoid the index column. However even I use index=false, it still failed. Would you able to help with it? Thanks. I'm using python 3.6 on Jupyter notebook

**Comment by srinivas-chatnalli** [comment]
df_new.to_excel('Misclassification.xlsx',index_label=None, header=False)

**Comment by AskariyanKarine** [comment]
Try updating pandas or installing a different code editor. I use Visual Studio Code and this code works correctly.
``` python
df_new.to_excel('Misclassification.xlsx', index=False)
df.to_excel(output_file_name, index=False)
```

**Comment by simonjayhawkins** [comment]
Thanks @aggraced for the report.

see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports detailing how to provide the necessary information for us to reproduce your bug.

closing this but feel free to open a new issue using the bug template.

**Comment by vbmark** [comment]
> df_new.to_excel('Misclassification.xlsx',index_label=None, header=False)

For other who come here, adding "index_label=None" made the column go away.
