### ISSUE TITLE
PERF: improve conversion to BooleanArray from int/float array

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#29838]
Currently, the creation of a BooleanArray from an int/float array goes through a conversion to object dtype (to do it together with the generic conversion from any list-like):

https://github.com/pandas-dev/pandas/blob/7d7f885856b0c3d51eaf15beaac9d4f30c23797d/pandas/core/arrays/boolean.py#L133-L145

For the specific case of int/float ndarray, this could be optimized with a specific path for those cases without the casting to object array (probably just skipping the `np.asarray(values, dtype=object)` if `values` is a float/int ndarray will be enough).

**Comment by leonicus** [comment]
take

**Comment by ethanywang** [comment]
take

**Comment by ethanywang** [comment]
take

**Comment by leonicus** [comment]
@ethanywang hi, you can't take the issue because it's assigned (to me :)). I had some technical difficulties last week, which stopped me from working on it, but I should submit a PR shortly. If you have a specific reason to want to take it or want to discuss, feel free to comment

**Comment by ethanywang** [comment]
@leonicus Hi Leonicus, sorry about taking this issue without asking you first, but we have submitted the PR and get a response from the maintainer... We saw you claimed it a week ago without doing anything, so we thought you were facing some difficulties to work on it. Actually, for now, we are doing this issue as a course project, and it is quite difficult for us to change the chosen issue as we have already submitted it to our professor... So sorry about that...

**Comment by leonicus** [comment]
@ethanywang that's OK, just please notice that the "take" keyword doesn't really work on assigned issues (as you can see, it is still assigned to me as well). So next time just write to the issue assignee to check
