### ISSUE TITLE
add to_cyclical function for cyclical data #enhancement 

### ISSUE THREAD

**Issue by ma7555** [pandas-dev/pandas#29849]
1- Short summary of the changes:

create a to_cyclical function that transforms ordinal or continous cyclical features to sine transform and cosine transform representing  the reality of the feature.

example if hours is to be taken as a feature, 23 and 01 is 22 units apart but in reality they are only two units apart.

![image](https://user-images.githubusercontent.com/7144929/69592267-19f7c700-0ffe-11ea-9857-8b5bdf4d214f.png)

If the idea is accepted as an enhancement, I would like to work on it and implement it then create a pull request.

2- Motivation for the changes:
This could add beneficial performance to classifiers and regressors in ML/DL

3-An explanation of why the change is in scope for pandas.
Dataframe / Series related, similar to pandas functions already implemented.

4-Detailed design: Preferably with example-usage (even if not implemented yet) and API documentation:
below is a quick code to the idea
```
def to_cyclical(a_series, max=None):
    if max:
        sin_ = np.sin(2*np.pi*a_series/max)
        cos_ = np.cos(2*np.pi*a_series/max)
    else:
        sin_ = np.sin(2*np.pi*df.col_name/a_series.max())
        cos_ = np.cos(2*np.pi*df.col_name/a_series.max())
    return pd.concat([sin_ , cos_ ], axis=1)
```
```
pandas.to_cyclical(series, max=None)
```
5-API Change: Any API changes that may result from the proposal:
Nothing i guess

Further readings for the solution:
https://ianlondon.github.io/blog/encoding-cyclical-features-24hour-time/
https://stats.stackexchange.com/questions/126230/optimal-construction-of-day-feature-in-neural-networks
https://datascience.stackexchange.com/questions/5990/what-is-a-good-way-to-transform-cyclic-ordinal-attributes

**Comment by jorisvandenbossche** [comment]
@ma7555 to me, this seems a very specific feature for a machine learning setting / feature engineering, so therefore think this is better suitable for a library focusing on that, and seems out of scope for pandas as a general dataframe library.

**Comment by ma7555** [comment]
@jorisvandenbossche Thanks for taking time to looking into it, I will propose the same directly into sk-learn maybe. 
Cheers
