### ISSUE TITLE
Replace "foo!r" to "repr(foo)" syntax

### ISSUE THREAD

**Issue by MomIsBestFriend** [pandas-dev/pandas#29886]
Since we are moving to f-strings and dropping old strings formats (```%``` and ```.format()```), we no longer need to have the redundant ```%r``` and ```!r``` specifiers, instead we use the ```repr()``` format.

#### Notes:
* Don't forget to link this issue in your PR, paste this ```https://github.com/pandas-dev/pandas/issues/29886``` in your PR.

* If any of your changed files are related to #29547 , please make sure to link your pull request to that issue as well, simply paste this ```https://github.com/pandas-dev/pandas/issues/29547``` in your pull request's body message as well.

* Please comment what you are planning to work on, so we won't do double work.

* If a file/files that should be marked as done, is'nt marked, please comment letting me know.

---

To check what files still needs to be fixed in the "pandas" directory:
```
grep -R -e '%r' -e '!r}' -e "'{}'" --include=*.{py,pyx} pandas/
```

##### Tip:
If you want to see the line number of the occurrence, replace the ```-l``` with ```-n```
for example:
```
grep -n -R '%r' --include=*.{py,pyx} pandas/
```

---

### The current list is:

- [x] ci/print_skipped.py

- [x] pandas/_config/config.py

- [x] pandas/conftest.py

- [x] pandas/core/accessor.py

- [x] pandas/core/algorithms.py

- [x] pandas/core/arrays/categorical.py

- [ ] pandas/core/arrays/datetimelike.py

- [ ] pandas/core/arrays/period.py

- [x] pandas/core/arrays/numpy_.py

- [x] pandas/core/computation/align.py

- [x] pandas/core/computation/eval.py

- [x] pandas/core/computation/expressions.py

- [x] pandas/core/computation/expr.py

- [x] pandas/core/computation/ops.py

- [x] pandas/core/computation/pytables.py

- [x] pandas/core/dtypes/common.py

- [x] pandas/core/dtypes/dtypes.py

- [x] pandas/core/frame.py

- [x] pandas/core/generic.py

- [x] pandas/core/groupby/grouper.py

- [x] pandas/core/indexes/base.py

- [x] pandas/core/indexes/datetimelike.py

- [x] pandas/core/indexes/interval.py

- [x] pandas/core/indexes/numeric.py

- [x] pandas/core/internals/concat.py

- [x] pandas/core/internals/managers.py

- [x] pandas/core/missing.py

- [x] pandas/core/nanops.py

- [x] pandas/core/reshape/concat.py

- [x] pandas/core/reshape/merge.py

- [x] pandas/core/reshape/tile.py

- [x] pandas/core/series.py

- [x] pandas/core/sorting.py

- [x] pandas/core/strings.py

- [x] pandas/core/window/rolling.py

- [x] pandas/\_\_init\_\_.py

- [x] pandas/io/formats/css.py

- [x] pandas/io/formats/excel.py

- [ ] pandas/io/formats/style.py

- [x] pandas/io/html.py

- [x] pandas/io/parsers.py

- [x] pandas/_libs/interval.pyx

- [x] pandas/plotting/_core.py

- [x] pandas/tests/computation/test_eval.py

- [x] pandas/tests/frame/test_alter_axes.py

- [x] pandas/tests/frame/test_analytics.py

- [x] pandas/tests/frame/test_query_eval.py

- [x] pandas/tests/groupby/test_whitelist.py

- [x] pandas/tests/indexes/datetimes/test_datetime.py

- [x] pandas/tests/indexes/multi/test_integrity.py

- [x] pandas/tests/indexes/period/test_period.py

- [x] pandas/tests/indexes/test_common.py

- [ ] pandas/tests/indexes/timedeltas/test_timedelta.py

- [x] pandas/tests/io/msgpack/test_case.py

- [x] pandas/tests/io/msgpack/test_extension.py

- [x] pandas/tests/io/parser/test_unsupported.py

- [x] pandas/tests/io/test_html.py

- [x] pandas/tests/test_expressions.py

- [x] pandas/tests/test_strings.py

- [ ] pandas/tests/io/test_sql.py

- [ ] pandas/tests/reshape/test_concat.py

- [ ] pandas/tests/scalar/timedelta/test_timedelta.py

- [x] pandas/tests/series/test_missing.py

- [x] pandas/tests/tseries/offsets/test_fiscal.py

- [x] pandas/tests/tseries/offsets/test_offsets.py

- [x] pandas/tseries/offsets.py

- [x] pandas/util/_decorators.py

- [x] pandas/util/_test_decorators.py

- [x] pandas/util/testing.py

- [x] pandas/_version.py

- [ ] /scripts/tests/test_validate_docstrings.py
---

#### Lastly:
- [ ] Add a test case (so we won't regress)

**Comment by jbrockmendel** [comment]
Another option that we use in quite a few places is single quotes `"foo '{bar}' baz"`

**Comment by MomIsBestFriend** [comment]
> Another option that we use in quite a few places is single quotes `"foo '{bar}' baz"`

@jbrockmendel I'm kinda obligated about how to find them systemically, meaning what if there's is a change to the ```repr()``` function, and the single quotas are there to differ from the ```repr()``` (If they're any). plus I'm not sure how to grep for this pattern.

**Comment by MomIsBestFriend** [comment]
I'll take:
- [ ] pandas/tests/tseries/offsets/test_fiscal.py
- [ ] pandas/tests/tseries/offsets/test_offsets.py
- [ ] pandas/tseries/offsets.py
- [ ] pandas/util/_decorators.py
- [ ] pandas/util/testing.py

**Comment by souravs17031999** [comment]
working on :
pandas/core/sorting.py
currently if no one has taken it yet.
will add more as i go further.

**Comment by kvn219** [comment]
Working on: `pandas/core/groupby/grouper.py`

**Comment by ZGrinacoff** [comment]
Working on:  pandas/tests/groupby/test_whitelist.py

**Comment by souravs17031999** [comment]
hi @kvn219 , actually i am already working on three files one of which is what you have also mentioned , can you please work on some other file.

**Comment by JvPy** [comment]
I`ll take 

pandas/core/accessor.py

pandas/core/algorithms.py

**Comment by EydenVillanueva** [comment]
Hi to everyone, I will take:

- `pandas/_config/config.py`
- `pandas/conftest.py`
- `pandas/core/accessor.py`
- `pandas/core/algorithms.py`

**Comment by JvPy** [comment]
Ill take 
core/indexes/numeric.py
core/frame.py 

if possible.

Ill do them on saturday

**Comment by nigeltart** [comment]
I'm working on pandas/core/arrays/numpy_.py

**Comment by chrisateen** [comment]
I am going to do pandas/utils/_test_decorators.py which is not on the original list but seems not to be updated

**Comment by MomIsBestFriend** [comment]
> I am going to do pandas/utils/_test_decorators.py which is not on the original list but seems not to be updated

Thanks @chrisateen

**Comment by nigeltart** [comment]
> I'm working on pandas/core/arrays/numpy_.py

Sorry, it was literally my first attempt at a pull request. I'll come back when I know enough to help. Cheers

**Comment by EydenVillanueva** [comment]
> Hi to everyone, I will take:
> 
> * `pandas/_config/config.py`
> * `pandas/conftest.py`
> * `pandas/core/accessor.py`
> * `pandas/core/algorithms.py`

These files were already finished with the replacement (it would be good if they appear checked in the list).

So I will take the following files to work with:

- `pandas/tests/indexes/datetimes/test_partial_slicing.py` (not on the list, but not updated)
- `pandas/core/nanops.py`
- `pandas/core/missing.py`
- `pandas/core/indexes/period.py` (not on the list, but not updated)

**Comment by lithomas1** [comment]
I'm taking
- [ ] pandas/io/formats/excel.py
- [ ] pandas/io/formats/css.py
- [ ] pandas/io/formats/style.py

**Comment by AncientRickles** [comment]
I'll do:

* [ ] pandas/core/indexes/numeric.py
* [ ] pandas/core/indexes/interval.py
* [ ] pandas/core/computation/eval.py
* [ ] pandas/core/reshape/tile.py
* [ ] pandas/core/indexes/base.py

**Comment by baevpetr** [comment]
I'll do:
- [  ]  pandas/core/arrays/categorical.py
- [  ]  pandas/core/arrays/datetimelike.py
- [  ]  pandas/core/computation/align.py
- [  ]  pandas/core/computation/expressions.py

**Comment by AncientRickles** [comment]
Jumping on:
* [ ] pandas/core/arrays/datetimelike.py
* [ ] pandas/core/arrays/period.py
* [ ] pandas/io/formats/printing.py
* [ ] pandas/tests/extension/list/array.py
* [ ] pandas/tests/indexes/datetimes/test_ops.py

**Comment by MomIsBestFriend** [comment]
@WillAyd Can you please reopen this issue?

In [this PR](https://github.com/pandas-dev/pandas/pull/30420) he uses the word ```fix``` and after that this PR number, so it closed it.

**Comment by WillAyd** [comment]
done - thanks!

**Comment by AncientRickles** [comment]
> @WillAyd Can you please reopen this issue?
> 
> In [this PR](https://github.com/pandas-dev/pandas/pull/30420) there is a use of the word `fix` and after that this PR number, so it closed it.

Sorry about that. Still kinda new to this...

**Comment by MomIsBestFriend** [comment]
> Sorry about that. Still kinda new to this...

It's perfectly fine :)

**Comment by naomi172839** [comment]
pandas/tests/test_strings.py was checked and already uses f-strings.
pandas/core/dtypes/common.py was checked and already uses f-strings.
pandas/tests/indexes/test_common.py was checked and already uses f-strings.
pandas/core/window/rolling.py was checked and already uses f-strings.
pandas/core/computation/pytables.py was checked and already uses f-strings.
pandas/tests/indexes/datetimes/test_datetime.py was checked and already uses f-strings.
pandas/core/generic.py was checked and already uses f-strings.

If possible, it would be great to update the master list.

**Comment by MomIsBestFriend** [comment]
> pandas/tests/test_strings.py was checked and already uses f-strings.
> pandas/core/dtypes/common.py was checked and already uses f-strings.
> pandas/tests/indexes/test_common.py was checked and already uses f-strings.
> pandas/core/window/rolling.py was checked and already uses f-strings.
> pandas/core/computation/pytables.py was checked and already uses f-strings.
> pandas/tests/indexes/datetimes/test_datetime.py was checked and already uses f-strings.
> pandas/core/generic.py was checked and already uses f-strings.
> 
> If possible, it would be great to update the master list.

TY, really appreciate it

**Comment by MomIsBestFriend** [comment]
@jreback Can you please reopen this issue?

The PR was suppose to contain two test cases, but it only contained one.

This should be reopen.

**Comment by MomIsBestFriend** [comment]
Thanks @jreback

**Comment by naomi172839** [comment]
pandas/core/arrays/datetimelike.py
pandas/core/arrays/period.py

Both of the above are free of the old style strings.
I am working on:
pandas/__init__.py

**Comment by naomi172839** [comment]
I tackled the remaining files.  Did not implement a test though.

**Comment by TomAugspurger** [comment]
So the only remaining item is a code check test for `!r` rather than repr?

**Comment by TomAugspurger** [comment]
Actually, it looks like we have a check for that. @MomIsBestFriend is there anything else to do here?

**Comment by MomIsBestFriend** [comment]
@TomAugspurger I think not :smiley: 

Thank you all for helping :heart:
