### ISSUE TITLE
Strange behaviour of pd.offsets.CustomBusinessHour when using holidays

### ISSUE THREAD

**Issue by maxQC** [pandas-dev/pandas#29901]
#### Code Sample, a copy-pastable example if possible

```python
import datetime
import pandas as pd
from pandas.tseries.holiday import USFederalHolidayCalendar

bhour_us = pd.offsets.CustomBusinessHour(calendar=USFederalHolidayCalendar())
#bhour_us = pd.offsets.CustomBusinessHour(calendar=USFederalHolidayCalendar(),start='07:00')
#bhour_us = pd.offsets.CustomBusinessHour(calendar=USFederalHolidayCalendar(),holidays=['2014-01-21'])
#bhour_us = pd.offsets.CustomBusinessHour(calendar=USFederalHolidayCalendar(),holidays=['2014-01-21','2014-01-22'])
#bhour_us = pd.offsets.CustomBusinessHour(calendar=USFederalHolidayCalendar(),holidays=['2014-01-21','2014-02-06'])

dt = datetime.datetime(2014, 1, 17, 13)

for i in range(1,30):
    y = dt + bhour_us * i
    print(y)
```
>>>
2014-01-17 14:00:00
2014-01-17 15:00:00
2014-01-17 16:00:00
2014-01-21 09:00:00
2014-01-21 10:00:00
2014-01-21 11:00:00
2014-01-21 12:00:00
**_2014-01-20 13:00:00
2014-01-31 14:00:00
2014-01-31 15:00:00
2014-01-31 16:00:00
2014-02-03 09:00:00
2014-02-03 10:00:00
2014-02-03 11:00:00
2014-02-03 12:00:00_**
2014-01-21 13:00:00
2014-01-21 14:00:00
2014-01-21 15:00:00
2014-01-21 16:00:00
2014-01-22 09:00:00
2014-01-22 10:00:00
2014-01-22 11:00:00
2014-01-22 12:00:00
2014-01-22 13:00:00
2014-01-22 14:00:00
2014-01-22 15:00:00
2014-01-22 16:00:00
2014-01-23 09:00:00
2014-01-23 10:00:00

#### Problem description
CustomBusinessHour behaves strangely when I try to use a custom calendar (same behaviour when using a list of holidays directly).

In the example above, I modified the example from the official doc.
https://pandas.pydata.org/pandas-docs/version/0.18.1/timeseries.html#timeseries-custombusinesshour

Something strange happens (here at i in range(8, 16)).

Then, the rest is fine, but shifted away.

Playing with the calendar and length of the business day (start and end) affects this.
This seems related in some sense to a mod function somewhere... But I can't get my finger on it.
#### Expected Output
2014-01-17 14:00:00
2014-01-17 15:00:00
2014-01-17 16:00:00
2014-01-21 09:00:00
2014-01-21 10:00:00
2014-01-21 11:00:00
2014-01-21 12:00:00
2014-01-21 13:00:00
2014-01-21 14:00:00
2014-01-21 15:00:00
2014-01-21 16:00:00
2014-01-22 09:00:00
2014-01-22 10:00:00
2014-01-22 11:00:00
2014-01-22 12:00:00
2014-01-22 13:00:00
2014-01-22 14:00:00
2014-01-22 15:00:00
2014-01-22 16:00:00
2014-01-23 09:00:00
2014-01-23 10:00:00
2014-01-23 11:00:00
2014-01-23 12:00:00
2014-01-23 13:00:00
2014-01-23 14:00:00
2014-01-23 15:00:00
2014-01-23 16:00:00
2014-01-24 09:00:00
2014-01-24 10:00:00
#### Output of ``pd.show_versions()``
<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en
LOCALE           : None.None

pandas           : 0.25.3
numpy            : 1.17.3
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 42.0.1.post20191125
Cython           : 0.29.14
pytest           : 5.3.0
hypothesis       : None
sphinx           : 2.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.2.6
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.9.0
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : 1.3.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 3.0.1
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.3.11
tables           : 3.6.1
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.6
</details>

**Comment by TSPereira** [comment]
So, by great coincidence I also got this problem yesterday.
I have defined a CustomBusinessHour with working hours from 07:00 to 01:00 and when I perform calculations between a timestamp and some amounts of these business hours, I don't get the expected results.

As you can see below, the behaviour is as expected except for some specific hours, which can be identified as a pattern

`import pandas as pd
cbh = pd.offsets.CustomBusinessHour(start='07:00', end='01:00')
time = pd.Timestamp('2019-03-06 13:00:00')
for i in range(48):
    print(i, ':', time - i * cbh)`

0 : 2019-03-06 13:00:00
1 : 2019-03-06 12:00:00
2 : 2019-03-06 11:00:00
3 : 2019-03-06 10:00:00
4 : 2019-03-06 09:00:00
5 : 2019-03-06 08:00:00
6 : 2019-03-06 01:00:00
7 : 2019-03-06 00:00:00
8 : 2019-03-05 23:00:00
9 : 2019-03-05 22:00:00
10 : 2019-03-05 21:00:00
11 : 2019-03-05 20:00:00
**12 : 2019-03-06 01:00:00
13 : 2019-03-06 00:00:00
14 : 2019-03-05 23:00:00
15 : 2019-03-05 22:00:00
16 : 2019-03-05 21:00:00
17 : 2019-03-05 20:00:00**
18 : 2019-03-05 13:00:00
19 : 2019-03-05 12:00:00
20 : 2019-03-05 11:00:00
21 : 2019-03-05 10:00:00
22 : 2019-03-05 09:00:00
23 : 2019-03-05 08:00:00
24 : 2019-03-05 01:00:00
25 : 2019-03-05 00:00:00
26 : 2019-03-04 23:00:00
27 : 2019-03-04 22:00:00
28 : 2019-03-04 21:00:00
29 : 2019-03-04 20:00:00
**30 : 2019-03-05 01:00:00
31 : 2019-03-05 00:00:00
32 : 2019-03-04 23:00:00
33 : 2019-03-04 22:00:00
34 : 2019-03-04 21:00:00
35 : 2019-03-04 20:00:00**
36 : 2019-03-04 13:00:00
37 : 2019-03-04 12:00:00
38 : 2019-03-04 11:00:00
39 : 2019-03-04 10:00:00
40 : 2019-03-04 09:00:00
41 : 2019-03-04 08:00:00
42 : 2019-03-02 01:00:00
43 : 2019-03-02 00:00:00
44 : 2019-03-01 23:00:00
45 : 2019-03-01 22:00:00
46 : 2019-03-01 21:00:00
47 : 2019-03-01 20:00:00


**Expected output:**

0 : 2019-03-06 13:00:00
1 : 2019-03-06 12:00:00
2 : 2019-03-06 11:00:00
3 : 2019-03-06 10:00:00
4 : 2019-03-06 09:00:00
5 : 2019-03-06 08:00:00
6 : 2019-03-06 01:00:00
7 : 2019-03-06 00:00:00
8 : 2019-03-05 23:00:00
9 : 2019-03-05 22:00:00
10 : 2019-03-05 21:00:00
11 : 2019-03-05 20:00:00
**12 : 2019-03-05 19:00:00
13 : 2019-03-05 18:00:00
14 : 2019-03-05 17:00:00
15 : 2019-03-05 16:00:00
16 : 2019-03-05 15:00:00
17 : 2019-03-05 14:00:00**
18 : 2019-03-05 13:00:00
19 : 2019-03-05 12:00:00
20 : 2019-03-05 11:00:00
21 : 2019-03-05 10:00:00
22 : 2019-03-05 09:00:00
23 : 2019-03-05 08:00:00
24 : 2019-03-05 01:00:00
25 : 2019-03-05 00:00:00
26 : 2019-03-04 23:00:00
27 : 2019-03-04 22:00:00
28 : 2019-03-04 21:00:00
29 : 2019-03-04 20:00:00
**30 : 2019-03-04 19:00:00
31 : 2019-03-04 18:00:00
32 : 2019-03-04 17:00:00
33 : 2019-03-04 16:00:00
34 : 2019-03-04 15:00:00
35 : 2019-03-04 14:00:00**
36 : 2019-03-04 13:00:00
37 : 2019-03-04 12:00:00
38 : 2019-03-04 11:00:00
39 : 2019-03-04 10:00:00
40 : 2019-03-04 09:00:00
41 : 2019-03-04 08:00:00
42 : 2019-03-02 01:00:00
43 : 2019-03-02 00:00:00
44 : 2019-03-01 23:00:00
45 : 2019-03-01 22:00:00
46 : 2019-03-01 21:00:00
47 : 2019-03-01 20:00:00



**Output of pd.versions**

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.4.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.24.2
pytest: None
pip: 19.1.1
setuptools: 41.0.1
Cython: 0.29.12
numpy: 1.16.4
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.8.0
sphinx: None
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.1.0
openpyxl: None
xlrd: 1.2.0
xlwt: None
xlsxwriter: None
lxml.etree: 4.3.4
bs4: 4.7.1
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: 2.7.6.1 (dt dec pq3 ext lo64)
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

**Comment by maxQC** [comment]
I went through a couple of hoops to get what I needed.
I currently use the following function I made:

```python
def customBHours(startDate,
                   hoursToOffset,
                   cal=None,
                   hol=None,
                   shiftStart='07:00',
                   shiftEnd='15:00'
                   ):
    """
    Patch because CustomBusinessHour bahaves strangely
    https://github.com/pandas-dev/pandas/issues/29901
    
    Can be used with positive, 0, or negative hoursToOffset
    
    hoursToOffset will be rounded to nearest int
    """
    import pandas as pd
    from pandas.tseries.holiday import Holiday, AbstractHolidayCalendar

    hoursToOffset = round(hoursToOffset)
    
    shiftLen = pd.Timedelta(pd.Timestamp(shiftEnd)-
                            pd.Timestamp(shiftStart)).total_seconds()/3600

    if hoursToOffset == 0:
        return startDate
    elif hoursToOffset > 0:
        completeshifts = hoursToOffset//shiftLen
        hoursRemainding = hoursToOffset-(completeshifts*shiftLen)
    else:
        completeshifts = hoursToOffset//shiftLen + 1
        hoursRemainding = hoursToOffset-(completeshifts*shiftLen) - shiftLen

    cbd = pd.offsets.CustomBusinessDay(calendar=cal,
                                       holidays=hol)
    cbh = pd.offsets.CustomBusinessHour(calendar=cal,
                                        holidays=hol,
                                        start=shiftStart,
                                        end=shiftEnd
                                        )
    if hoursRemainding == 0:
        return startDate + cbd*completeshifts
    else:
        return startDate +  cbd*completeshifts + cbh*hoursRemainding
```

**Comment by maxQC** [comment]
Modified it to account for shifts crossing midnight, works with negative increments too.

```python
def customBHours(startDate,
                   hoursToOffset,
                   cal=None,
                   hol=None,
                   shiftStart='07:00',
                   shiftEnd='15:00'
                   ):
    """
    Patch because CustomBusinessHour bahaves strangely
    https://github.com/pandas-dev/pandas/issues/29901
    
    Can be used with positive, 0, or negative hoursToOffset
    
    hoursToOffset will be rounded to nearest int
    """
    import pandas as pd
    from pandas.tseries.holiday import Holiday, AbstractHolidayCalendar

    hoursToOffset = round(hoursToOffset)
    
    if pd.Timestamp(shiftEnd) > pd.Timestamp(shiftStart):
        shiftLen = pd.Timedelta(pd.Timestamp(shiftEnd)-
                                pd.Timestamp(shiftStart)).total_seconds()/3600
    else:
        shiftLen = 24 + (pd.Timedelta(pd.Timestamp(shiftEnd)-
                                pd.Timestamp(shiftStart)).total_seconds())/3600

    if hoursToOffset == 0:
        print(startDate)
        return startDate
    else:
        completeshifts = hoursToOffset//shiftLen
        hoursRemainding = hoursToOffset-(completeshifts*shiftLen)

    cbd = pd.offsets.CustomBusinessDay(calendar=cal,
                                       holidays=hol)
    cbh = pd.offsets.CustomBusinessHour(calendar=cal,
                                        holidays=hol,
                                        start=shiftStart,
                                        end=shiftEnd
                                        )
    if hoursRemainding == 0:
        return startDate + cbd*completeshifts
    else:
        return startDate +  cbd*completeshifts + cbh*hoursRemainding
```

**Comment by TSPereira** [comment]
Thanks, your implementation is really neat. I think I'll try to adapt it to also include partial hours (such as 1,5). 
I have made something about this in my code and I think it might be useful.
I'll post it in the end (not sure when though)

**Comment by TSPereira** [comment]
I think this works. Removed the import outside and the final if you had since the calculation can be made even with cbh = 0. Also added the weekmask as this is relevant for my problem.

```
import pandas as pd


def customBHours(startDate,
                 hoursToOffset,
                 weekmask='Mon Tue Wed Thu Fri',
                 cal=None,
                 hol=None,
                 shiftStart='07:00',
                 shiftEnd='15:00'
                 ):
    """
    Patch because CustomBusinessHour bahaves strangely
    https://github.com/pandas-dev/pandas/issues/29901

    Can be used with positive, 0, or negative hoursToOffset

    hoursToOffset will be rounded to nearest int
    """

    minutes = 0
    if not float(hoursToOffset).is_integer():
        minutes = round((hoursToOffset - int(hoursToOffset)) * 60)
        hoursToOffset = int(hoursToOffset)

    hours = int(hoursToOffset)
    minutes = pd.Timedelta(minutes=minutes)

    # Find shifts length
    if pd.Timestamp(shiftEnd) > pd.Timestamp(shiftStart):
        shiftLen = pd.Timedelta(pd.Timestamp(shiftEnd) -
                                pd.Timestamp(shiftStart)).total_seconds() / 3600
    else:
        shiftLen = 24 + (pd.Timedelta(pd.Timestamp(shiftEnd) -
                                      pd.Timestamp(shiftStart)).total_seconds()) / 3600

    if hoursToOffset == 0:
        return startDate
    else:
        completeshifts = hoursToOffset//shiftLen
        hoursRemainding = hoursToOffset-(completeshifts*shiftLen)

    # Define business day and hour
    cbd = pd.offsets.CustomBusinessDay(calendar=cal,
                                       holidays=hol,
                                       weekmask=weekmask)
    cbh = pd.offsets.CustomBusinessHour(calendar=cal,
                                        holidays=hol,
                                        start=shiftStart,
                                        end=shiftEnd,
                                        weekmask=weekmask
                                        )

    return startDate + cbd * completeshifts + cbh * hoursRemainding + minutes
```

**Comment by maxQC** [comment]
That would be very nice!
Thank you and I wish you a nice day

**Comment by TSPereira** [comment]
Updated my comment with the code to exit right at beginning if hours==0 and also so that variables comply with PEP8 standards

**Comment by TSPereira** [comment]
New update. complete_shifts calculation with "//" for negative values was not working correctly. 
For example:

`-4 // 18`

evaluates to -1 when it should be 0.

**Comment by TSPereira** [comment]
I was double checking the function and this still have some issues.

This still produces wrong output
```python
custom_bhours_shift(pd.Timestamp('2019-03-13 21:00:00'), -4, start='07:00', end='01:00')
```

**output**
`Timestamp('2019-03-13 11:00:00')`

**expected output**
`Timestamp('2019-03-13 17:00:00')'

**Comment by maxQC** [comment]
Cleaned a bit.
(hour precision)

Works with
```python
customBHours(pd.Timestamp('2019-03-13 21:00:00'), -4, start='07:00', end='01:00')

```

```python
import pandas as pd

def customBHours(startDate, hours, weekmask='Mon Tue Wed Thu Fri', cal=None, hol=None, start='07:00',end='15:00'):
    """
    Patch because CustomBusinessHour bahaves strangely
    https://github.com/pandas-dev/pandas/issues/29901
    
    Can be used with positive, 0, or negative hours
    
    hours will be rounded to nearest int
    """
    import pandas as pd

    hours = round(hours)
    
    if pd.Timestamp(end).time() > pd.Timestamp(start).time():
        shiftLen = pd.Timedelta(pd.Timestamp(end) - pd.Timestamp(start)).total_seconds()/3600
    else:
        shiftLen = 24 + (pd.Timedelta(pd.Timestamp(end) - pd.Timestamp(start)).total_seconds())/3600

    if hours == 0:
        return startDate
    else:
        completeshifts = hours//shiftLen
        hoursRemainding = hours-(completeshifts*shiftLen)

    cbd = pd.offsets.CustomBusinessDay(calendar=cal, holidays=hol, weekmask=weekmask)
    cbh = pd.offsets.CustomBusinessHour(calendar=cal, holidays=hol, weekmask=weekmask, start=start, end=end)
    
    if hoursRemainding == 0:
        return startDate + cbd*completeshifts
    else:
        return startDate + cbd*completeshifts + cbh*hoursRemainding

```
#### Output
```
Timestamp('2019-03-13 17:00:00')`
```
#### Expected Output
```
Timestamp('2019-03-13 17:00:00')
```

**Comment by maxQC** [comment]
Edited Code in previous post (I had copied the wrong version...)

**Comment by TSPereira** [comment]
Still doesn't work, at least with shifts that go over midnight (most likely my issue here)

```python

import pandas as pd

def customBHours(startDate, hours, weekmask='Mon Tue Wed Thu Fri', cal=None, hol=None, start='07:00', end='15:00'):
    """
    Patch because CustomBusinessHour bahaves strangely
    https://github.com/pandas-dev/pandas/issues/29901
    Can be used with positive, 0, or negative hours
    hours will be rounded to nearest int
    """
    if hours == 0:
        return startDate
    hours = round(hours)
    if pd.Timestamp(end).time() > pd.Timestamp(start).time():
        shiftLen = pd.Timedelta(pd.Timestamp(end) - pd.Timestamp(start)).total_seconds() / 3600
    else:
        shiftLen = 24 + (pd.Timedelta(pd.Timestamp(end) - pd.Timestamp(start)).total_seconds()) / 3600
    bDays = hours // shiftLen
    remainingHours = hours - (bDays * shiftLen)
    cbd = pd.offsets.CustomBusinessDay(calendar=cal, holidays=hol, weekmask=weekmask)
    cbh = pd.offsets.CustomBusinessHour(calendar=cal, holidays=hol, weekmask=weekmask, start=start, end=end)
    if remainingHours == 0:
        return startDate + cbd * bDays
    else:
        return startDate + cbd * bDays + cbh * remainingHours
    
time = pd.Timestamp('2019-03-13 22:00:00')
for i in range(48):
    print(i, ':', customBHours(time, -i, end='01:00'))
```
    
0 : 2019-03-13 22:00:00
**1 : 2019-03-13 15:00:00
2 : 2019-03-13 14:00:00
3 : 2019-03-13 13:00:00
4 : 2019-03-13 12:00:00
5 : 2019-03-13 11:00:00
6 : 2019-03-13 10:00:00
7 : 2019-03-13 09:00:00
8 : 2019-03-13 08:00:00
9 : 2019-03-13 07:00:00**
10 : 2019-03-13 12:00:00
11 : 2019-03-13 11:00:00
12 : 2019-03-13 10:00:00
13 : 2019-03-13 09:00:00
14 : 2019-03-13 08:00:00
15 : 2019-03-13 07:00:00
16 : 2019-03-13 00:00:00
17 : 2019-03-12 23:00:00
18 : 2019-03-12 22:00:00
**19 : 2019-03-12 15:00:00
20 : 2019-03-12 14:00:00
21 : 2019-03-12 13:00:00
22 : 2019-03-12 12:00:00
23 : 2019-03-12 11:00:00
24 : 2019-03-12 10:00:00
25 : 2019-03-12 09:00:00
26 : 2019-03-12 08:00:00
27 : 2019-03-12 07:00:00**
28 : 2019-03-12 12:00:00
29 : 2019-03-12 11:00:00
30 : 2019-03-12 10:00:00
31 : 2019-03-12 09:00:00
32 : 2019-03-12 08:00:00
33 : 2019-03-12 07:00:00
34 : 2019-03-12 00:00:00
35 : 2019-03-11 23:00:00
36 : 2019-03-11 22:00:00
**37 : 2019-03-09 15:00:00
38 : 2019-03-09 14:00:00
39 : 2019-03-09 13:00:00
40 : 2019-03-09 12:00:00
41 : 2019-03-09 11:00:00
42 : 2019-03-09 10:00:00
43 : 2019-03-09 09:00:00
44 : 2019-03-09 08:00:00
45 : 2019-03-09 07:00:00**
46 : 2019-03-11 12:00:00
47 : 2019-03-11 11:00:00


**expected output (on bold groups)**
1 : 2019-03-13 21:00:00
2 : 2019-03-13 20:00:00
3 : 2019-03-13 19:00:00
4 : 2019-03-13 18:00:00
5 : 2019-03-13 17:00:00
6 : 2019-03-13 16:00:00
7 : 2019-03-13 15:00:00
8 : 2019-03-13 14:00:00
9 : 2019-03-13 13:00:00

**Comment by TSPereira** [comment]
I have remade the function to don't use business hours as I think the problem is in the implementation of those. From the tests I made so far it seems to be working fine for any shift hours. 

```python
def custom_bhours_shift(start_date, offset_hours, weekmask='Mon Tue Wed Thu Fri', cal=None, hol=None, start='08:00',
                        end='17:00'):
    """
    Patch because CustomBusinessHour bahaves strangely
    https://github.com/pandas-dev/pandas/issues/29901

    Can be used with positive, 0, negative or partial hours

    hours will be rounded to nearest int
    """

    if offset_hours == 0:
        return start_date

    # Convert start_date.time, start and end to fractional hours
    date_s = pd.Timedelta(start_date.time().isoformat()).total_seconds()
    start_s = pd.Timedelta(pd.Timestamp(start).time().isoformat()).total_seconds()
    end_s = pd.Timedelta(pd.Timestamp(end).time().isoformat()).total_seconds()
    d_s = 24 * 3600

    # Find whether to subtract or add
    sign = offset_hours / abs(offset_hours)
    offset_hours = abs(offset_hours) * 3600

    # Find shifts length
    if end_s < start_s:
        end_s += d_s
    shift_len = end_s - start_s

    # find nr of shifts and remaining hours
    comp_shifts = offset_hours // shift_len
    h_rem = offset_hours - (comp_shifts * shift_len)

    if sign < 0:
        diff = h_rem - (date_s - start_s) >= 0
        comp_shifts += diff
        add_time = shift_len - h_rem if diff else -h_rem

    else:
        diff = h_rem - (end_s - date_s) > 0
        comp_shifts += diff
        add_time = h_rem - shift_len if diff else h_rem

    cbd = pd.offsets.CustomBusinessDay(calendar=cal, holidays=hol, weekmask=weekmask)
    return start_date + sign * (comp_shifts * cbd) + pd.Timedelta(round(add_time), unit='s')

```

**Comment by TSPereira** [comment]
In more extensive test still found a new issue. If start_date outside of working hours, the calculations is still wrong. Will have to write something to roll the date to the limit of the business hours first and then apply the function.

**Comment by TSPereira** [comment]
I guess the problem starts with the "onOffset" method. Simple example with working hours over midnight. As you can see, it is only working in the period up to '00:00:00'. From '00:00:00' to '02:00:00' should still be considered on the offset, but is not.

```python
cbh = pd.offsets.CustomBusinessHour(start='06:00', end='02:00')
for period in ('06:00:00', '12:00:00', '23:00:00', '00:00:00', '01:00:00', '02:00:00', '03:00:00', '04:00:00'):
    print(f'{period}: {cbh.onOffset(pd.Timestamp(period))}')
```

06:00:00: True
12:00:00: True
23:00:00: True
00:00:00: False
01:00:00: False
02:00:00: False
03:00:00: False
04:00:00: False

**Comment by TSPereira** [comment]
I think I finally nailed it. Brief description of what I do here. 

First I check if the passed start_date is within the working period or not. If it is not I roll_forward it. In here I added an additional argument so one can choose whether you want a correct time or not. This correction means if you want to add the hours that were over the end_time (e.g. if end is 17:00 and start_date time is 19:00, then the equivalent corrected date will be 10:00 of the next day. If the flag is set to False, then it will just be 8:00 as of usual roll_forward)

Get the sign of the operation, compute everything to seconds and if end_time < start_time, add 24 * 3600s to end_time (this will be relevant for posterior calculations)
Get shift len, nr of shifts to offset and remaining hours

**Now the tricky part (where I think something is failing in cbh)**
We still need to see if the remaining hours will make the day shift once more or not, and if so, how many hours we will need to shift from there. There are other ways of doing this other than what I used (maybe easier ways but I was getting crazy trying to solve this)

So, I get if the hours remaining (h_rem) to shift are more than the difference to next (or previous) day. If so add 1 to complete shifts to shift. 
Now the additional time (hours) to add need to be recomputed. If we need to shift one more day, the hours to shift are the remaining hours - shift length, else we keep remaining hours as they were before.

Finally, the last bit... If the start_date time is before the start time of the shift (and, since we corrected the time if we were out of working hours, this also means start_date time < end_time) then we need to be careful we account for the non-working period if needed. This can be attained by adding the difference between the day time and the shift length (non-working hours) if the remaining_hours are more than the difference between the end time and the start_date time

Sorry about the complicated explanation. It is not easy to wrap our heads around the "passing over midnight shifts" and all of its implications


```python
import pandas as pd


def custom_bhours_shift(start_date, offset_hours, weekmask='Mon Tue Wed Thu Fri', cal=None, hol=None, start='08:00',
                        end='17:00', correct_if_not_in_int=True):
    """
        Patch because CustomBusinessHour bahaves strangely
        https://github.com/pandas-dev/pandas/issues/29901

        Can be used with positive, 0, negative or partial hours

        units below seconds will be rounded to nearest second
    """

    # Check if it is in working interval and if not perform correction/rollforward
    start_date = _check_if_in_working_hours(start_date, start, end, correct=correct_if_not_in_int, hol=hol,
                                            weekmask=weekmask)

    # Convert start_date.time, start and end to seconds
    date_s = pd.Timedelta(start_date.time().isoformat()).total_seconds()
    start_s = pd.Timedelta(pd.Timestamp(start).time().isoformat()).total_seconds()
    end_s = pd.Timedelta(pd.Timestamp(end).time().isoformat()).total_seconds()
    d_s = 24 * 3600

    # If no offset return current date (corrected if outside of working hours)
    if offset_hours == 0:
        return start_date

    # Find whether to subtract or add
    sign = offset_hours / abs(offset_hours)
    offset_hours = abs(offset_hours) * 3600

    # Find shifts length
    if end_s < start_s:
        end_s += d_s
    shift_len = end_s - start_s

    # find nr of shifts and remaining hours
    comp_shifts = offset_hours // shift_len
    h_rem = offset_hours - (comp_shifts * shift_len)

    # Check hours to see if remanining hours will make day shift once more
    diff = h_rem - (date_s - start_s) >= 0 if sign < 0 else h_rem - (end_s - date_s) > 0
    comp_shifts += diff

    # Get the additional hours to shift
    add_time = sign * ((h_rem - shift_len) if diff else h_rem)
    if (date_s < start_s) & (add_time > ((end_s % d_s) - date_s)):
        add_time += d_s - shift_len

    cbd = pd.offsets.CustomBusinessDay(calendar=cal, holidays=hol, weekmask=weekmask)
    return start_date + sign * (comp_shifts * cbd) + pd.Timedelta(round(add_time), unit='s')


def _check_if_in_working_hours(start_date, start, end, correct=False, hol=None, weekmask='Mon Tue Wed Thu Fri'):
    _time = pd.Timestamp(start_date)
    cbh = pd.offsets.CustomBusinessHour(holidays=hol, start=start, end=end, weekmask=weekmask)

    if not cbh.onOffset(_time):
        if correct:
            date_s = pd.Timedelta(start_date.time().isoformat()).total_seconds()
            end_s = pd.Timedelta(pd.Timestamp(end).time().isoformat()).total_seconds()
            d_s = 24 * 3600

            addit = date_s - end_s + (0 if date_s > end_s else d_s)
            start_date = cbh.rollforward(start_date) + pd.Timedelta(round(addit), unit='s')
        else:
            start_date = cbh.rollforward(start_date)

    return start_date

```

**Comment by MarcoGorelli** [comment]
I could not reproduce this issue on master, looks like it's been fixed

**Comment by TSPereira** [comment]
I have updated the version of pandas to the latest 0.25.3.
With this version I can't reproduce the exact issue (so it seems the main issue is solved), but I noticed two behaviours that can be improved/changed.

First, when running this on the for example I gave in my first post, I noticed that when `i == 0` the result is not the original time. 

```python
cbh = pd.offsets.CustomBusinessHour(start='07:00', end='01:00')
time = pd.Timestamp('2019-03-06 13:00:00')
for i in range(3):
    print(i, ':', time - i * cbh)
```

**0 : 2019-03-07 07:00:00**
1 : 2019-03-06 12:00:00
2 : 2019-03-06 11:00:00

This happens whether subtracting or adding `0 * cbh`

Second, then running the for subtracting or adding, the results on the "edge" dates of the business schedule are not consistent. When subtracting, the behaviour is to show the endtime of the business schedule (instead of the starttime) whereas when adding the behaviour is the opposite

```python
cbh = pd.offsets.CustomBusinessHour(start='07:00', end='01:00')
time = pd.Timestamp('2019-03-06 13:00:00')
for i in range(24):
    print(i, ':', time - i * cbh)
```

0 : 2019-03-07 07:00:00
1 : 2019-03-06 12:00:00
2 : 2019-03-06 11:00:00
3 : 2019-03-06 10:00:00
4 : 2019-03-06 09:00:00
**5 : 2019-03-06 08:00:00
6 : 2019-03-06 01:00:00**
7 : 2019-03-06 00:00:00
8 : 2019-03-05 23:00:00
9 : 2019-03-05 22:00:00
10 : 2019-03-05 21:00:00
11 : 2019-03-05 20:00:00
12 : 2019-03-05 19:00:00
13 : 2019-03-05 18:00:00
14 : 2019-03-05 17:00:00
15 : 2019-03-05 16:00:00
16 : 2019-03-05 15:00:00
17 : 2019-03-05 14:00:00
18 : 2019-03-05 13:00:00
19 : 2019-03-05 12:00:00
20 : 2019-03-05 11:00:00
21 : 2019-03-05 10:00:00
22 : 2019-03-05 09:00:00
23 : 2019-03-05 08:00:00

```python
cbh = pd.offsets.CustomBusinessHour(start='07:00', end='01:00')
time = pd.Timestamp('2019-03-06 13:00:00')
for i in range(24):
    print(i, ':', time + i * cbh)
```

0 : 2019-03-07 07:00:00
1 : 2019-03-06 14:00:00
2 : 2019-03-06 15:00:00
3 : 2019-03-06 16:00:00
4 : 2019-03-06 17:00:00
5 : 2019-03-06 18:00:00
6 : 2019-03-06 19:00:00
7 : 2019-03-06 20:00:00
8 : 2019-03-06 21:00:00
9 : 2019-03-06 22:00:00
10 : 2019-03-06 23:00:00
**11 : 2019-03-07 00:00:00
12 : 2019-03-07 07:00:00**
13 : 2019-03-07 08:00:00
14 : 2019-03-07 09:00:00
15 : 2019-03-07 10:00:00
16 : 2019-03-07 11:00:00
17 : 2019-03-07 12:00:00
18 : 2019-03-07 13:00:00
19 : 2019-03-07 14:00:00
20 : 2019-03-07 15:00:00
21 : 2019-03-07 16:00:00
22 : 2019-03-07 17:00:00
23 : 2019-03-07 18:00:00

In my opinion this should have same behaviour, maybe controlled by an argument on cbh such as `use='endtime'`/`use='starttime'`.

**Comment by MarcoGorelli** [comment]
I think the problem's in `_prev_opening_time`:
```
import datetime
import pandas as pd

pd.offsets.BusinessHour(n=0)._prev_opening_time(datetime.datetime(2019, 3, 6, 13, 0))
# returns datetime.datetime(2019, 3, 5, 9, 0)
pd.offsets.BusinessHour(n=1)._prev_opening_time(datetime.datetime(2019, 3, 6, 13, 0))
# returns datetime.datetime(2019, 3, 5, 9, 0)
```
will dig further

**Comment by MarcoGorelli** [comment]
@jbrockmendel what would be the expected output from
```
import datetime as dt
import pandas as pd

dt.datetime(2019, 3, 6, 13, 0) + 0*pd.offsets.MonthEnd()
```
?

I'm tempted to say we should disallow multiplying an offset by zero, in the same way that we disallow
```
pd.offsets.LastWeekOfMonth(0)
```

**Comment by jbrockmendel** [comment]
> I'm tempted to say we should simply disallow multiplying an offset by zero

I'd be fine with that.

**Comment by MarcoGorelli** [comment]
@jbrockmendel thanks.

What about the other issue raised by @TSPereira , that is to say:
```
>>> dt.datetime(2019, 3, 6, 16, 0) + pd.offsets.BusinessHour()                                                                                                                                              
Timestamp('2019-03-07 09:00:00')

>>> dt.datetime(2019, 3, 7, 10, 0) - pd.offsets.BusinessHour()                                                                                                                                              
Timestamp('2019-03-06 17:00:00')
```
?

Is it correct that both should return `Timestamp('2019-03-07 09:00:00')`?

**Comment by MarcoGorelli** [comment]
We've deviated quite a bit from the original issue (which is solved), so I've opened up two separate issues for the new ones (#31184 and #31186).

Thanks @TSPereira for the reports!
