### ISSUE TITLE
typo in docs "Essential basic functionality"

### ISSUE THREAD

**Issue by Linus-MK** [pandas-dev/pandas#29934]
Sorry to bother with a mere typo, but the sentence has no closing parentheses.

> Numeric dtypes will propagate and can coexist in DataFrames. If a dtype is passed (either directly via the dtype keyword, a passed ndarray, or a passed Series, then it will be preserved in DataFrame operations. 
> https://pandas.pydata.org/pandas-docs/stable/getting_started/basics.html

Thank you in advance.

**Comment by alimcmaster1** [comment]
Would you like to submit a PR?

**Comment by tab1tha** [comment]
Greetings. I am a new contributor and I just made a pull request for this. I hope it helps.

**Comment by tab1tha** [comment]
take

**Comment by alimcmaster1** [comment]
Thanks @tab1tha if you link the issue in the PR it will close this issue when merged

**Comment by Linus-MK** [comment]
Thank you @tab1tha !
I'll try submitting PR next time.
