### ISSUE TITLE
Flask + multiprocessing: "NotImplementedError: Not supported for DataFrames!"

### ISSUE THREAD

**Issue by jjarthur** [pandas-dev/pandas#29946]
**df_manager.py**
```python
from multiprocessing.managers import BaseManager
import pandas as pd

def init_dataframe():
    return pd.DataFrame(data={'col1': [1, 2], 'col2': [3, 4]})

def get_df():
    return df

df = init_dataframe()
manager = BaseManager(('', 37844), b'password')
manager.register('get_df', get_df)
server = manager.get_server()
server.serve_forever()
```    
    
**data_handler.py**
```python
from multiprocessing.managers import BaseManager
import pandas as pd

def get_df():
    manager = BaseManager(('', 37844), b'password')
    manager.register('get_df')
    manager.connect()
    return manager.get_df()

def data():
    df = get_df()
    return df.to_dict()

if __name__ == '__main__':
    data()
```    

I'm trying to use multiprocessing to create a service that handles my pandas dataframe to give to Flask requests. Unfortunately, this throws an exception when attempting to call `manager.get_df()` in `data_handler.py`. This seems to be caused by DataFrames specifically, as returning `df.to_json()` instead of just `df` in `df_manager.py` seems to work fine.

```python-traceback
Traceback (most recent call last):
  File "src/data_handler.py", line 15, in <module>
    data()
  File "src/data_handler.py", line 11, in data
    df = get_df()
  File "src/data_handler.py", line 8, in get_df
    return manager.get_df()
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 724, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 609, in _create
    id, exposed = dispatch(conn, None, 'create', (typeid,)+args, kwds)
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 82, in dispatch
    raise convert_to_error(kind, result)
multiprocessing.managers.RemoteError: 
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 201, in handle_request
    result = func(c, *args, **kwds)
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 391, in create
    exposed = public_methods(obj)
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 122, in public_methods
    return [name for name in all_methods(obj) if name[0] != '_']
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 113, in all_methods
    func = getattr(obj, name)
  File "/home/admin/dev/pandas-multiprocessing/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 392, in _constructor_expanddim
    raise NotImplementedError("Not supported for DataFrames!")
NotImplementedError: Not supported for DataFrames!
---------------------------------------------------------------------------
```
If I'm missing something obvious, please let me know. I think what I'm trying to do should be possible, though.
I've posted this on [StackOverflow](https://stackoverflow.com/questions/59097332/flask-multiprocessing-remoteerror) as well if you'd like to get some rep.

**EDIT** Removed Flask dependency in example code.

**Comment by TomAugspurger** [comment]
We'll just keep the question on stackoverflow open. If this turns out to be a bug could you post an update here?

**Comment by TomAugspurger** [comment]
Though looking at your error message, the line

```
  File "/home/admin/dev/flask-pandas-project/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 392, in _constructor_expanddim
    raise NotImplementedError("Not supported for DataFrames!")
```

indicates that you're possibly calling a Series method on a DataFrame, or vice-versa?

**Comment by jjarthur** [comment]
I think it might be a bug, unless this doesn't work for a purpose. The above code is exactly what I'm using -- I don't believe I'm calling methods incorrectly. I have created a repo with this simple test case [here](https://github.com/jjarthur/pandas-multiprocessing).

**Comment by jjarthur** [comment]
@TomAugspurger Any chance of getting this one reopened?

**Comment by jreback** [comment]
@jjarthur you have to show a self contained copy pastable example that can be run

attaching a link to repo doesn’t a any value here

**Comment by jjarthur** [comment]
@jreback Why is that? It involves running separate processes, so separate files make sense here.

**Comment by TomAugspurger** [comment]
Can you remove the need for flask in your reproducer? If there is a bug here, we'll need something that we can convert to a unit test, and that can't depend on flask.

See http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by jjarthur** [comment]
Thanks for the link Tom. I have updated the [repo](https://github.com/jjarthur/pandas-multiprocessing) and the code snippets above to remove the Flask dependency.

**Comment by jjarthur** [comment]
Hi @TomAugspurger, I'm still interested in this if it could get reopened. Thanks!

**Comment by TomAugspurger** [comment]
Thanks for the ping and update. The tracback points to a method in multiprocessing.


```pytb
n3.7/multiprocessing/managers.py", line 122, in public_methods
    return [name for name in all_methods(obj) if name[0] != '_']
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/managers.py", line 113, in all_methods
    func = getattr(obj, name)
  File "/Users/taugspurger/sandbox/pandas/pandas/core/frame.py", line 399, in _constructor_expanddim
    raise NotImplementedError("Not supported for DataFrames!")
NotImplementedError: Not supported for DataFrames!
```

Which can be recreated with

```python
In [13]: from multiprocessing.managers import public_methods

In [14]: df = pd.DataFrame()

In [15]: public_methods(df)
```

It's not clear to me that BaseManager was defined with managing arbitrary objects in mind. The docs list a few types that are supported, and mentions `register` for custom types https://docs.python.org/3/library/multiprocessing.html#multiprocessing.managers.BaseManager.register. Could you try registering a custom method to proxy dataframes?

**Comment by jjarthur** [comment]
That did the trick! You were right, adding the `exposed` parameter is what was needed. Thanks for pointing that out.

The working solution for reference:
**df_manager.py**
```python
from multiprocessing.managers import BaseManager
import pandas as pd

def init_dataframe():
    return pd.DataFrame(data={'col1': [1, 2], 'col2': [3, 4]})

def get_df():
    return df

df = init_dataframe()
manager = BaseManager(('', 37844), b'password')
manager.register('get_df', callable=get_df, exposed='get_df') # Adding `exposed` parameter was the key to solving the issue
server = manager.get_server()
server.serve_forever()
```    
    
**data_handler.py**
```python
from multiprocessing.managers import BaseManager
import pandas as pd

def get_df():
    manager = BaseManager(('', 37844), b'password')
    manager.register('get_df')
    manager.connect()
    return manager.get_df()

def data():
    df = get_df()
    return df

if __name__ == '__main__':
    print(data())
```
