### ISSUE TITLE
shifted column names by reading bigger csv-files

### ISSUE THREAD

**Issue by Intheelement** [pandas-dev/pandas#29965]
Using pandas version of newest anaconda windows setup-installer:
pd.__version__
Out[11]: '0.25.1'

While importing larger csv-files there occures a shift in column names. 
Simple version works:
```
df = pd.read_csv(relpath + "\data.csv", sep=';', header=0,  
                  skiprows=[1], parse_dates=False, keep_date_col=True)

df.head()
Out[4]: 
          Timestamp  PMaxEVU  U_L1_L2  Frequency
0  01.12.2019 00:01    100.0   20.688     49.965
1  01.12.2019 00:02    100.0   20.704     49.947
2  01.12.2019 00:03    100.0   20.700     49.971
3  01.12.2019 00:04    100.0   20.701     49.988
4  01.12.2019 00:05    100.0   20.701     49.986
```
while normal mode leads to shift (see Timestamp has PMaxEVU-values)

```
df1 = pd.read_csv(relpath + "\ALL_DATA_01.csv", sep=';', header=0,  
                  skiprows=[1], parse_dates=False, keep_date_col=True)
df1 = df1.set_index('Timestamp')

df1.head()
Out[9]: 
           PMaxEVU  PMaxEVU_Active  CosPhi_OP  ...   ER  ER_Cap  Unnamed: 59
Timestamp                                      ...                          
100.0          0.0           -0.01     -100.0  ...  0.0     0.0          NaN
100.0          0.0           -0.01     -100.0  ...  0.0     0.0          NaN
100.0          0.0           -0.01     -100.0  ...  0.0     0.0          NaN
100.0          0.0           -0.01     -100.0  ...  0.0     0.0          NaN
100.0          0.0           -0.01     -100.0  ...  0.0     0.0          NaN

[5 rows x 59 columns]
```
this occures even with direct importing with parse_dates=True, 
```
df1 = pd.read_csv( relpath + "\ALL_DATA_01.csv", sep=';', header=0, 
                  index_col=0, skiprows=[1], parse_dates=True, 
                  keep_date_col=False)
```
Useing string name leads to KeyError - this may be an error on my side
```
df1 = pd.read_csv( relpath + "\ALL_DATA_01.csv", sep=';', header=0, 
                  index_col='Timestamp', skiprows=[1], parse_dates=True, 
                  keep_date_col=False)
```
```

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 2100, in read
    values = data.pop(self.index_col[i])

KeyError: 'Timestamp'
```

**Comment by pfyffe** [comment]
I'm experiencing this issue as well. Did you find a work-around?

**Comment by TomAugspurger** [comment]
Can anyone provide a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by pfyffe** [comment]
My issue seems to be due to a difference between the csv file format produced by a php script that causes the column heading to be right-shifted one column. If I open the file in Excel, then save it, the column rendering is correct. The recreate files are Network_1x1.csv and Network_1x1_excel.csv respectively. Maybe this is a different issue to that of Intheelement?

![image](https://user-images.githubusercontent.com/31397086/73579425-658c7e00-4450-11ea-9704-79eac49410b1.png)


[device-version.zip](https://github.com/pandas-dev/pandas/files/4141699/device-version.zip)

**Comment by kebwi** [comment]
I'm also seeing this behavior on large CSV files. Apple Numbers reads the file correctly. Pandas leaves the first column blank and shifts the header ow over by one column all the way across.

**Comment by mroeschke** [comment]
Thanks for the report, but it appears that we would need a minimal example to proceed with this issue (ideally one where a large `DataFrame` is generated`, saved with `to_csv`, and reread with `pd.read_csv`). This would ensure we can have a suitable regression test if this is truly a bug.

Going to close in need of a more minimal example, but happy to reopen once we have a minimal example.
