### ISSUE TITLE
DOC: Remove :okwarning: from scale guide when used dask version is not raising FutureWarning anymore

### ISSUE THREAD

**Issue by SaturnFromTitan** [pandas-dev/pandas#29960]
can you also create an issue on the pandas side so we know what we need to update once dask is at a certain version (you can just point to this line here)

_Originally posted by @jreback in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM1MjM4MzI0NA==/comments/review_comment_

**Note:** This will be on hold for quite a while (first merging my PR, then waiting until dask has silenced the warning on their side, then bumping our dask dependency)

**Comment by seanjedi** [comment]
@SaturnFromTitan I am a bit unsure, but is this what you meant for this fix?
https://github.com/pandas-dev/pandas/pull/50004
