### ISSUE TITLE
REF: Deduplicate array, infer_dtype, and maybe_convert_objects

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#29973]
There's some duplicate / slightly diverging functionality between `pd.array`, `infer_dtype` and `convert_objects`. Both `pd.array` and `convert_objects` are roughly "convert this list-like thing to this better array". See the conversation in  https://github.com/pandas-dev/pandas/pull/29799#discussion_r352255141 for more.

Hopefully this can be deduplicated.

cc @jreback.

Followup to https://github.com/pandas-dev/pandas/pull/29799

**Comment by jbrockmendel** [comment]
xref #27460
