### ISSUE TITLE
pandas.core.dtypes.cast.find_common_type upcasts CategoricalDtype list to object

### ISSUE THREAD

**Issue by devin-petersohn** [pandas-dev/pandas#29980]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd
from pandas.core.dtypes.cast import find_common_type

types = [
    pd.CategoricalDtype([1,2,3], ordered=False), 
    pd.CategoricalDtype([1,4,5], , ordered=False),
]
find_common_types(types)
```
#### Problem description

The `find_common_types` is upcasting a list of `CategoricalDtype` to `object`. Ideally, it would create a `CategoricalDtype` that included the union of all of the values in the `categories` field of the `types` parameter.

The fix for this is relatively easy, I will propose a fix in a comment reply to this issue.

#### Expected Output

```python
CategoricalDtype(categories=[1, 2, 3, 4, 5], ordered=False)
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.8.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 16.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.3
numpy            : 1.15.0
pytz             : 2018.5
dateutil         : 2.7.3
pip              : 19.2.3
setuptools       : 41.0.1
Cython           : 0.29.10
pytest           : 3.9.3
hypothesis       : None
sphinx           : 1.8.1
blosc            : None
feather          : 0.4.0
xlsxwriter       : None
lxml.etree       : 4.2.5
html5lib         : None
pymysql          : None
psycopg2         : 2.8.3 (dt dec pq3 ext lo64)
jinja2           : 2.10
IPython          : 7.0.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.2.5
matplotlib       : 3.0.0
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.5.8
pandas_gbq       : 0.6.1
pyarrow          : 0.14.0.RAY
pytables         : None
s3fs             : 0.2.0
scipy            : 1.2.0
sqlalchemy       : 1.2.17
tables           : 3.4.4
xarray           : 0.11.3
xlrd             : 1.1.0
xlwt             : None
xlsxwriter       : None

</details>

**Comment by devin-petersohn** [comment]
This was encountered in modin-project/modin#874 and is fixed in modin-project/modin#889.

Relevant fix code here: https://github.com/modin-project/modin/pull/889/files#diff-13bf1e075a6c1b195f6eaf2c8544c255R29-R36

If the maintainers agree this functionality can be added, I will happily open a PR.

**Comment by jreback** [comment]
we have union_categoricals for this purpose

find_common_dtype is not exposed for external use - that said i suppose it could be smarter

**Comment by devin-petersohn** [comment]
Thanks @jreback, `union_categoricals` does not union `CategoricalDtype` objects, so a workaround like the following is needed if we must use that:

```python
union_categoricals(
    [pd.Categorical([], dtype=t, ordered=t.ordered) for t in types],
    sort_categories=all(t.ordered for t in types),
).dtype
```

This would put the constraint on the `types` that if `ordered=True`, they must all contain identical `categories` fields.

**Comment by jorisvandenbossche** [comment]
I think the `find_common_type` behaviour is actually correct. Or at least it is consistent with how we treat such two different categorical dtypes when they are combined (the discussion could be about that, though).

Eg, for a `concat` or `append` with data of such two categorical dtypes with different categories, it will not result in a categorical dtype in pandas.

**Comment by devin-petersohn** [comment]
If it is consistent, it may be best to not touch it then.

For my purposes, I can work around it. I am primarily using it to combine the `dtypes` from all partitions (which may not all contain identical `categories` fields), which is probably a separate use case than the `find_common_type` functionality was intended for.

If we were to change the way pandas handles `concat` or `append` on categoricals with different `dtypes`, there's a lot of ambiguity with how to handle different conditions (e.g. `ordered=True`) in pandas. That is probably why it's handled the way it is by upcasting to `object`.

**Comment by devin-petersohn** [comment]
Closing as no action to be taken.
