### ISSUE TITLE
 ".fillna(method='bfill', limit=7) hangs with "specifying a limit for fillna has not been implemented yet"

### ISSUE THREAD

**Issue by hkn0509** [pandas-dev/pandas#29987]
Hi! Please help me with this problem. Thank you in advance for your help.

Source code and data are attached.

Executing this statement: 
	  **labeled_features = labeled_features.fillna(method='bfill', limit=7)  ## where "labeled_features" is a dataframe**
it hangs with this error:	  
          **"NotImplementedError: specifying a limit for fillna has not been implemented yet"**

The code belongs to "Modeling Guide for Predictive Maintenance Python 3 Notebook",  downloaded from
	"https://notebooks.azure.com/Microsoft/projects/PredictiveMaintenance".  

Operating System: Windows 10
Google Chrome

I tried with Anaconda3-5.2.0-Windows-x86_64 (Python 3.6), and afterwards I tried with Python 3.8, Pandas 0.25.3, and iPython. 
Actually with Anaconda3-2019.10-Windows-x86_64, Jupyter 6.0.1, Pandas 0.25.1, Python 3.7.4, Numpy 1.16.5

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-27-259154593492> in <module>
[PredictiveMaintenance_SourceAndData.zip](https://github.com/pandas-dev/pandas/files/3914325/PredictiveMaintenance_SourceAndData.zip)

      1 labeled_features = final_feat.merge(failures, on=['datetime', 'machineID'], how='left')
----> 2 labeled_features = labeled_features.fillna(method='bfill', limit=7) # fill backward up to 24h
      3 labeled_features = labeled_features.fillna('none')
      4 labeled_features.head()

~\Anaconda3\lib\site-packages\pandas\core\frame.py in fillna(self, value, method, axis, inplace, limit, downcast, **kwargs)
   4242             limit=limit,
   4243             downcast=downcast,
-> 4244             **kwargs
   4245         )
   4246 

~\Anaconda3\lib\site-packages\pandas\core\generic.py in fillna(self, value, method, axis, inplace, limit, downcast)
   6235                 inplace=inplace,
   6236                 coerce=True,
-> 6237                 downcast=downcast,
   6238             )
   6239         else:

~\Anaconda3\lib\site-packages\pandas\core\internals\managers.py in interpolate(self, **kwargs)
    567 
    568     def interpolate(self, **kwargs):
--> 569         return self.apply("interpolate", **kwargs)
    570 
    571     def shift(self, **kwargs):

~\Anaconda3\lib\site-packages\pandas\core\internals\managers.py in apply(self, f, axes, filter, do_integrity_check, consolidate, **kwargs)
    436                     kwargs[k] = obj.reindex(b_items, axis=axis, copy=align_copy)
    437 
--> 438             applied = getattr(b, f)(**kwargs)
    439             result_blocks = _extend_blocks(applied, result_blocks)
    440 

~\Anaconda3\lib\site-packages\pandas\core\internals\blocks.py in interpolate(self, method, axis, inplace, limit, fill_value, **kwargs)
   1947         values = self.values if inplace else self.values.copy()
   1948         return self.make_block_same_class(
-> 1949             values=values.fillna(value=fill_value, method=method, limit=limit),
   1950             placement=self.mgr_locs,
   1951         )

~\Anaconda3\lib\site-packages\pandas\util\_decorators.py in wrapper(*args, **kwargs)
    206                 else:
    207                     kwargs[new_arg_name] = new_arg_value
--> 208             return func(*args, **kwargs)
    209 
    210         return wrapper

~\Anaconda3\lib\site-packages\pandas\core\arrays\categorical.py in fillna(self, value, method, limit)
   1842         if limit is not None:
   1843             raise NotImplementedError(
-> 1844                 "specifying a limit for fillna has not " "been implemented yet"
   1845             )
   1846 

NotImplementedError: specifying a limit for fillna has not been implemented yet

[PredictiveMaintenance_SourceAndData.zip](https://github.com/pandas-dev/pandas/files/3914330/PredictiveMaintenance_SourceAndData.zip)

**Comment by gfyoung** [comment]
cc @jreback

**Comment by hkn0509** [comment]
Hi @gfyoung! As I am new to GitHub, I don't understand to what "missing-data" you refer, as I attached a zip file with all the code and input data. I searched for the specific meaning of the label "missing-data" and I didn't found it. Thank you in advance for your answer.

**Comment by gfyoung** [comment]
@hkn0509: `missing-data` is a topic of issues related to missing values in a `DataFrame` or `Series`.  It does not have anything to deal with the fact that your issue report is missing something.  If that was the case, we would add the label `Needs Info`.

**Comment by hkn0509** [comment]
@Thank you @gfyoung for your clear and fast answer.

**Comment by mroeschke** [comment]
It would also help us and others diagnose your issue if you could provide a minimal, reproducible example: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by hkn0509** [comment]
Dear @mroeschke: thank you for your interest. In my question I've included the complete code and data.

**Comment by hkn0509** [comment]
Thank's to all, but I've found the cause of the failure: The column "failure" of the input file "failures" is categorical, and there is where "fillna(method=bfill, limit=7)" fails, due to the restriction of "limit" that can't handle categorical data. 
So I close this question.

**Comment by hkn0509** [comment]
Dear Matthew:

Thank you for your clever advices. I will use them.

Fortunately, yesterday I found the cause of the problem, so I’ve closed the issue.

Yours,

Juan Carlos Neufeld

De: Matthew Roeschke<mailto:notifications@github.com>
Enviado: martes, 3 de diciembre de 2019 16:37
Para: pandas-dev/pandas<mailto:pandas@noreply.github.com>
CC: hkn0509<mailto:juan_neufeld@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [pandas-dev/pandas] ".fillna(method='bfill', limit=7) hangs with "specifying a limit for fillna has not been implemented yet" (#29987)


It would also help us and others diagnose your issue if you could provide a minimal, reproducible example: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by sansea006** [comment]
to be clear, this will fix it

labeled_features['model'] = labeled_features['model'].astype('object')
labeled_features['failure'] = labeled_features['failure'].astype('object')
labeled_features = labeled_features.fillna(method='bfill', axis=0, limit=7) # fill backward up to 24h
