### ISSUE TITLE
Pandas is not able to append dataframe to an existing excel sheet.Although openpyxl can be used for it but openpyxl is also destroying pivot table and all other realted information.So we do not have another way available except openpyxl

### ISSUE THREAD

**Issue by vishavgupta97** [pandas-dev/pandas#29990]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

```
#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by gfyoung** [comment]
Lack of example notwithstanding, have a look at this link here:

https://stackoverflow.com/questions/47737220/append-dataframe-to-excel-with-pandas/47738103

If you could post example code, that would be great so that everyone can reference this.

**Comment by vishavgupta97** [comment]
Hello

Greetings of the day

Although this can be achieved through openpyxl.This is working fine but it
is also destroying pivot table and all the related information.Hence this
code is useless.Because I am achieving one thing but on the other hand
destroying another thing.
Is there any other way available so that my pivot table will not destroy

Thanks & Regards
Vishav Gupta

**Comment by vishavgupta97** [comment]
By this way pivot table and all the related information is getting destroyed.So using openpyxl is not an efficient way to achieve it. How it can achieve by xlwings or win32com because by using helper function of openpyxl ,we are unable to achieve it

**Comment by gfyoung** [comment]
@vishavgupta97 : Please share example code.  It is otherwise difficult to provide guidance.

**Comment by vishavgupta97** [comment]
https://stackoverflow.com/questions/59151055/how-to-write-dataframe-below-an-existing-excel-sheet-without-losing-value-of-piv

**Comment by vishavgupta97** [comment]
https://stackoverflow.com/questions/59134136/pivot-table-get-destroyed-while-appending-dataframe-below-excel-using-openpyxl

**Comment by vishavgupta97** [comment]
Check here

**Comment by gfyoung** [comment]
@vishavgupta97 : Can you share the input data as well?  We are looking for a complete example of code (and data) that we can run exactly that reproduces the issue you're describing.

**Comment by vishavgupta97** [comment]
I am getting this warning message C:\Users\abcd\PycharmProjects\Abacus_Report\venv\lib\site-packages\openpyxl\worksheet\_reader.py:292: UserWarning: Slicer List extension is not supported and will be removed
  warn(msg)

**Comment by vishavgupta97** [comment]
https://stackoverflow.com/questions/59134136/pivot-table-get-destroyed-while-appending-dataframe-below-excel-using-openpyxl

https://stackoverflow.com/questions/59151055/how-to-write-dataframe-below-an-existing-excel-sheet-without-losing-value-of-piv

Here are above two links for the description of problem. I am really sorry I can't share the data because it is very crucial data for our business organisation.However I will try to post an example of data

**Comment by vishavgupta97** [comment]
Please help to find solution of this particular problem

**Comment by gfyoung** [comment]
Please try to post example data so that we can help you

**Comment by mroeschke** [comment]
Happy to reopen when we get a reproducible example
