### ISSUE TITLE
Default dtype of empty Series: DeprecationWarning -> FutureWarning in 1.1

### ISSUE THREAD

**Issue by SaturnFromTitan** [pandas-dev/pandas#30017]
> Given that this can have some impact on libraries (see how often we used it ourselves in pandas), meaning that their users will start to see warnings they cannot solve, should be start with making this a DeprecationWarning instead of FutureWarning?
> 
> Given that this won't be actually changed in 1.0 (but only start raising a warning), we have some time to change it to a FutureWarning in a later release.

I guess we could have ``DeprecationWarning`` for a single version, then change to ``FutureWarning`` to give libraries a chance to change. I feel these are ignored as well by the downstream as they don't see them by-default (we in fact tend to ignore numpy ones :->)

@SaturnFromTitan let's change this and open an issue for the 1.1 milestone (let me create it) to change to a FutureWarning

_Originally posted by @jreback in https://github.com/pandas-dev/pandas/pull/29405#issuecomment-560383499_

**Comment by SaturnFromTitan** [comment]
@jreback Do you think I can work on this yet? 3 minor versions passed, which should be good enough to make this a FutureWarning now.

**Comment by TomAugspurger** [comment]
Closed by #29405.

**Comment by lithomas1** [comment]
@TomAugspurger Did this actually get changed? On my branch off master this still raises DeprecationWarning.

**Comment by TomAugspurger** [comment]
Not sure.
