### ISSUE TITLE
BUG: set/dict operations fail when hash collisions with pd.NA occur

### ISSUE THREAD

**Issue by jschendel** [pandas-dev/pandas#30013]
```python-traceback
In [1]: import pandas as pd; pd.__version__
Out[1]: '0.26.0.dev0+1155.ged20822a5'

In [2]: {pd.NA, hash(pd.NA)}
---------------------------------------------------------------------------
TypeError: boolean value of NA is ambiguous

In [3]: {pd.NA} | {hash(pd.NA)}
---------------------------------------------------------------------------
TypeError: boolean value of NA is ambiguous

In [4]: {pd.NA: 'foo', hash(pd.NA): 'bar'}
---------------------------------------------------------------------------
TypeError: boolean value of NA is ambiguous

In [5]: d = {pd.NA: 'foo'} 
   ...: d[hash(pd.NA)]
---------------------------------------------------------------------------
TypeError: boolean value of NA is ambiguous
```

The above behavior is due to Python using equality as a fallback when hash collisions occur and our defined behavior of `bool(pd.NA)` raising.  This might be something we have to live with if we want to maintain the current behavior of `bool(pd.NA)`, or at least an immediate workaround doesn't come to mind.

The examples above are admittedly a bit contrived, so I think it'd be fairly rare to see this occur in practice.  My main concern is that this could result in some confusing behavior when `pd.NA` is included in containers, e.g. `set(IntegerArray)` could fail in rare circumstances.

cc @jorisvandenbossche @TomAugspurger

**Comment by TomAugspurger** [comment]
Hmmm, that is unfortunate. I also can't think of a workaround right now.

**Comment by jorisvandenbossche** [comment]
It doesn't sound like there is a workaround possible .. Hmm, I think I would classify this under "unfortunate side-effect", but we can certainly discuss the bool value to be False as well.

**Comment by jschendel** [comment]
We could maybe adjust the `__hash__` definition to work around this, or at least minimize the potential issue.

It looks like the hashes for integers are no longer idempotent starting at `2**61 - 1`:
```python
In [1]: 2**61 - 2, hash(2**61 - 2)
Out[1]: (2305843009213693950, 2305843009213693950)

In [2]: 2**61 - 1, hash(2**61 - 1)
Out[2]: (2305843009213693951, 0)

In [3]: 2**61, hash(2**61)
Out[3]: (2305843009213693952, 1)
```

So if we modify `__hash__` to be at least `2**61 - 1` we should have a workaround for the integer case at least.

For example, I made the following change:
```diff
diff --git a/pandas/_libs/missing.pyx b/pandas/_libs/missing.pyx
index 9bf955ad3..23dabc58f 100644
--- a/pandas/_libs/missing.pyx
+++ b/pandas/_libs/missing.pyx
@@ -344,7 +344,7 @@ class NAType(C_NAType):
         raise TypeError("boolean value of NA is ambiguous")
 
     def __hash__(self):
-        return id(self)
+        return 2 ** 61 - 1
 
     # Binary arithmetic and comparison ops -> propagate
```

Which fixes the examples issues I originally described:
```python
In [2]: {pd.NA, hash(pd.NA)}
Out[2]: {2305843009213693951, NA}

In [3]: {pd.NA: 'foo', hash(pd.NA): 'foo'}
Out[3]: {NA: 'foo', 2305843009213693951: 'foo'}
```

The same issue will still occur for objects that have a hash collisions with `pd.NA`, so it's not like this fixes every possible case, but the change above look like it'll get us around the issue with integers at least.

**Comment by jschendel** [comment]
It looks like the idempotent behavior for integer hashes described above resets at `2**31 - 1` for 32-bit platforms instead of at `2**61 - 1` for 64-bit.
