### ISSUE TITLE
CI: numpydev is failing

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#30043]
```
==================================== ERRORS ====================================
_____ ERROR at setup of TestCasting.test_astype_object_series[data-object] _____
[gw1] linux -- Python 3.7.5 /home/vsts/miniconda3/envs/pandas-dev/bin/python

allow_in_pandas = None, dtype = PandasDtype('object')

    @pytest.fixture
    def data_missing(allow_in_pandas, dtype):
        # For NumPy <1.16, np.array([np.nan, (1,)]) raises
        # ValueError: setting an array element with a sequence.
        if dtype.numpy_dtype == "object":
            if _np_version_under1p16:
                raise pytest.skip("Skipping for NumPy <1.16")
>           return PandasArray(np.array([np.nan, (1,)]))
E           DeprecationWarning: Creating an ndarray with automatic object dtype is deprecated, use dtype=object if you intended it, otherwise specify an exact dtype
```

from https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=22360.

So numpy has deprecated object-dtype inference. I'm not sure if something like `np.array([object(), object()])` warns now, or if it's just when the elements are sequences of difference lengths.

Anyway, this is a nice change, but will be a bit of work to get fixed.

**Comment by jreback** [comment]
@jbrockmendel ideally could just xfail the test for now to get CI green (i saw your patch for some of these); i mean the rest

**Comment by TomAugspurger** [comment]
In theory, we can just pass `dtype=object` everywhere. Will try that quick.

**Comment by TomAugspurger** [comment]
Ahh, nevermind, this is going to be somewhat tricky to get right... I think we'll need to disable the numpydev build for now.

**Comment by jreback** [comment]
@jbrockmendel @TomAugspurger looks closeable yes?

**Comment by jbrockmendel** [comment]
Yes, numpy has reverted the warning and in this particular case weve updated our usage to avoid the warning.  closing.
