### ISSUE TITLE
Possible bug in indexing

### ISSUE THREAD

**Issue by varunpatro** [pandas-dev/pandas#30042]
#### Code Sample

```python

import pandas
x = pandas.Series(range(4))
x[::2][1]

```

This raises the following error:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-104-1e3011e95c0d> in <module>
      1 import pandas
      2 x = pandas.Series(range(4))
----> 3 x[::2][1]

/j/office/app/research-python/conda/envs/2019.10/lib/python3.7/site-packages/pandas/core/series.py in __getitem__(self, key)
   1069         key = com.apply_if_callable(key, self)
   1070         try:
-> 1071             result = self.index.get_value(self, key)
   1072 
   1073             if not is_scalar(result):

/j/office/app/research-python/conda/envs/2019.10/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_value(self, series, key)
   4728         k = self._convert_scalar_indexer(k, kind="getitem")
   4729         try:
-> 4730             return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))
   4731         except KeyError as e1:
   4732             if len(self) > 0 and (self.holds_integer() or self.is_boolean()):

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

KeyError: 1
```
#### Problem description

The expected output should be 2 in this case. I think this has to do with the way index values are calculated. But I'm not sure.

For example:

``` python
r = pandas.RangeIndex(0, 4, 2)
r.get_value(x, 1)
``` 
raises the following error:

```
KeyError                                  Traceback (most recent call last)
<ipython-input-108-1f3c6d93e1c7> in <module>
      1 r = pandas.RangeIndex(0, 4, 2)
----> 2 r.get_value(x, 1)

/j/office/app/research-python/conda/envs/2019.10/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_value(self, series, key)
   4728         k = self._convert_scalar_indexer(k, kind="getitem")
   4729         try:
-> 4730             return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))
   4731         except KeyError as e1:
   4732             if len(self) > 0 and (self.holds_integer() or self.is_boolean()):

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

KeyError: 1
```

This should also be returning 2 instead of raising an error.

I understand that the preferred way of indexing in pandas is using `.iloc` but default indexing behavior using `x[...]` is necessary when I want to integrate pandas with some C code. The Pandas Series seems to follow the [PySequence](https://docs.python.org/3.8/c-api/sequence.html) protocol except in cases of a Series view that is obtained by slicing the series with a step > 1. For example by doing `x[::2]`. Because this view no longer follows the PySequence protocol, accessing members of this view using [PySequence_GetItem](https://docs.python.org/3/c-api/sequence.html#c.PySequence_GetItem) which is a way to do `x[i]` results in segfaults. Do you have any suggestions here?

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-1062.4.3.el7.jane1.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.utf8
LOCALE           : en_US.UTF-8

pandas           : 0.25.3
numpy            : 1.17.3
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 41.6.0.post20191101
Cython           : 0.29.14
pytest           : 5.2.2
hypothesis       : None
sphinx           : 2.2.1
blosc            : None
feather          : 0.4.0
xlsxwriter       : 1.2.5
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.8.4 (dt dec pq3 ext lo64)
jinja2           : 2.10.3
IPython          : 7.9.0
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.2
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 3.0.0
pandas_gbq       : 0.11.0
pyarrow          : 0.15.1
pytables         : None
s3fs             : None
scipy            : 1.3.2
sqlalchemy       : 1.3.10
tables           : 3.6.1
xarray           : 0.14.0
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.5
</details>

**Comment by TomAugspurger** [comment]
We interpret the `1` as a label for integer indexes, rather than a position. As you say, `.iloc` is an option if you need positional indexing.

If you're trying to integrate with C code, you might just convert the Series to an ndarray first. That may be easier to handle, if you aren't using the index anyway.
