### ISSUE TITLE
NO TABLES FOUND IN domain searchers 

### ISSUE THREAD

**Issue by YashKarthik** [pandas-dev/pandas#30046]
`import` `webbrowser`
`import` `urllib3`
`import` `urllib.parse`
`import` `lxml.html` `as` `lh`
`from` `bs4` `import` `BeautifulSoup`
`import` `requests`
`import` `pandas` `as pd`
`with requests.Session() as c:`
    `url=("https://viewdns.info/reversewhois/?")`
  `  reg_name = input("enter registrant name")`
    `data = urllib.parse.urlencode({'q': reg_name})`
  `  url_n = url + data`
    `html = requests.get(url_n).content`
    `df_list = pd.read_html(html)`
   ` df = df_list[1]`
 `   print(df)`

Been searching around for a while now, 
This same program worked with other websites with tables, but hasn’t worked with any of the websites which provide domain search services etc. eg.-https://viewdns.info/reversewhois/?q=

thanks

**Comment by TomAugspurger** [comment]
@YashKarthik do you think this is a bug in pandas? If so, can you make a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports and fill out the issue template?

**Comment by YashKarthik** [comment]
I'm pretty sure that it's not a bug in pandas cuz it worked with other websites

**Comment by YashKarthik** [comment]
It's like pandas is not able to scan the page-"https://viewdns.info/reversewhois/?q=wikipedia"

**Comment by YashKarthik** [comment]
I figured this out, it was cuz of my location 
.
