### ISSUE TITLE
DOC:  Documentation for MultiIndex.get_locs() is missing in v0.25 docs

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#30056]
#### Problem description

The documentation for `MultiIndex.get_locs()` is missing in v0.25 docs (at least since v0.23?)

It is referred to here: 
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.MultiIndex.get_loc.html

And it existed in v0.22:
https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.MultiIndex.get_locs.html

Mentioned in #29967

**Comment by TomAugspurger** [comment]
I think adding get_locs to the list of methods in https://github.com/pandas-dev/pandas/blob/04c0870f3abb72e4d68e5e712e5eb4445eff4161/pandas/core/indexes/multi.py#L183 may fix this.
