### ISSUE TITLE
Add optional column separator character to DataFrame.to_string()

### ISSUE THREAD

**Issue by dov** [pandas-dev/pandas#30105]
I'd like more flexibility in the stringification of a pandas dataframe. Consider a trivial dataframe:

```python
import pandas as pd

df = pd.DataFrame([[1.2454235445,2],
                   [3,4.452455]],
                   columns = ['A','B'])
print(df.to_string())

```
This outputs:
````
          A         B
0  1.245424  2.000000
1  3.000000  4.452455
````

My desired output is:

```
|   |       A  |       B  |
+---+----------+----------+
| 0 | 1.245424 | 2.000000 |
| 1 | 3.000000 | 4.452455 |
```

I suggest adding the following options to `to_string()` to support the above output:

- `output_column_separator` -- The vertical bar in the above example
- `output_row_separator` -- The hyphen in the above example
- `output_cross_separator` -- The plus sign in the above example

**Comment by jreback** [comment]
why?

**Comment by dov** [comment]
Because I often find myself copying a pandas dataframe output into an org-mode document, and there is no simple way of 1) using the float formatting preference of `DataFrame.to_string()` and 2) inserting the table delimiters. But more generally, I think that the stringified DataFrame is a matter of preference, just as a html'ified dataframe is styled according to preference.

**Comment by jreback** [comment]
see discussion and links here: https://github.com/pandas-dev/pandas/issues/11052
