### ISSUE TITLE
setting precision for display sometimes shows wrong output

### ISSUE THREAD

**Issue by k1monfared** [pandas-dev/pandas#30122]
#### Code Sample, a copy-pastable example if possible

```python
pd.set_option("display.precision", 0)
pd.DataFrame([9.5444])

```
#### Problem description

The output is expected to be 10, but it shows 1.

#### Expected Output
    	0
    0	10
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.3
numpy            : 1.16.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.1.1
setuptools       : 41.0.1
Cython           : 0.29.12
pytest           : 5.0.1
hypothesis       : None
sphinx           : 2.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.3.4
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.6.1
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.4
matplotlib       : 3.1.0
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.2.1
sqlalchemy       : 1.3.5
tables           : 3.5.2
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.8
</details>

**Comment by scari** [comment]
will take a look at it at SprintSeoul year-end sprint.

**Comment by mroeschke** [comment]
This looks fixed on master. Could use a test

```
In [1]: pd.set_option("display.precision", 0)
   ...: pd.DataFrame([9.5444])
Out[1]:
    0
0  10
```

**Comment by dhruvsamdani** [comment]
take
