### ISSUE TITLE
SettingWithCopyWarning raised unnecessarily with .fillna() on df with multiple indices 

### ISSUE THREAD

**Issue by rebeccachinn** [pandas-dev/pandas#30123]
I'm creating a table with two levels of indices. 

```python
import numpy as np
import pandas as pd
column_a = ('group_name', "column_a")
column_b = ('group_name', "column_b")

df = pd.DataFrame({
    column_a: [1, np.NaN, 3, np.NaN],
    column_b: [1, 2, np.NaN, 4],
})

	group_name
column_a	column_b
0	1.0	1.0
1	NaN	2.0
2	3.0	NaN
3	NaN	4.0

```

When I try to fill in one column's na values with values from another column, like this, a SettingWithCopyWarning is triggered. 
```python
df2 = df['group_name']

df2['column_a'].fillna(df2['column_b'], inplace=True)

```
```
SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
```
Though the warning is triggered, the original dataframe is still being updated. 

```python
	group_name
column_a	column_b
0	1.0	1.0
1	2.0	2.0
2	3.0	NaN
3	4.0	4.0
```

If there was indeed a value being set on a copy, then the original data should not be updated. Because the data is being updated, it appears that the warning is falsely raised. 

Note that the following implementation, which does the same thing on a dataframe with a single index, does not raise the warning. 

```python

df = pd.DataFrame({
    'column_a':[1,np.NaN,3,np.NaN,5],
    'column_b':[1,2,3,4,5]
})


df['column_a'].fillna(df['column_b'], inplace=True)


column_a	column_b
0	1.0	1
1	2.0	2
2	3.0	3
3	4.0	4
4	5.0	5
```

This implementation of .fillna() on a df with multiple indices does not raise the warning. Is this the intended implementation?
```python
df[('group_name','column_a')].fillna(df2['column_b'], inplace=True)
```

**Comment by jreback** [comment]
pls re-read the documentation, by-definition you are chain indexing here when you specify ``inplace=True``.

idiomatically you should do this

``df['column_a')] = df['column_a)].fillna(df2['column_b'])``

**Comment by Laurent-Tupin** [comment]
Can someone answer this very relevant question,
Why someone can close the subject so abruptly by putting a code that countains typo + is False.

`df['Price2'] =   df['Column1'].fillna( df['Price'] )
`
got me the same WARNING
