### ISSUE TITLE
NoneType error during json_normalize due to schema change

### ISSUE THREAD

**Issue by bolkedebruin** [pandas-dev/pandas#30148]
#### Code sample
```
meta_df = json_normalize(json_struct, record_path='my_data')
```
#### Problem description

Normalizing a json with an absent field at a certain point in time due to a schema change(s) results in a NoneType error

#### Expected Output

Continue normalization

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 37b4b33075ed66721147027028d41b8faacd68a2
python           : 3.7.5.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.0.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 0.26.0.dev0+1247.g37b4b3307.dirty
numpy            : 1.17.4
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by jbrockmendel** [comment]
Can you post of a small example json_struct that reproduces the problem

**Comment by bolkedebruin** [comment]
Imagine if I have 3 records:

```
[{'state': 'Florida', 'info': [1, 2,]}]
[{'state': 'Texas', 'info': None}]
[{'state': 'California', 'info': [2,3,]}]
```

I cannot use json_normalize now with record_path=['info'] as the field for the second record is None. That's perfectly valid for this field, but not acceptable to pandas. Its a real world case btw.

if the key is not there it should raise a KeyError not a TypeError I think (I can change the test to verify for that).

**Comment by jbrockmendel** [comment]
@bolkedebruin thank you for providing an example, but i need you to go a little bit further and make it into something i can copy/paste to reproduce the problem (https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)

cc @WillAyd

**Comment by bolkedebruin** [comment]
@jbrockmendel please see the PR. I've written a test for it.

**Comment by jbrockmendel** [comment]
excellent, thank you
