### ISSUE TITLE
No mechanism for indicating missing value in na_values param of read_csv

### ISSUE THREAD

**Issue by jeremy-rutman** [pandas-dev/pandas#30152]
#### Code Sample, a copy-pastable example if possible
``` python 
 pd.read_csv('test.csv',sep=',',na_values=[None, '#N/A’, ‘#N/A N/A’, ‘#NA’, ‘-1.#IND’, ‘-1.#QNAN’, ‘-NaN’, ‘-nan’, ‘1.#IND’, ‘1.#QNAN’, ‘N/A’, ‘NA’, ‘NULL’,‘NaN’, ‘n/a’, ‘nan','null'],keep_default_na=False)

# is not the same as

 pd.read_csv('test.csv',sep=',',keep_default_na=True)
```
#### Problem description
The na_values parameter of read_csv doesn't have a way for users to indicate a missing field.
Thus if one wants to keep reading missing fields (ie two delimiters in a row) as NaN but use na_values for the rest, there doesn't seem to be any way to do this. 

#### Expected Output
Some mechanism for indicating a missing field in na_values is needed

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.0.0-37-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_IL
LOCALE           : en_IL.UTF-8

pandas           : 0.25.3
numpy            : 1.17.4
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 9.0.1
setuptools       : 39.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 0.999999999
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 5.5.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by jschendel** [comment]
Does including the empty string `''` in `na_values` achieve what you want?

**Comment by jeremy-rutman** [comment]
No (I could just use the default values in that case) - an example would be data like:
```
col1,col2
a,b
,d
'',f
```
where the  'missing value' (line 3 1st column) is treated the same as the empty string (line 4 first column)

**Comment by phofl** [comment]
Based on your example, the following

```
source = io.StringIO("""col1,col2
a,b
,c
'',f""")
print(pd.read_csv(source, sep=',', na_values=[None,
                                            '#N/A’, ‘#N/A N/A’, ‘#NA’, ‘-1.#IND’, ‘-1.#QNAN’, ‘-NaN’, ‘-nan’, ‘1.#IND’, ‘1.#QNAN’, ‘N/A’, ‘NA’, ‘NULL’,‘NaN’, ‘n/a’, ‘nan',  "''", ""], keep_default_na=False))
```

returns

```
  col1 col2
0    a    b
1  NaN    c
2  NaN    f
```

which seems to do what you expected? As long as I understood the problem correct

**Comment by mroeschke** [comment]
Looks like based on the above example this is working as expected. Closing as a usage question but happy to reopen if there is a bug in this behavior
