### ISSUE TITLE
Json Normalize failed

### ISSUE THREAD

**Issue by darbelley** [pandas-dev/pandas#30159]
#### Code Sample, a copy-pastable example if possible

{
		"data": [
			{
				"attributes": {
					....
					}
				}
		],
		"included": [
			{
				"attributes": {					
			}
		]
	},
	{
		"data": [
			{
				"attributes": {
					....
					}
				}
		],
		"included": [
			{
				"attributes": {					
			}
		]
	},
	....
	.......
	..........
	{
		"data": [
			{
				"attributes": {
					....
					}
				}
		]
	}

OrdersResponsesIncluded = json_normalize(data=my_list_loaded, record_path=['included'] , errors='ignore')

	
#### Problem description

Hi All,

since some week I am using Pandas to normalize data extracted by api responses
I would ask your help about a particular case that does not fit with the method json_normalize of pandas.
Basically I have a structure of my json like above (please note that last object contain ONLY the "data" array and not the "included" array.
Within detail there is the error received.

#### Expected Output

json normalized as usual about "included" 

<details>

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-54-e4812a026c1f> in <module>
      1 # farlo con quanto ricaricato
      2 
----> 3 OrdersResponsesIncluded = json_normalize(data=my_list_loaded, record_path=['included'] , errors='ignore')

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\json\_normalize.py in json_normalize(data, record_path, meta, meta_prefix, record_prefix, errors, sep, max_level)
    323                 records.extend(recs)
    324 
--> 325     _recursive_extract(data, record_path, {}, level=0)
    326 
    327     result = DataFrame(records)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\json\_normalize.py in _recursive_extract(data, path, seen_meta, level)
    295         else:
    296             for obj in data:
--> 297                 recs = _pull_field(obj, path[0])
    298                 recs = [
    299                     nested_to_record(r, sep=sep, max_level=max_level)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\json\_normalize.py in _pull_field(js, spec)
    244                 result = result[field]
    245         else:
--> 246             result = result[spec]
    247 
    248         return result

KeyError: 'included'

</details>

**Comment by darbelley** [comment]
I add that I tried also with another approach -->

Trying another way i created this(I am a newbeb also about python...):

1.Open file

with open("C:/Users/cdarbelley/Desktop/Jupyter_Phyton/my_list.json") as f:
    contents = f.read()
    count = contents.count("included")

2. For loop - extract only included section and append them within a list 


my_list_only_include=[]
array=[0]
for d in array:
    includedOnly=my_list_loaded[d]['included']
    my_list_only_include.append(includedOnly)
    
    array += [0] 

    if len(array) > count:
        break
    print(my_list_only_include)
    continue
    print(array)

	

3. Basically it create a structure like this 

[[{'attributes': 
....	
}]],
[[{'attributes': 
....	
}]],
[[{'attributes': 
....	
}]],
........................
	
	
4. json normalization

OrdersResponsesIncluded = json_normalize(my_list_only_include)


5.Error

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-4965f198839d> in <module>
----> 1 OrdersResponsesIncluded = json_normalize(my_list_only_include_loaded)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\json\_normalize.py in json_normalize(data, record_path, meta, meta_prefix, record_prefix, errors, sep, max_level)
    256 
    257     if record_path is None:
--> 258         if any([isinstance(x, dict) for x in y.values()] for y in data):
    259             # naive normalization, this is idempotent for flat records
    260             # and potentially will inflate the data considerably for

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\json\_normalize.py in <genexpr>(.0)
    256 
    257     if record_path is None:
--> 258         if any([isinstance(x, dict) for x in y.values()] for y in data):
    259             # naive normalization, this is idempotent for flat records
    260             # and potentially will inflate the data considerably for

AttributeError: 'list' object has no attribute 'values'

**Comment by mroeschke** [comment]
Could you post a self-contained, copy-pastable example that we could use as a regression test? https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by darbelley** [comment]
`[
	{
		"data": [
			{
				"id": "37640"
			}
		],
		"included": [
			{
				"id": "37641"
				},
			{
				"id": "37642"
			}
		]
	},
	{
		"data": [
			{
				"id": "37401"
			}
		]
	}
]`

**Comment by darbelley** [comment]
Do you know how can I extract the "included" part ?
I dont have any problem with the "data" part that is always within the json but sometime the data has no relation with include...

**Comment by darbelley** [comment]
resolved 
1. i created a list of dictionaries, some have empty "included" object
2. then i created a list where i have appended a number of elements = to count of dictionaries
3. for each element in the list i delete the data section and i append the element into another list

**Comment by darbelley** [comment]
.
