### ISSUE TITLE
Resampled.ffill leaves NA

### ISSUE THREAD

**Issue by therblack** [pandas-dev/pandas#30167]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
x = pandas.Series([1, pandas.np.NaN, 1], index=[pandas.Timestamp('2003-01-01'), pandas.Timestamp('2003-04-16'), pandas.Timestamp('2003-04-17')])

x.resample('D', closed='right').ffill()['2003-04']
```
#### Problem description

Resample.ffill leaves an NA. 

The output of the above has an NA on 2003-04-16 whereas I'd expect it all to be 1.0

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Expected Output
2003-04-01    1.0

2003-04-02    1.0

2003-04-03    1.0

2003-04-04    1.0

2003-04-05    1.0

2003-04-06    1.0

2003-04-07    1.0

2003-04-08    1.0

2003-04-09    1.0

2003-04-10    1.0

2003-04-11    1.0

2003-04-12    1.0

2003-04-13    1.0

2003-04-14    1.0

2003-04-15    1.0

2003-04-16    1.0

2003-04-17    1.0

Freq: D, dtype: float64
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS

------------------

commit           : None

python           : 3.8.0.final.0

python-bits      : 64

OS               : Linux

OS-release       : 3.10.0-862.14.4.el7.x86_64

machine          : x86_64

processor        : x86_64

byteorder        : little

LC_ALL           : None

LANG             : en_US.UTF-8

LOCALE           : en_US.UTF-8

 

pandas           : 0.25.3

numpy            : 1.17.4

pytz             : 2019.3

dateutil         : 2.8.1

pip              : 19.3.1

setuptools       : 42.0.2.post20191203

Cython           : None

pytest           : None

hypothesis       : None

sphinx           : None

blosc            : None

feather          : None

xlsxwriter       : None

lxml.etree       : None

html5lib         : None

pymysql          : None

psycopg2         : None

jinja2           : None

IPython          : None

pandas_datareader: None

bs4              : None

bottleneck       : None

fastparquet      : None

gcsfs            : None

lxml.etree       : None

matplotlib       : None

numexpr          : None

odfpy            : None

openpyxl         : None

pandas_gbq       : None

pyarrow          : None

pytables         : None

s3fs             : None

scipy            : None

sqlalchemy       : None

tables           : None

xarray           : None

xlrd             : None

xlwt             : None

xlsxwriter       : None

</details>

**Comment by TomAugspurger** [comment]
That's intended and documented in https://dev.pandas.io/docs/reference/api/pandas.core.resample.Resampler.fillna.html#pandas.core.resample.Resampler.fillna. Only values introduced by upsampling are filled. To fill missing values in the original, call fillna before or after resampling.
