### ISSUE TITLE
pandas.read_pickle can take buffer object as well, not only str

### ISSUE THREAD

**Issue by anatoly-khomenko** [pandas-dev/pandas#30163]
https://github.com/pandas-dev/pandas/blob/62a87bf4a2af02a8d3bc271ad26e5994292b8e6a/pandas/io/pickle.py#L95

read_pickle does not accept google storage URL (in form "gs://bucket-name/path/file.pkl") as input

While this code works fine:
`
with tf.io.gfile.GFile("gs://bucket-name/path/file.pkl", "rb") as infile:
      df = pd.read_pickle(infile, compression=None)
`

Might be reasonable to amend the documentation with this if the above is true for the recent version of pandas.

**Comment by WillAyd** [comment]
Makes sense - should be in line with other IO functions I think

**Comment by jreback** [comment]
this is very easy to patch to actually read from uri

**Comment by suzutomato** [comment]
take
