### ISSUE TITLE
groupby .sum() includes non-pertinent combinations of grouping criteria in result with a 'NaN' value

### ISSUE THREAD

**Issue by RS574** [pandas-dev/pandas#30172]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

d1 = ['foo', 'bar'] * 50
d2 = list('ABCD' * 25)
d3 = pd.date_range('2019-01-01', periods=100, freq='D')
d4 = list(range(1, 101, 1))
d5 = list(range(1000, 100001, 1000))

df = pd.DataFrame(dict(col1=d1, col2=d2, col3=d3, col4=d4, col5=d5))

bins = [0, 30, float('inf')]

grouped = df.groupby(['col1', 'col2', pd.Grouper(key='col3', freq='MS'), 
                      pd.cut(df.col4, bins)])
summary = grouped['col5'].sum()

```
#### Problem description

When using pandas version 0.25.3, **_grouped['col5'].sum()_**  in the code above generates a result that has every possible combination of the grouping criteria, and shows 'NaN' for non-significant combinations (see screenshot of the results below). This behavior was not observed when **_.count()_** was used instead of **_.sum()_**. This behavior was also not observed in pandas version 0.24.2.

#### Output

![image](https://user-images.githubusercontent.com/58710879/70833873-74df3b80-1dbe-11ea-82e1-5789696a8d36.png)

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en
LOCALE           : None.None

pandas           : 0.25.3
numpy            : 1.17.4
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 42.0.2.post20191203
Cython           : 0.29.14
pytest           : 5.3.1
hypothesis       : None
sphinx           : 2.2.2
blosc            : None
feather          : None
xlsxwriter       : 1.2.6
lxml.etree       : 4.4.2
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.10.1
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : 1.3.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.2
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 3.0.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.3.11
tables           : 3.6.1
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.6

</details>

**Comment by sendww** [comment]
Is this fix in a newer version?

**Comment by jbrockmendel** [comment]
This is the correct default behavior.  To get only entries that are non-NaN, you need to pass `observed=True` to `df.groupby`.

Closing as addressed; we can re-open if I've missed something.
