### ISSUE TITLE
Feature request: a simple aggregator function for error checking

### ISSUE THREAD

**Issue by FlorianDietz** [pandas-dev/pandas#30187]
I wrote a simple custom aggregator function that I have found repeatedly useful for error checking in data analysis.

This function does nothing you can't already do without it, but it's a simple way to add a sanity check to a common usecase.

The function is an aggregator function that raises an Exception if its input Series contains more than one unique value, and otherwise returns that value.

## Example usecase

If you know the value of the column 'datetime', you should logically also know the value of the column 'date'. Therefore, aggregating over 'datetime' should imply that you also know the 'date'. Situations like these appear often during data analysis, when you want to aggregate by a field A while keeping a field B that was derived from A.

These three statements result in the same dataframe, but the third version, which uses my custom aggregator the_value(), raises an exception if there are any rows that have the same datetime but not the same date. The first two potions are what people commonly do instead, and they are not able to detect this error:

```python
df.groupby(['datetime', 'date']).agg({'a': 'sum'})
df.groupby(['datetime']).agg({'a': 'sum', 'date':'first'})
df.groupby(['datetime']).agg({'a': 'sum', 'date': utilities.the_value})
```

## A simple implementation

```python
def the_value(series):
   c = series.nunique()
   if c > 1:
       raise ValueError("This field has more than one value after aggregation!")
   return series.iloc[0]
```

## Feature request

I request adding a named aggregator function that performs this operation, so that these sorts of errors can be caught more easily:

```python
df.groupby(['datetime']).agg({'a': 'sum', 'date': 'unique'})
```

**Comment by fujiaxiang** [comment]
@FlorianDietz 
I tried your suggestion on version 0.25.3, isn't this feature already there? Correct me if I misunderstood you.

```python
import pandas as pd

>>> import pandas as pd
>>>
>>> df = pd.DataFrame([
...     [1, 1],
...     [1, 1],
...     [2, 2],
...     [2, 3]
... ], columns=['a', 'b'])
>>> df
   a  b
0  1  1
1  1  1
2  2  2
3  2  3
>>>
>>> df.groupby('a').agg({'b': 'unique'})
        b
a
1     [1]
2  [2, 3]
>>> df.groupby('a').agg({'b': 'nunique'})
   b
a
1  1
2  2
>>> df.groupby('a').agg(n_unique_dates=pd.NamedAgg(column='b', aggfunc='nunique'))  # If you mean to give the column a custom name
   n_unique_dates
a
1               1
2               2
```

In your case, if you wish to catch the datetime groups with multiple different dates, you can then filter on that `nunique` column. Something like the below.
```python
result = df.groupby('datetime').agg({'a': 'sum', 'date': 'nunique'})
result[result['date'] > 1]  # This will show you the data errors. You can then decide what you wanna do about them
```

**Comment by FlorianDietz** [comment]
No, that's not what I mean. Although I should have picked a different name than 'unique', since that already exists.

This is what I mean:

```python
>>> df = pd.DataFrame([
...     [1, 1],
...     [1, 1],
...     [2, 2],
...     [2, 3]
... ], columns=['a', 'b'])
>>> df
   a  b
0  1  1
1  1  1
2  2  2
3  2  3
>>>
>>> df.groupby('a').agg({'b': 'the_value'})
Error: The column 'b' has more than one value for the group 'a'=2.
```

In your example, the function would raise an error. This is useful for performing sanity checks during aggregations. It's very useful to do this when you received your data from external sources who you can't fully trust to have done a good job. It's also useful for checking your own work, just like putting assert statements in your code.

**Comment by fujiaxiang** [comment]
That already exists. Just remove the quotes, like this:
```python
df.groupby('a').agg({'b': the_value})
```
You can use any custom function like this, as long as they have an output that can be properly concatenated in pandas' context.
However, unless you are sure you can't use the built-in functions, I would suggest you use the built-in functionalities which usually are much faster than custom defined python functions (often they pass the heavy-lifting computation to C codes which is much faster).
For example, in your case I would do 
```python
result = df.groupby('datetime').agg({'a': 'sum', 'date': 'nunique'})
```
You can then do
```python
result[result['date'] > 1]
```
to see if there are any errors and decide how to handle them.
This will give you more flexibility as well, as you can freely choose to 
1. drop these entries
1. manually correct them
1. average them
1. take the median
1. etc.

**Comment by FlorianDietz** [comment]
I am aware that this already exists. As I stated, this doesn't do anything that is not already possible. However, it makes it possible to perform these kinds of error checks in one line, for multiple columns, without having to manually add an assertion for each of them. It's purely a convenience function that makes it easier to check for errors, and therefore makes developers more likely to perform those checks when they would otherwise skip them to save time.

Is there any reason _against_ just adding this functionality? It's a trivial addition and doesn't conflict with anything.

**Comment by mroeschke** [comment]
Thanks for the suggestion. I am also on the side that this behavior shouldn't necessarily be a "first class" string operation in aggregations. Strings used in aggregations usually mirror pandas methods or numpy methods, and this would break this model.

Going to close since this feature hasn't gotten much support from the rest of the community and core devs, but happy to reopen if there's renewed interest
