### ISSUE TITLE
BUG: Series.astype does not change categorical dtype if categories match up to permutation

### ISSUE THREAD

**Issue by batterseapower** [pandas-dev/pandas#30206]
#### Code Sample, a copy-pastable example if possible

```python
pd.Series(['A', 'B'], dtype='category').astype(pd.CategoricalDtype(categories=['B', 'A'])).cat.categories
```

#### Problem description

This should return `Index(['B', 'A'])` but actually it returns `Index(['A', 'B'])`. This is bad because if I use `astype` to give a Series a particular dtype I expect the result to have the dtype I asked for!

Both of these examples work as expected, so this bug only seems to happen if the new dtype has categories that are equal to the old categories after sorting:
```python
pd.Series(['A', 'B'], dtype='category').astype(pd.CategoricalDtype(categories=['A'])).cat.categories
pd.Series(['A', 'B'], dtype='category').astype(pd.CategoricalDtype(categories=['B', 'A', 'C'])).cat.categories
```

#### Expected Output

`Index(['B', 'A'])`

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.0.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252

pandas           : 0.25.3
numpy            : 1.17.4
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 42.0.2.post20191203
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
</details>

**Comment by batterseapower** [comment]
This bug might have something to do with this:

`pd.CategoricalDtype(categories=['A', 'B']) == pd.CategoricalDtype(categories=['B', 'A']) `

This behavior doesn't seem very sensible to me?

**Comment by jreback** [comment]
categorical are unordered by default
you can specify ordered=True if you want to have specific otherwise categories are lexsortes

**Comment by batterseapower** [comment]
Thanks for the fast response & the information.

I find this behavior extremely surprising, but OK. I do think the [docs](https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.api.types.CategoricalDtype.html) could be improved: that page doesn't really explain in any great depth what `ordered` is meant to do.

If anyone else finds this issue, the workaround is to replace your uses of astype with something like this:

```python
def astype_categorical(xs: pd.Categorical, dtype: pd.CategoricalDtype):
    # https://github.com/pandas-dev/pandas/issues/30206
    return pd.Categorical.from_codes(
        dtype.categories.get_indexer(xs.categories)[xs.codes],
        categories=dtype.categories
    )
```

**Comment by jreback** [comment]
if u r interested in improving the docs would take a PR

your workaround is very odd

**Comment by batterseapower** [comment]
I'm not sure why you say my workaround is odd. Let me try to explain a bit more clearly why I was expecting this behaviour. Basically, what I expect is that this property will be true for any `Series`, `s` and `Index`, `cats`:

`s.astype(pd.CategoricalDtype(categories=cats)).cat.categories.equals(cats)`

In Pandas as it stands today, this invariant does hold almost all the time, except in the special case where `sorted(s.cat.categories) == sorted(cats)`. This makes it very easy to write code that depends on the invariant and works almost all the time, but then fails in some special cases.

Why is this invariant useful? The reason it came up in my code is because I have two categorical `Series` and I want to pass them to a `numba` function. Because `numba` is slow when using python objects, instead of passing the object arrays to the function I want to pass the codes instead, but I want to do this in such a way that the codes compare equal if-and-only-if the original objects compare equal. So for example imagine that we wanted to numbaify this function:

```python
def f(xs, ys):
    return (xs == ys).sum()
```

I was expecting to be able to do this like this:

```python
@nb.njit()
def f_numba(xs, ys):
    total = 0
    for i in range(len(xs)):
        total += (xs[i] >= 0) & (ys[i] >= 0) & (xs[i] == ys[i])
    return total

def f(xs, ys):
    ys = ys.astype(xs.dtype)
    return f_numba(xs.values.codes, ys.values.codes)
```

(Note that `f` is not actually the function I want to write, this is just an illustrative example.). The new `f` works almost all the time except when `xs` and `ys` have categorical dtypes that match up to permutation.

Clearly you have a semantics in mind for the default `ordered=False` `CategoricalDtype` that conflicts with my desire for this new `f` to work, but at this point I'm still not really sure what that semantics is.
