### ISSUE TITLE
Mongo error sort

### ISSUE THREAD

**Issue by mrameen** [pandas-dev/pandas#30212]
using this
https://www.quackit.com/mongodb/tutorial/mongodb_sort_query_results.cfm
But got error. column phase is exist

```python
collection.find( ).sort( { phase: 1 } )

```
Traceback (most recent call last):
  File "table2.py", line 37, in <module>
    collection.find( ).sort( { phase: 1 } )
NameError: name 'phase' is not defined

**Comment by jbrockmendel** [comment]
Is this a pandas issue or a mongodb issue?

**Comment by WillAyd** [comment]
Right these aren't pandas modules - I assume a mongo issue
