### ISSUE TITLE
Renaming DataFrame and Series is inconsistent when inplace=True

### ISSUE THREAD

**Issue by Hvass-Labs** [pandas-dev/pandas#30211]
#### Problem description

There is an inconsistency between **inplace** renaming of DataFrame and Series. `DataFrame.rename()` returns `None` when `inplace=True`, while `Series.rename()` returns the same object when `inplace=True`. I think they should both return the `self` object.

#### Code Sample

    d = {'col1': [1, 2], 'col2': [3, 4]}
    df = pd.DataFrame(data=d)

    d = [123, 456, 789]
    ser = pd.Series(data=d, name='col')

    # This returns a new DataFrame object.
    df.rename(columns={'col1': 'col1new'})

    # This returns a new Series object.
    ser.rename('colnew')

    # Note that (A) and (B) behave differently.

    # (A)
    # This updates df inplace and returns None.
    df.rename(columns={'col1': 'col1new'}, inplace=True)

    # (B)
    # This updates ser inplace and returns the same object.
    ser.rename('colnew', inplace=True) 

#### Cause

This appears to be the implementation of `Series.rename()`:

https://github.com/pandas-dev/pandas/blob/master/pandas/core/series.py#L1563-L1566

This appears to be the implementation of `DataFrame.rename()`:

https://github.com/pandas-dev/pandas/blob/master/pandas/core/generic.py#L1118-L1121

The relevant code for `DataFrame.rename()` is:

    if inplace:
        self._update_inplace(result._data)
    else:
        return result.__finalize__(self)

I would imagine it should simply be changed to something like the following, but Pandas' semantics are so complicated and inconsistent that I have no idea if this will break something somewhere else:

    if inplace:
        self._update_inplace(result._data)
        return self
    else:
        return result.__finalize__(self)

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-72-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.16.4
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.1.1
setuptools       : 41.6.0
Cython           : None
pytest           : 5.1.3
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.5.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.0
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by jreback** [comment]
there there is an issue about this already - pls
have a look

- inplace opperations should return None
- we are planning on depreciating inplace operations at some point

**Comment by Hvass-Labs** [comment]
Thanks for the quick reply! I did actually search for open/closed GitHub issues on this topic but couldn't find any. If I search for the text you suggest: inplace opperations should return None, I only get this GitHub issue here.

I don't understand why you want to deprecate inplace operations? Could you redirect to a GitHub issue where you are discussing the pro's and con's of this? It seems incredibly wasteful to copy large DataFrames e.g. just to change column-names.

**Comment by mroeschke** [comment]
Looks like this code path has changed and now should return `None`

```
        if inplace:
            self._update_inplace(result)
            return None
        else:
            return result.__finalize__(self, method="rename")
```

I believe we have tests for this so going to close. Happy to reopen if we don't
