### ISSUE TITLE
Feature Request: Convenience method to rename a column

### ISSUE THREAD

**Issue by Khris777** [pandas-dev/pandas#30224]
Usually when renaming a column you have to write:

```
df.rename(columns={"old": "new"})
```

It would be nice to have a convenience method to rename one column like this:

```
df.renamecol("old", "new")
```

**Comment by TomAugspurger** [comment]
Thanks for the feature request. IMO this isn't useful enough to warrant its own method.

**Comment by jreback** [comment]
closing. as @TomAugspurger says we *already* have an api for this.
