### ISSUE TITLE
Move 'For Developers' content from wiki to contributing docs.

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#30232]
Content from the 'For Developers' content section of the wiki should be included in the pandas documentation where relevant. 

- [ ] Code Style and Conventions
- [ ] Testing #20501
- [ ] Documenting new features and bug fixes
- [ ] Using Git
- [ ] Choosing Exceptions to Raise
- [ ] Tips & Tricks for pandas dev
- [ ] A quick overview of pandas.util
- [ ] Git Workflows
- [ ] Pandas Development FAQ
- [ ] Building On Windows

PRs welcome for any of the above sections.

**Comment by souvik3333** [comment]
Hi, I would like to work on this.

**Comment by baevpetr** [comment]
Hi, I would also like to take part.

**Comment by alimcmaster1** [comment]
Write which section you would like to work on here - to avoid any conflicts

**Comment by souvik3333** [comment]
I have started working on "Code Style and Conventions". I will comment on others if I started working on them.

**Comment by simonjayhawkins** [comment]
> I have started working on "Code Style and Conventions". I will comment on others if I started working on them.

In some places the wiki is quite outdated, so may be best to open a PR before you do too much work for feedback. You can mark it as WIP or Draft.

**Comment by ShamanthNyk** [comment]
Is the issue still open?
I would like to work on this

**Comment by drewseibert** [comment]
Hello, I would like to help out or shadow if this issue still exists. @ShamanthNyk

**Comment by drewseibert** [comment]
Any current PRs out for this?

**Comment by ayaan32** [comment]
Hi, I'd like to work on the "using git" part.

**Comment by echozzy629** [comment]
Hello, I would like to work on this.

**Comment by AdrianMastronardi** [comment]
Hello, I will work on **testing** and **Pandas Development FAQ**. 
Do you think that the FAQ page is still relevant? I was thinking on adding a reference to each of the other specific pages, e.g. in the coding style section of the FAQ reference the coding style section. Does it make sense to you?

**Comment by JeremiahKamama** [comment]
I would like to take a look at this

**Comment by musketeer191** [comment]
Hi, I would like to work on "Choosing Exceptions to Raise".

**Comment by simonjayhawkins** [comment]
> Hi, I would like to work on "Choosing Exceptions to Raise".

after quickly reading that wiki, my opinion is that most of that content is still applicable so could be copied over to doc\source\development\code_style.rst and reformatted appropriately.

Note: doc\source\development\code_style.rst is a relatively recent addition and is WIP so does not yet have a well defined structure.

**Comment by Ayushihelloworld** [comment]
Hello I want to work on this. Is this issue still open?

**Comment by Ayushihelloworld** [comment]
take

**Comment by Andres8ezau** [comment]
Hi!  Can I help ?

**Comment by Ayushihelloworld** [comment]
Sure

**Comment by agarwalutkarsh554** [comment]
Hello! can I help?
