### ISSUE TITLE
loop over dataframes to select rows didn't work

### ISSUE THREAD

**Issue by StevenLi-DS** [pandas-dev/pandas#30261]
#### Code Sample, a copy-pastable example if possible

```python
import seaborn as sns
import pandas as pd
df = sns.load_dataset('tips')

df_1 = df[['tip', 'time', 'day']].copy()
df_2 = df[['total_bill', 'time', 'day']].copy()

for each_df in [df_1, df_2]:
    each_df = each_df[each_df['day'] != 'Sun']
```
#### Problem description

I tried to loop over two dataframes but the selecting operation didn't work and I checked `df_1` and `df_2`, and rows with 'Sun' are still in the dataframe. I also check the iteration variable `each_df`, the rows with `Sun` were indeed dropped. 

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.3
numpy            : 1.16.2
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.1
setuptools       : 41.4.0
Cython           : 0.29.7
pytest           : 4.5.0
hypothesis       : None
sphinx           : 2.0.1
blosc            : None
feather          : None
xlsxwriter       : 1.1.7
lxml.etree       : 4.3.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.0
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.2.1
sqlalchemy       : None
tables           : None
xarray           : 0.12.1
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : 1.1.7
</details>

**Comment by jason-r-becker** [comment]
You're creating a new view of each DataFrame in the loop. Instead you need to modify the DataFrames inplace, change the loop to the following:

```Python
for each_df in [df_1, df_2]:
     each_df.drop(df[df['day'] == 'Sun'].index, inplace=True)
```

**Comment by mroeschke** [comment]
This board is for package issues and enhancement requests. For usage questions, we recommend StackOverflow.

**Comment by StevenLi-DS** [comment]
@jason-r-becker thanks for the clarification.

@mroeschke I thought it's a bug. Sorry about that.
