### ISSUE TITLE
Only reading first sheet without warning 

### ISSUE THREAD

**Issue by samuelweisenthal** [pandas-dev/pandas#30276]
#29491 ## Problem description

When there are multiple sheets in an excel file, read_excel only returns the first.  This is fine, but I think it should also warn that there are multiple sheets

**Comment by lukzmu** [comment]
@samuelweisenthal If you are unsure, whether your excel file has more than one sheet, you could always use `sheet_name=None` to read all sheets.

**Comment by WillAyd** [comment]
This is by design and not likely to change; the advice from @lukzmu is good and matches the documentation for the function

**Comment by samuelweisenthal** [comment]
I had never worked with excel files in pandas before - I was working quickly and missed that there were other sheets, so I thought someone else might too.  Excel standard behavior for a large dataset is apparently to split it into multiple sheets, but these are all but hidden from you if you read in using pandas
