### ISSUE TITLE
AttributeError: module 'pandas' has no attribute 'ewm'

### ISSUE THREAD

**Issue by sha-ali** [pandas-dev/pandas#30286]
#### Code Sample, a copy-pastable example if possible
def get_technical_indicators(dataset):
       dataset['26ema'] = pd.ewm(dataset['Close'], span=26)
       dataset['12ema'] = pd.ewm(dataset['Close'], span=12)
       dataset['MACD'] = (dataset['12ema']-dataset['26ema'])

def get_technical_indicators(dataset):
```python
# Your code here
when running those command is shows the error pandas has no attribute ewma
```
#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by jreback** [comment]
pls read the docs: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.ewm.html?highlight=ewm#pandas.DataFrame.ewm

ewm is a DataFrame method
