### ISSUE TITLE
pandas/excel/tkinter

### ISSUE THREAD

**Issue by uriielfl** [pandas-dev/pandas#30290]
Hi, there! How are? I'm trying to import the values from excel with pandas to a tkinter treeview, but i'm having some issues.
Here's the code:
![image](https://user-images.githubusercontent.com/49736581/70938361-c7219600-2024-11ea-81b2-f317424acf0f.png)

Here's the result:
![image](https://user-images.githubusercontent.com/49736581/70938333-b83ae380-2024-11ea-816f-c87caf0ac413.png)

Here's the values i want in right order:
![image](https://user-images.githubusercontent.com/49736581/70938431-ec160900-2024-11ea-9161-99fd06b5ae30.png)

If someone could help me, i wish I could see the informations of Excel on treeview in the same way i see on excel

**Comment by TomAugspurger** [comment]
@uriielfl we recommend [StackOverflow with the pandas tag](https://stackoverflow.com/questions/tagged/pandas) for usage questions.

**Comment by uriielfl** [comment]
@TomAugspurger Do you know a way to import line per line instead cells? Or a way to search for it, i'm trying to search and i can't even find something about it hahaha

**Comment by TomAugspurger** [comment]
Nope. I'd recommend asking on StackOverflow.

**Comment by WillAyd** [comment]
@uriielfl as mentioned should consult StackOverflow for usage questions - we typically just have bug reports and enhancement requests here
