### ISSUE TITLE
CI: Checks job aborted if a step fails

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#30298]
In our job that checks that the code is ok (flake8, mypy...) [1], we want to run all the steps whether any of them fail or not.

This is implemented by using `if: true` in each step. While this should work, it doesn't. A better way to implement this that probably fixes the issue is to use `if: always()` instead. 

What we should do is:
- Replace all instances of `if: true` by `if: always` in the yaml file. 
- Introduce couple of temporary errors. Something PEP-8 invalid (so flake8 reports the error), and change the order of the imports of a file (so isort reports the error). 
- Open a pull request
- See if the job behaves as expected, and wait for a code review
- Once the pull request is approved, revert the errors introduced, so the changes to the yaml file can be merged

1. https://github.com/pandas-dev/pandas/blob/master/.github/workflows/ci.yml

**Comment by suzutomato** [comment]
I'd like to take this.

**Comment by datapythonista** [comment]
Thanks @suzutomato 

You can assign the issue to yourself by writing `take` in a comment.

**Comment by suzutomato** [comment]
Sorry, I misunderstood the instruction in the contributing guide.
It had to be exactly "take", not including the exact word "take" in my comment.

**Comment by suzutomato** [comment]
take
