### ISSUE TITLE
Loading practice datasets without internet connection

### ISSUE THREAD

**Issue by jfmolano** [pandas-dev/pandas#30307]
Should Pandas has a feature that allows to load practice datasets (i.e. Iris) without internet connection such as R feature?

The solutions I have found need external libraries.

**Comment by TomAugspurger** [comment]
I don't think we would want to include datasets in the package installed by pip / conda.

I'd be happy to see a `pandas.datasets` package that loads datasets and caches them to disk, or generates random datasets, similar to `sklearn.datasets`.

**Comment by jfmolano** [comment]
Ok! It seems nice! What do you think that would be the path to implement that from Github? I am a newbie at contributing with open source projects but I would like to implement that feature.

**Comment by TomAugspurger** [comment]
Will need some discussion and agreement from other maintainers first.

**Comment by jfmolano** [comment]
Ok! Thanks for your reply!
