### ISSUE TITLE
.to_parquet() to a StringIO() causes python to crash

### ISSUE THREAD

**Issue by rootcss** [pandas-dev/pandas#30317]
```python
import pandas as pd
from io import StringIO
df = pd.DataFrame({'x': [1, 2, 2, 4]})
df.to_parquet('some_file')  # works fine

s = StringIO()
df.to_parquet(s)  # this causes the crash with following error
```

Error:
```
libc++abi.dylib: terminating with uncaught exception of type parquet::ParquetException: Arrow error: IOError: string argument expected, got 'bytes'
[1]    42832 abort      python
```

Edit:
The cause for the error is that instead of a String buffer, we should use Bytes buffer (io.BytesIO). But anyhow, the exception should be handled and shouldn't cause the interpreter itself to die.

**Comment by simonjayhawkins** [comment]
Thanks @rootcss for the report. I guess we should check the fname parameter and raise an appropriate user-facing message.

something like `TypeError: fname should be str or BytesIO, got {type(fname)}`

**Comment by vignesh-md** [comment]
I'd like to contribute and I'm a newbie here.

**Comment by baevpetr** [comment]
Me as well.

**Comment by jorisvandenbossche** [comment]
@rootcss what version of pyarrow are you using? (can you show the result of `pd.show_versions()`) 
I think this is already fixed in pyarrow. With pyarrow master I get:

```
>>> df.to_parquet(s)  
...
TypeError: binary file expected, got text file
```

**Comment by PhanatosZou** [comment]
I'm new here and I'd like to work on this issue:)

**Comment by jorisvandenbossche** [comment]
I am not sure there is something to fix. I think it is fine to rely on pyarrow for catching this, and it already works fine on the latest version.

**Comment by rootcss** [comment]
Upgrading pyarrow to latest resolves it. Thanks @jorisvandenbossche

**Comment by pydatasci-repos** [comment]
fyi, still running into this 
```
buff = io.StringIO()
df.to_parquet(buff) 
```
`TypeError: binary file expected, got text file`

```
!pip show pyarrow
Name: pyarrow
Version: 1.0.1
Summary: Python library for Apache Arrow
Home-page: https://arrow.apache.org/
Author: None
Author-email: None
License: Apache License, Version 2.0
Location: /Users/layne/.pyenv/versions/3.7.6/envs/jupyterlab/lib/python3.7/site-packages
Requires: numpy
Required-by: 
```

**Comment by impredicative** [comment]
I have created a related issue to make it easier to **write parquet to `bytes`** which should interest users: #37105
