### ISSUE TITLE
COMPAT: numpy test warning

### ISSUE THREAD

**Issue by nschloe** [pandas-dev/pandas#30334]
I'm currently testing a numpy deprecation to assess its impact on the ecosystem (https://github.com/numpy/numpy/pull/10615). To this end, I'd like to run pandas tests with `-Werror`. Doing that, I see that pandas throws a bunch of warnings at other places. Are those intentional? Perhaps pandas should test warning-free out of the box.

**Comment by TomAugspurger** [comment]
We raise on warnings from NumPy in our numpydev build, which uses the environment from ci/deps/azure-37-numpydev.yaml.

I'm not sure how feasible it would be to fail on warnings for all our builds, given the number of optional dependencies we have.

**Comment by TomAugspurger** [comment]
That's set in configured at https://github.com/pandas-dev/pandas/blob/master/ci/azure/posix.yml#L47-L53.

**Comment by jbrockmendel** [comment]
> I'm not sure how feasible it would be to fail on warnings for all our builds, given the number of optional dependencies we have.

This would fail in a bunch of places we don't have control over.  The biggest one is imports from `collections` that need to be updated to import from `collections.abc`.  We could try silencing those in the pytest config and see if whats left is manageable.

**Comment by nschloe** [comment]
I'm playing around with it atm and will submit a PR shortly. We can look at the diff then.
