### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by jayenashar** [pandas-dev/pandas#30333]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
pd.show_versions()
import seaborn as sns
```
#### Problem description

installed master with `pip install https://github.com/pandas-dev/pandas/archive/master.zip`

things that use the version don't work

<details>
<summary>show_versions()</summary>
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-45-3d232a07e144> in <module>()
----> 1 pd.show_versions()

15 frames

/usr/local/lib/python3.6/dist-packages/pandas/util/_print_versions.py in show_versions(as_json)
     94     for modname in deps:
     95         mod = import_optional_dependency(
---> 96             modname, raise_on_missing=False, on_version="ignore"
     97         )
     98         ver: Optional[str]

/usr/local/lib/python3.6/dist-packages/pandas/compat/_optional.py in import_optional_dependency(name, extra, raise_on_missing, on_version)
     84     )
     85     try:
---> 86         module = importlib.import_module(name)
     87     except ImportError:
     88         if raise_on_missing:

/usr/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

/usr/lib/python3.6/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib/python3.6/importlib/_bootstrap_external.py in exec_module(self, module)

/usr/lib/python3.6/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

/usr/local/lib/python3.6/dist-packages/pandas_datareader/__init__.py in <module>()
      1 from ._version import get_versions
----> 2 from .data import (DataReader, Options, get_components_yahoo,
      3                    get_dailysummary_iex, get_data_enigma, get_data_famafrench,
      4                    get_data_fred, get_data_google, get_data_moex,
      5                    get_data_morningstar, get_data_quandl, get_data_stooq,

/usr/local/lib/python3.6/dist-packages/pandas_datareader/data.py in <module>()
      5 import warnings
      6 
----> 7 from pandas_datareader.av.forex import AVForexReader
      8 from pandas_datareader.av.quotes import AVQuotesReader
      9 from pandas_datareader.av.sector import AVSectorPerformanceReader

/usr/local/lib/python3.6/dist-packages/pandas_datareader/av/__init__.py in <module>()
      1 import os
      2 
----> 3 from pandas_datareader.base import _BaseReader
      4 from pandas_datareader._utils import RemoteDataError
      5 

/usr/local/lib/python3.6/dist-packages/pandas_datareader/base.py in <module>()
      8 from pandas import read_csv, concat
      9 from pandas.io.common import urlencode
---> 10 from pandas_datareader.compat import bytes_to_str, string_types, binary_type, \
     11     StringIO
     12 

/usr/local/lib/python3.6/dist-packages/pandas_datareader/compat/__init__.py in <module>()
      9 PANDAS_VERSION = LooseVersion(pd.__version__)
     10 
---> 11 PANDAS_0190 = (PANDAS_VERSION >= LooseVersion('0.19.0'))
     12 PANDAS_0200 = (PANDAS_VERSION >= LooseVersion('0.20.0'))
     13 PANDAS_0210 = (PANDAS_VERSION >= LooseVersion('0.21.0'))

/usr/lib/python3.6/distutils/version.py in __ge__(self, other)
     68 
     69     def __ge__(self, other):
---> 70         c = self._cmp(other)
     71         if c is NotImplemented:
     72             return c

/usr/lib/python3.6/distutils/version.py in _cmp(self, other)
    335         if self.version == other.version:
    336             return 0
--> 337         if self.version < other.version:
    338             return -1
    339         if self.version > other.version:

TypeError: '<' not supported between instances of 'str' and 'int'
</details>

<details>
<summary>import seaborn as sns</summary>

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-46-52e5c5e254b6> in <module>()
----> 1 import seaborn as sns
      2 cmap_green_0 = sns.light_palette("green", as_cmap=True, reverse=True)
      3 cmap_red_1   = sns.light_palette("red", as_cmap=True)
      4 table_styles = [
      5                 {'selector': 'th', 'props': [('font-size', '0.9px'), ('padding', '0')]},

5 frames

/usr/local/lib/python3.6/dist-packages/seaborn/__init__.py in <module>()
      4 
      5 # Import seaborn objects
----> 6 from .rcmod import *
      7 from .utils import *
      8 from .palettes import *

/usr/local/lib/python3.6/dist-packages/seaborn/rcmod.py in <module>()
      3 import functools
      4 import matplotlib as mpl
----> 5 from . import palettes, _orig_rc_params
      6 
      7 

/usr/local/lib/python3.6/dist-packages/seaborn/palettes.py in <module>()
     10 from .external.six.moves import range
     11 
---> 12 from .utils import desaturate, set_hls_values, get_color_cycle
     13 from .colors import xkcd_rgb, crayons
     14 

/usr/local/lib/python3.6/dist-packages/seaborn/utils.py in <module>()
     15 
     16 from distutils.version import LooseVersion
---> 17 pandas_has_categoricals = LooseVersion(pd.__version__) >= "0.15"
     18 mpl_ge_150 = LooseVersion(mpl.__version__) >= "1.5.0"
     19 

/usr/lib/python3.6/distutils/version.py in __ge__(self, other)
     68 
     69     def __ge__(self, other):
---> 70         c = self._cmp(other)
     71         if c is NotImplemented:
     72             return c

/usr/lib/python3.6/distutils/version.py in _cmp(self, other)
    335         if self.version == other.version:
    336             return 0
--> 337         if self.version < other.version:
    338             return -1
    339         if self.version > other.version:

TypeError: '<' not supported between instances of 'str' and 'int'

</details>

#### Expected Output

<details>
/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.14.137+
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0+unknown
numpy            : 1.17.4
pytz             : 2018.9
dateutil         : 2.6.1
pip              : 19.3.1
setuptools       : 42.0.2
Cython           : 0.29.14
pytest           : 3.6.4
hypothesis       : None
sphinx           : 1.8.5
blosc            : None
feather          : 0.4.0
xlsxwriter       : None
lxml.etree       : 4.2.6
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.7.6.1 (dt dec pq3 ext lo64)
jinja2           : 2.10.3
IPython          : 5.5.0
pandas_datareader: 0.7.4
bs4              : 4.6.3
bottleneck       : 1.3.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.2.6
matplotlib       : 3.1.2
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 2.5.9
pandas_gbq       : 0.11.0
pyarrow          : 0.14.1
pytables         : None
s3fs             : 0.4.0
scipy            : 1.3.3
sqlalchemy       : 1.3.11
tables           : 3.4.4
xarray           : 0.11.3
xlrd             : 1.1.0
xlwt             : 1.3.0
xlsxwriter       : None
</details>

#### Output of ``pd.show_versions()``

<details>
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-45-3d232a07e144> in <module>()
----> 1 pd.show_versions()

15 frames

/usr/local/lib/python3.6/dist-packages/pandas/util/_print_versions.py in show_versions(as_json)
     94     for modname in deps:
     95         mod = import_optional_dependency(
---> 96             modname, raise_on_missing=False, on_version="ignore"
     97         )
     98         ver: Optional[str]

/usr/local/lib/python3.6/dist-packages/pandas/compat/_optional.py in import_optional_dependency(name, extra, raise_on_missing, on_version)
     84     )
     85     try:
---> 86         module = importlib.import_module(name)
     87     except ImportError:
     88         if raise_on_missing:

/usr/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

/usr/lib/python3.6/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib/python3.6/importlib/_bootstrap_external.py in exec_module(self, module)

/usr/lib/python3.6/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

/usr/local/lib/python3.6/dist-packages/pandas_datareader/__init__.py in <module>()
      1 from ._version import get_versions
----> 2 from .data import (DataReader, Options, get_components_yahoo,
      3                    get_dailysummary_iex, get_data_enigma, get_data_famafrench,
      4                    get_data_fred, get_data_google, get_data_moex,
      5                    get_data_morningstar, get_data_quandl, get_data_stooq,

/usr/local/lib/python3.6/dist-packages/pandas_datareader/data.py in <module>()
      5 import warnings
      6 
----> 7 from pandas_datareader.av.forex import AVForexReader
      8 from pandas_datareader.av.quotes import AVQuotesReader
      9 from pandas_datareader.av.sector import AVSectorPerformanceReader

/usr/local/lib/python3.6/dist-packages/pandas_datareader/av/__init__.py in <module>()
      1 import os
      2 
----> 3 from pandas_datareader.base import _BaseReader
      4 from pandas_datareader._utils import RemoteDataError
      5 

/usr/local/lib/python3.6/dist-packages/pandas_datareader/base.py in <module>()
      8 from pandas import read_csv, concat
      9 from pandas.io.common import urlencode
---> 10 from pandas_datareader.compat import bytes_to_str, string_types, binary_type, \
     11     StringIO
     12 

/usr/local/lib/python3.6/dist-packages/pandas_datareader/compat/__init__.py in <module>()
      9 PANDAS_VERSION = LooseVersion(pd.__version__)
     10 
---> 11 PANDAS_0190 = (PANDAS_VERSION >= LooseVersion('0.19.0'))
     12 PANDAS_0200 = (PANDAS_VERSION >= LooseVersion('0.20.0'))
     13 PANDAS_0210 = (PANDAS_VERSION >= LooseVersion('0.21.0'))

/usr/lib/python3.6/distutils/version.py in __ge__(self, other)
     68 
     69     def __ge__(self, other):
---> 70         c = self._cmp(other)
     71         if c is NotImplemented:
     72             return c

/usr/lib/python3.6/distutils/version.py in _cmp(self, other)
    335         if self.version == other.version:
    336             return 0
--> 337         if self.version < other.version:
    338             return -1
    339         if self.version > other.version:

TypeError: '<' not supported between instances of 'str' and 'int'
</details>

**Comment by TomAugspurger** [comment]
@jayenashar do you see the same if you clone the repository and pip install from that? Does versioneer work with zip installs?

**Comment by TomAugspurger** [comment]
IIUC, this looks like https://github.com/warner/python-versioneer/issues/140. Apparently versioneer can't get the necessary information from the zip archive. You'll need to clone it with git manually, or have pip do it with `pip install git+https://github.com/pandas-dev/pandas`.

LMK if that doesn't work and I'll reopen.

**Comment by jayenashar** [comment]
yup that works.  can you add that to the README or let people know when you ask them to use master?
