### ISSUE TITLE
tm.assert_series_equal checking on Integer EA should be exact by default?

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#30347]
#### Code Sample, a copy-pastable example if possible

```python
>>>
>>> import pandas as pd
>>> pd.__version__
'0.26.0.dev0+1328.g03dffb1eb'
>>>
>>> import pandas.testing as tm
>>> s1 = pd.Series([10000000000000000], dtype="Int64")
>>> s1
0    10000000000000000
dtype: Int64
>>>
>>> s2 = pd.Series([9999999999999999], dtype="Int64")
>>> s2
0    9999999999999999
dtype: Int64
>>>
>>> tm.assert_series_equal(s1,s2)
>>>
```
#### Problem description

does not raise

#### Expected Output

`AssertionError: ExtensionArray are different`

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 03dffb1eb312d1bc535e26f43e32c11e0584c8c5
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : None.None

pandas           : 0.26.0.dev0+1328.g03dffb1eb
numpy            : 1.17.3
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 42.0.2.post20191201
Cython           : 0.29.14
pytest           : 5.3.2
hypothesis       : 4.54.1
sphinx           : 2.3.0
blosc            : None
feather          : None
xlsxwriter       : 1.2.6
lxml.etree       : 4.4.2
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.10.2
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : 1.3.1
fastparquet      : 0.3.2
gcsfs            : None
lxml.etree       : 4.4.2
matplotlib       : 3.1.2
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 3.0.1
pandas_gbq       : None
pyarrow          : 0.15.1
pytables         : None
pytest           : 5.3.2
s3fs             : 0.4.0
scipy            : 1.3.1
sqlalchemy       : 1.3.11
tables           : 3.6.1
xarray           : 0.14.1
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.6

</details>

discovered while investigating #30268

**Comment by TomAugspurger** [comment]
What do we do for a NumPy int64-dtype array?

**Comment by simonjayhawkins** [comment]
That behaves the same, perhaps less restrictive issue title. I see some previous discussion on this (e.g. #26272) and concerns of it being a breaking API change.

For Integer EA, maybe this won't apply? 

IMO integers should be exact, could be identifiers, i.e. invoice number. If our tests are checking for exactness by default then we could have latent bugs.

with check_exact works fine.

**Comment by TomAugspurger** [comment]
Agreed. +1 for sure on IntegerArray, and probably on int64, though I don't recall the details on why it's not exact right now.

**Comment by jbrockmendel** [comment]
Instead of making the default behavior dtype-specific, should we just make the default in assert_extension_array_equal check_exact=True?  I think also in tm.assert_equal we hardcode check_exact=False which should change.

**Comment by mroeschke** [comment]
Closing in favor of https://github.com/pandas-dev/pandas/issues/55882
