### ISSUE TITLE
Pandas Read and Write Many Files.

### ISSUE THREAD

**Issue by phdnzdeveloper** [pandas-dev/pandas#30361]
#### Code Sample
prefix_of_filename_1.csv
prefix_of_filename_2.csv

```python
pd.read_csv('file://folder_name/prefix_of_filename*.csv')

df.to_csv('file://folder_name/file_name*.csv', name_function=name, chunksize='64mb')
```
#### Problem description

Hi Team,

I would like to request a feature to read and write multiple files at a same time. It would be nice to have features like that for preparing data for concurrent data reading system.

Kind Regards
Giang

**Comment by TomAugspurger** [comment]
> at a same time.

How exactly would that work? I suspect that the right answer is to use some thread or process pool managing mean read_csv / to_csv calls. Pandas probably isn't the right layer to think about this.

**Comment by phdnzdeveloper** [comment]
Hi Tom,

I mean we can do it in sequence.

**Comment by TomAugspurger** [comment]
Gotcha. So on the read side of things, you'd like to pass a list / globstring of files? I think that'd have a poor interaction with many of pandas' other keyword arguments. Things like the header, skipping rows, chunking, become more complicated if `read_csv` means more that multiple files.

I'd recommend reading the files in separately and concatenating them, or using dask.dataframe.
