### ISSUE TITLE
to_parquet mishandles dates

### ISSUE THREAD

**Issue by tigerhawkvok** [pandas-dev/pandas#30367]
#### Code Sample

This generates a series of ints for dates, which when trying to be imported elsewhere fails

```python
# Fails
dbSlice.to_parquet(outFile, index= False)
```

Instead, [consider something like this](https://medium.com/@andyreagan/tricks-for-coercing-pandas-into-parquet-d1137421db88) to run as a preprocessor for dates before saving as parquet as the default (or at least a flag):

```python
# Works
dbSlice['date'] = dbSlice.loc[~dbSlice.date.isnull(),'date'].apply(lambda x: x.isoformat())
dbSlice.to_parquet(outFile, index= False)
```

#### Problem description

The whole purpose of exporting the dataframe is data portability. Mangling data types is a big no-no, especially if there's no obvious way for other programs to read it. Exporting dates as an ISO string is easily interpretable by other software.

My particular use case wasn't even strange, just importing the parquet into Spark.

#### Expected Output

Any output interpretable by other software

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.2
numpy            : 1.17.3
pytz             : 2018.4
dateutil         : 2.7.2
pip              : 19.3
setuptools       : 41.0.1
Cython           : 0.27.3
pytest           : 4.3.1
hypothesis       : None
sphinx           : 1.6.6
blosc            : None
feather          : None
xlsxwriter       : 1.0.2
lxml.etree       : 4.1.1
html5lib         : 0.9999999
pymysql          : 0.8.0
psycopg2         : 2.7.6.1 (dt dec pq3 ext lo64)
jinja2           : 2.10
IPython          : 6.2.1
pandas_datareader: None
bs4              : 4.6.0
bottleneck       : 1.2.1
fastparquet      : 0.3.1
gcsfs            : None
lxml.etree       : 4.1.1
matplotlib       : 2.2.3
numexpr          : 2.6.4
odfpy            : None
openpyxl         : 2.5.12
pandas_gbq       : None
pyarrow          : 0.14.0
pytables         : None
s3fs             : None
scipy            : 1.3.0
sqlalchemy       : 1.2.1
tables           : 3.4.2
xarray           : None
xlrd             : 1.1.0
xlwt             : 1.3.0
xlsxwriter       : 1.0.2

</details>

**Comment by TomAugspurger** [comment]
Can you provide a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports.

**Comment by tigerhawkvok** [comment]
I felt like I did above (and even provided a link to another person with a similar issue) but here's another example

```python
>>> import pandas as pd
>>> import datetime as dt
>>> df = sqlToDF("select top 5 updateddate from myMSSQLTable")
>>> df.to_parquet("dummyTestTable3.parquet", index= False)
>>> df.head()
              updateddate
0 2018-10-15 12:55:49.117
1 2019-01-02 12:08:36.737
2 2019-04-22 14:16:42.757
3 2018-10-15 12:57:21.273
4 2019-04-24 13:41:51.143
```

![image](https://user-images.githubusercontent.com/165937/71299175-e54b0700-2340-11ea-8a5b-81837a901810.png)


Viewing the parquet directly:

![image](https://user-images.githubusercontent.com/165937/71299185-f136c900-2340-11ea-95f1-d5acd1dd2e92.png)


Loading it in Spark:

![image](https://user-images.githubusercontent.com/165937/71299238-470b7100-2341-11ea-8273-ad7123d79190.png)

**Comment by TomAugspurger** [comment]
You might want to try some of the options listed in https://arrow.apache.org/docs/python/parquet.html

**Comment by jorisvandenbossche** [comment]
And specifically look at https://arrow.apache.org/docs/python/parquet.html#storing-timestamps. There are options to control how datetimes are written, as not all parquet readers support all parquet data types.

**Comment by jorisvandenbossche** [comment]
Closing this as I think it's an issue with spark support of the specific timestamp type used. But @tigerhawkvok if you can further look into it and disagree with that, we can certainly re-open and further discuss!
