### ISSUE TITLE
Is `@td.skip_if_no("pathlib")` necessary?

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#30375]
Admittely this is very minor, but 
there's a few parts in the codebase (e.g. `pandas/tests/io/test_common.py`) where there is
```
@td.skip_if_no("pathlib")
```
As of `v1.0`, the minimum Python version supported will be 3.6.1, so `pathlib` will always be present as part of the standard library.

**Comment by TomAugspurger** [comment]
No necessary anymore, it can be removed.

**Comment by jreback** [comment]
closed by #30376
