### ISSUE TITLE
df.plot() with kind='scatter' and datetime on x axis bug

### ISSUE THREAD

**Issue by Sbrowneo** [pandas-dev/pandas#30391]
I noticed while helping a student that there's a bug when calling a scatter plot as a method on a DataFrame. Regardless of what the index is or what the x argument is, it appears that pandas makes the x argument into the index, and then searches for the x in the columns, where it no longer exists. When calling the same directly through matplotlib as plt.scatter, it worked properly.

<img width="1074" alt="Pandas_Error_scatter" src="https://user-images.githubusercontent.com/35703276/71311989-e7ba6900-23f3-11ea-9911-ebf4e2b1c463.png">

**Comment by MarcoGorelli** [comment]
Any chance you could post a copy-and-pasteable code example so we more easily reproduce the issue?

**Comment by Sbrowneo** [comment]
Sorry, I was helping a student whose code wasn't working, I don't have the original code myself. However I tried to recreate the error myself and I'm now getting something different: 
```python
dates=pd.date_range(start=datetime.date(2019,1,1),periods=12,freq='W')
vals=np.random.normal(0,1,len(dates))
df=pd.DataFrame({'dates':dates,'vals':vals})
df.plot(x='dates',y='vals',kind='scatter')
```
This gives me a different error:

![image](https://user-images.githubusercontent.com/35703276/71364654-dd6eab00-256a-11ea-84a3-5ae9d9d6e947.png)


However,
```python
plt.scatter(x=df['dates'],y=df['vals'])
```
does work, so I'm not sure if this is a bug or if scatter is supposed to throw an error when datetime objects are on the X axis. I'm also not sure why the error I'm getting is different from my student's.

**Comment by MarcoGorelli** [comment]
OK, thanks! I don't know about your student's error, but your one was already opened in #18755

**Comment by charlesdong1991** [comment]
take
