### ISSUE TITLE
DOC: Remove and disable wiki

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#30410]
I've been having a look at the pages on the GitHub wiki, and I think the content is mostly outdated, not very useful, and in some cases opinionated and not specific to pandas.

Not sure if there is anything worth keeping. But if there is, its not much, and I think it should be moved to the docs, so it's more visible, and we can open PRs on it, to update or delete the content.

Once the content we want to keep is in the docs, I'd diable the wiki. Personally I don't see any use case for it in our l project. The docs can contain everything. 

Any objection? Anything that someone wants to keep?

**Comment by alimcmaster1** [comment]
FYI there is an effort to move some of the content across:
https://github.com/pandas-dev/pandas/issues/30232

**Comment by jorisvandenbossche** [comment]
I think the only part that has been used / updated the last years are the "maintainers" pages. Although some of them are now also outdated with the https://github.com/pandas-dev/pandas-release repo. 

Some of the maintainers info like the "Benchmark machine" page might be fine to keep in the wiki?

**Comment by souvik3333** [comment]
I was working on #30232 but stopped working after knowing some content of wiki is not valid anymore. Please let me know or update the #30232 and I can move them from wiki to contributing.

**Comment by jbrockmendel** [comment]
+1, recently looked at it for the first time in a while and saw stuff about nose-based testing

**Comment by afeld** [comment]
Not hearing any objection, so changed the labels to reflect that.
