### ISSUE TITLE
CI: code check for " " introduced by black

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#30454]
Sometimes when we run `black` on something like

```
foo = (
    "bar "
    "baz"
)       
```

we end up with `foo = "bar " "baz"` when we would want `foo = "bar baz"`.

This is [not](https://github.com/psf/black/issues/1051) considered a bug in `black`, so is something we're currently checking for manually.  We should add it to code_checks.

**Comment by MomIsBestFriend** [comment]
take
