### ISSUE TITLE
TYPING: keywords in df.sort_values and sr.sort_values cannot be annotated

### ISSUE THREAD

**Issue by charlesdong1991** [pandas-dev/pandas#30451]
Observed in the PR #30402  and PR #27237 

Annotation seems not to be able to added for `sort_values`. If added, error message will pop up in CI:
```
pandas/core/series.py:2691: error: Signature of "sort_values" incompatible with supertype "NDFrame"
pandas/core/frame.py:4701: error: Signature of "sort_values" incompatible with supertype "NDFrame"
```

**Comment by jbrockmendel** [comment]
To make the signatures match, `by` would need to be added to Series.sort_values

**Comment by ja3067** [comment]
`by` would need to be added to `Series.sort_values` (as the first argument, so API breaking) _and_ we would need to remove the default `by=None` argument in `NDFrame.sort_values` in `generic.py`.

**Comment by jbrockmendel** [comment]
These now have types, though there is a "type: ignore" on the DataFrame method. Closable?
