### ISSUE TITLE
CLN: OrderedDict -> Dict

### ISSUE THREAD

**Issue by alimcmaster1** [pandas-dev/pandas#30469]
- Follow up from #29212

Continue work done in https://github.com/pandas-dev/pandas/pull/29923
 
As of CPython 3.6 the implementation of dict maintains insertion order.

This became a language feature in python 3.7.

Note in python 3.8 support for reversed(dict) was added - but we don't seem to use that in the use cases i've eliminated. ( OrderedDict support this)

Add code check as per comment here: https://github.com/pandas-dev/pandas/pull/29923#issuecomment-559889216

**Comment by alimcmaster1** [comment]
take

**Comment by jbrockmendel** [comment]
grepping for OrderedDict i see 29 usages outside of tests; most of those are either in doctests or in pandas.compat.numpy.function

**Comment by alimcmaster1** [comment]
@jbrockmendel think I have a branch somewhere that finishes this up - will push over the weekend.

Ali
