### ISSUE TITLE
CI: Travis failure in master because of GBQ table

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#30470]
Looks like there is a problem with GBQ. A test is finding that a table already exists. It's making Travis fail `master`. Didn't check in detail, the log is here: https://travis-ci.org/pandas-dev/pandas/jobs/629453901#L2297

@tswast mind having a look?

CC: @jreback

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/pull/30447 could have broken this

@datapythonista if you want to xfail this for now would be great.

**Comment by alimcmaster1** [comment]
Yep looks like the table added isn't removed in the teardown_class

In `test_gbq.py` :
`destination_table = DESTINATION_TABLE + "2"`

I can potentially take a look

**Comment by jreback** [comment]
ideally should fixtureze these tables to avoid this

**Comment by jreback** [comment]
hmm this is still running this test (maybe there were 2) https://travis-ci.org/pandas-dev/pandas/jobs/629507853

**Comment by charlesdong1991** [comment]
ahh, sorry about CI failure! I just take a look, and the test failed when `if_exists=='fail'`. And i just took a look at `pandas-gbq` and found out the problem.

From `pandas.to_gbq` documentation (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_gbq.html), when `if_exists=='fail'`, it says `If table exists, do nothing.`, so in the test, i leave the table size as is.
But in `pandas_gbq` documentation (https://pandas-gbq.readthedocs.io/en/latest/writing.html#writing-to-an-existing-table),  it says when `if_exists=='fail'`, should raise `TableCreationError `. I did not check the documentation from `pandas_gbq`, and somehow, this error did not show up in my local and PR test, so was overlooked.

changing the result to `TableCreationError` for `fail` should fix the problem

@datapythonista @jreback @alimcmaster1 

could be good to change the documentation as well in #30478

**Comment by datapythonista** [comment]
Can you open a PR with this @charlesdong1991 ? Thanks!

**Comment by charlesdong1991** [comment]
yeah, of course, but i saw a PR related to it was already opened by @alimcmaster1 

Or do you mean that you want a PR for doc change? @datapythonista

**Comment by datapythonista** [comment]
Sorry, didn't see the PR. But yes, creating one for the doc changes you propose sounds good.

**Comment by charlesdong1991** [comment]
sure!

**Comment by alimcmaster1** [comment]
Our docs are a copy of the [gbq ones](https://github.com/pydata/pandas-gbq/blob/master/pandas_gbq/gbq.py#L1090), i've updated the pandas side [here](https://github.com/pandas-dev/pandas/pull/30478/files). Would be good to do the same in pandas_gbq. 

Thinking we should maybe restore a [little documentation](https://github.com/pandas-dev/pandas/pull/15879/files#diff-7808955c52ebab35aaece971aa42025aL742) around this. Since these tests do not run on PRs. (Only master)
