### ISSUE TITLE
REF: window/test_moments.py

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#30486]
https://github.com/pandas-dev/pandas/blob/master/pandas/tests/window/test_moments.py

this includes testing for ewm/rolling and others. let's put into separate files to make this simpler.

**Comment by charlesdong1991** [comment]
take

**Comment by mroeschke** [comment]
@charlesdong1991 if you could find a way to reduce the runtime of some of the tests in this file while maintaining the spirit of the tests, that'd be much appreciated as well! Some of the tests in this file take a while to run.

**Comment by charlesdong1991** [comment]
will try @mroeschke
