### ISSUE TITLE
UTC offset defined through to_datetime function appears reversed 

### ISSUE THREAD

**Issue by yohplala** [pandas-dev/pandas#30518]
Hello,
Sorry to intrude, I think there might be a trouble with parsing strings containing timezone data as 'GMT+1'.

Basically, I have a list of timestamps stored as strings:

'''
0     Sat Mar 30 2019 21:00:00 GMT+0100
1     Sat Mar 30 2019 22:00:00 GMT+0100
2     Sat Mar 30 2019 23:00:00 GMT+0100
3     Sun Mar 31 2019 00:00:00 GMT+0100
'''

I add them in a dataframe as datetime object.

'''
GC['date'] = pd.to_datetime(my_timestamps)
'''

As a result, I get:

'''
0     2019-03-30 21:00:00-01:00
1     2019-03-30 22:00:00-01:00
2     2019-03-30 23:00:00-01:00
'''

As far as I googled the topic, the offset should not be reversed. It should stay +1.
See for instance this page discussing utcoffset and giving an example with Singapore timezone, that produces following output:

https://pythontic.com/datetime/datetime/utcoffset

'''
Singapore Time instance:2017-02-14 12:15:01.000099+08:00
UTC Offset for Singapore Time:8:00:00
'''

Offset is +8 hours, and if you check time difference between Singapore and UTC:
if Singapore is 5 AM the 2nd of January, UTC is 21 PM the 1str of January: the +8 offset has to be removed to get UTC timezone.

So in short, GMT+1 should be translated into +01:00 and not -01:00 as currently the case.

Coming back to my own topic, as I have DST in my timestamp list, and that I further use these timestamps as indexes in a panda dataframe, the verify_integrity check fails because it detects timestamps as being the same:

'''
14    Sun Oct 27 2019 02:00:00 GMT+0200
15    Sun Oct 27 2019 02:00:00 GMT+0100
16    Sun Oct 27 2019 03:00:00 GMT+0100
'''

becomes

'''
14    2019-10-27 02:00:00-02:00
15    2019-10-27 02:00:00-01:00
16    2019-10-27 03:00:00-01:00
'''

and if finally converted with

'''
GC['date2'] = pd.to_datetime(my_timestamps, utc=True)
'''

are written according utc time:

'''
14   2019-10-27 04:00:00+00:00
15   2019-10-27 03:00:00+00:00
16   2019-10-27 04:00:00+00:00
'''

Lines 14 & 16 have the same timestamp, which is not true.

Please, is this a bug?
Or should I do this in other way?

I thank you in advance for your attention.
Have a good day,
Bests,
Pierre

**Comment by mroeschke** [comment]
Thanks for the report. This parsing hits our dateutil parser which exhibits the same behavior. You might want to raise an issue about parsing these dates on their issue tracker:

```
In [1]: pd.to_datetime('Sat Mar 30 2019 21:00:00 GMT+0100')
Out[1]: Timestamp('2019-03-30 21:00:00-0100', tz='pytz.FixedOffset(-60)')

In [2]: import dateutil

In [3]: dateutil.parser.parse('Sat Mar 30 2019 21:00:00 GMT+0100')
Out[3]: datetime.datetime(2019, 3, 30, 21, 0, tzinfo=tzoffset(None, -3600))

In [4]: pd.Timestamp(dateutil.parser.parse('Sat Mar 30 2019 21:00:00 GMT+0100'))
Out[4]: Timestamp('2019-03-30 21:00:00-0100', tz='tzoffset(None, -3600)')
```

**Comment by yohplala** [comment]
Hello Matthew,
Thanks for the reply.
I added a comment in an existing issue. I see I havee not been the 1st to spot this trouble, and it would appear that there is no 'convention' on how interpreting the offset... Damned... I proposed to leave the choice to the coder.

https://github.com/dateutil/dateutil/issues/968

Bests,
Pierre
