### ISSUE TITLE
CI failing: Web_and_Docs (ipython 7.10.1 -> 7.11.0)

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#30527]
https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=24101&view=logs&j=5291ec4e-9543-503b-43ce-895cf0e06ba3&t=ba0a2b35-e1f8-54df-fd66-2b9fde6f4b1f

**Comment by jbrockmendel** [comment]
is the hypothesis that pinning ipython will fix this?

**Comment by charlesdong1991** [comment]
i think they are fixing it in this PR to avoid this error for now:

https://github.com/ipython/ipython/pull/12069

**Comment by jreback** [comment]
@simonjayhawkins can i make an issue to unpin this at some point

**Comment by simonjayhawkins** [comment]
> @simonjayhawkins can i make an issue to unpin this at some point

xref #30537
