### ISSUE TITLE
EA: np.array(integer_array) with no NAs

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#30522]
ATM we coerce to object, but it would be more performant (and to me at least, more intuitive) to return the underlying ndarray without the mask.  I guess this sacrifices consistency.

**Comment by TomAugspurger** [comment]
I think dtype consistency is more important.

**Comment by jreback** [comment]
agree with @TomAugspurger 

users won’t do this very often as we r handling the dispatch of functions anyhow

we might want to make the data & mask publicly accessible though thru attributes in case you really do want to drop to numpy (eg we have this exact case in another PR where we want to pass the data and mask to cython for conversion to date times and having to peer inside the container is not great)
