### ISSUE TITLE
Unpin ipython 7.10.1 once ipython 7.11.1 released

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#30537]
xref https://github.com/cython/cython/pull/3291#issuecomment-569403562

**Comment by Carreau** [comment]
New version on PyPI (soon on conda) you should be able to un-pin;  or at least instead of pinning `<=7.10.1`, pin `!=7.11.0`. 

`<=7.10.1` seem regardless wrong also as there is also a `7.10.2`
