### ISSUE TITLE
Re-Opening:  Pivot Table Margins aren't correctly showing NaN values despite dummy variables

### ISSUE THREAD

**Issue by pshMsGsAZL2n07ohWBCAGX9cC** [pandas-dev/pandas#30549]
I'm re-opening the issue[ #30351](https://github.com/pandas-dev/pandas/issues/30351), as I don't believe it's a duplicate and it occurs regardless of graphing.  Please see this prior issue for all the background.  [Tom, I posted some clarifying comments about a week ago on the original issue, but perhaps they got lost in the holiday rush.]  I'm relatively new to github, so apologies if I didn't follow the appropriate procedure.  Thank you.

**Comment by TomAugspurger** [comment]
We'll just reuse https://github.com/pandas-dev/pandas/issues/30351
