### ISSUE TITLE
calculate business hours between two time stamp

### ISSUE THREAD

**Issue by ashishmeta** [pandas-dev/pandas#30597]
<img width="488" alt="df" src="https://user-images.githubusercontent.com/55054825/71637854-1991c200-2c75-11ea-8090-b21ccb13ba93.PNG">

I have to calculate business hours between two time stamp. 
Challenge is Monday and Saturday have different business hours than rest of the weekdays.

Monday starts at 2:30 AM and ends at 11:59 PM. Saturday starts at 00:00 AM and ends at 6:30 AM.
Rest of the weekdays starts at 00:00 AM and ends at 11:59 PM. 
* All times are in IST.

**Comment by MarcoGorelli** [comment]
Seems like a question more appropriate for [StackOverflow](https://stackoverflow.com/questions/tagged/pandas)

**Comment by ashishmeta** [comment]
Hi,

I have posted this comment. But received any response till date.

Regards,
Ashish

**Comment by jreback** [comment]
currently this is out of scope for pandas 

what you are asking is actually somewhat non trivial - if an implementation was contributed we likely would accept, but many other higher priorities
