### ISSUE TITLE
DEPR: Remove pandas.datetime

### ISSUE THREAD

**Issue by ryankarlos** [pandas-dev/pandas#30610]
A follow up issue from #30296 , where it was discussed that pd.datetime should also be deprecated to only allow imports directly from datetime

```
>>> import pandas as pd
>>> pd.datetime
<class 'datetime.datetime'>
```

**Comment by ryankarlos** [comment]
take

**Comment by abhinavgaur** [comment]
So, only places where I need to make change in my past codes is 

- `from datetime import datetime` and 

- replace `pd.datetime` with `datetime `?
