### ISSUE TITLE
'Categorical' from output of 'factorize' has different encoding

### ISSUE THREAD

**Issue by david-cortes** [pandas-dev/pandas#30618]
If I call `pd.Categorical` using the results of `pd.factorize`, sometimes the encodings produced by them will be different:
```python
import pandas as pd, numpy as np

df = pd.DataFrame({
    "col1" : ["S","C","S","S","Q"]    
})
df["col1"] = pd.Categorical(df["col1"])
encoded, factors = pd.factorize(df["col1"])
recoded = pd.Categorical(df["col1"], factors).codes
```
I would expect in this case  that all three objects (`encoded`, `recoded`, and the original) will have the same encoding, but these are the results:
```python
df.col1.cat.codes.values
```
```
>>> array([2, 0, 2, 2, 1], dtype=int8)
```
```python
encoded
```
```
>>> array([0, 1, 0, 0, 2])
```
```python
recoded
```
```
>>> array([2, 0, 2, 2, 1], dtype=int8)
```

The issue can be solved by using `pd.Categorical` with `factors.to_numpy()` instead, but I think it'd be very reasonable to assume that the output from `factorize` is the expected input to `Categorical`.

**Comment by TomAugspurger** [comment]
I think things look correct here. You have an unordered categorical, so I wouldn't rely the relationship between the values and the codes.

**Comment by david-cortes** [comment]
@TomAugspurger but wouldn't it make more sense for `Categorical` and `factorize` to play along? e.g. `pd.Categorical.from_codes(encoded, factors)` (does not give the original input) instead of `factors[encoded]` (gives the original input).

Otherwise, what would be the recommended route when you want to encode a column and save the factors for reproducing the encoding later if not `factorize`?

**Comment by TomAugspurger** [comment]
I'm not sure if the guarantees we make on the codes in factorize and
categorical are compatible with eachother.

You might look at Categorical._from_factorized for inspiration.

**Comment by TomAugspurger** [comment]
@david-cortes anything else to do here? I think that the two requirements that

1. The order of the codes in factorize matches the order of the *values*
2. The order of the codes in Categorical matches the order of the *categories*

are fundamentally at odds with eachother.

**Comment by david-cortes** [comment]
But why does `Categorical` need to take the order given by the categories rather than the index of the categories? I mean, the docs say this:
```
categories : index-like, optional
  The categories for the categorical. Items need to be unique. If the categories are not
  given here (and also not in dtype), they will be inferred from the data.
```
(Particularly the part about `index-like`)

But if I pass the following:
```
present_enc = ['S', 'C', 'Q']
available_enc = ['S', 'C', 'R', 'Q']
categ_index = pd.CategoricalIndex(present_enc, categories=available_enc)
categ_index[2] == 'Q'

index = pd.Index(present_enc)
index[2] == categ_index[2]
```
Then the result from `Categorical(data, categ_index)` will differ from `Categorical(data, index)` despite the entries matching, and will not match with the order given by subsetting `categ_index`.

**Comment by mroeschke** [comment]
I think this behavior is longstanding so closing
