### ISSUE TITLE
ENH: Create a devcontainer.json env to work with VS Code in Containers

### ISSUE THREAD

**Issue by yehoshuadimarsky** [pandas-dev/pandas#30614]
VS Code has a great feature where you can work on a repo fully within a Docker container, either on your computer (called Remote - Containers) or remotely on Azure hosted by them (called VS Code Online). This could be particularly useful for setting up a quick dev environment to work on the pandas codebase, and not have to manually go through the setup steps in the [docs](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#working-with-the-code).

Per the VS Code docs (https://code.visualstudio.com/docs/remote/containers and https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring) you can create a `.devcontainer.json` file in the root of the repo that will contain everything needed to setup the environment, similar to the conda `environment.yml` file. You can also create a DockerFile inside a `devcontainer` folder to use with the `devcontainer.json` file.

I will try to put something together for this, figured I'd first start an issue here so that if anyone else is working on this we can collaborate and not duplicate our work.

**Comment by yehoshuadimarsky** [comment]
Maybe use this as a starting point: https://github.com/microsoft/vscode-dev-containers/tree/master/containers/python-3-miniconda

**Comment by WillAyd** [comment]
sounds Interesting - would be curious to see how it works if you push a PR

**Comment by yehoshuadimarsky** [comment]
@WillAyd just pushed a PR, check it out.
