### ISSUE TITLE
pandas.DataFrame.rolling.apply Can't deal with np.nan

### ISSUE THREAD

**Issue by LiuHang9527** [pandas-dev/pandas#30634]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd
import numpy as np

df = pd.DataFrame({'a':[1,2,3,4,5], 'b':[10,9,8,7,np.nan], 'c':[8,7,6,5,4], 'd':[4,np.nan,6,7,8]})
df

def sum_(data):
    return data.sum()
res= df.rolling(3,center=False).apply(sum_,raw=True)
res
```
#### Problem description

[pd.DataFrame.rolling.apply    Can't deal with np.nan]

**Comment by WillAyd** [comment]
What do you mean by can't deal with `np.nan`?

**Comment by LiuHang9527** [comment]
- [ ] 

> 你是什​​么意思不能应付`np.nan`？

![1-3](https://user-images.githubusercontent.com/50090308/71702447-8b4f4480-2e0a-11ea-8aec-583d9e898282.png)

I am not sure how to show my dataframe at this moment, but if you look at 4d, 2d, 3d which are all np.nan not ignored by pandas.rolling

**Comment by WillAyd** [comment]
The screenshot looks OK. IIUC correctly you might just want to look at specifying `min_periods`

**Comment by LiuHang9527** [comment]
The problem is not re
![111](https://user-images.githubusercontent.com/50090308/71702998-63151500-2e0d-11ea-814e-9449d1e2ebef.png)
solved

**Comment by LiuHang9527** [comment]
![111](https://user-images.githubusercontent.com/50090308/71703015-76c07b80-2e0d-11ea-8b5b-1eb5681ede3d.png)
The problem is not resolved

**Comment by jreback** [comment]
@LiuHang9527 please read the documentation, its not even clear what you are asking. if you think there is a bug, then you need to be very clear about what the expected result is.

note that using .apply in this way is very inefficient.

```
In [14]: df.rolling(3,center=False, min_periods=2).apply(sum_,raw=True)                                                                                                                                                     
Out[14]: 
      a     b     c     d
0   NaN   NaN   NaN   NaN
1   3.0  19.0  15.0   NaN
2   6.0  27.0  21.0   NaN
3   9.0  24.0  18.0   NaN
4  12.0   NaN  15.0  21.0

In [15]: df.rolling(3,center=False, min_periods=2).apply(sum_,raw=False)                                                                                                                                                    
Out[15]: 
      a     b     c     d
0   NaN   NaN   NaN   NaN
1   3.0  19.0  15.0   NaN
2   6.0  27.0  21.0  10.0
3   9.0  24.0  18.0  13.0
4  12.0  15.0  15.0  21.0
```

the difference is how numpy and pandas deal with nans. ```data.sum()``` is a *numpy* array and thus sum *always* includes nans, if you *really* really want to use apply, try using ``.nansum``

**Comment by LiuHang9527** [comment]
> @LiuHang9527 please read the documentation, its not even clear what you are asking. if you think there is a bug, then you need to be very clear about what the expected result is.
> 
> note that using .apply in this way is very inefficient.
> 
> ```
> In [14]: df.rolling(3,center=False, min_periods=2).apply(sum_,raw=True)                                                                                                                                                     
> Out[14]: 
>       a     b     c     d
> 0   NaN   NaN   NaN   NaN
> 1   3.0  19.0  15.0   NaN
> 2   6.0  27.0  21.0   NaN
> 3   9.0  24.0  18.0   NaN
> 4  12.0   NaN  15.0  21.0
> 
> In [15]: df.rolling(3,center=False, min_periods=2).apply(sum_,raw=False)                                                                                                                                                    
> Out[15]: 
>       a     b     c     d
> 0   NaN   NaN   NaN   NaN
> 1   3.0  19.0  15.0   NaN
> 2   6.0  27.0  21.0  10.0
> 3   9.0  24.0  18.0  13.0
> 4  12.0  15.0  15.0  21.0
> ```
> 
> the difference is how numpy and pandas deal with nans. `data.sum()` is a _numpy_ array and thus sum _always_ includes nans, if you _really_ really want to use apply, try using `.nansum`

Thank you very much, I understand, this is just an example that comes to my mind
