### ISSUE TITLE
Index comparison doesn't return index

### ISSUE THREAD

**Issue by giuliobeseghi** [pandas-dev/pandas#30657]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

s = pd.Series([1, 2, 3, 4, 5])
t = s.copy()

print(s.index == t.index)
# np.array([True, True, True, True, True])
```
#### Problem description
Comparing two indices returns an `np.ndarray`, and not another index. The behavior is different from series and dataframes. Is it a bug?

#### Expected Output
The output I expect should be achievable with
```python
pd.Index(s.index == t.index)
```

Possibly, the type of the index should be 'bool' (compare it with series, e.g. `s == t`).
It seems that `pd.Index(s.index == t.index).astype(bool)` doesn't return an index of bool either.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.3
numpy            : 1.17.4
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 42.0.2.post20191203
Cython           : 0.29.14
pytest           : 5.3.2
hypothesis       : 4.54.2
sphinx           : 2.3.0
blosc            : None
feather          : None
xlsxwriter       : 1.2.6
lxml.etree       : 4.4.2
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.10.2
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : 1.3.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.2
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 3.0.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : 0.4.0
scipy            : 1.3.2
sqlalchemy       : 1.3.11
tables           : 3.6.1
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.6

</details>

**Comment by TomAugspurger** [comment]
We don't have a boolean index dtype. And even if we did, I think changing this now is out of scope for pandas.

**Comment by jreback** [comment]
agreed a boolean indexer is almost always what you want

**Comment by giuliobeseghi** [comment]
Ok. I raised it because I couldn't call `(s.index == t.index).all()`, and I expected I could. But I can do the same with `all(s.index == t.index)`.

Is there a better way to make sure that two series have exactly the same index?

**Comment by giuliobeseghi** [comment]
Sometimes I just don't really understand why the behavior of pd.Index is different from series and df. I know it's not an Ndframe, but to me it kind of looks like an enhanced column of a DataFrame. Was it designed this way historically or was there a proper reason to differentiate it from DataFrames and Series?
