### ISSUE TITLE
CLN: de-privatize _parsers and _engines in pandas/core/computation and rename to something more descriptive

### ISSUE THREAD

**Issue by hwalinga** [pandas-dev/pandas#30681]
As a followup from #28215 

_parsers and _engines as used in the code for the `.query` and `.eval` methods should be de-privatized and named to something more informative. 

```
_engines: Dict[str, Type[AbstractEngine]] = {
    "numexpr": NumExprEngine,
    "python": PythonEngine,
}
```

```
_parsers = {"python": PythonExprVisitor, "pandas": PandasExprVisitor}
```

@jreback

**Comment by jbrockmendel** [comment]
theres are now ENGINES and PARSERS i think

**Comment by hwalinga** [comment]
Correct. Well I guess this can be closes then!

I also wouldn't think what a better name for those would be. I think only parser was a bit too generic term. Maybe ENGINE_PARSERS, AST_VISITOR?

ENGINES is probably good. What do you think?

**Comment by jbrockmendel** [comment]
These are pretty deeply internal, i wouldnt worry about it
