### ISSUE TITLE
BooleanArray, StringArray value_counts na_value

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#30685]
```
arr = pd.array([True, False, np.nan])

>>> arr
<BooleanArray>
[True, False, NA]
Length: 3, dtype: boolean

>>> arr.value_counts(dropna=False)
True     1
False    1
False    1
dtype: int64
```

Instead of two False entries, one of them should be pd.NA right?  cc @TomAugspurger 

```
arr = pd.array(['foo', 'bar', None])

>>> arr.value_counts(dropna=False)
foo    1
bar    1
NaN    1
dtype: int64
```

The NaN should be pd.NA right?

Side-note: the defaults for dropna are not consistent across our EAs

**Comment by jorisvandenbossche** [comment]
That's clearly a bug in the BooleanArray.value_counts implementation. And indeed, we should use pd.NA instead of np.nan in the object index.

**Comment by jorisvandenbossche** [comment]
@jbrockmendel you have an open PR that relates to EA.value_counts. Does that in some way also fixes this? (otherwise I can have a look at this issue)

**Comment by jbrockmendel** [comment]
> Does that in some way also fixes this? (otherwise I can have a look at this issue)

No, that shouldn't change any behavior.

I think the fix is fairly straightforward for BooleanArray, on L572 `np.concatenate([index, np.array([np.nan], dtype=object)]), dtype=object)` changing the `np.nan` to `pd.NA` should do the trick.  Or possibly use `self.dtype.na_value` like IntegerArray.
