### ISSUE TITLE
CLN: Move axis resolvers from core/generic.py to core/computation

### ISSUE THREAD

**Issue by hwalinga** [pandas-dev/pandas#30683]
As a followup from #28215

Moving the axis resolvers to core/computation

@jreback

**Comment by hwalinga** [comment]
ABCSeries is not the correct type hint. It probably should be Union["Series", MultiIndex]

**Comment by gugazan** [comment]
Wich functions exactly do you want to move to core/comptation ? Besides de obvious `_get_axis_resolvers()` does anything else needs to be moved ?

**Comment by lucaslarios** [comment]
take

**Comment by lucaslarios** [comment]
Does this issue still remain relevant?

**Comment by mroeschke** [comment]
Dont think this ticket is relevant anymore so closing
