### ISSUE TITLE
Nightly Builds

### ISSUE THREAD

**Issue by marco-neumann-jdas** [pandas-dev/pandas#30730]
Until 2019-11-02, https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/ contains nightly builds of pandas for different platforms. Is there any chance that this will be continued? I am asking because nightly testing is very helpful for some downstream artifacts to discover unintentional breaking chances or regressions before a new pandas version gets released. Building pandas from source on CI takes very long though, up to a duration where it gets kinda unpractical for downstream projects.

**Comment by jreback** [comment]
looks like the nightly wheel build has been failing

https://travis-ci.org/MacPython/pandas-wheels/builds

i don’t think i get status emails on this any more
not sure why

cc @pandas-core if someone can look

**Comment by jreback** [comment]
@pandas-dev/pandas-core

**Comment by datapythonista** [comment]
I can have a look, but I wasn't aware we had this. If it's not in our CI, who is maintaining those builds?

Probably I'm missing something, but if the idea is providing wheels, shouldn't it be better to generate them from our own builds? I think our CI is already too complex to also have to maintain builds elsewhere.

**Comment by jreback** [comment]
wheel building is a separate animal and non trivial
we also need a whole bunch of workers to do this
for all of these reasons it is a separate repo

these are documented as part of the release process

i suppose you could do the nightly builds as github actions

**Comment by datapythonista** [comment]
Thanks for the info, will check the release docs.

**Comment by TomAugspurger** [comment]
I was also going to take a look at the wheel building stuff on Tuesday in preparation for the RC.

**Comment by WillAyd** [comment]
ref https://github.com/pandas-dev/pandas-release/issues/20 I do think switching over to Actions would be possible; I've done something similar for another project https://github.com/innobi/pantab/pull/37/files sans the manylinux piece

**Comment by TomAugspurger** [comment]
Should be fixed by https://github.com/MacPython/pandas-wheels/pull/68
