### ISSUE TITLE
`pandas.DataFrame.explode()` combines rows with repeated index values

### ISSUE THREAD

**Issue by gsganden** [pandas-dev/pandas#30748]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

df = pd.DataFrame({"A": [[1, 2], [3, 4]], "B": ["x", "y"]}, index=[0, 0])
df.explode("A")
```

Output:

```
   A  B
0  1  x
0  2  x
0  3  x
0  4  x
0  1  y
0  2  y
0  3  y
0  4  y
```

#### Problem description

We are getting rows with e.g. `A=3` and `B=x`, which never appears in the original data. The `.explode()` method appears to be effectively combining rows with the same index value before splitting them, which is surprising at least to me.

#### Expected Output

```
   A  B
0  1  x
0  2  x
0  3  y
0  4  y
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.14.77-70.82.amzn1.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : C.UTF-8
LANG             : None
LOCALE           : en_US.UTF-8

pandas           : 0.25.3
numpy            : 1.17.2
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 41.2.0
Cython           : 0.28.4
pytest           : 5.2.0
hypothesis       : 4.38.1
sphinx           : 2.2.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.7.7 (dt dec pq3 ext lo64)
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : 1.3.1
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.15.1
pytables         : None
s3fs             : 0.4.0
scipy            : 1.3.1
sqlalchemy       : 1.3.10
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by jreback** [comment]
can u try this on master

**Comment by gsganden** [comment]
I get the expected result on master:

```
>>> import pandas as pd
>>> df = pd.DataFrame({"A": [[1, 2], [3, 4]], "B": ["x", "y"]}, index=[0, 0])
>>> df.explode("A")
   A  B
0  1  x
0  2  x
0  3  y
0  4  y
```

<details>

```
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.0.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.utf-8
LANG             : en_US.utf-8
LOCALE           : en_US.UTF-8

pandas           : 0.26.0.dev0+1658.gaf4e2ce19
numpy            : 1.17.4
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 44.0.0.post20200106
Cython           : 0.29.14
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.9.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
```

</details>
