### ISSUE TITLE
datatype converstion(.astype) error for bool type.

### ISSUE THREAD

**Issue by DSivaji** [pandas-dev/pandas#30777]
Datatype converstion(.astype) error for bool type.

```python
import pandas as pd
pd.__version__

df_1 = pd.DataFrame({'c_bool': [None, None, True, True, True,False]})
print(df_1['c_bool'].dtypes)
df_1['c_bool'] = df_1['c_bool'].astype(bool)
print(df_1['c_bool'].dtypes)
df_1

# '0.24.2'
# object
# bool
#   c_bool
# 0   False
# 1   False
# 2    True
# 3    True
# 4    True
# 5   False
```
I have a column that has some None/True/False values. Initially, the datatype of that column is 'object'. After I convert it to bool as datatype, Null values are converting to False. Which is not expected behavior.

**Comment by tanmay1618** [comment]
I was going through this issue.  I came to know that it is a numpy astype function error which converts None to False. Can some please suggest next steps to solving this ?

**Comment by gfyoung** [comment]
Let's take a step back here: when converting to boolean, is there actually a `NULL` value for booleans?  I understand the conversion might have surprised you, but `None` is a false-y value.

**Comment by tanmay1618** [comment]
On replacing None with numpy.nan, it throws correct result.

**Comment by gfyoung** [comment]
`nan` is also a false-y value though, so I'll ask again: is there actually a NULL value for booleans?

**Comment by tanmay1618** [comment]
Since, we are going by numpy's definition, it treats nan as a NULL value and None as False. We can go ahead accepting this behaviour from numpy.

**Comment by gfyoung** [comment]
> We can go ahead accepting this behaviour from numpy.

@DSivaji : Does that work for you?  Otherwise, I might suggest bringing this to `numpy`'s attention

**Comment by DSivaji** [comment]
I think this should bring it to the numpy or pandas should have a wrapper to take care of this behavior.

**Comment by gfyoung** [comment]
I would recommend you check with `numpy` first to see what they say.  When it comes to type-casting like this, we generally just rely on what they do.

If not, you are more than welcome to try to implement a wrapper.  I'm not sure how straightforward that is going to be though.

**Comment by jreback** [comment]
the BooleanArray extension type already handles this as it’s NA preserving

pass dtype=‘boolean’ on construction 

this is new in 1.0

you are welcome to do something in the numpy side but pandas already has a plan for this
