### ISSUE TITLE
Try supporting Python 3.6.0

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#30794]
In https://github.com/pandas-dev/pandas/pull/29212, we bumped the minimum Python to 3.6.1. @datapythonista mentioned an issue with 3.6.0 at https://github.com/pandas-dev/pandas/pull/29212#issuecomment-551370118

> Seems like Python 3.6 has something (I guess a bug) causing the error TypeError: only integer scalar arrays can be converted to a scalar index when converting strings to bytes in some of our cases.

I vaguely recall a few issues with 0.25.x requiring a point release of python 3.5. We should see if we can support 3.6.0 to save some headaches down the road.

**Comment by jreback** [comment]
really? why the effort here? this seems not worth it.

**Comment by WillAyd** [comment]
IIRC I think bumping numpy to 1.15 might have solved the same issue we were trying to solve in bumping to 3.6.1 so maybe it does just work now, but agreed with Jeff that at the same time it's not worth a lot of effort

For 0.25 we required 3.5.2 as a min and I don't recall coming across any issues or complaints from that

**Comment by TomAugspurger** [comment]
> For 0.25 we required 3.5.2 as a min and I don't recall coming across any issues or complaints from that

I recall a few (didn't find any in a search) though I think that was in part due to some ubuntu version having 3.5.0 by default.

Anyway, we use 3.6.1+ features like typing.ChainMap, so not a high enough priority.
