### ISSUE TITLE
DOC: Move import conventions from wiki to docs

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#30808]
The section about imports here: https://github.com/pandas-dev/pandas/wiki/Code-Style-and-Conventions#imports-aim-for-absolute

Can be moved to the code style guide in the documentation: https://dev.pandas.io/docs/development/code_style.html

This way we can remove the page from the wiki, that is mostly outdated.

**Comment by souvik3333** [comment]
Take

**Comment by jorisvandenbossche** [comment]
I think how that section is written is a bit outdated in the Python 3 world

**Comment by datapythonista** [comment]
@souvik3333 if you want to change that section a bit to avoid references to Python 2/3 stuff when moving it, that would be great. Let me know if you need help.
