### ISSUE TITLE
Request: isnotnull() type argument for selections 

### ISSUE THREAD

**Issue by JackMcCoy** [pandas-dev/pandas#30804]
Hey all, feature request here.

While I'm exploring data in the shell, I am _constantly_ forgetting the tilde prefix to a isnull() argument. There's something about the way I conceptualize the data and how I use pandas - "Okay, I have a dataframe, now I select a subset... this column, with variables that are not null.. Oh sh*t (backarrow, backarrow, backarrow)." This happens DOZENS of times a day. I've forked a copy of the code and am looking at implementing something for myself, but I thought I'd put this up and see if there's any interest in it. Yeah, it's redundant, but I think it would be an improved design and there are other redundant functions...

What do you think?

**Comment by jreback** [comment]
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.notna.html?highlight=notna#pandas.DataFrame.notna is what you are looking for (isnull/notnull are just aliases)

```df[df.a.notnull()]``
