### ISSUE TITLE
date_range calculates ranges off by one bin when passing period

### ISSUE THREAD

**Issue by lcandeago** [pandas-dev/pandas#30818]
#### Code Sample, a copy-pastable example if possible

```python

import pandas as pd
start_t = pd.Timestamp('2008-11-24')
end_t = pd.Timestamp('2008-12-08')
print(end_t)
# 2008-12-08 00:00:00
diff = end_t-start_t
dates = pd.date_range(start_t, end_t, periods=bins, tz=None)
diff = dates[1] - dates[0]
print(diff)
# 0 days 03:23:38.181818
wrong = start_t + 100*diff
# 2008-12-08 03:23:38.181818100

correct = start_t + 99*diff
#2008-12-07 23:59:59.999999919 
```
#### Problem description
the date range is created with the frequency of 101 bins when passing period = 100.

#### Expected Output
multiplying the time length of a bin by the number of bins should return the end date.
instead it returns the end date +1
#### Output of ``pd.show_versions()``

<details>
NSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.1.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.2.13-arch1-1-ARCH
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.3
numpy            : 1.18.0
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 42.0.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by parkerdgabel** [comment]
take

**Comment by parkerdgabel** [comment]
When I run the code that you provided, dates has a size of 100. So it is making the proper number of bins. I am not sure what the problem is exactly. I think that multiplying the interval by 99 should return the last date.

**Comment by lcandeago** [comment]
Thanks for testing this. 
I'll try to explain better: if i set a number of periods, say 100, I expect the frequency to be
`expected_frequency = (end_t-start_t)/100`
and hence that 
`expected_frequency*100=end_t-start_t`
`
Maybe I've just misunderstood the docs and interpreted the period parameter like the number of bins of an histogram, as if date_range would generate n equally spaced intervals when passing n as period parameter and not n-1 intervals. 
The actual meaning for the period parameter is generate n equally spaced dates (hence n-1 equally spaced time intervals). This was not clear to me from the docs.

Feel free to close. Thanks for your time!

**Comment by parkerdgabel** [comment]
No problem!
