### ISSUE TITLE
like old issue #2936:  df.apply(foo) will run twice at the first row

### ISSUE THREAD

**Issue by kerwin6182828** [pandas-dev/pandas#30815]
#### some example....

```python
def foo(row):
    status = row.get("status")
    print(status)
    status = True if status==1 else False
    row["status"] = status
    return row
    
df = pd.DataFrame([{"name":"bob", "status":1}])
df.apply(foo, axis=1)

>>>>>>>> output:
1
True
```
#### Problem description
today, I have a problem  that df.apply(foo) will run twice at the first row like old issue #2936.
I read a lot of explanations, but still can't find some help. As I wrote above, when df just have 1 row and then apply function will run twice at this row lead to print diffierent values.
 (It just modified my original value "1" to "True",  but it confused me a lot...)

I am wandering how to handle this issue, and is this a pandas bug?

thanks a lot~~

**Comment by jreback** [comment]
you need to show_versions()

**Comment by kerwin6182828** [comment]
> you need to show_versions()

pandas           : 0.25.3
numpy            : 1.17.0

python           : 3.7.4.final.0
python-bits      : 64
OS               : Darwin

Did you have the same result as me ? 
（I have to face to this situation many times, so it really bother me ...）
