### ISSUE TITLE
DOC: Fix indentation in docstring example

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#30830]
Not sure why we didn't see it before, but the example in the first code block of the docstring guidelines seem to be missing the indentation: https://pandas.io/docs/development/contributing_docstring.html#about-docstrings-and-standards

We should fix it, and indent the function properly: https://github.com/pandas-dev/pandas/blame/master/doc/source/development/contributing_docstring.rst#L25

**Comment by MomIsBestFriend** [comment]
take
