### ISSUE TITLE
Feature Request: context manager in which NaN equals NaN

### ISSUE THREAD

**Issue by fujiaxiang** [pandas-dev/pandas#30834]
I'm not really sure whether this is the correct place to request for this (maybe it should be numpy?), but here it is.

Often times when we deal with data we may want to compare two `Series` or `DataFrames`. In pandas/numpy standard and many other, if not all, programming standards, `NaN == NaN` yields ``False``. 

However, sometimes we really mean to make them equal. Say we are comparing two raw datasets. In this case it'd be nice if we have a context manager within which `NaN == NaN` yields True.
```python
>>> import numpy as np
>>> import pandas as pd
>>> pd.__version__
'0.25.3'

>>> s1 = pd.Series([1, 2, np.nan])
>>> s2 = pd.Series([1, 3, np.nan])

# Current behavior
>>> s1 == s2
0     True
1    False
2    False
dtype: bool

# Desired feature
>>> with pd.make_nans_equal():
>>>     print(s1 == s2)
0     True
1    False
2     True
dtype: bool
```

In addition, it'd be nice if we can configure the proposed `pd.make_nans_equal()` with parameters to set if we want `NaN == None` to be ``True`` too.

**Comment by jbrockmendel** [comment]
Would `s1.equals(s2)` handle your use case?

**Comment by fujiaxiang** [comment]
> Would `s1.equals(s2)` handle your use case?

Not really. I thought of this while I'm coding up the `df.differences()` feature mentioned here (#30429).
I need to identify exactly where the differences are. So far I'm doing this with a workaround like this:
```python
mask = (self != other) | (self.isna() & other.isna())
```
However this has a slight flaw that ``None`` is also considered equal to ``np.nan``.

Anyway I think this goes beyond this particular example. I've had other work experience when I find this feature would be handy. For example, in `df.apply()` with custom function, I may want to compare certain values and do things differently. With a context manager like this, I can achieve desired behaviors with each.

More importantly, I can reuse my exact same code for different kind of behaviors I want, without having to do lots of if-else at different places inside my code. I'm also quite confident that a lot of scripts, including some implementations of pandas itself, would be cleaner if we have such a context manager.

**Comment by jbrockmendel** [comment]
This might be useful, but would need to be implemented in numpy

**Comment by mroeschke** [comment]
Yeah agreed that this would ideally be implemented by numpy for pandas to use; therefore, closing as immediately out of scope for pandas unless numpy implements this.
