### ISSUE TITLE
Value Counts with categorical dtypes has unexpected behavior

### ISSUE THREAD

**Issue by datajanko** [pandas-dev/pandas#30844]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame({"A": [1, 2, 3], "B":[2, 3, 4], 
                   "C": pd.Categorical(["A", "B", "C"]), 
                   "D": pd.Categorical(["B", "C", "D"])})
df.dtypes.value_counts()
```
gives
```
int64       2
category    1
category    1
dtype: int64
```
#### Problem description

I would have expected to have an aggregated count for categories here. This also seems to be related to groupby on dtypes

#### Expected Output
```
int64       2
category    2
dtype: int64
```
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-1054-aws
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.3
numpy            : 1.17.4
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 42.0.2
Cython           : 0.29.14
pytest           : 5.3.2
hypothesis       : 4.36.2
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.2.6
lxml.etree       : 4.4.2
html5lib         : 1.0.1
pymysql          : 0.9.3
psycopg2         : 2.8.4 (dt dec pq3 ext lo64)
jinja2           : 2.10.3
IPython          : 7.9.0
pandas_datareader: 0.8.1
bs4              : 4.8.1
bottleneck       : 1.3.1
fastparquet      : 0.3.2
gcsfs            : None
lxml.etree       : 4.4.2
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 3.0.2
pandas_gbq       : 0.13.0
pyarrow          : 0.11.1
pytables         : None
s3fs             : 0.4.0
scipy            : 1.3.2
sqlalchemy       : 1.3.10
tables           : 3.6.1
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : 1.2.6

</details>

**Comment by TomAugspurger** [comment]
The behavior on master is correct, those are different dtypes

```python
In [4]: df.C.dtype == df.D.dtype
Out[4]: False
```

**Comment by datajanko** [comment]
Okay, thanks for pointing out that `df.C.dtype` is `CategoricalDtype(categories=['A', 'B', 'C'], ordered=False)` and not 'category'.  I fell (again) for the representation trap here. I see that the behavior is correct, but it's still unexpected (at least in my opinion).
