### ISSUE TITLE
read_fwf reading large numbers as object dtype

### ISSUE THREAD

**Issue by TonyFhh** [pandas-dev/pandas#30849]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
>>> pd.read_fwf(r'D:\Other\ggg.txt', header=None, widths =[26,3,3,26])
                            0   1    2                     3
0  +0000000000000000000000000 NaN  CCY        30000000000000
1  +0077800000000000000000000 NaN  ABF  18244030000000000000

>>> pd.read_fwf(r'D:\Other\ggg.txt', header=None, widths =[26,3,3,26])
                            0   1    2                           3
0  +0000000000000000000000000 NaN  CCY  +0000000000030000000000000
1  +0077800000000000000000000 NaN  ABF  +0000018544030000000000000

>>> pd.read_fwf(r'D:\Other\ggg.txt', header=None, widths =[26,3,3,26])[3]
0    +0000000000030000000000000
1    +0000018544030000000000000
Name: 3, dtype: object
```
#### Problem description
I have a fixed width file with numbers specifications up to 25 characters with a 1 character sign in front. Normally for small numbers these numbers read properly. As the numbers get bigger as shown above, read_fwf starts to read them as objects even though they are numbers. Attempting to convert said column series with bigger number results in overflow error.

This may cause incompatibility of dtypes when the field is expected to be numerical. read_fwf could process the column as np.float64 to maintain the numerical dtype if np.int64 is not compaitable.

#### Expected Output
```python
>>> pd.read_fwf(r'D:\Other\ggg.txt', header=None, widths =[26,3,3,26])[3].astype(np.float64)
0    3.000000e+13
1    1.854403e+19
Name: 3, dtype: float64
```

</details>

**Comment by WillAyd** [comment]
18244030000000000000 will have no precision at all as a 64 bit float so I don't think that would be very useful. The dtype being object maintains that number as a Python which allows for arbitrary size without loss of precision

**Comment by jeffencillo** [comment]
any solution with this issue? Im facing the same problem

**Comment by WillAyd** [comment]
This is more of a usage question than a bug. These numbers exceed the storage limit of a 64 bit integer, so coercing to Python objects (which have no limit) is the correct behavior
