### ISSUE TITLE
pandas.util.testing no longer imported with pandas

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#30869]
0.25.3

```python
In [1]: import pandas

In [2]: pandas.util.testing
Out[2]: <module 'pandas.util.testing' from '/private/tmp/pandas/util/testing.py'>
```

1.0

```python
In [1]: import pandas

In [2]: pandas.util.testing
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-968e027d039f> in <module>
----> 1 pandas.util.testing

AttributeError: module 'pandas.util' has no attribute 'testing'
```

**Comment by jreback** [comment]
hmm it i don’t think is a problem
and wouldn’t do anything about it

**Comment by jorisvandenbossche** [comment]
It's perfect legitimate usage pattern of util.testing, and it's also easy to fix (we can still import it while hiding the warning)

**Comment by jreback** [comment]
> It's perfect legitimate usage pattern of util.testing, and it's also easy to fix (we can still import it while hiding the warning)

missing the point - why should be supporting a non explicit import? i would simply break this

**Comment by jorisvandenbossche** [comment]
> why should be supporting a non explicit import?

Because we have always supported this?

**Comment by jreback** [comment]
> > why should be supporting a non explicit import?
> 
> Because we have always supported this?

i disagree

it doesn’t matter if it’s easy

**Comment by jorisvandenbossche** [comment]
> >  Because we have always supported this?
>
> i disagree

I am assuming that your "I disagree" is about this being a good reason to keep supporting it? Because AFAIK, it's a *fact* that we have always supported this.

**Comment by jreback** [comment]
> > > Because we have always supported this?
> > 
> > 
> > i disagree
> 
> I am assuming that your "I disagree" is about this being a good reason to keep supporting it? Because AFAIK, it's a _fact_ that we have always supported this.

my point is that @TomAugspurger did enough on the current warning for an explicit import 

an implicit import is not a reason to even have a depreciation 

so -1 for fixing this and a hard break is fine

**Comment by TomAugspurger** [comment]
I don’t think it’ll be hard. Similar to the np deprecation.
