### ISSUE TITLE
DOC: missing docstring substitution for Series/DataFrame.set_axis()

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#30881]
https://dev.pandas.io/docs/reference/api/pandas.Series.set_axis.html
https://dev.pandas.io/docs/reference/api/pandas.DataFrame.set_axis.html

![image](https://user-images.githubusercontent.com/13159005/72154883-b527de80-33a9-11ea-8593-91d2cc2a9aaf.png)

**Comment by MarcoGorelli** [comment]
Should the `DataFrame` and `Series` examples in the docstring be separated too?

**Comment by simonjayhawkins** [comment]
It would make the docs better but I think would need to override the set_axis method in series.py and frame.py to do this. Not sure worth it for the amount of duplication (esp. of typing), though no strong preference.

**Comment by giuliobeseghi** [comment]
Does it even make sense to have the parameter `axis` for a `Series`?

**Comment by giuliobeseghi** [comment]
Also, it would be if we could do this:
```python
df.set_axis(index=my_ind, columns=my_cols)
```
instead of

```python
df.set_axis(my_ind).set_axis(my_cols, axis=1)
```

Like the `rename` function: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html
