### ISSUE TITLE
WEB: Add link from the docs to the web

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#30896]
It looks like we'll finally have separate and independent website and docs. I personally think this is not great, and the UX would be much better with both things integrated.

But I think we should at least have a link from the documentation to the website, so users can navigate both sites without having to edit the url.

**Comment by Skchoudhary** [comment]
Hi @datapythonista 
This sound goods, we can add tab in Header of Docs with title "Pandas" or on click of Logo redirect to the home page.Can I start working on this.

**Comment by datapythonista** [comment]
Not sure what's the best option here, but making the logo go to the home sounds better to me than a `Pandas` tab.

**Comment by jorisvandenbossche** [comment]
> It looks like we'll finally have separate and independent website and docs. I personally think this is not great, and the UX would be much better with both things integrated.

I am not sure why you draw that conclusion now. Yes, there didn't happen much on that area, but we still have several ideas at https://github.com/pandas-dev/pandas/issues/28580 that can be tried out to improve this.

For now, of course fine to add a link.  
The theme has the ability to add "external links" that automatically are added on the right to the header navbar. But I agree that an additional item there with something like "Pandas website" is not really great.

**Comment by datapythonista** [comment]
Dupe of #28580
