### ISSUE TITLE
Make a code check which bans imports of fixtures in tests

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#30914]
xref https://github.com/pandas-dev/pandas/pull/30894#discussion_r365510231

Example: writing
```
from pandas.conftest import ALL_EA_INT_DTYPES
```
in a test file should be disallowed because there exists the fixture `any_nullable_int_dtype`

**Comment by SaturnFromTitan** [comment]
take

**Comment by jorisvandenbossche** [comment]
There are some useful things that are imported from conftest.py that cannot be converted to a fixture. So "fixing" this should first discuss what to do instead (or where to move those) ?

**Comment by SaturnFromTitan** [comment]
Good point @jorisvandenbossche I'll check the current violations and make a proposal here.

**Comment by SaturnFromTitan** [comment]
Alright, so there are basically three types of cases:
1. `indices_dict` is imported to create a more specific fixture. I submitted two PRs to resolve these cases as they can easily be replaced with using `indices`
1. `_get_cython_table_params` is imported. I suggest moving it to `pandas._testing` as it's not used for any fixtures anyways it doesn't really make sense to have it in `conftest.py`
1. Any of these dtype constants are imported. Not sure what to do here... We have to move them somewhere else, but I don't know what's a good location. Maybe create a `pandas._dtypes.py`?

Wdyt @jreback @simonjayhawkins @jorisvandenbossche?

**Comment by simonjayhawkins** [comment]
for 1 the two PRs lgtm.

agree with 2.
 
for 3 could have the constants in a separate module as suggested (like token.py — Constants used with Python parse trees) and then import into testing.py (like tokenize.py — Tokenizer for Python source - All constants from the token module are also exported from tokenize) and then we could do say tm.UNSIGNED_INT_DTYPES
