### ISSUE TITLE
DOC: Whatsnew for 1.0 has deprecations listed in Enhancements section

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#30927]
In 1.0.0RC0, at https://dev.pandas.io/docs/whatsnew/v1.0.0.html#other-enhancements (i.e., the list of enhancements), we list the following:

- The pandas.np submodule is now deprecated. Import numpy directly instead (GH30296)
- The pandas.datetime class is now deprecated. Import from datetime instead (GH30296)

Shouldn't those two lines appear in the deprecations section https://dev.pandas.io/docs/whatsnew/v1.0.0.html#deprecations instead?

**Comment by jreback** [comment]
yes this needs editing happy to take. PR

**Comment by ryankarlos** [comment]
One of these may have been my fault, sorry - now fixed in open PR
