### ISSUE TITLE
Getting ValueError: no results with apply(pd.to_numeric(df2.BATTING_Tests_Inns, errors='coerce'))

### ISSUE THREAD

**Issue by subhobrata** [pandas-dev/pandas#30938]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
# convert just selected columns to numeric
df2[["BATTING_Tests_Mat", "BATTING_Tests_Inns","BATTING_Tests_NO","BATTING_Tests_Runs","BATTING_Tests_HS","BATTING_Tests_Ave","BATTING_Tests_SR"]]= df2[["BATTING_Tests_Mat", "BATTING_Tests_Inns","BATTING_Tests_NO","BATTING_Tests_Runs","BATTING_Tests_HS","BATTING_Tests_Ave","BATTING_Tests_SR"]].apply(pd.to_numeric(df2.BATTING_Tests_Inns, errors='coerce'))
```
#### Getting ValueError: no results with apply(pd.to_numeric(df2.BATTING_Tests_Inns, errors='coerce'))

[Getting ValueError: no results with apply(pd.to_numeric(df2.BATTING_Tests_Inns, errors='coerce'))]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Expected Output
It should convert to numeric without any error

#### Output of ``pd.show_versions()``

'0.25.3' in Google colab

[paste the output of ``pd.show_versions()`` here below this line]

</details>
The dataset is taken from below website.
https://data.world/raghav333/cricket-players-espn
Full code is in my Github below
https://github.com/subhobrata/PandasIssue/blob/master/POC_Dataset.ipynb

**Comment by mroeschke** [comment]
We would need a self-contained, copy-pasteable example. https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

Nonetheless, I think you just want `df2[[...]].apply(pd.to_numeric, errors='coerce')`

Feel free to reopen if you are still experiencing issues or can give a reproducible example
