### ISSUE TITLE
REF: remove method and tolerance keywords from Index.get_loc

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#30954]
There is only one non-test place in the code that passes these arguments (Index.asof, and even then it is just "method").  We can put the relevant code directly in `asof` and simplify get_loc quite a bit.

**Comment by jorisvandenbossche** [comment]
`get_loc` is part of the public Index API, and I think eg used in xarray (cc @shoyer). So if we want to remove it, I think at least this should be deprecated, but we should maybe rather first check if this is actually used outside of pandas.

**Comment by jbrockmendel** [comment]
> `get_loc` is part of the public Index API

Yah, I think the thing to do is to implement the no-kwargs version in another method that isn't part of the public API.  Ideally I'd want to make it a non-private name so that it isnt a code smell for Series to do `loc = self.index.new_name(key)`

**Comment by jorisvandenbossche** [comment]
And what's the problem with keeping `get_loc` for that as name?

**Comment by jbrockmendel** [comment]
> And what's the problem with keeping get_loc for that as name?

The problem is that its a public API and changing it is a hassle that won't be finished until 2.0.  Or am I misunderstanding the question?

**Comment by jorisvandenbossche** [comment]
But why do you want to change it? If it is just about code simplicity / logic that `get_loc` now handles both cases and gives a long implementation, then you can also factor out the no-kwargs part in a private function and call that from `get_loc` ? (or the other way around, factor out the kwarg behaviour)

**Comment by jbrockmendel** [comment]
> then you can also factor out the no-kwargs part in a private function and call that from get_loc ?

I think thats what i was suggesting [here](https://github.com/pandas-dev/pandas/issues/30954#issuecomment-573743686), the only difference being that _ideally_ id want a non-private name, just for it to not be part of the public API.

**Comment by jorisvandenbossche** [comment]
Yes, but why do you want another name for the public API. That is `get_loc` already?

**Comment by jbrockmendel** [comment]
> Yes, but why do you want another name for the public API. That is get_loc already?

Do we have a term for "methods explicitly not in the public API but also not preceeded by an underscore, so that it isn't a code small to call from outside"?

**Comment by shoyer** [comment]
Yes, xarray uses `get_loc` internally for our implementation of the `method` and `tolerance` on our labeled indexing methods:
https://github.com/pydata/xarray/blob/8a650a11d1f859a88cc91b8815c16597203892aa/xarray/core/indexing.py#L179-L181

I'd be happy to consider alternatives but we do find this quite useful (and it would be best to avoid unnecessary churn).

**Comment by jorisvandenbossche** [comment]
> > Yes, but why do you want another name for the public API. That is get_loc already?
>
> Do we have a term for "methods explicitly not in the public API but also not preceeded by an underscore, so that it isn't a code small to call from outside"?

@jbrockmendel I don't know (eg "internally pubic API"), but that was not my question. Rather: if we already have a public `get_loc` that you can perfectly use without kwargs, why do you want a separate/new semi-public method that has exactly the same capabilities (for the non-kwarg use case)?

**Comment by jbrockmendel** [comment]
> why do you want a separate/new semi-public method that has exactly the same capabilities (for the non-kwarg use case)?

The subclass methods call the base class method (in some cases, the subclass get_value methods call get_loc or Index.get_loc too).  A lot of that could be simplified if those two keyword were not there.

**Comment by jorisvandenbossche** [comment]
Sorry, Brock, you will need to try to explain it better .. 
"the subclass get_value methods call get_loc or Index.get_loc too" -> yes, several of the `get_value` definitions of Index classes have a call to `get_loc` (without kwargs). What would be simplified there if those kwargs were gone?

**Comment by jorisvandenbossche** [comment]
Maybe we are talking past each other, because there are potentially two questions / discussion items:

- Let's try to get rid of those kwargs, since we don't use them.
- Let's have another "get_loc"-like method but without the kwargs (in addition to `get_loc` which keeps the kwargs)

For the first item, I understand that this would simplify code yes, since it would remove a bunch of things. But as indicated, xarray actually uses this, so I don't think we should deprecate/remove it. Therefore, I am assuming we are talking about the second thing (going from https://github.com/pandas-dev/pandas/issues/30954#issuecomment-573743686). And then, I don't understand why a kwarg-free `get_loc_new` would simplify things if we still keep `get_loc`.

**Comment by jbrockmendel** [comment]
> Maybe we are talking past each other

This seems to be the case.

Given that xarray uses get_loc directly, simplifying the existing method is a non-starter.  I no longer think this is worth pursuing.  May revisit after the current crop of get_loc related PRs/branches are wrapped up.  Closing.

**Comment by 1kastner** [comment]
I used to use `get_loc` with the kwarg parameters `nearest` and in the new API of pandas 2 this is not possible anymore. In the documentation, there is no hint how to achieve the same result with the new API. See, e.g., these for comparison:

- https://pandas.pydata.org/pandas-docs/version/1.2.4/reference/api/pandas.Index.get_loc.html
- https://pandas.pydata.org/docs/reference/api/pandas.Index.get_loc.html

Adding a short explanation of how to get a value from a time series index using the nearest value to the latest documentation would be a great help!
