### ISSUE TITLE
BUG: rpow with -1 and pd.NA should return pd.NA

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#30956]
In https://github.com/pandas-dev/pandas/pull/30097, we added special cases for 1 and -1 not propagating pd.NA:

```
In [59]: 1 ** pd.NA  
Out[59]: 1

In [60]: (-1) ** pd.NA
Out[60]: -1
```

But for -1 this should probably be pd.NA as result in the end, see https://mail.python.org/pipermail/pandas-dev/2020-January/001174.html

```
In [58]: (-1) ** np.array([2, 3, 2.5]) 
/home/joris/miniconda3/envs/dev/bin/ipython:1: RuntimeWarning: invalid value encountered in power
  #!/home/joris/miniconda3/envs/dev/bin/python
Out[58]: array([ 1., -1., nan])
```

**Comment by MarcoGorelli** [comment]
Seems that currently, `-1**pd.NA` is `-1` while `pd.array([-1])**pd.NA` is `[NA]`

**Comment by MarcoGorelli** [comment]
take
