### ISSUE TITLE
AttributeError: 'FrameFixed' object has no attribute 'format_type' on 1.0.0rc0

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#30962]
```python
import pandas as pd


df = pd.DataFrame({"A": [1, 2]})
df.to_hdf("foo.h5", "foo")

with pd.HDFStore("foo.h5") as hdf:
    for key in hdf.keys():
        storer = hdf.get_storer(key)
        print(type(storer), storer.format_type)
```

On 0.25.3, we have

```python
<class 'pandas.io.pytables.FrameFixed'> fixed
```

On 1.0.0rc0

```pytb
Traceback (most recent call last):
  File "bug.py", line 10, in <module>
    print(storer.format_type)
AttributeError: 'FrameFixed' object has no attribute 'format_type'
```

Didn't see anything about this in the release notes. cc @jbrockmendel (if this was part of your tables cleanup).

**Comment by jbrockmendel** [comment]
> (if this was part of your tables cleanup).

This seems likely.  AFAICT it was never used, so it got stripped out.  Does it need to be restored?

**Comment by TomAugspurger** [comment]
I think so. It's available by only public APIs and was used in downstream projects like Dask: https://travis-ci.org/dask/dask/jobs/636393300#L1315
