### ISSUE TITLE
DOC: Fix isort output in CI

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#30974]
In the CI, we're using `isort` to check whether the imports in Python files are sorted in an standard way. See https://github.com/pandas-dev/pandas/blob/master/ci/code_checks.sh#L114

The way it is implemented, we expect isort to not print anything in the terminal if everything is ok, and to show errors for the errors encountered. This is mostly true, except that `isort` is also reporting when there are files being skipped.

The result of this, is that we highlight in the CI as an error when there are files being skipped. See https://github.com/pandas-dev/pandas/pull/30946/checks?check_run_id=385833706#step:6:36

This can be misleading, and we should try to avoid it. Without adding much complexity to the already complex CI. Not sure if there is an `isort` parameter to simply not report the skipped files. Or if there is an easy way to not highlight the skipped files as an error.

**Comment by souvik3333** [comment]
There are no already-existing settings in ```isort``` for this. Can we not just catch the message from ```isort``` and if it's in ```Skipped * files``` format then ignore it? Also, this skip message is only appearing when all imports are sorted not when imports are not sorted.

**Comment by datapythonista** [comment]
Ignoring that message sounds good, or any other solution. The only constraint is that we surely don't want to make that CI part much more complex. I'd prefer to just not have the `##[error]` highlighting, than call `isort` in an unreadable or unreliable way.

**Comment by ndmar** [comment]
I wouldn't mind giving this a go. From a very cursory double check on this, it does indeed appear that the most straightforward solution would be to catch the stdout from the command, and ignore when the output matches the undesired message.

**Comment by leandermaben** [comment]
Hey 
I'd like to work on this issue

**Comment by d1618033** [comment]
The undocumented [`--quiet`](https://github.com/timothycrosley/isort/blob/e62c845d27d55981f99c7cf471adafa59c8ed399/isort/main.py#L330) option in isort seems to do the trick.

**Comment by datapythonista** [comment]
Excellent, thanks @d1618033 Do you want to open a pull request?
