### ISSUE TITLE
DOC: plotting backend is not mentioned in the user guide

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#30984]
The new plotting backend option is documented for package authors implementing such a backend: https://dev.pandas.io/docs/development/extending.html#plotting-backends, but we should probably mention this in the user guide (https://dev.pandas.io/docs/user_guide/visualization.html) as well.

**Comment by ShamanthNyk** [comment]
Can I work on this?

**Comment by mehersaipreetam** [comment]
I would like to work on this please.

**Comment by alimcmaster1** [comment]
Sure for for it! @mehersaipreetam - write `take` to assign the issue to yourself :)

**Comment by mehersaipreetam** [comment]
take

**Comment by mehersaipreetam** [comment]
Can you please review my pr and see where I'm going wrong?

**Comment by alimcmaster1** [comment]
Actually it looks like @rushabh-v already has an open PR. (Apologies for my comment above) There are many other good first issues
