### ISSUE TITLE
BUG: Kurtosis bug?

### ISSUE THREAD

**Issue by AlcoholV** [pandas-dev/pandas#30993]
Why pandas kurtosis and scipy kurtosis result is different?
During the test, I also realized that the Pandas kurtosis value was constantly changing according to the starting point.

![1578962134989](https://user-images.githubusercontent.com/3617014/72303684-6633bf00-36b1-11ea-8d50-92d75cd77de7.png)

**Comment by mroeschke** [comment]
1. pandas statistical methods are unbiased, `scipy.stats.kurtosis` has `bias=True` by default
2. It would be easier to describe the problem/difference comparing the numerical values instead visually with these graphs.

**Comment by AlcoholV** [comment]
bias = False also different. 
Apart from that, isn't it a bug that values constantly changing according to the starting point? Just looking at the screen shot, you can see the one line sticking out alone, even though I just sliding the window.  If it's normal, it should all be the same shape, regardless of location.

**Comment by AlcoholV** [comment]
It's weird. I'm trying to create an example by random generate time series. It can't be recreated. Several other stock charts work fine, too.
Is this what happens only some case or Did I do something wrong?

```
from scipy.stats import kurtosis
df = pd.read_csv('test.txt')
test_length=200

for d in range(10):
    test = df[-test_length-d:-d].reset_index(drop=True)
    plt.plot(test.close.rolling(4).kurt())
plt.show()


for d in range(10):
    test = df[-test_length-d:-d].reset_index(drop=True)
    plt.plot(test.close.rolling(4).apply(lambda x: kurtosis(x, bias=False), raw=True))
plt.show()
```

![kurt](https://user-images.githubusercontent.com/3617014/72317699-6ba6fe80-36dd-11ea-9fa6-e5c2e36ae8e2.png)
[test.txt](https://github.com/pandas-dev/pandas/files/4057547/test.txt)

**Comment by bashtage** [comment]
Is the variance of your data very close to zero?  If so, you could be seeing differences in rounding/numerical precision.

**Comment by bashtage** [comment]
excess kurtosis should always be > -3.  Since you are seeing large values then you are experiencing numerical errors and limits of numerical precision. I suspect many of your blocks have 0 or near 0 variance.

**Comment by bashtage** [comment]
To repro, just share observations 20 - 30 of test.csv.

**Comment by AlcoholV** [comment]
I think it's just like you said. 
In fact, there's not much change in the 1 minute chart. It changes rapidly in a moment.
It wasn't until rolling length 40 that it were stable enough to believe. Until than, value have changed little by little 

This problem made my three day trained network obsolete...


![1579011566007](https://user-images.githubusercontent.com/3617014/72351793-599c7e80-3724-11ea-8c2c-ec42e3c3b113.png)
Rolling 30

**Comment by mroeschke** [comment]
We're happy to reopen this issue when we can validate the issue with a reproducible example. Looking at small raw data samples should be sufficient instead of plots
