### ISSUE TITLE
Using the same column twice within pd.DataFrameGroupBy.agg named arguments

### ISSUE THREAD

**Issue by dprice80** [pandas-dev/pandas#31006]
#### Problem description

Currently, in .agg, one cannot use the same column more than once, so the following code results in an error: 

```
df = pd.DataFrame({
    'group': [1,1,2,2],
    'var1':  [1,2,3,4]
})

df.groupby(
    'group'
).agg(
    sum1 = ('var1', lambda x: x[x > 1].sum()),
    sum2 = ('var1', lambda x: x[x > 2].sum())
)
```

I understand that it is possible to create a MultiIndex DataFrame using a dictionary input rather than keyword arguments, but this required complicated renaming of columns and flattening of the resulting MI DataFrame. Is there some fundamental reason that a column cannot be used twice for two different column specs of .agg?

**Comment by charlesdong1991** [comment]
thanks for reporting @dprice80 which version of pandas are you using?

Could you try it on master? or 1.0.0rc version? I think this issue has been fixed already.

**Comment by TomAugspurger** [comment]
Confirmed that it works for me locally. You can try out the 1.0.0rc as described in https://github.com/pandas-dev/pandas/releases/tag/v1.0.0rc0, or wait for the final release in a week or two.

**Comment by dprice80** [comment]
Thanks very much. Didn't expect such a quick response. I will test with the new version.
