### ISSUE TITLE
incorrect docs: pd.NA ** 0 should return 1

### ISSUE THREAD

**Issue by tsvikas** [pandas-dev/pandas#31003]
`pd.NA ** 0` returns 1. which is correct, as far as I understand <sup>1</sup>
However, the [documents, line 832](https://dev.pandas.io/docs/user_guide/missing_data.html) incorrectly claims that `pd.NA ** 0` returns 0.

----
<sup>1</sup> although one can ask if `NULL**0` should behave like `NAN**0`

**Comment by MarcoGorelli** [comment]
Good catch :) Interested in opening a pull request?

**Comment by tsvikas** [comment]
let's try!

**Comment by tsvikas** [comment]
sorry, i seem to fork off the wron branch some how. i'll try again
