### ISSUE TITLE
DOC: contributing.rst sphinx link leads to 400 bad request

### ISSUE THREAD

**Issue by tonywu1999** [pandas-dev/pandas#31010]
When reading through the contributing guidelines (https://dev.pandas.io/docs/development/contributing.html), there are links to the Sphinx documentation and an introduction to reST.

_Sphinx documentation_:  http://sphinx.pocoo.org/
_Introduction to reST_:  http://sphinx.pocoo.org/rest.html

However, these links are not working and are leading to 400 bad requests.

I propose we replace these links with the following links:
_Sphinx documentation_:  http://www.sphinx-doc.org/en/master/
_Introduction to reST_:  https://www.sphinx-doc.org/en/master/usage/restructuredtext/index.html

I think this will be an easy fix, editing the links in the contributing.rst file in the documentation folder.

**Comment by MarcoGorelli** [comment]
Thanks for the report!

I agree, but perhaps https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html is more suited as the link for "Introduction to reST"?

**Comment by tonywu1999** [comment]
take

**Comment by simonjayhawkins** [comment]
xref #31011
