### ISSUE TITLE
CLN: Possibly obsolete scripts

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#31039]
xref #31038

I'm unsure if the following scripts are still used:
```
scripts/find_commits_touching_func.py
ci/check_cache.sh
ci/check_git_tags.sh
ci/travis_process_gbq_encryption.sh
```

The next I assume are for the release, but may be there is something obsolete here:
```
scripts/build_dist_for_release.sh
scripts/build_dist.sh
scripts/download_wheels.py
```

**Comment by jorisvandenbossche** [comment]
The `download_wheels.py` script is still used at https://github.com/pandas-dev/pandas-release. The other release scripts are seemingly not used there (cc @TomAugspurger )

**Comment by TomAugspurger** [comment]
I think that's right. We can also move the `download_wheels` script to that
repository.

**Comment by jbrockmendel** [comment]
the files mentioned in the OP are now gone.  closeable?

**Comment by datapythonista** [comment]
Yes, this is quite outdated now, closing.
