### ISSUE TITLE
WEB: Broken older versions link in the website

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#31061]
In the top navigation of the website (see pandas.io), in the Docs section, the `Older versions` link is broken.

In #30891 I proposed to just have a single link to the docs for now, so there is no broken link or inconsistencies. But there is no agreement on getting that merged, and some discussion is needed.

Opening this issue, so ideas on what to do can be discussed.

**Comment by jbrockmendel** [comment]
was this fixed by #30891?

**Comment by datapythonista** [comment]
I don't think that's the PR that fixed it, but I can't find that links anymore, so I guess it was fixed elsewhere. Closing.
