### ISSUE TITLE
pd.to_datetime() time conversion error

### ISSUE THREAD

**Issue by chunxueyu** [pandas-dev/pandas#31067]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

```
#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by chunxueyu** [comment]
when I use pd.to_datetime() to convert 12/1/2020. it has turn into 2020-12-01
this bug.

**Comment by chunxueyu** [comment]
the pandas version is 0.23.0
the code I use :  data["t2"] = pd.to_datetime(data["t2"])

**Comment by MarcoGorelli** [comment]
If you use format ([see the docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html))
```
pd.to_datetime('12/1/2020', format='%d/%m/%Y') 
```
you'll get
```
Timestamp('2020-01-12 00:00:00')
```
Is this what you were expecting?

**Comment by chunxueyu** [comment]
> If you use `format` ([see the docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html))
> 
> ```
> pd.to_datetime('12/1/2020', format='%d/%m/%Y') 
> ```
> 
> you'll get
> 
> ```
> Timestamp('2020-01-12 00:00:00')
> ```
> 
> Is this what you were expecting?

I used other methods to solve this problem. I want to know it's pandas  bug?

**Comment by chunxueyu** [comment]
> If you use `format` ([see the docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html))
> 
> ```
> pd.to_datetime('12/1/2020', format='%d/%m/%Y') 
> ```
> 
> you'll get
> 
> ```
> Timestamp('2020-01-12 00:00:00')
> ```
> 
> Is this what you were expecting?

en, I use other methods to solve this problem.  but the methods of you is more convenience.

**Comment by MarcoGorelli** [comment]
OK, I'll close the issue now then seeing as it looks like it's resolved
