### ISSUE TITLE
Unclear DataFrame.info() range summary info for DatetimeIndex

### ISSUE THREAD

**Issue by Ircama** [pandas-dev/pandas#31116]
Within [DataFrame.info](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html), the description of the [DatetimeIndex](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.html) of unsorted indexes might not be clear enough to users, because just showing the first and last element and not the *"min date" to "max date"* values.

Please check the following sample:

```python
import pandas as pd
dfs = []
for day in [30, 1, 2, 5]:
    idx = pd.date_range(f'2020-01-{day} 00:00:00', periods=1000, freq='s')
    dfs.append(pd.DataFrame({'count': range(len(idx)), 'date': idx}))

df = pd.concat(dfs)
df.set_index(['date'], inplace=True)
df
df.info()
df.index.min()
df.index.max()
```

Reated output is the following:
```
>>> df
                     count
date
2020-01-30 00:00:00      0
2020-01-30 00:00:01      1
2020-01-30 00:00:02      2
2020-01-30 00:00:03      3
2020-01-30 00:00:04      4
...                    ...
2020-01-05 00:16:35    995
2020-01-05 00:16:36    996
2020-01-05 00:16:37    997
2020-01-05 00:16:38    998
2020-01-05 00:16:39    999

[4000 rows x 1 columns]
>>> df.info()
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4000 entries, 2020-01-30 00:00:00 to 2020-01-05 00:16:39
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   count   4000 non-null   int64
dtypes: int64(1)
memory usage: 62.5 KB
>>> df.index.min()
Timestamp('2020-01-01 00:00:00')
>>> df.index.max()
Timestamp('2020-01-30 00:16:39')
```

I would expect `2020-01-01 00:00:00 to 2020-01-30 00:16:39` (min and max range values for DatetimeIndex) and not `2020-01-30 00:00:00 to 2020-01-05 00:16:39` (first and last element).

In case, PR https://github.com/pandas-dev/pandas/pull/31069 fixes the issue.

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.4.0-18362-Microsoft
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.17.4
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 41.6.0
Cython           : 0.29.14
pytest           : 5.3.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : None
fastparquet      : 0.3.2
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.15.1
pytables         : None
s3fs             : None
scipy            : 1.3.3
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
</details>

**Comment by drnancy** [comment]
`import pandas as pd
dfs = []
for day in [30, 1, 2, 5]:
    idx = pd.date_range(f'2020-01-{day} 00:00:00', periods=1000, freq='s')
    dfs.append(pd.DataFrame({'count': range(len(idx)), 'date': idx}))

df = pd.concat(dfs)
df.set_index(['date'], inplace=True)
**df= df.sort_index(axis=0)** 
df
df.info()
df.index.min()
df.index.max()`
![image](https://user-images.githubusercontent.com/58162442/72661513-fc911900-3a00-11ea-8c69-42aa9065be79.png)

**Comment by Ircama** [comment]
@drnancy thanks. Should index sorting (`df= df.sort_index(axis=0)`) be required after `df.set_index` for appropriate indexing?

**Comment by drnancy** [comment]
> @drnancy thanks. Should index sorting (`df= df.sort_index(axis=0)`) be required after `df.set_index` for appropriate indexing?

yes df.sort_index will work only after df.set_index

because in line df.set_index(['date'], inplace=True) we are setting date columns as index 
after only it is applicable to apply df.sort_index  which sort the index of the data frame

**Comment by Ircama** [comment]
> > @drnancy thanks. Should index sorting (`df= df.sort_index(axis=0)`) be required after `df.set_index` for appropriate indexing?
> 
> Yes df.sort_index will work only after df.set_index
> 
> Because in line df.set_index(['date'], inplace=True) we are setting date columns as index
> after only it is applicable to apply df.sort_index which sort the index of the data frame

OK thanks. Should I consider an invalid range displayed with `DatetimeIndex` in `DataFrame.info()` a sort of warning that the index is not sorted? I mean, in case sorting an index has to be considered a best practice (or even a requirement) after creating it, maybe the implementation of https://github.com/pandas-dev/pandas/pull/31069 could hide such warning. Conversely, I think that impementation would be appropriate if sorting is optional.

**Comment by drnancy** [comment]
If you want to sort date with sorting function, then you need use specify start point and end point like      the example shown below using pd.date_range function you need to  refer any of this function to generate datetime with sorted and then set it has index to dataframe

**Example:**
import pandas as pd
date1 = '2011-05-03'
date2 = '2011-05-10'
mydates = pd.date_range(date1, date2).tolist()

**Comment by Ircama** [comment]
Thanks for your support.
