### ISSUE TITLE
Docs mention non-existent doc/source/api.rst

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#31135]
E.g. in doc/source/development/contributing.rst it says:
> * Our API documentation in ``doc/source/api.rst`` houses the auto-generated
>   documentation from the docstrings. For classes, there are a few subtleties
>   around controlling which methods and attributes have pages auto-generated.
> 

There's a few other mentions of it elsewhere

**Comment by brebulous** [comment]
Has the auto-generated documentation been moved elsewhere? Or should all references to the auto-generated documentation just be removed completely?

**Comment by MarcoGorelli** [comment]
@brebulous by the looks of it, it is now split between the various files in `doc/source/reference`. Interested in submitting a pull request?

**Comment by ArunimSamudra** [comment]
Hey! I would like to work on this issue.

**Comment by ArunimSamudra** [comment]
Will submit a PR soon.

**Comment by ArunimSamudra** [comment]
Will raise a PR soon.

**Comment by MomIsBestFriend** [comment]
Fixed by #31280
