### ISSUE TITLE
show dtype when using df.head()

### ISSUE THREAD

**Issue by shuai-zhou** [pandas-dev/pandas#31141]
I have a class that requires R, and I realized R will show the data type right below the column names when listing the first n-th rows. I was wondering if this is a feature in Pandas, like when I type `df.head()`, there will be dtype right below the column names.

**Comment by jreback** [comment]
see https://pandas.pydata.org/pandas-docs/version/1.0.0/reference/api/pandas.DataFrame.info.html?highlight=info#pandas.DataFrame.info
