### ISSUE TITLE
Feature Request: Add offset as head() second parameter

### ISSUE THREAD

**Issue by StashOfCode** [pandas-dev/pandas#31140]
It would be very cool and intuitive if we could do somethig like this:
```python
df.head(10, 100) 
```
#### Problem description
There are a lot of situations where you need to look through rows and rows of data and currently the alternatives are: 

1. play with pd.options to display more rows
2. use indexing and slicing
3. output dataframe to excel

Adding `offset` would definitely save a lot of time and effort since it would take only a second to use. It is even easier than <strong>SQL</strong>'s `LIMIT` `OFFSET` approach

#### Docs
```python
DataFrame.head(self, n=5, offset=0)

Parameters: 
n : int, default 5. Number of rows to select.
offset: int, default 0. Skips the offset rows before selecting rows.
```
#### Expected Output
```python
>>> df = pd.DataFrame({'animal':['alligator', 'bee', 'falcon', 'lion',
...                    'monkey', 'parrot', 'shark', 'whale', 'zebra']})
>>> df
      animal
0  alligator
1        bee
2     falcon
3       lion
4     monkey
5     parrot
6      shark
7      whale
8      zebra

>>> df.head(3, 2)
      animal
2     falcon
3       lion
4     monkey
```

**Comment by dsaxton** [comment]
It seems what you're looking for is essentially the `tail` of the `head`, so you can get the same behavior by combining these two methods. With an offset one could argue that we're not actually interested in the head anymore.

**Comment by StashOfCode** [comment]
@dsaxton , I like it, but i've never thought about taking the `tail` of the `head` before for some reason. Probably, because it was not so obvious at least for me.

**Comment by mroeschke** [comment]
Thanks for the suggestion @StashOfCode. I think @dsaxton's alternative is idiomatic to pandas (chaining methods) as opposed to adding a new keyword to `head`.
