### ISSUE TITLE
ImportError because of file named bottleneck.py

### ISSUE THREAD

**Issue by imntl** [pandas-dev/pandas#31151]
There is a ImportError raised, if you have a file named bottleneck.py in your current working directory.

In a python 3.7.5 console you get:

```python
>>> import pandas

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jalea/.local/lib/python3.7/site-packages/pandas/__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "/home/jalea/.local/lib/python3.7/site-packages/pandas/core/api.py", line 5, in <module>
    from pandas.core.arrays.integer import (
  File "/home/jalea/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 7, in <module>
    from .categorical import Categorical  # noqa: F401
  File "/home/jalea/.local/lib/python3.7/site-packages/pandas/core/arrays/categorical.py", line 54, in <module>
    from pandas.core.base import NoNewAttributesMixin, PandasObject, _shared_docs
  File "/home/jalea/.local/lib/python3.7/site-packages/pandas/core/base.py", line 36, in <module>
    import pandas.core.nanops as nanops
  File "/home/jalea/.local/lib/python3.7/site-packages/pandas/core/nanops.py", line 38, in <module>
    bn = import_optional_dependency("bottleneck", raise_on_missing=False, on_version="warn")
  File "/home/jalea/.local/lib/python3.7/site-packages/pandas/compat/_optional.py", line 99, in import_optional_dependency
    version = _get_version(module)
  File "/home/jalea/.local/lib/python3.7/site-packages/pandas/compat/_optional.py", line 48, in _get_version
    raise ImportError("Can't determine version for {}".format(module.__name__))
ImportError: Can't determine version for bottleneck
```
 If i delete the empty bottleneck.py in the directory, everything works fine. I you want to test it, just use `touch bottleneck.py` and open a interactive python console and you will get the error.

The problem also arises in tensorflow and keras. If there is a file named `bottleneck.py` you can't import these two, because they depend on pandas. This problem arised also in a keras [issue](https://github.com/keras-team/keras/issues/6602), but it didn't get looked into it.

Possible fix could be to get another `try: … except: …` block around line 97 of [pandas/compat/_optional.py](https://github.com/pandas-dev/pandas/blob/3f57ae7967776a8cd22d16e45a3476e63f08cbe4/pandas/compat/_optional.py) if `on_version == "warn"`.

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.3.0-26-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : de_DE.UTF-8
LANG             : de_DE.UTF-8
LOCALE           : de_DE.UTF-8

pandas           : 0.25.3
numpy            : 1.17.4
pytz             : 2019.2
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 41.1.0
Cython           : 0.29.10
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.9.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.2
sqlalchemy       : 1.3.11
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
</details>

**Comment by TomAugspurger** [comment]
You shouldn't have module names that overlap with modules from the standard library or 3rd party packages. The typical recommendation is to include a trailing underscore in your module, so `bottleneck_.py`.

**Comment by imntl** [comment]
I can understand why you shouldn't use modules named like modules from the standard library, but also for 3rd party packages? So can you provide such list at all times? I digged around for more than an hour to find out, what the problem was and didn't think that the problem arises because of a name a file has in the directory I was in.

If the file is not empty the error messages become not helpful at all:

```python
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/pandas/__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/api.py", line 5, in <module>
    from pandas.core.arrays.integer import (
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/arrays/__init__.py", line 7, in <module>
    from .categorical import Categorical  # noqa: F401
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/arrays/categorical.py", line 52, in <module>
    import pandas.core.algorithms as algorithms
AttributeError: module 'pandas' has no attribute 'core
```

**Comment by TomAugspurger** [comment]
This isn’t really something that can be solved at the library level. It would need a change to Python’s import handling.

**Comment by grahamgower** [comment]
Well this is a fairly unsatisfying closure of an issue. I'm not even using pandas (a library I use pulls it in) and this hit me!

**Comment by MarcoGorelli** [comment]
Please try to be constructive - do you have a concrete suggestion?
