### ISSUE TITLE
Cannot iterate over result of a group by multiple columns if one contains NaN

### ISSUE THREAD

**Issue by gfitas** [pandas-dev/pandas#31153]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
df = pd.DataFrame({"a": [1, 1, None, None], "b": [2,3,4,5]})
r = df.groupby(["a","b"])
print(len(r))
for _, i in r:
    print(i)
```
#### Problem description

Hi, 
when trying to perform a group by over multiples columns and if a column contains a Nan, the composite key is ignored. We can still access to the lines by iterating over the groups property of the generic.DataFrameGroupBy by using iloc but it is unwieldy. 
```python
for i in gb.groups:
    print(df.iloc[gb.groups.get(i)]) 
```
It seems unexpected that the len of the result is different from the number of results got when iterating.

#### Expected Output
4
     a  b
0  1.0  2
     a  b
1  None  3
     a  b
1  None  4
     a  b
1  None  5
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.3
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 44.0.0.post20200106
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.4 (dt dec pq3 ext lo64)
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
None

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.3
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 44.0.0.post20200106
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.4 (dt dec pq3 ext lo64)
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None

</details>

**Comment by dsaxton** [comment]
I think the output is what we'd expect; the null values are excluded in the groupby by default: https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html#na-values-in-groupby

**Comment by mroeschke** [comment]
This is the expected behavior as @dsaxton points out.
