### ISSUE TITLE
REF: move 'describe' functions to new file

### ISSUE THREAD

**Issue by david-cortes** [pandas-dev/pandas#31154]
Opening an issue about a refactor of the code for the `describe` method in Series and DataFrames as requested here: https://github.com/pandas-dev/pandas/pull/30209
Idea was to move all the helper functions (according to type) into a new file `pandas/core/algos/describe.py`

And to redo the tests on `describe` methods by dtype using parametrize.

---------
Seeing as the current organization of the files in the master branch does not follow this arrangement and would imply some perhaps bug changes, I'd prefer not to work on this myself.

**Comment by mzeitlin11** [comment]
Think the refactor portion was taken care of by a string of PR's like #39102, but don't think the testing parameterization looked at

**Comment by jbrockmendel** [comment]
Closing as completed.  Test de-duplication goal is implied.
