### ISSUE TITLE
ValueError: can not merge DataFrame with instance of type 

### ISSUE THREAD

**Issue by chiang233** [pandas-dev/pandas#31173]
#### Code Sample, a copy-pastable example if possible

```python
df_debtor = pd.merge(debtor_marital,debtor_gender, left_on = "IDENTITY", right_on = "IDENTITY", how = "inner")

```
#### Problem description
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
 in 
----> 1 df_debtor = pd.merge(debtor_marital,debtor_gender, left_on = "IDENTITY", right_on = "IDENTITY", how = "inner")

~/opt/anaconda3/lib/python3.7/site-packages/modin/pandas/general.py in merge(left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
     75     if not isinstance(left, DataFrame):
     76         raise ValueError(
---> 77             "can not merge DataFrame with instance of type {}".format(type(right))
     78         )
     79

**Comment by charlesdong1991** [comment]
thanks for posting your issue @chiang233 

could you pls add minimal reproducible sample of the data in your description as well? (e.g. `debtor_marital =pd.DataFrame(something)`, the same for `debtor_marital `)

**Comment by chiang233** [comment]
Thank for kindly reply.
I think it can't reproduce in a user-defined dataframe. I had checked my dataframe's type, both the key columns are "object" type .  

I try to use pd.concat , but the two columns value does not match.

**Comment by charlesdong1991** [comment]
emm, which version of pandas do you use? could you try it on master branch or 1.00rc?

**Comment by chiang233** [comment]
>>> import pandas
>>> pandas.__version__
'0.25.3'

thank you for yr advise and I will try other version later.

**Comment by simonjayhawkins** [comment]
closing as not reproducible and _maybe_ Modin related.
