### ISSUE TITLE
COMPAT: numpy object array coercion warnings

### ISSUE THREAD

**Issue by AlexKirko** [pandas-dev/pandas#31201]
#### Problem description

Since at least a couple hours ago, the Numpy Dev pipeline fails 39 tests:
```
##[error]39 test(s) failed, 60964 test(s) collected.
```
I checked and all 39 are like this:
```
numpy.VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
```

Full output of one of the tests below.

<details>

```

        True
        >>> a = np.array([(1.0, 2), (3.0, 4)], dtype='f4,i4').view(np.recarray)
        >>> np.asarray(a) is a
        False
        >>> np.asanyarray(a) is a
        True
    
        """
>       return array(a, dtype, copy=False, order=order)
E       numpy.VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
```

</details>

Thanks to @jreback for pointing out we've run into this before, but Numpy reverted the deprecation warning. The original issue was #30043

**Comment by jreback** [comment]
this is numpy redoing the object array coercion

cc @jbrockmendel 
cc @mattip 

https://github.com/numpy/numpy/commit/287a9d0646c9cc40385615264348a637a7c57205

**Comment by AlexKirko** [comment]
Found the previous issue, I think: #30043. Added to the issue description.

**Comment by AlexKirko** [comment]
For reference, this is [NEP 34](https://numpy.org/neps/nep-0034.html), which justified this change.

**Comment by AlexKirko** [comment]
If anyone wante a quick look, you can look at [my error log](https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=26473&view=logs&j=3a03f79d-0b41-5610-1aa4-b4a014d0bc70&t=4d05ed0e-1ed3-5bff-dd63-1e957f2766a9&l=63), while it's still alive. Seems like mostly we call `np.array` or `asarray` on mixed input, but there is also some stuff in arithmetic operations testing.

**Comment by TomAugspurger** [comment]
I can take a look at this now.

**Comment by jbrockmendel** [comment]
@AlexKirko did there end up being a kwarg like `np.asarray(ragged, foo=np.ragged_as_object)`?

**Comment by seberg** [comment]
We did not add the special sentinel because it seemed that all of the (larger) downstream packages are handling fine without it. If you find a place where it would help you, we would add it though.
