### ISSUE TITLE
CI: Web and docs (pull_request) fails: can't rich intershipinx inventory

### ISSUE THREAD

**Issue by AlexKirko** [pandas-dev/pandas#31212]
#### Problem description
Seems like currently CI / Web and docs (pull_request) fails for everyone with this error message:
```
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'http://www.statsmodels.org/devel/objects.inv' not readable due to ValueError: unknown or unsupported inventory version: ValueError('invalid inventory header: ')
```
All my PRs had the `CI / Web and docs (pull_request)` check break without any changes to docs, and I checked PRs by other people: other people seem to have this problem.
#### Expected behaviour
Passing the test

**Comment by TomAugspurger** [comment]
cc @bashtage. Did https://github.com/statsmodels/statsmodels/pull/6452 perhaps fix this?

**Comment by TomAugspurger** [comment]
Apparently not fixed by https://github.com/statsmodels/statsmodels/pull/6452

**Comment by bashtage** [comment]
https://www.statsmodels.org/devel/objects.inv seems to work.  It a 439kb file with the right text at the start.

**Comment by TomAugspurger** [comment]
Indeed, that does look correct now. We'll see if things are working on the CI again.

**Comment by bashtage** [comment]
The deep issue is that the doctr log is so big that it was exceeding the upper limit for travis's log file, which causes the build to silently succeeed even though it did not.

**Comment by AlexKirko** [comment]
@bashtage 
When I downloaded the file directly when CI failed, the objects.inv file was completely empty. Don't know if it's relevant, but it may be useful.

**Comment by bashtage** [comment]
Yes, the upload to github silently failed and objects.inv (and probly lots of other things) didn't make it.  I'm going to try and do a fake run on travis to rebuild with a fixed script.  It is a bit tricky since everything on travis is under git and checking out a tag changes everything tracked.

**Comment by AlexKirko** [comment]
Ah, thanks for explaining, now I understand what happened.

**Comment by bashtage** [comment]
Definitely, all fixed now. Both stable and devel.

**Comment by TomAugspurger** [comment]
Thanks.
