### ISSUE TITLE
ENH: maybe_dispatch_to_dunder_op handle min/max

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#31219]
I'm running up against a case where I need np.maximum.reduce(period_array) to work; itd be nice if that could be handled by maybe_dispatch to call PeriodArray.max

cc @jorisvandenbossche @TomAugspurger

**Comment by TomAugspurger** [comment]
To clarify, `np.maximum(PeriodArray)` works fine, right? It's the `.reduce` part that isn't handled?

**Comment by jbrockmendel** [comment]
`np.maximum(PeriodArray)` breaks because it expects multiple arguments, `np.maximum(period_array, period_array)` works, while `np.maximum(period_index, period_index)` fails with `ValueError: ufunc 'maximum' not supported for the PeriodIndex`

But yes, it is specifically the `.reduce` that is coming up at the moment

**Comment by TomAugspurger** [comment]
> while `np.maximum(period_index, period_index)` fails with `ValueError: ufunc 'maximum' not supported for the PeriodIndex`

That would be solved with Index having an `__array_ufunc__`. I wounder if `Series.__array_ufunc__` can be moved to to IndexOpsMixin. I suppose alignment of Series but not Index makes that tricky.

Can you provide a failing example for reduce on period array?

```python
In [8]: np.maximum.reduce(pd.array(['2000', '2001'], dtype='Period[D]'))
Out[8]: Period('2001-01-01', 'D')
```

**Comment by jbrockmendel** [comment]
> Can you provide a failing example for reduce on period array?

Not on master.  In the relevant branch I have implemented `DatetimeLikeArrayMixin.__array_ufunc__` (to get `np.isfinite(datetimeindex_tzaware)` to work... yak shaving)
