### ISSUE TITLE
Make the documentation for pandas.Series.str.replace() clearer

### ISSUE THREAD

**Issue by drkarthi** [pandas-dev/pandas#31225]
#### Problem description

The current documentation of str.replace says ```Replace occurrences of pattern/regex in the Series/Index with some other string. Equivalent to str.replace() or re.sub().```.

For the novice user this suggests that base Python's str.replace() and re.sub() provide equivalent functionality. My suggestion is to explicitly specify that this depends on the value of regex, making it clearer. Something like this:

```Replace occurrences of pattern/regex in the Series/Index with some other string. Equivalent to str.replace() or re.sub() **depending on the _regex_ value**.```

**Comment by ashwinpn** [comment]
take
