### ISSUE TITLE
DOC ENH: Move DataFrame.info from "Serialization / IO / conversion" to "Attributes and underlying data"

### ISSUE THREAD

**Issue by jpeacock29** [pandas-dev/pandas#31233]
In the [API reference for DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html), why is `DataFrame.info()` in the "Serialization / IO / conversion" section? It would make more sense to me in the "Attributes and underlying data" section, which has similar methods and attributes like `DataFrame.memory_usage()`, `DataFrame.dtypes`and `DataFrame.shape`.

Glad to make a pull request if this makes sense to others.

**Comment by mroeschke** [comment]
Make sense to me. Happy to take a PR!
