### ISSUE TITLE
DOC BUG API Reference documentation truncated for Series.unstack(), Series.

### ISSUE THREAD

**Issue by jpeacock29** [pandas-dev/pandas#31235]
The [API Reference documentation for `Series`](https://pandas.pydata.org/pandas-docs/stable/reference/series.html) and [`DataFrame`](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html) have truncated documentation strings for `Series.at_time()`, `Series.unstack()`, and `DataFrame.at_time()`. The bug appears to occur where the docstring contains ". " (that is, a period followed by a space). Presumably, this pattern is being used to find the end of the one-line function description.

**Comment by jorisvandenbossche** [comment]
@jpeacock29 indeed, I think that's a correct analysis. We should reword it a bit to avoid the `. ` pattern

**Comment by anjalis2112** [comment]
Hello! 
I would be happy to work on this.

**Comment by jorisvandenbossche** [comment]
@anjalis2112 Certainly, that's welcome!
