### ISSUE TITLE
Potential bug in reading SAS files with CHAR (RLE) compression and many repeated characters

### ISSUE THREAD

**Issue by peterzsohar** [pandas-dev/pandas#31243]
Hi,

I think I ran into a bug in the RLE decompression implementation.

**Short description**:
String fields with more than 32 repeated consecutive characters are ~be~ cropped at 32 and next fields will spill over corrupting the whole dataframe.

**Example**:

example.csv with fields of length 50
```
long_string_field1,long_string_field2,long_string_field3
"00000000000000000000000000000000000000000000000000","11111111111111111111111111111111111111111111111111","aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
```

Create a CHAR compressed sas7bdat file (system encoding is set to latin1)
```sas
options compress=char;
proc import datafile="path\example.csv"
        out=your_lib.example
        dbms=csv
        replace;
        getnames=yes;
run;
```

```python
import pandas as pd
example = pd.read_sas("./example.sas7bdat", encoding="latin1")
```

This is what you get:
```python
>>> example['long_string_field1'].values[0]
'00000000000000000000000000000000  111111111111111111'
```
```python
>>> example['long_string_field2'].values[0]
'11111111111111  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
```
```python
>>> example['long_string_field3'].values[0]
nan
```
There are a couple of interesting points:
1. Exactly 32 characters are read/written from each field. Originals had 50 characters.
2. The dataframe fields are filled up to the 50 limit (+ 2 additional spaces between the sources of the fields. In case of consecutive integers) with spillovers from next fields.
3. This only happens if one uses the CHAR compression. (RLE)
4. This only happens if you have repeated consecutive characters.
5. The `sas7bdat` package works fine.

#### DISCLAIMER
I would never use any of the things above out of my free will. Sadly, this is an actual case I keep running into when having to deal with SAS... 😢 

#### Output of ``pd.show_versions()``

<details>

```
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : None.None

pandas           : 0.25.3
numpy            : 1.17.5
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 45.1.0.post20200119
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.4 (dt dec pq3 ext lo64)
jinja2           : 2.10.3
IPython          : 7.11.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.15.1
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.12
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
```
</details>

**Comment by Eric-Sommer** [comment]
I always read SAS files with `encoding='iso-8859-1'` (see [here](https://stackoverflow.com/questions/38203988/encoding-in-sas7dbat)). Does that help in your case?

**Comment by peterzsohar** [comment]
> I always read SAS files with `encoding='iso-8859-1'` (see [here](https://stackoverflow.com/questions/38203988/encoding-in-sas7dbat)). Does that help in your case?

Thanks, but unfortunately no.
`latin1` is the encoding that was used for the original `sas7bdat` so this is in fact the correct encoding to be used when reading the file to pandas.
(also, `latin1` is just an alias for `iso-8859-1` 😉 )

Nevertheless, before submitting the issue I ran a script to check if the issue persists if using any other enconding for reading the data. (It does.)

Not sure if it is the case if another encoding is used when writing the original `sas7bdat` file.

**Comment by Eric-Sommer** [comment]
> (also, `latin1` is just an alias for `iso-8859-1` 😉 )
thanks for that info :)

**Comment by paul-lilley** [comment]
Hi,
I can confirm this is a problem with decoding the RLE compression, not related to encoding.  
Looking at the docs for sas7bdat (actually the docs for the R package that sas7bdat is based on) SAS has an interesting compression with differing (and overlapping) options for how single and consecutive fields are compressed.  It looks like pandas correctly decompresses some of the options, but not all.

I've tested a bit and found that if there are preceeding fields, then a field with 18 consecutive zeros that is OK, but preceeding fields then 19 zeros is NOT decompressed correctly.
I'll dig a bit further to see if the SAS dataset uses differing compression control codes for these two datasets.

**Comment by paul-lilley** [comment]
I can try to put together a PR to alter the decompression for control code 0x40 (and add code for 0x50), or (since we have other issues related to SAS files) should we look to use Evan Miller's library or pyreadstat rather than duplicating others' efforts within pandas? @jbrockmendel, @mroeschke  - what do you think?

**Comment by mroeschke** [comment]
cc @bashtage

**Comment by ofajardo** [comment]
pyreadstat is already used in pandas.read_spss so I guess it would be an easy one to also provide it as an backend option for read_sas

**Comment by paul-lilley** [comment]
@ofajardo I agree pyreadstat (which uses Evan Miller's library) is also significantly faster than pandas cython implementation

**Comment by bashtage** [comment]
It sounds like a no brainer to move to pyreadstat given it is already a soft dep.  The only question is what will the path look like.  It would probably require adding optional support, deprecating pandas build-in, and then eventually removing the native reader.

**Comment by ofajardo** [comment]
Sounds like a plan!
