### ISSUE TITLE
Verbose parameter in pandas.Series.apply

### ISSUE THREAD

**Issue by MastafaF** [pandas-dev/pandas#31245]
Hi,

I think it could be really useful to add a **Verbose** parameter in the **pandas.Series.apply** function. It can take a really long time to get an output so having some kind of verbosity with something like tqdm could be really useful. 

Cheers,

**Comment by mroeschke** [comment]
What information would a `verbose` parameter provide that `print` statements in the apply function could not?

**Comment by MastafaF** [comment]
Hi @mroeschke, suppose you have N rows with N being large enough to make you wait for several hours. It would be great to know at which row in the dataframe the apply is, similarly to what tqdm offers in a range.

**Comment by MarcoGorelli** [comment]
`tqdm` offers a progress bar for `apply` - https://github.com/tqdm/tqdm/blob/master/examples/pandas_progress_apply.py

**Comment by MastafaF** [comment]
Cool @MarcoGorelli , thanks for the suggestion! 😄

**Comment by jbrockmendel** [comment]
apply in general doesnt operate row-wise, but column-wise.  we dont really have much ability to insert periodic logging between row operations.

dask might over more visibility into how an operation is performing (cc @TomAugspurger)

**Comment by TomAugspurger** [comment]
Dask has a couple options for monitoring progress through tasks. Agreed this is best handled outside pandas for now.

We'd gladly take an entry for tqdm's progress bar in the pandas ecosystem docs.
