### ISSUE TITLE
ENH: allow 'pad', 'backfill' and 'cumcount' in groupby.transform

### ISSUE THREAD

**Issue by fujiaxiang** [pandas-dev/pandas#31269]
#### Summary
Currently on master, `groupby.transform` with ``func`` equals one of `('fillna', 'pad', 'backfill', 'ffill', etc.)` yields wrong results (See #30918).

With updates from PR (#31101), the incorrect outputs are fixed. However, when ``func`` is one of `('pad', 'backfill', 'cumcout')`, `groupby.transform` then raises ``AttributeError`` similar to what's reported in #27472.

#### Code Sample

```python
# On branch of PR31101
>>> pd.__version__
'1.0.0rc0+162.g56c70234e'

>> df = pd.DataFrame(
...     {
...         "A": ["foo", "foo", "foo", "foo", "bar", "bar", "baz"],
...         "B": [1, 2, np.nan, 3, 3, np.nan, 4],
...     }
... )
>>> df
     A    B
0  foo  1.0
1  foo  2.0
2  foo  NaN
3  foo  3.0
4  bar  3.0
5  bar  NaN
6  baz  4.0

>>> df.groupby("A").pad()  # This is ok
     B
0  1.0
1  2.0
2  2.0
3  3.0
4  3.0
5  3.0
6  4.0

>>> df.groupby("A").transform("pad")  # This raises AttributeError
Traceback (most recent call last):
...
...
AttributeError: 'Series' object has no attribute 'pad'

>>> df.groupby("A").transform("cumcount")
Traceback (most recent call last):
...
...
AttributeError: 'Series' object has no attribute 'cumcount'
```

Ideally we want to allow all of the above 3 functions in `groupby.transform`

**Comment by punndcoder28** [comment]
Hey! I would like to work on this. Could you guide me?

**Comment by fujiaxiang** [comment]
@punndcoder28 The relevant PR #31101 has not been merged yet. After that is merged, you can try these three functions on master, and see what you can do. You can also take a look at #27472 to see what has been discussed.

**Comment by punndcoder28** [comment]
Ok. I will keep an eye out for PR #31101 and start as soon as it is merged.

**Comment by punndcoder28** [comment]
Hey @fujiaxiang. I tried out the functions on master now that PR #31101 got merged. I am getting the `AttributeError` only for `cumcount`.

**Comment by fujiaxiang** [comment]
Are you sure? I just tried again on current master and I got ``AttributeError`` for all 3. Please note that I'm talking about `df.groupby("A").transform("pad")`, and not `df.groupby("A").pad()`.

**Comment by punndcoder28** [comment]
This is the code I am executing:
```(python3)
>>> df1 = pd.DataFrame(
...     {
...             "A": ["foo", "foo", "foo", "foo", "bar", "bar", "baz"], 
...             "B": [1,2,np.nan, 3,3,np.nan,4]
...     }
... )
>>> df1.groupby("A").transform("pad")
     B
0  2.0
1  2.0
2  2.0
3  2.0
4  1.0
5  1.0
6  2.0
>>> df1.groupby("A").transform("cumcount")
Traceback (most recent call last):
  ...
AttributeError: ("'Series' object has no attribute 'cumcount'", 'occurred at index B')
>>> df1.groupby("A").transform("backfill")
     B
0  3.0
1  3.0
2  3.0
3  3.0
4  1.0
5  1.0
6  2.0

```

Am I missing something?

**Comment by fujiaxiang** [comment]
I think you are not on the latest master. You can see that the result you showed for both `pad` and `backfill` are not correct, and are inline with the behavior prior to PR #31101. Could you pull the latest master first?

**Comment by punndcoder28** [comment]
Yes, my mistake. I built from the latest master and I am getting the errors.

**Comment by punndcoder28** [comment]
Hey @fujiaxiang . I went through the code but couldn't figure out where to make changes. Since you had worked on a similar issue could you give me some pointers?

**Comment by fujiaxiang** [comment]
As a general guide you should try looking at the implementation of groupby.transform for other similar methods and mimic those. We already have implementations for these functions somewhere in the code so this shouldn't be too difficult to do.

**Comment by fujiaxiang** [comment]
@punndcoder28 are you still interested? If not, I will take a look at it myself.

**Comment by punndcoder28** [comment]
Yes I am still interested. I am looking that the definitions of similar functions like you had advised.

**Comment by punndcoder28** [comment]
Hey @fujiaxiang . I was unable to find the definitions for other similar functions.
