### ISSUE TITLE
pandas.Series.str.replace giving irrelavent results

### ISSUE THREAD

**Issue by jerilkuriakose** [pandas-dev/pandas#31276]
The following is my code:
```python
import pandas as pd

a = ['16', '66', '66', '42', '17', '55', '66b', '17', '48', 
     '66', '48', '75', '76', '6a', '80', '57', '66', '13', 
     '17', '31', '66', '6c', '17', '65b', '17', '39', '17', 
     '66.0', '80.0', '6.0', '66.0', '21.0', '31.0', '7.0', '8.0']
df = pd.DataFrame(a)

print(df[0].str.replace('.0', '').values)
'''
Output:
['16' '66' '66' '42' '17' '55' '66b' '17' '48' '66' '48' '75' '76' '6a' ''
 '57' '66' '13' '17' '31' '66' '6c' '17' '65b' '17' '39' '17' '66' '' '6'
 '66' '21' '31' '7' '8']
'''

print(df[0].apply(lambda x: x.replace('.0', '')).values)
'''
Output:
['16' '66' '66' '42' '17' '55' '66b' '17' '48' '66' '48' '75' '76' '6a'
 '80' '57' '66' '13' '17' '31' '66' '6c' '17' '65b' '17' '39' '17' '66'
 '80' '6' '66' '21' '31' '7' '8']
'''
```
#### Problem description

I was trying to replace `'.0'` with `''`, and when i use **pandas.Series.str.replace** `80` and `80.0` is replaced as `''`; whereas when I replace using **pandas.Series.apply(lambda x: x.replace('.0', ''))** it is working as expected.

Looks like an issue.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 7
machine          : AMD64
processor        : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.1
numpy            : 1.17.0
pytz             : 2018.4
dateutil         : 2.7.3
pip              : 19.3.1
setuptools       : 42.0.2
Cython           : 0.28.2
pytest           : 4.6.3
hypothesis       : None
sphinx           : 1.7.4
blosc            : None
feather          : None
xlsxwriter       : 1.0.4
lxml.etree       : 4.2.1
html5lib         : 1.0.1
pymysql          : 0.9.3
psycopg2         : None
jinja2           : 2.10
IPython          : 6.4.0
pandas_datareader: None
bs4              : 4.6.0
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.2.1
matplotlib       : 3.1.1
numexpr          : 2.6.5
odfpy            : None
openpyxl         : 3.0.0
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.3
sqlalchemy       : 1.2.7
tables           : 3.4.3
xarray           : None
xlrd             : 1.1.0
xlwt             : 1.3.0
xlsxwriter       : 1.0.4
</details>

**Comment by fujiaxiang** [comment]
This is because `df.str.replace` has argument `regex` default to ``True``. If you set `regex=False` you should get what you wanted.

**Comment by TomAugspurger** [comment]
Thanks for the explanation @fujiaxiang.
