### ISSUE TITLE
CI: update azure VM image

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#31281]
Email from Azure support

> On March 23, 2020, we’ll be removing the following Azure Pipelines hosted images:
>
> * Windows Server 2012R2 with Visual Studio 2015, a.k.a vs2015-win2012r2
> * macOS X High Sierra 10.13, a.k.a macOS-10.13
> * Windows Server Core 1803, a.k.a win1803

> If you use YAML pipelines, update your pipeline by editing its YAML file.
> 
>  
> 
>   jobs:
> 
>     - job: Windows
> 
>       pool:
> 
>         vmImage: 'vs2017-win2016'
> 
>       steps:
> 
>       - script: echo hello from Windows

**Comment by MomIsBestFriend** [comment]
Is there anything we need to change?

In

https://github.com/pandas-dev/pandas/blob/67a8016da0e39778354b2e6d35a4b9b964cc3381/azure-pipelines.yml#L17

(The most recent version of the file at the time of writing this)

The value of ```vmImage``` is already ```'vs2017-win2016'```

**Comment by TomAugspurger** [comment]
I think the macOS image may be the problem, but I'm not sure.

https://github.com/pandas-dev/pandas/blob/67a8016da0e39778354b2e6d35a4b9b964cc3381/azure-pipelines.yml#L4-L7

That at least matches the 10.13 part.

**Comment by MomIsBestFriend** [comment]
take
