### ISSUE TITLE
NaT values cannot be compared with tz-aware datetime objects

### ISSUE THREAD

**Issue by mitar** [pandas-dev/pandas#31306]
#### Code Sample, a copy-pastable example if possible

```python
import pandas
import datetime
a = pandas.DataFrame({'b': [pandas.NaT]})
a.b > datetime.datetime.now(datetime.timezone.utc)
```

Output:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../pandas/core/ops/__init__.py", line 1179, in wrapper
    res_values = dispatch_to_index_op(op, self, other, pd.DatetimeIndex)
  File ".../pandas/core/ops/__init__.py", line 630, in dispatch_to_index_op
    result = op(left_idx, right)
  File ".../pandas/core/indexes/datetimelike.py", line 132, in wrapper
    result = op(self._data, maybe_unwrap_index(other))
  File ".../pandas/core/arrays/datetimes.py", line 168, in wrapper
    self._assert_tzawareness_compat(other)
  File ".../pandas/core/arrays/datetimes.py", line 789, in _assert_tzawareness_compat
    "Cannot compare tz-naive and tz-aware " "datetime-like objects."
TypeError: Cannot compare tz-naive and tz-aware datetime-like objects.
```

#### Problem description

When parsing timestamps, I return `pandas.NaT` if value is not parsed correctly. Otherwise I return timezone-aware timestamps. I also want then to compare those values with a timezone-aware timestamp. But if there is any `pandas.NaT` value present comparison fails.

#### Expected Output

```
0    False
Name: b, dtype: bool
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.0.0-37-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.2
numpy            : 1.17.3
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.0.3
setuptools       : 40.4.3
Cython           : 0.29.10
pytest           : 4.4.1
hypothesis       : None
sphinx           : 1.8.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.2.5
html5lib         : 0.9999999
pymysql          : None
psycopg2         : 2.8.3 (dt dec pq3 ext lo64)
jinja2           : 2.10
IPython          : None
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.2.5
matplotlib       : 3.0.0
numexpr          : 2.6.9
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.15.1
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by jreback** [comment]
try on 1.0.0rc0 or master

**Comment by jorisvandenbossche** [comment]
This also fails on master. But I think it is correct in failing? 
The dtype of the columns is tz-naive, so if you want the NaT to represent a tz-aware timestamp, you can ensure the column has a datetimtz dtype.

cc @jbrockmendel

**Comment by jbrockmendel** [comment]
i agree with joris

**Comment by mitar** [comment]
> The dtype of the columns is tz-naive, so if you want the NaT to represent a tz-aware timestamp, you can ensure the column has a datetimtz dtype.

I think the problem is that I cannot create a tz-aware NaT. I think this is the main issue here. I think it makes no sense for NaT to depend on the column dtype to determine tz-awarness.

Example: I have a parsing function which returns tz-aware datetime objects, or NaT. Then I run this as a map (`apply`) over the column to get a new column. And then I can compare against a tz-aware datetime objects that column.

Now, in most cases this works great. Except when all values in the column cannot be parsed. Then I the column is all full of NaT and if I continue to compare the column an above exception is thrown.

If I could instead return a tz-aware NaT this would not be a problem.

Now, you are saying that I should force the dtype of the column to be tz-aware, but this is just only once I encounter this edge case. Which is not necessary easy to debug or pinpoint.

So, please provide a tz-aware NaT.

**Comment by TomAugspurger** [comment]
You can create a tz aware column with all NaT, you need to specify the dtype. Pandas cannot infer a time zone from all NaT values though.

**Comment by mitar** [comment]
> You can create a tz aware column with all NaT, you need to specify the dtype.

I understand what you are saying can be a workaround. What I am describing is that it is hard to envision such an edge case when you are writing the code. So one does not do it, because generally Pandas inferring just works.

>  Pandas cannot infer a time zone from all NaT values though.

Yes, so it would be great if one could have a UTC time-zone aware NaT value.

**Comment by jreback** [comment]
@mitar 
what you are doing here

> Example: I have a parsing function which returns tz-aware datetime objects, or NaT. Then I run this as a map (apply) over the column to get a new column. And then I can compare against a tz-aware datetime objects that column.

This is an edge case; you should *rarely* be 'parsing' things which return dates and *then* applying them. You *must* then handle things yourself. Pandas works because it can infer entire vectorized arrays of things. If you are operating on scalars one at a time, then you are responsinble for properly coercing. pandas can't guess what you want.

**Comment by jreback** [comment]
simply do this

```
In [2]: import pandas 
   ...: import datetime 
   ...: a = pandas.DataFrame({'b': [pandas.NaT]}, dtype='datetime64[ns, UTC]') 
   ...: a.b > datetime.datetime.now(datetime.timezone.utc)                                                                                                                                                                                                      
Out[2]: 
0    False
Name: b, dtype: bool
```

**Comment by mitar** [comment]
And how does Pandas know how to parse strings like "2 days ago" into a timestamp? I have to provide a parsing function and go over all scalar values, no?

**Comment by mitar** [comment]
Also, see [workarounds people have to do here](https://stackoverflow.com/questions/57484672/is-there-a-way-to-append-nat-to-a-pandas-datetime-with-timezone-without-changing).

**Comment by jreback** [comment]
you have made my point. if you need to do something custom then you are in charge of having the right dtype. pandas refuses to guess. if you are explicit then it works just fine.
