### ISSUE TITLE
ENH: add an option to read_csv to select a specific rows / sample of the csv file

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#3132]
propose an option, `sample` or `keeprows` (#14285)

maybe taking a callable, for really just something like `sample=10`

to return you every 10th row

if it takes a callbale couuld use something like: `lambda x: x % 10`

easy way to get a `sample` of the csv file

useful to avoid specifying `skiprows` with a big list

and to solve an issue like this:

http://stackoverflow.com/questions/15555005/get-inferred-dataframe-types-iteratively-using-chunksize

**Comment by nanoix9** [comment]
Oh, this issue has been opened for more than 3 years, and still opening? Why

**Comment by jorisvandenbossche** [comment]
> Oh, this issue has been opened for more than 3 years, and still opening? Why

Because nobody has implemented it. Pull requests with code are certainly welcome.

**Comment by nanoix9** [comment]
I would like to have a try, though it's "Difficulty Intermediate" and I am a newbie for the development of Pandas.

**Comment by linebp** [comment]
This seems to be already solved by this #15059. ``skiprows`` takes a callable with the linenumber as argument and returns ``true`` or ``false`` on whether or not to keep the row.
