### ISSUE TITLE
Sometimes one day of when reading date fields

### ISSUE THREAD

**Issue by matthiasleopold** [pandas-dev/pandas#31339]
#### Code Sample

```python
import datetime
import pandas

df = pandas.read_excel('28422_LZ.xlsx', sheet_name='Laufzettel')
stamp = df[df.columns[3]][16].timestamp()
print('first date =', datetime.datetime.utcfromtimestamp(stamp).strftime('%Y-%m-%d'), '(one day of)')

df = pandas.read_excel('test.xlsx', sheet_name='Tabelle1')
stamp = df[df.columns[0]][0
[28422_LZ.xlsx](https://github.com/pandas-dev/pandas/files/4116748/28422_LZ.xlsx)
[test.xlsx](https://github.com/pandas-dev/pandas/files/4116749/test.xlsx)

].timestamp()
print('seconde date =', datetime.datetime.utcfromtimestamp(stamp).strftime('%Y-%m-%d'), '(correct)')
```
#### Problem description

I read two date fields from two excel sheets. First date is one day off, second date is okay. I cannot see any reason for the difference in behavior. First date ('recalculated time') should be  2015-09-18.

#### Expected Output

```
first date = 2015-09-18 (!!!)
seconde date = 1978-03-16 (correct)
```

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.0-6-amd64
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : de_DE.UTF-8
LOCALE           : de_DE.UTF-8

pandas           : 0.25.3
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 18.1
setuptools       : 40.8.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
None
[28422_LZ.xlsx](https://github.com/pandas-dev/pandas/files/4116717/28422_LZ.xlsx)
[test.xlsx](https://github.com/pandas-dev/pandas/files/4116718/test.xlsx)

**Comment by MarcoGorelli** [comment]
If you convert to a `pandas.Timestamp` first, then you'll get your desired output:
```
>>> datetime.datetime.utcfromtimestamp(pd.to_datetime(df[df.columns[3]][16]).timestamp())
datetime.datetime(2015, 9, 18, 0, 0)
>>> datetime.datetime.utcfromtimestamp(df[df.columns[3]][16].timestamp())
datetime.datetime(2015, 9, 17, 23, 0)
```

I believe the reason is that otherwise, `df[df.columns[3]][16]` is a `datetime` object which will use your local timezone. I presume you live in a place where your timezone is the same as UTC, except for between March and October when you observe Daylight Saving time.

**Comment by matthiasleopold** [comment]
Thank you it's working!
