### ISSUE TITLE
json normalize max level not working

### ISSUE THREAD

**Issue by jphilippou27** [pandas-dev/pandas#31336]
#### Code Sample, a copy-pastable example if possible

```python
from pandas.io.json import json_normalize

data = [{'id': 1,
          'name': "Cole Volk",
          'fitness': {'height': 130, 'weight': 60}},
         {'name': "Mose Reg",
          'fitness': {'height': 130, 'weight': 60}},
        {'id': 2, 'name': 'Faye Raker',
          'fitness': {'height': 130, 'weight': 60}}]
json_normalize(data, max_level=0)
```
#### Problem description

The code above is from the pandas docs. I'm running python 3.6.4 and pandas==0.22.0

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by jphilippou27** [comment]
See attached output

**Comment by jphilippou27** [comment]
hmm seems like the pic isn't going through :

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-218-3f42a5e0f8ea> in <module>()
      7         {'id': 2, 'name': 'Faye Raker',
      8           'fitness': {'height': 130, 'weight': 60}}]
----> 9 json_normalize(data, max_level=0)

TypeError: json_normalize() got an unexpected keyword argument 'max_level'

**Comment by WillAyd** [comment]
Max_level is new in pandas 0.25.0 so you would have to upgrade to at least that for this to work

**Comment by maulberto3** [comment]
Hi @jphilippou27 @WillAyd, using pandas 1.0.1.  from anaconda, max_level does not go as deep as it states:
```
pd.json_normalize([{ '_id': '5ee2a48778abab31e88eaa7b', 
                         'first': { 'b': 3, 'c': 4 },
                         '2nd': {'lvl1': 1, 'lvl2': {'a', 2}}},
                   { '_id': '5ee2a48778abab31e88eaa7b', 
                         'first': { 'b': 30, 'c': 40 },
                         '2nd': {'lvl1': 10, 'lvl2': {'a', 20}}},
                  ], max_level=None)
			     _id	first.b		first.c		2nd.lvl1	2nd.lvl2
0	5ee2a48778abab31e88eaa7b	3		4		1		{a, 2}
1	5ee2a48778abab31e88eaa7b	30		40		10		{a, 20}
```
