### ISSUE TITLE
Using matplotlib scatter legends?

### ISSUE THREAD

**Issue by amueller** [pandas-dev/pandas#31357]
Matplotlib now allows doing legends for categorical data in scatter:
https://matplotlib.org/gallery/lines_bars_and_markers/scatter_with_legend.html

Is that something that pandas could/should use?
I feel like there's a tricky issue in deciding whether the color variable is categorical but basically matplotlib allows us now to treat the case and I'm not sure if treating all cases as continuous makes the most sense.

**Comment by charlesdong1991** [comment]
take

**Comment by charlesdong1991** [comment]
@amueller  looks nice! would be nice to have it, I will check and see if a patch can be made to add this feature

**Comment by lfmaomao** [comment]
Thanks for sharing
