### ISSUE TITLE
Center align the text and icons in documentation index

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#31369]
At https://dev.pandas.io/docs/index.html, the alignment is slightly off. Especially notable for User Guide and API reference

![Screen Shot 2020-01-27 at 3 27 16 PM](https://user-images.githubusercontent.com/1312546/73215355-90f22e80-4119-11ea-9f6b-d9bedd1f332b.png)

cc @jorisvandenbossche

**Comment by jorisvandenbossche** [comment]
Hmm, indeed. Looking at it with browser developer tools, for some reason there is padding on the left but no on the right in the `card-img-top` div.

Removing

```
.intro-card .card-img-top {
  margin: 10px;
}
```

from pandas.css seems to help (it makes there is a bit less whitespace above the icons, but not sure that is a problem)

cc @stijnvanhoey

**Comment by TomAugspurger** [comment]
I think it looks fine without the margin.
![Screen Shot 2020-01-28 at 9 02 54 AM](https://user-images.githubusercontent.com/1312546/73275611-00fdc480-41ad-11ea-8abf-5165cb151165.png)
