### ISSUE TITLE
loc on Series returning scalar when result size is 1

### ISSUE THREAD

**Issue by omri374** [pandas-dev/pandas#31381]
#### Code Sample

```python
# Create a DataFrame with index and one Series
df = pd.DataFrame({"id":[1,2,3,3],"val":["abcde","bbcde","cbcde","dbcde"]})
df.set_index("id",inplace=True)
```
Calling `.loc` when the result length is 2 returns a Series (as expected):
```
type(df['val'].loc[3])
```
Output:
```
pandas.core.series.Series
```

Calling `.loc` when the result length is 1 returns a `str`:
```python
# use .loc when the result length is 1:
type(df['val'].loc[1])
```
Output:
```
str
```
#### Problem description

The fact that the same code returns different types causes inconsistencies. If I run `len` on the result, I would get 2 for `id=3` and 5 for `id=1` or `id=2`, since the string length is 5:

```python
len(df['val'].loc[3])
```
Output:
```
2
```
When calling `loc[1]`:
```python
len(df['val'].loc[1])
```
Output:
```
5
```

#### Expected Output
`.loc` should return a Series regardless of the size. Otherwise this causes bugs when trying to evaluate the length of the output. 
```python
# Expected output:
type(df['val'].loc[1])
```
Output:
```
pandas.core.series.Series
```
```python
len(df['val'].loc[1])
```
Output:
```
1
```
#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None
pandas           : 0.25.3
numpy            : 1.17.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 42.0.2.post20191203
Cython           : None
pytest           : 5.3.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.10.2
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.2
sqlalchemy       : 1.3.12
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None

</details>

**Comment by jreback** [comment]
this is a duplicate issue - pls do a detailed search

**Comment by omri374** [comment]
Couldn't find this issue.

**Comment by jreback** [comment]
oldie but goodie
https://github.com/pandas-dev/pandas/issues/9519

welcome to have go at impl
note this would be a breaking change so would need to simply deprecate things for now
