### ISSUE TITLE
NTile function

### ISSUE THREAD

**Issue by xmnlab** [pandas-dev/pandas#31398]
#### Problem description

I've investigated on pandas a `ntile` operation alternative. I just found `qcut` but it seems there is a difference between them (at least I could have the same results I expected).

for more details about `NTile`[3] :

> NTILE() function allows you to divide ordered rows in the partition into a specified number of ranked groups as equal size as possible. These ranked groups are called buckets.
> The NTILE() function assigns each group a bucket number starting from 1. For each row in a group, the NTILE() function assigns a bucket number representing the group to which the row belongs.

I have locally a python version of this function, is this something I could open a PR to pandas? if yes, I would be very happy to work on this PR.

any feedback and/or guidance would be very appreciated.

some references about ntile:

[1] https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions101.htm
[2] https://www.sqlservertutorial.net/sql-server-window-functions/sql-server-ntile-function/
[3]https://www.postgresqltutorial.com/postgresql-ntile-function/

thanks!

**Comment by MarcoGorelli** [comment]
Thanks for the suggestion

> it seems there is a difference between them

Could you please document the difference, perhaps with an example?

**Comment by xmnlab** [comment]
@MarcoGorelli this is my example: https://gist.github.com/xmnlab/2c1f93df1a6c6bde4e32c8579117e9cc

if I could just use `qcut` that would be also ... let me know if I am missing some parameter there :)

thank you so much for your attention!

**Comment by datapythonista** [comment]
I think pandas API is already too big. Did you try implementing this as an aggregate function and use `apply`? I may be wrong, but doesn't feel like  there is enough demand for this to implement it in pandas itself, and I think implementing it in a third-party library or your own code should be easy.

**Comment by xmnlab** [comment]
thanks for the feedback @datapythonista !

**Comment by xmnlab** [comment]
I am closing this issue, but if there is anything related to that I can help, let me know :)
