### ISSUE TITLE
CI: revert the warning change once IPython updates

### ISSUE THREAD

**Issue by charlesdong1991** [pandas-dev/pandas#31407]
A couple days ago, there was a CI broken caused by the latest jedi release, and back then, made a patch to catch the warning. Ideally, after ipython updates and fixes the deprecated code, then the warning should be removed, and we should be able to revert the change in #31323

FYI, I created an issue on IPython: https://github.com/ipython/ipython/issues/12102

**Comment by jbrockmendel** [comment]
@charlesdong1991 some tab completion tests are failing, is that related to this?

**Comment by mroeschke** [comment]
Looks like the warning code has been reverted on master for quite some time since 2021-02-02, so appears safe to close.
