### ISSUE TITLE
helper method to sanitize column names of a pandas DataFrame

### ISSUE THREAD

**Issue by zahash** [pandas-dev/pandas#31417]
I will add a method to sanitize column names of a pandas DataFrame and make a pull request
Below is the test code

```python
from pandas import DataFrame
import pandas._testing as tm


def test_sanitize_column_names():
    df = DataFrame(
        {
            "A  ": [1],
            "b": [1],
            "  485 5(468a)44 44   4 ?  $@e3   *   C cc    c D  ": [1],
        }
    )
    df.sanitize_column_names()
    expected_df = DataFrame({"a": [1], "b": [1], "485_5468a44_44_4_e3_c_cc_c_d": [1]})
    tm.assert_frame_equal(df, expected_df)

```
This issue is about an enhancement

**Comment by TomAugspurger** [comment]
I think pyjanitor has something like this. I think "sanitize" is such a fuzzy concept it may not make sense for pandas proper.

**Comment by mroeschke** [comment]
Thanks for the suggestion, but agreed that that this would be better for an opinionated external library and pandas tries to be more general. Closing.
