### ISSUE TITLE
Cross tabulations for categorical data doesn't work as the way expected in the guide

### ISSUE THREAD

**Issue by GYHHAHA** [pandas-dev/pandas#31410]
#### Code Sample, a copy-pastable example if possible

```python
In [73]: foo = pd.Categorical(['a', 'b'], categories=['a', 'b', 'c'])
In [74]: bar = pd.Categorical(['d', 'e'], categories=['d', 'e', 'f'])
In [75]: pd.crosstab(foo, bar)
Out[75]: 
col_0  d  e
row_0      
a      1  0
b      0  1
```
#### Problem description

In the latest [user guide](https://dev.pandas.io/docs/user_guide/reshaping.html#cross-tabulations), it says "Any input passed containing Categorical data will have all of its categories included in the cross-tabulation, even if the actual data does not contain any instances of a particular category.". But why the example doesn't work like this way? (lack of the row 'c' and column 'f')
Thanks !

**Comment by MarcoGorelli** [comment]
Seems that you're right - thanks for the report, @GYHHAHA !

Are you interested in investigating the issue / opening a pull request?

**Comment by GYHHAHA** [comment]
Of course, glad to. @MarcoGorelli
