### ISSUE TITLE
"Tuple of Lists" method doesn't applicable for DataFrame

### ISSUE THREAD

**Issue by GYHHAHA** [pandas-dev/pandas#31439]
#### Code Sample, a copy-pastable example if possible

```python
>>>df = pd.DataFrame({'col':np.ones(9)},index=pd.MultiIndex.\
                       from_product([['A','B','C'],['a','b','c']])).sort_index()
>>>df['col'].loc[(['A','B'],['b','c'])]
A  b    1.0
    c    1.0
B  b    1.0
    c    1.0
Name: col, dtype: float64
>>>df.loc[(['A','B'],['b','c'])]
KeyError: "None of [Index(['b', 'c'], dtype='object')] are in the [columns]"
```
#### Problem description

It seems that the "tuple of lists" method doesn't applicable for dataframe.
Originally, I thought these two operations will return the same numerical result.

**Comment by TomAugspurger** [comment]
No, these are different. Tuples are treated as keys into the multiindex. Lists are treated like arrays slicing the level of a multiindex.

**Comment by GYHHAHA** [comment]
```python
>>>df.loc[(['A','B'],['b','c']),:]
```
Oh, I find it works for this way. Thanks !
