### ISSUE TITLE
pandas web and docs structure

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#31434]
The site served by `web` assumes that the docs are served from a `/docs/` directory relative to the root. The content of that directory should be equivalent to what we have at https://pandas.pydata.org/pandas-docs/version/1.0.0/, so `/version/1.0.0/` or `/version/stable/`.

Should I symlink `/docs/` to `/version/stable/`? Does that mess with canonical urls?

cc @datapythonista.

**Comment by datapythonista** [comment]
Symlinking was my idea, I think it makes things easy for us and the users.

**Comment by TomAugspurger** [comment]
OK, I made the symlink. Will try deploying the new website to pandas.pydata.org now.

**Comment by TomAugspurger** [comment]
It's live at https://pandas.pydata.org/! I clicked through things and didn't find any broken links.

Will update the release scripts later today to use this.
