### ISSUE TITLE
REGR: to_csv(na_rep) truncates values

### ISSUE THREAD

**Issue by mdruiter** [pandas-dev/pandas#31447]
#### Code Sample

```python
>>> import pandas as pd
>>> pd.__version__
'1.0.0rc0'
>>> pd.Series(range(8, 12)).to_csv(na_rep='-')
',0\r\n0,8\r\n1,9\r\n2,1\r\n3,1\r\n'
```
#### Problem description

Despite (or due to?) #29975 and #30146, using `na_rep` still makes `to_csv()` truncate values. In this case integers.

#### Expected Output

',0\r\n0,8\r\n1,9\r\n2,10\r\n3,11\r\n'

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.1.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Dutch_Netherlands.1252

pandas           : 1.0.0rc0
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.11.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
</details>

**Comment by jorisvandenbossche** [comment]
Thanks for the report!

Yes, the `itemsize = writers.word_len(na_rep)` in the PR you linked seems like a wrong fix. Further investigations always welcome! I tagged it with the 1.0.1 milestone, as this is also a regression compared to 0.25 (https://github.com/pandas-dev/pandas/issues/29975 was a new issue)

**Comment by fwitte** [comment]
Hi,
this is happening similarly to me, but in my case it affects pure boolean columns:
```
import pandas as pd
pd.__version__
'1.0.0'
pd.Series([True, False, 3.1113, 150, -10]).to_csv('outfile.csv', na_rep='nan')
```
correctly yields
```
,0
0,True
1,False
2,3.1113
3,150
4,-10
```
while
```
pd.Series([True, False, False, True]).to_csv('outfile.csv', na_rep='nan')
```
results in this:
```
,0
0,Tru
1,Fal
2,Fal
3,Tru
```

#### Output of ``pd.show_versions()``

<details>

commit           : None
python           : 3.6.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-76-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : de_DE.UTF-8
LOCALE           : de_DE.UTF-8

pandas           : 1.0.0
numpy            : 1.16.2
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 20.0.2
setuptools       : 41.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.4 (dt dec pq3 ext lo64)
jinja2           : 2.10.3
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.0.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.11
tables           : 3.6.1
tabulate         : None
xarray           : 0.14.1
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

Have a nice weekend!

**Comment by TomAugspurger** [comment]
Taking a look at this now.

**Comment by TomAugspurger** [comment]
I think https://github.com/pandas-dev/pandas/pull/30146 is the bug. That will truncate the values to the length of `na_rep`, regardless of the length of the string repr values.
