### ISSUE TITLE
DOC: to_csv is not properly linked from read_csv docstring

### ISSUE THREAD

**Issue by StevenLi-DS** [pandas-dev/pandas#31448]
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html#pandas.read_csv

![image](https://user-images.githubusercontent.com/33796896/73450512-8b703080-4333-11ea-8a76-b1f57a7400b0.png)

**Comment by jorisvandenbossche** [comment]
Thanks for the report!

The `to_csv` should read `DataFrame.to_csv` I suppose. PRs welcome

**Comment by srvanrell** [comment]
Can I fix this one?

**Comment by srvanrell** [comment]
I have created a PR. Let me know if there is anything more to do. It is my first time contributing in this project.
