### ISSUE TITLE
pandas.apply() converts all columns to object datatype

### ISSUE THREAD

**Issue by michaelsilverstein** [pandas-dev/pandas#31466]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame([['a', 1], ['b', 2]], columns=['col1', 'col2'])
df.dtypes
df.apply(lambda x: x.dtype)
```
![image](https://user-images.githubusercontent.com/22639569/73474042-cbe3a480-435b-11ea-8f95-957f8f4dba0d.png)

#### Problem description
Column datatypes are converted to object if one columns is dtype=object

#### Expected Output
Columns should maintain datatypes when passed to apply

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.0.0-1029-gcp
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.0
numpy            : 1.16.2
pytz             : 2018.9
dateutil         : 2.8.0
pip              : 19.2.2
setuptools       : 41.0.1
Cython           : 0.29.5
pytest           : 4.3.0
hypothesis       : None
sphinx           : 1.8.4
blosc            : None
feather          : None
xlsxwriter       : 1.1.5
lxml.etree       : 4.3.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10
IPython          : 7.3.0
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : 0.3.0
lxml.etree       : 4.3.0
matplotlib       : 3.0.2
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.6.0
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 4.3.0
pyxlsb           : None
s3fs             : 0.2.0
scipy            : 1.2.1
sqlalchemy       : 1.2.18
tables           : 3.4.4
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.5
numba            : 0.42.0

</details>

**Comment by vadella** [comment]
Shouldn't the dtype of the result depend on the dtype of the returns value of the applied function? In this case `x.dtype` returns objects of type `<class 'numpy.dtype'>`, so an object dtype on the resulting Series looks logical to me.

**Comment by TomAugspurger** [comment]
This bug report is about the dtype of the object given to the user's function, not the output.

Agreed that this looks strange @michaelsilverstein. Are you interested in debugging further?

**Comment by vadella** [comment]
I misread :man_facepalming: 

So output:

```
col1    object
col2    object
dtype: object
```
Expected output
```
col1    object
col2    int64
dtype: object
```

I noticed this behaviour also happens when there is a float columns present:
```python
pd.DataFrame([[.5, 1], [1.5, 2]], columns=['col1', 'col2']).apply(lambda x: x.dtype)
```
> ```
> col1    float64
> col2    float64
> dtype: object
> ```

**Comment by TomAugspurger** [comment]
The object-dtype values comes in https://github.com/pandas-dev/pandas/blob/master/pandas/core/apply.py#L278-L288. Not sure what changed from 0.25.x, but I don't think we should be doing `self.values` when we have mixed types. It'd be more appropriate (and possibly faster?) to fall back to https://github.com/pandas-dev/pandas/blob/master/pandas/core/apply.py#L316-L317 when we have `self.obj._is_mixed_type`

**Comment by jeremyliweishih** [comment]
Another affected use case of this bug is calling `DataFrame.corrwith(y)` when `y` is a `Series` object as `corrwith` will invoke the `apply()` function as well!

**Comment by mroeschke** [comment]
This looks to be fixed in master. Could use a test

```
In [195]: df.dtypes
Out[195]:
col1    object
col2     int64
dtype: object

In [196]: df.apply(lambda x: x.dtype)
     ...:
Out[196]:
col1    object
col2     int64
dtype: object
```

**Comment by grahamwetzler** [comment]
take
