### ISSUE TITLE
Add method to handle mixed string and non-string types in object column.

### ISSUE THREAD

**Issue by RicardoHS** [pandas-dev/pandas#31498]
#### Problem description

Since the version 1.0.0 and the creation of the StringDtype the use of an object column to handle string would decrease. Nevertheless, and [as in the new documentation is stated](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.0.0.html)
```
There isn’t a clear way to select just text while excluding non-text, but still object-dtype columns.
```
The way how I had handle this issue in the past have changed throught the time and depending on my needs. I think this is a great opportunity to define a way to proceed in this cases. I dont know the feelings of the devs on this issue. In any case, here we go my two cents to have something to start a discussion about this:

- Series.select_dtypes() : Select subset of rows based on the type. maybe with an option to convert non matching rows to NA instead of dropping it.

**Comment by TomAugspurger** [comment]
I'm having trouble understanding your proposal. Can you write up a sample docstring for your proposed method with some examples?

**Comment by RicardoHS** [comment]
[Someting similar to the dataframe method.](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.select_dtypes.html) Anyway, this is just an idea to handle mixing types in object column.

```python
def Series.select_dtypes(self, include=None, exclude=None, drop=True):
        """
        Return a subset of the Series's rows based on the rows dtypes.
        Parameters
        ----------
        include, exclude : scalar or list-like
            A selection of dtypes or strings to be included/excluded. At least
            one of these parameters must be supplied.
        drop : boolean
            If true, non-matching rows would be dropped. If false, they will be
            converted to NA instead.
        Returns
        -------
        Series
            The subset of the frame including the dtypes in ``include`` and
            excluding the dtypes in ``exclude``.
       
        Examples
        --------
       >>> s = pd.Series([1,2,'a'])
       >>> s
       0    1
       1    2
       2    a
       dtype: object
       >>> s.select_dtypes(include='string')
       2    a
       dtype: object
       >>> s.select_dtypes(include='string', drop=False)
       0    <NA>
       1    <NA>
       2    a
       dtype: object
        """

```

**Comment by TomAugspurger** [comment]
Mmm, I don't know if that justifies a top-level method. The filtering of rows seems strange to me. More typically you would do the conversion using something like `to_numeric` and have options to convert invalid values to some kind of NA value.

**Comment by RicardoHS** [comment]
I'm agree, when I face this problem I use to use `Dataframe.apply()` method with a simple nested lambda inside. Also sometimes I use some vectorized methods like `to_numeric` as you said, and I'm sure that other people use other workarounds but it is sure that there is no 'official' way to deal with.

The way of how to deal with this is not a problem, I have found complications when I have multiple object columns with more than two mixed types inside (or data types treated as string inside). The thing I want to discuss is the possibility to have an 'unified' method to overcome this situation. 

For example, having a method as the previosly presented would allow to do something like:

```python
for col in df.selec_dtypes('object'):
     df[col] = col.selec_dtypes('string', drop=False)
```

This approach is easy to remember. At this time, I know how to deal with a problem like this, but I dont remember how to deal exactly and I need to check in the docs. Using something like this, IMHO could benefit the readable of the code.

**Comment by Dr-Irv** [comment]
I'm not sure this makes sense because the `String` dtype that was introduced is the dtype of a *column*.  You're looking to be able to test dtypes *within* a column, which means that we'd have to test the dtypes of individual elements, which would most likely not be performant, because pandas tries to keep a unified dtype for all elements within a column.

**Comment by RicardoHS** [comment]
Why do you say it would not be performant?

Sorry, I don't know if I can't explain myself well or because of language problems.

I know that pandas always tries to have a dtype for the entire column. But there are times (especially when reading a csv without specifying the type of the column) that pandas assigns the generic dtype 'object' to the column and in that case dealing with the types of each element becomes a task where there is no specific pandas method. It is for these cases where I think that a method of this style would be a good improvement.

**Comment by Dr-Irv** [comment]
By "not performant", I mean that we would have to check the dtype of each individual element.  

I understand the request - I've labeled it as a possible enhancement that needs discussion by the core team.

You might also want to look at the `convert_dtypes()` method that can convert the dtype of an entire column, which might help with your CSV issue.

**Comment by mroeschke** [comment]
Thanks for the request, but agreed that this proposal doesn't really follow the pattern of other dtype conversion methods by evaluating element by element.

Since there hasn't been much support from the pandas team for this issue, going to close. Happy to reopen if there is renewed interest
