### ISSUE TITLE
Large dataframes aren't truncated in LaTeX output

### ISSUE THREAD

**Issue by mojones** [pandas-dev/pandas#31492]
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
pd.DataFrame(np.random.rand(300,4),columns=['a','b','c','d']).to_latex()

```
#### Problem description

I'm using Jupyter notebook to write a long document using pandas, which I eventually will nbconvert to a PDF. In the notebook with HTML output, long dataframes are truncated as expected and I can control the number of rows with `pd.set_option('max_rows', 5)`. When displaying as LaTeX, however, long dataframes are not truncated, so the above code will generate a 300 row LaTeX table. My real dataframes are much longer. This breaks PDF export. 

Obviously I can get round this by just calling `head()`. However, given that this a tutorial, it would be nice to be able to display a table in the PDF that will match the HTML output, i.e. with the rows of dots in the middle to represent data not shown. Could `to_latex()` honour the `max_rows` option? Is there any workaround here? 

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-74-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 0.25.3
numpy            : 1.16.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.1.1
setuptools       : 41.0.1
Cython           : None
pytest           : 5.3.4
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.3.3
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.5.0
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.3
matplotlib       : 3.1.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.0
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
</details>

**Comment by TomAugspurger** [comment]
Generally we make a distinction between printing for display (like in the notebook) and "exporting" data. In this case `to_html()` and `to_latex()` behave the same: they don't use the max_rows setting.

**Comment by mojones** [comment]
Fair enough. Ugly monkey patch workaround for anyone else in this situation:

```python
def to_latex_truncated(df):
    start = df.head(int(pd.get_option('max_rows') / 2)).to_latex_original().split('\n')[:-3]
    end = df.tail(int(pd.get_option('max_rows') / 2)).to_latex_original().split('\n')[4:]
    number_of_columns = start[-1].count('&') + 1
    missing = ' & '.join(['...'] * number_of_columns) + r' \\'
    return '\n'.join(start + [missing] + end)


pd.DataFrame.to_latex_original = pd.DataFrame.to_latex
pd.DataFrame.to_latex = to_latex_truncated
```

Never do this in production, etc. etc.
