### ISSUE TITLE
How to make partial sums in pivot tables a little more flexible?

### ISSUE THREAD

**Issue by wesm** [pandas-dev/pandas#3149]
http://stackoverflow.com/questions/15570099/pandas-pivot-tables-row-subtotals/15574875#15574875

**Comment by petehuang** [comment]
Hi,

This issue hasn't been touched for a few years. Does this continue to represent a useful enhancement?

**Comment by wesm** [comment]
It's a syntactic / API issue. I think this could still be improved -- I'm not sure if there's been any work done on this in the last few years

**Comment by chessplayer60** [comment]
Left a comment in #4817 about this. It would be really nice to have an augmented API allowing for drill-down and roll-up to be displayed in (extended) pivot tables.

**Comment by dharmen001** [comment]
is #4817 resolved??

**Comment by WillAyd** [comment]
Closing due to age and open-ended nature of request. If more succinct requests can be made feel free to reopen!
