### ISSUE TITLE
json_normalize Doc Broken

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#31514]
First google result for json_normalize will yield:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.io.json.json_normalize.html

This however is a dead link. I think the issue is we moved json_normalize to the top-level pd.namespace, so this works:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.json_normalize.html

The former should redirect to the latter

**Comment by alimcmaster1** [comment]
Weird thought:
https://github.com/pandas-dev/pandas/pull/27615/files#diff-47f38b5b26d0c19878c1e8e90a65463dR780

Would have solved this.. but clearly not!

**Comment by Harsh1347** [comment]
The link `https://pandas.pydata.org/pandas-docs/stable/reference` works but `/api` throws 404 error.
