### ISSUE TITLE
DOC: 10 minutes - <TAB> completion section showing inconsistent suggestions

### ISSUE THREAD

**Issue by Cardosaum** [pandas-dev/pandas#31526]
#### Code Sample, a copy-pastable example if possible

From the very end of the section "[Object Creation](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html#object-creation)"
```python

In [12]: df2.<TAB>  # noqa: E225, E999
df2.A                  df2.bool
df2.abs                df2.boxplot
df2.add                df2.C
df2.add_prefix         df2.clip
df2.add_suffix         df2.clip_lower
df2.align              df2.clip_upper
df2.all                df2.columns
df2.any                df2.combine
df2.append             df2.combine_first
df2.apply              df2.consolidate
df2.applymap
df2.D
```
And the following text:
```rst
As you can see, the columns ``A``, ``B``, ``C``, and ``D`` are automatically
tab completed. ``E`` is there as well; the rest of the attributes have been
truncated for brevity.
```

#### Problem description
In the text we read that columns `A`, `B`, `C` and  `D` are shown. However, `df2.B` isn't shown at all

#### Expected Output

I think we could just add some more <TAB> completions, along side `df2.B` to make the documentation more consistent to what is being said.

Something similar to:

```python

In [12]: df2.<TAB>  # noqa: E225, E999
df2.A                  df2.bool
df2.abs                df2.boxplot
df2.add                df2.C
df2.add_prefix         df2.clip
df2.add_suffix         df2.columns
df2.align              df2.combine
df2.all                df2.combine_first
df2.any                df2.D
df2.append             df2.describe
df2.apply              df2.diff
df2.applymap           df2.div
df2.B                  df2.divide
```

##### Note

I'd like to know what does `# noqa: E225, E999` means. I didn't see this reference early in this guide

**Comment by charlesdong1991** [comment]
thanks @Cardosaum  sounds reasonable, this shows subset, and could replace `d2.D` with `d2.B` and update the text below

Wanna help improve it? ^^ PR is welcome!

**Comment by Cardosaum** [comment]
Yeah! I'd like to help @charlesdong1991 !

This will be my first PR on github :)

I've just two questions:

1) Do you know what does `# noqa: E225, E999` mean? (Should I keep it or it's better to remove from text?)

2) Do I need to create `issues` on github for this small details in documentation or it's fine to just submit PRs correcting them ?

**Comment by charlesdong1991** [comment]
Go for it! @Cardosaum 

noqa usually indicates linter to ignore pep8 warnings in this code, I did not know who made it, but since it only shows the subset of returned output here due to limited space, maybe it is the reason to ignore some specific warnings?

and I think you could just keep as is, and just add the thing you want to address.

**Comment by Cardosaum** [comment]
Alright, thanks for the explanation @charlesdong1991 !

**Comment by Cardosaum** [comment]
take
