### ISSUE TITLE
`style` settings overwrite all `display` settings

### ISSUE THREAD

**Issue by lucatrv** [pandas-dev/pandas#31530]
The following code reproduces the issue:

```python
import pandas as pd
from IPython.display import display
pd.options.display.float_format = "{:,.1f}".format
df = pd.DataFrame([1000.1234, 2000.1234])
display(df)
display(df.style.hide_index())
```

Output:
![image](https://user-images.githubusercontent.com/8380499/73590262-c1064c80-44e0-11ea-90b8-aca4c55d243c.png)

IMHO `style.hide_index()` should not overwrite the previous `display.float_format` setting, only `style.format` should do it.

**Comment by TomAugspurger** [comment]
I don't think we want display settings affecting Styler, which is more about "exporting" data than displaying it. Things like truncation, max_rows, etc, also don't have any effect.

**Comment by mroeschke** [comment]
Sounds like this is more-or-less the intended behavior as display has a slightly different purpose than using styler.

Going to close as the expected behavior but happy to reopen if others from the core team have other opinions
