### ISSUE TITLE
DOC: Mention that boolean indexing is impossible for new nullable integer/boolean and string data types when they contain missing values

### ISSUE THREAD

**Issue by tdpetrou** [pandas-dev/pandas#31537]
The new data types nullable integer, nullable boolean, and string cannot do boolean indexing when the columns contain missing values. 

I searched the [pd.NA][0] and the [boolean indexing][1] sections and have not seen this mentioned. Users need to be aware of this limitation as it greatly reduces their usability.

[0]: https://pandas.pydata.org/docs/user_guide/missing_data.html#experimental-na-scalar-to-denote-missing-values
[1]: https://pandas.pydata.org/docs/user_guide/indexing.html#boolean-indexing

**Comment by jorisvandenbossche** [comment]
The docs can certainly be better organised and interlinked, but it is (briefly) mentioned here: https://pandas.pydata.org/docs/user_guide/boolean.html#indexing-with-na-values

**Comment by anant4299** [comment]
I will add that to the pd.NA and boolean indexing sections and will search for any other section that might need that information.

**Comment by rhshadrach** [comment]
This is no longer the case - Boolean indexing is allow, and is documented properly in the link above. Closing.
