### ISSUE TITLE
WEB: Wrong links on web page

### ISSUE THREAD

**Issue by topper-123** [pandas-dev/pandas#31539]
On [this page ](https://pandas.pydata.org/ )The link at "what's new in 1.0.0" (upper right corner) points to the v0.25 whatsnew.

On [this page](https://pandas.pydata.org/docs/index.html) the link on the upper left side logo points to the same page. I would expect it to point to the main page (https://pandas.pydata.org/).

**Comment by sohamtiwari3120** [comment]
I would like to work on this!

**Comment by sohamtiwari3120** [comment]
Just to be sure, you mean that, that the "What's New in 1.0.0" on [this page](https://pandas.pydata.org/), which redirects to what's new in v0.25.0 should actually redirect to what's new in v1.0.0

**Comment by jorisvandenbossche** [comment]
Closed by #31567
