### ISSUE TITLE
DOC issue of rendering for the docsting of pd.set_option

### ISSUE THREAD

**Issue by glemaitre** [pandas-dev/pandas#31531]
It seems that the `pd.set_option` docsting is not parsed properly by `sphinx`:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.set_option.html

It was already the case in 0.25 doc but it was working in 0.23:

https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.set_option.html

**Comment by alimcmaster1** [comment]
Duplicate of https://github.com/pandas-dev/pandas/issues/28780
