### ISSUE TITLE
Add TODOs Badge to the README

### ISSUE THREAD

**Issue by patrickdevivo** [pandas-dev/pandas#31560]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `// TODO` comments are in this codebase:

[![TODOs](https://img.shields.io/endpoint?url=https://todos.tickgit.com/badge?repo=github.com/pandas-dev/pandas)](https://todos.tickgit.com/browse?repo=github.com/pandas-dev/pandas)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for new contributors to find areas of code to improve.

The markdown is:

```
[![TODOs](https://img.shields.io/endpoint?url=https://todos.tickgit.com/badge?repo=github.com/pandas-dev/pandas)](https://todos.tickgit.com/browse?repo=github.com/pandas-dev/pandas)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

**Comment by leandermaben** [comment]
I would like to work on the issue

**Comment by alimcmaster1** [comment]
> It can help surface latent work and be a way for new contributors to find areas of code to improve.

I think we would prefer new contributors to use the github issue tracker. TODOs in the codebase are often ill described or outdated or of a unknown difficulty. 

That said its actually interesting to see them all on one page. So i'm fine either with this. Just don't think we should point new contributors to it :)

**Comment by leandermaben** [comment]
Sure
Thank you for taking the time to respond.

**Comment by jorisvandenbossche** [comment]
I agree with @alimcmaster1, I also wouldn't point new contributors to that (our TODO's are not always up to date, often lack information for newcomers to understand, etc), so I would rather not add it to the readme then.

**Comment by patrickdevivo** [comment]
> I think we would prefer new contributors to use the github issue tracker. TODOs in the codebase are often ill described or outdated or of a unknown difficulty.
> 
> That said its actually interesting to see them all on one page. So i'm fine either with this. Just don't think we should point new contributors to it :)

That makes sense to me. I think TODO comments can often be a precursor to a proper ticket/issue rather than equivalent to one. FYI a feature coming soon is a button to link directly to github issue creation from a TODO that's been indexed. I think generally, it's useful to surface TODOs as a means of not letting too many get lost (either by just displaying and aggregating them or by making it easier to produce tickets/issues from them).

**Comment by alimcmaster1** [comment]
Do let us know when that feature is available @patrickdevivo. Il close this for now but feel free to reopen. Maybe @jbrockmendel would fine this handy?

https://todos.tickgit.com/browse?repo=github.com/pandas-dev/pandas

**Comment by patrickdevivo** [comment]
I just wanted to circle back here with some updates! The new view I mentioned has been launched: https://www.tickgit.com/browse?repo=github.com/pandas-dev/pandas with a card layout that should hopefully be clearer to read than the previous table layout. Cards also include a button to make a Github issue directly from a TODO.

Pretty soon there will be more advanced filtering options as well, allowing users to lookup only TODOs they've created, within a time range, or within a particular directory.

I hope the project remains interesting! If there's any desire to add a badge to this repo, I'd be happy to open a PR.

Thanks so much
