### ISSUE TITLE
pandas.read_json(..., split='orient') builts DatetimeIndex instead of using 'index' attribute of json file

### ISSUE THREAD

**Issue by achatrian** [pandas-dev/pandas#31570]
#### Code Sample, a copy-pastable example if possible
```python
from pathlib import Path
import json
import pandas as pd

path_to_json = Path('path/to/json')
with open(path_to_json, 'r') as feature_file:
    features = pd.read_json(feature_file, orient='split')

with open(path_to_json, 'r') as feature_file:
    feats_= json.load(feature_file)

print(all(a == b for a, b in zip(feats_['index'],list(features.index))))
features.index = feats_['index']  # shouldn't be necessary 
print(features.index)
```

#### Problem description
I serialised a dataframe into json using the split options.
When deserializing, a DatetimeIndex is built instead of using the 'index' attribute of my JSON file.
DatetimeIndex(['1970-02-03 08:19:30.607525111',
               '1970-02-14 00:59:30.563649155',
               '1970-02-13 07:19:30.563381155',
               '1970-02-24 13:12:50.531381187',
               '1970-02-08 10:26:10.515841203',
               '1970-03-08 23:19:30.493779225',
               '1971-08-16 21:55:04.791319239',
               '1970-02-26 21:36:10.419351299',
               '1970-02-23 23:29:30.419351299',
               '1970-02-19 06:36:10.403239135',
               ...
               '1970-01-31 23:21:55.267811637',
               '1970-01-24 21:11:55.235221241',
               '1970-03-14 10:11:55.143305301',
               '1970-01-23 10:41:54.983117151',
               '1970-02-15 09:58:34.929541359',
               '1970-03-23 04:05:14.823177145',
               '1970-03-13 09:31:54.807145225',
               '1970-03-10 18:05:14.347205225',
               '1970-01-20 07:21:54.347143145',
               '1970-01-17 06:11:54.347269257'],
              dtype='datetime64[ns]', length=5294, freq=None)

My JSON file:
[TCGA-2A-AAYO-01Z-00-DX1.A5BB3437-956A-4A42-AC28-1217B8016970.zip](https://github.com/pandas-dev/pandas/files/4144042/TCGA-2A-AAYO-01Z-00-DX1.A5BB3437-956A-4A42-AC28-1217B8016970.zip)

#### Expected Output
True,
Index(['28811_70607_525_111', '38051_70563_649_155', '37415_70563_381_155',
       '47131_70531_381_187', '33207_70515_841_203', '57863_70493_779_225',
       '51227_70479_1319_239', '49161_70419_351_299', '46637_70419_351_299',
       '42573_70403_239_135',
       ...
       '26761_15267_811_637', '20635_15235_221_241', '62575_15143_305_301',
       '19393_14983_117_151', '39239_14929_541_359', '70131_14823_177_145',
       '61687_14807_145_225', '59403_14347_205_225', '16681_14347_143_145',
       '14047_14347_269_257'],
      dtype='object', length=5294)
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.3.0-28-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.0.0
numpy            : 1.16.3
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 42.0.2.post20191201
Cython           : None
pytest           : 4.5.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.10.1
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : 1.3.1
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 4.5.0
pyxlsb           : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : 3.4.4
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
numba            : 0.43.1

</details>

**Comment by mroeschke** [comment]
Is this possible to reproduce with a more minimal example? https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by mroeschke** [comment]
Closing in the meantime due to inactivity, but let us know if you can simplify your issue as noted in link above.
