### ISSUE TITLE
what is the future of nanosecond in parquet?

### ISSUE THREAD

**Issue by goldenbull** [pandas-dev/pandas#31572]
pandas 1.0.0

sample code as below:

```python
import pandas as pd

df = pd.DataFrame(data=range(123456000, 123456789), columns=["c1"])
df["c2"] = pd.Timestamp("2020-01-31") + pd.to_timedelta(df["c1"], "ns")
df.to_parquet('nanosecond-test.parquet',
              # use_deprecated_int96_timestamps=True
              )
```
without `use_deprecated_int96_timestamps=True`, an exception will raise:
```
...
  File "C:\dev\.venv\lib\site-packages\pyarrow\parquet.py", line 474, in write_table
    self.writer.write_table(table, row_group_size=row_group_size)
  File "pyarrow\_parquet.pyx", line 1375, in pyarrow._parquet.ParquetWriter.write_table
  File "pyarrow\error.pxi", line 78, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Casting from timestamp[ns] to timestamp[ms] would lose data: 1580428800123456000
```

my question is: will nanoseconds not be supported by parquet format in the future? or there will be some other way to convert nanoseconds between pandas and parquet?

**Comment by TomAugspurger** [comment]
That's coming from pyarrow. You should ask on their mailing list.

My (possibly incorrect) understanding is that using int96 for timestamps was added for Spark compatibility, and Spark has deprecated that as well. You'll still be able to write ns-precision timestamps as int64s.

**Comment by jorisvandenbossche** [comment]
Parquet version 2.0 will support nanosecond timestamp data (https://github.com/apache/parquet-format/blob/890af2212341aa914486a14e8d2c9b86284b40e4/src/main/thrift/parquet.thrift#L257-L275), however, this version is not yet recommended to use in practice (Arrow doesn't fully support it yet, and spark even less, as far as I know)

With parquet version 1.0 (the default), you can either use the "use_deprecated_int96_timestamps" , live with the MICRO resolution, or as Tom mentions store the nanoseconds as integers.
