### ISSUE TITLE
`Series.isin` does not return all values in the column

### ISSUE THREAD

**Issue by Dpananos** [pandas-dev/pandas#31595]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np

print(pd.__version__)

df = pd.DataFrame({'t': np.arange(0.5, 2.0, 0.1)})

slxn = df.t.isin(np.arange(0.5, 2.0, 0.5))

slxn.sum()
```
#### Problem description

`df` is a data frame with a single column called `t`.  The values of this column range from 0.5 to 2.0 in increments of 0.1.

There should be three values in `slxn` which are `True`, however the expression above yields 1.

#### Expected Output

```python
>>>slxn.sum()
3
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_CA.UTF-8
LOCALE           : en_CA.UTF-8

pandas           : 1.0.0
numpy            : 1.17.4
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.1.0.post20200127
Cython           : 0.29.14
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.10.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 0.14.1
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by jreback** [comment]
trying to index floats exactly is fraught with risk
because of numerical precision 

show the example with full precision of all values
