### ISSUE TITLE
DOC: pandas.Series.dt.day has incorrect docs

### ISSUE THREAD

**Issue by julienprieur** [pandas-dev/pandas#31604]
See https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dt.day.html#pandas.Series.dt.day. 

The documentation shows the description for dt.month and not dt.day.

**Comment by MarcoGorelli** [comment]
Thanks @julienprieur , good catch - are you interested in [submitting a pull request](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html)?

**Comment by julienprieur** [comment]
Failing to find out the location of the doc string in the source tree, I found that this was already fixed few days ago in commit #298fc15930d75f18328ca166295c9de023e3a1a6.
