### ISSUE TITLE
How to determine the severity of skewness(nanskew) such as highly skewed,moderately skewed,normally distributed,etc by interpreting the returned numerical values from the .skew() function.

### ISSUE THREAD

**Issue by getsrikar** [pandas-dev/pandas#31600]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

```
#### Problem description

The given documentation available below doesn't provide any specifics about the skewness results interpretation.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.skew.html

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by getsrikar** [comment]
The given documentation available below doesn't provide any specifics about the skewness results interpretation.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.skew.html

**Comment by MarcoGorelli** [comment]
Hi @getsrikar . I'll close ths for now as we recommend [stackoverflow](https://stackoverflow.com/questions/tagged/pandas) for usage questions, this is for bug reports
