### ISSUE TITLE
pd.NA is converted to {} instead of null with pd.DataFrame.to_json

### ISSUE THREAD

**Issue by pvieito** [pandas-dev/pandas#31615]
#### Code Sample

```python
import numpy as np
import pandas as pd

pd.DataFrame([[np.nan]], columns=["NA"]).to_json(orient="records")
# '[{"NA":null}]'
pd.DataFrame([[None]], columns=["NA"]).to_json(orient="records")
# '[{"NA":null}]'
pd.DataFrame([[pd.NA]], columns=["NA"]).to_json(orient="records")
# '[{"NA":{}}]'
```
#### Problem Description

`pd.NA` should behave as `np.nan` and `None` when converting a DataFrame to JSON.

#### Expected Output

In the resulting JSON the `pd.NA` instances should be converted to JSON's `null`.

**Comment by jorisvandenbossche** [comment]
@pvieito Thanks for the report! That's indeed buggy

**Comment by itsshavar** [comment]
json writer is having some issue

**Comment by ArtificialQualia** [comment]
I got this one, some changes are needed in ujson.
