### ISSUE TITLE
Does #28827 also apply to applymap?

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#31620]
In  #28854, the note 

> In the current implementation applymap calls func twice on the first column/row to decide whether it can take a fast or slow code path. This can lead to unexpected behavior if func has side-effects, as they will take effect twice for the first column/row.

was removed from the `DataFrame.apply` docstring.

However, it is still in the [docstring](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.applymap.html?highlight=applymap#pandas.DataFrame.applymap) of `DataFrame.applymap`.

Does it need to be removed there too?

EDIT
----

As far as I can tell, this behaviour (calling the function twice to decide which path to take) still happens for `groupby.apply` and is what a user was asking about in #31111. Does it need to be documented in Groupby.Apply? Do end-users need to know about such internals?

**Comment by r0cketr1kky** [comment]
I guess this should be included in `groupby.apply` for the end-users to be aware of such cases. I would love to take this up.

**Comment by MarcoGorelli** [comment]
Sure, you can assign issues to yourself by commenting "take", see the following from the contributing guide:

> 
> When you start working on an issue, it’s a good idea to assign the issue to yourself, so nobody else duplicates the work on it. GitHub restricts assigning issues to maintainers of the project only. In most projects, and until recently in pandas, contributors added a comment letting others know they are working on an issue. While this is ok, you need to check each issue individually, and it’s not possible to find the unassigned ones.
> 
> For this reason, we implemented a workaround consisting of adding a comment with the exact text take. When you do it, a GitHub action will automatically assign you the issue (this will take seconds, and may require refreshint the page to see it). By doing this, it’s possible to filter the list of issues and find only the unassigned ones

**Comment by r0cketr1kky** [comment]
take
