### ISSUE TITLE
PERF: Indexing a multi-index is a lot slower

### ISSUE THREAD

**Issue by valtron** [pandas-dev/pandas#31648]
Indexing a multi-index seemingly went from O(1) to O(N):

![bug](https://user-images.githubusercontent.com/123696/73701369-91a13c80-46a6-11ea-8335-6a8e7a3f7dca.png)

I did a bisect, and found this was caused by the `_shallow_copy` here: https://github.com/pandas-dev/pandas/commit/b0f33b3f40d5742531e31aef90573b9592489592#diff-4ffd1c69d47e0ac9f2de4f9e3e4a118cR643.

#### Code Sample

```python
from time import perf_counter as time
import pandas as pd

for N in [1000, 2000, 4000, 8000, 16000, 32000]:
	values = list(range(N))
	df = pd.DataFrame({ 'a': values })
	df['b'] = 1
	df.set_index(['a', 'b'], inplace = True)

	t = time()
	df.loc[values]
	t = time() - t
	print(N, t)
```

**Comment by TomAugspurger** [comment]
Mmm, thanks for bisecting things. I'm a bit surprised to see that the `shallow_copy` is causing issues. It should be relatively cheap.

cc @topper-123.

**Comment by TomAugspurger** [comment]
Changing `levels` to cache_readonly seems to help.

```diff
diff --git a/pandas/core/indexes/multi.py b/pandas/core/indexes/multi.py
index c560d81ba9..95921bd90e 100644
--- a/pandas/core/indexes/multi.py
+++ b/pandas/core/indexes/multi.py
@@ -677,7 +677,7 @@ class MultiIndex(Index):
     # --------------------------------------------------------------------
     # Levels Methods
 
-    @property
+    @cache_readonly
     def levels(self):
         result = [
             x._shallow_copy(name=name) for x, name in zip(self._levels, self._names)
```

With that, I see the timings

```
1000 0.1286114020000042
2000 0.26856144899999634
4000 0.5997097740000044
8000 1.2386244449999992
16000 3.030814161000002
32000 7.507717883000005
```

I'm not sure, but I suspect that the IndexEngine was previously cached, and `MultiIndex.get_locs` involves many calls to Index.get_loc. The change in https://github.com/pandas-dev/pandas/commit/b0f33b3f40d5742531e31aef90573b9592489592#diff-4ffd1c69d47e0ac9f2de4f9e3e4a118cR643 was returning a new index object, and the cache was lost (maybe).

**Comment by topper-123** [comment]
Thanks for the report @valtron.

``MultiIndex._shallow_copy`` could benefit from a refactor and definately shouldn't cause a slowdown like here. I had a small discussion on the subject [here](https://github.com/pandas-dev/pandas/pull/27242#discussion_r300793695) (maybe unrelated to this specific issue, but it's the same theme).

If _shallow_engine doesn't move the reference to the indexing engine over to the new index, I'd think that should be considered a performance bug. I.e. we should probably have that ``mi._shallow_copy()._engine is mi._engine``, which a casusual rundown shows is not the case in master.

@TomAugspurger , wouldn't you agree that ``idx._shallow_copy()._engine is idx._engine`` should be True in general? The indexing engines are expensive to create, but immutable, so we should copy reference where possible.

**Comment by TomAugspurger** [comment]
> wouldn't you agree that idx._shallow_copy()._engine is idx._engine should be True in general?

Yep, that's https://github.com/pandas-dev/pandas/issues/28584. Caching those makes sense to me.

**Comment by jbrockmendel** [comment]
> Changing levels to cache_readonly seems to help.

IIRC there was an issue a few weeks ago with MultiIndex names propogating to levels.  If we cache `levels` and then change the names on a MultiIndex, will subsequent levels calls have the wrong names?

> wouldn't you agree that idx._shallow_copy()._engine is idx._engine should be True in general?

That sounds like a good idea.

**Comment by TomAugspurger** [comment]
> and then change the names on a MultiIndex, will subsequent levels calls have the wrong names?

See https://github.com/pandas-dev/pandas/pull/31651. `MultiIndex._set_names` now includes a call to `self._reset_cache`

**Comment by topper-123** [comment]
Right, I had forgotten about that issue. Shouldn't be too difficult to fix.

**Comment by taozuoqiao** [comment]
Has the issue been fixed? It seems that it still exists in lastest pandas, or is there a solution for this?

Thanks very much.

-----------------------
Code
```python
from time import perf_counter as time
import pandas as pd
from matplotlib import pyplot as plt
print(pd.__version__)

costs = []
nums = 10*2**np.arange(1,12)
for n in nums:
    data = pd.Series(np.arange(n**2), index=pd.MultiIndex.from_product([np.arange(n), -np.arange(n)]))

    t = time()
    data.loc[1]
    t = time() - t
    costs.append(t)
    print(n, t)
plt.plot([num**2 for num in nums], costs, 'o-')
plt.show()
```
The output
```
1.3.4
20 0.0003912000101990998
40 0.00023500004317611456
80 0.00028410000959411263
160 0.00040820002323016524
320 0.0010468000546097755
640 0.004912000033073127
1280 0.01685159996850416
2560 0.06720160000259057
5120 0.23266949999378994
10240 0.9400221999967471
20480 3.795060899981763
```
![image](https://user-images.githubusercontent.com/18346451/145360241-01e57b90-e176-47a1-80fc-46d3be8186e6.png)
