### ISSUE TITLE
replace method does't work with string type Series

### ISSUE THREAD

**Issue by GYHHAHA** [pandas-dev/pandas#31644]
#### Code Sample, a copy-pastable example if possible

```python
>>>pd.Series(['A','B']).replace(r'.','C',regex=True)
0    C
1    C
dtype: object
pd.Series(['A','B']).astype('string').replace(r'.','C',regex=True)
0    A
1    B
dtype: string
```
#### Problem description

It seems that replace doesn't work with the string type Series.
Why these two codes return different results?

**Comment by charlesdong1991** [comment]
thanks for the report!

which version of pandas do you use? Could you test it on the current master? i think this should work on master now?

**Comment by charlesdong1991** [comment]
could remove that `r` and use `pd.Series(['A','B']).astype('string').replace('.','C',regex=True)`, i think then should work

**Comment by GYHHAHA** [comment]
```python
>>>pd.Series(['A','B']).astype('string').replace('.','C',regex=True)
0    A
1    B
dtype: string
```
Thanks for answer !
But still not work.
And also I want to ask a related question.
Since the str.replace for string does not allow pd.NA for the parameter 'repl', if I want change some strings which meet a certain regex condition to pd.NA, how can I get the correct result. Thanks !

**Comment by charlesdong1991** [comment]
you mean this `pd.Series(['A','B']).astype('string').replace('A', pd.NA)`?
works to me:
```python
>>> pd.Series(['A','B']).astype('string').replace('A', pd.NA)
0    <NA>
1       B
dtype: string
```

**Comment by GYHHAHA** [comment]
Oh? I get an error.
'''python
>>>pd.Series(['A','B']).astype('string').replace('A', pd.NA)
IndexError: arrays used as indices must be of integer (or boolean) type
'''

**Comment by charlesdong1991** [comment]
Are you running it on master branch?

**Comment by GYHHAHA** [comment]
I have already updated to the latest version 1.0.0.

**Comment by charlesdong1991** [comment]
yeah, there are some fixes after 1.0.0, but not released yet, so some new fixes can only be tested on master. Please let me know if you still have this issue on pandas master branch

**Comment by GYHHAHA** [comment]
Oh, I haven't do that.
I will run it on master branch and check the issue again.
Thanks !

**Comment by GYHHAHA** [comment]
It works for the pd.NA issue on master branch, but still not work for the original issue. @charlesdong1991

**Comment by charlesdong1991** [comment]
thanks for confirming the issue on master, are you interested in investigating what made it change? @GYHHAHA

**Comment by GYHHAHA** [comment]
Sorry, I'm not sophisticated on the Pandas source code, but I will pay close attention on that when the next version releases.
And also, it seems when pd.NA appears in the Series, an error will be raised for the replace method.
```python
>>>pd.Series(['A',np.nan],dtype='O').replace('A','B')
0      B
1    NaN
dtype: object
>>>pd.Series(['A',np.nan],dtype='string').replace('A','B')
AssertionError: B
``` 
The error seems also not very clear.

**Comment by charlesdong1991** [comment]
thanks for the report, your finding is very helpful!! @GYHHAHA 

i will look into it a bit

**Comment by charlesdong1991** [comment]
take

**Comment by GYHHAHA** [comment]
I guess a rough reason for that is, not like the np.nan, the pd.NA doesn't stand for a constant value, so when launch a match for 'A', it's not clear whether pd.NA equals 'A', so the error is raised.
Just my guess. : )

**Comment by GYHHAHA** [comment]
Is it possible to take pd.NA as a legal choice for the 'repl' parameter of str.replace method in the latter version? It seems to be more natural.

**Comment by mroeschke** [comment]
Looks to work on master now. Could use a test

```
In [20]: pd.Series(['A','B']).astype('string').replace(r'.','C',regex=True)
Out[20]:
0    C
1    C
dtype: string
```

**Comment by SidharthArya** [comment]
take

**Comment by klimpt** [comment]
I think there is another bug:

```python
>>> pd.Series([pd.NA, "a"]).astype("string").replace(["a"], "b", regex=True) #replace does nothing
0    <NA>
1       a
dtype: string
pd.Series([pd.NA, "a"]).astype("string").replace("a", "b", regex=True) #replace works as expected
0    <NA>
1       b
dtype: string
```

**Problem description**
If series contains `pd.NA` **and** dtype is string **and** `regex=True`**and** `to_replace` is a list or a dict, then replace does not work.

**Comment by paulbeckmann** [comment]
The bug with pd.NA also occurs **within** a series such that all values _below_ a pd.NA are not replaced: 

`>>> pd.Series(["a", pd.NA, "a"]).astype("string").replace(["a"], "b", regex=True)
0       b
1    <NA>
2       a`
