### ISSUE TITLE
DOC: extending pandas page is not rendered correctly

### ISSUE THREAD

**Issue by charlesdong1991** [pandas-dev/pandas#31645]
https://pandas.pydata.org/pandas-docs/stable/development/extending.html

this is the first result gotten by googling extending pandas, however, seems not rendered correctly, help is welcome!

**Comment by MarcoGorelli** [comment]
I just clicked on it and it seems like the rendering is alright: 
![image](https://user-images.githubusercontent.com/33491632/73736965-a11d9580-4739-11ea-85bd-9fd571bdac18.png)

**Comment by charlesdong1991** [comment]
oh, interesting, i got this, for the other sections, all work fine 🤔
<img width="1047" alt="Screen Shot 2020-02-04 at 11 49 59 AM" src="https://user-images.githubusercontent.com/9269816/73738299-8ac90700-4744-11ea-94bc-9097d8f99109.png">

**Comment by jorisvandenbossche** [comment]
@charlesdong1991 do you consistently get it, also after refreshing the page?

**Comment by charlesdong1991** [comment]
@jorisvandenbossche i consistently get it, however, after refreshing the page, i get the right one back 🤔 feel weird

**Comment by charlesdong1991** [comment]
oh, weird, i now could click and get the right rendering 😅 i will close then, somehow weird though, thanks @jorisvandenbossche @MarcoGorelli

**Comment by jorisvandenbossche** [comment]
I assume for some reason, the bootstrap css was not loaded properly. If you encounter this more, feel free to open an issue on https://github.com/pandas-dev/pydata-bootstrap-sphinx-theme/, there might be ways to optimize this loading.
