### ISSUE TITLE
https://pandas.pydata.org/pandas-docs/version/ gives a 403 Forbidden error.

### ISSUE THREAD

**Issue by dumbledad** [pandas-dev/pandas#31657]
On the pandas website at https://pandas.pydata.org/ if I click on the drop-down menu titled 'documentation' and then select 'older versions' I am taken to https://pandas.pydata.org/pandas-docs/version/ which gives a 403 Forbidden error.

**Comment by TomAugspurger** [comment]
@datapythonista do you know where that link is supposed to go?

**Comment by datapythonista** [comment]
It's a page we didn't build. My idea was to have the versioning of the docs in the web, but it's finally in the docs. Not sure if it make sense to implement it or not.

See #30891 for status of the discussion about that link and the rest of the docs links.
