### ISSUE TITLE
Documentation for divmod and rdivmod gives wrong return type

### ISSUE THREAD

**Issue by stephendavidmarsh** [pandas-dev/pandas#31663]
See https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.divmod.html#pandas.Series.divmod
and https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.rdivmod.html#pandas.Series.rdivmod

The documentation incorrectly says that the `divmod` and `rdivmod` returns Series. However, both methods actually return 2-tuples containing two series.

**Comment by MarcoGorelli** [comment]
Thanks @stephendavidmarsh , seems you're right - interesting in submitting a PR? See the [contributing guide](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html) for how to get started

**Comment by stephendavidmarsh** [comment]
I was originally going to try to put together a PR, but couldn't find where the doc was coming from. Searching for "class Series" or "def divmod" on Github wasn't productive.

**Comment by r0cketr1kky** [comment]
If it's not taken, I would like to work on this issue.

**Comment by MarcoGorelli** [comment]
@stephendavidmarsh did you try searching for any other words from the docstring  (e.g. modulo)?

**Comment by data-RanDan** [comment]
Hey, I'd love to give it a shot (first issue)

**Comment by ShamanthNyk** [comment]
I would like to work on this issue.

**Comment by MarcoGorelli** [comment]
Pull requests are welcome

**Comment by avinashpai** [comment]
take

**Comment by naterarmstrong** [comment]
take

**Comment by naterarmstrong** [comment]
take
