### ISSUE TITLE
Inconsistent kwargs argument 'color' passed to upstream matplotlib plot functions

### ISSUE THREAD

**Issue by xuancong84** [pandas-dev/pandas#31691]
In matplotlib.pyplot.bar , there is a keyword argument called 'color' which can control the color of all bars as well as each bar, e.g.,
<img width="639" alt="image" src="https://user-images.githubusercontent.com/10172392/73830682-08257200-4840-11ea-9aa0-64bb6bb2b9ab.png">

However, in Pandas DataFrame.plot.bar, by passing a list into 'color', the color of all bars is controlled only by the 1st element in the list, i.e.,
<img width="630" alt="image" src="https://user-images.githubusercontent.com/10172392/73831000-900b7c00-4840-11ea-8121-fe139365fdfc.png">

Ironically, if we pass in a list of list into 'color', we can control the color of each bar, i.e.,
<img width="651" alt="image" src="https://user-images.githubusercontent.com/10172392/73832150-9995e380-4842-11ea-9e35-6345364168b5.png">

So my question is why the behavior of the 'color' argument different from that in matplotlib? Is this intended inconsistency?

**Comment by charlesdong1991** [comment]
thanks for posting @xuancong84 

probably this could be clarified/better defined, but seems color is defined per column when you are using `pd.DataFrame` to plot, so in your case, since they all in the same column, they will get the first color set by `color`, and `color[0]` in your example is `red`. If doing below, all three colors are assigned:
```python
pd.DataFrame({"v1": [3,6,2], "v2": [2,1,5], "v3": [4,5,6]}).plot(kind="bar", color=["r", "b", "y"])
```

If you would like to make it work, you should use `pd.Series` to plot:
```python
pd.Series([3, 6, 2]).plot(kind="bar", color=["r", "b", "y"])
```
I think you will get the desired figure through the code above.

**Comment by xuancong84** [comment]
Thanks @charlesdong1991 , does that mean if we use pd.DataFrame.plot.bar to plot, it actually calls pyplot.bar several times, once for each column? Thus, all kwargs have to be packed into a list?

**Comment by charlesdong1991** [comment]
@xuancong84 indeed, `ax.bar` will be called three times in this case

> all kwargs have to be packed into a list

I am not sure what you mean by `all kwargs`, I haven't double checked, but i remember there are some postprocessings on `color`, but for some arguments, i think they will be shared by all, e.g. `rot`, right?

**Comment by xuancong84** [comment]
@charlesdong1991 , thanks for your info. I refer `all kwargs` to those additional keyword arguments such as `color=`, `ax=`, `rot=`, etc., that will be passed to upstream matplotlib plot functions.

Since not all of these arguments will be unpacked before passing to matplotlib, to avoid this confusion, I would like to suggest that: for all those arguments that will be unpacked, add a prefix or suffix to distinguish, e.g., instead of `color`, name it `color_packed`, `color_list`, `multi_color` or `packed_color`, etc. So that users will know that this keyword argument will be unpacked and passed to upstream matplotlib plot function, one for each column of the DataFrame. What do you think?

**Comment by charlesdong1991** [comment]
thanks for your suggestion @xuancong84  i think renaming the argument/having new similar argument is an API change and might cause confusion to users, especially if this only works for `pd.DataFrame.plot`. 

I think the easiest way is to have a better docstring for `color` argument, and clarify those scenarios.

@TomAugspurger might have better opinions on it?

**Comment by xuancong84** [comment]
Thanks @charlesdong1991 ! Yup, revising the documentation for `color` in `pd.DataFrame.plot` is the minimum needed to be done. But whether to apply this convention to every matplotlib keyword argument and even to every function, depends on whether there exists such a need. Pandas developers should examine and evaluate on this carefully in order to make a better decision.

**Comment by mfenner1** [comment]
There are similar issues with `pd.Series.plot`.  For example:

```python
import pandas as pd
import matplotlib
print(pd.__version__) # ---> 1.0.3
print(matplotlib.__version__) # ---> 3.1.3

# ok, line plot
pd.Series([5, 10, 20]).plot(color='r')

# ok, red dots 
pd.Series([5, 10, 20]).plot(style='.', color='r')

# fails
pd.Series([5, 10, 20]).plot(style='o', color='r')

# the following only applies the first color (red)
# --> all three points are red
pd.Series([5, 10, 20]).plot(style='.', color=['r', 'g', 'b'])
```

With`import matplotlib.pyplot as plt`:
```python
# works
plt.plot([5, 10, 20], marker='o', color='r')

# fails
plt.plot([5, 10, 20], marker='o', color=['r', 'g', 'b'])
```

**Comment by MarcoGorelli** [comment]
Hi @xuancong84 

> Yup, revising the documentation for color in pd.DataFrame.plot is the minimum needed to be done

Are you interested in submitting a PR?

**Comment by xuancong84** [comment]
> Are you interested in submitting a PR?
Sorry, what is PR?

**Comment by MarcoGorelli** [comment]
PR = Pull Request, see [contributing to pandas](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html)

**Comment by ankushduacodes** [comment]
Hi @MarcoGorelli, I would love to contribute to this issue. Please let me know if I may :)

**Comment by MarcoGorelli** [comment]
of course!

**Comment by ankushduacodes** [comment]
@MarcoGorelli As This will be my first contribution to pandas repo, Could you please give some pointer on this issue, I would really appreciate that.

**Comment by MarcoGorelli** [comment]
@ankushduacodes for a start, read through the contributing guide linked above.

After that, I think what needs to be done to close this issue is to reword the docstring for `DataFrame.plot.bar`. Currently, for `color`, it reads:
```
code, which will be used for each column recursively. For instance [‘green’,’yellow’] each column’s bar will be filled in green or yellow, alternatively.
```
This can probably be clarified, maybe by noting that if you only have a single column, then only the first colour in the list will be used
