### ISSUE TITLE
Where did check_bool_array_indexer move to?

### ISSUE THREAD

**Issue by achapkowski** [pandas-dev/pandas#31696]
I was leveraging the following:

```
pd.api.indexers.check_bool_array_indexer
```

And at v1.0.0, it is gone, what is the comparable operation to this?

**Comment by jorisvandenbossche** [comment]
It was renamed to `pd.api.indexers.check_array_indexer` and extended to also check integer arrays (not only boolean ones) during the RC.

(we currently don't really have a good way to list relevant changes since the RC in the whatsnew file ..)

**Comment by achapkowski** [comment]
Thank you
