### ISSUE TITLE
ValueError: buffer source array is read-only

### ISSUE THREAD

**Issue by kernc** [pandas-dev/pandas#31710]
#### Code Sample, a copy-pastable example if possible

```python
>>> index = pd.date_range('2020', 'now', freq='1h') 
>>> arr = np.zeros_like(index) 
>>> arr.setflags(write=False)
>>> pd.Series(arr, index=index).resample('1d').agg('last')

-------------------------------------------------------------------------
~/pandas/pandas/_libs/groupby.pyx in pandas._libs.groupby.group_last()
~/pandas/pandas/_libs/groupby.cpython-37m-x86_64-linux-gnu.so in View.MemoryView.memoryview_cwrapper()
~/pandas/pandas/_libs/groupby.cpython-37m-x86_64-linux-gnu.so in View.MemoryView.memoryview.__cinit__()
ValueError: buffer source array is read-only
```
#### Problem description

Groupby fails on some read-only buffers (I couldn't quickly reproduce it with `.groupby()` itself, sorry).

The prime solution would be to add `const` specifier to the input `values` here (and related entries):
https://github.com/pandas-dev/pandas/blob/0b6debf825db39f8f63d300cb8007a7996d002fc/pandas/_libs/groupby.pyx#L853

if it were not for Cython's non-support of const fused types (https://github.com/cython/cython/issues/1772), resolved in (https://github.com/cython/cython/pull/3118), but despite [miniscule change](https://github.com/cython/cython/pull/3118/files?file-filters%5B%5D=.py) only scheduled for release in Cython 3.0. I guess wait until then.

#### Expected Output

Resampling/groupby works with read-only arrays.

#### Output of ``pd.show_versions()``

pandas 1.1.0.dev0+361.gf0b00f887
cython 0.29.14

**Comment by PaddyAlton** [comment]
I think I've found a related issue with `isin` (at least, it throws the same sort of error!). May give some more insight though, as it was tricky to reproduce:

```
# python 3.6, on a Windows machine, Anaconda distribution
import numpy as np  # v1.16.4, then v1.18.1
import pandas as pd  # v1.0.1

arr = np.array([1,2,3], dtype=np.int64) # works fine if I don't set the dtype!

arr.setflags(write=False) # make it read-only

df = pd.DataFrame({"col": [2,4,8]})

test = df.col.isin(arr)
```

... and this then raises an exception as above:

```
...
pandas\_libs\hashtable_func_helper.pxi in pandas._libs.hashtable.ismember_int64()                                                                                                                                                                                                                                                               ~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\_libs\hashtable.cp37-win_amd64.pyd in View.MemoryView.memoryview_cwrapper()                                                                                                                                                                                                        ~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\_libs\hashtable.cp37-win_amd64.pyd in View.MemoryView.memoryview.__cinit__()                                                                                                                                                                                                       ValueError: buffer source array is read-only
```

Interesting, huh?

FWIW I originally ran into this when using Google's BigQuery python client to retrieve data from a table with an array-type field. When retrieved via `.to_dataframe()` it came back as a column of `np.array(dtype=int64)`s with the `OWNDATA` and `WRITEABLE` flags set to False. The latter flag was the problem, although as stated above the data-type appears to matter (note that the stack trace refers to `pandas._libs.hashtable.ismember_int64()`).

**Comment by TomAugspurger** [comment]
@jbrockmendel you think this is essentially unfixable until we use cython>=0.30? If so, let's remove it from the 1.0.2 milestone.

**Comment by jbrockmendel** [comment]
> you think this is essentially unfixable until we use cython>=0.30?

It's viable, just invasive and a hassle, whereas with cython 0.30 it should be a 1-liner.  Depends on when we expect that to be available cc @scoder?

**Comment by scoder** [comment]
> when we expect that to be available

This year. :)
I'm planning to release an "official alpha" in a couple of weeks, as soon as I catch up with the currently pending PRs, and as soon as it's in a state that allows users to prepare for it.

**Comment by scoder** [comment]
(Remember that the good thing about Cython is that you can control when and how the C code is generated, so you're rather free to use whatever released or unreleased Cython package you want, as long as you test it sufficiently on your side. That said, it's obviously easier to use a proper PyPI release, that's why I'd like to get at least _something_ out soon.)

**Comment by scoder** [comment]
(Also, the "miniscule change" for this feature is only small in Cython's master/3.0 branch. It's not quite that small in a backport.)

**Comment by jbrockmendel** [comment]
@scoder thanks for the rundown.  Big releases aren't easy, and we appreciate all the time and effort you put in.

@TomAugspurger I'm inclined to push this off to 1.0.3 as long as we have lower-hanging-fruit regressions to handle

**Comment by TomAugspurger** [comment]
Agreed.

**Comment by jorisvandenbossche** [comment]
Do we know what caused this regression? Because if this was supported before with cython < 0.30, why is it hard to support it now with that cython version?

**Comment by dmitra79** [comment]
I am having this error. The 'isin()' example from above also  throws it. 
'''
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-118-generic
Version          : #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.3
setuptools       : 49.6.0.post20201009
Cython           : 0.29.21
lxml.etree       : 4.5.2
jinja2           : 2.11.2
IPython          : 7.18.1
fsspec           : 0.8.4
fastparquet      : 0.4.1
matplotlib       : 3.3.2
pyarrow          : 0.17.1
scipy            : 1.5.2
xarray           : 0.16.1
numba            : 0.51.2
'''
