### ISSUE TITLE
Wrong start datetime for data_range

### ISSUE THREAD

**Issue by GYHHAHA** [pandas-dev/pandas#31732]
#### Code Sample, a copy-pastable example if possible

```python
>>>pd.date_range(start='1/1/2018', periods=5, freq='M')
DatetimeIndex(['2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30',
               '2018-05-31'],
              dtype='datetime64[ns]', freq='M')
```
#### Problem description

Why datatime start from '2018-01-31' ?

**Comment by rockg** [comment]
`M` is calendar month end, you need `MS` for calendar month start. See [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#dateoffset-objects) for the list of offset strings.

**Comment by GYHHAHA** [comment]
Thanks ! @rockg
