### ISSUE TITLE
read_parquet gives ArrowIOError

### ISSUE THREAD

**Issue by azimgivron** [pandas-dev/pandas#31747]
I am trying to open a .parquet file in pandas but I am failing at it. I tried the solution proposed in https://stackoverflow.com/questions/54201799/pandas-cannot-read-parquet-files-created-in-pyspark but it is not working for me. 

Does anyone have a clue of how to fix this ? 

#### 

python code:

pd.read_parquet('filepath')

#### 

Error received in the consol:

ArrowIOError Traceback (most recent call last)
<ipython-input-32-623a6e60c94a> in <module>
----> 2 pd.read_parquet('filepath'')

C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parquet.py in read_parquet(path, engine, columns, **kwargs)
    308 
    309     impl = get_engine(engine)
--> 310     return impl.read(path, columns=columns, **kwargs)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parquet.py in read(self, path, columns, **kwargs)
    123         kwargs["use_pandas_metadata"] = True
    124         result = self.api.parquet.read_table(
--> 125             path, columns=columns, **kwargs
    126         ).to_pandas()
    127         if should_close:

C:\ProgramData\Anaconda3\lib\site-packages\pyarrow\parquet.py in read_table(source, columns, use_threads, metadata, use_pandas_metadata, memory_map, read_dictionary, filesystem, filters, buffer_size)
   1272                             read_dictionary=read_dictionary,
   1273                             buffer_size=buffer_size,
-> 1274                             filesystem=filesystem, filters=filters)
   1275     else:
   1276         pf = ParquetFile(source, metadata=metadata,

C:\ProgramData\Anaconda3\lib\site-packages\pyarrow\parquet.py in __init__(self, path_or_paths, filesystem, schema, metadata, split_row_groups, validate_schema, filters, metadata_nthreads, read_dictionary, memory_map, buffer_size)
   1058 
   1059         if validate_schema:
-> 1060             self.validate_schemas()
   1061 
   1062     def equals(self, other):

C:\ProgramData\Anaconda3\lib\site-packages\pyarrow\parquet.py in validate_schemas(self)
   1090                 self.schema = self.common_metadata.schema
   1091             else:
-> 1092                 self.schema = self.pieces[0].get_metadata().schema
   1093         elif self.schema is None:
   1094             self.schema = self.metadata.schema

C:\ProgramData\Anaconda3\lib\site-packages\pyarrow\parquet.py in get_metadata(self)
    558         metadata : FileMetaData
    559         """
--> 560         f = self.open()
    561         return f.metadata
    562 

C:\ProgramData\Anaconda3\lib\site-packages\pyarrow\parquet.py in open(self)
    565         Returns instance of ParquetFile
    566         """
--> 567         reader = self.open_file_func(self.path)
    568         if not isinstance(reader, ParquetFile):
    569             reader = ParquetFile(reader, **self.file_options)

C:\ProgramData\Anaconda3\lib\site-packages\pyarrow\parquet.py in _open_dataset_file(dataset, path, meta)
    940         read_dictionary=dataset.read_dictionary,
    941         common_metadata=dataset.common_metadata,
--> 942         buffer_size=dataset.buffer_size
    943     )
    944 

C:\ProgramData\Anaconda3\lib\site-packages\pyarrow\parquet.py in __init__(self, source, metadata, common_metadata, read_dictionary, memory_map, buffer_size)
    135         self.reader.open(source, use_memory_map=memory_map,
    136                          buffer_size=buffer_size,
--> 137                          read_dictionary=read_dictionary, metadata=metadata)
    138         self.common_metadata = common_metadata
    139         self._nested_paths_by_prefix = self._build_nested_paths()

C:\ProgramData\Anaconda3\lib\site-packages\pyarrow\_parquet.pyx in pyarrow._parquet.ParquetReader.open()

C:\ProgramData\Anaconda3\lib\site-packages\pyarrow\error.pxi in pyarrow.lib.check_status()

ArrowIOError: Invalid parquet file. Corrupt footer.
####

version:

python 3.7.6
pandas 1.0.1

**Comment by jorisvandenbossche** [comment]
@azimgivron Can you give a bit more details? What is the pyarrow version you are using? (you can add the output `pd.show_versions()` in your issue report) Is the file path a directory? How did you create those files?
