### ISSUE TITLE
cannot import name 'OrderedDict'

### ISSUE THREAD

**Issue by aminemosbah** [pandas-dev/pandas#31776]
#### cannot import name 'OrderedDict'
trying to work on collab and panda failed to import  'OrderedDict'

here is the code 
import pandas as pd
data = pd.read_csv('/content/causalnex/fulcase_causal.csv', delimiter=';', index_col=0)
data.head(5)

 here is the message 
/usr/local/lib/python3.6/dist-packages/pandas/io/formats/html.py in <module>()
      8 from textwrap import dedent
      9 
---> 10 from pandas.compat import OrderedDict, lzip, map, range, u, unichr, zip
     11 
     12 from pandas.core.dtypes.generic import ABCMultiIndex

ImportError: cannot import name 'OrderedDict'

any suggestion

**Comment by WillAyd** [comment]
Hard to say from info provided but this hasn't existed in pandas for quite some time. You should try upgrading

**Comment by aminemosbah** [comment]
I m on collab it must have a compatible  on

**Comment by WillAyd** [comment]
Gotcha. I assume an issue with however the colab was set up so hard to say. 

Closing as I don't think a pandas issue, but if you can reproduce with pandas alone let us know and can reopen

**Comment by aminemosbah** [comment]
Yeep no issue we using a standalone pandas it only pups up with google collab without any impact on the workflow though ! However a bit annoying
