### ISSUE TITLE
Feature Request: Sample method for Groupby objects

### ISSUE THREAD

**Issue by yadunathg** [pandas-dev/pandas#31775]
Many times it is desirable to be able to iterate over a small number of groups of a group by object. Currently there is no direct way to get a random sample of groups. 

Similar to DataFrame.sample method, can we have Groupby.sample method which gives us a Dictionary{'group_name'->'group_labels'} containing n randomly selected groups?

#### Expected behaviour
```python
import pandas as pd
df = pd.DataFrame([['Male', 1], ['Female', 3], ['Female', 2], ['Other', 1]],
                                 columns=['gender', 'feature'])
grouped_df = df.groupby('gender')

# Desired feature
grouped_df.sample(n=2)
# {'Female': Int64Index([1, 2], dtype='int64'),
#  'Male': Int64Index([0], dtype='int64')}
```

**Comment by charlesdong1991** [comment]
interesting, will look into it

**Comment by echozzy629** [comment]
take

**Comment by echozzy629** [comment]
take

**Comment by yadunathg** [comment]
Thanks for adding the sample feature into groupby. However, behaviour of the added feature is different from what I had requested.

I wanted to get a sample of groups from the groupby objects. But the added feature allows us to get a sample of records from each group of the groupby object. Is it possible to add an argument to the sample method which allows us to choose whether the sampling should be done on the groups or records of each group?
