### ISSUE TITLE
plotting backends doesn't plot for the first time after importing pandas

### ISSUE THREAD

**Issue by rushabh-v** [pandas-dev/pandas#31787]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
pd.set_option('plotting.backend', 'matplotlib')
pd.Series([1, 2, 3]).plot()
```
```python
import pandas as pd
pd.options.plotting.backend = 'matplotlib'
pd.Series([1, 2, 3]).plot()
```
```python
import pandas as pd
pd.Series([1, 2, 3]).plot(backend='matplotlib')
```
#### Problem description
If you use any of the above three options to plot. for the first time, it will just return something like `<matplotlib.axes._subplots.AxesSubplot at 0x7f6b28a75ac8>
`. And then, from the next time onwards it will plot the graph. Even if you use one option after another then also from the second time onwards it works fine.
 
#### Expected Output
It should plot the graph for the first time also.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.20.5-042005-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_IN
LOCALE           : en_IN.ISO8859-1

pandas           : 1.0.0rc0
numpy            : 1.16.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 20.0.2
setuptools       : 41.0.1
Cython           : 0.29.12
pytest           : 5.0.1
hypothesis       : None
sphinx           : 2.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.3.4
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.6.1
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.4
matplotlib       : 3.1.0
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.0.1
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.5
tables           : 3.5.2
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.8
numba            : 0.44.1
</details>

**Comment by TomAugspurger** [comment]
@rushabh-v what do you mean by "doesn't plot"? If you're getting back an Axes object, then I think it's plotting.

**Comment by rushabh-v** [comment]
Yes, but it doesn't display any plot.

**Comment by lodagro** [comment]
Are you using IPython and familiar with [IPython interactive plotting](https://ipython.readthedocs.io/en/stable/interactive/plotting.html#id1)?

**Comment by rushabh-v** [comment]
> Are you using IPython and familiar with IPython interactive plotting?

Oh yes, I was using jupyter notebook. And it works fine when I first run %matplotlib.
I am closing this issue.
