### ISSUE TITLE
Groupby get_group is not consistent - sometimes it returns the grouping columns, sometimes it doesn't

### ISSUE THREAD

**Issue by giuliobeseghi** [pandas-dev/pandas#31780]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

df = pd.DataFrame(
    {"a": range(50), "b": range(0, 100, 2), "c": list(range(10)) * 5}
)

grouper = df.groupby("c")
grouper.get_group(0)
```
#### Problem description

This is quite weird and unfortunately I can't replicate it. The previous piece of code randomly returns one of the two options:

1)
|    |   a |   b |   c |
|---:|----:|----:|----:|
|  0 |   0 |   0 |   0 |
| 10 |  10 |  20 |   0 |
| 20 |  20 |  40 |   0 |
| 30 |  30 |  60 |   0 |
| 40 |  40 |  80 |   0 |

2)
|    |   a |   b |
|---:|----:|----:|
|  0 |   0 |   0 |
| 10 |  10 |  20 |
| 20 |  20 |  40 |
| 30 |  30 |  60 |
| 40 |  40 |  80 |

If I run it now, I get option 1 (which I assume it's the expected one, since `Groupby.get_group` doesn't say anything about dropping the column used in the groupby https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.GroupBy.get_group.html)

However, a few minutes earlier I ran this
```python
[grouper.get_group(i).do_something_with_c_column() for i in grouper.groups.keys()]
```

And it raised a `KeyError`. Which is the right behavior? Can anyone else replicate this?

#### Output of ``pd.show_versions()``

<details>

numexpr.utils - INFO - NumExpr defaulting to 8 threads.

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.0
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.1.0.post20200127
Cython           : 0.29.14
pytest           : 5.3.5
hypothesis       : 5.4.1
sphinx           : 2.3.1
blosc            : None
feather          : None
xlsxwriter       : 1.2.7
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : 1.3.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.1.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.3.5
pyxlsb           : None
s3fs             : 0.4.0
scipy            : 1.3.2
sqlalchemy       : 1.3.13
tables           : 3.6.1
tabulate         : 0.8.3
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.7
numba            : 0.48.0

</details>

**Comment by Dr-Irv** [comment]
Without an example that we can replicate, we can't investigate.
