### ISSUE TITLE
numpy.core._exceptions while resample using spline interpolation

### ISSUE THREAD

**Issue by Lama09** [pandas-dev/pandas#31781]
#### Code Sample, a copy-pastable example if possible

```python
time      value1      value2      value3
run_id

19            00:00:00     14.45       1000.0       5.800000
19     00:00:00.010000     14.45       1000.0       5.591578
19     00:00:00.020000     14.45       1000.0       5.878844
19     00:00:00.030000     14.45       1000.0       5.974964
19     00:00:00.040000     14.45       1000.0       5.643659
...                ...       ...          ...            ...
20     00:00:00.647290     17.46       1500.0       5.695907
```
#### Problem description
I have a grouped timeseries from measurement data which looks like this. I now would like to increase the sample rate from 0.01s to 0.001s using the following code.

```python
for name, group in data.groupby('run_id'):
  temp = group.reset_index().set_index('time').resample('0.001S').interpolate(method='spline', order=2)
```
This will end up in the following exception.

```python
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'greater' input 1 from dtype('float64') to dtype('<m8[ns]') with casting rule 'same_kind'
```
Select a frequency for downsampling like this.

```python
temp = group.reset_index().set_index('time').resample('0.02S').interpolate(method='spline', order=2)
```
It seems to be working. The upsampling is working if I change the interpolation method to linear.

```python
temp = group.reset_index().set_index('time').resample('0.001S').interpolate(method='linear')
```
What I'm doing wrong here? I also tried an approach to apply the resampling directly to the groupby object like this.

```python
data.reset_index().set_index('time').groupby('run_id').resample('0.001S').interpolate(method='linear')
```
Does this make sense or do I need the apply() approach here?

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None
pandas           : 0.25.3
numpy            : 1.17.1
pytz             : 2017.3
dateutil         : 2.6.1
pip              : 19.3.1
setuptools       : 41.2.0
Cython           : 0.27.3
pytest           : 5.1.2
hypothesis       : None
sphinx           : 2.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.0.2
lxml.etree       : 4.1.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10
IPython          : 6.2.1
pandas_datareader: None
bs4              : 4.6.0
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.1.1
matplotlib       : 2.1.2
numexpr          : 2.6.4
odfpy            : None
openpyxl         : 2.4.10
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.0.0
sqlalchemy       : 1.2.1
tables           : None
xarray           : None
xlrd             : 1.1.0
xlwt             : 1.3.0
xlsxwriter       : 1.0.2

</details>

**Comment by mroeschke** [comment]
Sorry this issue got ignored, but it was probably because your issue description does not contains a minimal copy paste-able example: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

If you could modify the issue to include that it will be easier for the team to triage this issue, but since there hasn't been much movement due to that going to close for now.
