### ISSUE TITLE
Failed to create the storer for xarray on HDFStore

### ISSUE THREAD

**Issue by ericksc** [pandas-dev/pandas#31798]
When The code below tried to store into a hdf in case of xarray DataArray but it cased an error. Other datatypes

```python
import pandas as pd
import xarray as xr
import tempfile

def test_hdfstore():
    with tempfile.NamedTemporaryFile('r', suffix='.hdf') as f:
        with pd.HDFStore(f.name, "a") as store:
            obj = xr.DataArray([[1,2],[3,4]],
                                   dims=('x', 'y'),
                                   coords={'x': ['A', 'B'], 'y':['a','b']})

            store['my_obj'] = obj

```
#### Problem description

When a DataArray was tried to be stored in an HDF5 file but it caused an error like this:

```
  File "C:\ProgramData\Anaconda3\envs\python37\lib\site-packages\pandas\io\pytables.py", line 556, in __setitem__
    self.put(key, value)
  File "C:\ProgramData\Anaconda3\envs\python37\lib\site-packages\pandas\io\pytables.py", line 1042, in put
    errors=errors,
  File "C:\ProgramData\Anaconda3\envs\python37\lib\site-packages\pandas\io\pytables.py", line 1682, in _write_to_group
    s = self._create_storer(group, format, value, encoding=encoding, errors=errors)
  File "C:\ProgramData\Anaconda3\envs\python37\lib\site-packages\pandas\io\pytables.py", line 1548, in _create_storer
    raise TypeError("value must be None, Series, or DataFrame")
TypeError: value must be None, Series, or DataFrame
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None
pandas           : 1.0.0
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.1.0.post20200127
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : 2.7.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : 3.6.1
tabulate         : None
xarray           : 0.15.0
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by TomAugspurger** [comment]
I don't think that's supported. You could use xarray's [to_netcdf](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.to_netcdf.html#xarray.DataArray.to_netcdf).

**Comment by mroeschke** [comment]
Thanks for the suggestion, but if xarray objects don't subclass pandas objects than this may not be appropriate for pandas to handle specifically. The workaround above or converting to a pandas object first would be more suitable here.

Going to close since there hasn't been much traction or support on this feature request, but happy to reopen if there revived interest from the core team
