### ISSUE TITLE
groupby returns non-pertinent combinations in result

### ISSUE THREAD

**Issue by RS574** [pandas-dev/pandas#31811]
#### Code Sample, a copy-pastable example if possible

```python

import pandas as pd

d1 = ['foo', 'bar'] * 50
d2 = list('ABCD' * 25)
d3 = pd.date_range('2019-01-01', periods=100, freq='D')
d4 = list(range(1, 101, 1))
d5 = list(range(1000, 100001, 1000))

df = pd.DataFrame(dict(col1=d1, col2=d2, col3=d3, col4=d4, col5=d5))

bins = [0, 30, float('inf')]

grouped = df.groupby(['col1', 'col2', pd.Grouper(key='col3', freq='MS'), 
                      pd.cut(df.col4, bins)])
summary = grouped['col5'].sum()
```
#### Problem description
The groupby() function returns a result that has every possible combination of the grouping criteria, and shows 'NaN' for non-significant combinations (see screenshot of the results below). This behavior was not observed in pandas version 0.24.2. Earlier version only returned combinations with values (ie, combinations with NaN values were not included in the result.)

#### Expected Output
![image](https://user-images.githubusercontent.com/58710879/74092960-2b932b80-4a91-11ea-928c-b2c51a865cda.png)

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en
LOCALE           : None.None

pandas           : 1.0.0
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.1.0.post20200127
Cython           : 0.29.14
pytest           : 5.3.5
hypothesis       : 5.4.1
sphinx           : 2.3.1
blosc            : None
feather          : None
xlsxwriter       : 1.2.7
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : 1.3.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.1.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.3.5
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.13
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.7
numba            : 0.48.0

**Comment by dsaxton** [comment]
I think this is expected because when you call cut on col4 the output is Categorical, and all categories of a Categorical appear in the groupby result even if they aren't in the original DataFrame. You can disable this by setting observed=True in the call to groupby.

**Comment by RS574** [comment]
Setting observed=True resolves the issue. Thanks for your help! I guess the bug is in pandas 0.24.2 then because it appears setting observed to True or False has no effect in that version.
