### ISSUE TITLE
DOC: Mention black and PEP8 in pandas style guide

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#31828]
`black` and PEP8 are pretty important elements of code style in `pandas` but they aren't mentioned in the style guide, so it may make sense to include them.

https://pandas.pydata.org/pandas-docs/stable/development/code_style.html

**Comment by alimcmaster1** [comment]
We mention them in the contributing guide?

(Maybe a link would be helpful)

https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#python-pep8-black

**Comment by gfyoung** [comment]
The purpose of the style guide to express particular style points we follow.  `black` and `pep8` are just tools we use to enforce general "stylistic correctness".

I agree with @alimcmaster1 that linking is probably a sensible thing to do.
