### ISSUE TITLE
1.0.1 on conda - doc change or pushing to main conda channel?

### ISSUE THREAD

**Issue by discdiver** [pandas-dev/pandas#31835]
To install 1.0.1 with conda I needed to use conda forge channel. 

The install instructions in the docs say to just use `conda install pandas`, but that installs 1.0.0. 

I'm not sure if the solution is to push 1.0.1 to the main conda channel (if you control that) or if it's worth updating the install instructions in the docs so they are in sync with how to install the latest pandas version.

**Comment by TomAugspurger** [comment]
Anaconda builds the packages uploaded to defaults, usually within a week or so.

I don't think there's anything to do here. The docs will need to be accurate in the future too, and the fact that some / many people will configure conda-forge to be their default makes writing this section tricky to cover all use cases.

**Comment by discdiver** [comment]
Gotcha @TomAugspurger . Maybe just worth adding a line in the docs that the default conda channel might take a week to have the latest version after a release - specify conda-forge as the install channel if you want to make sure you have the latest version.

**Comment by jbrockmendel** [comment]
@TomAugspurger actionable/closeable?
