### ISSUE TITLE
ENH: str.replace on multiple columns

### ISSUE THREAD

**Issue by manel00** [pandas-dev/pandas#31850]
#IT WORKS
    df['Total'] = df['Total'].str.replace(r'\.', '')
    df['Homes'] = df['Homes'].str.replace(r'\.', '')
    df['Dones'] = df['Dones'].str.replace(r'\.', '')
    
    #IT DOESNT WORK
    cols = ["Total", "Homes", "Dones"]
    df[cols] = df[cols].str.replace(r'\.', '')

On Pandas 1.0.1

**Comment by WillAyd** [comment]
There is no `.str` accessor for data frame, only series. This is similar to #27581 but same comment applies - I'm not sure we really would want to add `.str` or `.dt` accessors to DataFrames anyway

**Comment by hirolau** [comment]
It is not too much hassle to do:

```Python
for col in ["Total", "Homes", "Dones"]:
    df[col] = df[col].str.replace(r'\.', '')
```

**Comment by mroeschke** [comment]
Thanks for the suggestion but for a similar reason as https://github.com/pandas-dev/pandas/issues/27581 there is hesitation to add accessors that operate on dataframe due to the nature of mixed dtypes. Closing
