### ISSUE TITLE
Pandas qcut - Allow right argument to make left bins inclusive/exclusive

### ISSUE THREAD

**Issue by pushlog** [pandas-dev/pandas#31862]
```python
def qcut(
    x,
    q,
    right=True,
    labels=None,
    retbins: bool = False,
    precision: int = 3,
    duplicates: str = "raise",
):



fac, bins = _bins_to_cuts(
    x,
    bins,
    right=True,
    labels=labels,
    precision=precision,
    include_lowest=True,
    dtype=dtype,
    duplicates=duplicates,
)

```
#### Similar to R HMISC cut2 Equiwidth Binning

[Having right=False makes left bins inclusive and right bins exclusive whereas right=True makes left bins exclusive and right bins inclusive. When right=False, it replicates what cut2 function from HMISC R package is doing.]

#### Expected Output
<details>
When right=False, index of the dataframe looks like below:

```
[1.0, 3.0)
[4.0, 7.0)
```

When right=True, index of the dataframe looks like below:

```
(1.0, 3.0]
(1.0, 3.0]
```
</details>

**Comment by jreback** [comment]
pls edit the top
to show an example that is copy pastable for both left and right inclusive

can u elaborate in an actual usecase
