### ISSUE TITLE
Monthly Dev Meeting

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#31879]
The next monthly dev call is tomorrow (Wednesday, February 12th) at 18:00 UTC. We invite all to come. https://dev.pandas.io/docs/development/meeting.html

We'll use this Zoom link: https://zoom.us/j/942410248

The agenda is at https://docs.google.com/document/d/1tGbTiYORHiSPgVMXawiweGJlBw5dOkVJLY-licoBmBU/edit?usp=sharing if you have topics to discuss.

**Comment by alimcmaster1** [comment]
To be clear the date is:

The next monthly dev call is tomorrow (Wednesday, February 12th) at 18:00 UTC

**Comment by TomAugspurger** [comment]
Whoops, copy pasted the wrong text.
