### ISSUE TITLE
np.ndarray.nonzero() doesn't know how to deal with pd.NA and throws type error

### ISSUE THREAD

**Issue by mind6** [pandas-dev/pandas#31886]
#### Code Sample, a copy-pastable example if possible

```python
np.where(pd.Series([True, False,pd.NA], dtype='boolean'))
```
#### Problem description
np.ndarray.nonzero() doesn't know how to deal with pd.NA and throws type error. 

#### Expected Output
(array([0], dtype=int64),)

Since pd.NA is a value that just doesn't exist, it should be ignored and skipped over by nonzero() when returning indices of nonzero elements. 

#### Actual Output
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-55-d3635393ceeb> in <module>
----> 1 np.where(pd.Series([True, False,pd.NA], dtype='boolean'))

<__array_function__ internals> in where(*args, **kwargs)

pandas\_libs\missing.pyx in pandas._libs.missing.NAType.__bool__()

TypeError: boolean value of NA is ambiguous

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.1.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.0.1
numpy            : 1.17.4
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.2.0.post20200210
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
</details>

**Comment by TomAugspurger** [comment]
I don't know that I agree with your expected output. `where` returns the values where the condition is True, and the value of NA is unknown.

Regardless, what action do you propose we take, given that we don't control the behavior of `numpy.where` and NumPy doesn't depend on pandas?

**Comment by mind6** [comment]
```
>>>np.logical_not(pd.Series([True, False, pd.NA], dtype='boolean'))
0    False
1     True
2     <NA>
dtype: boolean

>>>np.logical_not(np.asarray(pd.Series([True, False, pd.NA], dtype='boolean')))
...TypeError: boolean value of NA is ambiguous

>>>np.asarray(pd.Series([True, False, pd.NA], dtype='boolean'))
array([True, False, <NA>], dtype=object)
```
It seems because np.where does np.asarray.nonzero(...) , the array conversion loses the type handling ability? How is np.logical_not able to work without array convertion?

**Comment by TomAugspurger** [comment]
`np.nan` and NA are different things. `bool(np.nan)` is defined to be False. For `pd.NA` isn't not defined and raises an exception.

**Comment by mind6** [comment]
What if we define bool(pd.NA) t be pd.NA? would that make sense to propagate correctly?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by TomAugspurger** [comment]
Bool has to return a Boolean I think. I don’t think there’s anything that can be done here right now.

**Comment by TomAugspurger** [comment]
Hmm unless we implement __array_function__. That’s a ways off though I think.
