### ISSUE TITLE
PERF: Index.__getitem__ should not need to do dtype inference

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#31903]
Currently, the `__getitem__` call in a snippet like

```
idx = pd.Index([1, 2, 3, 4])
idx[np.array([0, 3])]
```

does type inference when creating the new Index object (using `_shallow_copy_with_infer`), while I think we can always know for sure the result will be another Int64Index (for the above example) ?

**Comment by jbrockmendel** [comment]
`Index.__getitem__` no longer uses _shallow_copy_with_infer.  Are there other optimizations you had in mind?

**Comment by jbrockmendel** [comment]
Closing as I'm pretty sure this no longer does type inference.  Feel free to reopen if ive got this wrong.

**Comment by jorisvandenbossche** [comment]
Yep, that's correct
