### ISSUE TITLE
ohlc documentation

### ISSUE THREAD

**Issue by dequadras** [pandas-dev/pandas#31919]
The documentation for ohlc is missleading. In https://pandas.pydata.org/pandas-docs/stable/reference/groupby.html The following doc appears, which probably references the docstring in the code.
![image](https://user-images.githubusercontent.com/30231949/74328919-b3758000-4d86-11ea-96c1-9205373a48ad.png)

A sentence like `Computes open, high, low and close values, excluding missing values` is probably more complete.

**Comment by MarcoGorelli** [comment]
Thanks @dequadras 

Are you interested in submitting a pull request? See the [contributing guide](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html) for how to get started

**Comment by dequadras** [comment]
Sure!
