### ISSUE TITLE
Pandas negative timedelta is 1 day off

### ISSUE THREAD

**Issue by tuxcell** [pandas-dev/pandas#31924]
#### Code Sample:

```python
import datetime
import pandas as pd
a=pd.to_datetime('2017-04-03T14:06:00+01:00')
b=pd.to_datetime('2017-04-03T14:00:00+01:00')
print(a-b)
print(b-a)

#Timedelta('0 days 00:06:00')
#Timedelta('-1 days +23:54:00')

```
#### Problem description

Two timestamps obtained from Pandas "to_datetime" and having a time delta of 6 minutes, will have a strange result when the difference is negative.

#### Timedelta('0 days -00:06:00')

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-76-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 4.3.1
pip: 19.0.3
setuptools: 40.8.0
Cython: 0.29.6
numpy: 1.16.1
scipy: 1.2.1
pyarrow: 0.14.0
xarray: None
IPython: 7.3.0
sphinx: 1.8.5
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: 1.2.1
tables: 3.5.1
numexpr: 2.6.9
feather: None
matplotlib: 3.0.3
openpyxl: 2.6.1
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.5
lxml.etree: 4.3.2
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.3.1
pymysql: None
psycopg2: 2.7.6.1 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by MarcoGorelli** [comment]
Aren't `Timedelta('-1 days +23:54:00')` and `Timedelta('0 days -00:06:00')` expressing the same thing?

**Comment by WillAyd** [comment]
Yea as mentioned by @MarcoGorelli this is by design
