### ISSUE TITLE
pandas.DataFrame.reindex_like throws if called from a derived class instance

### ISSUE THREAD

**Issue by lguyot** [pandas-dev/pandas#31925]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import pandas.testing as pdt

class MyDataFrame(pd.DataFrame):
    pass

mdf = MyDataFrame()
df = pd.DataFrame()
# In DataFrame.reindex_like, the derived class is compared to
# the base class. The following line will throw
# 'AssertionError: <class 'pandas.core.frame.DataFrame'>'
mdf.reindex_like(df)

# In pdt.assert_frame_equal,
# check_like=True triggers a call to DataFrame.reindex_like.
# The following line will throw the same
# 'AssertionError: <class 'pandas.core.frame.DataFrame'>'
pdt.assert_frame_equal(mdf, df, check_like=True)
```
#### Problem description

The method `reindex_like` throws an `AssertionError` when the caller is an instance of a derived class of `pandas.DataFrame`.

#### Expected Output

No exception thrown.

#### Output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-65-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : fr_FR.UTF-8
LOCALE           : fr_FR.UTF-8

pandas           : 1.0.1
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 9.0.1
setuptools       : 39.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 0.999999999
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.12.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
</details>

**Comment by jorisvandenbossche** [comment]
@topper-123 another one from the `_ensure_type` checking

**Comment by jbrockmendel** [comment]
@jorisvandenbossche sounds like there has been some discussion about ensure_type already.  is someone on top of this?

**Comment by TomAugspurger** [comment]
> sounds like there has been some discussion about ensure_type already

I think Joris was referring to https://github.com/pandas-dev/pandas/issues/31785 / https://github.com/pandas-dev/pandas/pull/31788.

Don't think anyone is working on this yet (unless @topper-123 has something locally?)

**Comment by ericchansen** [comment]
Isn't this as simple as using `issubclass` instead of `isinstance`?

https://github.com/pandas-dev/pandas/blob/bdcb5da0906f7d8c7437d8531b8e3219f1ef554c/pandas/core/base.py#L90-L98

* Commit capturing proposed change https://github.com/ericchansen/pandas/commit/f2c3eabdfee735787a30eada5ffb808fe111d8c1
* Updated code https://github.com/ericchansen/pandas/blob/f2c3eabdfee735787a30eada5ffb808fe111d8c1/pandas/core/base.py#L90-L97
* Review of PR that introduced `_ensure_type` https://github.com/pandas-dev/pandas/pull/30613#pullrequestreview-367538632

**Comment by jorisvandenbossche** [comment]
@ericchansen do you want to make a PR with that change? (and a test)

I would personally also be fine with just getting rid of `_ensure_type`, the type checking should not have runtime consequences

**Comment by TomAugspurger** [comment]
> the type checking should not have runtime consequences

Agreed.

**Comment by ericchansen** [comment]
@jorisvandenbossche I'll open the PR today once I'm done with the tests.

@TomAugspurger @jorisvandenbossche It looks as if the type checking has something to do with mypy (as per discussion here https://github.com/pandas-dev/pandas/pull/30613#pullrequestreview-367538632 and here https://github.com/pandas-dev/pandas/pull/30565). I agree it shouldn't have runtime consequences, but it does look like there was some discussion about why they @topper-123 @jreback did it this way.
