### ISSUE TITLE
HTMLFormatter.to_html() does not look at show_index_names

### ISSUE THREAD

**Issue by blais** [pandas-dev/pandas#3195]
pandas.core.format.py:436
                                                                                                                                                                                                if self.show_index_names and self.has_index_names:

Below for pandas.core.format.py:647:
                                                                                                                                                                                            if self.fmt.has_index_names:

I think the second part should look at the show_index_names option.
The problem currently is that you cannot disable the two-row index, and sorttable.js does not work with two-row indexes.

**Comment by WillAyd** [comment]
Unclear what problem this is solving - feel free to re-open if you have a reproducible example
