### ISSUE TITLE
drawstyle with "step" or "step-mid" display error

### ISSUE THREAD

**Issue by mankoff** [pandas-dev/pandas#31965]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
df = pd.DataFrame(index=pd.date_range(start='2020-01-01', periods=3), data=[1,2,3])
df.plot(drawstyle='steps')
df.plot(drawstyle='steps-mid')
```

`df` is:

```
|                     | 0 |
|---------------------+---|
| 2020-01-01 00:00:00 | 1 |
| 2020-01-02 00:00:00 | 2 |
| 2020-01-03 00:00:00 | 3 |
```
#### Problem description

For the first plot (`step`), the first data point (value 1) is not displayed, and I question the x-axis labeling. It implies that the value throughout the day of 01 Jan is 2, while the datafram suggests the value is 1 (assuming the value is carried forward from the timestamp until the next observation).

![step](https://user-images.githubusercontent.com/145117/74480648-34577900-4e66-11ea-99bb-e9ca3add03c1.png)

![step-mid](https://user-images.githubusercontent.com/145117/74480702-46391c00-4e66-11ea-897f-039bde2d418f.png)

For the second plot (`step-mid`), all data is visible, but the x-axis is incorrect. It implies that  the value of 1 that began on 01 Jan changed midway through the day. Visually, both values 1 and 3 are graphically underrepresented and half-width, while value 2 is full-width.

I would expect that when `drawstyle="step"` is used, that the graph looks like this:

```
import pandas as pd
df = pd.DataFrame(index=pd.date_range(start='2020-01-01', periods=3), data=[1,2,3])
df.loc[df.index[-1] + (df.index[-1]-df.index[-2])] = df.iloc[-1]
df.plot(drawstyle='steps-post')

```

![better](https://user-images.githubusercontent.com/145117/74482932-4affcf00-4e6a-11ea-8a71-426f3fd01b56.png)

#### Expected Output

A graph that shows all data with correct x-axis labels.

#### Output of ``pd.show_versions()``

<details>

pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-76-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.3
numpy            : 1.17.3
pytz             : 2018.7
dateutil         : 2.7.5
pip              : 18.1
setuptools       : 40.5.0
Cython           : None
pytest           : 5.0.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.1 (dt dec pq3 ext lo64)
jinja2           : 2.10
IPython          : 7.1.1
pandas_datareader: None
bs4              : None
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.0.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.1.0
sqlalchemy       : 1.2.15
tables           : None
xarray           : 0.14.1
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None

 

</details>

**Comment by mankoff** [comment]
Seems to be a `matplotlib` issue so I posted over there. See https://github.com/matplotlib/matplotlib/issues/16635

**Comment by MarcoGorelli** [comment]
Thanks @mankoff for the report - closing as (from what I've understood by following the link) this isn't a bug in pandas, but please do let me know if I've misunderstood
