### ISSUE TITLE
Update DataFrame.to_latex() to have more flexibility

### ISSUE THREAD

**Issue by sglyon** [pandas-dev/pandas#3196]
The simple library `matrix2latex` has a lot of functionality packed into a single function. I think capturing some of those features in the current `DataFrame.to_latex()` method would make  `to_latex()` much more useful. 

The flexibility I am talking about is being able to do these types of things: 
- pass in arbitrary environment names
- specify the justification of each column (as well as vertical rules between them)
- natural handling for latex symbols like `\infty`
-  insert captions and labels into the tabular environment

**Comment by kameranis** [comment]
It seems that formatters can do a lot of stuff, like bold, italics, background color, etc for each cell. Is there an interest to implement this in the coming months?

**Comment by WillAyd** [comment]
Closing due to age and ambiguity - feel free to open new issues for particular requests if you have any

**Comment by gideonite** [comment]
I would like to be able to automatically make certain rows bold. For example, bold the largest values in each column.

Any thoughts on what the right abstraction is for this type of functionality? I'm inclined to think that the user can pass specific rows as well as a function specifying the formatting. (e.g. `\bf{}`). Then there can be specific options to automatically select on common criteria like `max` or `min`.

**Comment by TomAugspurger** [comment]
Seems like a latex backend to Styler is best here, but that’s a decent amount of work.

**Comment by KaleabTessera** [comment]
Can we reopen this as it is still of interest? @WillAyd

**Comment by WillAyd** [comment]
@KaleabTessera if you have something specific you should like to see probably best opening a separate issue for it at this point
