### ISSUE TITLE
Boolean diff is slower than float, int diff

### ISSUE THREAD

**Issue by JulianWgs** [pandas-dev/pandas#31972]
#### Code Sample

This code in Google Colab (Jupyter Notebook/Lab):
```python
import numpy as np
import pandas as pd


size = int(1e7)
value = np.sin(np.linspace(0, 100, size)) < 0.5

print("Numpy Boolean")
%timeit np.diff(value)

value = value.astype(int)
print("Numpy Integer")
%timeit np.diff(value)
df = pd.Series(np.sin(np.linspace(0, 100, size))) < 0.5

print("Pandas Boolean")
%timeit df.diff()

print("Pandas Integer")
%timeit df.astype(int).diff()

print("Pandas Float")
%timeit df.astype(float).diff()
```
Creates the following output:
```
Numpy Boolean
100 loops, best of 3: 11.8 ms per loop
Numpy Integer
100 loops, best of 3: 19 ms per loop
Pandas Boolean
1 loop, best of 3: 208 ms per loop
Pandas Integer
10 loops, best of 3: 51.7 ms per loop
Pandas Float
10 loops, best of 3: 43.8 ms per loop
```
#### Problem description

The diff function on a boolean series is about four times slower than on an integer or float series. This behavior is not reproducable in numpy, where diff on a boolean series is the fastest. Right now it is even faster to convert the boolean series to integer, do the diff and then convert back to boolean.

#### Expected Output

Boolean diff should be the fastest.

#### Output of ``pd.show_versions()``

Google Colab with pandas 1.0.1 installed.

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.14.137+
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.1
numpy            : 1.17.5
pytz             : 2018.9
dateutil         : 2.6.1
pip              : 19.3.1
setuptools       : 45.1.0
Cython           : 0.29.15
pytest           : 3.6.4
hypothesis       : None
sphinx           : 1.8.5
blosc            : None
feather          : 0.4.0
xlsxwriter       : None
lxml.etree       : 4.2.6
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.7.6.1 (dt dec pq3 ext lo64)
jinja2           : 2.11.1
IPython          : 5.5.0
pandas_datareader: None
bs4              : 4.6.3
bottleneck       : 1.3.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.2.6
matplotlib       : 3.1.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 2.5.9
pandas_gbq       : 0.11.0
pyarrow          : 0.14.1
pytables         : None
pytest           : 3.6.4
pyxlsb           : None
s3fs             : 0.4.0
scipy            : 1.4.1
sqlalchemy       : 1.3.13
tables           : 3.4.4
tabulate         : 0.8.6
xarray           : 0.14.1
xlrd             : 1.1.0
xlwt             : 1.3.0
xlsxwriter       : None
numba            : 0.47.0

</details>

#### Next steps
- Find out why it is slower
- Quick fix: `df.astype(int).diff().dropna().astype(bool)` which benchmarks to `10 loops, best of 3: 114 ms per loop`

**Comment by TomAugspurger** [comment]
They're doing different things. `np.diff` changes the shape of your array. pandas' preserves the shape and pads with a missing value, which is necessarily going to be slower.

Additionally, for bool dtype, pandas will cast from bool to object, to preserve the values (since bool can't hold NaN). You can use the new nullable `boolean` data type to avoid this.

I'd recommend profiling things to see where time is spent, but if it's all in missing-value handling then I'd recommend closing the issue.

**Comment by jorisvandenbossche** [comment]
And the new `boolean` type that @TomAugspurger mentioned is a lot faster (as it can preserve the dtype):

```
In [9]: %timeit df.diff() 
208 ms ± 16.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [10]: df2 = df.astype("boolean")      

In [13]: %timeit df2.diff()  
19.2 ms ± 168 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by JulianWgs** [comment]
Why doesnt a comparison produce the new boolean type? Its very counterintuative.

But for now I will convert my "bool" into a BooleanDtype and this issue can be closed. Thank you!

**Comment by TomAugspurger** [comment]
Backwards compatibility. This may change in the future.
