### ISSUE TITLE
Segfault in version 1.0.1, read_parquet after creating a clickhouse odbc connection

### ISSUE THREAD

**Issue by mvcalder-xbk** [pandas-dev/pandas#31981]
We started getting segfaults in upgraded versions of pandas and tracked it down to an interaction with making odbc connections. The specific odbc driver is for Clickhouse built in Dec19 from:

```
https://github.com/ClickHouse/clickhouse-odbc
commit 08b252b93fc771fab607fb973443543479b3d972
```

The core dump is reproducable in the example below: 

#### Code Sample, a copy-pastable example if possible

```python
import pyodbc
import pandas as pd

con_str = f"Driver=libclickhouseodbc.so;url=http://clickhouse/query;timeout=600"
with pyodbc.connect(con_str, autocommit=True) as con:
    pass

df = pd.DataFrame({'A': [1,1,1], 'B': ['a', 'b', 'c']})
df.to_parquet('/tmp/foo.pq')
# This line core dumps:
pd.read_parquet('/tmp/foo.pq')
```
#### Problem description

In the code above, creating the clickhouse odbc connection (not using it) leads to a segfault when reading the parquet file:

```
terminate called after throwing an instance of 'std::bad_cast'
  what():  std::bad_cast
Aborted (core dumped)
```

This does not happen in pandas 0.25.3 but does in pandas 1.0.1. 

#### Expected Output

No core dump.

#### Odbc driver dependencies

```xbk@499e30e4f63f:$ ldd libclickhouseodbc.so
        linux-vdso.so.1 (0x00007ffe02bee000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f246c269000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f246c061000)
        libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007f246be57000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f246ba66000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f246cd89000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f246b862000)
```

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-1062.4.3.el7.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.1
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 9.0.1
setuptools       : 45.2.0
Cython           : 0.29.14
pytest           : 5.3.2
hypothesis       : 5.1.2
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 0.999999999
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.2
numexpr          : None
odfpy            : None
openpyxl         : 3.0.2
pandas_gbq       : None
pyarrow          : 0.15.1.dev539+g8cf0c8e0a
pytables         : None
pytest           : 5.3.2
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.11
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
numba            : None
</details>

**Comment by WillAyd** [comment]
Do you have the same issue with a stable version of pyarrow? We don't have a lot of C++ internally so I think root cause *might* be elsewhere

**Comment by jreback** [comment]
this is from pyarrow

pls open an issue there

**Comment by jorisvandenbossche** [comment]
> This does not happen in pandas 0.25.3 but does in pandas 1.0.1.

Are you using the same pyarrow version in both environments?

**Comment by mvcalder-xbk** [comment]
Yes, this is the same pyarrow version in both cases. I'll open an issue there. Thank you.

**Comment by jorisvandenbossche** [comment]
For reference, the arrow issue is here: https://issues.apache.org/jira/browse/ARROW-7873
