### ISSUE TITLE
Feature request: option to set week starting on Sunday instead of Monday

### ISSUE THREAD

**Issue by charlesoblack** [pandas-dev/pandas#31987]
#### Problem description

Currently, calling `pd.Series.dt.weekday` returns Monday = 0, Sunday = 6. It would be nice to have a settable option that allows Sunday to be the beginning of the week, e.g.

```python
my_series.dt.weekday  # Monday = 0, Sunday = 6
pd.options.week_start = 'Sunday'
my_series.dt.weekday  # Sunday = 0, Saturday = 6
```

Pandas version 1.0.1.

**Comment by naomi172839** [comment]
I would be willing to work on this if it is something that others are interested in.  That being said, while it is obviously less than ideal, it seems that it would be an easy to work around it in your code.

**Comment by charlesoblack** [comment]
It is an easy workaround - but pandas is all about convenience, right? ;)

Here's what I'm currently doing:

```python
pd.Series.replace(6, -1, inplace=True)
```

**Comment by TomAugspurger** [comment]
We typically don’t have options that alter the behavior of computation. This option would require all downstream libraries to be aware that the mapping between days and integers could change, which doesn’t seem worthwhile.

**Comment by charlesoblack** [comment]
This is a locale setting in most other libraries, however. The standard
datetime library allows for locale changes. Plus, pandas changes the API
all the time with every version - why not have a "deprecation-style"
warning that the numbering might be different in the future?

We already allow for different datetime displays, although this doesn't
affect computation.

**Comment by jreback** [comment]
> Plus, pandas changes the API all the time with every 

this is a very odd comment; pls try to be constructive

**Comment by charlesoblack** [comment]
Sorry - let me try to elaborate.

Pands' API changes a lot with every version, so I don't think the argument
that downstream libraries that depend on pandas being aware of changes in
the pandas API holds much water. Most of the time, they need to be aware of
changes anyway, e.g. keyword changes or function deprecations or accessor
deprecations.

Following a deprecation-style warning saying "hey, the numbering might
change depending on user options" would communicate a change like the one I
proposed more effectively, if pandas devs deem this required. Effectively,
this should guarantee that downstream libraries are aware of the changes.

Please let me know if anything doesn't make sense.

**Comment by TomAugspurger** [comment]
> This is a locale setting in most other libraries

What libraries? Our Timestamp is a datetime.datetime subclass. From [what I can tell](https://docs.python.org/3/library/datetime.html#datetime.date.weekday), that doesn't allow configuring the start day.

**Comment by charlesoblack** [comment]
You're correct in that `date.weekday()` returns the same output as pandas currently does - however, `datetime` also allows for `strftime()` to be called with `%w` for Sunday-first (or compare `%W` and `%U`). Is this the recommended route when dealing with pandas datetimes, too? It seems silly to convert to string then back for a library meant for efficiency, but I'll accept it as long as it works...
