### ISSUE TITLE
Error running pd.show_versions()

### ISSUE THREAD

**Issue by langhimebaugh** [pandas-dev/pandas#31985]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
pd.show_versions()
```
#### Problem description
Was trying to import xlsb file...
pd.read_excel('my_file.xlsb', engine='pyxlsb')
when i received this error:
ImportError: Can't determine version for pyxlsb

Next, I tried pd.show_versions() and received the same error after restarting the kernel and running these two lines...
import pandas as pd
pd.show_versions()
ImportError: Can't determine version for pyxlsb

FYI:
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
IPython 5.5.0 -- An enhanced Interactive Python.

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
In [1]: import pandas as pd

In [2]: pd.show_versions()
Traceback (most recent call last):

  File "<ipython-input-2-3d232a07e144>", line 1, in <module>
    pd.show_versions()

  File "/home/lang/.local/lib/python3.6/site-packages/pandas/util/_print_versions.py", line 97, in show_versions
    modname, raise_on_missing=False, on_version="ignore"

  File "/home/lang/.local/lib/python3.6/site-packages/pandas/compat/_optional.py", line 98, in import_optional_dependency
    version = _get_version(module)

  File "/home/lang/.local/lib/python3.6/site-packages/pandas/compat/_optional.py", line 43, in _get_version
    raise ImportError(f"Can't determine version for {module.__name__}")

ImportError: Can't determine version for pyxlsb

pd.__version__
Out[3]: '1.0.1'
</details>

**Comment by WillAyd** [comment]
Pandas needs at least pyxlsb 1.0.5 installed - what version do you have?

**Comment by langhimebaugh** [comment]
Thanks for the response.  About 2 hours before your reply, I installed anaconda, conda update --all
then pip  install pyxlsb and all works fine now.  I do think I had pyxlsb 1.0.5 installed but not sure because it was installed about 4-5 months ago.
