### ISSUE TITLE
DOC: pivot_table example

### ISSUE THREAD

**Issue by raybellwaves** [pandas-dev/pandas#31983]
The documentation for pivot table seems limited https://pandas.pydata.org/pandas-docs/version/0.17/generated/pandas.pivot_table.html

It doesn't show how `df` was generated. In addition, should pivot_table be `pd.pivot_table`.

**Comment by nsiregar** [comment]
looks like its been updated in https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pivot_table.html?highlight=pivot_table#pandas.DataFrame.pivot_table

**Comment by raybellwaves** [comment]
Thanks. Apologies. Old docs.
