### ISSUE TITLE
WEB: the donate page is not loading correctly

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#31994]
For me, the donate page (and specifically the donate widget) is not loading:

![image](https://user-images.githubusercontent.com/1020496/74584748-e06ba200-4fd5-11ea-9dbc-61dbf0c564f8.png)

It just keeps saying "loading" for me.

**Comment by nsiregar** [comment]
[donation page](https://pandas.pydata.org/donate.html) seems to load data from salsalabs.org, is your network blocking salsalabs domain?

**Comment by jorisvandenbossche** [comment]
The actual webpage is working fine for me (https://numfocus.salsalabs.org/donate-to-pandas/index.html), but the widget not. Turning off blocking of trackers etc in my browser also doesn't help.

**Comment by jorisvandenbossche** [comment]
Although it is probably related to firefox, as in Chromium it displays fine.

**Comment by MarcoGorelli** [comment]
Widget loads fine for me on Chrome

**Comment by MarcoGorelli** [comment]
I guess this was just a temporary issue, am I OK to close?
