### ISSUE TITLE
COMPAT: numpy dev version raises new errors during CI

### ISSUE THREAD

**Issue by AlexKirko** [pandas-dev/pandas#31992]
### Problem description

Looks like something has been changed in numpy, and we now get new errors when running that Numpy dev pipeline during CI. This happens regardless of PR (saw it in #31563 and #31991). Seems to be centered around cumsum and division by nan, but I don't have the time to delve deeper atm.

One of the errors below:

```python


        # axis = 0
        cummin = datetime_frame.cummin()
        expected = datetime_frame.apply(Series.cummin)
>       tm.assert_frame_equal(cummin, expected)

pandas/tests/frame/test_cumulative.py:84: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pandas/_libs/testing.pyx:65: in pandas._libs.testing.assert_almost_equal
    cpdef assert_almost_equal(a, b,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   raise_assert_detail(obj, msg, lobj, robj)
E   AssertionError: DataFrame.iloc[:, 0] (column name="A") are different
E   
E   DataFrame.iloc[:, 0] (column name="A") values are different (46.66667 %)
E   [left]:  [0.652282807224414, -0.06609607048075124, 6.9221550547283e-310, 4.6661712289503e-310, 4.6661712289503e-310, 0.22575641583650302, 1.5013182000449852, -0.035445399728511705, -0.4007619715825971, -0.4007619715825971, -1.4917178151508124, -0.14834313680366412, 0.545948106375247, 1.495247786960942, 0.2128973463640255, 0.794985190506577, -1.4214210868734076, -1.4214210868734076, -1.019792839223919, -0.28828070056157995, -0.47176522372684804, -0.4267351486193231, -2.816743984494702, 0.4308015055934936, -0.007381576327430263, -0.007381576327430263, -1.121456436411571, -0.25765070817685554, -0.7686775772512485, 1.0963456159671487]
E   [right]: [0.652282807224414, -0.06609607048075124, -0.06609607048075124, 0.48729707348930335, 0.48729707348930335, 0.22575641583650302, 0.22575641583650302, -0.035445399728511705, -0.4007619715825971, -0.4007619715825971, 0.3249965661970306, -0.14834313680366412, -0.14834313680366412, 0.545948106375247, 0.2128973463640255, 0.2128973463640255, -1.4214210868734076, -1.4214210868734076, -0.9987072139900786, -0.9987072139900786, -0.47176522372684804, -0.47176522372684804, -2.816743984494702, -2.816743984494702, -0.007381576327430263, -0.007381576327430263, -1.121456436411571, -1.121456436411571, -0.7686775772512485, -0.7686775772512485]

```

[Link](https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=28623&view=logs&j=3a03f79d-0b41-5610-1aa4-b4a014d0bc70&t=4d05ed0e-1ed3-5bff-dd63-1e957f2766a9&l=75) to one of the failed pipelines. You can also just take a look at any recent PR.

**Comment by dsaxton** [comment]
It seems like the CI stills fails sometimes after https://github.com/pandas-dev/pandas/pull/32025 but now perhaps because the tests _pass_ unexpectedly? Not sure what's going on exactly, but does that mean we have to specify that the xfail isn't strict? Here's a pipeline failure after the xfail change: https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=28705&view=logs&j=3a03f79d-0b41-5610-1aa4-b4a014d0bc70&t=4d05ed0e-1ed3-5bff-dd63-1e957f2766a9&l=80

cc @simonjayhawkins

**Comment by simonjayhawkins** [comment]
@dsaxton see #32031 for follow-up PR, although having strict=False is not ideal to be able to keep track, so may be better to track down the underlying issue.

**Comment by dsaxton** [comment]
> @dsaxton see #32031 for follow-up PR, although having strict=False is not ideal to be able to keep track, so may be better to track down the underlying issue.

Ah, sorry missed that one

**Comment by AlexKirko** [comment]
This seems to no longer be a problem.

**Comment by simonjayhawkins** [comment]
@AlexKirko can we revert #32025, see https://github.com/pandas-dev/pandas/pull/32025#issuecomment-586612568
