### ISSUE TITLE
What's the difference between Timedelta and DateOffset on Earth?

### ISSUE THREAD

**Issue by GYHHAHA** [pandas-dev/pandas#32026]
After reading the docs, still I feel confused about the difference between the Timedelta and DataOffset.
```python
>>>ts = pd.Timestamp('2020-1-29 01:00:00')
>>>ts+pd.DateOffset(days=-1)
Timestamp('2020-01-28 01:00:00')
>>>ts+pd.Timedelta(days=-1)
Timestamp('2020-01-28 01:00:00')
```
It seems to be completely the same.
And I also find the difference appears when it involves a certain time zone operation.
```python
>>>ts = pd.Timestamp('2020-3-29 01:00:00', tz='Europe/Helsinki')
>>>ts + pd.Timedelta(days=1)
Timestamp('2020-03-30 02:00:00+0300', tz='Europe/Helsinki')
>>>ts + pd.DateOffset(days=1)
Timestamp('2020-03-30 01:00:00+0300', tz='Europe/Helsinki')
```
Therefore, how to tell the difference from these two concepts in a more explicit way?
Thanks for your answer!!!

**Comment by mroeschke** [comment]
As mentioned in the Overview in the Time Series docs, https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#overview, `DateOffset` respect calendar arithmetic while `Timedelta` respects absolute time arithmetic.

As you note, this matters with timezones. `pd.DateOffset(days=1)` increments a date by 1 calendar day (23, 24, or 25 hours depending on day light savings time). `pd.Timedelta(days=1)` increments a date by 24 hours.
