### ISSUE TITLE
Protecting sensitive columns while displaying data-frames at Jupyter notebook (feature request)

### ISSUE THREAD

**Issue by pavlovdog** [pandas-dev/pandas#32020]
Hi there!

Right now I'm working with pretty sensitive data - phone numbers, usernames, personal names and so on. Also, I'm using Jupyter notebooks for making reports and share the results with my colleagues. Tell me please - is it possible to specify some displaying settings, so some columns will be censored?

# Example

So the following command:

```python
> print (df)
         phone
0  79517123123
1  79517123923
2  79517123123
3  79517124123
4  79517115123
```

will become something like

```python
> print (df)
         phone
0  795*********23
1  795*********23
2  795*********23
3  795*********23
4  795*********23
```

# PR request

If right now it's not possible - I can make a PR with this feature. What do you guys think?

Thanks in advance!

**Comment by MarcoGorelli** [comment]
Thanks @pavlovdog 

It's not clear to me that you need a new feature for this -  if you have
```
>>> df                                                                                                     
         phone
0  79517123123
1  79517123123
2  79517123123
3  79517123123
4  79517123123
```
you could just do
```
>>> df.astype(str).replace(r"\B\w\B", "*", regex=True)                                                     
         phone
0  7*********3
1  7*********3
2  7*********3
3  7*********3
4  7*********3
```

**Comment by WillAyd** [comment]
We have a pretty high bar for adding to the API at this point and I don’t think this is a widely useful thing, so I would be -1 on adding this

**Comment by MarcoGorelli** [comment]
OK, closing for now, I guess it can be reopened if enough people show interest in this

**Comment by deveshgoyal** [comment]
I am working on a similar request, 
I want to obfuscate/anonymize sensitive data before sending it to downstream, can anyone suggest some library for the same?

I came across a few libraries like cape-dataframes / anonympy library that has some features for masking data. but it is much better if we also have similar things in the core pandas library.

**Comment by MarcoGorelli** [comment]
as suggested above: `df.astype(str).replace(r"\B\w\B", "*", regex=True)`

**Comment by global-saurabh** [comment]
> I am working on a similar request, I want to obfuscate/anonymize sensitive data before sending it to downstream, can anyone suggest some library for the same?
> 
> I came across a few libraries like cape-dataframes / anonympy library that has some features for masking data. but it is much better if we also have similar things in the core pandas library.

<I am also looking for something similar>

**Comment by schlich** [comment]
Came across this use case in the wild today.  I think it'd be a nice feature.
