### ISSUE TITLE
Should I be able to initialise a Series with a pandas array and pandas dtype?

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#32028]
#### Code Sample, a copy-pastable example if possible

```python
>>> import pandas as pd
>>> from pandas.core.arrays import PandasDtype
>>> pd.Series(pd.array([1,2,3]), dtype=PandasDtype('int64'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marco/pandas/pandas/core/series.py", line 323, in __init__
    data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
  File "/home/marco/pandas/pandas/core/construction.py", line 431, in sanitize_array
    subarr = subarr.astype(dtype, copy=copy)
  File "/home/marco/pandas/pandas/core/arrays/integer.py", line 475, in astype
    data = self.to_numpy(dtype=dtype, **kwargs)
  File "/home/marco/pandas/pandas/core/arrays/masked.py", line 144, in to_numpy
    data = self._data.astype(dtype, copy=copy)
TypeError: data type not understood
```

#### Output of ``pd.show_versions()``

(something's wrong here)
<details>

INSTALLED VERSIONS
------------------
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}

{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}

</details>

**Comment by jorisvandenbossche** [comment]
PandasDtype is not really meant for direct public use (they are also never actually stored in a Series, only created when we need to return an ExtensionArray). 

But in general, yes, you should be able to use such arrays and dtypes. Eg this works:

```
In [1]: pd.Series(pd.array([1,2,3]), dtype=pd.Int16Dtype()) 
Out[1]: 
0    1
1    2
2    3
dtype: Int16
```

**Comment by jorisvandenbossche** [comment]
But so there are still several missing things in `astype` support for extension arrays, eg https://github.com/pandas-dev/pandas/issues/22384, https://github.com/pandas-dev/pandas/issues/31204, ..

**Comment by jorisvandenbossche** [comment]
This has been fixed in the meantime, and we now "unpack" a PandasArray/PandasDtype it its plain numpy array/dtype when passed to the Series constructor.
