### ISSUE TITLE
Unable to Install Pandas on Python 3.9.0a3 

### ISSUE THREAD

**Issue by yogendrasoni79** [pandas-dev/pandas#32045]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
**Unable to Install Pandas on Python 3.9.0a3** (tags/v3.9.0a3:c33378d, Jan 25 2020, 10:12:02) [MSC v.1916 64 bit (AMD64)] on win32
```
#### Problem description
Keep getting message still running.. but no luck
PS C:\Windows\System32\WindowsPowerShell\v1.0> pip install pandas
Collecting pandas
  Downloading https://files.pythonhosted.org/packages/02/c3/e8c56de02d6c52f8541feca2fd77117e8ae4956f7b3e5cdbed726624039b/pandas-1.0.1.tar.gz (4.9MB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'error'
pip :   ERROR: Command errored out with exit status 1:
At line:1 char:1
+ pip install pandas
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (  ERROR: Comman... exit status 1::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   command: 'c:\users\yogendra.k.bhardwaj\python\python39\python.exe' 'c:\users\yogendra.k.bhardwaj\python\python39\lib\site-packages\pip' install 
--ignore-installed --no-user --prefix 'C:\Users\yogendra.k.bhardwaj\AppData\Local\Temp\pip-build-env-8hi0psxy\overlay' --no-warn-script-location 
--no-binary :none: --only-binary :none: -i https://pypi.org/simple --trusted-host pypi.org --trusted-host files.pythonhosted.org -- setuptools wheel 
'Cython>=0.29.13' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version>='"'"'3.7'"'"' and 
platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; 
python_version>='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"''
       cwd: None
  Complete output (1933 lines):
  Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.7" and platform_system == "AIX"' don't match your environment
  Collecting setuptools
    Downloading setuptools-45.2.0-py3-none-any.whl (584 kB)
  Collecting wheel
    Downloading wheel-0.34.2-py2.py3-none-any.whl (26 kB)
  Collecting Cython>=0.29.13
    Downloading Cython-0.29.15-py2.py3-none-any.whl (968 kB)
  Collecting numpy==1.14.5
    Downloading numpy-1.14.5.zip (4.9 MB)
  Installing collected packages: setuptools, wheel, Cython, numpy
      Running setup.py install for numpy: started
      Running setup.py install for numpy: still running...
      Running setup.py install for numpy: still running...
      Running setup.py install for numpy: still running...
      Running setup.py install for numpy: still running...
      Running setup.py install for numpy: still running...
      Running setup.py install for numpy: still running...
      Running setup.py install for numpy: still running...
      Running setup.py install for numpy: still running...
      Running setup.py install for numpy: still running...
      Running setup.py install for numpy: still running...
      Running setup.py install for numpy: still running...
      Running setup.py install for numpy: still running...
      Running setup.py install for numpy: still running...
      Running setup.py install for numpy: still running...
      Running setup.py install for numpy: still running...
      Running setup.py install for numpy: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\yogendra.k.bhardwaj\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = 
'"'"'C:\\Users\\yogendra.k.bhardwaj\\AppData\\Local\\Temp\\pip-install-tw6jolwp\\numpy\\setup.py'"'"'; 
__file__='"'"'C:\\Users\\yogendra.k.bhardwaj\\AppData\\Local\\Temp\\pip-install-tw6jolwp\\numpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', 
open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 
'C:\Users\yogendra.k.bhardwaj\AppData\Local\Temp\pip-record-oqns_udy\install-record.txt' --single-version-externally-managed --prefix 
'C:\Users\yogendra.k.bhardwaj\AppData\Local\Temp\pip-build-env-8hi0psxy\overlay' --compile --install-headers 
'C:\Users\yogendra.k.bhardwaj\AppData\Local\Temp\pip-build-env-8hi0psxy\overlay\Include\numpy'
           cwd: C:\Users\yogendra.k.bhardwaj\AppData\Local\Temp\pip-install-tw6jolwp\numpy\
      Complete output (1898 lines):
      Running from numpy source directory.
  
      Note: if you need reliable uninstall behavior, then install
      with pip instead of using `setup.py install`:
  
        - `pip install .`       (from a git repo or downloaded source
                                 release)
        - `pip install numpy`   (last NumPy release on PyPi)
  
  
      C:\Users\yogendra.k.bhardwaj\AppData\Local\Temp\pip-install-tw6jolwp\numpy\numpy\distutils\misc_util
.py:464: SyntaxWarning: "is" with a literal. Did you mean "=="?
        return is_string(s) and ('*' in s or '?' is s)
      blas_opt_info:
      blas_mkl_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries mkl_rt not found in ['c:\\users\\yogendra.k.bhardwaj\\python\\python39\\lib', 'C:\\', 
'c:\\users\\yogendra.k.bhardwaj\\python\\python39\\libs']
        NOT AVAILABLE
  
      blis_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries blis not found in ['c:\\users\\yogendra.k.bhardwaj\\python\\python39\\lib', 'C:\\', 
'c:\\users\\yogendra.k.bhardwaj\\python\\python39\\libs']
        NOT AVAILABLE
  
      openblas_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries openblas not found in ['c:\\users\\yogendra.k.bhardwaj\\python\\python39\\lib', 'C:\\', 
'c:\\users\\yogendra.k.bhardwaj\\python\\python39\\libs']
      get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
      customize GnuFCompiler
      Could not locate executable g77
      Could not locate executable f77
      customize IntelVisualFCompiler
      Could not locate executable ifort

**Comment by jreback** [comment]
well you have to build numpy and cython first which likely don’t work yet

so this is very premature

**Comment by yogendrasoni79** [comment]
> well you have to build numpy and cython first which likely don’t work yet
> 
> so this is very premature

Thanks for quick response, i am new to this so could you please share any references url to guide me

**Comment by jreback** [comment]
no idea -

**Comment by jorisvandenbossche** [comment]
@yogendrasoni79 if you are new to python/pandas, you can better install a *released* version.

**Comment by jbrockmendel** [comment]
@yogendrasoni79 building on previous responses: can you try `pip install numpy` before trying to install pandas?  It looks like the problem is there.

**Comment by snowman2** [comment]
pyproj experiencing installation issues as well: https://travis-ci.com/github/pyproj4/pyproj/jobs/385358258

**Comment by snowman2** [comment]
```
  pandas/_libs/writers.c: In function ‘__pyx_f_6pandas_5_libs_7writers_word_len’:

  pandas/_libs/writers.c:4942:5: error: ‘_PyUnicode_get_wstr_length’ is deprecated [-Werror=deprecated-declarations]

       __pyx_v_l = PyUnicode_GET_SIZE(__pyx_v_val);

       ^

  In file included from /opt/python/3.9-dev/include/python3.9/unicodeobject.h:1026:0,

                   from /opt/python/3.9-dev/include/python3.9/Python.h:97,

                   from pandas/_libs/writers.c:33:

  /opt/python/3.9-dev/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here

   static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {

                            ^

  pandas/_libs/writers.c:4942:5: error: ‘PyUnicode_AsUnicode’ is deprecated [-Werror=deprecated-declarations]

       __pyx_v_l = PyUnicode_GET_SIZE(__pyx_v_val);

       ^

  In file included from /opt/python/3.9-dev/include/python3.9/unicodeobject.h:1026:0,

                   from /opt/python/3.9-dev/include/python3.9/Python.h:97,

                   from pandas/_libs/writers.c:33:

  /opt/python/3.9-dev/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here

   Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(

                                               ^

  pandas/_libs/writers.c:4942:5: error: ‘_PyUnicode_get_wstr_length’ is deprecated [-Werror=deprecated-declarations]

       __pyx_v_l = PyUnicode_GET_SIZE(__pyx_v_val);

       ^

  In file included from /opt/python/3.9-dev/include/python3.9/unicodeobject.h:1026:0,

                   from /opt/python/3.9-dev/include/python3.9/Python.h:97,

                   from pandas/_libs/writers.c:33:

  /opt/python/3.9-dev/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here

   static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {

                            ^

  cc1: all warnings being treated as errors

  error: command '/usr/bin/gcc' failed with exit code 1

  ----------------------------------------

  ERROR: Failed building wheel for pandas
```

**Comment by jreback** [comment]
see https://github.com/pandas-dev/pandas/issues/36296

**Comment by esterrose** [comment]
Read the red sentence allert when you fail to install package and find what you have to install first
Try this, in cmd  : pip list and read what package you have installed.
skip if it is in the list

pip install setuptools
pip install numpy
pip install Cython
pip install wheel

then after that
pip install pandas

**Comment by Admund20** [comment]
@esterrose, best answer ever. I've been looking for a solution to install pandas in python 3.9 and you had it perfect, install all those modules before installing pandas. Thanks man.

**Comment by salma71** [comment]
It was successfully installed; however, when importing pandas it does say 
```
import pandas as pd
ImportError: No module named pandas

[Done] exited with code=1 in 0.102 seconds
```
I am using pyenv python 3.9.0, pip version 20.3.1
Any help would be appreciated.

**Comment by spyrpapa6** [comment]
> It was successfully installed; however, when importing pandas it does say
> 
> ```
> import pandas as pd
> ImportError: No module named pandas
> 
> [Done] exited with code=1 in 0.102 seconds
> ```
> 
> I am using pyenv python 3.9.0, pip version 20.3.1
> Any help would be appreciated.

You Are the Best!!! Thank you!!!!! It needs for running cmd administrator rights by right click and run as administrator!!

**Comment by dudu-24** [comment]
If u are having this kind of problem
Answer is simple , For the python version using pandas is officially not supported, I got the same error in python 3.10 
All I did is uninstall 3.10 version and install python 3.7 
Then all I did is 

`pip install pandas`

I think 3.9 supports pandas by the time I am writting this, But to safe I installed 3.7....

**Comment by AhmadJahun** [comment]
please i am a student carrying out a research on evaluation of machine learning classifiers for mobile malware detection,and from the research i find out that dealing with such a large amount of data to be train  need a guide on how to use modelling pipeline to easy the work.Thanks,

**Comment by tanmaychimurkar** [comment]
> and from the research i find out that dealing with such a large amount of data to be train need a guide on how to use modelling pipeline to easy the work.Thanks,

Hi @AhmadJahun, can you please elaborate on the question a little bit? Do you need a guide to handle to data modelling pipeline or a guide to training via the data pipeline?

If are referring to the first guide, you can checkout the following projects:

Modin: https://modin.readthedocs.io/en/stable/, 
Dask: https://www.dask.org/get-started

These would help you build a scalable data pipeline, as I have had a similar issue and used these to scale my data pipeline.

If you are referring to the second argument, about training via the data modelling pipeline, then you can checkout this project:
Ray: https://docs.ray.io/en/latest/index.html

Hope this helps.
