### ISSUE TITLE
Unable to see currency when loading excel file

### ISSUE THREAD

**Issue by ShayHa** [pandas-dev/pandas#32058]
```python
df = pd.read_excel(file)

```
So I have a few columns with numbers and currency e.g 155 USD.
When I load this table to python all I see is the numbers without the currency.
My solution was to convert the file to csv before loading it but I just hate using powershell script to convert each excel file to csv before using it.

Thanks.

**Comment by WillAyd** [comment]
Formats are not carried over from Excel by design, which I assume is what is being used here. If you are looking for strategies around that should try asking on StackOverflow (this tracker is just for bug reports and enhancement requests)
