### ISSUE TITLE
level argument for nunique

### ISSUE THREAD

**Issue by SylvainLan** [pandas-dev/pandas#32059]
The `unique` method makes it possible to specify a level for a multi-indexed df. I was wondering if it could also be made for the `nunique` method. 

If this sounds useful I could try to work on it.

**Comment by jbrockmendel** [comment]
I don't see a serious need for this, since users can do `df.groupby(level=whatever).nunique()`

**Comment by SylvainLan** [comment]
I'm not sure I understood your answer @jbrockmendel 

for instance let's do : 
```
df = pd.DataFrame({
'col1': [1,2,3,1,2,3,1,2,3], 
'col2': ['a','b','a','b','a','b','a','b','a'], 
'col3': [0,1,2,3,4,5,6,7,8]})

df = df.set_index(['col1', 'col2']).sort_index()
```

By doing `df.index.unique(level=1)` I get sth like `['a', 'b']` and I would like to have the call `df.index.nunique(level=1)` to return `2` as it is the number of unique indexes for the second level of my df. 

`df.groupby(level=1).nunique()` does not yield the result I wanted, as it gives the number of unique element of `col3` for each index of `col2`.

It is nothing more than `len(df.index.unique(level=1))`, but I was wondering if it could be an interesting enhancement.

**Comment by jbrockmendel** [comment]
I see.  I thought you wanted to get the number of unique elements in the data, per group, but you are talking about `df.index.nunique`.  Why not just `df.index.levels[1].nunique()`?

**Comment by SylvainLan** [comment]
It works indeed, as works `df.index.levels[1].unique()` instead of `df.index.unique(level=1)`, hence this issue. But again, it is nothing more than a small enhancement and I'll gladly close this issue if deemed unnecessary !

**Comment by mroeschke** [comment]
Thanks for the suggestion, but since there's an already a method for getting the expected result I agree that it probably not worth having multiple ways of doing the same thing. Going to close but happy to reopen if there's renewed interest from the core devs.
