### ISSUE TITLE
CI: Web and Docs fails

### ISSUE THREAD

**Issue by AlexKirko** [pandas-dev/pandas#32060]
#### Problem description

Currently, Web and Docs build seems to fail for everyone during CI, regardless of PR. Saw this in #31563 and #32055. 

This is the error:
```
Extension error:
Could not import extension contributors (exception: No module named 'gitdb.utils.compat')
##[error]Bash exited with code '2'.
```

**Comment by TomAugspurger** [comment]
https://github.com/gitpython-developers/GitPython/issues/983.

So we need gitpython>=3.0.6 or we need to pin to gitdb==3.0.1. Seems like gitpython 3.0.6 isn't on conda-forge yet.

**Comment by MomIsBestFriend** [comment]
May be completely wrong here, but aren't the docs are checked/pushed to the website, by ```github actions```?

**Comment by Harmon758** [comment]
It seems like GitPython v3.0.8 is on conda-forge now:
https://anaconda.org/conda-forge/gitpython/
https://github.com/conda-forge/gitpython-feedstock/pull/36

**Comment by MarcoGorelli** [comment]
Closing as it seems this is now fixed
