### ISSUE TITLE
Repeated `convert_dtypes()` fails for unicode string

### ISSUE THREAD

**Issue by tsoernes** [pandas-dev/pandas#32081]
#### Code Sample, a copy-pastable example if possible
Converting object to 'string' succeeds once, but not twice.
```python
In [635]: pd.Series([name], dtype='object')
Out[643]: 
0    OSCAR KANG’ORO
dtype: object

In [644]: pd.Series([name], dtype='object').convert_dtypes()
Out[644]: 
0    OSCAR KANG’ORO
dtype: string

In [645]: pd.Series([name], dtype='object').convert_dtypes().convert_dtypes()
---- (full traceback above) ----
File /home/torstein/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py, line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
File <ipython-input-645-6c1facea723b>, line 1, in <module>
    pd.Series([name], dtype='object').convert_dtypes().convert_dtypes()
File /home/torstein/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py, line 6046, in convert_dtypes
    infer_objects, convert_string, convert_integer, convert_boolean
File /home/torstein/anaconda3/lib/python3.7/site-packages/pandas/core/series.py, line 4393, in _convert_dtypes
    result = input_series.astype(inferred_dtype)
File /home/torstein/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py, line 5698, in astype
    new_data = self._data.astype(dtype=dtype, copy=copy, errors=errors)
File /home/torstein/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py, line 582, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
File /home/torstein/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py, line 442, in apply
    applied = getattr(b, f)(**kwargs)
File /home/torstein/anaconda3/lib/python3.7/site-packages/pandas/core/internals/blocks.py, line 607, in astype
    values = self.values.astype(dtype)
File /home/torstein/anaconda3/lib/python3.7/site-packages/pandas/core/arrays/string_.py, line 260, in astype
    return super().astype(dtype, copy)
File /home/torstein/anaconda3/lib/python3.7/site-packages/pandas/core/arrays/base.py, line 443, in astype
    return np.array(self, dtype=dtype, copy=copy)
File /home/torstein/anaconda3/lib/python3.7/site-packages/pandas/core/arrays/numpy_.py, line 184, in __array__
    return np.asarray(self._ndarray, dtype=dtype)
File /home/torstein/anaconda3/lib/python3.7/site-packages/numpy/core/_asarray.py, line 85, in asarray
    return array(a, dtype, copy=False, order=order)

UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 10: ordinal not in range(128)

```

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.18-100.fc30.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : nb_NO.UTF-8
LOCALE           : nb_NO.UTF-8

pandas           : 1.0.1
numpy            : 1.17.3
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 41.6.0.post20191030
Cython           : 0.29.13
pytest           : 5.2.2
hypothesis       : None
sphinx           : 2.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.2.2
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.8.4 (dt dec pq3 ext lo64)
jinja2           : 2.10.3
IPython          : 7.9.0
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 2.2.3
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 3.0.0
pandas_gbq       : None
pyarrow          : 0.15.1
pytables         : None
pytest           : 5.2.2
pyxlsb           : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.3.10
tables           : 3.5.2
tabulate         : 0.8.5
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.2
numba            : 0.46.0

</details>

**Comment by jreback** [comment]
this is a duplicate and fixed in 1.02 if someone can find the reference

**Comment by dsaxton** [comment]
I think this is the original issue: https://github.com/pandas-dev/pandas/issues/31731

**Comment by MarcoGorelli** [comment]
Thanks @tsoernes 

Closing as this is fixed on master, but feel free to open if you build from the source and find that the problem persists

```
name = 'OSCAR KANG’ORO'                                                                                 

In [6]: pd.Series([name], dtype='object').convert_dtypes().convert_dtypes()                                     
Out[6]: 
0    OSCAR KANG’ORO
dtype: string
```
