### ISSUE TITLE
Installing pandas on aarch64

### ISSUE THREAD

**Issue by odidev** [pandas-dev/pandas#32092]
Summary
----------
Installing pandas on aarch64 via pip using command "pip3 install pandas" tries to build wheel from source code

Problem description
----------------------
Pandas don't have wheel for aarch64 on PyPI repository. So, while installing pandas via pip on aarch64, pip builds wheel for same resulting in it takes more time to install pandas. Making wheel available for aarch64 will benefit aarch64 users by minimizing pandas installation time.

Expected Output
------------------
Pip should be able to download pandas wheel from PyPI repository rather than building it from source code.

@pandas team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make pandas wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by WillAyd** [comment]
We build a manylinux wheel - is that not usable? If not does pypi accept a wheel for the platform?

**Comment by jtiscione** [comment]
This is what happens for me on aarch64:

sudo -H pip install pandas
```
Collecting pandas
  Using cached https://files.pythonhosted.org/packages/02/c3/e8c56de02d6c52f8541feca2fd77117e8ae4956f7b3e5cdbed726624039b/pandas-1.0.1.tar.gz
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-mn_s23ky/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.29.13' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version>='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version>='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"''
       cwd: None
  Complete output (39 lines):
  Traceback (most recent call last):
    File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.6/dist-packages/pip/__main__.py", line 16, in <module>
      from pip._internal.main import main as _main  # isort:skip # noqa
    File "/usr/local/lib/python3.6/dist-packages/pip/_internal/main.py", line 8, in <module>
      import locale
    File "/usr/lib/python3.6/locale.py", line 16, in <module>
      import re
    File "/usr/lib/python3.6/re.py", line 142, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  Error in sys.excepthook:
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
      if not enabled():
    File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
      import re
    File "/usr/lib/python3.6/re.py", line 142, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  
  Original exception was:
  Traceback (most recent call last):
    File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.6/dist-packages/pip/__main__.py", line 16, in <module>
      from pip._internal.main import main as _main  # isort:skip # noqa
    File "/usr/local/lib/python3.6/dist-packages/pip/_internal/main.py", line 8, in <module>
      import locale
    File "/usr/lib/python3.6/locale.py", line 16, in <module>
      import re
    File "/usr/lib/python3.6/re.py", line 142, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-mn_s23ky/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.29.13' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version>='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version>='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' Check the logs for full command output.
```

**Comment by jreback** [comment]
we have 0 support / testing for big endian platforms (and not wheel capable linux)

so will take patches but you are on your own

**Comment by jtiscione** [comment]
Actually I got it working on arch64 once I uninstalled enum34.

**Comment by jreback** [comment]
@jtiscione great

**Comment by rhenwood-arm** [comment]
@jtiscione : it looks like enum34 is a compatibility layer for older Python versions. Which version of python were you using?

**Comment by jtiscione** [comment]
This was on Python 3.6.9. The enum34 thing is a known issue; I totally forgot I had installed it for another project, which needed it for some reason.

It only seems to interfere during installation. Once I removed enum34, I was able to install pandas successfully, and it's still working if I reinstall enum34.

**Comment by odidev** [comment]
Hi @jreback , @rhenwood-arm this issue has been raised to make the pandas wheel available for aarch64. Can you please reopen this issue and let me know if I can help you in this activity. I am very much interested to work on this.

**Comment by rhenwood-arm** [comment]
@WillAyd the manylinux wheel is unsuitable in this case because the request is about a different architecture (AArch64 aka Arm64). Different architectures are supported in 'manylinux2014', which I now supported in pypi and pip. This means that this project can add an entry in https://pypi.org/project/pandas/#files with a wheel for AArch64 as well.

Without a wheel the install of Pandas on AArch64 triggers a build of binary dependencies from source. This is slow.

There are a number of approaches to building a wheel for AArch64:
 1. The output from an aarch64 Travis-CI job.
 2. Building on an AArch64 platform.

or, in the absence of hardware:
 3. Running the manylinux2014 aarch64 wheel build environment https://quay.io/repository/pypa/manylinux2014_aarch64 in emulation https://blog.hypriot.com/post/docker-intel-runs-arm-containers/
 4. Doing a cross-compile from within the existing manylinux2014 x86 wheel build environment.

I am working with @odidev on documenting these alternatives. Please let me know if this project favors one over the others.

**Comment by odidev** [comment]
Ping @WillAyd Please could you have a look and suggest what more is required from my end.

**Comment by odidev** [comment]
Ping @WillAyd could you please share your thoughts on this.

**Comment by odidev** [comment]
Ping @WillAyd , I have created sample pandas aarch64 wheel and uploaded same on PyPi. Please find below supporting logs. 

Travis Log:   https://travis-ci.com/github/mpmkp2020/pandas/jobs/327256446
travis file:  https://github.com/mpmkp2020/pandas/blob/master/.travis.yml
cmake-odidev: https://pypi.org/project/pandas-mpmkp/

Could you please let me know if I can help in uploading pandas aarch64 wheel to PyPi?

**Comment by TomAugspurger** [comment]
@odidev to get wheels uploaded to PyPI we'll need to include an aarch64 build at https://github.com/MacPython/pandas-wheels.

**Comment by odidev** [comment]
Ping @TomAugspurger , I will work on this and update you with my findings. Thanks.

**Comment by TomAugspurger** [comment]
@odidev thanks. But before packaging for aarch64, won't we need to include aarch64 in our CI?

**Comment by odidev** [comment]
@TomAugspurger, looks like ossdev07 is working on including aarch64 in pandas CI. And, I don't think its a blocker to release pandas aarch64 wheel.

**Comment by jreback** [comment]
@odidev CI is a blocker for releasing anything - especially a non typical build

**Comment by ossdev07** [comment]
@TomAugspurger / @jreback ,
> @odidev CI is a blocker for releasing anything - especially a non-typical build

I have resolved issues in CI for ARM64 jobs and added a commit as well in #30641 . ARM64 build in Travis CI is passing as well. It will be helpful if that is merged. Can you review and provide your feedback in that PR.

**Comment by TomAugspurger** [comment]
Let's keep the discussion of ARM64 in #30641.

**Comment by rafis** [comment]
ARM is not big endian, 99.9% of current ARMs are little endian.

**Comment by vinzinz1396** [comment]
How did you resolve this issue about pandas installation? I'm working on ubuntu in ARM64. Please let me know.
