### ISSUE TITLE
ambiguous pandas filtering doesn't give warnings

### ISSUE THREAD

**Issue by mdf-github** [pandas-dev/pandas#32113]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

df = pd.DataFrame({'a': [True,True,False,False], 'b': [1,0,1,0]})

fltr1 = (
         (df['a']) &
         df['b'] == 0
        )

fltr2 = (
         (df['a']) &
         (df['b'] == 0)
        )

# fltr1 and fltr2 give very different results
```
#### Problem description

I finally found the bug in my code, but was surprised pandas didn't raise even a warning. Wouldn't it be better to issue a warning or an error about ambiguous combinations like this (which like mine had missing parentheses)?

#### Expected Output

A warning that the filter is ambiguous.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.4.0-18362-Microsoft
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.3
numpy            : 1.17.4
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 42.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.13
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
</details>

**Comment by TomAugspurger** [comment]
I don't think pandas has any way of knowing the "intended" operation, so we have no way of knowing parenthesis are "missing".

**Comment by MarcoGorelli** [comment]
Thanks @mdf-github 

Closing as I believe this is mentioned in the [user guide](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#boolean-indexing), along with an example:

> Another common operation is the use of boolean vectors to filter the data. The operators are: | for or, & for and, and ~ for not. These must be grouped by using parentheses, since by default Python will evaluate an expression such as df['A'] > 2 & df['B'] < 3 as df['A'] > (2 & df['B']) < 3, while the desired evaluation order is (df['A > 2) & (df['B'] < 3).
> 
> Using a boolean vector to index a Series works exactly as in a NumPy ndarray:
> 
> ```
> In [143]: s = pd.Series(range(-3, 4))
> 
> In [144]: s
> Out[144]: 
> 0   -3
> 1   -2
> 2   -1
> 3    0
> 4    1
> 5    2
> 6    3
> dtype: int64
> 
> In [145]: s[s > 0]
> Out[145]: 
> 4    1
> 5    2
> 6    3
> dtype: int64
> 
> In [146]: s[(s < -1) | (s > 0.5)]
> Out[146]: 
> 0   -3
> 1   -2
> 4    1
> 5    2
> 6    3
> dtype: int64
> 
> In [147]: s[~(s < 0)]
> Out[147]: 
> 3    0
> 4    1
> 5    2
> 6    3
> dtype: int64
> 
> 
> ```
