### ISSUE TITLE
groupby pd.Grouper with freq gives inconsistent groupings

### ISSUE THREAD

**Issue by mkowen1** [pandas-dev/pandas#32136]
#### Code Sample, a copy-pastable example if possible

```python
dates = pd.date_range(start='2020-02-01 09:30:00.01', periods=5, freq='14ms')
dates2 = pd.date_range(start='2020-02-01 11:00:00.01', periods=5, freq='8ms')
df = pd.DataFrame({'A': [1] * 10 + [2] * 10,
                   'B': np.concatenate((dates, dates2, dates, dates2)),
                   'C': np.arange(20) + 1})

df["B"] = pd.to_datetime(df["B"])
df['num_group'] = df.groupby(["A", pd.Grouper(key="B", freq="60ms")]).ngroup()
df
```
For the desired group of len=5, where A==1 and B about 9:30:
num_group==0 has length 4, num_group==1 has length 1

```python
df['num_group'] = df.groupby(["A", pd.Grouper(key="B", freq="61ms")]).ngroup()
```
num_group==0 has length 1, num_group==1 has length 4

```python
df['num_group'] = df.groupby(["A", pd.Grouper(key="B", freq="70ms")]).ngroup()
```
num_group==0 has length 3, num_group==1 has length 2

```python
df['num_group'] = df.groupby(["A", pd.Grouper(key="B", freq="72ms")]).ngroup()
```
num_group==0 has length 5 (expected output, this is all A==1 and B around 9:30)

```python
df['num_group'] = df.groupby(["A", pd.Grouper(key="B", freq="73ms")]).ngroup()
```
same split of the group as freq='60ms'

For freq greater than "100ms" (have not rigorously tested), appears to be the same (expected) as the 72ms freq case.

#### Problem description
Performing a groupby on a pd.Grouper with varying freqs returns differing ngroups() for some reason. As I change freq from 60 to 73ms, it splits what should be one group into subgroups of varying sizes.

Grouping on the pd.Grouper and then calling ngroup would be an nice way to perform secondary groupby-aggregations using the num_group as a key instead of a time window. If we have a sparse timeseries, then resample or rolling would 1) create additional unwanted rows or 2) condense the "B" time series column such that there isn't a unique key to merge back to the original dataframe.

Since the first five rows are from 09:30:00.010 to 09:30:00.066, I would not expect to have to use a freq >= 100ms to group these 56ms rows together, and the freqs cause unexpected groupings without explanation.

#### Expected Output
Expected output for all of the above should return num_group a series of [0]*5 + [1]*5 + [2]*5 + [3]*5, instead of varying divisions with max(num_group) == e.g. 7

### Show Versions

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : None.None

pandas           : 1.0.1
numpy            : 1.15.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.2.0.post20200209
Cython           : None
pytest           : 5.3.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 2.2.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.3.5
pyxlsb           : None
s3fs             : None
scipy            : 1.1.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by Dr-Irv** [comment]
I think this is an issue with respect to the origin of the time of the grouper, and that was not clear with pandas 1.0.1 (used in your report here).  Starting with pandas 1.1, the parameter `origin` has been added to `pd.Grouper`.  If I take your example and use `origin="start"`, then at least for the first 2 cases (`60ms` and `61ms`), I get the expected results.

@mkowen1 Can you do this again using that parameter and determine if the issue still persists?

**Comment by mkowen1** [comment]
@Dr-Irv thanks for the info, I have updated to 1.1.2 and tried using `origin` parameter in `pd.Grouper`. This causes some differences from the previous 1.0.1 version, namely in the first group. However for `70ms` the issue still persists -- here is the output:

```
    A                       B   C  num_group
0   1 2020-02-01 09:30:00.010   1          0
1   1 2020-02-01 09:30:00.024   2          0
2   1 2020-02-01 09:30:00.038   3          0
3   1 2020-02-01 09:30:00.052   4          0
4   1 2020-02-01 09:30:00.066   5          0
5   1 2020-02-01 11:00:00.010   6          1
6   1 2020-02-01 11:00:00.018   7          1
7   1 2020-02-01 11:00:00.026   8          2
8   1 2020-02-01 11:00:00.034   9          2
9   1 2020-02-01 11:00:00.042  10          2
10  2 2020-02-01 09:30:00.010  11          3
11  2 2020-02-01 09:30:00.024  12          3
12  2 2020-02-01 09:30:00.038  13          3
13  2 2020-02-01 09:30:00.052  14          3
14  2 2020-02-01 09:30:00.066  15          3
15  2 2020-02-01 11:00:00.010  16          4
16  2 2020-02-01 11:00:00.018  17          4
17  2 2020-02-01 11:00:00.026  18          5
18  2 2020-02-01 11:00:00.034  19          5
19  2 2020-02-01 11:00:00.042  20          5
```

It seems non-intuitive that rows 5 and 6 would be their own group (num_group == 1), despite being "within 70ms" of rows 7, 8, 9 (num_group == 2).

**Comment by Dr-Irv** [comment]
@mkowen1 The above is correct.  With `origin="start"`, the grouper uses the first time in the series as the origin.  You then chop up each 70 ms interval into chunks, and that determines the boundaries.  Look at this:
```python
>>> ts=pd.Timestamp("2020-02-01 09:30:00.010")
>>> ts
Timestamp('2020-02-01 09:30:00.010000')
>>> td=pd.Timedelta(70, unit='ms')
>>> td
Timedelta('0 days 00:00:00.070000')
>>> ts + 77142*td
Timestamp('2020-02-01 10:59:59.950000')
>>> ts + 77143*td
Timestamp('2020-02-01 11:00:00.020000')
```

So group 1 begins at 2020-02-01 10:59:59.950000 and ends at 2020-02-01 11:00:00.020000

I think we can close this, but would like your confirmation.

**Comment by mkowen1** [comment]
Yeah I suspected that was the case, thank you for confirming.
