### ISSUE TITLE
API: joining DatetimeIndexes not preserving freq

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#32157]
```
dti = pd.date_range('2016-01-01', periods=10)
left, right = dti[:5], dti[5:]
joined = left.join(right, how="outer")
```

In master `joined.freq` comes back as None, while in 0.25.3 it was "D".  There is some code in DatetimeIndex._wrap_joined_index that suggests to me this was intentional.

Can someone confirm this suspicion cc @jorisvandenbossche ?  If so, I've got a branch that restores the old behavior, just need to add tests.

**Comment by jorisvandenbossche** [comment]
> There is some code in DatetimeIndex._wrap_joined_index that suggests to me this was intentional.

Do you mean it was intentionally preserving the freq, or that it was an intentional change in 1.0 to no longer preserve this?

**Comment by jbrockmendel** [comment]
> Do you mean it was intentionally preserving the freq, or that it was an intentional change in 1.0 to no longer preserve this?

_wrap_joined_index looks like it was written to intentionally preserve the freq.
