### ISSUE TITLE
Tried this and output was true. Again tried to read the file car = pd.read_csv("/Users/apple/Desktop/usedcars.csv". But ended with same error

### ISSUE THREAD

**Issue by SatyakeerthiS** [pandas-dev/pandas#32195]
Pls provide your directory structure, then try:

```
import os 
os.getcwd()
# your current working directory will be displayed
os.path.exists('Department_of_Recreation_and_Parks__Facility_and_Park_Information.csv')
# Must be True, otherwise it is unrelated to pandas
```

Not sure why you're caring `matplotlib`. If you trying a script taken from somewhere, you can attach the link.

_Originally posted by @sinhrks in https://github.com/pandas-dev/pandas/issues/10457#issuecomment-116166868_

**Comment by SatyakeerthiS** [comment]
ParserError                               Traceback (most recent call last)
<ipython-input-67-0210f97304d3> in <module>
----> 1 car = pd.read_csv('/Users/apple/Desktop/usedcars.csv')

~/opt/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    683         )
    684 
--> 685         return _read(filepath_or_buffer, kwds)
    686 
    687     parser_f.__name__ = name

~/opt/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    461 
    462     try:
--> 463         data = parser.read(nrows)
    464     finally:
    465         parser.close()

~/opt/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py in read(self, nrows)
   1152     def read(self, nrows=None):
   1153         nrows = _validate_integer("nrows", nrows)
-> 1154         ret = self._engine.read(nrows)
   1155 
   1156         # May alter columns / col_dict

~/opt/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py in read(self, nrows)
   2057     def read(self, nrows=None):
   2058         try:
-> 2059             data = self._reader.read(nrows)
   2060         except StopIteration:
   2061             if self._first_chunk:

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.read()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_low_memory()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_rows()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._tokenize_rows()

pandas/_libs/parsers.pyx in pandas._libs.parsers.raise_parser_error()

ParserError: Error tokenizing data. C error: Expected 1 fields in line 6, saw 2

**Comment by charlesdong1991** [comment]
what does your csv data look like, might be issues with the header/delimiter of your data?

**Comment by WillAyd** [comment]
Thanks for the report but this appears to just be a malformed csv file. You should try asking in StackOverflow for help - this tracker is reserved for bug reports and enhancement requests.
