### ISSUE TITLE
visual bug in pd.style.background_gradient

### ISSUE THREAD

**Issue by DSLituiev** [pandas-dev/pandas#32208]
#### Problem description
The `pd.style.background_gradient` messes up the color order. That is it display wrongs colors that obviously don't conform the order of underlying numbers.

#### Code Sample, a copy-pastable example if possible
```python
import io
import pandas as pd
pd.read_csv(io.StringIO('''round,letter,source,findings,punctuation,see,reference
round 1,0.9853724610779391,0.9967806193222191,0.9857700345095259,0.966600495940578,0.98430677224734,0.572541233138048
round 2,0.9999946348522148,0.9995960833535309,0.994186634099717,0.987516415231207,0.9903793223872329,0.863724309623997
round 3,0.999963099705787,0.999681116612525,0.993544442544026,0.990503466426927,0.983378536954797,0.924636377166516
'''))

aucs.style.background_gradient(cmap='viridis_r').format("{:.2%}")

```

<img width="578" alt="Screen Shot 2020-02-23 at 13 09 22" src="https://user-images.githubusercontent.com/8426290/75120156-26f87680-563e-11ea-824f-1222be131eee.png">

Notice that 57% appears to be yellow, while on the left of it 98% is green (that is it suggest that it's a lower number).

#### Expected Output
This is how same table was plotted in seaborn. Find 10 differences ;)
![image](https://user-images.githubusercontent.com/8426290/75120174-4ee7da00-563e-11ea-91a5-26334d9d5f8a.png)

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.2.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.1
numpy            : 1.16.2
pytz             : 2018.4
dateutil         : 2.7.3
pip              : 19.0.3
setuptools       : 40.8.0
Cython           : 0.29.10
pytest           : 4.3.1
hypothesis       : None
sphinx           : 1.8.5
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.1
html5lib         : None
pymysql          : None
psycopg2         : 2.7.5 (dt dec pq3 ext lo64)
jinja2           : 2.10
IPython          : 7.4.0
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 2.2.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 4.3.1
pyxlsb           : None
s3fs             : None
scipy            : 1.2.1
sqlalchemy       : 1.3.10
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : 0.46.0
</details>

**Comment by MarcoGorelli** [comment]
Thanks @DSLituiev for the report

Could you change your example to
```
import io
import pandas as pd
aucs = pd.read_csv(io.StringIO('''round,letter,source,findings,punctuation,see,reference
round 1,0.9853724610779391,0.9967806193222191,0.9857700345095259,0.966600495940578,0.98430677224734,0.572541233138048
round 2,0.9999946348522148,0.9995960833535309,0.994186634099717,0.987516415231207,0.9903793223872329,0.863724309623997
round 3,0.999963099705787,0.999681116612525,0.993544442544026,0.990503466426927,0.983378536954797,0.924636377166516
'''))

aucs.set_index('round').style.background_gradient(cmap='viridis_r').format("{:.2%}")
```
so it runs? Thanks

Will look into this

**Comment by MarcoGorelli** [comment]
@DSLituiev you need to pass `axis=None` for it to work the way you intend to:

```
import io
import pandas as pd
aucs = pd.read_csv(io.StringIO('''round,letter,source,findings,punctuation,see,reference
round 1,0.9853724610779391,0.9967806193222191,0.9857700345095259,0.966600495940578,0.98430677224734,0.572541233138048
round 2,0.9999946348522148,0.9995960833535309,0.994186634099717,0.987516415231207,0.9903793223872329,0.863724309623997
round 3,0.999963099705787,0.999681116612525,0.993544442544026,0.990503466426927,0.983378536954797,0.924636377166516
'''))

aucs.set_index('round').style.background_gradient(cmap='viridis_r', axis=None).format("{:.2%}")
```

![image](https://user-images.githubusercontent.com/33491632/75273476-d8dba280-57f8-11ea-9cc7-b7416fd6361a.png)

**Comment by Klimmy** [comment]
Hi guys,

I faced similar problem. Strange behavior of axis parameter. Looks like rowwise (axis=0) doesn't apply gradient separately for each row.
Using your example, if we change _round 3 - letter_ cell from 0.99 to 1.99 it affects _round 2_ row as well, which I guess not expected.


```
import io
aucs = pd.read_csv(io.StringIO('''round,letter,source,findings,punctuation,see,reference
round 1,0.9853724610779391,0.9967806193222191,0.9857700345095259,0.966600495940578,0.98430677224734,0.572541233138048
round 2,0.9999946348522148,0.9995960833535309,0.994186634099717,0.987516415231207,0.9903793223872329,0.863724309623997
round 3,1.999963099705787,0.999681116612525,0.993544442544026,0.990503466426927,0.983378536954797,0.924636377166516
'''))

aucs.set_index('round').style.background_gradient(cmap='viridis_r', axis=0).format("{:.2%}")
```

### Initial data
![image](https://user-images.githubusercontent.com/8791068/96726297-7e600980-13ba-11eb-92e3-3cf9701979d9.png)

### Modified one cell
![image](https://user-images.githubusercontent.com/8791068/96726334-88820800-13ba-11eb-95e6-aaa417ddf62d.png)

**Comment by fooled-lama** [comment]
Hey, was getting a similar issue and I think it is because the html is being written out past a character limit and thus not being rendered properly. My hack fix was to use the textwrap package to make sure the lines were being truncated correctly, and playing around with the fill setting.

This is stemming from pandas giving each cell in a table a unique id - which is good. But can get wonky with large dataframes when each cell has properties and a unique id which are being spit out on the same line.

Here is what happens with large dataframes at the 1000th character position.
```html

#T_4858f_row14_col15, #T_4858f_row14_col16, #T!
#T_4858f_row18_col20, #T_4858f_row18_col21, #T_4858f_!
```


```python

import textwrap

html_str = textwrap.fill(html_str, fill=200)

```
