### ISSUE TITLE
CI: value_counts tests failing sometimes

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#32220]
It seems like we're getting some failures from `test_value_counts_unique_nunique` in `pandas/tests/base/test_ops.py` (weird thing is that it only fails some of the time; maybe because of randomized test data?). Looks like these tests were updated in https://github.com/pandas-dev/pandas/pull/32046; @SaturnFromTitan any ideas what might be happening there?

Sample failed pipeline: https://github.com/pandas-dev/pandas/runs/464853016

**Comment by SaturnFromTitan** [comment]
Hm, that's weird. Looking at the error log above the test failed for the fixture value `float16-series` [defined here](https://github.com/pandas-dev/pandas/blob/master/pandas/conftest.py#L1036).

If I recall correctly that fixture value wasn't used/tested in this test before, so possibly we can just remove it from the fixture again. I have no idea about why it's flaky/broken though...

**Comment by WillAyd** [comment]
We generally don’t support float16 so if it is causing test failures can probably remove

**Comment by SaturnFromTitan** [comment]
xref: #32205

**Comment by SaturnFromTitan** [comment]
take
