### ISSUE TITLE
Creating lag windows in pandas is slow for large dataset

### ISSUE THREAD

**Issue by ankurrajdev** [pandas-dev/pandas#32239]
#### Code Sample, a copy-pastable example if possible
```python
# Your code here
df = pd.DataFrame(
        {
            "date": pd.date_range("2018-01-01", periods=12, freq="D"),
            "group": ["first", "second"] * 6,
            "clicks": range(12)
        }
    ).sample(
        frac=1
    )

I want to add sum_click_last2days, mean_click_last2days, sum_click_last4days, mean_click_last4days and so on depending on columns, functions and lag windows passed.
Here last n days mean rolling sum till last day. Hence, if we are running on 10th, we would want sum for 8th and 9th.

The function I wrote is:
for lag in self.lags:
            agg_df = (
                df_tmp.set_index("date")
                .groupby("group")
                .resample("D")
                .sum()
                .groupby("group")
                .shift()
                .reset_index()
                .fillna(0)
                .groupby("group")
                .rolling(f"{lag}D", on="date")
                .agg(self.funcs)[self.cols]
            )
```
This is working fine for smaller dataset but is not efficient for a large dataset( 19M and there are 700K groups)
#### Problem description
I want to add new variables to a given dataset with lag windows. For instance, we have a column name clicks, we want to add sum_click_last2days, mean_click_last2days, sum_click_last4days, mean_click_last4days and so on depending on columns, functions and lag windows passed. This is working fine for smaller dataset but is not efficient for a large dataset( 19M and there are 700K groups)

#### Expected Output
expected_data = pd.DataFrame(
        {
            "date": pd.to_datetime(
                [
                    "2018-01-01",
                    "2018-01-03",
                    "2018-01-05",
                    "2018-01-07",
                    "2018-01-09",
                    "2018-01-11",
                    "2018-01-02",
                    "2018-01-04",
                    "2018-01-06",
                    "2018-01-08",
                    "2018-01-10",
                    "2018-01-12",
                ]
            ),
            "group": ["first"] * 6 + ["second"] * 6,
            "clicks": [*range(0, 11, 2), *range(1, 12, 2)],
            "orders": [*range(10, 21, 2), *range(11, 22, 2)],
            "sum_clicks_last2days": [
                0.0,
                0.0,
                2.0,
                4.0,
                6.0,
                8.0,
                0.0,
                1.0,
                3.0,
                5.0,
                7.0,
                9.0,
            ],
            "sum_clicks_last4days": [
                0.0,
                0.0,
                2.0,
                6.0,
                10.0,
                14.0,
                0.0,
                1.0,
                4.0,
                8.0,
                12.0,
                16.0,
            ],
        }
    )

**Comment by WillAyd** [comment]
@ankurrajdev thanks for the report but given the size of this it isn’t clear there is a bug or performance problem. If you can profile the code and isolate an issue we can certainly reopen - otherwise you should try StackOverflow for questions as the Q&A format may be better suited to your needs (we reserve this board for big reports and enhancement requests)

**Comment by ankurrajdev** [comment]
@WillAyd  - This is a performance issue. The code is working for small datasets but is not working for large datasets. So, it's a performance issue.
I posted it there so that if anyone can provide a more efficient solution and optimize the code.

I wasn't sure if StackOverflow or Issue tracker was the best platform to post this issue.
