### ISSUE TITLE
Convert style object to DataFrame

### ISSUE THREAD

**Issue by m2rik** [pandas-dev/pandas#32243]
```python
# Your code here
df.style.hide_index()
```
#### Problem description

How do I convert a Style object back to a dataframe to be outputted by nbconvert as a latex file or pdf

**Comment by attack68** [comment]
Style objects are not designed to be converted back to DataFrames. They serve different purposes. If you need to convert a Style object to latex or pdf via nbconvert (including formatted styles) then this should be raised as an enhancement and discussed how to implement.
