### ISSUE TITLE
pandas.tseries.offsets.CustomBusinessDay apply_index implementation

### ISSUE THREAD

**Issue by gaibo** [pandas-dev/pandas#32251]
#### Code Sample

Hi there, I'm trying to do something like this:
```python
BUSDAY_OFFSET = pd.offsets.CustomBusinessDay(calendar=MY_HOLIDAY_CALENDAR)
my_rollback = pd.date_range('2010-05-10', '2020-02-25') + BUSDAY_OFFSET - BUSDAY_OFFSET
```
and I am getting the following warning:
```
C:\Users\my_username\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\arrays\datetimes.py:743: PerformanceWarning: Non-vectorized DateOffset being applied to Series or DatetimeIndex
  "or DatetimeIndex", PerformanceWarning)
```

#### Problem description

The custom business day non-vectorized addition/subtraction works, but when performed on the order of millions of dates (ridiculous because I could take out duplicate dates, I know, but it was my original use case), it takes a non-trivial amount of time, whereas `` pd.offsets.Day()`` can be added and subtracted in trivial time.

I checked _datetimes.py_ and CustomBusinessDay's apply_index() method is not implemented, and it is not clear from any indication whether that's intended (as in, the user should override it?) or not. [The doc page is here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.tseries.offsets.CustomBusinessDay.apply_index.html#pandas.tseries.offsets.CustomBusinessDay.apply_index).

Can anyone familiar with CustomBusinessDay's structure comment on whether there can be a simple fix?

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.2
pytest: 5.0.1
pip: 19.1.1
setuptools: 41.0.1
Cython: 0.29.12
numpy: 1.16.4
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.6.1
sphinx: 2.1.2
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: 1.2.1
tables: 3.5.2
numexpr: 2.6.9
feather: None
matplotlib: 3.1.0
openpyxl: 2.6.2
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.8
lxml.etree: 4.3.4
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.3.5
pymysql: None
psycopg2: None
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by jbrockmendel** [comment]
> whether there can be a simple fix?

Simple, no.  But if you want to make a PR, we can pick up some mileage by making a vectorized version of `is_on_offset`, which in turn could be used to make a vectorized rollforward, which is what you're actually trying to do (I think theres another issue about that, should xref).

In the meantime, if you're data has _lots_ of duplicates, you can do something like:

```
dti = my_giant_index.unique()
result = dti + offset - offset
ser = pd.Series(result, index=dti)
out = ser[my_giant_index]
answer = pd.DatetimeIndex(out)
```

**Comment by gaibo** [comment]
Thanks for quick response on that. I ended up doing exactly like you suggested.
Don't think I can make a PR for now - spent a bit of time looking at the source and it was a lot haha.

**Comment by jbrockmendel** [comment]
> spent a bit of time looking at the source and it was a lot haha

Yah, a DateOffset performance issue is actually how I got involved here in the first place

Closing this for now, we can re-open if you want to revisit this down th eline.
