### ISSUE TITLE
Rolling groupby should not maintain the by column in the resulting DataFrame

### ISSUE THREAD

**Issue by KraxelHuber** [pandas-dev/pandas#32262]
When performing a `rolling` operation on a `groupby` object, the index level will be incorrectly maintained in the dataframe.

```
import numpy as np
import pandas as pd

df = pd.DataFrame({'idx_L1': ['Level_1'] * 10 + ['Level_2'] * 10 + ['Level_3'] * 10,  
                   'idx_L2': ([1] * 5 + [2] * 5 + [3] * 5) * 2,  
                   'vals': np.arange(30)})

df.groupby(['idx_L1', 'idx_L2']).rolling(3).sum()
```

This issue has been discussed in #14013.

It has been closed eventhough the bug still exists in v1.01.

**Comment by jreback** [comment]
update the top with a minimal reproducible example

**Comment by KraxelHuber** [comment]
![image](https://user-images.githubusercontent.com/29901736/75490219-1173ab80-59b4-11ea-8b57-dc323b211981.png)

![image](https://user-images.githubusercontent.com/29901736/75490294-3700b500-59b4-11ea-9bc6-fd58e39578da.png)

When performing a `groupby `and apply the `rolling` function, it is my understanding, that `idx_L2` should be deleted from the value section.

**Comment by MarcoGorelli** [comment]
Thanks @KraxelHuber for the report!

To expedite resolution, could you please copy and paste your example into the issue you opened?

**Comment by MarcoGorelli** [comment]
This isn't just confined to `rolling`, but also to `DataFrame.groupby.apply`:

```
>>> import pandas as pd
>>> df = pd.DataFrame({'d': [1.0, 1.0, 1.0, 2.0, 2.0, 2.0], 'v': [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]})
>>> df.groupby('d').sum()                                                                                   
        v
d        
1.0   6.0
2.0  15.0

>>> df.groupby('d').apply(sum)                                                                              
       d     v
d             
1.0  3.0   6.0
2.0  6.0  15.0
```

**Comment by MarcoGorelli** [comment]
take

**Comment by benjamin-ny** [comment]
Not sure if it's the same issue, but I see a similar thing with `groupby` + `expanding`:

```python
(
    pd.DataFrame({
        'a': [0, 0, 0, 1, 1, 1, 1],
        'val': [10, 12, 11, 105, 103, 109, 109]
    })
    .set_index('a')
    .groupby('a')
    .expanding()
    .max()
)
```

<img width="83" alt="Bildschirmfoto 2020-06-10 um 10 35 36" src="https://user-images.githubusercontent.com/47246546/84245984-3379df80-ab06-11ea-8281-75c6aad02d33.png">

The same does not happen when using, for instance, `.transform(max)`.

(pandas version 1.0.1)
