### ISSUE TITLE
bug: inconsistent Series indexing crash, depending on DataFrame index type??

### ISSUE THREAD

**Issue by xuancong84** [pandas-dev/pandas#32263]
Recently, I encountered a very strange bug when indexing pd.Series in Pandas groupby object.
```
if False:
	df = pd.DataFrame({'app':['a', 'b', 'c', 'd', 'e'], 'sessionId':['1', '1', '2', '3', '3']},
		index=['a1', 'a2', 'a3', 'a4', 'a5']) # this will not cause the last line to crash
else:
	df = pd.DataFrame({'app': ['a', 'b', 'c', 'd', 'e'], 'sessionId': ['1', '1', '2', '3', '3']},
		index=[1,2,3,4,5]) # this will cause the last line to crash

df1 = [v.app[0] for k, v in df.groupby('sessionId')] # the crashing line
```
As shown in the above code, if df.index elements are string, pd.Timestamp, etc., the last line will not crash; however, if df.index elements are int, float, etc., the last line will crash. Ridiculously, in both cases `type(v.app)` is pd.Series, yet one is index-able, while the other one is not. It is worth noting that the crashing line has not even touched df.index, so why does the value type of df.index elements matters?

So do we have another general inconsistency due to incompetent programming?

**Comment by MarcoGorelli** [comment]
`0` will be interpreted as a label for integer indexes, rather than as a position.

If you need to access the position `0`, use `.iloc[0]`, as advised in [the user guide](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#different-choices-for-indexing)

> So do we have another general inconsistency due to incompetent programming?

Please try to be constructive
