### ISSUE TITLE
[Regression] Index matching is wrong for dataframe operations such as div and mul

### ISSUE THREAD

**Issue by harmbuisman** [pandas-dev/pandas#32288]
#### Code Sample, a copy-pastable example if possible
```python
import pandas as pd

A = pd.read_pickle('A.pcl')
B = pd.read_pickle('B.pcl')

A.mul(B)
```
#### Problem description

In pandas 1.01 the result of multiplying the two dataframes in this file is wrong (wrong values, wrong size), where it was right in 0.25.3:
[Analysis.zip](https://github.com/pandas-dev/pandas/files/4261081/Analysis.zip)

The output of the above in 1.0.1 gives:
![image](https://user-images.githubusercontent.com/7702207/75436009-291b4780-5954-11ea-923a-74d120f5af45.png)

It may be triggered by the difference in the order of the categories in the index, but I am not sure. This order is different in both 0.25.3 and 1.0.1, so in 0.25.3 this was not a problem:
![image](https://user-images.githubusercontent.com/7702207/75436372-bb235000-5954-11ea-8385-d8aa1efe495e.png)

#### Expected Output
The expected output is returned in 0.25.3:
![image](https://user-images.githubusercontent.com/7702207/75436196-7697b480-5954-11ea-8f51-e9dbe6530b40.png)

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.1
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.2.0.post20200209
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 0.15.0
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
numba            : 0.48.0
</details>

**Comment by TomAugspurger** [comment]
Can you provide a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

Is pickle necessary to reproduce the problem?

**Comment by harmbuisman** [comment]
> Can you provide a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports
> 
> Is pickle necessary to reproduce the problem?

Hi Tom, yes, that is a fair request. Thanks for the link. I tried to reproduce the problem with just code and simple dataframes, but sadly did not succeed in reproducing it that way. I will try some more things and will post an update if I succeed.

**Comment by TomAugspurger** [comment]
@harmbuisman we'll reopen when you can provide a minimal example.

**Comment by harmbuisman** [comment]
> @harmbuisman we'll reopen when you can provide a minimal example.

@TomAugspurger , I managed to find a reproduction, see the updated starting post. Can you reopen the issue?

**Comment by TomAugspurger** [comment]
Thanks! On master, I see the following output

```python
x  y
A  1    1
B  1    1
C  1    1
Name: value, dtype: int64
```

So I believe the issue has been fixed. We're releasing 1.1.0 soon which will have the fix.

**Comment by harmbuisman** [comment]
> Thanks! On master, I see the following output
> 
> ```python
> x  y
> A  1    1
> B  1    1
> C  1    1
> Name: value, dtype: int64
> ```
> 
> So I believe the issue has been fixed. We're releasing 1.1.0 soon which will have the fix.

Thanks, that is good news!
