### ISSUE TITLE
Incomplete reference to `convert_dtypes` in `to_numeric` docstring

### ISSUE THREAD

**Issue by onietosi** [pandas-dev/pandas#32295]
In the `pandas.to_numeric` [documentation page](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_numeric.html), in the **See also** section, `convert_dtypes` has no link attached to it.

I am not familiar with contributing to the docs but I believe this is because the docstring of `to_numeric` refers to `convert_dtypes` instead of `DataFrame.convert_dtypes`.

https://github.com/pandas-dev/pandas/blob/29d6b0232aab9576afa896ff5bab0b994760495a/pandas/core/tools/numeric.py#L67-L73

**Comment by jqmviegas** [comment]
take
