### ISSUE TITLE
CI: Publishing development web and docs to GitHub actions fails

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#32303]
Looks like using the ssh key to publish the development web and docs is not working. The error we get in the CI is that [the key has an invalid format](https://github.com/pandas-dev/pandas/runs/472871471?check_suite_focus=true#step:14:10).

I guess it's not as simple as the key content being incorrect, I guess it can't be obtained from the secrets, and probably the used key is just empty.

The relevant code is in the [yaml of the GitHub action](https://github.com/pandas-dev/pandas/blob/master/.github/workflows/ci.yml#L180).

Besides making sure that the key is correct (that it's the private and not the public, it's complete...), I guess a good test to help identify the problem could be replace the content of the key by some random text, and echo it and see that we're ready getting the full content with no garbage in it.

I think just few people have access to it, @TomAugspurger do you have time for it? Or do you know who else has access to the settings? I think it was said in some thread, but I fail to remember.

**Comment by TomAugspurger** [comment]
Here's the secrets screen.

<img width="660" alt="Screen Shot 2020-02-28 at 7 20 06 PM" src="https://user-images.githubusercontent.com/1312546/75596634-5e608c00-5a5f-11ea-8647-223646ed4ae6.png">

I don't think there's a way to view the contents of the secret.

> be replace the content of the key by some random text, and echo it and see that we're ready getting the full content with no garbage in it.

I think CI services typically don't allow you to print the key.

I've deleted the old key and re-created it with the private SSH key you provided me.

**Comment by datapythonista** [comment]
Thanks @TomAugspurger. Looks like we still got the same error, so I guess the problem is something else. I'll do some tests in a separate repo, and see if I can reproduce the problem.
