### ISSUE TITLE
DOC: Standardize references to pandas in the documentation

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#32316]
In our documentation (files in `doc/source/../*.rst`), we refer to pandas as `Pandas`, `pandas`, and `*pandas*` (sphinx italics).

For documentation consistency, we should standardize these to one form. `pandas` is the preferable form in our documentation files.

Unfortunately I don't think we create a lint rule for this pattern since we have to be flexible to references and hyperlinks.

**Comment by joybhallaa** [comment]
Can I take this issue?

**Comment by MomIsBestFriend** [comment]
> Can I take this issue?

@joybhallaa  Sure!
You can do this by commenting the word ```take``` (and nothing else, just the word ```take```), and the github bot will assign this issue to you.

**Comment by joybhallaa** [comment]
take

**Comment by jorisvandenbossche** [comment]
We could also decide to just use "pandas" instead of "*pandas*" (no italic), that's one thing less that you can forget to do.

**Comment by mroeschke** [comment]
Good point @jorisvandenbossche. I'd prefer `pandas` as well for that reason. Will update the original post

**Comment by mroeschke** [comment]
https://github.com/pandas-dev/pandas/pull/32439 only fixed the references for `development/*.rst`

**Comment by willie3838** [comment]
take

**Comment by EllieLockhart** [comment]
take

**Comment by LeviMatus** [comment]
take

**Comment by Mikhaylov-yv** [comment]
take
