### ISSUE TITLE
API: Named aggregations for groupby.transform()

### ISSUE THREAD

**Issue by ghost** [pandas-dev/pandas#32318]
#### Code Sample, a copy-pastable example if possible

```python
In [2]: df = pd.DataFrame({
   ...:     'A': [1, 1, 2, 2, 3, 3],
   ...:     'B': [4, 5, 6, 7, 8, 9]
   ...: })

In [3]: df
Out[3]:
   A  B
0  1  4
1  1  5
2  2  6
3  2  7
4  3  8
5  3  9

In [4]: df.groupby('A').agg(maximum=('B', 'max'))
Out[4]:
   maximum
A
1        5
2        7
3        9

In [5]: df.groupby('A').transform(maximum=('B', 'max'))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-10080a262c70> in <module>
----> 1 df.groupby('A').transform(maximum=('B', 'max'))

TypeError: transform() missing 1 required positional argument: 'func'

In [6]: df['maximum'] = df.groupby('A')['B'].transform('max')

In [7]: df
Out[7]:
   A  B  maximum
0  1  4        5
1  1  5        5
2  2  6        7
3  2  7        7
4  3  8        9
5  3  9        9
```
#### Problem description

[Named aggregation](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#named-aggregation) streamlines the process of creating columns as a result of `groupby.agg()`. A similar (identical?) API for `groupby.transform()` would provide the same benefit when creating new columns from `groupby.transform()`.

This issue may be related to  #28380.

#### Expected Output

```python
In [2]: df = pd.DataFrame({
   ...:     'A': [1, 1, 2, 2, 3, 3],
   ...:     'B': [4, 5, 6, 7, 8, 9]
   ...: })

In [3]: df.groupby('A').transform(maximum=('B', 'max'))
Out[3]:
   A  B  maximum
0  1  4        5
1  1  5        5
2  2  6        7
3  2  7        7
4  3  8        9
5  3  9        9
```

#### Output of ``pd.show_versions()``

<details>

In [8]: pd.show_versions()
C:\Users\dwales\AppData\Local\Continuum\anaconda3\lib\site-packages\fastparquet\dataframe.py:5: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import CategoricalIndex, RangeIndex, Index, MultiIndex

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.1
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.2.0.post20200210
Cython           : 0.29.15
pytest           : 5.3.5
hypothesis       : 5.4.1
sphinx           : 2.4.0
blosc            : None
feather          : None
xlsxwriter       : 1.2.7
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.8.4 (dt dec pq3 ext lo64)
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : 1.3.1
fastparquet      : 0.3.2
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.1.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : 0.13.0
pytables         : None
pytest           : 5.3.5
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.13
tables           : 3.6.1
tabulate         : 0.8.3
xarray           : 0.15.0
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.7
numba            : 0.48.0

</details>

**Comment by mroeschke** [comment]
Thanks for the request but it appears this hasn't gotten traction in a while so closing
