### ISSUE TITLE
pd.concat loses frequency attribute for 'continuous' DataFrame appends

### ISSUE THREAD

**Issue by nehalecky** [pandas-dev/pandas#3232]
Hey all, 

I have a `DataFrame` (df) that stores live sensor data that is captured at a specific frequency. New raw data from sensor is updated at a set interval (an attempt at bandwidth conservation),  which is parsed into a new df object.

These new update dataframes are of the same frequency, and contain data that is 'continuous' in time (i.e., they pick up right where the last timestamp left off), and ultimately I would like to append this new data to the existing dataframe while preserving the main dataframe frequency attribute. I tried by using a `concat` of old and new dataframes, however, it seems that `concat` doesn't check this case for continuous time series, and loses its frequency attribute. This can be reproduced in code below:

``` python
import pandas as pd
import numpy as np
dr = pd.date_range('01-Jan-2013', periods=100, freq='50L', tz='UTC')
df = pd.DataFrame(np.random.randn(100, 2), index=dr)
df.index
```

``` python
<class 'pandas.tseries.index.DatetimeIndex'>
[2013-01-01 00:00:00, ..., 2013-01-01 00:00:04.950000]
Length: 100, Freq: 50L, Timezone: UTC
```

These guys look good:

``` python
#Preserves frequency
print df[:50].index
print df[50:].index
```

``` python
<class 'pandas.tseries.index.DatetimeIndex'>
[2013-01-01 00:00:00, ..., 2013-01-01 00:00:02.450000]
Length: 50, Freq: 50L, Timezone: UTC
<class 'pandas.tseries.index.DatetimeIndex'>
[2013-01-01 00:00:02.500000, ..., 2013-01-01 00:00:04.950000]
Length: 50, Freq: 50L, Timezone: UTC
```

However, these guys, together, forget where they came from:

``` python
#Loses frequency
pd.concat([df[:50], df[50:]]).index
```

``` python
<class 'pandas.tseries.index.DatetimeIndex'>
[2013-01-01 00:00:00, ..., 2013-01-01 00:00:04.950000]
Length: 100, Freq: None, Timezone: UTC
```

I currently get around this with a `resample` of the resulting df to set frequency, which isn't that big of a deal, however, thought I'd mention it so that a more elegant behavior could be implemented. I'll try and take a look when I have time, but I know that all you here are so much more familiar with pandas internals. Any pointers?
And, as always, thank you! :)

**Comment by WillAyd** [comment]
Still an issue on 23.2

**Comment by scootty1** [comment]
Still an issue in 0.23.4.
My current workaround is:
`df.index.freq = df.index.inferred_freq`
If the index and frequency were continuous before concat, this always seems to be working. 
Compared with other methods like resampling or reindexing, this is several orders faster:
```
df.shape
# Out: (308160, 78)
%timeit df_full.index.freq = df_full.index.inferred_freq
# Out: 73.7 µs ± 8.26 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
%timeit df_full.resample('1T').mean()
# Out: 947 ms ± 58 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
%timeit df_full.reindex(pd.date_range(start=df_full.index[0], end=df_full.index[-1], freq='1T'))
# Out: 117 ms ± 5.22 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
So setting the frequency is about 13k times faster than resample and about 1.6k times faster than reindexing. If it is not known if the indices are contiguous, I'd thus go with reindex. Any opinions/advice on this?

**Comment by jbrockmendel** [comment]
@TomAugspurger did the concat_same_type implementation end up checking if freq could be preserved?

**Comment by TomAugspurger** [comment]
Nope, but it would certainly make a good standalone PR.

**Comment by nehalecky** [comment]
Wow! Thanks @jreback and @mroeschke and everyone here!
