### ISSUE TITLE
ENH: Syntactic sugar for DatetimeIndex datetime slicing

### ISSUE THREAD

**Issue by Alpima-Quant** [pandas-dev/pandas#32325]
```python
import pandas as pd
from datetime import datetime
index = pd.date_range(start=datetime(2019, 1, 1), end=datetime(2020, 1, 1), freq='D')
ts = pd.Series(index=index, dtype=float)
start_date = datetime(2019, 6, 1)
index_from_ts_slice = ts[start_date:].index
# this errors:
try:
    index_from_index_slice = index[start_date:]
except TypeError as e:
    print(e)
# I can use slice_indexer to get what I want but it is uglier
index_from_slice_indexer = index[index.slice_indexer(start_date)]
assert (index_from_ts_slice == index_from_slice_indexer).all()
```
When a Series or a DataFrame has a sorted DatetimeIndex, one can slice these structures using datetimes and square brackets notation. However this kind of slicing is not supported directly on a DatetimeIndex.
Basically I really like the datetime slicing notation and I'd like index[start_date:] to be able to return the same slice of the index as ts[start_date:].index or index[index.slice_indexer(start_date)]

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.9.93-boot2docker
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : C.UTF-8
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.0
numpy            : 1.14.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 39.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 0.9999999
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : 4.4.1
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 2.0.0
numexpr          : 2.7.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 0.17.1
sqlalchemy       : None
tables           : 3.4.2
tabulate         : None
xarray           : None
xlrd             : 1.1.0
xlwt             : None
xlsxwriter       : None
numba            : 0.35.0

</details>

**Comment by jbrockmendel** [comment]
I doubt we'd want to add anything to the public API for this.  The way you defined `index_from_ts_slice` is likely your best option.  Is there a reason that isn't workable?

**Comment by jbrockmendel** [comment]
closing as no action.  if youd like to discuss further we can reopen
