### ISSUE TITLE
DataFrame.sort_index() with ascending passed as a list on a single level index gives wrong result

### ISSUE THREAD

**Issue by BeanNan** [pandas-dev/pandas#32334]
I found some problems while using data_frame sort_index,  first, create dataframe

```
data = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=['a', 'b', 'c'])
data = data.set_index('a')
data.sort_index(level=['a'], ascending=[False])
```
Then I want to sort index "a" in descending order,
```
data.sort_index(level=['a'], ascending=[False])
```
The above code does not sort index a in descending order,   I found the reason is that this dataframe is a single index structure, so when ascending = list is passed, it does not take effect

https://github.com/pandas-dev/pandas/blob/bf613c14f41b624b432d0d6b9a29007e7990d460/pandas/core/frame.py#L4777-L4783

Because when it is used, the index may be single index or multi-index. In order to use the effect uniformly,I think there should be a judgment here. If index is a single index and ascending type == list, ascending should be equal to ascending [0]，This may be more user friendly

If yes, can I mention pr

**Comment by Dr-Irv** [comment]
It seems that this works fine:
```python
 data.sort_index(level=['a'], ascending=False)
```
But the following does not
```python
data.sort_index(level=['a'], ascending=[False])
```

PR welcome

**Comment by Dr-Irv** [comment]
Possible fix is to do 2 things:

1. In `indexes/base.py` add a check on the type of `ascending`, and if a list and length 1, convert to a `True`/`False` value. 
2. If a list and length greater than 1, raise an Exception

**Comment by heyitskevin** [comment]
take

**Comment by BeanNan** [comment]
take

**Comment by BeanNan** [comment]
take
