### ISSUE TITLE
'IntegerArray' object has no attribute 'T'

### ISSUE THREAD

**Issue by bnaul** [pandas-dev/pandas#32342]
In our case this arose via `.cumsum()`:
```
pd.Series([0, 1], dtype='int64').cumsum()
0    0
1    1
dtype: int64

pd.Series([0, 1], dtype='Int64').cumsum()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-31-2ebc3e3cf698> in <module>
----> 1 pd.Series([0, 1], dtype='Int64').cumsum()
...

~/model/.venv/lib/python3.7/site-packages/pandas/core/generic.py in na_accum_func(blk_values)
  11324                 np.putmask(result, mask, mask_b)
  11325             else:
> 11326                 result = accum_func(blk_values.T, axis)
  11327
  11328             # transpose back for ndarray, not for EA

AttributeError: 'IntegerArray' object has no attribute 'T'
```
But it's also true that just calling `.values.T` on a regular `int` array works (just a no-op), whereas on an `Int64` array it does not. Same is true for 

Any reason not to just add a no-op `.T` on the base ExtensionArray class..? cc @TomAugspurger in case you have an opinion 🙂

**Comment by TomAugspurger** [comment]
In the past we've been hesitant to add useless methods to EAs simply because ndarrays have them. I'm not sure about adding it here.

**Comment by bnaul** [comment]
Makes sense; surely `.cumsum()` is not useless though 🙂. Would the right approach then be to have a separate implementation of that...?

**Comment by jorisvandenbossche** [comment]
`cumsum` is indeed useful, but should be implemented specifically for EAs probably, without requiring `T`. 
There is an open PR related to this (https://github.com/pandas-dev/pandas/pull/28509), but didn't check the status of it.

**Comment by jbrockmendel** [comment]
> In the past we've been hesitant to add useless methods to EAs simply because ndarrays have them

This statement is technically correct (the best kind of correct), but there is not at all consensus that "T" is useless.  This is just one more in a large pile of things that could be made easier.

**Comment by TomAugspurger** [comment]
As I said, it’s useless on its own for EAs. It’s potential use comes from writing code that works with both EAs and ndarrays.

**Comment by jbrockmendel** [comment]
the example from the OP works on master, could use test

**Comment by mzeitlin11** [comment]
Closing in favor of #28385
