### ISSUE TITLE
Implement Index.__array_ufunc__

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#32411]
It'd be similar to `Series.__array_ufunc__`, (extract array, apply ufunc, box in index with name) with the exception that

1. No alignment when operating between multiple indexes
2. We'd need to decide whether Index or Series defers when calling ufuncs on inputs of mixed index and series. Check what binops does.

**Comment by thirug13** [comment]
@TomAugspurger Would this be appropriate for first-time contributors? If so, I would like to work on this.

**Comment by TomAugspurger** [comment]
I'd recommend starting elsewhere.

There's plenty of pandas-specific things that need to be taken into
account, and we'll
likely want to consolidate Index.__array_ufunc__ and Series.__array_ufunc__
into a single function, which might
be tricky.

**Comment by thirug13** [comment]
Thanks for the heads up.

**Comment by jbrockmendel** [comment]
closed by #43904
