### ISSUE TITLE
EA: fillna should accept same type

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#32414]
```
cat = pd.Categorical(["A", "B", None, "A"])
ser = pd.Series(cat).fillna("B")

>>> filled = cat.fillna(ser)  # <-- works

>>> cat.fillna(filled)
TypeError: 'value' parameter must be a scalar, dict or Series, but you passed a Categorical
```

**Comment by thirug13** [comment]
@jbrockmendel Is this issue appropriate for first-time contributors?

**Comment by jbrockmendel** [comment]
> Is this issue appropriate for first-time contributors?

Probably not; it gets pretty deep into the weeds.  #32402 might be a good fit if you're comfortable with cython, otherwise i suggest searching for the Good First Issue label

**Comment by mroeschke** [comment]
I think this work on master. Could use a test

```
In [22]: cat = pd.Categorical(["A", "B", None, "A"])
    ...: ser = pd.Series(cat).fillna("B")

In [23]: >>> filled = cat.fillna(ser)

In [24]: >>> cat.fillna(filled)
Out[24]:
['A', 'B', 'B', 'A']
Categories (2, object): ['A', 'B']
```

**Comment by Bhavay192** [comment]
hey @mroeschke , Could you please tell on which cases should we really test it on?

**Comment by mroeschke** [comment]
@Bhavay192 This entire code snippet should be tested

**Comment by Bhavay192** [comment]
Hey @mroeschke , thanks for replying. Soo according to you I should take different values of numpy arrays and test it on that??

**Comment by mroeschke** [comment]
The exact code snippet above should be written as a unit test and added to the testing suite: https://pandas.pydata.org/pandas-docs/stable/development/contributing_codebase.html#writing-tests

**Comment by Bhavay192** [comment]
Hey @mroeschke, Since I'm quite new to open source and unit testing. Could you please help with in finding out what all test should I Perform on it??
I can take test of input values and what should be the expected output. Any other test that I can perform??

**Comment by Bhavay192** [comment]
Hey @mroeschke, I have written a small unit test for the above script. Now how will you review it please tell. Shall I send a PR?? Also please tell in which package shall I add my test into??

**Comment by mroeschke** [comment]
You can follow this guide to submit a PR and maintainers can help provide further guidance: https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#contributing-your-changes-to-pandas

**Comment by simonjayhawkins** [comment]
removing milestone
