### ISSUE TITLE
Rounding issue when using pd.read_excel() followed by pd.to_sql()

### ISSUE THREAD

**Issue by mralecthomas** [pandas-dev/pandas#32434]
#### Code Sample, a copy-pastable example if possible
Single column Excel(.xls) file with the following data:

Document Summary
All
Total Sales
1479.9
39002.33
11295.76

```python
import pandas as pd
import sqlalchemy

db_user = "user"
db_pass = "pass"
server = "server_name"
db = "database"
sql_engine = sqlalchemy.create_engine(
    f"mssql+pyodbc://{db_user}:{db_pass}@{server}/{db}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

# single column Excel file containing mixed string and float data types
file_path = (
    r"doc_summary.xls"
)
df = pd.read_excel(io=file_path, sheet_name=0, header=None)

# check our values once loaded into pandas dataframe
print(df[0].values)
# prints ['Document Summary' 'All' 'Total Sales' 1479.9 39002.32999999997 11295.76000000001]

table_name = "stopRounding"

# load dataframe into sql table
df.to_sql(table_name, sql_engine, if_exists="replace")
# !! this is where floating point values above are being rounded

# retrieve data from table created from dataframe
sql_val = pd.read_sql(f"SELECT * FROM {table_name}", sql_engine)

print(sql_val.values)
# prints [[0 'Document Summary']
# [1 'All']
# [2 'Total Sales']
# [3 '1479.9']
# [4 '39002.3']
# [5 '11295.8']]

```
#### Problem description

When using pandas.read_excel() to load the data into a dataframe followed by pandas.to_sql(), the float precision is being rounded up to the nearest tenth decimal place.

I read over the pandas documentation and do not see any arguments that can be passed to maintain the float precision.

I've also tried the same thing with pandas.read_csv() followed by pandas.to_sql() using the same data, and the float precision is maintained!  So the issue seems to be with read_excel() only.

#### Expected Output
Document Summary
All
Total Sales
1479.9
39002.33
11295.76
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
pandas           : 1.0.1
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 20.0.2
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.2.8
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.13
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : 1.2.8
numba            : None
</details>

**Comment by Dr-Irv** [comment]
@mralecthomas with pandas 1.1.3, I cannot replicate this part of your example:
```
print(df[0].values)
# prints ['Document Summary' 'All' 'Total Sales' 1479.9 39002.32999999997 11295.76000000001]
```
I get
```
>>> print(df[0].values)
['Document Summary' 'All' 'Total Sales' 1479.9 39002.33 11295.76]
```
Could be a platform issue (not clear which platform you are using) 

Can you try again with the latest version of pandas?

**Comment by mralecthomas** [comment]
@Dr-Irv I have updated to Pandas 1.1.3 (on Windows 10) and can confirm that I am now receiving the correct output:

```python
>>> print(df[0].values)
['Document Summary' 'All' 'Total Sales' 1479.9 39002.33 11295.76]
```
