### ISSUE TITLE
Include tests for pd.NA and pd.NaT in tests/base/test_ops.py

### ISSUE THREAD

**Issue by SaturnFromTitan** [pandas-dev/pandas#32437]
This is a follow-up from #32281, specifically on [this comment](https://github.com/pandas-dev/pandas/pull/32281/files#r387677448) from jreback.

`test_unique_null`, `test_nunique_null` and `test_value_counts_null` should be tested for `pd.NA` and `pd.NaT` as well, ideally using the `nulls_fixture` from `pandas/conftest.py`.

As discovered/discussed in the mentioned PR, they would xfail for now. It's something that should be tested and ideally fixed though.

**Comment by mroeschke** [comment]
I think we have coverage of this on other tests now so closing
