### ISSUE TITLE
TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [nan] of <class 'float'>

### ISSUE THREAD

**Issue by kzhui125** [pandas-dev/pandas#32431]
```py
import pandas as pd
import numpy as np

df = pd.Series([1, '{1,2}', 1, None])
vc = df.value_counts(dropna=False)
print(vc.loc[np.nan])
print(vc[np.nan])
```

```
TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [nan] of <class 'float'>
```

Hello, now I have trouble  getting null value count, help.

**Comment by jbrockmendel** [comment]
This works on master, what pandas version are you using?

**Comment by kzhui125** [comment]
@jbrockmendel 

1.0.1

<img width="901" alt="1" src="https://user-images.githubusercontent.com/11925432/75945525-6abc6d00-5ed5-11ea-84c1-b25dec8c470d.png">

**Comment by KOOTSTHEHOOTS** [comment]
Facing the same problem  Pandas 1.0.5. What code should I be providing?

`TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [nan] of <class 'float'>`

**Comment by jbrockmendel** [comment]
This works in 1.1.0

**Comment by simonjayhawkins** [comment]
@jbrockmendel i've labelled this as needs tests. Any idea which commit fixed this and whether additional tests are needed.

**Comment by alexhtn** [comment]
I think that commit d4293f0d232590c61d6deb517c0eea42035d1df3 fixed this issue. But I'm not sure about how I find it. I took commits from `git log --pretty=oneline` and in automated mode go from newest to oldest until code from first post started raising errors. On commit d4293f0d232590c61d6deb517c0eea42035d1df3 all works fine and on the next commit 58df0ac699a7b60ac5724da689c930e5b58134e6 starts errors.

**Comment by simonjayhawkins** [comment]
Thanks @alexhtn I think #31962 may also have contributed to fixing the issue. (commit before this `KeyError: nan` was raised)

d2064793087ccce7265829d9bb54ec6e0bbb0446 is the first fixed commit
commit d2064793087ccce7265829d9bb54ec6e0bbb0446
Author: jbrockmendel <jbrockmendel@gmail.com>
Date:   Tue Mar 3 07:27:17 2020 -0800

    REF: remove _convert_scalar_indexer (#31962)

> @jbrockmendel i've labelled this as needs tests. Any idea which commit fixed this and whether additional tests are needed.

no tests were added in #31962 and the test added in #31866 are for error checking so safe to say should add a test for the code sample in OP to close issue

> But I'm not sure about how I find it.

~/test.py
```
import numpy as np
import pandas as pd
print(pd.__version__)
s = pd.Series([1, "{1,2}", 1, None])
vc = s.value_counts(dropna=False)
print(vc)

try:
    res = vc.loc[np.nan]
    print(res)
except:
    pass
else:
    sys.exit(1)
```

and in shell
```
git bisect start HEAD v1.0.5 --term-new fixed --term-old broken
git bisect run /bin/bash -c "python setup.py build_ext -i;python ~/test.py"
```
see #35685

**Comment by wesleyboelrijk** [comment]
take

**Comment by callmekofi** [comment]
facing the same proble
<img width="1127" alt="Screenshot 2021-12-19 at 12 50 00 AM" src="https://user-images.githubusercontent.com/39478293/146649078-9ce640b4-209e-4d1f-8766-7df64dc7a9c5.png">
m

**Comment by jbrockmendel** [comment]
@callmekofi what version of pandas are you using?  for me the example in the OP currently raises KeyError, which I think is correct
