### ISSUE TITLE
BLD: Remove snappy from requirements-dev.txt

### ISSUE THREAD

**Issue by kendricng** [pandas-dev/pandas#32446]
#### Problem description

As raised in issues #32417 and #32327, `snappy` is causing issues while setting up a dev environment `requirements-dev.txt`. 

#### Proposed change
I suggest removing `snappy` from `requirements-dev.txt` to allow fewer issues when setting up the environment.

#### Acknowledgements

@WillAyd for suggesting to raise this issue.

Related Issues: #32417, #32327

**Comment by TomAugspurger** [comment]
I think we should just keep this discussion in https://github.com/pandas-dev/pandas/issues/32417
