### ISSUE TITLE
Converting a StringDtype series to an Inte64Dtype not working as expected

### ISSUE THREAD

**Issue by brent-field** [pandas-dev/pandas#32450]
I am interested in converting a StringDtype series to an Inte64Dtype. The following code produces a TypeError:

```
x = pd.Series(['1', pd.NA, '3'], dtype=pd.StringDtype())
x.astype('Int64')
...
TypeError: data type not understood
```

If I rewrite it as follows, I get a different TypeError:

```
x = pd.Series(['1', pd.NA, '3'], dtype=pd.StringDtype())
x.astype(int)
...
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NAType
```

The only way I have been able to convert from StringDtype is:

```
x = pd.Series(['1', pd.NA, '3'], dtype=pd.StringDtype())
pd.to_numeric(x, errors='coerce').convert_dtypes()
...
0       1
1    <NA>
2       3
dtype: Int64
```

This works fine, but is inelegant. I would have expect astype to be able to do the conversion directly. Is there a recommended way to convert between these types?

**Comment by ishanema1** [comment]
take

**Comment by jorisvandenbossche** [comment]
@brent-field Thanks for the report!

So there are two (user facing) issues here:

- `astype("Int64")` should work
- `pd.to_numeric` should work without needing to put `errors='coerce'` 
  (and actually, if the input is StringDtype, we should maybe directly return Int64Dtype as well, avoiding the need for a `convert_dtypes` call afterwards)

**Comment by WeiqiangZhang** [comment]
@jorisvandenbossche Hi, I was wondering if `astype("Int64")` should work.
"Int64" isn't a dtype of numpy, but "int64" is and works perfectly fine.
