### ISSUE TITLE
ENH: Feature request, date type 

### ISSUE THREAD

**Issue by zbrookle** [pandas-dev/pandas#32473]
There currently isn’t any native date dtype in pandas, which makes it impossible to integrate this type into file formats like parquet, where schema is defined

**Comment by jbrockmendel** [comment]
Period[D] behaves a lot like date.  Could that be adapted to solve the parquet issue?

**Comment by zbrookle** [comment]
That seems kind of like a work around, is there a real reason that pandas doesn’t have a date type? It’s a pretty essential and standard type for most data platforms and frameworks

**Comment by jreback** [comment]
> That seems kind of like a work around, is there a real reason that pandas doesn’t have a date type? It’s a pretty essential and standard type for most data platforms and frameworks

@zbrookle you are welcome to spend the time to develop one

normalized Timestamps are pretty easy to understand and easily act like a date type

**Comment by zbrookle** [comment]
@jreback Okay awesome I’d definitely love to work on it

**Comment by jreback** [comment]
our current setup actually would be pretty reasonable to support a dtype and extension array of type

datetime64[D] (and maybe other freqs); may also have to be named slightly different

could be backed by a nullable integer array that represent ordinala from epoch

i don’t think it’s that hard actually

**Comment by zbrookle** [comment]
@jorisvandenbossche I think the compatibility with NumPy is probably the most important since that's what the backend of pandas is. It wouldn't be too hard to have logic that converts to the appropriate pyarrow format when a dataframe writes to parquet. I think there would just have to be an error that would be raised if they tried to write out to a date that is beyond 32 bits, which I don't think will happened very frequently

**Comment by jorisvandenbossche** [comment]
> I think the compatibility with NumPy is probably the most important since that's what the backend of pandas is

Compatibility with numpy is important, but I am not fully sure the numpy being the backend is important in this case. I think many of the datetime-specific functionalities are implemented in pandas, and are not coming from numpy (although I am not very much up to date with the exact details here)

**Comment by zbrookle** [comment]
@jorisvandenbossche I'm actually very confident that the backend for at least the datetime64 object in pandas is NumPy (because a lot of my implementation of the date was based off the datetime type) and so I think the biggest priority in terms of conversion is that these two types at the very least work well and efficiently together

**Comment by jorisvandenbossche** [comment]
Yes, we *use* the numpy datime64 dtype, but that doesn't mean we use much of numpy to do datetime-related things with it (in the end, it's just an int64 array with an annotation).

**Comment by jbrockmendel** [comment]
> I think many of the datetime-specific functionalities are implemented in pandas, and are not coming from numpy (although I am not very much up to date with the exact details here)

This is correct, largely because the relevant C functions in numpy are not exposed.  If they become exposed (xref https://github.com/numpy/numpy/pull/16364) i expect we'll start using them (once our minimum np version catches up) instead of having our own mostly-copy/pasted versions.

**Comment by jbrockmendel** [comment]
> Eg the code to get "fields" from a date (like the month, of the day of the month, etc): https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslibs/fields.pyx

Those functions all assume the int64s being passed represent nanosecond unit timestamps, which wouldn't apply here.  What _would_ apply is wrapping Period[D]

**Comment by zbrookle** [comment]
I"m aware that the actual date functions and abstractions are not through NumPy, but the backing array containing the data is, and that's what will impact conversion between the different data types within pandas using the .astype method. I think the only real decision here is whether to have the DateDtype backed by an int32 array or an int64 array.
- If it's an int32 array, then when converting to another type of date, there would need to be a type conversion in addition to the conversion from datetime epoch to date epoch
- If it's an int64 array, then only the epoch conversion would be needed, but additional conversion and handling would be necessary for pyarrow
So really it's a trade off between pyarrow and numpy, so whatever you all think is most important I'll use

**Comment by jbrockmendel** [comment]
we now have pyarrow-backed date dtypes. im curious if that handles this use case

**Comment by mroeschke** [comment]
I think this is handled by the `ArrowDtype` `pa.date` type so closing
