### ISSUE TITLE
to_numeric fails with empty data and downcast="unsigned"

### ISSUE THREAD

**Issue by pspeter** [pandas-dev/pandas#32493]
#### Code Sample, a copy-pastable example if possible

```python
pd.to_numeric([], downcast="unsigned")
```
#### Problem description

The code currently calls `np.min()` on the data which fails when the data is empty. This does not happen for any other downcast.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../lib/python3.7/site-packages/pandas/core/tools/numeric.py", line 163, in to_numeric
    elif downcast == "unsigned" and np.min(values) >= 0:
  File "<__array_function__ internals>", line 6, in amin
  File "/.../lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2793, in amin
    keepdims=keepdims, initial=initial, where=where)
  File "/.../lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
```

#### Expected Output

array([], dtype=uint8)

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.3.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.0.1
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 41.2.0
Cython           : None
pytest           : 5.3.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : 0.4.0
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : 0.6.0
lxml.etree       : None
matplotlib       : 3.1.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.16.0
pytables         : None
pytest           : 5.3.5
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : 0.48.0
</details>

**Comment by TomAugspurger** [comment]
Thanks for the report. I think it's safe to include an `initial=0` in that call to `np.min` in https://github.com/pandas-dev/pandas/blob/970499d9660a4f4a1df3e1f8ce3015336ffb4d41/pandas/core/tools/numeric.py#L165-L166.

**Comment by MillanSharma** [comment]
take

**Comment by pspeter** [comment]
There's already a PR for this bug!

**Comment by pspeter** [comment]
Thanks @mikekutzma! :)
