### ISSUE TITLE
DOC indexing: Google search for 'pandas greater than' returns `pandas.DataFrame.ge` as #1, and `pandas.DataFrame.gt`/`pandas.Series.gt` aren't even found

### ISSUE THREAD

**Issue by smcinerney** [pandas-dev/pandas#32491]
#### Problem description

(I'm aware that Google SEO is not under pandas' control. However this one's quite important, and nowhere in the pandas doc does it actually tell us where/how to report SEO fails, if at all. So please tell us how and where to report things like this. Are all pandas doc pages automatically submitted to be crawled by Google?)

The indexing of pandas DataFrame/Series operators seems to have some holes:

A Google search for *'pandas greater than'* returns ['pandas.DataFrame.ge'](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.ge.html) as #1, and `pandas.DataFrame.gt`/`pandas.Series.gt` aren't even found, let alone in the top 10.

1. The #1 hit should be `pandas.DataFrame.gt`
1. `pandas.Series.gt` should also be found, #2, but they're not. Similarly #3 `pandas.Series.between`, `pandas.Series.ge` etc.

A Google search for *'pandas less than'* is slightly better:
1. #1 hit is `pandas.DataFrame.le` (pandas 1.0.1 doc)
1. #2 hit is `pandas.Series.le` (pandas 1.0.1 doc)
1. #3 hit is `pandas.Series.between` (pandas 0.23.1 doc(?), not 1.0.x)
1. The #1 and #2 hits should be `pandas.DataFrame.lt`/`pandas.Series.lt`

#### Expected Output

as above

**Comment by TomAugspurger** [comment]
> Are all pandas doc pages automatically submitted to be crawled by Google

We don't submit anything. We don't have a robots.txt to disallow crawling.

What do you suggest we do?

**Comment by smcinerney** [comment]
Was the cause due to a) selective crawling, or b) not understanding the doc page text itself, that the wrong page gets indexed as #1, and the right pages never get indexed at all? The solution depends on which is the cause. Anyone here who knows about crawling and SEO? (I know almost nothing, I can't comment).

Also, I would have expected that as long as https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html and https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html are crawled, the operators should be indexed, not necessarily #1 hits for their keywords.

**Comment by jbrockmendel** [comment]
Closing as nothing-we-can-do-about-this
