### ISSUE TITLE
DOC: `ref` issues in the contributing.rst file

### ISSUE THREAD

**Issue by kendricng** [pandas-dev/pandas#32502]
#### Problem description

Anytime I click on an internal reference link on the [Contributing.rst](https://github.com/pandas-dev/pandas/blob/master/doc/source/development/contributing.rst) file, I expect to be directed somewhere in the internal documentation that explains something about the internal link.

While it generates a `#id39` tag at the end of the link, it doesn't direct me to the page.

I suspect that this is not typical behavior. I just want to make sure this is the case before I post a PR on it.

**Comment by MomIsBestFriend** [comment]
The ```:ref foo``` is more of a Sphinx thing (I think) that is intended to work in the website, and not in github (I think so).

here's the website where this document is being presented:

https://dev.pandas.io/docs/development/contributing.html

**Comment by kendricng** [comment]
Ah, thanks for the reference. Thank you for that!
