### ISSUE TITLE
TST: Seemingly non-deterministic order of value_counts

### ISSUE THREAD

**Issue by SaturnFromTitan** [pandas-dev/pandas#32514]
We had a flaky test for `test_value_counts` in `pandas/tests/base/test_ops.py` which was related to the sort order of entries with the same count. A hotfix was introduced in #32449 and resolves the CI issue.

The underlying issue still isn't fixed/confirmed. The test assumes that in case of same counts the order of the original index/series object is preserved. This assumption breaks on CI though. Please refer to [my comment](https://github.com/pandas-dev/pandas/pull/32449#discussion_r388388353) (and the following ones) for all related details I have found so far.

It doesn't necessarily seem to be related to the narrow dtypes. It's probably just more likely that values are duplicated the narrower the dtype is.

**Comment by SaturnFromTitan** [comment]
take

**Comment by mroeschke** [comment]
Looks like this is not marked as flaky anymore so closing
