### ISSUE TITLE
DOC: Remove absolute urls from the docs

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#32529]
Looks like we've got some absolute urls (including the domain) in the docs, like https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases (see here: https://github.com/pandas-dev/pandas/blob/master/pandas/core/indexes/datetimes.py#L178 ).

Sphinx (the tool we use to build the docs) provides a way to create those automatically, with the `:ref:` directive.

See for example how to automatically generate a link [here](https://github.com/pandas-dev/pandas/blame/master/doc/source/user_guide/computation.rst#L113):
```
:ref:`caveats <computation.covariance.caveats>`
```
Which will point to the label defined [here](https://github.com/pandas-dev/pandas/blame/master/doc/source/user_guide/computation.rst#L51):
```
.. _computation.covariance.caveats:
```

To avoid having new cases in the future after fixing the existing ones, we should add a check in `ci/code_checks.sh` to validate that the pattern `pandas.pydata.org` doesn't exist in the repository (see other examples of patterns we don't want to find in `ci/code_checks.sh` that use the `invgrep` function). If there is a better patter than `pandas.pydata.org` feel free to use it.

**Comment by ArkadeepAdhikari** [comment]
take

**Comment by ArkadeepAdhikari** [comment]
Hi, this is my first issue, are there any checks/tests I should keep in mind? Thanks

**Comment by datapythonista** [comment]
Have a look at the contributing guide if you don't know how to contribute to pandas: https://pandas.pydata.org/docs/development/contributing.html

The rest should be explained in the description. You should know how to use grep to work on this.

Assign the issue to yourself again when you're ready to start working on it.

Thanks!

**Comment by jorisvandenbossche** [comment]
For docstrings, those absolute urls are on purpose, as sphinx references are not useful when looking at those docstrings in plain text (eg as help in ipython console / jupyter notebook). So for those, I would keep the absolute urls.

If there are absolute urls in the prose rst docs, for sure those can be changed to sphinx references.

**Comment by ArkadeepAdhikari** [comment]
Thanks for the clarification, I'm changing the absolute urls in the rst docs to sphinx references, and keeping the others as it is.

**Comment by ArkadeepAdhikari** [comment]
take
