### ISSUE TITLE
pdf documentation is not bookmarked

### ISSUE THREAD

**Issue by MarianD** [pandas-dev/pandas#32540]
The last PDF documentation 1.0.1. (Feb 05, 2020) has no table of contents, no bookmarks.   

I made Contents in the form of bookmarks, meanwhile up to level 2.  
The edited (bookmarked) pdf file is here: [pandas.pdf](https://github.com/pandas-dev/pandas/files/4303229/pandas.pdf).

**Comment by 752525721** [comment]
> The last PDF documentation 1.0.1. (Feb 05, 2020) has no table of contents, no bookmarks.
> 
> I made Contents in the form of bookmarks, meanwhile up to level 2.
> The edited (bookmarked) pdf file is here: [pandas.pdf](https://github.com/pandas-dev/pandas/files/4303229/pandas.pdf).

Thanks a lot, but still has no table of contents

**Comment by MarianD** [comment]
> Thanks a lot, but still has no table of contents

As I wrote, the table of contents is in my file (only) _in the form of bookmarks_.   
(Current PDF file has neither Table of Contents, nor bookmarks).

**Comment by TomAugspurger** [comment]
The pdf docs are built over in https://github.com/pandas-dev/pandas-release if you want to take a look. Not sure what's going on.

**Comment by MarianD** [comment]
@TomAugspurger

I found in https://github.com/pandas-dev/pandas-release/blob/master/Makefile this note:

```
## this had a non-zero exit, but seemed to succeed
# -----------------------------------------------------------------------------
# Docs
# -----------------------------------------------------------------------------

# this had a non-zero exit, but seemed to succeed
# Output written on pandas.pdf (2817 pages, 10099368 bytes).
  ....
  ....
```

Maybe something went wrong and the Table of Contents and bookmarks were not generated?

**Comment by TomAugspurger** [comment]
Perhaps, I'm not sure. That comment may have been from an old run.

**Comment by MarianD** [comment]
@TomAugspurger 

Irrespective of the true reason for a such result, I think that it would be a good temporary solution to replace the current documentation in https://pandas.pydata.org/pandas-docs/stable/ with my PDF file (manually bookmarked).

**Comment by TomAugspurger** [comment]
I'd prefer to get the root problem sorted out. If you aren't able to look
at the build stuff, I can take a look later today.

**Comment by MarianD** [comment]
@TomAugspurger 
Thank you.

**Comment by TomAugspurger** [comment]
I uploaded a fixed PDF. I'm having some trouble fetching it though. I think I'm hitting the issues in https://github.com/pandas-dev/pandas-website/issues/86.

**Comment by MarianD** [comment]
@TomAugspurger 
Nice from you, thanks!  

Now in this fixed PDF I see only a tiny issue — the first bookmark and the first chapter in Contents, too,  say 

>“What’s new in 1.0.1 (February 5, 2020)” 

but *there is not such a part in the book;* the target of both links is 

> “WHAT’S NEW IN 1.0.0 (JANUARY 29, 2020)”

**Comment by TomAugspurger** [comment]
That may have been an issue with the source, which was fixed in
https://github.com/pandas-dev/pandas/commit/469d5d9a8bd201fd352cc009bbf35c555ca70d56
(after 1.0.1 was tagged). It'll be fixed in the next release.
