### ISSUE TITLE
Index.insert(-1, value) should add value in the last position

### ISSUE THREAD

**Issue by mhabets** [pandas-dev/pandas#32576]
#### Problem description and Expected Output

``Index.insert(-1, value)`` should add value in the last position instead of one before the last position, shouldn't it?

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en
LOCALE           : None.None

pandas           : 1.0.1
numpy            : 1.18.1

</details>

**Comment by dvir1** [comment]
I don't think so.
Generally, in python, this
`a=[1,2,3,4]
a.insert(-1, 5)
`
results `a=[1,2,3,5,4]`

**Comment by mhabets** [comment]
Well noted, thank a lot @dvir1.
