### ISSUE TITLE
March 2020 Dev Meeting

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#32585]
The monthly dev meeting is tomorrow at 18:00 UTC. Note that your local time may be different than last month. The US had a DST transition last weekend, while Europe didn't. Our calendar is at https://pandas.pydata.org/docs/development/meeting.html#calendar

Video Call: https://meet.google.com/hav-rmax-zjx
Minutes: https://docs.google.com/document/u/1/d/1tGbTiYORHiSPgVMXawiweGJlBw5dOkVJLY-licoBmBU/edit?ouid=102771015311436394588&usp=docs_home&ths=true

Please add items you'd like to see discussed to the agenda.

**Comment by jorisvandenbossche** [comment]
I probably won't be able to make it to the meeting this time, but will try to add some comments in the notes.

**Comment by MarcoGorelli** [comment]
Trying to join to listen in but not managing, it just says "asking to join, you'll join the call when someone lets you in"

**Comment by MarcoGorelli** [comment]
> Trying to join to listen in but not managing, it just says "asking to join, you'll join the call when someone lets you in"

Got it now, but using the zoom link (https://meet.google.com/hav-rmax-zjx doesn't work for me)

**Comment by TomAugspurger** [comment]
Sorry @MarcoGorelli, I copy-pasted the wrong link for the video call.
