### ISSUE TITLE
Histogram or kde from datetime column

### ISSUE THREAD

**Issue by JulianWgs** [pandas-dev/pandas#32590]
It always annoyed me that it was not possible to generate a histogram or kernel density estimation plot from a datetime column.

Is there interest in a solution following this approach?
[Link to SO](https://stackoverflow.com/a/60617297)

```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.DataFrame({"datetime": pd.to_datetime(np.random.randint(1582800000000000000, 1583500000000000000, 100, dtype=np.int64))})
fig, ax = plt.subplots()
df["datetime"].astype(np.int64).plot.hist(ax=ax)
labels = ax.get_xticks().tolist()
labels = pd.to_datetime(labels)
ax.set_xticklabels(labels, rotation=90)
plt.show()
```

![2UUMI](https://user-images.githubusercontent.com/31596773/76345209-3563b500-6303-11ea-8f81-d6a2198e8c4f.jpg)

I didn't look into the the pandas source code yet, but if there is interest in something like this I will look into it.

I think the main issue will be finding good x tick labels, if thats a requirement.

Greetings!

**Comment by JulianWgs** [comment]
An answer would be appreciated :)

**Comment by JulianWgs** [comment]
An answer is still appreciated :)

**Comment by JulianWgs** [comment]
@jbrockmendel

**Comment by jbrockmendel** [comment]
I have no strong opinion on this.  The SO link appears to have a few viable options.

**Comment by JulianWgs** [comment]
Thanks for the response! I propose my option, since a groupby is not really a histogram like one would expect.

**Comment by jbrockmendel** [comment]
cc @datapythonista thoughts?

**Comment by datapythonista** [comment]
A datetime is a float under the hood, and we support floats, so I think it shouldn't be difficult to make this work. The approach would be similar  to the code that you showed (I think casting to float makes more sense than casting to int, but the idea is the same). Feel free to open a pull request for this.

**Comment by onshek** [comment]
Hi everyone here. I find it a litter strange: `data["datetime"].hist()` can work well for calling `hist_series()` and `hist_series()` dose not check whether the data is numerical. While `data.hist()` calls `hist_frame()` and fails at `data = data._get_numeric_data()` for `data` here has no columns any more and break down in Line415 resulting the final `ValueError`.

**Comment by AleGuarnieri** [comment]
take

**Comment by JulianWgs** [comment]
I‘d still interested in taking it, but right now Im at the end of my master thesis and have already an open PR for pandas. Id be very happy if you would give one more month :)

**Comment by charlesdong1991** [comment]
hey, @AleGuarnieri and @JulianWgs 

thanks very much for your interests in working on it, however, as you noticed, there is an open PR which solves this issue, and probably it looks pretty much close to being merged

So feel free to look around other issues! thanks!
