### ISSUE TITLE
DOCS SUGGESTION for pd.MultiIndex (Output of df.index.levels)

### ISSUE THREAD

**Issue by jhl0204** [pandas-dev/pandas#32595]
I've been wondering if it is possible to change the output of Example 2 to indicate that the index is a `FrozenList`. Currently it only indicates that it is an `Index` and I initially had trouble realizing that the index is also a `FrozenList` (and subsequently wondering why the frozen list index values weren't updating after modifying the original dataframe).  

If possible, I believe the inclusion of `FrozenList` would be helpful for users utilizing MultiIndex functionality of pandas.

Input Dataframe 
```
INPUT: df
Box       '1'                  '2'                   '3'
Latency   code latency  loc    code latency  loc    code latency  loc
0         9170.  948.    L.    8170.  328.    R.    9160.  238.    L.
1         7540   1501.   R     9170.  9028.   L.    7170.   94.    L.
```

Example 1
```
In:df.columns.levels
Out: FrozenList([['1', '2', '3'], ['event_code', 'latency', 'location']])
```

Example 2
```
In:df.columns.levels[0]
Out: Index(['1', '2', '3'], dtype='object', name='Box Number')
```

versions: 
python=3.6.8
pandas==1.0 

Note: I originally asked this question on SO [Link](https://stackoverflow.com/questions/60623606/unexpected-behavior-for-pd-dataframe-drop-when-using-with-multilevel-index-dataf#60623606): 

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.8.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.0
numpy            : 1.15.4
pytz             : 2018.7
dateutil         : 2.7.5
pip              : 20.0.2
setuptools       : 40.6.2
Cython           : 0.29
pytest           : 4.0.0
hypothesis       : None
sphinx           : 2.2.0
blosc            : None
feather          : None
xlsxwriter       : 1.1.2
lxml.etree       : 4.2.5
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10
IPython          : 7.1.1
pandas_datareader: None
bs4              : 4.6.3
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.2.5
matplotlib       : 3.0.2
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.5.9
pandas_gbq       : None
pyarrow          : 0.14.1
pytables         : None
pytest           : 4.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.2.1
sqlalchemy       : 1.2.14
tables           : 3.4.4
tabulate         : None
xarray           : 0.12.3
xlrd             : 1.1.0
xlwt             : 1.2.0
xlsxwriter       : 1.1.2
numba            : 0.40.0

</details>

**Comment by jbrockmendel** [comment]
Where is the docstring you're referring to?

**Comment by mroeschke** [comment]
Let us know if you could point us to the docstring that could use changing (I don't see our docstrings using the word `Latency` anywhere). Closing for now but happy to reopen when provided the information.
