### ISSUE TITLE
improve read_excel performance

### ISSUE THREAD

**Issue by Dookie78** [pandas-dev/pandas#32617]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

```
#### Problem description
I have a spreadsheet of 600,000 rows and the read_excel function takes around 10mins to process. 

Is there any way to improve the performance?

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by TomAugspurger** [comment]
I'm sure there are things that can be improved. I'd recommend profiling things with snakeviz and then opening issues or pull requests for specific optimizations that can be made.

But this issue is too vague to be useful right now. I'd recommend closing it unless it's edited to make concrete proposals.

**Comment by jbrockmendel** [comment]
> I have a spreadsheet of 600,000 rows and the read_excel function takes around 10mins to process.

> Is there any way to improve the performance?

Can you export the file to csv?  read_csv should be much faster.

**Comment by mroeschke** [comment]
Closing this issue as it's not well scoped right now. But happy to reopen if there are code paths that are identified and can be optimized.
