### ISSUE TITLE
df.index.is_unique inflates index memory 

### ISSUE THREAD

**Issue by meizy** [pandas-dev/pandas#32622]
calling is_unique on an Int64Index seems to inflate the index memory.

```python
l = np.arange(9)
df = pd.DataFrame({'a':l, 'b':l, 'c':l})
print('shape', df.shape)

display(df.memory_usage(deep=True, index=True))
print()

print('drop one row')
df.drop(index=[1], inplace=True)
display(df.memory_usage(deep=True, index=True))
print()

print('is_unique: ', df.index.is_unique)
display(df.memory_usage(deep=True, index=True))
print()

print('drop another row')
df.drop(index=[3], inplace=True)
display(df.memory_usage(deep=True, index=True))
print()

print('is_unique: ', df.index.is_unique)
display(df.memory_usage(deep=True, index=True))
```

output:
```
shape (9, 3)
Index    80
a        36
b        36
c        36
dtype: int64

drop one row
Index    64
a        32
b        32
c        32
dtype: int64

is_unique:  True
Index    384
a         32
b         32
c         32
dtype: int64

drop another row
Index    56
a        28
b        28
c        28
dtype: int64

is_unique:  True
Index    376
a         28
b         28
c         28
dtype: int64
```

#### Problem description

any explanation why the index size grows after the call to index.is_unique?

#### Expected Output

no change in index size is expected

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.9.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.2
pytest: None
pip: 19.1.1
setuptools: 39.1.0
Cython: None
numpy: 1.17.0
scipy: None
pyarrow: None
xarray: None
IPython: 7.7.0
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.1.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: 4.3.4
bs4: None
html5lib: None
sqlalchemy: 1.3.12
pymysql: 0.9.3
psycopg2: None
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by TomAugspurger** [comment]
Most likely the allocation of the hashtable for the indexing engine.

**Comment by meizy** [comment]
Do you mean that it's normal behavior? or that you suspect a bug in that area?

**Comment by TomAugspurger** [comment]
Normal behavior, if that's what it is.

**Comment by TomAugspurger** [comment]
Yep, that looks like what it is

```python
In [1]: import pandas as pd

In [2]: idx = pd.Index(list(range(1000)))

In [3]: idx._engine.is_mapping_populated
Out[3]: False

In [4]: idx.memory_usage(deep=True)
Out[4]: 8000

In [5]: idx.is_unique
Out[5]: True

In [6]: idx._engine.is_mapping_populated
Out[6]: True

In [7]: idx.memory_usage(deep=True)
Out[7]: 48960
```

**Comment by meizy** [comment]
so, in your example, each index entry takes on average 48 bytes (I know it's not really like that, but that's the bottom line).
Is this reasonable?
I'd expect some overhead above the 8-bytes per Int64Index entry, but isn't this too much?

thanks
