### ISSUE TITLE
Pandas 1.0.1 unable to read excels it created itself

### ISSUE THREAD

**Issue by gnudiff** [pandas-dev/pandas#32623]
After creating lots of XLSX files with pandas.Excelwriter(), the same pandas is unable to read some of them:

`writer=pd.ExcelWriter(outfile)`

Then in a different script, when processing the same files with `pd.read_excel(outfile)`

on some (but not all) files I get error:

`xlrd.biffh.XLRDError: ZIP file contents not a known type of workbook
`

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-72-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.1
numpy            : 1.17.2
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 20.0.2
setuptools       : 41.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.8.2 (dt dec pq3 ext lo64)
jinja2           : 2.10.1
IPython          : 5.5.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.0
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.10
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.1.0
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by TomAugspurger** [comment]
Can you provide a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by MarcoGorelli** [comment]
Closing for now as it's unclear how to reproduce this

> on some (but not all) files I get error

@gnudiff feel free to reopen if you can write a minimal reproducible example - perhaps inspect the files which give you an error to see what it is about that's the problem
