### ISSUE TITLE
BUG: Replace in `string` series with NA

### ISSUE THREAD

**Issue by albertotb** [pandas-dev/pandas#32621]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np

rep = {'one': '1', 'two': '2'}
a = pd.Series(['one', 'two'], dtype='string')
b = pd.Series(['one', 'two', np.nan])
c = pd.Series(['one', 'two', np.nan], dtype='string')


# A: this works
a.replace(to_replace=rep)

# B: this also works
b.replace(to_replace=rep)

# C: this throws exception
c.replace(to_replace=rep)
# TypeError: Cannot compare types 'ndarray(dtype=object)' and 'str'
```
#### Problem description

`pandas.Series.replace` cannot be used in series of type `string` that contain `<NA>`

#### Expected Output

I would expect `C` to output the same as `B` but with `string` dtype

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.4.0-112-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : es_ES.UTF-8
LOCALE           : es_ES.UTF-8

pandas           : 1.0.1
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 41.4.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
numba            : None
</details>

**Comment by jorisvandenbossche** [comment]
@albertotb Thanks for the report!

Slightly related to https://github.com/pandas-dev/pandas/issues/32075

It seems this works with scalars:

```
In [18]: c.replace('one', '1')                                                                                                                                                                                     
Out[18]: 
0       1
1     two
2    <NA>
dtype: string
```

but not with lists/dicts

**Comment by chrispe92** [comment]
Hi, can I try to pick this up?

**Comment by jorisvandenbossche** [comment]
Yes, that would be welcome!

**Comment by chrispe92** [comment]
So, here's a few things I've noticed so far:

- When the dtype of a `pd.Series` is defined as a string, then the nan values are converted to`pd.NA`. 
- When a dictionary/list is used to define the replacements (see variable `rep` in the above example) a different function is called underneath to apply those replacements. That's why the version specified by @jorisvandenbossche is working fine.
- The function used to find where to apply the replacements is using `operator.eq`. That operator fails to make the comparison between a value and pd.NA is returns a single scalar instead. And that's how the above exception is raised.

I'm now investigating what's the best way of resolving this.

**Comment by chrispe92** [comment]
I also noticed another issue, have a look at this code:
```python
import pandas as pd
import numpy as np

replacements = {'one': '1', 'two': '2'}

series_a = pd.Series(['one', 'two'], dtype='string')
for rep in replacements:
    series_a = series_a.replace(rep, replacements[rep])

series_b = pd.Series(['one', 'two'], dtype='string')
series_b = series_b.replace(to_replace=replacements)
```
It produces the following output:
`In [4]: series_a
Out[4]:
0    1
1    2
dtype: string`
`In [5]: series_b
Out[5]:
0    1
1    2
dtype: object`

Shouldn't both of them return a series with a dtype of string?

**Comment by chrispe92** [comment]
Here's an explanation of my current solution. In order to enable comparison with arrays which contain pd.NA, I make sure to replace them all with np.na instead. Specifically by doing this:
```python
# Replace all definitions of missing values (isna=True) to a numpy.nan
if is_a_array:
    a = np.where(isna(a), np.nan, a)
if is_b_array:
    b = np.where(isna(b), np.nan, b)
```
