### ISSUE TITLE
Error in py_convert_pandas_df(x)

### ISSUE THREAD

**Issue by norapap** [pandas-dev/pandas#32655]
#### Problem description
Hello!

I have a fresh Rstudio where i want to work with some data which come from python scripts. I try to use reticulate to source the following python script:

```python
# -*- coding: utf-8 -*-

import pandas as pd
import numpy as np
import functools as ft


pd.set_option('display.float_format', lambda x: '%.3f' % x)
pd.set_option('display.max_columns', 10)

def get_table(df, table_ref_no = all, col_ref_no = all, row_ref_no = all, \
              col_name = "", cols = ["Year", "Client", "Amount_thuf"], add_cols = []):
    
    sub_table = df
    
    sub_table = sub_table.reset_index().drop(columns = ["index"])
    
     # Selection
    if (cols != all):
        sub_table = sub_table[cols + add_cols]
    
    # Aggregation
    if (len(row_ref_no) > 1):
        sub_table = pd.DataFrame(sub_table.groupby(["Year", "Client"]).sum()).reset_index()
    
    # Renaming
    if (col_name != ""):
        sub_table = sub_table.rename(columns = {"Amount_thuf" : col_name})

    return(sub_table)


excel_file_path = "C:/Users/nori/Projects/data/"
excel_file_name = "Data2016-2018_final.xlsx"
excel_sheet_name = "Total"


orig_df = pd.read_excel(excel_file_path + excel_file_name, sheet_name = excel_sheet_name)
dfo = orig_df
dfo["Amount_thuf"] = pd.to_numeric(dfo["Amount_thuf"], errors = "coerce")
df = dfo

tmp5001 = get_table(df, "Stat", ["C0001"], ["R0001"], "Eredmenytartalek")
tmp5002 = get_table(df, "Stat", ["C0001"], ["R0002"], "Karingadozasi_tartalek")
tmp5003 = get_table(df, "Stat", ["C0001"], ["R0003"], "Nagykarok_tartaleka")
tmp5004 = get_table(df, "Stat", ["C0001"], ["R0004"], "Adozas_utani_eredmeny")
tmp3002 = get_table(dfo, "S05", ["C0200", "C0300"], ["R0210", "R1510"], "Brutto_MSZD_direkt")
tmp3021 = get_table(dfo, "S05", ["C0200"], ["R0220"], "Nem-elet_MSZD_aranyos_VB")

dfs500               = [tmp5001, tmp5002, tmp5003, tmp5004, tmp3002, tmp3021]
print(dfs500)

```

But when I call the following R code in Rstudio, I always got an error: 
Browse[1]> reticulate::source_python(paste0(project_folder,"data.py"))
Error in py_convert_pandas_df(x) :
SystemError: <built-in method item of numpy.ndarray object at 0x0000012709211440> returned a result with an error set

Detailed traceback:
File "C:\Users\nori\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 791, in iteritems
for k in self.columns:
Browse[1]>

Everything (pandas, numpy, python, r, rstudio) is up to date

Thanks in advance,
Nora

**Comment by TomAugspurger** [comment]
That's probably an issue on the R side, right?

**Comment by norapap** [comment]
I'm not sure, because the traceback doesn't say much, I can only see that reticulate, numpy and pandas is involved in the error, and hoped, that somebody already met with this kind of problem

**Comment by TomAugspurger** [comment]
Not to my knowledge. I'd recommend starting in reticulate (assuming that `py_convert_pandas_df` is from reticulate). You might also try narrowing your script down. It seems like the problematic method call is `ndarray.item()` from NumPy, which pandas is calling as part of DataFrame.iteritems().

**Comment by jbrockmendel** [comment]
Closing as not reproducible.  @norapap if you still have trouble we can re-open this, but there's not much we can do without a reproducible example, see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports
