### ISSUE TITLE
Please document expected behavior when default arguments are used.

### ISSUE THREAD

**Issue by steve-the-bayesian** [pandas-dev/pandas#32664]
This is a documentation request.

The docs for read_csv currently include the following:

index_col: 
int, str, sequence of int / str, or False, default None
Column(s) to use as the row labels of the DataFrame, either given as string name or column index. If a sequence of int / str is given, a MultiIndex is used.

Note: index_col=False can be used to force pandas to not use the first column as the index, e.g. when you have a malformed file with delimiters at the end of each line.

#### Problem description
The docs explain how read_csv works in every case EXCEPT the default, which is the most common.  Please document what happens when index_col=None is passed.

**Comment by TomAugspurger** [comment]
Can you submit a PR improving the documentation?

**Comment by steve-the-bayesian** [comment]
I'll give it a go.  Full disclosure: I was looking at the docs to try to
understand what Pandas does in the default case.  I'll guess, but some
editorial work on your part may be required.  :)

**Comment by steve-the-bayesian** [comment]
I tried adding the following text: but I don't know how to PR into the
pandas github repo.

Here is my suggestion:

  The default value of ``None`` instructs pandas to guess.  If the number of
  fields in the column header row is equal to the number of fields in the
body
  of the data file, then a default index is used.  If it is one larger then
the
  first field is used as an index.

Please modify as needed for correctness.
