### ISSUE TITLE
Add index=False option to_markdown() 

### ISSUE THREAD

**Issue by chrisjcameron** [pandas-dev/pandas#32667]
#### Problem description

This is a feature request to add an optional `index=False` argument to the new `to_markdown()` dataframe method. This would produce a markdown table without the initial unnamed index column.

**Comment by dsaxton** [comment]
This is actually possible by passing `showindex=False`, but could probably be better documented (it's one of the `tabulate` kwargs):

```python
In [1]: import pandas as pd       
                                                                                                                                                                                                        
In [2]: df = pd.DataFrame({"a": [1, 2, 3]})              
                                                                                                                                                                                 
In [3]: print(df.to_markdown(showindex=False))                                                                                                                                                                                            
|   a |
|----:|
|   1 |
|   2 |
|   3 |
```

**Comment by MarcoGorelli** [comment]
TBH I'm not sure it's worth documenting `tabulate`-specific kwargs, but adding an example showing the behaviour of `df.to_markdown(showindex=False)` would be nice.

@chrisjcameron are you interested in submitting a PR? If so, see the [contributing guide](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html) for how to get started

**Comment by jreback** [comment]
adding index=False here would be ok (and translating to tabulate)

PR welcome

**Comment by quangngd** [comment]
take

**Comment by quangngd** [comment]
What should the behaviour be if user set both ```showindex``` and ```index```? Which one should take the priority or should I raise an ```ValueError```

**Comment by mproszewska** [comment]
Does it make sense to add the index parameter if the showindex parameter already exists and will be used in the same way? 
I can submit PR with added examples

**Comment by chrisjcameron** [comment]
It would be more consistent with the other pandas `to_*` methods if the parameter to control including the index was called `index` rather than `showindex`.

**Comment by chrisjcameron** [comment]
> What should the behaviour be if user set both `showindex` and `index`? Which one should take the priority or should I raise an `ValueError`

I think most users will be expecting pandas-like keywords to work, so I would prioritize those. An alternative might be a warning about "When both index and showindex are set, one value will be used but which is undefined". This would at least give users a clue that these need not both be specified but gives a lot of latitude for future refinement that changes the behavior.

**Comment by franasa** [comment]
thumbs up for this enhancement to the docs. l landed here looking exactly for that https://github.com/pandas-dev/pandas/blob/3adf3340453d6704d4a2cb47058214cc697a7d29/pandas/core/frame.py#L1996-L2024
