### ISSUE TITLE
Feature request: Allow `how` and `subset` arguments for `DataFrame.isna()` and `notna()`

### ISSUE THREAD

**Issue by tsoernes** [pandas-dev/pandas#32676]
Something like this would be very useful, and would be consistent with the arguments of `DataFrame.dropna()`
```
def isna(df, how='any', subset: Collection[str] = ()) -> pd.Series:
    """
    Like DataFrame.isna(), but allows `how` and `subset` arguments
    """
    if not subset:
        subset = df.columns
    elif not (isinstance(subset, Collection) and not isinstance(subset, str)):
        subset = (subset, )
    if how == 'any':
        op = np.logical_or
    elif how == 'all':
        op = np.logical_and
    else:
        raise ValueError(f"`how={how}` not one of 'any', 'all'")
    return op.reduce([df[col].isna() for col in subset])


def notna(df, how='any', subset: Collection[str] = ()) -> pd.Series:
    """
    Like DataFrame.isna(), but allows `how` and `subset` arguments
    """
    if not subset:
        subset = df.columns
    elif not (isinstance(subset, Collection) and not isinstance(subset, str)):
        subset = (subset, )
    if how == 'any':
        op = np.logical_or
    elif how == 'all':
        op = np.logical_and
    else:
        raise ValueError(f"`how={how}` not one of 'any', 'all'")
    return op.reduce([df[col].notna() for col in subset])
```

**Comment by dsaxton** [comment]
Since `DataFrame.isna` operates element-wise I'm not sure the concept of "how" is entirely appropriate here (also axis control would have to be added if we're now thinking row or column-wise). Why not chain together `isna` along with `any` or `all`?

**Comment by WillAyd** [comment]
Thanks but for the sake of explicitness I am -1 on adding this. You should be able to do what @dsaxton suggests

**Comment by ItsmeKernel** [comment]
I think the request makes sense in this context: suppose you want to delete records from your DataFrame where a given subset of columns is null. You can do the following:
```import pandas as pd
import numpy as np
df = pd.DataFrame([[np.nan, 1, np.nan, 0,np.nan],
                   [3, np.nan, np.nan, 1, np.nan],
                   [np.nan, np.nan, 5, 5, np.nan],
                   [5, 4, np.nan, 4, np.nan],
                   [np.nan, np.nan, np.nan, np.nan, np.nan],],
                  columns=list('ABCDE'))
```


  | A | B | C | D | E
-- | -- | -- | -- | -- | --
0 | NaN | 1.0 | NaN | 0.0 | NaN
1 | 3.0 | NaN | NaN | 1.0 | NaN
2 | NaN | NaN | 5.0 | 5.0 | NaN
3 | 5.0 | 4.0 | NaN | 4.0 | NaN
4 | NaN | NaN | NaN | NaN | NaN

`df.dropna(subset=['A', 'B'], how='all')`

A | B | C | D | E
-- | -- | -- | -- | --
0 | NaN | 1.0 | NaN | 0.0 | NaN
1 | 3.0 | NaN | NaN | 1.0 | NaN
3 | 5.0 | 4.0 | NaN | 4.0 | NaN

This is fine. But, what about if I just want to check which records will be removed by this operation? Sure, you can use `isna` in conjunction with `any` or `all`. But, as far as I know, there's no easy way to do it. Currently, I'm using the following:

**To review which records will be removed:**

`df[df.loc[:,'A':'B'].isna().all(axis=1)]`

A | B | C | D | E
-- | -- | -- | -- | --
2 | NaN | NaN | 5.0 | 5.0 | NaN
4 | NaN | NaN | NaN | NaN | NaN



**To check how the resulting DataFrame will look like:**

`df[~df.loc[:,'A':'B'].isna().all(axis=1)]`


A | B | C | D | E
-- | -- | -- | -- | --
0 | NaN | 1.0 | NaN | 0.0 | NaN
1 | 3.0 | NaN | NaN | 1.0 | NaN
3 | 5.0 | 4.0 | NaN | 4.0 | NaN

**Comment by jbrockmendel** [comment]
Agreed with @dsaxton about the workaround and with @WillAyd on -1

**Comment by mroeschke** [comment]
Thanks for the suggestion, but it appears that there isn't much enthusiasm for this functionality from the other core devs. Closing.
