### ISSUE TITLE
FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.   import pandas.util.testing as tm

### ISSUE THREAD

**Issue by KillerStrike17** [pandas-dev/pandas#32675]
#### Problem description

Why am i getting this warning? i am just creating a dataframe using DataFrame function

#### Output of ``pd.show_versions()``

version is 1.0.1

**Comment by MomIsBestFriend** [comment]
@KillerStrike17 Can you please add a minimal example?

**Comment by KillerStrike17** [comment]
hey, i just checked in my code, i was using dataframe of dask array, so i guess those guys need to update their library.

**Comment by KillerStrike17** [comment]
So I am closing it, thanks for your time..

**Comment by weishuaishuai1** [comment]
Hello，I meet this problem today ，but I import seaborn.set_style instead use dataframe. I do not know how to fix it ,can i get help from you? 
my code as follow ,thank you very much!
`import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False


def sin_plot(flip=1):
    x = np.linspace(0, 14, 100)
    for i in range(1, 7):
        plt.plot(x, np.sin(x + i * 0.5) * (7 - i) * flip)


sns.set_style({"font.sans_serif": ['Microsoft YaHei', 'SimHei']})
sin_plot()

plt.show()`
