### ISSUE TITLE
Unify index and multindex (and possibly others) API

### ISSUE THREAD

**Issue by ghost** [pandas-dev/pandas#3268]
Have you ever written code that looks like this:

```
if isinstance(d.index, MultiIndex):
    results = []
    for l in d.index.levels:
       for x in baz(l):
          results.append(foo)
elif  isinstance(d.index, Index):
    for x in d.index:
       foo
```

I've had to special case the handling of index vs. multindex several times in the past.
Conceptually, I should be able to treat index as a private case of MultIndex
with nlevels =1, and supporting that in the API would make things nicer.

---

**Edit by @cpcloud:**
Tasks :
### API Unification

Method unification is relatively simple:
- [ ]  `Index.from_tuples` and `Index.from_arrays` are just `MultiIndex.from_tuples` and `MultiIndex.from_arrays` moved to classmethods of `Index`.
- [ ] `droplevel`, ` just raises on Index (right? what would it mean?): #21115
- [ ] `has_duplicates` is straightforward
- [ ] `truncate` should be equivalent to slicing
- [ ] `reorder_levels` raises if not level=0 or name of index
- [ ] `equal_levels` - straightforward
- [ ] `levshape` - (len(ind),)
- [ ] `sortorder` - None
- [ ] `get_loc_level` - I think meaningless with tuple, raises whatever if not 0 or index name
- [ ] `is_lexsorted` - doesn't need to change
- [ ] `is_lexosrted_tuple` - doesn't need to change
- [ ] `is_monotonic_*`
- [ ] `lexsort_depth` - doesn't need to be changed at all
- [ ] `searchsorted`
- [ ] `repeat`
- [ ] `levels` and `labels` property for Index - question on whether it should be sorted.
- [ ] change to `rename` behavior: `Index` will accept either string or single-element list; MI continues to handle only list

**Comment by jbrockmendel** [comment]
Some of these are pretty straightforward to implement.  If a `levels` property is added to `Index` that just returns `[self]`, then the following `MultiIndex` methods/properties are immediately valid in `Index`: `nlevels`, `levshape`, `_inferred_type_levels`, `_have_mixed_levels`, `_get_names`, `_reference_duplicate_name`, `equal_levels`.

A few others can be patched with only minor ugliness: `from_product`, `reorder_levels`, `lexsort_depth`, `swaplevel`, `is_lexsorted`.

To go much further than that requires a `labels` attribute (or per #14443 transition to `codes` to match `CategoricalIndex`).  Maybe lazily categorize Index under the hood?

**Comment by jreback** [comment]
Add in ``.levels`` to ``Index`` breaks a couple of easy-to-fix issues in pandas test suite, mainly checks like

```
if hasattr(idx, 'levels'):
    # is a MI
```

should change to
```
if idx.nlevels > 1:
    # is a MI
```

patch

```
diff --git a/pandas/core/indexes/base.py b/pandas/core/indexes/base.py
index a5949c62a..23279e3da 100644
--- a/pandas/core/indexes/base.py
+++ b/pandas/core/indexes/base.py
@@ -1108,6 +1108,10 @@ class Index(IndexOpsMixin, PandasObject):
     def nlevels(self):
         return 1
 
+    @property
+    def levels(self):
+        return [self]
+
     def _get_names(self):
         return FrozenList((self.name, ))
 
```

**Comment by jreback** [comment]
this is mostly done. should open specific issues for non compliance here.
