### ISSUE TITLE
Idea: Frame/series should support grep-like context specification

### ISSUE THREAD

**Issue by y-p** [pandas-dev/pandas#3269]
In shell grep you can do stuff like:

```
λ seq 1000 | grep -C 3 500
497
498
499
**500**
501
502
503
```

```
λ seq 1000 | grep -B 1 -A 3 500
499
**500**
501
502
503
```

I'd be glad to have something like

``` python
s.grep_index(pat_or_pred,A=1,B=3) # -> list of series/df , each of len(A+B) or C
s.grep_index(pat_or_pred,C=5)
also
s.grep_index(label_list,C=5)
```

in core.

An example use-case:
looking for point of change in a timeseries, where you want to
grab a window around a point of change:

``` python
s = some_timeseries
# pickout index label where a big change occured
cps = s[abs(s.diff()- threshold) > threshold]
# cps is a list of labels for "interest points"
list_of_s = s.grep_index(cps,C=5)

s[0]
< 5 rows from s, with the middle one being the first "intrest point" in cps >
```

the "return list of series" is really a sort of variant on groupby,
and could concievably be implemented on top of something like
#3101, after de-warting.

Would also love to have this working with #2460 (if it ever makes it in)
for the same (but slow) on plain,unindexed data columns.

**Comment by petehuang** [comment]
Hi,

This issue's last interaction was in 2013. I noticed you had paused work on the PR - are you aware of any other efforts to pick this up? Does this continue to represent a useful enhancement?

**Comment by jreback** [comment]
things like this are contemplated in pandas 2.0

**Comment by MattFaus** [comment]
I came up with this for now:

```
def find_with_context(base_idx, before=0, after=0, context=0):
    if context != 0:
        before = context
        after = context
        
    for i in range(1, before + 1):
        base_idx |= base_idx.shift(i)
        
    for i in range(1, after + 1):
        base_idx |= base_idx.shift(-i)
        
    return base_idx

df[find_with_context(df.my_column != 1.0, before=1)]
```

**Comment by robrechtdr** [comment]
Just want to give an incredible thumbs up for a grep-like functionality.

For me the most useful part of a grep-like functionality would be for a dataframe search across all columns (stringified values). This is THE most useful functionality missing from pandas that I can think off of the top of my head.

It's an unbelievable time saver to not always have to first inspect the columns and/or values and only then perform a filter specifying a column name when debugging; as this need happens very often. So it would save time on having to find the right column and also having to type the column name (when columns are spelled in certain ways, like containing spaces (which happens often), as far as I'm aware you can't use dot syntax to autocomplete. Also, an auto-complete supported debugging tool is not always immediately accessible).
