### ISSUE TITLE
PandasArray does not support slicing consistent with other array types 

### ISSUE THREAD

**Issue by maartenb** [pandas-dev/pandas#32692]
#### Code Sample

```python
>>> import pandas as pd
>>> x = pd.Series([1, 2, 3], index=pd.to_datetime(['2020-01-01', '2020-01-02', '2020-01-03']))
>>> x[:,None].ndim
>>> x.to_numpy()[:,None].ndim
>>> x.index.array[:,None].ndim
>>> x.array[:,None].ndim
```

#### Problem description

Currently PandasArray behaves differently then either the Series or or np.ndarray.
This causes a problem when passing the PandasArray to matplotlib for example.
PandasArray should implement this consistently like the other cases.

The output from above is:

<details>

```python
>>> import pandas as pd
>>> x = pd.Series([1, 2, 3], index=pd.to_datetime(['2020-01-01', '2020-01-02', '2020-01-03']))
>>> x[:,None].ndim
2
>>> x.to_numpy()[:,None].ndim
2
>>> x.index.array[:,None].ndim
2
>>> x.array[:,None].ndim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/maartenb/anaconda3/envs/Corona/lib/python3.8/site-packages/pandas/core/arrays/numpy_.py", line 240, in __getitem__
    result = type(self)(result)
  File "/Users/maartenb/anaconda3/envs/Corona/lib/python3.8/site-packages/pandas/core/arrays/numpy_.py", line 147, in __init__
    raise ValueError("PandasArray must be 1-dimensional.")
ValueError: PandasArray must be 1-dimensional.
```
</details>

#### Expected Output

<details>

```python
2
2
2
2
```

</details>

#### Output of ``pd.show_versions()``

<details>

```python

Python 3.8.1 (default, Jan  8 2020, 16:15:59) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.show_versions()

```

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.1.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.1
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.0.0.post20200309
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by MillanSharma** [comment]
take

**Comment by TomAugspurger** [comment]
This is intentional Extension arrays are 1D, so slicing with a 2D indexer is invalid.

**Comment by maartenb** [comment]
Well,  DatetimeArray, IntegerArray are ExtensionArrays too and do accept it. 

I get that from a modeling perspective it makes sense, but it breaks matplotlib and possibly other packages relying on this behavior. I guess this originated from numpy.

**Comment by jorisvandenbossche** [comment]
On Index it is being deprecated (with your example above):

```
In [9]: x.index[:,None]    
/home/joris/miniconda3/envs/dev/bin/ipython:1: DeprecationWarning: Support for multi-dimensional indexing (e.g. `index[:, None]`) on an Index is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  #!/home/joris/miniconda3/envs/dev/bin/python
Out[9]: 
array([['2020-01-01T00:00:00.000000000'],
       ['2020-01-02T00:00:00.000000000'],
       ['2020-01-03T00:00:00.000000000']], dtype='datetime64[ns]')
```

and the plan is to do the same for the other objects. Series is planned, see https://github.com/pandas-dev/pandas/issues/27837, but we might have overlooked the extension arrays, as we should probably do the same for those as well

**Comment by jbrockmendel** [comment]
This now works correctly, closing.
