### ISSUE TITLE
CI: azure pipelines are not in PRS

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#32705]
cc @pandas-dev/pandas-core

**Comment by jreback** [comment]
last run on thursday: https://dev.azure.com/pandas-dev/pandas/_build

**Comment by WillAyd** [comment]
Any chance something shows wrong with our plan on the plugin?

https://github.com/marketplace/azure-pipelines

I don't see anything for pandas on that, but maybe an access thing

**Comment by jreback** [comment]
i deselected and reselected the plugin, let's see

**Comment by jreback** [comment]
ok was able to run on master (its queued). let's see

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/pull/32697 just triggered, so let's see

**Comment by datapythonista** [comment]
I read on twitter that @seanlaw had problems with this yesterday, I guess it's an issue in Azure: https://twitter.com/seanmylaw/status/1238526293207023617

@vtbassmatt @chrispat do you know what's the problem on pipelines not starting for pull requests?

**Comment by jreback** [comment]
yeah so a manual runs seems to work, but its not triggering.

**Comment by seanlaw** [comment]
@datapythonista @jreback Not sure what you have inside of your [azure-pipelines.yml](https://github.com/TDAmeritrade/stumpy/blob/master/azure-pipelines.yml) but I ended up needing to explicitly add a PR trigger:

```
trigger:
- master

pr:
- master

``` 

Previous to yesterday, it was enough to trigger CI with only:

```
trigger:
- master
```

I just checked and my own repo and submitted a PR and it triggered properly. Hope this helps.

**Comment by datapythonista** [comment]
Thanks for the info @seanlaw, let's give it a try (we didn't have any of these options).

**Comment by datapythonista** [comment]
Yep, looks like adding these pipelines is triggered, thanks!

**Comment by seanlaw** [comment]
Glad it worked out! 

Not sure if I'm the only one who failed to read the docs but I learned from the Azure folks yesterday that you can also trigger pipeline runs by [commenting directly on PRs](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers): `/azp run`

**Comment by datapythonista** [comment]
> Not sure if I'm the only one who failed to read the docs but I also learned from the Azure folks yesterday that you can trigger pipeline runs by [commenting directly on PRs](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers): `/azp run`

That's very useful to know, thanks!
