### ISSUE TITLE
1.0.2 release is not on pypi

### ISSUE THREAD

**Issue by scarabeusiv** [pandas-dev/pandas#32717]
As per $SUBJ the pypi contains just 1.0.1 release.
In openSUSE we validate all added archives against upstream ones and because of that the https://build.opensuse.org/request/show/784545 is now not acceptable :)

Could you please push the wheels/etc on pypi?

**Comment by MarcoGorelli** [comment]
Thanks - it's on now https://pypi.org/project/pandas/
