### ISSUE TITLE
unexpected behavior in pd.to_datetime

### ISSUE THREAD

**Issue by yotamgi** [pandas-dev/pandas#32719]
#### Code Sample

```python
>>> pd.to_datetime('2016-01-01 00:00 UTC-5', utc=True)
Timestamp('2015-12-31 19:00:00+0000', tz='UTC')
```
#### Problem description

The time at UTC-x timezone region should correspond to a +x shift at UTC+00 zones. The behavior of `pd.to_datetime` in this case is wrong, since it correspond to -x shift at UTC.

As opposed to the above, the following syntax *is* working as expected:
```python
>>> pd.to_datetime('2016-01-01 00:00 -05:00', utc=True)
Timestamp('2016-01-01 05:00:00+0000', tz='UTC')
```

#### Expected Output
```python
Timestamp('2016-01-01 05:00:00+0000', tz='UTC')
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-smp-900.331.0.0
machine: x86_64
processor: 
byteorder: little
LC_ALL: en_US.UTF-8
LANG: None
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: None
pip: None
setuptools: unknown
Cython: None
numpy: 1.16.4
scipy: 1.2.1
pyarrow: 0.15.1
xarray: None
IPython: 2.0.0
sphinx: None
patsy: 0.4.1
dateutil: 2.8.1
pytz: 2019.3
blosc: None
bottleneck: None
tables: 3.5.2
numexpr: 2.6.10dev0
feather: None
matplotlib: 3.0.3
openpyxl: None
xlrd: 1.2.0
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10.3
s3fs: None
fastparquet: None
pandas_gbq: 0+unknown
pandas_datareader: None
gcsfs: None

</details>

**Comment by TomAugspurger** [comment]
cc @mroeschke.

**Comment by mroeschke** [comment]
We dispatch to dateutil for parsing this timezone format, so we're carrying over this behavior.

```
In [5]: dateutil.parser.parse('2016-01-01 00:00 UTC-5')
Out[5]: datetime.datetime(2016, 1, 1, 0, 0, tzinfo=tzoffset(None, 18000))
```

IIRC this is the correct behavior as I've seen this issue come up before, but if you believe the behavior is still incorrect, it would be an issue with dateutil

**Comment by yotamgi** [comment]
I noticed that indeed this is the expected behavior of the `dateutil` module, as written in this [bug](https://bugs.launchpad.net/dateutil/+bug/1056186). This is truly peculiar to me though, as it seems like the exact opposite of what you would expect.

Anyway, thanks for the answer.
