### ISSUE TITLE
DataFrame.plot docstring missing a few parameters

### ISSUE THREAD

**Issue by tdpetrou** [pandas-dev/pandas#32738]
Looking at the [plot accessor docstring][1], it's missing 

* `ax`
* `subplots`
* `sharex`
* `sharey`
* `secondary_y`
* `sort_columns`

Maybe others.

Also would be nice to have documentation of all parameters for all the accessor methods i.e. `df.plot.bar`.

[1]: https://github.com/pandas-dev/pandas/blob/master/pandas/plotting/_core.py#L579

**Comment by loudlemon** [comment]
take

**Comment by loudlemon** [comment]
Hi @tdpetrou 
Apart from those, just one missing parameter
 - stacked

And as for the accessor's methods parameters, seems to be well documented. Did you mean documenting parameters like _figsize_, _title_  or _legend_ in every accessor method?

**Comment by charlesdong1991** [comment]
thanks for taking this @loudlemon 

just FYI, missing `stacked` docs is mentioned in #32759 and being taken care of by #33337

**Comment by loudlemon** [comment]
@charlesdong1991 
all right, thanks!
I suppose there is no need in closing the issue in this thread?

**Comment by charlesdong1991** [comment]
yeah, still feel free to work on it! @loudlemon 
I just saw you mention `stacked` is also missing, so leave this message to avoid repeated work.

**Comment by crisza26** [comment]
Is there anything I can help with?

**Comment by charlesdong1991** [comment]
thanks @crisza26 , but it seems there is a PR about this issue already #33596 

Feel free to look around other issues!
