### ISSUE TITLE
DOC: What release version do we want in the header?

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#32748]
I think this has come up before, but which whatsnew document, if any, do we want to link from the header? The "What's New in 1.0.1" in the screenshot below.

<img width="454" alt="Screen Shot 2020-03-16 at 8 16 42 AM" src="https://user-images.githubusercontent.com/1312546/76762092-a15c7800-675e-11ea-864e-11978f436b86.png">

Choices

1. Latest release (e.g. 1.0.2)
2. Last major release (e.g. 1.0.0)
3. None

cc @jorisvandenbossche @datapythonista.

(I think my preference is for option 3, since it's not clear whether 1 or 2 is better, so put it behind an extra click via the "Release Notes" page).

**Comment by datapythonista** [comment]
As a user, I think what I'd be interested at this point (1.0.3 being the latest), is the changelog for 1.0.0 + 1.0.1 + 1.0.2 + 1.0.3. I feel if I'm visiting this page, I'm more likely to be in the previous minor (e.g. I'm moving from 1.2 to 1.3).

But that's not what I'm proposing. May be we could consider a hierarchy of changelogs now that we're using the major, but don't really know if it's a good idea or not.

For now I'd also say 3, just call that section `Release notes`, and let the user decide.

**Comment by simonjayhawkins** [comment]
> For now I'd also say 3, just call that section `Release notes`, and let the user decide.

`Release notes` is already in the header, so just remove "What's New in ..." link ?

**Comment by TomAugspurger** [comment]
Yeah, that's my option 3. You'd go to https://pandas.pydata.org/docs/whatsnew/index.html, and from there navigate to most recent, the last bugfix release (https://pandas.pydata.org/docs/whatsnew/v1.0.3.html) or perhaps "most relevant", the last major or minor release (https://pandas.pydata.org/docs/whatsnew/v1.0.0.html)

**Comment by WillAyd** [comment]
+1 to option 3 as well

**Comment by Dr-Irv** [comment]
I was about to report this issue, and found this discussion, and agree that you should remove the "What's New" link.  But maybe change "Release Notes" to "Release Notes/What's New" ?

**Comment by jorisvandenbossche** [comment]
I agree to remove the "What's new in x.x.x" as well

> But maybe change "Release Notes" to "Release Notes/What's New" ?

I think that will become a bit long (especially for a top bar), so personally would choose one of both

**Comment by jorisvandenbossche** [comment]
We could also have a more visible link on the doc home page to the "latest" (1.0.0, or 1.0.3, or a combined view) whatsnew page, if we remove it from the top bar. 
(although those links are already there on the website)
