### ISSUE TITLE
Request: Better error message for missing columns in aggregate

### ISSUE THREAD

**Issue by tsoernes** [pandas-dev/pandas#32755]
When attempting to aggregate a non-existing column, this error is raised, which is not very descriptive: `SpecificationError: nested renamer is not supported`
```
In [39]: pd.DataFrame([[1, 2]], columns=['A', 'B']).groupby('A').agg({'B': 'mean'})
Out[39]: 
   B
A   
1  2

In [40]: pd.DataFrame([[1, 2]], columns=['A', 'B']).groupby('A').agg({'B': 'mean', 'non-existing': 'mean'})
Out[40]:
...
SpecificationError: nested renamer is not supported
```

**Comment by MarcoGorelli** [comment]
Thanks @tsoernes - do you want to work on a pull request? https://pandas.pydata.org/docs/development/contributing.html

**Comment by tsoernes** [comment]
I'm sorry but I'm unable to contribute at this moment.
