### ISSUE TITLE
TypeError: searchsorted requires compatible dtype or scalar, not Series

### ISSUE THREAD

**Issue by MislavSag** [pandas-dev/pandas#32762]
#### Code Sample, a copy-pastable example if possible

```
x = ['1998-01-07 13:17:00', '1998-01-07 13:18:00', '1998-01-07 13:19:00', '1998-01-07 13:20:00',
     '1998-01-07 13:21:00', '1998-01-07 13:22:00', '1998-01-07 13:23:00', '1998-01-07 13:24:00',
     '1998-01-07 13:25:00', '1998-01-07 13:26:00']
df = pd.DataFrame(x)
df.set_index(df.iloc[:, 0], inplace=True)
df.index = pd.DatetimeIndex(df.index.values)
```
#### Problem description

I want to apply `searchsorted` function to df index:
`df.index.searchsorted(pd.Series(np.array([df.index[0], df.index.max()])))`
but it returns an error:

> TypeError: searchsorted requires compatible dtype or scalar, not Series

Why it doesn't find the nearest datetimeindex in time? I think this works with older versions of pandas.

I use the lastest version of pandas (1.0.3.)

**Comment by Baynez** [comment]
open it again, it is still appearing, or how did you solve ?
