### ISSUE TITLE
pd.to_datetime does not work.

### ISSUE THREAD

**Issue by filipporemonato** [pandas-dev/pandas#32774]
#### Code Sample, a copy-pastable example if possible

```python
data = pd.read_csv("Data_export.csv")
data.drop_duplicates(keep='first',inplace=True) # dropping duplicate rows
df_out = data.pivot(index='timeutc', columns='attributename', values='value') # produce correct columns with values
df_out = df_out.dropna()

print("BEFORE")
print(df_out.index)

df_out.index = pd.to_datetime(df_out.index)

print("AFTER")
print(df_out.index)

```
#### Problem description

I am importing a .csv file taken from the local meteorological data service.
The file contains data such as "humidity", "temperature", etc. together with a "dateutc" containing the timestamp of the data sample.

Pandas does not recognise the format immediately, so I explicitly call ```to_datetime```, but it does not seem to work.

Output of my file:
```
BEFORE
Index(['2018-06-06 15:10:00+02', '2018-06-06 15:20:00+02',
       '2018-06-06 15:30:00+02', '2018-06-06 16:20:00+02',
       '2018-06-06 16:30:00+02', '2018-06-06 17:10:00+02',
       '2018-06-06 17:20:00+02', '2018-06-06 17:30:00+02',
       '2018-06-06 17:40:00+02', '2018-06-06 17:50:00+02',
       ...
       '2019-07-21 05:50:00+02', '2019-07-21 06:00:00+02',
       '2019-07-21 06:10:00+02', '2019-07-21 06:20:00+02',
       '2019-07-21 06:30:00+02', '2019-07-21 06:40:00+02',
       '2019-07-21 06:50:00+02', '2019-07-21 07:00:00+02',
       '2019-07-21 07:10:00+02', '2019-07-21 07:20:00+02'],
      dtype='object', name='timeutc', length=52029)
```

This is type Object, as expected. But even after calling ```to_datetime``` it still remains Object:

```
AFTER
Index([2018-06-06 15:10:00+02:00, 2018-06-06 15:20:00+02:00,
       2018-06-06 15:30:00+02:00, 2018-06-06 16:20:00+02:00,
       2018-06-06 16:30:00+02:00, 2018-06-06 17:10:00+02:00,
       2018-06-06 17:20:00+02:00, 2018-06-06 17:30:00+02:00,
       2018-06-06 17:40:00+02:00, 2018-06-06 17:50:00+02:00,
       ...
       2019-07-21 05:50:00+02:00, 2019-07-21 06:00:00+02:00,
       2019-07-21 06:10:00+02:00, 2019-07-21 06:20:00+02:00,
       2019-07-21 06:30:00+02:00, 2019-07-21 06:40:00+02:00,
       2019-07-21 06:50:00+02:00, 2019-07-21 07:00:00+02:00,
       2019-07-21 07:10:00+02:00, 2019-07-21 07:20:00+02:00],
      dtype='object', name='timeutc', length=52029)
```

Calling ```print(type(data.index))``` gives
```
<class 'pandas.core.indexes.base.Index'>
```

#### Expected Output

I expected to have a DateTime index.
My code was working as intended before upgrading the Anaconda Interface. Somehow, without me realising it, upgrading the Anaconda Interface also upgraded Pandas to 1.0.1, and my code broke down in several places. I tried downgrading but I do not remember exactly which version of Pandas I was using before, when the code was working, but the above behaviour happens both with 1.0.1 and with 0.25.3.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.3
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.0.0.post20200309
Cython           : 0.29.15
pytest           : 5.3.5
hypothesis       : 5.5.4
sphinx           : 2.4.0
blosc            : None
feather          : None
xlsxwriter       : 1.2.7
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.1.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.13
tables           : 3.6.1
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.7

</details>

**Comment by mroeschke** [comment]
I believe you are encountering this, which was a documented API change https://pandas.pydata.org/docs/whatsnew/v0.24.0.html#parsing-datetime-strings-with-timezone-offsets

**Comment by filipporemonato** [comment]
Hi @mroeschke , thank you for the reply.
as it is now I unfortunately disagree with you.

My problem does not reside in timezones being converted to UTC or not.
In the page you link, as you can see after each use of ```to_datetime``` the type is correctly changed to ```dtype='datetime64```. In my code above, the code remains ```object```.

I hope this clarifies the question, even though I never mentioned a problem with timezones offset before.

I do not think this issue should be closed, unless more explanation is given.

**Comment by mroeschke** [comment]
In the link above, there is a mention that:

> Parsing datetime strings with different UTC offsets will now create an Index of datetime.datetime objects with different UTC offsets

```
In [59]: idx = pd.to_datetime(["2015-11-18 15:30:00+05:30",
   ....:                       "2015-11-18 16:30:00+06:30"])
   ....: 

In [60]: idx
Out[60]: Index([2015-11-18 15:30:00+05:30, 2015-11-18 16:30:00+06:30], dtype='object')

In [61]: idx[0]
Out[61]: datetime.datetime(2015, 11, 18, 15, 30, tzinfo=tzoffset(None, 19800))

In [62]: idx[1]
Out[62]: datetime.datetime(2015, 11, 18, 16, 30, tzinfo=tzoffset(None, 23400))
```

And since your dates range from 2018-2019 with utc offsets (`+02` as visible), I am assuming your date range may have crossed DST where the UTC offsets have changed (some dates may also have (`+1` or `+3`).

Nonetheless, if you could provide a more minimal reproducible example, it would help with investigation: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by filipporemonato** [comment]
@mroeschke Thank you very much, that clarifies much more. I missed that explanation on my read-through. Then I agree with you.
Unfortunatley I have tried making a functioning mwe but the dataset is very large and I could not share it easily, and of course without understanding what the problem was it was hard to create something manually. Thank you for your help.
