### ISSUE TITLE
Request: Changing default na_action of Series.map to 'ignore'

### ISSUE THREAD

**Issue by tsoernes** [pandas-dev/pandas#32788]
Looking at a pretty big Pandas codebase, through a couple of hundred of uses of `Series.map`, I'm unable to find a single usage where the `na_action` argument is left to its default value of `None`.

How often do people really call the mapping function or dictionary with a bunch of NaNs, instead of just using `fillna`?

I propose changing the default value of `na_action` to `'ignore'`.

**Comment by Dr-Irv** [comment]
We're unlikely to change the default argument - it would be a code breaking change for existing users.
