### ISSUE TITLE
DISC: use of typing.cast

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#32785]
placeholder to address https://github.com/pandas-dev/pandas/pull/32730#discussion_r393485655

**Comment by simonjayhawkins** [comment]
@jorisvandenbossche @WillAyd @jbrockmendel to avoid having similar conversations in separate PRs, we can xref back to this issue.

**Comment by jbrockmendel** [comment]
Is this actionable/closeable?  I think I've seen you use typing.cast, and I'm pretty happy deferring to you on typing-related issues.

**Comment by simonjayhawkins** [comment]
We have has a few regressions caused by using asserts. This is a double edge sword, since we at least identify where our assumptions on types are incorrect.

This was a placeholder for discussion, to avoid the discussion in separate PRs.

but OK with closing for now.
