### ISSUE TITLE
Aggregation does not preserve dtype when function passed in dictionary

### ISSUE THREAD

**Issue by tsoernes** [pandas-dev/pandas#32793]
#### Code Sample, a copy-pastable example if possible

```python
In [92]: df_ = pd.DataFrame([[0, 1], [0, np.nan]]).convert_dtypes()

In [93]: df_
Out[93]: 
   0     1
0  0     1
1  0  <NA>

In [108]: df_.groupby(0).agg('last')
Out[111]: 
   1
0   
0  1

In [112]: df_.groupby(0).agg({1:'last'})
Out[115]: 
     1
0     
0  1.0


In [116]: df_.groupby(0).agg('last').dtypes
Out[116]: 
1    Int64
dtype: object

In [117]: df_.groupby(0).agg({1:'last'}).dtypes
Out[117]: 
1    float64
dtype: object

```
#### Problem description
Aggregation does not preserve Int64 dtype when function passed in dictionary for the column.

#### Expected Output
Int64 dtype 
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.5.8-100.fc30.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : nb_NO.UTF-8
LOCALE           : nb_NO.UTF-8

pandas           : 1.0.2
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 41.6.0.post20191030
Cython           : 0.29.13
pytest           : 5.2.2
hypothesis       : None
sphinx           : 2.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.2.2
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.8.4 (dt dec pq3 ext lo64)
jinja2           : 2.10.3
IPython          : 7.9.0
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 2.2.3
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 3.0.0
pandas_gbq       : None
pyarrow          : 0.16.0
pytables         : None
pytest           : 5.2.2
pyxlsb           : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.3.10
tables           : 3.5.2
tabulate         : 0.8.5
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.2
numba            : 0.46.0

</details>

**Comment by mroeschke** [comment]
Looks to work on master now. Could use a test

```
In [1]: In [92]: df_ = pd.DataFrame([[0, 1], [0, np.nan]]).convert_dtypes()
   ...:
   ...: In [93]: df_
Out[1]:
   0     1
0  0     1
1  0  <NA>

In [2]: In [108]: df_.groupby(0).agg('last')
Out[2]:
   1
0
0  1

In [3]: In [112]: df_.groupby(0).agg({1:'last'})
Out[3]:
   1
0
0  1

In [4]: In [116]: df_.groupby(0).agg('last').dtypes
Out[4]:
1    Int64
dtype: object

In [5]: In [117]: df_.groupby(0).agg({1:'last'}).dtypes
Out[5]:
1    Int64
dtype: object
```
