### ISSUE TITLE
API: More direct way to determine which rows cause pd.to_numeric to coerce to 'NA' or raise ValueError

### ISSUE THREAD

**Issue by daviewales** [pandas-dev/pandas#32818]
#### Code Sample, a copy-pastable example if possible

```python
>>> series = pd.Series(['2.5', '3', np.nan, 'A'])
>>> pd.to_numeric(series)
Traceback (most recent call last):
  File "pandas/_libs/lib.pyx", line 1926, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "A"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dwales/anaconda3/lib/python3.6/site-packages/pandas/core/tools/numeric.py", line 150, in to_numeric
    values, set(), coerce_numeric=coerce_numeric
  File "pandas/_libs/lib.pyx", line 1963, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "A" at position 3
>>> pd.to_numeric(series, errors='coerce')
0    2.5
1    3.0
2    NaN
3    NaN
dtype: float64
# Index just the rows which were coerced by `to_numeric`
>>> just_coerced_na = pd.to_numeric(series.dropna(), errors='coerce')
>>> just_coerced_na
0    2.5
1    3.0
3    NaN
dtype: float64
>>> series.loc[just_coerced_na[just_coerced_na.isna()].index]
3    A
dtype: object

# Alternative way to mask just the rows coerced by `to_numeric`
>>> overall_coerced = pd.to_numeric(series, errors='coerce')
>>> numeric_coerced = pd.to_numeric(series.dropna(), errors='coerce')
>>> mask = overall_coerced.isna() & numeric_coerced.isna()
>>> series[mask]
3    A
dtype: object
```
#### Problem description

As shown in the code above, it is possible to create an index mask to determine which rows of an original series cause `to_numeric` coerce to `NA` or raise `ValueError`. However, the creation of this mask is not immediately obvious, and requires first performing `pd.to_numeric(series, errors='coerce')` on the `dropna` subset of the original data, then subsetting this subset with `isna`, then using the `index` of this second subset to mask the original series.

One might imagine that `series.str.isnumeric()` might reveal which values were or were not numeric, but in fact none of the standard Python string functions use the same definition of 'numeric' as the `pd.to_numeric` function.

A function called something like `pd.is_numeric()` which returns a nullable boolean mask would make this much easier. For example, see the following:

#### Expected Output

```python
>>> series = pd.Series(['2.5', '3', np.nan, 'A'])
>>> series
0    2.5
1      3
2    NaN
3      A
dtype: object
>>> series.is_numeric()
0     True
1     True
2     <NA>
3    False
dtype: boolean
>>> series.loc[series.is_numeric()]
0    2.5
1      3
dtype: object
>>> series.loc[~series.is_numeric()]
3    A
dtype: object
```

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.8.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 17.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_AU.UTF-8
LOCALE           : en_AU.UTF-8

pandas           : 1.0.2
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.0.0.post20200309
Cython           : 0.29.15
pytest           : 5.4.1
hypothesis       : 5.5.4
sphinx           : 2.4.0
blosc            : None
feather          : None
xlsxwriter       : 1.2.8
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.1.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : 0.15.1
pytables         : None
pytest           : 5.4.1
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.15
tables           : 3.6.1
tabulate         : 0.8.3
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.2.0
xlsxwriter       : 1.2.8
numba            : 0.48.0

</details>

**Comment by dsaxton** [comment]
I won't speak for the maintainers, but I know there's a general reluctance to add to the already very large `pandas` API, especially if it's possible to do something using existing features / regular Python.

A possible workaround here might be to use a custom function that tests whether `pd.to_numeric` will work:

```python
import numpy as np
import pandas as pd

def is_pd_numeric(x):
    try:
        pd.to_numeric(x, errors="raise")
        return True
    except:
        return False

s = pd.Series(["1", "2.5", "infinity", "A", np.nan])
s.map(is_pd_numeric)
# 0     True
# 1     True
# 2     True
# 3    False
# 4     True
# dtype: bool
```

**Comment by daviewales** [comment]
I understand the reluctance. The API is indeed very large.

I've defined the following function:

```python
def is_numeric(series: pd.Series) -> pd.Series:
    series_coerced = pd.to_numeric(series, errors='coerce')
    numeric_coerced = pd.to_numeric(series.dropna(), errors='coerce')
    return ~(series_coerced.isna() & numeric_coerced.isna())
```

For a real-world series (≈37000 rows, ≈3000 rows which are not NA), I get the following results from `%timeit`:

```python
In [20]: %timeit s.map(is_pd_numeric)
174 ms ± 5.25 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [21]: %timeit is_numeric(s)
33.8 ms ± 2.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by mroeschke** [comment]
Thanks for the suggestion but I think both proposed helper functions are adequate, and I'd be -1 on adding another method to specifically check for numeric values (would also open the can of worms to validate other data types).

Since there hasn't be much other traction on this issue since proposed going to close. Happy to reopen if there's renewed interest from the core team and community
