### ISSUE TITLE
DOC: CI failure due to fsspec deprecation warning

### ISSUE THREAD

**Issue by MomIsBestFriend** [pandas-dev/pandas#32832]
There is CI failure in the ```Web/Docs```, under ```check ipython directive errors``` on github actions, noticed on #32831 and on #32830 

The error that is being shown:

```
Run ! grep -B1 "^<<<-------------------------------------------------------------------------$" sphinx.log
  FutureWarning,
<<<-------------------------------------------------------------------------
##[error]Process completed with exit code 1.
```

---

The root cause of the problem, is a warning that is generated during the creation of the docs.

```
>>>-------------------------------------------------------------------------
Warning in /home/runner/work/pandas/pandas/doc/source/user_guide/scale.rst at block ending on line 254
 Specify :okwarning: as an option in the ipython:: block to suppress this message
 ----------------------------------------------------------------------------
 /home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/fsspec/implementations/local.py:33: FutureWarning: The default value of auto_mkdir=True has been deprecated and will be changed to auto_mkdir=False by default in a future release.
   FutureWarning,
<<<-------------------------------------------------------------------------
```

**Comment by jorisvandenbossche** [comment]
```
 >>>-------------------------------------------------------------------------
Warning in /home/runner/work/pandas/pandas/doc/source/user_guide/scale.rst at block ending on line 254
Specify :okwarning: as an option in the ipython:: block to suppress this message
----------------------------------------------------------------------------
/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/fsspec/implementations/local.py:33: FutureWarning: The default value of auto_mkdir=True has been deprecated and will be changed to auto_mkdir=False by default in a future release.
  FutureWarning,
<<<-------------------------------------------------------------------------
```

**Comment by MomIsBestFriend** [comment]
> ```
>  >>>-------------------------------------------------------------------------
> Warning in /home/runner/work/pandas/pandas/doc/source/user_guide/scale.rst at block ending on line 254
> Specify :okwarning: as an option in the ipython:: block to suppress this message
> ----------------------------------------------------------------------------
> /home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/fsspec/implementations/local.py:33: FutureWarning: The default value of auto_mkdir=True has been deprecated and will be changed to auto_mkdir=False by default in a future release.
>   FutureWarning,
> <<<-------------------------------------------------------------------------
> ```

Thanks @jorisvandenbossche I have updated the post above :)

**Comment by jorisvandenbossche** [comment]
@TomAugspurger @martindurant is this something to report to dask?

The warning comes from this snippet in the pandas docs:

```
   import dask.dataframe as dd
   ddf = dd.read_parquet("data/timeseries/ts*.parquet", engine="pyarrow")
   ddf
```

**Comment by TomAugspurger** [comment]
This is with fsspec 0.6.3?

**Comment by TomAugspurger** [comment]
https://github.com/dask/dask/issues/6028 is the same apparently.
