### ISSUE TITLE
Feature request: Allow regex flags for `str.split`

### ISSUE THREAD

**Issue by tsoernes** [pandas-dev/pandas#32835]
Most string functions allow `case` and `flags` for matching; `str.split` does not.

**Comment by davidwales** [comment]
To add to this, I think the API should be updated to more closely align with [`str.replace`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.replace.html?highlight=str%20replace#pandas.Series.str.replace).
The current logic for determining whether the split pattern is a string or a regex is not clear from the docs (#25549), and does not match Python's built-in `str.split`. [Looking at the code](https://github.com/pandas-dev/pandas/blob/v1.0.3/pandas/core/strings.py#L1479-L1496), the current (undocumented) logic is:

- If the pattern is None, or has length 1, it's a string split.
- Else it's a regex split.

However, the Python built-in `str.split` function accepts string patterns with length greater than 1, and doesn't accept regex patterns at all. Updating the function to include a `regex=True/False` argument would make this explicit, and allow string splits on delimiters with length greater than 1.

**Comment by stacymiller** [comment]
A side note: as currently Pandas str.split accepts compiled regexes, all flags can be passed to `re.compile()`:

Without flags:
```
>>> pd.Series(['first line\nsecond line', 'third line']).str.split(
...     re.compile('$'), regex=True, expand=True
... )
                         0 1
0  first line\nsecond line  
1               third line  
```

With flags:
```
>>> pd.Series(['first line\nsecond line', 'third line']).str.split(
...     re.compile('$', flags=re.MULTILINE), regex=True, expand=True
... )
            0              1     2
0  first line  \nsecond line      
1  third line                 None
```
