### ISSUE TITLE
TST: Improve searchsorted test coverage

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#32845]
As show by https://github.com/pandas-dev/pandas/issues/32762 `searchsorted` is lacking tests in some cases (e.g., we don't seem to have any here https://github.com/pandas-dev/pandas/tree/master/pandas/tests/indexes/interval or here https://github.com/pandas-dev/pandas/tree/master/pandas/tests/indexes/categorical), so it would be good to add these.

**Comment by mroeschke** [comment]
I see `test_searchsorted_different_argument_classes` and `test_searchsorted_invalid_argument` in `tests/index/interval` and none in `tests/index/categorical`

**Comment by mroeschke** [comment]
I think the coverage of this has been improved since the issue was created so closing
