### ISSUE TITLE
Unexpected behavior when inverting column of dtype object with boolean values

### ISSUE THREAD

**Issue by Ranfir** [pandas-dev/pandas#32851]
#### Code Sample, a copy-pastable example if possible

```python
Python 3.8.2 (default, Mar 14 2020, 03:36:42)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.__version__
'1.0.3'
>>> x = pd.DataFrame()
>>> x[0] = None
>>> x.loc[0, 0] = False
>>> x.loc[1, 0] = True
>>> x
       0
0  False
1   True
>>> ~x
    0
0  -1
1  -2
>>>
```
#### Problem description
Unexpected behavior when inverting column of dtype object with boolean values.

#### Expected Output
```
>>> ~x
       0
0  True
1   False
```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.4.0-18362-Microsoft
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.18.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.2.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
</details>

**Comment by Dr-Irv** [comment]
The issue here is that when you did `x[0] = None`, it set the dtype of the column to `object`.  In that case, the values `True` and `False` are treated as 1 and 0 respectively, not as `True` and `False`.  So the following works:
```
>>> x=pd.DataFrame()
>>> x.loc[0,0]=False
>>> x.loc[1,0]=True
>>> x.dtypes
0    object
dtype: object
>>> x[0]=x[0].astype(bool)
>>> x.dtypes
0    bool
dtype: object
>>> ~x
       0
0   True
1  False
```
