### ISSUE TITLE
importing pandas resulting an error

### ISSUE THREAD

**Issue by justlearn-spec** [pandas-dev/pandas#32862]
import pandas as pd
import dask.distributed as dd

The above code was working fine till afternoon IST and now, it has started throwing errors.
Perhaps, the version?

AttributeError: module 'pandas._libs.missing' has no attribute 'NAType'

>>> df_train = dd.read_csv(filename_train, blocksize = "60MB")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'dd' is not defined
>>> df_test = dd.read_csv(filename_test, blocksize = "60MB")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'dd' is not defined

>>> df_train = df_train.drop(columns = ['INTERVAL_ID'], axis=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'df_train' is not defined

version
pandas=1.0.2=py37h0573a6f_0

**Comment by TomAugspurger** [comment]
Is that the full traceback?

Does the same error occur if you create a new environment with just pandas?

**Comment by justlearn-spec** [comment]
I just created a new environment and I'm getting the below error.

[MLDEV:DEMDEP]:/home/demo/by/dem> conda activate daskdup
(daskdup) [MLDEV:DEMDEP]:/home/demo/by/dem> import pandas as pd
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.

**Comment by TomAugspurger** [comment]
How did you install pandas? pip or conda?

**Comment by TomAugspurger** [comment]
I'm not sure, but that sounds unrelated to pandas... @datapythonista do you know if X server would be hit by any of our clipboard init stuff?

**Comment by justlearn-spec** [comment]
I installed using 

conda create -n daskdup python
conda install -n daskdup pandas

**Comment by justlearn-spec** [comment]
I had one more environment with pandas=1.0.1=pypi_0

I reverted to old version of and the problem is fixed.
conda install -n dask pandas=0.24.0

Is this an expected behavior?

**Comment by TomAugspurger** [comment]
No, it's not expected. (but FYI, you generally shouldn't mix packages from conda and pypi if you can avoid it).

Anything you can do to debug this would be welcome.

**Comment by justlearn-spec** [comment]
There are lot of people working on the same server (256 GB RAM and 40 cores). Need to check with the team what was done. Meanwhile, I'll debug.

Thanks @TomAugspurger

**Comment by justlearn-spec** [comment]
I didn't do python after activating conda environment. That was my mistake. 

import: unable to open X server `' @ error/import.c/ImportImageCommand/369. Just FYI.

**Comment by datapythonista** [comment]
> I'm not sure, but that sounds unrelated to pandas... @datapythonista do you know if X server would be hit by any of our clipboard init stuff?

It shouldn't, and I'm quite confident it doesn't.

And from [this SO answer](https://stackoverflow.com/questions/19507096/python-error-import-unable-to-open-x-server) feels like this may be unrelated to pandas, and just being captured by the way pandas is set up in that server.

@justlearn-spec can you provide a screenshot of that pandas import, and then, after seeing the error, running `pandas.__version__` please?

**Comment by justlearn-spec** [comment]
Hi @datapythonista 
Are you looking for this?

![Pandas_Error](https://user-images.githubusercontent.com/61821667/77222029-75356280-6b75-11ea-99cc-a776262c4e7c.JPG)

**Comment by datapythonista** [comment]
Is this running in a cluster? Is it possible that you have different versions in the edge node and the workers? Or that part of the code is somehow cached?

It's very strange that this is happening when importing, but the problem seems to be that files from two different Python versions seem to be mixed.

Did you try to create a new conda environment? Or even better, a new conda environment in a new conda installation? Ideally you don't want anything installed in your base environment, that's why I think a new conda installation would be better. Guessing if the two mixed versions may be a pandas in your base conda environment, and pandas in your environment named dask.

**Comment by justlearn-spec** [comment]
Hi @datapythonista,

I forgot what I was doing when I created a new conda environment. I tried to reproduce with the steps that I followed, but I can't replicate the issue. When I post the issue next time, I'll share the complete but minimal steps. 

Thanks @datapythonista @TomAugspurger
