### ISSUE TITLE
Provide [major|religious|national] holiday offsets

### ISSUE THREAD

**Issue by fabianegli** [pandas-dev/pandas#32885]
#### Motivation

`pandas` does a wonderful job when working with time series - e.g. it is easy to find periodic patterns. There are straight forward methods to find these patterns for standard time intervals such as days, weeks, months and years.

However, it is trickier to find these patterns when they occur in other periodicities or irregular but defined intervals. Often religious holidays depend on the moon or a calendar different from the western calendar ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Usage)). Easter is such an example and already has an offset in `pandas`. It would be very practical to get offsets to other holidays as well, like [iftar](https://en.wikipedia.org/wiki/Iftar), [Chinese New Year](https://en.wikipedia.org/wiki/Chinese_New_Year), [Passover](https://en.wikipedia.org/wiki/Passover), [Krishna Janmashtami](https://en.wikipedia.org/wiki/Krishna_Janmashtami) and [Kanamara Matsuri](https://en.wikipedia.org/wiki/Kanamara_Matsuri) to find patterns relative to their timing.

**Comment by TomAugspurger** [comment]
Does https://pandas.pydata.org/docs/user_guide/timeseries.html?highlight=custom#holidays-holiday-calendars provide the necessary hooks you need to define a custom holiday?

**Comment by fabianegli** [comment]
This comes close, but it lacks the essential functionality to define holidays that occur on dates that are defined relative to the lunar cycle.

But I see that pandas basically only provides wrappers for `easter` from `dateutil`. So the question arises: Is this out of scope for pandas? Should this be propagated upstream to dateutil? Or do they already have this functionality and it would only require another wrapper?

**Comment by jreback** [comment]
this out of scope for both pandas and dateutil

i would recommend building a library that uses pandas to do this (or check if there is already one)
