### ISSUE TITLE
MultiIndex has problem selecting columns if one of the levels is tuples instead of str or int

### ISSUE THREAD

**Issue by zachary822** [pandas-dev/pandas#32902]
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame(np.random.rand(100))
df.columns = pd.MultiIndex.from_tuples([((1,), 1)])
df.loc[:, ((1,), 1)]

# results in an empty dataframe
```
#### Problem description

If a MultiIndex has tuples in one of its levels, you can not use a nested tuple to get that column. It returns empty.

#### Expected Output

Column(s) from the original dataframe.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.3.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.18.1
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : 0.29.14
pytest           : 5.3.5
hypothesis       : None
sphinx           : 2.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.3.4
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.12.0
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.4
matplotlib       : 3.1.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.3.5
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : 1.1.8
numba            : None

</details>

**Comment by Dr-Irv** [comment]
This is an issue with `.loc`, and the tuples, but you can get the column:
```python
>>> df[((1,),1)].head()
0    0.995268
1    0.729242
2    0.468988
3    0.564780
4    0.980172
Name: ((1,), 1), dtype: float64
```

**Comment by Dr-Irv** [comment]
This output is also interesting, where the name is included in a list:
```python
>>> df.loc[:, [((1,), 1)]].head()
C:\Anaconda3\lib\site-packages\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)
       (1,)
          1
0  0.077917
1  0.451104
2  0.448620
3  0.282166
4  0.156396
>>>
```

**Comment by mroeschke** [comment]
Looks like the style of indexing has been deprecated

```
In [21]: df = pd.DataFrame(np.random.rand(100))
    ...: df.columns = pd.MultiIndex.from_tuples([((1,), 1)])
    ...: df.loc[:, ((1,), 1)]
<ipython-input-21-b283aababb59>:3: FutureWarning: The behavior of indexing on a MultiIndex with a nested sequence of labels is deprecated and will change in a future version. `series.loc[label, sequence]` will raise if any members of 'sequence' or not present in the index's second level. To retain the old behavior, use `series.index.isin(sequence, level=1)`
  df.loc[:, ((1,), 1)]
```

Therefore, there will not likely be a fix for this unless the deprecation is reverted. Closing but happy to reopen if it gets reverted.
