### ISSUE TITLE
pd.pct_change() inconsistently rasies SettingWithCopyWarning:

### ISSUE THREAD

**Issue by RandyBetancourt** [pandas-dev/pandas#32913]
When calling the get_daily_adjusted() function from the Alpha Vantage web API to building a DataFrame and calling the pd.pct_change() function on the resulting DataFrame, a SettingWithCopyWarning is raised.  

Alternatively, if a similar DataFrame is built calling the DataFrame() constructor method with a call to the pd.pct_change() function, no SettingWithCopyWarning is raised.  

```python
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from alpha_vantage.timeseries import TimeSeries
>>> import pandas as pd
>>> import datetime
>>>
>>> ts = TimeSeries(key="XXXX", output_format='pandas')
>>> df, meta_data = ts.get_daily_adjusted(symbol='TSLA', outputsize='full')
>>>
>>> df.columns = df.columns.str[3:]
>>> tesla = df[(df.index > '2019-05-01')]
>>>
>>> print(isinstance(tesla, pd.DataFrame))
True
>>>
>>> print(tesla.info())
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 224 entries, 2020-03-20 to 2019-05-02
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   open               224 non-null    float64
 1   high               224 non-null    float64
 2   low                224 non-null    float64
 3   close              224 non-null    float64
 4   adjusted close     224 non-null    float64
 5   volume             224 non-null    float64
 6   dividend amount    224 non-null    float64
 7   split coefficient  224 non-null    float64
dtypes: float64(8)
memory usage: 15.8 KB
None
>>>
>>> tesla.close = tesla.close.pct_change(periods=1)
C:\Users\randy\Anaconda3\lib\site-packages\pandas\core\generic.py:5292: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value
>>>
>>> df2 = pd.DataFrame({
...     'open': [14.97,15.1,1.5,14.82],
...     'high': [14.97,15.15,15,15.47],
...     'low': [14.97,14.86,14.16,14.62],
...     'close': [14.97,13.08,15,15.14]},
...     index=['2019-12-31', '2020-01-02', '2020-01-03','2020-01-04'])
>>>
>>> print(isinstance(df, pd.DataFrame))
True
>>>
>>> df2.close = df2.close.pct_change(periods = 1)
>>>
>>> print(df2.info())
<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 2019-12-31 to 2020-01-04
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   open    4 non-null      float64
 1   high    4 non-null      float64
 2   low     4 non-null      float64
 3   close   3 non-null      float64
dtypes: float64(4)
memory usage: 160.0+ bytes
None
```
#### Problem description

I can't determine why the method for DataFrame construction seems to influence the behavior of the pd.pct_change() method.  What is different between these two instances?  Chaining a copy() method call to the first example still raises the SettingWithCopyWarning.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.0rc0
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.2.0.post20200210
Cython           : 0.29.15
pytest           : 5.3.5
hypothesis       : 5.5.4
sphinx           : 2.4.0
blosc            : None
feather          : None
xlsxwriter       : 1.2.7
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.1.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.3.5
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.13
tables           : 3.6.1
tabulate         : 0.8.6
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.7
numba            : 0.48.0
</details>

**Comment by TomAugspurger** [comment]
It's likely not `pct_change` that's creating the warning, it's probably the assigning the variable.
 Does it go away if you copy `df2` prior to assigning?

```python
df2 = df2.copy()
df2['close'] = df2.close.pct_change(periods = 1)
```

**Comment by RandyBetancourt** [comment]
Yes, that works.  Thanks @TomAugspurger for the quick response.
