### ISSUE TITLE
DEPR: Index.is_mixed

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#32922]
We only use it in one place, and removing it there doesn't break anything.  Moreover, it behaves surprisingly:

```
>>> pd.Index(['a', np.nan, 'b']).is_mixed()
True

>>> Index([0, 'a', 1, 'b', 2, 'c']).is_mixed()
False
```

**Comment by jorisvandenbossche** [comment]
Fine with me to deprecate. People can always use `pd.api.types.infer_dtype` directly.
