### ISSUE TITLE
Proposal: Rename bool() to to_bool()

### ISSUE THREAD

**Issue by skasturi** [pandas-dev/pandas#32923]
https://github.com/pandas-dev/pandas/blob/f78b1cc46268e8cee8f5ccdacc41e667a6b92ef7/pandas/core/generic.py#L1371

This method conflicts with python's native `bool`. Wondering if it would be okay to rename this to `to_bool`. 

I can get the needed changes done, but wanted to make sure it's okay before sending out a PR.

**Comment by jorisvandenbossche** [comment]
> This method conflicts with python's native bool. 

How does it conflict? It's a method, so I don't directly see a way that it can conflict with the built-in bool function?

I never use this method, so I don't have much of an opinion on the method itself, but also wondering whether it is worth a deprecation to rename this.

**Comment by skasturi** [comment]
Given that `bool` is a keyword and a method as well in Python overloading it might get confusing IMO. That's why.

**Comment by mproszewska** [comment]
IMO `to_bool` would be more consistent with function naming in pandas

**Comment by brurosa** [comment]
Is this refactor still relevant? If it is, I would like to take it!

**Comment by mroeschke** [comment]
Given there is traction to deprecate this it is renaming is not relevant anymore so closing
