### ISSUE TITLE
Empty error message in tz_localize

### ISSUE THREAD

**Issue by quangngd** [pandas-dev/pandas#32967]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
from pandas import Timestamp
Timestamp.min.tz_localize("Asia/Tokyo")
```
The example is picked directly from 
```pandas/tests/scalar/timestamp/test_timezones.py::TestTimestampTZOperations::test_tz_localize_pushes_out_of_bounds```
#### Problem description
Error message is empty.

> yep, out of scope. but if you could raise an issue, that'll be great.

_Originally posted by @simonjayhawkins in https://github.com/pandas-dev/pandas/pull/32929_

#### Expected Output
Meaningful error message

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : bbfecaffa1887a86a801213fd3e1d6188f7d3456
python           : 3.7.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.3.0-40-generic
Version          : #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.0.dev0+943.gbbfecaffa
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.0.0.post20200311
Cython           : 0.29.15
pytest           : 5.4.1
hypothesis       : 5.6.0
sphinx           : 2.4.4
blosc            : None
feather          : None
xlsxwriter       : 1.2.8
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : 1.3.2
fastparquet      : 0.3.3
gcsfs            : None
matplotlib       : 3.2.0
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : 0.16.0
pytables         : None
pyxlsb           : 1.0.6
s3fs             : 0.4.0
scipy            : 1.4.1
sqlalchemy       : 1.3.15
tables           : 3.6.1
tabulate         : 0.8.6
xarray           : 0.15.0
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.48.0
</details>

**Comment by simonjayhawkins** [comment]
Thanks @quangngd for posting this.

**Comment by sathyz** [comment]
@quangngd  shall I work on this?

**Comment by quangngd** [comment]
> @quangngd shall I work on this?

sure, please go ahead and take it

**Comment by sumanau7** [comment]
take

**Comment by sathyz** [comment]
take

**Comment by TomAugspurger** [comment]
PR was closed as stale if anyone wants to pick this up.

**Comment by gabrielNT** [comment]
take
