### ISSUE TITLE
TST: Rename indices fixture

### ISSUE THREAD

**Issue by SaturnFromTitan** [pandas-dev/pandas#32974]
Following up on https://github.com/pandas-dev/pandas/pull/28865#discussion_r333052051 by @simonjayhawkins we should discuss if we want to rename the indices fixture.

A singular name seems more reasonable to its use cases. The most obvious contender is `index`.

Does any1 have objections?

**EDIT:** In [another comment](https://github.com/pandas-dev/pandas/pull/32963#discussion_r397373641) jreback suggested to use `index_fixture` instead to make things more obvious. I agree that it would be a better fit

**Comment by topper-123** [comment]
Fixed in #35024.
