### ISSUE TITLE
min of Index does not have required axis= keyword for np.min 

### ISSUE THREAD

**Issue by SylvainGuieu** [pandas-dev/pandas#33007]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
> from pandas import DataFrame
> import bumpy as np
> df = DataFrame( [[10,20,30]], index=[0], columns=[1,2,3])
> df.columns.min()
1
> min(df.columns)
1
> np.min( df.columns )
TypeError: min() got an unexpected keyword argument 'axis'
```

#### Problem description

The np.min (or max, ... etc)  function failed probably because the .min method of Index does not have the axis keyword 
np.min should behave like min builtin 

#### Expected Output
1 

#### Output of ``pd.show_versions()``
<details>
INSTALLED VERSIONS
------------------
commit: None

pandas: 0.23.4
pytest: 4.0.2
pip: 18.1
setuptools: 40.6.3
Cython: 0.29.2
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.8.2
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.2
openpyxl: 3.0.0
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.2
lxml: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment]
you have an older version 
try this in 1.0.3

**Comment by SylvainGuieu** [comment]
> you have an older version
> try this in 1.0.3

Yes, that it. thanks.
Closing the issue
