### ISSUE TITLE
DOC: for pandas.read_json() using orient='table' add docu about schema spec

### ISSUE THREAD

**Issue by KaiRoesner** [pandas-dev/pandas#33004]
Please provide documentation about what kind of type specifications are supported when using the `pandas.read_json()` function with `orient` = 'table'. Currently the [function documentation](https://pandas-docs.github.io/pandas-docs-travis/reference/api/pandas.read_json.html#pandas.read_json) does not even mention 'table' under "The set of possible orients is". There is only a small example in the "Encoding with Table Schema" section.

**Comment by TomAugspurger** [comment]
What's a type specification?

**Comment by KaiRoesner** [comment]
At [datatofish.com](https://datatofish.com/export-pandas-dataframe-json/) there are some nice examples of how to use the various values of the `orient` parameter, and for `orient` = 'table' they have:

```json
{
  "schema": {
    "fields": [
      {
        "name": "col1",
        "type": "integer"
      },
      {
        "name": "col2",
        "type": "string"
      },
      {
        "name": "col3",
        "type": "integer"
      }
    ],
    "primaryKey": [
      "col1"
    ],
    "pandas_version": "0.20.0"
  },
  "data": [...]
}
```
The `pandas.read_json()` documentation should specify which values are supported for the "type" property in the table schema. From the example, I gather that "string" and "integer" are allowed but this is surely not the complete list. Also, are there any other constraints apart from the data type that can be specified here, such as min/max length for strings etc.?

When comparing this example (or the one from the `pandas.read_json()` docu) to the ones at [the "Field Descriptors" section](http://specs.frictionlessdata.io/table-schema/#field-descriptors) in the "Table Schema" documentation at "Frictionless Data Specifications" they look very similar. Which leads me to suspect that the schema specification for `orient`='table' json input uses the same format.

So, in the `pandas.read_json()` documentation I would expect more specific information about how to use the `orient`='table' input format, in particular
- a list of permissible values for the "type" property and
- a specification of any additional properties (per "type" value) that are allowed to express further constraints.

PS: I don't know docstrings and since I don't know the answers to the above questions, either, I wouldn't know what the docstring should look like.

**Comment by TomAugspurger** [comment]
I believe this is documented at https://pandas.pydata.org/docs/user_guide/io.html#table-schema. Is there anything missing?

**Comment by KaiRoesner** [comment]
That's exactly what I was looking for, thanks. A link to this page in the `pandas.read_json()` and `Dataframe.to_json()` documentation would be nice, though.
