### ISSUE TITLE
read_csv ParserError

### ISSUE THREAD

**Issue by ekomens1** [pandas-dev/pandas#33020]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
#import pandas as pd
import pandas as pd 

#Indicate file path
url = 'http://localhost:8888/edit/Dropbox/COURSES/Data%20Analysis%20Using%20Python/BookNEW.csv'

#Read data
df= pd.read_csv(url)
df.header()
```
#### Problem description
I am reading CSV file but getting ParserError
[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by mroeschke** [comment]
We would need a minimal reproducible example to help debug the issue. It's likely that the file is malformed as well: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by MarcoGorelli** [comment]
Thanks @ekomens1 for the report

Closing as there's no way to reproduce this, feel free to reopen if you have a reproducible example
