### ISSUE TITLE
Using DateTimeIndex in rolling() to define time-based windows

### ISSUE THREAD

**Issue by yohplala** [pandas-dev/pandas#33024]
Hi,
I would like to be able to provide a DateTimeIndex directly to rolling() so that the window is defined as [timestamp in provided DateTimeIndex that is immediately previous to timestamp of current row ; timestamp of current row[
Please, is that possible?

**Comment by mroeschke** [comment]
You may be able to accomplish this using the new BaseIndexer: https://pandas.pydata.org/pandas-docs/stable/user_guide/computation.html#custom-window-rolling

We would need more information about the use-case. An example with pseudo code would greatly help the discussion.

**Comment by yohplala** [comment]
@mroeschke 

Hello, thanks a lot for your answer.
I started to have a look, and the example given shows how to access current line based on an integer index.
In my case I have a DateTimeIndex. How can I access timestamp of current row (or basically index of df being processed) on which is depending start and end?
Thanks for your help!
Bests

Here is the code I would implement based on the example, but access of df.index being processed is missing.

`
import pandas as pd
from pandas.api.indexers import BaseIndexer
from random import seed
from random import randint

class CustomIndexer(BaseIndexer):

    def get_window_bounds(self, num_values, min_periods, center, closed):
        start = np.empty(num_values, dtype=np.int64)
        end = np.empty(num_values, dtype=np.int64)
        for i in range(num_values):
            #
            #                        need a function to access df being processed
            #                                              |
            #                                              v
            start = self.time_points.loc[time_points.index<Y.index.iat[i]].index[-1]
            #
            # we don't include timestamp of current row
            # but that of immediately previous row (closed = 'left')
            #
            # need a function to access df being processed
            #          |
            #          v             
            end = self.Y.index.iat[i-1]

        return start, end


# DataFrame
ts_1h = pd.date_range(start='2020-01-01 00:00+00:00', end='2020-01-02 00:00+00:00', freq='1h')
seed(1)
values = [randint(0,10) for ts in ts_index]
df = pd.DataFrame({'Values' : values}, index=ts_1h)

# Processing
ts_3h = pd.date_range(start='2020-01-01 00:00+00:00', end='2020-01-02 00:00+00:00', freq='3h')

indexer = CustomIndexer(time_points=ts_3h)
df.rolling(indexer).sum()
`

Thanks again for your help!

**Comment by mroeschke** [comment]
You can have `BaseIndexer` take in the index in the `__init__` and define other class methods that get called in `get_window_bounds`

```
class CustomIndexer(BaseIndexer):
     def __init__(self, index):
          self.index = index
          ...
```

Moreover, the Github issues tab is more suited for bugs with the pandas library and enhancement requests. We recommend going to StackOverflow for more usage questions.
