### ISSUE TITLE
Why pandas doesn't support python 3.6.1?

### ISSUE THREAD

**Issue by finswimmer** [pandas-dev/pandas#33038]
Hello,

the requirements for pandas 1 explicit says, that it needs python>=3.6.1. Why is 3.6.0 not supported?

fin swimmer

**Comment by simonjayhawkins** [comment]
see https://github.com/pandas-dev/pandas/pull/29212#issuecomment-551370118

**Comment by finswimmer** [comment]
Thanks a lot!
