### ISSUE TITLE
Comparing monthly to dayly frequencies: DateOffset or Timedelta?

### ISSUE THREAD

**Issue by yohplala** [pandas-dev/pandas#33049]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

offset_1M = pd.tseries.frequencies.to_offset('1MS')
offset_1D = pd.tseries.frequencies.to_offset('1D')

>>> offset_1M > offset_1D
Traceback (most recent call last):
  File "/.local/lib/python3.7/site-packages/pandas/tseries/offsets.py", line 2534, in f
    return op(self.delta, other.delta)
AttributeError: 'MonthBegin' object has no attribute 'delta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.local/lib/python3.7/site-packages/pandas/tseries/offsets.py", line 2538, in f
    f"Invalid comparison between {type(self).__name__} "
TypeError: Invalid comparison between Day and MonthBegin
```
#### Problem description

Hi, I would like to compare 2 frequencies, among which monthly frequency.
Two tools appear relevant for that but have each an issue:
- Timedelta that supports comparison, but not Month frequency
- DateOffset that supports Month frequency, but not comparison

Please, how should be this managed?

Thanks for your help.
Have a good day!
Bests

**Comment by TomAugspurger** [comment]
We recommend [StackOverflow with the pandas tag](https://stackoverflow.com/questions/tagged/pandas) for usage questions (I'd recommend including a bit more about the outcome you're trying to achieve).

I don't see a bug here, but let me know if I'm missing something!

**Comment by yohplala** [comment]
@TomAugspurger 
Hi Tom,
Ok I added it in StackOverflow.
Actually, I can see the question has already been raised, and the answer has been to open an issue in pandas bugtracker.
https://stackoverflow.com/questions/11679716/comparing-dateoffsets-in-pandas

I understand the why it can be difficult sometime, but when DateOffset can be compared, (ie there is no doubt which offset is bigger) it would be useful to allow it. (at lest for my need :))
But maybe I can override DateOffset class with custom __lt__ & __eq__ methods?
Would this be your advice?
Thanks again for your support,
Bests,

**Comment by TomAugspurger** [comment]
There's a note [in the docs](https://pandas.pydata.org/docs/user_guide/timeseries.html#dateoffset-objects)

> However, all DateOffset subclasses that are an hour or smaller (Hour, Minute, Second, Milli, Micro, Nano) behave like Timedelta and respect absolute time.

I don't think that orderable methods like gt and lt would be appropriate for DateOffset. Ideally you'd be able to reliably compare all instances of the DateOffset class, but there are things like MonthBegin wouldn't be well defined.

I could see an argument for offsets with a fixed `delta`, but even then I'm hesitant.

**Comment by yohplala** [comment]
Hi Tom,
Thanks for your feedback.
What I have in mind is to manage a dict separately with string aliases for Timedelta, and DateOffset.

```
# td stands for TimeDelta, do for DateOffset
time_aliases = {'1h' : {'td' : '1H'}, '1M': {'td':'30D', 'do':'1MS'}}
```
This way, if I need to compare, I can use Timedelta string representation in to_timedelta, and when I use them for what they are, frequency for Period & PeriodIndex, I can use DateOffset.
Thanks,
Bests,
