### ISSUE TITLE
Missing show_versions() in documentation

### ISSUE THREAD

**Issue by MarianD** [pandas-dev/pandas#33044]
```python
pandas.show_versions()
```
is not in pandas API Reference.

**Comment by TomAugspurger** [comment]
It's primarily used for bug reports. Is there a reason you'd like to see it in the API documentation?

We'd also need someone to write a docstring for it.

**Comment by MarianD** [comment]
@TomAugspurger 

> Is there a reason you'd like to see it in the API documentation?

For completeness. Once I need it (I knew that there is such a function) but I didn't remember its name. So I tried finding it in lists of API reference General functions and General utility functions.

> We'd also need someone to write a docstring for it.

I may do it. I need some days to find its source code and get acquainted with  common rules for docstrings in pandas, and learn the order of steps how to accomplish it in git — or do you suppose other way for doing it?

**Comment by TomAugspurger** [comment]
The source is at
https://github.com/pandas-dev/pandas/blob/e7ee418fa7a519225203fef23481c5fa35834dc3/pandas/util/_print_versions.py#L90.
Our contributing guide has a section on writing docstrings.

**Comment by MarianD** [comment]
@TomAugspurger, thanks for useful info.

**Comment by MarianD** [comment]
@TomAugspurger, I just wrote the docstring — see my pull request #33073.
