### ISSUE TITLE
A bug of CustomBusinessDay

### ISSUE THREAD

**Issue by entron** [pandas-dev/pandas#33051]
#### Code Sample, a copy-pastable example if possible

```python
from pandas.tseries.holiday import USFederalHolidayCalendar
from pandas.tseries.offsets import CustomBusinessDay

US_BD = CustomBusinessDay(calendar=USFederalHolidayCalendar())


from pandas.tseries.holiday import AbstractHolidayCalendar, Holiday, nearest_workday, \
    USMartinLutherKingJr, USPresidentsDay, GoodFriday, USMemorialDay, \
    USLaborDay, USThanksgivingDay

class USTradingCalendar(AbstractHolidayCalendar):
    rules = [
        Holiday('NewYearsDay', month=1, day=1, observance=nearest_workday),
        USMartinLutherKingJr,
        USPresidentsDay,
        GoodFriday,
        USMemorialDay,
        Holiday('USIndependenceDay', month=7, day=4, observance=nearest_workday),
        USLaborDay,
        USThanksgivingDay,
        Holiday('Christmas', month=12, day=25, observance=nearest_workday)
    ]
    
US_TD = CustomBusinessDay(calendar=USTradingCalendar())

print(pd.to_datetime("1982-12-30") + US_BD)  
print(pd.to_datetime("1982-12-30") + US_TD)
```
#### Problem description

Both give the result of 1983-01-03. 

#### Expected Output

The correct answer should be 1982-12-31 as it is Friday and not a public holiday.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 17.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.0.3
numpy            : 1.18.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.0.0.post20200309
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: 0.8.1
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.2.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by neilkg** [comment]
I'd like to look into this!

**Comment by neilkg** [comment]
@jbrockmendel I don' think this is a bug. For NewYearsDay for both USFederalHolidayCalendar() and USTradingCalendar() above, the observance=nearest_workday. So if a holiday lies on Saturday, it will be observed on Friday. Likewise if a holiday lies on Sunday, it will be observed on Monday. So in the case above, 1982-12-30 is a Thursday, so because 1983-01-01 lies on a Saturday, the correct answer is Monday 1983-01-03.

**Comment by entron** [comment]
@jbrockmendel thanks for the comment. What would be the correct way to find the next business day which also work for days such as 1982-12-30?

**Comment by jbrockmendel** [comment]
as @neilkg commented, the current behavior appears correct since USFederalHolidayCalendar uses the nearest_weekday for NewYearsDay, which in this case is Friday Dec 30.  You would need to define a custom calendar that passes `observance=None` instead of nearest_workday

**Comment by mroeschke** [comment]
Sounds like the existing behavior is correct. Going to close this issue, but happy to reopen if something need clarification
