### ISSUE TITLE
df.to_feather pandas:  Failed to open local file, error: The requested operation cannot be performed on a file with a user-mapped section open.

### ISSUE THREAD

**Issue by naveenbhupathi** [pandas-dev/pandas#33068]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
df = pd.DataFrame({'Loan':["L1","L2"], 'Gender':["male","Female"], "income":[25000.324, 43422.2754]})
df

df['income'] = df['income'].round(decimals=2)
df = df.astype(dict(zip(['Gender'], ['category'])), copy = True)
df

df.to_feather("temp")
df = pd.read_feather("temp")
df.to_feather("temp")
```
#### Problem description
I applied round function on a column and then applied object to category conversion.
I saved the final dataframe into feather file.

When i tried to read the feather file and save the feather file again, I'm getting file is open as per the error. Now able to understand, why the file is getting locked when i read the feather file. Any help on this is appreciated

Using pandas 1.0.0 and python 3.6.5v

**Comment by TomAugspurger** [comment]
@naveenbhupathi can you post the full traceback?

**Comment by naveenbhupathi** [comment]
Hi @TomAugspurger , 

This error was caused when i read feather file and again writing to feather file.

**Scenario - 1**
df.to_feather("temp")
**df = pd.read_feather("temp")**
df.to_feather("temp")

**Scenario - 2**
There is no issue If i don't read feather file and going to write file again.
df.to_feather("temp")
df.to_feather("temp")

Traceback details for **Scenario - 1** below.,

----------------------------------------------------------------------------------------------------------
OSError                Traceback (most recent call last)<ipython-input-6-44931fce06c7> in <module>
----> 1 df.to_feather("temp")

~\python\lib\site-packages\pandas\util\_decorators.py in wrapper(*args, **kwargs)
    212                 else:
    213                     kwargs[new_arg_name] = new_arg_value
--> 214             return func(*args, **kwargs)
    215 
    216         return cast(F, wrapper)

~\python\lib\site-packages\pandas\core\frame.py in to_feather(self, path)
   1992         from pandas.io.feather_format import to_feather
   1993 
-> 1994         to_feather(self, path)
   1995 
   1996     @Appender(

~\python\lib\site-packages\pandas\io\feather_format.py in to_feather(df, path)
     62         raise ValueError("feather must have string column names")
     63 
---> 64     feather.write_feather(df, path)
     65 
     66 

~\python\lib\site-packages\pyarrow\feather.py in write_feather(df, dest)
    179         Local file path
    180     """
--> 181     writer = FeatherWriter(dest)
    182     try:
    183         writer.write(df)

~\python\lib\site-packages\pyarrow\feather.py in __init__(self, dest)
     80         self.dest = dest
     81         self.writer = ext.FeatherWriter()
---> 82         self.writer.open(dest)
     83 
     84     def write(self, df):

~\python\lib\site-packages\pyarrow\feather.pxi in pyarrow.lib.FeatherWriter.open()

~\python\lib\site-packages\pyarrow\io.pxi in pyarrow.lib.get_writer()

~\python\lib\site-packages\pyarrow\io.pxi in pyarrow.lib.OSFile.__cinit__()

~\python\lib\site-packages\pyarrow\io.pxi in pyarrow.lib.OSFile._open_writable()

~\python\lib\site-packages\pyarrow\error.pxi in pyarrow.lib.pyarrow_internal_check_status()

~\python\lib\site-packages\pyarrow\error.pxi in pyarrow.lib.check_status()

**OSError: [WinError 1224] Failed to open local file 'temp'. Detail: [Windows error 1224] The requested operation cannot be performed on a file with a user-mapped section open.**

**Comment by neilkg** [comment]
take

**Comment by naveenbhupathi** [comment]
I did reset.index of the dataframe after reading feather file, which removed lock with the feather file. Now am able to write to feather file without any issues
