### ISSUE TITLE
Pandas styling is not rendered in Github

### ISSUE THREAD

**Issue by nabeel-hasan** [pandas-dev/pandas#33076]
**My pandas style for background in the local jupyter notebook looks like this** I am using version 1.0

![Screenshot from 2020-03-25 13-19-55](https://user-images.githubusercontent.com/59860027/77793524-3d0bb380-7090-11ea-9173-86002e37151f.png)

**But once i push the notebook in Github the rendering does not work it looks like this in github**

![Screenshot from 2020-03-25 13-20-40](https://user-images.githubusercontent.com/59860027/77793603-62002680-7090-11ea-9641-f36c97ed9c62.png)

Can u please solve this problem

**Comment by TomAugspurger** [comment]
Github strips CSS and javacript from their rendered notebooks as a security measure. You might try https://nbviewer.jupyter.org/ instead.

**Comment by nabeel-hasan** [comment]
Thanks for the help Tom
