### ISSUE TITLE
Accessing DataFrame with DatetimeIndex behaves unexpectedly with reverse chronological ordered data

### ISSUE THREAD

**Issue by jesse-norris** [pandas-dev/pandas#33082]
#### Problem description

When a Panda's DataFrame with a DatetimeIndex is in reverse chronological order accessing the data using the .loc method does not work unless the range is _also_ in reverse order.

#### Code Sample

```python
import pandas as pd
 
data = [
  ("2020-03-25 12:00:00", "A"),
  ("2020-03-24 18:00:00", "B"),
  ("2020-03-24 12:00:00", "C"),
  ("2020-03-24 06:00:00", "D"),
  ("2020-03-23 12:00:00", "E"),
]
 
df = pd.DataFrame(data, columns=["timestamp", "x"])
df["timestamp"] = pd.to_datetime(df["timestamp"])
df.index = df.pop("timestamp")
```

Accessing the date range 2020-03-24 through 2020-03-25 for this DataFrame results in the following:

```python
df.loc["2020-03-24":"2020-03-25"]
>>>
Empty DataFrame
Columns: [x]
Index: []
```

However, reversing the date range returns the expected output.

```python 
df.loc["2020-03-25":"2020-03-24"]
>>>
                     x
timestamp            
2020-03-25 12:00:00  A
2020-03-24 18:00:00  B
2020-03-24 12:00:00  C
2020-03-24 06:00:00  D
```

Is this really how the DatetimeIndex should function? Either should work when working with a DatetimeIndex.

This can be fixed by executing the .sort_index() method of the DataFrame. However, when working with a DatetimeIndex, I believe chronological order should be implied.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.8.0.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-88-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 5.4.1
pip: 20.0.2
setuptools: 41.2.0
Cython: None
numpy: 1.18.1
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: 2.4.4
patsy: None
dateutil: 2.8.1
pytz: 2019.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.2.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.8.2
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.11.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by jbrockmendel** [comment]
In pandas.core.indexes.datetimelike L421 there is a comment "# TODO: does this depend on being monotonic _increasing_?" that seems like it might be related

**Comment by jbrockmendel** [comment]
Looking again, I think this is correct.  We get similar behavior with a monotonic-decreasing numeric index:

```
ser = pd.Series(range(5))
ser.index = range(5)[::-1]

>>> ser.loc[2:3]
Series([], dtype: int64)
```

**Comment by jesse-norris** [comment]
That's an interesting way of looking at it. Since that how numeric indices behave, the same must have been intended for datetime indices, even if its not quite intuitive.

Thanks for looking into the source and your counter example, @jbrockmendel.
