### ISSUE TITLE
Question/Suggestion : Window or Rolling does not have a `get_window` public method 

### ISSUE THREAD

**Issue by SylvainGuieu** [pandas-dev/pandas#33095]
#### Code Sample, a copy-pastable example if possible

```python
# somewhere
rolling = df.rolling(7, win_type="bartlett")

#somewhere else 
plot( rolling._get_window( win_type=rolling.win_type) ) 
```
#### Problem description

Sometime you receive a Rolling or Window from somewhere and want, e.g. plot its shape. 
Would be convenient to have a public method or property to get the array window weight instead of  private `._get_window` method. 
could not found one.

**Comment by mroeschke** [comment]
pandas just uses `scipy.signal.get_window(win_type, window, False)` for the window weights. These weights are not really meant to be exposed since they are only calculated during the aggregation.

**Comment by jbrockmendel** [comment]
@mroeschke closable?

**Comment by mroeschke** [comment]
Thanks for the suggestion but I would recommend just using `scipy.signal.get_window` or `Rolling` and `Window` objects' `__iter__` method to get each window.
