### ISSUE TITLE
i m not able to use this .append function even after the syntax is correct

### ISSUE THREAD

**Issue by PrasannajeetBajpai** [pandas-dev/pandas#33097]
import pandas as pd
import xlsxwriter

cars = {'Brand': ['Honda Civic','Toyota Corolla','Ford Focus','Audi A8'],
        'Price': [22000,25000,27000,35000]}

df = pd.DataFrame(cars, columns = ['Brand', 'Price'])

def add():
    ans = input ("Want to add more data.?(y/n):")
    if (ans=='y'):
        car_name = input ("Enter name:")
        price = input ("Price:")
        df2 = pd.DataFrame({'Brand' : [car_name],
                            'Price' : [price]})
        df.append(df2, ignore_index = True) 
        
        add()
        
add()

df = pd.DataFrame(cars, columns = ['Brand', 'Price'])
#### Expected Output
Want to add more data.?(y/n):y

Enter name:Bugatti

Price:789456

Want to add more data.?(y/n):n
            Brand  Price
0     Honda Civic  22000
1  Toyota Corolla  25000
2      Ford Focus  27000
3         Audi A8  35000
4          Bugatti  789456

#### Output of ``pd.show_versions()``
Want to add more data.?(y/n):y

Enter name:Bugatti

Price:789456

Want to add more data.?(y/n):n
            Brand  Price
0     Honda Civic  22000
1  Toyota Corolla  25000
2      Ford Focus  27000
3         Audi A8  35000

<details>

here i m not able to use this .append function even after the syntax is correct can anyone plz help me out here i have sucessfully installed pandas also and i m running it in spyder

</details>

**Comment by phofl** [comment]
Him
append is not an inplace modification. You have to do something like 

```return df.append(df2, ignore_index = True)```

or 

``` df =  df.append(df2, ignore_index = True)```

**Comment by PrasannajeetBajpai** [comment]
For
return df.append(df2, ignore_index = True)

it does not work just like before

For
 df = df.append(df2, ignore_index = True)

UnboundLocalError: local variable 'df' referenced before assignment

**Comment by phofl** [comment]
The following works for me:

```
import pandas as pd

cars = {'Brand': ['Honda Civic','Toyota Corolla','Ford Focus','Audi A8'],
'Price': [22000,25000,27000,35000]}

df = pd.DataFrame(cars, columns = ['Brand', 'Price'])

def add():
    ans = input ("Want to add more data.?(y/n):")
    if (ans=='y'):
        car_name = input ("Enter name:")
    price = input ("Price:")
    df2 = pd.DataFrame({'Brand' : [car_name],
    'Price' : [price]})
    return df.append(df2, ignore_index = True)

df = add()
print(df)
```

Output:

```
            Brand  Price
0     Honda Civic  22000
1  Toyota Corolla  25000
2      Ford Focus  27000
3         Audi A8  35000
4              vw    100
```

**Comment by PrasannajeetBajpai** [comment]
thanks a lot man...i don't know how i missed that  and sorry for the example thing actually i don't know 
how to do things here i just came 3 hours ago here again thanks a lot man i really appreciate it.

**Comment by phofl** [comment]
Your welcome.

Could you close the issue, if everything works?
