### ISSUE TITLE
Explain how and when to use indirect fixtures

### ISSUE THREAD

**Issue by SaturnFromTitan** [pandas-dev/pandas#33128]
As mentioned in https://github.com/pandas-dev/pandas/pull/32963#issuecomment-605675606, it would be worthwhile to document this. I'm now sure if we already have consensus on that though. Would be good to make a proposal in a PR and then have a discussion on it.

**Comment by mroeschke** [comment]
Looks like there hasn't been much activity here in a while.

Additionally, I think a user could just look this up in the pytest docs: https://docs.pytest.org/en/6.2.x/example/parametrize.html#indirect-parametrization

Going to close due to inactivity, but happy to reopen if there's more interest.
