### ISSUE TITLE
.gt() add support for single column dataframes

### ISSUE THREAD

**Issue by mariolovric** [pandas-dev/pandas#33120]
It would be great if when comparing df to series like in pandas .gt() or .lt() one could compare also to single column dataframes instead of series.
Maybe also extend it to other functions?

Thanks

This works:
```
df1 = pd.DataFrame(np.array([[2,2],[1,1], [0,0]]), columns = ['a1','a2'])
df2 = pd.Series([2,2,2], name = 'b')
df1.lt(df2, axis=0)
```

This doesnt
```
df1 = pd.DataFrame(np.array([[2,2],[1,1], [0,0]]), columns = ['a1','a2'])
df2 = pd.DataFrame([2,2,2], columns = ['b'])
df1.lt(df2, axis=0)
```

**Comment by TomAugspurger** [comment]
I don't think we should do this. If you want the broadcasting / alignment semantics of a 1D object, you should provide a Series.

Generally speaking, we don't want to make the result type depend on something like the number of columns, just the input types.

**Comment by jbrockmendel** [comment]
Closing as no action.
