### ISSUE TITLE
build_table_schema references non-existent _as_json_table_type

### ISSUE THREAD

**Issue by mriswithe** [pandas-dev/pandas#33130]
#### Problem description
Documentation issue: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.io.json.build_table_schema.html
(and master branch contains this as well)

Description contains: 
```
See _as_json_table_type for conversion types. 
```
Which I cannot find anywhere else in the documentation

**Comment by TomAugspurger** [comment]
That's an internal method. We should probably remove the reference to it and link to https://pandas.pydata.org/docs/user_guide/io.html#table-schema, unless we think that it'd be useful to provide an API and we think we have a stable implementation.

For now, I'd prefer just linking to the docs.
