### ISSUE TITLE
DOC: document support for in-memory HDFStore

### ISSUE THREAD

**Issue by tgy** [pandas-dev/pandas#33166]
It seems to be currently imposible to have an in-memory HDFStore. 

Any of my attempts at using `io.BytesIO` failed.

This can be useful for applications where the bytes of the resulting HDF file need to be sent over the network.

**Comment by jreback** [comment]
we https://www.pytables.org/cookbook/inmemory_hdf5_files.html

you need to pass in the driver 

we have an open issue about adding this to the documentation where would take a pull request

**Comment by jreback** [comment]
but i think i closed that issue so can use this one

**Comment by tgy** [comment]
@jreback passing the driver is possible with pytables but is it also possible in pandas? i don't see any driver option in `pandas.io.pytables`.

**Comment by jreback** [comment]
yes, the store supports passing options, something like
```
with pd.HDFStore(...., driver=.....):
```

**Comment by tgy** [comment]
@jreback great! i will add some documentation in a PR. can you assign me to this issue so people know i'll work on it?

**Comment by jreback** [comment]
put in a comment ‘take’

**Comment by sriram2093** [comment]
Is this issue still open? I want to work on it. @jreback @tgy

**Comment by dennisbakhuis** [comment]
take

**Comment by tgy** [comment]
thanks @dennisbakhuis! let us know if you need help

**Comment by dennisbakhuis** [comment]
Do you want the ``driver`` parameter to be explicitly mentioned? As it is catched by the **kwargs and passed on to tables.open_file method, it is not really a Pandas parameter.

I currently have added to the docstring that **kwargs passes its parameters to PyTables. Maybe this is too much but I also added an example using **kwargs, passing the driver paramter to create an in-memory HDFStore.

Furthermore, I have added HDFStore class to the reference api, as it was not autogenerated and also made **kwargs more clear that it passes its parameters to PyTables.

Added in the cookbook the method of creating in-memory HDFStores, including an example.
