### ISSUE TITLE
Feature request: convert period to timedelta

### ISSUE THREAD

**Issue by yohplala** [pandas-dev/pandas#33170]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

mPI = pd.period_range(start='2020-02-01 10:00', end='2020-05-20 10:00', freq='1M')

mPI[0]
>>> Period('2020-02', 'M')

td = pd.Timedelta(mPI[0])
>>> ValueError: Value must be Timedelta, string, integer, float, timedelta or convertible, not Period

td = pd.to_timedelta(mPI[0])
>>> ValueError: Value must be Timedelta, string, integer, float, timedelta or convertible, not Period

mPI[0].to_timedelta()
>>> AttributeError: 'Period' object has no attribute 'to_timedelta'

# ok... write some more code then..
td = mPI[1].start_time - mPI[0].start_time
>>> Timedelta('29 days')
```
#### Problem description

Hi,
I would like to retrieve the duration of a period as a timedelta.
The 1st three examples are code I thought could be handled by pandas, but they are not.
The last one is an example of result I would like to retrieve.
Here, it is fine, I have the next period, so I can do the difference between the two successive periods.
If you don't have it, you are forced to create it.

Please, can pd.Period.to_timedelta() be defined in pandas?
Thanks for your help and support!
Bests,

**Comment by mroeschke** [comment]
I don't think it directly makes sense to have a `to_timedelta` on `Period/PeriodIndex` these represent an interval as a unit while `Timedelta` is a duration.

I think getting the `Timedelta` result as `period.end_time - period.start_time` is idiomatic and you can wrap this operation in your own function as well.

Thanks for the suggestion, but I don't think it's worth adding `to_timedelta` to the API.

**Comment by yohplala** [comment]
Hello Matthew,
I can understand there are certainly other priorities, and this demand is rejected.
But regarding the two reasons, I disagree with both:

- period.end_time - period.start time does not give exactly the same result. So yes, I will rely on the result that it gives and round it to a day.

- pandas documentation uses quite often the terms 'time span' to introduce period, and a span is a duration.

But I don't wish to argue here. No worries, pandas is a terrific library, thanks to have made it available and to provide support for it. I can just be picky sometime for reasons that may not be the true ones. I don't mean to offend, sorry.
Have a good evening, thanks again for your feedback, bests

**Comment by mroeschke** [comment]
Thank you for all your suggestions so far @yohplala. We really appreciate you engaging with the community and all your suggestions so far.

As pandas has a fairly large API, we are generally hesitant to add new APIs especially if the API ask can be composed from existing APIs.

'time span' is indeed not a very clear description. `Period` is a span that is anchored by 2 dates. `Timedelta` is a span that is not anchored by 2 dates. Efforts to clear up the documentation is always appreciated too!

**Comment by yohplala** [comment]
Thanks Matthew, I also appreciate your support and effort to bring answers to the huge number of requests you continuously receive and I do understand that to correctly maintain this complex library that pandas is, you need to study with care if a request really is worth it or not.
Thanks again, bests,
