### ISSUE TITLE
Setting histogram weights for multiple columns fails

### ISSUE THREAD

**Issue by mave240** [pandas-dev/pandas#33173]
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np
df = pd.DataFrame(dict(zip(['A', 'B'], np.random.randn(2, 100))))
df.plot.hist(weights=0.1*np.ones(shape=(100, 2)))  # fail
```
#### Problem description
Trying to plot a histogram of a multi-column data frame with weights fails with `ValueError: weights should have the same shape as a.` There is no error for a single column. It doesn't work with:
```python
df.plot.hist(weights=0.1*np.ones(shape=(100,)))  # fail
```
either.

#### Expected Output
A `matplotlib` figure.
![pandas_hist_weights_bug_01](https://user-images.githubusercontent.com/37543656/78025387-da493f00-7351-11ea-8b5f-a047dad14c9d.png)

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None
pandas           : 1.0.3
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.1.post20200323
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.3
numexpr          : None
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : 0.48.0

</details>

**Comment by TomAugspurger** [comment]
Thanks for the report. Can you post the full traceback, and investigate where things are going wrong?

**Comment by mave240** [comment]
> Thanks for the report. Can you post the full traceback, and investigate where things are going wrong?

File "Z:\miniconda3\envs\tf\lib\site-packages\pandas\plotting\_core.py", line 1180, in hist
    return self(kind="hist", by=by, bins=bins, **kwargs)
  File "Z:\miniconda3\envs\tf\lib\site-packages\pandas\plotting\_core.py", line 847, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
  File "Z:\miniconda3\envs\tf\lib\site-packages\pandas\plotting\_matplotlib\__init__.py", line 61, in plot
    plot_obj.generate()
  File "Z:\miniconda3\envs\tf\lib\site-packages\pandas\plotting\_matplotlib\core.py", line 260, in generate
    self._args_adjust()
  File "Z:\miniconda3\envs\tf\lib\site-packages\pandas\plotting\_matplotlib\hist.py", line 34, in _args_adjust
    weights=self.kwds.get("weights", None),
  File "<__array_function__ internals>", line 6, in histogram
  File "Z:\miniconda3\envs\tf\lib\site-packages\numpy\lib\histograms.py", line 793, in histogram
    a, weights = _ravel_and_check_weights(a, weights)
  File "Z:\miniconda3\envs\tf\lib\site-packages\numpy\lib\histograms.py", line 301, in _ravel_and_check_weights
    'weights should have the same shape as a.')
ValueError: weights should have the same shape as a.


There are two issues I think. The first one emerges when the number of bins is computed in `HistPlot._args_adjust(self)`. There, `np.histogram` is called with the `weights` argument unnecessarily passed in. When removed, the plot succeeds if the shape of `weights` is (100, ), as that matches the individual column (squeezed) shape, which is required by `np.histrogram`.
However, my guess is that the shape of `weights` should be the same as that of the data frame itself, (100, 2) in this case, so each column can be weighted individually. That is the second issue which is less trivial to fix.

**Comment by charlesdong1991** [comment]
take
