### ISSUE TITLE
to_csv / to_pickle optionally use fast gzip compressionlevel=1

### ISSUE THREAD

**Issue by kernc** [pandas-dev/pandas#33196]
#### Code Sample, a copy-pastable example if possible

Enhancement proposal

```python
>>> df.to_csv('data.csv.gz')  # Awfully slow

>>> df.to_pickle('data.pkl.bz2')  # Awfully slow

>>> df.to_csv('data.csv.gz', fast=True)  # Uses fast compressionlevel=1

# or, better:

>>> pd.options.io.compressionlevel = 1

>>> df.to_pickle('data.pkl.bz2')  # Uses fast compressionlevel=1

...
```
#### Problem description

Compression of large objects in pandas is slow.

Popular evidence comparing compression levels for average payloads shows [[1]](https://catchchallenger.first-world.info/wiki/Quick_Benchmark:_Gzip_vs_Bzip2_vs_LZMA_vs_XZ_vs_LZ4_vs_LZO) [[2]](https://tukaani.org/lzma/benchmarks.html) that compressed size is usually far less variable than compression time, which most often spans several folds.
`compressionlevel=1` is _orders of magnitude_ faster, whereas `compressionlevel=9` is only 10% smaller.

One optimizes for size, the other for speed, and much fewer people ever need something in between.

#### Output of ``pd.show_versions()``

<details>

1.1.0.dev0+786.gec7734169

</details>

**Comment by jessefarnham** [comment]
take
