### ISSUE TITLE
MacPython/pandas-wheels wheel builds failing

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#33210]
This affects the linux builds, both py37 and py38, 32 or 64-bit.

https://dev.azure.com/pandas-dev/pandas-wheels/_build/results?buildId=30996&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=2e128ad5-2f7f-5333-3f34-c85b8fbc7250&l=1216

```
=================================== FAILURES ===================================
__________________________ test_no_permission[c_high] __________________________
[gw1] linux -- Python 3.7.0 /venv/bin/python

            with pytest.raises(PermissionError, match=msg) as e:
>               parser.read_csv(path)

/venv/lib/python3.7/site-packages/pandas/tests/io/parser/test_common.py:978: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/venv/lib/python3.7/site-packages/pandas/tests/io/parser/conftest.py:22: in read_csv
    return read_csv(*args, **kwargs)
/venv/lib/python3.7/site-packages/pandas/io/parsers.py:676: in parser_f
    return _read(filepath_or_buffer, kwds)
/venv/lib/python3.7/site-packages/pandas/io/parsers.py:449: in _read
    parser = TextFileReader(fp_or_buf, **kwds)
/venv/lib/python3.7/site-packages/pandas/io/parsers.py:880: in __init__
    self._make_engine(self.engine)
/venv/lib/python3.7/site-packages/pandas/io/parsers.py:1112: in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
/venv/lib/python3.7/site-packages/pandas/io/parsers.py:1935: in __init__
    self._reader = parsers.TextReader(src, **kwds)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   pandas.errors.EmptyDataError: No columns to parse from file

pandas/_libs/parsers.pyx:532: EmptyDataError

```

Looks to be from https://github.com/pandas-dev/pandas/pull/32839

cc @gfyoung @roberthdevries

**Comment by roberthdevries** [comment]
Nope it's from #32737

**Comment by roberthdevries** [comment]
The test makes the file unreadable by doing `chmod(path, 0)`. This means nobody is allowed to read it. But for some reason, this does not work on all platforms. Originally this only did not work for Windows. But now apparently it also does not work on Azure.
The EmptyDataError exception is caused by the fact that the file is actually empty. There is no need to fill a file that you cannot read.

**Comment by TomAugspurger** [comment]
What needs to change? Something in the test?

**Comment by roberthdevries** [comment]
My guess is the test environment. But I don't understand why setting the mode of the file fails. This is a regular Linux OS, is it? Or is Azure doing something special here?

**Comment by roberthdevries** [comment]
Is this pipeline by any chance running as root?

**Comment by TomAugspurger** [comment]
I'm not sure. I don't see anything in the logs about what the user is.
