### ISSUE TITLE
Unable to Build pandas with Py38, macOS (clang?) and Cython>0.29.13 (tp_print warning)

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#33239]
Dedicated issue for @jbrockmendel callout in https://github.com/pandas-dev/pandas/issues/30609#issuecomment-605373212

I opened an issue on the Cython side as well https://github.com/cython/cython/issues/3474

There's a rabbit hole of conversation with this going back to CPython . This may just be a temporary issue for Py38, so one "workaround" could be to just add `-Wno-deprecated-declaration` when these particular combination of things is detected, though of course an actual fix would be ideal

**Comment by TomAugspurger** [comment]
After reading through the linked issues and BPOs I'm not sure that simply silencing this warning on macOS is the way to go. I'll do some more research, but for now I'm working around it with by setting `CFLAGS='-Wno-error=deprecated-declarations' ` when compiling.

**Comment by jbrockmendel** [comment]
is this resolved/do we have a gameplan?

**Comment by WillAyd** [comment]
We make an exception for PY38 in the Setup on this platform. That's probably the best we can get for now
