### ISSUE TITLE
DOC: in docstrings point users to valid offset aliases

### ISSUE THREAD

**Issue by patricktokeeffe** [pandas-dev/pandas#3324]
Many timeseries-related functions have a `freq` argument that accepts strings representing some offset value. The specific valid options are apparently known as "offset aliases." Not exactly intuitive search terms but I did eventually find https://github.com/pydata/pandas/blob/master/doc/source/timeseries.rst which lists the valid aliases. 

I can understand why it's suboptimal to list all valid aliases in the docstring of every function with a `freq` argument but it's also frustrating for users to be told "use one of these" without being told what "these" are. Can a balance be struck? 

Perhaps the aliases are already defined in some docstring and I have not found them. In this case, adding a "see here for valid aliases" would probably be sufficient. If they are not, however, what would be the best way of incorporating them?

**Comment by linebp** [comment]
This appears to be related to #13160 and can also be marked as closed?

**Comment by jreback** [comment]
yep, thanks @linebp 

of course if there are other doc-strings that appear to need to link, pls open a new issue listing them (of course PR is even better)!
