### ISSUE TITLE
Append Mode for ExcelWriter with "xlsxwriter"

### ISSUE THREAD

**Issue by engkimbs** [pandas-dev/pandas#33264]
**Problem description**

ExcelWriter's append mode doesn't work when setting default xlsxwriter. To use append mode, I have to set the engine openpyxl. I think it is inconvenient and slow. So I suggest ExcelWriter can be set as append mode when default (xlsxwriter).

**Sample Code**

**AS-IS**
```python
writer = pd.ExcelWriter('APT_TRADE.xlsx', engine='openpyxl', mode='a')
apt_dataframe.to_excel(writer, sheet_name='city-' + date.strftime("%Y%m"), index=False)
```

**TO-BE**
```python
writer = pd.ExcelWriter('APT_TRADE.xlsx', mode='a')
apt_dataframe.to_excel(writer, sheet_name='city-' + date.strftime("%Y%m"), index=False)
```

**Comment by WillAyd** [comment]
See this comment from the xlsxwriter maintainer https://github.com/pandas-dev/pandas/issues/3441#issuecomment-280296299

So not possible unless anything has changed that @jmcnamara is aware of

**Comment by ddileonardo** [comment]
The pandas documentation should be updated to say that you need to specify openpyxl as the engine. It still reads as 

>>> with pd.ExcelWriter("output.xlsx", mode="a") as writer:
...     df1.to_excel(writer, sheet_name="Sheet_name_3")

which does not work!

[https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_excel.html](url)
