### ISSUE TITLE
BUG: Can't disable progress bar for read_gbq

### ISSUE THREAD

**Issue by de-code** [pandas-dev/pandas#33360]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
import pandas as pd

pd.read_gbq(..., progress_bar_type=None)
```

(Due to the BigQuery dependency it's not copy-pastable)

Warning message displayed or tqdm is used:

```
/path/to/python/site-packages/pandas_gbq/gbq.py:555: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  progress_bar_type=progress_bar_type,
```

That is because if `progress_bar_type` is set to `None` it is not passed to `pandas_gbq.read_gbq` (see https://github.com/pandas-dev/pandas/pull/29858#discussion_r352260559). But the default for `pandas_gbq.read_gbq` is `tqdm`.

#### Problem description

It should be possible to disable the progress bar.

#### Expected Output

No progress bar.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-91-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.0.3
numpy            : 1.18.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 39.0.1
Cython           : None
pytest           : 4.6.9
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : 0.13.1
pyarrow          : None
pytables         : None
pytest           : 4.6.9
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
</details>

**Comment by TomAugspurger** [comment]
Thanks for the report. Looks like we need to just always set it at https://github.com/pandas-dev/pandas/blob/6ae710adf2739ca9da0877e7cc780f420661b670/pandas/io/gbq.py#L171-L172.

We'll need to verify that the minimum supported version of gbq will accept it.

**Comment by de-code** [comment]
You could also set the default to something like `NOT_SET` and compare against that instead of `None`. (Or use something like kwargs)

**Comment by TomAugspurger** [comment]
I'm not sure why we have a different default, perhaps a version issue. Ideally we would just follow pandas-gbq (cc @tswast)

**Comment by tswast** [comment]
Yes, it was left out due to version issues. `progress_bar_type` was added in `pandas-gbq==0.12.0`.

Options:

1. Increment minimum pandas-gbq version to at least `0.12.0` and pass through the argument value to pandas-gbq.
2. Use a sentinel value for the default (`NOT_SET`) and only populate the value in pandas-gbq when set to something else.

By following (2), the default value in pandas-gbq will be used. By following (1), pandas can set a different default value from pandas-gbq.

**Comment by sumanau7** [comment]
take
