### ISSUE TITLE
BUG: `pandas.Series.eq` doc and result mismatch for fill_value

### ISSUE THREAD

**Issue by rgsl888prabhu** [pandas-dev/pandas#33380]
- [ ] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample

```
>>> import pandas as pd
>>> import numpy as np
>>> pd.Series([np.nan]).eq(pd.Series([np.nan]), fill_value=5.0)
0    False
dtype: bool
```

#### Problem description

As per the doc, if fill_value is provided and if the element at a position is missing in both series, then result will also be missing, but as per the result, False is being returned rather than `nan`. 

#### Expected Output
So, not sure if doc is wrong or output is wrong. So opening this issue just to clarify this and fix appropriate issue.
#### Output of ``pd.show_versions()``

<details>

```
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.3.0-26-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.1
numpy            : 1.16.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.1.1
setuptools       : 41.0.1
Cython           : 0.29.12
pytest           : 5.0.1
hypothesis       : None
sphinx           : 2.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.3.4
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.6.1
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.4
matplotlib       : 3.1.0
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.0.1
pyxlsb           : None
s3fs             : None
scipy            : 1.3.0
sqlalchemy       : 1.3.5
tables           : 3.5.2
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.8
numba            : 0.44.1

```
</details>

**Comment by dsaxton** [comment]
@rgsl888prabhu This documentation does seem confusing, but I think what it actually means is that the result of _filling_ will be null when both entries are missing rather than the result of the comparison itself (in this case the comparison has a bool dtype, so it actually cannot be null). An internal docstring is a bit more explicit:

> If a non-None fill_value is given, replace null entries in left and right with this value, but only in positions where _one_ of left/right is null, not both.

I think this could probably be made more clear in the user-facing docs.
