### ISSUE TITLE
DEPR: Remove aliased Resampler methods

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#33396]
It seems the forward and backward filling methods are duplicated for Resampler objects (e.g., bfill is an alias for backfill, and ffill is an alias for pad). Does it make sense to deprecate backfill and pad in favor of the bfill and ffill, as these names are more consistent with other methods in pandas (e.g., DataFrame.ffill)?

**Comment by rhshadrach** [comment]
It looks like pad / backfill were deprecated in groupby / Resampler, but not Series / DataFrame. I'm guessing it's desired to remove them in Series / DataFrame too? If that's the case, I'm wondering if we should deprecate them there in 2.x, leave them in groupby / Resampler (still deprecated), and remove everything altogether.
