### ISSUE TITLE
QST:What's wrong with SHA256? Be hacked?

### ISSUE THREAD

**Issue by tezhanduiyuan** [pandas-dev/pandas#33390]
When I pip3 install pandas using raspberrypi,it reports:

THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    pandas from https://www.piwheels.org/simple/pandas/pandas-1.0.3-cp37-cp37m-linux_armv7l.whl#sha256=f1b6b335a4aefff03ce1aefffd24934d3e93ce0dc88e387efa761de1981fdcf1:
        Expected sha256 f1b6b335a4aefff03ce1aefffd24934d3e93ce0dc88e387efa761de1981fdcf1
             Got        e2621af914f20cbe948a6bfe74d009dc28b8fa1511f50ac46ab70c24a14f4176

**Comment by TomAugspurger** [comment]
I'm not sure, but we don't maintain those packages.
