### ISSUE TITLE
pandas 1.0.0 conflict with Anaconda

### ISSUE THREAD

**Issue by ronyarmon** [pandas-dev/pandas#33419]
Trying to install or update from pandas 0.25.1 to 1.0.0 I'm getting into a long process of examining conflicts with existing packages: 
```
conda install pandas=1.0.0
```
Installation log:

> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: | 
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort

Followed by:
> Examining conflict for psutil parso spyder-kernels sphinxcontrib-websupport tblib urllib3  jupyter_core glob2 asn1crypto docutils sphinxcontrib boto sortedcollections matplotlib entrypoints markupsafe astropy... 
And a conflict check against individual packages which takes a long time. 

Working with pandas standalone or on virtual env is not an option as I need to run my function using a jupyter notebook.  Do I need to write it with version 0.25.1 or is there a work around that I may be missing here?

**Comment by TomAugspurger** [comment]
We typically recommend working in environments: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

> as I need to run my function using a jupyter notebook

You can include jupyter notebook in your environment.
