### ISSUE TITLE
BUG/ENH: to_datetime dayfirst ought to be strict

### ISSUE THREAD

**Issue by hayd** [pandas-dev/pandas#3341]
xref #12585

I think this ought to raise a ValueErrror:

```
In [1]: pd.to_datetime('01-13-2012', dayfirst=True)
Out[1]: datetime.datetime(2012, 1, 13, 0, 0)
```

_This means if my data is bad (i.e. somehow I have a mixture of american and british string-dates), I won't be told there was an issue when parsing! I can't think of a usecase where this kind of precedence would be appropriate, and it means you'll end up with incorrect dates._

The [precedence behaviour](http://labix.org/python-dateutil#head-b95ce2094d189a89f80f5ae52a05b4ab7b41af47) appears to be a feature from `dateutil` (which `tslib.array_to_datetime` calls):

```
In [2]: from dateutil.parser import parse as parse_date

In [3]: parse_date('1/12/2012', dayfirst=True)
Out[3]: datetime.datetime(2012, 12, 1, 0, 0)

In [4]: parse_date('1/13/2012', dayfirst=True)
Out[4]: datetime.datetime(2012, 1, 13, 0, 0)
```

It should raising like this:

```
In [5]: parse_date('14/14/2012', dayfirst=True)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-ca14fc16e421> in <module>()
----> 1 parse_date('14/14/2012', dayfirst=True)

/Library/Python/2.7/site-packages/dateutil/parser.pyc in parse(timestr, parserinfo, **kwargs)
    718         return parser(parserinfo).parse(timestr, **kwargs)
    719     else:
--> 720         return DEFAULTPARSER.parse(timestr, **kwargs)
    721
    722

/Library/Python/2.7/site-packages/dateutil/parser.pyc in parse(self, timestr, default, ignoretz, tzinfos, **kwargs)
    315             if value is not None:
    316                 repl[attr] = value
--> 317         ret = default.replace(**repl)
    318         if res.weekday is not None and not res.day:
    319             ret = ret+relativedelta.relativedelta(weekday=res.weekday)

ValueError: month must be in 1..12
```

... :(

**Comment by JanSchulz** [comment]
Switching from #11725, where this happened, e.g. daysfirst=False would parse month as days

```
>>> pd.to_datetime(["29.01.1945","1.3.1945", "02.03.1945"])
DatetimeIndex(['1945-01-29', '1945-01-03', '1945-02-03'], dtype='datetime64[ns]', freq=None)
``` 

right now, the doc only describes the problem for the other way:  

> Warning: dayfirst=True is not strict, but will prefer to parse with day first (this is a known bug, based on dateutil behavior).

As dayfirst is False, this makes no mention that the other way can also happen

**Comment by jorisvandenbossche** [comment]
@JanSchulz Indeed .. Maybe also worth mentioning that if you want strict behaviour, you can use `format=...` if possible?

**Comment by jorisvandenbossche** [comment]
I opened an issue for this at the dateutil tracker, as I couldn't find one: https://github.com/dateutil/dateutil/issues/214

**Comment by WillAyd** [comment]
Not a pandas bug and documented accordingly

**Comment by jbrockmendel** [comment]
This is one that we need to bug dateutil about. (Or offer a PR upstream).
Pls consider reopening.

**Comment by WillAyd** [comment]
@jbrockmendel  I closed because there's nothing technically to be done on the pandas side and this is arguably duplicative of #12585. Feel free to reopen if you think it's this issue in particular adds value to tracking
