### ISSUE TITLE
BUG: set_levels set wrong order levels for MutiIndex

### ISSUE THREAD

**Issue by zxdawn** [pandas-dev/pandas#33420]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas as pd
arrays = [['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
          ['one', 'one', 'one', 'one', 'one', 'one', 'one', 'one'],
          ['three', 'four', 'three', 'four', 'three', 'four', 'three', 'four'],
          ]

df = pd.DataFrame(np.random.randn(8, 4), index=arrays)
df.index.set_levels([3, 4], level=2, inplace=True)
```

#### Problem description

The changed MutiIndex isn't the same order of assigned list.
```
                  0         1         2         3
bar one 4 -0.606998 -1.225794  0.284541 -0.395946
        3  2.693403  0.803962  0.421412 -0.369766
baz one 4  0.182893  0.364850  0.499927  0.271245
        3 -0.783458 -0.072504 -1.081301 -0.091093
foo one 4  2.630340 -0.442308  0.519715 -0.412296
        3 -0.813574  0.323040 -0.356866  1.877196
qux one 4 -0.578158  0.511383  0.613484 -0.483777
        3 -0.161618 -0.481930  0.012694 -1.001978
```

#### Expected Output
```
                  0         1         2         3
bar one 3 -0.606998 -1.225794  0.284541 -0.395946
        4  2.693403  0.803962  0.421412 -0.369766
baz one 3  0.182893  0.364850  0.499927  0.271245
        4 -0.783458 -0.072504 -1.081301 -0.091093
foo one 3  2.630340 -0.442308  0.519715 -0.412296
        4 -0.813574  0.323040 -0.356866  1.877196
qux one 3 -0.578158  0.511383  0.613484 -0.483777
        4 -0.161618 -0.481930  0.012694 -1.001978
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.3
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.3.post20200325
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 2.4.4
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.2.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 0.15.1
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by zxdawn** [comment]
However, if I reassign the whole index instead of using `set_levels`, it works well:
```
df.index = pd.MultiIndex.from_arrays(
    [df.index.get_level_values(0),
     df.index.get_level_values(1),
     np.tile([3, 4], 4)])
```

Output:
```
                  0         1         2         3
bar one 3  0.503767  1.109582 -0.146793 -0.419135
        4  0.456081  2.401097  1.433270  0.180908
baz one 3  1.197156  0.674720  1.549449  0.428057
        4 -2.115809  0.257640  0.981204 -1.296013
foo one 3 -0.022447 -0.023483 -0.177297 -0.425126
        4 -0.138847 -0.593709  1.081993  1.418835
qux one 3  1.143166  0.596455 -0.011853  0.630963
        4  0.932577 -1.362461 -0.675947  1.051204
```

**Comment by yixinxiao7** [comment]
take

**Comment by yixinxiao7** [comment]
It seems that the problem's that the codes aren't being reset when the new level is set. Is there a method I could call to easily do this?

**Comment by zxdawn** [comment]
@yixinxiao7 You question remind me that I can reset index after changing the multiindex:
```
level_list = ['level_0', 'level_1', 'level_2']
df = df.reset_index().set_index(level_list).sort_index(level=level_list)
```

However, I don't know how to reset codes in `set_levels`.

**Comment by jreback** [comment]
closing as this is the expected behavior, the levels ordering is an internal impl detail.
