### ISSUE TITLE
DOC: Data links in Pandas API Reference are broken 404

### ISSUE THREAD

**Issue by Hackathorn** [pandas-dev/pandas#33428]
#### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.plotting.parallel_coordinates.html
...probably many examples in other sections

#### Documentation problem

Results in 404 not found error
df = pd.read_csv('https://raw.github.com/pandas-dev/pandas/master'
                    '/pandas/tests/data/csv/iris.csv')

#### Suggested fix for documentation

The GitHub site should be "raw.githubusercontent.com"

**Comment by TomAugspurger** [comment]
Thanks for the report, a pull request to fix it would be welcome.

**Comment by jackattackyang** [comment]
take

**Comment by jackattackyang** [comment]
The correct link is 
`https://raw.github.com/pandas-dev/pandas/master/pandas/tests/data/iris.csv`

However doc string for `parallel_coordinates` actually contains the correct link. The referencing might be the problem. First time contributing and unfortunately running into problems with locally building pandas on Windows. Looking into it but have removed my assignment in the meantime.

**Comment by konstell** [comment]
The path in the current doc is incorrect, but not because it has the incorrect domain name. The second line of the `read_csv` command should say `'/pandas/tests/data/iris.csv'` instead of `'/pandas/tests/data/csv/iris.csv'`

**Comment by konstell** [comment]
take

**Comment by konstell** [comment]
Upon further investigation, this has already been fixed in another PR 15 days ago: https://github.com/pandas-dev/pandas/pull/33099

**Comment by datapythonista** [comment]
Fixed in #33099
