### ISSUE TITLE
BUG: core.missing._akima_interpolate will raise AttributeError

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#33426]
```
    from scipy import interpolate

    P = interpolate.Akima1DInterpolator(xi, yi, axis=axis)

    if der == 0:
        return P(x)
    elif interpolate._isscalar(der):
        return P(x, der=der)
    else:
        return [P(x, nu) for nu in der]
```

There is no `interpolate._isscalar` so this would raise if it were ever reached.  AFAICT we have only one test that gets to this function, must always have `der == 0`

**Comment by jbrockmendel** [comment]
I'm guessing [this](https://github.com/scipy/scipy/blob/master/scipy/interpolate/polyint.py#L11) is the function that we're trying to get at:

```
def _isscalar(x):
    """Check whether x is if a scalar type, or 0-dim"""
    return np.isscalar(x) or hasattr(x, 'shape') and x.shape == ()
```

**Comment by Fifthist** [comment]
We could

1. Import `_isscalar` directly inside the definition of `_akima_interpolate`.

```python
from scipy.interpolate.polyint import _isscalar
```

2. Use  [`is_scalar`](https://github.com/pandas-dev/pandas/blob/24827e5d93f55368803a8e6a599e5b0cf858ac24/pandas/core/missing.py#L17), which is already imported in the module. Looking at it's [definition](https://github.com/pandas-dev/pandas/blob/d106b81ce532bc71ec6cced944ddb751a4b0e5a3/pandas/_libs/lib.pyx#L117), it seems to check both cases that `_isscalar` checks.

**Comment by jbrockmendel** [comment]
we'll want to use is_scalar, will probably also need a lib.item_from_zerodim.

**Comment by Fifthist** [comment]
how about checking that `der` is a non-negative integer instead of a general scalar value, since n-th order derivatives of a polynomial is only defined for natural n.

https://github.com/scipy/scipy/blob/c1372d8aa90a73d8a52f135529293ff4edb98fc8/scipy/interpolate/interpolate.py#L876

**Comment by hkennyv** [comment]
take

**Comment by hkennyv** [comment]
Hey all, I'm trying to add to the `test_interpolate_akima` test so that it covers cases where `der` is a list but I'm having trouble debugging this error:

```python
Exception has occurred: TypeError
NumPy boolean array indexing assignment requires a 0 or 1-dimensional input, input has 2 dimensions
  File "/Users/khuynh/github/pandas/pandas/core/missing.py", line 303, in interpolate_1d
    result[invalid] = _interpolate_scipy_wrapper(
  File "/Users/khuynh/github/pandas/pandas/core/internals/blocks.py", line 1203, in func
    return missing.interpolate_1d(
  File "<__array_function__ internals>", line 5, in apply_along_axis
  File "/Users/khuynh/github/pandas/pandas/core/internals/blocks.py", line 1216, in _interpolate
    interp_values = np.apply_along_axis(func, axis, data)
  File "/Users/khuynh/github/pandas/pandas/core/internals/blocks.py", line 1113, in interpolate
    return self._interpolate(
  File "/Users/khuynh/github/pandas/pandas/core/internals/managers.py", line 397, in apply
    applied = getattr(b, f)(**kwargs)
  File "/Users/khuynh/github/pandas/pandas/core/internals/managers.py", line 558, in interpolate
    return self.apply("interpolate", **kwargs)
  File "/Users/khuynh/github/pandas/pandas/core/generic.py", line 6897, in interpolate
    new_data = data.interpolate(
  File "/Users/khuynh/github/pandas/test.py", line 33, in <module>
    interp_s = ser.reindex(new_index).interpolate(method="akima", der=[1, 2])
```

I'm getting this error when running this test file I made so I could step through with my debugger:

```python
import numpy as np
import pytest

import pandas.util._test_decorators as td

import pandas as pd
from pandas import Index, MultiIndex, Series, date_range, isna
import pandas._testing as tm

print("hello world!")

ser = Series([10, 11, 12, 13])

expected = Series(
    [11.00, 11.25, 11.50, 11.75, 12.00, 12.25, 12.50, 12.75, 13.00],
    index=Index([1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 2.75, 3.0]),
)
# interpolate at new_index
new_index = ser.index.union(Index([1.25, 1.5, 1.75, 2.25, 2.5, 2.75])).astype(
    float
)
interp_s = ser.reindex(new_index).interpolate(method="akima")
# tm.assert_series_equal(interp_s[1:3], expected)
print(interp_s)

# test interpolate when a non-zero int
interp_s = ser.reindex(new_index).interpolate(method="akima", der=1)
# tm.assert_series_equal(interp_s[1:3], expected)
print(interp_s)
print(interp_s[1:3])

# test interpolate when der is a list
interp_s = ser.reindex(new_index).interpolate(method="akima", der=[1, 2])
# tm.assert_series_equal(interp_s[1:3], expected)

print(interp_s)
print('success!')
```

Any pointers?

**Comment by jbrockmendel** [comment]
> test so that it covers cases where der is a list

why?

**Comment by hkennyv** [comment]
because the docstring for [`core.missing._akima_interpolate`](https://github.com/pandas-dev/pandas/blob/master/pandas/core/missing.py#L449) specififes `der` to be "int or list". But I see upon checking [`scipy.interpolate.PPoly.__call__`](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.interpolate.PPoly.__call__.html#scipy.interpolate.PPoly.__call__) that the docstring is incorrect.

I can modify the docstring for `_akima_interpolate` and submit a PR if everything else checks out?

**Comment by jbrockmendel** [comment]
> I can modify the docstring for _akima_interpolate and remove that else branch and submit a PR if everything else checks out?

sounds good
