### ISSUE TITLE
tm.external_error_raised instead of tm.assertRaises in the documentation

### ISSUE THREAD

**Issue by SurajH1** [pandas-dev/pandas#33434]
I tried to use tm.assertRaises but got the following error:

 with tm.assertRaises(ValueError):
AttributeError: module 'pandas.util.testing' has no attribute 'assertRaises'

After carefully assessing whether I had all the dependencies, I looked into the testing.py files and realised that there is no assertRaises function although the testing documentation advises to use the function.(https://github.com/pandas-dev/pandas/wiki/Testing) I believe the documentation should be updated to tm.external_error_raised.

**Comment by WillAyd** [comment]
We actually use pytest.raises now. @TomAugspurger @datapythonista are we still maintaining the wiki or should this be migrated to the docs somewhere?

**Comment by TomAugspurger** [comment]
Not using the wiki anymore. I'm guessing that has been moved to the
contributing guide.

**Comment by jbrockmendel** [comment]
Just updated the usage on the wiki page to use pytest.raises.  It seems unlikely to stay in sync; removing it may make sense (i think theres an issue about that)

**Comment by lithomas1** [comment]
Closing as resolved.
