### ISSUE TITLE
DOC: Development guide giving 404

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#33430]
https://pandas.pydata.org/docs/development/index.html is giving a 404 right now. Haven't looked into why cc @datapythonista.

**Comment by datapythonista** [comment]
Oh, I guess the nginx redirect for the dev docs is capturing that, didn't realize. Will fix it shortly. Thanks for the heads up.

**Comment by jorisvandenbossche** [comment]
How would the dev docs conflict? That's /docs/dev/ and not /docs/development/ ?

**Comment by datapythonista** [comment]
Fixed.

The redirection url was `/docs/dev`, which apparently matches `/docs/development`, and I guess was redirecting to `<redirect_directory>/elopment`. Now it's `/docs/dev/` and everything seems to work as expected.

**Comment by jorisvandenbossche** [comment]
Ah :) Thanks for the quick fix!

**Comment by TomAugspurger** [comment]
Thanks!
