### ISSUE TITLE
BUG: Using `kwargs` in `Rolling.apply()`

### ISSUE THREAD

**Issue by echasnovski** [pandas-dev/pandas#33433]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
from functools import partial

import numpy as np
import pandas as pd


def foo(x, par):
    return np.sum(x + par)


df = pd.DataFrame({"gr": [1, 1], "a": [1, 2]})

# With `kwargs`
try:
    print(df.groupby("gr")["a"].rolling(1).apply(foo, kwargs={"par": 10}))
except Exception as e:
    print(e)

# Using `partial`
bar = partial(foo, par=10)
print(df.groupby("gr")["a"].rolling(1).apply(bar))
```

#### Problem description

**Expected**: using appropriate `kwargs` argument for `pandas.core.window.rolling.Rolling.apply()` should be equivalent to premodifying supplied function with `functools.partial()` (because it is stated in [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.window.rolling.Rolling.apply.html)).
**Current**: `kwargs` doesn't seem to be used at all, because it results into "missing 1 required positional argument" exception.
**Note**: This works as expected in pandas 0.25.3, but gives error as early as 1.0.0.

#### Expected Output

```
gr   
1   0    11.0
    1    12.0
Name: a, dtype: float64
gr   
1   0    11.0
    1    12.0
Name: a, dtype: float64
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-29-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : ru_UA.UTF-8
LOCALE           : ru_UA.UTF-8

pandas           : 1.0.3
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.3.post20200325
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by simonjayhawkins** [comment]
> **Note**: This works as expected in pandas 0.25.3, but gives error as early as 1.0.0.

regression in #29428 (i.e. 1.0.0)

6e5d14834072e7856987eb31e574b2a05db9f0b9 is the first bad commit
commit 6e5d14834072e7856987eb31e574b2a05db9f0b9
Author: Matthew Roeschke <emailformattr@gmail.com>
Date:   Thu Nov 21 04:59:30 2019 -0800

    REF: Separate window bounds calculation from aggregation functions (#29428)
