### ISSUE TITLE
BUG: Series.any/all with level keyword should preserve boolean dtype

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#33449]
```
In [5]: s = pd.Series([False, False, True, True, False, True],
                      index=[0, 0, 1, 1, 2, 2], dtype="boolean")  

In [6]: s.all(level=0) 
Out[6]: 
0    False
1     True
2    False
dtype: bool
```

The dtype of the result could also be boolean instead of bool.

**Comment by KenilMehta** [comment]
Hi @jorisvandenbossche 
This is my first Pandas Issue and I would like to help solve this issue.

Just for understanding the issue, the dtype of the Series object is "boolean", hence, we want the return type of Series.all() also to be "boolean" instead of "bool". Is that right?

**Comment by jorisvandenbossche** [comment]
Yes, that is correct. But specifically with the `level` keyword as in the example above. Without using the `level` keyword, it already works as expected.

**Comment by KenilMehta** [comment]
Do we want the dtype of result Series to match with the original Series in all the cases or only in the case of boolean?

What would you expect the dtype of result Series to be in the following example?
```
import pandas as pd
import numpy as np

s = pd.Series([0, 0, 1, 1, 0, 1], index=[0, 0, 1, 1, 2, 2], dtype="int64")
print(s.all(level=0))
```
