### ISSUE TITLE
BUG: Low performance of DataFrame operations

### ISSUE THREAD

**Issue by rkashapov** [pandas-dev/pandas#33443]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import timeit

import pandas as pd
import numpy as np


def div_simple(df):
    return df.div(df.sum(axis=0), axis=1)


def div_transposed(df):
    df = df.T
    return df.div(df.sum(axis=1), axis=0).T


def div_python(df):
    data = df.values.tolist()
    for i in range(COLS):
        s = sum(data[j][i] for j in range(ROWS))
        for j in range(ROWS):
            data[j][i] /= s
    return data


COLS = 1000
ROWS = 10


df = pd.DataFrame(
    np.random.randint(0,100,size=(ROWS, COLS)),
    columns=list(range(COLS)),
)

for func in (div_simple, div_transposed, div_python):
    print(f'{timeit.timeit(lambda: func(df.copy()), number=100):08.4f}s\t{func.__name__}')
```

#### Problem description

I've faced a strange performance issue. The pandas' version works much longer than a bare-python version.

```
100 x 100
001.6424s	div_simple
000.0596s	div_transposed
000.1856s	div_python
```
```
10 x 1000
000.2322s	div_simple
000.0576s	div_transposed
000.1780s	div_python
```
```
1000 x 10
015.3119s	div_simple
000.0560s	div_transposed
000.2327s	div_python
```

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.4.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : ru_RU.UTF-8
LOCALE           : ru_RU.UTF-8

pandas           : 1.0.3
numpy            : 1.18.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 40.8.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by jbrockmendel** [comment]
I expect this will be solved by #32779

**Comment by jorisvandenbossche** [comment]
I don't think #32779 will help here, this is a single block (#32779 doesn't handle that case I noticed while trying out timings)

BTW, regarding the pure python one being faster. For small data, pandas (and to a lesser extent also numpy) will always have some more overhead. But if you go to a bit larger dataframe, you can already see that the pure python gets slower:

```
In [5]: COLS = 1000 
   ...: ROWS = 10000 
   ...:  
   ...: df = pd.DataFrame( 
   ...:     np.random.randint(0,100,size=(ROWS, COLS)), 
   ...:     columns=list(range(COLS)), 
   ...: ) 

In [6]: %timeit div_simple(df) 
328 ms ± 3.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [7]: %timeit div_transposed(df) 
65.8 ms ± 746 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [8]: %timeit div_python(df) 
2.39 s ± 506 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by jbrockmendel** [comment]
div_simple now handily outperforms div_python.  closing.
