### ISSUE TITLE
merge_asof(left_index=True, right_on=...) overwrites left index with right index

### ISSUE THREAD

**Issue by gtg944q** [pandas-dev/pandas#33463]
Building from an example in the docs...
```
left = pd.DataFrame({'left_val': ['a', 'b', 'c'], 'left_time': [1, 5, 10]}, index=[1, 5, 10])
right = pd.DataFrame({'right_val': [1, 2, 3, 6, 7]}, index=[1, 2, 3, 6, 7])
```

```
>>> pd.merge_asof(left, right, left_index=True, right_index=True)
   left_val  left_time  right_val
1         a          1          1
5         b          5          3
10        c         10          7
```
Returned index is the index of left.

```
>>> pd.merge_asof(left, right, left_on='left_time', right_index=True)
   left_val  left_time  right_val
1         a          1          1
5         b          5          3
10        c         10          7
```
Returned index is the index of left.

```
>>> pd.merge_asof(left, right, left_on='left_time', right_on='right_val')
  left_val  left_time  right_val
0        a          1          1
1        b          5          3
2        c         10          7
```
Return value has index reset (I assume expected?)

```
>>> pd.merge_asof(left, right, left_index=True, right_on='right_val')
  left_val  left_time  right_val
1        a          1          1
3        b          5          3
7        c         10          7
```
Returned index is the index of _right_.

Perhaps I'm misunderstanding something about how this is supposed to work, but it seems to me that the behavior in the last example is incorrect.

**Comment by gtg944q** [comment]
NB:  proving to myself that the indexes returned in examples 2 and 4 are indeed the _indexes_, not the values:

**Comment by MomIsBestFriend** [comment]
@gtg944q Thank you for the report!

---

Do you mind paste the URL of the examples you found in the docs? we fixed a lot of documentation related problems recently, maybe this is already solved.

**Comment by gtg944q** [comment]
It's at https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.merge_asof.html, but I'm really just building on an example in there, so it's not a documentation problem.

**Comment by mroeschke** [comment]
Since this is advertised as "left-join" like, the last 2 examples you provide are surprising, and I'd expect to propagate the values in the left index (and not reset the index or use the right index). I'll mark as a bug, but this _may_ break some existing tests.
