### ISSUE TITLE
BUG: When using apply on a DataFrame with SparseDtype, passing raw=True doesn't have any effect.

### ISSUE THREAD

**Issue by v-borges** [pandas-dev/pandas#33460]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of pandas.
---

#### Code Sample, a copy-pastable example

```python
import pandas as pd
import numpy as np

pd.DataFrame(
    [[0, 1, 0, 2, 0, 3, 0, 4]],
    dtype=pd.SparseDtype(np.dtype("int")),
).apply(lambda x: type(x), raw=True, axis=1)
```
Output: 

 `0    <class 'pandas.core.series.Series'>`

#### Problem description

When using apply on a DataFrame with SparseDtype, passing raw=True doesn't have any effect.

#32425 is related but did not solve it.

#### Expected Output

 `0    <class 'numpy.ndarray'>`

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.3
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.3.post20200330
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : 0.3.2
gcsfs            : None
lxml.etree       : 4.4.2
matplotlib       : 3.1.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
numba            : 0.48.0

</details>

**Comment by mroeschke** [comment]
#32425's fix will be applied when pandas 1.1 is released (should be in a couple of months). This fix was not backported to the 1.0.x versions of pandas
