### ISSUE TITLE
BUG: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.   import pandas.util.testing as tm

### ISSUE THREAD

**Issue by fescobar96** [pandas-dev/pandas#33475]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd

```

#### Problem description

I'm getting this future warning when I import pandas as pd. It does not affect pandas' performance, but I think this is something that should be looked at. I have already looked into reports for similar issues, but the circumstances are different. It is also important to note that I am working in Google Colab.

#### Expected Output
There should be no warning.
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]
pandas           : 1.0.3
</details>

**Comment by rmsilva1973** [comment]
@fescobar96 The code you pasted as an example doesn't trigger the warning. However, looking at the warning I think you might be trying this:

**import pandas.util.testing as tm**

And pandas returns a warning stating that this usage is deprecated. Just do this, instead:

**import pandas testing as tm**

This is not a bug in pandas...

**Comment by fescobar96** [comment]
@rmsilva1973: Hi Renato, I am not importing pandas testing, I'm doing the following:
**import pandas as pd**
I am attaching the google colab notebook where I have been able to reproduce the error.
[](https://colab.research.google.com/drive/1pYbNqusO80gvCZ5jjNzyYOnwgjZr8azZ)
Thanks!

**Comment by jreback** [comment]
the offender is statsmodels

you are welcome to open an issue / patch there

**Comment by rmsilva1973** [comment]
@fescobar96 more specifically, the warning fires on importing seaborn. Anyway, like jreback said, it's a statsmodel issue.. :-)
