### ISSUE TITLE
BUG: Clipping a data frame after selecting only numeric columns does not work

### ISSUE THREAD

**Issue by santhisenan** [pandas-dev/pandas#33483]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
import numpy as np

df1 = pd.DataFrame({'A': [100] * 10, 'B': [100] * 10, 'C': ['abc'] * 10})
df1.loc[:, df1.select_dtypes(include=[np.number]).columns].clip(-90, 90, inplace=True)

```

#### Problem description
I am trying to clip the values of all numeric columns in the dataframe.

Initially, the data frame is 
```
	A	B	C
0	100	100	abc
1	100	100	abc
2	100	100	abc
3	100	100	abc
4	100	100	abc
5	100	100	abc
6	100	100	abc
7	100	100	abc
8	100	100	abc
9	100	100	abc
```
The numeric columns are A and B, so
`df1.loc[:, df1.select_dtypes(include=[np.number]).columns]` selects the required columns.

`df1.loc[:, df1.select_dtypes(include=[np.number]).columns].clip(-90, 90, inplace=True)` should clip values in A and B to 90.

Dataframe after clipping is:
```
	A	B	C
0	100	100	abc
1	100	100	abc
2	100	100	abc
3	100	100	abc
4	100	100	abc
5	100	100	abc
6	100	100	abc
7	100	100	abc
8	100	100	abc
9	100	100	abc
```
Clearly, the values are not getting clipped.

#### Expected Output
```
	A	B	C
0	90	90	abc
1	90	90	abc
2	90	90	abc
3	90	90	abc
4	90	90	abc
5	90	90	abc
6	90	90	abc
7	90	90	abc
8	90	90	abc
9	90	90	abc
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None

pandas           : 1.0.3
numpy            : 1.17.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.2.3
setuptools       : 41.4.0
Cython           : 0.29.13
pytest           : 5.2.1
hypothesis       : None
sphinx           : 2.4.4
blosc            : None
feather          : None
xlsxwriter       : 1.2.1
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.8.4 (dt dec pq3 ext lo64)
jinja2           : 2.10.3
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 3.0.0
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.2.1
pyxlsb           : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.3.15
tables           : 3.5.2
tabulate         : 0.8.6
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.1
numba            : 0.45.1

</details>

**Comment by santhisenan** [comment]
I would also like to add that performing the operation without `.loc[]` throws SettingWithCopyWarning.

```python
import pandas as pd
import numpy as np

df1 = pd.DataFrame({'A': [100] * 10, 'B': [100] * 10, 'C': ['abc'] * 10})
df1[df1.select_dtypes(include=[np.number]).columns].clip(-90, 90, inplace=True)
```

```
/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:7496: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._clip_with_scalar(lower, upper, inplace=inplace)
```

This also does not clip the dataframe.

**Comment by santhisenan** [comment]
Another observation:
```python
import pandas as pd
import numpy as np

df1 = pd.DataFrame({'A': [100] * 10, 'B': [100] * 10, 'C': ['abc'] * 10})
df1[['A', 'B']] = df1[df1.select_dtypes(include=[np.number]).columns].clip(-90, 90)
df1
```

This clips the values in the respective columns.

The output of the above piece of code is:
```
	A	B	C
0	90	90	abc
1	90	90	abc
2	90	90	abc
3	90	90	abc
4	90	90	abc
5	90	90	abc
6	90	90	abc
7	90	90	abc
8	90	90	abc
9	90	90	abc
```

**Comment by dsaxton** [comment]
Looks like you've figured it out, but what seems to be happening is you're doing an inplace operation on a _copy_ of your data, which won't affect the original DataFrame:

```python
[ins] In [1]: df = pd.DataFrame({"a": [1, 2, 3], "b": [1, 2, 3]})                                                                                                                                            

[ins] In [2]: df.loc[:, ["a", "b"]] is df.loc[:, ["a", "b"]]                                                                                                                                                 
Out[2]: False
```

**Comment by santhisenan** [comment]
@dsaxton, shouldn’t SettingWithCopyWarning be thrown then? I think it is confusing otherwise.

**Comment by jreback** [comment]
pls read the docs; https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html?highlight=settingwith#indexing-view-versus-copy

doing an inplace operation after indexing works in a copy of the data and this doesn’t do anything

this is generally but not always detectable (in this case it’s not)
