### ISSUE TITLE
BUG: pd.Series.replace(to_replace=...) does not preserve the original dtype of the series

### ISSUE THREAD

**Issue by chrispe** [pandas-dev/pandas#33484]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [X] (optional) I have confirmed this bug exists on the master branch of pandas.

---
#### Code Sample, a copy-pastable example

```python
>>> s = pd.Series(["one", "two"], dtype="string")
>>> expected = pd.Series(["1", "2"], dtype="string")
>>> result = s.replace(to_replace={"one": "1", "two": "2"})
>>> expected
0    1
1    2
dtype: string
>>> result
0    1
1    2
dtype: object
```
#### Problem description

The `pandas.Series.replace` does not return a series with the same `dtype` as the the original series. This behaviour is produced only when the replace function is called using the argument `to_replace`.

Notice: Similar behaviour is produced with other dtypes as well, this issue is not limited to string dtype.

The investigation should probably start here: `/pandas/core/generic.py`

#### Expected Output
We would expect the `pandas.Series.replace(to_replace=...)` to preserve the dtype of the series.
In the above code sample, both of the series should have a dtype of string.
#### Output of ``pd.show_versions()``

<details>
<h2>INSTALLED VERSIONS</h2>
commit           : None
python           : 3.8.2.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.4.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.0.3
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.3.post20200330
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
</details>

**Comment by dsaxton** [comment]
I think that this is not only limited to string dtype:

```python
[ins] In [7]: s                                                                                                                                                                                              
Out[7]: 
0    1
1    2
dtype: Int64

[ins] In [8]: s.replace({1: 3})                                                                                                                                                                              
Out[8]: 
0    3
1    2
dtype: int64
```

```python
[ins] In [12]: s                                                                                                                                                                                             
Out[12]: 
0     True
1    False
dtype: boolean

[ins] In [13]: s.replace({True: False})                                                                                                                                                                      
Out[13]: 
0    False
1    False
dtype: object
```

Also related: https://github.com/pandas-dev/pandas/issues/32988

**Comment by chrispe92** [comment]
> I think that this is not only limited to string dtype:
> 
> ```python
> [ins] In [7]: s                                                                                                                                                                                              
> Out[7]: 
> 0    1
> 1    2
> dtype: Int64
> 
> [ins] In [8]: s.replace({1: 3})                                                                                                                                                                              
> Out[8]: 
> 0    3
> 1    2
> dtype: int64
> ```
> 
> ```python
> [ins] In [12]: s                                                                                                                                                                                             
> Out[12]: 
> 0     True
> 1    False
> dtype: boolean
> 
> [ins] In [13]: s.replace({True: False})                                                                                                                                                                      
> Out[13]: 
> 0    False
> 1    False
> dtype: object
> ```
> 
> Also related: #32988

Added this to the description, so it should be more clear now. Thanks for the feedback @dsaxton.

**Comment by simonjayhawkins** [comment]
> Also related: #32988

#32988 is a regression from 0.25.3 whereas this issue was already present in 0.25.3 for Int64 type

```
>>> import pandas as pd
>>>
>>> pd.__version__
'0.25.3'
>>>
>>> s = pd.Series([1, 2], dtype="Int64")
>>> s
0    1
1    2
dtype: Int64
>>>
>>> s.replace(to_replace={1: 3})
0    3
1    2
dtype: int64
>>>
```

**Comment by MarcusJellinghaus** [comment]
I think I have the same issue:

import pandas as pd
import numpy as np
pd.__version__  #1.1.2

s = pd.Series(['abc', None, pd.NA, 'def'], dtype="string")
print(s.dtype)  # string
t = pd.Series([None], dtype="string")
print(t.dtype)  # string
u = pd.Series([pd.NA], dtype="string")
print(u.dtype)  # string

v = pd.Series(['abc', None, pd.NA], dtype="string")
print(v.dtype)  # string
w = v.replace('abc', pd.NA)
print(w.dtype) # Now of type object, why not string?
               # In Python 1.0.3, it was string
