### ISSUE TITLE
BUG: weird resample behavior between very similar cases of Period vs Datetimes

### ISSUE THREAD

**Issue by hasB4K** [pandas-dev/pandas#33489]
- [X] I have checked that this issue has not already been reported. (as far as I know...)

- [X] I have confirmed this bug exists on the latest version of pandas.

- [X] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

Create `result_date`:
```python
series = pd.Series(1, index=pd.date_range(start="2000-01-01", periods=100))
result_date = series.resample("2M").count()
result_date
```
Outputs:
```
2000-01-31    31
2000-03-31    60
2000-05-31     9
Freq: 2M, dtype: int64
```
Create `result_period`:
```python
series = pd.Series(1, index=pd.period_range(start="2000-01-01", periods=100))
result_period = series.resample("2M").count()
result_period
```
Outputs:
```
2000-01    60
2000-03    40
Freq: 2M, dtype: int64
```

#### Problem description

I would have expect that `result_period` and `result_date` would have been equals.
I have noticed this behavior when trying to debug `pandas/tests/resample/test_period_index.py::test_resample_count` for #31809. (see https://github.com/pandas-dev/pandas/pull/31809#discussion_r407133957)

After the debug, I realised that maybe another bug was there... but I am not sure, I am not familiar enough with the use of Period. So. Is this a bug? If that's not the case, could someone explain why the two outputs are different?

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.5.13-arch2-1
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.18.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.3
Cython           : None
pytest           : 5.4.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.4.1
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : 0.48.0

</details>

**Comment by rhshadrach** [comment]
You get the same results by changing the DateTimeIndex series to be:

    result_date = series.resample("2MS").count()

I think for periods, resampling always starts with the first period and so this behavior is correct if perhaps a little unintuitive.

**Comment by hasB4K** [comment]
Oh okay, good to know! :smiley:
I'm closing this then.
