### ISSUE TITLE
BUG: Illegal instruction: 4 on mid2010 Mac

### ISSUE THREAD

**Issue by lc3t35** [pandas-dev/pandas#33518]
#### Code Sample, a copy-pastable example

```python
Python 3.7.7 (default, Mar 26 2020, 10:32:53) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
Illegal instruction: 4
(Pandas) iMac:~ laurent$ sysctl -a | grep machdep.cpu.features
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 CX16 TPR PDCM SSE4.1 SSE4.2 POPCNT
(Pandas) iMac:~ laurent$ conda list numpy
# packages in environment at /Users/laurent/opt/anaconda3/envs/Pandas:
#
# Name                    Version                   Build  Channel
numpy                     1.18.1           py37h7241aed_0  
numpy-base                1.18.1           py37h6575580_1  
```

#### Problem description

With a mid 2010 Mac, OSX 10.13.6 (High Sierra)

  ```
Identifiant du modèle :	iMac11,3
  Nom du processeur :	Intel Core i5
  Vitesse du processeur :	2,8 GHz
  Nombre de processeurs :	1
  Nombre total de cœurs :	4
  Cache de niveau 2 (par cœur) :	256 Ko
  Cache de niveau 3 :	8 Mo
  Mémoire :	16 Go
  Version de la ROM de démarrage :	99.0.0.0.0
  Version SMC (système) :	1.59f2
```

`import pandas as pd`, crashes with `Illegal instruction: 4`

This problem is mentionned also here : 

https://github.com/conda/conda/issues/9678
https://github.com/das-developers/condaCDF/issues/1

and as it was detected when trying to run inside Anaconda/jupyter, the work in progress to solve is described here : 

https://discourse.jupyter.org/t/osx-10-13-6-kernelrestarter-restarting-kernel/3965/8

**Comment by TomAugspurger** [comment]
Do you see the same issue with just `import numpy`?

**Comment by lc3t35** [comment]
Yes,

````
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Illegal instruction: 4
````

I solved the problem by downgrading to numpy 1.17.4 with a specific Anaconda's environment as explained here : https://discourse.jupyter.org/t/osx-10-13-6-kernelrestarter-restarting-kernel/3965/10

**Comment by TomAugspurger** [comment]
Pandas imports numpy, so is there anything for pandas to do here?

**Comment by lc3t35** [comment]
@TomAugspurger yes pandas's users should be warned that they can't run anymore on these "old" Macs due to the default numpy version embedded in pandas by default. With this issue, they know now where the problem comes from and they are able to fix it.
Maybe the installation script of pandas can detect the hardware configuration (missing "VFX" in sysctl -a | grep machdep.cpu.features) and choose the needed numpy version 1.17.4 ?

**Comment by TomAugspurger** [comment]
We don't "embed" numpy. It sounds like this can / should be fixed upstream.

**Comment by lc3t35** [comment]
A little warning in the dependencies of https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html : 
````
`
1.13.3 (*)
(*) less than 1.17.4 for Macs that don't support VFX - check empty result for `sysctl -a | grep machdep.cpu.features | grep VFX`

**Comment by TomAugspurger** [comment]
I think we'll pass on that. I suspect this will be fixed in conda before
long making that unnecessary.
