### ISSUE TITLE
DownSampling Time Series Data using pandas

### ISSUE THREAD

**Issue by Solly7** [pandas-dev/pandas#33541]
Hi all, i am still new to machine learning , I have time series data as per below and i need tips/help on how to downsample it using scikit-learn. see my dummy data below ,Payment status is my label(0=missed, 1=paid), i need to downsample using time series strategy and keeping temporal order

```
Policy_no  Deduction_date    Payment_status
1               01-Jan-2019                      1
2               01-Jan-2019                      1
3               01-Jan-2019                      1
4               01-Jan-2019                      1
5               01-Jan-2019                      1
1               01-feb-2019                      1
2               01-feb-2019                      1
3               01-feb-2019                      0
4               01-feb-2019                      0
5               01-feb-2019                      0
1               01-mar-2019                     1
2               01-mar-2019                     1
3               01-mar-2019                     1
```

**Comment by vishnu-dev** [comment]
This is is a general question as such. This should be asked in StackOverflow.

**Comment by mroeschke** [comment]
Check out resample: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html

Also this usage questions would be better suited for StackOverflow
