### ISSUE TITLE
ENH: Use self values in Series groupby

### ISSUE THREAD

**Issue by vishnu-dev** [pandas-dev/pandas#33542]
#### Is your feature request related to a problem?

I wish I could use pandas to do

```
s = pd.Series([1,2,1,3,1,2])
s.groupby()
```
rather than

```
s.groupby(s)
```

#### Describe the solution you'd like

I would like pandas to interpret the series values as `grouper` when `by` or `level` is not provided.

#### API breaking implications

I can't think of any reason this will affect the API.

#### Describe alternatives you've considered

Grouping using series itself as `grouper`.

`s.groupby(s)`

**Comment by TomAugspurger** [comment]
I don't think the intent of that code is especially clear.

**Comment by WillAyd** [comment]
Hmm yea I am also -1 on this; there's also no equivalent on the DataFrame side of things AFAIK

**Comment by vishnu-dev** [comment]
I'm only talking about Series here. There is no need for an equivalent representation in DataFrame as both of them are different in their roots. Also, what other ways would you think that `s.groupby()` could be interpreted other than grouping by series values itself?

**Comment by TomAugspurger** [comment]
Dunno. I just don't find the intent of `s.groupby()` obvious.

We'll leave this open for a bit longer, but will close it unless there's more support.

**Comment by jreback** [comment]
-1 here as well; passing a grouper to s that is not the index of a actually is pretty common 
; removing tat ability not only would be a major breaking change but remove functionality

**Comment by vishnu-dev** [comment]
As many of you have a negative opinion on this, I'm closing it.
