### ISSUE TITLE
BUG: Series.apply() throws an error on empty series when dtype = pd.StringDtype

### ISSUE THREAD

**Issue by IDDT** [pandas-dev/pandas#33559]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
pd.Series(['a', 'b', 'c']).iloc[0:0].apply(lambda x: x) #works as expected
pd.Series(['a', 'b', 'c']).astype('string').iloc[0:0].apply(lambda x: x) #throws an exception
```

#### Problem description
Applying a function to an empty Series with dtype `pd.StringDtype` throws `ValueError: PandasArray must be 1-dimensional.`.

#### Expected Output
Apply does nothing.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.1.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.6.3-arch1-1
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.18.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.5 (dt dec pq3 ext lo64)
jinja2           : 2.11.2
IPython          : 7.13.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
</details>

**Comment by TomAugspurger** [comment]
Thanks for the report. Slightly smaller reproducer

```python
pd.Series(dtype="string", index=[])
```

We try to insert `np.array(<NA>)`.

In `_init_dict`

```python
    354         elif index is not None:
    355             # fastpath for Series(data=None). Just use broadcasting a scalar
    356             # instead of reindexing.
    357             values = na_value_for_dtype(dtype)
    358             keys = index
 ```

I'm not sure if that would need to change (special case length-0?) or whether `create_series_with_explicit_dtype` should change.
