### ISSUE TITLE
DOC: rename_axis 'columns' param

### ISSUE THREAD

**Issue by Toussaic** [pandas-dev/pandas#33564]
Example :
```python
import pandas as pd
import numpy as np

s1 = pd.Series(np.random.randn(3), name="First", index=['a', 'b', 'c'])
s1.rename(columns="My Column")
```

Except :
TypeError: rename_axis() got an unexpected keyword argument "columns"

Description :
The documentation shows a "columns" param which is not allowed for a Series. There should be a note to explain this parameter only apply for DataFrame.

Link :
https://github.com/pandas-dev/pandas/blob/3adf3340453d6704d4a2cb47058214cc697a7d29/pandas/core/generic.py#L1110-L1279

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.2.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : fr_FR.cp1252

pandas           : 1.0.3
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.3.post20200330
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 2.4.4
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by MarcoGorelli** [comment]
Thanks @Toussaic for the report - are you insterested in submitting a pull request? https://pandas.pydata.org/pandas-docs/stable/development/contributing.html

**Comment by benrhodeland** [comment]
take

**Comment by Toussaic** [comment]
> Thanks @Toussaic for the report - are you insterested in submitting a pull request? https://pandas.pydata.org/pandas-docs/stable/development/contributing.html

Sorry, I'm not a real dev.

But after reading other docstring, maybe there should be a wrapper in "series.py" with a different docstring, like for "series.py:rename". Don't know...

**Comment by TapanGujjar** [comment]
I would like to work on this issue if possible

**Comment by MarcoGorelli** [comment]
@TapanGujjar it seems @benrhodeland is already working on this, but there are other good first issues you're welcome to submit a pull request for!

**Comment by gabsmoreira** [comment]
Hello, is @benrhodeland on this issue? Because I would like to work on this as well.

**Comment by MarcoGorelli** [comment]
Given the silence, you're probably OK to take it - PRs are welcome!

**Comment by gabsmoreira** [comment]
Ok, thanks @MarcoGorelli . Should I add the explanation inside "Notes" or just after the parameter "index, columns" text?
