### ISSUE TITLE
appropriate converting without '1900-01-01'

### ISSUE THREAD

**Issue by BenbrahimMouad** [pandas-dev/pandas#33574]
hello everybody, i wish that you are in good healthy, so i have one little problem, i wanna to convert one column from my tabular csv (a lot of columns of time HH:MM:SS) so i see that a lot of my columns are object so i wanna to convert them to datetime64 with this method include in pandas library, 

`data['DT']=data['DT].apply(pd.to_datetime)` 
the problem that he showed me the actual date so i wanna just HH:MM:SS without date and preserving that their type format in datetime.
any kind of help if possible in my case.

**Comment by mroeschke** [comment]
`datetime64` inherently always includes the date portion.

If you want the time only as a string, you can use `data['DT'].apply(pd.to_datetime).dt.strftime(..)` to only view the time portion
