### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by GeyseR** [pandas-dev/pandas#33576]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
df = pd.DataFrame([
    {'id': 1},
    {'id': 2}
])
df2 = pd.DataFrame([
    {'id': 2, 'col1': 'text', 'col2': None}
])
df = pd.merge(df, df2, how='left', on=['id'])
print(df)

#      id  col1    col2
# 0   1   NaN   NaN
# 1   2   text    None

df = pd.DataFrame([
    {'id': 1},
    {'id': 2}
])
df2 = pd.DataFrame([
    {'id': 2, 'col2': None}
])
df = pd.merge(df, df2, how='left', on=['id'])
print(df)
#     id  col2
# 0   1  None
# 1   2  None
```

#### Problem description
Not sure is it a "real " bug or just an expected behavior of pandas. From the code fragment below you can see that with different input pandas fills empty columns with different empty values. 

#### Expected Output
```
#      id  col1    col2
# 0   1   NaN   None
# 1   2   text    None
```
For the first print statement

#### Output of ``pd.show_versions()``

<details>

import pandas as pd
pd.show_versions()
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.76-linuxkit
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8
pandas           : 1.0.3
numpy            : 1.18.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.3
Cython           : None
pytest           : 5.4.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.2.8
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.8.4 (dt dec pq3 ext lo64)
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.4.1
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : 1.2.8
numba            : None

</details>

**Comment by TomAugspurger** [comment]
I think this is roughly working as expected. None is a a bit strange for a missing value, and we have some inconsistencies with object dtype.

I'd recommend using the new string dtype, which has a single missing value (pd.NA)

```python

In [23]: df = pd.DataFrame([
    ...:     {'id': 1},
    ...:     {'id': 2}
    ...: ])
    ...: df2 = pd.DataFrame({
    ...:     'id': [2],
    ...:     'col1': pd.array(['text']),
    ...:     'col2': pd.array([pd.NA], dtype="string")
    ...: })
    ...:
    ...: pd.merge(df, df2, how='left', on=['id'])
    ...:
Out[23]:
   id  col1  col2
0   1  <NA>  <NA>
1   2  text  <NA>

```

**Comment by GeyseR** [comment]
Hi @TomAugspurger,

> None is a a bit strange for a missing value

In our projects we use self-written utilities for converting django querysets to pandas dataframes, that look like this (simplefied version):
```
def qs_to_df(qs, fields):
    return pd.DataFrame(qs.values(*fields))
```

Some of the fields obviously could be `None`. Basically that is the reason why we have a lot of Nones in our data. Do you think it is the invalid usage/conversion? Would you recommend converting all None values to np.nan?

**Comment by TomAugspurger** [comment]
I'd recommend using the new string dtype and pd.NA for string values.
