### ISSUE TITLE
ENH:  add row and column options to margin parameter in pd.DataFrame.pivot_table

### ISSUE THREAD

**Issue by pshMsGsAZL2n07ohWBCAGX9cC** [pandas-dev/pandas#33620]
#### Is your feature request related to a problem?

Currently, the margin parameter is a simply boolean value that controls showing totals for all rows **and** columns.  However, there are times when it is either necessary or  desirable to show grand totals for only rows or only columns.   I discovered this limitation when I had a pivot_table that was constructed using cumsum() over time.  As a result, the grand totals along one of the dimensions were incorrect, and I needed to use a less-than-ideal workaround solution.  While I absolutely love pandas (still in my first year with it), Excel has a simple checkbox setting to set grand totals.

#### Describe the solution you'd like

Rather than margins=True (or False), I would suggest changing the options to the following:  Both (i.e., True in current implementation), Row, Columns, or None (i.e., False).  If desired, the rows or columns could use the standard axis=0 or axis=1 terms.  Regardless of whether or not this enhancement happens, thank you for your efforts.  Pandas has been a wonderful discovery.

**Comment by TomAugspurger** [comment]
@pshMsGsAZL2n07ohWBCAGX9cC can you provide a reproducible example along with he expected output? See http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by pshMsGsAZL2n07ohWBCAGX9cC** [comment]
Sure, thanks for taking a look.

**Current Behavior**
```python
In [1]:
import pandas as pd
import numpy as np

data = {'Product': {0: 'Product A',
  1: 'Product A',
  2: 'Product A',
  3: 'Product B',
  4: 'Product B',
  5: 'Product B'},
 'Period': {0: '2018_H1',
  1: '2018_H2',
  2: '2019_H1',
  3: '2018_H1',
  4: '2018_H2',
  5: '2019_H1'},
 'Value': {0: 5.0, 1: 7.0, 2: np.nan, 3: 13.0, 4: 21.0, 5: 22.0}}

df = pd.DataFrame(data=data)

# Current behavior when margins=True.  If margins=False, both the "All" column and row don't appear
table = pd.pivot_table(df, values='Value', index='Product',
                    columns='Period', aggfunc='sum', margins=True)

print(table.to_markdown())

Out [1]:
| Product   |   2018_H1 |   2018_H2 |   2019_H1 |   All |
|:----------|----------:|----------:|----------:|------:|
| Product A |         5 |         7 |         0 |    12 |
| Product B |        13 |        21 |        22 |    56 |
| All       |        18 |        28 |        22 |    68 |

```
**Desired Behavior (both of these options, in addition to the current behavior)**
```python
In [2]:
# Desired Outcome #1:  Margins Option for Axis = 0 (rows).  Resulting in the dataframe below
desired_outcome1 = {'2018_H1': {'Product A': 5, 'Product B': 13, 'All': 18},
 '2018_H2': {'Product A': 7, 'Product B': 21, 'All': 28},
 '2019_H1': {'Product A': 0, 'Product B': 22, 'All': 22}}

print(pd.DataFrame.from_dict(data=desired_outcome1).to_markdown())

Out [2]:
|           |   2018_H1 |   2018_H2 |   2019_H1 |
|:----------|----------:|----------:|----------:|
| Product A |         5 |         7 |         0 |
| Product B |        13 |        21 |        22 |
| All       |        18 |        28 |        22 |

In [3]:
# Desired Outcome #2:  Margins Option for Axis = 1 (columns).  Resulting in the dataframe below
desired_outcome2 = {'2018_H1': {'Product A': 5, 'Product B': 13},
 '2018_H2': {'Product A': 7, 'Product B': 21},
 '2019_H1': {'Product A': 0, 'Product B': 22},
 'All': {'Product A': 12, 'Product B': 56}}

print(pd.DataFrame.from_dict(data=desired_outcome2).to_markdown())

Out [3]:
|           |   2018_H1 |   2018_H2 |   2019_H1 |   All |
|:----------|----------:|----------:|----------:|------:|
| Product A |         5 |         7 |         0 |    12 |
| Product B |        13 |        21 |        22 |    56 |
```

**Comment by mroeschke** [comment]
I think it's straightforward enough to drop the undesired column or row after the operation with `margins=True`.

Going to close due to lack of activity, but happy to reopen if this issue garners more community interest.
