### ISSUE TITLE
ENH: snapshot testing of dataframes

### ISSUE THREAD

**Issue by fkromer** [pandas-dev/pandas#33636]
#### Is your feature request related to a problem?

When testing dataframe manipulating functions defining explicit expected dataframes takes a lot of time.

#### Describe the solution you'd like

I've used [snapshottest](https://github.com/syrusakbary/snapshottest) to test GraphQl APIs. The same approach could be implemented in a pytest plugin for pandas as well.

#### API breaking implications

[this should provide a description of how this feature will affect the API]

#### Describe alternatives you've considered

[this should provide a description of any alternative solutions or features you've considered]

#### Additional context

[add any other context, code examples, or references to existing implementations about the feature request here]

```python
# Your code here, if applicable

```

**Comment by MarcoGorelli** [comment]
Thanks @fkromer for the report - could you please provide the complete code showing what you're doing? https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by fkromer** [comment]
@MarcoGorelli That does not really make sense in this case. This issue does not apply to testing the `DataFrame` functionality of `pandas` itself but applications making use of pandas `DataFrame` functionality. For example I've functions which manipulate `DataFrame`s in a data manipulation pipeline and have a signature like this: `def df_manipulation_func_a(df: pd.DataFrame, another_df: pdDataFrame) -> pd.DataFrame`. Right now when unit testing these functions I've to define the expected returned dataframe myself. This is a lot of boilerplate. Instead in analogy to snapshottesting a tool/pytest plugin could run the tests in `snapshot` mode first to run the tests, capture the functions output and write it into files. In usual execution mode thetoll/plugin compares the actual output of the tests with the output previously captured.

**Comment by MarcoGorelli** [comment]
OK, thanks for the details @fkromer . 

So, from what I've understood, this doesn't need to be implemented in pandas itself, it's a request for a pytest plugin

**Comment by fkromer** [comment]
Exactly. I know this issue is misplaced. But there was no better place to propose this. The issue is related to https://github.com/pandas-dev/pandas/issues/16567#issuecomment-619415662 where other functionality is discussed which would fit into some `pandas-dev/pytest-pandas` as well.

**Comment by MarcoGorelli** [comment]
Closing as this wouldn't go in pandas and there doesn't seem to have been any uptake from the folks here, but please do let us know if you implement this

**Comment by fkromer** [comment]
@MarcoGorelli Sure. This won't be soon but in case I can prioritize and implement this I'll let you know.

**Comment by clintmod** [comment]
It's worth noting that this works pretty well with `pytest` and `snapshottest`  a data frame:
```python
def test_something_works(snapshot): # snapshot is a pytest fixture from snapshottest
    data_frame = calc_something_and_return_pandas_dataframe()
    snapshot.assert_match(data_frame.to_csv(index=False), 'some_module_level_unique_name_for_the_snapshot')
```

**Comment by fkromer** [comment]
@clintmod Yepp. The problem is that `.csv` does not save the df meta data (types of rows/columns) and that multi rows/columnns are tricky. Instead I usually store the data into `.h5` instead. In any case you have to work with files which are not easy to read and diff. But right now I'm totally fine with implementing it this way.

**Comment by afouchet** [comment]
> It's worth noting that this works pretty well with `pytest` and `snapshottest` for a dataframe:

I have a use case where snapshottest do not work.
I need to assert almost equal.
So
``` snapshot.assert_match(df.to_csv(), "path_to_expected") ```
raises an Error

If I did a 
```
expected_df = pd.read_csv("path_to_expected")
pd.testing.assert_frame_equal(df, expected_df, check_exact=False)
```
It would work

**Comment by kdebrab** [comment]
FWIW, the pytest plugin [pytest-regressions](https://github.com/ESSS/pytest-regressions) provides a [dataframe_regression](https://pytest-regressions.readthedocs.io/en/latest/api.html#dataframe-regression) fixture that stores expected data files as a csv and uses them as baseline for future test runs, in other words it provides snapshot testing for pandas dataframes.

It's not perfect (e.g., dtypes are not checked), but it works well for many use cases:
* Tolerances for floats could be specified
* Multi-level rows work out of-the-box
* Multi-level columns are not supported, but a work-around is to flatten them first with `data.columns = data.columns.to_flat_index()`
