### ISSUE TITLE
BUG: Python any() on a dataframe is returning True always

### ISSUE THREAD

**Issue by Dergel0806** [pandas-dev/pandas#33669]
- [Yes ] I have checked that this issue has not already been reported.

- [ Yes] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
df = pd.DataFrame([[False, False],  [False, False]])
print(any(df))
print(df.any().any())
```

#### Problem description

Calling python `any()` on a pandas DataFrame return True even if all elements are False, which is counterintuitive and even misleading. A way that gives correct result is to call `.any().any()`.
  
**Example of use case:**  
I found this bug when I was using `isna()` and it lead me to a conclusion that there are some missing values, while that was not true.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.112+
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : C.UTF-8
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.3
numpy            : 1.18.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.3.post20200330
Cython           : 0.29.16
pytest           : 5.0.1
hypothesis       : 5.5.4
sphinx           : 2.4.4
blosc            : None
feather          : 0.4.0
xlsxwriter       : 1.2.8
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: 0.8.1
bs4              : 4.8.2
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.2.1
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : 0.16.0
pytables         : None
s3fs             : 0.4.1
scipy            : 1.4.1
sqlalchemy       : 1.3.15
tables           : 3.5.1
xarray           : 0.15.1
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.8
None

</details>

**Comment by jorisvandenbossche** [comment]
@Dergel0806 the problem is that `any`, a built-in python function, is not doing here what you expect it does, due to how iteration for a dataframe works. 

The `any` docstring says "Return True if bool(x) is True for any x in the iterable.". But, iterating through a DataFrame does not iterate through all flat values, it iterates through the "keys", i.e. the column names, and not through the flat values.

You can see a similar pattern when you would try to use `any` on a dict:

```
In [6]: any({'a': False, 'b': False})                                                                                                                                                                              
Out[6]: True
```

If you want to call "any" on all values, you can use the `df.any().any()` as you mentioned yourself, or use numpy's any:

```
In [9]: df = pd.DataFrame([[False, False],  [False, False]])

In [10]: np.any(df)   
Out[10]: False
```

**Comment by Dergel0806** [comment]
I see! Thank you very much for the clarification. I was assuming that is happens because `any()` take into account indexes or column names, but wanted to raise this in case it may be an issue.
