### ISSUE TITLE
BUG: Assertion error : Gaps in blk ref_locs in pandas profiling

### ISSUE THREAD

**Issue by saten25** [pandas-dev/pandas#33672]
Hi Everyone,

I think i am facing a similar kind of issue.
I have created a django utility that is using pandas profiling.

The steps that i am doing is python are-
1-Uploading a file
df = pd.read_csv(path)

2- Changing the datatypes of columns from objects to category
df.select_dtypes(['object']).apply(pd.Series.astype, dtype='category')], axis=1).reindex(df.columns, axis=1)

3- Separating continuous and categorical variables from the dataframe and sending this information to multiselect dropdown in HTML

4- As per user selection from continuous and categorical variables dropdown, storing the selections in form of list.
context['selectedContinousValues'] = request.POST.getlist('continous')
context['selectedCategoricalValues'] = request.POST.getlist('categorical')

5- Combining both list and keeping the list items from df.
Profiling_variables=context['selectedContinousValues']+context['selectedCategoricalValues']
print(Profiling_variables)
profile=df[Profiling_variables]

6- Using this selected df in pandas profiling
profile_final = ProfileReport(profile)

Error: Error is coming when profile_final is having all categorical variables. I am using pandas profiling version 2.6.
Please note that error is not hitting in following cases:
1- Selecting categorical variables only.
2- if we are not changing the datatypes of columns from objects to category. I have added this steps because i wanted to include a functionality where user could convert selected continuous variable to categorical variables. i tried to change them from continuous to object but as soon as this object variable(say eg: variable having values like 1,2,3,4,1,2,3,4,1,2,3,4 where i want to treat this variable as object) is being used by pandas profiling, it is considering this object variable as numeric in output. but i want to treat it as categories.

Request Method: | POST
-- | --
http://localhost:8000/selected-data/ |  
3.0.5 |  
AssertionError Gaps in blk ref_locs |  
C:\Users\myname\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\internals\managers.py in _rebuild_blknos_and_blklocs, line 231 |  
C:\Users\myname\AppData\Local\Continuum\anaconda3\python.exe |  
3.7.4 |  
['C:\Users\myname\Desktop\EDA Pandas Profiling V4\file-upload', 'C:\Users\myname\AppData\Local\Continuum\anaconda3\python37.zip', 'C:\Users\myname\AppData\Local\Continuum\anaconda3\DLLs', 'C:\Users\myname\AppData\Local\Continuum\anaconda3\lib', 'C:\Users\myname\AppData\Local\Continuum\anaconda3', 'C:\Users\myname\AppData\Local\Continuum\anaconda3\lib\site-packages', 'C:\Users\myname\AppData\Local\Continuum\anaconda3\lib\site-packages\django_crispy_forms-1.9.0-py3.7.egg', 'C:\Users\myname\AppData\Local\Continuum\anaconda3\lib\site-packages\win32', 'C:\Users\myname\AppData\Local\Continuum\anaconda3\lib\site-packages\win32\lib', 'C:\Users\myname\AppData\Local\Continuum\anaconda3\lib\site-packages\Pythonwin', 'C:\Users\myname\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\extensions']

**Comment by TomAugspurger** [comment]
This looks like an issue in pandas-profiling, not pandas, right?

**Comment by saten25** [comment]
Yes the issue i am facing is with pandas profiling.

Just an example below: I am uploading a file with 9000 records and 18 columns and getting error.

import pandas as pd
import numpy as np
from pandas_profiling import ProfileReport
from pandas_profiling.utils.cache import cache_file

df = pd.read_excel('filepath')

df.columns = df.columns.str.replace(" ","_")
df = pd.concat([
    df.select_dtypes([], ['object']),
    df.select_dtypes(['object']).apply(pd.Series.astype, dtype='category')], axis=1).reindex(df.columns, axis=1)

no_of_rows = len(df.columns)
data_qlt_df = pd.DataFrame(index=np.arange(0, no_of_rows),columns=('column_name', 'col_data_type','non_null_values','unique_values_count'))
for ind, cols in enumerate(df.columns):
    col_unique_count = df[cols].nunique()
    data_qlt_df.loc[ind] = [cols,df[cols].dtype,df[cols].count(),col_unique_count]

    cat_data = data_qlt_df[data_qlt_df['col_data_type']=='category']
    cat_data.reset_index(inplace=True)

    con_data = data_qlt_df[data_qlt_df['col_data_type']!='category']
    con_data.reset_index(inplace=True)

    Categorical = []
    for col in cat_data['column_name']:
        Categorical = Categorical + [col]

    Continuous = []
    for col in con_data['column_name']:
        Continuous = Continuous + [col]

profile=df[Categorical]

profile_final = ProfileReport(profile)

By running this code, i am hitting an error

Few warnings:
C:\Users\myname\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py:4238: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(**kwargs)

Error:

AssertionError                            Traceback (most recent call last)
<ipython-input-16-a3a8766b1d8d> in <module>
     21 profile=df[Categorical]
     22 
---> 23 profile_final = ProfileReport(profile)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\__init__.py in __init__(self, df, minimal, config_file, **kwargs)
     61 
     62         # Get dataset statistics
---> 63         description_set = describe_df(df)
     64 
     65         # Build report structure

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\model\describe.py in describe(df)
    631 
    632     # missing diagrams
--> 633     missing = get_missing_diagrams(df, table_stats)
    634 
    635     # Messages

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\model\describe.py in get_missing_diagrams(df, table_stats)
    505                         missing[name] = {
    506                             "name": settings["name"],
--> 507                             "matrix": missing_diagram(name)(df),
    508                         }
    509                 except ValueError as e:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas_profiling\visualisation\missing.py in missing_bar(data)
     68         color=hex_to_rgb(config["html"]["style"]["primary_color"].get(str)),
     69         fontsize=get_font_size(data),
---> 70         labels=labels,
     71     )
     72     for ax0 in plt.gcf().get_axes():

~\AppData\Local\Continuum\anaconda3\lib\site-packages\missingno\missingno.py in bar(df, figsize, fontsize, labels, log, color, inline, filter, n, p, sort, ax)
    224     df = nullity_filter(df, filter=filter, n=n, p=p)
    225     df = nullity_sort(df, sort=sort, axis='rows')
--> 226     nullity_counts = len(df) - df.isnull().sum()
    227 
    228     if ax is None:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py in isnull(self)
   4722     @Appender(_shared_docs["isna"] % _shared_doc_kwargs)
   4723     def isnull(self):
-> 4724         return super().isnull()
   4725 
   4726     @Appender(_shared_docs["notna"] % _shared_doc_kwargs)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\generic.py in isnull(self)
   7320     @Appender(_shared_docs["isna"] % _shared_doc_kwargs)
   7321     def isnull(self):
-> 7322         return isna(self).__finalize__(self)
   7323 
   7324     _shared_docs[

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py in isna(obj)
    120     Name: 1, dtype: bool
    121     """
--> 122     return _isna(obj)
    123 
    124 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py in _isna_new(obj)
    147         return _isna_ndarraylike(obj)
    148     elif isinstance(obj, ABCGeneric):
--> 149         return obj._constructor(obj._data.isna(func=isna))
    150     elif isinstance(obj, list):
    151         return _isna_ndarraylike(np.asarray(obj, dtype=object))

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\internals\managers.py in isna(self, func, **kwargs)
    552 
    553     def isna(self, func, **kwargs):
--> 554         return self.apply("apply", func=func, **kwargs)
    555 
    556     def where(self, **kwargs):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\internals\managers.py in apply(self, f, axes, filter, do_integrity_check, consolidate, **kwargs)
    442             return self.make_empty(axes or self.axes)
    443         bm = self.__class__(
--> 444             result_blocks, axes or self.axes, do_integrity_check=do_integrity_check
    445         )
    446         bm._consolidate_inplace()

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\internals\managers.py in __init__(self, blocks, axes, do_integrity_check)
    145         self._consolidate_check()
    146 
--> 147         self._rebuild_blknos_and_blklocs()
    148 
    149     def make_empty(self, axes=None):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\internals\managers.py in _rebuild_blknos_and_blklocs(self)
    229 
    230         if (new_blknos == -1).any():
--> 231             raise AssertionError("Gaps in blk ref_locs")
    232 
    233         self._blknos = new_blknos

AssertionError: Gaps in blk ref_locs

**Comment by TomAugspurger** [comment]
I'd recommend opening an issue on the pandas profiling repo. If there's an issue here in pandas we'll reopen this.
