### ISSUE TITLE
BUG: Multiplication of two serieses changes the the timezone from the given serieses

### ISSUE THREAD

**Issue by eyjay-ok** [pandas-dev/pandas#33671]
(since this is my first bug report I am happy for any feedback :) )

```python
import pandas as pd

cet_idx = pd.date_range(start=pd.to_datetime('today').normalize(), periods=10, freq='15min', tz='CET')
utc_idx = cet_idx.tz_convert('utc')

cet_series = pd.Series(data=2, index=cet_idx)
utc_series = pd.Series(data=2, index=utc_idx)

print(cet_series.index.tz)
>> <DstTzInfo 'CET' CET+1:00:00 STD>

out_series = utc_series * cet_series   # The output is irrelevant 

print(cet_series.index.tz)
>> <UTC>
```

#### Problem description

The timezone of the series 'cet_series' changes by the multiplication. Since it is only an input series the timezone should stay the same.

#### Expected Output
```python
... # the same initialization as above

print(cet_series.index.tz)
>> <DstTzInfo 'CET' CET+1:00:00 STD>

utc_series * cet_series   # The output is irrelevant 

print(cet_series.index.tz)
>> <DstTzInfo 'CET' CET+1:00:00 STD>
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.3.0-46-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.1
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 2.4.4
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.13
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by TomAugspurger** [comment]
Thanks for the report. Confirmed on master.

@eyjay-ok do you know if this happened in pandas 0.25?

**Comment by eyjay-ok** [comment]
Yes, it was the same behavior in Pandas 0.25.1
I also tested it in pandas 0.24.0 and it was also the same (the output was a bit different but still the timezone was changed to UTC)

**Comment by mroeschke** [comment]
Thanks for the report.

This is the expected behavior. Please see https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#working-with-time-zones

> Operations between Series in different time zones will yield UTC Series, aligning the data on the UTC timestamps:

**Comment by TomAugspurger** [comment]
@mralgos I think the surprising behavior is that one of the operands (`cet_series`) is mutated so that it's index changes from CET to UTC.

**Comment by mroeschke** [comment]
Ah that is really weird behavior. Yes, that definitely looks like a bug. Sorry for reading the issue too quickly.

**Comment by mroeschke** [comment]
This fixes the issue locally:

```
(pandas-dev) matthewroeschke:pandas-mroeschke matthewroeschke$ git diff
diff --git a/pandas/core/ops/__init__.py b/pandas/core/ops/__init__.py
index 9a7c9fdad..048eb6cc5 100644
--- a/pandas/core/ops/__init__.py
+++ b/pandas/core/ops/__init__.py
@@ -380,7 +380,7 @@ def _align_method_SERIES(left, right, align_asobject=False):
                 left = left.astype(object)
                 right = right.astype(object)

-            left, right = left.align(right, copy=False)
+            left, right = left.align(right, copy=True)

     return left, right
```

Always copying seems unnecessary though. Maybe we should set `copy=True` for extentionarray indexes?

**Comment by phofl** [comment]
> Not sure if _always_ copying is necessary though. Maybe we should set `copy=True` for Extension Array indexes?

We could set copy=True if the indices at this point:

https://github.com/pandas-dev/pandas/pandas/core/generic.py#L8486-8491

are not equal. (else block). This works locally.
