### ISSUE TITLE
Inconsistent retrieval of DataFrame columns as Series.

### ISSUE THREAD

**Issue by geppi** [pandas-dev/pandas#33675]
1. Retrieve a DataFrame column by attribute as a Series.
2. Modify an element of this series.
3. As expected the modification has no effect on the original DataFrame.
4. But it changes the Series that is retrieved from a column by attribute or with the 'loc' method.
5. In contrast the Series retrieved from a column using the 'iloc' method is still the original.

This is at least inconsistent. However, I would also expect to see no change of the retrieved Series under point 4.

```python
import pandas as pd
pd.show_versions()
```

    
    INSTALLED VERSIONS
    ------------------
    commit           : None
    python           : 3.7.4.final.0
    python-bits      : 64
    OS               : Windows
    OS-release       : 10
    machine          : AMD64
    processor        : Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
    byteorder        : little
    LC_ALL           : None
    LANG             : None
    LOCALE           : None.None
    
    pandas           : 1.0.3
    numpy            : 1.18.1
    pytz             : 2019.3
    dateutil         : 2.8.1
    pip              : 20.0.2
    setuptools       : 40.8.0
    Cython           : None
    pytest           : None
    hypothesis       : None
    sphinx           : None
    blosc            : None
    feather          : None
    xlsxwriter       : 1.2.8
    lxml.etree       : 4.5.0
    html5lib         : None
    pymysql          : None
    psycopg2         : None
    jinja2           : 2.10.3
    IPython          : 7.11.1
    pandas_datareader: None
    bs4              : None
    bottleneck       : None
    fastparquet      : None
    gcsfs            : None
    lxml.etree       : 4.5.0
    matplotlib       : 3.1.3
    numexpr          : None
    odfpy            : None
    openpyxl         : 3.0.3
    pandas_gbq       : None
    pyarrow          : None
    pytables         : None
    pytest           : None
    pyxlsb           : None
    s3fs             : None
    scipy            : None
    sqlalchemy       : None
    tables           : None
    tabulate         : None
    xarray           : None
    xlrd             : None
    xlwt             : None
    xlsxwriter       : 1.2.8
    numba            : None
    

```python
df = pd.DataFrame([[1,2], [3,4]], index= ['a', 'b'], columns=['A', 'B'])
df
```

<div>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A</th>
      <th>B</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>a</th>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <th>b</th>
      <td>3</td>
      <td>4</td>
    </tr>
  </tbody>
</table>
</div>

```python
s = df.A
s
```

    a    1
    b    3
    Name: A, dtype: int64

```python
s['c'] = 5
s
```

    a    1
    b    3
    c    5
    Name: A, dtype: int64

```python
df
```

<div>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A</th>
      <th>B</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>a</th>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <th>b</th>
      <td>3</td>
      <td>4</td>
    </tr>
  </tbody>
</table>
</div>

```python
df.A
```

    a    1
    b    3
    c    5
    Name: A, dtype: int64

```python
df.loc[:,'A']
```

    a    1
    b    3
    c    5
    Name: A, dtype: int64

```python
df.iloc[:,0]
```

    a    1
    b    3
    Name: A, dtype: int64

```python
s['b'] = 2
```

```python
s
```

    a    1
    b    2
    c    5
    Name: A, dtype: int64

```python
df
```

<div>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A</th>
      <th>B</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>a</th>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <th>b</th>
      <td>3</td>
      <td>4</td>
    </tr>
  </tbody>
</table>
</div>

```python
df.A
```

    a    1
    b    2
    c    5
    Name: A, dtype: int64

```python
df.loc[:,'A']
```

    a    1
    b    2
    c    5
    Name: A, dtype: int64

```python
df.iloc[:,0]
```

    a    1
    b    3
    Name: A, dtype: int64

```python

```

**Comment by jbrockmendel** [comment]
I think the underlying issue here is that we have _getitem_cache for label-based lookups but no analogous _igetitem_cache.  So either making _igetitem_cache or getting rid of _getitem_cache should do the trick.

**Comment by geppi** [comment]
That boils down to the question if the retrieval of a DataFrame column or row should return a copy or a reference. I'm relatively new to pandas and therefore might have a rather naive look on this but I would expect a copy and my gut feeling tells me that a copy would have less side effects.
It's a little bit strange when the retrieval of a column delivers something different from the column as shown by the \_\_repr__ method of the DataFrame.
Also assignment to an element of a new row in the DataFrame does extend the DataFrame and create NaN values for the other elements of the new row. In the context of my simple example above:
```python
df.loc['c','A'] = 7
df
```




<div>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A</th>
      <th>B</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>a</th>
      <td>1.0</td>
      <td>2.0</td>
    </tr>
    <tr>
      <th>b</th>
      <td>3.0</td>
      <td>4.0</td>
    </tr>
    <tr>
      <th>c</th>
      <td>7.0</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
</div>

If the Series 's' in my example would be a reference to the DataFrame column I would expect the same to happen when I add an element to the Series 's'.
Currently it behaves like a copy of the DataFrame column and the DataFrame is not extended.
