### ISSUE TITLE
BUG: repr of Categorical does not distinguish int and str.

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#33676]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
>>> pd.Categorical([1, "2", 3, 4])
[1, 2, 3, 4]
Categories (4, object): [1, 3, 4, 2]
```

#### Problem description

does not show the string elements quoted. This is inconsistent with numpy.

```python
>>> np.array([1, "2", 3, 4], dtype="object")
array([1, '2', 3, 4], dtype=object)
```
#### Expected Output

```python
>>> pd.Categorical([1, "2", 3, 4])
[1, '2', 3, 4]
Categories (4, object): [1, 3, 4, '2']
```

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by MarcoGorelli** [comment]
Does this mean that some of the existing tests need to change?

For example
```python
    def test_unicode_print(self):
        c = Categorical(["aaaaa", "bb", "cccc"] * 20)
        expected = """\
[aaaaa, bb, cccc, aaaaa, bb, ..., bb, cccc, aaaaa, bb, cccc]
Length: 60
Categories (3, object): [aaaaa, bb, cccc]"""

        assert repr(c) == expected
```

should become
```python
    def test_unicode_print(self):
        c = Categorical(["aaaaa", "bb", "cccc"] * 20)
        expected = """\
['aaaaa', 'bb', 'cccc', 'aaaaa', 'bb', ..., 'bb', 'cccc', 'aaaaa', 'bb', 'cccc']
Length: 60
Categories (3, object): ['aaaaa', 'bb', 'cccc']"""

        assert repr(c) == expected
```

**Comment by simonjayhawkins** [comment]
> Does this mean that some of the existing tests need to change?

Maybe more discussion needed, but IMO the current representation of the string categories without quotes is a bug and not pythonic. However, it is also a breaking change. need to see what others think as I don't know the history.

**Comment by MarcoGorelli** [comment]
This isn't limited to Categorical though, is it?
```python
>>> pd.DataFrame(['a', 'b', 2])
   0
0  a
1  b
2  2
```

**Comment by simonjayhawkins** [comment]
In the OP, the values are shown inside square brackets, so for me, this implies a list literal which I would expect could be copy and pasted. I do find it frustrating that the reprs of many pandas objects cannot be used to create an object, but that's another issue.

For the Series case, the values are not shown inside square brackets, so the strings shown without quotes is more acceptable.
