### ISSUE TITLE
BUG: pd.Series.value_counts with pd.NA implies ValueError

### ISSUE THREAD

**Issue by mariusgarbowski** [pandas-dev/pandas#33681]
- [ x] I have checked that this issue has not already been reported.

- [x ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

The new pd.NA seems to have an issues with the pandas.Series method value_counts:
#### Code Sample, a copy-pastable example

```python
import pandas as pd
import numpy as np
s1 = pd.Series([np.nan, np.nan], dtype='float')
s2 = pd.Series([None, None], dtype='str')
s3 = pd.Series([pd.NA, pd.NA], dtype='Int64')

print(s1.value_counts()) 
print(s2.value_counts())
print(s3.value_counts()))
```

#### Problem description
The current output (with the new pd.NA values) raises a ValueError (see below). I would expect a blank pandas.Series as output (analogous to np.nan or None values with it's dtypes).
This issues regards pandas/python in my home pc as well as python installed on an ubuntu EC2 instance (see below).

#### Current Output:
Series([], dtype: int64)
Series([], dtype: int64)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-a787e255adb5> in <module>
      1 print(s1.value_counts())
      2 print(s2.value_counts())
----> 3 print(s3.value_counts())

~\Miniconda3\lib\site-packages\pandas\core\base.py in value_counts(self, normalize, sort, ascending, bins, dropna)
   1233             normalize=normalize,
   1234             bins=bins,
-> 1235             dropna=dropna,
   1236         )
   1237         return result

~\Miniconda3\lib\site-packages\pandas\core\algorithms.py in value_counts(values, sort, ascending, normalize, bins, dropna)
    726 
    727     if sort:
--> 728         result = result.sort_values(ascending=ascending)
    729 
    730     if normalize:

~\Miniconda3\lib\site-packages\pandas\core\series.py in sort_values(self, axis, ascending, inplace, kind, na_position, ignore_index)
   2960         idx = ibase.default_index(len(self))
   2961 
-> 2962         argsorted = _try_kind_sort(arr[good])
   2963 
   2964         if is_list_like(ascending):

~\Miniconda3\lib\site-packages\pandas\core\series.py in _try_kind_sort(arr)
   2946             try:
   2947                 # if kind==mergesort, it can fail for object dtype
-> 2948                 return arr.argsort(kind=kind)
   2949             except TypeError:
   2950                 # stable sort not available for object dtype

~\Miniconda3\lib\site-packages\pandas\core\arrays\base.py in argsort(self, ascending, kind, *args, **kwargs)
    514         ascending = nv.validate_argsort_with_ascending(ascending, args, kwargs)
    515 
--> 516         result = nargsort(self, kind=kind, ascending=ascending, na_position="last")
    517         return result
    518 

~\Miniconda3\lib\site-packages\pandas\core\sorting.py in nargsort(items, kind, ascending, na_position)
    261 
    262     if is_extension_array_dtype(items):
--> 263         items = items._values_for_argsort()
    264     else:
    265         items = np.asanyarray(items)

~\Miniconda3\lib\site-packages\pandas\core\arrays\integer.py in _values_for_argsort(self)
    500         """
    501         data = self._data.copy()
--> 502         data[self._mask] = data.min() - 1
    503         return data
    504 

~\Miniconda3\lib\site-packages\numpy\core\_methods.py in _amin(a, axis, out, keepdims, initial, where)
     32 def _amin(a, axis=None, out=None, keepdims=False,
     33           initial=_NoValue, where=True):
---> 34     return umr_minimum(a, axis, None, out, keepdims, initial, where)
     35 
     36 def _sum(a, axis=None, dtype=None, out=None, keepdims=False,

ValueError: zero-size array to reduction operation minimum which has no identity

#### Expected Output
Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)

Implemented temporal workaround:

```python
def get_value_counts(s: pd.Series) -> pd.Series:
    try:
        unique_values = s.value_counts()

    except ValueError:
        unique_values = pd.Series(dtype='int64')

    return unique_values
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.3
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.3.post20200330
Cython           : None
pytest           : 5.4.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.8.5 (dt dec pq3 ext lo64)
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.4.1
pyxlsb           : None
s3fs             : 0.4.0
scipy            : 1.4.1
sqlalchemy       : 1.3.16
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : None
numba            : None

Same issue on Ubutnu Server:

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-1065-aws
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8
pandas           : 1.0.3
numpy            : 1.16.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.0.3
setuptools       : 41.0.0
Cython           : None
pytest           : 5.4.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.3.4
html5lib         : None
pymysql          : None
psycopg2         : 2.8.4 (dt dec pq3 ext lo64)
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.4
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.4.1
pyxlsb           : None
s3fs             : 0.4.0
scipy            : None
sqlalchemy       : 1.3.13
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by TomAugspurger** [comment]
I believe that all these work on master.

**Comment by dsaxton** [comment]
I'm seeing that as well:

```python
[ins] In [1]: import pandas as pd
         ...: import numpy as np
         ...: s1 = pd.Series([np.nan, np.nan], dtype='float')
         ...: s2 = pd.Series([None, None], dtype='str')
         ...: s3 = pd.Series([pd.NA, pd.NA], dtype='Int64')
         ...:
         ...: print(s1.value_counts())
         ...: print(s2.value_counts())
         ...: print(s3.value_counts())
Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: Int64)
```
