### ISSUE TITLE
DOC: pd.Categorical does not throw ValueError, converts to NaN instead

### ISSUE THREAD

**Issue by behrenhoff** [pandas-dev/pandas#33696]
My problem might be a bug or just a documentation issue. Consider this two-liner:

```python
import pandas as pd
print(pd.Categorical([*'abc'], categories=[*'ab']))
```
The output is:
```
[a, b, NaN]
Categories (2, object): [a, b]
```

According to the docs:

> All values of the Categorical are either in categories or np.nan. **Assigning values outside of categories will raise a ValueError.**

And further:
> Raises ValueError  If the categories do not validate.

However, no ValueError is thrown, instead 'c' is converted to NaN silently.

Either this is intended - then the docu needs update.
Or it is not intended - then it is a bug - and it should throw a ValueError("c not in categories")

Tested with Pandas 0.25.3 and 1.0.3 on Python 3.6.9.

I tried in a fresh venv:
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-96-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : de_DE.UTF-8
LOCALE           : de_DE.UTF-8

pandas           : 1.0.3
numpy            : 1.18.3
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 9.0.1
setuptools       : 39.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 0.999999999
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by behrenhoff** [comment]
sorry, its a documentation issue. Documentation also contains " If categories are given, values not in categories will be replaced with NaN.".

**Comment by behrenhoff** [comment]
Maybe I should reopen this - can this be It in unclear when a ValueError is thrown. Probably a documentation issue.

**Comment by dsaxton** [comment]
I think the documentation is referring to setting the value of an existing Categorical rather than construction of a new one:
```python
[ins] In [1]: cat = pd.Categorical(["a", "b", "c"], categories=["a", "b"])                                                                                                                                   

[ins] In [2]: cat[2] = "c"                                                                                                                                                                                   
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-b89f99137006> in <module>
----> 1 cat[2] = "c"

~/pandas/pandas/core/arrays/categorical.py in __setitem__(self, key, value)
   2036         # something to np.nan
   2037         if len(to_add) and not isna(to_add).all():
-> 2038             raise ValueError(
   2039                 "Cannot setitem on a Categorical with a new "
   2040                 "category, set the categories first"

ValueError: Cannot setitem on a Categorical with a new category, set the categories first
```

**Comment by Rish001** [comment]
Can I update the error message?

**Comment by dsaxton** [comment]
> Can I update the error message?

@Rish001 I think that the error message is fine here, this was more a question about the documentation. But since the documentation for the values argument reads

> The values of the categorical. If categories are given, values not in categories will be replaced with NaN.

we could probably consider this resolved.
