### ISSUE TITLE
ENH: Integrate pdpipe into pandas

### ISSUE THREAD

**Issue by marctorsoc** [pandas-dev/pandas#33700]
### Is your feature request related to a problem?

I wish I could create pipelines in pandas, the way I do for sklearn. This seems to be feasible using pdpipe https://pdpipe.github.io/pdpipe/, so I wonder why that is not directly available in pandas

### Describe the solution you'd like

I'd like being able to write stuff like:

```
>>> pipeline = pdp.PdPipeline([drop_name, binar_label, map_job])
 >>> print(pipeline)
  A pdpipe pipeline:
  [ 0]  Drop column Name
  [ 1]  OneHotEncode Label
  [ 2]  Map values of column Job with {'Part': True, 'Full': True, 'No': False}.
```

and
```
pipeline += pdp.PdPipeline([pdp.ColRename({"Job": "Employed"})])
```

but directly with pandas stuff

### API breaking implications

I'm not sure about this, tbh

### Describe alternatives you've considered

Just use the library xD

**Comment by mroeschke** [comment]
I don't think it's very likely we'll add this directly into the pandas library. 

In pandas, our version of a pipeline is [method chaining](https://tomaugspurger.github.io/method-chaining.html) with utilization of our own pipe method if needed https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pipe.html

**Comment by marctorsoc** [comment]
yeah I know that. The problem is that you need to write wrappers for Dataframe methods. Imagine I want to do:

```
df.drop("z", axis=1).reset_index(drop=True).sort_values(by="y").rename(columns={"x": "keys", "y": "values"}).dropna().iloc[:, [2, 1]]
```

I don't think you can do this with pipe unless you create a bunch of wrappers, and even in such a case, the code will look like:

```
df.pipe(a).pipe(b).pipe(c) ....
```

but it's not possible to have a **pipeline** and do it

```
df.apply(pipeline)
```

and that nice pipeline being sklearn compatible, sliceable, and being able to concatenate to other pipelines.

Is this correct or am I missing something?

**Comment by jreback** [comment]
this library uses pandas and provides a completely different api, which is fine but not for pandas proper which already has a well defined and familiar api. we are not likely to make major changes or provide alternate apis inside pandas.
