### ISSUE TITLE
DEP: bump numpy min version?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#33718]
We currently require 1.13.3 which was released 2017-09-29.  The last bump was in 0.25.0 (#25554).

I think its time for another bump.  The release dates for the 1.x.0 and 1.x.MAX versions out there:

1.14.0 -> 2018-01-06
1.14.6 -> 2018-09-23
1.15.0 -> 2018-07-23
1.15.4 -> 2018-11-04
1.16.0 -> 2019-01-13
1.16.6 -> 2019-12-29
1.17.0 -> 2019-07-06
1.17.5 -> 2020-01-01

1.15.4 looks not-unreasonable to me.

**Comment by jreback** [comment]
+1 in bumping to 1.15.x

even 1.16.x is ok

**Comment by TomAugspurger** [comment]
According to https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule, NumPy 1.14 can / should be dropped after

**Comment by jorisvandenbossche** [comment]
I would also follow NEP29, which means np 1.14 for pandas 1.1 (and then can probably go to np 1.15 after pandas 1.1 is released)

**Comment by TomAugspurger** [comment]
@jorisvandenbossche doesn't NEP29 say we're already supposed to drop 1.14, since it's the next release after January 7, 2020?

**Comment by jorisvandenbossche** [comment]
Whoops, sorry, yes I should have said 1.15 and 1.16, instead of 1.14 and 1.15
