### ISSUE TITLE
BUG: Inconsistent behavior of `DataFrame.clip` when using with `loc`

### ISSUE THREAD

**Issue by narendramukherjee** [pandas-dev/pandas#33710]
- [CHECKED] I have checked that this issue has not already been reported.

- [ EXISTS on v1.0.3] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---
Pandas version:
```
In [9]: pd.__version__                                                          
Out[9]: '1.0.3'
```
`DataFrame` used through the example:
```
df = pd.DataFrame({"A":[-5, 8, 12, -9, 5, 3], 
                   "B":[-1, -4, 6, 4, 11, 3], 
                   "C":[11, 4, -8, 7, 3, -2]})
```
`DataFrame.clip` with `inplace=True` works fine when I run it on a single column pulled out with `loc`:
```
In [10]: df.loc[:, "C"].clip(lower=0, inplace=True)                             

In [11]: df                                                                     
Out[11]: 
    A   B   C
0  -5  -1  11
1   8  -4   4
2  12   6   0
3  -9   4   7
4   5  11   3
5   3   3   0
```
But if I pull out more than 1 column, this fails:
```
In [12]: df.loc[:, ["A", "B"]].clip(lower=0, inplace=True)                      

In [13]: df                                                                     
Out[13]: 
    A   B   C
0  -5  -1  11
1   8  -4   4
2  12   6   0
3  -9   4   7
4   5  11   3
5   3   3   0
```
So, `clip` doesn't work `inplace` when used on a dataframe subset with several columns (here pulled out with `loc`). 
**Note:** `clip` does work `inplace` when used on the entire dataframe. Just when used on a subset with `loc`, it doesn't work.
```
In [15]: df.clip(lower=0, inplace=True)                                                                                                                                                                     

In [16]: df                                                                                                                                                                                                 
Out[16]: 
    A   B   C
0   0   0  11
1   8   0   4
2  12   6   0
3   0   4   7
4   5  11   3
5   3   3   0
```

#### Output of ``pd.show_versions()``

<details>

In [14]: pd.show_versions()                                                     

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.3.0-46-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.3.post20200330
Cython           : 0.29.15
pytest           : 5.4.1
hypothesis       : 5.8.3
sphinx           : 2.4.4
blosc            : None
feather          : None
xlsxwriter       : 1.2.8
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: None
bs4              : 4.9.0
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.1.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.4.1
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.16
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.8
numba            : 0.49.0

</details>

**Comment by jreback** [comment]
you should be getting a `SettingWithCopy` warning. this is a changed operation and `inplace=True` is never recommended. Read the docs here: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#indexing-view-versus-copy
