### ISSUE TITLE
ENH: Control the escape scope of read_csv's escapechar

### ISSUE THREAD

**Issue by garylavayou** [pandas-dev/pandas#33720]
#### Is your feature request related to a problem?

So far, the `escapechar` (`\` by default) of `read_csv` method is used to escape the special meaning of all other characters for all columns.

#### Describe the solution you'd like

In my situation, I want the escape char to take effect only for quoted values, while it can be interpreted as normal character in some other non-quoted columns, like the following example:
```csv
..., "This is \"quoted\"",  C:\users\gary, bad value\, ...
```
The listed values are expected to be interpreted as `This is "quoted"`, `C:\users\gary` and `bad value\`. But now, the `read_csv` method will interpret all columns, resulting in `This is "quoted"` and  `C:usersgary` (`\` is removed), and the separater `,` after the `bad value\` will be render out by the escapechar `\` at the end of `bad value\`, making the `bad value` concatenated with the next column's value, which is not right.

Therefore, it would be better to add an option to determine whether `escape_all` or `escape_in_quote`.

#### API breaking implications

Adding an option will not affect the default behavior of `read_csv` method.

#### Describe alternatives you've considered

Adding an option `escape_scope='escape_all' | 'escape_in_quote'`, with `escape_all` as default option.

**Comment by gutzbenj** [comment]
Dear @garylavayou ,

I am currently running into the same problem. Have you found an intermediate solution to this problem?

Cheers
Benjamin

**Comment by mroeschke** [comment]
Thanks for the request, but it appears this hasn't gain traction in a while so closing
