### ISSUE TITLE
BUG: Exceptions not propagated from c_is_list_like in lib.pyx

### ISSUE THREAD

**Issue by shwina** [pandas-dev/pandas#33721]
Python exceptions originating in `c_is_list_like()` are not propagated as the function doesn't declare an exception value (`except -1`).

https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/lib.pyx#L988

**Comment by jbrockmendel** [comment]
Can you give an example of where the problem shows up?

**Comment by shwina** [comment]
@jbrockmendel Unfortunately I'm not able to reproduce easily at this moment. I left a comment [here](https://github.com/pandas-dev/pandas/pull/33723#discussion_r413099393) that hopefully 
sheds some light on the issue.
