### ISSUE TITLE
BUG: argument 'axis=1' is silently ignored in DataFrame diff() method when dtype is nullable integer (Int64)

### ISSUE THREAD

**Issue by geppi** [pandas-dev/pandas#33726]
```python
import numpy as np
import pandas as pd
pd.show_versions()
```

    
    INSTALLED VERSIONS
    ------------------
    commit           : None
    python           : 3.7.4.final.0
    python-bits      : 64
    OS               : Windows
    OS-release       : 10
    machine          : AMD64
    processor        : Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
    byteorder        : little
    LC_ALL           : None
    LANG             : None
    LOCALE           : None.None
    
    pandas           : 1.0.3
    numpy            : 1.18.1
    pytz             : 2019.3
    dateutil         : 2.8.1
    pip              : 20.0.2
    setuptools       : 40.8.0
    Cython           : None
    pytest           : None
    hypothesis       : None
    sphinx           : None
    blosc            : None
    feather          : None
    xlsxwriter       : 1.2.8
    lxml.etree       : 4.5.0
    html5lib         : None
    pymysql          : None
    psycopg2         : None
    jinja2           : 2.10.3
    IPython          : 7.11.1
    pandas_datareader: None
    bs4              : None
    bottleneck       : None
    fastparquet      : None
    gcsfs            : None
    lxml.etree       : 4.5.0
    matplotlib       : 3.1.3
    numexpr          : None
    odfpy            : None
    openpyxl         : 3.0.3
    pandas_gbq       : None
    pyarrow          : None
    pytables         : None
    pytest           : None
    pyxlsb           : None
    s3fs             : None
    scipy            : None
    sqlalchemy       : None
    tables           : None
    tabulate         : None
    xarray           : None
    xlrd             : None
    xlwt             : None
    xlsxwriter       : 1.2.8
    numba            : None
    

```python
df = pd.DataFrame([[1,2], [3,np.nan]], index= ['a', 'b'], columns=['A', 'B']).convert_dtypes()
df
```

<div>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A</th>
      <th>B</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>a</th>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <th>b</th>
      <td>3</td>
      <td>&lt;NA&gt;</td>
    </tr>
  </tbody>
</table>
</div>

```python
df.dtypes
```

    A    Int64
    B    Int64
    dtype: object

```python
df.diff(axis=0)
```

<div>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A</th>
      <th>B</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>a</th>
      <td>&lt;NA&gt;</td>
      <td>&lt;NA&gt;</td>
    </tr>
    <tr>
      <th>b</th>
      <td>2</td>
      <td>&lt;NA&gt;</td>
    </tr>
  </tbody>
</table>
</div>

```python
df.diff(axis=1)
```

<div>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A</th>
      <th>B</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>a</th>
      <td>&lt;NA&gt;</td>
      <td>&lt;NA&gt;</td>
    </tr>
    <tr>
      <th>b</th>
      <td>2</td>
      <td>&lt;NA&gt;</td>
    </tr>
  </tbody>
</table>
</div>

Conversion to float fixes the issue

```python
df = df.astype(float)
df
```

<div>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A</th>
      <th>B</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>a</th>
      <td>1.0</td>
      <td>2.0</td>
    </tr>
    <tr>
      <th>b</th>
      <td>3.0</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
</div>

```python
df.diff(axis=1)
```

<div>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A</th>
      <th>B</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>a</th>
      <td>NaN</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>b</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
</div>

```python

```

**Comment by dsaxton** [comment]
I think this is fixed on master, apparently by https://github.com/pandas-dev/pandas/pull/32995

```python
[ins] In [2]: df = pd.DataFrame([[1,2], [3,np.nan]], index= ['a', 'b'], columns=['A', 'B']).convert_dtypes()                                                                                                 

[ins] In [3]: df                                                                                                                                                                                             
Out[3]: 
   A     B
a  1     2
b  3  <NA>

[ins] In [4]: df.diff(axis=0)                                                                                                                                                                                
Out[4]: 
      A     B
a  <NA>  <NA>
b     2  <NA>

[ins] In [5]: df.diff(axis=1)                                                                                                                                                                                
Out[5]: 
      A     B
a  <NA>     1
b  <NA>  <NA>

[ins] In [6]: pd.__version__                                                                                                                                                                                 
Out[6]: '1.1.0.dev0+1336.g652a39f50'
```

cc @jbrockmendel

**Comment by geppi** [comment]
Thanks.

Then I can close this one.
