### ISSUE TITLE
API: deprecate silently casting np.nan to NaT

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#33731]
When doing a setitem into a dt64/td64 Series, we cast `np.nan` to `NaT`.  The alternative would be to cast to object dtype and set np.nan unchanged.

Similarly anything that ends up calling `is_valid_nat_for_dtype` will allow through np.nan which ends up getting cast to NaT.

We should consider deprecating this behavior and requiring users to pass NaT directly.

**Comment by jreback** [comment]
this is pretty convenient from a user POV
so -0 on depreciating

**Comment by AlexKirko** [comment]
Can't speak for others, but I expect NaN and NaT to be implicitly cast into each other when converting between number and date array-likes. Conceptually, they are both implementations of "not-a-valid-object-of-relevant-type".

**Comment by jbrockmendel** [comment]
woops, i opened these in the wrong order.  closing.
