### ISSUE TITLE
ENH: support for Python data structures containing Pandas DataFrames/Series

### ISSUE THREAD

**Issue by xuancong84** [pandas-dev/pandas#33738]
It is great that you have implemented to_csv and read_csv() to export and import tables in CSV format. It would be even better to be able to serialize/deserialize Python data structures such as list and dict containing DataFrames/Series. For example, something like [this](https://github.com/xuancong84/pandas-serializer).

Would that be possible? Thanks!

**Comment by jreback** [comment]
-1 on this as general serialization like this out of scope 

better handled by pyarrow or plain old pickle

I don’t view human readability in a custom format as a plus

**Comment by xuancong84** [comment]
-1 on @jreback , you seem to view everything as negative and simply refuse to implement anything useful to the general public, your attitude is very negative and arrogant. Okay, so be it.

I am pretty sure that people would like to see something like pd.serialize and pd.deserialize
