### ISSUE TITLE
pandas statistics

### ISSUE THREAD

**Issue by nschloe** [pandas-dev/pandas#33744]
Just a small heads-up of how well pandas is doing. I wrote [hotware](https://github.com/nschloe/hotware) to check the popularity of software on GitHub and StackOverflow, and in the scientific Python department, pandas is clearly number 1:

![pd](https://user-images.githubusercontent.com/181628/80079616-cfe52400-8550-11ea-95a6-cdcab06530c1.png)
https://github.com/nschloe/hotware#scientific-python

You might want to use this in your next funding proposal. :smile_cat: 

Congrats on a great piece of software!

**Comment by mroeschke** [comment]
This is awesome! Thanks for sharing @nschloe
