### ISSUE TITLE
Can we reduce the size of file generated with empty_df.to_hdf() below 2MB?

### ISSUE THREAD

**Issue by mwouts** [pandas-dev/pandas#33759]
I store my dataframes on disk with `df.to_hdf()`, but to my surprise, even for an empty dataframe the resulting file size is 2MB. Is there a way to make it smaller? Thanks!
```python
import pandas as pd
empty_df = pd.DataFrame()
empty_df.to_hdf('empty_df.hdf', 'data')
```

NB: Versions tested: Pandas 0.21.1, Pandas 1.03.

**Comment by TomAugspurger** [comment]
@mwouts can you see how large an empty pytables file is?

**Comment by mwouts** [comment]
Hi @TomAugspurger , thank you for your answer. I am happy to dig this further, but must say that I am not familiar with `pytables`. But maybe just following the call stack, and finding what is the difference with the non-empty case, could help... let's see if I get an answer about how to do that on [twitter](https://twitter.com/marcwouts/status/1305159099429126147) :smile:

**Comment by jreback** [comment]
you should read the docs - this is a design feature of pytables itself and is not likely to change nor can pandas do anything

**Comment by mwouts** [comment]
I think I have something interesting - If I force a dtype on the empty indices then the files have a reasonable size. For instance, 
`pd.Series(index=pd.Index([]))` has a size on disk > 1MB, when `pd.Series(index=pd.Index([], dtype=int))` takes less than 10kB. 

The same is true for dataframes:
```python
import pandas as pd
import pytest


@pytest.mark.parametrize(
    "series",
    [
        # Size > 1MB
        pd.Series(),
        pd.Series(dtype="float"),
        pd.Series(index=pd.Index([])),
        # Size < 10kB
        pd.Series(index=pd.Index([], dtype=int)),
        pd.Series([0.0]),
    ],
)
def test_empty_series_to_hdf(tmpdir, series):
    """An empty series should not take much room on disk"""
    hdf_file = tmpdir.join("empty.hdf")
    series.to_hdf(hdf_file, "data")
    assert hdf_file.size() < 10000  # 5832 for pd.Series([0.])


@pytest.mark.parametrize(
    "df",
    [
        # Size > 2MB
        pd.DataFrame(),
        pd.DataFrame(dtype="float"),
        pd.DataFrame(index=pd.Index([]), columns=pd.Index([])),
        # Size < 10kB
        pd.DataFrame(index=pd.Index([], dtype=int), columns=pd.Index([], dtype=int)),
        pd.DataFrame({"a": [0.0]}),
    ],
)
def test_empty_dataframe_to_hdf(tmpdir, df):
    """An empty series should not take much room on disk"""
    hdf_file = tmpdir.join("empty.hdf")
    df.to_hdf(hdf_file, "data")
    assert hdf_file.size() < 10000  # 7040 for  pd.DataFrame({'a':[0.]}
```

**Comment by trevorkask** [comment]
take

**Comment by trevorkask** [comment]
Just to clarify, does this issue need a code change?

**Comment by TomAugspurger** [comment]
I don't think so. IIUC, the only issue is that object-dtype indexes / columns take more space.

There might be something pytables could do, but I suspect there isn't much. I don't think there's anything pandas can do.

**Comment by mwouts** [comment]
Hi @trevorkask , @TomAugspurger , thanks for having a look at this.

Well I understand that the issue is with pytables (and personally I am not affected any more as I serialize to other file types now), but still, I'd be curious to know why empty pandas indices have an object dtype?

**Comment by TomAugspurger** [comment]
I'm not sure if there's a particular reason, it's just the default we use for everything (including columns) when we don't have any additional information. It's not likely to change.

**Comment by mwouts** [comment]
I see! Thanks
