### ISSUE TITLE
Pandas won't drop index after rename using said index

### ISSUE THREAD

**Issue by veranscoto** [pandas-dev/pandas#33785]
So, there should probably be a 'drop' option as part of the rename function to drop said index if using it, but like the title says, if you rename using an index, you can't then use the drop function to drop said index (tested with xlsx and csv)

works for whatever index, 1, 2, 3, etc.
[testfile.xlsx](https://github.com/pandas-dev/pandas/files/4532369/testfile.xlsx)

```
    dataframe = pandas.read_excel(ENVT_SETTINGS['working_dir'] + 'testfile.xlsx', engine='openpyxl', header=None)
    
    print(dataframe.head(5))
    dataframe.rename(columns = dataframe.iloc[0], inplace = True)
    print(dataframe.head(5))
    dataframe.drop(dataframe.index[0])
    print(dataframe.head(5))
```
interestingly, you CAN drop it if you then recreate the dataframe like
`    dataframe = dataframe[1:]`
to literally cut out that row from the dataset, but otherwise, it won't go away.
[testfile.xlsx](https://github.com/pandas-dev/pandas/files/4532379/testfile.xlsx)
[testresult.xlsx](https://github.com/pandas-dev/pandas/files/4532380/testresult.xlsx)

**Comment by MarcoGorelli** [comment]
Thanks @veranscoto for the report

Could you please write a minimal reproducible example (see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) and/or show the output of `dataframe` after you read in the excel file?

**Comment by veranscoto** [comment]
this is as small as I can get the code?
```
    import pandas
    import openpyxl
    dataframe = pandas.read_excel(r'C:\testfile.xlsx', engine='openpyxl', header=None)
    dataframe.rename(columns = dataframe.iloc[0], inplace = True)
    dataframe.drop(dataframe.index[0])
```

Dataframe when you read the file:
```
      0      1      2      3
0  TEST  Test1  Test2  Test3
1   abc    def    hgi    jkl
2   123    456    789     12
3   zyx    wvu    tsr    qpo
```
dataframe after rename:
```
   TEST  Test1  Test2  Test3
0  TEST  Test1  Test2  Test3
1   abc    def    hgi    jkl
2   123    456    789     12
3   zyx    wvu    tsr    qpo
```

dataframe after drop of index used to rename
```
   TEST  Test1  Test2  Test3
0  TEST  Test1  Test2  Test3
1   abc    def    hgi    jkl
2   123    456    789     12
3   zyx    wvu    tsr    qpo

```
The second and third dataframes are the same; but they shouldn't be.

**Comment by MarcoGorelli** [comment]
`drop` doesn't modify the original dataframe. Does
```python
dataframe = dataframe.drop(dataframe.index[0])
```
give you what you want?

**Comment by MarcoGorelli** [comment]
As an aside, I think removing `header=None`from `read_excel` should work for your use case, can you try that?

**Comment by veranscoto** [comment]
yeah, setting it to a new dataframe (or using inplace=True) works.  Idk why that didn't occur to me.  I have to keep header=None because sometimes I get the same file with a weird header (like because they wanted to make it 'pretty') and othertimes not.
