### ISSUE TITLE
BUG: can't import pandas in directory containing file named inspect.py

### ISSUE THREAD

**Issue by Ysgorg** [pandas-dev/pandas#33794]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```bash
$ python3 -c "import pandas;print(pandas.__version__)" && touch inspect.py && python3 -c "import pandas"
1.0.3
Traceback (most recent call last): <error>
```
The error message: 
<details>

  File "<string>", line 1, in <module>
  File "/home/f/.local/lib/python3.6/site-packages/pandas/__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "/home/f/.local/lib/python3.6/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.groupby import Grouper, NamedAgg
  File "/home/f/.local/lib/python3.6/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import DataFrameGroupBy, NamedAgg, SeriesGroupBy
  File "/home/f/.local/lib/python3.6/site-packages/pandas/core/groupby/generic.py", line 60, in <module>
    from pandas.core.frame import DataFrame
  File "/home/f/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 104, in <module>
    from pandas.core.generic import NDFrame, _shared_docs
  File "/home/f/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 151, in <module>
    class NDFrame(PandasObject, SelectionMixin, indexing.IndexingMixin):
  File "/home/f/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 1111, in NDFrame
    def rename_axis(self, mapper=lib.no_default, **kwargs):
  File "/home/f/.local/lib/python3.6/site-packages/pandas/util/_decorators.py", line 229, in decorate
    kind = inspect.Parameter.POSITIONAL_OR_KEYWORD
AttributeError: module 'inspect' has no attribute 'Parameter'
</details>

#### Problem description

When using pandas in a project, I must take care not to use the filename `inspect.py`. 

#### Expected Output

No error

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-96-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.18.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 9.0.1
setuptools       : 41.5.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 0.999999999
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : None
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 2.1.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : 0.8.3
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by mroeschke** [comment]
There is a python standard library module called `inspect` that will conflict if a file is named `inspect.py` https://docs.python.org/3/library/inspect.html

Since this is a python standard library module, we recommend that the user file is renamed.
