### ISSUE TITLE
BUG:  .corr() fails when input is Int64Dtype()

### ISSUE THREAD

**Issue by akanz1** [pandas-dev/pandas#33803]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] This bug exists on the master branch of pandas. [see below](https://github.com/pandas-dev/pandas/issues/33803#issuecomment-619574491)

---

#### Code Sample, a copy-pastable example

```python
df = pd.DataFrame({'First':[1,2,3,4,np.nan],
                   'Second':[True, True, False, False, True],
                   'Third':[2,3,8,5,6]})
print(df.dtypes)
print(df.corr())
df
```
```
df_conv = df.convert_dtypes()
print(df_conv.dtypes)
print(df_conv)
df_conv.corr() # results in the following TypeError

TypeError: float() argument must be a string or a number, not 'NAType'
```

#### Problem description

When applying convert_dtypes() to a DataFrame, columns containing NaNs (np.nan) and integer values (stored as float64) are converted to "pd.NA" and actual integers (Int64). While this is desirable, it results in an error when calling the .corr() method on the DataFrame with the new dtypes.

**Before convert_dtypes():**
![before_conv](https://user-images.githubusercontent.com/51492342/80301427-5c3b5500-87a4-11ea-87fe-e3727c240a90.png)

**After convert_dtypes():**
![after_conv](https://user-images.githubusercontent.com/51492342/80301430-60677280-87a4-11ea-898c-7d0c9352edc9.png)

**Error message:**
![corr_error](https://user-images.githubusercontent.com/51492342/80301434-652c2680-87a4-11ea-94a9-7dd9b1a0c7f5.png)

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.3
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.3.post20200325
Cython           : None
pytest           : 5.4.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.13.0
pandas_datareader: None
bs4              : 4.9.0
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.2.1
numexpr          : None
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.4.1
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
numba            : 0.48.0

</details>

**Comment by dsaxton** [comment]
@akanz1 Thanks, looks like a bug to me and fails on master as well. Since the issue is with corr and not convert_dtypes could you update the title to reflect that?

**Comment by akanz1** [comment]
@dsaxton Thank you for your quick response, I've updated the title.

**Comment by akanz1** [comment]
Getting the same TypeError for .cov(). 

pointing to --> `libalgos.nancorr(ensure_float64(mat) ...)` as well

![cov_error](https://user-images.githubusercontent.com/51492342/80315938-283f4e80-87fb-11ea-82d8-94c4baf1d80f.png)
