### ISSUE TITLE
TST: add Feather V2 round-trip test

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#33810]
no that pyarrow 0.17 has landed, we should have a round-trip Feather V2 test to ensure we have dtype preservation (we can likely re-use some of our test frames from the parquet tests).

**Comment by jreback** [comment]
cc @alimcmaster1

**Comment by alimcmaster1** [comment]
will take a look

**Comment by jorisvandenbossche** [comment]
I think this was already covered by https://github.com/pandas-dev/pandas/pull/33422

**Comment by mroeschke** [comment]
Yeah looks like there are round tripping tests in `pandas/tests/io/test_feather.py` so I think we're okay to close
