### ISSUE TITLE
ENH: Add na_value to DataFrame.to_numpy

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#33820]
#### Is your feature request related to a problem?

Control the NA value used when converting a DataFrame to an ndarray.

#### Describe the solution you'd like

Add an `na_value` argument to `DataFrame.to_numpy()`. Has the same meaning as `na_value` in `Series.to_numpy`, except it applies to all the columns.

#### Additional context

```python
In [8]: df = pd.DataFrame({"A": pd.array([1, None])})

In [9]: df.to_numpy(na_value=np.nan)
```

This has come up in a few places (cc @jorisvandenbossche @dsaxton)

**Comment by dsaxton** [comment]
Thanks @TomAugspurger. https://github.com/pandas-dev/pandas/pull/33809 took the approach of using DataFrame.astype(float).to_numpy() to coerce NA to np.nan which should likely be fixed once this becomes available.
https://github.com/pandas-dev/pandas/blob/8aa707298428801199280b2b994632080591700a/pandas/core/frame.py#L7873
