### ISSUE TITLE
BUG: pandas.io.common _stringify_path uses isinstance in a wrong way raising an exception

### ISSUE THREAD

**Issue by Fjolnir-Dvorak** [pandas-dev/pandas#33827]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# pandas.io.common._stringify_path (line 150) uses pathlib.Path in an
# isinstance check but misses a wrapping type()
# broken:
isinstance("dummyvalue", pahtlib.Path)
# working fix:
isinstance("dummyvalue", type(pathlib.Path)
```

#### Problem description

The current implementation raises following exception: 
TypeError: isinstance() arg 2 must be a type or tuple of types

Tested in the latest python 3.7 and 3.8 releases

#### Output of ``pd.show_versions()``

<details>
import pandas as pd
pd.show_versions()
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.33-3-MANJARO
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8
pandas           : 1.0.3
numpy            : 1.18.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.3
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : 0.9.3
psycopg2         : None
jinja2           : 2.11.1
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : 0.3.3
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.2.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.16.0
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.16
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : 0.48.0

</details>

**Comment by Fjolnir-Dvorak** [comment]
Monkey patch:

```python

def fix_pandas() -> None:
    from pandas.io.common import pathlib, _expand_user
    import pandas
    def _stringify_path(filepath_or_buffer):
        """Attempt to convert a path-like object to a string.

        Parameters
        ----------
        filepath_or_buffer : object to be converted

        Returns
        -------
        str_filepath_or_buffer : maybe a string version of the object

        Notes
        -----
        Objects supporting the fspath protocol (python 3.6+) are coerced
        according to its __fspath__ method.

        For backwards compatibility with older pythons, pathlib.Path and
        py.path objects are specially coerced.

        Any other object is passed through unchanged, which includes bytes,
        strings, buffers, or anything else that's not even path-like.
        """
        if hasattr(filepath_or_buffer, "__fspath__"):
            return filepath_or_buffer.__fspath__()
        elif isinstance(filepath_or_buffer, type(pathlib.Path)):
            return str(filepath_or_buffer)
        return _expand_user(filepath_or_buffer)
    pandas.io.common._stringify_path = _stringify_path
    return
```

**Comment by simonjayhawkins** [comment]
@Fjolnir-Dvorak Thanks for the report.

> isinstance("dummyvalue", pahtlib.Path)

should raise NameError: name 'pahtlib' is not defined

```
>>> import pathlib
>>> isinstance("dummyvalue", pathlib.Path)
False
>>>
```
seems to be as expected.

can you update the OP with a reproducible example. see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by Fjolnir-Dvorak** [comment]
I am sorry. I found the issue. It is a bug in a default python shell initialization script on my part overriding pathlib.Path due to a typing typo.
