### ISSUE TITLE
API: EA/Index/Series.factorize should have same kwargs as pd.factorize

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#33838]
This will allow pd.factorize to dispatch to the EA/Index/Series implementations instead of the other way around.

**Comment by jorisvandenbossche** [comment]
What would be the advantage of having `pd.factorize()` call `Series.factorize()` instead of `Series.factorize()` calling `pd.factorize()` as it is now?

**Comment by jbrockmendel** [comment]
Reopening bc I'm finding that having DTI.factorize retain freq is a PITA if I can't just defer to the DTI/DTA implementation

**Comment by jbrockmendel** [comment]
xref #35563
