### ISSUE TITLE
BUG: groupby on columns does not work with Series

### ISSUE THREAD

**Issue by FlorentinGerard** [pandas-dev/pandas#33842]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

---

No groups are found when using a pd.Series instead of a list in a groupby(axis=1)

```python
>>> df = pd.DataFrame(np.arange(16).reshape(4, 4), columns=['A', 'B', 'C', 'D'])

>>> grouped_list_row = df.groupby([1, 2, 1, 2])
>>> print(f"number of elem list_row: {len(grouped_list_row)}")

>>> grouped_series_row = df.groupby(pd.Series([1, 2, 1, 2]))
>>> print(f"number of elem series_row: {len(grouped_series_row)}")

>>> grouped_list_column = df.groupby([1, 2, 1, 2], axis=1)
>>> print(f"number of elem list_column: {len(grouped_list_column)}")

>>> grouped_series_column = df.groupby(pd.Series([1, 2, 1, 2]), axis=1)
>>> print(f"number of elem series_column: {len(grouped_series_column)}")

number of elem list_row: 2
number of elem series_row: 2
number of elem list_column: 2
number of elem series_column: 0
```

#### Problem description

I would expect to have the same result with a list and with a pd.Series(list). 
Instead no groups are created
#### Expected Output
number of elem list_row: 2
number of elem series_row: 2
number of elem list_column: 2
number of elem series_column: **2**
#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : fr_FR.UTF-8
LOCALE           : None.None

pandas           : 1.0.3
numpy            : 1.17.1
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 18.1
setuptools       : 40.8.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.7.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.2.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
</details>

**Comment by TomAugspurger** [comment]
I think this is an alignment issue.

```python
In [23]: s = pd.Series([1, 2, 1, 2], index=["A", "B", "C", "D"])

In [25]: len(df.groupby(s, axis=1))
Out[25]: 2
```

As the DataFrame.groupby docs say

```
If a dict or Series is passed, the Series or dict VALUES
    will be used to determine the groups (the Series' values are first
    aligned; see ``.align()`` method). 
```

**Comment by FlorentinGerard** [comment]
Ok, I see thanks

I think the [groupby section](https://pandas.pydata.org/docs/user_guide/groupby.html) in the user guide should not have this example:

> In [4]: grouped = df.groupby('order', axis='columns')

It is quite confusing and there is no group at all cause of the allignement

**Comment by TomAugspurger** [comment]
@FlorentinGerard a doc example (probably in the user guide?) would be welcome. Can you submit one?

**Comment by FlorentinGerard** [comment]
Well I am not sure if an example should be provided for the alignment. 
But this example is really confusing:

```python
In [1]: df = pd.DataFrame([('bird', 'Falconiformes', 389.0),
   ...:                    ('bird', 'Psittaciformes', 24.0),
   ...:                    ('mammal', 'Carnivora', 80.2),
   ...:                    ('mammal', 'Primates', np.nan),
   ...:                    ('mammal', 'Carnivora', 58)],
   ...:                   index=['falcon', 'parrot', 'lion', 'monkey', 'leopard'],
   ...:                   columns=('class', 'order', 'max_speed'))
   ...: 

In [2]: df
Out[2]: 
          class           order  max_speed
falcon     bird   Falconiformes      389.0
parrot     bird  Psittaciformes       24.0
lion     mammal       Carnivora       80.2
monkey   mammal        Primates        NaN
leopard  mammal       Carnivora       58.0
....
In [4]: grouped = df.groupby('order', axis='columns')
```
Here we groupby on colomn axis with the key being a column. 
It does not really make sense and result in no group since index & columns do not share labels.

At the very begin of the groupby guide it is puzzling (at least it was for me).
To illustrate grouby on columns it could be replace by something like that:

```python
 In [4]: grouped = df.groupby(['taxonomy', 'taxonomy', 'species_attribute'], axis='columns')
```
Probably easier to understand

**Comment by rhshadrach** [comment]
Since `axis` has been removed, closing.
