### ISSUE TITLE
BUG: pd.read_excel error when a cell contains string "INF"

### ISSUE THREAD

**Issue by josephernest** [pandas-dev/pandas#33853]
Here is how to reproduce the bug: run this script:

    import pandas as pd
    pd.read_excel('test.xlsx')
    # idem with pd.read_excel('test.xlsx', engine='openpyxl')
    # so it's not specific to xlrd or openpyxl

with this [test.xlsx](https://gget.it/tuha/test.xlsx) file:

a | b
-- | --
12 | 1
14 | 1
15 | 1
16 | INF

Error:

> OverflowError: cannot convert float infinity to integer

Why does this happen / why is there a integer conversion? No automatic integer parsing has been asked.

___

PS: Congrats for this great project!

**Comment by asishm** [comment]
@josephernest 
> Why does this happen / why is there a integer conversion? No automatic integer parsing has been asked.

there is a parameter : `convert_float: bool, default True`. 

**workaround:**
As a workaround you can set `convert_float=False`. It only works with the default engine (xlrd).

**openpyxl**

Note that this would still fail when using `engine='openpyxl`. It seems like openpyxl does its own internal int conversion when parsing the file as referenced in the traceback:

```py
  File "pandas-dev/lib/python3.8/site-packages/openpyxl/worksheet/_reader.py", line 199, in parse_cell
    value = _cast_number(value)
  File "pandas-dev/lib/python3.8/site-packages/openpyxl/worksheet/_reader.py", line 82, in _cast_number
    return int(value)
ValueError: invalid literal for int() with base 10: 'INF'
```

That is something that would need to be fixed upstream.

**xlrd**

Fixing for `xlrd` case should be fairly straightforward as we'd only need to catch the `OverFlowError` that is being raised

```py
  File "pandas/io/excel/_xlrd.py", line 105, in <listcomp>
    _parse_cell(value, typ)
  File "pandas/io/excel/_xlrd.py", line 96, in _parse_cell
    val = int(cell_contents)
OverflowError: cannot convert float infinity to integer
```

**Comment by mroeschke** [comment]
Since this is an issue with openpyxl, I think it would be better for the issue to be fixed upstream. If you could file an issue in their repo that would be great. Closing.
