### ISSUE TITLE
DOC: Code Standards Broken Link

### ISSUE THREAD

**Issue by Stockfoot** [pandas-dev/pandas#33852]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#code-standards
![image](https://user-images.githubusercontent.com/36280534/80523857-f4277300-894b-11ea-9e9c-0ae0b2b8ed77.png)

#### Documentation problem

There is a broken link on Development -> Contributing To Pandas -> Contributing To The Code Base -> Code Standards -> "pandas code style guide"

Link location goes to 404 Error at
https://pandas.pydata.org/pandas-docs/stable/development/code_style

#### Suggested fix for documentation

Change link address to proper page/document

**Comment by MarcoGorelli** [comment]
Thanks @Stockfoot - are you interested in submitting a pull request?
