### ISSUE TITLE
ImportError: cannot import name 'TimeGrouper' from 'pandas' (F:\Anaconda\lib\site-packages\pandas\__init__.py)BUG:

### ISSUE THREAD

**Issue by DheerajPranav** [pandas-dev/pandas#33850]
ImportError                               Traceback (most recent call last)
<ipython-input-64-1268709bbfb0> in <module>
----> 1 from pandas import TimeGrouper
      2 groups = series.groupby(TimeGrouper('A'))
      3 years = DataFrame()
      4 for name, group in groups:
      5     years[name.year] = group.values

ImportError: cannot import name 'TimeGrouper' from 'pandas' (F:\Anaconda\lib\site-packages\pandas\__init__.py)

**Comment by hwalinga** [comment]
TimeGrouper is deprecated. Take a look at Grouper instead.
