### ISSUE TITLE
BUG: RGBA-transparency issue in pandas boxplot

### ISSUE THREAD

**Issue by MatthiVH** [pandas-dev/pandas#33868]
When setting color and transparency using rgba-values in pandas.boxplot(), the code doesn't seem to recognize the alpha-value. I raised a question on StackOverflow already (<https://stackoverflow.com/questions/61501795/set-boxplot-boxes-facecolor-transparency-in-python-matplotlib>) but this might be something to fix in the github. I have used rgba-values elsewhere and never had issues with it, only here it doesn't seem to work properly.

**Comment by StefRe** [comment]
See my [SO answer](https://stackoverflow.com/a/62718470/3944322). I think you can close this issue.
