### ISSUE TITLE
BUG: Series.apply behaves incorrectly with timezone-aware data.

### ISSUE THREAD

**Issue by NotSpecial** [pandas-dev/pandas#33876]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# For a series with tz-unaware datetime, apply behaves correctly and passes each value to the function.
pd.Series([pd.Timestamp(1)]).apply(print)

# For tz-aware data, apply injects a DatetimeIndex containing the whole series as first argument
pd.Series([pd.Timestamp(1)]).astype("datetime64[ns, UTC]").apply(print)
```

Output:
```
# First, correct:
1970-01-01 00:00:00.000000001+00:00

# Second, incorrect:
DatetimeIndex(['1970-01-01 00:00:00.000000001+00:00'], dtype='datetime64[ns, UTC]', freq=None)
1970-01-01 00:00:00.000000001+00:00
```

#### Problem description

According to [the documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.apply.html#pandas.Series.apply), `apply` should call the provided function (`print` in the dummy example) to each value in the series.
For timezone-unaware data, this works as expected. In the example, `print` is called with the timestamp only.

However, when the data is tz-aware, the function is first called with a `DatetimeIndex` containing the whole series. Only afterwards, the function is called with each value in the series.

#### Expected Output

Regardless of whether the data is tz-aware, apply should call the function only with each value in the series.

Or am I misunderstanding `apply`, and this output is actually intended?

In any case, thanks for your help!

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-76-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.18.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 9.0.1
setuptools       : 46.1.3
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 0.999999999
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.13.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.2.1
numexpr          : 2.7.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : 3.6.1
tabulate         : 0.8.7
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by mroeschke** [comment]
I think code path applies generally for ExtensionArray dtypes and dispatches to `Index.map`.

I think this is more an artifact of the internal implementation details (which can change) as the function is still applied to each element. Is there a case where this produces an actual bug as a result of `apply`?

**Comment by NotSpecial** [comment]
This causes problems when using custom apply functions:

```
def compute_something(must_be_timestamp):
   ...

# Works, as only the timestamps are passed to the function.
pd.Series([pd.Timestamp(1)]).apply(compute_something)

# Fails, as the function is passed a non-timestamp argument first.
pd.Series([pd.Timestamp(1)]).astype("datetime64[ns, UTC]").apply(compute_something)
```

It is not a huge problem, as it can be solved with multiple workarounds:
- check whether the input is a timestamp in the function and return None otherwise
- remove the timezone first).
- rewrite the function so it can use a vector of timestamps as input and can be called on the whole series.

Nevertheless, I found it just a bit confusing that I my function was called with inputs it should not receive. Maybe a warning in in the docs would also be ok?

**Comment by mroeschke** [comment]
Could you give a small toy example where your custom function fails because of this behavior? Would give us more clarity to see how/if this behavior should be fixed.

As this is an internal implementation that is subject to change, I'd hesitant to put it in the docs, but all for correcting this behavior if it impacts a custom function passed into apply

**Comment by jbrockmendel** [comment]
@NotSpecial ping, we could use some more information to help address your issue (see previous comment)

**Comment by mroeschke** [comment]
Closing for now due to inactivity, but happy to reopen if we can get a concrete apply functions where there exists a bug.
