### ISSUE TITLE
DOC:https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.reindex.html#pandas.DataFrame.reindex

### ISSUE THREAD

**Issue by 2bon** [pandas-dev/pandas#33888]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.reindex.html#pandas.DataFrame.reindex

#### Documentation problem
Returns
DataFrame with changed index.

#### Suggested fix for documentation
fix= a NEW DataFrame instance with changed index,NOT changing old instance .
why? I thought old instance has changed index.

**Comment by MarcoGorelli** [comment]
Thanks @2bon for the report - the docs currently say

> A new object is produced unless the new index is equivalent to the current one and copy=False.

but if you think it could be clarified, pull requests are welcome https://pandas.pydata.org/pandas-docs/stable/development/contributing.html

**Comment by 2bon** [comment]
Could we make it ez 2 read, pls!
now is 2 ivory-Towered and confusing .
(unless the new index is equivalent to the current one ) if so, why do I reIndex? let's ignore 1%% corner case

**Comment by gauravchandok** [comment]
Is someone working on this issue or can I take it?

**Comment by MarcoGorelli** [comment]
@gauravchandok sure, pull requests are welcome if you think the docs can be clarified

**Comment by 2bon** [comment]
@gauravchandok ya, thx

**Comment by 2bon** [comment]
Hi, any update?

**Comment by MarcoGorelli** [comment]
> Hi, any update?

as mentioned above, pull requests are welcome, see [here](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html) for how to contribute

**Comment by MarcoGorelli** [comment]
Closing for now as there doesn't seem to be any traction here, but feel free to open a PR if you think this docstring can be clarified
