### ISSUE TITLE
QST: Conversion of series to Dataframe Issue

### ISSUE THREAD

**Issue by steve-c3** [pandas-dev/pandas#33893]
#### Question about pandas
After using groupby on a Dataframe to group and sum column data into a series I then converted the result back to a Dataframe using .to_frame method which I then converted to html for output to a file. This appears to work well except that the header row has a zero in the last column which I am unable to delete - any ideas? - see here
                                                                                          0
Board Type   NE Type Hardware Version Software Version                                     

# Your code here, if applicable
       NE_3 = NE_2.groupby(NE_2.columns.tolist(), as_index=False).size()
       NE_3 = NE_3.to_frame()

       NE_2 = NE_2.drop_duplicates()
       NE_3 = NE_3.drop(columns='NE Type') # This doesn't work due to the '0' corrupting the header row
       html_txt = NE_3.to_html()
       tfile.write(html_txt)
       tfile.write('<br/>')
```

**Comment by jreback** [comment]
please ask usage questions Stackoverflow. you should post with a reproducible example
