### ISSUE TITLE
API: Revert changes to describe

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#33903]
https://github.com/pandas-dev/pandas/pull/30209/ has some changes to describe for datelike data. I think the changes count as API breaking and should wait until a 2.0, possibly with a deprecation warning.

cc @david-cortes, @jreback.

master:

```python
In [1]: import pandas as pd

In [2]: pd.Series(pd.date_range('2000', periods=10)).describe()
Out[2]:
count                     10
mean     2000-01-05 12:00:00
min      2000-01-01 00:00:00
25%      2000-01-03 06:00:00
50%      2000-01-05 12:00:00
75%      2000-01-07 18:00:00
max      2000-01-10 00:00:00
dtype: object

In [3]: pd.__version__
Out[3]: '1.1.0.dev0+1417.g12c9c626d'
```

1.0.2:

```python
In [1]: import pandas as pd

In [2]: pd.Series(pd.date_range('2000', periods=10)).describe()
Out[2]:
count                      10
unique                     10
top       2000-01-08 00:00:00
freq                        1
first     2000-01-01 00:00:00
last      2000-01-10 00:00:00
dtype: object

In [3]: pd.__version__
Out[3]: '1.0.2'
```

**Comment by jreback** [comment]
I guess, this is allowing new ops in M8. what exactly did this show up?

**Comment by TomAugspurger** [comment]
Came up in a dask test asserting that the output of dask.dataframe's describe matches pandas.

I'd also be fine with a `datetlike_is_numeric=None/True/False` with a default of warning and giving the old output and an option to silence the warning by specifying True / False.
