### ISSUE TITLE
ENH: Add nrows parameter to pd.read_json

### ISSUE THREAD

**Issue by sp1thas** [pandas-dev/pandas#33916]
#### Is your feature request related to a problem?

Let's say I have a huge `jsonlines` file and I want to read only the first `n` lines of the file.

#### Describe the solution you'd like

This problem could be fixed by adding `nrows` parameter in method `pd.read_json`. This parameter should be applicable if and only if `lines=True`

#### API breaking implications

Simply add and implement `nrows` parameter in `pd.read_json` (like `pd.read_csv`).

#### Additional context

How this enhancement could work:

```python
import pandas as pd

df = pd.read_json('/path/to/file.jsonlines', lines=True, nrows=1000)
```

**Comment by hasnain2808** [comment]
Hi @sp1thas ,
I checked the code and I feel, I should be able to implement this feature.

**Comment by hasnain2808** [comment]
take
