### ISSUE TITLE
Performance regression in DataFrame[bool_indexer]

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#33924]
```python
import numpy as np
import pandas as pd

idx_dupe = np.array(range(30)) * 99
df = pd.DataFrame(np.random.randn(10000, 5))
bool_indexer = [True] * 5000 + [False] * 5000


%timeit df[np.array(bool_indexer)]
```

```
# 1.0.2
2.58 ms ± 108 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

# master
5.47 ms ± 192 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

Note that this only affects the case where the indexer is a *list*. Performance looks fine when an ndarray is passed.

https://pandas.pydata.org/speed/pandas/index.html#indexing.DataFrameNumericIndexing.time_bool_indexer?commits=80d37adcc3d9bfbbe17e8aa626d6b5873465ca98-4f89c261f624305fc7bae6c43ae862663994be34 points to somewhere in 80d37adc..4f89c261, which has a bunch of commits.

**Comment by rohitkg98** [comment]
The performance issue seems to be in https://github.com/pandas-dev/pandas/blob/e835b7609668222fcbb193eab4ec72c664ba991f/pandas/core/indexers.py#L348

in which https://github.com/pandas-dev/pandas/blob/911e19bf0868b6d9ba76e63e071f410bb693fa50/pandas/core/construction.py#L56 is called which calls `infer_dtype` twice.
It seems to have started from this PR [#31150](https://github.com/pandas-dev/pandas/pull/31150).
The performance also seems to have worsened just a tiny bit after this [commit](https://github.com/pandas-dev/pandas/commit/ee1736a). 
I have used cProfile to perform the analysis. I apologise for any mistakes, I'm still a novice dev.
