### ISSUE TITLE
BUG: Local test fail due to change of botocore error handling

### ISSUE THREAD

**Issue by monferrand** [pandas-dev/pandas#33928]
Running 
```
pytest pandas/tests/io/parser/test_network.py::TestS3::test_write_s3_csv_fails
```
or 
```
pytest pandas/tests/io/parser/test_network.py::TestS3::test_write_s3_parquet_fails
```

will fail 

```
FAILED pandas/tests/io/parser/test_network.py::TestS3::test_write_s3_csv_fails - botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified ...
FAILED pandas/tests/io/parser/test_network.py::TestS3::test_write_s3_parquet_fails - botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the PutObject operation: The specif...
```

With python 3.8 (linux), s3fs 0.4.2

I believe the issue comes from a change of error handling in botocore (used by s3fs).

Output of pd.show_versions():
<details>
INSTALLED VERSIONS
------------------
commit           : 1c88e6aff94cc9183909b7c110f554df42509073
python           : 3.8.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-28-generic
Version          : #32-Ubuntu SMP Wed Apr 22 17:40:10 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.0.dev0+1446.g1c88e6aff.dirty
numpy            : 1.18.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1
setuptools       : 46.1.3.post20200325
Cython           : 0.29.17
pytest           : 5.4.1
hypothesis       : 5.10.4
sphinx           : 3.0.3
blosc            : None
feather          : None
xlsxwriter       : 1.2.8
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.13.0
pandas_datareader: None
bs4              : 4.9.0
bottleneck       : 1.3.2
fastparquet      : 0.3.3
gcsfs            : None
matplotlib       : 3.2.1
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : 0.17.0
pytables         : None
pyxlsb           : None
s3fs             : 0.4.2
scipy            : 1.4.1
sqlalchemy       : 1.3.16
tables           : 3.6.1
tabulate         : 0.8.7
xarray           : 0.15.1
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.48.0

</details>

**Comment by mroeschke** [comment]
Looks like this is from an older version of s3fs and is not failing in our CI so closing
