### ISSUE TITLE
Unstable time_get_loc benchmark 

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#33922]
This benchmark regularly jumps between 200 and 800 ms: https://pandas.pydata.org/speed/pandas/index.html#indexing_engines.NumericEngineIndexing.time_get_loc?p-engine_and_dtype=%28%3Cclass+%27pandas._libs.index.Int16Engine%27%3E%2C+%3Cclass+%27numpy.int16%27%3E%29&p-index_type=%27monotonic_incr%27&commits=d04b965f98fa53f22cc41f7e4d081d763d2856a1

I don't immediately see any issues with it, but haven't looked closely. This issue can be closed when we determine the cause and make the benchmark timings stable.

**Comment by jbrockmendel** [comment]
I don't see any jumps on the graph, closing as no-action and lumping in with the general "make asvs more reliable" goals.
