### ISSUE TITLE
Performance regression in Index.union

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#33923]
Setup

```python
import numpy as np
import pandas as pd

dtype = "datetime"
method = "union"

N = 10 ** 5
left = pd.date_range("1/1/2000", periods=N, freq="T")
right = left[:-1]

%timeit left.union(right)
```

```
# 1.0.2
161 µs ± 7.46 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

# master
296 µs ± 5.58 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

https://pandas.pydata.org/speed/pandas/index.html#index_object.SetOperations.time_operation?p-dtype=%27datetime%27&p-method=%27union%27&commits=428791c5e01453ff6979b43d37c39c7315c0aaa2-1e5ff233c559ecb2f14fdb9c8d9537db3a02ce1d points to somewhere in https://github.com/pandas-dev/pandas/compare/428791c5e01453ff6979b43d37c39c7315c0aaa2...1e5ff233c559ecb2f14fdb9c8d9537db3a02ce1d

Maybe c60882429e? (cc @jbrockmendel) Haven't looked closely yet.

**Comment by jbrockmendel** [comment]
Restoring the is_integer fastpath in `DTA.__getitem__` fixes about 3.4 of the perf loss.  Most of the rest looks like its in can_fast_union, not sure exactly whats going on there.  A few more percent can be trimmed by making properties in NDArrayBackedExtensionArray into cache_readonlys.

**Comment by TomAugspurger** [comment]
We've restored the majority of the performance here. On master I have ~25% slowdown compared to 1.0.4

```
# 1.0.4
160 µs ± 7.18 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
# master
202 µs ± 7.84 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

Leaving this open for now, but it may be hard to identify the remaining slowdown.

**Comment by jbrockmendel** [comment]
I'm seeing 132µs on 1.0.2, 136µs on 1.0.4, and 144µs on master, so still a slowdown, but not nearly as much as you're seeing.

**Comment by jbrockmendel** [comment]
Looks like more time spent inside _can_fast_union

**Comment by TomAugspurger** [comment]
I think we're close enough to 1.0.4 to call this fixed.
