### ISSUE TITLE
API/BUG: Series.argmin/max with all-NaN data returns -1 ?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#33941]
Ran into this while looking at https://github.com/pandas-dev/pandas/pull/27801. 

Both numpy and pandas raise an error for empty arrays/Series in `argmin` and `argmax`:

```python
>>> pd.Series([], dtype=float).argmin()   
...
ValueError: attempt to get argmin of an empty sequence

>>> np.array([], dtype=float).argmin()  
...
ValueError: attempt to get argmin of an empty sequence
```

However, when having all NaN data, we see a different behaviour:

```python
>>> pd.Series([np.nan, np.nan], dtype=float).argmin() 
-1

>>> np.array([np.nan, np.nan], dtype=float).argmin() 
0
```

Does somebody have an explanation of *why* this would return -1 ?

In principle, in pandas, `argmin` has a `skipna=True` keyword, so for pandas I would expect that an all-NaN Series behaves the same as an empty Series.

**Comment by jorisvandenbossche** [comment]
So this is quite explicit in the code of nanops.nanargmin/max:

https://github.com/pandas-dev/pandas/blob/07402f6c3565e1689f61d6320bd4a570e94bcfc0/pandas/core/nanops.py#L1171-L1176

and those lines haven't been touched in 8 years .. https://github.com/pandas-dev/pandas/commit/c1307b68d5cc16848be832db67937fd9e639800e

This behaviour is used in `idxmin/max`:

https://github.com/pandas-dev/pandas/blob/07402f6c3565e1689f61d6320bd4a570e94bcfc0/pandas/core/series.py#L2005-L2008

The logic behind "-1" might be that in general in pandas indexers, -1 is used for missing values (and argmin kind of returns an indexer). But still, that doesn't make much sense to me for a user-facing `argmin/max`.

**Comment by jreback** [comment]
if you recall we separated out argmax from idxmax a while back

since argmax is not that useful in pandas (you almost always want idxmax) it’s likely understated

not averse to changing to more common behavior to raise for argmax

however min/max imho should just work in empty (no raise) as that is a common pandas pattern

**Comment by jorisvandenbossche** [comment]
> if you recall we separated out argmax from idxmax a while back

Yes, I know. But, which actually means that the new user-facing behaviour of argmin/argmax is rather recent (only from pandas 1.0), which is maybe a good reason that we can still fix this as a bug instead of deprecating. 

Now, the actual behaviour of `nanops.nanargmin/max` is from long before this idx/arg split. It even stems from before pandas 0.13, when Series stopped being an ndarray subclass and changed the behaviour of argmin/max. Now, I suppose before 1.0, the nanops version was only used internally (eg in the `idxmin/max` implementation, as shown above)

**Comment by jorisvandenbossche** [comment]
>  Now, I suppose before 1.0, the nanops version was only used internally (eg in the idxmin/max implementation, as shown above)

On second thought, that's not fully true, since the Index classes already have been using the `nanops` version in their argmin/max methods (and does already returns -1 for a long time in this case).

**Comment by rhshadrach** [comment]
> if you recall we separated out argmax from idxmax a while back
> 
> since argmax is not that useful in pandas (you almost always want idxmax) it’s likely understated
> 
> ...
> 
> however min/max imho should just work in empty (no raise) as that is a common pandas pattern

Should idxmax also work on empty Series - both truly empty Series and Series that are entirely null? Both Series.idxmax and DataFrame.idxmax currently raise, but their groupby equivalents do not (except for the special case of a categorical grouper with `observed=False` and missing categories).

@jreback - I'm curious as to what common pattern you refer to above. Is it the idea that producing summary statistics (e.g. DataFrame.describe) on any data shouldn't fail?

**Comment by jbrockmendel** [comment]
Discussed on last week's dev call, agreed these should be deprecated to raise.
