### ISSUE TITLE
CondaMemoryError When Creating Development Environment with 1 GB Memory

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#33946]
This is on a rather limited set of hardware (only 1 GB of memory available) but was surprised when building an environment that running a 

```sh
conda env create -f environment.yml
```

throws the following error:

```sh
CondaMemoryError: The conda process ran out of memory. Increase system memory and/or try again.
```

**Comment by jorisvandenbossche** [comment]
This is quite expected I think, as conda is known to use a lot of memory while solving the environment. 

I don't think we should solve this in pandas for the main `environment.yml` file, but you can make a version of the env file with less optional dependencies (we install a *lot*), or set exactly pinned versions (this reduces the work conda needs to do when solving, see also https://github.com/mariusvniekerk/conda-lock which can help wit this).
