### ISSUE TITLE
BUG: Not properly checking if post_processing function is callable or not in _get_cythonized_result() function in class GroupBy

### ISSUE THREAD

**Issue by KenilMehta** [pandas-dev/pandas#33955]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

#### Problem description
While looking at the code, I found this line which I think is a bug. In the current master branch, pandas/core/groupby/groupby.py file, in the _get_cythonized_result() function :

```
        if post_processing:
            if not callable(pre_processing):
                raise ValueError("'post_processing' must be a callable!")
```

While checking if post_processing is callable or not, we are actually passing pre_processing object instead of post_processing. This looks like a bug.

#### Expected Code
```
        if post_processing:
            if not callable(post_processing):
                raise ValueError("'post_processing' must be a callable!")
```

**Comment by jreback** [comment]
user codes don’t hit this
so is there any user facing issue?

**Comment by KenilMehta** [comment]
No, not that I know of.
But I think we should still fix it.

**Comment by jreback** [comment]
not averse to an AssertionError

**Comment by WillAyd** [comment]
Looks like a typo. PR welcome

**Comment by TomAugspurger** [comment]
@rhshadrach was this closed by https://github.com/pandas-dev/pandas/pull/34372?

**Comment by rhshadrach** [comment]
@TomAugspurger - Yes, thanks for catching this.
