### ISSUE TITLE
Feature Request: Add Direct Support to Plotly Express as a submodule in pandas.DataFrame.iplot

### ISSUE THREAD

**Issue by jtelleriar** [pandas-dev/pandas#33965]
Could support to Plotly Express be directly added within pandas as a iplot submodule?:

https://plotly.com/python/plotly-express/

Thanks!

**Comment by jorisvandenbossche** [comment]
With the new "plotting backend" system (https://pandas.pydata.org/docs/dev/user_guide/visualization.html#plotting-backends, https://stackoverflow.com/questions/58440524/change-pandas-plotting-backend-to-get-interactive-plots-instead-of-matplotlib-st), plotly express (or another package) can provide such functionality, without the need to include it into pandas itself.

And it seems they are planning that in plotly: https://github.com/plotly/plotly.py/issues/2005

**Comment by jtelleriar** [comment]
If this is already being developed in plotly/plotly.py#2005 will close this issue then.

Thanks! 

Juan
