### ISSUE TITLE
QST:

### ISSUE THREAD

**Issue by Gautamshahi** [pandas-dev/pandas#33981]
I am using the below code to merger the multiple CSV files in the folder. The code is working fine for smaller dataset but for bigger data.

As the total number of rows is 51163632 but as a result, in big_frame I am getting only 20883611 rows.

Is there a limit of pandas dataframe to store the values?

big_frame = pd.DataFrame()

filename= []
num_comments=0
for file in os.listdir():
    print(file)
    if file.endswith('.CSV'):
        filename.append(file)
        num_lines = sum(1 for line in open(file, encoding="utf8"))
        #print(num_lines)
        num_comments = num_comments + num_lines
        print(num_comments)
        try:
        #df = pd.read_csv(file, error_bad_lines=False, sep=',', header=None, encoding='utf-8')
            df = pd.read_csv(file, error_bad_lines=False, delimiter=',', header=None, encoding='utf-8')
        except:
            continue
        big_frame = big_frame.append(df, ignore_index=True)

**Comment by CloseChoice** [comment]
Is it possible that the rest of the data cannot be read correctly with the options you gave( `pd.read_csv(file, error_bad_lines=False, delimiter=',', header=None, encoding='utf-8')`) and is therefore skipped by your `try-except`?
Or you run into a MemoryError before all of the data is read. You are excepting every Error which could happen and in one of these errors lies the reason for your missing data.

**Comment by jbrockmendel** [comment]
can you do this without the try/except?  if some of the files are raising, that would explain why you're getting fewer rows than expected

**Comment by MarcoGorelli** [comment]
Closing as it's been > 1 month since we heard from the OP, and it's hard to know what to do with the question as it stands
