### ISSUE TITLE
Failing test_missing_required_dependency in pandas-wheels

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#33999]
The test `test_missing_required_dependency` is failing in MacPython/pandas-wheels. https://dev.azure.com/pandas-dev/pandas-wheels/_build/results?buildId=34824&view=logs&j=c0130b29-789d-5a3c-6978-10796a508a7f&t=e120bc6c-1f5e-5a41-8f0a-1d992cd2fbfb.

This has caused issues in the past. It's low priority so for now I'm just going to skip it over there.

**Comment by simonjayhawkins** [comment]
changed milestone to increase visibility, but not a blocker.

**Comment by simonjayhawkins** [comment]
moved off 1.1.3 milestone (overdue) as no PRs to fix in the pipeline
