### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by kevinksyTRD** [pandas-dev/pandas#33997]
- [O ] I have checked that this issue has not already been reported.

- [O ] I have confirmed this bug exists on the latest version of pandas.

- [O ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
import pandas
```

#### Problem description
I cannot import pandas because of the Attribute error. AttributeError: partially initialized module 'pandas' has no attribute 'plotting' (most likely due to a circular import)

#### Expected Output
No error.
#### Output of ``pd.show_versions()``
Couldn't do it because it could not be imported. O a,
<details>
I didn't get the error when I installed version 1.0.1.
Below is the error message.

 import pandas
  File "C:\Users\user\app\venv\lib\site-packages\pandas\__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "C:\Users\user\app\venv\lib\site-packages\pandas\core\api.py", line 29, in <module>
    from pandas.core.groupby import Grouper, NamedAgg
  File "C:\Users\user\app\venv\lib\site-packages\pandas\core\groupby\__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import DataFrameGroupBy, NamedAgg, SeriesGroupBy
  File "C:\Users\user\app\venv\lib\site-packages\pandas\core\groupby\generic.py", line 60, in <module>
    from pandas.core.frame import DataFrame
  File "C:\Users\user\app\venv\lib\site-packages\pandas\core\frame.py", line 124, in <module>
    from pandas.core.series import Series
  File "C:\Users\user\app\venv\lib\site-packages\pandas\core\series.py", line 122, in <module>
    class Series(base.IndexOpsMixin, generic.NDFrame):
  File "C:\Users\user\app\venv\lib\site-packages\pandas\core\series.py", line 4562, in Series
    plot = CachedAccessor("plot", pandas.plotting.PlotAccessor)
AttributeError: partially initialized module 'pandas' has no attribute 'plotting' (most likely due to a circular import)
</details>

**Comment by jbrockmendel** [comment]
How did you install pandas?

**Comment by kevinksyTRD** [comment]
I installed it by 
`pip install -r requirements.txt`
where requirements.txt includes pandas without specifying the version.

**Comment by MarcoGorelli** [comment]
> C:\Users\user\app\venv\lib\site-packages\pandas_init_.py

I don't have such a file in my `site-packages` folder - can you try re-installing pandas in a new virtual environment?

**Comment by TomAugspurger** [comment]
@kevinksyTRD any followup here?

**Comment by kevinksyTRD** [comment]
It worked with a new installation. Can’t reproduce the error.

**Comment by frank9th** [comment]
I get same pandas attribute error. i followed the instruction above and installed it on a new environment but i still have the same error after importing pandas in my project. what can i do further please.

**Comment by MarcoGorelli** [comment]
can you show the traceback?

**Comment by frank9th** [comment]
I got it fixed already by installing an earlier version 1.0.0. but this was the error;

  File "C:\lib\site-packages\pandas\core\series.py", line 4562, in Series
    plot = CachedAccessor("plot", pandas.plotting.PlotAccessor)
AttributeError: partially initialized module 'pandas' has no attribute 'plotting' (most likely due to a circular import)
