### ISSUE TITLE
What is the best way to normalize_json before read_json for the file with gigabytes size?

### ISSUE THREAD

**Issue by anki-code** [pandas-dev/pandas#34028]
Hello! Thank you for pandas! It's great!

Is there an elegant way to do `normalize_json` before `read_json` in stream/chunks (to avoid loading a big gygabyte file to the memory and then normalizing and then read_json)?

Thanks!

**Comment by WillAyd** [comment]
normalize_json today unfortunately doesn't support any chunking of data

You can of course read json by lines but would need a community PR to support what I think you are really looking for

**Comment by mroeschke** [comment]
Thanks for the request, but it appears this hasn't gain traction in a while so closing
