### ISSUE TITLE
DOC: Series.str.rstrip() and Series.str.lstrip() have incorrect description at the top

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#34026]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.rstrip.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.lstrip.html

#### Documentation problem

At the top of the documentation for the `rstrip()` and `lstrip()` methods, it says "Remove leading and trailing characters."  

#### Suggested fix for documentation

It should say "Remove trailing characters" for `rstrip()` and "Remove leading characters" for `lstrip()`.

This is due to the way that the shared docs are set up between `str.lstrip()`, `str.rstrip()` and `str.strip()`

**Comment by moaraccounts** [comment]
Hello! n00b here - I'll take this.

**Comment by Harshal96** [comment]
Take @MarcoGorelli
