### ISSUE TITLE
BUG: Pandas Cython pd.sort_values() function, ignore_index DOESN'T WORK

### ISSUE THREAD

**Issue by edin0** [pandas-dev/pandas#34038]
- [ ] I have checked that this issue has not already been reported.
yes
- [ ] I have confirmed this bug exists on the latest version of pandas.
yes
- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.
idk
<img width="646" alt="Capture d’écran 2020-05-07 à 00 12 24" src="https://user-images.githubusercontent.com/60808981/81234096-635e3080-8ff8-11ea-9f53-3c9709a66f34.png">

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here

```

#### Problem description
The code works on python3, but not on Cython. It works when I delete "ignore_index=True" from my code, but then the output is obviously wrong :(
(sorry for censoring, I don't want to leak anything)
[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Expected Output
ignore_index should work on Cython 
#### Output of ``pd.show_versions()``
1.0.3
<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by mroeschke** [comment]
We would need a reproducible example. The behavior might be able to be replicated with fake data: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by edin0** [comment]
yes sure ! 
here is my file example : 
[index_value_cython_error.zip](https://github.com/pandas-dev/pandas/files/4589800/index_value_cython_error.zip)

run in the folder: 
python3 setup.py build_ext --inplace

then run :  
python3 testing.py

thank you for the answer.

**Comment by mroeschke** [comment]
Ideally a minimal example that can be copy and pasted in a console like:

```
In [1]: pd.DataFrame(...).sort_index(by=[...], ignore_index=True)
```

It is unlikely that this is an issue with Cython.

**Comment by edin0** [comment]
Oh my bad sorry  : 
`pd.DataFrame({'account-start': ['2017-02-03', '2017-03-03', '2017-01-01'],'client': ['Alice Anders', 'Bob Baker', 'Charlie Chaplin'],'balance': [-1432.32, 10.43, 30000.00],'db-id': [1234, 2424, 251],'proxy-id': [525, 1525, 2542],'rank': [52, 525, 32],}).sort_values(by=['client', 'account-start'], inplace=True, ignore_index=True)`
(something like this I guess ?)
do you have an idea where the error could come from ?

**Comment by mroeschke** [comment]
It looks like it's working locally for me

```
In [9]: df.sort_values(by=['client', 'account-start'], inplace=True, ignore_index=True)

In [10]: df
Out[10]:
  account-start           client   balance  db-id  proxy-id  rank
0    2017-02-03     Alice Anders  -1432.32   1234       525    52
1    2017-03-03        Bob Baker     10.43   2424      1525   525
2    2017-01-01  Charlie Chaplin  30000.00    251      2542    32

In [11]: pd.__version__
Out[11]: '1.0.3'
```

**Comment by MarcoGorelli** [comment]
@edin0 can you show the full output of `pd.show_versions()` (as in the issue template) please?

**Comment by edin0** [comment]
Oh sorry I should have closed the issue since I found the problem. I usually use PyCharm so my pandas version was up to date. The pandas on my pc was outdated though which is why index_ignore didn’t work ! 
Quick update in the terminal for anyone having a similar issue : 
`pip3 install —upgrade pandas`
Sorry for bothering and thank you for your help!
