### ISSUE TITLE
ENH: piped alias for .merge(left_index=True,right_index=True,how='outer')

### ISSUE THREAD

**Issue by MiguelArriaga** [pandas-dev/pandas#34046]
#### Is your feature request related to a problem?

The way to merge two dataframes by index and default 'outer' is to use concat(axis=1), but this does not work if I want to follow a piped workflow. I would like to do the equivalent of df.merge(left_index=True,right_index=True,how='outer') but in a less verbose way.

#### Describe the solution you'd like

```python
def merge_byindex(self,df2,how='outer',**kwargs):
    """Merge input DataFrame by index.

         It is equivalent to doing pd.DataFrame.merge(left_index=True,right_index=True,how='outer',**kwargs).
    """
    return self.merge(df2,left_index=True,right_index=True,how='outer',**kwargs)
```
#### API breaking implications

no breaking implications

#### Describe alternatives you've considered

The natural alternative is to just keep doing .merge(left_index=True,right_index=True,how='outer')

#### Additional context

The reasons for having this as a separate function are the following:

1. The level of verbosity required to do this simple operation seems unreasonable.
2. Seems that maybe this particular operation could be more efficient than a general merge.
3. It would greatly simplify the documentation for this particular operation

**Comment by Liam3851** [comment]
Does DataFrame.combine_first work for your use case? It takes two DataFrames, unions their indices and columns, and defaults to using the value from the first DF if there is an overlap. I think it has the exact behavior you describe in the case where the two DataFrames have non-overlapping columns.

```python
In [3]: pd.DataFrame({'a':[1, 2, 3], 'b':[4, 5, 6]}) \
          .combine_first(pd.DataFrame({'c':[1, 2, 3], 'd':[4, 5, 6]}, index=[1, 2, 3]))
Out[3]:
     a    b    c    d
0  1.0  4.0  NaN  NaN
1  2.0  5.0  1.0  4.0
2  3.0  6.0  2.0  5.0
3  NaN  NaN  3.0  6.0

In [4]: pd.DataFrame({'a':[1, 2, 3], 'b':[4, 5, 6]}) \
          .merge(pd.DataFrame({'c':[1, 2, 3], 'd':[4, 5, 6]}, index=[1, 2, 3]), left_index=True, right_index=True, how='outer')
Out[4]:
     a    b    c    d
0  1.0  4.0  NaN  NaN
1  2.0  5.0  1.0  4.0
2  3.0  6.0  2.0  5.0
3  NaN  NaN  3.0  6.0
```

**Comment by MiguelArriaga** [comment]
That is indeed an interesting alternative, although the behavior in case of repeated columns would be important to keep. 

I think that for my case I will stick to merge since the future readers of the code would probably understand better if they saw "merge(left_index=True,right_index=True,how='outer')" than if they saw "combine_first".

I guess this more of a philosophical question whether or not it is useful to have simplified aliases for a very general function. Like having `merge` and then `merge_byindex` as a simplified version of merge, which could potentially be optimized for this use but not necessarily, being the only advantage readability. 

Thanks for the tip regarding `combine_first`. This could come in handy in the future.

**Comment by Liam3851** [comment]
@MiguelArriaga You may also want to look at DataFrame.join for the case with duplicates:

```python
In [14]: pd.DataFrame({'a':[1, 2, 3], 'b':[4, 5, 6]}) \
    ...:           .join(pd.DataFrame({'c':[1, 2, 3], 'd':[4, 5, 6], 'b':[7, 8, 9]}, index=[1, 2, 3]), how='outer', rsu
    ...: ffix='_y')
Out[14]:
     a    b    c    d  b_y
0  1.0  4.0  NaN  NaN  NaN
1  2.0  5.0  1.0  4.0  7.0
2  3.0  6.0  2.0  5.0  8.0
3  NaN  NaN  3.0  6.0  9.0
```

though now you would need to specify how='outer' and a suffix if there's a duplicate column.

```python
df.join(df2, how='outer', rsuffix='_y')
```

If that still feels too verbose to you because you do this a lot, I'd suggest defining a custom method and using `.pipe`:

```python
df.pipe(merge_by_index, df2)
```

Only 5 characters longer than df.merge_by_index(df2).

**Comment by TomAugspurger** [comment]
Thanks, I think @Liam3851's suggestion looks reasonable. I think adding a dedicated method for this isn't needed.
