### ISSUE TITLE
BUG: DataFrameGroupBy.sum ignores min_count for boolean data type

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#34051]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of pandas.
- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

Behavior is from master:

```python
import pandas as pd

df = pd.DataFrame({"a": [1, 2], "b": pd.array([True, True])})
df.groupby("a").sum(min_count=2)
```
gives
```python
      b
a      
1  True
2  True
```
but expected output is
```python
      b
a      
1  <NA>
2  <NA>
```

It looks to me like there's an attempt to compute a Cythonized result which fails, after which point the min_count argument is forgotten.

**Comment by simonjayhawkins** [comment]
This also occurs for Timedelta

```
>>> import pandas as pd
>>>
>>> pd.__version__
'1.1.0.dev0+1537.g6be51cb65b'
>>>
>>> df = pd.DataFrame(
...     {"foo": ["a", "a", "a"], "bar": [pd.Timedelta("1D"), pd.Timedelta("2D"), None]}
... )
>>>
>>> df
  foo    bar
0   a 1 days
1   a 2 days
2   a    NaT
>>>
>>> grp = df.groupby("foo")["bar"]
>>>
>>> grp.sum(min_count=3)
foo
a   3 days
Name: bar, dtype: timedelta64[ns]
>>>
```
