### ISSUE TITLE
BUG: str.contains() doesn't apply AND and OR properly

### ISSUE THREAD

**Issue by Maxence-L** [pandas-dev/pandas#34068]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
test_df = pd.DataFrame({'col1' : ['ab','bc']})

print(test_df['col1'].str.contains('a' or 'b'))

print(test_df['col1'].str.contains('a' and 'b'))


```

#### Problem description

Using logical 'and' in str.contains without regex applies a logical 'or'.
Using logical 'or' in str.contains without regex applies a logical 'and'.

#### Expected Output
The code above returns :
0    True
1    False
Name: col1, dtype: bool

0    True
1    True
Name: col1, dtype: bool

But it should be :

0    True
1    True
Name: col1, dtype: bool

0    True
1    False
Name: col1, dtype: bool

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None

pandas           : 1.0.3
numpy            : 1.18.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 10.0.1
setuptools       : 39.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : 1.3.0
xlsxwriter       : None
numba            : None

</details>

**Comment by TomAugspurger** [comment]
In Python the arguments are evaluated first, so your example is equivalent to

```python
