### ISSUE TITLE
BUG: SettingWithCopyWarning:  A value is trying to be set on a copy of a slice from a DataFrame

### ISSUE THREAD

**Issue by DSKaarthick** [pandas-dev/pandas#34078]
#### Code Sample, a copy-pastable example

```python
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import gensim 
from gensim.models import FastText
from sklearn.feature_extraction.text import TfidfVectorizer
from difflib import SequenceMatcher

#Loading Query Text for Corpus Building
qt=pd.read_csv('C:/Demo/Query_Text.csv')
qt.shape

#Loading QueryText for comparing

convid =pd.read_csv('C:/Demo/ConvId_May4th.csv')

convid.shape

sentences = qt


convid = convid.sort_values(['User_PUID','EventInfo_Time'], ascending=[True,True])
convid = convid.reset_index()
convid['FastTextResult'] =float()
convid['Tfidf'] = float()
convid['TfidfWc'] = float()

model_ted = FastText(qt,  window=1, min_count=1, sg=0)

for i in range(len(convid['Query_Text'])):
    print('i',i)
    if(i == len(convid)-1):
            break
    
    #print("The FastText Output")
    
    ft=model_ted.wv.similarity(str(convid['Query_Text'][i]).lower(),str(convid['Query_Text'][i+1]).lower())
    ft=round(ft,3)
    #print(ft)
    convid['FastTextResult'][i]=ft;
    
    #print("vector output ")
    
    vectorizer = TfidfVectorizer(decode_error='ignore',strip_accents='unicode',stop_words='english',min_df=1,analyzer='word',vocabulary=qt) 
    tfidf= vectorizer.fit_transform([str(convid['Query_Text'][i]).lower(),str(convid['Query_Text'][i+1]).lower()])
    product=(tfidf *tfidf.T).A
    pro = product[0,1]
    pro = round(pro,3)
    #print(pro)
    convid['Tfidf'][i]=pro;
    
    #print("widlchar")
    wildchar_value = SequenceMatcher(str(convid['Query_Text'][i]).lower(),str(convid['Query_Text'][i+1]).lower()).ratio()
    
    wildchar_value = round(wildchar_value,3)

    convid['TfidfWc'][i]=wildchar_value;
    #print(wildchar_value)

convid.to_csv('C:/Demo/ConvIdOutput_May4th.csv')





```

#### Problem description

when i am trying to execute the above python script , getting the following error:

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

#### Expected Output

The above code should 
#### Output of ``pd.show_versions()``

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.3
numpy            : 1.18.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.3.post20200330
Cython           : None
pytest           : 5.4.1
hypothesis       : None
sphinx           : 2.4.4
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.2.1
numexpr          : 2.7.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.4.1
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

**Comment by mroeschke** [comment]
See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy.

This is just a warning and you may get the expected output in your code.

`convid['Tfidf'][i]=pro` is an example of chain indexing. You can avoid this by using `loc` and `iloc` for assignment
