### ISSUE TITLE
QST: Distinguishing row and column slices in DataFrame subclass

### ISSUE THREAD

**Issue by zhenruiliao** [pandas-dev/pandas#34089]
- [X ] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com/questions/61246252/distinguish-column-and-row-slice-in-pandas-subclass).

---

Hi pandas devs,

What is the best way to distinguish whether a row or column was sliced in a DataFrame subclass? I am designing a subclass where row slices should return my custom Series/DF subclass, but columns are just vanilla pd.Series. In addition, I want non-slice calls to `_constructor` (e.g., `apply`) to simply return vanilla DataFrames. Is there a straightforward way to do this?

Thanks for a great package!

**Comment by zhenruiliao** [comment]
just wanted to bump this - any thoughts on workarounds also welcome!

**Comment by jbrockmendel** [comment]
> Is there a straightforward way to do this?

Not really.  I think you'd need to go into core.indexing and tinker around with Loc/iLoc

**Comment by jbrockmendel** [comment]
Closing as answered.  We can re-open if you'd like to purse this further.
