### ISSUE TITLE
DISC: Deprecate use_inf_as_na

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#34093]
I think a case could be made for deprecating pd.options.mode.use_inf_as_na. Few thoughts:

* Doesn't seem necessary or particularly useful: it's easy to get the same behavior by checking for NA _or_ infinity.
* Source of bugs: e.g., https://github.com/pandas-dev/pandas/issues/33655, https://github.com/pandas-dev/pandas/issues/33594. If an array has a cached mask attribute there's no guarantee that it's correct:
  ```python
  import numpy as np
  import pandas as pd

  arr = pd.Categorical([1.0, 2.0, np.inf])
  pd.options.mode.use_inf_as_na = True
  arr.isna().any()  # False
  ```
* General maintenance cost: several null-checking functions either have to be duplicated or equipped with boolean arguments to switch their behavior (e.g., _isna and _isna_ndarraylike from /core/dtypes/missing.py, or isnaobj and isnaobj_old from /_libs/missing.pyx). These could all be cleaned up if NA had _one_ meaning.

Thoughts?

**Comment by jbrockmendel** [comment]
xref #28392
