### ISSUE TITLE
BUG:pd.value_counts() When the values are equal, the order of equal values is invalid

### ISSUE THREAD

**Issue by sun1638650145** [pandas-dev/pandas#34098]
```python
import pandas as pd
df = pd.DataFrame([('a', 1), ('b', 1), ('c', 3), ('a', 1), ('b', 1)])
print(pd.value_counts(df[0], sort=True))
# you can see two situations
# b    2
# a    2
# c    1
# Name: 0, dtype: int64
# a    2
# b    2
# c    1
# Name: 0, dtype: int64
```

#### Problem description

When the values are equal, the order of equal values is invalid, Sorting is only for values, no index is processed

#### Expected Output

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.4.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : zh_CN.UTF-8

pandas           : 1.0.3
numpy            : 1.18.4
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1
setuptools       : 46.1.3
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.2.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
None

</details>

**Comment by dsaxton** [comment]
The sorting only deals with the values and not the index so I believe this is correct as is

**Comment by sun1638650145** [comment]
Sorry, but I think this function should be sorted when the values are the same, otherwise, use another function to process it again?

**Comment by dsaxton** [comment]
> Sorry, but I think this function should be sorted when the values are the same, otherwise, use another function to process it again?

Again it's the _counts_ that are sorted and when they're equal there's nothing left to sort. If you would  also like to sort by the index then that would have to be done using some custom code.

**Comment by sun1638650145** [comment]
OK fine
