### ISSUE TITLE
ENH: enable concat for nullable Int with other dtypes

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#34095]
Following-up on https://github.com/pandas-dev/pandas/pull/33607 which added the `ExtensionDtype._get_common_dtype` method to the EA interface to determine concat/append behaviour, we can now use this to refine the concat behaviour for nullable integer and boolean dtypes.

See comment here: https://github.com/pandas-dev/pandas/pull/33607#discussion_r410127707

For now, the PR only enabled concat of all IntegerDtype objects (any other combination will result in object dtype). But, we can expand this to the combination of IntegerDtype with numpy int dtype, Int with boolean, Int with float, etc

**Comment by jorisvandenbossche** [comment]
As a concrete example, this currently gives object dtype:

```
In [14]: pd.concat([pd.Series([1, 2, None], dtype="Int64"), pd.Series([4, 5], dtype="int64")])
Out[14]: 
0       1
1       2
2    <NA>
0       4
1       5
dtype: object
```

while it could perfectly preserve the nullable Int64 dtype.

(cc @dsaxton in case you are interested ;))

**Comment by dsaxton** [comment]
@jorisvandenbossche Interesting, how do you envision the case of concating nullable ints and floats? Try casting the float values to nullable int if possible, else use float? I suppose always converting to the more general float type seems more natural in that it would depend entirely on the types and not the values, but then the NAs would be lost (at least until there's a nullable float).

**Comment by jorisvandenbossche** [comment]
We want to move not have any value-depending concat/cast behaviour (right now we have such a few cases), so this means that int+float should always result in float. 
Yes, that for now means that nullable dtype gets lost, so in theory we could also preserve object. But I don't think which of the two we take now is that important, in the hope there will be a beginning of a nullable float dtype soon.

**Comment by TomAugspurger** [comment]
@jorisvandenbossche what else do you want to do here for 1.1? Currently, `concat([Int64, int64])` correctly returns `Int64`.

I think the remaining issue is for `concat([Int64, boolean])` to return Int64? Anything else/

**Comment by jorisvandenbossche** [comment]
Indeed, with boolean we can already preserve the nullable dtype. For float we have to wait on the Floating EA PR. And Int64+int64 (with numpy dtype) I did in a previous PR. 
-> https://github.com/pandas-dev/pandas/pull/34985 for the boolean case + adding tests for Int64+int64
