### ISSUE TITLE
BUG: Index with tuples comparison not working anymore

### ISSUE THREAD

**Issue by charlesdong1991** [pandas-dev/pandas#34123]
It seems trace back to #34081

with Index we could do something like:
```python
>>> pd.Index(['a', 'b', 'c']) == 'c'
array([False, False,  True])
```
And it's also possible to do the same for Index with tuples:
```python
>>> pd.Index([('a', 'b'), ('b', 'c'), ('c', 'a')]) == ('c', 'a')
array([False, False, True])
```
But seems not working this way anymore after #34081 , is this length check here correct (so it is designed this way on purpose)? or we should consider it a bug?

cc @jbrockmendel 

currently master:
```python
>>> pd.Index([('a', 'b'), ('b', 'c'), ('c', 'a')]) == ('c', 'a')
ValueError: ('Lengths must match', (3,), (2,), <class 'tuple'>)
```

**Comment by jbrockmendel** [comment]
Hmm good point.  May be best to just revert #34081.

**Comment by jbrockmendel** [comment]
or could treat tuples different from other listlikes

**Comment by charlesdong1991** [comment]
take

**Comment by jorisvandenbossche** [comment]
It's not just tuples, it's also any other "scalar" object that might have a length (eg dicts when storing those, but for example also Shapely geometries). 
I seem to remember we have had this conversation before .. (don't directly remember the exact issue though)

I would maybe start with reverting, and can then try to think of a better solution.

**Comment by jorisvandenbossche** [comment]
It seems @jbrockmendel actually recorded those concerns in an issue before: https://github.com/pandas-dev/pandas/issues/27911

**Comment by charlesdong1991** [comment]
emm, okay, i haven't looked at the changes in detail, sounds impact quite many cases. maybe let's revert it first then. thanks for the input @jorisvandenbossche
