### ISSUE TITLE
BUG: Join of DataFrames with MultiIndex does not keep order of index

### ISSUE THREAD

**Issue by rikardn** [pandas-dev/pandas#34133]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import numpy as np
import pandas as pd

arrays = [np.array(['top', 'top', 'top', 'top', 'bottom', 'bottom', 'bottom', 'bottom']),
          np.array(['bar', 'bar', 'baz', 'baz', 'bar', 'bar', 'baz', 'baz']),
          np.array(['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two'])]

left = pd.DataFrame(np.random.randn(8, 4), index=arrays)
left.index.set_names(['pos', 'vars', 'numbers'], inplace=True)

right = pd.DataFrame({'vars': ['bar', 'bar', 'baz', 'baz'], 'numbers': ['one', 'two', 'one', 'two'], 'value': [1, 2, 3, 4]})
right = right.set_index(['vars', 'numbers'])
joined = left.join(right)

print(left.index.names)
print(joined.index.names)
```

output
```
['pos', 'vars', 'numbers']
['vars', 'numbers', 'pos']
```
#### Problem description

When two multindexed DataFrames are joined on a subset of the left index the resulting index becomes reordered.

#### Expected Output

I expect the order of the left dataframe to be kept after the left join.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.3.0-51-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.16.2
pytz             : 2019.2
dateutil         : 2.7.3
pip              : 18.1
setuptools       : 41.1.0
Cython           : None
pytest           : 3.7.4
hypothesis       : None
sphinx           : 2.4.4
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.10.2
pandas_datareader: None
bs4              : 4.9.0
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.1.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 3.7.4
pyxlsb           : None
s3fs             : None
scipy            : 1.1.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 0.14.1
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by lukemanley** [comment]
When left and right indexes have a different number of levels, the current behavior is to order the output as: 

```
common levels + left levels not in right levels + right levels not in left levels
```

I agree this behavior seems odd. I would expect a left join to maintain the order of the left index levels. However, changing the behavior would break a few tests. 

cc @mroeschke if any thoughts?

**Comment by mroeschke** [comment]
How many tests break if we change this behavior? Also agreed not sorting would be better behavior here

**Comment by lukemanley** [comment]
> How many tests break if we change this behavior? Also agreed not sorting would be better behavior here

I opened #55370 showing what would need to be updated
