### ISSUE TITLE
CI: test_object_factorize_dropna failing in MacPython/pandas-wheels

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#34130]
https://dev.azure.com/pandas-dev/pandas-wheels/_build/results?buildId=35317&view=logs&j=79f3a53a-4a6d-509c-98b5-ff6e9111f67c&t=25a63239-9c30-5cf0-cb4c-3d01da7b47c5

```python
    def test_object_factorize_dropna(
        self, data, dropna, expected_codes, expected_uniques
    ):
        codes, uniques = algos.factorize(data, dropna=dropna)
    
        tm.assert_numpy_array_equal(uniques, expected_uniques)
>       tm.assert_numpy_array_equal(codes, expected_codes)
E       AssertionError: numpy array are different
E       
E       Attribute "dtype" are different
E       [left]:  int32
E       [right]: int64
```

I'm not sure what the correct behavior is here, but the implementation is returning int32 while we're asserting int64. The test should probably check for `np.dtype("intp")`.

**Comment by charlesdong1991** [comment]
emm, yeah this was brought in #30584 and i did observe issues with dtypes in windows machine, that's why to force to `int64` back then, but probably should better use `intp` .

btw, i think this should have milestone for `1.1`? since the pr that brought this issue has the 1.1 milestone.

**Comment by TomAugspurger** [comment]
Thanks, good call on the milestone.
