### ISSUE TITLE
May 2020 Dev Meeting

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#34142]
The monthly dev meeting is tomorrow, Wednesday 13th, at 18:00 UTC. Our calendar is at https://pandas.pydata.org/docs/development/meeting.html#calendar to check your local time.

Video Call: https://zoom.us/j/942410248
Minutes: https://docs.google.com/document/u/1/d/1tGbTiYORHiSPgVMXawiweGJlBw5dOkVJLY-licoBmBU/edit?ouid=102771015311436394588&usp=docs_home&ths=true

Please add items you'd like to see discussed to the agenda.

**Comment by dair-targ** [comment]
Is the video call open to everybody to shadow/participate?

**Comment by TomAugspurger** [comment]
Yep, it's open to everyone.
