### ISSUE TITLE
BUG: Pandas import error Python 2.7.6 isinstance() arg 2 must be a class, type, or tuple of classes and types 

### ISSUE THREAD

**Issue by barenn7** [pandas-dev/pandas#34156]
Hi,

I am obliged to use Python 2.7.6 and pandas below 0.24.2.

The only thing I am trying to do as for now is 'import pandas'.

And I keep getting the error below. I have checked online and tslib was fixed in new versions but I have to stay on 2.7.6.
I have already tried pip uninstall and pip install again.

Any possible fix you might know of ? 

Thanking you very much for your answer,
Regards and take care

ERROR LOG:
---------------------------------------------------------------------------------------------------------------

468","import   pandas |  
468","  File "C | \Python27\lib\site-packages\pandas\__init__.py", line   42, in <module>
  |  
468","from pandas.core.api import * |  
  |  
468","    File "C | \Python27\lib\site-packages\pandas\core\api.py",   line 10, in <module>
  |  
468","from   pandas.core.groupby import Grouper |  
  |  
468","  File "C | \Python27\lib\site-packages\pandas\core\groupby.py",   line 47, in <module>
  |  
468","from pandas.core.index import   (Index, MultiIndex, |  
  |  
468","    File "C | \Python27\lib\site-packages\pandas\core\index.py",   line 2, in <module>
  |  
468","from   pandas.core.indexes.api import * |  
  |  
468","  File "C | \Python27\lib\site-packages\pandas\core\indexes\api.py",   line 9, in <module>
  |  
468","from pandas.core.indexes.interval   import IntervalIndex  # noqa |  
  |  
468","    File "C | \Python27\lib\site-packages\pandas\core\indexes\interval.py",   line 30, in <module>
  |  
468","from   pandas.core.indexes.datetimes import date_range |  
  |  
468","  File "C | \Python27\lib\site-packages\pandas\core\indexes\datetimes.py",   line 39, in <module>
  |  
468","from pandas.tseries.frequencies   import ( |  
  |  
468","    File "C | \Python27\lib\site-packages\pandas\tseries\frequencies.py",   line 18, in <module>
  |  
468","from   pandas.tseries.offsets import DateOffset |  
  |  
468","  File "C | \Python27\lib\site-packages\pandas\tseries\offsets.py",   line 2692, in <module>
  |  
484","class Tick(SingleConstructorOffset) |  
  |  
484","    File "C | \Python27\lib\site-packages\pandas\tseries\offsets.py",   line 2693, in Tick
  |  
484","_inc   = Timedelta(microseconds=1000) |  
  |  
484","  File "pandas\_libs\tslib.pyx",   line 2585, in pandas._libs.tslib.Timedelta.__new__ |  
  |  
484","TypeError"
484","isinstance()   arg 2 must be a class, type, or tuple of classes and types 
  |  
484","Python interpretor failed

**Comment by MarcoGorelli** [comment]
How did you install it? I just tried
```bash
$ conda create -n python2 python=2.7
$ conda activate python2
$ pip install pandas==0.24.2
$ python
```
```python
import pandas
```
and it worked just fine

**Comment by barenn7** [comment]
Hi,

Thanking you very much for your answer, I installed Python 2.7.6 with https://www.python.org/ and not conda.

Then I used pip install. It is working in the python interpreter. 

But I am using a software called ADTF that is calling the python interpreter and I get the above error. 

The software is only calling the python interpreter, so we are thinking that the issue is coming from python.

And that is where I am stuck, maybe there is a manual fix I can make to make this work and fix the error ? 

Thanks again in advance for your reply,
Best regards

**Comment by MarcoGorelli** [comment]
>  It is working in the python interpreter.

Just to make sure I've understood - so, if you type `python` and, inside the Python repl, type `import pandas`, then it works, but it doesn't work when ADTF calls the Python interpreter?

**Comment by barenn7** [comment]
If I go in c:\Python27 and I open python.exe. I run the command import pandas it is working and I am able to use the library.

And when ADTF software calls my python script and the interpreter, the above error is showing. 

I an sure that ADTF is calling the right library pandas in C:/Python27 in site packages.

**Comment by barenn7** [comment]
Tslib import is really blocking and giving the errors. Do you know how I could remove this import from pandas manually?

**Comment by TomAugspurger** [comment]
Sorry, but we aren't supporting 2.7 anymore, closing.
