### ISSUE TITLE
BUG: str.split fails on a multiple character match

### ISSUE THREAD

**Issue by pblankley** [pandas-dev/pandas#34155]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
test_df = pd.DataFrame({
    'fails': ['let me||test', 'the||splitting']
})

test_df['fails'].str.split('||')

```

#### Problem description

I expect pandas to retain the same behavior as `str.split` and return the split column.

However, it doesn't handle multiple characters, and throws this instead (I didn't include the whole traceback to keep the issue clean).

```python
ValueError: split() requires a non-empty pattern match.
```

#### Expected Output

```python
0      [let me, test]
1    [the, splitting]
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 9f69ccadffbc67de0c946e4fd9f22d41d30392f3
python           : 3.6.8.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.4.0
Version          : Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.0.dev0+1563.g9f69ccadf
numpy            : 1.18.4
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 18.1
setuptools       : 40.6.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by MarcoGorelli** [comment]
Thanks @pblankley 

If you escape the `|` it works:
```python
>>> test_df['fails'].str.split(r'\|\|')
0      [let me, test]
1    [the, splitting]
Name: fails, dtype: object
```
