### ISSUE TITLE
ENH: Allow for `loc` to specify numeric and/or name slicing

### ISSUE THREAD

**Issue by lazarillo** [pandas-dev/pandas#34153]
#### Is your feature request related to a problem?

Yes. The problem is that many use cases require specifying a numeric row range (say, the 10th - 20th rows) and a name-based column range (columns "timestamp" and "value").

As of now, the most consistent way to solve it is:

```python
df.loc[df.index[start_val:(end_val + 1)],cols_of_interest]
```

This is not ideal because

1. It is long and ugly to need to use `df.index` at all.
1. Notice the `(end_val + 1)`:  While most of Python uses exclusive ranges (eg, `range(1,3)` does not include `3`), `pandas`' `loc` is inclusive.  So, developers get used to `df.loc[1:3,'a']` giving all three rows.

#### Describe the solution you'd like

[this should provide a description of the feature request, e.g. "`DataFrame.foo` should get a new parameter `bar` that [...]", try to write a docstring for the desired feature]

`DataFrame.loc` should have a new argument `num_idxs` which is a boolean list of 2 values, specifying whether the row or column indices should be numeric or names.  Eg, `[True, False]` means that the rows should be treated as numeric and the columns as names.

This argument should have a default value of `None`, since default lists are dangerous in Python, but that `None` should resolve to `[True, False]`, since this is the most common situation that most of us want (I think).

The behavior of numeric should be exactly identical to the current implementation of `iloc`.  The behavior of names should be identical to `loc`, currently.

#### API breaking implications

[this should provide a description of how this feature will affect the API]

The only API breaking implication I am aware of is that using the default I suggested (rows being treated as numeric) will create "off-by-one" issues, since `iloc` is exclusive and `loc` is inclusive.

This could potentially be handled by first making the default resolve to `[False, False]` upon initial introduction, but it should eventually be deprecated to `[True, False]` as I say above, since this is the most common case.

#### Describe alternatives you've considered

[this should provide a description of any alternative solutions or features you've considered]

As mentioned above, I sprinkle my code with the ugly:

```python
df.loc[df.index[start_val:(end_val + 1)],cols_of_interest]
```

The reason this is necessary is because (a) row *names* rarely mean anything to me in my work, and (b) I try to make code as generalizable as possible.

#### Additional context

I feel the description above covers it, but I am happy to add some examples if there is confusion.

**Comment by MarcoGorelli** [comment]
Thanks @lazarillo for the suggestion - would something like `df.loc[:, cols_of_interest].iloc[start_val:end_val]` work for you?

TBH I'm at least 99% confident that the core team would not consider adding a `num_idxs` argument to `loc`

**Comment by MarcoGorelli** [comment]
Indeed, if I've understood correctly, your request is for something like [DataFrame.ix](https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.DataFrame.ix.html#pandas-dataframe-ix), which has been deprecated _in favour_ of the more explicit `loc` and `iloc`

**Comment by charlesdong1991** [comment]
yep, as @MarcoGorelli mentioned, `df.loc[code].iloc[code]` is the answer for your question, it is explicit and also nice for chaining!

**Comment by lazarillo** [comment]
@MarcoGorelli @charlesdong1991  I would be OK with `df.loc[:,cols_of_interest].iloc[start_val:end_val]` if I knew it were stable. My understanding is that regardless of the means by which we do it, we should **never stack indexing** because it may be inconsistent, right?  And even if it were consistent, doesn't it also carry a significant performance hit?

I guess I have two main issues / concerns:

1) **Almost everyone** uses numeric rows and named columns.  Why isn't that combination viable in some fashion?  Newbie users don't even realize that they are accessing rows by names, and I suspect this leads to a TON of hard-to-find bugs.  And more experienced users find themselves jumping through hoops like what I expressed.

2) I do not understand what the problem was with `ix`.  I remember it, and I liked it, except for the minor issue that `ix` was not an ideal name.  If the problem is performance, folks need to realize that neither `loc` nor `iloc` fix it, since we need to mix and match numeric and names anyway.

But it does not even need to flexibly allow numbers or names in any combination, per se.  It just needs to work in a way that we are all already using it anyway: with numeric rows and named columns.

**Comment by MarcoGorelli** [comment]
> My understanding is that regardless of the means by which we do it, we should never stack indexing because it may be inconsistent, right? 

Why not? (I'm asking because it's not something I've come across, not because I think you're wrong)

**Comment by lazarillo** [comment]
It's [this whole discussion](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#why-does-assignment-fail-when-using-chained-indexing) in the official docs that makes me nervous about touching any stacked indexing.

When I saw the comment in that doc which said `# Is foo a view? A copy? Nobody knows!`, I was very concerned that there was a non-determinancy happening.  :(

**Comment by jreback** [comment]
@lazarillo this only applies to setting not getting as should be clear

and it’s not non determinism it’s how views work
