### ISSUE TITLE
BUG: Index formed with list of tuples return wrong output in eq ops

### ISSUE THREAD

**Issue by charlesdong1991** [pandas-dev/pandas#34180]
xref #34137

Currently

```python
>>> pd.Index([('a', 'b'), ('b', 'c'), ('c', 'a')]) == ('c', 'a')
>>> array([False, False, False])
```
The issue is such case is treated as a MultiIndex other than plain Index.

Expected:
```python
>>> pd.Index([('a', 'b'), ('b', 'c'), ('c', 'a')]) == ('c', 'a')
>>> array([False, False, True])
```

**Comment by asishm** [comment]
@charlesdong1991 It seems this is currently failing on master with `ValueError: ('Lengths must match to compare', (3,), (2,))`
