### ISSUE TITLE
DEPR: deprecate Index.__getitem__ with float key

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#34191]
I would propose to deprecate interpreting float numbers as integers in Index `__getitem__`.

Numpy does (no longer) allow this:

```
In [1]: a = np.array([1, 2, 3])   

In [3]: a[0.0]      
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-2ec1d2c6d8d4> in <module>
----> 1 a[0.0]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

With a Series with `iloc`, we also don't allow this:

```
In [7]: pd.Series(a).iloc[0.0] 
...
TypeError: Cannot index by location index with a non-integer key
```

But for Index we do check if the float is integer-like and in that case convert to integer:

```
In [5]: pd.Index(a)[0.0]  
Out[5]: 1
```

However, this is not for all Index subclasses the case, eg:

```
In [9]: pd.DatetimeIndex(a)[0.0]                                                                                                                                                                                   
...
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

So I think we can simply deprecate this to align Index with numpy/Series/some Index subclasses.

**Comment by jbrockmendel** [comment]
Can you specify which Index subclasses and methods would be affected?

In particular, would this address #33469, #31344, #7501

**Comment by jorisvandenbossche** [comment]
@jbrockmendel all the issue you link to are about `Series.__getitem__` with a float/integer index, this is about `Index.__getitem__` with a float/integer key. 

I had searched for related issues, but didn't directly find any, so opened this one.

This is the case for where `com.cast_scalar_indexer` is used in the `__setitem__` definition, which means the base class Index (and the numeric subclasses that inherit setitem) and MultiIndex, and *not* for any of the ExtensionIndex subclasses (since that redefines ``__setitem__`` without using  `com.cast_scalar_indexer`)

**Comment by jbrockmendel** [comment]
Thanks for clarifying.

**Comment by jorisvandenbossche** [comment]
There is a PR, if you want to see it in code ;)
