### ISSUE TITLE
Option to return all idxmax rows in case of ties

### ISSUE THREAD

**Issue by GodefroyClair** [pandas-dev/pandas#34205]
What do you think of adding an option to « idmax » in order to return not just the first idmax but all of them in case of ties.

I think this would be really useful, especially  when used with groupby. For exemple when you want the most recent yearly published data for an entity - say a company.

We could simply add a Boolean to the function like returnTies that would be false by default.

**Comment by charlesdong1991** [comment]
emm, sounds fair. 

maybe add `keep` option similar to `nlargest` or `nsmallest`?

**Comment by MatthewMoye** [comment]
take

**Comment by simonjayhawkins** [comment]
> maybe add `keep` option similar to `nlargest` or `nsmallest`?

so for api consistency we may also want to add a `keep='last'` option and also add it to argmax/argmin

**Comment by MatthewMoye** [comment]
#35257

**Comment by MatthewMoye** [comment]
Should any tests be written for this?

**Comment by charlesdong1991** [comment]
@MatthewMoye yep, tests are the first thing for PRs (especially for new feature implementation), and i don't think maintainers are gonna review if there is no tests in the PR.

**Comment by nathancarter** [comment]
Honestly, I think the documentation sounds like it currently does this already!  (Except that it doesn't.)

When I first read [the documentation here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.argmax.html), I assumed that what you're describing here is the default value.  The return value is explicitly documented as "Indices of the maximum values."

I'm still not actually sure what the docs actually mean.  They're either incorrect or they're referring to some higher-dimensional NumPy situation that simply doesn't arise in normal pandas use.

Either way, I strongly suggest fixing the docs for clarity and correctness as part of this issue.

**Comment by simonjayhawkins** [comment]
> The return value is explicitly documented as "Indices of the maximum values."

latest 1.1.0 docs are much clearer.

**Comment by lubianat** [comment]
+1 here, I was expecting the behavior described by @nathancarter

**Comment by jchemp** [comment]
+1

**Comment by aniketcomps** [comment]
+1

**Comment by jbrockmendel** [comment]
Discussed on last week's dev call, agreed we don't want to support this.  Instead you can do an idxmax() followed by a filter.  Closing.
