### ISSUE TITLE
BUG: fillna(inplace=True) does not work when a subset of rows is selected via .loc

### ISSUE THREAD

**Issue by matthiasha** [pandas-dev/pandas#34206]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example
```python
df = pd.DataFrame({'x': [float('nan')] * 3})
df.loc[1:, 'x'].fillna('bla', inplace=True)
print(df)
```
```
    x
0 NaN
1 NaN
2 NaN
```

#### Problem description
`fillna()` does not work with a subset of rows, while direct assignment works:
```python
df = pd.DataFrame({'x': [float('nan')] * 3})
df.loc[1:, 'x'] = 'bla'
print(df)
```
```
     x
0  NaN
1  bla
2  bla
```
`fillna()` also works when all rows are selected:
```python
df = pd.DataFrame({'x': [float('nan')] * 3})
df.loc[:, 'x'].fillna('bla', inplace=True)
print(df)
```
```
     x
0  bla
1  bla
2  bla
```

This is very confusing.

#### Expected Output
```
     x
0  NaN
1  bla
2  bla
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
```
commit           : None
python           : 3.6.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-45-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.14.1
pytz             : 2019.1
dateutil         : 2.2
pip              : 20.0.2
setuptools       : 42.0.1
Cython           : None
pytest           : 5.1.3
hypothesis       : None
sphinx           : 2.4.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.5.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 2.0.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.1.3
pyxlsb           : None
s3fs             : None
scipy            : 1.1.0
sqlalchemy       : None
tables           : None
tabulate         : 0.8.6
xarray           : 0.14.0
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
```
</details>

**Comment by matthiasha** [comment]
A workaround is to avoid `inplace=True` in this case:
```python
df = pd.DataFrame({'x': [float('nan')] * 3})
df.loc[1:, 'x'] = df.loc[1:, 'x'].fillna('bla')
print(df)
```

**Comment by jreback** [comment]
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#why-does-assignment-fail-when-using-chained-indexing

you are modifying a copy

**Comment by matthiasha** [comment]
Hi @jreback , thanks for your comment, could you please elaborate? I had read the page you linked and specifically used `df.loc[1:, 'x']` to avoid getting a copy. 
Why does this fail
```python
df.loc[1:, 'x'].fillna('bla', inplace=True)
```
when this works:
```python
df.loc[1:, 'x'].fillna('bla', inplace=True)
```
Thank you for your help!

**Comment by jreback** [comment]
inplace=Trye means the fillna is operating on a copy which you don’t have a reference; this very similar example is in the docs

**Comment by charlesdong1991** [comment]
emm, but why does the result differentiate between a full selection (`.loc[:]`) or sub-selection (`.loc[1:]`)? @jreback

**Comment by jreback** [comment]
the first is a view and the 2nd a copy

the entire point here is using inplace=True is non idiomatic and subject to implementation details like view/copy semantics

**Comment by charlesdong1991** [comment]
get it, thanks for your explanation!

**Comment by matthiasha** [comment]
> the first is a view and the 2nd a copy
Can we find an explanation of this behavior in the docs? 
Do you mean `inplace=True` should be avoided in general?

**Comment by charlesdong1991** [comment]
I think a PR that makes better clarification on such scenario will be accepted. @matthiasha

**Comment by matthiasha** [comment]
Thanks for your trust @charlesdong1991 but I would not dare touching it. If I were to propose a change, I'd deprecate the `inplace` parameter. However, despite using Pandas every day, I know too little about other people's use cases.

Compare filling `5` vs filling `'bla'`, the result depends on the type of the parameter to `fillna()`:
```python
df = pd.DataFrame({'x': [float('nan')] * 3})
df.loc[1:, 'x'].fillna(5, inplace=True)
print(df)
```
```
     x
0  NaN
1  5.0
2  5.0
```
Compared with the original example:
```python
df = pd.DataFrame({'x': [float('nan')] * 3})
df.loc[1:, 'x'].fillna('bla', inplace=True)
print(df)
```
```
    x
0 NaN
1 NaN
2 NaN
```

**Comment by charlesdong1991** [comment]
>  I would not dare touching it

Doc improvements are very welcomed too :)
