### ISSUE TITLE
ENH: Add VariableForwardWindowIndexer

### ISSUE THREAD

**Issue by yohplala** [pandas-dev/pandas#34226]
#### Is your feature request related to a problem?

I would like to use the rolling() method with looking-forward window using a negative `window`.
I don't remember which other pandas function is using this approach of negative window for reversing the position of the window with respect to the actual index, but it is for the user very convenient.
I was convinced it was existing for rolling, but it appears it is not.

#### Describe the solution you'd like

```python
# Definition of a negative offset (this works)
offset = pd.tseries.frequencies.to_offset('-1h')

# Use it in rolling (this does not work)
start = '2020-01-01 08:00'
end = '2020-01-01 12:00'
intervals = pd.period_range(start = start, end=end, freq = '30T')
values = [i for i in range(0, len(intervals))]
ser = pd.Series(values, index = intervals)
test = ser.rolling(window = offset, closed='left').min()
```

**Comment by mroeschke** [comment]
The semantics of having a monotonically increasing index with a negative offset is a bit confusing with the current API since the windows always begin from the start of the index.

That being said you can create your own custom definition of how the windows should be constructed: https://pandas.pydata.org/pandas-docs/stable/user_guide/computation.html#custom-window-rolling

So that being said, I'd be -1 on the idea given the ability to create a custom indexer but open to thoughts from others

**Comment by yohplala** [comment]
Hello Matthew,
Thanks for your reply.
I am mentioning another method taking a 'negative' window value. I think I have made a quiproquo, and I think I am referring to the `shift` function that has a `period` parameter that can be either positive or negative.

Matthew, yes, you are right and my demand can be addressed with already existing feature, except it seems to me that by playing on existing parameters, this should be supported by pandas.

I can propose an alternative, relying on existing parameters.
Couldn't the `center` parameter be also used for that, with values like `right`, `center`, and `left`?
I understand current `False` value being `right`, and `True` value being `center`. Maybe this can be extended as well.

Matthew, on my side, I have worked out following workaround.
As I have also the trouble of `PeriodIndex` being not supported by `rolling` (https://github.com/pandas-dev/pandas/issues/34225), I also switch back to `DatetimeIndex`, using `end_time`.

In the end, I feel it is a bit complex, and maybe the double list reversal, because pandas has not currently this built-in looking-forward window capability, may not be the most memory efficient.

```python
def extrema_over_forward_rolling_window(extrema: str = '',
                                        duration : pd.Timedelta,
                                        ser : pd.Serie) -> pd.Serie:
    """
    Helper function.
    Assess the extrema (min or max) over a forward rolling window, which
    duration has to be specified.

    Parameters
        extrema (str):
            `min` or `max` to be retrieved in forward-looking rolling window.
        duration (pd.Timedelta):
            Duration of the forward-looking rolling window.
        ser (pd.Serie):
            `pandas.Serie` to process.

    Returns:
        sr (pd.Serie):
            `pandas.Serie` with the extrema.
    # Create temporary reversed Serie with a DatetimeIndex, which Timestamps
    # are end of periods.    
    sr = pd.Series(ser.tolist()[::-1], index = ser.index.end_time)
    roll = sr.rolling(window = td, closed='left')
    # Get extrema and reverse back
    sr = getattr(roll, func)()[::-1]
    # Reset the index to start of periods.
    sr.index = ser.index

    return sr
```

**Comment by mroeschke** [comment]
Sorry for the long delay @yohplala 

In version 1.1.0. A `FixedFowardWindowIndexer` was added which would solve your use case for fixed windows. https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.api.indexers.FixedForwardWindowIndexer.html

I suppose we could also add a `VariableForwardWindowIndexer` which would address your particular example.
