### ISSUE TITLE
DOC: Validation script doesn't report that the docstring is correct

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#34228]
When executing for example:
```
./scripts/validate_docstrings.py pandas.DataFrame.head
```
The script, after the docstring, should report:
```
################################################################################
################################## Validation ##################################
################################################################################
Docstring for DataFrame.head correct. :)
```
But for some reason, the sentence `Docstring for DataFrame.head correct. :)` is not being printed.

This is the line that is not being executed: https://github.com/pandas-dev/pandas/blob/master/scripts/validate_docstrings.py#L364

**Comment by pikamegan** [comment]
I might be completely off, but the `if` and `elif` statement have the same condition `result["errors"]` so if it meets the `if` condition, it just skips the `elif` statement and thus it will never print the sentence. Perhaps getting rid of the `elif` statement completely or changing the condition would work?

**Comment by miguelmarques1904** [comment]
@pikamegan I believe so too. I'm currently testing the docstring by simply replacing the `elif` statement with an `else` statement. Are you taking the issue?

**Comment by pikamegan** [comment]
@miguelmarques1904 I actually don't know how to test the function (new to open source). Tried running `./scripts/validate_docstrings.py pandas.DataFrame.head` in git bash and it returned permission denied. Should I be running it in python itself with an actual data frame?

**Comment by miguelmarques1904** [comment]
@pikamegan Sorry for the delayed response.

You can try typing `chmod +x ./scripts/validate_docstrings.py`, which adds execute permissions to the `./scripts/validate_docstrings.py` file.

Welcome to the community and best of luck.

**Comment by MarcoGorelli** [comment]
FWIW, I usually run it as `python scripts/validate_docstrings.py <method I'd like to validate docstring for>`

**Comment by pikamegan** [comment]
@miguelmarques1904 thanks for the response, it still returns  `/usr/bin/env: ‘python3’: Permission denied` even though I am using the correct version of Python and it is in my path (as various stackoverflow posts suggest).

**Comment by pikamegan** [comment]
@MarcoGorelli this worked, but now I get the following error:
 `Traceback (most recent call last):
  File "scripts/validate_docstrings.py", line 50, in <module>
    from numpydoc.validate import validate, Docstring  # noqa: E402 isort:skip
ModuleNotFoundError: No module named 'numpydoc.validate'`

Google searched and there isn't such a module, so what is this line about? Would appreciate any help :)

**Comment by datapythonista** [comment]
Thanks @pikamegan for helping with this. It's unfortunately a bit more complex. What you probably want to do is:

- Write a comment in this issue with just the word `take`, so the issue is assigned to yourself, and other people don't work on it
- Set up a development environment. You have extensive information here: https://pandas.pydata.org/docs/development/contributing.html And we've also got a simplified version for a sprint, that now is probably outdated in few things, but could be helpful: https://python-sprints.github.io/pandas/guide/pandas_setup.html
- Then you'll be able to test your changes locally
- You'll finally have to submit a PR, if you're not familiar, besides the contributing guide above, you can check this document: https://python-sprints.github.io/pandas/guide/pandas_pr.html

Let me know if you have any question. For the specific error you've got, you'll have to install miniconda (or anaconda), run `conda env create`, and then activate the environment `conda activate pandas-dev`. With this, you'll have all the dependencies needed (the error is telling you that you don't have `numpydoc` installed).

**Comment by pikamegan** [comment]
@datapythonista Thanks so much for pointing me in the right direction. I'll probably try to familiarise myself with the development environment first, so someone else can take this issue

**Comment by rtm010** [comment]
Hi all, new to open source. Got my dev environment set up and happy to take this issue 😄

**Comment by rtm010** [comment]
take
