### ISSUE TITLE
REF: do length-checks in boilerplate decorator

### ISSUE THREAD

**Issue by charlesdong1991** [pandas-dev/pandas#34233]
The PR #34081 was reverted due to its impact on length-checks in Index special cases with tuples.

And the refactor is still nice for the cleanup but needs to have appropriate changes to avoid this issue.

**Comment by jorisvandenbossche** [comment]
Relevant issue about this: https://github.com/pandas-dev/pandas/issues/27911

**Comment by mroeschke** [comment]
We can consider this as a subpoint to https://github.com/pandas-dev/pandas/issues/27911, so closing in favor of consolidating there
