### ISSUE TITLE
ENH: skip_blank_columns in read_csv

### ISSUE THREAD

**Issue by metazoic** [pandas-dev/pandas#34231]
#### Is your feature request related to a problem?

If the `names` parameter in `read_csv` has more elements than the number of columns in the input file, then the returned DataFrame has `NaN` columns for the extra elements.

#### Describe the solution you'd like

Add a `skip_blank_columns` parameter in `read_csv` (similar to `skip_blank_lines`) to avoid creating the `NaN` columns.

#### API breaking implications

An additional parameter in `read_csv` should not break anything.

#### Describe alternatives you've considered

`read_csv` can be followed by `dropna()` to achieve this, but `skip_blank_columns` would complement the `skip_blank_lines` functionality currently in `read_csv`.

**Comment by mroeschke** [comment]
Thanks for the request, but it appears this hasn't gain traction in a while so closing
