### ISSUE TITLE
BUG: `astype` on index drops name

### ISSUE THREAD

**Issue by giuliobeseghi** [pandas-dev/pandas#34234]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

Index name is dropped when using `astype`

#### Code Sample, a copy-pastable example

```python
import pandas as pd

index = pd.Float64Index(range(10), name='my_index')
int_index = index.astype(int)
print(int_index.name)  # doesn't print anything
```

#### Problem description

From the docs of `astype`, I wouldn't expect the `name` attribute to be dropped:

> Cast a pandas object to a specified dtype ``dtype``.

#### Expected Output
`map` works.

```python
int_index = index.map(int)
print(int_index.name)  # prints original index name
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.7.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.3
numpy            : 1.18.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.3.post20200330
Cython           : 0.29.17
pytest           : 5.4.1
hypothesis       : 5.11.0
sphinx           : 3.0.3
blosc            : None
feather          : None
xlsxwriter       : 1.2.8
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.13.0
pandas_datareader: None
bs4              : 4.9.0
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.1.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.4.1
pyxlsb           : None
s3fs             : 0.4.2
scipy            : 1.4.1
sqlalchemy       : 1.3.16
tables           : 3.6.1
tabulate         : 0.8.3
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.8
numba            : 0.49.0

</details>

**Comment by jreback** [comment]
please check on master this was recently patched

**Comment by giuliobeseghi** [comment]
Sorry I couldn't find any issues about it. I'll wait for the next release then.

**Comment by dsaxton** [comment]
Yes this is fixed on master
```python
[ins] In [1]: import pandas as pd                                                                                                                                                                            

[ins] In [2]:                                                                                                                                                                                                

[ins] In [2]: index = pd.Float64Index(range(10), name='my_index')                                                                                                                                            

[ins] In [3]: int_index = index.astype(int)                                                                                                                                                                  

[ins] In [4]: print(int_index.name)                                                                                                                                              
my_index

[ins] In [5]: pd.__version__                                                                                                                                                                                 
Out[5]: '1.1.0.dev0+1604.g1ce9f0ca9'
``
