### ISSUE TITLE
BUG:pd.read_excel does not read xlsb

### ISSUE THREAD

**Issue by ShayHa** [pandas-dev/pandas#34237]
In the docs it says:
```code
Supports xls, xlsx, xlsm, xlsb, and odf file extensions read from a local filesystem or URL. Supports an option to read a single sheet or a list of sheets.
```
When I try to read a xlsb file with specifying engine='openpyxl'
I get the next error:

```code
df = pd.read_excel(r"file.xlsb",engine='openpyxl')
```

```code
openpyxl does not support binary format .xlsb, please convert this file to .xlsx format if you want to open it with openpyxl
```
I do have the openpyxl module installed

Thank you

**Comment by TomAugspurger** [comment]
https://pandas.pydata.org/docs/user_guide/io.html?highlight=excel#excel-files says that just the `pyxslb` engine supports xlsb. We could make that clear in the docstring for read_excel, and perhaps in the error message if we're the one reading raising it (but are we, or is openpyxl?)

**Comment by ShayHa** [comment]
Thank you. using engine='pyxlsb' worked.

**Comment by miguelmarques1904** [comment]
take
