### ISSUE TITLE
ENH: to_sql option for progress_bar 

### ISSUE THREAD

**Issue by Aqua-4** [pandas-dev/pandas#34249]
#### Is your feature request related to a problem?

pd.to_sql should definitely have a *progress bar* while dumping *df.to_sql *just like 
*pandas.to_gbq*

#### Describe the solution you'd like

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_gbq.html
pd.to_sql should have *progress_bar=True* as a boolean parameter in case the user is sending the data in chunks or if the user wants to see the progress.

#### Describe alternatives you've considered

https://stackoverflow.com/questions/39494056/progress-bar-for-pandas-dataframe-to-sql

```python

import sqlite3
import pandas as pd
from tqdm import tqdm

DB_FILENAME='/tmp/test.sqlite'

def chunker(seq, size):
    # from http://stackoverflow.com/a/434328
    return (seq[pos:pos + size] for pos in xrange(0, len(seq), size))

def insert_with_progress(df, dbfile):
    con = sqlite3.connect(dbfile)
    chunksize = int(len(df) / 10) # 10%
    with tqdm(total=len(df)) as pbar:
        for i, cdf in enumerate(chunker(df, chunksize)):
            replace = "replace" if i == 0 else "append"
            cdf.to_sql(con=con, name="MLS", if_exists=replace, index=False)
            pbar.update(chunksize)

df = pd.DataFrame({'a': range(0,100000)})
insert_with_progress(df, DB_FILENAME)

```

**Comment by mroeschke** [comment]
Of note, `to_gbq` supports a `progress_bar` argument because the we dispatch to a 3rd party `pandas-gbq` library that supports it.

For sql, we would most likely want a similar solution where we could dispatch to a sql library that supports a progress bar

**Comment by vlasvlasvlas** [comment]
+1

**Comment by mroeschke** [comment]
Thanks for the issue, but it appears this hasn't gotten traction in a while so closing

**Comment by ganbaaelmer** [comment]
i also need pandas to_sql with native progress bar
