### ISSUE TITLE
Problem with obtaining a view of a DataFrame using loc

### ISSUE THREAD

**Issue by figuetbe** [pandas-dev/pandas#34270]
Hello, I am trying to obtain a view of a pandas dataframe using the `loc` method but it is not working as expected when I am modifying the original DataFrame.  
I want to extract a row/slice of a DataFrame using the `loc` method so that when a modification is done to the DataFrame, the slice reflects the change.

Let's have a look at this example:
```python
import pandas as pd
import numpy as np
df = pd.DataFrame({'ID':np.arange(0,5,2), 'a':np.arange(3), 'b':np.arange(3)}).set_index('ID')
df
 	a 	b
ID 		
0 	0 	0
2 	1 	1
4 	2 	2
```

Now I create a slice using loc:
```python
slice1 = df.loc[[2],]
slice1

	a 	b
ID 		
2 	1 	1
```

Then I modify the original DataFrame:
```python
df.loc[2, 'b'] = 9
df

	a 	b
ID 		
0 	0 	0
2 	1 	9
4 	2 	2
```

But unfortunately our slice does not reflect this modification as I would be expecting for a view:
```python
slice1
	a 	b
ID 		
2 	1 	1
```

My expectation:
```python
	a 	b
ID 		
2 	1 	9
```

Am I doing something wrong or is this a bug?
Thank you for your help.

Pandas version: 1.0.3
Stackoverflow: https://stackoverflow.com/questions/61890845/obtain-a-view-of-a-dataframe-using-the-loc-method

**Comment by jorisvandenbossche** [comment]
> Now I create a slice using loc:

What you are doing (`df.loc[[2],]`) is not actually a *slice*, but a list selection. 

In numpy terms, this means "advanced" or "fancy" indexing, which means the result is a copy (in contrast with actual slicing which gives a view): https://numpy.org/devdocs/reference/arrays.indexing.html#advanced-indexing

However, in pandas there is the additional complication that a DataFrame is not a single-dtyped array, but a heterogeneous collection of different arrays, which makes this logic even more difficult / less transparent. So this means that when actually doing a *slice* (eg `df.loc[2:4, ]`) it is not 100% guaranteed to be a slice (it depends on the column selection as well)

**Comment by figuetbe** [comment]
Thank you for your input. It's more clear now.

I wanted to work on views of a big DataFrame to optimize my memory ([CF my SO post](https://stackoverflow.com/questions/61916923/how-to-optimize-pandas-dataframes-slices-copies)), but I guess I will have to stick to copies instead.

**Comment by mroeschke** [comment]
Thanks for the question. It appears that this was a usage question and the behavior is more-or-less expected. Closing and tagging as such
