### ISSUE TITLE
Reopened: "TypeError: searchsorted requires compatible dtype or scalar, not ndarray "

### ISSUE THREAD

**Issue by Baynez** [pandas-dev/pandas#34279]
"TypeError: searchsorted requires compatible dtype or scalar, not Series"
appears again when applying timeindex data:

``` 
#sample data
data = ['1998-01-07 13:17:00', '1998-01-07 13:18:00', '1998-01-07 13:19:00', '1998-01-07 13:20:00',
     '1998-01-07 13:21:00', '1998-01-07 13:22:00', '1998-01-07 13:23:00']
df = pd.DataFrame(x)
df.set_index(df.iloc[:, 0], inplace=True)
df.index = pd.DatetimeIndex(df.index.values) 
 
# this is the line
df.index.searchsorted(pd.Series(np.array([df.index[0], df.index.max()]))) 
  
```
How to solve this?

**Comment by dsaxton** [comment]
@Baynez which version of pandas are you using?

Also is there possibly a typo in your code? The DataFrame is built up from x but I think you mean to use the list data. If I make that change it seems to work for me on master.

```python
>>> import numpy as np
>>> import pandas as pd
>>> 
>>> # sample data
>>> data = ['1998-01-07 13:17:00', '1998-01-07 13:18:00', '1998-01-07 13:19:00', '1998-01-07 13:20:00',
...         '1998-01-07 13:21:00', '1998-01-07 13:22:00', '1998-01-07 13:23:00']
>>> df = pd.DataFrame(data)
>>> df.set_index(df.iloc[:, 0], inplace=True)
>>> df.index = pd.DatetimeIndex(df.index.values)
>>> 
>>> # this is the line
>>> df.index.searchsorted(pd.Series(np.array([df.index[0], df.index.max()]))) 
array([0, 6])
```

**Comment by Baynez** [comment]
> 
> 
> @Baynez which version of pandas are you using?
> 
> Also is there possibly a typo in your code? The DataFrame is built up from x but I think you mean to use the list data. If I make that change it seems to work for me on master.
> 
> ```python
> >>> import numpy as np
> >>> import pandas as pd
> >>> 
> >>> # sample data
> >>> data = ['1998-01-07 13:17:00', '1998-01-07 13:18:00', '1998-01-07 13:19:00', '1998-01-07 13:20:00',
> ...         '1998-01-07 13:21:00', '1998-01-07 13:22:00', '1998-01-07 13:23:00']
> >>> df = pd.DataFrame(data)
> >>> df.set_index(df.iloc[:, 0], inplace=True)
> >>> df.index = pd.DatetimeIndex(df.index.values)
> >>> 
> >>> # this is the line
> >>> df.index.searchsorted(pd.Series(np.array([df.index[0], df.index.max()]))) 
> array([0, 6])
> ```

sry i pasted the code wrong here, still not working, pd version is 1.0.1

**Comment by dsaxton** [comment]
Yes, it looks like this was broken at least on 1.0.1 and 1.03, but going to close since it seems to be fixed on master
