### ISSUE TITLE
QST: How "safe" is it to pickle a DataFrame with v1.x for long(er) term storage? 

### ISSUE THREAD

**Issue by jolespin** [pandas-dev/pandas#34276]
#### Question about pandas

How "safe" is pickling `DataFrame` objects with v1.x for long term?  Pickling in past versions has been a sort of gamble, as expected, but I'm wondering how the long term storability is for `pandas` objects (in particular, `DataFrame`) now that the API has solidified in v1.x.

**Comment by jreback** [comment]
we already have backwards compatilibity from 0.21.0. The support for pickles before this was removed (though may still work). So its the same guarantee as before. Backwards compatibility is preserved, though certainly may have performance differences.

**Comment by jreback** [comment]
all that said. pickle is not a great format for long term storage. choose parquet.

**Comment by jolespin** [comment]
Good to know!  Thanks.  Performance issues aren't a concern (at the moment).  I'm using pickle because I have a lot of `MultiIndex` dataframes and some have `frozenset` objects as keys. 

I'll look into `parquet`, I've been hearing more about that recently.
