### ISSUE TITLE
BUG: querying AWS athena via pyathena connection produces error 

### ISSUE THREAD

**Issue by cuckookernel** [pandas-dev/pandas#34283]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
from sqlalchemy.engine import create_engine
import pandas as pd

# %%
connection_params = {
    's3_staging_dir': PUT_AN_S3_PATH_HERE,
    'aws_region': 'us-west-2',
    'aws_key_id':  OMITTED_KEY,
    'aws_secret': OMITTED_SECRET,
    'dbname':  PUT_ANY_ATHENA_DB_NAME}

url_string = 'awsathena+rest://{aws_key_id}:{aws_secret}@athena.{aws_region}.amazonaws.com:443/{dbname}?s3_staging_dir={s3_staging_dir}'
# %%
engine = create_engine( url_string.format(**connection_params))
conn = engine.connect()
# %%
conn.execute(""" drop table if exists tmp1""")
conn.execute("""
    create external table tmp1( a int, b string ) 
    stored as parquet
    location 's3://ml-lahaus/tmp1'
    """)
conn.execute("""
    insert into tmp1 values (4, 'badad') 
""")
# %% A query using regular conn.execute method
result = conn.execute("""select * from tmp1 where b='badad'""")
for row in result:
    print(row)  # shows expected result

# %% Last cell: same query passed to pd.read_sql
df = pd.read_sql( """select * from tmp1 where b='badad'""", conn)
print( df ) #also shows expected result but at the same time scary error trace shows in console
# %%

```

#### Problem description

The code works perfectly fine up to the line marked with `# %% Last cell`. The code after that produces an exception saying 'Failed to execute query', and the corresponding stack trace which I paste below. However, this exception seems to be happening in a different thread or something like that as the code actually finishes successfully, and the "df" variable is actually bound to a DataFrame with the right data in it, which is at the very least puzzling and disorienting for the data analyst.

Exception produced by last cell (in a different thread?)
```
Failed to execute query.
Traceback (most recent call last):
  File "/home/teo/git/ml-services/venv-tmp/lib/python3.7/site-packages/pyathena/common.py", line 236, in _execute
    **request
  File "/home/teo/git/ml-services/venv-tmp/lib/python3.7/site-packages/pyathena/util.py", line 344, in retry_api_call
    return retry(func, *args, **kwargs)
  File "/home/teo/git/ml-services/venv-tmp/lib/python3.7/site-packages/tenacity/__init__.py", line 409, in call
    do = self.iter(retry_state=retry_state)
  File "/home/teo/git/ml-services/venv-tmp/lib/python3.7/site-packages/tenacity/__init__.py", line 356, in iter
    return fut.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/teo/git/ml-services/venv-tmp/lib/python3.7/site-packages/tenacity/__init__.py", line 412, in call
    result = fn(*args, **kwargs)
  File "/home/teo/git/ml-services/venv-tmp/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/teo/git/ml-services/venv-tmp/lib/python3.7/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 12:63: mismatched input 'badad' expecting {<EOF>, '.', '[', 'GROUP', 'ORDER', 'HAVING', 'LIMIT', 'AT', 'OR', 'AND', 'UNION', 'EXCEPT', 'INTERSECT', '+', '-', '*', '/', '%', '||'}
```

The exception shows up when query contains literal string enclosed in single quotes. It doesn't show otherwise.

#### Expected Output

Expected no puzzling exception to be shown.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-88-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : sv_SE.UTF-8
LOCALE           : sv_SE.UTF-8
pandas           : 1.0.3
numpy            : 1.18.4
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 19.0.3
setuptools       : 40.8.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.5 (dt dec pq3 ext lo64)
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.17
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
</details>

I also paste other possible relevant package versions below:

```
$ pip freeze

boto3==1.13.14
botocore==1.16.14
docutils==0.15.2
future==0.18.2
jmespath==0.10.0
joblib==0.15.1
lahaus-ml-shared==0.1
numpy==1.18.4
pandas==1.0.3
psycopg2-binary==2.8.5
PyAthena==1.10.7
python-dateutil==2.8.1
python-dotenv==0.13.0
pytz==2020.1
s3transfer==0.3.3
scikit-learn==0.23.1
scipy==1.4.1
six==1.14.0
SQLAlchemy==1.3.17
tenacity==6.2.0
threadpoolctl==2.0.0
urllib3==1.25.9

```

**Comment by WillAyd** [comment]
Given pandas doesn’t appear in the traceback I think this is an issue elsewhere. Do you get the same when using the connection directly without read_sql?

**Comment by mroeschke** [comment]
Agreed from the traceback it looks like it doesn't appear like an issue in pandas. Closing, but If you could provide more information that shows its a pandas issue, we would be happy to reopen.
