### ISSUE TITLE
DOC: improve pie chart example

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#34288]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.plot.pie.html

**Note**: You can check the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/).

#### Documentation problem

This example doesn't look great:
![image](https://user-images.githubusercontent.com/33491632/82543164-06f82680-9b4b-11ea-98bf-c7245506410a.png)

The legend covers the labels, and the two pies are so close that "mercury" is hard to read.

#### Suggested fix for documentation

Make a more readable plot

**Comment by wicky1234444** [comment]
Hi @MarcoGorelli , I am new to open source. Can i work on this?

**Comment by MarcoGorelli** [comment]
@wicky1234444 sure, pull requests are welcome - see the [contributing guide](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html) for how to get started, and feel free to ask for help

**Comment by wicky1234444** [comment]
Thanks. I will got through the contributing guide and start on the issue.

**Comment by Akshatt** [comment]
Hi @MarcoGorelli, is the issue assigned already? If not can i work on this issue too? I'm new as well

**Comment by MarcoGorelli** [comment]
Looks like @wicky1234444 is already working on it (if so, @wicky1234444 , please comment 'take' so the issue is assigned to you)

**Comment by wicky1234444** [comment]
@MarcoGorelli iam   working on it.
