### ISSUE TITLE
DOC: "Setting layouts" plots are hard to read

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#34305]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/dev/user_guide/visualization.html#using-layout-and-targeting-multiple-axes

**Note**: You can check the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/).

#### Documentation problem

This is hard to read:
![image](https://user-images.githubusercontent.com/33491632/82655302-e2b74b00-9c19-11ea-9bdb-52c1e9d86f45.png)

Same with the plot immediately below it:
![image](https://user-images.githubusercontent.com/33491632/82655376-fcf12900-9c19-11ea-9e02-54eedf7c1600.png)

#### Suggested fix for documentation

Could the plots be made clearer, so the labels don't cover each other?

**Comment by wicky1234444** [comment]
@MarcoGorelli can i do this?

**Comment by MarcoGorelli** [comment]
Sure, go ahead - if you leave a comment with the word 'take' the issue will be assigned to you

**Comment by wicky1234444** [comment]
take

**Comment by wicky1234444** [comment]
@MarcoGorelli  i changed the code in doc/source/user_guide/visualization.rst , but when I tried to build the docs using python make.py html, there are no images generated in the  doc/build/html/user_guide/visualization.html.  The images in the html page looks like these,
![Annotation 2020-05-22 220745](https://user-images.githubusercontent.com/29908168/82689850-c1397c00-9c78-11ea-8b68-c1aae807da68.png)

**Comment by MarcoGorelli** [comment]
Are the images generated if you don't change the code in `doc/source/user_guide/visualization.rst`?

btw, instead of building the whole docs, it should be enough to do
```bash
python make.py clean
python make.py --single user_guide/visualization.rst
```

**Comment by wicky1234444** [comment]
@MarcoGorelli  i tried building docs from my master branch using the above commands, the output of visualization.rst html file still doesnt have any images.(I haven't made any changes to master branch and it is up to date with the changes in pandas-dev/pandas repository).

**Comment by najann** [comment]
If you don't mind I'll give it a try :)

**Comment by najann** [comment]
take
