### ISSUE TITLE
ENH:  pd.DataFrame.plot.hist() does not use sharex argument

### ISSUE THREAD

**Issue by sorenwacker** [pandas-dev/pandas#34326]
The command 

    df.plot.hist(subplots=True, layout=(4, 4), figsize=(15,10), sharex=False, sharey=False)

produces a grid of histograms. Unfortunately, sharex and y arguments are not taken into account and the plots all share the same axis. This only makes sense if all columns have the similar scales. But in general this behaviour is not very useful. Apparently, `df.plot.density()` accepts the keywords and uses them correctly. 

I would hope the function could be extended to provide the functionality as well as

    df.hist(...)

**Comment by avirlrma** [comment]
Hey,
Can I take this up?
