### ISSUE TITLE
ENH: `name` attribute for pd.Interval

### ISSUE THREAD

**Issue by jolespin** [pandas-dev/pandas#34320]
#### Is your feature request related to a problem?

No
#### Describe the solution you'd like

`pd.Interval(x, y, name="Feature")`

#### API breaking implications

Not that I know of. 

#### Describe alternatives you've considered

Tried `setattr`

**Comment by dsaxton** [comment]
I don't believe this is supported in general for pandas scalars (e.g., Timestamp or Period). What would be the use case for this?

**Comment by jolespin** [comment]
I work in bioinformatics and genomics.  I was thinking this interval object can be uses as genes.  For example, on a chromosome there will be multiple genes.

Interval(2,100, name=gene_1) and Interval(200,500,name=gene_2)

What are your thoughts? Would this cause any internal issues?

**Comment by dsaxton** [comment]
I think in general intervals are thought of as having only endpoints (it's the _gene_ that you want to name rather than the interval itself). How about using a custom gene class that has left and right endpoints as well as a name (which could then be wrapped in a Series if need be)?

**Comment by jolespin** [comment]
Yea that’s a good idea.  I could also just use it in a series.

**Comment by mroeschke** [comment]
I'd be -0.5 on adding a name attribute to `pd.Interval`. In addition to the precedent set by the other pandas scalars, I think this would complicate notions of equality between the between two `Interval` scalars

**Comment by jolespin** [comment]
I agree, you bring up a good point.  A custom class with inheritance seems like it would be the best option. Closing this issue now.  Thanks for considering and the suggestions.
