### ISSUE TITLE
ENH: Add hue functionality to df.hist() 

### ISSUE THREAD

**Issue by sorenwacker** [pandas-dev/pandas#34327]
The following command:

    df.hist(layout=(4, 4), figsize=(15,10), bins=30)

produces a grid of histograms. I would like to group the data by a column value and plot the corresponding histograms in the same plot with different colors. Unfortunately, the `by=` argument generates subplots. And plots all the data regardless the scale in as many subplots as unique values in the dataframe. 

I wonder if either an argument `hue=` as used in seaborn could be added so to produce the desired result.

**Comment by raphacosta27** [comment]
Hi there, is this issue still open? If so, I`d like to take it.

**Comment by mroeschke** [comment]
Thanks for the request but it appears this hasn't gotten traction in a while so closing
