### ISSUE TITLE
BUG: Clipboard tests failing in Dockerfile

### ISSUE THREAD

**Issue by matteosantama** [pandas-dev/pandas#34348]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
pytest pandas/tests/io/test_clipboard.py 
```

#### Problem description
Last three clipboard tests are failing in a Docker image running on Mac. Dug into the pyperclip code and the issue appears to be that the Docker container does not have a DISPLAY environment variable set correctly. Pyperclip code does not recognize my machine as a Mac, so it tries to proceed as if its a Linux.

I've tried manually setting it, and the tests run through completion but the assertions fail and I get `Could not open display`. Does anyone have an idea how to fix this? Or is Dockerfile not supported for Macs?

**Comment by jbrockmendel** [comment]
I've seen these same 3 failures for a while on a headless ubuntu machine, had assumed it was because of the "headless" part, but hooked up a monitor today and find they're still failing.

@datapythonista IIRC there was some env variable in the test config that requires special treatment?

**Comment by datapythonista** [comment]
Those tests need a clipboard mechanism to run. We used to skip them if the clipboard was failing, but this caused the tests often being skipped unintentionally when things were failing.

I don't think this is a bug. In the same way that it shouldn't be a bug if you run the tests for a database, but you don't have the database installed.

The way to make them work is to have a clipboard in the system. `xvfb` is the one we're using in the CI (see `ci/run_tests.sh`).

**Comment by matteosantama** [comment]
My understanding of the problem is that pyperclip tries to determine which machine you are running, so it can access the proper clipboard mechanism. The code does not recognize my Docker container as a Mac, so it falls back on assuming its Linux. But there is no DISPLAY environment variable set, which reports an error somewhere in the copy/paste process. So even if I install xclip, it doesn't run properly.

I thought if someone know what DISPLAY should be, it would be an easy fix. If not, I can make a note in the documentation that if you use the Dockerfile expect some tests to fail.

**Comment by datapythonista** [comment]
You can try `DISPLAY=:0`. But `DISPLAY` is automatically set by the X server when it's working. I have no idea about Mac, but in Linux, if it's not set, it likely means that you don't have an X server available.

**Comment by jbrockmendel** [comment]
```
$ echo $DISPLAY
:0
```

This is on Ubuntu desktop

**Comment by matteosantama** [comment]
Thanks guys, unfortunately that doesn't work for me. I went back to the Contributing to Pandas documentation and I don't see the section on setting up a development environment in Docker anymore. This is probably more trouble than it's worth, so I'm OK closing this ticket.

**Comment by jbrockmendel** [comment]
I solved this locally with `sudo apt-get install xsel`. @matteosantama is this viable for your use case?

**Comment by matteosantama** [comment]
@jbrockmendel sadly no, but thanks. I think my particular set-up falls right in the weak spot of pyperclip. It's not quite a Linux and its not quite a Mac. I'm probably gonna move on from Docker, its a bit of a pain.
