### ISSUE TITLE
WARN: possible windows x64 issue with older numpy MKL

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#3434]
I happened to have an older verion of numpy 1.6.2 MKL installed on a windows machines

very intermittently (I think you hae to be using a really big frame)
sometimes I got a:

OMP : Error # 134 Cannot set thread affinity mask

which I think is caused by numexpr operations

see this

http://software.intel.com/en-us/forums/topic/279406

I am not sure its a real problem, because it only affects some versions of MKL, upgrading numpy (or even using a newer version of 1.6.2) seems to fix it..

also can be programatically disabled by

`pandas.core.expressions.set_use_numexpr(False)`

just a FYI

**Comment by JohnNapier** [comment]
Please find here (https://github.com/pydata/pandas/issues/9328) code to reproduce this issue.

**Comment by jreback** [comment]
closing as non-supported numpy version
