### ISSUE TITLE
retrieve unwanted things later

### ISSUE THREAD

**Issue by ramimohammad** [pandas-dev/pandas#34350]
If I'm trying to make some data processing and I want to hide unwanted symbols or html codes during processing stage and I want to popup those unwanted things again on their origin place within the text after finishing.

My question is : is that doable ? if yes .. how to do that ?

Thanks

**Comment by ramimohammad** [comment]
let me show you an example : on of the xlsx sheet cells : "What will the font size of the link be? <div class="primary"> <a href="#" class="link">Home</a> </div> <style> .primary a { font-size: 16px; } div a.link { font-size: 20px; } </style> "

for example I want to leave " What will the font size of the link be?" part to be translated to another language without "<div> ... <style> .. etc" content >>>> then after finishing I want them back to their previous place with the newly translated text.

**Comment by ramimohammad** [comment]
to make clear .. let's say we have a xlsx sheet with text mixed with those html codes or symbols ... we need to translate text without html codes then we need them back with the newly translated text side by side on their origin place. I hope it's clear now.

**Comment by MarcoGorelli** [comment]
Hi @ramimohammad 

> I hope it's clear now.

to be honest, it's not clear to me. Anyway, is this relevant to pandas? Have you tried asking on stackoverflow?

**Comment by ramimohammad** [comment]
> Hi @ramimohammad
> 
> > I hope it's clear now.
> 
> to be honest, it's not clear to me. Anyway, is this relevant to pandas? Have you tried asking on stackoverflow?

Hi @MarcoGorelli  , yes I'm using pandas , and yes I asked on stackoverflow but no answer till now.

**Comment by ramimohammad** [comment]
@MarcoGorelli I'll show an example of what I'm trying to do.

let's say I have the following two cells

26  Assuming this is the only css on the page, how wide will the box be when its rendered .box{         Width: 100px;         Height: 50px;         Padding: 5px;         Border: 1px solied red;         Background-color: red; }   

27  What will the font size of the link be? <div class="primary">   <a href="#" class="link">Home</a> </div> <style>  .primary a {   font-size: 16px; }  div a.link {   font-size: 20px; } </style> 


I have a third party translation tool not allowing html tags or coding things with the text .. and I need t

**Comment by MarcoGorelli** [comment]
Thanks @ramimohammad for the details

Closing as this is really the kind of question you'd want to ask on StackOverflow (if you include a minimal complete verifiable example, you'll usually get an answer), the issue tracker here is more intended for pandas development

**Comment by alimcmaster1** [comment]
This sounds like a css/html issue - stackoverflow is a better place for this kind of question @ramimohammad feel free to reopen if there is a pandas specific issue.
