### ISSUE TITLE
BUG: Series.value_counts(normalize=True) fails with Int64Dtype

### ISSUE THREAD

**Issue by elnikkis** [pandas-dev/pandas#34361]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas as pd
pd.Series([1,2,3, None], dtype=pd.Int64Dtype()).value_counts(normalize=True)
```

Traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/.pyenv/versions/pandas-test/lib/python3.8/site-packages/pandas/core/base.py", line 1229, in value_counts
    result = value_counts(
  File "/home/xxx/.pyenv/versions/pandas-test/lib/python3.8/site-packages/pandas/core/algorithms.py", line 731, in value_counts
    result = result / float(counts.sum())
AttributeError: 'IntegerArray' object has no attribute 'sum'
```

#### Problem description

An error occurd when I called `Series.value_counts(normalize = True)` with Int64Dtype.

#### Expected Output

The result probably should be:
```
3    0.333333
2    0.333333
1    0.333333
dtype: float64
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.0.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.0-6-amd64
machine          : x86_64
processor        :
byteorder        : little
LC_ALL           : None
LANG             : ja_JP.UTF-8
LOCALE           : ja_JP.UTF-8

pandas           : 1.0.3
numpy            : 1.18.4
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by jorisvandenbossche** [comment]
@elnikkis This has recently been fixed on master already:

```
In [12]: import pandas as pd 
    ...: pd.Series([1,2,3, None], dtype=pd.Int64Dtype()).value_counts(normalize=True)  
Out[12]: 
1    0.333333
2    0.333333
3    0.333333
dtype: float64

In [13]: pd.__version__ 
Out[13]: '1.1.0.dev0+1651.g3d32bc813'
```

But thanks for the report anyway!

**Comment by elnikkis** [comment]
Thank you for reply. I'm looking forward to it being released.
