### ISSUE TITLE
DOC: Add D-Tale to Visualizations section of Pandas Ecosystem

### ISSUE THREAD

**Issue by aschonfeld** [pandas-dev/pandas#34376]
#### Location of the documentation

[Pandas Ecosystem - Visualization](https://pandas.pydata.org/docs/ecosystem.html#visualization)

#### Documentation problem

This isn't a problem, just a suggestion for improving the current ecosystem listing.

#### Suggested fix for documentation

[D-Tale](https://github.com/man-group/dtale) is a open-source tool for visualizing pandas data structures and it has really started to gain some traction in the data science community. 1K+ stars since 9/2019.  I think it would be nice addition to the visualization section of "Pandas Ecosystem".

Here's an example of the listing for it, but feel free to write your own (assuming you think it should be added):

### [D-Tale](https://github.com/man-group/dtale)

D-Tale is the combination of a Flask back-end and React front-end to bring you an easy way to view, edit & analyze Pandas data structures. Also, includes a fully-featured chart builder by way of Plotly Dash.  It integrates seamlessly with jupyter notebooks, python terminals, kaggle. Currently this tool supports such Pandas objects as DataFrame, Series, MultiIndex, DatetimeIndex & RangeIndex.  A nice demo is located [here](http://alphatechadmin.pythonanywhere.com/).

**Comment by TomAugspurger** [comment]
@aschonfeld that sounds fine, can you submit a PR with this?

**Comment by aschonfeld** [comment]
@TomAugspurger here ya go #34396

**Comment by rootsmusic** [comment]
Similar to [sweetviz](https://github.com/fbdesignpro/sweetviz/blob/master/README.md) and [ydata-profiling](https://docs.profiling.ydata.ai/latest/).
