### ISSUE TITLE
BUG: Memory leak when calling an apply with datetime.fromtimestamp

### ISSUE THREAD

**Issue by frd-glovo** [pandas-dev/pandas#34404]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
import numpy as np
import psutil
import os
from datetime import datetime

    
def process_samples(df):
    df['time'] = df['time'].apply(lambda x: datetime.fromtimestamp(x//10**3))
    
    df = df.rename(columns={'time':f'time_timestamp' })

df = pd.DataFrame({'time':np.random.randint(0,1000, size=30)})

process = psutil.Process(os.getpid())
beg = process.memory_info().rss/1024/1024

for i in range(1000000):
    
    process_samples(df.copy())
    
    end = process.memory_info().rss/1024/1024
    if i % 500 ==0:
        print(f'Memory after {i} iterations ', end, ', difference w.r.t. beggining',end-beg)

```

#### Problem description

We have identified a memory leak in our code when executing a combination of an apply and a rename. If we do any of these two steps without the other, there is no leak.

The apply simply uses datetime.fromtimestamp to convert POSIX timestamp to a date. We understand that we achieve similar results with the apply using time pd.to_datetime(), but still believe there could be a memory leak with the apply method in general that should be investigated

If we use datetime.fromtimestamp to convert the POSIX timestamps to dates without pandas there is no leak.

#### Expected Output

Memory consumption should not increase and stay constant

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.9.184-linuxkit
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.16.0
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.1
setuptools       : 45.1.0
Cython           : None
pytest           : 5.4.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : 0.9.3
psycopg2         : 2.8.2 (dt dec pq3 ext lo64)
jinja2           : 2.11.2
IPython          : 7.13.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.2.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.4.2
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.2.16
tables           : None
tabulate         : 0.8.3
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : 0.49.1

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by TomAugspurger** [comment]
@frd-glovo what output do you see? Here's mine

```
## -- End pasted text --
Memory after 0 iterations  74.5625 , difference w.r.t. beggining 0.35546875
Memory after 500 iterations  74.71875 , difference w.r.t. beggining 0.51171875
Memory after 1000 iterations  74.7109375 , difference w.r.t. beggining 0.50390625
Memory after 1500 iterations  74.6875 , difference w.r.t. beggining 0.48046875
Memory after 2000 iterations  74.6875 , difference w.r.t. beggining 0.48046875
Memory after 2500 iterations  74.6875 , difference w.r.t. beggining 0.48046875
Memory after 3000 iterations  74.6875 , difference w.r.t. beggining 0.48046875
Memory after 3500 iterations  74.6875 , difference w.r.t. beggining 0.48046875
Memory after 4000 iterations  74.6875 , difference w.r.t. beggining 0.48046875
Memory after 4500 iterations  74.6875 , difference w.r.t. beggining 0.48046875
Memory after 5000 iterations  74.6875 , difference w.r.t. beggining 0.48046875
Memory after 5500 iterations  74.6875 , difference w.r.t. beggining 0.48046875
Memory after 6000 iterations  74.6875 , difference w.r.t. beggining 0.48046875
Memory after 6500 iterations  74.6875 , difference w.r.t. beggining 0.48046875
Memory after 7000 iterations  74.6875 , difference w.r.t. beggining 0.48046875
Memory after 7500 iterations  74.6875 , difference w.r.t. beggining 0.48046875
Memory after 8000 iterations  74.6875 , difference w.r.t. beggining 0.48046875
Memory after 8500 iterations  74.6875 , difference w.r.t. beggining 0.48046875
Memory after 9000 iterations  74.6875 , difference w.r.t. beggining 0.48046875
Memory after 9500 iterations  74.6875 , difference w.r.t. beggining 0.48046875
```

**Comment by frd-glovo** [comment]
There is a sustained increase in memory that does not plateau.

This is how it begins:

```
Memory after 0 iterations  54.91796875 , difference w.r.t. beggining 0.0
Memory after 500 iterations  55.77734375 , difference w.r.t. beggining 0.859375
Memory after 1000 iterations  55.77734375 , difference w.r.t. beggining 0.859375
Memory after 1500 iterations  55.77734375 , difference w.r.t. beggining 0.859375
Memory after 2000 iterations  56.02734375 , difference w.r.t. beggining 1.109375
Memory after 2500 iterations  56.02734375 , difference w.r.t. beggining 1.109375
Memory after 3000 iterations  56.02734375 , difference w.r.t. beggining 1.109375
Memory after 3500 iterations  56.02734375 , difference w.r.t. beggining 1.109375
Memory after 4000 iterations  56.28125 , difference w.r.t. beggining 1.36328125
Memory after 4500 iterations  56.36328125 , difference w.r.t. beggining 1.4453125
Memory after 5000 iterations  56.36328125 , difference w.r.t. beggining 1.4453125
Memory after 5500 iterations  56.36328125 , difference w.r.t. beggining 1.4453125
Memory after 6000 iterations  56.36328125 , difference w.r.t. beggining 1.4453125
Memory after 6500 iterations  56.6171875 , difference w.r.t. beggining 1.69921875
Memory after 7000 iterations  56.6171875 , difference w.r.t. beggining 1.69921875
Memory after 7500 iterations  56.73828125 , difference w.r.t. beggining 1.8203125
Memory after 8000 iterations  56.73828125 , difference w.r.t. beggining 1.8203125
Memory after 8500 iterations  56.73828125 , difference w.r.t. beggining 1.8203125
Memory after 9000 iterations  56.9921875 , difference w.r.t. beggining 2.07421875
Memory after 9500 iterations  56.9921875 , difference w.r.t. beggining 2.07421875
Memory after 10000 iterations  57.109375 , difference w.r.t. beggining 2.19140625
Memory after 10500 iterations  57.109375 , difference w.r.t. beggining 2.19140625
Memory after 11000 iterations  57.109375 , difference w.r.t. beggining 2.19140625
```

This is how it ends:

```
Memory after 998500 iterations  194.37109375 , difference w.r.t. beggining 139.31640625
Memory after 999000 iterations  194.48828125 , difference w.r.t. beggining 139.43359375
Memory after 999500 iterations  194.4921875 , difference w.r.t. beggining 139.4375
```

**Comment by frd-glovo** [comment]
What versions are you using?

**Comment by TomAugspurger** [comment]
Master, but I also checked 1.0.3 and things look fine.

Both are with numpy 1.18.4. Can you try that?

**Comment by frd-glovo** [comment]
Yes, it's numpy's version. With numpy==1.18.4 this is the output (and stays the same)
```

Memory after 0 iterations  56.8125 , difference w.r.t. beggining 1.2109375
Memory after 500 iterations  57.0390625 , difference w.r.t. beggining 1.4375
Memory after 1000 iterations  57.0390625 , difference w.r.t. beggining 1.4375
Memory after 1500 iterations  57.0390625 , difference w.r.t. beggining 1.4375
Memory after 2000 iterations  57.0390625 , difference w.r.t. beggining 1.4375
Memory after 2500 iterations  57.0390625 , difference w.r.t. beggining 1.4375
Memory after 3000 iterations  57.0390625 , difference w.r.t. beggining 1.4375
```

**Comment by TomAugspurger** [comment]
Thanks for following up.
