### ISSUE TITLE
TST: slow test_nearest_upsample_with_limit with tzlocal

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#34413]
Doing `pytest pandas/tests --skip-slow --durations=10` the top two entries are

```
71.76s call     pandas/tests/resample/test_datetime_index.py::test_nearest_upsample_with_limit[tzlocal()-30S-Y]
59.86s call     pandas/tests/resample/test_datetime_index.py::test_nearest_upsample_with_limit[tzlocal()-30S-10M]
```

Because this uses the tz_aware_fixture, there isn't a trivial way to add a pytest.mark.slow to this, but figuring something out may be worthwhile.

**Comment by dsaxton** [comment]
This test came up here https://github.com/pandas-dev/pandas/issues/34131 and @jreback pointed out that it's resampling at probably too fine a frequency

**Comment by jbrockmendel** [comment]
That and tzlocal is just slower than everything else in general.  (ive got a branch implementing a cython equivalent i need to circle back to)

Could do something like:

```
@pytest.mark.slow
def test_foo_tzlocal():
    return thing(tzlocal)

def test_foo(tz_aware_fixture):
    if tz_aware_fixture is tzlocal:
         return/skip/whatever
    thing(tz_aware_fixture)
```

**Comment by jreback** [comment]
no easiest way is simple to split it into 2 tests and not try to upsample 1ms to 1y
