### ISSUE TITLE
CLN: is pandas/tests/data used?

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#34427]
In `pandas/tests/data` there are two files:
```
iris.csv
tips.csv
```
Both of these files are also in `pandas/tests/io/data/csv`.

Do they need to be in both places? If not, can they be removed from one of them?

**Comment by najann** [comment]
<img width="1440" alt="output_duplicate_files" src="https://user-images.githubusercontent.com/47032941/83154865-ec045400-a100-11ea-9617-a7622baa5e70.png">

Apparently, `iris.csv` is only needed in `pandas/tests/data`. 
However, I'm not sure about `tips.csv`: It is definitely accessed in `pandas/tests/data`, too. There is no direct reference to the file in `pandas/tests/io/data/csv` but to the one in `pandas/tests/io/parser/data`. So, if that one contains parsed files from `tests/io/data` `tips.csv`is needed there.

**Comment by WillAyd** [comment]
Yea I think should clean these up. @najann interested in a PR?

**Comment by najann** [comment]
Yes, I can do that @WillAyd :)

**Comment by najann** [comment]
take
