### ISSUE TITLE
ENH: Implement min_max() function that returns both

### ISSUE THREAD

**Issue by matteosantama** [pandas-dev/pandas#34436]
#### Describe the solution you'd like

It might be a common enough situation for someone to want to know the min AND max of an index or series. I assume the min and max are not stored as attributes so the function has to scan all the data. It would be an improvement to scan once, and return both values as a tuple.

#### API breaking implications

None

```python
my_min, my_max = df.index.min_max()

```

**Comment by TomAugspurger** [comment]
I think we're using NumPy for most ops, so for an actual performance improvement this would need to go there.

**Comment by TomAugspurger** [comment]
Looks like there's an issue for this at https://github.com/numpy/numpy/issues/9836. Seems like there are some complexities, but we'll track that.
