### ISSUE TITLE
BUG: pivot_table calculates incorrect standard deviation when np.std passed to aggfunc

### ISSUE THREAD

**Issue by dcsaba89** [pandas-dev/pandas#34437]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

`
import numpy as np
import pandas as pd

df = pd.DataFrame({'A': ['a', 'a'], 'X': [2.8597, 2.8503]})
pivot = pd.pivot_table(df, index='A', values='X', aggfunc=(np.mean, np.std))
my_std = np.std(df.X)  # 0.0047000000000001485
pivot_std = pivot.loc['a', 'std']  # 0.006646803743153757
`

#### Problem description

pivot_table calculates incorrect standard deviation when np.std passed to aggfunc.

#### Expected Output
Numpy calculates the correct std in the given example.

**Comment by dsaxton** [comment]
pivot_table is using the unbiased estimate of variance where we divide by n - 1 instead of n:
```python
import numpy as np

np.std([2.8597, 2.8503], ddof=1)                                                                                                                                                               
# 0.006646803743153757
np.std([2.8597, 2.8503], ddof=0)                                                                                                                                                              
# 0.0047000000000001485
```

**Comment by mroeschke** [comment]
Going to close as a usage question.

**Comment by dcsaba89** [comment]
This difference is unexcepted:

df = pd.DataFrame({'A': ['a', 'a'], 'X': [2.8597, 2.8503]})
pivot = pd.pivot_table(df, index='A', values='X', aggfunc=(np.std, lambda x: np.std(x)))
lambda_std = pivot.loc['a', '<lambda_0>']  # 0.0047000000000001485
std = pivot.loc['a', 'std']  # 0.006646803743153757


In the above example,  standard deviation is calculated twice, in the first case, np.std function directly passed to aggfunc, on the other hand in the second case, a lambda function is passed to aggfunc which uses the same np.std function to calculate standard deviation. The results in these cases must equal.
