### ISSUE TITLE
BUG: to_numpy on empty dataframe allocates O(len(df)) array

### ISSUE THREAD

**Issue by huonw** [pandas-dev/pandas#34445]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas as pd
import tracemalloc as tm
import numpy as np

N = 123456789
df = pd.DataFrame(index=range(N))
tm.start()
arr = df.to_numpy(dtype=np.uint8)
memory, _ = tm.get_traced_memory()
print(memory, arr.size, arr.shape)
tm.stop()
```

Output:

```
123457803 0 (123456789, 0)
```

#### Problem description

If a DataFrame `df` has no columns, the result of `df.to_numpy(...)` is an array without any data, meaning there's nothing that can be read from/written to memory at all. This array doesn't require a large memory allocation, but one is still allocated (specifically it is allocated as if all the 0s in the shape were 1s). This could be optimised in some form. 

This is almost certainly the same bug as https://github.com/numpy/numpy/issues/16410, but could have an explicit work-around in Pandas (e.g. so that the memory is still not allocated on older versions of NumPy, and because it's somewhat unclear how/if the NumPy bug will be fixed).

#### Expected Output

The reported memory allocated by the `to_numpy` call should be minimal, and not change with `N`, e.g.

```
2640 0 (123456789, 0)
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.6.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_AU.UTF-8
LOCALE           : en_AU.UTF-8

pandas           : 1.0.3
numpy            : 1.18.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 3.0.3
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.11.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : 2.7.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : 0.8.3
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by TomAugspurger** [comment]
Do you have a proposed workaround in mind?

**Comment by huonw** [comment]
I don't know enough about the internals of Pandas to know if this would be easy to apply, but https://github.com/numpy/numpy/issues/16410 demonstrates that using `broadcast_to` can avoid the allocation. For example, `np.broadcast_to(np.uint8(0), (123456789, 0))` for the example in the PR description.

**Comment by TomAugspurger** [comment]
I don't think the array resulting `brodcast_to` has equivalent semantics though. For one thing, it's not writable. I don't know if that would qualify as an API breaking change so I'm hesitant to change it.

**Comment by huonw** [comment]
That's a fair concern, however, I believe it is equivalent for this case, because the 0 columns means there's no data and no way to access any memory (in particular, any `x[..., i]` will fail with an `IndexError`).

**Comment by mroeschke** [comment]
Thanks for the suggestion but it appears theres not much appetite to change this so closing
