### ISSUE TITLE
BUG:pandas use all() or any() get wrong result

### ISSUE THREAD

**Issue by sin-en-2009** [pandas-dev/pandas#34451]
- [ ] I have checked that this issue has not already been reported.
yes
- [ ] I have confirmed this bug exists on the latest version of pandas.
yes
- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.
yes
---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
print(data['shift1'].values.all() > 0,data['shift1'].values)
print(data['shift1'].values.any() > 0,data['shift1'].values[0],data['shift1'].values[1],-3680.0>0)
```

#### Problem description
True [-3680. -3680.]
True -3680.0 -3680.0 False
The value of series is clearly less than 0, but using all () and any () gives the wrong result

#### Expected Output
True [-3680. -3680.]
True -3680.0 -3680.0 False

#### Output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.7.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.3
numpy            : 1.18.4
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 39.1.0
<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by sin-en-2009** [comment]
现在我创建一个新的dataframe
temp = pd.DataFrame({'shift1':[-3680.0,-3680.0]},)
print(temp['shift1'].values, temp['shift1'].values.any()>0, temp['shift1'].values[0]>0)

result:
[-3680. -3680.] True False

**Comment by jorisvandenbossche** [comment]
@sin-en-2009 the github issues are meant for reporting potential bugs / enhancement requests, and not for general questions for help (but of course, the line between both is not always clear). For general usage questions, a Q&A forum like [StackOverflow](https://stackoverflow.com/questions/tagged/pandas) or the [pydata mailing list](https://groups.google.com/forum/#!forum/pydata) is a better place to ask.

In this case, you are using `any` in an incorrect way: `temp['shift1'].values.any() > 0` does not check if any of the values is above 0. Rather it checks if any of the values is true-like, which returns True, and then compares True > 0, which gives False.

What you want is to first compare with 0, and then use 'any' on the result of that:

```
In [4]: (temp['shift1'].values > 0).any()                                                                                                                                                                          
Out[4]: False
```

**Comment by connesy** [comment]
@jorisvandenbossche 
> then compares True > 0, which gives False.

I think you mean True here, not False.

**Comment by jorisvandenbossche** [comment]
Whoops, yes ;) Updated in the post above!
