### ISSUE TITLE
DEPS: drop 3.6

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#34472]
according to schedule we should 3.6 in june 2020

https://numpy.org/neps/nep-0029-deprecation_policy.html

prob ok to keep for the 1.1 release then should drop for 1.2. we will likely be adding. 3.9 support so this makes sense.

**Comment by alimcmaster1** [comment]
Happy to help here when the time comes :)

**Comment by simonjayhawkins** [comment]
> prob ok to keep for the 1.1 release then should drop for 1.2. we will likely be adding. 3.9 support so this makes sense.

we had a discussion about Python version support in #28415, so if doing this we need to update the version policy https://pandas.pydata.org/docs/development/policies.html#python-support

**Comment by simonjayhawkins** [comment]
looking at the number of downloads at https://anaconda.org/conda-forge/pandas/files i'm not convinced we should be doing this.

**Comment by jreback** [comment]
no we need to drop we are already supporting 3.9 and it's time 

and most of that is likely city

**Comment by simonjayhawkins** [comment]
what about https://github.com/pandas-dev/pandas/issues/34472#issuecomment-656740441

I'm all for dropping 3.6 (and using some typing stuff from 3.7), just want to make sure.

**Comment by jreback** [comment]
the version policy is wrong
it should say minor
