### ISSUE TITLE
DOC: improve the .equals() docstring

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#34498]
The current docstring for Series/DataFrame `equals` method can use some improvement (https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.equals.html):

- " The column headers do not need to have the same type" is not very clear, and also doesn't apply to Series.equals. Something like "The row/column index do not need to have the same type (as long as the values are still considered equal)" might be better
- The "Notes" section is mostly duplicating the long description at the top.

**Comment by freakypandit** [comment]
take
