### ISSUE TITLE
ENH: add logfmt support

### ISSUE THREAD

**Issue by link2xt** [pandas-dev/pandas#34501]
[logfmt](https://www.brandur.org/logfmt) is a structured log format similar to JSON lines, but much simpler. Each line has a format `column1=value1 column2=value2 ...`. Pandas already has support for JSON lines, which can be read with `pd.read_json(path, lines=True)`, but to read logfmt logs a conversion is needed.

I have been using [agrind](https://github.com/rcoh/angle-grinder) to convert logs to JSON lines, but it is an additional step that I would like to eliminate from my workflow. You can see an example at https://gitlab.com/nsnam/ns-3-dev/-/merge_requests/303

Besides, I would like to use logfmt as an output format for simple computational experiments (think C/Fortran without dependencies), because it is easier to maintain one line of code that outputs keys and values interleaved, in contrast to maintaining the code to output headers and code to output values separately. And logfmt becomes easier to read than CSV as the number of columns grows. Compare
```
node=1 throughput=63.0 delay=52.0 x=0.0 y=5.0
node=2 throughput=100.0 delay=35.0 x=5.0 y=5.0
```
to
```
node,throughput,delay,x,y
1,63.0,52.0,0.0,5.0
2,100.0,35.0,5.0,5.0
```

To read logfmt directly with pandas, I want a function `pd.read_logfmt()` that can be used in place of `pd.read_csv()` and `pd.read_json()` in described above cases.

**Comment by link2xt** [comment]
take

**Comment by jreback** [comment]
can u provide justification on how this is a popular format?

why would we not just document using this? why bake this into pandas itself?

**Comment by link2xt** [comment]
> can u provide justification on how this is a popular format?

[Official nodejs package](https://www.npmjs.com/package/logfmt) has 28k weekly downloads now. This is an official log format of Heroku and it is supported in [Elastic stack](https://www.elastic.co/), [Splunk](https://www.splunk.com/), [InfluxDB](https://docs.influxdata.com/telegraf/v1.14/data_formats/input/logfmt/), [Fluentd (with plugin)](https://www.fluentd.org/plugins/all).

> why would we not just document using this? why bake this into pandas itself?

I don't get what do you propose to document.

Using plain python logfmt package does not create `DataFrame` and infer dtypes, it parses the file into generator of dictionaries, parsing every field as string or boolean flags.

Angle-grinder, `logfmt` tool from npm and [hutils](https://blog.heroku.com/hutils-explore-your-structured-data-logs) require additional binary, NPM or Ruby. It is much easier to eliminate additional dependency and only install `logfmt` package from pypi or [conda-forge](https://github.com/conda-forge/staged-recipes/pull/11779).

**Comment by jorisvandenbossche** [comment]
> Using plain python logfmt package does not create DataFrame and infer dtypes, it parses the file into generator of dictionaries, parsing every field as string or boolean flags.

Have you proposed in that package to add pandas support?

In general we are rather converative in adding new formats in IO support in pandas, as there are *many* formats people would like to see added, and it is not scalable to add support for all possible formats directly into pandas. 
So therefore, I think we would rather encourage making external packages that give a nice pandas-like interface for people using pandas and want to read/write the specific format. 

And if such a package exists (whether it is in `logfmt` itself or in a new "pandas-logfmt" package), we can refer to that in our documentation. 
(we have an ecosystem page in the docs, but we should actually also do a better job of listing specifically third-party packages for file formats that are not natively supported in pandas on the IO doc page).

**Comment by jreback** [comment]
@link2xt using the conversion as code

if a user wanted to write this it’s just several lines of code right?

can i show an example here

**Comment by link2xt** [comment]
> if a user wanted to write this it’s just several lines of code right?

The problem is that there is no type inference, which is needed for pandas.

```python
#!/usr/bin/env python3

from io import StringIO

import logfmt
import pandas as pd

data = StringIO("x=1 y=2\nx=10 y=15")
df = pd.DataFrame(logfmt.parse(data))
print(type(df['x'][0]))
```

This code outputs `<class 'str'>`.

**Comment by jreback** [comment]
it would be better to make a package that has a to_pandas method

-1 on adding this directly to pandas at this time

**Comment by link2xt** [comment]
If I move this into a separate package, how do I use compression support from `get_filepath_or_buffer`? Is there any API exposed for that? PR #34494 tests for `.gz` support.

**Comment by jreback** [comment]
> If I move this into a separate package, how do I use compression support from `get_filepath_or_buffer`? Is there any API exposed for that? PR #34494 tests for `.gz` support.

nope but it’s pretty easy to implement

**Comment by link2xt** [comment]
I have moved the code to https://gitlab.com/link2xt/logfmt-pandas
