### ISSUE TITLE
BUG: DateOffset pickle bug when months=12

### ISSUE THREAD

**Issue by jjbarton** [pandas-dev/pandas#34511]
- [ x] I have checked that this issue has not already been reported.

- [ x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```
import pickle
import pandas as pd

offset = pd.DateOffset(months=12)

pickle.dump(offset, open("/tmp/o.p", "wb"))
loaded = pickle.load(open("/tmp/o.p", "rb"))
print(loaded)

# <DateOffset: months=12, years=1>

```

#### Problem description

If you pickle a pandas DateOffset instance with months=12, and then unpickle it, you have a DateOffset(months=12, years=1) instance (effectively a 2 year date offset object.

Arguably one shouldn't create a 12 month date offset in preference to a 1 year offset, but this is still bad behaviour imho.

#### Expected Output

print(loaded)
# <DateOffset: months=12>

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.0.3
numpy            : 1.18.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.4.0.post20200518
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by fujiaxiang** [comment]
@jjbarton Would you be interested to have a look and PR?
