### ISSUE TITLE
Release notes still missing for 1.0.4

### ISSUE THREAD

**Issue by impredicative** [pandas-dev/pandas#34513]
What's up with the release notes still missing for 1.0.4? It has been four days since the release. This is unprofessional.

https://github.com/pandas-dev/pandas/releases/tag/v1.0.4 links to https://pandas.pydata.org/docs/whatsnew/v1.0.4.html but the whatsnew page has been missing. Shouldn't it be made available no later than two hours after a release? People look for it and can't find it. A release shouldn't be published if its notes are not ready to go.

@simonjayhawkins you seem responsible.

**Comment by TomAugspurger** [comment]
@impredicative check your tone please: things like "unrpofessional" and "you seem responsible" are not kind.

See https://github.com/pandas-dev/pandas/issues/33300#issuecomment-635932128.

**Comment by simonjayhawkins** [comment]
try https://pandas.pydata.org/pandas-docs/version/1.0.4/whatsnew/v1.0.4.html in the meantime.

**Comment by impredicative** [comment]
@TomAugspurger Do you know what else is not kind? People wasting their time clicking on a link that doesn't work, waiting days, and it still doesn't work. A waste of time. Also, why did you close this issue when it's not resolved yet?

**Comment by jreback** [comment]
> @TomAugspurger I am stating the facts, and you don't like the facts. Do you know what else is not kind? People wasting their time clicking on a link that doesn't work, waiting days, and it still doesn't work. It's a waste of time. This is a routine problem with Pandas releases. Also, why did you close this issue considering it's not resolved yet? Who is your manager? I want to report your dysfunction to them.

@impredicative 

pandas is an open source project, which is ALL VOLUNTEER. If you want to help great. Otherwise, please stop comments that are not helpful at all.
