### ISSUE TITLE
Getting Attribute error while merging framed

### ISSUE THREAD

**Issue by datascientistpur** [pandas-dev/pandas#34527]
When merging frames,I am getting AttributeError:Dataframe object has no attribute _cols.
It shows the error in 5067 line of generic.py

Current pandas version:0.24.2

**Comment by jreback** [comment]
please show a reproducible example: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by rhshadrach** [comment]
@datascientistpur if you could give us a reproducible example, it would be very helpful. Just respond here and I'll reopen.
