### ISSUE TITLE
ENH: Implement categorical correlation

### ISSUE THREAD

**Issue by idankash** [pandas-dev/pandas#34528]
#### Is your feature request related to a problem?

Currently, whenever I want to visualize features correlation I'm using df.corr(), but when I have a dataset with categorical features I have to encode them before using df.corr() if I want to include the categorical features.

#### Describe the solution you'd like

I came across this article 
[https://towardsdatascience.com/the-search-for-categorical-correlation-a1cf7f1888c9](https://towardsdatascience.com/the-search-for-categorical-correlation-a1cf7f1888c9) 
and I wondered if I can implement the solution as a new feature or add it into corr().

#### API breaking implications

Maybe add another boolean parameter to corr which indicate that the user wants to include categorical features?

Thanks :)

**Comment by bashtage** [comment]
The "ideal" place for Cramer's V and Theil's U would be scipy.stats.  If these were available, then it would be easy to have

```
from scipy.stats import cramers_v, theils_u

df.corr(method=cramers_v)
df.corr(method=theils_u)
```

**Comment by idankash** [comment]
Hey, 
I'll open an issue on scipy's GitHub page for these two(cramers_v, theils_u).
One more question, let's say we already have these methods and I call corr like so  
df.corr(method=theils_u) or df.corr(method=cramers_v), 
both of them will give me the correlation of the categorical features.
If I have a mixed dataset according to the article I can use the correlation ratio, so the same goes here, the "ideal" place should be scipy.stats?

**Comment by bashtage** [comment]
It is tricky with a mixed dataset. Since you might want person for continuous, cramer/theil for 2 cats and (??) missing value for cross. While they appear to be missing from scipy (they are generally useful, not just in pandas), they would need some adapting for pandas.

**Comment by idankash** [comment]
Got you.
Can you pls explain what kind of adapting, so I know what to do when I'll implement it?

**Comment by bashtage** [comment]
If you had scipy functions (or similar "basic" functions that only understands numeric values), then you will need to get the underlying int64 values that are used in the categorical.  This is it I think, so something like

```
cramers_v(s1.cat.codes, s2.cat.codes)
```

rather than 

```
cramers_v(s1, s2)
```

**Comment by TomAugspurger** [comment]
@idankash did you open an issue in scipy? If so could you link back to this issue?

And I think let's close this for now, since we can't work on it till it's implemented in scipy.
