### ISSUE TITLE
ENH: Set numeric_only=True in aggregations

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#34521]
I've noticed that I make this mistake quite often:

```python
>>> df = pd.DataFrame({"a": ["1"] * 3, "b": np.ones(3)})
>>> df.sum()
a    111
b      3
dtype: object
```

Getting `111` as a result in column a is harmless in this example, but actually quite annoying in most real life use cases where it can produce exceedingly large strings that exhaust memory or tie up the interpreter.

The `numeric_only` argument gets around this issue:

```python
>>> df.sum(numeric_only=True)
b    3.0
dtype: float64
```

Though I'm curious if this should really be the default

**Comment by jorisvandenbossche** [comment]
There should already be some issues about this, eg I remember @jbrockmendel recently raising this as well, and I suspect some older issues as well

**Comment by jorisvandenbossche** [comment]
The one I remembered is https://github.com/pandas-dev/pandas/issues/28900, I think this can be closed as a duplicate?

**Comment by WillAyd** [comment]
It's a little bit different. That PR is about removing the kwarg whereas this is about changing the default value

The former would encapsulate the latter but we *may* want to do in steps instead of outright removal

**Comment by jorisvandenbossche** [comment]
OK, that's right, but I would still propose to use the other issue for that discussion? As in the end it is a single discussion about what to do with this keyword: keep as is, change default, or fully remove. It are not really separate discussion? 
So I would put your proposal to change the default (instead of removing the kwarg) in #28900

**Comment by WillAyd** [comment]
Sure that works just as well
