### ISSUE TITLE
BUG: Groupby sum, different result between 0.25.3 and 1.0.4

### ISSUE THREAD

**Issue by Xachriel** [pandas-dev/pandas#34532]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---
This is most likely a known problem, but I did not find an exact issue where to copy this behavior.
I ran into a problem between functionalities between 0.25.3 and 1.0.4.

Now:
```python
import pandas
df = pandas.DataFrame({"id": [1, 1], "value_1": [None, None], "value_2": [0, 0]})
df.loc[df["value_1"].isnull(), "value_1"] = 0
df.groupby("id").sum()
```

#### Problem description
In 1.0.4 the output is:
```python
    value_2
id         
1         0
```
Is this now the intended behaviour?
This is most likely because:
```python
df.dtypes
id          int64
value_1    object
value_2     int64
```

#### Expected Output
In 0.25.3
```python
    value_1  value_2
id                  
1         0        0
```
dtypes are
```python
df.dtypes
id          int64
value_1     int64
value_2     int64
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.2.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.5.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_GB.UTF-8
pandas           : 1.0.4
numpy            : 1.18.4
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 47.1.1
Cython           : None
pytest           : 5.3.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.3.2
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by jorisvandenbossche** [comment]
@Xachriel Thanks for the report! 

It seems the underlying change is actually the dataframe creating / setting, not the groupby:

```
df = pandas.DataFrame({"id": [1, 1], "value_1": [None, None], "value_2": [0, 0]})
df.loc[df["value_1"].isnull(), "value_1"] = 0
df.dtypes
```

gives

```
# master
id          int64
value_1    object
value_2     int64
dtype: object

# pandas 0.25.3
id         int64
value_1    int64
value_2    int64
dtype: object
```

And I suppose because it is now an object dtype column, it is automatically left out in the groupby operation.

**Comment by Xachriel** [comment]
yes, that is true. Is this kind of dtype behavior now the current normal, or is this considered a bug? This is really an edge case, but kind of annoying as you cannot even force it with:
```python
df.groupby("id")[["value_1", "value_2"]].sum()
```
But this works correctly:
```python
df.groupby("id")[["value_1"]].sum()
```

**Comment by jreback** [comment]
this is not a bug rather pandas tries to preserve dtypes

using None in construction creates an object column
if you want numeric then create as numeric, use Int64 or coerce

**Comment by jorisvandenbossche** [comment]
> Is this kind of dtype behavior now the current normal

Yes, I would say that in general it is an improvement that we try to preserve the original dtype, because it was inconsistent before. On 0.25.3:

```
In [14]: s = pd.Series([None, None])  

In [17]: s[s.isna()] = 0  

In [18]: s    
Out[18]: 
0    0
1    0
dtype: object

In [19]: s.loc[s.isna()] = 0   

In [20]: s   
Out[20]: 
0    0
1    0
dtype: int64
```

So direct getitem preserved object dtype, but `.loc` not. 
Now on pandas 1.0, both preserve object dtype.

>  kind of annoying as you cannot even force it with: 
> ``df.groupby("id")[["value_1", "value_2"]].sum()``

In any case, it is better to ensure you have "proper" dtypes (so not object for numerical columns) before calling groupby (not only for the issue above, but also for performance). 
But, I would say that the above indeed should include the column, even if it is object, since you explicitly selected it (for dataframe, pandas cannot detect this, but for groupby we actually do. So it would give an inconsistency, though).

But you can always force to use all columns by passing `numeric_only=False`:

```
In [35]: df.groupby("id").sum(numeric_only=False) 
Out[35]: 
    value_1  value_2
id                  
1         0        0
```

**Comment by jreback** [comment]
@jorisvandenbossche this is clearly documented and expected behavior

why did you reopen this?

**Comment by jorisvandenbossche** [comment]
Because I was having a conversation with @Xachriel 

The groupby behaviour is certainly documented (it's here btw: https://pandas.pydata.org/docs/dev/user_guide/groupby.html#automatic-exclusion-of-nuisance-columns, which also mentions the case of selecting nuisance columns), but the dtype change between 0.25 and 1.0 is certainly not that obvious.

**Comment by rhshadrach** [comment]
There is a consensus that there is no issue and no more conversation.
