### ISSUE TITLE
Chunksize from json memory consumption as high as without chunksize

### ISSUE THREAD

**Issue by hasnain2808** [pandas-dev/pandas#34548]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

While working on the PR (#33962) for adding nrows to read_json it was seen that maybe the chunksize parameter for read_json is not doing its task. ASV benchmarks were carried out but as this issue is not related to the PR we decided to create a new issue for it

Here is the link to the paste that has all the results
[paste](https://pastebin.com/E22PAxKe)
The results are nicely added this to this spreadsheet
[spreadsheet](https://docs.google.com/spreadsheets/d/1MjE2iMrlYnWbnfSyizfYI3IbwSK1z760VKeoYfCBeJs/edit?usp=sharing)

**Comment by hasnain2808** [comment]
Someone please add the 'Needs Discussion' label

**Comment by fabriceyhc** [comment]
I'm having the same issue with pandas==1.1.0 and downgraded to pandas==1.0.0 in order to get a usable JsonReader.
