### ISSUE TITLE
DOC: DatetimeIndex day says the same as month

### ISSUE THREAD

**Issue by VictorGerritsen** [pandas-dev/pandas#34544]
#### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DatetimeIndex.day.html#pandas.DatetimeIndex.day

#### Documentation problem

Right now it says the same as month, `The month as of January=1, December=12`

#### Suggested fix for documentation

Something along the lines of `Day of the month, from 1 through 31`

**Comment by MarcoGorelli** [comment]
Sounds good - are you interested in submitting a pull request?

**Comment by raphacosta27** [comment]
Hi guys, if there's a chance, I can submit the PR.

**Comment by MarcoGorelli** [comment]
Hey @raphacosta27 - sure, PRs are welcome! Just for reference, if you comment 'take', the issue will be assigned to you

> Hi guys

Minor note, but in general we encourage inclusive behavior - for example, please don’t say “hey guys!” but “hey everyone!” (see https://github.com/pandas-dev/pandas/blob/master/web/pandas/community/coc.md)

**Comment by erfannariman** [comment]
@raphacosta27 are you still working on this? Else I would like too.

**Comment by raphacosta27** [comment]
> @raphacosta27 are you still working on this? Else I would like too.

Hi there! I'm out of time, please, go ahead and take it.

**Comment by erfannariman** [comment]
take

**Comment by kishvanchee** [comment]
@erfannariman are you still working on this? Else I am interested in taking this

**Comment by erfannariman** [comment]
Yes, I will take some time to submit a MR this week, if I didn't have time, you can take over after that. @kishvanchee

**Comment by MarcoGorelli** [comment]
Looks like this was already fixed in #31490. Indeed, the development version of the docs looks correct - https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DatetimeIndex.day.html?highlight=datetimeindex%20day#pandas.DatetimeIndex.day

Sorry @erfannariman for not having picked up on this sooner
