### ISSUE TITLE
DOC: Wrong description of behaviour Series.pop()

### ISSUE THREAD

**Issue by bestrandomnameever** [pandas-dev/pandas#34569]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.pop.html

#### Documentation problem

Documentation describes that the operation would not return the popped column and would instead return the modified version of the Series (making it appear as a non-inplace function). Actual behavior however returns the value of the popped column and executes the operation in-place.

#### Suggested fix for documentation

Use the documentation of the similar and well described method of Dataframe.pop() and adjust it for Series (return a value instead of a Series).

**Comment by MarcoGorelli** [comment]
Thanks @bestrandomnameever for the report

To be fair it's kind of hard to understand what Series.pop does from the docs, so if you want to submit a pull request to improve them I'm sure that would be welcome!

**Comment by 2796gaurav** [comment]
take

**Comment by 2796gaurav** [comment]
@MarcoGorelli Hi, can I add inplace -True parameter to this function. What do you say?

**Comment by MarcoGorelli** [comment]
@2796gaurav isn't it already inplace?

```python
>>> import pandas as pd
>>> s = pd.Series([1,2,3])
>>> s.pop(0)
1
>>> s
1    2
2    3
dtype: int64
```

I think the issue is more that's it's no so clear from the docs what it does. The docs talk about columns (which a Series doesn't have), when they should talk about the index.

Also, the return type is not a Series (as `FrameOrSeries` would suggest)

**Comment by 2796gaurav** [comment]
@MarcoGorelli can I make the changes?

**Comment by 2796gaurav** [comment]
take
