### ISSUE TITLE
ENH: more functions like between_time()

### ISSUE THREAD

**Issue by jerryzhujian9** [pandas-dev/pandas#34562]
I have a time index for data frame in full date time format: eg,

> 2019-04-18 11:23:00
> 2020-06-03 11:00:00

Currently it is easy to slice with `between_time("08:00","09:00")` to get rows from 8am-9am across all the days I have in the data frame.

However, if I want to get all data in April across years, I wish I could do` between_month(4,4)`. Similarly, `between_day(1,15)`, or `between_year(2019,2020)`

**Comment by jreback** [comment]
see https://pandas.pydata.org/docs/user_guide/timeseries.html Indexing section 

this is already very easy to do and would be -1 on adding more specific api

**Comment by jerryzhujian9** [comment]
I did read the link you posted. However, I think it would require something a bit award like to select month which is lower time frame than year.

` df[(df.index.month>=3) & (df.index.month<=9)]`

**Comment by jreback** [comment]
and this is the idiomatic way of selecting / indexing 

having named in every object for each is just boating the api

in reality between_time should be depreciated as well

**Comment by jerryzhujian9** [comment]
oh no, please do not depreciate between_time. It is very useful to get specific time window across days/months/years.

**Comment by daskol** [comment]
> in reality between_time should be depreciated as well

Aggreed with @jerryzhujian9. Do not deprecate, please. I think that it would be more idiomatic way of selecting time ranges with `datetime.time` or internal `pandas` type.
```python
def foo(df: pd.DataFrame, begin, end):
    """Some generic function.
    """
    ...
    df.loc[begin, end].groupby(....)  # do something
    ...

foo(df_uint_indexed, 42, 228)
foo(df_time_indexed, time(hours=14), time(hours=16))
```

**Comment by TomAugspurger** [comment]
I don't think we're likely to add `between_<thing>` for all the different resolutions people would like to filter by.

**Comment by mroeschke** [comment]
Thanks for the suggestion but agreed that creating boolean indexing masks is pandas' preferred method that overlaps with this enhancement request.

Since there hasn't been much enthusiasm for this feature from the core devs, closing.
