### ISSUE TITLE
ENH: pipe function enhancement

### ISSUE THREAD

**Issue by qitianliang** [pandas-dev/pandas#34567]
feature request about `.pipe`
many data science need know the details of processing...
so if we define lots of functions to processing the raw data, and we need the details of each processing, I'm not familiar to the pipe function, but this way may be elegant way to summary this processing...

df.pipe(func0).pipe(func1).pipe(func2).summary()
which summary can summary all your functions in pipe line,such as shape or some others function that can apply to the result of dataframe/series

**Comment by TomAugspurger** [comment]
That's not possible given pandas' eager execution.

I'd recommend placing the logging / annotations on the functions themselves, possible as a decorator. https://tomaugspurger.github.io/method-chaining.html has an example.
