### ISSUE TITLE
DOC: The argument of pandas.DataFrame.to_markdown is unfriendly

### ISSUE THREAD

**Issue by nuka137** [pandas-dev/pandas#34568]
#### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.to_markdown.html

#### Documentation problem

The document of `pandas.DataFrame.to_markdown` is unfriendly because many options are shown as `**kwargs`.
I think these arguments should be documented explicitly like a `to_csv`.

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.to_csv.html

#### Suggested fix for documentation

All arguments supported by `to_markdown` should be shown at document.
If don't mind, I would like to tackle this improvement.

**Comment by MarcoGorelli** [comment]
Thanks @nuka137 - there's [a PR](#33091) open to document 'index', if you'd like to document other options I think that would be welcome

**Comment by TomAugspurger** [comment]
I'd caution against adding too many keyword arguments. The function could be expanded in the future to accept an `engine` function to determine which package we use to format things.

So we should only add explicit keywords for names that are standard across the rest of pandas IO methods.

**Comment by nuka137** [comment]
@MarcoGorelli @TomAugspurger 

I agree not to introduce many keywords. But I didn't intend to add more keyword arguments in this issue.
This issue mentions the unclear documentation of `**kwargs`.

I think adding a link of [tabulate package](https://pypi.org/project/tabulate/) to this document is enough for the user.
Or, it may be good to add an example which uses tabulate argument.
The users can check what options they need to pass to `**kwargs`.
What do you think of this idea?

**Comment by TomAugspurger** [comment]
Thanks, both of those sound like great ideas.

**Comment by nuka137** [comment]
I noticed `pandas.Series.to_markdown` has same argument.  
So, I also created PR for it (#34616 ).
