### ISSUE TITLE
BUG: problem with index set_names when names is a list

### ISSUE THREAD

**Issue by zsinnema** [pandas-dev/pandas#34571]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Problem description

I have a question: 

why raise a ValueError here https://github.com/pandas-dev/pandas/blob/1ce1c3c1ef9894bf1ba79805f37514291f52a9da/pandas/core/indexes/base.py#L1239 when values can be a list and thus len of the list can be > 1

and please also check this: https://github.com/pandas-dev/pandas/blob/1ce1c3c1ef9894bf1ba79805f37514291f52a9da/pandas/core/indexes/base.py#L1246 if it's a list why select the first element?

**Comment by TomAugspurger** [comment]
Can you provide a reproducible example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by zsinnema** [comment]
Ah o wait, sorry I think I need to look at MultiIndex
