### ISSUE TITLE
BUG: read_csv with quoting=csv.QUOTE_NONNUMERIC error trying to convert header row

### ISSUE THREAD

**Issue by scimecac** [pandas-dev/pandas#34581]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here

```

#### Problem description
attempt to read_csv file with first row header. Using option quoting=csv.QUOTE_NONNUMERIC and header=0.  causes:

"ValueError: could not convert string to float: 'frid'"
   **(frid is my column name defined in the header row)

My text type fields are quoted and numeric are not. Looks like the quoting=csv.QUOTE_NONNUMERIC tries to convert non-quoted values to numeric, however it is also doing this to the header row.

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]
Most methods of dumping to csv do not quote the header row names. read_csv() function should not attempt to convert unquoted header row names.

#### Expected Output
Header row should not be subject to data conversion, as header names are always text.

#### Output of ``pd.show_versions()``
0.25.1

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]
0.25.1

**Comment by fujiaxiang** [comment]
@scimecac  thanks for reporting this issue.
Can you add a code example to your Code Sample section that shows us the error?
Also if possible, can you share what your CSV file look like?

**Comment by MarcoGorelli** [comment]
Closing as it's not clear how to reproduce this, but please do ping if you write a bug report as suggested above
