### ISSUE TITLE
BUG: Series.where doesn't work with empty lists

### ISSUE THREAD

**Issue by jluttine** [pandas-dev/pandas#34592]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas. (Checked 1.0.3)

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
>>> pd.Series([], dtype=float).where([])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/vqd2pmsja84h36wz6c878bgbpz46cy2h-python3.7-pandas-1.0.3/lib/python3.7/site-packages/pandas/core/generic.py", line 8919, in where
    cond, other, inplace, axis, level, errors=errors, try_cast=try_cast
  File "/nix/store/vqd2pmsja84h36wz6c878bgbpz46cy2h-python3.7-pandas-1.0.3/lib/python3.7/site-packages/pandas/core/generic.py", line 8673, in _where
    raise ValueError(msg.format(dtype=cond.dtype))
ValueError: Boolean array expected for the condition, not float64
```

For comparison, if the list isn't empty, it works:

```python
>>> pd.Series([42], dtype=float).where([True])
0    42
dtype: int64
```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

If `where` accepts lists as its mask argument, it should work for empty lists too. Either don't support lists at all or support empty lists too.

#### Expected Output

```
>>> pd.Series([], dtype=float).where([])
Series([], dtype: float64)
```

#### Output of ``pd.show_versions()``

<details>

>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.41
machine          : x86_64
processor        :
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.18.3
pytz             : 2019.3
dateutil         : 2.8.1
pip              : None
setuptools       : None
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : 1.3.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : None
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.13
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : None
numba            : None

</details>

**Comment by simonjayhawkins** [comment]
Thanks @jluttine for the report.

It appears that #21947 fixed this issue for the DataFrame case.

numpy returns the same array in this case.

```
>>> np.where([], np.array([], dtype=float), [])
array([], dtype=float64)
>>>
```

have opened a PR with similar behaviour for Series.

```
>>> pd.Series([], dtype=float).where([])
Series([], dtype: float64)
```
