### ISSUE TITLE
DOC: Can't figure out how to get exponential working

### ISSUE THREAD

**Issue by tavurth** [pandas-dev/pandas#34593]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd

to_test = pd.DataFrame({ "data": [1,2,3,4,5,6,7,8,9,10] })
exponent = to_test.rolling((3,4), win_type="exponential").mean()

print(exponent)
```

```error
ValueError: exponential window requires tau
```

```python
import pandas as pd

to_test = pd.DataFrame({ "data": [1,2,3,4,5,6,7,8,9,10] })
exponent = to_test.rolling(3, win_type="exponential", tau=4).mean()

print(exponent)
```

```error
TypeError: rolling() got an unexpected keyword argument 'tau'
```

#### Problem description

I can't get exponential rolling working, and there's no documentation on this.

#### Expected Output
The exponential mean of the first 4 values

#### Output of ``pd.show_versions()``
<details>

INSTALLED VERSIONS

------------------

commit           : None
python           : 3.7.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.3.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.0.4
numpy            : 1.18.5
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 46.0.0
Cython           : 0.29.17
pytest           : 5.4.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : 0.4.1
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.14.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.2.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.17.0
pytables         : None
pytest           : 5.4.2
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : 0.8.7
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
</details>

**Comment by tavurth** [comment]
I finally fixed this by changing the code as follows:

```python
import pandas as pd

to_test = pd.DataFrame({ "data": [1,2,3,4,5,6,7,8,9,10] })

exponent = to_test.rolling(3, win_type="exponential").mean(tau=5)

print(exponent)
```

I was hoping this could be documented somewhere, and hence this issue. I can't find any other reference online about this.

**Comment by MarcoGorelli** [comment]
Thanks @tavurth for the report

> there's no documentation on this.

Here it is https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.Series.rolling.html

Though to be fair, perhaps `exponential (needs tau)` doesn't make it too clear where the `tau` needs to go, so if you have an idea on how to clarify this, I think a PR would be welcome

**Comment by wchen928** [comment]
How about `exponential (needs tau in operation argument)`?

**Comment by MarcoGorelli** [comment]
Yes, I think that would be clearer - would you like to submit a pull request, @wchen928 ? If so, perhaps reword the others where this happens too (e.g. `gaussian (needs std)`)

**Comment by wchen928** [comment]
> Yes, I think that would be clearer - would you like to submit a pull request, @wchen928 ? If so, perhaps reword the others where this happens too (e.g. `gaussian (needs std)`)

Sounds good. I will do that.

**Comment by wchen928** [comment]
I hope I did it right. I am not sure what the 5 tasks are. Do I need to check them off? or the reviewer will check them off? Sorry about the entry-level question... this is my first commit.

**Comment by dsaxton** [comment]
> I hope I did it right. I am not sure what the 5 tasks are. Do I need to check them off? or the reviewer will check them off? Sorry about the entry-level question... this is my first commit.

You did, for documentation fixes like this most of those boxes don't really apply (and actually checking them off isn't a big deal, more important is the content of the changes)

**Comment by wchen928** [comment]
> You did, for documentation fixes like this most of those boxes don't really apply (and actually checking them off isn't a big deal, more important is the content of the changes)

Thank you so much for the explanation!
