### ISSUE TITLE
BUG: Positional Arguments Passed as a Keyword Argument in Custom Rolling Aggregation

### ISSUE THREAD

**Issue by daskol** [pandas-dev/pandas#34605]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Problem description

According to [docstring][1] of `Rolling.apply` arguments `args` and `kwargs` allow to pass to a custom function positional and keyword arguments enumerated in `kwargs`.  However, `Rolling.apply` passes both of them as keyword arguments. In other word, it passes keyword `args ` consisting of "positional" arguments. This is definitely buggy behaviour.

The reason is that a closure function is built in [a wrong way][2]. The issue states for `cython` backend as well as `numba` backend. The possible should looks like the following.
```diff
diff --git a/pandas/core/window/rolling.py b/pandas/core/window/rolling.py
index a01a753e8..32360848a 100644
--- a/pandas/core/window/rolling.py
+++ b/pandas/core/window/rolling.py
@@ -1313,11 +1313,11 @@ class _Rolling_and_Expanding(_Rolling):
 
         window_func = partial(
             self._get_cython_func_type("roll_generic"),
-            args=args,
-            kwargs=kwargs,
+            *args,
             raw=raw,
             offset=offset,
             func=func,
+            **kwargs,
         )
 
         def apply_func(values, begin, end, min_periods, raw=raw):
```
[1]: https://github.com/pandas-dev/pandas/blob/1.0.x/pandas/core/window/rolling.py#L1237-L1240
[2]: https://github.com/pandas-dev/pandas/blob/1.0.x/pandas/core/window/rolling.py#L1314-L1321

**Comment by mroeschke** [comment]
Could you give an example of the buggy behavior? It looks like the args are being passed to the function:

**Comment by daskol** [comment]
Sorry, I was mistaken in the previous investigation. The issue is more intricate than it seems at a glance.

```python
def foo(*args, **kwargs):
    assert len(args) == 2, 'Too a few pos argumnets.'
    return float('nan')


df = pd.DataFrame(data={'X': range(5)},
                  index=[0, 0, 1, 1, 1])

df.rolling(1) \
    .apply(foo, raw=True, args=(42,))  # ok

df.groupby(level=0) \
    .rolling(1) \
    .apply(foo, raw=True, args=(42,))  # failed
```

The second `.apply()` is applied to an instance of `pandas.core.window.rolling.RollingGroupby`  but `pandas.core.window.rolling.Rolling`. The major difference of these `rolling`-objects is that `pandas.core.window.rolling.RollingGroupby` has another method resolution order due to `pandas.core.window.common.WindowGroupByMixin` object. 

So, [this snippet][1] elucidates where buggy behavour is from. Method `_apply()` invokes either common agg functions (like `sum()` or `mean()`) or original not curried custom agg function. In the example above `func` is `_Rolling_and_Expanding._generate_cython_apply_func.<locals>.apply_func` and `name` is just `foo`.

```python
class WindowGroupByMixin(GroupByMixin):
     def _apply(
        self,
        func: Callable,
        ....
        name: Optional[str] = None,
        ....
    ):
        def f(x, name=name, *args):
            x = self._shallow_copy(x)

            if isinstance(name, str):
                return getattr(x, name)(*args, **kwargs)

            return x.apply(name, *args, **kwargs)
```

[1]: https://github.com/pandas-dev/pandas/blob/1.0.x/pandas/core/window/common.py#L83-L89

**Comment by mroeschke** [comment]
It appears this is fixed on master now, and will be fixed in the pandas 1.1 release. I think https://github.com/pandas-dev/pandas/pull/34052 inadvertently fixed this. It'd be good to add a test to confirm.

```
In [4]: df.groupby(level=0) \
   ...:     .rolling(1) \
   ...:     .apply(foo, raw=True, args=(42,))
Out[4]:
      X
0 0 NaN
  0 NaN
1 1 NaN
  1 NaN
  1 NaN

In [5]: pd.__version__
Out[5]: '1.1.0.dev0+1800.g43a463d22'
```

**Comment by gglanzani** [comment]
take

**Comment by gglanzani** [comment]
Hi, I'm preparing a tutorial on pytest for PyData Amsterdam 2020.

The tutorial — which is part of a longer serie — should prepare them to start contributing on pandas.

I thought this would be a good issue to illustrate how people can get started with pytest. I plan to work these days until the 17/06 (day of the tutorial).

I should be able to create a pull request for this, so I'm not taking it for the sake of the tutorial.

**Comment by daskol** [comment]
> The tutorial — which is part of a longer serie — should prepare them to start contributing on pandas.
>
> I thought this would be a good issue to illustrate how people can get started with pytest. I plan to work these days until the 17/06 (day of the tutorial).

@gglanzani This is great! Thanks for helping and good luck with your talk.
