### ISSUE TITLE
I can't get this to work

### ISSUE THREAD

**Issue by CarlosAV91** [pandas-dev/pandas#34609]
https://github.com/pandas-dev/pandas/blob/1ce1c3c1ef9894bf1ba79805f37514291f52a9da/pandas/core/frame.py#L6253-L6323

if I run the lines I get a syntax error with the ":" after column. If I try to import and test on a dataframe i get an error that .explode is not an attribute. :'(

**Comment by dsaxton** [comment]
Can you provide some sample code that can be copy / pasted to reproduce your problem? BTW you shouldn't need to actually define this function anywhere, it should just be a method you can use on a DataFrame.

**Comment by CarlosAV91** [comment]
Thank you for such a quick reply! The first time I tried to define the function as it is written in the lines above, to no avail. the second time i tried  

`import numpy as np
import pandas as pd

df = pd.DataFrame ({'P': [[2,3,4], 'fff', [], [4,5]], 'Q': 2})
df

df = pd.DataFrame({'P': [[2, 3, 4], 'fff', [], [4, 5]], 'Q': 2})
df.explode('P')`

and I got the AttributeError, saying explode is not an attribute.

**Comment by rhshadrach** [comment]
The explode function was added in version 0.25.0 of pandas. Can you check to see what version you have? Try running the following code:

    import pandas as pd
    pd.show_versions()

**Comment by CarlosAV91** [comment]
I am in version 1.0.3

**Comment by CarlosAV91** [comment]
> The explode function was added in version 0.25.0 of pandas. Can you check to see what version you have? Try running the following code:
> 
> ```
> import pandas as pd
> pd.show_versions()
> ```

I am in version 1.0.3

**Comment by dsaxton** [comment]
This seems to work on 1.0.3:

```python
[ins] In [1]: import numpy as np
         ...: import pandas as pd
         ...:
         ...: df = pd.DataFrame ({'P': [[2,3,4], 'fff', [], [4,5]], 'Q': 2})
         ...: df
         ...:
         ...: df = pd.DataFrame({'P': [[2, 3, 4], 'fff', [], [4, 5]], 'Q': 2})
         ...: df.explode('P')
Out[1]:
     P  Q
0    2  2
0    3  2
0    4  2
1  fff  2
2  NaN  2
3    4  2
3    5  2

[ins] In [2]: pd.__version__
Out[2]: '1.0.3'
```

**Comment by CarlosAV91** [comment]
Ok, thank you, @dsaxton . It's at least helpful to see it does work for others. I will keep digging; it could be a different issue why it didn't work for me.

**Comment by dsaxton** [comment]
@CarlosAV91 No problem. I'm going to close this for now but feel free to reopen if you feel there's still an issue that needs addressing.
