### ISSUE TITLE
QST: How to plot hist not in stacked style for different columns by df.plot.hist()?

### ISSUE THREAD

**Issue by futurehome** [pandas-dev/pandas#34629]
-  I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

When using pd.plot.hist(), how to plot different columns in the parallel style(1st pic below), rather than in the stacked style(2nd pic below)?

Thanks,
Alex

![image](https://user-images.githubusercontent.com/6230304/83967855-b416c100-a8f7-11ea-8491-17763ca13384.png)

![image](https://user-images.githubusercontent.com/6230304/83967844-9d706a00-a8f7-11ea-8f86-a439ade13dab.png)

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
# Your code here, if applicable

```

**Comment by rhshadrach** [comment]
You can do this by calling matplotlib and passing in the values of a DataFrame:

````
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randn(30, 2), columns=['A', 'B'])
ax = plt.hist(df.values, label=df.columns)
legend = plt.legend()
````

produces

![image](https://user-images.githubusercontent.com/45562402/83970623-ae43c000-a8a4-11ea-9bae-a0ce2b6a1211.png)

**Comment by futurehome** [comment]
Yes, it's what I want. But can it be done by plotly backend in Pandas pd.plot?

**Comment by rhshadrach** [comment]
Currently, I don't believe so. Right now the plots are constructed for each column and then combined together. In order to have them side-by-side as you desire, the internal code would need to be refactored so that all of the data is passed to matplotlib in a single call.

@TomAugspurger: Any thoughts here? Would having the option to have the histogram bars be side-by-side be a welcomed enhancement?

**Comment by TomAugspurger** [comment]
I haven't looked in a while, but it sounds like that wouldn't be easily doable with the current implementation. I'd be hesitant to add anything too complex.

**Comment by futurehome** [comment]
Got it.

Thanks.
