### ISSUE TITLE
ENH: Add max_results to `read_gbq`

### ISSUE THREAD

**Issue by charlesdong1991** [pandas-dev/pandas#34639]
For queries for which the purpose is to create/replace tables: `CREATE OR REPLACE TABLE`, if the table is huge, it will eat up a lot of memory currently using `read_gbq`.

And it turns out that since `pandas-gbq==0.12.0`, a new argument `max_results` was implemented to limit the number of rows in result dataframe for e.g. setting it to `0` for DDL queries, which will help save memory.

So it will be nice for pandas to add it for `read_gbq` as `pandas-gbq` does.

**Comment by JohnPaton** [comment]
I can take a swing at this!
