### ISSUE TITLE
CLN: remove `private_key` and `verbose` from gbq

### ISSUE THREAD

**Issue by charlesdong1991** [pandas-dev/pandas#34640]
Since `verbose` and `private_key` have been deprecated since https://github.com/pandas-dev/pandas/pull/30200, we should also remove both from function since they are not used at all? see them in `read_gbq` and `to_gbq`, e.g.

https://github.com/pandas-dev/pandas/blob/24857a2844be9ee6f604d93ea18301f587751f0a/pandas/io/gbq.py#L33

https://github.com/pandas-dev/pandas/blob/24857a2844be9ee6f604d93ea18301f587751f0a/pandas/io/gbq.py#L34

**Comment by faraz16iqbal** [comment]
Is this issue still up for grabs?

**Comment by lathamri** [comment]
take

**Comment by lathamri** [comment]
take

**Comment by faraz16iqbal** [comment]
taking up this task

**Comment by charlesdong1991** [comment]
Hey, @faraz16iqbal thanks for your interest in helping out, there is an open PR already to fix this issue.

Feel free to look for other issues!
