### ISSUE TITLE
PERF: don't consolidate at __init__

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#34657]
xref mailing list [discussion](https://mail.python.org/pipermail/pandas-dev/2020-June/001246.html)

ATM most calls to `DataFrame(foo)` will end up going through either `core.internals.managers.create_manager_from_blocks` or `core.internals.managers.create_block_manager_from_arrays`, both of which call `mgr._consolidate_inplace()` before returning a `BlockManager` object.  I think we should consider disabling this consolidation.  (There is also consolidation-by-another-name within form_blocks that im still tracking down)

Behavior-wise, consider:

```
arr = np.random.randn(10)
ser = pd.Series(arr)

df = pd.DataFrame({"A": arr, "B": ser})
```

ATM we get a new 2x10 array backing `df`.  The proposed change would mean that we keep 2 separate arrays, and `df["B"]` shares data with `ser`.  I find the proposed behavior more intuitive.

Performance-wise, we expect faster construction but slower subsequent operations. [note to self: get some estimates/measurements here].  For long-lived DataFrames where the subsequent slowdowns add up, we can suggest users call `_consolidate()` (which i guess we would have to de-privatize)

**Comment by TomAugspurger** [comment]
Most likely this should live behind a `pd.options` config, and possibly a parameter to `DataFrame.__init__` first. That will let people try things out easily and report back performance on real-world workloads.

**Comment by jorisvandenbossche** [comment]
Personally I am not sure whether it is worth pursuing this for the current BlockManager. It has impact on performance and on copy/view semantics, so we should be careful about changing it, which will take some effort. 
Related to the mailing list discussion, I think we should we rather put this effort in a non-consolidating block manager (and eg put that behind a config)

**Comment by jbrockmendel** [comment]
> Most likely this should live behind a pd.options config, and possibly a parameter to DataFrame.__init__ first. That will let people try things out easily and report back performance on real-world workloads.

This seems reasonable.  ATM the branch I've got going adds a `consolidate` parameter to `create_block_manager_from_arrays` that defaults to False, but it would be easy to have it default to True and be override-able from the DataFrame constructor.

That said, global options always make me wary of test coverage.  e.g. the branch I'm working on looks like it has uncovered some weird behavior of `BlockManager._unstack` that I need to track down.
