### ISSUE TITLE
BUG: DataFrame.to_dict() converts Nullable Int types to numpy.int

### ISSUE THREAD

**Issue by dmlogv** [pandas-dev/pandas#34665]
#### Problem description

`DataFrame.to_dict()` method do not cast Nullable Int types (`Int*Dtype`) into Python `int` type. Instead, it unwrapping into `numpy.int*` types.

Possibly related to: #27616, #25969, #21256

#### Expected Output

Native Python `int` type.

#### Reproduction

Make some data:

```python
import pandas as pd

df = pd.DataFrame({'id': range(5),
                   'coeff': [i * 0.1 for i in range(5)],
                   'is_hot': [True] * 2 + [False] * 3,
                   'value': [1, None, 2, 3, None]})
df
```

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>id</th>
      <th>coeff</th>
      <th>is_hot</th>
      <th>value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>0.0</td>
      <td>True</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>0.1</td>
      <td>True</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2</td>
      <td>0.2</td>
      <td>False</td>
      <td>2.0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>3</td>
      <td>0.3</td>
      <td>False</td>
      <td>3.0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>4</td>
      <td>0.4</td>
      <td>False</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>

```python
df.dtypes

id          int64
coeff     float64
is_hot       bool
value     float64
dtype: object
```

`value` have to be a nullable `int`:

```python
df['value'] = df['value'].astype(pd.Int64Dtype())
df.dtypes

id          int64
coeff     float64
is_hot       bool
value       Int64
dtype: object
```

Looks great. But convert a dataframe to `dict`:

```python
dicts = df.to_dict(orient='records')
dicts

[{'id': 0, 'coeff': 0.0, 'is_hot': True, 'value': 1},
 {'id': 1, 'coeff': 0.1, 'is_hot': True, 'value': nan},
 {'id': 2, 'coeff': 0.2, 'is_hot': False, 'value': 2},
 {'id': 3, 'coeff': 0.30000000000000004, 'is_hot': False, 'value': 3},
 {'id': 4, 'coeff': 0.4, 'is_hot': False, 'value': nan}]
```

```python
pd.DataFrame(
    [[type(v) for k, v in row.items()] for row in dicts], 
    columns=dicts[0].keys())
```

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>id</th>
      <th>coeff</th>
      <th>is_hot</th>
      <th>value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>&lt;class 'int'&gt;</td>
      <td>&lt;class 'float'&gt;</td>
      <td>&lt;class 'bool'&gt;</td>
      <td>&lt;class 'numpy.int64'&gt;</td>
    </tr>
    <tr>
      <th>1</th>
      <td>&lt;class 'int'&gt;</td>
      <td>&lt;class 'float'&gt;</td>
      <td>&lt;class 'bool'&gt;</td>
      <td>&lt;class 'float'&gt;</td>
    </tr>
    <tr>
      <th>2</th>
      <td>&lt;class 'int'&gt;</td>
      <td>&lt;class 'float'&gt;</td>
      <td>&lt;class 'bool'&gt;</td>
      <td>&lt;class 'numpy.int64'&gt;</td>
    </tr>
    <tr>
      <th>3</th>
      <td>&lt;class 'int'&gt;</td>
      <td>&lt;class 'float'&gt;</td>
      <td>&lt;class 'bool'&gt;</td>
      <td>&lt;class 'numpy.int64'&gt;</td>
    </tr>
    <tr>
      <th>4</th>
      <td>&lt;class 'int'&gt;</td>
      <td>&lt;class 'float'&gt;</td>
      <td>&lt;class 'bool'&gt;</td>
      <td>&lt;class 'float'&gt;</td>
    </tr>
  </tbody>
</table>

#### Output of ``pd.show_versions()``

<details>

```
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.4.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8

pandas           : 1.0.4
numpy            : 1.18.4
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.15.0
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.2.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
```

</details>

**Comment by jorisvandenbossche** [comment]
@dm-logv thanks for the report. This is probably related to https://github.com/pandas-dev/pandas/issues/29738

**Comment by arw2019** [comment]
Minimal reproducer: 
``` python
In [3]: import pandas as pd 
   ...:  
   ...: df = pd.DataFrame({'A': [1, None, 2, 3, None]}) 
   ...: df['A'] = df['A'].astype('Int64') 
   ...: dicts = df.to_dict(orient="records") 
   ...: pd.DataFrame( 
   ...:     [[type(v) for k, v in row.items()] for row in dicts],  
   ...:     columns=dicts[0].keys())                                                                                                                                                                               
Out[3]: 
                                       A
0                  <class 'numpy.int64'>
1  <class 'pandas._libs.missing.NAType'>
2                  <class 'numpy.int64'>
3                  <class 'numpy.int64'>
4  <class 'pandas._libs.missing.NAType'>
```

**Comment by arw2019** [comment]
Even smaller:
``` python
In [2]: import pandas as pd 
   ...:  
   ...: df = pd.DataFrame({'A': [1, None]}) 
   ...: df['A'] = df['A'].astype('Int64') 
   ...: records_as_dicts = df.to_dict(orient="records") 
   ...: pd.DataFrame([[type(v) for v in row.values()] for row in records_as_dicts], columns=records_as_dicts[0].keys())                                                                                            
Out[2]: 
                                       A
0                  <class 'numpy.int64'>
1  <class 'pandas._libs.missing.NAType'>
```

**Comment by VikingPathak** [comment]
I am using `pd.read_sql()` which returned a dataframe and then applying `.to_dict()` gave me a dictionary with value `True` having type `numpy.bool_`.

Could not find a better approach so I used `to_json()` instead of `to_dict()` and enclosed it in `json.loads()`. **All the numpy types were converted to python object.**

```python
json.loads(dataframe.iloc[0, :].to_json())
```
