### ISSUE TITLE
BUG: read_excel: incorrect multi-index values - 3

### ISSUE THREAD

**Issue by kuraga** [pandas-dev/pandas#34676]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas as pd
df = pd.read_excel('test.xlsx', header=[0, 1], index_col=[0, 1])
print(df.index)
print(df.index)
```
(`engine` could be `xlrd` or `openpyxl`, doesn't matter.)

[test.xlsx](https://github.com/pandas-dev/pandas/files/4754140/test.xlsx)
![image](https://user-images.githubusercontent.com/1063219/84186440-368ab680-aa99-11ea-95b7-e0449c4bae2e.png)

#### Problem description

```
MultiIndex([(nan, nan),
            ('x', 'y')],
           names=['A', 'B'])
Index(['C', 'Unnamed: 3'], dtype='object')
```

#### Expected Output

I'm not sure exactly.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.42-calculate
machine          : x86_64
processor        : Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
byteorder        : little
LC_ALL           : None
LANG             : ru_RU.utf8
LOCALE           : ru_RU.UTF-8

pandas           : 1.0.3
numpy            : 1.18.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.4.0.post20200518
Cython           : 0.29.17
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.2.8
lxml.etree       : 4.5.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.13.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.1.3
numexpr          : None
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : 1.2.8
numba            : None
</details>

**Comment by TomAugspurger** [comment]
@kuraga can you include the code to generate the `test.xlsx` file? We'd need that for a unit test anyway.

What's the expected ouput?

**Comment by kuraga** [comment]
@TomAugspurger I made them in LibreOffice Writer.

**Comment by mroeschke** [comment]
Let us know if could provide the expected output for this issue, going to close in the meantime due to inactivity.

**Comment by kuraga** [comment]
@mroeschke , which output is correct on your mind for this file?

**Comment by mroeschke** [comment]
I am not sure either what the result should be for this file. It's an oddly formatted file

**Comment by kuraga** [comment]
BTW, the 3.0.5 output is:

```
MultiIndex([('x', 'y')],
           names=[None, None])
MultiIndex([('C', 'D'),
            ('C', 'E')],
           names=['B', None])
```

Do we have thoughts on `index.names` and `columns.names`?
