### ISSUE TITLE
BUG: DataFrame.to_feather() does not work

### ISSUE THREAD

**Issue by yannikschaelte** [pandas-dev/pandas#34670]
The function `DataFrame.to_feather()` creates a file that cannot be read in in R.

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas as pd
df = pd.DataFrame({'a': [42, 43]})
df.to_feather("out.feather")
```

#### Problem description

When exporting a dataframe as above to feather format and reading it in from R, I get
```R
> library(feather)
> read_feather("out.feather")
Error in openFeather(path) : Invalid: Not a feather file
```

This error seems to have been introduced recently, it used to work on older environments. R version: 3.6.3.

#### Expected Output

It should be read in correctly.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-33-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.4
numpy            : 1.18.5
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 47.1.1.post20200604
Cython           : 0.29.19
pytest           : 5.4.3
hypothesis       : None
sphinx           : None
blosc            : None
feather          : 0.4.1
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.15.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.2.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.17.1
pytables         : None
pytest           : 5.4.3
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.17
tables           : None
tabulate         : None
xarray           : 0.15.1
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
>>> 

</details>

**Comment by matteosantama** [comment]
Does the accompanying pandas `read_feather()` function work on your `out.feather` file?

**Comment by yannikschaelte** [comment]
yes it does
```python
>>> (df == pd.read_feather("out.f")).all()
a    True
dtype: bool
```

**Comment by TomAugspurger** [comment]
This is almost surely on the Arrow side (R or python), rather than pandas. I'd recommend ensuring that your verisons of Arrow are compatible.

**Comment by yannikschaelte** [comment]
@TomAugspurger Do you mean the pyarrow python package and arrow R package? Do you happen to know where compatibility can be checked?

**Comment by TomAugspurger** [comment]
Yes, pyarrow for the Python side. I'm not sure how the R side is packaged,
or what versions are compatible with the other. (cc @jorisvandenbossche).

**Comment by jorisvandenbossche** [comment]
@yannikschaelte you have the latest version of pyarrow installed (0.17.1), which will write Feather Version 2 files by default. Those files can only be read by the latest R arrow package (and I don't think the R `feather` package is already updated, but the R `arrow` package should include feather reading functionality that recognizes those files).

To write files that are readable by the older `feather` package, you can specify `df.to_feather("out.feather", version="1.0")`. The only problem is that you need pandas master to be able to pass through this keyword ..

**Comment by jorisvandenbossche** [comment]
See the note at https://github.com/wesm/feather#feather-development-is-in-apache-arrow-now (we should maybe clarify that to also include a note about the format version). 
And see https://arrow.apache.org/docs/r/reference/read_feather.html for the R `arrow` docs on this.

**Comment by yannikschaelte** [comment]
Thanks all for your fast replies! Using the latest versions of arrow resolved this problem.
