### ISSUE TITLE
ENH: Make metadata from read_spss available 

### ISSUE THREAD

**Issue by mario-bermonti** [pandas-dev/pandas#34682]
#### Is your feature request related to a problem?
I would like to have the [metadata that pyreadstats provides](https://ofajardo.github.io/pyreadstat_documentation/_build/html/index.html) available when reading files from SPSS. 

This would be really helpful because it would provide an easy way to have variable labels (descriptions), value labels, and other important metadata available to format results/reports (by replacing the variable names manually with `.replace` function). 

Those kinds of metadata are widely used in social sciences because it makes understanding results really easy. For example, SPSS changes the variable names to the variable labels in the output of analyses. Users could manually do this if the metadata was available.

#### Describe the solution you'd like
The metadata read by pyreadstats could be stored in the df's `_metadata` attribute and that would make it readily available

#### API breaking implications
I don't think there would be any implications if it's stored in the `_metadata` attribute because it was developed for this kind of use-case. I'm I right?

#### Describe alternatives you've considered
I could use the pyreadstats directly without using the `df.read_spss`. I can't think of any other options.

#### Additional context
This is related to issues [#11179](https://github.com/pandas-dev/pandas/issues/11179) and [#39](https://github.com/pandas-dev/pandas/issues/39).

**Comment by TomAugspurger** [comment]
> The metadata read by pyreadstats could be stored in the df's _metadata attribute and that would make it readily available

`NDFrame._metadata` is primarily for subclasses. We would want to use `.attrs` instead.

**Comment by mario-bermonti** [comment]
So in theory this shouldn’t cause too much trouble? I’m going to give it a try and get back with the results

**Comment by TomAugspurger** [comment]
Yeah, won't cause any trouble. There will be some operations that fail to propagate the metadata, and we still need to determine how metadata propagates when multiple dataframes (possibly with different metadata) are involved. But won't cause any issues.

Thanks for working on this.

**Comment by mario-bermonti** [comment]
Hi. I’m so sorry for this late reply. I haven’t been able to work on this because this last year has been very hard. I hope to work on it sometime in the near future. So I will keep in touch.

**Comment by jbrockmendel** [comment]
Closed by #55472?
