### ISSUE TITLE
BUG: CI builds failing at compilation of _sas

### ISSUE THREAD

**Issue by martindurant** [pandas-dev/pandas#34704]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

See, for example, the build line https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=37068&view=logs&j=a3a13ea8-7cf0-5bdb-71bb-6ac8830ae35c&t=2296ffae-5e67-52bf-66a8-6160145a0f80&l=660 
(and this appears to be failing other PRs too)

#### Problem description

CI builds are failing, see link above

**Comment by TomAugspurger** [comment]
Maybe related to the Cython version? Locally, with Cython 29.20 I see

```
pandas/_libs/interval.c:8301:18: error: unused function '__pyx_pw_6pandas_5_libs_8interval_8Interval_25__div__' [-Werror,-Wunused-function]
static PyObject *__pyx_pw_6pandas_5_libs_8interval_8Interval_25__div__(PyObject *__pyx_v_self, PyObject *__pyx_v_y) {
                 ^
1 error generated.
```

With 29.19, I don't see that error. Let me try pining cython for that build.

**Comment by TomAugspurger** [comment]
CI should be passing again if people merge master in their PRs.

We'll leave this issue open to determine why this is generating unused functions with Cython 0.29.20.

**Comment by WillAyd** [comment]
Woud have to check Cython changelog but I guess would also just remove the `__div__` method - isn't that a Py2 compat leftover?
