### ISSUE TITLE
ENH: implement pd.Series.corr(method="polychoric")

### ISSUE THREAD

**Issue by dev-pawel** [pandas-dev/pandas#34706]
I wish I could use pandas to calculate the polychoric correlation for ordinal variables. According to the literature, the polychronic correlation presents really good results. Compare to Spearman correlation it performs better on n > 1000 number of samples. 

I couldn't find an easy way to use it in python.
In R there are at least two implementations of this correlation e.g.
https://r-forge.r-project.org/projects/polycor/

**Comment by dsaxton** [comment]
I think scipy would probably be the place for this to be implemented. In any case if there is a formula for this that could be coded by hand you could pass that as a callable to the method argument to get this behavior using existing functionality.

**Comment by mroeschke** [comment]
Agreed it's better that this is implemented in scipy so pandas can dispatch to its implementation.

Thanks for the suggestion, but we recommend upstreaming this feature request to scipy. Closing
