### ISSUE TITLE
QST:Need to stop converting my regular values to date formats

### ISSUE THREAD

**Issue by amansani** [pandas-dev/pandas#34723]
- [ ] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
# Your code here, if applicable

I have values in my tables as 5-7, 3-5, 5-6, these values are converting into date formats like 07-May, 05-Mar, 06-May. But those values are related to length, width and height, so i want to leave the values the way it is and to convert into date format only to date values. This is happening only when saving the data in 'to_csv' method and working properly in 'to_excel' method.

Also hyphen(—) values in csv are converted to â€” and working properly in excel.

Any help in any of the issues are much appreciated.

Thanks.
```

**Comment by amansani** [comment]
The Hyphen issue got solved. Added encoding='utf-8-sig' in to_csv method.

Need help in fixing the values to date formats.

**Comment by mroeschke** [comment]
Could you provide a minimal example of the conversion behavior you're seeing? https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by amansani** [comment]
Sure, here is the code snippet and the input and output files. I couldn't able to upload the output file, so added image instead. The length, width and height are converted to dates, which i don't want to do. The output in the excel files are good, this problem exists only in csv files. Please let me know if you need any more information. Thank you.

tables = camelot.read_pdf(pdfFile, pages ="1-end", flavor=flavorType, multiple_table = True)            
tableData = tables[0]                   
tableData.to_csv("inputPdfFileGoesHere", index = False, encoding='utf-8-sig')

[InputPage.pdf](https://github.com/pandas-dev/pandas/files/4771080/InputPage.pdf)


![image](https://user-images.githubusercontent.com/31453971/84508828-e5451780-ac90-11ea-93ec-5cfa6739f590.png)

**Comment by TomAugspurger** [comment]
@amansani see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reportsfor writing bug reports. For excel IO you should explicitly distinguish between what pandas is doing and what the underyling engine (e.g. xlrd) is doing.

**Comment by amansani** [comment]
Hello Tom, the excel format is .xlsx.  I am just exporting the table from given input page to csv using Camelot and pandad df. Seems like the problem is not with pandas, because I can able to see the right values when I open csv using text editor and the values are in date formats when I open the csv file using excel (Microsoft Excel Comma Separated Values File (.csv)).

I am looking for some option from pandas if there is anything to stop converting the values into date format when opening the csv file using excel comma separated values. 

Any help is really appreciated. Thank you.

**Comment by TomAugspurger** [comment]
We unfortunately have too many open issues to be able to help in detail. You might try asking on stackoverflow with the pandas tag.

**Comment by amansani** [comment]
No problem @TomAugspurger . I am going to close this issue, as this problem is not with either pandas or Camelot. It's the problem opening the csv file using microsoft excel. However, I really appreciate if pandas can come up with some kind of option/parameter to fix this. Thanks to everyone though :)
