### ISSUE TITLE
CI: window 37_141 jobs needs to update numpy version

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#34724]
https://github.com/pandas-dev/pandas/blob/master/ci/deps/azure-windows-37.yaml

we no longer support this, I guess it *still* works ok. But we should advance this job to be numpy 1.15* at least, i would say we should actually test numpy 1.18* here.

might also need to actually rename the job to reflect the update.

**Comment by Akshatt** [comment]
Hey @jreback, Can I work on this issue?

**Comment by ObliviousParadigm** [comment]
Hey @jreback, can I work on this issue?

**Comment by Bharat123rox** [comment]
take
