### ISSUE TITLE
TST: split up tests/plotting/test_frame.py into subdir & modules

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#34769]
we should split up this test file into a separate subdir and multiple test modules for better groking. first PR should be a straight move, then can split (or all in one is ok)

**Comment by nthiagar** [comment]
Hello @jreback,
I am a new contributor and I would like to tackle this as my first issue. I have familiarized myself with Python and Github. Would you be willing to guide me through the process?
Thank you

**Comment by iahsanujunda** [comment]
I would also like to help if needed

**Comment by iahsanujunda** [comment]
take

**Comment by iahsanujunda** [comment]
@jreback I have created PR for putting `tests/plotting/test_frame.py` into `tests/plotting/frame/test_frame.py` first. How should we proceed on splitting this into sub-modules?

**Comment by rajalakshmi139** [comment]
Hi,
I am new to open source and would like to help. I have decent experience with Python and Github.

**Comment by Mikhaylov-yv** [comment]
take
