### ISSUE TITLE
ENH: Support Multi-Index for columns in parquet format

### ISSUE THREAD

**Issue by yohplala** [pandas-dev/pandas#34777]
#### Is your feature request related to a problem?

I would like to save DataFrame with Multi-Index used for columns into parquet format.
This is currently not possible.

```python
import pandas as pd
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns= pd.MultiIndex.from_product([['1'],['a', 'b', 'c']]))
df.to_parquet('test.parquet')
""" doesn't work, whatever the engine """
ValueError: parquet must have string column names
```

#### Describe alternatives you've considered

To do so with actual state of library, a [piece of code has been shared on SO](https://stackoverflow.com/questions/54861430/how-do-i-save-multi-indexed-pandas-dataframes-to-parquet).
I will use it for now.

```python
import pyarrow as pa
import pyarrow.parquet as pq
table = pa.Table.from_pandas(df)
pq.write_table(table, 'test.parquet')
df_test_read = pd.read_parquet('test.parquet')
```

Thanks for your help!
Bests,

**Comment by rhshadrach** [comment]
Simply removing the code

````
# must have value column names (strings only)
if df.columns.inferred_type not in {"string", "empty"}:
    raise ValueError("parquet must have string column names")
````

this example then works, although I'm not sure what the limitations are. I've tested a couple of examples, such as `columns=[1, 2, 3]` and things seem to generally work. Even weird things like `columns=[(1, 2), 3, 4]` "work", although this is converted to `['('1', '2')', '3', '4']` when reading back in (with a warning message).

**Comment by TomAugspurger** [comment]
The check needs to be updated to handle MultiIndexes. Something like

```python
if df.index.nlevels > 1:
    if not all(x.inferred_type in {"string", "empty"} for x in df.index.levels):
        raise ValueError(...)
```

**Comment by hweecat** [comment]
Hello! I could make an attempt on updating the check to handle MultiIndexes for parquet format, if that's okay. :)

**Comment by TomAugspurger** [comment]
That'd be great, thanks.

**Comment by hweecat** [comment]
Take :)
