### ISSUE TITLE
CI: move 3.6,slow or 3.6 locale builds from travis to azure

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#34776]
we have capacity on azure (we are using 8/10) and slightly overloaded on travis.

**Comment by hardikpnsp** [comment]
I would like to contribute but I am new to CI. From what I have read about CI and explored in the codebase it seems to me like all I have to do is remove a job ("3.6, slow") from .travis.yml and add it to posix.yml and windows.yml but I would appreciate guidance.

**Comment by tomaszps** [comment]
Hey @hardikpnsp, are you still looking at this issue? I'm also not too familiar (with Azure at least), but if I were going to do this I figured I'd try to get the change working on CI on my own fork, and then ask to make sure that the changes looked correct. Do you still want to have this issue?
