### ISSUE TITLE
CI: gbq tests failing

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#34779]
https://travis-ci.org/github/pandas-dev/pandas/builds/698328374
and specificallly these 2 builds: https://travis-ci.org/github/pandas-dev/pandas/jobs/698328378

cc @alimcmaster1 @tswast 

if you have any insights

**Comment by tswast** [comment]
`Invalid grant: account not found` looks to me like the error that happens when a service account has been deleted. I recall that this repo is using a different project for CI tests than we're using for pandas-gbq, so I'm not sure how to investigate further.

**Comment by alimcmaster1** [comment]
@twast our project id is "pandas-travis" - is there any info that would help further?

 @jreback - who on the pandas side has access to the GCP console? "https://console.cloud.google.com/iam-admin/serviceaccounts?project=pandas-travis" -> should help confirm if it is our service account that's gone missing

**Comment by jreback** [comment]
hmm i don't have access here either. So let's in the meantime just disable these tests on master. We can also setup a new GCP account for this and re-enable at some point.

**Comment by alimcmaster1** [comment]
Sure @jreback ill do this this eve! @tswast maybe we could use the same setup as pandas-gbq ?

**Comment by alimcmaster1** [comment]
@tswast - friendly ping on the above.

**Comment by tswast** [comment]
I created a service account key in the `pandas-gbq-tests` project, but when I try to encrypt it with `ci/travis_encrypt_gbq.sh`, I get `resource not found ({"error":"Couldn't find repository"})` from the `travis encrypt-file` command.

I believe this is because I'm not a member of the pandas-dev GitHub org, so don't have permissions to create new environment variables in Travis.

**Comment by jreback** [comment]
@tswast added you to your triage team. give a try again (after you accept the invite)

**Comment by jreback** [comment]
@tswast I sent an invite to make you a member of the core team :-> you should have be able to create these keys now.

**Comment by tswast** [comment]
I was able to create the keys in Travis and got a running build at https://travis-ci.org/github/pandas-dev/pandas/builds/705824144 with the same code as #35090
