### ISSUE TITLE
CI: test failure, raises unexpected warning

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#34792]
I merged master into #33247 . This results in a failing test:
`pandas/tests/plotting/test_converter.py::TestRegistration::test_pandas_plots_register`

in Windows py37_np_18

```
 AssertionError: Caused unexpected warning(s): [('DeprecationWarning', DeprecationWarning("Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working")
```

Was this already detected?

[test results](https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=37342&view=logs&j=ea1e4a48-f1c1-5933-c4f7-7e56de389fce&t=967459d8-2b8b-5603-ef1c-c585363eb056&l=92)

**Comment by TomAugspurger** [comment]
Will need a similar fix as https://github.com/pandas-dev/pandas/pull/34721/files#diff-fb957a9fbb8d57904092e2bbe06b1b2bR99-R109.

**Comment by jbrockmendel** [comment]
Has this been fixed?

**Comment by mroeschke** [comment]
Looks like we're not testing py37_np_18 anymore, and an analgous py37_np_18 build doesn't seem to have this warning anymore so I think we can close. Can open a new issue if this reappears.

https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=64034&view=logs&jobId=404760ec-14d3-5d48-e580-13034792878f&j=404760ec-14d3-5d48-e580-13034792878f&t=f81e4cc8-d61a-5fb8-36be-36768e5c561a
