### ISSUE TITLE
DOC: to_sql accepting Engine vs. Connectable

### ISSUE THREAD

**Issue by gordthompson** [pandas-dev/pandas#34824]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_sql.html

#### Documentation problem

[Documentation](https://github.com/pandas-dev/pandas/blob/1ce1c3c1ef9894bf1ba79805f37514291f52a9da/pandas/core/generic.py#L2530) says that `con` is to be a "sqlalchemy.engine.Engine or ..." while [source](https://github.com/pandas-dev/pandas/blob/f34fd588cd9facfa82a792fb570fb8a56f11f6c7/pandas/io/sql.py#L539) says that `con` can be a "SQLAlchemy connectable(engine/connection) or ..."

#### Suggested fix for documentation

Documentation should mention that a SQLAlchemy `Connection` is acceptable because some operations like [an upsert via a temporary table in SQL Server](https://stackoverflow.com/q/62388767/2144390) need to ensure that the same DBAPI connection is used for the entire operation. (SQL Server local temp tables are only visible to the connection/session that created them).

**Comment by arw2019** [comment]
take

**Comment by arw2019** [comment]
@gordthompson Would love your thoughts on the rewritten docstring in PR #34944
