### ISSUE TITLE
ENH: Use of NamedTuple instead of Tuple for MultiIndex

### ISSUE THREAD

**Issue by yohplala** [pandas-dev/pandas#34840]
#### Is your feature request related to a problem?

Simply from an ergonomic point of view, when using MultiIndex, it would be worth using a list of NamedTuple instead of Tuple, so that level name can be directly used to call index values.

#### Describe the solution you'd like

Currently,

```python
import pandas as pd
midx = pd.MultiIndex.from_product([['value1','value2'],[1]], names=['level1','level2'])
df = pd.DataFrame(0,index=[1,2],columns=midx)
df.columns[0]['level1']
```
returns:
```python
TypeError: tuple indices must be integers or slices, not str
```

Would this be a NamedTuple, this would return the correct result: 'value1'
Bests,

PS: and thanks for your awesome work!

**Comment by jreback** [comment]
see https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.get_level_values.html?highlight=get_level_values#pandas.MultiIndex.get_level_values

**Comment by yohplala** [comment]
Hi Jeff, yes I know this command.
It is just when looping over columns

````python
for col in df.columns:
     col['level1']
```

becomes possible by use of NamedTuple.
Well, that was only an idea.
Bests,

**Comment by rhshadrach** [comment]
How could this work when columns is an Index instead of a MultiIndex?

**Comment by yohplala** [comment]
Hello @rhshadrach,

Hmmm, does this need to work actually? 
With simple index, df.columns[0] does not return a tuple but directly the column identifier as an object of its own type.
I propose to keep the same behavior as now.

```python
import pandas as pd
midx = pd.MultiIndex.from_product([['value1','value2'],[1]], names=['level1','level2'])
df = pd.DataFrame(0,index=[1,2],columns=midx)
type(df.columns[0])
```
```python
tuple
```
Whereas
```python
dti = pd.DataFrame(0,index=[1,2],columns=['bla'])
type(dti.columns[0])
```
```python
str
```

The proposal here is to change the type of returned object from Tuple to NamedTuple, using name of the level.
But I definitely understand this is only sugar.

Bests,

**Comment by suvayu** [comment]
@yohplala `namedtuple` doesn't allows you to pass the field name to `__getitem__`.  Having pandas return a `namedtuple` still does not make your example work

    df.columns[0]['level1']  # will fail with TypeError
    df.columns[0].level1     # this will work, but probably not what you want

**Comment by yohplala** [comment]
Ok, if this is inconsistent, I close the ticket. Thanks for the time you took to answer. Have a good day, bests,
