### ISSUE TITLE
DOC: Page Invalid 404 Pandas 1.0.5 full whatsnew 

### ISSUE THREAD

**Issue by JiaxiangBU** [pandas-dev/pandas#34855]
#### Location of the documentation

[this should provide the location of the documentation, e.g. "pandas.read_csv" or the URL of the documentation, e.g. "https://dev.pandas.io/docs/reference/api/pandas.read_csv.html"]

Here is the page location https://github.com/pandas-dev/pandas/releases/tag/v1.0.5

```
404 Not Found
nginx/1.10.3 (Ubuntu)
```

**Note**: You can check the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/).

#### Documentation problem

[this should provide a description of what documentation you believe needs to be fixed/improved]

#### Suggested fix for documentation

[this should explain the suggested fix and **why** it's better than the existing documentation]

**Comment by jorisvandenbossche** [comment]
The documentation for 1.0.5 is not yet uploaded. The link will be working shortly (when the release is officially announced; the github release always happens a bit earlier, since it is required for other release tasks)

**Comment by simonjayhawkins** [comment]
> The documentation for 1.0.5 is not yet uploaded. The link will be working shortly (when the release is officially announced; the github release always happens a bit earlier, since it is required for other release tasks)

The docs are now uploaded to https://pandas.pydata.org/pandas-docs/version/1.0.5/

@jorisvandenbossche I could change the link in the edit the github release link temporarily and change back once the stable docs point there. wdyt?

( I now have access to the web server so can do this b4 the github release next time)

I do not have access to PyPI so IIUC we don't switch the docs to stable till the wheels are upload?

**Comment by jorisvandenbossche** [comment]
>  I could change the link in the edit the github release link temporarily and change back once the stable docs point there. 

That's fine for me, but I also woudn't bother too much about it

**Comment by jorisvandenbossche** [comment]
Actually, in older releases we sometimes always used that /version/x.x.x/ link, so it's also fine to change it and leave it like that, I think

**Comment by simonjayhawkins** [comment]
done. issue unpinned.

**Comment by JiaxiangBU** [comment]
Thanks, it is valid for me now.
