### ISSUE TITLE
startswith function gives misleading results when passed a series

### ISSUE THREAD

**Issue by darindillon** [pandas-dev/pandas#3485]
Using pandas 0.10.1. I think this is probably "working correctly as designed", but the design seems non-obvious and there's not much documentation on this. 
    The Series object has a vectorized .str.startswith() method which works when you give it a constant string. But if you give it a series instead of a string, it "works" (in the sense of returning data) but that data is not what you'd expect. It appears the function was simply not designed to handle being passed a series, which is OK, but passing a series seems like a logicial thing to do, so can we at least make the function return an error rather than misleading data, so people don't get confused? I had to spent a half hour debugging to figure out why this wasn't working as I expected.
# I want to select the rows where column 'two' starts with the string in column 'one'

d = pandas.DataFrame([['hi,hi 2'],['bye','bye 2']], columns=['one','two'])
d.two.str.startswith(d.one) #Returns false for everything, but you'd expect it to be true

The startswith function doesn't handle Series. Ideally, we should change it so it does handle series. But if that's too much work, can we at least have it return "series is not supported, pass a constant string instead" error?

**Comment by christopherkang** [comment]
Could we close the issue and re-open if necessary?

**Comment by christopherkang** [comment]
Cool, that makes more sense. Yeah, it's a lower priority issue, but I agree that it's still important that it's eventually fixed.
(Also, I'm new to open source contribution, so I really appreciate your explanation! 😄 )

**Comment by kokes** [comment]
Just tested it and it no longer returns False, it gives you NaN instead. I suppose that OP suggested that either this works or there is a TypeError triggered?

```
In [1]: import pandas as pd

In [2]: df = pd.DataFrame({'a': ['foo', 'bar'], 'b': ['foox', 'xxx']})

In [3]: df.b.str.startswith(df.a)
Out[3]: 
0   NaN
1   NaN
Name: b, dtype: float64```

**Comment by kokes** [comment]
I suppose something like this would work? I'm not sure about conventions regarding string type testing (`compat.string_types` or `is_string_like`?) and perhaps the tests are written in a non-standard way.

```
diff --git a/pandas/core/strings.py b/pandas/core/strings.py
index 861739f6c..f85bd62a0 100644
--- a/pandas/core/strings.py
+++ b/pandas/core/strings.py
@@ -458,6 +458,8 @@ def str_startswith(arr, pat, na=np.nan):
     3    False
     dtype: bool
     """
+    if not isinstance(pat, compat.string_types):
+        raise TypeError("pattern supplied in str.startswith has to be a string")
     f = lambda x: x.startswith(pat)
     return _na_map(f, arr, na, dtype=bool)
 
@@ -513,6 +515,8 @@ def str_endswith(arr, pat, na=np.nan):
     3    False
     dtype: bool
     """
+    if not isinstance(pat, compat.string_types):
+        raise TypeError("pattern supplied in str.endswith has to be a string")
     f = lambda x: x.endswith(pat)
     return _na_map(f, arr, na, dtype=bool)
 
diff --git a/pandas/tests/test_strings.py b/pandas/tests/test_strings.py
index bd450cdcf..5ce9bbbfd 100644
--- a/pandas/tests/test_strings.py
+++ b/pandas/tests/test_strings.py
@@ -609,6 +609,13 @@ class TestStringMethods(object):
         result = values.str.endswith('foo', na=False)
         tm.assert_series_equal(result, exp.fillna(False).astype(bool))
 
+    def test_startswith_endswith_non_str_patterns(self):
+        values = Series(['foo', 'bar'])
+        invalid_patterns = [0, True, values]
+        for pattern in invalid_patterns:
+            pytest.raises(TypeError, values.str.startswith, pattern)
+            pytest.raises(TypeError, values.str.endswith, pattern)
+
     def test_title(self):
         values = Series(["FOO", "BAR", NA, "Blah", "blurg"])
 
```

**Comment by NumberPiOso** [comment]
I think @kokes was on track to do a successful PR to close this issue. I will use his code to do it.

**Comment by NumberPiOso** [comment]
take
