### ISSUE TITLE
QST: Events generated when dataframes are changed

### ISSUE THREAD

**Issue by sgt101** [pandas-dev/pandas#34854]
- [x ] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [x ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

here is a link to this question (similar) 
https://stackoverflow.com/questions/48209811/how-to-notify-pandas-dataframe-modification

---

#### Question about pandas

What events are generated when a dataframe is updated in pandas? for example if a column is dropped or a value is changed in a cell? I am not interested in accesses, but I'd like to know if a dataframe in my environment goes away or if it is altered.

**Comment by rhshadrach** [comment]
[Copying possible solution from SO]

Could you poll the dataframe?

    _old_df = None
    def poll_func(df):
        if df is not None and (_old_df is None or not df.equals(_old_df)):
            _old_df = df.copy()
            update_other_components()

and then poll this function every X seconds?

**Comment by TomAugspurger** [comment]
No events, and supporting something like this is probably out of scope for pandas.

**Comment by sgt101** [comment]
Thank you - that's what I thought, but I didn't want to go ahead and do something different without double checking. I am very grateful for the response.

**Comment by sgt101** [comment]
@rhshadrach  thanks for the response. I think that the df.equals could be problematic for large dataframes! I'll investigate though.

**Comment by sgt101** [comment]
@rhshadrach  thanks for the response. I think that the df.equals could be problematic for large dataframes! I'll investigate though.
