### ISSUE TITLE
DOC: pandas/pandas/core/window/ewm.py

### ISSUE THREAD

**Issue by db-baron** [pandas-dev/pandas#34867]
#### Location of the documentation
Docstring for `class EWM(_Rolling)` in ewm.py.

#### Documentation problem
The purposes of the `EWM` class is unclear because there's no documentation on what 'ewm' is abbreviating. One reason this is confusing is that `ewm` can easily be interpreted as either "exponentially weighted mean" or "exponentially weighted moving". The `EWM` class docstring actually muddies the water further by stating that the class provides "exponential weighted **(EW)** functions".

#### Suggested fix for documentation
If it's absolutely necessary to use an abbreviation like `ewm` then the docstring needs to clearly state what it's abbreviating.

**Comment by MarcoGorelli** [comment]
Thanks @db-baron for the report - are you interested in [submitting a pull request](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html)?

**Comment by KrishnaSai2020** [comment]
take

**Comment by jreback** [comment]
closing in favor of #34910

**Comment by charlesdong1991** [comment]
ehh? this is the issue, not PR? @jreback

**Comment by MarcoGorelli** [comment]
Reopening as I'm pretty sure Jeff meant to close #34901 instead :)
