### ISSUE TITLE
BUG: read_parquet doesn't accept anymore a file route starting with 'file://'

### ISSUE THREAD

**Issue by jorloplaz** [pandas-dev/pandas#34861]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

```python
# Your code here
import pandas as pd
pd.read_parquet('file://<route_to_parquet_file>')
```

#### Problem description

When passed a path with the file protocol (e.g., `file:///home/Desktop/my_parquet.pq`) it throws the following error:

OSError: Passed non-file path: file:///home/Desktop/my_parquet.pq

#### Expected Output

Should read things fine. 

With Pandas 1.0.3 it does work perfectly, so there's something wrong when moving from 1.0.3 to 1.0.4.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-101-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : es_ES.UTF-8
LOCALE           : es_ES.UTF-8

pandas           : 1.0.4
numpy            : 1.18.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 47.3.0.post20200616
Cython           : 0.29.20
pytest           : 5.4.2
hypothesis       : None
sphinx           : None
blosc            : 1.7.0
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.13.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : 0.3.2
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : 2.7.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.15.1
pytables         : None
pytest           : 5.4.2
pyxlsb           : None
s3fs             : 0.4.2
scipy            : 1.4.1
sqlalchemy       : None
tables           : 3.6.1
tabulate         : None
xarray           : 0.15.1
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
numba            : 0.49.1

</details>

**Comment by jreback** [comment]
try on 1.0.5 which was just released to patch this

**Comment by jorloplaz** [comment]
It does indeed work. Sorry I didn't see issue [#GH34467](https://github.com/pandas-dev/pandas/issues/34467) as it was already closed. 

Didn't even know there was already a 1.0.5 release, just got an e-mail announcing 1.0.4. You're too fast, guys! Keep on with the good work!
