### ISSUE TITLE
Series and Index have inconsistent repr

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#34864]
Series and Index format differently when printed to the console (e.g., `dtype: object` vs. `dtype='object'`), but likely they should look the same (Index seems better IMO since it matches the constructor and agrees with numpy).

```python
In [11]: pd.Series([], dtype=object, name="abc")                                                                                                                                                             
Out[11]: Series([], Name: abc, dtype: object)

In [12]: pd.Index([], dtype=object, name="abc")                                                                                                                                                              
Out[12]: Index([], dtype='object', name='abc')
```

**Comment by jorisvandenbossche** [comment]
Note this is only for empty Series. It seems that for Series, it reuses the "Name:.., dtype: .. " part of the repr of a non-empty series.

**Comment by dsaxton** [comment]
> Note this is only for empty Series. It seems that for Series, it reuses the "Name:.., dtype: .. " part of the repr of a non-empty series.

You're right, can close this if it's too much on the nitty side

**Comment by jorisvandenbossche** [comment]
Yeah, I would personally not bother about it, but if someone wants to fix it and it doesn't give much complication, I suppose that would still be welcome (but maybe not worth cluttering the issue list with it)
