### ISSUE TITLE
CI/COMPAT: PyUnicode_FromUnicode is deprecated failure on 3.9 CI

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#34881]
The 3.9-dev build started failing (eg https://travis-ci.org/github/pandas-dev/pandas/jobs/700233890):

```
    pandas/_libs/parsers.c: In function ‘__Pyx_decode_c_string’:
    pandas/_libs/parsers.c:56645:9: error: ‘PyUnicode_FromUnicode’ is deprecated [-Werror=deprecated-declarations]
             return PyUnicode_FromUnicode(NULL, 0);
             ^~~~~~
    In file included from /opt/python/3.9-dev/include/python3.9/unicodeobject.h:1026:0,
                     from /opt/python/3.9-dev/include/python3.9/Python.h:97,
                     from pandas/_libs/parsers.c:57:
    /opt/python/3.9-dev/include/python3.9/cpython/unicodeobject.h:551:42: note: declared here
     Py_DEPRECATED(3.3) PyAPI_FUNC(PyObject*) PyUnicode_FromUnicode(
                                              ^~~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors
```

See https://docs.python.org/3.9/c-api/unicode.html#c.PyUnicode_FromUnicode

**Comment by jorisvandenbossche** [comment]
It doesn't seem we are using this method directly ourselves. Might be coming from cython: https://github.com/cython/cython/issues/3678

**Comment by alimcmaster1** [comment]
I also get this on 3.8 locally when building C extentions. (Also see the same on a few [jobs](https://travis-ci.org/github/pandas-dev/pandas/jobs/700310700))
```
ImportError while loading conftest '/home/travis/build/pandas-dev/pandas/pandas/conftest.py'.
pandas/__init__.py:34: in <module>
    raise ImportError(
E   ImportError: C extension: 'dtypes' from partially initialized module 'pandas._libs.tslibs' (most likely due to a circular import) (/home/travis/build/pandas-dev/pandas/pandas/_libs/tslibs/__init__.py) not built.
```

**Comment by jreback** [comment]
moving the 3.9 build for now to allowed failures in https://github.com/pandas-dev/pandas/pull/34894 (actually was in there but incorrectly so didn't work)

**Comment by TomAugspurger** [comment]
> It doesn't seem we are using this method directly ourselves. Might be coming from cython: cython/cython#3678

It looks like we're using it at https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/parsers.pyx#L28-L29.

**Comment by simonjayhawkins** [comment]
moved off 1.1.1 milestone (scheduled for this week) as no PRs to fix in the pipeline

**Comment by simonjayhawkins** [comment]
removing milestone

**Comment by jbrockmendel** [comment]
How do we check if this is resolved?

**Comment by mroeschke** [comment]
Hmm appears that we aren't seeing this on our 3.9 builds in Github Actions anymore. I'm assuming this has been resolved so closing, but we can reopen if this reappears.
