### ISSUE TITLE
CI/TST: html tests are failing with 404 for fdic.gov url

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#34893]
See eg https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=37674&view=logs&jobId=a67b4c4c-cd2e-5e3c-a361-de73ac9c05f9&j=a67b4c4c-cd2e-5e3c-a361-de73ac9c05f9&t=33d2fdd0-c376-5f94-e6d3-957bdd23a3b8

**Comment by jreback** [comment]
looks ok now
