### ISSUE TITLE
DOC: Contributor guideline should guide contributors for expected local mypy failures

### ISSUE THREAD

**Issue by oguzhanogreden** [pandas-dev/pandas#34902]
#### Location of the documentation

[Location](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#style-guidelines).

#### Documentation problem

See conversation [here](https://gitter.im/pydata/pandas?at=5eee0e2ba813c72dcffccbb5).

#### Suggested fix for documentation

This 'failing' of mypy should be noted so that inexperienced contributors don't have to Google around and experienced ones don't have to explain repeatedly.

I came across this in [this context](https://github.com/pandas-dev/pandas/pull/32542#discussion_r442959117).

**Comment by oguzhanogreden** [comment]
`SKIP=mypy` may be the 'clean' suggestion, [thanks](https://gitter.im/pydata/pandas?at=5eee2234a813c72dcffcfa1a) @MarcoGorelli.

**Comment by MarcoGorelli** [comment]
Thanks @oguzhanogreden , might be good to add a line mentioning this to the "pre-commit" section of the contributing guide https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#pre-commit

**Comment by erfannariman** [comment]
take

**Comment by erfannariman** [comment]
Need some input for this, based on the discussion in gitter (see link in message by OP), we should use 

```
SKIP=mypy git commit -m "<some message which I know should be descriptive but usually isn't>"
```
But this does not work for me, I had to use 

```
git commit --no-verify -m "<some message>"
```
Which one are we going for and should I add to the docs?

**Comment by WillAyd** [comment]
Why not just remove mypy from the pre-commit check? I think this has been an ongoing issue with the interaction of those tools @TomAugspurger I think brought up originally

**Comment by erfannariman** [comment]
If it (mypy check) is not needed, @WillAyd 's suggestions makes more sense to me.

**Comment by WillAyd** [comment]
Another option would be to only run mypy before a push instead of on every commit. This might be achievable with specifying the stage in the config

https://pre-commit.com/

**Comment by MarcoGorelli** [comment]
> Another option would be to only run mypy before a push instead of on every commit. This might be achievable with specifying the stage in the config
> 
> https://pre-commit.com/

Not sure that work would - see below

```bash
(pandas-dev) marco@marco-Predator-PH315-52:~/pandas-dev$ git fetch upstream master
From https://github.com/pandas-dev/pandas
 * branch                master     -> FETCH_HEAD
(pandas-dev) marco@marco-Predator-PH315-52:~/pandas-dev$ git reset --hard upstream/master
HEAD is now at 0159cba6e CLN: dont consolidate in indexing (#34679)
(pandas-dev) marco@marco-Predator-PH315-52:~/pandas-dev$ pre-commit run --all
black....................................................................Passed
flake8...................................................................Passed
flake8-pyx...............................................................Passed
flake8-pxd...............................................................Passed
isort....................................................................Failed
- hook id: isort
- files were modified by this hook

Fixing /home/marco/pandas-dev/web/pandas_web.py

mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

pandas/core/dtypes/generic.py:10: error: unused 'type: ignore' comment
pandas/core/resample.py:970: error: unused 'type: ignore' comment
Found 2 errors in 2 files (checked 1043 source files)

(pandas-dev) marco@marco-Predator-PH315-52:~/pandas-dev$ mypy pandas
Success: no issues found in 1024 source files
```

IMHO it could be removed from `pre-commit` - if you're adding type annotations you'll need to run `mypy pandas` anyway, and if you're not then its false positives are a distraction (especially for new contributors)

**Comment by TomAugspurger** [comment]
I'm fine with removing mypy from pre-commit.
