### ISSUE TITLE
REF/INT: never set `df._mgr` after `__init__`, never hold a Block in more than 1 BlockManager

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#34961]
ATM there are a few places where we will do `self._mgr = mgr.reindex_or_whatever(...)`.  I think the code would be easier to reason about if we avoided this pattern.  To do that, we will need the relevant `mgr.reindex_or_whatever` methods to be in-place at the `BlockManager` level.

Similarly I don't think we have strictly-enforced policies describing the relationship between Block objects and BlockManagers.

Potential tightening of rules we could implement:
1) A DataFrame will only ever have a single BlockManager attached to it.
2) A BlockManager will only ever be attached to a single DataFrame.
3) A Block will only ever be attached to a single BlockManager

Thoughts?  Others I'm missing?

**Comment by jorisvandenbossche** [comment]
For the first item, can you explain why you find an inplace `reindex_..` on a BlockManager to be easier? I personally tend to think that "inplace" operations are harder to reason about, certainly if it can actually return a fully different (in constract to something like `fillna`). 
Doing `self._mgr = mgr.reindex_or_whatever(...)` at least makes it clear we are overwriting it with a new BlockManager (or is it the context where such a line is used?)

> A DataFrame will only ever have a single BlockManager attached to it.

Is it currently possible to attach multiple BlockManagers to a dataframe?

> A BlockManager will only ever be attached to a single DataFrame.
> A Block will only ever be attached to a single BlockManager

Currently, doing `df2 = pd.DataFrame(df)` creates two dataframes sharing a single BlockManager I think? So how would you do such no-copy conversions if the above holds true? Create a new BlockManager with new Blocks, but those blocks can still point to the same arrays?

**Comment by jbrockmendel** [comment]
> For the first item, can you explain why you find an inplace reindex_.. on a BlockManager to be easier? I personally tend to think that "inplace" operations are harder to reason about, certainly if it can actually return a fully different (in constract to something like fillna).

This is a tradeoff to be sure.

> Doing self._mgr = mgr.reindex_or_whatever(...) at least makes it clear we are overwriting it with a new BlockManager (or is it the context where such a line is used?)

The idea here is that we wouldn't be getting a new BlockManager, but would be altering the existing one.

>> A DataFrame will only ever have a single BlockManager attached to it.

> Is it currently possible to attach multiple BlockManagers to a dataframe?

Unclear wording on my part.  Rephrasing: `id(frame._mgr)` is constant over the lifetime of `frame`.

> Currently, doing df2 = pd.DataFrame(df) creates two dataframes sharing a single BlockManager I think? So how would you do such no-copy conversions if the above holds true? Create a new BlockManager with new Blocks, but those blocks can still point to the same arrays?

I would want to change this so that df2 gets its own BlockManager with its own blocks, yes.

**Comment by jorisvandenbossche** [comment]
Do you have specific benefits / advantages in mind that we would be getting from not sharing block managers / blocks? Or is it rather a general sense of "this is cleaner" ?

**Comment by jbrockmendel** [comment]
Just a cleaner abstraction.  Closing.

**Comment by jorisvandenbossche** [comment]
"just a cleaner abstraction" can still be a worthwile reason to do this, to be clear (I was just trying to understand your reasoning)
