### ISSUE TITLE
I had this error please tell me the solution

### ISSUE THREAD

**Issue by hamzajamil12** [pandas-dev/pandas#34964]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-71bf30a97169> in <module>
----> 1 df=pd.read("datasets_33180_43520_heart_csv.py")

~\miniconda3\lib\site-packages\pandas\__init__.py in __getattr__(name)
    261             return _SparseArray
    262 
--> 263         raise AttributeError(f"module 'pandas' has no attribute '{name}'")
    264 
    265 

AttributeError: module 'pandas' has no attribute 'read'

**Comment by charlesdong1991** [comment]
there is no `read` method in pandas, pls find suitable method to call:

https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html
