### ISSUE TITLE
BUG: fixtures are not to be called directly

### ISSUE THREAD

**Issue by pizzathief** [pandas-dev/pandas#34970]
- [ X] I have checked that this issue has not already been reported.

- [X ] I have confirmed this bug exists on the latest version of pandas.

- [X ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```bash
pytest-3 pandas

========================================================================== test session starts ==========================================================================
platform linux -- Python 3.8.2, pytest-4.6.9, py-1.8.1, pluggy-0.13.0
rootdir: ~/code/pandas, inifile: setup.cfg, testpaths: pandas
collected 27211 items / 3 errors / 4 skipped / 27204 selected                                                                                                           

================================================================================ ERRORS =================================================================================
________________________________________________________ ERROR collecting pandas/tests/groupby/test_whitelist.py ________________________________________________________
Fixture "df_letters" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.
_____________________________________________________ ERROR collecting pandas/tests/indexes/datetimes/test_tools.py _____________________________________________________
Fixture "epoch_1960" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.
________________________________________________________ ERROR collecting pandas/tests/series/test_analytics.py _________________________________________________________
Fixture "s_main_dtypes" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.
=========================================================================== warnings summary ============================================================================
pandas/tests/extension/json/array.py:27
  /home/jason/code/pandas/pandas/tests/extension/json/array.py:27: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    type = collections.Mapping

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================ 4 skipped, 1 warnings, 3 error in 9.47 seconds =============================================================


```

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]
>>> pandas.show_versions()

INSTALLED VERSIONS
------------------
commit: 5a84593d9d02f4c26be18c98bf6637bf0a6f876c
python: 3.8.2.final.0
python-bits: 64
OS: Linux
OS-release: 5.4.0-37-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_AU.UTF-8
LOCALE: en_AU.UTF-8

pandas: 0.24.0.dev0+193.g5a84593d9
pytest: None
pip: 20.0.2
setuptools: 44.0.0
Cython: None
numpy: 1.18.5
scipy: 1.4.1
pyarrow: None
xarray: None
IPython: 7.15.0
sphinx: None
patsy: None
dateutil: 2.8.1
pytz: 2020.1
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.2.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
>>> 

</details>

**Comment by pizzathief** [comment]
#34971

**Comment by MarcoGorelli** [comment]
Thanks @pizzathief for the report

> ```
> ERROR collecting pandas/tests/groupby/test_whitelist.py
> ```

This file doesn't exist on the `master` branch, can pull the most recent commits and try again?

**Comment by pizzathief** [comment]
fetched from upstream and ran tests again, I dunno what happened with the code I had, pytest runs through all tests now without stopping. False alarm, closing issue, sorry :-(
