### ISSUE TITLE
BUG: Cannot create third-party ExtensionArrays for datetime types

### ISSUE THREAD

**Issue by xhochy** [pandas-dev/pandas#34986]
- [x] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

Code Sample: https://github.com/pandas-dev/pandas/pull/34987

#### Problem description

With https://github.com/pandas-dev/pandas/pull/33400 type checks now fasttrack on the kind of the `dtype`. Thus for every `ExtensionDtype` that is of kind `M`, `is_datetime64tz_dtype` returns `True`.  This is then used in `get_block_type` which leads to the usage of `DatetimeTZBlock` for all of these arrays although this block only supports `DatetimeArray`.

https://github.com/pandas-dev/pandas/blob/4f7d8bba44aa45a81333cdefd7ec627370e7117b/pandas/core/internals/blocks.py#L2685-L2690

**Comment by mroeschke** [comment]
I ran into this in https://github.com/pandas-dev/pandas/pull/47515

Since https://github.com/pandas-dev/pandas/pull/34987, just added some unit tests, I think this behavior should still be fixed so reopening.

**Comment by jbrockmendel** [comment]
@mroeschke will this be fixed by your is_datetime64tz_dtype PR?

**Comment by mroeschke** [comment]
I did refactor my original `is_datetime64tz_dtype` PR https://github.com/pandas-dev/pandas/pull/48258 to only be a unit test since I think another one of your PRs fixed the original issue, but can open a separate PR to reintroduce the fix
