### ISSUE TITLE
ENH: add re.fullmatch

### ISSUE THREAD

**Issue by rchurt** [pandas-dev/pandas#34980]
#### Is your feature request related to a problem?

I want to find only strings that match my full regex expression, not just the first part of it.

For example, if I am searching for the string `'panda'`, and my series contains the strings `'panda'` and `'pandas'`, I only want it to return `'panda'`. Currently, using `str.match('panda')` returns both.

#### Describe the solution you'd like

Add support for `re.fullmatch` (https://docs.python.org/3.4/library/re.html#re.fullmatch) so that it can be called with `str.fullmatch`.

**Comment by dsaxton** [comment]
Can you use str.match along with ^ and $ anchors to achieve the same result? (Also simple equality works here, but of course only because we have a trivial regex.)

**Comment by rchurt** [comment]
Yup, that's what I ended up doing in my code, but I thought I'd post this here as a possibility to help those not so familiar with regex. I'll defer to you as to whether you think it's worth implementing or not.

**Comment by WillAyd** [comment]
This was done in #32806 scheduled for 1.1
