### ISSUE TITLE
ENH: pd.DataFrame.merge() customizable indicator names

### ISSUE THREAD

**Issue by ianzur** [pandas-dev/pandas#34992]
#### Is your feature request related to a problem?
When performing multiple merge operations I would love to specify a more informative name than ['left_only', 'right_only', 'both'] for column '_merge'.

#### Describe the solution you'd like
pd.DataFrame.merge() indicator param could accept a categorical index with a custom naming scheme. 
something like:

```
pandas.CategoricalIndex(
    categories=['my_custom_left_name', 'my_custom_right_name', 'custom_both'],
    name='custom_column_name',
)
```

#### API breaking implications
This should not break anything.

#### Describe alternatives you've considered
Use Series.cat.rename_categories() after merge to change indicator names.

**Comment by WillAyd** [comment]
I don't think `merge` needs this as an argument - you should be able to just call `replace` on the column

**Comment by TomAugspurger** [comment]
Agreed with Will's proposal.
