### ISSUE TITLE
BUG:to_numeric with leading zeros is not working consistently

### ISSUE THREAD

**Issue by abedhammoud** [pandas-dev/pandas#35009]
- [X ] I have checked that this issue has not already been reported.

- [X ] I have confirmed this bug exists on the latest version of pandas.

I using version: '1.0.5'

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python

s = pd.Series(['apple', '001', '002', -3])
pd.to_numeric(s, errors='ignore')

[out]:
0    apple
1      001
2      002
3       -3
dtype: object


but if I do the following: 
s2 = pd.Series([1, 1.0, '1', '1.0', ' 1', ' 1.0', '01', '002'])
pd.to_numeric(s2, errors='ignore')

[out]:
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
5    1.0
6    1.0
7    2.0
dtype: float64

Then I try:
s2 = pd.Series([1, 1.0, 'hello', '1.0', ' 1', ' 1.0', '01', '002'])
pd.to_numeric(s2, errors='ignore')

[out]:
0        1
1        1
2    hello
3      1.0
4        1
5      1.0
6       01
7      002
dtype: object

notice the 002 is not converted to 2 as before.
```

#### Problem description

It seems that the behavior of to_numeric in handling int with leading zeros is not consistent.

#### Expected Output

handling 00n should be consistent (converted to n)

INSTALLED VERSIONS
------------------

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.5
numpy            : 1.18.5
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 47.3.1.post20200616
Cython           : 0.29.20
pytest           : 5.4.3
hypothesis       : 5.18.1
sphinx           : 3.1.1
blosc            : None
feather          : None
xlsxwriter       : 1.2.9
lxml.etree       : 4.5.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.15.0
pandas_datareader: None
bs4              : 4.9.1
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.1
matplotlib       : 3.2.1
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.4.3
pyxlsb           : None
s3fs             : None
scipy            : 1.5.0
sqlalchemy       : 1.3.18
tables           : 3.6.1
tabulate         : None
xarray           : 0.15.1
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.9
numba            : 0.49.1

</details>

**Comment by mwaddoups** [comment]
New here but thought I'd be able to help. I would say this behaviour is actually expected.

In the documentation on the `errors` flag for `to_numeric`

```
 - If 'ignore', then invalid parsing will return the input.
```

Since strings cannot be coerced to numeric values, these count as invalid parses and thus the series is returned unchanged. However, in the case of your `s2` series, all values could be parsed successfully (as you can see from the return `dtype` of `float64`).

If you change the flag to `errors='coerce'`, you may get the behaviour you're looking for. For example:

```python
import pandas as pd
s1 = pd.Series(['apple', '001', '002', -3])
s2 = pd.Series([1, 1.0, '1', '1.0', ' 1', ' 1.0', '01', '002'])
s3 = pd.Series([1, 1.0, 'hello', '1.0', ' 1', ' 1.0', '01', '002'])

for s in [s1, s2, s3]:
    print(pd.to_numeric(s, errors='coerce'))
```

outputs

```
0    NaN
1    1.0
2    2.0
3   -3.0
dtype: float64
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
5    1.0
6    1.0
7    2.0
dtype: float64
0    1.0
1    1.0
2    NaN
3    1.0
4    1.0
5    1.0
6    1.0
7    2.0
dtype: float64
```

The documentation could be a touch clearer on what "invalid parsing" refers to - something like "any value which fails to be parsed will cause the error to be ignored and the initial values to be returned".

I can't think of many use cases for `errors='ignore'` over `errors='coerce'` off the top of my head.

**Comment by abedhammoud** [comment]
Thanks very much for helping. I am new here too.

I am not sure I follow what you are stating above - but I believe I am not fully understanding how the to_numeric() should behave. 

I thought given:

s1 = pd.Series(['apple', '001', '002', -3])

the results of running:

pd.to_numeric(s1, errors='ignore')

should be to convert all number strings (ex. '0001') into numbers (1) and to keep strings that cannot be converted to numbers intact (ex. 'apple' would stay the same). Numbers like -3 would also stay -3.

Your comment about coerce vs ignore certainly helped me.  thanks. I solved the problem (not very neat but it works) as follows:

import pandas as pd
s1 = pd.Series(['apple', '001', '002', -3])
t = pd.to_numeric(s1, errors='coerce', downcast='integer')
t.fillna(s1[t.isna()])

output:
0    apple
1        1
2        2
3       -3
dtype: object

where type(s1[1]) is float

and type(s1[0]) is str

which is what I wanted, but there must be a more pythonic/pandas way.

Thanks again,

**Comment by dsaxton** [comment]
Agree with @mwaddoups that this is behaving as expected. to_numeric is simply not doing any conversion when it can't parse something. It's not related to there being leading zeros in the input (notice the string "1" is not converted either):
```python
In [5]: pd.to_numeric(pd.Series(["abc", "1"]), errors="ignore").iloc[1]                                                                                                                                      
Out[5]: '1'
```

**Comment by abedhammoud** [comment]
Thank you @dsaxton  and @mwaddoups for your help.
I got what I needed using the python str.isnumeric() method.

df['A'] = df['A'].apply(lambda s: int(s) if str(s).isnumeric() else s)
