### ISSUE TITLE
ENH: Add command line support like pandashells

### ISSUE THREAD

**Issue by zhxh1** [pandas-dev/pandas#35000]
#### Is your feature request related to a problem?

I wish I could use pandas to directly process the data in the command line.

#### Describe the solution you'd like

[pandashells](https://github.com/robdmc/pandashells) does the job pretty well, but it is not under active development and doesn't use the full power of pandas.

#### Additional context

For example, pandashells can process the data in the terminal with:

```bash
$ p.df 'df["c"] = 2 * df.b' 'df.groupby(by="a").c.count()' 'df.reset_index()'
```

More examples can be found [here](https://github.com/robdmc/pandashells#dataframe-manipulations).

**Comment by jreback** [comment]
this is out of scope for pandas proper

 better to create a library / tool on top (like pandashell)
