### ISSUE TITLE
BUG: `fillna()` on multiple columns with a series

### ISSUE THREAD

**Issue by eggers** [pandas-dev/pandas#35005]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
df = pd.DataFrame([{'Cat1': None, 'Cat2': 'mouse', 'Cat3': 'dog'},{'Cat1': 'cat', 'Cat2': 'mouse', 'Cat3': 'dog'},])

print('One column')
print(df['Cat1'].fillna(df['Cat3']))
print()

print('Two columns with one column')
print(df[['Cat1', 'Cat2']].fillna(df['Cat3']))
print()

print('Two columns with two columns')
print(df[['Cat1', 'Cat2']].fillna(df[['Cat3', 'Cat3']]))
```

Output:
```
One column
0    dog
1    cat
Name: Cat1, dtype: object

Two columns with one column
   Cat1   Cat2
0  None  mouse
1   cat  mouse

Two columns with two columns
  Cat1   Cat2
0  NaN  mouse
1  cat  mouse
```

#### Problem description

`fillna()` on multiple columns with a series doesn't work in the same way that it does on a single column. I also tried to use a dataframe thinking that perhaps it needed a matching number of columns, but that only filled the column with `NaN` instead of the correct value.

#### Expected Output

```
One column
0    dog
1    cat
Name: Cat1, dtype: object

Two columns with one column
   Cat1   Cat2
0  dog  mouse
1   cat  mouse

Two columns with two columns
  Cat1   Cat2
0  dog  mouse
1  cat  mouse
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.9.0-12-amd64
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.4
numpy            : 1.18.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 47.1.1.post20200529
Cython           : 0.29.19
pytest           : 5.4.2
hypothesis       : 5.16.0
sphinx           : 3.0.4
blosc            : None
feather          : None
xlsxwriter       : 1.2.9
lxml.etree       : 4.5.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.15.0
pandas_datareader: None
bs4              : 4.9.1
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : 0.6.2
lxml.etree       : 4.5.1
matplotlib       : 3.2.1
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : 0.17.1
pytables         : None
pytest           : 5.4.2
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.17
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.9
numba            : 0.49.1

</details>

**Comment by TomAugspurger** [comment]
Can you make this a reproducible exampled by defining `df`?

**Comment by eggers** [comment]
@TomAugspurger Of course, I forgot to put that in. I edited the issue, but here's the definition as well:

```python
df = pd.DataFrame([{'Cat1': None, 'Cat2': 'mouse', 'Cat3': 'dog'},{'Cat1': 'cat', 'Cat2': 'mouse', 'Cat3': 'dog'},])
```

**Comment by Rish001** [comment]
Can I work on this?

**Comment by TomAugspurger** [comment]
@Rish001 the expected behavior hasn't been established yet.

@eggers Series are treated like dicts, so the index labels of the `value` should match the column name of the DataFrame.

I think DataFrame.fillna(DataFrame) is similar but has a restriction that the column names should match too?

**Comment by eggers** [comment]
@TomAugspurger 

That makes sense about column names needing to match for `DataFrame.fillna(DataFrame)`. For example this does work:

```python
df_fill = df[['Cat3', 'Cat3']]
df_fill.columns = ['Cat1', 'Cat2']
print(df[['Cat1', 'Cat2']].fillna(df_fill))
```

So the question is what `DataFrame.fillna(Series)` should result in.

My contention is that `DataFrame.fillna(Series)` should be to `DataFrame.fillna(value)` what `series.fillna(Series)` is to `Series.fillna(value)` That's what the documentation (which is identical for `Series.fillna()` and `DataFrame.fillna()` says:

```...values specifying which value to use for each index (for a Series)...```

I also tried adding `axis=1` and got this error: `NotImplementedError: Currently only can fill with dict/Series column by column` which also seems to indicate that `DataFrame.fillna(Series)` was meant to fill column by column.

**Comment by TomAugspurger** [comment]
I don't fully understand your example, but Series are dict-like where the index is the keys and the values are the values.

So this looks correct to me

```python
In [10]: df = pd.DataFrame({"A": [1, None], "B": [1, None]})

In [11]: df.fillna(pd.Series({"A": 0, "B": 1}))
Out[11]:
     A    B
0  1.0  1.0
1  0.0  1.0

In [12]: df.fillna({"A": 0, "B": 1})
Out[12]:
     A    B
0  1.0  1.0
1  0.0  1.0
```

**Comment by eggers** [comment]
@TomAugspurger  the example was just getting `DataFrame.fill(DataFrame)` to work correctly.

Your example is filling by columns. The documentation states that it should be filled by rows.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html

>value: scalar, dict, Series, or DataFrame
>Value to use to fill holes (e.g. 0), alternately a dict/Series/DataFrame of values specifying which value to use for each index (for a Series) or column (for a DataFrame). Values not in the dict/Series/DataFrame will not be filled. This value cannot be a list.

...

>axis: {0 or ‘index’, 1 or ‘columns’}
>Axis along which to fill missing values.

**Comment by TomAugspurger** [comment]
> The documentation states that it should be filled by rows.

Which part? My read on that is that when `self` is a Series, the keys specify which index to fill for. When `self` is a DataFrame the keys specify which column to fill for.

I think that `axis` only applies to `method=`, not `value=`. That could be clarified.

**Comment by TomAugspurger** [comment]
@eggers let me know if https://github.com/pandas-dev/pandas/issues/35005#issuecomment-674061609 is incorrect. We'd be happy to have doc improvements, but I think things are working as intended.
