### ISSUE TITLE
BUG: Double requirement given for fsspec in requirements-dev.txt

### ISSUE THREAD

**Issue by SanthoshBala18** [pandas-dev/pandas#35010]
Following error is found, while trying to set up local development environment:

ERROR: Double requirement given: fsspec>=0.7.4 (from -r requirements-dev.txt (line 69)) (already in fsspec>=0.5.1 (from -r requirements-dev.txt (line 25)), name='fsspec')

In requirements-dev.txt, two different versions of fsspec modules are specified.
fsspec>=0.5.1
fsspec>=0.7.4

**Comment by TomAugspurger** [comment]
Thanks for the report. We need to remove https://github.com/pandas-dev/pandas/blob/998e2abdca47f37072f4ec5ca72beffb3b1afeaf/environment.yml#L40 and then run `python scripts/generate_pip_deps_from_conda.py`. Would you be able to submit a PR with that?
