### ISSUE TITLE
ENH: Delta Lake file format support

### ISSUE THREAD

**Issue by jackwellsxyz** [pandas-dev/pandas#35017]
#### Is your feature request related to a problem?

No

#### Describe the solution you'd like

I'd love it if Pandas could support Databricks' Delta Lake file format (https://github.com/delta-io/delta). It's a type of versioned parquet file format that supports updates/inserts/deletions.

#### API breaking implications

None that I'm aware of

#### Describe alternatives you've considered

N/A

#### Additional context

N/A

**Comment by yehoshuadimarsky** [comment]
I'm pretty sure Delta Lake only supports access via Spark at the moment, not through any other tools or APIs. I'll post the link in the docs where it mentions it when I can find it, but I do remember reading that.

**Comment by jbrockmendel** [comment]
I doubt we would support that directly, but if there is an implementation we could link to it in the ecosystem docs.

**Comment by ggGibs** [comment]
FYI Koalas reads/writes to delta lake [https://koalas.readthedocs.io/en/latest/reference/io.html#delta-lake](url), and has easy koalas <--> pandas methods
But it looks like a pandas-like wrapper on top of pyspark - you will need a spark cluster somewhere to handle the I/O. No hope running it standalone

**Comment by TomAugspurger** [comment]
Happy to take an addition to the ecosystem docs when a reader / writer is available. That won't be implemented in pandas, but perhaps in / using pyarrow.

**Comment by houqp** [comment]
Happy to share that we now have native support for Delta lakes outside of JVM and Spark. It's a full deltalake implementation in pure Rust. We also provide a thin python wrapper for pandas integration, see https://github.com/delta-io/delta-rs/tree/main/python#usage.

@jbrockmendel perhaps we can link this to the ecosystem docs?

**Comment by jbrockmendel** [comment]
fine by me

**Comment by houqp** [comment]
Add to @MrPowers 's comment, delta-rs now has write support in the rust core, just waiting for someone to send us a PR to expose that write api to the python shim ;)
