### ISSUE TITLE
BUG: pd.Series.plot() with specific datetime values shows wrong dates when specifying a matplotlib DateFormatter

### ISSUE THREAD

**Issue by gshpychka** [pandas-dev/pandas#35016]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

Hello. I've run into a very weird and specific issue. 

When plotting a Series with some specific datetime values produced by pd.to_datetime() in the index, using pd.Series.plot() and supplying a custom matplotlib DateFormatter to the x axis, the x axis is all wrong.

I know this sounds confusing.

Here's a minimal example:

```python
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter
%matplotlib inline

x_formatter = DateFormatter("%Y")

dates = [dt.date(2020,1,4), dt.date(2020,1,5), dt.date(2020,1,6)]
pd.Series([5,8,7], index=pd.to_datetime(dates)).plot()
ax = plt.gca()
ax.xaxis.set_major_formatter(x_formatter)
```

#### Problem description

[Here's what the output looks like](
https://i.imgur.com/DjqqeWa.png)

The formatted outputs "0051" as the year for this particular example. This only happens for some specific dates (I wasn't able to figure out a rule), and only when supplying a matplotlib formatter.

This does not happen when using matplotlib directly.
This also does not happen when NOT using pd.to_datetime()

#### Expected Output

'2020' labels at major tick locations.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.5.final.0
python-bits      : 32
OS               : Linux
OS-release       : 3.10.0-862.2.3.el7.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.16.1
pytz             : 2018.5
dateutil         : 2.6.1
pip              : 20.1.1
setuptools       : 39.2.0
Cython           : 0.29.17
pytest           : 3.5.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.1.1
lxml.etree       : 4.2.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.7.4 (dt dec pq3 ext)
jinja2           : 2.10
IPython          : 6.4.0
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.2.1
matplotlib       : 2.2.2
numexpr          : None
odfpy            : None
openpyxl         : 2.5.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 3.5.1
pyxlsb           : None
s3fs             : None
scipy            : 1.1.0
sqlalchemy       : 1.1.15
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.1.0
xlwt             : None
xlsxwriter       : 1.1.1
numba            : 0.40.0

</details>

**Comment by NHTRB-py** [comment]
I think pandas is actually changing the date when it causes this bug. I was getting the same strange output and tried the "%y" format for a date in 2020, the DateFormatter threw an error to do with "%y" only working for dates after 1900.

**Comment by TomAugspurger** [comment]
@gshpychka this is working correctly with recent verisons of matplotlib

![gh](https://user-images.githubusercontent.com/1312546/92251634-bc4cb100-ee92-11ea-93e2-c63cfac5c0d7.png)
