### ISSUE TITLE
ASV: asvs for DataFrame.values, to_numpy

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#35023]
xref #34999

**Comment by Rong-Inspur** [comment]
Hi, I am new to this community and would like to do my first contribution. May I take this issue?
To clarify the problem, we want to add to_numpy() benchmarks?

**Comment by jreback** [comment]
yep

**Comment by jreback** [comment]
for single dtype and mixed frames of varying size 

we might have some .values benchmarks which should be consolidated with these

**Comment by Rong-Inspur** [comment]
> for single dtype and mixed frames of varying size
> 
> we might have some .values benchmarks which should be consolidated with these

Thanks for the clarify. I'll look into that.

**Comment by erfannariman** [comment]
@Rong-Inspur are you still working on this?

**Comment by Rong-Inspur** [comment]
> @Rong-Inspur are you still working on this?

Yes, I'm still looking into that.

**Comment by GobindB** [comment]
Hey there, wanted to see if this issue was still open and if there was any scope for me to get involved?

**Comment by Rong-Inspur** [comment]
Hi, due to some personal reasons, I no longer have access to this account. This issue is still open for now and anyone interested can get involved. So sorry for the delay and inconvenience.

**Comment by Rong-Inspur** [comment]
> Hey there, wanted to see if this issue was still open and if there was any scope for me to get involved?

Yes

**Comment by avinashpancham** [comment]
@erfannariman @GobindB is either of you planning to pick this up? Else I would like to work on it.

**Comment by Anupam-USP** [comment]
I am new to this, can you please explain me what to do so that this can be my first contribution?

**Comment by GobindB** [comment]
@avinashpancham I'm planning on picking up this issue

**Comment by hardikpnsp** [comment]
if no one is working on it, I would like to pick this up.

**Comment by hardikpnsp** [comment]
take

**Comment by avinashpancham** [comment]
I am not working on it, so go ahead :)
