### ISSUE TITLE
DOC: text in pandas.Series.dt.day refers to month instead of day

### ISSUE THREAD

**Issue by danielolsen** [pandas-dev/pandas#35031]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dt.day.html

#### Documentation problem

The text here is a duplicate of https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dt.month.html (`The month as January=1, December=12.`), when it should probably be something else.

**Comment by erfannariman** [comment]
This is already resolved in master, see https://github.com/pandas-dev/pandas/pull/31490
