### ISSUE TITLE
Performance regression in arithmetic.ApplyIndex.time_apply_index

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#35048]
https://pandas.pydata.org/speed/pandas/index.html#arithmetic.ApplyIndex.time_apply_index?p-offset=%3CMonthBegin%3E&commits=55adcb8688582e3a3be66b1036d3604327ae5071-b05e6b1402124a062608b97ca02af0cfb13568d1, https://github.com/pandas-dev/pandas/compare/55adcb8688582e3a3be66b1036d3604327ae5071...b05e6b1402124a062608b97ca02af0cfb13568d1 (30 commits in there).

**Comment by jbrockmendel** [comment]
Best guess is this is #34778 and the compiler is inlining things differently on the benchmark machine than it does locally.

**Comment by TomAugspurger** [comment]
Another thing: I think the benchmark code changed from `offset.apply_index(rng)` to `offset + rng`. Locally I have these timings

```python
import pandas as pd
import numpy as np

N = 10000
rng = pd.date_range(start="1/1/2000", periods=N, freq="T")
offset = pd.offsets.MonthBegin()
```


```python
# 1.0.4
In [6]: %timeit offset + rng
424 µs ± 4.53 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [7]: %timeit offset.apply_index(rng)

335 µs ± 12.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```


```python
# master
   ...: %timeit offset + rng
755 µs ± 7.05 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
