### ISSUE TITLE
CI: Linux py37_np_dev Concatenation operation is not implemented for NumPy arrays, use np.concatenate() instead.

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#35041]
https://github.com/numpy/numpy/commit/8ac7ac94ab868473e2276902be656946745c641f

https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=38318&view=logs&j=3a03f79d-0b41-5610-1aa4-b4a014d0bc70&t=4d05ed0e-1ed3-5bff-dd63-1e957f2766a9

**Comment by biddwan09** [comment]
Hi @simonjayhawkins  for fixing this issue should i check for Concatenation operation here and use np. concatenate() here ?
  
```
  if should_extension_dispatch(lvalues, rvalues) or isinstance(rvalues, Timedelta):
        # Timedelta is included because numexpr will fail on it, see GH#31457
        res_values = op(lvalues, rvalues)

    else:
        with np.errstate(all="ignore"):
            res_values = na_arithmetic_op(lvalues, rvalues, op)

    return res_values
```

**Comment by simonjayhawkins** [comment]
not sure. wait and see what others think. I can't see a change note or deprecation for the change in NumPy. @pandas-dev/pandas-core

**Comment by biddwan09** [comment]
Sure will wait for the others to respond
