### ISSUE TITLE
Performance regression in frame_methods.Apply.time_apply_ref_by_name

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#35047]
https://pandas.pydata.org/speed/pandas/index.html#frame_methods.Apply.time_apply_ref_by_name?commits=91802a9ae400830f9eaadd395f6a9b40cdd92ee5

https://github.com/pandas-dev/pandas/commit/91802a9ae400830f9eaadd395f6a9b40cdd92ee5 (cc @jbrockmendel)

Also affects other benchmarks that probably use apply: https://pandas.pydata.org/speed/pandas/index.html#frame_methods.Nunique.time_frame_nunique?commits=91802a9ae400830f9eaadd395f6a9b40cdd92ee5.

**Comment by jbrockmendel** [comment]
I measured 91802a9 as perf-neutral locally.  If that doesnt hold elsewhere, might as well revert.

**Comment by TomAugspurger** [comment]
I don't know if it's an artifact of asv / line-profiler, but it looks like a lot of time is spent in `option_context.__enter__` and `option_context.__exit__`:

```
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   266                                               def apply_series_generator(self, partial_result=None) -> Tuple[ResType, "Index"]:
...
   296      1000      24406.0     24.4     34.5                  with option_context("mode.chained_assignment", None):
```

Do you have time to explore that? Either optimizing `option_context`, or making an internal version that skips expensive checks, or (if the contextmanager machinery itself is too expensive) a private setitem that skips chained_assignment checks?
