### ISSUE TITLE
Performance regression in replace.Convert.time_replace

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#35053]
https://github.com/pandas-dev/pandas/pull/34999 caused a 2x slowdown in replace.Convert.time_replace (https://pandas.pydata.org/speed/pandas/index.html#replace.Convert.time_replace?p-constructor=%27Series%27&p-replace_data=%27Timestamp%27&commits=dbfbef7eaea7f23a42d9a65344b5745fc055f5b4)

**Comment by jbrockmendel** [comment]
How do you get 100x?  do you mean 100ms?

**Comment by TomAugspurger** [comment]
Sorry, meant 100% (2x). Edited.

**Comment by jbrockmendel** [comment]
Assuming this was caused by#34999, this is something we just have to live with.  The previous behavior was incorrect.

**Comment by TomAugspurger** [comment]
Perhaps a fluke in the timing? The latest runs are back to normal.
