### ISSUE TITLE
BUG: idxmax returns erroneous index from grouped DataFrame

### ISSUE THREAD

**Issue by spluque** [pandas-dev/pandas#35081]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

The following code demonstrates the erroneous output:

```python
import numpy as np
import pandas as pd

N = 12
np.random.seed(1234)
price = np.random.uniform(0, 100, N)
color = np.repeat(list("ABCD"), 3)
df = pd.DataFrame(dict(price=price, color=color),
                  index=pd.date_range("2020-01-01", periods=N,
                                      freq="100ms", tz="UTC"))
df["color"] = df["color"].astype("category")
```

```python
>>> print(df)
                                      price color
2020-01-01 00:00:00+00:00         19.151945     A
2020-01-01 00:00:00.100000+00:00  62.210877     A
2020-01-01 00:00:00.200000+00:00  43.772774     A
2020-01-01 00:00:00.300000+00:00  78.535858     B
2020-01-01 00:00:00.400000+00:00  77.997581     B
2020-01-01 00:00:00.500000+00:00  27.259261     B
2020-01-01 00:00:00.600000+00:00  27.646426     C
2020-01-01 00:00:00.700000+00:00  80.187218     C
2020-01-01 00:00:00.800000+00:00  95.813935     C
2020-01-01 00:00:00.900000+00:00  87.593263     D
2020-01-01 00:00:01+00:00         35.781727     D
2020-01-01 00:00:01.100000+00:00  50.099513     D
```

```python
color_grp = df.groupby("color")
color_idxmax = color_grp.idxmax()
```

```python
>>> print(color_idxmax)
                                 price
color                                 
A     2020-01-01 00:00:00.100000+00:00
B     2020-01-01 00:00:00.300000+00:00
C     2020-01-01 00:00:00.800000+00:00
D     2020-01-01 00:00:00.900000+00:00
```

#### Problem description

Notice the erroneous value printed for the first row in column "price" of `color_idxmax`.

#### Expected Output

It should be: `2020-01-01 00:00:00.200000+00:00`

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.6.0-2-amd64
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_CA.UTF-8
LOCALE           : en_CA.UTF-8

pandas           : 1.0.5
numpy            : 1.19.0
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 44.0.0
Cython           : None
pytest           : 5.4.3
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.16.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.2.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.4.3
pyxlsb           : None
s3fs             : None
scipy            : 1.5.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by erfannariman** [comment]
Thanks for submitting the issue, this looks solved on master:

```python
>>> df_grp = df.groupby("color")
>>> color_idxmax = df_grp.idxmax()
>>> print(color_idxmax)
                                 price
color
A     2020-01-01 00:00:00.200000+00:00
B     2020-01-01 00:00:00.400000+00:00
C     2020-01-01 00:00:00.800000+00:00
D            2020-01-01 00:00:01+00:00
```
```python
>>> print(pd.__version__)
1.1.0.dev0+2003.g5507452c4
```

**Comment by MarcoGorelli** [comment]
> - [x] I have confirmed this bug exists on the latest version of pandas.

I haven't yet checked to see if there's a test for this, just leaving a quick comment to say that 0.25.2 isn't the latest version of pandas

**Comment by erfannariman** [comment]
If it is needed, I can create a test for this @MarcoGorelli

**Comment by simonjayhawkins** [comment]
Thanks @spluque for the report.

I'm not aware of a pandas 0.25.32. Is the output of show_versions correct? I can't reproduce on pandas 0.25.3. The code sample uses random without a seed, so not able to consistently reproduce same result. can you update the OP with a minimal reproducible example.

Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

**Comment by spluque** [comment]
I've updated the report, including details, and printing at the console.  This time I made sure I was in a virtualenv with latest pandas.

**Comment by simonjayhawkins** [comment]
> Notice the erroneous value printed for the first row in column "price" of `color_idxmax`.

the maximum value in group A, is 62.210877, which occurs at 2020-01-01 00:00:00.100000+00:00.

The results look correct to me.

**Comment by spluque** [comment]
> > Notice the erroneous value printed for the first row in column "price" of `color_idxmax`.
> 
> the maximum value in group A, is 62.210877, which occurs at 2020-01-01 00:00:00.100000+00:00.
> 
> The results look correct to me.

Indeed!  That's embarrassing, I must have misread the results previously.  Apologies for the unnecessary report.

**Comment by simonjayhawkins** [comment]
Not a problem!
