### ISSUE TITLE
QST: Zero copy access to the mask of a nullable array

### ISSUE THREAD

**Issue by brandon-b-miller** [pandas-dev/pandas#35089]
- [ ] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

Hello Pandas devs,
I was wondering what's the best zero-copy way to access the mask of a nullable array, say a StringArray for example. I noticed these all inherit from BaseMaskedArray which provides `isna()` wrapping `_mask` however I want to make sure this is the recommended method, if I can always be sure this doesn't incur a copy, etc. Should I be using `isna()` or something else, if it exists?

**Comment by TomAugspurger** [comment]
See https://github.com/pandas-dev/pandas/issues/34873.

And FYI StringArray doesn't use a mask currently. It's NA values are stored inline.
