### ISSUE TITLE
BUG: series.loc(index) throws exception

### ISSUE THREAD

**Issue by Nodirbek3d** [pandas-dev/pandas#35094]
Simple loc() method does not work!
Here is the code to reproduce:

```python
# Your code here
letters = pd.Series(['A', 'B', 'C', 'D', 'E' ], index=[3, 4, 1, 2, 2])
letters.loc(2)
```
code above throws exception:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-45-42a68f905e63> in <module>
----> 1 animals.loc(1)

/usr/local/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py in __call__(self, axis)
    575 
    576         if axis is not None:
--> 577             axis = self.obj._get_axis_number(axis)
    578         new_self.axis = axis
    579         return new_self

/usr/local/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py in _get_axis_number(cls, axis)
    405             except KeyError:
    406                 pass
--> 407         raise ValueError(f"No axis named {axis} for object type {cls}")
    408 
    409     @classmethod

ValueError: No axis named 1 for object type <class 'pandas.core.series.Series'>
```

#### Problem description

Getting the same error on ```obj.iloc(1)```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.5.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.1
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.0.0.post20200309
Cython           : 0.29.15
pytest           : 5.3.5
hypothesis       : 5.5.4
sphinx           : 2.4.0
blosc            : None
feather          : None
xlsxwriter       : 1.2.7
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.1.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.3.5
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.13
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.7
numba            : 0.48.0
</details>

**Comment by jorisvandenbossche** [comment]
See the docs: https://pandas.pydata.org/docs/user_guide/indexing.html#selection-by-label. You need to use square brackets instead of parantheses (``letters.loc[2]``)
