### ISSUE TITLE
QST: Does the following method have circular dependencies? hash_pandas_object

### ISSUE THREAD

**Issue by alessiosavi** [pandas-dev/pandas#35097]
- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

Hi Team, does the method `hash_pandas_object` have circular dependencies?

I'm not able to serialize class that contains the method in my code with `dill`.

```python
# Your code here, if applicable
import numpy as np
import pandas as pd
from pandas.core.util.hashing import hash_pandas_object
# Same result using the following library
# from pandas.util import hash_pandas_object


class T:
	def __init__(self):
		self.dataset_hash = ""

	def main(self):
		df = pd.DataFrame(np.random.randint(0, 100, size=(100, 4)), columns=list('ABCD'))
		print(df)
		self.dataset_hash = hash_pandas_object(df).sum()


import sys
import dill

sys.setrecursionlimit(10 ** 4)

t = T()
with open("test.dill", "wb") as f:
	dill.dump(t, f, recurse=True)
t.main()
```

NOTE:
I've opened an issue to the `dill` repository to [https://github.com/uqfoundation/dill/issues/374]

**Comment by jbrockmendel** [comment]
Yes, xref #29208.  PR(s) to avoid this would be welcome (though i expect not easy)

**Comment by jbrockmendel** [comment]
Closing as answered, can re-open if there are follow-up questions/issues.
