### ISSUE TITLE
BUG: Rounding on float16 type not working

### ISSUE THREAD

**Issue by Genarito** [pandas-dev/pandas#35124]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Problem description

I'm trying to round a column to 4 decimal places to store them in the DB. I must use `np.float16` type to work with as I need the smallest possible precision, but it's not working (see *output* section), if I don't cast the values and leave them as `np.float64` type It'll work correctly.
I think it's a bug of Pandas as if I run:

```python
np.array([0.37324, 0.12321, 0.23]).astype(np.float16).round(4)
```
It works as expected, so It doesn't seem to be a problem for Numpy.

#### Code Sample

```python
import pandas as pd
import numpy as np
df = pd.DataFrame(np.array([0.37324, 0.12321, 0.23]), columns=['A'])
df.astype(np.float16).round(4)
```

Running:

```python
pd.DataFrame(np.array([0.37324, 0.12321, 0.23]).astype(np.float16), columns=['A']).round({'A': 4})
```
Doesn't work either as it has the same output.

#### Current Output

```
          A
0  0.373291
1  0.123230
2  0.229980
```

#### Expected Output

```
          A
0  0.3732
1  0.1232
2  0.23
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.3.0-62-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : es_AR.UTF-8
LOCALE           : es_AR.UTF-8
pandas           : 1.0.5
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 18.1
setuptools       : 40.8.0
Cython           : None
pytest           : 5.3.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.3.5
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by jreback** [comment]
we have very little support for float16

furthermore i suspect this is really just a display issue; convert the series to numpy and see

**Comment by Genarito** [comment]
Hi!
First of all, thanks for answering!
Secondly, converting to Numpy works, I confirmed that above in the description of the issue. However, It'd be great to have a built in solution to manage this kind of rounding in float16.
I'm inserting the DataFrame in the DB with PyMongo, I need the entire DF structure, but every time I put the rounded data in it the values return to its original representation and are inserted with more than 4 decimals. So I'm not sure that it's only a display issue.

**Comment by erfannariman** [comment]
> furthermore i suspect this is really just a display issue; convert the series to numpy and see

This is actually the case. Converting it back to numpy gives us the correct result, so the values underneath are actually rounded correct:

```
pd.DataFrame(np.array([0.37324, 0.12321, 0.23]).astype(np.float16), columns=['A']).round({'A': 4}).to_numpy()

array([[0.3733],
       [0.1232],
       [0.23  ]], dtype=float16)
```

**Comment by Genarito** [comment]
Thank you! When I save in CSV format it was 4 decimals truncated as expected. But now I found a use case where it's not  working:

```python
df = pd.DataFrame(np.array([0.37324, 0.12321, 0.23]), columns=['A'])
df.astype(np.float16).round(4).to_dict('records')
```

Outputs `[{'A': 0.373291015625}, {'A': 0.12322998046875}, {'A': 0.22998046875}]`. Shouldn't the truncation be preserved during the conversion?

**Also important**: the same problem occurs with float32. The float64 and float128 types don't present the problem.

Please, consider re-open the issue as the examples I gave are the commonly used way to work with Pandas and PyMongo. We could iterate over all the dict, but that's not the idea. 

Thanks in advance

**Comment by erfannariman** [comment]
Can confirm the problem stated above occurs on master as well.

@jreback would that be sufficient to re-open this issue?

**Comment by erfannariman** [comment]
Maybe important to note that `to_numpy` still gives the correct result, `to_dict` does not:

```
>>> df.astype(np.float16).round(4).to_numpy()
array([[0.3733],
       [0.1232],
       [0.23  ]], dtype=float16)
```

**Comment by Genarito** [comment]
@jreback Is there any update on this? If you like i would try making a PR when I have some free time.

**Comment by jreback** [comment]
you can make a PR but really sure what you are attempting to solve

**Comment by Genarito** [comment]
Ok, I'll try in a few weeks

**Comment by mickaelandrieu** [comment]
Hi,

The issue is still present on the latest release of pandas with float32.

Regards,

**Comment by jreback** [comment]
you would have to open a new issue with a reproducible example

**Comment by mickaelandrieu** [comment]
Hi Jeff,

I don't know ! This issue was reproducible, clear and ... closed with no action.

The best I can do here is to inform you, then cast my series to float64 and move on.

No hard feelings here, I'm glad this bug was reported because I know why it's not working as I expected.

Regards,

**Comment by jreback** [comment]
this is about float16

**Comment by Genarito** [comment]
Now it's about float16 and float32

**Comment by Kerybas** [comment]
I found the root cause:
https://github.com/pandas-dev/pandas/issues/50125#issuecomment-1342886489
