### ISSUE TITLE
BUG: pandas does not build on AIX - when using xlc/xlC as compiler

### ISSUE THREAD

**Issue by aixtools** [pandas-dev/pandas#35123]
- [x ] I have checked that this issue has not already been reported.

- [ x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

Panda build stops with:

```
"pandas/_libs/window/aggregations.cpp", line 5436.23: 1540-0063 (S) The text "(" is unexpected.
"pandas/_libs/window/aggregations.cpp", line 5523.23: 1540-0063 (S) The text "(" is unexpected.
"pandas/_libs/window/aggregations.cpp", line 6759.21: 1540-0063 (S) The text "(" is unexpected.
"pandas/_libs/window/aggregations.cpp", line 20023.21: 1540-0063 (S) The text "(" is unexpected.
```

On examining this I see that there are special statements - perhaps unsupported by xlc/xlC (v11).

```
 +5436      __pyx_t_1 = (std::signbit(__pyx_v_val) != 0);

 +5523      __pyx_t_1 = (std::signbit(__pyx_v_val) != 0);

 +6759    __pyx_t_1 = (std::isnan(__pyx_v_val) != 0);

+20023    __pyx_t_1 = (std::isnan(__pyx_v_val) != 0);

```

There is a good chance this is an issue caused by cython. but I thought I would post/mention it here as well.

**Comment by jreback** [comment]
we have no support on AIX - but would accept patches

**Comment by aixtools** [comment]
Would love to help - but will need help creating a patch. Cython says - not our problem: https://github.com/cython/cython/issues/3723

**Comment by aixtools** [comment]
For a starting point - currently testing the tagged versions 0.24.2 and 0.25.3 - to see if they build.

**Comment by WillAyd** [comment]
I think @da-woods summed it up well on the Cython issue; seems like more of a compiler C++11 support issue than anything else

If you can find a way to define compatible functions without C++11 support feel free to push a PR

**Comment by WillAyd** [comment]
At this point in time pandas requires C++11 and that is explicitly enforced by the build system, so I don't think there is much to do here
