### ISSUE TITLE
CI: Update to isort 5

### ISSUE THREAD

**Issue by AlexKirko** [pandas-dev/pandas#35134]
`isort` 5.x is out with some changes to how it sorts. We'll need to update the code and unpin in our environment file.

**Comment by jreback** [comment]
love a PR to fix (can likely just drop the recursive kw) or could pin isort- either way us ok

**Comment by AlexKirko** [comment]
Should be fine if we drop the keyword. Let me give it a try.

**Comment by AlexKirko** [comment]
take

**Comment by AlexKirko** [comment]
Yeah, no. Version 5 has changed the way it sorts imports, so it now throws a couple hundred errors on our file base. I'll pin `isort` for now, and we can check later if this new version breaks anything.

**Comment by VirosaLi** [comment]
isort 5 would change all
```python
import x.y as z
```
to
```python
from x import y as z
```

then the unwantedpattern check won't pass.

The

```bash
mypy pandas
```
check would fail as well
```bash
(pandas-dev) xxx@xxx-home-office:~/Workspace/pandas-VirosaLi$ mypy pandas
pandas/core/util/hashing.py:9: error: Module 'pandas._libs' has no attribute 'hashing'
pandas/core/ops/array_ops.py:13: error: Module 'pandas._libs' has no attribute 'ops'
pandas/core/strings.py:10: error: Module 'pandas._libs' has no attribute 'ops'
pandas/core/indexes/base.py:19: error: Module 'pandas._libs' has no attribute 'join'
pandas/core/indexes/datetimelike.py:9: error: Module 'pandas._libs' has no attribute 'join'
pandas/core/series.py:25: error: Module 'pandas._libs' has no attribute 'reshape'
pandas/io/parsers.py:17: error: Module 'pandas._libs' has no attribute 'ops'
pandas/core/reshape/reshape.py:6: error: Module 'pandas._libs' has no attribute 'reshape'
pandas/core/groupby/ops.py:13: error: Module 'pandas._libs' has no attribute 'groupby'
pandas/core/groupby/ops.py:13: error: Module 'pandas._libs' has no attribute 'reduction'
pandas/core/groupby/groupby.py:36: error: Module 'pandas._libs' has no attribute 'groupby'
pandas/io/excel/_xlwt.py:1: error: Module 'pandas._libs' has no attribute 'json'
pandas/io/excel/_xlsxwriter.py:1: error: Module 'pandas._libs' has no attribute 'json'
pandas/io/json/_table_schema.py:9: error: Module 'pandas._libs' has no attribute 'json'
pandas/io/json/_json.py:10: error: Module 'pandas._libs' has no attribute 'json'
pandas/io/excel/_odswriter.py:5: error: Module 'pandas._libs' has no attribute 'json'
pandas/core/reshape/merge.py:13: error: Module 'pandas._libs' has no attribute 'join'
pandas/_testing.py:25: error: Module 'pandas._libs' has no attribute 'testing'
pandas/core/window/rolling.py:14: error: Module 'pandas._libs.window' has no attribute 'aggregations'
pandas/core/window/ewm.py:9: error: Module 'pandas._libs.window' has no attribute 'aggregations'
pandas/tests/test_join.py:4: error: Module 'pandas._libs' has no attribute 'join'
pandas/tests/io/json/test_ujson.py:16: error: Module 'pandas._libs' has no attribute 'json'
pandas/tests/groupby/test_bin_groupby.py:4: error: Module 'pandas._libs' has no attribute 'groupby'
pandas/tests/groupby/test_bin_groupby.py:4: error: Module 'pandas._libs' has no attribute 'reduction'
pandas/tests/groupby/transform/test_transform.py:7: error: Module 'pandas._libs' has no attribute 'groupby'
pandas/tests/reshape/merge/test_join.py:5: error: Module 'pandas._libs' has no attribute 'join'
pandas/tests/test_algos.py:9: error: Module 'pandas._libs' has no attribute 'groupby'
Found 27 errors in 25 files (checked 1024 source files)
```

**Comment by VirosaLi** [comment]
### Breakdown of MyPy errors regarding isort 5 upgrade
- [ ] pandas/core/util/hashing.py:9: error: Module 'pandas._libs' has no attribute 'hashing'
- [ ] pandas/core/ops/array_ops.py:13: error: Module 'pandas._libs' has no attribute 'ops'
- [ ] pandas/core/strings.py:10: error: Module 'pandas._libs' has no attribute 'ops'
- [ ] pandas/core/indexes/base.py:19: error: Module 'pandas._libs' has no attribute 'join'
- [ ] pandas/core/indexes/datetimelike.py:9: error: Module 'pandas._libs' has no attribute 'join'
- [ ] pandas/core/series.py:25: error: Module 'pandas._libs' has no attribute 'reshape'
- [ ] pandas/io/parsers.py:17: error: Module 'pandas._libs' has no attribute 'ops'
- [ ] pandas/core/reshape/reshape.py:6: error: Module 'pandas._libs' has no attribute 'reshape'
- [ ] pandas/core/groupby/ops.py:13: error: Module 'pandas._libs' has no attribute 'groupby'
- [ ] pandas/core/groupby/ops.py:13: error: Module 'pandas._libs' has no attribute 'reduction'
- [ ] pandas/core/groupby/groupby.py:36: error: Module 'pandas._libs' has no attribute 'groupby'
- [ ] pandas/io/excel/_xlwt.py:1: error: Module 'pandas._libs' has no attribute 'json'
- [ ] pandas/io/excel/_xlsxwriter.py:1: error: Module 'pandas._libs' has no attribute 'json'
- [ ] pandas/io/json/_table_schema.py:9: error: Module 'pandas._libs' has no attribute 'json'
- [ ] pandas/io/json/_json.py:10: error: Module 'pandas._libs' has no attribute 'json'
- [ ] pandas/io/excel/_odswriter.py:5: error: Module 'pandas._libs' has no attribute 'json'
- [ ] pandas/core/reshape/merge.py:13: error: Module 'pandas._libs' has no attribute 'join'
- [ ] pandas/_testing.py:25: error: Module 'pandas._libs' has no attribute 'testing'
- [ ] pandas/core/window/rolling.py:14: error: Module 'pandas._libs.window' has no attribute 'aggregations'
- [ ] pandas/core/window/ewm.py:9: error: Module 'pandas._libs.window' has no attribute 'aggregations'
- [ ] pandas/tests/test_join.py:4: error: Module 'pandas._libs' has no attribute 'join'
- [ ] pandas/tests/io/json/test_ujson.py:16: error: Module 'pandas._libs' has no attribute 'json'
- [ ] pandas/tests/groupby/test_bin_groupby.py:4: error: Module 'pandas._libs' has no attribute 'groupby'
- [ ] pandas/tests/groupby/test_bin_groupby.py:4: error: Module 'pandas._libs' has no attribute 'reduction'
- [ ] pandas/tests/groupby/transform/test_transform.py:7: error: Module 'pandas._libs' has no attribute 'groupby'
- [ ] pandas/tests/reshape/merge/test_join.py:5: error: Module 'pandas._libs' has no attribute 'join'
- [ ] pandas/tests/test_algos.py:9: error: Module 'pandas._libs' has no attribute 'groupby'

### Resolve conflicts between non-standard imports checks and isort 5
- [ ] ci/code_checks.sh

### Upgrade to isort 5
- [ ] ci/code_checks.sh
- [ ] doc/source/development/contributing.rst
- [ ] environment.yml
- [ ] requirements-dev.txt
- [ ] run isort 5 for the entire codebase

**Comment by nixphix** [comment]
@VirosaLi can I pick some from the list?

**Comment by VirosaLi** [comment]
> @VirosaLi can I pick some from the list?

The latest version of isort has changed its way of sorting. There is no conflict between MyPy and Isort anymore. So I guess those changes are not needed anymore.
