### ISSUE TITLE
QST:What is the largest datetime in pandas to_datetime?

### ISSUE THREAD

**Issue by vitthaljkulkarni** [pandas-dev/pandas#35143]
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [x] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.
I am  trying to read a date from excel. For validation, when I use 'pd.to_datetime' to compare against another datetime object, for date 9999-12-31, I am getting an exception: 'OutofBoundsDateTime', whereas I believe this should still be a valid MAXDATE as per standards. Here is a sample code where I am facing such issue:

```python
# Your code here, if applicable
import pandas as pd
df = pd.DataFrame(["9999-12-31"])
pd.to_datetime(df[0])
```

**Comment by jreback** [comment]
see the docs here https://pandas.pydata.org/docs/user_guide/timeseries.html#timeseries-oob

**Comment by jreback** [comment]
this is not representable in ns units
