### ISSUE TITLE
July 2020 Developer Meeting

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#35157]
The monthly dev meeting is Wednesday July 8th, at 18:00 UTC. Our calendar is at https://pandas.pydata.org/docs/development/meeting.html#calendar to check your local time.

Video Call: https://zoom.us/j/942410248
Minutes: https://docs.google.com/document/u/1/d/1tGbTiYORHiSPgVMXawiweGJlBw5dOkVJLY-licoBmBU/edit?ouid=102771015311436394588&usp=docs_home&ths=true

Please add items you'd like to see discussed to the agenda.

All are welcome to attend.

FYI, I might not be able to attend, or I might just be on the phone. I think the Zoom call is structured to start automatically without me. @jreback and @jorisvandenbossche should also have Zoom accounts through NumFOCUS that can be used.

**Comment by jreback** [comment]
july 10 right? and we could move to another day if helpful

**Comment by TomAugspurger** [comment]
Fixed: it should have said July 8th. No need to move it.
