### ISSUE TITLE
BUG: ImportError: cannot import name 'Collection' from 'typing'

### ISSUE THREAD

**Issue by niju1** [pandas-dev/pandas#35177]
- [ ] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python

import pandas as pd 

data = pd.read_csv('Simulations Ãœbersicht_Labled_intrusion.csv')
print(data.head(5))

```

#### Problem description
base) ballal@i6.emi.fhg.de:/home-24/ballal/Skripte/Rule Extraction
$ python3 decisiontree.py
Traceback (most recent call last):
  File "decisiontree.py", line 1, in <module>
    import pandas as pd 
  File "/home/ballal/anaconda3/lib/python3.7/site-packages/pandas/__init__.py", line 54, in <module>
    from pandas.core.api import (
  File "/home/ballal/anaconda3/lib/python3.7/site-packages/pandas/core/api.py", line 6, in <module>
    from pandas.core.dtypes.dtypes import (
  File "/home/ballal/anaconda3/lib/python3.7/site-packages/pandas/core/dtypes/dtypes.py", line 10, in <module>
    from pandas._typing import Ordered
  File "/home/ballal/anaconda3/lib/python3.7/site-packages/pandas/_typing.py", line 2, in <module>
    from typing import (
ImportError: cannot import name 'Collection' from 'typing' (/usr/lib/python3.4/site-packages/typing.py)

I cannot import pandas. I installed the latest version of pandas too. 

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by simonjayhawkins** [comment]
Collection was added in 3.6 https://docs.python.org/3/library/typing.html#typing.Collection

**Comment by niju1** [comment]
I tried using 3.6 and still facing the same issue 

Python 3.6.8 (default, Apr  2 2020, 13:34:55) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ballal/.local/lib/python3.6/site-packages/pandas/__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "/home/ballal/.local/lib/python3.6/site-packages/pandas/core/api.py", line 6, in <module>
    from pandas.core.dtypes.dtypes import (
  File "/home/ballal/.local/lib/python3.6/site-packages/pandas/core/dtypes/dtypes.py", line 10, in <module>
    from pandas._typing import Ordered
  File "/home/ballal/.local/lib/python3.6/site-packages/pandas/_typing.py", line 2, in <module>
    from typing import (
ImportError: cannot import name 'Collection'

**Comment by TomAugspurger** [comment]
Your original traceback points to `usr/lib/python3.4/site-packages/typing.py`. Seems like something strange with your paths.

**Comment by rhshadrach** [comment]
Any updates @niju1? Did you get it working?

**Comment by MarcoGorelli** [comment]
closing but please let us know if you can update with more info

**Comment by niju1** [comment]
The problem was not only with pandas, but even with the other packages.
I was facing it only in virtual environment. I tried reinstalling pycharm, updating python, reinstalling python, manually installing ‘typing’, but nothing helped. So, I had to run it outside the virtual environment.

Von: Marco Gorelli <notifications@github.com>
Gesendet: Mittwoch, 19. August 2020 14:22
An: pandas-dev/pandas <pandas@noreply.github.com>
Cc: Ballal, Niranjan <Niranjan.Ballal@emi.fraunhofer.de>; Mention <mention@noreply.github.com>
Betreff: Re: [pandas-dev/pandas] BUG: ImportError: cannot import name 'Collection' from 'typing' (#35177)


closing but please let us know if you can update with more info
