### ISSUE TITLE
ENH: Inconsistency: .astype("string") should convert int-Series to string

### ISSUE THREAD

**Issue by FlorianWetschoreck** [pandas-dev/pandas#35174]
```python
pd.Series(['1', '2', '3'], dtype="string").astype("int")
```
Turns the String Series into an Integer Series and converts the values.

However, the inverse operation raises an Error:

```python
pd.Series([1, 2, 3], dtype="int").astype("string")
```

In order to be consistent, the inverse operation should also work.
Currently, I think that the best alternative solutions are something like this:

```python
pd.Series(pd.Series([1, 2, 3], dtype="int").apply(str), dtype="string")
```
or
```python
pd.Series([1, 2, 3], dtype="int").apply(str).convert_dtypes()
```
But those solutions are too convoluted and not consistent with the above API.

**Comment by dlegor** [comment]
I don't see the inconsistency, just change **"string"** to  **"str"**.

Instead of using this: 
~~~python 
pd.Series([1, 2, 3], dtype="int").astype("string")
~~~

Use this:
~~~python 
pd.Series([1, 2, 3], dtype="int").astype("str")
~~~

**Comment by TomAugspurger** [comment]
@FlorianWetschoreck this is fixed on master.

@dlegor `str` and `string` give different result dtypes. `str` converts to object right now.
