### ISSUE TITLE
Possible performance regression in Series.xs() and DataFrame.xs() with MultiIndex.

### ISSUE THREAD

**Issue by taozuoqiao** [pandas-dev/pandas#35188]
Performance of `Series.xs()` when getting values at specified index and the **first level** of a large dataset seems to have regressed significantly, after pandas was upgraded to v1.0.5 from v0.25.3.  So is `DataFrame.xs()`.

code:
```python
import numpy as np
import pandas as pd
n=1e4
data = pd.Series(np.arange(n**2), index=pd.MultiIndex.from_product([np.arange(n), -np.arange(n)]))
%timeit data.xs(100, level=0) #first level
%timeit data.xs(-100, level=1) #second level
```
outcome
```python
## 0.25.3
%timeit data.xs(100, level=0)
571 µs ± 1.79 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit data.xs(-100, level=1)
193 ms ± 947 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## 1.0.5
%timeit data.xs(100, level=0)
683 ms ± 3.35 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)  

%timeit data.xs(-100, level=1)
197 ms ± 2.42 ms per loop (mean ± std. dev. of 7 runs, 10 loops each) 
```

**Comment by simonjayhawkins** [comment]
it appears #29840 is responsible for the slowdown here

9dd1b50f2cf70c0ec7de07137b08ae5866afae69 is the first bad commit
commit 9dd1b50f2cf70c0ec7de07137b08ae5866afae69
Author: jbrockmendel <jbrockmendel@gmail.com>
Date:   Fri Nov 29 15:10:02 2019 -0800

    DEPR: remove FrozenNDarray (#29840)

cc @jbrockmendel

**Comment by lukemanley** [comment]
I think this can be closed. 

```
## main

%timeit data.xs(100, level=0)
198 µs ± 1.79 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

%timeit data.xs(-100, level=1)
82.3 ms ± 3.22 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by jreback** [comment]
yep
do we have covering asvs for these cases?

**Comment by lukemanley** [comment]
> do we have covering asvs for these cases?

ASVs added in linked PR

**Comment by repos-cl** [comment]
Thanks very much!
