### ISSUE TITLE
ENH: Print and manipulate rows

### ISSUE THREAD

**Issue by SayanJerr** [pandas-dev/pandas#35191]
#### Is your feature request related to a problem?

[this should provide a description of what the problem is, e.g. "I wish I could use pandas to do [...]"]

#### Describe the solution you'd like

[this should provide a description of the feature request, e.g. "`DataFrame.foo` should get a new parameter `bar` that [...]", try to write a docstring for the desired feature]

#### API breaking implications

[this should provide a description of how this feature will affect the API]

#### Describe alternatives you've considered

[this should provide a description of any alternative solutions or features you've considered]

#### Additional context

[add any other context, code examples, or references to existing implementations about the feature request here]

```python
# Your code here, if applicable

```

**Comment by SayanJerr** [comment]
take

**Comment by mroeschke** [comment]
If you could fill out the issue template, it may help us better understand your proposed enhancement request. Going to close this issue for now, but feel free to open another one with more detail.
