### ISSUE TITLE
API: make DTA/DTI == string behavior match DTI.get_loc partial-string-matching?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#35197]
In most cases, there is a relationship between `index.get_loc` and `index.__eq__`.  `index.get_loc(key)` roughly matches `(index == key).nonzero()`

`DatetimeIndex.get_loc` has special treatment for strings that we could extend to DatetimeIndex (and DatetimeArray) `__eq__`.

```
>>> dti = pd.date_range("2016-01-01 20:00", periods=10, freq="H")
>>> s = "2016-01-01
>>> dti.get_loc(s)
slice(0, 4, None)
>>> dti == s
array([False, False, False, False, False, False, False, False, False, False])
```

Under this proposal, the last comparison here would give `array([True, True, True, True, False, False, False, False, False, False])`

The main benefit of this would be internal consistency.  Possibly some code sharing, but I'm not ready to make any promises on that front.

**Comment by jorisvandenbossche** [comment]
In general, I think `==` should mean equality, and not a partial match. So IMO this would be confusing/unexpected. If we think such a partial match functionality is useful, I would rather add a new method for it specific to datetimes.
