### ISSUE TITLE
BUG: Inconsistent behavior in Index.difference

### ISSUE THREAD

**Issue by galipremsagar** [pandas-dev/pandas#35217]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

`Index.difference` seems to be treating float vs object / int vs object differently.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
float_index = pd.Index([1.0, 2, 3])
string_index = pd.Index(['1','2','3'])
integer_index = pd.Index([1, 2, 3])
print(float_index.difference(string_index))
print(string_index.difference(float_index))

print(integer_index.difference(string_index))
print(string_index.difference(integer_index))


Float64Index([], dtype='float64')
Index([], dtype='object')
Int64Index([1, 2, 3], dtype='int64')
Index(['1', '2', '3'], dtype='object')
```

#### Problem description
Index.difference should probably not type-cast and compare the elements to honor consistent behavior with other types where they are not being type-casted.

#### Expected Output

```python
Float64Index([1.0, 2.0, 3.0], dtype='float64')
Index(['1', '2', '3'], dtype='object')
Int64Index([1, 2, 3], dtype='int64')
Index(['1', '2', '3'], dtype='object')
```

or 

All empty Index objects like in case of int vs object.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None

pandas           : 1.0.5
numpy            : 1.19.0
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 49.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
None

</details>

**Comment by galipremsagar** [comment]
After going through code this looks like an issue with `Index.equals`:

```python
import pandas as pd
float_index = pd.Index([1.0, 2, 3])
string_index = pd.Index(['1','2','3'])
integer_index = pd.Index([1, 2, 3])
print(float_index.equals(string_index))
print(string_index.equals(float_index))

print(integer_index.equals(string_index))
print(string_index.equals(integer_index))

True
True
False
False
```

**Comment by renan-alonkin** [comment]
Hello There. I see that the issue was closed, but I'm still having this problem. I have a column called "Serial", and I'm trying to merge two DataFrames Together. The problem is: I have a few elements in both DataFrames with special characters (let me give you guys an example, one of the serial numbers is "#AUTO_451432HH0YH50"). 

Every time that it encounters those elements with special characters, the merge doesn't work for them, it says that they are not equal for some reason;

I can provide the data if necessary.
