### ISSUE TITLE
DOC: remove Bug Fix / Other section in whatsnew in favor of correct placement of issues

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#35276]
*very* few of the current whatsnew notes in Bug Fixes / Other actually belong. Should move everything out.

**Comment by leeyspaul** [comment]
Hello! 

Happy to take this up. Would you be able to link the section? Also, would you be able to clarify if moving everything out means deletion or movement to another section?

Thank you!

**Comment by TomAugspurger** [comment]
Thanks @leeyspaul. This one required some familiarity with the changes so I did it in https://github.com/pandas-dev/pandas/pull/35329.

We have plenty of other good first issues if you're interested: https://github.com/pandas-dev/pandas/labels/good%20first%20issue
