### ISSUE TITLE
ENH: Implement PandasArray.equals

### ISSUE THREAD

**Issue by kuraga** [pandas-dev/pandas#35283]
Feature request: implement `PandasArray.equals` for consistency (in addition to `Series.equals` and `DataFrame.equals`).

**Comment by TomAugspurger** [comment]
Can you share a bit more about your motivation? Are you writing code that's generic across Series, DataFrame, and ExtensionArrays?

EAs tend to be more similar to ndarrays, which don't have a `.equals` method.

**Comment by kuraga** [comment]
For coherence. Feel free to close.

**Comment by TomAugspurger** [comment]
I think we'll pass on this until there's a more compelling reason to add it.
