### ISSUE TITLE
BUG: upsampling returns less rows than expected

### ISSUE THREAD

**Issue by rwijtvliet** [pandas-dev/pandas#35293]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

I have a pandas Series with a (tz-localized) DateTimeIndex with one value per day, which I want to upsample to hourly values, so that each value is repeated 24 times (or 23 or 25, depending on summer/wintertime changeover).

```python
s = pd.Series([1,2,3,4], index=pd.date_range('2020-03-28 00:00:00', periods=4, freq='D', tz='Europe/Berlin'))
r = s.resample('H').ffill() #misses the last 23 hours of March
```
```
s:
2020-03-28 00:00:00+01:00    1
2020-03-29 00:00:00+01:00    2
2020-03-30 00:00:00+02:00    3
2020-03-31 00:00:00+02:00    4
Freq: D, dtype: int64

r:
2020-03-28 00:00:00+01:00    1
2020-03-28 01:00:00+01:00    1
2020-03-28 02:00:00+01:00    1
                            ..
2020-03-30 22:00:00+02:00    3
2020-03-30 23:00:00+02:00    3
2020-03-31 00:00:00+02:00    4  #<-- !
Freq: H, Length: 72, dtype: int64
```

#### Problem description

Each row in series `s` has the correct number of corresponding rows in series `r` - expect for the final row. The final row in `s` has only 1 corresponding row in `r`, where 24 would be expected.

#### Additional information / observations

a)

I've tried various combinations of having the original and/or the resampled timeseries be open or closed on the right side, but no setting gave me the wanted result.

b)

I assume the reason for the observed behaviour in `r`, above, is the following: I suppose that `freq == D` on a `DatetimeIndex` means, that the values are spaced one calendar day apart, and not, that they are valid for the entire calender day. Using a `PeriodIndex` instead does indeed solve this, see below.

However, using a `PeriodIndex` instead of a `DateTimeIndex` is not an option. It solves the problem with the missing hours, but loses the timezoneawareness that I need:
```python
s2 = pd.Series(s.values, pd.PeriodIndex(s.index, freq='D')) #misses timezoneawareness.
r2 = s2.resample('H').ffill() #does not miss last 23 hours of March, but is still incorrect.
```
```
s2:
2020-03-28    1
2020-03-29    2
2020-03-30    3
2020-03-31    4
Freq: D, dtype: int64

r2:
2020-03-28 00:00    1
2020-03-28 01:00    1
2020-03-28 02:00    1
                   ..
2020-03-31 21:00    4
2020-03-31 22:00    4
2020-03-31 23:00    4
Freq: H, Length: 96, dtype: int64
```

c)

Full disclosure: I've asked this questions before, on [stackoverflow](https://stackoverflow.com/questions/61761237/keep-24h-for-each-day-when-resampling-pandas-series-from-daily-to-hourly), but did not receive a satisfactory answer - just a workaround.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.2.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en
LOCALE           : de_DE.cp1252

pandas           : 1.0.5
numpy            : 1.18.5
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 49.2.0.post20200714
Cython           : None
pytest           : 5.4.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.16.1
pandas_datareader: None
bs4              : 4.9.1
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.3
numexpr          : None
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.4.1
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.17
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by CloseChoice** [comment]
Interestingly, the values are distributed unevenly:

```
r.groupby(r.values).count()
Out[8]: 
1    24
2    23
3    24
4     1
dtype: int64```

**Comment by rwijtvliet** [comment]
Thanks for looking into this; I think you are right!

The root cause here is that I'm trying to use DatetimeIndex'ed timeseries to describe data that actually should be PeriodIndex'ed. That causes ugly unwanted effects and the need to repair them; I've abstracted the functionality away in the function
```
def resample(s, freq):
    s_temp = pd.Series([None], [s.index[-1]+s.index.freq])
    return pd.concat([s, s_temp]).resample(freq).ffill().dropna()
```

I think timezone-awareness for periods would be a great addition ;)

**Comment by rwijtvliet** [comment]
I'm considering implementing something like this, though I'm a bit wary it might be beyond my current capabilities. Still, [have a look at the project](https://github.com/rwijtvliet/spandas) and leave some feedback if you want; it's much appreciated!
