### ISSUE TITLE
ENH: pandas.DataFrame.pivot option to output hierarchically indexed rows

### ISSUE THREAD

**Issue by rchurt** [pandas-dev/pandas#35313]
#### Is your feature request related to a problem?
When I use `pivot` or `pivot_table` and pass a list of `values`, I get a multiindex on the columns, as the docs say. However, in my case I want the output to be hierarchically indexed by rows.

#### Describe the solution you'd like

It would be nice to have a `indexing_axis` kwarg in `pivot` and `pivot_table` so I could pass `indexing_axis='rows'` and get a multiindex on the rows instead of on the columns.

#### Describe alternatives you've considered

Can be fixed by running `df_pivoted.stack()`, but it would be nice to not have to do this as a separate step.

```python
df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
                         "bar", "bar", "bar", "bar"],
                   "B": ["one", "one", "one", "two", "two",
                         "one", "one", "two", "two"],
                   "C": ["small", "large", "large", "small",
                         "small", "large", "small", "small",
                         "large"],
                   "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
                   "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})

df_pivoted = df.pivot_table(index=['A','C'], columns='B', values=['D','E'])
# df_pivoted = df.pivot_table(index=['A','C'], columns='B', values=['D','E'], indexing_axis='rows') # this is what I want to be able to do

df_pivoted.stack() # this is what I want the result to look like

```

**Comment by TomAugspurger** [comment]
Can you provide a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by rchurt** [comment]
@TomAugspurger sorry for the delay, but I just updated the issue to include more info

**Comment by mroeschke** [comment]
Thanks for the suggestion, but generally we're not keen on expanding the API signature of functions especially if there is a reasonable, alternative way of achieving the result (namely the idiomatic chaining of methods in this example).

Going to close this issue for now, but happy to reopen if we gain more interest for this feature from the community
