### ISSUE TITLE
DOC: Unable to install pre-release

### ISSUE THREAD

**Issue by ginward** [pandas-dev/pandas#35336]
#### Location of the documentation

["https://github.com/pandas-dev/pandas/releases/tag/v1.1.0rc0"]

#### Documentation problem

It seems that I am not able to install the v1.1.0 version of the Pandas package using the following commands: 

```
python -m pip install --upgrade --pre pandas==1.1.0rc0

conda install -c conda-forge/label/rc pandas==1.1.0rc0

```

It says that: 

PackagesNotFoundError: The following packages are not available from current channels:

  - pandas==1.1.0rc0

Current channels:

```
  - https://conda.anaconda.org/conda-forge/label/rc/osx-64
  - https://conda.anaconda.org/conda-forge/label/rc/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
```

**Comment by ginward** [comment]
Only the following command seems to work for me: 

`https://github.com/pandas-dev/pandas/releases/download/v1.1.0rc0/pandas-1.1.0rc0.tar.gz`

**Comment by simonjayhawkins** [comment]
Thanks @ginward for the report

The wheels for 1.1.0rc0 are not yet uploaded. The install instructions should be working shortly (when the release is officially announced; the github release always happens a bit earlier, since it is required for other release tasks)

**Comment by ginward** [comment]
Ok thanks!
