### ISSUE TITLE
BUG: np.argwhere on pandas series

### ISSUE THREAD

**Issue by rossbar** [pandas-dev/pandas#35331]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

numpy/numpy#15555 reports an issue with `np.argwhere` on pandas Series. Reporting here for visibility.

MRE:
```python
>>> import numpy as np
>>> import pandas as pd
>>> s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
>>> np.argwhere(s < 0)
```
which, with `numpy.__version__ ==1.20.0.dev0+046a736`  gives:
**pd.__version__ == 0.25.3:**
```
FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
array([[3]])
```
**pd.__version__ == 1.0.5:**
```
ValueError: Length of passed values is 1, index implies 5.
```

**Comment by simonjayhawkins** [comment]
Thanks @rossbar for drawing our attention to this issue.

**Comment by ArchangeGabriel** [comment]
I’ve run into this while trying to execute a code that used to work back in 2019. The workaround for anyone stumbling upon this is thus to `.to_numpy()` the series in the `np.argwhere()` call, e.g. for the above example:
```python
>>> np.argwhere(s.to_numpy() < 0)
```

**Comment by mroeschke** [comment]
This looks to work on main now. Could use a test

```
In [18]: >>> import numpy as np
    ...: >>> import pandas as pd
    ...: >>> s = pd.Series(range(5), index=['a', 'b', 'c', 'd', 'e'])
    ...: >>> np.argwhere(s < 3)
Out[18]: 
array([[0],
       [1],
       [2]])
```

**Comment by mcgeestocks** [comment]
I can jump in and add a test for this.
