### ISSUE TITLE
DOC: expand "using a Docker container" section

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#35345]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#using-a-docker-container
#### Documentation problem

Someone unfamiliar with Docker would be confused reading this.

#### Suggested fix for documentation

The expansion needed is quite small, just:

1. link to the Docker installation instructions
2. link to how to develop in a container using PyCharm (current docs only link to vs code instructions)
3. mention that you might still need to rebuild the C extensions if/when you merge with upstream/master with
   ```
   python setup.py build_ext --inplace -j 4
   ```

**Comment by alexhlim** [comment]
I was able to find links for the [docker installation](https://docs.docker.com/get-docker/) and developing in a container using [PyCharm](https://www.jetbrains.com/help/pycharm/using-docker-as-a-remote-interpreter.html?_ga=2.260919181.1086065302.1595331195-1975408772.1595110607). However, I notice this feature is only for PyCharm Professional, is it still worth including this link?

**Comment by MarcoGorelli** [comment]
Sure, go ahead! I've assigned you, but in the future if you comment "take" then the issue will be automatically assigned to you
