### ISSUE TITLE
QST: How to provide regular expression in na_values ?

### ISSUE THREAD

**Issue by Vishnuhp01** [pandas-dev/pandas#35354]
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [x] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
# Your code here, if applicable

```

**Comment by Vishnuhp01** [comment]
KM | FuelType | HP | MetColor
-- | -- | -- | --
46986 | Diesel | 90 | 1
72937 | Diesel | 90 | 1
41711 | Diesel | 90 |  
48000 | Diesel | 90 | 0
38500 | Diesel | 90 | 0
61000 | Diesel | 90 | 0
?? | Diesel | ???? |  
75889 |   | 90 | 1
19700 | Petrol | 192 | 0
71138 | Diesel | ???? |  

For this type of data what if I want to replace '??' and '????' to a NAN?
It is easy if there is only '?' and '????' but what if we have inconsistent no. of '?' ?

**Comment by simonjayhawkins** [comment]
@Vishnuhp01 can you provide the code you have tried and the output your getting and please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

**Comment by Vishnuhp01** [comment]
I've tried this

`data = pd.read_csv('./CarData.csv', na_values=['??','????'])`

and got this as an output


KM | FuelType | HP | MetColor
-- | -- | -- | --
46986 | Diesel | 90 | 1
72937 | Diesel | 90 | 1
41711 | Diesel | 90 | NaN
48000 | Diesel | 90 | 0
38500 | Diesel | 90 | 0
61000 | Diesel | 90 | 0
NaN | Diesel | NaN | NaN  
75889 | NaN  | 90 | 1
19700 | Petrol | 192 | 0
71138 | Diesel | NaN | NaN  

But I want to use the regex for the '?'s which is '?+'.

**Comment by simonjayhawkins** [comment]
AFAIK, `pd.read_csv` doesn't accept a regex,  from https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.read_csv.html

> na_values: scalar, str, list-like, or dict, optional
>   Additional strings to recognize as NA/NaN. If dict passed, specific per-column NA values. By default the following values are 
>   interpreted as NaN: ‘’, ‘#N/A’, ‘#N/A N/A’, ‘#NA’, ‘-1.#IND’, ‘-1.#QNAN’, ‘-NaN’, ‘-nan’, ‘1.#IND’, ‘1.#QNAN’, ‘<NA>’, ‘N/A’, 
>   ‘NA’, ‘NULL’, ‘NaN’, ‘n/a’, ‘nan’, ‘null’.


`DataFrame.replace`, https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.replace.html however allows a regex to be specified.

**Comment by viipul** [comment]
data= data.replace(to_replace =float('NaN'), value = '??', regex = True) 
This is giving expected ouput.

**Comment by MarcoGorelli** [comment]
Closing as I don't see there being much to do here
