### ISSUE TITLE
BUG: multiindex slice 1.1.0rc0

### ISSUE THREAD

**Issue by leo4183** [pandas-dev/pandas#35351]
mulitindex slicing returns different (from pandas<=1.0.x) results in pandas 1.1.0rc0

```
df = pd.DataFrame( data=[[0,1,'a',1],[1,0,'a',0],[1,1,'b',1],[1,1,'c',2]], columns=['index','date','author','price'] )

# to keep the most recent date for every index (could happen in practice)
idx = df.drop_duplicates('index',keep='last').set_index(['index','date']).index 

df.set_index(['index','date']).loc[idx,:].reset_index()
```

df

 index | date  | author | price
-- | -- | -- | --
0|1|a | 1
1|0|a | 0
1|1|b | 1
1|1|c | 2

Result

  | | author | price
 -- | -- | --
(0, 1) | a | 1
(1, 1) | b | 1
(1, 1) | c | 2

**Comment by TomAugspurger** [comment]
What's the output for 1.0.5?

**Comment by leo4183** [comment]
for pandas<=1.0.x, the results would look like (as expected):

index | date | author | price
-- | -- | -- | --
0 | 1 | a | 1
1 | 1 | b | 1
1 | 1 | c | 2

**Comment by simonjayhawkins** [comment]
The output was good in 1.0.1, bisecting now.

**Comment by simonjayhawkins** [comment]
#33691 appears to be the cause of the regression, labelled 1.1

73fd8a797dc45ab1ced1c1712e04852d8d4a7d09 is the first bad commit
commit 73fd8a797dc45ab1ced1c1712e04852d8d4a7d09
Author: jbrockmendel <jbrockmendel@gmail.com>
Date:   Tue Apr 21 19:31:36 2020 -0700

    CLN: remove shallow_copy_with_infer (#33691)

cc @jbrockmendel

**Comment by simonjayhawkins** [comment]
slight refactor of OP to clearly show the issue.

```
>>> pd.__version__
'1.1.0rc0'
>>>
>>> df = pd.DataFrame(
...     data=[["a", 1], ["a", 0], ["b", 1], ["c", 2]],
...     columns=["author", "price"],
...     index=pd.MultiIndex.from_tuples(
...         [(0, 1), (1, 0), (1, 1), (1, 1)], names=["index", "date"]
...     ),
... )
>>> df
           author  price
index date
0     1         a      1
1     0         a      0
      1         b      1
      1         c      2
>>>
>>> idx = pd.MultiIndex.from_tuples([(0, 1), (1, 1)], names=["index", "date"])
>>> idx
MultiIndex([(0, 1),
            (1, 1)],
           names=['index', 'date'])
>>>
>>> df.loc[idx, :]
       author  price
(0, 1)      a      1
(1, 1)      b      1
(1, 1)      c      2
>>>
>>> _.index
Index([(0, 1), (1, 1), (1, 1)], dtype='object')
>>>
```
