### ISSUE TITLE
to_sql functionality not working on python

### ISSUE THREAD

**Issue by cdu2620** [pandas-dev/pandas#35352]
Whenever I try to insert a pandas DF into my database, I get this error:
<img width="844" alt="Screen Shot 2020-07-20 at 11 13 28 AM" src="https://user-images.githubusercontent.com/48495622/87954278-255e9d80-ca7a-11ea-90aa-12316ef8b105.png">

It happens with any dataframe I try, even dataframes I had successfully inserted before. The specific test dataframe I was trying to insert is this:
<img width="208" alt="Screen Shot 2020-07-20 at 11 14 49 AM" src="https://user-images.githubusercontent.com/48495622/87954346-41623f00-ca7a-11ea-9ba6-04b1e3709c1e.png">

**Comment by TomAugspurger** [comment]
See http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports for writing bug reports.

**Comment by simonjayhawkins** [comment]
Thanks @cdu2620 for the report. can you update the OP using the bug report template (available when raising an issue but repeated in details below)

<details>
- [ ] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here

```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Expected Output

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>
</details>

**Comment by MarcoGorelli** [comment]
Closing as it's not clear how to reproduce this, but please do ping if you write a bug report as suggested above
