### ISSUE TITLE
DOC: `to_pickle` arguments for `compression` have a mistake (easy-fix)

### ISSUE THREAD

**Issue by ianozsvald** [pandas-dev/pandas#35364]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_pickle.html

#### Documentation problem

`compression{‘infer’, ‘gzip’, ‘bz2’, ‘zip’, ‘xz’, None}, default ‘infer’` notes that `gzip` is a valid extension, this is wrong, the extension checked for is `gz`. The documentation for `to_csv` is correct with `... detect compression mode from the following extensions: ‘.gz’, ‘.bz2’, ‘.zip’ or ‘.xz’` and should act as a guide: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html

#### Suggested fix for documentation

`compression{‘infer’, ‘gz’, ‘bz2’, ‘zip’, ‘xz’, None}, default ‘infer’` to match the code implementation: https://github.com/pandas-dev/pandas/blob/v1.0.5/pandas/io/common.py#L223

There _may_ be an argument to extending the `_compression_to_extension` code to accept both `gzip` and `gz`for gzip compression, whoever reads this might decide this is worth escalating. For me making sure we fix the docs in line with the code is the priority.

**Comment by rhshadrach** [comment]
It's a bit confusing because `gzip` is the one compression type where the `mode` and the `extension` differ. The option compression *mode* is `gzip`. On the other hand, when `mode=infer`, the *extension* `gz` is looked for.

This is how `to_csv` works too:

 > Compression mode may be any of the following possible values: {‘infer’, ‘gzip’, ‘bz2’, ‘zip’, ‘xz’, None}. If compression mode is ‘infer’ and path_or_buf is path-like, then detect compression mode from the following extensions: ‘.gz’, ‘.bz2’, ‘.zip’ or ‘.xz’. (otherwise no compression). If dict given and mode is ‘zip’ or inferred as ‘zip’, other entries passed as additional compression options.

It seems to me having these details would be useful in the `to_pickle` docs as well.

**Comment by ianozsvald** [comment]
Thanks to @jreback for picking this up :+1:
