### ISSUE TITLE
BUG: to_parquet doesn't reliably support file:// URI

### ISSUE THREAD

**Issue by impredicative** [pandas-dev/pandas#35371]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
pd.__version__
'1.0.5'
df = pd.DataFrame()  # Any dataframe is fine for this issue.

df.to_parquet('file:///tmp/df.parquet')  # DOESN'T WORK! Raises urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: '/tmp/df.parquet'>
df.to_parquet('/tmp/df.parquet')  # Works fine.
df.to_parquet('file:///tmp/df.parquet')  # Works given that the file now exists.
```

#### Problem description

It is important to correctly support file URIs so users can interchangeably write to S3 or local files, both of which I represent as a URI. With Pandas 1.0.5, `to_parquet` works with a file URI only if the file already exists.

#### Expected Output

`to_parquet` should work with a file URI independent of whether the file already exists.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.4.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.3.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8
pandas           : 1.0.5
numpy            : 1.18.5
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 47.3.1.post20200622
Cython           : None
pytest           : 5.4.3
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : None
pandas_datareader: None
bs4              : 4.9.1
bottleneck       : None
fastparquet      : 0.4.1
gcsfs            : None
lxml.etree       : 4.5.1
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.4
pandas_gbq       : None
pyarrow          : 0.17.1
pytables         : None
pytest           : 5.4.3
pyxlsb           : None
s3fs             : 0.4.2
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : 0.50.1

</details>

**Comment by TomAugspurger** [comment]
Can you try with 1.1.0rc0? All of those works for me.

**Comment by impredicative** [comment]
I confirm that it works in 1.1.0rc0. I will remember to check any rc releases next time!
