### ISSUE TITLE
ENH: Collation argument to to_sql

### ISSUE THREAD

**Issue by MislavSag** [pandas-dev/pandas#35375]
#### Is your feature request related to a problem?

I would like to be able to set Collation when sending the data to sql table.

#### Describe the solution you'd like

Now when I use pandas function `to_sql` to send data to mysql I would use `df.to_sql(table_name, engine, if_exists='replace', index=False, chunksize=100)` where engine is pymsql engine. But this doesn't work if my data contains utf-8 (Croatian characters). It converts č and ć characters to ?. 

#### API breaking implications

It wouldn't affect API.

#### Describe alternatives you've considered

I tried to change collation manually.

**Comment by rhshadrach** [comment]
I think it is the database connection setting that you want to modify for supporting utf-8 rather than pandas. If this doesn't help, could you post a minimal reproducible example?

**Comment by MislavSag** [comment]
@rhshadrach , I have changed collation in the cpanel database settings. Now it is ok. Thanks.
