### ISSUE TITLE
BUG: Pandas Read_html can't get values from table td data-sort-values

### ISSUE THREAD

**Issue by riyadfebrian** [pandas-dev/pandas#35372]
- [ ✔] I have checked that this issue has not already been reported.

- [✔ ] I have confirmed this bug exists on the latest version of pandas.

---

#### URL Example

[https://en.wikipedia.org/wiki/Comparison_of_text_editors](https://en.wikipedia.org/wiki/Comparison_of_text_editors)
```python
df = pd.read_html(url, flavor='bs4')
```

#### Problem description

I'm trying to scrape first table from WIkipedia, the column 'Open Source' and 'CLI available' are displaying the data with ✔ images to refer 'Yes' and ❌ for 'No'.  if we inspect the HTML code.

```html
<td data-sort-value="Yes" style="background: #D2FFD2; color: black; vertical-align: middle; text-align: center;" class="table-yes2"><img alt="Yes" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/03/Green_check.svg/13px-Green_check.svg.png" decoding="async" title="Yes" width="13" height="13" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/03/Green_check.svg/20px-Green_check.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/03/Green_check.svg/26px-Green_check.svg.png 2x" data-file-width="600" data-file-height="600">
</td>
```
The value is embedded in `data-sort-value` but `pandas.read_html` maybe read the column value as image and return NaN

#### Output of ``pd.show_versions()``

<details>

commit           : None
python           : 3.8.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_Indonesia.1252

pandas           : 1.0.5
numpy            : 1.19.0
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 47.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.2
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.15.0
pandas_datareader: None
bs4              : 4.9.1
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.2
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by jbrockmendel** [comment]
> The value is embedded

I doubt we'll want to support having an HTML parser that can figure out how to get at embedded information like this.  You're better off using bs4 directly.

**Comment by TomAugspurger** [comment]
Agreed, read_html is mainly focused on relatively simple tables.
