### ISSUE TITLE
Drop similar rows of dataframe except for one column

### ISSUE THREAD

**Issue by paulthemagno** [pandas-dev/pandas#35383]
It seems a trivial question, but I don't find anything on the web. I have a dataframe with **inconsistent rows**. In the example below `primary_key` is the primary key so it has to be once in dataset, while `info` is an information of `primary_key`. While for **exactly repeated rows** I want to keep only one of them using a function like `df.drop_duplicates(keep = 'first')`, I don't know which keep in the case in which primary keys (`primary_key`) are the same so refer to the same item, but `info` is different, because they are inconsistent information. In this case I'd like to remove all of these rows with a function like `df.drop_duplicates(subset = "primary_key" , keep = False)`. I don't know how to do this kind of filter because I want to keep 1 row if one case and 0 rows in the other, depending on the values of a specific column within groups of _similar rows_.
 
### Desired behaviour
In:
```bash
     primary_key    info
0    a              1 
1    a              1 #duplicated row of index 0
2    a              2 #similar row of indexes 0 and 1 but inconsistent with info field
3    b              1 
4    b              1 #duplicated row of index 3
```

Out:
```bash
     primary_key    info
1    b              1  #the only primary key with the same value on info field
```

Thank you

**Comment by erfannariman** [comment]
To only use the vectorized methods and prevent us from using `GroupBy.apply`, we can do the following:

```python
m = df.groupby('primary_key')['info'].nunique().eq(1)
dfn = df[df['primary_key'].map(m)].drop_duplicates()
print(dfn)

  primary_key  info
3           b     1
```

So basically the method you were looking for was `nunique`

**Comment by paulthemagno** [comment]
Thank you very much @erfannariman. It works. I ask you a little modification of this. If i I had 2 possible values in `info` and I wanted to keep the one with the highest frequency, removing all the entries only in the case in which the 2 possible values appear with the same frequency, how could I update the code?

**Comment by MarcoGorelli** [comment]
Just FYI - it's great that @erfannariman has kindly answered your question this time, but in general it's encouraged to ask usage questions on StackOverflow, which is where I'd like to encourage you to ask your second question

Closing for now then (to keep the issue tracker more focused on requests / bugs), but please do ping if you think there's a bug / missing feature here
