### ISSUE TITLE
Display dataframe name or title when using display()

### ISSUE THREAD

**Issue by spizwhiz** [pandas-dev/pandas#35387]
Requesting ability to display name of dataframe above dataframe when using display(df)

I have tried df.name = "Name"

and display(df, display_id = "Name")

Neither results in any kind of identifier for the dataframe when using the display() function in Jupyter Notebook.

**Comment by rhshadrach** [comment]
There is no `name` attribute on a DataFrame. While you can attach such an attribute, be aware that it will be lost on many operations such as

    df = df.set_index('idx')

The `display_id` parameter to IPython's `display` is for updating a display later via a handle; it does not alter the contents of the display.

However the index of DataFrame does have a name attribute. Perhaps this suits your needs?

````
df = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
df.index.name = 'My DataFrame'
display(df)
````

Output:

![image](https://user-images.githubusercontent.com/45562402/88485919-0f544f80-cf48-11ea-9e87-8a65b5af2f42.png)

**Comment by spizwhiz** [comment]
@rhshadrach thanks!  This does suit my needs.

**Comment by rhshadrach** [comment]
@spizwhiz: Apologies, I had written `index` where I had meant `columns`. When doing operations with DataFrames, pandas will align on the index, so it is better to not set the index name purely for display purposes. Using columns is safer.

**Comment by spizwhiz** [comment]
@rhshadrach  got it, thanks for the clarification.
