### ISSUE TITLE
QST:  DatetimeIndex changes

### ISSUE THREAD

**Issue by mboldin-temple** [pandas-dev/pandas#35390]
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

In version 1.0.5, DatetimeIndex seems greatly changed from earlier versions 
Was this intentional and documented in the version changes?

Many statsmodels  forecasting steps now break
 
For example, the code below no longer works

dx = pd.DatetimeIndex(start ='2020-01-01 00:00', freq ='M',  periods = 12)

I get
 TypeError: __new__() got an unexpected keyword argument 'start'

The documentation has these arguments 

 class pandas.DatetimeIndex(data=None, freq=None, tz=None, normalize=False, closed=None, ambiguous='raise', dayfirst=False, yearfirst=False, dtype=None, copy=False, name=None)[source]

with little explanation or usefulness IMHO 

I see old Pandas has 
def __new__(cls, data=None,
                freq=None, start=None, end=None, periods=None, tz=None,
                normalize=False, closed=None, ambiguous='raise',
                dayfirst=False, yearfirst=False, dtype=None,
                copy=False, name=None, verify_integrity=True): 

```python

# Your code here, if applicable
# Create the DatetimeIndex 
dx = pd.DatetimeIndex(start ='2020-01-01 00:00', freq ='M',  periods = 12)
## expect TypeError: __new__() got an unexpected keyword argument 'start'

```

**Comment by mboldin-temple** [comment]
I see now it is documented in What's New
Removed the previously deprecated keywords “start”, “end”, and “periods” from the DatetimeIndex, TimedeltaIndex, and PeriodIndex constructors; use date_range(), timedelta_range(), and period_range() instead (GH23919)

and date_range() works as I need it 

Still some statsmodels routines  will fail when expecting to use start= as a keyword

**Comment by jreback** [comment]
these were deprecated in 0.24.0 and removed in 1.0.x. you should push statsmodels to update this.

**Comment by jreback** [comment]
xref https://github.com/pandas-dev/pandas/pull/23919
