### ISSUE TITLE
Random Sample Not Working

### ISSUE THREAD

**Issue by TanushGoel** [pandas-dev/pandas#35395]
I think there's an issue with the sample function. It displays the randomized dataframe with a different heading, but when you actually get the value of the dataframe at a certain index, it displays the same value as before the random sample.

<img width="651" alt="Screen Shot 2020-07-23 at 9 30 38 AM" src="https://user-images.githubusercontent.com/47517229/88312776-68fa1700-ccc7-11ea-94fc-00087cc743e7.png">

<img width="693" alt="Screen Shot 2020-07-23 at 9 31 49 AM" src="https://user-images.githubusercontent.com/47517229/88312788-6dbecb00-ccc7-11ea-9a6a-353951e56fca.png">

How can I fix this?

**Comment by TomAugspurger** [comment]
The `.text[0]` looks up the value with the label `0`, which is the original first row. You might want `.iloc[0]`
