### ISSUE TITLE
BUG: When plotting a pandas dataframe year is wrong

### ISSUE THREAD

**Issue by smeznaric** [pandas-dev/pandas#35413]
- [ x] I have checked that this issue has not already been reported.

- [x ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
import matplotlib.pyplot as plt

# Save the attached file somewhere and open it as follows
file_name = 'your_path'
df = pd.read_csv(file_name, index_col = 'date', parse_dates = True)
df.plot()

plt.show()

```

#### Problem description

The year is displayed as in 3900s. See picture:

![image](https://user-images.githubusercontent.com/28095296/88466980-e68d7500-cec9-11ea-9155-3400112e7c01.png)

I have noticed a few things:

- Generating random data and keeping the index the same does not resolve the issue
- Trying to recreate the index from scratch but using the same date does not resolve the issue
- Plotting using plotly backend resolves the issue
- Doing df.to_period('D').plot() also seems to resolve the issue

#### Expected Output

Year should not be in 3900s.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.104-microsoft-standard
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.5
numpy            : 1.19.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 44.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.16.1
pandas_datareader: 0.9.0
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.2
matplotlib       : 3.3.0
numexpr          : 2.7.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : None
tables           : 3.6.1
tabulate         : None
xarray           : 0.16.0
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by smeznaric** [comment]
I've uploaded an example CSV file to generate the above.

[example.zip](https://github.com/pandas-dev/pandas/files/4976657/example.zip)

**Comment by MarcoGorelli** [comment]
Thanks for the report - could you please write a reproducible example? See https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by misantroop** [comment]
Matplotlib 3.3 introduced modifications to the datetime conversion. Update pandas, NumPy and Matplotlib to latest builds and see if issue persists.

**Comment by brooketalcott** [comment]
I am on MPL v3.3.0 and having the same problem when reading CSVs

**Comment by brooketalcott** [comment]
I was having the same problem, updating from Pandas 1.0.5 to 1.1.0 fixed it for me, thanks for the suggestions @misantroop

**Comment by TomAugspurger** [comment]
Thanks for confirming that it's fixed @brooketalcott.

**Comment by smeznaric** [comment]
Thanks everyone, I can also confirm that it works with 1.1.0.
