### ISSUE TITLE
CI/COMPAT: read_stata failing in numpy dev pipeline

### ISSUE THREAD

**Issue by AlexKirko** [pandas-dev/pandas#35426]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [X] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Problem description

Looks like a change in numpy broke our `read_stata` code, so now we have a bunch of `read_stata` test errors popping up during CI in the numpy_dev pipeline. Maybe this [Numpy PR](https://github.com/numpy/numpy/pull/16943) somehow broke things? I don't think any other PR merged during the last 24 hours could have possibly done so, although I might be missing something.

Error example:
```
pandas/tests/io/test_stata.py:52: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pandas/io/stata.py:1928: in read_stata
    data = reader.read()
pandas/io/stata.py:1646: in read
    cols_ = np.where(self.dtyplist)[0]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = ([<class 'numpy.int8'>, <class 'numpy.int16'>, <class 'numpy.int32'>, <class 'numpy.float32'>, <class 'numpy.float64'>, <class 'numpy.float32'>, ...],)
kwargs = {}
relevant_args = ([<class 'numpy.int8'>, <class 'numpy.int16'>, <class 'numpy.int32'>, <class 'numpy.float32'>, <class 'numpy.float64'>, <class 'numpy.float32'>, ...], None, None)

>   ???
E   ValueError: invalid __array_struct__
```

**Comment by jreback** [comment]
cc @bashtage

**Comment by bashtage** [comment]
That is a NumPy bug.  numpy/numpy#16939

**Comment by bashtage** [comment]
Fixed it anyway.  No reason to create an array of dtypes.

**Comment by AlexKirko** [comment]
@bashtage , thanks!
Looks like there are still a bunch of places where we create an array of dtypes and then assign them to a numpy array with something like `result[:] = values`.

**Comment by AlexKirko** [comment]
@jreback should we alter this issue to incorporate other test fails (basically anywhere we create a list of dtypes and assign it to a numpy array) or open a new issue?

**Comment by TomAugspurger** [comment]
We've already opened an issue upstream: https://github.com/numpy/numpy/issues/16939

**Comment by simonjayhawkins** [comment]
closing in favour of #35481 as Stata tests no longer failing
