### ISSUE TITLE
Support reading YAML files

### ISSUE THREAD

**Issue by janosh** [pandas-dev/pandas#35421]
Would be cool if pandas supported reading YAML files.

#### Describe the solution you'd like

`pd.read_yaml(file_path: str, **kwargs: dict)`

#### API breaking implications

None

#### Describe alternatives you've considered

You can of course import the `yaml` module, use it to read the file and then feed that data into pandas.

```py
import pandas as pd
import yaml

with open("data.yml") as stream:
    data = yaml.safe_load(stream)

df = pd.DataFrame(data)
```

But for a format that has become as widely used as YAML, this is a lot of manual work compared to

```py
import pandas as pd

df = pd.read_yaml("data.yml")
```

**Comment by TomAugspurger** [comment]
This feels out of scope since there's no builtin YAML parser and I tend to see YAML used for much more than simple tabular datasets.

**Comment by WillAyd** [comment]
I agree with Tom. there may be some niche applications but I am not aware of people generally storing tabular data in yaml

**Comment by janosh** [comment]
@TomAugspurger & @WillAyd: Thanks for the quick replies. I take your points.

Just wanted to mention though that YAML being fairly niche, especially in the realm of data storage, may change in the future. In fact, a number of document databases built around YAML have already popped up (e.g. [Netlify CMS](https://www.netlifycms.org), [YAML DB](http://blog.varunajayasiri.com/yamldb)).

Admittedly, this is mostly unrelated to Pandas. But while YAML may never surpass JSON for data storage, overall it's certainly picking up steam much faster. Going by Google trends, interest in YAML over the past 5 years has increased fourfold, going from 4 to 16 (in arbitrary units). By comparison, JSON over that same period went from 72 to 93.

![yaml-vs-json](https://user-images.githubusercontent.com/30958850/88577504-67be4680-d047-11ea-8981-6d4c05e5f865.png)

**Comment by mroeschke** [comment]
Thanks for the suggestion, but agreed I think yaml has been good for configurations formats but not necessarily storing tabular datasets. Since there hasn't been much support from the core devs for this enhancement going to close, but happy to reopen if there is a revived interest from the core team and community.
