### ISSUE TITLE
DOC: Can't find mention of DataFrame accepting namedtuples as input

### ISSUE THREAD

**Issue by sjvrijn** [pandas-dev/pandas#35438]
#### Location of the documentation

User guide ['Intro to data structures'](https://pandas.pydata.org/docs/dev/user_guide/dsintro.html#dataframe)
(alternatively [`DataFrame` API docs](https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.html?highlight=dataframe#pandas.DataFrame))

#### Documentation problem

I recently only found out through a [StackOverflow answer](https://stackoverflow.com/a/51173794/) that the `DataFrame` constructor can take a list of namedtuples and automatically infers column names from it. Until then I had only found the [`DataFrame.from_records`](https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.from_records.html#pandas.DataFrame.from_records) constructor, which manually requires specifying `columns=Namedtuple._fields`.

After searching the documentation for [namedtuple](https://pandas.pydata.org/docs/dev/search.html?q=namedtuple), I haven't been able to find an explicit mention of constructors accepting namedtuples, while there is apparently explicit code in the constructor to deal with them nicely. Currently it only finds mentions where internal functions return rows as namedtuples.

In contrast, searching for e.g. ['dataclass'](https://pandas.pydata.org/docs/dev/search.html?q=dataclass) finds [an explicit paragraph](https://pandas.pydata.org/docs/dev/user_guide/dsintro.html?highlight=dataclass#from-a-list-of-dataclasses) listing the option.

#### Suggested fix for documentation

I would propose adding an explicit mention and/or example somewhere that these kinds of inputs are accepted/encouraged, such that they can be easily found when searching for the 'namedtuple' keyword.

I can write a similar paragraph as for dataclasses in the intro to data structures, if that is indeed the right place for this.

**Comment by TomAugspurger** [comment]
Thanks for the report. A note that we accept namedtuples would be welcome.
