### ISSUE TITLE
BUG: 'something' in pd.Series does not return the True when the object is contained.

### ISSUE THREAD

**Issue by soerendip** [pandas-dev/pandas#35442]
```python
import pandas as pd
df = pd.DataFrame(['Test', '123'])
'test' in df[0]
> False
```
I am not sure if this made on purpose, but I think this should return True. False seems a bit strange. Is there a good reason for this?

**Comment by mroeschke** [comment]
This is the expected behavior as `Series` objects are dict-like, so this is expected (`'test'` is not in the index)

See: https://pandas.pydata.org/pandas-docs/stable/user_guide/dsintro.html#series-is-dict-like
