### ISSUE TITLE
Question/bug: How to get rid of "0 days" in timedelta64[s]

### ISSUE THREAD

**Issue by pllim** [pandas-dev/pandas#35463]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas. -- I can't tell if this is a feature or a bug.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
>>> import pandas as pd
>>> import numpy as np
>>> dt = pd.Series(np.array([1, 300], dtype='timedelta64[s]')) 
>>> df = pd.DataFrame({'dt': dt})
```
```python
>>> pd.__version__
'1.0.5'
>>> df
        dt
0 00:00:01
1 00:05:00
```
```python
>>> pd.__version__
'1.1.0'
>>> df
               dt
0 0 days 00:00:01
1 0 days 00:05:00
```

#### Problem description

"0 days" started to appear when DataFrame contains `timedelta64[s]`.

#### Expected Output

See "Code Sample" for `pandas` 1.0.5.

#### Output of ``pd.show_versions()``

See "Code Sample" for `pandas` 1.1.0.

#### Further readings

astropy/astropy#10608 and astropy/astropy#10609

**Comment by simonjayhawkins** [comment]
Thanks @pllim for the report. Not sure if this was an intentional change, so will mark as regression pending further investigation.

**Comment by simonjayhawkins** [comment]
It appears this was an intentional change, see tests changed in #33270

**Comment by pllim** [comment]
Wasn't expecting that in a minor release. Is there a way to get the old behavior back? If no, that's fine too, just want to know.

**Comment by simonjayhawkins** [comment]
@jbrockmendel

**Comment by jreback** [comment]
> Wasn't expecting that in a minor release. Is there a way to get the old behavior back? If no, that's fine too, just want to know.

minor release can and do have api changes - pls read the release notes

this was for conformity of timedelta outputs

**Comment by pllim** [comment]
I did glance at the notes but I guess I missed it. Okie dokie then.

**Comment by pllim** [comment]
Thanks for digging into this, @simonjayhawkins !
