### ISSUE TITLE
BUG: Inconsistent initialization of `timedelta64` between Series vs numpy & pd.TimeDelta

### ISSUE THREAD

**Issue by galipremsagar** [pandas-dev/pandas#35465]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

The creation of a pandas Series with any dtype other than `timedelta64[ns]` is discarding values and setting the entire series to `0`'s. Whereas `numpy.array` and `pd.TimeDelta` are correctly instantiating and preserving the passed values which can be retrieved by a type-cast too.

#### Code Sample, a copy-pastable example

```python
>>> import pandas as pd
>>> pd.__version__
'1.1.0'
>>> pd.Series([1000000, 200000, 3000000], dtype='timedelta64[ns]')
0   0 days 00:00:00.001000
1   0 days 00:00:00.000200
2   0 days 00:00:00.003000
dtype: timedelta64[ns]
>>> pd.Series([1000000, 200000, 3000000], dtype='timedelta64[s]')
0   0 days
1   0 days
2   0 days
dtype: timedelta64[ns]
>>> pd.Series([1000000, 200000, 3000000], dtype='timedelta64[s]').astype('int')
0    0
1    0
2    0
dtype: int64
>>> pd.Series([1000000, 200000, 3000000], dtype='timedelta64[ns]').astype('int')
0    1000000
1     200000
2    3000000
dtype: int64

>>> import numpy as np
>>> np.array([1000000, 200000, 3000000], dtype='timedelta64[ns]')
array([1000000,  200000, 3000000], dtype='timedelta64[ns]')
>>> np.array([1000000, 200000, 3000000], dtype='timedelta64[s]')
array([1000000,  200000, 3000000], dtype='timedelta64[s]')
>>> np.array([1000000, 200000, 3000000], dtype='timedelta64[s]').astype('int')
array([1000000,  200000, 3000000])

>>> pd.Timedelta(10)
Timedelta('0 days 00:00:00.000000010')
>>> pd.Timedelta(10, unit='s')
Timedelta('0 days 00:00:10')
>>> pd.Timedelta(10, unit='ns')
Timedelta('0 days 00:00:00.000000010')

```

#### Problem description

The expected behaviour is Series initialization must be in-line with numpy array initialization in this case.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : d9fff2792bf16178d4e450fe7384244e50635733
python           : 3.7.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
Version          : Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8
pandas           : 1.1.0
numpy            : 1.19.0
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 49.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by simonjayhawkins** [comment]
Thanks @galipremsagar for the report.

Further investigation and PRs welcome.

**Comment by simonjayhawkins** [comment]
I'll mark as a regression as this raised Exception in 0.25.3

```
>>> pd.__version__
'0.25.3'
>>>
>>> pd.Series([1000000, 200000, 3000000], dtype="timedelta64[s]")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\simon\Anaconda3\lib\site-packages\pandas\core\series.py", line 314, in __init__
    data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
  File "C:\Users\simon\Anaconda3\lib\site-packages\pandas\core\internals\construction.py", line 679, in sanitize_array
    subarr = _try_cast(data, dtype, copy, raise_cast_failure)
  File "C:\Users\simon\Anaconda3\lib\site-packages\pandas\core\internals\construction.py", line 784, in _try_cast
    subarr = maybe_cast_to_datetime(arr, dtype)
  File "C:\Users\simon\Anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 1035, in maybe_cast_to_datetime
    "dtype [{dtype}]".format(dtype=dtype)
TypeError: cannot convert timedeltalike to dtype [timedelta64[s]]
>>>
```

**Comment by galipremsagar** [comment]
So is the expected behavior to raise an exception or initialization similar to numpy?
