### ISSUE TITLE
ENH: data frame min/max and idxmin/idxmax

### ISSUE THREAD

**Issue by chrisvoncsefalvay** [pandas-dev/pandas#35474]
#### Is your feature request related to a problem?

I wish I could use an idxmax-like function to obtain the row and column coordinates of the minimum or maximum value.

#### Describe the solution you'd like

For a `DataFrame` object `df`, the proposed function `df.dfmin` would yield a tuple `(idx, col)` where `idx` would be the index of the minimum value (or a tuple of the hierarchical index's levels) and `col` the name of the column. For multiple equal values, a tuple of values could be returned.

#### API breaking implications

None.

**Comment by TomAugspurger** [comment]
Can you provide an example? I'm having trouble understanding, but this sounds like a `.groupby().idxmin()`.

**Comment by jbrockmendel** [comment]
I think what you're looking for is `df.stack().idxmax()`

```
df = pd.DataFrame(np.random.randn(5, 4), columns=["A", "B", "C", "D"])

>>> df.stack().idxmax()
(4, 'C')

>>> df.loc[4, "C"]
0.9770855399527882
>>> df.max().max()
0.9770855399527882
```

**Comment by MarcoGorelli** [comment]
closing, feel free to ping if you have a reproducible example which shows your expected output
