### ISSUE TITLE
ENH: Method on pd.Period to find the nth weekday in a period. 

### ISSUE THREAD

**Issue by smithto1** [pandas-dev/pandas#35472]
#### Is your feature request related to a problem?

It should be easy to find the nth weekday of period (usually a month). This kind of operation comes up all the time in financial contracts (i.e. futures and options expiring on the 3rd Wed of the month) and other use-cases (i.e. US election dates).

#### Describe the solution you'd like

Add an `nth_weekday` method to the `pd.Period` object to handle this operation. It could then be extended to the `PeriodArray`. 

`nth_weekday` should work forward and backwards with Pythonic-indexing (n=0 gives you date of first weekday, n=-1 gives you date of last weekday) 

`nth_weekday` should have a flag to to enforce that the returned date has to be inside the period, or if you let it go outside the period bounds. It should default to enforcing the period bounds. 

#### API breaking implications

This will add a new method to the `pd.Period`  and the `PeriodArray`. Proposed name is `nth_weekday` but that can be changed. It shouldn't have any other impact on the API. 

#### Describe alternatives you've considered

A general search of the internet did not find any convenient solution for this in all of Python. These looked like the best solutions available, and they're not great:
https://stackoverflow.com/questions/11883058/nth-weekday-calculation-in-python-whats-wrong-with-this-code
https://stackoverflow.com/questions/61106105/python-how-to-find-the-nth-weekday-of-the-year

#### Additional context

Below is a quick mock-up of the method (unoptimised, undocumented, but illustrates the functionality). 

```python

import pandas as pd

class Period_(pd.Period):
    def nth_weekday(self, n:int, weekday:int, within_period:bool=True) -> pd.Timestamp :
        
        assert weekday >= 0
        assert weekday <= 6
        
        if n >= 0:
            diff = weekday - self.start_time.weekday()
            diff += 7 if diff < 0 else 0            
            diff = diff + n * 7
            
            res = self.start_time + pd.Timedelta(days=diff)
            
            if within_period:
                if res > self.end_time:
                    res = pd.NaT
            return res
        
        if n < 0:
            diff = weekday - self.end_time.weekday()
            diff -= 7 if diff > 0 else 0
            diff = diff + (n+1) * 7
            
            res = self.end_time.normalize() + pd.Timedelta(days=diff)
            
            if within_period:
                if res < self.start_time:
                    res = pd.NaT
            return res
```

Some examples of use: 
```
# third Wednesday
Period_('2020-09', 'M').nth_weekday(n=2, weekday=2)

# first Friday
Period_('2020-09', 'M').nth_weekday(n=0, weekday=4)

# last Monday
Period_('2020-09', 'M').nth_weekday(n=-1, weekday=0)

# sixth Tuesday --> returns NaT when within_period=True 
Period_('2020-09', 'M').nth_weekday(n=6, weekday=1)

# sixth Tuesday --> returns a date in the next month if user explicitly 
# specifies within_period=False
Period_('2020-09', 'M').nth_weekday(n=6, weekday=1, within_period=False)

```

Some details would need to be ironed out on how to handle frequencies less than one day (i.e. an Hour). The mock example has some protection because `within_period` defaults to `True`, so any op that goes to a different day (not the day the hour occurrs on), it will return `NaT`. 

```
# Trying to shift from a smaller freq can return NaT
Period_('2020-01-01 15:00', 'H').nth_weekday(n=0, weekday=3)

Period_('2020-01-01 15:00', 'H').nth_weekday(n=1, weekday=2)
```

The mock still needs handling of corner cases: if you ask for the `n=0` instance of the day that the hour occurs on, you get the start_time back (rather than `NaT`). Will need to put in some thought for handling these corner cases. 

```
# This hour period occurs on a Wed. If I ask for the n=0 Wed of that Period, it gives me the start_time back. 
Period_('2020-01-01 15:00', 'H').nth_weekday(n=0, weekday=2)
```

I'm happy to work on this but wanted to raise an issue for discussion in case there already exists such a function somewhere (couldn't find one in the pandas docs) or if it has already been proposed and decided against.

**Comment by jreback** [comment]
we already have an offset for this which can easily work on the begin of a Period

pls give a try

**Comment by smithto1** [comment]
Ah cool, thanks.
