### ISSUE TITLE
ENH: Add different reference epochs for to_julian_date() as an argument

### ISSUE THREAD

**Issue by ioshchepkov** [pandas-dev/pandas#35487]
There are a lot of starting points (epochs), which leads to different modifications of the Julian date. It can help save memory and disk space in a very long time-series, because it will use less digits in the representation.

Good list: [https://en.wikipedia.org/wiki/Julian_day#Variants](https://en.wikipedia.org/wiki/Julian_day#Variants)

The use case will be something like this:

```python

tm = pd.Timestamp('2018-01-05')

tm_jd = tm.to_julian_date() # Julian Date

tm_mjd = tm.to_julian_date(kind='MJD') # Modified Julian Date

tm_tjd = tm.to_julian_date(kind='TJD') # Truncated Julian Date
```
I'm not sure about the name `kind=` and is it necessary to add arbitrary epoch as `pandas.Timestamp` object.

**Comment by jbrockmendel** [comment]
Isn't this kind of equivalent to adding more bits to the Timestamp representation?

**Comment by jbrockmendel** [comment]
I think this is a use case for a custom ExtensionArray, not likely something we'll implement internally

**Comment by mroeschke** [comment]
Thanks for the report, but there hasn't much core dev or community interest in the feature in a while so closing. Happy to reopen if there's renewed interest
