### ISSUE TITLE
DOC: pd.read_sql() connection disposal for str type connections 

### ISSUE THREAD

**Issue by AdamSpannbauer** [pandas-dev/pandas#35495]
This is in between a documentation issue and a general question.

#### Location of the documentation

[`pd.read_sql()`](https://github.com/pandas-dev/pandas/blob/v1.1.0/pandas/io/sql.py#L441-L443)

#### Documentation problem

The documentation notes that if the `con` is a `SQLAlchemy connectable` that the user is responsible for disposing/closing.  The documentation doesn't note whether the connection is closed if the user provides a `str` to the `con` parameter.  In my quick search, I couldn't find a reference to `.dispose()`/`.close()` in the source code when the user provides a `str` type `con`.  Is this connection being closed? Is it being left up to garbage collection as noted in [SQLAlchemy docs](https://docs.sqlalchemy.org/en/13/core/connections.html#engine-disposal)?

#### Suggested fix for documentation

I think a note about connection closure for `str` type `con`s would be a nice addition.  Right now, if I'm understanding correctly, the connection is being garbage collected and the user needs to infer from the docs that they don't need to worry about an open connection.

Current wording:

> The user is responsible for engine disposal and connection closure for the SQLAlchemy connectable.

Potential wording:

> The user is responsible for engine disposal and connection closure for the SQLAlchemy connectable; str connections are closed automatically.

**Comment by arw2019** [comment]
I *think* that's right. If I didn't make a mistake at the end of the day we connect to the database here:
https://github.com/pandas-dev/pandas/blob/bdcc5bffaadb7488474b65554c4e8e96a00aa4af/pandas/io/sql.py#L1159-L1163
and scrolling down the `SQLAlchemy` [doc page](https://docs.sqlalchemy.org/en/14/core/connections.html) you linked, at the bottom of the`Connectionless Execution, Implicit Execution` section:
```
the Connection is created behind the scenes; the CursorResult returned by the execute() call references the Connection 
used to issue the SQL statement. When the CursorResult is closed, the underlying Connection is closed for us, 
resulting in the DBAPI connection being returned to the pool with transactional resources removed.
```

A pull request with the clarification you propose will be welcome!
