### ISSUE TITLE
DOC: ExcelWriter constructor types

### ISSUE THREAD

**Issue by alexhtn** [pandas-dev/pandas#35505]
#### Location of the documentation

[https://pandas.pydata.org/docs/dev/reference/api/pandas.ExcelWriter.html?highlight=excelwriter](https://pandas.pydata.org/docs/dev/reference/api/pandas.ExcelWriter.html?highlight=excelwriter)
or
[https://github.com/pandas-dev/pandas/blob/d9fff2792bf16178d4e450fe7384244e50635733/pandas/io/excel/_base.py#L544](https://github.com/pandas-dev/pandas/blob/d9fff2792bf16178d4e450fe7384244e50635733/pandas/io/excel/_base.py#L544)

#### Documentation problem

Parameter `path` has type `str`, but based on this feature [https://github.com/pandas-dev/pandas/issues/7074](url) I can pass `io.BytesIO`.

#### Suggested fix for documentation

Change type description to `str | io.BytesIO`.

**Comment by rhshadrach** [comment]
The links in the issue are broken, you need to use

    [description](url)

**Comment by MJafarMashhadi** [comment]
It's better to use bytes-like object instead of `io.BytesIO` specifically.

**Comment by alexhtn** [comment]
> The links in the issue are broken, you need to use
I fixed links

**Comment by alexhtn** [comment]
> It's better to use bytes-like object instead of `io.BytesIO` specifically.

I didn't understand how can I use bytes-like object as output for ExcelWriter.

**Comment by MJafarMashhadi** [comment]
I mean it doesn't strictly require `io.BytesIO` instance, it can be a subclass or anything else that behaves like a bytes buffer (a zip file, a network socket, etc). So I'd suggest to use a more generic term in your patch.

```
with zipfile.ZipFile('samplezip.zip', 'w') as zf:
    with zf.open('XLfile.xlsx', 'w') as inf:
        with ExcelWriter(inf) as ew:
            df.to_excel(ew)
```

**Comment by alexhtn** [comment]
Now I got your idea.
I think correct type is `io.BufferedIOBase`. `ZipFile` and `io.Bytes` inherits from it, and function `open` returns `io.BufferedWriter`.
Also I check `socket.makefile`, for binary format in writing mode it returns `io.BufferedWriter`.
`io.BufferedWriter` inherits from `io.BufferedIOBase`.
But I'm not sure that it covers all cases. Maybe correct type would be `io.IOBase`.

**Comment by MJafarMashhadi** [comment]
I believe bytes like object means [the same](https://docs.python.org/3.3/glossary.html#term-bytes-like-object) thing. It's more about having the expected interface (duck typing), rather than being a subclass of a certain class (which is the case in Java).

**Comment by alexhtn** [comment]
I understand this. But now possibility of using bytes-likes objects isn't described in docs at all and also pycharm shows warnings.
I think it would be enough add `io.BufferedIOBase` to `path` type and some examples to show how it works.

**Comment by MJafarMashhadi** [comment]
Sounds good, Would you like to submit a PR?

**Comment by alexhtn** [comment]
take

**Comment by alexhtn** [comment]
After I made changes to docstring I ran `python scripts/validate_docstrings.py pandas.ExcelWriter` and it showed errors for new examples and also for old examples: `NameError:` name 'ExcelWriter' is not defined` and `NameError: name 'df' is not defined`.
Should I ignore these errors?

**Comment by MJafarMashhadi** [comment]
The current version has that warning anyway, so I guess you can ignore that. Worst case, you'll get a comment in code review on how to fix it.
