### ISSUE TITLE
BUG: DataFrame saved in Pickle under v1.1.0 cannot be read under v1.0.3 

### ISSUE THREAD

**Issue by Alalalalaki** [pandas-dev/pandas#35508]
I find any DataFrame saved in v1.1.0 by `to_pickle` is not readable under v1.0.3. Any functions on the DataFrame will throw `AttributeError: 'DataFrame' object has no attribute '_data'` or `RecursionError: maximum recursion depth exceeded while calling a Python object`.

I use pip to install pandas.

**Comment by jreback** [comment]
pickle is not in general forward compatible like this

older versions can be read by newer but not vice versa 

it might work but there are no guarantees at all
