### ISSUE TITLE
BUG: columns disappear when selecting rows with an explicit boolean expression which returns no rows

### ISSUE THREAD

**Issue by yanvirin** [pandas-dev/pandas#35528]
- [ ] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
df = DataFrame(columns=["x","y"])
df = df[df["x"]]
print(df.columns)
# columns disappeared

df = DataFrame(columns=["x","y"])
df = df[df["x"] == True]
print(df.columns)
# columns still there

```

#### Problem description

Columns disappear in the first example, when using a boolean expression to select rows with no matching rows.

#### Expected Output

Columns should remain intact as in the second example, which should be equivalent to the first one.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.3
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.0.3
setuptools       : 40.8.0
Cython           : None
pytest           : 5.3.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.5 (dt dec pq3 ext lo64)
jinja2           : 2.11.0
IPython          : 7.6.1
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.2.1
numexpr          : 2.7.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.13
tables           : 3.6.1
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by TomAugspurger** [comment]
Can you try with 1.1.0? I see equivalent output on both.

**Comment by yanvirin** [comment]
I think the bug is more nuanced. It happens to some dataframes on my local set up but I can't reproduce it with a simple example.

**Comment by yanvirin** [comment]
@TomAugspurger Thanks for looking into it. I have updated the issue with the correct scenario, it happens only then the df is empty to begin with.

**Comment by simonjayhawkins** [comment]
> Columns disappear in the first example, when using a boolean expression to select rows with no matching rows.

not looked in detail, but if `df["x"]` is intended to be a boolean indexer, I think you need to ensure the column dtype is bool for the empty DataFrame

```
>>> pd.__version__
'1.2.0.dev0+17.ga0c8425a5'
>>>
>>> df = pd.DataFrame(columns=["x", "y"], dtype=bool)
>>> df = df[df["x"]]
>>> df
Empty DataFrame
Columns: [x, y]
Index: []
>>> df.dtypes
x    bool
y    bool
dtype: object
>>>
```

**Comment by yanvirin** [comment]
@simonjayhawkins I think it is still weird behavior which makes it possible to write buggy code. Is there a way to make sure that the columns will not disappear even if they dtype is not set?
I understand that there are internal implementation details which might explain this behavior, but from the perspective of the user who receives a dataframe which he does not have control over, it is a bug.
May be then give a warning when the df is empty and someone is using an indexer and not a `.loc` to warn about this possible behavior?

**Comment by jbrockmendel** [comment]
xref #37772 this is technically correct as is, but it isnt uncommon for people to be confused by it

**Comment by phofl** [comment]
Closing as correct behavior
