### ISSUE TITLE
ENH: Add keep_index as an optional argument to json_serialize

### ISSUE THREAD

**Issue by amrsoll** [pandas-dev/pandas#35525]
#### Is your feature request related to a problem?

I have a DataFrame with a column filled with json data. I would like concatenate a subset of that json data to the DataFrame itself while preserving the index of the DataFrame for easy concatenation.

#### Describe the solution you'd like

1. I would add `pd.Series` as a possible data input in [the definition of json_normalize]
2. Add optional keyword `keep_index`
3. If the type of the data is a Series and `keep_index` is `True`, then add set the index of the result to the index of the Series.

#### API breaking implications

As an optional feature, this does not break the API, but the preservation of the index can not take effect if the data is not a pandas Series and might have unintended effects when switching the type of data.

However, given that i doesn't affect other types of data than `pd.Series`, the default value of `keep_index` could be set to `True` without affecting the example use cases.

#### Describe alternatives you've considered

I have been using this alternative so far, simply adding the index after json_serialize.

```python
s = df['col']
result = pd.json_serialize(s)
result.index = s.index
pd.concat(df, s, axis='columns')
```

#### Additional context

This feature request is similar to #17440 but doesn't result in the same kind of output, because this doesn't add an extra column.

#### Current behaviour
```python
data = [{'id': 1, 'name': {'first': 'Coleen', 'last': 'Volk'}},
        {'name': {'given': 'Mose', 'family': 'Regner'}},
        {'id': 2, 'name': 'Faye Raker'}]
df = pd.DataFrame({"Letters":['A','B','C']})
df['data'] = data
df.index = ['a', 'b','c']
df
```
| | Letters |                                           data |
|---| --- | --- |
| a |   A | {'id': 1, 'name': {'first': 'Coleen', 'last': ... |
| b |   B | {'name': {'given': 'Mose', 'family': 'Regner'}} | 
| c |   C |                 {'id': 2, 'name': 'Faye Raker'} |

```
>>> pd.json_normalize(df['data'])
    id name.first name.last name.given name.family        name
0  1.0     Coleen      Volk        NaN         NaN         NaN
1  NaN        NaN       NaN       Mose      Regner         NaN
2  2.0        NaN       NaN        NaN         NaN  Faye Raker
>>> pd.concat([df, pd.json_normalize(df['data'])], axis='columns')
  Letters                                               data   id  ... name.given name.family        name
a       A  {'id': 1, 'name': {'first': 'Coleen', 'last': ...  NaN  ...        NaN         NaN         NaN
b       B    {'name': {'given': 'Mose', 'family': 'Regner'}}  NaN  ...        NaN         NaN         NaN
c       C                    {'id': 2, 'name': 'Faye Raker'}  NaN  ...        NaN         NaN         NaN
0     NaN                                                NaN  1.0  ...        NaN         NaN         NaN
1     NaN                                                NaN  NaN  ...       Mose      Regner         NaN
2     NaN                                                NaN  2.0  ...        NaN         NaN  Faye Raker
```

#### Expected behaviour
```
>>> pd.json_normalize(df['data'], keep_index=True)
    id name.first name.last name.given name.family        name
a  1.0     Coleen      Volk        NaN         NaN         NaN
b  NaN        NaN       NaN       Mose      Regner         NaN
c  2.0        NaN       NaN        NaN         NaN  Faye Raker
>>> pd.concat([df, pd.json_normalize(df['data'], keep_index=True)], axis='columns')
  Letters                                               data   id  ... name.given name.family        name
a       A  {'id': 1, 'name': {'first': 'Coleen', 'last': ...  1.0  ...        NaN         NaN         NaN
b       B    {'name': {'given': 'Mose', 'family': 'Regner'}}  NaN  ...       Mose      Regner         NaN
c       C                    {'id': 2, 'name': 'Faye Raker'}  2.0  ...        NaN         NaN  Faye Raker
```

[the definition of json_normalize]: https://github.com/pandas-dev/pandas/blob/6388370eb313244ba0e4cd8215dcdbfdabb7004b/pandas/io/json/_normalize.py#L113

**Comment by rhshadrach** [comment]
You can instead set the index of the json-normalized frame:

     json_normalized = pd.json_normalize(df['data']).set_index(df.index)
     pd.concat([df, json_normalized], axis='columns', ignore_index=False)

Is that sufficient for you use case?

**Comment by amrsoll** [comment]
Yes that is similar to my alternative and does suit me. However I just thought that this extra argument might augment the `pd.json_serialize` function. I already found it weird that the default behaviour is *not* to keep the index of the original Series.

**Comment by rhshadrach** [comment]
Comparing the two solutions:

    pd.json_normalize(df['data'], keep_index=True)
    pd.json_normalize(df['data']).set_index(df.index)

offhand I don't see much benefit in having the argument. Also, this argument would only have meaning in the case of a Series as opposed to a list or dict. With these, I'm -1 on this.

**Comment by mroeschke** [comment]
Agreed, I think generally composing various existing pandas functionality is preferable over expanding the API surface area with convenience arguments.

Thanks for the suggestion, but since there hasn't been much support for this feature from the core team, closing.
