### ISSUE TITLE
BUG: Cannot select values in series using tuples when indexing with tuples in pandas 1.1.0

### ISSUE THREAD

**Issue by lfiedler** [pandas-dev/pandas#35534]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd

if __name__ == "__main__":
    series = pd.Series([1, 2, 3, 4], index=[("a", ), ("b", ), ("c", ), ("d", )])
    print(series[("a", )])

```

#### Problem description
On pandas 1.0.5 selecting values of a series which is indexed by tuples was possible via `__getitem__` using the desired tuple (see above code). In pandas 1.1.0 this suddenly raises a ValueError:
```
ValueError: Can only tuple-index with a MultiIndex
```
As this used to work in 1.0.5 and earlier versions (0.25 as far as I can recall) I expect this to be an unwanted side effect rather than a wanted change in behavior (in which case it would certainly be breaking).
Apart from this, I expected Series objects to behave to some degree like python dictionaries. In particular using tuples of strings as keys and selecting values by such tuples I think should be possible.

#### Expected Output
`1`

#### Output of ``pd.show_versions()``

<details>

```
INSTALLED VERSIONS
------------------
commit           : d9fff2792bf16178d4e450fe7384244e50635733
python           : 3.8.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-42-generic
Version          : #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.0
numpy            : 1.19.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 47.3.1.post20200622
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
None

```

</details>

**Comment by simonjayhawkins** [comment]
Thanks @lfiedler for the report

This was changed with a bugfix #31112. @jbrockmendel I'm not sure what the bugfix was, no release note or added tests. 

f19035d3a9848f61f00f753c1b7aac334930d425 is the first bad commit
commit f19035d3a9848f61f00f753c1b7aac334930d425
Author: jbrockmendel <jbrockmendel@gmail.com>
Date:   Sat Jan 18 07:49:03 2020 -0800

    REF: fix calls to Index.get_value (#31112)

**Comment by simonjayhawkins** [comment]
It appears that the call to `result = self.index.get_value(self, key)` inside a try block in `Series.__getitem__` raised `InvalidIndexError` after the changes in #31112 instead of returning the result.

However, due to further changes in #31399, get_value is no longer called for a tuple indexer before the isinstance MultiIndex check. and the 'Can only tuple-index with a MultiIndex' message raised.

**Comment by jbrockmendel** [comment]
This is pretty hairy, and likely to remain fragile even once fixed (e.g `series.loc[("a",)]` also raises because it treats the 1-tuple as a listlike indexer).  I'd advise users to avoid this pattern wherever possible.

**Comment by simonjayhawkins** [comment]
> I'd advise users to avoid this pattern wherever possible.

discussion in #24688. 

As there is not consensus there on deprecating tuples in index, we should restore the 1.0.5 behaviour for now.

**Comment by jbrockmendel** [comment]
> As there is not consensus there on deprecating tuples in index, we should restore the 1.0.5 behaviour for now.

Agreed.
