### ISSUE TITLE
DOC: add additional numba example

### ISSUE THREAD

**Issue by raybellwaves** [pandas-dev/pandas#35550]
#### Location of the documentation
 
https://pandas.pydata.org/pandas-docs/stable/user_guide/enhancingperf.html#using-numba

#### Documentation problem

Provide a simpler copy-paste example.

#### Suggested fix for documentation

@TomAugspurger has a nice example of using numba to speed up a `rolling.apply()` operation here https://github.com/TomAugspurger/acon-2020-pandas/blob/master/Numba%20Acceleration.ipynb

Could this or a variant of this be added to the docs? Perhaps to show that you don't need to do `import numba` but can do `engine='numba'`

**Comment by TomAugspurger** [comment]
I think I took that from the docs (perhaps the whatsnew?)

**Comment by raybellwaves** [comment]
Thanks found it.

https://pandas.pydata.org/pandas-docs/stable/user_guide/computation.html#rolling-apply

**Comment by reubence** [comment]
May I take this issue?

**Comment by vaibhavarora102** [comment]
sir, can I work on this

**Comment by erfannariman** [comment]
take

**Comment by erfannariman** [comment]
@TomAugspurger @simonjayhawkins Makes sense to add this as an example in the Numba part of `enhancingperf.rst`, but the example in `computation.rst` is pretty extensive, it just needs an example. Should I add the example to `computation.rst` in this case and mention to it in the Numba part? I can also copy the text from `computation.rst` and add an example for it in `enhancing.rst`, but that seemse redundant.

**Comment by TomAugspurger** [comment]
I think just linking from one to the other is fine.

**Comment by erfannariman** [comment]
Didnt want to remove comment, wanted to edit. Thanks for reply @TomAugspurger

**Comment by vaibhavarora102** [comment]
@TomAugspurger  kindly tell I could contribute in any way, as I am new  to open source
thanks!

**Comment by TomAugspurger** [comment]
We have a contributing guide at
https://pandas.pydata.org/docs/development/contributing.html. It recommends
how to find a good first issue.

**Comment by vaibhavarora102** [comment]
Thanks alot
