### ISSUE TITLE
BUG:Dataframe.to_string, when set index=False, there is a white space in the head of every line

### ISSUE THREAD

**Issue by ZephyrShannon** [pandas-dev/pandas#35561]
- [x] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
d = {'col1': ["1", "2", "3"], 'col2': [4, 5, 6]}
df = pd.DataFrame(d)
print(df.to_string(index=False, formatters={'col1':'{:10}'.format}))

```

#### Problem description
there is a white space in the head of every line:
       col1  col2
 1              4
 2              5
 3              6
#### Expected Output
no white space in the head
       col1  col2
1              4
2              5
3              6

#### Output of ``pd.show_versions()``
<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Darwin
OS-release: 19.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: zh_CN.UTF-8
pandas: 0.24.2
pytest: None
pip: 19.0.3
setuptools: 41.0.0
Cython: None
numpy: 1.16.4
scipy: 1.3.0
pyarrow: None
xarray: None
IPython: 7.5.0
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.1.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: 4.5.1
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.8.1
gcsfs: None
</details>

**Comment by linchiwei123** [comment]
try this. [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_string.html?highlight=to_string#pandas.DataFrame.to_string)
```python
print(df.to_string(index=False, formatters={'col1':'{:10}'.format}, justify="left"))
```

**Comment by TomAugspurger** [comment]
Duplicate o fhttps://github.com/pandas-dev/pandas/issues/24980 I think.
