### ISSUE TITLE
Change the default of `check_freq` to `False` as it breaks existing code

### ISSUE THREAD

**Issue by MaxWinterstein** [pandas-dev/pandas#35570]
As already mentioned in https://github.com/pandas-dev/pandas/pull/34050 the default of `check_freq` was set to True, which leads to broken code / tests. 

I suggest to change it to `False` as it ensures existing code won't break.

>k thanks. pls open an issue to change this to `check_freq=False`; I *think* this might break downstream, IIRC a comment by @jorisvandenbossche

_Originally posted by @jreback in https://github.com/pandas-dev/pandas/pull/34050#issuecomment-626227446_

**Comment by jreback** [comment]
-1 on changing this.

**Comment by TomAugspurger** [comment]
See https://github.com/pandas-dev/pandas/pull/35571#issuecomment-674063870
