### ISSUE TITLE
ENH: write support for google cloud storage 

### ISSUE THREAD

**Issue by zyxue** [pandas-dev/pandas#35577]
#### Is your feature request related to a problem?

Pandas can read from google cloud storage directly. I wonder if it's a good idea to support writing data frame to google cloud storage directly.

#### Describe the solution you'd like

pd.to_parquet('gs://some-bucket/mydata.parquet')

#### API breaking implications

unaware 

#### Describe alternatives you've considered

I've been writing custom functions like `write_df_to_gcs(df, gcs_uri, gcs_credentials)`, but I feel the better abstraction is to be inside `pd.to_parquet`, e.g. if to_parquet detects the path is a GCS URL, then write to GCS instead.

**Comment by TomAugspurger** [comment]
This might work with 1.1.0. You'll need to install gcsfs. Can you try?

**Comment by zyxue** [comment]
I can try, could you point to me the PR the implements this feature?

**Comment by zyxue** [comment]
oh, it works. wondering if there is another way to pass credentials other than `GOOGLE_APPLICATION_CREDENTIALS`.

**Comment by TomAugspurger** [comment]
It's linked from the release notes.

https://github.com/pandas-dev/pandas/pull/35381 is implementing the ability to control how the filesystem is created.
