### ISSUE TITLE
BUG: `DataFrame.reset_index()` discards `MultiIndex` dtypes if `DataFrame` is empty

### ISSUE THREAD

**Issue by batterseapower** [pandas-dev/pandas#35589]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of pandas. (tried on v1.0.5 -- the latest in Conda -- and checked the release notes for the new version to make sure they don't mention anything related)
- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
x = pd.DataFrame.from_dict({
    'A': pd.Categorical.from_codes([1], categories=['G', 'H']),
    'B': np.array([0], dtype='i8'),
})

x.dtypes # category and int64

# This is the bug:
x.iloc[:0].set_index(['A', 'B']).reset_index().dtypes # float64 and float64

# These cases all work correctly i.e. the dtypes are category and int64
x.set_index(['A', 'B']).reset_index().dtypes
x.set_index('A').reset_index().dtypes
x.iloc[:0].set_index('A').reset_index().dtypes

# This is CategoricalDtype as expected, so the MultiIndex construction is correct: it's just the `reset_index()` which is throwing away the info
x.iloc[:0].set_index(['A', 'B']).index.get_level_values('A').dtype
```

#### Problem description

`reset_index` shouldn't throw away dtype information in the special case where the `DataFrame` has zero rows. Sometimes it's hard to avoid throwing away info when you manipulate zero-element DataFrames, but in this case there is no reason to do it.

#### Expected Output

category and int64 dtypes from `reset_index` in all cases

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.936

pandas           : 1.0.5
numpy            : 1.19.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 49.2.0.post20200714
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.16.1
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by TomAugspurger** [comment]
This sounds like https://github.com/pandas-dev/pandas/issues/19602. Can you try with pandas 1.1?

**Comment by TomAugspurger** [comment]
Just tried with master, and I see

```python
# This is the bug:
x.iloc[:0].set_index(['A', 'B']).reset_index().dtypes # float64 and float64

## -- End pasted text --
Out[3]:
A    category
B       int64
dtype: object
```

so I think we're good. LMK if not and we'll reopen.
