### ISSUE TITLE
BUG: After sort_values() is executed, a large block of memory is not freed

### ISSUE THREAD

**Issue by wjsi** [pandas-dev/pandas#35599]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python                                                                                                                                               
import psutil
import pandas as pd

print(psutil.Process().memory_info().rss)  # outputs 77533184

# first execution
arrow_ser = pd.Series(['abcdefg'] * (10 * 1024 ** 2))
arrow_ser = arrow_ser.sort_values()  # same behavior as sort_values(inplace=True)
del arrow_ser
print(psutil.Process().memory_info().rss)  # outputs 686264320

# second execution
arrow_ser = pd.Series(['abcdefg'] * (10 * 1024 ** 2))
arrow_ser = arrow_ser.sort_values()
del arrow_ser
print(psutil.Process().memory_info().rss)  # outputs 686456832
```

#### Problem description

When calling ``sort_values()`` on dataframes or series, we discover that a large block of memory is allocated and not freed even if all related objects are deleted. When sort_values() is executed again, the size of allocated memory does not increase significantly. When the line of ``sort_values()`` is commented out, memory sizes are ok. We guess if there is a cache or memory pool when calling ``sort_values()``, but we cannot spot it.

We test ``sort_values()`` under 1.1.0, 1.0.5 and 0.24.1, and they share the same behavior. The test environment is an independent conda env without MKL, thus MKL buffers is not a problem.

#### Expected Output

The memory shall be freed once the related object is deleted, or a method cleaning the caches is needed.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : d9fff2792bf16178d4e450fe7384244e50635733
python           : 3.7.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
Version          : Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : zh_CN.UTF-8

pandas           : 1.1.0
numpy            : 1.19.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 49.2.0.post20200714
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.16.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by TomAugspurger** [comment]
Python will sometimes not release memory back to the operating system, even when it's been freed. Are you sure that's not happening here?

```python
In [1]: import numpy as np

In [2]: import psutil

In [3]: print(psutil.Process().memory_info().rss)  #
57196544

In [4]: a = np.arange(10 * 1024 ** 2)

In [5]: del a

In [6]: print(psutil.Process().memory_info().rss)  #
141139968
```

**Comment by AlexKirko** [comment]
The `Series` itself is about 3 times larger on my machine than the garbage left by the `sort_values` function (primarily the sorted index that results from argsort but also arrays of bools and such). To me, this seems like a reasonable overhead percentage, and since we don't manually clean up garbage without very good reason, these get to hang around until the garbage collector gets to them.

**Comment by wjsi** [comment]
Thank you for your answers. @TomAugspurger @AlexKirko
