### ISSUE TITLE
BUG: interpolate gives a TypeError on empty dataframes

### ISSUE THREAD

**Issue by sanderland** [pandas-dev/pandas#35598]
Already fixed in #35543, making an issue for linking/discussion.

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
from pandas import DataFrame
DataFrame().interpolate()
```
    "Cannot interpolate with all object-dtype columns "
TypeError: Cannot interpolate with all object-dtype columns in the DataFrame. Try setting at least one column to a numeric dtype.

#### Problem description
This is a regression, 1.0.5 handles it fine.

The problem appeared due to checking `np.all(obj.dtypes == np.dtype(object))` since the all of an empty set is True

#### Output of ``pd.show_versions()``

pandas           : 1.1.0

**Comment by simonjayhawkins** [comment]
change in behaviour caused by #33084 cc @jbrockmendel 

e894809c665314ccc63231a9f0e2842f13431a56 is the first bad commit
commit e894809c665314ccc63231a9f0e2842f13431a56
Author: jbrockmendel <jbrockmendel@gmail.com>
Date:   Sun Mar 29 08:16:17 2020 -0700

    CLN: de-kludge NDFrame.interpolate (#33084)
