### ISSUE TITLE
BUG: to_sql if_exists not working properly when schema is set on PostgreSQL

### ISSUE THREAD

**Issue by westhyena** [pandas-dev/pandas#35594]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import sqlalchemy
import pandas as pd 

uri = "some uri to postgresql
engine = sqlalchemy.create_engine(uri)
conn = engine.connect()

df = pd.DataFrame([[1,2,3], [2,1,3]], columns=["A", "B", "C"])

# works
df.to_sql("tt", conn, schema="pg_temp", if_exists="append", index=False)

# causes error
df.to_sql("tt", conn, schema="pg_temp", if_exists="append", index=False)

# works
df.to_sql("tt", conn, if_exists="append", index=False)
```

#### Problem description

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateTable) relation "tt" already exists

[SQL: 
CREATE TABLE pg_temp.tt (
	"A" BIGINT, 
	"B" BIGINT, 
	"C" BIGINT
)

]
(Background on this error at: http://sqlalche.me/e/f405)
```

When I set to_sql with schema and if_exists="append", it works at first call(when table doesn't exists).
But when I call to_sql again(when table exists), it doesn't append the data. It tries to create table again and causes error.

Not setting the schema parameter worked fine when table exists.

**Comment by westhyena** [comment]
I tested more, and found only schema="pg_temp" makes the problem.
and check the code, it might be sqlalchemy issue.

**Comment by alimcmaster1** [comment]
```
import sqlalchemy
import pandas as pd 

uri = "some uri to postgresql"
engine = sqlalchemy.create_engine(uri)
conn = engine.connect()
# Doesnt work - returns False
eng.dialect.has_schema(eng, "pg_temp")
# Works - returns True
eng.execute(sqlalchemy.schema.CreateSchema("x"))
eng.dialect.has_schema(eng, "x") 

```
https://github.com/sqlalchemy/sqlalchemy/issues/3264

Could you raise in SQLAlchemy @westhyena ?

**Comment by westhyena** [comment]
@alimcmaster1 Yes, I can raise in SQLALchemy. 
When I set schema with pg_temp, it's not working properly.

```python
engine.execute("create table pg_temp.test_table (a int);")

# returns True
engine.dialect.has_table(engine, "test_table")

# returns False
engine.dialect.has_table(engine, "test_table", schema="pg_temp")
```

I'll post this issue to SQLALchemy repo.
