### ISSUE TITLE
BUG: Incorrect float format in object column

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#35603]
from https://github.com/pandas-dev/pandas/issues/35580#issuecomment-670245569

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```
>>> pd.Series([1.0]).astype(object)
0    1
dtype: object
>>>
```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Expected Output

```
>>> pd.Series([1.0]).astype(object)
0    1.0
dtype: object
```
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by mzeitlin11** [comment]
Fixed on master, but could probably use a test

**Comment by mdhsieh** [comment]
I can try making one.

**Comment by mdhsieh** [comment]
take
