### ISSUE TITLE
ENH: Make top-level Pandas functions serializable

### ISSUE THREAD

**Issue by mrocklin** [pandas-dev/pandas#35611]
```python
import pandas as pd
import pickle
pickle.dumps(pd.read_csv)
```

```python-traceback
AttributeError: Can't pickle local object '_make_parser_function.<locals>.parser_f'
```

**Comment by mroeschke** [comment]
Looks like `read_csv` is serializable in 1.1.0, as well as all callable object in the top level namespace

```
In [20]: import pickle

In [21]: import pandas as pd

In [22]: pd.__version__
Out[22]: '1.1.0'

In [23]: pickle.dumps(pd.read_csv)
Out[23]: b'\x80\x03cpandas.io.parsers\nread_csv\nq\x00.'

In [24]: for name, obj in pd.__dict__.items():
    ...:     if callable(obj):
    ...:         try:
    ...:             pickle.dumps(obj)
    ...:         except:
    ...:             print(f'{name}' is not pickleable)
    ...:

In [25]:
```

**Comment by mroeschke** [comment]
https://github.com/pandas-dev/pandas/pull/34976 probably made `read_csv` serializable.

I suppose we could add unit tests to ensure all these objects are serializable

**Comment by ikedaosushi** [comment]
May I take it?

**Comment by mrocklin** [comment]
Oh that's great news.  Thank you @mroeschke for checking, and my apologies for testing against an older version.

@ikedaosushi I think that you do not need permission to submit a pull request.  I do not know Pandas' development policies, but I think that it is ok for you to contribute.

**Comment by mroeschke** [comment]
No worries @mrocklin 

Yes, @ikedaosushi, happy to have you take this issue.
