### ISSUE TITLE
BUG: error: may be used uninitialized. In alpine

### ISSUE THREAD

**Issue by NikSays** [pandas-dev/pandas#35622]
- [ x ] I have checked that this issue has not already been reported. (Not as a separate issue)

- [ x ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Problem description
In an alpine contarner, running `pip3 install pandas=1.1.0`, 
results in error: 
```
'__pyx_v_year' may be used uninitialized in this function`
     7787 |             __pyx_v_year = (__pyx_v_year - 1);
          |             ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors
    error: command 'gcc' failed with exit status 1
```

#### Expected Output

Successful install

**Comment by bashtage** [comment]
Which file was being compiled?

**Comment by bashtage** [comment]
parsing.c

```
*/
          __pyx_t_1 = ((__pyx_v_month > __pyx_v_mnum) != 0);
          if (__pyx_t_1) {

            /* "pandas/_libs/tslibs/parsing.pyx":452
 *                 month = (mnum + (quarter - 1) * 3) % 12 + 1
 *                 if month > mnum:
 *                     year -= 1             # <<<<<<<<<<<<<<
 *             else:
 *                 month = (quarter - 1) * 3 + 1
 */
            __pyx_v_year = (__pyx_v_year - 1);

            /* "pandas/_libs/tslibs/parsing.pyx":451
 * 
 *                 month = (mnum + (quarter - 1) * 3) % 12 + 1
 *                 if month > mnum:             # <<<<<<<<<<<<<<
 *                     year -= 1
 *             else:
 */
```

**Comment by bashtage** [comment]
This is a suprious warning in the sense that the uninitialized year cannot be hit.  This said, it is free to initialize it above.

**Comment by biswabandhu21** [comment]
Hi ,

Is the issue fixed I am still getting the error , when trying to install pandas in docker . 

version : pandas-1.1.1

**Comment by jreback** [comment]
1.2

**Comment by biswabandhu21** [comment]
when is the latest version released. The latest version shows as 1.1.1
Refered to following link
https://pandas.pydata.org/

**Comment by jreback** [comment]
1.2 is not released yet

**Comment by adriantorrie** [comment]
For anyone else running into this, we just pinned `pandas==1.0.5` and it installed successfully.
