### ISSUE TITLE
ENH: to_sql support DB-API other than sqlite3/sqlalchemy (eg peewee ORM)

### ISSUE THREAD

**Issue by wilberh** [pandas-dev/pandas#35635]
#### Is your feature request related to a problem?

I can't use, to_sql, api to insert data to a database table that complies with DB-API (pep-249) v2. 

#### Describe the solution you'd like

I would like to use, to_sql, to insert data to a database table that complis with DB-API (pep-249) v2.  
Example, I use peewee ORM (not sqlalchemy / sqlite3 connections) to interact with a database that has a DB-API v2 driver.

#### Describe alternatives you've considered

I'm pulling each row of the dataframe to do inserts using threading.  But I'd like this api to support connections other than sqlalchemy and sqlite3.

**Comment by gordthompson** [comment]
You say that the "database ... has a DB-API v2 driver" but does it have a [SQLAlchemy dialect](https://docs.sqlalchemy.org/en/13/dialects/index.html)? If so, and if you're concerned about having SQLAlchemy "bloat up" your project then note that you've already invested about 120 MiB when you `import pandas as pd` but you only need 6 MiB more to `import sqlalchemy as sa`:

``` none
>>> import psutil
>>> process = psutil.Process()
>>> f"vms {(process.memory_info().vms / 1048576):0.1f} MiB"
'vms 21.9 MiB'
>>> import pandas as pd
>>> f"vms {(process.memory_info().vms / 1048576):0.1f} MiB"
'vms 143.6 MiB'
>>> import sqlalchemy as sa
>>> f"vms {(process.memory_info().vms / 1048576):0.1f} MiB"
'vms 149.3 MiB'
```

**Comment by jbrockmendel** [comment]
@wilberh if the solution suggested by @gordthompson works for you, thats probably your best bet.  Is that viable?

**Comment by wilberh** [comment]
> @wilberh if the solution suggested by @gordthompson works for you, thats probably your best bet.  Is that viable?

Yes; thank you.
