### ISSUE TITLE
QST: How to select the week data from a given DataFrame?

### ISSUE THREAD

**Issue by Monsieurvishal** [pandas-dev/pandas#35653]
Question about pandas 
For the given DataFrame How do I select data between two weeks?

	Date	Open	High	Low	Close
0	01-08-2019	97.85	98.45	96.40	97.25
1	02-08-2019	97.15	98.95	96.75	98.15
2	05-08-2019	98.30	98.70	94.30	95.65
3	06-08-2019	95.75	97.75	95.20	97.05
4	07-08-2019	96.80	97.70	96.05	96.90
5	08-08-2019	97.40	98.90	96.55	97.40
6	09-08-2019	97.20	98.10	96.65	97.30
7	12-08-2019	97.20	97.25	93.40	93.75
8	13-08-2019	93.70	96.60	93.15	96.35
9	14-08-2019	95.85	96.40	94.00	94.45

August 01-08-2019 ,02-08-2019 is one week.
August 05-08-2019, 06-08-2019, 07-08-2019, 08-08-2019, 09-08-2019 is second week
I want data in dataframe should be grouped according to week.

![august-2019-calendar](https://user-images.githubusercontent.com/59202862/89797048-0cf91480-db48-11ea-8a90-e7b96ca33f7e.png)

I want to group the week data for whole year?

**Comment by jreback** [comment]
pls ask usage questions on StackOverflow
