### ISSUE TITLE
CI: DeprecationWarning in `tests/io/json/test_json_table_schema.py` and `tests/io/json/test_pandas.py`

### ISSUE THREAD

**Issue by fangchenli** [pandas-dev/pandas#35661]
On the NumPy dev build. The following tests:

```bash
FAILED pandas/tests/io/json/test_json_table_schema.py::TestTableOrient::test_to_json
FAILED pandas/tests/io/json/test_json_table_schema.py::TestTableOrient::test_date_format_raises
FAILED pandas/tests/io/json/test_pandas.py::TestPandasContainer::test_datetime_tz
FAILED pandas/tests/io/json/test_pandas.py::TestPandasContainer::test_tz_is_utc[ts0]
FAILED pandas/tests/io/json/test_pandas.py::TestPandasContainer::test_tz_is_utc[ts1]
FAILED pandas/tests/io/json/test_pandas.py::TestPandasContainer::test_tz_is_utc[ts2]
FAILED pandas/tests/io/json/test_pandas.py::TestPandasContainer::test_tz_range_is_utc[tz_range0]
FAILED pandas/tests/io/json/test_pandas.py::TestPandasContainer::test_tz_range_is_utc[tz_range1]
FAILED pandas/tests/io/json/test_pandas.py::TestPandasContainer::test_tz_range_is_utc[tz_range2]
```
raise `DeprecationWarning: an integer is required (got type float). Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.`
I filtered this warning for now.

**Comment by jbrockmendel** [comment]
cc @WillAyd

**Comment by WillAyd** [comment]
Does this only fail for tests with date time values? My guess is that any of the PyInt calls that Cython generates from the date time modules could be the culprit

Slightly related issue on the numpy side:

https://github.com/numpy/numpy/issues/13412

**Comment by simonjayhawkins** [comment]
removing milestone

**Comment by jbrockmendel** [comment]
I don't see these warnings on master (and im pretty sure local numpy has caught up to what npdev was at the time of OP).  closeable?

**Comment by mroeschke** [comment]
Agreed, haven't seen this on builds lately so closing
