### ISSUE TITLE
August 2020 Developer Meeting (August 12th)

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#35678]
The monthly dev meeting is Wednesday August 12th, at 18:00 UTC. Our calendar is at https://pandas.pydata.org/docs/development/meeting.html#calendar to check your local time.

Video Call: https://zoom.us/j/942410248
Minutes: https://docs.google.com/document/u/1/d/1tGbTiYORHiSPgVMXawiweGJlBw5dOkVJLY-licoBmBU/edit?ouid=102771015311436394588&usp=docs_home&ths=true

Please add items you'd like to see discussed to the agenda.

All are welcome to attend.

cc @pandas-dev/pandas-core @pandas-dev/pandas-triage

**Comment by jreback** [comment]
I will miss the meeting today :-<

    On Tuesday, August 11, 2020, 04:33:20 PM EDT, Joris Van den Bossche <notifications@github.com> wrote:  
 
 


The monthly dev meeting is Wednesday August 12th, at 18:00 UTC. Our calendar is at https://pandas.pydata.org/docs/development/meeting.html#calendar to check your local time.

Video Call: https://zoom.us/j/942410248
Minutes: https://docs.google.com/document/u/1/d/1tGbTiYORHiSPgVMXawiweGJlBw5dOkVJLY-licoBmBU/edit?ouid=102771015311436394588&usp=docs_home&ths=true

Please add items you'd like to see discussed to the agenda.

All are welcome to attend.

cc @pandas-dev/pandas-core @pandas-dev/pandas-triage
