### ISSUE TITLE
BUG: DatetimeIndex.get_loc failing when key is int (introduced in v1.1.0)

### ISSUE THREAD

**Issue by maximemorariu** [pandas-dev/pandas#35691]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

In version 1.0.5 the below was running successfully, but in 1.1.0, this is now broken as `int` keys are not accepted anymore (a `KeyError` is raised because the type of the key is now unexpected).

```
import numpy as np
from numpy import datetime64
from pandas import DatetimeIndex

dt = datetime64("2020-08-12T00:00:00.000000000")
dt_item = np.array(dt).item()
index = DatetimeIndex(data=[dt])
print(index.get_loc(dt))
print(index.get_loc(dt_item))
```

**Comment by jbrockmendel** [comment]
`dti.get_loc(some_int)` _should_ raise a `KeyError`

**Comment by jreback** [comment]
yep, this is a user-error; its possible it accidently enforced previously, but this is incorrect as is fixed.
