### ISSUE TITLE
BUG: DataFrame.merge() fails with program termination, consumed entire available memory(Memory Leak)

### ISSUE THREAD

**Issue by HimanshuS24** [pandas-dev/pandas#35735]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
 
df1 = pd.read_csv(path_of_csv1)
df2 = pd.read_csv(path_of_csv2)
resultant_df = df1.merge(df2, left_on='left_csv_column_name', right_on='right_csv_column_name', how='inner') <= Exception thrown here.

```

```
[1] 31330 killed python
```

#### Problem description

Memory Leak occurs while trying to merge two Dataframes read from two different CSV's of bigger size (>=10Mb in my case)

For smaller CSV files (let's say of <=10Mb) each merging process is working fine. 
My system is having 8Gb of RAM and before starting the Merging process, Enough Memory is available(>3Gb) and after starting the merging process, the system consumes the entire available memory and killed the merging process in between with the below exception:-

```
[1] 31330 killed python
```

#### Expected Output

`resultant_df` contains the two DataFrame `df1` and `df2` based on the join type we have given as a parameter `how='inner'` in pandas merge function

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.5.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.4.0
Version          : Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.1.0
numpy            : 1.19.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.1
setuptools       : 49.2.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None]

</details>

**Comment by jreback** [comment]
pls show a reproducible example 
that is just code

**Comment by HimanshuS24** [comment]
> pls show a reproducible example
> that is just code

Hey @jreback, I followed the below steps only to reproduce this issue.
<img width="596" alt="Screenshot 2020-08-15 at 10 24 34 PM" src="https://user-images.githubusercontent.com/60599856/90317348-6dbc8e80-df46-11ea-8f22-0fb2bdc7ff35.png">
After this `df1.merge(df2,...)` step, the process/shell terminated after some time while memory usage by the python program reaches to a full system capacity limit. 
<img width="1159" alt="Screenshot 2020-08-15 at 10 31 00 PM" src="https://user-images.githubusercontent.com/60599856/90317421-0c48ef80-df47-11ea-948c-0988de9e0433.png">

**Comment by jreback** [comment]
@HimanshuS24 you need an example that someone can copy paste and reproduce - pictures are impossible

you need to reduce to a reproducible example in order for anyone to even have a look

**Comment by jbrockmendel** [comment]
@HimanshuS24 see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by TomAugspurger** [comment]
@HimanshuS24 let us know if you can provide a reproducible example and we'll reopen!
