### ISSUE TITLE
CI: unpin numpy and matplotlib

### ISSUE THREAD

**Issue by VirosaLi** [pandas-dev/pandas#35779]
revert #35312 and #35358

**Comment by danieldjewell** [comment]
Does ```pyproject.toml``` also need to be changed? Currently, it appears locked to numpy 1.17.3 for python >= 3.8

**Comment by VirosaLi** [comment]
> Does `pyproject.toml` also need to be changed? Currently, it appears locked to numpy 1.17.3 for python >= 3.8

If I understand it correctly, what is specified in `pyproject.toml` is the minimum requirements.
