### ISSUE TITLE
BUG: Series.replace doesn't distinguish single and double quotes

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#35781]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of pandas.
- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

If we try to replace the single quotes in a string with double quotes or vice versa using Series.replace it doesn't work (Series.str.replace does):

```python
import pandas as pd

print(pd.__version__)
# 1.2.0.dev0+112.g0d0f53f3c
print(pd.Series([" ' ' "]).replace("'", '"'))
# 0     ' ' 
# dtype: object
print(pd.Series([" ' ' "]).str.replace("'", '"'))
# 0     " " 
# dtype: object

pd.Series([' " " ']).replace('"', "'")
# 0     " "
# dtype: object
pd.Series([' " " ']).str.replace('"', "'")
# 0     ' '
# dtype: object
```

**Comment by geetha-rangaswamaiah** [comment]
Let's say, series = [' " ', ' " " ', ' 2 '] and we want to replace(' " ', " ' ")

<br>

**Series.replace:** Takes each element of the series and if it finds the value it's looking for then it replaces.

| | | |
|--|--|--|
| Takes the first element <br><br> " = " <br><br> Replaces it with single quotes | Takes the second element <br><br> " "  != " <br><br> No replacement |  Takes the third element <br><br> 2 != " <br><br> No replacement |

<br> 

**Series.str.replace:** Takes each element of the series, treats it as a string and then does string replacement. 

| | | |
|--|--|--|
| Takes the first element <br><br> " <br><br> The above string contains " <br><br> Replaces it with single quotes | Takes the second element <br><br> " " <br><br> The above string contains two " <br><br> Replaces them with single quotes |  Takes the third element <br><br> 2 <br><br> The above string doesn't contain " <br><br> No replacement |


<br><br>

![image](https://user-images.githubusercontent.com/61543692/90504452-b6ef2700-e16e-11ea-9bb0-fa6d346cab00.png)

**Comment by dsaxton** [comment]
You're right, didn't think that through
