### ISSUE TITLE
ENH: round(inplace=True)

### ISSUE THREAD

**Issue by Peters-D** [pandas-dev/pandas#35786]
#### Is your feature request related to a problem?

I frequently round numerical columns in my dataframe to two decimals using `pandas.DataFrame.round`. I would like to do this inplace, since it will make code simpler and presumable less prone to errors.

#### Describe the solution you'd like
`DataFrame.round` should get a new argument `inplace` such that if `True` the operation is done inplace. I think `DataFrame.apply` could also improve from this enhancement.

#### Example code
```python
import pandas as pd
import numpy as np

df = pd.DataFrame({"foo": [1.11, 2.22, 3.33, 4.44, 5.55],
                   "bar": [6.66, 7.77, 8.88, 9.99, np.nan]})

# e.g. dropna() works with inplace
df.dropna(inplace=True)

# but round() does not
df["foo"] = df["foo"].round(1)

# I would like a feature like:
df["foo"].round(1, inplace=True) # does not run

```

**Comment by dsaxton** [comment]
Thanks for posting an issue @Peters-D. Ultimately it'd be up to the core developers as to whether or not this option is added, but my guess is that it's unlikely since there's more a push towards deprecating inplace than expanding its reach (couple reasons being it doesn't lend itself to method chaining and can also lead to surprising bugs in some cases).

**Comment by jreback** [comment]
-1 on adding inplace anywhere - it's going to be depreciated (several issues about this)

inplace is much worse from an api / readability perspective and is error prone itself

**Comment by JB-AM** [comment]
I did not know inplace=True would/may be deprecated… I was going to create a similar issue but this one already existed.

**Comment by brandonrwin** [comment]
A workaround (maybe intended method?) for this is to reference and modify the underlying numpy array:

```python
np.round(df['foo'].values, 3, out=df['foo'].values)
```

This will prevent a copy of the array being made.
