### ISSUE TITLE
BUG: failing test for pyarrow/s3fs on windows

### ISSUE THREAD

**Issue by martindurant** [pandas-dev/pandas#35791]
- [ ] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```
FAILED pandas/tests/io/test_parquet.py::TestParquetPyArrow::test_s3_roundtrip_for_dir[partition_col0]
```

#### Problem description

See build https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=40576&view=logs&jobId=404760ec-14d3-5d48-e580-13034792878f&j=404760ec-14d3-5d48-e580-13034792878f&t=f81e4cc8-d61a-5fb8-36be-36768e5c561a

env:
```
pyarrow                   1.0.0
botocore                  1.17.44 
fsspec                    0.8.0 
moto                      1.3.14 
s3fs                      0.4.2 
```

I do not know the cause of this problem, but it appears in https://github.com/pandas-dev/pandas/pull/35655 and also for the original code, so skipping it on win for now.

**Comment by simonjayhawkins** [comment]
closed in #35814
