### ISSUE TITLE
Performance regression in reindex.LevelAlign.time_reindex_level

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#35804]
https://pandas.pydata.org/speed/pandas/index.html#reindex.LevelAlign.time_reindex_level?commits=a0c8425a5f2b74e8a716defd799c4a3716f66eff-2a319238e47d3d7362188f7da4eb911199c423b8

Somewhere in https://github.com/pandas-dev/pandas/compare/a0c8425a5f2b74e8a716defd799c4a3716f66eff...2a319238e47d3d7362188f7da4eb911199c423b8

**Comment by dsaxton** [comment]
https://github.com/pandas-dev/pandas/commit/0b90685f4df2024754748b992d5eaaa352e7caa5 seems to be the only commit in that range that touches index code. May be worth investigating @simonjayhawkins?

**Comment by jorisvandenbossche** [comment]
I suppose https://github.com/pandas-dev/pandas/issues/35805 might be related to the same then?

**Comment by simonjayhawkins** [comment]
Thanks @dsaxton will look soon

**Comment by jreback** [comment]
no open PR for this, moving off 1.2
