### ISSUE TITLE
Performance regression in tslibs.tz_convert.TimeTZConvert.time_tz_convert_from_utc

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#35803]
https://pandas.pydata.org/speed/pandas/index.html#tslibs.tz_convert.TimeTZConvert.time_tz_convert_from_utc?p-size=1000000&p-tz=datetime.timezone.utc&commits=3701a9b1bfc3ad3890c2fb1fe1974a4768f6d5f8-522f855a38d52763c4e2b07480786163b91dad38

Somewhere in https://github.com/pandas-dev/pandas/compare/3701a9b1bfc3ad3890c2fb1fe1974a4768f6d5f8...522f855a38d52763c4e2b07480786163b91dad38

**Comment by jorisvandenbossche** [comment]
To be clear, it's only a regression on master, after 1.1 (so only a target for 1.2, not 1.1.1) ?

**Comment by jorisvandenbossche** [comment]
Quite likely cause from that commit range: https://github.com/pandas-dev/pandas/pull/35532

**Comment by jorisvandenbossche** [comment]
cc @lidavidm @jbrockmendel 

Looking at the PR, it might also be caused by the added `copy` ? (the regression only happened for the case of UTC timezone, see [view](https://pandas.pydata.org/speed/pandas/index.html#tslibs.tz_convert.TimeTZConvert.time_tz_convert_from_utc?p-size=1000000&p-tz=datetime.timezone.utc&p-tz=datetime.timezone(datetime.timedelta(0%2C%203600))&p-tz=%3CDstTzInfo%20'US%2FPacific'%20LMT-1%20day%2C%2016%3A07%3A00%20STD%3E&p-tz=tzfile('%2Fusr%2Fshare%2Fzoneinfo%2FAsia%2FTokyo')&commits=3701a9b1bfc3ad3890c2fb1fe1974a4768f6d5f8-522f855a38d52763c4e2b07480786163b91dad38&x-axis-scale=date&x-axis=commit)) In which case it might be something to ignore?

**Comment by lidavidm** [comment]
Probably because of the copy. As originally written, the patch did not involve the copy, if that's worth testing. UTC might be a fairly common timezone to run into as well.

(Side note, that's some super impressive benchmark infrastructure!)

**Comment by jbrockmendel** [comment]
It makes sense that the copy would hurt perf, but we would still expect the UTC case to be more performant than any of the other cases, which it no longer is

**Comment by lidavidm** [comment]
This is the patch without the copy:

```diff
From b4a1de2988ad85c92a705a9a131f0573696a94fd Mon Sep 17 00:00:00 2001
From: David Li <li.davidm96@gmail.com>
Date: Mon, 3 Aug 2020 16:06:32 -0400
Subject: [PATCH] BUG: handle immutable arrays in tz_convert_from_utc (#35530)

---
 pandas/_libs/tslibs/tzconversion.pyx | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

diff --git a/pandas/_libs/tslibs/tzconversion.pyx b/pandas/_libs/tslibs/tzconversion.pyx
index 2b148cd88..2b24982d9 100644
--- a/pandas/_libs/tslibs/tzconversion.pyx
+++ b/pandas/_libs/tslibs/tzconversion.pyx
@@ -410,7 +410,7 @@ cpdef int64_t tz_convert_from_utc_single(int64_t val, tzinfo tz):
         return val + deltas[pos]
 
 
-def tz_convert_from_utc(int64_t[:] vals, tzinfo tz):
+def tz_convert_from_utc(const int64_t[:] vals, tzinfo tz):
     """
     Convert the values (in i8) from UTC to tz
 
@@ -424,7 +424,7 @@ def tz_convert_from_utc(int64_t[:] vals, tzinfo tz):
     int64 ndarray of converted
     """
     cdef:
-        int64_t[:] converted
+        const int64_t[:] converted
 
     if len(vals) == 0:
         return np.array([], dtype=np.int64)
@@ -435,7 +435,7 @@ def tz_convert_from_utc(int64_t[:] vals, tzinfo tz):
 
 @cython.boundscheck(False)
 @cython.wraparound(False)
-cdef int64_t[:] _tz_convert_from_utc(int64_t[:] vals, tzinfo tz):
+cdef const int64_t[:] _tz_convert_from_utc(const int64_t[:] vals, tzinfo tz):
     """
     Convert the given values (in i8) either to UTC or from UTC.
 
@@ -457,7 +457,7 @@ cdef int64_t[:] _tz_convert_from_utc(int64_t[:] vals, tzinfo tz):
         str typ
 
     if is_utc(tz):
-        converted = vals
+        return vals
     elif is_tzlocal(tz):
         converted = np.empty(n, dtype=np.int64)
         for i in range(n):
-- 
2.28.0
```

**Comment by jreback** [comment]
@lidavidm care to do a PR?

**Comment by lidavidm** [comment]
Will do, sorry about the delay here
