### ISSUE TITLE
BUG: error in reduction.pyx file while building pandas from source with setup.py file

### ISSUE THREAD

**Issue by akshaymanu007** [pandas-dev/pandas#35817]
I am compiling pandas1.10 from source with the help of setup.py

It is showing me following error in reduction.pyx file 

        self.orig_data = self.buf.data
        self.orig_len = self.buf.shape[0]
        self.orig_stride = self.buf.strides[0]

        self.buf.data = self.values.data
               ^
------------------------------------------------------------

pandas/_libs/reduction.pyx:313:16: Assignment to a read-only property

Error compiling Cython file:

enviornment :  Linux opensuze
python version : 3.7.9

**Comment by bashtage** [comment]
You need to use Cython < 3.

**Comment by bashtage** [comment]
xref #35675

**Comment by akshaymanu007** [comment]
I am using 3.0a6 version but still it is giving error

**Comment by bashtage** [comment]
That is Cython 3.  You need to use Cython < 3 which means Cython 0.29.x (usually 0.29.21).
