### ISSUE TITLE
CI: Failures due to pyarrow 0.11 in Travis 37 Locale Build 

### ISSUE THREAD

**Issue by alimcmaster1** [pandas-dev/pandas#35813]
Looks like recently the Travis 37 Locale Build has started picking up pyarrow 0.11.1

https://travis-ci.org/github/pandas-dev/pandas/jobs/719430999
pyarrow                   0.11.1           py37he6710b0_0 

This causes the pyarrow tests to run which seem to be failing.

Previously no pyarrow in env: https://travis-ci.org/github/pandas-dev/pandas/jobs/719138849 (passing build)

Feels like one of our deps has started to depend to pyarrow.

**Comment by jorisvandenbossche** [comment]
It's this one? -> https://github.com/pandas-dev/pandas/blob/master/ci/deps/travis-37-locale.yaml (I don't directly see something in it that would depend on Arrow)

**Comment by jorisvandenbossche** [comment]
Comparing the output of `conda list` for the working vs failing build, it's google-bigquery client that changed, and indeed that now depends on arrow: https://github.com/conda-forge/google-cloud-bigquery-feedstock/blob/master/recipe/meta.yaml 
(there seems to be a google-cloud-bigquery-core package that doesn't depend on pyarrow, though)

But the question is also, why does it install such an old version of pyarrow.
