### ISSUE TITLE
BUG: Unable to build Pandas on z/OS when using xlc

### ISSUE THREAD

**Issue by pitmanst** [pandas-dev/pandas#35826]
- [x] I have checked that this issue has not already been reported

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Problem description

When building Pandas using xlc on z/OS, it errors out with the following message:

```
"pandas/_libs/window/aggregations.cpp", line 25295.13: CCN5888 (S) The current option settings do not allow the use of "long long". The suffix of the integer literal "1LL" is not valid.
```

This seems to be due to xlc++ needing specific options to be set when building the c++ code (need to swap the language standard to one that supports long long). However, after adding this via CFLAGS, it'll then error out with the following:

```
 "pandas/_libs/window/aggregations.cpp", line 5461.18: CCN5130 (S) "std::__class" is not declared.
  "pandas/_libs/window/aggregations.cpp", line 5548.18: CCN5130 (S) "std::__class" is not declared.
  "pandas/_libs/window/aggregations.cpp", line 6783.16: CCN5130 (S) "std::__class" is not declared.
  "pandas/_libs/window/aggregations.cpp", line 19752.16: CCN5130 (S) "std::__class" is not declared.
```

While the error messages are different and is on a different platform/OS, this issue might be related to https://github.com/pandas-dev/pandas/issues/35123. I haven't tested on AIX so cannot confirm this however. FYI - @aixtools - since this will need a fix for xlc on z/OS, it seems likely that it will apply to AIX as well. What it seems to be is that there is support for those functions within xlc, but they're not placed within the std:: namespace (macros from older standards). 

Since there's two build errors here for z/OS, I'll be opening this issue rather than dup'ing the other issue.

**Comment by bashtage** [comment]
Do you have an old xlc or are you up to date? I think older xlc is likely
missing some c++ features required.

**Comment by pitmanst** [comment]
I'm using the latest version of xlc & xlc++ to build Pandas currently.

For reference, there's two different c & c++ compilers currently supported on z/OS. There's xlc/xlc++, and xlclang/xlclang++. xlc Only has moderate support of c++11, which fails to build Pandas currently - I have a patch which will be ready shortly which works around this. I also tested xlclang/xlclang++, and it works fine for building Pandas.
