### ISSUE TITLE
BUG: Same Directory copy.py incompatibility.

### ISSUE THREAD

**Issue by Tazarus** [pandas-dev/pandas#35827]
#### Problem description
If you are importing pandas into a script which shares a folder with another python script named copy.py pandas fails to import and the script cannot execute.

I would recommend changing the duplicate name in the pandas code to something less accidentally callable (perhaps simply add a few numbers or symbols afterward), but overall this is a very minor issue that I suspect very few people will run into.

- [Yes] I have checked that this issue has not already been reported.

- [Yes] I have confirmed this bug exists on the latest version of pandas.

- [No] (optional) I have confirmed this bug exists on the master branch of pandas.
Apologies unsure how.
---

#### Code Sample

```python
import pandas as pd
print(yes)
```

#### Expected Output
```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Coding\JetBrains\PyCharm 2020.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Coding\JetBrains\PyCharm 2020.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Christian/PycharmProjects/pythonProject/Workspace.py", line 1, in <module>
    import pandas as pd
  File "C:\Coding\JetBrains\PyCharm 2020.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Anaconda3\envs\pythonProject\lib\site-packages\pandas\__init__.py", line 52, in <module>
    from pandas.core.api import (
  File "C:\Coding\JetBrains\PyCharm 2020.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Anaconda3\envs\pythonProject\lib\site-packages\pandas\core\api.py", line 15, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Coding\JetBrains\PyCharm 2020.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Anaconda3\envs\pythonProject\lib\site-packages\pandas\core\arrays\__init__.py", line 10, in <module>
    from pandas.core.arrays.interval import IntervalArray
  File "C:\Coding\JetBrains\PyCharm 2020.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Anaconda3\envs\pythonProject\lib\site-packages\pandas\core\arrays\interval.py", line 43, in <module>
    from pandas.core.indexes.base import ensure_index
  File "C:\Coding\JetBrains\PyCharm 2020.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Anaconda3\envs\pythonProject\lib\site-packages\pandas\core\indexes\base.py", line 1, in <module>
    from copy import copy as copy_func
ImportError: cannot import name 'copy' from 'copy' (C:\Users\Christian\PycharmProjects\pythonProject\copy.py)

```
#### Output of ``pd.show_versions()``

<details>
Note: This is my first attempt at bug reporting, and am very new to this, and I don't have as much time as I would have liked to ensure I'm posting this in the correct place. If this should be reported to JetBrains instead or simply somewhere else on the site please let me know and I'll do my best to update/fix it promptly. 

I am using Jetbrains Pycharm Professional IDE and found that having a python file named copy.py in the same project folder (windows folder) causes some kind of check/name confusion when pandas is importing. This happened by accident as I have been lately using copy.py as a dummy backup of working versions of code while working on improvements. I discovered the issue by accident.

A screenshot of the issue
![image](https://user-images.githubusercontent.com/69982590/90804338-7ae3cf80-e2f0-11ea-92a3-ca06ec65bc2c.png)

A screenshot of the issue not occurring under identical circumstances but when copy.py is renamed to copy2.py
![image](https://user-images.githubusercontent.com/69982590/90804431-96e77100-e2f0-11ea-8a6b-24b4de70b128.png)

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]
INSTALLED VERSIONS
------------------
commit           : d9fff2792bf16178d4e450fe7384244e50635733
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
machine          : AMD64
processor        : AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_Canada.1252
pandas           : 1.1.0
numpy            : 1.19.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.2
setuptools       : 49.6.0.post20200814
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : None
pandas_datareader: None
bs4              : 4.9.1
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by bashtage** [comment]
This is python. I don't think there is just to do. I often get hit by this in Pycharm when I work on modules in io where json and io both conflict.

**Comment by Tazarus** [comment]
So does that mean is essentially a fundamental python naming conflict and isn't something that's 1.) really work fixing, or 2.) possible to fix easily?

**Comment by TomAugspurger** [comment]
It's a fundamental python thing. In general you shouldn't have modules that mirror names of packages (especially from the standard library). Typically you'd name it `copy_.py`.

**Comment by Tazarus** [comment]
Cool, thanks guys for the quick replies. 

Apologies for any wasted time.

Cheers.
