### ISSUE TITLE
QST: CSV read issue

### ISSUE THREAD

**Issue by sarthakpan** [pandas-dev/pandas#35820]
suppose my csv has data
2 83 02
" 12 29
3 82 10
” 38 92
½ 29 39

and so on..

if I use pd.read_csv('file.csv')
then it gives EOF error.
I tried encoding UTF-8 but it doesn't worked.
The only way i figured out is by manually opening the file.
Please suggest an idea how to open this kind of Measurement kind of Data file.

**Comment by bashtage** [comment]
That single double quote is a problem.

**Comment by sarthakpan** [comment]
> That single double quote is a problem. What are you expecting the dataframe to look like?

I want my pandas Dataframe should contain every character as a single character
pandas df should look like this:
0 | 1 | 2
-----------
2 | 83 | 02
" | 12 | 29
3 | 82 |10
” | 38 | 92
½ | 29 | 39

**Comment by bashtage** [comment]
Have you tried setting the `sep` to white space? Is your file really fixed width?  It is is, you might use `read_fwf`

**Comment by sarthakpan** [comment]
> Have you tried setting the `sep` to white space? Is your file really fixed width? It is is, you might use `read_fwf`

Yes, I have tried, you just copy-paste that data and try to import into DF you will understand my problem. My problem is with those non-standard characters in the first column.

**Comment by twoertwein** [comment]
@sarthakpan have you tried opening the CSV file with `quoting=csv.QUOTE_NONE`. The following works for me:

```py
import csv
import pandas as pd

pd.read_csv("test.csv", quoting=csv.QUOTE_NONE)
```

**Comment by phofl** [comment]
Yes, ``csv.QUOTE_NONE`` is for these cases.
