### ISSUE TITLE
DOC: pandas.Series.transform

### ISSUE THREAD

**Issue by onshek** [pandas-dev/pandas#35870]
#### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.Series.transform.html?highlight=pandas%20series%20transform#pandas.Series.transform

**Note**: You can check the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/).

#### Documentation problem

> list of functions and/or function names, e.g. [np.exp. 'sqrt']

#### Suggested fix for documentation

list of functions and/or function names, e.g. [np.exp, 'sqrt']

**Comment by MarcoGorelli** [comment]
sure, feel free to submit a PR
