### ISSUE TITLE
QST:

### ISSUE THREAD

**Issue by 1994Shankar** [pandas-dev/pandas#35886]
import pandas as pd
import xlrd
book = xlrd.open_workbook("Excel_to_panda.xlsx")

getting below error:-

/usr/local/bin/python3.8 /Users/bhabanishankarkar/PycharmProjects/untitled/hello.py
Traceback (most recent call last):
  File "/Users/bhabanishankarkar/PycharmProjects/untitled/hello.py", line 71, in <module>
    book = xlrd.open_workbook("Excel_to_panda.xlsx")
  File "/Users/bhabanishankarkar/Library/Python/3.8/lib/python/site-packages/xlrd/__init__.py", line 145, in open_workbook
    raise XLRDError('ZIP file contents not a known type of workbook')
xlrd.biffh.XLRDError: ZIP file contents not a known type of workbook

Process finished with exit code 1

Can anyone help with this?

**Comment by jbrockmendel** [comment]
Have you tried opening it with openpyxl?

**Comment by MarcoGorelli** [comment]
please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question. Will reopen if you can provide it

besides, this question is unrelated to pandas, which (other than importing it) you don't use in your example
