### ISSUE TITLE
DOC: pandas.Series.filter talks about dataframe not series

### ISSUE THREAD

**Issue by notestaff** [pandas-dev/pandas#35892]
#### Location of the documentation
https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.Series.filter.html

[this should provide the location of the documentation, e.g. "pandas.read_csv" or the URL of the documentation, e.g. "https://dev.pandas.io/docs/reference/api/pandas.read_csv.html"]

**Note**: You can check the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/).

#### Documentation problem

Documentation talks about dataframe, not series
[this should provide a description of what documentation you believe needs to be fixed/improved]

#### Suggested fix for documentation

[this should explain the suggested fix and **why** it's better than the existing documentation]
Replace with the correct documentation for Series.

**Comment by TomAugspurger** [comment]
Thanks. Many of our docstrings are shared between Series and DataFrame. This one mentions the different behavior for Series and DataFrame.

We'd certainly take improvements to clarify this (maybe a Series example), but we have other issues for general improvements to the docstring.
