### ISSUE TITLE
BUG: ValueError: Of the four parameters: start, end, periods, and freq, exactly three must be specified

### ISSUE THREAD

**Issue by malapradej** [pandas-dev/pandas#35890]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here

```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by bashtage** [comment]
Can you provide a copy-pastable demo of the issue by editing your post.

**Comment by MarcoGorelli** [comment]
This issue brings "needs info" to another level :)

See [https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) for how to write a bug report, will reopen if you write one
