### ISSUE TITLE
BUG: DataFrame([]).squeeze() returns DataFrame instead of Series

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#35896]

**Comment by TomAugspurger** [comment]
What's the use-case here?  It's a bit unclear what the best outcome should be, since squeeze operates on length-1 axes, but not >1. I'm not sure what length-0 axes should do.

NumPy has this behavior,

```python
In [37]: np.squeeze(np.ones(shape=(0, 0)))
Out[37]: array([], shape=(0, 0), dtype=float64)
```

which perhaps matches ours?

**Comment by jbrockmendel** [comment]
Fair enough
