### ISSUE TITLE
BUG: sorting dataframe increases memory usage

### ISSUE THREAD

**Issue by tacitvenom** [pandas-dev/pandas#35909]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python

import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(0,4000,size=(1000, 4)), columns=list('ABCD'))
print(df.memory_usage(index=True).sum())
df = df.sort_values(['A', 'B'])
print(df.memory_usage(index=True).sum())

```

Output:
32128
40000

#### Problem description

The dataframe is essentially same rows and same dtypes, just sorted. Why should the sorted df be bigger?
I understand that during sorting, a copy is created so the memory consumption increases but once sorting is finished, that should be back to where it was. Here, the memory usage of the dataframe increased from 31KB to 40 KB for this toy example.

#### Expected Output
The memory usage of sorted pandas dataframe should be similar to what it was before sorting.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.76-linuxkit
machine          : x86_64
processor        :
byteorder        : little
LC_ALL           : C.UTF-8
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.5
numpy            : 1.19.0
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 49.2.0
Cython           : None
pytest           : 6.0.0
hypothesis       : 5.16.1
sphinx           : 1.6.7
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.5 (dt dec pq3 ext lo64)
jinja2           : 2.11.2
IPython          : 7.15.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.2.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.13.0
pytables         : None
pytest           : 6.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.18
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by TomAugspurger** [comment]
It's coming from the Index. After you sort you don't have a RangeIndex anymore, just a regular Int64Index, which takes more memory. If you specify `memory_usage(index=False)` or reset the index it'll be the same.

**Comment by tacitvenom** [comment]
Updated the description, the issue still persists.
