### ISSUE TITLE
Datetime error

### ISSUE THREAD

**Issue by ayushsom96** [pandas-dev/pandas#35903]
### Can you please let me know how I can correct the following error
**CODE:**
tx_data['InvoiceDate'] = pd.to_datetime(tx_data['InvoiceDate'])
tx_uk = tx_data.query("Country=='United Kingdom'").reset_index(drop=True)

#create 3m and 6m dataframes
tx_3m = tx_uk[(tx_uk.InvoiceDate < date(2011,6,1)) & (tx_uk.InvoiceDate >= date(2011,3,1))].reset_index(drop=True)
tx_6m = tx_uk[(tx_uk.InvoiceDate >= date(2011,6,1)) & (tx_uk.InvoiceDate < date(2011,12,1))].reset_index(drop=True)

**ISSUE:**
 32     else:
     33         typ = type(right).__name__
---> 34         raise TypeError(f"Invalid comparison between dtype={left.dtype} and {typ}")
     35     return res_values
     36

**TypeError: Invalid comparison between dtype=datetime64[ns] and date**

**Comment by MarcoGorelli** [comment]
Thanks for the report - I suspect it's because you've done `from datetime import datetime`. If not, please see here [https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) for how to provide a bug report

**Comment by ayushsom96** [comment]
> Thanks for the report - I suspect it's because you've done `from datetime import datetime`. If not, please see here https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports for how to provide a bug report

**Comment by ayushsom96** [comment]
Thank you @MarcoGorelli. I tried correcting the code to minimalize the errors. However, I'm still stuck with the same line but with a different error. Please review.
