### ISSUE TITLE
BUG: .astype(int) converts values to negative at large integer values.

### ISSUE THREAD

**Issue by jetilton** [pandas-dev/pandas#35911]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas as pd
df = pd.DataFrame({"ints":[2**x for x in range(50)]})
df["ints"].astype(int)
```

#### Problem description

`astype(int)` converts values to negative at 2**31 power and 0 afterwards.

#### Expected Output
`[int(x) for x in df["ints"].values]`

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f2ca0a2665b2d169c97de87b8e778dbed86aea07
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.17763
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.1.1
numpy            : 1.17.3
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.2.2
setuptools       : 42.0.2.post20191201
Cython           : None
pytest           : 6.0.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.10.2
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by asishm** [comment]
`.astype(int)` I believe defaults to numpy's default int which is int32 on Windows

`df["ints"].astype('int64')` produces what you expect

**Comment by jreback** [comment]
of course, int32 is limited to about 2B

you are windows so you should be explicit about using int64
