### ISSUE TITLE
BUG: Dataframe slicing incosistent behavior when using & operator

### ISSUE THREAD

**Issue by henrypinkard** [pandas-dev/pandas#35916]
- [ ] I have checked that this issue has not already been reported.

Not familiar enough with pandas to know what to search for to verify this

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Problem description

There seems to be a bug with indexing into DataFrames using logical and. When I do the operations in series, like this, it works, giving two rows:

```
slidescan_db = pd.read_csv('slidescan_db.csv')
db = slidescan_db[slidescan_db['Stain'].str.contains('unstained').fillna(False)]
db[db['Batch'] == batch_index]
```

But when I do it with a one-liner, it gives a different result--no rows

```
slidescan_db = pd.read_csv('slidescan_db.csv')
slidescan_db[slidescan_db['Batch'] == batch_index & slidescan_db['Stain'].str.contains(ch_name).fillna(False)]
```

slidescan_db.csv is attached, but renamed to slidescan.txt because GitHub wouldn't let me upload a csv

[slidescan_db.txt](https://github.com/pandas-dev/pandas/files/5133799/slidescan_db.txt)

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f2ca0a2665b2d169c97de87b8e778dbed86aea07
python           : 3.7.0.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
Version          : Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.1
numpy            : 1.18.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.2.0.post20200511
Cython           : 0.29.17
pytest           : 5.4.2
hypothesis       : 5.11.0
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.2.8
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.7.5 (dt dec pq3 ext lo64)
jinja2           : 2.11.2
IPython          : 7.13.0
pandas_datareader: None
bs4              : 4.9.0
bottleneck       : 1.3.2
fsspec           : 0.7.1
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.1
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.16
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.49.0
</details>

**Comment by bashtage** [comment]
Can you make your example code copy and pastable?

**Comment by henrypinkard** [comment]
```
import pandas as pd
batch_index = 2
slidescan_db = pd.read_csv('slidescan_db.csv')
db = slidescan_db[slidescan_db['Stain'].str.contains('unstained').fillna(False)]
db[db['Batch'] == batch_index]
```

But when I do it with a one-liner, it gives a different result--no rows

```
import pandas as pd
batch_index = 2
slidescan_db = pd.read_csv('slidescan_db.csv')
slidescan_db[slidescan_db['Batch'] == batch_index & slidescan_db['Stain'].str.contains('unstained').fillna(False)]
```

**Comment by asishm** [comment]
I haven't run it, but this looks like a case of missing parenthesis when chaining the two masks

Can you try this?

`slidescan_db[(slidescan_db['Batch'] == batch_index) & slidescan_db['Stain'].str.contains('unstained').fillna(False)]`

**Comment by henrypinkard** [comment]
Oh yeah, duh.

Thanks!
