### ISSUE TITLE
DOC: Aggregate and rename is undocumented

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#35912]
The function `DataFrame.agg` allows for kwargs to aggregate and rename the results.

    df = pd.DataFrame({'a': [1, 2, 3]})
    print(df.agg(a_new=('a', 'sum')))

results in

           a
    a_new  6

Perhaps I'm missing it, but I can't find it in both the API reference and the User Guide.

**Comment by onshek** [comment]
I'm willing to take it.
