### ISSUE TITLE
DOC: "engine=odf" option should ask you to install pyodf instead of odf in pandas.read_excel

### ISSUE THREAD

**Issue by TrigonaMinima** [pandas-dev/pandas#35948]
#### Location of the documentation

"pandas.read_excel"

#### Documentation problem

When `engine="odf"` is used and `pyodf` is not installed it gives an error that you should install optional dependency odf as `pip or conda install odf`. This pip/conda command fails because there's no module called `odf`. This could also be a security vulnerability if someone puts a malicious "odf" module on pypi.

#### Suggested fix for documentation

The error should ask you to install odf using `pip or conda install pyodf`

**Comment by TomAugspurger** [comment]
Do you mean `odfpy` rather than `pyodf`?

We'll need to update https://github.com/pandas-dev/pandas/blame/master/pandas/compat/_optional.py#L48-L50 to take an optional package name argument.

**Comment by hs2361** [comment]
Hello, I am new to the community, and I would like to work on this issue. May I take this issue?

**Comment by hs2361** [comment]
Please review my changes made in the commit.

**Comment by arw2019** [comment]
@hs2361 can you open a pull request and link to this isssue

**Comment by hs2361** [comment]
I have opened a pull request. Please review my code, and please notify me of changes to be made.
