### ISSUE TITLE
QST: to_excel() deletes the existed sheets

### ISSUE THREAD

**Issue by MFalghanmi** [pandas-dev/pandas#35969]
- As per Pandas [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_excel.html), the to_excel() deletes the existed sheets in the excel document using the code below. I am not sure what is the issue.
```python
with pd.ExcelWriter('pay_past_5_years.xlsx', mode='a') as writer:  
    df.to_excel(writer, sheet_name='Sheet_name_3')
```
- The second question the mode is give error when using small 'a' char in mode. Here tip was found in [stackoverflow](https://stackoverflow.com/questions/54863238/pandas-excelwriter-valueerror-append-mode-is-not-supported-with-xlsxwriter/55683301)
```python
ValueError: Append mode is not supported with xlsxwriter!
````
**The Pandas version is 1.0.5**

Thank you

**Comment by rhshadrach** [comment]
It seems your question is "why does xlsxwriter not support appending?", is that accurate? I think that would be a question for xlsxwriter, not pandas. As mentioned in the SO post that you linked to, openpyxl can append.

**Comment by MFalghanmi** [comment]
> It seems your question is "why does xlsxwriter not support appending?", is that accurate? I think that would be a question for xlsxwriter, not pandas. As mentioned in the SO post that you linked to, openpyxl can append.

Hey @rhshadrach Thank you for your comment. However, the main issue is that ExcelWriter deleted existed sheets in the file. So I am not sure how it is related to xlsxwriter

Thank you

**Comment by jbrockmendel** [comment]
>  However, the main issue is that ExcelWriter deleted the existed sheets in the file. So I am not sure how it is related to xlsxwriter

pandas.ExcelWriter is a thin wrapper around xlsxwriter.

IIUC xlsx is xml-like under the covers, which would be difficult to append to.  I imagine its easier to re-write the entire file than try to append in place.

**Comment by jeet-parekh** [comment]
I see it doesn't delete the existing sheets in pandas 1.1.1

**Comment by MFalghanmi** [comment]
Hey, @jeet-parekh 
I did upgrade the version, but I am still facing the same issue.
```
with pd.ExcelWriter(file_path,   mode='A') as writer:
    df.to_excel(writer, sheet_name="name_of_sheet")
```
```
print(pd.__version__)
1.1.1
```

**Comment by TomAugspurger** [comment]
@MFalghanmi can you provide a reproducible example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by jeet-parekh** [comment]
@TomAugspurger, I was able to reproduce this.

```python
import pandas as pd

df = pd.DataFrame({"col1": [1, 2, 3]})

with pd.ExcelWriter("df.xlsx") as writer:
    df.to_excel(writer, sheet_name="sheet_1")
    df.to_excel(writer, sheet_name="sheet_2")

from_excel = pd.read_excel("df.xlsx", sheet_name=None)
print(f"sheets read: {len(from_excel)}")

with pd.ExcelWriter("df.xlsx", mode="A") as writer:
    df.to_excel(writer, sheet_name="sheet_3")

from_excel = pd.read_excel("df.xlsx", sheet_name=None)
print(f"sheets read: {len(from_excel)}")
```

Note the use of capital A for the mode argument. There's a check for `a`, but not `A`. So it proceeds to open the file in write mode.

**Comment by TomAugspurger** [comment]
I don't think that `'A'` is a valid file mode, unless xlsxwriter is doing special with it.

**Comment by jeet-parekh** [comment]
Right, xlsxwriter does not support appends. But the ExcelWriter constructor defaults to xlsxwriter. Even though I have both xlsxwriter and openpyxl installed.

And it's not clear from the [ExcelWriter docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.ExcelWriter.html) that append is not supported for xlsxwriter. `mode='a'` will raise an exception. Any other mode, whether or not valid, will turn into write mode.

Even though I didn't open this issue, I'm also confused by this now. The [to_excel docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_excel.html) suggests using ExcelWriter for appends. And ExcelWriter is defaulting to something that doesn't support appends even though the alternative is installed on the system (openpyxl).

**Comment by MFalghanmi** [comment]
Hey @TomAugspurger , @jeet-parekh 

Regarding the 'a' or 'A', please check the this post in [stackoverflow](https://stackoverflow.com/questions/54863238/pandas-excelwriter-valueerror-append-mode-is-not-supported-with-xlsxwriter)

**Comment by TomAugspurger** [comment]
Is pandas doing anything with the `mode` or just passing it to xlsxwriter? If we're just passing it through I'd recommend raising an issue with xlsxwriter to validate that the mode isn't nonsense.

**Comment by MFalghanmi** [comment]
> 
> 
> @MFalghanmi can you provide a reproducible example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. When you say "deletes existing sheets" do you mean the sheet `sheet_name` or other ones in the same workbook?

Thank you for the link @TomAugspurger.
The 'sheet_name' is the new sheet that is needed to be add to the existing excel file.

**Comment by MFalghanmi** [comment]
> 
> 
> Is pandas doing anything with the `mode` or just passing it to xlsxwriter? If we're just passing it through I'd recommend raising an issue with xlsxwriter to validate that the mode isn't nonsense.

![image](https://user-images.githubusercontent.com/43381180/92307256-9fe96b00-ef9d-11ea-8e00-f54308b07510.png)

**Comment by jeet-parekh** [comment]
> Is pandas doing anything with the mode or just passing it to xlsxwriter?

Pandas isn't doing anything with the mode. Also, xlsxwriter isn't doing anything with it either. I don't think the [xlsxwriter workbook](https://xlsxwriter.readthedocs.io/workbook.html) accepts our mode argument at all.

I think the ExcelWriter defaults could be improved. See my [comment above](https://github.com/pandas-dev/pandas/issues/35969#issuecomment-687607651).
> The to_excel docs suggests using ExcelWriter for appends. And ExcelWriter is defaulting to something that doesn't support appends even though the alternative is installed on the system (openpyxl).
