### ISSUE TITLE
BUG: replacement works for object but not string dtype

### ISSUE THREAD

**Issue by yunkypunky** [pandas-dev/pandas#35977]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample

```python
import pandas as pd
import numpy as np

a = pd.DataFrame({'a': ['a', 'b', 'c'], 'b': ['d', '', '']}, dtype='object')
b = pd.DataFrame({'a': ['a', 'b', 'c'], 'b': ['d', '', '']}, dtype='string')

print(a)
a.replace(r'^\s*$', pd.NA, regex=True, inplace=True)
print(a)

print(b)
b.replace(r'^\s*$', pd.NA, regex=True, inplace=True)
print(b)
```

#### Problem description

replace(r'^\s*$', pd.NA, regex=True, inplace=True) works on object dtype, but not on stringdtype

#### Expected Output

Same on both replacement

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by yunkypunky** [comment]
replace(r'^\s*$',pd.NA,regex=True,inplace=True) works on object dtype, but not on stringdtype

Code sample:

import pandas as pd
import numpy as np

a = pd.DataFrame({'a':['a','b','c'],'b':['d','','']},dtype='object')
b = pd.DataFrame({'a':['a','b','c'],'b':['d','','']},dtype='string')

display(a[a['b']==''])
a.replace(r'^\s*$',pd.NA,regex=True,inplace=True)
display(a[a['b']==''])

display(b[b['b']==''])
# b['b'] = b['b'].astype(object)
b.replace(r'^\s*$',pd.NA,regex=True,inplace=True)
display(b[b['b']==''])

Expected output:
Same on both replacement

**Comment by dsaxton** [comment]
@yunkypunky Thanks for the report. This could be a real bug (haven't looked too closely yet) so I think it's worth leaving open for now.

**Comment by yunkypunky** [comment]
I'm using Python 3.8.5 with Pandas 1.1.1

**Comment by cgangwar11** [comment]
This bug is coming because ExtensionBlock doesn't support replacement by regex.
`In [4]: is_extension_array_dtype(pd.Series(["d","d","f"],dtype='string').dtype)
Out[4]: True

In [5]: is_extension_array_dtype(pd.Series(["d","d","f"],dtype='object').dtype)
Out[5]: False
`
Since variable **a** calls replace method of ObjectBlock but variable **b** calls replace method of ExtensionBlock . Hence we see different output because ExtensionBlock doesn't support replacement by regex. Possible solution is to override replace method of superclass block with correct logic

**Comment by dsaxton** [comment]
@cgangwar11 Agreed that extension dtypes should also support replacement with a regex, PR would be welcome

**Comment by simonjayhawkins** [comment]
since [09e2036a63300cc14cb99fc0c839aff8dd80f695] DEPR: CategoricalBlock; combine Block.replace methods (#40527) this no longer silently fails

```
>>> b.replace(r'^\s*$', pd.NA, regex=True, inplace=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/simon/pandas/pandas/core/frame.py", line 5202, in replace
    return super().replace(
  File "/home/simon/pandas/pandas/core/generic.py", line 6686, in replace
    new_data = self._mgr.replace(
  File "/home/simon/pandas/pandas/core/internals/managers.py", line 414, in replace
    return self.apply(
  File "/home/simon/pandas/pandas/core/internals/managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/simon/pandas/pandas/core/internals/blocks.py", line 684, in replace
    return self._replace_regex(to_replace, value, inplace=inplace)
  File "/home/simon/pandas/pandas/core/internals/blocks.py", line 757, in _replace_regex
    replace_regex(new_values, rx, value, mask)
  File "/home/simon/pandas/pandas/core/array_algos/replace.py", line 152, in replace_regex
    f = np.vectorize(re_replacer, otypes=[values.dtype])
  File "/home/simon/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2070, in __init__
    otypes = ''.join([_nx.dtype(x).char for x in otypes])
  File "/home/simon/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2070, in <listcomp>
    otypes = ''.join([_nx.dtype(x).char for x in otypes])
TypeError: Cannot interpret 'StringDtype' as a data type
```
