### ISSUE TITLE
DOC: Update documentation for pd.Interval if string endpoints are not allowed anymore

### ISSUE THREAD

**Issue by souris-dev** [pandas-dev/pandas#36002]
#### Location of the documentation

[https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Interval.html](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Interval.html)

On `master`:
[https://pandas.pydata.org/docs/dev/reference/api/pandas.Interval.html](https://pandas.pydata.org/docs/dev/reference/api/pandas.Interval.html)

#### Documentation problem

The examples in the documentation for `pd.Interval` show in the end that Intervals with string endpoints can also be created. However, when the example is run on `master`, a `ValueError` is raised, saying:

"Only numeric, Timestamp and Timedelta endpoints are allowed when constructing an Interval."

#### Suggested fix for documentation

If Intervals with strings as endpoints are not allowed anymore, this example should be removed from the documentation.

I've confirmed that the docstring still contains this example, so I'd be happy to make a PR for this if we agree.

**Comment by dsaxton** [comment]
Thanks @souris-dev, looks like you are right (and this evidently hasn't worked at least as far back as 0.23.5). PR certainly welcome.
