### ISSUE TITLE
DOC: use single back-ticks for variable, module, function, and class names

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#36006]
EDIT I've rewritten this issue after Joris' comment.

----

Pandas' docstrings are somewhat inconsistent in using single or double back-ticks, e.g. [isin](https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.isin.html?highlight=isin#pandas.DataFrame.isin) has both
```
`values`
```
and
```
``values``
```

In keeping with the [numpydoc docstring guide](https://numpydoc.readthedocs.io/en/latest/format.html), which reads

> Use *italics*, **bold** and ``monospace`` if needed in any explanations (but not for variable names and doctest code or multi-line code). Variable, module, function, and class names should be written between single back-ticks (`numpy`).

, it might be good update docstrings which don't follow this convention, as well as to mention this convention in the pandas docstring guide.

**Comment by jorisvandenbossche** [comment]
In *theory*, this is correct (and consistent within the guide I think). It follows the numpydoc docstring guide: https://numpydoc.readthedocs.io/en/latest/format.html

But of course that doesn't mean we need to follow it (how it gets rendered also depends on your sphinx configuration).

**Comment by MarcoGorelli** [comment]
> In _theory_, this is correct (and consistent within the guide I think). It follows the numpydoc docstring guide: https://numpydoc.readthedocs.io/en/latest/format.html

Thanks, I wasn't aware of that. They make it quite clear which to use:

> Use *italics*, **bold** and ``monospace`` if needed in any explanations (but not for variable names and doctest code or multi-line code). Variable, module, function, and class names should be written between single back-ticks (`numpy`).

Pandas' docstrings seem to jump between the two, e.g. [isin](https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.isin.html?highlight=isin#pandas.DataFrame.isin) has both
```
`values`
```
and
```
``values``
```

So, perhaps this should be changed to encourage easy contributions to be more consistent about this in the docstrings?

**Comment by swapniljha001** [comment]
Which file should be edited to reflect the changes mentioned here?

**Comment by MarcoGorelli** [comment]
> Which file should be edited to reflect the changes mentioned here?

Perhaps just mention in the docstring guide that it's preferrable to use single quotes for variable, module, function, and class names - then at least there's some kind of rule in the docstring guide and going forward it can be referenced
