### ISSUE TITLE
BUG: Read_Parquet replacing values with None

### ISSUE THREAD

**Issue by jaded-1** [pandas-dev/pandas#36019]
Tried reading a parquet file with data below. However, I see that some of the topics are replaced with None in the dataframe and I'm not sure what's causing this. This happens for only some rows.

example.parquet:
   {
        "id": "035f57ed-ef07-4ec1-b8d4-04453b9b8fa1",
        "topics": [
            "GOVERNMENT",
            "ECONOMY",
            "POLITICS"
        ]
    },...
```
import pandas as pd

s3_path = 's3://test-bucket/example.parquet'
df = pd.read_parquet(s3_path)
df[['id', 'topics']][df['id'] == '035f57ed-ef07-4ec1-b8d4-04453b9b8fa1'].values

result:
array([['035f57ed-ef07-4ec1-b8d4-04453b9b8fa1',
        array(['GOVERNMENT', 'ECONOMY', None], dtype=object)]],
      dtype=object)
```

**Comment by jorisvandenbossche** [comment]
@jaded-1 can you try to provide a reproducible example? (see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) For example, do you also have it with a local file (and not from S3)? And if so, can you reproduce it by writing a file to parquet and reading it back?

**Comment by MarcoGorelli** [comment]
Closing as it's hard to know what to do here, but if you write a reproducible example we can take a look
