### ISSUE TITLE
QST: is the new behavior of GroupByRolling for MultiIndex in v1.1.1 intended?

### ISSUE THREAD

**Issue by itholic** [pandas-dev/pandas#36018]
#### Question about pandas

Let's say we have a `Series` with `MultiIndex` like the below.

```python
>>> pser = pd.Series(
...     [1, 2, 3, 2],
...     index=pd.MultiIndex.from_tuples([("a", "x"), ("a", "y"), ("b", "z"), ("c", "z")]),
...     name="a",
... )

>>> pser
a  x    1
   y    2
b  z    3
c  z    2
Name: a, dtype: int64
```

Then, when I use `GroupByRolling`, In the version of pandas <= 1.0.5 shows result as below.
(Let's focus on the level of `MultiIndex` in the examples below)

```python
>>> pser.groupby(pser).rolling(2).max()
a
1  a  x    NaN
2  a  y    NaN
   c  z    2.0
3  b  z    NaN
Name: a, dtype: float64

>>> pser.groupby(pser).rolling(2).max().index
MultiIndex([(1, 'a', 'x'),
            (2, 'a', 'y'),
            (2, 'c', 'z'),
            (3, 'b', 'z')],
           names=['a', None, None])

>>> pser.groupby(pser).rolling(2).max().index.nlevels  # It keeps the index level.
3
```

However, In the pandas 1.1.0, the result seems different from the previous version as below.
(The level of `MultiIndex` is decreased after performing)

```python
>>> pser.groupby(pser).rolling(2).max()
a
1  (a, x)    NaN
2  (a, y)    NaN
   (c, z)    2.0
3  (b, z)    NaN
Name: a, dtype: float64

>>> pser.groupby(pser).rolling(2).max().index
MultiIndex([(1, ('a', 'x')),
            (2, ('a', 'y')),
            (2, ('c', 'z')),
            (3, ('b', 'z'))],
           names=['a', None])

>>> pser.groupby(pser).rolling(2).max().index.nlevels  # index level changed from 3 to 2
2
```

Is it intended behavior in pandas 1.1.1. ??

Thanks :)

**Comment by TomAugspurger** [comment]
Hard to say, but probably not intentional. Are you able to bisect 1.1.0 to 1.1.1 to see what changed?

**Comment by phofl** [comment]
I looked into this and found, that the index names also get lost now:



```
a        
1  (a, x)    NaN
2  (a, y)    NaN
   (c, z)    2.0
3  (b, z)    NaN
Name: a, dtype: float64
```

while with 1.0.5

```
a  1  2
1  a  x    NaN
2  a  y    NaN
   c  z    2.0
3  b  z    NaN
Name: a, dtype: float64
```

Input was:

```
pser = pd.Series(
     [1, 2, 3, 2],
     index=pd.MultiIndex.from_tuples([("a", "x"), ("a", "y"), ("b", "z"), ("c", "z")], names=["1", "2"]),
     name="a")
```


Method which constructs the index is completely new, so there is no single thing which changed

**Comment by rhshadrach** [comment]
@mroeschke Looks like this is a regression and so should be tagged 1.1.2, is that right?

**Comment by simonjayhawkins** [comment]
#34052

https://github.com/simonjayhawkins/pandas/runs/1078593349?check_suite_focus=true

bad52a9d1ef9fe6b27ef44fae99f483d07ad16f6 is the first bad commit
commit bad52a9d1ef9fe6b27ef44fae99f483d07ad16f6
Author: Matthew Roeschke <emailformattr@gmail.com>
Date:   Mon May 25 10:26:19 2020 -0700

    PERF: Use Indexers to implement groupby rolling (#34052)
