### ISSUE TITLE
Coverting bug by null values from csv into panda nan to a python list

### ISSUE THREAD

**Issue by Kaufhold** [pandas-dev/pandas#36033]
Hello,
I read a csv file with panda and convert it to a python list.
The problem is that panda convert the null values from the csv to nan values.
After that I convert the panda dataframe to a python nested list and got nan values inside the python list that have the float type. 

Code:
`for chunk in pd.read_csv(pfad_incoming + record, chunksize=1000000, delimiter=';', quotechar="'",                                  escapechar='"'):

batch = [chunk.columns.values.tolist()] + chunk.values.tolist()`

A column:
[5000000026661893028, 26661987940, '2020-07-09 10:40:10.435000', 1, nan, nan, nan, nan, nan, nan, nan, nan, 'v5', nan]
The type of the nan values:
<class 'float'>

Is that a bug? In the python list, however, should nan be None, right?
Regards,
Phil

**Comment by TomAugspurger** [comment]
Can you provide a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by nishithshowri006** [comment]
![image](https://user-images.githubusercontent.com/58651995/92069646-7c6cc780-edc7-11ea-8375-ce7c36b906b8.png)
@TomAugspurger I think this is what @Kaufhold  want to ask when we convert a Series or a Dataframe to a list nan value is showing up insead of None.

**Comment by TomAugspurger** [comment]
That's pandas' type inference, and isn't something we can really change. The list `[1, 2, None]` is inferred to be floating point, while `[None, None]` is inferred to be object.

You can specify `dtype=` if pandas' inference isn't what you want.
