### ISSUE TITLE
BUG: wrong plotting in x-axis when index set to date

### ISSUE THREAD

**Issue by saturn99** [pandas-dev/pandas#36030]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

in `mydata` i have't no any data between `2000-01-03` to `2020-01-01`

but pandas wrong plotting in x-axis when index set to date

```python
d1 = [ '2000-01-01', 5 ]
d2 = [ '2000-01-02', -5 ]
d3 = [ '2020-01-02', 5 ]
mydata = pd.DataFrame( [d1,d2,d3] , columns=["DATE","DATA"] )

mydata["DATE"] = pd.to_datetime( mydata["DATE"] )
mydata = mydata.set_index("DATE")

mydata.plot()
```
![index](https://user-images.githubusercontent.com/5188799/91824221-a8fdd380-ec4f-11ea-8837-66d039ec792d.png)

#### Expected Output

```python
d1 = [ '2000-01-01', 5 ]
d2 = [ '2000-01-02', -5 ]
d3 = [ '2020-01-02', 5 ]
mydata = pd.DataFrame( [d1,d2,d3] , columns=["DATE","DATA"] )

# mydata["DATE"] = pd.to_datetime( mydata["DATE"] )
mydata = mydata.set_index("DATE")

mydata.plot()
```
![index](https://user-images.githubusercontent.com/5188799/91824423-fda14e80-ec4f-11ea-9eda-d5988d18eb2a.png)

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f2ca0a2665b2d169c97de87b8e778dbed86aea07
python           : 3.8.1.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.9.0-7-amd64
Version          : #1 SMP Debian 4.9.110-1 (2018-07-05)
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.utf8
LOCALE           : en_US.UTF-8

pandas           : 1.1.1
numpy            : 1.18.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.2.2
setuptools       : 49.6.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.2.9
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: None
bs4              : 4.9.0
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.2.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by TomAugspurger** [comment]
I don't think your expected is correct. Your plot makes it look like 2000-01-02 is halfway between 2000-01-01 and 2020-01-02. We plot dates as there numerical values.
