### ISSUE TITLE
BUG: Index.equals returns incorrect result

### ISSUE THREAD

**Issue by YarShev** [pandas-dev/pandas#36065]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
import pandas
i1 = pandas.date_range("2008-01-01", periods=1000, freq="12H")
i2 = pandas.date_range("2008-01-01", periods=1000, freq="12H")
i2.freq = None
i1.equals(i2)
True
# but freqs are now equal
i1.freq == i2.freq
False
```

#### Problem description

Could anyone please explain? Is it normal behavior for `equals`?

#### Output of ``pd.show_versions()``

<details>

pandas           : 1.1.1
numpy            : 1.18.4
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.2
setuptools       : 41.2.0
Cython           : None
pytest           : 5.4.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : 0.4.1
xlsxwriter       : None
lxml.etree       : 4.5.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.14.0
pandas_datareader: None
bs4              : 4.9.1
bottleneck       : None
fsspec           : 0.7.3
fastparquet      : None
gcsfs            : None
matplotlib       : 3.2.1
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : 0.16.0
pytables         : None
pyxlsb           : None
s3fs             : 0.4.2
scipy            : 1.4.1
sqlalchemy       : 1.3.17
tables           : 3.6.1
tabulate         : None
xarray           : 0.15.1
xlrd             : 1.2.0
xlwt             : None
numba            : None

</details>

**Comment by MarcoGorelli** [comment]
> # but freqs are now equal

`i1.equals(i2)` only determines whether they are equal, it doesn't set them to be equal. Closing then, but please let me know if I've misunderstood the report

**Comment by YarShev** [comment]
@MarcoGorelli , yes, `i1.equals(i2)` has not to set them to be equal. However, since i1.freq and i2.freq are not equal, I guess that `i1.equals(i2)` has to return `False` in this case. Or I misunderstand this?

**Comment by MarcoGorelli** [comment]
@YarShev though actually, the docs do say


>The things that are being compared are:
>
>    The elements inside the Index object.
>
>    The order of the elements inside the Index object.
>

and give an example showing that other attributes such as `dtype` are not compared.

So, it seems correct?

**Comment by dsaxton** [comment]
xref https://github.com/pandas-dev/pandas/issues/33940

**Comment by YarShev** [comment]
@MarcoGorelli , yes the docs are saying exactly what you mentioned. However, may be it's worth doing this method more restricted?

**Comment by MarcoGorelli** [comment]
> @MarcoGorelli , yes the docs are saying exactly what you mentioned. However, may be it's worth doing this method more restricted?

Possibly, but it seems this is already being discussed in the issue linked to by Daniel.

If this isn't a bug then, is it OK to close it?

**Comment by YarShev** [comment]
@MarcoGorelli , I think the issue can be closed if it is treated as a bug. Can we keep it as feature request or something like that?

**Comment by MarcoGorelli** [comment]
@YarShev it looks like @attack68 has kindly mentioned this in the above issue, so I'll close this for now - thanks for your report!
