### ISSUE TITLE
BUG: Unary minus raises for series with Int64Dtype

### ISSUE THREAD

**Issue by mila** [pandas-dev/pandas#36063]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas (commit 73c1d32)

---

#### Code Sample, a copy-pastable example

```python
>>> import pandas as pd
>>> pd.__version__
'1.1.1'
>>> s = pd.Series([1, 2, 3], dtype="Int64")
>>> -s
Traceback (most recent call last):
  File "...", line 1, in <module>
    -s
  File ".../lib/python3.8/site-packages/pandas/core/generic.py", line 1297, in __neg__
    arr = operator.neg(values)
TypeError: bad operand type for unary -: 'IntegerArray'
```

#### Problem description

I cannot negate series with Int64Dtype. This was possible in previous versions (but it returned object dtype).

#### Expected Output

```
>>> import pandas as pd
>>> pd.__version__
'1.0.5'
>>> s = pd.Series([1, 2, 3], dtype="Int64")
>>> -s
0    -1
1    -2
2    -3
dtype: object
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f2ca0a2665b2d169c97de87b8e778dbed86aea07
python           : 3.8.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
Version          : Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.1
numpy            : 1.19.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 47.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.15.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by kokes** [comment]
Bisection identified 67aae8028773eae231662e47ec2c46124ad4229e as the first bad commit. (PR https://github.com/pandas-dev/pandas/pull/32422)

bisect log
<details>

```
# bad: [d9fff2792bf16178d4e450fe7384244e50635733] RLS: 1.1.0
git bisect bad d9fff2792bf16178d4e450fe7384244e50635733
# good: [b687cd4d9e520666a956a60849568a98dd00c672] RLS: 1.0.5
git bisect good b687cd4d9e520666a956a60849568a98dd00c672
# good: [d3f08566a80239a18a813ebda9a2ebb0368b1dc5] RLS: 1.0.0rc0
git bisect good d3f08566a80239a18a813ebda9a2ebb0368b1dc5
# bad: [63957e46c789d5f891344cf335eaf8eaccabe5ba] Requested ASV (#33197)
git bisect bad 63957e46c789d5f891344cf335eaf8eaccabe5ba
# good: [c0066f32b4667744d7b86d680e7e3e5d9a08e33d] REG: dont call func on empty input (#32121)
git bisect good c0066f32b4667744d7b86d680e7e3e5d9a08e33d
# bad: [3b66021ecb74da2c35e16958121bd224d5de5264] TST: make tests stricter (#32527)
git bisect bad 3b66021ecb74da2c35e16958121bd224d5de5264
# good: [821aa25c9039e72da9a7b236cf2f9e7d549cbb7b] BUG: Fix __ne__ comparison for Categorical (#32304)
git bisect good 821aa25c9039e72da9a7b236cf2f9e7d549cbb7b
# bad: [09a46a4e465b19fa688f1d58124d266c0bbbebf0] DOC: Add extended summary, update parameter types desc, update return types desc, and add whitespaces after commas in list declarations to DataFrame.first in core/generic.py (#32018)
git bisect bad 09a46a4e465b19fa688f1d58124d266c0bbbebf0
# bad: [777c0f90c6067c636fcd76ce003a8fbfcc311d7b] CLN: remove unreachable _internal_get_values in blocks (#32472)
git bisect bad 777c0f90c6067c636fcd76ce003a8fbfcc311d7b
# bad: [86ed2b654abfe82adeba2bae7c4424377d428d91] PERF: lazify blknos and blklocs (#32261)
git bisect bad 86ed2b654abfe82adeba2bae7c4424377d428d91
# good: [d33b0025db0b2d79abe51343054d4c8bbed104c6] CLN: remove unreachable branch (#32405)
git bisect good d33b0025db0b2d79abe51343054d4c8bbed104c6
# bad: [67aae8028773eae231662e47ec2c46124ad4229e] CLN: avoid values_from_object in NDFrame (#32422)
git bisect bad 67aae8028773eae231662e47ec2c46124ad4229e
# good: [c5f0ebf8d92322445a4413c1bf9bd08e226583f0] TYP/cln: generic._make_*_function (#32363)
git bisect good c5f0ebf8d92322445a4413c1bf9bd08e226583f0
# good: [0d04683baaf65f6023fa83ab0d985726fb3c98b0] TST: Split and simplify test_value_counts_unique_nunique (#32281)
git bisect good 0d04683baaf65f6023fa83ab0d985726fb3c98b0
# first bad commit: [67aae8028773eae231662e47ec2c46124ad4229e] CLN: avoid values_from_object in NDFrame (#32422)
```
</details>

setup to reproduce
<details>

Ran bisection with this shell script, first good/bad commits are 1.0.5 and 1.1.0 releases respectively:
```
set -eu
python3 setup.py build_ext --inplace --force
python3 un.py
```

where un.py is

```python
import pandas

s = pandas.Series([1, 2, 3], dtype="Int64")

print(-s)
```
</details>

**Comment by simonjayhawkins** [comment]
moving off 1.1.2 milestone

**Comment by simonjayhawkins** [comment]
> Bisection identified [67aae80](https://github.com/pandas-dev/pandas/commit/67aae8028773eae231662e47ec2c46124ad4229e) as the first bad commit. (PR #32422)

Thanks @kokes cc @jbrockmendel

**Comment by jbrockmendel** [comment]
Yikes, returning object dtype in the old version is not great.  This is just waiting for someone to implement `IntegerArray.__neg__`

**Comment by mila** [comment]
Thank you @dsaxton and @jreback! You are doing amazing work.
