### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by nicolas-gervais** [pandas-dev/pandas#36079]
SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

**Comment by jreback** [comment]
you need to show an actual example

docs (in the errror message are):  https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#indexing-view-versus-copy

**Comment by MarcoGorelli** [comment]
Closing as there's no way to know what's happening here, but please let us know if you can provide a bug report (see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) and I'll reopen
