### ISSUE TITLE
DOC: Docstring for comparison operators has "=!" instead of "!="

### ISSUE THREAD

**Issue by daytonb** [pandas-dev/pandas#36075]
#### Location of the documentation

Shows up in all the flexible comparison docstrings like "https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.ne.html". The typo is in the `_flex_comp_doc_FRAME` shared docstring found in `core/ops/docstrings.py`.

#### Documentation problem

The docstring says `=!` instead of `!=` for the not-equals comparison.

#### Suggested fix for documentation

Just need to change it to `!=`.

**Comment by daytonb** [comment]
take

**Comment by MarcoGorelli** [comment]
From a comment on the PR https://github.com/pandas-dev/pandas/pull/36077#issuecomment-812754556:

> 
> So this change actually breaks building docs, at least using sphinx. Leads to an error
> 
> ```
> /usr/local/lib/python3.8/site-packages/docutils/nodes.py", line 567, in __getitem__
>     return self.attributes[key]
> KeyError: 'reftarget'
> ```
> 
> whereas simply swapping them back fixes the problem. Any idea what might be going on here?

I haven't yet looked into it, just reopening so it's not forgotten

**Comment by jbrockmendel** [comment]
@MarcoGorelli is there anything left to do here?

**Comment by daytonb** [comment]
@jbrockmendel and @MarcoGorelli, O don't believe there is anything left to do here. I was pretty certain that my tiny docstring correction could not have broken building the docs and my commit has been part of the main line for quite a while now including several pandas releases. This tells me that whatever was actually causing the doc build failures has also been addressed by some other work.

**Comment by MarcoGorelli** [comment]
Agreed, thanks for closing, looks like I just forgot to get back to this, sorry 😞
