### ISSUE TITLE
BUG: ser.to_frame().all() inconsistent with ser.all() with CategoryDtype

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#36076]
Based on tests.frame.test_analytics.test_any_all_np_func

```
ser = pd.Series([0, 1], dtype="category", name="A")
df = ser.to_frame()

>>> ser.all().
TypeError: Categorical cannot perform the operation all

>>> df.all().item()
False
```

Whats happening here is the DataFrame case is calling `self.values` which casts to int64 (avoidable with 2D EAs...).

If instead we refactor (xref #35881) to operate blockwise, this block is ignored, so we end up getting the result we'd get on an empty DataFrame, i.e. True.  (xref #28900 ignoring failures is a footgun).

Expected Behavior: as long as have ignore_failures, `df.all()` should be `True`

**Comment by jorisvandenbossche** [comment]
Same happens for datetime/timedelta -> https://github.com/pandas-dev/pandas/issues/34479 (which came out of the same PR experiments)

**Comment by jbrockmendel** [comment]
Any preferences on how to handle the inconsistency?

**Comment by jbrockmendel** [comment]
From the most recent call, the consensus seems to be that we should deprecate the current behavior in favor of matching the Series behavior

**Comment by jorisvandenbossche** [comment]
Yes, I would be in favor of that as well. The user can always convert to boolean to be explicit.
