### ISSUE TITLE
BUG: Plotting charts in different orders creates different plot outputs

### ISSUE THREAD

**Issue by cinerea0** [pandas-dev/pandas#36083]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample

```python
import numpy as np
import pandas as pd

df = pd.DataFrame(
    {
        "date": [
            "2000-01-01",
            "2000-01-01",
            "2000-01-01",
            "2000-01-02",
            "2000-01-02",
            "2000-01-02",
            "2000-01-03",
            "2000-01-03",
            "2000-01-03",
        ],
        "group": ["A", "B", "C", "A", "B", "C", "A", "B", "C"],
    }
)
df["count"] = np.random.randint(0, 5, df.shape[0])
df["date"] = pd.to_datetime(df["date"])

separate_plot = df.groupby(["date", "group"])["count"].sum().unstack().plot()
separate_plot.get_figure().savefig("separate_plot.png")
total_plot = df.groupby("date")["count"].sum().plot()
total_plot.get_figure().savefig("total_plot.png")
```

#### Problem description

Plotting the "separate" plot before the "total" plot results in the following graphs:

*separate_plot.png*:
![separate_plot](https://user-images.githubusercontent.com/49368915/92064588-4ad70a80-ed8d-11ea-8b7d-93d833a52e69.png)

*total_plot.png*:
![total_plot](https://user-images.githubusercontent.com/49368915/92064626-5f1b0780-ed8d-11ea-8820-b1e1fe34a5b4.png)

As you can see, the lines from the "separate" plot also appear on the "total" plot, despite not grouping by "group" in the "total" plot. In my testing, this only occurs when the "separate" plot is made before the "total" plot.

#### Expected Output

The graphs should look something like the following regardless of which is plotted first:

*separate_plot.png*:
![separate_plot](https://user-images.githubusercontent.com/49368915/92064962-38110580-ed8e-11ea-8f15-54d753d93835.png)

*total_plot.png*:
![total_plot](https://user-images.githubusercontent.com/49368915/92064987-46f7b800-ed8e-11ea-965c-90f46a31cde8.png)

#### Output of ``pd.show_versions()``

<details>

/usr/lib/python3.8/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit           : f2ca0a2665b2d169c97de87b8e778dbed86aea07
python           : 3.8.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.8.5_1
Version          : #1 SMP Thu Aug 27 08:23:40 UTC 2020
machine          : x86_64
processor        :
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.1
numpy            : 1.19.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 50.0.0
Cython           : None
pytest           : 5.4.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.18.1
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.1
numexpr          : None
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
numba            : None

</details>

**Comment by TomAugspurger** [comment]
IIUC, this is the same as https://github.com/pandas-dev/pandas/issues/8776. DataFrame.plot and Series.plot are inconsistent with whether they plot on an existing figure or create a new one.
