### ISSUE TITLE
CLN: clean `pandas/compat.__init__.py`

### ISSUE THREAD

**Issue by VirosaLi** [pandas-dev/pandas#36108]
Remove `is_platform_32bit()` from `pandas/compat.__init__.py`, use `IS64` instead to improve consistency.

**Comment by KarenEfereyan** [comment]
@VirosaLi can i take this up? I am a new contributor. I really want to be  a part of this

**Comment by VirosaLi** [comment]
> @VirosaLi can i take this up? I am a new contributor. I really want to be a part of this

There is an open PR on this issue. See #36109. ^^

**Comment by KarenEfereyan** [comment]
Oh okay
