### ISSUE TITLE
ENH: Standarization changing copy parameter to inplace

### ISSUE THREAD

**Issue by Genarito** [pandas-dev/pandas#36116]
#### Is your feature request related to a problem?

No, it's not a problem

#### Describe the solution you'd like

Some functions like [astype](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.astype.html) (I don't know if there is another one) has the `copy` parameter, which has exactly the same functionality that `inplace` in the vast majority of the other methods.
Sometimes, even PyCharm is unable to infer the type of some objects, so I think that It'd be great to have only one way to make things, renaming `copy` to `inplace` and changing its default value to `False`.
This will make Pandas an even more easy-to-use tool and will simplify the documentation and general structure.

#### API breaking implications

The `copy` parameter will be changed to `inplace`. In the general cases where default values are used it don't represent a problem. In other cases an `AttributeError` will be reaised

**Comment by jreback** [comment]
we are planning on deprecating `inplace` see https://github.com/pandas-dev/pandas/issues/16529

in any event.
