### ISSUE TITLE
BUG: pandas.DataFrame().stack() raise an error, while expected is empty

### ISSUE THREAD

**Issue by evyasonov** [pandas-dev/pandas#36113]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
pandas.DataFrame().stack()
pandas.DataFrame().stack(dropna = True)
```

#### Problem description

I expect that stack() of empty dataframe will be empty dataframe and not an exception

**Comment by TomAugspurger** [comment]
Thanks for the report. What's the expected output? An empty Series?

**Comment by evyasonov** [comment]
@TomAugspurger 
I expect a dataframe, because if input is not empty, then the method returns a dataframe

**Comment by TomAugspurger** [comment]
Doesn't DataFrame.stack return a Series? Or do I misunderstand?

**Comment by ivanovmg** [comment]
From the code on ``stack`` method:

```
from pandas.core.reshape.reshape import stack, stack_multiple

if isinstance(level, (tuple, list)):
    return stack_multiple(self, level, dropna=dropna)
else:
    return stack(self, level, dropna=dropna)
```
By default ``level=-1``.
Meanwhile ``pandas.core.reshape.reshape.stack`` returns a Series.

**Comment by evyasonov** [comment]
@TomAugspurger 
All of my use cases were about multiindex, so .stack() returns a dataframe for my cases.
But I checked the documentation and it returns a Series if it's just one level.
So let's use the logic @ivanovmg  described
