### ISSUE TITLE
ENH/API: errors argument for ExtensionArray.astype

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#36151]
`Series.astype` and `DataFrame.astype` both allow control over whether the original object should be returned on errors in conversion by setting the `errors` argument to either `"ignore"` or `"raise"`. Should `ExtensionArray.astype` also allow this?

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.astype.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.astype.html

xref https://github.com/pandas-dev/pandas/pull/35979

**Comment by jorisvandenbossche** [comment]
Personally I would keep this ability on the Series/DataFrame level, and not complicate the ExtensionArray interface with it.

**Comment by jbrockmendel** [comment]
I agree with @jorisvandenbossche on this one.

**Comment by dsaxton** [comment]
I think not overcomplicating makes sense
