### ISSUE TITLE
BUG: Adding offset produces NonExistentTimeError

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#36165]
In #36160, Travis had the following failure:

````
pandas/tests/tseries/offsets/test_offsets_properties.py:88: 
[snip]
---------------------------------- Hypothesis ----------------------------------
Falsifying example: test_on_offset_implementations(
    dt=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=tzfile('/usr/share/zoneinfo/Iceland')),
    offset=<96 * MonthBegins>,
)
You can reproduce this example by temporarily adding @reproduce_failure('5.29.0', b'AAEAMgAAAAAAAAAAAABgAA==') as a decorator on your test case
````

Can reproduce with:

    from datetime import datetime
    import pytz
    from pandas.tseries.offsets import MonthBegin

    dt = datetime(1900, 1, 1, 0, 0, tzinfo=pytz.timezone('Iceland'))
    offset = MonthBegin(96)
    dt + offset

which produces the trace:

````
  File "pandas/_libs/tslibs/offsets.pyx", line 422, in pandas._libs.tslibs.offsets.BaseOffset.__add__
  File "pandas/_libs/tslibs/offsets.pyx", line 424, in pandas._libs.tslibs.offsets.BaseOffset.__add__
  File "pandas/_libs/tslibs/offsets.pyx", line 172, in pandas._libs.tslibs.offsets.apply_wraps.wrapper
  File "pandas/_libs/tslibs/timestamps.pyx", line 1317, in pandas._libs.tslibs.timestamps.Timestamp.tz_localize
  File "pandas/_libs/tslibs/tzconversion.pyx", line 63, in pandas._libs.tslibs.tzconversion.tz_localize_to_utc_single
  File "pandas/_libs/tslibs/tzconversion.pyx", line 319, in pandas._libs.tslibs.tzconversion.tz_localize_to_utc
pytz.exceptions.NonExistentTimeError: 1908-01-01 00:00:00
````

Not sure if this is a bug or an invalid input.

**Comment by hemraj4545** [comment]
@rhshadrach It's seems to be an bad input. I tried the code `offset = MonthBegin(n=90)` which works. So, except n=96, it works with all other values.

**Comment by mroeschke** [comment]
I think the root issue stems from https://github.com/pandas-dev/pandas/issues/28610.

`datetime object + Offset object` does not have any handling whether the resulting timestamp if ambiguous or nonexsitent

**Comment by rhshadrach** [comment]
Okay - I found it [here](https://rmets.onlinelibrary.wiley.com/doi/full/10.1002/gdj3.23):

> The time zone of Iceland is UT0 (i.e. the same as Greenwich, UK), but Iceland did not adopt the global time zone until January 1908, when GMT‐1 was adopted.

That makes this a duplicate of #28610.

**Comment by germainvelard** [comment]
Hi,
To me this issue is not closed.
I have the issue with the operation datetime object + Offset object which leads to "pytz.exceptions.NonExistentTimeError: 2019-03-31 02:00:00"
This is due to the fact that this hour is not existent in western Europe due to DST

**Comment by rhshadrach** [comment]
@germainvelard This issue is closed not because it has been resolved, but rather because it has been found to be a duplicate of another issue as noted above. It seems to me that issue covers what you mention as well, but please let me know if you disagree here.

**Comment by germainvelard** [comment]
Hi @rhshadrach, thanks for your reply.
It seemed to me that the linked issue was also closed but I was mistaken !
Apologies.
