### ISSUE TITLE
DOC: index described as a "set" but permits duplicates -- change to multiset or list?

### ISSUE THREAD

**Issue by notestaff** [pandas-dev/pandas#36170]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/indexing.html

#### Documentation problem

Index is described as a "set", but behaves as a multiset: len() counts each occurrent of a duplicate element separately.

Also, Index is described as an "ordered set", but that term connotes a set with an order relation on the _values_ of its elements.  

#### Suggested fix for documentation

An index seems more like an immutable ordered _list_; maybe, describe it as that?

**Comment by dsaxton** [comment]
Thanks @notestaff, this does seem like an odd description. "Immutable ndarray implementing an ordered, sliceable set.", but it's neither an ndarray, ordered, or a set. A PR to update the docs would be helpful.

**Comment by onshek** [comment]
I'm willing to take this.

**Comment by Nikhil1O1** [comment]
i would be glad to make my first contribution here

**Comment by Nikhil1O1** [comment]
take

**Comment by Nikhil1O1** [comment]
take

**Comment by Nikhil1O1** [comment]
There's no indexing.html present in my clone... However, I found \pandas\doc\source\reference\indexing.rst but 
this is not what we are looking for
Please help me to  pinpoint its location
@notestaff  @dsaxton

**Comment by dsaxton** [comment]
@Nikhil1O1 It looks like the docs you'd want to update are in two places (this description is used for a few different classes): `/pandas/core/indexes/base.py` and `/pandas/core/indexes/numeric.py`

**Comment by Nikhil1O1** [comment]
Done, If there's anything else I can do... Do let me know.
