### ISSUE TITLE
QST:Column deletion

### ISSUE THREAD

**Issue by chipxx** [pandas-dev/pandas#36219]
Hi, how do I delete the first column that is useless? Thanks

![pandas](https://user-images.githubusercontent.com/43586762/92475574-e927fd80-f1dd-11ea-9b76-bbb8a0763839.png)

**Comment by ivanovmg** [comment]
You can try to use method ``to_string``.

```
print(data.to_string(index=False))
```

But I am not sure that you will like how it is rendered, since it is suitable for the console output.

**Comment by TomAugspurger** [comment]
We recommend StackOverflow for usage questions.
