### ISSUE TITLE
DOC: whatsnew for Pandas release 1.1.2

### ISSUE THREAD

**Issue by engineerchange** [pandas-dev/pandas#36225]
#### Location of the documentation

https://github.com/pandas-dev/pandas/releases/tag/v1.1.2

#### Documentation problem

The "what's new" link doesn't appear to function for update 1.1.2.

**Comment by simonjayhawkins** [comment]
Thanks @engineerchange the docs are currently being built.

**Comment by simonjayhawkins** [comment]
doc build completed
