### ISSUE TITLE
DOC: Deprecation Warnings in user guide

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#36258]
#### Location of the documentation

https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-deprecate-loc-reindex-listlike

#### Documentation problem

We have a lot of warnings in the documentation ``Starting with 0.x the following is deprecated.`` Most of these things stopped working with 1.0. Should we update the docs and say, that this stopped working with 1.0?

**Comment by jreback** [comment]
if they are now completely working then the docs can simply be updated (eg in the case u pointed it's now an exception)
