### ISSUE TITLE
New feature/enhancement: it would be cool if read_csv() function can read n random lines from a csv file.

### ISSUE THREAD

**Issue by wenjunsun** [pandas-dev/pandas#36253]
#### Problem:

I am using Pandas for reading in data to do machine learning tasks. And one problem I encounter is that the data I have is usually very very big. For example one data set I have is about 16 GB big, and my RAM is only 12 GB. So instead of reading all the lines from this data, I know I can read in the first million rows from my data, and do machine learning on that. But what I really want to do is select 100 random lines from the entire file for it to be a valid sample from the 16 GB data. Pandas currently doesn't allow that.

#### Solution I would like

[pd.read_csv() should take in an additional parameter, called random. Random should be a tuple of 3 ints. (start, end, number of random lines). For example: pd.read_csv('my_data.csv', random = (100, 1000, 100)) should read in 100 random lines into python datafraem from 100 lines to 1000 lines within the data.csv file.]

#### API breaking implications

[existing API about nrows should be modified so that when random = (100, 1000, 100) is present, nrows doesn't do anything, since we specify the number of rows we need to read in parameter random already.]

#### alternatives I considered

[what we could do also is to have another parameter specifying the starting line and end line, for example start line = 10, end line = 100 will allow the reader to read from 10 lines and up to 100 lines in the csv file, nrows specifies how many lines starting from 10 we read. If Random = True then we read 10 random lines from 10 to 100 lines instead of reading from 10 - 20 lines.]

#### Additional context

[I haven't looked too deep into pandas to see if my idea is already being developed, but if there is any development, I would appreciate the link to that discussion post. I would very much like to help and code this thing if no one has done this before.]
[FYI: this is my first time to contribute to open source, so please let me know how to help code this feature.]

**Comment by jbrockmendel** [comment]
`pd.read_csv` is overly-complicated as it is, so we are reluctant to add new keywords.  I think you're better off doing this kind of random row selection before passsing your data to pandas.

**Comment by rhshadrach** [comment]
read_csv has the skiprows argument, does that satisfy your purpose? See an example here:

https://stackoverflow.com/questions/22258491/read-a-small-random-sample-from-a-big-csv-file-into-a-python-data-frame

**Comment by wenjunsun** [comment]
Yeah I think it is better to write my own function and method to get random lines, rather than adding it to read_csv function. Thanks for helping.
