### ISSUE TITLE
BUG: DataFrame.sort_values(by, ascending): by CANNOT recognize a tuple, yet ascending can. 

### ISSUE THREAD

**Issue by runsun** [pandas-dev/pandas#36268]
This behavior looks like a bug to me. 

Inconsistent behaviors of the argument for **DataFrame.sort_values**( )

The first argument takes list, but fail to take tuple .

These worked: 

``` python
   df.sort_values( ['A', 'B'], ascending= [1, 0] )  # list, list
   df.sort_values( ['A', 'B'], ascending= (1, 0) )  # list, tuple 
```
These failed: 

``` python
   df.sort_values( ('A', 'B'), ascending= [1, 0] )  # tuple, list
   df.sort_values( ('A', 'B'), ascending= (1, 0) )  # tuple, tuple 
```
Error:
``` phthon
raise ValueError(
ValueError: Length of ascending (2) != length of by (1)
```

**Comment by MarcoGorelli** [comment]
Hi @runsun - what version of pandas are you using? Currently, DataFrame doesn't have a `sort` method

**Comment by runsun** [comment]
From my pip list, it says :

pandas          1.1.2

**Comment by ivanovmg** [comment]
I tried to solve it, but it seems that tuple for ``by`` kwarg is reserved for sorting via multilevel column names, which comprise tuples.

**Comment by runsun** [comment]
Thx for the quick response. I imagined there must be some design reserve for not allowing tuple here. It seems correct.
