### ISSUE TITLE
ENH: allow sort_values to use the natural sort order

### ISSUE THREAD

**Issue by AlexeyGy** [pandas-dev/pandas#36286]
#### Is your feature request related to a problem?

The [natural sort order](https://en.wikipedia.org/wiki/Natural_sort_order#:~:text=Natural%20sort%20order%20is%20an,machine%2Doriented%20pure%20alphabetical%20order) is a common use case when working with real-world data. For example, consider the following DataFrame of clinical data where the body temperature of patients was measured:

```
data = {'Patient_ID': {0: 'ID-1',
  1: 'ID-11',
  2: 'ID-2'},
 'temperature': {0: 37.2, 1: 37.5, 2: 37.2}}
df = pd.DataFrame(data).sort_values(by=['Patient_ID'])
df.head(5)
```
will yield:

|    | Patient_ID   |   temperature |
|---:|:-------------|--------------:|
|  0 | ID-1         |          37.2 |
|  1 | ID-11        |          37.5 |
|  2 | ID-2         |          37.2 |

whereas we would want

|    | Patient_ID   |   temperature |
|---:|:-------------|--------------:|
|  0 | ID-1         |          37.2 |
|  2 | ID-2         |          37.2 |
|  1 | ID-11        |          37.5 |

#### Describe the solution you'd like
- sort_values could get a new parameter `sort_order` that is by default alphabetical and could be switched to natural.
- the implementation could be similar to the [natsort](https://github.com/SethMMorton/natsort) package without any of the extra options `natsort` brings.: modify all values and pass them to np.argsort() s.t. then transform them back.
#### API breaking implications

Since we are only adding a parameter this would not break any existing API.

#### Describe alternatives you've considered
Currently, one could use the `natsort` package. However, this seems cumbersome for such a common operation and makes it necessary to reindex the DataFrame. [Stackoverflow example](https://stackoverflow.com/questions/29580978/naturally-sorting-pandas-dataframe).

**Comment by jreback** [comment]
you can probably use the key= option here (happy to take a PR to show this in the docs)

-1 on adding any api

**Comment by erfannariman** [comment]
Is it oké to give an example in the docs using a third party package like natsort? @jreback

**Comment by satrio-hw** [comment]
hai, I solved the problem using key as @jreback said..
`df = pd.DataFrame(data).sort_values(by=['Patient_ID'], key=lambda col:col.astype(str).str[3:].astype(int))`
as it would take Patient_ID as string[3:] (so it will ignore 'ID-') and convert it back to int for sorting..

**Comment by erfannariman** [comment]
Here's a more general solution which should work in all cases:

```

**Comment by erfannariman** [comment]
Here's a more general solution, which should work in all cases:

```python
from natsort import index_natsorted

df.sort_values(
    by="col_name",
    key=lambda x: np.argsort(index_natsorted(df["col_name"]))
)
```

Which needs an installation first: `pip install natsort`

**Comment by jreback** [comment]
@erfannariman so happy to take a PR to add that as an example; it would be ok i think to add to `environment.yml` with an appropriate comment (used in doc-strings) as this environment builds the docs.

**Comment by erfannariman** [comment]
Sure will do tonight after work. @jreback

**Comment by erfannariman** [comment]
@jreback PR is ready for review, weird stata test failing, will check later.

**Comment by jaredight** [comment]
@erfannariman Could you update the [docs](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html) to reflect your answer [here](https://stackoverflow.com/questions/29580978/naturally-sorting-pandas-dataframe/63890954#63890954)?
```
from natsort import natsort_keygen

df.sort_values(
    by="time",
    key=natsort_keygen()
)
```
