### ISSUE TITLE
ERR: Report key on (unsupported) indexing errors

### ISSUE THREAD

**Issue by prhbrt** [pandas-dev/pandas#36288]
I would suggest to that indexing errors also state what they received, e.g. change [this](https://github.com/pandas-dev/pandas/blob/master/pandas/core/indexing.py#L705) to:

            except ValueError as err:
                raise ValueError(
                    "Location based indexing can only have "
                    f"[{self._valid_types}] types, but got: {key}"
                ) from err

Or possibly a truncation for long types: `f"{(str(key)[:20] + '...') if len(str(key)) > 23 else str(key)}"`

It would particularly help sloppy data scientists like me :)

I'm happy to make a pull request, but I'd like to hear thoughts first.

**Comment by dsaxton** [comment]
Could also display `type(k)` instead since the error message is about types, PR to improve the error message would be helpful

**Comment by mroeschke** [comment]
Thanks for the request but it appears this hasn't gotten traction in a while so closing
