### ISSUE TITLE
BLD/CI: 3.9 support

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#36296]
- [x] CI for the 3.9 build is from source, we should update this to use numpy wheels (just became available IIUC) #36323
- [ ] pass tests & update whatsnew for 3.9 build so we can include in 1.1.3

cc @pandas-dev/pandas-core

**Comment by VirosaLi** [comment]
We need to fix #34014 first.

**Comment by jbrockmendel** [comment]
AFAICT #34014 is fixed by #35928 + #34997

**Comment by wumpus** [comment]
Also https://github.com/pandas-dev/pandas/pull/36298 is needed to build with -Werror on 3.9 -- I haven't run the pandas test suite with it, but it did fix pandas enough that [my pandas-using project was happy in with 3.9 in travisci](https://travis-ci.com/github/wumpus/pandas-appender/jobs/384167589)

**Comment by TomAugspurger** [comment]
@jbrockmendel how comfortable are you with backporting https://github.com/pandas-dev/pandas/pull/34997 and https://github.com/pandas-dev/pandas/pull/35928? IMO those probably decide whether we're likely to add support for Pytyhon 3.9 in 1.1.x or 1.2.0.

**Comment by simonjayhawkins** [comment]
1.1.x still needs to support 3.6. so need to make sure any changes to don't break 3.6 support.

**Comment by jbrockmendel** [comment]
> how comfortable are you with backporting #34997 and #35928? IMO those probably decide whether we're likely to add support for Pytyhon 3.9 in 1.1.x or 1.2.0.

no particular objections

**Comment by jorisvandenbossche** [comment]
I am not sure #34997 is a good one to backport, it involve quite some tricky code / corner cases?

**Comment by jreback** [comment]
what do we actually need to support 3.9 in 1.1.3? the above PRs are nice to have for cython3 but don't appear to actually be needed correct? (exempting https://github.com/pandas-dev/pandas/pull/36298)

**Comment by jreback** [comment]
do we actually *need* cython3 to compile for 3.9? e.g. https://travis-ci.org/github/pandas-dev/pandas/jobs/726742374

**Comment by wumpus** [comment]
See my 3 day old comment for a report of exactly what I needed to build with 3.9

> Also #36298 is needed to build with -Werror on 3.9 -- I haven't run the pandas test suite with it, but it did fix pandas enough that [my pandas-using project was happy in with 3.9 in travisci](https://travis-ci.com/github/wumpus/pandas-appender/jobs/384167589)

Just 2 lines of change plus cython3.

**Comment by jbrockmendel** [comment]
> Just 2 lines of change plus cython3.

The reason why @jreback is asking is because there are two difficulties with bumping to cython3: 1) it isn't actually released yet and 2) bumping to it breaks a bunch of our tests, the fixes for which are not easy.

So the question is if there is any option that doesnt require cy3.

**Comment by jreback** [comment]
numpy is building with 29.21: https://github.com/numpy/numpy/releases/tag/v1.19.2

can try removing the -pre here: https://github.com/pandas-dev/pandas/blob/master/ci/build39.sh#L7

and see what happens

**Comment by VirosaLi** [comment]
> numpy is building with 29.21: https://github.com/numpy/numpy/releases/tag/v1.19.2
> 
> can try removing the -pre here: https://github.com/pandas-dev/pandas/blob/master/ci/build39.sh#L7
> 
> and see what happens

I've just tried this. We only need #36298 + remove --pre to make it work. And all tests passed on my machine.

**Comment by jreback** [comment]
wow let's do it (single PR wouos be great as have to backport)

also can i update .travis.yml to make this a build that is required (remove the allow failures for that one)
