### ISSUE TITLE
BUG: DataFrameGroupBy.transform with axis=1 fails

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#36308]
The following seems to happen on all transform groupby kernels:

```
df = DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
df.groupby([1, 1], axis=1).transform("shift")
```

results in `ValueError: Length mismatch: Expected axis has 2 elements, new values have 3 elements`.

I think the issue is in `pandas.core.groupby.generic._wrap_transformed_output`; this method does not take into account `self.axis` when wrapping the output. All that needs to happen is `result = result.T` and to use the index labels rather than the column labels for `columns` there.

**Comment by Ethanator** [comment]
Could I work on this issue?

**Comment by xxsacxx** [comment]
I tried the same example with :
`df.groupby(['val']*df.shape[1],axis=1).transform('shift')`
which failed with 
_Shape of passed values is (2, 3), indices imply (3, 3)_

while 
`df.groupby(['val']*df.shape[1],axis=1).transform(lambda x:x.shift())`


 gives : 
           A	        B
0	NaN 	1.0
1	NaN	        2.0
2	NaN	        3.0

what output are we expecting here ?

**Comment by rhshadrach** [comment]
@Ethanator Absolutely! Simply make a comment here "take" and github will assign it to you. If you encounter any difficulties, feel free to reach out here.

@xxsacxx Your 2nd result looks correct to me; the values are shifted 1 to the right, and since there are no values to the left of the first column, you get NaN. The presence of NaN then coerces the dtype to being a float.

**Comment by Ethanator** [comment]
take

**Comment by purusharthmalik** [comment]
take

**Comment by aks861999** [comment]
take

**Comment by tannu-singh** [comment]
take

**Comment by adhilcodes** [comment]
take
