### ISSUE TITLE
ENH: Improve Multiindexing API

### ISSUE THREAD

**Issue by leonarduschen** [pandas-dev/pandas#36314]
#### Is your feature request related to a problem?

Consider the following dataframe

```
               Exams     Labs    
                   I  II    I  II
Student Course                   
Ada     Comp      70  71   72  73
        Math      71  73   75  74
        Sci       72  75   75  75
Quinn   Comp      73  74   75  76
        Math      74  76   78  77
        Sci       75  78   78  78
Violet  Comp      76  77   78  79
        Math      77  79   81  80
        Sci       78  81   81  81
```

to get the rows in for `Math`, there are currently 2 ways to do it as described in here https://pandas.pydata.org/pandas-docs/stable/user_guide/cookbook.html#slicing

1. Using`xs` like so `df.xs('Math', level=1, axis=0)`
2. Using `loc` like so `df.loc[(slice(None), 'Math'), slice(None)]`

Method 2 seems to be very verbose. Furthermore, merely using `df.loc[(slice(None), 'Math')]` does not work here and the columns `slice(None)` has to be specified. I believe this is inconsistent with how we slice single-indexed dataframes (e.g.. `df.loc[<INDEX>]` works just fine for single-indexed `df` without having to specify the columns like `df.loc[<INDEX>, slice(None)]`

#### Describe the solution you'd like

Improve method 2 (using .loc) describe by perhaps making it similar to NumPy`s `ndarray` here https://numpy.org/doc/stable/reference/arrays.ndarray.html

So then I guess the improvement would be to make the following:
`df.loc[( ,'Math')]` equivalent to `df.loc[(slice(None), 'Math'), slice(None)]`

#### API breaking implications

None if we still allow the old API to work

**Comment by jreback** [comment]
see https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html

you can simply use pd.IndexSlice to achieve an idiomatic syntax
