### ISSUE TITLE
CLN: Series.__getitem__ structure

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#36329]
Items for in `Series.__getitem__`

- [ ] Look into moving try-except to `_get_value`
- [ ] Handle remaining hashable cases in try-except.

**Comment by jbrockmendel** [comment]
@rhshadrach can you give this a more helpful title

**Comment by jbrockmendel** [comment]
Looking at `Series.__getitem__`, it isnt clear to me that this is actionable.

**Comment by rhshadrach** [comment]
Agreed, closing.
