### ISSUE TITLE
BUG: when i merge two dataframes in pandas if the datatypes of columns are mismatched  exception is raised

### ISSUE THREAD

**Issue by selvaramkumar** [pandas-dev/pandas#36324]
- [ ] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
import pandas as pd
data_right = [['Alex','10',100],['Bob','12',90],['Clarke','13.0',80]]
data_left =[[10.0],[12.0],[13.0]]
df_right = pd.DataFrame(data_right,columns=['Name','Age','score'])
df_left  = pd.DataFrame(data_left,columns=['Age'])
df_result=df_left.merge(df_right,on='Age',how='inner')

print(df_result)
```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

sometimes when I read from files in some storage .I am not sure of the datatype of a column . Hence I get an Exception while merging
#### Expected Output
What I Propose is we could have a parameter having ignore_data_type=true in the merge . When its true We could mandatorily cast the column of right_dataframe to the data type of left one and Proceed. Hence we could avoid this Exception.

#### Output of ``pd.show_versions()``

<details>
    Age    Name  score
0  13.0  Clarke     80
[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by arw2019** [comment]
Please provide a copy-pastable example so we can reproduce the bug and investigate. See https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by selvaramkumar** [comment]
> Please provide a copy-pastable example so we can reproduce the bug and investigate it. See https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports
I have added the sample code and Explained the Issue @arw2019

**Comment by arw2019** [comment]
Does this snippet do what you intended?
``` python
In [6]: import pandas as pd 
   ...: data_right = [['Alex','10'],['Bob','12'],['Clarke','13.0']] 
   ...: data_left =[['Alex',10.0],['Bob',12.0],['Clarke',13.0]] 
   ...: df_right = pd.DataFrame(data_right,columns=['Name','Age']) 
   ...: df_left  = pd.DataFrame(data_left,columns=['Name','Age']) 
   ...: df_result=pd.concat([df_left, df_right], join='inner') 
   ...:                                          
In [7]: df_result                                                                                                        
Out[7]: 
     Name   Age
0    Alex    10
1     Bob    12
2  Clarke    13
0    Alex    10
1     Bob    12
2  Clarke  13.0                                                                        
```
If yes I think you should just use `concat` instead of `merge`. 

In case it's helpful we have detailed documentation on merge methods [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html).

**Comment by selvaramkumar** [comment]
> Does this snippet do what you intended?
> 
> ```python
> In [6]: import pandas as pd 
>    ...: data_right = [['Alex','10'],['Bob','12'],['Clarke','13.0']] 
>    ...: data_left =[['Alex',10.0],['Bob',12.0],['Clarke',13.0]] 
>    ...: df_right = pd.DataFrame(data_right,columns=['Name','Age']) 
>    ...: df_left  = pd.DataFrame(data_left,columns=['Name','Age']) 
>    ...: df_result=pd.concat([df_left, df_right], join='inner') 
>    ...:                                          
> In [7]: df_result                                                                                                        
> Out[7]: 
>      Name   Age
> 0    Alex    10
> 1     Bob    12
> 2  Clarke    13
> 0    Alex    10
> 1     Bob    12
> 2  Clarke  13.0                                                                        
> ```
> 
> If yes I think you should just use `concat` instead of `merge`.
> 
> In case it's helpful we have detailed documentation on merge methods [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html).

@arw2019  I have updated the sample input and i have placed my expected output as well

**Comment by attack68** [comment]
> 
> #### Expected Output
> What I Propose is we could have a parameter having ignore_data_type=true in the merge . When its true We could mandatorily cast the column of right_dataframe to the data type of left one and Proceed. Hence we could avoid this Exception.

I lean towards this not really being helpful. It seems to be more explicit and a very simple fix augment the code when the error appears. I suspect that there are only very few cases where join keys are more than say 3 columns and then dtypes can be directly specified with minimal effort. The `astype()` is doing exactly what you intend prior to executing the merge:

```
import pandas as pd

data_left = [[10.0, 'Child'], [18.0, 'Teenager'], [30.0, 'Adult']]
data_right = [['Alex', '10'], ['Bob', '18'], ['Clarke', '30.0']]

df_left = pd.DataFrame(data_left, columns=['Age', 'Type'])
df_right = pd.DataFrame(data_right, columns=['Name', 'Age'])

df_result = df_left.merge(df_right.astype({'Age': float}), on='Age', how='left')
print(df_result)
```

**Comment by selvaramkumar** [comment]
@attack68 No What if my merge columns is list of 5 columns .Then i had to manually put astype 5 times

**Comment by attack68** [comment]
OK, my opinion is that in this case I would prefer explicit code:

    df_l.merge(df.r.astype({'col1': int, 'col2': float, 'col3': str}, on=[col1, col2, col3], how='left')

I find the warning that the datatypes are different useful information for controlling pipelines. I do not consider specifying 5 datatypes particularly time consuming, and even though I have no statistics I believe that a merge on 5 or more columns would be quite rare. Personally I do not think I have ever done more than 3.

But, irrespective of my opinion, I'm sure the pandas members would appreciate a PR to review and discuss.

Whilst your argument approach would work in your case ` str --> float ` there might be a host of cases where introducing the keyword creates ambiguous or undefined behaviour which yields its own problems, for example across the many dtypes pandas supports like datetime, datetimes with timezone, timedelta, categorical, etc..

Even something like this might lead to unexpected behaviour on the merge:

    >>> str(3.00) == '3'
    False
    >>> str(3) == '3'
    True

It would be better to cast the `str` column to `float` in the left dataframe rather than the `float` column to `str`on the right dataframe.

**Comment by selvaramkumar** [comment]
> OK, my opinion is that in this case I would prefer explicit code:
> 
> ```
> df_l.merge(df.r.astype({'col1': int, 'col2': float, 'col3': str}, on=[col1, col2, col3], how='left')
> ```
> 
> I find the warning that the datatypes are different useful information for controlling pipelines. I do not consider specifying 5 datatypes particularly time consuming, and even though I have no statistics I believe that a merge on 5 or more columns would be quite rare. Personally I do not think I have ever done more than 3.
> 
> But, irrespective of my opinion, I'm sure the pandas members would appreciate a PR to review and discuss.
> 
> Whilst your argument approach would work in your case `str --> float` there might be a host of cases where introducing the keyword creates ambiguous or undefined behaviour which yields its own problems, for example across the many dtypes pandas supports like datetime, datetimes with timezone, timedelta, categorical, etc..
> 
> Even something like this might lead to unexpected behaviour on the merge:
> 
> ```
> >>> str(3.00) == '3'
> False
> >>> str(3) == '3'
> True
> ```
> 
> It would be better to cast the `str` column to `float` in the left dataframe rather than the `float` column to `str`on the right dataframe.

@attack68  yeah i agree with Your apprach of converting float to str

**Comment by jreback** [comment]
this is as expected
-1 on adding keywords or doing implicit casting

having exceptions tells you that something might be wrong and is a good thing

**Comment by selvaramkumar** [comment]
Yeah i agree @jreback .But if we could add a parameter and handle the exception inside merge function it would be helpful .So that we need worry on casting outside of merge

**Comment by jreback** [comment]
@selvaramkumar not going to happen - this is just making an already very complex function worse
