### ISSUE TITLE
Representation of pd.Timestamp is not ISO8601 compliant.

### ISSUE THREAD

**Issue by kotval** [pandas-dev/pandas#36351]
ISO 8601 specifies that the date and time portion of a timestamp is separated by a "T", but python's datetime.isoformat allows any character to separate them. To comply with ISO8601, [line 650](https://github.com/pandas-dev/pandas/blob/6b2d0260c818e62052eaf535767f3a8c4b446c69/pandas/_libs/tslibs/timestamps.pyx#L650) should be changed to include a "T" in between the date and the time. Since this also complies with datetime.isoformat, there is no reason not to change this.

**Comment by jreback** [comment]
you can use strftime if you actually want to do this but why would we change this and break the world?

**Comment by TomAugspurger** [comment]
Agreed that we can't just change this.

**Comment by jreback** [comment]
and we use the isoformat from datetime already (which has a default sep argument of T)

**Comment by jreback** [comment]
@kotval the code you are referencing is simply a repr and not thr isoformat function - so this is no where implied even that this is ISO
