### ISSUE TITLE
CI: exclude directories from ci/code_checks.sh

### ISSUE THREAD

**Issue by plammens** [pandas-dev/pandas#36368]
I'm using a virtual environment to contribute to pandas that sits in a `venv` directory in the repository root. When I run `./ci/code_checks.sh`, all of the linters and checks start to check every single `.py` file in the virtual environment's site packages, which is a pain. Same happens with the documenation checks and the generated `.rst` files in `doc/source/reference/api`.

It would be nice to ensure that the script only runs on files that are being tracked by git, or at least have an option to exclude a directory when doing the checks.

**Comment by mroeschke** [comment]
Sounds like from https://github.com/pandas-dev/pandas/pull/36386 there isn't much appetite to add this so closing
