### ISSUE TITLE
DOC: New storage_options for read_csv needs a docstring

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#36361]
#### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.read_csv.html
#### Documentation problem

The new `storage_options` keyword for `read_csv` and `read_table` is not documented in the docstring.  

#### Suggested fix for documentation

Add docstring

@martindurant 

NOTE:  I noticed this when running `validate_docstrings` locally for `read_csv` and it reported this.

**Comment by kshivi99** [comment]
What this keyword is used for @Dr-Irv 
I could fix the docstring, which would help me understand the contribution process for pandas.

**Comment by Dr-Irv** [comment]
@kshivi99 If you look at files `common.py`, `feather_format.py`, `parquet.py`, `pickle.py`, `stata.py`, in the directory `pandas/io`, you can just copy the docstring from there.

Just be really careful to do `validate_docstrings` on the changed file to make sure it will render OK.
