### ISSUE TITLE
BUG: duplicated() returns rows that are not duplicated

### ISSUE THREAD

**Issue by bnojavan** [pandas-dev/pandas#36405]
I have a matrix of 1000*285 where 285 is my feature size which contain numerical and categorical features. The range of values are in (-15,32). When I use "dups = df.duplicated()" It is returning rows that are NOT duplicate.

**Comment by dsaxton** [comment]
@bnojavan Can you add a reproducible example that can be copy / pasted?

**Comment by MarcoGorelli** [comment]
Closing to clear up the queue, please let us know if you can provide a reproducible example and we'll reopen

https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports
