### ISSUE TITLE
CLN: err.orig in DataFrame.to_sql seems redundant

### ISSUE THREAD

**Issue by erfannariman** [pandas-dev/pandas#36408]
When going through the `DataFrame.sql` code in version `1.1.2` I found a part of the code confusing and seems redundant:

```python
except exc.SQLAlchemyError as err:
	# GH34431
	msg = "(1054, \"Unknown column 'inf' in 'field list'\")"
	err_text = str(err.orig)
	if re.search(msg, err_text):
		raise ValueError("inf cannot be used with MySQL") from err
	else:
		raise err
```

This is in pandas.io.sql line 1400-1407.

`err.orig` part seems wrong, and does not exist as a method in the sqlalchemy class `SQLAlchemyError`.

Should I remove it or am I missing something?

**Comment by mroeschke** [comment]
This is being explicitly tested here: https://github.com/pandas-dev/pandas/pull/34493/files#diff-be40559e2fd6d796a469b8a717312d9cR1826

So I presume that this is working as intended

**Comment by erfannariman** [comment]
Not sure if I see what you mean, what would `err.orig` do here?

**Comment by mroeschke** [comment]
I am entirely familiar with with SQLAlchemy errors API, but my larger point is that `err.orig` is correctly extracting the error message we want and is being tested in the code path I tested above.

**Comment by erfannariman** [comment]
I see, you are probably right, although I still can't find anything in the `SQLAlchemryError` class. Will close this issue.
