### ISSUE TITLE
DOC: add searchsorted examples

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#36411]
in this PR: https://github.com/pandas-dev/pandas/pull/36346

we updated `.searchsorted()` on the datetimelike indexes to accept string and a list-like, we should add some examples to the doc-string.

cc @jbrockmendel

**Comment by lacrosse91** [comment]
Hi, can I handle this work?
I would like to help!

**Comment by wprazuch** [comment]
I would like to take this issue - is anyone working on that?

**Comment by hardikpnsp** [comment]
> I would like to take this issue - is anyone working on that?

Hey, seems like no one has been assigned the issue yet, you can just comment "take" and the bot will assign it to you.

**Comment by 2796gaurav** [comment]
take

**Comment by Ayushihelloworld** [comment]
take

**Comment by MananKGarg** [comment]
take

**Comment by Ajaydeep123** [comment]
take

**Comment by Ayushihelloworld** [comment]
Hi I am working on this

**Comment by Ajaydeep123** [comment]
Okay no issue, go ahead.

**Comment by Mikhaylov-yv** [comment]
take

**Comment by Mikhaylov-yv** [comment]
Please see if I understood the problem correctly.
