### ISSUE TITLE
BUG: Inconsistent lint environments

### ISSUE THREAD

**Issue by clbarnes** [pandas-dev/pandas#36426]
As of https://github.com/pandas-dev/pandas/blob/3a15e47374762cbc89a6742c4239a069414dbbfc/.pre-commit-config.yaml#L8 , pre-commit uses flake8 3.8, where the other checks use 3.7.

As of https://github.com/pandas-dev/pandas/blob/11d5fc9e89ad8e238ece42890482bae875d9de98/environment.yml#L23 , conda environments use isort 5.2, where pre-commit uses 4.3.

This makes it impossible to create a commit which passes pre-commit and CI.

**Comment by TomAugspurger** [comment]
I would recommend running the linting commands on CI through pre-commit. That way the versions in `.pre-commit-config.yaml` are used everywhere.

We could do this by updating our existing code-checks.sh, or by moving these checks to a GitHub action that uses the pre-commit action, like in https://github.com/dask/dask/pull/6645.

**Comment by clbarnes** [comment]
A couple of possible issues with that approach is that CI will never catch differences between the `environment.yml`/ `requirements-dev` version of linters and the pre-commit linters, but the former is what will be used by users' IDEs and development environments. Furthermore, pre-commit runs the "active" version of fixers like isort and black (i.e. it makes file changes), where CI should just be running the "passive" checks.

AFAIK there's no way to get pre-commit to respect tool versions specified in other files/ existing in the outer environment (and there shouldn't be given pre-commit's design goals). The MVP fix for this is just to change the version strings in the pre-commit config as it's only 3 lines.

**Comment by clbarnes** [comment]
Looks like the mismatch in CI and pre-commit versions is intentional for flake8: https://github.com/pandas-dev/pandas/pull/36412#issuecomment-694072443 . But it's breaking things for isort so I'll fix that.

**Comment by jorisvandenbossche** [comment]
Indeed, the bump for flake8 (and thus inconsistent with environment.yaml) was deliberate, because pre-commit was a bit unusable lately because of that.

**Comment by MarcoGorelli** [comment]
this is fixed now, as pre-commit is used to run CI now
