### ISSUE TITLE
QST: Replace subset of DataFrame by another subset of DataFrame

### ISSUE THREAD

**Issue by zxdawn** [pandas-dev/pandas#36424]
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
# Your code here, if applicable
import numpy as np
import pandas as pd
dic = {'A': [1, 4, 1, 4], 'B': [9, 2, 5, 3], 'C': [0, 0, 5, 3]}
df = pd.DataFrame(dic)
df.index = [0, 0, 1, 1]

df1 = df.copy()
df1[:] = np.nan

df1.loc[0]['A'] = df.loc[0]['A']
```

original `df`:
```
   A  B  C
0  1  9  0
0  4  2  0
1  1  5  5
1  4  3  3
```

I want to replace the subset of the copy with the subset of original `df`:
```
    A   B   C
0 1   NaN NaN
0 4   NaN NaN
1 NaN NaN NaN
1 NaN NaN NaN
```

However, it shows no change at all:
```
    A   B   C
0 NaN NaN NaN
0 NaN NaN NaN
1 NaN NaN NaN
1 NaN NaN NaN
```

**Comment by MarcoGorelli** [comment]
Hi @zxdawn - please ask usage questions on StackOverflow first

Did you not get a `SettingWithCopyWarning` when executing `df1.loc[0]['A'] = df.loc[0]['A']`? 

Use
```
df1.loc[0, 'A'] = 
```
for assignment

**Comment by MarcoGorelli** [comment]
> Thanks, @MarcoGorelli. It works now.
> 
> BTW, I didn't get the warning with `pandas = 1.0.5`.

Thanks for the report - I can confirm that 1.0.5 doesn't give this warning with this snippet, while 1.1.2 does. Reopening for now with `needs tests`, will check later when this was fixed

**Comment by MarcoGorelli** [comment]
```
760ba37a776947694ec816eaf29ce8937e08f544 is the first bad commit
commit 760ba37a776947694ec816eaf29ce8937e08f544
Author: jbrockmendel <jbrockmendel@gmail.com>
Date:   Tue May 26 15:47:18 2020 -0700

    CLN: _consolidate_inplace less (#34389)

 pandas/core/generic.py            |  9 ---------
 pandas/core/internals/managers.py | 10 ----------
 2 files changed, 19 deletions(-)
bisect run success
```

**Comment by samilAyoub** [comment]
take

**Comment by erfannariman** [comment]
Insn't this question abouy why it doesn't do the replacing?

**Comment by MarcoGorelli** [comment]
> Insn't this question about why it does not do the replacing?

Yes, but I believe I answered that in https://github.com/pandas-dev/pandas/issues/36424#issuecomment-694208658 , as you should not use chained slicing for assignment.

However, the OP didn't get a warning, even though they should've, so a test to make sure that such a warning will continue to be thrown would be useful
