### ISSUE TITLE
ENH: Multiple dataframe groupby/apply

### ISSUE THREAD

**Issue by mickvanhulst** [pandas-dev/pandas#36423]
#### Is your feature request related to a problem?

When working with larger separate data frames, it may be computationally more efficient to not join them. However, in scenarios I have personally encountered, I might still want to perform a group by/apply to both data frames while accessing both subframes based  

#### Describe the solution you'd like

An example solution would be:

```python
def func(df_sub1, df_sub2):
    # perform computations.
    return df_sub1, df_sub2

df1, df2 = pd.grouped_apply([df1, df2], on='key', func)

```

Or if results from a single data frame are only of importance:

```python
def func(df_sub1, df_sub2):
    # perform computations.
    return df_sub1

df1 = df.groupby(by='key', dfs=[df2]).apply(func)
```

#### API breaking implications
Some constraints might have to be in place such as treating this as a left join, where df2 may potentially not have any values for a given key. 

#### Describe alternatives you've considered

Standard merge/join/etc, which consumes a large number of resources. Can also do the following:

```python
dict1 = dict(tuple(df1.groupby('Date_A')))
dict2 = dict(tuple(df2.groupby('Date_A')))

for k, df_sub1 in dict1.items():
    df_sub2 = dict2[k]
    dict1[k], dict2[k] = func(df_sub1, df_sub2)

```

#### Additional context
Please forgive me if this makes no sense whatsoever :)!

**Comment by jreback** [comment]
while there is some utility here, this would add to the already very large complexity in groupby.

the way to do this efficiently w/o joining is to
- create common indexes (.reindex)
- groupby (which itself) is pretty cheap, its the agg which can take time.
