### ISSUE TITLE
BUG: If a dataframe element is a list, using `.extend()` method affects the whole column

### ISSUE THREAD

**Issue by eric-downes** [pandas-dev/pandas#36425]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample

in pandas 1.1.1:

```python
import pandas as pd
df = pd.DataFrame({'a': [[]]*10}, index = range(10))
df.loc[0,'a'].extend([1])
assert (df.a.str.len()).sum() == 1 # fails
```

#### Problem description

The entire `a` column should not be filled when using `.loc` to reference a single element.  Instead, we get this
```python
>>> df
     a
0  [1]
1  [1]
2  [1]
3  [1]
4  [1]
5  [1]
6  [1]
7  [1]
8  [1]
9  [1]
```

I am not aware of another way of doing this, now that `.ix` has been removed.  It is inelegant to store iterables inside of df elements, but often necessary (e.g. temporary records of inconsistent length) or when `result_type='expand'` is not appropriate.

#### Expected Output

The script at the top should not trigger the assert; `df` should be:

```python
>>> df 
     a
0  [1]
1  []
2  []
3  []
4  []
5  []
6  []
7  []
8  []
9  []
```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : f2ca0a2665b2d169c97de87b8e778dbed86aea07
python           : 3.8.5.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
Version          : Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.1
numpy            : 1.19.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.2.3
setuptools       : 47.1.0
Cython           : 0.29.20
pytest           : 6.0.1
hypothesis       : 5.33.1
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.18.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.0
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.17.1
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : None
tables           : None
tabulate         : 0.8.7
xarray           : 0.15.1
xlrd             : None
xlwt             : 1.3.0
numba            : 0.51.2
</details>

**Comment by TomAugspurger** [comment]
This is a Python thing. The statement` a = [[]]*10` creates 10 references to the same list.

```python
In [5]: a = [[]] * 10

In [6]: a[0] is a[1]
Out[6]: True

In [7]: a[0].append(1)

In [8]: a
Out[8]: [[1], [1], [1], [1], [1], [1], [1], [1], [1], [1]]
```

You should create 10 different lists, with something like `[[] for _ in range(10)]`.
