### ISSUE TITLE
CLN: infer_dtype has no skipna argument

### ISSUE THREAD

**Issue by erfannariman** [pandas-dev/pandas#36422]
infer_dtype function in `lib.py` has no `skipna` argument, although it is documented in the docstring:

```python
def infer_dtype(foo=None, bar=None): # real signature unknown; restored from __doc__
    """
    Efficiently infer the type of a passed val, or list-like
        array of values. Return a string describing the type.
    
        Parameters
        ----------
        value : scalar, list, ndarray, or pandas type
        skipna : bool, default True
            Ignore NaN values when inferring the type.
    
        Returns
        -------
        str
            Describing the common type of the input data.
        Results can include:
```

The method is called a couple times with the `skipna=True` argument. For example in:

- `pandas/core/algorithms.py` line 220
- `pandas/core/dtypes/cast.py` line 131

Is this expected behaviour? Should I rename `foo -> value` and `bar -> skipna`?

**Comment by jorisvandenbossche** [comment]
I am not fully sure where you got the signature from that you show, but the actual implementation has this keyword:

https://github.com/pandas-dev/pandas/blob/b4d0ae5016133271c1dae3082e3f3dd97684ecb0/pandas/_libs/lib.pyx#L1209-L1212
