### ISSUE TITLE
test_c_parser_only on linux py_3.8_32 failing on MacPython.pandas-wheels

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#36429]
https://dev.azure.com/pandas-dev/pandas-wheels/_build/results?buildId=42365&view=logs&j=bb1c2637-64c6-57bd-9ea6-93823b2df951&t=9c62e7ff-391e-517d-ede1-af63bc6a25da

```
=========================== short test summary info ============================
FAILED ../../venv/lib/python3.8/site-packages/pandas/tests/io/parser/test_c_parser_only.py::test_float_precision_options[c_high]
FAILED ../../venv/lib/python3.8/site-packages/pandas/tests/io/parser/test_c_parser_only.py::test_float_precision_options[c_low]
= 2 failed, 66511 passed, 7439 skipped, 1144 xfailed, 6 xpassed, 15 warnings in 434.87s (0:07:14) =
```

**Comment by jreback** [comment]
these are still failing?

**Comment by simonjayhawkins** [comment]
yes.

on latest nightly build (https://dev.azure.com/pandas-dev/pandas-wheels/_build/results?buildId=48368&view=logs&j=79f3a53a-4a6d-509c-98b5-ff6e9111f67c) failed on windows py_3.8_32 and windows py_3.9_32

some wheels are failing to build. so there maybe other envs this fails on.

I am no longer able to select the build history from the breadcrumb bar. permission error. need to log in to Azure DevOps. am using sign-in with GitHub. are you seeing this too?

**Comment by jreback** [comment]
these look like we are mishandling 32 bit pointers 

these are failing nightly but not on commit pushes?

**Comment by simonjayhawkins** [comment]
these are not failing on commit pushes.

IIUC on commit pushes we use a docker container for the 32bit environment where on MacPython the environment is selected using PYTHON_ARCH environment variable.

I think MacPython may need some updates on versions, maybe NP_BUILD_DEP and CYTHON_BUILD_DEP. have opened https://github.com/MacPython/pandas-wheels/pull/111 to troubleshoot the failures. this failure may or may not be related.

**Comment by simonjayhawkins** [comment]
forgot to mention. 1.1.x wheel builds are OK. so this is probably not an environment issue. https://github.com/MacPython/pandas-wheels/pull/109

**Comment by simonjayhawkins** [comment]
> forgot to mention. 1.1.x wheel builds are OK. so this is probably not an environment issue. [MacPython/pandas-wheels#109](https://github.com/MacPython/pandas-wheels/pull/109)

forget that.

test_float_precision_options was added in #36228 which is not in 1.1.x

**Comment by simonjayhawkins** [comment]
the test failures prevent the nightly wheels to be published. https://anaconda.org/scipy-wheels-nightly/pandas/files

will open PR on MacPython to skip these tests till this issue is resolved (and can remove blocker label)

will break off commit https://github.com/MacPython/pandas-wheels/pull/111/commits/3d2e30aaf32baf73f16125604b41721cdf8c772b from https://github.com/MacPython/pandas-wheels/pull/111

**Comment by simonjayhawkins** [comment]
> I think MacPython may need some updates on versions, maybe NP_BUILD_DEP and CYTHON_BUILD_DEP. have opened [MacPython/pandas-wheels#111](https://github.com/MacPython/pandas-wheels/pull/111) to troubleshoot the failures. this failure may or may not be related.

NP_BUILD_DEP does not appear to be related. still failing in https://github.com/MacPython/pandas-wheels/pull/111/commits/42e9fa4a8aa0e269c26acbca082098316448ac2f

**Comment by simonjayhawkins** [comment]
> these are failing nightly but not on commit pushes?

there were some changes needed in #35898 to get test_float_precision_options to pass.

**Comment by simonjayhawkins** [comment]
removed the blocker tag.

**Comment by simonjayhawkins** [comment]
and removing from 1.2 milestone

**Comment by mroeschke** [comment]
I don't see this skipped in the feedstock or our wheelbuild anymore so closing
