### ISSUE TITLE
DOC: read_excel supports skiprows argument like read_csv, but tests and docs needed

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#36435]
#### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html
https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

#### Documentation problem

In `read_csv`, we say that we support:
**skiprows           list-like, int or callable, optional**

_Line numbers to skip (0-indexed) or number of lines to skip (int) at the start of the file._

_If callable, the callable function will be evaluated against the row indices, returning True
if the row should be skipped and False otherwise. An example of a valid callable argument 
would be lambda x: x in [0, 2]._

In `read_excel`, we say that we support:

**skiprows     list-like**

_Rows to skip at the beginning (0-indexed)._

It turns out that the `int` and `callable` arguments work fine with `read_excel()`, so we should indicate that in the documentation. 
 We also need to add tests for those 2 cases.

#### Suggested fix for documentation and additional tests

- copy the `read_csv` doc for `skiprows` over to `read_excel`
- add tests to `tests/io/excel/test_readers.py` for the `int` and `callable` options

**Comment by ahgamut** [comment]
I'd like to try this out. How do I assign the issue to myself?

**Comment by ahgamut** [comment]
take

**Comment by ahgamut** [comment]
@Dr-Irv  I've submitted a PR (#36437) for this, and it has passed all CI checks except one: the [`travis-ci`](https://travis-ci.org/github/pandas-dev/pandas/jobs/728187422#L706) check is failing due to a stalled build (?).

```
conda env create -q --file=ci/deps/travis-37-cov.yaml

Collecting package metadata (repodata.json): ...working... done

Solving environment: ...working... 

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated
```
