### ISSUE TITLE
DOC: broken link in warning message

### ISSUE THREAD

**Issue by prhbrt** [pandas-dev/pandas#36448]
I couldn't figure out the spot in the code, sorry about that, but the link in this message is broken:

    A value is trying to be set on a copy of a slice from a DataFrame.
    Try using .loc[row_indexer,col_indexer] = value instead
    
    See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

It should be: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

**Comment by dsaxton** [comment]
I think you're right, would you be interested in opening a PR to fix?

**Comment by wprazuch** [comment]
take

**Comment by MarcoGorelli** [comment]
Hi @prhbrt - what version of pandas are you running?

From master the link looks fine:
```python
In [7]: df[df['a']>1].loc[1] = 'b'                                                                                                                                                                        
/home/marco/pandas-dev/pandas/core/indexing.py:1776: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
```

**Comment by khintze1** [comment]
If this is still an issue I'd like to take it.

**Comment by dsaxton** [comment]
@khintze1 Thanks for the interest, but actually this issue seems to be fixed already. Welcome to look for other issues labeled as good first issue.
