### ISSUE TITLE
CLN upgrade to Python3.7+ syntax

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#36450]
Given that the next release will we Python3.7+, we might as well upgrade some of the syntax, e.g.

```diff
-    for make_index_func in make_index_funcs:
-        yield make_index_func
+    yield from make_index_funcs
```
or
```diff
-            return "%s[%s, %s]" % (cls, tp_repr, metadata_reprs)
+            return f"{cls}[{tp_repr}, {metadata_reprs}]"
```

We can do this using [pyupgrade](https://github.com/asottile/pyupgrade).

Here are the files that can be upgraded:

- [ ] pandas/_config/display.py
- [ ] pandas/_testing.py
- [ ] pandas/_vendored/typing_extensions.py
- [ ] pandas/_version.py
- [x] pandas/core/arrays/datetimes.py
- [x] pandas/core/arrays/sparse/array.py
- [x] pandas/core/common.py
- [x] pandas/core/computation/expr.py
- [x] pandas/core/computation/pytables.py
- [x] pandas/core/generic.py
- [x] pandas/core/groupby/base.py
- [x] pandas/core/groupby/generic.py
- [x] pandas/core/indexes/base.py
- [x] pandas/core/indexes/datetimelike.py
- [x] pandas/core/reshape/merge.py
- [ ] pandas/io/clipboard/__init__.py
- [ ] pandas/io/formats/excel.py
- [ ] pandas/io/html.py
- [ ] pandas/io/json/_json.py
- [ ] pandas/io/pytables.py
- [ ] pandas/io/stata.py
- [ ] pandas/plotting/_matplotlib/core.py
- [ ] pandas/tests/arrays/categorical/test_constructors.py
- [ ] pandas/tests/arrays/integer/test_construction.py
- [ ] pandas/tests/extension/decimal/array.py
- [ ] pandas/tests/extension/test_categorical.py
- [ ] pandas/tests/frame/test_constructors.py
- [ ] pandas/tests/groupby/test_groupby.py
- [ ] pandas/tests/groupby/test_grouping.py
- [ ] pandas/tests/indexes/test_base.py
- [ ] pandas/tests/indexing/test_indexing.py
- [ ] pandas/tests/io/formats/test_format.py
- [ ] pandas/tests/io/formats/test_to_csv.py
- [ ] pandas/tests/io/formats/test_to_html.py
- [ ] pandas/tests/io/formats/test_to_latex.py
- [ ] pandas/tests/io/json/test_ujson.py
- [ ] pandas/tests/io/parser/test_c_parser_only.py
- [ ] pandas/tests/io/parser/test_common.py
- [ ] pandas/tests/io/parser/test_encoding.py
- [ ] pandas/tests/io/parser/test_read_fwf.py
- [ ] pandas/tests/io/pytables/common.py
- [ ] pandas/tests/io/test_common.py
- [ ] pandas/tests/io/test_html.py
- [ ] pandas/tests/io/test_sql.py
- [ ] pandas/tests/reshape/test_get_dummies.py
- [ ] pandas/tests/scalar/test_na_scalar.py
- [ ] pandas/tests/series/test_analytics.py
- [ ] pandas/tests/series/test_constructors.py
- [ ] pandas/tests/series/test_dtypes.py
- [ ] pandas/tests/series/test_io.py
- [ ] scripts/validate_rst_title_capitalization.py
- [ ] scripts/validate_unwanted_patterns.py
- [ ] setup.py
- [ ] versioneer.py

If you're intereseted in helping out, please choose a batch of 10-15 to run pyupgrade on.

Install pyupgrade with:
```
pip install pyupgrade==2.7.2
```
Then, run
```
pyupgrade <files you want to upgrade> --py37-plus
```
e.g.
```
pyupgrade pandas/tests/io/test_html.py pandas/tests/io/json/test_ujson.py --py37-plus
```

See  #36453 for an example PR.

Once this is done, we can add it to pre-commit / CI.

**Comment by ahgamut** [comment]
I'll try to submit a PR for this. take

**Comment by ahgamut** [comment]
I've submitted #36457 for all the unchecked files.
