### ISSUE TITLE
QST: Wish to know how to properly avoid SettingwithCopyWarning without changing dtype

### ISSUE THREAD

**Issue by DOH-Manada** [pandas-dev/pandas#36505]
- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).
---

#### Question about pandas

The data dataframe's label column is dtype: float64, and consists of four numbers, `[ 0.,  2.,  1.,  3., nan]`.
```python
data[label_column][data[label_column] != 2] = 0
```
produces a SettingWithCopyWarning as it should. However,

```python
data.loc[data[label_column] != 2, label_column] = 0
```
does not produce a SettingWithCopyWarning, but changes the column to dtype: object.

I recognize `.loc` tries to cast back to the original dtype on assignment and `[]` does not based on [the getting started docs](http://pandas-docs.github.io/pandas-docs-travis/getting_started/basics.html), but I would like to know if the expected behaviour in this situation is expected and what the proper syntax I should use to avoid the warning but preserve the dtype.

**Comment by erfannariman** [comment]
Can you create a reproducable example?

**Comment by DOH-Manada** [comment]
Sorry erfannariman, I didn't realize that my column actually contained nans. 

My reproducible example is below, even though I am not getting the same behaviour I described before.
```
import pandas
import numpy

data = {'Name':['Tom', 'Jack', 'nick', 'juli'], 'marks':[0., 1., 2., numpy.nan]}
df = pandas.DataFrame(data)
label_column = 'marks'


df1 = df.copy();
df2 = df.copy();

df1[label_column][df1[label_column] != 2] = 0;
df2.loc[df2[label_column] != 2, label_column] = 0;

print(df1.head());
print(df1.dtypes);

print(df2.head());
print(df2.dtypes);
```

**Comment by jreback** [comment]
please read the docs; this is the very first example of chained indexing 


https://pandas.pydata.org/docs/user_guide/indexing.html

**Comment by jreback** [comment]
it's not always possible to preserve dtypes with integer dtypes
