### ISSUE TITLE
BUG: concat series returns error result when indexes use tuples with NA in them

### ISSUE THREAD

**Issue by hdou** [pandas-dev/pandas#36500]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
import pandas as pd

names=['A1','A2']

idx1 = [(1,1), (2, pd.NA)]
idx2 = [(2, pd.NA), (3,3)]

s1 = pd.Series([11,12], index=idx1)
s2 = pd.Series([13,14], index=idx2)
s3 = pd.concat([s1, s2], axis=1)
print (s3)
#           0     1
# 1 1    11.0   NaN
# 2 NaN   NaN   NaN     <= expect 12.0 13.0 as the values
# 3 3     NaN  14.0
```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]
INSTALLED VERSIONS
------------------
commit           : 2a7d3326dee660824a8433ffd01065f8ac37f7d6
python           : 3.8.5.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
Version          : Darwin Kernel Version 18.7.0: Thu Jun 18 20:50:10 PDT 2020; root:xnu-4903.278.43~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.2
numpy            : 1.19.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 47.1.0
Cython           : 0.29.21
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
</details>

**Comment by dsaxton** [comment]
See @phofl's response to your other issue https://github.com/pandas-dev/pandas/issues/36479. Also #30750 #36060 #36470, etc.

**Comment by ivanovmg** [comment]
Probably because ``pd.NA`` is not comparable (no equal, not not equal) with ``pd.NA``?
I am not sure, but I guess index values has to be comparable.

**Comment by mroeschke** [comment]
Thanks for the report. Agreed that this seem to overlap/be related to linked issues so going to close in favor of those issues.
