### ISSUE TITLE
BUG:  Series.replace does not work as intended when replacing values with None

### ISSUE THREAD

**Issue by zzztpppp** [pandas-dev/pandas#36513]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
>>> pd.Series([1, 2,2 ,3, 3])
>>> s.replace(2, None)
0    1
1    1
2    1
3    3
4    3
dtype: int64



```

#### Problem description

This should replace all the 2's with None. 

#### Expected Output
```
0    1.0
1    NaN
2    NaN
3    3.0
4    3.0
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : d9fff2792bf16178d4e450fe7384244e50635733
python           : 3.7.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-957.el7.x86_64
Version          : #1 SMP Thu Nov 8 23:39:32 UTC 2018
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.0
numpy            : 1.18.5
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 49.1.0.post20200710
Cython           : 0.29.20
pytest           : 5.4.3
hypothesis       : 5.18.3
sphinx           : 3.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.2.9
lxml.etree       : 4.5.1
html5lib         : 1.1
pymysql          : 0.10.1
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.16.1
pandas_datareader: None
bs4              : 4.9.1
bottleneck       : 1.3.2
fsspec           : 0.7.4
fastparquet      : None
gcsfs            : None
matplotlib       : 3.2.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.4
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.18
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.50.1

</details>

**Comment by asishm** [comment]
@zzztpppp this is intended behavior as documented
https://pandas.pydata.org/docs/reference/api/pandas.Series.replace.html

> When value=None and to_replace is a scalar, list or tuple, replace uses the method parameter (default ‘pad’) to do the replacement. So this is why the ‘a’ values are being replaced by 10 in rows 1 and 2 and ‘b’ in row 4 in this case. The command s.replace('a', None) is actually equivalent to s.replace(to_replace='a', value=None, method='pad'):
> 
> s.replace('a', None)
> 0    10
> 1    10
> 2    10
> 3     b
> 4     b
> dtype: object

**Comment by zzztpppp** [comment]
@asishm 
Oh thanks! I did miss the default None in the documentation.  Now should I close this issue?

**Comment by mroeschke** [comment]
Yes this is working as intended per the documentation, so going to close for now.
