### ISSUE TITLE
DOC: default value for pd.DateOffset() is 24 hours instead of 1 calendar day

### ISSUE THREAD

**Issue by GYHHAHA** [pandas-dev/pandas#36512]
```python
>>>pd.__version__
1.1.1
>>>ts = pd.Timestamp('2011-3-27 00:00:00', tz='Europe/Helsinki')
>>>ts + pd.DateOffset(days=1)
Timestamp('2011-03-28 00:00:00+0300', tz='Europe/Helsinki')
>>>ts + pd.DateOffset()
Timestamp('2011-03-28 01:00:00+0300', tz='Europe/Helsinki')
>>>ts + pd.DateOffset(hours=24)
Timestamp('2011-03-28 01:00:00+0300', tz='Europe/Helsinki')
```

The default action for pd.DateOffset seems to be equal to pd.DateOffset(hours=24) instead of pd.DateOffset(days=1).
But the user guide says DateOffset object defaults to 1 calendar day.

<img width="611" alt="捕获" src="https://user-images.githubusercontent.com/41546976/93727690-db677480-fbee-11ea-9439-24979ebb85ce.PNG">

**Comment by arw2019** [comment]
What would you expect to get instead?

**Comment by GYHHAHA** [comment]
I want to get Timestamp('2011-03-28 00:00:00+0300', tz='Europe/Helsinki') when use ts + pd.DateOffset().

**Comment by arw2019** [comment]
Hmmm  so I'm not sure whether this is the expected behavior from `DateOffset`

For your specific use case would `round` be a solution?
```
In [7]: ts.round('D')                                                                                  
Out[7]: Timestamp('2011-03-28 00:00:00+0300', tz='Europe/Helsinki')
```

**Comment by GYHHAHA** [comment]
Oh, I know how to convert it to this form.
But just that is not matching the doc description.

> For example, a Timedelta day will always increment datetimes by 24 hours, while a DateOffset day will increment datetimes to the same time the next day whether a day represents 23, 24 or 25 hours due to daylight savings time.

Thus maybe it's more clear to point out the default value is 24 hours not a calendar day here.

**Comment by arw2019** [comment]
Ok, makes sense! Are you interested in opening a PR to add this clarification to the doc?

**Comment by GYHHAHA** [comment]
glad to

**Comment by arw2019** [comment]
Fantastic. Here's the [contributions guide](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html) with the instructions
