### ISSUE TITLE
BUG: Indexing Pandas dataframe via timestamps - inclusive at either end of range

### ISSUE THREAD

**Issue by IainStrachan** [pandas-dev/pandas#36548]
- [x] I have checked that this issue has not already been reported.

- [ x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
import numpy as np

# Integer indexing, non-inclusive  i1 <= i < i2
dfi = pd.DateFrame(np.cumsum(np.ones(3))
print(dfi[0:2])
 
"""
    0
0  1.0
0  2.0
"""

# Indexing via timestamp inclusive at both ends t1 <= t <= t2

idx = pd.date_range('2020/1/1','2020/1/3')
df = pd.DataFrame(np.cumsum(np.ones(3)),index = idx)
print(df[idx[0]:idx[2])

"""
             0
2020-01-01  1.0
2020-01-02  2.0
2020-01-03  3.0
"""


```

#### Problem description

If I have a pandas dataframe that is indexed by timestamps, and I specify a slice based on two timestamps (t1,t2) eg:

df[t1:t2] then I find that the slice is inclusive of both t1 and t2, ie it selects all items for which t1 <= t <= t2

However if it is indexed by integers, i1, i2, then df[i1:i2] selects all i where t1<=i<t2  ie is inclusive at the higher end

Is the behaviour for timestamps by design or a bug?  It leads to incorrect code, for example if I have two adjacent time windows (t1,t2) and (t2,t3) then if one of the items in the dataframe is indexed at exactly t2, that item appears in both windows.

#### Expected Output

Example:

I have a Pandas dataframe df, where the index is a timestamp.

If I then do 

len(df[df.index[0]:df.index[2]], 

then the result is three, having selected the elements at index[0] index[1] and index[2]

But if it is indexed by an integer,  then the result is 2 as I expect, so points at the boundary aren't double counted.

I do not know if this is designed behaviour

**Comment by phofl** [comment]
Hey, thanks for your report. Could you please provide a minimal example (see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) and change the title to something more meaningful?

**Comment by phofl** [comment]
Your second print statement has errors. Could you please fix them?

**Comment by jorisvandenbossche** [comment]
@IainStrachan this is the documented behaviour. Slicing with integers is positional indexing (see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#slicing-ranges), while slicing with timestamps is using the labels. And then see here (https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#selection-by-label, the first paragraph after the three warning boxes) saying that label-based indexing includes both start and end point. 

(I am certainly not saying it is clearly documented, clearly room for improvement ..)

**Comment by IainStrachan** [comment]
> @IainStrachan this is the documented behaviour. Slicing with integers is positional indexing (see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#slicing-ranges), while slicing with timestamps is using the labels. And then see here (https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#selection-by-label, the first paragraph after the three warning boxes) saying that label-based indexing includes both start and end point.
> 
> (I am certainly not saying it is clearly documented, clearly room for improvement ..)

Thanks for the clarification - so as I understand it timestamp indices are treated as labels and hence inclusive.

It causes problems for signal processing where you divide into adjacent windows of data, because a data point that falls exactly on the window boundary thereby crops up in both windows.  So I guess if you want to do this the best thing would be to convert the timestamp into an integer (e.g. number of ticks since the start) and then use that as the index.

The problem occurred as I am converting some Python to c#, and did indeed convert the timestamps to integers relative to the start.  By pure fluke, one of my data files had a sample that fell on a window boundary to the exact millisecond, and I used positional indexing - this showed up in a unit test failure as the number of data points in one of the windows was off by one.

Is there a case for making timestamps behave via positional indexing?  After all they are numbers, not really labels.

**Comment by leonarduschen** [comment]
@IainStrachan you can do it like so `df.loc[df.index[0:2]]`

**Comment by IainStrachan** [comment]
> @IainStrachan you can do it like so `df.loc[df.index[0:2]]`

That works in the simple example I gave, but in the application the timestamps between which you take the slice are not necessarily in the actual index.  It is a timestamped series, but the begin and end of the slice are a constant width window.  So this would only work if some of the timestamps occurred at the exact time of the window boundary.  The only solution that works seems to be to have the end of one window reduced by, say 1 nanosecond with respect to the beginning of the next (my readings are to the nearest millisecond).   

This is why I think timestamps should be a special case - because it is so common in signal processing to divide a time series into windows of fixed length.  I can understand it is correct for labels, like if you had ['Monday', 'Tuesday', 'Wednesday' ...] for an index, then if you asked for df['Monday':Wednesday'] then it would make sense to give the Wednesday entry.  But not, I think if you are using timestamps, which are, after all, numbers.

**Comment by jreback** [comment]
-1 on any change in this
it is so ingrained it can never be chained

and it actually a very simple clear rule

if you want label indexing then simply use .loc and you can get it

**Comment by jbrockmendel** [comment]
> into windows of fixed length

Have you looked at IntervalIndex?  That specifically supports clopen intervals.

Another option might be "partial string indexing", where `frame.loc["2020-09-30 20:21"]` will give everything between 8:21:00.000000000 and 8:21:59.999999999 (inclusive)

**Comment by IainStrachan** [comment]
> > into windows of fixed length
> 
> Have you looked at IntervalIndex? That specifically supports clopen intervals.
> 
> Another option might be "partial string indexing", where `frame.loc["2020-09-30 20:21"]` will give everything between 8:21:00.000000000 and 8:21:59.999999999 (inclusive)

Thanks - I'll look into that.  I solved it by subtracting 1 ns off the end time, but this looks more elegant.

**Comment by mroeschke** [comment]
Closing as the behavior is documented and expected.
