### ISSUE TITLE
QST: Subclassing DataFrame creates problems with assigning to self when changing size

### ISSUE THREAD

**Issue by hydrogeoscience** [pandas-dev/pandas#36543]
I have successfully subclassed DataFrame (say into CustomDataFrame) according to the recommendations. I am now adding new custom methods to enhance my workflow. I have come across an issue which I have not found an answer to anywhere:

My CustomDataFrame has a DatetimeIndex set. When I manipulate the CustomDataFrame in my class, I am able to assign a _new_ DataFrame to _self_ without an error message, but _self_ does not update if _new_ has more, less or a different DatetimeIndex. I can drop rows using `inplace=True`. However, if I expand manually, I can only add one DatetimeIndex at a time in a loop: `self.loc[idx, :] = new.loc[idx, :]` (which is very slow). When _idx_ is an array, then Pandas throws an error: KeyError: "None of [DatetimeIndex([], dtype='datetime64[ns, pytz.FixedOffset(600)]', name='datetime', length=19998, freq=None)] are in the [index]"

Does anyone know why that is and how I can overcome this issue?

**Comment by jreback** [comment]
you would have to have a fully reproducible example

**Comment by MarcoGorelli** [comment]
> Does anyone know why that is and how I can overcome this issue?

Closing for now, but if you post a reproducible example we can take a look
