### ISSUE TITLE
ENH: Add Option to `.plot.scatter` to Label the Points based on Index name or supplied sequence

### ISSUE THREAD

**Issue by fmagin** [pandas-dev/pandas#36598]
#### Is your feature request related to a problem?

I just had to generate a scatter plot with labels for the points, and was surprised that there isn't an argument to `.plot.scatter` to allow this.

#### Describe the solution you'd like

An additional keyword argument to `df.plot.scatter` that adds labels to the points. This would be off by default because it is not helpful for plots with too many points. I am unsure about the type of the parameter that should be passed. A default case that uses the index (if available) as a label would be useful, otherwise something iterable that contains the value for each point, or a string reference to a column name to use as labels.
   
#### API breaking implications

This would only extend the available options for `.plot.scatter` and should lead to no API breaking changes as long as care is taken that the parameter name doesn't shadow some `kwarg` that would be handled by the underlying functions (incl. matplotlib) instead.

#### Describe alternatives you've considered

My current workaround is simply:

```python
plt = df.plot.scatter(x='x', y='y')

# Label the points
for row in df[['x', 'y']].itertuples():
    plt.text(row.x, row.y, row.Index)
```

If this is a reasonable feature request, I will look into  implementing it myself, but currently I don't have the time, and could not find any previous issue that addresses this feature.

**Comment by mroeschke** [comment]
Thanks for the suggestion, but since there hasn't been much interest from the core devs or community going to close. Can reopen if there's renewed interest
