### ISSUE TITLE
ENH: Expose type annotations declared in `_typing.py`

### ISSUE THREAD

**Issue by giuliobeseghi** [pandas-dev/pandas#36594]
I often use pandas type annotations found in the `_typing` module: `FrameOrSeries`, `FrameOrSeriesUnion`, ...

It feels a bit weird to import stuff from a private module though. Would it make sense to expose *some* annotations in a `typing.py` module?

#### API breaking implications

I wouldn't expect any, `typing.py` could be an additional module that imports from `_typing.py`

#### Describe alternatives you've considered

Alternatively, annotations could be added to the main `__init__.py` so they can be imported with `pandas.*`.

**Comment by rohitkg98** [comment]
Creating a typing module sounds good, I can take it up and make a PR

**Comment by jreback** [comment]
we purposely made _typing.py private

at some point we could have a public typing which would import some of these

**Comment by simonjayhawkins** [comment]
use https://github.com/pandas-dev/pandas-stubs
