### ISSUE TITLE
DOC: Replace single with double backticks in RST files

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#36617]
https://github.com/pandas-dev/pandas/pull/36591 added a pre-commit hook for flagging the use of single instead of double backticks for code blocks in restructured text. This is a pretty common mistake in the docs so a lot of files have to be skipped, but we should instead remove these exclusions and fix the relevant files.

Note that this might mean _removing_ rather than adding backticks if the text is not actual code. Also certain linked references require single backticks, see https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#xref-syntax.

In addition to most release notes these files all have errors:

- [x] doc/source/user_guide/10min.rst
- [x] doc/source/user_guide/timeseries.rst
- [x] doc/source/user_guide/visualization.rst
- [x] doc/source/user_guide/missing_data.rst
- [x] doc/source/user_guide/options.rst
- [x] doc/source/user_guide/reshaping.rst
- [x] doc/source/user_guide/scale.rst
- [x] doc/source/user_guide/merging.rst
- [x] doc/source/user_guide/cookbook.rst
- [x] doc/source/user_guide/enhancingperf.rst
- [x] doc/source/user_guide/groupby.rst
- [x] doc/source/user_guide/io.rst
- [x] doc/source/getting_started/overview.rst
- [x] doc/source/reference/panel.rst
- [x] doc/source/reference/plotting.rst
- [x] doc/source/user_guide/basics.rst
- [ ] doc/source/user_guide/categorical.rst
- [ ] doc/source/development/contributing.rst
- [ ] doc/source/development/contributing_docstring.rst
- [ ] doc/source/development/extending.rst
- [ ] doc/source/ecosystem.rst
- [ ] doc/source/getting_started/comparison/comparison_with_sql.rst
- [ ] doc/source/getting_started/install.rst
- [ ] doc/source/getting_started/intro_tutorials/06_calculate_statistics.rst
- [ ] doc/source/getting_started/intro_tutorials/08_combine_dataframes.rst

Easiest worfklow for fixing is probably to install the pre-commit hooks, delete exclusions from https://github.com/pandas-dev/pandas/blob/master/.pre-commit-config.yaml, run `pre-commit run rst-backticks --all-files`, fix the errors and then commit. Any PRs can link back to this issue we'll cross things off when merged.

**Comment by satrio-hw** [comment]
Hi @dsaxton , I would like take this issue, can I?

**Comment by kaptajnen** [comment]
I have added a PR to fix a few of the files. There are still more that needs to be fixed in case anyone else wants to help.

**Comment by satrio-hw** [comment]
Than I'll take :

- doc/source/development/contributing.rst
- doc/source/development/contributing_docstring.rst
- doc/source/development/extending.rst
- doc/source/ecosystem.rst
- doc/source/getting_started/install.rst
- doc/source/getting_started/comparison/comparison_with_sql.rst
- doc/source/getting_started/intro_tutorials/06_calculate_statistics.rst
- doc/source/getting_started/intro_tutorials/08_combine_dataframes.rst
- doc/source/user_guide/categorical.rst

**Comment by Shubhamsm** [comment]
if some files still left to fix I've made a PR #36632

**Comment by dsaxton** [comment]
> Hi @dsaxton , I would like take this issue, can I?

Sure, feel free to simply open a PR (which it looks like you've done)
