### ISSUE TITLE
QST: Error importing pandas

### ISSUE THREAD

**Issue by huyaox** [pandas-dev/pandas#36651]
hello!
when I import any module,this  is a misstake show"No module named'pandas._libs.join'

why?and how to resoled this?

thanks!

**Comment by dimithras** [comment]
Have you updated pandas recently? Try a fresh install:
```console
pip3 uninstall pandas
pip3 install pandas 
```
or
```console
pip uninstall pandas
pip install pandas 
```

**Comment by huyaox** [comment]
ok

**Comment by MarcoGorelli** [comment]
Hi @huyaox - Can you show your full output please?

**Comment by MarcoGorelli** [comment]
Closing, please let us know if you're able to provide any more info and we'll reopen
