### ISSUE TITLE
DEPR deprecate pd.to_timedelta('1 M') and pd.to_timedelta('1 Y')

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#36666]
We have that `pd.to_timedelta(1, unit='M')` and `pd.to_timedelta(1, unit='Y')` are deprecated, and so so should these (xref https://github.com/pandas-dev/pandas/pull/34979#issuecomment-699494617 ).

Once deprecated, the note added in #34979 should be removed

**Comment by avinashpancham** [comment]
take
