### ISSUE TITLE
QST:How to make dataframe output HTML format by default in Cpython shell

### ISSUE THREAD

**Issue by syejing** [pandas-dev/pandas#36736]
---

#### Question about pandas
I wrote jupyter myself. The kernel of the program uses Cpython instead of IPython. The problem is that when I output dataframe data, pandas does not output HTML strings under IPython notebook. How can I set the behavior of pandas to output HTML strings

```python
# Your code here, if applicable
[11]import pandas as pd
[12]data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
[13]df= pd.DataFrame(data)
[14]df
Out:    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2
```

**Comment by syejing** [comment]
I probably know how to change it. I need to change my Python kernel to something similar to IPython display and support calling first_ repr_ html_ , and demote the call after the object is found to be missing__ repr__ method。

**Comment by dsaxton** [comment]
There exists DataFrame.to_html which you could likely use (the repr currently uses DataFrame.to_string)

**Comment by syejing** [comment]
Yes, but there are still many problems to be solved. Under the display hook of interactive shell, you can judge whether to call repr or_ repr_ html_ But if the parameter of print (dataframe) and write function returns the result after automatically calling repr, what should I do？

**Comment by syejing** [comment]
`class DisplayHook(object):

    def __init__(self, session, pub_socket):
        self.session = session
        self.pub_socket = pub_socket
        self.parent_header = {}

    def __call__(self, obj, automatic=True):
        if obj is None:
            return

        builtins._ = obj
        if automatic:
            if getattr(obj, '_repr_html_', None) is not None:
                msg = self.session.msg('pyout', {'data': {'category': 'html', 'content': obj._repr_html_()}},
                                       parent=self.parent_header)
            else:
                msg = self.session.msg('pyout', {'data': {'category': 'text', 'content': repr(obj)}},
                                       parent=self.parent_header)
        else:
            msg = self.session.msg('pyout', {'data': obj}, parent=self.parent_header)
        self.pub_socket.send_json(msg)

    def set_parent(self, parent):
        self.parent_header = extract_header(parent)`
