### ISSUE TITLE
Is there any doucument about telling how to   cross-compile pandas  to arm ? so difficult 

### ISSUE THREAD

**Issue by fanucwj** [pandas-dev/pandas#36739]
- [ ] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
# Your code here, if applicable

```

**Comment by jbrockmendel** [comment]
@WillAyd i think this is just a "no", is there something im not aware of?

**Comment by WillAyd** [comment]
Questions are typically better asked on StackOverflow . This is a rather broad question so difficult to say anything without more details.

I'd suggest starting there and if you see a bug along the way of what you are trying to do feel free to come back and open an issue with more details
