### ISSUE TITLE
BUG: Dataframe filter no longer working in code

### ISSUE THREAD

**Issue by KPStarr** [pandas-dev/pandas#36732]
- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

I was wondering if there were any syntax changes that is preventing the code below from running properly. I am new to Python and I am learning to understand how it works. This code was working 24 hours ago and today it is not. I am using pandas version 0.25.1 on Anaconda
```python
dfs = pd.read_html('https://finance.yahoo.com/trending-tickers') 
for df in dfs:
    pass

df["% Change"] = df["% Change"].str.replace('%',"")

filt_data = (df['Last Price'].astype(float) >= 10.00) & (df['Last Price'].astype(float) <= 100.00) & (df['% Change'].astype(float) > 1)

symbols_most_active = [i for i in df[filt_data].iloc[:,0]] 
print(symbols_most_active)

```

**Comment by dsaxton** [comment]
Can you try to create a copy / pastable example? See https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by MarcoGorelli** [comment]
The issue here is that `df['Last Price']` contains `-`, which can't be converted to `float`

```
In [12]: df['Last Price']
Out[12]:
0       20.85
1       70.52
2      125.40
3       50.71
4      276.93
5      2.1300
6      1.0500
7      4.7600
8      165.66
9       5.020
10     573.61
11     0.5979
12     2.9800
13      11.79
14     3.0300
15      4.020
16     1.1100
17      19.13
18     0.4094
19     3.0400
20       7.82
21    121.400
22      87.79
23    275.600
24     100.47
25          -
26     2.5600
27      82.41
28     376.00
29     0.2841
Name: Last Price, dtype: object
```

Seeing as you're downloading live data, my guess is that something changed upstream

**Comment by MarcoGorelli** [comment]
Closing then as it looks like this isn't a bug in pandas, but please do let us know if you find any other issues
