### ISSUE TITLE
DOC: Summing by level on a category index produce extra columns.

### ISSUE THREAD

**Issue by gepcel** [pandas-dev/pandas#36740]
Generate a dataframe:
```
import pandas as pd
import numpy as np
column_cat = pd.CategoricalDtype(['One', 'Two', 'Three', 'Four'], ordered=True)
groups = list('AABBB')
numbers = pd.Categorical(['One', 'Two','One', 'Two', 'Three'], 
                         categories=column_cat.categories, ordered=True)
d = pd.DataFrame(data=np.arange(15).reshape(3, 5), 
                 columns=pd.MultiIndex.from_arrays([groups, numbers]))
```

<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th colspan="2" halign="left">A</th>
      <th colspan="3" halign="left">B</th>
    </tr>
    <tr>
      <th></th>
      <th>One</th>
      <th>Two</th>
      <th>One</th>
      <th>Two</th>
      <th>Three</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>3</td>
      <td>4</td>
    </tr>
    <tr>
      <th>1</th>
      <td>5</td>
      <td>6</td>
      <td>7</td>
      <td>8</td>
      <td>9</td>
    </tr>
    <tr>
      <th>2</th>
      <td>10</td>
      <td>11</td>
      <td>12</td>
      <td>13</td>
      <td>14</td>
    </tr>
  </tbody>
</table>

Now  do `d.sum(axis=1, level=1)`, get the following result:

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>One</th>
      <th>Two</th>
      <th>Three</th>
      <th>Four</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2</td>
      <td>4</td>
      <td>4</td>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>12</td>
      <td>14</td>
      <td>9</td>
      <td>0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>22</td>
      <td>24</td>
      <td>14</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

Which produces a non existing column `Four`.

pandas 1.1.1, pandas 1.1.2

**Comment by phofl** [comment]
Is this done on purpose? Looks related to the explanation in https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html#operations

**Comment by MarcoGorelli** [comment]
I think so, but the user guide says

> Series methods like Series.value_counts() will use all categories, even if some categories are not present in the data [...] Groupby will also show “unused” categories:

yet here we have a DataFrame method. Perhaps a little example like this one would be a good addition there

**Comment by phofl** [comment]
Then this is not a bug, isn't it?
