### ISSUE TITLE
DOC: TimeStamp.strftime() missing argument description

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#36745]
#### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.Timestamp.strftime.html?highlight=strftime#pandas.Timestamp.strftime

#### Documentation problem

The argument for `TimeStamp.strftime()` is missing in the docs

#### Suggested fix for documentation

Argument is a format string.  Should reference python docs https://docs.python.org/3/library/datetime.html

**Comment by TomAugspurger** [comment]
I think this is a CPython issue. We subclass `datetime.datetime`, and don't override strftime.

```python
In [9]: pd.Timestamp.strftime is datetime.datetime.strftime
Out[9]: True
````

**Comment by Dr-Irv** [comment]
@TomAugspurger So how does the doc page for `Timestamp.strftime()`  get generated?

**Comment by jorisvandenbossche** [comment]
> So how does the doc page for Timestamp.strftime() get generated?

The docstring is inherited as well, so `pd.Timestamp.strftime.__doc__` is the docstring of the stdlib (which is not very informative). 

We could override the method just to add a more elaborate docstring.

**Comment by jorisvandenbossche** [comment]
That's again still an issue with `datetime.datetime`, which simply has no information about its arguments (eg inspecting the signature of it will fail), and which we inherit

**Comment by 7astro7** [comment]
take

**Comment by 7astro7** [comment]
Hi, does solution to #37559 resolve this? I'm unsure despite the open tag and would appreciate other people's opinions on if this still needs addressing. If unresolved, is ~/pandas/_libs/tslibs/timestamps.pyx the correct file to change the documentation in?

**Comment by TomAugspurger** [comment]
I think this is being resolved in https://github.com/python/cpython/pull/20677. Nothing to do in pandas.

@7astro7 let us know if you need help finding another issue.

**Comment by jorisvandenbossche** [comment]
It was actually resolved by https://github.com/pandas-dev/pandas/pull/37559 on the pandas side. That PR added a `Timestamp.strftime` method overriding the parent `datetime.datetime` method, to add a docstring. 
(and it's probably good to do this anyway, as the upstream python one uses different non-numpydoc docstring formatting)
