### ISSUE TITLE
BUG: call to pandas/pandas/core/construction.py  lead to import error

### ISSUE THREAD

**Issue by franckjulliard** [pandas-dev/pandas#36756]
pandas
Version: 1.1.2

https://github.com/pandas-dev/pandas/blob/master/pandas/core/construction.py

line 17 you can see
from pandas._typing import AnyArrayLike, ArrayLike, Dtype, DtypeObj

There is no more DtypeObj in pandas._typing and this lead to import error.

**Comment by jbrockmendel** [comment]
> There is no more DtypeObj in pandas._typing and this lead to import error.

Yes, there is.  How did you install pandas?

**Comment by franckjulliard** [comment]
with pip, doing an upgrade.
![image](https://user-images.githubusercontent.com/45554409/94777903-35daaf00-03ff-11eb-8a66-b1a40cd78ced.png)

**Comment by franckjulliard** [comment]
I reinstall, now it's working fine. 
Sorry for this wrong bug report.
