### ISSUE TITLE
DEPR: |&^ as set operations for Index

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#36758]
It isn't that burdensome to write `left.union(right)` instead of `left | right`, and deprecating this special-case behavior allow us to fully share the implementation with Series.

**Comment by rohitkg98** [comment]
Code might get a bit more verbose when chaining operators. for eg:

```
first | second | third
```
vs
```
first.union(second).union(third)
```

Even more so with other operators:
```
first & second & third
```
vs
```
first.intersection(second).intersection(third)
```

```
first ^ second ^ third
```
vs
```
first.symmetric_difference(second).symmetric_difference(third)
```
sounds fine otherwise. Happy to make a PR if we do decide on deprecating.

**Comment by jorisvandenbossche** [comment]
Previous round of discussions related to this: https://github.com/pandas-dev/pandas/issues/8226 (when we deprecated `+` and `-` as set operations, but decided to keep `&`, `|` and `^`)

**Comment by jbrockmendel** [comment]
@jorisvandenbossche do you feel strongly about keeping the status quo?  

In #8226 it looks like you [initially](https://github.com/pandas-dev/pandas/issues/8226#issuecomment-55103687) suggested doing this, @jreback [said](https://github.com/pandas-dev/pandas/issues/8226#issuecomment-55106112) "I don't think this should change (you are right can reevaluate in the future)", @immerrr seemed [on board](https://github.com/pandas-dev/pandas/issues/8226#issuecomment-55110268) with this, and @shoyer saw upsides [either way](https://github.com/pandas-dev/pandas/issues/8226#issuecomment-55217626).
