### ISSUE TITLE
BUG: Nullable floats can look like ints in repr

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#36775]
Nullable floats when output to the screen can look like ints, but in my opinion should look the same as regular non-NaN floats so as not to cause confusion.
```python
import pandas as pd

s = pd.Series([0.0, 1.0, None], dtype="Float64")
print(s)
# 0       0
# 1       1
# 2    <NA>
# dtype: Float64
print(s.astype(float))
# 0    0.0
# 1    1.0
# 2    NaN
# dtype: float64
pd.__version__
# '1.2.0.dev0+560.g86f543143'

```
cc @jorisvandenbossche

**Comment by simonjayhawkins** [comment]
@dsaxton why is this milestoned 1.1.4. Does #36800 fix some existing formatting issues. test_nullable_float_to_string can't be backported (#34307 is an enhancement for 1.2)

**Comment by jorisvandenbossche** [comment]
Yeah, since nullable floats are only in master, this issue is also for master.

**Comment by jorisvandenbossche** [comment]
But fully agree on the actual bug report! We should indeed ensure that they look as floats
