### ISSUE TITLE
DOC: Fix code style in documentation

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#36777]
The docs use certain coding style conventions that are no longer used in pandas (e.g., we adopt black's opinions in terms of line wrapping and quoting), for instance https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html. We should update the docs to match current style preferences.

[blacken-docs](https://github.com/asottile/blacken-docs) is a useful tool that can help in doing _some_ of this formatting, but it has to be used carefully since it might render lines that are too long and will fail flake8-rst checks, or it may not be able to parse certain files because of nuances in how the docs are written (raw output or magic commands in code blocks). One approach is to comment out the erring lines, let the tool handle all the others, then finish the commented lines manually.

Example cleanup: https://github.com/pandas-dev/pandas/pull/36700/files

List of files that need updating (if you submit a PR be sure to link back to this issue):

**doc/source/development:**

- [x] code_style.rst
- [x] contributing.rst
- [x] contributing_docstring.rst
- [x] developer.rst
- [x] extending.rst
- [x] index.rst
- [x] internals.rst
- [x] maintaining.rst
- [x] meeting.rst
- [x] policies.rst
- [x] roadmap.rst

**doc/source/getting_started/comparison:**

- [x] comparison_with_r.rst
- [x] comparison_with_sas.rst
- [x] comparison_with_sql.rst
- [x] comparison_with_stata.rst
- [x] index.rst

**doc/source/getting_started/intro_tutorials:**

- [x] 01_table_oriented.rst
- [x] 02_read_write.rst
- [x] 03_subset_data.rst
- [x] 04_plotting.rst
- [x] 05_add_columns.rst
- [x] 06_calculate_statistics.rst
- [x] 07_reshape_table_layout.rst
- [x] 08_combine_dataframe.rst
- [x] 09_timeseries.rst
- [x] 10_text_data.rst

**doc/source/getting_started:**

- [x] index.rst
- [x] install.rst
- [x] overview.rst
- [x] tutorials.rst

**doc/source/user_guide**:

- [x] 10min.rst
- [x] advanced.rst
- [x] basics.rst
- [x] boolean.rst
- [x] categorical.rst
- [x] computation.rst
- [x] cookbook.rst
- [x] dsintro.rst
- [x] duplicates.rst
- [x] enhancingperf.rst
- [x] gotchas.rst
- [x] groupby.rst
- [x] index.rst
- [x] integer_na.rst
- [x] io.rst
- [ ] merging.rst
- [x] missing_data.rst
- [x] options.rst
- [x] reshaping.rst
- [x] scale.rst
- [x] sparse.rst
- [x] text.rst
- [x] timedeltas.rst
- [x] timeseries.rst
- [x] visualization.rst

**Comment by Meghana-12** [comment]
I'd like to work on this.

**Comment by dsaxton** [comment]
> I'd like to work on this.

Sure, feel free to submit a PR

**Comment by Meghana-12** [comment]
Are there any docs you'd like me to fix first? @dsaxton

**Comment by dsaxton** [comment]
> Are there any docs you'd like me to fix first? @dsaxton

Up to you, probably the best way would be to browse through the rst files in https://github.com/pandas-dev/pandas/tree/master/doc/source (the `user_guide` folder might be a good place to start) and check for code blocks that use "old style" formatting and update those. Any improvement is appreciated!

**Comment by erfannariman** [comment]
Files I reformatted in #36780 so others won't do double work:

- doc/source/getting_started/intro_tutorials/06_calculate_statistics.rst
- doc/source/getting_started/intro_tutorials/07_reshape_table_layout.rst
- doc/source/getting_started/intro_tutorials/08_combine_dataframes.rst
- doc/source/getting_started/intro_tutorials/09_timeseries.rst
- doc/source/getting_started/intro_tutorials/10_text_data.rst
- doc/source/user_guide/10min.rst
- doc/source/user_guide/sparse.rst

**Comment by mvoitko** [comment]
@dsaxton Any ideas about docs needed to be fixed first? I would like to contribute. I am also planning to hold a Hacktoberfest meetup and I am sure there would be some guys who would love to help pandas, so I would really appreciate it if you could make some kind of prioritized list of docs which should be fixed first.

**Comment by dsaxton** [comment]
> @dsaxton Any ideas about docs needed to be fixed first? I would like to contribute. I am also planning to hold a Hacktoberfest meetup and I am sure there would be some guys who would love to help pandas, so I would really appreciate it if you could make some kind of prioritized list of docs which should be fixed first.

That would be awesome, @erfannariman put together a list of files (thank you!) that I just added to the OP

**Comment by erfannariman** [comment]
> @dsaxton Any ideas about docs needed to be fixed first? I would like to contribute. I am also planning to hold a Hacktoberfest meetup and I am sure there would be some guys who would love to help pandas, so I would really appreciate it if you could make some kind of prioritized list of docs which should be fixed first.

As @dsaxton already mentioned [here](https://github.com/pandas-dev/pandas/issues/36777#issuecomment-702258346) the `user_guide` is probably a good place to start.

**Comment by karasinski** [comment]
It looks like the following are already compliant with blacken and flake8 and need no additional formatting.

**doc/source/development:**
-  contributing_docstring.rst
-  developer.rst

**doc/source/user_guide:**
-  boolean.rst
-  categorical.rst
-  index.rst
-  integer_na.rst
-  options.rst
-  reshaping.rst
- timedeltas.rst

**Comment by karasinski** [comment]
Upon further inspection, it looks like doc/source/user_guide/text.rst is also fine as is.

**Comment by Mikhaylov-yv** [comment]
I fixed computation.rst
Hope everything is good

https://github.com/pandas-dev/pandas/pull/36829

**Comment by erfannariman** [comment]
> I fixed computation.rst
> Hope everything is good
> 
> #36829

Thanks, you committed your changes to your fork, next step is to create a pull request to the pandas repository so we can merge it.

**Comment by skorani** [comment]
I fixed visualization.rst

**Comment by Mikhaylov-yv** [comment]
Sorry, did I do the right thing here or not? a3850c9

**Comment by dsaxton** [comment]
> a3850c9

That looks fine aside from the line wrapping of dtypes

**Comment by Meghana-12** [comment]
> > Are there any docs you'd like me to fix first? @dsaxton
> 
> Up to you, probably the best way would be to browse through the rst files in https://github.com/pandas-dev/pandas/tree/master/doc/source (the `user_guide` folder might be a good place to start) and check for code blocks that use "old style" formatting and update those. Any improvement is appreciated!

Sure, thank you!

**Comment by skorani** [comment]
timedeltas.rst and timeseries.rst are fixed.

**Comment by SambhaviPD** [comment]
@dsaxton - Thought of contributing to this issue, went through most of the files in pandas/doc/source and found them to be formatted similar to https://github.com/pandas-dev/pandas/pull/36700/files. Is this whole list complete?

**Comment by dsaxton** [comment]
> @dsaxton - Thought of contributing to this issue, went through most of the files in pandas/doc/source and found them to be formatted similar to https://github.com/pandas-dev/pandas/pull/36700/files. Is this whole list complete?

Yes I think everything is pretty much fixed, but will probably leave open for a little bit in case anything else shows up.
