### ISSUE TITLE
API: disallow frame.__and__(other, axis="foo", fill_value="bar") etc

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#36796]
For code-sharing purposes we re-use ops.arith_method_FRAME for both flex and non-flex methods.  As a result, the non-flex methods have the flex signature, and accept arguments not generally accepted by dunder methods.  We even have a few tests e.g.

```
result = d.__and__(s, axis="columns")
result = d.__and__(s, axis=0)
```

in tests.frame.test_operators.

Should we disallow passing these arguments?  Is it relevant that we do _not_ have flex versions of and/or/xor?

**Comment by jreback** [comment]
> Should we disallow passing these arguments? 

yes

> Is it relevant that we do not have flex versions of and/or/xor?

no; I mean we *could* have .and,.or,.xor prob not very useful anyhow.
