### ISSUE TITLE
Reading xml files not directly available in Pandas?

### ISSUE THREAD

**Issue by RahulReady** [pandas-dev/pandas#36798]
- [ X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com). (There are workarounds to this, but this is a question to the devs)

---

#### Question about pandas
I have already figured out a workaround to reading xml files by using '**xml.etree.ElementTree**', but I was not able to find a read_xml() function in the pandas library. 

There is another package '**https://pypi.org/project/pandas-read-xml/**' that implements this function, but it seems like extra steps for an individual to download another package if they wanted to read the xml file (should they decide not to implement it themselves).

May I know the thought process for not having such function, or if I am blatantly missing something, kindly excuse the ignorance.

**Comment by mroeschke** [comment]
Thanks for the suggestion. We have a duplicate request at https://github.com/pandas-dev/pandas/issues/27554

**Comment by ghuname** [comment]
It would be nice to have df.to_xml() as well.
