### ISSUE TITLE
BUG: Series.groupby.rolling duplicates  index when grouping over index

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#36794]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
data = {
    'groupby_col': ['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B', ],
    'agg_col': [1, 1, 0, 1, 0, 0, 0, 0, 1, 0],
}
df = pd.DataFrame(data).set_index("groupby_col")
grouped = df.groupby('groupby_col')
rolled = grouped.rolling(4)

result = rolled.mean()
print(result)

```
Output:
```
                         agg_col
groupby_col groupby_col         
A           A                NaN
            A                NaN
            A                NaN
            A               0.75
            A               0.50
B           B                NaN
            B                NaN
            B                NaN
            B               0.25
            B               0.25
```

#### Problem description

The duplicate ``groupby_col`` seems at least odd.

...

#### Expected Output

Would expect, that we get ``groupby_col`` only once in the index and a ``Series`` instead of a ``DataFrame``

Maybe related to #36507, but

```
data = {
    'groupby_col': ['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B', ],
    'agg_col': [1, 1, 0, 1, 0, 0, 0, 0, 1, 0],
}
df = pd.DataFrame(data).set_index("groupby_col")
grouped = df.groupby('groupby_col')
result = grouped.apply(sum)
print(result)
```
works. So I am not sure.

#### Output of ``pd.show_versions()``

<details>

master

</details>

**Comment by mroeschke** [comment]
Though there's redundancy, I am not sure that I'd totally classify it as a bug.

This behavior is consistent before I made changes to `groupby.rolling` it's own independent calculation (in version 1.0.0). Previously this operation under the hood was equivalent to `groupby.apply(lambda x.rolling(...))`

```
In [1]: data = {
   ...:     'groupby_col': ['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B', ],
   ...:     'agg_col': [1, 1, 0, 1, 0, 0, 0, 0, 1, 0],
   ...: }
   ...: df = pd.DataFrame(data).set_index("groupby_col")
   ...: grouped = df.groupby('groupby_col')
   ...: rolled = grouped.rolling(4)
   ...:
   ...: result = rolled.mean()
   ...: print(result)
                         agg_col
groupby_col groupby_col
A           A                NaN
            A                NaN
            A                NaN
            A               0.75
            A               0.50
B           B                NaN
            B                NaN
            B                NaN
            B               0.25
            B               0.25

In [2]: pd.__version__
Out[2]: '1.0.0'
``` 

I think the MultiIndex levels should always be comprised by `[groupby levels, rolling index]` even if both levels are redundant. I think special casing for redundant levels is not worth it, and dropping the redundant level can be left to the user.

**Comment by phofl** [comment]
Thanks very much for the background information. Closing this issue.

**Comment by jreback** [comment]
yep this makes sense
thanks @mroeschke
