### ISSUE TITLE
DOC: unclear kwarg null_counts

### ISSUE THREAD

**Issue by ivanovmg** [pandas-dev/pandas#36805]
#### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.info.html?highlight=info#pandas.DataFrame.info

#### Documentation problem

Keyword ``null_counts`` from its name may be considered as a need to count null items.
However, the documentation explains that is quite the opposite - count **non-null** items.
I suggest to rename it with ``show_counts`` and maintain the old behavior.

#### Suggested fix for documentation

Replace ``null_counts`` with ``show_counts``.
It will make it more clear what this kwarg means without even the need to read docs.

#### API

It the suggested rename is implemented, then need to start deprecation of kwarg ``null_counts``.

**Comment by MarcoGorelli** [comment]
I agree that it's a bit of a misnomer, but wouldn't renaming potentially break people's code?

**Comment by ivanovmg** [comment]
I suggest smooth transition to the new kwarg via the deprecation process, so that nobody's code gets broken right away.
We can start with throwing warnings that the old kwarg is deprecated and in version X.X will be removed.

**Comment by MarcoGorelli** [comment]
Might be worth it actually - I _think_ people are only likely to use `.info` in an interactive session, rather than as part of production code, so perhaps it is worth going through the deprecation process to make this argument clearer
