### ISSUE TITLE
QST: while trying to convert categorical variables which are ordinal , i ran the following code

### ISSUE THREAD

**Issue by senthilguna79** [pandas-dev/pandas#36830]
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
# Your code here, if applicable

```

**Comment by erfannariman** [comment]
This ticket is not reviewable. If it's pure about usage, it's better to post your question on stackoverflow. Otherwise please edit your question with a reproducable example.

**Comment by MarcoGorelli** [comment]
Hi @senthilguna79 

Closing as this is too far off from being a usable bug report, sorry

See https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports for how to report bugs - if you edit your issue accordingly and let us know, we'll reopen it
