### ISSUE TITLE
Add hacktoberfest topic to the repo

### ISSUE THREAD

**Issue by PrayagS** [pandas-dev/pandas#36837]
Hacktoberfest 2020 has undergone some changes due to the excessive spamming that occurred this year. The rules for a PR to be accepted have been modified. Detailed post on their official website can be found [here](https://hacktoberfest.digitalocean.com/hacktoberfest-update).

Here is the most important part for maintainers:

![](https://user-images.githubusercontent.com/44412790/94985906-ef5c9000-0577-11eb-9eaa-850fcd0b0942.png)

As one can see, the maintainers need to add the `hacktoberfest` topic to the repo in order for all the PRs to be considered valid. This is completely opt-in and this issue serves as a notification for the maintainers in case they want to take part.

**Comment by MarcoGorelli** [comment]
Thanks for the suggestion @PrayagS 

There's already lots of open pull requests, so I'd be hesitant to add the 'hacktoberfest' topic, but let's see what others say

**Comment by Meghana-12** [comment]
Hey, how about adding hacktoberfest label to the issues people (interested in contributing to the issue) ask for it? And of course only to the issues/PRs you feel are worthy of being part of hacktoberfest!

**Comment by PrayagS** [comment]
@Meghana-12 Sadly that wouldn't work as having `hacktoberfest` in the topics list is a primary requirement. Refer the link/pic in my OP.

**Comment by Meghana-12** [comment]
Oh, I see... my bad!

**Comment by rhshadrach** [comment]
> There's already lots of open pull requests, so I'd be hesitant to add the 'hacktoberfest' topic, but let's see what others say

I don't see why having a lot of open PRs is a reason not to do this. We only need to tag as such when requested by the author, right? No need to do a systematic review of all PRs to tag.

**Comment by MarcoGorelli** [comment]
OK, sure - to be fair, if Hacktoberfest have changed their rules so that PRs need to be accepted to count, then the chances of being overloaded with
```diff
- pandas
+ pandas - awesome library
```
_should_ be reduced :smile:

**Comment by Meghana-12** [comment]
Yeah, and the maintainers can always mark a PR invalid if necessary.

**Comment by dsaxton** [comment]
It's true that there are a lot of open PRs, but there are even more open issues (many marked as "good first issue"). I also wouldn't want to discourage people who started contributing due to Hacktoberfest before DigitalOcean changed the rules.

It isn't too hard to close obvious spam PRs, and I suppose could always remove the topic if things get really out of control.

**Comment by Meghana-12** [comment]
I just saw this on the [hacktoberfest](https://hacktoberfest.digitalocean.com/details) website :
"Additionally, any pull request with the` hacktoberfest-accepted` label, submitted to any public GitHub repository, **with or without** **the hacktoberfest topic**, will be considered valid for Hacktoberfest."
So, adding the` hacktoberfest` topic isn't compulsory and without the `hackoberfest` topic I believe there will be less spam PRs. So, the maintainers can add the label only if the author asks for and ofc only if the maintainers think they are good enough.

**Comment by dsaxton** [comment]
I think that sounds like a reasonable compromise. If contributors reference this issue from merged PRs that they want counted, that could also help keeping track.

**Comment by rhshadrach** [comment]
@dsaxton +1

**Comment by GrosSacASac** [comment]
How  to add hacktoberfest topic ?
