### ISSUE TITLE
mean over axis=1 in not-completely-numeric frame returns all nans

### ISSUE THREAD

**Issue by cpcloud** [pandas-dev/pandas#3689]
DataFrame from #3688. This might be related to that:

``` python
df = pd.DataFrame({'bar': {0: 1, 1: 1, 2: 1}, 'foo': {0: 0, 1: 1, 2: 2}, 'foo1': {0: 1, 1: 2, 2: 3}, 'hello': {0: 'a', 1: 'a', 2: 'a'}}, columns=['bar', 'foo', 'foo', 'hello'])
print df.T.sum(1) == df.sum()  # fine. + is str cat
print df.T.mean(1).isnull().all()  # prints True
```

I think non numeric should be dropped...

**Comment by WillAyd** [comment]
Problem still exists on master

**Comment by jbrockmendel** [comment]
> I think non numeric should be dropped...

`df.T` is _all_ object dtype, so you would be dropping everything.  Is that what you have in mind?

On the other hand, `df.mean(axis=0)` works as we'd expect.

**Comment by DriesSchaumont** [comment]
This now provides a warning, will raise in the future: ```FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.```  xref #28900

**Comment by DriesSchaumont** [comment]
> do we have sufficient tests on the warning?

Tests for the warnings in dataframe reductions were added in https://github.com/pandas-dev/pandas/pull/41480
