### ISSUE TITLE
ENH: Intermediate join results that preserve data frame alias, similar to SQL joins

### ISSUE THREAD

**Issue by RedTailedHawk** [pandas-dev/pandas#36890]
Please take a look at this stackoverflow post (this is my post) and let me know what you think.  You can answer the question if you like, but I'm guessing the answer is that there is currently no other way to handle the column conflicts other than using the suffixes keyword.

https://stackoverflow.com/questions/64126437/pandas-merges-and-suffixes

As such, I have been enhancing my Pandas code generator to deal with column conflicts, but would be a really nice Pandas feature to be more "SQL like" in how merges are handled in that the "intermediate results" preserve the original column names and then allow you to reference by dataset alias.

Thanks.

**Comment by dsaxton** [comment]
You can also do your own aliasing before the join and not rely on the suffixes keyword at all:
```python
import pandas as pd

df = pd.DataFrame({"a": [1, 2], "b": [1, 2], "c": [1, 2]})
print(df)
#    a  b  c
# 0  1  1  1
# 1  2  2  2
result = pd.merge(
    df.rename(columns=lambda c: c + "_left"),
    df.rename(columns=lambda c: c + "_right"),
    left_on="a_left",
    right_on="a_right",
)
print(result)
#    a_left  b_left  c_left  a_right  b_right  c_right
# 0       1       1       1        1        1        1
# 1       2       2       2        2        2        2
```
I think this would let you more or less exactly mimic the SQL approach.

**Comment by RedTailedHawk** [comment]
Hi @dsaxton, thanks for the response.

The approach you're suggesting still means that the columns in the data frames will need to change so as not to conflict with each other when they are merged.

In the SQL world, you can join lots of tables together and not have to worry about the column names, since there's a  `SELECT` clause that allows the columns to be referenced by their _original_ names via table aliases.  For example:

```-- dataset_join_node(out, [a, b, c])
SELECT r1_1.amount AS "sales_vt", r1_2.amount AS "sales_ny", r1_3.amount AS "sales_mi",
       r1_1.amount + r1_2.amount + r1_3.amount AS "sales_total"
FROM
(
    -- leaf_node(a, fact_sales)
    SELECT ... AS amount
    FROM ...
) AS r1_1
CROSS JOIN
(
    -- leaf_node(b, fact_sales)
    SELECT ... AS amount
    FROM ...
) AS r1_2
CROSS JOIN
(
    -- leaf_node(c, fact_sales)
    SELECT ... AS amount
    FROM ...
) AS r1_3
```

I don't have to rename anything beforehand, or worry about suffixes added on to columns that collide after each pair of tables in the pipeline are joined together.

I know that Pandas is not SQL, but it sure would be nice to be able to do something like this:

```
out_dataset_join_node = (
    a_leaf_node_fact_sales
    .merge(b_leaf_node_fact_sales, how="outer", left_on=["__x"], right_on=["__x"])
    .merge(c_leaf_node_fact_sales, how="outer", left_on=["__x"], right_on=["__x"])
    .select({ "sales_vt" : a_leaf_node_fact_sales["amount"],
                   "sales_ny" : b_leaf_node_fact_sales["amount"],
                   "sales_mi" : c_leaf_node_fact_sales["amount"],
                   "sales_total" : a_leaf_node_fact_sales["amount"] + out_dab_leaf_node_fact_salesaset_join_node["amount"] + c_leaf_node_fact_sales["amount"]})
)
```

**Comment by jreback** [comment]
this is hard to do in pandas proper. but is very easy in ibis: https://ibis-project.org/docs/user_guide/sql.html

which can also run as pandas fyi

**Comment by mroeschke** [comment]
Thanks for the report, but agreed it appears that ibis already has this functionality so it would be redundant to replace in pandas. Closing
