### ISSUE TITLE
REGR: change in Series.astype(str) behavior for None

### ISSUE THREAD

**Issue by itholic** [pandas-dev/pandas#36904]
#### Question about pandas

Let's say we have a `Series` with `None` like the below.

```python
pser = pd.Series(["hi", "hi ", " ", " \t", "", None], name="x")

print(pser)
0      hi
1     hi
2
3      \t
4
5    None
Name: x, dtype: object
```

the last value is `None`, but it is casted to `nan` after using `astype` with `str` parameter.

```python
print(pser.astype(str))
0     hi
1    hi
2
3     \t
4
5    nan
Name: x, dtype: object
```

Is it intended behavior in pandas 1.1.1. ??

Thanks :)

**Comment by dsaxton** [comment]
Thanks @itholic, this seems like a regression and is due to https://github.com/pandas-dev/pandas/pull/35519

cc @topper-123

**Comment by itholic** [comment]
Thanks, @dsaxton :)
