### ISSUE TITLE
ENH: Add option for `to_json` function to discard null values

### ISSUE THREAD

**Issue by Fju** [pandas-dev/pandas#36912]
#### Is your feature request related to a problem?

No, at least not that I am aware of.

#### Describe the solution you'd like

The [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_json.html) states that "NaN’s and None will be converted to null" when using `pandas.DataFrame.to_json`. I'd like to have an option for the `to_json` function, so that keys that have a null value will be discarded. See "'Additional context" for an example.

#### API breaking implications

New optional parameter for `pandas.DataFrame.to_json`. However by default this option should be disabled, so no breaking implications, I think.

#### Additional context

``` python
import pandas as pd
import numpy as np

data = {
    # None and np.nan will result in null values when converting to JSON
    "a": [None, 1, 2],
    "b": [0, np.nan, 0]
}
df = pd.DataFrame(data)

# Note: `discard_null` doesn't exist yet
print(df.to_json(orient="records", discard_null=True))

# current result: [{"a":null,"b":0.0},{"a":1.0,"b":null},{"a":2.0,"b":0.0}]
# desired result: [{"b":0.0},{"a":1.0},{"a":2.0,"b":0.0}]
```

Currently I am only working with `orient="records"`. Does it make sense to restrict the option only to this orientation or does it make sense to implement this option for other orientations as well?

I'd like to implement this feature by myself and contribute a PR. If there are any tips about how I can do this, please let me know 👌

**Comment by erfannariman** [comment]
I would not be perse -1 on this, since I can see the convenience of this. I have to say, you can still do this with `stack`:

```
df.stack().reset_index(level=0, drop=True).to_json(orient='columns')

'{"b":0.0,"a":1.0,"a":2.0,"b":0.0}'
```

**Comment by Fju** [comment]
I don't quite understand your code example. Since the keys `"a"` and `"b"` are re-declared, wouldn't that result in overwriting the previous values and loss of data when parsing the JSON string?

``` python
import json
json.loads('{"b":0.0,"a":1.0,"a":2.0,"b":0.0}')
# result: {'b': 0.0, 'a': 2.0}
```

Is this a bug in `to_json`? The result when running your code snippet doesn't seem to make any sense from a JSON perspective...

**Comment by erfannariman** [comment]
It's not a bug, dictionaries cannot have duplicated keys, to the latter overwrites the first keys. So my solution actually does not work and you can ignore it.

**Comment by Fju** [comment]
I see, but that means that `to_json` produces improper JSON in this scenario, doesn't it?

**Comment by erfannariman** [comment]
> I see, but that means that `to_json` produces improper JSON in this scenario, doesn't it?

You could argue that, but that would be a discussion for another ticket in my opinion. Implementing your solution would be quite tricky on first check I did, since it depends on `json.dumps`. Which will eventually come down to a [loopy implementation](https://stackoverflow.com/questions/4255400/exclude-empty-null-values-from-json-serialization). But I might be wrong.

**Comment by mroeschke** [comment]
Thanks for the report. I'd be -1 on this enhancement as well as preprocessing can be done on the DataFrame first before saving to `to_json`, so a `discard_null` keyword would be fairly niche.

**Comment by prasanik** [comment]
@mroeschke, I too had the same need and stumbled across this while searching. I think we still need this.
Consider a dataframe with a number of columns and a number of rows.. with lot of them with null values for different columns. If you do a to_json(orient='records'), you will end up getting too big a json with lot of the fields appearing as fieldname=null in you json. I don't see a simple way to get rid of the nulls, other than looping over the resultant json. If you or anyone know a way, I'd be glad to hear it.
