### ISSUE TITLE
ENH: pd.unstack(level, values=["a", "b", "c"])

### ISSUE THREAD

**Issue by Hoeze** [pandas-dev/pandas#36916]
#### Is your feature request related to a problem?

I would like to unstack only certain values from a DataFrame to know exactly which columns will be in the resulting dataframe.
For example, when the dataframe is empty, `df.unstack(0)` will just return an empty dataframe without columns:
https://github.com/pandas-dev/pandas/issues/21255

Advantages:
- predictable column layout
- subsetting for certain values

#### Describe the solution you'd like

I'd propose a values option for `pd.DataFrame.unstack()` that lets one specify which values will be unstacked into columns.
E.g. `df.unstack(0, values=["A", "B", "C"])` would ensure that the resulting dataframe has exactly the toplevel columns `A`, `B` and `C`.

#### API breaking implications

N/A

#### Describe alternatives you've considered

I checked out `pd.DataFrame.pivot()`, however, it is more complicated to use and cannot use index levels for unstacking.

**Comment by jreback** [comment]
you can just filter before the unstack
no new to add yet another api

**Comment by Hoeze** [comment]
@jreback Thanks for your answer.

However, filtering does not help if there is no value for `B`.
In this case, `B` will be missing in the resulting columns.

As written above, as an extreme example you can test unstacking an empty dataframe.

**Comment by jreback** [comment]
well after then

i don't really see this as very common

**Comment by Hoeze** [comment]
Actually I end up having this problem quite often when I want to ensure that the dataframe schema keeps being propagated. Also, I cannot think of any solution to this problem beside of changing the "unstack" function.

Do you know a workaround @jreback?

**Comment by rhshadrach** [comment]
> would ensure that the resulting dataframe has exactly the toplevel columns

It's not clear to me what would happen if the index level being unstacked has more or less values. Would they both raise? If so, why not just check the column of the result and raise then?

**Comment by Hoeze** [comment]
> > would ensure that the resulting dataframe has exactly the toplevel columns
> 
> It's not clear to me what would happen if the index level being unstacked has more or less values. Would they both raise? If so, why not just check the column of the result and raise then?

There should not be any error raised. Instead, more values should just be dropped and less values should be filled with N/A.

When specifying the values which should be unstacked, I want to ensure that the resulting dataframe always has the same schema, independent of the input.

**Comment by rhshadrach** [comment]
@Hoeze: Here is an attempt, I'd be interested in hearing if there are edge-cases this misses. It works on the empty frame.

```
def rigid_unstack(df, level, values, fill_value=np.nan):
    result = (
        df[df.index.get_level_values(level).isin(values)]
        .unstack(level)
    )
    idx = 0
    for c in df.columns:
        for value in values:
            if (c, value) not in result.columns:
                result.insert(idx, (c, value), fill_value)
            idx += 1
    return result
```

e.g.

```
df = pd.DataFrame({'a': [0, 1], 'b': [2, 3], 'c': [4, 5], 'd': [6, 7]}).set_index(['a', 'b'])
print(rigid_unstack(df, 0, [1, 2, 3]))
```

produces

```
   c          d        
a  1   2   3  1   2   3
b                      
3  5 NaN NaN  7 NaN NaN
```

**Comment by jreback** [comment]
u can just reindex

**Comment by rhshadrach** [comment]
Ahh, thanks @jreback

**Comment by Hoeze** [comment]
Thanks a lot for solving this @rhshadrach, looks great :grinning: 
Can we have that in the next Pandas version?

**Comment by rhshadrach** [comment]
I can do you one better @Hoeze - that function can be executed on the current version of pandas ;)

In all seriousness though, this is three separate operations: select, unstack, and reindex. I do no think we should add a new function to the API just because there is a use case where they are used together.

**Comment by Hoeze** [comment]
Yes, but having this as the default behavior inside `unstack` would have been nice :slightly_smiling_face: 
Otherwise feel free to close, I do have a working solution to my problem :+1:

**Comment by jreback** [comment]
this is not a good default as it's a bit unexpected
