### ISSUE TITLE
ENH: add string method remove prefix and suffix, python 3.9

### ISSUE THREAD

**Issue by erfannariman** [pandas-dev/pandas#36944]
Opening this issue for discussion:

Since python 3.9 is out, and we have the new [string methods](https://www.python.org/dev/peps/pep-0616/) `removeprefix` and `removesuffix`, it would be nice to add them to the pandas string methods as well
```python
In [2]: import pandas as pd

In [3]: df = pd.DataFrame({'A': ['str_string1', 'str_string2', 'str_string3']})

In [4]: print(df)
             A
0  str_string1
1  str_string2
2  str_string3

In [5]: df['A'].str.removeprefix('str_')
Out[5]: 
0    string1
1    string2
2    string3
Name: A, dtype: object
```
An argument not to add this is that it's pretty easily to achieve with `str.split`:
```python
df['A'].str.split('_').str[-1]
```

**Comment by rhshadrach** [comment]
+1

@erfannariman Your alternative to `removeprefix` will not work on any input, e.g. `str_str_string1` or `other_str_string1`.

**Comment by erfannariman** [comment]
> +1
> 
> @erfannariman Your alternative to `removeprefix` will not work on any input, e.g. `str_str_string1` or `other_str_string1`.

True, but you could solve that with: `str.split('_', n=1).str[-1]`

**Comment by davidwales** [comment]
@erfannariman, your updated version won't work if the prefix is not separated by a delimiter.

e.g. for prefix `str`: `strFollowedByOtherThings`, `strWithDifferentOtherThingsFollowing`.

The most robust method is the one documented in [PEP 616](https://www.python.org/dev/peps/pep-0616/).

e.g.

``` python
prefix = 'str'
df2 = df.copy()
df2.loc[df['A'].str.startswith(prefix), 'A'] = df2.loc[df['A'].str.startswith(prefix), 'A'].str[len(prefix):]
df2
```

I think this makes a pretty good case that it would be nice to add the new string methods!

**Comment by erfannariman** [comment]
> @erfannariman, your updated version won't work if the prefix is not separated by a delimiter.
> 
> e.g. for prefix `str`: `strFollowedByOtherThings`, `strWithDifferentOtherThingsFollowing`.
> 
> The most robust method is the one documented in [PEP 616](https://www.python.org/dev/peps/pep-0616/).
> 
> e.g.
> 
> ```python
> prefix = 'str'
> df2 = df.copy()
> df2.loc[df['A'].str.startswith(prefix), 'A'] = df2.loc[df['A'].str.startswith(prefix), 'A'].str[len(prefix):]
> df2
> ```
> 
> I think this makes a pretty good case that it would be nice to add the new string methods!

Yes, I agree.

**Comment by jreback** [comment]
+1 in adding this

**Comment by janosh** [comment]
@simonjayhawkins Would this be a good first issue? Happy to help in that case.

**Comment by simonjayhawkins** [comment]
Thanks @janosh. sure. go for it!

**Comment by janosh** [comment]
Great. Anything to be aware of? Is it okay to use `removeprefix` or should the implementation be backwards compatible, i.e. work for people on Python <3.9?

**Comment by simonjayhawkins** [comment]
From the comments here and the stalled PR #39226, I believe that we would want to use the implementation in [PEP 616](https://www.python.org/dev/peps/pep-0616/) to order to provide support for Python <3.9.

I think there is an outstanding question on whether we use the python native functions when available https://github.com/pandas-dev/pandas/pull/39226#issuecomment-836719770.

**Comment by janosh** [comment]
Cool, I opened a draft PR at #43328. Let's discuss details there.
