### ISSUE TITLE
QST: Use object property as key?

### ISSUE THREAD

**Issue by DorianCzichotzki** [pandas-dev/pandas#36947]
Is there a way to use a property of an object as the key when providing the object to a DataFrame?
I think the code makes clearer what I am looking for.

```python
class Key:
  def __init__(self, name: str):
    self.name = name
  
  # Something like that
  def __pandas_key__(self):
    return self.name

df = DataFrame({"col": [1,2,3,4]})
key = Key("col")

df[key] # is [1,2,3,4]
```

**Comment by jbrockmendel** [comment]
No, but I think if you do `df = pd.DataFrame({key: [1, 2, 3, 4]})` then `df[key]` works just fine

Longer term, #11723 might make this feasible.

**Comment by TomAugspurger** [comment]
This would be subsumed by https://github.com/pandas-dev/pandas/issues/11723, so let's have the discussion there.
