### ISSUE TITLE
BUG: Pandas Dataframe is converting float variable to integer

### ISSUE THREAD

**Issue by AslanDevbrat** [pandas-dev/pandas#37000]
- [ Done ] I have checked that this issue has not already been reported.

- [ Done ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
     
    df_mle.at[words_of_bigram[0], words_of_bigram[1]] = (df_bigram.at[i,'BigramCount']/frequencies.at['Frequency',words_of_bigram[0]])


```

#### Problem description

When I assigned the answer of the division which is a decimal value ( like 0.5) then value stored in the df_mle variable is an integer (like 0).

#### Expected Output
print(df_mle.at[words_of_bigram[0], words_of_bigram[1]])
>>> 0.5

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by MarcoGorelli** [comment]
HI @AslanDevbrat - thanks for the report, could you please provide a reproducible example? See https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports how to write minimal bug reports

**Comment by AslanDevbrat** [comment]
Hey, actually the problem lies in the initialization step.
I have initialized like `df_mle = pd.DataFrame (0, columns = [*vocabluray_dict],index=[*vocabluray_dict])`

Then I changed 0 to 0.0 like this `df_mle = pd.DataFrame (0.0, columns = [*vocabluray_dict],index=[*vocabluray_dict])`
and this resolved my issue.
