### ISSUE TITLE
ENH: allow NaN value in str.place

### ISSUE THREAD

**Issue by GYHHAHA** [pandas-dev/pandas#37020]
```python
>>>pd.Series(['A',pd.NA],dtype='string').str.replace(pd.NA,0)
TypeError: repl must be a string or callable
>>>pd.Series(['A',pd.NA],dtype='string').str.replace(0,pd.NA)
TypeError: repl must be a string or callable
```

Now both `str.replace(pd.NA,0)` and `str.replace(0,pd.NA)` raise.

I think it will be better to allow these replacements since `replace` method can handle this.

**Comment by erfannariman** [comment]
Why would we not just use `fillna` here?

**Comment by GYHHAHA** [comment]
Yes, `str.replace(pd.NA,0)` can be replaced by `fillna`.

Only need to consider `str.replace(0,pd.NA)`, thanks.

**Comment by dsaxton** [comment]
Replacing with NA can be done using mask (or where):
```python
[ins] In [6]: s
Out[6]: 
0    1
1    2
2    3
dtype: Int64

[ins] In [7]: s.mask(s == 1)
Out[7]: 
0    <NA>
1       2
2       3
dtype: Int64
```

**Comment by GYHHAHA** [comment]
Good, thanks!

Close.
