### ISSUE TITLE
CLN: unify numpy.random-related imports

### ISSUE THREAD

**Issue by onshek** [pandas-dev/pandas#37053]
#### Location of the imports
https://github.com/pandas-dev/pandas/blob/8a25b23dd69d1e24840337797e1d20184920b5f3/pandas/tests/plotting/test_hist_method.py#L3-L4

#### Imports problem
~~All numpy-related imports are only about `numpy.random` including `randint`, `choice`, `normal`, etc~~
Part of numpy.random-related imports use aliases

#### Suggested fix for imports
eg: ~~`import numpy as np ` && `np.ranom.randn` --> `from numpy.random import randn`~~
`from numpy.random import randn` --> `import numpy as np ` && `np.ranom.randn`

**Comment by jreback** [comment]
yeah this would be fine to change
but if we do then pls implement a code_check to enforce this

**Comment by onshek** [comment]
> yeah this would be fine to change
> but if we do then pls implement a code_check to enforce this

Do you mean adding a new code_check to check the whole package instead of the single file?

**Comment by jreback** [comment]
yes see code_check.sh

**Comment by onshek** [comment]
take

**Comment by mroeschke** [comment]
My 2 cents; I would actually prefer to standardize in the other direction.

i.e. use `np.random.choice()` directly instead of `from np.random import choice; choice()`

**Comment by jreback** [comment]
sorry i think i misread the top

we always want fully qualified things eg

np.random.randn

no aliases for these

**Comment by onshek** [comment]
Um...it seems I did the opposite. will be corrected later.
