### ISSUE TITLE
ENH: MultiIndex.dtypes

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#37062]
create a mi
```
In [13]: mi = pd.MultiIndex.from_product([[1,2,3], list('abc'), pd.date_range('20200101', periods=2, tz='UTC')], names=['int', 'string', 'dt'])                            
```

You can already get .dtypes, but is slightly cumbersome. I would propose adding `Multidex.dtypes` (we *already* have MultiIndex.dtype but its *always* object). I think this is worth the convenience api.
```
In [14]: mi.to_frame().dtypes                                                                                                                                              
Out[14]: 
int                     int64
string                 object
dt        datetime64[ns, UTC]
dtype: object

# we would actually implement like this.
In [15]: pd.Series({l.name: l.dtype for l in mi.levels})                                                                                                                   
Out[15]: 
int                     int64
string                 object
dt        datetime64[ns, UTC]
dtype: object
```

**Comment by abdurrehman11** [comment]
Hi, @jreback I could give a try to implement MultiIndex.dtypes, if that's okay ?

**Comment by jreback** [comment]
there is already a PR out for this

**Comment by abdurrehman11** [comment]
I filtered the issues with no-assignee and this also came under that tag. I am a newbie here so anyone can guide how I can find the issues that need to be resolved yet.

**Comment by Aloqeely** [comment]
> (we _already_ have MultiIndex.dtype but its _always_ object)

May I ask why is that the case? Why does it not go for the "smallest" dtype that covers all the dtypes in the multiindex, so if it has dtypes: `int`, `float` then `mi.dtype` returns `float`?

If there's no specific reason then I'll open an enhancement request
