### ISSUE TITLE
CI/TST: xfail in `test_parquet` has passed

### ISSUE THREAD

**Issue by fangchenli** [pandas-dev/pandas#37067]
The xfail test `test_s3_roundtrip_for_dir` in `io/test_parquet` has passed on my machine. But I don't see it on our CI.

<details>

INSTALLED VERSIONS
------------------
commit           : 4d3b197c98913e894bcea9edca9ee7bad2964d84
python           : 3.8.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-48-generic
Version          : #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8
pandas           : 1.2.0.dev0+745.g4d3b197c9
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.3
setuptools       : 49.6.0.post20201009
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : 5.37.1
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.6
lxml.etree       : 4.5.2
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.18.1
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.8.3
fastparquet      : 0.4.1
gcsfs            : 0.7.1
matplotlib       : 3.3.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : 1.0.1
pytables         : None
pyxlsb           : None
s3fs             : 0.4.2
scipy            : 1.5.2
sqlalchemy       : 1.3.19
tables           : 3.6.1
tabulate         : 0.8.7
xarray           : 0.16.1
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.51.2

</details>

**Comment by dsaxton** [comment]
Hmm, this does fail for me locally on either Mac OS or Ubuntu Python3.8.

**Comment by fangchenli** [comment]
I rebuilt my environment but still see it.  Not sure why.

**Comment by nofarm3** [comment]
take

**Comment by nofarm3** [comment]
@fangchenli Is this issue still relevant? I see ```test_s3_roundtrip_for_dir``` marked with ```@td.skip_if_no("s3fs")```  and not with ```@pytest.mark.xfail```

**Comment by fangchenli** [comment]
> @fangchenli Is this issue still relevant? I see `test_s3_roundtrip_for_dir` marked with `@td.skip_if_no("s3fs")` and not with `@pytest.mark.xfail`

It's fixed by #38514. But thank you for taking a look at this!
