### ISSUE TITLE
October 2020 Developer Meeting

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#37077]
The monthly dev meeting is Wednesday October 14th, at 18:00 UTC. Our calendar is at https://pandas.pydata.org/docs/development/meeting.html#calendar to check your local time.

Video Call:  https://zoom.us/j/942410248?pwd=T2l2Qi9vaC82Z294ZEtFczYxMVM2dz09
Minutes: https://docs.google.com/document/u/1/d/1tGbTiYORHiSPgVMXawiweGJlBw5dOkVJLY-licoBmBU/edit?ouid=102771015311436394588&usp=docs_home&ths=true

**Note: the call URL is different than previous meetings. You may need to download the meeting calendar again**. Zoom changed some things w.r.t. authentication and waiting rooms.

Please add items you'd like to see discussed to the agenda. All are welcome to attend.

**Comment by erfannariman** [comment]
Just to prevent confusion, title should be "October 2020 Developer Meeting" and date should be October 14th right?

**Comment by TomAugspurger** [comment]
Yes and yes, thanks. :)
