### ISSUE TITLE
DOC: add one more column may better

### ISSUE THREAD

**Issue by HOLL4ND** [pandas-dev/pandas#37075]
#### Location of the documentation
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.cumsum.html
[this should provide the location of the documentation, e.g. "pandas.read_csv" or the URL of the documentation, e.g. "https://dev.pandas.io/docs/reference/api/pandas.read_csv.html"]

**Note**: You can check the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/).

#### Documentation problem

[this should provide a description of what documentation you believe needs to be fixed/improved]

#### Suggested fix for documentation
in the example shows how pandas.DataFrame.cumsum works, i think add one more column in the example df.cumsum(axis=1) will make thing more clear. Just like df.cumsum(axis=0),which have 3 row in the example
[this should explain the suggested fix and **why** it's better than the existing documentation]

**Comment by MarcoGorelli** [comment]
Hi @HOLL4ND - why do you think having 3 columns instead of 2 would make the example clearer?

Here's the contributing guide if you want to submit a suggestion https://pandas.pydata.org/pandas-docs/stable/development/contributing.html

**Comment by MarcoGorelli** [comment]
OK, closing then - thanks anyway for your suggestion, please let us know if you have others!
