### ISSUE TITLE
QST:AttributeError: module 'fsspec' has no attribute 'utils'

### ISSUE THREAD

**Issue by Isaac52** [pandas-dev/pandas#37084]
- [ ] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions. 

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

I'm a little confused about the error I'm getting. Any pointers will be much appreciated.
```python
# Your code here, if applicable

df.to_csv("education_salary.csv")
```

**Comment by phofl** [comment]
Hey, thanks for your report. Could you please provide a reproducible example?

**Comment by jorisvandenbossche** [comment]
There might be an old version of `fsspec` installed. @Isaac52 can you show the output of `pd.show_versions()` ?

**Comment by jorisvandenbossche** [comment]
Hmm, quickly creating an env with pandas + old fsspec doesn't reproduce it (we should actually also only importing fsspec if the provided file path is remote-like, and even then we should import fsspec with `import_optional_dependency` which checks the minimum version, which is defined as  0.7.7 for fsspec)

**Comment by lowercase00** [comment]
Same here while using boto3 to access s3 files and pandas to read parquet.
`pd.show_versions()` also leads to this error. Before that I was getting `module 'snappy' has no attribute 'compress'`
It seems that it's something related to the compression engine while using `read_parquet` maybe?

**Comment by mroeschke** [comment]
Appears more information is needed to pin down where/if different fsspec import handling is needed. Closing for now, but happy to reopen once we get more info.
