### ISSUE TITLE
PERF: regression in DataFrame reduction ops performance

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#37081]
From https://pandas.pydata.org/speed/pandas/#stat_ops.FrameOps.time_op?Cython=0.29.21&Cython=0.29.16&p-op='sum'&p-dtype='int'&p-axis=0&commits=3a043f2d-4c03d07b&x-axis-scale=date

Reproducer:

```
values = np.random.randn(100000, 4)  
df = pd.DataFrame(values).astype("int")
%timeit df.sum()
```

increased with a  factor 2 to 3 x somewhere the last days.

**Comment by ukarroum** [comment]
Would like to try working on that if possible.

**Comment by ukarroum** [comment]
take

**Comment by jbrockmendel** [comment]
#35881 is a candidate, though thats a much bigger impact than id expect

**Comment by jorisvandenbossche** [comment]
Checking out that commit vs the one before, seems to confirm that #35881 is indeed the cause of the slowdown

**Comment by jorisvandenbossche** [comment]
@ukarroum especially https://github.com/pandas-dev/pandas/pull/35881#discussion_r504035006 is something you could test

**Comment by ukarroum** [comment]
Can confirm that by using `self._iter_column_arrays()` instead of `self.dtypes` we have significant performance improvement : 

With `self.dtypes` : 

```
In [8]: values = np.random.randn(100000, 4)   
   ...: df = pd.DataFrame(values).astype("int") 
   ...: %timeit df.sum() 
714 µs ± 21 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

With `self._iter_column_arrays()` 

```
In [4]: values = np.random.randn(100000, 4)   
   ...: df = pd.DataFrame(values).astype("int") 
   ...: %timeit df.sum() 
477 µs ± 8.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

Gonna submit a PR soon.

**Comment by jorisvandenbossche** [comment]
Reopening since this dtype change only fixed part of the regression. See the updated plot at https://pandas.pydata.org/speed/pandas/#stat_ops.FrameOps.time_op?Cython=0.29.21&Cython=0.29.16&p-op='sum'&p-dtype='int'&p-axis=0&commits=3a043f2d-4c03d07b&x-axis-scale=date

**Comment by ukarroum** [comment]
Gonna do some profiling and open a PR asap.

**Comment by ukarroum** [comment]
The origin of the remaining regression is changing this condition : 

```python
if numeric_only is not None:
```

`312 µs ± 2.74 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)`

to : 

```python
if numeric_only is not None or (
            numeric_only is None
            and axis == 0
            and not any_object
            and not self._mgr.any_extension_types
        ):
```
`474 µs ± 2.29 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)`

in commit 7d257c69734113599c2eb300cfdb88636d5d034e

**Comment by ukarroum** [comment]
replacing `out = df._constructor(res).iloc[0]` with an 0(1) instruction (hardcoded serie) has almost no impact on time execution.

`df._mgr.reduce(blk_func, ignore_failures=ignore_failures)` is the line adding the 4xx microsec.

**Comment by jbrockmendel** [comment]
We don't particularly need ignore_failures in BlockManager.reduce right now, but it will be needed when we fix the many reduction bugs caused by calling `.values` further down in `DataFrame._reduce`.  If the perf impact is that big, it can be reverted in the interim i guess.

**Comment by ukarroum** [comment]
@jbrockmendel : Actually we don't need to revert the whole change, we only need to revert the following condition : 

```python
if numeric_only is not None or (
            numeric_only is None
            and axis == 0
            and not any_object
            and not self._mgr.any_extension_types
        ):
```

to : 

```python
if numeric_only is not None:
```

This will solve the regression issue

**Comment by jbrockmendel** [comment]
> Do you think i can safely do so ?

In the short term, yes, since we are not really relying on this.  The upcoming bugfixes will rely on it.  So its really a question of if we want to revert then unrevert later.
