### ISSUE TITLE
STY: avoid 1-letter variable names, especially pdb keywords

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#37123]
Every so often I use pdb and want to access a variable that happens to be a pdb keyword and its a hassle.  Let's avoid these: ["h", "w", "u", "d", "b", "s", "n", "r", "c", "j", "l", "a", "p"].  Or simpler, just avoid 1-letter variable names altogether.

**Comment by dsaxton** [comment]
I think it's pylint maybe that actually enforces this? Would it make sense to add an automated check for it (although could get annoying to try to avoid in absolutely all cases; maybe a single exception could be made for dummy index variables)?

**Comment by TomAugspurger** [comment]
Just as an FYI, if you have one of these variables, you can print them with `pp` 

```
In [1]: p = 1

In [2]: 1/0
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-2-9e1622b385b6> in <module>
----> 1 1/0

ZeroDivisionError: division by zero

In [3]: debug
> <ipython-input-2-9e1622b385b6>(1)<module>()
----> 1 1/0

ipdb> pp p
1
```

Or use `!p` to avoid the pdb command.

**Comment by jbrockmendel** [comment]
Neat, thanks

**Comment by jreback** [comment]
you can also use ```!p ....``` to escape it
