### ISSUE TITLE
ENH: Aggregation with multiple columns in one function

### ISSUE THREAD

**Issue by dingweihua** [pandas-dev/pandas#37127]
I digged into the pandas.pivot_table and pandas.DataFrame.groupby + aggregate methods, it seems that the aggfunc (or the method in aggregate) doesn't support multiple columns' computation in one function. 

Let me take an dataframe example:

```
data = {
    'Col X': ['class 1', 'class 2', 'class 3', 'class 2'],
    'Col Y': ['cat 1', 'cat 1', 'cat 2', 'cat 3'],
    'count': [1, 2, 3, 4],
    'count2': [1, 2, 3, 4]
}

df = pd.DataFrame(data=data)
```

The aggregation doesn't support directly "sum(count) + sum(count2)". What I have to do is first compute sum(count) and sum(count2), and then add the two sum results.

So do we plan to support the aggregation on multiple columns directly? Looks like:

```
df.groupby(['Col X','Col Y']).aggregate({
    'New column': lambda x: sum(x['count']) + sum(x['count2'])
}).unstack('Col Y', fill_value=0)
```
or
```
pd.pivot_table(df, values=['count', 'count2'], index=['Col X'], columns=['Col Y'],
    aggfunc=lambda x: sum(x['count']) + sum(x['count2']), fill_value=0)
```

Thanks!

**Comment by jreback** [comment]
-1 on making this even more complicated

**Comment by mroeschke** [comment]
Agreed, I think your original point of computing individual results first and then adding the results is idiomatic as pandas aims to build composable results. Thanks for the suggestion but closing
