### ISSUE TITLE
BUG:Installation problem in python 3.9

### ISSUE THREAD

**Issue by AdiHamdani** [pandas-dev/pandas#37135]
- [ v] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here

```

#### Problem description
[When installing pandas, we have these messages:

Collecting pandas
  Using cached pandas-1.1.3.tar.gz (5.2 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\adihamdani\appdata\local\programs\python\python39\python.exe' 'c:\users\adihamdani\appdata\local\programs\python\python39\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\adihamdani\AppData\Local\Temp\pip-build-env-r734sg_q\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.29.21,<3' 'numpy==1.15.4; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.15.4; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"''
       cwd: None
  Complete output (20 lines):
  Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.8" and platform_system == "AIX"' don't match your environment
  Collecting setuptools
    Using cached setuptools-50.3.1-py3-none-any.whl (785 kB)
  Collecting wheel
    Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
  Collecting Cython<3,>=0.29.21
    Using cached Cython-0.29.21-py2.py3-none-any.whl (974 kB)
  Collecting numpy==1.17.3
    Using cached numpy-1.17.3.zip (6.4 MB)
  Using legacy 'setup.py install' for numpy, since package 'wheel' is not installed.
  Installing collected packages: setuptools, wheel, Cython, numpy
      Running setup.py install for numpy: started
      Running setup.py install for numpy: still running...
      Running setup.py install for numpy: finished with status 'done'
  ERROR: Could not install packages due to an EnvironmentError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"C:'

  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\adihamdani\appdata\local\programs\python\python39\python.exe' 'c:\users\adihamdani\appdata\local\programs\python\python39\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\adihamdani\AppData\Local\Temp\pip-build-env-r734sg_q\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.29.21,<3' 'numpy==1.15.4; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.15.4; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"'' Check the logs for full command output.

C:\Users\adihamdani>pip install python==3.8.0
ERROR: Could not find a version that satisfies the requirement python==3.8.0 (from versions: none)
ERROR: No matching distribution found for python==3.8.0

]

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by fangchenli** [comment]
I'm not sure how to apply this change #37144 when using pip. 
```
pip install pandas
```
works on Linux without this change. Unfortunately I don't have a Windows machine to test this.

In the meantime, my personal recommendation is to use Python 3.8 with [Anaconda](https://www.anaconda.com/products/individual). New programmers usually find it much easier to use than pip does.

If you really need to use Python 3.9, please give us more details about how you set up the Python enviroment and install pandas. Someone might be able to tell what the problem is.

**Comment by AkiraTenchi** [comment]
I had the same issue i was able to fix it by installing the visual studio build tools which can be found here https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017
then `pip install numpy`
then `pip install pandas`

**Comment by LotusLine** [comment]
I had the same issue and was using virtualenv for my environment. I switched over to pipenv and then pandas installed like a charm. Im on MacOs Big Sur.

pip3 install pipenv
pipenv shell
pip3 install pandas

**Comment by codin-art** [comment]
@LotusLine I have the same issue but when I try to use your code, the message error : 'pipenv : command not found' appeared. Any solutions please? I have been trying to install pandas for a couples of hours with no success now...
