### ISSUE TITLE
BUG: Legend is wrong when plotting line over bar plot on same axis

### ISSUE THREAD

**Issue by Jeitan** [pandas-dev/pandas#37167]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import numpy as np
import pandas as pd

np.random.seed(123456)
d1 = ((np.random.randn(8)*3) + 200).astype(np.int)
d2 = ((np.random.randn(8)*3) - 150).astype(np.int)

df = pd.DataFrame({'Accrued': d1, 'Spent': d2})
df.loc[:, 'Net'] = df['Accrued'] + df['Spent']

# First plot step
ax = df.plot.bar(y=['Accrued', 'Spent'], stacked=True)

# Second plot step
df.plot.line(y='Net', marker='s', ms=3, color='0.3', ax=ax)
```

#### Problem description

I'm plotting a line on top of a stacked bar plot, but when I do the legend ends up incorrect - somehow the label _appends_ to the legend while the actual marker _prepends_ to the legend.  The first plot is what shows after the first plot step.  The second plot is after the second plot step.  The dark line should be associated with 'Net', but instead it's associated with 'Accrued', and the whole legend is wrong.
![barstacked](https://user-images.githubusercontent.com/9399446/96299141-6a766b00-0fa8-11eb-983a-a1e2a6ef9b72.png)
![barstackedplusline](https://user-images.githubusercontent.com/9399446/96299149-6e09f200-0fa8-11eb-9b4b-a74983e90985.png)

It may be worth noting that if I replace `.bar(` with `.line(` in the first step, the legend stays correct.  I usually run from inside PyCharm but this particular behavior is the same whether from PyCharm or directly from the command line.

#### Expected Output

I expect that the legend should a) update properly, or b) at the very least not update at all.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.14393
machine          : AMD64
processor        : Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.1.3
numpy            : 1.19.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.3
setuptools       : 50.3.0.post20201006
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : 5.37.1
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.5.2
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.18.1
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.8.3
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.1
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : 1.3.19
tables           : 3.6.1
tabulate         : None
xarray           : 0.11.3
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.51.2

</details>

**Comment by rhshadrach** [comment]
As a temporary workaround, if you switch the order of `bar` and `line`:

```
ax = df.plot.line(y='Net', marker='s', ms=3, color='0.3')
df.plot.bar(y=['Accrued', 'Spent'], stacked=True, ax=ax)
```

the correct legend is produced. A PR to fix is most certainly welcomed.

**Comment by yjheo15** [comment]
Hello, may I PR this issue?

**Comment by Jeitan** [comment]
@yjheo15 If you are using a version that does not reproduce the behavior that may be a good start to figuring out what's causing it.  All the version info is in the issue.  I don't have the bandwidth to work on it myself, but I'm sure if you can fix it it'd be well received.

**Comment by yjheo15** [comment]
Thank you for the quick response! I realized that I executed pandas release 1.1.4 instead of 1.1.3. 
I was able to reproduce the report with release 1.1.3.
To me, this implies that the new release has fixed this bug. Is it fine for me to continue probing this issue or should I search for another issue?

**Comment by rhshadrach** [comment]
@yjheo15 I am still seeing this issue on master. To be sure, the legend should have blue as "Accrued", yellow as "Spent" and the black line should be labeled "Net". Is this what you see?

**Comment by yjheo15** [comment]
@rhshadrach Yes, that is what I saw when I simply downloaded pandas with pip and ran the given code.

**Comment by Jeitan** [comment]
@yjheo15 That is interesting because I cannot get that to happen with 1.1.4 either.  Or on master....

**Comment by yjheo15** [comment]
@Jeitan Sorry for the late reply. You were right. I confused switching around the lines as @rhshadrach suggested, with switching to the previous version of pandas. I do get the same issue with 1.1.4.

**Comment by yjheo15** [comment]
@rhshadrach I apologize for the long silence. I was distracted by other material but am trying to tackle this issue again. I realized that using the temporary workaround you provided, the x-axis' value rotates as below. May I know what may be causing this?
<img width="561" alt="Screen Shot 2020-12-10 at 6 29 21 AM" src="https://user-images.githubusercontent.com/25251824/101767054-b679f380-3ab1-11eb-9811-3a826a90e9c7.png">

**Comment by rhshadrach** [comment]
@yjheo15: I'm not sure if the rotation is a bug or usual behavior; in any case, one can supply `rot=0` to get a vertical orientation.

**Comment by Bernadette-Mohr** [comment]
Since this issue is still open, I just wanted to give you a heads up: I just encountered the same behavior with pandas plotting on python 3.7 and pandas version 1.2.4. But it only happens if I plot errors (setting yerr from one df column), without the legend behavior is as expected.

**Comment by Jeitan** [comment]
Not sure what changed, but I can no longer reproduce this as of pandas 1.3.4 (python 3.8), even with the plotting with error bars that @Bernadette-Mohr mentioned.  Figured I'd close this to tidy.
