### ISSUE TITLE
TST: suppress matplotlib warnings (or determine if they represent a bug)

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#37178]
There are a bunch of these in the test logs:

```
pandas/tests/plotting/test_hist_method.py::TestDataFramePlots::test_hist_column_order_unchanged[None-expected0]
pandas/tests/plotting/test_hist_method.py::TestDataFramePlots::test_hist_column_order_unchanged[column1-expected1]
pandas/tests/plotting/test_hist_method.py::TestDataFramePlots::test_hist_with_legend[None-None]
   pandas/tests/plotting/common.py:556: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
    ret = f(**kwargs)
```

Do these represent problems we need to do something about?  cc @tacaswell 

If not, we should suppress them.  My attempts to do so with `pytestmark = pytest.mark.filterwarnings` have failed, could use another pair of eyeballs.

**Comment by tacaswell** [comment]
The warnings are from the pandas side of things: https://github.com/pandas-dev/pandas/blob/58dcafadfa50bb160afb2657a4fbda326d4802a6/pandas/plotting/_matplotlib/tools.py#L226-L231

**Comment by fangchenli** [comment]
xref #18306

**Comment by ivanovmg** [comment]
I fixed similar warnings in https://github.com/pandas-dev/pandas/pull/36982
I can look at the remaining ones of this kind.

**Comment by jbrockmendel** [comment]
@ivanovmg is this closed by #37274?

**Comment by ivanovmg** [comment]
@jbrockmendel I think the PR mentioned helps resolve the problem.
However, let me check whether there are still some tests issuing the same warning.
If so, then I will apply the same changes as was already done in the PR.

**Comment by ivanovmg** [comment]
I checked on master.
No more warnings of this kind:
```
UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
```
So, probably the issue can be closed.

**Comment by jbrockmendel** [comment]
thanks
