### ISSUE TITLE
DOC: Same description of `Returns` in `isna` and `notna`

### ISSUE THREAD

**Issue by galipremsagar** [pandas-dev/pandas#37175]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isna.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.notna.html

#### Documentation problem

There seems to be a typo in `Returns` section where both `isna` and `notna` are having this same description:

_Mask of bool values for each element in DataFrame that indicates whether an element is **not an NA value.**_

#### Suggested fix for documentation

I think `isna` doc should be corrected with:

_Mask of bool values for each element in DataFrame that indicates whether an element is **an NA value.**_

**Comment by erfannariman** [comment]
Thanks for noticing this and opening the ticket. I made a PR to fix this.
