### ISSUE TITLE
BUG:When SeriesGroupBy.apply to return DataFrame for each group, the result is incorrect

### ISSUE THREAD

**Issue by CrystalWindSnake** [pandas-dev/pandas#37187]
- [x] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
import numpy as np

df = pd.DataFrame(
{
    'name':'a a b b'.split(),
    'n1': [1,20,1,30],
})

def ap_gp(s):
    des = np.where(s>10,'over','not over')
    res = s.to_frame()
    res['des']=des
    return res

df.groupby('name')['n1'].apply(ap_gp)
```

output:
|    |   a | des      |   b |
|---:|----:|:---------|----:|
|  0 |   1 | not over | nan |
|  1 |  20 | over     | nan |
|  2 | nan | not over |   1 |
|  3 | nan | over     |  30 |

#### Expected Output
|    |   n1 | des      |
|---:|-----:|:---------|
|  0 |    1 | not over |
|  1 |   20 | over     |
|  2 |    1 | not over |
|  3 |   30 | over     |

#### Problem description
I think the reason for this error is to modify the name attribute of Series before concat

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.1
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.2.0.post20200210
Cython           : 0.29.15
pytest           : 5.3.5
hypothesis       : 5.5.4
sphinx           : 2.4.0
blosc            : None
feather          : None
xlsxwriter       : 1.2.7
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.1.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.3.5
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.13
tables           : 3.6.1
tabulate         : 0.8.7
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.7
numba            : 0.48.0
</details>

**Comment by erfannariman** [comment]
I am not sure if I agree with your expected output and if this is a bug. It actually makes sense what is returned.

To achieve what you want you can use `transform` instead:

```python
df = pd.DataFrame(
{
    'name': 'a a b b'.split(),
    'n1': [1, 20, 1, 30],
})


def ap_gp(s):
    return np.where(s > 10, 'over', 'not over')


df['des'] = df.groupby('name')['n1'].transform(ap_gp)
print(df.drop(columns='name'))
```
Output:
```
   n1       des
0   1  not over
1  20      over
2   1  not over
3  30      over
```

**Comment by rhshadrach** [comment]
Agreed with @erfannariman; when the results are DataFrames, they are concatenated vertically. One must take care to align column names when doing this. This can be done by changing the function in this case to:

```
def ap_gp(s):
    des = np.where(s>10,'over','not over')
    res = s.to_frame('n1')
    res['des']=des
    return res
```

which will produce the expected output.

**Comment by CrystalWindSnake** [comment]
> Agreed with @erfannariman; when the results are DataFrames, they are concatenated vertically. One must take care to align column names when doing this. In addition to what @erfannariman suggested, this can be done by changing the function in this case to:
> 
> ```
> def ap_gp(s):
>     des = np.where(s>10,'over','not over')
>     res = s.to_frame('n1')
>     res['des']=des
>     return res
> ```
> 
> which will produce the expected output.

My example may be not fully expressed.
When I have a function like this:
```
def get_df_from_series(col_series):
    #Other complicated operations
    return df_res

```

I expect the following two operations to return the same results：
```
df.groupby(keys).apply(lambda x: get_df_from_series(x['col'])

# and
df.groupby(keys)['col'].apply(get_df_from_series)

```
But not now

**Comment by rhshadrach** [comment]
@CrystalWindSnake can you give an example that shows the issue?

**Comment by MarcoGorelli** [comment]
closing, feel free to ping if you have a complete reproducible example as suggested above
