### ISSUE TITLE
BUG:cannot perform __truediv__ with this index type: DatetimeArray

### ISSUE THREAD

**Issue by syejing** [pandas-dev/pandas#37216]
#### Code Sample, a copy-pastable example

```python
df_price_new.pct_change()
```

#### Problem description

Index is time, column is 300 stock names, calculating the growth rate, pandas reported an error

df_price_new.info()
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 81 entries, 2019-09-02 to 2019-12-31
Columns: 300 entries, 000001.SZ to 603993.SH
dtypes: datetime64[ns](1), float64(299)
memory usage: 190.5 KB

#### Expected Output

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-de16c3a3e118> in <module>
----> 1 df_price_new.pct_change()

d:\Anaconda3\lib\site-packages\pandas\core\generic.py in pct_change(self, periods, fill_method, limit, freq, **kwargs)
  10239             data = _data
  10240 
> 10241         rs = data.div(data.shift(periods=periods, freq=freq, axis=axis, **kwargs)) - 1
  10242         if freq is not None:
  10243             # Shift method is implemented differently when freq is not None

d:\Anaconda3\lib\site-packages\pandas\core\ops\__init__.py in f(self, other, axis, level, fill_value)
    649         if isinstance(other, ABCDataFrame):
    650             # Another DataFrame
--> 651             new_data = self._combine_frame(other, na_op, fill_value)
    652 
    653         elif isinstance(other, ABCSeries):

d:\Anaconda3\lib\site-packages\pandas\core\frame.py in _combine_frame(self, other, func, fill_value)
   5864                 return func(left, right)
   5865 
-> 5866         new_data = ops.dispatch_to_series(self, other, _arith_op)
   5867         return new_data
   5868 

d:\Anaconda3\lib\site-packages\pandas\core\ops\__init__.py in dispatch_to_series(left, right, func, axis)
    273         #  _frame_arith_method_with_reindex
    274 
--> 275         bm = left._mgr.operate_blockwise(right._mgr, array_op)
    276         return type(left)(bm)
    277 

d:\Anaconda3\lib\site-packages\pandas\core\internals\managers.py in operate_blockwise(self, other, array_op)
    362         Apply array_op blockwise with another (aligned) BlockManager.
    363         """
--> 364         return operate_blockwise(self, other, array_op)
    365 
    366     def apply(self: T, f, align_keys=None, **kwargs) -> T:

d:\Anaconda3\lib\site-packages\pandas\core\internals\ops.py in operate_blockwise(left, right, array_op)
     36             lvals, rvals = _get_same_shape_values(blk, rblk, left_ea, right_ea)
     37 
---> 38             res_values = array_op(lvals, rvals)
     39             if left_ea and not right_ea and hasattr(res_values, "reshape"):
     40                 res_values = res_values.reshape(1, -1)

d:\Anaconda3\lib\site-packages\pandas\core\ops\array_ops.py in arithmetic_op(left, right, op)
    184     if should_extension_dispatch(lvalues, rvalues) or isinstance(rvalues, Timedelta):
    185         # Timedelta is included because numexpr will fail on it, see GH#31457
--> 186         res_values = op(lvalues, rvalues)
    187 
    188     else:

d:\Anaconda3\lib\site-packages\pandas\core\ops\invalid.py in invalid_op(self, other)
     51     def invalid_op(self, other=None):
     52         typ = type(self).__name__
---> 53         raise TypeError(f"cannot perform {name} with this index type: {typ}")
     54 
     55     invalid_op.__name__ = name

TypeError: cannot perform __truediv__ with this index type: DatetimeArray

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.15063
machine          : AMD64
processor        : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Simplified)_China.936

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 49.2.0.post20200714
Cython           : 0.29.21
pytest           : 5.4.3
hypothesis       : None
sphinx           : 3.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.2.9
lxml.etree       : 4.5.2
html5lib         : 1.1
pymysql          : 0.9.2
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.16.1
pandas_datareader: 0.9.0
bs4              : 4.9.1
bottleneck       : 1.3.2
fsspec           : 0.7.4
fastparquet      : None
gcsfs            : None
matplotlib       : 3.2.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.4
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.0
sqlalchemy       : 1.3.18
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.50.1

</details>

**Comment by ukarroum** [comment]
`Columns: 300 entries, 000001.SZ to 603993.SH
dtypes: datetime64ns, float64(299)`

it looks like one of your 300 columns is of type : `datetime64ns`, which makes the exception completely normal.

I would also recommand to provide a minimal working example in the future, yours is not a good one since we don't actually have a `df_price_new` dataframe

**Comment by erfannariman** [comment]
As @ukarroum it's best practice to add a [minimal bug report](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)

**Comment by syejing** [comment]
I thought it was the version of Pandas before, so I upgraded The Pandas version. As mentioned, there may be a problem with the type of column, so I will have no problem if I keep the column within 5 columns
