### ISSUE TITLE
QST: Rolling mean triggers exception : Cannot cast array data from dtype('float64') to dtype('int32') [Works on macOS (64 bits?) not on Linux 32 bits])

### ISSUE THREAD

**Issue by aamalikcmu** [pandas-dev/pandas#37244]
- [ Check] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ Check] I have asked my usage related question on [StackOverflow](https://stackoverflow.com/questions/64373351/pandas-rolling-window-cannot-cast-array-data-from-dtypeint64-to-dtypeint).

---

#### Question about pandas

I am trying to calculate the average of a rolling window [of x number of seconds, in this case 300] using Panda's rolling window function. This works perfectly fine on my mac 
![image](https://user-images.githubusercontent.com/61522212/96454822-66d22680-11ea-11eb-936a-8fcd5db56ff6.png)

however the same code fails to work on a armv71 [32 bit system Linux 4.9.82-ti-r102  armv7l GNU/Linux]. here is a minimal reproducible example : 

```python

import pandas as pd
import times

df = pd.read_csv('example.csv', index_col=2)
df.index = pd.to_datetime(df.index)
df.index
try:
    # Interval is the step size
    interval = 300

    # input to rolling window
    window_val = str(interval) + 's'

    # Variable
    start = time.time()

    df['Variable_Average_' + str(interval)] = df \
        .groupby('Group_By_Number') \
        .rolling(window=window_val)['Variable'] \
        .mean() \
        .reset_index(drop=True) \
        .values

except:
    print(traceback.format_exc())
```

This produces the following error for me : 

```
Traceback (most recent call last):
  File "Test2.py", line 19, in <module>
    .rolling(window=window_val)['Variable'] \
  File "/home/fiq/venv/lib/python3.7/site-packages/pandas/core/window/rolling.py", line 2091, in mean
    return super().mean(*args, **kwargs)
  File "/home/fiq/venv/lib/python3.7/site-packages/pandas/core/window/rolling.py", line 1488, in mean
    return self._apply(window_func, center=self.center, name="mean", **kwargs)
  File "/home/fiq/venv/lib/python3.7/site-packages/pandas/core/window/rolling.py", line 2194, in _apply
    **kwargs,
  File "/home/fiq/venv/lib/python3.7/site-packages/pandas/core/window/rolling.py", line 588, in _apply
    result = calc(values)
  File "/home/fiq/venv/lib/python3.7/site-packages/pandas/core/window/rolling.py", line 574, in calc
    closed=self.closed,
  File "/home/fiq/venv/lib/python3.7/site-packages/pandas/core/window/indexers.py", line 301, in get_window_bounds
    index_array = self.index_array.take(indicies)
TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'

```

On the line where I call the rolling mean function.  I have tried typecasting all the data to int32 before reaching the rolling stage and i still get the same error.

The data used for this example is as follows :

![image](https://user-images.githubusercontent.com/61522212/96456056-fdebae00-11eb-11eb-9076-0543aa173558.png)

with tmstamp being its index and all other columns of type str and int32 respectively.

**Comment by ukarroum** [comment]
I would recommend (to help solve the issue) : 

1) give an example of the content of the file : example.csv (idealy small number of rows just to reproduce the error), or even better a code to reconstruct a df causing the issue.
2) put a more explicit title on the issue (for example : `Rolling mean triggers exception : Cannot cast array data from dtype('float64') to dtype('int32') [Works on macOS (64 bits?) not on Linux 32 bits]`)

**Comment by aamalikcmu** [comment]
thanks for the advice @ukarroum i have updated the title, the content of the CSV is in the screenshot of the post. i will try to write a script to generate it.

**Comment by mroeschke** [comment]
Sorry for not getting back to this issue sooner.

Could you ideally make a more minimal, reproducible example? https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

Also could you paste the output of `pd.show_versions()`? Similar issues were discovered a few months ago and should be patched now.

**Comment by mroeschke** [comment]
Going to close this issue for now, but happy to reopen if you are still getting the same errors on the latest version of pandas.

I suspect a similar issue was reported and solved by the latest version.
