### ISSUE TITLE
TST: split up test_concat.py

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#37243]
we should split this to a sub-module (concat) and then split logically (similar to merge)

https://github.com/pandas-dev/pandas/blob/master/pandas/tests/reshape/test_concat.py

**Comment by laffite56** [comment]
Hello,
i want contribute to this issue. I am not completely sure about files content, so let me know if I need to change something. I will make PR in about 30 minutes.

**Comment by laffite56** [comment]
take
