### ISSUE TITLE
QST: Does SciPy dependency license still apply / if so, for what version?

### ISSUE THREAD

**Issue by r-i-v-a** [pandas-dev/pandas#37276]
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [x] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

I noticed that a SciPy license was added to the licenses folder https://github.com/pandas-dev/pandas/blob/master/LICENSES/SCIPY_LICENSE in a commit from 2012 (doesn't mention a specific version). SciPy doesn't currently seem to get installed as a dependency via pip install. Does that dependency still apply? Asking for the purpose of attributing licenses and tracking relevance of CVEs filed on some past versions of SciPy.

**Comment by fangchenli** [comment]
I think the license still applies. We at least use code from scipy in https://github.com/pandas-dev/pandas/blob/master/doc/sphinxext/announce.py, and we kind of sync `pyproject.toml` with scipy. There are maybe more that I'm not aware of.

**Comment by r-i-v-a** [comment]
Thanks for the answer @fangchenli !
