### ISSUE TITLE
DOC: list all options for encoding and quoting in read_csv

### ISSUE THREAD

**Issue by YuriyTigiev** [pandas-dev/pandas#37272]
#### Location of the documentation

[pandas.to_csv](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html)

**Note**: You can check the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/).

#### Documentation problem
"encoding" and "quoting" described briefly. 

#### Suggested fix for documentation
Should provide all parameters which support these options.

**Comment by Meghana-12** [comment]
I'd like to work on this! Are the required details available in the latest version of the doc?

**Comment by Meghana-12** [comment]
I'd like to work on this! Could you help me out with the details to be added?

**Comment by JMBurley** [comment]
A full list of encodings would be prohibitively long IMO, but I do see value in linking to the full list of python encodings
https://docs.python.org/3/library/codecs.html#standard-encodings.

Of course, this has some drawbacks (for instance, the table I link doesn't list `latin-1` as an alias, but latin-1 is in every sane library I've ever used).

**Comment by YuriyTigiev** [comment]
> A full list of encodings would be prohibitively long IMO, but I do see value in linking to the full list of python encodings
> https://docs.python.org/3/library/codecs.html#standard-encodings.
> 
> Of course, this has some drawbacks (for instance, the table I link doesn't list `latin-1` as an alias, but latin-1 is in every sane library I've ever used).
