### ISSUE TITLE
BUG: to_offset has inconsistent behaviour for "W"

### ISSUE THREAD

**Issue by larsrinn** [pandas-dev/pandas#37273]
- [x] I have checked that this issue has not already been reported.

It might be related to https://github.com/pandas-dev/pandas/issues/34101 - I'm not sure, though

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas as pd
from pandas.tseries.frequencies import to_offset


offsets = [
    pd.offsets.YearBegin(),
    pd.offsets.YearEnd(),
    pd.offsets.YearEnd(month=5),
    pd.offsets.BYearBegin(month=3),
    pd.offsets.MonthBegin(),
    pd.offsets.MonthEnd(),
    pd.offsets.CustomBusinessMonthBegin(),
    pd.offsets.SemiMonthBegin(),
    pd.offsets.Week(),  # this is the one with the inconsistency
    pd.offsets.Week(weekday=4),
    pd.offsets.Hour(),
    pd.offsets.Hour(2),
    pd.offsets.Minute(),
    pd.offsets.Minute(15),
    pd.offsets.Hour(2) + pd.offsets.Minute(15),
]
for offset in offsets:
    freqstr = offset.freqstr
    offset_from_freqstr = to_offset(freqstr)
    if offset != offset_from_freqstr:
        print(f"Round trip not working for offset={offset}, offset.freqstr: {freqstr}, to_offset(offset.freqstr): {offset_from_freqstr}")
```

This yields:

```
Round trip not working for offset=<Week: weekday=None>, offset.freqstr: W, to_offset(offset.freqstr): <Week: weekday=6>
```

#### Problem description

I'd expect `to_offset("W")` to produce `pd.offsets.Week()`. However it yields `pd.offsets.Week(weekday=6)`. This is inconsistent with the behaviour of basically all other offsets, where passing the `freqstr` property of an offset to `to_offset` yields the offset itsself. Also for the ones with an anchor (see code example above)

For a context: I'm trying to store a time series to a database and only want to store the values, the first time and the freqeuncy. While doing that I'd like to use the `freqstr` property to serialize the frequency, a consistent round trip would be a requirement for that, though.

#### Expected Output

No output from code above

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.2.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
Version          : Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : de_DE.UTF-8
pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : None
pytest           : 6.1.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.6 (dt dec pq3 ext lo64)
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by phofl** [comment]
Hi, thanks for your report. I don't think that this qualifies as a bug. The behavior is documented in https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.tseries.offsets.Week.html#pandas.tseries.offsets.Week

**Comment by mroeschke** [comment]
Yes it appears that this behavior is documented, additionally here as well https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.tseries.frequencies.to_offset.html. Closing as the expected behavior
