### ISSUE TITLE
ENH: pivot/groupby index with nan

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#3729]
ENH: maybe for now just provide a warning if dropping the nan rows when pivotting...

rom ml

http://stackoverflow.com/questions/16860172/python-pandas-pivot-table-silently-drops-indices-with-nans

This is effectivly trying to groupby on a NaN, currently not allowed

```
In [13]: a = [['a', 'b', 12, 12, 12], ['a', nan, 12.3, 233., 12], ['b', 'a', 123.23, 123, 1], ['a', 'b', 1, 1, 1.]]

In [14]: df = DataFrame(a, columns=['a', 'b', 'c', 'd', 'e'])

In [15]: df.groupby(['a','b']).sum()
Out[15]: 
          c    d   e
a b                 
a b   13.00   13  13
b a  123.23  123   1
```

Workaround to fill the index with a dummy, pivot, and replace

```

    In [31]: df2 = df.copy()

    In [32]: df2['dummy'] = np.nan

    In [33]: df2['b'] = df2['b'].fillna('dummy')

    In [34]: df2
    Out[34]: 
       a      b       c    d   e  dummy
    0  a      b   12.00   12  12    NaN
    1  a  dummy   12.30  233  12    NaN
    2  b      a  123.23  123   1    NaN
    3  a      b    1.00    1   1    NaN

    In [35]: df2.pivot_table(rows=['a', 'b'], values=['c', 'd', 'e'], aggfunc=sum)
    Out[35]: 
       a      b       c    d   e
    0  a      b   13.00   13  13
    1  a  dummy   12.30  233  12
    2  b      a  123.23  123   1

    In [36]: df2.pivot_table(rows=['a', 'b'], values=['c', 'd', 'e'], aggfunc=sum).replace('dummy',np.nan)
    Out[36]: 
       a    b       c    d   e
    0  a    b   13.00   13  13
    1  a  NaN   12.30  233  12
    2  b    a  123.23  123   1

```

**Comment by mattvivier** [comment]
@jreback - I apologize, I'm a bit new to github, but is your last action indicating that this (adding dropna=True) should've been implemented in 0.16.0? If so, should I file another bug as I'm experiencing similar behavior in 0.16.2?

**Comment by hayd** [comment]
> modified the milestone: 0.16.0, Next Major Release on Mar 5

Github's a bit unclear, but implementing this was moved *from* 0.16.0 *to* next major release (0.17).

**Comment by mattvivier** [comment]
@hayd thanks for the clarification

**Comment by Zenadix** [comment]
+1 for adding `dropna=True` to groupby

**Comment by peterpanmj** [comment]
@hayd I am using 0.17, but it seems there is still no dropna= True option for groupby

**Comment by jreback** [comment]
this is still an open issue
pull requests to implement are welcome

**Comment by compandu** [comment]
+1 for optional dropna in groupby. The automatic drops can lead to strange behavior:

```python
In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'foo': [1, 2, 3], 'bar': [4, 5, np.nan], 'qux': [None, None, None]})

In [3]:
df

Out[3]:
bar	foo	qux
0	4	1	None
1	5	2	None
2	NaN	3	None

In [4]:
grouped = df.groupby(by=['foo', 'bar'])

In [5]:
keys = grouped.groups.keys()
keys

Out[5]:
[(3, nan), (2, 5.0), (1, 4.0)]

In [6]:
grouped.get_group(keys[0])
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-8c0d3ec7c89a> in <module>()
----> 1 grouped.get_group(keys[0])

.../env/local/lib/python2.7/site-packages/pandas/core/groupby.py in get_group(self, name, obj)
    646         inds = self._get_index(name)
    647         if not len(inds):
--> 648             raise KeyError(name)
    649 
    650         return obj.take(inds, axis=self.axis, convert=False)

KeyError: (3, nan)
```

**Comment by hmgaudecker** [comment]
+1 for the dropna option. Just got bitten by this again...

**Comment by stefanw** [comment]
+1 for the dropna option as well, got bitten by it with some `NaT` values. This is most unexpected, especially with multiple column `groupby`s. Explicitly excluding `NaN` rows before grouping seems more pythonic to me, but a backwards-compatible option with `dropna=False` would work as well.

**Comment by nbonnotte** [comment]
I'm working on a solution.

Problem: there is already a `dropna` parameter in [`DataFrame.pivot_table`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.pivot_table.html), which is used for something slightly different:

```
dropna : boolean, default True
    Do not include columns whose entries are all NaN
```

I'll gladly accept any input. The best solution would probably to just call that option with another name, both for `.groupby` and `.pivot_table`. Is there any other similar parameter somewhere in pandas whose name could be used again?

**Comment by darshanpandit** [comment]
+1 for this bug resolution. I stumbled into this and it took me a while to figure out the cause for my code\s failure. Looking forward to the next release.

**Comment by jreback** [comment]
@darshanpandit this is not fixed, nor likely for a while. PR's are welcome.

**Comment by MeetQingLiu** [comment]
+1 for this resolution

**Comment by autopotent** [comment]
+1 on this, the current behavior is not consistent with SQL (T-SQL at least) and I think that is making it tricky to realize you have an issue when grouping.

**Comment by ottothecow** [comment]
There really needs to be an option to parse the NA/missing group.

SAS and Stata both offer "missing" options when making crosstabs or summarizing by group variables, and at least for me, I use them more often than not. 

Simply saying "R does it" seems like odd logic.  Silently dropping missing categories in a groupby is dangerous.

**Comment by 77QingLiu** [comment]
+1 on this. Ability to summarise missing data is very important in data analysis.

**Comment by TomAugspurger** [comment]
The issue is still open if anyone has time to work on it.

**Comment by ShichenXie** [comment]
Actually, the na values don't removed when doing groupby in R.  Highly recommend to add the option dropna in pandas' groupby.

**Comment by tamsl** [comment]
Adding my vote on this one.

**Comment by andrewdalecramer** [comment]
I'm looking at having a go at this. We could call the option `groupna=False` instead of `dropna=True` to avoid conflicts with the pivot functions.

**Comment by andrewdalecramer** [comment]
@jreback @nbonnotte I've had a go, and you can see it [here](https://github.com/andrewdalecramer/pandas/commit/cfc6e2143b8340119a1ae8e3b6fbcfd7ac947db7). Let me know if I'm on the right track or not.

**Comment by jangorecki** [comment]
Is there any chance to have this solved for 0.24.0?

**Comment by jreback** [comment]
there is an open PR but needs a fair amount of work

happy to have a resubmitted

**Comment by andrewdalecramer** [comment]
It's not hard to solve. In fact, it's quite easy. The work is in the testing and such. I ran out of the time I had to do it at the time unfortunately.

I don't see myself getting any free time for it in the next fortnight at least, so if you want to have a go @jangorecki , you're most welcome.

**Comment by lrq3000** [comment]
Just like @stefanw, got bitten by this issue when working with a groupby on multiple columns, one including a datetime type that can be missing. I expected then to have the grouped key to have a missing datetime, but not to be missing entirely! The workaround of using a placeholder value is not obvious to implement with datetime type (what date should I use that I can be certain won't be in the dataset? What if I don't know the input dataset?). Fixing this by adding an option would be awesome!

**Comment by htuhxf** [comment]
+1 for the dropna option. Just got bitten by it.

**Comment by inderjalli** [comment]
+1 for the dropna option. Just got bitten by it.

**Comment by TrigonaMinima** [comment]
Working on this. Since this requires writing a lot of tests, it's taking time to finish the pull.

@jreback I am creating a copy of all the tests under pandas/tests/groupby to test the `dropna=False`. Is that the right way? I am 25-30% done writing tests that way.

**Comment by jreback** [comment]
> I am creating a copy of all the tests under pandas/tests/groupby to test the dropna=False. Is that the right way? I am 25-30% done writing tests that way.

please no. simply parameterize tests as needed, we already have a dropna fixture to do this

**Comment by tourdownunder** [comment]
I also got bit by this this past week. Is it possible to add a warning when ther drop na groups occurs as a stop gap? I used df.fillna('') that worked for my text cols though I understand that won't work for all dTypes.

**Comment by mgsnuno** [comment]
also faced this. I'm really used to do `value_counts(dropna=False)` and without this feature in groupby, cannot have the same results without before doing something like `fillna(-1)`

**Comment by madeleinemf** [comment]
I would also really like an option that allows dropna=False to allow a group keyed by Nan values.

**Comment by TomAugspurger** [comment]
In https://github.com/pandas-dev/pandas/issues/29716, @sorenwolfers noted that this affects `.sum(level=...)` as well

```python
import pandas as pd
import numpy as np
df = pd.DataFrame({'ind':[np.nan,np.nan,'a','a'],'col':[0,1,2,3]}).set_index('ind')
df.sum(level='ind')
```

**Comment by franz101** [comment]
Any update?
Getting this error especially with using groupie and transform

**Comment by franz101** [comment]
Any update?
Getting this error especially with using groupie and transform

**Comment by jreback** [comment]
@franz101 happy to have a PR for this
there are several attempts so lots of source material

**Comment by charlesdong1991** [comment]
take

**Comment by json2d** [comment]
a.fillna(-1)

a.groupby(['payment_type_key'], as_index=False).sum()
# a = foo_dff.groupby(['gross_amount'], as_index=False).sum()

a[a['payment_type_key'] == -1] = np.nan

**Comment by json2d** [comment]
seems really easy to get caught by this one

**Comment by OFFICE365USER** [comment]
Got bitten by this. Again. Can't believe this has been open since 2013. Consistency with R is not a reason to do something!

**Comment by StevenLi-DS** [comment]
If this is not likely be solved easily, could you guys pls consider adding a warning for the users?

Btw, I'm using `1.0.3` and set `dropna=Fasle` will make `pivot_table` extremely slow.

**Comment by andrewdalecramer** [comment]
People are aware that it's an issue. It's not a difficult issue to solve, I've done it before and it worked fine, the main impediment there is just getting the option through all the layers of indirection down to the actual work code. The reason it hasn't been solved by me is all the testing and work that goes around it, which I was unable to complete. If someone is familiar with the testing apparatus I'd be glad to talk them through my old PR (which would need to be updated as it is quite old).

On my part, I've rolled off the project using pandas a long time ago and am primarily using R now (which handles this just fine) so I don't have a strong reason to spend the days required to learn how testing works in pandas.

**Comment by jreback** [comment]
if you look at #30584 this issue is completed for groupby, wasn't hard actually. will be in 1.1 (soon).

but just like anything else in pandas, its all volunteer, if you want an issue fixed then pushing a PR is the best way.

**Comment by OFFICE365USER** [comment]
> People are aware that it's an issue. It's not a difficult issue to solve, I've done it before and it worked fine, the main impediment there is just getting the option through all the layers of indirection down to the actual work code. The reason it hasn't been solved by me is all the testing and work that goes around it, which I was unable to complete. If someone is familiar with the testing apparatus I'd be glad to talk them through my old PR (which would need to be updated as it is quite old).
> 
> On my part, I've rolled off the project using pandas a long time ago and am primarily using R now (which handles this just fine) so I don't have a strong reason to spend the days required to learn how testing works in pandas.

People are not aware of this issue. An interim solution would be groupby() to throw an error for an unsupported case with a flag to allow the broken exclude-nan "feature".

**Comment by andrewdalecramer** [comment]
Sorry, _contributers_ are aware it's an issue. You're welcome to become one and submit a PR.

**Comment by zxymath** [comment]
There are some problem when groupby category column
```
categories = ['x%s' % str(i) for i in range(2)]
d = pd.Categorical(np.random.choice(categories, size=100), categories=categories)
d[80:] = np.nan
data = pd.DataFrame(np.random.rand(len(d), 1))
print(data.groupby(d, dropna=False).count())
```

```
Out:
     0
x0  35
x1  45
```

**Comment by LaveryRM** [comment]
As a business analyst I was trained to apply two QC rules:

    never let the number of rows, or the var of interest total, change w/o knowing why.
    Check every path through nested IFs and through conditional transforms.

This was basic Business Analyst /data scientist QC and should happens on EVERY merge/filter step in a in a project. Because of the need to do this frequently, I suggest EVERY summation should default to preserving the count and the total.

An option to remove NaNs in an index is appropriate but not as the default.

**Comment by colomb8** [comment]
why is this issue closed? the problem persist on pandas 1.4.0.

**Comment by soerenwolfers** [comment]
I agree that the problem persists. In the special case of a single index level there is now the option to pass `dropna=False`. 
Sadly this newly introduced parameter is accepted, but doesn't work, for multi-indices.

**Comment by ngstahl** [comment]
Would a PR to add a warning when dropping nan values be accepted? This issue just bit me, and it would've saved me some trouble if I had gotten that warning.
