### ISSUE TITLE
CI: pin some builds to use pyarrow==1.0

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#37306]
Now that pyarrow 2.0 is released, it will get picked by the CI builds that don't pin the pyarrow version. It would be good to pin some builds to use pyarrow 1.0.

See this overview table of @simonjayhawkins at https://github.com/pandas-dev/pandas/pull/35259#issuecomment-712966527

**Comment by dsaxton** [comment]
What's the best way to figure out which ones need to be pinned? See what starts failing and then pin as needed, or is there a smarter way to do this?

**Comment by jorisvandenbossche** [comment]
I don't think it needs to be based on what is failing (because all builds should be passing right now?). Based on the table at https://github.com/pandas-dev/pandas/pull/35259#issuecomment-712966527, there are now 4 envs that have 1.0. We could for example leave 2 of them at "latest version", and pin 2 (or 1) of them to pyarrow 1.0 ?

**Comment by simonjayhawkins** [comment]
I guess we could also maybe consider adding the nightly build of PyArrow to np-dev
