### ISSUE TITLE
ENH: Add support for more units in pandas.Timedelta

### ISSUE THREAD

**Issue by rohan-gt** [pandas-dev/pandas#37301]
Currently pandas.Timedelta only support units upto weeks. Can it be extended to months, quarters, years etc.?

**Comment by jorisvandenbossche** [comment]
In pandas, Timedelta represents an exact time span. And larger units like months or years cannot be generally represented by a fixed number of seconds (or nanoseconds).

**Comment by jreback** [comment]
see #36838 for why this is going away
