### ISSUE TITLE
DOC: `to_pickle` function takes pickle v5 but doc says only 1-4 supported

### ISSUE THREAD

**Issue by ianozsvald** [pandas-dev/pandas#37316]
#### Location of the documentation

* https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_pickle.html
* https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.to_pickle.html (same as stable)

#### Documentation problem

The docstring states ` DataFrame.to_pickle(path, compression='infer', protocol=5, storage_options=None)` noting _protocol 5_ by default, the Parameters following text notes "The possible values are 0, 1, 2, 3, 4" which does not include protocol 5. 

#### Suggested fix for documentation

Add "5" to the docs: "The possible values are 0, 1, 2, 3, 4, 5" which was included from Python 3.8 https://docs.python.org/3/library/pickle.html

**Comment by jorisvandenbossche** [comment]
Thanks for the catch, indeed a good easy issue!

**Comment by botplex** [comment]
I will take this one

**Comment by botplex** [comment]
take
