### ISSUE TITLE
df.groupby(by=["b"], dropna=False).sum() returns"groupby() got an unexpected keyword argument 'dropna'"

### ISSUE THREAD

**Issue by vahanm01** [pandas-dev/pandas#37323]
Using the official documentation for groupby: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html

the dropna=False argument does not work even with given example. 

l = [[1, 2, 3], [1, None, 4], [2, 1, 3], [1, 2, 2]]
df = pd.DataFrame(l, columns=["a", "b", "c"])
df.groupby(by=["b"], dropna=False).sum()

**Comment by arw2019** [comment]
This runs on master:
``` python
In [2]: l = [[1, 2, 3], [1, None, 4], [2, 1, 3], [1, 2, 2]] 
   ...: df = pd.DataFrame(l, columns=["a", "b", "c"]) 
   ...: df.groupby(by=["b"], dropna=False).sum()                                                                                                                                                                   
Out[2]: 
     a  c
b        
1.0  2  3
2.0  2  5
NaN  1  4
```
It was fixed in #35078

**Comment by rhshadrach** [comment]
Thanks for reporting this, the fix will be available when 1.2 is released.

**Comment by janalysis** [comment]
Any workarounds while I wait for 1.2?

**Comment by arw2019** [comment]
in case that helps 1.2 is out within a few weeks (and actually the release candidate is out already if you feel like trying it out)

**Comment by rhshadrach** [comment]
For a workaround, can replace nan with a value that doesn't exist in the frame, do the groupby, and then refill will nan.

**Comment by pramodh941** [comment]
The issue still persists. 
"TypeError: group() got an unexpected keyword argument 'dropna'"
