### ISSUE TITLE
CLN make namespace usage in tests consistent

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#37334]
Currently, there are many test files where we use the pandas namespace inconsistently: for example, we do
```
import pandas as pd
from pandas import DataFrame
```
and then one test function uses `pd.DataFrame`, the other `DataFrame`.

The goal here is to be consistent: each file should either just contain pd.DataFrame, or DataFrame. Same goes for, e.g. `to_timedelta`, `Series`, ...

Here are the files which have such inconsistencies. If you'd like to work on this, please choose 10-15 files at a time.

**There is no need to ask for permission to work on this.** Just open a pull request, and link to this issue: write `xref #` in the pull request description. I'll do my best to keep the checklist up-to-date.

List of files which may need changing (along with an example of an offending line):

- [ ] pandas/tests/api/test_api.py:238:        assert datetime(2015, 1, 2, 0, 0) == pd.datetime(2015, 1, 2, 0, 0)
- [ ] pandas/tests/arithmetic/conftest.py:85:    Float64Index([nan, inf, inf, inf, inf], dtype='float64')
- [ ] pandas/tests/arithmetic/test_datetime64.py:54:        dti = date_range("20130101", periods=3, tz=tz)
- [ ] pandas/tests/arithmetic/test_interval.py:53:def array(left_right_dtypes):
- [ ] pandas/tests/arithmetic/test_numeric.py:138:        expected = pd.TimedeltaIndex(["10s", "40s", "90s"])
- [ ] pandas/tests/arithmetic/test_object.py:132:            [Timestamp("2011-01-01"), Timestamp("2011-01-02"), pd.NaT],
- [ ] pandas/tests/arithmetic/test_period.py:35:        pi = pd.period_range("2000", periods=4)
- [ ] pandas/tests/arithmetic/test_timedelta64.py:57:        tdi = pd.timedelta_range("2H", periods=4)
- [ ] pandas/tests/arrays/boolean/test_arithmetic.py:12:    return pd.array(
- [ ] pandas/tests/arrays/boolean/test_astype.py:10:    arr = pd.array([True, False, None], dtype="boolean")
- [ ] pandas/tests/arrays/boolean/test_comparison.py:12:    return pd.array(
- [ ] pandas/tests/arrays/boolean/test_construction.py:11:    values = np.array([True, False, True, False], dtype="bool")
- [ ] pandas/tests/arrays/boolean/test_function.py:13:    a = pd.array([True, False, None], dtype="boolean")
- [ ] pandas/tests/arrays/boolean/test_logical.py:14:        a = pd.array([True, False, None], dtype="boolean")
- [ ] pandas/tests/arrays/categorical/test_constructors.py:35:        ordered = np.array([0, 1, 2])
- [ ] pandas/tests/arrays/categorical/test_indexing.py:37:        expected = Categorical(["c", "b", "b", "a", "a", "c", "c", "c"], ordered=True)
- [ ] pandas/tests/arrays/categorical/test_missing.py:24:        tm.assert_numpy_array_equal(isna(cat), labels == -1)
- [ ] pandas/tests/arrays/categorical/test_operators.py:15:        factor = Categorical(["a", "b", "b", "a", "a", "c", "c", "c"], ordered=True)
- [ ] pandas/tests/arrays/floating/test_arithmetic.py:27:    a = pd.array([1.0, 2.0, None, 4.0, 5.0], dtype=dtype)
- [ ] pandas/tests/arrays/floating/test_astype.py:10:    arr = pd.array([0.1, 0.2, None], dtype="Float64")
- [ ] pandas/tests/arrays/floating/test_construction.py:11:    a = pd.array([1, None], dtype=pd.Float64Dtype())
- [ ] pandas/tests/arrays/floating/test_function.py:12:    a = pd.array([1, 2, -3, np.nan], dtype="Float64")
- [ ] pandas/tests/arrays/floating/test_to_numpy.py:16:    expected = np.array([0.1, 0.2, 0.3], dtype="object")
- [ ] pandas/tests/arrays/integer/test_arithmetic.py:21:    a = pd.array([0, 1, None, 3, 4], dtype=dtype)
- [ ] pandas/tests/arrays/integer/test_construction.py:12:    a = pd.array([1, None], dtype=pd.Int64Dtype())
- [ ] pandas/tests/arrays/integer/test_dtypes.py:46:        {"B": np.array([1.0, 3.0]), "C": integer_array([1, 3], dtype="Int64")},
- [ ] pandas/tests/arrays/integer/test_function.py:48:    arr = np.array([1, 2, 3, 4])
- [ ] pandas/tests/arrays/interval/test_interval.py:25:        (date_range("20170101", periods=3), date_range("20170102", periods=3)),
- [ ] pandas/tests/arrays/masked/test_arithmetic.py:11:arrays = [pd.array([1, 2, 3, None], dtype=dtype) for dtype in tm.ALL_EA_INT_DTYPES]
- [ ] pandas/tests/arrays/masked/test_arrow_compat.py:8:arrays = [pd.array([1, 2, 3, None], dtype=dtype) for dtype in tm.ALL_EA_INT_DTYPES]
- [ ] pandas/tests/arrays/sparse/test_array.py:19:        self.arr_data = np.array([np.nan, np.nan, 1, 2, 3, np.nan, 4, 5, np.nan, 6])
- [ ] pandas/tests/arrays/sparse/test_dtype.py:22:    sparse_dtype = SparseDtype(dtype)
- [ ] pandas/tests/arrays/string_/test_string.py:13:    df = pd.DataFrame({"A": pd.array(["a", pd.NA, "b"], dtype="string")})
- [ ] pandas/tests/arrays/test_array.py:33:        ([1, 2], object, PandasArray(np.array([1, 2], dtype=object))),
- [ ] pandas/tests/arrays/test_datetimelike.py:677:            arr.take([-1, 1], allow_fill=True, fill_value=pd.Period("2014Q1"))
- [ ] pandas/tests/arrays/test_datetimes.py:24:        arr = np.array([0, 1, 2, 3], dtype="M8[h]").astype("M8[ns]")
- [ ] pandas/tests/base/test_conversion.py:126:        i = CategoricalIndex([Timestamp("1999-12-31"), Timestamp("2000-12-31")])
- [ ] pandas/tests/base/test_misc.py:112:    assert Index([1]).item() == 1
- [ ] pandas/tests/base/test_value_counts.py:36:        expected.index = pd.Index(expected.index)
- [ ] pandas/tests/computation/test_eval.py:191:            result = pd.eval(ex, engine=self.engine, parser=self.parser)
- [ ] pandas/tests/dtypes/test_common.py:170:    assert com.is_object_dtype(np.array([], dtype=object))
- [ ] pandas/tests/dtypes/test_dtypes.py:313:        dr = date_range("20130101", periods=3, tz="US/Eastern")
- [ ] pandas/tests/dtypes/test_inference.py:83:    (Index([1]), True, "Index"),
- [ ] pandas/tests/dtypes/test_missing.py:67:        assert isna(np.array(np.nan))
- [ ] pandas/tests/extension/arrow/arrays.py:119:            pa.chunked_array([pa.array(result, mask=pd.isna(self._data.to_pandas()))])
- [ ] pandas/tests/extension/base/getitem.py:134:        expected = data[np.array([], dtype="int64")]
- [ ] pandas/tests/extension/base/methods.py:33:        data = data[:10].unique()
- [ ] pandas/tests/extension/base/missing.py:13:        result = pd.isna(data_missing)
- [ ] pandas/tests/extension/base/setitem.py:47:        data[np.array([], dtype=int)] = []
- [ ] pandas/tests/extension/decimal/test_decimal.py:72:            # need to convert array([Decimal(NaN)], dtype='object') to np.NaN
- [ ] pandas/tests/extension/list/array.py:44:            if not isinstance(val, self.dtype.type) and not pd.isna(val):
- [ ] pandas/tests/extension/test_boolean.py:36:    return pd.array(make_data(), dtype=dtype)
- [ ] pandas/tests/extension/test_categorical.py:51:    return Categorical(make_data())
- [ ] pandas/tests/extension/test_floating.py:44:    return pd.array(make_data(), dtype=dtype)
- [ ] pandas/tests/extension/test_numpy.py:48:        return PandasArray(np.array([np.nan, (1,)], dtype=object))
- [ ] pandas/tests/extension/test_sparse.py:29:    return SparseDtype()
- [ ] pandas/tests/frame/apply/test_frame_apply.py:67:                "A": date_range("20130101", periods=3),
- [ ] pandas/tests/frame/indexing/test_categorical.py:17:        labels = Categorical([f"{i} - {i + 499}" for i in range(0, 10000, 500)])
- [ ] pandas/tests/frame/indexing/test_indexing.py:65:        msg = "\"None of [Index(['baf'], dtype='object')] are in the [columns]\""
- [ ] pandas/tests/frame/indexing/test_sparse.py:50:        expected = np.full(cols, SparseDtype(dtype, fill_value=0))
- [ ] pandas/tests/frame/indexing/test_xs.py:59:        # no columns but Index(dtype=object)
- [ ] pandas/tests/frame/methods/test_align.py:89:        tm.assert_index_equal(bf.index, Index([]))
- [ ] pandas/tests/frame/methods/test_append.py:132:        df1 = DataFrame({"bar": Timestamp("20130101")}, index=range(5))
- [ ] pandas/tests/frame/methods/test_cov_corr.py:73:        "other_column", [pd.array([1, 2, 3]), np.array([1.0, 2.0, 3.0])]
- [ ] pandas/tests/frame/methods/test_describe.py:249:        start = Timestamp(2018, 1, 1)
- [ ] pandas/tests/frame/methods/test_diff.py:78:        dti = pd.date_range("2016-01-01", periods=4, tz=tz)
- [ ] pandas/tests/frame/methods/test_drop.py:90:        expected = Index(["a", "b", "c"], name="first")
- [ ] pandas/tests/frame/methods/test_quantile.py:247:            [Timestamp("2010-07-02 12:00:00"), 2.5], index=["a", "b"], name=0.5
- [ ] pandas/tests/frame/methods/test_replace.py:964:                Timestamp("20130102", tz="US/Eastern"),
- [ ] pandas/tests/frame/methods/test_reset_index.py:42:        expected["idx"] = expected["idx"].apply(lambda d: Timestamp(d, tz=tz))
- [ ] pandas/tests/frame/methods/test_sort_values.py:243:        df = DataFrame({"x": pd.Categorical(np.repeat([1, 2, 3, 4], 5), ordered=True)})
- [ ] pandas/tests/frame/test_analytics.py:68:        df = DataFrame({"b": date_range("1/1/2001", periods=2)})
- [ ] pandas/tests/frame/test_constructors.py:94:            ([[]], RangeIndex(1), RangeIndex(0)),
- [ ] pandas/tests/frame/test_dtypes.py:62:                "A": date_range("20130101", periods=3),
- [ ] pandas/tests/frame/test_query_eval.py:46:        result = df.eval("A+1")
- [ ] pandas/tests/frame/test_reshape.py:64:        tm.assert_index_equal(result.columns, Index(["A", "B"], name=0))
- [ ] pandas/tests/frame/test_to_csv.py:40:    def read_csv(self, path, **kwargs):
- [ ] pandas/tests/generic/test_finalize.py:35:        (np.array([0], dtype="float64")),
- [ ] pandas/tests/generic/test_generic.py:792:        df1["start"] = date_range("2000-1-1", periods=10, freq="T")
- [ ] pandas/tests/generic/test_series.py:65:        o = Series(date_range("20130101", periods=3))
- [ ] pandas/tests/groupby/aggregate/test_aggregate.py:135:    exp = Series([], dtype=np.float64, index=pd.Index([], dtype=np.float64))
- [ ] pandas/tests/groupby/aggregate/test_other.py:109:            "time": date_range("1/1/2011", periods=8, freq="H"),
- [ ] pandas/tests/groupby/test_apply.py:43:    exp_idx = pd.Index(
- [ ] pandas/tests/groupby/test_categorical.py:88:    cats = Categorical(
- [ ] pandas/tests/groupby/test_counting.py:240:            index=Index([0.0, 3.0, 4.0, 5.0], name="B"), data={"A": [1, 1, 1, 1]}
- [ ] pandas/tests/groupby/test_function.py:66:    exp_df = DataFrame([exp] * 2, columns=["val"], index=Index(["a", "b"], name="key"))
- [ ] pandas/tests/groupby/test_groupby.py:19:    result = repr(pd.Grouper(key="A", level="B"))
- [ ] pandas/tests/groupby/test_grouping.py:159:        dates = date_range(d0, date.today())
- [ ] pandas/tests/groupby/test_missing.py:14:        columns=pd.Index(["type", "a", "b"], name="idx"),
- [ ] pandas/tests/groupby/test_nth.py:14:    expected.index = Index(["bar", "foo"], name="A")
- [ ] pandas/tests/groupby/test_pipe.py:35:    index = Index(["bar", "foo"], dtype="object", name="A")
- [ ] pandas/tests/groupby/test_quantile.py:48:        [a_expected, b_expected], columns=["val"], index=Index(["a", "b"], name="key")
- [ ] pandas/tests/groupby/test_timegrouper.py:54:                index=date_range(
- [ ] pandas/tests/groupby/transform/test_transform.py:103:            "d": pd.date_range("2014-1-1", "2014-1-4"),
- [ ] pandas/tests/indexes/base_class/test_reshape.py:14:        index = pd.Index([1, 2, 3])
- [ ] pandas/tests/indexes/base_class/test_setops.py:15:        idx1 = pd.Index(["a", "b"])
- [ ] pandas/tests/indexes/categorical/test_category.py:24:        return CategoricalIndex(list("aabbca"), categories=categories, ordered=ordered)
- [ ] pandas/tests/indexes/categorical/test_formats.py:12:        idx = pd.CategoricalIndex(["a", "bb", "ccc"])
- [ ] pandas/tests/indexes/categorical/test_indexing.py:14:        idx = pd.CategoricalIndex([1, 2, 3], name="xxx")
- [ ] pandas/tests/indexes/categorical/test_map.py:20:        index = CategoricalIndex(data, categories=categories, ordered=ordered)
- [ ] pandas/tests/indexes/common.py:96:            result = pd.Index(expected)
- [ ] pandas/tests/indexes/datetimes/test_astype.py:24:        idx = DatetimeIndex(["2016-05-16", "NaT", NaT, np.NaN], name="idx")
- [ ] pandas/tests/indexes/datetimes/test_constructors.py:30:            dt_cls([pd.NaT, pd.Timestamp("2011-01-01")], freq="D")
- [ ] pandas/tests/indexes/datetimes/test_date_range.py:32:        rng = date_range("20090415", "20090519", tz="US/Eastern")
- [ ] pandas/tests/indexes/datetimes/test_datetime.py:17:        index = date_range("20130101", periods=3, tz="US/Eastern")
- [ ] pandas/tests/indexes/datetimes/test_indexing.py:20:        idx = pd.date_range(
- [ ] pandas/tests/indexes/datetimes/test_misc.py:17:        idx = pd.date_range(
- [ ] pandas/tests/indexes/datetimes/test_ops.py:44:        rng = date_range("1/1/2000", "1/1/2001")
- [ ] pandas/tests/indexes/datetimes/test_setops.py:57:        rng1 = pd.date_range("1/1/2000", freq="D", periods=5, tz=tz)
- [ ] pandas/tests/indexes/datetimes/test_shift.py:23:        idx = pd.DatetimeIndex([], name="xxx", tz=tz)
- [ ] pandas/tests/indexes/datetimes/test_timezones.py:55:        idx = DatetimeIndex(dates)
- [ ] pandas/tests/indexes/interval/test_interval.py:57:        ivs = [Interval(l, r, closed) for l, r in zip(range(10), range(1, 11))]
- [ ] pandas/tests/indexes/multi/test_analytics.py:35:    major_axis = Index(list(range(4)))
- [ ] pandas/tests/indexes/multi/test_constructors.py:21:    expected = Index(["foo", "bar", "baz", "qux"], name="first")
- [ ] pandas/tests/indexes/multi/test_get_level_values.py:22:    expected = Index(["foo", "foo", "bar", "baz", "qux", "qux"], name="first")
- [ ] pandas/tests/indexes/multi/test_get_set.py:289:    expected = pd.MultiIndex(levels=[[0, 1]], codes=[[0, 1]], names=["first"])
- [ ] pandas/tests/indexes/multi/test_indexing.py:67:        index = MultiIndex(
- [ ] pandas/tests/indexes/multi/test_integrity.py:161:    # isna(MI)
- [ ] pandas/tests/indexes/multi/test_join.py:10:    "other", [Index(["three", "one", "two"]), Index(["one"]), Index(["one", "three"])]
- [ ] pandas/tests/indexes/multi/test_missing.py:42:    idx = MultiIndex(
- [ ] pandas/tests/indexes/multi/test_monotonic.py:37:    i = MultiIndex(
- [ ] pandas/tests/indexes/multi/test_sorting.py:178:    mi = MultiIndex(
- [ ] pandas/tests/indexes/period/test_formats.py:117:        exp1 = """Series([], dtype: period[D])"""
- [ ] pandas/tests/indexes/period/test_indexing.py:28:        idx = period_range("2011-01-01", "2011-01-31", freq="D", name="idx")
- [ ] pandas/tests/indexes/period/test_ops.py:32:        idx = PeriodIndex(np.repeat(idx._values, range(1, len(idx) + 1)), freq="H")
- [ ] pandas/tests/indexes/ranges/test_indexing.py:11:        index = RangeIndex(start=0, stop=20, step=2)
- [ ] pandas/tests/indexes/ranges/test_range.py:108:        expected = pd.Index([0, pd.NaT, 1, 2, 3, 4], dtype=object)
- [ ] pandas/tests/indexes/test_base.py:50:        return Index(list("abcde"))
- [ ] pandas/tests/indexes/test_numeric.py:42:        expected = Float64Index(arr)
- [ ] pandas/tests/indexes/timedeltas/test_astype.py:21:        idx = timedelta_range(start="1 days", periods=4, freq="D", name="idx")
- [ ] pandas/tests/indexes/timedeltas/test_constructors.py:17:            TimedeltaIndex([1, 3, 7], unit)
- [ ] pandas/tests/indexes/timedeltas/test_formats.py:46:        exp1 = """Series([], dtype: timedelta64[ns])"""
- [ ] pandas/tests/indexes/timedeltas/test_indexing.py:15:        idx = timedelta_range("1 day", "31 day", freq="D", name="idx")
- [ ] pandas/tests/indexes/timedeltas/test_ops.py:16:        idx = timedelta_range("1 days 09:00:00", freq="H", periods=10)
- [ ] pandas/tests/indexes/timedeltas/test_scalar_compat.py:19:        rng = timedelta_range("1 days, 10:11:12.100123456", periods=2, freq="s")
- [ ] pandas/tests/indexes/timedeltas/test_setops.py:14:        i1 = timedelta_range("1day", periods=5)
- [ ] pandas/tests/indexes/timedeltas/test_shift.py:17:        idx = pd.TimedeltaIndex([], name="xxx")
- [ ] pandas/tests/indexing/multiindex/test_multiindex.py:63:                Index(["R1", "R2", np.nan, "R4"], name="a"),
- [ ] pandas/tests/indexing/test_categorical.py:101:        exp = np.array([4, 3, 2, 1], dtype=np.int64)
- [ ] pandas/tests/indexing/test_check_indexer.py:13:        ([1, 2], np.array([1, 2], dtype=np.intp)),
- [ ] pandas/tests/indexing/test_datetime.py:18:        idx = date_range("20010101", periods=4, tz="UTC")
- [ ] pandas/tests/indexing/test_iloc.py:238:        df = concat([df1, df2], axis=1)
- [ ] pandas/tests/indexing/test_indexing.py:39:            df.loc[df.index[2:5], "bar"] = np.array([2.33j, 1.23 + 0.1j, 2.2, 1.0])
- [ ] pandas/tests/indexing/test_loc.py:332:        expected = df.loc[np.array(mask)]
- [ ] pandas/tests/internals/test_internals.py:108:        values = Categorical([1, 1, 2, 2, 3, 3, 3, 3, 4, 4])
- [ ] pandas/tests/io/excel/test_readers.py:842:        si = Index(
- [ ] pandas/tests/io/excel/test_xlrd.py:30:        with ExcelFile(book, engine=engine) as xl:
- [ ] pandas/tests/io/formats/test_format.py:185:        with option_context(
- [ ] pandas/tests/io/formats/test_printing.py:112:        with cf.option_context("display.unicode.ambiguous_as_wide", True):
- [ ] pandas/tests/io/formats/test_to_html.py:197:    with option_context("display.multi_sparse", multi_sparse):
- [ ] pandas/tests/io/json/test_pandas.py:72:        result = read_json(df.to_json(orient=orient), orient=orient)
- [ ] pandas/tests/io/json/test_readlines.py:21:    result = read_json('{"a": 1, "b": 2}\n{"b":2, "a" :1}\n', lines=True)
- [ ] pandas/tests/io/parser/test_c_parser_only.py:35:        parser.read_csv(StringIO(malformed))
- [ ] pandas/tests/io/parser/test_parse_dates.py:448:                Timestamp("05/31/2012, 15:30:00.029"),
- [ ] pandas/tests/io/parser/test_read_fwf.py:30:    result = read_fwf(StringIO(data))
- [ ] pandas/tests/io/pytables/test_store.py:69:            with HDFStore(path) as store:
- [ ] pandas/tests/io/pytables/test_timezones.py:47:                    Timestamp("20130102 2:00:00", tz=gettz("US/Eastern"))
- [ ] pandas/tests/io/test_clipboard.py:152:        result = read_clipboard(sep=sep or "\t", index_col=0, encoding=encoding)
- [ ] pandas/tests/io/test_feather.py:40:            result = read_feather(path, **read_kwargs)
- [ ] pandas/tests/io/test_parquet.py:191:                actual = read_parquet(path, **read_kwargs)
- [ ] pandas/tests/io/test_sql.py:607:        iris_frame = sql.read_sql_query("SELECT * FROM iris", self.conn)
- [ ] pandas/tests/io/test_stata.py:52:    parsed_114 = read_stata(dta14_114, convert_dates=True)
- [ ] pandas/tests/plotting/test_frame.py:508:        idx = date_range(start="2014-07-01", freq="M", periods=10)
- [ ] pandas/tests/reductions/test_reductions.py:58:            expected = pd.Period(ordinal=getattr(obj.asi8, opname)(), freq=obj.freq)
- [ ] pandas/tests/resample/test_datetime_index.py:44:    b = Grouper(freq=Minute(5))
- [ ] pandas/tests/resample/test_deprecated.py:43:    idx = pd.date_range("2001-01-01", periods=4, freq="T")
- [ ] pandas/tests/resample/test_period_index.py:45:            new_index = date_range(start=start, end=end, freq=freq, closed="left")
- [ ] pandas/tests/resample/test_resample_api.py:11:dti = date_range(start=datetime(2005, 1, 1), end=datetime(2005, 1, 10), freq="Min")
- [ ] pandas/tests/resample/test_resampler_grouper.py:16:    index=date_range("1/1/2000", freq="s", periods=40),
- [ ] pandas/tests/resample/test_time_grouper.py:13:test_series = Series(np.random.randn(1000), index=date_range("1/1/2000", periods=1000))
- [ ] pandas/tests/resample/test_timedelta.py:17:        index=timedelta_range("0 day", periods=4, freq="1T"),
- [ ] pandas/tests/reshape/merge/test_join.py:412:        ex_index = Index(index1.values).union(Index(index2.values))
- [ ] pandas/tests/reshape/merge/test_merge.py:127:        result = pd.merge(df_empty, df_a, left_index=True, right_index=True)
- [ ] pandas/tests/reshape/merge/test_merge_asof.py:21:        x.time = to_datetime(x.time)
- [ ] pandas/tests/reshape/merge/test_multi.py:110:        expected = pd.merge(left, right.reset_index(), on=on_cols, how=join_type)
- [ ] pandas/tests/reshape/test_concat.py:50:            pd.Timestamp("2011-01-01"),
- [ ] pandas/tests/reshape/test_cut.py:29:    result = cut(data, 4, labels=False)
- [ ] pandas/tests/reshape/test_melt.py:29:        result = melt(self.df)
- [ ] pandas/tests/reshape/test_pivot.py:31:    return Categorical(pd.IntervalIndex.from_arrays(left, right, closed))
- [ ] pandas/tests/reshape/test_qcut.py:127:    exp_levels = np.array(
- [ ] pandas/tests/reshape/test_union_categoricals.py:42:                result = union_categoricals([box(Categorical(a)), box(Categorical(b))])
- [ ] pandas/tests/scalar/period/test_period.py:22:        i1 = Period("1/1/2005", freq="M")
- [ ] pandas/tests/scalar/test_na_scalar.py:102:        value = np.array([value])
- [ ] pandas/tests/scalar/timedelta/test_arithmetic.py:29:            Timedelta(10, unit="s"),
- [ ] pandas/tests/scalar/timestamp/test_unary_ops.py:327:        # datetime.timestamp() converts in the local timezone
- [ ] pandas/tests/series/apply/test_series_apply.py:28:        s = Series(dtype=object, name="foo", index=pd.Index([], name="bar"))
- [ ] pandas/tests/series/indexing/test_datetime.py:29:    assert s[Timestamp(datetime(2009, 1, 2))] == 48
- [ ] pandas/tests/series/indexing/test_indexing.py:73:        pd.date_range("2011-01-01", periods=3, tz="US/Eastern"), index=["a", "b", "c"]
- [ ] pandas/tests/series/indexing/test_where.py:182:        [Timestamp("2017-01-01"), pd.NaT, Timestamp("2017-01-02")],
- [ ] pandas/tests/series/methods/test_interpolate.py:552:            [1, np.nan, 3], index=date_range("1/1/2000", periods=3, tz=tz_naive_fixture)
- [ ] pandas/tests/series/methods/test_quantile.py:28:        assert q == Timestamp("2000-01-10 19:12:00")
- [ ] pandas/tests/series/methods/test_shift.py:76:        index = date_range("2000-01-01", periods=5)
- [ ] pandas/tests/series/methods/test_truncate.py:76:        rng = pd.date_range("2011-01-01", "2012-01-01", freq="W")
- [ ] pandas/tests/series/methods/test_value_counts.py:88:        values = pd.Categorical([1, 2, 3, 1, 1, 3], ordered=True)
- [ ] pandas/tests/series/test_api.py:158:            [x[1] for x in _d], index=pd.Index([x[0] for x in _d], tupleize_cols=False)
- [ ] pandas/tests/series/test_arithmetic.py:244:        dt = Series(date_range("2012-1-1", periods=3, freq="D"))
- [ ] pandas/tests/series/test_constructors.py:137:        # these are Index() and RangeIndex() which don't compare type equal
- [ ] pandas/tests/series/test_datetime_values.py:85:            Series(date_range("20130101", periods=5), name="xxx"),
- [ ] pandas/tests/series/test_io.py:15:    def read_csv(self, path, **kwargs):
- [ ] pandas/tests/series/test_logical_ops.py:164:        result = left & pd.Index(right)
- [ ] pandas/tests/series/test_missing.py:215:        tm.assert_series_equal(result, ts[pd.notna(ts)])
- [ ] pandas/tests/series/test_period.py:19:            [pd.Period("2011-01-01", freq="D"), pd.Period("2011-02-01", freq="D")]
- [ ] pandas/tests/series/test_repr.py:169:        with pd.option_context("max_rows", None):
- [ ] pandas/tests/series/test_timeseries.py:19:        rng = date_range("1/1/2000", "3/1/2000", freq="B")
- [ ] pandas/tests/series/test_ufunc.py:246:    arr = np.array([Dummy(0), Dummy(1)])
- [ ] pandas/tests/test_algos.py:43:        codes, uniques = algos.factorize(["a", "b", "b", "a", "a", "c", "c", "c"])
- [ ] pandas/tests/test_multilevel.py:307:            index=pd.Index([2], name="ix1"),
- [ ] pandas/tests/test_strings.py:189:    values = np.array(values, dtype=object)  # object dtype to avoid casting
- [ ] pandas/tests/tools/test_to_datetime.py:43:        results1 = [Timestamp("20000101"), Timestamp("20000201"), Timestamp("20000301")]
- [ ] pandas/tests/tools/test_to_numeric.py:58:    result = to_numeric(ser, **input_kwargs)
- [ ] pandas/tests/tools/test_to_timedelta.py:14:        result = to_timedelta(["", ""])
- [ ] pandas/tests/window/test_expanding.py:53:    e = Expanding(Series([2, 4, 6]), window=2)
- [ ] pandas/tests/window/test_rolling.py:81:        {"value": np.arange(n)}, index=pd.date_range("2015-12-24", periods=n, freq="D")

----

See #37335 for an example pull request

**Comment by jreback** [comment]
umm didn't @dsaxton PR do this? we should just change them all in one go

**Comment by MarcoGorelli** [comment]
His PR was only for instances of pd.DataFrame - here there are many more, e.g. `pd.to_datetime` and `to_datetime` in the same file.

> we should just change them all in one go

OK, I can make a sweeping change then - but it'll be a huge PR

**Comment by MarcoGorelli** [comment]
I'll close then and'll make a PR to do it all in one go

**Comment by jreback** [comment]
see my comment on your PR
i don't think we should change these at all except to make them consistency pd. which they likely already are

**Comment by MarcoGorelli** [comment]
OK, thanks for explaining - I'll come back to this later
