### ISSUE TITLE
DOC:Pandas groupby agg example for k-hot encoding

### ISSUE THREAD

**Issue by XtremeGood** [pandas-dev/pandas#37378]
#### Location of the documentation
https://pandas.pydata.org/pandas-docs/version/0.22.0/generated/pandas.DataFrame.aggregate.html#pandas.DataFrame.aggregate

[this should provide the location of the documentation, e.g. "pandas.read_csv" or the URL of the documentation, e.g. "https://dev.pandas.io/docs/reference/api/pandas.read_csv.html"]

**Note**: You can check the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/).

#### Documentation problem
It is strange that even on stackoverflow reverse explode has only a single answer(that too is asked very recently). So adding a few more examples should not be bad.
![image](https://user-images.githubusercontent.com/40588378/97079156-51586480-160f-11eb-8545-2efa6c384784.png)

[this should provide a description of what documentation you believe needs to be fixed/improved]

#### Suggested fix for documentation
The following example tells how to perform k-hot encoding with agg. 

![image](https://user-images.githubusercontent.com/40588378/97079098-ddb65780-160e-11eb-9db3-0577a034352e.png)

```
maximum = df.groupby("ImageId").agg({"ClassId":lambda x:x.tolist()})["ClassId"].max()[0]
df = df.groupby("ImageId").agg({"ClassId":lambda x:x.tolist()})
df["ClassId"] = df["ClassId"].apply(lambda x:[1 if i+1 in x else 0 for i in range(maximum)] )
```

![image](https://user-images.githubusercontent.com/40588378/97079113-09394200-160f-11eb-90ad-5b1c38d86859.png)

[this should explain the suggested fix and **why** it's better than the existing documentation]

**Comment by arw2019** [comment]
Are you interested in submitting a PR?

**Comment by XtremeGood** [comment]
I have the code but I do not know much about PR. I just mean to put that example in the docs if you want.

**Comment by arw2019** [comment]
> I have the code but I do not know much about PR. I just mean to put that example in the docs if you want.

Right. that would be great! If you'd like to open a PR to add that example is what I meant.

**Comment by nagesh-chowdaiah** [comment]
i can help here to create the PR @XtremeGood if you don't mind

**Comment by XtremeGood** [comment]
yes I need help. I just have experience of a single PR that I made to sympy 2 years ago.

**Comment by arw2019** [comment]
Take a look at the [doc contributor guide](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#contributing-to-the-documentation). You don't need to set up a dev environment for this, just start a branch and make changes to the relevant doc section. Most of the styling is taken care of if you use our [precommit tool](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#pre-commit)

Don't hesitate to post any questions here!

**Comment by XtremeGood** [comment]
I think I 'm getting you. Fork->Make a new branch -> Make edits to html file -> Pull Request.

**Comment by arw2019** [comment]
Not the html file, we auto generate that. you want to edit either a docstring in a .py file or .rst file in the API ref

**Comment by XtremeGood** [comment]
Oh so there seems to be some code generation stuff going on. I have heard of it. Ok let me try it then. Extending the doc string of the .py file.

**Comment by arw2019** [comment]
> Oh so there seems to be some code generation stuff going on. I have heard of it. Ok let me try it then. Extending the doc string of the .py file.

Great! Ping with any questions

**Comment by XtremeGood** [comment]
Well, I added the code to the docstring but I 'm getting whitespaces errors and other errors. I edited the file on GitHub itself. I can't see the spaces too.

**Comment by XtremeGood** [comment]
I had used tabs because when I did `df.to_clipboard()` the column names were out of the dataframe area. So I had to align them with the columns

**Comment by arw2019** [comment]
Can you open a pull request? I'll help debug

**Comment by XtremeGood** [comment]
I had opened one because the pep8bot showed me all those errors.

**Comment by arw2019** [comment]
I see now

**Comment by arw2019** [comment]
You need to action what is says (get rid of whitespaces, if a line is too long run over to the next one etc.)

**Comment by XtremeGood** [comment]
https://github.com/pandas-dev/pandas/pull/37543

**Comment by XtremeGood** [comment]
Looks quite difficult. There are so many tabs, spaces errors and I can't see them(tabs, spaces, newlines).

**Comment by arw2019** [comment]
Okay it's up to you if you want to continue or leave the issue open for someone else to work on. Ping on the PR when you're ready for a review if you continue otherwise let's close the PR but leave this open

**Comment by XtremeGood** [comment]
Ok I ll try to fix these

**Comment by XtremeGood** [comment]
Hey, btw, how do you write the docstrings? I could have used black but the >>> doesn't let me do it.

**Comment by XtremeGood** [comment]
https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AOLAbtdAD2IimZxl1N_Wgna85uzYfFb0m7YrYUXzXDwjzVNQRdlgthEJgyoH3Uw61ztudSIGYI72VzNbtRp9zyXuvvSORrVBiJxqahG24lJnbK_2t56IddpgRKK2moYESLSizCm1vcijYAiaDO_pL_fpIUjZz-oq2BSXW00PScSCwWCex4z2pMDieu94OQ9qy4PYpyiZ1A9zWd6XdFswt15cww8ShoXMzOHcoxStEEJWqYOKO95FMcnvF8jt_kbpP_AkEBPeXZkFnMioTzzG1f3qdrlI8BP65khpFMlQl7T8zOSkR8GVBorvzi9cyO5WmOfUNnwBf2s2CwnBoGDTr8gvCTZYRUCVUdjqejMZlNruGoHd27Ke_JLMBbyyXXHoULvSOUtO8y-xL879_mZA2RU43kctc5OfXYIMjYZ-yf3723734Mi7TGVs9blHmayRnnHVsmguahe7ibEwAKL7B5hJprxbKIkm6T1aDHLFszc9NhoAZ1LXtkNhgc0D7rFJC7pTg0CZ_3of3iz413w1ZgA-rHrVN3MmIAKUV5GfZitwUpuJ_dJvt_ymZs70pWxYGFNC5KBwN9KXyjFSEy_0CnYAACH249IBatVkgAB1wOMBwAAnJ0OKbHEZ_sCAAAAAARZWg==

**Comment by arw2019** [comment]
Maybe I'm misunderstanding but why wouldn't you use `get_dummies` for this?

**Comment by XtremeGood** [comment]
1) Ah, right.
2) Before writing that code, I did ask it on SO python chat and they gave me a dirty `pivot_table` solution. Nobody told me about this function.

Thanks, this can be closed. But do you mind having that example with agg too?

**Comment by arw2019** [comment]
> 1. Ah, right.
> 2. Before writing that code, I did ask it on SO python chat and they gave me a dirty `pivot_table` solution. Nobody told me about this function.
> 
> Thanks, this can be closed. But do you mind having that example with agg too?

Personal opinion: I'd rather not. Usage of `apply` is an antipattern in pandas (it has terrible performance). 

But feel free to keep the PR open and let others weigh in

**Comment by XtremeGood** [comment]
Ya I know apply applies a function which avoids vectorization. But is it always possible to find a work around?

**Comment by arw2019** [comment]
> Ya I know apply applies a function which avoids vectorization. But is it always possible to find a work around?

Not always, that's why we provide `apply`. But when it is (like here) `apply` should be avoided

**Comment by XtremeGood** [comment]
I would do it for  learning purposes and yes then you can decide upon it.

**Comment by XtremeGood** [comment]
> 
> 
> > Ya I know apply applies a function which avoids vectorization. But is it always possible to find a work around?
> 
> Not always, that's why we provide `apply`. But when it is (like here) `apply` should be avoided

Also can you share the knowledge which function would you use in place of apply for performing that encoding?It would increase my skills.

**Comment by arw2019** [comment]
> I would do it for learning purposes and yes then you can decide upon it.

Feel free to do that! However, if you're interested in getting started on contributing it might be a better idea to choose another issue (look for labels "Good first issue") since I'm not sure this will go in.

**Comment by arw2019** [comment]
> Also can you share the knowledge which function would you use in place of apply for performing that encoding?It would increase my skills.

https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html

**Comment by XtremeGood** [comment]
Hmm, ok. I already have the dev environment setup so it should not be very difficult to get started.

**Comment by XtremeGood** [comment]
> 
> 
> > Also can you share the knowledge which function would you use in place of apply for performing that encoding?It would increase my skills.
> 
> https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html

I already have seen the docs for `get_dummies`. I thought you meant some vectorization method to convert [1, 3] to [1, 0, 1, 0]
