### ISSUE TITLE
List indexing works for .tail() but not .head()

### ISSUE THREAD

**Issue by Symeonw** [pandas-dev/pandas#37413]
- [x ] I have checked that this issue has not already been reported.

- [x ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
df.close.head(1)[0]
df.close.tail(1)[0]

```

df.close.head(1)[0] <-- Works just fine
df.close.tail(1)[0] <-- Returns KeyError: 0

Current fix:
list(df.close.tail(1))[0]

[df.close.tail(1)][0] does not work. 

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Expected Output
The last number by itself without its index. The current output just returns an error, so, it would be great to have it more consistent with the return of its .head() counterpart. 

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.7.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.5
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 47.3.1.post20200622
Cython           : 0.29.17
pytest           : 5.4.3
hypothesis       : 5.18.3
sphinx           : 3.1.1
blosc            : None
feather          : None
xlsxwriter       : 1.2.9
lxml.etree       : 4.5.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.16.1
pandas_datareader: None
bs4              : 4.9.1
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.1
matplotlib       : 3.2.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : 0.15.1
pytables         : None
pytest           : 5.4.3
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.18
tables           : 3.6.1
tabulate         : 0.8.7
xarray           : 0.15.1
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.9
numba            : 0.49.1

</details>

**Comment by jreback** [comment]
pls show an actual reproducible example

you almost certainly need to just use .iloc as getting the last index is often NOT 0

**Comment by phofl** [comment]
See https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports for an example of a minimal example.

**Comment by venaturum** [comment]
@Symeonw This is not a bug. As per jreback's comment you need to use .iloc if you want to get the first element in the tail series.

**Comment by Symeonw** [comment]
------------------------------

import pandas as pd
close = [1,2,3,4,5,6]
df = pd.DataFrame(pd.Series(close))
df.columns = ["close"]
df["open"] = [2,3,1,4,5,6]

df.close.head(1)[0]

df.close.tail(0)[0]

--------------------------------
Here is an example of the code. 

.iloc can be used, but in the least, for consistency, one would expect similarly applied methods to have similar outcomes.

**Comment by jreback** [comment]
```In [11]: df.close.tail(1)                                                                                                                                                                                       
Out[11]: 
5    6
Name: close, dtype: int64

In [12]: df.close.head(1)                                                                                                                                                                                       
Out[12]: 
0    1
Name: close, dtype: int64

```

``[]`` is a label-based indexer and this is a correct and expected result. pls read the docs here: https://pandas.pydata.org/docs/user_guide/indexing.html#basics
