### ISSUE TITLE
xlrd is required for handle excel in pandas but it is EOL and yield warnings on py37

### ISSUE THREAD

**Issue by MikHulk** [pandas-dev/pandas#37438]
Hello,

To use `pandas.read_excel` and `pandas.DataFrame.to_excel` we need xlrd.

xlrd is EOL, and can be replaced with OpenPyXL Do you plan this migration ?

Moreover, now xlrd yield warnings with python 3.7

```
xlrd/xlsx.py:266: PendingDeprecationWarning: This method will be removed in future versions.  Use 'tree.iter()' or 'list(tree.iter())' instead.
    for elem in self.tree.iter() if Element_has_iter else self.tree.getiterator():

```

```
xlrd/xlsx.py:312: PendingDeprecationWarning: This method will be removed in future versions.  Use 'tree.iter()' or 'list(tree.iter())' instead.
    for elem in self.tree.iter() if Element_has_iter else self.tree.getiterator()
```

**Comment by jorisvandenbossche** [comment]
Hi @MikHulk, yes, we are aware of that problem. See https://github.com/pandas-dev/pandas/issues/28547. But note that xlrd is not *required*, it's only the default (and which we need to change), but you can already use openpyxl instead.

**Comment by MikHulk** [comment]
Hi @jorisvandenbossche thank you.

It's a very good news I am going to switch to openpyxl.
