### ISSUE TITLE
BUG: read csv with enclosed double quotes

### ISSUE THREAD

**Issue by zer0link** [pandas-dev/pandas#37442]
- [ ✔] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
def read_as_df(self, file_path):
        return pd.read_csv(
            file_path,
            sep='|',
            quoting=csv.QUOTE_ALL,
            encoding='utf-16'
        )
```

#### Problem description
I have a csv with some data with separator "|" and all columns are enclosed with double quotes:
```
"Code"|"Owner"|"OwnerName"|"Age"|"Description"|"AdditionalRemarks"
"122"|"100"|"Random owner 1"|"52"|"’Some random description""|"Some addtitional remarks"
"123"|"101"|"Owner 2"|"32"|"Data1 | Data2 | Data3"|"Addtitional remarks ++"
```

When I read the csv using the code above: I got this result:
#### Shown Output:
![image](https://user-images.githubusercontent.com/7539963/97289933-29077a80-1848-11eb-9de2-73dc221c0787.png)

#### Expected Output
For data row 1: the addtional remarks column is read as part of the description column
For data row 2: the data looks fine

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]
INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.7.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.17763
machine          : AMD64
processor        : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : None.None

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 20.2.3
setuptools       : 40.8.0
Cython           : None
pytest           : 5.3.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 1.0.1
pymysql          : 0.10.1
psycopg2         : 2.8.6 (dt dec pq3 ext lo64)
jinja2           : 2.11.1
IPython          : 6.3.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 0.8.4
fastparquet      : 0.3.2
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 1.0.1
pytables         : None
pyxlsb           : None
s3fs             : 0.3.4
scipy            : None
sqlalchemy       : 1.3.20
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.45.1
</details>

**Comment by erfannariman** [comment]
I would argue this as a bug and say that this is a problem in the data delivery and the choice of the quote character:

```
"’Some random description""|"Some addtitional remarks"
^                                            ^
start quote char 1            end 1
                                               ^
                                           start 2
                                                  ^
                                                end 2
```

So it actually makes sense that the delimiter is ignored and read in as text

**Comment by erfannariman** [comment]
I wouldn't say that this is a bug in the csv reader of pandas but a problem in your data delivery. The delimiter is enclosed in two quote characters and thus ignored.
