### ISSUE TITLE
ENH: support casting Int arrays with nulls to np.float?

### ISSUE THREAD

**Issue by arw2019** [pandas-dev/pandas#37460]
xref https://github.com/numpy/numpy/issues/17659

> I would expect numpy to automatically convert such arrays into a float type and fill with np.nan. However, for some reason it converts it to object:
> 
> `pd.DataFrame({'col': [1, np.nan, 3]}).astype('UInt8').values.dtype`
> 
> which leads to errors like this one
> 
> `np.nanmax(pd.DataFrame({'col': [1, np.nan, 3]}).astype('UInt8').values)`
> 
> returns "TypeError: boolean value of NA is ambiguous"
> 
> Is that expected ?

Personally I don't have a strong opinion re: whether it's a good idea to support this

**Comment by jorisvandenbossche** [comment]
We discussed this (somewhat) before when the nullable integer dtype was first introduced, and then also when pd.NA was introduced / in the nullable float dtype discussion. 

It's a difficult topic. On the one hand, automatically using np.nan as missing value indicator is not fully correct (it looses information, and np.nan behaves differently than pd.NA) and you could therefore argue that it should take explicit action from the user to ask for it. 
On the other hand, most code that is written to work on numpy arrays will typically be able to handle np.nan, but none will be able to handle pd.NA, making this default behaviour of using object dtype in the conversion of nullable arrays to numpy probably rather annoying.

**Comment by Kreol64** [comment]
@jorisvandenbossche , I would vote for backward compatibility with the existing users` codebase that includes thousands of np.nan*() functions applied to pandas columns/group by statements.
