### ISSUE TITLE
PERF: performance regression in timeseries/timestamp comparison (ASV)

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#37462]
See https://pandas.pydata.org/speed/pandas/#arithmetic.Timeseries.time_series_timestamp_compare?python=3.8&Cython=0.29.21&p-tz=None&commits=ac7ca239-038aab96

This seems to be caused by https://github.com/pandas-dev/pandas/pull/37313 cc @jbrockmendel

**Comment by simonjayhawkins** [comment]
@jorisvandenbossche is the milestone here correct?
