### ISSUE TITLE
BUG: Rolling calls custom function with wrong index

### ISSUE THREAD

**Issue by alexeypertcev** [pandas-dev/pandas#37483]
#### Code Sample, a copy-pastable example
```python
def test_count(x):
    last_index = None
    count = 0

    print(" - test_count")
    for index, value in x.items():
        print(" - - index, value: {}, {}".format(index, value))
        last_index = index
        count += 1

    res = pd.Series([count], index=[last_index])
    return res

def test():
    df = pd.DataFrame({'B': [3030, 3030, 1010],
                       'C': [1, 1, 1]},
                  index = [ pd.Timestamp('2020-04-13 04:30:30'),
                            pd.Timestamp('2020-04-13 04:30:30'),
                            pd.Timestamp('2020-04-13 05:10:10'),])
    print(df)
    
    df_grouped_by_B = df.groupby('B')
    df_tmp = pd.DataFrame(df_grouped_by_B.rolling("1H").B.agg(
        {
            "count" : test_count,
        }
    ))
    
    print(df_tmp)
    
print("pandas {}".format(pd.__version__))
test()

```
#### Problem description
The problem in the calling of test_count function with wrong Series objects, the first call of test_count should be with Series (2020-04-13 04:30:30, 1010) as in previous pandas version (1.0.5), but the new version calls function with wrong argument (index, value: 2020-04-13 05:10:10, 1010). This wrong Series object is not possible for above DataFrame.
(This is minimal example for repeat the problem. I use more difficult processing in agg function.)
#### Expected Output (1.0.5 version works right)
```
pandas 1.0.5
                        B  C
2020-04-13 04:30:30  3030  1
2020-04-13 04:30:30  3030  1
2020-04-13 05:10:10  1010  1
 - test_count
 - - index, value: 2020-04-13 05:10:10, 1010.0
 - test_count
 - - index, value: 2020-04-13 04:30:30, 3030.0
 - test_count
 - - index, value: 2020-04-13 04:30:30, 3030.0
 - - index, value: 2020-04-13 04:30:30, 3030.0
                          count
B                              
1010 2020-04-13 05:10:10    1.0
3030 2020-04-13 04:30:30    1.0
     2020-04-13 04:30:30    2.0
```
#### Output with pandas 1.1.3
```
pandas 1.1.3
                        B  C
2020-04-13 04:30:30  3030  1
2020-04-13 04:30:30  3030  1
2020-04-13 05:10:10  1010  1
 - test_count
 - - index, value: 2020-04-13 04:30:30, 1010.0
 - test_count
 - - index, value: 2020-04-13 04:30:30, 3030.0
 - test_count
 - - index, value: 2020-04-13 04:30:30, 3030.0
 - - index, value: 2020-04-13 05:10:10, 3030.0
                          count
B                              
1010 2020-04-13 05:10:10    1.0
3030 2020-04-13 04:30:30    1.0
     2020-04-13 04:30:30    2.0
```
#### Output of ``pd.show_versions()``
<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-51-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8

pandas           : 1.1.3
numpy            : 1.19.3
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.18.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.3.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.3
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : 0.51.2
</details>

**Comment by mroeschke** [comment]
It appears though that the results are equivalent though in both cases?

**Comment by alexeypertcev** [comment]
Yes, final results are equivalent.
But it is wrong behaviour if I need use custom logic in function (get or set value in Dataframe), based on index value.

**Comment by mroeschke** [comment]
Could you demonstrate an example where it affects the final output? It is difficult to confirm a fix if there's a potential issue in intermediate results

**Comment by mroeschke** [comment]
Thanks for the report. Please let us know if you could give a simplified bug report that demonstrates the wrong behavior. Closing but happy to reopen one there's is a minimal reproducible example
