### ISSUE TITLE
BUG: File saved with to_stata and version=119 cannot be opened with STATA 15.1 SE

### ISSUE THREAD

**Issue by raffaem** [pandas-dev/pandas#37490]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
df = pd.DataFrame({"A":[1]})
df.to_stata("a.dta", version=119)

```

#### Problem description

I have Stata/SE 15.1.

I run the above code, then try to open `a.dta` with my version of Stata.

But Stata doesn't open the file and instead gives the following error:

> dataset too large
>     This .dta file format was created by Stata/MP and has more variables than your Stata can handle.

Of course the file is not too large, since it contains only 1 observation and 1 variable.
It looks like pandas is saving the file in the "MP" version. 
I propose to save it in the SE version, or at least specify which sub-version of Stata the file is saved in in the documentation.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Italian_Italy.1252

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.0.post20201006
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.18.1
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.8.3
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.0
sqlalchemy       : 1.3.20
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.51.2

</details>

**Comment by jbrockmendel** [comment]
cc @bashtage

**Comment by bashtage** [comment]
The files we create are compliant with the state DTA documentation.  It is hard to know what is broken.  I think 119 can never be open in SE since it is only created when there is a very large number of variables.  Stata will only create 118 files for datasets that SE can handle. 

IMO there is no fix possible that can address this limitation imposed by Stata Corp.

**Comment by bashtage** [comment]
I would be happy to support a PR that added some documentation that states that 119 cannot be opened in Stata SE. Although this might need a caveat as to the date since this might change in the future, which makes documenting Stata's behavior a bit problematic.
