### ISSUE TITLE
CI: revert disable of windows window/moments tests

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#37535]
Here we disable collection of the windowing tests *only* on windows: https://github.com/pandas-dev/pandas/pull/37455

let's see if we an figure out where this is coming on.

cc @mroeschke @AlexKirko @jbrockmendel

**Comment by nagesh-chowdaiah** [comment]
@jreback 

```
if [[ $(uname) != "Linux"  && $(uname) != "Darwin" ]]; then
    # GH#37455 windows py38 build appears to be running out of memory
    #  skip collection of window tests
    PYTEST_CMD="$PYTEST_CMD --ignore=pandas/tests/window/"
fi
```
I think we need to revert this change to enable the window test for windows

if you can i can take this ticket

**Comment by nagesh-chowdaiah** [comment]
take

**Comment by jreback** [comment]
to be clear we need to actually fix the failing tests when all are run on windows before this is reverted.

**Comment by nagesh-chowdaiah** [comment]
I think we should have kept the PR open to understand the issue.. and debug more on that. I have heard that the issues are been generated by node.js. are we using node anywhere in the code

**Comment by jreback** [comment]
not sure what this has to do with node.js

this issue has been around for a while - you are welcome to debug 
pls indicate if that is the case in thr PR by making it a draft

**Comment by mroeschke** [comment]
@jbrockmendel why were the `tests/window` excluded specifically?

**Comment by jbrockmendel** [comment]
i figured they had a large ratio of collection-overhead to actually-being-run.  ill have no objection if you want to re-enable them and do something more targeted

**Comment by mroeschke** [comment]
Gotcha. Just curious if it was something known about those tests in particular that was specifically causing the memory issues.
