### ISSUE TITLE
ENH: extend DataFrame.insert to also insert rows

### ISSUE THREAD

**Issue by martijnvanattekum** [pandas-dev/pandas#37558]
#### Is your feature request related to a problem?

I wish I could use pandas to directly insert a row at a specific position in a data frame, just like I can insert a column via the `DataFrame.insert` method. This would be similar to the [add_row](https://tibble.tidyverse.org/reference/add_row.html) function that exist for R data frames.

#### Describe the solution you'd like

expand the functionality of `DataFrame.insert` to take an axis argument and allow for the insertion of rows when `axis` is set to `0`.

#### API breaking implications

as `insert` currently inserts a column by default, the default argument to `axis` should be set to `1`. When this is done, I don't foresee any breaks.

#### Describe alternatives you've considered

An alternative is to use concatenate. This is tedious though, because it requires several concat operations (upper block + row to insert + lower block) and error prone. Another alternative (not in-place) is to use `np.insert` like
```python
import seaborn as sns
import pandas as pd
import numpy as np

def insert_row(df, row, position):
    out = pd.DataFrame(np.insert(arr=df.values,
        	                     obj=position,
                	             values=row,
                                 axis=0),
           	            columns=df.columns)

    return out
iris = sns.load_dataset("iris")
row_to_insert = iris.iloc[1, :]
insert_row(iris, row_to_insert, 1)
```

#### Additional context

Code example to insert column:
```python
import seaborn as sns
iris = sns.load_dataset("iris")
col_to_insert = iris.iloc[:, 1]
position_to_insert = 1
iris.insert(position_to_insert, "new_column", col)
```

Desired behaviour:
```python
row_to_insert = iris.iloc[1, :]
iris.insert(position_to_insert, "new_row", row, axis=0)
```

**Comment by erfannariman** [comment]
This would be a nice addition, especially since you have to write quite some (ugly) code to achieve this, for example:

```
pd.concat([iris.iloc[:1], row_to_insert.to_frame().T, iris.iloc[1:]])
```
One thing you have to take into accunt is index that gets duplicated, so you will probably have an argument as well, where you add 1 to the index of the bottom half of the added row. 

So the downside of this addition is that you probably need two more arguments for `DataFrame.insert` so it get's quite complex:
```
iris.insert(position_to_insert, "new_row", row, axis=0, ignore_index=True)
```

**Comment by jreback** [comment]
we already have .loc and .iloc for indexing 

yet another indexing operations is a -1

**Comment by erfannariman** [comment]
I agree @jreback that adding more indexing operations is a bad idea, rather deprecate them (.at / .iat). But right now there is no obvious way to add a row where 0 <= loc <= len(index). 

So I would be in favour to extend the functionality of a method somewhere in the API to have this functionality.

**Comment by jreback** [comment]
umm what is wrong with .iloc which can update any row you want

**Comment by erfannariman** [comment]
There isn't anything wrong with and we should use `iloc` or `loc` to update any data, but what about adding a row. See example:

```python
In [4]: df = pd.DataFrame({'A': [1, 2, 4], 'B': [5, 6, 8]})

In [5]: df
Out[5]: 
   A  B
0  1  5
1  2  6
2  4  8

In [6]: row = pd.DataFrame({'A': [3], 'B': [7]})

In [7]: pd.concat([df.iloc[:2], row, df.iloc[2:]], ignore_index=True)
Out[7]: 
   A  B
0  1  5
1  2  6
2  3  7
3  4  8
```

**Comment by TomAugspurger** [comment]
I don't think we should encourage growing DataFrames by rows, given the very different performance relative relative to adding a new column.

**Comment by rhshadrach** [comment]
Agreeing with @TomAugspurger, while the `concat` option might be a bit, it truly reflects what's going on. If users really need this, it is easy to write a function that (I think) would be just as performant as what we could do internally.

**Comment by MarcoGorelli** [comment]
closing as there doesn't seem to be much support for this
