### ISSUE TITLE
QST: Seems inconsistent behavior in MultiIndex.is_monotonic ??

### ISSUE THREAD

**Issue by itholic** [pandas-dev/pandas#37576]
#### Question about pandas

In the example below, I have no idea why their results are different in pandas 1.1.4.

```python
>>> pd.MultiIndex.from_tuples([('x', 'a'), ('y', 'b'), ('y', 'b'), ('z', 'a')]).is_monotonic
True
>>> pd.MultiIndex.from_tuples([('x', 'a'), ('y', 'b'), ('y', 'a'), ('z', 'a')]).is_monotonic
False
```

Is it intended behavior in pandas 1.1.4. or seems like bug ??

If this is a bug, which one is correct behavior ??

Thanks :)

**Comment by phofl** [comment]
Hey, thanks for your report. Why would you think this is a bug? The behavior did not change with 1.1.4
