### ISSUE TITLE
ENH: DataFrame Constructions from Data Classes

### ISSUE THREAD

**Issue by daskol** [pandas-dev/pandas#37577]
#### Is your feature request related to a problem?

I wish to construct `pandas.DataFrame` from iterable of `dataclasses.dataclass` as from iterable of tuples `DataFrame.from_records`. The rationale behind is that data classes is more typed object than general tuple or dictionary. Also, data classes more memory efficient than `tuple`'s. It makes data classes attractive to use them instead of `dict`'s or `tuple`'s whenever schema is known.

#### Describe the solution you'd like

I would like class method `.from_dataclasses` which allows `DataFrame` construction and type inference from uniform (for simplicity) sequence of data classes. See example below.

```python
import pandas as pd
from dataclasses import dataclass


@dataclass
class Record:
    id: int
    name: str
    constant: float

df = pd.DataFrame.from_dataclasses([
    Record(0, 'Landau', 3.1415926),
    Record(1, 'Kapitsa', 2.718281828459045),
    Record(2, 'Bogolyubov', 6.62607015),
])

print(df.dtypes)
#  id            int64
#  name         object
#  constant    float64
#  dtype: object
````
In the example above schema of `DataFrame` is infered with `Record.__annotations__` dictionary which contains type user provided type information. API could also provide ways to validate schema in runtime by comparying type of actual type and specified type for a column.

#### API breaking implications

There is no API breaking in general but there is requirements to minimum Python version (which is 3.7).

**Comment by TomAugspurger** [comment]
We already support that in the main DataFrame constructor, right? https://pandas.pydata.org/docs/user_guide/dsintro.html?highlight=dataclass#from-a-list-of-dataclasses

**Comment by daskol** [comment]
> We already support that in the main DataFrame constructor, right?
Wow! It really works. Nice!

Well, I guess that an explicit mention of data classes in API reference is neded. I guess that many people (especially mature users) looks up on the reference and do not read user guide intro.

**Comment by jreback** [comment]
> Wow! It really works. Nice!
> 
> Well, I guess that an explicit mention of data classes in API reference is neded. I guess that many people (especially mature users) looks up on the reference and do not read user guide intro.

sure would take updated docs.

also could take a PR to import dataclass at the top level (as this was for 3.6 compat before): https://github.com/pandas-dev/pandas/blob/master/pandas/core/dtypes/inference.py#L419

**Comment by taytzehao** [comment]
Updated the pandas dataframe docstring to include dataclasses together with an example. Please help to provide feedback as it is my first time contributing. #37632

**Comment by taytzehao** [comment]
Updated #37649 


> Updated the pandas dataframe docstring to include dataclasses together with an example. Please help to provide feedback as it is my first time contributing. #37632

Updated this PR's comment on new PR #37649

**Comment by TomAugspurger** [comment]
Closed by https://github.com/pandas-dev/pandas/pull/37632

**Comment by taytzehao** [comment]
Updated mistakes of the documentation update #37699
