### ISSUE TITLE
API: Should Index.where/insert raise or cast on invalid other?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#37594]
Index.where

ATM `index.where(mask, something_incompatible)` raises for EA-backed indexes and MultiIndex and casts (sometimes buggily xref #37591) for everything else.

These should all do the same thing.  I lean towards raising rather than casting.  Doing that breaks a handful of tests, but AFAICT they are all directly testing Index.where, so not used by other parts of the code.

----
Index.insert

CategoricalIndex and IntervalIndex raise on invalid, PeriodIndex casts to object, DatetimeIndex and TimedeltaIndex cast to object _only_ for strings and otherwise raise.  The base class casts but uses _coerce_scalar_to_index instead of any of our more standard patterns.

If changed to always raise, 25 tests fail.  Most of these are directly testing Index.insert so could be changed if the API changed.  The main troubling one is test_pivot_periods_with_margins, which I haven't tracked down all the way.

---
Index.putmask I'm still getting a handle on

**Comment by jbrockmendel** [comment]
On "insert" loc.setitem is liable to raise if we dont cast

**Comment by jorisvandenbossche** [comment]
Is there a reason you closed this?

**Comment by jbrockmendel** [comment]
I determined pretty definitively that `insert` needs to cast, and im not actually sure where/putmask are really needed.  (IIRC there is one non-test place where Index.where is used)

**Comment by jorisvandenbossche** [comment]
`Index.where` is a public method, so should ideally have a clear / consistent API, so I think the question your raised is still relevant (also, the same inconsistency is true for `Series.where`)
