### ISSUE TITLE
BUG: DataFrame iloc does not accept Series assignment

### ISSUE THREAD

**Issue by jonasreiher** [pandas-dev/pandas#37593]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

---

#### Code Sample, a copy-pastable example

```python
df = pd.DataFrame(columns=[0], index=[0])

df.iloc[0,0] = pd.Series([1,2,3])    # this raises a ValueError
df.iloc[0] = [pd.Series([1,2,3])]    # this works, but is ugly

```

#### Problem description

When trying to assign a pandas.Series to one cell of a pandas.DataFrame, the following error is raised:
`ValueError: Incompatible indexer with Series`
Series in DataFrames are a common thing e.g. in sktime, when working with multivariate time series data and (as the working example above shows) it is unproblematically supported by pandas. Just the assignment to one cell via .iloc seems to be erroneous.

<details>

INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
machine          : AMD64
processor        : Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : de_DE.cp1252

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.0.post20201006
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.18.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by GYHHAHA** [comment]
I don't think this is necessary. Could you a more specific example about its usage in sktime?

**Comment by jreback** [comment]
This is a very strange thing to do. I suppose this is technically a bug as a scalar could be anything, even a list-like

e.g. this works

```
In [189]: df = pd.DataFrame(columns=[0], index=[0]) 
     ...:  
     ...:                                                                                                                                                                                       

In [190]: df.iloc[0, 0] = [5, 3, 1]                                                                                                                                                             
```

so will mark it though embedding complicated structures *inside* a cell is non-performant and likely has rough edges.

**Comment by onshek** [comment]
take

**Comment by onshek** [comment]
@jreback  It seem right here dose not accept a `Series` https://github.com/pandas-dev/pandas/blob/28a0f666217f1a4590f74cad2ee42d263af843d5/pandas/core/indexing.py#L1944

**Comment by jonasreiher** [comment]
@GYHHAHA sktime uses exactly this format when loading multivariate time series data ([see documentation](https://www.sktime.org/en/latest/examples/loading_data.html)) with samples in rows, channels in columns and the time dimension in the series. And this is then also the format expected by different classifiers, even if its performance may not be the best.
So I think you should be able to contruct something like this manually without unpleasant workarounds.

**Comment by GYHHAHA** [comment]
Strange. This looks fine.

```python
>>>df = pd.DataFrame({'dim0':[pd.Series([1,2])], 'dim1':[pd.Series([3,4])]})
>>>df.loc[0, 'dim0']
0    1
1    2
dtype: int64
```

And also the following assignment raises. 

```python
>>>df = pd.DataFrame([[0]])
>>>df.iloc[0,0] = [5, 3, 1] 
ValueError: setting an array element with a sequence.
```

**Comment by jreback** [comment]
i was running on an older version actually

can u run on master and show the results

**Comment by GYHHAHA** [comment]
Now I have checked these two on master. Still the same results.

**Comment by phofl** [comment]
I think this would be fixed through #37718, even if this was not the intent :)

**Comment by onshek** [comment]
> I think this would be fixed through #37728, even if this was not the intent :)

well, then I will unassign myself

**Comment by cedricdonie** [comment]
Workaround for older pandas versions: use [`df.at`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.at.html) instead of `df.loc`. I tested this with pandas 1.1.5.

Perhaps `df.iat` can also be used a workaround for `df.iloc`, but I have not tested this. Unfortunately, sktime-dl restricts me to using this old pandas version.

**Comment by jmpalumbo** [comment]
`df.at` worked like a charm. This is the only board online where I saw `df.at` as a solution to this `ValueError`. Thank you @cedricdonie
