### ISSUE TITLE
ENH: support none in header list 

### ISSUE THREAD

**Issue by ShaneKao** [pandas-dev/pandas#37625]
I have a file with two sheets, one has a header, and another hasn't. 
The following code will raise `TypeError: list indices must be integers or slices, not NoneType.`

```python
# Your code here, if applicable
df = pd.read_excel(file_path, sheet_name=None, header=[0, None])
```

**Comment by ivanovmg** [comment]
@ShaneKao can you add the file concerned here?
``header`` should be a list of col names for the given sheet, not one col name per sheet.
Thus, I would like to clarify what the actual problem is.

**Comment by ShaneKao** [comment]
[test.xlsx](https://github.com/pandas-dev/pandas/files/5535273/test.xlsx)

    import pandas as pd

    df = pd.read_excel('test.xlsx', sheet_name=None, header=[0, None])

    df1 = pd.read_excel('test.xlsx', sheet_name='Sheet1', header=0)
    df2 = pd.read_excel('test.xlsx', sheet_name='Sheet2', header=None)

**Comment by ivanovmg** [comment]
Thank you. Now I see what the problem is.
I guess that header as as list is reserved to creating multiindex columns, so making what you suggest is hardly ever possible.

Would mapping be a more viable option?

```
df = pd.read_excel(fname, header={'Sheet1': 0, 'Sheet2': [0, 1]})
```

I am not sure if that is easy to implement, but just it seems more reasonable in terms of usage.

**Comment by Alvinwuzw** [comment]
I would love to try adding this feature to the pandas. Could I take the issue?

**Comment by mroeschke** [comment]
Thanks for the request, but it appears there hasn't been much traction for this request over the years so closing
