### ISSUE TITLE
BUG: RollingGroupby duplicates columns in index even with group_keys=False

### ISSUE THREAD

**Issue by venaturum** [pandas-dev/pandas#37641]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd

arrays = [['val1', 'val1', 'val2'], ['val1', 'val1', 'val2']]
index = pd.MultiIndex.from_arrays(arrays, names=('idx1', 'idx2'))

s = pd.Series([1, 2, 3], index=index)
print(
    s.groupby(["idx1", "idx2"], group_keys=False).rolling(1).mean()
)

```

#### Problem description

the group_keys parameter in Seried.groupby() is broken since 1.1.0 when using .rolling()

It does not seem to be an issue if another function instead of *rolling* is used, eg 
```python
    s.groupby(["idx1", "idx2"], group_keys=False).mean()
```
In pandas=1.1.{0,1} the output is

    idx1 idx2  
    val1 val1  (val1, val1)   1.0
         val1  (val1, val1)   2.0
    val2 val2  (val2, val1)   3.0

In pandas=1.1.{2,3,4} the output is

    idx1 idx2  idx1 idx2     
    val1 val1  val1 val1   1.0
                    val1   2.0
    val2 val2  val2 val2   3.0

#### Expected Output (as per pandas 1.0.*)

    idx1 idx2       
    val1 val1   1.0
         val1   2.0
    val2 val2   3.0

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f2ca0a2665b2d169c97de87b8e778dbed86aea07
python           : 3.6.7.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.17134
machine          : AMD64
processor        : Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.1.1
numpy            : 1.16.1
pytz             : 2018.9
dateutil         : 2.8.0
pip              : 10.0.1
setuptools       : 39.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.3.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10
IPython          : 7.2.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 2.6.0
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by taozuoqiao** [comment]
I have the same problem (`pd.__version__`: 1.1.3), but the alternative approach
```python
s.groupby(["idx1", "idx2"], group_keys=False).apply(lambda x: x.rolling(1).mean())
```
produces the right expected output:
```
idx1  idx2
val1  val1    1.0
      val1    2.0
val2  val2    3.0
dtype: float64
```
This is  documented in [pandas.DataFrame.groupby.html](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html)
>group_keys: bool, default True
>When calling apply, add group keys to index to identify pieces.

**Comment by simonjayhawkins** [comment]
first bad commit: [bad52a9d1ef9fe6b27ef44fae99f483d07ad16f6] PERF: Use Indexers to implement groupby rolling (#34052)
