### ISSUE TITLE
ENH: read_excel improve usecols

### ISSUE THREAD

**Issue by aster94** [pandas-dev/pandas#37686]
#### Is your feature request related to a problem?
No

#### Describe the solution you'd like
Let's imagine a excel database with multiple sheets
We can do `pd.read_excel(db, sheet_name=[0, 1], usecols=[0, 1])` and we would read the first and second columns of the first and second sheets.

Imagine we need to read the first and second columns from the first sheet and the second and third columns from the second sheet. A solution could be to pass to `usecols` a list of list, for example: `pd.read_excel(db, sheet_name=[0, 1], usecols=[[0,1], [1,2]])`. Both integer and string should be used inside the inner-list

#### API breaking implications
No, well I guess

#### Describe alternatives you've considered
Multiple run of `read_excel`

**Comment by jreback** [comment]
this seems overly complicated 
it's simple enough to just call read_excel per sheet with the right options

so -1

**Comment by ZOUG** [comment]
> this seems overly complicated
> it's simple enough to just call read_excel per sheet with the right options
> 
> so -1

Calling `read_excel` twice would require reading the file twice. For large files, that would slow down the loading process. The following alternative would be better.

```
with pd.ExcelFile(path, engine) as file:
        file.parse(sheet1, usecols=[...])
        file.parse(sheet2, usecols=[...])
```

**Comment by aster94** [comment]
Nice snippet @zoug

I am closing the issue

**Comment by ZOUG** [comment]
> Nice snippet @ZOUG if it is not in the tutorial/guide it should be there
> 
> I am closing the issue

There is no API documentation for the `pd.ExcelFile` class. It should be added as well.
