### ISSUE TITLE
TST: Add tests for dtype changes when assigning values via indexing

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#37692]
#37680 will fix the assigning problems reported in #26395. 

We should add further tests for iloc/iat and different dtypes for all cases (loc, at, iloc, iat)

cc @jreback

**Comment by allenmac347** [comment]
take

**Comment by Rprabudeva** [comment]
I would like to contribute this one

**Comment by phofl** [comment]
Ping @allenmac347 are you still working on this?

**Comment by allenmac347** [comment]
Hi, yes I am still working on making tests. I have been busy with classes lately but with Thanksgiving break coming up I should be more free to work on this issue. My apologies for the delay.

**Comment by allenmac347** [comment]
@phofl hello, so after testing loc, iloc, at, and iat, it seems like at and iat does not seem to be able to upcast at all for different dtypes. This code for example throws an error:
# column D initially has an int64 dtype
df = pd.DataFrame(index=['A','B','C'])
df['D'] = 0
df.at['B', 'D'] = "hello"

ValueError: could not convert string to float: 'hello'

This is the same case for iat. Both loc and iloc seem to work fine and promotes column D to an object dtype. It seems like both iat and at are forcing the assigned value to cast to the dtype of the column.

**Comment by phofl** [comment]
cc @jbrockmendel is this done on purpose?

**Comment by jbrockmendel** [comment]
> is this done on purpose?

no, at and iat should behave just like loc and iloc, just restricted to scalar arguments (and i guess without setitem-with-expansion)

**Comment by phofl** [comment]
@allenmac347 Are you interested in debugging this further?

**Comment by allenmac347** [comment]
@phofl yep, I'd be happy to debug this further

**Comment by phofl** [comment]
Great, you can ping me, if you need some help

**Comment by allenmac347** [comment]
@phofl Hey just a quick update. After further debugging this issue, I found that the issue occurs in the _set_value() function on line 3187 in pandas/core/frame.py. Here is the relevant piece of code for when using at to assign a string to an int64 DataFrame index:

try:
            if takeable is True:
                series = self._ixs(col, axis=1)
                series._set_value(index, value, takeable=True)
                return

            series = self._get_item_cache(col)
            engine = self.index._engine
            loc = engine.get_loc(index)
            validate_numeric_casting(series.dtype, value)

            series._values[loc] = value
            # Note: trying to use series._set_value breaks tests in
            #  tests.frame.indexing.test_indexing and tests.indexing.test_partial
except (KeyError, TypeError):
      # set using a non-recursive method & reset the cache
      if takeable:
           self.iloc[index, col] = value
      else:
           self.loc[index, col] = value
       self._item_cache.pop(col, None)

series._values[loc] = value throws a ValueError which the except block doesn't catch. I made somewhat of a hacky fix where I do the following:

if find_common_type([np.array([value]).dtype, series.dtype]) == series.dtype:
        series._values[loc] = value
else:
        raise TypeError

This would make the code go into the except block where it would use loc to convert the dtype to an object and insert the value into the DataFrame. This seemed to fix the ValueError issue and also now correctly upcasts the DataFrame dtype. However, this fix now causes "pandas/tests/frame/indexing/test_set_value.py::TestSetValue::test_set_value_resize" to fail. It appears that this particular test was expecting pandas to raise a ValueError in this particular instance, hence why it's failing. I was wondering how I should move forward? thanks

**Comment by phofl** [comment]
@jbrockmendel Any suggestions how to handle this? 

```
ser = Series([1, 2, 3], index=list("abc"))
ser.loc["b"] = "test"
ser = Series([1, 2, 3], index=list("abc"))
ser.at["b"] = "test"
```

The ``loc`` case works while the ``at`` case raises. This seems odd to me

**Comment by jbrockmendel** [comment]
In DataFrame._set_value, can catch ValueError in addition to KeyError and TypeError.  can add a comment pointing out this case as the reason for catching ValueError

Ditto for Series._set_value.

We probably should send both of those methods through Block.setitem eventually.
