### ISSUE TITLE
BUG: PyMysql : module 'sqlalchemy' has no attribute 'engine'

### ISSUE THREAD

**Issue by 92376** [pandas-dev/pandas#37698]
- [x] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
self.conn = pymysql.connect(**info_dic)
pd.read_sql(sql, self.conn)
```

#### Problem description
line 53, in read_data_frame return pd.read_sql(sql, self.conn) File "/usr/local/lib/python3.6/site-packages/pandas/io/sql.py", line 394, in read_sql pandas_sql = pandasSQL_builder(con) File "/usr/local/lib/python3.6/site-packages/pandas/io/sql.py", line 532, in pandasSQL_builder if _is_sqlalchemy_connectable(con): File "/usr/local/lib/python3.6/site-packages/pandas/io/sql.py", line 86, in _is_sqlalchemy_connectable return isinstance(con, sqlalchemy.engine.Connectable) AttributeError: module 'sqlalchemy' has no attribute 'engine'

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.224-1.el7.elrepo.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.utf8
LOCALE: en_US.UTF-8

pandas: 0.20.3
pytest: None
pip: 10.0.1
setuptools: 28.8.0
Cython: 0.28.1
numpy: 1.14.0
scipy: 1.0.0
xarray: None
IPython: None
sphinx: None
patsy: 0.5.0
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.2
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: 4.5.2
bs4: None
html5lib: None
sqlalchemy: 1.2.4
pymysql: 0.8.0
psycopg2: None
jinja2: None
s3fs: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by ukarroum** [comment]
Hello,

Here are some tips you can use to ensure your questions get the most chance to being resolved : 

- Your title need to give an idea about what your issue is, a lot of people may ignore your issue/question. For example you can use : "BUG : PyMysql : module 'sqlalchemy' has no attribute 'engine' ", not perfect but give a first idea. 
- Problem description is not correctly formatted, maybe an issue using markdown ? 
- pandas 0.20 is pretty old, It may help to test your code on the latest version of pandas (maybe your issue had already been resolved ?).

**Comment by 92376** [comment]
@ukarroum 这是一个老项目的一部分，这个提示不是每次都有，并且项目是在docker中运行的，偶然会导致这个问题；确定项目代码没有一个`sqlalchemy.py`的python文件，让我不思其解

**Comment by 92376** [comment]
This is part of an old project. This prompt does not appear every time, and the project is running in docker, which may cause this problem occasionally. Make sure that there is no code for the project` sqlalchemy.py `Python file, let me not think of its solution

**Comment by MarcoGorelli** [comment]
Hi @92376  - closing for now, will reopen if you include a reproducible example (or at least some more info)
