### ISSUE TITLE
BUG: read_html - file path cannot be pathlib.Path type

### ISSUE THREAD

**Issue by simon-spier0** [pandas-dev/pandas#37705]
```python
import pandas as pd
from pathlib import Path


file_path_string = r'C:\Users\Desktop\my_file.html'
file_path = Path(file_path_string)
df1 = pd.read_html(file_path_string)[0]  # works fine
df2 = pd.read_html(file_path)[0]  # raises TypeError: cannot parse 'from WindowsPath'
```

Why do `read_excel()`, `read_csv()`, `to_excel()`, `to_csv()`, ... support `pathlib.Path` while `read_html()` doesn't?

**Comment by twoertwein** [comment]
thanks @simon-spier0 for the report!

An easy fix would be to call `stringify_path` (from pandas/io/common.py) in `read_html`.

**Comment by inspurwusixuan** [comment]
> thanks @simon-spier0 for the report!
> 
> An easy fix would be to call `stringify_path` (from pandas/io/common.py) in `read_html`.

Hi, I'm new here and want to start my first contribution. Can I take this issue? :) 

Thanks!

**Comment by twoertwein** [comment]
@inspurwusixuan  of course!
