### ISSUE TITLE
BUG: Wrong index after monthly resampling

### ISSUE THREAD

**Issue by justmert** [pandas-dev/pandas#37708]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---
#### Reproduce

```python
df_sent = df_date.groupby('name').resample('M').count()
```
**df_date**
![image](https://user-images.githubusercontent.com/37740842/98491929-65bf7280-2247-11eb-8167-2a172d9f3e1e.png)

**df_sent**
![image](https://user-images.githubusercontent.com/37740842/98491951-75d75200-2247-11eb-9be4-173f11f57707.png)

#### Problem description
When i resample my dataframe to month, it gives wrong index. As you can see my dataframe (__df_date__) has dates from __2020-06-13 10:23:00__ to __2020-09-11 00:22:00__ which has month **6** to **9** so if i resample to month, i expect new dataframe's months from  __2020-06__ to __2020-09__. 
#### Expected Output
![image](https://user-images.githubusercontent.com/37740842/98492238-4aa13280-2248-11eb-88f3-bf472a1e9253.png)
After resampling, new dataframe needs to has these months just like the above

I have searched a solution to this unexpected behaviour and couldn't find anything. If i have wrong intuition about resampling, please correct me. Also i have encountered the same problem in [stackoverflow](https://stackoverflow.com/questions/52527619/wrong-index-after-monthly-resampling-of-dataframe-pandas) which hasn't got a solution

#### Output of ``pd.show_versions()``

<details>

pandas version= 1.1.3
INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.7.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.9.4-arch1-1
Version          : #1 SMP PREEMPT Wed, 04 Nov 2020 21:41:09 +0000
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.0.post20201006
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.18.1
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.8.3
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : 1.3.20
tables           : 3.6.1
tabulate         : 0.8.7
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.51.2

</details>

**Comment by jreback** [comment]
can u post an actual dataframe that is copy pastable and not an image

**Comment by justmert** [comment]
@jreback the dataframe is fairly big (39011 rows × 2 columns) so it is better to post info about it to give intuition about dtypes. 

**df_date**
```
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 39011 entries, 2020-06-13 10:23:00 to 2020-09-11 00:22:00
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   name     39011 non-null  object
 1   message  39011 non-null  object
dtypes: object(2)
memory usage: 2.1+ MB
```

**df_sent**
```
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 12 entries, 2020-01-31 to 2020-12-31
Freq: M
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     12 non-null     int64
 1   message  12 non-null     int64
dtypes: int64(2)
memory usage: 608.0 bytes
```

**Comment by justmert** [comment]
I have resolved the issue. My data had these dates respectively,
```
30.06.2020 23:49 - Mert
30.06.2020 23:49 - Mert
1.07.2020 15:00 - Tolga
1.07.2020 15:00 - Tolga
```
So while pandas parsing the data, it encounters with **30.06.2020** and thinks **30 is day** and **06 is month** which is correct. So far so good but when it encounter with **1.07.2020** _baam_, now our pandas thinks that **1 is month** and **07 is day**. The issue was my fault. I had to use `infer_datetime_format=True` when converting date column to datetime to resolve the issue. I am closing this, thank you.
