### ISSUE TITLE
BUG: rolling covariance then dropping nans doesn't drop first level index which corresponds to those nans

### ISSUE THREAD

**Issue by nwdset** [pandas-dev/pandas#37712]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample

```python
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randn(10, 5))
df = df.rolling(5).cov().dropna()
df.index.levels[0]
```

#### Current Output

```python
Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')
```

#### Problem description

Since doing a rolling covariance would cause the first 4 entries to the dataframe to be nan, which I dropped. However, if I try to access the first level of the index, I would get the full original index, being from 0 to 9. One would expect to receive an index for which the corresponding nan entries was removed for the new first level index. However, 

```python
df.index.get_level_values(0)
```

gives the expected output.

#### Expected Output

```python
Int64Index([4, 5, 6, 7, 8, 9], dtype='int64')
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 67a3d4241ab84419856b84fc3ebc9abcbe66c6b3
python           : 3.9.0.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.1.4
numpy            : 1.19.3
pytz             : 2020.4
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.19.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by ukarroum** [comment]
This is the expected behaviour, for more info check here : https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html#defined-levels 

> The MultiIndex keeps all the defined levels of an index, even if they are not actually used. When slicing an index, you may notice this. For example:

> This is done to avoid a recomputation of the levels in order to make slicing highly performant. If you want to see only the used levels, you can use the get_level_values() method.

Which can be checked (on your example) : 

`
>>> df.index.get_level_values(0)
Int64Index([4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8,
            8, 8, 8, 9, 9, 9, 9, 9],
           dtype='int64')
`

**Comment by mroeschke** [comment]
Thanks for the explanation @ukarroum. Yes, I believe this is the expected behavior.
