### ISSUE TITLE
November 2020 Meeting

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#37751]
The monthly dev meeting is Wednesday November 11th (tomorrow), at 18:00 UTC. Our calendar is at https://pandas.pydata.org/docs/development/meeting.html#calendar to check your local time. The US had a DST transition since the last meeting, so your local time may be different.

Video Call: https://zoom.us/j/942410248?pwd=T2l2Qi9vaC82Z294ZEtFczYxMVM2dz09
Minutes: https://docs.google.com/document/u/1/d/1tGbTiYORHiSPgVMXawiweGJlBw5dOkVJLY-licoBmBU/edit?ouid=102771015311436394588&usp=docs_home&ths=true

FYI, I likely won't be able to attend tomorrow.

**Comment by jreback** [comment]
our meeting is scheduled for tomorrow Dec 10th, I cannot make it at that time, happy for folks to meet then, or reschedule

@pandas-dev/pandas-core

**Comment by jorisvandenbossche** [comment]
Unless there are items we need to discuss with a bigger group, I would propose to keep it as planned. 
(and it doesn't need to take an hour if there aren't many people / if there isn't much to discuss)

**Comment by Dr-Irv** [comment]
Was there an announcement of how to connect to the meeting?  November was announced here, but prior announcements went to the mailing list.  Maybe I missed it?

**Comment by jorisvandenbossche** [comment]
I *think* the zoom meeting link from above (from November) can be used for today as well.
