### ISSUE TITLE
ENH: option to plot data points on top of boxplot

### ISSUE THREAD

**Issue by mikessut** [pandas-dev/pandas#37759]
#### Is your feature request related to a problem?

My longing for this feature comes from many years of using Minitab, [which has a convenient option to show individual data on boxplots](https://support.minitab.com/en-us/minitab/18/help-and-how-to/graphs/how-to/general-graph-options/display-options/boxplot/). As a result, I often find myself wanting to be able to get a better visual idea of the data distribution.  The boxplot would look something like:

![image](https://user-images.githubusercontent.com/2250372/98817645-a524c500-23e7-11eb-8fd4-cd98d1ff7a46.png)

#### Describe the solution you'd like

```
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(10,2))
df.boxplot(plot_points=True)
```

#### API breaking implications

The above implementation adds an optional parameter to boxplot function.

#### Describe alternatives you've considered

What I'm after can be accomplished by other means, for example:
https://stackoverflow.com/questions/29779079/adding-a-scatter-of-points-to-a-boxplot-using-matplotlib
I find some of these alternative methods a bit clumsy, especially when trying to interactively inspect data.

I've looked for some solution along these lines (layer a scatter plot on top of a boxplot), but haven't been able to figure out a path that works.
```
ax = df.plot(kind='box')
# This doesn't work. It requires x and y parameters to be passed. I haven't figured out a way to make categorical scatter plots.
df.plot(kind='scatter') 
```

I've found a way to do it using Seaborn:
```
import seaborn as sns
df = pd.DataFrame(np.random.randn(10, 3))
df2 = df.melt()

sns.boxplot(x='variable', y='value', data=df2)
sns.stripplot(x='variable', y='value', data=df2)
```

**Comment by rhshadrach** [comment]
Echoing some comments in the linked PR, this type of feature seems more appropriate for matplotlib than pandas. In particular, there are many values a user may want to configure (point shape/color/size/alpha, jitter magnitude).

**Comment by MarcoGorelli** [comment]
> Echoing some comments in the linked PR, this type of feature seems more appropriate for matplotlib than pandas

Agreed, plus the PR hasn't had any work on it for 3 months.
Closing both for now then, but thanks @mikessut for your suggestion
