### ISSUE TITLE
CI: migrate from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#37765]
See https://docs.travis-ci.com/user/migrate/open-source-repository-migration, if we want to keep the Travis CI builds, we need to migrate to the .com version before the end of the year.

**Comment by jorisvandenbossche** [comment]
(I am adding the 1.2 milestone for now. Not that it is in any way linked or a blocker to actually releasing 1.2, but doing that as a way to keep this issue a bit more visible, and the timeframe we need to do this migration also is somewhat similar as the planned timeline for 1.2)

**Comment by erfannariman** [comment]
Just for my understanding, on the long term, is it needed to keep Travis while we have the option to use Azure pipelines and/or GitHub Actions?

**Comment by jreback** [comment]
not all capabilities are currently supported in azure, mainly the database testing
also travis has arm and usually is easier to do builds like numpy dev

**Comment by erfannariman** [comment]
> not all capabilities are currently supported in azure, mainly the database testing
> also travis has arm and usually is easier to do builds like numpy dev

Thanks for the clarification.

**Comment by simonjayhawkins** [comment]
I think the gist of the discussion in https://github.com/scipy/scipy/issues/13109 is that there is a preference to migrate to Azure/Github Actions where possible.

> not all capabilities are currently supported in azure, mainly the database testing
> also travis has arm and usually is easier to do builds like numpy dev

We currently have 4 build in Travis. Do all of these need to be on Travis?

**Comment by simonjayhawkins** [comment]
> (I am adding the 1.2 milestone for now. Not that it is in any way linked or a blocker to actually releasing 1.2, but doing that as a way to keep this issue a bit more visible, and the timeframe we need to do this migration also is somewhat similar as the planned timeline for 1.2)

because of potential issues with credits, it may be worth leaving this to the last minute https://github.com/scipy/scipy/issues/13109#issuecomment-733145469

**Comment by fangchenli** [comment]
> We currently have 4 build in Travis. Do all of these need to be on Travis?

GitHub Actions have SQL services. We could migrate the 3 builds that require databases to GitHub Actions.

**Comment by jorisvandenbossche** [comment]
> GitHub Actions have SQL services. We could migrate the 3 builds that require databases to GitHub Actions.

I think it would certainly be very welcome if someone can look into setting up database tests elsewhere (such as github actions)

**Comment by simonjayhawkins** [comment]
> (I am adding the 1.2 milestone for now. Not that it is in any way linked or a blocker to actually releasing 1.2, but doing that as a way to keep this issue a bit more visible, and the timeframe we need to do this migration also is somewhat similar as the planned timeline for 1.2)

The 1.2.x branch will be active past the deadline, so any changes needed as part of the migration will need to be backported. (so keeping this issue on the 1.2 milestone is fine.)

**Comment by fangchenli** [comment]
After #38344, the only build left on Travis is arm64.

**Comment by jreback** [comment]
ok i did this migration. let's see what happens.
