### ISSUE TITLE
ENH: implement Series.diff for nullable dtypes

### ISSUE THREAD

**Issue by arw2019** [pandas-dev/pandas#37779]
xref https://github.com/pandas-dev/pandas/issues/28385#issuecomment-572750633

**Comment by phofl** [comment]
Actually that was already implemented. Executing the example on master yields

```
0    <NA>
1       1
2       1
dtype: Int16
```

**Comment by mroeschke** [comment]
Since this was implemented, I think this issue should be good to close.
