### ISSUE TITLE
QST: Rolling pd.Grouper over N days

### ISSUE THREAD

**Issue by mattc-eostar** [pandas-dev/pandas#37793]
Starting from a desired date in a dataframe, can we group and sum the last 30 days and compare the prior 30 day period? And it would have to be days since this calculation could be done at any point in a month.

The first option below isn't very elegant, but I think gets to the right place. The second option using pd.Grouper, but chops off values during the group and produces different results and groups to the beginning of the period.

Any suggestions? Is there another function to try? Thanks!

```python
data = pd.DataFrame({
    'Timestamp': pd.date_range('8-11-2020', '10-12-20', freq='D'),
    'Qty': [4, 8, 5, 0, 6, 1, 0, 5, 4, 8, 4, 4, 8, 2, 6, 5, 3, 2, 4, 8, 0, 4,
       0, 9, 5, 3, 8, 2, 2, 4, 5, 7, 6, 7, 6, 5, 1, 6, 0, 1, 0, 5, 0, 2,
       3, 6, 5, 2, 5, 8, 3, 7, 8, 6, 4, 5, 8, 7, 7, 5, 9, 6, 6]
})
df = data.groupby(pd.Grouper(key='Timestamp', freq='D')).sum()[['Qty']].sort_index()
df = df.rolling('30D').sum().pct_change(1, freq='30D')
df.loc['10-12-2020']['Qty']

# or...

data \
    .groupby(pd.Grouper(key='Timestamp', freq='30D', label='right', closed='right')) \
    .sum()[['Qty']].sort_index().pct_change()
```
Using grouper begins the grouping of the Timestamp column from the earliest date to the latest. I would want to do the opposite.

**Comment by phofl** [comment]
Hey, have you asked your question on stackoverflow? That is probably a better place, if you do not think the behavior is erronoeus. Additionally your example is not self contained.

**Comment by mattc-eostar** [comment]
I have not yet. I wasn't aware the behavior had to erroneous to be labeled under "Usage Question".
I updated the question to be self-contained.

**Comment by phofl** [comment]
If you open an issue under steh question section, the first two points are

```
- [ ] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).
```

Additionally in https://pandas.pydata.org/pandas-docs/stable/development/maintaining.html?highlight=stackoverflow#issue-triage under point 6.

**Comment by mroeschke** [comment]
It appears that this is more of a usage question which as mentioned is more appropriate for Stackoverflow.

If you discover that the behavior you're looking for is buggy or could be an enhancement, feel free to reopen.
