### ISSUE TITLE
DOC: corrupted function signatures on stable

### ISSUE THREAD

**Issue by ivanovmg** [pandas-dev/pandas#37813]
#### Location of the documentation

Stable (v1.1.4) docs.
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_parquet.html

#### Documentation problem

On stable (v1.1.4) there are corrupted function signatures in docs for these functions at least.
 - pandas.DataFrame.to_stata
 - pandas.DataFrame.to_feather
 - pandas.DataFrame.to_parquet

![image](https://user-images.githubusercontent.com/41443370/99090999-ded11800-2601-11eb-903c-f7e600a82716.png)

Instead of named arguments followed by kwargs there are only kwargs.

There is no such problem on dev docs.
For example, here https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.to_parquet.html?highlight=to_parquet#pandas.DataFrame.to_parquet

#### Suggested fix for documentation

I though that probably decorator ``deprecate_kwargs`` was causing problems (the functions concerned are decorated),
but there is no such problem on dev docs, so the reason is not clear to me.

**Comment by jorisvandenbossche** [comment]
One other difference is the sphinx version with which both docs are built (3.1.1 vs 3.3.1), but no idea if that would be the cause.

**Comment by simonjayhawkins** [comment]
I'll milestone this as 1.1.5 for now

**Comment by simonjayhawkins** [comment]
locally I have built the docs for both 1.1.5 and 1.2.0rc0. both created using Sphinx 3.3.1. So it appears that this is not a release environment issue.

I think there is nothing more to do here, other than to check the function signatures before publishing the docs during the release process.

**Comment by jreback** [comment]
ok leaving it on this tag, pls close if ok.

**Comment by ivanovmg** [comment]
Closing as confirmed that the issue is not present anymore.
Will need to ensure that the function signatures are rendered correctly.
