### ISSUE TITLE
BUG: Slicing of Index with strings does not raise anymore when keys are not in Index

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#37810]
The following 
```
df2 = pd.DataFrame({"A": [1, 2, 3]}, index=['a', 'c', 'b'])
df2.loc['d':'e']
```

Should raise a ``KeyError``. This worked in the past (see #18531) but does not anymore. Question is if we should raise in ``slice_locs`` if start and end are equal or if we should do this after calling the function.

cc @jreback

**Comment by jorisvandenbossche** [comment]
This still raises a KeyError for me. With what version do you see something else? And can you show the output?

**Comment by phofl** [comment]
Sorry, i applied the loc to the DatetimeIndex, which did not raise on master (as expected). Mixed this up... You are right this still raises

**Comment by phofl** [comment]
cc @jorisvandenbossche 

Hm used the wrong example. The above raises, but when the index is monotonic, it does not raise.

```
df2 = pd.DataFrame({"A": [1, 2, 3]}, index=['a', 'b', 'c'])
df2.loc['d':'e']
```

This does not raise for me on master

**Comment by jorisvandenbossche** [comment]
As far as I know, that is the expected result, because it is a monotonic index, the exact labels in the slice don't need to be present in the index

**Comment by phofl** [comment]
Ah ok, did not know that. Then closing this again
