### ISSUE TITLE
BUG: DataFrame.from_dict gives me 3 duplicates

### ISSUE THREAD

**Issue by bergen288** [pandas-dev/pandas#37883]
- [x ] I have checked that this issue has not already been reported.

- [x ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

get_omdb_data function is defined to get movie information in JSON format from OMDB website and convert it to dataframe with  pandas ```DataFrame.from_dict``` function.  However, "Titanic" will give me 3 DF duplicates.  I also tried with "Godfather" which has only 1 record.

```python
def get_omdb_data(movie):
    """[get OMDB movie data in the world]

    Args:
        movie ([str]): [valid movie name]
    """
    movie_name = str(movie)
    middle_string = f'i={i_string}&apikey={apikey}&t='
    url = serviceurl + middle_string + movie_name
    try:
        uh = urllib.request.urlopen(url)
    except HTTPError as e:
        print("Sorry! Could not retrieve anything on {}".format(movie_name))
        return None
    except URLError as e:
        print("Failed to reach a server.")
        print("Reason:", e.reason)
        return None
    else:
        data = uh.read().decode()
        json_data = json.loads(data)
        if json_data['Response'] == 'True':
            print(
                "Retrieved data on {}.  Total {} characters read.".format(
                    movie_name, len(data)
                )
            )
            return json_data
        else:
            print("Sorry! {} can not be found.  Your spelling might be wrong".format(movie_name))
            return None

data = get_omdb_data('Titanic')
print(data)
df = pd.DataFrame.from_dict(data)
print(df)
```

#### Problem description

Retrieved data on Titanic.  Total 1051 characters read.

{'Title': 'Titanic', 'Year': '1997', 'Rated': 'PG-13', 'Released': '19 Dec 1997', 'Runtime': '194 min', 'Genre': 'Drama, Romance', 'Director': 'James Cameron', 'Writer': 'James Cameron', 'Actors': 'Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates', 'Plot': 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.', 'Language': 'English, Swedish, Italian, French', 'Country': 'USA, Mexico, Australia, Canada', 'Awards': 'Won 11 Oscars. Another 112 wins & 83 nominations.', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.8/10'}, {'Source': 'Rotten Tomatoes', 'Value': '89%'}, {'Source': 'Metacritic', 'Value': '75/100'}], 'Metascore': '75', 'imdbRating': '7.8', 'imdbVotes': '1,029,426', 'imdbID': 'tt0120338', 'Type': 'movie', 'DVD': 'N/A', 'BoxOffice': 'N/A', 'Production': '20th Century Fox, Lightstorm Entertainment, Paramount Pictures', 'Website': 'N/A', 'Response': 'True'}

     Title  Year  ... Website Response
0  Titanic  1997  ...     N/A     True
1  Titanic  1997  ...     N/A     True
2  Titanic  1997  ...     N/A     True

**[3 rows x 25 columns]**

#### Expected Output
Above has Titanic information in JSON format.  DataFrame.from_dict should give me 1 Titanic record, not 3.
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 2a7d3326dee660824a8433ffd01065f8ac37f7d6
python           : 3.8.2.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : English_United States.utf8

pandas           : 1.1.2
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.3
setuptools       : 41.2.0
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.18.1
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
numba            : None

</details>

**Comment by rhshadrach** [comment]
When a dictionary contains a mix of lists and scalars, pandas will assume the lists are to be expanded into rows and fills in the scalars as necessary:

```
data = {'a': 1, 'b': [1, 2, 3]}
df = pd.DataFrame(data)
print(df)
```

gives

```
   a  b
0  1  1
1  1  2
2  1  3
```

If your dictionary will always represent a single row, you can pack the values in lists.

```
data = {'a': 1, 'b': [1, 2, 3]}
data = {k: [v] for k, v in data.items()}
df = pd.DataFrame(data)
print(df)
```

gives

```
   a          b
0  1  [1, 2, 3]
```

**Comment by rhshadrach** [comment]
If this doesn't solve your issue, respond here and can reopen.

**Comment by bergen288** [comment]
Your suggestion helps.  Thanks.
