### ISSUE TITLE
BUG: df.str.contains(XX) return False when XX contains "+" character

### ISSUE THREAD

**Issue by TakuNishiumi** [pandas-dev/pandas#37888]
- [ y] I have checked that this issue has not already been reported.

#### Code Sample, a copy-pastable example

```python
df = pd.DataFrame(["ABC", "ABC+534"], index=["AA","BB"]).T
df["BB"].str.contains("ABC+5")
```
returns 
```
0    False
Name: BB, dtype: bool
```

#### Problem description
When I ran the `df.str.contains(XX)`, I found a new bug.
I run the below notebook, it returns False, despite it is definitely include keyword with in the cell.

**Comment by TakuNishiumi** [comment]
![pandas_bug+](https://user-images.githubusercontent.com/38071139/99219539-3a78ec80-2820-11eb-8f34-49f019edf428.png)

**Comment by mzeitlin11** [comment]
`df.str.contains` uses `regex=True` by default. Running 
```
df = pd.DataFrame(["ABC", "ABC+534"], index=["AA","BB"]).T
df["BB"].str.contains("ABC+5", regex=False)
```
returns 
```
0    True
Name: BB, dtype: bool
```

**Comment by TakuNishiumi** [comment]
@mzeitlin11,

Thank you!!
