### ISSUE TITLE
BUG: Empty dataframe with valid index object is not being read correctly via parquet reader

### ISSUE THREAD

**Issue by galipremsagar** [pandas-dev/pandas#37897]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
In[38]: df = pd.DataFrame(index=pd.RangeIndex(0, 10, 1))
In[39]: df.to_parquet('a')
In[40]: pd.read_parquet('a')
Out[40]: 
Empty DataFrame
Columns: []
Index: []
In[41]: df.to_parquet('a', index=True)
In[42]: pd.read_parquet('a')
Out[42]: 
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
In[43]: pd.read_parquet('a').index
Out[43]: Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')```
```

#### Problem description

When `index` is `None`/`True` parquet reader must retrieve only `RangeIndex` and not empty `RangeIndex` or `Int64Index`.

#### Expected Output
We should be able to get rangeIndex when we read from parquet file `a`.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]
INSTALLED VERSIONS
------------------
commit           : 67a3d4241ab84419856b84fc3ebc9abcbe66c6b3
python           : 3.7.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-53-generic
Version          : #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8
pandas           : 1.1.4
numpy            : 1.19.4
pytz             : 2020.4
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 49.6.0.post20201009
Cython           : 0.29.21
pytest           : 6.1.2
hypothesis       : 5.41.1
sphinx           : 3.3.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 0.8.4
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 1.0.1
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.51.2

</details>

This could be related to https://github.com/pandas-dev/pandas/issues/37896, but it appears the parquet reader is also not able to retrieve any Index at all when `index` is `None`. Hence filing this as a separate issue.

**Comment by jreback** [comment]
likely a pyarrow issue
cc @jorisvandenbossche

**Comment by jorisvandenbossche** [comment]
(thanks for the ping, will take a look later this week)

**Comment by jorisvandenbossche** [comment]
It's indeed a pyarrow issue, but not directly related to Parquet itself, but the pandas <-> pyarrow roundtrip is already failing for this corner case:

```
In [33]: df = pd.DataFrame(index=pd.RangeIndex(0, 10, 1))

In [34]: df
Out[34]: 
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [35]: df.shape
Out[35]: (10, 0)

In [36]: table = pa.table(df)

In [37]: table.to_pandas()
Out[37]: 
Empty DataFrame
Columns: []
Index: []

In [38]: table.to_pandas().shape
Out[38]: (0, 0)
```

I opened https://issues.apache.org/jira/browse/ARROW-10643 for this, contributions to fix this are always welcome!

Since it is an issue on the pyarrow side, closing this.

**Comment by wence-** [comment]
While the underlying pyarrow issue was fixed. The bug in the original report persists. `to_parquet/read_parquet` do not roundtrip `RangeIndex` correctly. I suspect this is because `to_parquet` doesn't preserve range indices:
```python
import pyarrow as pa
import pandas as pd
from io import BytesIO

buf = BytesIO()

df = pd.DataFrame({"a": [1, 2, 3]}, index=pd.RangeIndex(0, 3))
df.to_parquet(buf, index=True)
table = pa.parquet.read_table(buf)

pa_table = pa.table(df)

assert table == pa_table # False
```

**Comment by wence-** [comment]
parquet case is https://github.com/apache/arrow/issues/40743
