### ISSUE TITLE
CI upgrade pyupgrade to v2.7.4

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#37891]
This should just be a matter of changing the version number to v2.7.4 for pyupgrade in .pre-commit-config.yaml, and checking that all still passes:
```
pre-commit run pyupgrade --all-files
```
If it does, please open a PR to upgrade - else, report on any failures

**Comment by BAlmeidaS** [comment]
May I take this one?? This is gonna be my first contribution to Pandas. I know that I should have answered it with `take`, but I'm felling that I must justify myself.

**Comment by MarcoGorelli** [comment]
sure, go ahead!
