### ISSUE TITLE
BUG:BadZipFile CRC-32 for file 'docProps/core.xml' when  I use pandas read excel accord an error "BadZipFile CRC-32 for file 'docProps/core.xml' ".  Python

### ISSUE THREAD

**Issue by 530435745** [pandas-dev/pandas#37890]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here

```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by 530435745** [comment]
python version 3.7.0

**Comment by rhshadrach** [comment]
Looks like you're trying to use pandas `read_excel` to read an xml file, is that accurate?

**Comment by 530435745** [comment]
Thank for your reply, the fact is that I use pandas to_excel made an excel, and then I read it.  It likes orign content contains some error code made the xlsx file CRC-32 error. Just like \xa0 which can not use gbk encoding.

**Comment by 530435745** [comment]
> Looks like you're trying to use pandas `read_excel` to read an xml file, is that accurate?
Thank for your reply, the fact is that I use pandas to_excel made an excel, and then I read it. It likes orign content contains some error code made the xlsx file CRC-32 error. Just like \xa0 which can not use gbk encoding.

**Comment by rhshadrach** [comment]
Can you provide a reproducible example?

**Comment by mroeschke** [comment]
Going to close due to inactivity, but happy to reopen once we have a reproducible example

**Comment by biddls** [comment]
for peoples future reference the file might be corrupted and lost
try opening the excel file, if its badly corrupted it wont open and you'll have to pray you have a backup somewhere

A better error message would be nice
like there is an issue with X file it may be corrupted

**Comment by ghz20040102** [comment]
“Bad CRC-32 for file 'docProps/core.xml”
when I use pd.read_excel deal a large .xlsx file more then 300000 rows,
but it's ok when deal a .xlsx file only 1000 rows。why?
