### ISSUE TITLE
BUG: EA inplace add (and other ops) with non-EA arg broken

### ISSUE THREAD

**Issue by marco-neumann-by** [pandas-dev/pandas#37910]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas (`1.0.4`).

- [X] (optional) I have confirmed this bug exists on the master branch of pandas (`87247370c14629c1797fcf3540c6bd93b777a17e`).

---

#### Code Sample, a copy-pastable example

```python
import numpy as np
import pandas as pd

ser1 = pd.Series([1], dtype="Int64")
ser2 = pd.Series([1.0], dtype=np.float64)
ser1 += ser2
```

Note that the issue is NOT specific to the integer EA, but happens with all EAs that don't use NumPy dtypes.

#### Problem description

```
Traceback (most recent call last):
  File "bug.py", line 6, in <module>
    ser1 += ser2
  File ".../pandas/core/generic.py", line 11305, in __iadd__
    return self._inplace_method(other, type(self).__add__)  # type: ignore[operator]
  File ".../pandas/core/generic.py", line 11289, in _inplace_method
    if self.ndim == 1 and result._indexed_same(self) and result.dtype == self.dtype:
TypeError: Cannot interpret 'Int64Dtype()' as a data type
```

This is likely a fallout of #37508. See here:

https://github.com/pandas-dev/pandas/blob/87247370c14629c1797fcf3540c6bd93b777a17e/pandas/core/generic.py#L11283-L11292

There, the result dtype (which is a NumPy dtype in this case) is compared with the EA dtype. This raises the TypeError, because NumPy only allows comparing its dtype objects with "real" NumPy dtypes (and EAs don't provide NumPy-compatible dtypes).

#### Expected Output

Pass. I'm pretty sure that worked with `1.0.3` (the mentioned PR in question was backported to the `1.0.x` branch between the `1.0.3` and `1.0.4` release).

**Comment by jbrockmendel** [comment]
best guess is this can be fixed by changing `result.dtype == self.dtype` to `is_dtype_equal(result.dtype, self.dtype)`

**Comment by jorisvandenbossche** [comment]
@marco-neumann-by Thanks for the report! 

It seems we don't really have testing for inplace ops for EAs ..
