### ISSUE TITLE
BUG: SingleBlockManager' object has no attribute 'external_vaues' while using drop_duplicate

### ISSUE THREAD

**Issue by Jasonsey** [pandas-dev/pandas#37928]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
In [1]: import pandas as pd

In [2]: pd.__version
Out[2]: '1.1.3'

In [3]: df = pd.DataFrame({'a': [1,2,3,4,5], 'b': [3,3,3,3,3]})

In [4]: df.drop_duplicates()
```

#### Problem description

The following error occurred when executing the code above

```shell

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-c128d71b3023> in <module>
----> 1 df.drop_duplicates()

~/.conda/envs/test/lib/python3.6/site-packages/pandas/core/frame.py in drop_duplicates(self, subset, keep, inplace, ignore_index)
   5106
   5107         inplace = validate_bool_kwarg(inplace, "inplace")
-> 5108         duplicated = self.duplicated(subset, keep=keep)
   5109
   5110         result = self[-duplicated]

~/.conda/envs/test/lib/python3.6/site-packages/pandas/core/frame.py in duplicated(self, subset, keep)
   5245
   5246         vals = (col.values for name, col in self.items() if name in subset)
-> 5247         labels, shape = map(list, zip(*map(f, vals)))
   5248
   5249         ids = get_group_index(labels, shape, sort=False, xnull=False)

~/.conda/envs/test/lib/python3.6/site-packages/pandas/core/frame.py in <genexpr>(.0)
   5244             raise KeyError(diff)
   5245
-> 5246         vals = (col.values for name, col in self.items() if name in subset)
   5247         labels, shape = map(list, zip(*map(f, vals)))
   5248

~/.conda/envs/test/lib/python3.6/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5137             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5138                 return self[name]
-> 5139             return object.__getattribute__(self, name)
   5140
   5141     def __setattr__(self, name: str, value) -> None:

~/.conda/envs/test/lib/python3.6/site-packages/pandas/core/series.py in values(self)
    536                '2013-01-03T05:00:00.000000000'], dtype='datetime64[ns]')
    537         """
--> 538         return self._mgr.external_vaues()
    539
    540     @property

AttributeError: 'SingleBlockManager' object has no attribute 'external_vaues'
```

#### Expected Output
No error occured
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.6.12.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.1.0
Version          : Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : zh_CN.UTF-8
LOCALE           : zh_CN.UTF-8

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : None
pytest           : 6.1.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : 0.10.1
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.16.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : 1.3.20
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by ma3da** [comment]
Hi, this has since been corrected.
```
>>> import pandas as pd
>>> pd.__version__
'1.1.4'
>>> df = pd.DataFrame({'a': [1,2,3,4,5], 'b': [3,3,3,3,3]})
>>> df.drop_duplicates()
   a  b
0  1  3
1  2  3
2  3  3
3  4  3
4  5  3
```
