### ISSUE TITLE
BUG: style.background_gradient works in jupyter but not in Github

### ISSUE THREAD

**Issue by alexiska** [pandas-dev/pandas#37936]
The bakground color gradient works fine in jupyter but when I upload it to Github the color disappears. Is there anyway I can fix this?

From jupyter
![image](https://user-images.githubusercontent.com/38601205/99515458-47671e80-298d-11eb-9cba-1c05ed5f0862.png)

After uploading to Github
![image](https://user-images.githubusercontent.com/38601205/99515685-901ed780-298d-11eb-9287-5e6bed9693ea.png)

**Comment by MarcoGorelli** [comment]
Hi @alexiska 

If I've understood correctly, this sounds like an issue in how GitHub renders notebooks rather than in pandas?

**Comment by TomAugspurger** [comment]
GitHub doesn't render CSS or execute javascript in notebooks. IIRC it was a security concern.

**Comment by MarcoGorelli** [comment]
FWIW, it might display correctly if you view it with nbviewer

**Comment by alexiska** [comment]
Hi @MarcoGorelli 
nbviewer seems to work. I was thinking thinking if I could do something to enable the colors if someone check out my repo in the future.
