### ISSUE TITLE
STYLE: fail on pd.testing direct usage

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#37957]
`pd.testing.assert_series_equal(result, expected)`

should fail style checks, rather we want `tm.assert_series_equal`

we need to update any usages in the codebase as well as add this to the pre-commit checks.

**Comment by inspurwusixuan** [comment]
Hi @jreback, can I take this? :)

**Comment by cjlynch278** [comment]
Hello, I'm going to try to fix this issue. I'll submit a pull request linking the issue if I'm able to complete it within the next week, otherwise I'll post an update here
