### ISSUE TITLE
„case-when“ function is missing?

### ISSUE THREAD

**Issue by pandasnew** [pandas-dev/pandas#37962]
I only started working with pandas a few weeks ago. What I often miss is a case-when-function. Here I always use the numpy equivalent np.where(). 
Is there a case-when-function in pandas not? If there is, I would like to add this functionality.

**Comment by phofl** [comment]
Hi,

have you looked at ``where`` and ```loc``?

**Comment by pandasnew** [comment]
You mean there where-function from numpy?

**Comment by phofl** [comment]
No, pandas has a where function

**Comment by pandasnew** [comment]
But the pandas wher-function is similar to filter and and not like case when condition, then , else. Right?

**Comment by jreback** [comment]
there is an example just added https://dev.pandas.io/docs/user_guide/indexing.html

about using np.select which is like case-when

**Comment by rhshadrach** [comment]
`mask` can also be used to get numpy where like behavior:

```
df = pd.DataFrame({'a': [1, 2, 3, 4], 'b': [5, 6, 7, 8]})
mask = df['a'] >= 2
df['c'] = df['a'].mask(mask, df['b'])
```

**Comment by jreback** [comment]
closing this is fully documented
