### ISSUE TITLE
ENH: bfloat16 when available?

### ISSUE THREAD

**Issue by mingwugmail** [pandas-dev/pandas#37969]
Same numpy bfloat16 feature request for pandas:

https://github.com/numpy/numpy/issues/17809

Hi,

I saw NEP 41 Status: | Accepted

https://github.com/numpy/numpy/blob/master/doc/neps/nep-0041-improved-dtype-support.rst

I'm just wondering when will bfloat16 be available in numpy?

For some ML problems, this will reduce the memory requirement by half (or process 2x more data), can we give this high priority?

Thanks.

**Comment by TomAugspurger** [comment]
We can't support this until after NumPy or (or maybe Apache Arrow) introduced it. Let's close this until we can actually take action on it.

**Comment by jreback** [comment]
see also https://github.com/pandas-dev/pandas/issues/9220
