### ISSUE TITLE
BUG: ImportError: cannot import name 'EmptyDataError' from 'pandas.io.common'

### ISSUE THREAD

**Issue by pisulski** [pandas-dev/pandas#37978]
I upgraded pandas and python version
python          3.8.6
numpy            1.19.4
pandas           1.1.4
pip              20.2.4

When I try:

`import pandas as pd
from pandas.io.common import EmptyDataError
`

I have  error:

`ImportError: cannot import name 'EmptyDataError' from 'pandas.io.common' (/xxx/xxx/enviroments/py3_8_env/lib/python3.8/site-packages/pandas/io/common.py)`

**Comment by jreback** [comment]
error moved to `pandas.errors` quite a while ago; you are referencing an internal module.
