### ISSUE TITLE
Should FilePathorBuffer use os.PathLike instead of pathlib.Path?

### ISSUE THREAD

**Issue by willfrey** [pandas-dev/pandas#37979]
The [documentation for `pandas.read_csv(...)`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) states that it can support anything that adheres to the `os.PathLike` protocol, but the definition of `FilePathOrBuffer` is too strict.

https://github.com/pandas-dev/pandas/blob/08e4baf13005d33136608bd4e6e15f6b38f50887/pandas/_typing.py#L138

where `Path` is a `pathlib.Path` object.

Could this be changed to use `os.PathLike[str]` or just `os.PathLike`?

```py3
from os import PathLike

FilePathOrBuffer = Union["PathLike[str]", FileOrBuffer]
```

`PathLike` is in quotes because `PathLike` only supports `__class_getitem__` for Python 3.9 and later and `PathLike` alone might be too broad, assuming you don't want to support byte-encoded paths.

Thanks!

**Comment by twoertwein** [comment]
Replacing `pathlib.Path` with `os.PathLike[str]` should definitely work! Most (all?)  IO calls go through `get_handle` which internally calls `stringify_path` which converts all `os.PathLike[str]` using `__fspath__` to a string. Unless you add a decode function to stringify_path, I wouldn't add `os.PathLike[bytes]`.

I think we already have tests for non-`pathlib.Path` PathLike objects.

**Comment by AbhirajHinge** [comment]
From what I gathered through @twoertwein comment, the `PathLike[str]` change will bring the definition of `FilePathorBuffer` closer to being in-line with the [documentation for pandas.read_csv(...)](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html). Should I go ahead and make that change?

**Comment by twoertwein** [comment]
yes, feel free to make the change.

**Comment by Abhi-H** [comment]
Okay, will make a PR soon. Setting up my dev environment currently.
