### ISSUE TITLE
DOC: DataFrame.last() needs the index to be sorted to deliver the expected results

### ISSUE THREAD

**Issue by alejsm** [pandas-dev/pandas#38000]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.last.html

#### Documentation problem

For the method to work it is needed that the **_DatetimeIndex_ of the dataframe is sorted**, otherwise it will notwork.
Example:
```
import pandas as pd

df = pd.DataFrame({
    'Date': ['2020-01-03', '2020-01-02', '2020-01-05', '2020-01-01', '2020-01-04'],
    'Value': [1, 2, 3, 4, 5]
    })

df['Date'] = pd.to_datetime(df.Date)
df.set_index('Date', inplace=True)
#df.sort_index(inplace=True) This line is needed to make it work
df.last('3D')
```
returns all the rows in the DataFrame
```
                   Value
Date	
2020-01-03	1
2020-01-02	2
2020-01-05	3
2020-01-01	4
2020-01-04	5
```

#### Suggested fix for documentation

It should be mentioned that for the _last()_ method to work, the **_DatetimeIndex_ must be sorted**, or the user may think that there is a bug in the function.

**Comment by phofl** [comment]
Hi thanks for your report. You are right, the documentation should be better here. Additionally I am wondering if we should raise when the Index is unsorted. 

PS: Could you adjust your title to reflect the problem a bit better?

**Comment by aflah02** [comment]
Can I take up this issue and add this to the documentation? @phofl

**Comment by alejsm** [comment]
Yes, sure!

**Comment by aflah02** [comment]
Oh thanks @alejsm

**Comment by aflah02** [comment]
Do I need to just add the part in the documentation or also add a error when the index is not sorted, if yes, what should be the type of the error?
