### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by Jacques2101** [pandas-dev/pandas#38016]
Hi i have a huge problem and I suppose it could be a bug but not sure. 

```
def volat(prices, n):
    n_years = prices.last_valid_index()-pd.DateOffset(years=n)
    return 100*np.sqrt(52)*prices[n_years:].asfreq('W-FRI', method='ffill').pct_change().std()


################### METHOD 1 ###################
table = (base_corr
         .query("classification_produit=='Sans classification'")
         [['date', 'gestionnaire', 'nom_de_produit', 'code_isin_part',
           'classification_produit', 'vl', 'collecte', 'nbre_part', 'actif_net_part']]
         .pivot(columns='date',
                index=['gestionnaire', 'nom_de_produit', 'code_isin_part', 'classification_produit'],
                values=['vl', 'collecte', 'nbre_part', 'actif_net_part'])
         .apply([
             lambda x: volat(x.vl, 3),
         ], axis=1)
         .set_axis([
             'volat 3 ans'
         ],
             axis='columns')
         )

table.loc[(slice(None),slice(None),'FR0011026905')] # part of Result from method 1


################### METHOD 2 ###################
volat(base.query("code_isin_part=='FR0011026905'").set_index('date')['vl'], 3)  # Result from method 2


################### METHOD 3 ###################
(base_corr
     .query("code_isin_part=='FR0011026905'")
     [['date', 'gestionnaire', 'nom_de_produit', 'code_isin_part',
       'classification_produit', 'vl', 'collecte', 'nbre_part', 'actif_net_part']]
     .pivot(columns='date',
            index=['gestionnaire', 'nom_de_produit', 'code_isin_part', 'classification_produit'],
            values=['vl', 'collecte', 'nbre_part', 'actif_net_part'])
     .apply([
         lambda x: volat(x.vl, 3),
     ], axis=1)
     .set_axis([
         'volat 3 ans'
     ],
         axis='columns')
     )
```

and the output is : 
```
RESULT FROM METHOD 1  (the wrong one) : 

			volat 3 ans
FIDEAS CAPITAL SAS	SICAV DES OLIVIERS	Sans classification	0.05

RESULT FROM METHOD 2 :
7.922765211671436

RESULT FROM METHOD 3 :
				volat 3 ans
FIDEAS CAPITAL SAS	SICAV DES OLIVIERS	FR0011026905	Sans classification	7.92

```

From my point of view I should get exactly the same answer (method 2 & 3 are alright but not method 1). 
I don't know why this is not the case. 
I need maybe to add that base_corr is a huge database (10_892_693 rows × 12 columns) with dailies and weekly data that why I convert each series to weekly data to make it possible to annualize the volatility figures (with np.sqrt(52) multiplication). 

INSTALLED VERSIONS
------------------
commit           : 67a3d4241ab84419856b84fc3ebc9abcbe66c6b3
python           : 3.8.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.1.0
Version          : Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.4
numpy            : 1.19.4
pytz             : 2020.4
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: 0.9.0
bs4              : 4.9.3
bottleneck       : None
fsspec           : 0.8.4
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : 2.0.0
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.3
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 0.16.1
xlrd             : 1.2.0
xlwt             : None
numba            : 0.51.2

</details>

**Comment by Jacques2101** [comment]
I found my error. It is linked with asfreq(). For this particular series, the frequency is first month then weekly (based on Wednesday day and not Friday). 
So with asfreq() I get a lot of nan data. When I change my function to : 
```
def volat(prices, n):
    n_years = prices.last_valid_index()-pd.DateOffset(years=n)
    return 100*np.sqrt(52)*prices[n_years:].ffill().asfreq('W-FRI', method='ffill').pct_change().std()
```

It seems to work ok but what I not understand is why method 3 still give me the correct figure ?

**Comment by MarcoGorelli** [comment]
Hi @Jacques2101 

Thanks for the report - please see [here](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) for how to write a minimal reproducible bug report, if you make a reproducible example we can take a look

**Comment by MarcoGorelli** [comment]
Closing for now but  if you make a reproducible example we can take a look
