### ISSUE TITLE
BUG: df.rename raises when multiindex has duplicates

### ISSUE THREAD

**Issue by GYHHAHA** [pandas-dev/pandas#38015]
```python
>>> idx = pd.Index([('A','cat'),('B','cat'),('B','cat')])
>>> df = pd.DataFrame(index=idx)
>>> df.rename(index={'A':'Apple'}, level=0)
ValueError: non-broadcastable output operand with shape (1,1) doesn't match the broadcast shape (1,2)
```

**Comment by rhshadrach** [comment]
Thanks for the report @GYHHAHA! Further investigations and PRs are certainly welcome.

**Comment by GYHHAHA** [comment]
Hi, where this function tested? I think the error is related to this, but can't find test case.
https://github.com/pandas-dev/pandas/blob/54f23e8f1f02c03aa3e166bda88e9d5b051f1054/pandas/_libs/index.pyx#L572
And also confused about `_codes_to_ints` func, any explanation about this bit computation? Thanks.
https://github.com/pandas-dev/pandas/blob/1cc030e984944bf4ca7ea5aec552dca55a117204/pandas/core/indexes/multi.py#L107

**Comment by mroeschke** [comment]
It appears this work on master now, I think. Could use a test

```
In [1]: >>> idx = pd.Index([('A','cat'),('B','cat'),('B','cat')])
   ...: >>> df = pd.DataFrame(index=idx)
   ...: >>> df.rename(index={'A':'Apple'}, level=0)
Out[1]:
Empty DataFrame
Columns: []
Index: [(Apple, cat), (B, cat), (B, cat)]
```

**Comment by andrewwoood** [comment]
I was looking to take this on as my first open source contribution, but when I ran the code locally I'm running into the error mentioned initially: 
```
>>> idx = pd.Index([('A','cat'),('B','cat'),('B','cat')])
>>> df = pd.DataFrame(index=idx)
>>> df.rename(index={'A':'Apple'}, level=0)
ValueError: non-broadcastable output operand with shape (1,1) doesn't match the broadcast shape (1,2)
```


In the case that I'm doing this incorrectly, could I take this issue on? @mroeschke, when you mention that it needs tests, does that mean running it locally with different values and verifying correctness? Or are there unit tests that I need to run somewhere? I'm not so clear on the process, sorry for asking so many questions.

**Comment by mroeschke** [comment]
@andrewwoood I was running this on the master branch, and it appeared to have worked. This code snippet would need to be added as a unit test in the pandas testing suite.

**Comment by andrewwoood** [comment]
take
