### ISSUE TITLE
QST: Pandas without MKL?

### ISSUE THREAD

**Issue by flcong** [pandas-dev/pandas#38023]
I build a small application that uses `pandas` and use `pyinstaller` to build `.exe` file. Since the default `numpy` uses MKL, which results in very large folder. I use `conda install conda-forge nomkl numpy` to install numpy without MKL. Then I install pandas using `conda install pandas`. The program works well. However, after I convert the code to `.exe` file. I encounter the following error from pandas:
```
Traceback (most recent call last):
  File "\\VBoxSvr\twitterscraper\twitter_scraper_tweepy_Vader_V4.py", line 21, in <module>
  File "c:\users\XXXX\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "pandas\__init__.py", line 16, in <module>
ImportError: Unable to import required dependencies:
numpy: cannot import name '_mklinit' from partially initialized module 'mkl' (most likely due to a circular import) (C:\Users\XXXX\Documents\twitterscraper\dist\twitter_scraper_tweepy_Vader_V4\mkl\__init__.pyc)
[2136] Failed to execute script twitter_scraper_tweepy_Vader_V4
```
I'm not sure why, but it seems that pandas still requires MKL. I wonder if there is a version of pandas that does not require MKL?

I also tried to install pandas using `conda install conda-forge::blas=*=openblas pandas`. The problem remains.

Info of my system:

* OS: Win10
* Python: 3.8.3 (installed from Miniconda)
* Numpy: 1.19.4 (installed from `conda-forge` together with `nomkl` to use blas.
* Pandas: 1.1.3 (installed using `conda install pandas` or `conda install conda-forge::blas=*=openblas pandas`)

**Comment by jreback** [comment]
pandas does not use mkl directly, your issue is with pyinstaller.
