### ISSUE TITLE
STYLE use types_or in pre-commit

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#38022]
[pre-commit 2.9 adds support for types_or](https://github.com/pre-commit/pre-commit/releases/tag/v2.9.0), which would help clear up some of the less readable regexes like `\.(py|pyx|rst)$`, replacing them with `types_or: [python, cython, rst]`

**Comment by rkc007** [comment]
Can I work on this issue?

**Comment by rkc007** [comment]
take

**Comment by MarcoGorelli** [comment]
sure! the [pre-commit docs](https://pre-commit.com/) may be useful here. You'll need to specify `minimum_pre_commit_version` somewhere and update the versions in requirements.txt and environment.yml. If any hook defines `types` upstream, it may be necessary to overwrite it with `types: [text]`. Anyway, if you open a PR I'll correct you if it's not right.

**Comment by MarcoGorelli** [comment]
Hi @rkc007 - I've unassigned you so others can take this up if they wish, but if you're stil interseted in working on it do let me know and I'll re-assign you

**Comment by rkc007** [comment]
Hi @MarcoGorelli  - Sorry I wasn't able to work on this issue as I was working on another issue #32073 and it is now approved. So, I would love to work on this issue now.

I have a quick doubt regarding this issue. I saw the documentation and your PR (https://github.com/pre-commit/pre-commit/pull/1677) on the repository. Does the change here is like this - 

`types: [cython]`

will be converted to 

`types_or: [cython]`

but what about the ` files: \.pxi\.in$` ? Does this too change? If you could give an example from this figure, it would be great.
![image](https://user-images.githubusercontent.com/22396042/101298522-fb710200-37f3-11eb-9322-bbc2d7cb56b2.png)

Thanks.

**Comment by MarcoGorelli** [comment]
Hey - no worries, I've re-assigned you :smile: 

For flake8, we run it with different options on each type of file, so I'd leave it as it is.

For isort, we could overwrite `types` and then use `types_or`:
```
types: [text]  # overwrite types[python]
types_or: [python, cython]
```

For some of the local hooks, we can `types_or` instead of regexes like `files: \.(py|pyx|pxd|pxi)$`

----

To check what type a file is, you can use [identify](https://github.com/pre-commit/identify). E.g.:
```console
$ identify-cli pandas/_libs/tslibs/conversion.pxd
["cython", "file", "non-executable", "text"]

$ identify-cli pandas/_libs/tslibs/parsing.pyx
["cython", "file", "non-executable", "text"]

$ identify-cli pandas/io/formats/info.py 
["file", "non-executable", "python", "text"]
```

**Comment by rkc007** [comment]
Thank you @MarcoGorelli for your guidance. I have created a PR for this issue. Can you please review it and let me know if I need to change anything in the PR.
