### ISSUE TITLE
the .corr method filter the columns to only keep the numerical columns before apply any corr calclation.

### ISSUE THREAD

**Issue by z7ye** [pandas-dev/pandas#38031]
https://github.com/pandas-dev/pandas/blob/67a3d4241ab84419856b84fc3ebc9abcbe66c6b3/pandas/core/frame.py#L8127

the .corr method filter the columns to only keep the numerical columns before apply any corr calclation. one issue with that is if I would like to apply a callable method _cramer_v to calc the correlation between categorical features, the .corr will skip it. I think for callable method, it should not skip any type of columns

**Comment by rhshadrach** [comment]
Is it too onerous in your situation to use `astype` on the columns? If so, an example would help.

Creating two different behaviors (drop vs keep non-numerics) based on function argument seems less desirable from an API standpoint. Also `corr` is different from other methods where there is a `numeric_only` in that it can really only operate on numeric data. It seems to me that exposing a `numeric_only` argument would be of very limited use.

**Comment by mroeschke** [comment]
Thanks for the request. Agreed that converting the data types beforehand would be preferable than adding extra logic to `corr/cov`

Since this enhancement request hasn't gotten much traction from the community or the other core devs, going to close, but happy to reopen if there is revived interest.
