### ISSUE TITLE
speed up apply calculation 

### ISSUE THREAD

**Issue by Jacques2101** [pandas-dev/pandas#38036]
Hi, I have a huge database with multi index ((8832, 14384)) from which I calculate some statistics with code like that : 

```python
(df
 .apply([
     lambda x: ...,  
     lambda x: ...,
     lambda x: ...,
     lambda x: ...,
     lambda x: ...,

     lambda x: ...,
     lambda x: ...,
     lambda x: ...,
     lambda x: ...,
     lambda x: ...,
     lambda x: ...,

     lambda x: ...,
     lambda x: ...,
     lambda x: ...,
     lambda x: ...,

     lambda x: ...,
     lambda x: ...,

     lambda x: ...,
     lambda x: ...,
 ], axis=1)
)
```
My problem is that it took **more than 5 min** to do the calculation (!!!!). 
Is there a way to do it better ? Multiprocessing but don't know how to structure it ? 

Thx

**Comment by rhshadrach** [comment]
Usage questions should be asked on StackOverflow first. Has this question been asked there? If so, please add a link to the question.

**Comment by Jacques2101** [comment]
No. I did not post my question elsewhere. I will do it now but if you have some solution in the meantime, I will take it of course...
thx
