### ISSUE TITLE
BUG: BDay() offsetting not behaving as expected

### ISSUE THREAD

**Issue by mhorsley30896** [pandas-dev/pandas#38046]
```python
import pandas as pd
from pandas.tseries.offsets import CDay, BDay

idx = pd.bdate_range("2010/02/01","2010/02/15", freq='6H')

t1 = idx + BDay(offset=pd.Timedelta(3, unit='H'))

t2 = idx + CDay(offset=pd.Timedelta(3, unit='H'))

t1.equals(t2)

False
```

#### Problem description

BDay does not seem to be offsetting when a timedelta is supplied.

#### Expected Output

True

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.6.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-514.6.1.el7.x86_64
Version          : #1 SMP Wed Jan 18 13:06:36 UTC 2017
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C
LOCALE           : None.None

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.16.1
pandas_datareader: 0.9.0
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.8.3
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : 1.3.20
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.51.2

</details>

**Comment by phofl** [comment]
Hi,

thanks for your report. This returns ``True`` on master

```
/home/developer/PycharmProjects/pandas/pandas/core/arrays/datetimes.py:700: PerformanceWarning: Non-vectorized DateOffset being applied to Series or DatetimeIndex
  warnings.warn(
True
```

Would you like to contribute a test for this to avoid regression?

**Comment by mhorsley30896** [comment]
Something like?

```
def test_bday_ignores_timedeltas():
    idx = pd.bdate_range("2010/02/01","2010/02/15", freq='6H')
    t1 = idx + BDay(offset=pd.Timedelta(3, unit='H'))
    t2 = idx + CDay(offset=pd.Timedelta(3, unit='H'))
    assert t1.equals(t2), 't1 should always equal t2 as we should ignore timedeltas'
    pass
```

**Comment by phofl** [comment]
Yes essentially, it would be a bit better if you could define expected (t2) without calling a function

**Comment by theoniko** [comment]
I tried the code snippet from mhorsley30896 with latest master (1.2.0.dev0+1469.g122ae441d) and it returned True. I have not worked in python but i will try to add the test above.

**Comment by theoniko** [comment]
take

**Comment by theoniko** [comment]
Hello @phofl 
Could you please review pr #38324?
