### ISSUE TITLE
BUG: Changing values in copied dataframe manipulates the original dataframe

### ISSUE THREAD

**Issue by bastingup** [pandas-dev/pandas#38060]
Hey everybody,

so I ran into something odd last night.
I had two dataframes: dataframe_original and the dataframe_copy.

Whenever I changed the values in a column of dataframe_copy the code changed the values in dataframe_original.
I had the original one as a backup and assign it every iteration to a local copy.
I displayed the output of the original dataframe (so not the one I attempted to change) but it showed the changes were made on the original one, not the copied one. For assigning the original frame to the copied one I tried all these approaches:

1) local_df.loc[local_df.index, local_df.columns] = df.tail(l)
2) local_df = pd.DataFrame(data = df.tail(l))
3) local_df = pd.DataFrame(df.tail(l))
4) local_df = df

But no matter what, it did not actually copy the frame, it just created a reference to the original one.
I assume this is not how the constructor is supposed to work?

Thanks for your time.

---
#### Code Sample
```
import pandas as pd

#### Data
d = {'col1': [1, 1, 1], 'col2': [1, 1, 1], 'col3': [1, 1, 1]}
df = pd.DataFrame(data = d)

#### Limits for the iteration
xr = 2
yr = 2

#### Value to add
v = 1

#### Length
l = 2

#### Loop
local_df = pd.DataFrame(df.tail(l))
list_of_df = []
for x in range(xr):
    for y in range(yr):
        local_df.loc[local_df.index, local_df.columns] = df.tail(l)
        local_df["col1"] = local_df["col1"] + v
        list_of_df.append(local_df)
        display(df)
```

[
<img width="834" alt="Screenshot 2020-11-25 at 11 52 11" src="https://user-images.githubusercontent.com/28649176/100218656-4f870700-2f15-11eb-9f10-8044a666df66.png">
](url)

<img width="858" alt="Screenshot 2020-11-25 at 11 57 53" src="https://user-images.githubusercontent.com/28649176/100218776-780f0100-2f15-11eb-876c-98dec3270df5.png">

Versions & Sys:
macOS Mojave 10.14.6
Python 3.7.3
Pandas 1.1.4
ipython 7.4.0
_anaconda_depends 2019.03
anaconda-client .7.2
anaconda-navigator 1.9.7
anaconda-project 0.8.2

**Comment by Jeitan** [comment]
I think this is not a bug - though it may seem like pd.DataFrame() is making a completely new DataFrame, it likely is not (and this has been the case for awhile).  Try doing local_df = df.tail(l).copy() instead.

**Comment by bastingup** [comment]
Hey and thanks! Yeah, we actually did it that way now.
Might be possible for pd.DataFrame(), but even with df_copy = df?
I thought that direct assignment would have created a new variable instead of a reference. I mean, totally possible that I was wrong about this the whole time and just never ran into a situation like this.

**Comment by Jeitan** [comment]
I'm not a pandas dev but I'm 99.9% positive that df_copy = df will _not_ make a copy.

**Comment by jreback** [comment]
> local_df = df

is a reference in python. if you want a copy use `.copy()`.
