### ISSUE TITLE
DOC: Include missing holiday observance rules

### ISSUE THREAD

**Issue by Jeitan** [pandas-dev/pandas#38067]
#### Location of the documentation

[Timeseries Holiday](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#holidays-holiday-calendars) section in doc/source/user_guide/timeseries.rst.

#### Documentation problem

The list of available holiday observance rules is incomplete - several available observances are missing.

#### Suggested fix for documentation

The following observances should be added to the documentation because they are already available:

- next_workday
- previous_workday
- before_nearest_workday
- after_nearest_workday

Before I examined `holiday` via TAB-completion I had written my own version of weekend_to_monday; others may likewise re-invent these wheels if they're not documented.

(Updated to remove "weekend_to_monday" because it does the same thing as "next_monday")

**Comment by Jeitan** [comment]
I was poking at this, and discovered that `weekend_to_monday` actually does the same thing that `next_monday` does.  I think I had taken "next Monday" too literally and thought that that would move even other weekdays to Monday.  However, the code is actually the same (except for the order in which the weekday is checked).  So one of them should probably go, and whichever one survives live in the documentation (personally, I think "weekend_to_monday" is clearer...).

**Comment by leonarduschen** [comment]
https://github.com/pandas-dev/pandas/blob/da5f91438e0a632eee841c8775ed20e3ab7c2744/pandas/tseries/holiday.py#L15

We should probably remove `next_monday` since it's misleading as it doesn't do anything if the current day is not Saturday or Sunday.

**Comment by leonarduschen** [comment]
There are room for improvement for the docstring as well. For example:

Docstring of `before_nearest_workday`:
https://github.com/pandas-dev/pandas/blob/65319af6e563ccbb02fb5152949957b6aef570ef/pandas/tseries/holiday.py#L111 

Docstring of `after_nearest_workday`:
https://github.com/pandas-dev/pandas/blob/65319af6e563ccbb02fb5152949957b6aef570ef/pandas/tseries/holiday.py#L118

**Comment by dontgoto** [comment]
take
