### ISSUE TITLE
ENH: pd.link([*dataframes], how='left')

### ISSUE THREAD

**Issue by bergkvist** [pandas-dev/pandas#38075]
#### Is your feature request related to a problem?
When working with data that contains a lot of references, pd.merge seems to be the best approach.

If you need to follow more than 1 reference to get where you need, this quickly gets verbose.

To solve this problem, I suggest a higher level wrapping for merge, that is focused around being able to follow multiple references. Some potential names are:
```py
pd.link([*dataframes])  # The one I use in the examples below
pd.follow([*dataframes])
pd.traverse([*dataframes])
```

#### Describe the solution you'd like

Example implementation below:

```py
from functools import reduce
import pandas as pd

def link(dataframes, how='left'):
    """
    Follow references in between pandas dataframes and series.
    
    Parameters:
    -----------
    `values` is an iterable of pd.DataFrame or pd.Series.
    `how` decides how the internal pd.merge will be performed.
    """
    def _link(x, y):
        # Support for passing in pandas series
        if type(x) == pd.Series:
            x = x.to_frame()
        if type(y) == pd.Series:
            y = y.to_frame()
        return pd.merge(x, y, left_on=list(x.columns), right_index=True, how=how)[y.columns]
    return reduce(_link, dataframes)
```

### Example

![image](https://user-images.githubusercontent.com/410028/100298345-2efc9280-2f91-11eb-808c-2f8b684977bb.png)

#### And for the variables used:

<details><summary>user_to_session_id</summary>

![image](https://user-images.githubusercontent.com/410028/100298042-5e5ecf80-2f90-11eb-9598-0be86835d54c.png)

</details>

<details><summary>session_id_to_article_id</summary>

![image](https://user-images.githubusercontent.com/410028/100298111-8bab7d80-2f90-11eb-9172-b871ecd25b28.png)

</details>

<details><summary>article_id_to_price_usd</summary>

![image](https://user-images.githubusercontent.com/410028/100298221-d6c59080-2f90-11eb-8bf5-dfb804160f16.png)

</details>

---

<details><summary>Code</summary>

```python
sessions = pd.DataFrame({
    'session_id': ['a', 'b', 'c', 'd'],
    'user': ['jack', 'jack', 'john', 'steve'],
})
user_to_session_id = sessions.set_index('user')

orders = pd.DataFrame({
    'session_id': ['a', 'b', 'c', 'c'],
    'article_id': ['x', 'x', 'y', 'x']
})
session_id_to_article_id = orders.set_index('session_id')

articles = pd.DataFrame({
    'article_id': ['x', 'y'],
    'price_usd': [25, 50]
})
article_id_to_price_usd = articles.set_index('article_id')

link([
    user_to_session_id,
    session_id_to_article_id,
    article_id_to_price_usd
])
```

</details>

### Notes
This could be created to only support pd.Series - but then this prevents us from merging multi-index frames/series. For merging multi-index data, we need a multi-column frame to match the index.

**Comment by jreback** [comment]
not averse to a doc-string example / docs example but -1 on adding this generally 

we already have a tremendous amount of api

it's possible we could accept a list of frames in pd.merge to do this - would be +0 on that

**Comment by bergkvist** [comment]
@jreback I imagine a significant difference between my proposed pd.link and pd.merge with list arguments - is that pd.link drops all columns other than the index of the first dataframe and the columns of the last dataframe.

I probably wouldn't be using the pd.merge-list personally if this was added.

**Comment by jorisvandenbossche** [comment]
I agree with @jreback that this seems (at first sight) a rather specific use case, probably too specific to add to pandas (eg the fact that it is limited to single column dataframes). 
Or do you know of other languages/tools having such a method?

**Comment by bergkvist** [comment]
You can also use multi-column dataframes with multi-index dataframes as well - athough I imagine this is going to be a less common use-case (none the less something I've actually needed to do). I've noticed that dropping all the columns not needed for linking yields much better performance as well.

I'm working with CIM-data ([Common Information Model (electricity)](https://en.wikipedia.org/wiki/Common_Information_Model_(electricity))), which is practically drowning in references. See the image below as an example:

![image](https://user-images.githubusercontent.com/410028/100372299-54c57e00-3009-11eb-8f33-3483f7d952b5.png)

And now, imagine that your goal is to find a nominalVoltage for every ConnectivityNode. Filled arrow head means the reference is always there. Empty arrow head means the reference is only sometimes there.

You can think of every "box"/"class" as separate pandas dataframes. The PowerTransformerEnd dataframe will have a column named PowerTransformer with uuids that can be used for merging with the PowerTransformer dataframe.

Using the proposed `pd.link`, the code to solve this problem was massively simplified - and a lot more readable (compared to the version using pd.merge directly)

**Comment by bergkvist** [comment]
Although this might be a "niche function", I've still found a use for it in more than 170 places across 18 different files (out of ~34 files in total), and in turn improved both performance, readability and conciseness of my code. Most of the files are less than 100 lines long.

The abstraction has been extremely useful - especially for working with the CIM-data as mentioned in my last comment.

**Comment by jreback** [comment]
@bergkvist best way to start is with an example of your code above in a recipe. pandas api is so huge that adding needs a really high bar (it might be that this is useful more generally, but let's start small).

**Comment by bergkvist** [comment]
Slightly simplified example (ignoring the power transformer):

```py
pd.link([
        Terminal.ConnectivityNode.pipe(flip),
        Terminal.ConductingEquipment,
        pd.concat([
            ACLineSegment.BaseVoltage,
            BusbarSection.BaseVoltage,
            EnergyConsumer.BaseVoltage,
            Breaker.BaseVoltage,
            Disconnector.BaseVoltage,
            Fuse.BaseVoltage,
            GroundDisconnector.BaseVoltage,
            Jumper.BaseVoltage,
            LoadBreakSwitch.BaseVoltage,
            pd.link([
                pd.concat([
                    ACLineSegment.EquipmentContainer,
                    BusbarSection.EquipmentContainer,
                    EnergyConsumer.EquipmentContainer,
                    Breaker.EquipmentContainer,
                    Disconnector.EquipmentContainer,
                    Fuse.EquipmentContainer,
                    GroundDisconnector.EquipmentContainer,
                    Jumper.EquipmentContainer,
                    LoadBreakSwitch.EquipmentContainer,
                ]),
                pd.concat([
                    pd.link([
                        Bay.VoltageLevel,
                        VoltageLevel.BaseVoltage
                    ]),
                    VoltageLevel.BaseVoltage
                ])
            ])
        ]),
        BaseVoltage.nominalVoltage
    ])
```

The flip-function will swap index and columns of a pandas Series or DataFrame.

**Comment by bergkvist** [comment]
I guess a nice way of conceptualizing what pd.link tries to be:

A pd.Series is a mapping between an index (input) and a values (output). You can think of this as a mathematical function that has been converted to a lookup table. The only difference from a mathematical function is that you can have multiple entries for the same index (which makes pd.Series a bit more general).

pd.link is basically a way of composing/piping these functions together. (Combining lookup tables)

**Comment by jbrockmendel** [comment]
@bergkvist is what you're describing at all like the following use case:

```
dates = DatetimeIndex(...)
states = CategoricalIndex(...)

df = pd.DataFrame(..., columns=["x", "y", "z", "date", "state"])
df["state"] = df["state"].astype(states.dtype)

unemp = pd.DataFrame(..., index=dates, columns=states)
```


and you might like to define an `df["unemp"]` column which you could do with something like

```
mi = MultiIndex.from_arrays([df["date"], df["state"]])
unemp2 = unemp.stack()
newcol = unemp2[mi]
```

_but_ you dont want to actually realize this `newcol` (maybe to avoid making a copy?), but instead define it as a reference?

**Comment by mroeschke** [comment]
Thanks for the suggestion, but it appears that this enhancement generally hasn't garnered much interest from the core team. Going to close, but if you would like to contribute to our recipe documentation on how to compose this functionality from existing pandas functions that would be welcome.
