### ISSUE TITLE
PERF: regression in Series.asof with single date

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#38083]
From https://pandas.pydata.org/speed/pandas/#timeseries.AsOf.time_asof_single?p-constructor='Series'&commits=52a17259-24e881d4&x-axis=commit&Cython=0.29.21&python=3.8

Snippet extracted from ASV:

```python
N = 10000
rng = pd.date_range(start="1/1/1990", periods=N, freq="53s")
s = pd.Series(np.random.randn(N), index=rng)

dates = pd.date_range(start="1/1/1990", periods=N * 10, freq="5s")
date = dates[0]

%timeit s.asof(date)
```

On pandas 1.1 this takes around 20µs, on master I get around 110µs

Commit range indicated by ASV is https://github.com/pandas-dev/pandas/compare/52a17259...24e881d4

**Comment by jorisvandenbossche** [comment]
Profile indicates a lot of use of `searchsorted`, so potential cause https://github.com/pandas-dev/pandas/pull/37990 cc @jbrockmendel

**Comment by jbrockmendel** [comment]
Yep, restoring the overriden searchsorted method fixes the perf.  that suggests there's a lot of overhead in algorithms.searchsorted
