### ISSUE TITLE
CI: very slow tests

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#38091]
from a recent build on master, these builds are *very* slow. Yes we have 140k tests, but 30m is a lot of time (esp considering the azure builds are 2x faster).

needs some investigation on what is happening.
- https://travis-ci.org/github/pandas-dev/pandas/jobs/746072524
- https://travis-ci.org/github/pandas-dev/pandas/jobs/746072525

cc @pandas-dev/pandas-core

**Comment by bashtage** [comment]
Could start up upping the number of durations shown.  There may be a large tranch of tests that are all not super slow but slow enough.

**Comment by ivanovmg** [comment]
``pandas/tests/io/excel`` are pretty slow. Can gain about 5 minutes there.

**Comment by mroeschke** [comment]
Looks like we don't have the travis logs anymore. I think we can reopen a subsequent issue once the offending set of tests are found.
