### ISSUE TITLE
BUG: `df.copy` removes attributes from series in the original dataframe

### ISSUE THREAD

**Issue by ivirshup** [pandas-dev/pandas#38107]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
# Your code here
import pandas as pd

df = pd.DataFrame({"a": [1, 2, 3]})
df["a"].attrs["key"] = "value"
display(df["a"].attrs)
# {'key': 'value'}
_ = df.copy()
display(df["a"].attrs)
# {}
```

#### Problem description

Calling copy on a dataframe probably shouldn't modify it or it's contents (especially those exposed through public attributes) in any way.

I would also ague the copy should keep these attributes, but that's more related to #35425

#### Expected Output

The second `display(df["a"].attrs)` should print: `{'key': 'value'}`

#### Output of ``pd.show_versions()``

<details>

```
INSTALLED VERSIONS
------------------
commit           : 67a3d4241ab84419856b84fc3ebc9abcbe66c6b3
python           : 3.8.5.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
Version          : Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.4
numpy            : 1.19.4
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.2
Cython           : 0.29.21
pytest           : 6.1.2
hypothesis       : None
sphinx           : 3.3.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 0.7.4
fastparquet      : 0.4.1
gcsfs            : None
matplotlib       : 3.3.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 2.0.0
pytables         : None
pyxlsb           : None
s3fs             : 0.4.2
scipy            : 1.5.4
sqlalchemy       : 1.3.18
tables           : 3.6.1
tabulate         : 0.8.7
xarray           : 0.16.1
xlrd             : 1.2.0
xlwt             : None
numba            : 0.51.2
```

</details>

**Comment by leonarduschen** [comment]
I believe this is intentional. `.attrs` is only propagated on the object itself (i.e. the dataframe) and not on each individual columns.

This is related to https://github.com/pandas-dev/pandas/issues/35425

**Comment by jorisvandenbossche** [comment]
Indeed, this is a consequence of what is being discussed in #35425.

The reason that it "seems" to retain the attrs for the Series before copying, is because we cache the Series upon first access. So you are actually setting the attrs on this cached Series. You can see that if we clear the cache, the attrs are not hold on the DataFrame:

```
In [12]: 
    ...: df = pd.DataFrame({"a": [1, 2, 3]})
    ...: df["a"].attrs["key"] = "value"

In [13]: df["a"].attrs
Out[13]: {'key': 'value'}

In [14]: df._clear_item_cache()

In [15]: df["a"].attrs
Out[15]: {}
```

So let's discuss this further as part of #35425
