### ISSUE TITLE
REF: dtypes.cast

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#38119]
There are too many functions in `dtypes.cast`, making it difficult to know which one to use in a given situation.  e.g. when working with `Index.insert` in #38102 I considered `maybe_promote`, `maybe_upcast`, `maybe_casted_values`, `find_common_type`.

Best case scenario we can de-duplicate some of these and just remove some of them, but failing that, I think we could find new homes for e.g. `construct_1d_arraylike_from_scalar`, `construct_1d_object_array_from_listlike`, `construct_1d_ndarray_preserving_na`.

**Comment by jreback** [comment]
would start by making a submodule and organizing

**Comment by jbrockmendel** [comment]
There are a couple of functions in here that are basically disguised Series/DataFrame methods, in particular cast.convert_dtypes is effectively Series._convert_dtypes, cast.maybe_casted_values is only used in DataFrame.reset_index.  These aren't re-usable low-level functions (which is how i like to think of core.dtypes, but I guess it doesn't have to be that way), but I'm not eager to move code _into_ Series/DataFrame, so not obvious how to handle.
