### ISSUE TITLE
CLN: C408 Unnecessary dict call - rewrite as a literal

### ISSUE THREAD

**Issue by fangchenli** [pandas-dev/pandas#38138]
The following files contain flake8 C408 Unnecessary dict call - rewrite as a literal. Good for first time contributors. See #38078 and #38116 for how to fix them. Use `flake8 [file_path]` to check for each file.

### C408
- [x] ./pandas/core/generic.py
- [x] ./pandas/core/series.py
- [x] ./pandas/core/frame.py
- [x] ./pandas/core/strings/accessor.py
- [x] ./pandas/core/dtypes/dtypes.py
- [x] ./pandas/core/computation/pytables.py
- [x] ./pandas/core/computation/expressions.py
- [x] ./pandas/core/arrays/floating.py
- [x] ./pandas/core/arrays/interval.py
- [x] ./pandas/core/arrays/numpy_.py
- [x] ./pandas/core/arrays/base.py
- [x] ./pandas/core/ops/methods.py
- [x] ./pandas/core/indexes/interval.py
- [x] ./pandas/core/indexes/multi.py
- [x] ./pandas/core/indexes/numeric.py
- [x] ./pandas/core/indexes/base.py
- [x] ./pandas/io/pytables.py
- [x] ./pandas/tests/reshape/concat/test_datetimes.py
- [x] ./pandas/tests/reshape/merge/test_merge.py
- [x] ./pandas/tests/reshape/merge/test_multi.py
- [x] ./pandas/tests/tools/test_to_numeric.py
- [x] ./pandas/tests/resample/test_time_grouper.py
- [x] ./pandas/tests/util/test_assert_series_equal.py
- [x] ./pandas/tests/util/test_assert_interval_array_equal.py
- [x] ./pandas/tests/util/test_assert_index_equal.py
- [x] ./pandas/tests/util/test_assert_extension_array_equal.py
- [x] ./pandas/tests/io/test_parquet.py
- [x] ./pandas/tests/io/generate_legacy_storage_files.py
- [x] ./pandas/tests/io/formats/test_format.py
- [x] ./pandas/tests/io/parser/test_comment.py
- [x] ./pandas/tests/io/parser/test_parse_dates.py
- [x] ./pandas/tests/io/parser/test_c_parser_only.py
- [x] ./pandas/tests/io/parser/test_dialect.py
- [x] ./pandas/tests/io/parser/test_skiprows.py
- [x] ./pandas/tests/io/parser/test_encoding.py
- [x] ./pandas/tests/io/parser/test_read_fwf.py
- [x] ./pandas/tests/io/parser/test_python_parser_only.py
- [x] ./pandas/tests/io/parser/test_na_values.py
- [x] ./pandas/tests/io/parser/test_usecols.py
- [x] ./pandas/tests/io/parser/test_quoting.py
- [x] ./pandas/tests/io/parser/test_header.py
- [x] ./pandas/tests/io/parser/test_index_col.py
- [x] ./pandas/tests/io/json/test_ujson.py
- [x] ./pandas/tests/io/json/test_normalize.py
- [x] ./pandas/tests/io/pytables/test_timezones.py
- [x] ./pandas/tests/io/pytables/test_store.py
- [x] ./pandas/tests/frame/test_reductions.py
- [x] ./pandas/tests/frame/test_arithmetic.py
- [x] ./pandas/tests/frame/methods/test_to_records.py
- [x] ./pandas/tests/frame/methods/test_sort_values.py
- [x] ./pandas/tests/frame/methods/test_fillna.py
- [x] ./pandas/tests/frame/methods/test_to_csv.py
- [x] ./pandas/tests/frame/indexing/test_indexing.py
- [x] ./pandas/tests/frame/indexing/test_where.py
- [x] ./pandas/tests/dtypes/test_inference.py
- [x] ./pandas/tests/groupby/test_function.py
- [x] ./pandas/tests/groupby/transform/test_transform.py
- [x] ./pandas/tests/plotting/test_boxplot_method.py
- [x] ./pandas/tests/plotting/frame/test_frame_subplots.py
- [ ] ./pandas/tests/io/parser/test_common.py

### Remove ignore setting from flake8 section
- [ ] setup.cfg

**Comment by liudj2008** [comment]
I would like to take the followings in pandas core and io as the first step
----------------------------------------
 ./pandas/core/generic.py
 ./pandas/core/series.py
 ./pandas/core/frame.py
 ./pandas/core/strings/accessor.py
 ./pandas/core/dtypes/dtypes.py
 ./pandas/core/computation/pytables.py
 ./pandas/core/computation/expressions.py
 ./pandas/core/arrays/floating.py
 ./pandas/core/arrays/interval.py
 ./pandas/core/arrays/numpy_.py
 ./pandas/core/arrays/base.py
 ./pandas/core/ops/methods.py
 ./pandas/core/indexes/interval.py
 ./pandas/core/indexes/multi.py
 ./pandas/core/indexes/numeric.py
 ./pandas/core/indexes/base.py
 ./pandas/io/pytables.py

**Comment by skvrahul** [comment]
Created a PR (#38180 )that addresses the following files:

./pandas/tests/reshape/concat/test_datetimes.py
./pandas/tests/reshape/merge/test_merge.py
./pandas/tests/reshape/merge/test_multi.py

@fangchenli Is a **whatsnew** entry necessary for such a change in the code?

**Comment by Qbiwan** [comment]
[Rewrite dict literal for files in tests/plotting/test_boxplot_method.py #38186](https://github.com/pandas-dev/pandas/pull/38186)

**Comment by Qbiwan** [comment]
first-time contributor here; please let me know if I'd missed anything

**Comment by pillemer** [comment]
Hi, I'm new to contributing and would like to help on this issue. Do I need to request to work on specific files before I start?

**Comment by fangchenli** [comment]
> Hi, I'm new to contributing and would like to help on this issue. Do I need to request to work on specific files before I start?

No, that is not necessary.

**Comment by jreback** [comment]
@fangchenli if you have a chance can you check things off from the merged PRs

**Comment by UrielMaD** [comment]
**I'd like to take the following as my first contribution**

./pandas/tests/util/test_assert_series_equal.py

**Comment by austiezr** [comment]
Just submitted a [PR](https://github.com/pandas-dev/pandas/pull/38249) to fix another swath of this.

**Comment by gerardjorgensen** [comment]
I would like to start working on the following
 ./pandas/tests/io/json/test_ujson.py
 ./pandas/tests/io/json/test_normalize.py

**Comment by vmdhhh** [comment]
Hi @jreback 
First time contributing
I would like to take up ./pandas/tests/io/pytables/test_store.py
I will start working on it, please let me know otherwise

**Comment by mavismonica** [comment]
Hi, 
I would like to take up ./pandas/tests/io/parser/test_comment.py

**Comment by mavismonica** [comment]
Hi,
I would like start working on  ./pandas/core/indexes/numeric.py

**Comment by mavismonica** [comment]
Hi,
I would like to start working on  ./pandas/core/indexes/numeric.py

**Comment by zanuttin** [comment]
Hello, I'm Joao and I would like to take  

./pandas/core/arrays/floating.py

to start working as my first issue

**Comment by vmdhhh** [comment]
@zanuttin hey, `./pandas/core/arrays/interval.py` is already up for merge in #38263.
Just to avoid rework, maybe you could take something else if possible?

**Comment by zanuttin** [comment]
I have already pushed the modifications @vmdhhh, sorry for not paying attention on your first comment. 
From what I've checked we did the same modifications, not sure if this is enough to not generate a conflict though.

**Comment by UrielMaD** [comment]
Hello, I just submitted a PR for ./pandas/core/strings/accessor.py

**Comment by UrielMaD** [comment]
Hi again @jreback, I checked the file ./pandas/core/dtypes/dtypes.py and it has no unnecessary dict calls

**Comment by fangchenli** [comment]
I've checked everything in #38320 (not merged yet) off. Please select from the remaining files to work on.

**Comment by shrutiguptabu** [comment]
Hello, 

I would like to take 

./pandas/tests/io/parser/test_parse_dates.py
./pandas/tests/io/generate_legacy_storage_files.py

as my first issue.

**Comment by pillemer** [comment]
I will do /pandas/tests/io/parser/test_index_col.py

**Comment by UrielMaD** [comment]
Hi @jreback I just updated the last 10 files remaining, this will close the issue, 
there's just the setup.cfg file to be changed, I tried to do it but it throws some flake8 errors and didn't passed the checks

**Comment by jreback** [comment]
close the issue when the checks are updated

**Comment by MarcoGorelli** [comment]
sorry didn't realise there was the "closes" keyword in the PR, will check more carefully next time
