### ISSUE TITLE
TST: Add tests for observance rules in holiday.py

### ISSUE THREAD

**Issue by leonarduschen** [pandas-dev/pandas#38139]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

None of the observance rules (e.g. `next_workday`, `before_nearest_workday`) are tested

**Comment by ivanovmg** [comment]
take

**Comment by ivanovmg** [comment]
I guess that there are tests for those in ``pandas/tests/tseries/holiday/test_holiday.py``.
I added several cases for ``next_workday`` and ``before_nearest_workday`` (I guess all possible cases), but there are other observance rules, which can be covered with more cases as well.

**Comment by mroeschke** [comment]
Looks like `pandas/tests/tseries/holiday/test_observance.py` has been pretty fleshed out in the meantime to meet the spirit of the original issue so closing. Can open a new issue with specific items if there are followups
