### ISSUE TITLE
BUG/DEPR: Fix unwanted warnings from the Series(Index[datetime objects]) deprecation

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#38182]
See https://github.com/pandas-dev/pandas/pull/36697#discussion_r497786546 and https://github.com/pandas-dev/pandas/pull/37193#issuecomment-715228272

Due to the `Index.is_all_dates` + `Series(Index[datetime object])` deprecation warnings, there are several code examples that are not using this attribute or constructor method directly, that still cause this warning (from internal pandas code, without direct control over this by the user). 

Users should not see unrelated deprecation warnings from the internals of pandas that they can't do anything about themselves, so IMO we should either fix those for 1.2, or delay the deprecationg for 1.3

**Comment by jorisvandenbossche** [comment]
cc @jbrockmendel

**Comment by jbrockmendel** [comment]
> there are several code examples that are not using this attribute or constructor method directly, that still cause this warning (from internal pandas code, without direct control over this by the user).

I see #37193 has been fixed.  Are there others that we can just fix internally?  I don't see any good option other than hunting these down.

Shorthand: dti = "instance of DatetimeIndex", dti_obj = dti.astype(object)

Two cases come to mind:

1) User passes dti_obj as index to Series constructor, gets back a Series with dti.  We correctly issue a warning.

2) User does [anything else], internal code does something that ends up passing dti_obj to the Series constructor
    a) that Series (or its index) are never returned to the user (e.g. in #37193), and
    b) no relevant behavior depends on the deprecated behavior.
    
    We incorrectly issue a warning.

I can imagine (ugly) ways to check whether we're in case 1 vs case 2, but I don't have any idea how to determine at runtime that both 2a and 2b hold.  Do you think that's feasible?

**Comment by jorisvandenbossche** [comment]
> I see #37193 has been fixed. 

I don't think it is fixed? (or at least not that I am aware of, and the linked PR only suppressed the warning in the *tests*, not in the actual code). See the linked example at https://github.com/pandas-dev/pandas/pull/37193#issuecomment-715228272:

```
idx = pd.date_range("2012-6-22 21:59:51", freq="S", periods=100)
df = pd.DataFrame(np.random.randn(len(idx), 2), index=pd.Index(idx, dtype=object))

df.plot()
```

**Comment by simonjayhawkins** [comment]
@jorisvandenbossche @jbrockmendel what's the status here? As this has not been fixed and the release is imminent are we reverting #36697 for 1.2 and deferring to 1.3?

**Comment by simonjayhawkins** [comment]
@jorisvandenbossche @jbrockmendel @jreback  can't be reverted automatically. will start the manual revert shortly. may not be difficult, but please lmk if this is not what we want to do.

**Comment by jorisvandenbossche** [comment]
It should certainly not be reverted fully. I think the `is_all_dates` deprecation is not causing any problems, but on the Series(..) construction

**Comment by simonjayhawkins** [comment]
Thanks @jorisvandenbossche i'll update #38679

**Comment by jbrockmendel** [comment]
@jorisvandenbossche can you respond to https://github.com/pandas-dev/pandas/issues/38182#issuecomment-736840436
