### ISSUE TITLE
DOC: Clarify development environment creation for documentation changes

### ISSUE THREAD

**Issue by ooojpeg** [pandas-dev/pandas#38193]
#### Location of the documentation

[https://pandas.pydata.org/docs/dev/development/contributing.html#creating-a-development-environment](contributing.html)

#### Documentation problem

The documentation for creating a development environment is not really clear regarding the benefits/limitations of creating a development environment when changing documentation.

#### Suggested fix for documentation

To test out code changes, you’ll need to build pandas from source, which requires a C/C++ compiler and Python environment. If you’re making documentation changes, you can skip to Contributing to the documentation but if you skip creating the development environment you won’t be able to build the documentation locally before pushing your changes.

**Comment by rhshadrach** [comment]
So from

> ..., you can skip to Contributing to the documentation but you won’t be able...

to 

> ..., you can skip to Contributing to the documentation but if you skip creating the development environment...

It seems clear to me that "but" is referring to "you can skip" in the current version.

**Comment by ooojpeg** [comment]
@rhshadrach I'm not 100% tbh. It confused me for a moment when I read for the first time so thought I'd mention and see if anyone else feels the same.
