### ISSUE TITLE
BUG: pd's std function inconsistency between series and values within a series

### ISSUE THREAD

**Issue by zwcolin** [pandas-dev/pandas#38218]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
temp = pd.DataFrame({'col':[1,2]})
display(temp)
temp['col'].std(), temp['col'].values.std(), np.std(temp['col']), np.std(temp['col'].values)
```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

Results of std is inconsistent between a series and values within a series

#### Expected Output
(0.7071067811865476, 0.7071067811865476, 0.5, 0.5)
or
(0.5, 0.5, 0.5, 0.5)
#### Output of ``pd.show_versions()``
(0.7071067811865476, 0.5, 0.5, 0.5)
<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by zwcolin** [comment]
I noticed that this function is normalized by N-1 by default. Then I think it's a consistency issue between series' std and values' std (eg. difference between temp['col'].std(), temp['col'].values.std())

**Comment by mroeschke** [comment]
`.values` returns a numpy array and therefore `.values.std()` uses numpy's `std` function which normalize by N while pandas normalizes by N-1 by default as you mentioned.

So this is the expected behavior. Closing.
