### ISSUE TITLE
BUG: values are dropped when grouping on a variables with NaNs

### ISSUE THREAD

**Issue by randomgambit** [pandas-dev/pandas#38227]
Hello there,

Consider this simple example

```
pd.__version__
Out[158]: '1.1.3'

df = pd.DataFrame({'col': [1,2,3],
                   'group' : ['a',np.NaN,'b']})

df
Out[160]: 
   col group
0    1     a
1    2   NaN
2    3     b

df.groupby('group').apply(lambda x: x)
Out[161]: 
   col group
0  1.0     a
1  NaN   NaN
2  3.0     b
```

There are a few things that are puzzling.

1. I thought `groupby` would drop the NA groups by default
2. Why is the variable `col` set to missing?

This looks like a bug to me, unless I am missing something (apologies if this is the case)
What do you think?

Thanks!

**Comment by jreback** [comment]
pls try this in master

**Comment by randomgambit** [comment]
1.1.4 ?

**Comment by phofl** [comment]
Persists on master
