### ISSUE TITLE
API: make tm.assert_foo_equal kwargs keyword-only for rarely-used keywords

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#38222]
I expect this would need a deprecation cycle cc @jorisvandenbossche ?

**Comment by jorisvandenbossche** [comment]
Is there a reason you closed this? (I think this is a good idea)

We should have the infrastructure to deprecate it (I think we did something similar for eg read_html), if we want that

**Comment by jbrockmendel** [comment]
I tend to prune my own open issues fairly aggressively.  I may come back to it sooner or later, but there are much higher priorities.
