### ISSUE TITLE
In search of a pandas logo...

### ISSUE THREAD

**Issue by cpcloud** [pandas-dev/pandas#3825]
complete [bikeshedding](https://en.wikipedia.org/wiki/Parkinson's_law_of_triviality), but...might be nice, any ideas? i was thinking one of the plots shown on the main website might work.

**Comment by joelostblom** [comment]
It would be nice to have a favicon for the pandas documentation pages! Is pandas still in search for an official logo? A friend of mine might be able to help design one if you are interested.

If you're not looking for a logo any longer, could a favicon be made from [the logo on the homepage](https://pandas.pydata.org/_static/pandas_logo.png)? Maybe using one of the three plots in the logo, such as the rightmost one would look good?

**Comment by gfyoung** [comment]
Closing in favor of #21376.

**Comment by gfyoung** [comment]
Closing in favor of #21376.
