### ISSUE TITLE
DOC: pandas.DataFrame.mask

### ISSUE THREAD

**Issue by ab-10** [pandas-dev/pandas#38261]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.mask.html#pandas-dataframe-mask

#### Documentation problem

The first line of docstring states:

>> Replace values where the condition is True.

However, `where` replaces the values for which the `cond` is False.

e.g.
```
zeros = pd.DataFrame(np.zeros(5))
zeros.where(zeros == 0.0, "REPLACED")
>>>
0.0
0.0
0.0
0.0
0.0


zeros.where(zeros != 0.0, "REPLACED")
>>>
REPLACED
REPLACED
REPLACED
REPLACED
REPLACED



#### Suggested fix for documentation

I think documentation should say "Replace values where the condition is False."

The rest of the `where` documentation should also be changed to reflect the actual behaviour of `where`.

**Comment by Qbiwan** [comment]
I think there is a difference between `mask` and `where`. You were using `where` in your example, but maybe looking at the documentation for `mask`?
It seems like one is kinda the opposite of the other in terms of what they do

## pandas.DataFrame.where
Where cond is **True**, **keep** the original value. Where False, replace with corresponding value from other. 
```
zeros = pd.DataFrame(np.zeros(5))
zeros.where(zeros == 0.0, "REPLACED")
>>>
0.0
0.0
0.0
0.0
0.0

zeros.where(zeros != 0.0, "REPLACED")
>>>
REPLACED
REPLACED
REPLACED
REPLACED
REPLACED

```
## pandas.DataFrame.mask
Where cond is False, keep the original value. Where **True**, **replace** with corresponding value from other. 


```
zeros = pd.DataFrame(np.zeros(5))
zeros.mask(zeros == 0.0, "REPLACED")
>>>
REPLACED
REPLACED
REPLACED
REPLACED
REPLACED

zeros.mask(zeros != 0.0, "REPLACED")
>>>
0.0
0.0
0.0
0.0
0.0

```

**Comment by ab-10** [comment]
My bad, I did indeed mix the documentation between the two.
Thank you for the clarification.

**Comment by Qbiwan** [comment]
you're welcome. tbh i could never remember which is which too :)
