### ISSUE TITLE
ENH: I wish I could use pandas to compare Two Excels and Create a difference Report where I can filter out differences alone

### ISSUE THREAD

**Issue by sunkusowmyasree** [pandas-dev/pandas#38288]
#### Is your feature request related to a problem?

[this should provide a description of what the problem is, e.g. "I wish I could use pandas to do [...]"]

#### Describe the solution you'd like

[this should provide a description of the feature request, e.g. "`DataFrame.foo` should get a new parameter `bar` that [...]", try to write a docstring for the desired feature]

#### API breaking implications

[this should provide a description of how this feature will affect the API]

#### Describe alternatives you've considered

[this should provide a description of any alternative solutions or features you've considered]

#### Additional context

[add any other context, code examples, or references to existing implementations about the feature request here]

```python
# Your code here, if applicable

```

**Comment by jreback** [comment]
see this: https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.compare.html?highlight=compare#pandas.DataFrame.compare
