### ISSUE TITLE
DOC: Out-of-date list of sort algorithms

### ISSUE THREAD

**Issue by jamesmyatt** [pandas-dev/pandas#38287]
#### Location of the documentation

e.g. https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.sort_values.html, https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_index.html

#### Documentation problem

List of values for `kind` should be updated to reflect changes in NumPy: https://numpy.org/doc/stable/reference/generated/numpy.sort.html

Specifically, since NumPy 1.15.0, the list has been `{‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}`

#### Suggested fix for documentation

Full list of options is provided. Also, the statement that "‘mergesort’ is the only stable algorithm" is now incorrect.

I can do this, when I get time. But I'm more than happy for someone else to do it if they want.

**Comment by rhshadrach** [comment]
Thanks for the report! PR to update is most welcome.

**Comment by DonPablo99** [comment]
@jamesmyatt are you ok with me taking this ?

**Comment by jamesmyatt** [comment]
@DonPablo99 Of course. Thank you.
