### ISSUE TITLE
DOC: add to str.endswith / startswith that tuples are accepted for multiple value testing

### ISSUE THREAD

**Issue by erfannariman** [pandas-dev/pandas#38281]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.endswith.html
https://pandas.pydata.org/docs/reference/api/pandas.Series.str.startswith.html

#### Documentation problem

 Right now there is no indication that these methods accept a tuple for testing on multiple character sequences.

#### Suggested fix for documentation

Add in the documentation that tuples are accepted as values.

**Comment by erfannariman** [comment]
take

**Comment by rhshadrach** [comment]
+1. Also should update type hints for the argument.

**Comment by mroeschke** [comment]
Closed by https://github.com/pandas-dev/pandas/pull/48587
