### ISSUE TITLE
ENH: set the first code value in Categorical

### ISSUE THREAD

**Issue by StevenLi-DS** [pandas-dev/pandas#38294]
#### Is your feature request related to a problem?

```python
import pandas as pd
from pandas.api.types import CategoricalDtype

df = pd.DataFrame(data={'col': ['small', 'medium', 'large']})
ordered = CategoricalDtype(categories=['small', 'medium', 'large'], ordered=True)

df.col = df.col.astype(ordered)
df.col.cat.codes

# 0    0
# 1    1
# 2    2
# dtype: int8

```
I often wish I can set the beginning underline code value in a Categorical. Right, no matter ordered or unordered, pandas will always begin the first code value as 0. Sometimes, I want it to begin with 1. like

```
ordered = CategoricalDtype(categories=['small', 'medium', 'large'], start=1, ordered=True)
```

Currently, there is no alternative I can think of other than manually storing the modified codes in a new column but this will not affect the underline coding. I really wish this feature could be added.

**Comment by rhshadrach** [comment]
How would the proposed feature be beneficial to you?

**Comment by StevenLi-DS** [comment]
Currently, you can't do anything and this like you have a datetime variable but you need to save it as a string and then format the string to want you want.

This is very useful when you try to run some satanical models in which you have to use numerical values. You don't have to save the code and then recode it, but simply do it during preprocessing. This separates your workflow and make it liner and clear.

Another situation is that pandas supports saving other data format like Stata, in which you can code any string value in a variable to any numerical value you want. Now, I also have to do the recoding in Stata since pandas' categorical always starts from 0 and has to be consecutive. You can only get 0, 1, 2 instead of 2, 4, 5.

In fact, I think pandas should support manual coding from the moment when converting a variable. For example, if you have a variable with two cats Group A and Group B. You can't control which one gets 0 and which one gets 1. Unless you make a ordered cat even if your variable is not ordered like male or female. I can't remember how many times I have to do this when running a logit model.

Maybe, pandas could support some API like this:
```
cat = CategoricalDtype(categories={'Group A': 1, 'Group B': 2})
df.col = df.col.astype(cat)
```

**Comment by jreback** [comment]
use https://pandas.pydata.org/docs/reference/api/pandas.Categorical.from_codes.html?highlight=from_codes#pandas.Categorical.from_codes

i actually don't find your examples compelling @StevenLi-DS but the api exists

**Comment by StevenLi-DS** [comment]
@jreback This still needs you to have a column/list of codes right? If you have 100 rows and you need a list with 100 codes right?

**Comment by jreback** [comment]
yes; as i said i don't find this use case compelling 

codes are internal 
you can certainly make them external if u want as a mother column - that's what i would do if u need this

**Comment by StevenLi-DS** [comment]
@jreback If I already have a code column. I don't need to create one. 

> This constructor is useful if you already have codes and categories/dtype and so do not need the (computation intensive) factorization step, which is usually done on the constructor

I just don't understand why I can't set up the code myself in a Categorical? If you have dataframe like this:
```
df = pd.DataFrame(data={'col': ['small', 'medium', 'large']})
```
How would you change the code to 1, 2, 3? If my use case is not compelling. There must be a solution right?
This has been one of the biggest issue for me for years now.

**Comment by jreback** [comment]
again you have haven't given an explicit example of why this is useful

**Comment by StevenLi-DS** [comment]
Hi @jreback. 
I really don't know how explicit it has to be and I've listed a couple of situations, but it is not compelling from your perspective. It's like you ask me why coding in stats is useful at all. Based on our conversation, I believe this is no solution for this now i.e. an limitation in pandas. Is this what feature request for? To be honest, I was surprised when I realized that pandas doesn't support this. All the data analysis software I know supports customized coding and it is such a basic function. 

There are many different coding schemes:
https://stats.idre.ucla.edu/spss/faq/coding-systems-for-categorical-variables-in-regression-analysis/
and I really believe that having the ability to control it could be a really useful ENH for pandas.

I wish you could give it a reconsideration.

**Comment by jreback** [comment]
@StevenLi-DS you are still missing the point

why is this useful? pandas already allows comparisons and operations on categories that have semantic meaning

if you show an example of how this is actually useful would give it consideration - please read the extensive categorical docs and things would become clear

**Comment by jreback** [comment]
and to be honest anything beyond simple coding and dummies is out of scope

if u must code for downstream use then do that -

**Comment by StevenLi-DS** [comment]
I'm simply asking for a way to control the coding.
If it is by design that pandas will only allow one, then I guess I have no other choice than accepting it.
Thanks for your time @jreback.

**Comment by jreback** [comment]
you can use from_codes - it is designed for this
