### ISSUE TITLE
ENH: Make pandas API more consistent

### ISSUE THREAD

**Issue by dclong** [pandas-dev/pandas#38300]
#### Is your feature request related to a problem?

The pandas DataFrame uses both arguments of `inplace` and `copy` (`DataFrame.astype` and `Series.astype`) in different methods to indicate change in place. It would be great if it can be unified to use `inplace` in all methods.

#### Describe the solution you'd like

Always use the argument `inplace` (instead of `copy`) to indicate change in place. 

#### API breaking implications

Some methods such as `DataFrame.astype` and `Series.astype` will be affected as they argument `copy` is changed to `inplace`.

**Comment by arw2019** [comment]
We've been discussing this in #16529
