### ISSUE TITLE
BUG: Sliced subclassed Series returns full data result when custom method is applied

### ISSUE THREAD

**Issue by GuillaumeDMMarion** [pandas-dev/pandas#38314]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas as pd

class _Subseries(pd.Series):

   _metadata = ['custom_method']

   @property
   def _constructor(self):
       return _Subseries

   @property
   def _constructor_expanddim(self):
       return _Subseries

   def custom_method(self, value):
       return self + value

s = _Subseries(range(5))
s = s.iloc[-3:]
s.custom_method(1)
```

#### Problem description

The above code returns:
0&nbsp;&nbsp;&nbsp;1
1&nbsp;&nbsp;&nbsp;2
2&nbsp;&nbsp;&nbsp;3
3&nbsp;&nbsp;&nbsp;4
4&nbsp;&nbsp;&nbsp;5

A similar method, such as .add(), on a sliced Series will return the result of that method on the sliced data and not on the original full data. I would expect this to be the same in a subclassed version of a Series.

#### Expected Output
2&nbsp;&nbsp;&nbsp;3
3&nbsp;&nbsp;&nbsp;4
4&nbsp;&nbsp;&nbsp;5

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 67a3d4241ab84419856b84fc3ebc9abcbe66c6b3
python           : 3.9.0.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_Belgium.1252

pandas           : 1.1.4
numpy            : 1.19.4
pytz             : 2020.4
dateutil         : 2.8.1
pip              : 20.3.1
setuptools       : 49.6.0.post20201009
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by jorisvandenbossche** [comment]
Hmm, that's strange. Thanks for the report! 

What's also strange that directly doing what the custom method does, doesn't give the wrong result (using your example):

```
In [24]: s = _Subseries(range(5))
    ...: s = s.iloc[-3:]

In [25]: s + 1
Out[25]: 
2    3
3    4
4    5
dtype: int64
```

Very welcome to dig in!

**Comment by jorisvandenbossche** [comment]
Ah, it's because of putting ``'custom_method"`` in the ``_metadata``, which is only meant to be done for *attributes*, not methods. Because of that (and because we try to preserve the metadata), we will assign the parent its method to the resulting series:

```
In [27]: s = _Subseries(range(5))

In [28]: s.custom_method
Out[28]: 
<bound method _Subseries.custom_method of 0    0
1    1
2    2
3    3
4    4
dtype: int64>

In [29]: s_sliced = s.iloc[-3:]

In [30]: s_sliced.custom_method
Out[30]: 
<bound method _Subseries.custom_method of 0    0
1    1
2    2
3    3
4    4
dtype: int64>
```

So basically what we did under the hood is `s_sliced.custom_method = s.custom_method`. And that way, you get the original series its values that are used when the method is called.

Is there a specific reason you put this in the `_metadata` ?

**Comment by GuillaumeDMMarion** [comment]
Thanks for the quick answer!

The reason I had it in ```_metadata``` was because I originally encountered it with an attribute indeed. What you state is correct and solves the code from above for sure.

I could imagine a new use case, and my apologies if it's too far from the original issue:

Imagine a subclassed ```Series``` where we have some ```metric``` of the instance stored as an attribute (why? maybe to avoid recomputing it every time we do some other operation). In that case, slicing the subclassed ```Series``` and then accessing the stated ```metric``` attribute will return a different shape.

```
class _Subseries(pd.Series):
    _metadata = ['metric']
    @property
    def _constructor(self):
        return _Subseries

class Subseries(_Subseries):
    def __init__(self, data):
        super().__init__(data)
        self.metric = self+5

s = Subseries(range(5))
s = s[-2:]
print(s.metric.shape == s.shape)
```
False

I doubt there's a way around this though? Is there for example some "hook" that is called when the ```Series``` is sliced, wherein we could reset some specific attributes (e.g. those that would need to preserve similar shape to the instance). Such as ```metric``` above?

**Comment by jorisvandenbossche** [comment]
I think the answer then still is: you shouldn't add this to `_metadata`. 
Not each attribute needs to be added in that list, you can also define normal attributes/properties in the subclass. Only properties you *want* to propagate, should be added there. See https://pandas.pydata.org/docs/dev/development/extending.html#define-original-properties about this

Also note that setting this attribute happens in the `__finalize__` method, which you can override in your subclass if you want more custom checks to see when the metadata should be propagated or not.

> Is there for example some "hook" that is called when the Series is sliced, wherein we could reset some specific attributes 

Yes, so that's basically the `__finalize__` which I mentioned above. 
An example where we use this

**Comment by GuillaumeDMMarion** [comment]
I've looked a bit into ```__finally__``` and am not sure it completely solves my use case.
But you are correct that adding to ```_metadata``` wasn't needed as such.

Below example makes no use of ```_metadata```, while still (per my use case) allowing me to:
- Compute ```metric``` once (at each manipulation)
- Retain identical shape between ```self``` and ```metric```

```python
import time
import pandas as pd

class _Subseries(pd.Series):
    @property
    def _constructor(self):
        return _Subseries
    @property
    def _constructor_expanddim(self):
        return _Subseries
    @property
    def metric(self):
        try:
            assert(hasattr(self, '_metric'))
        except:
            self._metric = self.compute_metric()
        finally:
            return self._metric
    def compute_metric(self):
        time.sleep(1)
        return self * 100

class Subseries(_Subseries):
    def __init__(self, data):
        super().__init__(data)
        self._metric = self.compute_metric()

s = Subseries(range(5))
s_sliced = s[-2:]
s_sliced.shape == s_sliced.metric.shape
```
True

Another approach with simple indexing, that does need ```_metadata```:
```python
import time
import pandas as pd

class _Subseries(pd.Series):
    _metadata = ['_metric']
    @property
    def _constructor(self):
        return _Subseries
    @property
    def _constructor_expanddim(self):
        return _Subseries
    @property
    def metric(self):
        return self._metric.loc[self.index]
    def compute_metric(self):
        time.sleep(1)
        return self * 100

class Subseries(_Subseries):
    def __init__(self, data):
        super().__init__(data)
        self._metric = self.compute_metric()

s = Subseries(range(5))
s_sliced = s[-2:]
s_sliced.shape == s_sliced.metric.shape
```
True

Bit of a hack I guess, but it fits my needs. Thanks again.

No bug and use case solved. Closing.
