### ISSUE TITLE
ENH: implement fast isin() for nullable dtypes

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#38340]
Currently, you can get quite a slowdown:

```
In [41]: arr = np.random.randint(0, 10, 1_000_001)

In [42]: s = pd.Series(arr)

In [43]: %timeit s.isin([1, 2, 3, 20])
2.71 ms ± 175 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [44]: s = pd.Series(arr, dtype="Int64")

In [45]: %timeit s.isin([1, 2, 3, 20])
22.9 ms ± 96.7 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by tushushu** [comment]
@jorisvandenbossche  Hi, I'm new here and would like to work on this issue.

**Comment by tushushu** [comment]
After testing, I found this line could be the bottleneck, for it would cost about 20ms according to the example provided.
https://github.com/pandas-dev/pandas/blob/b5958ee1999e9aead1938c0bba2b674378807b3d/pandas/core/algorithms.py#L442

**Comment by tushushu** [comment]
@jorisvandenbossche 

We can see Series's isin method is calling `algorithms.isin` function.
https://github.com/pandas-dev/pandas/blob/5cafae72a9c00da8e2f42f11c42b8fcb1639340a/pandas/core/series.py#L4633

And if we pass `s2._values._data` to `algorithms.isin` instead, the performance could be much better.
```
import pandas as pd
import numpy as np
from pandas.core import algorithms

arr = np.random.randint(0, 10, 1_000_001)
s1 = pd.Series(arr)

%timeit algorithms.isin(s1._values, [1, 2, 3, 20])
2.05 ms ± 200 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit algorithms.isin(s2._values, [1, 2, 3, 20])
24.1 ms ± 727 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

%timeit algorithms.isin(s2._values._data, [1, 2, 3, 20])
3.24 ms ± 61.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

So the solution could be:
```Python
from pandas.core.arrays.integer import IntegerArray

def isin(self, values) -> "Series":

    if isinstance(s3._values, IntegerArray):
        result = algorithms.isin(self._values._data, values)
    else:
        result = algorithms.isin(self._values, values)
    return self._constructor(result, index=self.index).__finalize__( self, method="isin")
```

**Comment by tushushu** [comment]
Here is the link of PR, please let me know if there is anything need to be modified. Thanks
https://github.com/pandas-dev/pandas/pull/38379
