### ISSUE TITLE
ENH: Functions for creating data frames and series "like" an existing one with different values

### ISSUE THREAD

**Issue by felix-hilden** [pandas-dev/pandas#38343]
#### Problem
Sometimes I find myself needing a copy of a `DataFrame` or a `Series` with different values to the original. That is to say, with a similar index and column structure and naming. For example, it could occur when doing some numerical transformations which return NumPy arrays. The thing can of course be done by creating new objects by hand, but it becomes quite repetitive after a few lines.

#### Solution
Utilities like `np.zeros_like` are neat shorthands, and looks like Pandas has used them, at least in Indexing ([`reindex_like`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.reindex_like.html)). I would like to see similar ways of constructing frames and series. I've written such shorthands for my personal use, but I think others could benefit from them being included in the library.

#### API breaking implications
This would introduce new functionality without affecting other parts of the system.

#### Describe alternatives you've considered
Doing it by hand is possible and pretty easy. It's only cumbersome, which the shorthand would solve.

#### Additional context
I'm not in the know of Pandas internal functionality, but the shorthands I've written are as follows:
```python
def df_like(data: Union[np.ndarray, pd.DataFrame], like: pd.DataFrame) -> pd.DataFrame:
    if isinstance(data, pd.DataFrame):
        data = data.values
    return pd.DataFrame(data, index=like.index, columns=like.columns)

def series_like(data: Union[np.ndarray, pd.Series], like: pd.Series) -> pd.Series:
    if isinstance(data, pd.Series):
        data = data.values
    return pd.Series(data, index=like.index, name=like.name)
```
If there's something else to account for, I would expect the functions to handle that as well. Maybe it could also be class method.
```python
class DataFrame:
    @classmethod
    def like(cls, data, like: "DataFrame") -> "DataFrame":
        if isinstance(data, cls):
            data = data.values
        return cls(data, index=like.index, columns=like.columns)
```

Looking forward to hearing your thoughts! I'd also be open to contributing these changes if an agreement is reached.

**Comment by arw2019** [comment]
I'm not sold on the motivation for adding this to the codebase but I don't feel strongly

**Comment by rhshadrach** [comment]
Isn't the constructor for DataFrame/Series already the parallel to `np.zeros_like` that you seek?

    pd.DataFrame(0, df.index, df.columns)

I don't find specifying one argument rather than two to be a compelling reason to add a new function to the API.

**Comment by felix-hilden** [comment]
That's fair, and I agree that it is straightforward to use the constructor. Let me expand a bit though. `np.zeros_like` is a similar shorthand for just a few arguments. `b = np.zeros(a.shape)` is likely the most common use case, although I imagine `zeros_like` takes care of the datatype and memory ordering as well. An important distinction for me is communicating intent, which I now realise was not addressed at all in my original post. Compare these lines:

```python
a = DataFrame(...)

b1 = DataFrame(0, df.index, df.columns)
b2 = DataFrame(0, df.columns, df.index)
b3 = DataFrame.like(0, a)
```

As a more casual user, it is not obvious to me which of the constructor calls will produce a similarly shaped frame without looking at the documentation. So I often use keyword arguments to make it extra clear. But with dedicated functions, be it the classmethod, `dataframe_like`, or even a method of the original Data Frame (e.g. `a.with_values(0)`), I think this communicates the intent very clearly.

Another benefit would be validating the data types. If `a` contains, say, strings and the incoming array is similarly shaped but contains only floats, I would expect the operation to fail, or at least the function to have a parameter for disabling the type validation.

But I'm not here to design your library, so I'll be happy with whatever conclusion you reach, because at least then this topic is addressed and we have a decision! Thoughts on my reasoning above?

**Comment by jreback** [comment]
-1 on adding any api here 

in numpy it is pretty common to create a new single dtyped array based on an existing then do operations on it

this is not super common in pandas and not important to warrant a new method -

there has empty some discussion about this in the past if u want to search the tracker

**Comment by mroeschke** [comment]
I'd be -1 as well on extending the API with this, especially given how your shorthand functions are essentially the feature you want.

Going to close this as there isn't too much interest.
