### ISSUE TITLE
DOC: Clarify stability of sorting in documentation of DataFrame.sort_values for multiple columns / labels

### ISSUE THREAD

**Issue by jotasi** [pandas-dev/pandas#38357]
#### Location of the documentation

Description of the argument `kind` in the documentation of [pandas.DataFrame.sort_values](https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.sort_values.html).

#### Documentation problem

The current documentation states (emphasize mine):

>Choice of sorting algorithm. See also ndarray.np.sort for more information. **mergesort is the only stable algorithm. For DataFrames, this option is only applied when sorting on a single column or label**.

To me that means, that the `kind` argument is ignored if you sort by multiple columns / labels. But I think one could even interpret it as `mergesort` explicitely is not done in that case. Running some tests, it does look like the sorting is stable when sorting multiple columns / labels. But it is not written anywhere. If it really is guaranteed that the sorting is stable for sorting by multiple columns / labels, it would be nice to have this written down explicitely in the documentation.

#### Suggested fix for documentation

IF that is actually the case, I would suggest to add a sentence to the effect that the sorting is stable if sorting is done by multiple columns / labels. E.g. change the `kind` argument description to:

>Choice of sorting algorithm. See also ndarray.np.sort for more information. mergesort is the only stable algorithm. ~~For DataFrames, this option is only applied when sorting on a single column or label.~~ **For DataFrames, if sorting by multiple columns or labels, this argument is ignored, defaulting to a stable sorting algorithm.**

**Comment by arw2019** [comment]
Are you interested in submitting a PR?

**Comment by jotasi** [comment]
Sure, I can do that. So the stability of sorting for multiple columns or labels is guaranteed?

**Comment by arw2019** [comment]
I'm not that familiar with that part of the codebase but merge sort, as stated, is definitely stable. We also appear to have an implementation of counting sort for multi-key sorting which is stable:
https://github.com/pandas-dev/pandas/blob/32bebdbcd2c8d68ad6dc9dab7cab2149c4861883/pandas/core/sorting.py#L566-L579

If we're using quicksort I'm not sure (can be stable/unstable and I don't know which one(s?) we have)

**Comment by jotasi** [comment]
Ok. Thanks for the help. I'll have a closer look at the code base trying to understand what is done for multiple columns / labels and then open a PR. I'll definitely not get to that before the weekend though.
