### ISSUE TITLE
Performance regressions in GroupBy.fillna

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#38358]
https://pandas.pydata.org/speed/pandas/#groupby.FillNA.time_df_ffill?python=3.8&Cython=0.29.21&commits=03e58585

From https://github.com/pandas-dev/pandas/commit/03e58585

cc @GYHHAHA

**Comment by GYHHAHA** [comment]
take

**Comment by GYHHAHA** [comment]
Is there a faster way to get the df with dropping the NaN group?
I try to use the indice operation to replace calling `filter`, but still slow.
Any suggestion? Thanks! @TomAugspurger

**Comment by TomAugspurger** [comment]
I’m not sure. If the bug we fixed was for correctness and the performance loss is unavoidable, then we can close this issue.

**Comment by jreback** [comment]
could be fixed by https://github.com/pandas-dev/pandas/pull/43578 

cc @mzeitlin11 @jbrockmendel

**Comment by jbrockmendel** [comment]
closed by #43578
