### ISSUE TITLE
ENH: Add an `assert`  method to Series and DataFrame to assert on the fly in chaining

### ISSUE THREAD

**Issue by ClementWalter** [pandas-dev/pandas#38356]
#### Is your feature request related to a problem?

When chaining methods, one may want to make some check and raise errors accordingly. Currently it is not possible to define these checks on the fly but one rather has to define a function like :

```
def assert_a_positive(df):
    if not (df.a > 0).all():
        raise ValueError()
    return df
```

so as to be able to do later, for example:

```
(
    pd.DataFrame({"a": [1, 2]})
    .pipe(assert_a_positive)
    .assign(b=lambda df: 1 / df.a)
)
```

This lakes flexibility and readability. Eventually it refrains from writing more test for data scientist that, even though then don't write unit test, at least are used to write sanity check like that.

#### Describe the solution you'd like

Adding an `assert` method to `pd.Series` and `pd.DataFrame` such that the above example could be written:

```
(
    pd.DataFrame({"a": [1, 2]})
    .assert(lambda df: (df.a > 0).all())
    .assign(b=lambda df: 1 / df.a)
)
```

#### API breaking implications

It doest not break a thing but just add a new method

#### Describe alternatives you've considered

There is actually a [great-expectation](https://github.com/great-expectations/great_expectations) package that does this sort of thing but with pre-built check. It is not as natural as writing down directly `assert` on-the-fly and requires an extra dep.

#### Additional context

In my current projects, I have just added these few lines at init:

```
from pandas.core.frame import DataFrame
from pandas.core.series import Series


def pandas_assert(df, func, *args, error_type=AssertionError):
    if not func(df):
        raise error_type(*[arg(df) if callable(arg) else arg for arg in args])
    return df


setattr(DataFrame, "assert_", pandas_assert)  # assert cannot be used
setattr(Series, "assert_", pandas_assert)
```

so that I can then do for example:

```
(
    pd.DataFrame({"a": [-1, 1, 2, 0]})
    .assert_(lambda df: (df.a > 0).all())
    .assign(b=lambda df: 1 / df.a)
)
(
    pd.DataFrame({"a": [-1, 1, 2, 0]})
    .assert_(lambda df: (df.a > 0).all(), "some a are lower than 0")
    .assign(b=lambda df: 1 / df.a)
)
(
    pd.DataFrame({"a": [-1, 1, 2, 0]})
    .assert_(
        lambda df: (df.a > 0).all(), "some a are lower than 0", error_type=ValueError
    )
    .assign(b=lambda df: 1 / df.a)
)
(
    pd.DataFrame({"a": [-1, 1, 2, 0]})
    .assert_(
        lambda df: (df.a > 0).all(),
        lambda df: f"some a are lower than 0:\n{df[df.a <= 0]}",
        error_type=ValueError,
    )
    .assign(b=lambda df: 1 / df.a)
)
```

**Comment by TomAugspurger** [comment]
I'd prefer to keep this outside of pandas.

**Comment by ClementWalter** [comment]
From a datascientist point of view I like this because it helps adding checks without breaking a chaining, which is a best practice. Furthermore it makes the check very explicit at the point where it is actually made. Currently I would not pipe but rather break the chain:

```
df = pd.DataFrame({"a": [-1, 1, 2, 0]})

if not (df.a > 0).all():
    raise ValueError()

df.assign(b=lambda df: 1 / df.a)
```

which I guess is less readable and not as concise as the proposed version

**Comment by ClementWalter** [comment]
For the record, I have created a pubic repo called "pandas-addons" where I have added this feature and plan to add some more, see https://github.com/ClementWalter/pandas-addons

**Comment by bersbersbers** [comment]
I don't usually comment on issues like this, but  since this has carries the "Needs Discussion" label: I'd love to have this. It's really painful to add checks in the middle of a long, chained pipeline (also because you cannot use `assert` in a `lambda` expression), and having `df.assert` might help a lot.

**Comment by TomAugspurger** [comment]
I'd recommend using something like [bulwark](https://github.com/zaxr/bulwark). Then you have something like

```python
    import bulwark.checks as ck

    df.pipe(ck.has_no_nans())
```

Which, to me, seems just about as good as a dedicated `.assert` method.

Not to mention, `assert` is a keyword reserved by python, so it would need to be called something else.

**Comment by ClementWalter** [comment]
Actually your suggestion does not cover the target use case as it requires to have the check built in `bulwark`. As stated by @bersbersbers it is painful to add check in chained pandas. `pipe` requires you to have the check already existing in the namespace while the proposed `assert` does not.

As for the name, in my proposed implementation in https://github.com/ClementWalter/pandas-addons I have used `df.assert_` following python convention of adding `_` to prevent collision with base python names.

**Comment by mroeschke** [comment]
Thanks for the suggestion, but agreed that this feature sounds best belonging in an external repo like you have in https://github.com/ClementWalter/pandas-addons. The only assertions pandas maintains in the library are dedicating for unit testing.

Since this feature hasn't gotten much favor from other core developers, going to close this issue.
