### ISSUE TITLE
DOC: infer_dtypes document is inconsistent with behaviour regarding boolean

### ISSUE THREAD

**Issue by tsinggggg** [pandas-dev/pandas#38375]
#### Location of the documentation

https://github.com/pandas-dev/pandas/blob/0711b7adb3150f14461c5d1a111a87a83a45bc90/pandas/_libs/lib.pyx#L1315

#### Documentation problem

In this example the return value should be 'boolean' as mentioned in this test case https://github.com/pandas-dev/pandas/blob/1db3aa2b8ae8bd3b20dea14b92e1e7355bfa266a/pandas/tests/dtypes/test_inference.py#L679

#### Suggested fix for documentation

change 'mix' to 'boolean'

**Comment by arw2019** [comment]
Am I misunderstanding or this isn't a docs problem? infer_dtypes returns `mixed` in this case

**Comment by tsinggggg** [comment]
> Am I misunderstanding or this isn't a docs problem? infer_dtypes returns `mixed` in this case

@arw2019 i think it actually returns boolean, as shown in the test case

**Comment by arw2019** [comment]
is the difference that one is a python list holding `[True, False, np.nan]` versus an ndarray `np.array([True, np.nan, False], dtype="O")` constructed from that list

**Comment by tsinggggg** [comment]
> is the difference that one is a python list holding `[True, False, np.nan]` versus an ndarray `np.array([True, np.nan, False], dtype="O")` constructed from that list

it seems even with a list it's returning boolean
https://colab.research.google.com/drive/1s8kRGIkeQk2TXprc_Q2iYcNAT3u1QrPa?usp=sharing

**Comment by arw2019** [comment]
ok. Are you interested in submitting a PR with the correction?

(I know that in .py files we verify the docstrings but maybe in .pyx we don't...)

**Comment by tsinggggg** [comment]
> ok. Are you interested in submitting a PR with the correction?
> 
> (I know that in .py files we verify the docstrings but maybe in .pyx we don't...)

yes sure!

**Comment by DonPablo99** [comment]
Hello there, as I'm starting to work on some open source contributions, I'm happy to submit a PR with the correction.

**Comment by tsinggggg** [comment]
take

**Comment by tsinggggg** [comment]
> Hello there, as I'm starting to work on some open source contributions, I'm happy to submit a PR with the correction.

@DonPablo99 hey i just assigned this to myself and i started working on it
