### ISSUE TITLE
BUG: `DataFrame.__repr__` not showing correct `MultiIndex` values

### ISSUE THREAD

**Issue by galipremsagar** [pandas-dev/pandas#38388]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
>>> import pandas as pd
>>> df = pd.DataFrame()
>>> df['a'] = pd.Series([1, 2, None], dtype='Int64')
>>> df['b'] = pd.Series([10, 11, 12])
>>> df['c'] = pd.Series(['dsf', 'bac', 'abc'])
>>> df
      a   b    c
0     1  10  dsf
1     2  11  bac
2  <NA>  12  abc
>>> df.set_index(['a','b'])
          c
a   b      
1   10  dsf
2   11  bac
NaN 12  abc
>>> df.set_index(['a','b']).index
MultiIndex([(1.0, 10),
            (2.0, 11),
            (nan, 12)],
           names=['a', 'b'])
```

#### Problem description

The actual underlying values in the multiIndex in first level are all `floats` but the `DataFrame.__repr__` outputs the values as integers.

#### Expected Output

The expected output should be inline with `MultiIndex.__repr__`.

```python
>>> df.set_index(['a','b'])
          c
a     b      
1.0   10  dsf
2.0   11  bac
NaN   12  abc
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 67a3d4241ab84419856b84fc3ebc9abcbe66c6b3
python           : 3.7.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.1.0
Version          : Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8
pandas           : 1.1.4
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.3
setuptools       : 50.3.0
Cython           : None
pytest           : None
hypothesis       : 5.29.0
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 1.0.1
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by phofl** [comment]
Actually I think MultiIndex was constructed wrong previously.

I am getting
```
df.set_index(['a','b'])
Out[6]: 
          c
a   b      
1   10  dsf
2   11  bac
NaN 12  abc
df.set_index(['a','b']).index
Out[7]: 
MultiIndex([(  1, 10),
            (  2, 11),
            (nan, 12)],
           names=['a', 'b'])
```

on master, which is what I would expect here

**Comment by galipremsagar** [comment]
Thanks @phofl this seems to be fixed in `master`.
