### ISSUE TITLE
ENH: Naming inconsistency of functions like read_csv() and to_csv()

### ISSUE THREAD

**Issue by aiwalter** [pandas-dev/pandas#38402]
#### Is your feature request related to a problem?

Inconsistent naming of functions related to read and write data like `pd.read_csv()` and `to_csv()`. This is confusing for users because of the naming: **read vs. to** . For users who are new to pandas, those function names `read` and `to` are confusing and not consistent.

#### Describe the solution you'd like
Those functions should either be named `read() `and `write()` or `from()` and `to()`.  My solution is to add a function `write()` like `write_csv()` that just wraps the existing `to()` function. Then the old way would still work. Another solutions is to add a `from()` function like `from_csv()`.

#### API breaking implications

We could have a depreciation warning on the `to()` functions or just keep it.

#### Describe alternatives you've considered

Keeping naming inconsistency.

**Comment by jreback** [comment]
these are probably the mostly heavily used functions and would cause way too much unecessary churn. -1 on any change.

**Comment by aiwalter** [comment]
@jreback yes and that is why I would prefer to fix that inconsistency and just add a `write_csv()` and `write_excel()` as a wrapper. Everyone who likes the old inconsistent style could still use that. When I started with pandas, this was the first negative impression I had, because I was confused about this naming.

**Comment by jreback** [comment]
I am not sure why you think is inconsistent at all. `to_` is actually a much more general term, IOW it describes converting a structure to JSON or a dict or a string for example, sure this is like writing, but write_json, write_dict just don't make a lot of sense. In any event, this is highly unlikely to be deprecated as would cause enormous churn for little gain. Maintaing aliases for names is also an anti-pattern, yes we do it (in a very limited cases) but its not a great item.

**Comment by mroeschke** [comment]
Thanks for the suggestion, but agreed that the churn on these functions would probably be to heavy handed for the community. Closing.
