### ISSUE TITLE
CI: SQL tests on py38 slow build

### ISSUE THREAD

**Issue by fangchenli** [pandas-dev/pandas#38429]
In #38344, we found that SQL tests were not run on py38 slow build. Currently, we are testing SQL on py37-locale and py37-coverage. If that is enough, we could move py38-slow to Azure. Otherwise, we could add more builds for SQL.

**Comment by jreback** [comment]
this is closed by https://github.com/pandas-dev/pandas/pull/38613 right?

**Comment by fangchenli** [comment]
> this is closed by #38613 right?

If we've decided to not test SQL on py38 slow, this can be closed.

**Comment by jreback** [comment]
can u see how much slow sql tests we have - meaning are we testing slow sql in at least 1 build?

**Comment by mroeschke** [comment]
We're testing SQL in GHA on Linux for PY3.8/3.9/3.10, so we have sufficient coverage now.
