### ISSUE TITLE
BUG/API: allowing scalars in Categorical constructor

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#38433]
I expected this to raise

```
>> pd.Categorical("A")
['A']
Categories (1, object): ['A']
```

This gets listified inside the call to `maybe_infer_to_datetimelike` in `Categorical.__init__`

**Comment by simonjayhawkins** [comment]
the docs for pd.Categorical do indeed suggest `values` should be list-like. and the string is NOT being interpreted as a list.

```
>>> pd.Categorical("ABC")
['ABC']
Categories (1, object): ['ABC']
>>>
```

**Comment by jbrockmendel** [comment]
Deep inside tests.arrays.categorical.test_constructors.TestCategoricalConstructors.test_constructor is 

```
        # Scalars should be converted to lists
        cat = Categorical(1)
        assert len(cat.categories) == 1
        assert cat.categories[0] == 1
        assert len(cat.codes) == 1
        assert cat.codes[0] == 0
```
