### ISSUE TITLE
DOC: name not defined in section "2.14.1 Basic plotting: plot"

### ISSUE THREAD

**Issue by gepcel** [pandas-dev/pandas#38451]
In the [pdf version of document](https://pandas.pydata.org/docs/pandas.pdf), section "User Guide -> Visualization -> 2.14.1 Basic plotting: plot", page 588,  there are `name 'pd' (or 'ts') is not defined` problems.

![image](https://user-images.githubusercontent.com/4179106/102015941-57f69300-3d99-11eb-86c7-28ae8c6a8196.png)

**Comment by MarcoGorelli** [comment]
Thanks @gepcel for the report - are you interested in submitting a pull request to fix this?

**Comment by gepcel** [comment]
Sure.

**Comment by gepcel** [comment]
I know this should be a very easy pr that should take less than one minute for an expert, but I need some guidance for something.

From what I understand, to fix this, I need to put some imports at the beginning of file `visualization.rst`. Which should be like:

```
.. _visualization:

{{ header }}

.. ipython:: python
   :suppress:

   import pandas as pd
   import numpy as np

   
*************
Visualization
*************
```

But what I don't understand is why some other files without the imports at the beginning are built without error, for example:

`development/internals.rst`

```
.. _internals:

{{ header }}

*********
Internals
*********

# A lot of stuff here and then

.. ipython:: python

   index = pd.MultiIndex.from_product(
       [range(3), ["one", "two"]], names=["first", "second"]
   )
   index
   index.levels
   index.codes
   index.names
```

**Comment by simonjayhawkins** [comment]
Thanks @gepcel for looking into this. I don't think any changes are needed to the documentation as the HTML pages are generated fine. https://pandas.pydata.org/docs/user_guide/visualization.html

The problem is in the pdf generation, where the header that includes imports is incorrectly generated. will look some more

![image](https://user-images.githubusercontent.com/13159005/102366710-e09b4c00-3fb0-11eb-86ed-78d5c3469528.png)

**Comment by gepcel** [comment]
Some information somewhere gave me an impression that the header part `{{header}}` only applies to html format, not pdf.

**Comment by gepcel** [comment]
@simonjayhawkins It is actually weird that that is an `{{ header }}` before `2.14 Visualization`, which suggested something is wrong with the header since the header do the `pandas` and `numpy` imports.

But compared with other chapters like `groupby.rst`:

The header in 'visualization.rst':
```
.. _visualization:

{{ header }}

*************
Visualization
*************
```

And the header in `groupby.rst`:
```
.. _groupby:

{{ header }}

*****************************
Group By: split-apply-combine
*****************************
```

There seems no difference here. And can someone help me what does `.. currentmodule:: pandas` mean, I have googled around with no result.

**Comment by gepcel** [comment]
Did some more research, I think the part doing the pre-imports for latex format is [`ipython_exec_lines`](https://github.com/pandas-dev/pandas/blob/54682234e3a3e89e246313bf8f9a53f98b199e7b/doc/source/conf.py#L430), but not the `{{ header }}`. What I don't understand is:

1. Why the `ipython_exec_lines` works fine for most chapters but not this one?
2. Why does the `{{ header }}` line appear before `2.14 Visualization`, but not other chapters?
3. What's the difference between the two types beginning of every chapter, sometimes there's `.. currentmodule:: pandas` and sometimes `.. _indexing:`?

**Comment by gepcel** [comment]
@jreback Before I understand the mechanism here, the only solution I know is to put the imports at the head of the chapter, like:

```
.. _visualization:

{{ header }}

.. ipython:: python
   :suppress:

   import pandas as pd
   import numpy as np

   
*************
Visualization
*************
```

I don't think this is the *right* solution because of the puzzles I mentioned before. I'll continue to dig and search around and test my ideas. Any help is appreciated. It's also fine by me for someone to take this over.

**Comment by simonjayhawkins** [comment]
The lastest uploaded PDF also has the problems in the visualization section.

for the release we do

```
./make.py html
./make.py zip_html
./make.py latex_forced ||:
./make.py latex_forced
```

I did manage to get the viz section to work but IIRC other sections were corrupted.

I can't remember the order, maybe a clean and build the pdf before the html pages or maybe just run the `./make.py latex_forced` once

so I don't think the docs need to change, but not sure why when we run `./make.py latex_forced` the first time in the sequence above it chooses to only recreate (and corrupt) the viz section.

**Comment by gepcel** [comment]
> I can't remember the order, maybe a clean and build the pdf before the html pages or maybe just run the ./make.py latex_forced once

I've set up developing environments with both windows 10 and ubuntu. `Clean` and `build` pdf before HTML pages with `make.py latex_forced` doesn't work.

The problem is the `imports` (both pd and np) didn't get imported at the beginning of the doc building. I have a guess:

During the HTML building, `{{ header }}` was put at every section with the jinja template mechanism, maybe generated some temporary files, and pdf building was based on those temporary files?
