### ISSUE TITLE
ENH: option to export df to Stata dataset with value labels

### ISSUE THREAD

**Issue by WWakker** [pandas-dev/pandas#38454]
#### Is your feature request related to a problem?

One feature of Stata (.dta) datasets is that it's possible to have categorical columns with numerical values and string value labels. At the moment, `df.to_stata` doesn't have an option to create this kind of columns.

#### Describe the solution you'd like

It would be nice if `df.to_stata` could have a `value_labels` option that accepts a dictionary mapping numerical values to value labels. 

#### API breaking implications

.
#### Describe alternatives you've considered

.
#### Additional context

.

**Comment by Liam3851** [comment]
Can you check that this isn't already happening/supported? Note that the pandas has its own implementation of this feature. Pandas' implementation of numerically-encoded string values is a Categorical dtype with string categories. Thus to the extent pandas would support this it wouldn't be by having a `value_labels` kwarg in the `to_stata` method, but rather by calling `to_stata` on a Categorical-typed object.

I don't have access to Stata to see what this looks like there, but I can verify that if I write out a Categorical Series as Stata format, it is read back as Categorical when using pandas read_stata, so it seems that pandas must be encoding the categories and codes in the Stata file somehow.

```
In [15]: df = pd.DataFrame({'a':['a', 'b', 'a']})

In [16]: df['a'] = df['a'].astype('category')

In [17]: df.to_stata('C:/temp/df.dta', write_index=False)

In [18]: df2 = pd.read_stata('C:/temp/df.dta')

In [19]: df2
Out[19]:
   a
0  a
1  b
2  a

In [20]: df2.dtypes
Out[20]:
a    category
```

Can you verify that using the above code appears in Stata as a categorical variable?

**Comment by WWakker** [comment]
Thank you for looking into this.

I can confirm that df['a'] is indeed read in Stata as a numerical variable with value labels, with 0:'a', 1:'b'. 

I think this gets Stata users most of the way in almost all cases. One remaining problem would be control over the numeric values. In Stata, it is possible to have something like 1:'a', 3:'b'. It appears that the values that the `to_stata` method exports are always ordered from 0 to max, incremented by 1, based on the ordering.

One can change the order of the underlying values by using `Categorical.reorder_categories()` or `Categorical.set_categories()`. But there is no control of the values, is that right?

This is probably not big enough of a problem to implement a new feature though.

**Comment by bashtage** [comment]
General support could be added to non-categoricals in `StataWriter`, `StataWriter117` and `StataWriterUTF8`. The natural syntax would probably be a dictionary of dictionaries where the keys in the other dictionary are column names and the inner dictionary contains the value labels.

**Comment by lmcindewar** [comment]
take
