### ISSUE TITLE
BUG: .loc selection using str datetime label on dataframe with MultiIndex containing datetime column returns series

### ISSUE THREAD

**Issue by kylekeppler** [pandas-dev/pandas#38469]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
df = pd.DataFrame({
    'a': ['20201214 12:00:00', '20201214 12:00:01'],
    'b': [1, 2],  
    'c': [3446, 2342],
    'd': [10, 11]
})
df['a'] = pd.to_datetime(df['a'])
df = df.set_index(['a', 'b'])

# expected this to return a scalar, but returns Series:
df.loc[('2020-12-14 12:00:01', 2), 'c']
a                    b
2020-12-14 12:00:01  2    2342
Name: c, dtype: int64

# returns a scalar as expected:
df.loc[(pd.Timestamp('2020-12-14 12:00:01'), 2), 'c']
2342
```

#### Problem description

I was confused that `.loc[(str, int), str]` returned a series with one value rather than a single scalar (`int` in this case). Research showed that `.at` requires the exact type, so I tried that with `.loc` and got the expected results which is confusing.

#### Expected Output

```python
# returns a scalar:
df.loc[('2020-12-14 12:00:01', 2), 'c']
2342
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.2.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.17763
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.1.3
numpy            : 1.18.1
pytz             : 2020.4
dateutil         : 2.8.1
pip              : 20.3.1
setuptools       : 51.0.0.post20201207
Cython           : None
pytest           : 5.4.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.19.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : 2.7.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
</details>

**Comment by jreback** [comment]
see the docs in partial indexing - this is as expected because a string makes this do a slice selection and not a single point

if u want a point use a Timestamp

**Comment by jreback** [comment]
e.g. https://pandas.pydata.org/docs/user_guide/timeseries.html#indexing

**Comment by kylekeppler** [comment]
Thanks for the clarification, it looks like the important part I missed in the docs is that string label indexing is treated as a slice and thus always returns a non-scalar.
