### ISSUE TITLE
API: EAs should default _is_numeric / _is_boolean

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#38465]
I think we should define

```
@property
def _is_numeric(self) -> bool:
   return False

@property
def _is_boolean(self) -> bool:
   return False
```

on the EA base class.

Just makes less fragile checks on all EAs as we can assume the attributes exist

**Comment by jreback** [comment]
cc @jorisvandenbossche @TomAugspurger @jbrockmendel

**Comment by TomAugspurger** [comment]
We define an `ExtensionDtype.kind`  right? Can we safely define these attributes based on that?

**Comment by jorisvandenbossche** [comment]
We already have this (this is on the base `ExtensionDtype` class): 

https://github.com/pandas-dev/pandas/blob/e91cbd774838ee0189b9b18cb8e234517921e0fe/pandas/core/dtypes/base.py#L297-L324

**Comment by jreback** [comment]
> We already have this (this is on the base `ExtensionDtype` class):
> 
> https://github.com/pandas-dev/pandas/blob/e91cbd774838ee0189b9b18cb8e234517921e0fe/pandas/core/dtypes/base.py#L297-L324

ok its possible code was accessing the *array* and not the *dtype* then. okie. closing.

**Comment by jorisvandenbossche** [comment]
>  its possible code was accessing the array and not the dtype then. okie. closing.

Yeah, it was trying to access the attribute on the string version of the dtype, instead of the dtype object, in this case (but with array same error would have occurred)
