### ISSUE TITLE
CI: --strict option in pytest failing builds

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#38483]
seems we are passing `--strict` to pytest, we must have picked up an updated version and this is now raising: https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=50126&view=logs&j=eab14f69-13b6-5db7-daeb-7b778629410b&t=ce687173-08c6-5301-838d-71b2dda24510

temporarily can just fix the pytest version or just remove this 

cc @pandas-dev/pandas-core

**Comment by jreback** [comment]
and @mroeschke alredy has a PR: https://github.com/pandas-dev/pandas/pull/38478

**Comment by WillAyd** [comment]
Is this different from #38478 ?

**Comment by jreback** [comment]
nope i opened the issue then saw the PR (already merged it as well)
