### ISSUE TITLE
DOC: Missing ipython block in user_guide/indexing.rst

### ISSUE THREAD

**Issue by mzeitlin11** [pandas-dev/pandas#38485]
#### Location of the documentation
https://pandas.pydata.org/docs/user_guide/indexing.html

#### Documentation problem
Looks like a missing ipython block:
<img width="866" alt="Screen Shot 2020-12-14 at 8 20 33 PM" src="https://user-images.githubusercontent.com/37011898/102155736-238edf80-3e4a-11eb-8ae3-db335d755b2b.png">

**Comment by AmalChandru** [comment]
can I look into it.
