### ISSUE TITLE
ENH: Default Excel engine only compatible with XLS files -> replace by new one

### ISSUE THREAD

**Issue by dalonsoa** [pandas-dev/pandas#38498]
#### Is your feature request related to a problem?

With the release of [xlrd 2.0.0 the last 11th of December](https://github.com/python-excel/xlrd/blob/master/CHANGELOG.rst#200-11-december-2020), they drop support for any file format except the (very old) XLS. As this is the default Excel engine for Pandas, it is likely there will be a cascade of complains popping up very soon. 

#### Describe the solution you'd like

Replace the default `xlrd` engine by another engine compatible with modern file formats, maybe [openpyxl](https://openpyxl.readthedocs.io/en/stable/).

#### API breaking implications

Shouldn't have any... I think. 

#### Describe alternatives you've considered

There is a bunch of other possible alternative engines: http://www.python-excel.org

#### Additional context

None

**Comment by asishm** [comment]
duplicate of #38424
