### ISSUE TITLE
BUG: method fillna not working when supplied value is a dict

### ISSUE THREAD

**Issue by etiennekintzler** [pandas-dev/pandas#38520]
#### Reproducible example

```python
import pandas as pd

s = pd.Series([{"a": 1}, None])
s.fillna({"a": 0})
```

returns:
```python
0    {'a': 1}
1         NaN
dtype: object
```

The error is the same when using `np.nan` instead of None.

#### Problem description

The fillna method does not work when the supplied value is a dict.

#### Expected Output

```python
0    {'a': 1}
1    {'a': 0}
dtype: object
```

#### Problem identification

I check the internals of `NDFrame.fillna` the problem seems to be the following lines : 
https://github.com/pandas-dev/pandas/blob/122d50246bcffcf8c3f252146340ac02676a5bf6/pandas/core/generic.py#L6379-L6382
Indeed these lines build the value as :  
```python
value = create_series_with_explicit_dtype(dict(a=0), dtype_if_empty=object)
```
which returns
```
a    0
dtype: int64
```
This index has no overlap with `s.index` and reindex value is :
```python
0   NaN
1   NaN
dtype: float64
```
which seems wrong.

However passing the dict value without the transformation done in the block beginning `if isinstance(value, (dict, ABCSeries))` seems to work fine  : 

```python
new_data = s._mgr.fillna(value=dict(a=0), downcast=None, inplace=None, limit=None)
s._constructor(new_data)

#returns
#0    {'a': 0}
#1    {'a': 1}
#dtype: object
```

(not saying that this approach should be pursue since I am not familiar with pandas internals and thus don't know what the consequences of doing like this could be)

INSTALLED VERSIONS
------------------
commit           : b5958ee1999e9aead1938c0bba2b674378807b3d
python           : 3.8.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-122-generic
Version          : #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.5
numpy            : 1.19.4
pytz             : 2020.4
dateutil         : 2.8.1
pip              : 20.2.2
setuptools       : 50.3.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.4
sqlalchemy       : 1.3.20
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by simonjayhawkins** [comment]
Thanks @etiennekintzler for the report.

a dictionary passed to `Series.fillna` is not treated a scalar value. see https://pandas.pydata.org/docs/reference/api/pandas.Series.fillna.html

nested datastructures are not natively supported in pandas yet.

however, the following appears to work in this case.

```
>>> pd.__version__
'1.3.0.dev0+83.g122d50246b'
>>>
>>> s = pd.Series([{"a": 1}, None])
>>>
>>> s[s.isna()] = {"a": 0}
>>> s
0    {'a': 1}
1    {'a': 0}
dtype: object
>>>
```

**Comment by etiennekintzler** [comment]
Hey @simonjayhawkins !

Thank for your quick answer 👍

The usage of dict is quite clear regarding `DataFrame` ; however I don't see the value of having this feature for `Series` since it implies knowing the position of the NaN and usually just one scalar value would be used.
