### ISSUE TITLE
QST: error while using pickle to load the files

### ISSUE THREAD

**Issue by sagar-m** [pandas-dev/pandas#38538]
Hi, I am getting the below error while using pickle to load the files on kaggle. It has worked for everyone, but it is not working for me. The file path is correct. Thank you for your help.

```

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<timed exec> in <module>

/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py in read_pickle(filepath_or_buffer, compression)
    167     if not isinstance(fp_or_buf, str) and compression == "infer":
    168         compression = None
--> 169     f, fh = get_handle(fp_or_buf, "rb", compression=compression, is_text=False)
    170 
    171     # 1) try standard library Pickle

/opt/conda/lib/python3.7/site-packages/pandas/io/common.py in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors)
    497         else:
    498             # Binary mode
--> 499             f = open(path_or_buf, mode)
    500         handles.append(f)
    501 

FileNotFoundError: [Errno 2] No such file or directory: '../input/riiid-cross-validation-files/cv2_train.pickle'
```

**Comment by rhshadrach** [comment]
Thanks for the report. From what can be discerned, it appears your usage of pandas is correct. As for why you're getting the error, I don't believe that's relevant to pandas.

In the future, this question would be more appropriate for StackOverflow. As you were instructed when writing the issue, please ask there first and if you don't get a satisfactory answer, then okay to ask here (with a link to the SO question).

**Comment by sagar-m** [comment]
Hi, I had posted this issue on [stackoverflow](https://stackoverflow.com/questions/65353252/qst-error-while-using-pickle-to-load-the-files), but it remains unsolved. Thank you.

**Comment by jreback** [comment]
@sagar-m this is not a pandas issue - your file is not found

try using an absolute path
