### ISSUE TITLE
ENH: add ignore_index to DataFrame / Series.sample 

### ISSUE THREAD

**Issue by erfannariman** [pandas-dev/pandas#38581]
#### Is your feature request related to a problem?

When sampling a dataframe / series we get the original index back by default, which is good, but we should add an option to ignore the index to keep it consistent with other methods like `drop_duplicates` and `explode` for example.
#### Describe the solution you'd like

Add `ignore_index` argument to Series/DataFrame.sample.
#### API breaking implications

None as far as I can tell.

```python
df = pd.DataFrame(
    {"col1": range(10, 20), "col2": range(20, 30), "colString": ["a"] * 10}
)
df.sample(n=3, ignore_index=True)

   col1  col2 colString
0    14    24         a
1    17    27         a
2    11    21         a
```

**Comment by skvrahul** [comment]
take

**Comment by skvrahul** [comment]
@erfannariman Doesn't `df.reset_index` serve the same purpose in this case?

**Comment by erfannariman** [comment]
I actually wanted to work on this, was waiting till one of the devs approved the enhancement. But no worries, I guess you can take it.

**Comment by erfannariman** [comment]
I actually wanted to work on this if you don't mind. I was waiting till one of the core devs approved the change.

**Comment by jreback** [comment]
yep this is ok to do

**Comment by erfannariman** [comment]
Thanks @jreback , @skvrahul you mind if I pick this one up? My bad I didn't "take" before.

**Comment by skvrahul** [comment]
> Thanks @jreback , @skvrahul you mind if I pick this one up? My bad I didn't "take" before.

Sure. No worries! :)
I've unassigned myself

**Comment by erfannariman** [comment]
take
