### ISSUE TITLE
Performance regression in DataFrame reduction ops

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#38592]
The `stat_ops.FrameOps` are generally showing a slowdown since a few days, see eg https://pandas.pydata.org/speed/pandas/#stat_ops.FrameOps.time_op?python=3.8&Cython=0.29.21&p-op='mean'&p-dtype='int'&p-axis=0&commits=8dbb593d-7043f8fa

The indicated range is https://github.com/pandas-dev/pandas/compare/8dbb593d...7043f8fa, but don't directly see which commit might be the cause cc @jbrockmendel

**Comment by IngErnestoAlvarez** [comment]
I think it's in this commit: 7043f8fa9d4d97782ec0d0d1a4c3b57573a7fc21.
Where `astype` function was deleted and replaced with `astype_nansafe` on "pandas/core/indexes/base.py::Index::astype" method.
Before, it only calls `astype_nansafe` if this condition was true `is_integer_dtype(dtype) and not is_extension_array_dtype(dtype)`.
Now it calls it every time. 
That can be the issue. "pandas/core/indexes/numeric.py::NumericIndex::astype" method did manage to know when to call `astype_nansafe` and when to call directly `super().astype`. Now that it's deleted, it always call `astype_nansafe`.

**Comment by jorisvandenbossche** [comment]
That commit has been reverted, but that didn't seem to have solved the performance regression. 

@jbrockmendel can you look into this?

**Comment by jbrockmendel** [comment]
> That commit has been reverted, but that didn't seem to have solved the performance regression.

does this mean we can un-revert?  its a nice little cleanup

> can you look into this?

cant make any promises at the moment, but ill keep a tab open for this so it doesnt fall off the radar screen entirely.

**Comment by jorisvandenbossche** [comment]
> does this mean we can un-revert?

No, it was reverted because of a behaviour regression -> https://github.com/pandas-dev/pandas/issues/38607

> cant make any promises at the moment, but ill keep a tab open for this so it doesnt fall off the radar screen entirely.

If you can't look at it on the short term, I would propose to revert the change for now, until you have time (otherwise later it might become much more difficult to do that, if it turns out to be needed). 
From quickly testing the different potential commits in the range, it seems https://github.com/pandas-dev/pandas/pull/38507 is the cause of the slowdown.

**Comment by jorisvandenbossche** [comment]
Ah, I think the reason is that it is now doing a non-copy ravel, while before the copying ravel ensured we would have good layout for a performant reduction (while this is not the case when the DataFrame is created from a 2D numpy array).

**Comment by jbrockmendel** [comment]
Huh, and to think I made a non-copying ravel specifically with perf in mind.  you learn something every day

**Comment by simonjayhawkins** [comment]
@jbrockmendel @jorisvandenbossche Any idea what the status is here?

**Comment by jbrockmendel** [comment]
Fixed by #41911/#41924

**Comment by simonjayhawkins** [comment]
> Fixed by #41911/#41924

These are for the recent perf regression? This issue is quite old.

**Comment by jbrockmendel** [comment]
my mistake, i thought this was the one discussed on the call on wednesday.  no idea off the top of my head what the status is here.

**Comment by jorisvandenbossche** [comment]
This is still causing a regression in the reductions (for integer dtypes) compared to 1.2.x. 
Just re-ran some benchmarks, and it's giving a 2.5 to 3.5 slowdown for sum and mean.

**Comment by jorisvandenbossche** [comment]
Now, based on my comment above (https://github.com/pandas-dev/pandas/issues/38592#issuecomment-751824815), this might depend on the memory layout of the DataFrame, and thus on how the DataFrame was created. 

But so we maybe should remove some of the extra code added in https://github.com/pandas-dev/pandas/pull/38507 to ensure the memory layout is preserved in the `ravel()` call, since that doesn't seem to be helpful (at least based on this single benchmark ..)
