### ISSUE TITLE
BUG:Issue Concerning Ambiguous Numpy Array Shape in Column

### ISSUE THREAD

**Issue by tlplayer** [pandas-dev/pandas#38599]
I spent multiple hours wondering why my dataframe was not fitting well into my tf model but it was the fact that the shape of the numpy array was not inferred and thus left ambiguous. I suggest, having a warning or a strict option for what shape is allowed within the column.

https://stackoverflow.com/questions/65383794/tensorflow-fails-to-interpret-what-is-stored-in-numpy-ndarray/65384804?noredirect=1#comment115597094_65384804

**Comment by jreback** [comment]
pls post a reproducible example

**Comment by tlplayer** [comment]
```python
import pandas as pd
import numpy as np

def foo(num):
    return np.array([num,num])

L = [1]
df = pd.DataFrame([L])
df['Nums'] = df.loc[0].apply(foo)
print(df['Nums'].values.shape)
print(df['Nums'].values[0].shape)

L = []
for n in df['Nums']:
    L.append(n)
print(L)
nums = np.array(L)
print(nums.shape)

```

> (1,)
(2,)
[array([1, 1])]
(1, 2)

**Comment by tlplayer** [comment]
The numpy shape was not infered for whatever reason. So when you deal with image data as is typical with pandas, TF can't convert because it doesn't know the shape of the numpy array.

**Comment by simonjayhawkins** [comment]
@tlplayer `df['Nums'].values` is a 1-d object array of 1-d numpy arrays so the pandas behaviour looks correct to me, but I maybe missing something. can you be explicit about where the pandas behaviour is incorrect and what the expected behaviour is.

```
>>> df["Nums"] = df.loc[0].apply(foo)
>>> df
   0    Nums
0  1  [1, 1]
>>>
>>> df["Nums"].values
array([array([1, 1])], dtype=object)
>>>
>>> print(df["Nums"].values.shape)
(1,)
>>>
>>> print(df["Nums"].values[0].shape)
(2,)
>>>
```

**Comment by tlplayer** [comment]
Hello @simonjayhawkins,

The problem comes from the .apply function where the shape of the DF is not inferred. Look below for an example. What should happen is the user can maintain the shape or mandate the shape of the column. The apply function creates a different df than the pd.DataFrame function applied to the numpy array. Because convert_to_tensor can't decipher what the shape of an image numpy array is and therefore henders easy transition. So either warn the user, allow them to dictate the shape or something better than what I'm thinking. 

```python
import pandas as pd
import numpy as np

def foo(num):
    return np.array([num,num])

print()
print("Dataframe from apply functionality")
print()
L = [1]
df = pd.DataFrame([L])
df['Nums'] = df.loc[0].apply(foo)
print(df['Nums'].values.shape)
print(df['Nums'].values[0].shape)

print()
print("Dataframe from list ")
print()
L = []
for n in df['Nums']:
    L.append(n)
print(L)
nums = np.array(L)
print(nums.shape)

print()
print("New DF from Numpy array:")
print()
new_df = pd.DataFrame(nums)
print(new_df)
print(new_df.values)
print(new_df.values.shape)
```
> 
Dataframe from apply functionality

(1,)
(2,)

Dataframe from list 

[array([1, 1])]
(1, 2)

New DF from Numpy array:

   0  1
0  1  1
[[1 1]]
(1, 2)

**Comment by simonjayhawkins** [comment]
> What should happen is the user can maintain the shape or mandate the shape of the column.

a pandas column is one dimensional. you probably want to create a DataFrame instead?

**Comment by tlplayer** [comment]
This is just an example. Look at the stackoverflow link for a more practical example.

**Comment by MarcoGorelli** [comment]
Hi @tlplayer 

There's lots of open issues, and we're all time-constrained - to expedite resolution, could you please post:
- a simple reproducible example
- the actual output
- what you would expect the output to be

From the above, this isn't that clear - people will be much more likely to help resolve an issue if it's really easy to reproduce and really easy to see what might be wrong

**Comment by tlplayer** [comment]
I don't know how to further explain this. The best I can do is to tell anyone who runs across the same error to be careful with the apply function.

**Comment by venaturum** [comment]
@tlplayer

Stepping through your examples, the output you have supplied is exactly what I'd expect it to be.

I'm wondering, if you replace np.array with pd.Series in your foo function, do you get the result you are wanting?

Hard to be much more help without having you do those steps as outlined by @MarcoGorelli.

**Comment by tlplayer** [comment]
I'm just going to close this as it's more of a "You should know" kind of thing for the user.
