### ISSUE TITLE
REGR: astype(str) of object array with byte objects

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#38607]
On released version, we see this behaviour:

```
In [1]: idx = pd.Index(['あ', b'a'], dtype='object')

In [2]: idx
Out[2]: Index(['あ', b'a'], dtype='object')

In [4]: idx.astype(str)
Out[4]: Index(['あ', 'a'], dtype='object')
```

So where the `bytes` object `b"a"` gets converted to the string `"a"`.

On master (since a few days), however, we now get:

```
In [7]: idx.astype(str)
Out[7]: Index(['あ', 'b'a''], dtype='object')
```

so where the `bytes` object gets converted to the string `"b'a'"`

Possibly due to https://github.com/pandas-dev/pandas/pull/38518 cc @jbrockmendel

**Comment by simonjayhawkins** [comment]
> Possibly due to #38518 cc @jbrockmendel

can confirm, first bad commit: [7043f8fa9d4d97782ec0d0d1a4c3b57573a7fc21] REF: use astype_nansafe in Index.astype (#38518)

**Comment by simonjayhawkins** [comment]
hit the revert button b4 becomes more difficult to revert.. https://github.com/pandas-dev/pandas/pull/38610

**Comment by jbrockmendel** [comment]
reverting makes sense short term.

longer-term, does this affect other places where astype_nansafe is called?
