### ISSUE TITLE
DOC: example for doing a reversed rolling window

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#38627]
https://github.com/pandas-dev/pandas/issues/34226#issuecomment-690887774 is the example, should just add to window.rst

also would be good to show using https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.api.indexers.FixedForwardWindowIndexer.html?highlight=forward#pandas.api.indexers.FixedForwardWindowIndexer

**Comment by willb0246** [comment]
Just submitted a PR for this

**Comment by MaruthiKo** [comment]
Dear Developer, 
I am new to open source contributions and I would like to contribute. Can someone pls help me up with how and where do I start?

**Comment by mzeitlin11** [comment]
Hi @MaruthiKo, welcome to pandas! I'd recommend reading https://pandas.pydata.org/docs/development/contributing.html for guidance on contribution to pandas. If you'd like to work on this issue, the `Contributing to the documentation` section should be particularly useful.

**Comment by vangorade** [comment]
looks like issue is still not resolved let me fix it real quick.

**Comment by vangorade** [comment]
take

**Comment by hvp004** [comment]
Is this available to take? I see no updates in almost 2 months.

**Comment by mdhsieh** [comment]
I can make suggested changes from the closed pull request.

**Comment by mdhsieh** [comment]
take
