### ISSUE TITLE
BUG: tm.assert_produces_warning() doesn't work with expected_warning=None or False

### ISSUE THREAD

**Issue by mzeitlin11** [pandas-dev/pandas#38620]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import warnings
import pandas._testing as tm

with tm.assert_produces_warning(None):
    warnings.warn(UserWarning)

with tm.assert_produces_warning(False):
    warnings.warn(RuntimeWarning)
```

#### Problem description

Docs for this function say "To check that no warning is returned, specify ``False`` or ``None``". It also includes the second example as something that should raise an `AssertionError`. However, both these examples do not raise.

#### Expected Output

Raise `AssertionError` for both.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 9a46a4b700d1b794d9a944928ac95f4cb742b259
python           : 3.8.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
Version          : Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.3.0.dev0+125.g9a46a4b70
numpy            : 1.19.4
pytz             : 2020.4
dateutil         : 2.8.1
pip              : 20.3.1
setuptools       : 49.6.0.post20201009
Cython           : 0.29.21
pytest           : 6.2.0
hypothesis       : 5.43.3
sphinx           : 3.3.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.2
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.8.4
fastparquet      : 0.4.1
gcsfs            : 0.7.1
matplotlib       : 3.3.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : 2.0.0
pyxlsb           : None
s3fs             : 0.4.2
scipy            : 1.5.3
sqlalchemy       : 1.3.20
tables           : 3.6.1
tabulate         : 0.8.7
xarray           : 0.16.2
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.52.0

</details>

**Comment by mzeitlin11** [comment]
take

**Comment by simonjayhawkins** [comment]
first bad commit: [77811c78e2b3356a43174675ae066091aad92785] ENH: implement matching warning message (#37263)
