### ISSUE TITLE
BUG: `DataFrame.corrwith` seems to be broken

### ISSUE THREAD

**Issue by acturner** [pandas-dev/pandas#38647]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
>>> import numpy as np; import pandas as pd
>>> x = pd.DataFrame(np.random.randn(100, 3), columns=['A', 'B', 'C'])
>>> y = pd.DataFrame(np.random.randn(100, 3), columns=['X', 'Y', 'Z'])
>>> x.corrwith(y)
A   NaN
B   NaN
C   NaN
D   NaN
E   NaN
F   NaN
dtype: float64
```

#### Problem description

I believe that this is a bug, and that if it is intended behavior, it should not be so.

#### Expected Output

Expected output is the cross-correlations between `self` and `other`:
```
>>> x.corrwith(y)
          A         B         C
X -0.144123 -0.063604  0.008358
Y -0.097303 -0.032101 -0.127265
Z  0.032475  0.037129  0.082559
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : b5958ee1999e9aead1938c0bba2b674378807b3d
python           : 3.8.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.2.0
Version          : Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.5
numpy            : 1.19.4
pytz             : 2020.4
dateutil         : 2.8.1
pip              : 20.3.3
setuptools       : 51.0.0
Cython           : None
pytest           : 6.2.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.19.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 2.0.0
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.4
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.52.0

</details>

**Comment by mzeitlin11** [comment]
I think this is expected behavior, the docs say "DataFrames are first aligned along both axes before computing the correlations." `corrwith` always returns a `Series` because it only compares each column/row to a single corresponding column/row.

Adapting your example with using matching column names:
```
>>> y = pd.DataFrame(np.random.randn(100, 3), columns=['A', 'B', 'C'])
>>> x.corrwith(y)

A   -0.026583
B   -0.098419
C   -0.010372
dtype: float64
```

For correlations between `x` and `y`, 
```
pd.concat((x, y), axis=1).corr().loc[y.columns, x.columns]
```
gives your expected output.
