### ISSUE TITLE
why not check the column order and type consistent before use ‘appand’ mode in to_csv or equivalent ops such as to_sql?

### ISSUE THREAD

**Issue by svjack** [pandas-dev/pandas#38656]
as the title say, when i append a column permutation of a exists dataframe to a exists(saved)
csv file, the column permutation df not reordered by the exist header in csv file.
one reason i can understand is that not all csv file have header in the first row, so 
this design seems reasonable, but for many cases, if the source code reordered for
our append op which have header or table column, this may be more convenient.
same problem to type.

**Comment by rhshadrach** [comment]
The use case makes sense, but I don't think it needs to be baked into the API. When columns match and there aren't duplicate labels, this is easy to accomplish (see below). If the labels are duplicated or not the same set, I'd imagine the only safe thing to do would be to raise.

```
df1 = pd.DataFrame({'a': [1, 2], 'b': [3, 4]})
df2 = pd.DataFrame({'b': [5, 6], 'a': [7, 8]})

df1.to_csv('test.csv', index=False, mode='w')
columns = pd.read_csv('test.csv', nrows=0).columns
df2[columns].to_csv('test.csv', index=False, mode='a', header=False)
print(pd.read_csv('test.csv'))
```

gives

```
   a  b
0  1  3
1  2  4
2  7  5
3  8  6
```

**Comment by svjack** [comment]
> The use case makes sense, but I don't think it needs to be baked into the API. When columns match and there aren't duplicate labels, this is easy to accomplish (see below). If the labels are duplicated or not the same set, I'd imagine the only safe thing to do would be to raise.
> 
> ```
> df1 = pd.DataFrame({'a': [1, 2], 'b': [3, 4]})
> df2 = pd.DataFrame({'b': [5, 6], 'a': [7, 8]})
> 
> df1.to_csv('test.csv', index=False, mode='w')
> columns = pd.read_csv('test.csv', nrows=0).columns
> df2[columns].to_csv('test.csv', index=False, mode='a', header=False)
> print(pd.read_csv('test.csv'))
> ```
> 
> gives
> 
> ```
>    a  b
> 0  1  3
> 1  2  4
> 2  7  5
> 3  8  6
> ```

i know it is simple, but many incremental data merge framework have done it.
particularly with to_sql in mode a , i think it is necessary.

**Comment by jreback** [comment]
this is combining 2 different functions in pandas which each are pretty complicated

this is much better done in an external framework / library

i suppose we could optionally support this in pandas then (my point is that we don't want to maintain this possibly messy inference code)

**Comment by svjack** [comment]
> this is combining 2 different functions in pandas which each are pretty complicated
> 
> this is much better done in an external framework / library
> 
> i suppose we could optionally support this in pandas then (my point is that we don't want to maintain this possibly messy inference code)
> 
> 
Dose pandas have contrib library as tensorflow have?

**Comment by jreback** [comment]
no

**Comment by rhshadrach** [comment]
@svjack Using to_sql already produces the desired behavior:

```
import sqlalchemy

df1 = pd.DataFrame({'a': [1, 2], 'b': [3, 4]})
df2 = pd.DataFrame({'b': [5, 6], 'a': [7, 8]})

con = sqlalchemy.create_engine("sqlite:///:memory:")
df1.to_sql("test", con, index=False)
df2.to_sql("test", con, index=False, if_exists="append")

print(pd.read_sql("test", con))
```

produces

```
   a  b
0  1  3
1  2  4
2  7  5
3  8  6
```

**Comment by svjack** [comment]
> @svjack Using to_sql already produces the desired behavior:
> 
> ```
> import sqlalchemy
> 
> df1 = pd.DataFrame({'a': [1, 2], 'b': [3, 4]})
> df2 = pd.DataFrame({'b': [5, 6], 'a': [7, 8]})
> 
> con = sqlalchemy.create_engine("sqlite:///:memory:")
> df1.to_sql("test", con, index=False)
> df2.to_sql("test", con, index=False, if_exists="append")
> 
> print(pd.read_sql("test", con))
> ```
> 
> produces
> 
> ```
>    a  b
> 0  1  3
> 1  2  4
> 2  7  5
> 3  8  6
> ```

have you try hive engine created by sqlalchemy?

**Comment by rhshadrach** [comment]
No, I have not. Please feel free to post the code/results here.

**Comment by mroeschke** [comment]
It appears that the discussion here has gotten stale and `to_sql` tentatively already has the necessary functionality. Closing to happy to reopen if not the case
