### ISSUE TITLE
Split up pandas/tests/io/pytables/test_store.py into smaller modules

### ISSUE THREAD

**Issue by moink** [pandas-dev/pandas#38687]
pandas/tests/io/pytables/test_store.py is more than 5000 lines long, which is pretty long for a test module. It would be good to break it up into smaller, logical pieces, each in its own test module.

Came out of PR 38609.

OT: @moink love to split this file up: pandas/tests/io/pytables/test_store.py in a separate PR :->

_Originally posted by @jreback in https://github.com/pandas-dev/pandas/issues/38609#issuecomment-749256512_

**Comment by mzeitlin11** [comment]
xref #26807

**Comment by moink** [comment]
Ah, sorry, looks like it's a duplicate with #26807. Feel free to remove this issue.
