### ISSUE TITLE
ASV: Add benchmark for indexing with .loc for sorted/unsorted DatetimeIndex

### ISSUE THREAD

**Issue by mzeitlin11** [pandas-dev/pandas#38690]
xref #17754, a benchmark should be added for indexing with .loc for sorted/unsorted `DatetimeIndex`. With a constructed `DatetimeIndex`, for example

```python
dates = pd.date_range('2011-1-1', periods=500000, freq='min')
index = np.random.choice(dates, 500000, replace=True)
df = pd.DataFrame(index=index, data={'a': 1})
df_sorted = df.sort_index()
```

the behavior of interest to benchmark is
```python
df.loc['2011-6-11']
```
and 
```python
df_sorted.loc['2011-6-11']
```

**Comment by kuspia** [comment]
I would like to do this can you please guide me how can I and what are files that are supposed to be changed and added

**Comment by ngcd04-fa07** [comment]
Hey
This would be my first open-source contribution, and I'd love to work on this. Would you please assign this to me and guide me a bit as to what needs to be done?
Thank you

**Comment by mzeitlin11** [comment]
Anyone is welcome to work on this! Just comment "take" and you'll be automatically assigned. See https://pandas.pydata.org/docs/development/contributing_codebase.html#running-the-performance-test-suite for additional information about the task of adding a benchmark
