### ISSUE TITLE
BUG: Pandas 1.2.0 not importing numpy

### ISSUE THREAD

**Issue by brendanahart** [pandas-dev/pandas#38712]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [X] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

Collecting pandas
222
  Downloading http://*private-pypi-repo*/root/pypi/%2Bf/e03/386615b970b8b/pandas-1.2.0.tar.gz (5.4 MB)
223
  Installing build dependencies: started
224
  Installing build dependencies: finished with status 'done'
225
  Getting requirements to build wheel: started
226
  Getting requirements to build wheel: finished with status 'error'
227
  ERROR: Command errored out with exit status 1:
228
   command: /usr/local/bin/python /usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpyzo8hnvu
229
       cwd: /tmp/pip-install-wsvw3tn6/pandas_0107e3e2e0984808803b03b19130c9e4
230
  Complete output (18 lines):
231
  Traceback (most recent call last):
232
    File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
233
      main()
234
    File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
235
      json_out['return_val'] = hook(**hook_input['kwargs'])
236
    File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
237
      return hook(config_settings)
238
    File "/tmp/pip-build-env-isjnq9ut/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 150, in get_requires_for_build_wheel
239
      config_settings, requirements=['wheel'])
240
    File "/tmp/pip-build-env-isjnq9ut/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
241
      self.run_setup()
242
    File "/tmp/pip-build-env-isjnq9ut/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 254, in run_setup
243
      self).run_setup(setup_script=setup_script)
244
    File "/tmp/pip-build-env-isjnq9ut/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 145, in run_setup
245
      exec(compile(code, __file__, 'exec'), locals())
246
    File "setup.py", line 20, in <module>
247
      import numpy
248
  ModuleNotFoundError: No module named 'numpy'

#### Problem description

When I am downloading pandas 1.2.0 to build my docker image for my python project, I am getting the following error above. Numpy seems to be not importing for some reason. The excepted output would be what was when I building the image yesterday (before the release)

#### Expected Output

Collecting pandas
214
  Downloading http://*private-pypi-repo*/root/pypi/%2Bf/f10/fc41ee3c75a47/pandas-1.1.5.tar.gz (5.2 MB)
215
  Installing build dependencies: started
216
  Installing build dependencies: still running...
217
  Installing build dependencies: still running...
218
  Installing build dependencies: still running...
219
  Installing build dependencies: finished with status 'done'
220
  Getting requirements to build wheel: started
221
  Getting requirements to build wheel: still running...
222
  Getting requirements to build wheel: finished with status 'done'
223
    Preparing wheel metadata: started
224
    Preparing wheel metadata: finished with status 'done'
225
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/pytz/

**Comment by jreback** [comment]
3.6 is not supported by either latest numpy or 1.2 in pandas

**Comment by brendanahart** [comment]
Sweet, thanks I've updated to 3.8 in my docker image and things are building now. 

Cheers,
Brendan
