### ISSUE TITLE
DOC: chat-ops

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#38726]
xref https://github.com/pandas-dev/pandas/pull/38444#issuecomment-749711369

There are some GitHub Actions workflows which can be triggered via comments:

1. If you comment `@github-actions pre-commit` on a pull request, it will trigger a workflow which will autofix formatting errors (e.g. from `black` or `isort`)
2. `@meeseeksdev backport ` will trigger a workflow which will backport a given change to a branch (e.g. `@meeseeksdev backport 1.2.x`)
3. If you comment `take` on an issue, it will trigger a workflow which will assign the issue to you

These should be documented somewhere in the docs - I think `doc/source/development/contributing.rst` might be a sensible location. `take` is already documented in there, but the other two aren't

**Comment by 1nF0rmed** [comment]
Hey, I would like to work on this

**Comment by MarcoGorelli** [comment]
sure, if you comment `take` it'll be assigned to you
