### ISSUE TITLE
pandas.Series.to_json() incorrectly localizes tz-naive datetimes to UTC

### ISSUE THREAD

**Issue by dactrungnguyen** [pandas-dev/pandas#38760]
Seemingly related but not identical to #12997
## How to reproduce the bug
Checked with pandas 0.24.2, 1.1.5 and 1.2.0.
```
import pandas as pd

index = pd.date_range(
    start='2020-12-28 00:00:00',
    end='2020-12-28 02:00:00',
    freq='1H',
)
a = pd.Series(
    data=range(3),
    index=index,
)
a.to_json(date_format='iso')
```
## Output
```
'{"2020-12-28T00:00:00.000Z":0,"2020-12-28T01:00:00.000Z":1,"2020-12-28T02:00:00.000Z":2}'
```
(Notice the "Z" indicating UTC)
## Expected output
```
'{"2020-12-28T00:00:00.000":0,"2020-12-28T01:00:00.000":1,"2020-12-28T02:00:00.000":2}'
```
(without "Z")

**Comment by dactrungnguyen** [comment]
Solving #12997 should close this issue as well.

**Comment by jreback** [comment]
> Seemingly related but not identical to #12997

how so?

**Comment by dactrungnguyen** [comment]
> how so?
Related: #12997 _may_ be at the root of the present issue because `pandas.Series.to_json()` calls `pandas.io.json.to_json()`, which is the object of #12997.
Not identical:
- #12997 does not mention `pandas.Series.to_json()` explicitely
- #12997 mentions timezone conversion on a tz-aware timestamp, while the present issue mentions localization of tz-naive timestamps.
