### ISSUE TITLE
DOC: Undocumented change in .isin behavior from 1.1.5 to 1.2.0

### ISSUE THREAD

**Issue by StefanBRas** [pandas-dev/pandas#38781]
#### Location of the documentation
https://pandas.pydata.org/docs/whatsnew/v1.2.0.html

#### Documentation problem
There seems to be an undocumented change with how `isin` works.
pandas 1.1.5:
```python
import pandas as pd
pd.Series([0]).isin(['0']) 
# 0    True
# dtype: bool
pd.Series([1]).isin(['1']) 
# 0    True
# dtype: bool
pd.Series([1.1]).isin(['1.1']) 
# 0    True
# dtype: bool
```
But in pandas 1.2.0 (and 1.2.0rc):
```python
import pandas as pd
pd.Series([0]).isin(['0']) 
# 0    False
# dtype: bool
pd.Series([1]).isin(['1']) 
# 0    False
# dtype: bool
pd.Series([1.1]).isin(['1.1']) 
# 0    False
# dtype: bool
```

But the release notes mentions nothing about it.
I have not posted this issue as an bug,  because I think the newer implementation is the better implementation.
However I propose adding the change to the release notes for other people like me where the change broke tests in a pipeline.

#### Suggested fix for documentation

Add a line mentioning that `isin` no longer returns true when comparing floats to a string of the float.

**Comment by jreback** [comment]
hmm we did a lot of fixing on isin. likley: https://github.com/pandas-dev/pandas/pull/37528

we would need validation tests for this as it works on master. happy to take a PR. your examples in the doc-string would be great as well.

**Comment by StefanBRas** [comment]
So adding tests for it here: https://github.com/pandas-dev/pandas/blob/master/pandas/tests/test_algos.py#L812?
I'm not sure which doc-string you're refering to here.

**Comment by jreback** [comment]
> So adding tests for it here: https://github.com/pandas-dev/pandas/blob/master/pandas/tests/test_algos.py#L812?
> I'm not sure which doc-string you're refering to here.

yep

https://github.com/pandas-dev/pandas/blob/master/pandas/core/series.py#L4584

**Comment by StefanBRas** [comment]
It looks like there already are tests for this:
https://github.com/pandas-dev/pandas/blob/master/pandas/tests/test_algos.py#L1047
And it looks like there has been some discussion about it in https://github.com/pandas-dev/pandas/pull/38346
Which means that https://github.com/pandas-dev/pandas/issues/34125 and https://github.com/pandas-dev/pandas/issues/19356 can probably be closed.

**Comment by simonjayhawkins** [comment]
fixed in [4699c2b0994c131733c1028fc05fe6b7c41f76a8] BUG: isin numeric vs string (#38279), no release note added.

**Comment by omarafifii** [comment]
Hi, 
I am willing to work on this issue. 
I understand I should add the missing part in the release notes, but I am not sure if I should do something with the testing.

**Comment by erfannariman** [comment]
> Hi,
> I am willing to work on this issue.
> I understand I should add the missing part in the release notes, but I am not sure if I should do something with the testing.

The tests seem to be there as mentioned by @StefanBRas , seems like only release notes are added.

**Comment by omarafifii** [comment]
Ok, I can do it.

**Comment by phofl** [comment]
#34125 still persists
