### ISSUE TITLE
BUG: pd.testing.makeMultiIndex ignores k parameter

### ISSUE THREAD

**Issue by ivirshup** [pandas-dev/pandas#38795]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
assert len(pd.testing.makeMultiIndex(k=10)) == 4
```

https://github.com/pandas-dev/pandas/blob/0976c4ca0276a333346619c5a9e3c92631ec7006/pandas/_testing/__init__.py#L491-L492

#### Problem description

All other `testing.make*Index` methods take a parameter `k` which lets you specify the length. `makeMultiIndex` explicitly takes this parameter but does nothing with it.

#### Expected Output

```python
assert len(pd.testing.makeMultiIndex(k=10)) == 10
```

**Comment by ShashankR87** [comment]
Hey, I would like to contribute to solving this issue. This would be my first contribution.
Could you please provide some more info about the issue and what is supposed to happen?

**Comment by RaphaelAzev** [comment]
@ShreyasPatel031 Are you still working on this? I would like to contribute if aswell if possible

**Comment by bobquest33** [comment]
This ticket is still open if this is fixed, should it not be closed

**Comment by jreback** [comment]
this is not fixed 
PRs were closed as stale
