### ISSUE TITLE
CLN: Add typing for dtype argument in codebase

### ISSUE THREAD

**Issue by avinashpancham** [pandas-dev/pandas#38808]
Follow up from #37546 and #38680 

Add typing for the `dtype` argument throughout the pandas codebase. Part of the code might need an update after adding the type since the mypy type checks can fail.

 In #38680 it is already done for `io/sql.py`, from a directory search I found that the list of files below still have untyped dtype arguments. 

Would be great if people can work on a few files at a time in separate PRs and mention this issue. I will already start with the remaining files in the io directory

- [x] io/parsers.py
- [x] io/excel/_base.py
- [x] io/json/_json.py
- [x] io/pytables.py
- [x] core/arrays/datetimelike.py
- [x] core/arrays/base.py
- [x] core/arrays/boolean.py
- [x] core/arrays/categorical.py
- [x] core/arrays/integer.py
- [x] core/arrays/interval.py
- [x] core/arrays/masked.py
- [x] core/arrays/numpy_.py
- [x] core/arrays/period.py
- [x] core/arrays/sparse/array.py
- [x] core/arrays/string_.py
- [x] core/arrays/string_arrow.py
- [x] core/arrays/timedeltas.py
- [x] core/indexes/category.py
- [x] core/indexes/datetimes.py
- [x] core/indexes/interval.py
- [x] core/indexes/numeric.py
- [x] core/indexes/period.py
- [x] core/indexes/range.py
- [x] core/internals/block.py
- [x] core/internals/managers.py
- [x] core/reshape/reshape.py
- [x] core/strings/object_array.py
- [x] core/base.py
- [x] core/common.py
- [x] core/frame.py
- [x] core/generic.py
- [x] core/series.py

**Comment by avinashpancham** [comment]
Add typing for  io/parsers.py, io/excel/_base.py, io/json/_json.py and io/pytables.py in 38814

Add typing for  core/arrays/datetimelike.py, core/arrays/base.py, core/arrays/boolean.py, core/arrays/categorical.py and core/arrays/integer.py in 38826

**Comment by ssooffiiaannee** [comment]
I would like to work on a few files, would it be possible?

**Comment by avinashpancham** [comment]
Sure, go ahead! Would propose to take a number of files (max 5 or less) and start with them. Please first mention the files here such that other people will not work on those files.

**Comment by avinashpancham** [comment]
I will work on the remainder of files in core/arrays

**Comment by avinashpancham** [comment]
I will work on all the files in the directory `core/indexes`

**Comment by avinashpancham** [comment]
Good to hear! Once you've started, it would be great if you could reference this issue in the PR that will update core/frame.py

**Comment by tushushu** [comment]
Hi, I would like to work on `core/common.py`. It seems that no one is working on that yet.

**Comment by avinashpancham** [comment]
Thanks @tushushu, will mark that file as done

**Comment by avinashpancham** [comment]
Will work on the dir  `core/internals/*` and ` core/reshape/*` and the file `core/base.py`

**Comment by zbremmer** [comment]
Anyone working on ```
core/generic.py
```? I'll take that on if it's still open.

**Comment by avinashpancham** [comment]
Sorry @zbremmer, all the files that need to be modified according to this issue are already taken or finished. But please have a look at other issues, since there are still plenty of open issues!

**Comment by avinashpancham** [comment]
@rbpatt2019 any updates on `core/frame.py`, else I will work on it this weekend

**Comment by SouravPal1995** [comment]
take

**Comment by zitorelova** [comment]
I'd like to do updates for `core/frame.py` if no one else has done it yet.
