### ISSUE TITLE
BUG: pandas 1.2.0 and Pyarrow [0.16.0, 1.0.0) are incompatible for some column types

### ISSUE THREAD

**Issue by ADraginda** [pandas-dev/pandas#38801]
#35259 added optional importing from pyarrow. The currently listed minimum version of pyarrow is 0.15.1, and the logic of said PR guards against importing attributes from `pyarrow.compute` because it is not available in 0.15.1

Problem: pyarrow added the compute module in [0.16.0](https://github.com/apache/arrow/commit/27dded680e84f1a628de1bddff1f4eb62fbc5887#diff-3d08757408024228c4443730cc3536ab39c9436cd2e4cb63e5da34c69c18962f) but attributes imported by pandas are not available in that module until [1.0.0](https://github.com/apache/arrow/commit/dcd17bf36e0f7b18e8b8f466ed2cb3eb396955d8#diff-3d08757408024228c4443730cc3536ab39c9436cd2e4cb63e5da34c69c18962f)

Therefore: with pandas 1.2.0 and merging a DataFrame (with an Array String column?) :

| Pyarrow Version       | Behavior |
| -------------: | ----- |
| not installed              | works |
| < 0.15.1                     | not supported |
| [0.15.1, 0.16.0).         | works (pyarrow.compute.equal not used?) |
| [0.16.0, 1.0.0)           | ArgumentError |
| [1.0.0, 2.0.0 (latest)] | works (using pyarrow.compute.equal) |

Adding another try/except around the comparison functions in pandas [string_arrow.py](https://github.com/pandas-dev/pandas/blob/master/pandas/core/arrays/string_arrow.py#L39) will change the table of functionality to:

| Pyarrow Version       | Behavior |
| -------------: | ----- |
| not installed              | works |
| < 0.15.1                     | not supported |
| [0.15.1, 1.0.0).         | works (pyarrow.compute.equal not used?) |
| [1.0.0, 2.0.0 (latest)] | works (using pyarrow.compute.equal) |

**Comment by jreback** [comment]
see my comments on the PR. what causes this error exactly?

e.g. what is 
> Therefore: with pandas 1.2.0 and merging a DataFrame (with an Array String column?) :

**Comment by ADraginda** [comment]
@jreback I replied in the PR as well but here is a reproduction:


You can reproduce with pyarrow 0.17.1 (that's what I'm on, but breaks for other versions too) with the following example. Seems to be related to merging tow tables, one on a column of type `string` and the other of type `object`.

```python
import pandas as pd

example_dict = {'i': {0: 'foo'}, 'j': {0: 1}}

foo = pd.DataFrame(example_dict)
foo['i'] = foo['i'].astype(pd.StringDtype.name)
foo['j'] = foo['j'].astype(pd.Int64Dtype.name)

bar = pd.DataFrame(example_dict)
bar['j'] = bar['j'].astype(pd.Int64Dtype.name)

foo.merge(bar)
```
