### ISSUE TITLE
CI/STYLE extend codespell beyond pandas/core

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#38802]
There is task left here:

1. apply the following diff
```diff
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index d78c2bacc..bcb9202d4 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -173,4 +173,4 @@ repos:
     hooks:
     -   id: codespell
         types_or: [python, rst, markdown]
         files: ^(pandas|doc)/
-        exclude: ^pandas/tests/
```
, run `pre-commit run codespell --all-files`, and fixup the mistakes 

You _may_ need you to add new words to ignore in `setup.cfg`.

**Comment by chinggg** [comment]
Hi! I am new to opensource and I want to take task 4.Do I just need to fork the repo and make a PR?

**Comment by chinggg** [comment]
take

**Comment by MarcoGorelli** [comment]
hey @chinggg - yup, the contributing guide explains everything https://pandas.pydata.org/pandas-docs/dev/development/contributing.html

**Comment by zitorelova** [comment]
Hello, I would like to take on the 1st task.

**Comment by zitorelova** [comment]
take

**Comment by MarcoGorelli** [comment]
Have updated the tasks based on those which have already been done, in case any newcomers want to contribute

**Comment by bryanccho** [comment]
I will work on task 2

**Comment by bryanccho** [comment]
take

**Comment by 01-vyom** [comment]
I am working on task 2 and cleaned pretty much everything, but I had a couple of doubts:

1) `.sav` is caught in the codespell, and I don't know if I should include it in the ignore list. 
(https://github.com/pandas-dev/pandas/blob/master/doc/source/user_guide/io.rst#spss-formats)
2) There is an example with the `TIP.csv` which has `Thur` which is caught in codespell, but as it part of the example I don't if it should be changed, and adding `Thur` to ignore-word-list doesn't seem feasible to me.
(https://github.com/pandas-dev/pandas/blob/master/doc/source/getting_started/comparison/comparison_with_sql.rst)
<img width="271" alt="Screenshot 2021-03-06 at 5 39 09 PM" src="https://user-images.githubusercontent.com/46242526/110206321-ef541980-7ea2-11eb-8ca8-a5e89c1104b9.png">

**Comment by MarcoGorelli** [comment]
Hey @01-vyom 

For `sav`, I think we'll have to ignore it, I can't think of a way to avoid it.

For Thur, I'd say just change it to `Thu` in the examples

**Comment by 01-vyom** [comment]
Ok going ahead with this plan, will make a PR soon.

**Comment by 01-vyom** [comment]
Working on Task 1 and closing this issue.
