### ISSUE TITLE
STYLE: use option_context almost always

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#38813]
we *should* very rarely be setting / getting options (except to test that functionaily explicity), and instead use `pd.option_context`, e.g. this should be changed:

https://github.com/pandas-dev/pandas/pull/31569/files#diff-5974844fa02c9b81f3477198023bd02503bf82da1e3d15df6dfd62cdca48666bR242

pandas/tests/io/formats/test_format.py is a hotbed for incorrect usages like this.

it *may* be possible to add a pre-commit hook to check for this in all but a small handful of files.

**Comment by ssooffiiaannee** [comment]
I would like to work on this issue, would it be possible?

**Comment by 1nF0rmed** [comment]
> I would like to work on this issue, would it be possible?

You can use the `take` chat command to self-assign an issue

**Comment by ssooffiiaannee** [comment]
`take`

**Comment by ssooffiiaannee** [comment]
I'm sorry, I accidentally unassigned myself, could you assign me again?, I don't understand what you mean by the take chat command, I don't have the permission to assign myself an issue, do I?

**Comment by 1nF0rmed** [comment]
@ssooffiiaannee You can comment `take` it'll be assigned to you. I'm not a maintainer so I won't be able to assign you.

**Comment by n-mathis** [comment]
take

**Comment by Opher-Lubzens** [comment]
take

**Comment by debnathshoham** [comment]
take

**Comment by chrismoradi** [comment]
take
