### ISSUE TITLE
TST: dropping of nuisance columns for groupby ops

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#38815]
xref #38774 

As far as I can tell, for groupby we only have two tests for dropping nuisance columns and these only involve sum/mean. A more robust and parameterized test over all the groupby ops that drop nuisance columns should be added.

**Comment by horaceklai** [comment]
take

**Comment by horaceklai** [comment]
Is there a list of aggregation functions where nuisance columns are dropped?

I expected functions such as max, min, last, first to drop columns of object datatypes. But I was wrong.

So far I have mean, sum, std, var, sem
