### ISSUE TITLE
Improve error message in Series.any and Series.all, when bool_only is passed and not level

### ISSUE THREAD

**Issue by moink** [pandas-dev/pandas#38810]
When working on xref #30999 I came across TestSeriesReductions.test_all_any_params in pandas/tests/reductions/test_reductions.py

It showed that calling the following code:
```
s = Series([False, False, True, True, False, True], index=[0, 0, 1, 1, 2, 2])
s.any(bool_only=True)
```
would raise a `NotImplementedError` with the error message "Series.any does not implement numeric_only", and equivalent for calling `s.all` the same way. This error message is confusing because the user didn't pass `numeric_only`, they passed `bool_only`.

So the messages need to change to "Series.any does not implement bool_only" and  "Series.all does not implement bool_only".

> what actually needs to happen is we pass bool_only thru, but this increases the scope of this PR greatly.
-- @jreback #38720

**Comment by theodorju** [comment]
Hi, I'd like to work on this one since there is no one assigned.
Should only the string be changed, or the method's argument as well from `numeric_only` to `boolean_only`?

I'm referring to method `_reduce` on `series.py`.

**Comment by weikhor** [comment]
Pandas version I used:
```
1.5.0.dev0+725.g9f24918759
```
With this pandas version, the result is worked as expected. 

1)  
    ```
    s = Series([False, False, True, True, False, True], index=[0, 0, 1, 1, 2, 2])
    s.all(bool_only=True)
    ```
    ```
    NotImplementedError: Series.all does not implement bool_only.
    ```

2)
    ```
   s = Series([False, False, True, True, False, True], index=[0, 0, 1, 1, 2, 2])
   s.any(bool_only=True)
   ```
   ```
   NotImplementedError: Series.any does not implement bool_only.
   ```

**Comment by rhshadrach** [comment]
Thanks @weikhor; this is tested for in `test_all_any_params`. Closing.
