### ISSUE TITLE
TYP: add RandomState alias

### ISSUE THREAD

**Issue by erfannariman** [pandas-dev/pandas#38860]
This is a follow up of #38594. When adding type hints to the `sample` method, I ran into some problems for `random_state`. The reason is that `numpy < 1.17.0` does not have the `random.Generator` class implemented. I tried to solve this with checking the numpy version with:

```python
if np_version_under1p17:
    RandomState = Union[int, ArrayLike, np.random.RandomState]
else:
    RandomState = Union[int, ArrayLike, np.random.Generator, np.random.RandomState]
```
But this resulted in:

```commandline
Cannot assign multiple types to name "RandomState" without an explicit "Type[...]" annotation [misc]
```

To solve this issue we have to add typing for `random_state`.

**Comment by arw2019** [comment]
I'd change the title to `TYP: add RandomState alias` 

(AFAIK enhancements are new feature implementations)
