### ISSUE TITLE
DEPS: bump pyarrow min to 0.17.0

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#38870]
this would remove some complexity around parquet, csv engine & string array. this is an optional dep and so i don't think this a big deal.

keep in mind that we likley won't release 1.3 until june time frame anyhow

**Comment by jorisvandenbossche** [comment]
As I mentioned before, the default conda channel doesn't have pyarrow 1.0 yet. So I think that is a good reason to not yet require that version for pandas. 
In addition, pyarrow 1.0 is only just half a year old.

(so @alimcmaster1, I would personally wait a bit with working on this, at least until it has been discussed more)

**Comment by jorisvandenbossche** [comment]
As mentioned in https://github.com/pandas-dev/pandas/issues/41329, we could start by bumping to 0.17
