### ISSUE TITLE
QST: function similarity

### ISSUE THREAD

**Issue by ZhangLockerberg** [pandas-dev/pandas#38875]
Does Pandas also support a function like what np.vstack or np.hstack does?

**Comment by MarcoGorelli** [comment]
Hi @ZhangLockerberg - this kind of question would be more well-suited to [StackOverflow](https://stackoverflow.com/). Post a reproducible example with clearly defined input and expected output and you'll likely get a helpful response

**Comment by ZhangLockerberg** [comment]
> Hi @ZhangLockerberg - this kind of question would be more well-suited to [StackOverflow](https://stackoverflow.com/). Post a reproducible example with clearly defined input and expected output and you'll likely get a helpful response

Thanks.
