### ISSUE TITLE
CLN/TST:  Pyarrow CSV engine

### ISSUE THREAD

**Issue by arw2019** [pandas-dev/pandas#38889]
This is a master tracker for the more cosmetic follow-ups to #38370: styling, testing, etc.

- [ ] #38888 correctly check version for optional dependency submodule imports (to handle `import pyarrow.csv`)

**Comment by lithomas1** [comment]
Can't edit the OP, but wanted to add

- [ ] Convert all ``pyarrow_skip`` markers to ``pyarrow_xfail``. This was previously disabled due to timeouts.

**Comment by mroeschke** [comment]
I think we have a dedicated issue for https://github.com/pandas-dev/pandas/issues/38889#issuecomment-907670667 and our minimum version of pyarrow should guarantee pyarrow.csv to be available so closing
