### ISSUE TITLE
DEPR: Remove xlrd as being the default reader for xlsx

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#38884]
Currently the default reader for xlsx is openpyxl if installed, otherwise it is xlrd. While xlrd == 1.2.0 will work with xlsx files, xlrd >= 2.0 will not. In pandas 1.2, a FutureWarning is raised if xlrd is used on non-xls files. We should remove xlrd as being the default for xlsx files in pandas 2.0, but perhaps even 1.3 (if 1.3 != 2.0).

cc @jorisvandenbossche

**Comment by rhshadrach** [comment]
I'm thinking we should do this for 1.3, but want to make sure others don't think that's too soon before putting up a PR.

**Comment by jreback** [comment]
it's ok to do this for 1.3
xlrd broke things and no reason to go to great lengths to support
