### ISSUE TITLE
DOC: Update contributing.rst

### ISSUE THREAD

**Issue by BobinMathew** [pandas-dev/pandas#38938]
#### Location of the documentation

doc/source/development/contributing.rst

#### Documentation problem

Need additional information about the command that verifies the linting of code files.

#### Suggested fix for documentation

`pre-commit run --from-ref=upstream/master --to-ref=HEAD --all-files`

The command verifies the linting of code files, it looks for common mistake patterns
*NOTE: An additional paragraph is preferred for this*

**Comment by MarcoGorelli** [comment]
Thanks @BobinMathew 

Yes, it would be good to mention the command
```
pre-commit run --from-ref=upstream/master --to-ref=HEAD --all-files
```
somewhere there, doesn't need to me a large addition

**Comment by vangorade** [comment]
hi, can i work on this issue please?
