### ISSUE TITLE
TST/REF: splitting pandas/io/parsers.py into multiple files

### ISSUE THREAD

**Issue by arw2019** [pandas-dev/pandas#38930]
`pandas/io/parsers.py` is close to 4k LOC (3986 on 1.3 master). Would it be reasonable to split it into multiple files (located, say, in a `pandas/io/parsers` directory)?

AFAICT the file contains 4 logical pieces:
- `read_...` methods (~700 LOC)
-  `ParserBase` and related module-level methods ( ~1100 LOC)
- `CParser` and related module-level methods (~400LOC)
- `PythonParser`, its derived classes and related module-level methods (~1800 LOC)

Once #38370 goes in these would be joined by 
- `PyarrowParser` (~100 LOC right now)

IMO this kind of refactor would make the module somewhat easier to grok

**Comment by jreback** [comment]
sure seems reasonable
