### ISSUE TITLE
CI: Travis not running (no credits)

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#38943]
https://travis-ci.com/github/pandas-dev/pandas/requests

**Comment by jreback** [comment]
i know 
i have an email out to travis about this

**Comment by bashtage** [comment]
Could consider drone.io for ARM CI. It is not too burdensome, aside from the risk of CI-provider disruptions with a new CI.

**Comment by jreback** [comment]
sure - i think we need try something else - travis is completely unresponsive

**Comment by avinashpancham** [comment]
Read on HN that credit allocation for OSS project is on hold. Might be related

https://news.ycombinator.com/item?id=25338983

**Comment by lithomas1** [comment]
@jreback Can this be closed? Travis CI seems to be running again. e.g. https://travis-ci.com/github/pandas-dev/pandas/jobs/497435258

**Comment by jreback** [comment]
they gave us some credits so let's have a look

**Comment by lithomas1** [comment]
@jreback I think we ran out again. This is what I see on the dashboard. 
![image](https://user-images.githubusercontent.com/47963215/114904381-a7db7a00-9dcc-11eb-8704-e58b4d139df9.png)
