### ISSUE TITLE
ENH: Explode like feature for spliting column containing iterable values into multiple columns

### ISSUE THREAD

**Issue by minesh1291** [pandas-dev/pandas#38949]
#### Describe the solution you'd like

```py
from collections.abc import Iterable
import pandas as pd

def split_columns(df):
    iterable_cols = [c for c in df.columns if isinstance(df[c].iloc[0], Iterable)]
    for c in iterable_cols:
        n = len(df[c].iloc[0])
        if isinstance(df[c].iloc[0], dict):
            tmp_df = pd.DataFrame(df[c].tolist(), index=df.index)
            tmp_df.columns = c + "_" + tmp_df.columns
            df = pd.concat([df, tmp_df], 1)
        else:
            df[[f"{c}_{i}" for i in range(n)]] = pd.DataFrame(
                df[c].tolist(), index=df.index
            )
    return df.drop(iterable_cols, 1)
```
I think the code is not robust and optimized, but it will give an idea of the desired feature.
<table>
<tr>
<td>
Input: 
<img src="https://user-images.githubusercontent.com/6646693/103563159-45780100-4ee2-11eb-976b-fbeea5a3922f.png" height="200">
<td>Output:
<img src="https://user-images.githubusercontent.com/6646693/103563202-5cb6ee80-4ee2-11eb-9df9-4c75b80eeb8a.png" height="200">
<tr>
<td>
<img src="https://user-images.githubusercontent.com/6646693/103565357-3bf09800-4ee6-11eb-9f6b-22d7f5bd3e89.png" width=150>

<td>
<img src="https://user-images.githubusercontent.com/6646693/103565412-50349500-4ee6-11eb-8c4b-ad53e3fe89df.png" width=200>

**Comment by phofl** [comment]
Hi, thanks for your report. This can be done relatively easy

```
df = DataFrame({"a": [[1, 2], [3, 4], [5, 6]]})
DataFrame(df["a"].tolist())
df = DataFrame({"a": [{1: 2, 2: 5}, {1: 3, 2: 6}, {1: 4, 2:7}]})
DataFrame(df["a"].tolist())
```

**Comment by minesh1291** [comment]
> Hi, thanks for your report. This can be done relatively easy
> 
> ```
> df = DataFrame({"a": [[1, 2], [3, 4], [5, 6]]})
> DataFrame(df["a"].tolist())
> df = DataFrame({"a": [{1: 2, 2: 5}, {1: 3, 2: 6}, {1: 4, 2:7}]})
> DataFrame(df["a"].tolist())
> ```
@phofl 
It's one of the cases. I am looking forward to have pandas way (inbuilt) functionality like `explode_horizontal` . Where we can simply give name of the columns as argument, etc. I don't want to deal with bits and pieces. If I individually do it won't be robust and computationally optimized. I need it for large scale dataset.

**Comment by jreback** [comment]
you can use .str.split(expand=True) or generally .explode

-1 on adding any additional api

**Comment by minesh1291** [comment]
> you can use .str.split(expand=True) or generally .explode
> 
> -1 on adding any additional api

@jreback 
I did't understand that how can I use ".str.split(expand=True) or .explode" in this situation.
Instead of adding additional api, .explode api can be enhanced with accepting additional boolean argument to direct the functionality to explode vertically vs horizontally.  Thanks for your input.

**Comment by mroeschke** [comment]
Thanks for the suggestion, but agreed that since this functionality can be composed relatively succinctly with existing APIs, it is probably not worthwhile to add an additional method for this.

Since there is also lack of enthusiasm from other core devs going to close.
