### ISSUE TITLE
DOC: MultiIndex.is_lexsorted not linked

### ISSUE THREAD

**Issue by kylekeppler** [pandas-dev/pandas#38953]
#### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.MultiIndex.html?highlight=is_lexsorted

#### Documentation problem

On the API page for `MultiIndex`, `is_lexsorted` does not link to an API page for that method. That method has been deprecated and does not contain a docstring, perhaps that is why there is no link?

#### Suggested fix for documentation

Since this method is deprecated, suggest removing `is_lexsorted` from the list of methods on the `MultiIndex` API page. Alternatively could add a docstring and API page.

What is preferred?

**Comment by jreback** [comment]
we *just* merged a PR which deprecated is_lexsorted, which removed it from the api docs. https://github.com/pandas-dev/pandas/pull/38701

**Comment by kylekeppler** [comment]
Good timing then! Looks like the `is_lexsorted` entry in the `MultiIndex` docstring should be removed?

**Comment by jreback** [comment]
it is in the PR 
you have to look at the dev docs build

**Comment by jreback** [comment]
ahh I know we need to remove that reference (that you pointed above). if you would do a PR would be great!

**Comment by kylekeppler** [comment]
Will do tomorrow.

**Comment by kylekeppler** [comment]
Closed by #38975
