### ISSUE TITLE
DOC: Scatter and Hexbin from Series plot documentation

### ISSUE THREAD

**Issue by lucas-hattori-costa** [pandas-dev/pandas#38976]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.plot.html

#### Documentation problem

As the scatter and hexbin kinds are not supported for Series, it shouldn't appear in the docs for Series, just for DataFrames.

#### Suggested fix for documentation

Simply removing them.

**Comment by mzeitlin11** [comment]
Thanks for catching this @lucas-hattori-costa! A PR to fix is welcome!

**Comment by 1nF0rmed** [comment]
take

**Comment by 1nF0rmed** [comment]
Would I only have to update the doc string here:
https://github.com/pandas-dev/pandas/blob/v1.2.0/pandas/plotting/_core.py#L603-L1708

**Comment by venaturum** [comment]
https://github.com/1nF0rmed/pandas/commit/5bc961f47d0e16be0d87fceeb961afd5e0534e9e#commitcomment-45696570
