### ISSUE TITLE
BUG: IntegerDtype.__eq__(np.dtype(object)) returns True

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#38983]
Also looks like `IntegerArray.astype(other_nullable_integer_dtype)` is returning an ndarray

**Comment by jorisvandenbossche** [comment]
> Also looks like IntegerArray.astype(other_nullable_integer_dtype) is returning an ndarray

I don't think that's the case (you actually recently refactored that to have all astype(extension_dtype) be handled by the base MaskedArray class):

```
> In [39]: pd.array([1, 2, 3]).astype("Int8")
Out[39]: 
<IntegerArray>
[1, 2, 3]
Length: 3, dtype: Int8
```

I also don't see the issue from the title? Do you have a code example?

```
In [41]: pd.Int64Dtype() == np.dtype(object)
Out[41]: False
```

**Comment by jbrockmendel** [comment]
Looks like I was using the dtype classes instead of instances, thanks

**Comment by jorisvandenbossche** [comment]
Ah, yes, that seems to be the case for any class object ...

```
In [45]: class A:
    ...:     pass
    ...: 

In [46]: A == np.dtype(object)
Out[46]: True
```
