### ISSUE TITLE
DOC: add comparison to spreadsheets

### ISSUE THREAD

**Issue by afeld** [pandas-dev/pandas#38990]
#### Location of the documentation

https://pandas.pydata.org/docs/dev/getting_started/comparison/comparison_with_spreadsheets.html

#### Documentation problem

From https://github.com/pandas-dev/pandas/pull/38554:

> I teach [a class on pandas for public policy students](https://github.com/afeld/python-public-policy/blob/master/syllabus.md#readme), and for many of them, spreadsheets are the only point of reference they have for working with tabular data.

There are [a number of unofficial resources](https://www.google.com/search?q=excel+vs+pandas), but no official, living documentation to point them to.

#### Suggested fix for documentation

The idea is to add a "Comparison to spreadsheets" page alongside [the other comparison pages](https://pandas.pydata.org/pandas-docs/stable/getting_started/comparison/index.html). That new page already got merged in https://github.com/pandas-dev/pandas/pull/38554; creating this issue to keep a running checklist of the TODOs.

- [x] start with what @rotuna did in https://github.com/pandas-dev/pandas/pull/23042
- [x] link from Getting Started pages
- [ ] incorporate structure from [SAS](https://pandas.pydata.org/pandas-docs/stable/getting_started/comparison/comparison_with_sas.html)/[STATA](https://pandas.pydata.org/pandas-docs/stable/getting_started/comparison/comparison_with_stata.html) comparison pages
   - [x] Data structures
   - [x] Data input / output
      - [x] Mention `read_excel()`
   - [x] Data operations
   - [x] String processing
   - [x] Merging
   - [ ] Missing data
   - [ ] GroupBy
   - [x] Other considerations
- [ ] standardize datasets used for examples, for greater consistency and reduced cognitive burden on the readers
   - [`tips`](https://raw.github.com/pandas-dev/pandas/master/pandas/tests/io/data/csv/tips.csv) probably works for most
- [ ] add info about charting
- [x] [add example showing round trip to/from Excel](https://github.com/pandas-dev/pandas/pull/38554#discussion_r549409566)
- [ ] [have pivot table examples match](https://github.com/pandas-dev/pandas/pull/38554#issuecomment-752767183)
- [ ] add [quick reference](https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_r.html#quick-reference)

**Comment by bsun94** [comment]
Hi there, I was wondering if you needed any help with this ticket? I'm new to open source, and am looking to get my feet in the water :)

**Comment by afeld** [comment]
Sure! [Adding an example showing the round trip to/from Excel](https://github.com/pandas-dev/pandas/pull/38554#discussion_r549409566) would be a great first contribution. I started writing out how to go about doing so, and [it accidentally turned into a blog post](https://aidanfeldman.medium.com/1a68692c4d47?source=friends_link&sk=a8dbcae9e46155cf75d6bd9b10b9dfc8) 😆 Since you're my audience of one, let me know if it answers your questions!

I just joined [the Gitter chat room](https://gitter.im/pydata/pandas) — feel free to reach out there if you'd like to talk through details 👋

**Comment by pilyavetsb** [comment]
Hello! Just wanted to point out that I've noticed a small mistake on that page. In the very beginning, when describing what dataframe is, you write:

> While an Excel **worksheet** can contain multiple worksheets, pandas DataFrames exist independently.

I think that you meant "workbook" instead of a bolded worksheet. Since it is a minor issue I figured creating a new pull request would be an overkill, hence writing about it here. However, I am very new to all of this, so, please let me know, if I am approaching it incorrectly)

**Comment by jreback** [comment]
@pilyavetsb a PR to fix would be great

**Comment by bsun94** [comment]
Thanks Aidan, apologies I've been offline for a couple of days - had a couple days of overtime at work. Would you mind adding me as an assignee on this ticket? Would help me better keep track of it :)

**Comment by bsun94** [comment]
Thank you for your suggestion before, Aidan, I've managed to locate and make edits to the Comparison to Excel .rst and made PR #39241 above. Essentially I just swapped the order of the "Excel" and "CSV" paragraphs in the data importing section, so that the examples given for to_excel and read_excel (as suggested by @jreback) would flow from the CSV example without needing repeated code/codeblocks.

**Comment by bsun94** [comment]
Thank you for your suggestion before, Aidan, I've managed to locate and make edits to the Comparison to Excel .rst and made PR #39242 above, following the suggestion by @jreback in ticket #38554. Please ignore the #39241 above.

**Comment by bsun94** [comment]
Would just like to bump the thread @afeld @jreback :) I was wondering if you guys wouldn't mind taking a look at my PR when you have a sec - please let me know if everything looks OK!

**Comment by Bhard27** [comment]
Hey Everyone! I am a participant at HackIllinois 2021 Open Source Fellowship program. This seems like a good issue for me to start contributing to the pandas docs. I would like to take this one up.

**Comment by dan-r95** [comment]
Can i have a look at this? :)

**Comment by ilaiyengar** [comment]
Hi! I am a first time contributor and would love to help. Is there anything that I could possibly be assigned to or help out with?

**Comment by keerthinannepamula7** [comment]
@afeld Hello..I'm a first contributor. are there any areas in the documentation I can be part of?

**Comment by Mikil03** [comment]
Hello, I am new to open source and would like to contribute. Would like to work on missing data if possible.

**Comment by imsoumya18** [comment]
Hi @afeld , I am new to open source. Want to get my feet wet. Can you please assign this to me? I shall be happy if this can be my first open source contribution.

**Comment by imsoumya18** [comment]
take

**Comment by Johin2** [comment]
Hey there!! I am new to open-source contribution and would like to get started with contributions. I would like to work on this issue.

**Comment by afeld** [comment]
Hey everyone- Given this page has been up for a while, this issue probably should have been closed to avoid confusion.

https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_spreadsheets.html

If you see anything there that could use improvement, including unchecked items above, here are the instructions for contributing to documentation: 

https://pandas.pydata.org/pandas-docs/stable/development/contributing_documentation.html

Just tag me - I'm happy to review. Thanks!
