### ISSUE TITLE
ENH: enhance query syntax

### ISSUE THREAD

**Issue by DylanDmitri** [pandas-dev/pandas#39011]
#### Is your feature request related to a problem?

No, it's additional behavior.

#### Describe the solution you'd like

```df.query(key=value)```

Add new query behavior for simple key lookup. Helps improve readability.

#### API breaking implications

Will not break API. Make the query expression optional, new calls hit this feature if and only if the query expression is not provided.

#### Describe alternatives you've considered

Just not adding this. It's sugar and adds some complexity.

#### Additional context

Single value lookups can be:

```
info = df[df['zipcode'] == adress.zip]
``` 

Or if you want to use the query API:

```
info = df.query(f'zipcode == {address.zip}')
```

I've found myself writing (on accident)

```
info = df.query(zipcode=adress.zip)
```

The third approach is cleanest and easiest to read. The first approach (via bitmask) is fastest. We can just short-circuit the new special case to use a bitmask, rather than going through the "query" machinery each time.

**Comment by jreback** [comment]
-1 on adding *anything* to `.query`; in particular this is *already* available thru standard pythonic apis, this is additional cause for guess 'what does this do'? or 'why do we have multiple ways to do things'?

**Comment by mroeschke** [comment]
Thanks for the suggestion, but agreed that having more than one method of performing the same action (and having to maintain those methods in sync) is not ideal. Since there hasn't been much support for this functionality from the other core devs, closing but happy to reopen if there is revived interest from the team.
