### ISSUE TITLE
DOCUMENTATION BUG: DOC FOR `pandas.Index.resize` TALKS ABOUT `numpy`

### ISSUE THREAD

**Issue by Samuel-Muldoon** [pandas-dev/pandas#39048]
I was reading the [documentation](https://pandas.pydata.org/pandas-docs/version/0.14/generated/pandas.Index.resize.html) for `pandas.Index.resize`   

The doc for `pandas.index.resize` talks about `numpy`

All of the examples use the `numpy` library.   

`pandas` and `numpy` are not the same library.  

shouldn't the examples looks more like `pandas`?

**Comment by jreback** [comment]
this method doesn't exist in Index any longer 
would take a PR to remove the doc entry

**Comment by jreback** [comment]
actually you've pointed to a really old version of pandas docs 

unless this persists on 1.2 pls close

**Comment by phofl** [comment]
This does not exist in the 1.2 docs, so closing.
