### ISSUE TITLE
QST: How to print specific element from dataframe?

### ISSUE THREAD

**Issue by debasisc-opa** [pandas-dev/pandas#39055]
- [ ] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
# Your code here, if applicable

https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html

```
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
print("Print the dataframe which is like a matrix")
print(df)
```

This works. But how do I print specific element of the dataframe? What is the syntax?

print(df[0:1] prints one row

print(df[0:2] prints two rows.

How do I print exact element (ex: row1, value of column A)?
Also length of a dataframe. Here, we know length=6 because we have created.

```

**Comment by jreback** [comment]
pls read the guide on. indexing https://pandas.pydata.org/docs/user_guide/indexing.html and the getting started tutorials

hint use .iloc

**Comment by debasisc-opa** [comment]
@jreback - Thank you very much indeed. Very useful link. Also "iloc" does the trick.
