### ISSUE TITLE
CI: Numpy changed dtype inference

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#39089]
Numpy changed the dtype inference (https://github.com/numpy/numpy/pull/17863), which causes tests to fail. Problem description as follows:

```
other = [pd.Interval(0, 1, closed="right"), 0, "foo"]
arr = np.asarray(other)
result = pd.array(arr)
```

On a regular Numpy version the numpy array has dtype object and this returns
```
<PandasArray>
[Interval(0, 1, closed='right'), 0, 'foo']
Length: 3, dtype: object
```

while on numpy dev the numpy array has dtype ``<U64`` and this returns 
```
<StringArray>
['(0, 1]', '0', 'foo']
Length: 3, dtype: string
```
This leads to a different evaluation of ``is_object_dtype(other_dtype)``

**Comment by jbrockmendel** [comment]
is it just me or does this look like really weird behavior on numpy's part?

**Comment by jreback** [comment]
yea this should be reverted by numpy it is a huge breaking change

**Comment by phofl** [comment]
Seems like a bug.
```
arr1 = np.asarray([0, "foo", pd.Interval(0, 1, closed="right")])
print(arr1.dtype)
arr = np.asarray([pd.Interval(0, 1, closed="right"), 0, "foo"])
print(arr.dtype)
```

returns 
```
object
<U64
```

**Comment by jbrockmendel** [comment]
cc @seberg

**Comment by seberg** [comment]
Thanks, the problematic PR is gh-18115, I managed to write `&&` instead of `||` (at least I guess).  The more annoying thing is that the NumPy tests apparently only test the first case of your examples @jbrockmendel ...

**Comment by jreback** [comment]
thanks @seberg

**Comment by jreback** [comment]
@seberg so this is fixed in numpy master?

**Comment by seberg** [comment]
Yes, was a simple bug and should be fixed (and I guess by now the new, corrected, weekly build is up.
