### ISSUE TITLE
Pandas strftime function prints unix epoch time in local TZ instead of UTC

### ISSUE THREAD

**Issue by blwells** [pandas-dev/pandas#39119]
I'm trying to convert a given date and time to unix epoch time using Pandas. This is normally a very straightforward thing to do, merely converting the string of date and time to a datetime object, and then printing the object as a unix epoch timestamp using strftime, for example:

`pd.to_datetime('2021-01-01 00:00:00').strftime('%s')`

Running the above example on a remote linux machine I have set up, whose system date is recorded in UTC, gets me the expected output of "1609459200" which is 2020-01-01 00:00:00 in unix epoch time. However, when pulling my code onto my Mac laptop and running locally has resulted in what was unexpected to me at first: that the above code prints off a unix epoch time 7 hours in advance, or a string reading "1609484400". 

Running the date command on my Mac OS terminal gives me the time in MST, which is where I live, instead of UTC like the remote linux machine I pulled my code from. MST is 7 hours behind UTC so I assume that Pandas is trying to account for the MST time recorded on my laptop and doing some kind of internal conversion. I figure that I need to specify that the time I'm inputing is UTC, so I tried that both with "utc=True" for `pd.to_datetime()` as well as "tz='UTC'" for `pd.Timestamp()`. No dice though, as I still get a return value of "1609484400". 

Output when running with pd.to_datetime():
> dt = pd.to_datetime('2021-01-01 00:00:00', utc=True)
> dt
> ->Timestamp('2021-01-01 00:00:00+0000', tz='UTC')
> 
> dt.strftime('%Y-%m-%d %H:%M:%S')
> -> '2021-01-01 00:00:00'  # Converting back to the original format gives me the original string
> 
> dt.strftime('%B %d, %Y, %r')
> -> 'January 01, 2021, 12:00:00 AM'  # Expected output
> 
> dt.strftime('%s')
> -> '1609484400'  # This is '2021-01-01 07:00:00+00:00' in unix epoch time (7 hours ahead)
> 
> dt.tz_convert('MST').strftime('%s')
> -> '1609484400'  # Converting the timezone to MST before strftime strangely produces the same result

The exact same outputs occurred using `pd.Timestamp()` with the timezone set to either UTC or MST. Again, the expected output for `dt.strfime('%s')` should be "1609484400" in UTC, and I'm confused why I can't produce this value on my local machine. I know I could try to futz around with my Mac's system date, or hardcode a solution into my script by subtracting 7 hours from the dt object, but I don't want to change my Mac's system date, nor do I want to hardcode a solution into the script residing on my local machine. Am I doing something wrong or fundamentally misunderstanding something here, or is this a bug for the epoch time printoff for strftime? 

I am using:
Pandas version 1.2.0
Mac OS version 10.13.6

Thanks in advance for your help!

**Comment by mroeschke** [comment]
I suspect that this is an OS system implementation difference (https://stackoverflow.com/questions/62445620/python-list-date-supported-format-codes-for-your-platform).

`pd.Timestamp.strftime` just dispatches to `datetime.datetime.strftime` https://github.com/pandas-dev/pandas/blob/a6bc6ecc97d6d5520c609f4a8cbf3d51d2c0746d/pandas/_libs/tslibs/timestamps.pyx#L948

```
In [6]: import pandas as pd

In [7]: pd.__version__
Out[7]: '1.3.0.dev0+432.ga6bc6ecc9'

In [8]: import datetime

# On just OSX
In [9]: datetime.datetime(2021, 1, 1).strftime('%s')
Out[9]: '1609488000'

In [10]: pd.to_datetime('2021-01-01 00:00:00').strftime('%s')
Out[10]: '1609488000'
```

So I'm fairly sure that there is consistency on the pandas side, so I'm going to close this issue for now. If you are able to pin the issue specific to strftime on the pandas side happy to reopen.
