### ISSUE TITLE
BUG: `get_dummies` works on a single integer value column, but fails silently when applied to multiple columns. 

### ISSUE THREAD

**Issue by wcneill** [pandas-dev/pandas#39110]
- [x] I could not find this issue under open issues when searching: "bug get_dummies"

- [X] I have confirmed this bug exists on the latest version of pandas (1.2.0)

---

#### Code Sample, a copy-pastable example

```python
# A sample dataframe. Last column has integer values.
df = pd.DataFrame({'A': ['a', 'b', 'c'], 'B': ['1', '2', '3'], 'C': [1, 2, 3]})

# Encoding the integer values fine. 
df2 = pd.get_dummies(df['C'], prefix='C')

# Encoding the string values works fine.:
df3 = pd.get_dummies(df[['A', 'B']], prefix=['a', 'b'])

# Encoding both this fails silently:
df4 = pd.get_dummies(df)

# Supplying prefixes makes the issue apparent:
df5 = pd.get_dummies(df, prefix=['A', 'B', 'C'])
```

#### Problem description
Pandas `get_dummies` will one-hot encode a single integer valued categorical column. **However, it silently ignores any further columns containing numeric categories.** 

The last line of the minimal working example (with prefix list argument) results in:
```
ValueError: Length of 'prefix' (3) did not match the length of the columns being encoded (2).
```

#### Why the current behavior a problem and why the expected output is a better solution:
The expected output matches what the documentation advertises. 

#### Expected Output
All columns passed to `get_dummies` should be considered categorical and encoded, including those containing integers.

**or**

No integer columns should be allowed. Produce a warning/error/update the docs. 

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 3e89b4c4b1580aa890023fc550774e63d499da25
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.2.0
numpy            : 1.19.2
pytz             : 2020.5
dateutil         : 2.8.1
pip              : 20.3.3
setuptools       : 51.1.2.post20210110
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.15.1
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by toobaz** [comment]
> All columns passed to `get_dummies` should be considered categorical and encoded, including those containing integers.

This not what the docs promise:

```
    columns : list-like, default None
        Column names in the DataFrame to be encoded.
        If `columns` is None then all the columns with
        `object` or `category` dtype will be converted.
```

Indeed, conversion does not happen _at all_ (as long as ``columns=None``) for integer columns in a ``DataFrame``:
```python3
In [2]: df = pd.DataFrame({'A': ['a', 'b', 'c'], 'B': ['1', '2', '3'], 'C': [1, 2, 3]})

In [3]: pd.get_dummies(df[['C']])
Out[3]: 
   C
0  1
1  2
2  3
```

(although it is unexpected that this column passes through... and I think _that's_ a bug).

When you do


> ```python
> # Encoding the integer values fine. 
> df2 = pd.get_dummies(df['C'], prefix='C')
> ```

you are passing a ``Series`` (not a 1-column ``DataFrame``), and hence everything is different.

By the way, you can get what you probably want with:
```python3
In [4]: pd.get_dummies(df, columns=df.columns)
Out[4]: 
   A_a  A_b  A_c  B_1  B_2  B_3  C_1  C_2  C_3
0    1    0    0    1    0    0    1    0    0
1    0    1    0    0    1    0    0    1    0
2    0    0    1    0    0    1    0    0    1
```

**Comment by wcneill** [comment]
> This not what the docs promise:
> 
> ```
>     columns : list-like, default None
>         Column names in the DataFrame to be encoded.
>         If `columns` is None then all the columns with
>         `object` or `category` dtype will be converted.
> ```

I see. I think that many (I won't presume to say most, but maybe?) users would read this:

```
data : array-like, Series, or DataFrame
Data of which to get dummy indicators.
```

and expect that they are getting dummy variables from everything they passed. Perhaps the solution is to move the phrase

```
>         If `columns` is None then all the columns with
>         `object` or `category` dtype will be converted.
```

into the description of the `data` argument. That way it's a bit more up front.

**Comment by simonjayhawkins** [comment]
I'll close this issue and open a new issue for the bug discovered in https://github.com/pandas-dev/pandas/issues/39110#issuecomment-758726915

**Comment by simonjayhawkins** [comment]
> (although it is unexpected that this column passes through... and I think _that's_ a bug).

the output of `df4 = pd.get_dummies(df)` is 

```
   C  A_a  A_b  A_c  B_1  B_2  B_3
0  1    1    0    0    1    0    0
1  2    0    1    0    0    1    0
2  3    0    0    1    0    0    1
```

I assume including column C is the result is also a bug.
