### ISSUE TITLE
January 2021 Developer Meeting

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#39125]
The monthly dev meeting is Wednesday January 13th, at 18:00 UTC (12 am Central). Our calendar is at https://pandas.pydata.org/docs/development/meeting.html#calendar to check your local time.

Video Call:  https://zoom.us/j/942410248?pwd=T2l2Qi9vaC82Z294ZEtFczYxMVM2dz09
Minutes: https://docs.google.com/document/u/1/d/1tGbTiYORHiSPgVMXawiweGJlBw5dOkVJLY-licoBmBU/edit?ouid=102771015311436394588&usp=docs_home&ths=true

Please add items you'd like to see discussed to the agenda. All are welcome to attend.

@pandas-dev/pandas-core @pandas-dev/pandas-triage

**Comment by Dr-Irv** [comment]
@jorisvandenbossche Since we'll have special guests (including the inventor of Python....) with respect to the type stubs issue, can we move that item to first in the agenda?

**Comment by jorisvandenbossche** [comment]
Certainly!
