### ISSUE TITLE
BUG: Cells containing "NA" (string) in excel is imported as NaN

### ISSUE THREAD

**Issue by michamich** [pandas-dev/pandas#39148]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd

test_dict = {
    "TestInput": ["NA", "na", "N.A."],
    "TestCol2": [1234, "1234", ""]
}

test_df = pd.DataFrame(test_dict)
print(test_df)

file_path = "./test-input.xlsx"
test_df.to_excel(file_path, index=False)
input_df = pd.read_excel(file_path, dtype="object")
print(input_df)
```

#### Problem description
The string "NA" is imported as NaN instead of a string.

During DataFrame creation, the top-left cell contains the string "NA". However, when the same DataFrame was imported from excel, it is imported as NaN, as if the cell was blank.

Screenshot of output from jupyter below:
<img width="526" alt="Screenshot 2021-01-13 at 11 36 59 PM" src="https://user-images.githubusercontent.com/35208548/104473723-40106a00-55f8-11eb-8b1e-958ae39a675d.png">

#### Expected Output

The imported DataFrame should be identical to the DataFrame that was initially created with "NA" imported a string and not NaN.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 3e89b4c4b1580aa890023fc550774e63d499da25
python           : 3.8.5.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.2.0
Version          : Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.2.0
numpy            : 1.19.2
pytz             : 2020.5
dateutil         : 2.8.1
pip              : 20.3.3
setuptools       : 51.1.2.post20210112
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by phofl** [comment]
Hi, thanks for your report. You have to overwrite the ``na_values`` argument, see https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html

**Comment by phofl** [comment]
``pd.read_excel(file_path, dtype="object", keep_default_na=False)`` does what you want

**Comment by phofl** [comment]
Closing since there is no bug
