### ISSUE TITLE
QST: Why is `storage_options` parameter missed in `read_table` method?

### ISSUE THREAD

**Issue by YarShev** [pandas-dev/pandas#39167]
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
# Your code here, if applicable

```

**Comment by alimcmaster1** [comment]
Think this was likely just missed as part of https://github.com/pandas-dev/pandas/pull/35381 - can take a look

**Comment by YarShev** [comment]
@alimcmaster1 , thanks! It would be great.

**Comment by YarShev** [comment]
@alimcmaster1 , when are you planning to add this parameter to the function?
