### ISSUE TITLE
CI: docs build failing?

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#39176]
several recent PRs are showing a web / docs build failure: https://github.com/pandas-dev/pandas/pull/39136/checks?check_run_id=1704155153

though not sure we are actually seeing this on master.

cc @pandas-dev/pandas-core

**Comment by phofl** [comment]
The first failed build on master had two version changes:

nbformat  5.0.8 -> 5.1.0
gstreamer 1.18.2 -> 1.18.3

Probably nbformat broke something with the ipython notebooks?
We are getting a lot of warnings starting in line 2400 here
https://github.com/pandas-dev/pandas/runs/1704034071#step:6:2393

**Comment by jorisvandenbossche** [comment]
Yes, the current last commit on master also has the failure: https://github.com/pandas-dev/pandas/runs/1704622280

There are many warnings like

```
 /home/runner/work/pandas/pandas/doc/source/user_guide/style.ipynb:7: WARNING: Unexpected indentation.
/home/runner/work/pandas/pandas/doc/source/user_guide/style.ipynb:19: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/runner/work/pandas/pandas/doc/source/user_guide/style.ipynb:20: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/runner/work/pandas/pandas/doc/source/user_guide/style.ipynb:22: WARNING: Unexpected indentation.
/home/runner/work/pandas/pandas/doc/source/user_guide/style.ipynb:25: WARNING: Unexpected indentation.
/home/runner/work/pandas/pandas/doc/source/user_guide/style.ipynb:42: WARNING: Block quote ends without a blank line; unexpected unindent.
```

**Comment by jreback** [comment]
ok let's just fix those deps for now. if someone can do a PR :->
