### ISSUE TITLE
January 2021 Docs Meeting

### ISSUE THREAD

**Issue by afeld** [pandas-dev/pandas#39183]
- [Thursday, January 21st at 9am EST - 14:00 UTC](https://everytimezone.com/?t=6008c400,348)
- [Zoom link](https://nyu.zoom.us/j/97315680910?pwd=NEJ3ZityVUM3VkltOGdVS01JbzZOQT09)
- [Notes](https://docs.google.com/document/d/1JoiqTdK6gi5W1QiTWrqtTV-rNmIqU3xROgHY5iT4J5g/edit#)

---

It was mentioned at the Developer Meeting (https://github.com/pandas-dev/pandas/issues/39125) that there would be interest in having a meeting specifically focused on documentation. I hope the core team doesn't mind me pushing ahead on that 😄 

Please [**provide your availability**](https://doodle.com/poll/m46rp3ngx8f7sd62?utm_source=poll&utm_medium=link) in the next few days so we can find a time that works for the most people. Will comment with the date and Zoom link once finalized. All are welcome.

[Agenda/notes doc](https://docs.google.com/document/d/1JoiqTdK6gi5W1QiTWrqtTV-rNmIqU3xROgHY5iT4J5g/edit#) — feel free to add things in advance. Thanks!

@pandas-dev/pandas-core @pandas-dev/pandas-triage @pandas-dev/pydata-sphinx-theme @bollwyvl

**Comment by jorisvandenbossche** [comment]
@afeld thanks a lot for getting this started! 
I am very interested in having more focused doc meeting(s) and helping out with this.

One note about the doodle: since the pandas contributors are spread across timezones, it's probably best to try to include hours that can work for several timezones. I know it's impossible to have something that works for everybody (and eg the time of our dev meeting last Wednesday also excludes people from large part of Asia, or Australia, etc ...), so it's also something that can be discussed later with the people that are interested. 
But so, that's the reason you see that Simon and I only filled the slots for one specific time of the day (since the others are around midnight in Europe ;))

**Comment by afeld** [comment]
> It's probably best to try to include hours that can work for several timezones.

Added some more options in there. @jorisvandenbossche @simonjayhawkins Mind editing your responses (you should have gotten an email, I think?) or submitting new ones?

**Comment by afeld** [comment]
Ok, scheduled for [**Thursday, January 21st at 9am EST**](https://everytimezone.com/?t=6008c400,348). [Zoom meeting.](https://nyu.zoom.us/j/97315680910?pwd=NEJ3ZityVUM3VkltOGdVS01JbzZOQT09) Would someone mind adding to [the calendar](https://pandas.pydata.org/docs/development/meeting.html)?

**Comment by bollwyvl** [comment]
Just saw this... I'll try to make that time! Is there an agenda someplace?

While I'm sure the goal is not just triage, I'd selfishly toss out:

- accessibility roadmap
https://github.com/pandas-dev/pydata-sphinx-theme/pull/294

- theme toggles (night/day, hi-viz)
https://github.com/pandas-dev/pydata-sphinx-theme/pull/273

**Comment by jorisvandenbossche** [comment]
@afeld I added it to the calender at https://pandas.pydata.org/docs/development/meeting.html Can you check the time to be sure I picked the correct one?

**Comment by afeld** [comment]
@bollwyvl Added to [the list of potential topics](https://docs.google.com/document/d/1JoiqTdK6gi5W1QiTWrqtTV-rNmIqU3xROgHY5iT4J5g/edit#heading=h.c3mxsnpagwrm).

@jorisvandenbossche See [the time conversion](https://everytimezone.com/?t=6008c400,348) — it's an hour later than what I'm seeing on the calendar.

**Comment by jorisvandenbossche** [comment]
@afeld Sorry, missed this. But that's strange, for me the link you provide and the calendar both show "15:00" for my local time. 

So in UTC (which should be unambigous), it is UTC 14:00, is that correct?

UTC 14:00 then corresponds to 9:00 EST (UTC-5) and 15:00 in Europe (UTC+1). What time do you see in the calendar?

**Comment by afeld** [comment]
Oh, weird, the embedded calendar is set to the wrong time zone for me — times look fine when I open in an incognito window. All good, sorry for the confusion!

**Comment by afeld** [comment]
February edition: https://github.com/pandas-dev/pandas/issues/39833
