### ISSUE TITLE
Dataframe: Get n rows before and after condition met 

### ISSUE THREAD

**Issue by helloworldnoob** [pandas-dev/pandas#39222]
I am working with a time series dataframe, and I would like to know how to get a number of rows before, and after the condition is met. 

I have a datetime index but also trying a numbered index for ease of use, however, i am not sure how to do either...

The output I want is as follows:
7 rows(or days/hours/minutes) before, then the condition row, and 7 rows(or days,etc...) after.

Any help is massively appreciated! Thank you.

**Comment by MarcoGorelli** [comment]
Hi @helloworldnoob 

It's not clear to me what you're asking, but this seems like the kind of question you should ask on StackOverflow

Closing for now then, but please do let us know if you believe there is a bug in pandas
