### ISSUE TITLE
BUG: read_excel fails with IndexError: list index out of range

### ISSUE THREAD

**Issue by YarShev** [pandas-dev/pandas#39250]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
import pandas
df = pandas.read_excel("excel_sheetname_title.xlsx")
IndexError: list index out of range
```
<details>

pandas           : 1.2.0
numpy            : 1.19.2
pytz             : 2020.5
dateutil         : 2.8.1
pip              : 20.3.3
setuptools       : 51.1.2.post20210112
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.6
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
numba            : None

</details>

The file which read_excel fails on.
[excel_sheetname_title.xlsx](https://github.com/pandas-dev/pandas/files/5830079/excel_sheetname_title.xlsx)

**Comment by asishm** [comment]
full traceback please.

I can't open this file with Excel (It tries to recover then fails)

**Comment by YarShev** [comment]
>>> df = pandas.read_excel("excel_sheetname_title.xlsx")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "miniconda3\envs\pandas\lib\site-packages\pandas\util\_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "miniconda3\envs\pandas\lib\site-packages\pandas\io\excel\_base.py", line 344, in read_excel
    data = io.parse(
  File "miniconda3\envs\pandas\lib\site-packages\pandas\io\excel\_base.py", line 1153, in parse
    return self._reader.parse(
  File "miniconda3\envs\pandas\lib\site-packages\pandas\io\excel\_base.py", line 479, in parse
    sheet = self.get_sheet_by_index(asheetname)
  File "miniconda3\envs\pandas\lib\site-packages\pandas\io\excel\_openpyxl.py", line 498, in get_sheet_by_index
    return self.book.worksheets[index]
IndexError: list index out of range

**Comment by YarShev** [comment]
```
I can't open this file with Excel (It tries to recover then fails)
```
Yes, I have the same issue. However, my excel recovered the file and I can open it.

**Comment by YarShev** [comment]
I have figured out why the exception is arisen. The file, which I provided, can be read via xlrd <= 1.2.0 (maybe via even other xlrd versions, but not >= 2.0). However, pandas 1.2.0 uses openpyxl to read the file, if it is installed, that leads to the exception.

**Comment by asishm** [comment]
yes, this is an `openpyxl` bug then.

```py
In [131]: wb = openpyxl.load_workbook(path, read_only=False)

In [132]: wb.sheetnames
Out[132]: []

In [133]: wb.read_only
Out[133]: False

In [134]: wb.worksheets
Out[134]: []
```

`wb.worksheets` is an empty list and pandas does `sheet = wb.worksheets[0]` which is what fails with the IndexError

**Comment by asishm** [comment]
did some digging - again - this is if anything an upstream issue.

openpyxl has this block of code:
```py
        for sheet, rel in self.parser.find_sheets():
            if rel.target not in self.valid_files: # this results in True for all the sheets
                continue
```

the if statement becomes True for all the sheets.
`self.valid_files` is this list 
```
['_rels/',
 '_rels/.rels',
 '[Content_Types].xml',
 'docProps/',
 'docProps/app.xml',
 'docProps/core.xml',
 'xl/',
 'xl/workbook.xml',
 'xl/.DS_Store',
 '__MACOSX/xl/._.DS_Store',
 'xl/worksheets/',
 'xl/styles.xml',
 'xl/theme/',
 'xl/_rels/',
 'xl/sharedStrings.xml',
 'xl/worksheets/Sheet2.xml',
 'xl/worksheets/Sheet3.xml',
 'xl/worksheets/Sheet1.xml',
 'xl/worksheets/Sheet4.xml',
 'xl/theme/theme1.xml',
 'xl/_rels/workbook.xml.rels']
```

but the relationships file (`rel.target`) has the filenames of the sheets as lowercase 

```
['xl/worksheets/sheet1.xml',
 'xl/worksheets/sheet2.xml',
 'xl/worksheets/sheet3.xml',
 'xl/worksheets/sheet4.xml']
```

This probably indicates this is a malformed excel file (given that Excel also tries to "fix" the errors) - so openpyxl may be doing the right thing. I don't particularly intend on reading up the specs as to whether these should be case sensitive or not.

Re-saving the zip after correctly capitalizing the 's' in 'sheetX.xml' in the rels file (`xl\_rels`) makes it readable.

**Comment by YarShev** [comment]
Yes, more accurate error message would be better.

**Comment by simonjayhawkins** [comment]
Thanks @YarShev for the report

since this worked in 1.1.5, i'll label as regression.

> Yes, more accurate error message would be better.

further investigations/PRs welcome

**Comment by asishm** [comment]
@simonjayhawkins The regression is because of the default engine being changed to openpyxl

in 1.1.5, specifying `engine='openpyxl'` leads to the same error. 

There are many such issues where changing the engine has caused issues. #38956 #39001 and (https://github.com/pandas-dev/pandas/issues/34747#issuecomment-691546453 on #34747)

**Comment by simonjayhawkins** [comment]
just to be clear
> @simonjayhawkins The regression is because of the default engine being changed to openpyxl
> 
and this is unlikely to be changed. so any code that worked in 1.1.5 and does not in 1.2 should be considered a regression in the first instance (even if an upstream issue)

> in 1.1.5, specifying `engine='openpyxl'` leads to the same error.
> 

and the converse is also true, specifying `engine='xlrd'` in 1.2 and the code should work fine.

> There are many such issues where changing the engine has caused issues. #38956 #39001 and ([#34747 (comment)](https://github.com/pandas-dev/pandas/issues/34747#issuecomment-691546453) on #34747)

these should probably be labelled as regressions also (will look at these shortly)

**Comment by simonjayhawkins** [comment]
> > There are many such issues where changing the engine has caused issues. #38956 #39001 and ([#34747 (comment)](https://github.com/pandas-dev/pandas/issues/34747#issuecomment-691546453) on #34747)
> 
> these should probably be labelled as regressions also (will look at these shortly)

labelled #38956 and #39001 as regressions. For #34747, or indeed any issue with the openpyxl  engine, since the default has changed could result in a regression from a user POV, we should consider backporting any fixes.
