### ISSUE TITLE
ENH: pivot and pivot_table: option to name levels of new column multiindex

### ISSUE THREAD

**Issue by rchurt** [pandas-dev/pandas#39265]
#### Is your feature request related to a problem?
When I use `pivot` or `pivot_table` and pass a list of `values`, I get a multiindex on the columns, as the docs say. However, there is no kwarg in the `pivot` or `pivot_table` functions to name the levels of this multiindex.

#### Describe the solution you'd like

It would be nice to have a `level_names` kwarg in `pivot` and `pivot_table` so I could pass a string or list of strings for the desired names of the new column multiindex levels.

#### Describe alternatives you've considered

Can be fixed by running `df_pivoted.columns.set_names('name', level=0)`, but it would be nice to not have to do this as a separate step.

```python
df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
                         "bar", "bar", "bar", "bar"],
                   "B": ["one", "one", "one", "two", "two",
                         "one", "one", "two", "two"],
                   "C": ["small", "large", "large", "small",
                         "small", "large", "small", "small",
                         "large"],
                   "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
                   "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})

df_pivoted = df.pivot_table(index=['A','C'], columns='B', values=['D','E'])
# df_pivoted = df.pivot_table(index=['A','C'], columns='B', values=['D','E'], level_names='name') # this is what I want to be able to do

df_pivoted.columns.names # returns [None, 'B'], when what I want is ['name', 'B']

```

**Comment by mroeschke** [comment]
Though convenient, I'd be -1 on adding a new keyword just to add index level names.

Since there is already a method in renaming with `set_names`, I don't think it's worth expanding the API of `pivot_table`.

**Comment by mroeschke** [comment]
Thanks for the suggestion, but since no other core devs have weighed in to support this enhancement going to close. But happy to reopen if it gains renewed support.
