### ISSUE TITLE
Minimal pandas

### ISSUE THREAD

**Issue by blueRegen** [pandas-dev/pandas#39281]
Hi,

thanks for all the hardwork and the wonderful pandas.

Is there a way to install "minimal" pandas ?
I just need dataframe and save to CSV functionality.
We have a requirement to keep our alpine docker container really really small and want to install just the dataframe and csv modules.  is it possible? 

thanks.

**Comment by phofl** [comment]
No, they depend on ohter modules which again depend on ohter modules within pandas and so on

**Comment by jbrockmendel** [comment]
Nothing out of the box, but there are a couple things you could try.

1) remove pandas/tests cuts about 10%
2) could try building without debug symbols https://github.com/cython/cython/issues/2102
