### ISSUE TITLE
CLN: Remove np_datetime64_compat and np_array_datetime64_compat

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#39283]
We probably can remove both checks, see #39092

**Comment by phofl** [comment]
Hm probably can not remove this.

```
np.datetime64("2014-02-01 00:00Z")
```
still raising
```
DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  np.datetime64("2014-02-01 00:00Z")
```

Unless we want to remove the ``Z``?

cc @jreback

**Comment by jbrockmendel** [comment]
We only use it in tests and AFAICT all of those places we'd be better off just stripping the "Z", yes.
