### ISSUE TITLE
DOC: Fix inaccurate statement in 1.2.0 release notes

### ISSUE THREAD

**Issue by rs2** [pandas-dev/pandas#39291]
#### Location of the documentation

https://pandas.pydata.org/docs/whatsnew/v1.2.0.html

#### Suggested fix for documentation

It would be more accurate for [this line](https://github.com/pandas-dev/pandas/blame/ff628b17ccfcaf14ceefeb438aafa56d3849937c/doc/source/whatsnew/v1.2.0.rst#L749) to reference https://github.com/pandas-dev/pandas/pull/37983 (itself) as #27101 does _not_ deal with the `xarray` upgrade, whereas #37983 does.

**Comment by bsun94** [comment]
Hi there, I'm still quite new to contributing to pandas, and I was wondering if help is still needed here?
