### ISSUE TITLE
BUG: ExcelWriter creates Excel file with wrong sheet name.

### ISSUE THREAD

**Issue by izanbf1803** [pandas-dev/pandas#39297]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
writer = pd.ExcelWriter("test.xlsx", engine="openpyxl")
pd.DataFrame().to_excel(writer, sheet_name="sheet", index=False)
writer.save()
pd.read_excel("test.xlsx", sheet_name="sheet")
>> KeyError: 'Worksheet sheet does not exist.'
```

#### Problem description

Executing DataFrame.to_excel() with sheet_name="sheet" creates an Excel with a sheet named "sheet1" instead of the requested name "sheet".

#### Expected Output

An Excel with a sheet named "sheet".

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 9d598a5e1eee26df95b3910e3f2934890d062caa
python           : 3.7.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.8.0-38-generic
Version          : #43~20.04.1-Ubuntu SMP Tue Jan 12 16:39:47 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : es_ES.UTF-8
LOCALE           : es_ES.UTF-8

pandas           : 1.2.1
numpy            : 1.19.5
pytz             : 2020.5
dateutil         : 2.8.1
pip              : 20.3.3
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.6
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by jitendra29mishra** [comment]
This issue is exactly from openpyxl (engine) side.

If you use a different name for your sheet, openpyxl will create Excel with the requested name.

**Comment by izanbf1803** [comment]
In this case, i'll check if this bug is already reported in openpyxl. If it's not reported, i will create a new issue there.

**Comment by rhshadrach** [comment]
Thanks @izanbf1803. Please cross link the issue found or created in case other uses get here.

**Comment by mroeschke** [comment]
Since this is an upstream issue with openpyxl, closing.
