### ISSUE TITLE
DOC: fix the incorrect doc style in 1.2.1

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#39290]
@jorisvandenbossche pls following up and fix the docs

it's not a style issue rather this is completely inconsistent with the current docs 

we NEVER use the style - always ipython docs style

__Originally posted by @jreback in https://github.com/pandas-dev/pandas/pull/39239#issuecomment-763475054__

**Comment by jorisvandenbossche** [comment]
I moved this to the 1.2.2 milestone, there is no need to have this block the release IMO (and 1.2.2 is targetted for a few weeks anyway, which will then still update the docs for this).

Now, about the actual issue:

- About `>>>` vs `In []` ipython style in the code-blcocks: we actually *do* use this style in the docs, see eg in the 1.0.0 release notes: https://pandas.pydata.org/docs/dev/whatsnew/v1.0.0.html#dataframe-rename-now-only-accepts-one-positional-argument. We can of course still discuss that we would like to make this more consistent, but so it is not that this is "never" used
- About code-blocks vs executed ipython directive: I of course needed some code-blocks for the behaviour that will change, therefore I prefer to use plain code blocks for the full example to have consistent look within that subsection (ipython directives and code blocks (even with ipython style In[]) look slightly different)

**Comment by jreback** [comment]
> I moved this to the 1.2.2 milestone, there is no need to have this block the release IMO (and 1.2.2 is targetted for a few weeks anyway, which will then still update the docs for this).
> 
> 
> 
> Now, about the actual issue:
> 
> 
> 
> - About `>>>` vs `In []` ipython style in the code-blcocks: we actually *do* use this style in the docs, see eg in the 1.0.0 release notes: https://pandas.pydata.org/docs/dev/whatsnew/v1.0.0.html#dataframe-rename-now-only-accepts-one-positional-argument. We can of course still discuss that we would like to make this more consistent, but so it is not that this is "never" used


then pls fix those - that is incorrect 

> 
> - About code-blocks vs executed ipython directive: I of course needed some code-blocks for the behaviour that will change, therefore I prefer to use plain code blocks for the full example to have consistent look within that subsection (ipython directives and code blocks (even with ipython style In[]) look slightly different)

pls don't change what we do everywhere else 

we are very consistent about using ipython and not code blocks in new code - this is done deliberately 

if you want to make a style change then propose it rather than unilaterally changing

**Comment by simonjayhawkins** [comment]
moving to 1.2.3

**Comment by simonjayhawkins** [comment]
moved to 1.2.5

**Comment by simonjayhawkins** [comment]
removing the 1.2.5 milestone. does not need to block release. added 1.3 which gives a few extra weeks to fix..

**Comment by yash112-lang** [comment]
Hello @simonjayhawkins, is this issue is still open. I am new to open source, I want to contribute.
