### ISSUE TITLE
Fuzzy match between the left_on and right_on

### ISSUE THREAD

**Issue by BoxOink** [pandas-dev/pandas#39315]
In MSSQL, JOIN statement is allowed to take in LIKE clause instead of the usual exact match condition. 

Hence, I am wondering how is the left_on key being compared to the right_on key in merge. So that maybe I can try to change the exact match to a fuzzy match :(

**Comment by nmay231** [comment]
`pd.merge` only does exact matches with the `left_on`, `right_on`, and `on` arguments. You must do fuzzy merges manually like how [this stackoverflow post](https://stackoverflow.com/questions/13636848/is-it-possible-to-do-fuzzy-match-merge-with-python-pandas) demonstrates.

**Comment by mroeschke** [comment]
Thanks for the request but it appears this hasn't gotten traction in a while so closing
