### ISSUE TITLE
BUG / Question: Cant loop over Full/Complete DataFrame Index

### ISSUE THREAD

**Issue by helloworldnoob** [pandas-dev/pandas#39339]
I have been looping over dataframes from selected indexes. Works fine for the most part, however, when trying to loop over the entire dataframe (rather than using .query() and then saving the queried index), I get KeyError: 4393 

Why I think this is a bug is because I can make it work by doing:
```
dfDbi = dfD.head(4390)  # dataframe has 4393 keys, tried .copy() but no luck with the for loop
dfDbi = dfDbi.query('OC<0').index #saving index to later loop through

# pseudocode
for x in dfDbi:
    if dfD.loc[x] and dfD.loc[x+1] condition true:
        (do something)
```

The above works. Changing dfD.head to (4391) or higher does not. 
What I want to do is:

```
dfDi = dfD.index 

for x in dfDi:
    if dfD[x] and dfD.loc[x+1] condition true:
        (do something)
```

If I have butchered my explanation, please let me know so I can try to further explain.

**Comment by phofl** [comment]
Please provide a reproducible example showing the bug, if you think this is a bug. Otherwise please ask usage question on stackoverflow.

```
df = pd.DataFrame(np.ones(5000))
dfi = df.index 
for x in dfi:
    if all(df.loc[x] == 1) and all(df.loc[x + 1] == 1):
        continue
```

This has to raise because in the last iteration x+1 is no longer in index.

**Comment by helloworldnoob** [comment]
Sorry that is my fault. I wrote the code example wrong.

However now, I have realised my mistake through your answer. I didn't account for the end of the index and the x+1. 

I was using .query() with something else, that wasn't the end of the main dataframe index, hence why it was working as expected.

Thank you! Definitely not a bug, an oversight on my part.
