### ISSUE TITLE
STYLE: cpplint (unintentionally?) skips pandas/_libs/src/ujson/

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#39347]
In code_checks.sh we have
```
cpplint --quiet --extensions=c,h --headers=h --recursive --filter=-readability/casting,-runtime/int,-build/include_subdir pandas/_libs/src/*.h pandas/_libs/src/parser pandas/_libs/ujson pandas/_libs/tslibs/src/datetime pandas/_libs/*.cpp
```

However, `pandas/_libs/ujson` doesn't exist.

I presume `cpplint` should be running on `pandas/_libs/src/ujson/` instead?

**Comment by gcmaciel** [comment]
Yeah, that's true.  It looks like `pandas/_libs/src/ujson/` is the only possible path. 

Adding the missing `/src/` to the path will fix it, I suppose.

**Comment by gcmaciel** [comment]
take
