### ISSUE TITLE
WEB: decommission dev.pandas.io

### ISSUE THREAD

**Issue by afeld** [pandas-dev/pandas#39368]
#### Location of the documentation

http://dev.pandas.io/

#### Documentation problem

Both http://dev.pandas.io/ and https://pandas.pydata.org/docs/dev/ exist, and it's confusing what the difference is / what each are for.

#### Suggested fix for documentation

- [x] Remove references to `dev.pandas.io` -> #39377
- [ ] Ensure all content from http://dev.pandas.io/pandas-blog/ is on https://pandas.pydata.org/community/blog/
   - https://github.com/pandas-dev/pandas-blog/tree/master/content
   - https://github.com/pandas-dev/pandas/tree/master/web/pandas/community/blog
- [ ] Redirect `dev.pandas.io`

**Comment by ayushmankumar7** [comment]
hey @afeld  I am new to this repository. I want to work on this issue. 
I am a bit confused with what exactly this issue expects? 
Removing all references of dev.pandas.io and replace by it's corresponding reference at https://pandas.pydata.org/docs/dev/ ?

**Comment by jorisvandenbossche** [comment]
For the actual content being hosted in different places, it seems we moved the content to `/web/community/blog/` a while ago (https://github.com/pandas-dev/pandas/pull/33178), the but more recent posts were still added in https://github.com/pandas-dev/pandas-blog (cc @TomAugspurger)

**Comment by attack68** [comment]
The 'old' website is showing the current version of pandas 1.0.1.

**Comment by mroeschke** [comment]
Looks like this site is fully not owned by us anymore so closing
