### ISSUE TITLE
participate in Season of Docs?

### ISSUE THREAD

**Issue by afeld** [pandas-dev/pandas#39369]
Google has a [Season of Docs](https://developers.google.com/season-of-docs) program, in which the provide a stipend for people to contribute to documentation of an open source community. Does pandas want to [apply as an Organization](https://developers.google.com/season-of-docs/docs/admin-guide)?

This would also require folks to step up as [Mentors](https://developers.google.com/season-of-docs/docs/mentor-guide) — I am personally interested.

**Comment by jreback** [comment]
we could apply thru NumFocus
only need some mentors and projects written down

**Comment by ReemAlattas** [comment]
I'm in!

**Comment by afeld** [comment]
> only need some…projects written down

We certainly had a lot of ideas at the documentation meeting (#39183), so no shortage there. I'm also going to be making a list of smaller projects for https://github.com/pandas-dev/pandas/issues/39349, so we can use overflow from that.

> I'm in!

Yay! For anyone interested in participating as a writer, see [information about that side of the program](https://developers.google.com/season-of-docs/docs/tech-writer-guide). For anyone interested in being a mentor, I suppose just post in here expressing your interest in mentoring specifically.

**Comment by afeld** [comment]
["Deadline for organization applications" is March 26, 2021 at 18:00 UTC.](https://developers.google.com/season-of-docs/docs/timeline) I'm not going to have bandwidth to take on mentoring after all, unfortunately.

**Comment by afeld** [comment]
Missed this. Ah well!
