### ISSUE TITLE
DOC: split Contributing page

### ISSUE THREAD

**Issue by afeld** [pandas-dev/pandas#39367]
#### Location of the documentation

https://pandas.pydata.org/docs/development/contributing.html

#### Documentation problem

The page is long and covers a lot:

- Environment setup
- The mechanics of contributing to code and docs
- Code standards

#### Suggested fix for documentation

I suggest streamlining the primary Contributing page to be about the basic workflow, splitting out sub-pages for:

- Setting up an environment outside of Docker
   - `Installing a C compiler`
   - `Creating a Python environment`
   - `Creating a Python environment (pip)`
- `Contributing to the code base`
- `Contributing to the documentation`

**Comment by ShrillShrestha** [comment]
Hi @afeld, I am a beginner and am learning to contribute. I haven't use pandas before, but this issue seems interesting. If you can guide me and provide more information regarding the issue (i.e files to change, how to change), maybe I can resolve it.

**Comment by MarcoGorelli** [comment]
Hi @ShrillShrestha - the contributing file is here doc/source/development/contributing.rst

**Comment by ShrillShrestha** [comment]
Thanks, @MarcoGorelli for responding. I am kind of new to .rst files. Can you refer me to some resources I can start with to resolve this issue?

**Comment by David-dmh** [comment]
Hi @MarcoGorelli, new to contributing but keen to help out. Am I understanding correctly that you do not intend to change to contents of the contributing page but rather to reorder the heading in a more logical manner?

**Comment by MarcoGorelli** [comment]
The suggestion is to split out 
```
    Setting up an environment outside of Docker
        Installing a C compiler
        Creating a Python environment
        Creating a Python environment (pip)
    Contributing to the code base
    Contributing to the documentation
```
to be separate pages, rather than all being part of the same `contributing.rst` file

**Comment by Marcopollom** [comment]
Hello @MarcoGorelli, I'm new to contributing but am looking forward to making these changes. Do you know if a Pull Request been made yet (I checked the PR logs but didn't see any).

**Comment by David-dmh** [comment]
take

**Comment by David-dmh** [comment]
Just submitted a PR
