### ISSUE TITLE
BUG: groupby.rolling: Originial index is not being preserved when using date_part of DatetimeIndex and as_index key word seems to have no effect

### ISSUE THREAD

**Issue by derHeinzer** [pandas-dev/pandas#39433]
- [ ] I have checked that this issue has not already been reported.

- [ x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas as pd

data = [
    ["A", "2018-01-01", 100],
    ["A", "2018-01-02", 200],
    ["B", "2018-01-01", 150],
    ["B", "2018-01-02", 250],
]
df = pd.DataFrame(data, columns=["id", "date", "num"])
df["date"] = pd.to_datetime(df["date"])
df.set_index(["date"], inplace=True)


df_res1 = df.groupby([df.id, df.index.weekday]).rolling(window=2, min_periods=1).mean()
df_res2 = df.groupby([df.id, df.index.weekday], as_index=False).rolling(window=2, min_periods=1).mean()
df_res3 = df.groupby([df.id]).rolling(window=2, min_periods=1).mean()
df_res4 = df.groupby([df.id], as_index=False).rolling(window=2, min_periods=1).mean()
pd.show_versions()
print(df_res1.head())
print(df_res1.index.names)
print(df_res2.index.names)
print(df_res3.index.names)
print(df_res4.index.names)


if __name__ == '__main__':
    ...
```

#### Problem description

Comparing pandas 1.0.1 and 1.2.1 yields:
1. When using a date part like df.index.weekday to group by and using some rolling window function like .mean() the original datetime index is not part of the resulting frames index anymore.
2. The group by keyword argumen as_index seems to have no effect in that situation anymore

#### Expected Output
['id', 'date', 'date']
[None, 'date']
['id', 'date']
[None, 'date']

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 9d598a5e1eee26df95b3910e3f2934890d062caa
python           : 3.8.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-45-generic
Version          : #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8
pandas           : 1.2.1
numpy            : 1.19.1

</details>

**Comment by derHeinzer** [comment]
as one might have expected, same applies for expanding functions.

**Comment by ravneetg** [comment]
I had a similar problem with rolling mean with groupby. Should i log this as a separate bug?
[show_versions.txt](https://github.com/pandas-dev/pandas/files/5934789/show_versions.txt)

```
import pandas as pd
df_bug = pd.DataFrame([['2018-10-30', 'key2', 2.02],
       ['2018-10-31', 'key2', 1.68],
       ['2018-11-01', 'key2', 2.47],
       ['2018-11-02', 'key2', 1.0],
       ['2018-11-11', 'key2', 1.45],
       ['2021-01-07', 'key2', 1.86],
       ['2021-01-08', 'key2', 1.86],
       ['2021-01-09', 'key2', 1.64],
       ['2021-01-10', 'key2', 1.59],
       ['2021-01-11', 'key2', 1.43]], columns=["key1", "key2", "raw_value"])

print(df_bug.shape)

# below line returns NaNs
df_bug.groupby("key1")["raw_value"].rolling(3,3).mean()

# below line returns raw value as is
df_bug.groupby("key1")["raw_value"].rolling(3,1).mean()
```

**Comment by abhineetgupta** [comment]
Encountered the same bug, and wasn't able to find a solution in pandas version `1.2.2`.
