### ISSUE TITLE
QST: How to solve the problem KeyError: "['Label'] not found in axis" ??

### ISSUE THREAD

**Issue by ihafsa** [pandas-dev/pandas#39431]
I am working on network traffic classification using tf.keras. i want to drop a column name Label and set Label as Y and all other columns in X.  I am using pandas.  here is the code line:
**df =df.drop(['Label'], axis=1, inplace=True)**

I am getting the following error:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-41-6e2d6c1eb80d> in <module>()
----> 1 df =df.drop(['Label'], axis=1, inplace=True)

3 frames
/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py in drop(self, labels, errors)
   5285         if mask.any():
   5286             if errors != "ignore":
-> 5287                 raise KeyError(f"{labels[mask]} not found in axis")
   5288             indexer = indexer[~mask]
   5289         return self.delete(indexer)

**KeyError: "['Label'] not found in axis**"

I am trying different methods but failed. anyone of you kindly help to get rid of this situation.

**Comment by attack68** [comment]
I will comment that with `inplace=True` `df` is updated and the return is `None` so by then setting `df = None` the result of that code will not work. Use either `df.drop(.., inplace=True)` or `df = df.drop(..)`.

Have you checked that column name `'Label'` is there, e.g. with `df.loc[:, 'Label']`. The error you are getting suggests the column called `'Label'` is not present.

**Comment by ihafsa** [comment]
@attack68 i should not use `inplace=true` ??
and Yes! there are total 88 columns and Label is the last column which contains Labels.

**Comment by phofl** [comment]
If you think this is a bug, please provide a reproducible example

**Comment by mojtabavasou** [comment]
`df = df.drop(df.columns[[87]], axis=1)`
it's work for me.

**Comment by MarcoGorelli** [comment]
closing for now, feel free to ping if you address this:

> If you think this is a bug, please provide a reproducible example
> 
> if this is simply a usage question, please ask these on stackoverflow

**Comment by Mayonnaise-Slap** [comment]
I faced the same problem. It is fixed by renaming the column, so that there are no spaces in there. tensorflow datasets semi-automatically replace spaces by "_", but it somehow breaks on declaring label. So just rename your label column so that it does not have spaces. I also do it to all my other columns, just so it's more convenient. 

```python
YourDataFrame.rename(columns={"your label": "your_label"}, inplace=True)

smth = tfdf.keras.pd_dataframe_to_tf_dataset(YourDataFrame, label='my_label')
```

Hope it helps you
