### ISSUE TITLE
BUG: inconsistent `at` setter method

### ISSUE THREAD

**Issue by andrewjgray1001** [pandas-dev/pandas#39438]
#### Problem description

I am seeing some very strange behaviour. I have a python function which does simple manipulation of data in a DataFrame.

this code is very simple - unit tests work in the relevant package - however the behaviour is very different in server environment - where function is called via rest api.

It turns out that the difference is due to the fact that in the server environment the behaviour of the dataframe 'at' setter method, (ie: myframe.at[rowidx,colkey] = value) is different to that in the package test environment.

in the package test environment the effect of this method is to change the value of the appropriate element of the dataframe - but in the server environment it appears to insert a value after the referenced element. The dataframe changes size - even through the referenced element is within the defined bounds of the data.

as far as I can tell the versions of the relevant libraries packages are exactly the same in both cases - I might be wrong - if I dig into the pandas code - it seems to me to be unnecessarily convoluted, but as far as i can tell the problem happens with frame._set_value in the except clause.

I am a very experienced developer - but not with Python. I have written components similar to DataFrame in C++ in the distant past.

this kind of problem shakes my confidence in deploying anything which might exhibit this kind of behaviour - which causes serious and unpredictable errors downstream rather than an outright runtime error, or maybe I am just using it incorrectly. 

I have dug into this quite a bit - and I am unclear how to further diagnose what is going on.

#### Output of ``pd.show_versions()``

<details>

Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : English_United Kingdom.1252

pandas           : 1.2.1
numpy            : 1.19.5
pytz             : 2020.5
dateutil         : 2.8.1
pip              : 21.0
setuptools       : 49.2.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by attack68** [comment]
can you share a minimalist code snippet that can reproduce the error, or at least provide details to cross validate the behaviour?

**Comment by MarcoGorelli** [comment]
> this code is very simple 

could you share it please? It's hard to know where to begin with this issue otherwise

**Comment by andrewjgray1001** [comment]
yes certainly, the problem is that the behaviour is different in the two different environments - and I dont know what factor is which is causing that.

Here is a simple test function running on the server - I have included the data in the body of the function as as json.

you can see that after the 'at' assignment - the shape of the frame has changed ,,, my understanding is that should not happen.

here is some code:

import numpy as np
import pandas as pd

def f_DataFrameIssue():

    pd.show_versions()

    strJson = {"x":{"0":0.0,"1":1.0101010101,"2":2.0202020202,"3":3.0303030303,"4":4.0404040404,"5":5.0505050505,"6":6.0606060606,"7":7.0707070707,"8":8.0808080808,"9":9.0909090909,"10":10.101010101,"11":11.1111111111,"12":12.1212121212,"13":13.1313131313,"14":14.1414141414,"15":15.1515151515,"16":16.1616161616,"17":17.1717171717,"18":18.1818181818,"19":19.1919191919,"20":20.202020202,"21":21.2121212121,"22":22.2222222222,"23":23.2323232323,"24":24.2424242424,"25":25.2525252525,"26":26.2626262626,"27":27.2727272727,"28":28.2828282828,"29":29.2929292929,"30":30.303030303,"31":31.3131313131,"32":32.3232323232,"33":33.3333333333,"34":34.3434343434,"35":35.3535353535,"36":36.3636363636,"37":37.3737373737,"38":38.3838383838,"39":39.3939393939,"40":40.404040404,"41":41.4141414141,"42":42.4242424242,"43":43.4343434343,"44":44.4444444444,"45":45.4545454545,"46":46.4646464646,"47":47.4747474747,"48":48.4848484848,"49":49.4949494949,"50":50.5050505051,"51":51.5151515152,"52":52.5252525253,"53":53.5353535354,"54":54.5454545455,"55":55.5555555556,"56":56.5656565657,"57":57.5757575758,"58":58.5858585859,"59":59.595959596,"60":60.6060606061,"61":61.6161616162,"62":62.6262626263,"63":63.6363636364,"64":64.6464646465,"65":65.6565656566,"66":66.6666666667,"67":67.6767676768,"68":68.6868686869,"69":69.696969697,"70":70.7070707071,"71":71.7171717172,"72":72.7272727273,"73":73.7373737374,"74":74.7474747475,"75":75.7575757576,"76":76.7676767677,"77":77.7777777778,"78":78.7878787879,"79":79.797979798,"80":80.8080808081,"81":81.8181818182,"82":82.8282828283,"83":83.8383838384,"84":84.8484848485,"85":85.8585858586,"86":86.8686868687,"87":87.8787878788,"88":88.8888888889,"89":89.898989899,"90":90.9090909091,"91":91.9191919192,"92":92.9292929293,"93":93.9393939394,"94":94.9494949495,"95":95.9595959596,"96":96.9696969697,"97":97.9797979798,"98":98.9898989899,"99":100.0},"y1":{"0":0.0,"1":0.0,"2":0.0,"3":0.0,"4":0.0,"5":0.0,"6":1.0,"7":0.0,"8":0.0,"9":0.0,"10":0.0,"11":0.0,"12":0.0,"13":0.0,"14":0.0,"15":0.0,"16":0.0,"17":0.0,"18":-1.0,"19":0.0,"20":0.0,"21":0.0,"22":0.0,"23":0.0,"24":0.0,"25":0.0,"26":0.0,"27":0.0,"28":0.0,"29":0.0,"30":0.0,"31":0.0,"32":0.0,"33":0.0,"34":0.0,"35":0.0,"36":0.0,"37":0.0,"38":0.0,"39":0.0,"40":0.0,"41":1.0,"42":0.0,"43":0.0,"44":0.0,"45":0.0,"46":0.0,"47":0.0,"48":0.0,"49":0.0,"50":0.0,"51":0.0,"52":0.0,"53":0.0,"54":0.0,"55":0.0,"56":-1.0,"57":0.0,"58":0.0,"59":0.0,"60":0.0,"61":0.0,"62":0.0,"63":0.0,"64":0.0,"65":0.0,"66":0.0,"67":0.0,"68":0.0,"69":0.0,"70":0.0,"71":0.0,"72":0.0,"73":0.0,"74":0.0,"75":0.0,"76":0.0,"77":1.0,"78":0.0,"79":0.0,"80":0.0,"81":0.0,"82":-1.0,"83":0.0,"84":0.0,"85":0.0,"86":0.0,"87":0.0,"88":0.0,"89":0.0,"90":0.0,"91":0.0,"92":0.0,"93":1.0,"94":0.0,"95":0.0,"96":0.0,"97":0.0,"98":0.0,"99":0.0},"y2":{"0":0.0,"1":0.0,"2":0.0,"3":0.0,"4":0.0,"5":0.0,"6":0.0,"7":1.0,"8":0.0,"9":0.0,"10":0.0,"11":0.0,"12":0.0,"13":0.0,"14":0.0,"15":0.0,"16":0.0,"17":0.0,"18":0.0,"19":0.0,"20":0.0,"21":0.0,"22":0.0,"23":0.0,"24":0.0,"25":0.0,"26":-1.0,"27":0.0,"28":0.0,"29":0.0,"30":0.0,"31":0.0,"32":0.0,"33":0.0,"34":0.0,"35":0.0,"36":0.0,"37":0.0,"38":0.0,"39":0.0,"40":0.0,"41":0.0,"42":0.0,"43":0.0,"44":0.0,"45":0.0,"46":0.0,"47":0.0,"48":0.0,"49":0.0,"50":0.0,"51":0.0,"52":0.0,"53":1.0,"54":0.0,"55":0.0,"56":0.0,"57":0.0,"58":0.0,"59":0.0,"60":0.0,"61":0.0,"62":0.0,"63":0.0,"64":0.0,"65":-1.0,"66":0.0,"67":0.0,"68":0.0,"69":0.0,"70":0.0,"71":0.0,"72":1.0,"73":0.0,"74":0.0,"75":0.0,"76":0.0,"77":0.0,"78":0.0,"79":0.0,"80":0.0,"81":0.0,"82":0.0,"83":0.0,"84":0.0,"85":0.0,"86":0.0,"87":0.0,"88":0.0,"89":0.0,"90":0.0,"91":0.0,"92":0.0,"93":0.0,"94":0.0,"95":0.0,"96":-1.0,"97":0.0,"98":0.0,"99":0.0}}

    df = pd.DataFrame.from_dict(strJson)

    print(df.shape)

    df.at[82,'y1'] = 0

    print(df.shape)

    return

===========================================================

here is the output of the shapes:

(100, 3)
(101, 3)

**Comment by jreback** [comment]
show the versions

and show do.index 

likely this is object; you are indexing with an integer vs strings

**Comment by andrewjgray1001** [comment]
- versions were shown previously
- what does 'show do.index' mean ?
- yes dataframe is an object, i am indexing rows by integer position, columns by name (string)

**Comment by jreback** [comment]
df.index

and you are NOT indexing by position at all rather by label

use .iat for indexing by position

**Comment by phofl** [comment]
@jreback is right. Your Index consists of strings, at searches for the number 82 in index, can not find it -> enlargment
