### ISSUE TITLE
BUG: read_json(orient='table') converts 'float64' to  'datetime64' datatype if the column name ends with '_time'

### ISSUE THREAD

**Issue by thoo** [pandas-dev/pandas#39430]
- [ X] I have checked that this issue has not already been reported.

- [ X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import numpy as np
import pandas as pd
df1=pd.DataFrame({'test_time':[np.nan,np.nan]})
df1.info()
```
This returns the data type as `float64`.  
```python 
RangeIndex: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   test_time  0 non-null      float64
dtypes: float64(1)
memory usage: 144.0 bytes
```
Now convert `df1` to `json` and convert it back to `DataFrame`. 
```python
df2=pd.read_json(df1.to_json(orient='table'),orient='table')
df2.info()
```
This convert the data type from `float64` to `datetime64` as shown below.
```python
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   test_time  0 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 32.0 bytes
```

The following works as expected if the column named is changed to avoid to end with  `_time` . 

```python
DF1=pd.DataFrame({'test_t':[np.nan,np.nan]})
DF1.info()
DF2=pd.read_json(DF1.to_json(orient='table'),orient='table')
DF2.info()
```
#### Problem description
When the data is read from `json` , the column names ending with `_time` change the data type from `float64` to `datetime64`.  

`DataFrame => to_json (orient='table') => read_json(orient='table') => DataFrame` 
should return the same data type since `orient='table' ` encodes all the column data type in the `json` string. 

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 9d598a5e1eee26df95b3910e3f2934890d062caa
python           : 3.7.8.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.5.0
Version          : Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.1
numpy            : 1.19.4
pytz             : 2020.5
dateutil         : 2.8.1
pip              : 20.3.3
setuptools       : 51.1.1
Cython           : 0.29.21
pytest           : 6.2.1
hypothesis       : None
sphinx           : 3.4.2
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.2
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.8.6 (dt dec pq3 ext lo64)
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.8.3
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.2
numexpr          : 2.7.2
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : 1.0.1
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : 1.3.22
tables           : 3.6.1
tabulate         : 0.8.7
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.50.1

</details>

**Comment by attack68** [comment]
This is probably valid since:

`read_json` has a default kwarg: `convert_dates=True`.

with this applied the following inspection is performed, agreeing with OPs description:

```
            if (
                col_lower.endswith("_at")
                or col_lower.endswith("_time")
                or col_lower == "modified"
                or col_lower == "date"
                or col_lower == "datetime"
                or col_lower.startswith("timestamp")
            ):
                return True
```

`convert_axes` is already adjusted with `orient='table'`, should probably extend to `convert_dates`:

    if convert_axes is None and orient != "table":
        convert_axes = True

**Comment by mroeschke** [comment]
Yes this is documented and the expected behavior from the `keep_default_dates` keyword

> If parsing dates (convert_dates is not False), then try to parse the default datelike columns. A column label is datelike if
it ends with '_at',
it ends with '_time',

Closing as expected.
