### ISSUE TITLE
BUG: DataFrame to_csv compression with 'zip' use zipfilename as archive name

### ISSUE THREAD

**Issue by HQDragon** [pandas-dev/pandas#39465]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

```python
a=pd.DataFrame({'a':[1,2,3,4,5],'b':[4,5,6,7,8]})
a.to_csv('myfile.csv.zip')
```

#### Problem description

when use gzip method, the function works fine, a.to_csv('myfile.csv.gz') will create a gzip file with an archive file named myfile.csv.  
the "zip" method works bad,a.to_csv('myfile.csv.zip') will create a zipfile with an archive file named myfile.csv.zip

**Comment by twoertwein** [comment]
> the "zip" method works bad,a.to_csv('myfile.csv.zip') will create a zipfile with an archive file named myfile.csv.zip 

Do you want to create a PR to remove the ".zip" suffix? If you need a workaround:
`pd.to_csv("test.csv.zip", compression={"method": "zip", "archive_name": "test.csv"})`

> and an strange case shows that a large dataframe will report dumplicate archive name

are you using 1.2.1? #38714

**Comment by HQDragon** [comment]
> > the "zip" method works bad,a.to_csv('myfile.csv.zip') will create a zipfile with an archive file named myfile.csv.zip
> 
> Do you want to create a PR to remove the ".zip" suffix? If you need a workaround:
> `pd.to_csv("test.csv.zip", compression={"method": "zip", "archive_name": "test.csv"})`
> 
> > and an strange case shows that a large dataframe will report dumplicate archive name
> 
> are you using 1.2.1? #38714

now i'm using 1.2.1,i add a pr(#39647 ) to do some work with the name problem,but not the large dataframe problem

**Comment by twoertwein** [comment]
do you still have the issue with the large dataframe when using 1.2.1?

**Comment by WillAyd** [comment]
Is this different than #26023?

**Comment by HQDragon** [comment]
> Is this different than #26023?

same purpose, but my PR#40387 will take "myfile" as archive_name when "myfile.zip" used as zipfile name,just like gzip or xz. It won't add ".csv" to the end of "myfile" automatically.
"myfile.csv.zip"->"myfile.csv"
"myfile.zip"->"myfile"
"myfile.csv.csv.zip"->"myfile.csv.csv"
