### ISSUE TITLE
DOC: Add header to `test_writing.rst`

### ISSUE THREAD

**Issue by gcmaciel** [pandas-dev/pandas#39468]
#### Location of the documentation

https://github.com/pandas-dev/pandas/blob/master/doc/source/development/test_writing.rst

#### Documentation problem

The `test_writitng.rst` file doesn't have the standard header.

#### Suggested fix for documentation

This can be fixed by adding `{{ header }}` at the beginning of the file.

**Comment by jorisvandenbossche** [comment]
Is it a problem that this header is not present in this file?

**Comment by gcmaciel** [comment]
I wouldn't call this a *problem*, per se,  but since all the `.rst` files contain this header, it looks like there's a standard, am I right?

**Comment by jorisvandenbossche** [comment]
Yes, but it's only needed for pages that actually have ipython code blocks that get executed (and this page doesn't have that) + there is also an issue about removing this `header` -> https://github.com/pandas-dev/pandas/issues/28038

**Comment by gcmaciel** [comment]
Yeah there's a full discussion about it. Thanks for clarifying!
