### ISSUE TITLE
BUG: GroupBy Aggregation Behavior

### ISSUE THREAD

**Issue by clampr** [pandas-dev/pandas#39489]
- I have asked my usage related question on [StackOverflow](https://stackoverflow.com/questions/65955108/pandas-groupby-aggregation-behavior).

---

#### Question About GroupBy Aggregation Behavior

I observed a behavior of the Pandas GroupBy method `agg()` which I cannot explain based on the [docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.DataFrameGroupBy.aggregate.html).

I want to perform a custom aggregation on a grouped `DataFrame`. Let's take this code snippet:

```python
def aggregate_point(x):
 print(x)
 exit()

data = data.groupby(
 pd.Grouper(level='time', freq='1H')).agg(aggregate_point)
```

This prints a `Series` for each group.

However, when I pass any additional parameter to `aggregate_point`, the full `DataFrame` is being printed:

```python
def aggregate_point(x, score):
 print(x)
 exit()

data = data.groupby(
 pd.Grouper(level='time', freq='1H')).agg(aggregate_point, score=True)
```

Why does the `score` parameter influence the value of `x` (`DataFrame` vs. `Series`)?

**Comment by rhshadrach** [comment]
This is a bug, related to #39169. The addition of a parameter should not have this influence.

**Comment by jnchngc** [comment]
take

**Comment by mroeschke** [comment]
Closing at this appears identical to https://github.com/pandas-dev/pandas/issues/39169
