### ISSUE TITLE
BUG: Stack creates duplicate column

### ISSUE THREAD

**Issue by soerenwolfers** [pandas-dev/pandas#39481]
```
import numpy as np
import pandas as pd

df = pd.DataFrame(
    np.zeros([1, 5]), 
    columns=pd.MultiIndex.from_tuples(
        [
            (0, None, None), 
            (0, 0, 0),
            (0, 0, 1),
            (0, 1, 0),
            (0, 1, 1),
        ],
    )
)
```
![image](https://user-images.githubusercontent.com/16045385/106360891-efe11980-6312-11eb-8682-a5ed546b8d10.png)
```
df.stack(2)
```
![image](https://user-images.githubusercontent.com/16045385/106360914-05564380-6313-11eb-8ebb-b5a35a74f4b5.png)

```

INSTALLED VERSIONS
------------------
commit           : b5958ee1999e9aead1938c0bba2b674378807b3d
python           : 3.6.6.final.0
pandas           : 1.1.5
numpy            : 1.17.4
```

**Comment by phofl** [comment]
That is not really a duplicate, the first 1 is representing the NaN. The MultiIndex handling was not correct.

**Comment by soerenwolfers** [comment]
Right,  my original problem was that I got an error when trying to stack both the last two levels of the columns. Error message said something about duplicate columns, and when I made the MWE it seemed to fit

**Comment by aelshazlyIT** [comment]
might be the MultiIndex handling was not correct.

**Comment by phofl** [comment]
> That is not really a duplicate, the first 1 is representing the NaN. The MultiIndex handling was not correct.

Yes, is fixed in my pr
