### ISSUE TITLE
CI: green builds

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#39541]
so the confluence of some pyarrow pinning and release of numpy 1.20 are causing pain rn. several PRs have addressed most of these. I think 38_locale is the remaining problem, needs to pin pyarrow. 

We need to get to green on master & 1.2.2 before any other PRs.

cc @pandas-dev/pandas-core

**Comment by MarcoGorelli** [comment]
> before any other PRs.

Read this after having merged #39500, though that was only a simple doc change - sorry about that, won't do any more til it's all green again

**Comment by jorisvandenbossche** [comment]
The reason it was failing because 1) we were pinning to pyarrow 1.0.0, and only 1.0.1 was rebuilt on conda-forge to be compatible with numpy 1.20, and 2) pyarrow 0.17 was also not rebuilt, which is done now, but I think it is fine to keep the pin to an older numpy version on that CI build.
