### ISSUE TITLE
QST:How to implement the _reduce on ExtentionArray to enable df.max() call it.

### ISSUE THREAD

**Issue by cvcv2525** [pandas-dev/pandas#39555]
- [ yes] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ yes] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---
Currently I am working on a project about the extension array, while I have some problems related to the _reduce.
First I define my extension array. 
```python
d4 = MyArray(Farr(np.array([[3,4,1,2],[3,5,2,1]])))
df4 = pd.DataFrame(d4, dtype = MyDtype())
```
it looks like this

	0	1	2	3
0	Sfixed(value=3)	Sfixed(value=4)	Sfixed(value=1)	Sfixed(value=2)
1	Sfixed(value=3)	Sfixed(value=5)	Sfixed(value=2)	Sfixed(value=1)

where Sfixed is my own object.

Then I put it into DataFrame, then I call 
df4.max(), it would not call the _reduce in my EA.
while run df4[0].max(), it would call the _reduce in my EA,  this is correct.

My question is how to enable df.max() or df.std(), or df.abs() call my _reduce in EA?

Thanks!

**Comment by jorisvandenbossche** [comment]
@cvcv2525 what version of pandas are you using? 
We had quite some changes related to the reduction implementation the last months, and I *think* we should be calling `ExtensionArray._reduce` is most common cases.

**Comment by mzeitlin11** [comment]
Closing for now since nothing actionable here, but please ping to reopen if you can respond to the question (and maybe post an example of your code `ExtensionArray` definition).
