### ISSUE TITLE
CI: have database builds *just* run db tests

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#39550]
The database builds: https://github.com/pandas-dev/pandas/pull/39457/checks?check_run_id=1797892949

take the longest. we should just have this run the database tests only. (so add a marker for the appropriate tests / just run the sql tests entirely).

**Comment by jreback** [comment]
cc @fangchenli

**Comment by fangchenli** [comment]
> cc @fangchenli

What shall we do for the cov build? If only run db test, we don't have the coverage anymore.
