### ISSUE TITLE
BUG: Erroneous join error message

### ISSUE THREAD

**Issue by fonnesbeck** [pandas-dev/pandas#39560]
I'm trying to execute a simple left join on a single column, as follows:

```python
data2016.join(expected_runs, how='left', on='STATE')
```

However, it fails with the message:

```
ValueError: You are trying to merge on object and int64 columns. If you wish to proceed you should use pd.concat
```

Looking at the STATE column in each table, it shows that both are object columns:

<img width="394" alt="Screen Shot 2021-02-02 at 9 24 57 AM" src="https://user-images.githubusercontent.com/81476/106621793-8a6e7200-6538-11eb-8955-0efeac1e3ba5.png">

Note that using `merge` works as follows:

    pd.merge(data2016, expected_runs, how='left', on='STATE')

Here is the full error trace:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-58-bbf0335fbf11> in <module>
----> 1 data2016.join(expected_runs, how='left', on='STATE')

~/anaconda3/envs/baseball/lib/python3.8/site-packages/pandas/core/frame.py in join(self, other, on, how, lsuffix, rsuffix, sort)
   8105         5  K5  A5  NaN
   8106         """
-> 8107         return self._join_compat(
   8108             other, on=on, how=how, lsuffix=lsuffix, rsuffix=rsuffix, sort=sort
   8109         )

~/anaconda3/envs/baseball/lib/python3.8/site-packages/pandas/core/frame.py in _join_compat(self, other, on, how, lsuffix, rsuffix, sort)
   8130                     sort=sort,
   8131                 )
-> 8132             return merge(
   8133                 self,
   8134                 other,

~/anaconda3/envs/baseball/lib/python3.8/site-packages/pandas/core/reshape/merge.py in merge(left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
     72     validate=None,
     73 ) -> "DataFrame":
---> 74     op = _MergeOperation(
     75         left,
     76         right,

~/anaconda3/envs/baseball/lib/python3.8/site-packages/pandas/core/reshape/merge.py in __init__(self, left, right, how, on, left_on, right_on, axis, left_index, right_index, sort, suffixes, copy, indicator, validate)
    670         # validate the merge keys dtypes. We may need to coerce
    671         # to avoid incompatible dtypes
--> 672         self._maybe_coerce_merge_keys()
    673 
    674         # If argument passed to validate,

~/anaconda3/envs/baseball/lib/python3.8/site-packages/pandas/core/reshape/merge.py in _maybe_coerce_merge_keys(self)
   1191                     inferred_right in string_types and inferred_left not in string_types
   1192                 ):
-> 1193                     raise ValueError(msg)
   1194 
   1195             # datetimelikes must match exactly

ValueError: You are trying to merge on object and int64 columns. If you wish to proceed you should use pd.concat
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 9d598a5e1eee26df95b3910e3f2934890d062caa
python           : 3.8.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.2.0
Version          : Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.1
numpy            : 1.20.0
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 49.6.0.post20210108
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 3.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.6.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 0.16.2
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by phofl** [comment]
Hi, thanks for your report. Please provide a reproducible example. see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by rhshadrach** [comment]
Join works on the index of other (expected_runs in this case). What is the dtype of that index?

**Comment by fonnesbeck** [comment]
Here are the indices:

<img width="697" alt="Screen Shot 2021-02-03 at 9 41 25 AM" src="https://user-images.githubusercontent.com/81476/106770913-0bdf0680-6604-11eb-8a14-1749b8a87720.png">

**Comment by fonnesbeck** [comment]
Its clear I should be using `merge` instead of `join`, though I still would have expected `join` to work.

**Comment by phofl** [comment]
Please provide a reproducible example, which can be executed

**Comment by rhshadrach** [comment]
@fonnesbeck - join is to be used when joining on other's index which is an integer here. So you are joining an object to an integer, as the error message says. I don't think there is anything to be done here.

As a note for any future issues, as @phofl has requested, please always include a reproducible example.
