### ISSUE TITLE
pandas 1.2.0 - drop_duplicates()

### ISSUE THREAD

**Issue by ilyosbekibrohimov** [pandas-dev/pandas#39562]
Hi everyone, I was using the .drop_duplicates() function to remove duplicate values from the .csv  file,  but unfortunately, it removed some non-duplicate values from my table.  So what would you recommend me to save non-duplicate values while dropping duplicates from the .csv  file using  drop_duplicates() function?
one small  part of  my  code:
            table = pd.read_csv(csv_path, low_memory=False, names=['timestamp', 'data'])
            table = table.drop_duplicates()
            table = table.sort_values(by=['timestamp'])
            table.to_csv(csv_path, index=False)
Thank you!

```

**Comment by MarcoGorelli** [comment]
> So what would you recommend me to save non-duplicate values while dropping duplicates from the .csv file using drop_duplicates() function?

Hi @ilyosbekibrohimov - this is the kind of question you'd typically want to ask on StackOverflow

If you believe there's a bug in pandas, please include a reproducible example, see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by ilyosbekibrohimov** [comment]
thanks
