### ISSUE TITLE
ENH: fnmatch for easier wildcard str matching

### ISSUE THREAD

**Issue by shaharkadmiel** [pandas-dev/pandas#39565]
I wish `fnmatch` was one of the str accessors.

regex (in `str.match` for instance) are sometimes complicated and unintuitive. Shell wildcards, although limited, are easy.

If I want to match all SEED channel codes (max 3 characters) for example that end with 'Z' in a column named `cha_code`, I could do:

```python
from fnmatch import fnmatch
df.cha_code.apply(fnmatch, args=('??Z', )) 
```

or

```python
df.cha_code.apply(fnmatch, args=('*Z', )) 
```

If there was an `str.fnmatch` accessor method:

```python
df.cha_code.str.fnmatch('*Z')
```

This is of course a simple example that can be handled with `endswith` but the idea is clear - I think.

This does not break anything else as far as I can think.

Another option is to add this functionality to `str.match` but as `pat` is already expecting a regex I am not sure how to avoid confusion. May be add a `fnmatch: bool` kwarg to switch between regex and fnmatch style patterns.

**Comment by rhshadrach** [comment]
> regex (in str.match for instance) are sometimes complicated and unintuitive

Okay - but in the case where you only want to support `?` and `*`, it's just using `.` and `.*` instead. I don't see that as complicated. Or is there more here?

**Comment by shaharkadmiel** [comment]
It would allow the use of all Unix shell-style wildcards:

```
Pattern | Meaning
* | matches everything
? | matches any single character
[seq] | matches any character in seq
[!seq] | matches any character not in seq
```
Translating these to regex, in your head, is not hard but for me, and I guess many other *nix users this is easier and more intuitive. 

This style of wildcards are also the standard in the seismology community for requesting data through web-apis and data selection tools. 

See for example in ObsPy’s [Stream.select](https://docs.obspy.org/packages/autogen/obspy.core.stream.Stream.select.html) near the bottom, or [Client.get_waveforms](https://docs.obspy.org/packages/autogen/obspy.clients.fdsn.client.Client.get_waveforms.html)

**Comment by jreback** [comment]
this is not standard and extra confusing - regexes are enough 
-1 on any change.

**Comment by mroeschke** [comment]
Agreed, I believe this does not warrant another API method (which pandas is trying to avoid increasing as pandas contains a large API surface area). Thanks for the suggestion, but since this feature hasn't gotten much further support from the team, going to close.
