### ISSUE TITLE
BUG: apply on Series of dtype category produces dtype category when float was expected

### ISSUE THREAD

**Issue by mkp-gebensleben** [pandas-dev/pandas#39580]
I'm trying to get the left edge from a Series of Intervals. Unexpectedly, the result is a Series of dtype category. I'm also getting a FutureWarning.

```python
>>> import pandas as pd
>>> s = pd.Series(pd.cut([1, 2, 3], 2))
>>> s
0    (0.998, 2.0]
1    (0.998, 2.0]
2      (2.0, 3.0]
dtype: category
Categories (2, interval[float64]): [(0.998, 2.0] < (2.0, 3.0]]
>>> s.apply(lambda x: x.left)
C:\Users\My.Name\.virtualenvs\MyRepo-nagZr6A2\lib\site-packages\pandas\io\formats\format.py:1403: FutureWarning: Index.ravel returning ndarray is deprecated; in a future version this wi
ll return a view on self.
  for val, m in zip(values.ravel(), mask.ravel())
0    0.998
1    0.998
2    2.000
dtype: category
Categories (2, float64): [0.998 < 2.000]
```

Interestingly, the individual cells have objects with the correct dtype:

```python
>>> result = s.apply(lambda x: x.left)
>>> type(result[0])
<class 'numpy.float64'>
```

However, operations you would expect from a Series of floats to work do not work:

```python
>>> result + 1
[...]
TypeError: unsupported operand type(s) for +: 'Categorical' and 'int'
```

<details><summary>pd.show_versions()</summary>
INSTALLED VERSIONS<br>
------------------<br>
commit           : 9d598a5e1eee26df95b3910e3f2934890d062caa<br>
python           : 3.8.7.final.0  <br>
python-bits      : 64  <br>
OS               : Windows  <br>
OS-release       : 10<br>
Version          : 10.0.19041<br>
machine          : AMD64<br>
processor        : AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD<br>
byteorder        : little<br>
LC_ALL           : None<br>
LANG             : None<br>
LOCALE           : de_DE.cp1252<br>
pandas           : 1.2.1<br>
numpy            : 1.20.0<br>
pytz             : 2021.1<br>
dateutil         : 2.8.1<br>
pip              : 20.3.3<br>
setuptools       : 51.1.2<br>
Cython           : None<br>
pytest           : 6.2.2<br>
hypothesis       : None<br>
sphinx           : None<br>
blosc            : None<br>
feather          : None<br>
xlsxwriter       : None<br>
lxml.etree       : None<br>
html5lib         : None<br>
pymysql          : None<br>
psycopg2         : None<br>
jinja2           : 2.11.3<br>
IPython          : 7.20.0<br>
pandas_datareader: None<br>
bs4              : None<br>
bottleneck       : None<br>
fsspec           : None<br>
fastparquet      : None<br>
gcsfs            : None<br>
matplotlib       : None<br>
numexpr          : None<br>
odfpy            : None<br>
openpyxl         : 3.0.6<br>
pandas_gbq       : None<br>
pyarrow          : None<br>
pyxlsb           : None<br>
s3fs             : None<br>
scipy            : 1.6.0<br>
sqlalchemy       : 1.3.23<br>
tables           : None<br>
tabulate         : 0.8.7<br>
xarray           : None<br>
xlrd             : None<br>
xlwt             : None<br>
numba        : None<br>
</details>

**Comment by sahahn** [comment]
So cut returns a Categorical Series, which while the individual items might be float64 I think it is expected behavior that you can't add a value. I.e., what if the categories were 'cat' and 'dog', you should not be able to add 1 to 'dog'. I think you could either set labels = False when calling cut or cast the result s to type float if you want.

The FutureWarning though seems like its from:
def format_with_na_rep(values: ArrayLike, formatter: Callable, na_rep: str):
            mask = isna(values)
            formatted = np.array(
                [
                    formatter(val) if not m else na_rep
                    for val, m in zip(values.ravel(), mask.ravel())
                ]
            ).reshape(values.shape)
            return formatted
in https://github.com/pandas-dev/pandas/blob/c322b2436cdbb447a430bb9eb1aff965d07e7e4e/pandas/io/formats/format.py

It seems like this might still be fine even after ravel returns a view on self, so could maybe be muted? But I'm not sure

**Comment by mkp-gebensleben** [comment]
> So cut returns a Categorical Series, which while the individual items might be float64 I think it is expected behavior that you can't add a value

How is that relevant? `lambda x: x.left` returns a float.

**Comment by attack68** [comment]
> It seems wildly inconsistent to me that Series of dtype category are the ONLY Series where `apply(foo)` does not care about the types of the values returned by `foo`. Instead, it always produces a Series of dtype category, no matter what you `apply`. No other dtype behaves like this.

Are you sure no other dtype behaves likes this? Tracing the function identifies a check performed on the series:

``is_extension_array_dtype(s)``

It seems that extension arrays are classified as:

```
    Notes
    -----
    This checks whether an object implements the pandas extension
    array interface. In pandas, this includes:

    * Categorical
    * Sparse
    * Interval
    * Period
    * DatetimeArray
    * TimedeltaArray
```

In the case that it *is* an extension array the function is applied and no conversion takes place. 

In the case that it is *not* one of the above, there is some dtype conversion taking place. [see core/apply.py lines 855-860]

**Comment by mkp-gebensleben** [comment]
Thank you, that's good to know. If "never convert" is really intended for these dtypes, maybe it should be mentioned in the `Series.apply` documentation?

For example:

<pre>
convert_dtypebool, default True

    Try to find better dtype for elementwise function results. If False, leave as dtype=object.
    For the dtypes X, Y and Z the original dtype is kept.
</pre>

**Comment by attack68** [comment]
Yes indeed, a good opportunity for contributions perhaps :)

**Comment by sukriti1** [comment]
take

**Comment by sukriti1** [comment]
take
