### ISSUE TITLE
BUG: Support keywords in pd.Timestamp.isoformat(), ref.#26131 is stale.

### ISSUE THREAD

**Issue by boringow** [pandas-dev/pandas#39583]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

```python

import pandas as pd
now=pd.Timestamp.utcnow()
now.isoformat(timespec="milliseconds")
print(now)

```

#### Problem description

The isoformat is just to follow the ISO format 8601, but it is not detecting any keywords.

#### Expected Output

"2020-02-03 21:54:34:024"

#### Output of ``pd.show_versions()``

</details>

INSTALLED VERSIONS
------------------
commit           : 9d598a5e1eee26df95b3910e3f2934890d062caa
python           : 3.8.2.final.0
python-bits      : 32
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : es_ES.cp1252

pandas           : 1.2.1
numpy            : 1.20.0
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 20.3.1
setuptools       : 51.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

**Comment by phofl** [comment]
Hi, what do you expect here? This is exactly the same as #26131

**Comment by boringow** [comment]
Yeah, but the issue #26131 is stale and still not fixed.

**Comment by boringow** [comment]
@jreback told me to open a new PR, as I am having the same issue.

**Comment by phofl** [comment]
PR is Pull Request not Issue?

The PR is stale not the issue

**Comment by boringow** [comment]
Oh sorry. I did not know what PR was. I am really trying to help in here but as I am new everyone looks really busy. I will pull a new PR request now 👍

**Comment by phofl** [comment]
Closing then
