### ISSUE TITLE
QST: is the behavior of Series comparison intended?

### ISSUE THREAD

**Issue by itholic** [pandas-dev/pandas#39588]
#### Question about pandas

For `Series.eq`, In the doc it says "Equivalent to `series == other`" but it seems not true.

Let me show a simple example.

```python
>>> a = pd.Series([1, 1, 1, np.nan], index=['a', 'b', 'c', 'd'])
>>> b = pd.Series([1, np.nan, 1, np.nan], index=['a', 'b', 'd', 'e'])

>>> a.eq(b)
a     True
b    False
c    False
d    False
e    False
dtype: bool

>>> a == b
Traceback (most recent call last):
...
ValueError: Can only compare identically-labeled Series objects
```

Series comparison with `eq` API works, whereas `==` raise an Exception.

Is it intended behavior ??

Thanks :)

**Comment by nmay231** [comment]
Yes, I believe this is intended behavior.

Your example fails because the indexes are not the same. `['a', 'b', 'c', 'd'] != ['a', 'b', 'd', 'e']`. Try using the same index, and you'll see that using `==` works. `.eq()` happens to work because it ignores the index when checking for equality.

**Comment by itholic** [comment]
Thanks for the answer, @nmay231 :)
