### ISSUE TITLE
BUG:When reading in a csv with MultiIndex columns, duplicated level names mangled

### ISSUE THREAD

**Issue by samgalen** [pandas-dev/pandas#39590]
- [X] I have checked that this issue has not already been reported. 

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.
 (I created a venv, and installed pandas version 1.2.1, but did not clone/build from source, not sure if that counts or not).
---

A csv with MultiIndexed columns, when read in appends a .1, .2, etc. unnecessarily. 

#### Code Sample, a copy-pastable example

```python
import pandas as pd
import numpy as np

# creating a multi-Indexed csv

cols = [
    ("Left", "Tier 2", "Column 1"),
    ("Left", "Tier 2", "Column 2"),
    ("Left", "Tier 2", "Total"),
    ("Right", "Tier 2", "Total")]

df = pd.DataFrame(np.arange(20).reshape((5,4)))
df.columns = pd.MultiIndex.from_tuples(cols)
print(df.head())

df.to_csv("test.csv")

read_df = pd.read_csv("./test.csv", header=[0,1], index_col=0)
print(read_df.head())

# output

# the original dataframe
      Left                 Right
    Tier 2                Tier 2
  Column 1 Column 2 Total  Total
0        0        1     2      3
1        4        5     6      7
2        8        9    10     11
3       12       13    14     15
4       16       17    18     19

# dataframe after being read back in from read_csv
         Left                     Right
       Tier 2  Tier 2.1 Tier 2.2 Tier 2
NaN  Column 1  Column 2    Total  Total
0.0         0         1        2      3
1.0         4         5        6      7
2.0         8         9       10     11
3.0        12        13       14     15

```

#### Problem description

In the example, the function read_csv appends a .1, .2 etc. to levels in a multi-indexed column. This is unnecessary, since the columns are uniquely identified by ("Left, "Tier 2", "Column 1"), ("Left", "Tier 2", "Column 2"), so in theory there should be no column name overlap. This is additionally undesirable, as one of the main benefits to having a multi-index is the ability to access subsets of columns easily. 

#### Expected Output

The level names should not be mangled. Specifically, the expected output should be

```python
      Left                 Right
    Tier 2                Tier 2
  Column 1 Column 2 Total  Total
0        0        1     2      3
1        4        5     6      7
2        8        9    10     11
3       12       13    14     15
4       16       17    18     19
```

And 

```python
print(read_df.columns.values)
```

```python
array([("Left", "Tier 2", "Column 1"),
       ("Left", "Tier 2", "Column 2"),
       ("Left", "Tier 2", "Total"),
       ("Right", "Tier 2", "Total")])
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 9d598a5e1eee26df95b3910e3f2934890d062caa
python           : 3.9.1.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
Version          : Darwin Kernel Version 18.7.0: Tue Nov 10 00:07:31 PST 2020; root:xnu-4903.278.51~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.1
numpy            : 1.20.0
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 20.2.3
setuptools       : 49.2.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by nmay231** [comment]
I don't think you're reading the full header. Try changing the line:

```diff
- read_df = pd.read_csv("./test.csv", header=[0,1], index_col=0)
+ read_df = pd.read_csv("./test.csv", header=[0,1,2], index_col=0)
```

**Comment by samgalen** [comment]
Oh - you know what, you're right. Thank you!

After this, I looked more closely at the non-minimal case that caused me to generate this report, and realized that the columns were encoded incorrectly in the CSV.

**Comment by nmay231** [comment]
No problem :+1:
