### ISSUE TITLE
DOC: Group optional dependencies by relevant topic

### ISSUE THREAD

**Issue by nmay231** [pandas-dev/pandas#39594]
#### Location of the documentation

URL: https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#optional-dependencies
File in GitHub: https://github.com/pandas-dev/pandas/blob/master/doc/source/getting_started/install.rst

#### Documentation problem

The list of optional dependencies is currently just listed in alphabetical order. However, I think it would be much more logical to group packages by topic (PyTables **reads/writes hdf5** files, xlrd **reads Excel** files). Then you can compare/contrast which packages you should install for *your* usecase, e.g. should I install openpyxl or xlrd to read my excel files; I should research more about them.

Additionally, it might be helpful to include more detailed information about how they're different, but I am not as familiar with the minute differences between them. That will have to be for another time.

#### Suggested fix for documentation

I am willing to work on this.

I could either a) add a fourth column to the dependency table listing which group it is a part of (read/write HTML, read/write Excel), or b) split it into multiple tables with a minor header for each group.

Are there any issues with making this change, and which of those two actions should I prefer?

**Comment by jreback** [comment]
multiple tables would be ok (prob need an other section for ones that don't group well)
