### ISSUE TITLE
QST: Pandas plot Invalid RGBA argument when defining color and style

### ISSUE THREAD

**Issue by Sikerdebaard** [pandas-dev/pandas#39596]
When plotting a line chart with a defined color per line and a defined linestyle per line, using the plot function in a pandas DataFrame an invalid RGBA argument exception is thrown. When one defines either color or linestyle the code works, but it looks like you can't do both at the same time. Further more, this behavior only seems to occur when using one or more 'o' style lines. How come?

```python
import pandas as pd
import numpy as np


df = pd.DataFrame(np.random.randn(1000, 4), index=pd.date_range("1/1/2000", periods=1000), columns=list("ABCD"))
df = df.cumsum()

style = ['-'] * 3 + ['o']

colors = [
    [.6, .6, .6],
    [0, .7, .1],
    [1, .5, .1],
    [0.66, 0.55, 0.84],
]
        
params = dict(
    color=colors,
    style=style,
)

ax = df.plot(**params)
```

**Comment by Sikerdebaard** [comment]
This is caused because the target machine was running python 3.6.9. The newest version of pandas that runs on this version of python is pandas==1.1.5. This problem does not occur when running a newer version of python combined with pandas==1.2.1.

**Comment by MarcoGorelli** [comment]
Thanks @Sikerdebaard 

> This problem does not occur when running a newer version of python combined with pandas==1.2.1.

Closing then, but do write if you run into problems with v1.2.1
