### ISSUE TITLE
DOC: Enhance docs for Styler: details and high level.

### ISSUE THREAD

**Issue by attack68** [pandas-dev/pandas#39593]
#### Location of the documentation

`ecosystem`, + `user_guide/index.rst + style.ipynb + visualization.rst`
 possibly others.

#### Documentation problem and proposed changes.

**High Level**

Scientific data visualization is not just restricted to charting. Tabular data visualization is important and `Styler` has some really good features for dealing with this - albeit `Styler` is not a recognised scientific term.

Currently the `User Guide` has left navigation links `Visualization` and `Styling`, and I would like to rename them `Chart Visualization` and `Table Visualization` and put them next to each other in the list. Also with some cross-refs.
The `Api` page has a `Style` navigation link which is probably best left as is due to API naming.

**Low Level**

a) I will revisit the `style.ipynb` page and update it with many of the new features, and possibly provide more of a continuous real-case example, rather than using numpy.random repeatedly to demonstrate the features. This isn't completely necessary but maybe works well.

b) I will revisit the function doc strings to ensure consistency on the API page (there is some inconsistency currently) and add examples where missing to the API page.

<br>
<br>

If you feel this is warranted or have any comments on the items please share before I get started.

**Comment by jreback** [comment]
sounds reasonable

note that we can do redirects for new page names (see conf.py)
