### ISSUE TITLE
ENH: Index Left Alignment Option in a DataFrame

### ISSUE THREAD

**Issue by nataligracia** [pandas-dev/pandas#39602]
I wish I could align the contents of the index in a DataFrame to the left.

I could set the index as a column, and then hide the remaining index. This is not ideal, because I'd like to keep the pandas dataframe index formatting (i.e. bolding). Currently, it is possible to left align the columns within dataframes, just not the index.

![GitHub PandasIssue](https://user-images.githubusercontent.com/64047614/106974226-31096d00-6709-11eb-9dae-933d7f0c3288.png)

**Comment by attack68** [comment]
when displaying a DataFrame use `Styler` and you can control many properties,

e.g.

```
df = pd.DataFrame(np.random.randn(2,2), index=['Big School', 'Little School'], columns=['Data 1', 'More Data'])
df.style.format({'Data 1': '{:,.1f}', 'More Data': '{:,.3f}'})\
        .set_table_styles([{'selector': 'td', 'props': [('text-align', 'center'),
                                                        ('color', 'red')]},
                           {'selector': '.col_heading', 'props': [('text-align', 'right'),
                                                                  ('color', 'green'),
                                                                  ('width', '150px')]},
                           {'selector': '.row_heading', 'props': [('text-align', 'left'),
                                                                  ('color', 'blue')]}],
                           {'selector': '', 'props': [('width', '50%')]})
```
![Screen Shot 2021-02-05 at 07 24 12](https://user-images.githubusercontent.com/24256554/106997440-2db2c780-6783-11eb-9968-b15c846c4c51.png)

**Comment by nataligracia** [comment]
Thank you!
