### ISSUE TITLE
BUG: Inconsistency between Period.ordinal and Timestamp.fromordinal()

### ISSUE THREAD

**Issue by EBenkler** [pandas-dev/pandas#39613]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas as pd
ordinaldate = pd.Period(pd.Timestamp('2020-12-31'), freq='s').ordinal
pd.Timestamp.fromordinal(ordinaldate)
```

#### Problem description

The code snippet raises the error message:
*** ValueError: year 4406314 is out of range

#### Expected Output

Timestamp('2020-12-31 00:00:00')

Maybe I completely misunderstand the concept of Period and Timestamp, but I would expect that when I convert from a Period to an ordinal date, and subsequently convert back to a Timestamp, I should get the initial Timestamp.

I am specifically interested in the inverse operation of the conversion to ordinal in class PeriodConverter(dates.DateConverter)

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 9d598a5e1eee26df95b3910e3f2934890d062caa
python           : 3.8.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
machine          : AMD64
processor        : Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en
LOCALE           : de_DE.cp1252

pandas           : 1.2.1
numpy            : 1.20.0
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 49.6.0.post20210108
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 3.4.3
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.20.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 3.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.6.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by jbrockmendel** [comment]
A Period's ordinal is unrelated to Timestamp.fromordinal.  To round-trip, you'd need to do something like `Period(...).to_timestamp("S").toordinal()`

**Comment by EBenkler** [comment]
> 
> 
> A Period's ordinal is unrelated to Timestamp.fromordinal. To round-trip, you'd need to do something like `Period(...).to_timestamp("S").toordinal()`

Thanks for your reply. Yes, it is obvious that Period and Timestamp ordinals are not the same. Your suggestion doesn't help me though, as I need to convert Period().ordinal (generated by Pandas' plotting date converters) back to Period. Meanwhile I found a workaround using the internal method `Period._from_ordinal()`.
