### ISSUE TITLE
BUG:weeks = df.groupby(['CUSTOMER_ID', 'SALES_WEEK']).aggregate({'SALES_AMOUNT' :                                                        {'HISTORIC_VISITS' : 'count',                                                         'HISTORIC_SALES':'sum',                                                         'STD_SALESAMOUNT':'std',                                                        'VARIATION_SALESAMOUNT':'var',                                                        'MIN_SALESAMOUNT':'min',                                                        'MAX_SALESAMOUNT': 'max'}}).reset_index()

### ISSUE THREAD

**Issue by jawadnaseemkhan** [pandas-dev/pandas#39611]
- [x] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here

```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by attack68** [comment]
I can see this is your first issue report. Some advice..

You have not given any details or described what is the error.
Just giving a single line of code is unhelpful, it is also most likely an error unique to you and not to Pandas.

Better to provide a better description, and show some code that allows others to reproduce and debug the error that you are facing.
