### ISSUE TITLE
BUG: .query() using uint64 column fails with TypeError "dtype could not be cast"

### ISSUE THREAD

**Issue by FenderJazz** [pandas-dev/pandas#39617]
#### Code Sample, a copy-pastable example

```python
import pandas as pd
df = pd.DataFrame({'x': [1,2,3]}, dtype='uint64')
df = df.query('x > 1')
print(df)
```

#### Problem description

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-44-168c7ec0f5d8> in <module>
      1 import pandas as pd
      2 df = pd.DataFrame({'x': [1,2,3]}, dtype='uint64')
----> 3 df = df.query('x > 1')
      4 print(df)

~\.conda\envs\digital-activity\lib\site-packages\pandas\core\frame.py in query(self, expr, inplace, **kwargs)
   3464         kwargs["level"] = kwargs.pop("level", 0) + 1
   3465         kwargs["target"] = None
-> 3466         res = self.eval(expr, **kwargs)
   3467 
   3468         try:

~\.conda\envs\digital-activity\lib\site-packages\pandas\core\frame.py in eval(self, expr, inplace, **kwargs)
   3594         kwargs["resolvers"] = kwargs.get("resolvers", ()) + tuple(resolvers)
   3595 
-> 3596         return _eval(expr, inplace=inplace, **kwargs)
   3597 
   3598     def select_dtypes(self, include=None, exclude=None) -> DataFrame:

~\.conda\envs\digital-activity\lib\site-packages\pandas\core\computation\eval.py in eval(expr, parser, engine, truediv, local_dict, global_dict, resolvers, level, target, inplace)
    345         eng = ENGINES[engine]
    346         eng_inst = eng(parsed_expr)
--> 347         ret = eng_inst.evaluate()
    348 
    349         if parsed_expr.assigner is None:

~\.conda\envs\digital-activity\lib\site-packages\pandas\core\computation\engines.py in evaluate(self)
     71 
     72         # make sure no names in resolvers and locals/globals clash
---> 73         res = self._evaluate()
     74         return reconstruct_object(
     75             self.result_type, res, self.aligned_axes, self.expr.terms.return_type

~\.conda\envs\digital-activity\lib\site-packages\pandas\core\computation\engines.py in _evaluate(self)
    112         scope = env.full_scope
    113         _check_ne_builtin_clash(self.expr)
--> 114         return ne.evaluate(s, local_dict=scope)
    115 
    116 

~\.conda\envs\digital-activity\lib\site-packages\numexpr\necompiler.py in evaluate(ex, local_dict, global_dict, out, order, casting, **kwargs)
    834     _numexpr_last = dict(ex=compiled_ex, argnames=names, kwargs=kwargs)
    835     with evaluate_lock:
--> 836         return compiled_ex(*arguments, **kwargs)
    837 
    838 

TypeError: Iterator operand 1 dtype could not be cast from dtype('uint64') to dtype('int64') according to the rule 'safe'
```

Failure when using an unsigned dtype should work (and worked in earlier versions, for example 1.0.3).

#### Expected Output

   x
1  2
2  3

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 9d598a5e1eee26df95b3910e3f2934890d062caa
python           : 3.8.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 2012ServerR2
Version          : 6.3.9600
machine          : AMD64
processor        : Intel64 Family 6 Model 26 Stepping 5, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252

pandas           : 1.2.1
numpy            : 1.19.4
pytz             : 2020.5
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 49.6.0.post20210108
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.6 (dt dec pq3 ext lo64)
jinja2           : 2.11.3
IPython          : 7.19.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 0.8.5
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : 2.7.2
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : 0.5.2
scipy            : 1.6.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
numba            : None
</details>

**Comment by lithomas1** [comment]
@FenderJazz Seems like a problem with numexpr not pandas with the uint64 dtype. 
Can you try ```df.query('x' > '1', engine='python')```, which works for me?

**Comment by lithomas1** [comment]
Looking at the numexpr docs, it says

> Datatypes supported internally
> Numexpr operates internally only with the following types:
>
> * 8-bit boolean (bool)
> * 32-bit signed integer (int or int32)
> * 64-bit signed integer (long or int64)
>
> * 32-bit single-precision floating point number (float or float32)
> * 64-bit, double-precision floating point number (double or float64)
> * 2x64-bit, double-precision complex number (complex or complex128)
> * Raw string of bytes (str)
> If the arrays in the expression does not match any of these types, they will be upcasted to one of the above types (following the usual type inference rules, see below). Have this in mind when doing estimations about the memory consumption during the computation of your expressions.
> 
> Also, the types in Numexpr conditions are somewhat more restrictive than those of Python. For instance, the only valid constants for booleans are True and False, and they are never automatically cast to integers. 

So it seems like uint64 is not supported and cannot be cast safely to a supported type.

**Comment by FenderJazz** [comment]
Thank you, @lithomas1.  I should have read the NumExpr docs before logging this.  I was distracted by the fact that uints were apparently OK in earlier versions, but I suppose it's quite possible that earlier NumExpr behaviour with unsigned types was problematic in non-obvious ways.  I'm closing this, as to me the current behaviour seems to be as documented.

**Comment by FenderJazz** [comment]
This does work for me, by the way:

`
df.query('x' > '1', engine='python')
`

This also works:

`
df = pd.DataFrame({'x': [1,2,3]}, dtype='uint32')
df = df.query('x > 1')
`

It is my bad luck that I am using uint64, and there's nowhere to go from there!
