### ISSUE TITLE
ENH: vector methods for conversion from Period to its ordinal and back

### ISSUE THREAD

**Issue by JacekPliszka** [pandas-dev/pandas#39628]
#### Is your feature request related to a problem?

a) Currently to get Series of ordinal of Period Series I do

`s.apply(lambda  x: x.ordinal)

b) Also to get back I do

`s.apply(lambda x: Period(ordinal=x, 'W-SAT'))

c) And last but not least:

s.astype(int).astype('period[W-SAT]') is different than s.

#### Describe the solution you'd like

a)
s.ordinal  returns series with ordinals

b)
There is some easy method to create series of Periods from ordinals... like Period(s, 'W-SAT')
or s.astype('period[W-SAT]', from_ordinal=True)

c) last option in b) is kind of solution to c)

[this should provide a description of the feature request, e.g. "`DataFrame.foo` should get a new parameter `bar` that [...]", try to write a docstring for the desired feature]

#### API breaking implications

Mostly it won't but if .astype('period[W-SAT]') would use ordinals then yes as currently 2650 means year nor ordinal for this method

**Comment by jreback** [comment]
i am not sure why you actually want the ordinals and how they r useful

**Comment by jbrockmendel** [comment]
is `ser._values.asi8` what you're looking for?

**Comment by JacekPliszka** [comment]
> is `ser._values.asi8` what you're looking for?

Yes, this is exactly a), thank you!

What about setting it ?
```
>>> d.sp._values.asi8 = np.array([2670, 2672])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: can't set attribute
```

**Comment by JacekPliszka** [comment]
> i am not sure why you actually want the ordinals and how they r useful

I am doing operations on weeks. period[W-SAT] is a great abstraction but I would love to be able to operate on week number sometimes.

e.g. I am working on things that happen in some weeks and match them with things in other weeks, or shift things by couple weeks forth or back - this is all very easy and fast with week numbers as integers.

I am also considering using categoricals for that but I hate micromanagement there (category union etc.)

The only piece I am missing now is the way to quickly assign/modify Period values by ordinals in series.

**Comment by jbrockmendel** [comment]
even simpler:

```
i8vals = ser.view("i8")
i8vals[:] = np.array([2670, 2672])
```

**Comment by JacekPliszka** [comment]
Thanks! Then I believe I do not need it.
