### ISSUE TITLE
BUG: pd.to_timedelta needs rounding argument to eliminate floating-point imprecision

### ISSUE THREAD

**Issue by Caballero93** [pandas-dev/pandas#39675]
- [ ] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
a = 0.00026
print(pd.to_timedelta(a, unit='s'))

```

#### Problem description

As can be seen with the provided code, thanks to floating-point imprecision, the result is 0 days 00:00:00.000259999. The expected result is of course 260us. Because of this, synchronously sampled data can appear as asynchronous, which can cause issues. If this cannot be fixed differently, workaround would be to provide some rounding option to user, so it can be assured that output has the expected value

#### Expected Output
260us
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 9d598a5e1eee26df95b3910e3f2934890d062caa
python           : 3.8.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Serbian (Latin)_Serbia.1250
pandas           : 1.2.1
numpy            : 1.19.0
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 21.0
setuptools       : 47.1.0
Cython           : 0.29.16
pytest           : 6.0.1
hypothesis       : None
sphinx           : 1.7.0
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.1.2
numexpr          : 2.7.2
odfpy            : None
openpyxl         : 1.7.0
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.1
sqlalchemy       : None
tables           : 3.6.1
tabulate         : 0.8.3
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : None

</details>

**Comment by mroeschke** [comment]
You can call round after the `to_timedelta` call to achieve the result you want: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Timedelta.round.html
