### ISSUE TITLE
BUG: Undesired non-deterministic reordering when indexing by unordered iterable

### ISSUE THREAD

**Issue by Verhoef-W** [pandas-dev/pandas#39671]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample

```python
import pandas as pd
df = pd.DataFrame([], columns=[2, 1, 0])
df2 = df[{2, 1, 0}]

# expect column order to be preserved
assert((df.columns == df2.columns).all())

```

#### Problem description

An unordered iterable such as a set iterates in a non-deterministic way. Thus a reordering of the columns when indexing with an unordered iterable would be undesirable. It should be desirable that in those cases a preservation of the order is guaranteed. This should not be considered a breaking change, since the results were never guaranteed to be in a specific ordering in those cases.

#### Expected Output
See Code Sample.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : b5958ee1999e9aead1938c0bba2b674378807b3d
python           : 3.6.9.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
Version          : Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None
pandas           : 1.1.5
numpy            : 1.19.5
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 19.0.3
setuptools       : 40.8.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.0
html5lib         : 1.1
pymysql          : 0.9.3
psycopg2         : 2.8.4 (dt dec pq3 ext lo64)
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.15
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by alexprincel** [comment]
New here so may be wrong but it seems more like a feature request than a bug.

**Comment by debnathshoham** [comment]
A set is an _unordered_ data structure. I think ordering / reordering of a set is meaningless. 
If I am not wrong the re-ordering in the example happens in python (and has nothing to do with pandas).
```python
In [1]: {2,1,0}
Out[1]: {0, 1, 2}

**Comment by phofl** [comment]
Passing sets as indexers is deprecated.

In general the result is returned in the same order as the indexer is given. I think we can close this

**Comment by mroeschke** [comment]
Agreed this was deprecated in 1.4, so I don't think this is addressable anymore. Closing
