### ISSUE TITLE
DOC: Adding links to the cheat sheets

### ISSUE THREAD

**Issue by OliEfr** [pandas-dev/pandas#39706]
#### Location of the documentation

Cheat Sheets

#### Documentation problem

It would be great to have web-links to the official pandas docs included in the cheat sheets.

#### Suggested fix for documentation

I already implemented this [here](https://github.com/OliEfr/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf). It works well! However, I am not sure how to create a pull request now.

**Comment by OliEfr** [comment]
For the PR some checks failed. However, I am not sure how to resolve them.
I didn't change anything in the codebase anyway.

**Comment by lithomas1** [comment]
@OliEfr looks like the CI failures are #39688. Can you merge master to fix?
