### ISSUE TITLE
BUG: `Style` index name row does not label column class

### ISSUE THREAD

**Issue by attack68** [pandas-dev/pandas#39716]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

The `Styler` ignores column class on the `index_name` row and just inputs `blank`, which is a pain for controlling `table_styles` using column selectors.

```
df3 = pd.DataFrame(0, index=['a'], columns=['A','B'])
df3.index.name = 'foo'
print(df3.style.render())
```

```
<style type="text/css">
</style>
<table id="T_a6821_">
  <thead>
    <tr>
      <th class="blank level0" ></th>
      <th class="col_heading level0 col0" >A</th>
      <th class="col_heading level0 col1" >B</th>
    </tr>
    <tr>
      <th class="index_name level0" >foo</th>
      <th class="blank" ></th>
      <th class="blank" ></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th id="T_a6821_level0_row0" class="row_heading level0 row0" >a</th>
      <td id="T_a6821_row0_col0" class="data row0 col0" >0</td>
      <td id="T_a6821_row0_col1" class="data row0 col1" >0</td>
    </tr>
  </tbody>
</table>
```

Internal mechanics should be fixed to add the col index class.

**Comment by AkshatGadhwal** [comment]
Hii, I am new to open source and decided to fix this bug because it is labeled "good first issue". But I am facing difficulty in starting. 
In which file should I make changes? ( i mean where should I do changes ?).

**Comment by attack68** [comment]
The offending lines of code are in `pandas/io/formats/style.py` 

```
 476           index_header_row.extend(
 477               [{"type": "th", "value": BLANK_VALUE, "class": " ".join([BLANK_CLASS])}]
 478               * (len(clabels[0]) - len(hidden_columns))
 479            )
```

you need to make the `class` value show more than just "blank", i.e. it should be `col<k>` where k if from a loop of columns conditional on any hidden columns being excluded.
