### ISSUE TITLE
ENH: handling units.

### ISSUE THREAD

**Issue by lohraspco** [pandas-dev/pandas#39713]
#### Is your feature request related to a problem?
I wish we could manage units of measurements in pandas. 

#### Describe the solution you'd like

For example a temperature column may have the unit of Fahrenheit, if we need to convert the units to Centigrade it will be nice to convert it without creating the convertor functions. Here are some ideas: 
Series.unit returns the current unit of measurement (e.g., Fahrenheit). 
Series.to_unit() returns a series with the unit in parameter  (e.g., Series.to_unit('Fahrenheit')).

More complex units can be electricity consumption and electricity demand.

**Comment by mroeschke** [comment]
Thanks for the report. We are tracking this issue in https://github.com/pandas-dev/pandas/issues/10349 so going to close this is favor of that.
