### ISSUE TITLE
QST: Passing data class to DataFrame constructor

### ISSUE THREAD

**Issue by paulalex** [pandas-dev/pandas#39723]
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

My question  is quite simple, I have some code which builds a list of objects defined in a `Dataclass` and until today I was calling `asdict()` to convert them into dictionaries as I thought this was something I needed to do.

Today I removed this and the excel generation still works as expected but I would like to know if this now supported behaviour.

```python
# previously this was a list of dictionaries, and it is now a list of custom data classes
pd.DataFrame(renewals).reindex(columns=get_report_columns())
```

**Comment by MarcoGorelli** [comment]
Hi @paulalex - yes, [as documented](https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.html), you can initialise a DataFrame using dataclasses
