### ISSUE TITLE
BUG: import absolut path to style.py --> class Styler:

### ISSUE THREAD

**Issue by MarcinP94** [pandas-dev/pandas#39733]
- [x] I have checked that this issue has not already been reported. 
- [x] I have confirmed this bug exists on the latest version of pandas.
- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: 

#### Code Sample,

```python
import os
class Styler:
    absolute_dir = os.pwd()
    loader = jinja2.PackageLoader("pandas", absolute_dir +"/io/formats/templates")
    env = jinja2.Environment(loader=loader, trim_blocks=True)
    template = env.get_template("html.tpl")
```

#### Problem description

It allows including html.tpl as a local static file when styling of the dataframe is needed, and it works when is needed to transform python file into exe via pyinstaller.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

- [ ] </details>

**Comment by attack68** [comment]
I don't really understand the problem here.

1. The offending code lines seem relevant to the `jinja2` package and its internal loading?
2. The code above is not `pandas` signature. You are defining your own Styler class, augmented from the official vesion.

What is it you are proposing?

**Comment by MarcinP94** [comment]
Pandas DataFrame with method **.style** does not work after transformation from .py file into exe (pyinstaller) with error  **jinja2.exceptions.TemplateNotFound --> html.tpl** . I solve the issue with the way which i presented above just simply add absolute path to local copy but i would like to highlight the issue which will help to to find more generic solution as a library owner.

**Comment by jreback** [comment]
@MarcinP94 this relates not to pandas itself but to pyinstaller
