### ISSUE TITLE
QST:   File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item

### ISSUE THREAD

**Issue by Picbull** [pandas-dev/pandas#39749]
Hi ! I have some kind of hard time using panda to read a data base. My objective and my issue are simple, yet i'm unable to find a solution on other trending issues. 
I'm trying to access the index of a column using it's name :

indicecol=df.columns.get_loc(nomF)

where nomF is the name of the column and is asked as an imput. I think the probleme is that my imput is "PK [m]" and the function doesn't like the brackets.

I have this error message : 

File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'PK [m]'

Does anybody know how to get around this ? 

Thx !

**Comment by jreback** [comment]
you need to make a copy pastable example that is reproducible

**Comment by jbrockmendel** [comment]
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by MarcoGorelli** [comment]
closing, will reopen if you provide a reproducible example
