### ISSUE TITLE
BUG: to_datetime throws TypeError: unhashable type: 'list' even with errors='ignore'

### ISSUE THREAD

**Issue by adamerose** [pandas-dev/pandas#39756]
I'm getting this error when I try converting certain `Series` to datetime using `pd.to_datetime`, even though I pass `errors='ignore'`

```python
_ = pd.to_datetime(pd.Series([['a']]*50), errors='ignore')  # works
_ = pd.to_datetime(pd.Series([['a']]*51), errors='ignore')  # error
```
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python38\lib\site-packages\pandas\core\tools\datetimes.py", line 801, in to_datetime
    cache_array = _maybe_cache(arg, format, cache, convert_listlike)
  File "C:\Python38\lib\site-packages\pandas\core\tools\datetimes.py", line 173, in _maybe_cache
    if not should_cache(arg):
  File "C:\Python38\lib\site-packages\pandas\core\tools\datetimes.py", line 137, in should_cache
    unique_elements = set(islice(arg, check_count))
TypeError: unhashable type: 'list'
```

**Comment by rhshadrach** [comment]
Can you post an example that doesn't require pickle?

**Comment by MarcoGorelli** [comment]
Thanks @adamerose - could you please upload your in a format other than `pickle`?

---

https://docs.python.org/3/library/pickle.html :

> 
> Warning
> 
> The pickle module is not secure. Only unpickle data you trust.
> 
> It is possible to construct malicious pickle data which will execute arbitrary code during unpickling. Never unpickle data that could have come from an untrusted source, or that could have been tampered with.
> 
> Consider signing data with hmac if you need to ensure that it has not been tampered with.
> 
> Safer serialization formats such as json may be more appropriate if you are processing untrusted data. See Comparison with json.
>

**Comment by bjornjorgensen** [comment]
Hi you can load it from my arangodb server 

import pandas as pd
import json
import re
from pandasgui import show
from arango import ArangoClient

client = ArangoClient(hosts='http://bjhjemme.duckdns.org:8529')

db = client.db('test_2015-2020', username='test', password='test')

aql = db.aql

cursor = db.aql.execute('FOR c IN FORM_3 RETURN c', batch_size=1)
result = [c for c in cursor]

df = pd.json_normalize(result, max_level=None)

df = df.drop(columns=['_key', '_id', '_rev'])
df = df.dropna(axis=1, how='all')
show(df) #show are for pandagui.


You can brows the files in http://bjhjemme.duckdns.org:8529 logg in with test and test

**Comment by adamerose** [comment]
This reproduces it with no other packages needed:
```
import pandas as pd
import json
s_raw = pd.read_csv('https://github.com/adamerose/temp/raw/main/test.csv')['test']
s = s_raw.apply(lambda x: json.loads(x.replace('\'', '"')) if type(x) == str else x)

# these work
x = pd.to_datetime(s[:35], errors='ignore')
x = pd.to_datetime(s[25:], errors='ignore')
# this doesn't
x = pd.to_datetime(s, errors='ignore')
```

**Comment by MarcoGorelli** [comment]
Thanks @adamerose 

simpler reproducer:
```python
>>> pd.to_datetime(pd.Series([['a']]*50), errors='ignore')
0     [a]
1     [a]
2     [a]
3     [a]
4     [a]
5     [a]
6     [a]
7     [a]
8     [a]
9     [a]
10    [a]
11    [a]
12    [a]
13    [a]
14    [a]
15    [a]
16    [a]
17    [a]
18    [a]
19    [a]
20    [a]
21    [a]
22    [a]
23    [a]
24    [a]
25    [a]
26    [a]
27    [a]
28    [a]
29    [a]
30    [a]
31    [a]
32    [a]
33    [a]
34    [a]
35    [a]
36    [a]
37    [a]
38    [a]
39    [a]
40    [a]
41    [a]
42    [a]
43    [a]
44    [a]
45    [a]
46    [a]
47    [a]
48    [a]
49    [a]
dtype: object
>>> pd.to_datetime(pd.Series([['a']]*51), errors='ignore')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marco/pandas-marco/pandas/core/tools/datetimes.py", line 814, in to_datetime
    cache_array = _maybe_cache(arg, format, cache, convert_listlike)
  File "/home/marco/pandas-marco/pandas/core/tools/datetimes.py", line 186, in _maybe_cache
    if not should_cache(arg):
  File "/home/marco/pandas-marco/pandas/core/tools/datetimes.py", line 150, in should_cache
    unique_elements = set(islice(arg, check_count))
TypeError: unhashable type: 'list'
```

**Comment by rhshadrach** [comment]
@adamrose - I've removed the link to your pickle file in the OP. In general one should not load pickles unless the source is trusted as they can execute arbitrary code.

**Comment by adamerose** [comment]
@rhendric Understood, no problem. I only resorted to posting that because I couldn't figure out a way to reproduce it programmatically initially. Thanks for providing that @MarcoGorelli, I'll edit that into the OP
