### ISSUE TITLE
CI: remove the current coverage build, run coverage on multiple builds instead

### ISSUE THREAD

**Issue by fangchenli** [pandas-dev/pandas#39758]
Currently, we upload one coverage report from `actions-37-cov`. It takes the longest. But Codecov automatically merges multiple reports. See details https://docs.codecov.io/docs/merging-reports. So we could run coverage on multiple shorter builds.

We need to select a set of builds (create new ones if needed), add `-cov` to the name of their environment files (suggested by @jreback ), update their CI configs to upload reports to Codecov, and remove the `actions-37-cov` build if it's no longer required.

**Comment by MarcoGorelli** [comment]
Reopening as #40394 didn't remove actions-37-cov, but i think i that can be done now if there's no issues
