### ISSUE TITLE
BUG: setitem with ArrayManager not preserving PeriodDtype

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#39763]
cc @jorisvandenbossche this is coming up the quantile tests with --array-manager

```
index = pd.period_range("2016-01-01", periods=9, freq="D", name="A")
obj = pd.DataFrame(index).copy()

obj.iloc[:] = index._na_value

>>> obj.dtypes
A    datetime64[ns]
dtype: object
```

We'd like to keep `period[D]` here.

**Comment by jorisvandenbossche** [comment]
That seems fixed with https://github.com/pandas-dev/pandas/pull/39578 (`setitem` is not yet implemented for ArrayManager on master)

**Comment by jbrockmendel** [comment]
fixed on main, may need test

**Comment by srkds** [comment]
take
