### ISSUE TITLE
Object to String conversion Does not work in Panda

### ISSUE THREAD

**Issue by saniyaparveez** [pandas-dev/pandas#39818]
I have a dataset consisting of 10,00,000 rows and one column has a data type of value eg. 'FY2020-Q1' and I am trying to convert this to a String Data type because I would like to apply a filter of == but it does not work when using with **astype.**
Basically, the conversion does not work on a huge dataset but on a small dataset, it works.

`df['fyq'] = df['fyq'].astype(str) and  also`

`df['fyq'] = df['fyq'].astype('string')`

I would like to filter like:  `df[df.fyq== 'FY2020-Q4']`

Pandas version in use is **1.2.2**

**Comment by phofl** [comment]
Please provide something reproducible

Did you check https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.StringDtype.html#pandas.StringDtype?

**Comment by MarcoGorelli** [comment]
closing, will reopen if you provide a reproducible example
