### ISSUE TITLE
BUG: Problems round-tripping categoricals to/from parquet

### ISSUE THREAD

**Issue by secure-mail-documentation-project** [pandas-dev/pandas#39838]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import os
import pandas as pd

fname = 'categorical_test'

data = {
    'int': pd.Series([0, 1] * 1000, dtype=pd.CategoricalDtype([0,1])),
    'str': pd.Series(['foo', 'bar'] * 1000, dtype=pd.CategoricalDtype(['foo', 'bar'])),
}
df = pd.DataFrame(data)

for write in ['fastparquet', 'pyarrow']:
    for read in ['fastparquet', 'pyarrow']:
        if os.path.exists(fname):
            os.remove(fname)
        df.to_parquet(fname, engine=write, compression=None)
        df_read = pd.read_parquet(fname, engine=read)

        print()
        print('write:', write, 'read:', read)
        for t in data.keys():
            print(t, df[t].dtype == df_read[t].dtype)
```

#### Problem description

Pandas does not reliably round-trip categorical columns to/from parquet.

This problem was originally reported on the pyarrow bug tracker by @chrisroat in https://github.com/apache/arrow/issues/1688#issuecomment-751128963. I appears that it was not reported to pandas though.

Output from the test-case above:

```
write: fastparquet read: fastparquet
int True
str True

write: fastparquet read: pyarrow
int False
str False

write: pyarrow read: fastparquet
int True
str True

write: pyarrow read: pyarrow
int False
str True
```

#### Expected Output

```
write: fastparquet read: fastparquet
int True
str True

write: fastparquet read: pyarrow
int True
str True

write: pyarrow read: fastparquet
int True
str True

write: pyarrow read: pyarrow
int True
str True
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 9d598a5e1eee26df95b3910e3f2934890d062caa
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
machine          : AMD64
processor        : Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_Germany.1252

pandas           : 1.2.1
numpy            : 1.19.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 20.3.3
setuptools       : 52.0.0.post20210125
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.20.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : 0.5.0
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 3.0.0
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.51.2

</details>

**Comment by jorisvandenbossche** [comment]
This was actually followed up as a JIRA issue on the pyarrow side: https://issues.apache.org/jira/browse/ARROW-11157

**Comment by mroeschke** [comment]
This is seems like an issue with pyarrow, not sure if there's any further action on the pandas side so closing. Happy to reopen if I misunderstood
