### ISSUE TITLE
BUG: When checking equality of column dtype - TypeError: Cannot interpret 'datetime64[ns, UTC]' as a data type

### ISSUE THREAD

**Issue by adamerose** [pandas-dev/pandas#39839]
This code reproduces the error:
```python
import pandas as pd

df = pd.DataFrame([{'publish_time': pd.Timestamp('2017-11-13 17:13:01+0000', tz='UTC'),
                    'title': 'A'},
                   {'publish_time': pd.Timestamp('2017-11-13 07:30:00+0000', tz='UTC'),
                    'title': 'B'},
                   {'publish_time': pd.Timestamp('2017-11-12 19:05:24+0000', tz='UTC'),
                    'title': 'C'},
                   {'publish_time': pd.Timestamp('2017-11-13 11:00:04+0000', tz='UTC'),
                    'title': 'D'},
                   {'publish_time': pd.Timestamp('2017-11-12 18:01:41+0000', tz='UTC'),
                    'title': 'E'}])
# This works
print(df['publish_time'].dtype == df['title'].dtype)
# This throws an error
print(df['title'].dtype == df['publish_time'].dtype)
```

```
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-25-1048e1cb1cf5>", line 1, in <module>
    print(df['title'].dtype == df['publish_time'].dtype)
TypeError: Cannot interpret 'datetime64[ns, UTC]' as a data type
```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : 7d32926db8f7541c356066dcadabf854487738de
python           : 3.8.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252
pandas           : 1.2.2
numpy            : 1.19.3
pytz             : 2020.4
dateutil         : 2.8.1
pip              : 20.2.1
setuptools       : 49.2.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.19.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.17.1
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.20
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
numba            : None

</details>

**Comment by nmay231** [comment]
I think this is more of an issue on numpy's side. Looking at the types:

```python
type(df['title'].dtype), type(df['publish_time'].dtype)
# (numpy.dtype[object_], pandas.core.dtypes.dtypes.DatetimeTZDtype)
```

`df['title'].dtype.__eq__()` should probably just return `False` instead of raising a type error. I would open an issue in the numpy repo and see if there is a specific reason `.__eq__()` raises an error. If they don't want to change it, then pandas can potentially include a wrapper for numpy dtypes that works around this issue.

**Comment by jreback** [comment]
there are multiple numpy reports for this but it won't likely change 

pandas already wraps is_* comparison methods 

so nothing to do here - won't fix

**Comment by mroeschke** [comment]
Closing as it seem that is an upstream issue.
