### ISSUE TITLE
February 2021 Docs Meeting

### ISSUE THREAD

**Issue by afeld** [pandas-dev/pandas#39833]
- [Thursday, February 25th at 9-10am US Eastern Time](https://everytimezone.com/s/f469edb9)
- [Zoom link](https://nyu.zoom.us/j/98201283174?pwd=d0VoUy9GTDRlVVZ0cCtTK0s4NnlBZz09)
- [Agenda/notes](https://docs.google.com/document/d/1JoiqTdK6gi5W1QiTWrqtTV-rNmIqU3xROgHY5iT4J5g/edit#heading=h.1obsyhexqytc)

---

~~Please [**provide your availability**](https://doodle.com/poll/inay6zfys98t49sv?utm_source=poll&utm_medium=link) in the next few days so we can find a time that works for the most people. Will comment with the date and Zoom link once finalized.~~ All are welcome.

We just kicked off HackIllinois where I'm mentoring students as they contribute to pandas documentation (https://github.com/pandas-dev/pandas/issues/39349), so hoping they can make it to the meeting to see the glamorous side of open source: governance! 😉 

[Agenda/notes doc](https://docs.google.com/document/d/1JoiqTdK6gi5W1QiTWrqtTV-rNmIqU3xROgHY5iT4J5g/edit#heading=h.1obsyhexqytc) — feel free to add things in advance. Thanks!

- [x] Start notes doc section
- [x] Finalize time
- [x] Add to calendar
- [x] Send invite to students

@pandas-dev/pandas-core @pandas-dev/pandas-triage @pandas-dev/pydata-sphinx-theme

**Comment by afeld** [comment]
Last call for [specify your availability](https://doodle.com/poll/inay6zfys98t49sv?utm_source=poll&utm_medium=link) for those who want to come!

**Comment by afeld** [comment]
Let's go with same time as before, [9am US Eastern Time, on Thursday, February 25th](https://everytimezone.com/s/f469edb9). Connection info up top.

Would someone mind adding it to the calendar, and make it recurring, staggered two weeks from the Dev meetings?

**Comment by TomAugspurger** [comment]
@afeld I added it to the pandas calendar.

**Comment by afeld** [comment]
Starting now! https://nyu.zoom.us/j/98201283174?pwd=d0VoUy9GTDRlVVZ0cCtTK0s4NnlBZz09

**Comment by afeld** [comment]
Good meeting, thanks folks!
