### ISSUE TITLE
BUG: Creating empty datetime64[ns] column should not try to use cache

### ISSUE THREAD

**Issue by nicolaslegrand91** [pandas-dev/pandas#39843]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas as pd
import numpy as np
import timeit

df = pd.DataFrame(index=range(10000))

# Create empty float column by assigning np.nan
print(timeit.timeit(
    "df['float_col'] = np.nan",
    number=10,
    globals=globals()
))

# Create empty datetime64[ns] column by assigning pd.NaT
print(timeit.timeit(
    "df['datetime_col_no_typing'] = pd.NaT",
    number=10,
    globals=globals()
))

# Create empty datetime64[ns] column by instantiating a pd.Series
print(timeit.timeit(
    "df['datetime_col_with_typing'] = pd.Series(dtype='datetime64[ns]')",
    number=10,
    globals=globals()
))

```

#### Output:

```
0.003220411000000034
4.237677962999999
0.017725253000000052
```

#### Problem description

This is a performance issue : the creation of an empty column of type datetime64[ns] is very slow when instantiating it with `pd.NaT`. 
I have tracked the problem down to the `should_cache` method in `pandas/core/tools/datetimes.py`, where more than 99% of the time is spent in the `set` function, to determine in the end whether the cache should be used.

If `df[col] = pd.NaT` is indeed a valid way to create a datetime64[ns] column, it should not try to use the cache at all.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 7d32926db8f7541c356066dcadabf854487738de
python           : 3.7.8.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
Version          : Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.2
numpy            : 1.19.5
pytz             : 2018.5
dateutil         : 2.7.3
pip              : 21.0.1
setuptools       : 49.6.0
Cython           : 0.29.21
pytest           : 5.3.0
hypothesis       : None
sphinx           : 3.4.3
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.2
html5lib         : None
pymysql          : 1.0.2
psycopg2         : 2.8.6 (dt dec pq3 ext lo64)
jinja2           : 2.10
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.3
numexpr          : None
odfpy            : None
openpyxl         : 3.0.6
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.0
sqlalchemy       : 1.3.22
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
numba            : None

</details>

**Comment by attack68** [comment]
I cannot replicate this on master.
Get..

```
0.0021253440000000845
0.017650047000000058
0.01662684999999997
```


commit           : 95c1a68c215edf2e98baeb49bc264872161205c8
python           : 3.8.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 17.7.0
Version          : Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_GB.UTF-8

pandas           : 1.3.0.dev0+786.g95c1a68c21
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.3
setuptools       : 50.3.0
Cython           : 0.29.21
pytest           : 6.1.0
hypothesis       : 5.36.1
sphinx           : 3.2.1
blosc            : 1.9.2
feather          : None
xlsxwriter       : 1.3.6
lxml.etree       : 4.5.2
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.18.1
pandas_datareader: None
bs4              : 4.9.2
bottleneck       : 1.3.2
fsspec           : None
fastparquet      : 0.4.1
gcsfs            : None
matplotlib       : 3.3.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : 1.0.1
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.51.2

**Comment by mzeitlin11** [comment]
Can't replicate either. Closable, or do you still see this issue @nicolaslegrand91 (on master, or 1.3rc, or 1.3 out soon)?

**Comment by nicolaslegrand91** [comment]
Just installed 1.3.1, I can't see the issue anymore, thanks!
