### ISSUE TITLE
BUG: read_csv() does not read all the lines in a tsv file

### ISSUE THREAD

**Issue by vincent6liu** [pandas-dev/pandas#39857]
**Code Sample, a copy-pastable example if possible**
`snps_df = pd.read_csv('cast_chr7_snps.txt', sep='\t', header=None)`

[cast_chr7_snps.txt](https://github.com/pandas-dev/pandas/files/5993376/cast_chr7_snps.txt)

**Problem description**
`pd.read_csv` doesn't read the entire file (30219 of the 30423 rows).
I double-checked and don't think there are empty lines in the file. Setting `skip_blank_lines=True` doesn't change the result.
I manually checked some of the lines missed, and they all seem consistent with other lines.

Output of `pd.show_versions()`
INSTALLED VERSIONS
------------------
commit           : 9d598a5e1eee26df95b3910e3f2934890d062caa
python           : 3.8.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.3.0
Version          : Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.1
numpy            : 1.19.1
pytz             : 2021.1
dateutil         : 2.8.1
pip              : None
setuptools       : 52.0.0.post20210125
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.17.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : None
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
numba            : None

**Comment by attack68** [comment]
import pandas as pd
import numpy as np

```
 with open('cast_chr7_snps.txt', 'r') as file:
     snapstr = file.read()
     lines = snapstr.split('\n')
 df = pd.DataFrame({'lines': lines})
 df['len'] = df[['lines']].applymap(lambda x: len(x))

print(np.histogram(df['len'].values, bins=[0,1,2,3,5,10,300]))
print(len(df))  # 30424

df = pd.read_csv('cast_chr7_snps.txt', sep='\t', header=None, skip_blank_lines=False, nrows=30423)
print(len(df)) # 30219
```

There must be something in the missing rows, but no bad-line errors are raised.

Hmmm...

**Comment by tdakic** [comment]
read_csv will read all lines if you add **quoting=csv.QUOTE_NONE**:

` snps_df = pd.read_csv('cast_chr7_snps.txt', sep='\t', header=None, `quoting=csv.QUOTE_NONE)

**Comment by phofl** [comment]
I don't think this is a bug. This comes down to the following:

```
data = """
a,b,c
d,e,"f
g,h,i"
m,n,o
"""

pd.read_csv(StringIO(data), header=None)
pd.read_csv(StringIO(data), header=None, quoting=csv.QUOTE_NONE)
```

Which reproduces the problem in the file. I think this behaves as the behavior of the csv quoting styles is documented

**Comment by phofl** [comment]
Closing. please ping to reopen if this does not solve your issue
