### ISSUE TITLE
DOC: fixup link for lookup example

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#39863]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.lookup.html?highlight=lookup#pandas.DataFrame.lookup

#### Documentation problem

It says

> For an example see lookup() in the user guide.

but the hyperlink doesn't send to the user guide

#### Suggested fix for documentation

link to https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#looking-up-values-by-index-column-labels instead

**Comment by morrme** [comment]
If it helps (until #39859 is decided), the affected files/lines are:

https://github.com/pandas-dev/pandas/blob/94e29822556259efa2e29bdaa37ffb4f6c470bf3/pandas/core/frame.py#L4069
https://github.com/pandas-dev/pandas/blob/master/doc/source/user_guide/indexing.rst#looking-up-values-by-indexcolumn-labels

**Comment by MarcoGorelli** [comment]
Thanks @morrme

Just to be clear, this issue can be done independently of #39859

**Comment by morrme** [comment]
> Thanks @morrme
> 
> Just to be clear, this issue can be done independently of #39859

Updated my comment for clarity. 🙂

**Comment by MarcoGorelli** [comment]
Thanks :)

> Since it can be a little challenging to find the relevant files (see #39859 

Though in this case, wouldn't the `[source]` button already give you the file location?

![image](https://user-images.githubusercontent.com/33491632/108252765-eb10c800-7150-11eb-81f6-f212be22b557.png)
