### ISSUE TITLE
Wrong date math

### ISSUE THREAD

**Issue by gordio** [pandas-dev/pandas#39866]
Explanation:
```
d = pd.Timestamp('2017-10-31T00:00:00+00:00')
d -= pd.DateOffset(months=1)
d += pd.DateOffset(months=1)
assert d == pd.Timestamp('2017-10-31T00:00:00+00:00'), f"Date '{d}' is not as expected"
```

**Comment by jbrockmendel** [comment]
If you want to always have the last day of the month, you want pd.offsets.MonthEnd(1).  pd.DateOffset(months=1) uses dateutil.relativedelta, which is behaving correctly here.

**Comment by MarcoGorelli** [comment]
closing as this doesn't seem like a bug, but please ping if I've misunderstood
