### ISSUE TITLE
BUG: Ignore_index on concat does not ignore index 

### ISSUE THREAD

**Issue by mvirag2000** [pandas-dev/pandas#39896]
I have this line of code which works fine in pandas 1.1.5 but not in 1.2.2:

`vintable = pd.concat([vintable, data], join='inner', ignore_index=True)`

I expect this to concatenate the rows, inner-join the columns, and then reindex - which it used to do in December.  But now I get this error: "Reindexing only valid with uniquely valued Index objects."  As I read the docs, it should not be looking at the index at all.  So, I am fine sticking with 1.1.5 but I think is a bug ... TIA

**Comment by attack68** [comment]
a reproducible code snippet is needed to debug.

related to #39882 ?

**Comment by MarcoGorelli** [comment]
Hi @mvirag2000 - closing for now, will reopen if you include a reproducible example
