### ISSUE TITLE
ENH: Multi-layered Vector Functions

### ISSUE THREAD

**Issue by itmmckernan** [pandas-dev/pandas#39914]
#### Add multi-layered vector support
When working on a large panadas dataframe, I tried to use the iloc method on the dataframe with a list of lists index query. I thought that the behavior of iloc with a 1d array would be extended to 2d arrays, and it would return a 2d array of the query results. This would allow for lists of lists to be operated on inside the dataframe.

#### Extending the behavior of iloc to multidimensional indexes

I think that the way that iloc handles 1d arrays should be extended to 2d and possibly even higher dimensions to allow for efficient loopless code to be written. For example, passing iloc a 2d array of indices should have it return 2d array of the results.

#### API breaking implications

This shouldn't break any existing code, or add any new arguments to iloc, just make the backend handle multidimensional arrays and return a multidimensional array as necessary.

#### Alternatives

A loop can just be made in python to achieve the same effect but will be significantly slower. While my dataset could probably be operated on with just python and some basic patience, the most ideal solution, as far as I can tell, would be this.

#### Example
This is what could be an implementation of this could look like.
```
indexArray = [[0, 3, 5, 7, 9], [1, 4, 6, 8]]
2d_result = df.iloc[indexArray]
```
2d_result would be an array with the shape of the indexArray populated by results from df.

**Comment by attack68** [comment]
For integer indexing numpy has some useful functions. Since there are a multitude of things you might be doing.
Is it possible to do what you want with 

``` 
arr = df.to_numpy()
# do numpy indexing
df2 = DataFrame(arr)
```
?

**Comment by itmmckernan** [comment]
I don't that NumPy supports this either, although I am far from sure. I don't think I did a great example of explaining what I am trying to do here so I'll do my best to provide an example below.

```
dataframeDict = {'name': ['flamingos', 'parrots', 'dove', 'finch'],
                 'species': ['bird', 'bird', 'bird', 'bird']
                 }
dataFrame = pd.DataFrame(data=dataframeDict)
```
Now, we query for indices 1 and 3
```
>>>dataFrame.iloc[[1, 3]]
      name species
1  parrots    bird
3    finch    bird
```
Same as above for 0 and 2
```
>>>dataFrame.iloc[[0, 2]]
        name species
0  flamingos    bird
2       dove    bird
```

But if we make both of these queries at once, it returns an error.
The desired response to both queries being passed at once would be the two above results being wrapped into an array-like object.
```
dataFrame.iloc[[[1, 3], [0, 2]]]
```

I tried to do this with the to_numpy function and NumPy indexing but it appears to treat the dataframe as a 2d array and uses the indices I pass to it as indices for the columns of the array. I could be missing something with the NumPy method though.

**Comment by attack68** [comment]
ok so with your example, what is the exact form you expect from `dataFrame.iloc[[[1, 3], [0, 2]]]`? Still not clear to me.

**Comment by itmmckernan** [comment]
It would be equvilant to ```
[dataFrame.iloc[[1, 3]], dataFrame.iloc[[0, 2]]]```

**Comment by phofl** [comment]
I am not sure if this is desirable for us? Indexing is pretty complicated already. @jbrockmendel thoughts here?

**Comment by jbrockmendel** [comment]
i dont see a need for this

it seems like just using `df.iloc[[1, 3, 0, 2]]` gets you most of the way towards what you want in the example

**Comment by rhshadrach** [comment]
> The desired response to both queries being passed at once would be the two above results being wrapped into an array-like object.

Like this?

```
queries = [[1, 3], [0, 2]]
result = [dataFrame.iloc[query] for query in queries]
```

**Comment by itmmckernan** [comment]
@rhshadrach is correct in that it can be solved with list comprehension for a 2 layer deep query, but as far as I know, this leaves performance on the table as well as not working for arrays with higher dimensions. While iloc for higher dimensions is probably not wanted by many, it should be the most performant way to solve problems like these. As shown [here](https://engineering.upside.com/a-beginners-guide-to-optimizing-pandas-code-for-speed-c09ef2c6a4d6), there appears to be a lot of performance to gain from pandas implementing this, although I'm not positive their results are directly representative of this problem.

**Comment by attack68** [comment]
I think that there is already enough confusion around .loc, .iloc and the various combinations of inputs (and with MultiIndex) and `KeyError` returns that avoiding adding more complexity is actually a benefit.

**Comment by jreback** [comment]
you can use .lookup here (though it's deprecated in favor of melt and selection)

**Comment by mroeschke** [comment]
Thanks for the suggestion, but from the discussion it appears that there's not much support from the team to support this functionality. Closing, but happy to reopen if there is revived interest
