### ISSUE TITLE
QST: The site ahead contains harmful programs

### ISSUE THREAD

**Issue by soerendip** [pandas-dev/pandas#39918]
I am getting "site contains harmful programs' error here:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.apply.html

> The site ahead contains harmful programs 
> Attackers on pandas.pydata.org might attempt to trick you into installing programs that harm your browsing experience (for example, by changing your homepage or showing extra ads on sites you visit). Learn more

**Comment by soerendip** [comment]
Using Chrome Version 88.0.4324.182 (Official Build) (64-bit) on Windows 10

**Comment by apeguero1** [comment]
I see the same here with chrome. No issues with Microsoft Edge Version 88.0.705.74.

**Comment by ndrezn** [comment]
Getting this error using Firefox.

**Comment by phofl** [comment]
Thx, duplicta eof #39862
