### ISSUE TITLE
ENH: Ability to use "normalize" function (df['col'].value_counts(normalize=True) when you do df.groupby(cols).size()

### ISSUE THREAD

**Issue by bbennett36** [pandas-dev/pandas#39938]
`groupby.size()` should have the ability to "normalize" the results and return them as a percentage.   
  
  
```
df['col'].value_counts(normalize=True) 
  
A = 0.25
B = 0.25  
C = 0.25  
D = 0.25
```  
  
To accomplish this result with a `groupby.size()` you have to do the following - 

```
df2 = df.groupby(['subset_product', 'subset_close']).size().reset_index(name='prod_count')
a = df2.groupby('subset_product')['prod_count'].transform('sum')
df2['prod_count'] = df2['prod_count'].div(a)
```  
  
Is there a way to add a feature to include this as a parameter in `.size()`

**Comment by rhshadrach** [comment]
Please include a full reproducible example.

`df.groupby(...).size() / df.shape[0]` gives you the normalized counts.

**Comment by MarcoGorelli** [comment]
Hi @bbennett36 - does `df.groupby(...).size() / df.shape[0]` work for you? If so, I think this can be closed, I don't think it's worth adding an extra parameter in `size` for this

**Comment by bbennett36** [comment]
@MarcoGorelli That gives the percentage of the entire dataframe. I was looking for a percentage within the group.

I'll try to get a reproducible example on here today.

**Comment by MarcoGorelli** [comment]
Hi @bbennett36 - closing for now to reduce the queue, will reopen if you post a reproducible example
