### ISSUE TITLE
ENH: `applymap` get kwargs?

### ISSUE THREAD

**Issue by attack68** [pandas-dev/pandas#39987]
`apply` has `kwargs` whilst `applymap` does not. Is there a specific reason for this?

it's straight forward to do 

```
apply(f, **kwarrgs)
```
or
```
g = partial(f **kwargs)
applymap(g)
```

its not documented how this can be achieved with `partial` which the more casual user might miss?

**Comment by alexprincel** [comment]
I may attempt a PR on this unless someone disagrees with the approach but it seems like the simplest solution would be to modify the `func` variable in `pandas.frame.applymap` to be the result of `functools.partial(func, **kwargs)`. Obviously, this requires adding **kwargs as an argument, modyfing the docs and adding tests.

I tested locally the aforementioned change and obtained this output from the following interactive session:
```
>>> df = pd.DataFrame({'a': [1, 2], 'b': [3, 4]})
>>> df.applymap(test, b=5)
   a  b
0  6  8
1  7  9
>>> df.applymap(test)
   a  b
0  3  5
1  4  6
```
