### ISSUE TITLE
ENH: change behavior in reading malformat file

### ISSUE THREAD

**Issue by smohr003** [pandas-dev/pandas#40038]
#### Is your feature request related to a problem?

Currently, for large CSV files, pandas parse a column with mixed data types with only a warning (DtypeWarning)
[https://github.com/pandas-dev/pandas/blob/v1.2.2/pandas/errors/__init__.py#L57-L112](url)
[https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/parsers.pyx](url)  

This behavior of keeping mix data type in a column is totally unexpected and a warning for it is not enough.  

#### Describe the solution you'd like
Just convert all the values of the column to one type and produce a warning. For example, if it is a mix of int and object, just convert all to object and then produce a warning. This way, there would be no unexpected behavior/error later in the manipulation of DataFrame. 

#### API breaking implications
API will not change. The behavior of API becomes more predictable.

**Comment by nmay231** [comment]
This is the current behavior. If a column has a mix of strings and ints, it will simply coerce it to an object type. As is mentioned in the [docstring](https://github.com/pandas-dev/pandas/blob/master/pandas/errors/__init__.py#L78-L80).

>     Despite the warning, the CSV file is read with mixed types in a single
>     column which will be an object type. See the examples below to better
>     understand this issue.

If you have a csv file where you get this warning, you can check the resultant dtype: `my_dataframe.dtypes`.

Hope that clarifies it :+1:

**Comment by smohr003** [comment]
Yes, it shows that the columns is of type "Object". However, the values at the row level are stored differntly. One challenging example is this: 
`df['a'].nuinuqe()`, the output would be `3` (i.e., '1', 1, 'X') while one would expect `2`, i.e., there would be only ('1' and 'X') in the column if everything is of "object" type. 
p.s. I have not run the example provided; i just came across this issue while working in another dataset; i think the example in docsting is not up to date.

**Comment by mroeschke** [comment]
This proposal would sound like an API change, and one that would break a lot of people's code since this has been the behavior for a while. The current behavior, as documented, is more forgiving IMO since it warns and assumes the most forgiving data type `object`. There is also a `dtype` keyword to perform the converting as well.

Thanks for the suggestion, but closing as this behavior is documented and unlikely to change.
