### ISSUE TITLE
BUG: Series.groupby.sum fails because result has _values attribute but not ndim attribute

### ISSUE THREAD

**Issue by venaturum** [pandas-dev/pandas#40045]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd

class TestClass:
    
    def __init__(self, num):
        self.num = num
        self._values = []
        
    def __add__(self, other):
        return TestClass(self.num + other.num)

s = pd.Series(
    [TestClass(1), TestClass(2), TestClass(3)],
    index=pd.Index([0,1,1], name="ind"),
)

s.sum()

s.groupby("ind").sum()
```

#### Problem description
s.sum() works but, for pandas >= 1.2.0, s.groupby("ind").sum() results in the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rclement\tempenv\lib\site-packages\pandas\core\groupby\groupby.py", line 1654, in sum
    npfunc=np.sum,
  File "C:\Users\rclement\tempenv\lib\site-packages\pandas\core\groupby\groupby.py", line 1044, in _agg_general
    result = self.aggregate(lambda x: npfunc(x, axis=self.axis))
  File "C:\Users\rclement\tempenv\lib\site-packages\pandas\core\groupby\generic.py", line 259, in aggregate
    return self._python_agg_general(func, *args, **kwargs)
  File "C:\Users\rclement\tempenv\lib\site-packages\pandas\core\groupby\groupby.py", line 1173, in _python_agg_general
    result, counts = self.grouper.agg_series(obj, f)
  File "C:\Users\rclement\tempenv\lib\site-packages\pandas\core\groupby\ops.py", line 706, in agg_series
    return self._aggregate_series_fast(obj, func)
  File "C:\Users\rclement\tempenv\lib\site-packages\pandas\core\groupby\ops.py", line 732, in _aggregate_series_fast
    result, counts = grouper.get_result()
  File "pandas\_libs\reduction.pyx", line 260, in pandas._libs.reduction.SeriesGrouper.get_result
  File "pandas\_libs\reduction.pyx", line 77, in pandas._libs.reduction._BaseGrouper._apply_to_group
  File "pandas\_libs\reduction.pyx", line 289, in pandas._libs.reduction.extract_result
AttributeError: 'list' object has no attribute 'ndim'

The error is due to an assumption in pandas\_libs\reduction.pyx in the following function, where if the result of the sum has an attribute _values, then it is also assumed to have an attribute ndim (and the __len__ method), which is not necessarily true for user defined objects like "TestClass"

```python
cpdef inline extract_result(object res, bint squeeze=True):
    """ extract the result object, it might be a 0-dim ndarray
        or a len-1 0-dim, or a scalar """
    if hasattr(res, "_values"):
        # Preserve EA
        res = res._values
        if squeeze and res.ndim == 1 and len(res) == 1:
            res = res[0]
    if hasattr(res, 'values') and is_array(res.values):
        res = res.values
    if is_array(res):
        if res.ndim == 0:
            res = res.item()
        elif squeeze and res.ndim == 1 and len(res) == 1:
            res = res[0]
    return res
```

#### Expected Output

```python
>>> s.sum()
<__main__.TestClass object at 0x000002359C7F2C08>

>>> s.groupby("ind").sum()
ind
0    <__main__.TestClass object at 0x000002359C7F2E48>
1    <__main__.TestClass object at 0x000002359C80B788>
dtype: object
```

We could check hasattr(res, "ndim") and hasattr(res, "__len__") is True, before trying to access those attributes, but it seems like the check for _values attribute is being used as a proxy for a more concrete assumption, eg is the result a pandas object?  Could the check for _values attribute be replaced with a more explicit check?

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 7d32926db8f7541c356066dcadabf854487738de
python           : 3.7.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.2.2
numpy            : 1.20.1
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by venaturum** [comment]
I realise this is probably a pretty niche problem.  I'm happy to write a solution (once direction is given) and tests.

**Comment by jreback** [comment]
-1 on doing anything 

you are contriving an artificial class that doesn't duck type with anything 

if you have a real world actual use case that hits this pls show it

**Comment by venaturum** [comment]
"TestClass" was a contrived class for the purposes of a minimal example, but the real world case is the Stairs class from [staircase](https://github.com/venaturum/staircase) which abstracts mathematical step functions.  This class has an attribute _values (for legacy reasons, it used to be extended from sortedcontainers.SortedDict which had this attribute).  Quite often this class is used in a Series, where groupbys and sums are performed.

At the moment we've had to replace operations of the form series.groupby(...).sum() with series.groupby(...).apply(np.sum) as a workaround with pandas 1.2.* but again, acknowledge I do not expect this to be a widespread problem.

The staircase package is maintained by myself, so if there is no appetite for change in pandas I will do away with Stairs._values in future versions to avoid the problem.

**Comment by jreback** [comment]
yeah u likely need to implement as an extension class to avoid this

**Comment by venaturum** [comment]
Cool, will look into that. Are you suggesting that after implementing as an extension class, a sum of a series of these objects would be done with something like series.sc.sum() where sc is an accessor? Or are you suggesting a chain of functions, different to that it in the traceback above, occurs as a result of being an extension class?

**Comment by jreback** [comment]
.sum() works for fully implemented extension arrays
.sc is just for additional things

**Comment by venaturum** [comment]
Hi @jreback 

I've tried testing the extension class approach:

```python
class TestClass():
    
    def __init__(self, num):
        self.num = num
        self._values = []
    
    def __add__(self, other):
        return TestClass(self.num + other.num)
  
@pd.api.extensions.register_extension_dtype    
class TestDtype(ExtensionDtype):
    
    type = TestClass
    name = "test"
    
    @classmethod
    def construct_from_string(cls, string):
        if string == cls.name:
            return cls()
        else:
            raise TypeError("Cannot construct a '{}' from "
                            "'{}'".format(cls, string))
            
    @classmethod
    def construct_array_type(cls):
        return TestArray
        
    
class TestArray(ExtensionArray):
    
    _dtype = TestDtype()
    ndim = 1
    
    def __init__(self, values):
        if isinstance(values, TestClass):
            values = [values]
        self.data = values
        
    @property
    def dtype(self):
        return self._dtype
    
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        if isinstance(idx, numbers.Integral):
            return self.data[idx]
        elif isinstance(idx, (Iterable, slice)):
            return TestArray(self.data[idx])
        else:
            raise TypeError("Index type not supported", idx)
    
    def __setitem__(self, key, value):
        if isinstance(value, TestClass) or _isna(value):
            if _isna(value):
                # internally only use None as missing value indicator
                # but accept others
                value = None
            if isinstance(key, (slice, Iterable)):
                value_array = np.empty(1, dtype=object)
                value_array[:] = [value]
                self.data[key] = value_array
            else:
                self.data[key] = value
            
    @property
    def ndim(self):
        return len(self.shape)
    
    def copy(self, *args, **kwargs):
        # still taking args/kwargs for compat with pandas 0.24
        return TestArray(self.data.copy())
    
    def take(self, indices, allow_fill=False, fill_value=None):
        from pandas.api.extensions import take
        result = take(self.data, indices, allow_fill=allow_fill, fill_value=fill_value)
        if allow_fill and fill_value is None:
            result[pd.isna(result)] = None
        return TestArray(result)  
    
    def isna(self):
        return np.array([g is None for g in self.data], dtype="bool")
    
    def __eq__(self):
        if not isinstance(other, TestArray):
            return NotImplemented
        mask = self.isna() | other.isna()
        result = self.data == other.data
        result[mask] = False
        return result
    
    @classmethod
    def _from_sequence(cls, scalars, dtype=None, copy=False):
        if isinstance(scalars, TestClass):
            scalars = [scalars]
        return TestArray(scalars)   
    
    @classmethod
    def _from_factorized(cls, values, original):
        return cls(values)
        
    @property
    def nbytes(self):
        return self._itemsize * len(self)
    
    @classmethod
    def _concat_same_type(cls, to_concat):
        return cls(np.concatenate([array.data for array in to_concat]))
    
    def _sum(self):
        return np.sum(self.data)
    
    def _reduce(self, name: str, *, skipna: bool = True, **kwargs):
        return {
            "sum":self._sum,
        }[name]()
   
```

but again with:

```python
s = pd.Series(
    [TestClass(1), TestClass(2), TestClass(3)],
    index=pd.Index([0,1,1], name="ind"),
    dtype="test",
)
```

s.sum() works and gives me back a TestClass object as expected, but s.groupby("ind").sum() crashes for the same reason as before (although goes through a different chain of functions to get there):

the result of the sum is a TestClass object, which has _values as an attribute, but not ndim.

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rclement\Documents\pandas\pandas\core\groupby\groupby.py", line 1667, in sum
    result = self._agg_general(
  File "C:\Users\rclement\Documents\pandas\pandas\core\groupby\groupby.py", line 1059, in _agg_general
    result = self.aggregate(lambda x: npfunc(x, axis=self.axis))
  File "C:\Users\rclement\Documents\pandas\pandas\core\groupby\generic.py", line 259, in aggregate
    return self._python_agg_general(func, *args, **kwargs)
  File "C:\Users\rclement\Documents\pandas\pandas\core\groupby\groupby.py", line 1189, in _python_agg_general
    result, counts = self.grouper.agg_series(obj, f)
  File "C:\Users\rclement\Documents\pandas\pandas\core\groupby\ops.py", line 694, in agg_series
    return self._aggregate_series_pure_python(obj, func)
  File "C:\Users\rclement\Documents\pandas\pandas\core\groupby\ops.py", line 746, in _aggregate_series_pure_python
    res = libreduction.extract_result(res)
  File "pandas\_libs\reduction.pyx", line 283, in pandas._libs.reduction.extract_result
    cpdef inline extract_result(object res, bint squeeze=True):
  File "pandas\_libs\reduction.pyx", line 290, in pandas._libs.reduction.extract_result
    if squeeze and res.ndim == 1 and len(res) == 1:
AttributeError: 'list' object has no attribute 'ndim'
```

I've already renamed the _values attribute in the staircase.Stairs class (upon which this contrived example is based) so that this problem will not occur, but I'm curious if I've missed something with your suggested extension class approach?

**Comment by venaturum** [comment]
```python
cpdef inline extract_result(object res, bint squeeze=True):
    """ extract the result object, it might be a 0-dim ndarray
        or a len-1 0-dim, or a scalar """
```

I guess the issue is the result is a scalar, but there is an implicit assumption that scalars won't have a _values attribute

**Comment by jreback** [comment]
you would have to study the existing extension types and make sure it's following the apis

**Comment by venaturum** [comment]
For anyone who comes across a similar issue it would seem this is a relevant piece of documentation :

> The ExtensionArray interface does not impose any rules on how this data is stored. However, currently, the backing data cannot be stored in attributes called .values or ._values to ensure full compatibility with pandas internals. But other names as .data, ._data, ._items, … can be freely used.


From https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.api.extensions.ExtensionArray.html#pandas.api.extensions.ExtensionArray

The only issue I see is that people may not be looking to implement ExtensionArrays and working on the basis that if __add__ is defined for the objects in a pandas Series then sum and groupby.sum should work straight out of the box via a reduce operation. They would not think to visit this documentation.
