### ISSUE TITLE
BUG: Empty dataframe created with Index, not RangeIndex

### ISSUE THREAD

**Issue by connesy** [pandas-dev/pandas#40077]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
>>> import pandas as pd
>>> df = pd.DataFrame(columns=['a', 'b'])
>>> print(df.index)
Index([], dtype='object')

>>> df2 = df.append(df, ignore_index=True)
>>> print(df2.index)
RangeIndex(start=0, stop=0, step=1)

>>> pd.testing.assert_frame_equal(df, df2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stefan/miniconda3/envs/pandas/lib/python3.9/site-packages/pandas/_testing.py", line 1657, in assert_frame_equal
    assert_index_equal(
  File "/home/stefan/miniconda3/envs/pandas/lib/python3.9/site-packages/pandas/_testing.py", line 773, in assert_index_equal
    _check_types(left, right, obj=obj)
  File "/home/stefan/miniconda3/envs/pandas/lib/python3.9/site-packages/pandas/_testing.py", line 740, in _check_types
    assert_class_equal(left, right, exact=exact, obj=obj)
  File "/home/stefan/miniconda3/envs/pandas/lib/python3.9/site-packages/pandas/_testing.py", line 868, in assert_class_equal
    raise_assert_detail(obj, msg, repr_class(left), repr_class(right))
  File "/home/stefan/miniconda3/envs/pandas/lib/python3.9/site-packages/pandas/_testing.py", line 1073, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.index are different

DataFrame.index classes are not equivalent
[left]:  Index([], dtype='object')
[right]: RangeIndex(start=0, stop=0, step=1)
```

#### Problem description

When creating an empty dataframe it is created with `Index`, and not with a `RangeIndex` as specified in the [docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html). This is a problem, e.g. in the example shown above, where I would not expect the index to change when appending the empty dataframe to itself. However, `pd.testing.assert_frame_equals` raises `AssertionError` since the indeces are not equivalent.

#### Expected Output
```python
>>> df = pd.DataFrame(columns=['a', 'b'])
>>> print(df.index)
RangeIndex(start=0, stop=0, step=1)
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 7d32926db8f7541c356066dcadabf854487738de
python           : 3.9.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-59-generic
Version          : #65-Ubuntu SMP Thu Dec 10 12:01:51 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.2
numpy            : 1.20.1
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 49.6.0.post20210108
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by alexprincel** [comment]
The following code in pandas.core.internals.construction seems to be the culprit. I do not think I have enough maturity with the Pandas API to understand the code-breaking potential of editing the following from Index to RangeIndex or to reorganize the code without the length check:

```
def extract_index(data) -> Index:
    """
    Try to infer an Index from the passed data, raise ValueError on failure.
    """
    index = None
    if len(data) == 0:
        index = Index([])
    elif len(data) > 0:
        raw_lengths = []
        indexes: List[Union[List[Hashable], Index]] = []

        have_raw_arrays = False
        have_series = False
        have_dicts = False

        for val in data:
            if isinstance(val, ABCSeries):
                have_series = True
                indexes.append(val.index)
            elif isinstance(val, dict):
                have_dicts = True
                indexes.append(list(val.keys()))
            elif is_list_like(val) and getattr(val, "ndim", 1) == 1:
                have_raw_arrays = True
                raw_lengths.append(len(val))

        if not indexes and not raw_lengths:
            raise ValueError("If using all scalar values, you must pass an index")

        if have_series:
            index = union_indexes(indexes)
        elif have_dicts:
            index = union_indexes(indexes, sort=False)

        if have_raw_arrays:
            lengths = list(set(raw_lengths))
            if len(lengths) > 1:
                raise ValueError("All arrays must be of the same length")

            if have_dicts:
                raise ValueError(
                    "Mixing dicts with non-Series may lead to ambiguous ordering."
                )

            if have_series:
                assert index is not None  # for mypy
                if lengths[0] != len(index):
                    msg = (
                        f"array length {lengths[0]} does not match index "
                        f"length {len(index)}"
                    )
                    raise ValueError(msg)
            else:
                index = ibase.default_index(lengths[0])

    return ensure_index(index)
```

**Comment by mzeitlin11** [comment]
Persists on current master, contributions welcome to fix this!
