### ISSUE TITLE
QST: Invalid representation of data 

### ISSUE THREAD

**Issue by AlexandreDecan** [pandas-dev/pandas#40081]
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

Hello,

I'm the maintainer of a Python library to store and manipulate (disjunctions of) intervals of arbitrary values (as long as they are comparable). It's called `portion` and it's available on PyPI and also on GitHub (https://github.com/AlexandreDecan/portion). 

This data type defines a `__repr__` method (e.g. the interval from 0 to 1 included is represented as "[0,1]"). When I use this data type in `pandas`, I got a representation that does not correct to what can be expected. Let me provide a very simple example:

```python
>>> import portion as P
>>> P.closed(0, 1)
[0,1]
>>> import pandas as pd
>>> df = pd.DataFrame([P.closed(0,1)])
>>> df
  | 0
-- | --
((([0,1])))
```

As you can see, the expected output has three extra "(" and three extra ")", this is:
EXPECTED OUTPUT= "[0,1]"
CURRENT_OUTPUT = "((([0,1])))"

The same occurs when I display the corresponding index:

```python
>>> df.loc[0]
0    ((([0,1])))
Name: 0, dtype: object
```

But not when I display the corresponding "cell": 
```python
>>> df.loc[0][0]
[0,1]
```

Actually, if I get the object from `df.loc[0][0]`, I got the correct instance and its expected behaviour. 

I looked at how `__repr__` is handled by `pandas` but couldn't find the reason why this occurs. 

For what is worth, here's the implementation of `__repr__` in `portion`(see https://github.com/AlexandreDecan/portion/blob/master/portion/interval.py#L584): 

```python
    def __repr__(self):
        intervals = []

        for interval in self:
            if interval.empty:
                intervals.append('()')
            elif interval.lower == interval.upper:
                intervals.append('[{}]'.format(repr(interval.lower)))
            else:
                intervals.append(
                    '{}{},{}{}'.format(
                        '[' if interval.left == Bound.CLOSED else '(',
                        repr(interval.lower),
                        repr(interval.upper),
                        ']' if interval.right == Bound.CLOSED else ')',
                    )
                )
        return ' | '.join(intervals)
```

In the above snippet, `self` is an `Interval` instance that can be iterated over. Each `interval in self` is an `Interval` instance as well (they correspond to all the atomic intervals you can have in a disjunctive one, e.g., "[0,1] | [3,4]" has two atomic intervals: [0,1] and [3,4]). Each `interval` has several attributes, but the ones of interest here are `left` and `right` (either `Bound.CLOSED` or `Bound.OPEN`, two constants from an enum based on Booleans), and `upper` and `lower` that respectively correspond to the upper bound of the interval and the lower bound of the interval (e.g., for [0,1], upper = 1, and lower = 0). 

FYI, I'm using pandas 1.2.2 but I already got this "issue" with a previous version (unfortunately, I do not remember which one). 

Thank you!

**Comment by alexprincel** [comment]
Here's what I found:
- pprint_thing (in io/formats/format.py) will get called for both DataFrame and Series objects, whereas this is not the case if directly accessing the object;
- pprint_thing checks for different types of objects to use an appropriate printing method. On line 224 it uses pandas.core.dtypes.inference.is_sequence and determines that your object is a sequence (essentially because it converts to iter() and has a length); therefore, your object is treated as a sequence;

Start of a loop:
- _pprint_seq is called and your object is enclosed between parentheses
- Create an iterator based on your object
- Call pprint_thing on next() of iterator and increase depth by 1
- As next() on your object itself will return an object that, when converted to an iterator will yield the same item instead of StopIteration, this goes infinitely until reaching display.pprint_nest_depth, which defaults to 3

After these three iterations,  _pprint_seq is not triggered because you are now == display.pprint_nest_depth. This is resolved by calling as_escaped_string instead.

I suspect the issue is with how you handle __iter__, not with pandas.

**Comment by AlexandreDecan** [comment]
Thanks for your answer, I'll have a look at the code you're referring to.

Is there any known workaround I can implement in my code to mitigate this issue?

**Comment by alexprincel** [comment]
You can use the yield from construct to make a generator out of your sequence. This means you would have to change your __iter__ to simply : `yield from self._intervals`

I have tested the above and it yields the slighly better but imperfect:

```
                        0
0  (CLOSED, 0, 1, CLOSED)
```

**Comment by alexprincel** [comment]
Actually, I found a simpler solution, albeit maybe a bit hacky. Simply add a __next__ handler in your Interval class and make it return None. This will activate an if clause ahead of the is_sequence call, which checks for the presence of __next__. If so, it returns str(your_object):

```
    def __next__(self):
        # Just to behave better with Pandas
        return None
```

See the code I am referencing in pandas

```
    if hasattr(thing, "__next__"):
        return str(thing)
    elif isinstance(thing, dict) and _nest_lvl < get_option(
        "display.pprint_nest_depth"
    ):
        result = _pprint_dict(
            thing, _nest_lvl, quote_strings=True, max_seq_items=max_seq_items
        )
    elif is_sequence(thing) and _nest_lvl < get_option("display.pprint_nest_depth"):
        result = _pprint_seq(
            thing,
            _nest_lvl,
            escape_chars=escape_chars,
            quote_strings=quote_strings,
            max_seq_items=max_seq_items,
        )
```

**Comment by AlexandreDecan** [comment]
Thanks a lot!
