### ISSUE TITLE
BUG: ewma with time should not update value when timedelta between two steps is 0

### ISSUE THREAD

**Issue by jasonzhang2s** [pandas-dev/pandas#40099]
- [yes ] I have checked that this issue has not already been reported.

- [ yes] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example
```
idx=pd.date_range('20000101','20201231')

idx2=[idx[0]]*5 + [idx[1]]*5

df=pd.DataFrame(data=range(10),index=idx2)

df.ewm(halflife=pd.Timedelta('1D'), times=df.index).mean()
```
```python
# Your code here

```

  | 0
-- | --
0.000000
0.500000
1.000000
1.500000
2.000000
2.857143
3.555556
4.181818
4.769231
5.333333

#### Problem description

Why is the value being updated when time hasn't elapsed yet?

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by mroeschke** [comment]
From the formula we're using (https://pandas.pydata.org/docs/user_guide/window.html#exponentially-weighted-window in the times section), when the timedelta is 0 the weights equal 1 and therefore the op acts like an expanding mean.

**Comment by mroeschke** [comment]
Going to close as I believe this is the expected behavior, but happy to reopen if I am missing something.
