### ISSUE TITLE
BUG: IO unit test creates file at home directory

### ISSUE THREAD

**Issue by chrispe** [pandas-dev/pandas#40091]
- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of pandas.
- [X] (optional) I have confirmed this bug exists on the master branch of pandas.
---

The unit test at `pandas/tests/io/test_common.py` produces a file using a hardcoded name as shown below:
```python
filename = path_type("~/sometest")
with icom.get_handle(filename, "w") as handles:
  assert os.path.isabs(handles.handle.name)
  assert os.path.expanduser(filename) == handles.handle.name
```

#### Problem description
A developer may encounter an empty file "sometest" appearing in their home directory (after running `pytest`). If the developer is unaware of that, then it may raise some wrong security concerns on their side. Also, in the extreme scenario that the developer has a file at the exact same path, then its content may be replaced.

#### Expected Output
I would expect the file produced by the unit test to be temporary and get deleted afterwards. Also, that the filename is generated rather than hardcoded.

**Comment by lithomas1** [comment]
@chrispe Thanks for the bug report. I can confirm this on master that a sometest file is created in the home directory(I'm testing this on MacOS). I think we should at least check for the existence of a file before overwriting and for sure clean up the file after we're done. cc @twoertwein

**Comment by twoertwein** [comment]
That test should use:

```py
import pandas._testing as tm

with tm.ensure_clean() as path:
    ....
```

**Comment by chrispe** [comment]
In this test case we want to ensure that the path is able to expand correctly (i.e. '~/' is converted to an absolute path to home directory) right? However, the `tm.ensure_clean` does not allow creating a temp file in a custom directory. Should we then try to expand its functionality or directly use the module of 'tempfile'?

**Comment by twoertwein** [comment]
you are right! If that is the only place where a file in "~"needs to be cleaned up, I wouldn't extend `tm.ensure_clean`.

**Comment by chrispe** [comment]
By a quick look at the rest of the tests, it seems like this is the only hardcoded case. If you agree, I can continue with a PR to use the `tempfile` module for the file creation.

**Comment by twoertwein** [comment]
> By a quick look at the rest of the tests, it seems like this is the only hardcoded case. If you agree, I can continue with a PR to use the `tempfile` module for the file creation.

Yes, please go ahead :)
