### ISSUE TITLE
API/BUG: partially-inferring datetimes

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#40111]
from `test_mixed_offsets_with_native_datetime_raises`

```
vals = [
    "nan",
    pd.Timestamp("1990-01-01"),
    "2015-03-14T16:15:14.123-08:00",
    "2019-03-04T21:56:32.620-07:00",
    None,
]
ser = pd.Series(vals)
```

As expected, this comes back as object-dtype, but it also does some casting:

```
>>> ser
0                                 NaT
1                 1990-01-01 00:00:00
2    2015-03-14 16:15:14.123000-08:00
3    2019-03-04 21:56:32.620000-07:00
4                                None
dtype: object
```

`ser[0]` is a _str_ "NaT" and `ser[[2, 3]]` are stdlib datetime objects.  ser[1] and ser[4] are unchanged.

This casting is done inside a call to `to_datetime`, but has the surprising effect of not being idempotent:

```
>>> pd.to_datetime(ser)
ValueError: Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True
```

I'd expect `ser` to be constructed without doing any casting.

**Comment by jbrockmendel** [comment]
This _may_ be fixed in 2.0 when the string-inference behavior in maybe_infer_to_datetimelike deprecation is enforced.

**Comment by jbrockmendel** [comment]
partially closed by #44296; the lack of idempotency still needs to be addressed

**Comment by jorisvandenbossche** [comment]
With latest main, I think none of the original objects have been converted:


```
In [38]: ser
Out[38]: 
0                              nan
1              1990-01-01 00:00:00
2    2015-03-14T16:15:14.123-08:00
3    2019-03-04T21:56:32.620-07:00
4                             None
dtype: object

In [39]: ser.values
Out[39]: 
array(['nan', Timestamp('1990-01-01 00:00:00'),
       '2015-03-14T16:15:14.123-08:00', '2019-03-04T21:56:32.620-07:00',
       None], dtype=object)

```

**Comment by jbrockmendel** [comment]
This looks correct to me now, closing.
