### ISSUE TITLE
CI: failing numpy_dev 3.8 build

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#40144]
https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=55190&view=logs&j=eab14f69-13b6-5db7-daeb-7b778629410b&t=ce687173-08c6-5301-838d-71b2dda24510

```
__________________ TestGroupby.test_groupby_apply_identity ____________________
[gw0] linux -- Python 3.8.8 /home/vsts/miniconda3/envs/pandas-dev/bin/python

>   raise TypeError("boolean value of NA is ambiguous")
E   TypeError: boolean value of NA is ambiguous

pandas/_libs/missing.pyx:436: TypeError

The above exception was the direct cause of the following exception:

self = <pandas.tests.extension.test_boolean.TestGroupby object at 0x7f9eb07e2bb0>
data_for_grouping = <BooleanArray>
[True, True, <NA>, <NA>, False, False, True]
Length: 7, dtype: boolean

    def test_groupby_apply_identity(self, data_for_grouping):
        df = pd.DataFrame({"A": [1, 1, 2, 2, 3, 3, 1], "B": data_for_grouping})
        result = df.groupby("A").B.apply(lambda x: x.array)
        expected = pd.Series(
            [
                df.B.iloc[[0, 1, 6]].array,
                df.B.iloc[[2, 3]].array,
                df.B.iloc[[4, 5]].array,
            ],
            index=pd.Index([1, 2, 3], name="A"),
            name="B",
        )
>       self.assert_series_equal(result, expected)

pandas/tests/extension/test_boolean.py:335: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
```

**Comment by jreback** [comment]
cc @pandas-dev/pandas-core

**Comment by simonjayhawkins** [comment]
changed milestone to 1.2.3 as also failing on 1.2.x branch. https://github.com/pandas-dev/pandas/runs/1998469459

**Comment by jreback** [comment]
cc @rhshadrach

**Comment by jorisvandenbossche** [comment]
@simonjayhawkins since this is only about numpy master (and they don't plan to release any time soon, they just had a release), I don't think this should be blocking 1.2.3 (still be useful for 1.2.x in general if there is a fix, of course)

**Comment by simonjayhawkins** [comment]
agree. see https://github.com/pandas-dev/pandas/pull/40143#issuecomment-787999262. will start release tomorrow regardless.

**Comment by jreback** [comment]
@jbrockmendel is this failure on numpy_dev build *different* that what you were discussing with @seberg ? (can't remember where that convo was).

can we xfail these temporarily to make CI green.

**Comment by jbrockmendel** [comment]
Its the same thing as #40158.  IIUC seberg is on top of it.

**Comment by seberg** [comment]
Allen made a PR here: https://github.com/numpy/numpy/pull/18530 that should be fine (there is another small potential thing, but I doubt you hit that).
