### ISSUE TITLE
BUG: MonthEnd(), April 31, 2020 is not a date 

### ISSUE THREAD

**Issue by rrabbitt** [pandas-dev/pandas#40151]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample

```python
import pandas as pd
from pandas.tseries.offsets import MonthEnd

pd.Timestamp('2020-05-01') + MonthEnd(0)
>>> Timestamp('2020-05-31 00:00:00')

```

#### Problem description

There are not 31 days in April... Or am I missing an April Fools joke?

I have tried this code above in multiple environments, however I keep getting April 31, 2020. 

There is no error, I just think this is a bug and wanted to report it.

#### Expected Output

>>> Timestamp('2020-05-30 00:00:00')

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.7.4.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.3.0
Version          : Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8
pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 53.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
</details>

**Comment by MarcoGorelli** [comment]
`2020-05-31` is the 31st of May, not April, and May indeed has 31 days

**Comment by rrabbitt** [comment]
omg thank you!
