### ISSUE TITLE
BUG: read_csv header=0 does NOT infer column headers if the separator is a ';', i.e. non-standard

### ISSUE THREAD

**Issue by williammollers** [pandas-dev/pandas#40201]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
dataframe = pd.read_csv('semicolon_separated_values.csv', sep=';', header = 'infer')

```

#### Problem description

I am trying to import a CSV into pandas using the pandas.read_csv method and every time I have a CSV with a semi-colon ';' as a separator, it does not read the column headers, even if I add header=0 or header='infer'.

#### Expected Outcome

First row of the data should be treated as the header row

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.7.9.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
Version          : Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.1.3
numpy            : 1.19.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.0.post20201006
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : 5.5.4
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : 0.10.1
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.18.1
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.8.3
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.1
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : 1.3.19
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.51.2

</details>

**Comment by timmygee** [comment]
Can confirm. Also happened to me. Workaround to set headers is to do:

```
dataframe.columns = dataframe.iloc[0]
dataframe = dataframe[1:]
```

Still, would be nice if header row could be picked up when using a non-standard separator!

**Comment by alexprincel** [comment]
Can you include a minimal sample CSV file? I may look into this later.

**Comment by attack68** [comment]
The following code works on master:

```
>>> csv = "col1;col2\n1;2\n3;4\n"
>>> pd.read_csv(StringIO(csv), header='infer', sep=';')
      col1    col2
0        1       2
1        3       4
```

Docs say this is equivalent to `header=0`.

**Comment by alexprincel** [comment]
I have the same result as @attack68 and also routinely use files with separators other than a comma at work (semi-colon, pipe and @ (don't ask)) and I have never had this issue. A specific reproducible example would be necessary here.

**Comment by williammollers** [comment]
hey Guys,

we made a very stupid mistake: In the first row of our CSV (data not made by us) there were about 25 semicolons ;, which caused the error. Will close now and sorry for the confusion.
