### ISSUE TITLE
DOC: fix grammar issues and incorrect link in "Getting Started" guide

### ISSUE THREAD

**Issue by madhuv2002** [pandas-dev/pandas#40215]
#### Location of the documentation
https://pandas.pydata.org/docs/getting_started/index.html

#### Documentation problem

As part of the HackIllinois Open Source Fellowship and having never used pandas before, I have been reading through the pandas documentation to learn more about it and noticed several issues in the Getting Started page of the docs.
- Small punctuation errors
- The "to user guide" link under "How to manipulate textual data?" leads to the time-series section of the guide
-  Under "How to combine data from multiple tables", the given explanation is hard to understand due to grammar issues

#### Suggested fix for documentation
- Under "What kind of data does pandas handle" add a comma after "clean"
- Under "How to calculate summary statistics" add a comma after "a sliding window of data"
- For the incorrect linking to time-series, have the user guide instead link to "Working with text data"
- Rephrase the synopsis under "How to combine data from multiple tables" to -> Multiple tables can be concatenated both column wise **and** row wise **as** database-like join/merge operations are provided to combine multiple tables of data.

**Comment by rlukevie** [comment]
take

**Comment by afeld** [comment]
Yay! Another contribution for #39349.
