### ISSUE TITLE
ENH: DataFrame.to_hdf() can't save to a subgroup

### ISSUE THREAD

**Issue by aleksejs-fomins** [pandas-dev/pandas#40249]
I am storing a lot of complex hierarchical data to HDF5 files. Thus, my HDF5 files have a hierarchical structure of datasets sitting inside groups sitting inside other groups.

Currently, the [to_hdf](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_hdf.html) function allows to input a path and a key. As far as I have understood, the key refers to the name of the group to be created at the lowest level of HDF5 file. However, I don't want to place it at the lowest level. I want it to be a subgroup of an already created group.

Here is an example functionality that I would expect to work

import pandas as pd

```
df = pd.DataFrame()
with h5py.File('test.h5') as f:
    f.create_group('foo')

df.to_hdf('test.h5', 'foo/bar')
```
Here, `foo` is an already existing group, and `bar` is the name of the pandas dataset. As you see, I would like `bar` to be a subgroup of `foo`. Currently, this crashes with the error

`ValueError: Unable to create group (name already exists)`

I would also be happy if somebody could recommend a hack. Currently, I am unable to find how to move groups around using h5py

EDIT: I realize that for this to work, the [read_hdf](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_hdf.html) function will also need to change. I haven't tested, but I suspect that it also can't handle hierarchical keys yet

**Comment by jreback** [comment]
try using pytables as h5py is not involved here at all

**Comment by aleksejs-fomins** [comment]
@jreback The question is about `pandas.DataFrame.to_hdf` function. Is this the wrong place to ask it, even though it is part of pandas?

**Comment by jreback** [comment]
the implementation of to_hdf writes the HDF5 format using pytables meta data

h5py will open the file but you can use pytables in an easier way to inspect things

this is heavily documented

**Comment by aleksejs-fomins** [comment]
I see. Thanks for your advice.
I have had a look at pytables cookbook and tutorials and did not find an answer to my question. Do you have further suggestions on how to proceed? Pytables does not natively support pandas, so would I have to jump hoops to convert my pandas dataframe to their format and back manually if I were to use their h5py overlay?

**Comment by jreback** [comment]
pls read the documentation you cannot use h5py at all with pandas as it writes an incompatible format

**Comment by jreback** [comment]
closing as this is a usage question

**Comment by jreback** [comment]
https://pandas.pydata.org/pandas-docs/version/1.2.3/user_guide/io.html#io-hdf5

it’s in the docs under hierarchical keys

**Comment by aleksejs-fomins** [comment]
Thanks for the link. I'm sorry. Everything actually works as intended. There was a bug in my code in the original question. Namely, I was not checking if the initial group was already present in the file. This was my bug
