### ISSUE TITLE
BUG: I am facing parse error but it was note resolved so can someone please give an idea to resolve this issue?

### ISSUE THREAD

**Issue by bhasker-1996** [pandas-dev/pandas#40309]
line1 : import pandas as pd
line2 : import numpy as np
line3 :
line4 : gd = pd.read_csv('Desktop/Data_Science/abcd_efgh.csv')

for the above code i was getting the error as follows 
---------------------------------------------------------------------------
ParserError                               Traceback (most recent call last)
<ipython-input-5-61cbc9c13f04> in <module>
      2 import numpy as np
      3 
----> 4 gd = pd.read_csv('Desktop/Data_Science/abcd_efgh.csv')
      5 gd

~\anaconda3\lib\site-packages\pandas\io\parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    674         )
    675 
--> 676         return _read(filepath_or_buffer, kwds)
    677 
    678     parser_f.__name__ = name

~\anaconda3\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
    452 
    453     try:
--> 454         data = parser.read(nrows)
    455     finally:
    456         parser.close()

~\anaconda3\lib\site-packages\pandas\io\parsers.py in read(self, nrows)
   1131     def read(self, nrows=None):
   1132         nrows = _validate_integer("nrows", nrows)
-> 1133         ret = self._engine.read(nrows)
   1134 
   1135         # May alter columns / col_dict

~\anaconda3\lib\site-packages\pandas\io\parsers.py in read(self, nrows)
   2035     def read(self, nrows=None):
   2036         try:
-> 2037             data = self._reader.read(nrows)
   2038         except StopIteration:
   2039             if self._first_chunk:

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader.read()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._read_low_memory()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._read_rows()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._tokenize_rows()

pandas\_libs\parsers.pyx in pandas._libs.parsers.raise_parser_error()

ParserError: Error tokenizing data. C error: Expected 3 fields in line 5, saw 66

**Comment by jbrockmendel** [comment]
Please post an example that we can copy/paste to reproduce (https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)

**Comment by MarcoGorelli** [comment]
closing, will reopen if you address the above
