### ISSUE TITLE
BUG: Inserting series into dataframe does ignore column names/keys

### ISSUE THREAD

**Issue by pandas2021** [pandas-dev/pandas#40316]
- [ ] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

I am initializing a dataframe with column names and was able to insert a pandas series which is dictionary-like.
In older versions (e.g. 1.1.4), pandas did sort the values of the series according to their keys into the columns of the dataframe.
However, in newer versions (1.2.2 at least, and also 1.2.3) it ignores the keys of the series and assigns the elements of the series in current order of the series keys (no matter their names).

This can lead to data mis-location. I would not have noticed this behaviour if the entries of the series did not have different shapes.

#### Code Sample, a copy-pastable example

```python
# Your code here
import pandas as pd

# init dataframe with column names
df = pd.DataFrame(columns=['a', 'b', 'c'], index=range(3))

# create series on the fly and put it into dataframe
s = pd.Series({'d': 2, 'a': 1, 'c': 3})
df.iloc[0] = s
df

```

#### Problem description

The output in version 1.2.3 looks like

```python
     a    b    c
0    2    1    3
1  NaN  NaN  NaN
2  NaN  NaN  NaN

```

#### Expected Output

The output in version 1.1.4 looks like

```python
     a    b    c
0    1   NaN   3
1  NaN  NaN  NaN
2  NaN  NaN  NaN

```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f2c8480af2f25efdbd803218b9d87980f416563e
python           : 3.9.2.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.17763
machine          : AMD64
processor        : Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en
LOCALE           : de_DE.cp1252

pandas           : 1.2.3
numpy            : 1.20.1
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 20.2.3
setuptools       : 54.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 3.5.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.21.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
numba            : None

</details>

**Comment by phofl** [comment]
Hi, thanks for your report. Iloc stopped aligning in 1.2. The previous behavior was wrong. You should use loc if you want to align

**Comment by pandas2021** [comment]
Perfect, thank you for the fast reply!
