### ISSUE TITLE
BUG: unexpected DataFrame output when LaTeX is used in column names

### ISSUE THREAD

**Issue by RastislavTuranyi** [pandas-dev/pandas#40318]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example
LaTeX and `int`:
```python
import pandas as pd

pd.DataFrame({'$a$': [1]})
```
LaTeX and `str:`
```python
import pandas as pd

pd.DataFrame({'$a$': ['1']})
```
LaTeX that includes spaces and  `float` or `int` or `str`:
```python
import pandas as pd

pd.DataFrame({'$a \: a$': [1.]})
```

#### Problem description

Any dataframe that uses a LaTeX in the column name and data of dtype `int `or `str `in the same column ends up taking the whole width of the jupyter cell. In DataFrames with several columns, all columns with no LaTeX or LaTeX and `float `dtype data have the expected width, while the problematic combination produces a very wide column that takes up the rest of the space.

![df with simple latex](https://user-images.githubusercontent.com/78977041/110456706-cb225380-80c1-11eb-9b2c-1c8c8112fb2f.jpg)

Furthemore, column names using LaTeX with spaces in them result in the same behaviour for `float`, `int `and `str `dtypes. Additionally, the spaces appear displayed as if a linebreak (\n) and a space were used. This behaviour persists with r- and f-strings.

![latex and spaces](https://user-images.githubusercontent.com/78977041/110456894-fb69f200-80c1-11eb-9ddb-ba89714f5010.png)

#### Expected Output

The outputted DataFrame should be identical whether LaTeX was used in the column name or not (other than the column name). The outputted DataFrame when using LaTeX  in column names and `str `or `int `dtype data in the column should be the same (apart from data dtype) as when `float `dtype is used.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f2c8480af2f25efdbd803218b9d87980f416563e
python           : 3.8.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252

pandas           : 1.2.3
numpy            : 1.20.1
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 49.6.0.post20210108
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.21.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : None
odfpy            : None
openpyxl         : 3.0.6
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.0
sqlalchemy       : 1.3.23
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
numba            : None

</details>

**Comment by attack68** [comment]
This is not a `pandas` issue. It is a the way Jupyter Notebook automatically uses MathJax to convert latex to HTML.
Pandas renders the cell as `$a$` and Mathjax does the rest (errorneously here).

You can work around it doing one of two things: 
  - using `$$a$$` instead.
  - using `pd.DataFrame({'$a$': [1]}).style.set_table_styles([{'selector': 'th', 'props': 'max-width: 50px;'}])`

**Comment by MarcoGorelli** [comment]
thanks @attack68
