### ISSUE TITLE
BUG: Inconsistent rounding up and rounding down in Timestamp.round (v1.2.3)

### ISSUE THREAD

**Issue by najeeb-kazmi** [pandas-dev/pandas#40315]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
print(pd.Timestamp('2021-03-03T23:20:30').round("1min"))
print(pd.Timestamp('2021-03-03T23:21:30').round("1min"))

print(pd.Timestamp('2021-03-03T23:22:30').round("5min"))
print(pd.Timestamp('2021-03-03T23:27:30').round("5min"))
```
Output:
```
2021-03-03 23:20:00
2021-03-03 23:22:00
2021-03-03 23:20:00
2021-03-03 23:30:00
```

#### Problem description
Rounding a `Timestamp` has inconsistent behavior w.r.t. rounding up vs rounding down when the `Timestamp` is exactly in the middle of the rounding resolution. In the above example, if the minute is even, it rounds down, and if the minute is odd, it rounds up.

#### Expected Output
Round up consistently
```
2021-03-03 23:21:00
2021-03-03 23:22:00
2021-03-03 23:25:00
2021-03-03 23:30:00
```

#### Output of ``pd.show_versions()``
```
INSTALLED VERSIONS
------------------
commit           : f2c8480af2f25efdbd803218b9d87980f416563e
python           : 3.7.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.0.0-1032-azure
Version          : #34-Ubuntu SMP Mon Feb 10 19:37:25 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8

pandas           : 1.2.3
numpy            : 1.20.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 50.3.0.post20201006
Cython           : None
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.18.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 0.8.3
fastparquet      : None
gcsfs            : None
matplotlib       : 3.2.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : 0.4.2
scipy            : 1.3.3
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 0.16.0
xlrd             : None
xlwt             : None
numba            : None
```
</details>

**Comment by jreback** [comment]
check on master as this has been refactored

**Comment by phofl** [comment]
Persists and is covered somehow.

```
pd.Timestamp("2018-01-01 12:00:00").round("1D")
pd.Timestamp("2019-01-01 12:00:00").round("1D")
```

results in 

```
2018-01-01 00:00:00
2019-01-02 00:00:00
```

in ``test_round_int64`` in pandas/tests/scalar/timestamp/test_unary_ops.py

**Comment by mroeschke** [comment]
I think this is the expected behavior as bankers rounding was implemented for rounding timestamp:

https://github.com/pandas-dev/pandas/blob/25488377fcd77fbd489602d0a905d856aa6cec53/pandas/_libs/tslibs/fields.pyx#L654-L685

**Comment by MarcoGorelli** [comment]
agreed, seems like expected behaviour, and is consistent with Python's rounding:

```python
>>> round(1.5)
2
>>> round(0.5)
0
```
