### ISSUE TITLE
DOC: Wrong examples 

### ISSUE THREAD

**Issue by JIHYO-JEON** [pandas-dev/pandas#40362]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.all.html

#### Documentation problem

This documentation is about 'pandas.Index.all' but it has examples of 'pandas.Index.any'.
The examples of 'pandas.Index.any' are also included in [its own page](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.any.html).

#### Suggested fix for documentation

Delete 'any()' examples on the documentation of 'all()', I think this is wrong place.

**Comment by dsaxton** [comment]
I think this was likely done on purpose since the two methods are closely related

**Comment by JIHYO-JEON** [comment]
Then it looks more reasonable to add 'all()' examples in 'any()' page, like argmin and argmax. They have both examples on both page.

**Comment by devashish-gaikwad** [comment]
I would like to add an example of 'all' to the  'any' doc page, can I get this issue assigned to me? Provided it still has value.

**Comment by dsaxton** [comment]
> I would like to add an example of 'all' to the 'any' doc page, can I get this issue assigned to me? Provided it still has value. @dsaxton

No problem, done. In the future feel free to simply open a PR (issue doesn't need to be assigned for someone to work on it; just be sure to reference it in your PR).
