### ISSUE TITLE
BUG: Can't import hvplot.pandas

### ISSUE THREAD

**Issue by stualden** [pandas-dev/pandas#40360]
#### Code Sample, a copy-pastable example

```python
# Your code here
import hvplot.pandas
```

#### Problem description
When I try the import, I get the following when running from a Jupyter Notebook on Chrome or Edge:

```Javascript error adding output!
Error: Cannot find module '@bokehjs/styles/buttons'
See your browser Javascript console for more details.
```

With Internet Explorer, I get the following (both messages):

```
Javascript error adding output!
SyntaxError: Expected ';'
See your browser Javascript console for more details.

Javascript error adding output!
SyntaxError: Syntax error
See your browser Javascript console for more details.
```

After that, any calls to hvplot produce no output. I have checked the Javascript console, but it did not illuminate the problem for me.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f2c8480af2f25efdbd803218b9d87980f416563e
python           : 3.8.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-65-generic
Version          : #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.3
numpy            : 1.19.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 52.0.0.post20210125
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.2
html5lib         : None
pymysql          : None
psycopg2         : 2.8.6 (dt dec pq3 ext lo64)
jinja2           : 2.11.3
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.1
sqlalchemy       : 1.3.23
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.52.0

</details>

Thank you!  If this is a bokeh issue rather than a pandas issue, please advise.

**Comment by dsaxton** [comment]
@stualden This looks like an issue for `hvplot`, have you tried posting there?

**Comment by stualden** [comment]
Of course, sorry about that - thank you.
