### ISSUE TITLE
ENH: `pivot_table` no aggregation validation

### ISSUE THREAD

**Issue by joshlk** [pandas-dev/pandas#40376]
#### Is your feature request related to a problem?

`pd.pivot_table` reshapes a table and aggregates values using a `aggfunc` (default `mean`) when rows has the same `index`+`columns` values. However, it is also common to use this function to purely reshape the table without aggregation - based on the assumption that no duplicates exist in the input table. However, if the upstream data does contain duplicates the output of `pd.pivot_table` "silently" changes to an aggregation instead of a pure reshape.

This issue is a parallel issue with `pd.merge` and `1:m` "silently" converting to a `m:m` join when input tables contain duplicates.

#### Describe the solution you'd like

`pd.merge` introduced a `validate` switch which checks the inputs do not have duplicates (depending on which setting is used). I propose that `pd.pivot_table` also introduce a `validate` switch to check that the input table doesn't have duplicate rows with the same `index`+`columns` values.

#### API breaking implications

None

#### Describe alternatives you've considered

`assert df.duplicated(keys).sum() == 0`

**Comment by rhshadrach** [comment]
Thanks for raising this issue. Can you provide a minimal example and show the current output.

**Comment by joshlk** [comment]
```
# Table with unique values. No aggregation performed by pivot
df = pd.DataFrame({'A': ['a', 'b', 'c'], 'B': ['X', 'Y', 'Y'], 'x': [1, 2, 3]})
pd.pivot_table(df, index='A', columns='B', values='x')
```

I propose adding in another argument `validate_no_agg` that ensures `index+columns` are unique.

```
# This works fine. Nothing changes
df = pd.DataFrame({'A': ['a', 'b', 'c'], 'B': ['X', 'Y', 'Y'], 'x': [1, 2, 3]})
pd.pivot_table(df, index='A', columns='B', values='x', validate_no_agg=True)
```

So that if the tables does contain duplicates an error is thrown

```
# New `df` with duplicate row: Error thrown
df = pd.DataFrame({'A': ['a', 'b', 'c', 'c'], 'B': ['X', 'Y', 'Y', 'Y'], 'x': [1, 2, 3, 3]})
pd.pivot_table(df, index='A', columns='B', values='x', validate_no_agg=True)
```

Error:

```
PivotError: Value keys are not unique - aggregation would occur
```

Similar to [merges validate functionality](https://pandas.pydata.org/pandas-docs/dev/user_guide/merging.html#checking-for-duplicate-keys).

**Comment by mroeschke** [comment]
`pd.pivot` seems to do this already and generally is the "non-aggregation" version of `pivot_table`

```
In [7]: pd.pivot(df, index='A', columns='B', values='x')
ValueError: Index contains duplicate entries, cannot reshape
```

**Comment by rhshadrach** [comment]
Thanks @mroeschke - agreed and that is also how `pivot` is documented. I think that makes the addition of a keyword here not necessary, closing this issue for now. If this doesn't satisfy your use-case @joshlk, let us know why not here and can reopen.
