### ISSUE TITLE
DOC: Backticks missing in pandas.DataFrame.query

### ISSUE THREAD

**Issue by bersbersbers** [pandas-dev/pandas#40375]
#### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.query.html

#### Documentation problem

![image](https://user-images.githubusercontent.com/12128514/110805248-31a1a000-8281-11eb-93bd-2281a2a43073.png)

#### Suggested fix for documentation

Backticks should be shown for the second `Area (cm^2)`.

**Comment by rhshadrach** [comment]
Thanks for the report @bersbersbers! PR to fix would be most welcome.

**Comment by sstiijn** [comment]
Hello, I am new to contributing to open source and I am trying to get started. I am following the contributing to pandas guide and this issue seems to be a good first issue to try and get started.

**Comment by sstiijn** [comment]
take

**Comment by sstiijn** [comment]
@rhshadrach I think the first `"Area (cm^2)` is also missing a double quote at the end. Should I add that as well?

**Comment by bersbersbers** [comment]
This is now online:
![image](https://user-images.githubusercontent.com/12128514/111022738-ec8e8280-83d4-11eb-9e50-a59869f853aa.png)

Shouldn't the second "Area (cm^2)" instead be marked as code with `double (in this case, triple) backticks, like here

https://github.com/pandas-dev/pandas/blob/400751335a0508f420b1f39bfcac5c38463f1c56/pandas/core/frame.py#L3806-L3807

and here

https://github.com/pandas-dev/pandas/blob/400751335a0508f420b1f39bfcac5c38463f1c56/pandas/core/frame.py#L3889-L3890

**Comment by sstiijn** [comment]
@bersbersbers Good point. So concretely you would suggest that the docstring needs to be updated to 

`(For example, a column named "Area (cm^2)" would be referenced as ```Area (cm^2)```).`
?

**Comment by bersbersbers** [comment]
I have no way to test it, but I think yes.

**Comment by sstiijn** [comment]
@bersbersbers  this would be the result

![image](https://user-images.githubusercontent.com/22836503/111035278-f686a480-8419-11eb-902c-383de1b94138.png)

**Comment by bersbersbers** [comment]
Makes a lot of sense to me!
