### ISSUE TITLE
DOC: Slightly broken grammar for `groupby.apply` with fix (good first doc issue?)

### ISSUE THREAD

**Issue by ianozsvald** [pandas-dev/pandas#40377]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.window.rolling.Rolling.apply.html

#### Documentation problem

For `engine` we have `None : Defaults to 'cython' or globally setting compute.use_numba`

#### Suggested fix for documentation

I'm very confident that this should read `None : Defaults to 'cython' or the global setting in compute.use_numba`.

Following the source code for `apply` to https://github.com/pandas-dev/pandas/blob/v1.2.3/pandas/core/window/rolling.py#L1307 and https://github.com/pandas-dev/pandas/blob/v1.2.3/pandas/core/util/numba_.py#L17 neither place sets the global variable, they just read from it.

**Comment by mroeschke** [comment]
Sure, your suggested edit is clearer. PRs welcome!

**Comment by Mayurji** [comment]
Shall I make the changes ? This would be my first contribution.

**Comment by Mayurji** [comment]
Shall I make the changes ? This would be my first contribution.

**Comment by MarcoGorelli** [comment]
sure go ahead
