### ISSUE TITLE
BUG: pip install pandas==1.2.3 triggers source build on aarch64 (manylinux2014 wheel missing from PyPi)

### ISSUE THREAD

**Issue by jakob-keller** [pandas-dev/pandas#40382]
Hello,

please accept my apologies for not adhering to the bug report template. I felt this issue doesn't quite fit it.

There is a huge increase in installation times on aarch64 Linux machines (e.g. AWS Graviton 2 based EC2 instances) running CPython 3.8 when comparing the current and previous releases of pandas:

- [``pip install pandas==1.2.2``](https://pypi.org/project/pandas/1.2.2/#files) -> completes fast, leverages the [manylinux2014 wheel](https://files.pythonhosted.org/packages/86/c2/dbb6f8b0e42da7c556fc07668b97d1614d9bb39a9dcab69eb91a78f04ba9/pandas-1.2.2-cp38-cp38-manylinux2014_aarch64.whl)
- [``pip install pandas==1.2.3``](https://pypi.org/project/pandas/1.2.3/#files) -> takes several times longer, performs source build

The cause appears to be **manylinux2014 wheels for pandas 1.2.3 missing from PyPi**. Could these please be added? Are there plans to include these for future releases?

My workaround is simply to pin the 1.2.2 release on aarch64 for the time being.

Thanks for all the effort!

**Comment by jreback** [comment]
cc @simonjayhawkins 

we don't officially support arch as we don't have great testing infrastructure 

but will give best efforts

**Comment by lithomas1** [comment]
Hi @jakob-keller, Can you please try again with pandas 1.3.0? We've recently re-added aarch64 wheels again.

**Comment by jakob-keller** [comment]
> Hi @jakob-keller, Can you please try again with pandas 1.3.0?

Unfortunately not at this point. Another issue is preventing me from moving to pandas 1.3.x. I will check again as soon as possible.

**Comment by jakob-keller** [comment]
> Hi @jakob-keller, Can you please try again with pandas 1.3.0? We've recently re-added aarch64 wheels again.

I can now finally confirm that aarch64 wheels are working. Thanks!
