### ISSUE TITLE
BUG: convert_dtypes throws a ValueError when called on an empty DataFrame

### ISSUE THREAD

**Issue by owenlamont** [pandas-dev/pandas#40393]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
import pandas as pd

pd.DataFrame().convert_dtypes()
```

#### Problem description

convert_dtypes throws a "ValueError: No objects to concatenate" exception when called on an empty DataFrame. I find that a problem because I have use cases of chaining up DataFrame transform calls fluently that may result in an empty DataFrame before the convert_dtypes call. I don't want want to break up the transform calls to check for an empty DataFrame or handle the ValueError.

#### Expected Output

I expect calling convert_dtypes on an empty DataFrame should return an empty DataFrame without error.

```python
import pandas as pd

df = pd.DataFrame().convert_dtypes()
assert df.empty
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f2c8480af2f25efdbd803218b9d87980f416563e
python           : 3.8.8.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.3.0
Version          : Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_AU.UTF-8
LOCALE           : en_AU.UTF-8

pandas           : 1.2.3
numpy            : 1.20.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 49.6.0.post20200917
Cython           : None
pytest           : 6.0.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.21.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.8.2
fastparquet      : 0.5.0
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : 3.0.0
pyxlsb           : None
s3fs             : 0.2.2
scipy            : 1.5.3
sqlalchemy       : 1.3.23
tables           : 3.6.1
tabulate         : 0.8.7
xarray           : 0.16.1
xlrd             : 2.0.1
xlwt             : None
numba            : 0.51.2

</details>

**Comment by jreback** [comment]
pls try on master

**Comment by jorisvandenbossche** [comment]
This raises on master as well.

@owenlamont thanks a lot for the clear bug report! 
We should add a check for empty dataframe before trying to concat the converted columns.

**Comment by owenlamont** [comment]
You're welcome, I'd actually be keen to try making a PR for this if no one has taken it. I'd like to be able to say I was a Pandas contributor (I haven't worked with the code base yet).

Any tips on which file/s I'd need to touch for the fix would be appreciated otherwise I'll investigate for myself.

**Comment by jorisvandenbossche** [comment]
@owenlamont a PR would be very welcome! I am happy to help you getting started. 

It is `pd.concat` that is (correctly) raising an error if there are no objects to concat. And then from the full strack trace, you can find out where the concat call comes from:

```
In [5]: import pandas as pd
   ...: 
   ...: df = pd.DataFrame().convert_dtypes()
   ...: assert df.empty
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-3a9d571433f7> in <module>
      1 import pandas as pd
      2 
----> 3 df = pd.DataFrame().convert_dtypes()
      4 assert df.empty

~/scipy/pandas/pandas/core/generic.py in convert_dtypes(self, infer_objects, convert_string, convert_integer, convert_boolean, convert_floating)
   6323                 for col_name, col in self.items()
   6324             ]
-> 6325             return concat(results, axis=1, copy=False)
   6326 
   6327     # ----------------------------------------------------------------------

~/scipy/pandas/pandas/core/reshape/concat.py in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    302         verify_integrity=verify_integrity,
    303         copy=copy,
--> 304         sort=sort,
    305     )
    306 

~/scipy/pandas/pandas/core/reshape/concat.py in __init__(self, objs, axis, join, keys, levels, names, ignore_index, verify_integrity, copy, sort)
    349 
    350         if len(objs) == 0:
--> 351             raise ValueError("No objects to concatenate")
    352 
    353         if keys is None:

ValueError: No objects to concatenate
```

So the actual concat call comes from `pandas/pandas/core/generic.py` in the `convert_dtypes()` method definition. In there, we can check if the `results` is empty, in which case we can return an empty DataFrame instead of calling `concat`.

**Comment by owenlamont** [comment]
Thanks @jorisvandenbossche - I think you practically solved this yourself. I've tried to follow all the requirements in the contributing documentation but have probably missed something. I wasn't sure where best to document the bug... in the 1.3.0 notes? Wasn't sure what section to list it under... 

I really appreciate your help walking me through the first contribution anyway - I'll await the PR comments and see how I go.
