### ISSUE TITLE
DOC: pandas.Series.str.replace has pandas.DataFrame.str.replace examples

### ISSUE THREAD

**Issue by dgokeeffe** [pandas-dev/pandas#40459]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.replace.html

#### Documentation problem

The documentation has DataFrame examples and not those related to Series

#### Suggested fix for documentation

Give examples related to Series.

**Comment by mzeitlin11** [comment]
Hi @dgokeeffe, thanks for the report! I don't see the issue you describe when looking at the docs you linked - they appear to be all related to Series. Could you please give more information about the specific issue?

**Comment by MarcoGorelli** [comment]
> Hi @dgokeeffe, thanks for the report! I don't see the issue you describe when looking at the docs you linked - they appear to be all related to Series. Could you please give more information about the specific issue?

agreed - closing for now, will reopen if you address the above
