### ISSUE TITLE
BUG: run_callable is deprecated in sqlalchemy 1.4 

### ISSUE THREAD

**Issue by jrbourbeau** [pandas-dev/pandas#40467]
#### Code Sample, a copy-pastable example

I've not yet been able to isolate the code path where `run_callable` is used

https://github.com/pandas-dev/pandas/blob/ac3e3f71129bc9ea9ed0a27f3adcd89e367fa9af/pandas/io/sql.py#L1615-L1618

However, it looks like several tests, for example `pandas/tests/io/test_sql.py::TestSQLApi.test_timedelta`, will trigger this warning. For instance [here's a recent CI build](https://github.com/pandas-dev/pandas/runs/2122982478#step:7:78) where a deprecation warning is being raised and actually causes the test to fail. 

#### Problem description

[`run_callable` is deprecated in sqlalchemy 1.4](https://docs.sqlalchemy.org/en/14/core/connections.html#sqlalchemy.engine.Connection.run_callable) -- `Connection.run_callable()` should be used instead 

#### Output of ``pd.show_versions()``

<details>

```
INSTALLED VERSIONS
------------------
commit           : f2c8480af2f25efdbd803218b9d87980f416563e
python           : 3.8.8.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.3.0
Version          : Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.3
numpy            : 1.20.1
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 49.6.0.post20210108
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.21.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.4.0
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
```

</details>

**Comment by fangchenli** [comment]
xref #40460

**Comment by jorisvandenbossche** [comment]
This might already be fixed (mostly/fully?) by https://github.com/pandas-dev/pandas/pull/40471 ?

**Comment by jrbourbeau** [comment]
Yep, I just tried out the latest `pandas` nightly release and don't see any sqlalchemy deprecations. Thanks for the heads up @jorisvandenbossche!
