### ISSUE TITLE
QST: No common columns to perform merge on

### ISSUE THREAD

**Issue by TWidmer46** [pandas-dev/pandas#40466]
```
frequency = 'monthly'
start = '1969-12-31'
end = '2020-12-31'
data = quandl.get(["ISM/MAN_PMI"], trim_start=start, trim_end=end)
data.head()
```
ISM/MAN_PMI - PMI Date
1970-01-01 48.7 1970-02-01 47.4 1970-03-01 46.9 1970-04-01 45.0 1970-05-01 47.2

```
df_log = numpy.log(df / df.shift(1))
df_log.head()
```
Adjusted Close Date
1969-12-31 NaN 1970-01-30 -0.079554 1970-02-27 0.051352 1970-03-31 0.001451 1970-04-30 -0.094842

`pd.merge(df, data)`
Error: MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

How chan I merge the two tables and harmonize them to:

1969-12 
1970-1
 1970-2 
1970-3 
..
 ..

**Comment by dsaxton** [comment]
Can you try to create a copy / pasteable example following this guide: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by TWidmer46** [comment]
```
import numpy as np 
import pandas as pd
import quandl
from pylab import mpl, plt
plt.style.use('seaborn')
%matplotlib inline
import pandas_datareader.data as web
import datetime
```
# import S&P 500 Prices from Excel / Sorted by Date/Price and % Change
```
names= ['Date','Adjusted Close', '% Change']
df = pd.read_excel('SP500 Prices.xlsx', names=['Date','Adjusted Close','% Change'])

df.head()
df = pd.read_excel('SP500 Prices.xlsx', names=names, index_col='Date')
df.head()
df = (df.sort_values(by=['Date']))
df
```
`# Compute Log returns from Price Series of S&P 500
df_log = numpy.log(df / df.shift(1))
df_log.head()`

	Adjusted Close
Date	
1969-12-31	NaN
1970-01-30	-0.079554
1970-02-27	0.051352
1970-03-31	0.001451
1970-04-30	-0.094842

`# import ISM PMI from Quandl
frequency = 'monthly'
start = '1969-12-31'
end = '2020-12-31'
data = quandl.get(["ISM/MAN_PMI"], trim_start=start, trim_end=end)
data.head()
`
	ISM/MAN_PMI - PMI
Date	
1970-01-01	48.7
1970-02-01	47.4
1970-03-01	46.9
1970-04-01	45.0
1970-05-01	47.2

`pd.merge(df, data)`

---------------------------------------------------------------------------
MergeError                                Traceback (most recent call last)
<ipython-input-7-5ed2a846810c> in <module>
----> 1 pd.merge(df, data)

~\anaconda3\lib\site-packages\pandas\core\reshape\merge.py in merge(left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
     72     validate=None,
     73 ) -> "DataFrame":
---> 74     op = _MergeOperation(
     75         left,
     76         right,

~\anaconda3\lib\site-packages\pandas\core\reshape\merge.py in __init__(self, left, right, how, on, left_on, right_on, axis, left_index, right_index, sort, suffixes, copy, indicator, validate)
    643             warnings.warn(msg, UserWarning)
    644 
--> 645         self._validate_specification()
    646 
    647         # note this function has side effects

~\anaconda3\lib\site-packages\pandas\core\reshape\merge.py in _validate_specification(self)
   1212                 common_cols = self.left.columns.intersection(self.right.columns)
   1213                 if len(common_cols) == 0:
-> 1214                     raise MergeError(
   1215                         "No common columns to perform merge on. "
   1216                         f"Merge options: left_on={self.left_on}, "

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False


I would like to bring them together in one table with:
1969-12
1970-1
1970-2
1970-3

...without the days.

Many thanks

**Comment by ParfaitG** [comment]
Your code is somewhat hard to read. Can you edit above and ensure each command is on its own line and can you comment `#` inside code block for any command output? Be sure to open code block with lang type:  ```python.

But I would guess `Date` in `quandl.get` output is an index (not column) or is actually named `PMI Date`, Please post result of `df.columns` and `data.columns`.

**Comment by phofl** [comment]
Could you provide something reproducible? See the link above.

**Comment by MarcoGorelli** [comment]
closing for now, will reopen if you address the above
