### ISSUE TITLE
read_excel() cannot read excel files properly with openpyxl

### ISSUE THREAD

**Issue by oakca** [pandas-dev/pandas#40469]
`pandas 1.2.3, openpyxl 3.0.7`

I read an excel file with pandas via openpyxl package. It converts the number in the `'ATC'` column to a weird bitwise string. Previously I was using `xlrd(1.2.0)` instead of `openpyxl` and it was working fine:

```
# with openpyxl 3.0.7
df = pd.read_excel('excel_file.xlsx')

>>>df['ATC']
0    _x0033_40.00
Name: ATC, dtype: object

>>>df['ATC'][0]
'_x0033_40.00'
```

```
# with xlrd 1.2.0
df = pd.read_excel('excel_file.xlsx')

>>>df['ATC']
0    340.0
Name: ATC, dtype: float64

>>>df['ATC'][0]
340.0
```

Here is the excel file if you like to check:
[excel_file.xlsx](https://github.com/pandas-dev/pandas/files/6151138/excel_file.xlsx)

Any work arounds? or I should keep using `xlrd`?

**Comment by mzeitlin11** [comment]
Thanks for the report @oakca. Looks like an `openpyxl` issue, just doing
```
from openpyxl import load_workbook
wb = load_workbook(filename="excel_file.xlsx")
print(list(wb["Sheet1"].values))
```
gives the strange results you were seeing - I'd recommend reporting this to them. A workaround would just be to use `xlrd` (can specify with the `engine` argument).

**Comment by asishm** [comment]
issue already exists with openpyxl - https://foss.heptapod.net/openpyxl/openpyxl/-/issues/1410

**Comment by mroeschke** [comment]
Closing as it appears that this is a openpyxl issue
