### ISSUE TITLE
BUG: Unusual behaviour in to_parquet re-load file

### ISSUE THREAD

**Issue by DSivaji** [pandas-dev/pandas#40464]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
 import pandas as pd
print(pd.__version__)

df = pd.DataFrame({'col1': [1,2,3,4,5], 'col2': ['s','p','d','q','r']})
# check data types
print(df.dtypes)  # <-- col1 dtype: int64

# convert col1 data type from int64 to object
df = df.astype({'col1': 'object'})
print(df.dtypes) # <-- col1 dtype: object

# write it to a parquet file
df.to_parquet('./test.parquet', compression='gzip')
re-load the dataset
df1 = pd.read_parquet('./test.parquet')
print(df1.dtypes) # <-- col1 dtype: int64 

```

#### Problem description

In the above code, col1 in df is converted to object before writing it to parquet file. Surprisingly, it is converted to integer after re-load. Is that an expected behaviour? I think it should preserve the data types of each column.

I have seen same behaviour for float values as well.

#### Expected Output
col1     object
col2    object
dtype: object

#### Output of ``pd.show_versions()``

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

INSTALLED VERSIONS
------------------
commit           : f2c8480af2f25efdbd803218b9d87980f416563e
python           : 3.7.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.3.0
Version          : Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.2.3
numpy            : 1.20.1
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 49.6.0.post20210108
Cython           : 0.29.22
pytest           : 6.2.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.21.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 3.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.6.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.52.0

**Comment by jorisvandenbossche** [comment]
I think this is to be expected, yes. The Parquet file format has no notion of an "object" data type like general Python objects. So when writing a column with object dtype, pyarrow will try to infer the data type to be able to write such a column (if it cannot infer the data type, it will actually raise an error), and in your case infer it to be int64. So the data is written as ints, and thus you also read it back as integers.

In theory, since we store the original dtype in pandas-specific metadata in the parquet file, we *could* cast the integers back to object dtype. But I am not sure that's very useful behaviour.

**Comment by DSivaji** [comment]
@jorisvandenbossche , Thanks for answering. It is actually a useful behaviour. I think, no one like to check data types when it reads aback.
