### ISSUE TITLE
BUG:read_excel no default style openpyx1

### ISSUE THREAD

**Issue by Starman1984** [pandas-dev/pandas#40483]
i receive an excel attachment via outlook, after saving the file and running the python script the following warning is returned.
"UserWarning: Workbook contains no default style, apply openpyxl's default" if the warning is ignored then read_excel  report 2 header records when there are 7 header records.

if I open the file via Excel and save the file with no changes, some dialog is shown but it is display so quickly I am unable to determine what excel is doing.  

when I re-run the python script no exceptions occur and everything works as expected.

I have upgraded pandas from 1.2.1 to 1.2.3
i have upgraded openpyxl  from 3.0.6 to 3.0.7
issue remains

ry:
    df = pd.read_excel(Filename, header = 7) 
    print('no issues reading excel file')
except Exception as e:
    print('Excel read error: ', e.args[0])

**Comment by rhshadrach** [comment]
I'd guess that the excel file itself is invalid and that resaving fixed issues in the file. Can you share the file here?

**Comment by Starman1984** [comment]
I happen inform my supervisor about this issue approx 3 three weeks prior to my bug report and it appears the originator has fixed this issue that caused the wrong header count to be returned, the warning issue still occurs but that is not a show stopper, I am in the process of checking for other sources i.e. older excel files, I will close this ticket/item as resolved and reissue if I find an older excel file, thanks for your reply.
