### ISSUE TITLE
DOC: Outdated Python version in contributing docs

### ISSUE THREAD

**Issue by hasan-yaman** [pandas-dev/pandas#40485]
#### Location of the documentation
[URL of the documentation](https://pandas.pydata.org/docs/development/contributing.html#creating-a-python-environment-pip)

**Note**: You can check the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/).
(Problem exist in the latest version: [here](https://pandas.pydata.org/docs/dev/development/contributing.html?highlight=contributing#creating-a-python-environment-pip))
#### Documentation problem

In the documents, it says  `at least Python 3.6.1 installed` to create Python virtual environment to contribute Pandas. However, to install some development requirements (such as NumPy) Python version must be >=3.7. See [here](https://pypi.org/project/numpy/) for NumPy minimum requirement.

#### Suggested fix for documentation
We should update the relevant document so contributors can install an appropriate virtual environment for contribution.
Suggested edit:
 `You’ll need to have at least Python 3.7 installed on your system.`

**Comment by hasan-yaman** [comment]
I can take the issue if the proposed solution is fine.

**Comment by hasan-yaman** [comment]
take

**Comment by rhshadrach** [comment]
Thanks for the report @hasan-yaman! PR to fix is most certainly welcome. I would consider leaving the python requirement vague (e.g. something like "you need to have at least the minimum python version that pandas supports") along with a link to the minimum version page. That way we don't have to routinely update the number.
