### ISSUE TITLE
TST: rewrite test_expressions.py to use pytest idioms

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#40497]
The [`test_expressions.py` test file](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/test_expressions.py) could be updated to use some more pytest features (eg using fixtures for the test data, using fixture for the setup/teardown to set `_MIN_ELEMENTS`)

**Comment by jandirdlctm** [comment]
Can I take this?
