### ISSUE TITLE
QST:keyerror message for a dataframe.head().to_dict()

### ISSUE THREAD

**Issue by wenouyang** [pandas-dev/pandas#40504]
- [ ] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

I have a dataframe `season_statistics_T1`, its related information is given as follows. Each operation looks normal except `season_statistics_T1.head().to_dict()`, which gives the **keyerror: 'Season' message**. I am not sure why. At the same time, `season_statistics_T1.head().to_dict('records')` works fine.
---

![image](https://user-images.githubusercontent.com/5430158/111680272-0cb4ac00-87f0-11eb-93a5-e41d685bcfe9.png)

![image](https://user-images.githubusercontent.com/5430158/111680311-163e1400-87f0-11eb-89bf-aa4367c8812b.png)

![image](https://user-images.githubusercontent.com/5430158/111680391-2a821100-87f0-11eb-96af-cec9dd0cff97.png)

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

**Comment by mzeitlin11** [comment]
Hi @wenouyang, thanks for the report! This error does not occur for me running with a simple test dataframe, can you provide a copy-pastable minimal example along the lines of (https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to help us reproduce? Also, does this error occur using the latest version of pandas? (1.2.3)

**Comment by wenouyang** [comment]
> Hi @wenouyang, thanks for the report! This error does not occur for me running with a simple test dataframe, can you provide a copy-pastable minimal example along the lines of (https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to help us reproduce? Also, does this error occur using the latest version of pandas? (1.2.3)

The pandas version is 1.1.5.  I was trying to reproduce the error, but when I re-run the code, the error just disappered. So I choose to close this issue. Thanks.
