### ISSUE TITLE
TYP use typed version of namedtuple

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#40531]
Instead of
```python
OutputKey = collections.namedtuple("OutputKey", ["label", "position"])
```

we can do
```python
from typing import NamedTuple

class OutputKey(NamedTuple)
    label
    position
```

The advantage is that like this we can add type hints to the various elements, such as
```python
from typing import NamedTuple

class OutputKey(NamedTuple)
    label: Hashable
    position: int
```

-----

See https://docs.python.org/3/library/typing.html#typing.NamedTuple for reference

**Comment by jreback** [comment]
better to use a dataclass

**Comment by MarcoGorelli** [comment]
Is that always true? Immutability is a nice property, I'd have thought we wouldn't want to lose that

**Comment by attack68** [comment]
Im also waiting for pandas to adopt `TypedDict`, for similar reasons. Similar to a data class but also with user input args where a dict is expected and a dataclass wouldn't work becuase the `user` input cant be a data class.

**Comment by MarcoGorelli** [comment]
> Is that always true? Immutability is a nice property, I'd have thought we wouldn't want to lose that

at the time of writing, I wasn't aware that dataclasses would use `frozen=True`, so that'd do

**Comment by franslarsson** [comment]
take

**Comment by MarcoGorelli** [comment]
> take

Hi @franslarsson - still working on this?

**Comment by franslarsson** [comment]
> > take
> 
> 
> 
> Hi @franslarsson - still working on this?

Hi @MarcoGorelli 
Sorry for the delay, I'll open a PR for it tomorrow, Wednesday.
