### ISSUE TITLE
ENH: Non-nullable extension types

### ISSUE THREAD

**Issue by gsakkis** [pandas-dev/pandas#40554]
As far as I can tell, all custom extension types are nullable. It would be useful to provide a way to create non-nullable extensions. One way to support this could be by setting the `na_value` attribute to `NotImplemented`. Thoughts?

**Comment by dsaxton** [comment]
Sounds like you want something like a database constraint but for DataFrames? That's an interesting idea, although I suspect this might be easiest to accomplish in end-user code by simply asserting that a given column contains no null values, rather than creating whole new data types.

**Comment by gsakkis** [comment]
IMO nullability is part of the type definition, it's not some extra constraint to be tested by the end-user code. Checking the constraint in the extension code itself (e.g. in `__init__` and/or `_from_sequence`) would be an improvement but even that is not sufficient for my use case. Ideally nullability should be an inspectable property of the type, discoverable by a new `pd.api.types.is_nullable_dtype(arr_or_dtype)` function.

**Comment by jbrockmendel** [comment]
xref #40574

**Comment by jbrockmendel** [comment]
A 3rd party EA could just raise if any NA-like is passed to the relevant constructor or `__setitem__`.  I guess we could document this?  Otherwise not clear that this is actionable.

**Comment by mroeschke** [comment]
Looks like there's not much support for this feature from the core team so closing
