### ISSUE TITLE
DOC: inconsistency in doc argument types

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#40560]
This is not exactly right, but we have an inconsitency in the argument specifications of using 'array_like' vs 'array-like', in argument types we should settle on one (prob 'array-like')

```
(pandas-dev) ~/pandas$ grep -r array-like --include '*.py' pandas|wc
     317    2259   24072
(pandas-dev) ~/pandas$ grep -r array_like --include '*.py' pandas|wc
     104     498    7414
```

Similar to this
```
pandas/plotting/_core.py:    yerr : DataFrame, Series, array-like, dict and str
```

**Comment by jreback** [comment]
cc @MarcoGorelli @WillAyd not sure if this is the doc-string validation and/or precommit checks.

**Comment by WillAyd** [comment]
Not aware of any validation currently - I'd agree that array-like is better

**Comment by MarcoGorelli** [comment]
agreed on array-like - will look into this

**Comment by kemcbride** [comment]
Hi, I'm a noob hunting for easy first issue and this seems like a prime target. Hopefully I can knock this one out pretty quick. PR coming soon!
