### ISSUE TITLE
BUG: Pandas 1.2 the clip method does not support Float64Dtype with pd.NA

### ISSUE THREAD

**Issue by jaspersival** [pandas-dev/pandas#40581]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
series = pd.Series([pd.NA, 1.0, 2.5], dtype=pd.Float64Dtype())
series.clip(upper=2.0)
```

#### Problem description

Pandas 1.2 cannot handle pd.NA values when the series has a Float64Dtype. When running the code snipped above, the following error occurs:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\XXX\AppData\Local\pypoetry\Cache\virtualenvs\XXX-w19Rd76b-py3.9\lib\site-packages\pandas\core\generic.py", line 7711, in clip
    return self._clip_with_scalar(lower, upper, inplace=inplace)
  File "C:\Users\XXX\AppData\Local\pypoetry\Cache\virtualenvs\XXX-w19Rd76b-py3.9\lib\site-packages\pandas\core\generic.py", line 7562, in _clip_with_scalar
    subset = self.to_numpy() <= upper
  File "pandas\_libs\missing.pyx", line 360, in pandas._libs.missing.NAType.__bool__
TypeError: boolean value of NA is ambiguous

#### Expected Output
pd.Series([pd.NA, 1.0, 2.0], dtype=pd.Float64Dtype)

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f2c8480af2f25efdbd803218b9d87980f416563e
python           : 3.9.1.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252
pandas           : 1.2.3
numpy            : 1.20.1
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 52.0.0
Cython           : None
pytest           : 6.2.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.1
sqlalchemy       : 1.4.2
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
numba            : None

</details>

**Comment by jorisvandenbossche** [comment]
@jaspersival Thanks for the clear report! 
That's indeed a bug for the nullable dtypes (the same happens if you have eg Int64Dtype)

In the line

```
~pandas\core\generic.py", line 7562, in _clip_with_scalar
               subset = self.to_numpy() <= upper
```

we should not simply convert to a numpy array with `to_numpy()`. Probably best to first do the comparison, and only afterwards convert to a numpy array.

**Comment by ericch99** [comment]
Hi, I am a first-time contributor and noticed this was labeled with "good first issue" -- can I be preemptively assigned this?

**Comment by mzeitlin11** [comment]
Have assigned you @ericch99, let us know if you need help with anything! (in future you can assign yourself by commenting "take")

**Comment by AlPalll** [comment]
take

**Comment by Rasori** [comment]
take
