### ISSUE TITLE
QST:

### ISSUE THREAD

**Issue by yanuarkrisna** [pandas-dev/pandas#40607]
why my plotnine cant be applied? this is that error, how to solved that?

ImportError: cannot import name 'FrameOrSeriesUnion' from 'pandas._typing' (C:\Users\ASUS\Anaconda3\lib\site-packages\pandas\_typing.py)

**Comment by MarcoGorelli** [comment]
Hi - please see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by rhshadrach** [comment]
@yanuarkrisna, respond here with a reproducible example and can reopen.
