### ISSUE TITLE
March 2021 Docs Meeting

### ISSUE THREAD

**Issue by afeld** [pandas-dev/pandas#40603]
- [Thursday, March 25th 9-10am US Eastern Time](https://everytimezone.com/s/d95276ff)
- [Zoom link](https://nyu.zoom.us/j/98201283174?pwd=d0VoUy9GTDRlVVZ0cCtTK0s4NnlBZz09)
- [Agenda/notes](https://docs.google.com/document/d/1JoiqTdK6gi5W1QiTWrqtTV-rNmIqU3xROgHY5iT4J5g/edit#heading=h.98uhh75g3r7w)

---

A time to talk about pandas documentation. [Agenda/notes doc](https://docs.google.com/document/d/1JoiqTdK6gi5W1QiTWrqtTV-rNmIqU3xROgHY5iT4J5g/edit#heading=h.1obsyhexqytc) — feel free to add things in advance. All are welcome. Thanks!

@pandas-dev/pandas-core @pandas-dev/pandas-triage @pandas-dev/pydata-sphinx-theme @pandas-dev/pandas-docs

**Comment by jorisvandenbossche** [comment]
I probably won't be able to make it this time (too many other meetings tomorrow ..)

**Comment by choldgraf** [comment]
not strictly related to Pandas, but curious if folks would be interested in something like this:

https://discourse.jupyter.org/t/a-documentation-workshop-for-the-jupyter-community/8491

**Comment by afeld** [comment]
Just two of us this time, so we ended early. Hopefully more folks can make it next time.

**Comment by jorisvandenbossche** [comment]
The workshop mentioned by @choldgraf above will take place this week Wednesday May 5 (given by Daniele Procida, on the Diátaxis Framework for Documentation, see https://diataxis.fr/).

Exact time slots:

Wednesday May 5 
Part 1: 3-5pm UTC+1 (click here for your timezone: https://www.timeanddate.com/worldclock/fixedtime.html?msg=Diátaxis+Framework+Workshop+Part+1&iso=20210505T15&p1=3903&ah=2) 
Part 2: 7-8:30 pm UTC+1 (click here for your timezone: https://www.timeanddate.com/worldclock/fixedtime.html?msg=Diátaxis+Framework+Workshop+Part+2&iso=20210505T19&p1=3903&ah=1&am=30)

There are still some available spaces, if people are interested!

**Comment by afeld** [comment]
I am! How does one sign up?

**Comment by jorisvandenbossche** [comment]
I have sent you an email
