### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by PiyuGandhi** [pandas-dev/pandas#40631]
---

#### Code Sample, a copy-pastable example

```python
# Your code here
import pandas as pd

pd.read_excel('2a/07AAUFG6881H1ZP_012021_R2A.xlsx',sheet_name='B2B',skiprows=6, engine='openpyxl').shape
Ouput- (24, 24)
```

#### Problem description

There are no empty rows, no change  in data has occurred. Somehow, only 24 rows are being read since today. There are 4 more files where same thing is happening

#### Expected Output
Actual shape of data - (92,24)

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 2a7d3326dee660824a8433ffd01065f8ac37f7d6
python           : 3.7.8.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.3.0
Version          : Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.1.2
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 49.6.0.post20200917
Cython           : None
pytest           : 6.2.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.20.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
numba            : None

</details>

**Comment by MarcoGorelli** [comment]
Hi @PiyuGandhi can you try with the latest pandas and post a reproducible example?

**Comment by rhshadrach** [comment]
@PiyuGandhi - thanks for the report. Going to close since we lack a reproducible example. If you can post one here (either file or code that produces the file), then we can reopen and look into the issue.
