### ISSUE TITLE
DOC: Styling guide lacks links to the referenced objects

### ISSUE THREAD

**Issue by moi90** [pandas-dev/pandas#40645]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/user_guide/style.html

#### Documentation problem

The page lacks links to the referenced objects (`DataFrame`, `Series`, ... but most importantly `Styler`).

#### Suggested fix for documentation

Links should be included. This could either be done using [raw reST cells](https://nbsphinx.readthedocs.io/en/0.8.2/raw-cells.html#reST) (which looks not as nice in the downloadable notebook) or by inserting relative links into the markdown code (which breaks easily).

**Comment by attack68** [comment]
does #39720 address some of these items?

**Comment by attack68** [comment]
It creates links in the jupyter notebook that sphinx can parse. Such as:

``` 
Styling should be performed after the data in a DataFrame has been processed. 
The [Styler][styler] creates an HTML `<table>` and leverages CSS styling language to
 manipulate many parameters including colors, fonts, borders, background, etc. 
See [here][w3schools] for more information on styling HTML tables.
 This allows a lot of flexibility out of the box, and even enables web developers to 
integrate DataFrames into their exiting user interface designs.

The `DataFrame.style` attribute is a property that returns a [Styler][styler] object.
It has a `_repr_html_` method defined on it so they are rendered automatically in Jupyter Notebook.

[styler]: ../reference/api/pandas.io.formats.style.Styler.rst
[w3schools]: https://www.w3schools.com/html/html_tables.asp

**Comment by moi90** [comment]
@attack68 Yes, I think #39720 resolves this issue. :+1:
