### ISSUE TITLE
Consolidate into contributing_environment.rst

### ISSUE THREAD

**Issue by David-dmh** [pandas-dev/pandas#40640]
If you could also make `contributing_environment.rst` which includes _both_ Docker instructions as well as non-Docker, and remove `env_outside_docker`, that'd be great, else it can be a follow-up PR

_Originally posted by @MarcoGorelli in https://github.com/pandas-dev/pandas/issues/40130#issuecomment-803026178_

**Comment by David-dmh** [comment]
take

**Comment by MarcoGorelli** [comment]
closed by #40130
