### ISSUE TITLE
DOC: Trivial typo fix in user_guide/window

### ISSUE THREAD

**Issue by mdengler** [pandas-dev/pandas#40666]
#### Location of the documentation

Trivial typo fix of `min_periods` from `min_peridos` in the Overview of the [Windowing](https://pandas.pydata.org/docs/user_guide/window.html) User Guide section.

**Comment by mdengler** [comment]
Fixed in https://github.com/pandas-dev/pandas/pull/40665

**Comment by jbrockmendel** [comment]
closed by #40667
