### ISSUE TITLE
BUG: row filtering by index slicing does not always work

### ISSUE THREAD

**Issue by yohplala** [pandas-dev/pandas#40663]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas as pd
df = pd.DataFrame(columns=['a', 'b'], index=range(6))
# Slicings that work
df[::2] = 1
df['a'][::2] = 'a'
df[1::2] = 2
df['a'][1::2] = 'c'
# Slicing that does not work
df[['a','b']][1::2] = 'aha'
```

#### Problem description

The last slicing does not work (Dataframe is not modified), and no error message is issued.
I could check that it works with `pd.IndexSlice`.
At least an error message should be raised.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f2c8480af2f25efdbd803218b9d87980f416563e
python           : 3.8.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.8.0-48-generic
Version          : #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : fr_FR.UTF-8
LOCALE           : fr_FR.UTF-8

pandas           : 1.2.3
numpy            : 1.18.5
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 52.0.0.post20210125
Cython           : 0.29.22
pytest           : 6.2.2
hypothesis       : None
sphinx           : 3.5.3
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.21.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.8.7
fastparquet      : 0.5.0
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : 2.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.6.2
sqlalchemy       : 1.3.23
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.51.2

</details>

**Comment by mzeitlin11** [comment]
Thanks for the report @yohplala. I don't think this is row filtering specific, but rather a case of chained assignment (see https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-view-versus-copy).  Column setting also fails in this case, eg: `df[['a','b']][1::2] = 5` also does not modify `df`. The right way to slice with your final statement would be

```df.loc[1::2, ['a', 'b']] = 'aha'```

**Comment by yohplala** [comment]
Thanks @mzeitlin11 
The `.loc` does the trick indeed, a lot of thanks.
Bests
(leaving the ticket open - I think issuing an error in above mentionned case would be the answer)

**Comment by attack68** [comment]
I think this is already covered here: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#indexing-view-versus-copy

**Comment by phofl** [comment]
This should probably raise a SettingWithCopyWarning?

**Comment by jreback** [comment]
yeah ideally this would show the warning

**Comment by mzeitlin11** [comment]
Will close in favor of #9767
