### ISSUE TITLE
BUG: When using np.datetime64 should have date ranges according to frequency

### ISSUE THREAD

**Issue by timcera** [pandas-dev/pandas#4066]
A daily frequency np.datetime64 should have a range of [2.5e16 BC, 2.5e16 AD].  Instead it follows the range for nanosecond [ 1678 AD, 2262 AD].

Ranges taken from http://docs.scipy.org/doc/numpy/reference/arrays.datetime.html

In [126]: pd.Timestamp(np.datetime64('1677-01-01'),'D')
Out[126]: Timestamp('2261-07-22 23:34:33.709551616', tz=None)

In [127]: pd.Timestamp(np.datetime64('1678-01-01'),'D')
Out[127]: Timestamp('1678-01-01 00:00:00', tz=None)

In [128]: pd.Timestamp(np.datetime64('2262-01-01'),'D')
Out[128]: Timestamp('2262-01-01 00:00:00', tz=None)

In [129]: pd.Timestamp(np.datetime64('2263-01-01'),'D')
Out[129]: Timestamp('1678-06-12 00:25:26.290448384', tz=None)

**Comment by jbrockmendel** [comment]
@jreback closeable?

**Comment by jreback** [comment]
yes we raise appropriately for out of bounds
