### ISSUE TITLE
EHN: Function to optimise dataframe (efficient datatypes)

### ISSUE THREAD

**Issue by mapattacker** [pandas-dev/pandas#40692]
**Problem**

It is well-documented that the default data frame is not the most size efficient. To do that we have to manually convert each column to their respectively smallest datatype possible.

This will involve the conversion of categorical and downsizing of integers & floats as stated in pandas [documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/scale.html#use-efficient-datatypes).

**Solution**

I am wondering if it makes sense to create a new function to automatically convert/scale down all the columns in a dataframe to its most efficient. Something as simple as below.

```python
import pandas as pd

df_optimzied = pd.optimize(df)
```

I will be willing to implement this feature as a pull request if it is something the maintainers value. At least, I feel it is something our team will use frequently.

**Comment by rhshadrach** [comment]
What would be the methodology for deciding various float datatypes?

**Comment by mroeschke** [comment]
Sounds like this would just be a wrapper around `pd.to_numeric(..., downcast="...")`? https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_numeric.html

If so, I'm not entirely convinced this needs to be a separate pandas function.

**Comment by attack68** [comment]
@mroeschke I agree

**Comment by jorisvandenbossche** [comment]
It's not really easy to apply `pd.to_numeric` to all columns (eg can only downcast to one of integer or floating at a time, and will also downcast integers to float):

```
In [46]: df = pd.DataFrame({'a': [1, 2, 3], 'b': [1.1, 2.2, 3.3]})

In [47]: df.dtypes
Out[47]: 
a      int64
b    float64
dtype: object

In [48]: df.apply(lambda col: pd.to_numeric(col, downcast="integer")).dtypes
Out[48]: 
a       int8
b    float64
dtype: object

In [49]: df.apply(lambda col: pd.to_numeric(col, downcast="float")).dtypes
Out[49]: 
a    float32
b    float32
dtype: object
```

So you will need to write a function with a bit more logic that calls ``pd.to_numeric`` in a certain way depending on the dtype.

Now, I think there could be quite some different options on what's the "best" optimization (use categorical dtype or not, use the lowest possible integer bitsize or not (can be annoying for arithmetic, which overflows), ...), which will heavily depend on your exact usecase. So that might be best left to the user to write.

**Comment by ZurMaD** [comment]
> **Problem**
> 
> It is well-documented that the default data frame is not the most size efficient. To do that we have to manually convert each column to their respectively smallest datatype possible.
> 
> This will involve the conversion of categorical and downsizing of integers & floats as stated in pandas [documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/scale.html#use-efficient-datatypes).
> 
> **Solution**
> 
> I am wondering if it makes sense to create a new function to automatically convert/scale down all the columns in a dataframe to its most efficient. Something as simple as below.
> 
> ```python
> import pandas as pd
> 
> df_optimzied = pd.optimize(df)
> ```
> 
> I will be willing to implement this feature as a pull request if it is something the maintainers value. At least, I feel it is something our team will use frequently.

Something like this? https://github.com/deepak7376/downcast

https://github.com/deepak7376/downcast/blob/master/src/downcast.py

```
import pandas as pd
import numpy as np

def reduce(df):
    cols = df.dtypes.index.tolist()
    types = df.dtypes.values.tolist()
    for i,t in enumerate(types):
        if 'int' in str(t):
            if df[cols[i]].min() > np.iinfo(np.int8).min and df[cols[i]].max() < np.iinfo(np.int8).max:
                df[cols[i]] = df[cols[i]].astype(np.int8)
            elif df[cols[i]].min() > np.iinfo(np.int16).min and df[cols[i]].max() < np.iinfo(np.int16).max:
                df[cols[i]] = df[cols[i]].astype(np.int16)
            elif df[cols[i]].min() > np.iinfo(np.int32).min and df[cols[i]].max() < np.iinfo(np.int32).max:
                df[cols[i]] = df[cols[i]].astype(np.int32)
            else:
                df[cols[i]] = df[cols[i]].astype(np.int64)
        elif 'float' in str(t):
            if df[cols[i]].min() > np.finfo(np.float16).min and df[cols[i]].max() < np.finfo(np.float16).max:
                df[cols[i]] = df[cols[i]].astype(np.float16)
            elif df[cols[i]].min() > np.finfo(np.float32).min and df[cols[i]].max() < np.finfo(np.float32).max:
                df[cols[i]] = df[cols[i]].astype(np.float32)
            else:
                df[cols[i]] = df[cols[i]].astype(np.float64)
        elif t == np.object:
            if cols[i] == 'date':
                df[cols[i]] = pd.to_datetime(df[cols[i]], format='%Y-%m-%d')
            else:
                df[cols[i]] = df[cols[i]].astype('category')
    return df

```

**Comment by mapattacker** [comment]
> It's not really easy to apply `pd.to_numeric` to all columns (eg can only downcast to one of integer or floating at a time, and will also downcast integers to float):
> 
> ```
> In [46]: df = pd.DataFrame({'a': [1, 2, 3], 'b': [1.1, 2.2, 3.3]})
> 
> In [47]: df.dtypes
> Out[47]: 
> a      int64
> b    float64
> dtype: object
> 
> In [48]: df.apply(lambda col: pd.to_numeric(col, downcast="integer")).dtypes
> Out[48]: 
> a       int8
> b    float64
> dtype: object
> 
> In [49]: df.apply(lambda col: pd.to_numeric(col, downcast="float")).dtypes
> Out[49]: 
> a    float32
> b    float32
> dtype: object
> ```
> 
> So you will need to write a function with a bit more logic that calls `pd.to_numeric` in a certain way depending on the dtype.
> 
> Now, I think there could be quite some different options on what's the "best" optimization (use categorical dtype or not, use the lowest possible integer bitsize or not (can be annoying for arithmetic, which overflows), ...), which will heavily depend on your exact usecase. So that might be best left to the user to write.

Sorry for the late response.

hi @jorisvandenbossche, you are right to an extent.

I think for my use case, after doing all the data wrangling, I want to pickle the data frame to its most efficient data type, before using it in production. Till now I have to write or copy a version of a function shown below (similar to @ZurMaD , and also @mroeschke of wrapping `pd.to_numeric`, and I find it mildly bother more to repeat that.


```python
def reduce_df(df, cat_col=[], cat_percent=0.5):
    """"data memory optimization
    
    Args:
        cat_col (list): list of columm names to convert to category dtype
        cat_percent (float): only convert if percentage duplicates more than stated
    """
    size = len(df)
    for col in df.columns:
        if df[col].dtype == float:
            df[col] = pd.to_numeric(df[col], downcast='float')
        elif df[col].dtype == int:
            min_ = df[col].min()
            if min_ > 0:
                df[col] = pd.to_numeric(df[col], downcast='integer')
            else:
                df[col] = pd.to_numeric(df[col], downcast='unsigned')
        elif df[col].dtype == object:
            if col in cat_col:
                dup_percent = 1 - (len(df[col].unique()) / size)
                if dup_percent > cat_percent:
                    df[col] = df[col].astype('category')
    return df
```

**Comment by mroeschke** [comment]
Thanks for the suggestion, but as others have mentioned, it appears a function like this is best suited for the user to implement and for pandas not to have an opinion on what `optimal` is. Closing.
