### ISSUE TITLE
BUG: Divide zero by zero returns NaN in a Float64 dtype column which cannot be handled by fillna

### ISSUE THREAD

**Issue by jaspersival** [pandas-dev/pandas#40704]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
series1 = pd.Series([0.], dtype=pd.Float64Dtype())
series2 = pd.Series([0.], dtype=pd.Float64Dtype())
series1/series2
0    NaN
dtype: Float64
(series1/series2).fillna(0)
0    NaN
dtype: Float64
```

#### Problem description

When dividing a pd.Float64Dtype series by another of the same type, and if there is a zero by zero division taking place, then pandas returns a NaN value for that particular case. If I want to replace this NaN value with something else, I cannot do that.
I can only get it to work if I do:
```python
(series1/series2).astype(float).astype(pd.Float64Dtype()).fillna(0)
0    0.0
dtype: Float64
```
#### Expected Output

```python
(series1/series2).fillna(0)
0    0.0
dtype: Float64
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f2c8480af2f25efdbd803218b9d87980f416563e
python           : 3.9.1.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252
pandas           : 1.2.3
numpy            : 1.20.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 52.0.0
Cython           : None
pytest           : 6.2.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.1
sqlalchemy       : 1.4.3
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
numba            : None

</details>

**Comment by attack68** [comment]
lots of discussion on this: #32265 and #30188

**Comment by mzeitlin11** [comment]
And #39926, will close in favor of discussion there and other issues mentioned
