### ISSUE TITLE
ENH: add dataframe render trimming in `Styler` to avoid browser crash

### ISSUE THREAD

**Issue by attack68** [pandas-dev/pandas#40712]
`DataFrame.to_html` has max rows and max cols to automatically trim the console or string output.

`DataFrame.styler.render` does not and with large DataFrames this can potentially crash the browser of a Jupyter Notebook, or maybe a console.

Personally, I use `Styler` occasionally to quickly avoid the reasonably small max values in the former and this I would want to keep, but some tolerable, larger limit should be imposed in my opinion.

**Comment by LarWong** [comment]
take
