### ISSUE TITLE
BUG: to_sql performance decreases dramatically with more than 10 columns (SQL Server)

### ISSUE THREAD

**Issue by nurglexxx** [pandas-dev/pandas#40721]
- [x ] I have checked that this issue has not already been reported.

- [x ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

Found an interesting issue regarding the performance of to_sql() in combination with SQL Server.

OS: Centos/Redhat
DB Driver: ODBC Driver 17 for SQL Server
DB Server (remote): SQLServer 12

Performance:
34484 rows x 10 columns => >10k records per second

34484 rows x 12 columns => ~500 records per second

I tested it on two different Servers and DB's and the type of data doesn't seem to matter (all dtypes are object), the drop happens always if the df is havin more than 10 Columns

```python
    engine = sqlalchemy.create_engine("mssql+pyodbc:///?odbc_connect=%s?charset=utf8" % params, fast_executemany=True)
    sqlalchemy_connection = engine.connect()
    ....
   df.to_sql(name='TEST', con=con, if_exists='append', index=False)

```

(Tested it now with postgresql, the "bug" does not appear there, get around 14k/sec)

**Comment by jbrockmendel** [comment]
can you profile it to see where the hotspot is?

**Comment by nurglexxx** [comment]
Unfortunately not as I have no direct access to the DB's (only via the linux server, so no management studio), tried it also without fast_executemany parameter and using multi/chunksize, but this runs even worse.

**Comment by mroeschke** [comment]
Thanks for the report, but as presented it's very difficult to diagnose whether this is a pandas issue or not as the db flavor or underlying ORM (sqlalchemy, etc.) could also be at play here. Since it would be difficult for other maintainers to diagnose this performance issue, closing, but happy to reopen if you can pinpoint the issue to pandas specifically.
