### ISSUE TITLE
BUG: Inconcistency in DataFrame column numeric dtype comparison

### ISSUE THREAD

**Issue by aaraney** [pandas-dev/pandas#40753]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

#### Code Sample

```python
import pandas as pd
import numpy as np

df = pd.DataFrame({"int": [1,2,3], "float": [1.,2.,3.]})

# Below shows the unexpected differences

df.select_dtypes(np.number)

>>>   int  float
>>> 0    1    1.0
>>> 1    2    2.0
>>> 2    3    3.0

df[df.columns[df.dtypes.eq(np.number)]]

>>>   float
>>> 0    1.0
>>> 1    2.0
>>> 2    3.0

# More explicitly
df.dtypes.eq(np.number) #<- returns False for int64 type

>>> int      False
>>> float     True
>>> dtype: bool
```

#### Problem description

I realize this may be as intended or just an edge case that has not been handled, but I thought it was worth documenting as an issue. There is, what I would consider, unexpected behavior when trying to filter a dataframe to retrieve numeric columns. As shown in the above examples, when using the `df.select_dtypes(np.number)`, I get back what I would expected. However, when using `df.dtypes.eq(np.number)`, I get back a `pd.Series` noting that the column container an `int64` type is not equivalent to `np.number`.

#### Expected Output

```python
df.dtypes.eq(np.number)

>>> int      True
>>> float     True
>>> dtype: bool
```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : f2c8480af2f25efdbd803218b9d87980f416563e
python           : 3.8.5.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
Version          : Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.3
numpy            : 1.19.4
pytz             : 2020.4
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 50.3.1.post20201107
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : 0.8.7
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.4
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 0.17.0
xlrd             : None
xlwt             : None
numba            : None
</details>

**Comment by rhshadrach** [comment]
Thanks for the report! It seems to me this is not a pandas issue: `np.dtype('int64') == np.number` gives False whereas `np.dtype('float64') == np.number` gives True. I believe this is all that `eq` is doing.

**Comment by aaraney** [comment]
Certainly! That makes sense, I should have perused the `numpy` issues to see if that topic has come up before.

**Comment by mroeschke** [comment]
Yes this appears like numpy specific behavior. Feel free to let us know if there is something on the numpy side pandas hasn't taken into account. Closing
