### ISSUE TITLE
STYLE remove --keep-runtime-typing from pyupgrade

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#40759]
xref @simonjayhawkins 's comment: https://github.com/pandas-dev/pandas/pull/40545#discussion_r606360410

Task is:
- remove `keep-runtime-typing` from:

https://github.com/pandas-dev/pandas/blob/cc84a2383c641998d4817cfaeb33c64f017b7454/.pre-commit-config.yaml#L57

- run `pre-commit run pyupgrade --all-files`
- run `pre-commit run flake8 --all-files`, fixup any errors (probably some about extra imports)

Finally, run `pre-commit run --all-files` (this may take a few minutes), fixup any hooks which don't pass, and when everything passes, open a pull request :rocket:

**Comment by fathomer** [comment]
Hi
I was working on this issue, fixed all the import errors from flake8, but there are some(19) "F821 undefined name" errors thrown by flake8 which seem to be some sort of false-positives. Is it ok to suppress them ?

As an example, for the file pandas/core/dtypes/generic.py ->
`pandas/core/dtypes/generic.py:37:5: F821 undefined name 'Int64Index'` 

But I don't see anything which suggests there is anything wrong with line 37 :
`ABCInt64Index = cast(
    "Type[Int64Index]",
    create_pandas_abc_type("ABCInt64Index", "_typ", ("int64index",)),
)`

There are multiple such instances in the same file.
Is it ok to suppress or them or is there any way to fix ?

**Comment by MarcoGorelli** [comment]
Hi @fathomer ,

`pandas/core/dtypes/generic.py` wouldn't get rewritten by pyupgrade, so I don't see why anything else would have to change there, but if you open a pull request I can take a look

**Comment by fathomer** [comment]
@MarcoGorelli raised the pull request, but there are some errors now in mypy type validations due to the changes by pyupgrade.
Any ideas on how to proceed on this?

**Comment by MarcoGorelli** [comment]
I've left a comment on the PR (https://github.com/pandas-dev/pandas/pull/40773#issuecomment-813008503), let's continue the conversation there
