### ISSUE TITLE
ENH: Option to turn off cell wrap in notebook output.

### ISSUE THREAD

**Issue by autoscraper** [pandas-dev/pandas#40779]
#### Option to turn off cell wrap in notebook output.

Behavior:
![image](https://user-images.githubusercontent.com/81045987/113525207-fd708500-9589-11eb-8c75-0fdd45c09b1c.png)

Wanted:
![image](https://user-images.githubusercontent.com/81045987/113525231-1842f980-958a-11eb-820c-a5cc9b3f8086.png)

there is df.style.set_properties(**{'white-space': 'nowrap'}), but I could not find a way to set it as default for pandas.

#### Solution I'd like

Implementation of `pd.options.display.wrap_cells`

##### Per DataFrame:
```
df.style.set_properties(**{'white-space': 'nowrap'})
```

##### Per Notebook
(from https://stackoverflow.com/a/65371335)

In the first cell of your notebook put
```
%%html
<style>
/* Any CSS style can go in here. */
.dataframe th {
    font-size: 18px;
}
.dataframe td {
    font-size: 16px;
}
</style>
```

#### Additional context

Tried all of those:
```
pd.options.display.width
pd.options.display.max_colwidth
pd.options.display.expand_frame_repr
```

**Comment by attack68** [comment]
Styler does not create HTML for the sake of setting a default - it leaves these upto the Browser and the application whose defaults actually do differ between them. 

For example it will not arbitrarily set: `font-family: verdana; font-size: 16pt;` and it will not do `line-height: 1.5em;`, these are inherited properties. I argue the same is true for the property you have highlighted.

Your alterantive will produce the required the result, as will:

`df.style.set_table_styles([{'selector': 'td', 'props': 'white-space: nowrap;'}])`

as will creating the factory:

```
def SpacedStyler(df, **kwargs):
    return Styler(df, **{'table_styles': [{'selector': 'td', 'props': 'white-space: nowrap;'}], **kwargs})
SpacedStyler(df)
```

**Comment by attack68** [comment]
closing since likely no action here.
