### ISSUE TITLE
BUG: Datetime duplicates

### ISSUE THREAD

**Issue by monkiravn** [pandas-dev/pandas#40786]
#### Problem description

Today I get a error from AutoML in Azuer is `Error: The specified time column, 'SolarDate', contains rows with duplicate timestamps. If your data contains multiple time series, review the time series identifier column setting to define the time series identifiers for your data. If the dataset needs to be aggregated, please provide freq and target_aggregation_function parameters and run AutoML again.` 
So I check for duplicates in 'SolarDate' - a datetime column, the result is this column is duplicated at a certain time of day 

#### Output of ``pd.show_versions()``
`df[['Solar_Date']]`
![image](https://user-images.githubusercontent.com/50236861/113598064-c9b75d00-9666-11eb-88f7-aef19500d1f8.png)
```
df['Solar_Date'] = pd.to_datetime(df['Solar_Date'],format="%Y/%m/%d %H:%M:%S")
df[df.duplicated(subset=['Solar_Date'])][['Solar_Date']]
```
![image](https://user-images.githubusercontent.com/50236861/113598183-ee133980-9666-11eb-9dee-75869aeb60db.png)

**Comment by phofl** [comment]
Hey,

thanks for your report. I am a bit confused what your actual problem with pandas is?

**Comment by monkiravn** [comment]
> thanks for your report. I am a bit confused what your actual problem with pandas is?

I don't know why it was duplicated like that, it also make me very confused and don't know how to handle it. I think it is a potential bug because you can see in my column don't have any duplicate row.

**Comment by phofl** [comment]
Your column has duplicates, otherwise your result would be empty. If you have a usage question, please ask them on stackoverflow

**Comment by phofl** [comment]
Closing now, feel free to ping to reopen if you have something reproducible, which shows a bug in pandas
