### ISSUE TITLE
DOC: to_datetime not type-stable on mixed timezones (possible bug)

### ISSUE THREAD

**Issue by mkovarik337** [pandas-dev/pandas#40808]
_Note_: This behaviour might be a bug. I'm assuming its an undocumented  feature.

#### Location of the documentation

[pandas.to_datetime.html](https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html)

#### Documentation problem

`to_datetime` outputs different types depending on if the timezones are mixed or not (assuming `utc=True` not passed in).
``` python
MIXED = ["2018-10-26 12:00 -0500", "2018-10-26 12:00 -0400"]
UNMIXED = ["2018-10-26 12:00 -0500", "2018-10-26 12:00 -0500"]

print(pandas.to_datetime(MIXED).dtype)   # ==> object
print(pandas.to_datetime(UNMIXED).dtype) # ==> datetime64[ns, pytz.FixedOffset(-300)]
```

#### Suggested fix for documentation

Specify aforementioned behaviour in documentation (in the `returns` section). Or, if not intentional feature, update the API to be type-stable.

**Comment by mroeschke** [comment]
We do have tests asserting this `object` dtype (`test_construction_index_with_mixed_timezones`), but could use more documentation in `to_datetime` regarding this behavior

**Comment by chinmayrane** [comment]
take
