### ISSUE TITLE
TYP return type of DataFrame.clip not correct

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#40829]
https://github.com/pandas-dev/pandas/blob/094f630cd84365b1902b4ee8d3de6a72d1bcbca3/pandas/core/generic.py#L7449-L7458

Return type should be `Optional[FrameOrSeriesUnion]`

It could also do with being overloaded according to the value of `inplace` - see `set_axis` and `DataFrame.reset_index` for examples

**Comment by DriesSchaumont** [comment]
take

**Comment by nidhishtyagi** [comment]
Hey, so I've changed the return type to `Optional[FrameOrSeriesUnion]` but could you please explain what you mean by 
overloading according to the value of `inplace` @MarcoGorelli

**Comment by MarcoGorelli** [comment]
See `set_axis` and `reset_index` for examples - it looks like @DriesSchaumont is already working on this though

**Comment by DriesSchaumont** [comment]
Yep, PR probably out tomorrow.

**Comment by MarcoGorelli** [comment]
Awesome, feel free to ping if you get stuck on anything

**Comment by DriesSchaumont** [comment]
@MarcoGorelli Did you mean that the return type is supposed to be  `FrameOrSeriesUnion | None`  or `FrameOrSeries | None` ? If I use  FrameOrSeriesUnion, I get `pandas/core/generic.py:7538: error: Incompatible return value type (got "FrameOrSeries", expected "Optional[Union[DataFrame, Series]]")  [return-value]` On line 7526, `result = self`. So `FrameOrSeries` seems applicable here?

**Comment by MarcoGorelli** [comment]
My bad, I meant `FrameOrSeries` - thanks @DriesSchaumont !
