### ISSUE TITLE
ENH: Make concat succeed on empty list.

### ISSUE THREAD

**Issue by frobnitzem** [pandas-dev/pandas#40820]
#### Is your feature request related to a problem?

Yes, `pd.concat([])` currently raises the exception, ValueError("No objects to concatenate").

#### Describe the solution you'd like

To be correct on all input sizes, it should return an empty DataFrame.

#### API breaking implications

Obviously, concat will no longer detect empty data.  However, empty data will detect itself.

#### Additional context

The concatenation operation is for lists what addition is for numbers.  Concatenation of an empty list should produce an empty dataframe, because the empty dataframe represents `0`.  Consider
```
sum([])
```
which python evaluates to 0.

This makes concatenation and sum commute, `sum([1] + []) == sum([1]) + sum([])`.

This already works for an empty dataframe:
```
pd.concat([pd.DataFrame({'A':[1]}), pd.DataFrame()])
```
if is very odd for concat([]) not to produce a DataFrame, since its input has the correct type.

**Comment by ivanovmg** [comment]
I guess it is not clear what should be the return type.
If we concat dataframes, then the function returns a dataframe.
Similarly, for series objects it returns a series.
However, what should we return in case of an empty input?

**Comment by hamishdarbyshire** [comment]
> I guess it is not clear what should be the return type.
> If we concat dataframes, then the function returns a dataframe.
> Similarly, for series objects it returns a series.
> However, what should we return in case of an empty input?

I agree, and if Series is to be interpreted as a 'simpler' object (i.e. df["colA"] returns a Series not a DataFrame), then arguably one might suggest returning a Series rather than a DataFrame, **if** anything at all is returned.

**Comment by attack68** [comment]
> I guess it is not clear what should be the return type.
> If we concat dataframes, then the function returns a dataframe.
> Similarly, for series objects it returns a series.
> However, what should we return in case of an empty input?

I agree, and if Series is to be interpreted as a 'simpler' object (i.e. df["colA"] returns a Series not a DataFrame), then arguably one might suggest returning a Series rather than a DataFrame, if anything at all is returned.

**Comment by frobnitzem** [comment]
Sounds like a solution would be for concat([]) to return a new object type representing both empty Series and empty DataFrames.  Perhaps there's a base class that makes sense there - I don't know enough to say.

For now, I just create my own `concatDF` function that only works on DataFrames.

**Comment by yushao2** [comment]
> Sounds like a solution would be for concat([]) to return a new object type representing both empty Series and empty DataFrames. Perhaps there's a base class that makes sense there - I don't know enough to say.
> 
> For now, I just create my own `concatDF` function that only works on DataFrames.

Here's an idea, incorporating an optional initializer for the pd.concat function, similar to reduce:

https://docs.python.org/3/library/functools.html#functools.reduce

**Comment by yushao2** [comment]
> Sounds like a solution would be for concat([]) to return a new object type representing both empty Series and empty DataFrames. Perhaps there's a base class that makes sense there - I don't know enough to say.
> 
> For now, I just create my own `concatDF` function that only works on DataFrames.

I created a PR for this for the first solution mentioned -- feel free to take a look and share your thoughts.

It's my first time contributing to this project so I'm sorry if I've made any mistakes.

Thanks!

**Comment by mroeschke** [comment]
I find the current behavior correct as is.

For reference `np.concatenate` also raises a similar error as `pd.concat`

```
In [1]: np.concatenate([])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-7806ca832c55> in <module>
----> 1 np.concatenate([])

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: need at least one array to concatenate
```

And I believe it's more explicit for the user to decide what to do in code flow if they get to a `pd.concat([])` situation.

So I'd be -1 on any changes here.

**Comment by mroeschke** [comment]
Thanks for the suggestion, but also from the review on a proposal PR https://github.com/pandas-dev/pandas/pull/41355#pullrequestreview-654681587, I think this behavior is best left for the user to decide manually what the result of empty concatenation should be. Closing.
