### ISSUE TITLE
QST: hi guys i have an doubt in pandas i created  series as ['Quality–color'] in my data frame by adding Cut & Color variable into that series as "diam['Quality-color']=diam.cut + ', ' + diam.color" my query was why im getting two colums as 'Quality-color' for your reference i have attached the image  

### ISSUE THREAD

**Issue by sbrsankar** [pandas-dev/pandas#40859]
- [ ] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
# Your code here, if applicable

```

**Comment by phofl** [comment]
Please provide something reproducible

**Comment by sbrsankar** [comment]
![pandas](https://user-images.githubusercontent.com/56156134/114236003-9a725a00-999e-11eb-8025-a733160e4b60.jpg)

**Comment by phofl** [comment]
A reproducible example in code please, not a screenshot.

**Comment by sbrsankar** [comment]
Write a Pandas program to create a new 'Quality -color' Series (use bracket
notation to define the Series name) of the diamonds DataFrame.
above exercise need to get solved by me so i have written the code as
"diam['Quality-color']=diam.cut + ', ' + diam.color" my question was why
im getting two column name as  'Quality -color' when i used to print using
the head() function can you please explain this

Thanks
Sabari Sankar Mohan

**Comment by phofl** [comment]
Please have a look at https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports, this explains what a reproducible example is.

**Comment by MarcoGorelli** [comment]
Hi @sbrsankar ,

Please ask usage questions on StackOverflow or some other forum - if you believe there's a bug in pandas, then please include a reproducible example (as suggested above)

Thanks! :+1:

**Comment by sbrsankar** [comment]
thanks for your reply
Thanks
Sabari Sankar Mohan
