### ISSUE TITLE
STYLE, TYP frame-or-series-union check no longer relevant

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#40876]
This check is no longer relevant:

https://github.com/pandas-dev/pandas/blob/9ab55b4aed9018b070c939ffbdf232f99bf50f1a/.pre-commit-config.yaml#L83-L88

Since using PEP604 rewrites, this would be written as
```
x: Series | DataFrame
```
anyway.
```
x: FrameOrSeriesUnion
```
is actually just as long as the above, and arguably less explicit.

----

@simonjayhawkins thoughts on replacing all the `FrameOrSeriesUnion` occurrences, removing the alias, and removing the above check?

**Comment by simonjayhawkins** [comment]
+1

**Comment by mohansaimandalapu** [comment]
Hi MarcoGorelli 

I would like to take up this issue, this is my first open source PR, I couldn't understand the issue completely. It would be great if you can elucidate it. Thank you

**Comment by MarcoGorelli** [comment]
Sure. At the moment, we alias `DataFrame | Series` as `FrameOrSeriesUnion`, the issue is simply to remove the alias. So:

1. remove this check:

   https://github.com/pandas-dev/pandas/blob/895f0b4022562d33e485c5d4eab1014d18656e0c/.pre-commit-config.yaml#L83-L88

2. remove this alias:

   https://github.com/pandas-dev/pandas/blob/895f0b4022562d33e485c5d4eab1014d18656e0c/pandas/_typing.py#L97-L101

3. Anywhere in the codebase which uses this alias, replace it with `DataFrame | Series`

If anything is unclear, please do ask :)

**Comment by Swanand01** [comment]
Hello @MarcoGorelli.
First time contributor here.  I would like to take up this issue.  
If i understand correctly,  
the check:

` -   id: frame-or-series-union 
     name: Check for use of Union[Series, DataFrame] instead of FrameOrSeriesUnion alias 
     entry: Union\[.*(Series,.*DataFrame|DataFrame,.*Series).*\] 
     language: pygrep 
     types: [python] 
     exclude: ^pandas/_typing\.py$ ` 

and

` # FrameOrSeriesUnion  means either a DataFrame or a Series. E.g. 
 # `def func(a: FrameOrSeriesUnion) -> FrameOrSeriesUnion: ...` means that if a Series 
 # is passed in, either a Series or DataFrame is returned, and if a DataFrame is passed 
 # in, either a DataFrame or a Series is returned. 
 FrameOrSeriesUnion = Union["DataFrame", "Series"] `

has to be removed, and all other instances of  FrameOrSeriesUnion have to be replaced with Series | DataFrame

**Comment by Swanand01** [comment]
Hello @MarcoGorelli, first time contributor here. I would like to take up this issue.
If I understand correctly, the check and alias have to be removed, and all instances of FrameOrSeriesUnion in the codebase have to be replaced with Series | DataFrame.
Thank you.

**Comment by joonlimeecs** [comment]
take

**Comment by MarcoGorelli** [comment]
I think @mohansaimandalapu is already working on this

**Comment by joonlimeecs** [comment]
> I think @mohansaimandalapu is already working on this
I thought multiple contributors on a single issue is allowed, my bad.

**Comment by MarcoGorelli** [comment]
> > I think @mohansaimandalapu is already working on this
> > I thought multiple contributors on a single issue is allowed, my bad.

Hey @joonlim9 - it doesn't look like they're working on it, feel free to take it up if you like

**Comment by Anupam-USP** [comment]
PR is merged so is this issue closed? @MarcoGorelli

**Comment by simonjayhawkins** [comment]
> PR is merged so is this issue closed? @MarcoGorelli

#41546 is the PR to address this issue and that is not merged.

**Comment by Anupam-USP** [comment]
Can I take it?

**Comment by MarcoGorelli** [comment]
> Can I take it?

If the author of #41546 doesn't update in, say, another week, then yeah, sure - let's leave them a couple weeks to get back to us at least
