### ISSUE TITLE
BUG: for pd.Series with tz-aware index resample shifts time-labels after DST time transition 

### ISSUE THREAD

**Issue by alexveden** [pandas-dev/pandas#40891]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python

dt_idx = pd.date_range(pd.Timestamp('2021-03-12 05:00:00', tz='US/Pacific'),
                       pd.Timestamp('2021-04-07 12:45:00', tz='US/Pacific'),
                       freq='1T',
                       )
series = dt_idx.to_series()

bar_df = series.resample('120T', label='right').last().dropna()

print(bar_df)

```

#### Problem description
After resampling a time-series with tz-aware DatetimeIndex I've found that at the point of daylight clock change `resample` begins to show shifted time-labels. For example, typical hours are 0,2,4,6,8,10 , but after DST shift at 2021-03-14 we get +1 hour i.e. 7,9,11,13 and so on.

The issue seem to affect non-standard timeframes, e.g. 2H, 4H, 90T. Others like 1H, 30min, 15min, 5min look good.

**IMPORTANT**
The problem looks to be dependent on start date:
```python
# If we include previous DST transition date, we'll get valid values (no issue at all)
dt_idx = pd.date_range(pd.Timestamp('2020-10-31 05:00:00', tz='US/Pacific'),
                       pd.Timestamp('2021-04-07 12:45:00', tz='US/Pacific'),
                       freq='1T',
                       )
....
>print(bar_df.tail())
2021-04-07 06:00:00-07:00   2021-04-07 05:59:00-07:00
2021-04-07 08:00:00-07:00   2021-04-07 07:59:00-07:00
2021-04-07 10:00:00-07:00   2021-04-07 09:59:00-07:00
2021-04-07 12:00:00-07:00   2021-04-07 11:59:00-07:00
2021-04-07 14:00:00-07:00   2021-04-07 12:45:00-07:00



# Jan 2020 has influence on timestamp of Apr 2021
dt_idx = pd.date_range(pd.Timestamp('2020-01-31 05:00:00', tz='US/Pacific'),
                       pd.Timestamp('2021-04-07 12:45:00', tz='US/Pacific'),
                       freq='1T',
                       )
....
>print(bar_df.tail())
2021-04-07 05:00:00-07:00   2021-04-07 04:59:00-07:00
2021-04-07 07:00:00-07:00   2021-04-07 06:59:00-07:00
2021-04-07 09:00:00-07:00   2021-04-07 08:59:00-07:00
2021-04-07 11:00:00-07:00   2021-04-07 10:59:00-07:00
2021-04-07 13:00:00-07:00   2021-04-07 12:45:00-07:00
```

#### Expected Output

```python
> print(bar_df)
# Prior DST time
2021-03-12 06:00:00-08:00   2021-03-12 05:59:00-08:00
2021-03-12 08:00:00-08:00   2021-03-12 07:59:00-08:00
2021-03-12 10:00:00-08:00   2021-03-12 09:59:00-08:00
2021-03-12 12:00:00-08:00   2021-03-12 11:59:00-08:00
2021-03-12 14:00:00-08:00   2021-03-12 13:59:00-08:00
...
# BUG new DST time timestamp hours are shifted
2021-04-07 05:00:00-07:00   2021-04-07 04:59:00-07:00
2021-04-07 07:00:00-07:00   2021-04-07 06:59:00-07:00
2021-04-07 09:00:00-07:00   2021-04-07 08:59:00-07:00
2021-04-07 11:00:00-07:00   2021-04-07 10:59:00-07:00
2021-04-07 13:00:00-07:00   2021-04-07 12:45:00-07:00

```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f2c8480af2f25efdbd803218b9d87980f416563e
python           : 3.7.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.0-16-amd64
Version          : #1 SMP Debian 4.19.181-1 (2021-03-19)
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.3
numpy            : 1.20.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 52.0.0.post20210125
Cython           : 0.29.22
pytest           : 5.0.1
hypothesis       : None
sphinx           : 2.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.3.4
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.21.0
pandas_datareader: 0.9.0
bs4              : 4.9.3
bottleneck       : 1.2.1
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.1.0
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.3.0
sqlalchemy       : 1.3.5
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.53.0

</details>

**Comment by Liam3851** [comment]
This is intentional, see [the docs](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#dateoffset-objects). When you do a resample('2H') you're asking for a timeseries of every 2 hours, in Pacific time, from a pre-DST time to a post-DST time. At the changeover, you skip an hour. So 2 hours after midnight PST on the DST change is 3:00 AM PDT. Two hours after that is 5:00 AM PDT etc., until DST flips back, at which point 2 hours after 1 AM PDT is 2 AM PST.

**Comment by mroeschke** [comment]
Thanks for the report, but as explained this is the expected behavior. Closing.
