### ISSUE TITLE
QST: I have tried lots of different suggestions but still cannot import pandas / numpy into pycharm

### ISSUE THREAD

**Issue by oliverpjon** [pandas-dev/pandas#40919]
![image](https://user-images.githubusercontent.com/82443972/114531780-7f2c7680-9c4c-11eb-87f6-1c3ca6f24d69.png)

I have installed both using PIP as seen in photo
but always get this in pycharm
![image](https://user-images.githubusercontent.com/82443972/114531897-99665480-9c4c-11eb-8414-5c601fb5ecfc.png)

**Comment by MarcoGorelli** [comment]
Hi @oliverpjon ,

Thanks for your question, but this isn't really the place to debug IDE issues - can you try asking on StackOverflow / some PyCharm forum please? Thanks :+1:
