### ISSUE TITLE
QST: Can read_sql ignore the condition if parameter is None?

### ISSUE THREAD

**Issue by ghuname** [pandas-dev/pandas#40920]
If I have params and sql defined as this:

```
params = {
	'field1': 1, 
	'field2': 'XYZ', 
	'field3: 100
	}
	
sql = """
	select *
	from table
	where 1 = 1
	and table.field1 = %(field1)s
	and table.field2 = %(field2)s
	and table.field3 = %(field3)s
"""
```

Everything works as it should if I am reading the sql like this:

`df = pd.read_sql(sql, params=params)`

But, if for example `params['field3'] is None` (instead of `100` or any other value) I would like to ignore condition `and table.field3 = %(field3)s`.

Can I use read_sql and have such behaviour with pandas read_sql or jinjasql is my only option?

**Comment by mzeitlin11** [comment]
The action of `params` depends on your database driver (pandas just forwards it along, doesn't do anything with it). So unless a driver supports this, pandas cannot support this (and I don't think adding such support would be in scope for pandas). I'd suggest just writing a quick helper to build the query before the `read_sql` step, in that way you can log it, etc, to see what query you're actually feeding in which seems much safer/more reliable.

**Comment by ghuname** [comment]
Hi @mzeitlin11,

than jinjasql is the best bet.
Thanks for clarifying.

Regards.

**Comment by mzeitlin11** [comment]
Thanks @ghuname! Closing as resolved, but please ping if you run into other issues
