### ISSUE TITLE
BUG: View on DataFrame with a Multiindex using .loc doesn't give proper results for df.index.levels or df.index.levshape

### ISSUE THREAD

**Issue by scmartin** [pandas-dev/pandas#40943]
If I create a view on a subset of a dataframe with a Multiindex using `.loc`, if I print the index of the subset, it get the expected subset of the Multiindex. However `index.levels` and `index.levshape ` return the values for the original dataframe, not the subset.

```python
import pandas as pd
import numpy as np

index = [[1,1,1,1,2,2,2,2,3,3,3,3],
             [1,2,3,4,1,2,3,4,1,2,3,4]]
data = pd.DataFrame(np.random.randn(12,2),index=index)
smalldata = data.loc[(slice(None),slice(1,2)),:]
print(data.index)
print(smalldata.index)
print(smalldata.index.levels)
print(smalldata.index.levshape)
```

#### Problem description

If the index of the created view is only the subset of values which appear in the view, the index methods `levels` and `levshape` should reflect this subset of values, not the whole index of the original dataframe

#### Expected Output

```python
>>> print(smalldata.index.levels)
[[1, 2, 3], [1, 2]]
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : d9fff2792bf16178d4e450fe7384244e50635733
python           : 3.8.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-957.1.3.el7.x86_64
Version          : #1 SMP Thu Nov 29 14:49:43 UTC 2018
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : None.None

pandas           : 1.1.0
numpy            : 1.19.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2
setuptools       : 49.2.0.post20200712
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.17.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.0
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by phofl** [comment]
Hey, thanks for your report.

This has nothing to do with the view. MultiIndex levels are not updated, when values are deleted from the Index, see for example:

```
x = data.drop(index=[(1, 4), (2, 4), (3, 4)])
```

still has

```
[[1, 2, 3], [1, 2, 3, 4]]
```

There was discussion about this in the past

**Comment by phofl** [comment]
See #36227 for example

**Comment by phofl** [comment]
Closing as this is expected

**Comment by rambo-yuanbo** [comment]
but still, maybe this should be mentioned in MultiIndex.levshape  Documentation

**Comment by phofl** [comment]
This is mentioned in multiple laces in the documentation
