### ISSUE TITLE
TYP final `_take_with_is_copy` is overridden in series

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#40974]
This method is declared as `final`:

https://github.com/pandas-dev/pandas/blob/526d52f91ee06ba9134762373ab3a0bb38395d8a/pandas/core/generic.py#L3629-L3630

It's then overridden in `series`:

https://github.com/pandas-dev/pandas/blob/526d52f91ee06ba9134762373ab3a0bb38395d8a/pandas/core/series.py#L866

The reason `mypy` doesn't detect this failure is that the override in `series` in untyped, and so `mypy` doesn't check it

---

@jbrockmendel do you know which one is correct? Remove `final` or remove the override?

**Comment by jbrockmendel** [comment]
i think remove the final

**Comment by 1Riyad** [comment]
Hi, I'm interested in contributing. Could I help to solve this?
