### ISSUE TITLE
BUG: Read Excel Unnamed Empty Columns

### ISSUE THREAD

**Issue by akald** [pandas-dev/pandas#40976]
Before I upgraded to Pandas v1.2.3, read_excel would sometimes create empty columns, titled "Unnamed: x". But after upgrading, it always creates empty unnamed columns and several of them. It seems like there should be a default such that empty columns that Pandas wants to call Unnamed don't show when reading in Excel.  Or that the read excel reverts to the old version (pre v1.2.3) where it wasn't as bad and unnamed empty columns weren't always being created.

**Comment by phofl** [comment]
Please provied something reproducible

**Comment by MarcoGorelli** [comment]
thanks for the report - closing for now, will reopen if you can address the above comment
