### ISSUE TITLE
BUG: module 'calendar' has no attribute 'day_abbr'

### ISSUE THREAD

**Issue by antoscha** [pandas-dev/pandas#40983]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas

```

#### Problem description

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/pandas/__init__.py", line 29, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "/usr/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "/usr/lib/python3.9/site-packages/pandas/_libs/tslibs/__init__.py", line 30, in <module>
    from .conversion import OutOfBoundsTimedelta, localize_pydatetime
  File "pandas/_libs/tslibs/conversion.pyx", line 58, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas/_libs/tslibs/timestamps.pyx", line 47, in init pandas._libs.tslibs.timestamps
  File "pandas/_libs/tslibs/fields.pyx", line 40, in init pandas._libs.tslibs.fields
  File "pandas/_libs/tslibs/strptime.pyx", line 627, in init pandas._libs.tslibs.strptime
  File "pandas/_libs/tslibs/strptime.pyx", line 532, in pandas._libs.tslibs.strptime.TimeRE.__init__
  File "pandas/_libs/tslibs/strptime.pyx", line 408, in pandas._libs.tslibs.strptime.LocaleTime.__init__
  File "pandas/_libs/tslibs/strptime.pyx", line 428, in pandas._libs.tslibs.strptime.LocaleTime.__calc_weekday
AttributeError: module 'calendar' has no attribute 'day_abbr'
```
Also I have built the latest 1.2.4 and the bug persists.
#### Expected Output

No output, successful import

<details>

$ pacman -Qi python-pandas                                                                                                                             [17:56:31]
Name            : python-pandas
Version         : 1.2.3-1
Description     : High-performance, easy-to-use data structures and data analysis tools for Python
Architecture    : x86_64
URL             : https://pandas.pydata.org/
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : python-numpy  python-dateutil  python-pytz  python-setuptools
Optional Deps   : python-pandas-datareader: pandas.io.data replacement (recommended) [installed]
                  python-numexpr: needed for accelerating certain numerical operations (recommended)
                  python-bottleneck: needed for accelerating certain types of nan evaluations (recommended)
                  python-beautifulsoup4: needed for read_html function [installed]
                  python-jinja: needed for conditional HTML formatting [installed]
                  python-pyqt5: needed for read_clipboard function (only one needed) [installed]
                  python-pytables: needed for HDF5-based storage
                  python-sqlalchemy: needed for SQL database support [installed]
                  python-scipy: needed for miscellaneous statistical functions [installed]
                  python-xlsxwriter: alternative Excel XLSX output [installed]
                  python-blosc: for msgpack compression using blosc
                  python-html5lib: needed for read_hmlt function (and/or python-lxml) [installed]
                  python-lxml: needed for read_html function (and/or python-html5lib) [installed]
                  python-matplotlib: needed for plotting [installed]
                  python-openpyxl: needed for Excel XLSX input/output [installed]
                  python-psycopg2: needed for PostgreSQL engine for sqlalchemy [installed]
                  python-pymysql: needed for MySQL engine for sqlalchemy
                  python-qtpy: needed for read_clipboard function (only one needed)
                  python-tabulate: needed for printing in Markdown-friendly format [installed]
                  python-fsspec: needed for handling files aside from local and HTTP
                  xclip: needed for read_clipboard function (only one needed) [installed]
                  python-xlrd: needed for Excel XLS input [installed]
                  python-xlwt: needed for Excel XLS output [installed]
                  xsel: needed for read_clipboard function (only one needed)
                  zlib: needed for compression for msgpack [installed]
Required By     : python-arch  python-pandas-datareader  python-pyportfolioopt-git  python-statsmodels
Optional For    : python-cclib  python-openpyxl  python-tabulate
Conflicts With  : None
Replaces        : None
Installed Size  : 55.24 MiB
Packager        : Morten Linderud <foxboron@archlinux.org>
Build Date      : Thu 11 Mar 2021 01:24:21
Install Date    : Fri 16 Apr 2021 17:56:31
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

</details>

**Comment by jbrockmendel** [comment]
what do you get if you do

```
import calendar
calendar.day_abbr
```

**Comment by antoscha** [comment]
```
>>> import calendar
>>> calendar.day_abbr
<calendar._localized_day object at 0x7fce1ef3a550>
```

**Comment by antoscha** [comment]
Oh, sorry, I created a file `calendar.py` which cause the error.
