### ISSUE TITLE
DEPR: Deprecate downcast keyword for fillna

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#40988]
This came up recently in #40861 
Depending on the way forward this would allow us to get downcast out from Block or be stricter about it

Thougts?

cc @jbrockmendel @jreback

**Comment by jbrockmendel** [comment]
xref #11537

**Comment by jbrockmendel** [comment]
More questionable behavior: 1) we do the downcast even if the fillna is a no-op, 2) we ignore `inplace=True` and downcast anyway.

**Comment by jbrockmendel** [comment]
Based on a few days of trying to figure this out, along with #11537, I propose we deprecate the 'downcast' keyword in 'fillna', 'interpolate', 'ffill', 'bfill', with the future behavior being to _always_ downcast for object dtype and never for anything else (the only relevant case for "anything else" being floats)

**Comment by jreback** [comment]
sounds ok to me

**Comment by jbrockmendel** [comment]
Having some trouble with the "do X instead" part because we don't have a method for downcasting floats (do we?)

**Comment by jreback** [comment]
we don't downcast floats as a general rule

**Comment by jbrockmendel** [comment]
update: deprecating the argument seems increasingly invasive.  Leaning towards chipping away at the inconsistencies and calling them bugfixes.

**Comment by rhshadrach** [comment]
@jbrockmendel - I removed the deprecate tag; do you know if this issue remain open for tracking or if it is now duplicative of other issues?

**Comment by jbrockmendel** [comment]
I've completely lost track

**Comment by jbrockmendel** [comment]
@phofl what are your current thoughts here?

**Comment by phofl** [comment]
Ideally, we would get rid of downcast in fillna and others and provide a proper down casting method?

**Comment by jbrockmendel** [comment]
Sounds good to me.  Want to take point on this?

**Comment by phofl** [comment]
Yep, can take care of this.

Would add deprecation note and new method for 2.1, so that we can immediately point users to an alternative.

**Comment by jbrockmendel** [comment]
I got annoyed enough by this to spend some more time on it.  Thinking of deprecating in steps:

1) Deprecate any "downcast" other than [None, False, "infer"] (or dict with each value being one of these)
2) Deprecate behavior of downcasting that casts round-floats to ints (once enforced this would allow us to reuse Block.convert instead of Block._downcast_2d)
3) Deprecate downcast keyword altogether
