### ISSUE TITLE
BUG: Compile failed on Raspberry Pi

### ISSUE THREAD

**Issue by Albelt** [pandas-dev/pandas#40997]
## Problem Description
I have followed the guidance of **README.md -> Installation from sources** , download the source code of master and excute the install commands. However, I got some errors when running this command 
``` bash
python setup.py install
```
It looks like that the installation script called gcc and got some problems, here's the error report:
``` bash
gcc: error: unrecognized command line option '-ffile-prefix-map=/builder/shared-workdir/build/sdk/build_dir/target-aarch64_cortex-a72_musl/Python-3.9.2=Python-3.9.2'
gcc: error: unrecognized command line option '-ffile-prefix-map=/builder/shared-workdir/build/sdk/build_dir/target-aarch64_cortex-a72_musl/Python-3.9.2=Python-3.9.2'
gcc: error: unrecognized command line option '-ffile-prefix-map=/builder/shared-workdir/build/sdk/build_dir/target-aarch64_cortex-a72_musl/Python-3.9.2=Python-3.9.2'
error: command '/usr/bin/gcc' failed with exit code 1
```
How can I solve this problem? Should I change the different gcc version or else?

## Device Information
Platform: Raspberry Pi 4B
CPU: BCM2711 ARM Cortex-A71 64bit
OS: OpenWrt( a linux distribution )
gcc: gcc (OpenWrt GCC 7.4.0) 7.4.0
g++: g++ (OpenWrt GCC 7.4.0) 7.4.0
Python: 3.9.2

**Comment by rhshadrach** [comment]
Looks like you need a more recent version of gcc:

https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=bd4d3cd1017feb469efa3112d2f92408a420be35

**Comment by erdoukki** [comment]
https://forum.openwrt.org/t/python3-pip3-aarch64-help/74685

**Comment by mroeschke** [comment]
Thanks for the report. As mentioned, this appears to be a gcc issue and not a pandas issue so closing. Happy to reopen if this circles back to a pandas issue
