### ISSUE TITLE
BUG: Pandas Multicolumns don´t keep df.columns.name when modifiyng some colum

### ISSUE THREAD

**Issue by epasseto** [pandas-dev/pandas#41009]
Just imagine that I create a dataset with multicolumns like that:
`import pandas as pd`
`arrays = [["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
          ["one", "two", "one", "two", "one", "two", "one", "two"],]`
`tuples = list(zip(*arrays))`
`index = pd.MultiIndex.from_tuples(tuples, names=["first", "second"])`
`df = pd.DataFrame(np.random.randn(3, 8), index=["A", "B", "C"], columns=index)`
`df`

OK, I created a df dataset, and I need to keep the name for the dataset using the **columns.name** attribute:
`df.columns.name = 'BOO'`
`df.columns.name`
gives: 'BOO'

Then I made a little alteration in my dataset (e.g. deleting, or adding a column) like this:
`df = df.drop([('bar', 'one')], axis=1)`
`df.columns.name`
gives: None

On single-column datasets, the column.name persist. But on multicolumns, column.name is lost every time I make a even small change on my columns!

INSTALLED VERSIONS
------------------
commit           : f2c8480af2f25efdbd803218b9d87980f416563e
python           : 3.8.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : pt_BR.cp1252

pandas           : 1.2.3
numpy            : 1.19.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 52.0.0.post20210125
Cython           : 0.29.22
pytest           : 6.2.2
hypothesis       : None
sphinx           : 3.5.3
blosc            : None
feather          : None
xlsxwriter       : 1.3.8
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.22.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.8.7
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.2
sqlalchemy       : 1.4.4
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.53.1

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here

```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by jreback** [comment]
notice that in a multi index .names is the relevant attribute (and it's a list)

.name is not meaningful
