### ISSUE TITLE
ENH: Adding 'hidden=True' to 'to_excel', or efficiently hiding some excel tabs?

### ISSUE THREAD

**Issue by chrisjdixon** [pandas-dev/pandas#41031]
I need to hide some excel tabs in an output from `to_excel`, and I'd like to do that with a parameter like `hidden=True`, but [no such parameter exists](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_excel.html). The only solution I can find is [hiding the sheet manually with openpyxl](https://stackoverflow.com/questions/23157643/openpyxl-and-hidden-unhidden-excel-worksheets/23170772#23170772), but this is prohibitively slow for large files.

[My StackOverflow question on this](https://stackoverflow.com/questions/67154554/pandas-to-excel-with-sheets-being-hidden-or-efficiently-hiding-excel-tabs) is unanswered, which suggests I'm out of luck.

Testing openpyxl showed that we can't save .xlsxs without at least one visible tab, so it looks like this would only work like so:

```
writer = pd.ExcelWriter(filename, engine='xlsxwriter') 
with writer:
    df.to_excel(writer, sheet_name='df')
    df.to_excel(writer, sheet_name='2nd tab')
```

Would adding `hidden=True` to `to_excel` be practical?

**Comment by chrisjdixon** [comment]
@jmcnamara has since answered my SO question, providing a great solution.

My issue is solved but I still think `hidden=True` is more elegant and beginner friendly than his answer, although I don't know what technical complications that might involve. I'll leave this open in case others think adding this is a good idea and easily done, otherwise please feel free to close this.

**Comment by jmcnamara** [comment]
> My issue is solved but I still think `hidden=True` is more elegant and beginner friendly than his answer, although I don't know what technical complications that might involve. 

There are some potential issues with this proposal. The first is that any parameter added to `to_excel()` has to be supported by all the Excel engines. In addition, there are a lot of parameters and methods that are exposed by XlsxWriter and OpenPyXL (and xlwt) and it wouldn't be feasible to add them all to the `to_excel()` interface (in fact it probably already has too many). Finally, there is a technical issue where hiding the active worksheet without activating another worksheet would generate a "corrupt" Excel file that would open with errors.

So my vote is to close this as can't fix/won't fix.

**Comment by rhshadrach** [comment]
> Testing openpyxl showed that we can't save .xlsxs without at least one visible tab

What is the use-case for creating an excel workbook with zero visible sheets? (If such a thing could exist)

**Comment by rhshadrach** [comment]
The User Guide outsources this kind documentation to [xlsxwriter](https://xlsxwriter.readthedocs.io/working_with_pandas.html), which doesn't have an example of hiding sheets. Maybe it could be a useful add there.

**Comment by chrisjdixon** [comment]
> What is the use-case for creating an excel workbook with zero visible sheets? (If such a thing could exist)

I can't think of any. Excel stops you from hiding the only visible sheet, openpyxl won't let you save without at least one visible sheet, and as @jmcnamara points out no visible tabs means a corrupt xlsx. I only mentioned it as I thought it might be relevant for technical considerations I wouldn't understand.

Agreed that this looks like a nice add to xlsxwriter documentation. I didn't know that `with writer:` could have functions other than `df.to_excel()` so it'd be nice to see some examples of this for laypeople like me 😅

**Comment by jmcnamara** [comment]
> The User Guide outsources this kind documentation to xlsxwriter.

That is fair enough. :-)

> which doesn't have an example of hiding sheets.

It does have an example of hiding sheets: https://xlsxwriter.readthedocs.io/example_hide_sheet.html

That isn't referenced in the Pandas section of the docs but not every feature is documented from a Pandas point of view. The [Working with Python Pandas and XlsxWriter](https://xlsxwriter.readthedocs.io/working_with_pandas.html) section of the docs mainly shows how to move from Pandas space to XlsxWriter space and answers the most frequent questions/usecases that come up on StackOverflow. Once the user is in XlsxWriter space then the rest of the documentation is available to help them.

**Comment by rhshadrach** [comment]
Thanks @jmcnamara - I missed the lines:

> After that we can treat them as normal XlsxWriter objects.
> ...
> This is equivalent to the following code when using XlsxWriter on its own:

but caught

> The Workbook and Worksheet objects can then be used to access other XlsxWriter features, see below.

which lead to my comment. This was merely due to my all-to-fast parsing, I do find the docs very clear and don't think anything needs changed.

**Comment by rhshadrach** [comment]
I don't think there is any further action required here - @chrisjdixon thanks for the report! If you feel something is still unresolved, simply reply here and can reopen.
