### ISSUE TITLE
ENH: Enable DataFrame.get(key) to return the index if key not found in columns

### ISSUE THREAD

**Issue by normanius** [pandas-dev/pandas#41038]
## Problem

Sometimes, one would like to get a column regardless whether it was previously set as index.

Consider the following example:

```python
df = pd.DataFrame(np.arange(50).reshape(5,10).T, columns=list("ABCDE"))
df = df.set_index(["A","B"])
col = df.get("B")
```

In the above code `col` is set to `None`.

## Solution

I suggest to add an argument `include_index`, so that the following is possible:

```python
item = df.get("B", include_index=True)
```

It first checks the column names, and if not successful, continues searching the index names. It still returns None if no item was found. 

This permits simpler queries that combine indices and columns:

```python
mask = (df.get("B", include_index=True) > 15) & (df.get("C", include_index=True) > 20)
```

## Implications on API

Backwards compatibility is guaranteed by setting the default value of `include_index=False`.

The return type of `get(key, include_index=True)` is now Optional[Union[pd.Series, pd.Index]]. If `key` belongs to the index, a `pd.Index` must be returned. A conversion to `pd.Series` is infeasible.

## Alternatives

Currently, the idiomatic way to return either column or index is:

```python
def get_item(df, key):
    return df[key] if key in df else (df.index.get_level_values(key) if key in df.index.names else None)
```

**Comment by jreback** [comment]
this is value dependent behavior and likely very confusing 

-1 on any change

**Comment by normanius** [comment]
@jreback I see that the different possible return types are confusing. On the other hand, for the type of problem described above, it doesn't matter what type of array-like object is returned, doesn't it?

Or going one step back: What is the best way to handle queries involving both index and columns at the same time while addressing them by name?

I think the following creates too much overhead:

```python
index_name = df.index.name
df = df.reset_index()
mask = df["B"]>15 & df["C"]>20
df = df.set_index(index_name)
```

**Comment by phofl** [comment]
get_level_values can be used to retrieve the index values for example

**Comment by normanius** [comment]
@phofl That's what I currently do, see `get_item()` above.

**Comment by mroeschke** [comment]
Thanks for the suggestion, but it appears this enhancement request hasn't gotten support from the core team so it's unlikely that pandas will proceed with this feature so closing. Happy to reopen if there is revived support from other core team members
