### ISSUE TITLE
BUG: Clipboard does not work on wsl2 Ubuntu 20.04

### ISSUE THREAD

**Issue by haleemur** [pandas-dev/pandas#41055]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
>>> import pyperclip
>>> pyperclip.copy('hello,world\n1,2\n3,4\n')
>>> pyperclip.paste()
'hello,world\r\n1,2\r\n3,4\r\n'
>>> import pandas as pd
>>> df = pd.read_clipboard(sep=',')

---------------------------------------------------------------------------
PyperclipException                        Traceback (most recent call last)
<ipython-input-6-7d5bcbe66479> in <module>
----> 1 df = pd.read_clipboard(sep=',')

~/envs/default/lib/python3.8/site-packages/pandas/io/clipboards.py in read_clipboard(sep, **kwargs)
     36     from pandas.io.parsers import read_csv
     37
---> 38     text = clipboard_get()
     39
     40     # Try to decode (if needed, as "text" might already be a string here).

~/envs/default/lib/python3.8/site-packages/pandas/io/clipboard/__init__.py in lazy_load_stub_paste()
    647     global copy, paste
    648     copy, paste = determine_clipboard()
--> 649     return paste()
    650
    651

~/envs/default/lib/python3.8/site-packages/pandas/io/clipboard/__init__.py in __call__(self, *args, **kwargs)
    285     class ClipboardUnavailable:
    286         def __call__(self, *args, **kwargs):
--> 287             raise PyperclipException(EXCEPT_MSG)
    288
    289         def __bool__(self) -> bool:

PyperclipException:
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit
    https://pyperclip.readthedocs.io/en/latest/#not-implemented-error
```

#### Problem description

pandas is unable to copy from the clipboard on windows using wsl2. This affects workflows where data is copied between spreadsheets, from the web and a dataframe is created, or vice-versa (i.e. dataframe is copied into a spreadsheet).

Pandas ships a vendored version of pyperclip that is old. The recent version of pyperclip resolves this issue on windows wsl2 in this pull request. https://github.com/asweigart/pyperclip/pull/168

As can be seen in my  pasted code sample, I have the most recent pyperclip installed on my system, and the clipboard functionality works as expected.

We can fix pandas' clipboard functionality by updating the vendored code (it seems that copy-pasting the `__init__.py` file from pyperclip ought to do the trick.

I'd be happy to contribute this change if the issue is approved. There seems to be a separate effort to move the backend from pyperclip to pyclip

#### Expected Output

I would expect to see 
#### Output of ``pd.show_versions()``

<details>

```
INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.8.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.128-microsoft-standard
Version          : #1 SMP Tue Jun 23 12:58:10 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.4
numpy            : 1.19.4
pytz             : 2020.4
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 44.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.6 (dt dec pq3 ext lo64)
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 0.8.7
fastparquet      : 0.5.0
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : None
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : 0.5.2
scipy            : 1.5.4
sqlalchemy       : 1.3.23
tables           : None
tabulate         : 0.8.7
xarray           : None
xlrd             : 2.0.1
xlwt             : None
numba            : 0.52.0
```
</details>

**Comment by fangchenli** [comment]
It works on my wsl. I have

```
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.8.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.4.0-19041-Microsoft
Version          : #488-Microsoft Mon Sep 01 13:43:00 PST 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.4
numpy            : 1.20.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 44.0.0
```

**Comment by jbrockmendel** [comment]
are you working on a headless system?

**Comment by haleemur** [comment]
@jbrockmendel i am working on a windows machine but my python environment is run in wsl2 (ubuntu 20.04). I think that _means_ i'm on a headless system, though I'm not 100% certain what you mean by "headless system".

@fangchenli I think the issue is that in your version of windows / wsl. the os release uses the capital-cased `Microsoft`, whereas on mine, it is lower-cased. the change made to pyperclip in the linked pull changes a line that detects the os environment from `if "Microsoft" in f.read():` to `if "microsoft" in f.read().lower():`, thus handling variance in the case of letters.

**Comment by jbrockmendel** [comment]
> though I'm not 100% certain what you mean by "headless system".

i was thinking of a machine that you ssh into (generally without a monitor attached).  when i do this i often get failures in the clipboard tests

**Comment by haleemur** [comment]
Today I installed pandas from source in a fresh virtual environment in wsl, and copy / paste worked. Closing the issue, as it seems i'll just have to update pandas when the next version is released.

**Comment by haleemur** [comment]
The issue was resolved with this change

```
-        with open("/proc/version") as f:
-            if "Microsoft" in f.read():
-                return init_wsl_clipboard()
+        if which("wslconfig.exe"):
+            return init_wsl_clipboard()
```
