### ISSUE TITLE
QST:hello all...i have a csv of about six years of records...the dates through out all years are a mess because of many different users throughout the years....would someone kindly help to transform all dates into one single format...your contribution will be greatkly appreciated since it is biomedical research

### ISSUE THREAD

**Issue by ptoru001** [pandas-dev/pandas#41054]
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [x] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
# Your code here, if applicable

```

**Comment by ptoru001** [comment]
pdx['date'] = pd.to_datetime(pdx['date'], format=('Y-%d-%m')) throws value error...and this is what the csv looks like
![Screen Shot 2021-04-20 at 9 58 07 AM](https://user-images.githubusercontent.com/63522254/115408514-ea32fb80-a1be-11eb-8c23-cf744041ad93.png)

**Comment by phofl** [comment]
Hi, if you think the ValueError is a bug on the pandas side, please provide a reproducible and minimal example (see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports). If this is a simple usage question then please ask the on stackoverflow.

You can look into the date_parser argument here https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

**Comment by phofl** [comment]
Please provide something reproducible

**Comment by phofl** [comment]
Going from your error message:

```
pdx = pd.DataFrame({"date": ['2015-08-27']})
pdx['date'] = pd.to_datetime(pdx['date'], format=('%Y-%m-%d'))
```

Switch m and d and it works

**Comment by phofl** [comment]
Closing as this is a UsageQuestion. Please ask them on stackoverflow

**Comment by phofl** [comment]
Please ping to reopen if you find a bug in the way to_datetime operates
