### ISSUE TITLE
Numpy Import Error

### ISSUE THREAD

**Issue by electromeow** [pandas-dev/pandas#41070]
Pandas frequently errors about importing NumPy. When I try to import pandas, it tries to import NumPy and creates an error.
I don't know why but when I delete venv folder and create a new venv and install pandas again, it automatically resolves but after 3-4 days, it throws an error about importing NumPy. There isn't a problem with the NumPy version because I don't manually install NumPy or any package with NumPy dependency before installing pandas. Anyway, I don't use another package using Numpy.
If you know what is the problem, please reply.

**Comment by MarcoGorelli** [comment]
> but after 3-4 days

what did you do in those 3-4 days?

**Comment by MarcoGorelli** [comment]
> Pandas frequently errors

Also, please show the error, we can't see your screen

**Comment by electromeow** [comment]
I don't have the error now, so I can't send it. But if I don't remember wrong, it was "no module called numpy.core.multiarray.math" or sth like that.
in that 3-4 days I didn't install any other packages. I don't use any package using NumPy except pandas.

**Comment by MarcoGorelli** [comment]
No worries - closing for now, next time it happens, please include a full traceback and we can take a look

**Comment by electromeow** [comment]
Traceback (most recent call last):
  File "/pathtomyproject/main.py", line 22, in <module>
    import pandas as pd
  File "/pathtomyproject/venv/lib/python3.9/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/pathtomyproject/venv/bin/python3"
  * The NumPy version is: "1.20.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
