### ISSUE TITLE
DOC/CI: fix doc build with Python 3.9

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#41096]
The doc build was failing on master (`/home/runner/work/pandas/pandas/doc/source/reference/api/pandas.Series.dt.rst: WARNING: document isn't included in any toctree`), which started when the environment switched to Python 3.9.

It is now pinned to Python 3.8 (https://github.com/pandas-dev/pandas/pull/41092), but we should fix the warning for Python 3.9, and unpin the environment.

cc @pandas-dev/pandas-docs

**Comment by simonjayhawkins** [comment]
@jorisvandenbossche changed the milestone since we want to do this before the 1.2.5 release.

**Comment by jorisvandenbossche** [comment]
To be clear, the docs are still building fine. I think it's OK if we need to keep the Python 3.8 pin on the 1.2.x branch?

**Comment by simonjayhawkins** [comment]
The thing is, since we are changing environment.yml just for ci, do we want that change in an actual release?

**Comment by jorisvandenbossche** [comment]
How does the environment.yml impact the release? (eg the file is not included in the sdist)

**Comment by simonjayhawkins** [comment]
> eg the file is not included in the sdist

didn't know that.

**Comment by simonjayhawkins** [comment]
> eg the file is not included in the sdist

didn't know that.

**Comment by simonjayhawkins** [comment]
> > eg the file is not included in the sdist
> 
> didn't know that.

removing the milestone

**Comment by phofl** [comment]
Lets track in #52513
