### ISSUE TITLE
Can this be a list instead?

### ISSUE THREAD

**Issue by duchai24** [pandas-dev/pandas#41116]
https://github.com/pandas-dev/pandas/blob/v1.2.4/pandas/io/json/_normalize.py#L137

Hi,

I'm trying to use json_normalize to flatten a complex dictionary where there are nestes dict and nested list. While the record_path accepts a list of strings, the record_prefix only accepts a single string, this does not allow me to set a different prefix in corresponding to each element in record_path. Can we allow record_prefix to be a list?

Thanks
Hai

**Comment by attack68** [comment]
Thanks Hai for the report. It would be helpful if your title could be more descriptive, and if possible to include an example or little more info that might help a potential developer of this feature.

**Comment by MarcoGorelli** [comment]
Hi @duchai24 - closing for now, will reopen if you include input + expected output
