### ISSUE TITLE
BUG: Unexpected behavior of groupby when a column has None values

### ISSUE THREAD

**Issue by aalloul** [pandas-dev/pandas#41119]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
# Your code here
import pandas as pd
df = pd.DataFrame(data=[
    {"a": 1, "b": None},
    {"a": 2, "b": None},
])
df.groupby(["a", "b"]).size() # returns Series([], dtype: int64)
df.drop_duplicates() # returns the dataframe itself
```

#### Problem description
The 2 rows in my dataframe are different and grouping on the 2 columns should thus not return an empty `Series`. 

Update: I observe the same behavior when I use np.nan` instead of `None`

#### Expected Output
```
a  b   
1  None    1
2  None    1
dtype: int64
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.9.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.14.225-121.357.amzn1.x86_64
Version          : #1 SMP Mon Mar 15 23:52:05 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.4
numpy            : 1.20.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 49.6.0.post20210108
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by asishm-wk** [comment]
`.groupby` has `dropna=True` as default - change that to `False`

**Comment by phofl** [comment]
Yes this is expected, as @asishm mentioned ``dropna=False`` is the solution

**Comment by rhshadrach** [comment]
Agree, @aalloul thanks for the report. Let us know if this doesn't suffice for you here and can reopen.

**Comment by aalloul** [comment]
Thanks a lot for your quick reply, I didn't see that option for `groupby` but it makes sense!
