### ISSUE TITLE
BUG: AttributeError: 'StringArray' object has no attribute 'tolist'

### ISSUE THREAD

**Issue by aiqc** [pandas-dev/pandas#41134]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of pandas.
- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```bash
$ pip show pandas

Name: pandas
Version: 1.2.4
```

```python
import pandas as pd
import numpy as np

lzt = ["a","b","c"]
arr = np.array(lzt)
df = pd.DataFrame(arr).astype('string')

srs = df[0]
u = srs.unique()


type(u)
<class 'pandas.core.arrays.string_.StringArray'>


u.dtype == 'string'
True


u.tolist()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'StringArray' object has no attribute 'tolist'
```

#### Problem description

So I tried changing my code to use `list(srs.unique())`, but then all of my numeric dtypes become unserializable for JSON.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.7.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.3.0
Version          : Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.4
numpy            : 1.18.5
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.2
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.17.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 2.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
</details>

**Comment by isaac-chung** [comment]
@aiqc Was able to use `json.dumps(list(srs.unique()))` which gave an output `'["a", "b", "c"]'`. I'm a bit confused by your reference to numeric dtypes when your example only had strings/list of strings. Does this resolve your issue?

**Comment by aiqc** [comment]
> @aiqc Was able to use `json.dumps(list(srs.unique()))` which gave an output `'["a", "b", "c"]'`. Does this resolve your issue?

I'd say it's not really resolved until StringArray has a `to_list()` method like the other dtypes. Part of making the new dtype feature complete.

> I'm a bit confused by your reference to numeric dtypes when your example only had strings/list of strings. 
I run many dtypes through `unique()`, not just strings.

**Comment by isaac-chung** [comment]
To add to your point, I spot-checked another class, and tried a something similar on Pandas 1.2.4 with `BooleanArray` class and grabbed the `unique()` from a DataFrame column. Found that when running `json.dumps(list(u))`
- if u is of `<class 'pandas.core.arrays.string_.StringArray'>`, the line runs without error
- if u is of `<class 'pandas.core.arrays.boolean.BooleanArray'>`, the line returns a not JSON serializable error

Both types do not have tolist() methods, like how the `numpy.ndarray` does.

**Comment by dsaxton** [comment]
@aiqc The `tolist` method is part of the `Series` and not the `PandasArray` API so this is behaving as expected.

Regarding data being JSON serializable you can pass a custom serializer to `cls` when using `json.dumps` to convert from `numpy` types to primitive Python types (there are probably several other ways to do this).

**Comment by mroeschke** [comment]
Yes this is expected as explained above and I don't think `tolist` is in scope for `PandasArray` therefore closing
