### ISSUE TITLE
BUG: Sympy can not handle Series as b in a*b

### ISSUE THREAD

**Issue by maxmcclorey** [pandas-dev/pandas#41144]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas
import sympy
scalar_float = 3.5
scalar_sympy = sympy.Rational(7, 2)
series_float = pandas.Series([3.5])
series_sympy = pandas.Series([sympy.Rational(7, 2)])
scalar_float * series_float  # Yields a single-element float series
series_float * scalar_float  # Yields a single-element float series
scalar_sympy * series_sympy  # YIELDS A SCALAR FLOAT
series_sympy * scalar_sympy  # Yields a single-element sympy Rational series
```

#### Problem description

When doing arithmetic between a scalar `sympy Rational` value and a single-element `pandas Series`, if the scalar value is on the left side of the arithmetic equation the result is not a single-element `Series` as you would expect, but is instead a scalar value. Also, the `sympy Rational` gets evaluated into a floating point number.

See the `ipython` output below:

```
In [1]: import pandas

In [2]: import sympy

In [3]: scalar_float = 3.5

In [4]: scalar_sympy = sympy.Rational(7, 2)

In [5]: series_float = pandas.Series([3.5])

In [6]: series_sympy = pandas.Series([sympy.Rational(7, 2)])

In [7]: scalar_float * series_float
Out[7]:
0    12.25  # <---------Correct, as expected
dtype: float64

In [8]: series_float * scalar_float
Out[8]:
0    12.25  # <---------Correct, as expected
dtype: float64

In [9]: scalar_sympy * series_sympy
Out[9]: 12.2500000000000  # <-------------INCORRECT

In [10]: series_sympy * scalar_sympy
Out[10]:
0    49/4  # <---------Correct, as expected
dtype: object
```

#### Expected Output

I would expect the output of `scalar_sympy * series_sympy` to be equal to `series_sympy * scalar_sympy`

#### Output of ``pd.show_versions()``

<details>

In [8]: pandas.show_versions()
/Users/maxmcclorey/Documents/workspace/captivateiq/venv/lib/python3.8/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.8.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.3.0
Version          : Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.4
numpy            : 1.19.2
pytz             : 2021.1
dateutil         : 2.8.0
pip              : 20.3.3
setuptools       : 49.2.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : 0.9.3
psycopg2         : 2.8.2 (dt dec pq3 ext lo64)
jinja2           : None
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.13
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by jreback** [comment]
this is almost certainly an issue on sympy itself not pandas

**Comment by phofl** [comment]
Can confirm, sympy can not deal with a Series as b in ``a*b``. Not a pandas issue

**Comment by phofl** [comment]
Closing as this is not a pandas issue. You have to ask in the sympy issue tracker
