### ISSUE TITLE
BUG: index.isin working with RangeIndex

### ISSUE THREAD

**Issue by attack68** [pandas-dev/pandas#41151]
```
RangeIndex(start=0, stop=2).isin(RangeIndex(start=0, stop=1))  # <- TypeError

Index([0, 1, 2]).isin(RangeIndex(start=0, stop=1))             # <- TypeError

RangeIndex(start=0, stop=2).isin(Index([0, 1]))                # <- OK

Index([0, 1, 2]).isin(Index([0, 1]))                           # <- OK
```
Have only tested on master. Not yet on 1.2.4

**Comment by phofl** [comment]
This works on 1.2.4, so looks like a regression. Could you try on your side on 1.2.4 just to be sure, that I don't miss anything? Labeling as regression for now

**Comment by phofl** [comment]
If I understand you correctly the following

```python
RangeIndex(start=0, stop=2).isin(RangeIndex(start=0, stop=1))
```

is sufficient to reproduce? If this is true, could you update your example a bit?

**Comment by attack68** [comment]
Have updated, it seems passing a range index to the isin() method is the problem.
