### ISSUE TITLE
BUG: Unexpected output of `to_json` for `complex` data

### ISSUE THREAD

**Issue by karalekas** [pandas-dev/pandas#41174]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
s = pd.Series({0: 0+2j, 1: 3+4j, 2: 5+6j})
s.to_json()
```

#### Problem description

Calling `to_json()` on a `DataFrame` or `Series` with `complex` data gives unexpected results. Running the above Code Sample gives the following output:

```
'{"0":{"imag":2.0},"1":{"imag":4.0},"2":{"imag":6.0}}'
```

This is a problem both because (1) the output is not terribly useful (the real part is just dropped), and (2) according to [the docs](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#fallback-behavior) this should raise an error (see the following snippet copied from the linked docs page):

```python
>>> DataFrame([1.0, 2.0, complex(1.0, 2.0)]).to_json()  # raises
RuntimeError: Unhandled numpy dtype 15
```

#### Expected Output

According to the docs, this should at least raise a `RuntimeError`. However, it would be nice for this to actually be supported.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 0158382ac8459a197d088790fd45f433c83c25c8
python           : 3.8.5.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.1.0
Version          : Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.0.dev0+1441.g0158382ac8
numpy            : 1.20.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 47.1.0
Cython           : 0.29.23
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.22.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by ZurMaD** [comment]
I think here is the missing error raise

https://github.com/pandas-dev/pandas/blob/070341cf4958652343f798c74c04a8c15de2fd04/pandas/io/json/_json.py#L582-L588

**Comment by ZurMaD** [comment]
By default of `to_json()` is

https://github.com/pandas-dev/pandas/blob/070341cf4958652343f798c74c04a8c15de2fd04/pandas/io/json/_json.py#L78-L92

**Comment by mroeschke** [comment]
I'm getting a more useful result on master now that could use tests to nail this behavior down

```
In [13]: import pandas as pd
    ...: s = pd.Series({0: 0+2j, 1: 3+4j, 2: 5+6j})
    ...: s.to_json()
Out[13]: '{"0":{"imag":2.0,"real":0.0},"1":{"imag":4.0,"real":3.0},"2":{"imag":6.0,"real":5.0}}'
```

**Comment by lorenzophys** [comment]
@mroeschke I would like to write the tests for this behavior. Being my first issue with this codebase, tests related to this issue will go in `pandas/tests/io/json/test_pandas.py`? Or there's a more appropriate place?
