### ISSUE TITLE
ENH: Check if individual value is pd.NA

### ISSUE THREAD

**Issue by bandlerr** [pandas-dev/pandas#41198]
#### Is your feature request related to a problem?

Currently, according to Pandas documentation, dataframe.isna() returns a same-size dataframe object (or Series) containing boolean values for each element indicating whether that element is or is not a pd.NA. However, in pandas current implementation, there is no way to clearly check if a single value in a dataFrame (or Series) is NA. For example: If I want to iterate over a Series, and perform some operation to each element, but ignore any pd.NA elements, there is no intuitive way to check for that. Without running into errors such as "boolean value of NA is ambiguous".

#### Describe the solution you'd like

a pandas function which simply accepts any entity and returns whether or not it is a pd.NA object, or direct implementation for the == or is operator for pd.NA

#### Describe alternatives you've considered

I am aware that workarounds for this exist, such as using applyMap() or Map() with na_action='ignore', but that doesn't mean that this functionality I am proposing shouldn't also exist. The current dataframe.isna() function could be used to solve this issue as well, but I would have to find all indices for True in the returned dataframe, which is not an elegant solution, and is also computationally expensive.

```python

data = some_pandas_series
for i in range(len(data)):
    print(data[i].isna())
##or some other function which would achieve the same results in this way

```
this should iterate through the Series and print True or False to the screen indicating whether or not each element is pd.NA

**Comment by jreback** [comment]
this is not idiomatic usage and should not be encouraged

-1 as this is the entire point of raising in __bool__ as do other vectorized containers (numpy)

**Comment by mzeitlin11** [comment]
Agree with @jreback here. But also doesn't `pd.isna()` do exactly what you want here? eg `pd.isna(pd.NA)` gives True

**Comment by bandlerr** [comment]
oh wow, the function already exists. I was not aware of this. Also @jreback I agree with you that this should generally be avoided. Anyways, I am closing the issue regardless because @mzeitlin11 has shown that the functionality already exists. Thanks to you both for quick response.
