### ISSUE TITLE
QST: single MultiIndex.from_tuples errors

### ISSUE THREAD

**Issue by Leejung8763** [pandas-dev/pandas#41191]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
pd.MultiIndex.from_tuples(("2018", "11"))
```

#### Problem description
I want to make Multiple index to append my dataframe.
So, I used those codes and get something different with my think

#### Expected Output
I think 
MultiIndex([('2018', '11'),
           )
but, I got 
MultiIndex([('2', '0'),
            ('1', '1')],
           )
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.7.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-693.11.6.el7.x86_64
Version          : #1 SMP Thu Jan 4 01:06:37 UTC 2018
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : ko_KR.UTF-8
LOCALE           : ko_KR.UTF-8

pandas           : 1.2.4
numpy            : 1.19.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 49.2.0.post20200714
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.4.0
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.16.1
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.2
numexpr          : None
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : 2.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.5.3
sqlalchemy       : 1.3.18
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
numba            : 0.51.2

</details>

**Comment by Liam3851** [comment]
MultiIndex.from_tuples takes a sequence of sequences, you only provided 1 tuple. You call should have been (note the list brackets)

```python
pd.MultiIndex.from_tuples([("2018", "11")])
```

As it was, from_tuples interpreted your tuple as the outer sequence, and the strings themselves (which are iterable/indexable) as the inner sequences.
