### ISSUE TITLE
QST: ERROR in Jupyter using pandas module: ImportError: cannot import name 'np_version_under1p17' from 'pandas.compat.numpy' (unknown location)

### ISSUE THREAD

**Issue by NocaoBr** [pandas-dev/pandas#41206]
Question about  ERROR pandas
-------

English:
Guys I was trying to learn a program with Jupyter, but when I installed pandas at
'pip install pandas' please worked, but I used (import pandas as pd) it on jupyter and I give the following  error message:

```python
#  ImportError                               Traceback (most recent call last)
<ipython-input-35-33fbe9d324d8> in <module>
----> 1 import pandas as pd
      2 
      3 df = pd.read_excel(r'C:\Users\USER\Desktop\Vendas - Dez.xlsx')
      4 df.corr()

~\anaconda3\lib\site-packages\pandas\__init__.py in <module>
     20 
     21 # numpy compat
---> 22 from pandas.compat.numpy import (
     23     np_version_under1p17 as _np_version_under1p17,
     24     np_version_under1p18 as _np_version_under1p18,

ImportError: cannot import name 'np_version_under1p17' from 'pandas.compat.numpy' (unknown location)"


```

=============================================
Portuguese:
Cara eu estava tentando aprender a programar com o Jupyter, mas quando instalei o pandas pelo 
'pip install pandas' pareceu dar certo, mas fui usar (import pandas as pd) no jupyter e da a seguinte mensagem:

```python

"ImportError                               Traceback (most recent call last)
<ipython-input-35-33fbe9d324d8> in <module>
----> 1 import pandas as pd
      2 
      3 df = pd.read_excel(r'C:\Users\USER\Desktop\Vendas - Dez.xlsx')
      4 df.corr()

~\anaconda3\lib\site-packages\pandas\__init__.py in <module>
     20 
     21 # numpy compat
---> 22 from pandas.compat.numpy import (
     23     np_version_under1p17 as _np_version_under1p17,
     24     np_version_under1p18 as _np_version_under1p18,

ImportError: cannot import name 'np_version_under1p17' from 'pandas.compat.numpy' (unknown location)"


```

![Sem título](https://user-images.githubusercontent.com/83371463/116465142-36c3aa00-a843-11eb-9bad-e4be302e4f2f.png)

----------
HELP PLEASE GUYS!!!!!

**Comment by NocaoBr** [comment]
I already uninstall pandas and install pandas three times.

**Comment by phofl** [comment]
Hi,

please show pd.show_versions()

**Comment by NocaoBr** [comment]
> Oi,
> 
> Você poderia descrever como configurou seu ambiente, incluindo qual versão do pandas você usou?

Hello, I am just install pandas with 'pip install pandas' + 'pip3 install pandas' + 'pip install numpy' in the Anaconda prompt.
My version in the pandas 1.2.4

I am just write the command 'import pandas as pd' and i think that is a error from Jupyter.

U can help-me?
![Sem título](https://user-images.githubusercontent.com/83371463/116471136-b4d77f00-a84a-11eb-9bf9-9a183e04df86.png)

Is as maybe installation not ocorreced well for the jupyter

**Comment by NocaoBr** [comment]
> Eu já desinstalo o pandas e instalo o pandas três vezes.

I too open the archive where the jupyter not find. 
AND IT HAS THE 'np_version_under1p17'


![Sem título](https://user-images.githubusercontent.com/83371463/116473339-71324480-a84d-11eb-84f1-1a0ae63bfeb5.png)


So it is a error from jupyter?

**Comment by mroeschke** [comment]
Thanks for the report, but it doesn't appear this is a pandas issue from the report so closing.
