### ISSUE TITLE
BUG: Dataframe structure is incompatible across minor versions 1.0.5 -> 1.1.0+, violating semver rules

### ISSUE THREAD

**Issue by tigerhawkvok** [pandas-dev/pandas#41208]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

1. Create a DF in Pandas 1.1.0+

```python
import pandas as pd
dfContents = [{"foo": 1.1, "bar": True, "baz": "test1"}, {"foo":5.5, "bar": False, "baz": "test2"}]
df = pd.DataFrame(dfContents)
print(df.head())
df.to_pickle("bugReportSample.pkl", protocol= 4)
```

![image](https://user-images.githubusercontent.com/165937/116479257-2eb03e00-a834-11eb-98b5-a4ee0afe48a8.png)

2. Load in a different computer/system/subsystem with a different Pandas version like 1.0.5

```python
import pandas as pd
df = pd.read_pickle("bugReportSample.pkl")
print(df.head())
```

![image](https://user-images.githubusercontent.com/165937/116478360-cf9df980-a832-11eb-89c7-9ba309d21ce6.png)

#### Problem description

A core objects structure should be compatible across minor versions; which [via the semver standard](https://semver.org/#summary)

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> MAJOR version when you make incompatible API changes,
> ***MINOR version when you add functionality in a backwards compatible manner, and*** \[emphasis added\]
> PATCH version when you make backwards compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

#### Expected Output

A serialized dataframe should be compatible across versions. 

- Serialization to basic objects should be backwards compatible, in such a way that all reasonable serializations should "just work" (eg, joblib, pickle, hdf5 ...)
- If it cannot be in all cases, native write functions like `DataFrame.to_pickle()` should handle the backwards-compatibility work, at least via flag. 
- If it cannot be at all, the _major_ version should be incremented as per semver, since this breaks backwards compatibility. 
- If the major version cannot be incremented, Pandas shouldn't pretend to follow semantic versioning and should use a version number that is plainly and obviously not semantic versioning, like Ubuntu's whimsical named versions.

#### Output of ``pd.show_versions()``

<details>

Writer system:

```
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.8.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.4.0-19041-Microsoft
Version          : #488-Microsoft Mon Sep 01 13:43:00 PST 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.4
numpy            : 1.20.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 54.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
>>>
```

Reader system:

```
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.5
numpy            : 1.19.0
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 47.1.0
Cython           : None
pytest           : 5.4.3
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.18.1
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fastparquet      : 0.4.0
gcsfs            : None
lxml.etree       : 4.6.1
matplotlib       : 3.2.2
numexpr          : None
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : 3.0.0
pytables         : None
pytest           : 5.4.3
pyxlsb           : None
s3fs             : None
scipy            : 1.5.1
sqlalchemy       : 1.3.18
tables           : None
tabulate         : 0.8.7
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
numba            : 0.50.1
```

</details>

**Comment by jreback** [comment]
there is no guarantee of forwards compatibility, backwards yes (read in 1.1.x but created in 1.0.x)
