### ISSUE TITLE
BUG: Cannot change the data type in the data frame

### ISSUE THREAD

**Issue by Leejung8763** [pandas-dev/pandas#41216]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
df1 = pd.DataFrame(np.arange(16).reshape(4,4),
                index = [[1,1,2,2],['s1','s2','s1','s2']],
                columns = [['apple','apple','banana','banana'], ['price','qty','price','qty']],
               )
# first
df1["apple"]["price"] = [12, 16, 15, 18]
# second
df1["apple"]["price"] = ["a", "b", "c", "d"]

```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]
first code(change with numeric data)'s output is exactly same with what I think. 
but when I used second one(change with string data), there's nothing change.
I know It can solve with code df1.loc[:, ("apple", "price")] = ["a", "b", "c", "d"], but I just wonder why second one is impossible.

#### Expected Output
		apple	banana
price	qty	price	qty
1	s1	a	1	2	3
s2	16	b	6	7
2	s1	c	9	10	11
s2	18	d	14	15

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.7.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-693.11.6.el7.x86_64
Version          : #1 SMP Thu Jan 4 01:06:37 UTC 2018
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : ko_KR.UTF-8
LOCALE           : ko_KR.UTF-8

pandas           : 1.2.4
numpy            : 1.19.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 49.2.0.post20200714
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.4.0
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.16.1
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.2
numexpr          : None
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : 2.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.5.3
sqlalchemy       : 1.3.18
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
numba            : 0.51.2

</details>

**Comment by MarcoGorelli** [comment]
Hi @Leejung8763 - did you read the page which the warning which you should've got linked you to? https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

**Comment by phofl** [comment]
As @MarcoGorelli pointed out, this is the expected behavior. Chained indexing is tricky and I always try to avoid this.

If you change the dtype, this makes a copy, hence the underlying DataFrame is not modified. Loc is the recommended way to go here.

**Comment by Leejung8763** [comment]
> Hi @Leejung8763 - did you read the page which the warning which you should've got linked you to? https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Oh... I've never seen it before. I'm appreciate your answer

> As @MarcoGorelli pointed out, this is the expected behavior. Chained indexing is tricky and I always try to avoid this.
> 
> If you change the dtype, this makes a copy, hence the underlying DataFrame is not modified. Loc is the recommended way to go here.

Ah.. Now I need to get used to using .loc
