### ISSUE TITLE
DOC: Cannot acces to index value when using 'key' function in 'Sort_index'

### ISSUE THREAD

**Issue by MiguelonGonzalez** [pandas-dev/pandas#41214]
[https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_index.html]

#### Documentation problem

[When setting  'key argument' in sort_index function (DataFrame object method), I cannot acces to index value because it's consider as an object. I haven't found the way of extracting Index' object value. I do not know if I'm wrong or a new Index method would be required for accesing that value]

#### Suggested fix for documentation

[Here I attached some code to let me explain:
df = pd.DataFrame({"a": [1, 2, 3, 4]}, index=['(0-1)', '(1-2)', '(2-3)', '(3-4)'])
df.sort_index(key=lambda x: int(x[1]))

Useful information: https://stackoverflow.com/questions/64160980/key-function-when-using-sort-index]

**Comment by attack68** [comment]
The sort_index method seems to have this well documented:

```
key : callable, optional
If not None, apply the key function to the index values before sorting. 
This is similar to the key argument in the builtin sorted() function, with 
the notable difference that this key function should be vectorized. 
It should expect an Index and return an Index of the same shape. For 
MultiIndex inputs, the key is applied per level.
```

Your `key` callable is not vectorised, it operates element-wise.
Additionally your example is poorly chosen since the sort order returned is the same as input but consider instead:

```
>>> df = pd.DataFrame({"a": [1, 2, 3, 4]}, index=['(0-1)', '(2-2)', '(1-3)', '(3-4)'])
>>> print(df.sort_index(key=lambda x: x.str[1].astype(int)))
       a
(0-1)  1
(1-3)  3
(2-2)  2
(3-4)  4
```

the `x.str[1].astype(int)` is a vectorised way of what you were trying to do and has no errors.

**Comment by MiguelonGonzalez** [comment]
Perfectly explained. Thank you very much @attack68 
My code was just an example.
