### ISSUE TITLE
BUG: Series.replace(List, ...) changes the dtype of the Series to object

### ISSUE THREAD

**Issue by EdGaere** [pandas-dev/pandas#41215]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas. (v1.2.4)

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

There is a bug when calling Series.replace(List, ...), the Series gets converted to dtype 'object', which is incorrect.

Let's start with a simple example that works as expected. 

```
df = pd.DataFrame({'a': ['abc', 'def']}, dtype="string") 

s0 = df["a"].replace('abc', 'xyz')
print(s0)
```

The output is as expected, and Series has maintained the type __string__:
```
0  xyz
1  def
Name: a, dtype: string
```

But when calling Series.replace(List, ...), Series gets converted to dtype __object__, which is incorrect.
```
s1 = df["a"].replace(['abc', 'any other string'], "xyz" )
print(s1)
```

Output:
```
0  xyz
1  def
Name: a, dtype: object
```

#### Problem description

Datatype of Series should not change when using a different argument to Series.replace().

#### Expected Output

```
0  xyz
1  def
Name: a, dtype: string
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.8.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
Version          : Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.2.4
numpy            : 1.19.4
pytz             : 2020.4
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 56.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.2
sqlalchemy       : None
tables           : None
tabulate         : 0.8.7
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by mzeitlin11** [comment]
Thanks for the report @EdGaere! Persists on master, probably same underlying issue as #40732
