### ISSUE TITLE
API: SeriesGroupBy.product with numeric_only and empty non-numeric data

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#41291]
By default numeric_only=True.  But when there are no numeric columns and we raise DataError, the fallback ignores numeric_only.  So we end up getting wonky results.

Below I think that gb1 raising is correct, gb3 should raise, gb2 and gb4 should return empty DataFrames.  cc @jreback @jorisvandenbossche @TomAugspurger @WillAyd 

```
dti = pd.date_range("2016-01-01", periods=3)
ser = pd.Series(dti)
df = ser.to_frame()

gb1 = ser.groupby([0, 0, 0])
gb2 = df.groupby(gb1.grouper)
gb3 = ser[:0].groupby([])
gb4 = df[:0].groupby([])

>>> gb1.prod()
TypeError: 'DatetimeArray' does not implement reduction 'prod'

>>> gb2.prod()  # <-float64
    0
0 NaN

>>> gb3.prod()
Series([], dtype: datetime64[ns])

>>> gb4.prod()  # <- dt64
Empty DataFrame
Columns: [0]
Index: []
```

**Comment by jorisvandenbossche** [comment]
> Below I think that gb1 raising is correct, gb3 should raise, gb2 and gb4 should return empty DataFrames

That sounds correct to me, on first sight. 
This is also consistent with non-grouped Series/DataFrame (`ser.prod()` raises, `df.prod()` gives emtpy series)

**Comment by jbrockmendel** [comment]
Fixing this segues into another issue:  NDFrame reductions have `numeric_only` kwarg default to None, and for Series `numeric_only=True` (i.e. user explicitly passed it) raises NotImplementedError.  GroupBy reductions have numeric_only default to True, don't have a None option.

So for SeriesGroupBy, if we match the Series behavior without changing the default kwarg, then `SeriesGroupBy[dt64].prod()` will raise `NotImplementedError`.  I think better to change the default but (for now) only for SeriesGroupBy, so we only get NotImplementedError if numeric_only is explicitly passed, and TypeError otherwise.
