### ISSUE TITLE
DEPR: pd.Grouper?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#41297]
I guess the point of Grouper is to allow for finer customization of groupby behavior?  My _hope_ is that it is a historical artifact and we can now do anything we need without it.  Any idea if this is the case?

**Comment by jreback** [comment]
the main use of this was to do grouping and resampling simultaneously but we can easily use groupby..resample

so maybe it's possible to deprecate this

**Comment by rhshadrach** [comment]
Searching SO, I'm seeing a lot of questions of the form "How do I do this with pd.Grouper?" and the answer does not use pd.Grouper. I haven't found a question that can't be done with resample.

+1 on deprecating

**Comment by NowanIlfideme** [comment]
What the `.groupby().resample()` examples miss are cases when you want to pass "grouping arguments" from one function to another. There isn't a clean way to do that besides `pd.Grouper` and strings within a list, as far as I'm aware - everything else would need to either specifically check for frequency resampling, or create an auxiliary column of the new periodicity. I'd be glad to be proven wrong. 😃

**Comment by jbrockmendel** [comment]
@NowanIlfideme thanks for clarifying this for me!
