### ISSUE TITLE
BUG: Incorrect parsing csv header line if no separator in the end

### ISSUE THREAD

**Issue by dimka11** [pandas-dev/pandas#41304]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

```python

import pandas as pd
from io import StringIO

data = """
"date_time";"T";"Po"
"04.05.2021 09:00";"9.8";"759.0";
"""

df = pd.read_csv(StringIO(data), sep=';',index_col=0)

df['T']

df.head(1)

```

#### Problem description

When there is no separator at the end of the header line, pandas seems like skip first column (T) and shows second column instead.

```python

df['T']
df.loc[:,'T']

```
**Output:**
```
04.05.2021 09:00    759.0
Name: T, dtype: float64
```

**Expected:**
 (as df.iloc[0,0] give 9.8):
```
Местное время в Омске / им. Д. М. Карбышева (аэропорт)
04.05.2021 09:00    9.8
Name: T, dtype: float64
```
After I add ";" separator after "sss" bug disappeared, df.iloc[0,0] output is same in both case.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : b5958ee1999e9aead1938c0bba2b674378807b3d
python           : 3.6.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.21354
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.1.5
numpy            : 1.17.4
pytz             : 2018.9
dateutil         : 2.8.1
pip              : 19.0.3
setuptools       : 42.0.1
Cython           : 0.29.21
pytest           : 6.2.3
hypothesis       : None
sphinx           : 3.5.4
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10
IPython          : 7.5.0
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.3.1
fsspec           : 0.6.1
fastparquet      : None
gcsfs            : 0.5.0
matplotlib       : 3.1.2
numexpr          : None
odfpy            : None
openpyxl         : 2.6.1
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.2.1
sqlalchemy       : 1.2.18
tables           : None
tabulate         : None
xarray           : 0.14.1
xlrd             : 1.2.0
xlwt             : None
numba            : 0.48.0

</details>

**Comment by erictzimas** [comment]
Could somebody guide me on where to start with this, i am new to contributing, thank you in advance.

**Comment by phofl** [comment]
I am getting 

```
Traceback (most recent call last):
  File "/home/developer/.config/JetBrains/PyCharm2021.1/scratches/scratch_4.py", line 564, in <module>
    df = pd.read_csv(StringIO(data), sep=';', skiprows=6, index_col=0)
  File "/home/developer/PycharmProjects/pandas/pandas/io/parsers/readers.py", line 552, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/developer/PycharmProjects/pandas/pandas/io/parsers/readers.py", line 465, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/developer/PycharmProjects/pandas/pandas/io/parsers/readers.py", line 762, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/developer/PycharmProjects/pandas/pandas/io/parsers/readers.py", line 991, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/developer/PycharmProjects/pandas/pandas/io/parsers/c_parser_wrapper.py", line 57, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 554, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

```

```
data = """
"Местное время в Омске / им. Д. М. Карбышева (аэропорт)";"T";"Po";"P";"Pa";"U";"DD";"Ff";"ff10";"ff3";"N";"WW";"W1";"W2";"Tn";"Tx";"Cl";"Nh";"H";"Cm";"Ch";"VV";"Td";"RRR";"tR";"E";"Tg";"E'";"sss";
"04.05.2021 09:00";"9.8";"759.0";"";"";"68";"Ветер, дующий с запада";"3";"";"";"Облаков нет.";" ";"";"";"-0.3";"";"";"";"";"";"";"20.0";"";"Осадков нет";"12";"";"";"";"";
"""

df = pd.read_csv(StringIO(data), sep=';', skiprows=6, index_col=0)
```

So can not reproduce. Please provide something which is minimal, reproducible and copy and pastable. see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by phofl** [comment]
@erictzimas

I would recommend searching something labeled as good first issue, if you are new. The IO csv code is quite complex, so don't know if this is the best place to start.

**Comment by dimka11** [comment]
@phofl just remove skiprows and the behavior will be as I did write. I can't add first 6 lines, because they contained # mark and it сonflicts with markdown here.

**Comment by phofl** [comment]
Is this the minimal example to reproduce? If you can further trim this down please do so.

**Comment by phofl** [comment]
Executing 
```
df = pd.read_csv(StringIO(data), sep=';', index_col=0)
```
returns

```
                                                      T  ...  Unnamed: 29
Местное время в Омске / им. Д. М. Карбышева (аэ...       ...             
04.05.2021 09:00                                    9.8  ...          NaN

[1 rows x 29 columns]
```
 so can not reproduce with this either

**Comment by dimka11** [comment]
@phofl you can access first column, only as df.iloc[0,0], if write df['T'] or df.loc[:,'T'] there output of second column, not first as expected.

**Comment by phofl** [comment]
Please provide a minimal and reproducible example, which shows the error explicitly and then show your expected result.

**Comment by dimka11** [comment]
@phofl 

```python

import pandas as pd
from io import StringIO

data = """
"Местное время в Омске / им. Д. М. Карбышева (аэропорт)";"T";"Po";"P";"Pa";"U";"DD";"Ff";"ff10";"ff3";"N";"WW";"W1";"W2";"Tn";"Tx";"Cl";"Nh";"H";"Cm";"Ch";"VV";"Td";"RRR";"tR";"E";"Tg";"E'";"sss"
"04.05.2021 09:00";"9.8";"759.0";"";"";"68";"Ветер, дующий с запада";"3";"";"";"Облаков нет.";" ";"";"";"-0.3";"";"";"";"";"";"";"20.0";"";"Осадков нет";"12";"";"";"";"";
"""

df = pd.read_csv(StringIO(data), sep=';',index_col=0)

df['T']
df.loc[:,'T']

```
Output:

04.05.2021 09:00    759.0
Name: T, dtype: float64


Expected: (as df.iloc[0,0] give 9.8):

Местное время в Омске / им. Д. М. Карбышева (аэропорт)
04.05.2021 09:00    9.8
Name: T, dtype: float64

After I add ";" separator after "sss" bug disappeared

**Comment by dimka11** [comment]
@phofl no, I did edit first post

**Comment by phofl** [comment]
Thx, this is something we can work with

**Comment by phofl** [comment]
I am not 100% sure if I understand you correctly, but the following happens here:

Your column names are shorter than your data. When index_col=0 is set the first column is interpreted as index. If your names have the same length as your data, the first name is the index name. If your names are shorter than the data, the index has no name and all names are used as column names -> There happens a "shift".


```
data = """
"date_time";"T";"Po"
"04.05.2021 09:00";"9.8";"759.0"
"""

df = pd.read_csv(StringIO(data), sep=';', index_col=0)
```

I think this returns your expected result?

```
                    T     Po
date_time                   
04.05.2021 09:00  9.8  759.0
```

Please note that I have removed the trailing separator in the data, leading to equal length in names and keys. Adding a trailing separator to the names would have the same effect

**Comment by phofl** [comment]
Does this solve your issue?

**Comment by phofl** [comment]
Closing for now. Please ping to reopen if this does not solve your issue
