### ISSUE TITLE
Non-Reducing Return Values in Rolling .apply

### ISSUE THREAD

**Issue by hayd** [pandas-dev/pandas#4130]
related #2813, #4964 (somewhat)

At the moment rolling_apply (et al) the passed function has to return a value (unlike apply which can return a Series and overall return a DataFrame).

If you could pass it a Series you could, for example, do this:

```
from pandas.core.algorithms import value_counts
s = Series([1, 1, 2, 3, 1, 2, 3, 2, 1])

pd.rolling_apply(s, 3, value_counts)
```

from the [mailing list](https://groups.google.com/forum/#!topic/pydata/I7YET3egFtY).

**Comment by WillAyd** [comment]
A series can be produced now via the keyword argument `raw=False`, though the original issue does not work on master with a relatively cryptic message:

```python
>>> 
s.rolling(3).apply(lambda x: x[:2], raw=False) 
TypeError: cannot convert the series to <class 'float'>
```

Not sure it is even feasible to support non-reducing functions like `value_counts` provided in the original message, but keeping open in case others have an idea on how to support

**Comment by mroeschke** [comment]
Looks like there hasn't been a lot of demand for this feature and would increase the complexity greatly if apply could return arbitrary shaped results for each window, so closing for now. Can reopen if there's more interest
