### ISSUE TITLE
CI: numpy doesn't build on python 3.10beta

### ISSUE THREAD

**Issue by ShaharNaveh** [pandas-dev/pandas#41313]
The CI is failing is only failing for the "Install dependencies" phase for ```python 3.10```

Saw in:
- https://github.com/pandas-dev/pandas/pull/41308/checks?check_run_id=2501536827
- https://github.com/pandas-dev/pandas/pull/41307/checks?check_run_id=2501358707
- https://github.com/pandas-dev/pandas/pull/41269/checks?check_run_id=2498810271

**Comment by jreback** [comment]
cc @fangchenli 

I think for now we could fix the python version (e.g. go back to the alpha release)? or pin numpy?

**Comment by jorisvandenbossche** [comment]
So it started to fail when Python was updated from 3.10-alpha7 to 3.10beta1

The failure happens when building a numpy wheel from the git checkout (`pip install git+https://github.com/numpy/numpy.git`)

**Comment by Dr-Irv** [comment]
I did a push late yesterday of a merge with master of one of my PRs and it had no errors, so I think #41315 fixed it.

**Comment by jreback** [comment]
right we pinned this to the alpha build - so leaving this open until later builds are resolved (but CI green now)

**Comment by jorisvandenbossche** [comment]
To be clear, that PR didn't "fix" it, it only pinned python temporarily to an older, working version. 

Now, the actual issue in numpy seems to be fixed as well: https://github.com/numpy/numpy/issues/18907, so we can probably revert the pinning already.

**Comment by jorisvandenbossche** [comment]
-> https://github.com/pandas-dev/pandas/pull/41328
