### ISSUE TITLE
QST: Why is `FutureWarning: Index.__and__ operating as a set operation is deprecated`? 

### ISSUE THREAD

**Issue by jolespin** [pandas-dev/pandas#41323]
- [ ] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

I noticed that set comprehension of pandas index are being deprecated.  These are extremely useful.  I was wondering what the rationale for this change is amongst the developers? 

This functionality is extremely useful:
```python
X_A = # Some dataframe (n,m)
X_B = # Some other dataframe (n,q)
X_C = X_A.loc[X_A.columns & X_B.columns]

features = X_A.columns | X_B.columns | X_C.columns

```

**Comment by jbrockmendel** [comment]
You can still do `features = X_A.columns.intersection(X_B.columns).intersection(X_C.columns)`

The motivation was internal consistency between Index methods with their Series/DataFrame counterparts

**Comment by jolespin** [comment]
Got it, so because of the following: 

```
a =  df_annotations[("nr","sseqid")].iloc[:10].dropna()
a = pd.Series({'g0': 'XP_027044459.1',
 'g1': 'PFX28884.1',
 'g10': 'XP_022785414.1',
 'g100': 'XP_020630778.1',
 'g1000': 'XP_026478365.1',})
b = a.iloc[1:]

a.index & b.index
# Index(['g1', 'g10', 'g100', 'g1000'], dtype='object')

a & b
# TypeError: unsupported operand type(s) for &: 'str' and 'bool'
```

This makes sense.  I can work on a custom `FeatureIndex` class that inherits from `pd.Index` to retain specific functionalities and override the set methods. 

Are there any base classes you recommend to use?

**Comment by jbrockmendel** [comment]
> Are there any base classes you recommend to use?

I wouldn't recommend doing this at all.  pandas has decent support for custom subclasses of Series and DataFrame, but very limited support for custom Index subclasses.  

If you must, it depends on what dtype your Index has.  If you're only working with object dtype, then just Index.
