### ISSUE TITLE
ENH: API for Accessing Underlying Arrays of a DataFrame

### ISSUE THREAD

**Issue by Alipescapital** [pandas-dev/pandas#41350]
We have many use-cases where we want to access the underlying column of a `DataFrame`, either as an Array or `numpy.ndarray`, and right now we have to go through a Series to do so:
```python
df["columnname"].array
df["columnname"].to_numpy()
```
Going through a Series has unwanted large overhead for us (ignoring the internal `_item_cache`), so it would be nice to be able to go directly to an `Array `or `numpy.ndarray`.  If we want fast access we right now have to do:
```
df._mgr.iget_values(df.columns.get_loc("columnname"))
```

**Comment by rhshadrach** [comment]
Can you give some more detail here? A reproducible example and what  the overhead you observe is.

```
size = 100_000_000
%memit df = pd.DataFrame({'a': range(size), 'b': range(size)})
# peak memory: 3147.55 MiB, increment: 3012.55 MiB
%memit df["a"].to_numpy()
# peak memory: 1661.55 MiB, increment: 0.48 MiB

%timeit df["a"].to_numpy()
# 2.93 µs ± 5.01 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

**Comment by mroeschke** [comment]
Thanks for the suggestion but this enhancement request need a little more scoping to be actionable for feedback from the team so closing. Happy to reopen when we have an API proposal and background regarding performance.
