### ISSUE TITLE
REGR: Change to Series[dt64/td64].astype("string")` behavior on master

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#41409]
xref https://github.com/pandas-dev/pandas/pull/38562#issuecomment-836438843 cc @jbrockmendel 

old behaviour

```
>>> pd.__version__
'1.2.4'
>>> 
>>> tdi = pd.timedelta_range("1 Day", periods=3)
>>> ser = pd.Series(tdi)
>>> ser
0   1 days
1   2 days
2   3 days
dtype: timedelta64[ns]
>>> ser.astype("string")
0    1 days
1    2 days
2    3 days
dtype: string
>>> 
>>> dti = pd.date_range("2021", periods=3)
>>> ser = pd.Series(dti)
>>> ser
0   2021-01-01
1   2021-01-02
2   2021-01-03
dtype: datetime64[ns]
>>> ser.astype("string")
0    2021-01-01
1    2021-01-02
2    2021-01-03
dtype: string
```

new behaviour

```
>>> pd.__version__
'1.3.0.dev0+1567.g67c9385787'
>>> 
>>> tdi = pd.timedelta_range("1 Day", periods=3)
>>> ser = pd.Series(tdi)
>>> ser
0   1 days
1   2 days
2   3 days
dtype: timedelta64[ns]
>>> ser.astype("string")
0     86400000000000 nanoseconds
1    172800000000000 nanoseconds
2    259200000000000 nanoseconds
dtype: string
>>> 
>>> dti = pd.date_range("2021", periods=3)
>>> ser = pd.Series(dti)
>>> ser
0   2021-01-01
1   2021-01-02
2   2021-01-03
dtype: datetime64[ns]
>>> ser.astype("string")
0    2021-01-01T00:00:00.000000000
1    2021-01-02T00:00:00.000000000
2    2021-01-03T00:00:00.000000000
dtype: string
>>> 
```

**Comment by simonjayhawkins** [comment]
@jbrockmendel adding the blocker to this. we shouldn't release with this change?

**Comment by jbrockmendel** [comment]
> adding the blocker to this. we shouldn't release with this change?

i wouldn't raise a fuss if we release without fixing this.  ill take a look soonish at what it would take to revert/fix

**Comment by simonjayhawkins** [comment]
Thanks. sure, not a blocker for rc since we can fix things things like this after but before actual release. At the moment, trying to establish what's outstanding before we can do the rc.

**Comment by jbrockmendel** [comment]
@simonjayhawkins im catching up on an email backlog.  is this a short-term priority?

**Comment by simonjayhawkins** [comment]
removing the blocker tag as if not done before 1.3 release, milestone will be updated to 1.3.1 to keep track of this regression. Ideally since we are aware of this regression, we would not release without fixing, but we have other regressions also on master without the blocker label so don't need to make this a special case.
