### ISSUE TITLE
BUG: read_json changes dtype (object => int) 

### ISSUE THREAD

**Issue by sidsvash26** [pandas-dev/pandas#41408]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd

dct1 = {'text': "I ran to the store.",
 'e1_span': '17',
 'e2_span': '18_19',
 'value1': 0.0,
 'value2': 0.2}

dct2 = {'text': "I ran to the store.",
 'e1_span': '11',
 'e2_span': '12_13_14',
 'value1': 0.4,
 'value2': 0.67}

df = pd.DataFrame([dct1, dct2])
print(f"initial value: {df['e2_span'].values[0]}")
print(f"value type: {type(df['e2_span'].values[0])}")

json_string = df.to_json(orient="records", lines=True)

df2 = pd.read_json(json_string, orient="records", lines=True)
print(f"final value: {df2['e2_span'].values[0]}")
print(f"value type: {type(df2['e2_span'].values[0])}")
```

#### Problem description

When the `json_string` is read by `pd.read_json` function, it converts the `str` type of `e2_span` to `int64`.

The current output is:
```python
initial value: 18_19
value type: <class 'str'>
final value: 1819
value type: <class 'numpy.int64'>
```

#### Expected Output
```python
initial value: 18_19
value type: <class 'str'>
final value: 18_19
value type: <class 'str'>
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.8.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-120-generic
Version          : #122~16.04.1-Ubuntu SMP Wed Sep 30 15:09:00 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.4
numpy            : 1.20.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.1
setuptools       : 56.0.0
Cython           : None
pytest           : 6.2.4
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.23.1
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : 2021.04.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.3
sqlalchemy       : None
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by sidsvash26** [comment]
My Current workaround is to manually set the dtype of the column name:

```python
df2 = pd.read_json(json_string, orient="records", lines=True, dtype={'e1_span': object,
                                                                    'e2_span': object})
```

This then gives the correct expected output.

**Comment by phofl** [comment]
Hi, ``18_19`` is a number in python, the same as ``17``. Why would you expect something different here?

**Comment by manikaran1993** [comment]
Hi,
you can also try 

df2 = pd.read_json(json_string, orient="records", lines=True, dtype=False)

**Comment by sidsvash26** [comment]
> Hi, `18_19` is a number in python, the same as `17`. Why would you expect something different here?

18_19 can both be a `str` or an `int` type in Python.  I wanted the code to keep the data type consistent with the original dictionary, but the type is changing when storing the data in a JSON string and then reading it back to pandas dataframe.

I think what @manikaran1993 has suggested is probably the right way to handle this. I didn't know the existence of `dtype` attribute in `read_json`. Closing the issue as I believe `dtype` attribute is intended for exactly these kinds of issues.
