### ISSUE TITLE
DOC: Unclear first example in pandas.DataFrame.append

### ISSUE THREAD

**Issue by t0asty** [pandas-dev/pandas#41407]
#### Location of the documentation

pandas.DataFrame.append 

#### Documentation problem

I think the example chosen to show the difference between ignore_index=False and ignore_index = True (the very first on the page) could make this difference more clear.

#### Suggested fix for documentation

Choosing a custom index for the first df (the one whose append function is called) could help to especially point out the fact that ignore_index=True actually overwrites the whole index and does not keep the index of the first dataframe, as it could be interpreted from this example (given somebody dared to not read the doc above 😉 )

**Comment by attack68** [comment]
yes I agree. Thanks for the report. Do feel free to contribute this idea via a PR!

**Comment by t0asty** [comment]
On it :)
