### ISSUE TITLE
CI: Fail build on "UserWarning: Code input with no code at..."

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#41410]
Blank lines in ipython blocks cause the warning "UserWarning: Code input with no code at..." to be emitted when building the docs. #41400 removed the blank lines so there are currently no warnings, but they will likely reappear, specially since double blank lines around classes/functions looks correct. Should we fail the doc build on such a warning (not sure why that doesn't already happen) or enforce this through style checks?

**Comment by rhshadrach** [comment]
Thanks @jorisvandenbossche! I hope to find some time follow up on this and put in a PR to ipython in a few weeks.

**Comment by rhshadrach** [comment]
https://github.com/ipython/ipython/pull/13030 has been merged, to be included in 7.26. Will test after 7.26 is released and can then close this issue.

**Comment by MrMino** [comment]
@rhshadrach Update: 7.26 was released today.

**Comment by rhshadrach** [comment]
Thanks @MrMino! Confirmed the CI fails when warnings are present in #42858.

**Comment by jorisvandenbossche** [comment]
Thanks @rhshadrach for fixing this on the IPython side!
