### ISSUE TITLE
Dropping top level in multiindex independently of key

### ISSUE THREAD

**Issue by didacrarbones** [pandas-dev/pandas#41416]
I am developing some code that derives various pandas classes, and I have stumbled what seems to me like a bug. I do not have too much experience with pandas, so pardon me if this is obviously wrong.

In function `maybe_droplevels` from the `multiindex` file, lines [3878](https://github.com/pandas-dev/pandas/blob/15dff11b799f665b50e9078ae52dd820ac1bc678/pandas/core/indexes/multi.py#L3878) and [3884](https://github.com/pandas-dev/pandas/blob/15dff11b799f665b50e9078ae52dd820ac1bc678/pandas/core/indexes/multi.py#L3884) disregard the content of `key` and directly drop the top-most level. It has been like that for at least some years. I am not sure if this was by design in the beginning, to avoid issues, but after a brief look I cannot find the reason why it is would not possible to drop only the level where `key` is.

My code derives `MultiIndex`, and when I return a slice that shrinks the DataFrame size, line [3463](https://github.com/pandas-dev/pandas/blob/15dff11b799f665b50e9078ae52dd820ac1bc678/pandas/core/frame.py#L3463) wants to shrink the size of the index too.

**Comment by attack68** [comment]
the function

```
def maybe_droplevels(index: Index, key) -> Index:
    # drop levels
    original_index = index
    if isinstance(key, tuple):
        for _ in key:
            try:
                index = index._drop_level_numbers([0])
            except ValueError:
                # we have dropped too much, so back out
                return original_index
    else:
        try:
            index = index._drop_level_numbers([0])
        except ValueError:
            pass

    return index
```

does indeed only drop the top levels, effectively it is doing the same as (which I find more explicit):

```
def maybe_droplevels(index: Index, key) -> Index:
    # drop leading levels
    if isinstance(key, tuple):
        if len(key) >= index.nlevels: # cannot drop all or more
            return index
        else:  # drop the leading number corresponding to key length
            return index._drop_level_numbers(list(range(len(key)))        
    else:
        if index.nlevels == 1:
            return index
        else:  # drop leading level
            return index._drop_level_numbers([0])
```

Sorry, without further investigation I too don't know why this would be the case.

I might speculate the when using `.loc` with a multiIndex you do not have to index with a a tuple the length of `nlevels` but if you want to index say the 2nd or 3rd levels, you must always populate the left-most, i.e. .loc[(slice(None), "a", "z")]`, this might be relevant for this method. But this may also be a red-herring so beware!

**Comment by mroeschke** [comment]
Thanks for the report. While this does point to suspicious behavior, it would be great to have a small reproducible example of the discrepancy so we could ultimately see the difference and have a unit test as well. Closing, but happy to reopen once we can get that information.
