### ISSUE TITLE
ENH: while exporting MultiIndex dataframe, to Google Sheets allow a Single name to be displayed for all columns having the same name.

### ISSUE THREAD

**Issue by Lokeshrathi** [pandas-dev/pandas#41422]
I wish to use pivot_table function of python same as the one in Excel, where the columns with the same name are grouped as One.

Also this is the first time, I am trying to contribute to a open source, please help me out so that my question/feature request makes sense to all.

**Comment by attack68** [comment]
posting a clear, unambiguous, minimal example will help users understand what you are trying to do...

**Comment by MarcoGorelli** [comment]
Hi @Lokeshrathi - closing for now, will reopen if you address the comment above
