### ISSUE TITLE
DOC: DataFrame.hist documentation cuts off mid-sentence

### ISSUE THREAD

**Issue by asongtoruin** [pandas-dev/pandas#41421]
#### Location of the documentation

[`pandas.DataFrame.hist`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.hist.html)

#### Documentation problem

The introduction to the documentation currently reads:

> Make a histogram of the DataFrame’s.
> 
> A histogram is a representation of the distribution of data. This function calls matplotlib.pyplot.hist(), on each series in the DataFrame, resulting in one histogram per column.

As defined in `pandas.plotting._core` [here](https://github.com/pandas-dev/pandas/blob/15dff11b799f665b50e9078ae52dd820ac1bc678/pandas/plotting/_core.py#L135-L141). This first sentence seems incomplete - the DataFrame's _what_?

#### Suggested fix for documentation

The sentence should probably be completed, likely in a manner that matches [`pandas.DataFrame.plot.hist`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.hist.html),
the simplest form of which is probably just

> Make a histogram of the DataFrame's **columns**.

which might be a bit small to be its own PR, but could be wrapped together with marking `column` and `figsize` as optional parameters (currently also not reflected in the documentation)

**Comment by mdhsieh** [comment]
Hi, I'm a first-time contributor. Can I take this issue?

**Comment by mdhsieh** [comment]
take
