### ISSUE TITLE
WEB: Format broken in team page (maintainers grid)

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#41438]
Looks like the format of our team grid is broken when there is only one maintainer in a row, check Patrick here: https://pandas.pydata.org/about/team.html

The website generates invisible cards in the last row so the size stays the same, regardless of the actual (visible) number of cards. But something doesn't seem to be working as expected.

**Comment by attack68** [comment]
there are flex-wraps within flex wraps:

```
<div class="row">
    <div class="card-container">
        <div class="card"></div>
        ..
        <div class="card"></div>
    </div>
    ...
    <div class="card-container">
        <div class="card"></div>
        ..
        <div class="card"></div>
    </div>
</div>
```

might be better just to create a single div as the flex container and let all the name cards organise themselves based on browser size?

```
<div class="main-container">
    <div class="card"></div>
    ..
    <div class="card"></div>
    <div class="card"></div>
    ..
    <div class="card"></div>
</div>
```

**Comment by datapythonista** [comment]
That sounds good. I think I started implementing that, but couldn't get it working, and that's why I implemented the current approach. In any case, happy with any approach that fixes the problem.

**Comment by calvh** [comment]
I'd like to work on this

**Comment by calvh** [comment]
take

**Comment by calvh** [comment]
Sorry @wesm and @gfyoung I did not realize the build script was making API requests to github for data on all the maintainers. I exceeded the API rate limit for your accounts. I hope that won't be too much of an issue. I do apologize for not reading the script completely before running it.

**Comment by datapythonista** [comment]
> Sorry @wesm and @gfyoung I did not realize the build script was making API requests to github for data on all the maintainers. I exceeded the API rate limit for your accounts. I hope that won't be too much of an issue. I do apologize for not reading the script completely before running it.

The quota is the number of requests you can do from your own IP address to the GitHub API. It managed to fail when fetching their profiles, but it's your own quota, and didn't affect anyone else, don't worry.

When building the website for development is unfortunately expected to run out of that quota. Not sure if we still have a flag in the script to continue the build if that quota is exceeded. But in your case, since you're testing the page that needs the GitHub data, there is nothing else that can be done than waiting one hour for the quota to reset. I guess you already seen that.
