### ISSUE TITLE
Performance regression in series_methods.Clip.time_clip

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#41434]
https://pandas.pydata.org/speed/pandas/index.html#series_methods.Clip.time_clip?python=3.8&Cython=0.29.21&p-n=50&commits=29512dc9ea2b066ab5f4a7cb80c1f8f5becef1c2

https://github.com/pandas-dev/pandas/pull/41141/

I don't know if there's any easy way to get this back, but it'd be nice to avoid the slowdown if possible.

cc @Rasori

**Comment by simonjayhawkins** [comment]
@TLouf can you open a PR with the proposed changes

**Comment by TLouf** [comment]
Done

**Comment by simonjayhawkins** [comment]
Thanks @TLouf
