### ISSUE TITLE
CI: Build documentation broken after jinja2 update to 3.0

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#41450]
Looks like an upgrade broke our doc build.

Successful build:
https://github.com/pandas-dev/pandas/runs/2567593238

Broken build:
https://github.com/pandas-dev/pandas/pull/41444/checks?check_run_id=2573993166

This occurs in more than one pr, so not related to changes in the prs

Full version diff:
```
       packages                      version_now              version_previous
70        boto3                      1.17.72                      1.17.71
71     botocore                      1.20.72                      1.20.71
86        click                        8.0.0                        7.1.2
141   gitpython                       3.1.16                       3.1.15
203      jinja2                        3.0.0                       2.11.3
327  markupsafe                        2.0.0                        1.1.1
343        moto                        2.0.7                        2.0.5
403      pandas  1.3.0.dev0+1607.g0a3a7c7f5d  1.3.0.dev0+1605.g4ec6925c19
591   terminado                        0.9.5                        0.9.4
661         NaN                          NaN                            #
```

**Comment by jreback** [comment]
this has to be the sphinx update. pin <4.0.0 for now

**Comment by phofl** [comment]
I think this is related to the jinja2 upgrade to 3.0. Sphinx is still 3.5.4. Pinned this in the related pr

**Comment by jorisvandenbossche** [comment]
The cause for the doc failure is due to a nbsphinx / jinja interaction: https://github.com/spatialaudio/nbsphinx/issues/563

**Comment by simonjayhawkins** [comment]
removed the milestone, I assume the current pin is ok for the release?
