### ISSUE TITLE
BUG: random warning about dataframe.sub()

### ISSUE THREAD

**Issue by jiahe224** [pandas-dev/pandas#41467]
- [x] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example
x file: https://github.com/jiahe224/bug_report/blob/909726d7693af1c1b34a1f6c0604b768c845bf99/x.csv
y file: https://github.com/jiahe224/bug_report/blob/909726d7693af1c1b34a1f6c0604b768c845bf99/y.csv

```python
# Your code here
x = pd.read_csv('x.csv')
y = pd.read_csv('y.csv')
x = x.set_index(['年份','133行业名称'])
y = y.set_index(['年份','133行业名称'])
x.sub(y)
```

#### Problem description
A warning will appear randomly, the warning message is as follows.

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\multi.py:3369: RuntimeWarning: The values in the array are unorderable. Pass `sort=False` to suppress this warning.
  uniq_tuples = lib.fast_unique_multiple([self._values, other._values], sort=sort)

x.sub(y) Runs correctly occasionally：
https://github.com/jiahe224/bug_report/blob/6b500dfd729b4772c9c2ee57cff63eaee9393628/1.png

But most of the time it will warning：
https://github.com/jiahe224/bug_report/blob/6b500dfd729b4772c9c2ee57cff63eaee9393628/2.png

x.shape is (501, 2)
y.shape is (500, 2)
But after testing, different index does not affect the normal operation, eg:
`df_test1 = pd.DataFrame({'col1':[1,2,3,4]},index=[list('xxxx'),list('1111'),list('opqn')])`
`df_test2 = pd.DataFrame({'col1':[1,2,3]},index=[list('xxx'),list('111'),list('opq')])`
`df_test1.sub(df_test2)`

The following runs are correct without warning：
`x.loc['2017'].sub(y.loc['2017']) # '2018', '2019', '2020' are all correct`

so, Why does it work correctly after slicing, but a warning appears when running as a whole?

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 67a3d4241ab84419856b84fc3ebc9abcbe66c6b3
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Simplified)_China.936

pandas           : 1.1.4
numpy            : 1.19.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 52.0.0.post20210125
Cython           : 0.29.22
pytest           : 6.2.2
hypothesis       : None
sphinx           : 3.5.2
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.2
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.21.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.8.3
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.1
sqlalchemy       : 1.3.23
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.53.0

</details>

**Comment by phofl** [comment]
Hi,

please provide a reproducible example which is copy-pasteable. See https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports
Also I can not open your links.

**Comment by jiahe224** [comment]
I am very sorry, Because the data is confidential, it cannot be provided. Even if the transformed data is provided, I guess it cannot be reproduced. The link cannot be clicked directly, it needs to be copied and opened in a new tab. This may be a mistake of GitHub. @phofl

**Comment by jiahe224** [comment]
I updated the comment and added the transformed data, now I can reproduce the random warning. @phofl

**Comment by jbrockmendel** [comment]
@jiahe224 can you post a copy/pasteable example?  see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by mroeschke** [comment]
Thanks for the report, but as mentioned we would need a minimal example without reading csv so we can have the simplest example to unit test against if there is a bug here. Closing, but happy to reopen if we receive a minimal example
