### ISSUE TITLE
QST:When I execute a (96554023, 16) dimension DataFrame and save it to the hard disk, On a host with 64G memory, the process is killed What should I do to make this process execute normally?

### ISSUE THREAD

**Issue by greenary-John** [pandas-dev/pandas#41483]
Code:
df.shape
(96554023, 16)
df.to_pickle('data/test_sample.pkl')

Description：
df.memory_usage(deep=True)
Index                772432184
id                   772432184
request_timestamp    772432184
position             772432184
uid                  772432184
aid                  772432184
imp_ad_size          772432184
bid                  772432184
pctr                 772432184
quality_ecpm         772432184
totalEcpm            772432184
request_day          772432184
wday                 772432184
hour                 772432184
minute               772432184
period_id            772432184
imp                  772432184
dtype: int64

The entire dataframe can be completely loaded into memory
error:
But when the dataframe is written to the hard disk through df.to_pickle(path), the memory required for the entire process exceeds 64G. I executed the (os:linux)top command in real time. After the memory reached 98%, The entire process is terminated by the operating system
**df.to_pickle('data/test_sample.pkl')** The entire process caused by this line is terminated 

memory:64G
```
python3.6
absl-py             0.12.0
astor               0.8.1
boto3               1.17.72
botocore            1.20.72
cached-property     1.5.2
certifi             2020.12.5
chardet             4.0.0
click               8.0.0
dataclasses         0.8
filelock            3.0.12
future              0.18.2
gast                0.4.0
gensim              3.6.0
grpcio              1.37.1
h5py                3.1.0
idna                2.10
importlib-metadata  4.0.1
jmespath            0.10.0
joblib              1.0.1
Keras               2.2.4
Keras-Applications  1.0.8
Keras-Preprocessing 1.1.2
Markdown            3.3.4
numpy               1.15.4
pandas              1.1.5
pip                 21.1.1
protobuf            3.17.0
python-dateutil     2.8.1
pytz                2021.1
PyYAML              5.4.1
regex               2021.4.4
requests            2.25.1
s3transfer          0.4.2
sacremoses          0.0.45
scikit-learn        0.24.2
scipy               1.2.1
sentencepiece       0.1.95
setuptools          49.6.0.post20210108
six                 1.16.0
sklearn             0.0
smart-open          5.0.0
termcolor           1.1.0
threadpoolctl       2.1.0
tokenizers          0.5.2
tqdm                4.60.0
transformers        2.8.0
typing-extensions   3.10.0.0
urllib3             1.26.4
Werkzeug            2.0.0
wheel               0.36.2
zipp                3.4.1
```

**Comment by greenary-John** [comment]
Please help me, I have no money to expand the memory now

**Comment by jbrockmendel** [comment]
can you post the results of `frame.memory_usage(deep=True)`?

**Comment by greenary-John** [comment]
Thank you for your help, I have updated the details of the memory

**Comment by mzeitlin11** [comment]
If file size is not a concern, you could try `to_csv`, which probably will be less memory-intensive than `pickle`. If you have `pyarrow` installed on the machine, `to_parquet` will usually be better than pickling since the storage format is explicitly designed for data.

**Comment by greenary-John** [comment]
Thank you very much for your reply
I don’t know if the community has plans to optimize df.to_pickle？
and I also tried to use df.to_csv with chunksize to solve this problem yesterday.
You said df.to_parquet is also an option
Thanks again for your reply

**Comment by mzeitlin11** [comment]
> I don’t know if the community has plans to optimize df.to_pickle？

If you think something weird might be going on, investigation into optimizing memory usage here would certainly be welcome. If you could provide a reproducible (smaller than 64 GB) example where memory usage is much higher than you'd expect, that would be helpful for diagnosing any potential memory inefficiency.

**Comment by greenary-John** [comment]
Yesterday, I have solved this problem by using df.to_csv(path,chunksize=10000)
