### ISSUE TITLE
Deprecate non-keyword arguments for methods with `inplace`

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#41485]
## Background

Having many parameters with defaults makes static typing a lot harder when one of them changes the return type, as they require many* overloads.

There's still no broad agreement about whether or not to deprecate the `inplace` argument, so in the meanwhile, if we force default-arguments to be keyword-only, then we can at least set the correct return types for these methods without requiring all these overloads (as many as 38 in one case!).

## What to do

1. Choose a method from the following list:

- [ ] pandas/core/computation/eval.py:164:0, eval (skip for now)
- [x] pandas/core/frame.py:4718:4, set_axis
- [x] pandas/core/frame.py:4743:4, drop
- [x] pandas/core/frame.py:5134:4, fillna
- [x] pandas/core/frame.py:5306:4, set_index
- [x] pandas/core/frame.py:5572:4, reset_index
- [x] pandas/core/frame.py:5809:4, dropna
- [x] pandas/core/frame.py:5958:4, drop_duplicates
- [x] pandas/core/frame.py:6196:4, sort_values
- [x] pandas/core/frame.py:6267:4, sort_index
- [x] pandas/core/generic.py:6432:4, ffill
- [x] pandas/core/generic.py:6495:4, bfill
- [x] pandas/core/generic.py:6700:4, interpolate
- [x] pandas/core/generic.py:7473:4, clip
- [x] pandas/core/generic.py:9080:4, where
- [x] pandas/core/generic.py:9234:4, mask
- [x] pandas/core/indexes/base.py:1530:4, set_names
- [x] pandas/core/indexes/multi.py:810:4, set_levels
- [x] pandas/core/indexes/multi.py:997:4, set_codes
- [x] pandas/core/resample.py:831:4, interpolate
- [x] pandas/core/series.py:1279:4, reset_index
- [x] pandas/core/series.py:2028:4, drop_duplicates
- [x] pandas/core/series.py:3228:4, sort_values
- [x] pandas/core/series.py:3438:4, sort_index
- [x] pandas/core/series.py:4475:4, set_axis
- [x] pandas/core/series.py:4490:4, drop
- [x] pandas/core/series.py:4713:4, fillna
- [x] pandas/core/series.py:5064:4, dropna
- [x] read_csv
- [x] read_table
- [x] concat

2. Use `pandas.util._decorators.deprecate_nonkeyword_arguments` to issue a FutureWarning that the method's default arguments will be keyword-only in the next release.

3. Fixup any tests / internal code which uses such default arguments positionally. See [this gist](https://gist.github.com/MarcoGorelli/1e8fb9d4cfb24353b0022f03150651a0) for a helper-script which can help identify cases which need fixing, just replace `"drop"` with whatever method you're working on and then run it as `python visitor.py`.

4. Add a new test, checking that a FutureWarning is raised if this method's default arguments are used positionally.

5. Add a note to `doc/source/whatsnew/v1.3.0.rst`

See https://github.com/pandas-dev/pandas/pull/41511 for an example of how to do this.

In most of these methods, the first argument is probably fine to be kept as is, it's the ones after that (such as `axis`) which should become keyword-only.

----

*(2^{number of default types preceding the one to overload} +2)

----

It's really common to call `replace` with both `value` and `to_replace` as positional, so I think we can make an exception for that one. It'll only require 6 overloads, which I'd argue isn't too many, especially if no other method requires more than 3 or 4

---

TODO: unify the whatsnew entries

**Comment by jmholzer** [comment]
I would like to work on this issue, it would be my first contribution to Pandas.

It could take me a week or two. If that is unacceptable, feel free to assign this to someone else.

**Comment by jmholzer** [comment]
take

**Comment by MarcoGorelli** [comment]
Awesome! @jmholzer please start by choosing one of the methods listed above, and comment here which one you've chosen

**Comment by jmholzer** [comment]
Sorry, didn't see the 'what to do' edit.

eval, as it's first ;)

**Comment by jmholzer** [comment]
Adding the pandas.util._decorators.deprecate_nonkeyword_arguments decorator to eval seemed to cause it to break (could not run example in docs, tested before and after adding decorator, ensuring decorator was only change). I can open an issue if anyone else would like to confirm.

To sanity check my method, I went through the process above for drop_duplicates (in frame and series) without any problems, I have opened a pull request (#41500) for these changes.

**Comment by MarcoGorelli** [comment]
> Adding the pandas.util._decorators.deprecate_nonkeyword_arguments decorator to eval seemed to cause it to break

Thanks for looking into this - I just tried it, and confirm that it breaks for me too.

Let's skip this one for now, the others seems to be working fine

**Comment by Anupam-USP** [comment]
Is someone already in this or can I try?

**Comment by MarcoGorelli** [comment]
> Is someone already in this or can I try?

Hey @Anupam-USP - feel free to take any of the non-ticked methods

**Comment by Jiezheng2018** [comment]
@MarcoGorelli I am not confident that I did the pull request correctly. I only completed the first two instructions, and I didn't use the gist you created.

**Comment by jackzyliu** [comment]
@MarcoGorelli I'd like to work on the two `.fillna` functions (series and frame) if they are still open.

**Comment by Anupam-USP** [comment]
Hey @MarcoGorelli, I have started on `.where` but as indicated in #41523, I am not able to find any usage of .where like .drop, should I continue the search or proceed to test?

**Comment by MarcoGorelli** [comment]
@Anupam-USP #41523 already addresses `where`, please choose a different method

**Comment by jmholzer** [comment]
I will open a pull request for set_names.

**Comment by ShreyDixit** [comment]
Hi @MarcoGorelli, I would like to work on `mask` if its not already taken?

**Comment by MarcoGorelli** [comment]
go ahead, thanks!

**Comment by 01-vyom** [comment]
Working on `set_levels`.

**Comment by Pydare** [comment]
Hi @MarcoGorelli, this would be my first Open Source Contribution. I would like to work on the `set_codes` function.

**Comment by MarcoGorelli** [comment]
Awesome, @Pydare, do ask if you want/need any help!

**Comment by Anupam-USP** [comment]
Ok, I will take `interpolate` then. The last one!

**Comment by MarcoGorelli** [comment]
@Anupam-USP Thanks!

This wasn't part of the original issue, but `read_csv` also has keyword argument which changes the return type, if you wanted to make a PR for that one too that would be welcome!

**Comment by Anupam-USP** [comment]
It is in ./pandas/io/parsers/readers.py right? Or am I looking to the wrong function? Also, I wanted to know if any other technique is there to search in the codebase

**Comment by MarcoGorelli** [comment]
yup, that's the one

easiest way to find where things are defined is probably to find the function in the documentation, then click "source"

![Screenshot 2021-05-24 at 18 06 39](https://user-images.githubusercontent.com/33491632/119383169-eb25e400-bcba-11eb-98c2-f417aaf1f108.png)

**Comment by Pydare** [comment]
> Awesome, @Pydare, do ask if you want/need any help!

I have been able to complete tasks 1 & 2, but I'm a little confused about where the visitor.py file should be placed to fix any tests / internal code that uses default arguments positionally.

**Comment by MarcoGorelli** [comment]
@Pydare no need to use the visitor.py file, it's just to help you identify what might need changing - if you open a PR (even if it's not a finished) I can take a look

**Comment by EricFleishman26** [comment]
Hi, I would like to work on interpolate if that is not already taken.

**Comment by MarcoGorelli** [comment]
> Ok, I will take `interpolate` then. The last one!

Hi @Anupam-USP - are you still working on resample.interpolate?

**Comment by Anupam-USP** [comment]
> @Anupam-USP Thanks!
> 
> This wasn't part of the original issue, but `read_csv` also has keyword argument which changes the return type, if you wanted to make a PR for that one too that would be welcome!

No @MarcoGorelli, you suggested me to do read_csv. So should I go for it now?

**Comment by MarcoGorelli** [comment]
I wrote

> if you wanted to make a PR for that one too 

so if you wanted to do this one too, that would be welcome

**Comment by Anupam-USP** [comment]
Okay! Surely I will try it

**Comment by tegardp** [comment]
may I try working on the read_table?

**Comment by MarcoGorelli** [comment]
> may I try working on the read_table?

go ahead, thanks! see what's been done for `read_csv` as an example

**Comment by simonjayhawkins** [comment]
@MarcoGorelli can you confirm just #41699 and #41718 outstanding.

**Comment by MarcoGorelli** [comment]
@simonjayhawkins that's right (and the clean of up these whatsnew entries, but I can do that later today)

**Comment by Anupam-USP** [comment]
Only eval is left. Should I take it?

**Comment by MarcoGorelli** [comment]
> Only eval is left. Should I take it?

if you can figure out how to do it, then sure - it's a bit tricker though, I'm not sure myself why it was failing when I tried it earlier

**Comment by simonjayhawkins** [comment]
@MarcoGorelli Thanks for coordinating this effort. i'll close this, maybe open an issue for pandas/core/computation/eval.py
