### ISSUE TITLE
Pandas Timedelta gives different result than numpy timedelta64

### ISSUE THREAD

**Issue by bhishanpdl** [pandas-dev/pandas#41515]
Is this the desired behavior of pandas vs numpy timedelta?

```python

In [4]: df = pd.DataFrame({'date': pd.date_range('2021-05-16',periods=5)})

In [5]: df
Out[5]: 
        date
0 2021-05-16
1 2021-05-17
2 2021-05-18
3 2021-05-19
4 2021-05-20

In [6]: df['date'] - pd.Timedelta('12 m')
Out[6]: 
0   2021-05-15 23:48:00
1   2021-05-16 23:48:00
2   2021-05-17 23:48:00
3   2021-05-18 23:48:00
4   2021-05-19 23:48:00
Name: date, dtype: datetime64[ns]

In [7]: df['date'] - pd.Timedelta('12 M') # Pandas gives same result for m and M
Out[7]: 
0   2021-05-15 23:48:00
1   2021-05-16 23:48:00
2   2021-05-17 23:48:00
3   2021-05-18 23:48:00
4   2021-05-19 23:48:00
Name: date, dtype: datetime64[ns]

In [8]: df['date'] - np.timedelta64(12,'m')
Out[8]: 
0   2021-05-15 23:48:00
1   2021-05-16 23:48:00
2   2021-05-17 23:48:00
3   2021-05-18 23:48:00
4   2021-05-19 23:48:00
Name: date, dtype: datetime64[ns]

In [9]: df['date'] - np.timedelta64(12,'M') # numpy gives DIFFERENT result for m and M
Out[9]: 
0   2020-05-15 18:10:48
1   2020-05-16 18:10:48
2   2020-05-17 18:10:48
3   2020-05-18 18:10:48
4   2020-05-19 18:10:48
Name: date, dtype: datetime64[ns]
```

**Comment by AlexKirko** [comment]
Hello, @bhishanpdl . As stated in the docs, pandas `Timedelta` is an equivalent of the python `datetime.timedelta` class and not `numpy.timedelta64`. This is reflected in the constructor, please refer to the python [docs](https://docs.python.org/3/library/datetime.html#datetime.timedelta). As a result of this decision, we do not support the month time unit, while numpy does.

**Comment by AlexKirko** [comment]
Please reopen if I have missed something.

**Comment by bhishanpdl** [comment]
@AlexKirko Thanks for the heads up. Then, I would suggest that when using 'M', pandas should give an error, since the same code works in NumPy and gives different. 

It would be nicer if there was only 'm' and NOT 'M', then there would be no confusion.

**Comment by mzeitlin11** [comment]
@bhishanpdl that will be the behavior in the future! Right now on the master branch using 'M' gives a `FutureWarning`
