### ISSUE TITLE
QST: How to export json as zip without directories

### ISSUE THREAD

**Issue by danymat** [pandas-dev/pandas#41517]
Hello Everyone, I searched a possible answer for my question without success.

Suppose I start my python script in the root directory of this structure tree:

```
.
├── Dockerfile
├── files
├── scripts
```

In this script I read a csv from files, with a `read_csv('files/filename.csv')`

When I try to export a modified dataframe with `to_json('files/export.zip', compression='zip')`, I get a zipped file with the correct name, but when unzipping, I get a folder named `files`, and the json inside.

How can I export the json file in zip without having the root `files` directory listed ?

*Note: This is a related problem below, but I was hoping a builtin solution with `to_json()`*
https://unix.stackexchange.com/questions/182032/zip-the-contents-of-a-folder-without-including-the-folder-itself

**Comment by twoertwein** [comment]
`to_csv` does the same. Changing the behavior should be fairly easy, simply adding
```py
if archive_name is not None:
    archive_name = os.path.basename(archive_name)
```
before
https://github.com/pandas-dev/pandas/blob/671cf86a78e931a9c98ad72571ec65cd3c35d8a7/pandas/io/common.py#L776

Do you want to create a PR? This probably needs some discussion as some people might expect the nested behavior.

**Comment by mroeschke** [comment]
Thanks for the issue, but it appears this hasn't gotten traction in a while so closing
