### ISSUE TITLE
Pandas plot giving wrong graph with date time index

### ISSUE THREAD

**Issue by soorejmg** [pandas-dev/pandas#41536]
With Pandas  1.2.*  and previous version as well, when the index is a date time format, dataframe is plotting wrongly. Date time as read from csv file using csv read  function has both date and time in it. The graph plotted is appearing wrongly, unless converted to String format. 
Wrong graph below
![IMG-20210518-WA0019](https://user-images.githubusercontent.com/47497915/118642790-59c3f700-b80e-11eb-8f81-b85f21725f20.jpeg)

Correct graph

![IMG-20210518-WA0023](https://user-images.githubusercontent.com/47497915/118642943-80822d80-b80e-11eb-81c3-b0581aa60067.jpeg)

**Comment by MarcoGorelli** [comment]
can you post a reproducible example please

**Comment by soorejmg** [comment]
It looks like it happens when there is a break in the time interval ``
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np



df_read=pd.read_csv('trial2.csv',parse_dates=["Time"])
df_read.set_index('Time',inplace=True)

df_read.plot(y='blackmagic',rot=15)


# plot after converting to string

df_read.index=df_read.index.map(str)
df_read.plot(y='blackmagic',rot=30)

**Comment by soorejmg** [comment]
# this was not a bug. It was caused by missing date time points which was being filled automatically

**Comment by soorejmg** [comment]
**This was not a bug. It was caused by missing date time points which was being filled automatically**
