### ISSUE TITLE
BUG: openpyxl not mentioned in Dependencies

### ISSUE THREAD

**Issue by garvit-joshi** [pandas-dev/pandas#41547]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
df.to_excel("output.xlsx")

```

#### Problem description

While using the above code snippet in Python 3.9.5
```
Traceback (most recent call last):
  File "/mnt/windowsD/Repos/Aster_TelegramBot/env/lib/python3.9/site-packages/telegram/ext/utils/promise.py", line 80, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/mnt/windowsD/Repos/Aster_TelegramBot/rate.py", line 98, in plot_rate
    df.to_excel("output.xlsx")
  File "/mnt/windowsD/Repos/Aster_TelegramBot/env/lib/python3.9/site-packages/pandas/core/generic.py", line 2189, in to_excel
    formatter.write(
  File "/mnt/windowsD/Repos/Aster_TelegramBot/env/lib/python3.9/site-packages/pandas/io/formats/excel.py", line 815, in write
    writer = ExcelWriter(  # type: ignore[abstract]
  File "/mnt/windowsD/Repos/Aster_TelegramBot/env/lib/python3.9/site-packages/pandas/io/excel/_openpyxl.py", line 30, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.9.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.12.1-2-MANJARO
Version          : #1 SMP PREEMPT Sun May 2 13:56:40 UTC 2021
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_IN
LOCALE           : en_IN.ISO8859-1

pandas           : 1.2.4
numpy            : 1.20.3
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.1
setuptools       : 56.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by garvit-joshi** [comment]
Possible Fix: #41548

**Comment by phofl** [comment]
Openpyxl and xlsxwriter are listed as optional dependencies here https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#optional-dependencies

this is not a required dependency

**Comment by garvit-joshi** [comment]
Ok! Thank You
