### ISSUE TITLE
BUG: self.fill_value ignored in SparseArray.min/max

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#41552]
https://github.com/pandas-dev/pandas/pull/41159#discussion_r621602882 the PR got merged before the problem was addressed

**Comment by simonjayhawkins** [comment]
@jbrockmendel i've added the blocker tag since I assume we should revert #41159 if this is not addressed?

**Comment by jbrockmendel** [comment]
It looks like #41159 will be correct in the modal case, so might be better than nothing.  @taytzehao will you have a chance to address this anytime soon?

**Comment by taytzehao** [comment]
Yeap, will be doing it this week
