### ISSUE TITLE
ENH: keep the common columns from either the left/right/both dfs in pd.merge.

### ISSUE THREAD

**Issue by jaindamini1111** [pandas-dev/pandas#41561]
#### Is your feature request related to a problem?

I wish I could use pd.merge and keep the common columns just from either the left/right df instead of getting col_x/col_y.

#### Describe the solution you'd like

pd.merge should get a new parameter like - keep_common_columns_from - which can take three arguments - 

1. only_left
2. only_right
3. both

**Comment by ParfaitG** [comment]
I feel the user can prepare the data prior to merge to decide which same-named columns from either side to retain and do so as part of the same chain. Adding extra args to a well-established, extensive method may cause confusion. See current signature: [`pandas.merge`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html).

```python
common_cols = ["common_col1", "common_col2", "common_col3"]

merged_df = left_df.merge(
    right_df.drop(common_cols, axis="columns"), 
    on="id"
)
```

**Comment by phofl** [comment]
You can simply do ``suffixes=("", "drop_later")`` if you want to keep the left column names as is. If you want to drop, you have to do this beforehand

**Comment by Lokeshrathi** [comment]
@phofl Can you please elaborate here, seems to be effective solution but couldn't find anything in the documentation.

**Comment by phofl** [comment]
> @phofl Can you please elaborate here, seems to be effective solution but couldn't find anything in the documentation.

You will have to be more specific about this. I just showed how to use the suffixes keyword to avoid renaming on one side. The suffixes keyword itself is documented

**Comment by mroeschke** [comment]
Thanks for the suggestion, but the provided work arounds are idiomatic in pandas, and I don't believe as well this necessitates an API expansion for convenience. Closing since this has not gotten much support from the team but happy to reopen if there is revived interest
