### ISSUE TITLE
ENH: support defaultdict in read_csv dtype parameter

### ISSUE THREAD

**Issue by jtbr** [pandas-dev/pandas#41574]
I have a large csv file with 15k columns with non-obvious names, of which 14990 are floating point numbers. I'd like to load them as floats without `read_csv` having to spend the time divining their types.

`dtype` allows providing a `dict`, but making one with all the column names is tedious and not always possible. The obvious solution is to provide a `defaultdict`, with a default of `np.float32`, and including entries for the other column types. Unfortunately currently, the default is silently ignored by `read_csv`. Presumably `read_csv` is not directly querying the dictionary, but rather checking first whether an item is there. 

If this is not possible, it would be helpful to include a warning to the user, or at least some mention in the documentation, that defaultdict is not supported. It took me a long time to figure out why my floats weren't being treated as float32 and why read_csv was still trying to determine the types of these columns.

**Comment by jtbr** [comment]
As a workaround I tried subclassing `defaultdict` to make `mydict.get(key)` behave like `mydict[key]` and to override the `in` operator to always return true. Unfortunately this is not work either. So it appears `read_csv` must be using the dict's `keys()` function directly. My subclass code follows:

    class MyDefaultDict(defaultdict):
        def __contains__(self, item):
            return True
        def get(self, key):
            return super().__getitem__(key)

**Comment by NickVeld** [comment]
+1

I investigated the code and found [here](https://github.com/pandas-dev/pandas/blob/a246270e55ba953276fc11fdf30ea070ba6edd82/pandas/_libs/parsers.pyx#L986) this
```
            col_dtype = None
            if self.dtype is not None:
                if isinstance(self.dtype, dict):
                    if name in self.dtype:
                        col_dtype = self.dtype[name]
                    elif i in self.dtype:
                        col_dtype = self.dtype[i]
                else:
                    if self.dtype.names:
                        # structured array
                        col_dtype = np.dtype(self.dtype.descr[i][1])
                    else:
                        col_dtype = self.dtype
```
looking through the following stack (I have all the floats except the strings in the index column thus I need the default dict too):
```
File ".../my_code.py", line 58, in __init__
    data = pd.read_csv(data_filepath, delimiter=DELIMITER, dtype=np.float, header=0, index_col=0)
  File ".../lib/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File ".../lib/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File ".../lib/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File ".../lib/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 850, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 982, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1056, in pandas._libs.parsers.TextReader._convert_tokens
ValueError: could not convert string to float: 'SOME_STR_FOR_INDEX'
```

Maybe it helps to make workaround

**Comment by mzeitlin11** [comment]
Supporting `defaultdict` sounds reasonable, I think a PR to add this would be welcome if anyone's interested in working on it!

**Comment by TLouf** [comment]
I see two ways to solve this, either you nest another if statement checking for a `defaultdict` instance, or you switch from `if name in self.dtype:` to a nested `try` / `except`, following a "better ask for forgiveness than permission" approach. I don't know which one would be preferred in terms of style (I think the performance change would be negligible in most use cases). Anyway I can write the PR if that's ok.

**Comment by NickVeld** [comment]
Done. I used try/except approach because it is more general so it can be used latter for supporting
