### ISSUE TITLE
QST: Was it intended to not sort the columns anymore when creating DataFrame from the list of dictionaries?

### ISSUE THREAD

**Issue by NeuroBobster** [pandas-dev/pandas#41605]
When migrating from pandas 0.24 to 1.1.5 I stumbled across this:

```python
import pandas as pd
d1 = {'b':1,'a':2,'c':3}
d2 = {'a':1,'c':2,'b':3}
print(pd.DataFrame([d1, d2]))

# output from pandas 0.24.2:
#    a  b  c
# 0  2  1  3
# 1  1  3  2

# output from pandas 1.1.5
#    b  a  c
# 0  1  2  3
# 1  3  1  2
```
Both ran on python 3.7. Seems like old version used to always sort columns, while the new one doesn't and uses the order of the first item in the list. I didn't find any related information in docs or SO, so my question is: was this behaviour intended? Does this have anything to do with dictionaries preserving order (since python 3.6 I think)?

**Comment by Liam3851** [comment]
Added in 0.25.0, see [the release notes](https://pandas.pydata.org/pandas-docs/version/0.25.1/whatsnew/v0.25.0.html#column-order-is-preserved-when-passing-a-list-of-dicts-to-dataframe).
