### ISSUE TITLE
QST: Error in Pandas to_datetime conversion?

### ISSUE THREAD

**Issue by ardamaks** [pandas-dev/pandas#41623]
#### Is this an error in Pandas to_datetime conversion?

**Initial data stored in following format as dtype: object:**
17:00:00

**After using following code, data is returned with year added and desired dtype: datetime**
```
df['$Time'] = pd.to_datetime(df['$Time'], exact=True, format='%H:%M:%S', errors='coerce')

0   1900-01-01 17:00:00
1   1900-01-01 17:00:01
2   1900-01-01 17:00:02
3   1900-01-01 17:00:03
4   1900-01-01 17:00:04
Name: $Time, dtype: datetime64[ns]
```

**If Im using now dt.time to remove date and keep only hours, I'm getting dtype: object back... Is this a bug? What should be correct logic to keep %H:%M:%S and dtype: datetime?**
```
df['$Time'] = df['$Time'].dt.time

0    17:00:00
1    17:00:01
2    17:00:02
3    17:00:03
4    17:00:04
Name: $Time, dtype: object
```

**Comment by jbrockmendel** [comment]
> If Im using now dt.time to remove date and keep only hours, I'm getting dtype: object back... Is this a bug? What should be correct logic to keep %H:%M:%S and dtype: datetime?

I don't know what it means "to keep %H:%M:%S and dtype: datetime".  What is the ideal end result?

**Comment by ardamaks** [comment]
> > If Im using now dt.time to remove date and keep only hours, I'm getting dtype: object back... Is this a bug? What should be correct logic to keep %H:%M:%S and dtype: datetime?
> 
> I don't know what it means "to keep %H:%M:%S and dtype: datetime". What is the ideal end result?

I want to have in this format 17:00:00 and dtype: datetime. So no date added. If I use to_datetime it returns desired object, but does not (it seems) respect format. If I use  dt.time, it returns desired format, but "wrong" dtype

**Comment by ZurMaD** [comment]
So, do you want this?

```
>df['$Time'] 

0   1900-01-01 17:00:00
1   1900-01-01 17:00:01
2   1900-01-01 17:00:02
3   1900-01-01 17:00:03
4   1900-01-01 17:00:04

>df['$Time'] .dtype

datetime64[ns]

>df['$Time'] = df['$Time'].dt.time

0    17:00:00
1    17:00:01
2    17:00:02
3    17:00:03
4    17:00:04

>df['$Time'] .dtype

# Wanted
datetime64[ns] # not posible because pandas store full data 
# Real
object # because you're cutting part of datetime

```

**Comment by jbrockmendel** [comment]
It sounds like you want to keep the datetime64 data but change how it is displayed to just display the time part of the datetime.  That is not what the "format" arg of to_datetime does; that arg is about how to parse strings into datetimes, not the other way around.

**Comment by ardamaks** [comment]
Ok guys, thanks for explanation.
Then I have related question.
So if I import csv file which contain time column and other parameter columns, when I plot the  graph based on parameter/time correlation, pandas plots time axis in wrong format. So what is the best way to import time data and work with it?

**Comment by ParfaitG** [comment]
For related question, we will need a reproducible example. We cannot tell what you mean by *wrong format*. Perhaps you can research similar questions on StackOverflow (which consist of many pandas posts about datetime formats for plots). If still unable to find solution, go ahead and ask specific question with sample data and code on SO.
