### ISSUE TITLE
CI: FutureWarning from string promotion on actions-38-numpydev

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#41632]
- [x] I have checked that this issue has not already been reported.

- [] I have confirmed this bug exists on the latest master of pandas

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

CI seems to be failing in some tests.  I did an update to a PR #41594 which ONLY had a doc change and merge to latest master, and now it is failing in CI.

**Comment by lithomas1** [comment]
Looks like something changed in numpy and scipy. 
Version changes are numpy 1.21.0.dev0+1625.g4caf8e707 -> 1.22.0.dev0+4.gb283e1632
scipy 1.7.0.dev0+990.cee5290 -> 1.7.0.dev0+1036.4ec6f29
This is the diff for numpy https://github.com/numpy/numpy/compare/4caf8e707..b283e1632

**Comment by jbrockmendel** [comment]
opened https://github.com/numpy/numpy/issues/19078

**Comment by mroeschke** [comment]
Looks like the numpy issue has been address and I don't think we're seeing this on our numpy dev build anymore so closing
