### ISSUE TITLE
ENH: Add a unit conversion method for Pandas Series

### ISSUE THREAD

**Issue by normansimonr** [pandas-dev/pandas#41641]
I wish I could use pandas to do unit conversion between miles/kilometres, inches/centimetres, feet/metres, etc, in a single line of code. I was thinking of something that someone could use like this:

~~~python
my_series_in_kilometres = my_series_in_miles.convert_units(from="mi", to="km")
my_series_in_feet = my_series_in_metres.convert_units(from="m", to="ft")
~~~

I think this feature could potentially ease the lives of people who have to do a lot of data munging with `pandas`. I don't know if this already exists (`pandas` is so vast!) but after having searched on Google and having found nothing, I decided to open an issue. I am aware that you can do this with simple arithmetic operations, but perhaps it'd be nice to have a built-in method that saves you the looking up in conversion tables. Thank you!

**Comment by jreback** [comment]
see https://github.com/pandas-dev/pandas/issues/10349

this was an inspiration for extension arrays; there is some preliminary support for `pint`
