### ISSUE TITLE
DOC:  Sort list of month name strings in ascending order (No Documentation present)

### ISSUE THREAD

**Issue by Lokeshrathi** [pandas-dev/pandas#41646]
#### No Doc present

While using the datetime library, when we extract month from a given datetime datatype. There should be a way to sort those values in ascending order.
tried: 
1. sorted()
2. sort_values

Neither of them throws a error nor gives the desired output.

Although found a solution on [StackOverflow](https://stackoverflow.com/questions/60624571/sort-list-of-month-name-strings-in-ascending-order) but I assume, this is used widely in time series problems and could come in handy!

Thank you

**Comment by mroeschke** [comment]
Thanks for the report, this overlaps with the enhancement request in https://github.com/pandas-dev/pandas/issues/12993 so closing in favor of that issue
