### ISSUE TITLE
BUG: Rounding not working

### ISSUE THREAD

**Issue by akald** [pandas-dev/pandas#41640]
The conventional system for rounding is that if the second digit is larger or equal to 5, we round up

df   Value
0    0.45
1      0.95

df.Value.round(1) doesn't give the correct answer. It should be 0.5 and 1.0

**Comment by jreback** [comment]
pls give a copy passable example that constructs the frame along with versions

**Comment by ZurMaD** [comment]
@jreback I think he refers to this


```python
import pandas as pd
import numpy as np
df=pd.DataFrame({'col':[0.45,0.95]})
# Round decimals
df['round']=df['col'].round(decimals=1)
df
```

That gives and output of 
```python
    col  round  
0  0.45    0.4    
1  0.95    1.0   
```

But using
``````

**Comment by ZurMaD** [comment]
@akald with this code you should get what you want

```python
import pandas as pd
import numpy as np

def round_special(number, base=0.5):
    return number + (base - number) % base

df=pd.DataFrame({'col':[0.45,0.95]})
df['special']=df['col'].apply(round_special)
df
# gives output of
    col  special
0  0.45      0.5
1  0.95      1.0
```

**Comment by akald** [comment]
Thanks @ZurMaD. But that doesn't always work. For example, 0.345 should round at 1dp to 0.4 .

**Comment by ZurMaD** [comment]
> Thanks @ZurMaD. But that doesn't always work. For example, 0.345 should round at 1dp to 0.4.

As far as I know, there are, at least, four ways to round:
```python
import numpy as np
import pandas as pd

def some_special_function(number,decimals=2):
    return round(number,decimals)

df=pd.DataFrame({'col':[0.45,0.95,0.345]})

# with decimals 
df['round']=df['col'].round(1)

# with ceil
df['ceil']=df['col'].apply(np.ceil) 

# with floor
df['floor']=df['col'].apply(np.floor)  

# special functions to round
df['some_special_function']=df['col'].apply(some_special_function)
```

```python
>>> df
     col  round  ceil  floor  some_special_function
0  0.450    0.4   1.0    0.0                   0.45
1  0.950    1.0   1.0    0.0                   0.95
2  0.345    0.3   1.0    0.0                   0.34
```

**Comment by akald** [comment]
The standard way for rounding is how Excel does it using the ROUND function, which is the same as https://www.calculatorsoup.com/calculators/math/roundingnumbers.php. For 1dp, for example:

0.345 should round to  0.3
0.45 should round to 0.5
0.95 should round to  1

**Comment by phofl** [comment]
This is on the numpy side. We are dispatching to numpy here.

```
na = np.array([0.45,0.95])
na.round(1)
```

This yields the same

**Comment by ZurMaD** [comment]
According to build-in functions of Python https://docs.python.org/3/library/functions.html#round


> Note The behavior of round() for floats can be surprising: for example, round(2.675, 2) gives 2.67 instead of the expected 2.68. This is not a bug: it’s a result of the fact that most decimal fractions can’t be represented exactly as a float. 

for `round( )` build-in function it's part of Python limitation with how floating-point numbers are represented, read more here https://docs.python.org/3/tutorial/floatingpoint.html#floating-point-arithmetic-issues-and-limitations

So, yo need to do this to get what yo want

```python
import numpy as np
import pandas as pd

def round_half_up(number,decimals):
    if (number * 10 ** (decimals + 1)) % 10 == 5:
        return round(number + 1 / 10 ** (decimals + 1), decimals)
    else:
        return round(number, decimals)

df=pd.DataFrame({'col':[0.45,0.95,0.345,838.274]})

# special functions to round
df['some_special_function']=df['col'].apply(round_half_up,decimals=1)

```
```python
# output
print(df)
       col  some_special_function
0    0.450                    0.5
1    0.950                    1.0
2    0.345                    0.3
3  838.274                  838.3
```
Check more ways to solve this here https://stackoverflow.com/questions/33019698/how-to-properly-round-up-half-float-numbers-in-python

**Comment by phofl** [comment]
Thx @ZurMaD

**Comment by mwaskom** [comment]
I don't think it has to do with floating point, it's because [numpy uses](https://numpy.org/doc/stable/reference/generated/numpy.around.html#numpy.around) a "round to even" convention.

This could probably be made more clear in the docstring (you need to click through to the numpy docs to uncover it).

**Comment by lithomas1** [comment]
Hi @akald, can this issue be closed now since it is not a bug in pandas? Thanks.
