### ISSUE TITLE
BUG: `pd.concat` on MultiIndex joins named levels by order rather than by name

### ISSUE THREAD

**Issue by zhenruiliao** [pandas-dev/pandas#41660]
- [ X] I have checked that this issue has not already been reported.

- [ X] I have confirmed this bug exists on the latest version of pandas.

- [] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
iris_data = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
iris = iris_data.set_index(['species', 'petal_width'])
iris1 = iris[:100]
iris2 = iris[100:]
iris2.index = iris2.index.reorder_levels([1,0])
pd.concat([iris1, iris2])
```

#### Problem description
When concatenating on a named MultiIndex, expected behavior is that corresponding named levels are joined even if the order of levels is different. Instead, the levels are only joined in order. This occurs even if `levels=` is passed explicitly

#### Expected Output
Same as `iris`

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.9.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.101-0504101-generic
Version          : #202102261049 SMP Fri Feb 26 11:30:58 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.4
numpy            : 1.20.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.1
setuptools       : 52.0.0.post20210125
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.23.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by attack68** [comment]
take a look at #41162 

in my opinion there needs to be some clarity over how to treat different cases.

**Comment by phofl** [comment]
Closing as duplicate, the other issue covers this
