### ISSUE TITLE
Drop support for Python 3.7

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#41678]
from https://numpy.org/neps/nep-0029-deprecation_policy.html

> On Dec 26, 2021 drop support for Python 3.7 (initially released on Jun 27, 2018)

The next release after 1.3 can be scheduled for 6 months, and we can drop 3.7 support in the next release.

**Comment by simonjayhawkins** [comment]
updated the 2.0 milestone date to match.

**Comment by Anupam-USP** [comment]
Hey, can I take this issue? I found [this](https://packaging.python.org/guides/dropping-older-python-versions/) article that I think will be useful?

**Comment by simonjayhawkins** [comment]
We won't be starting this until 1.3.0rc0 is released at the earliest.
