### ISSUE TITLE
QST: pandas.loc["x", :] (slicing) automatically converts int to float : is this issue addressed somewhere?

### ISSUE THREAD

**Issue by github4xyz** [pandas-dev/pandas#41671]
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions. yes, and I can not find any resolution or explanations other then confirming the issue is there. refer to https://stackoverflow.com/questions/55455010/how-to-stop-pandas-dataframe-from-converting-int-to-float-for-no-reason

- [x] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

please look into the following link for the code which explains the issue as well as reproducible codes.
https://stackoverflow.com/questions/55455010/how-to-stop-pandas-dataframe-from-converting-int-to-float-for-no-reason 

```python
# Your code here, if applicable

```
I am looking for confirmation on whether this is a bug, if it is a feature, point me to appropriate documentation.

Thanks in advance!

**Comment by mroeschke** [comment]
Thanks for the report, but if you are proposing this is a bug we please ask you to provide need a minimal reproducible example by filling in the bug report issue template. Closing, but the team would be happy to follow up in a bug report.
