### ISSUE TITLE
May 2021 Docs Meeting

### ISSUE THREAD

**Issue by afeld** [pandas-dev/pandas#41686]
- [Thursday, May 27th 9-10am US Eastern Time](https://everytimezone.com/s/5f687654)
- [Zoom link](https://nyu.zoom.us/j/98201283174?pwd=d0VoUy9GTDRlVVZ0cCtTK0s4NnlBZz09)
- [Agenda/notes](https://docs.google.com/document/d/1JoiqTdK6gi5W1QiTWrqtTV-rNmIqU3xROgHY5iT4J5g/edit#heading=h.pd2rym64bmch)

---

For this session, thinking we try something a bit different: In [the workshop around the Diátaxis documentation framework](https://github.com/pandas-dev/pandas/issues/40603#issuecomment-830860731), @evildmp was explaining his highly incremental approach to documentation improvement. He:

1. Picks a small chunk of content
2. Asks things like:
   - Is this in the right place?
   - Is it still valuable?
   - Is there anything that could be improved in it?
3. He moves/edits/deletes it
4. Repeat

(Hope I summed that up well!) I thought this might be interesting to try as a group; kind of like [mob programming](https://en.wikipedia.org/wiki/Mob_programming) but for docs. We'll see how it goes!

@pandas-dev/pandas-core @pandas-dev/pandas-triage @pandas-dev/pydata-sphinx-theme @pandas-dev/pandas-docs

**Comment by jorisvandenbossche** [comment]
That sounds as a nice idea! But unfortunately I won't be able to join (lack of voice after giving a long workshop while having a cold .. ;))
