### ISSUE TITLE
Cannot install pandas on Linux machine

### ISSUE THREAD

**Issue by krishna3008** [pandas-dev/pandas#41687]
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [x] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python

![MicrosoftTeams-image](https://user-images.githubusercontent.com/74471606/119768973-3caaba80-bed7-11eb-9f03-a515df26a731.png)
I tried to install pandas in linux machine using pip3 and error raised as in the image uploaded 
please look into this and help
```

**Comment by phofl** [comment]
Could you upgrade pip and try again? 8.1.1 is pretty old.

**Comment by phofl** [comment]
Closing for now, please ping to reopen after you have tried a newer pip
