### ISSUE TITLE
Docs behaviour on bad urls

### ISSUE THREAD

**Issue by hayd** [pandas-dev/pandas#4169]
When hitting a bad url it shows content from [main page](http://pandas.pydata.org/) but loses css.

e.g. http://pandas.pydata.org/pandas-docs/dev/foo.html

I think these pages link to the old (non-existent) `"_static/pydata.css"` rather than `"_static/nature.css"` (does this come from [here](https://github.com/pydata/pandas-website/blob/4431565525f6002710f68817ac46a910adf67227/conf.py#L109) or [here](https://github.com/pydata/pandas-website/blob/4431565525f6002710f68817ac46a910adf67227/_themes/pydata/theme.conf#L3)?). :S

Also, not sure how/where this behaviour is configured (or if it can be), but could be nice if it could show a alert message to say was a bad url, but perhaps that's not possible.

**Comment by TomAugspurger** [comment]
Fixed now I think
