### ISSUE TITLE
core.DataFrame(or Series).combine_first  better doc string 

### ISSUE THREAD

**Issue by zhangyi-hu** [pandas-dev/pandas#41704]
https://github.com/pandas-dev/pandas/blob/beabf0aab2a1ff7776d1aa30b8ede9d9386f9836/pandas/core/frame.py#L7315

I'm suggesting adding this sentence after the above location to make the function name easier to understand:

The 'first' dataframe overrides the second one where both first.loc[index, col] and second.loc[index, col] are not nan, upon calling
first.combine_first(second).

**Comment by jbrockmendel** [comment]
PR would be welcome
