### ISSUE TITLE
STYLE disallow assigning to single-letter variable names

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#41719]
We keep leaving this comment to each other and to contributors in review, so let's add a rule for it

PR should be made to https://github.com/pandas-dev/pandas-dev-flaker if anyone wants to give this a go

**Comment by jbrockmendel** [comment]
id like this, but in fairness its mostly me leaving that comment

**Comment by MarcoGorelli** [comment]
:laughing: pretty sure I've seen it from others too

@mgmanzella tagging you in case you'd be interested in giving this a go, as you'd expressed interest in implementing more linting rules

**Comment by MarcoGorelli** [comment]
done in pandas-dev-flaker

next step will be to gradually introduce it to the pandas codebase

**Comment by MarcoGorelli** [comment]
closing for now as the PR's already been made to pandas-dev-flaker, enabling it will be another issue
