### ISSUE TITLE
CLN: Delete pandas-docs GitHub organization

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#41736]
xref #41050

Feels like https://github.com/pandas-docs/pandas-docs-travis was created to publish the development pandas docs, but that was eventually moved elsewhere, and now there is just a two year old copy published there (in their github pages).

I think we should delete the `pandas-docs` organization, to avoid confusion, or people accessing old docs from outdated links to that copy.

**Comment by lithomas1** [comment]
cc @jorisvandenbossche

**Comment by datapythonista** [comment]
This is actually a dupe of #41050, which has now been reopened. My mistake, closing here.
