### ISSUE TITLE
DOC: whatsnew format for minor enhancements/bug-fixes

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#41748]
Admittedly this is extremely minor, but it's something that has always irked me. Currently for minor (single-line, not a section) enhancements and bug-fixes, we have the format:

> This is sentence one (GH28527)

which on its own is perfectly fine. However when a line has multiple sentences:

> This is sentence one. This is sentence two (GH28527)

the lack of a period at the end looks off to me. I'd prefer if we did full sentences for each line followed by the GH link at the end, this way a multi-sentence doesn't look so odd.

> This is sentence one. (GH28527)
> This is sentence one. This is sentence two. (GH28527)

Another option is to limit one-line notes to being a single sentence (which I'm opposed to), and of course we could  just stay with it as is. If we are to make any changes, I'd do it for the version minor/major version after 1.3.0.

cc @simonjayhawkins

**Comment by attack68** [comment]
when committing for first time I looked to copy this structure and I agree with you, albeit this is tiny.

what about:

> This is one issue (GH12345).
> This is another issue (GH23456). And a related component (GH34567).
> This is a fourth. And a final note (GH45678).

**Comment by rhshadrach** [comment]
Thanks @attack68 - if two issues have different references to a GH issue/PR, then I think they should be separate line items, even if related.

**Comment by jbrockmendel** [comment]
This is 100% not worth bikeshedding, but I often use a semicolon to avoid getting into the 2-sentence situation.

**Comment by jbrockmendel** [comment]
is this actionable?
