### ISSUE TITLE
QST: Mailinglist or Discussion Forum beside StackOverflow

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [pandas-dev/pandas#41786]
I miss a way to get intouch with the pandas community (users & devs) beside StackOverflow where I can ask strick questions.

But I want to discuss some ideas and thinks like that. I am not sure if am allowed to that in this "Question" section in the Issues?

btw: GitHub now offers a discussion forum, too.

**Comment by MarcoGorelli** [comment]
Hey @Codeberg-AsGithubAlternative-buhtz 

What do you mean by "strict questions"?

You could try asking in https://gitter.im/pandas-dev/community , or on the mailing list - I'm not aware of any other place at the moment. Or ask here, I guess

https://pandas.discourse.group/c/general-discussion/8 also exists, but it doesn't look like it ever took off

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Great, thanks.

But where was gitter or the mailinglist mentioned on the project website? https://pandas.pydata.org/

I do not mean the GitHub project side where it is mentioned in the README.md.
