### ISSUE TITLE
BUG: AttributeError: 'NoneType' object has no attribute 'get' on  __version__ = v.get("closest-tag", v["version"])

### ISSUE THREAD

**Issue by irshad-io** [pandas-dev/pandas#41782]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest 

---
###Problem
I am unable to import pandas into python. Whenever I try to import, it gives me a traceback 
```python

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\__init__.py", line 186, in <module>

 __version__ = v.get("closest-tag", v["version"])
AttributeError: 'NoneType' object has no attribute 'get'

```

I tried reinstalling pandas but the error still exists. I am using Pycharm but even in cmd when I import pandas it gives me the same error.

#### Output of ``pd.show_versions()``

<details>

I cant show it because I cant import it. But from files, it is 1.2.4

</details>

**Comment by phofl** [comment]
Could you show output of pip freeze or conda list? Also can you explain how you set your env up?

**Comment by mroeschke** [comment]
Please let us know if you are able to give more detail regarding your env set up, otherwise this issue isn't very actionable to the team. Closing in the meantime.
