### ISSUE TITLE
ImportError: cannot import name 'Series' from 'pandas' (unknown location)

### ISSUE THREAD

**Issue by mksarker** [pandas-dev/pandas#41798]
>>> from pandas import Series, DataFrame
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Series' from 'pandas' (unknown location)

**Comment by MarcoGorelli** [comment]
please fill in the issue template

**Comment by mksarker** [comment]
Thanks.
