### ISSUE TITLE
ISSUE: ImportError: cannot import name 'Series' from 'pandas' (unknown location)

### ISSUE THREAD

**Issue by mksarker** [pandas-dev/pandas#41799]
from pandas import Series, DataFrame
Traceback (most recent call last):
File "", line 1, in
ImportError: cannot import name 'Series' from 'pandas' (unknown location)

**Comment by phofl** [comment]
Could you please describe how you setup your env? We can Not help without more information.

**Comment by mksarker** [comment]
conda version : 4.10.1
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
------------------------
Name: pandas
Version: 1.2.4
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: None
Author-email: None
License: BSD
Location: /anaconda3/lib/python3.7/site-packages
Requires: pytz, python-dateutil, numpy
Required-by: statsmodels, seaborn

**Comment by MarcoGorelli** [comment]
do you have a file called `pandas.py` or a folder called `pandas` locally in your path? If so, perhaps try renaming it? Also, it would be useful to see the full traceback

**Comment by mksarker** [comment]
No. I am trying from python terminal.
Python 3.7.6 (default, Jan  8 2020, 19:59:22)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pandas import Series, DataFrame
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Series' from 'pandas' (unknown location)

**Comment by mksarker** [comment]
solved! thanks.

**Comment by MarcoGorelli** [comment]
> solved! thanks.

how did you solve it?

**Comment by mksarker** [comment]
install pandas-1.1.3 version

**Comment by MarcoGorelli** [comment]
🤔  thanks - can't see why that would fix it though, but I think that if you make a new conda environment and install the latest pandas in there it should work https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands

**Comment by mksarker** [comment]
Thanks, will try! anyway, it's working now, and happy about it :)
