### ISSUE TITLE
QST:Can i able to merge cells column wise using pandas to excel

### ISSUE THREAD

**Issue by AnithaSyed** [pandas-dev/pandas#41802]
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [x] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

I need to export some data to exccel sheets throush a loop
For each sheet I need to merge some cells in column wise. I searched in the Stack also but not able to find
PFA

![image](https://user-images.githubusercontent.com/77221656/120690652-1da5bd00-c4c3-11eb-9702-7284983a984d.png)

```python
# Your code here, if applicable

```

**Comment by MarcoGorelli** [comment]
Hi @AnithaSyed 

>  I searched in the Stack also but not able to find

Can you ask on StackOverflow as well please, rather than just searching? That's where usage questions are encouraged to be posted.

If you believe there's a bug in pandas, please do let us know and we'll reopen - thanks :+1:
