### ISSUE TITLE
groupby and np.dot with MultiIndex

### ISSUE THREAD

**Issue by jseabold** [pandas-dev/pandas#4181]
Should the following work? On revision 07403ca.

```
weights = np.random.randn(4,4)
panel = pd.util.testing.makePanel(nper=2).to_frame()
panel.groupby(level=0).apply(lambda x : np.dot(weights, x))
```

I realize I can do

```
panel.groupby(level=0).apply(lambda x : pd.DataFrame(np.dot(weights, x), index=x.index, columns=x.columns))
```

Would it make sense to just assume that the result should be wrapped like this if it's conformable to the other level of the MultiIndex? Too much of a special case?

**Comment by kordek** [comment]
I've just came across this issue, if transform is used instead of apply this gives the desired output. So maybe this can be closed?

**Comment by jreback** [comment]
@kordek this should still work on ``.apply`` though. want to look at doing a patch?

generally ``.transform`` is much more strict on its output shape and not very flexible, while ``.apply`` tries to infer things, which in this case it could do a better job.

**Comment by kordek** [comment]
@jreback I see, I'll work on this.

**Comment by jreback** [comment]
closing as Panel deprecated
