### ISSUE TITLE
DEPS: clarifying setuptools's status as a dependency 

### ISSUE THREAD

**Issue by fangchenli** [pandas-dev/pandas#41815]
In `install.rst`, we list `setuptools` as a runtime dependency. If that is the case, we don't need to vendor `packaging` #41199 since it's vendored by `pkg_resources`, which is part of `setuptools`. And we need to update `setup.cfg` and `README.md` to reflect this.

If `setuptools` is not a runtime dependency, vendoring `packaging` is necessary. And, we need to list it as a test and optional dependency because we are using `pkg_resources` in `pandas/plotting/_core.py` and `pandas/tests/plotting/test_backend.py` #41503. An alternative of `pkg_resources` for accessing entry points is `importlib.metadata`, which is only available after Python 3.8. And `importlib.metadata` is the suggested way to do this according to https://setuptools.readthedocs.io/en/latest/pkg_resources.html.

**Comment by jreback** [comment]
setuptools is needed and we should list it

**Comment by jorisvandenbossche** [comment]
Setuptools (`pkg_resources`) is not a required dependency, only an optional one when using plotting backends (it's not even needed when using the default matplotlib backend). 
So I don't think we should list it as required dependency.



> An alternative of `pkg_resources` for accessing entry points is `importlib.metadata`, which is only available after Python 3.8. And `importlib.metadata` is the suggested way to do this according to https://setuptools.readthedocs.io/en/latest/pkg_resources.html.

Somewhat a separate issue from listing setuptools as dependency or not, but I think we should indeed look into replacing `pkg_resources` (probably easier to do once we only support Python 3.8+ https://github.com/pandas-dev/pandas/issues/41678)

**Comment by simonjayhawkins** [comment]
> Setuptools (`pkg_resources`) is not a required dependency, only an optional one when using plotting backends (it's not even needed when using the default matplotlib backend).
> So I don't think we should list it as required dependency.
> 
> > An alternative of `pkg_resources` for accessing entry points is `importlib.metadata`, which is only available after Python 3.8. And `importlib.metadata` is the suggested way to do this according to https://setuptools.readthedocs.io/en/latest/pkg_resources.html.
> 
> Somewhat a separate issue from listing setuptools as dependency or not, but I think we should indeed look into replacing `pkg_resources` (probably easier to do once we only support Python 3.8+ #41678)

maybe open a new issue and we can close this one now that #41818 is merged.

**Comment by jreback** [comment]
setup tools is an undeclared dependency now

it should be an official runtime one

**Comment by jorisvandenbossche** [comment]
There is a difference between "optional" and "required" dependencies. We have lots of optional dependencies that are not declared in `install_requires`. And in practice, setuptools always has been an optional dependency (not required for importing pandas / normal usage, only required when actually using one of the non-default plotting backends).

It's true that we don't provide a proper error message about "pkg_resources" (setuptools) being required for using a plotting backend (as we do for other optional dependencies), but give a plain import error instead. This certainly gives the impression we assume the library is always present, but giving a more informative import error message is also something we can easily fix.

**Comment by simonjayhawkins** [comment]
removing the blocker label since #42006 fixed the import issue.

**Comment by simonjayhawkins** [comment]
> but giving a more informative import error message is also something we can easily fix.

is that now the only outstanding actionable item here? moving to 1.3.1

**Comment by jreback** [comment]
actually i think prob ok for 1.3.x to close this (as #42410) is going to remove the need for this in 3.8

**Comment by jreback** [comment]
we merged the update for 1.4 to remove the need for setuptools entirely, so not merging this to 1.3.x unless strong desire (as efffectively by not merging we are not changing 1.3 vs 1.2 at all w.r.t. requirements).

**Comment by jorisvandenbossche** [comment]
Sounds good!
