### ISSUE TITLE
ENH: retain attrs when concat dataframes

### ISSUE THREAD

**Issue by xiki-tempula** [pandas-dev/pandas#41828]
#### Is your feature request related to a problem?

I wish the attrs could be retained when concat data frames.

```
d = {'col1': [1, 2], 'col2': [3, 4]}
df1 = pd.DataFrame(data=d)
df1.attrs = {1:1}
df2 = pd.DataFrame(data=d)
df2.attrs = {1:1}
pd.concat([df1, df2]).attrs
{}
```

#### Describe the solution you'd like

```
d = {'col1': [1, 2], 'col2': [3, 4]}
df1 = pd.DataFrame(data=d)
df1.attrs = {1:1}
df2 = pd.DataFrame(data=d)
df2.attrs = {1:1}
pd.concat([df1, df2]).attrs
{1: 1}
```

#### API breaking implications

N/A

#### Describe alternatives you've considered

N/A

**Comment by lithomas1** [comment]
Hi @xiki-tempula, thanks for the report.
This is indeed currently not implemented(xref #28283), and I guess the correct way to propogate metadata in this case would be to drop them when they don't match as in your example. PRs to fix this are welcome.
cc @TomAugspurger

**Comment by xiki-tempula** [comment]
@lithomas1 Thanks for the comment.

I'm thinking that the logic of the concat should be

```
def concat(objs, *args, **kwargs):
    '''Concatenate pandas objects along a particular axis with optional set
    logic along the other axes. If all pandas objects has the same attrs
    attribute, the new pandas objects would have this attrs attribute. A
    ValueError would be raised if any pandas object has a different attrs.

    Returns
    -------
    DataFrame
        Concatenated pandas object.
    '''
    # Sanity check
    attrs = objs[0].attrs
    for obj in objs:
        if attrs != obj.attrs:
            raise ValueError('All pandas objects should have the same attrs.')
    new = pd.concat(objs, *args, **kwargs)
    new.attrs = attrs
    return new
```

I wonder what is your thought?

**Comment by TomAugspurger** [comment]
No, I don't think we should raise if the attrs don't match. They aren't supposed to affect the result of the computation.

For now, let's just support the case where attrs match, dropping them in other cases. We can add a keyword to concat later to control that behavior.

**Comment by amreesh** [comment]
Using `pandas 1.4.2`

Instead of `append` or `concat` I used `loc` to add a row into the dataframe

`
import pandas as pd
df = pd.DataFrame(columns={'field1','field2','field3'})
df.loc[len(df.index)] = ['a','b','c']
print(df)
      field3 field2 field1
0      a      b      c
`
How do we keep the order?
any clue?

**Comment by msingh00** [comment]
is this merge in the latest version of pandas?

**Comment by xiki-tempula** [comment]
@msingh00 Yes. This should be the case.
