### ISSUE TITLE
CI: Re-enable Circle CI

### ISSUE THREAD

**Issue by lithomas1** [pandas-dev/pandas#41829]
I contacted CircleCI to check if they could be interested in sponsoring our ARM builds. Will update if I hear from them. For now looks like we're getting the 2,500 credits that @lithomas1 mentioned (not the 400,000 for open source projects for Linux builds). So, not much we can do with those.

I updated this PR so we don't add the CircleCI build, but still, it has everything else so the build passes when it can be added wherever. Only thing is that we now need to disable Circle CI, so the build doesn't fail after we remove the configuration. But only an admin of the pandas-dev organization can do it. @jreback do you mind going to https://app.circleci.com/settings/project/github/pandas-dev/pandas?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fpandas-dev%2Fpandas%2F30%2Fworkflows%2Ff9a6db17-510a-4eaf-a10c-b3a800e0a6c4%2Fjobs%2F30872 and clickig on "Stop builds" please?

_Originally posted by @datapythonista in https://github.com/pandas-dev/pandas/issues/41739#issuecomment-852446796_

We should re-enable Circle CI if we receive the Circle CI credits. 
cc @datapythonista for updates on this

**Comment by MrNaif2018** [comment]
I am also searching for arm provider that supports arm64 and arm32. Will track this issue. CircleCI works without issues on arm64, arm32 doesn't work yet I think, I contacted them.
About the 2500 credits thing: actually it's an UI "bug" (or feature), you have 400,000 credits and can go past 2500 credits without issues, it's just not updated in the UI
![изображение](https://user-images.githubusercontent.com/39452697/133679112-02ae069a-4612-4467-a486-066a4deaf843.png)

**Comment by lithomas1** [comment]
@jreback @datapythonista Do you know if we have those credits? We seem to be listed on CircleCI's website on https://circleci.com/open-source/.
![image](https://user-images.githubusercontent.com/47963215/133683821-ee797d57-79f9-4128-8940-5a87bac54e91.png)

**Comment by MrNaif2018** [comment]
![изображение](https://user-images.githubusercontent.com/39452697/133684540-c348fcd6-6b0b-419f-9fc8-e5a6eefea19c.png)
For example that's how it looks for my opensource project, our workflows run just fine as always, with no billing. For pandas especially it should work (:

**Comment by jreback** [comment]
we can try to reenable

cc @lithomas1

**Comment by jreback** [comment]
@MrNaif2018 ok this is re-enabled, let's see how it goes.
