### ISSUE TITLE
DOC: Input/Output page contains only input functions

### ISSUE THREAD

**Issue by attack68** [pandas-dev/pandas#41839]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/dev/reference/io.html#html

#### Documentation problem

The title is Input/Output but all linked methods are `read_xyz()`, and there is little if any reference to any `write_xyz()` or `to_xyzz methods.

#### Suggested fix for documentation

Perform a review and enure all input/output methods are referenced on the page.

**Comment by gansel51** [comment]
See linked PR.
