### ISSUE TITLE
ENH: Using transparentpath in read_csv

### ISSUE THREAD

**Issue by michaelshekasta** [pandas-dev/pandas#41838]
Hi Guys,

First of all, Thanks for your work!  I wish I could use pandas with transparentpath in read_csv function.
In short, transparentpath can contain gscfs paths and local paths.
for more information see [this example](https://towardsdatascience.com/transparentpath-a-python-package-to-manage-paths-on-google-cloud-storage-ae25a15a44d5)

Thanks,
Michael

**Comment by jreback** [comment]
you should contribute to https://pypi.org/project/fsspec/#data as this is the canonical interface and will just work with pandas

we do not implement specific interfaces any more

**Comment by mroeschke** [comment]
Thanks for the suggestion but as mentioned the team would prefer to have fsspec handle this instead of IO specific code to be handled in pandas. Closing.
