### ISSUE TITLE
ENH: Add option to surpress timezone warning

### ISSUE THREAD

**Issue by Tasty213** [pandas-dev/pandas#41871]
I have a column of DateTime objects that includes their timezone information. However, I know that all the timezones will always be the same. When I call `df.dt.to_period('M')` I get the following error:
```
/home/$USER/anaconda3/envs/crime_data/lib/python3.6/site-packages/pandas/core/arrays/datetimes.py:1091: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  UserWarning,
```

Should be able to pass a variable to suppress the warning

**Comment by jreback** [comment]
no you should fix your code, this is the point
