### ISSUE TITLE
QST: ExtensionDtype made available with arguments to `astype` method

### ISSUE THREAD

**Issue by thomassajot** [pandas-dev/pandas#41877]
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas
Hello, 

I have been attempting to create a new ExtensionDtype and ExtensionArray.  The Dtype can take in arguments. I was looking into how to replicate the behaviour of `Categorical` when assigning a dtype to a series. 

If the user does not provide arguments 
```python
pd.Series(['a', 'b', 'c']).astype('category')  # or pd.Series(['a', 'b', 'c']).astype(pd.CategoricalDtype())
```
Returns:
```
0      a
1      b
2     c
dtype: category
Categories (2, object): ['a', 'b']
```

If the user provides the `categories` list:
```python
pd.Series(['a', 'b', 'c']).astype(pd.CategoricalDtype(['a', 'b'])) 
```
Then the argument is given to the Array constructor which now returns a missing value:
```
0      a
1      b
2    NaN
dtype: category
Categories (2, object): ['a', 'b']
```

But for now, with my custom Dtype called in a similar fashion, the default values are used no matter the given arguments: 
Running:
```python
pd.Series([1, 2, 3]).astype(DiscreteNumericalDtype(lower=0, upper=3, inc=1))
```
expected to return
```
0   1.0
1   2.0
2   3.0
dtype: discrete
```

but actually returns:
```
0   1.0
1   NaN
2   NaN
dtype: discrete
```
which is the results of using the default argument (lower=0, upper=1, inc=.1)

### More detail about the custom types:
The goal is to create an array where float values have to be between a min and a max value, [lower, upper] and at an interval `inc`. For example, [0, 1, 5.3] mapped onto [1, 6] with an inc=1 should return: [NaN, 1, 5], and with an inc=0.2 should return [NaN, 1, 5.2].

Here is the full code I have so far.

I did not ask the question on StackOverflow as I believe the answer to this question should be added into panda's Documentation as well.

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
from typing import Type, List, Optional

import numpy as np
from druid.pandas.dtypes import DiscreteNumericalDtype
from pandas._typing import DtypeObj
from pandas.core.arrays import ExtensionArray
from pandas.core.dtypes.base import register_extension_dtype, ExtensionDtype


class DiscreteNumericalDtypeType(type):
    """
    the type of DiscreteNumericalDtype, this metaclass determines subclass ability
    """

    pass


@register_extension_dtype
class DiscreteNumericalDtype(ExtensionDtype):

    name = 'discrete'
    type: Type[DiscreteNumericalDtypeType] = DiscreteNumericalDtypeType
    base = np.dtype("O")

    def __init__(self, lower: float = 0., upper: float = 1., inc: float = 0.1):
        self.lower = lower
        self.upper = upper
        self.inc = inc

    @property
    def type(self) -> Type:
        return np.float

    @classmethod
    def construct_array_type(cls) -> Type['DiscreteNumericalArray']:
        from druid.pandas.arrays import DiscreteNumericalArray
        return DiscreteNumericalArray

    def _is_numeric(self) -> bool:
        return True

    def _is_boolean(self) -> bool:
        return False

    def _get_common_dtype(self, dtypes: List[DtypeObj]) -> Optional[DtypeObj]:
        raise NotImplementedError('TODO')



class DiscreteNumericalArray(ExtensionArray):
    """
    Represent a Continuous value into bins between [Lower, Upper] and a step size.
    """
    _dtype = DiscreteNumericalDtype()
    ndim: int = 1

    def __init__(self,
                 values,
                 lower: Optional[float] = 0.,
                 upper: Optional[float] = 1.,
                 inc: float = 0.1):
        values = np.asarray(values, dtype=float)
        if lower is None:
            lower = np.min(values)
        if upper is None:
            upper = np.max(values)

        values[values > upper] = np.nan
        values[values < lower] = np.nan

        self._dtype = DiscreteNumericalDtype(lower=lower, upper=upper + inc, inc=inc)
        bins = self.bins
        self.codes = np.searchsorted(bins, values, side='right') - 1
        self.codes[np.isnan(values)] = -1

    @property
    def values(self):
        values = self.bins[self.codes]
        values[self.codes == -1] = np.nan
        return values

    @property
    def dtype(self) -> DiscreteNumericalDtype:
        return self._dtype

    @property
    def bins(self):
        return np.arange(start=self.dtype.lower,
                         stop=self.dtype.upper,
                         step=self.dtype.inc,
                         dtype=float)

    @classmethod
    def _from_sequence(cls, scalars, *, dtype=None, copy=False):
        return DiscreteNumericalArray(scalars)

    @property
    def _constructor(self) -> Type['DiscreteNumericalArray']:
        return DiscreteNumericalArray

    @classmethod
    def _from_factorized(cls, values, original):
        return original._constructor(values,
                                    lower=original.dtype.lower,
                                    upper=original.dtype.upper,
                                    inc=original.dtype.inc)

    def astype(self, dtype, copy=True):
        raise NotImplementedError('TODO')

    def isna(self):
        return self.codes == -1

    def __len__(self):
        return len(self.codes)

    def __getitem__(self, key):
        return self.values[key]


```

**Comment by thomassajot** [comment]
I was expected to get more functionality when extending from `ExtensionArray` and `ExtensionDtype`, but it seems there are a lot of additional custom code necessary to make the `Categorical` array available easily. Especially, I was wondering if the `ExtensionBlock` would be helping to obtain the functionality I am looking for.

**Comment by jbrockmendel** [comment]
> I was looking into how to replicate the behaviour of Categorical when assigning a dtype to a series. [`.astype('category')`]

Define `DiscreteNumericalDtype.construct_from_string`.  Then when you do `obj.astype('discrete[foo, bar]')`, internally we will use the appropriate DiscreteNumericalDtype object in place fo the string.

**Comment by jbrockmendel** [comment]
> Especially, I was wondering if the ExtensionBlock would be helping to obtain the functionality I am looking for.

In principle, no, you shouldn't need to ever think about ExtensionBlock.  In practice, there are still some places where pandas-internal ExtensionArrays get special-cased, and we're trying to track those down and generalize them.  If you find any, please let us know.

**Comment by jbrockmendel** [comment]
> But for now, with my custom Dtype called in a similar fashion, the default values are used no matter the given arguments:

In your _from_sequence you call `__init__` but you don't pass dtype, so you get the default parameters.

**Comment by jorisvandenbossche** [comment]
For your example code, it's specifically the last comment of @jbrockmendel that needs to be fixed: the `_from_sequence` methods get the actual dtype instance (that is passed to `astype(..)`), so you can ensure there that you honor the parameters of the dtype.

**Comment by thomassajot** [comment]
Thank you @jbrockmendel  and @jorisvandenbossche, propagating the dtype in `_from_sequence` is working properly. 

I also did not know that you could transfer the arguments to a dtype through the string representation. 

It would be great to enhance the documentation as to the impact of the different to implement.

**Comment by thomassajot** [comment]
Hi @jbrockmendel, 
While Implementing the testing scenarios provided by pandas, I came across an `if` statement that maybe too generic.

Failing Test class:
```
class TestComparisonOps(base.BaseComparisonOpsTests):
    def check_opname(self, s, op_name, other, exc=None):
        super().check_opname(s, op_name, other, exc=None)

    def _compare_other(self, s, data, op_name, other):
        self.check_opname(s, op_name, other)
```

In `BaseOpsUtil._check_op`
```
    def _check_op(self, s, op, other, op_name, exc=NotImplementedError):
        if exc is None:
            result = op(s, other)
            if isinstance(s, pd.DataFrame):
                if len(s.columns) != 1:
                    raise NotImplementedError
                expected = s.iloc[:, 0].combine(other, op).to_frame()
                self.assert_frame_equal(result, expected)
            else:
                expected = s.combine(other, op)   <---- Combining here cast the returned values (booleans) to a DiscreteNumerical types which are float64
                self.assert_series_equal(result, expected)
        else:
            with pytest.raises(exc):
                op(s, other)
```

If we have a look in `Series.combine` implementation
```python
    def combine(self, other, func, fill_value=None) -> "Series":
        if fill_value is None:
            fill_value = na_value_for_dtype(self.dtype, compat=False)

        if isinstance(other, Series):
            # If other is a Series, result is based on union of Series,
            # so do this element by element
            new_index = self.index.union(other.index)
            new_name = ops.get_op_result_name(self, other)
            new_values = []
            for idx in new_index:
                lv = self.get(idx, fill_value)
                rv = other.get(idx, fill_value)
                with np.errstate(all="ignore"):
                    new_values.append(func(lv, rv))
        else:
            # Assume that other is a scalar, so apply the function for
            # each element in the Series
            new_index = self.index
            with np.errstate(all="ignore"):
                new_values = [func(lv, other) for lv in self._values]
            new_name = self.name

        if is_categorical_dtype(self.dtype):
            pass
        elif is_extension_array_dtype(self.dtype):
            # TODO: can we do this for only SparseDtype?
            # The function can return something of any type, so check
            # if the type is compatible with the calling EA.
            new_values = maybe_cast_to_extension_array(type(self._values), new_values)   <---- THIS line will cast the new_values (of boolean type) into a DiscreteNumerical array, which is a float
        return self._constructor(new_values, index=new_index, name=new_name)
```

because of the casting, the expected value in `BaseOpsUtil._check_op` is of the wrong type.

It seems that there is a comment about restraining the if statement to `SparseDtype` only.

**Comment by jbrockmendel** [comment]
> because of the casting, the expected value in BaseOpsUtil._check_op is of the wrong type.

what is the desired type/dtype?

**Comment by thomassajot** [comment]
this current test is triggered on comparison operation. the expected dtype should be boolean.

**Comment by jbrockmendel** [comment]
OK.  This is less of a "bug" than it is a "difficult situation where we make an educated guess".  I'm open to suggestions on better ways to do this.  If you'd like to discuss, let's either re-open this issue or open a dedicated new one.
