### ISSUE TITLE
PERF: performance regression in indexing UInt64Index with an array-like

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#41873]
See eg https://pandas.pydata.org/speed/pandas/#indexing.NumericSeriesIndexing.time_loc_list_like?python=3.8&Cython=0.29.21&p-index_dtype=%3Cclass%20'pandas.core.indexes.numeric.UInt64Index'%3E&p-index_structure='unique_monotonic_inc'

Up to 180x slowdown in the `indexing.NumericSeriesIndexing.time_loc_array/time_loc_list_like` benchmarks with UInt64Index.

Indicated range of responsible commits is https://github.com/pandas-dev/pandas/compare/21d61451...c9d50d82

Didn't check, but potential candidate: https://github.com/pandas-dev/pandas/pull/41777 or #41804

cc @jbrockmendel

**Comment by jbrockmendel** [comment]
#41777 is more plausible than #41804
