### ISSUE TITLE
BUG: Incorrect read_csv values for NaN when using regex sep argument

### ISSUE THREAD

**Issue by adrotog** [pandas-dev/pandas#41887]
#### Code Sample

```python
import numpy as np
import pandas as pd

file_path = "temp.csv"

df1 = pd.DataFrame({"x": [np.nan, 1]})
df1.to_csv(file_path, index=False)
df1_regex = pd.read_csv(file_path, sep=',|\t')

df2 = pd.DataFrame({"x1": [np.nan, 1],
                    "x2": [np.nan, np.nan]})
df2.to_csv(file_path, index=False)
df2_regex = pd.read_csv(file_path, sep=',|\t')

print(f"-----------\ndf1\n{df1}")
print(f"-----------\ndf1_regex\n{df1_regex}")
print(f"-----------\ndf2\n{df2}")
print(f"-----------\ndf2_regex\n{df2_regex}")
```

**Output**
```python
-----------
df1
     x
0  NaN
1  1.0
-----------
df1_regex
     x
0   ""
1  1.0
-----------
df2
    x1  x2
0  NaN NaN
1  1.0 NaN
-----------
df2_regex
    x1  x2
0  NaN NaN
1  1.0 NaN
```

#### Problem description

- When I provide any regex value for `sep` in `read_csv`, I get `""` instead of `NaN` for blank cells
- This only happens if the CSV only has a single column

#### Expected Output

`df1_regex` should have `NaN` in the first column like `df2_regex` does, not `""`

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.8.9.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252
pandas           : 1.2.4
numpy            : 1.20.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.2
setuptools       : 49.2.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.21.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : None
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : 3.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.6.1
sqlalchemy       : 1.4.11
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by phofl** [comment]
This is not really a read_csv issue.

The to_csv produces two different looking csv files:

```
with open("temp.csv", 'w', newline='') as f:
    writer = csv.writer(f)

    writer.writerows([['', ''], ['1.0', '1.0']])
```
This returns a file:

```
,
1.0,1.0
```

while

```
with open(file_path, 'w', newline='') as f:
    writer = csv.writer(f)

    writer.writerows([[''], ['1.0']])
```

returns
```
""
1.0
```

Hence the incorrect return value. Regex separators and quoted data are a bit tricky as mentioned in the docstrings

**Comment by phofl** [comment]
Closing as it seems this is not on our side
