### ISSUE TITLE
ENH: Add subset to fillna

### ISSUE THREAD

**Issue by eikevons** [pandas-dev/pandas#41909]
#### Is your feature request related to a problem?

When filling NAs, I need to use different methods for different columns or ignore some columns. Filling with different values per column works by passing a dict to `values` but it's not possible to do something similar for `method`-based filling, e.g. bfill `x` and ffill `y` of
```python
>>> df = pd.DataFrame({'x':[1, None, 2]}).assign(y=lambda df: df.x)
>>> df
     x    y
0  1.0  1.0
1  NaN  NaN
2  3.0  3.0
```

#### Describe the solution you'd like

I see 3 options to implement this in pandas (with examples how to solve the task above):

1. Allow the `method` argument of `fillna` to accept a dict mapping column/index-label to requested method (similar to how the `value` argument is working)
   ```python
   df.fillna(method={'x':'bfill', 'y':'ffill'})
   ```
   when dealing with many columns, this will turn into:
   ```python
   df.fillna(method={'col1': 'bfill', 'col2': 'ffill', 'col3': 'nearest', 'col4': 'bfill', 'col5': 'bfill'})
   ```
2. Allow `method` to take a dict which maps methods to lists of column/index-labels. This would allow more-concise code than the 1. option but will also add inconsistency between `method` and `value` arguments.
   ```python
   df.fillna(method={'bfill': 'x', 'ffill':'y'})
   ```
   when dealing with many columns, this will turn into:
   ```python
   df.fillna(method={'bfill':['col1', 'col4', 'col5'], 'ffill':'col2', 'nearest':'col3'})
   ```
3. Add a `subset` argument working the same as with [`dropna()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html) and [`drop_duplicates()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html). This should also be available in the method-specific methods, e.g. [`bfill()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.bfill.html)
   ```python
   df.bfill(subset=['x']).ffill(subset=['y'])
   ```
   and
   ```python
   df.bfill(subset=['col1', 'col4', 'col5']).ffill(subset='col2').fillna(method='nearest', subset='col3')
   ```

#### API breaking implications

There should be none because arguments will added or existing arguments will accept types currently not allowed.

#### Describe alternatives you've considered

It's always possible to re-assign subsets of the data frame, e.g.
```python
df['x'] = df['x'].bfill()
df['y'] = df['y'].ffill()
```
But this involves a lot of boilerplate code which adds noise to the code in total.

**Comment by eikevons** [comment]
Depending on the chance of acceptance, I'm happy to work on this.

**Comment by mzeitlin11** [comment]
Thanks for requesting this @eikevons! Option 1 looks somewhat like the syntax with passing a dictionary to GroupBy agg and feels more intuitive than 2 IMO (but I guess 2 has benefits since there aren't many filling methods, so easier to write with fewer keys).  

For option 3, I think just subsetting yourself, eg `df[["col1", "col4", "col5"]].bfill()` is clearer than adding a subset argument. Although you couldn't chain this way, chaining feels somewhat confusing when you're acting on different parts of the dataframe.

A contribution to implement this would be great, but it should first be further discussed how/if this is an enhancement others would support.

**Comment by eikevons** [comment]
> Thanks for requesting this @eikevons! Option 1 looks somewhat like the syntax with passing a dictionary to GroupBy agg and feels more intuitive than 2 IMO (but I guess 2 has benefits since there aren't many filling methods, so easier to write with fewer keys).  
>
@mzeitlin11, I agree that option 1 feels most natural in pandas compared to the other two (I guess that's why it's first on the list). Those users who do this very often and are bitten by the less concise syntax can create a small helper that translates between 2 and 1 (i.e. inverting the dict).

> For option 3, I think just subsetting yourself, eg `df[["col1", "col4", "col5"]].bfill()` is clearer than adding a subset argument. Although you couldn't chain this way, chaining feels somewhat confusing when you're acting on different parts of the dataframe.

Not arguing for option 3, just want to point out that the difference to sub-setting on `df`-level would be:
```python
# df-level subsetting
df[["col1", "col4", "col5"]] = df[["col1", "col4", "col5"]].bfill()
# subset parameter
df = df.bfill(subset=["col1", "col4", "col5"])
```

**Comment by mroeschke** [comment]
Thanks for the suggestion but it appears there hasn't been much interest in this feature from the core devs & community over the years so closing. Happy to reopen if there's renewed interest
