### ISSUE TITLE
BUG: read_json chunksize parameter does not work

### ISSUE THREAD

**Issue by simonm3** [pandas-dev/pandas#41905]
If I set chunksize=100 without nrows then it crashes with a memory error. If I set chunksize and nrows then it returns the maximum rows of the two. The workaround of setting nrows to a high number does not work as it just crashes with a memory error even with low chunksize.

I am using ubuntu20 wsl2/windows10, python=3.8, pandas=1.2.4

This has been reported in other closed issues but does not seem to be fixed. 

https://github.com/pandas-dev/pandas/issues/34548
https://github.com/pandas-dev/pandas/issues/36791

**Comment by aacosta13** [comment]
Is there any way you could post the code and/or dataset that you attempted to run with? Just tested it myself using the same Yelp dataset as one of the comments from the issue ([#36791](https://github.com/pandas-dev/pandas/issues/36791)) you linked and it seems that chunksize worked with both a value of 100 and 1000.

**Comment by simonm3** [comment]
This is the link:
http://download.companieshouse.gov.uk/en_pscdata.html

Below is trying to read chunksize=10 with the full 6GB file. Tried this in
windows and in wsl/ubuntu.

For testing try one of the smaller files from the link. This fits in memory
but takes a very long time. It is clearly not just reading 10 rows.

[image: image.png]

**Comment by simonm3** [comment]
Oh. I thought you called read to read a chunk but actually it is an iterator. Sorry my mistake!
