### ISSUE TITLE
Ability to scroll through dataframe or series for viewing

### ISSUE THREAD

**Issue by vipatel10** [pandas-dev/pandas#4193]
I think it would be nice to be able to scroll through a DataFrame by calling whatever scroll function and then holding down the up or down arrow to scroll through the different rows in a series or dataframe and the left and right arrows to scroll across various columns.  Currently, it's a little cumbersome to type in different index ranges if you want to quickly look at different parts of a dataframe ala df[0:60], then df[60:120], etc.

**Comment by mattayes** [comment]
It's been a while, is there any traction behind this issue? Is this something pandas should support, or is it more the purview of ipython, Jupyter, etc.? There's a [related issue](https://github.com/pandas-dev/pandas/issues/5611#issuecomment-259924886) that thought it was the latter.

**Comment by jreback** [comment]
this was for a text paginator, not an html one (which is the purview of ``ipython/jupyter``).

**Comment by mattayes** [comment]
Thanks for clarifying, @jreback.

**Comment by nokados** [comment]
Use this gist to paginate pandas Dataframe within Jupyter Notebook:
https://gist.github.com/nokados/e8f0a64b55099f2f07a50f2b090c91c7

**Comment by mroeschke** [comment]
This seems a little out of scope for pandas now and more suited for jupyter. Closing.
