### ISSUE TITLE
CI: intermittent segfaults on `macOS py37_macos` run

### ISSUE THREAD

**Issue by mzeitlin11** [pandas-dev/pandas#41937]
See https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=61339&view=logs&j=b516280a-8c75-541b-8ba0-ae13561718a7&t=a9217cb1-24f6-5625-717d-72085a70e1d3

and https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=61324&view=logs&j=b516280a-8c75-541b-8ba0-ae13561718a7&t=a9217cb1-24f6-5625-717d-72085a70e1d3

for some examples on 2 different runs. I've only noticed it on this run, will look to try to see when it started (unless anyone knows :)

**Comment by lithomas1** [comment]
@mzeitlin11 
Maybe we need to bump pyarrow to 0.17.1 on MacOS? xref https://issues.apache.org/jira/browse/ARROW-8684

**Comment by jreback** [comment]
sure that would be fine

**Comment by jorisvandenbossche** [comment]
It _seems_ this started in https://github.com/pandas-dev/pandas/pull/41903 (see https://github.com/pandas-dev/pandas/pull/41903)

**Comment by jorisvandenbossche** [comment]
The linked Arrow bug was fixed in 0.17.1, and the build is using 0.17.0, so that should be an easy version bump

**Comment by jorisvandenbossche** [comment]
Attempt at https://github.com/pandas-dev/pandas/pull/41948
