### ISSUE TITLE
ENH: Give name to index column as argument when using `df.reset_index`

### ISSUE THREAD

**Issue by gcaria** [pandas-dev/pandas#41947]
#### Is your feature request related to a problem?

When resetting the index of a `DataFrame`, and when needing to rename the "index" column to something more useful, it would be nice to do it directly with the call to`reset_index` (and not afterwards with `df.rename`).
#### Describe the solution you'd like

`DataFrame.reset_index` should get a new parameter `name` that renames the "index" column after resetting.

#### API breaking implications

I don't see any obvious implications.

**Comment by jorisvandenbossche** [comment]
I think that would be a good idea, see https://github.com/pandas-dev/pandas/issues/6878 (I think we can close this as a duplicate).

The main problem is that `Series.reset_index` already has a `name` keyword but that is used for the values column name, not index column name (so we will probably need another keyword name for this, unfortunately)

**Comment by gcaria** [comment]
Totally a duplicate, my bad for not checking properly! I'll have a look at #6878 and see if I can submit a PR.
