### ISSUE TITLE
DataFrame.melt fails if there are duplicate value_vars

### ISSUE THREAD

**Issue by swenlaur** [pandas-dev/pandas#41951]
DataFrame.columns.get_indexer fails if there are duplicate column names. 

https://github.com/pandas-dev/pandas/blob/05552d354a430f17a45b5fda8a1fd417f4c60c2e/pandas/core/reshape/melt.py#L109

This is really unfortunate -- melting should handle such cases

id   value value
id1  2       3 

should go to

id1 2
id1 3

**Comment by simonjayhawkins** [comment]
Thanks @swenlaur for the report.

Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug. 

and can you use the bug template that is available when you open an issue from the GitHub web interface.

**Comment by swenlaur** [comment]
Minimal code to trigger the bug (regression from earlier versions) 

`from pandas import DataFrame
(DataFrame([['id', 2, 3]])
 .set_axis(['id_var', 'value_var', 'value_var'], axis=1)
 .melt(id_vars=['id_var'], value_vars=['value_var']))`

The resulting data frame contains columns with the same name. This is not illegal as sometimes uncleaned data in this form and the most sane way to clean int is using melt.

**Comment by simonjayhawkins** [comment]
> regression from earlier versions

will add the regression tag for now pending investigation. posting more info on versions could help

**Comment by swenlaur** [comment]
I do not know the highest package number but repro works with pandas=1.0.0. I guess it stoped working after the multi-level colums patch was added to the code.
