### ISSUE TITLE
ENH: Modify .any() to return Null if all values are null

### ISSUE THREAD

**Issue by rapatel0** [pandas-dev/pandas#41967]
#### Is your feature request related to a problem?

For sparce data it is particuarly helpful to preserve null values when doing reduction operations. I end up using this (see below) wrapper function to achieve the intended result. 

```
def any_nan(x):
    if pd.isnull(x).all():
        return pd.NA
    else:
        return x.any(skipna=True)

output = df.column_to_operate_on.apply(any_nan) 

```

#### Describe the solution you'd like

The ask is to add a configuration parameter to. `.any()` and `.all()` that optionally preserves null values when returning the array. Skipna doesn't seem to have to correct functionality as it will return false, if all the values of the array are null. Ideally, with the toggleable parameter, `.any()` would return `np.nan/pd.NA` if all values in the array are null.

#### API breaking implications

This shouldn't change the api. It will just add an optional parameter

#### Describe alternatives you've considered

`pd.NA`

**Comment by mzeitlin11** [comment]
Thanks for the request @rapatel0! Does https://pandas.pydata.org/pandas-docs/stable/user_guide/boolean.html satisfy what you are looking for? For the new `pandas` nullable data types, the behavior will be as you ask, eg
```
>>> ser = pd.Series([pd.NA, pd.NA], dtype="boolean")
>>> ser.any(skipna=False)
<NA>
>>> ser.all(skipna=False)
<NA>
```
I think there are still some inconsistencies with this behavior, though, for example 
```
>>> ser = pd.Series([pd.NA, pd.NA], dtype="Int64")
>>> ser.all(skipna=False)
True
```
should be `pd.NA` I think.

**Comment by rapatel0** [comment]
Awesome. this is exactly what need. Sorry I may be dealing with legacy `np.nan` in my dataframes

**Comment by rapatel0** [comment]
The functionality works in your test case but I'm not seeing it when wrapped in a groupby to operate on a dataframe. Am I doing something wrong?


![image](https://user-images.githubusercontent.com/18704704/122285450-5a56b880-ceb4-11eb-8e97-bf1982fb3151.png)

**Comment by rapatel0** [comment]
Running a simple groupby in front of the series code implies that some masking logic is failing. 

![image](https://user-images.githubusercontent.com/18704704/122286208-3ba4f180-ceb5-11eb-90e8-6ddd677b19c1.png)

**Comment by mzeitlin11** [comment]
When you ran `df.a.fillna(pd.NA)`, the dtype of `a` becomes object. Rather than doing that, you can convert (or start with) one of the new masked types using `astype`. That failure is a known bug (#37501), but works fine for masked types

**Comment by mzeitlin11** [comment]
Closing for now, but please ping to reopen if you think there's any other weird behavior here @rapatel0
