### ISSUE TITLE
ENH: Gather `dtype` and `convertors` processing in one place

### ISSUE THREAD

**Issue by NickVeld** [pandas-dev/pandas#41996]
#### Is your feature request related to a problem?

[this should provide a description of what the problem is, e.g. "I wish I could use pandas to do [...]"]

There are many places where `dtype` and `converters` can be modified

#### Describe the solution you'd like

[this should provide a description of the feature request, e.g. "`DataFrame.foo` should get a new parameter `bar` that [...]", try to write a docstring for the desired feature]

This should gather all the `dtype` and `convertors` processing in one place.

#### API breaking implications

[this should provide a description of how this feature will affect the API]

The changes are absolutely internal.

#### Describe alternatives you've considered

[this should provide a description of any alternative solutions or features you've considered]

It is maintainers' idea.

#### Additional context

[add any other context, code examples, or references to existing implementations about the feature request here]

See discussion in #41664

**Comment by lithomas1** [comment]
Seems reasonable to me. I guess the solution would be to deprecate convertors and allow callables in dtype.

**Comment by rhshadrach** [comment]
@lithomas1 - I'm not sure what is meant by "convertors" here, can you elaborate on the proposed deprecation?

**Comment by jbrockmendel** [comment]
Without more information this is not actionable.  Closing.
