### ISSUE TITLE
BUG/TYP: 1.3.0 index.values returns ExtensionArray | ndarray instead of ndarray

### ISSUE THREAD

**Issue by twoertwein** [pandas-dev/pandas#42002]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

Probably an intended change, but I didn't find anything related to it in the whatsnew.

```py
import pandas as pd

df = pd.DataFrame({"a": [1]})

reveal_type(df.values)
reveal_type(df.index.values)
```
pyright with 1.2.4
```sh
info: Type of "df.values" is "ndarray"
info: Type of "df.index.values" is "ndarray"
```

pyright with 1.3.0.rc1
```sh
info: Type of "df.values" is "ndarray"
info: Type of "df.index.values" is "ExtensionArray | ndarray"
```

**Comment by jorisvandenbossche** [comment]
That seems a correct change indeed

> I didn't find anything related to it in the whatsnew.

I don't think we generally list typing changes/fixes in the whatsnew

**Comment by simonjayhawkins** [comment]
> That seems a correct change indeed

agreed.

https://github.com/pandas-dev/pandas/blob/a1412a0440f96cc04288f4672d9473ae481a802b/pandas/core/indexes/base.py#L4273-L4293


> I don't think we generally list typing changes/fixes in the whatsnew

agreed. the type of the property is unchanged. only the type annotation has been changed (in #38531)
