### ISSUE TITLE
DOC: Add New Community Tutorial

### ISSUE THREAD

**Issue by stefmolin** [pandas-dev/pandas#42009]
#### Location of the documentation

I'm proposing the addition of another community tutorial to the [Community tutorials](https://pandas.pydata.org/docs/getting_started/tutorials.html) page.

#### Documentation problem

Not a problem, but an opportunity for improvement.

#### Suggested fix for documentation

I recently built a [pandas workshop](https://github.com/stefmolin/pandas-workshop) for the Open Data Science Conference (ODSC) Europe event aimed at new users of pandas. It focuses on real-world datasets (making it easier for beginners to understand), includes detailed environment setup instructions (and binder), and provides notebooks and exercises to practice the concepts. I think it would make a great addition to the [Community tutorials](https://pandas.pydata.org/docs/getting_started/tutorials.html) page -- the more learning resources the better 😃 

I'm happy to make a PR.

**Comment by mohansaimandalapu** [comment]
Hi Stefmolin

Can I take up this issue, this is my first open-source issue, I couldn't completely comprehend the issue, can you please elucidate it a bit more. Thank you

**Comment by stefmolin** [comment]
Hi @mohansaimandalapu,

No need - I hoping to make the contribution myself once this is triaged. This would be my first pandas contribution 😄
