### ISSUE TITLE
ENH: Clarify error message when reindexing on an axis containing duplicates

### ISSUE THREAD

**Issue by aberres** [pandas-dev/pandas#42000]
#### Is your feature request related to a problem?

Let's consider the following snippet:

```python
pd.DataFrame(index=[pd.to_datetime("2019"), pd.to_datetime("2019"), pd.to_datetime("2020")]).asfreq("M")
```

This will raise an exception as the to be resampled dataframe has an axis with duplicates. The problem: I stumpbled at least twice on this problem and never understood what the error message wanted to tell me on first sight.

When seeing just the message (wihtout looking at the backtrace) I always thought this is about providing duplicate axis names or something like this.

```python
ValueError: cannot reindex from a duplicate axis
```

#### Describe the solution you'd like

Maybe the exception message could be clarified. The comment two lines above the exception always saves me:

```python
# trying to reindex on an axis with duplicates
```

So maybe  something like this could help?

```python
raise ValueError("Cannot reindex on an axis with duplicate values")
```

#### API breaking implications

None I guess.

The message would additionally need to be changed in some tests and in the docs.

#### Additional context

If there is interest I could draft a PR.

**Comment by jreback** [comment]
I *think* there maybe an issue about this that duplicates this one if you can have a search.
