### ISSUE TITLE
DOC: pandas.Series.str.isspace has wrong documentation

### ISSUE THREAD

**Issue by felixdivo** [pandas-dev/pandas#42015]
#### Location of the documentation

[pandas.Series.str.isspace](https://pandas.pydata.org/docs/dev/reference/api/pandas.Series.str.isspace.html)

#### Documentation problem

> Check whether all characters in each string are alphanumeric.
>
> This is equivalent to running the Python string method str.isalnum() for each element of the Series/Index. If a string has zero characters, False is returned for that check. Seems like it was somehow copied from `pandas.Series.str.isalnum`.

That does not seem to match the function.

#### Suggested fix for documentation

Not copy the doc of `pandas.Series.str.isalnum` but rather provide a specific one.

**Comment by simonjayhawkins** [comment]
Thanks @felixdivo for the report.

The code is here...

https://github.com/pandas-dev/pandas/blob/2c1e656ccae21dde88eda157b0ed0d0506265ce3/pandas/core/strings/accessor.py#L3007-L3009

contributions welcome
