### ISSUE TITLE
API: deprecate get_offset, Offset for time rules like '30s'

### ISSUE THREAD

**Issue by jseabold** [pandas-dev/pandas#4205]
From stackoverflow: http://stackoverflow.com/questions/17579932/statsmodel-arma-function-is-incompatiable-with-pandas/17581170

I'm looking only quickly at this, but I'm wondering if this should be recognized and return an offset.

```
from pandas.tseries.frequencies import get_offset
get_offset('30s')
```

or if in statsmodels we should accept custom offsets in place of frequency strings.

**Comment by jbrockmendel** [comment]
This isn't exposed in tseries.api or anywhere, does it actually need to be deprecated?  could privatize?
