### ISSUE TITLE
DOC: How to use storage_option param here to integrate with GCP bucket?

### ISSUE THREAD

**Issue by KayvanShah1** [pandas-dev/pandas#42066]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_pickle.html

#### Documentation problem

How to use storage_option param here to integrate with GCP bucket?

#### Suggested fix for documentation

Please add some examples to pandas.DataFrame.to_{any_file_format}.html

**Comment by Juliewhitaker842** [comment]
take

**Comment by PurnaChandraMansingh** [comment]
Hello, I would like to work on this issue if it's not entirely finished! I noticed that it's still open.

**Comment by Juliewhitaker842** [comment]
Sure.

Please take it.

Thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by PurnaChandraMansingh** [comment]
Hi @MarcoGorelli, do I need to set up a Google Cloud Storage and then demonstrate an example on how to store pandas DataFrame to GCS bucket?

**Comment by MarcoGorelli** [comment]
Hey @PurnaChandraMansingh - yeah if it's possible to put together a simple example, I think it'd be useful. Otherwise we can close

**Comment by PurnaChandraMansingh** [comment]
Thanks for your response @MarcoGorelli, I am trying to propose a simple example, I will let you know soon.

**Comment by PurnaChandraMansingh** [comment]
Hi @MarcoGorelli, below is working to read/write data to GCS. Kindly have a look if I am doing right or not
Thanks

### Integrate with GCP bucket
- Pandas accept URLs with the prefix "gcs://", and will use gcsfs to complete the IO operation.
- The IO functions take an argument storage_options, which will be passed to GCSFileSystem, for example:

**Write DataFrame to Google Cloud Storage**
```
df.to_pickle('gs://bucket-name/path/file-name.pkl', <other parameters>,  storage_options={"token": "credentials.json"})
```
**Read DataFrame from Google Cloud Storage**
```
df.read_pickle('gs://bucket-name/path/file-name.pkl', <other parameters>,  storage_options={"token": "credentials.json"})
```

**Comment by MarcoGorelli** [comment]
Hey @PurnaChandraMansingh - looking into this again, I think this is documented quite clearly in this part of the user guide https://pandas.pydata.org/docs/user_guide/io.html?highlight=storage_options#reading-writing-remote-files

Rather than adding an example to each docstring of each method which has `storage_options`, I'd be inclined to simply link to the above part of the user guide in each description of the storage options. E.g. in `to_pickle` it could be amended to

```
Please see fsspec and urllib for more details, and [link to the above section of the user guide] for examples.
```

Do you want to open a PR to add that?

**Comment by PurnaChandraMansingh** [comment]
Sure @MarcoGorelli I will be opening a PR with these changes.
Thanks

**Comment by purna135** [comment]
> Rather than adding an example to each docstring of each method which has `storage_options`, I'd be inclined to simply link to the above part of the user guide in each description of the storage options. E.g. in `to_pickle` it could be amended to

Hi @MarcoGorelli, I made the required changes and generated the HTML file shown below;

![image](https://user-images.githubusercontent.com/42216008/153470909-092bbca6-d14b-4bdd-8760-150396ef7961.png)

Please see ``fsspec`` and ``urllib`` for more details, and for more examples on storage options refer [here](https://pandas.pydata.org/docs/user_guide/io.html?highlight=storage_options#reading-writing-remote-files).

Could you please confirm that this is okay before I make a PR?

**Comment by MarcoGorelli** [comment]
Looks good
