### ISSUE TITLE
BUG: read_excel cannot open .xls file, ValueError: File is not a recognized excel file

### ISSUE THREAD

**Issue by liaoyusaki** [pandas-dev/pandas#42071]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
df_product = pd.read_excel("tmp/Presentaciones.xls")
```

#### Problem description

I got an error when I tried to open a product.xls with pd.read_excel ("NDC database file - Excel version (zip format)" downloaded from https://www.fda.gov/drugs/drug-approvals-and-databases/national-drug-code-directory), I tried different engine, but i always got an error

pandas version: 1.2.4
xlrd version: 2.0.1
openpyxl version: 3.0.7

#### Output of ``pd.read_excel("tmp/Presentaciones.xls")``

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 336, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 1071, in __init__
    ext = inspect_excel_format(
  File "/usr/local/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 965, in inspect_excel_format
    raise ValueError("File is not a recognized excel file")
ValueError: File is not a recognized excel file

**Comment by simonjayhawkins** [comment]
I don't think this is a pandas issue.

![image](https://user-images.githubusercontent.com/13159005/122396317-c77b5400-cf6f-11eb-99d5-8be904204d78.png)

**Comment by liaoyusaki** [comment]
> I don't think this is a pandas issue.
> 
> ![image](https://user-images.githubusercontent.com/13159005/122396317-c77b5400-cf6f-11eb-99d5-8be904204d78.png)

you are right, I downloaded it from the website and it ends with `.xls`, but it is actually an csv file with suffix `.xls`, I managed to read it after I force the name into `.csv`
