### ISSUE TITLE
When change default dtype for empty Series?

### ISSUE THREAD

**Issue by Rubtsowa** [pandas-dev/pandas#42078]
Hello! 
I see ``<stdin>:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.``. When you planed change default dtype for empty Series? 
Thank you in advanced!

**Comment by MarcoGorelli** [comment]
Hey - I thought it would've been 2.0, but I don't see #29405 in #30228 - @jorisvandenbossche should it be added?

**Comment by jbrockmendel** [comment]
> should it be added?

yes

**Comment by MarcoGorelli** [comment]
OK, done - closing for now then as I think this answers the question, thanks @Rubtsowa for bringing this to our attention!

**Comment by jorisvandenbossche** [comment]
Indeed, thanks for keeping track of it!
