### ISSUE TITLE
Use better example in pd.lookup replacement

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#42106]
https://github.com/pandas-dev/pandas/issues/39171#issuecomment-773477244

In the user guide, let's use
```
idx, cols = pd.factorize(df['col'])
df.reindex(cols, axis=1).to_numpy()[np.arange(len(df)), idx]
```
instead of the current workaround

https://pandas.pydata.org/pandas-docs/dev/user_guide/indexing.html#looking-up-values-by-index-column-labels

cc @erfannariman 
also cc @quanghm in case you have further comments on this

**Comment by raghuabhishek** [comment]
Hi MacroGorelli, Can I take this issue and work on it.

**Comment by MarcoGorelli** [comment]
sure, PRs welcome

**Comment by raghuabhishek** [comment]
Thanks MarcoGorelli, I have raised a PR https://github.com/pandas-dev/pandas/pull/42110. Can you pls review it and let me know if there are changes required.

**Comment by samukweku** [comment]
@MarcoGorelli @raghuabhishek I think it would be nice if this is abstracted into the deprecated `lookup` (I think it would be easier to understand, and just use). Although, I can understand if there is a reluctance to increase the number of APIs
