### ISSUE TITLE
ENH:

### ISSUE THREAD

**Issue by KutuDev** [pandas-dev/pandas#42112]
#### Is your feature request related to a problem?
I wish the CSV files exported from Pandas have cell sizes automatically fitted to the data. Using Microsoft Excel to open a CSV file exported from Pandas results in a cluttered spreadsheet. Some data in a cell are hidden until I manually increase the cell size.

#### Describe the solution you'd like
df.to_csv() should have a new parameter called autoFit that automatically resizes the cells before exporting the data.

#### API breaking implications
Well, I can't answer this specifically.

#### Describe alternatives you've considered
None at the moment

#### Additional context
Google sheets have a fit-to-data option that resizes each cell based on the length of its content.

```python
# None available. I was hoping this is something someone in the community can do.

```

**Comment by jreback** [comment]
and why aren't you just using to_excel()

**Comment by KutuDev** [comment]
> and why aren't you just using to_excel()

Well, I use to_excel() if I need a workbook containing many sheets and use to_csv() for just a single sheet.

**Comment by jreback** [comment]
can simply does not have meta data

use excel
