### ISSUE TITLE
BUG: M1 pipenv install failed

### ISSUE THREAD

**Issue by howardpen9** [pandas-dev/pandas#42127]
- [ ] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
pipenv install pandaas

```

#### Problem description
After running lots of minutes, I still got this errors!!

#### Expected Output
![image](https://user-images.githubusercontent.com/36764495/122650033-3371de00-d163-11eb-9576-b625386a8fa5.png)

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by lithomas1** [comment]
@howardpen9 Can you please try again with pandas 1.3.0? We have aarch wheels now.

**Comment by mroeschke** [comment]
Thanks for the report. Please let us know if you are still experience issues with 1.3 and we can reopen
