### ISSUE TITLE
DOC add example to align

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#42125]
https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.align.html?highlight=align#pandas.DataFrame.align

Align has no examples - can one be added?

**Comment by Yama-aa** [comment]
take

**Comment by Ashis26** [comment]
May I contribute to this issue?

**Comment by Yama-aa** [comment]
Hi Ashis, we have a PR open on this issue -
https://github.com/pandas-dev/pandas/pull/42129 Meiruv is still working on
it.

‫בתאריך יום א׳, 20 ביוני 2021 ב-12:23 מאת ‪Ashis26‬‏ <‪
***@***.***‬‏>:‬

**Comment by Nishita5421** [comment]
is this close ? Can I take this?

**Comment by Yama-aa** [comment]
Yes, you can

**Comment by MarcoGorelli** [comment]
> Yes, you can

Thanks for letting us know - @Nishita5421 feel free to take a look at https://github.com/pandas-dev/pandas/pull/42129 for a good start on this

**Comment by oovk** [comment]
@Nishita5421 still working on this issue?
