### ISSUE TITLE
DOC add example to reorder levels

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#42124]
https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.reorder_levels.html?highlight=reorder_levels#pandas.DataFrame.reorder_levels

No examples! Can we add at least one?

**Comment by Ashis26** [comment]
May I contribute to this?

**Comment by MarcoGorelli** [comment]
sure, at the end of this docstring https://github.com/pandas-dev/pandas/blob/master/pandas/core/frame.py#L6825-L6853

**Comment by Ashis26** [comment]
Hi, I have added an example at the end of the doc. However, several tests were failed on the pull request. I don't know how can I do corrections. May you help me?

**Comment by trevorkask** [comment]
Take

**Comment by MarcoGorelli** [comment]
> Take

there's already a PR open for this

**Comment by Nishita5421** [comment]
Is this close ? or Can I take this?

**Comment by jorisvandenbossche** [comment]
@Nishita5421 there is already an open PR for it
