### ISSUE TITLE
BUG: Pandas does not recognize NaN values on M1 macbook pro

### ISSUE THREAD

**Issue by byunwj** [pandas-dev/pandas#42139]
- [Y] I have checked that this issue has not already been reported.

- [Y] I have confirmed this bug exists on the latest version of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
import pandas as pd

data = [['tom', 20], ['mike', 30], ['julie', float('nan')]]
df = pd.DataFrame(data, columns = ['Name', 'Age'])

print(df) # can see that there is a NaN value in the dataframe

print(df.info())     # says that there are 3 non-null counts for column 'Age' instead of 2
print(df.isnull())   # says that the age value in the third row is not null 

# below does the same process but with np.nan instead of float('nan'), and the same result is produced
import numpy as np
data = [['tom', 20], ['mike', 30], ['julie', np.nan]]
df = pd.DataFrame(data, columns = ['Name', 'Age'])

print(df) # can see that there is a NaN value in the dataframe

print(df.info())     # says that there are 3 non-null counts for column 'Age' instead of 2
print(df.isnull())   # says that the age value in the third row is not null 
```

#### Problem description

df.info() should output 2 non-null count for column 'Age' since a NaN value has been deliberately placed for one of the elements however it outputs 3 non-null count for column 'Age'.
Furthermore, df.isnull() method should output "True" for the third element in column 'Age' however it outputs "False". 

#### Expected Output

df.info():

Data columns (total 2 columns):
   Column  Non-Null Count  Dtype  
 0   Name    3 non-null      object 
 1   Age        **2** non-null      float64
dtypes: float64(1), object(1)

AND

df.isnull():
    Name    Age
0  False  False
1  False  False
2  False  **TRUE**

#### Output of ``pd.show_versions()``

<details>

>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.8.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.4.0
Version          : Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.4
numpy            : 1.18.5
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 57.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.24.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.3
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by fangchenli** [comment]
This is fixed on master. But I'm not sure which PR actually fixed this.

```
INSTALLED VERSIONS
------------------
commit           : 98e22297bb66f81ff4c1d4f1c3277cfe8c6b9ce7
python           : 3.8.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.5.0
Version          : Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.0.dev0+58.g98e22297bb
numpy            : 1.20.3
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.2
setuptools       : 49.6.0.post20210108
Cython           : 0.29.23
pytest           : 6.2.4
hypothesis       : 6.14.0
......

    Name   Age
0    tom  20.0
1   mike  30.0
2  julie   NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    3 non-null      object 
 1   Age     2 non-null      float64
dtypes: float64(1), object(1)
memory usage: 176.0+ bytes
None

    Name    Age
0  False  False
1  False  False
2  False   True
---------------------------

    Name   Age
0    tom  20.0
1   mike  30.0
2  julie   NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    3 non-null      object 
 1   Age     2 non-null      float64
dtypes: float64(1), object(1)
memory usage: 176.0+ bytes
None

    Name    Age
0  False  False
1  False  False
2  False   True
```

**Comment by lithomas1** [comment]
@byunwj This looks like a duplicate of issue #41149. It looks like you might need a numpy version upgrade to 1.20 too.

**Comment by byunwj** [comment]
> This is fixed on master. But I'm not sure which PR actually fixed this.
> 
> ```
> INSTALLED VERSIONS
> ------------------
> commit           : 98e22297bb66f81ff4c1d4f1c3277cfe8c6b9ce7
> python           : 3.8.10.final.0
> python-bits      : 64
> OS               : Darwin
> OS-release       : 20.5.0
> Version          : Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101
> machine          : arm64
> processor        : arm
> byteorder        : little
> LC_ALL           : None
> LANG             : en_US.UTF-8
> LOCALE           : en_US.UTF-8
> 
> pandas           : 1.4.0.dev0+58.g98e22297bb
> numpy            : 1.20.3
> pytz             : 2021.1
> dateutil         : 2.8.1
> pip              : 21.1.2
> setuptools       : 49.6.0.post20210108
> Cython           : 0.29.23
> pytest           : 6.2.4
> hypothesis       : 6.14.0
> ......
> 
>     Name   Age
> 0    tom  20.0
> 1   mike  30.0
> 2  julie   NaN
> 
> <class 'pandas.core.frame.DataFrame'>
> RangeIndex: 3 entries, 0 to 2
> Data columns (total 2 columns):
>  #   Column  Non-Null Count  Dtype  
> ---  ------  --------------  -----  
>  0   Name    3 non-null      object 
>  1   Age     2 non-null      float64
> dtypes: float64(1), object(1)
> memory usage: 176.0+ bytes
> None
> 
>     Name    Age
> 0  False  False
> 1  False  False
> 2  False   True
> ---------------------------
> 
>     Name   Age
> 0    tom  20.0
> 1   mike  30.0
> 2  julie   NaN
> 
> <class 'pandas.core.frame.DataFrame'>
> RangeIndex: 3 entries, 0 to 2
> Data columns (total 2 columns):
>  #   Column  Non-Null Count  Dtype  
> ---  ------  --------------  -----  
>  0   Name    3 non-null      object 
>  1   Age     2 non-null      float64
> dtypes: float64(1), object(1)
> memory usage: 176.0+ bytes
> None
> 
>     Name    Age
> 0  False  False
> 1  False  False
> 2  False   True
> ```

Thanks a lot for your answer.
Do you mind telling me how I can install pandas version of 1.4.0.dev0+58.g98e22297bb?
And do you happen to know if it's compatible with tensorflow 2.4.0-rc0?
Thank you in advance.

**Comment by fangchenli** [comment]
> Do you mind telling me how I can install pandas version of 1.4.0.dev0+58.g98e22297bb?
> and perhaps if it's compatible with tensorflow 2.4.0-rc0?

You can install pandas master with `pip install git+https://github.com/pandas-dev/pandas.git`

I'm not sure if it's compatible with any specific version of TensorFlow.

**Comment by byunwj** [comment]
Updating numpy to the lastest version solved the issue.
Thanks everyone for your help!
