### ISSUE TITLE
DOC: .style.set_table_styles example produces error

### ISSUE THREAD

**Issue by mjb-v9-5-2** [pandas-dev/pandas#42133]
#### Location of the documentation

https://pandas.pydata.org/docs/user_guide/style.html

#### Documentation problem

The docs include sample code to demonstrate how a .style.set_table_styles method can be chained using the overwrite=False arg. 

```
html = html.set_table_styles({
    'B': [dict(selector='', props=[('color', 'green')])],
    'C': [dict(selector='td', props=[('color', 'red')])],
    }, overwrite=False)
html
```

Copying and pasting the sample produces an error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-93-53e5b3797780> in <module>
      2 'A': [ {'selector':'',   'props': [('color', 'red')]}],
      3 'B': [ {'selector':'td', 'props': ['color: blue']}]
----> 4 }, overwrite=False)

TypeError: set_table_styles() got an unexpected keyword argument 'overwrite'

```

**Comment by attack68** [comment]
The docs is written in a jupyter notebook which is executed by the docs builder. The fact that it works on the web means that it works for the version of the docs its describes which is 1.2.4.

The `overwrite` argument existed at earliest 1.2.0. I would suggest your pandas version is  earlier than that.

Please close this issue if so.

**Comment by mjb-v9-5-2** [comment]
I see. Yes, the pip repository gives me 1.1.5. (Upgrading that seems easier said than done). That's identified the source of the problem, thank you.

**Comment by attack68** [comment]
`pip install --upgrade pandas`

**Comment by mjb-v9-5-2** [comment]
I would have thought so. But upon receiving the upgrade command, pip reports "Requirement already satisfied .... ... =2.7.3->pandas) (1.15.0) ".

Uninstalling and installing again makes no difference. Neither does pip install pandas==1.2.4

If there was a missing dependency that precented a 1.2.4 install, it would say, would it not?
