### ISSUE TITLE
STYLE don't use in-line comments for configuring flake8

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#42141]
Check this note from the flake8 docs:

> 
> Following the recommended settings for Python’s configparser, Flake8 does not support inline comments for any of the keys. So while this is fine:
> 
> [flake8]
> per-file-ignores =
>     # imported but unused
>     __init__.py: F401
> 
> this is not:
> 
> [flake8]
> per-file-ignores =
>     __init__.py: F401 # imported but unused
> 

However, that's exactly what we do:

https://github.com/pandas-dev/pandas/blob/98e22297bb66f81ff4c1d4f1c3277cfe8c6b9ce7/setup.cfg#L71-L104

In each case, the comment should be moved to be on its own line, on the line before the code

Else, we risk accidentally putting something in the comments that'll mess with how flake8 works

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by MarcoGorelli** [comment]
awesome, PRs welcome
