### ISSUE TITLE
REF: consolidate object dtype handling for any/all

### ISSUE THREAD

**Issue by mzeitlin11** [pandas-dev/pandas#42175]
From https://github.com/pandas-dev/pandas/pull/42085#discussion_r655520599, for groupby any/all we have bool coercing logic in https://github.com/pandas-dev/pandas/blob/6ca875787b60b5d45ad0136ff501f5d523719a3a/pandas/core/groupby/groupby.py#L1521-L1526

Would be nice to share this with handling in https://github.com/pandas-dev/pandas/blob/6ca875787b60b5d45ad0136ff501f5d523719a3a/pandas/core/nanops.py#L534-L539
though complicated by shape requirement differences and the complicated nature of `_get_values`

**Comment by jbrockmendel** [comment]
I'm on board in principle, but it isn't obvious to me how to move forward with this.  Closing.
