### ISSUE TITLE
BUG: wrong dateutil dependency link in dependency graph

### ISSUE THREAD

**Issue by soxofaan** [pandas-dev/pandas#42199]
- [x] I have checked that this issue has not already been reported.

Probably not a bug in pandas per se, but it might be useful to be aware of this: 
I noticed that the `python-dateutil` dependency on this github dependency graph page https://github.com/pandas-dev/pandas/network/dependencies points to https://github.com/clones/python-dateutil which is a strange 1-commit mirror repo from 2008, instead of the official repo https://github.com/dateutil/dateutil/

**Comment by fangchenli** [comment]
Thanks for reporting this. We probably need to report this issue to GitHub.

**Comment by fangchenli** [comment]
I've contacted GitHub Support. And they've fixed the link.
