### ISSUE TITLE
June 2021 Docs Meeting - CANCELLED

### ISSUE THREAD

**Issue by afeld** [pandas-dev/pandas#42202]
Sorry folks, have a conflict and I didn't reach out about finding someone else to host early enough. See you in a month!

- [ ] Remove from calendar

**Comment by jorisvandenbossche** [comment]
I *think* I deleted it from the calendar, and that seems to have worked according to https://pandas.pydata.org/docs/development/meeting.html

**Comment by afeld** [comment]
I haven't been able to spend much time on pandas recently, and it didn't seem like we had enough attendance to justify finding another facilitator for the docs meetings. Sigh. They had a good run. @jorisvandenbossche Mind pulling them off the calendar for now?
