### ISSUE TITLE
Absolute value or minus sign missing in docstrings for head and tail

### ISSUE THREAD

**Issue by olbermann** [pandas-dev/pandas#42204]
In the docstrings for the head and tail functions (in pandas/core/generic.py) there is an absolute value or minus sign missing:
e.g. in tail docstring
```
For negative values of `n`, this function returns all rows except
        the first `n` rows, equivalent to ``df[n:]``.
```

should read something like
```
For negative values of `n`, this function returns all rows except
        the first `np.abs(n)` rows, equivalent to ``df[np.abs(n):]``.
```

or 

```
For negative values of `n`, this function returns all rows except
        the first `-n` rows, equivalent to ``df[-n:]``.
```
Similarly for head.

**Comment by parkdj1** [comment]
I think the original should be correct since it says 'for negative values of' n, implying we are thinking of n as some positive integer and considering the cases in which the input is the negative value of such n

**Comment by olbermann** [comment]
No, the original is wrong. It says 'for negative values of n', this means the same as  'in the case that n is negative'. 

You are right that it would be easier to think of variables with positive values: Maybe one should say
``For a positive integer `k`, the function `df.tail(-k)` returns all rows except the first `k` rows, equivalent to `df[k:]`.
``

**Comment by mzeitlin11** [comment]
+1 on that being clearer wording. Would you be interested in making a pr?

**Comment by parkdj1** [comment]
Agreed it never hurts to make documentation clearer. I can take if @olbermann doesn’t want to

**Comment by jackgoldsmith4** [comment]
take

**Comment by jackgoldsmith4** [comment]
I am going to make changes to the docstrings based on the feedback on #42216
