### ISSUE TITLE
CI: azure windows timeouts

### ISSUE THREAD

**Issue by mzeitlin11** [pandas-dev/pandas#42236]
Seeing lots of timeouts on `Windows py38_np18` builds, for example https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=62155&view=logs&j=404760ec-14d3-5d48-e580-13034792878f&t=f81e4cc8-d61a-5fb8-36be-36768e5c561a

The main tests showing up in the slowest durations are the groupby `numba` tests. Would it make sense to do something similar to #42024 in the groupby conftest to reduce the number of combinations run? Also in that run seeing warnings like 

```
pandas/tests/window/test_numba.py: 14 warnings
  D:\a\1\s\pandas\core\window\numba_.py:74: NumbaPerformanceWarning: 
  The keyword argument 'parallel=True' was specified but no transformation for parallel execution was possible.
  
  To find out why, try turning on parallel diagnostics, see https://numba.pydata.org/numba-doc/latest/user/parallel.html#diagnostics for help.
  
  File "pandas\core\util\numba_.py", line 109:
  
              def impl(data, *_args):
              ^
  
    result[i] = numba_func(window, *args)
```

so the `parallel=True` case might not be testing anything. cc @mroeschke

**Comment by simonjayhawkins** [comment]
doesn't look like #42237 fixed this https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=62162&view=logs&j=404760ec-14d3-5d48-e580-13034792878f&t=f81e4cc8-d61a-5fb8-36be-36768e5c561a

**Comment by mzeitlin11** [comment]
On attempt #2 of that run it succeeded in just 36 min, used 2 workers. The attempt #1 that timed out spun up 4 workers, as did the failing run posted in the issue body.  Maybe enforcing <= 2 workers would help (could it be some kind of memory issue?)
