### ISSUE TITLE
PERF: regression in DataFrame construction from nested dict

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#42248]
#41785 removed some cython code to handle this case (because it could also be handled by existing python code, AFAIU), but this de-duplication caused a big slowdown in one of the benchmarks: https://pandas.pydata.org/speed/pandas/#frame_ctor.FromDicts.time_nested_dict_int64?python=3.8&Cython=0.29.21

It's of course a trade-off between the maintenance cost of having the cython version versus the performance benefit. But if the benchmark is representative, a 5-6x slowdown seems quite a lot for getting rid of a relatively small piece of cython code.

_Originally posted by @jorisvandenbossche in https://github.com/pandas-dev/pandas/issues/41785#issuecomment-856827815_

**Comment by jbrockmendel** [comment]
> can you verify this?

This appears correct.  For context, this change was made as a follow-up to a bugfix where this de-duplication would have prevented the bug.  I agree 5-6x is a bigger slowdown than I expected.
