### ISSUE TITLE
BUG: expanding numba functions being cached with arguments

### ISSUE THREAD

**Issue by lucaswebb** [pandas-dev/pandas#42287]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample

```python
def expanding_multiply(values, x):
    arr = values[-1]
    arr[1] = values[:,0].sum() * x
    return arr

df = pd.DataFrame({'id': [1, 2, 3], 'value': [0, 0, 0]})

def call_expanding(x):
    expanded = df.expanding(method="table").apply(expanding_multiply, raw=True, engine="numba", args=x)
    return expanded

call_expanding(tuple([1]))
#  1.0    1.0
#  2.0    3.0
#  3.0    6.0
```
```python
call_expanding(tuple([2]))
#  1.0    1.0
#  2.0    3.0
#  3.0    6.0
```

#### Problem description

When using expanding.apply with engine='numba' calling the same function with different arguments gives the same results as the first time it was called. I believe this is because the function is being cached with its arguments.

https://github.com/pandas-dev/pandas/blob/e8dbdb07782437ad592736f6d212d0af5e7324be/pandas/core/window/rolling.py#L1172-L1175

#### Expected Output
```python
call_expanding(tuple([2]))
# 1.0    2.0
# 2.0    6.0
# 3.0    12.0
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 2dd9e9ba9009a40191c0c0b96262fa3939d609f0
python           : 3.7.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.5.0
Version          : Darwin Kernel Version 19.5.0: Thu Apr 30 18:25:59 PDT 2020; root:xnu-6153.121.1~7/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.0rc1
numpy            : 1.19.1
pytz             : 2019.1
dateutil         : 2.8.1
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : None
psycopg2         : 2.8.2 (dt dec pq3 ext lo64)
jinja2           : 3.0.1
IPython          : 7.18.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.3
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.53.1

</details>

**Comment by lucaswebb** [comment]
I believe the issue is actually located in the following two places:

https://github.com/pandas-dev/pandas/blob/e8dbdb07782437ad592736f6d212d0af5e7324be/pandas/core/window/rolling.py#L525

https://github.com/pandas-dev/pandas/blob/e8dbdb07782437ad592736f6d212d0af5e7324be/pandas/core/window/numba_.py#L215-L218

*args parameter isn't being passed in either place.

**Comment by mzeitlin11** [comment]
Thanks for reporting and investigating this @lucaswebb! This looks similar to #41647, would you be interested in putting up a pr to fix this? cc @mroeschke
