### ISSUE TITLE
CI: Re-starting on Github Actions Posix build re-runs all of them

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#42307]
Frequently one of the posix github action builds will fail because conda won't download.  Hitting the re-run button causes _all_ of them to re-run instead of just that one.  Can we find a way to only re-run the affected build?

**Comment by lithomas1** [comment]
Doesn't seem to be a feature unfortunately.
xref https://github.com/actions/runner/issues/432

**Comment by simonjayhawkins** [comment]
can we put the jobs in separate workflows. they only need to be in the same workflow file if some subsequent action depends on their success?

**Comment by simonjayhawkins** [comment]
if we are using a matrix then probably not, but CI/Checks and Web and Docs maybe be a good starting point.

**Comment by lithomas1** [comment]
SGTM

**Comment by lithomas1** [comment]
https://github.com/github/roadmap/issues/271. Hooray, this is in Github's Roadmap now.

Tagging as No Action and Closing Candidate. We can close once github adds this feature.

**Comment by mroeschke** [comment]
Since Github is in change of releasing this feature and not us, I think we can just wait until we see the feature in the CI one day. Closing
