### ISSUE TITLE
WEB: Use appropriate favicon when user has browser in dark mode

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#42314]
We've got two versions of our logo, one for light backgrounds, and another one for dark backgrounds: https://pandas.pydata.org/about/citing.html#brand-and-logo.

Modern browsers usually support a dark mode, and when users have it activated, our favicon (our logo for light backgrounds) doesn't look really nice:

![Screenshot at 2021-06-29 13-18-05](https://user-images.githubusercontent.com/10058240/123855087-b4a44000-d8dc-11eb-9949-f7aa04389592.png)

Looks like there are ways to change the favicon colors (or the favicon itself I guess) based on the light theme of the browser user. For example, see this article: https://catalin.red/svg-favicon-light-dark-theme/

It'd be nice to show the dark background logo as a favicon to web visitors using a dark theme for their browser.

**Comment by shourya5** [comment]
I would like to contribute.
I think the way to do this would be to use the  CSS prefers-colour-scheme: dark media feature to change the logo according to the user theme.

**Comment by shourya5** [comment]
take
