### ISSUE TITLE
DOC: timedelta return type

### ISSUE THREAD

**Issue by max-sixty** [pandas-dev/pandas#42316]
#### Location of the documentation

https://github.com/pandas-dev/pandas/blob/master/pandas/core/tools/timedeltas.py#L70

#### Documentation problem

Is `numpy.array of timedelta64` the correct return time for to_timedelta? I see it here as `TimedeltaIndex`: https://github.com/pandas-dev/pandas/blob/master/pandas/tests/indexes/timedeltas/test_timedelta.py#L27

**Comment by loicdiridollou** [comment]
Hey @max-sixty,
I looked at it and indeed it does not return a `numpy.array`, it will either be a `TimedeltaIndex` as in the following case `pd.to_timedelta(np.arange(5), unit='d')` or `Timedelta` (from `pandas._libs.tslibs.timedeltas.Timedelta`) in the following case `pd.to_timedelta("15.5us")` (when passing just a string it seems)
I have opened a PR to update the docs.
Have a good day!
