### ISSUE TITLE
RLS: Missing assets in release 1.3.0

### ISSUE THREAD

**Issue by benoit9126** [pandas-dev/pandas#42347]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

#### Problem description

The list of assets published on Pypi for pandas 1.3.0 does not contain assets for Python 3.8 and Python 3.9. See the list [here](https://pypi.org/project/pandas/1.3.0/#files)

For comparison, in Pandas 1.2.5, the list of published assets is [here](https://pypi.org/project/pandas/1.2.5/#files).

#### Expected Output

I expected the same list of assets as the one of Pandas 1.2.5 for Pandas 1.3.0.

**Comment by TomAugspurger** [comment]
cc @simonjayhawkins. Looks like some of the wheel build tasks failed: https://dev.azure.com/pandas-dev/pandas-wheels/_build/results?buildId=62474&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05.

Might be worth adding a sanity check to https://github.com/pandas-dev/pandas-release to verify that the number of wheels looks correct.

**Comment by benoit9126** [comment]
In this case, the source archive is also not available...

**Comment by simonjayhawkins** [comment]
> cc @simonjayhawkins. Looks like some of the wheel build tasks failed: https://dev.azure.com/pandas-dev/pandas-wheels/_build/results?buildId=62474&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05.

all the wheels built.  18 wheels in staging area (6 linux, 6 windows, 3 mac, 3 aarch64)

but all jobs restarted when one failed. and then others failed but had wheels from previous build.

the missing wheels in PyPI are due to storage restriction.
