### ISSUE TITLE
BUG: pandas 1.3.0 is only available for python 3.7

### ISSUE THREAD

**Issue by Alphadelta14** [pandas-dev/pandas#42344]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Problem description

Using a package manager (pip 21.1.1 on python 3.8), pandas 1.3.0 is not installable.
This project has neither a source distribution nor any non-3.7 versions for the 1.3.0 version of pandas according to: https://pypi.org/project/pandas/#files

![image](https://user-images.githubusercontent.com/480845/124293910-22db4380-db25-11eb-8559-e10b0f2464ec.png)

#### Expected Output

`pip install pandas==1.3.0` would work if python 3.8 is platform.

**Comment by jreback** [comment]
1.3 is still in the process of being released. please wait.

**Comment by jreback** [comment]
see https://github.com/pandas-dev/pandas/issues/40169
