### ISSUE TITLE
STYLE disallow Series | AnyArrayLike

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#42359]
PR should be made to https://github.com/pandas-dev/pandas-dev-flaker

idea is to disallow `foo: Series | AnyArrayLike`, as `Series` is array-like already

This came out of this review: https://github.com/pandas-dev/pandas/pull/41955#discussion_r663390463

**Comment by jramirez857** [comment]
Hello, I'd like to try taking this on!

**Comment by MarcoGorelli** [comment]
Awesome @jramirez857  - a PR should probably go to https://github.com/pandas-dev/pandas-dev-flaker , let me know if you want / need any help

**Comment by jramirez857** [comment]
Thank you, @MarcoGorelli for offering help. Yes, this is my first contribution and if you could point me in the right direction that would be very helpful.  Here is what I currently have. 

`import ast
from typing import Iterator, Tuple

from pandas_dev_flaker._data_tree import State, register

MSG = "PDF026 found union between State and AnyArrayLike in type hint"

@register(ast.FunctionDef)
def visit_arg(
    state: State,
    node: ast.FunctionDef,
    parent: ast.AST,
) -> Iterator[Tuple[int, int, str]]:

    arguments = node.args
    for arg in arguments:
        if (isinstance(arg.annotation, ast.BinOp)):
            yield node.lineno, node.col_offset, MSG
`

I am currently trying out using registering ast.FunctionDef using the decorator and I think I will need to traverse a binary tree of [BinOp](https://docs.python.org/3/library/ast.html#ast.BinOp) of argument nodes. I have written a test case shown below:
 
 
 @pytest.mark.parametrize(
    "source, expected",
    (
        pytest.param(
            "def dot(foo, other: Series | DataFrame | AnyArrayLike): pass",
            "1:0: PDF026 Both State and AnyArrayLike in type hint",
            id="Series DataFrame AnyArrayLike type hint",
        ),
    ),
)
def test_violation(source, expected):
    (result,) = results(source)
    assert result == expected
`

I am currently figuring out how I can try to step through it in the repl. If you have any tips on how I could step through the tree traversal within the pandas-dev-flake environment it would be a huge help for my debugging purposes.

**Comment by MarcoGorelli** [comment]
You might want to have a look at `pyupgrade`, they do some similar things (for example to rewrite `Optional[int]` as `int | None`)

**Comment by Pydare** [comment]
hello, is it too late to try this out?

**Comment by MarcoGorelli** [comment]
Hey @Pydare - I don't think anyone's working on this, though @jramirez857 please do speak up if you still are

**Comment by jramirez857** [comment]
Feel free to take this @Pydare. I made some progress initially but have not been actively working on this recently.

**Comment by Pydare** [comment]
take
