### ISSUE TITLE
BUG:path='C:\Users\Ebunlomo.A.Sonola\Credit Card Customer Data.xlsx' df=pd.read_excel("C:\Users\Ebunlomo .A. Sonola\Credit Card Customer Data.xlsx")

### ISSUE THREAD

**Issue by ebun2all** [pandas-dev/pandas#42372]
- [ ] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here

```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by ebun2all** [comment]
path='C:\Users\Ebunlomo.A.Sonola\Credit Card Customer Data.xlsx'
df=pd.read_excel("C:\Users\Ebunlomo .A. Sonola\Credit Card Customer Data.xlsx")
error:
File "<ipython-input-15-b37a0b27c366>", line 1
    path='C:\Users\Ebunlomo.A.Sonola\Credit Card Customer Data.xlsx'
         ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by ivanovmg** [comment]
Can you try to escape backslash with another backslash, or use raw strings in your paths?

Raw string:
```
path = r'C:\Users\Ebunlomo.A.Sonola\Credit Card Customer Data.xlsx'
```

Escape backslash:
```
path = 'C:\\Users\\Ebunlomo.A.Sonola\\Credit Card Customer Data.xlsx'
```

**Comment by ebun2all** [comment]
Thanks alot , thanks for the help. much appreciated.
Regards,
Sonola
