### ISSUE TITLE
DOC: Formatting Issue

### ISSUE THREAD

**Issue by DavidDeLord** [pandas-dev/pandas#42371]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html

#### Documentation problem

Two of the * symbols used for the multiplication and power operators emphasize the comma in between them instead of being displayed: (+, -, /, , *) instead of (+, -, /, *, **).

#### Suggested fix for documentation

IDK should be easy to fix, though.

**Comment by mzeitlin11** [comment]
Thanks for noticing this @DavidDeLord! Contributions welcome to fix this

**Comment by Varun270** [comment]
@mzeitlin11 I would like to solve this issue, Can you please confirm whether this issue is still open and if it is please do assign me the issue.
