### ISSUE TITLE
BUG: find_common_type raises an exception on Series

### ISSUE THREAD

**Issue by YarShev** [pandas-dev/pandas#42397]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

#### Code Sample, a copy-pastable example

```python
from pandas.core.dtypes.cast import find_common_type
import pandas
s = pandas.Series(["int", "float"])
find_common_type(s)
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

#### Problem description

The exception is raised in 1.3.0 whereas the method works correctly in 1.2.5.

#### Expected Output

Output for 1.2.5

```python
from pandas.core.dtypes.cast import find_common_type
import pandas
s = pandas.Series(["int", "float"])
find_common_type(s)
dtype('float64')
```

#### Output of ``pd.show_versions()``

<details>

pandas           : 1.3.0
numpy            : 1.20.3
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 21.1.2
setuptools       : 49.6.0.post20210108
Cython           : None
pytest           : 6.2.4
hypothesis       : None
sphinx           : 4.0.2
blosc            : None
feather          : 0.4.1
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.24.1
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : 2021.05.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.2.2
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : 0.15.0
pyarrow          : 3.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.6.3
sqlalchemy       : 1.4.18
tables           : 3.6.1
tabulate         : None
xarray           : 0.18.2
xlrd             : 2.0.1
xlwt             : None
numba            : None

</details>

**Comment by YarShev** [comment]
The issue persists even on np.array.

```python
from modin.backends.pandas.parsers import find_common_type_cat
import numpy as np
a = np.array(["int", "float"])
find_common_type_cat(a)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by jreback** [comment]
this looks like a modin routine
pls report to them

**Comment by YarShev** [comment]
ouh, sorry :D

**Comment by YarShev** [comment]
I fixed the examples above. The problem comes from pandas so I am reopening the issue.

**Comment by jreback** [comment]
i'll reopen but i dont believe this is designed to accept what you are passing 

look at the signature

**Comment by jreback** [comment]
nor is this public api in any way

**Comment by YarShev** [comment]
Yes, the signature says `types : list of dtypes` but the function worked in 1.2.5. Is not this a regression?

**Comment by jreback** [comment]
list is correct

series or ndarray are not lists

**Comment by YarShev** [comment]
I understand but if the function would be expanded to be worked with array-like objects, it would be great.

**Comment by jreback** [comment]
not likely this is pretty low level on purpose
