### ISSUE TITLE
BUG: Running pandas df.progress_apply in notebook run under vscode generates 'dataframe object has no attribute _is_builtin_func'

### ISSUE THREAD

**Issue by dickreuter** [pandas-dev/pandas#42393]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```
df['col'].progress_apply(lambda x: x+1)

```

#### Problem description

generates error message when run in notebook under vscode (but works fine when run in a normal jupyter notebook)
dataframe object has no attribute _is_builtin_func

#### Expected Output
Should show a progress bar and perform the apply lambda

#### Output of ``pd.show_versions()``
1.3.0

</details>

**Comment by jreback** [comment]
progress_apply is not a pandas method

you just be importing something that patches

**Comment by jreback** [comment]
closing - you would need to investigate with the package that provides the method
