### ISSUE TITLE
DOC: Spelling mistake in code example of Styler.to_latex documentation

### ISSUE THREAD

**Issue by Lullatsch** [pandas-dev/pandas#42409]
#### Location of the documentation
"https://pandas.pydata.org/docs/reference/api/pandas.io.formats.style.Styler.to_latex.html"

#### Documentation problem

Last example under "CSS Conversion" which uses the `convert_css` parameter writes `css_convert` instead.

#### Suggested fix for documentation

Simply replace `css_convert` with `convert_css`

**Comment by mzeitlin11** [comment]
Thanks for pointing this out @Lullatsch!

**Comment by STAMcM** [comment]
take

**Comment by STAMcM** [comment]
Sorry, I didn't think to ask before assigning to myself, @Lullatsch would you like to do this? Or am I good to use this as a chance to raise my first PR?

**Comment by Lullatsch** [comment]
No you're good. :) Just wanted to point out the mistake.
