### ISSUE TITLE
ENH: Do same operations to a list of pandas objects, Series or DataFrames.

### ISSUE THREAD

**Issue by wangzhe3224** [pandas-dev/pandas#42414]
#### Is your feature request related to a problem?

The idea is basically do same operations to a list of pandas objects, Series or DataFrames.

#### Describe the solution you'd like

There a a lot of time I do following operations
```python
df1.sum().plot()
df2.sum().plot()
df3.sum().plot()
```
I wish in pandas I could do following:

```python
dfs = MetaDf(df1, df2, df3)
dfs.sum().plot()
```

#### API breaking implications

This should not affect APIs.

#### Describe alternatives you've considered

I tried something here: https://github.com/wangzhe3224/compare
But it does not work well with chaining operations.

```python
import pandas as pd 

from compare.core import Comp

a = pd.Series([1,2,3])
b = pd.Series([1,2,3])
c = Comp(a, b)
c.shift(1)
c.sum()
# we cannot do this yet...
# c.mean() + c.std()
# c.plot()
```

#### Additional context

None

**Comment by jreback** [comment]
pandas is already heavily overloaded api and not likely to expand in this direction.

```
for df in dfs:
  df.sum().plot()
```

is pretty idiomatic here
