### ISSUE TITLE
BUG: .dt.isocalendar().week returns unexpected dtype (UInt32)

### ISSUE THREAD

**Issue by outa** [pandas-dev/pandas#42429]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
data = {'date': pd.date_range('2021-07-01', freq='D', periods=7)}
df = pd.DataFrame(data)

weeknumbers = df.date.dt.isocalendar().week

weeknumbers
0    26
1    26
2    26
3    26
4    27
5    27
6    27
Name: week, dtype: UInt32
```

#### Problem description

This returns dtype UInt32, with `weeknumbers.values` being an "IntegerArray" from pandas.

I am not sure if this is intended, but I discovered this because I replaced the deprecated `dt.weekofyear` with `dt.isocalendar().week` and then had `weeknumbers.values.tolist()` at a later point in my code which results in an AttributeError.

#### Expected Output
I would have expected the dtype to be int64, or, more importanty, the the `.values` being a numpy array, so that `.values.tolist()` works as expected.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f00ed8f47020034e752baf0250483053340971b0
python           : 3.9.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.8.0-59-generic
Version          : #66-Ubuntu SMP Thu Jun 17 00:46:01 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : de_DE.UTF-8
LOCALE           : de_DE.UTF-8

pandas           : 1.3.0
numpy            : 1.21.0
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.3
setuptools       : 52.0.0.post20210125
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by rhshadrach** [comment]
This was indeed intentional, e.g https://github.com/pandas-dev/pandas/pull/33220#discussion_r405612394. As with any pandas Series, you can directly call `tolist` without accessing the underlying array:

    df.date.dt.isocalendar().week.tolist()

Does this satisfy your use-case?

**Comment by outa** [comment]
Yes it does. Thanks for the clarification!
