### ISSUE TITLE
Unclear warning message (SettingWithCopyWarning)

### ISSUE THREAD

**Issue by Wallerand-Artefact** [pandas-dev/pandas#42426]
Hi, 

Very often when manipulating pandas DataFrames I had a SettingWithCopyWarning and I did not understand why because the warning message was telling me to use the syntax .loc[row_indexer,col_indexer] = value , which I was already using !
The issue actually had nothing to do with the .loc syntax but with the fact that the dataframe I was trying to modify was created by applying a filter on another dataframe (something like : df1 = df0[df0.column_x == value_x]), therefore there was an ambiguity on whether the original dataframe should be modified or not. In my case I did not want to modify df0 so the clean way of creating df1 was df1 = df0[df0.column_x == value_x].copy(), which solved the issue and I did not get the warning anymore.
I think this a very common issue, this is why, in my opinion, it could be a nice idea to include in the warning message that if the issue is not coming from the .loc syntax, it is likely that it comes from the fact that the concerned dataframe is probably a filtered copy of another dataframe and that adding .copy() when defining this particular dataframe might solve the issue. 
I hope my message was clear enough, otherwise I can try to explain it better if necessary.

Have a good day, 

Wallerand

**Comment by mroeschke** [comment]
Thanks for the issue and sorry for the lack of response over the years, but we would need a reproducible example in order to diagnose the exact instance of this warning so closing. Happy to reopen with an example
