### ISSUE TITLE
DOC: Inconsistency in Setting Up Dev Env

### ISSUE THREAD

**Issue by DavidDeLord** [pandas-dev/pandas#42420]
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/dev/development/contributing_environment.html#installing-a-c-compiler

**Note**: You can check the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/).

#### Documentation problem

> You will need Build Tools for Visual Studio 2017.
> 
> Warning
> 
> You DO NOT need to install Visual Studio 2019. You only need “Build Tools for Visual Studio 2019”

#### Suggested fix for documentation

Someone should update. This is confusing for me because I'm trying to set one up.

**Comment by rhshadrach** [comment]
@DavidDeLord thanks for the report, but I don't see what is inconsistent. The former says you need the `Build Tools for Visual Studio` and the latter says you don't need `Visual Studio`.

**Comment by DavidDeLord** [comment]
yep, should be changed to 2019 which is the one the download link links to

**Comment by lithomas1** [comment]
PRs to fix welcome. :)

**Comment by DanAbara** [comment]
Hi @lithomas1, I'm a first time seeking tasks. I would like to take this. Please assign to me.

**Comment by DanAbara** [comment]
take

**Comment by DanAbara** [comment]
Just looked through existing PRs and it appears someone already fixed this.
