### ISSUE TITLE
BUG: 1D slices over extension types turn into N-dimensional slices over ExtensionArrays

### ISSUE THREAD

**Issue by frreiss** [pandas-dev/pandas#42430]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [X] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
class LoggingStringArray(pd.arrays.StringArray):
    """Extend StringArray to log arguments to __getitem__"""
    def __getitem__(self, item):
        print(f"Argument to __getitem__ is '{item}'")
        return super().__getitem__(item)

df = pd.DataFrame({"col1": LoggingStringArray(np.array(["hello", "world"], dtype=object))})
_ = df.iloc[:1]
```

Expected output:
```
Argument to __getitem__ is 'slice(None, 1, None)'
```

Actual output:
```
Argument to __getitem__ is '(Ellipsis, slice(None, 1, None))'
```

#### Problem description

If a DataFrame contains extension types, the block manager turns a 1D slice in the form `DataFrame.iloc[slice(x, y, z)]` into an N-dimensional slice over the ExtensionArray of the form `__getitem__((Ellipsis, slice(x, y, z))` . This problem breaks the `__getitem__()` method on one of our extension types in [Text Extensions for Pandas](https://github.com/CODAIT/text-extensions-for-pandas).

The `__getitem__` methods in Pandas' built-in extension types happens to work when fed this kind of n-dimensional slice
--- they just ignore the `Ellipsis` in the first position of the tuple. But I don't think they're supposed to accept that type of input.

The root cause is the new method `Block.getitem_block_index()`, added during some performance optimizations introduced in pandas-dev/pandas#40353:

```python
    def getitem_block_index(self, slicer: slice) -> Block:
        """
        Perform __getitem__-like specialized to slicing along index.

        Assumes self.ndim == 2
        """
        # error: Invalid index type "Tuple[ellipsis, slice]" for
        # "Union[ndarray, ExtensionArray]"; expected type "Union[int, slice, ndarray]"
        new_values = self.values[..., slicer]  # type: ignore[index]
        return type(self)(new_values, self._mgr_locs, ndim=self.ndim)
```

This method assumes that the contents of the block are 2-dimensional. The `ExtensionBlock` class inherits this method from `EABackedBlock`, which inherits it from `Block`.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f00ed8f47020034e752baf0250483053340971b0
python           : 3.7.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.5.0
Version          : Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.0
numpy            : 1.21.0
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.3
setuptools       : 52.0.0.post20210125
Cython           : None
pytest           : 6.2.4
hypothesis       : None
sphinx           : 4.0.2
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.25.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 4.0.1
pyxlsb           : None
s3fs             : None
scipy            : 1.7.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by jbrockmendel** [comment]
Is the logging output itself the problem?  If so, couldn't you patch `LoggingStringArray__getitem__` to drop the leading Ellipsis from the print call?

**Comment by samgd** [comment]
@jbrockmendel The `ExtensionArray.__getitem__` specification does not list `Ellipsis` as a valid index type: 

https://github.com/pandas-dev/pandas/blob/b72b6b260297cf31ba5e3558e431fff008eb9005/pandas/core/arrays/base.py#L294-L307

**Comment by frreiss** [comment]
Sorry @jbrockmendel , I missed the notification for your earlier response (https://github.com/pandas-dev/pandas/issues/42430#issuecomment-877650091).

Our extension type currently uses a workaround similar to what you describe. We check the inputs to `__getitem__` for leading `Ellipsis` elements and strip them off:
```python
    def __getitem__(self, item) -> Union["TensorArray", "TensorElement"]:
        """
        See docstring in `Extension   Array` class in `pandas/core/arrays/base.py`
        for information about this method.
        """
        # Return scalar if single value is selected, a TensorElement for single array
        # element, or TensorArray for slice
        if isinstance(item, int):
            [...]
        else:
            # BEGIN workaround for Pandas issue #42430
            if (pd.__version__ == "1.3.0" and isinstance(item, tuple) and len(item) > 1
                    and item[0] == Ellipsis):
                if len(item) > 2:
                    # Hopefully this case is not possible, but can't be sure
                    raise ValueError(f"Workaround Pandas issue #42430 not implemented "
                                     f"for tuple length > 2")
                item = item[1]
            # END workaround for issue #42430
            [...]
```
(see original code [here](https://github.com/CODAIT/text-extensions-for-pandas/blob/57638f5e4c0dcea2b75a57976c94afff972e0e23/text_extensions_for_pandas/array/tensor.py#L544)).

Having to use this kind of workaround is cumbersome for extension type developers. It's not clear what other variations of "multidimensional indexing expression that happens to work on a 1D numpy array" we're supposed to handle. If Pandas starts throwing additional variations on the theme at us, our extension types will break again.

Personally, I think that this issue would be best resolved by adding the following code to the class `EABackedBlock`:

```python
def getitem_block_index(self, slicer: slice) -> Block:
    """
    Override the superclass's implementation of this method, which assumes a 2D block, with
    code that works on a 1D extension array.
    """
    return type(self)(self.values[slicer], self._mgr_locs, ndim=self.ndim) 
```

I'd be happy to put in a PR with this change if it's acceptable.

**Comment by jbrockmendel** [comment]
> best resolved by adding the following code to the class EABackedBlock [...]

I guess I'd be OK with that short term, but longer-term there is a decent chance that we're going to move to having EAs support 2D, in which case that would be reverted and you'd need to handle this case

**Comment by jbrockmendel** [comment]
BTW looking at your code, you might want to subclass NDArrayBackedExtensionArray rather than ExtensionArray; many of its methods are better-optimized.

**Comment by jbrockmendel** [comment]
Fair point, it isn't publicly exposed and I don't have any plans on exposing it anytime soon.  On the other hand, I'm mostly responsible for that class and it isn't going anywhere.

**Comment by frreiss** [comment]
I've filed #42787 with the fix described above, with a slightly smaller patch due to other changes to the same code.

@jbrockmendel we'll take a look at the `NDArrayBackedExtensionArray` class and see if we can use it in future versions of our library. Is there a design doc or issue we can follow to track the status of 2D support for ExtensionArrays?

**Comment by jbrockmendel** [comment]
> Is there a design doc or issue we can follow to track the status of 2D support for ExtensionArrays?

Not really.  There has been a lack of consensus about it for  while now.

**Comment by vnmabus** [comment]
> > Is there a design doc or issue we can follow to track the status of 2D support for ExtensionArrays?
> 
> Not really. There has been a lack of consensus about it for while now.

Doesn't it make more sense to have a "Tensor" ExtensionArray, for storing one tensor per observation, all with the same dimensions? That would allow for having a "Time series" column or an "Image" column, for example.

**Comment by jbrockmendel** [comment]
Are all of your tensors the same shape?  This sounds like a use case for e.g. xarray

**Comment by vnmabus** [comment]
I mean having mixed data. Consider a case in which you have medical data. You have some scalar measurements for each patient, each on different columns, an electrocardiogram as one 1d tensor column, an image of the brain activity, as one 2d tensor column, etc.

**Comment by jbrockmendel** [comment]
@WillAyd the use case described here sounds a little bit like the nested data work you were doing a while back.  thoughts?

**Comment by frreiss** [comment]
> Are all of your tensors the same shape? This sounds like a use case for e.g. xarray

Sometimes it's useful to have a column of tensors without abandoning Pandas entirely. Our own use cases are similar to what @vnmabus describes -- the tensors are just one feature among many. For example we may have a DataFrame with one row for each token in a document and one column for each feature of the token. One of those features could be a BERT embedding or an n-gram, but most of them will be categorical or numeric.
