### ISSUE TITLE
DOC: Readme.md file have some grammatical errors 

### ISSUE THREAD

**Issue by Varun270** [pandas-dev/pandas#42447]
#### Location of the documentation
README.md file

#### Documentation problem
There are some unwanted commas and colons with grammatical error

#### Suggested fix for documentation

The fix is easy just have to grammatically correct the README file.

**Comment by Varun270** [comment]
I am solving this issue as of now but am facing trouble since I made some changes on the master branch and forgot to create a branch. I haven't staged that updated file. Can anyone tell me what can I do to fix this?

**Comment by vladu** [comment]
Commit your changes, but don't push. Then create the branch. That will have your changes. Then switch back to master and git reset --hard to the commit just before your first commit that's supposed to be on the branch.

**Comment by rhshadrach** [comment]
@Varun270 - Can you specify exactly what the issues are in the readme.

**Comment by Varun270** [comment]
@rhshadrach There are some grammatical mistakes , unwanted spaces and commas in README.md

**Comment by Varun270** [comment]
@vladu Let me try

**Comment by rhshadrach** [comment]
@Varun270 Issues of this nature need to be specific on what the errors are, otherwise a reviewer does not know whether a corresponding PR closes it. It is also okay to submit a PR that doesn't correspond to an issue.

**Comment by Varun270** [comment]
@rhshadrach  Ohh I am sorry I didn't know that since I am a beginner so I don't really have any idea how exactly things work here. I have generated the PR that resolves this issue. There is a total of 8 changes you can have a look at them.
