### ISSUE TITLE
BUG: NaN cannot be detected

### ISSUE THREAD

**Issue by sunpei-zju** [pandas-dev/pandas#42443]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
import numpy as np
pd.DataFrame([np.random.randn(10)]).rolling(window=5,axis=1).mean().isna()

```

#### Problem description

The NaN cannot be detected by pandas, it is just a toy example above. 
The result was:

```Python
       0      1      2      3      4      5      6      7      8      9

0  False  False  False  False  False  False  False  False  False  False
```

#### Expected Output

I believe that the desired result should be:
```Python
       0      1      2      3      4      5      6      7      8      9

0   True   True   True   True  False  False  False  False  False  False
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f00ed8f47020034e752baf0250483053340971b0
python           : 3.8.8.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.5.0
Version          : Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8
pandas           : 1.3.0
numpy            : 1.18.5
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1
setuptools       : 49.6.0.post20210108
Cython           : 0.29.23
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.22.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by lithomas1** [comment]
Hi @sunpei-zju, This issue seems similar to #41149, given that you are both on ARM and have an older numpy(1.18.5). Can you please try a bump of numpy to 1.20.0 and test if that fixes it?

**Comment by sunpei-zju** [comment]
> Hi @sunpei-zju, This issue seems similar to #41149, given that you are both on ARM and have an older numpy(1.18.5). Can you please try a bump of numpy to 1.20.0 and test if that fixes it?

**Comment by sunpei-zju** [comment]
@lithomas1 yes, you are right, thank you!
