### ISSUE TITLE
read_excel() modifies provided types dict when accessing file with duplicate column

### ISSUE THREAD

**Issue by cdol** [pandas-dev/pandas#42462]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of pandas.
- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

_test.xlsx :_
| a | a | b | c |
|---|---|---|---|
| 1 | 1 | b1| c1|
| 2 | 2 | b2| c2|
| 3 | 3 | b3| c3|

```
import pandas as pd


types_dict = {'a': str,
             'b': str,
             'c': str,
             }


if __name__ == "__main__":
    df = pd.read_excel('./test.xlsx', dtype=type_dict)
    print(list(type_dict.keys()))
```

```
>> ['a', 'b', 'c', 'a.1']
```

**Bug/Issue description:**
When using dtype loading a .xlsx-file with a duplicate column into a dataframe modifies the provided types_dict / adds entries for duplicate columns.

It seems to me like the modification of the types_dict is an unwanted side effect.

**Comment by mzeitlin11** [comment]
Thanks for reporting this @cdol! Confirmed on master (seems limited to `read_excel`, doesn't show up for similar example with `read_csv`), agree it is an unwelcome side effect. Fixes very welcome!
