### ISSUE TITLE
BLD: Bump ManyLinux

### ISSUE THREAD

**Issue by lithomas1** [pandas-dev/pandas#42522]
From the manylinux README
```
The goal of the manylinux project is to provide a convenient way to distribute binary Python extensions as wheels on Linux. This effort has produced PEP 513 (manylinux1), PEP 571 (manylinux2010), PEP 599 (manylinux2014) and PEP 600 (manylinux_x_y).

PEP 513 defined manylinux1_x86_64 and manylinux1_i686 platform tags and the wheels were built on Centos5. Centos5 reached End of Life (EOL) on March 31st, 2017.

PEP 571 defined manylinux2010_x86_64 and manylinux2010_i686 platform tags and the wheels were built on Centos6. Centos6 reached End of Life (EOL) on November 30th, 2020.
PEP 599 defines the following platform tags:

manylinux2014_x86_64
manylinux2014_i686
manylinux2014_aarch64
manylinux2014_armv7l
manylinux2014_ppc64
manylinux2014_ppc64le
manylinux2014_s390x
Wheels are built on CentOS 7 which will reach End of Life (EOL) on June 30th, 2024.
```
Since Centos5 and 6 have reached EOL already, we should bump manylinux to manylinux2014. FWIW, numpy has already bumped manylinux to manylinux2014.

cc @simonjayhawkins

**Comment by simonjayhawkins** [comment]
> manylinux2014_aarch64

does that mean we can remove the Travis job on MacPython/pandas-wheels and build all wheels using the same Azure environment?

**Comment by lithomas1** [comment]
Only if we're emulating aarch with qemu, I think.

**Comment by simonjayhawkins** [comment]
milestone as 1.3.1 since if we merge https://github.com/MacPython/pandas-wheels/pull/146 we will build wheels using manylinux2014 for the remaining 1.3.x releases

**Comment by simonjayhawkins** [comment]
closed by https://github.com/MacPython/pandas-wheels/pull/146
