### ISSUE TITLE
MatplotlibDeprecationWarning for ax.is_first_col() 

### ISSUE THREAD

**Issue by sourabh69733** [pandas-dev/pandas#42532]
https://github.com/pandas-dev/pandas/blob/2001798e0f467bde552a95e39a00bfbde28aecd5/pandas/plotting/_matplotlib/tools.py#L396

It is depreciated and needs replacement with ax.get_subplotspec().is_first_col().

**Comment by lithomas1** [comment]
@sourabh69733 This is gated behind a version check(on triggers on less than 3.4.0) on 1.2.4 . If you are seeing this warning, can you please update to the latest pandas?

**Comment by sourabh69733** [comment]
I was using it on Kaggle where it shows a warning. I updated it on Kaggle now and working without warning on my computer which has an updated version.
