### ISSUE TITLE
BUG: - xlsx file not supported 

### ISSUE THREAD

**Issue by soydepr** [pandas-dev/pandas#42535]
raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
xlrd.biffh.XLRDError: Excel xlsx file; not supported
>>> 
![5D1AD636-68E9-43BD-93D6-FCDB2A455D2E](https://user-images.githubusercontent.com/546367/125670336-b9abfa33-2603-484d-9dc8-ebed86292cde.png)

**Comment by mzeitlin11** [comment]
Can you please revise this to follow the bug report template? (especially the part about versions is important for an issue like this). You can find the template at (https://github.com/pandas-dev/pandas/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) or when you open an issue.

**Comment by lithomas1** [comment]
FYI, if you're using xlrd >= 2.0, you cannot read xlsx files anymore. Please use openpyxl instead.

**Comment by phofl** [comment]
@soydepr could you please adress questions?

**Comment by soydepr** [comment]
Yes  > xlrd thank you
