### ISSUE TITLE
ENH: Enhance printing options for stylized DataFrames

### ISSUE THREAD

**Issue by dennymarcels** [pandas-dev/pandas#42533]
#### Is your feature request related to a problem?

More like an improvement.

#### Describe the solution you'd like

I just started playing around with pandas styling, and I noticed there is no way to print only the head and/or tail of a stylized DataFrame. It would be awesome if the styling could be applied to the whole df but then we could print only selected rows, like head and/or tail.

#### API breaking implications

I guess there could be a parameter passed to methods such as `bar`,  or a new method to be appended to the end of a call.

#### Describe alternatives you've considered

I can apply the style to a slice of a DataFrame but then the styling function is applied to this slice only. What if I want to highlight_max to the whole df but print head/tail only?

**Comment by attack68** [comment]
Interesting idea. 
After #41635, there are `max_rows` and `max_cols` mechanics which are expected to be added as keywords to: `Styler.to_html()`. Currently this is only equivalent to a `head` scenario. The parsing and rendering mechanics were quite complicated so the equivalent of a `tail` might be `df[::-1].style.to_html(max_rows=100)` for example.

Do comment on the PR or further if you have any good ideas.

**Comment by dennymarcels** [comment]
To be honest, I like it when I call the DataFrame as the last line of code in a Colab cell and only the first 5 and last 5 rows are rendered. I was thinking something along that idea.

**Comment by attack68** [comment]
@dennymarcels please comment on #45176

**Comment by ivasve** [comment]
Hi @dennymarcels , did you have a look at issue #45176 if it has solved the issue you've been having?

**Comment by LinuxIsCool** [comment]
It's frustrating that max_rows can not be applied to a stylized dataframe.

**Comment by LinuxIsCool** [comment]
To deal with this for now, I just implemented this utility function in my code: 

```python
    def _truncate_dataframe(df, max_rows):
        return pd.concat([df.head(max_rows//2), df.tail(max_rows//2)])
```

**Comment by attack68** [comment]
The "stylized dataframe" discussed in this thread is actually a `Styler` class. Your utility function involves `DataFrames` and does not reference a `Styler`. For `Styler` have you considered the global pandas option `styler.render.max_rows` ? https://pandas.pydata.org/docs/user_guide/options.html#available-options

**Comment by LinuxIsCool** [comment]
Thanks @attack68  for the fast response. That did indeed help me, but there is still a nuance issue of the aesthetics of the truncation. I would like to see the head and tail of the dataframe rather than just the head as was pointed out by @dennymarcels in this thread. 

Here is my example: 

```python
import pandas as pd
import panel as pn
pd.set_option('styler.render.max_rows', 5)

df = pd.DataFrame(list(range(20)))

# Define CSS style for the sapphire color on column 'A' header
styles = [
    {'selector': 'th.col_heading.level0.col0', 
     'props': [('background-color', 'blue'), ('color', 'white')]}
]

# Apply the style to the DataFrame
styled_df = df.style.set_table_styles(styles, overwrite=False)

styled_df
```

![image](https://github.com/pandas-dev/pandas/assets/31582215/0cf47076-ffc6-4ce6-81fa-24e8ac60fc0e)

**Comment by attack68** [comment]
`styled_df.hide(df.index[5:-5])`

**Comment by attack68** [comment]
I don't think the API for `Styler` is going to be expanded to for the `head` and `tail` case, nor with a `show` method. I think the solution to use `hide` whilst initially unintuitive is actually the best way to utilise all of `Styler` chained procedures.

Will close this issue and relabel the title for anyone searching for similar.
