### ISSUE TITLE
DOC: `pandas.json_normalize` missing from API Reference portion of documentation

### ISSUE THREAD

**Issue by TimelikeClosure** [pandas-dev/pandas#42540]
#### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.json_normalize.html (currently responds with a `404 Not Found`)

#### Documentation problem

While the source code does contain API reference documentation for `pandas.json_normalize` (previously `pandas.io.json.json_normalize`) as seen in [`/pandas/io/json/_normalize.py`](https://github.com/pandas-dev/pandas/blob/master/pandas/io/json/_normalize.py#L240-L381), it isn't available in the documentation for the current version of pandas hosted on `pandas.pydata.org`.

#### Suggested fix for documentation

At least one older version of `pandas` _does_ have documentation that includes a `json_normalize` API reference under its old name ([`pandas.io.json.json_normalize` in v0.25.0](https://pandas.pydata.org/pandas-docs/version/0.25.0/reference/api/pandas.io.json.json_normalize.html)), so it seems feasible that it was removed by accident when its old name was [deprecated in v1.0.0](https://github.com/pandas-dev/pandas/blob/master/pandas/io/json/_normalize.py#L524-L526). Attempting to visit [`pandas.io.json.json_normalize` in the current version of the documentation](https://pandas.pydata.org/docs/dev/reference/api/pandas.io.json.json_normalize.html) redirects to the new name (`pandas.json_normalize`), which responds with a 404.

**Comment by rhshadrach** [comment]
The method referenced is `_json_normalize`, the leading underscore indicating that is is internal and not meant for users.

**Comment by tilusnet** [comment]
Pandas 1.2.5 still had the API documentation available: https://pandas.pydata.org/pandas-docs/version/1.2.5/reference/api/pandas.json_normalize.html

Yet the latest version still has `json_normalize` documented in the User Guide section: https://pandas.pydata.org/docs/user_guide/io.html#normalization

The missing API entry is surely a mistake then?

**Comment by haakenlid** [comment]
> Thanks for the report! The method referenced is _json_normalize, the leading underscore indicating that is is internal and not meant for users.

It's exposed as `pandas.json_normalize` in the top level namespace, and it certainly _is_ meant for users.

https://github.com/pandas-dev/pandas/blob/master/pandas/__init__.py#L170

**Comment by haakenlid** [comment]
Here's a commit removing it from the docs, claiming it's deprecated.

https://github.com/pandas-dev/pandas/pull/41844/commits/47f90edd0a2b71f3ec3b819e7c2fbbab24f7bbb7

I can't find any explanation of what that is supposed to mean.

**Comment by rhshadrach** [comment]
Thanks for following up on this @haakenlid - my comment above was incorrect (and is now edited). In 1.0.0 pandas.io.json_normalize was deprecated in favor of pandas.json_normalize

https://pandas.pydata.org/pandas-docs/version/1.0.0/whatsnew/v1.0.0.html#deprecations
https://github.com/pandas-dev/pandas/pull/27615

So the commit you found was right in that it should be removed from io, but it needs to be added to the docs from pandas namespace. A PR to fix this is most welcome!

**Comment by trenton3983** [comment]
> Thanks for following up on this @haakenlid - my comment above was incorrect (and is now edited). In 1.0.0 pandas.io.json_normalize was deprecated in favor of pandas.json_normalize
> 
> https://pandas.pydata.org/pandas-docs/version/1.0.0/whatsnew/v1.0.0.html#deprecations #27615
> 
> So the commit you found was right in that it should be removed from io, but it needs to be added to the docs from pandas namespace. A PR to fix this is most welcome!

Not sure I understand this. As the documentation already does exist: https://pandas.pydata.org/pandas-docs/version/1.2.0/reference/api/pandas.json_normalize.html

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.io.json.json_normalize.html was a working link until more recently than 1.2.0 (but not sure exactly which version).
