### ISSUE TITLE
BUG: MultiIndex assignment fails to broadcast omitted levels

### ISSUE THREAD

**Issue by bashtage** [pandas-dev/pandas#42557]
- [X] I have checked that this issue has not already been reported.
- [X] (optional) I have confirmed this bug exists on the master branch of pandas.

**Note**: Not in a released pandas, only master

---

#### Code Sample
```python
import pandas as pd
mi = pd.MultiIndex.from_product([["a","b"],[1,2],["z","y"]])
df = pd.DataFrame(index=mi,dtype=float)
mi2 = pd.MultiIndex.from_product([["a","b"],[1,2]])
s = pd.Series(index=mi2, dtype=float)
s.iloc[:]=3.14
df["new"] = s
print(df)
```

#### Problem description

In 1.3.0 MultiIndex assignment broadcast missing levels.  As of #42231, this no longer works.

#### Expected Output

In master, I see
```
       new
a 1 z  NaN
    y  NaN
  2 z  NaN
    y  NaN
b 1 z  NaN
    y  NaN
  2 z  NaN
    y  NaN
```

In 1.3.0 or 1.2.5, I see
```
        new
a 1 z  3.14
    y  3.14
  2 z  3.14
    y  3.14
b 1 z  3.14
    y  3.14
  2 z  3.14
    y  3.14
```

#### Output of ``pd.show_versions()``

<details>
```
INSTALLED VERSIONS
------------------
commit           : f3a6753d2d8abd20cd522920d4dc08555c701bce
python           : 3.8.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19043
machine          : AMD64
processor        : AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.4.0.dev0+246.gf3a6753d2d
numpy            : 1.20.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.3
setuptools       : 52.0.0.post20210125
Cython           : 0.29.23
pytest           : 6.2.4
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.22.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

```
</details>

**Comment by trevorkask** [comment]
just to clarify, is it an issue of missing data or missing levels? if it is missing levels, what levels are they,exactly?

**Comment by trevorkask** [comment]
take

**Comment by trevorkask** [comment]
I have found two probable causes of this bug. However, I am not sure which one to go with because I understand that a patch led to this bug. So one option may be better in terms of not undoing the patch.
1. In the method _should_compare, line 5646, the parameters for the if statement check for boolean and numeric data, whereas the example given [https://github.com/pandas-dev/pandas/issues/42557#issue-945839860](url), uses mixed data types(char and numeric). I suggest passing the is_mixed function rather than is_boolean or is_numeric.
2. In the method get_indexer, line 3481, I could change the 'and' to 'or', so that the should_compare condition gets bypassed. This is a bit riskier.

Kindly advise on the best way forward, depending on what the patch altered.

**Comment by bashtage** [comment]
I think the source of this bug was reverted in 4c9ef1bf2dc6a9eb4d5e85617da0f48d08df522b

**Comment by simonjayhawkins** [comment]
> I think the source of this bug was reverted in [4c9ef1b](https://github.com/pandas-dev/pandas/commit/4c9ef1bf2dc6a9eb4d5e85617da0f48d08df522b)

#42575
