### ISSUE TITLE
ENH: write to existing sheet of excel file

### ISSUE THREAD

**Issue by fdzuJ** [pandas-dev/pandas#42559]
#### Is your feature request related to a problem?

Prior to [GH40230](https://github.com/pandas-dev/pandas/issues/40230) it was possible to write to existing sheet using code like below. I would like to be able to do it again.
I use it to create excel files with overly compicated and/or regularly changing header requirements.

```python
def write_to_excel(df: pd.DataFrame, mode: str = 'a', form: Path, sheetname: Union[int, str] = 0, **kwargs)
    with pd.ExcelWriter(path, mode=mode) as writer:
        if mode == 'a':
            for sheet, sheet_name in zip(writer.book.worksheets, writer.book.sheetnames)
                writer.sheets.setdefault(sheet_name, sheet)
            if isinstance(sheetname, int):
                sheetname = writer.book.sheetnames[sheetname]
        else:
            sheetname = sheetname if isinstance(sheetname, str) else 'Sheet1'

        df.to_excel(writer, sheet_name=sheetname, engine='openpyxl', **kwargs)
```

#### Describe the solution you'd like

Add `append` option for `if_sheet_exists` parameter

#### API breaking implications

New option for parameter shouldn't break API.

#### Describe alternatives you've considered

This was possible prior to previously mentioned enhancement. Only solution I can think of now is to initiate `ExcelWriter` with `if_sheet_exists='new'` and to copy everything from previously existing sheet before writing dataframe and to rename and delete sheets accordingly later.

**Comment by pavel-hushcha** [comment]
Strongly agree with that.

**Comment by simonjayhawkins** [comment]
@fdzuJ duplicate of #42221?

**Comment by fdzuJ** [comment]
Yes, it's a duplicate. Closing.
