### ISSUE TITLE
QST: why changing dataframe values impacts the array that the dataframe was created from?

### ISSUE THREAD

**Issue by pinshuai** [pandas-dev/pandas#42573]
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

```python
>>> import numpy as np
>>> import pandas as pd

>>> mat = np.array([[1,2], [2,3]])
>>> mat
array([[1, 2],
       [2, 3]])

>>> df = pd.DataFrame(mat)
>>> df.iloc[0,1] = 4

>>> mat
array([[1, 4],
       [2, 3]])
```

Why the value in the original `mat` is also changed? I am not sure if this is a bug or Pandas' way of doing things. I found it to be very confusing.

**Comment by lithomas1** [comment]
From the pd.DataFrame constructor docs.
```
copy : bool or None, default None
Copy data from inputs. For dict data, the default of None behaves like copy=True. For DataFrame or 2d ndarray input, the default of None behaves like copy=False.

Changed in version 1.3.0.
```
If you do ``pd.DataFrame(mat, copy=True)`` the original is unchanged.

**Comment by Varun270** [comment]
@lithomas1  I am a beginner in open source and would love to work on this issue, I have cloned the repository but am unable to find the folder that has this code. Can you help me?

**Comment by Varun270** [comment]
take

**Comment by rhshadrach** [comment]
@Varun270 the relevant code will be in `pandas.core.frame` or `pandas.core.genreic`. However, it seems to me there is no issue to be resolved here.

**Comment by attack68** [comment]
closing - democracy seems to have identified this as a non-issue, but rather an educational question for which an answer was given
