### ISSUE TITLE
BUG: Nullable Int64 <NA> behavior inconsistent with np.nan

### ISSUE THREAD

**Issue by alexlenail** [pandas-dev/pandas#42599]
- [ ] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
>>> pd.Series(np.nan) == pd.Series(np.nan)
0    False
>>> pd.Series(np.nan) == pd.Series(np.nan).astype("Int64")
0    <NA>
>>> pd.Series(np.nan).astype("Int64") == pd.Series(np.nan)
0    <NA>
>>> np.nan == np.nan
False
>>> pd.Series(np.nan).astype("Int64").values[0] == pd.Series(np.nan).astype("Int64").values[0]
<NA>
```

#### Problem description

Pandas recently introduced a [Nullable Int64 data type](https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html). I missed the conversation, but I feel like its behavior should be consistent with numpy float nan's here? 

pandas 1.2.4

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.7.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.4.0
Version          : Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:14 PST 2021; root:xnu-7195.101.1~3/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.4
numpy            : 1.19.5
pytz             : 2021.1
dateutil         : 2.7.5
pip              : 21.1.3
setuptools       : 53.0.0
Cython           : 0.29.19
pytest           : 5.0.1
hypothesis       : None
sphinx           : 1.6.3
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.2.0
pandas_datareader: None
bs4              : 4.9.1
bottleneck       : None
fsspec           : 2021.06.1
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : 4.0.1
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : 0.18.2
xlrd             : 1.2.0
xlwt             : None
numba            : 0.49.1
</details>

**Comment by lithomas1** [comment]
This is a design decision. Please see https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html#propagation-in-arithmetic-and-comparison-operations. If the behavior was exactly the same, we would use np.nan :).

**Comment by alexlenail** [comment]
Thanks and sorry for not reading the docs. 

I'd like to register myself as being surprised by this design choice.
