### ISSUE TITLE
What the fucking meaning? Numerical issues were encountered when scaling the data and might not be solved. The standard deviation of the data is probably very close to 0. 

### ISSUE THREAD

**Issue by GF-Huang** [pandas-dev/pandas#42592]
![image](https://user-images.githubusercontent.com/4510984/126069891-a7a47a7a-4f27-40d2-89cd-aae6e5fc9af9.png)

**Comment by venaturum** [comment]
Read how to submit a bug report and try again. This is not a pandas issue anyhow.
