### ISSUE TITLE
ENH: rename, or at least alias, "quantile" method with "fractile"

### ISSUE THREAD

**Issue by venaturum** [pandas-dev/pandas#42593]
#### Is your feature request related to a problem?

The method called quantile, is misnamed. What is it calculating is the fractile. A fractile is a number, where fractile(x) = percentile(100x).  A quantile is  a set of fractiles.

#### Describe the solution you'd like

Fractile becomes an alias of quantile in next non-major release then quantile is removed in next major release, or redefined. An appropriate redefinition would take an integer n, and return an array of  n values where the kth value is given by fractile(k/(n+1)) as per https://en.m.wikipedia.org/wiki/Quantile

#### API breaking implications

Removal or redefinition of quantile method will of course not be backwards compatible.

**Comment by jreback** [comment]
pls show what this method is called in other languages eg
r, sql, matlab and so on

i think you will find it's called quartile

**Comment by venaturum** [comment]
@jreback, I've done as you suggested and summarised below:

Matlab: function quantile - for a parameter less than one the result is a fractile, and for integers it returns an array of cut points (as per definition I proposed).

R : function quantile - takes float or list of floats, between 0 and 1, and returns corresponding fractiles

Sql : ntile function - takes an integer and buckets the data according to cut points.

So matlab combines current pandas definition with the one I'm proposing. R is consistent with current pandas definition while sql is not and uses the quantile cut points to bucket data. The R result surprised me, as I would have thought the stats community of all people would have demanded an implementation that is consistent with the mathematical definition.

I'm not convinced that keeping the current definition is the correct course of action, but that's probably me being anal-retentive. Matlab's implementation does provide a compromise that pandas could adopt though.

**Comment by venaturum** [comment]
It seems the source of confusion may stem from

Quantile https://en.m.wikipedia.org/wiki/Quantile
vs
Quantile function https://en.m.wikipedia.org/wiki/Quantile_function

**Comment by venaturum** [comment]
Happy for this issue to be closed if required.

**Comment by jreback** [comment]
yeah i think this boat has long sailed - not worth the churn

there is an issue about being more explicit in the documentation - if u can find it pls link / take PR

**Comment by rhshadrach** [comment]
https://stats.stackexchange.com/questions/235330/iles-terminology-for-the-top-half-a-percent/

This post seems to be authoritative, and backs the current terminology used in pandas.

**Comment by venaturum** [comment]
@rhshadrach I'd disagree on that. It actually supports my point. The post refers to quartiles, quintiles, sextiles etc as examples of quintiles. These things are sets, not scalars, which is why the post is referring to things like the "upper quartile" and "third quintile". The top rated answer in that thread lists several papers as references, the first being Aronson, J. K. 2001. Francis Galton and the invention of terms for quantiles. Journal of Clinical Epidemiology 54: 1191-1194.
Its second paragraph defines quantile in the exact way I suggested, which is not consistent with pandas:
_Let’s start with quantile itself. It comes from the Latin
word quantus (how much or how great), and is defined in
the Oxford English Dictionary (OED) as “each of any set of
values of a variate which divide a frequency distribution
into equal groups, each containing the same fraction of the
total population; also, any one of the groups so produced,
e.g. a quartile, decile, or percentile.” Well that expresses the
general concept._

**Comment by rhshadrach** [comment]
@venaturum - the opening line is:

> Historically, and to the present, the upper or third quartile (for example) is the value exceeded by just 25% of values. (I only ever see informal use of "top" for this meaning.)

which is a scalar.

**Comment by venaturum** [comment]
If you want to ignore the formal definition outlined in the paper and hang your hat on commentary from internet strangers then that is your pregorative. But realise in order to calculate the "third quartile" you need two pieces of information - 3 from third, and 4, from quartile. Either a quantile method should take two integers as parameters and return a scalar, or it should take one integer and return a set. A quantile method taking one parameter, possibly not integer, and returning a scalar, ain't calculating a quantile, it can only be one thing and that's a fractile 

https://diffsense.com/diff/fractile/quantile

**Comment by rhshadrach** [comment]
> hang your hat on commentary from internet strangers

@venaturum - The post was written by [Dr Nicholas J. Cox](https://www.dur.ac.uk/directory/profile/?id=335).

**Comment by venaturum** [comment]
Touché.  I concede he does seem to be an authorative source.  From his own paper _Cox, N.J. 2016. Letter values as selected quantiles._ http://www.stata-journal.com/article.html?article=st0465 :

_Consider a set of n values ordered, smallest first, so that they have ranks 1 to n. The 
ordered values are often called “order statistics” or (particularly in statistical graphics)
the (sample) “quantiles”_

As you can see the definition of quantile requires the notion of a set, which the pandas implementation does not.
