### ISSUE TITLE
QST: pandas rolling enabling offset even if my index is not datetime

### ISSUE THREAD

**Issue by chivalry123** [pandas-dev/pandas#42601]
For this dataframe 

    df = pd.DataFrame({'B': [0, 1, 2, np.nan, 4]},index=[0.1,0.2,0.5,0.7,0.9])

df

           B
    0.1  0.0
    0.2  1.0
    0.5  2.0
    0.7  NaN
    0.9  4.0

I want to perform an offset based rolling like: 

    df.rolling(0.3).sum()

But I got this error:

> ValueError: window must be an integer

Could anyone help me? my real case involves about 1B rows, and I needed to do groupby().rolling() in the end. The above is just an extreme simplification of my problem. Please help me. Thanks!

**Comment by mroeschke** [comment]
Thanks for the question. Your best bet is to convert your index to a `DatetimeIndex` and then perform the calculation as normal to get offset-based behavior.

```
In [1]: df = pd.DataFrame({'B': [0, 1, 2, np.nan, 4]},index=[0.1,0.2,0.5,0.7,0.9])

In [2]: df.index = pd.to_datetime(df.index, unit="s")

In [3]: df.rolling("300ms").mean()
Out[3]:
                           B
1970-01-01 00:00:00.100  0.0
1970-01-01 00:00:00.200  0.5
1970-01-01 00:00:00.500  2.0
1970-01-01 00:00:00.700  2.0
1970-01-01 00:00:00.900  4.0
```

We highly encourage to ask usage questions on stackoverflow first in the future.

**Comment by chivalry123** [comment]
Thanks so much! I didn't expect this method so fast. I was trying on 10M rows and it only takes 153ms! really fast!
