### ISSUE TITLE
BUG: to_datetime()'s origin does not use unit specified in the parameter

### ISSUE THREAD

**Issue by ytchanglp** [pandas-dev/pandas#42624]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
pd.to_datetime(1, unit='s')                    
# Timestamp('1970-01-01 00:00:01')               

pd.to_datetime(1, unit='s', origin=1)          
# Current --> Timestamp('1970-01-01 00:00:01')               
# Expected -> Timestamp('1970-01-01 00:00:02')       

pd.to_datetime(1, unit='s', origin=1000000000) 
# Current --> Timestamp('1970-01-01 00:00:02')               
# Expected -> Timestamp('2001-09-09 01:46:41')

```

#### Problem description

The numeric values of origin should be parsed as number of units defined by unit

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f00ed8f47020034e752baf0250483053340971b0
python           : 3.9.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.950

pandas           : 1.3.0
numpy            : 1.21.0
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.3
setuptools       : 57.0.0
Cython           : 0.29.23
pytest           : 6.2.4
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.25.0
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.2
fsspec           : 2021.06.1
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.2
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.0
sqlalchemy       : None
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : 2.0.1
xlwt             : None
numba            : 0.53.1

</details>

**Comment by stephan-hesselmann-by** [comment]
This should be easy to fix, but I'm not sure what the correct expected behavior actually is. According to the docs (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html) `origin` may be given as `"unix" (or POSIX) time`. POSIX time is defined in seconds. So should the correct behavior be to use seconds as unit for numeric `origin` (potentially different from the `unit` of `arg`)? Or should `origin` be in the `unit` of `arg`? The current behavior also makes sense since it corresponds to the default `Timestamp(origin)` conversion.

**Comment by ytchanglp** [comment]
the doc is clearly said. 
> The numeric values would be parsed as number of units (**_defined by unit_**) since this reference date.

**Comment by Dinkarkumar** [comment]
Can I work on this issue ?

**Comment by stephan-hesselmann-by** [comment]
> the doc is very clearly.
    The numeric values would be parsed as number of units (defined by unit) since this reference date.

At least to me this does not clarify if the reference date itself should be parsed as number of units as well. Especially with Unix time this would not really make sense, because Unix time is per definition always in seconds.
