### ISSUE TITLE
date_range bug for 

### ISSUE THREAD

**Issue by ThiMaul** [pandas-dev/pandas#42638]
I need help!!

When I use this code :

debut = df_idmatch.date.min().replace(tzinfo=None)
fin = df_idmatch.date.max().replace(tzinfo=None)
print(debut, fin)
dates=pd.date_range(start=debut,end=fin,freq='W')            
date_index=dates.year.astype(str)+"-"+dates.weekofyear.astype(str).str.zfill(2)
date_index.tolist()

There is a trouble when you pass from the end of the year to next year. If you print date_index, it will print you :

Index(['2020-38', '2020-39', '2020-40', '2020-41', '2020-42', '2020-43',
       '2020-44', '2020-45', '2020-46', '2020-47', '2020-48', '2020-49',
       '2020-50', '2020-51', '2020-52', '**2021-53**', '2021-01', '2021-02',
       '2021-03', '2021-04', '2021-05', '2021-06', '2021-07', '2021-08',
       '2021-09', '2021-10', '2021-11', '2021-12', '2021-13', '2021-14',
       '2021-15', '2021-16', '2021-17', '2021-18', '2021-19', '2021-20',
       '2021-21', '2021-22', '2021-23', '2021-24', '2021-25', '2021-26',
       '2021-27', '2021-28', '2021-29', '2021-30'],
      dtype='object')

in fact, 2021-53 should be 2020-53
is it a problem with the date_range fonction or is it inside my own code ?

Regards,

Thibaud

**Comment by phofl** [comment]
Hi, could you please provide a reproducible example?

**Comment by ThiMaul** [comment]
debut = datetime. datetime(2020, 10, 10, 11, 22, 33) 
fin = datetime. datetime(2021, 02, 02, 11, 22, 33)
dates=pd.date_range(start=debut,end=fin,freq='W')
date_index=dates.year.astype(str)+"-"+dates.weekofyear.astype(str).str.zfill(2)
date_index.tolist()
print(date_index)

I think with this you will see the error.

**Comment by aterzgar** [comment]
i think if you use isocalendar() it might fix your problem. It should return 2021-01 not 2021-53 or 2020-53.

**Comment by simonjayhawkins** [comment]
simpler code sample

```
>>> dti = pd.date_range(start="2020-12-27", periods=2, freq="W")
>>> dti
DatetimeIndex(['2020-12-27', '2021-01-03'], dtype='datetime64[ns]', freq='W-SUN')
>>> 
>>> dti.year
Int64Index([2020, 2021], dtype='int64')
>>> 
>>> dti.weekofyear
<stdin>:1: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series.  To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)
Int64Index([52, 53], dtype='int64')
>>> 
>>> dti.isocalendar().week
2020-12-27    52
2021-01-03    53
Freq: W-SUN, Name: week, dtype: UInt32
>>> 
>>> dti.isocalendar().year
2020-12-27    2020
2021-01-03    2020
Freq: W-SUN, Name: year, dtype: UInt32
```

**Comment by mroeschke** [comment]
This follows the standard library. ISO week and year have specific definitions that differ slightly from conventional week and year definitions: https://docs.python.org/3/library/datetime.html#datetime.date.isocalendar

```
In [1]: import datetime

In [2]: datetime.datetime(2020, 12, 27).isocalendar()
Out[2]: (2020, 52, 7)

In [3]: datetime.datetime(2021, 1, 3).isocalendar()
Out[3]: (2020, 53, 7)
```

**Comment by ThiMaul** [comment]
I solve it with isocalendar().week and year

dates=pd.date_range(start=debut,end=fin,freq='W')
date_index=dates.isocalendar().year.astype(str)+"-"+dates.isocalendar().week.astype(str).str.zfill(2)
date_index.tolist()

Thanks
