### ISSUE TITLE
QST: `min_periods` effect on `std` rolling aggregation?

### ISSUE THREAD

**Issue by isVoid** [pandas-dev/pandas#42653]
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [x] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

In rolling aggregation, `min_periods` dictates that if there's `N` valid observations, and that `N >= min_periods`, the aggregation should be computed with all valid observations in the window. However, for `std` and `var` aggregation, the above guideline is not observed:

```python
# Your code here, if applicable
s = pd.Series([1.0, 1.0, 1.0, np.nan, 1.0, 2.0])
s.rolling(2, min_periods=1).std()
0         NaN
1    0.000000
2    0.000000
3         NaN
4         NaN
5    0.707107
dtype: float64
```

The question is: should `min_periods` have effects on `std` aggregation?

**Comment by mroeschke** [comment]
Each window in this case does have at least 1 observation:

```
In [2]: for r in pd.Series([1.0, 1.0, 1.0, np.nan, 1.0, 2.0]).rolling(2, min_periods=1):
   ...:     print(r)
   ...:
0    1.0
dtype: float64
0    1.0
1    1.0
dtype: float64
1    1.0
2    1.0
dtype: float64
2    1.0
3    NaN
dtype: float64
3    NaN
4    1.0
dtype: float64
4    1.0
5    2.0
dtype: float64
```

And therefore the result should be equivalent to the following:

```
In [3]: for r in pd.Series([1.0, 1.0, 1.0, np.nan, 1.0, 2.0]).rolling(2, min_periods=1):
   ...:     print(r.std())
   ...:
   ...:
nan
0.0
0.0
nan
nan
0.707106781186547
```

**Comment by isVoid** [comment]
Thanks for the reply @mroeschke ! My understanding of `min_periods` is this:
```
if valid_observations in window >= min_periods:
    compute aggregation for all valid observations in the window
else:
    result is nan
```
At least for `sum`, this seem to check:

```python
>>> s = pd.Series([1.0, 1.0, 1.0, np.nan, 1.0, 2.0])
>>> s.rolling(2, min_periods=1).sum()
0    1.0
1    2.0
2    2.0
3    1.0
4    1.0
5    3.0
dtype: float64
```

**Comment by phofl** [comment]
The std of something like 
```
ser = Series([1])
ser.std()
```

is ``nan``, hence the result from the rolling aggregation

**Comment by isVoid** [comment]
Ah, thanks for the clarification!

**Comment by phofl** [comment]
Can close?

**Comment by isVoid** [comment]
Yup, closing.
