### ISSUE TITLE
ENH: read_csv() optional parameter `append_line_numbers`

### ISSUE THREAD

**Issue by sgsokol** [pandas-dev/pandas#42663]
#### Is your feature request related to a problem?

I wish I could use pandas.read_csv() to include the original line number of csv file. It can be useful for error report in case of invalid entry  (invalid from an application point of view not from csv's one). Given that users can skip few starting lines,  blank lines or commented ones, the df index may not correspond to the original line number from csv file.

#### Describe the solution you'd like

`read_csv()` should include an optional parameter, let say `append_line_numbers=None`. If its value is None, nothing happens, i.e. the classical way of functioning is kept. If it is a string, its value is used to name a column in a returned data frame that will contain line numbers

#### API breaking implications

No API breaking is expected

#### Describe alternatives you've considered

read the file without skipping any line then remove headers, blank lines, etc. "manually" in the users's application

**Comment by mroeschke** [comment]
Thanks for the suggestion but it appears there hasn't been much interest in this feature from the core devs & community over the years so closing. Happy to reopen if there's renewed interest
