### ISSUE TITLE
BUG: reading csv error : KeyError: 'x'

### ISSUE THREAD

**Issue by Binger-cn** [pandas-dev/pandas#42681]
python 3.9.6 x64 on windows10pro,   vscode 1.58.2, pandas 1.3.0
![image](https://user-images.githubusercontent.com/87395223/126746250-54a871cd-a216-494f-a144-3e1a1f07971a.png)
[pandas-bug.zip](https://github.com/pandas-dev/pandas/files/6866965/pandas-bug.zip)

KeyError: 'x'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Roaming\Python\Python39\site-packages\IPython\core\formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_ppr

**Comment by phofl** [comment]
Hi, thanks for your report. Could you provide a copy pasteable example? See https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by Binger-cn** [comment]
> Hi, thanks for your report. Could you provide a copy pasteable example? See https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

I'm so sorry! It's because I copied a line to set the option, which errorly adds an 'x' in the code:
pd.set_option('display.float_format','{x:,.2f}'.format)

I have corrected this line :
pd.set_option('display.float_format','{:,.2f}'.format)
