### ISSUE TITLE
CI: xarray upgrade to 0.19 broke CI Checks pipeline

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#42716]
Xarray was recently upgrade from 0.18.2 to 0.19 in our ci. This broke the checks pipeline

Passing:
https://github.com/pandas-dev/pandas/runs/3155104841

Failing:
https://github.com/pandas-dev/pandas/pull/42713/checks?check_run_id=3155841275

**Comment by phofl** [comment]
Following errors happen:

```
 Performing static analysis using mypy
/usr/share/miniconda/envs/pandas-dev/lib/python3.8/site-packages/xarray/core/common.py:1659: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
If this issue continues with mypy master, please report a bug at https://github.com/python/mypy/issues
version: 0.910
/usr/share/miniconda/envs/pandas-dev/lib/python3.8/site-packages/xarray/core/common.py:1659: : note: please use --show-traceback to print a traceback when reporting a bug
Performing static analysis using mypy DONE
Error: Process completed with exit code 2.
```

Some mypy issue


Doctest issue:

```
 _______________ [doctest] pandas.core.generic.NDFrame.to_xarray ________________
3086 
3087         >>> df_multiindex
3088                            speed
3089         date       animal
3090         2018-01-01 falcon    350
3091                    parrot     18
3092         2018-01-02 falcon    361
3093                    parrot     15
3094 
3095         >>> df_multiindex.to_xarray()
Differences (unified diff with -expected +actual):
    @@ -1,4 +1,4 @@
     <xarray.Dataset>
    -Dimensions:  (animal: 2, date: 2)
    +Dimensions:  (date: 2, animal: 2)
     Coordinates:
       * date     (date) datetime64[ns] 2018-01-01 2018-01-02
```

**Comment by simonjayhawkins** [comment]
changing milestone to 1.3.5

**Comment by jbrockmendel** [comment]
both of these persist with xarray 0.20.1

**Comment by simonjayhawkins** [comment]
xarray is a py.typed library and this was also the case for xarray 0.18.2 (since v0.12.4  https://github.com/pydata/xarray/pull/3112) 

Not sure what the mypy error is all about but adding an empty `xarray.pyi` file in our `typings` directory allows mypy to run and is green (for xarray 0.20.1), so could do this if unpinning xarray is considered more important than type checking against xarray.

**Comment by simonjayhawkins** [comment]
removing from 1.3.x milestone as I don't think there is anything that needs to done for 1.3.x and this is just a ci issue? So having xarray pinned on 1.3.x is nbd.

**Comment by jbrockmendel** [comment]
There are several ci/deps/ files where xarray version is not pinned.  Does that indicate this issue is resolved?

**Comment by phofl** [comment]
I think it only caused the typing checks to fail, nothing else

**Comment by jbrockmendel** [comment]
OK.  Do we have a way of checking when this is resolved?

**Comment by MarcoGorelli** [comment]
closing as it looks like CI is fine now

**Comment by simonjayhawkins** [comment]
xarray is still pinned in environment.yaml, xarray<0.19. local environment resolving to 0.18.2

mypy is now passing locally with both xarray 0.19.0 and xarray 0.20.1, so I guess that the issue has been resolved by some changes in pandas itself.

I think we should not close this issue until xarray is unpinned.

**Comment by djgray780** [comment]
Can this be assigned to me?

**Comment by djgray780** [comment]
take

**Comment by djgray780** [comment]
This is my first contribution to pandas and open-source in general, but I am pretty sure that my PR [47016](https://github.com/pandas-dev/pandas/pull/47016) is ready for review/merge.

**Comment by simonjayhawkins** [comment]
> mypy is now passing locally with both xarray 0.19.0 and xarray 0.20.1, so I guess that the issue has been resolved by some changes in pandas itself.

xref https://github.com/pandas-dev/pandas/pull/47016#pullrequestreview-973000450, doctest issue mentioned in https://github.com/pandas-dev/pandas/issues/42716#issuecomment-886271371 still persists.

**Comment by mroeschke** [comment]
Closed by https://github.com/pandas-dev/pandas/pull/47016
