### ISSUE TITLE
DOC: Version information in headline / menubar

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [pandas-dev/pandas#42722]
Example
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html

It would be nice to show the pandas version this documentation is related to.
The version string could be placed somewhere in the head, e.g. beside the horizontal menu bar.

The Python docs does this. There you can see everytime the current version.
Python also offers a drop down menu to select a specific docs version. I think this is overhead and not needed for pandas.

**Comment by rhshadrach** [comment]
+1 - I wonder if it could go next to the pandas logo on the top left.

**Comment by jorisvandenbossche** [comment]
There is active work in the upstream theme to add a version switcher (https://github.com/pydata/pydata-sphinx-theme/pull/436). That could also be a way to show the version you are using (it of course doesn't necessarily conflicts with showing the current version somewhere as well, but probably the version dropdown will already be located in the top bar)

**Comment by jreback** [comment]
closed by #45370
