### ISSUE TITLE
BUG: segfault with pytables tests

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#42755]
Started noticing this after doing `brew upgrade` a couple days ago.  Somewhere in pandas/tests/io/test_common.py I get a long warning that starts with

```
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.12.0, library is 1.12.1
```

followed by a segfault.

This is likely an upstream issue, but parking this here for now.

**Comment by jbrockmendel** [comment]
xref https://github.com/PyTables/PyTables/issues/903

**Comment by lithomas1** [comment]
Do you use conda? It's possible that conda installed its own hdf5 if you installed pytables with conda.

**Comment by jbrockmendel** [comment]
pretty much just pip

**Comment by jbrockmendel** [comment]
Solution was to compile from source instead of using a wheel.  Discussed in the https://github.com/PyTables/PyTables/issues/903, closing

**Comment by sunilshah** [comment]
In native mode, seg fault in tables does occur on M1.  Big Sur 11.6.
