### ISSUE TITLE
DOC: .to_hdf() compression argument `complevel` ambiguous default

### ISSUE THREAD

**Issue by alexlenail** [pandas-dev/pandas#42760]
#### Location of the documentation

[`.to_hdf()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_hdf.html)

#### Documentation problem

They keyword argument default is `complevel=None`. The documentation says **complevel {0-9}, optional**. It seems like this parameter is passed to pytables directly, however, a little bit of direction from pandas would be nice for users here. 

#### Suggested fix for documentation

Could include a pointer to [this documentation](http://www.pytables.org/usersguide/optimization.html#compression-issues) from pytables, but more would be nice.

**Comment by rhshadrach** [comment]
Thanks for the report! Agreed the behavior of `None` should be documented. Would you be interested in putting up a PR to fix?

**Comment by kadatatlukishore** [comment]
Hey @rhshadrach , I would like to do this.

**Comment by kadatatlukishore** [comment]
Can I PR @rhshadrach ?
