### ISSUE TITLE
BUG: Exactly same check multiple times in if statement

### ISSUE THREAD

**Issue by debnathshoham** [pandas-dev/pandas#42781]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

Hi, I stumbled upon this while trying to fix another bug.
Is there a reason for the multiple check below (Lines 3536-3537)? 
Should be a quick fix.

https://github.com/pandas-dev/pandas/blob/8924277fa3dbe775f46e679ab8bd97b293e465ea/pandas/core/indexes/multi.py#L3533-L3540

**Comment by phofl** [comment]
Yes, fast_unique_multiple does Not match nans iirc
