### ISSUE TITLE
CI: Doctests failing on master

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#42798]
The next doctests are failing on master, and are breaking the CI. Didn't check what caused the problem, would be good to understand (I guess we merged a PR that wasn't updated). In any case, we should update the output, so the CI is green again:

```
_______________ [doctest] pandas.core.construction.extract_array _______________
398     Categories (3, object): ['a', 'b', 'c']
399 
400     Other objects like lists, arrays, and DataFrames are just passed through.
401 
402     >>> extract_array([1, 2, 3])
403     [1, 2, 3]
404 
405     For an ndarray-backed Series / Index a PandasArray is returned.
406 
407     >>> extract_array(pd.Series([1, 2, 3]))
Expected:
    <PandasArray>
    [1, 2, 3]
    Length: 3, dtype: int64
Got:
    array([1, 2, 3])

/home/runner/work/pandas/pandas/pandas/core/construction.py:407: DocTestFailure
_______________ [doctest] pandas.core.indexing.IndexingMixin.loc _______________
356         Alignable boolean Series:
357 
358         >>> df.loc[pd.Series([False, True, False],
359         ...        index=['viper', 'sidewinder', 'cobra'])]
360                     max_speed  shield
361         sidewinder          7       8
362 
363         Index (same behavior as ``df.reindex``)
364 
365         >>> df.loc[pd.Index(["cobra", "viper"], name="foo")]
Differences (unified diff with -expected +actual):
    @@ -1,4 +1,3 @@
            max_speed  shield
    -foo
     cobra          1       2
     viper          4       5

/home/runner/work/pandas/pandas/pandas/core/indexing.py:365: DocTestFailure
__________________ [doctest] pandas.core.indexing._LocIndexer __________________
1043 Alignable boolean Series:
1044 
1045 >>> df.loc[pd.Series([False, True, False],
1046 ...        index=['viper', 'sidewinder', 'cobra'])]
1047             max_speed  shield
1048 sidewinder          7       8
1049 
1050 Index (same behavior as ``df.reindex``)
1051 
1052 >>> df.loc[pd.Index(["cobra", "viper"], name="foo")]
Differences (unified diff with -expected +actual):
    @@ -1,4 +1,3 @@
            max_speed  shield
    -foo
     cobra          1       2
     viper          4       5

/home/runner/work/pandas/pandas/pandas/core/indexing.py:1052: DocTestFailure
```

The next command should report the above errors, and should return clean after the fixes: `./ci/code_checks.sh doctests`

**Comment by hrishikeshnikam2000** [comment]
take

**Comment by hrishikeshnikam2000** [comment]
okay so this issue is actually because a PR #42705 had problems right? So should I make the changes or wait for the PR to be edited?

**Comment by datapythonista** [comment]
Not exactly. Those doctests are broken in master, which means that any PR that we open now, even one with an empty commit, will fail, and we won't be able to merge it. So, the PR for this issue is the first one that should be merged, before we can merge anything else.

**Comment by jreback** [comment]
@datapythonista 

this already has an issue and a PR to fix

**Comment by datapythonista** [comment]
Thanks for the heads up. There is no issue, I see the PR now, didn't see it.

@hrishikeshnikam2000 seems like there is a PR for this already.

**Comment by hrishikeshnikam2000** [comment]
> Not exactly. Those doctests are broken in master, which means that any PR that we open now, even one with an empty commit, will fail, and we won't be able to merge it. So, the PR for this issue is the first one that should be merged, before we can merge anything else.

Okay I, will make the changes. could you please let me know in which file are we supposed to make the changes?




> @datapythonista
> 
> this already has an issue and a PR to fix

So should I look into any other issue.

I'm sorry its my first Issue in this community

**Comment by hrishikeshnikam2000** [comment]
> Thanks for the heads up. There is no issue, I see the PR now, didn't see it.
> 
> @hrishikeshnikam2000 seems like there is a PR for this already.

okay git it
