### ISSUE TITLE
BUG: to_pytimedelta can produce timedeltas that overflow pandas.Timedelta

### ISSUE THREAD

**Issue by xaellison** [pandas-dev/pandas#42805]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

Python to reproduce
```
import pandas as pd
pd.Timedelta((pd.Timedelta.max - pd.Timedelta(microseconds=1)).to_pytimedelta()) # works
pd.Timedelta(pd.Timedelta.max.to_pytimedelta()) # fails
```

#### Problem description
I'd expect `to_pytimedelta` for any Pandas Timedelta to convert to a python Timedelta which won't overflow Pandas Timdelta.

Instead, I get this error:
```
>>> pd.Timedelta(pd.Timedelta.max.to_pytimedelta())
Traceback (most recent call last):
  File "pandas/_libs/tslibs/timedeltas.pyx", line 186, in pandas._libs.tslibs.timedeltas.delta_to_nanoseconds
OverflowError: Python int too large to convert to C long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1301, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
  File "pandas/_libs/tslibs/timedeltas.pyx", line 306, in pandas._libs.tslibs.timedeltas.convert_to_timedelta64
  File "pandas/_libs/tslibs/timedeltas.pyx", line 189, in pandas._libs.tslibs.timedeltas.delta_to_nanoseconds
pandas._libs.tslibs.conversion.OutOfBoundsTimedelta: Python int too large to convert to C long
>>> 
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : c7f7443c1bad8262358114d5e88cd9c8a308e8aa
python           : 3.9.1.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
Version          : Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.1
numpy            : 1.21.1
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 20.2.3
setuptools       : 49.2.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by stephan-hesselmann-by** [comment]
The problem lies with `datetime.timedelta` not supporting nanosecond resolution. `to_pytimedelta` does rounding, which leads to `106751 days 23:47:16.854775807` being rounded `106751 days, 23:47:16.854776` which is then out of bounds. Without changing the rounding behavior I don't see a good solution. Also since the conversion between `pandas.Timedelta` and `datetime.timedelta` is not lossless in the first place, I don't think the round trip should be guaranteed to work.

**Comment by rhshadrach** [comment]
Thanks for the report @xaellison, and @stephan-hesselmann-by for the investigation. Agreed the error seems reasonable here, marking as a closing candidate.

**Comment by mroeschke** [comment]
Agreed, I think the error message is fairly clear about the out of bounds timedelta. Closing.
