### ISSUE TITLE
QST:

### ISSUE THREAD

**Issue by aalkhatib9** [pandas-dev/pandas#42815]
Hope someone can help me out here

I’m trying to create a separate data frame and have it read files based on data I have in a separate data frame 

For example 

Here’s my code so far 
```
Import pandas as pd 

Df = pd.read_excel(aaa.xlsx)

# df would look something like this 
Company  | excel_name 
A                | apple.xslx 
G                | Google.xlsx 
M               | Microsoft.xlsx 
Etc….. 

Df_names = df.company.unique()
Filenames = df.excel_names.unique()

For company in df_names:
    Vars()[comapny] = pd.DataFrame()
```
This so far creates the empty data frames for me but how can I get each dataframe to pd.read_excel(excel_names) in the data frame above in contrast to its company name. 

Data frame A would read Apple.xlsx 
Dataframe G = read_excel(google.xlsx)
M = read_excel(microsoft.xslx) etc….

The data is variable week by week so it could be different companies in week 2 than week 1 and because of that I'm trying o avoid writing any hard code. 

- [ ] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
# Your code here, if applicable

```

**Comment by MarcoGorelli** [comment]
Hi @aalkhatib9 

usage questions should be asked on StackOverflow - if you believe there's a bug in pandas, please include a reproducible example and we'll reopen
