### ISSUE TITLE
BUG: erroneous initialization of a DataFrame with Series objects

### ISSUE THREAD

**Issue by raphaelquast** [pandas-dev/pandas#42818]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
x = pd.Series(["a", "b", "c"])
y = pd.Series([1, 2, 3])

pd.DataFrame(y, x)
>>>     0
>>> a NaN
>>> b NaN
>>> c NaN
```
```python
pd.DataFrame(x, y)
>>>      0
>>> 1    b
>>> 2    c
>>> 3  NaN
```
```python
pd.DataFrame(x.values, y.values)
>>>    0
>>> 1  a
>>> 2  b
>>> 3  c
```

#### Problem description

I would expect `pd.Series` objects to be valid inputs for the `DataFrame` constructor.
If this is not the case a warning (or even raising an error) would be nice...

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : c7f7443c1bad8262358114d5e88cd9c8a308e8aa
python           : 3.9.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.17763
machine          : AMD64
processor        : AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : en
LOCALE           : German_Austria.1252

pandas           : 1.3.1
numpy            : 1.21.1
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.1
setuptools       : 49.6.0.post20210108
Cython           : None
pytest           : 6.2.4
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.2
numexpr          : 2.7.3
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.0
sqlalchemy       : None
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by jreback** [comment]
use a list of the Series

what u r passing is actually valid but thr 2nd arg is the index

**Comment by raphaelquast** [comment]
@jreback thanks for responding!

I don't fully get what you mean "it is actually valid"... the result is really not what I've expected
(and i know that the 2nd arg is supposed to be the index... )

let me clarify this a bit more:
i was just expecting that passing a `Series` object would be similar to passing a `list` or a `1D numpy array`
to summarize:
```python
x = [1,2,3,4,5]
pd.DataFrame(x, index=x)                         # OK
pd.DataFrame(np.array(x), index=x)               # OK
pd.Series(x).to_frame().set_index(pd.Series(x))  # OK

pd.DataFrame(pd.Series(x), index=x)              # NOT OK
pd.DataFrame(dict(a=pd.Series(x)), index=x)      # NOT OK
pd.DataFrame([pd.Series(x)], index=x)            # NOT OK  (generates a 2D grid of values)
```

**Comment by phofl** [comment]
The index of the series and the DataFrame Index are aligned, this causes the nans, since you do not have matching entries in there.

```
x = pd.Series([2, 1, 0])
y = pd.Series([1, 2, 3])

pd.DataFrame(y, x)
```
returns
```   0
2  3
1  2
0  1
```

which should make clear what happens here

**Comment by raphaelquast** [comment]
@phofl 
aaaah, OK i got it 😄 sorry for the confusion!

so basically because the data (e.g. `y`) already has an index defined, the index gets aligned with respect to the new index (instead of being replaced with the new index)

I consider myself as a long-term user of pandas but this was so far not clear to me!
(also the doc of `pd.DataFrame` does not mention this special treatment of `Series` and `DataFrame` compared to other iterables)

> data ndarray (structured or homogeneous), Iterable, dict, or DataFrame
> Dict can contain Series, arrays, constants, dataclass or list-like objects. If data is a dict, column order follows insertion-order.

not sure, but how about a comment in the doc of `pd.DataFrame` to clarify this?  
...or maybe just an Example that uses Series or mixed objects to construct a DataFrame... something like:
```python
>>> pd.DataFrame(dict(a=[1,2,3,4,5], 
>>>                   b=pd.Series([3,4,5], index=[3,4,5])), 
>>>              index=[1,2,3,4,5])
   a    b
1  1  NaN
2  2  NaN
3  3  3.0
4  4  4.0
5  5  5.0
```

**Comment by simonjayhawkins** [comment]
PRs always welcome to clarify/enhance the documentation.

**Comment by tyuyoshi** [comment]
Hi, can I pick this issue as my first OSS contribution?

**Comment by simonjayhawkins** [comment]
@tyuyoshi sure. go for it!

**Comment by dhivyadharshin** [comment]
Can I fix the issues?

**Comment by Stark-developer01** [comment]
> @tyuyoshi sure. go for it!

I have proposed a PR at #43271 can the PR be approved for awaiting workflows?

**Comment by rajaryanbanka** [comment]
Hi, I would like to take up this problem as my first open source contribution.

**Comment by ankitasankars** [comment]
Hello, Can I use this issue as my first contribution?

**Comment by goyaldhara** [comment]
take

**Comment by Tarunssd** [comment]
take

**Comment by amanj7820** [comment]
df = pd.DataFrame(prcpSeries, columns=['prcp'])
df['tmax'] = tmaxSeries
df = prcpSeries.to_frame(name='prcp’)
An alternative here is to create each as a DataFrame and then perform an outer join (using concat):

df1 = pd.DataFrame(prcpSeries, columns=['prcp'])
df2 = pd.DataFrame(tmaxSeries, columns=['tmax'])
...

df = pd.concat([df1, df2, ...], join='outer', axis=1)

In [21]: dfA = pd.DataFrame([1,2], columns=['A'])

In [22]: dfB = pd.DataFrame([1], columns=['B'])

In [23]: pd.concat([dfA, dfB], join='outer', axis=1)
Out[23]:
   A   B
0  1   1
1  2 NaN

**Comment by tyuyoshi** [comment]
take

**Comment by tyuyoshi** [comment]
Sorry, but I have already open PR #42960  
I'm going to wait for review, so please take other issues.
 
@goyaldhara  @Tarunssd  @simonjayhawkins
