### ISSUE TITLE
BUG: Pylance type annotation issue with loc

### ISSUE THREAD

**Issue by cmot17** [pandas-dev/pandas#42847]
#### Code Sample, a copy-pastable example

```python
import pandas as pd

index = ["Firefox", "Chrome", "Safari", "IE10", "Konqueror"]
index2 = [1, 2, 3, 4, 5]

df = pd.DataFrame(
    {
        "http_status": [200, 200, 404, 404, 301],
        "response_time": [0.04, 0.02, 0.07, 0.08, 1.0],
    },
    index=[index, index2],
)

print(df)

print(df.loc[("Firefox", 1)])
```

#### Problem description
![image](https://user-images.githubusercontent.com/25753364/127804362-9641a963-358e-4e97-b672-7fc9aba94c7b.png)

This code works, and is pretty much exactly following what the documentation says I should do by Pylance is still not happy with the types.
#### Expected Output
No type error
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : c7f7443c1bad8262358114d5e88cd9c8a308e8aa
python           : 3.9.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19043
machine          : AMD64
processor        : AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : English_United States.1252

pandas           : 1.3.1
numpy            : 1.21.1
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.2
setuptools       : 56.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by sanskarbtw** [comment]
Unable to recreate this bug. Looks like more of a Pylance issue to me.

**Comment by MarcoGorelli** [comment]
Thanks for the report - pandas doesn't (yet) expose types, so I'd also suggest reporting to pylance
