### ISSUE TITLE
QST: I am getting valueerror: setting an array element with a sequence

### ISSUE THREAD

**Issue by Romper9** [pandas-dev/pandas#42853]
Struggling couple of hours with it, what is going wrong here?

Trying to implement a demo from the tutorial "Art of Pandas"
Here is my code that should replace an element in the array

```

import pandas as pd 
arr = pd.array([2, 5, 3], dtype="int")
arr[0] = [1]
```

**Comment by Kamenlom** [comment]
You are trying to assign array to element here :

```
arr[0] = [1]
```

just assign scalar:

```
arr[0] = 1
```

Check out the [example on fix exception](https://fixexception.com/pandas/setting-an-array-element-with-a-sequence/) with example steps to reproduce and fix

**Comment by attack68** [comment]
the above answer is correct. Please use stackoverflow for this kind of question.
