### ISSUE TITLE
BUG: to_latex not escaping characters correctly

### ISSUE THREAD

**Issue by merubhanot** [pandas-dev/pandas#42869]
- [X ] I have checked that this issue has not already been reported.

- [X ] I have confirmed this bug exists on the latest version of pandas.

- [ X] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Problem description

.to_latex() for Styler seems to have no way to handle when latex-invalid characters are used in the dataset. For instance, if the data values are in percentages (e.g. one cell is 68%, after the usage of .format('{0:,.0%}') on a python dataframe), the latex conversion doesn't handle escaping these characters appropriately for LaTeX. 

https://pandas.pydata.org/docs/reference/api/pandas.io.formats.style.Styler.to_latex.html 

#### Expected Output

Current output to LaTeX: -59%
Correct output: -59\%

<details>

INSTALLED VERSIONS
------------------
commit           : c7f7443c1bad8262358114d5e88cd9c8a308e8aa
python           : 3.8.11.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.122-66.218.amzn2int.x86_64
Version          : #1 SMP Fri May 28 00:16:13 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.1
numpy            : 1.19.5
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.3
setuptools       : 57.0.0
Cython           : 0.29.23
pytest           : 5.4.3
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.6 (dt dec pq3 ext lo64)
jinja2           : 2.11.3
IPython          : 7.22.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : 2021.04.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.1
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : 4.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.6.3
sqlalchemy       : 1.4.11
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.53.1

</details>

**Comment by attack68** [comment]
That is correct. The `to_latex` method does not escape latex characters. That is handled by the `format` method as documented.

The `format` method also documents that escaping is done before the formatter, which implies that if you need to format a percentage as per `{:,.1%}` then this should be refactored to:

```
df = DataFrame([[1,2]])
df.style.format(lambda val: "{:,.1f}\%".format(val*100)).to_latex()

\begin{tabular}{lrr}
{} & {0} & {1} \\
0 & 100.0\% & 200.0\% \\
\end{tabular}

```

This won't change, and if a formatter is supplied it is expected that a user supplies the format they require.
