### ISSUE TITLE
DOC: to_latex documentation for Styler

### ISSUE THREAD

**Issue by merubhanot** [pandas-dev/pandas#42868]
#### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.io.formats.style.Styler.to_latex.html

#### Documentation problem

I think the set of packages needed to get this to work should be more clearly defined, given how different peoples' Latex setups are. For instance, the current package list in the documentation doesn't seem to provide any explaination for where the \thsolid command comes from, which seems to be used in all of the tables generated by this table.

#### Suggested fix for documentation

A suggested set of imports to add to the preamble of a LaTeX document should be clearly laid out, and complete, with a minimum working example present including both Python and accompanying LaTeX code.

**Comment by attack68** [comment]
what is `\thsolid`. it is not a defauly output but `Styler.to_latex()`

would welcome a full example.

**Comment by mroeschke** [comment]
Happy to reopen once more information is provided.
