### ISSUE TITLE
BUG: wrong/confusing error message in DataFrame.take with a scalar indexer

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#42875]
```
In [4]: df = pd.DataFrame({'a': [1, 2, 3]})

In [5]: df.take(1)
...

~/scipy/pandas/pandas/core/indexes/range.py in take(self, indices, axis, allow_fill, fill_value, **kwargs)
    433     ) -> Int64Index:
    434         with rewrite_exception("Int64Index", type(self).__name__):
--> 435             return self._int64index.take(
    436                 indices,
    437                 axis=axis,

~/scipy/pandas/pandas/core/indexes/base.py in take(self, indices, axis, allow_fill, fill_value, **kwargs)
    962             self._values, indices, allow_fill=allow_fill, fill_value=self._na_value
    963         )
--> 964         return type(self)._simple_new(taken, name=self.name)
    965 
    966     @final

~/scipy/pandas/pandas/core/indexes/base.py in _simple_new(cls, values, name)
    611         Must be careful not to recurse.
    612         """
--> 613         assert isinstance(values, np.ndarray), type(values)
    614 
    615         result = object.__new__(cls)

AssertionError: <class 'numpy.int64'>
```

`take` requires an array-like for the indexer, but when passing a scalar you get a not very useful error message as above. We should raise a ValueError (or rather TypeError) instead with an informative message.

It actually comes from the Index take implementation:

```
In [9]: pd.Index([1, 2, 3]).take(1)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-9-ce9f87ba8bd2> in <module>
----> 1 pd.Index([1, 2, 3]).take(1)

~/scipy/pandas/pandas/core/indexes/base.py in take(self, indices, axis, allow_fill, fill_value, **kwargs)
    962             self._values, indices, allow_fill=allow_fill, fill_value=self._na_value
    963         )
--> 964         return type(self)._simple_new(taken, name=self.name)
    965 
    966     @final

~/scipy/pandas/pandas/core/indexes/base.py in _simple_new(cls, values, name)
    611         Must be careful not to recurse.
    612         """
--> 613         assert isinstance(values, np.ndarray), type(values)
    614 
    615         result = object.__new__(cls)

AssertionError: <class 'numpy.int64'>
```

**Comment by radioactive11** [comment]
Can I take up this issue?

**Comment by jorisvandenbossche** [comment]
Yes, certainly!

**Comment by Arnab1181412** [comment]
Sir can I take this issue? Im new to the contrib community.

**Comment by radioactive11** [comment]
@jorisvandenbossche I am working on this issue. Just wanted to approve my approach. Currently, an assertion is being raised if `values` is not of type `np.ndarray`.

Instead, we want to raise a `TypeError` with a helpful message stating `values` should be of type `np.ndarray`.

**Comment by jorisvandenbossche** [comment]
> Currently, an assertion is being raised if values is not of type np.ndarray.

This is raised inside the Index._simple_new. But for fixing this PR, I would add a check higher up in Index.take to avoid that we pass a non-ndarray to Index._simple_new

**Comment by Arnab1181412** [comment]
@jorisvandenbossche Sure sir and I had one query that how will I know that the issue has been merged successfully .

**Comment by jorisvandenbossche** [comment]
@Arnab1181412 you will get a notification when this issue would get closed.

**Comment by sinking8** [comment]
@jorisvandenbossche  Sir can I take up this issue?

**Comment by a-n-622** [comment]
Sir, in the documentation of df.take, I noticed that the input indices need to be in the form of an array. Here, in our issue, it has been passed as an integer. 
When I tried to replicate the issue, and passed 1 as [1] instead, there was no issue. I feel it was an error while passing the variable. 
Regards.

**Comment by a-n-622** [comment]
Sir, instead of scalar indexer, we should ideally pass a scalar array of indices. This is what I gathered from the documentation, and the error message hints towards the same thing, that it is expecting an array (I had similar issue in some other project I was doing). I hope this is resolved.

**Comment by radioactive11** [comment]
@a-n-622 We should pass an array-like indexer in .take(). The goal of this issue is to improve the error message when a scalar indexer is passed.

**Comment by a-n-622** [comment]
@radioactive11 got it. I am viewing the discussion on #42886 now. thanks.

**Comment by S-T-A-R-L-O-R-D** [comment]
Hello everyone, I am working on this issue. I have understood the problem and hopefully will solve it by tomorrow.

**Comment by radioactive11** [comment]
@S-T-A-R-L-O-R-D thanks for showing interest but I already have a PR open and have almost solved the issue.

**Comment by S-T-A-R-L-O-R-D** [comment]
ok

**Comment by Anupam-USP** [comment]
Is the issue solved?

**Comment by ADing4818** [comment]
I see that this issue is still open with no comments in the past 1.5 months. I would like to take this issue.

**Comment by ADing4818** [comment]
take

**Comment by gfkang** [comment]
FYI, I'm @ADing4818 's teammate for a project, so I'll be creating the PR for this issue on behalf of him.
