### ISSUE TITLE
QST: why pandas.Series.unique() behaves differently from numpy.unique()?

### ISSUE THREAD

**Issue by emanuele** [pandas-dev/pandas#42876]
First of all, thank you for the great Pandas!

The docs of `pandas.Series.unique()` clearly state that the function does NOT sort the elements. Differently, `numpy.unique()` sorts the elements. What is the reason behind this counterintuitive difference? It is quite unexpected and deemed to create nasty bugs in code - which just happen to me.
Just to be clear:
```
In [3]: a=[3,2,1,0]

In [4]: np.unique(a)
Out[4]: array([0, 1, 2, 3])

In [5]: pd.Series(a).unique()
Out[5]: array([3, 2, 1, 0])
```
In the context of code that uses both `numpy` and `pandas`, it would be greatly beneficial to have the same behavior. Would that be possible?

**Comment by jreback** [comment]
pandas uses a hash table and is significantly faster than numpy here - i doubt pandas nor numpy are going to change
