### ISSUE TITLE
BUG: DataFrame[Int64].mean().dtype is object, should be Float64

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#42895]
This breaks the last corner case I want to test for #33036.

```
arr = np.random.randn(4, 3).astype("int64")
df = pd.DataFrame(arr).astype("Int64")
df.iloc[:, 1] = pd.NA  # <-- incorrectly casts to object, lets cast back and ignore that for now
df = df.astype("Int64")

res = df.mean()

>>> res
0     0.0
1    <NA>
2   -0.25
dtype: object
```

Trivial to fix with 2D EAs, not sure how/if to fix it without.

**Comment by Demetrio92** [comment]
I was digging into the related issue. And figured out that despite that casting problem `.mean()` actually works as OP expects it if the second casting is removed. 

```python
arr = np.random.randn(4, 3).astype("int64")
df = pd.DataFrame(arr).astype("Int64")
df.iloc[:, 1] = pd.NA  # <-- incorrectly casts to object, lets cast back and ignore that for now
# df = df.astype("Int64")

res = df.mean()
```

Not sure why, but the above code works as expected 
```
0    0.00
1     NaN
2   -0.25
dtype: float64
```

Tested using pandas `1.3.4`

**Comment by jbrockmendel** [comment]
@Demetrio92 the underlying cause here is the lack of 2D support for IntegerArray.  Further investigation is not a good use of your time.  A place where investigative eyeballs would be very helpful is https://github.com/pandas-dev/pandas/blob/master/pandas/core/internals/blocks.py#L1265 "# TODO: in all tests we have mask.all(); can we rely on that?"

**Comment by mroeschke** [comment]
Closed by https://github.com/pandas-dev/pandas/pull/52788
