### ISSUE TITLE
BUG: dataframe.goupby()

### ISSUE THREAD

**Issue by on55** [pandas-dev/pandas#42898]
i have a .py document work ok in before edition, but fail in 1.3.1

these two sentence fail:
   a = abc.loc[:, ['name', 'gl', 'time']]
  output = a.groupby(['name']).sum().reset_index()

it run ok before, but under  pandas edition 1.3.1, it report fail.
i found  output is not what i want , it only have one series with 'name'. the output dataframe drop 'gl' and 'time' list. 
it seems  groupby  function not work well.
so strange is ,  i found if i use  a.groupby(['name']).sum(0).reset_index(drop=False),  i add a 0 into sum(), it work well and output is ok.
so strange...

**Comment by rhshadrach** [comment]
Thanks for the report @on55, my guess is that the columns getting dropped have become object-type; this is the default behavior of `groupby(...).sum()` (but see [this related deprecation](https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.3.0.html#deprecated-dropping-nuisance-columns-in-dataframe-reductions-and-dataframegroupby-operations)). By calling `groupby(...).sum(numeric_only=False)` (which you did by passing `0`), you are instructing pandas to keep all columns.

Can you provide a reproducible example? In other words, what is the DataFrame `abc` that you posted above?

**Comment by on55** [comment]
got it, i found it treat float series as object.
i define the type and everything is ok. 
but not sure why former edition is ok, and this edition not work.
thank you.
