### ISSUE TITLE
QST: Generate sentece_id from the word column.

### ISSUE THREAD

**Issue by sami10644** [pandas-dev/pandas#42912]
I want to generate sentece_id from the word column. Between two fullstop puncuation ( | ,?, !) all the words will be counted as a sentence_id . 
I have two columns named as Words and Labels . I wanna generate a new column which specify the words of the same sentences as an unique id . I have the words and labels column . 
Can anyone help me ?
In this format I'm trying to convert - (https://simpletransformers.ai/docs/ner-data-formats/)
my dataframe is kinda look like this. -
![2021-08-06](https://user-images.githubusercontent.com/61244442/128474829-01165088-00fd-4abd-85d9-1338370464b6.png)

**Comment by MarcoGorelli** [comment]
Hi @sami10644 

This isn't really the place to ask for help - please ask on StackOverflow / somewhere else. If you believe there's a bug in pandas, include a reproducible example and we'll reopen
