### ISSUE TITLE
ENH: Series types does not support inverse indexing

### ISSUE THREAD

**Issue by zlzlelzl** [pandas-dev/pandas#42913]
#### Is your feature request related to a problem?

Indexed data on series types does not support inverse indexing (like lists in Python).

#### Describe the solution you'd like

In the Series type, I wish negative index to count data from the back.

#### Additional context

```python
r = [1, 2]
ser = pd.Series(r, copy=False)
ser.iloc[0] = 999
print(ser)
# 0    999
# 1      2
# dtype: int64

print(ser[0])
# 999

print(ser[-1])
# KeyError: -1
```
expected data ( it is not good looking )
```python
print(ser[len(ser) - 1])
# 2
```

**Comment by jreback** [comment]
pls ready about indexing https://pandas.pydata.org/docs/user_guide/indexing.html

[] is a label indexer, use .iloc for positional indexing
