### ISSUE TITLE
BUG: Limitation of adding years in dateoffset pandas

### ISSUE THREAD

**Issue by rinshankolayil** [pandas-dev/pandas#42948]
This is reference to other question i found on Stackoverflow, but i am not intersted add the reference here without their permission. My question is what will be the reason for i cannot add more than 240 years to pandas dataframe with pd.offsets.DateOffset?.

Here is my code

```
df=pd.date_range(start="2020-10-29",end="2020-10-30").to_pydatetime().tolist()
df=pd.DataFrame(df,columns=['dte'])
df["dte_"]=df["dte"]+pd.offsets.DateOffset(years=241)
```
Output is
```
     dte               dte_
0   2020-10-29  2261-10-29
1   2020-10-30  2261-10-30

df["dte_"]=df["dte"]+pd.offsets.DateOffset(years=242)
```
The output of above code is
```
     dte                 dte_
0   2020-10-29  1678-04-09 00:25:26.290448384
1   2020-10-30  1678-04-10 00:25:26.290448384
```

If i change start and end date to 2021, I am able to add only 240 years as follows ,
`df=pd.date_range(start="2021-10-29",end="2021-10-30").to_pydatetime().tolist()`

Other code with year 2200 

```
df=pd.date_range(start="2200-10-29",end="2200-10-30").to_pydatetime().tolist()
df=pd.DataFrame(df,columns=['dte'])
df["dte_"]=df["dte"]+pd.offsets.DateOffset(years=62) # i.e I can add only 61 years
```

Output is

```
     dte                dte_
0   2200-10-29  1678-04-09 00:25:26.290448384
1   2200-10-30  1678-04-10 00:25:26.290448384
```

- Is this due to limitation of availability calender date after 240 Years from now?
- Or pandas Limitation?
- Or is this my misunderstanding about DateOffset?
- I undestand 2261 Supposed to be the last year. Is there any speciality for 2261?
- From one of answer i understand `timestamp(9200000000000000000) was Monday, July 15, 2261 2:33:20 PM approximately Timestamp('2262-04-11 23:47:16.854775807'). So what is the solution?

**Comment by Liam3851** [comment]
This is covered in the [documention](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timestamp-limitations) along with [alternatives for long periods](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-oob).
