### ISSUE TITLE
Python 3.10 manylinux wheels

### ISSUE THREAD

**Issue by hrnciar** [pandas-dev/pandas#42946]
Hello.

Could you please release CPython 3.10 manylinux wheels on PyPI? 

Python 3.10.0 release candidate 1 was released this week: https://www.python.org/downloads/release/python-3100rc1/

It should be quite safe to release wheels for release candidate. ABI for Python 3.10 should be frozen from now on, even for bugfixes. From release notes: 

> There will be no ABI changes from this point forward in the 3.10 series and the goal is that there will be as few code changes as possible.

Thank You.

**Comment by lithomas1** [comment]
I think we are currently waiting on numpy to provide its Python 3.10 wheels before we do.

**Comment by hroncok** [comment]
https://github.com/numpy/numpy/issues/19630

**Comment by hrnciar** [comment]
> I think we are currently waiting on numpy to provide its Python 3.10 wheels before we do.

@lithomas1 numpy's wheels are now available. https://pypi.org/project/numpy/1.21.2/#files

**Comment by lithomas1** [comment]
Milestoning for 1.3.3 since I think we've agreed to upload wheels.

**Comment by simonjayhawkins** [comment]
wheels for pandas 1.3.3 uploaded to PyPI

**Comment by hroncok** [comment]
Thank you @simonjayhawkins.

**Comment by simonjayhawkins** [comment]
Thanks to @fangchenli and @lithomas1
