### ISSUE TITLE
Use new GitHub issue forms?

### ISSUE THREAD

**Issue by mzeitlin11** [pandas-dev/pandas#42951]
Github recently released a beta for issue forms (https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/). Scipy already has an open pr to use these to replace existing issue templates (https://github.com/scipy/scipy/pull/14493)

Seems like a good way to improve issue quality, while also making writing issues easier for users (through improvements like built-in code formatting).

**Comment by jorisvandenbossche** [comment]
Sounds as a good idea! At a minimum, it would already be much nicer to put the information (eg the link to best practice to report bugs) in text in the form without it ending up in the actual issue report.

**Comment by mzeitlin11** [comment]
Made a test to see what it might be like for our documentation issue template. Feel free to open any issues at https://github.com/mzeitlin11/issue-forms to play around with it / make any suggestions. 

Will add more of these when I have time (especially the bug report one should be interesting!)

**Comment by jbrockmendel** [comment]
closed by #43411?
