### ISSUE TITLE
CI: Dateutil broke CI

### ISSUE THREAD

**Issue by lithomas1** [pandas-dev/pandas#42961]
Failing CI is actions 3.9 numpy dev. 

It fails with a FileNotFound error I think and I believe that its probably an upstream issue. 

Any reason why we're installing dateutil from source here on the CI? I know that its a dependency but we aren't installing pytz from source on the same env.

**Comment by jorisvandenbossche** [comment]
Do you have a traceback or link to one of the failing builds?

**Comment by mroeschke** [comment]
Don't think we're seeing this anymore, especially since we're on numpy dev 3.10 and not reading from source, so closing. Can reopen again if this is an issue.
