### ISSUE TITLE
BUG: Index.droplevel() used in an .apply() function affects  subsequent rows in an accumulating fashion

### ISSUE THREAD

**Issue by soilstack** [pandas-dev/pandas#42967]
- [x ] I have checked that this issue has not already been reported.

- [x ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```import numpy as np
import pandas as pd
print(f"pandas: {pd.__version__}")
!python --version   


cols = pd.MultiIndex.from_product([['coz',], ['alpha', 'beta', 'gamma']], names=['health', 'protocol'])
index=pd.date_range(start="1jan2020", end=None, periods=5, freq="d", name="Date")
data = np.random.rand(5,3)

df = pd.DataFrame(data=data, index=index, columns=cols)

def foo(row):
    row.index = row.index.droplevel(0)
    return row['beta'] > row['alpha']

df.apply(foo, axis="columns")

```

#### Problem description

In `Pandas 0.25.3` this function works.   In `Pandas 1.2.4`` it fails with an `ValueError: Cannot remove 1 levels from an index with 1 levels`.

What seems to be happening is when I apply `.droplevel(0)` on a row inside the `.apply` function, it removes a level for that instance of the row.Index passed in as a parameter, but also for all the subsequent rows passed to the `.apply`.  So if I have a ten level column,  apply would process ten rows and then this this `ValueError` trips.

I can get around this by applying the `.droplevel()` on a copy of the row  `row.index = row.index.droplevel(0)`  but seems like a hack, and I'm confused because this used to work. Perhaps is a bug.

#### Expected Output
pandas: 0.25.3
```
Python 3.7.11
Date
2020-01-01    False
2020-01-02     True
2020-01-03    False
2020-01-04     True
2020-01-05    False
Freq: D, dtype: bool
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.9.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_Singapore.1252

pandas           : 1.2.4
numpy            : 1.20.1
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 52.0.0.post20210125
Cython           : 0.29.23
pytest           : 6.2.3
hypothesis       : None
sphinx           : 4.0.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.8
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.22.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.9.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.2
sqlalchemy       : 1.4.7
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.53.1
</details>

**Comment by MarcoGorelli** [comment]
Hi @soilstack - you shouldn't mutate inside a user-defined-function to apply, see https://pandas.pydata.org/docs/user_guide/gotchas.html#mutating-with-user-defined-function-udf-methods

**Comment by soilstack** [comment]
@MarcoGorelli  Oh, thanks for that.  So this isn't really a bug, then, as it's explicitly advised against doing this? Guess I was just lucky that it worked in old 0.25.3.
