### ISSUE TITLE
How to add coroutines in apply lambda function

### ISSUE THREAD

**Issue by zysNLP** [pandas-dev/pandas#42965]
#### Question about pandas

I write a function use apply and lambda for one column in a DataFrame. But because every time excute once fucntion use lot of time, so I turn the column into a list and use coroutines and for loop. I create a new list then insert into my DataFrame. I want to know if I can use both apply funtion and coroutines at the same time? But I think apply has been a parallel operation. It seems not work in real.

```python
# Your code here, if applicable

list1 = ["a", "b", "c", "d",....]
list2 = [1,  2, 3, 4,...]
df = pd.DataFrame({"col1":list1, "col2":list2})

def add_suffix(x):
    return x+"_suffixsuffix"

df["col_with_suffix"] = df["col1"].apply(lambda x: add_suffix(x))


# another method use coroutines 

col1_list = df["col1"].values.tolist()
import genvent
from gevent import monkey; monkey.patch_all()
g_list = []
i = 0
for x in col1_list:
    i =i + 1
    g = gevent.spawn(add_suffix, x)
    g_list.append(g)
    if i > 200:
        gevent.joinall(g_list)
        i = 0
        g_list = []



```

**Comment by attack68** [comment]
I'm not sure the reason for you wanting to use these coroutines but they look like they would be so much slower to me.

```python
l1 = [1,2,3,4,5,6,7,8,9]
l2 = ["a", "b", "c", "d", "e", "f", "h", "i", "j"]
df = pd.DataFrame({"col1": l1, "col2": l2})
df

%timeit df["col2"] + "suffix"
75.2 µs ± 735 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

%timeit df["col2"].apply(lambda s: s + "suffix")
133 µs ± 839 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

%timeit df[["col2"]].applymap(lambda v: v + "suffix")
833 µs ± 14.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

Using vectorised string functions is fastest. Using `apply`, which is a vectorised op is close, and using `applymap` which is essentially a loop is more than 10x worse.

**Comment by mroeschke** [comment]
Generally pandas objects are not threadsafe: https://pandas.pydata.org/docs/user_guide/gotchas.html#thread-safety

If you are able to utilize and of the ops with the numba engine you can access parallelism that way as well: https://pandas.pydata.org/pandas-docs/stable/user_guide/enhancingperf.html#pandas-numba-engine

But it is not likely that native parallelism will be added to pandas, possible only dispatching to different engines. But as mentioned above, the vectorized operations area already pretty fast so the use case in the example above is a bit unclear. Closing.
