### ISSUE TITLE
Possible undefined variable 

### ISSUE THREAD

**Issue by Jarvx** [pandas-dev/pandas#42978]
https://github.com/pandas-dev/pandas/blob/99cf794ae2f63f3137290e7df59b1d31b22ae3d3/pandas/core/reshape/pivot.py#L243

I found the variable values_multi is not defined when  values_passed is False, but the variable is used in line 243 

```
  if values_passed:
        if is_list_like(values):
            values_multi = True
            values = list(values)
        else:
            values_multi = False
            values = [values]
```
``` if values_passed and not values_multi and table.columns.nlevels > 1:```

**Comment by phofl** [comment]
``values_multi`` is only reached if ``values_passed`` is True, so everything ok

**Comment by Jarvx** [comment]
Thanks, due to the execution strategy, values_multi is only access when values_passed is true.
