### ISSUE TITLE
Why can't write the dataframe into excel with sheetname?

### ISSUE THREAD

**Issue by yufeiluo** [pandas-dev/pandas#42994]
I have created a new workbook and a worksheet named `raw`:

    from openpyxl import Workbook
    wb = Workbook()
    ws = wb.active
    dest_fn = '/tmp/mytest.xlsx'
    ws.title = "raw"

Then to create a dataframe :

    import pandas as pd
    data = [{"code":"dow","value":35100}]
    df = pd.DataFrame.from_dict(data)

To write and save it:

    df.to_excel (dest_fn, index = False, header=False, startcol=1,startrow=2,sheet_name="raw")
    wb.save(dest_fn)
    wb.close()

Why no data in the dest_fn `/tmp/mytest.xlsx` when to open it?

**Comment by phofl** [comment]
Why not simply

```
data = [{"code":"dow","value":35100}]
df = pd.DataFrame.from_dict(data)
df.to_excel("xxx.xlsx", index = False, header=False, startcol=1,startrow=2,sheet_name="raw")
```
?

In general please ask usage questions on stackoverflow

**Comment by phofl** [comment]
Closing, please ping to reopen if you think this is a pandas bug
