### ISSUE TITLE
pandas version

### ISSUE THREAD

**Issue by Pysion-lin** [pandas-dev/pandas#43012]
pandas==1.0.3
In [16]: df.where(df.notnull(), None)
Out[16]: 
            A               B
0   2013-01-01      1
1          NaT           2
2  2013-01-03    None

but pandas==1.3.1
In [16]: df.where(df.notnull(), None)
Out[16]: 
           A             B
0 2013-01-01     1
1        NaT          2
2 2013-01-03  NaN

why?

@MarcoGorelli

**Comment by MarcoGorelli** [comment]
Hi @Pysion-lin - duplicate of #42423?

**Comment by Pysion-lin** [comment]
> Hi @Pysion-lin - duplicate of #42423?

Thankyou very much

**Comment by MarcoGorelli** [comment]
no worries 😄
