### ISSUE TITLE
DOC: rolling return type inconsistent with doc

### ISSUE THREAD

**Issue by debnathshoham** [pandas-dev/pandas#43023]
#### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.core.window.rolling.Rolling.min.html

**Note**: You can check the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/).

#### Documentation problem

the return type of rolling methods (rolling.min / rolling.max) is mentioned to be same as the original object. But the default return types appears to be `float64`.

```python
>>> import pandas as pd
>>> s = pd.Series([4, 3, 5, 2, 6])
>>> s.dtypes
dtype('int64')
>>> s.rolling(3).min().dtypes
dtype('float64')
>>> s.rolling(3).max().dtypes
dtype('float64')
>>> s.rolling(3).std().dtypes
dtype('float64')
```

#### Suggested fix for documentation

Maybe the doc should mention the default return type

**Comment by phofl** [comment]
This is mentioned in https://pandas.pydata.org/pandas-docs/stable/user_guide/window.html#overview

**Comment by mroeschke** [comment]
The first mention of type relates to the type of object, but I guess could also add a note specifically about the dtype to avoid confusion.
