### ISSUE TITLE
REF: use `_get_axis_number` instead of `if axis in [...]`:

### ISSUE THREAD

**Issue by attack68** [pandas-dev/pandas#43048]
This PR regards searching the **non-test codebase** (i.e. don't find code examples in pandas/tests) for examples like the following:

Try to find and replace logic like:

```python
if axis in [0, "index"]:
    ...
elif axis in [1, "columns"]:
    ...
else:
    ...
```

with the standard codebase method `get_axis_number(axis)`. This is a DataFrame method so often you need use local DataFrame objects to call this method.

It may also be necessary to change `axis` args in internal methods to consistently accept the same input format compatible with this method, i.e. axis as an integer (0 or 1).

This is an open issue and contributions are welcome to solve individual files in the code. As an example see #43078 or other merged contributions below.

- [x] `style.py` #43078
- [x] `test_label_or_level_utils.py` #43131
- [x] #43121

**Comment by rhshadrach** [comment]
I think this applies to all code, not just the style, is that right? Or would you like to keep this issue focused on just the styler?

**Comment by attack68** [comment]
@rhshadrach I don't know. I know that it applies to much of the stuff I wrote in `Styler` that @jreback pointed out to me. If it applies more broadly can convert this issue into a master tracker and try to locate more examples..

**Comment by jreback** [comment]
yeah this was mainly for Styler, but its possible we do this elsewhere in the codebase so should clean those up (and ideally have a pre-commit rule but might be non-trivial)

**Comment by dhivyadharshin** [comment]
Can I work on this issues?

**Comment by rhshadrach** [comment]
I noticed it in the tests recently, doing some quick searches I'm seeing a few instances in core as well.

**Comment by HemanjaliAdini** [comment]
hey, can i have this issue?
I'm quite new to this so I might need some guidance

**Comment by dhivyadharshin** [comment]
Yes you can!

**Comment by attack68** [comment]
As has been commented here there are likely many places this pattern is present in the code and needs addressing. 
The best PRs will be to work on a single file and correct all the offending occurrences within that file. There may be only one item to address or several.
After the PR is approved and merged, we will note it down here as having been addressed.
My example above shows how to do this for a file `style.py`.

In order to find bits to work on you will have to search for a pattern in the code `axis in` and then see if you can correct it as per my example.

**Comment by dhivyadharshin** [comment]
Will do, thanks!

**Comment by RohanTrix** [comment]
take

**Comment by RohanTrix** [comment]
@attack68 I have assigned myself to work on this issue, should I move forward with it?

**Comment by dhivyadharshin** [comment]
Yes, go ahead.

**Comment by attack68** [comment]
Anyone is welcome to work on this issue. This will not be solved by just one PR, there are likely many places and many files where the same work needs to be done. Therefore many people can work on this, simultaneously.

**Comment by alli1999** [comment]
Hello, could I help with this issue?
This would be my first ever contribution so I could use some guidance

**Comment by HardevKhandhar** [comment]
Hi @jreback & @attack68 
I have linked a PR relating to changes done in one of the files. Thank you.

**Comment by soni-muskan1234** [comment]
take

**Comment by ForthenchoPacino** [comment]
take

**Comment by ForthenchoPacino** [comment]
found a few more instances, working on correcting them

**Comment by soni-muskan1234** [comment]
How i can run test suites prior to making a PR

**Comment by simonjayhawkins** [comment]
https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#running-the-test-suite

**Comment by soni-muskan1234** [comment]
I am new to open source.
Anyone please tell me, after I have refactored the code in my local repository how shall I proceed.

**Comment by simonjayhawkins** [comment]
details in https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#contributing-to-pandas

if anything unclear please let us know or open an issue suggesting improvements.

**Comment by Stark-developer01** [comment]
take

**Comment by SARANYA233** [comment]
I m first time to this contribution field, I need some guidance to work on this issue. can I?

**Comment by attack68** [comment]
Please see the revised description of this issue.
You can find code patterns in the generic codebase. Don't try and fix test files in `pandas/tests`.

**Comment by KiranHipparagi** [comment]
I am new to OpenSource Contributions . I want to work on this feature .
@attack68 Can I contribute to this issue ?

**Comment by KiranHipparagi** [comment]
take

**Comment by Tarunssd** [comment]
take

**Comment by tambibhavika2000** [comment]
take

**Comment by attack68** [comment]
Did a quick search of the codebase and outside of all the test files this seems to have been addressed by all contributions now.
