### ISSUE TITLE
ENH: Allow for passing in engine_kwargs to read_excel

### ISSUE THREAD

**Issue by driscoll42** [pandas-dev/pandas#43053]
#### Is your feature request related to a problem?

In experimenting with openpyxl, I have found that I can load my files in faster when read_only=True, and I would like to pass in that argument to read_excel

#### Describe the solution you'd like

Similar to ExcelWriter, I would like to have engine_kwargs added to read_excel to pass in engine specific kwargs.

#### API breaking implications

This shouldn't break it.

#### Describe alternatives you've considered

Just use read_excel as is, works fine but I can load large excel files more quickly with using engine specific kwargs

#### Additional context

I imgine it would look like pd.read_excel('example.xlsx', engine='openpyxl', engine_kwargs={'read_only : True}) for am example

**Comment by rhshadrach** [comment]
Is there is a case where we shouldn't be passing `read_only=True`?

**Comment by rhshadrach** [comment]
But makes sense to allow passing kwargs through to the engine regardless.

**Comment by driscoll42** [comment]
I don't believe so. When I looked at the source code further after opening this ticket I realized that it was already being passed along with a few variables with data_only and keep_links which probably give all the speedup possible. I was looking if the convert_cell loop could be sped up at all as that, at least in my test cases, was 93% of the load time and couldn't see anything.

**Comment by scotscotmcc** [comment]
I'm happy to take this (or try to, at least).

**Comment by rmhowe425** [comment]
@mroeschke @rhshadrach Should this issue be closed now that #52214 has been merged?

**Comment by rhshadrach** [comment]
Thanks - agreed.
