### ISSUE TITLE
BUG: Incorrect assigning Series to DF

### ISSUE THREAD

**Issue by YarShev** [pandas-dev/pandas#43079]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas
df = pandas.DataFrame(
    {
        "a": [1, 1, 2, 3],
        "b": [3, 4, 5, 6],
        "c": [7, 8, 9, 10],
        "d": [11, 12, 13, 14],
    }, index= ["1", "2", "3", "4"]
)
a = df["a"] = pandas.Series([5, 5, 5, 5])
a
0    5
1    5
2    5
3    5
dtype: int64
df
    a  b   c   d
1 NaN  3   7  11
2 NaN  4   8  12
3 NaN  5   9  13
4 NaN  6  10  14
```

#### Problem description & Expected Output

Shouldn't the column "a" contain `Series([5, 5, 5, 5])`?

#### Output of ``pd.show_versions()``

<details>

pandas           : 1.3.2
numpy            : 1.21.1
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.1
setuptools       : 49.6.0.post20210108
Cython           : None
pytest           : 6.2.4
hypothesis       : None
sphinx           : None
blosc            : None
feather          : 0.4.1
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.25.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 2021.07.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.2.2
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : 0.15.0
pyarrow          : 3.0.0
pyxlsb           : None
s3fs             : 0.4.2
scipy            : 1.7.0
sqlalchemy       : 1.4.22
tables           : 3.6.1
tabulate         : None
xarray           : 0.19.0
xlrd             : 2.0.1
xlwt             : None
numba            : None

</details>

**Comment by phofl** [comment]
No, the rhs is aligned to the rhs. The index does not match, hence the nans

**Comment by YarShev** [comment]
Thanks! Closing the issue.
