### ISSUE TITLE
BUG: pandas.DataFrame.reindex -  sample code to expand the dataframe as given in the API reference is not working

### ISSUE THREAD

**Issue by Ramaseshanr** [pandas-dev/pandas#43085]
- [x ] I have checked that this issue has not already been reported.

- [x ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example
date_index = pd.date_range('1/1/2010', periods=6, freq='D')
df2 = pd.DataFrame({"prices": [100, 101, np.nan, 100, 89, 88]},
                   index=date_index)
df2
date_index2 = pd.date_range('12/29/2009', periods=10, freq='D')
df2.reindex(date_index2)
df2

```python
date_index = pd.date_range('1/1/2010', periods=6, freq='D')
df2 = pd.DataFrame({"prices": [100, 101, np.nan, 100, 89, 88]},
                   index=date_index)
df2
date_index2 = pd.date_range('12/29/2009', periods=10, freq='D')
df2.reindex(date_index2)
df2
```

#### Problem description

Unable to expand a dataframe using reindex, if the index is datetime. It works for other data types. The code is copied from the  [API reference](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reindex.html) of Pandas
#### Expected Output
            prices
2009-12-29     NaN
2009-12-30     NaN
2009-12-31     NaN
2010-01-01   100.0
2010-01-02   101.0
2010-01-03     NaN
2010-01-04   100.0
2010-01-05    89.0
2010-01-06    88.0
2010-01-07     NaN
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 5f648bf1706dd75a9ca0d29f26eadfbb595fe52b
python           : 3.9.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19043
machine          : AMD64
processor        : Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_India.1252

pandas           : 1.3.2
numpy            : 1.21.1
</details>

**Comment by attack68** [comment]
Can confirm this fails.
Should probably add this to the doctest list as well since it is an api example.

**Comment by attack68** [comment]
of course, as pointed out by @pragatimehra21 the DataFrame object returned by `reindex` should overwrite, i.e.

use: `df2 = df2.reindex(date_index2)`.

Should correct the docs

**Comment by debnathshoham** [comment]
Hi @attack68 , actually [here](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reindex.html). I can see this works exactly in master. In the doc `df2.reindex(date_index2)` returns the above and not `df2`.

```python
>>> import pandas as pd
>>> pd.__version__
'1.4.0.dev0+444.gf5d1cacb38'
>>> date_index = pd.date_range('1/1/2010', periods=6, freq='D')
>>> df2 = pd.DataFrame({"prices": [100, 101, np.nan, 100, 89, 88]},
...                     index=date_index)
>>> df2
            prices
2010-01-01   100.0
2010-01-02   101.0
2010-01-03     NaN
2010-01-04   100.0
2010-01-05    89.0
2010-01-06    88.0
>>> date_index2 = pd.date_range('12/29/2009', periods=10, freq='D')
>>> df2.reindex(date_index2)
            prices
2009-12-29     NaN
2009-12-30     NaN
2009-12-31     NaN
2010-01-01   100.0
2010-01-02   101.0
2010-01-03     NaN
2010-01-04   100.0
2010-01-05    89.0
2010-01-06    88.0
2010-01-07     NaN
```

![Screenshot 2021-08-18 at 9 52 19 PM](https://user-images.githubusercontent.com/6472290/129935694-7876f24b-102c-47b2-9678-0eef1c023826.png)

**Comment by attack68** [comment]
Yes looks correct. Thanks @debnathshoham
