### ISSUE TITLE
ENH:why we don't have an axis called column

### ISSUE THREAD

**Issue by AhmedIbrahim336** [pandas-dev/pandas#43094]
### The Problem 
Currently, we can select the `axis` by typing `0` `1` `index`.
But why we can't select the axis also by typing `column`. 
Personally, I prefer to use `index` as an axis as this makes my code clean.

#### The solution
Check for the key world `column` as an axis if so this means it is the same as  `1`
After doing this it will be like this 
```python
0 == index 
1 == column 
```

#### API breaking implications
This code here throw an error.
```python
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
f = lambda x: x.max() - x.min()frame.apply()
frame.apply(f, axis="column")
```

**Comment by MarcoGorelli** [comment]
you can pass `"columns"` already, see https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html

closing for now, but let me know if this doesn't work and I'll reopen
