### ISSUE TITLE
Rank by multiple columns

### ISSUE THREAD

**Issue by hayd** [pandas-dev/pandas#4311]
I don't _think_ this is possible atm, but would be a nice enhancement.

Similar to how you can pass list of columns to sort*.

http://stackoverflow.com/questions/17775935/sql-like-window-functions-in-pandas-row-numbering-in-python-pandas-dataframe

_\_probably there is a cheeky answer/hack to this q using sort...*

**Comment by imre-kerr** [comment]
This was possible until 0.23, but is semi-broken currently. (Understandable since I guess it's a bit of a hack.)
```python
df['rankby'] = pd.Series(df[['foo', 'bar']].itertuples(index=False)).values
df['ranking'] = inner.groupby('quux')['rankby'].rank(method='min')
```
Still works if you don't have a groupby.

**Comment by WillAyd** [comment]
@imre-kerr this is a pretty old issue that in the current iteration of pandas mixes a few concepts. If you want row-numbering within a group you should use cumcount:

https://stackoverflow.com/questions/37997668/pandas-number-rows-within-group

The behavior you are referring to of using rank would work if dealing only with numeric data. Rank within GroupBy operations on strings will raise an error, and should in the future raise also when called from a Series / Frame (see #19560)

**Comment by WillAyd** [comment]
Closing as this issue is no longer relevant - rank can be used on numeric data in combination with groupby. For object data cumcount can be used, though it would be up to the user to specify the desired order first

**Comment by oulenz** [comment]
@WillAyd `cumcount` isn't a proper substitute, since it doesn't take a `method` parameter. Also, it feels wrong that it requires sorting the whole dataframe when all you want is sorting within groups (even if in practice it doesn't make much difference in terms of performance).
