### ISSUE TITLE
TYP: annotate matching dtypes

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#43113]
e.g. in `Index._get_fill_indexer` we can work out that `target.dtype` should match `self.dtype`.  It would be nice if we could get that into the annotation.  cc @simonjayhawkins

```
# current
def _get_fill_indexer(self, target: Index, ...):

# desired?
def _get_fill_indexer(self: Index[MyDtype], target: Index[MyDtype], ...):
```

**Comment by simonjayhawkins** [comment]
Need to make Index Generic w.r.t. to Dtype. https://mypy.readthedocs.io/en/stable/generics.html#defining-generic-classes
