### ISSUE TITLE
QST: How to add option "-fstack-protector-all" when build lib_lightgbm.so?

### ISSUE THREAD

**Issue by liyuan1062** [pandas-dev/pandas#43126]
### 

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

NA

### Question about pandas

linux env, how to build lib_lightgbm.so with "-fstack-protector-all" option?

**Comment by MarcoGorelli** [comment]
closing as this doesn't seem related to pandas
