### ISSUE TITLE
DOC: Inconsistent use of "column-wise" and "row-wise"

### ISSUE THREAD

**Issue by ianozsvald** [pandas-dev/pandas#43128]
5 Pandas docstrings discuss the `axis` argument with one use of `row/column-wise`, 2 docstrings use an opposite meaning (and possibly more examples exist, I picked these up using Google & DuckDuckGo).

I believe the first 5 usages are in agreement with the Numpy usage. 

Examples of `axis: Equals 0 or ‘index’ for row-wise, 1 or ‘columns’ for column-wise` (i.e. 0 is row-wise):
* https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.quantile.html
* https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.swaplevel.html
* https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.idxmin.html
* https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.idxmax.html
* https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.nunique.html

Examples of `The axis to use. 0 or ‘index’ to compute column-wise, 1 or ‘columns’ for row-wise` (i.e. 0 is column-wise):
* https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.corrwith.html
* https://pandas.pydata.org/pandas-docs/version/0.24.2/reference/api/pandas.Series.all.html

For `Series.all` the examples down the page note `Default behaviour (i.e. axis=0) checks if column-wise values all return True.` and `Specify axis='columns' (or axis=1) to check if row-wise values all return True.`.

On Numpy I can't find many examples, the few that I find are consistent with the first (5 case) usage:
* https://numpy.org/doc/stable/reference/generated/numpy.hsplit.html#numpy.hsplit `horizontally (column-wise)...equivalent to split with axis=1`
* https://numpy.org/doc/stable/reference/generated/numpy.vsplit.html#numpy.vsplit `vertically (row-wise)... equivalent to split with axis=0 (default)`

#### Suggested fix for documentation

I _think_ that the 2 opposing cases (`corrwith` and `Series.all`) don't need to have the inverted explanation so I _think_ that reversing them to fit the general case makes sense, but maybe I'm missing something?

**Comment by mattharrison** [comment]
On a semi-related note (since this isn't the `axis` parameter), the behavior of the `normalize` parameter for `pd.crosstab` also accepts `'columns'` or `'index'`. When you pass `'columns'`, it doesn't normalize across the columns, but down each one. I understand the behavior, but it seems inconsistent. 🤷‍♀️😢

**Comment by jackgoldsmith4** [comment]
take
