### ISSUE TITLE
BUG: timeseries.groupby(...).transform('mean') wrong when aggregating over pd.NaT

### ISSUE THREAD

**Issue by behrenhoff** [pandas-dev/pandas#43132]
#### Code Sample, a copy-pastable example

The problem is best shown in the following example:

```python
import pandas as pd
s = pd.Series(['1 day', '3 days', pd.NaT], dtype='timedelta64[ns]')

print(f'{s.mean()=}\n')
# as expected: result is '2 days'

print(f"{s.apply('mean')=}\n")
# as expected: result is '2 days'

print("transform('mean')")
print(s.groupby([1,1,1]).transform('mean'))
# whoops: (a series of 3x) -35583 days +08:04:14.381741568
# expectation was: (a series of 3x) '2 days'

# Fixing the problem
print("\ntransform(pd.Series.mean)")
print(s.groupby([1,1,1]).transform(pd.Series.mean))
# (a series of 3x) '2 days', sanity restored :-)
```

#### Problem description

When passing a function name by string to `transform`, pd.NaT is not handled correctly. This not only happens for 'mean' but also for other functions like 'sum'.

I don't know how transform is looking up the function if a string is passed (and it's not really documented), but it certainly doesn't select pd.Series.mean but some other non-NaT-aware mean function.

This is surprising since NaT is handled correctly when calling `apply('mean')`.

Tested with pd 1.3.2.

**Comment by AlexeyGy** [comment]
Can I work on this issue?

**Comment by simonjayhawkins** [comment]
Thanks @AlexeyGy for exploring this issue further.

> * Are there any plans to harmonize both paths? It would surely be easy to just make 'mean' take the same route as pd.Series.mean.

refactoring, de-duplication, cleaning and maintaining api consistency is an ongoing process, but that may not be the best option if we wanted to backport any fixes to 1.3.x unless we limited the dispatch from `groupby.mean`  to `DatetimeLikeArrayMixin.mean` @jbrockmendel?

> * To mitigate, we could modify [`_resolve_numeric_only`](https://github.com/pandas-dev/pandas/blob/cf791c880c9506cbd3b5962063e81aa5354ef382/pandas/core/groupby/groupby.py#L1102) to return True if there are any NaN values in an otherwise numeric set.

There has been much discussion in #42395 and #43154 about changes to `_resolve_numeric_only` so I think further changes there is likely not desirable.

There is also the case that the 1.2.x behavior was incorrect and that the new behavior is a new bug and not a regression. But personally I would prefer to see 1.3.x patched to fix this.

#42659 is clearly a regression and it may well be that a fix for that case fixes this one too.

**Comment by jbrockmendel** [comment]
The correct long-term solution is for libgroupby.group_mean to take a `is_datetimelike` keyword like many of the other functions there do.

@AlexeyGy any interest in implementing this?

**Comment by AlexeyGy** [comment]
Yes, happy to help. Should not be a problem since I can peek at the other implementations in [the file](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/groupby.pyx#L674).

Awesome that there are even tests for both, [libgroupby](https://github.com/pandas-dev/pandas/blob/d0e20a01c77e6f894559fb9a7431ae947dbfb69a/pandas/tests/groupby/test_libgroupby.py), and [groupby](https://github.com/pandas-dev/pandas/blob/8fb6164c292f9d397c76fb1f3c34d2647996a855/pandas/tests/groupby/test_grouping.py) already which I can extend.

**Comment by AlexeyGy** [comment]
I've drafted up #43467. Will want to add a couple more tests to ensure that nothing is breaking but want to share it out early. Open for feedback on it.
