### ISSUE TITLE
BUG: Exactly same if check multiple times

### ISSUE THREAD

**Issue by debnathshoham** [pandas-dev/pandas#43139]
Hi, I came across the below while working on another bug.

https://github.com/pandas-dev/pandas/blob/e8f359348a601f303e19dc33fc66f0b602efce50/pandas/core/groupby/groupby.py#L2445-L2450

**Comment by phofl** [comment]
This is not the same or am I missing something?

**Comment by debnathshoham** [comment]
My bad. Misread it.
