### ISSUE TITLE
ENH: Add 'ascending' parameter to series/searchsorted() method.

### ISSUE THREAD

**Issue by KiranHipparagi** [pandas-dev/pandas#43162]
Hello,

i tried using [pandas.Series.searchsorted](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.searchsorted.html) method in series.

**Example-1** 
```
input:
import pandas as pd
ser_order = pd.Series([1, 1, 2,3,4])
ser_order.searchsorted([2,3])

output:
array([2,3]) #correct result.
```

**Example-2** 
```
input:
import pandas as pd
ser_order = pd.Series([2, 2,3,5,6,3,1])
ser_order.searchsorted([2,4])

output:
array([0,3]) #wrong result.
```
So  above two example clearly shows that [pandas.Series.searchsorted](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.searchsorted.html) will work only for ordered array.if we could add parameter **ascending**,then we can resolve this issue.

Thanks

**Comment by phofl** [comment]
This is documented and follows the numpy behavior, -1 on this

**Comment by KiranHipparagi** [comment]
@phofl yes,Thanks for your response. Even in numpy also the same situation.so what i was thinking we can add parameter called **ascending** to sort array and fix this issue.what you think?please comment.

**Comment by phofl** [comment]
This is not an issue. The function is called searchsorted, which already implies that the underlying object is sorted.

**Comment by mroeschke** [comment]
Thanks for the suggestion, but agreed that it is better for the pandas to strictly align with numpy so I'm -1 as well. Closing since this feature hasn't gotten enough acceptance from the team.
