### ISSUE TITLE
How to make pandas-stubs library compliant with pandas development team requirements

### ISSUE THREAD

**Issue by zkrolikowski-vl** [pandas-dev/pandas#43197]
Hello,

my name is Zbigniew Królikowski. I am a software developer at VirtusLab.

Together with my colleagues we started working on our own [pandas type stubs library](https://github.com/VirtusLab/pandas-stubs), and at some point decided to make it open-source.

We wanted to ask you:
1. Is the separation between our library and pandas itself clear? We wanted to be clear on the authorship so we added a [disclaimer](https://github.com/VirtusLab/pandas-stubs).
2. Do you see any issues with how we promote our library, especially in terms of our graphics?

We'd be very grateful to hear your thoughts on this.

Best regards,
Zbigniew Królikowski

**Comment by MarcoGorelli** [comment]
Hey @zkrolikowski-vl - my personal opinion is that the separation is clear enough, curious to see what others think though

cc @datapythonista (as I think I've seen you comment on issues surrounding other libraries / authorship / licensing before)

One thing you might want to be aware of is that there are aspirational plans to eventually expose pandas types from this repo

**Comment by datapythonista** [comment]
Thanks for sharing @zkrolikowski-vl 

Couple of things. Where did you get the disclaimer information from? Feels outdated, I guess we've got it outdated somewhere. The brand and logo "belong" to NumFOCUS. Not sure about the copyright of the code. We've got a section in the website about the logo and how to cite pandas, I think we could add information for your case there, and how to refer to pandas for third-party projects.

In any case, from your side the way you present your project looks perfect.

Second thing, did you add your project to our ecosystem page? That would be very helpful. Unfortunately we've got two ecosystem pages, one in the website, and the same in the docs (which aren't problably in sync anymore). You may want to add it to both.

@simonjayhawkins for you to be aware, and in case you've got any feedback.

**Comment by simonjayhawkins** [comment]
> One thing you might want to be aware of is that there are aspirational plans to eventually expose pandas types from this repo

see #28142 for discussion.

**Comment by zkrolikowski-vl** [comment]
@MarcoGorelli @datapythonista Thank you for responding so quickly and taking an interest in our project.

We've taken the copyright owners from the [pandas license](https://github.com/pandas-dev/pandas/blob/master/LICENSE) but now I see that the opensource contributors should also be included.

As for the logo we assumed the owner based on the [wikimedia page](https://commons.wikimedia.org/wiki/File:Pandas_mark.svg) - it mentions the same/outdated BSD license. For the sake of correctness we can just remove the first sentence about ownership as it's pretty much implied.

As for the [ecosystem page](https://github.com/pandas-dev/pandas/blob/master/doc/source/ecosystem.rst) I didn't know it exists. Now that I do I'll open a PR to the repository if that's the way to go. I wasn't able to find any disclaimers like ours in any of the linked projects.

As for the [#28142 ](https://github.com/pandas-dev/pandas/issues/28142) we're aware of the plans and that at some point pandas will have complete/semi-complete annotations and that you'll add `py.typed` so that information will be included in the pandas package. We're ok with our library becoming obsolete at some point. We hope that its contents will be helpful when annotating pandas.

**Comment by zkrolikowski-vl** [comment]
@datapythonista I've prepared a PR with an update to the ecosystem: https://github.com/pandas-dev/pandas/pull/43207
