### ISSUE TITLE
Combination of groupby with dropna set to True and apply function not returning expected output

### ISSUE THREAD

**Issue by deponovo** [pandas-dev/pandas#43205]
(Using pandas 1.3.1 and numpy 1.20.3)

This is a repetition of the SO question found [here](https://stackoverflow.com/questions/68918019/pandas-groupby-with-dropna-set-to-true/68918101?noredirect=1#comment121798992_68918101). (I did not have this issue previously when working with version 1.1.3).

In the following snippet:
```
import pandas as pd
import numpy as np

df = pd.DataFrame(
    {
        "a": [1, 2, 3, 4, 5, 6, 7, 8, 9], 
        "b": [1, np.nan, 1, np.nan, 2, 1, 2, np.nan, 1]
    }
)
df_again = df.groupby("b", dropna=False).apply(lambda x: x)
```
I was expecting df and df_again to be identical. But they are not:
```
df
   a    b
0  1  1.0
1  2  NaN
2  3  1.0
3  4  NaN
4  5  2.0
5  6  1.0
6  7  2.0
7  8  NaN
8  9  1.0

df_again
   a    b
0  1  1.0
2  3  1.0
4  5  2.0
5  6  1.0
6  7  2.0
8  9  1.0
```

Now, if I tweak slightly the lambda expression slightly to "see" what is going on by `df.groupby("b", dropna=False).apply(lambda x: print(x))` I can actually visualize that also the portion of the `df` where `b` was `NaN` was processed.

**Comment by simonjayhawkins** [comment]
Thanks @deponovo for the report

first bad commit: [03e58585036c83ca3d4c86d7d3d7ede955c15130] BUG: groupby.apply on the NaN group drops values with original axes return (#38257) cc @GYHHAHA
