### ISSUE TITLE
BUG: to_frame and transpose called on a series don't maintain dtype

### ISSUE THREAD

**Issue by momomorphism** [pandas-dev/pandas#43204]
- [ O] I have checked that this issue has not already been reported.

- [ O ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

```python
import pandas as pd

series_index = ["a", "b", "c"]
series_data = [1.0, 0, "X"]

series = pd.Series(index=series_index, data=series_data)

df_from_series = series.to_frame().T

print(df_from_series["a"].dtype)
# >> dtype('O')

df_from_constructor = pd.DataFrame(columns=series.index, data=[series.values])

print(df_from_constructor["a"].dtype)
# >> dtype('float64')
```

#### Problem description

When converting a series to a single row dataframe, dtypes are not maintained. This cause a problem when a subsequent groupby with sum is called, which dropped the now non-numeric column. 

Above behaviour is inconsistent to the resulting dataframe initialized from the DataFrame constructor with the series index and values attribute passed.

Above behaviour has not been observed in previous versions and I can see some transpose() related changes in the release-notes.

#### Output of ``pd.show_versions()``

<details>

Can neither log into github from my corporate machine nor send the version information out without getting compliance issues, but pandas is 1.3.2

</details>

**Comment by PatelDaksh** [comment]
Hey , I saw the bug reported by you , Can I work on that ?

**Comment by momomorphism** [comment]
Yes, that would be awesome. If you can’t reproduce it I can guve more
details on version, I just couldn’t cooy past the whole thing.

**Comment by phofl** [comment]
Acutally I do think this is correct. Your Series has dtype object. If you transpose it every target column has dtype object, not float. e.g. the dtype is maintained. When creating a df via the constructor, the dtpye inference is done per column, causing float in a and b and object in c

**Comment by simonjayhawkins** [comment]
> Above behaviour has not been observed in previous versions and I can see some transpose() related changes in the release-notes.

does not appear to be a recent change, checked back to 0.25.3


> Acutally I do think this is correct. Your Series has dtype object. If you transpose it every target column has dtype object, not float. e.g. the dtype is maintained. When creating a df via the constructor, the dtpye inference is done per column, causing float in a and b and object in c

agreed. closing. can reopen if we are missing something.
