### ISSUE TITLE
TYP: Type hints in merge incorrect for ``on`` 

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#43215]
The type hints for merge 
```
    on: IndexLabel | None = None,
    left_on: IndexLabel | None = None,
    right_on: IndexLabel | None = None,
```

imply that we pass keys here. 

We have tests, which pass arrays as on argument, for example

``test_handle_join_key_pass_array``

Not sure if this is tested well...

related: #42844

**Comment by twoertwein** [comment]
I think this issue can be closed `pd.merge` uses `IndexLabel | AnyArrayLike | None` on main:

https://github.com/pandas-dev/pandas/blob/b111ac671e9eb8119e53ca57be54d24c47f672f8/pandas/core/reshape/merge.py#L142

(pandas-stubs also has a few tests for `on*` with arrays: https://github.com/pandas-dev/pandas-stubs/blob/072997b077ad4f766272e9bb2d03fc3771829270/tests/test_merge.py#L10 )
