### ISSUE TITLE
ENH: Add .sem() to .describe()

### ISSUE THREAD

**Issue by Karim-53** [pandas-dev/pandas#43234]
Hi,
The standard error of the mean is quite an interesting statistic. But many didn't hear about it.
It would be nice to add it to ``.describe()`` hoping that people would ask themself about the difference between ``.sem()`` and ``.std()``

```python
series = pd.Series([1,2,3,4])
print(series.sem())
print(series.describe())
```

If many people like the idea then I would create a PR to add this feature :)

**Comment by mroeschke** [comment]
Thanks for the suggestion. While a useful statistic, I would be -1 on changing the API result of describe just to include sem. Could use additional input from other members of the core team.

**Comment by mroeschke** [comment]
Thanks for the suggestion but it appears there hasn't been much interest in this feature from the core devs & community over the years so closing. Happy to reopen if there's renewed interest
