### ISSUE TITLE
DEPR: squeeze() argument in read_csv/read_table

### ISSUE THREAD

**Issue by lithomas1** [pandas-dev/pandas#43242]
I'm pretty sure you can do this directly with a .squeeze() afterwards. 
The code does look pretty similar
squeeze()

https://github.com/pandas-dev/pandas/blob/5f648bf1706dd75a9ca0d29f26eadfbb595fe52b/pandas/core/generic.py#L979-L985

vs

read_csv(squeeze=True)

https://github.com/pandas-dev/pandas/blob/15302106ef41e562d2f80c6d1ecffdd4aea7158a/pandas/io/parsers/readers.py#L1063-L1064

**Comment by lithomas1** [comment]
This should also be deprecated in read_excel, and ExcelFile.parse too. 
cc @rhshadrach

**Comment by rhshadrach** [comment]
+1 on deprecating squeeze for read_excel
