### ISSUE TITLE
iterrows does not preserve dtypes

### ISSUE THREAD

**Issue by George3d6** [pandas-dev/pandas#43245]
#### Is your feature request related to a problem?

I wish I could use pandas in a way that does not cause bug-hunting for hours to look for a specific spot where nonsensical behavior occurs.

#### Describe the solution you'd like

The iterrow function (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iterrows.html) and a few other ways of access do not preserve data types, this is very counterintuitive behavior (unless reading the docs, and making a comment about it for the next guy that maintain the code to see).

Fixing this would involve making sure they return the correct types *and* potentially adding a `breaking_iterrow` function that can be used for more efficient type-unaware iteration.

#### API breaking implications

Would involve changing the behavior of iterrows, might break a few pieces of code that rely upon the arbitrary types this generates (likely without the author realizing)

#### Describe alternatives you've considered

Leaving comments every time I use pandas iterrows.

**Comment by kwhkim** [comment]
It seems that `iterrow` is misleadning. How about `iterseries` or so. Naming is hard! I've been using `iterrow` but was not unaware of this problem.. :(

**Comment by phofl** [comment]
-1 on this

One column of a DataFrame is often viewed as a Series, this would be really confusing. The disadvantages of iterrows are clearly documented and an alternative is provided.

**Comment by kwhkim** [comment]
Sure. I understand what you mean. But One column of a DataFrame is naturally a Series, and one row of most DataFrames can not be a series without converting dtype. There could another options like `iterseries(axis=0)` or `iterseries(axis=1)`.

**Comment by phofl** [comment]
If you do not want to change the dtype, just use itertuples

**Comment by jreback** [comment]
there are already too many iteration methods 

-1 on any change

**Comment by kwhkim** [comment]
Thanks. but not quite the point though. I am talking about bad naming :(

**Comment by mroeschke** [comment]
Thanks for the report, but since this hasn't gained much traction from other member of the core team, closing

**Comment by dclong** [comment]
I personally think `iterrows` should either be deprecated or renamed.
