### ISSUE TITLE
Reading from mongodb (BSON)

### ISSUE THREAD

**Issue by hayd** [pandas-dev/pandas#4329]
Now we have a neat read_json function (#3804), it'd be really neat if we could read in from mongo using this i.e. without have to create an intermediary python object.

_I wasn't even sure how to return a json (bson) string from a mongo query, though surely this ought to be relatively easy..._

I've no idea how much of an issue the BSON parts are, or whether these can be converted after the fact...

http://stackoverflow.com/questions/17805304/how-can-i-load-data-from-mongodb-collection-into-pandas-dataframe

**Comment by femtotrader** [comment]
Any news about this ?

**Comment by lJoublanc** [comment]
@femtotrader was about to suggest you look at arctic as it has BSON (de)serialization into pandas frames implemented, but I see from your profile you already seem to be using it. Does that implementation serve your purpose well?

**Comment by femtotrader** [comment]
Thanks @lJoublanc I'm giving a try to Arctic... I wondered if Monary wasn't more efficient... but road is not so straight than using Arctic https://bitbucket.org/djcbeach/monary/issues/19/use-pandas-series-dataframe-and-panel-with

**Comment by drafter250** [comment]
Does the bson_numpy project close this? http://bson-numpy.readthedocs.io/en/latest/#

**Comment by jreback** [comment]
is this a conda package / wheel?

**Comment by gfyoung** [comment]
Doesn't appear to be the case from the docs, but I *think* there is a `pip` package:

https://pypi.python.org/pypi/BSON-NumPy/0.1

**Comment by jreback** [comment]
source only are not very useful when a c library is needed

**Comment by gfyoung** [comment]
Ah, that's a good point.

**Comment by wesm** [comment]
Closing; this might be better addressed in an external package
