### ISSUE TITLE
BUG: pd.json_normalize() does not handle index while working with Series

### ISSUE THREAD

**Issue by tommasogallingani** [pandas-dev/pandas#43304]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
pd.json_normalize(test_data['mycol'])
import pandas as pd
test_data =  pd.DataFrame([[{'a':1,'b':4,'c':0}],[ {'a':10,'b':10,'c':10}],[{'a':0,'b':0,'c':0}]], index=[5,2,3], columns=['mycol'])
pd.json_normalize(test_data['mycol'])

	a	b	c
0	1	4	0
1	10	10	10
2	0	0	0

```

#### Problem description

When a Series is passed to json_normalize the function returns a re-indexed dataframe without taking into account the index passed through the Series. This beahaviour is absolutely unexpected while working with Series

#### Expected Output
```python
	a	b	c
5	1	4	0
2	10	10	10
3	0	0	0
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 3e89b4c4b1580aa890023fc550774e63d499da25
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Italian_Italy.1252

pandas           : 1.2.0
numpy            : 1.19.5
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 20.3.3
setuptools       : 51.1.2.post20210112
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.6 (dt dec pq3 ext lo64)
jinja2           : 3.0.1
IPython          : 7.26.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 0.8.5
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.3
numexpr          : None
odfpy            : None
openpyxl         : 3.0.6
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : 0.5.2
scipy            : 1.6.0
sqlalchemy       : 1.3.22
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
numba            : None

</details>

**Comment by phofl** [comment]
``data`` is supposed to be a list or a dict, not a Series. So this is expected.

on a related note: I am not able to find the docs after 1.2.5, can anybody double check please?

**Comment by asishm** [comment]
> on a related note: I am not able to find the docs after 1.2.5, can anybody double check please?

possibly xref #42540

**Comment by phofl** [comment]
Should have checked, thx

**Comment by mroeschke** [comment]
Closing as the expected behavior
