### ISSUE TITLE
BUG: groupby.std() casts to float64

### ISSUE THREAD

**Issue by debnathshoham** [pandas-dev/pandas#43330]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

This came out of https://github.com/pandas-dev/pandas/pull/43213#discussion_r699410411

#### Code Sample, a copy-pastable example

```python
In [1]: import pandas as pd

In [2]: pd.__version__
Out[2]: '1.4.0.dev0+532.g9bf09adcda'

In [3]: df=pd.DataFrame([[1,2]]*3, columns=["a","b"], dtype="Int64")

In [4]: df.groupby("a").std().dtypes
Out[4]: 
b    float64
dtype: object

In [5]: df=pd.DataFrame([[1,2]]*3, columns=["a","b"], dtype="Float64")

In [6]: df.groupby("a").std().dtypes
Out[6]: 
b    float64
dtype: object

```

#### Problem description

With `Float64` as input, should return `Float64` and not `float64`

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 9bf09adcdab1a5babaed9f3315f2572cebf9f1f2
python           : 3.8.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.4.0.dev0+532.g9bf09adcda
numpy            : 1.21.0
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.3
setuptools       : 49.6.0.post20210108
Cython           : 0.29.23
pytest           : 6.2.4
hypothesis       : 6.14.1
sphinx           : 3.5.4
blosc            : None
feather          : None
xlsxwriter       : 1.4.4
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.25.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 2021.05.0
fastparquet      : 0.6.3
gcsfs            : 2021.05.0
matplotlib       : 3.4.2
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : 4.0.1
pyxlsb           : 1.0.8
s3fs             : 0.4.2
scipy            : 1.7.0
sqlalchemy       : 1.4.20
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : 0.18.2
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.53.1

</details>

**Comment by phofl** [comment]
See #37494

**Comment by phofl** [comment]
Does this happen also with other functions except var? I think this is on purpose for std and var

**Comment by debnathshoham** [comment]
var is working as expected..

```python

In [4]: df=pd.DataFrame([[1,2]]*3, columns=["a","b"], dtype="Int64")

In [5]: df.groupby("a").var().dtypes
Out[5]: 
b    Float64
dtype: object

In [6]: df=pd.DataFrame([[1,2]]*3, columns=["a","b"], dtype="float32")

In [7]: df.groupby("a").var().dtypes
Out[7]: 
b    float32
dtype: object
