### ISSUE TITLE
CLN: Remove Sphinx Warnings from DocBuild

### ISSUE THREAD

**Issue by alimcmaster1** [pandas-dev/pandas#43348]
```
/home/runner/work/pandas/pandas/doc/source/conf.py:524: RemovedInSphinx50Warning: rpartition() is now deprecated.
  modname, accessor = rpartition(mod_cls, ".")
```

eg. https://github.com/pandas-dev/pandas/pull/43145/checks?check_run_id=3479105382

Deprecated in 5.0 https://www.sphinx-doc.org/en/master/extdev/deprecated.html

**Comment by souravsingh** [comment]
@alimcmaster1 I am interested in taking the issue.

**Comment by bodevone** [comment]
take
