### ISSUE TITLE
BUG: datetimelike index and column with name same as year in index

### ISSUE THREAD

**Issue by Dominioncher** [pandas-dev/pandas#43345]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas as pd

dates = ['2019-01-01', '2020-01-01']
frame = pd.DataFrame(index=pd.to_datetime(dates))
frame['2020'] = 0
print(frame['2020'])

```

#### Problem description

I can create any column with any names but when i try create column with name like year in my indexes it return DataFrame expect Series

#### Expected Output
2019-01-01    0
2020-01-01    0
Name: 2020, dtype: int64
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 5f648bf1706dd75a9ca0d29f26eadfbb595fe52b
python           : 3.8.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Russian_Russia.1251

pandas           : 1.3.2
numpy            : 1.21.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 20.2.3
setuptools       : 56.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
None

</details>

**Comment by phofl** [comment]
Hi,

the logic is as follows for datetime like objects:

1. Check if we are a column -> No
2. Look if we are in the index -> Yes
3. Add new column -> don't arrive here
