### ISSUE TITLE
DOC: Default engine incorrect for ExcelWriter and xlsx

### ISSUE THREAD

**Issue by jseabold** [pandas-dev/pandas#43359]
### 

- [X] I have checked that the issue still exists on the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.ExcelWriter.html#pandas.ExcelWriter

### Documentation problem

Unless, I'm missing something I don't think openpyxl is the default for writing xlsx files.

```python
In [1014]: pd.ExcelWriter("foo.xlsx").engine
Out[1014]: 'xlsxwriter'

In [1015]: pd.ExcelWriter("foo.xlsx", engine="openpyxl").engine
Out[1015]: 'openpyxl'
``` 

### Suggested fix for documentation

Change the default to xlsxwriter in the docstring. Happy to submit a PR, if I'm correct.

**Comment by phofl** [comment]
Yeah this is incorrect. You can put up a pr if you like

**Comment by LiquidMika** [comment]
Hello,

I would like to take care of this issue. Let me know whether it's possible.

Thanks.

Michael

**Comment by LiquidMika** [comment]
take

**Comment by LiquidMika** [comment]
Hi,

I've modified the ExcelWriter docstring in the file "pandas/io/excel/_base.py".
When I launch the script/validate_docstrings.py on the pandas.ExcelWriter, my modifications are not taken into account. Any idea why ?

Thanks.

Michael

**Comment by phofl** [comment]
In what sense are they not taken into account?

**Comment by LiquidMika** [comment]
I can even delete the all pandas folder except the script folder and the script/validate_docstrings.py still output some docstrings. It looks like it parses an hidden copy of sources...
