### ISSUE TITLE
CI Set pre-commit autoupdate to run monthly instead of weekly

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#43364]
most of the packages' new release don't affect pandas code - can we change the cron schedule to be monthly instead of weekly? 

https://github.com/pandas-dev/pandas/blob/58059c152ccf8a714eb3233f13ed22987eb42b44/.github/workflows/autoupdate-pre-commit-config.yml#L5

Feel free to open a pull request if you know how to do this, no need to ask if you can work on it

**Comment by 1nF0rmed** [comment]
take

**Comment by 1nF0rmed** [comment]
I would assume that this will run the `1st` of every month. If not, when should this run every month?

**Comment by MarcoGorelli** [comment]
1st is fine

**Comment by normyp** [comment]
take

**Comment by 1nF0rmed** [comment]
Sorry, @normyp I didn't notice that you had created a PR for the issue I picked up ;-;

**Comment by normyp** [comment]
@1nF0rmed no problem! :)
