### ISSUE TITLE
DOC: wrong example in comparison with spreadsheets

### ISSUE THREAD

**Issue by solopython** [pandas-dev/pandas#43361]
### 

- [X] I have checked that the issue still exists on the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_spreadsheets.html

### Documentation problem

In [38]: firstlast["Last_Name"] = firstlast["String"].str.rsplit(" ", expand=True)[**0**]

### Suggested fix for documentation

In [38]: firstlast["Last_Name"] = firstlast["String"].str.rsplit(" ", expand=True)[**1**]

**Comment by mzeitlin11** [comment]
Thanks for noting this @solopython! Would you be interested in putting up a pr to fix this?

**Comment by Digres45** [comment]
take
