### ISSUE TITLE
BUG: DataFrame.drop does not work with MultiIndex dataframes

### ISSUE THREAD

**Issue by imahdimir** [pandas-dev/pandas#43398]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here

```

#### Problem description

[this should explain **why** the current behavior is a problem and why the expected output is a better solution]

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by simonjayhawkins** [comment]
@imahdimir can you fill out the bug report template.

**Comment by mzeitlin11** [comment]
Closing for now, please ping to reopen if you fill out the template
