### ISSUE TITLE
pd.date_range function not returns right bound when start=end and closed set to 'right'

### ISSUE THREAD

**Issue by lzy1g1225** [pandas-dev/pandas#43394]
```python
pd.date_range(start='2021-09-02', end='2021-09-02', freq='D', closed=None)
pd.date_range(start='2021-09-02', end='2021-09-02', freq='D', closed='right')

```

#### Problem description
the first line returns 2021-09-02
but the second line returns empty( this is incorrect )

#### Expected Output
I think if we set closed to 'right', then the date range should still returns 2021-09-02, because start date equals end date and we want the end date, the formula would looks like (2021-09-02,  2021-09-02], right date should be picked instead of returns empty

**Comment by attack68** [comment]
link to #40245
