### ISSUE TITLE
ENH: native sparse conversion from csc/csr scipy sparse matrix to DataFrame

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#4343]
http://stackoverflow.com/questions/17818783/populate-a-pandas-sparsedataframe-from-a-scipy-sparse-matrix

**Comment by kernc** [comment]
* https://stackoverflow.com/questions/31084942/pandas-sparse-dataframe-to-sparse-matrix-without-generating-a-dense-matrix-in-m
* https://stackoverflow.com/questions/33457626/huge-sparse-dataframe-to-scipy-sparse-matrix-without-dense-transform
* https://stackoverflow.com/questions/41152264/convert-pandas-sparsedataframe-to-scipy-sparse-csc-matrix
* https://stackoverflow.com/questions/37084032/how-do-i-create-a-scipy-sparse-matrix-from-a-pandas-dataframe
...

**Comment by jreback** [comment]
@kernc there *might* be some other sparse issues which are covered / dupes by this. If you find any pls ping on them.

**Comment by kernc** [comment]
Surprisingly, [no duplicates](https://github.com/pandas-dev/pandas/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20scipy%20label%3ASparse).
