### ISSUE TITLE
BUG: `groupby` on categorical columns creates unexisting combinations

### ISSUE THREAD

**Issue by Seon82** [pandas-dev/pandas#43448]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame(
    {
        "col1": [1, 1, 2, 2, 3, 3],
        "col2": ["a", "a", "b", "b", "c", "c"],
        "col3": [8, 8, 8, 8, 8, 8],
    }
)
df.col1 = df.col1.astype("category")
df.groupby(["col1", "col2"]).col3.first()
```

Output:
```
col1	col2	col3
1	a	8.0
1	b	NaN
1	c	NaN
2	a	NaN
2	b	8.0
2	c	NaN
3	a	NaN
3	b	NaN
3	c	8.0
```

### Issue Description

Combinations that don't exist in the original dataframe are created after the `groupby`, for instance: `col1=1 and col2='b'`.

### Expected Behavior

```python
import pandas as pd
df = pd.DataFrame(
    {
        "col1": [1, 1, 2, 2, 3, 3],
        "col2": ["a", "a", "b", "b", "c", "c"],
        "col3": [8, 8, 8, 8, 8, 8],
    }
)
df.groupby(["col1", "col2"]).col3.first()
```

Output when `col1` isn't a category:
```
col1	col2	col3
1	a	8
2	b	8
3	c	8
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 5f648bf1706dd75a9ca0d29f26eadfbb595fe52b
python           : 3.9.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.4.0-19041-Microsoft
Version          : #1151-Microsoft Thu Jul 22 21:05:00 PST 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.2
numpy            : 1.21.2
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 56.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.27.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 2021.08.1
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : 1.4.23
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by attack68** [comment]
I'm not sure where the offending code is but building indexes via vector products (or the need to do this) should always be avoided. It just explodes and crashes when using big data.

I confirm your issue on master

**Comment by jbrockmendel** [comment]
i think you might want the `observed` keyword

**Comment by Seon82** [comment]
> 
> 
> i think you might want the `observed` keyword

I somehow managed to miss that in the `groupby` documentation, thanks! Using `df.groupby(["col1", "col2"], observed=True)` does indeed solve my issue, which seems to in fact be a feature. 

Is there a specific reason for the interface to behave differently by default in the presence of categoricals?
