### ISSUE TITLE
CI: re-run failed tests

### ISSUE THREAD

**Issue by attack68** [pandas-dev/pandas#43462]
I can see there is the re-run tests that have failed in **some** of the sections of a PR review.

Some jobs, though, dont have the option to re-run in isolation. Is there a way of getting a button in github that re-runs just failed tests. I imagine this would improve the performance by avoiding recalculating the majority of the jobs which have already passed?

**Comment by mroeschke** [comment]
Is the similar in spirit to https://github.com/pandas-dev/pandas/issues/42307?

**Comment by attack68** [comment]
yeh thats a more technical question, did a search couldnt find/. thx
