### ISSUE TITLE
ENH: Add observed keyword to value_counts

### ISSUE THREAD

**Issue by jseabold** [pandas-dev/pandas#43498]
#### Is your feature request related to a problem?

If you do `value_counts` on a categorical there's no way to suppress unobserved categories.

#### Describe the solution you'd like

Add an observed keyword to value_counts.

#### API breaking implications

None, unless we want to revisit the default in light of #35967.

**Comment by usersblock** [comment]
Hello, is there a code sample you want to add to testing?

**Comment by jbrockmendel** [comment]
closing as duplicate of #46486 (even though this came first, there is more discussion there)
