### ISSUE TITLE
BUG: Assigning on new column replaces value on different data frame

### ISSUE THREAD

**Issue by matg19** [pandas-dev/pandas#43502]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
test = pd.DataFrame([1, 2, 3])

test_a = test

test_b = test

test_a['year'] = 1990

test_b['year'] = 2000

print(test_a)
```

### Issue Description

I am very surprised by this, I thought it might be some element sticking on the memory on an interactive session but it does the same if executing the script on a console.

Basically, if I duplicate a data frame and try to assign values at the same time that I create a column, if I do this in sequence the values in the first data frame are replaced by those assigned to the second data frame.

In the reproducible example this would print a data frame `test_a` with 2000s... while I assigned 1990s. I don't see how assigning a value in the second data frame could affect a different object...

### Expected Behavior

In the above code, `test_a['year']` should be filled with 1990, not 2000

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 5f648bf1706dd75a9ca0d29f26eadfbb595fe52b
python           : 3.8.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.11.0-7620-generic
Version          : #21~1626191760~21.04~55de9c3-Ubuntu SMP Tue Jul 20 22:18:55 UTC 
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.2
numpy            : 1.20.1
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.23
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.4.5
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : None
psycopg2         : 2.8.6 (dt dec pq3 ext lo64)
jinja2           : 2.11.3
IPython          : 7.22.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.1
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : 0.15.0
pyarrow          : 4.0.1
pyxlsb           : None
s3fs             : None
scipy            : 1.6.2
sqlalchemy       : 1.4.2
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : None
xlrd             : 1.2.0
xlwt             : None

</details>

**Comment by MarcoGorelli** [comment]
> I don't see how assigning a value in the second data frame could affect a different object...

It's not a different object:

```python
>>> import pandas as pd
>>> test = pd.DataFrame([1, 2, 3])
>>> 
>>> test_a = test
>>> 
>>> test_b = test
>>> id(test_a)
140420257519888
>>> id(test_b)
140420257519888
>>> id(test)
140420257519888

```

You probably want to use `DataFrame.copy`
