### ISSUE TITLE
DOC: Typo in `fillna()` documentation

### ISSUE THREAD

**Issue by cesare-spinoso** [pandas-dev/pandas#43522]
### 

- [X] I have checked that the issue still exists on the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html

### Documentation problem

Typo in one of the examples for `fillna()`. Specifically, the last example with `df2 = pd.DataFrame(np.zeros((4, 4)), columns=list("ABCE"))` where the last column should be `E` but is instead `D` in the printout.

### Suggested fix for documentation

Either fix to `df2 = pd.DataFrame(np.zeros((4, 4)), columns=list("ABCD"))` or fix the printout.

**Comment by MarcoGorelli** [comment]
I believe this is intentional, to show that you can fill with a DataFrame which has extra columns not present in the original one

**Comment by mzeitlin11** [comment]
Thanks for noting this @cesare-spinoso. I think this is not explicitly wrong - since column "E" does not match any column in `df1`, that column is essentially just ignored - and column "D" in `df1` is unaffected. 

However, since there are no missing values in column "D" in `df1`, this example could probably be improved to show it more explicitly

**Comment by mzeitlin11** [comment]
whoops sorry @MarcoGorelli just saw your comment

**Comment by cesare-spinoso** [comment]
Aha! Makes sense, maybe it's just me but that was easy to miss. Perhaps an extra line explaining just that could be useful? I'll leave it up to you.

**Comment by mzeitlin11** [comment]
Yeah I think an extra line could help - or adding a missing value to column "D" to make it more obvious that it is not being filled

**Comment by erfannariman** [comment]
take
