### ISSUE TITLE
BUG: read_csv() incorrectly parses data in case '\n' is used as a separator

### ISSUE THREAD

**Issue by romanov-o** [pandas-dev/pandas#43528]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd
import io

df = pd.read_csv(io.StringIO('A\nB\nC'), sep='\n', header=None, names=range(3))
```

### Issue Description

`pd.read_csv()` incorrectly parses data in case `'\n'` is used as a separator.

```python
df = pd.read_csv(io.StringIO('A\nB\nC'), sep='\n', header=None, names=range(3))
```
produces:
```
   0   1   2
0  A NaN NaN
1  B NaN NaN
2  C NaN NaN
```

### Expected Behavior

Expected:
```
   0   1   2
0  A   B   C
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 5f648bf1706dd75a9ca0d29f26eadfbb595fe52b
python           : 3.8.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.3.2
numpy            : 1.19.2
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : 0.29.24
pytest           : 6.2.5
hypothesis       : None
sphinx           : 4.1.2
blosc            : None
feather          : None
xlsxwriter       : 3.0.1
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.9.1 (dt dec pq3 ext lo64)
jinja2           : 3.0.1
IPython          : 7.27.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fsspec           : 2021.08.1
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.8
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.2
sqlalchemy       : 1.4.23
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.54.0

</details>

**Comment by leonarduschen** [comment]
How would it detect newlines though?

**Comment by phofl** [comment]
Yeah agreed. I think we should raise if ``\n`` is provided as separator.

**Comment by leonarduschen** [comment]
I'll go ahead and make a PR for that, should be a quick one

**Comment by leonarduschen** [comment]
Wait - I realized we have the parameter `lineterminator` - which is `\n` by default.

```python
import pandas as pd
import io

df = pd.read_csv(io.StringIO('A\nB\nC'), sep='\n', header=None, names=range(3), lineterminator='\r')
```
gives

```
   0  1  2
0  A  B  C
```

Maybe we raise when `sep` is the same as `lineterminator` ?

**Comment by phofl** [comment]
A separator with more than one character forces the python engine, which does not accept a lineterminator
