### ISSUE TITLE
BUG 1.3.3: pytest is failing when `pytest-randomly` pytest plugin is used

### ISSUE THREAD

**Issue by kloczek** [pandas-dev/pandas#43534]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
run pytest
```

### Issue Description

pytest is failing with `unrecognized arguments: --strict-data-files`
```console
+ /usr/bin/pytest -ra
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --strict-data-files
  inifile: /home/tkloczko/rpmbuild/BUILD/pandas-1.3.3/pyproject.toml
  rootdir: /home/tkloczko/rpmbuild/BUILD/pandas-1.3.3
```

### Expected Behavior

pytest should run test suite

### Installed Versions

N/A

**Comment by kloczek** [comment]
```consol
[tkloczko@barrel SPECS]$ pytest --version
pytest 6.2.5
```

**Comment by debnathshoham** [comment]
I think you should run `pytest pandas`
Refer [here](https://pandas.pydata.org/pandas-docs/stable/development/contributing_codebase.html#running-the-test-suite) for more details.

**Comment by kloczek** [comment]
With that hint it is a bit better but now I have 29 failed units.
Full log is in attachment.
[python-pandas_pytest.log.txt](https://github.com/pandas-dev/pandas/files/7150220/python-pandas_pytest.log.txt)

**Comment by MarcoGorelli** [comment]
These tests pass just fine

Please follow the [contributing guide](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html) for how to set up your environment

To avoid wasting time like in https://github.com/matplotlib/matplotlib/issues/20312, I'll quote their reply:

> I've now wasted more than enough time on basically confirming how Python import semantics work, so unless you can come up with some concrete reason why something is wrong, I'm not going to bother any further.

**Comment by kloczek** [comment]
> These tests pass just fine

Did you had a look on exect failing units messages?

> Please follow the [contributing guide](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html) for how to set up your environment

This ticket is not about contribution to the code.
This ticket is about fauiling test suite.

> To avoid wasting time like in [matplotlib/matplotlib#20312](https://github.com/matplotlib/matplotlib/issues/20312), I'll quote their reply:
> 
> > I've now wasted more than enough time on basically confirming how Python import semantics work, so unless you can come up with some concrete reason why something is wrong, I'm not going to bother any further.

In that case it was wrong testing methodology usuusing `python3 -Bm pytest`. It should be used pytest script because `python3 -Bm pytest` automatically adds to the `sys.path` upfront current directory. Byu this pytest was not testing what was installed in `</install/prefix>` but in current directory.

If you will look one more time in the attached log you will see that in fseconfd line is `/usr/bin/pytest -ra pandas`.
Between those two cases there is no any connections.

May I ask you to provide list of installed modules wqith version in your test env?

**Comment by kloczek** [comment]
Just rerun pytest and had completly different set of fails.
I'm using `pytest-randomly` pytest plugin.
Looks like `pandas` teest suite has some dependencies between test units and that plugin exposes that kind of issue.
With such dependencies running `pytest pandas <exac/file.py>` or `pytest pandas <exac/file.py>::><exact_unit>` may fail.
So it would be rally good to reopen that ticket ..

On diagnosing that kind of issue can be used https://github.com/mrbean-bremen/pytest-find-dependencies/

**Comment by MarcoGorelli** [comment]
> changed the title BUG 1.3.3: pytest is failing with unrecognized arguments: --strict-data-files BUG 1.3.3: pytest is failing when pytest-randomly pytest plugin is used

OK, now this is a more specific and actionable report, thanks - let's open a PR which uses pytest-randomly  and see what happens

**Comment by MarcoGorelli** [comment]
closing in favour of https://github.com/pandas-dev/pandas/issues/34373

If there's an issue other than pytest-randomly which pandas should be aware of, please do open a new issue - thanks!
