### ISSUE TITLE
Feature Request - New pd.set_option()  option: display.column_delimiter : str

### ISSUE THREAD

**Issue by marklewis3000** [pandas-dev/pandas#43554]
When I print a dataframe, which uses df.to_string(), I would like the ability to display it in CSV format with commas between the columns instead of spaces, like this:
```
Name,Age
Alex,10
Bob,12
Clarke,13
```
This might be done with a new string option 'display.column_delimiter' in pd.set_option().
pd.set_option('display.column_delimiter', ',')
```
import pandas as pd
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
###  pd.set_option('display.column_delimiter', ',')  ### Use comma instead of spaces
print(df.to_string(index=False))
```
Currently, the output uses spaces as below:
```
     Name  Age
    Alex   10
     Bob   12
  Clarke   13
```

**Comment by attack68** [comment]
As of master (v1.5.0) you can do with Styler.

``` python
>>> df = DataFrame({"Name": ["Alex", "Bob"], "Age": [10, 12]})
>>> print(df.style.hide().to_string(delimiter=","))
Name,Age
Alex,10
Bob,12
```

Any views on the further development of `Styler.to_string` welcome to submit.

**Comment by attack68** [comment]
closing since this is now possible
