### ISSUE TITLE
BUG: not correct work str.split

### ISSUE THREAD

**Issue by ilgrad** [pandas-dev/pandas#43563]
### 

- [ ] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame(columns=['url'])
df['url'] = ['https://qweqwe.com/2021-09-14/qweqwejpgqweqwe.jpg']
df['id'] = df['url'].str.split('/').str[-2].astype(str) + '_' + df['url'].str.split('/').str[-1].str.split('.jpg').str[0]
print(df['id'].iloc[0])
```

### Issue Description

output: 2021-09-14_qweqw
true output: 2021-09-14_qweqwejpgqweqwe

### Expected Behavior

2021-09-14_qweqwejpgqweqwe

### Installed Versions

python 3.9
pandas version 1.3.2

**Comment by debnathshoham** [comment]
I can confirm this on master, and I think should work given it works on `str.split`.
```python
In [23]: 'qweqwejpgqweqwe.jpg'.split(".jpg")[0]
Out[23]: 'qweqwejpgqweqwe'
```
For your case, you can add an escape character and it should work (`.jpg` -> `\.jpg`).
```python
In [1]: import pandas as pd
   ...: 
   ...: df = pd.DataFrame(columns=['url'])
   ...: df['url'] = ['https://qweqwe.com/2021-09-14/qweqwejpgqweqwe.jpg']
   ...: df['id'] = df['url'].str.split('/').str[-2].astype(str) + '_' + df['url'].str.split('/').str[-1].str.split('\.jpg').str[0]
   ...: print(df['id'].iloc[0])
   ...: 
2021-09-14_qweqwejpgqweqwe
```

**Comment by asishm** [comment]
maybe the documentation could be improved here, but with `.str.split` uses regex where `len(pat) > 1`

OR an enhancement to include a `regex=True` parameter as it exists for `str.replace`

https://github.com/pandas-dev/pandas/blob/0a9f9eed3e3eb7d5fa23cbc588e78b9bef915a89/pandas/core/strings/object_array.py#L311-L326

**Comment by asishm** [comment]
also see related : #37963

**Comment by mzeitlin11** [comment]
I like the idea of adding a `regex` arg since that would be consistent with `replace`. It feels arbitrary to choose whether or not to treat as a regex based on being a single character or not
