### ISSUE TITLE
ENH: Possible to add dtype/converters as arguments for pandas.read_xml() ?

### ISSUE THREAD

**Issue by soliujing** [pandas-dev/pandas#43567]
#### Is your feature request related to a problem?

I am using pandas lib to read xml for further processes, however a number of columns with leading ZERO are always converted to numbers, so I lost the original data.

#### Describe the solution you'd like

It would be great to add **dtype/converter** arguments for `pandas.read_xml()` to force pandas to interprete certain columns with given dtype/converters.
Just like similar IO read (read_csv, read_html, etc)

[read_xml](https://pandas.pydata.org/docs/reference/api/pandas.read_xml.html)
[read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)

#### API breaking implications

Probably not, this argument could be optional.

#### Describe alternatives you've considered

Write my own code to pull data by each xml nodes, which results in very bad performance.

**Comment by mzeitlin11** [comment]
Could maybe be added to #40131, cc @ParfaitG if any thoughts

**Comment by ParfaitG** [comment]
Agreed! Good feature to add to running list. Also, `read_xml` passes parsed data to [`TextParser`](https://github.com/pandas-dev/pandas/blob/6161f67d1d5886838fa968e42158e675ac987970/pandas/io/parsers/readers.py#L1185) shared by other io readers.

**Comment by ParfaitG** [comment]
As a current workaround, consider running XSLT to quote the nodes with leading zeroes and then convert on the pandas side. If using the default `lxml` parser, XSLT 1.0 scripts are supported in `read_xml`. Below XSLT runs the standard Identity Template and encloses the text values of the `zip` with double quotes.

```python
import pandas as pd

xml = \
'''<root>
     <row>
        <zip>08540</zip>
        <dat>123</dat>
     </row>
     <row>
        <zip>08628</zip>
        <dat>456</dat>
     </row>
     <row>
        <zip>27599</zip>
        <dat>789</dat>
     </row>
    </root>'''

xsl = \
'''<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output method="xml" omit-xml-declaration="no" indent="yes"/>
    <xsl:strip-space elements="*"/>

    <!-- IDENTITY TEMPLATE TO COPY XML AS IS -->
    <xsl:template match="node()|@*">
       <xsl:copy>
         <xsl:apply-templates select="node()|@*"/>
       </xsl:copy>
    </xsl:template>
    
    <!-- ENCLOSE zip NODES WITH DOUBLE QUOTES -->
    <xsl:template match="zip">
      <xsl:copy>
        <xsl:variable name="quot">"</xsl:variable>
        <xsl:value-of select="concat($quot, text(), $quot)"/>
      </xsl:copy>
    </xsl:template>
    
</xsl:stylesheet>'''

df = (
    pd.read_xml(xml, stylesheet = xsl)
      .assign(zip = lambda x: x["zip"].str.replace('"', ''))
)

df
     zip  dat
0  08540  123
1  08628  456
2  27599  789
```

**Comment by soliujing** [comment]
@ParfaitG xsl is really a good idea !
I have tried and have questions on namespace.
- actually the XML file i am processing contains namespace at root node, I am not very familar with xsl, so any suggestion for match & replace ?

I have done as below but cannot get any output..
```
xsl = \
'''<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:doc="http://sample.com/sample">
    <xsl:output method="xml" omit-xml-declaration="no" indent="yes"/>
    <xsl:strip-space elements="*"/>

    <!-- IDENTITY TEMPLATE TO COPY XML AS IS -->
    <xsl:template match="node()|@*">
       <xsl:copy>
         <xsl:apply-templates select="node()|@*"/>
       </xsl:copy>
    </xsl:template>
    
    <!-- ENCLOSE zip NODES WITH DOUBLE QUOTES -->
    <xsl:template match="doc:zip">
      <xsl:copy>
        <xsl:variable name="quot">"</xsl:variable>
        <xsl:value-of select="concat($quot, text(), $quot)"/>
      </xsl:copy>
    </xsl:template>
    
</xsl:stylesheet>'''
```

**Comment by ParfaitG** [comment]
Hmmmm...At the very least, you should get back the same XML with this XSLT. The identity transform should work across any XML with or without namespaces. I can understand the double quotes not rendering. Possibly, `doc:` is not the correct namespace for `<zip>` nodes. Please share sample of XML for reproducible example.
