### ISSUE TITLE
BUG: pivot_table produces NaT and FutureWarning on dataset with explicitly typed date-value field

### ISSUE THREAD

**Issue by felciano** [pandas-dev/pandas#43574]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd 
import numpy as np

df = pd.DataFrame([
    {'category': 'Books', 'date_str': '2021-01-01', 'amount': 10.00},
    {'category': 'Books', 'date_str': '2021-01-01', 'amount': 20.00},
    {'category': 'Books', 'date_str': '2021-01-03', 'amount': 50.00},
    {'category': 'Vacation', 'date_str': '2021-01-01', 'amount': 100.00},
    {'category': 'Vacation', 'date_str': '2021-01-01', 'amount': 200.00},
    {'category': 'Vacation', 'date_str': '2021-01-02', 'amount': 500.00},
])

df['date'] = pd.to_datetime(df['date_str'])

pivot = df.pivot_table(
    index = ["category", "date"],
    values = ["amount"],
    aggfunc = [np.sum],
    margins = True
)
```

### Issue Description

When executing the `pivot_table` function with `margins=True` on a dataset with dates that have been explicitly typed as `datetime`, a `FutureWarning` error is produced regarding inference of `datetime64[ns]`, and the pivot operation appears to try to aggregate the date-valued field, producing `NaT`.

```
<ipython-input-22-f8a00ede7c0c>:1: FutureWarning: Inferring datetime64[ns] from 
data containing strings is deprecated and will be removed in a future version. To 
retain the old behavior explicitly pass Series(data, dtype={value.dtype})
  pivot = df.pivot_table(
```
I'm not sure why this warning is triggered given that the `date` field is explicitly typed (no inference) and fully populated (no missing date values).

Here's what the pivot produces, with the `NaT` on the bottom row under the `date` column:
```
                       sum
                    amount
category date             
Books    2021-01-01   30.0
         2021-01-03   50.0
Vacation 2021-01-01  300.0
         2021-01-02  500.0
All      NaT         880.0
```

### Expected Behavior

Absent a clear semantic for summing up date-valued fields, I would expect the pivot operation to ignore that field when calculating totals as part of the `margins` behavior, and no `FutureWarning` to be produced.

The expected resulting table would look like (note absent 'NaT` on the bottom `All` line):
```
                       sum
                    amount
category date             
Books    2021-01-01   30.0
         2021-01-03   50.0
Vacation 2021-01-01  300.0
         2021-01-02  500.0
All                  880.0
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 73c68257545b5f8530b7044f56647bd2db92e2ba
python           : 3.8.11.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 21.1.2
setuptools       : 57.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.3.6
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.18.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.2
numexpr          : None
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.19
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : None
​

</details>

**Comment by felciano** [comment]
Hi @mroeschke thanks for reviewing this bug. Can you clarify the `missing-data` tag? Is there additional information I should have provided in the bug report itself?

**Comment by mroeschke** [comment]
`missing-data` refers to "null data and null data operations" in the issue tracker, so nothing lacking on your end. Thank you for a clear and concise bug report!

**Comment by VasilijKolomiets** [comment]
May be it is obviously, but better to say )

variant with last row pivoting like this


```
pivot =  pd.pivot_table(df,
    index = ["category", "date"],
    values = ["amount"],
    aggfunc = [np.sum], 
    margins = True
)
```
rise the same warning:

> FutureWarning: Inferring datetime64[ns] from data containing strings is deprecated and will be removed in a future version. To retain the old behavior explicitly pass Series(data, dtype=datetime64[ns])
  pivot = pd.pivot_table(df,

**Comment by jbrockmendel** [comment]
The output now matches what the user expects in the OP. Could use a test (or determine if one already exists)

**Comment by kvn4** [comment]
take
