### ISSUE TITLE
DOC: `pd.Categorical` has undocumented `fastpath`

### ISSUE THREAD

**Issue by david-cortes** [pandas-dev/pandas#43580]
### 

- [X] I have checked that the issue still exists on the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Categorical.html#pandas.Categorical

### Documentation problem

Argument `fastpath` is not documented.

### Suggested fix for documentation

All arguments to the function should be documented. `fastpath` is not currently documented even though it is part of the function signature.

**Comment by samukweku** [comment]
@david-cortes will you be contributing the docs? Would love to c scenarios where fast path can be used. Thanks

**Comment by david-cortes** [comment]
I'm not familiar with it, sorry.

**Comment by oli5679** [comment]
see [#20110](https://github.com/pandas-dev/pandas/issues/20110)

The plan is to remove this.
