### ISSUE TITLE
How to ensure monthly date ranges show month beginning dates instead of ending dates.

### ISSUE THREAD

**Issue by ajdse** [pandas-dev/pandas#43582]
I don't know if there is a way to generate a date range with month beginning dates instead of month ending. I know I could use time delta to modify the DatetimeIndex that I obtain below. However, I was wondering if there is some argument that can be passed while creating the date_range instance.

See below:
>>>pd.date_range(start='1/1/2018', end='08/08/2018',
freq='M')

DatetimeIndex(['2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30',
               '2018-05-31', '2018-06-30', '2018-07-31'],
              dtype='datetime64[ns]', freq='M')

**Comment by samukweku** [comment]
Maybe try MS for the freq

**Comment by MarcoGorelli** [comment]
Thanks @samukweku 

@ajdse please ask usage questions on StackOverflow in the future, thanks 👍
