### ISSUE TITLE
BUG: changed behavior of df.loc on multiindex since 1.3.0

### ISSUE THREAD

**Issue by auderson** [pandas-dev/pandas#43599]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

df = pd.DataFrame(index=pd.MultiIndex.from_product([list('ab'), list('cd'), list('e')]), columns=['Val'])

df.loc[np.s_[:,'c',:]]
```

### Issue Description

for versions later than 1.3, this selection will keep the second level in the index. But for versions earlier than 1.3, the 2nd level will be dropped:

![image](https://user-images.githubusercontent.com/48577571/133558540-8e3f367c-6a54-4fae-b59e-844bf1c0c9a9.png)

![image](https://user-images.githubusercontent.com/48577571/133558566-51d5de84-db81-48e0-a0cd-747f7cfe73c6.png)

![image](https://user-images.githubusercontent.com/48577571/133558586-a57a13e2-7651-42e1-af3e-ec574d464083.png)

### Expected Behavior

I've read the release notes of 1.3 but can't find a documentation about this. Is this a changed behavior?

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 7c48ff4409c622c582c56a5702373f726de08e96
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-156-generic
Version          : #163-Ubuntu SMP Thu Aug 19 23:31:58 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.5
numpy            : 1.20.3
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : 0.29.23
pytest           : 6.2.4
hypothesis       : None
sphinx           : 4.1.2
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.2
html5lib         : 1.1
pymysql          : 0.9.3
psycopg2         : 2.8.6 (dt dec pq3 ext lo64)
jinja2           : 3.0.1
IPython          : 7.27.0
pandas_datareader: 0.9.0
bs4              : 4.9.3
bottleneck       : None
fsspec           : 0.8.5
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : 4.0.1
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : 1.4.17
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
numba            : 0.54.0

INSTALLED VERSIONS
------------------
commit           : 73c68257545b5f8530b7044f56647bd2db92e2ba
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-156-generic
Version          : #163-Ubuntu SMP Thu Aug 19 23:31:58 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.3
numpy            : 1.20.3
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : 0.29.23
pytest           : 6.2.4
hypothesis       : None
sphinx           : 4.1.2
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.2
html5lib         : 1.1
pymysql          : 0.9.3
psycopg2         : 2.8.6 (dt dec pq3 ext lo64)
jinja2           : 3.0.1
IPython          : 7.27.0
pandas_datareader: 0.9.0
bs4              : 4.9.3
bottleneck       : None
fsspec           : 0.8.5
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : 4.0.1
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : 1.4.17
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
numba            : 0.54.0

</details>

**Comment by auderson** [comment]
![image](https://user-images.githubusercontent.com/48577571/133559083-070baae2-d580-4cad-b9bf-8d92a10c3347.png)

on both versions, if df is a series, the 2nd level will dropped

**Comment by attack68** [comment]
On master this works as previous
![Screen Shot 2021-09-19 at 21 53 07](https://user-images.githubusercontent.com/24256554/133941111-4fd612cc-d46e-458d-b254-205dd314c8f4.png)
:

**Comment by Ale-Cas** [comment]
Hello, I am a first-time contributor. Is the issue still open? 
I would like to work on it.

**Comment by ChrisAlbertsen** [comment]
@Ale-Cas 

From the looks of it the two prior PRs were closed due to inactivity, and no one else has been assigned the issue, so I think you can go ahead and work on it.
Looks like the latest of the two PRs got close to a working test, so you could take a look at it.

If you want the issue assigned to you try writing a single comment in here with the text "take" - this will make a bot assign the issue to you, letting other people know, that it is being worked on.

If you haven't read it from one end to another I'd suggest reading the "Contributing to pandas"-section. As a newbie I think its supportive :-)
https://pandas.pydata.org/docs/dev/development/contributing.html (you can also find a link in the repos landing page)

**Comment by rogimus** [comment]
take

**Comment by mroeschke** [comment]
Closed by https://github.com/pandas-dev/pandas/pull/46190
