### ISSUE TITLE
BUG: `DataFrame.sort_index` is not accounting for `ignore_index=True` for some cases

### ISSUE THREAD

**Issue by galipremsagar** [pandas-dev/pandas#43591]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
>>> import pandas as pd
>>> df = pd.DataFrame({'a': [1, 2, 3]})
>>> df.index = pd.RangeIndex(4, -1, -2)
>>> df
   a
4  1
2  2
0  3
>>> df.sort_index()
   a
0  3
2  2
4  1
>>> df.sort_index().index
Int64Index([0, 2, 4], dtype='int64')
>>> df.sort_index(ignore_index=True).index
RangeIndex(start=0, stop=3, step=1) #Index is being ignored.
>>> df.sort_index(ascending=False)
   a
4  1
2  2
0  3
>>> df.sort_index(ascending=False, ignore_index=True)
   a
4  1
2  2
0  3
>>> df.sort_index(ascending=False, ignore_index=True).index
RangeIndex(start=4, stop=-1, step=-2) # Index is not being ignored.
```

### Issue Description

In `DataFrame.sort_index`, looks like `ignore_index=True` is being adhered to only when there is a sorting taking place. This seems to be unexpected.

### Expected Behavior

The expected behavior for `ignore_index=True` is to always ignore the index irrespective of if there was a sorting performed or not.

### Installed Versions

<details>

>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : 73c68257545b5f8530b7044f56647bd2db92e2ba
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-76-generic
Version          : #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.3
numpy            : 1.21.2
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : 0.29.24
pytest           : 6.2.5
hypothesis       : 6.21.3
sphinx           : 4.2.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.27.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
fsspec           : 2021.08.1
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 5.0.0
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.53.1
>>> 

</details>

**Comment by mzeitlin11** [comment]
Thanks for reporting this @galipremsagar! Confirmed on master, looks like `ignore_index` is just ignored if the sort is a noop https://github.com/pandas-dev/pandas/blob/72a10906bfedad13208139f7847848d34a361acd/pandas/core/generic.py#L4578-L4582

Investigations to fix very welcome

**Comment by saehuihwang** [comment]
take
