### ISSUE TITLE
DOC: Chart visualisation, Colormaps links to old Matplotlib documentation

### ISSUE THREAD

**Issue by stelios-c** [pandas-dev/pandas#43624]
### 

- [X] I have checked that the issue still exists on the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/user_guide/visualization.html#colormaps

### Documentation problem

The first paragraph of the Colormaps section finishes with 

> A visualization of the default matplotlib colormaps is available [here](https://matplotlib.org/2.0.2/examples/color/colormaps_reference.html).

Following that URL gets you to a page with a red banner warning 

> You are reading an old version of the documentation (v2.0.2). For the latest version see https://matplotlib.org/stable/

### Suggested fix for documentation

Shouldn't the documentation point to the [stable color examples](https://matplotlib.org/stable/gallery/index.html#color)  or perhaps more appropriately to the [tutorial Choosing colormaps in Matplotlib](https://matplotlib.org/stable/tutorials/colors/colormaps.html#sphx-glr-tutorials-colors-colormaps-py)

**Comment by mzeitlin11** [comment]
Thanks for reporting this @stelios-c! Contributions to update this link are very welcome

**Comment by ricardobohadana** [comment]
Hi,
Can i have this issue? It is my first time contribuiting...

**Comment by ricardobohadana** [comment]
take
