### ISSUE TITLE
CI: codecov for pyx files

### ISSUE THREAD

**Issue by twoertwein** [pandas-dev/pandas#43652]
#### Is your feature request related to a problem?

cython supports [line coverage](https://cython.readthedocs.io/en/latest/src/tutorial/profiling_tutorial.html#enabling-coverage-analysis) but pyx files are currently not included in the codecov reports. Having code coverage for cython code might help to remove unused cython code.

#### Describe the solution you'd like

pyx files are included in the codecov report.

**Comment by twoertwein** [comment]
> xref #25600

If running cython with line coverage is much slower, having a nightly build as mentioned in the issue might be a better option. Happy to close this issue.

**Comment by jbrockmendel** [comment]
are we even still using codecov?

**Comment by twoertwein** [comment]
I don't see it run anymore.
