### ISSUE TITLE
BUG: Wrong result when inserting and sorting with groupby and apply 

### ISSUE THREAD

**Issue by ryangogogo36** [pandas-dev/pandas#43655]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd

'''
Create the following dataframe "df":
a  b
----
1  4
1  2
2  5
2  1
'''
df = pd.DataFrame({'a': [1, 1, 2, 2], 'b': [4, 2, 5, 1]})

def f(x):
    # Insert a new column "c" and sort each sub-dataframe "x" according to values in "c"
    x['c'] = x['b'].tolist()
    return x.sort_values('c')

df = df.groupby('a').apply(f).reset_index(drop=True)
'''
I got an unexpected dataframe "df":
a  b  c
-------
1  2  2
1  4  4
1  2  2
1  4  4
'''
```

### Issue Description

As shown in the reproducible example, when I use groupby and apply to insert a new column to the sub-dataframe of each group and sort the sub-dataframe according to the new column, I got a wrong result. 

It seems to me that the sub-dataframe of the first group was simply duplicated. I feel this is a bug, but please correct me if I am wrong. Thank you so much for your help! I would really appreciate it!

### Expected Behavior

The expected dataframe "df" should look like:
```python-traceback
a  b  c
-------
1  2  2
1  4  4
2  1  1
2  5  5
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.6.8.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
Version          : Darwin Kernel Version 18.7.0: Mon Aug 31 20:53:32 PDT 2020; root:xnu-4903.278.44~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8
pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.4
dateutil         : 2.8.1
pip              : 20.3.3
setuptools       : 51.0.0.post20201207
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.2
html5lib         : 0.9999999
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 5.8.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 2.1.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.0.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
numba            : None

</details>

**Comment by debnathshoham** [comment]
This is giving the expected df on master.
Maybe could be closed with a test.
```python

In [8]: import pandas as pd

In [9]: pd.__version__
Out[9]: '1.4.0.dev0+722.ge7e7b40722'

In [10]: df = pd.DataFrame({'a': [1, 1, 2, 2], 'b': [4, 2, 5, 1]})
    ...: 
    ...: def f(x):
    ...:     # Insert a new column "c" and sort each sub-dataframe "x" according to values in "c"
    ...:     x['c'] = x['b'].tolist()
    ...:     return x.sort_values('c')
    ...: 
    ...: df = df.groupby('a').apply(f).reset_index(drop=True)

In [11]: df
Out[11]: 
   a  b  c
0  1  2  2
1  1  4  4
2  2  1  1
3  2  5  5

**Comment by MarcoGorelli** [comment]
Mutation within groupby.apply isn't supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/gotchas.html#gotchas-udf-mutation - as it's not something that is planned to be supported, I _think_ this can be closed without a test? @rhshadrach what do you think?

**Comment by ryangogogo36** [comment]
> Mutation within groupby.apply isn't supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/gotchas.html#gotchas-udf-mutation - as it's not something that is planned to be supported, I _think_ this can be closed without a test? @rhshadrach what do you think?

Thank you so much for the link! I am new to Pandas and didn't know mutation within groupby.apply isn't supported. If it is not planned to be supported in the near future, feel free to close. Thank you again!

**Comment by rhshadrach** [comment]
Thanks for the report @ryangogogo36 - agreed @MarcoGorielli.
