### ISSUE TITLE
BUG: Wrong time data when using GMT+/-xy time zones

### ISSUE THREAD

**Issue by SKittan** [pandas-dev/pandas#43669]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd

pd.date_range("01.01.2021", periods=4, freq='H', tz='Europe/Berlin')
pd.date_range("01.01.2021", periods=4, freq='H', tz='Etc/GMT+1')
```

### Issue Description

I use the date_range function to create a series of time values with time zone information. Since I don't want the DST, I do not use the Berlin time zone, but the equivalent GMT+1 zone. Comparing the results of both function calls, it seems that the time offset sign of the GMT is inverted. This leads to different results for above function calls, which is not correct in my opinion.

### Expected Behavior

I expect the same results for both function calls. But the time zone of GMT+1 is different from the time zone of Berlin.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 73c68257545b5f8530b7044f56647bd2db92e2ba
python           : 3.9.7.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : de_DE.cp1252

pandas           : 1.3.3
numpy            : 1.20.3
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.27.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : 2.7.3
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : None
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.54.0

</details>

**Comment by Liam3851** [comment]
This is due to the convention of tzdata timezones, which in turn follow POSIX. Use Etc/GMT-1. See https://github.com/eggert/tz/blob/2019c/etcetera#L37-L43 and https://en.wikipedia.org/wiki/Tz_database#Area .

**Comment by goyodiaz** [comment]
This is not a bug and should be closed. Using the correct time zone (`'Etc/GMT-1'`)  works as it should:

```python
>>> import pandas as pd
>>> pd.date_range("01.01.2021", periods=4, freq='H', tz='Europe/Berlin')
DatetimeIndex(['2021-01-01 00:00:00+01:00', '2021-01-01 01:00:00+01:00',
               '2021-01-01 02:00:00+01:00', '2021-01-01 03:00:00+01:00'],
              dtype='datetime64[ns, Europe/Berlin]', freq='H')
>>> pd.date_range("01.01.2021", periods=4, freq='H', tz='Etc/GMT-1')
DatetimeIndex(['2021-01-01 00:00:00+01:00', '2021-01-01 01:00:00+01:00',
               '2021-01-01 02:00:00+01:00', '2021-01-01 03:00:00+01:00'],
              dtype='datetime64[ns, Etc/GMT-1]', freq='H')
```
