### ISSUE TITLE
BUG: idxmax raises when used with tuples

### ISSUE THREAD

**Issue by helgehatt** [pandas-dev/pandas#43697]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd

x = pd.Series([(1,3),(2,2),(3,1)])

# This succeeds as the max operation is performed on the first element of a tuple
assert x.max() == (3,1)

# This fails with `TypeError: reduction operation 'argmax' not allowed for this dtype`
assert x.idxmax() == 2

# Using numpy directly works as you'd expect
import numpy as np
assert np.argmax(x.values) == 2
```

### Issue Description

Using `max` on a series of tuples returns the tuple as if the max operation was performed on the first element of each tuple. 

Using `idxmax` however, raises an operation not allowed TypeError.

### Expected Behavior

Even though there are several ways of achieving the desired result, I would expect consistency between the usage of `max` and `idxmax`, as it is for `max` and `argmax` in numpy.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 73c68257545b5f8530b7044f56647bd2db92e2ba
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-1113-azure
Version          : #126~16.04.1-Ubuntu SMP Tue Apr 13 16:55:24 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.3
numpy            : 1.20.1
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.1.3
setuptools       : 52.0.0.post20210125
Cython           : 0.29.23
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.22.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 2021.06.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : 2.7.3
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.2
sqlalchemy       : None
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by goyodiaz** [comment]
The problem actually comes from `argmax`:

```python
>>> x.argmax()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/goyo/.local/lib/python3.9/site-packages/pandas/core/base.py", line 647, in argmax
    return nanops.nanargmax(  # type: ignore[return-value]
  File "/home/goyo/.local/lib/python3.9/site-packages/pandas/core/nanops.py", line 88, in _f
    raise TypeError(
TypeError: reduction operation 'argmax' not allowed for this dtype
```

The way it is written it always delegate to `nanops.nanargmax` for dtype `'O`', but `nanops.nanargmax` explicitly disallows arrays of that dtype.

Here's a hotfix:

```python
import numpy as np
import pandas as pd
from pandas.core.base import nv, nanops, ExtensionArray, IndexOpsMixin

def argmax(self, axis=None, skipna: bool = True, *args, **kwargs) -> int:
    """
    Return int position of the {value} value in the Series.

    If the {op}imum is achieved in multiple locations,
    the first row position is returned.

    Parameters
    ----------
    axis : {{None}}
        Dummy argument for consistency with Series.
    skipna : bool, default True
        Exclude NA/null values when showing the result.
    *args, **kwargs
        Additional arguments and keywords for compatibility with NumPy.

    Returns
    -------
    int
        Row position of the {op}imum value.

    See Also
    --------
    Series.arg{op} : Return position of the {op}imum value.
    Series.arg{oppose} : Return position of the {oppose}imum value.
    numpy.ndarray.arg{op} : Equivalent method for numpy arrays.
    Series.idxmax : Return index label of the maximum values.
    Series.idxmin : Return index label of the minimum values.

    Examples
    --------
    Consider dataset containing cereal calories

    >>> s = pd.Series({{'Corn Flakes': 100.0, 'Almond Delight': 110.0,
    ...                'Cinnamon Toast Crunch': 120.0, 'Cocoa Puff': 110.0}})
    >>> s
    Corn Flakes              100.0
    Almond Delight           110.0
    Cinnamon Toast Crunch    120.0
    Cocoa Puff               110.0
    dtype: float64

    >>> s.argmax()
    2
    >>> s.argmin()
    0

    The maximum cereal calories is the third element and
    the minimum cereal calories is the first element,
    since series is zero-indexed.
    """
    delegate = self._values
    nv.validate_minmax_axis(axis)
    skipna = nv.validate_argmax_with_skipna(skipna, args, kwargs)

    if delegate.dtype is np.dtype('O'):  # This is the part I added to deal with dype('O')
        # Ignoring skipna because I am not sure what it should do here. NA's in
        # series with dtype('O') will cause trouble anyway.
        return delegate.argmax()
    elif isinstance(delegate, ExtensionArray):
        if not skipna and delegate.isna().any():
            return -1
        else:
            return delegate.argmax()
    else:
        # error: Incompatible return value type (got "Union[int, ndarray]", expected
        # "int")
        return nanops.nanargmax(  # type: ignore[return-value]
            delegate, skipna=skipna
        )

IndexOpsMixin.argmax = argmax

x = pd.Series([(1, 3), (2, 2), (3, 1), (3, 0)], index=['zero', 'one', 'two', 'three'])
assert x.idxmax() == 'two'
assert x.argmax() == 2
```
