### ISSUE TITLE
BUG: styler render trimming does not work with `hide_columns`

### ISSUE THREAD

**Issue by attack68** [pandas-dev/pandas#43704]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
pd.options.styler.render.max_columns = 2
df = DataFrame(np.random.randn(1,5))
df.style.hide_columns(df.columns[:2])
```

### Issue Description

The render is empty since the first two columns are looped but hidden, the loop index does not progress passed 2.

This is a similar issue to #43703 but recorded separately since requires different fixes.

### Expected Behavior

Render columns 3 and 4 with a trimmed column

### Installed Versions

master

**Comment by pedr0luiz** [comment]
take

**Comment by VFermat** [comment]
take

**Comment by VFermat** [comment]
Hi!
I'll be working alongside @pedr0luiz on this issue!

**Comment by gabrielzezze** [comment]
take

**Comment by attack68** [comment]
anyone looking at this should wait until #43649 is merged, since the code relevant to this issue will change significantly, and you will struggle to merge.
