### ISSUE TITLE
DOC: pandas.DataFrame.rename's introduction may be misleading.

### ISSUE THREAD

**Issue by smallfishabc** [pandas-dev/pandas#43708]
### 

- [X] I have checked that the issue still exists on the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.rename.html?highlight=rename#pandas.DataFrame.rename

### Documentation problem

In the document, the developers have suggested a simple way to rename the columns. However, I think we should add a sentence to point out that the rename will only give out a new data frame rather than directly rename the old data frame.

### Suggested fix for documentation

In the document, the developers have suggested a simple way to rename the columns. However, I think we should add a sentence to point out that the rename will only give out a new data frame rather than directly rename the old data frame.

**Comment by jreback** [comment]
this is what virtually operations do in pandas

if u use inplace it will be inplace

not sure what u r suggesting

you are welcome to do a PR with changes and we can look

**Comment by smallfishabc** [comment]
> this is what virtually operations do in pandas
> 
> if u use inplace it will be inplace
> 
> not sure what u r suggesting
> 
> you are welcome to do a PR with changes and we  can look

Hi. Thank you for your reply. For people who know how to use pandas, this operation is not surprising. However, for people who are not familiar with pandas, this may be confusing. Especially, when the description of the 'inplace' keyword is vague and inconsistent with the other commends in the same module/script. 

Here is the introduction of 'inplace' in the document.
inplace bool, default False
Whether to return a new DataFrame. If True then value of copy is ignored.
(This introduction do not indicate whether this 'inplace' will alter the value in the original dataframe)
Here are some descriptions from the other commands of the same module/script.
       inplace : bool, default False
            If True, modifies the DataFrame in place (do not create a new object).
inplace : bool, default False
        If True, performs operation inplace and returns None."""
Those explanations are better I think.
 
We can also change this 

df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
df.rename(columns={"A": "a", "B": "c"})

to this

df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
new_df=df.rename(columns={"A": "a", "B": "c"})

or 

df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
df.rename(columns={"A": "a", "B": "c"},inplace=True)
