### ISSUE TITLE
BUG: df.groupby.apply(lambda x: x.reindex) behaviour changed from Pandas 1.3.0 to 1.3.3

### ISSUE THREAD

**Issue by mlee94** [pandas-dev/pandas#43727]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

start_date = pd.to_datetime('2019-01-01')
end_date = pd.to_datetime('2019-01-05')
data = {
    'code': ['X333']*5,
    'date': pd.date_range(start_date, periods=5),
    'float': np.random.randn(5),
}

df = (
    pd.DataFrame(data)
    .set_index('date')
    .groupby('code')
    .apply(
        lambda x: x.reindex(pd.date_range(start_date, end_date, name='date'))
    )
)
print(df)
```

### Issue Description

pandas=1.3.3
Group by key `code` is removed from the multi-index:
```
            code     float
date
2019-01-01  X333 -0.732025
2019-01-02  X333  0.251650
2019-01-03  X333  0.301808
2019-01-04  X333 -0.585017
2019-01-05  X333  0.067119
```
### Expected Behavior
pandas=1.3.0
Group by key `code` is kept in the multi-index:
```
                 code     float
code date
X333 2019-01-01  X333 -0.971248
     2019-01-02  X333  0.701875
     2019-01-03  X333  1.222485
     2019-01-04  X333  0.315564
     2019-01-05  X333  0.836289
```
### Installed Versions

<details>

<br>

INSTALLED VERSIONS
------------------

commit           : 73c68257545b5f8530b7044f56647bd2db92e2ba
python           : 3.7.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 58 Stepping 0, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.3.3
numpy            : 1.21.2
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.1
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : None
psycopg2         : 2.9.1 (dt dec pq3 ext lo64)
jinja2           : 2.11.3
IPython          : 7.27.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
fsspec           : 2021.08.1
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 5.0.0
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.4.24
tables           : None
tabulate         : None
xarray           : 0.19.0
xlrd             : None
xlwt             : None
numba            : 0.53.0
</details>

**Comment by TomAugspurger** [comment]
I think this is the same as https://github.com/pandas-dev/pandas/issues/43568.
