### ISSUE TITLE
BUG: None is replaced with Nan

### ISSUE THREAD

**Issue by George3d6** [pandas-dev/pandas#43721]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas. 
Note: Env bellow is not the latest, but I also tested with 1.3.3 and behavior remains the same

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame()
df['a'] = [1,2,3,4,5,6,7,8,None,None]
print(df['a'])

> Outputs:
0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    7.0
7    8.0
8    NaN
9    NaN
Name: a, dtype: float64
```

### Issue Description

Pandas is replacing `None` with `NaN` these are no the same, this is horrible and will cause bugs

### Expected Behavior

I'd expected values I assign to an element or column in a pandas data frame to either:

1. Get assigned
2. Raise and error if they can't be assigned

### Installed Versions

>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : 67a3d4241ab84419856b84fc3ebc9abcbe66c6b3
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.11.0-34-generic
Version          : #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.1.4
numpy            : 1.21.2
pytz             : 2019.3
dateutil         : 2.7.3
pip              : 20.0.2
setuptools       : 57.4.0
Cython           : 0.29.21
pytest           : 6.1.2
hypothesis       : None
sphinx           : 4.1.2
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.18.1
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : 0.8.7
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 4.0.0
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.0
sqlalchemy       : 1.4.23
tables           : None
tabulate         : 0.8.7
xarray           : None
xlrd             : 1.2.0
xlwt             : None
numba            : 0.53.1

**Comment by jreback** [comment]
https://pandas.pydata.org/docs/dev/user_guide/missing_data.html

None is an object snd cannot be represented as such in a numeric array

you can use object dtype and it will preserve with a performance penalty

**Comment by George3d6** [comment]
But converting to `object` doesn't actually work in most cases.

Pandas randomly decide to convert `object` typed column backed into ints and there's no reliable way to "force" it to use `object`.
