### ISSUE TITLE
DOC: Typo in pandas.tseries.offset

### ISSUE THREAD

**Issue by tanjt107** [pandas-dev/pandas#43749]
### 

- [X] I have checked that the issue still exists on the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.tseries.offsets.BYearEnd.html

### Documentation problem

A “s” is missing in the word “offset” `from pandas.tseries.offset import BYearEnd`

### Suggested fix for documentation

`from pandas.tseries.offsets import BYearEnd`

**Comment by debnathshoham** [comment]
Thanks for the report @tanjt107!
PR to fix this would be welcome.

**Comment by Digres45** [comment]
take

**Comment by MarcoGorelli** [comment]
Looks like there's a few more places where this happens

```
$ git grep 'from pandas.tseries.offset '
pandas/_libs/tslibs/offsets.pyx:    >>> from pandas.tseries.offset import BYearBegin
pandas/_libs/tslibs/offsets.pyx:    >>> from pandas.tseries.offset import BQuarterEnd
pandas/_libs/tslibs/offsets.pyx:    >>> from pandas.tseries.offset import BQuarterBegin
pandas/_libs/tslibs/offsets.pyx:    >>> from pandas.tseries.offset import BMonthEnd
pandas/_libs/tslibs/offsets.pyx:    >>> from pandas.tseries.offset import BMonthBegin
```

If anyone wanted to fix those too, that'd be welcoem

**Comment by debnathshoham** [comment]
shouldn't we include the cython modules in the doctests? (IIUC they aren't as of now)

**Comment by VivekThazhathattil** [comment]
take

**Comment by MarcoGorelli** [comment]
> shouldn't we include the cython modules in the doctests? (IIUC they aren't as of now)

Yeah I don't think `doctest` runs of cython files, but it'd be good to include them somehow
