### ISSUE TITLE
DOC: Typo(s?) in pandas.DataFrame.isin

### ISSUE THREAD

**Issue by loucadufault** [pandas-dev/pandas#43755]
### 

- [X] I have checked that the issue still exists on the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isin.html

### Documentation problem

In the last example, the text introducing the code snippet reads:

> When values is a Series or DataFrame the index and column must match. Note that ‘falcon’ does not match based on the number of legs in df2.

However, "df2" does not exist in the  included code snippet (it is instead called "other").

Additionally, I am not comfortable enough with pandas to assert this, but it seems like the text should incorrectly states that "falcon" does not match, since "falcon" indeed does match for both columns, see the relevant portion of the code snippet:

```
>>> df.isin(other)
        num_legs  num_wings
falcon      True       True
dog        False      False
```

### Suggested fix for documentation

Text should at least read:

> When `values` is a Series or DataFrame the index and column must match. Note that ‘falcon’ does not match based on the number of legs in other.

or the variable in the code snippet should be renamed to "df2".

Additionally, something may need to be done to address the potential discrepancy in saying that "falcon" does not match.

**Comment by Varun270** [comment]
@loucadufault I am not able to find out the exact location of the file that needs to be fixed. Can you tell me what is the location of this file? I tried finding it through this link https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isin.html but wasn't able to spot the relevant folders.

**Comment by johnzangwill** [comment]
@Varun270 The fiile is frame.py. If you want to fix it I'll leave it to you. Otherwise, I can.

**Comment by MarcoGorelli** [comment]
> @loucadufault I am not able to find out the exact location of the file that needs to be fixed. Can you tell me what is the location of this file? I tried finding it through this link https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isin.html but wasn't able to spot the relevant folders.

You can find locations clicking on 'source':
![Screenshot 2021-09-27 at 09 55 06](https://user-images.githubusercontent.com/33491632/134876964-c3441519-3b9e-4ffe-8243-c847856ad5c9.png)

**Comment by Varun270** [comment]
> @Varun270 The file is frame.py. If you want to fix it I'll leave it to you. Otherwise, I can.

Yeah, I would love to fix this issue. Thanks !!!

**Comment by Varun270** [comment]
take

**Comment by Varun270** [comment]
<img width="860" alt="pandas_new_issue" src="https://user-images.githubusercontent.com/75975268/135234105-668b763c-34be-4ea4-b80f-fd46874f7158.png">

**Comment by Varun270** [comment]
<img width="896" alt="pandas_new_issue_git" src="https://user-images.githubusercontent.com/75975268/135234140-08d86cd8-a187-49be-9e01-63dfc652c3de.png">

**Comment by Varun270** [comment]
@MarcoGorelli  I have pushed the changes but somehow instead of pushing it from Development ----> Master. I pushed it from Development ----> Development. Development is a branch that I made. what should I do now to fix this delete the previous commit and again create a PR?

**Comment by MarcoGorelli** [comment]
you can make a new branch - I recommend the first 3 chapters of [this book](https://git-scm.com/book/en/v2) for getting familiar with the git workflow

**Comment by johnzangwill** [comment]
@Varun270 Just follow the "contributing" instructions to the letter. Yes, there is a bit of a learning curve...

I suggest that you change your change slightly. You say "Note that 'falcon' does not match based on the number of legs in other."
But in fact it does match.

I would change to:

`other = pd.DataFrame({'num_legs': [8, 3], 'num_wings': [0, 2]},index=['spider', 'falcon'])`

Then you will indeed get the falcon not matching:

```
 >>> df.isin(other)
                num_legs  num_wings
        falcon     False       True
        dog        False      False
```
