### ISSUE TITLE
Summing nanoseconds time delta to timestamp

### ISSUE THREAD

**Issue by deponovo** [pandas-dev/pandas#43764]
### 

- [X] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd
res1 = (pd.Timestamp(1001) == pd.Timedelta(seconds=1e-9) + pd.Timestamp(1000))  # False, but should be True
res2 = (pd.Timestamp(1001) == pd.Timestamp(1) + pd.Timedelta(seconds=1000e-9))  # True
res1 == res2  # False, should be True
# this sum works properly `pd.Timestamp(1) + pd.Timedelta(nanoseconds=1)`
```

### Issue Description

Adding `Timedelta`s that have nanoseconds defined as a float do not work properly for timedelta values in the [1-999] range.
This report is a result of [this SO question](https://stackoverflow.com/questions/69321347/pandas-summing-nanoseconds-time-delta-to-timestamp?noredirect=1#comment122560569_69321347) 

### Expected Behavior

`all([pd.Timestamp(1000 + x) == (pd.Timedelta(seconds=x*1e-9) + pd.Timestamp(1000)) for x in range(1000)])` should be `True`

Or any equivalent not using the explicit default nanoseconds unit or the `nanoseconds` keyword as in: `pd.Timedelta(1)` or `pd.Timedelta(nanoseconds=1)`

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : c7f7443c1bad8262358114d5e88cd9c8a308e8aa
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : de_DE.cp1252
pandas           : 1.3.1
numpy            : 1.20.3
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.2
setuptools       : 49.6.0.post20210108
Cython           : None
pytest           : 6.2.4
hypothesis       : None
sphinx           : 4.0.2
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.24.1
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.2
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.1
numexpr          : 2.7.3
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.3
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by MrFuppes** [comment]
To clarify a bit more, you can create a pandas Timedelta with nanoseconds specified;
```Python
td = pd.Timedelta(nanoseconds=1)
print(td.seconds, td.microseconds, td.nanoseconds)
# 0 0 1
```
You can also specify a certain number of microseconds by providing the microseconds as a fractional seconds:
```Python
td = pd.Timedelta(seconds=1e-6)
print(td.seconds, td.microseconds, td.nanoseconds)
# 0 1 0
```
However **what does not work** is specifying nanoseconds like this:
```Python
td = pd.Timedelta(seconds=1e-9)
print(td.seconds, td.microseconds, td.nanoseconds)
# 0 0 0
```
So the point here to me is: everything that pandas Timedelta inherited from Python's timedelta works as expected. But when it comes to the additional feature, the nanoseconds attribute, a correct conversion from some inputs seems to be missing.

**Comment by jbrockmendel** [comment]
> res1 = (pd.Timestamp(1001) == pd.Timedelta(seconds=1-9) + pd.Timestamp(1000))  # False, but should be True

First off I'm guessing you want `1e-9` instead of `1-9`.  Fixing that doesn't actually make a difference bc the Timedelta constructor casts 1e-9 to integer, in this case 0.

Could take a PR either a) raising if a non-integer is passed to Timedelta (depends on how much that check affects perf) or b) documenting this requirement

**Comment by jreback** [comment]
this is a duplicate issue
pls have a search of the tracker

**Comment by deponovo** [comment]
@jbrockmendel fixed the typo.
>  Timedelta constructor casts 1e-9 to integer, in this case 0.
This is not consistent with:
`td = pd.Timedelta(seconds=1e-6)`
as metnioned by @MrFuppes

**Comment by MrFuppes** [comment]
> this is a duplicate issue pls have a search of the tracker

@jreback would not surprise me - but I couldn't find an exact dupe by searching the issues (also not knowing where exactly the described behavior originates from). If you have one in mind, please share.

**Comment by deponovo** [comment]
Take

**Comment by deponovo** [comment]
@mroeschke @jbrockmendel @jreback would it be ok if I solve this issue together with #40946 in one PR?
