### ISSUE TITLE
DOC: No links to prior versions docs

### ISSUE THREAD

**Issue by DrGFreeman** [pandas-dev/pandas#43782]
### 

- [X] I have checked that the issue still exists on the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/index.html

### Documentation problem

It is difficult to access the documentation of prior pandas versions. https://pandas.pydata.org/docs/index.html has no links to prior versions docs or they are difficult to find.

When working with legacy code using older pandas versions, access to the docs of a specific version, especially the API reference, can be useful.

While it if possible to find the URL, e.g. https://pandas.pydata.org/pandas-docs/version/0.24.0/ with a bit of trial and error, a list of links to the prior versions docs would be useful.

### Suggested fix for documentation

Add a page in the docs with a list of links to prior versions docs.

**Comment by DrGFreeman** [comment]
I'm interested in contributing a PR to add the links on a new page, or elsewhere, if this idea is accepted by the maintainers. Feedback welcome. Thx.

**Comment by mroeschke** [comment]
Thanks for the suggestion. Since this suggestion overlaps with https://github.com/pandas-dev/pandas/issues/42722, I am going to close this issue in order to consolidate discussion and effort towards that issue. Still happy to have your contribution towards this suggestion!

**Comment by DrGFreeman** [comment]
@mroeschke, I agree this overlaps with #42722, but I believe the intent and solutions to the two issues are different.

As solution to #42722 would add the **current** version number in the page header but would not provide access to the documentation of previous versions.

In opposition, a solution to this issue would add information on how to get documentation of prior versions (example below), without information on the current version (except on the `index` page).

![image](https://user-images.githubusercontent.com/22901938/135186694-0eff09a3-c323-40aa-80ca-9ddc49f94aa5.png)

Adding a dropdown menu to select the docs version would be a solution to both issues. However, the implementation of such a solution is significantly more complex and, as stated in #42722, probably not worth the effort:

> Python also offers a drop down menu to select a specific docs version. I think this is overhead and not needed for pandas.

For the above reasons, I believe the two issues should be dealt with separately. If you agree, I could submit a PR that addresses the current issue with a change as in the above example.

**Comment by MarcoGorelli** [comment]
> If you agree, I could submit a PR that addresses the current issue with a change as in the above example.

sounds good, feel free to open a PR
