### ISSUE TITLE
BUG: python engine in pd.read_csv fails to parse with " after delimiter

### ISSUE THREAD

**Issue by alex-tully** [pandas-dev/pandas#43798]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd
pd.read_csv("pandas_check.csv", engine="python")


# pandas_check.csv
id,name,description
ID001,Task_001,Task_001 – here for the testing
ID002,"Task_002" this is a test,Task_002 – here for the testing
```

### Issue Description

When the python engine is used in `read_csv` and a column contains a `"text" more text` after the delimiter then a parser error is thrown.

```
Traceback (most recent call last):
  File "/home/development/my_project/.venv/lib/python3.8/site-packages/pandas/io/parsers/python_parser.py", line 742, in _next_iter_line
    return next(self.data)
_csv.Error: ',' expected after '"'
```

### Expected Behavior

I would expect the column to be parsed without error as it is in the  C engine

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 73c68257545b5f8530b7044f56647bd2db92e2ba
python           : 3.8.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.14.246-187.474.amzn2.x86_64
Version          : #1 SMP Tue Sep 7 21:48:11 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.3
numpy            : 1.21.2
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.3
setuptools       : 49.2.1
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 5.0.0
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by phofl** [comment]
This is from the csv.reader module, because the following raises too:

```
with open("test.csv") as f:
    data = csv.reader(f, quotechar='"', delimiter=",", strict=True)
    while True:
        next(data)
```

The csv is "bad"

**Comment by alex-tully** [comment]
Ah so it is. This only occurs because `strict=True` is set in the python parser, there is a discrepancy between the behaviour of this and the c engine with `read_csv`. 

Thankfully the c engine works here as we have a lot of csv with quotes within the columns
