### ISSUE TITLE
how to merge on one column while keeping index?

### ISSUE THREAD

**Issue by lidh15** [pandas-dev/pandas#43794]
Question:
In older version of pandas, I got this:

df1
         value
index
10        100
20        200
30        300

df2
         value
index
40        100
50        300
60        600

by merge on "value" and set "left_index=True" I got
df3
         value
index
10        100
30        300

but after update the library, it's illegal to do this, 
if I set left_index=True, there won't be any intersection, 
if I use "on" key word, I lost the original index
what is the solution?

**Comment by debnathshoham** [comment]
Thanks for the report @lidh15 !

Could you please provide a minimal, copy-pastable example as mentioned [here](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by phofl** [comment]
Closing for now. Please ping to reopen if you can provide something reproducible
