### ISSUE TITLE
CI: Incompatible versions in resolved dependencies

### ISSUE THREAD

**Issue by attack68** [pandas-dev/pandas#43804]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
.
```

### Issue Description

I tried to create a new development environment today. 

Resolving the dependencies using `pip install -r requirements-dev.txt` took two hours before I cancelled it. 

I then tried to use `pip-compile` from `pip install pip-tools` and I received the message:

```
There are incompatible versions in the resolved dependencies:
  botocore>=1.11 (from -r requirements-dev.in (line 35))
  botocore>=1.12.201 (from moto==2.2.8->-r requirements-dev.in (line 37))
  botocore<1.22.0,>=1.21.51 (from boto3==1.18.51->-r requirements-dev.in (line 34))
  botocore<1.20.107,>=1.20.106 (from aiobotocore==1.4.1->-r requirements-dev.in (line 72))
```
Having pinned `boto3>=1.17.106,<1.17.107` since that is what `aiobotocore` packages with, the next error was:

```
There are incompatible versions in the resolved dependencies:
  fsspec<2021.6.0,>=0.7.4 (from -r requirements-dev.in (line 73))
  fsspec==2021.09.0 (from gcsfs==2021.9.0->-r requirements-dev.in (line 74))
  fsspec==2021.09.0 (from s3fs==2021.9.0->-r requirements-dev.in (line 71))
  fsspec (from fastparquet==0.7.1->-r requirements-dev.in (line 67))
  fsspec>=0.6.0 (from dask==2021.9.1->-r requirements-dev.in (line 26))
```

So then I pinned `gcsfs==2021.5.0` and `s3f2==2021.5.0`.

It then compiled and I was able to install packages.

(adding a third complaint: new pyright checks need numpy >1.21.0 but numba needs less than that)

### Expected Behavior

consistent deps.

### Installed Versions

master as of 29-sep-21. python 3.8, mac os.

**Comment by lithomas1** [comment]
I have fixed the fsspec issue, and unpinned fsspec.  I don't use pip to install my packages so not sure about the first error. Can you please provide us your pip version?
