### ISSUE TITLE
TYP: mypy complaint isocalendar does not match supertype

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#43807]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
When I run mypy locally (this has happened for a while and I've been ignoring it) I get


pandas/_libs/tslibs/timestamps.pyi:160: error: Return type "Tuple[int, int, int]" of "isocalendar" incompatible with return type "_IsoCalendarDate" in supertype "datetime"  [override]
pandas/_libs/tslibs/timestamps.pyi:160: error: Return type "Tuple[int, int, int]" of "isocalendar" incompatible with return type "_IsoCalendarDate" in supertype "date"  [override]
```
```


### Issue Description

N/A

### Expected Behavior

N/A

### Installed Versions

py39, master

**Comment by twoertwein** [comment]
Python 3.9 changed it to a namedtuple https://docs.python.org/3/library/datetime.html#datetime.date.isocalendar

**Comment by jbrockmendel** [comment]
OK.  So i should continue to ignore it until the CI's mypy runs on py39?

**Comment by twoertwein** [comment]
I think the best would be to add `python_version = "3.8"` to pyproject.toml (I didn't test whether that helps - I have been ignoring this error as well)

**Comment by simonjayhawkins** [comment]
> OK. So i should continue to ignore it until the CI's mypy runs on py39?

If we want to to use mypy to help catch errors for our minimum supported versions, we should probably keep type checking pinned to Python 3.8 until we drop support for it. That does not stop us running mypy on a later version of Python.

Similarly we have the mypy config setup to check against Linux otherwise we get clipboard related errors reported on Windows.
