### ISSUE TITLE
ENH: Add  a ```level``` option to ```pd.DataFrame.append()```

### ISSUE THREAD

**Issue by MoAly98** [pandas-dev/pandas#43821]
I have two dataframes:

The first one looks like this:

|       |          | variable |
|:----: |:------:   | :-----:|
| entry | subentry |          |
| 0  | 1       | X |
|    | 2       | Y |
|    | 3       | Z |

and the second one looks like:

|       |          | variable |
|:----: |:------:   | :-----:|
| entry | subentry |          |
| 0  | 1       | A |
|    | 2       | B |

I would like to merge the two dataframe such that I get:

|       |          | variable |
|:----: |:------:   | :-----:|
| entry | subentry |          |
| 0  | 1       | X |
|    | 2       | Y |
|    | 3       | Z |
| 1  | 1       | A |
|    | 2       | B |

Simply using ```df1.append(df2, ignore_index=True)``` gives 

|        |variable |
|:----:  |:-----:|
|     |         |
| 0   |X |
| 1   | Y |
| 2   | Z |
| 3   | A |
| 4   | B |

In other words, it appends on the highest level (level 1) in the dataframes. I think it important to allow the user dealing with mutli-index dataframes to specify which level of the dataframe to append on. In the simple example above, this would allow me to specify "entry" as the index to append on. 

 Here is a code sinppet that will reproduce the problem:

```
	arrays = [
	    np.array([0,0,0]),
	    np.array([0,1,2]),]
	arrays_2 = [
	    np.array([0,0]),
	    np.array([0,1]),]
	df1 = pd.DataFrame(np.random.randn(3, 1), index=arrays)
	df2 = pd.DataFrame(np.random.randn(2, 1), index=arrays_2)
	df = df1.append(df2, ignore_index=True)
	print(df)
```

 In practice, I am looking ao combine N dataframes, each with a different number of "entry" rows. So I am looking for an approach that will not rely on me knowing the exact  of the dataframes I am combining.

**Comment by phofl** [comment]
It does append on all levels and calls reset_index afterwards.

-1 on this

**Comment by MoAly98** [comment]
This is exactly what I'm asking to make more flexible. The reseting of the index causes the loss of my multi-index structure. I think there should be flexibility in append to just append on one level and only reset one level's index.

**Comment by mroeschke** [comment]
I would be also -1 toward this suggestion for similar reasons as well as the likelihood for append to be deprecated in a future release: https://github.com/pandas-dev/pandas/issues/35407

**Comment by mroeschke** [comment]
Thanks for the suggestion, but since there hasn't been additional support from the community or other core devs, going to close.
