### ISSUE TITLE
QST: About the meaninf of `~` used in `dfs = dfs.loc[:, ~dfs.columns.str.contains('^Unnamed', na=False)]`.

### ISSUE THREAD

**Issue by hongyi-zhao** [pandas-dev/pandas#43832]
### 

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/a/64335734

### Question about pandas

Currently, I'm using the following method to get rid of "Unnamed: 0" column in a pandas DataFrame according to the comments noted [here](https://stackoverflow.com/questions/36519086/how-to-get-rid-of-unnamed-0-column-in-a-pandas-dataframe/66704993#66704993) and [here](https://stackoverflow.com/questions/52297740/typeerror-bad-operand-type-for-unary-float):

```python
import pandas as pd

excel='2021-2022-1.xlsx'
dfs = pd.read_excel(excel)
dfs = dfs.loc[:, ~dfs.columns.str.contains('^Unnamed', na=False)]
```
But I am puzzled by the meaning of the `~` symbol used above. I try to find some relevant explanations by googling or digging into the source code of  pandas, but still got nothing. Any hints for this question will be greatly appreciated.

Regards,
HZ

**Comment by phofl** [comment]
This has nothing to do with pandas. It is a python operator

https://docs.python.org/3/reference/expressions.html#unary-arithmetic-and-bitwise-operations

**Comment by hongyi-zhao** [comment]
Based on your notes, I would like to add some relevant validations as follows:

```python
In [17]: dfs.columns.str.contains('^Unnamed', na=False)
Out[17]: 
array([ True, False, False, False, False, False, False, False, False,
       False])

In [18]: ~dfs.columns.str.contains('^Unnamed', na=False)
Out[18]: 
array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [19]: bool_arr = np.array([True, False, False, False, False, False, False, False, False, False], dtype=bool)

In [20]: ~bool_arr
Out[20]: 
array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])
```
So, the `Unnamed` column will be filtered out by the above expression. See [here](https://riptutorial.com/numpy/example/21181/creating-a-boolean-array#example) and [here](https://stackoverflow.com/questions/7278779/bit-wise-operation-unary-invert) for some additional explanations.
