### ISSUE TITLE
BUG: using 2 character seperator in pd.json_normalize

### ISSUE THREAD

**Issue by pustetorte** [pandas-dev/pandas#43831]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd
d = {'a': [1, 2], 'b': {'b_1': 2, 'b_2': (3, 4)}}
r = pd.json_normalize(d, sep='__')
```

### Issue Description

When using a separator with more then 1 character, for example '__', the new column names get the separator as prefix, too. If you use a separator with only 1 character, for example '_', everything works fine.

I get the following output from the code provided:

>         a      __b__b_1      __b__b_2
>      0  [1, 2]      2         (3, 4)

### Expected Behavior

>         a      b__b_1      b__b_2
>      0  [1, 2]     2       (3, 4)

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 73c68257545b5f8530b7044f56647bd2db92e2ba
python           : 3.9.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18363
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : de_DE.cp1252
pandas           : 1.3.3
numpy            : 1.21.1
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 49.6.0.post20210108
Cython           : 0.29.24
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.26.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 2021.07.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.2
numexpr          : 2.7.3
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 1.0.1
pyxlsb           : None
s3fs             : 0.4.2
scipy            : 1.7.1
sqlalchemy       : 1.3.23
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by pustetorte** [comment]
A workaround is to set `record_prefix=''`, but I don't think, that this should be the solution.

**Comment by Vijay-Arora** [comment]
Hey @pustetorte, I am new to open source contribution; Could you please suggest me if I could help you with any of the things related to this issue? Would love to hear from you!
Thanks!
