### ISSUE TITLE
ENH: Should  `pandas.CategoricalDtype` use `pandas.NA` as the sentinel value instead of `float('nan')` ?

### ISSUE THREAD

**Issue by randolf-scholz** [pandas-dev/pandas#43836]
Almost all of the the new nullable data types (which are incredibly useful btw.) seem to use `pd.NA` as the null-value.
However, I noticed that `pandas.CategoricalDtype` still uses `float('nan')`, which I suppose is for historical reasons.

Are there any plans - for the sake of consistency - to switch `CategoricalDtype`'s sentinel value to `pandas.NA` in the future?

**Comment by jbrockmendel** [comment]
> Are there any plans - for the sake of consistency - to switch CategoricalDtype's sentinel value to pandas.NA in the future?

No.  I think it's more likely we'll go the opposite direction with #29962

**Comment by phofl** [comment]
closing in favour of #50711
