### ISSUE TITLE
REF: Series.argsort should dispatch to EA.argsort

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#43840]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
N/A
```

### Issue Description

cc @jorisvandenbossche unless I'm missing something?  ive misunderstood the design/behavior of EA.argsort in the past.

### Expected Behavior

NA

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by mzeitlin11** [comment]
somewhat xref #35178

**Comment by jbrockmendel** [comment]
gentle ping @jorisvandenbossche

**Comment by jorisvandenbossche** [comment]
Sorry for the slow reply here. Maybe the more general question is: why does `Series.argsort` not use `nargsort`? (which then will dispatch to EA.argsort)  
`Series.argsort` seems like a more limited version reimplementing the missing value handling of `nargsort`?


---

I think in previous discussions related to EAs and argsort, it was mostly about the relationship between `nargsort`, `EA.argsort` and `EA._values_for_argsort` (which can call which?), and I don't directly remember discussing Series.argsort specifically. 
The original PR adding EA.argsort (https://github.com/pandas-dev/pandas/pull/19957) mentions that it enables `Series.argsort` (although the initial end goal was sorting), but it didn't actually do that (it didn't change Series.argsort to use it).

**Comment by jbrockmendel** [comment]
Looking at this, Series.argsort looks really sketchy.

```
dti = pd.date_range("2016-01-01", periods=4)
ser = pd.Series(dti)
ser[1] = pd.NaT

>>> ser.argsort().values
array([ 0, -1,  1,  2])

>>> ser.values.argsort()
array([0, 2, 3, 1])

>>> pd.core.sorting.nargsort(ser.values)
array([0, 2, 3, 1])
```

What would the `ser.argsort()` be useful for?  Passing it to something like `take` produces weird results (which vary depending on which take-like thing you use).

**Comment by jbrockmendel** [comment]
Once the deprecation in #54219 is enforced, we will be able to refactor in such a way as to close this.
