### ISSUE TITLE
API/DISC: engine="numba" (computational API) location in reductions functions or constructors

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#43886]
Currently, `engine="numba"` is enabled for `rolling` reduction functions (e.g. mean). I am making efforts to enable numba execution for `groupby` and regular `DataFrame/Series` reduction functions as well.

For `rolling`, the `engine` keyword is currently defined on the reduction functions e.g. 

```
df.rolling(2).mean(engine="numba", engine_kwargs={...})
df.groupby(key).mean(engine="numba", engine_kwargs={...})  # planned
df.mean(engine="numba", engine_kwargs={...})   # planned
```

https://github.com/pandas-dev/pandas/pull/43731#discussion_r715931881 suggested possibly putting engine in the "constructor" e.g. 

```
df.rolling(2, engine="numba", engine_kwargs={...}).mean()
df.groupby(key, engine="numba", engine_kwargs={...}).mean()
DataFrame(..., engine="numba", engine_kwargs={...}.mean()  ?
```

Pros of "in the constructor"

1. Less verbose e.g.
```
roll = df.rolling(2, engine="numba", engine_kwargs={...})
roll.mean() # numba
roll.median() # numba
roll.unsupported_agg() # raise NotImplementedError
```

Cons of "in the constructor"

1. Less flexibility in switching engines (probably minor) e.g.
```
gb = df.groupby(key, engine="numba", engine_kwargs={...})
gb.mean() # numba
# Reconstruct to switch engines
gb = df.groupby(key, engine="cython")
gb.cython_only_agg() # cython
```

2. Increased complexity with "chained constructors" e.g.
```
gb_roll = df.groupby(key, engine="numba").rolling(2, engine="numba").mean()
```

I prefer having `engine` in the reduction function, but opening this issue to solicit thoughts.

**Comment by attack68** [comment]
Initially I thought moving to constructor was cleaner, but I see the downside when you need more control or want to switch.

Is there a pandas option for this? It seems that `engine` is a frequent enough kwarg that it is precisely what the pandas options were designed to do. Then you can not have it in the constructor and use the pre-set option as default in the function, but still be able to overwrite where necessary?

**Comment by mroeschke** [comment]
Yes, one can currently specify the `compute.use_numba` option to globally or in a context use the numba engine. Not a bad, viable alternative to consistently use numba instead of kwargs in a methodd. If this path is pursued, this option will probably need to support `engine_kwargs` as the user can currently toggle` nogil`, `nopython`, and `parallel` with numba.

Of note, I imagine pandas will eventually adopt `arrow` as an option for compute or block/array storage, so consideration should probably be made for when `engine="arrow"` will also be a reality.

**Comment by mroeschke** [comment]
Since the issue was created, groupby agg funcs now have `engine` in the signature.

I guess since this is the pattern moving forward, going to close.

> I am wondering why not provide Pandas.DataFrame.apply()

Happy to have a PR adding that keyword in regular `DataFrame/Series` apply & reduction functions!
