### ISSUE TITLE
BUG: groupby().fillna does not return groupby key with the output

### ISSUE THREAD

**Issue by mdziel** [pandas-dev/pandas#43911]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import numpy as np
import pandas as pd

df = pd.DataFrame({'group': ['A', 'A', 'A', 'B', 'B', 'B'], 'v': [4, 5, np.nan, 1, np.nan, 2 ]})
df2 = df.groupby(by=['group']).fillna(method='bfill')
```

### Issue Description

The variable `group` is completely missing from the output - it is neither a column of `df2` nor part of its index.

### Expected Behavior

Expected behavior would be to include the `group` variable either as a column or an index of the output dataframe. This was actually the behavior in previous versions of pandas.

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : 73c68257545b5f8530b7044f56647bd2db92e2ba
python           : 3.8.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.17134
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en
LOCALE           : English_United States.1252

pandas           : 1.3.3
numpy            : 1.20.3
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.0.1
setuptools       : 58.0.4
Cython           : 0.29.24
pytest           : 6.2.4
hypothesis       : None
sphinx           : 4.2.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.1
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.8.6 (dt dec pq3 ext lo64)
jinja2           : 2.11.3
IPython          : 7.27.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fsspec           : 2021.08.1
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.2
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : 1.4.22
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.53.1

**Comment by asishm** [comment]
Can you specify which version of pandas?
> This was actually the behavior in previous versions of pandas.

**Comment by mroeschke** [comment]
Happy to reopen once the necessary information is provided.

**Comment by mdziel** [comment]
Well, I noticed it after upgrading to pandas 1.3.0, so I believe any version prior to that.

**Comment by jreback** [comment]
look at the release notes - this was intentionally changed

**Comment by adrienpacifico** [comment]
Hi @jreback ! Could you reference the release note you are referring to? 

I have note been able to find why it has been intentionally changed ([i haved looked in 1.3.0 release notes](https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.3.0.html). 

If I still need the key(s) after a `df.grouby(keys).fillna(method='bfill')`, what should I do?

If anyone is interested my current dirty workaround is:

```python
import pandas as pd

df = pd.DataFrame({'group': ['A', 'A', 'A', 'B', 'B', 'B'], 'v': [4, 5, None, 1, None, 2 ]})
df2 = (df
        .assign(group2= lambda x: x.group)
        .groupby(by=['group2'])
        .fillna(method='bfill')
      )
```
I also tried the `.groupby(["group"], as_index=False)` option, but the behavior was the same.
