### ISSUE TITLE
ENH: Make it possible to convert types using astype inplace

### ISSUE THREAD

**Issue by gasparitiago** [pandas-dev/pandas#43946]
#### Is your feature request related to a problem?

No, the feature is not related to a problem.

#### Describe the solution you'd like

It should be possible to perform the `astype()` operation directly into a dataframe passing an argument `inplace` as True.

#### API breaking implications

The API should not break once the default argument should be false, and the function will keep returning the same result as before.

#### Describe alternatives you've considered

Creating a new function exclusively for doing this kind of operation.

#### Additional context

```python
df = pd.DataFrame({'col1' : [1, 2, 3], 'col2' : [1.0, 2.0, 3.0]})
df.astype('float32', inplace=True)
```

**Comment by mzeitlin11** [comment]
Thanks for the request @gasparitiago. What is your use case for wanting the `inplace` argument? `astype` will always make a copy when the type changes, so the `inplace` argument seems confusing since it's not truly inplace.

**Comment by gasparitiago** [comment]
> Thanks for the request @gasparitiago. What is your use case for wanting the `inplace` argument? `astype` will always make a copy when the type changes, so the `inplace` argument seems confusing since it's not truly inplace.

Actually, I taught it would be a better solution for when you need to convert the types of a DataFrame, instead of overwriting the object, like this:

```
df = df.astype('float')
```

I opened a PR for doing that, but if it doesn't make sense because it's not truly in place, as you mentioned, we can close it :)

**Comment by phofl** [comment]
Also we are discussing deprecating inplace
