### ISSUE TITLE
ENH: Rolling TimeSeries Interpolation Methods

### ISSUE THREAD

**Issue by sweg44** [pandas-dev/pandas#43956]
I commonly deal with time-series data with gaps and would like Pandas to have the functionality to either apply a custom interpolation function which I can specify into .interpolate or have a dedicated time series data generator based on say the rolling N period values with some noise added to it for real-world applicability.

**Comment by sweg44** [comment]
Right now I just use the cubicspline interpolation method and then use a mask to add noise to it generated via scipy

**Comment by jreback** [comment]
and pls show what u r doing in code

**Comment by mroeschke** [comment]
Closing as this enhancement request needs more information and further API design information
