### ISSUE TITLE
ENH:Possible expansion of codespell to more file types

### ISSUE THREAD

**Issue by PApostol** [pandas-dev/pandas#44045]
At the moment, [codespell](https://github.com/pandas-dev/pandas/blob/c30afb23dfa948e3b34b4d71abb16ce455012428/.pre-commit-config.yaml#L15-L20) is enabled only for the following file types: `python, rst, markdown`

As a consequence, typos in various other file types can easily slip through (see #44043 as an example).

Could the expansion of codespell to more file types be beneficial?

**Comment by luke396** [comment]
I am not quite sure if the changes mentioned here are necessary now, and if so, can I suggest a pr.
