### ISSUE TITLE
BUG: CI cannot create benchmark environments with Cython < 0.29.24

### ISSUE THREAD

**Issue by attack68** [pandas-dev/pandas#44067]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
asv continuous -f 1.1 -E virtualenv upstream/master HEAD -b style.Render

RuntimeError: Cannot cythonize with old Cython version (0.29.21 installed, needs 0.29.24)
```

### Issue Description

Needed to update `asv.conf.json` to get this to work.

### Expected Behavior

probably need to update dependency verisons.

### Installed Versions

master at 17 Oct.

**Comment by simonjayhawkins** [comment]
benchmarks for previous versions are run from master so fix does not need backport.
