### ISSUE TITLE
Add Support For Reading XBRL Files in Pandas

### ISSUE THREAD

**Issue by cancan101** [pandas-dev/pandas#4407]
XBRL (http://en.wikipedia.org/wiki/XBRL) is the standard format for financial filings.

As of 2009, the SEC requires companies to file in XBRL format (http://xbrl.sec.gov/)

**Comment by jorisvandenbossche** [comment]
I personally think this would be out of scope for core pandas, therefore closing this. But it would certainly make for a nice standalone package if someone is interested.
