### ISSUE TITLE
ENH pd.ExcelFile new method to read all sheets

### ISSUE THREAD

**Issue by wpriddy** [pandas-dev/pandas#44168]
#### Is your feature request related to a problem?

pd.ExcelFile lists the sheet names but does not read the book on instantiation. This is not a problem but makes front-end code necessary to access this information longer than it needs to be. 

Current way to access a sheet:

file = pd.ExcelFile("./foo.xlsx")

pd.read_excel(file, sheet_name)

#### Describe the solution you'd like

I would like pd.ExcelFile to either have a new method or attribute that reads all sheets as data frames on call or to read all sheets on instantiation and be available as a property. 

#### API breaking implications

This would add a new method or attribute to an existing class.

#### Describe alternatives you've considered

Alternatives include putting this functionality on the front-end user to implement. However, since this seems to fit as a core functionality, I request that it is added to the source code. 

#### Additional context

Current way to read all sheets:

file = pd.ExcelFile("./foo.xlsx")

dfs = {sheet: pd.read_excel(file, sheet) for sheet in file.sheet_names}

```python
def sheets(self):

      return {sheet: read_excel(self._io, sheet) for sheet in self._read.sheet_names}

```

**Comment by lithomas1** [comment]
Doesn't ``pd.read_excel`` return a dict of all the sheets that you can iterate over?

**Comment by wpriddy** [comment]
You can pass a parameter of "sheet_name=None" to read_excel to get all sheets as dictionary but not ExcelFile.

**Comment by rhshadrach** [comment]
@wpriddy - can you detail why you're needing to use ExcelFile over read_excel?

**Comment by wpriddy** [comment]
No good reason, I was unaware of sheet_name = None. I previously used excel_file and had to use dict  comprehension to read all sheets.

**Comment by wpriddy** [comment]
It may be nice to have that functionality in both, but not necessary. How do I close?
