### ISSUE TITLE
DOC: var and std missing examples

### ISSUE THREAD

**Issue by AnshuTrivedi** [pandas-dev/pandas#44162]
### 

- [X] I have checked that the issue still exists on the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.var.html
https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.std.html

![Screenshot (1178)](https://user-images.githubusercontent.com/47869948/138578381-f8777eb1-2ebc-46cc-a503-1d4586cdd348.png)

### Documentation problem

In all other APIs in DataFrame at least one example is given for better understanding.
I believe, function description is also available in notebooks but not any example.
It's good to have one example for mentioned APIs.

### Suggested fix for documentation

Fix: Use of atleast one example for better undertanding of function.
It's better because function description along with example creates clarity of its use and implimentation.

**Comment by MarcoGorelli** [comment]
`std` is done in #44226, so there's still space for a PR for `var`
