### ISSUE TITLE
BUG: .resample(...).sum() incorrect result for time intervals for missing and NaN data

### ISSUE THREAD

**Issue by iansheng** [pandas-dev/pandas#44188]
#### Is your feature request related to a problem?

No.

#### Describe the solution you'd like

 I'm using `pd.DataFrame.resample` for stats. There's a piece of data, and I'd like to be able to count the totals by time interval. However, I note that if there is no data or the data is `NaN` in a certain time period, the total value of the time period will be `0`, which is not my expectation because I am **confused** as to whether there is data in this interval. 

```shell
>>> import pandas as pd

>>> index = pd.date_range('1/1/2000', periods=5, freq='T')
>>> series = pd.Series(1, index=index)
>>> series.pop('2000-01-01 00:01:00')
>>> series['2000-01-01 00:03:00'] = None
>>> print(series.resample('T').sum())
2000-01-01 00:00:00    1.0
2000-01-01 00:01:00    0.0
2000-01-01 00:02:00    1.0
2000-01-01 00:03:00    0.0
2000-01-01 00:04:00    1.0
Freq: T, dtype: float64
```

Is it possible to exclude time intervals for missing data from the statistical results or to present them as `NaN`? As follows:

exclude :

```shell
2000-01-01 00:00:00    1.0
2000-01-01 00:02:00    1.0
2000-01-01 00:04:00    1.0
Freq: T, dtype: float64
```

or present as `NaN`:

```shell
2000-01-01 00:00:00    1.0
2000-01-01 00:01:00    NaN
2000-01-01 00:02:00    1.0
2000-01-01 00:03:00    NaN
2000-01-01 00:04:00    1.0
Freq: T, dtype: float64
```

#### API breaking implications

This will change how a Resampler behaves when it encounters the sum method.

**Comment by mroeschke** [comment]
pandas follows the numpy convention of the sum of an empty array (or resample group) to be 0 to this cannot change

```
In [1]: np.array([]).sum()
Out[1]: 0.0
```

But I would expect `2000-01-01 00:03:00    NaN` instead of `2000-01-01 00:03:00    0` since the sum of an array with NaN is NaN

**Comment by iansheng** [comment]
@mroeschke Thanks for replying. Now that you mention pandas follow the numpy, I compared Series and ndarray. And the results are as follows:
```
arr = np.array([1, np.NAN])
ser = pd.Series([1, np.NAN])
```
Result:
```
arr + 10 = [11. nan]
ser + 10 ：
0    11.0
1     NaN
dtype: float64
arr.sum() = nan
ser.sum() = 1.0
```
In Pandas, the function `+`  is the same as that in Numpy. But the function `sum()` deal `NAN` as `0`, which is different from  that in Numpy. Why? Is this a specific strategy?

**Comment by jreback** [comment]
we have a min_count parameter to control this

this is a really long debate so please look at the issue tracker if you want more context
