### ISSUE TITLE
BUG: Multiple Styler.format calls not working

### ISSUE THREAD

**Issue by mvinoba** [pandas-dev/pandas#44184]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame({'a': [1, 2.5, 3, 5.7], 'b': [1.11, -2.7, -5.9, 10]})
def color_cell(cell):
    if float(cell) > 0:
        return "color: #4472c4"
    if float(cell) < 0:
        return "color: #ff0000"
df = df.style.applymap(color_cell, subset=["a", "b"])

df = df.format({"a": "{:.2%}"})
df

df = df.format({"b": "{:.2f}"})
df
```

### Issue Description

Multiple `.format` assignments are not applying to every column it gets called. 

Prior to version 1.3.x (I've tested in 1.2.3), it had the expected behaviour described below and since I could not find this change in the release notes I am opening this issue.

![image](https://user-images.githubusercontent.com/19884360/138792506-53bf9f01-04e3-43a6-ab42-5526ae12ab0c.png)

### Expected Behavior

I would expect that multiple `.format` calls worked the same as calling one `.format` with just one dictionary:

![image](https://user-images.githubusercontent.com/19884360/138792331-2046de6c-e49a-4175-90f9-7fd203bffdaf.png)

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.9.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 11, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : English_United States.1252

pandas           : 1.3.4
numpy            : 1.20.3
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.1
setuptools       : 56.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.9.1 (dt dec pq3 ext lo64)
jinja2           : 3.0.1
IPython          : 7.23.1
pandas_datareader: 0.9.0
bs4              : 4.9.3
bottleneck       : None
fsspec           : 2021.06.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.2
numexpr          : None
odfpy            : None
openpyxl         : 3.0.8
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.3
sqlalchemy       : 1.4.22
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
</details>

**Comment by mroeschke** [comment]
Closing as this is changed, documented behavior.
