### ISSUE TITLE
ENH: Set default storage for strings globaly

### ISSUE THREAD

**Issue by taoufik07** [pandas-dev/pandas#44203]
#### Is your feature request related to a problem?

As far as I know, the only way to use the new string dtypes, is to set them manually either via the param `dtype` if it's supported or using `astype` otherwise the string will be stored as `object`.

#### Describe the solution you'd like

I'm aware that the string dtype is experimental, but it would be easy for us to play with it in large projects if there's a way to change the default behavior globally which can also be used in the future to set the storage for `StringDtype`.

**Comment by lithomas1** [comment]
Hmmm. I don't think we have a way to specify to infer the string datatype in the dataframe constructor.
I guess you could call ``.convert_dtypes()`` on the frame afterwards which would convert string columns to the string datatype and leave the other columns alone, if that's a suitable workaround.

**Comment by mroeschke** [comment]
There is `future.infer_string` so I think we can close this out
