### ISSUE TITLE
BUG: test_date_col_as_index_col[pyarrow] failing locally with pyarrow 6.0.0

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#44231]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
>   raise_assert_detail(obj, msg, lobj, robj, index_values=index_values)
E   AssertionError: DataFrame.iloc[:, 1] (column name="X2") are different
E   
E   DataFrame.iloc[:, 1] (column name="X2") values are different (100.0 %)
E   [index]: [1999-01-27T19:00:00.000000000, 1999-01-27T20:00:00.000000000, 1999-01-27T21:00:00.000000000, 1999-01-27T21:00:00.000000000, 1999-01-27T22:00:00.000000000]
E   [left]:  [18:56:00, 19:56:00, 20:56:00, 21:18:00, 21:56:00]
E   [right]: [ 18:56:00,  19:56:00,  20:56:00,  21:18:00,  21:56:00]
```

### Issue Description

cc @jorisvandenbossche 

### Expected Behavior

NA

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by lithomas1** [comment]
I think this happens since pyarrow is now auto inferring datetimes, instead of the previous behavior of reading it as a string. Unfortunately, I don't think there is a way to disable this behavior.

**Comment by jorisvandenbossche** [comment]
Indeed, arrow started to infer more types, but in this case it's actually about the "time" column (not the datetime column), and I also don't think there is a way to disable this right now. I will do a PR to update the test to follow that new behaviour.
