### ISSUE TITLE
ENH: Option to store dataset creation/modification times with `to_hdf`.

### ISSUE THREAD

**Issue by rickhg12hs** [pandas-dev/pandas#44246]
#### Is your feature request related to a problem?

"I wish I could use pandas to" store a `DataFrame` with `to_hdf` and optionally include the datetime of dataset creation/modification.

#### Describe the solution you'd like

`DataFrame.to_hdf` should have an option that will store the datetime of dataset creation/modification.

[docstring addition]
```
with_datetime : bool, default False
    Stores `datetime` when dataset is written
```
#### API breaking implications

Shouldn't break anything.

#### Describe alternatives you've considered

A separate "metafile" that the user would need to write with dataset creation/modification datetimes.

#### Additional context

With the possibility of rewriting datasets, having the creation and modification times of the dataset in the HDF5 file would help to inform HDF5 file readers/users of updated datasets.

```python
my_df.to_pdf(..., with_datetime=True, ...)
...
my_df_read = pd.read_hdf(store_file, key=key_value, mode="r")
print(my_df_read.ctime) # None or datetime
print(my_df_read.mtime) # None or datetime
...
my_df_read.info() # Would also show datetimes if present
```

**Comment by mroeschke** [comment]
Thanks for the suggestion.

My immediate reaction is that this seems out of scope for pandas as this problem doesn't seem entirely specific to HDF5 files (same can be said of CSV files for example), and alternate solutions like the one you provided, naming the file with timestamps, using the filesystem to keep track of time are valid solutions.

**Comment by rickhg12hs** [comment]
Understood.

Thanks for the consideration.

**Comment by mroeschke** [comment]
Closing as this issue hasn't gotten much traction over the years
