### ISSUE TITLE
DOC: Fix inconsistency in user_guide/options.html

### ISSUE THREAD

**Issue by rs2** [pandas-dev/pandas#44250]
### 

- [X] I have checked that the issue still exists on the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html

### Documentation problem

The narrative mentions `e.g. display.max_colwidth, display.max_rows, display.max_columns`, but the example references `pd.get_option("column")`

### Suggested fix for documentation

Perhaps, `pd.get_option("max")` would be more intuitive.

**Comment by attack68** [comment]
if you check master and and the dev docs 1.4.0 you will find this has been changed already a couple months ago.

**Comment by mroeschke** [comment]
Yup, this looks correct on the dev docs and should reflect on stable when 1.4 is released. Closing
