### ISSUE TITLE
BUG: Pandas-1.3.4 (and1.3.2, and 1.3.1) do not work well with seaborn-0.11.2 on PyPy-3.7-7.3.7 , but pandas-1.2.5 does

### ISSUE THREAD

**Issue by stonebig** [pandas-dev/pandas#44253]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

with pypy3.7-v7.3.7-win64.zip and wheels provided per cgohlke: 
- the following example works with seaborn-0.11.2 (and 0.11.1) and Pandas-1.2.5,
- but fails with Pandas-1.3.1, 1.3.2 and latest 1.3.4

````python

import seaborn as sns
sns.set()
df = sns.load_dataset("iris")
sns.pairplot(df, hue="species", height=1.5)
````
 

### Issue Description

jupyterlab kernel crashes and restarts, 

- a pandas_libs.parser.TextReader is blamed, but PyPy says "invalid usage of a dying CPython object"
- looking at seaborn code, seaborn is just calling pandas , so doesn't seem guilty of anything apparently
https://github.com/mwaskom/seaborn/issues/2688

https://github.com/mwaskom/seaborn/blob/master/seaborn/utils.py#L586

![image](https://user-images.githubusercontent.com/4312421/139593153-018bb0c3-c915-412a-94b9-3c579cec0362.png)

![image](https://user-images.githubusercontent.com/4312421/139592837-ad7019e5-9a63-4db4-846c-f4ef8d927147.png)

### Expected Behavior

a typical seaborn graph, (when pandas-1.2.5)
![image](https://user-images.githubusercontent.com/4312421/139592813-30b6f6ba-ee79-45ce-bc85-e3abbca8b4f0.png)

also this pure pandas one works
````
import pandas as pd
df = pd.read_csv('~/seaborn-data/iris.csv',index_col=False)

import pandas as pd
import altair as alt

alt.Chart(df).mark_bar().encode(
    x=alt.X('sepal_length', bin=alt.Bin(maxbins=50)),
    y='count(*):Q',
    color='species:N',
    #column='species',
).interactive()
````
![image](https://user-images.githubusercontent.com/4312421/139593375-f30f2600-4b4d-424d-ac47-c43e17f3591c.png)

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.7.12.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19043
machine          : AMD64
processor        : Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.3.4
numpy            : 1.21.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 58.3.0
Cython           : 0.29.24
pytest           : 6.2.5
hypothesis       : 6.24.0
sphinx           : 4.2.0
blosc            : 1.10.6
feather          : None
xlsxwriter       : 3.0.1
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.2
IPython          : 7.29.0
pandas_datareader: 0.10.0
bs4              : 4.10.0
bottleneck       : 1.3.2
fsspec           : 2021.10.1
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : 1.4.26
tables           : None
tabulate         : 0.8.9
xarray           : 0.19.0
xlrd             : None
xlwt             : None
numba            : None
</details>

**Comment by lithomas1** [comment]
Thanks for reporting this. We have 0 testing on PyPy unfortunately(adding that testing is in a separate issue, and last time I checked we had a ton of segfaults/test failures). However, if you can find a patch for this, we would be happy to take it.
