### ISSUE TITLE
ENH: remove moto from requirements-dev.txt

### ISSUE THREAD

**Issue by suliuzh** [pandas-dev/pandas#44268]
#### Is your feature request related to a problem?

Hi
There seems to be no code in the source code that uses "moto". But in “requirements-dev.txt”, "moto" is still listed as a dependency.
The following commit removed "import moto" in "pandas/tests/io/conftest.py ".
[TST: make it possible to run tests without moto installed ](https://github.com/pandas-dev/pandas/commit/c753e1e08b01a438aaa252327de046109bf4bcfd)
So should it be removed from "requirements-dev.txt"?

**Comment by lithomas1** [comment]
@suliuzh Thanks for asking but I think it is used in this fixture. (see line 73)
https://github.com/pandas-dev/pandas/blob/059c8bac51e47d6eaaa3e36d6a293a22312925e6/pandas/tests/io/conftest.py#L43-L92
