### ISSUE TITLE
BUG: `groupby(level=).shift(axis=1)` changes order of original index

### ISSUE THREAD

**Issue by prutskov** [pandas-dev/pandas#44269]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({'a': [2,1,2,1], 'b': [7,2,3,9], 'c': [2.0, 3.0, 1.1, 7.8]})
df = df.set_index('a')

result = df.groupby(level=0).shift()
result_axis_1 = df.groupby(level=0).shift(axis=1)

print(df)
print(result)
print(result_axis_1)
```

### Issue Description

Ouput:
```bash
   b    c
a
2  7  2.0
1  2  3.0
2  3  1.1
1  9  7.8
     b    c
a
2  NaN  NaN
1  NaN  NaN
2  7.0  2.0
1  2.0  3.0
    b  c
a
2 NaN  7
2 NaN  3
1 NaN  2
1 NaN  9
```

We can see that `groupby.shift(axis=1)` breaks the original order of values in index. 

The same behavior we can see for `groupby.apply(lambda df: df.shift())` function:

```python
import pandas as pd

df = pd.DataFrame({'a': [2,1,2,1], 'b': [7,2,3,9], 'c': [2.0, 3.0, 1.1, 7.8]})
df = df.set_index('a')

result = df.groupby(level=0).shift()
result_apply = df.groupby(level=0).apply(lambda df: df.shift())

print(df)
print(result)
print(result_apply)
```

Output:
```bash
   b    c
a
2  7  2.0
1  2  3.0
2  3  1.1
1  9  7.8
     b    c
a
2  NaN  NaN
1  NaN  NaN
2  7.0  2.0
1  2.0  3.0
     b    c
a
2  NaN  NaN
2  7.0  2.0
1  NaN  NaN
1  2.0  3.0
```
We get different order of index for `shift`/`apply(shift)`

### Expected Behavior

```bash
   b    c
a
2  7  2.0
1  2  3.0
2  3  1.1
1  9  7.8
     b    c
a
2  NaN  NaN
1  NaN  NaN
2  7.0  2.0
1  2.0  3.0
    b  c
a
2 NaN  7
1 NaN  2
2 NaN  3
1 NaN  9
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.8.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-65-generic
Version          : #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US
LOCALE           : en_US.ISO8859-1

pandas           : 1.3.4
numpy            : 1.21.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : 0.4.1
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.2
IPython          : 7.28.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 2021.10.1
fastparquet      : None
gcsfs            : None
matplotlib       : 3.2.2
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : 0.15.0
pyarrow          : 6.0.0
pyxlsb           : None
s3fs             : 2021.10.1
scipy            : 1.7.1
sqlalchemy       : 1.4.26
tables           : 3.6.1
tabulate         : None
xarray           : 0.19.0
xlrd             : 2.0.1
xlwt             : None
numba            : None

</details>

**Comment by rhshadrach** [comment]
axis=1 in this method is now deprecated. Closing.
