### ISSUE TITLE
BUG/API: Categorical.map & CategoricalIndex.map have no 'na_action' kwarg

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#44279]
- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.
- [X] I have confirmed this bug exists on the master branch of pandas.

**Comment by jbrockmendel** [comment]
xref #22527

**Comment by topper-123** [comment]
I'd like to take this on, if that's ok.

**Comment by jbrockmendel** [comment]
Go for i!
