### ISSUE TITLE
Add stack argument to str.findall

### ISSUE THREAD

**Issue by hayd** [pandas-dev/pandas#4428]
Some of the string methods return a Series of lists (e.g. findall) which isn't that convenient for doing more analysis:

```
df = pd.DataFrame([['@a @b'], ['@a'], ['@c']], columns=['tweets'])
at_mentions = df.tweets.str.findall('@[a-zA-Z0-9_]+')

In [3]: at_mentions
Out[3]:
0    [@a, @b]
1        [@a]
2        [@c]
Name: tweets, dtype: object
```

I think it would be nice to be able to stack the results:

```
In [4]: at_mentions.apply(pd.Series).stack()
Out[4]:
tweets
1       0    @a
        1    @b
2       0    @a
3       0    @c
dtype: object
```

_see this [SO answer](http://stackoverflow.com/a/17989510/1240268)_

Could just do it directly like that, or perhaps make more efficient. Thoughts?

**Comment by mroeschke** [comment]
I think `explode` solves this use case. Happy to reopen if this doesn't solve the original use case.

```
In [7]: at_mentions.explode()
Out[7]:
0    @a
0    @b
1    @a
2    @c
Name: tweets, dtype: object
```
