### ISSUE TITLE
BUG: Timestamp.floor() method not able to handle DST change in local time

### ISSUE THREAD

**Issue by m-kremer** [pandas-dev/pandas#44287]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd

# Example 1: Timestamp('2021-10-31 02:30:00+0200', tz='Europe/Amsterdam')
timestamp = (pd.to_datetime('2021-10-31 00:30:00')
             .tz_localize('UTC')
             .tz_convert('Europe/Amsterdam'))

ts_hour = timestamp.floor('60T')

# Returns: AmbiguousTimeError
# Expected: Timestamp('2021-10-31 02:00:00+0200', tz='Europe/Amsterdam')

# Example 2: Timestamp('2021-10-31 02:30:00+0100', tz='Europe/Amsterdam')
timestamp = (pd.to_datetime('2021-10-31 01:30:00')
             .tz_localize('UTC')
             .tz_convert('Europe/Amsterdam'))

ts_hour = timestamp.floor('60T')

# Returns: AmbiguousTimeError
# Expected: Timestamp('2021-10-31 02:00:00+0100', tz='Europe/Amsterdam')
```

### Issue Description

The timestamp is in local time, so pandas should how enough information to know how to round it down to the whole hour. However, it does not recognize this and asks for an ambiguous argument. 

Adding ambiguous=True does not provide the desired result. 

### Expected Behavior

See reproducible example

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.9.2.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Dutch_Netherlands.1252

pandas           : 1.3.4
numpy            : 1.21.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 58.4.0
Cython           : None
pytest           : 6.2.4
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.6 (dt dec pq3 ext lo64)
jinja2           : 2.11.3
IPython          : 7.29.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.2
numexpr          : None
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : 1.4.13
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by mroeschke** [comment]
It appears the `ambiguous` keyword will give you the correct result?

```
In [12]: timestamp = (pd.to_datetime('2021-10-31 00:30:00')
    ...:              .tz_localize('UTC')
    ...:              .tz_convert('Europe/Amsterdam'))
    ...:
    ...: ts_hour = timestamp.floor('H', ambiguous=True)

In [13]: ts_hour
Out[13]: Timestamp('2021-10-31 02:00:00+0200', tz='Europe/Amsterdam')

In [14]: timestamp = (pd.to_datetime('2021-10-31 01:30:00')
    ...:              .tz_localize('UTC')
    ...:              .tz_convert('Europe/Amsterdam'))
    ...:
    ...: ts_hour = timestamp.floor('60T', ambiguous=False)

In [15]: ts_hour
Out[15]: Timestamp('2021-10-31 02:00:00+0100', tz='Europe/Amsterdam')
```

**Comment by m-kremer** [comment]
Your example is producing the desired result, but it seems inconsistent to me. There seems to be no way of knowing upfront whether or not to use the ambiguous=True argument or not, is there? 

And then again, the argument should not be needed in this case; there is no ambiguity here...

**Comment by mroeschke** [comment]
The flooring is done in local time, so `02:30:00 floor 60T = 2:00:00`. Since this is on 2021-10-31, it's ambiguous whether this is `+0200` or `+0100`.

**Comment by m-kremer** [comment]
The timestamp includes timezone information, so I would expect that to be taken into account, but I understand its not. Is that something that could potentially be improved?

**Comment by jreback** [comment]
@m-kremer once u floor the time it's not clear which fold it's in and the result could be 2am or 1am; it's a user decision here

**Comment by m-kremer** [comment]
That's not true if you would take tz info into account: 

`02:30:00+0200 floor 60T = 02:00:00+0200`

`02:30:00+0100 floor 60T = 02:00:00+0100`

No ambiguity here...

**Comment by jreback** [comment]
@m-kremer and sure for a subset of operations this may actually work. but as a general rule, e.g. arithmetic (+/-) and rounding operations you inevitably get to an ambiguous state because working *with* a timezone in an operation has so many edge cases. The general rule is easy to understand & test (operate in *local* non-tz aware time)

**Comment by m-kremer** [comment]
Thanks @jreback, now I better understand why its working this way. 

This issue can be closed... :)
