### ISSUE TITLE
ENH: Define columns to exclude/skip when reading data from file

### ISSUE THREAD

**Issue by AYSung** [pandas-dev/pandas#44297]
#### Is your feature request related to a problem?

When reading a csv file (or other form of table) into a DataFrame, it would be convenient to be able to directly specify columns to exclude rather than columns to include. This happens a lot when working with data that have a variable number of columns, but a fixed set of columns that should be ignored.

#### Describe the solution you'd like

`pandas.read_csv` and other read functions in the `readers.py` module should get a new parameter `skipcols` that would essentially be the inverse of the `usecols` parameter.

```
skipcols : list-like, optional
    Return a subset of the columns excluding the specified columns. If list-like, 
    all elements must either be positional (i.e. integer indices into the document
    columns) or strings that correspond to column names provided either by the
    user in `names` or inferred from the document header row(s). For example, a
    valid list-like `skipcols` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
    Element order is ignored, so ``skipcols=[0, 1]`` is the same as ``[1, 0]``.
```

A callable doesn't make as much sense here since it would be the same as supplying a callable to `usecols` with a `not`.

#### API breaking implications

I don't think this would conflict with the existing API, though it would need to be mutually exclusive with `usecols`

#### Describe alternatives you've considered

This could be accomplished using `usecols=lambda x: x not in columns_to_skip` but I think the syntax would be more clear and straightforward as `skipcols=columns_to_skip`.

**Comment by jreback** [comment]
https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#column-and-index-locations-and-names

this is very easy to do as usecols accepts a callable 

would take an enhancement to the docs to add an even more explicit example of excluding cols this way

**Comment by AYSung** [comment]
Fair enough!
