### ISSUE TITLE
QST: Output all supported dtypes directly from Pandas?

### ISSUE THREAD

**Issue by Shellcat-Zero** [pandas-dev/pandas#44299]
### 

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/q/69776073/3433625

### Question about pandas

I was hoping it might be possible to have the Pandas module output all of its supported dtypes, but I haven't found any documentation mentioning how to do this, although I have seen the [utilities documentation](https://pandas.pydata.org/docs/reference/general_utility_functions.html) and the [documentation explaining Pandas dtypes](https://pandas.pydata.org/pandas-docs/stable/user_guide/basics.html#dtypes).

I need to create some artificial datasets in Pandas dataframes which make use of all possible dtypes in order to test another software application which processes dataframes based on the dtypes existing in those dataframes. At present, it looks like I have to look at the documentation and hardcode those dtypes. The primary test case I'm trying to build is a single dataframe featuring all possible dtypes in it. If anyone can shed some light on how to get all possible dtypes from Pandas and generate data for those dtypes, it would be much appreciated.

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/blob/master/pandas/conftest.py has fixtures for all dtypes.
