### ISSUE TITLE
DOC: DataFrame.groupby().apply()

### ISSUE THREAD

**Issue by k-dominik** [pandas-dev/pandas#44318]
### 

- [X] I have checked that the issue still exists on the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.core.groupby.GroupBy.apply.html?highlight=groupby%20apply#pandas.core.groupby.GroupBy.apply

### Documentation problem

Documentation mentions that `func` is called twice on the first item. This [was fixed in 0.25](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.25.0.html#groupby-apply-on-dataframe-evaluates-first-group-only-once). I was a bit unsure after reading the documentation, so I tried the example from the 0.25 release notes with all versions available on conda (for Python 3.7) and it seems the function is not called twice on any item.

For reference here is a table of the results. In the table the "count" indicates how often the function was called (same example as in the 0.25 release notes). 3 means the some item is evaluated twice, 2 means that weird behavior is gone...

<details>

| build                    |   count |
|:-------------------------|--------:|
| 0.23.4=py37h637b7d7_1000 |       3 |
| 0.23.4=py37hf8a1672_0    |       3 |
| 0.24.0=py37hf484d3e_0    |       3 |
| 0.24.1=py37hf484d3e_0    |       3 |
| 0.24.2=py37hb3f55d8_0    |       3 |
| 0.24.2=py37hb3f55d8_1    |       3 |
| 0.24.2=py37hf484d3e_0    |       3 |
| 0.25.0=py37hb3f55d8_0    |       2 |
| 0.25.1=py37hb3f55d8_0    |       2 |
| 0.25.2=py37hb3f55d8_0    |       2 |
| 0.25.3=py37hb3f55d8_0    |       2 |
| 1.0.0=py37hb3f55d8_0     |       2 |
| 1.0.1=py37hb3f55d8_0     |       2 |
| 1.0.2=py37h0da4684_0     |       2 |
| 1.0.3=py37h0da4684_0     |       2 |
| 1.0.3=py37h0da4684_1     |       2 |
| 1.0.4=py37h0da4684_0     |       2 |
| 1.0.5=py37h0da4684_0     |       2 |
| 1.1.0=py37h3340039_0     |       2 |
| 1.1.1=py37h3340039_0     |       2 |
| 1.1.2=py37h3340039_0     |       2 |
| 1.1.3=py37h3340039_0     |       2 |
| 1.1.3=py37h9fdb41a_1     |       2 |
| 1.1.3=py37h9fdb41a_2     |       2 |
| 1.1.3=py37hb33c840_2     |       2 |
| 1.1.4=py37h10a2094_0     |       2 |
| 1.1.5=py37hdc94413_0     |       2 |
| 1.2.0=py37h40f5888_1     |       2 |
| 1.2.0=py37hdc94413_0     |       2 |
| 1.2.0=py37hdc94413_1     |       2 |
| 1.2.1=py37h40f5888_0     |       2 |
| 1.2.1=py37hdc94413_0     |       2 |
| 1.2.2=py37h40f5888_0     |       2 |
| 1.2.2=py37hdc94413_0     |       2 |
| 1.2.3=py37h40f5888_0     |       2 |
| 1.2.3=py37hdc94413_0     |       2 |
| 1.2.4=py37h219a48f_0     |       2 |
| 1.2.4=py37h40f5888_0     |       2 |
| 1.2.5=py37h219a48f_0     |       2 |
| 1.2.5=py37h40f5888_0     |       2 |
| 1.3.0=py37h219a48f_0     |       2 |
| 1.3.1=py37h219a48f_0     |       2 |
| 1.3.1=py37h40f5888_0     |       2 |
| 1.3.2=py37h40f5888_0     |       2 |
| 1.3.2=py37he8f5f7f_0     |       2 |
| 1.3.3=py37h40f5888_0     |       2 |
| 1.3.3=py37he8f5f7f_0     |       2 |
| 1.3.4=py37h40f5888_0     |       2 |
| 1.3.4=py37he8f5f7f_0     |       2 |

</details>

### Suggested fix for documentation

I'd propose to delete the following text:

> In the current implementation apply calls func twice on the first group to decide whether it can take a fast or slow code path. This can lead to unexpected behavior if func has side-effects, as they will take effect twice for the first group.

CC: @stuarteberg

**Comment by jreback** [comment]
we don't include older version changes like this

pls update your proposed w/o this

**Comment by k-dominik** [comment]
@jreback, thank you for having a look. In this case I changed my proposal to remove that note completely.

**Comment by jreback** [comment]
PR to fix welcome
