### ISSUE TITLE
BUG: an error with to_datetime() conversion

### ISSUE THREAD

**Issue by kyrgyzov** [pandas-dev/pandas#44320]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
pandas as pd

# load data
p2file = 'test_data.xlsx'
df = pd.ExcelFile(p2file).parse()
print(df.head())
print(df.dtypes)
```

               Date/Time          ch1     ch2
0  13:00:00 16-jul.-2020 -2202.969155 -999.25
1  13:00:01 16-jul.-2020 -2202.969155 -999.25
2  13:00:02 16-jul.-2020 -2202.969155 -999.25
3  13:00:03 16-jul.-2020 -2202.969155 -999.25
4  13:00:04 16-jul.-2020 -2202.969155 -999.25
Date/Time     object
ch1          float64
ch2          float64
dtype: object

```#convert a column in datetime format
dt = pd.to_datetime(df.iloc[:,0])
print(dt.head())
print(dt.dtypes)
```

0   2021-07-16 13:00:00-20:20
1   2021-07-16 13:00:01-20:20
2   2021-07-16 13:00:02-20:20
3   2021-07-16 13:00:03-20:20
4   2021-07-16 13:00:04-20:20
Name: Date/Time, dtype: datetime64[ns, pytz.FixedOffset(-1220)]
datetime64[ns, pytz.FixedOffset(-1220)]
```


### Issue Description

In some of our xlsx files we keep date/time information in  'h: m: s day-month-year'  format (date after time), 
where day-month-year were separated by a  ‘-’ symbol.

Pandas decided to subtract  ‘year’ from ‘h: m: s’ and to present it as a time offset.

To avoid this collision , we need  to replace the symbol ’-‘ by ‘/’.
Now, it works as desired.

if we keep date/time information in  'day-month-year h: m: s' format (time after date), we do not have this issue. 




### Expected Behavior

```#process datetime format
df.iloc[:,0] = df.iloc[:,0].str.replace('-','/')
print(df.head())
print(df.dtypes)
```

               Date/Time          ch1     ch2
0  13:00:00 16/jul./2020 -2202.969155 -999.25
1  13:00:01 16/jul./2020 -2202.969155 -999.25
2  13:00:02 16/jul./2020 -2202.969155 -999.25
3  13:00:03 16/jul./2020 -2202.969155 -999.25
4  13:00:04 16/jul./2020 -2202.969155 -999.25
Date/Time     object
ch1          float64
ch2          float64
dtype: object

```#convert a column in datetime format
dt = pd.to_datetime(df.iloc[:,0])
print(dt.head())
print(dt.dtypes)
```

0   2020-07-16 13:00:00
1   2020-07-16 13:00:01
2   2020-07-16 13:00:02
3   2020-07-16 13:00:03
4   2020-07-16 13:00:04
Name: Date/Time, dtype: datetime64[ns]
datetime64[ns]

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.8.12.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : 
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : fr_FR.cp1252

pandas           : 1.3.4
numpy            : 1.21.2
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.29.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

**Comment by jreback** [comment]
use the format= argument

converting malformed strings to dates can result in malformed output

**Comment by kyrgyzov** [comment]
unfortunately, we can't predefine format since we process files from different sources and do not know the prior date/time format.
the # of xlsx files > 1000, so we just leave the format by default.

**Comment by mroeschke** [comment]
Alternatively, you can pass your own custom `date_parser` to have function that handles multiple formats
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html
