### ISSUE TITLE
to_csv() enconding option "utf-8-BOM"

### ISSUE THREAD

**Issue by martino-vic** [pandas-dev/pandas#44323]
Hey, could there be a way to save csvs as "utf-8-BOM" encoded? Because Excel needs the BOM to open csvs correctly. Everytime I save a csv with Pandas I have to open it with Notepad++ and change the encoding from utf-8 to uf8-BOM so that I can open it with Excel. Thanks in advance.

**Comment by twoertwein** [comment]
If utf-8-BOM were a [valid python encoding](https://docs.python.org/3/library/codecs.html#standard-encodings), `to_csv` would/should support it.

I think windows uses cp1252 by default. Does `pd.DataFrame().to_csv("test.csv", encoding="cp1252")` work nicely with excel/notepad++?

**Comment by bluss** [comment]
`utf_8_sig` is in the encoding list and it seems to work for this.

**Comment by martino-vic** [comment]
```utf_8_sig``` worked perfectly, thanks! :))
