### ISSUE TITLE
DOC: Clarify docs for groupby when passed a list with length equal to length of axis

### ISSUE THREAD

**Issue by asishm** [pandas-dev/pandas#44333]
### Documentation location

https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.groupby.html

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame([['a', 'b'], ['b', 'c']], columns=['foo', 'bar'])
df.groupby(['y', 'z']).first()

>>>
  foo bar
y   a   b
z   b   c
```

While it is mentioned in the user-guide, I think it would be clearer to include lists (along with the existing mention of the ndarray) to reflect that the values will be used as-is to determine the groups if the lengths match that of the selected axis.

**Comment by samukweku** [comment]
You are grouping by an array that is the same length as the dataframe. Groupby is not restricted to just columns

**Comment by asishm** [comment]
How does it align the index and why does it do so? The docs offer little clarity in this regard.

> by : mapping, function, label, or list of labels
Used to determine the groups for the groupby. If by is a function, it’s called on each value of the object’s index. If a dict or Series is passed, the Series or dict VALUES will be used to determine the groups (the Series’ values are first aligned; see .align() method). If an ndarray is passed, the values are used as-is to determine the groups. A label or list of labels may be passed to group by the columns in self. Notice that a tuple is interpreted as a (single) key.

**Comment by samukweku** [comment]
the dataframe is of length 2; a list of length 2 is passed - that's an exact match. The grouping is used as-is to split into different parts. The code below shows the pairing of the dataframe with the values in the list shared:

```py
In [6]: [*df.groupby(['y', 'z'])]
Out[6]: 
[('y',
    foo bar
  0   a   b),
 ('z',
    foo bar
  1   b   c)]
```

Let's look at a slightly larger dataframe:

```py
In [8]: df = pd.DataFrame({"foo": range(5), "bar":['a', 'b', 'c', 'd', 'e']})

In [9]: df
Out[9]: 
   foo bar
0    0   a
1    1   b
2    2   c
3    3   d
4    4   e

In [11]: df.groupby(['y','z', 'z', 'y', 'z'])
Out[11]: <pandas.core.groupby.generic.DataFrameGroupBy object at 0x7fbaaaf9b970>

In [12]: [*df.groupby(['y','z', 'z', 'y', 'z'])]
Out[12]: 
[('y',
     foo bar
  0    0   a
  3    3   d),
 ('z',
     foo bar
  1    1   b
  2    2   c
  4    4   e)]
```

The dataframe is of length 5, the grouping sequence is of length 5 as well; the pairing is as-is; you can imagine it as putting that grouping side by side with the dataframe before grouping : 

```py
df.assign(grouper = ['y','z', 'z', 'y', 'z'])
Out[14]: 
   foo bar grouper
0    0   a       y
1    1   b       z
2    2   c       z
3    3   d       y
4    4   e       z
```

Groupby is quite flexible ... but the summary is as long as the sequence(list/numpy array) shares the same length as the dataframe, the grouping(splitting) will be done based on the respective positions of the labels/values in the grouping sequence.

Hope that expalins much;  the devs will have a better understanding, and better wording too.

**Comment by asishm** [comment]
@samukweku Thanks for the detailed explanation! And I'm familiar with the `.groupby(ndarray)` construct. I was unable to connect that lists would also behave similarly given that lists are mentioned separately in the docs

What threw me off is that the docs for the ndarray part
> If an ndarray is passed, the values are used as-is to determine the groups. 
1. has no mention of lists also being treated similarly
2. has no mention of the length being equal to the length of the selected axis.

In addition this is also explicitly mentioned in the user guide 
![image](https://user-images.githubusercontent.com/1978117/140624156-c33c42bd-5c39-4aa9-890f-225d755bf0ca.png)


I'll change this to a doc issue.

**Comment by rhshadrach** [comment]
Thanks for the report! It seems the request here is to make 

> If an ndarray is passed, the values are used as-is to determine the groups.

into something like

> If a list or ndarray of length equal to the selected axis is passed, the values are used as-is to determine the groups.

Is that right? If so, +1 from me.

Perhaps it would also be helpful to modify the link to the User Guide in the Notes section of this docstring to point directly at

https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#splitting-an-object-into-groups

Off-topic, but it has been commented in other issues that putting the link to the User Guide in the Notes section is not very visible. Perhaps this visibility could be increased somehow, but that would be its own issue (impacting all docstrings) I think.

**Comment by asishm** [comment]
> If a list or ndarray of length equal to the selected axis is passed, the values are used as-is to determine the groups.

This is not entirely right. This only applies if the list elements don't corresponding to the column names.  i.e.

```py
In [74]: df = pd.DataFrame([['a', 'b'], ['b', 'c']], columns=['foo', 'bar'])
    ...: df.groupby(['foo', 'bar']).first()
Out[74]:
Empty DataFrame
Columns: []
Index: [(a, b), (b, c)]
```

I think your proposal is still better than what exists currently and I'd be ok with it. It would probably be better if the mapping section from the user guide could be added to the Notes section along with the link to the user-guide.
