### ISSUE TITLE
BUG/API: DataFrame.iloc[:, foo] = bar inplaceness?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#44353]
In 1.3.0 we made it so that `df["A"] = foo` *never* operates in-place (xref [whatsnew](https://github.com/pandas-dev/pandas/blob/master/doc/source/whatsnew/v1.3.0.rst#never-operate-inplace-when-setting-framekeys--values),  #33457) and *mostly* made it so that `df.loc[foo, bar] = baz` tries to operate in-place before falling back to casting (xref [whatsnew](https://github.com/pandas-dev/pandas/blob/master/doc/source/whatsnew/v1.3.0.rst#try-operating-inplace-when-setting-values-with-loc-and-iloc), https://github.com/pandas-dev/pandas/issues/33457#issuecomment-660126628)

There are some remaining cases where .iloc and .loc do not try to set inplace.  This issue is to make sure we have consensus about changing/deprecating that behavior.  Most of the impacted test cases involve doing an astype, e.g.

```
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randn(4).reshape(2, 2), dtype=object)
df.iloc[:, 0] = df.iloc[:, 0].astype(np.float64)
```

ATM this changes df[0] to float64, i.e. is not inplace.

In this case, the user could/should do `df[0] = df[0].astype(np.float64)`.  But that approach runs into problems with either non-unique columns or setting a slice of columns `df.iloc[:, :2] = foo`

My thoughts are that 1) we should be consistent about inplace-ness, not special-case the API and 2) the use case here _is_ convenient.

Thoughts?

<b>update</b> Cataloguing issues/PRs where this behavior we implemented apparently-intentionally
#29393 (#25495)
#6149
#6159  BUG/API: df['col'] = value and df.loc[:,'col'] = value are now completely equivalent

<b>update 2</b> Cataloguing issues that appear to be caused by/related to this inconsistency
#20635 BUG: indexing with loc and iloc with list-likes and new dtypes do not change from object dtype
#24269 DataFrame.loc/iloc fails to update object with new dtype

**Comment by jbrockmendel** [comment]
cc @jreback @jorisvandenbossche @TomAugspurger discussed briefly on today's call could use your inputs

**Comment by jbrockmendel** [comment]
gentle ping @jreback a lot of indexing work hinges on whether we want to change this

**Comment by jreback** [comment]
API: df['col'] = value and df.loc[:,'col'] = value are now completely equivalent

i think these should be completely equivalent always
i always thought we did this

**Comment by jbrockmendel** [comment]
> i always thought we did this

Two problems here:

1) We don't have a way for users to do this setting that _is_ inplace.
2) it isn't actually completely equivalent.  If `value` has the same dtype as the existing column, it'll be inplace.

**Comment by jbrockmendel** [comment]
xref #15631

**Comment by jbrockmendel** [comment]
Marking as blocker for 1.4rc; we should make a decision about deprecation before then.

**Comment by jorisvandenbossche** [comment]
Personally I think I would like the consistency of ``.iloc[row_indexer, column_indexer]`` always being inplace. But if we do that, we should provide an alternative to achieve the same: setting a column using a positional index (with new values, not in place, like `df[label] = ..` but using an integer index instead of a label).  
Without the current `iloc` behaviour, this is not (easily) possible to do I think with our current APIs?

Also, if we change this, I think it should go with some deprecation cycle, since this was explicitly designed this way before (it's not that we are fixing a bug).

**Comment by jbrockmendel** [comment]
> Also, if we change this, I think it should go with some deprecation cycle, since this was explicitly designed this way before (it's not that we are fixing a bug).

Yah, that's why i'm pushing to get this done for 1.4 so we can enforce in 2.0.

> should provide an alternative to achieve the same: setting a column using a positional index (with new values, not in place, like df[label] = .. but using an integer index instead of a label).

Agreed.  Do you have any preferences on what that API would look like?  I think something like `df.iloc(axis=1)[foo] = bar` might work in theory (though i doubt we have good test coverage for that)

**Comment by jbrockmendel** [comment]
Turns out the `df.iloc(axis=1)[foo]=bar` doesn't work ATM bc of #45032

**Comment by jreback** [comment]
> Personally I think I would like the consistency of `.iloc[row_indexer, column_indexer]` always being inplace. But if we do that, we should provide an alternative to achieve the same: setting a column using a positional index (with new values, not in place, like `df[label] = ..` but using an integer index instead of a label). Without the current `iloc` behaviour, this is not (easily) possible to do I think with our current APIs?
> 
> Also, if we change this, I think it should go with some deprecation cycle, since this was explicitly designed this way before (it's not that we are fixing a bug).

i don't think this is particular useful for integer indices, so -1 on adding *yet* another method to do the same thing.

**Comment by jbrockmendel** [comment]
> i don't think this is particular useful for integer indices, so -1 on adding _yet_ another method to do the same thing.

The trouble is that if you have non-unique columns then there is _no_ public way of doing this

**Comment by jreback** [comment]
> > i don't think this is particular useful for integer indices, so -1 on adding _yet_ another method to do the same thing.
> 
> The trouble is that if you have non-unique columns then there is _no_ public way of doing this

i get it.

**Comment by jreback** [comment]
I mean another option here is to go back to doing real masking instead of setitem with ```.loc[:, columns]``` (and `.iloc`)

but i think that creates more issues

**Comment by jbrockmendel** [comment]
> I mean another option here is to go back to doing real masking instead of setitem with .loc[:, columns] (and .iloc)

I'm not clear on what you're suggesting.  In the status quo `df.loc[:, foo] = bar` _never_ tries to operate in-place, is identical to `df[foo] = bar`.  The proposal is that we _should_ try to operate in-place, just like we would for `df.loc[:-1, foo] = bar[:-1]`.

Under the status quo, there is no way to do a try-to-operate-in-place setting of an entire column.  Under the proposed change, there is no way to do a dont-try-to-operate-in-place _positional_ setting of an entire column.

**Comment by jreback** [comment]
> I'm not clear on what you're suggesting. In the status quo df.loc[:, foo] = bar never tries to operate in-place, is identical to df[foo] = bar. The proposal is that we should try to operate in-place, just like we would for df.loc[:-1, foo] = bar[:-1].

we used to do exactly this and i changed it a long time ago because it was very confusing

**Comment by jbrockmendel** [comment]
> we used to do exactly this and i changed it a long time ago because it was very confusing

how is ".iloc[foo, bar] = baz always tries inplace" more confusing than "that, except for .iloc[:, bar] = baz which is _almost_ never inplace, the exception being when baz has the same dtype as the existing column (but uh, not for ArrayManager or (some) ExtensionDtypes!)"
