### ISSUE TITLE
ENH: add suffixes argument to DataFrame.compare

### ISSUE THREAD

**Issue by erfannariman** [pandas-dev/pandas#44354]
#### Is your feature request related to a problem?

It would be convenient to choose other suffixes in `DataFrame.compare` than `self, other`

#### Describe the solution you'd like

Add argument `suffixes` so users can specify them.

#### API breaking implications

None

#### Additional context

```python
df = pd.DataFrame(
    {"col1": ["a", "b", "c"], "col2": [1.0, 2.0, np.nan], "col3": [1.0, 2.0, 3.0]},
    columns=["col1", "col2", "col3"],
)
df2 = df.copy()
df2.loc[0, "col1"] = "c"
df2.loc[2, "col3"] = np.nan
diff = df.compare(df2, suffixes=["left", "right"])
print(diff)

  col1       col3      
  left right left right
0    a     c  NaN   NaN
2  NaN   NaN  3.0   NaN
```

**Comment by jreback** [comment]
seems reasonable

**Comment by Runningwater23** [comment]
In the source code, suffixes is fixed to keys=['self', 'other'],  change the value of keys to the value of suffixes transferred by the user.
