### ISSUE TITLE
BUG: Incorrect string matched in tests/io/parser/test_quoting.py

### ISSUE THREAD

**Issue by RRathna** [pandas-dev/pandas#44420]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
Run command:
python3 -m pytest -s -q --no-header --skip-slow --skip-db --skip-network /usr/local/lib/python3.9/site-packages/pandas/tests/io/parser/test_quoting.py

Expected result:
AssertionError: Regex pattern '"quotechar" must be string, not int' does not match '"quotechar" must be string or None, not int'.
```

### Issue Description

Pandas now returns string '"quotechar" must be string or None, not int' when passing in an int value as argument.
The current test does a regex match for '"quotechar" must be string, not int' which is resulting in the test failing.

### Expected Behavior

The test should pass

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.9.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0
Version          : Mystikos 1.0.0
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8

pandas           : 1.3.4
numpy            : 1.21.4
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 57.5.0
Cython           : None
pytest           : 6.2.5
hypothesis       : 6.24.2
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by jreback** [comment]
and this is failing in master?

**Comment by phofl** [comment]
No, this is a python stdlib error message which was changed on master and is in a not yet released python version.

The pd.show_versions is wrong. The released 3.10 python raises still the error message we are testing against

**Comment by phofl** [comment]
I think we can close till this ocurrs on our ci?

**Comment by jreback** [comment]
yep
