### ISSUE TITLE
ENH: pd.Inplace/pd.Copy enum

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#44433]
For e.g. `DataFrame.mask`, `inplace=True` can be misleading because it really means "inplace if you don't have to cast, otherwise not inplace".  We could be more explicit with an enum like

```
class InPlace(enum.Enum):
    only = 0  # never copy; raise instead of casting
    attempt = 1  # inplace if you can, cast on fallback
    never = 2  # always make a copy
```

I think I've seen numpy discussions on doing something similar, forget which kwarg that was about.

**Comment by CloseChoice** [comment]
just to make this clear: you mean to introduce these options to the public API not just for internal usage, right?

**Comment by jbrockmendel** [comment]
thats what i had in mind yes

**Comment by jbrockmendel** [comment]
CoW is expected to become the default/only behavior, making this irrelevant.  Closing.
