### ISSUE TITLE
ENH: Implement reading the output of a MDX query into a dataframe.

### ISSUE THREAD

**Issue by jachymb** [pandas-dev/pandas#44467]
#### Is your feature request related to a problem?

This may be a quite big thing. But I's like pandas to be able to execute a MDX query to an OLAP server and read the results into a DataFrame. 

#### Describe the solution you'd like

I imagine there could be a function similar to pd.read_sql

#### API breaking implications

May require a new library as a pandas dependency?

#### Describe alternatives you've considered

It's possible to actually embed a MDX query into a SQL and simply use read_sql. It's also possible to use a library like adodbapi and transform the output into a DataFrame myself. But both feel kind of cumbersome.

**Comment by jreback** [comment]
pandas doesn't implement these connections rather they are wrappers around libraries 

so show libraries that can do this

**Comment by jachymb** [comment]
Sure, it could be something like:

```python
  with adodbapi.connect(connection_string) as connection:
    with connection.cursor() as cursor:
      cursor.execute(mdx_query)
      data = cursor.fetchall()
```

see for example: https://stackoverflow.com/questions/56075159/convert-listadodbapi-apibase-sqlrow-to-pd-dataframe

**Comment by jreback** [comment]
since we already have read_sql and friends i don't think worthwhile to add anything as this is a very similar operation

**Comment by ParfaitG** [comment]
Actually `adodbapi` can work as a DB-API with `read_sql`. Did you try `df = pd.read_sql(mdx_query, connnection)`? See my answer at bottom of your linked SO page. You may get nested data due query's multidimensional elements.

**Comment by mroeschke** [comment]
Thanks for the suggestion, but since there is compatible operations with `read_sql`, it's probably out of scope to add code to specific support this niche use case. Closing, but can reopen if there's renewed interest
