### ISSUE TITLE
BUG: pd.DataFrame.columns.insert( -1: <name>) does not insert in last position

### ISSUE THREAD

**Issue by stephenhallfr** [pandas-dev/pandas#44509]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame(columns = ["A", "B"])
col = df.columns.insert(-1, "C")
print(col)
df = pd.DataFrame( columns = col)
print(df.columns)
```

### Issue Description

the method index.insert does not allow to insert a value last.
`loc=-1` gives an insertion at the second last place
'loc=0=-0' gives an insertion at 1st place

### Expected Behavior

The method index.insert should follow the standard loc function and 'loc=-1' should insert the item last in the index 

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.129+
Version          : #1 SMP Wed Aug 18 19:58:18 PDT 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8

pandas           : 1.3.4
numpy            : 1.21.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 20.0.2
setuptools       : 45.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
None
</details>

**Comment by abatomunkuev** [comment]
The insert adds an element before the specified index. In your case, you insert `C` before the last element of the columns list. See https://stackoverflow.com/questions/53932704/array-insert-with-negative-index/53932930#53932930

To add to the end of the list you can use `len(df.columns)`. 

```python
col = df.columns.insert(len(df.columns),"C")
```
```
Index(['A', 'B', 'C'], dtype='object')
```

**Comment by phofl** [comment]
This is not consistent with the docs, which state that the function behaves like list.append, so this is a bug, either in code or in the docs
