### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by alexmondaini** [pandas-dev/pandas#44515]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame([NaN,*range(5),1000],columns=['col1'])
df.update(df.loc[:,df.columns != 'some_column'].pct_change(-1))

print(df)
```

### Issue Description

This code without `df.update` will make the last row of the dataset filled with `NaN` values, however when an `update` is made the row remains unchanged. is this a normal behavior of pandas ? shouldn't the row be updated to `Nan` ?  

### Expected Behavior

return last row with `NaN`

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : 73c68257545b5f8530b7044f56647bd2db92e2ba
python           : 3.9.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.1.0
Version          : Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.3.3
numpy            : 1.21.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.28.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
None

**Comment by asishm** [comment]
This is documented behavior. From the [docs](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.update.html) 

> If other contains NaNs the corresponding values are not updated in the original dataframe.

![image](https://user-images.githubusercontent.com/1978117/142475406-3f57752d-bd60-4521-977f-989b9eff6625.png)

**Comment by MarcoGorelli** [comment]
Yup, thanks @asishm !
