### ISSUE TITLE
pip --proxy=foo.com install pandas fails to download numpy dependency

### ISSUE THREAD

**Issue by lemonlaug** [pandas-dev/pandas#4452]
I believe the problem here is that setup.py is trying to install numpy without using the proxy server passed to pip.

```
pip-2.7 install --proxy=http://sampleproxy.com:3128 pandas
Downloading/unpacking pandas
  Downloading pandas-0.12.0.zip (3.4MB): 3.4MB downloaded
  Running setup.py egg_info for package pandas
    Download error on https://pypi.python.org/simple/numpy/: [Errno 110]     Connection timed out -- Some packages may not be found!
    Couldn't find index page for 'numpy' (maybe misspelled?)
```

Installing numpy using `pip --proxy=proxy.com:3128 install numpy` and then install pandas as above worked fine.

**Comment by mandshaw** [comment]
This is a Pandas issue,

The folks at pip have confirmed. Details are here:

https://github.com/pypa/pip/issues/3238#issuecomment-155345708

**Comment by TheMcGoose** [comment]
Any movement on this issue? Or a workaround people have found to make this work?

**Comment by TomAugspurger** [comment]
I think that pyproject.toml will eventually fix this.
