### ISSUE TITLE
DOCS question: add pandera to ecosystem page?

### ISSUE THREAD

**Issue by cosmicBboy** [pandas-dev/pandas#44543]
https://pandas.pydata.org/pandas-docs/stable/ecosystem.html

Hi pandas maintainers! I wanted to field a question here to add [pandera](https://pandera.readthedocs.io/) to the pandas ecosystem docs page under "data validation and cleaning". Pandera is a schema specification, type annotation, and data testing tool for Pandas and dataframe-like libraries (Dask, Modin, and Koalas) and wanted to see if it would make sense to add to this page.

**Comment by mroeschke** [comment]
Sure that would be welcome.

Might be good to replace https://pandas.pydata.org/pandas-docs/stable/ecosystem.html#engarde with this package as it appears engarde is no longer under active development https://github.com/engarde-dev/engarde#readme.

**Comment by mroeschke** [comment]
Closed by https://github.com/pandas-dev/pandas/pull/44708
