### ISSUE TITLE
ENH: Multiple character separators in to_csv

### ISSUE THREAD

**Issue by alphasierra59** [pandas-dev/pandas#44568]
#### Is your feature request related to a problem?

I would like to_csv to support multiple character separators.

#### Describe the solution you'd like

Be able to use multi character strings as a separator.

#### API breaking implications

Don't know.

#### Describe alternatives you've considered

Manually doing the csv with python's existing file editing.

#### Additional context

N/A

**Comment by AlexKirko** [comment]
Hello, @alphasierra59 . Could you please clarify what you'd like to see? Do you mean for us to natively process a csv, which, let's say, separates some values with "," and some with ";"?

From what I know, this is already available in pandas via the Python engine and regex separators. Let me check with an example.

**Comment by AlexKirko** [comment]
Yes, this works perfectly:

```python
df = pd.read_csv('test.txt', sep=';|,')
```

With the following CSV file:
```
A;B,C
1,2;3
```

Output:
| |A|B|C|
|-|-|-|-|
|0|1|2|3|

I'm closing this for now. Please reopen if you meant something else.

**Comment by alphasierra59** [comment]
I would like to be able to use a separator like ";;" for example where the file looks like
```
col1;;col2
val1;;val2
```

Output:
| Col1 | Col2 |
| --- | --- |
| Val1 | Val2 |

**Comment by AlexKirko** [comment]
Ah, apologies, I misread your post, thought it was about `read_csv`. Reopening for now.

The reason we have regex support in read_csv is because it's useful to be able to read malformed CSV files out of the box. The reason we don't have this support in `to_csv` is, I suspect, because being able to make what looks like malformed CSV files is a lot less useful. The case of the separator being in conflict with the fields' contents is handled by quoting, so that's not a use case.

Could you provide a use case where this is necessary, i.e. where a one character separator plus quoting do not do the job somehow? It would help us evaluate the need for this feature.

**Comment by alphasierra59** [comment]
Recently I needed a quick way to make a script that could handle having commas and other special characters in the data fields that needed to be simple enough for anyone with a basic text editor to work on. Using pandas was a really handy way to get the data from the files in while being simple for less skilled users to understand. I am using other pandas functions to use the data after ingest, but I also need to be able to write back new data to those same files. Being able to specify an arbitrary delimiter means I can make it tolerate having special characters in the data.

**Comment by jreback** [comment]
-1 on supporting multi characters writing 

its barely supported in reading and not anywhere to standard in csvs (not that much is standard)

why for example wouldn't you just use | or similar as that's a standard way around this

**Comment by alphasierra59** [comment]
Because that character appears in the data. I am aware that it's not part of the standard use case for CSVs, but I am in the situation where the data can contain special characters, the file format to be simple and accessible, and users that are less technically skilled need to interact with the files. Using something more complicated like sqlite or xml is not a viable option for me. A custom delimited ".csv" meets those requirements.

**Comment by AlexKirko** [comment]
I see. What I would personally recommend in your case is to scour the utf-8 table for a separator symbol which do not appear in your data and solve the problem this way. If you also use a rare quotation symbol, you'll be doubly protected. Less skilled users should still be able to understand that you use `ᚢ` to separate fields. Just don't forget to pass `encoding="utf-8"` when you read and write.

-1 from me. I believe the problem can be solved in better ways than introducing multi-character separator support to `to_csv`.

From what I understand, your specific issue is that somebody else is making malformed files with weird multi-char separators and you need to write back in the same format and that format is outside your control. This would be the case where the support you are requesting would be useful, however, it is a super-edge case, so I would suggest that you cludge something together in this case. Just use a super-rare separator for `to_csv`, then search-and-replace it using Python or whatever tool you prefer.

**Comment by AlexKirko** [comment]
Closing the issue for now, since there are no new arguments for implementing this.

**Comment by alphasierra59** [comment]
Sorry for the delayed reply. The only other thing I could really say in favour of this is just that it seems somewhat asymmetric to be able to read but not write to these files. I agree the situation is a bit wonky, but there was apparently enough value in being able to read these files that it was added. It should be able to write to them as well.

**Comment by craigim** [comment]
Looking for this very issue. I am trying to write a custom lookup table for some software over which I have no control (MODTRAN6 if curious). The particular lookup table is delimited by _three spaces_. I've been wrestling with Pandas for hours trying to trick it into inserting two extra spaces between my columns, to no avail. It sure would be nice to have some additional flexibility when writing delimited files.

**Comment by michael-urrutia** [comment]
> Closing the issue for now, since there are no new arguments for implementing this.

Echoing @craigim. There are situations where the system receiving a file has really strict formatting guidelines that are unavoidable, so although I agree there are way better alternatives, choosing the delimiter is some cases is not up to the user. For my example, I am working on sharing data with a large partner in the pharmaceutical industry and their system requires us delimit data with `|~|`. They will not budge, so now we need to overcomplicate our script to meet our SLA.

**Comment by alexisechague** [comment]
Same problem. There are cases of manual entried data that the safe way to treat is to add a very complicated combination of characters. A multicharacter separator is perfect for this.
