### ISSUE TITLE
Locking as resolved for now, thanks for sharing solutions - if anyone experiences any issues, please open a new issue with a reproducible example - thanks 👍

### ISSUE THREAD

**Issue by arghanath007** [pandas-dev/pandas#44570]
Locking as resolved for now, thanks for sharing solutions - if anyone experiences any issues, please open a new issue with a reproducible example - thanks 👍

_Originally posted by @MarcoGorelli in https://github.com/pandas-dev/pandas/issues/11493#issuecomment-863971914_
error_bad_lines=False argument works and it resolves the issue while reading a csv file using pandas but it gives this Future Warning -> "  FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. " Should I be worried about this warning? Although the csv file is read file with the warning though. Just curious if there are any other alternatives to it.

I am trying to read a CSV file like this -> 
          df=pd.read_csv('./data/data.csv', sep='\t', error_bad_lines=False)
          df

**Comment by MarcoGorelli** [comment]
You can use `on_bad_lines`, see https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html
