### ISSUE TITLE
BUG: Pandas sets current time if you do not set it

### ISSUE THREAD

**Issue by Jakub-Ner** [pandas-dev/pandas#44573]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd

hour = pd.DataFrame({"hour": ["09:00", "12:37"]})
hour["hour"] = pd.to_datetime(hour["hour"])
print(hour["hour"].dt.date) # display current time
```

### Issue Description

Pandas sets current time if you do not set it by yourself.

### Expected Behavior

if you don't set a date you expect it to be NaN

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.11.0-40-generic
Version          : #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.4
numpy            : 1.21.4
pytz             : 2020.1
dateutil         : 2.7.3
pip              : 20.0.2
setuptools       : 45.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.5.0
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.18
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
None

</details>

**Comment by MarcoGorelli** [comment]
I think this is due to dateutil
```
>>> from dateutil.parser import parse
>>> parse('09:00')
datetime.datetime(2021, 11, 22, 9, 0)
```

You should specify the format if you expect it to error if it doesn't match the format

**Comment by mroeschke** [comment]
Correct, this is inherited behavior from dateutil. Closing
