### ISSUE TITLE
CI: docstring check failing with Segmentation fault

### ISSUE THREAD

**Issue by johnzangwill** [pandas-dev/pandas#44590]
#### CI failing
"CI / Checks (pull_request)" is failing repeatedly with:
```
2021-11-23T14:38:53.7695817Z ci/code_checks.sh: line 100:  8142 Segmentation fault      (core dumped) 
```

[logs_205535.zip](https://github.com/pandas-dev/pandas/files/7589379/logs_205535.zip)

**Comment by johnzangwill** [comment]
This is still happening

**Comment by phofl** [comment]
Tried reproducing locally without sucess

**Comment by johnzangwill** [comment]
Thanks. It seems very random, and I can't reproduce it locally at all.

**Comment by johnzangwill** [comment]
Haven't seen this in a while, so Close
