### ISSUE TITLE
DEPR Deprecate mapper argument in rename?

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#44627]
xref https://github.com/pandas-dev/pandas/pull/40979#issuecomment-980063593

> thanks @MarcoGorelli i realize now why this is convoluted, will be glad to remove this in 2.0

@jreback not sure I understand what you mean - as in, to remove `mapper` in 2.0 and only support the `index=` and `columns=` calls? (and hence, introduce a deprecation warning in time for 1.4)

**Comment by jreback** [comment]
no what u mean is to fix the structure of the impl here
maybe we just need to make the structure in generic a private function to avoid having to handle the signature like this

**Comment by MarcoGorelli** [comment]
OK, so rename `rename` in `pandas/core/generic.py` to `_rename`, and go back to the old signature for `Series.rename`, i.e.
```
    def rename(
        self,
        index=None,
        *,
        index=None,
        columns=None,
        axis=None,
        copy=True,
        inplace=False,
        level=None,
        errors="ignore",
    ):
```
? Like this, `mypy` wouldn't complain about the incompatibility.
Wish I'd thought of this actually, it seems like a better solution than what I did.

If so, I think that could be done straight away, rather than having to wait for 2.0, it wouldn't alter anything user-facing

**Comment by jreback** [comment]
yeah i think that's right. its not worth trying to shoe-horn this in for methods which have a different signatture in series vs dataframe just to placate mypy, better to just have the impl be private.

**Comment by Varun270** [comment]
@MarcoGorelli I tried to understand this issue and so far I understood that in `pandas/core/generic.py` we have to make the `rename` function private and make it `_rename`. Is that all? I am sure I am missing out on a lot.

**Comment by MarcoGorelli** [comment]
Hey @Varun270 !

So, there's a few things to do:
1. rename `rename` in `pandas/core/generic.py` to `_rename`
2. update `rename` (in both `pandas/core/frame.py` and `pandas/core/series.py` to call `super()._rename`, rather than `super().rename`)
3. revert some of the changes I made in #40979 so that the signature of `Series.rename` becomes:
```python
    def rename(
        self,
        index=None,
        *,
        axis=None,
        copy=True,
        inplace=False,
        level=None,
        errors="ignore",
    ) ->  Series | None:
```

If you open a PR (even if you're not sure about everything) and tag me I can help you along with this

**Comment by Varun270** [comment]
> Hey @Varun270 !
> 
> So, there's a few things to do:
> 
> 1. rename `rename` in `pandas/core/generic.py` to `_rename`
> 2. update `rename` (in both `pandas/core/frame.py` and `pandas/core/series.py` to call `super()._rename`, rather than `super().rename`)
> 3. revert some of the changes I made in [TYP: Signature of "rename" incompatible with supertype "NDFrame" #40979](https://github.com/pandas-dev/pandas/pull/40979) so that the signature of `Series.rename` becomes:
> 
> ```python
>     def rename(
>         self,
>         index=None,
>         *,
>         axis=None,
>         copy=True,
>         inplace=False,
>         level=None,
>         errors="ignore",
>     ) ->  Series | None:
> ```
> 
> If you open a PR (even if you're not sure about everything) and tag me I can help you along with this

I understood the first two points but will require your guidance on 3rd point as I don't know how can I revert changes done by someone else.

**Comment by Varun270** [comment]
Currently in `Series.rename` the function rename looks like this -
```py
def rename(
        self,
        index=None,
        *,
        axis=None,
        copy=True,
        inplace=False,
        level=None,
        errors="ignore",
    ):
```
So after reverting it would look like this - 
```py
    def rename(
        self,
        index=None,
        *,
        axis=None,
        copy=True,
        inplace=False,
        level=None,
        errors="ignore",
    ) ->  Series | None:

```
Is that what you are saying?

**Comment by MarcoGorelli** [comment]
> Currently in Series.rename the function rename looks like this -

Make sure to pull the latest changes, it doesn't quite look like that at the moment. Anyway,

> So after reverting it would look like this -

Yes, it should look like that at the end

**Comment by Varun270** [comment]
> > Currently in Series.rename the function rename looks like this -
> 
> Make sure to pull the latest changes, it doesn't quite look like that at the moment. Anyway,
> 
> > So after reverting it would look like this -
> 
> Yes, it should look like that at the end

Okay, so I guess I would have to revert the changes first then rename the `rename` functions. How am I supposed to do that? Like should I do the usual git revert commit_id?

**Comment by MarcoGorelli** [comment]
it's up to you how you do it

**Comment by Varun270** [comment]
Alright, will do it!

**Comment by Varun270** [comment]
@MarcoGorelli I found the commit that needed to be reverted but you have done some other changes in that commit apart from adding args to function `rename`. Here have a look at this - https://github.com/pandas-dev/pandas/pull/40979/commits/40ecf6e754451acb87f8a2f3b911a8cb9728cda1
so should I proceed ahead since reverting it would revert some additional changes as well?

**Comment by MarcoGorelli** [comment]
What can be reverted are:
- changes to `Series.rename` (can just revert them all, and change `super().rename` to `super()._rename`
- the extra tests in `pandas/tests/series/methods/test_rename.py` are no longer necessary

Might be easier to do this manually rather than reverting a commit using git. Up to you though, if you open a PR I'll take a look

**Comment by Varun270** [comment]
> What can be reverted are:
> 
> * changes to `Series.rename` (can just revert them all, and change `super().rename` to `super()._rename`
> * the extra tests in `pandas/tests/series/methods/test_rename.py` are no longer necessary
> 
> Might be easier to do this manually rather than reverting a commit using git. Up to you though, if you open a PR I'll take a look

Yeah, even I was thinking that manually doing these changes would be much easier for me. Will create a PR.
