### ISSUE TITLE
BUG: rolling function for std has a substantial bug

### ISSUE THREAD

**Issue by MichalRIcar** [pandas-dev/pandas#44640]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd

a = pd.Series([0 for i in range(15)])
a[5] = -1
b3 = a.rolling(3, center=False, win_type = None, axis=0, method='single').std()
b4 = a.rolling(4, center=False, win_type = None, axis=0, method='single').std()
b6 = a.rolling(6, center=False, win_type = None, axis=0, method='single').std()

c = b3/b6

# even though b3 and b6 has to be 0 after -1 disappears in the rolling window, c result is 
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
5     1.414214e+00
6     1.414214e+00
7     1.414214e+00
8     1.825012e-08
9     1.825012e-08
10    1.825012e-08
►11    6.575299e+08
►12    6.575299e+08
►13    6.575299e+08
►14    6.575299e+08
```

### Issue Description

b3 std is an incorrect expression of 0 after -1 disappears and only 0 is present in std calc
b4 std is correct
b6 std is an incorrect expression of 0 after -1 disappears and only 0 is present in std calc

c cause a significant issue in further calculations...

The rolling function of STD has a bug that seems to wrongly represent 0 after the occurrence of a value in the previous rolling window.
Tested other rolling fx like avg, min, max, seems to behave OK. 

### Expected Behavior

STD as standard deviation has to reproduce 0 when constant value is evaluated. In the example above the constant value is 0.

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.8.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.3.4
numpy            : 1.21.3
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 52.0.0.post20210125
Cython           : 0.29.23
pytest           : 6.2.3
hypothesis       : None
sphinx           : 4.0.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.8
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.27.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.9.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.8
pandas_gbq       : None
pyarrow          : 4.0.1
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : 1.4.7
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.53.1

**Comment by phofl** [comment]
This is mentioned in https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.3.0.html#removed-artificial-truncation-in-rolling-variance-and-standard-deviation.

**Comment by mroeschke** [comment]
Agreed, this is an unfortunate implementation artifact of the underlying algorithm that is calculating std and var. Closing.
