### ISSUE TITLE
BUG: Pandas plot does not accept Columns for color keyword

### ISSUE THREAD

**Issue by mosc9575** [pandas-dev/pandas#44670]
### 

- [ ] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({
 'A': {1: 6, 2: 2, 3: 1, 4: 8, 5: 6},
 'B': {1: 2, 2: 10, 3: 3, 4: 1, 5: 1},
 'pos': {1: 1, 2: 2, 3: 4, 4: 1, 5: 1},
 'color': {1: 'red', 2: 'blue', 3: 'green', 4: 'red', 5: 'red'}
})

# df >>>
#    A   B  color
# 1  6   2    red
# 2  2  10   blue
# 3  1   3  green
# 4  8   1    red
# 5  6   1    red


df.plot(x='A', y='B', kind='scatter', color=df['color'].values)
# df.plot(x='A', y='B', kind='scatter', color='color')
```

### Issue Description

I tried to plot a scatterplot with different groups, with one color for each group. I thought is is enought to pass the name of the column to the color-keyword, but this throws an error:

`ValueError: 'c' argument must be a color, a sequence of colors, or a sequence of numbers, not ['color']`

### Expected Behavior

I expect this figure, which was generated using the commented line

`s.plot(x='A', y='B', kind='scatter', color=s['color'].values)`

![grafik](https://user-images.githubusercontent.com/68053396/143868392-11e5de24-d1a7-412d-9404-38a0b2b5afc6.png)

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.9.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.0-8-amd64
Version          : #1 SMP Debian 5.10.46-4 (2021-08-03)
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.4
numpy            : 1.20.3
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : 0.29.24
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.28.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 2021.09.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : 1.4.23
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.54.0
1
​

</details>

**Comment by mosc9575** [comment]
This is mentioned as a workaround in [#40605](https://github.com/pandas-dev/pandas/issues/40605).

**Comment by MarcoGorelli** [comment]
>  I thought is is enought to pass the name of the column to the color-keyword

Is that documented anywhere? If not, I'd consider this as a feature request rather than a bug

**Comment by mosc9575** [comment]
Yes, the line `df.plot(x='A', y='B', kind='scatter', c='color')` creates the expected result.

**Comment by mosc9575** [comment]
This is at least a inconsistency, beacuse in [`barh`]https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.barh.html#pandas.DataFrame.plot.barh and [`bar`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.barh.html#pandas.DataFrame.plot.bar) the keyword seem to be `color` and not `c`.

**Comment by mosc9575** [comment]
Yes, I'll come back and give a PR a try.
