### ISSUE TITLE
ENH: Pairwise method or symmetric keyword in DataFrame.corr

### ISSUE THREAD

**Issue by maurosilber** [pandas-dev/pandas#44671]
#### Is your feature request related to a problem?

I wish I could use pandas to do pairwise computations.

#### Describe the solution you'd like

The [`DataFrame.corr`](https://github.com/pandas-dev/pandas/blob/c58d8ee6e93fc1ba7aa4a40dc71488cc9807ed43/pandas/core/frame.py#L9526-L9545) method accepts a callable to compute a user-specified correlation function. Its docstring says:

> callable: callable with input two 1d ndarrays returning a float. Note that the returned matrix from corr have 1 along the diagonals and will be symmetric of the callable's behavior.

I'd like to compute pairwise calculations which are not symmetric. I can think of two possible solutions:

1. Add a `symmetric` keyword-only argument, changing the signature to:

```python
def corr(
        self,
        method: str | Callable[[np.ndarray, np.ndarray], float] = "pearson",
        min_periods: int = 1,
        *,
        symmetric=True,
    ) -> DataFrame:
```

It keeps the current behaviour by default, but allows asymmetric callables to be computed. It could also change the behaviour when computing the diagonals, which are now set to 1, independently of the function provided.

2. Add a new pairwise method.

#### API breaking implications

The first option shouldn't change the API, as it is adding a keyword-only argument which keeps current behaviour as default.

The second option might not be backwards-compatible with code where columns are named `pairwise` and called via attribute access.

#### Additional context

A similar issue was raised here: https://github.com/pandas-dev/pandas/issues/25726

**Comment by jreback** [comment]
that issue see discussions in the PR: https://github.com/pandas-dev/pandas/pull/43569

**Comment by mroeschke** [comment]
Thanks for the suggestion, but given the discussion in https://github.com/pandas-dev/pandas/pull/43569, agreed that expanding the API of the corr function does not have much support. Closing
