### ISSUE TITLE
ENH: Generate a full frequency table from a categorical feature

### ISSUE THREAD

**Issue by HenriqueAJNB** [pandas-dev/pandas#44698]
#### Describe the solution you'd like

`Series.frequency_table()` could return a DataFrame with full frequency table, with the following columns:
- `abs_freq`: The count of each label like in `.value_counts()`
- `rel_freq`: The relative frequency like in `.value_counts(normalize=True)`
- `cum_abs_freq`: the cumulative frequency, considering a `sort` parameter.
- `cum_rel_freq`: the relative cumulative frequency, considering the same `sort` parameter.

Example:

**Input series**
| categ_col |
|-----------|
| A         |
| B         |
| C         |

**Output DataFrame**
| categ_col | abs_freq | rel_freq | cum_abs_freq | cum_rel_freq |
|-------------:|----------|----------|--------------|--------------|
| A            | 1        | 0.33     | 1            | 0.33         |
| B            | 1        | 0.33     | 2            | 0.66         |
| C            | 1        | 0.33     | 3            | 1.00         |

The `sort` parameter could be used to define the prior order of column, because it affects the both cumulative columns.

**Comment by jreback** [comment]
umm as indicated u can use .value_counts

this looks easily implemented externally and just adds to an already very large api

-1 on adding

**Comment by mroeschke** [comment]
Agreed. This looks easily implemented as an ad-hoc helper function composed of existing pandas functionalities that doesn't necessarily need to be maintained in the library.

Thanks for the suggestion, but going to close due to lack of core team support
