### ISSUE TITLE
BUG: Apply ewm to GroupBy object results in duplicate index columns

### ISSUE THREAD

**Issue by matteosantama** [pandas-dev/pandas#44696]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd

pd.__version__
>>> '1.3.4'

numbers = [1, 2, 3, 4]
colors = ["green", "red", "blue"]
index = pd.MultiIndex.from_product([numbers, colors], names=["numbers", "colors"])
df = pd.DataFrame({"data": range(len(numbers) * len(colors))}, index=index)

df.groupby(level=["colors"]).mean()
>>>         data
colors      
blue     6.5
green    4.5
red      5.5

df.groupby(level=["colors"]).ewm(span=2).mean()
>>>                            data
colors numbers colors          
blue   1       blue    2.000000
       2       blue    4.250000
       3       blue    6.846154
       4       blue    9.650000
green  1       green   0.000000
       2       green   2.250000
       3       green   4.846154
       4       green   7.650000
red    1       red     1.000000
       2       red     3.250000
       3       red     5.846154
       4       red     8.650000
```

### Issue Description

By adding an intermediary `.ewm()` step to the groupby operation, the resulting DataFrame has a duplicate index column.

### Expected Behavior

I would expect consistent behavior whether I apply a `.ewm` transformation or not.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.8.12.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.1.0
Version          : Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.4
numpy            : 1.20.0
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 56.0.0
Cython           : 0.29.24
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.4
html5lib         : None
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.30.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
fsspec           : 2021.11.1
fastparquet      : None
gcsfs            : None
matplotlib       : 3.5.0
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 5.0.0
pyxlsb           : None
s3fs             : 2021.11.1
scipy            : 1.7.3
sqlalchemy       : 1.4.27
tables           : None
tabulate         : 0.8.9
xarray           : 0.20.1
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by phofl** [comment]
This is deliberate. See https://pandas.pydata.org/docs/whatsnew/v1.3.0.html#groupby-rolling-with-multiindex-no-longer-drops-levels-in-the-result and #44410
