### ISSUE TITLE
BUG: DataFrame attributes do not propagate after calling DataFrame.add, DataFrame.sub, and other arithmetic operators

### ISSUE THREAD

**Issue by skwirskj** [pandas-dev/pandas#44707]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame({'a': [0, 1, 2], 'b': [3, 4, 5]})
df.attrs['name'] = 'scores'
print(df.attrs)
"""
{'name': 'scores'}
"""
df = df.add(1)
print(df.attrs)
"""
{}
"""
```

### Issue Description

When applying arithmetic operators to DataFrame, such as add, mul, div, and sub, the attributes and other metadata are not retained in the result. 

### Expected Behavior

```
import pandas as pd
df = pd.DataFrame({'a': [0, 1, 2], 'b': [3, 4, 5]})
df.attrs['name'] = 'scores'
print(df.attrs)
"""
{'name': 'scores'}
"""
df = df.add(1)
print(df.attrs)
"""
{'name': 'scores'}
"""

```
The attributes should be retained after applying the operation. 

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : f5107e41467fe7f9c921d5cea7790c12cacab751
python           : 3.8.12.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.0.dev0+1275.gf5107e4146
numpy            : 1.21.4
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 58.5.3
Cython           : 0.29.24
pytest           : 6.2.5
hypothesis       : 6.24.3
sphinx           : 4.3.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.2
lxml.etree       : 4.6.4
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.29.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fsspec           : 2021.11.0
fastparquet      : 0.7.1
gcsfs            : 2021.11.0
matplotlib       : 3.4.3
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 6.0.0
pyxlsb           : None
s3fs             : 2021.11.0
scipy            : 1.7.2
sqlalchemy       : 1.4.27
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : 0.18.2
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.53.1

</details>

**Comment by skwirskj** [comment]
take

**Comment by phofl** [comment]
Please post these on the other issue. Add and mul are even listed there
