### ISSUE TITLE
BUG: read sql from varbinary error

### ISSUE THREAD

**Issue by panqingdian** [pandas-dev/pandas#44718]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
select t.dt,t.pub_code,stage_flag,
sum(t.total) as total,
cast(CONCAT(round(sum(t.c_5m_num)*100/sum(t.total),2),'% (',sum(t.c_5m_num),')') as char) as c_5m_num,
CONCAT(round(sum(t.c_10m_num)*100/sum(t.total),2),'% (',sum(t.c_10m_num),')') as c_10m_num,
CONCAT(round(sum(t.c_15m_num)*100/sum(t.total),2),'% (',sum(t.c_15m_num),')') as c_15m_num,
CONCAT(round(sum(t.c_30m_num)*100/sum(t.total),2),'% (',sum(t.c_30m_num),')') as c_30m_num,
CONCAT(round(sum(t.c_1h_num)*100/sum(t.total),2),'% (',sum(t.c_1h_num),')') as c_1h_num,
CONCAT(round(sum(t.c_6h_num)*100/sum(t.total),2),'% (',sum(t.c_6h_num),')') as c_6h_num,
CONCAT(round(sum(t.c_12h_num)*100/sum(t.total),2),'% (',sum(t.c_12h_num),')') as c_12h_num,
CONCAT(round(sum(t.c_1d_num)*100/sum(t.total),2),'% (',sum(t.c_1d_num),')') as c_1d_num,
CONCAT(round(sum(t.c_2d_num)*100/sum(t.total),2),'% (',sum(t.c_2d_num),')') as c_2d_num,
CONCAT(round(sum(t.c_3d_num)*100/sum(t.total),2),'% (',sum(t.c_3d_num),')') as c_3d_num,
CONCAT(round(sum(t.c_nd_num)*100/sum(t.total),2),'% (',sum(t.c_nd_num),')') as c_nd_num
from 
app_timeliness_cnt t 
where 1=1
and t.stage_flag = 3
and t.crawler_id = 6
and is_reply = 0
and job_id = 0
and dt <= CURRENT_DATE
and t.pub_code='bg_m_sinacn'
-- and dt >= 20211122
-- and dt <= 20211128
group by 1,2,3
order by dt desc
```

### Issue Description

When I execute a SQL query, I use read_SQL, where the field type is varbinary,Pandas returns b'99.71% (6357334) '

![image](https://user-images.githubusercontent.com/46396731/144361544-7be226b2-3ce6-42e7-97f5-f90cd68ab0ea.png)

### Expected Behavior

Expect to return a normal string

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()
1.2.5
</details>
1.2.5

**Comment by mroeschke** [comment]
This would need a more reproducible example (ideally showing `read_sql` usage with sqllite)

**Comment by mroeschke** [comment]
Thanks for the issue, but until we have a more minimal, reproducible example the triage team won't be able to act on this issue. Closing, but happy to reopen if one is provided.
