### ISSUE TITLE
lib.maybe_convert_objects will fail on uint64 values that exceed int64 max

### ISSUE THREAD

**Issue by wesm** [pandas-dev/pandas#4471]
xref #11440 for addtl tests

Observed in the wild. cc @blais

**Comment by pwaller** [comment]
I keep hitting this while importing a dataset which has uint64's in it. Is there anything I can do to help it along, given that someone already made a patch but it didn't get in?

**Comment by jreback** [comment]
where's the patch?

**Comment by pwaller** [comment]
@jreback see @jtratner's [comment above](https://github.com/pydata/pandas/issues/4471#issuecomment-24473554). Is the patch unsuitable or is it just that it wasn't shepherded into master?

**Comment by jreback** [comment]
that's 2 years old - if someone wants to cherry pick and present then can look

**Comment by jdc2172** [comment]
also hitting this bug - just wondering if the fix is in progress, or if interest is simply too low

**Comment by jreback** [comment]
well need someone motivated to push a fix
