### ISSUE TITLE
BUG: DataFrame.to_latex() does not correctly capture all columns

### ISSUE THREAD

**Issue by claragessner** [pandas-dev/pandas#44723]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd

data = {"a": [1, 2, 3],
    "b": [4, 5, 6],
    "c": [7, 8, 9],
    "d": [10, 1, 12],
    "e": [13, 14, 15]}

df = pd.DataFrame(data).T

df.to_latex("some_doc.tex", column_format='r', caption="some caption.", label="tab:", position="H")
```

### Issue Description

The provided code produces a file like this:

```
\begin{table}[H]
\centering
\caption{some caption.}
\label{tab:}
\begin{tabular}{r}
\toprule
{} &   0 &   1 &   2 \\
\midrule
a &   1 &   2 &   3 \\
b &   4 &   5 &   6 \\
c &   7 &   8 &   9 \\
d &  10 &   1 &  12 \\
e &  13 &  14 &  15 \\
\bottomrule
\end{tabular}
\end{table}
```

However, this coding does not work in Latex. In the tabular environment, it should be clear how many columns the table has. This one has 4, but only 1 is recognized (`\begin{tabular}{r}`). This leads to an error in Latex. The expected behaviour is shown below (`\begin{tabular}{rrrr}`).

### Expected Behavior

```
\begin{table}[H]
\centering
\caption{some caption.}
\label{tab:}
\begin{tabular}{rrrr}
\toprule
{} &   0 &   1 &   2 \\
\midrule
a &   1 &   2 &   3 \\
b &   4 &   5 &   6 \\
c &   7 &   8 &   9 \\
d &  10 &   1 &  12 \\
e &  13 &  14 &  15 \\
\bottomrule
\end{tabular}
\end{table}
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 73c68257545b5f8530b7044f56647bd2db92e2ba
python           : 3.8.5.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.1.0
Version          : Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.3.3
numpy            : 1.21.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.27.0
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.2
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.2
numexpr          : 2.7.3
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by mroeschke** [comment]
Thanks, but appears this is the expected behavior as described. Closing
