### ISSUE TITLE
CI: Flaky ResourceWarning: unclosedssl.SSLSocket

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#44732]
https://github.com/pandas-dev/pandas/runs/4399631223?check_suite_focus=true

```
AssertionError: Caused unexpected warning(s): [('ResourceWarning', ResourceWarning("unclosed <ssl.SSLSocket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.1.0.137', 51532), raddr=('52.216.164.101', 443)>"), '', 1043)]
```

Initial guess: it may be coming from one of our dependencies like https://github.com/boto/boto3/issues/454

Potential solution:
https://github.com/boto/botocore/pull/1810#issuecomment-749961250
https://github.com/mintel/pytest-localstack/issues/44#issuecomment-848258701

**Comment by jbrockmendel** [comment]
We already have one special-case in _assert_caught_no_extra_warnings to filter out SSL-related warnings, might as well filter these out too.  the time spent on tracking down ResourceWarnings has way exceeded the usefulness

**Comment by mroeschke** [comment]
+1. Since pandas is not a http library, agreed we should just ignore related artifacts for the stability of the CI.
