### ISSUE TITLE
BUG: DF from parquet expands with groupby

### ISSUE THREAD

**Issue by martgra** [pandas-dev/pandas#44734]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd

parquet_path = "some_path" # Parquet dataset with hive partition on column code. 

df = pd.read_parquet(parquet_path)
df["code"].nunique() # 714
df["b"].nunique() # 39

df = pd.read_parquet(parquet_path, filters=[('code', '=', 1)])
len(df) # 1024

df_g = df.groupby(by=["code", "b"], as_index=False).last()
len(df_g) # 27846 (714*39)
```

### Issue Description

Trying to load part of a hive partitioned dataset. The dataset is partitioned on the column "code" using hive partition. Using pd.read_parquet() and passing the filter keyword to pyarrow engine, a df of 1024 rows is loaded. So far everything as expected. 

Then reducing the dataframe by using groupby on "code" and "b" expands the dataframe from including only "code"=1 to every code found in the dataset. Each code has 39 values filled with NaN except the code that was originally filtered. 

### Expected Behavior
```python
df = pd.read_parquet(parquet_path, filters=[('code', '=', 1)])
len(df) # 1024

df_g = df.groupby(by=["code", "b"], as_index=False).last()
len(df_g) # 39 (1*39)
```
### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.9.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.16.3-microsoft-standard-WSL2
Version          : #1 SMP Fri Apr 2 22:23:49 UTC 2021
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.4
numpy            : 1.21.4
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 57.5.0
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.4
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.2
IPython          : 7.29.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 6.0.1
pyxlsb           : None
s3fs             : None
scipy            : 1.7.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by MarcoGorelli** [comment]
thanks for the report - can you add a descriptive title please?

**Comment by martgra** [comment]
@MarcoGorelli sure!

**Comment by mroeschke** [comment]
This would need a minimal, copy pasteable example: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

Ideally a similar parquet file could be generated with `pd.read_parquet(df.to_parquet())`

**Comment by mroeschke** [comment]
Thanks for the issue, but until we have a more minimal, reproducible example the triage team won't be able to act on this issue. Closing, but happy to reopen if one is provided.
