### ISSUE TITLE
TST: do we still need tests.extension.arrow.array.ArrowStringArray?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#44743]
We have a real one implemented in core.arrays.string_arrow, seems like wasted effort to fix the dummy one up to pass the tests

cc @jorisvandenbossche

**Comment by jbrockmendel** [comment]
gentle ping @jorisvandenbossche

**Comment by jorisvandenbossche** [comment]
It's only used for a single test, and that was added in https://github.com/pandas-dev/pandas/pull/27674. So we will need to verify that this is tested otherwise as well.

**Comment by jbrockmendel** [comment]
The relevant test now uses `dtype=StringDtype(storage="pyarrow")` and the test ArrowStringArray has been removed.  Closing.
