### ISSUE TITLE
CI: CI / Web and docs fails more in last 2 days

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#44754]
Looking at recent PR's, for  the "CI / Web and docs (pull_request)" fail, but a couple days ago, things were working, independent of whether any doc changes were made

Example fails:

- #44750 (12/4 at approx 3AM EST)
- #44741 (12/3 at approx 7PM EST)

Example successes:

- #47156 (12/2 - unknown time)
- #47155 (12/2 - unknown time)

**Comment by rhshadrach** [comment]
Should be resolved now by #44756

**Comment by mroeschke** [comment]
Closing as fixed by https://github.com/pandas-dev/pandas/pull/44756
