### ISSUE TITLE
Skew and kurtosis in describe method

### ISSUE THREAD

**Issue by PeterPirog** [pandas-dev/pandas#44751]
I wish I could use pandas to do show skew and kurtosis in df.describe method, of course I know that there are separate methods:

- df.kurtosis
- df.skew

**Comment by attack68** [comment]
see #43894 
add a comment if you consider useful.

**Comment by mroeschke** [comment]
Thanks for the report.

Given #43894, and generally existing as separate methods, I don't think it's worth introducing this is describe. Thanks for the suggestion, but closing.

**Comment by attack68** [comment]
New info might change the direction of styler.

**Comment by rhshadrach** [comment]
@attack68 - did you want to repurpose this into an issue about Styler?

**Comment by rhshadrach** [comment]
I think you're saying it's okay to close this now; let me know if I've misunderstood.
