### ISSUE TITLE
Understanding multidimensional boolean contigiency tables

### ISSUE THREAD

**Issue by JoaoDDuarte** [pandas-dev/pandas#44789]
This is crossposted from StackOverflow but I got the classic "this is not a specific technical question" response, hence I am asking it here :)

I am trying to understand this contingency table and I have no luck looking in the documentation of pandas or any other related questions. This is for a personal machine learning project.

I have the following example data:

```python
df = pd.DataFrame({"la":[0,1,1,0,1], "lp1": [1,0,1,0,0], "lp2":[1,1,0,0,1], "lp3":[0,0,1,1,1], "lp4":[0,1,1,0,0]})
```

Hence we will have a Boolean contingency table. If I run:

```python
df.crosstab(index=df['la'], columns=[df['lp1'],df['lp2']])
```

I get the output:

```python
lp1  0     1   
lp2  0  1  0  1
la             
0    1  0  0  1
1    0  2  1  0
```

This can be better visualised in a table like so:

|    | | |  | |  |
|----|------|---|---|---|----|
|    | **lp1**: | **0** | **0** | **1** | **1** |
|    | **lp2**: | **0** | **1** | **0** | **1** |
| **la** | **0**    | *1* | *0* | *0* | *1* |
|    | **1**    | *0* | *2* | *1* | *0* |

Which can be better understood as (e.g.) there were `2` occurrences of `lp1=0 lp2=1 and la=0` in the dataset. However, if I run:

```python
pd.crosstab(index=df['la'], columns=[df['lp1'],df['lp2'],df['lp3']])
```
I expect a table like this:

```python
lp1  0           1   
lp2  0     1     0     1
lp3  0  1  0  1  0  1  0  1 
la                
0    1   #results here
1    0  
```

Instead, I get:
```python
lp1  0        1   
lp2  0  1     0  1
lp3  1  0  1  1  0
la                
0    1  0  0  0  1
1    0  1  1  1  0
```

I have no idea how to interpret this table. I am unsure why there is a repeating label (the repeating 1 in lp3), why the labels suddenly change order from `0,1` to `1,0`. This continues for higher dimensions (e.g. 5 dimensions):

```python
pd.crosstab(index=df['la'], columns=[df['lp1'],df['lp2'],df['lp3'],df['lp4']])
```
produces:
```python
lp1  0        1   
lp2  0  1     0  1
lp3  1  0  1  1  0
lp4  0  1  0  1  0
la                
0    1  0  0  0  1
1    0  1  1  1  0
```

It all makes sense to me until you have a table > 3 dimensions. I am running Python 3.10 and pandas 1.3.4.

I have tried to go through the source code, docs and related StackOverflow questions and I have not found an answer. 

How do I properly interpret this 4 dimensional table, please?

**Comment by attack68** [comment]
I think you need to know two things.

Firstly you can turn off sparsification and visualise the entire column headers. Each column is identifiable by a unique 3 tuple, which appears to be lex sorted automatically to enable better indexing:

```
pd.options.styler.sparse.columns = False
pd.options.styler.sparse.index = False
df = pd.DataFrame({"la":[0,1,1,0,1], "lp1": [1,0,1,0,0], "lp2":[1,1,0,0,1], "lp3":[0,0,1,1,1], "lp4":[0,1,1,0,0]})
pd.crosstab(index=df['la'], columns=[df['lp1'],df['lp2'],df['lp3']]).style
```

![Screen Shot 2021-12-06 at 20 37 23](https://user-images.githubusercontent.com/24256554/144910881-02c8c468-433f-43c3-b7ae-315bed6e36ba.png)

Secondly your default expectation is fine for this rather small dataset, but in general the principle of exhaustive vector product spaces is going to break memory. Imagine doing the same on the arrays:

[a, b, c, d]
[e, f, g, h]
[i, j, k, l]

You can either return a 4 column DataFrame with the column 3 tuples as above or return a 64 column DataFrame where 60 of those are redundant.

**Comment by aa1371** [comment]
In addition to what @attack68 said above, there is no way to know what the other possible values of your fields could be. You know that it is only {0, 1}, but pandas doesn't know this, there are infinite possibilities in what  a "dense" multiindex column could look like.

However, since you know the domain of possible values for the different fields, you can build a dense view manually. Like so:

```
df = pd.DataFrame({"la":[0,1,1,0,1], "lp1": [1,0,1,0,0], "lp2":[1,1,0,0,1], "lp3":[0,0,1,1,1], "lp4":[0,1,1,0,0]})

ct = pd.crosstab(index=df['la'], columns=[df['lp1'],df['lp2'],df['lp3'],df['lp4']])

BINARY_DOMAIN = [0, 1]
desired_columns = pd.MultiIndex.from_product([BINARY_DOMAIN] * ct.columns.nlevels, names=ct.columns.names)

ct.reindex(columns=desired_columns).fillna(0).astype(int)

lp1  0           1         
lp2  0     1     0     1   
lp3  0  1  0  1  0  1  0  1
la                         
0    0  1  0  0  0  0  1  0
1    0  0  1  1  0  1  0  0
```

Potentially a better way to do this would be to use categoricals. This way you can essentially define up front what the domain of possible values of your fields would be.

```
df = pd.DataFrame({"la":[0,1,1,0,1], "lp1": [1,0,1,0,0], "lp2":[1,1,0,0,1], "lp3":[0,0,1,1,1], "lp4":[0,1,1,0,0]})
df = df.astype(pd.CategoricalDtype([0, 1]))

# crosstab doesn't automiatically give the desired dense output, but the below is equivalent, and does
ct = df.groupby(['la', 'lp1', 'lp2', 'lp3']).size().unstack(0).T

lp1  0           1         
lp2  0     1     0     1   
lp3  0  1  0  1  0  1  0  1
la                         
0    0  1  0  0  0  0  1  0
1    0  0  1  1  0  1  0  0
```

**Comment by mroeschke** [comment]
Thanks for the question. Given the answer and that there's not necessarily an actionable task on the pandas library side, closing as a usage question
