### ISSUE TITLE
TYP tighten `any` return type

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#44802]
Currently, `any` returns `Series | bool`.

However, for `DataFrame.any` the return type should be `Series`, and for `Series.any` the return type should be `bool`.

Marking as good first issue, but please only attempt this if you already have some experience with Python typing and `mypy`.

**Comment by sglambert** [comment]
Hi @MarcoGorelli I've always wanted to contribute to Pandas. Would I be able to be assigned this issue? Cheers

**Comment by MarcoGorelli** [comment]
If you're familiar with mypy, sure, I'll assign you

**Comment by yadav-sachin** [comment]
@sglambert 
I want to take this issue. I have implemented some ideas. 
Are you still working on it?

**Comment by MarcoGorelli** [comment]
@yadav-sachin I think you're OK to take this on if you want
