### ISSUE TITLE
Add set operations to Series objects

### ISSUE THREAD

**Issue by cpcloud** [pandas-dev/pandas#4480]
from [this SO question](http://stackoverflow.com/questions/18079563/finding-the-intersection-between-two-series-in-pandas)

**Comment by milindsmart** [comment]
Any update on this? Is this still impossible? I was looking at doing a symmetric difference.

**Comment by h-vetinari** [comment]
This is something I would have needed several times in the last half year. Using `apply` is just terribly slow for large data sets (and `numpy` has fast set implementations like `np.intersect1d`).

To reiterate, I would like to have a `.set`-accessor, like there currently is for `.str`, `.dt`; examples below:

```
import pandas as pd # 0.21.0
import numpy as np # 1.13.3

# this function is just for demonstration purposes
def random_sets(n = 100):
    length = 10
    # strings of random numbers, padded to common length
    s = pd.Series(np.random.randint(0, 10**length-1, (n,), dtype = np.int64)).astype(str).str.zfill(length)
    # split into set of individual numbers and cast back to integers
    return s.map(set).apply(lambda s: set(int(x) for x in s)) 

a = random_sets(5)
# WANTED: a.set.intersect(set([1, 2])) should result in:
a.apply(lambda r: r & set([1, 2])) # intersection of 'a' with {1, 2}, e. g.
# 0    {1, 2}
# 1       {1}
# 2        {}
# 3    {1, 2}
# 4        {}

b = random_sets(5)
# WANTED a.set.intersect(b) should result in:
pd.concat([a, b], keys = ['a', 'b'], axis = 1).apply(lambda row: row['a'] & row['b'], axis = 1) # intersection of 'a' and 'b' (per row!), e. g.
# 0          {8, 1, 2}
# 1    {1, 3, 5, 7, 9}
# 2       {0, 8, 5, 9}
# 3       {8, 2, 3, 6}
# 4       {8, 9, 3, 6}
```

Like the `.str`-methods, it should work with either another `Series` (including index alignment), or broadcast a 'scalar' set correspondingly. Some important methods I think should be implemented (the function signature tries to indicate the action _per row_):

(set, set) -> set:
`a.set.intersect(b)` - as above
`a.set.union(b)` - row-wise union of `a` and `b`
`a.set.diff(b)` - row-wise set difference of `a` and `b`
`a.set.xor(b)` - row-wise symmetric difference of `a` and `b`

(set, set) -> bool:
`a.set.subset(b)` - row-wise check if `a` is subset of `b`
`a.set.superset(b)` - row-wise check if `a` is superset of `b`

(set, obj) -> bool:
`a.set.contains(c)` - row-wise check if `a` contains `c`

**Comment by jreback** [comment]
@h-vetinari sets are not efficiently stored, so this offers *only* an api benefit, which I have yet to see and interesting use case. You can use ``Index`` for these operations individually and that is quite efficient. ``Series.isin`` is pretty much ``.contains``. ``IntervalIndex`` will work for some of these cases as well.

**Comment by h-vetinari** [comment]
@jreback, well, I was hoping not just for an API improvement, but some fast cython code to back it up (like for the `.str`-methods). ;-)

Do I understand you correctly that you propose to work with `Series` of (short) `pd.Index`es? How would you then do something like `a.set.intersect(b)` (as described above)?

**Comment by jreback** [comment]
@h-vetinari and you are welcome to contribute things.  I the current impl would be quite inefficient and no each way to get around this ATM.

**Comment by chinchillaLiao** [comment]
import pandas as pd
df = pd.DataFrame({'a':{1,2,3}, 'b':{2,3,4}})

# Difference operator works between Series.
df['a - b'] = df['a'] - df['b']

# Set intersection operactor doesn't work between Series. 
df['a & b'] = df['a'] & df['b']

# A very slow way to do intersection between Series:
df['a & b'] = df.apply(lambda row: row['a'] & row['b'], axis = 1)

# I found it is much more faster to do intersection this way:
df['a - b'] = df['a']  - (df['a'] - df['b'])

# I don't know why.

**Comment by h-vetinari** [comment]
@chinchillaLiao : cool, didn't know set difference worked on Series! It's the only one to work on pandas level though.

But an even better work-around is to go down to the `numpy`-implementation with `.values`. In particular, this shouldn't suffer from the speed degradation you're reporting.

(@jreback; my comment half a year ago about a `.set`-accessor now seems very superfluous - why not just enable the numpy-behaviour directly in pandas?)

```
df = pd.DataFrame([[{1,2}, {2,3}],[{2,4}, {3, 1}]], columns=['A', 'B'])
df
#         A       B
# 0  {1, 2}  {2, 3}
# 1  {2, 4}  {1, 3}

df['A - B'] = df.A - df.B  # only one that work out of the box in pandas
df['A - B']
# 0       {1}
# 1    {2, 4}
# dtype: object

df['A & B'] = df.A & df.B
# TypeError: unsupported operand type(s) for &: 'set' and 'bool'
df['A & B'] = df.A.values & df.B.values
df['A & B'] 
# 0    {2}
# 1     {}
# Name: A & B, dtype: object

df['A | B'] = df.A | df.B
# TypeError: unsupported operand type(s) for |: 'set' and 'bool'
df['A | B'] = df.A.values | df.B.values
df['A | B'] 
# 0       {1, 2, 3}
# 1    {1, 2, 3, 4}
# Name: A | B, dtype: object

df['A ^ B'] = df.A ^ df.B
# TypeError: unsupported operand type(s) for ^: 'set' and 'bool'
df['A ^ B'] = df.A.values ^ df.B.values
df['A ^ B'] 
# 0          {1, 3}
# 1    {1, 2, 3, 4}
# Name: A ^ B, dtype: object

df
#         A       B   A - B A & B         A | B         A ^ B
# 0  {1, 2}  {2, 3}     {1}   {2}     {1, 2, 3}        {1, 3}
# 1  {2, 4}  {1, 3}  {2, 4}    {}  {1, 2, 3, 4}  {1, 2, 3, 4}
```

In terms of usability, the really cool thing is that this also works for `many-to-one` comparisons.

```
dd = df.A.to_frame()
C = {2, 5}
dd['A - C'] = df.A - C
dd['A & C'] = df.A.values & C
dd['A | C'] = df.A.values | C
dd['A ^ C'] = df.A.values ^ C

dd
#         A A - C A & C      A | C   A ^ C
# 0  {1, 2}   {1}   {2}  {1, 2, 5}  {1, 5}
# 1  {2, 4}   {4}   {2}  {2, 4, 5}  {4, 5}
```

**Comment by jreback** [comment]
sets are not first class and actually completely inefficient in a Series

**Comment by h-vetinari** [comment]
Inefficient as opposed to what? Some situations fundamentally require processing sets.

And even so, why make treating sets harder than it needs to be? I used to think (see my response from December) that this wasn't implemented at all, but since it's in `numpy` already, why not just expose that functionality on a `pandas` level? Sure as hell beats writing your own `.apply()` loops, both in terms of speed and code complexity.

**Comment by jreback** [comment]
complexity in terms of implementation and code

sure if u wanted to contribute would be great

but it’s not trivial to do in a first class supoorted way

**Comment by hayd** [comment]
@h-vetinari what is your use case for this? How does this come up?

IMO a nice way to contribute this would be with an [extension type](https://pandas.pydata.org/pandas-docs/stable/extending.html#extension-types) in a library. Depending on your use case. If you have a smallish finite super-set you can describe each set as a bitarray (and hence do set operations cheaply).

Note: This is quite different from the original issue: set operations like `set(s1) & set(s2)`...

**Comment by h-vetinari** [comment]
@jreback 

OK, I'm thinking about contributing that. Since the numpy-methods I showed above are actually not nan-safe,
```
np.array([{1,2}, np.nan]) | np.array([{2,4}, {3, 1}])
# TypeError: unsupported operand type(s) for |: 'float' and 'set'
```
I'm back to thinking that a set accessor for Series (not for Index) would be the best. And, since I wouldn't have to write the cython for those methods, I think I can come up with such a wrapper relatively easily.

@hayd 
Thanks for the link. I've had several use cases over time, e.g. joining email-addresses/telephone numbers when deduplicating user information. But it keeps cropping up. I'm actually really happy I found out about those numpy-methods some days ago. ;-)

Re: 
> Note: This is quite different from the original issue: set operations like set(s1) & set(s2)...

I've chosen to comment on this issue (rather than opening a new one) due to the title, which imo has a much larger scope. I could easily open a more general issue, if desired.

**Comment by jbrockmendel** [comment]
Discussed on today's dev call and the consensus was to convert your Series to Index and do setops on those.  Closing.
