### ISSUE TITLE
BUG: `groupby.apply()` inconsistently indexes its return value with the groupby-cols

### ISSUE THREAD

**Issue by ypsah** [pandas-dev/pandas#44803]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame(dict(
    name=["Alice", "Bob", "Carl", "Dan", "Eve"],
    age=[20, 21, 20, 21, 20],
    height=[165, 175, 189, 182, 157],
    weight=[65, 72, 95, 83, 58],
)).set_index("name")

indexed_by_age = df.groupby(["age"]).apply(lambda group: group.copy())
print(indexed_by_age)

print()
print("=" * 30)
print()

indexed_only_by_name = df.groupby(["age"]).apply(lambda group: group)
print(indexed_only_by_name)
```

### Issue Description

The above snippet produces the following output:

```
           age  height  weight
age name
20  Alice   20     165      65
    Carl    20     189      95
    Eve     20     157      58
21  Bob     21     175      72
    Dan     21     182      83

==============================

       age  height  weight
name
Alice   20     165      65
Bob     21     175      72
Carl    20     189      95
Dan     21     182      83
Eve     20     157      58
```

Where we can see that despite the return values of the `apply-func` being semantically identical (`group` vs. `group.copy()`), one ends up being indexed with `age` and `name` while the other only gets `name`.

### Expected Behavior

I would have expected the two returned dataframes to be the same. I have a personal preference for the first option, with the `age` appearing in the index, but I think I would be able to work with both.

-----

I know other inconsistencies have been reported:
- #22545
- #22546

But IMHO never as clearly as this. I'm hoping this reproducer helps diagnose the issue more easily.
Interestingly, the difference only creeps up when `grouping_keys` is set to `True`. Otherwise, we get the second output twice.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.9.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.6-arch2-1
Version          : #1 SMP PREEMPT Thu, 02 Dec 2021 15:47:09 +0000
machine          : x86_64
processor        :
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.4
numpy            : 1.21.4
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 58.5.3
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by v-liuwei** [comment]
I just met the same problem, and did some test. 

It seems that the `fast_apply` set the `mutated` to `True` in the `.copy()` case while set it to `False` in the other case. 

https://github.com/pandas-dev/pandas/blob/66e3805b8cabe977f40c05259cc3fcf7ead5687d/pandas/core/groupby/ops.py#L813-L820

And the truth value of `mutated` (the same as `not_indexed_same` here)will affect the concatenation of applied results:

https://github.com/pandas-dev/pandas/blob/66e3805b8cabe977f40c05259cc3fcf7ead5687d/pandas/core/groupby/groupby.py#L1003-L1067

I tried to disable the `fast_apply` （manually raise `IndexError` before it）, then it went to the slow apply in python code:

https://github.com/pandas-dev/pandas/blob/66e3805b8cabe977f40c05259cc3fcf7ead5687d/pandas/core/groupby/ops.py#L847-L855

and the value of `mutated` and the printed results of the two cases became consistent. 

### Summary
I think there is a bug that **the mutate checking of the fast apply**(supported by `apply_frame_axis0` from _libs.reduction.pyx) **and the slow apply are inconsistent.**

**Comment by ODemidenko** [comment]
I encounter a similar issue. 
In this case  whether group columns are added to the index depends on the amount fo rows returned by apply:
when it changes - group columns are added to the index. When it doesn't change - group columns aren't added.
The problem is, that the amount of rows may or may not change after applying exactly same code.
```
full_time_index = pd.Index(
        pd.to_datetime(['2020-01-01', '2020-01-03', '2020-01-10', '2020-01-15']),
        name='timestamp'
    )
group_cols = ['B']
df = pd.DataFrame({'A': [3, 1],
                   'B': ['foo', 'foo'],
                   'timestamp': full_time_index[::2]
                   }).set_index('timestamp')

def reindex_by_group(df, group_cols=group_cols, new_index=full_time_index):
    result = df.groupby(group_cols).apply(lambda d: d.reindex(new_index, fill_value=0)).drop(columns=group_cols)
    print(result.index.names)
    assert set(result.index.names) == set(['timestamp']+group_cols)

#this adds group column to index (desired behavior):
result = reindex_by_group(df, new_index=full_time_index)
result = reindex_by_group(df, new_index=full_time_index[:1])
result = reindex_by_group(df.iloc[:1], new_index=full_time_index)

#this fail:
result = reindex_by_group(df.iloc[:1], new_index=full_time_index[:1])
result = reindex_by_group(df, new_index=full_time_index[::2])
```
IMO, the most intuitive behavior is always adding group columns to index. The fact that 'transform' operations don't do it - was a major source of confustion for me and my colleagues.
And in the case above, in would be much more difficult to implement groupby with reindex, unless group columns are added to the index.

**Comment by mroeschke** [comment]
This is consistent on the master branch now (which will be reflected in the 1.4 release). This was probably most likely made consistent by https://github.com/pandas-dev/pandas/pull/42992

```
In [1]: import pandas as pd
   ...:
   ...: df = pd.DataFrame(dict(
   ...:     name=["Alice", "Bob", "Carl", "Dan", "Eve"],
   ...:     age=[20, 21, 20, 21, 20],
   ...:     height=[165, 175, 189, 182, 157],
   ...:     weight=[65, 72, 95, 83, 58],
   ...: )).set_index("name")
   ...:
   ...: indexed_by_age = df.groupby(["age"]).apply(lambda group: group.copy())
   ...: print(indexed_by_age)
   ...:
   ...: print()
   ...: print("=" * 30)
   ...: print()
   ...:
   ...: indexed_only_by_name = df.groupby(["age"]).apply(lambda group: group)
   ...: print(indexed_only_by_name)
       age  height  weight
name
Alice   20     165      65
Bob     21     175      72
Carl    20     189      95
Dan     21     182      83
Eve     20     157      58

==============================

       age  height  weight
name
Alice   20     165      65
Bob     21     175      72
Carl    20     189      95
Dan     21     182      83
Eve     20     157      58
```

Suppose could use a unit test to prevent a regression.

**Comment by aragard** [comment]
take

**Comment by pratimugale** [comment]
May I work on this?

**Comment by aragard** [comment]
Yes!

**Comment by NumberPiOso** [comment]
@pratimugale  are you working on this? If not, I would like to take it

**Comment by pratimugale** [comment]
@NumberPiOso you can take it

**Comment by NumberPiOso** [comment]
take

**Comment by NumberPiOso** [comment]
I did not understand if the output shown is the expected behaviour. However, I will do the test to keep outputs similar, regardless of the results

> This is consistent on the master branch now (which will be reflected in the 1.4 release). This was probably most likely made consistent by #42992
> 
> ```
> In [1]: import pandas as pd
>    ...:
>    ...: df = pd.DataFrame(dict(
>    ...:     name=["Alice", "Bob", "Carl", "Dan", "Eve"],
>    ...:     age=[20, 21, 20, 21, 20],
>    ...:     height=[165, 175, 189, 182, 157],
>    ...:     weight=[65, 72, 95, 83, 58],
>    ...: )).set_index("name")
>    ...:
>    ...: indexed_by_age = df.groupby(["age"]).apply(lambda group: group.copy())
>    ...: print(indexed_by_age)
>    ...:
>    ...: print()
>    ...: print("=" * 30)
>    ...: print()
>    ...:
>    ...: indexed_only_by_name = df.groupby(["age"]).apply(lambda group: group)
>    ...: print(indexed_only_by_name)
>        age  height  weight
> name
> Alice   20     165      65
> Bob     21     175      72
> Carl    20     189      95
> Dan     21     182      83
> Eve     20     157      58
> 
> ==============================
> 
>        age  height  weight
> name
> Alice   20     165      65
> Bob     21     175      72
> Carl    20     189      95
> Dan     21     182      83
> Eve     20     157      58
> ```
> 
> Suppose could use a unit test to prevent a regression.
