### ISSUE TITLE
BUG: rolling with method='table' and then apply with engine='numba' gets wrong result

### ISSUE THREAD

**Issue by sappersapper** [pandas-dev/pandas#44825]
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

df = pd.DataFrame({'A': range(4), 'B': [1, 2] * 2})
#    A  B
# 0  0  1
# 1  1  2
# 2  2  1
# 3  3  2

# right result:
df.rolling(2).apply(np.mean, raw=True, engine='numba')
#      A    B
# 0  NaN  NaN
# 1  0.5  1.5
# 2  1.5  1.5
# 3  2.5  1.5

# wrong result:
df.rolling(2, method='table').apply(np.mean, raw=True, engine='numba')
#      A    B
# 0  NaN  NaN
# 1  1.0  1.0
# 2  1.5  1.5
# 3  2.0  2.0
```

### Issue Description

When trying to `rolling` with numba engine, I found the `method='table'` described in the [doc ](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rolling.html?highlight=rolling#pandas.DataFrame.rolling) leads to wrong result. Did I set the wrong parameters? Or it is a bug?

### Expected Behavior

I suppose `df.rolling(2, method='table').apply(np.mean, raw=True, engine='numba')` returns the same result as `df.rolling(2).apply(np.mean, raw=True, engine='numba')` or `df.rolling(2).agg(np.mean)` returns.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.8.12.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19043
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Simplified)_China
pandas           : 1.3.4
numpy            : 1.21.4
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 59.4.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.54.0rc1+0.g9bed2ebb2.dirty

</details>

**Comment by mroeschke** [comment]
So this is the intended behavior albeit a little tricky.

When rolling table wise for the above `df`, the second row is equivalent to calculating
```
In [7]: arr = np.array([[0., 1.],
   ...:                 [1., 2.]])

In [8]: np.mean(arr)
Out[8]: 1.0
```

And the `1.0` is broadcasting to the resulting row.

You can try to bypass this by creating a UDF with `mean`, but appears that numba is not supporting the axis argument 

```
In [4]: def f(x):
   ...:     return x.mean(axis=1)

In [5]: df.rolling(2, method='table').apply(f, raw=True, engine='numba')
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function mean at 0x7fd850452ca0>) found for signature:

 >>> mean(array(float64, 2d, A), axis=Literal[int](0))

There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'Numpy_method_redirection.generic': File: numba/core/typing/npydecl.py: Line 348.
    With argument(s): '(array(float64, 2d, A), axis=Literal[int](0))':
   Rejected as the implementation raised a specific error:
     TypingError: numba doesn't support kwarg for mean
```

Note in this case, you can just use `method="table"` with mean directly

```
In [8]: df.rolling(2, method='table').mean(engine='numba')
Out[8]:
     A    B
0  NaN  NaN
1  0.5  1.5
2  1.5  1.5
3  2.5  1.5
```
