### ISSUE TITLE
ENH: inverse / reverse function of convert_dtypes

### ISSUE THREAD

**Issue by EuanRichard** [pandas-dev/pandas#44842]
#### Is your feature request related to a problem?

Pandas provides a choice - work with external datatypes (and face the many complexities and annoyances of dealing with NaN data), or work with the new internal datatypes (and face compatibility issues with external libraries, including those that have some integration with Pandas, such as `sklearn` / `xgboost`.).

#### Describe the solution you'd like

[convert_dtypes](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.convert_dtypes.html) is the function for changing types from external, to internal with `pd.NA` support. For example: `int32` → `Int32`, `bool` → `boolean` etc.

This is great, but I would like to add the inverse function (`Int32` → `int32`, etc.).

It would of course have to come with a parameter for treating NA types on return - for example,`fillna=...`.

#### API breaking implications

No existing API features changed (potentially this could be added to `convert_dtypes` as a new optional argument).

#### Describe alternatives you've considered

It's possible to handle this manually of course, but when dealing with hundreds of columns and complex joins, this becomes an extremely useful convenience function - you can work in Pandas datatypes the whole time, then switch back as a single final operation.

Of course maybe I'm being stupid and missing some other easy alternatives...

**Comment by jbrockmendel** [comment]
similar to #35694?

**Comment by EuanRichard** [comment]
Yes, exactly the same - sorry I didn't find that one. Then please ignore this and consider this a +1 for the other request. Thanks.
