### ISSUE TITLE
ENH: `DataFrame.apply` returns None if the function is not applicable

### ISSUE THREAD

**Issue by realliyifei** [pandas-dev/pandas#44860]
#### Is your feature request related to a problem?

I wise `DataFrame.apply` can return None if the function is not applicable

#### Describe the solution you'd like

Add an optional boolean argument (e.g. `return_none`) to `DataFrame.apply` and when it’s true it will return None to the cell if the function is not applicable 

#### Demo

Now, every time I need to try something like

```python
def func(...):
    try:
        return xxx
    except:
        return None

df.apply(func)
```

but if this proposal feature exists, we can via one line

```python
df.apply(lambda xxx, return_none=True)
```

**Comment by jreback** [comment]
it's possible result_type would work for this

but as you have stated this it's impossible to know if a function is applicable or not so this api doesn't make sense
