### ISSUE TITLE
ENH: Allow multiple date format outputs using to_csv

### ISSUE THREAD

**Issue by Wouittone** [pandas-dev/pandas#44865]
#### Is your feature request related to a problem?

I need to export a dataframe which includes multiple datetime columns to a csv file, with different datetime formats (my use case is having event dates on one hand, and revision or logging dates on the other hand)

#### Describe the solution you'd like

Accepting a dictionary of datetime columns with their associated export formats

#### API breaking implications

N/A, I believe this should only be an addition to the exisiting features

#### Describe alternatives you've considered

I could not find any

#### Additional context

This is my first request, and even though I am quite familiar with Pandas and its documentation, I might very well have missed an exisitng option. Thanks for pointing me to the proper of doing this if it's already available, otherwise I'll be happy to contribute to this feature.

#### Expected Output

```python
>>> import pandas as pd
>>> df = pd.DataFrame(data=[['2021-12-13', '2021-12-13 16:54:00']], columns=['event', 'logged'], dtype='datetime64[ns]')
>>> df.to_csv()
',event,logged\n0,2021-12-13 00:00:00,2021-12-13 16:54:00\n'
>>> df.to_csv(date_format={'event': '%d/%m/%Y', 'logged': '%Y-%m-%d %H:%M'})
',event,logged\n0,13/12/2021,2021-12-13 16:54\n'
```

**Comment by BlaneG** [comment]
You can format dates using `strftime`:
```
df.event = df.event.dt.strftime("%Y/%m/%d")
df.logged = df.logged.dt.strftime('%Y-%m-%d %H:%M')
```

**Comment by mroeschke** [comment]
Thanks for the request. The given example above would be the idiomatic way to format dates in a csv output as `date_format` method in other APIs consistently means formatting dates across all columns. So I would be -1 on this change.

**Comment by mroeschke** [comment]
Thanks for the request, but since this enhancement request hasn't gotten more interest from the core team and community, closing.
