### ISSUE TITLE
ENH: change pd.read_json kwarg to rtype or return_type?

### ISSUE THREAD

**Issue by ammarasmro** [pandas-dev/pandas#44881]
#### Is your feature request related to a problem?
Curious to know why pd.read_json has kwarg `typ` instead of `rtype` or `return_type`? Sorry if the answer is too simple but I couldn't find something that could explain it and `typ` might not be trivial to guess.

#### Describe the solution you'd like
few ways I guess (assuming there isn't a component that would break from this change)
- Change variable to `rtype`
- Change variable to `return_type`
- Update documentation to reflect reason for choice of variable name

#### API breaking implications

[this should provide a description of how this feature will affect the API]

#### Describe alternatives you've considered

[this should provide a description of any alternative solutions or features you've considered]

#### Additional context

[add any other context, code examples, or references to existing implementations about the feature request here]

```python
pd.read_json(typ='series')

```

**Comment by ammarasmro** [comment]
Happy to help with it if people agree it's an issue

**Comment by mroeschke** [comment]
Maybe the intention was for this kwarg to be `type`, but that is a built-in function in Python.

While `return_type` would be a better name, changing it would require a deprecation cycle since it's an API change which may not purely be worth the API churn.

**Comment by mroeschke** [comment]
Thanks for the report, but it appears there's no appetite to change this keyword so closing
