### ISSUE TITLE
BUG: DataFrame[interval[td64]] transpose fails 

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#44917]
```
tdi = pd.timedelta_range("0 Days", "3 Days")
ii = pd.IntervalIndex.from_breaks(tdi)
ii = ii.insert(-1, np.nan)
df = pd.DataFrame(ii)

>>> df.T
[...]
TypeError: Cannot convert Float64Index to dtype timedelta64[ns]; integer values are required for conversion
```

This would be solved by having 2D EAs.

**Comment by sukriti1** [comment]
take

**Comment by weikhor** [comment]
@jbrockmendel Hi I see this from above `This would be solved by having 2D EAs.`  . May I know what is meaning of `2D EAs`?

**Comment by jbrockmendel** [comment]
2D EAs means making all ExtensionArrays support 2D.  There is not consensus on doing this, which seems unlikely to change.

**Comment by weikhor** [comment]
> 2D EAs means making all ExtensionArrays support 2D.  There is not consensus on doing this, which seems unlikely to change.

Ok thank
