### ISSUE TITLE
BUG: String with less-than sign gets truncated when added to a dataframe.

### ISSUE THREAD

**Issue by kimobu** [pandas-dev/pandas#44915]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd
l = ['bash -c </dev/tcp/wtf', 'bash -c >/dev/tcp/wtf', 'bash -c 1</dev/tcp/wtf', r'''bash -c </dev/tcp''']
df = pd.DataFrame(l)
df
```

### Issue Description

When a string contains a less-than symbol, its result gets truncated. Instead of 'bash -c </dev/tcp/wtf', only 'bash -c' is copied.

### Expected Behavior

The entire string should be copied.

### Installed Versions

<details>

1.3.5

</details>

**Comment by phofl** [comment]
This seems to work for me.
```
                        0
0   bash -c </dev/tcp/wtf
1   bash -c >/dev/tcp/wtf
2  bash -c 1</dev/tcp/wtf
3       bash -c </dev/tcp
```

If this is not your expected result then please narrow your example down. If the less sign is the issue most of your string is irrelevant

**Comment by kimobu** [comment]
Weird, I tried this in a couple of other environments and it worked properly. Must be some local issue. Sorry about that.
