### ISSUE TITLE
BUG: Pandas differently interprets `int` dtype on Linux/Windows

### ISSUE THREAD

**Issue by prutskov** [pandas-dev/pandas#44925]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd

data = {
        "A": pd.bdate_range("1/1/2009", periods=5),
    }

df = pd.DataFrame(data)
df2 = df.astype({"A": int})

print(df2)
```

### Issue Description

On Linux the script works well because `int` is interpreted as `int64`, but on Windows as `int32`:

```bash

    df2 = df.astype({"A": int})
  File "C:\Users\aprutsko\.conda\envs\tmp\lib\site-packages\pandas\core\generic.py", line 5799, in astype
    col.astype(dtype=dtype[col_name], copy=copy, errors=errors)
  File "C:\Users\aprutsko\.conda\envs\tmp\lib\site-packages\pandas\core\generic.py", line 5815, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\aprutsko\.conda\envs\tmp\lib\site-packages\pandas\core\internals\managers.py", line 418, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\aprutsko\.conda\envs\tmp\lib\site-packages\pandas\core\internals\managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Users\aprutsko\.conda\envs\tmp\lib\site-packages\pandas\core\internals\blocks.py", line 591, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "C:\Users\aprutsko\.conda\envs\tmp\lib\site-packages\pandas\core\dtypes\cast.py", line 1309, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "C:\Users\aprutsko\.conda\envs\tmp\lib\site-packages\pandas\core\dtypes\cast.py", line 1242, in astype_array
    raise TypeError(msg)
TypeError: cannot astype a datetimelike from [datetime64[ns]] to [int32]
```

### Expected Behavior

The same behavior as for Linux:
```bash
                     A
0  1230768000000000000
1  1230854400000000000
2  1231113600000000000
3  1231200000000000000
4  1231286400000000000

FutureWarning: casting datetime64[ns] values to int64 with .astype(...) is deprecated and will raise in a future version. Use .view(...) instead.
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.7.11.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.3.4
numpy            : 1.20.3
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 58.0.4
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.30.1
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.2
fsspec           : 2021.10.1
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.2
numexpr          : 2.7.3
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 3.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.6.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.54.1

</details>

**Comment by mzhou23** [comment]
Hi, I'm a college student majored in computer science. I'm trying to make contribution to an open source project for my final. About this bug, I found that 
```
if (
        values.dtype.kind in ["m", "M"]
        and dtype.kind in ["i", "u"]
        and isinstance(dtype, np.dtype)
        and dtype.itemsize != 8
    ):
        # TODO(2.0) remove special case once deprecation on DTA/TDA is enforced
        msg = rf"cannot astype a datetimelike from [{values.dtype}] to [{dtype}]"
        raise TypeError(msg)
```
in [pandas/pandas/core/dtypes/cast.py](https://github.com/pandas-dev/pandas/blob/master/pandas/core/dtypes/cast.py).
This if statement is the reason for getting a bug in the windows system. (32-bit integer has an itemize of 4.), since we can't change 64-bit datetime type to 32-bit integer. A possible solution is automatically adjust 32-bit int dtype to 64-bit int dtype and send the warning message. Since I haven't made a contribution before, can someone take a look at my solution to verify my thought? Thank you!!!

**Comment by jbrockmendel** [comment]
The underlying issue is that we are following numpy's behavior (actually just using `np.dtype(dtype)` in `pd.core.dtypes.common.pandas_dtype`).  (i dont have a windows machine so please double-check me on this).  i dont  think we can change this on our end.

**Comment by jbrockmendel** [comment]
> Since I haven't made a contribution before, can someone take a look at my solution to verify my thought? Thank you!!!

@mzhou23 I suggest you look at issues with the "Good First Issue" label

**Comment by mzhou23** [comment]
> The underlying issue is that we are following numpy's behavior (actually just using `np.dtype(dtype)` in `pd.core.dtypes.common.pandas_dtype`). (i dont have a windows machine so please double-check me on this). i dont think we can change this on our end.

Thank you for recommendation and explanation.

**Comment by simonjayhawkins** [comment]
> The underlying issue is that we are following numpy's behavior

see numpy/numpy#9464. closing.
