### ISSUE TITLE
BUG: Apply pd.get_dummies() on string type columns of pandas dataframe do nothing?

### ISSUE THREAD

**Issue by stevesolun** [pandas-dev/pandas#44965]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

I have the following dataframe:

```
df = pd.DataFrame({'a': [6.6, -5.2, 2.1, 3.3, 1.1],
              'b': ['a', 'a', 'c', 'b', 'a'],
              'c': ['kfr', 'kfr', 'lu', 'ku', 'lu'],
              'd': ['t', 's', 's', 't', 'a']})
```
All the dtypes (columns b, c, d) are of type string.

If I call `df = df.convert_dtypes()`, and then call `pd.get_dummies()`, nothing happens:

```
df = pd.DataFrame({'a': [6.6, -5.2, 2.1, 3.3, 1.1],
              'b': ['a', 'a', 'c', 'b', 'a'],
              'c': ['kfr', 'kfr', 'lu', 'ku', 'lu'],
              'd': ['t', 's', 's', 't', 'a']})
df = df.convert_dtypes()
pd.get_dummies(df)
```

But if I will change the `df.convert_dtypes()` to `df.convert_dtypes(convert_string=False) ` it will work as expected.
Why is this happening? Is it a bug?

### Expected Behavior

pandas `pd.get_dummies()` should work on strings columns dtype also.

### Installed Versions

<details>
1.3.5
</details>

**Comment by cheruiyot-amon** [comment]
when you write the pd.get_dummies() without the dataframe inside the bracket, it will throw some errors. The best you can do is create a variable say ,,"dummies"
dummies=pd.get_dummies(name_of_dataframe)

**Comment by stevesolun** [comment]
> when you write the pd.get_dummies() without the dataframe inside the bracket, it will throw some errors. The best you can do is create a variable say ,,"dummies" dummies=pd.get_dummies(name_of_dataframe)

What does it do to fix the bug?

**Comment by cheruiyot-amon** [comment]
It will create dummies for data series in a dataframe. It will convert the
strings into zeros and ones .

**Comment by cheruiyot-amon** [comment]
Just write this code:
dummies=pd.get_dummies(df) 
print(dummies)
.This will fix your problem

**Comment by stevesolun** [comment]
I am sorry but it's not the problem here...
The problem is that if I am using convert_dtypes() on my df before get_dummies() it will return the same df without any change. Please read the question again and go step by step. Your solution doesn't solve the bug.

**Comment by cheruiyot-amon** [comment]
For your case, I think it is not possible to convert strings to integers, float, or even boolean. However, you can convert an integer to float and vice versa.

**Comment by stevesolun** [comment]
Did you run my example?
I am able to solve it if I will explicitly tell convert_dtypes() to skip converting strings.

**Comment by cheruiyot-amon** [comment]
Yes. I did run your example. could you please send a screenshot a code so that i could have a look at it

**Comment by stevesolun** [comment]
I am sorry but if you were able to reproduce the issue, can you please suggest a fix? You are one of the pandas developers?
Maybe we can create a Zoom call?

**Comment by cheruiyot-amon** [comment]
I am aspiring to become one. I started learning data science recently.

**Comment by MarcoGorelli** [comment]
Hi @stevesolun 

I think @cheruiyot-amon 's point is that your example does run as it's written - in order to expedite resolution, could you fix it up so it can be easily copy-and-pasted please?

**Comment by stevesolun** [comment]
@MarcoGorelli sure, will do it now.

**Comment by asishm** [comment]
To minimize this

```py
>>> df = pd.DataFrame({'a': ['a', 'b']})
>>> print(pd.get_dummies(df))
   a_a  a_b
0    1    0
1    0    1
>>> print(pd.get_dummies(df.convert_dtypes()))
   a
0  a
1  b
```

**Comment by MarcoGorelli** [comment]
I see - thanks for the report, and @asishm for the minimal code !

**Comment by asishm** [comment]
Issue is because `pd.get_dummies` only selects the dtypes - object, category to encode, but with `convert_dtypes` they are now of dtype `string`

https://github.com/pandas-dev/pandas/blob/a3c0e7bcfb8bbe9ca45df7e571a305d403e0f066/pandas/core/reshape/reshape.py#L913

**Comment by stevesolun** [comment]
@asishm @lithomas1 thanks a lot!
It's a bug or by design? Does it mean that the dev team will change the behavior of get_dummies to support strings also?

**Comment by lukemanley** [comment]
take
