### ISSUE TITLE
BUG: ImportError due to missing symbol "_ZTINSt8ios_base7failure85Scxx11E"

### ISSUE THREAD

**Issue by muellert** [pandas-dev/pandas#44963]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
I am trying to install Pandas via pip on a self-compiled Python 3.9.9 on a Linux machine, but get that this symbol is not defined.

This bug report refers to a problem with the installation of Pandas, not with its usage.
```

### Issue Description

The path is /path/to/my/python/lib/python3.9/site-packages/pandas/_libs/window/aggregation.cpython-3.9-x86_64-linux-gnu.so

I have tried to delete and reinstall pandas using

/.../pip3 install --force-reinstall pandas

which should have given me the latest version of pandas, since I had also deleted the pip cache beforehand, but the symbol is still undefined, and thus, I cannot make use of Pandas.

This is on SLES11SP3 - sorry about that, I can't help it.

### Expected Behavior

I would like to see that I can import and use Pandas without any issues, eg.

>>> import pandas
>>>

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

Since I get a traceback with an ImportError, upon trying to import pandas, I can't execute the code specified above.

pandas 1.3.5

**Comment by jbrockmendel** [comment]
Is the problem at install time or import time?

**Comment by muellert** [comment]
The problem is at import time. I had done private version of Python 3.9.6 on the same system a few months ago, where I also installed Pandas, and where I can import it without a problem, but at the moment, I can't access the system right now to tell you which Pandas version it was. However, that version had other problems, which is why I started over with 3.9.9.

**Comment by muellert** [comment]
I could get the full traceback. Paths obfuscated, but the rest is intact:

```
hostname:/path/to/python/build/dir/python39 # /opt/python-3.9.9/bin/python
Python 3.9.9 (main, Dec 18 2021, 21:18:55)
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python-3.9.9/lib/python3.9/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/opt/python-3.9.9/lib/python3.9/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/opt/python-3.9.9/lib/python3.9/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
 File "/opt/python-3.9.9/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/opt/python-3.9.9/lib/python3.9/site-packages/pandas/core/frame.py", line 129, in <module>
    from pandas.core import (
  File "/opt/python-3.9.9/lib/python3.9/site-packages/pandas/core/generic.py", line 144, in <module>
    from pandas.core.window import (
  File "/opt/python-3.9.9/lib/python3.9/site-packages/pandas/core/window/__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (  # noqa:F401
  File "/opt/python-3.9.9/lib/python3.9/site-packages/pandas/core/window/ewm.py", line 11, in <module>
    import pandas._libs.window.aggregations as window_aggregations
ImportError: /opt/python-3.9.9/lib/python3.9/site-packages/pandas/_libs/window/aggregations.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZTINSt8ios_base7failureB5cxx11E
>>>
```

**Comment by MarcoGorelli** [comment]
> on a self-compiled Python 3.9.9

can you try on a non-self-compiled Python (e.g. in a `conda` environment) please? If it works there, I'd suggest the issue might be with your environment

**Comment by muellert** [comment]
No, I can't. For a number of reasons, we can't have standard OS packages or other pre-compiled stuff, and need to compile everything ourselves. And the same thing works without a problem on a self-compiled Python 3.9.6 using the same build script, which resides in /opt/python-3.9.6. There, I have:

```
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : f00ed8f47020034e752baf0250483053340971b0
python           : 3.9.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.0.101-0.7.44-default
Version          : #1 SMP Wed Oct 19 14:28:11 UTC 2016 (ad8e171)
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.utf8
LANG             : en_US.utf8
LOCALE           : en_US.UTF-8

pandas           : 1.3.0
numpy            : 1.20.1
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.0.1
setuptools       : 56.0.0
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.0.2
IPython          : 7.29.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.4.21
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
>>>
```

**Comment by MarcoGorelli** [comment]
> FWIW, I just have successfully installed Pandas 1.3.0 for Python 3.9.9, so I guess the problem lies between Pandas 1.3.0 and Pandas 1.3.5.

could you try narrowing this down? perhaps installing pandas from source (check the contributing guide) and doing `git bisect`

**Comment by muellert** [comment]
I have found that the problem starts in Pandas 1.3.1, so 1.3.0 is fine, but in 1.3.1, I get this undefined symbol.

**Comment by jbrockmendel** [comment]
when you install, is it using a wheel or does it build from source?  looks like you don't have cython installed so building should fail

**Comment by muellert** [comment]
It builds a wheel and then installs it (typing from the screen of the other system):
```
Collecting pandas==1.3.1
  Downloading pandas-1.3.1.tar.gz (4.7 MB)
      (progress bar here)
  Installing build ependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: python-dateutil...
...
```
The entire process takes quite some time.

**Comment by mroeschke** [comment]
Thanks for the issue, but appears that the team doesn't quite have enough information to sufficiently debug given the circumstances of the installation. Closing, but happy to reopen if more context could be provided
