### ISSUE TITLE
DOC: typo in describe_option

### ISSUE THREAD

**Issue by TudorRus-ETS** [pandas-dev/pandas#44970]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

![image](https://user-images.githubusercontent.com/25108392/146685857-5a16c936-91b6-412c-a608-fcbc6636ab44.png)

### Documentation problem

The help function on python3.9 currently has a spelling mistake.
The line shown in the picture says not instead of no 

### Suggested fix for documentation

Replace the not with a no for better grammatical structure.
Call with not arguments to get listing for all registered options SHOULD RATHER BE 
>> 
Call with no arguments to get listing for all registered options

**Comment by bonsoirval** [comment]
I have to trying to find the DOC to correct the typo but I seem not to be finding it easy locating the Doc. Someone should help me please @TudorRus-ETS

**Comment by MarcoGorelli** [comment]
Hey - have you tried using `git grep` and searching for parts of the quoted text?

**Comment by bonsoirval** [comment]
I am yet to do that please. I am a newbie so a couple of things might not be easy at first look. Please kindly direct me on to do this. 
Do I have to fork and clone first or what are the steps? Thanks

**Comment by bonsoirval** [comment]
Just saw it now. Thanks

**Comment by MarcoGorelli** [comment]
No worries! If you search "pandas contributing guide" you should find all the instructions

**Comment by tyleralgigi** [comment]
Hello, this is also my first time contributing. I created a commit that fixes the issue, how would I go about linking my commit and the issue?

**Comment by MarcoGorelli** [comment]
Looks like @bonsoirval is already working on this

**Comment by MarcoGorelli** [comment]
@TudorRus-ETS for the future, there's no need to open an issue about a minor typo, you can just open a PR and fix it if you think it needs changing

**Comment by bonsoirval** [comment]
@MarcoGorelli please I got an email with a link that directed me to this location - https://github.com/pandas-dev/pandas/actions/runs/1602512609
I do not understand it please, some one should clarify me, a newbie please.

**Comment by MarcoGorelli** [comment]
> @MarcoGorelli please I got an email with a link that directed me to this location - https://github.com/pandas-dev/pandas/actions/runs/1602512609 I do not understand it please, some one should clarify me, a newbie please.

it's unrelated, don't worry about it, the previous commit had it too
