### ISSUE TITLE
DOC: broken "Test-driven development/code writing" and "Code standards" links.

### ISSUE THREAD

**Issue by sarusso** [pandas-dev/pandas#44985]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://github.com/pandas-dev/pandas/blob/master/.github/CONTRIBUTING.md

### Documentation problem

The links "Test-driven development/code writing" and "Code standards" leads to not (anymore?) existing anchors on the docs.

### Suggested fix for documentation

Either remove the links or fix them, possibly by re-inserting info about test-driven development/code writing and code standards.

**Comment by simonjayhawkins** [comment]
Thanks @sarusso for the report

> Either remove the links or fix them, possibly by re-inserting info about test-driven development/code writing and code standards.

PR to fix broken links welcome.

**Comment by simonjayhawkins** [comment]
> PR to fix broken links welcome.

On second thoughts on not sure what value https://github.com/pandas-dev/pandas/blob/master/.github/CONTRIBUTING.md adds.

Could just remove it and the link to it from https://github.com/pandas-dev/pandas#contributing-to-pandas-

> A detailed overview on how to contribute can be found in the contributing guide. There is also an overview on GitHub.

The markdown file seems to duplicate the overview in README.md and therefore the  https://pandas.pydata.org/docs/dev/development/contributing.html#where-to-start in the contributing guide in the main docs is probably as good an overview.

**Comment by sarusso** [comment]
Ouch about seconds... I just submitted the PR for fixing the links. Let me create another one.

**Comment by simonjayhawkins** [comment]
> Ouch about seconds... I just submitted the PR for fixing the links. Let me create another one.

leave that one open. fixing the links should get approved quickly. My suggestion to delete the file will need more scrutiny.
