### ISSUE TITLE
ENH: Allow passing a function to the `keep` parameter of `duplicated` and `drop_duplicates` to choose which rows get kept in each duplicate group

### ISSUE THREAD

**Issue by Xnot** [pandas-dev/pandas#45003]
#### Is your feature request related to a problem?
I think it would be useful to be able to drop duplicates from a DataFrame while keeping one or more of the duplicated rows through an arbitrary selection method.

#### Describe the solution you'd like
Allow passing a function to the `keep` parameter of `duplicated` and `drop_duplicates`. Whenever there is a group of duplicates, pandas calls this function to determine which of the rows within the duplicate group get kept. The function should take one parameter, a DataFrame-like containing all rows within a given duplicate group (including columns outside of the subset parameter), and return the index or indices of the rows within the group to be kept.

Example:
```py
def keep_first(duplicate_group):
    return duplicate_group.iloc[[0], :].index

def keep_first_and_fourth(duplicate_group):
    return duplicate_group.iloc[[0, 3], :].index

def keep_very_important(duplicate_group):
    return duplicate_group.iloc[duplicate_group["very_important"], :].index
```
```py
>>> df
   a  very_important
0  1            True
1  1           False
2  1            True
3  1           False
4  2           False
5  3           False
>>> df.drop_duplicates(["a"], keep=keep_first)
   a  very_important
0  1            True
4  2           False
5  3           False
>>> df.drop_duplicates(["a"], keep=keep_first_and_fourth)
   a  very_important
0  1            True
3  1           False
4  2           False
5  3           False
>>> df.drop_duplicates(["a"], keep=keep_very_important)
   a  very_important
0  1            True
2  1            True
4  2           False
5  3           False
```

#### API breaking implications
None

#### Describe alternatives you've considered
The best alternative I can think of to achieve this currently is using `groupby` on the `subset` columns and using `apply` or looping through the groups to concatenate the selected rows to a new DataFrame. Following the example above, it would look something like:
```py
def keep_very_important_apply(duplicate_group):
    if len(duplicate_group.index) == 1:
        # no duplicates
        return duplicate_group
    return duplicate_group.loc[duplicate_group["very_important"], :]

df.groupby("a", group_keys=False).apply(keep_very_important_apply)
```

**Comment by jreback** [comment]
you could simply run with `keep='first'` and `keep='last'` and then just do a `np.where` to select between these. I am not sure its worth adding this.

**Comment by aa1371** [comment]
No comment in favor or against this enh, but here are some alternative existing ways you can achieve some of the more complex drop duplicate behaviors you provided in your example

```
# keep first and fourth
df.loc[df.groupby('a').cumcount().isin([0, 3])]

# keep first and very important
df.loc[(~df.a.duplicated()) | (df.very_important)]
```

**Comment by mroeschke** [comment]
Agreed I think chaining post processing commands would be equivalent to passing a callable into `keep` and therefore I would be -1 on this change as well.

Thanks for the request, but since there hasn't been support from other core devs or the community going to close. Happy to reopen if there's revived support.
