### ISSUE TITLE
ENH: colormap support for `DataFrame.to_latex()`

### ISSUE THREAD

**Issue by Zac-HD** [pandas-dev/pandas#45020]
I've [recently written a paper](https://arxiv.org/abs/2112.10328) where we converted some of our [`sns.heatmap()`](https://seaborn.pydata.org/generated/seaborn.heatmap.html) figures to true LaTeX tables, keeping the cell coloring:

<img src="https://user-images.githubusercontent.com/12229877/147173501-1d2da178-099b-44f9-92c1-ab07cff9136c.png" alt="drawing" width="400"/>

**It would be lovely if Pandas could do this**; while my implementation is pretty ugly @rsokl suggested that colormapped tables could improve many papers.

Concretely, I think this would involve adding two new arguments, `cmap` and `norm`, to `DataFrame.to_latex()`; interpreted in the usual way for plotting functions.  That's a non-breaking API change, though it would need some consideration of what should happen (probably error messages) for non-numeric inputs - I also had a duration (`timedelta`) table colored by `.total_seconds()`, but it seems reasonable to push that back to custom user code.

```python
def value_to_table_cell(n):
    txt = f'{int(n):,}'  # whatever format the user supplied
    if np.isnan(n):
        return txt  # unclear how NaN should be colored; default no color

    # I'm sure there's a more elegant way to do this, but we had a deadline...
    colors = matplotlib.cm.inferno_r.colors
    x = LogNorm(vmin=0.5, vmax=200)(n + 0.5)
    idx = int(x * len(colors))
    r, g, b = colors[max(0, min(idx, len(colors)-1))]

    # If the selected color is darker than 50% grey, make the text white
    color = "" if r + b + g >= 1.5 else  r"\color{white} "

    # Put it all together!  And don't forget to \usepackage{colortbl}
    return f"\\cellcolor[rgb]{{{r},{g},{b}}} {color}{txt}"
```

Also happy to close if this is just out of scope 😁

**Comment by attack68** [comment]
Why not try Styler?
![Screen Shot 2021-12-23 at 20 03 16](https://user-images.githubusercontent.com/24256554/147282349-3bfcd5b9-f6d6-4800-9cb4-b7e45e820426.png)

```
>>> print(styler.to_latex(convert_css=True, hrules=True))

\begin{tabular}{lrrrrrrrrrr}
\toprule
 & 0 & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 \\
\midrule
0 & {\cellcolor[HTML]{F98C0A}} \color[HTML]{F1F1F1} 3.000000 & {\cellcolor[HTML]{FCFFA4}} \color[HTML]{000000} 0 & {\cellcolor[HTML]{FCFFA4}} \color[HTML]{000000} 0 & {\cellcolor[HTML]{DD513A}} \color[HTML]{F1F1F1} 8 & {\cellcolor[HTML]{F98C0A}} \color[HTML]{F1F1F1} 3 & {\cellcolor[HTML]{440A68}} \color[HTML]{F1F1F1} 78 & {\cellcolor[HTML]{FCFFA4}} \color[HTML]{000000} 0 & {\cellcolor[HTML]{F57B17}} \color[HTML]{F1F1F1} 4 & {\cellcolor[HTML]{F9C932}} \color[HTML]{000000} 1 & {\cellcolor[HTML]{F9C932}} \color[HTML]{000000} 1 \\
1 & {\cellcolor[HTML]{000000}} \color[HTML]{F1F1F1} nan & {\cellcolor[HTML]{FCFFA4}} \color[HTML]{000000} 0 & {\cellcolor[HTML]{FCFFA4}} \color[HTML]{000000} 0 & {\cellcolor[HTML]{D74B3F}} \color[HTML]{F1F1F1} 9 & {\cellcolor[HTML]{F9C932}} \color[HTML]{000000} 1 & {\cellcolor[HTML]{420A68}} \color[HTML]{F1F1F1} 80 & {\cellcolor[HTML]{FCFFA4}} \color[HTML]{000000} 0 & {\cellcolor[HTML]{F57B17}} \color[HTML]{F1F1F1} 4 & {\cellcolor[HTML]{F9C932}} \color[HTML]{000000} 1 & {\cellcolor[HTML]{F9C932}} \color[HTML]{000000} 1 \\
\bottomrule
\end{tabular}
```

![Screen Shot 2021-12-23 at 20 05 00](https://user-images.githubusercontent.com/24256554/147282482-f56937ef-2623-41dd-9393-c153e93ff8cf.png)

**Comment by attack68** [comment]
It might be a bug that the NaN cell is coloured.

**Comment by Zac-HD** [comment]
Oh, nice!  I didn't realize that Styler could export to LaTex (just checked; new-in-1.3 explains that).

Let's consider this a docs issue - adding a short note to `.to_latex()` mentioning that Styler gets exported properly would have pointed me in the right direction - or just close as "already implemented".  Thanks for the super-fast and helpful response! 😍

**Comment by attack68** [comment]
1.4.0 already has docs changes, and issues a warning that 2.0 will use the Styler implementation and replace the DataFrameLatexFormatter, since it has much more flexibility.
