### ISSUE TITLE
DOC: index and dropna docs missing from to_hdf docstring

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#45030]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.to_hdf.html?highlight=to_hdf#pandas.DataFrame.to_hdf

### Documentation problem

- dropna
- index

are missing from the docstring

### Suggested fix for documentation

Add them

**Comment by fanoway** [comment]
take

**Comment by fanoway** [comment]
take

**Comment by pree-T** [comment]
May I work on this?

**Comment by phofl** [comment]
There is already a pr linked, but you can look for some other good first issue

**Comment by anirudhlakhotia** [comment]
I'd like to take a shot at this if it's still open
