### ISSUE TITLE
DEPR: numeric_only=None in NDFrame.rank

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#45036]
We've deprecated it in DataFrame and groupby reductions, would be nice to get it here too.

**Comment by phofl** [comment]
Are you sure? In groupby numeric_only is not accepted and in DataFrame.rank this does not show a warning

**Comment by jbrockmendel** [comment]
> in DataFrame.rank this does not show a warning

I'm suggesting we should deprecated so that it does show a warning.

```
        # if numeric_only is None, and we can't get anything, we try with
        # numeric_only=True
        if numeric_only is None:
            try:
                return ranker(self)
            except TypeError:
                numeric_only = True
```

**Comment by phofl** [comment]
Ok sorry, misunderstood your initial comment

**Comment by jreback** [comment]
I would ideally like to kill `numeric_only` everywhere but i guess its convenient (rant)

**Comment by jbrockmendel** [comment]
> I would ideally like to kill numeric_only everywhere but i guess its convenient (rant)

we've mostly gotten rid of numeric_only=None, which is the biggest hassle
