### ISSUE TITLE
BUG: dt64.astype(period) allowed but not vice-versa

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#45038]
```
import pandas as pd

dti = pd.date_range("2016-01-01", periods=3)
pi = dti.to_period("D")

dti.astype(pi.dtype)  # <- OK
pi.astype(dti.dtype)  # <- works but deprecated in #44398

pd.Series(dti).astype(pi.dtype)  # <- OK
pd.Series(pi).astype(dti.dtype)  # <- raises
```

In #44398 we deprecated PeriodIndex.astype(dt64).  The motivation was that PeriodIndex.astype should be consistent with Series[Period].astype.  I chose to deprecate the PeriodIndex behavior instead of allow it in Series.astype bc there's an optional keyword in PeriodIndex.astype that we're deprecating anyway.

I'm having seconds thoughts based on the fact that we _do_ support `Series[dt64].astype(period)`, and it seems like these should be able to round-trip.

**Comment by jbrockmendel** [comment]
Added blocker label bc if we want to un-deprecate it will need to be before the release.

**Comment by jreback** [comment]
i think fine to undeprecate and match the series behavior here.

**Comment by jbrockmendel** [comment]
> i think fine to undeprecate and match the series behavior here.

So we're clear: the existing deprecation, when enforced, will change the PeriodIndex behavior to match the Series[Period] behavior.  This issue is suggesting we 1) un-deprecate and 2) change the Series[Period] behavior to match the PeriodIndex behavior.

**Comment by jbrockmendel** [comment]
putting together a branch now to Just Do It.
