### ISSUE TITLE
QST: Projects with low Build Activity - Survey

### ISSUE THREAD

**Issue by jadsonjs** [pandas-dev/pandas#45046]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

l

### Question about pandas

Dear Developers of project **pandas-dev/pandas,**

We are conducting a study on CI metrics and we noticed that in your project, something peculiar happened.

During the period you are using Travis CI, the project passed by a long period of inactivity.
We noticed that the TravisCI configuration file (.travis.yml) was committed to your project on the date of 2012-06-03.
But there is only a build history in TravisCI for a very short period, between 2020-12-07 and 2021-01-01, in which were performed suddenly 920 builds.

Please, we would like you to answer this short survey with just 4 questions to help us identify the cause of this behavior.

https://forms.gle/UkkFrxpi7MNscYmV7

**Comment by MarcoGorelli** [comment]
Hi - check https://github.com/pandas-dev/pandas/pull/41738 and #38943
