### ISSUE TITLE
QST: 

### ISSUE THREAD

**Issue by elu-123** [pandas-dev/pandas#45045]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions

### Question about pandas
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)
(6164, 43) (2642, 43) (6164, 2) (2642, 2)

classifier = BinaryRelevance(GaussianNB())
# train
classifier.fit(x_train, y_train)
# predict
predictions = classifier.predict(x_test)
accuracy_score(y_test,predictions)

TypeError                                 Traceback (most recent call last)
<ipython-input-47-8f3136b79f0f> in <module>
----> 1 accuracy_score(y_test,predictions)

~\anaconda3\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     61             extra_args = len(args) - len(all_args)
     62             if extra_args <= 0:
---> 63                 return f(*args, **kwargs)
     64 
     65             # extra_args > 0

~\anaconda3\lib\site-packages\sklearn\metrics\_classification.py in accuracy_score(y_true, y_pred, normalize, sample_weight)
    200 
    201     # Compute accuracy for each possible representation
--> 202     y_type, y_true, y_pred = _check_targets(y_true, y_pred)
    203     check_consistent_length(y_true, y_pred, sample_weight)
    204     if y_type.startswith('multilabel'):

~\anaconda3\lib\site-packages\sklearn\metrics\_classification.py in _check_targets(y_true, y_pred)
     83     check_consistent_length(y_true, y_pred)
     84     type_true = type_of_target(y_true)
---> 85     type_pred = type_of_target(y_pred)
     86 
     87     y_type = {type_true, type_pred}

~\anaconda3\lib\site-packages\sklearn\utils\multiclass.py in type_of_target(y)
    286 
    287     # Invalid inputs
--> 288     if y.ndim > 2 or (y.dtype == object and len(y) and
    289                       not isinstance(y.flat[0], str)):
    290         return 'unknown'  # [[[1, 2]]] or [obj_1] and not ["label_1"]

TypeError: len() of unsized object

**Comment by MarcoGorelli** [comment]
Hi - please include a example, check the link in the template, and try again
