### ISSUE TITLE
BUG: running pytest fails on master

### ISSUE THREAD

**Issue by jmg-duarte** [pandas-dev/pandas#45047]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
pytest pandas
```

### Issue Description

Running the `pytest` command fails with an import error

```
ImportError while loading conftest '/workspaces/pandas/pandas/conftest.py'.
pandas/conftest.py:537: in <module>
    "mi-with-dt64tz-level": _create_mi_with_dt64tz_level(),
pandas/conftest.py:505: in _create_mi_with_dt64tz_level
    return MultiIndex.from_product(
pandas/core/indexes/multi.py:619: in from_product
    codes, levels = factorize_from_iterables(iterables)
pandas/core/arrays/categorical.py:2862: in factorize_from_iterables
    codes, categories = zip(*(factorize_from_iterable(it) for it in iterables))
pandas/core/arrays/categorical.py:2862: in <genexpr>
    codes, categories = zip(*(factorize_from_iterable(it) for it in iterables))
pandas/core/arrays/categorical.py:2835: in factorize_from_iterable
    cat = Categorical(values, ordered=False)
pandas/core/arrays/categorical.py:440: in __init__
    codes, categories = factorize(values, sort=False)
pandas/core/algorithms.py:746: in factorize
    codes, uniques = values.factorize(sort=sort)
pandas/core/arrays/datetimelike.py:1830: in factorize
    uniques = self.copy()  # TODO: copy or view?
pandas/core/arrays/datetimelike.py:512: in copy
    new_obj = super().copy(order=order)  # type: ignore[call-arg]
E   TypeError: copy() takes no keyword arguments
```

I'm running on pandas' VSCode dev container.

### Expected Behavior

Should not fail, but run the tests instead.

### Installed Versions

<details><pre><code>INSTALLED VERSIONS
------------------
commit           : c323494e7313b9ac105e59d0748cd3ac53adf89d
python           : 3.8.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.76-linuxkit
Version          : #1 SMP Mon Nov 8 10:21:19 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : C.UTF-8
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.0.dev0+1469.gc323494e73
numpy            : 1.21.4
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 59.6.0
Cython           : 0.29.26
pytest           : 6.2.5
hypothesis       : 6.31.6
sphinx           : 4.3.2
blosc            : None
feather          : None
xlsxwriter       : 3.0.2
lxml.etree       : 4.7.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.30.1
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fsspec           : 2021.11.0
fastparquet      : 0.7.2
gcsfs            : 2021.11.0
matplotlib       : 3.5.1
numexpr          : 2.8.0
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 6.0.1
pyxlsb           : None
s3fs             : 2021.11.0
scipy            : 1.7.3
sqlalchemy       : 1.4.28
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : 0.18.2
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.53.1
zstandard        : None</code></pre></details>

**Comment by phofl** [comment]
This works for me. Could you provide a traceback and some more information

**Comment by MarcoGorelli** [comment]
Hi @jmg-duarte - CI is green, I assume it's an issue with your local environment? Perhaps you need to re-build the C extensions (`python setup.py build_ext -j 4`)? Closing for now, but if you post your traceback and it's a genuine issue we can reopen

**Comment by jmg-duarte** [comment]
> This works for me. Could you provide a traceback and some more information

Sorry, my bad. I've updated the original post. 
cc @MarcoGorelli

**Comment by jmg-duarte** [comment]
Update: rebuilding the extensions seems to have worked.

Closing.

**Comment by MarcoGorelli** [comment]
😄  no worries, glad it's working now!
