### ISSUE TITLE
BUG: inconsistent groupby behavior when groupby.apply return dataframe

### ISSUE THREAD

**Issue by GYHHAHA** [pandas-dev/pandas#45066]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
>>> df = pd.DataFrame({"A":[1,2,1,2]})
>>> df.groupby("A").apply(lambda x: x)
   A
0  1
1  2
2  1
3  2
>>> df.groupby("A").apply(lambda x: x.copy())
     A
A     
1 0  1
  2  1
2 1  2
  3  2
```

### Issue Description

I think both two cases should return a multi-index (just like the second case). Is this actually a bug? or just on purpose?

### Expected Behavior

```python
>>> df = pd.DataFrame({"A":[1,2,1,2]})
>>> df.groupby("A").apply(lambda x: x)
     A
A     
1 0  1
  2  1
2 1  2
  3  2
```

### Installed Versions

<details>

1.3.5

</details>

**Comment by LucasG0** [comment]
It looks like a duplicate of [44803](https://github.com/pandas-dev/pandas/issues/44803)

**Comment by GYHHAHA** [comment]
sorry for duplication, close
