### ISSUE TITLE
BUILD: Cannot install Pandas MAC OSx 12.1 M1 Chipe

### ISSUE THREAD

**Issue by werowe** [pandas-dev/pandas#45077]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Mac OSx 12.1 M1 Chip

### Installation Method

pip install

### pandas Version

latest

### Python Version

3.8.9

### Installation Logs

<details>

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Using cached pandas-1.3.5.tar.gz (4.7 MB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting numpy>=1.20.0; platform_machine == "arm64" and python_version < "3.10"
  Using cached numpy-1.21.5.zip (10.7 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting pytz>=2017.3
  Using cached pytz-2021.3-py2.py3-none-any.whl (503 kB)
Collecting python-dateutil>=2.7.3
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Building wheels for collected packages: pandas, numpy
  Building wheel for pandas (PEP 517): started
  Building wheel for pandas (PEP 517): still running...
  Building wheel for pandas (PEP 517): still running...
  Building wheel for pandas (PEP 517): still running...
  Building wheel for pandas (PEP 517): still running...
  Building wheel for pandas (PEP 517): still running...
  Building wheel for pandas (PEP 517): finished with status 'done'
  Created wheel for pandas: filename=pandas-1.3.5-cp38-cp38-macosx_10_14_6_arm64.whl size=16918274 sha256=3b4ac859e8b88b9b7ec73b84bc9aadb0e6dc1c0d539713daf6b56bae77adcc59
  Stored in directory: /Users/walkerrowe/Library/Caches/pip/wheels/a1/82/6d/78ce0bfdd4413cc8e4c7d1ab85242b144a62e303cc8f9ab6e7
  Building wheel for numpy (PEP 517): started
  Building wheel for numpy (PEP 517): finished with status 'error'
Successfully built pandas
Failed to build numpy

</details>

**Comment by phofl** [comment]
This looks like a numpy issue! Can you try installing numpy to check if this works? Your log says that pandas was build sucessfully

**Comment by werowe** [comment]
pip3 install numpy

Defaulting to user installation because normal site-packages is not
writeable

Collecting numpy

  Using cached numpy-1.21.5-cp38-cp38-macosx_11_0_arm64.whl (12.3 MB)

Installing collected packages: numpy

  WARNING: The scripts f2py, f2py3 and f2py3.8 are installed in
'/Users/walkerrowe/Library/Python/3.8/bin' which is not on PATH.

  Consider adding this directory to PATH or, if you prefer to suppress this
warning, use --no-warn-script-location.

Successfully installed numpy-1.21.5

**Comment by rbelew** [comment]
i'm not sure i'm having the same issue, but this one comes close.  i'm also on OSX 12.1 on arm64.
i think i've found an inconsistency: numpy>=**1.20.0** in `egg-info/requires.txt` but numpy >=**1.19.5,<2.0a0**
in conda's info

* `egg-info/requires.txt

		[:platform_machine == "arm64" and python_version < "3.10"]
		numpy>=1.20.0

* Using `pandas=1.3.5=py39h9197a36_0`

* `conda search pandas --info`

		pandas 1.3.5 py39h9197a36_0
		---------------------------
		file name   : pandas-1.3.5-py39h9197a36_0.conda
		name        : pandas
		version     : 1.3.5
		build       : py39h9197a36_0
		build number: 0
		size        : 9.1 MB
		license     : BSD-3-Clause
		subdir      : osx-arm64
		url         : https://repo.anaconda.com/pkgs/main/osx-arm64/pandas-1.3.5-py39h9197a36_0.conda
		md5         : 29968e22e8cad5c544ed77e051278172
		timestamp   : 2022-01-06 15:19:13 UTC
		dependencies: 
		- bottleneck >=1.2.1
		- libcxx >=12.0.0
		- numexpr >=2.7.0
		- numpy >=1.19.5,<2.0a0
		- python >=3.9,<3.10.0a0
		- python-dateutil >=2.7.3
		- pytz >=2017.3

**Comment by topper-123** [comment]
I can pip install pandas om my m1 mac 13.2.1. Maybe time gone by means this is no longer an issue?
