### ISSUE TITLE
BUG: df.groupby().head() missing rows when grouping on several columns with NA

### ISSUE THREAD

**Issue by LucasG0** [pandas-dev/pandas#45089]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
>>> df = pd.DataFrame([["a", "z"], ["b", None], ["c", None]], columns=["X", "Y"])
>>> df
   X     Y
0  a     z
1  b  None
2  c  None
>>> df.groupby(by=["X", "Y"]).head(n=1)
   X     Y
0  a     z
1  b  None

# Other example
>>> df = pd.DataFrame([["a", "z"], ["b", None], ["c", None], ["c", None], ["c", None]], columns=["X", "Y"])
>>> df
   X     Y
0  a     z
1  b  None
2  c  None
3  c  None
4  c  None
>>> df.groupby(by=["X", "Y"]).head(n=3)
   X     Y
0  a     z
1  b  None
2  c  None
3  c  None
```

### Issue Description

1 row having `("c", None)` values is missing in both examples.

### Expected Behavior

In both above examples we expect the whole dataframe to be returned. It seems the number of rows of the first group having NA in `("b", None)` is deduced from the number of rows that should be returned for the second group having NA `("c", None)`.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.11.0-43-generic
Version          : #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : fr_FR.UTF-8
LOCALE           : fr_FR.UTF-8

pandas           : 1.1.3
numpy            : 1.19.5
pytz             : 2019.3
dateutil         : 2.8.2
pip              : 20.0.2
setuptools       : 45.2.0
Cython           : None
pytest           : 6.2.4
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.25.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 2021.10.1
fastparquet      : 0.7.1
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 6.0.0
pytables         : None
pyxlsb           : None
s3fs             : 2021.10.1
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by phofl** [comment]
You have to set ``dropna=False``, then this will work as expected.

This should not return rows with None at all in your examples.
