### ISSUE TITLE
PERF: find_stack_level

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#45099]
Profiling `pandas/tests/groupby/test_function.py::test_builtins_apply` I'm seeing 18.78 seconds spent in groupby.apply, with 14.06 of that spent in 1732 calls of find_stack_level.

Maybe we can make find_stack_level lazy so it is only called when the warning is actually issued?

**Comment by jreback** [comment]
yeah or could have a 

show_warning method that only is executed in the warnjng block itself

eg


if <condition>:
   show_warning(,,,)
