### ISSUE TITLE
BUG: Sorting dataframe by value changes index type

### ISSUE THREAD

**Issue by amosroei** [pandas-dev/pandas#45107]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd

# initialize list of lists
data = [['tom', 10], ['nick', 15], ['juli', 14]]
 
# Create the pandas DataFrame
df = pd.DataFrame(data, columns = ['Name', 'Age'])

print(type(df.index[0]))
print(type(df.sort_values('Age', ascending=True).index[0]))
```

### Issue Description

I've noticed that sorting dataframe changes the type of its index from int to numpy.int64.
I know that I can solve it by using reset_index(), but I just wanted to know why it happen and if it is a bug.

### Expected Behavior

I expected index type to not change

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : f00ed8f47020034e752baf0250483053340971b0
python           : 3.7.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.14.252-131.483.amzn1.x86_64
Version          : #1 SMP Mon Nov 1 20:48:11 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.0
numpy            : 1.18.5
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.3.1
setuptools       : 49.6.0.post20210108
Cython           : 0.29.22
pytest           : 6.2.2
hypothesis       : 6.3.2
sphinx           : 3.5.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.4
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.7.5 (dt dec pq3 ext lo64)
jinja2           : 2.11.3
IPython          : 7.30.1
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 2021.04.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : 2.7.2
odfpy            : None
openpyxl         : 3.0.6
pandas_gbq       : None
pyarrow          : 6.0.1
pyxlsb           : None
s3fs             : 2021.04.0
scipy            : 1.5.3
sqlalchemy       : 1.3.23
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.52.0

**Comment by phofl** [comment]
The first one is a ``RangeIndex`` while the second one is an ``Int64Index``. The RangeIndex is represented as a range object to save memory, hence the dtype
