### ISSUE TITLE
Provide more intelligent way of setting skipfooter in read_csv

### ISSUE THREAD

**Issue by cancan101** [pandas-dev/pandas#4512]
See for example: http://www.datazoa.com/publish/export.asp?hash=vg6p5mBl1v&uid=dzadmin&a=exportcsv, http://www.datazoa.com/publish/export.asp?hash=yjPceG6fHL&uid=dzadmin&a=exportcsv or the http://pastebin.com/S2NqhFq0.

In all cases, it is important to set `skipfooter` in order to correctly parse the CSV.

I current set `skipfooter` in the above files using:

```
    data_raw = pd.io.parsers.read_csv(text,skiprows=range(1,13+1))
    skipfooter = data_raw["Series title"].index[-1]-data_raw[data_raw["Series title"].isnull()].index[0]+1

    ret = pd.io.parsers.read_csv(text,skiprows=range(1,13+1),skipfooter=skipfooter,parse_dates=[0],index_col=0)
```

The issue is that the value of skipfooter is not static, but rather varies based on how much meta data the provider is placing at the end of the file.

**Comment by mroeschke** [comment]
Thanks for the suggestion, but based on the inactivity and lack of community and core dev interest going to close for now. Can reopen if there's more interest
