### ISSUE TITLE
REF: de-duplicate Index._find_common_type_compat and dtypes.cast.find_result_type

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#45149]
In particular both include logic for working around Categoricals.  Not sure how much is shareable, but worth a shot.

**Comment by yuri-stepanov** [comment]
I will try to look at that. From the first glance not sure I can make it more readable, but I will give it shot. If anything will pan out I will create a PR. Otherwise I will comment here =)

**Comment by yuri-stepanov** [comment]
take

**Comment by yuri-stepanov** [comment]
Just wanted to update that I am still looking at that refactoring and if I am not blocking anyone I would be glad to continue. This took me on a fascinating adventure around pandas \ numpy type system =). 

At the moment I was looking through the code and relevant issues discussion like #26778 and #37258. I was interesting to learn about all of this corner cases. 
I think that at the moment the best that can be done without breaking the compatibility is refactoring of the logic for categorical types, as was mentioned by @jbrockmendel, but I really need to think where is the best place to put it.

**Comment by yuri-stepanov** [comment]
@jbrockmendel I think you beat me to it. Still it was interesting =)

**Comment by jbrockmendel** [comment]
Closing as pushed as far is it can go without API changes.
