### ISSUE TITLE
BUG: dataframe transform to dict , then accuracy of column  will lost. for example

### ISSUE THREAD

**Issue by AlitaIcon** [pandas-dev/pandas#45243]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame([{"a": 1}, {"a": None}])
##df
##     a
##0  1.0
##1  NaN
df['a'] = df['a'].apply(lambda x : int(x) if not pd.isnull(x) else x)
df
## df
##     a
##0  1.0
##1  NaN
```

### Issue Description

the accuracy of column  will lost, when the value of columns contains None or np.nan or pd.NaT

### Expected Behavior

the accuracy of column  will not lost, when the value of columns contains None or np.nan or pd.NaT

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : b5958ee1999e9aead1938c0bba2b674378807b3d
python           : 3.6.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None
pandas           : 1.1.5
numpy            : 1.19.5
pytz             : 2021.3
dateutil         : 2.8.0
pip              : 21.3.1
setuptools       : 59.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : 1.0.2
psycopg2         : 2.9.2 (dt dec pq3 ext lo64)
jinja2           : 3.0.3
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 2.4.11
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.4.28
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

**Comment by jreback** [comment]
pls check on a modern version eg 1.4.0rc1

**Comment by AlitaIcon** [comment]
> pls check on a modern version eg 1.4.0rc1

on a modern version eg 1.4.0rc1, it doesn't  work correctly.

**Comment by jreback** [comment]
https://pandas.pydata.org/docs/user_guide/missing_data.html

this is as expected 

use object dtype if u want to preserve None

**Comment by AlitaIcon** [comment]
> https://pandas.pydata.org/docs/user_guide/missing_data.html
> 
> this is as expected
> 
> use object dtype if u want to preserve None
thanks, but when i call function of "df.to_dict('records')", etc:
