### ISSUE TITLE
DEPR: subclassing Index

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#45289]
In theory we support subclassing Index, but that support is spotty (xref #15258, #37882).  Now that we allow arbitrary EAs in Index, we should deprecate that and direct downstream libraries to use EAs instead.

xref https://github.com/pydata/xarray/issues/6129

**Comment by jorisvandenbossche** [comment]
#37822 is a wrong link?

**Comment by rhshadrach** [comment]
For this deprecation, is this merely a docs change or would we be actively stopping users from subclassing Index?

**Comment by jbrockmendel** [comment]
I think just a docs change
