### ISSUE TITLE
Adding list of international holidays calendars

### ISSUE THREAD

**Issue by girolamodaschio** [pandas-dev/pandas#45310]
While working with [pandas/tseries/holiday.py](https://github.com/pandas-dev/pandas/blob/master/pandas/tseries/holiday.py), I notice that there is a `class USFederalHolidayCalendar(AbstractHolidayCalendar):` as an example.

I suggest creating an `international_holiday.py` file with appropriate international holidays child classes.

**Comment by girolamodaschio** [comment]
I can start with Italian and EU countries.

**Comment by Liam3851** [comment]
I can't speak to its quality, but there is already an international calendar holiday project at https://github.com/dr-prodigy/python-holidays. Not sure the extent to which maintaining a bunch of international calendars inside the library is in scope for pandas?

**Comment by jreback** [comment]
agree would in fact be ok with moving the existing holiday implementation out of pandas to another package

**Comment by girolamodaschio** [comment]
That's true. I didn't see the library.
I'll start using that.
Thanks for the comment, I'm closing the issue.
