### ISSUE TITLE
Hi all, I'm have multiple link (.iqy) to SharePoint, I want to combine them in excel using python

### ISSUE THREAD

**Issue by AlaaMustafa90** [pandas-dev/pandas#45329]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/51864417/merging-iqy-files-with-python

### Question about pandas

import os, glob
import pandas as pd

files = []
for file in glob.glob("D:\\Forms\\Forms_Link\\*.iqy"):
    files.append(file)

excels = [pd.ExcelFile(name) for name in files]
frames = [x.parse(x.sheet_names[0], header=None, index_col=None) for x in excels]

frames[1:] = [df[1:] for df in frames[1:]]

combined = pd.concat(frames)
-----------------------------------------------------------------------------------------------------------------------------
The error I get

ValueError                                Traceback (most recent call last)
<ipython-input-3-5ce6474f6783> in <module>
----> 1 excels = [pd.ExcelFile(name) for name in files]
      2 frames = [x.parse(x.sheet_names[0], header=None, index_col=None) for x in excels]
      3 
      4 frames[1:] = [df[1:] for df in frames[1:]]
      5 

<ipython-input-3-5ce6474f6783> in <listcomp>(.0)
----> 1 excels = [pd.ExcelFile(name) for name in files]
      2 frames = [x.parse(x.sheet_names[0], header=None, index_col=None) for x in excels]
      3 
      4 frames[1:] = [df[1:] for df in frames[1:]]
      5 

~\Anaconda3\lib\site-packages\pandas\io\excel\_base.py in __init__(self, path_or_buffer, engine, storage_options)
   1069                 ext = "xls"
   1070             else:
-> 1071                 ext = inspect_excel_format(
   1072                     content=path_or_buffer, storage_options=storage_options
   1073                 )

~\Anaconda3\lib\site-packages\pandas\io\excel\_base.py in inspect_excel_format(path, content, storage_options)
    963             return "xls"
    964         elif not peek.startswith(ZIP_SIGNATURE):
--> 965             raise ValueError("File is not a recognized excel file")
    966 
    967         # ZipFile typing is overly-strict

ValueError: File is not a recognized excel file

**Comment by MarcoGorelli** [comment]
> Link to question on StackOverflow
> https://stackoverflow.com/questions/51864417/merging-iqy-files-with-python

this isn't the question you asked - please ask your question on SO first, thanks
