### ISSUE TITLE
ENH: fill_na with new fill_partial argument

### ISSUE THREAD

**Issue by stevenschaerer** [pandas-dev/pandas#45332]
#### Is your feature request related to a problem?

I'd like to use fill_na with `method="ffill"` and `limit` say 4, but only fill NaN values if there are no more than 4 consecutive NaNs. Currently pandas will partially fill the first (for `"ffill"`) 4 of a gap of 6 NaNs.

#### Describe the solution you'd like

I propose to add a new parameter `fill_partial`. The default `True` replicates the current behavior, i.e. if `True`, fill up to and including `limit` consecutive NaN values. If `False`, only fill NaNs if there are at most `limit` consecutive NaNs. This parameter can be used with both `"ffill"` and `"bfill"`

#### API breaking implications

This would be a backward-compatible change.

#### Describe alternatives you've considered

None

#### Additional context

I'd be happy to implement this change if there is interest from the wider community.

**Comment by mroeschke** [comment]
Thanks for the suggestion but it appears there hasn't been much interest in this feature from the core devs & community over the years so closing. Happy to reopen if there's renewed interest
