### ISSUE TITLE
is_numeric_dtype('B') returns True

### ISSUE THREAD

**Issue by janvorac** [pandas-dev/pandas#45345]
`is_numeric_dtype` of certain single-capital-letter strings unexpectedly returns `True`

```py
import pandas as pd

pd.api.types.is_numeric_dtype('A')
Out[40]: False
pd.api.types.is_numeric_dtype('B')
Out[41]: True
pd.api.types.is_numeric_dtype('C')
Out[42]: False
pd.api.types.is_numeric_dtype('D')
Out[43]: True
pd.api.types.is_numeric_dtype('E')
Out[44]: False
pd.api.types.is_numeric_dtype('F')
Out[45]: True
pd.api.types.is_numeric_dtype('G')
Out[46]: True
pd.api.types.is_numeric_dtype('H')
Out[47]: True
pd.api.types.is_numeric_dtype('I')
Out[48]: True
pd.api.types.is_numeric_dtype('J')
Out[49]: False
```

That isn't intentional, is it?

**Comment by mroeschke** [comment]
This is the expected behavior as it's checking with numpy dtypes

```
In [2]: np.dtype("B")
Out[2]: dtype('uint8')
```

Could use better documentation.

**Comment by janvorac** [comment]
Thank you, I'll raise that in the `numpy` repo then.

**Comment by jorisvandenbossche** [comment]
@janvorac out of curiosity, what's the use case of wanting to have `is_numeric_dtype("B")` return False? 

(in general it's always safer to call those type methods with actual dtype objects instead of strings)

**Comment by janvorac** [comment]
@jorisvandenbossche I think I had wrong expectations from the method. I focused too much on the possibility to provide an array and forgot about the `dtype` input. Improving the docs is very wellcome here.

There is a place in one of my apps where I might have an array of numbers, a single number or a string. The string is just a piece of data, it is not a code for a `dtype`, i.e. an eventual `'B'` is just a B. And I need to make sure that in the end, I have only a number or a string. Something along these lines:

```py
if pd.api.types.is_numeric_dtype(data):
    data = numpy.mean(data) 
```

From `array([1, 3])`, I should get a `2`, from `'B'`, I expect a `'B'`.

But now, looking closely at my code, I see that I should have done that quite differently and I won't actually need it.

**Comment by jorisvandenbossche** [comment]
Is there something specific in the docstring that is confusing / that you would clarify?

**Comment by yashrajput0508** [comment]
This issue is only occurs in the strings case, I think so.

**Comment by yashrajput0508** [comment]
There are two methods to solve this issue:-
1. Solve the issue in np.dtype which occurs in numpy.
2. Or instead using np.dtype we can use another algo.

**Comment by yashrajput0508** [comment]
The error in line No:- 1777 in pandas/pandas/core/dtypes/common.py , I updated the code with this code
```
    try:
        npdtype = np.dtype(dtype)
        
        # if type of dtype is string than raise SyntaxError
        if type(dtype)==str and dtype!="M8" and dtype!="m8" and dtype!="O":
            raise SyntaxError
            
            
    except SyntaxError as err:
        # np.dtype uses `eval` which can raise SyntaxError
        raise TypeError(f"data type '{dtype}' not understood") from err
```

Now , it working i think so.

I am a fresher if there is any mistake plz tell me.

**Comment by phofl** [comment]
This works as intended on the numpy side and since we are using a lot of numpy dtypes, 2 is not feasible

**Comment by jreback** [comment]
agreed
