### ISSUE TITLE
BUG: df.str.len() returning floats

### ISSUE THREAD

**Issue by ddejohn** [pandas-dev/pandas#45351]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

words = pd.read_csv("words_alpha.txt", sep="\n", header=None, names=["all_words"])
# words["all_words"].str.isalpha().all()
# words["all_words"].isnull().all()

words["all_words"].str.len()
```

### Issue Description

Using [this](https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt) `.txt` and running the code above, `.str.len()` is returning floats in Pandas 1.3.5:

```python
In [2]: import pandas as pd

In [3]: words = pd.read_csv("Downloads/words_alpha.txt", sep="\n", header=None, names=["all_words"])

In [4]: words["all_words"].str.isalpha().all()
Out[4]: True

In [5]: words["all_words"].isnull().all()
Out[5]: False

In [6]: words["all_words"].isna().all()
Out[6]: False

In [7]: words["all_words"].str.len()
Out[7]:
0          1.0
1          2.0
2          3.0
3          3.0
4          5.0
          ...
370098    12.0
370099    12.0
370100     7.0
370101    10.0
370102    12.0
Name: all_words, Length: 370103, dtype: float64
```

### Expected Behavior

`.str.len()` should return integers

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d
python           : 3.9.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.3.5
numpy            : 1.20.3
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.3.1
setuptools       : 56.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.9.1 (dt dec pq3 ext lo64)
jinja2           : 3.0.1
IPython          : 7.24.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.3
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
</details>

**Comment by mroeschke** [comment]
Could you post a more minimal example? Ideally the reproducible, testable behavior it shouldn't depend on an external file.

As a guess, it's probably because there's a `np.nan` in the Series which will expectedly return `np.nan`

```
In [1]: pd.Series(["foo"]).str.len()
Out[1]:
0    3
dtype: int64

In [2]: pd.Series(["foo", np.nan]).str.len()
Out[2]:
0    3.0
1    NaN
dtype: float64
```

**Comment by ddejohn** [comment]
Ugh. I accidentally used `.isnull().all()` to make sure there weren't any null values, instead of `.any()`. My bad.
