### ISSUE TITLE
BUG: DataFrame constructor with copy=False and missing columns creates columns that are views of each other

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#45369]
See https://github.com/pandas-dev/pandas/pull/44889#discussion_r784926771

With `copy=False` and constructing a DataFrame with missing columns in the passed data, the columns get constructed as identical arrays, so mutating one also incorrectly mutates the other columns:

```
In [10]: df = pd.DataFrame(index=[1, 2, 3], columns=["a", "b", "c"], copy=False)

In [11]: df.iloc[0, 0] = 0

In [12]: df
Out[12]: 
     a    b    c
1    0    0    0
2  NaN  NaN  NaN
3  NaN  NaN  NaN
```

**Comment by simonjayhawkins** [comment]
> With `copy=False` and constructing a DataFrame with missing columns in the passed data, the columns get constructed as identical arrays, so mutating one also incorrectly mutates the other columns:

This is a regression from 1.2.5

first bad commit: [66e6ba302105c9968674365ad043efedcad9977f] API: honor copy=True when passing dict to DataFrame (#38939)

cc @jbrockmendel
