### ISSUE TITLE
QST: use and breadth of `x_compat=True`

### ISSUE THREAD

**Issue by ptoche** [pandas-dev/pandas#45367]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/70707996/matplotlib-horizontal-labels-as-style?noredirect=1#comment125004119_70707996

### Question about pandas

If I understand correctly, `x_compat=True` allows one to have access to `matplotlib`'s date formatters and disables some of `pandas`'s date formatting. However, it has no effect on `rotation` (or `rot` in pandas parlance). My question is whether one would expect `x_compat=True` to also disable the rotation (that is, set it to `0`). In other words, I'm not clear on how much of the date formatting `x_compat=True` is expected to "return" to the `matplotlib` default. Was it a design decision?

**Comment by ptoche** [comment]
Thanks for your question! 

Well I may be misunderstanding. Here's what I thought happened: with `df.plot()` a number of default are set, including handling of dates and rotating long dates such as "2021-01-01" by 30 degrees, but the `x_compat=True` flag allows the user to disable these defaults and call the `matplotlib` locators and formatters. Am I misunderstanding?

Setting `x_compat=True` keeps the rotation at 30 degrees, when I expected it to be reset to the matlolib default of 0 degrees. 

I'm currently setting the rotation to 0 inside the plot call, but I would have liked for it to have been a default. Not a big deal.

**Comment by MarcoGorelli** [comment]
I think `x_compat` is more about tick location than about format, so I presume they thought the 30 degree rotation would be a sensible default

You can look through #2205 and https://github.com/pandas-dev/pandas/commit/8d45dc4b766629a99d5c766448c433bc2c067b8e for more info

Anyway, regardless of the design decision which was taken 10 years ago, it's probably not worth changing this now

**Comment by ptoche** [comment]
The label's orientation feels like something distinct from the locator/formatter, maybe similar to the choice of font type and size. That's why I expected to be able to control it as a style, rather than within the call to plot. But yes, I'll just forget about this.
