### ISSUE TITLE
QST: Is Series homogeneous or heterogeneous?

### ISSUE THREAD

**Issue by ErSheetal** [pandas-dev/pandas#45379]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/70718929/pandas-is-series-homogenous

**Comment by jreback** [comment]
answered on SO
