### ISSUE TITLE
BUILD: Cannot create development environment using pip on macOS

### ISSUE THREAD

**Issue by hasan-yaman** [pandas-dev/pandas#45374]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

macOS-10.16-x86_64-i386-64bit

### Installation Method

Built from source

### pandas Version

master

### Python Version

Python: 3.8.10 pip: 21.3.1

### Installation Logs

<details>

Building wheels for collected packages: pydata-sphinx-theme
  Building wheel for pydata-sphinx-theme (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/hasan/virtualenvs/pandas-dev/bin/python /Users/hasan/virtualenvs/pandas-dev/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/jg/jhfnlx653h9dmfw4n6rzsr8c0000gn/T/tmp5w180uju
       cwd: /private/var/folders/jg/jhfnlx653h9dmfw4n6rzsr8c0000gn/T/pip-req-build-00ga2i7s
  Complete output (447 lines):
  [stb] # nodeenv does not exist.
  [stb] # Generating new nodeenv with NodeJS 16.13.2!
  [stb] $ python -m nodeenv --node=16.13.2 --prebuilt --clean-src /private/var/fol
  ders/jg/jhfnlx653h9dmfw4n6rzsr8c0000gn/T/pip-req-build-00ga2i7s/.nodeenv
   * Install prebuilt node (16.13.2) .
  ╭───────────────────── Traceback (most recent call last) ──────────────────────╮
  │                                                                              │
  │ /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/reque │
  │ st.py:1354 in do_open                                                        │
  │ /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client. │
  │ py:1252 in request                                                           │
  │                                                                              │
  │ /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client. │
  │ py:1298 in _send_request                                                     │
  │                                                                              │
  │ /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client. │
  │ py:1247 in endheaders                                                        │
  │                                                                              │
  │ /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client. │
  │ py:1007 in _send_output                                                      │
  │                                                                              │
  │ /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client. │
  │ py:947 in send                                                               │
  │                                                                              │
  │ /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client. │
  │ py:1421 in connect                                                           │
  │                                                                              │
  │ /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py:500   │
  │ in wrap_socket                                                               │
  │                                                                              │
  │ /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py:1040  │
  │ in _create                                                                   │
  │                                                                              │
  │ /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py:1309  │
  │ in do_handshake                                                              │
  ╰──────────────────────────────────────────────────────────────────────────────╯
  SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify
  failed: unable to get local issuer certificate (_ssl.c:1131)
  
  During handling of the above exception, another exception occurred:
  
  ╭───────────────────── Traceback (most recent call last) ──────────────────────╮
  │ <string>:12 in <module>                                                      │
  │ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
  │ │ __annotations__ = {}                                                     │ │
  │ │    __builtins__ = <module 'builtins' (built-in)>                         │ │
  │ │         __doc__ = None                                                   │ │
  │ │      __loader__ = <class '_frozen_importlib.BuiltinImporter'>            │ │
  │ │        __name__ = '__main__'                                             │ │
  │ │     __package__ = None                                                   │ │
  │ │        __spec__ = None                                                   │ │
  │ │            rich = <module 'rich' from                                    │ │
  │ │                   '/private/var/folders/jg/jhfnlx653h9dmfw4n6rzsr8c0000… │ │
  │ │           runpy = <module 'runpy' from                                   │ │
  │ │                   '/Library/Frameworks/Python.framework/Versions/3.8/li… │ │
  │ │          urllib = <module 'urllib' from                                  │ │
  │ │                   '/Library/Frameworks/Python.framework/Versions/3.8/li… │ │
  │ ╰──────────────────────────────────────────────────────────────────────────╯ │
  │ /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py:207 │
  │ in run_module                                                                │
  │                                                                              │
  │ /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py:97  │
  │ in _run_module_code                                                          │
  │                                                                              │
  │ /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py:87  │
  │ in _run_code                                                                 │
  │                                                                              │
  │ /private/var/folders/jg/jhfnlx653h9dmfw4n6rzsr8c0000gn/T/pip-build-env-6wljs │
  │ 2vd/overlay/lib/python3.8/site-packages/nodeenv.py:1494 in <module>          │
  │                                                                              │
  │   1491 """                                                                   │
  │   1492                                                                       │
  │   1493 if __name__ == '__main__':                                            │
  │ ❱ 1494 │   main()                                                            │
  │   1495                                                                       │
  │                                                                              │
  │ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
  │ │                 __builtins__ = {                                         │ │
  │ │                                │   '__name__': 'builtins',               │ │
  │ │                                │   '__doc__': 'Built-in functions,       │ │
  │ │                                exceptions, and other                     │ │
  │ │                                objects.\n\nNoteworthy: None is the       │ │
  │ │                                `nil'+46,                                 │ │
  │ │                                │   '__package__': '',                    │ │
  │ │                                │   '__loader__': <class                  │ │
  │ │                                '_frozen_importlib.BuiltinImporter'>,     │ │
  │ │                                │   '__spec__':                           │ │
  │ │                                ModuleSpec(name='builtins', loader=<class │ │
  │ │                                '_frozen_importlib.BuiltinImporter'>),    │ │
  │ │                                │   '__build_class__': <built-in function │ │
  │ │                                __build_class__>,                         │ │
  │ │                                │   '__import__': <built-in function      │ │
  │ │                                __import__>,                              │ │
  │ │                                │   'abs': <built-in function abs>,       │ │
  │ │                                │   'all': <built-in function all>,       │ │
  │ │                                │   'any': <built-in function any>,       │ │
  │ │                                │   ... +142                              │ │
  │ │                                }                                         │ │
  │ │                   __cached__ = '/private/var/folders/jg/jhfnlx653h9dmfw… │ │
  │ │                      __doc__ = '\n    nodeenv\n    ~~~~~~~\n    Node.js  │ │
  │ │                                virtual environment\n\n    :copyright:    │ │
  │ │                                (c) 20'+70                                │ │
  │ │                     __file__ = '/private/var/folders/jg/jhfnlx653h9dmfw… │ │
  │ │                   __loader__ = <_frozen_importlib_external.SourceFileLo… │ │
  │ │                                object at 0x7f8626bc88b0>                 │ │
  │ │                     __name__ = '__main__'                                │ │
  │ │                  __package__ = ''                                        │ │
  │ │                     __spec__ = ModuleSpec(name='nodeenv',                │ │
  │ │                                loader=<_frozen_importlib_external.Sourc… │ │
  │ │                                object at 0x7f8626bc88b0>,                │ │
  │ │                                origin='/private/var/folders/jg/jhfnlx65… │ │
  │ │           _get_versions_json = <function _get_versions_json at           │ │
  │ │                                0x7f86270a3af0>                           │ │
  │ │                      abspath = <function abspath at 0x7f86252014c0>      │ │
  │ │                 ACTIVATE_BAT = '\n@echo off\nset                         │ │
  │ │                                "NODE_VIRTUAL_ENV=__NODE_VIRTUAL_ENV__"\… │ │
  │ │                                not defined PROMPT (\n '+513              │ │
  │ │                ACTIVATE_FISH = '\n\n# This file must be used with        │ │
  │ │                                "source bin/activate.fish" *from fish*\n# │ │
  │ │                                you can'+4141                             │ │
  │ │                 ACTIVATE_PS1 = '\nfunction global:deactivate             │ │
  │ │                                ([switch]$NonDestructive) {\n    # Revert │ │
  │ │                                to original'+1306                         │ │
  │ │                  ACTIVATE_SH = '\n\n# This file must be used with        │ │
  │ │                                "source bin/activate" *from bash*\n# you  │ │
  │ │                                cannot r'+3608                            │ │
  │ │          build_node_from_src = <function build_node_from_src at          │ │
  │ │                                0x7f86270a35e0>                           │ │
  │ │                       callit = <function callit at 0x7f8627096f70>       │ │
  │ │                 clear_output = <function clear_output at 0x7f8627072550> │ │
  │ │                       Config = <class '__main__.Config'>                 │ │
  │ │                 ConfigParser = <class 'configparser.ConfigParser'>       │ │
  │ │                   contextlib = <module 'contextlib' from                 │ │
  │ │                                '/Library/Frameworks/Python.framework/Ve… │ │
  │ │      copy_node_from_prebuilt = <function copy_node_from_prebuilt at      │ │
  │ │                                0x7f86270a3550>                           │ │
  │ │                     copytree = <function copytree at 0x7f86270a34c0>     │ │
  │ │           create_environment = <function create_environment at           │ │
  │ │                                0x7f86270a3a60>                           │ │
  │ │                create_logger = <function create_logger at                │ │
  │ │                                0x7f8627096d30>                           │ │
  │ │                  CYGWIN_NODE = '#!/bin/sh\n\nif [ -r "$1" ]; then\n      │ │
  │ │                                SCRIPT_PATH=$(cygpath -w "$1")\n          │ │
  │ │                                shift\n   '+84                            │ │
  │ │               DEACTIVATE_BAT = '@echo off\nif defined                    │ │
  │ │                                _OLD_VIRTUAL_PROMPT (\n    set            │ │
  │ │                                "PROMPT=%_OLD_VIRTUAL_PROMPT%'+262        │ │
  │ │               DISABLE_PROMPT = {                                         │ │
  │ │                                │   'activate': "\n# disable nodeenv's    │ │
  │ │                                prompt\n# (prompt already changed by      │ │
  │ │                                original virtualenv's s"+89,              │ │
  │ │                                │   'activate.fish': "\n# disable         │ │
  │ │                                nodeenv's prompt\n# (prompt already       │ │
  │ │                                changed by original virtualenv's s"+93    │ │
  │ │                                }                                         │ │
  │ │            download_node_src = <function download_node_src at            │ │
  │ │                                0x7f86270a33a0>                           │ │
  │ │                ENABLE_PROMPT = {                                         │ │
  │ │                                │   'activate': '\nunset                  │ │
  │ │                                NODE_VIRTUAL_ENV_DISABLE_PROMPT\n',       │ │
  │ │                                │   'activate.fish': '\nset -e            │ │
  │ │                                NODE_VIRTUAL_ENV_DISABLE_PROMPT\n'        │ │
  │ │                                }                                         │ │
  │ │                  get_env_dir = <function get_env_dir at 0x7f86270a3dc0>  │ │
  │ │    get_last_lts_node_version = <function get_last_lts_node_version at    │ │
  │ │                                0x7f86270a3d30>                           │ │
  │ │ get_last_stable_node_version = <function get_last_stable_node_version at │ │
  │ │                                0x7f86270a3ca0>                           │ │
  │ │             get_node_bin_url = <function get_node_bin_url at             │ │
  │ │                                0x7f86270a3160>                           │ │
  │ │             get_node_src_url = <function get_node_src_url at             │ │
  │ │                                0x7f86270a31f0>                           │ │
  │ │            get_node_versions = <function get_node_versions at            │ │
  │ │                                0x7f86270a3b80>                           │ │
  │ │                 get_root_url = <function get_root_url at 0x7f86270a3040> │ │
  │ │                         glob = <module 'glob' from                       │ │
  │ │                                '/Library/Frameworks/Python.framework/Ve… │ │
  │ │                         http = <module 'http' from                       │ │
  │ │                                '/Library/Frameworks/Python.framework/Ve… │ │
  │ │             ignore_ssl_certs = False                                     │ │
  │ │               IncompleteRead = <class 'http.client.IncompleteRead'>      │ │
  │ │             install_activate = <function install_activate at             │ │
  │ │                                0x7f86270a3940>                           │ │
  │ │                 install_node = <function install_node at 0x7f86270a3670> │ │
  │ │         install_node_wrapped = <function install_node_wrapped at         │ │
  │ │                                0x7f86270a3700>                           │ │
  │ │                  install_npm = <function install_npm at 0x7f86270a3790>  │ │
  │ │              install_npm_win = <function install_npm_win at              │ │
  │ │                                0x7f86270a3820>                           │ │
  │ │             install_packages = <function install_packages at             │ │
  │ │                                0x7f86270a38b0>                           │ │
  │ │                           io = <module 'io' from                         │ │
  │ │                                '/Library/Frameworks/Python.framework/Ve… │ │
  │ │                    is_CYGWIN = False                                     │ │
  │ │                       is_PY3 = True                                      │ │
  │ │                       is_WIN = False                                     │ │
  │ │               is_x86_64_musl = <function is_x86_64_musl at               │ │
  │ │                                0x7f86270a30d0>                           │ │
  │ │                    iteritems = operator.methodcaller('items')            │ │
  │ │                         join = <function join at 0x7f8622ec8dc0>         │ │
  │ │                         json = <module 'json' from                       │ │
  │ │                                '/Library/Frameworks/Python.framework/Ve… │ │
  │ │                       logger = <Logger nodeenv (INFO)>                   │ │
  │ │                      logging = <module 'logging' from                    │ │
  │ │                                '/Library/Frameworks/Python.framework/Ve… │ │
  │ │                         main = <function main at 0x7f86270a3e50>         │ │
  │ │              make_executable = <function make_executable at              │ │
  │ │                                0x7f8627096e50>                           │ │
  │ │                        mkdir = <function mkdir at 0x7f862571c550>        │ │
  │ │        node_version_from_opt = <function node_version_from_opt at        │ │
  │ │                                0x7f8627096ca0>                           │ │
  │ │              nodeenv_version = '1.6.0'                                   │ │
  │ │                     operator = <module 'operator' from                   │ │
  │ │                                '/Library/Frameworks/Python.framework/Ve… │ │
  │ │                     optparse = <module 'optparse' from                   │ │
  │ │                                '/Library/Frameworks/Python.framework/Ve… │ │
  │ │                           os = <module 'os' from                         │ │
  │ │                                '/Library/Frameworks/Python.framework/Ve… │ │
  │ │                   parse_args = <function parse_args at 0x7f86257685e0>   │ │
  │ │                parse_version = <function parse_version at                │ │
  │ │                                0x7f8626e35d30>                           │ │
  │ │                        pipes = <module 'pipes' from                      │ │
  │ │                                '/Library/Frameworks/Python.framework/Ve… │ │
  │ │                     platform = <module 'platform' from                   │ │
  │ │                                '/Library/Frameworks/Python.framework/Ve… │ │
  │ │             PREDEACTIVATE_SH = '\nif type -p deactivate_node >           │ │
  │ │                                /dev/null; then deactivate_node;fi\n'     │ │
  │ │          print_node_versions = <function print_node_versions at          │ │
  │ │                                0x7f86270a3c10>                           │ │
  │ │                           re = <module 're' from                         │ │
  │ │                                '/Library/Frameworks/Python.framework/Ve… │ │
  │ │     remove_env_bin_from_path = <function remove_env_bin_from_path at     │ │
  │ │                                0x7f8627096c10>                           │ │
  │ │       set_predeactivate_hook = <function set_predeactivate_hook at       │ │
  │ │                                0x7f86270a39d0>                           │ │
  │ │                         SHIM = "#!/usr/bin/env bash\nexport              │ │
  │ │                                NODE_PATH='__NODE_VIRTUAL_ENV__/lib/node… │ │
  │ │                       shutil = <module 'shutil' from                     │ │
  │ │                                '/Library/Frameworks/Python.framework/Ve… │ │
  │ │                 src_base_url = 'https://nodejs.org/download/release'     │ │
  │ │                          ssl = <module 'ssl' from                        │ │
  │ │                                '/Library/Frameworks/Python.framework/Ve… │ │
  │ │                         stat = <module 'stat' from                       │ │
  │ │                                '/Library/Frameworks/Python.framework/Ve… │ │
  │ │                   subprocess = <module 'subprocess' from                 │ │
  │ │                                '/Library/Frameworks/Python.framework/Ve… │ │
  │ │                          sys = <module 'sys' (built-in)>                 │ │
  │ │                    sysconfig = <module 'sysconfig' from                  │ │
  │ │                                '/Library/Frameworks/Python.framework/Ve… │ │
  │ │                      tarfile = <module 'tarfile' from                    │ │
  │ │                                '/Library/Frameworks/Python.framework/Ve… │ │
  │ │                 tarfile_open = <function tarfile_open at 0x7f86270a3310> │ │
  │ │                      to_utf8 = <function to_utf8 at 0x7f8626d83160>      │ │
  │ │                      urllib2 = <module 'urllib.request' from             │ │
  │ │                                '/Library/Frameworks/Python.framework/Ve… │ │
  │ │                      urlopen = <function urlopen at 0x7f86270a3430>      │ │
  │ │                    writefile = <function writefile at 0x7f8627096ee0>    │ │
  │ │                      zipfile = <module 'zipfile' from                    │ │
  │ │                                '/Library/Frameworks/Python.framework/Ve… │ │
  │ ╰──────────────────────────────────────────────────────────────────────────╯ │
  │                                                                              │
  │ /private/var/folders/jg/jhfnlx653h9dmfw4n6rzsr8c0000gn/T/pip-build-env-6wljs │
  │ 2vd/overlay/lib/python3.8/site-packages/nodeenv.py:1079 in main              │
  │                                                                              │
  │   1076 │   │   install_packages(env_dir, opt)                                │
  │   1077 │   else:                                                             │
  │   1078 │   │   env_dir = get_env_dir(opt, args)                              │
  │ ❱ 1079 │   │   create_environment(env_dir, opt)                              │
  │   1080                                                                       │
  │   1081                                                                       │
  │   1082 # ---------------------------------------------------------           │
  │                                                                              │
  │ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
  │ │       args = [                                                           │ │
  │ │              │                                                           │ │
  │ │              '/private/var/folders/jg/jhfnlx653h9dmfw4n6rzsr8c0000gn/T/… │ │
  │ │              ]                                                           │ │
  │ │    env_dir = '/private/var/folders/jg/jhfnlx653h9dmfw4n6rzsr8c0000gn/T/… │ │
  │ │        opt = <Values at 0x7f862709f0a0: {'node': '16.13.2', 'mirror':    │ │
  │ │              None, 'jobs': '2', 'load_average': None, 'without_ssl':     │ │
  │ │              False, 'debug': False, 'profile': False, 'make_path':       │ │
  │ │              'make', 'prebuilt': True, 'verbose': True, 'quiet': False,  │ │
  │ │              'config_file': ['./tox.ini', './setup.cfg',                 │ │
  │ │              '~/.nodeenvrc'], 'requirements': '', 'prompt': None,        │ │
  │ │              'list': False, 'update': False, 'with_npm': False, 'npm':   │ │
  │ │              'latest', 'no_npm_clean': False, 'python_virtualenv':       │ │
  │ │              False, 'clean_src': True, 'force': False,                   │ │
  │ │              'ignore_ssl_certs': False}>                                 │ │
  │ │ src_domain = 'nodejs.org'                                                │ │
  │ ╰──────────────────────────────────────────────────────────────────────────╯ │
  │                                                                              │
  │ /private/var/folders/jg/jhfnlx653h9dmfw4n6rzsr8c0000gn/T/pip-build-env-6wljs │
  │ 2vd/overlay/lib/python3.8/site-packages/nodeenv.py:956 in create_environment │
  │                                                                              │
  │    953 │   mkdir(src_dir)                                                    │
  │    954 │                                                                     │
  │    955 │   if opt.node != "system":                                          │
  │ ❱  956 │   │   install_node(env_dir, src_dir, opt)                           │
  │    957 │   else:                                                             │
  │    958 │   │   mkdir(join(env_dir, 'bin'))                                   │
  │    959 │   │   mkdir(join(env_dir, 'lib'))                                   │
  │                                                                              │
  │ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
  │ │ env_dir = '/private/var/folders/jg/jhfnlx653h9dmfw4n6rzsr8c0000gn/T/pip… │ │
  │ │     opt = <Values at 0x7f862709f0a0: {'node': '16.13.2', 'mirror': None, │ │
  │ │           'jobs': '2', 'load_average': None, 'without_ssl': False,       │ │
  │ │           'debug': False, 'profile': False, 'make_path': 'make',         │ │
  │ │           'prebuilt': True, 'verbose': True, 'quiet': False,             │ │
  │ │           'config_file': ['./tox.ini', './setup.cfg', '~/.nodeenvrc'],   │ │
  │ │           'requirements': '', 'prompt': None, 'list': False, 'update':   │ │
  │ │           False, 'with_npm': False, 'npm': 'latest', 'no_npm_clean':     │ │
  │ │           False, 'python_virtualenv': False, 'clean_src': True, 'force': │ │
  │ │           False, 'ignore_ssl_certs': False}>                             │ │
  │ │ src_dir = '/private/var/folders/jg/jhfnlx653h9dmfw4n6rzsr8c0000gn/T/pip… │ │
  │ ╰──────────────────────────────────────────────────────────────────────────╯ │
  │                                                                              │
  │ /private/var/folders/jg/jhfnlx653h9dmfw4n6rzsr8c0000gn/T/pip-build-env-6wljs │
  │ 2vd/overlay/lib/python3.8/site-packages/nodeenv.py:721 in install_node       │
  │                                                                              │
  │    718 │   and install it in virtual environment.                            │
  │    719 │   """                                                               │
  │    720 │   try:                                                              │
  │ ❱  721 │   │   install_node_wrapped(env_dir, src_dir, opt)                   │
  │    722 │   except BaseException:                                             │
  │    723 │   │   # this restores the newline suppressed by continued=True      │
  │    724 │   │   logger.info('')                                               │
  │                                                                              │
  │ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
  │ │ env_dir = '/private/var/folders/jg/jhfnlx653h9dmfw4n6rzsr8c0000gn/T/pip… │ │
  │ │     opt = <Values at 0x7f862709f0a0: {'node': '16.13.2', 'mirror': None, │ │
  │ │           'jobs': '2', 'load_average': None, 'without_ssl': False,       │ │
  │ │           'debug': False, 'profile': False, 'make_path': 'make',         │ │
  │ │           'prebuilt': True, 'verbose': True, 'quiet': False,             │ │
  │ │           'config_file': ['./tox.ini', './setup.cfg', '~/.nodeenvrc'],   │ │
  │ │           'requirements': '', 'prompt': None, 'list': False, 'update':   │ │
  │ │           False, 'with_npm': False, 'npm': 'latest', 'no_npm_clean':     │ │
  │ │           False, 'python_virtualenv': False, 'clean_src': True, 'force': │ │
  │ │           False, 'ignore_ssl_certs': False}>                             │ │
  │ │ src_dir = '/private/var/folders/jg/jhfnlx653h9dmfw4n6rzsr8c0000gn/T/pip… │ │
  │ ╰──────────────────────────────────────────────────────────────────────────╯ │
  │                                                                              │
  │ /private/var/folders/jg/jhfnlx653h9dmfw4n6rzsr8c0000gn/T/pip-build-env-6wljs │
  │ 2vd/overlay/lib/python3.8/site-packages/nodeenv.py:743 in                    │
  │ install_node_wrapped                                                         │
  │                                                                              │
  │    740 │                                                                     │
  │    741 │   # get src if not downloaded yet                                   │
  │    742 │   if not os.path.exists(node_src_dir):                              │
  │ ❱  743 │   │   download_node_src(node_url, src_dir, opt)                     │
  │    744 │                                                                     │
  │    745 │   logger.info('.', extra=dict(continued=True))                      │
  │    746                                                                       │
  │                                                                              │
  │ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
  │ │      env_dir = '/private/var/folders/jg/jhfnlx653h9dmfw4n6rzsr8c0000gn/… │ │
  │ │ node_src_dir = '/private/var/folders/jg/jhfnlx653h9dmfw4n6rzsr8c0000gn/… │ │
  │ │     node_url = 'https://nodejs.org/download/release/v16.13.2/node-v16.1… │ │
  │ │          opt = <Values at 0x7f862709f0a0: {'node': '16.13.2', 'mirror':  │ │
  │ │                None, 'jobs': '2', 'load_average': None, 'without_ssl':   │ │
  │ │                False, 'debug': False, 'profile': False, 'make_path':     │ │
  │ │                'make', 'prebuilt': True, 'verbose': True, 'quiet':       │ │
  │ │                False, 'config_file': ['./tox.ini', './setup.cfg',        │ │
  │ │                '~/.nodeenvrc'], 'requirements': '', 'prompt': None,      │ │
  │ │                'list': False, 'update': False, 'with_npm': False, 'npm': │ │
  │ │                'latest', 'no_npm_clean': False, 'python_virtualenv':     │ │
  │ │                False, 'clean_src': True, 'force': False,                 │ │
  │ │                'ignore_ssl_certs': False}>                               │ │
  │ │      src_dir = '/private/var/folders/jg/jhfnlx653h9dmfw4n6rzsr8c0000gn/… │ │
  │ │     src_type = 'prebuilt'                                                │ │
  │ ╰──────────────────────────────────────────────────────────────────────────╯ │
  │                                                                              │
  │ /private/var/folders/jg/jhfnlx653h9dmfw4n6rzsr8c0000gn/T/pip-build-env-6wljs │
  │ 2vd/overlay/lib/python3.8/site-packages/nodeenv.py:570 in download_node_src  │
  │                                                                              │
  │    567 │   """                                                               │
  │    568 │   logger.info('.', extra=dict(continued=True))                      │
  │    569 │   try:                                                              │
  │ ❱  570 │   │   dl_contents = io.BytesIO(urlopen(node_url).read())            │
  │    571 │   except IncompleteRead as e:                                       │
  │    572 │   │   logger.warning('Incomplete read while reading'                │
  │    573 │   │   │   │   │      'from {}'.format(node_url))                    │
  │                                                                              │
  │ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
  │ │ node_url = 'https://nodejs.org/download/release/v16.13.2/node-v16.13.2-… │ │
  │ │      opt = <Values at 0x7f862709f0a0: {'node': '16.13.2', 'mirror':      │ │
  │ │            None, 'jobs': '2', 'load_average': None, 'without_ssl':       │ │
  │ │            False, 'debug': False, 'profile': False, 'make_path': 'make', │ │
  │ │            'prebuilt': True, 'verbose': True, 'quiet': False,            │ │
  │ │            'config_file': ['./tox.ini', './setup.cfg', '~/.nodeenvrc'],  │ │
  │ │            'requirements': '', 'prompt': None, 'list': False, 'update':  │ │
  │ │            False, 'with_npm': False, 'npm': 'latest', 'no_npm_clean':    │ │
  │ │            False, 'python_virtualenv': False, 'clean_src': True,         │ │
  │ │            'force': False, 'ignore_ssl_certs': False}>                   │ │
  │ │  src_dir = '/private/var/folders/jg/jhfnlx653h9dmfw4n6rzsr8c0000gn/T/pi… │ │
  │ ╰──────────────────────────────────────────────────────────────────────────╯ │
  │                                                                              │
  │ /private/var/folders/jg/jhfnlx653h9dmfw4n6rzsr8c0000gn/T/pip-build-env-6wljs │
  │ 2vd/overlay/lib/python3.8/site-packages/nodeenv.py:606 in urlopen            │
  │                                                                              │
  │    603 │   │   context = ssl.SSLContext()                                    │
  │    604 │   │   context.verify_mode = ssl.CERT_NONE                           │
  │    605 │   │   return urllib2.urlopen(req, context=context)                  │
  │ ❱  606 │   return urllib2.urlopen(req)                                       │
  │    607                                                                       │
  │    608 # ---------------------------------------------------------           │
  │    609 # Virtual environment functions                                       │
  │                                                                              │
  │ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
  │ │  headers = {                                                             │ │
  │ │            │   'User-Agent': 'nodeenv/1.6.0                              │ │
  │ │            (https://github.com/ekalinin/nodeenv/)'                       │ │
  │ │            }                                                             │ │
  │ │ home_url = 'https://github.com/ekalinin/nodeenv/'                        │ │
  │ │      req = <urllib.request.Request object at 0x7f862709f8e0>             │ │
  │ │      url = 'https://nodejs.org/download/release/v16.13.2/node-v16.13.2-… │ │
  │ ╰──────────────────────────────────────────────────────────────────────────╯ │
  │                                                                              │
  │ /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/reque │
  │ st.py:222 in urlopen                                                         │
  │                                                                              │
  │ /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/reque │
  │ st.py:525 in open                                                            │
  │                                                                              │
  │ /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/reque │
  │ st.py:542 in _open                                                           │
  │                                                                              │
  │ /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/reque │
  │ st.py:502 in _call_chain                                                     │
  │                                                                              │
  │ /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/reque │
  │ st.py:1397 in https_open                                                     │
  │                                                                              │
  │ /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/reque │
  │ st.py:1357 in do_open                                                        │
  ╰──────────────────────────────────────────────────────────────────────────────╯
  URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify
  failed: unable to get local issuer certificate (_ssl.c:1131)>
  error: nodeenv-creation-failed
  
  × Failed to create a `nodeenv`
  ╰─> See above for failure output from the underlying tooling.
  
  hint: A `urllib.error.HTTPError` would indicate mean that the issue is related
        to the network, or the NodeJS servers, or the node version that this tool
        is trying to fetch is no longer available.
  
  Link: https://sphinx-theme-builder.rtfd.io/errors/#nodeenv-creation-failed
  ----------------------------------------
  ERROR: Failed building wheel for pydata-sphinx-theme
Failed to build pydata-sphinx-theme
ERROR: Could not build wheels for pydata-sphinx-theme, which is required to install pyproject.toml-based projects

</details>

**Comment by hasan-yaman** [comment]
It looks like the working last commit is [pydata/pydata-sphinx-theme@56d5621](https://github.com/pydata/pydata-sphinx-theme/commit/56d5621276ce8a2fb96c091fa294a98e19479ced) and the first broken commit is [pydata/pydata-sphinx-theme@579d7ce](https://github.com/pydata/pydata-sphinx-theme/commit/579d7ce695cb5c2611aa7b8ab76fbc3efc5fab26)

Also, I couldn't find a reason to install the latest version of pydata-sphinx-theme. The latest version (0.7.2) seems to work fine.

**Comment by hasan-yaman** [comment]
It seems like the problem continues in the master branch but the latest version of pydate-sphinx-theme (0.8.0) doesn't have the problem.

**Comment by jorisvandenbossche** [comment]
@hasan-yaman would you like to open an issue at https://github.com/pradyunsg/sphinx-theme-builder/ as well? 
I understand that this is a problem for creating a pandas development environment (and we can fix it by no longer installing the dev version), but in theory the install _should_ work, so it could be a bug in sphinx-theme-builder (or nodeenv).

**Comment by hasan-yaman** [comment]
@jorisvandenbossche thank you for the suggestion, i will open.
