### ISSUE TITLE
BUG: Duplicate columns when select subsets with same columns

### ISSUE THREAD

**Issue by dchvn** [pandas-dev/pandas#45439]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
pdf = pd.DataFrame([1,2,3,4], columns=['a'])
pdf = pdf[['a', 'a']]
pdf[['a', 'a']]
```

### Issue Description

Duplicate columns when select subsets with same columns

```python
>>> import pandas as pd
>>> pdf = pd.DataFrame([1,2,3,4], columns=['a'])
>>> pdf
   a
0  1
1  2
2  3
3  4
>>> pdf = pdf[['a', 'a']]
>>> pdf
   a  a
0  1  1
1  2  2
2  3  3
3  4  4
>>> pdf[['a', 'a']]
   a  a  a  a
0  1  1  1  1
1  2  2  2  2
2  3  3  3  3
3  4  4  4  4
```

### Expected Behavior

```python
>>> import pandas as pd
>>> pdf = pd.DataFrame([1,2,3,4], columns=['a'])
>>> pdf
   a
0  1
1  2
2  3
3  4
>>> pdf = pdf[['a', 'a']]
>>> pdf
   a  a
0  1  1
1  2  2
2  3  3
3  4  4
>>> pdf[['a', 'a']]
   a  a  
0  1  1  
1  2  2  
2  3  3  
3  4  4 
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d
python           : 3.9.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.11.0-44-generic
Version          : #48~20.04.2-Ubuntu SMP Tue Dec 14 15:36:44 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.5
numpy            : 1.21.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.1.2
setuptools       : 57.0.0
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : 3.0.4
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : None
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.5.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 6.0.1
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : 1.4.29
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by dchvn** [comment]
Related issue https://issues.apache.org/jira/browse/SPARK-37930

**Comment by phofl** [comment]
This behaves as expected. The first "a" selects all columns named ``a``. While the second does the same.

With unique column names this behaves the same:

```
df = pd.DataFrame({"a": [1]})
df[["a", "a"]]
```

returns

```
   a  a
0  1  1
```

which is correct

**Comment by dchvn** [comment]
Thank you
