### ISSUE TITLE
QST: how i slove problem like it 

### ISSUE THREAD

**Issue by schild** [pandas-dev/pandas#45452]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

polling question 

### Question about pandas

```import pandas  as pd
import numpy  as np
df = pd.DataFrame({'col1': np.arange(6), 'col2': np.arange(2, 8)})
df
```
<html>
<body>

col1 | col2
-- | --
0 | 3
1 | 4
2 | 5
3 | 6
4 | 7

</body>
</html>

and i want get column col3 if condition with after rolling.tail(3) and re turn count(col1>=3 and col2>=3)
the last result i want it `likes：`
<html>
<body>

col1 | col2 | col3 | reason
-- | -- | -- | --
0 | 3|0| 
1 | 4|1| [(3>=3 and 6>=3)]
2 | 5|2| [(3>=3 and 6>=3),(4>=3 and 7>=3)]
3 | 6|nan| 
4 | 7|nan| 

</body>
</html>
Hope to get your reply as soon as possible

**Comment by MarcoGorelli** [comment]
Hey - sorry, answering usage questions like this doesn't scale here, please ask on StackOverflow (but do open an issue if you find a bug) - thanks!
