### ISSUE TITLE
BUG: Issue converting a nested FrozenDict into a df

### ISSUE THREAD

**Issue by siddharthrajaraja** [pandas-dev/pandas#45468]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
res = .. # some end point sending a nested frozen dict as a reponse
df = pd.DataFrame(res)
```

### Issue Description

When I try to convert the nested frozen dict into a df I found that the level 1 key values are easily detected but the nested frozen dic key value pairs are converted into a pd series and not an object type 

### Expected Behavior

We expect to convert the nested frozen dict into an obj type acting as a value of the df column `xx`

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d
python           : 3.8.11.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.47-linuxkit
Version          : #1 SMP Sat Jul 3 21:51:47 UTC 2021
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.5
numpy            : 1.17.4
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.1.3
setuptools       : 57.0.0
Cython           : None
pytest           : 4.6.9
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
None

</details>

**Comment by mroeschke** [comment]
Could you provide a reproducible example? https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by phofl** [comment]
Closing for now. Please ping to reopen if you are able to provide a reproducible example
