### ISSUE TITLE
REGR: roundtrip pandas<->pyarrow conversion for Period dtype broken for older pyarrow versions

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#45470]
To have an issue tracking https://github.com/pandas-dev/pandas/pull/44681#issuecomment-1015274292

Reproducible snippet:

```python
import pyarrow as pa

df = pd.DataFrame({"col": pd.period_range("2012", periods=3)})
pa.table(df).to_pandas()
```

No longer works with pyarrow < 4

**Comment by mroeschke** [comment]
Looks like we might have related xfailed tests already

https://github.com/pandas-dev/pandas/blob/b8cce91ee7bcc86877d4679cd8a9454b5995c2c6/pandas/tests/arrays/period/test_arrow_compat.py#L74-L132

**Comment by jorisvandenbossche** [comment]
Yes, but that only silences the tests, we should still fix the regression itself :)

The fix should be relatively straightforward I think, see https://github.com/pandas-dev/pandas/pull/44681#issuecomment-1015665238
