### ISSUE TITLE
DOC: Development with pip installation needs to say to use python 3.8

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#45472]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/development/contributing_environment.html#creating-a-python-environment-pip

### Documentation problem

If you are creating a virtual environment using `pip` to do pandas development, you have to use python 3.8.  If you use python 3.9, then the dependency build may fail or take a really long time.  There is nothing in `requirements-dev.txt` that says that python 3.8 is required (unlike `environment.yml`, which does specify python 3.8).

I was supporting someone doing pandas development at a company where use of `conda` is not allowed due to anaconda's new licensing restrictions, so we have to make sure that using `pip` is supported and correctly documented.  The solution was to create a virtual environment using python 3.8, as he was using python 3.9.

In addition, the docs for the Unix/MacOS set up for pip say to create a virtual environment using python 3.7.6, but we're not supporting python 3.7 any more.

### Suggested fix for documentation

- Mention in this section to use python 3.8 and to look in `environment.yml` for the correct python version (in case we up it to 3.9 in the future and forget to update the docs)
- Change the set up listing for Linux/MacOS to specify some version of python 3.8 (3.8.12??)

**Comment by marco-georgaklis** [comment]
take

**Comment by itaise** [comment]
take

**Comment by isevitt** [comment]
take

**Comment by mroeschke** [comment]
Looks like we have a link now to the minimum supported Python version so I think we can close this https://pandas.pydata.org/docs/development/contributing_environment.html#option-2-using-pip
