### ISSUE TITLE
ENH: support popping multiple columns in df.pop 

### ISSUE THREAD

**Issue by alonme** [pandas-dev/pandas#45497]
#### Is your feature request related to a problem?

Currently pop accepts a single label, i would like to be able to pop multiple columns ( and get a pd.DataFrame as a result)

#### Describe the solution you'd like

the `item` parameter of `df.pop` should also accept a list of labels

#### API breaking implications

There shouldn't be.

#### Describe alternatives you've considered

the alternative is to implement this myself with something like
`pd.concat([df.pop(label) for label in ['label1', 'label2']], axis=1)`

**Comment by jreback** [comment]
the alternative is to use .drop or simple selection 

-1 on any change here

**Comment by alonme** [comment]
My idea was to be able to perform this in a single action.

It is of course possible to use *both*  selection and drop to do that. (See Below)

```
In [400]: df = pd.DataFrame([np.arange(8)], index=np.arange(1), columns=['a1','a2','a3','a4','b1','b2','b3','b4'])

In [401]: df
Out[401]:
   a1  a2  a3  a4  b1  b2  b3  b4
0   0   1   2   3   4   5   6   7

In [402]: a_columns = ['a1','a2','a3','a4']

In [403]: dfa = df[a_columns]

In [404]: dfb = df.drop(columns=a_columns)

In [405]: dfa
Out[405]:
   a1  a2  a3  a4
0   0   1   2   3

In [406]: dfb
Out[406]:
   b1  b2  b3  b4
0   4   5   6   7
```

**Comment by jreback** [comment]
overloading api is not warranted
