### ISSUE TITLE
BUG: missing newline when `info` is called on DataFrame

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#45494]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
>>> import pandas as pd
>>> pd.DataFrame().info()
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Empty DataFrame>>> 
```

### Issue Description

Note how, for the second example `pd.DataFrame().info()`, there is a missing newline at the end of the output

### Expected Behavior

```python
>>> import pandas as pd
>>> pd.DataFrame().info()
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Empty DataFrame
>>> 
```

### Installed Versions

<details>

home/marco/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/fastparquet/dataframe.py:5: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import (

INSTALLED VERSIONS
------------------
commit           : 04f5721617a622912f493f42f160139e073d0c2f
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-94-generic
Version          : #106-Ubuntu SMP Thu Jan 6 23:58:14 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.5.0.dev0+130.g04f5721617
numpy            : 1.21.1
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 49.6.0.post20210108
Cython           : 0.29.24
pytest           : 6.2.5
hypothesis       : 6.24.2
sphinx           : 4.1.2
blosc            : None
feather          : None
xlsxwriter       : 3.0.2
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.29.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fastparquet      : 0.7.0
fsspec           : 2021.10.1
gcsfs            : 2021.10.1
matplotlib       : 3.4.1
numba            : 0.53.1
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 4.0.0
pyreadstat       : 1.1.2
pyxlsb           : None
s3fs             : 2021.10.1
scipy            : 1.7.0
sqlalchemy       : 1.4.22
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : 0.18.2
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None

</details>

**Comment by Ninsta22** [comment]
take
