### ISSUE TITLE
BUG: .replace does not support None as a target value

### ISSUE THREAD

**Issue by jmg-duarte** [pandas-dev/pandas#45490]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
pd.DataFrame({'a': [pd.NA]}).replace(pd.NA, None)
```

### Issue Description

The replace function uses `None` instead of a sentinel value to check for a missing argument, thus it does not allow `None` to be used.

The `fillna` function also has this problem.

### Expected Behavior

The replace function should allow the usage of `None` as a target value.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d
python           : 3.8.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.3.5
numpy            : 1.18.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 59.8.0
Cython           : 0.29.26
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : 1.4.30
tables           : None
tabulate         : None
xarray           : 0.20.2
xlrd             : None
xlwt             : None
numba            : 0.49.1
</details>

**Comment by jreback** [comment]
this is changed in 1.4.0rc0 
pls check

**Comment by jmg-duarte** [comment]
It works, any idea when 1.4.0 will be released?

**Comment by jreback** [comment]
shortly
