### ISSUE TITLE
BUG: to_latex doesn't convert CSS 

### ISSUE THREAD

**Issue by schorschie** [pandas-dev/pandas#45520]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

# create some Dataframe
df = pd.DataFrame([[1, 2,], [3, 4]], 
                  columns=['A', 'B'], 
                  index=['a', 'b'])

# Create some style which contains bold font
bold_column = pd.IndexSlice[df.index , ['B']]
bold_style = lambda x: 'font-weight: bold;'

# Display
display(df.style.applymap(bold_style, 
                          subset=bold_column).to_latex())
```

### Issue Description

The to latex command shall yield a string, that can be parsed with latex. but the `\font-weightbold x` is not valid  latex cammand. I used the latex imports from the documentation, my preamble looks like this:

    \documentclass{article}

    \RequirePackage{multirow}
    \RequirePackage{booktabs}
    \RequirePackage[table]{xcolor}
    \RequirePackage{siunitx}
    \RequirePackage{etoolbox}
    \RequirePackage{etoolbox}

    \robustify\bfseries
    \robustify\itshape

    \begin{document}
    \sisetup{detect-all = true}

    \begin{tabular}{lrr}
        {} & {A} & {B} \\
        a & 1 & \font-weightbold 2 \\
        b & 3 & \font-weightbold 4 \\
    \end{tabular}
    
    \end{document}

### Expected Behavior

The expected string would be `\textbf{x}`, including the curly brackets. They ensure, that not only the next letter is bold.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d
python           : 3.10.1.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18363
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : German_Switzerland.1252

pandas           : 1.3.5
numpy            : 1.22.0
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 60.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.30.1
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.5.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by Compro-Prasad** [comment]
@schorschie You need to use the following code for setting bold style:

```
bold_style = lambda x: 'textbf:--rwrap;'
```

Reference: https://pandas.pydata.org/docs/reference/api/pandas.io.formats.style.Styler.to_latex.html

Feel free to close this issue.

**Comment by attack68** [comment]
or don't forget the CSS conversion: `to_latex(convert_css=True)`
