### ISSUE TITLE
PERF: to_csv very slow when exporting a small slice of a large multiindexed dataframe 

### ISSUE THREAD

**Issue by richbon75** [pandas-dev/pandas#45535]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this issue exists on the main branch of pandas.

### Reproducible Example

I ran into a surprising performance problem that took me awhile to identify.  On a large DataFrame, with a 2-level MultiIndex where the second level is  pd.Timestamp values, exporting a small slice of it with `to_csv` takes a surprisingly long time.

If the "sliced" dataframe has .reset_index() called on it BEFORE exporting with `to_csv`, it is much faster.

In the example below, on my machine the export with index took ~ 6.5 seconds, and the unindexed version took  ~ 0.04 seconds.  The indexed version takes over 160x as long.

```
# %% Setup
import io
import time
import pandas as pd
import numpy as np
import cProfile

# %% Make a large dataframe.

# Imagine it's some metric recorded once per second for 5 different pets over 20 days.
pets = ["cat", "dog", "fish", "bird", "goat"]
timestamps = pd.date_range(
    start=pd.Timestamp("2021-01-01 00:00:00+00:00"),
    end=pd.Timestamp("2021-01-20 00:00:00+00:00"),
    freq="1S",
)
N = len(pets) * len(timestamps)

df = pd.DataFrame(
    data={
        "pet": sum([[pet] * len(timestamps) for pet in pets], []),
        "timestamp": timestamps.to_list() * len(pets),
        "metric": [np.random.uniform()] * N,
    }
)

# %% Index and sort the data

df = df.set_index(keys=["pet", "timestamp"]).sort_index()

print(f"The whole dataset is {len(df)} rows.")

# %% Now imagine I want to export just one particular hour of data for the dog.

save_slice_tuple = (
    "dog",
    slice(
        pd.Timestamp("2021-01-02 00:00:00+00:00"),
        pd.Timestamp("2021-01-02 00:59:59+00:00"),
    ),
)
s_df = df.loc[save_slice_tuple, :]

print(f"The slice I want to save is only {len(s_df)} rows.")

# %% Write the slice to a csv file. THIS IS SLOW. ~ 6.5 seconds

file_buffer = io.BytesIO()
st = time.time()
with cProfile.Profile() as pr:
    s_df.to_csv(file_buffer, index=True)
et = time.time()
print(f"Time to prepare {len(s_df)} line CSV file from indexed slice: {et-st} seconds")
print(f"File bytes: {file_buffer.getbuffer().nbytes}")
# pr.print_stats()
pr.dump_stats("profile_csv.prf")


# %% Same slice of data, but reset the index first.  MUCH FASTER.  ~ 0.04 seconds

file_buffer = io.BytesIO()
st = time.time()
s_df = s_df.reset_index()                  # reset_index
with cProfile.Profile() as pr:
    s_df.to_csv(file_buffer, index=False)  # no longer need to output the index
et = time.time()
print(
    f"Time to prepare {len(s_df)} line CSV file from unindexed slice: {et-st} seconds"
)
print(f"File bytes: {file_buffer.getbuffer().nbytes}")
# pr.print_stats()
pr.dump_stats("profile_csv_no_index.prf")
```

In looking at the profiles, for the poorly performing `to_csv` with the index, it is spending the vast majority of its time in `{pandas._libs.tslib.format_array_from_datetime}` which seems unusual.

![image](https://user-images.githubusercontent.com/8406130/150576342-048af917-362b-4eec-a196-6710bc1bf826.png)

In looking at the better performing `to_csv` call on the unindexed dataframe, while the call to `{pandas._libs.tslib.format_array_from_datetime}` still represents a significant part of the runtime, it is a smaller proportion and much faster.

![image](https://user-images.githubusercontent.com/8406130/150576744-99067e5b-0b2d-45f6-891b-6ed7212d0e7c.png)

I presume something is happening in the export of the indexed dataframe where it is converting many more datetime values than is necessary to actually perform the export.

Additional observations:
* I think this is specific to `to_csv`.  I tried a similar experiment with `to_parquet` and there was no significant performance difference - both were fast.
* The problem seems specific to MultiIndexes, since I tried this with a dataframe of a single index on `timestamp` and the slice did not take any longer to export.
* I saw the same behavior even if I excluded the index from the output of the indexed slice with `s_df.to_csv(file_buffer, index=False)`  Even though the timestamp was no longer going to the output, it still took a very long time to run.  

In the meantime, I can work around this by simply resetting the index on my sliced dataframe before exporting, but this was some very surprising behavior.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d
python           : 3.8.5.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
Version          : Darwin Kernel Version 19.6.0: Sun Nov 14 19:58:51 PST 2021; root:xnu-6153.141.50~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.5
numpy            : 1.21.4
pytz             : 2021.3
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 47.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.6 (dt dec pq3 ext lo64)
jinja2           : None
IPython          : 8.0.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 6.0.1
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by phofl** [comment]
Please try on 1.4rc. I think we fixed this

**Comment by phofl** [comment]
Probably a duplicate of #37484

**Comment by richbon75** [comment]
Indeed.  I just tried it in pandas-1.4.0rc0 and both versions ran quickly.  Thank you!  Closing.
