### ISSUE TITLE
PERF: DataFrame.agg method is very slow 

### ISSUE THREAD

**Issue by fshabashev** [pandas-dev/pandas#45538]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this issue exists on the main branch of pandas.

### Reproducible Example

```
import pandas

import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randint(0,100,size=(5000000, 4)), columns=list('ABCD'))


import datetime
before = datetime.datetime.now()
tmp1 = df.agg(list, axis=1)
after = datetime.datetime.now()
print(after - before)

import datetime
before = datetime.datetime.now()
tmp2 = pandas.Series(df.values.tolist())
after = datetime.datetime.now()
print(after - before)

print("checking equality", tmp1.equals(tmp2))
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.8.2.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
Version          : Darwin Kernel Version 19.6.0: Sun Nov 14 19:58:51 PST 2021; root:xnu-6153.141.50~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.4
numpy            : 1.20.3
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.23.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 2021.05.0
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

### Prior Performance

DataFrame.agg method is almost 100 times slower than the tolist() method when  in comparable example. 
This line:
```tmp = df.agg(list, axis=1)```
takes more than a minute to run while this:
```tmp = df.values.tolist() ```
produces the same output in a few seconds. 

Since the output of these two methods is the same, there might be some performance issues with the agg method that prevents it from working as fast as the tolist method.

**Comment by phofl** [comment]
The output is not the same. agg returns a Series, while tolist returns a list of lists.

agg usese apply in the background, which iteraters over the Series

**Comment by phofl** [comment]
Does not change the fact that agg uses apply, which is Slow. This is documented too. I don‘t think that we can do much here

**Comment by fshabashev** [comment]
got it, I'd close the issue then.

**Comment by AlexKirko** [comment]
Closing, since the OP agreed to it.
