### ISSUE TITLE
ENH: Frequency, Probability functions on categorical columns

### ISSUE THREAD

**Issue by AymanElsayeed** [pandas-dev/pandas#45549]
I think it useful to have two functions:

- frequency, which calculates the frequency of each value in categorical columns, which could be done by using value counts function results and dividing by row number.
- probabilities, given a category returns the probability of that category in the same categorical columns.

NA values could be dropped or treated as a category.

Also, those functions could be very useful with discrete numeric values.

**Comment by jreback** [comment]
show pseudo code and expected results

**Comment by AymanElsayeed** [comment]
Here is an example, i used API extensions to do that:

```python

import pandas as pd

@pd.api.extensions.register_dataframe_accessor("Cat")
class Cat:
    def __init__(self, pandas_obj):
        self._df: pd.DataFrame = pandas_obj
        is_all_cat = self._df.apply(lambda col: col.dtype.name == pd.CategoricalDtype.name).all()
        if not is_all_cat:
            raise TypeError(f"columns must be Categorical type {self._df.dtypes}")

    def freq(self):
        """
        Frequency of each value in each column
        :return:
        """
        freq = self._df.apply(lambda col: col.value_counts())
        freq.fillna(value=0, inplace=True)
        return freq

    def prob(self):
        """
        Probability of each value in each column
        :return:
        """
        prob = self._df.apply(lambda col: col.value_counts()/col.shape[0])
        prob.fillna(value=0, inplace=True)
        return prob

```

Can this functionality be built in?
How can i add it?

**Comment by jreback** [comment]
.describe already does
this for categoricals 

or can use value_counts

-1 on adding more api

**Comment by rhshadrach** [comment]
I don't understand how this request differs from using `.value_counts(normalize=False)` and `.value_counts(normalize=True)`:

```
ser = pd.Series([1, 1, 2, 2, 2, 3, 4], dtype='category')
print(ser.iloc[:5].value_counts())
print(ser.iloc[:5].value_counts(normalize=True))
```

produces

```
2    3
1    2
3    0
4    0
dtype: int64
2    0.6
1    0.4
3    0.0
4    0.0
dtype: float64
```

**Comment by mroeschke** [comment]
Thanks for the request, but since there hasn't been enough core developer support for this issue (due to existing functionality) closing.
