### ISSUE TITLE
Addition of a new merge/filter logic for Dataframes

### ISSUE THREAD

**Issue by sameer12year** [pandas-dev/pandas#45553]
#### Is your feature request related to a problem?

Suppose there are 2 pandas DataFames A & B. We want to keep only those rows in A which are uncommon with DataFrame B. Currently there's no easy way to perform this operation directly although a function should be there to handle this operation. This is a challenge that I face quite often while using pandas and this can be easily implemented in the source code.

**Comment by jreback** [comment]
show an example in pseudo code and expected output

**Comment by sameer12year** [comment]
> show an example in pseudo code and expected output

dataFrame1 = pd.DataFrame(
   {
      "alphabets": ['a', 'b', 'c', 'd', 'e', 'f'],
      "numerals": [1, 2, 3, 4, 5, 6]
   }
)

dataFrame2 = pd.DataFrame(
   {
      "alphabets": ['e', 'f'],
      "numerals": [5, 6]
   }
)



**Case 1: I want to use dataFrame2 as filter for dataFrame1 to remove all corresponding rows which exist in dataFrame2:**

Output in this case should look like this:
{
      "alphabets": ['a', 'b', 'c', 'd'],
      "numerals": [1, 2, 3, 4]
   }

**=>** The problem is quite simple that we just want to exclude all entries from dataFrame1 which exist in dataFrame2. There are some indirect and non-optimal ways of doing it but there's no direct function to do it.


**Case 2: We have a list of filter: **filter_list = ['b', 'd', 'e']**. We want to remove all these filter entires from dataFrame1.**


Output in this case should look like this:
{
      "alphabets": ['a', 'c', 'f'],
      "numerals": [1, 3, 6]
   }

**=>** For this case as well there's no direct way of arriving at the shown out using currently available pandas functions although there are ways to do it indirectly in multiple steps.

Do let me know if you need more clarity. If this feature gets added, then I am sure it will solve many people's issue who resort to other inefficient ways to achieve the same output.

**Comment by jreback** [comment]
these are easily accomplished via

the indicators columns or using isin

**Comment by sameer12year** [comment]
Yes, I agree with you for the 'case-2' that I highlighted above. Yes we can directly pass on filter list in the isin condition but we cannot do row-level filtering with that if you again look at case-1. In case-, we are directly removing all the rows which are present in the other filter dataFrame. You can do that with 2-3 lines of code but there's no direct way to solve case-1.

Happy to be corrected if I am wrong.

**Comment by sameer12year** [comment]
> these are easily accomplished via
> the indicators columns or using isin

Yes, I agree with you for the 'case-2' that I highlighted above. Yes we can directly pass on filter list in the isin condition but we cannot do row-level filtering with that if you again look at case-1. In case-1, we are directly removing all the rows which are present in the other filter dataFrame. You can do that with 2-3 lines of code but there's no direct way to solve case-1.

Happy to be corrected if I am wrong.

We can apply isin() function by running a loop on all columns but there should be a direct way to do that just like we have options to get common rows between 2 DataFrames using the pd.merge(how='inner') function.

**Comment by phofl** [comment]
This sounds like #42916?

**Comment by rhshadrach** [comment]
> => For this case as well there's no direct way of arriving at the shown out using currently available pandas functions although there are ways to do it indirectly in multiple steps.

It sounds like you may already be aware, but 

     df[~df['alphabets'].isin(filter_list)]

I think accomplishes what you're after directly in one step. In any case, I don't think "can't accomplish an operation in one step" is sufficient justification to add to the pandas API.

Assuming this correctly handles case 2, agree with @phofl that case 1 is duplicative of an anti-join.

**Comment by sameer12year** [comment]
@rhshadrach, I am completely aligned with you on case-2 that it can be directly solved in one step using the isin() clause. 
Yes, you correctly pointed out that case-1 is basically **LEFT-Anti join**. Being a Data Scientist, I wrangle big dataframes and data comes from varied sources but whenever I want to remove certain rows from a dataFrame-1 which are present in dataFrame2, I have to do it in multiple steps.

I just want to make other's life easier who bump into such issues. My point is just that if this anti-join is added in the API then it will make pandas much more powerful.

Happy to be corrected if I am wrong.

**Comment by jreback** [comment]
closing as duplicate

**Comment by sameer12year** [comment]
Thanks for letting me know that it's already in production.
