### ISSUE TITLE
No way to access correlation significance value (Spearman, Kendall)

### ISSUE THREAD

**Issue by smdabdoub** [pandas-dev/pandas#4557]
The corr()  method attached to DataFrames is a great way to get a matrix of correlation coefficients. But for the Kendall and Spearman options, the p-value is discarded:

https://github.com/pydata/pandas/blob/8ac0e11b59b65f0ac898dca2beebde5f87836649/pandas/core/nanops.py#L510-L517

For a function called corr() this would certainly be expected behavior, but the problem remains that there is no other method (as far as I've been able to find) to get those significance values without going back to scipy and doing it myself.

**Comment by jorisvandenbossche** [comment]
Closing this for now as out of scope for pandas. We can always reopen the discussion if someone is really interested in this and has a proposal for specific API.
