### ISSUE TITLE
DOC: don't suggest melt instead of lookup

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#45589]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://github.com/pandas-dev/pandas/blob/12475e00c0d683673ecd32c4d6cf854da2fcd342/pandas/core/frame.py#L4562-L4566

### Documentation problem

It suggested to use `loc` and `melt`. However, the example from https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-lookup suggests to instead use `factorize` and NumPy indexing.

This a lot faster, so that should be suggested instead

### Suggested fix for documentation

Suggest to use `factorize` and `NumPy` indexing, rather than `loc` and `melt`

**Comment by adi611** [comment]
Please assign me this issue.

**Comment by MarcoGorelli** [comment]
done
