### ISSUE TITLE
parse_dates argument in read_sql() example: "y" lowercase

### ISSUE THREAD

**Issue by mdlstudioar** [pandas-dev/pandas#45583]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.read_sql.html

### Documentation problem

"Examples" 

3. Apply custom formatting when date parsing the values of “date_column”

pd.read_sql('SELECT int_column, date_column FROM test_data',
            conn,
            parse_dates={"date_column": {"format": "%d/%m/%**y"**}})

_y_ is in lowercase, so the output doesn't change

<img width="735" alt="Screen Shot 2022-01-24 at 03 15 05" src="https://user-images.githubusercontent.com/68649892/150731566-84922419-b32f-4471-821a-184e33b3b974.png">

### Suggested fix for documentation

You should change it to uppercase

pd.read_sql('SELECT int_column, date_column FROM test_data',
            conn,
            parse_dates={"date_column": {"format": "%d/%m/%**Y"**}})
<img width="700" alt="Screen Shot 2022-01-24 at 03 16 58" src="https://user-images.githubusercontent.com/68649892/150731661-8eae941f-9772-4a3a-a4d6-636d31ff5446.png">

**Comment by ashaypatil12** [comment]
Hi @mdlstudioar , Sorry I am new to Open Source, can you please explain why "Y" is needed instead of "y". They both provide examples of parse dates wherein the argument is passed in form of a dictionary.

**Comment by mroeschke** [comment]
Thanks for the suggestion, but this example is doctested so it's correct in behavior and I don't think this change is significant enough to warrant a change. Closing
