### ISSUE TITLE
BUG: fillna downcast object to int even downcast=False/None

### ISSUE THREAD

**Issue by yinweisu** [pandas-dev/pandas#45603]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.Series([1,2,3], dtype='object')
df.fillna('', downcast=False)  # will get int64 instead
```

### Issue Description

fillna will convert an object dataframe to int64 dataframe even when downcast is specified to be False or None

### Expected Behavior

The dataframe should keep the original dtype

### Installed Versions

<details>

NSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.9.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.0
numpy            : 1.21.4
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 57.4.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by phofl** [comment]
This is already known, see #44241

**Comment by jbrockmendel** [comment]
I think downcast=False is separate from #44241

**Comment by phofl** [comment]
The note inline says:

```
            # GH#44241 We downcast regardless of the argument;
            #  respecting 'downcast=None' may be worthwhile at some point,
            #  but ATM it breaks too much existing code.
            # split and convert the blocks
```

So this sounded related to me.

**Comment by jbrockmendel** [comment]
definitely related, but not identical.  when we did #44241 we were focused on "None" and "infer", and False was an afterthought.  IIRC there was only one place where we used downcast=False and it was in the io code so we just changed that, so there are no tests that use it.

**Comment by phofl** [comment]
Got you, thx

**Comment by simonjayhawkins** [comment]
first bad commit: [3bbaa8952f673c7aa7757ff85fff7b04de08950c] BUG: Series[object].fillna ignoring downcast='infer' (#45062)
