### ISSUE TITLE
BUG: OptionError: Pattern matched multiple keys - pd.set_option()

### ISSUE THREAD

**Issue by chrispryer** [pandas-dev/pandas#45619]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

pd.set_option("max.columns", 500)
```

### Issue Description

`OptionError` does not throw on environment using 1.3.5.

```
...
Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.set_option("max.columns", 500)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\users\pryerc\github\sandbox\venv\lib\site-packages\pandas\_config\config.py", line 256, in __call__
    return self.__func__(*args, **kwds)
  File "C:\users\pryerc\github\sandbox\venv\lib\site-packages\pandas\_config\config.py", line 149, in _set_option
    key = _get_single_key(k, silent)
  File "C:\users\pryerc\github\sandbox\venv\lib\site-packages\pandas\_config\config.py", line 116, in _get_single_key
    raise OptionError("Pattern matched multiple keys")
pandas._config.config.OptionError: Pattern matched multiple keys
```

### Expected Behavior

Set option without error.

### Installed Versions

<details>
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.10.1.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : English_United States.1252

pandas           : 1.4.0
numpy            : 1.22.1
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
</details>

**Comment by phofl** [comment]
Your statement is not specific enough. You have to use ``display.max_columns`` (as documented here https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html). We added a new option ``styler.render.max_columns`` in 1.4
