### ISSUE TITLE
BUG: describe does not generate unique values for numbers, inconsistent with nunique

### ISSUE THREAD

**Issue by Archer6621** [pandas-dev/pandas#45617]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame(
    {
        "A": [1, 2, 2],
        "B": [1.3, 1.3, 1.3],
        "C": ['a', 'b', 'c']
    }
)

print(df.describe(include='all'))
print()
print("nunique for A:", df.A.nunique())
print("nunique for B:", df.B.nunique())
```

### Issue Description

Currently the unique statistic for number series shows up as `NaN` in `DataFrame.describe`, even though calling `nunique` on such a series does produce a number (that can be useful for e.g. identifying fully unique series in a standard way for all series, especially with an integer type).

Output of the above example:
```
               A    B    C
count   3.000000  3.0    3
unique       NaN  NaN    3
top          NaN  NaN    a
freq         NaN  NaN    1
mean    1.666667  1.3  NaN
std     0.577350  0.0  NaN
min     1.000000  1.3  NaN
25%     1.500000  1.3  NaN
50%     2.000000  1.3  NaN
75%     2.000000  1.3  NaN
max     2.000000  1.3  NaN

nunique for A: 2
nunique for B: 1
```

### Expected Behavior

I would expect the `unique` field in `DataFrame.describe` for number series to work the same way as `nunique` being called directly on a number series, but now it just shows `NaN`.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.9.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.0-9-amd64
Version          : #1 SMP Debian 5.10.70-1 (2021-09-30)
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.0
numpy            : 1.20.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : 0.29.24
pytest           : 6.2.4
hypothesis       : None
sphinx           : 4.2.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.1
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.29.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fastparquet      : None
fsspec           : 2021.08.1
gcsfs            : None
matplotlib       : 3.4.3
numba            : 0.54.1
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : 1.4.22
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None

</details>

**Comment by phofl** [comment]
This behaves as documented (see https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html). Hence this is not a bug.

**Comment by attack68** [comment]
if this is of interest you can support it with a thumbs up: #43894

**Comment by Archer6621** [comment]
> if this is of interest you can support it with a thumbs up: #43894

Seems what I was really looking for was `.agg`, which I found after clicking around a bit via your issue link, so thanks!
