### ISSUE TITLE
 ENH: In-built functions/API or utility to handle avro files

### ISSUE THREAD

**Issue by KayvanShah1** [pandas-dev/pandas#45614]
#### Is your feature request related to a problem?

It would be great if pandas has inbuilt capabilities to handle - read, write, update, manipulate `Avro` files

#### Describe the solution you'd like

`read_avro()` and `to_avro()` functions

#### Describe alternatives you've considered

There are two installable libraries for working with Avro files:
[avro](https://avro.apache.org/) & [fastavro](https://fastavro.readthedocs.io/en/latest/)

#### Additional context
- https://towardsdatascience.com/csv-files-for-storage-absolutely-not-use-apache-avro-instead-7b7296149326

**Comment by jreback** [comment]
this was asked in #11752

if a fully baked and tested PR was proposed would not object

**Comment by jorisvandenbossche** [comment]
Some relevant discussion about this on the fastavro side: https://github.com/fastavro/fastavro/issues/112

To be honest, I think this should be rather implemented as a third-party package first, and if that exists, we can still consider whether we want to optionally depend on that and wrap it in a `to_avro`/`read_avro`

**Comment by mroeschke** [comment]
Thanks for the request. We have this logged in our master IO tracker https://github.com/pandas-dev/pandas/issues/30407, and agreed utilizing a 3rd party parser would be idea. Closing as in our master tracker.
