### ISSUE TITLE
BUG: 1.4.0 does not preserve initially empty Index and appended by `loc` assignment.

### ISSUE THREAD

**Issue by ketozhang** [pandas-dev/pandas#45621]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame(columns=["a", "b"]).set_index("a")
print(df.index, id(df.index))  # Index([], dtype='object', name='a') 4644041536
df.loc[0] = {"b": 0}
print(df.index, id(df.index))  # Int64Index([0], dtype='int64') 4726025904
```

### Issue Description

Given an empty dataframe with a index column name set, when adding a row on a specific index using `df.loc[INDEX]`, the original index is not preserved. Furthermore, what gets returned is not type`Index` but is `Int64Index` when the passed in index is an integer.

### Expected Behavior

The modified index should print out `Index([0], dtype='int64', name='a')`.

### Installed Versions

1.4.0

**Comment by phofl** [comment]
@jbrockmendel This was changed in #43507, looks somehow intended. Did you mean to change this also for the index?

**Comment by jbrockmendel** [comment]
IIRC the dtype change is expected, but losing the name is not
