### ISSUE TITLE
BUG: resample.last return non-nan value by default

### ISSUE THREAD

**Issue by tade0726** [pandas-dev/pandas#45656]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np


ts = pd.date_range("2021-01-01", periods=11, freq="30min")
S = pd.Series(range(len(ts)), index=ts)

# change the last value to nan
S[-1:] = np.nan

# return the first non-nan value
S.resample("1h", origin="end").last()

# get error
# TypeError: too many arguments passed in
S.resample("1h", origin="end").last(numeric_only=True)
```

### Issue Description

Hi, 

I am using `resample.last`. Based on the doc, the default behavior of `last` should return the last value regards if it is nan(https://pandas.pydata.org/docs/reference/api/pandas.core.resample.Resampler.last.html).

But it returns the first non-nan value in my practice in version 1.4.0.

Also, the doc mentioned `numeric_only` parameter can be passed to change the default behavior. But in the actual lib, the `last` function did not accept that argument, and raised `TypeError: too many arguments passed in` .

Thanks

### Expected Behavior

The default behavior of `last` should return the last value regards if it is nan(https://pandas.pydata.org/docs/reference/api/pandas.core.resample.Resampler.last.html)

And the parameters mentioned in the doc should be accepted.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.9.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.16.3-microsoft-standard-WSL2
Version          : #1 SMP Fri Apr 2 22:23:49 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.0
numpy            : 1.20.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : 0.29.25
pytest           : 6.2.5
hypothesis       : None
sphinx           : 4.2.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.2
lxml.etree       : 4.7.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.29.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fastparquet      : None
fsspec           : 2022.01.0
gcsfs            : None
matplotlib       : 3.5.0
numba            : 0.54.1
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : 1.4.27
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None

</details>

**Comment by PurnaChandraMansingh** [comment]
HI, I would like to work on this issue.

**Comment by phofl** [comment]
This is consistent with groupby, 

```
df = pd.DataFrame({"a": [1, 1, 1, 2, 2, 2], "b": [1, 2, np.nan, 3, 4, np.nan]})

print(df.groupby("a").last())
```

The parameter ``min_count`` indicates for me, that this is the expected behavior
