### ISSUE TITLE
BUG: pands.to_excel doesn't write all dataframe if worksheet had data 

### ISSUE THREAD

**Issue by rubengr** [pandas-dev/pandas#45659]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import shutil

list = {'Data':['10-20-2022'], 'Week':['Thursday'], 'Schedule':['9:00 - 13:00, 14:00 - 18:00 '], 'Working Time':['8'], 'Hours':['8'], 'Hours to bank':['0']}
df = pd.DataFrame(list)
print(df)
month = 'January'
shutil.copy("Model.xlsx", "Month - " + month + ".xlsx")
writer = pd.ExcelWriter("Month - " + month + ".xlsx", engine='openpyxl')
df.to_excel(writer, sheet_name='Model', startrow=2, index=False, header=False, verbose=True)

writer.save()
writer.close()
```

### Issue Description

[model.xlsx](https://github.com/pandas-dev/pandas/files/7951813/model.xlsx)

Doesn't write dataframe in excel template correctly.

### Expected Behavior

It was expected to write a dataframe in a template sheet

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : c7f7443c1bad8262358114d5e88cd9c8a308e8aa
python           : 3.9.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Portuguese_Portugal.1252
pandas           : 1.3.1
numpy            : 1.21.1
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.3
setuptools       : 57.4.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 2.0.0
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
numba            : None

**Comment by twoertwein** [comment]
Does

```py
with pd.ExcelWriter("file.xlsx", engine='openpyxl', mode="a", if_sheet_exists="overlay") as writer:
    df.to_excel(writer, sheet_name='Model', startrow=2, index=False, header=False)
```

work?

**Comment by phofl** [comment]
The existing sheet is named ``Model Hora`` while you write to the sheet ``Model``. This does what I would expect. Please provide a more specific description, if this is not what you want to do

**Comment by phofl** [comment]
@twoertwein I think this does not work, because he tries to write into a merged cell. without the merged cell this works as expected.

**Comment by rubengr** [comment]
> @twoertwein I think this does not work, because he tries to write into a merged cell. without the merged cell this works as expected.

so it's not possible to use merged cells?

**Comment by twoertwein** [comment]
I'm not familiar with which excel-features pandas supports, but I would recommend using `with pd.ExcelWriter(...)` instead of calling `save`/`close`.
