### ISSUE TITLE
ENH: Styler apply_index should have the ability to pass data context to the user-provided func

### ISSUE THREAD

**Issue by tehunter** [pandas-dev/pandas#45686]
#### Is your feature request related to a problem?

I would like to use `apply_index` to apply styles that are dependent on (a) the data in that column/row, and (b) the other levels of the index. For scenario (a), I would like to set the CSS `text_align` property for a column header based on the type of data in that column. For scenario (b), I have a DataFrame with MultiIndex columns and I would like to set border and alignment properties on all of the column levels excluding the lowest level column. Workarounds are feasible if the DataFrame is known at the time of calling `apply_index`, but no simple solutions exist for creating a generalized style that can be passed through `export` and `use`. This is useful in a context where many DataFrames need to be exported with a consistent data-aware style (i.e. compatible with certain branding/design requirements) but the columns are different for all of them.

#### Describe the solution you'd like

Please see the code below to understand the use case. The key is that the `apply_index` functions should be designed without knowing anything about the dataframe which will be styled. See the alternatives below for how the function calls might be structured.

```
import pandas as pd
import numpy as np

import pandas.io.formats.style
from pandas.api.types import is_numeric_dtype

def auto_align(level, df):
    # Intended use is alignment. Flag with color here for clarity.
    return np.where(df.apply(is_numeric_dtype, axis=0), "color:red", "color:green")

def align_header(level, df):
    if (level.name < df.columns.nlevels-1):
        return ["color: yellow"] * len(level)
    else:
        return [""] * len(level)

my_style = (
    pandas.io.formats.style.Styler(
        pd.DataFrame(),
    )
    .apply_index(auto_align, axis=1) # Arguments or functions would change here
    .apply_index(align_header, axis=1) # Arguments or functions would change here
).export()

df_multi = pd.DataFrame({("A", "1"): [1], ("A", "2"): ["b"], ("B", "1"): [3], ("B", "2"): ["d"]})

df.style.use(my_style)
```

The above should produce the following output

![image](https://user-images.githubusercontent.com/7980666/151627561-b6661ea1-53d3-41dd-8bb3-86e8a00dc41c.png)

#### API breaking implications

Depending on the implementation, it could expose new arguments/argument types without affecting existing behavior (Alternative 1 below). It could expose new methods (Alternative 2)

#### Describe alternatives you've considered

I think the API design is worth some discussion. Two approaches come to mind.

##### Alternative 1

One option is to provide a `data_keyword` through which the DataFrame will be passed, along the lines of `df.pipe` design. The docstring for the `func` keyword is outlined below. The benefit to this approach is it offers the most flexibility to the user. Any information about the data or the index/columns can be found from the dataframe. The downside is confusion since it's not quite equivalent to `df.pipe` in that the `data_keyword` indicated *additional* arguments to pass rather than simply the name of the default argument.

>         `func` should take a Series representing the level and return a string array of the same length. Alternatively a `(callable, data_keyword)` tuple where `data_keyword` is a string indicating the keyword of callable to additionally pass `styler.data`. kwargs are passed into func.

##### Alternative 2

Create a new function that is modeled after the `df.aggregate` function. Upon compute, the styler would pass all of the data column-wise or row-wise to `func` and expect a scalar string returned. It could also be implemented so that the function can return a list of strings in the case of multi-index, one string per level. The naming of this function would be challenging, as `aggregate_index` would not clearly communicate what the function does. Perhaps a `method` argument could be added to `apply_index`, accepting `["apply", "aggregate"]` with default value of `"apply"`.

This would not resolve scenario (b). A solution to that could be to all passing `level="all"` (or some a new argument) to `apply_index` which would trigger calling `data.transform(...)` in the `_apply_index` function. Or the `level` argument could accept a slice (e.g. `pd.IndexSlice[0:-1]`), though this would preclude styling based on the value at multiple levels.

**Comment by attack68** [comment]
OK, so to caveat this response, `apply_index` is a new feature for which it is worth gathering user feedback before moving forward with changes. Additionally what you are describing is really *advanced* usage of the these features so we must be careful not to add esoteric functions that complicate the basic cases.

What is currently possible for the general dynamic application is the following:

```python
def color_except_last_level(styler):
    return styler.applymap_index(
        lambda v: "color: blue;", 
        level=[i for i in range(styler.columns.nlevels-1)],
        axis=1
    )

def align_header(styler):
    from pandas.api.types import is_numeric_dtype
    def auto_align(s):
        return np.where(styler.data.apply(is_numeric_dtype, axis=0), "color:red", "color:green")
    return styler.apply_index(auto_align, axis=1, level=styler.columns.nlevels-1)

def my_styles(styler):
    styler.pipe(color_except_last_level)
    styler.pipe(align_header)
    return styler
```

Now we attach this to a generic styled dataframe:

```python
df_multi = pd.DataFrame({
    ("A", "1", "1"): [1], 
    ("A", "2", "1"): ["b"], 
    ("B", "1", "2"): [3], 
    ("B", "2", "2"): ["d"]
})
df_multi.style.pipe(my_styles)
```

![Screen Shot 2022-01-29 at 11 11 30](https://user-images.githubusercontent.com/24256554/151656976-bfa239b4-f901-4894-b3e2-8d885a16cfe2.png)

This can be combined, of course, with use of `use` and `export` and whilst it might not be ideal that everything cannot be done in the same syntax at least the dynamism is there as a feature.

**Comment by tehunter** [comment]
Ah, that's a clever solution. I hadn't thought to use `pipe` in that way.
