### ISSUE TITLE
ENH: Series.get to return series for iterable of indices when indices are missing instead of default scalar value.

### ISSUE THREAD

**Issue by ProgrammingDao** [pandas-dev/pandas#45697]
#### Problem

a = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])

a.get(['a', 'c']) => pd.Series([1, 3], index=['a', 'c'])

a.get(['a', 'c', 'e']) => None

#### Describe the solution you'd like

I would prefer the following: a.get(['a', 'c', 'e']) => pd.Series([1, 3, np.Nan], index=['a', 'c', 'e'])

It is possible by checking in advance which indices are available in the series to extract the values from and combine a series with missing indices + default value and a series with present indices + extracted values.

#### API breaking implications

Unknown

### Note

Happy to add tests for this issue and a potential solution if issue is acknowledged.

**Comment by jreback** [comment]
-1 on any expansion of .get which is very well defined

you can use .loc to do this not generally

**Comment by ProgrammingDao** [comment]
Thank you for your feedback @jreback. Happy to close the issue in this case.

**Comment by ProgrammingDao** [comment]
It seems that pandas.Series.reindex(indices).fillna(default_value) is equivalent so closing now.
