### ISSUE TITLE
ENH: `transform` method for RollingGroupby object

### ISSUE THREAD

**Issue by shoyip** [pandas-dev/pandas#45713]
#### Is your feature request related to a problem?

**Yes.** I am trying to do a rolling average over time (with a specific time interval), and then get a pandas Series with the aggregate results repeated over rows with the same grouping.

#### Describe the solution you'd like

I would like to possibly have a `transform` method for the `RollingGroupby` object, in the same way it is implemented in `pandas.core.groupby.DataFrameGroupBy`.

#### API breaking implications

This feature will imply just the creation of a new method for the `RollingGroupby` object, without any side effect.

#### Additional context

Currently I get this error:

```python
~/.../lib/python3.9/site-packages/pandas/core/window/rolling.py in __getattr__(self, attr)
    271             return self[attr]
    272 
--> 273         raise AttributeError(
    274             f"'{type(self).__name__}' object has no attribute '{attr}'"
    275         )

AttributeError: 'RollingGroupby' object has no attribute 'transform'
```

**Comment by jreback** [comment]
these object by definition are transforms already

**Comment by shoyip** [comment]
@jreback I don't know if I've been misunderstood, please tell me if it is so.

What I am asking if it's already implemented is the [pandas.core.groupby.DataFrameGroupBy.transform](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.transform.html) method for `RollingGroupby` objects, so a method that enables me to Split, Apply, Combine and then reassign the aggregate values to the original dataframe, repeated for each occurence of elements relative to each group of the groupby operation.

I would like to ask you if, at least, is there any way to borrow the method from [pandas.core.groupby.DataFrameGroupBy.transform](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.transform.html) to [RollingGroupby](https://github.com/pandas-dev/pandas/blob/main/pandas/core/window/rolling.py#L2593), since their implementation is very similar.
