### ISSUE TITLE
BUG: IntervalIndex._can_hold_na wrong for integer-backed

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#45720]
If we patch it to be correct, we get errors in IntervalArray._cmp_method when trying to do `other.categories.take`

**Comment by Kyrpel** [comment]
can you post an example so I can reproduce the bug?

**Comment by jbrockmendel** [comment]
```
ii = pd.period_range(1, 2)
>>> ii._can_hold_na
True
```
