### ISSUE TITLE
DOC: Addition of plt.show() in the "How to create plots in pandas?" section of the Getting started tutorials

### ISSUE THREAD

**Issue by BadLoaf** [pandas-dev/pandas#45772]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

[https://pandas.pydata.org/docs/dev/getting_started/intro_tutorials/04_plotting.html#min-tut-04-plotting](url)

### Documentation problem

In all the code blurbs, the 6 plot outputs are shown without the required input of 

> plt.show()

For example, in the "I want a quick visual check of the data." section:

> In[5]:air_quality.plot()
> Out[5]: <AxesSubplot:xlabel='datetime'>

This may cause some confusion for people reading the docs who are not familiar with the matplotlib.pyplot module. 

### Suggested fix for documentation

The line of code:

`in[n]: plt.show()`                           (where n is the required line number of the code)

can be added before each of the graphs to show the required command to display the graph. 
This will allow the readers of the documentation to learn how to display the required graph on the screen.

**Comment by mroeschke** [comment]
For `plt.show()` to be added, the restructured text will probably need these directives added to show correctly https://stackoverflow.com/a/60870687

**Comment by ehallam** [comment]
take
