### ISSUE TITLE
BUG: pendulum.duration subtracts an extra day from pandas.Timestamp

### ISSUE THREAD

**Issue by Pelleaon** [pandas-dev/pandas#45799]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import pendulum

x = pd.Timestamp("2022-02-03 11:10:05.400")
x-pendulum.duration(milliseconds=200)
```

### Issue Description

When pendulum.duration() is less than 1 day, subtracting it from a pd.Timestamp subtracts the requested value + an extra day.

### Expected Behavior

In the example given above, the expected output is `Timestamp('2022-02-03 11:10:05.200000')`, instead the actual output is `Timestamp('2022-02-02 11:10:05.200000')`. At the very least this should throw a warning/error if pendulum.duration() is not supposed to be compatible with a pd.Timestamp, rather than simply giving the wrong result. Interestingly, addition works fine, as does subtracting a duration greater than 1 day.
`

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.9.7.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19043
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1250

pandas           : 1.4.0
numpy            : 1.19.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.1.0
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.2
IPython          : 7.28.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

**Comment by jreback** [comment]
likely this is on the pendulum side 

we don't have explicit support here

**Comment by mroeschke** [comment]
Agreed, it doesn't scale well for pandas to check for all 3rd party timedelta implementations. pandas only guarantees compatibility with against `pd.Timedelta` and `datetime.timedelta`. I would suggest raising this on the pendulum side.
