### ISSUE TITLE
BUG: infer_dtype fails on PeriodIndex

### ISSUE THREAD

**Issue by jmg-duarte** [pandas-dev/pandas#45825]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame({'a': [1]})
df.index = pd.PeriodIndex(['2013-05-02'], freq='D')
pd.api.types.infer_dtype(df.index)
```

### Issue Description

`infer_dtype` throws `ValueError: cannot infer type for <class 'NoneType'>` for `PeriodIndex`

### Expected Behavior

That it is able to infer the index dtype

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 7c48ff4409c622c582c56a5702373f726de08e96
python           : 3.8.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.2.5
numpy            : 1.18.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 60.3.1
Cython           : 0.29.27
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.0.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : 1.4.31
tables           : None
tabulate         : None
xarray           : 0.21.1
xlrd             : None
xlwt             : None
numba            : 0.49.1

</details>

**Comment by jbrockmendel** [comment]
On main I get a ValueError on the `df = pd.DataFrame({'a': 1})` line.  If I change that to use pd.Series, the infer_dtype call works as expected.

**Comment by jmg-duarte** [comment]
Oh, my bad, it should be [1]

A sexta, 4 de fev de 2022, 19:43, jbrockmendel ***@***.***>
escreveu:

**Comment by mroeschke** [comment]
Could you try on a more recent version of pandas? On main I get

```
In [1]: import pandas as pd
   ...: df = pd.DataFrame({'a': [1]})
   ...: df.index = pd.PeriodIndex(['2013-05-02'], freq='D')
   ...: pd.api.types.infer_dtype(df.index)
Out[1]: 'period'
```

**Comment by jmg-duarte** [comment]
I realize now that the version I reported was old indeed. The error happened to one of our devs but 1.4.0 seems to work indeed. Closing now.
