### ISSUE TITLE
fillna(value=[partial-multi-index]) raises "A value is trying to be set on a copy of a slice from a DataFrame" warning

### ISSUE THREAD

**Issue by Ponteaus** [pandas-dev/pandas#45821]
```
from pandas import DataFrame
df = DataFrame({'a':[1,2,3],'b':[1,2,3],'c':[1,2,3]})
piv = df.pivot(columns='a',values=['b','c'])
piv.fillna(value={'b':0,'c':100})
```

This code produces the expected result, where all columns under the 'b' index are filled with 0s and all columns under the 'c' index are filled with 100s, but it unexpectedly raises a "/lib/python3.9/site-packages/pandas/core/frame.py:5176: SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame" warning.

This warning is NOT raised if I fully specify the column index:

```
from pandas import DataFrame
df = DataFrame({'a':[1,2,3],'b':[1,2,3],'c':[1,2,3]})
piv = df.pivot(columns='a',values=['b','c'])
piv.fillna(value={('b',1):0,('b',2):0,('b',3):0,('c',1):100,('c',2):100,('c',3):100})
```

But this is too verbose. The first code segment is preferred

**Comment by phofl** [comment]
Which Version of pandas are you using? Please Show your versions with pd.show_versions()

also please create your df without pivot

**Comment by phofl** [comment]
Duplicate of #43476

**Comment by Ponteaus** [comment]
pandas version = 1.3.4

```
from pandas import DataFrame
from numpy import NaN
df = DataFrame({('b',1):[1,NaN], ('b',2):[NaN, 2], ('c',1):[1,NaN], ('c',2):[NaN, 2]})
df.fillna(value={'b':0,'c':100})
```
