### ISSUE TITLE
ENH: support column oriented table output. + schema

### ISSUE THREAD

**Issue by yairlenga** [pandas-dev/pandas#45835]
#### Is your feature request related to a problem?

I would like to send schema (table layout) and send data in column oriented format) to be consumed by read_json (from a web service/file).

[this should provide a description of what the problem is, e.g. "I wish I could use pandas to do [...]"]

I am generating a wide/large data set (>200 columns, 2000k+ rows) for processing. Given complexity of columns,  important to include schema with data, otherwise lot of opportunities for mis interpreting data by casting. 

With the current data delivery format, json data size is big, even with compression. I noticed much better compression (gzip) if data is sent column wise (same reason that column based storage faster then row base storage). I believe column based storage will also speed up loading, as panda is column oriented,

I would like to see support for sending schema data, and separate control for the data format - should be possible to choose any data layout to be included with the schema.

currently the table layout imply very verbose format for data.

#### Describe the solution you'd like

Ideally, new withSchema Boolean parameter will be added to the call. If set, the result will include a dataLayout attribute, telling the reader how to bring in the data into the data frame. It should support all layout options (or at least the column based output)

#### API breaking implications

Change is backward compatible.

#### Describe alternatives you've considered

In theory, two separate calls - one from schema and one for data can do the trick,but very cumbersome/inefficient. Another option is for the layout param to be extended to include combinations like “schema+column”, but this is very error prone - hard to expand.

#### Additional context

[add any other context, code examples, or references to existing implementations about the feature request here]

```python
# Your code here, if applicable

```

**Comment by mroeschke** [comment]
I think you'd want https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.io.json.build_table_schema.html?

**Comment by mroeschke** [comment]
Thanks for the request, but since there is potentially an existing function that fits this request, closing. Otherwise, the triage team would need a tighter scoped enhancement proposal
