### ISSUE TITLE
BUG: ModuleNotFoundError: No module named 'pandas' (Problem with Python3.9)

### ISSUE THREAD

**Issue by Nafees-060** [pandas-dev/pandas#45833]
Initially, I ran experiments on python3, which supports Pandas perfectly. Since our lab recently upgraded the server to an **RTX 3000 series GPU**, **it supports Python 3.9**, not previous versions. For that, when I ran the tests in python3.9 (python3.9 code file.py), the following error occurred:
`ModuleNotFoundError: No module named 'pandas'`

Then I ran 'pip install pandas' and found that the requirements had already been met; here's further information:

    Defaulting to user installation because normal site-packages is not writeable
    Requirement already satisfied: pandas in ./.local/lib/python3.6/site-packages (1.1.5)
    Requirement already satisfied: pytz>=2017.2 in ./.local/lib/python3.6/site-packages (from pandas) (2021.1)
    Requirement already satisfied: python-dateutil>=2.7.3 in ./.local/lib/python3.6/site-packages (from pandas) (2.8.2)
    Requirement already satisfied: numpy>=1.15.4 in ./.local/lib/python3.6/site-packages (from pandas) (1.19.5)
    Requirement already satisfied: six>=1.5 in ./.local/lib/python3.6/site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

But when I ran the file again, I received the same issue: `ModuleNotFoundError: No module named 'pandas'`

How can we install solve this issue?

**Comment by twoertwein** [comment]
You are using pip with python 3.6:

> Requirement already satisfied: pandas in ./.local/lib/**python3.6**/site-packages (1.1.5)

You probably want to use: `python3.9 -m pip install pandas`

**Comment by MarcoGorelli** [comment]
agreed - closing as it looks like that's the issue (rather than anything in pandas)
