### ISSUE TITLE
BUG: Dataframe from CSV convert to numpy produce weird behavior in np.frompyfunc

### ISSUE THREAD

**Issue by Howard-O-Neil** [pandas-dev/pandas#45846]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import numpy as np
import pandas as pd


def add(x, y):
    # Print pair value
    print(f"{x} --- {y}")
    return x + y

custom_add = np.frompyfunc(add, 2, 1)

# This one is normal

a = np.array(
    [
        [1, 1, 1, 1],
        [2, 2, 2, 2],
    ]
)

b = np.array(
    [
        [4, 4, 4, 4],
        [5, 5, 5, 5],
    ]
)

print(custom_add(a, b))

# === OUTPUT ===
# 1 --- 4
# 1 --- 4
# 1 --- 4
# 1 --- 4
# 2 --- 5
# 2 --- 5
# 2 --- 5
# 2 --- 5

# [[5 5 5 5]
#  [7 7 7 7]]


pd.DataFrame(a).to_csv("test/a.csv")
pd.DataFrame(b).to_csv("test/b.csv")

# This one has weird behavior

a = pd.read_csv("test/a.csv").to_numpy()[:, 1:]
b = pd.read_csv("test/b.csv").to_numpy()[:, 1:]

print(custom_add(a, b))

# === OUTPUT ===
# 1 --- 4
# 2 --- 5
# 1 --- 4
# 2 --- 5
# 1 --- 4
# 2 --- 5
# 1 --- 4
# 2 --- 5
# [[5 5 5 5]
#  [7 7 7 7]]
```

### Issue Description

Normal numpy array pass pair values into `np.frompyfunc` in **column wise** manner
However with the same input value (construct pandas dataframe from csv then convert to numpy) give different behavior, pair values passed into `np.frompyfunc` in **row wise** manner.

This behavior happen only when data frame is constructed from csv, data frame from numpy perform properly (column wise)
```
# This will perform properly

a = pd.DataFrame(a).to_numpy()
b = pd.DataFrame(b).to_numpy()
```

### Expected Behavior

Value passed into `np.frompyfunc` must be in **column wise** manner.

Although the 2 results from reproducible example is the same, but in some specific use case like calculating IoU. Row wise pair values will product fault result

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.9.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.68-1-MANJARO
Version          : #1 SMP PREEMPT Wed Sep 22 12:29:47 UTC 2021
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.0
numpy            : 1.22.1
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.3
setuptools       : 57.4.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : None
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by jreback** [comment]
pls narrow this down - it is not clear whether you think this is a bug in read csv, writing csv, or to_numpy

**Comment by Howard-O-Neil** [comment]
The bug in read csv i think

**Comment by jreback** [comment]
then show the structure and the actual error

**Comment by Howard-O-Neil** [comment]
There's no actual error, it's like what i have described in "Reproducible Example"

When input read from csv, the behavior of `np.frompyfunc` is different than that input but from normal dataframe.

**Comment by phofl** [comment]
I think this is related to the layout of the underlying objects, e.g. the numpy arrays. In your case every row in your array corresponds with a row in the DataFrame. 

In the csv case we use one numpy array per columns, e.g. the numpy arrays representing different columns are not related. It is basically equivalent to the following construction of a DataFrame

```
a = pd.DataFrame({0: np.array([1, 2]), 1: np.array([1, 2]), 2: np.array([1, 2]), 3: np.array([1, 2])}).to_numpy()
```

This also produces the result from the csv case. Not sure what we can do here

**Comment by Howard-O-Neil** [comment]
I searched this on gg but have no luck. Really this issue is really weird, i mange to fix it by convert the dataframe (from csv) to python list, then from list to numpy.

**Comment by phofl** [comment]
A bit clearer: The csv case is equivalent to the following:

```
a1 = np.array([[1, 2], [1, 2], [1, 2], [1, 2]]).T
b1 = np.array([[4, 5], [4, 5], [4, 5], [4, 5]]).T
custom_add(a1, b1)
```

**Comment by Howard-O-Neil** [comment]
I tried to reproduced the issue by concatenate multiple column np array

```
a = np.array([])
for i in range(4):
    u = np.array([1, 2])

    if a.shape[0] <= 0:
        a = np.expand_dims(u, 1)
    else: a = np.concatenate(
        (a, np.expand_dims(u, 1)), 1
    )

b = np.array([])
for i in range(4):
    u = np.array([4, 5])

    if b.shape[0] <= 0:
        b = np.expand_dims(u, 1)
    else: b = np.concatenate(
        (b, np.expand_dims(u, 1)), 1
    )

print(custom_add(a, b))

# === OUTPUT ===
# 1 --- 4
# 1 --- 4
# 1 --- 4
# 1 --- 4
# 2 --- 5
# 2 --- 5
# 2 --- 5
# 2 --- 5
# [[5 5 5 5]
#  [7 7 7 7]]
```
I don't know if this code make sense but it produce proper results (column wise)

**Comment by Howard-O-Neil** [comment]
> A bit clearer: The csv case is equivalent to the following:
> 
> ```
> a1 = np.array([[1, 2], [1, 2], [1, 2], [1, 2]]).T
> b1 = np.array([[4, 5], [4, 5], [4, 5], [4, 5]]).T
> custom_add(a1, b1)
> ```

Oh wow, didn't event think about this. So the problem is cause by transposing a matrix

**Comment by phofl** [comment]
No, not really. In the csv case every column is a single np.array, while your method of creating a DataFrame pases an array, where one row from the array is a row from the DataFrame. These are just different methods of creating the DataFrame with a different memory layout.

**Comment by Howard-O-Neil** [comment]
Hmmm, i has nothing to do with dataframe anymore

This code is pure numpy and it reproduced the issue
```
a = np.array([])
for i in range(4):
    u = np.array([1, 2])

    if a.shape[0] <= 0:
        a = np.expand_dims(u, 1)
    else: a = np.concatenate(
        (a, np.expand_dims(u, 1)), 1
    )

b = np.array([])
for i in range(4):
    u = np.array([4, 5])

    if b.shape[0] <= 0:
        b = np.expand_dims(u, 1)
    else: b = np.concatenate(
        (b, np.expand_dims(u, 1)), 1
    )

print(custom_add(a, b))
# 1 --- 4
# 1 --- 4
# 1 --- 4
# 1 --- 4
# 2 --- 5
# 2 --- 5
# 2 --- 5
# 2 --- 5
# [[5 5 5 5]
#  [7 7 7 7]]

a = np.array([[1, 2], [1, 2], [1, 2], [1, 2]]).T
b = np.array([[4, 5], [4, 5], [4, 5], [4, 5]]).T


print(custom_add(a, b))
# 1 --- 4
# 2 --- 5
# 1 --- 4
# 2 --- 5
# 1 --- 4
# 2 --- 5
# 1 --- 4
# 2 --- 5
# [[5 5 5 5]
#  [7 7 7 7]]
```

Do you think this is an issue on numpy? Since there's kinda lack of documentation about `np.frompyfunc` usage

**Comment by phofl** [comment]
Have not used this function myself, so can not help you there. I think this might be intended, but not sure. I will close here, since this is not  related to pandas itself
