### ISSUE TITLE
BUG: comment option in read_excel() returns NaNs unlike in read_csv()

### ISSUE THREAD

**Issue by DonteRW** [pandas-dev/pandas#45847]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
My data is like this:

Layer	LyrLBounds_m	dz_m	para1	dtheta_dpsi
1	0.05	0.01	1.43	0.13
2	0.1	0.01	1.65	0.1
3	0.2	0.01	0.98	0.09
#layer - declares the number of layers 				
#LyrLBounds_m - is the lower bound or interface of the layer				
#dz_m - dz of each layer to be defined in layer i				

I have saved the data in a .xlsx and .csv file called 'model_parameters'

import pandas as pd

Reading the csv file with pd.read_csv():

df_csv = pd.read_csv( 'model_parameters.csv', comment='#' )
df_csv
Layer	LyrLBounds_m	dz_m	para1	dtheta_dpsi
0	1	0.05	0.01	1.43	0.13
1	2	0.10	0.01	1.65	0.10
2	3	0.20	0.01	0.98	0.09


Reading the data with pd.read_excel()

df_xl = pd.read_excel( 'model_parameters.xlsx', sheet_name="GRID", comment='#' )
df_xl
Layer	LyrLBounds_m	dz_m	para1	dtheta_dpsi
0	1.0	0.05	0.01	1.43	0.13
1	2.0	0.10	0.01	1.65	0.10
2	3.0	0.20	0.01	0.98	0.09
3	NaN	NaN	NaN	NaN	NaN
4	NaN	NaN	NaN	NaN	NaN
5	NaN	NaN	NaN	NaN	NaN
```

### Issue Description

When I use the comment option in read_excel(), the lines with the comments are returned or read as lines with NaNs.  I expected that the comments will not  result in NaNs in the dataframe just like what  read_csv() does

One could opt for using CSV files, but if you have multiple inputs in different excel file sheets then you will have to create and read multiple csv files, which is not ideal. I would like to take advantage of the excel file sheets and keep all the data to be read in one file.  So it will be great if NaNs were not returned.

### Expected Behavior

I expect the output as read_csv()

df_xl = pd.read_excel( 'model_parameters.xlsx', sheet_name="GRID", comment='#' )
df_xl

Layer	LyrLBounds_m	dz_m	para1	dtheta_dpsi
0	  1	 0.05	    0.01	   1.43	   0.13
1	 2	 0.10	    0.01	   1.65	   0.10
2 	 3	 0.20	   0.01	   0.98	   0.09

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d
python           : 3.8.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252

pandas           : 1.3.5
numpy            : 1.20.1
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.0.3
setuptools       : 59.8.0
Cython           : 0.29.27
pytest           : 7.0.0
hypothesis       : None
sphinx           : 4.4.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.2
lxml.etree       : 4.7.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.0.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fsspec           : 2022.01.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.5.1
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
sqlalchemy       : 1.4.31
tables           : 3.6.1
tabulate         : None
xarray           : 0.19.0
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.55.1

</details>

**Comment by phofl** [comment]
Please provide a reproducible example that is copy and pasteable. Please See https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports for a Description. 

You can also check other csv issues if you need an example

**Comment by phofl** [comment]
Closing. Please ping to reopen if you can provide a reproducible example

**Comment by sbwiecko** [comment]
I have the same issue with the `comment` argument, while trying to import a sheet from an Excel file that contains some comment rows starting with a `#` character.

**Comment by phofl** [comment]
Could you provide a minimal and reproducible example?

**Comment by sbwiecko** [comment]
The thing is that happens with external .xlsx files. For example if you enter this in Excel:
```
group	animal	A
jq1	40	2440
jq1	40	2440
jq1	40	2440
# body weight in grams		
# time in days			
```	
and save the file as `example.xlsx`, the following code:
```
import pandas as pd
data = pd.read_excel(
    "./example.xlsx",
    comment='#', # doesn't work for unknown reasons
    )
print(data)
```
generates the following result:
```
  group  animal       A
0   jq1    40.0  2440.0
1   jq1    40.0  2440.0
2   jq1    40.0  2440.0
3  None     NaN     NaN
4  None     NaN     NaN
```

Interestingly, if we use a single row of data like in Excel as follows:
```
group	animal	A
jq1	40	2440
# body weight in grams		
# time in days		
```
the same code will return the expected result:
```
  group  animal     A
0   jq1      40  2440
```

I know it's not pastable and reproducible, but I cannot generate a code in python that create the exact same Excel file as in these examples. Thank you for your support and understanding!
