### ISSUE TITLE
CI: Doc build is failing because scipy inventories can not be reached.

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#45850]
Looks to be an issue on the scipy side. https://docs.scipy.org/doc/scipy/reference/ returns a 404 instead of the 1.8.0 docs. opened https://github.com/scipy/scipy/issues/15540

https://github.com/scipy/scipy/issues/14267

**Comment by jbrockmendel** [comment]
i didnt follow the full discussion on the scipy tracker.  is this something we expect to fix itself or do we need to e.g. pin something?

**Comment by phofl** [comment]
Ths should fix itself eventually. Opened a pr to pin to 1.7.1 until it is fixed

**Comment by simonjayhawkins** [comment]
closed by #45878
