### ISSUE TITLE
BUG: Partial bug with resample() function

### ISSUE THREAD

**Issue by jiahe224** [pandas-dev/pandas#45869]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example
https://github.com/jiahe224/bug_report/blob/main/resample_test.csv
```python
import pandas as pd
temp = pd.read_csv('resample_test.csv',dtype={'stockcode':str, 'A股代码':str})
temp['date'] = pd.to_datetime(temp['date'])
temp = temp.set_index(['date'])
result = temp['北向占自由流通比'].resample('Q',closed='left').first()
result
```

### Issue Description

![1644292948(1)](https://user-images.githubusercontent.com/35186992/152917240-1e19bb2a-8ca8-481e-86bf-626f2127ea49.jpg)

As we can see from the graph, the output of the third quarter is not as expected, theoretically it should output the value of 2020-06-29, but the actual output is the value of 2020-07-02. The same problem exists in last() when the value of the closed parameter is left, only the quarter of the error is different.

### Expected Behavior

The first value of each quarter should be the end of the previous quarter

### Installed Versions

<details>
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Simplified)_China.936

pandas           : 1.4.0
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fastparquet      : None
fsspec           : 0.8.3
gcsfs            : None
matplotlib       : 3.3.2
numba            : 0.51.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : 1.3.20
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
zstandard        : None

</details>

**Comment by Liam3851** [comment]
From pandas' perspective with closed='left' the boundary of the second and third quarter would be 2020-06-30, not 2020-06-29 (with closed='right', the boundary would be 2020-07-01). 2020-06-29 will always map to the 2nd quarter regardless of whether closed='left' or closed='right'. I'm not sure why your dataset is missing 2020-06-30, but that seems to be your problem.

**Comment by jiahe224** [comment]
I'm very sorry, I still don't understand, I would like to ask a design question first, what will pandas do if there is no data in the dataset with the corresponding date? From this example, since 2019-12-31 and 2020-06-30 are missing, pandas seems to ignore the closed value and use the earliest day of the current quarter in the available data, i.e. 2020-01-02 and 2020-07-02. The problem about the missing data is that there is no stock trading on the missing day. I would like pandas to handle it this way, i.e. if there is no corresponding date, find the closest date, e.g. if there is no 2020-06-30, find 2020-06-29.

Translated with www.DeepL.com/Translator (free version)

**Comment by jiahe224** [comment]
I'm very sorry, I still don't understand, I would like to ask a design question first, what will pandas do if there is no data in the dataset with the corresponding date? From this example, since 2019-12-31 and 2020-06-30 are missing, pandas seems to ignore the closed value and use the earliest day of the current quarter in the available data, i.e. 2020-01-02 and 2020-07-02. The problem about the missing data is that there is no stock trading on the missing day. I would like pandas to handle it this way, i.e. if there is no corresponding date, find the closest date, e.g. if there is no 2020-06-30, find 2020-06-29. @Liam3851 @mroeschke
