### ISSUE TITLE
ENH: Easily calculate percentages of your df or of groups (i.e. normalize)

### ISSUE THREAD

**Issue by SandervandenOord** [pandas-dev/pandas#45898]
**Calculating percentages (or normalizing as it is called in pandas) should be made easier.**

When aggregating and analyzing data it is very common that you want to see the percentages instead of counts.

Currently you can do this with `.value_counts(normalize=True)` and `pd.crosstab(normalize='index')`.  

In all other cases it will require you (multiple) lines of custom code, stackoverflow is filled with examples:
[https://stackoverflow.com/questions/31481803/compute-percentage-for-each-row-in-pandas-dataframe](https://stackoverflow.com/questions/31481803/compute-percentage-for-each-row-in-pandas-dataframe)
[https://stackoverflow.com/questions/36987829/how-to-use-groupby-in-pandas-to-calculate-a-percentage-proportion-total-based](https://stackoverflow.com/questions/36987829/how-to-use-groupby-in-pandas-to-calculate-a-percentage-proportion-total-based)
[https://stackoverflow.com/questions/23377108/pandas-percentage-of-total-with-groupby](https://stackoverflow.com/questions/23377108/pandas-percentage-of-total-with-groupby)

I looked in the source code how this was implemented for pd.crosstab():

``` python
# Actual Normalizations
normalizers: dict[bool | str, Callable] = {
    "all": lambda x: x / x.sum(axis=1).sum(axis=0),
    "columns": lambda x: x / x.sum(),
    "index": lambda x: x.div(x.sum(axis=1), axis=0),
}

normalizers[True] = normalizers["all"]

try:
    f = normalizers[normalize]
except KeyError as err:
    raise ValueError("Not a valid normalize argument") from err

table = f(table)
table = table.fillna(0)
```

It would be great if there would be a method `.percentage()` or `.normalize()` that you call on a dataframe or grouped dataframe that does this for you.  
Or something like `.count(normalize=True)` or `.size(normalize=True)`.

Just a simple, unified way of getting percentages/proportions.

Maybe the normalizing options should be something like:  
`all, index, columns, group_all, group_index, group_columns`

**Comment by mroeschke** [comment]
pandas already has a large API so I would be -1 to add another method especially if existing methods can be used to achieve the same result.

**Comment by SandervandenOord** [comment]
As said, I think getting (relative) percentages is such a key factor in data analysis, just like means, counts, etc.
It is a very basic need.
I think it's underestimated and yet one mostly needs custom code to get them out of your data.

To get percentages depending on your data when using pandas you need to know 5 different ways of getting them out of your data. That hurdles speed in analysis. Data analysis should be at the speed of thought.

A once and for all .percentage() method would be superb.

(No one would argue about this if it would be about .count(). Yet there is no good .relative_count() in pandas)

**Comment by SandervandenOord** [comment]
To add, this is an example of the groupby options in Excel. 

(I don't know if I'm allowed to use the word Excel here, but hey it's an illustration)
(and, well technically it's a pivot table in Excel, but I set it up that it is equal to a groupby in pandas)

As you can see, there are % options for grand total, for rows, for columns, and for a level.

<img width="581" alt="image" src="https://user-images.githubusercontent.com/7305600/153560237-e843bc2f-06fc-4937-a12e-ba520dbb36db.png">

**Comment by jreback** [comment]
what does group_all mean ?

**Comment by SandervandenOord** [comment]
> what does group_all mean ?

Something like take all cells in a group and calculate the percentage of current cell over all cells in that group. 
(As compared to over the whole dataframe)
But this was more of a brainstorm naming in my example. 

The main point is that calculating percentages should be easier.

Here's also examples how it's done in Tableau:
https://help.tableau.com/current/pro/desktop/en-us/calculations_percentages_options.htm

**Comment by attack68** [comment]
the stackoverflow answer you provided gives a one-line method of doing exactly this.
https://stackoverflow.com/questions/36987829/how-to-use-groupby-in-pandas-to-calculate-a-percentage-proportion-total-based

This what the `groupby` `transform` and `apply` methods are all designed to do, in a general sense.

```python
df = pd.DataFrame({
    "yr": [2021,2021,2021,2022,2022,2022], 
    "month": [1,2,3,1,2,3],
    "val": [23, None, 30, 50, 25, 75]
}).set_index(["yr", "month"])

df["percent"] = df.groupby(level=[0]).apply(lambda s: s/s.sum())
df
```
![Screen Shot 2022-02-11 at 19 45 09](https://user-images.githubusercontent.com/24256554/153651124-b795bfd3-7941-4119-9bed-ad6b120064fe.png)

Personally, I think adding individual methods rather than informing users effectively how to use the generic tools has negative long terms impact.

**Comment by SandervandenOord** [comment]
Yes, there are alternatives, but they are hard to remember. 
You need a normal `.groupby()` and then for the percentages a rather advanced and difficult `.groupby(level=[0]).apply(lambda etc.)`
For a common need, there should be an easy solution.

**Comment by SandervandenOord** [comment]
To add still an argument, this question is in the top 100 of most bookmarked questions on stackoverflow.  
I find bookmarking a clear cue for users not being able to remember how to do something: 

[https://stackoverflow.com/questions/36987829/how-to-use-groupby-in-pandas-to-calculate-a-percentage-proportion-total-based](https://stackoverflow.com/questions/36987829/how-to-use-groupby-in-pandas-to-calculate-a-percentage-proportion-total-based)

You can check this by running the query here:
[https://data.stackexchange.com/stackoverflow/query/1555517](https://data.stackexchange.com/stackoverflow/query/1555517)

**Comment by jreback** [comment]
yeah this is very straightforward 

would take a doc recipe / example somewhere but -1 on adding more api

api surface area is directly related to usability -
we are already the at limit of good api (well over the limit really) so new methods would have to have massive support

don't see it here

**Comment by mroeschke** [comment]
Thanks for the request, but it appears this proposal doesn't have a lot of support from the pandas team so closing given that existing APIs can be composed to emulate the desired functionality
