### ISSUE TITLE
BUG: pandas.tseries.offsets.DateOffset behavior changes

### ISSUE THREAD

**Issue by iajoiner** [pandas-dev/pandas#45890]
### Pandas version checks

- [ ] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

s = pd.Series(pd.to_datetime('2022-02-04'))
s = s + pd.DateOffset(1)
print(s)
```

### Issue Description

This code snippet produces a series with a date. In Pandas 1.3.5 the date is 2022-02-05. On the other hand in Pandas 1.4.0 the date is abruptly changed to 2022-02-04 which means a API breaking change which is against the Pandas version policy has happened.

### Expected Behavior

This code snippet should produce a series with the date is 2022-02-05.

### Installed Versions

<details>

1.4.0

</details>

**Comment by iajoiner** [comment]
I'm basically reopening https://github.com/pandas-dev/pandas/issues/45643. As an open source developer who does have a PR here I think this issue needs to be addressed one way or another.

**Comment by simonjayhawkins** [comment]
first bad commit: [cd5a12417a6a1ee221fd915db1b499384c292de9] FIX BUG: Timestamp __add__/__sub__ DateOffset with nanoseconds lost. (#43968)
