### ISSUE TITLE
DOC: Unclear documentation for Period Construction

### ISSUE THREAD

**Issue by cancan101** [pandas-dev/pandas#4591]
The documentation is unclear as to what the date passed to a `Period` means: whether it is the start date or the end date of the period. Convention is that fiscal quarters are usually stated by the date the quarter ends, whereas weeks are many times stated by the day week starts. This is especially unclear given that the default `freq='W'` is `W-SUN` which means the "week ending on Sunday" whereas one convention is to show weeks starting on Sunday. 

I would recommend clearing this up in the documentation.

**Comment by MatthijsReyers** [comment]
Hi, I would like to have a go at solving this.

**Comment by sunaymehta** [comment]
Hey! Can I solve this?

**Comment by MomIsBestFriend** [comment]
@sunaymehta Sure we would love to accept a PR!

---

The location of the ```Period``` documentation is at https://github.com/pandas-dev/pandas/blob/eab7226549c21a724fa6afce21d2e585b6a84eb6/pandas/_libs/tslibs/period.pyx#L2375

ATM what is missing is some examples on how to construct a period.

**Comment by soumya17052002** [comment]
Hey since the Issue is still open. I am currently looking into it.

**Comment by soumya17052002** [comment]
From your reference, I guess you want to keep some examples of how to construct a Period, here-
<img width="494" alt="Screenshot 2021-01-18 at 10 22 02 PM" src="https://user-images.githubusercontent.com/56285471/104943329-99531180-59db-11eb-9d09-ca0e3c2949a1.png">

**Comment by Nishita5421** [comment]
Is this still open? Can I take this?

**Comment by MarcoGorelli** [comment]
Pull requests are welcome

**Comment by athielem** [comment]
Hey, would be interested to work on this as a good first issue!

**Comment by jackgoldsmith4** [comment]
take
