### ISSUE TITLE
BUG: Outputs Series.values.codes and print(Series.values.codes) are different

### ISSUE THREAD

**Issue by YarShev** [pandas-dev/pandas#45916]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
>>> import pandas
>>> series = pandas.Series(["a", "b", "c", "a"], dtype="category")
>>> series.values.codes
>>> array([0, 1, 2, 0], dtype=int8)
>>> print(series.values.codes)
>>> [0 1 2 0]
```

### Issue Description

Outputs Series.values.codes and print(Series.values.codes) are different.

### Expected Behavior

Should be equal.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.8.12.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.4.0
numpy            : 1.21.4
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 60.6.0
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : 4.3.1
blosc            : None
feather          : 0.4.1
xlsxwriter       : None
lxml.etree       : 4.6.4
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.30.1
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
fastparquet      : None
fsspec           : 2021.11.1
gcsfs            : None
matplotlib       : 3.2.2
numba            : None
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : 0.16.0
pyarrow          : 3.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : 2021.11.1
scipy            : 1.7.3
sqlalchemy       : 1.4.28
tables           : 3.6.1
tabulate         : None
xarray           : 0.20.2
xlrd             : 2.0.1
xlwt             : None
zstandard        : None

</details>

**Comment by mroeschke** [comment]
This is taken from numpy, so it's expected behavior from pandas.

```
In [11]: arr = np.array([0, 1, 2, 0], dtype=np.int8)

In [12]: arr
Out[12]: array([0, 1, 2, 0], dtype=int8)

In [13]: print(arr)
[0 1 2 0]
```
