### ISSUE TITLE
BUG: Pandas not working with some locale on Win10

### ISSUE THREAD

**Issue by Nirdor** [pandas-dev/pandas#45934]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import locale
locale.setlocale(locale.LC_ALL, 'de-DE')

import pandas as pd
#Fails in File "pandas\_libs\tslibs\strptime.pyx", line 370, in pandas._libs.tslibs.strptime._getlang
#ValueError: unknown locale: de-DE
```

### Issue Description

Python has a problem with some locales on Win10
(see https://bugs.python.org/issue43115)
pandas is not working when that happens

### Expected Behavior

Pandas should catch any erros from locale.getlocale and use a default lang.

`def _getlang():`
`    """Figure out what language is being used for the locale"""`
`    try:`
`        return locale.getlocale(locale.LC_TIME)`
`    except:`
`        return (None, None)`

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.10.2.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.14393
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : de_DE.cp1252

pandas           : 1.4.0
numpy            : 1.21.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : None

**Comment by mroeschke** [comment]
Thanks for the request, but generally pandas aims to align with Python (which unfortunately means adopting its bugs). Since it appears this is an upstream issue, we would prefer this issue be fixed upstream instead of having brittle patch in the library. Closing as an upstream issue.
