### ISSUE TITLE
ENH: read_json behaviour with bytes object

### ISSUE THREAD

**Issue by abdulniyaspm** [pandas-dev/pandas#45935]
#### Is your feature request related to a problem?

The latest version of `pandas.read_json` does not directly operate on bytes object.

_pandas version 1.1.4_ 
```
>>> import pandas as pd
>>> pd.__version__
'1.1.4'
>>> df = pd.read_json(b'{"col": [1, 2, 3]}')
>>> df
   col
0    1
1    2
2    3
```

_pandas version 1.4.0_ 
```
>>> import pandas as pd
>>> pd.__version__
'1.4.0'
>>>
>>> df = pd.read_json(b'{"col": [1, 2, 3]}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
..... # Skipped traceback for brevity
raise TypeError(
TypeError: Expected file path name or file-like object, got <class 'bytes'> type
```

#### Describe the solution you'd like

I don't know the discussion that leads to the removal of this behavior from the latest releases, but I would like the latest version behave exactly same as version `1.1.4`. 

#### API breaking implications

I don't think that this will affect the API, but we may need to update the documentation.

#### Describe alternatives you've considered

We need to wrap the bytes within in-memory bytes buffer(`BytesIO`) to get the expected behavior. 

```
>>> import pandas as pd
>>>
>>> pd.__version__
'1.4.0'
>>>
>>> from io import BytesIO
>>> df = pd.read_json(BytesIO(b'{"col": [1, 2, 3]}'))
>>> df
   col
0    1
1    2
2    3
```
But I would like pandas to do this work implicitly [like in this case.](https://github.com/pandas-dev/pandas/commit/5f36af325c276454201495eaf66be55bd17964a5#diff-63200ddb7f5656b8ee868a28d9cb7720ffe50689b0e3fb0b4e15cc5c0ae80dd7R411)

#### Additional context

[pandas `read_json` behavior with `bytes` object](https://stackoverflow.com/questions/71074363/pandas-read-json-behavior-with-bytes-object)

**Comment by twoertwein** [comment]
> I don't think that this will affect the API, but we may need to update the documentation.

`read_json` is [not documented to support bytes](https://pandas.pydata.org/docs/reference/api/pandas.read_json.html). If it is intended that `read_json` should accept bytes, you probably need to add bytes to [this isinstance checks](https://github.com/pandas-dev/pandas/blob/72d8ec2913368a02da1ebc5a76c7dc9714b869ba/pandas/io/json/_json.py#L705) and likely an if-statement [here](https://github.com/pandas-dev/pandas/blob/72d8ec2913368a02da1ebc5a76c7dc9714b869ba/pandas/io/json/_json.py#L688) to convert it to `StringIO(filepath_or_buffer.decode(encoding, errors=encoding_errors))`


Personally, I'm not a fan of accepting both content and file handles (but `read_json` unfortunately already accepts json-strings).

**Comment by jreback** [comment]
yeah i believe we *not* accept bytes here as json is by definition a string format (all that said it can surely come over the wire as bytes, but that is a boundry that the user should cross)

**Comment by mroeschke** [comment]
Thanks for the request, but agreed I think not accepting bytes was an intentional decision due to json's definition. Closing as it appears there's not a lot of support to change this
