### ISSUE TITLE
ENH: Add (df | srs).index.between()

### ISSUE THREAD

**Issue by janosh** [pandas-dev/pandas#45958]
#### Is your feature request related to a problem?

Would be useful to be able to call `between()` on indices.

#### Describe the solution you'd like

```py
srs = pd.Series(0, index=range(10))
srs.index.between(0, 5)
0     True
1     True
2     True
3     True
4     True
5     True
6    False
7    False
8    False
9    False
Name: index, dtype: bool
```

#### API breaking implications

Enhancement, no breakage.

#### Describe alternatives you've considered

This already works but is clunky:

```py
srs = pd.Series(0, index=range(10))
srs.reset_index().iloc[:, 0].between(0, 5)
0     True
1     True
2     True
3     True
4     True
5     True
6    False
7    False
8    False
9    False
Name: index, dtype: bool
```

**Comment by mroeschke** [comment]
I think the workaround is fairly idiomatic (or `pd.Series(ser.index).between(0, 5)`) so I'd be -1 on expanding the API.

**Comment by jreback** [comment]
-1 as well

**Comment by mroeschke** [comment]
Thanks for the request, but since there is not a lot of support for this feature, closing.
