### ISSUE TITLE
ENH: add flag to allow for +/- signs in pandas.Series.str.isdigit()

### ISSUE THREAD

**Issue by janosh** [pandas-dev/pandas#45963]
#### Is your feature request related to a problem?

`pandas.Series.str.isdigit()` gives `False` for strings that contain signs like `'+10'`, `'-3'`. This is good default behavior but perhaps there could be a flag to allow for sign prefixes?

#### Describe the solution you'd like

`pandas.Series.str.isdigit(allow_signs: bool = False)` and same for `pandas.Series.str.isnumeric()`.

```py
pd.Series([str(idx) for idx in range(-1, 2)]).str.isdigit()
0    False
1     True
2     True
dtype: bool

pd.Series([str(idx) for idx in range(-1, 2)]).str.isdigit(allow_signs=True)
0     True
1     True
2     True
dtype: bool
```

#### API breaking implications

Enhancement, no breakage.

#### Describe alternatives you've considered

Could be another function entirely `pandas.Series.str.is_signed_digit()` but seems overkill.

#### Additional context

[add any other context, code examples, or references to existing implementations about the feature request here]

```python
# Your code here, if applicable

```

**Comment by mroeschke** [comment]
It's important that pandas str functions align closely with the standard library string functions, so since `string.isdigit` doesn't allow for `+/-` keyword support I don't think pandas should (-1 for this change)

```
In [1]: "+10".isdigit()
Out[1]: False
```

**Comment by janosh** [comment]
@mroeschke I see your point and expected someone would make this objection. To be clear, default behavior would still align with stdlib `str.isdigit()`. I'm just proposing to add additional control. Though I'll understand if you say you don't want to extend beyond stdlib behavior.

**Comment by janosh** [comment]
@jreback `pd.to_numeric` would handle floats too, no? I want to error on floats. Currently I'm using

```
try:
    srs.astype(int)
    all_ints = True
except (ValueError, TypeError):
    pass
```

**Comment by jreback** [comment]
you can also do a reflex with contains

in any event expanding this api is -1

**Comment by janosh** [comment]
> you can also do a reflex with contains

Not sure what that means. This `srs.str.contains('(+|-)\d+')`?

> in any event expanding this api is -1

Yes, I got that. 🤔
