### ISSUE TITLE
DOC: Series.rolling and DataFrame.rolling share docstring

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [pandas-dev/pandas#45969]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.Series.rolling.html?highlight=series%20rolling#pandas.Series.rolling

### Documentation problem

The documentation of the Series function contains references to axis, which makes no sense for a Series (which is one-dimensional).  It also refers to single vs. table functionality, which again makes no sense for a Series (which is single-only).

I can see that in cases like drop and dropna, axis exists as a parameter, but clearly states that there is only one axis.  In other documentation (such as groupby) the series documentation invites both row and column axis.

### Suggested fix for documentation

The Series documentation for rolling should follow the pattern of explaining axis as provided by drop/dropna.  All Series functions with an axis parameter should be checked and fixed if necessary.

**Comment by phofl** [comment]
Hi, thanks for your report. The drop and dropna functions have one implementation for Series and DataFrame each while for rolling aggregations there is only one implementation. Hence the identical dostring. Not sure if we can fix this easily.

**Comment by jackgoldsmith4** [comment]
#47109 adds docs for all Series functions that take an `axis` parameter to explain that the `axis` parameter is unused in Series and only for compatibility with DataFrame. That seems like it might close this issue as well?

**Comment by MichaelTiemannOSC** [comment]
It does, thank you!

**Comment by jreback** [comment]
the PR has not been merged 
instead you can add a refeneve there and will close the issue when it's merged
