### ISSUE TITLE
IF the read_sql function can read multi datatable results in one time like the read_excel behaves

### ISSUE THREAD

**Issue by DatumWorld** [pandas-dev/pandas#45979]
#### Is your feature request related to a problem?

IF the read_sql function can read multi datatable results in one time like the read_excel behaves. 
For sometimes, I have to read data from database with read_sql for several times.

#### Describe the solution you'd like
Like the function read_excel, setting the param sheet_name=None will get all the worksheets, add a similar param like that for read_sql funtion,try to make it convenient to read  multi datatable results in one time.
The read_sql returns the first datatable result only now, like that shown in the following picture
![image](https://user-images.githubusercontent.com/24842100/153786436-e1a1a8f6-a2d0-498c-8886-c5dc5341ff95.png)

Is it possible to return multi datatable results in one time? Thanks!

**Comment by Pydare** [comment]
take

**Comment by Pydare** [comment]
take

**Comment by mroeschke** [comment]
For the reason describe in https://github.com/pandas-dev/pandas/pull/46035#issuecomment-1047427179 (i.e. each `read_*` function is intentionally designed to read 1 source at a time), I'd be -1 based on consistency

**Comment by jreback** [comment]
agree -1
