### ISSUE TITLE
BUG: not able to install pandas

### ISSUE THREAD

**Issue by teja1809** [pandas-dev/pandas#46002]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd 

pip install pandas
```

### Issue Description

error starting 

### Expected Behavior

should start library imported

### Installed Versions

python 3.10.2

**Comment by Hrushi20** [comment]
Hey! can you send a screenshot about your issue.
