### ISSUE TITLE
REF: ArrowBackedExtensionArray

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#46008]
We should refactor out parts of `ArrowStringArray` and `tests.extension.arrow.arrays.ArrowExtensionArray` that can be re-used for more general arrow-based EAs.

A couple of questions that came up in my first pass at this (cc @jorisvandenbossche):

- Should the general case allow backing by either pa.Array or pa.ChunkedArray, or just pa.ChunkedArray?
- ArrowStringArray.copy relies on immutability.  Will that be the case in general? If not, how do we check for it?
- Is the more verbose `nbytes` in ArrowExtensionArray more robust/correct than the one in ArrowStringArray?
- Are the slightly-different `_concat_same_type` methods equivalent? Usable for the general case?

**Comment by jbrockmendel** [comment]
@xhochy is there anything worth upstreaming from fletcher?  Or maybe fletcher is a better home for this?

**Comment by jbrockmendel** [comment]
@mroeschke closeable?

**Comment by mroeschke** [comment]
Yeah will close with https://github.com/pandas-dev/pandas/pull/49000

**Comment by xhochy** [comment]
Looks good 👍
