### ISSUE TITLE
BUG: scaled_df.describe() TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

### ISSUE THREAD

**Issue by levalencia** [pandas-dev/pandas#46017]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
# azureml-core of version 1.0.72 or higher is required
# azureml-dataprep[pandas] of version 1.1.34 or higher is required
from azureml.core import Workspace, Dataset

subscription_id = 'x'
resource_group = 'RG-Architecture-Playground'
workspace_name = 'mlplayground'

workspace = Workspace(subscription_id, resource_group, workspace_name)

dataset = Dataset.get_by_name(workspace, name='WineDataset')
df = dataset.to_pandas_dataframe()
df.head(10)

len(df)

df.dropna(how='any', inplace=True)
df.isnull().sum()


from sklearn import preprocessing
import pandas as pd
scaler = preprocessing.MinMaxScaler()
names = df.columns
d = scaler.fit_transform(df)
scaled_df = pd.DataFrame(d, columns=names)
scaled_df.head()

# Basic descriptive and statistics for each column
scaled_df.describe()
```

### Issue Description

I ran pip freeze to see the packages I have in the environment.

!pip freeze
    
    
    absl-py==0.15.0
    adal==1.2.7
    alembic==1.7.6
    ansiwrap==0.8.4
    antlr4-python3-runtime==4.7.2
    applicationinsights==0.11.10
    arch==4.14
    argcomplete==1.12.3
    argon2-cffi==21.3.0
    argon2-cffi-bindings==21.2.0
    astor==0.8.1
    astunparse==1.6.3
    attrs==21.4.0
    autokeras==1.0.16
    azure-appconfiguration==1.1.1
    azure-batch==11.0.0
    azure-cli==2.33.0
    azure-cli-core==2.33.0
    azure-cli-telemetry==1.0.6
    azure-common==1.1.27
    azure-core==1.21.1
    azure-cosmos==3.2.0
    azure-datalake-store==0.0.52
    azure-graphrbac==0.61.1
    azure-identity==1.7.0
    azure-keyvault==1.1.0
    azure-keyvault-administration==4.0.0b3
    azure-keyvault-keys==4.5.0b4
    azure-loganalytics==0.1.1
    azure-mgmt-advisor==9.0.0
    azure-mgmt-apimanagement==0.2.0
    azure-mgmt-appconfiguration==2.0.0
    azure-mgmt-applicationinsights==1.0.0
    azure-mgmt-authorization==0.61.0
    azure-mgmt-batch==16.0.0
    azure-mgmt-batchai==7.0.0b1
    azure-mgmt-billing==6.0.0
    azure-mgmt-botservice==0.3.0
    azure-mgmt-cdn==11.0.0
    azure-mgmt-cognitiveservices==13.0.0
    azure-mgmt-compute==23.1.0
    azure-mgmt-consumption==2.0.0
    azure-mgmt-containerinstance==9.1.0
    azure-mgmt-containerregistry==8.2.0
    azure-mgmt-containerservice==16.4.0
    azure-mgmt-core==1.3.0
    azure-mgmt-cosmosdb==7.0.0b2
    azure-mgmt-databoxedge==1.0.0
    azure-mgmt-datalake-analytics==0.2.1
    azure-mgmt-datalake-nspkg==3.0.1
    azure-mgmt-datalake-store==0.5.0
    azure-mgmt-datamigration==10.0.0
    azure-mgmt-deploymentmanager==0.2.0
    azure-mgmt-devtestlabs==4.0.0
    azure-mgmt-dns==8.0.0
    azure-mgmt-eventgrid==9.0.0
    azure-mgmt-eventhub==9.1.0
    azure-mgmt-extendedlocation==1.0.0
    azure-mgmt-hdinsight==9.0.0
    azure-mgmt-imagebuilder==1.0.0
    azure-mgmt-iotcentral==9.0.0
    azure-mgmt-iothub==2.1.0
    azure-mgmt-iothubprovisioningservices==1.0.0
    azure-mgmt-keyvault==9.3.0
    azure-mgmt-kusto==0.3.0
    azure-mgmt-loganalytics==12.0.0
    azure-mgmt-managedservices==1.0.0
    azure-mgmt-managementgroups==0.2.0
    azure-mgmt-maps==2.0.0
    azure-mgmt-marketplaceordering==1.1.0
    azure-mgmt-media==7.0.0
    azure-mgmt-monitor==3.0.0
    azure-mgmt-msi==0.2.0
    azure-mgmt-netapp==6.0.1
    azure-mgmt-network==19.3.0
    azure-mgmt-nspkg==3.0.2
    azure-mgmt-policyinsights==1.0.0
    azure-mgmt-privatedns==1.0.0
    azure-mgmt-rdbms==10.0.0
    azure-mgmt-recoveryservices==2.0.0
    azure-mgmt-recoveryservicesbackup==4.0.0
    azure-mgmt-redhatopenshift==1.0.0
    azure-mgmt-redis==13.1.0
    azure-mgmt-relay==0.1.0
    azure-mgmt-reservations==0.6.0
    azure-mgmt-resource==20.0.0
    azure-mgmt-search==8.0.0
    azure-mgmt-security==2.0.0b1
    azure-mgmt-servicebus==6.0.0
    azure-mgmt-servicefabric==1.0.0
    azure-mgmt-servicefabricmanagedclusters==1.0.0
    azure-mgmt-servicelinker==1.0.0b1
    azure-mgmt-signalr==1.0.0
    azure-mgmt-sql==3.0.1
    azure-mgmt-sqlvirtualmachine==1.0.0b1
    azure-mgmt-storage==19.0.0
    azure-mgmt-synapse==2.1.0b4
    azure-mgmt-trafficmanager==1.0.0
    azure-mgmt-web==4.0.0
    azure-multiapi-storage==0.7.0
    azure-nspkg==3.0.2
    azure-storage-blob==12.9.0
    azure-storage-common==1.4.2
    azure-storage-queue==12.1.6
    azure-synapse-accesscontrol==0.5.0
    azure-synapse-artifacts==0.10.0
    azure-synapse-managedprivateendpoints==0.3.0
    azure-synapse-spark==0.2.0
    azureml-accel-models==1.38.0
    azureml-automl-core==1.38.0
    azureml-automl-dnn-nlp==1.38.0
    azureml-automl-runtime==1.38.0
    azureml-cli-common==1.38.0
    azureml-contrib-automl-pipeline-steps==1.38.0
    azureml-contrib-dataset==1.38.0
    azureml-contrib-fairness==1.38.0
    azureml-contrib-notebook==1.38.0
    azureml-contrib-pipeline-steps==1.38.0
    azureml-contrib-reinforcementlearning==1.38.0
    azureml-contrib-server==1.38.0
    azureml-contrib-services==1.38.0
    azureml-core==1.38.0
    azureml-datadrift==1.38.0
    azureml-dataprep==2.26.0
    azureml-dataprep-native==38.0.0
    azureml-dataprep-rslex==2.2.0
    azureml-dataset-runtime==1.38.0
    azureml-defaults==1.38.0
    azureml-explain-model==1.38.0
    azureml-inference-server-http==0.4.2
    azureml-interpret==1.38.0
    azureml-mlflow==1.38.0
    azureml-opendatasets==1.38.0
    azureml-pipeline==1.38.0
    azureml-pipeline-core==1.38.0
    azureml-pipeline-steps==1.38.0
    azureml-responsibleai==1.38.0
    azureml-sdk==1.38.0
    azureml-telemetry==1.38.0
    azureml-tensorboard==1.38.0
    azureml-train==1.38.0
    azureml-train-automl==1.38.0
    azureml-train-automl-client==1.38.0
    azureml-train-automl-runtime==1.38.0
    azureml-train-core==1.38.0
    azureml-train-restclients-hyperdrive==1.38.0
    azureml-widgets==1.38.0
    backcall==0.2.0
    backports.tempfile==1.0
    backports.weakref==1.0.post1
    bcrypt==3.2.0
    beautifulsoup4==4.10.0
    bleach==4.1.0
    blis==0.2.4
    bokeh==2.3.3
    Boruta==0.3
    boto==2.49.0
    boto3==1.20.19
    botocore==1.23.19
    Bottleneck==1.3.2
    cached-property==1.5.2
    cachetools==4.2.4
    certifi==2021.10.8
    cffi==1.15.0
    chardet==3.0.4
    charset-normalizer==2.0.10
    click==8.0.3
    cloudpickle==2.0.0
    colorama==0.4.4
    colorlover==0.3.0
    configparser==3.7.4
    contextlib2==21.6.0
    contextvars==2.4
    convertdate @ file:///home/conda/feedstock_root/build_artifacts/convertdate_1642883757836/work
    coremltools @ git+https://github.com/apple/coremltools@13c064ed99ab1da7abea0196e4ddf663ede48aad
    cryptography==36.0.1
    cufflinks==0.17.3
    cycler==0.11.0
    cymem==2.0.6
    Cython==0.29.26
    dask==2.30.0
    databricks-cli==0.16.2
    dataclasses==0.6
    datasets==1.8.0
    decorator==5.1.1
    defusedxml==0.7.1
    Deprecated==1.2.13
    dice-ml==0.7.2
    dill==0.3.4
    distributed==2.30.1
    distro==1.6.0
    docker==5.0.3
    dotnetcore2==2.1.22
    dowhy==0.7
    econml==0.12.0
    en-core-web-sm @ https://aka.ms/automl-resources/packages/en_core_web_sm-2.1.0.tar.gz
    encrypted-inference==0.9
    entrypoints==0.3
    erroranalysis==0.1.29
    fabric==2.6.0
    fairlearn==0.7.0
    fastai==1.0.61
    fastprogress==1.0.0
    fbprophet==0.5
    filelock==3.4.1
    fire==0.4.0
    Flask==1.0.3
    Flask-Cors==3.0.10
    flatbuffers==2.0
    fsspec==2022.1.0
    funcy==1.17
    fusepy==3.0.1
    future==0.18.2
    gast==0.2.2
    gensim==3.8.3
    gevent==1.3.6
    gitdb==4.0.9
    GitPython==3.1.18
    google-auth==1.35.0
    google-auth-oauthlib==0.4.6
    google-pasta==0.2.0
    graphviz @ file:///tmp/build/80754af9/python-graphviz_1602262908037/work
    greenlet==1.1.2
    grpcio==1.43.0
    gunicorn==20.1.0
    h5py==3.1.0
    HeapDict==1.0.1
    holidays==0.9.11
    horovod==0.19.1
    htmlmin==0.1.12
    huggingface-hub==0.0.19
    humanfriendly==10.0
    idna==3.3
    ImageHash==4.2.1
    imageio==2.15.0
    imbalanced-learn==0.7.0
    immutables==0.16
    importlib-metadata==4.8.3
    importlib-resources==5.4.0
    inference-schema==1.3.0
    interpret-community==0.24.1
    interpret-core==0.2.7
    invoke==1.6.0
    ipykernel==5.5.6
    ipython==7.16.3
    ipython-genutils==0.2.0
    ipywidgets==7.6.5
    isodate==0.6.1
    itsdangerous==2.0.1
    javaproperties==0.5.2
    jedi==0.18.0
    jeepney==0.7.1
    Jinja2==2.11.2
    jmespath==0.10.0
    joblib==0.14.1
    json-logging-py==0.2
    jsondiff==1.3.1
    jsonpickle==2.1.0
    jsonschema==3.2.0
    jupyter==1.0.0
    jupyter-client==6.1.12
    jupyter-console==6.4.0
    jupyter-core==4.9.1
    jupyterlab-widgets==1.0.2
    Keras==2.3.1
    Keras-Applications==1.0.8
    keras-nightly==2.5.0.dev2021032900
    Keras-Preprocessing==1.1.2
    keras-tuner==1.1.0
    keras2onnx==1.6.0
    kiwisolver==1.3.1
    kmodes==0.11.1
    knack==0.8.2
    kt-legacy==1.0.4
    liac-arff==2.5.0
    lightgbm==2.3.0
    llvmlite==0.36.0
    locket==0.2.1
    lunardate==0.2.0
    Mako==1.1.6
    Markdown==3.3.6
    MarkupSafe==2.0.1
    matplotlib==3.3.4
    missingno==0.5.0
    mistune==0.8.4
    mkl-fft==1.2.0
    mkl-random==1.1.0
    mkl-service==2.3.0
    ml-wrappers==0.0.6
    mlflow==1.23.1
    mlflow-skinny==1.23.0
    mlxtend==0.19.0
    mpmath==1.2.1
    msal==1.16.0
    msal-extensions==0.3.1
    msgpack==1.0.3
    msrest==0.6.21
    msrestazure==0.6.4
    multimethod==1.5
    multiprocess==0.70.12.2
    murmurhash==1.0.6
    nbconvert==5.6.1
    nbformat==5.1.3
    ndg-httpsclient==0.5.1
    nest-asyncio==1.5.4
    networkx==2.5
    nimbusml==1.8.0
    nltk==3.6.7
    notebook==6.4.7
    numba==0.53.1
    numexpr==2.8.1
    numpy==1.18.5
    nvidia-ml-py3==7.352.0
    oauthlib==3.1.1
    olefile==0.46
    onnx==1.7.0
    onnxconverter-common==1.6.0
    onnxmltools==1.4.1
    onnxruntime==1.8.0
    opencv-python-headless==4.5.5.62
    opt-einsum==3.3.0
    packaging==21.3
    pandas==1.1.5
    pandas-ml==0.6.1
    pandas-profiling==3.1.0
    pandocfilters==1.5.0
    papermill==1.2.1
    paramiko==2.9.2
    parso==0.7.1
    partd==1.2.0
    pathlib2==2.3.6
    pathspec==0.9.0
    patsy==0.5.2
    pexpect==4.8.0
    phik==0.12.0
    pickleshare==0.7.5
    Pillow @ file:///tmp/build/80754af9/pillow_1602788709045/work
    pkginfo==1.8.2
    plac==0.9.6
    plotly==5.5.0
    pmdarima==1.1.1
    portalocker==2.3.2
    preshed==2.0.1
    prometheus-client==0.12.0
    prometheus-flask-exporter==0.18.7
    prompt-toolkit==3.0.24
    property-cached==1.6.4
    protobuf==3.19.3
    psutil==5.9.0
    psycopg2 @ file:///tmp/build/80754af9/psycopg2_1612298609104/work
    ptyprocess==0.7.0
    py4j==0.10.9.2
    pyarrow==3.0.0
    pyasn1==0.4.8
    pyasn1-modules==0.2.8
    pycaret==2.3.6
    pycocotools==2.0.0
    pycparser==2.21
    pydantic==1.9.0
    pydot==1.4.2
    PyGithub==1.55
    Pygments==2.11.2
    PyJWT==2.3.0
    pyLDAvis==3.3.1
    PyMeeus @ file:///home/conda/feedstock_root/build_artifacts/pymeeus_1615809745702/work
    PyNaCl==1.5.0
    pynndescent==0.5.6
    pyod==0.9.7
    pyodbc===4.0.0-unsupported
    pyOpenSSL==21.0.0
    pyparsing==3.0.6
    pyreadline==2.1
    pyrsistent==0.18.0
    PySocks==1.7.1
    pyspark==3.2.0
    pystan==2.19.0.0
    python-dateutil==2.8.2
    pytorch-transformers==1.0.0
    pytz==2021.3
    PyWavelets==1.1.1
    PyYAML==6.0
    pyzmq==22.3.0
    qtconsole==5.2.2
    QtPy==2.0.1
    querystring-parser==1.2.4
    rai-core-flask==0.2.4
    raiwidgets==0.16.0
    regex==2022.1.18
    requests==2.27.1
    requests-oauthlib==1.3.0
    responsibleai==0.16.0
    rsa==4.8
    s3transfer==0.5.0
    sacremoses==0.0.47
    scikit-image==0.17.2
    scikit-learn==0.24.2
    scikit-plot==0.3.7
    scipy==1.5.2
    scp==0.13.6
    scrapbook==0.5.0
    seaborn==0.11.2
    SecretStorage==3.3.1
    semver==2.13.0
    Send2Trash==1.8.0
    sentencepiece==0.1.96
    seqeval==1.2.2
    setuptools-git==1.2
    shap==0.39.0
    sip==4.19.24
    six==1.16.0
    skl2onnx==1.4.9
    sklearn-pandas==1.7.0
    slicer==0.0.7
    smart-open==1.9.0
    smmap==5.0.0
    sortedcontainers==2.4.0
    soupsieve==2.3.1
    spacy==2.1.8
    sparse==0.13.0
    SQLAlchemy==1.4.31
    sqlparse==0.4.2
    srsly==1.0.5
    sshtunnel==0.1.5
    statsmodels==0.10.2
    sympy==1.9
    tabulate==0.8.9
    tangled-up-in-unicode==0.1.0
    tblib==1.7.0
    tenacity==8.0.1
    tensorboard==2.1.1
    tensorboard-data-server==0.6.1
    tensorboard-plugin-wit==1.8.1
    tensorflow==2.1.0
    tensorflow-estimator==2.1.0
    tensorflow-gpu==2.1.0
    termcolor==1.1.0
    terminado==0.12.1
    testpath==0.5.0
    textblob==0.17.1
    textwrap3==0.9.2
    thinc==7.0.8
    threadpoolctl @ file:///tmp/tmp9twdgx9k/threadpoolctl-2.1.0-py3-none-any.whl
    tifffile==2020.9.3
    tokenizers==0.10.3
    toolz==0.11.2
    torch==1.10.1
    torch-tb-profiler==0.3.1
    torchvision==0.9.1
    tornado==6.1
    tqdm==4.62.3
    traitlets==4.3.3
    transformers==4.5.1
    typing-extensions==4.0.1
    umap-learn==0.5.2
    urllib3==1.26.7
    uuid==1.30
    visions==0.7.4
    waitress==2.0.0
    wasabi==0.9.0
    wcwidth==0.2.5
    webencodings==0.5.1
    websocket-client==1.2.3
    websockets==9.1
    Werkzeug==2.0.2
    widgetsnbextension==3.5.2
    wordcloud==1.8.1
    wrapt==1.12.1
    xgboost==0.90
    xmltodict==0.12.0
    xxhash==2.0.2
    yellowbrick==1.3.post1
    zict==2.0.0
    zipp==3.6.0
    zope.event==4.5.0
    zope.interface==5.4.0

Then I ran the code above, manipulated a dataframe, normalized it, and then I wanted to describe it with .describe()

### Expected Behavior

.describe() should run without errors

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.1.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-1068-azure
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.3
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 50.3.0
Cython           : 0.29.21
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 8.0.1
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.2.1
numexpr          : 2.8.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 3.0.0
pytables         : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : 1.4.31
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by mroeschke** [comment]
Could you provide a minimal reproducible example? https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports
