### ISSUE TITLE
ENH: add `DataFrame.to_frame` to simplify generic code.

### ISSUE THREAD

**Issue by randolf-scholz** [pandas-dev/pandas#46011]
#### Is your feature request related to a problem?

Sometimes when writing generic code it can happen that it is not clear whether one is dealing with a `DataFrame` or a `Series`, for example after doing `df[cols]` when `cols` is `Union[str, list[str]]`. In this case current one can to do either 

1. `df = DataFrame(df)` 
2. `isinstance` checks 

However, the situation gets worse if also the object could be an `Index`, because then `DataFrame(obj)` and `obj.to_frame()` might give different results (for example in the case of `MultiIndex`), and the `isinstance` checks get more verbose.

#### Describe the solution you'd like

Simply add a `to_frame` method to `DataFrame`, that returns the instance as-is. This also has a speed advantage:

```python
from types import MethodType
import numpy as np
from pandas import DataFrame
df = DataFrame(np.random.randn(100, 100))
df.to_frame = MethodType(lambda self: self, df)

%%timeit
df.to_frame()  # ← ~65ns

%%timeit
DataFrame(df)   # ← ~1.3µs
```

#### API breaking implications

None? Possibly if `hasattr(obj, to_frame)` is used somewhere to test if the object is a `DataFrame`.

#### Additional context

Further down the road an interesting question is whether one would want to have some abstract base classes similar to [collections.abc](https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes), with guaranteed methods for a variety of pandas objects.

**Comment by jreback** [comment]
-0.5 on this 

operation are very clear on what they return and this just encourages errors

i can see the utility of writing slightly more generic code but not so much to expand the api
