### ISSUE TITLE
Multiindex Equals Not Commutative

### ISSUE THREAD

**Issue by hliatrussellinvestments** [pandas-dev/pandas#46026]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

df1 = pd.DataFrame({
    'a': [0, 0, 1, 1],
    'b': [0, 1, 0, 1],
    'c': [0, 0, 0, 0],
    'v': [1, 2, 3, 4],
})
df1['a'] = df1['a'].astype('Int32')


df2 = pd.DataFrame({
    'a': [0, 0, 1, 1],
    'b': [0, 1, 0, 1],
    'v': [1, 2, 3, 4],
})
df2.set_index(['a', 'b'], inplace=True)

df1_agg = df1.groupby(['a', 'b']).agg({'v': 'max'})

print(df1_agg.index.equals(df2.index) == df2.index.equals(df1_agg.index))
```

### Issue Description

For any 2 indexes, idx_1, idx_2, we should get the same result for idx_1.equals(idx_2) and idx_2.equals(idx_1). Currently they are not the same.

### Expected Behavior

print(df1_agg.index.equals(df2.index) == df2.index.equals(df1_agg.index)) should print out True.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.8.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252
pandas           : 1.4.0
numpy            : 1.19.0
pytz             : 2021.3
dateutil         : 2.8.1
pip              : 21.3.1
setuptools       : 49.2.1
Cython           : None
pytest           : 5.4.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : 2021.10.0
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.4
sqlalchemy       : 1.4.31
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by lukemanley** [comment]
Looks like this block is causing the behavior:

https://github.com/pandas-dev/pandas/blob/9cc98a064e2873ff5ddab62efdb23060c2d52167/pandas/core/indexes/multi.py#L3607-L3613


```
import numpy as np
import pandas as pd
from pandas.core.dtypes.missing import array_equivalent

a = pd.Index([1, 2, 3], dtype="Int64")
b = np.array([1, 2, 3])

a.equals(b)               # False
array_equivalent(a, b)    # True
