### ISSUE TITLE
BUG: .astype date conversion from object to datetime switches months and days

### ISSUE THREAD

**Issue by eliyahuA** [pandas-dev/pandas#46031]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

print(pd.__version__)
df = pd.DataFrame({'A': ['01/07/2021']})
print(df)
pd.set_option('display.date_dayfirst', True)
date_df = df.astype(dtype={'A': 'datetime64'})
date_df_np = df.astype(dtype={'A': np.datetime64})
print(date_df)
print(date_df_np)

Output:

            A
0  01/07/2021
           A
0 2021-01-07
           A
0 2021-01-07
```

### Issue Description

When converting a string (object) dtype to a datetime dtype with DataFrame astype method, the date format is inferred according to United States notation, despite the setting of display.date_dayfirst

### Expected Behavior

Yes, it's possible to use pd.to_datetime, but for simple cases it's cumbersome to have to break the symmetry between how you would coerce other types and how you coerce datetimes.

Expected Output:

            A
0  01/07/2021
           A
0 2021-07-01
           A
0 2021-07-01

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.9.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18363
machine          : AMD64
processor        : Intel64 Family 6 Model 63 Stepping 0, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Hebrew_Israel.1255
pandas           : 1.4.1
numpy            : 1.22.0
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.0.3
setuptools       : 58.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.31.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.4.31
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
</details>

**Comment by phofl** [comment]
The option is a display option, this does not influence pandas internal behvior when inferring a format. I would recommend using ``pd.to_datetime``. This allows you to specify a format

``pd.to_datetime(df["A"], format="%d/%m/%Y")``

**Comment by eliyahuA** [comment]
In the [docs ](https://pandas.pydata.org/docs/reference/api/pandas.set_option.html?highlight=set_option#)it says that the display option also affects parsing:
**display.date_dayfirst boolean**
When True, prints and **parses** dates with the day first, eg 20/01/2005
So, perhaps the documentation should be updated

Also, I want to propose updating astype to have additional keyword argument to receive the format, such as:
`date_df_np = df.astype(dtype={'A': np.datetime64}, formats= '%d/%m/%Y')`
should I open a new Issue for that proposal as feature request?

The use of `astype` for date conversions is more powerfull then `to_datetime` when we convert several columns of different types at the same time.

example:
```
types = {'user_id': int, 'user_name': pd.StringDtype(), 'create_date': np.datetime64, 'last_login_date': np.datetime64}
date_format = '%d/%m/%Y'
typed_df = df.astype(types)
```
to achieve this with to_datetime, several more lines of code required

**Comment by phofl** [comment]
I am -1 on addind formats to astype, this is specific to datetimes.


You are correct with respect to the display option, but this is only relevant for date specific functionality I think

**Comment by phofl** [comment]
Closing since this is expected. to_datetime handles this
