### ISSUE TITLE
BUG: Pandas rolling std precision error

### ISSUE THREAD

**Issue by juanmpga** [pandas-dev/pandas#46049]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

data = pd.Series([-3.0, -3.0, -4.0, -5.0, -4.0, -3.0, -4.0, -4.0, -3.0, -4.0, -3.0, -4.0, -3.0, -2.0, -2.0, -3.0, -2.0, -2.0, -3.0, -3.0, -4.0, -4.0, -4.0, -4.0, -4.0, -5.0, -5.0, -5.0, -5.0, -5.0])

print(data.rolling(5).std().iloc[-1]) # <-- yields 1.2904784139758924e-08 instead of 0
print(data.tail(25).rolling(5).std().iloc[-1]) # <-- correctly yields 0
```

### Issue Description

There seems to be a precision problem with rolling.std(). Including more data in the pd.Series affects noticeably the result of calculations that are quite far apart (several times the rolling window). I think it may be an error introduced by the online algorithm that is used.

Related: 
https://github.com/pandas-dev/pandas/pull/37055
https://github.com/pandas-dev/pandas/issues/37051
https://github.com/pandas-dev/pandas/issues/39872

### Expected Behavior

`print(data.rolling(5).std().iloc[-1]) `
The above should yield 0 as the 5 last data points are equal.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.8.12.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18363
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : es_ES.cp1252

pandas           : 1.4.1
numpy            : 1.21.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 20.3.3
setuptools       : 58.0.4
Cython           : None
pytest           : 7.0.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.2
IPython          : 7.31.1
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.2
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.1
numba            : 0.55.1
numexpr          : 2.8.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
sqlalchemy       : 1.3.24
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by phofl** [comment]
The issues you have linked contain discussion about this topic. This was announced in 1.3. 

See https://pandas.pydata.org/docs/whatsnew/v1.3.0.html#removed-artificial-truncation-in-rolling-variance-and-standard-deviation

**Comment by juanmpga** [comment]
> The issues you have linked contain discussion about this topic. This was announced in 1.3.
> 
> See https://pandas.pydata.org/docs/whatsnew/v1.3.0.html#removed-artificial-truncation-in-rolling-variance-and-standard-deviation

Thanks! I did see the ~1e-15 error for variance but thought it wasn't exactly for the same reason given the difference in the order of magnitude (i.e., I didn't realise ~1e-15 in variance is equivalent to ~1e-8 in std).

Thanks again for the quick response!
