### ISSUE TITLE
Add Clarification in Docs about Business DateOffset

### ISSUE THREAD

**Issue by cancan101** [pandas-dev/pandas#4607]
Add clarification in docs about business `DateOffset` (for example BMonthEnd and BQuarterEnd).

How are these `DateOffset`s defined?

The docstring is not particularly helpful:

> DateOffset increments between business EOM dates

**Comment by Tanya-Jain** [comment]
I would like to work on this issue!

**Comment by Azuremis** [comment]
Are you working on this @TanyaaCJain? I'd like to work on this if it's still available.

**Comment by Azuremis** [comment]
As I've not heard back from @TanyaaCJain, I'm going to start working on this issue

**Comment by Azuremis** [comment]
I'm not able to pursue this at this time. Anyone else interested, please feel free to go ahead

**Comment by dhuettenmoser** [comment]
I'd like to work on this!
