### ISSUE TITLE
DOC: tail works even if n > length of DataFrame

### ISSUE THREAD

**Issue by kevinlinxc** [pandas-dev/pandas#46079]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.tail.html

### Documentation problem

It may be obvious to some, but if the `n` requested by `tail()` is greater than the length of the DataFrame, you get the entire DataFrame and no errors are thrown, and this is not mentioned in the documentation. This is useful for me because I'm trying to plot only the last 70 data points of a dataframe but the dataframe might not have 70 values yet. I think it would be reasonable to assume that one implementation would throw an out-of-bounds style exception. 

### Suggested fix for documentation

Add one line about how n > dataframe length is handled.

**Comment by attack68** [comment]
I strongly disagree on exception. This follows python's core logic:

```python
>>> a = [0, 1]
>>> a[:5]
[0, 1]
```

Doc edits generally welcome if they make things more explicit.

**Comment by jreback** [comment]
yep no exception is warranted

**Comment by somieee20** [comment]
Working fine

**Comment by kevinlinxc** [comment]
I think you have misunderstood. I am not calling for an exception to be raised, I am asking that the documentation state that no exception be raised. I was stating that someone reading the documentation right now has no clue what the edge case behaviour is, and some clarification would be a value add to the documentation.

**Comment by itaise** [comment]
take

**Comment by arneja-arnav** [comment]
Hi. I would like to get on this issue. Could it be assigned to me?

**Comment by arneja-arnav** [comment]
take
