### ISSUE TITLE
DOC: missing path-like at path parameter in to_pickle()

### ISSUE THREAD

**Issue by simon-spier0** [pandas-dev/pandas#46081]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.to_pickle.html

### Documentation problem

Based on documentation, it accepts parameter path as str. Inside the to_pickle(), the path parameter is put to stringify_path() so it accepts path-like object actually.

### Suggested fix for documentation

Adding path-like object to documentation removes warning in PyCharm.
![image](https://user-images.githubusercontent.com/60992048/154826832-3f9a70f3-3c29-4f1b-8b78-c74901e33a3c.png)

**Comment by simonjayhawkins** [comment]
Thanks @simon-spier0 for the report. 

The path parameter of NDFrame.to_pickle is also missing a type annotation to match the docstring.

https://github.com/pandas-dev/pandas/blob/afc06e780e267b7eaac8651c7feb53f682d5b4a9/pandas/core/generic.py#L2968-L2971

> Inside the to_pickle(), the path parameter is put to stringify_path() so it accepts path-like object actually.

`NDFrame.to_pickle` dispatches to  `to_pickle` in `pandas/io/pickle.py` where the accepted types are defined as `filepath_or_buffer: FilePath | WriteBuffer[bytes]`. (`FilePath` is defined in `pandas._typing` as `FilePath = Union[str, "PathLike[str]"]`)

The type annotation for `path` in `DataFrame.to_pickle` should match the type annotation for `filepath_or_buffer` in `pandas.io.pickle.to_pickle` and should match the docstring too

contributions welcome.

**Comment by marco-georgaklis** [comment]
take
