### ISSUE TITLE
DOC: Incomplete documentation for get_dummies

### ISSUE THREAD

**Issue by bibhas2** [pandas-dev/pandas#46099]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

In this page:

https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html

### Documentation problem

For the ``columns`` parameter it is stated:

> If columns is None then all the columns with object or category dtype will be converted.

While this is generally correct, this is not true if the file has no header row. Let me first show the problem. Let's say we have file called ``data.txt`` as follows.

```plain
1
2
4
1
3
```

The following code will not do any encoding or conversion.

```python
train_y = pd.read_csv("data.txt", header=None)
train_y = pd.get_dummies(train_y)
train_y.head(5)
```

![image](https://user-images.githubusercontent.com/1730356/155060640-4eeb1e4e-e472-4c01-941a-b011cbf2a05e.png)

To properly encode the values we must supply the column index.

```python
train_y = pd.read_csv("data.txt", header=None)
train_y = pd.get_dummies(train_y, columns=[0])
train_y.head(5)
```

![image](https://user-images.githubusercontent.com/1730356/155060609-38a1ec01-9f84-4796-8d05-8f029150c5e1.png)

### Suggested fix for documentation

Please add coverage for the case when the DataFrame has no header column names.

**Comment by phofl** [comment]
Could you clarify that? this is not a reproducible example. A DataFrame always has column names, if header is None the columns are a RangeIndex.

**Comment by bibhas2** [comment]
Sorry, I wasn't very clear. I have updated my comment with code that you can easily run. I have added screenshot to show the results I am seeing.

**Comment by phofl** [comment]
This works as intended. Your DataFrame has dtype int64, which is not encoded as per the docs. Through declaring columns, you can force an encoding for int64 dtype

**Comment by bibhas2** [comment]
Thank you for explaining. For the benefit of others, this is probably a better way to load a file which has only categorical data (as in the example above).

```python
train_y = pd.read_csv("data.txt", header=None, dtype="category")
train_y = pd.get_dummies(train_y)
train_y.head(5)
```

The issue can be closed.
