### ISSUE TITLE
BUG: is_integer_dtype does not consider Int16Dtype as an integer dtype

### ISSUE THREAD

**Issue by DriesSchaumont** [pandas-dev/pandas#46115]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
>>> import pandas as pd
>>> pd.api.types.is_integer_dtype(pd.DataFrame([1, 2], dtype=pd.Int16Dtype()))
False
```

### Issue Description

According to the docs (https://pandas.pydata.org/docs/reference/api/pandas.api.types.is_integer_dtype.html): 

```The nullable Integer dtypes (e.g. pandas.Int64Dtype) are also considered as integer by this function.```

### Expected Behavior

Should return `True`

### Installed Versions

<details>

commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-91-generic
Version          : #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.1
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 20.0.2
setuptools       : 44.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by asishm** [comment]
Changing the DataFrame to a Series works. Don't think this method supports passing DataFrame as input - the docs mention array-like. The primary reason is probably because dataframes can have multiple dtypes.

**Comment by mroeschke** [comment]
Correct, `is_*_dtypes` are only meant to work on scalars and 1D array likes so this behavior is expected

**Comment by jreback** [comment]
i suppose might be worth adding to the doc string with this as a counter example
