### ISSUE TITLE
ENH: Update to_gbq method in gbq.py to be equal to pandas_gbq.

### ISSUE THREAD

**Issue by ariosramirez** [pandas-dev/pandas#46117]
#### Is your feature request related to a problem?

Yes, I'm using to_gbq pandas's method to upload data from a DataFrame to BigQuery but I can't write floating point to NUMERIC column, the problem is solved by adding the argument `api_method="load_csv"`  (check out the conversation about it: https://www.giters.com/googleapis/python-bigquery-pandas/issues/421)

#### Describe the solution you'd like

Change this code -> https://github.com/pandas-dev/pandas/blob/main/pandas/io/gbq.py#L198-L224 to:
```python
def to_gbq(
        dataframe: DataFrame,
        destination_table: str,
        project_id: str | None = None,
        chunksize: int | None = None,
        reauth: bool = False,
        if_exists: str = "fail",
        auth_local_webserver: bool = False,
        table_schema: list[dict[str, str]] | None = None,
        location: str | None = None,
        progress_bar: bool = True,
        credentials=None,
        api_method: str = "default",
) -> None:
    pandas_gbq = _try_import()
    pandas_gbq.to_gbq(
        dataframe,
        destination_table,
        project_id=project_id,
        chunksize=chunksize,
        reauth=reauth,
        if_exists=if_exists,
        auth_local_webserver=auth_local_webserver,
        table_schema=table_schema,
        location=location,
        progress_bar=progress_bar,
        credentials=credentials,
        api_method=api_method,
    )
```
#### API breaking implications

Just adds the possibility of placing the argument `api_method`

#### Describe alternatives you've considered

I solved the problem using pandas_gbq directly, here is an example:

```Python
import pandas as pd
import pandas_gbq as gbq

table_schema = [{
    "name": "id",
    "type": "INTEGER"
}, {
    "name": "nombre",
    "type": "STRING"
}, {
    "name": "precio",
    "type": "NUMERIC"
}, {
    "name": "fecha",
    "type": "DATE"
}]

data = pd.DataFrame({'id': [123], 'nombre': ['Anderson'], 'precio': [1.25],
                     'fecha': ['2021-12-12']})

project_id = 'proyecto111'
table_name = 'prueba.clientes'

gbq.to_gbq(data, table_name, project_id, if_exists='append',
           table_schema=table_schema, api_method="load_csv")
```

#### Additional context
N/A

**Comment by jreback** [comment]
pandas_gbq has been a separate package for a while

ask on that tracker

**Comment by ariosramirez** [comment]
> pandas_gbq has been a separate package for a while
> 
> ask on that tracker

Then we should specify here (https://github.com/pandas-dev/pandas/blob/main/pandas/core/frame.py#L1985) that this method is not being maintained and that we recommend using this function `pandas_gbq.to_gbq`, don't you think @jreback?

**Comment by jreback** [comment]
there is a convenience wrapper in pandas that calls the appropriate method

so no the docs are pretty clear
