### ISSUE TITLE
ENH: Conversion function errors kwarg callback function

### ISSUE THREAD

**Issue by timlod** [pandas-dev/pandas#46126]
#### Is your feature request related to a problem?

I'm trying to ingest a large amount of data from a csv file into postgres. However, the types in the csv do not perfectly match those of the DB schema, so I load the file in a dataframe for dtype conversion.

`.astype` functions currently only allow `errors={'raise', 'ignore'}`, meaning conversion either fails or doesn't happen - both resulting in not being able to ingest the data. 

#### Describe the solution you'd like

A callback for the `errors` kwarg would be very useful here - accepting a function to apply to the failed element to do a valid conversion.

For example:
```python
x = pd.Series([100, 10, 1, "bad"])
x.astype("Int32") # fails
x.astype("Int32", errors="ignore") # does nothing because of the bad row
# callback to replicate "coerce" behaviour
x.astype("Int32", errors=lambda x: np.nan)
```

Another, more involved case:
```python
x = pd.Series([1000000000, 10, 12, -10000000000])
x.astype("Int32") # fails

# hypothetical case where positive out-of-range values are truncated and other errors are NA
def int32_conv_callback(x):
    if isinstance(x, numbers.Number) and (x > 2**31):
        return np.int32(2 ** 32)
    else:
        return pd.NA

x.astype("Int32", errors=int32_conv_callback)
# (2**31, 10, 12, <NA>)
```

#### API breaking implications

None, an option is added, backwards compatibility is maintained.

#### Describe alternatives you've considered

Adding the `'coerce'` option to `.astype`, which would fill the appropriate null type on failure. NaNs are better than not being able to use a dataframe (and probably cover most cases).

**Comment by Liam3851** [comment]
You can currently do `pd.to_numeric(x, errors='coerce')` which does the NA conversion for you.

For your more complicated example the best way would be something like this in current pandas:
```python3
max_int32 = np.iinfo(np.int32).max
x = pd.to_numeric(x, errors='coerce')
x.loc[x > max_int32] = max_int32
x = x.astype('Int32')
```

which would have the advantage of running the comparisons in C and being substantially faster than a python callback.

**Comment by timlod** [comment]
I'm aware of `pd.to_numeric`, and I do use it in some parts of the code. However, I hadn't thought of chaining it with `astype` to arrive at the desired numeric type (my issue was that ie. I have data that should fit in 8 bits, but has some bad numbers that would only fit in 64 bits, hence `to_numeric` would return `int` at best, and often `float` (when there are NaNs), which can lead to loss in precision. The latter I could achieve by range clipping first, then using `pd.to_numeric` before `astype`.

I believe a callback would be more elegant for such cases, but I don't understand exactly what the performance implications of the python function are - if the more verbose solution is much more efficient, it would still be preferred. 

In any case, adding `coerce` to `astype` would already be a huge improvement here, as we can go to pandas extension types directly, and lose one extra conversion.

**Comment by jreback** [comment]
there is already an issue about dealing with safe conversions i. astype - this is a redundant issue

cc @jorisvandenbossche if u can point to the issue

**Comment by mroeschke** [comment]
Looks like this idea never fully took off so closing
