### ISSUE TITLE
BUILD: openpyxl and xlsxwriter should be installed while installing pandas

### ISSUE THREAD

**Issue by alvynabranches-symbl** [pandas-dev/pandas#46127]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

all

### Installation Method

pip install

### pandas Version

1.4.1

### Python Version

3.8

### Installation Logs

<details>

ModuleNotFoundError: No module named 'openpyxl'

ModuleNotFoundError: No module named 'xlsxwriter'

</details>

**Comment by jreback** [comment]
these are listed as optional dependencies
