### ISSUE TITLE
BUG: dataframe/series.isna().sum() overcounts nan values.

### ISSUE THREAD

**Issue by dhern023** [pandas-dev/pandas#46145]
[test.csv](https://github.com/pandas-dev/pandas/files/8139205/test.csv)
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas # 1.4.1. numpy is 1.22.2

#Dataset provided by WID 2022
raw_test = pandas.read_csv("test.csv")

Try any of these commmands in the console.

raw_test['days_with_fog'].isna().values
>>> array([ True,  True,  True, ...,  True,  True,  True])

len(raw_test['days_with_fog'].isna().values)
>>> 9705

raw_test['days_with_fog'].isna()
>>> 
0        True
1        True
2        True
3        True
4       False
        ...
9700     True
9701     True
9702     True
9703     True
9704     True
Name: days_with_fog, Length: 9705, dtype: bool

raw_test['days_with_fog'].isna().sum()
>>> 9117

raw_test['days_with_fog'].isna().values.sum()
>>> 9117

raw_test['days_with_fog'].isna().value_counts()
>>> 
True     9117
False     588
Name: days_with_fog, dtype: int64

raw_test['days_with_fog'].index
>>> RangeIndex(start=0, stop=9705, step=1)

# These total to 588
raw_test['days_with_fog'].value_counts()
>>> 
129.0    176
138.0    154
250.0    131
123.0     72
34.0      41
126.0     10
107.0      4
Name: days_with_fog, dtype: int64
```

### Issue Description

Pandas is overcounting nans to the point that there are more nan's than can possibly be in the dataframe.. Maybe double-counting numpy.nan and pandas.na uniquely?

### Expected Behavior

All should show the correct totals.

series.isna().value_counts()
series.isna().sum()
series.isna().values.sum()

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.60.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Aug 25 23:20:18 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.1
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 20.0.2
setuptools       : 45.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by phofl** [comment]
Can you narrow this done with less rows? With over 9000 rows this is difficult to investigate

**Comment by rhshadrach** [comment]
I seem to be missing it - what values in the above output are incorrect? They all appear consistent to me.

**Comment by dhern023** [comment]
Jesus Christ. This is why I shouldn't open an issue at 2 AM.
