### ISSUE TITLE
BUG: to_hdf hangs without error messag

### ISSUE THREAD

**Issue by fab6** [pandas-dev/pandas#46148]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
# print(df.head()) in the line above is working as expected
h5FileN = "data.h5"
hdfStruct = "FM_Burner_RAD_snapshot/SIM/2022/BUW/fireFoam_v2106/Run_3/wallPanel_qin_qr_middle_x06_y_z07.patchProbe/patchProbes/99.99/G"
df.to_hdf(h5FileN, hdfStruct, format='table')
```

### Issue Description

The above code snipsel is a part of a larger script which converts simulation data into a large hdf file with many `tables`.

The code runs on the same system with other simulation data. Furthe this script was used on another system (linux and macos) with slightly older versions of pandas. This work as well.

The hdf-file gets created, but it is empty and the script just hangs without any error message.

The example from the helppage for `to_hdf` does work, but not always, as you see in this screenshot:
![image](https://user-images.githubusercontent.com/3047695/155754119-c6e6f71d-304f-409f-b602-522c988b999a.png)

There is no error message; and killing with `Ctrl-c` does not working; only killing it with top.

I am not sure yet, when this happens.
Thank you in advance!

### Expected Behavior

writing and creating the hdf

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-1160.31.1.el7.x86_64
Version          : #1 SMP Thu Jun 10 13:32:12 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_GB.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.1
numpy            : 1.21.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.2
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : None
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by fab6** [comment]
btw. it is a centos 7 system

**Comment by mroeschke** [comment]
We would need a reproducible example for other to help diagnose: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by fab6** [comment]
yes, sorry
```
import pandas as pd
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]}, index=['a', 'b', 'c'])  
df.to_hdf('data.h5', key='df', mode='w')  
```
this is the one from 
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_hdf.html

**Comment by fab6** [comment]
I tried several different variants; with and without the `format` option, with `complevel` using something like 
```
store = pd.HDFStore(h5FileN)
store[hdfStruct]= df
```
or
```
store.append(hdfStruct, df)
```

**Comment by fab6** [comment]
for me the weird thing is that I do not get an error message and that the tiny example fails not consistently.

**Comment by fab6** [comment]
the test data set for the larger script works (just tested) on a different system with the same script;
I have no clue why, so I assume, that there is some weird setting on the system... is there some option which I can set to get more detailed debug information?

**Comment by fab6** [comment]
tried 
` exec env --ignore-environment /bin/sh
`
and loading conda  without success

**Comment by jreback** [comment]
this is almost certainly the local pytables installation and not a bug in pandas

**Comment by fab6** [comment]
ok, thank your for your help! I will see if it possible to install a different pytables version; do you have a better idea what to try out?

**Comment by fab6** [comment]
oh, crazy, just installed an older 3..6 python with pandas 1.1.5 and pytables 3.6.1, but still, I assume as well that it is my system, sorry for the trouble. Would be great to get any advice how to check what is going wrong...
