### ISSUE TITLE
ENH: Add typing support

### ISSUE THREAD

**Issue by Matheus-Rangel** [pandas-dev/pandas#46155]
#### Describe the solution you'd like
Add type the possibility to add type hints on Dataframes and Series. This would improve the readability of functions that are using dataframes.

```python
@dataclass
class Quote:
  id: str
  price: float
  submit_date: date

@dataclass
class PriceQuarter:
  price: float
  quarter: str

def get_max_price_by_quarter(quotes: DataFrame[Quote]) -> DataFrame[PriceQuarter]:
  ...
```

**Comment by mroeschke** [comment]
Thanks for the request. This is an ongoing effort in https://github.com/pandas-dev/pandas/issues/28142 and https://github.com/pandas-dev/pandas/issues/45253 and https://github.com/pandas-dev/pandas/issues/45252. Happy to have contributions over in those issue or pull requests to improve typing
