### ISSUE TITLE
Inconsistent comparisons between Series and 2-D ndarray

### ISSUE THREAD

**Issue by cpcloud** [pandas-dev/pandas#4615]
related: #4585 

```
In [5]: randn(10, 2) == Series(randn(2))
Out[5]:
array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]], dtype=bool)
```

but

```
In [6]: randn(10, 2) <= Series(randn(2))
```

throws an `Exception`.

got a PR in the works

**Comment by jbrockmendel** [comment]
In master (and 0.23.3) neither of the operations in the OP work; both raise with "Lengths must match to compare".

Is this something we want to support?

**Comment by mroeschke** [comment]
I think we've tightened up comparison ops with pandas object to ensure similar shape a while back to be more strict and not as flexible as this. Going to close but happy to reopen if there's more interest for this
