### ISSUE TITLE
BUG: KeyError in a multiindex with Timestamps

### ISSUE THREAD

**Issue by AlphaScorpii-dev** [pandas-dev/pandas#46189]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas
from pandas import Timestamp

myData = {'close': {('ACWI', Timestamp('2008-03-28 00:00:00+0000', tz='UTC')): 50.1,
  ('ACWI', Timestamp('2008-03-31 00:00:00+0000', tz='UTC')): 49.32,
  ('ACWI', Timestamp('2008-04-01 00:00:00+0000', tz='UTC')): 50.65,
  ('ACWI', Timestamp('2008-04-02 00:00:00+0000', tz='UTC')): 51.206,
  ('ACWI', Timestamp('2008-04-03 00:00:00+0000', tz='UTC')): 51.5},
 'high': {('ACWI', Timestamp('2008-03-28 00:00:00+0000', tz='UTC')): 50.1,
  ('ACWI', Timestamp('2008-03-31 00:00:00+0000', tz='UTC')): 50.0,
  ('ACWI', Timestamp('2008-04-01 00:00:00+0000', tz='UTC')): 50.65,
  ('ACWI', Timestamp('2008-04-02 00:00:00+0000', tz='UTC')): 51.4,
  ('ACWI', Timestamp('2008-04-03 00:00:00+0000', tz='UTC')): 59.7},
 'low': {('ACWI', Timestamp('2008-03-28 00:00:00+0000', tz='UTC')): 50.0999,
  ('ACWI', Timestamp('2008-03-31 00:00:00+0000', tz='UTC')): 49.32,
  ('ACWI', Timestamp('2008-04-01 00:00:00+0000', tz='UTC')): 50.16,
  ('ACWI', Timestamp('2008-04-02 00:00:00+0000', tz='UTC')): 51.05,
  ('ACWI', Timestamp('2008-04-03 00:00:00+0000', tz='UTC')): 50.95},
 'open': {('ACWI', Timestamp('2008-03-28 00:00:00+0000', tz='UTC')): 50.0999,
  ('ACWI', Timestamp('2008-03-31 00:00:00+0000', tz='UTC')): 50.0,
  ('ACWI', Timestamp('2008-04-01 00:00:00+0000', tz='UTC')): 50.25,
  ('ACWI', Timestamp('2008-04-02 00:00:00+0000', tz='UTC')): 51.12,
  ('ACWI', Timestamp('2008-04-03 00:00:00+0000', tz='UTC')): 59.7},
 'volume': {('ACWI', Timestamp('2008-03-28 00:00:00+0000', tz='UTC')): 200,
  ('ACWI', Timestamp('2008-03-31 00:00:00+0000', tz='UTC')): 400,
  ('ACWI', Timestamp('2008-04-01 00:00:00+0000', tz='UTC')): 600,
  ('ACWI', Timestamp('2008-04-02 00:00:00+0000', tz='UTC')): 10700,
  ('ACWI', Timestamp('2008-04-03 00:00:00+0000', tz='UTC')): 29100},
 'adjClose': {('ACWI',
   Timestamp('2008-03-28 00:00:00+0000', tz='UTC')): 37.8185964187,
  ('ACWI', Timestamp('2008-03-31 00:00:00+0000', tz='UTC')): 37.2298038997,
  ('ACWI', Timestamp('2008-04-01 00:00:00+0000', tz='UTC')): 38.2337706309,
  ('ACWI', Timestamp('2008-04-02 00:00:00+0000', tz='UTC')): 38.6534740163,
  ('ACWI', Timestamp('2008-04-03 00:00:00+0000', tz='UTC')): 38.8754035043},
 'adjHigh': {('ACWI',
   Timestamp('2008-03-28 00:00:00+0000', tz='UTC')): 37.8185964187,
  ('ACWI', Timestamp('2008-03-31 00:00:00+0000', tz='UTC')): 37.7431101983,
  ('ACWI', Timestamp('2008-04-01 00:00:00+0000', tz='UTC')): 38.2337706309,
  ('ACWI', Timestamp('2008-04-02 00:00:00+0000', tz='UTC')): 38.7999172839,
  ('ACWI', Timestamp('2008-04-03 00:00:00+0000', tz='UTC')): 45.0652735768},
 'adjLow': {('ACWI',
   Timestamp('2008-03-28 00:00:00+0000', tz='UTC')): 37.8185209325,
  ('ACWI', Timestamp('2008-03-31 00:00:00+0000', tz='UTC')): 37.2298038997,
  ('ACWI', Timestamp('2008-04-01 00:00:00+0000', tz='UTC')): 37.863888151,
  ('ACWI', Timestamp('2008-04-02 00:00:00+0000', tz='UTC')): 38.5357155125,
  ('ACWI', Timestamp('2008-04-03 00:00:00+0000', tz='UTC')): 38.4602292921},
 'adjOpen': {('ACWI',
   Timestamp('2008-03-28 00:00:00+0000', tz='UTC')): 37.8185209325,
  ('ACWI', Timestamp('2008-03-31 00:00:00+0000', tz='UTC')): 37.7431101983,
  ('ACWI', Timestamp('2008-04-01 00:00:00+0000', tz='UTC')): 37.9318257493,
  ('ACWI', Timestamp('2008-04-02 00:00:00+0000', tz='UTC')): 38.5885558668,
  ('ACWI', Timestamp('2008-04-03 00:00:00+0000', tz='UTC')): 45.0652735768},
 'adjVolume': {('ACWI', Timestamp('2008-03-28 00:00:00+0000', tz='UTC')): 200,
  ('ACWI', Timestamp('2008-03-31 00:00:00+0000', tz='UTC')): 400,
  ('ACWI', Timestamp('2008-04-01 00:00:00+0000', tz='UTC')): 600,
  ('ACWI', Timestamp('2008-04-02 00:00:00+0000', tz='UTC')): 10700,
  ('ACWI', Timestamp('2008-04-03 00:00:00+0000', tz='UTC')): 29100},
 'divCash': {('ACWI', Timestamp('2008-03-28 00:00:00+0000', tz='UTC')): 0.0,
  ('ACWI', Timestamp('2008-03-31 00:00:00+0000', tz='UTC')): 0.0,
  ('ACWI', Timestamp('2008-04-01 00:00:00+0000', tz='UTC')): 0.0,
  ('ACWI', Timestamp('2008-04-02 00:00:00+0000', tz='UTC')): 0.0,
  ('ACWI', Timestamp('2008-04-03 00:00:00+0000', tz='UTC')): 0.0},
 'splitFactor': {('ACWI',
   Timestamp('2008-03-28 00:00:00+0000', tz='UTC')): 1.0,
  ('ACWI', Timestamp('2008-03-31 00:00:00+0000', tz='UTC')): 1.0,
  ('ACWI', Timestamp('2008-04-01 00:00:00+0000', tz='UTC')): 1.0,
  ('ACWI', Timestamp('2008-04-02 00:00:00+0000', tz='UTC')): 1.0,
  ('ACWI', Timestamp('2008-04-03 00:00:00+0000', tz='UTC')): 1.0}}
dataframe = pandas.DataFrame.from_dict(myData)

# ensuring I take a datetime that is in the index
mydate = dataframe.index[3][1]
# works
print(dataframe.loc["ACWI",mydate])
# key error
print(dataframe.loc[slice(None),mydate])
```

### Issue Description

From my understanding of Multi-Index, I should be able to select data using the second index only.
I tried using slice(None), as well as .loc[: , mydate], but everytime I get a key error.

Here is the trace I have on my machine

> KeyError                                  Traceback (most recent call last)
> Input In [10], in <module>
> ----> 1 print(dataframe.loc[slice(None), mydate])
> 
> File ~\AppData\Local\miniforge3\envs\scientific\lib\site-packages\pandas\core\indexing.py:961, in _LocationIndexer.__getitem__(self, key)
>     959     if self._is_scalar_access(key):
>     960         return self.obj._get_value(*key, takeable=self._takeable)
> --> 961     return self._getitem_tuple(key)
>     962 else:
>     963     # we by definition only have the 0th axis
>     964     axis = self.axis or 0
> 
> File ~\AppData\Local\miniforge3\envs\scientific\lib\site-packages\pandas\core\indexing.py:1140, in _LocIndexer._getitem_tuple(self, tup)
>    1138 with suppress(IndexingError):
>    1139     tup = self._expand_ellipsis(tup)
> -> 1140     return self._getitem_lowerdim(tup)
>    1142 # no multi-index, so validate all of the indexers
>    1143 tup = self._validate_tuple_indexer(tup)
> 
> File ~\AppData\Local\miniforge3\envs\scientific\lib\site-packages\pandas\core\indexing.py:843, in _LocationIndexer._getitem_lowerdim(self, tup)
>     841 # we may have a nested tuples indexer here
>     842 if self._is_nested_tuple_indexer(tup):
> --> 843     return self._getitem_nested_tuple(tup)
>     845 # we maybe be using a tuple to represent multiple dimensions here
>     846 ax0 = self.obj._get_axis(0)
> 
> File ~\AppData\Local\miniforge3\envs\scientific\lib\site-packages\pandas\core\indexing.py:942, in _LocationIndexer._getitem_nested_tuple(self, tup)
>     939     axis -= 1
>     940     continue
> --> 942 obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)
>     943 axis -= 1
>     945 # if we have a scalar, we are done
> 
> File ~\AppData\Local\miniforge3\envs\scientific\lib\site-packages\pandas\core\indexing.py:1202, in _LocIndexer._getitem_axis(self, key, axis)
>    1200 # fall thru to straight lookup
>    1201 self._validate_key(key, axis)
> -> 1202 return self._get_label(key, axis=axis)
> 
> File ~\AppData\Local\miniforge3\envs\scientific\lib\site-packages\pandas\core\indexing.py:1153, in _LocIndexer._get_label(self, label, axis)
>    1151 def _get_label(self, label, axis: int):
>    1152     # GH#5667 this will fail if the label is not present in the axis.
> -> 1153     return self.obj.xs(label, axis=axis)
> 
> File ~\AppData\Local\miniforge3\envs\scientific\lib\site-packages\pandas\core\generic.py:3861, in NDFrame.xs(self, key, axis, level, drop_level)
>    3859 if axis == 1:
>    3860     if drop_level:
> -> 3861         return self[key]
>    3862     index = self.columns
>    3863 else:
> 
> File ~\AppData\Local\miniforge3\envs\scientific\lib\site-packages\pandas\core\frame.py:3505, in DataFrame.__getitem__(self, key)
>    3503 if self.columns.nlevels > 1:
>    3504     return self._getitem_multilevel(key)
> -> 3505 indexer = self.columns.get_loc(key)
>    3506 if is_integer(indexer):
>    3507     indexer = [indexer]
> 
> File ~\AppData\Local\miniforge3\envs\scientific\lib\site-packages\pandas\core\indexes\base.py:3623, in Index.get_loc(self, key, method, tolerance)
>    3621     return self._engine.get_loc(casted_key)
>    3622 except KeyError as err:
> -> 3623     raise KeyError(key) from err
>    3624 except TypeError:
>    3625     # If we have a listlike key, _check_indexing_error will raise
>    3626     #  InvalidIndexError. Otherwise we fall through and re-raise
>    3627     #  the TypeError.
>    3628     self._check_indexing_error(key)
> 
> KeyError: Timestamp('2008-04-01 00:00:00+0000', tz='UTC')

### Expected Behavior

I was expecting pandas to return me all the lines (here one only, but much more in my real data, one line for each ticker) that would match the datetime provided in .loc[ ].

### Installed Versions

pd.show_versions() raises an exception (perhaps because I'm running a Conda environment ?)
pd.__version__ returns 1.4.1
numpy itself is in 1.22.2

**Comment by phofl** [comment]
Hi, thanks for your report. Could you narrow this down to a couple of lines? Or are all of these lines necessary? An example should be minimal (see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)

**Comment by lukemanley** [comment]
In both of these cases `mydate` is targeting axis=1:

```
dataframe.loc["ACWI", mydate]
dataframe.loc[slice(None), mydate]
```

In order to target `mydate` in the second level of axis=0, you can wrap the two levels in a tuple:

```
dataframe.loc[("ACWI", mydate), :]
dataframe.loc[(slice(None), mydate), :]
```

**Comment by attack68** [comment]
agreed this seems to be syntax error in OP.

can reopen if necessary
