### ISSUE TITLE
DOC: provide detailed information about building the C extensions (development environment)

### ISSUE THREAD

**Issue by rendner** [pandas-dev/pandas#46205]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/development/contributing_environment.html#creating-a-development-environment

### Documentation problem

To setup a local development environment the user has to build the C extensions.
The current description contains minimal information about how to build the C extensions.

The information has already been expanded somewhat in PR #46055 ([updated docs](https://pandas.pydata.org/docs/dev/development/contributing_environment.html#creating-an-environment-using-docker)), but it would be helpful to provide more detailed information.

### Suggested fix for documentation

Extract the already existing information into a separate section.
In addition, the new section should provide the user with more detailed information on the following questions:

- Why do these need to be build?
- How to build?
- When do they need to be build or rebuild? 

The existing sections [Creating an environment using Docker](https://pandas.pydata.org/docs/development/contributing_environment.html#creating-an-environment-using-docker) and [Creating an environment without Docker](https://pandas.pydata.org/docs/development/contributing_environment.html#creating-an-environment-without-docker) should then refer to the newly created section.

**Comment by MarcoGorelli** [comment]
the docs have since been clarified a bit, and there's an ongoing effort to clarify them, so I think we can close this for now (though feel free to send a PR to clarify further if you wish, that'd be welcome)
