### ISSUE TITLE
QST: I HAVE 12 MONTHS DATA I  JUST WANT THE DATA FOR ONLY APRIL MONTH HOW CAN I DO IT

### ISSUE THREAD

**Issue by haritha1022** [pandas-dev/pandas#46237]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/71360038/i-have-12-months-data-in-a-excel-sheet-i-want-plt-a-graph-to-one-month

**Comment by haritha1022** [comment]
[sample.xlsx](https://github.com/pandas-dev/pandas/files/8190149/sample.xlsx)

**Comment by MarcoGorelli** [comment]
Please ask on StackOverflow, and read http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports
