### ISSUE TITLE
PERF: performance regression in assigning value to df[col_name]

### ISSUE THREAD

**Issue by Hubedge** [pandas-dev/pandas#46267]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this issue exists on the main branch of pandas.

### Reproducible Example

```python
import numpy as np
import pandas as pd
from tqdm import tqdm

df = pd.DataFrame(np.random.random((5000,15000)))
df.columns = df.columns.astype("str")
col_0_np = df.iloc[:, 0].to_numpy()

for idx in tqdm(df.columns):
    df[idx] = col_0_np
```

```
  0%|          | 20/15000 [00:04<57:50,  4.32it/s] 
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.8.12.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : ***

pandas           : 1.4.1
numpy            : 1.19.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.2
setuptools       : 58.0.4
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.8.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.2
IPython          : 7.31.1
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : 1.3.2
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.1
numba            : 0.54.1
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.2
sqlalchemy       : 1.4.27
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : None

</details>

### Prior Performance

In `1.3.5`, the code should complete within seconds.

**Comment by Hubedge** [comment]
Works fine if switching to `df.loc[:, idx] = col_0_np`:
```python
import numpy as np
import pandas as pd
from tqdm import tqdm

df = pd.DataFrame(np.random.random((5000,15000)))
df.columns = df.columns.astype("str")
col_0_np = df.iloc[:, 0].to_numpy()

for idx in tqdm(df.columns):
    df.loc[:, idx] = col_0_np
```

```
100%|██████████| 15000/15000 [00:04<00:00, 3246.66it/s]
```

**Comment by phofl** [comment]
The performance regression is caused by a change in behavior underneath. Before 1.4 the setitem operation wrote into the underlying numpy array in place -> if you do

```
na = np.random.random((2,15))
df = pd.DataFrame(na)
df.columns = df.columns.astype("str")
col_0_np = df.iloc[:, 1].to_numpy()
df[df.columns[0]] = col_0_np
```

na was changed after the setitem call. This makes now a copy of the underlying array, hence the slowdown. If this is not relevant for you, I would suggest using loc. I am not sure if we can speed this up easily

cc @jbrockmendel

**Comment by Hubedge** [comment]
@phofl 

In this case whether the original `na` is modified is not relevant, but I'm curious the motivation to make the change, because I would assume people are more used to setitem than to loc. Can you share the link to the discussion, if any?

**Comment by phofl** [comment]
That might have been misleading on my side.

Setitem was supposed to make a copy while loc was supposed to operate inplace. Before 1.4 this was inconsistent based on the code paths this was running through. This should be more consistent now, hence the change above. Technically speaking, the fact that this was modifying the underlying array before 1.4 was a bug.

**Comment by jbrockmendel** [comment]
https://github.com/pandas-dev/pandas/blob/main/doc/source/whatsnew/v1.3.0.rst#never-operate-inplace-when-setting-framekeys--values

`df.loc[:, foo] = bar` tries to write into the existing array(s), so should be fast (though we're still not totally consistent about this xref #45333).  `df[foo] = bar` will _never_ write into the existing array(s).

I think there may be a perf improvement available by changing `Block.delete` to not call np.delete.  Not sure if that'd be relevant here.

**Comment by phofl** [comment]
Yeah that would help. Most of the time is spent in np.delete

**Comment by lbittarello** [comment]
It's also worth noting that it's difficult to use `.loc` when chaining operations, unlike `assign`, so it can be a lot clunkier.

**Comment by simonjayhawkins** [comment]
removing from 1.4.x milestone
