### ISSUE TITLE
ENH: to_clipboard(as="html" | "markdown" | "latex" | ...)

### ISSUE THREAD

**Issue by janosh** [pandas-dev/pandas#46269]
#### Is your feature request related to a problem?

When writing papers, it's often useful to be able to copy dataframes into documents as Markdown, HTML or LaTeX.

#### Describe the solution you'd like

Allow more formats besides `excel: bool` in [`DataFrame.to_clipboard()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_clipboard.html). For example, a new keyword `as`:

```py
df.to_clipboard(as="html" | "markdown" | "latex" | ...)
```

#### API breaking implications

Pure extension unless `excel` keyword of `to_clipboard()` was removed in favor of `as`.

#### Describe alternatives you've considered

The other option would be allowing the `buf` argument of `df.to_(html|markdown|latex|...)` to take the string `"clipboard"`: 

```py
df.to_markdown(buf="clipboard")
```

**Comment by jreback** [comment]
all of these exist already as methods 

why should .to_clipboard support this?

**Comment by janosh** [comment]
Like I said, to copy dataframes into text documents...

> all of these exist already as methods

They don't chain, right? How do I get `df.to_html()` into the clipboard?

**Comment by jreback** [comment]
what does that even mean?

**Comment by wany-oh** [comment]
It seems that `clipboard_set()` can be used.

```python
import pandas as pd
from pandas.io.clipboard import clipboard_set

df = pd._testing.makeMixedDataFrame()

clipboard_set(df.to_html())
clipboard_set(df.to_latex())
clipboard_set(df.to_markdown())
...
clipboard_set(str(df))  # It can copy anything of type str
```

**Comment by janosh** [comment]
@wany-oh Thanks, that works great!

> what does that even mean?

@jreback Which part is unclear?

**Comment by attack68** [comment]
`clipboard_set` is used within `DataFrame.to_clipboard`.

I would hazard that `to_clipboard` might have been coded before the other formats, html, laTex etc became available. It seems to be a simple extension to change `excel={True, False}` to something like `format={"excel", "str", "html", "latex"}` and to call the relevant renderer.
