### ISSUE TITLE
BUG: join does not always honor the `rsuffix` argument

### ISSUE THREAD

**Issue by mlohbihler** [pandas-dev/pandas#46281]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
>>> print(pd.__version__)
1.4.1
>>> 
>>> df1 = pd.DataFrame([[1], [2], [3]], index=['a', 'b', 'c'], columns=['val'])
>>> df2 = pd.DataFrame([[4], [5], [6]], index=['a', 'b', 'd'], columns=['val'])
>>> df3 = pd.DataFrame([[7], [8], [9]], index=['b', 'c', 'd'], columns=['val'])
>>> df4 = pd.DataFrame([[10], [11], [12]], index=['a', 'd', 'f'], columns=['val'])
>>> df5 = pd.DataFrame([[13], [14], [15]], index=['a', 'b', 'd'], columns=['val'])
>>> 
>>> df = (df1.join(df2, how='outer', lsuffix='_1', rsuffix='_2')
...       .join(df3, how='outer', rsuffix='_3')
...       .join(df4, how='outer', rsuffix='_4')
...       .join(df5, how='outer', rsuffix='_5')
...      )
>>> df
   val_1  val_2  val  val_4  val_5
a    1.0    4.0  NaN   10.0   13.0
b    2.0    5.0  7.0    NaN   14.0
c    3.0    NaN  8.0    NaN    NaN
d    NaN    6.0  9.0   11.0   15.0
f    NaN    NaN  NaN   12.0    NaN
>>>
```

### Issue Description

The third data frame join does not honor the given `rsuffix`. Note in the column names in the given example that they third column does not have a `_3` suffix.

The above was run on the following: `docker pull amancevice/pandas`

### Expected Behavior

All of the columns in the above example should have a `_<n>` suffix.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.47-linuxkit
Version          : #1 SMP Sat Jul 3 21:51:47 UTC 2021
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.1
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
</details>

**Comment by phofl** [comment]
Hi, thanks for your report.

This works as intended. After your first join, you get two columns, ``val_1`` and ``val_2``. When performing the second join, there are not duplicates, hence r_suffix is not needed

**Comment by mlohbihler** [comment]
Thanks for your explanation.

This is surprising behaviour. It was inexplicable to my team and I. Considering the `rsuffix` option is optional, we had expected that if it is specified it would be set. It is kind of a nuisance for it not to be since to get column naming consistent one has to explicitly rename the one remaining unsuffixed column.

**Comment by phofl** [comment]
The documentation says:

``Suffix to use from right frame’s overlapping columns.``

Hence, this is only used if there are overlapping columns

**Comment by mlohbihler** [comment]
Yeah, i saw that. Still surprising.
