### ISSUE TITLE
ENH: read_sas(..., format='sas7bdat') to handle page type 16384 ("metc")

### ISSUE THREAD

**Issue by MarkPundurs** [pandas-dev/pandas#46293]
#### Is your feature request related to a problem?

`read_sas(..., format='sas7bdat')` fails to read files with page type 16384 ("metc"). pandas defines a page type constant `page_metc_type` (https://github.com/pandas-dev/pandas/blob/main/pandas/io/sas/sas_constants.py#L59) but doesn't use it in the code (https://github.com/pandas-dev/pandas/blob/main/pandas/io/sas/sas7bdat.py#L413).

#### Describe the solution you'd like

Enhance the sas7bdat.py code to handle `page_metc_type`.

**Comment by phofl** [comment]
Can you please provide a sas file with the specific format? Since this is a proprietary software, we can not easily create them ourselves.
