### ISSUE TITLE
BUG: ZeroDivisionError when dividing a DataFrame by 0 when dtype is object

### ISSUE THREAD

**Issue by chrisprobably** [pandas-dev/pandas#46292]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

I get a ZeroDivisionError when running the following:

```python
import pandas as pd
pd.DataFrame([[1.0, 2.0]]).astype('object') / 0
```

I would expect instead for the no error to be raised and the resulting values to be `Inf`.

Stacktrace:

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.9/site-packages/pandas/core/ops/common.py", line 70, in new_method
    return method(self, other)
  File ".../python3.9/site-packages/pandas/core/arraylike.py", line 124, in __truediv__
    return self._arith_method(other, operator.truediv)
  File ".../python3.9/site-packages/pandas/core/frame.py", line 6940, in _arith_method
    new_data = self._dispatch_frame_op(other, op, axis=axis)
  File ".../python3.9/site-packages/pandas/core/frame.py", line 6967, in _dispatch_frame_op
    bm = self._mgr.apply(array_op, right=right)
  File ".../python3.9/site-packages/pandas/core/internals/managers.py", line 302, in apply
    applied = b.apply(f, **kwargs)
  File ".../python3.9/site-packages/pandas/core/internals/blocks.py", line 402, in apply
    result = func(self.values, **kwargs)
  File ".../python3.9/site-packages/pandas/core/ops/array_ops.py", line 222, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)
  File ".../python3.9/site-packages/pandas/core/ops/array_ops.py", line 163, in _na_arithmetic_op
    result = func(left, right)
  File ".../python3.9/site-packages/pandas/core/computation/expressions.py", line 239, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File ".../python3.9/site-packages/pandas/core/computation/expressions.py", line 69, in _evaluate_standard
    return op(a, b)
ZeroDivisionError: float division by zero
```

### Issue Description

When dividing a DataFrame of floats as type object by 0 I unexpectedly get a ZeroDivisionError. 

### Expected Behavior

Expected behaviour is the same as if the dtypes were float i.e. a DataFrame of Inf.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.0.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
Version          : Darwin Kernel Version 19.6.0: Thu Jan 13 01:26:33 PST 2022; root:xnu-6153.141.51~3/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.4.1
numpy            : 1.22.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 20.2.4
setuptools       : 50.3.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by mroeschke** [comment]
Thanks for the report. This follows the numpy behavior which pandas is backed by therefore the consistency is expected. Closing

```
In [7]: np.array([[1.0, 2.0]], dtype=object) / 0
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-7-c1972435095f> in <module>
----> 1 np.array([[1.0, 2.0]], dtype=object) / 0

ZeroDivisionError: float division by zero
```
