### ISSUE TITLE
BUG:  "data type 'Int64' not understood"

### ISSUE THREAD

**Issue by TouriM** [pandas-dev/pandas#46298]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame(data={"test": [20.222, 1.01]})
df['test'][1].round(0).astype("Int64")

<details>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [3], in <cell line: 3>()
      1 import pandas as pd
      2 df = pd.DataFrame(data={"test": [20.222, 1.01]})
----> 3 df['test'][1].round(0).astype("Int64")

TypeError: data type 'Int64' not understood
</details>
```

### Issue Description

While investigating another problem with Int64, I ran into this unexpected behaviour. 

Casting to int64 works:
```python
>>> import pandas as pd
>>> df = pd.DataFrame(data={"test": [20.222, 1.01]})
>>> df['test'][1].round(0).astype("int64")
1
```

Slicing works:
```python
>>> import pandas as pd
>>> df = pd.DataFrame(data={"test": [20.222, 1.01]})
>>> df['test'][1:2].round(0).astype("Int64")
1    1
Name: test, dtype: Int64
```

df['test'].round(0).astype("Int64")

### Expected Behavior

I would expect, that Int64 would return "1" in the 

```python
>>> import pandas as pd
>>> df = pd.DataFrame(data={"test": [20.222, 1.01]})
>>> df['test'][1].round(0).astype("Int64")
 1   # Would be the result I expect
```

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.10.2.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.3.0
Version          : Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.4.1
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.0.4
setuptools       : 58.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.1.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.4.31
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
</details>

**Comment by jreback** [comment]
you are trying to astype a numpy value (not series) so this isn't going to work

**Comment by mroeschke** [comment]
Just to show the example

```
In [1]: df = pd.DataFrame(data={"test": [20.222, 1.01]})
   ...: df['test'][1]
Out[1]: 1.01

In [2]: type(df['test'][1])
Out[2]: numpy.float64
```

Closing as these scalars don't have `astype` as expected

**Comment by TouriM** [comment]
Okay, I looked into In64 a bit more. I was in the wrong believe that it would be a drop-in for int64  with null values.
But I as it is an extension based on arrays... this makes sense.  Thus there will be different behaviours, besides the null-values, between int64 and Int64.
