### ISSUE TITLE
ENH: Convert a string column of times (hour:min) to datetime without date

### ISSUE THREAD

**Issue by Hadi2525** [pandas-dev/pandas#46291]
I have the following `df`:

```
import pandas as pd
df = pd.DataFrame(['12:53','13:00','13:11','14:45'],columns = 'Time')
df = pd.to_datetime(df, format = '%H:%M')
```
The output is:
```
>>> df
Time:
1900-01-01 12:53:00
1900-01-01 13:00:00
1900-01-01 13:11:00
1900-01-01 14:45:00
```

Is there a way to remove dates from rows in `df`? Perhaps, a method or attribute be added like `date = None`?

**Comment by norisa118** [comment]
take

**Comment by norisa118** [comment]
Hi @sinhrks, I'm new to open source and looking to contribute to this! Is there anything I need to take into account besides assigning myself to this to start working on this issue? I see that this issue still needs triaging.

**Comment by mroeschke** [comment]
There's `pandas.core.tools.to_time` that can parse times which seems to be what you want. Needs to be exposed properly which is referenced in https://github.com/pandas-dev/pandas/issues/11947 so closing in favor of that issue
