### ISSUE TITLE
Use pandas.io.formats.style.Styler.background_gradient at Python 3.7.0

### ISSUE THREAD

**Issue by JiaxiangBU** [pandas-dev/pandas#46303]
#### Is your feature request related to a problem?

[this should provide a description of what the problem is, e.g. "I wish I could use pandas to do [...]"]

I read the package [document](pandas.io.formats.style.Styler.background_gradient.html) for the function `pandas.io.formats.style.Styler.background_gradient`, I find the argument `gmap` available in verison 1.3.0. If I want to upgrade pandas to 1.3.0, this version will require the python > 3.7.1. 

However, my cloud server only supports the python under 3.7.0. 

#### Describe the solution you'd like

[this should provide a description of the feature request, e.g. "`DataFrame.foo` should get a new parameter `bar` that [...]", try to write a docstring for the desired feature]

Any other solution I can use the function `pandas.io.formats.style.Styler.background_gradient` or similar ones at python under 3.7.0. 

#### API breaking implications

[this should provide a description of how this feature will affect the API]

#### Describe alternatives you've considered

[this should provide a description of any alternative solutions or features you've considered]

#### Additional context

[add any other context, code examples, or references to existing implementations about the feature request here]

```python
# Your code here, if applicable

```

**Comment by phofl** [comment]
We use the numpy support policy for  python versions (see https://numpy.org/neps/nep-0029-deprecation_policy.html). 

We dropped 3.7 in 1.4 so this won't be possible, sorry.
