### ISSUE TITLE
ENH: merging using DataFrame index should raise a warning or ValueError if the dtype of the indices don't match

### ISSUE THREAD

**Issue by jloxh** [pandas-dev/pandas#46305]
DataFrame `merge` has inconsistent behaviour depending on whether joining using the index or using columns. This means the user might experience unexpected results when using the `merge` method.

For a minimal example, consider that the following:

```python
import pandas as pd
df_a = pd.DataFrame({'a': 1}, index=[1])
df_b = pd.DataFrame({'c': 1}, index=['1'])
df_c = df_a.merge(df_b, left_index=True, right_index=True)
```

will result in `df_c` being an empty DataFrame with pandas `1.3.5`.

_However_, attempting to perform a similar operation but using named columns:

```python
import pandas as pd
df_a = pd.DataFrame({'a': 1, 'index': '1'}, index=[1])
df_b = pd.DataFrame({'index': 1, 'c': 1}, index=[1])
df_c = df_a.merge(df_b, left_on='index', right_on='index')
```

will produce the appropriate `ValueError` (since the dtypes of the target columns do not match).

**Desired Behaviour:**
It would be helpful to issue either some type of warning or a `ValueError` (consistent with the case using named columns) when attempting to merge on an index/indices with different dtypes.

**Comment by mroeschke** [comment]
Thanks for the request but it appears this hasn't gotten traction in a while so closing
