### ISSUE TITLE
ENH: Add `subset` param to `add_(pre|suf)fix`

### ISSUE THREAD

**Issue by janosh** [pandas-dev/pandas#46310]
#### Is your feature request related to a problem?

I would like to add suffixes to only to a subset of columns.

#### Describe the solution you'd like

```py
df.add_suffix('foo', subset=['col1', 'col2'])
```

Could potentially implement an API similar to `df.filter`, i.e. `subset` could accept besides a list of column names the following types: `regex='str' | like='str' | callable: col_name => bool`.

#### API breaking implications

Nothing breaking.

**Comment by jreback** [comment]
-1 on changing these methods at all

in fact we have an issue about deprecating these entirely

**Comment by mroeschke** [comment]
Thanks for the request but agreed especially since we have discussion deprecating this API. Closing
