### ISSUE TITLE
BUG: Upgrading to pandas version 1.4.0 or 1.4.1 causes a call to the method .at[idx, "XXX"] to generate an InvalidIndexError

### ISSUE THREAD

**Issue by pierrebaudot** [pandas-dev/pandas#46315]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
df.at[(df_patient.columnx == something),"columny']= something
```

### Issue Description

Upgrading to pandas version 1.4.0 or 1.4.1 causes a call to the method .at[idx, "XXX"] to generate an InvalidIndexError
see :

https://stackoverflow.com/questions/71293357/upgrading-to-pandas-version-1-4-0-or-1-4-1-causes-a-call-to-the-method-atidx/71431430#71431430

for more information
The error is reproducible since we are at least two that got it. 

### Expected Behavior

Expected working as in version 1.3.5

### Installed Versions

<details>

1.4.1

</details>

**Comment by phofl** [comment]
Your example has at least one typo

please provide a reproducible example that we can copy and paste.

Without the underlying DataFrame we can not reproduce your bug

**Comment by pierrebaudot** [comment]
yes sorry
df.at[(df.columnx == something),"columny']= something
I will not reproduce the error further since i could fixed it after quite sometime by downgrading pandas to 1.3.5.

**Comment by phofl** [comment]
Closing in this case, if you can not provide a reproducible example, we can not investigate
