### ISSUE TITLE
Bug: Dataframe.apply on Empty Dataframe Return a Dataframe instead of Series

### ISSUE THREAD

**Issue by eric-zhu-uw** [pandas-dev/pandas#46356]
Hi,

Not 100% if this is a bug or the intended behaviour but when you use `df.apply` on an empty dataframe, it returns `pd.Dataframe` however, when you use `df.apply` on a non-empty dataframe, it returns `pd.Series`. This has caused me issues where I need to check if a dataframe is empty befored deciding whether or not to use the `df.apply` function. I have provided an example below.

```
df1 = pd.DataFrame([{'a': 1, 'b': 2}], columns=['a', 'b'])
df2 = pd.DataFrame([], columns=['a', 'b'])

print(type(df1.apply(lambda row: row.b, axis=1)))
print(type(df2.apply(lambda row: row.b, axis=1)))

type(df1.apply(lambda row: row.b, axis=1)) == type(df2.apply(lambda row: row.b, axis=1))
```

**Comment by eric-zhu-uw** [comment]
@mroeschke Do you know what the process is to get a bug fix. Does it have to get approved before I make a pull request to fix it (_don't want to spend time fixing it if it's the intended behaviour_)?

**Comment by mroeschke** [comment]
It appears to be a bug so submitting a pull request is the best way to get more visibility

**Comment by jwiaduck** [comment]
take

**Comment by eric-zhu-uw** [comment]
Tried this on version `2.2.0.dev` and it seems like it's resolved and always returns `pandas.core.series.Series` now.
