### ISSUE TITLE
BUG: where method results in a different outputs with "object" and "string" dtypes

### ISSUE THREAD

**Issue by Leejung8763** [pandas-dev/pandas#46366]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
df = pd.DataFrame({'A':["1","","3"]}, dtype="object")
df.where(df!="", np.nan, inplace=True)

df = pd.DataFrame({'A':["1","","3"]}, dtype="string")
df.where(df!="", np.nan, inplace=True)
```

### Issue Description

I am getting different results when using the where method with different data type which are "object" and "string".

### Expected Behavior

First, consider the dataframe with "object" and `inplace=True` options.

Then, I got a result that I expected.

```
df = pd.DataFrame({'A':["1","","3"]}, dtype="object")
df.where(df!="", np.nan, inplace=True)
    a
0   1
1   NaN
2   3
```

But, when I changed the dtypes "object" to "string", I got different result as below.

```
df = pd.DataFrame({'A':["1","","3"]}, dtype="string")
df.where(df!="", np.nan, inplace=True)
    A
0   <NA>
1   
2   <NA>
```

### Installed Versions

<details>

pandas version: 1.3.5 , numpy version: 1.19.5

</details>

**Comment by SeanRBurton** [comment]
Can I try tackling this?

**Comment by SeanRBurton** [comment]
I am unable to replicate this with master. I get the behavior that you report for "object" in both cases.

**Comment by mroeschke** [comment]
Yeah I believe this was address in 1.4 so closing
