### ISSUE TITLE
QST: How to make LateX table headers enclosed in {} from pandas.style.to_latex()

### ISSUE THREAD

**Issue by MR-T77** [pandas-dev/pandas#46373]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/71481868/how-to-make-pandas-style-to-latex-output-header-fields-enclosed-in

### Question about pandas

Up until recently the output of pandas.style_to_latex() had the table header contents enclosed in {}.

Output from Styler.to_latex() (Latex Code and Image)

    \begin{table}[H]
    \centering
    \begin{tabular}{llrr}
    \toprule
    {} & {} & {F-1} & {F-2} \\
    {dataset} & {Model} & {} & {} \\
    \midrule
    \multirow[c]{2}{*}{G} & Baseline & 5.824811 & 5.804303 \\
     & Version2 & 5.824811 & 5.804303 \\
    \multirow[c]{2}{*}{H} & Baseline & 4.677066 & 4.570626 \\
     & Version2 & 4.801857 & 4.660115 \\
    \multirow[c]{2}{*}{S} & Baseline & 2.406244 & 1.921260 \\
     & Version2 & 2.719123 & 2.189293 \\
    \multirow[c]{2}{*}{T} & Baseline & 5.284241 & 4.949087 \\
     & Version2 & 5.931376 & 5.909215 \\
    \bottomrule
    \end{tabular}
    \end{table}

I'm not exactly sure if there was any change to my code that had this side effect, or if I may have updated pandas, but now the header contents are not enclosed in {} (showing only the header part of the table).

    \begin{table}[H]
        \centering
        \begin{tabular}{llrr}
        \toprule
          &          &   F-1 &   F-2 \\
        dataset & Model &       &       \\
        \midrule

As I have some post-processing of the tables built into python that makes use of the `{}`, is there any way I can output the header with `{}`?

**Comment by attack68** [comment]
two ways,

```
df.style.to_latex(siunitx=True)
```
(since siunitx package requires this formatting)

or

```
df.style.format_index("{{{0}}}", axis=1).to_latex()
```
(explicitly using the format function to control the output)
