### ISSUE TITLE
BUG: pandas.io.formats.style.Styler.to_excel doesn't support storage_options as its documented

### ISSUE THREAD

**Issue by jcunhafonte** [pandas-dev/pandas#46381]
### Pandas version checks

- [x] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

bigdf = pd.DataFrame(np.random.randn(16, 100))
file = bigdf.style.set_sticky(axis="index")
file.to_excel('file.xlsx', storage_options=dict())
```

### Issue Description

[pandas.io.formats.style.Styler.to_excel](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.io.formats.style.Styler.to_excel.html) method documents the support of the parameter `storage_options` since version `1.2.0`, however when defined it raises the following error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [40], in <module>
----> 1 file.to_excel('file.xlsx', storage_options=dict())

TypeError: to_excel() got an unexpected keyword argument 'storage_options'
```

When checking the source code of the `main` branch the method is documented [here](https://github.com/pandas-dev/pandas/blob/fb3e3e60963ae4808ce976fc0f89864122eced15/pandas/io/formats/style.py#L549). However the parameter is not defined in the method.

### Expected Behavior

The referred method should accept `storage_options` as DataFrame [to_excel](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_excel.html?highlight=to_excel#pandas.DataFrame.to_excel) method supports.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.3.0
Version          : Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.4.1
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 60.5.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.0.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : 2022.02.0
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : 2022.02.0
scipy            : 1.8.0
sqlalchemy       : None
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by attack68** [comment]
Styler.to_excel, re-uses the doc string from DataFrame.to_excel but doesn't actually implement it.

Should changes docs or try to find a more generally reuseable solution.

**Comment by edwhuang23** [comment]
Hi, I would be interested in taking this issue. Is this still something that needs a change?

**Comment by attack68** [comment]
yes. PRs will be linked to this issue, since there are no linked PRs it is still outsanding issue.

**Comment by ben-feldstein** [comment]
take

**Comment by eshirvana** [comment]
isn't this method `[style.Styler.to_excel](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.io.formats.style.Styler.to_excel.html?highlight=to_excel#pandas.io.formats.style.Styler.to_excel)` which is different from `DataFrame.to_excel`.
and in style.Styler.to_excel documentation correctly shows we don't have `storage_options` option
so is it a real bug?

**Comment by eshirvana** [comment]
@attack68 I'm looking at doc 1.4.1 and looks ok to me , the link in the original post goes to DataFrame.to_excel docs despite the title is [pandas.io.formats.style.Styler.to_excel]

**Comment by attack68** [comment]
if you read the issue description by the oroginal poster at the top of thread it describes the issue exactly and I agree with his assessment
