### ISSUE TITLE
TYP: Got mypy error  No overload variant of "add" of "Timestamp" matches argument type "DateOffset"

### ISSUE THREAD

**Issue by Prabhat-Thapa45** [pandas-dev/pandas#46390]
# Sample code reproducing error

````
import pandas as pd


class RunConfigs:
    def __hash__(self) -> int:
        return hash(str(self))

    horizon_date: pd.Timestamp


def fun(run_config: RunConfigs) -> list:
    if run_config.horizon_date + pd.DateOffset(days=366):
        return []
    else:
        return ["fsd"] 
````

# Error 
sam.py199: note:  error: No overload variant of "__add__" of "Timestamp" matches argument type "DateOffset"  [operator]
        if run_config.horizon_date + pd.DateOffset(days=366):
           ^
src\sam.py199: note: Possible overload variants:
src\sam.py199: note:     def __add__(self, ndarray[Any, Any]) -> ndarray[Any, Any]
src\sam.py199: note:     def __add__(self, Union[timedelta, timedelta64]) -> Timestamp

````

**Comment by twoertwein** [comment]
Thank you @Prabhat-Thapa45 for testing the type annotations!

It seems that this is already fixed in main, I believe with this overload https://github.com/pandas-dev/pandas/blob/e7a0cf3ba098c0074a4462522da5c7fdca804c78/pandas/_libs/tslibs/offsets.pyi#L58 in BaseOffset (super-class of DateOffset).

**Comment by twoertwein** [comment]
@Dr-Irv Since pandas has not yet type tests, it might be good to add it to the MS stub tests.

**Comment by mroeschke** [comment]
Sounds like this is fixed and will be handed in pandas-stubs so closing
