### ISSUE TITLE
Add `index` param to `to_dict` like in `to_json`.

### ISSUE THREAD

**Issue by pavelkomarov** [pandas-dev/pandas#46398]
`df.to_json(orient='split', index=False)` is really nice. `df.to_dict(orient='split')` basically does the same thing, but I get a dictionary back instead of a string. For symmetry, I'd like `to_dict` to also have an `index` param, so I can keep from having to `del dictionary['index']` to make them really similar.

**Comment by vruthik** [comment]
Would love to attempt this

**Comment by vruthik** [comment]
take

**Comment by rhshadrach** [comment]
> but I get a dictionary back instead of a string

I'm not sure I follow what the expectation is here. But in any case, I'm +1 in adding index for API consistency with other `DataFrame.to_*` methods.
