### ISSUE TITLE
BUG: Pandas isn't able to read compressed file from sftp server

### ISSUE THREAD

**Issue by Mustafasavran** [pandas-dev/pandas#46402]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import pysftp

cnopts = pysftp.CnOpts()
with pysftp.Connection(
        host=hostname,
        port=port,
        username=username,
        password=password,
        cnopts=cnopts,
    ) as sftp:
        with sftp.open(path, 'rb') as dst_file:
            
            df = pd.read_csv(
                dst_file, compression = "zip")

            print(df)
```

### Issue Description

I am trying to read compressed file from a sftp server but I encountered an issue that when I open the file and give the file like object to pandas in localhost without using any sftp library, It is working well but when I try to do the same thing on sftp. It  gives this error:
    
    File "pandas/_libs/parsers.pyx", line 817, in pandas._libs.parsers.TextReader.read_low_memory
    File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._read_rows
    File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader._tokenize_rows
    File "pandas/_libs/parsers.pyx", line 1960, in pandas._libs.parsers.raise_parser_error
    pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 6, saw 2

I tried zip and gzip files , they both give an error.

### Expected Behavior

Read compressed file without any error

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.10.0.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.16.3-microsoft-standard-WSL2
Version          : #1 SMP Fri Apr 2 22:23:49 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.1
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : None
setuptools       : None
Cython           : 0.29.28
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.31.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.24
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
zstandard        : None

</details>

**Comment by twoertwein** [comment]
The error seems to indicate that there are two columns in row 6 but it expected only one. Which error do you get when you add `engine="python"`?

I think fsspec supports SFTP, you could probably use `pd.read_csv("sftp://path", ..., storage_options={...})`.

Is there a public file on an SFTP server to reproduce this?

**Comment by twoertwein** [comment]
another debug option could be to use

```py
from io import BytesIO

pd.read_csv(BytesIO(dst_file.read()), compression="zip")
```

If this fails, then there should be something wrong with the file.

**Comment by Mustafasavran** [comment]
> another debug option could be to use
> 
> ```python
> from io import BytesIO
> 
> pd.read_csv(BytesIO(dst_file.read()), compression="zip")
> ```
> 
> If this fails, then there should be something wrong with the file.



> 

Thanks for the answer , when I add engine = "python", It gives this error:
  pandas.errors.ParserError: iterator should return strings, not bytes (the file should be opened in text mode)

when I open the file with "r" instead of "rb" it gives:
  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9b in position 12: invalid start byte

When I pass url as a parameter urllib didn't recognize sftp url type and give this error:
  urllib.error.URLError: <urlopen error unknown url type: sftp>

There is no public file available right now but I find anything to test I will share.

**Comment by Mustafasavran** [comment]
> The error seems to indicate that there are two columns in row 6 but it expected only one. Which error do you get when you add `engine="python"`?
> 
> I think fsspec supports SFTP, you could probably use `pd.read_csv("sftp://path", ..., storage_options={...})`.
> 
> Is there a public file on an SFTP server to reproduce this?

Thanks for the answer , when I add engine = "python", It gives this error:
`pandas.errors.ParserError: iterator should return strings, not bytes (the file should be opened in text mode)`

when I open the file with "r" instead of "rb" it gives:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9b in position 12: invalid start byte`

When I pass url as a parameter urllib didn't recognize sftp url type and give this error:
`urllib.error.URLError: <urlopen error unknown url type: sftp>`


There is no public file available right now but I find anything to test I will share.

**Comment by Mustafasavran** [comment]
> another debug option could be to use
> 
> ```python
> from io import BytesIO
> 
> pd.read_csv(BytesIO(dst_file.read()), compression="zip")
> ```
> 
> If this fails, then there should be something wrong with the file.

Thanks for the answer, as I said before when I open the file normally ( I mean like open("data_path","rb")) and give it to read_csv function, it is working clearly but when I do the same via pysftp, it gives error.

This solution works but we have big zip files and It isn't a good way to store whole file in memory. I need to read the files chunk by chunk

**Comment by twoertwein** [comment]
Thank you for testing the different alternatives! I assume that `dst_file.mode` does not exist (or if it exists it, it doesn't contain "b"). Pandas needs to infer whether the file-like object is opened in binary or text mode, without `.mode` it tends to assume text mode (unless it is a sub-class of well-known to be binary classes).

Is it possible to do `dst_file.mode = 'rb'` before calling read_csv? Or wrapping this object and add a mode property?

If has no mode, I would recommend opening an issue at the sftp library you are using. You are also more than welcome to open a PR here to add a `mode` argument to `read_csv` (we already have that for `to_csv`).

**Comment by twoertwein** [comment]
> Well, Using fsspec instead of pysftp solved my issue. However There is a conflict between pandas and pysftp and it remains.

I assume fsspec adds `.mode`

**Comment by Mustafasavran** [comment]
> > Well, Using fsspec instead of pysftp solved my issue. However There is a conflict between pandas and pysftp and it remains.
> 
> I assume fsspec adds `.mode`

Adding  dst_file.mode = "rb" before read_csv worked like a charm. Appreciate your help.

**Comment by mroeschke** [comment]
Closing as it appears the issue was fixed
