### ISSUE TITLE
ENH: resample.sum documents a numeric_only argument

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#46442]
https://pandas.pydata.org/docs/reference/api/pandas.core.resample.Resampler.sum.html

The parameters listed there include `numeric_only` though it is not in the function signature, and not implemented currently.

@mroeschke - is the right action here just to remove it from the docs?

**Comment by mroeschke** [comment]
Yes, I would say if the function doesn't accept this argument then `numeric_only` can just be removed from the docstring

**Comment by rhshadrach** [comment]
Similar to #46524, I think it'd be better to instead add numeric_only.
