### ISSUE TITLE
DOC: converting Index object with duplicate entries into a set

### ISSUE THREAD

**Issue by kwhkim** [pandas-dev/pandas#46440]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

from https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#selecting-random-samples,
in section "Index objects", it reads "The pandas [Index](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.html#pandas.Index) class and its subclasses can be viewed as implementing an ordered multiset. Duplicates are allowed. However, **if you try to convert an [Index](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.html#pandas.Index) object with duplicate entries into a set, an exception will be raised**."

### Documentation problem

from https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#selecting-random-samples,
in section "Index objects", it reads "The pandas [Index](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.html#pandas.Index) class and its subclasses can be viewed as implementing an ordered multiset. Duplicates are allowed. However, **if you try to convert an [Index](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.html#pandas.Index) object with duplicate entries into a set, an exception will be raised**."

but as I tried the below,

```python
i = pd.Index(['a', 'b', 'a'])
set(i)
## {'a', 'b'}
```

it just works fine.

### Suggested fix for documentation

it does not raise an exception... :(

**Comment by rhshadrach** [comment]
Thanks for the report @kwhkim. It looks to me like the offending sentence "However, if you try... an exception will be raised" can be removed. Would you be interesting in submitting a PR to fix?

**Comment by rhshadrach** [comment]
Also - can you make the title of this issue more informative.

**Comment by kwhkim** [comment]
Sure, will do in a day or so :)
