### ISSUE TITLE
BUG: Inconsistent treatment of NaN with `.rolling()` methods

### ISSUE THREAD

**Issue by joaomacalos** [pandas-dev/pandas#46458]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import numpy as np
import pandas as pd

(
    pd.DataFrame({"a": np.linspace(1, 10, 10)})
    .assign(a=lambda df: np.where(
        df.index.isin([3, 7]), np.nan, df.a

    ))
    .assign(window_equal_min_days=lambda df: df.a.rolling(2, 2).sum())
    .assign(window_bigger_min_days=lambda df: df.a.rolling(3, 2).sum())
    .rename(columns={"a": "col_with_nans"})
)
```

### Issue Description

When using a `.rolling()` methods, the treatment of NaN values is inconsistent.

If the `window` argument is equal to the `min_periods` argument, it treats the NaN as a NaN, thus requiring a new sequence of values (equal to `min_periods`) to output a new value that is not a NaN.

However, if the `window` argument is bigger than the `min_periods` argument, it treats the NaN as a zero, thus not stopping the calculation of the rolling windows.

### Expected Behavior

I'd expect the NaN's to be treated equally and as NaN's (if not stated otherwise, a NaN _is not_ equal to a zero). 

However, if documented, both answers should be acceptable, as long as the treatment is consistent.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : Intel64 Family 6 Model 126 Stepping 5, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.4.1
numpy            : 1.21.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.1.3
setuptools       : 52.0.0.post20210125
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.7.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.29.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.0
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 4.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 0.21.0
xlrd             : 2.0.1
xlwt             : None
zstandard        : None

</details>

**Comment by zhenqin77** [comment]
Hey I'm trying to see what the dataframe looks like before and after .rolling, but I'm unsure how to print the dataframe with the format you reported

**Comment by joaomacalos** [comment]
Hey, below I divided the example I used in the first post in two steps to make it easier to understand.

First, I create a DataFrame and added some nans to the column `col_with_nans`:

```python
df = (
    # Create a DataFrame with a sequence from 1 to 10
    pd.DataFrame({"col_with_nans": np.linspace(1, 10, 10)})
    # Add some nans to this column
    .assign(col_with_nans=lambda df: np.where(
        df.index.isin([3, 7]), np.nan, df.col_with_nans
    ))
)

# Print the results
df 
```
<html>
<body>


  | col_with_nans
-- | --
0|1.0
1|2.0
2|3.0
3|NaN
4|5.0
5|6.0
6|7.0
7|NaN
8|9.0
9|10.0


</body>
</html>

Second: Create two new columns using `.rolling()` methods to show the inconsistent treatment of NaNs depending on the `window` and `min_periods` arguments:

```python
(
    df
    # Create two new columns to show the inconsistent treatment of NaNs   
    .assign(
        window_equal_min_days=lambda df: df.col_with_nans.rolling(window=2, min_periods=2).sum(),
        window_bigger_min_days=lambda df: df.col_with_nans.rolling(window=3, min_periods=2).sum()
    )
)
```

<html>
<body>


  | col_with_nans | window_equal_min_days | window_bigger_min_days
-- | -- | -- | --
0|1.0 | NaN | NaN
1|2.0 | 3.0 | 3.0
2|3.0 | 5.0 | 6.0
3|NaN | NaN | 5.0
4|5.0 | NaN | 8.0
5|6.0 | 11.0 | 11.0
6|7.0 | 13.0 | 18.0
7|NaN | NaN | 13.0
8|9.0 | NaN | 16.0
9|10.0 | 19.0 | 19.0


</body>
</html>

As you can see, the NaNs are treated as NaNs in the `window_equal_min_days` column while they are treated as zeros in the `window_bigger_min_days` column. I hope this helps.

**Comment by phofl** [comment]
The behavior is correct. Your window has size 3, but the aggregation function requires only 2 valid values (e.g. non NaN values). Since no window ever contains 2 nans, every cell is filled (after the first one obviously)
