### ISSUE TITLE
DOC: SciPy minimum version

### ISSUE THREAD

**Issue by jamesmyatt** [pandas-dev/pandas#46455]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://github.com/pandas-dev/pandas/blame/main/doc/source/getting_started/install.rst#L279

### Documentation problem

SciPy minimum version is listed as 1.14.1, but the latest SciPy release is 1.8.0.

### Suggested fix for documentation

Correct minimum version

**Comment by jreback** [comment]
umm what do u think is the actual problem? minimum is the oldest version that is working

**Comment by jamesmyatt** [comment]
v1.14.1 doesn't exist. The latest is actually v1.8.0.

**Comment by jreback** [comment]
ahh that's a type 1.4.1

**Comment by iahsanujunda** [comment]
Is it okay if I work on this?

**Comment by iahsanujunda** [comment]
take
