### ISSUE TITLE
Not tested: `Period.strftime` and `PeriodIndex.strftime` with non-ascii char present in the formatting string

### ISSUE THREAD

**Issue by smarie** [pandas-dev/pandas#46468]
EDIT : as I found out this was not a bug in the main branch, I introduced it accidentally in #46405.
 Therefore I rename the ticket as "not tested", meaning that current test suite does not cover this case.

### Pandas version checks

- [X] I have checked that this issue has not already been reported.

### Reproducible Example

```python
import pandas as pd
import locale

locale.setlocale(locale.LC_ALL, "fr_FR")
per = pd.Period("2018-03-11 13:00", freq="H")
assert per.strftime("%Y é") == "2018 é"
```

### Issue Description

When there is a non-ascii character in the formatting string passed to `Period.strftime` the result may be corrupted. This is most probably related to an encoding error.

### Expected Behavior

The assert should pass without error

**Comment by smarie** [comment]
This issue was extracted from https://github.com/pandas-dev/pandas/issues/46319 for clarity

**Comment by zhenqin77** [comment]
take

**Comment by smarie** [comment]
I just realized that this bug was actually introduced in my PR #46405 
There was no test for this, introducing one is the only thing new that can be done. Renaming accordingly
