### ISSUE TITLE
BUG: style.set_sticky() doesn't work with axis="columns"

### ISSUE THREAD

**Issue by yegulalp** [pandas-dev/pandas#46469]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
bigdf = pd.DataFrame(np.random.randn(16, 100))
bigdf.style.set_sticky(axis=1)
bigdf.style.set_sticky(axis="columns")
```

### Issue Description

Dataframe style doesn't work with sticky columns.  Regardless of choosing axis="index" or axis="columns" (or axis=0 or axis=1), only a stick index is produced.  I can't get sticky columns.  I'm using JupyterLab 3.2.6

### Expected Behavior

I can't show an example of sticky columns, as it never produces the expected output.

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-693.5.2.el7.x86_64
Version          : #1 SMP Fri Oct 20 20:32:50 UTC 2017
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.4.1
numpy            : 1.20.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.8.0
html5lib         : None
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.0.2
IPython          : 8.1.1
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.2
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.1
numba            : 0.54.1
numexpr          : 2.8.0
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
sqlalchemy       : 1.3.23
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

**Comment by yegulalp** [comment]
> Your issue is not with pandas, but with Jupyter Lab.
> 
> Try `set_sticky` in an HTML document or in Jupyter Notebook and it will work as expected.

Thanks, I've tried notebook and it does work there.  Sadly, it still doesn't work when exported as HTML from lab or notebook.

Could you explain what you mean by "set_sticky" in an HTML document?

**Comment by attack68** [comment]
`bigdf.style.set_sticky(axis="columns").to_html("my_html.html", doctype_html=True)`
then open the HTML document in a browser

**Comment by yegulalp** [comment]
> `bigdf.style.set_sticky(axis="columns").to_html("my_html.html", doctype_html=True)` then open the HTML document in a browser

Thank you.  As you say, the problem is clearly with JupyterLab.

**Comment by attack68** [comment]
you should open an issue at Jupyter Lab to see what is their response or if their is workaround.

**Comment by yegulalp** [comment]
Reported to Jupyter Lab and accepted in March 24th triage meeting
https://github.com/jupyterlab/jupyterlab/issues/12263
