### ISSUE TITLE
AttributeError: 'pandas._libs.properties.CachedProperty' object has no attribute 'func'QST: 

### ISSUE THREAD

**Issue by threehappy** [pandas-dev/pandas#46474]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

AttributeError: 'pandas._libs.properties.CachedProperty' object has no attribute 'func'QST: 

### Question about pandas

%matplotlib inline

import numpy as np
import pandas as pd
import pandas_datareader.data as web

# from pyfinance.ols import PandasRollingOLS
# replaces pyfinance.ols.PandasRollingOLS (no longer maintained)
from statsmodels.regression.rolling import RollingOLS
import statsmodels.api as sm
from talib import RSI, BBANDS, MACD, NATR, ATR

from sklearn.feature_selection import mutual_info_classif, mutual_info_regression

import matplotlib.pyplot as plt
import seaborn as sns

________________________________________________________________________________________

--> 516 @Appender(RegressionResults.aic.func.__doc__)
    517 def aic(self):
    518     return self._wrap(RegressionResults.aic.func(self))
    520 @cache_readonly
    521 @Appender(RegressionResults.bic.func.__doc__)
    522 def bic(self):

AttributeError: 'pandas._libs.properties.CachedProperty' object has no attribute 'func'

**Comment by mroeschke** [comment]
It appears that this an upstream issue in the packages mentioned since those libraries are using private APIs so they can be subject to change. I would recommend opening up an issue in the libraries you used to address the pandas usages.
