### ISSUE TITLE
DOC: `allow_duplicate_labels=True`

### ISSUE THREAD

**Issue by kwhkim** [pandas-dev/pandas#46480]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/user_guide/duplicates.html#disallowing-duplicate-labels

### Documentation problem

Document says, 
> Setting allows_duplicate_labels=True on a Series or DataFrame with duplicate labels or performing an operation that introduces duplicate labels on a Series or DataFrame that disallows duplicates will raise an errors.DuplicateLabelError.

But it should be `allows_duplicate_labels=False` instead of `True`

### Suggested fix for documentation

`allows_duplicate_labels=True` -> `allows_duplicate_labels=False`

**Comment by rhshadrach** [comment]
Thanks for the report! Would you be interested in putting up a PR to fix, @kwhkim?

**Comment by kwhkim** [comment]
Okay, consider it done

**Comment by kwhkim** [comment]
Looks like everythings fine here

**Comment by kwhkim** [comment]
take
