### ISSUE TITLE
DOC: sample variance -> population variance

### ISSUE THREAD

**Issue by kwhkim** [pandas-dev/pandas#46482]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/user_guide/gotchas.html

### Documentation problem

Differences with NumPy
For [Series](https://pandas.pydata.org/docs/dev/reference/api/pandas.Series.html#pandas.Series) and [DataFrame](https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.html#pandas.DataFrame) objects, [var()](https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.var.html#pandas.DataFrame.var) normalizes by
N-1 to produce unbiased estimates of the sample variance, while NumPy’s numpy.var() normalizes by N, which measures the variance of the sample. 

"unbiased estimates of **the sample variance**" needs to be corrected to '**the population variance**'

### Suggested fix for documentation

"unbiased estimates of **the sample variance**" needs to be corrected to '**the population variance**'

**Comment by phofl** [comment]
Could you elaborate why you would make this change?

**Comment by kwhkim** [comment]
https://en.wikipedia.org/wiki/Bias_of_an_estimator

note that sample variance can be either biased or unbiased.

> sample variance defined as $S^2 = \frac{1}{n-1}\sum_{i=1}^n(X_i-\bar{X})^2$ is an unbiased estimator of the population variance 

The phrase above is quoted as it is in wikipedia. $S^2$ is a random variable so it is called **estimator**. If we have concrete numbers and calculated using the same formula, the result should be called **estimate**.

**Comment by phofl** [comment]
Thanks, would you be interested in submitting a pr?

**Comment by kwhkim** [comment]
sure

**Comment by kwhkim** [comment]
@jreback sorry this pull request is for issue #46440. Would you help me move this PR to that issue? I thought trailing (#...) would be sufficient but it appears not.
