### ISSUE TITLE
DOC: remove `regex` argument from `.str.rsplit` docs

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#46488]
#### Is your feature request related to a problem?

`.str.split` has a `regex` argument, which was added in https://github.com/pandas-dev/pandas/pull/44185

Should `.str.rsplit` also take it?

EDIT
----

`re.Pattern` has `split`, but not `rsplit`, so this isn't straightforward without some crazy workaround. Let's just separate out the `split` and `rsplit` docs such that the `rsplit` ones don't have the `regex` argument

Currently, the argument is documented, but can't be passed https://pandas.pydata.org/docs/reference/api/pandas.Series.str.rsplit.html?highlight=rsplit#pandas.Series.str.rsplit

**Comment by rhshadrach** [comment]
+1 on the consistency here.

**Comment by banditelol** [comment]
Hello, I'm interested in working on this issue, looking around I assume this entails:
- Implementing similar logic from `.str.split` to  `.str.rsplit`
- Writing additional test code

And I also noticed that the documentation has already been applied, so there's no need to update it right?

**Comment by MarcoGorelli** [comment]
@banditelol apologies, I'd suggested this issue to a co-worker who I think had started working on it, but they hadn't commented "take" - let's quickly check with them. @dykim29 are you still working on this?

**Comment by dykim29** [comment]
Hi @banditelol @MarcoGorelli I did start working on this! Still very new to this so didn’t comment ‘take’, apologies!

**Comment by dykim29** [comment]
take

**Comment by banditelol** [comment]
Okaay, good luck with the issue!
I'll look around again then
