### ISSUE TITLE
BUG: Datetime object is not being detected with Timestampz type in DB

### ISSUE THREAD

**Issue by rahilbhansali** [pandas-dev/pandas#46494]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
1. Fetch values from a postgres DB with column type timestampz (2021-03-09 11:06:00.000 +0000)
2. Print out the df['date'] column and see the datatype in 1.2.5 and 1.4.1.

self.df['date'] = pd.to_datetime(self.df['date'], errors='coerce')  # Doing this since pandas has stopped auto-detecting a date from the timestampz field for some reason.
```

### Issue Description

In 1.2.5 (the previous version I used), Pandas auto-detected the datetime field from the DB (type timestampz in postgres - 2021-03-09 11:06:00.000 +0030) as datetime64.

However, after I updated to 1.4.1, Pandas now recognises this as an object and sets the dtype for the column to object instead of datetime64. I need to add self.df['date'] = pd.to_datetime(self.df['date'], errors='coerce') in order to convert it manually, but not sure why it's happening suddenly. 

My guess is its failing to detect a timestamp column with the timezone (+0000).

<img width="421" alt="image" src="https://user-images.githubusercontent.com/7209471/159875034-30f21a83-1600-478e-ba08-fb2b3985bfbf.png">

This is a screenshot from 1.2.5
<img width="317" alt="image" src="https://user-images.githubusercontent.com/7209471/159875467-064950b6-73b0-4e3d-aa84-3969258ae588.png">

This is a screenshot from 1.3.5
<img width="313" alt="image" src="https://user-images.githubusercontent.com/7209471/159876344-9cc6b12e-c91f-4af6-8281-525cadfa05e6.png">

This is a screenshot from 1.4.1
<img width="260" alt="image" src="https://user-images.githubusercontent.com/7209471/159874941-8de1172b-b139-45a9-9518-6f7817f05b9a.png">

### Expected Behavior

It should auto-detect the datetime field and set the column dtype to datetime64.

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by mroeschke** [comment]
Hi thanks for the report. Could you post a more reproducible example? https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by phofl** [comment]
Closing for now, please ping to reopen when you can provide an example
