### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by allendred** [pandas-dev/pandas#46526]
### Pandas version checks

- [ ] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
>>> import pandas as pd
>>> pd.DataFrame(pd.date_range(start=f'{str("2022-03-01")}', end=f'{str(2022)}-{str("03")}-01', freq='30min', inclusive='left'))
           0
0 2022-03-01
```

### Issue Description

 Version 1.2.3  is OK with Argument `closed`
Argument `closed` is deprecated in  Version 1.4.1

### Expected Behavior

Empty DataFrame
Columns: [0]
Index: []
 

### Installed Versions

V1.4.1

**Comment by MarcoGorelli** [comment]
I just tried your example and it works fine:
```
>>> import pandas as pd
>>> pd.DataFrame(pd.date_range(start=f'{str("2022-03-01")}', end=f'{str(2022)}-{str("03")}-01', freq='30min', inclusive='left'))
           0
0 2022-03-01
>>> pd.__version__
'1.4.1'
```

could you clarify what you think the bug is, and put a descriptive title?

**Comment by attack68** [comment]
This has no descriptive title, nor is the issue clearly stated, and the example seems to work fine.

Closing for now. Please re-open when more info and description is available, thank you.

**Comment by allendred** [comment]
> I just tried your example and it works fine:
> 
> ```
> >>> import pandas as pd
> >>> pd.DataFrame(pd.date_range(start=f'{str("2022-03-01")}', end=f'{str(2022)}-{str("03")}-01', freq='30min', inclusive='left'))
>            0
> 0 2022-03-01
> >>> pd.__version__
> '1.4.1'
> ```
> 
> could you clarify what you think the bug is, and put a descriptive title?
The expected output 
>>> pd.DataFrame(pd.date_range(start=f'{str("2022-03-01")}', end=f'{str(2022)}-{str("03")}-01', freq='30min', inclusive='left'))
Empty DataFrame
Columns: [0]
Index: []

This is different from the previous comparison, it may be a logical problem

**Comment by MarcoGorelli** [comment]
what's different?
```
>>> pd.DataFrame(pd.date_range(start=f'{str("2022-03-01")}', end=f'{str(2022)}-{str("03")}-01', freq='30min', inclusive='left'))
           0
0 2022-03-01
>>> pd.DataFrame(pd.date_range(start=f'{str("2022-03-01")}', end=f'{str(2022)}-{str("03")}-01', freq='30min', closed='left'))
<stdin>:1: FutureWarning: Argument `closed` is deprecated in favor of `inclusive`.
           0
0 2022-03-01
```

**Comment by MarcoGorelli** [comment]
ah, I see what you mean, in 1.2.3 the output was different:
```
>>> pd.DataFrame(pd.date_range(start=f'{str("2022-03-01")}', end=f'{str(2022)}-{str("03")}-01', freq='30min', closed='left'))
Empty DataFrame
Columns: [0]
Index: []
>>> pd.__version__
'1.2.3'
```

**Comment by MarcoGorelli** [comment]
looks like this was changed intentionally in https://github.com/pandas-dev/pandas/issues/43394 , so no action needed here
