### ISSUE TITLE
ENH: Compact result from named aggregation

### ISSUE THREAD

**Issue by kwhkim** [pandas-dev/pandas#46553]
#### Is your feature request related to a problem?

```python
dat = pd.DataFrame({'carat':[0.23, 0.21, 0.23, 0.29, 0.31],
                    'x':[3.95, 3.89, 4.05, 4.20, 4.34]},
                  index = [1,2,3,4,5])
dat.agg(mean1 = ('carat', 'mean'), stdx = ('x', np.std))
## 	carat	x
## mean1	0.254	NaN
## stdx	NaN	0.184201

dat.agg({'carat':'mean', 'x':'std'})
## carat    0.254000
## x        0.184201
## dtype: float64
```

For consistency, result of `dat.agg(meanx = ('carat', 'mean'), stdx = ('x', np.std))` should better be 
```python
## meanx    0.254000
## stdx        0.184201
## dtype: float64
```

Anyway putting `NaN`'s does not help anyone here. Take a look at the code below

```python
dat.agg(mean1 = ('carat', 'mean'), std = ('x', 'std'), mean3 = ('carat', 'std'))
## 	carat	x
## mean1	0.254000	NaN
## std	NaN	0.184201
## mean3	0.043359	NaN
```

so even if we used the same 'std' function, there is no way we can name the index 'std'  for the result twice,
because index name is function parameter name(function can not have two identical parameter name)

Compare the result below with the result above.

```python
dat.agg({'carat':['mean', 'std'], 'x':['std', 'var']})
	  carat	x
## mean	0.254000	NaN
## std	0.043359	0.184201
## var	NaN	0.033930
```

It might better to support something like the below

```python
dat.agg(f1 = ('carat', ('mean', 'std')), f2 = ('x', (np.std, 'var')))
	  f1          f2
## mean	0.254000	NaN
## std	0.043359	0.184201
## var	NaN	0.033930

```

#### Describe the solution you'd like

For consistency, result of `dat.agg(mean = ('carat', 'mean'), std = ('x', np.std))` should better be 
```python
## mean    0.254000
## std        0.184201
## dtype: float64
```

and 

It might better to support something like the below

```python
dat.agg(v1 = ('carat', ('mean', 'std')), v2 = ('x', (np.std, 'var')))
	  v1          v2
## mean	0.254000	NaN
## std	0.043359	0.184201
## var	NaN	0.033930
```

#### API breaking implications

[this should provide a description of how this feature will affect the API]

There is not much inconsistency nor contradiction from this change.

#### Describe alternatives you've considered

[this should provide a description of any alternative solutions or features you've considered]

I can't think of any now

#### Additional context

[add any other context, code examples, or references to existing implementations about the feature request here]

**Comment by mroeschke** [comment]
Thanks for the request but it appears this hasn't gotten traction in a while so closing
