### ISSUE TITLE
QST: mypy errors when extending pandas Series with custom mixin

### ISSUE THREAD

**Issue by verdimrc** [pandas-dev/pandas#46554]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/71649892/mypy-errors-when-extending-pandas-series

### Question about pandas

Hi,

I encountered mypy errors `Definition of "_values" in base class "IndexOpsMixin" is incompatible with definition in base class "NDFrame"` when [extending](https://pandas.pydata.org/docs/development/extending.html#subclassing-pandas-data-structures) pandas Series.

The error disappears when `MyMixin` is removed from `SubclassedSeries`'s parent. However, I'd like to keep the mixin to provide common functions for both `SubclassedSeries` and `SubclassedDataFrame`, and I wonder what changes needed to remove the mypy errors?

```python
import pandas as pd


class MyMixin:
    def common_function(self):
        return 123


class SubclassedSeries(MyMixin, pd.Series):  # <-- Mypy errors.
    @property
    def _constructor(self):
        return SubclassedSeries

    @property
    def _constructor_expanddim(self):
        return SubclassedDataFrame


class SubclassedDataFrame(MyMixin, pd.DataFrame):
    @property
    def _constructor(self):
        return SubclassedDataFrame

    @property
    def _constructor_sliced(self):
        return SubclassedSeries
```

```bash
$ mypy mydf.py
mydf.py:9: error: Definition of "_values" in base class "IndexOpsMixin" is incompatible with definition in base class "NDFrame"
Found 1 error in 1 file (checked 1 source file)
```

**Comment by MarcoGorelli** [comment]
pandas doesn't expose types yet - I presume you're using a third-party tool? If so, please report there

**Comment by verdimrc** [comment]
Hi, I followed the instruction here (https://pandas.pydata.org/docs/dev/development/contributing_codebase.html#testing-type-hints-in-code-using-pandas) to create an empty file `py.typed` before running mypy.

```bash
# Without py.typed
$ mypy mydf.py
mydf.py:1: error: Skipping analyzing "pandas": module is installed, but missing library stubs or py.typed marker
mydf.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports

# After creating py.typed
$ mypy mydf.py
mydf.py:9: error: Definition of "_values" in base class "IndexOpsMixin" is incompatible with definition in base class "NDFrame"
Found 1 error in 1 file (checked 1 source file)
```

And if it helps, here're all the packages installed:

```bash
$ pip list
Package           Version
----------------- -------
mypy              0.942
mypy-extensions   0.4.3
numpy             1.22.3
pandas            1.4.1
pip               21.2.4
python-dateutil   2.8.2
pytz              2022.1
setuptools        58.1.0
six               1.16.0
tomli             2.0.1
typing_extensions 4.1.1
```

**Comment by MarcoGorelli** [comment]
Ah apologies, reopening then

**Comment by twoertwein** [comment]
> This seems to work, however would like to hear if this is really the right way.

I think for users, the best option is to do what Pandas does internally: use `# type: ignore[misc]`

https://github.com/pandas-dev/pandas/blob/9008ee5810c09bc907b5fdc36fc3c1dff4a50c55/pandas/core/series.py#L265
