### ISSUE TITLE
BUG: Segmentation fault with groupby/transform

### ISSUE THREAD

**Issue by ian-r-rose** [pandas-dev/pandas#46566]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas

df = pandas.DataFrame(
    {
        "A": [1, 2, 3, 4, 5] * 4,
        "B": [1, 2, 3, 4, 5] * 4,
        "C": [1, 2, 3, 4, 5] * 4,
    }
)

df.groupby(["A", "B"]).transform(lambda x: x)
```

### Issue Description

:wave: Since about February 27, the above snippet has been generating a segmentation fault in pandas `main`. As far as I can tell, this is coming from `get_group_index_sorter()` in `pandas.core.sorting`. 

Based on the timing and git history, it may be related to #45953, though I've been unable to identify the source of the problem thus far.

A few observations:
1. The length of the series seem to matter. If I shorten the sample df to have length 15, things work fine.
2. It seems to matter if I groupby more than one field (just grouping by `"A"` works fine)
3. The segfault only happens for `transform`. If I use `apply` it works.

### Expected Behavior

No segfault should occur.

### Installed Versions

This shows up on pandas `main`.

Based on the nightly builds [here](https://anaconda.org/scipy-wheels-nightly/pandas), it seems like the first affected version was [this one](https://anaconda.org/scipy-wheels-nightly/pandas/1.5.0.dev0%2B447.g6caefb19f4/download/pandas-1.5.0.dev0%2B447.g6caefb19f4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl).

**Comment by ian-r-rose** [comment]
Update, I ran a git bisect, and it seems to come from #45953

**Comment by rhshadrach** [comment]
Thanks for the report! Confirmed on main, tagging as 1.5 to track.

**Comment by rhshadrach** [comment]
I believe the method `result_ilocs` is missing a call to `compress_group_index`. Will put up a PR to fix shortly.

**Comment by ian-r-rose** [comment]
Thanks for the quick fix!
