### ISSUE TITLE
ENH: Allow usage of custom library to serialize with `to_json` method.

### ISSUE THREAD

**Issue by Duoquote** [pandas-dev/pandas#46571]
#### Is your feature request related to a problem?

I was thinking about if I can pass my custom function to pandas' `to_json` to use some other json serializer, or maybe somehow access the dictionary that `to_json` method generates, turns out you can not do both.

#### Describe the solution you'd like

As seen [here](https://github.com/pandas-dev/pandas/blob/3b163de02f666a2342e18468cba7d6c286f526bf/pandas/io/json/_json.py#L69), the default `json.dumps` function is set hardcoded, a new argument can be added to `to_json` method like `serializer_function`.  So that I can use any other library like `orjson` and pass it like `df.to_json(serializer_function=orjson.dumps)`.

**Comment by rmhowe425** [comment]
take

**Comment by rmhowe425** [comment]
@mroeschke @Duoquote 

Should we assume that the custom function should accept the same parameters as the hard coded function used for serialization?

**Comment by rmhowe425** [comment]
@mroeschke @rhshadrach Do we want to close this issue in addition to the closed PR above?

**Comment by mroeschke** [comment]
Thanks for the issue, but it appears this hasn't gotten traction in a while so closing
