### ISSUE TITLE
change the index in DataFrame.to_csv to False as default?

### ISSUE THREAD

**Issue by KirderfEman** [pandas-dev/pandas#46583]
Maybe it’s time in some future release change the index in DataFrame.to_csv to False as default? Just a feeling that many change it manually from True to False every time using it...

Thanks for a 10/10 product!

**Comment by attack68** [comment]
i suspect this is a widely used method. changing might cause more problems that the observed benefits. not convinced that a default of false is more readily used than true across all users and cases.

**Comment by KirderfEman** [comment]
Ok, have only seen False in all codes I have seen in 4y, have also seen in examples/how-to that they recommend False. Hope you can take in consideration to future releases, changes in the standard parameters is common, I think the community can handle it.

**Comment by twoertwein** [comment]
The same issue has previously been closed #12627 (very similar issue #24468)

**Comment by asishm** [comment]
Most of the code I've seen (within our org) either drops the "Unnamed ..." index column as the very first thing when reading a csv output by `pd.DataFrame.to_csv` or uses `index=False` when writing the csv.

The few times it is useful (when writing the result of a pivot / groupby operation directly without resetting the index) is a minority.

That said, and as much as I'd like to see the default being changed - it's unlikely to change (#34576 in addition to the ones listed above)

**Comment by mroeschke** [comment]
Thanks for raising the issue, but additionally the core sticking point is that the Index is assumed a necessary component of a pandas DataFrame (for better or worse), so if the index (or axes in general) would ever be made optional this change would be more welcome. Closing for now as discussed in the linked issues
