### ISSUE TITLE
CI: Increase GitHub Actions resources

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#46600]
xref https://github.com/pandas-dev/pandas/pull/46493#issuecomment-1079541210

I'm assuming it'd make our life easier, if we could significantly increase our resources in GitHub actions, so we could standardize most of our CI to use it. In partiicular builds in Azure pipelines, I think we want to keep CircleCI unless GitHub actions start supporting arm.

I contacted the open source program manager at GitHub to see if this is an option. I asked them few times already over the past few years, as part of a GitHub feedback group I'm in, but never got an answer. Let's see if this changed.

If this is not an option, I think another option could be to use a [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners). We should be able to get the hardware for free, with the sponsoring agreements we're working on at NumFOCUS. I guess it wouldn't be too complex to setup or maintain. So, maybe worth if this is going to save us time from maintaining different CI systems.

I need to check in detail, and make sure we can use both our current quota, plus self-hosted runners, but I assume it's possible.

Thoughts?

CC: @jreback @mroeschke @jonashaag

**Comment by jonashaag** [comment]
Would be great.

(Btw, I think we would be better off with a single fast 16 core machine than all of the Azure and GH machines combined (based on an observed 5x speed up running CI on an M1 machine with 1 core vs on GHA))

**Comment by jreback** [comment]
we need as simple as possible
and as maintainable as possible

i think we have had a lot of churn recently and would not change anything at this time

**Comment by jonashaag** [comment]
I think the best option would be just move everything to Docker containers and run that. Then we can use whatever platform we want that supports Docker. 

Doesn’t work for Windows though.

**Comment by datapythonista** [comment]
GitHub upgraded our repo to the Enterprise-level actions quota, which should be a major increase in the resources for the CI (not sure exactly how much, I'll try to understand better what are the changes later).

Please let me know if any feedback (any problem, or if you notice the improvement).

CC: @pandas-dev/pandas-core

**Comment by jreback** [comment]
oh wow
thanks @datapythonista

**Comment by datapythonista** [comment]
If I'm checking at the right place, and there aren't more limits I'm unaware of, we just went from 20 concurrent workers, to 180... :exploding_head: 

https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits

**Comment by jreback** [comment]
wow
