### ISSUE TITLE
ENH: Interval.__contains__(self, other: Interval)

### ISSUE THREAD

**Issue by tgy** [pandas-dev/pandas#46613]
#### Is your feature request related to a problem?

Not a problem. Just a feature I would have liked to have! :-)

I would like to be able to know if an `Interval` is contained into another `Interval`.

e.g. `[2, 3)` is contained in `[2, 4)` but not in `(2, 4]`

#### Describe the solution you'd like

Something like this

```python
def interval_contains(a: pd.Interval, b: pd.Interval) -> bool:
    res = a.left <= b.left and a.right >= b.right
    if a.open_left and b.closed_left:
        res &= a.left < b.left
    if a.open_right and b.closed_right:
        res &= a.right > b.right
    return res
```

#### API breaking implications

Currently, if you do something like this

```python
a = pd.Interval(2, 3, closed="left")
b = pd.Interval(2, 4, closed="left")
print(a in b)
```

it raises the following exception

```
TypeError: __contains__ not defined for two intervals
```

Adding support for another type of object in `__contains__` would not break the API, but just extend it.

#### Describe alternatives you've considered

Could not find any.

**Comment by jreback** [comment]
https://pandas.pydata.org/docs/reference/api/pandas.IntervalIndex.contains.html?highlight=contains#pandas.IntervalIndex.contains

**Comment by tgy** [comment]
@jreback thanks for your reply. I know about what you just referred to. It works with `scalar` values but it does not work with another `Interval`. Therefore, I am not sure how your answer is relevant to the original feature request.

**Comment by samukweku** [comment]
@tgy is this similar to interval overlap? Maybe `interval overlaps` could apply

**Comment by tgy** [comment]
> @tgy is this similar to interval overlap? Maybe `interval overlaps` could apply

Thanks for your reply. I know about the `overlaps()` method of `Interval`, as I read the documentation and the code before opening this issue.

Interval containment is different from interval overlap.

First of all, the `overlaps` operator is commutative. In other words, for any given two intervals `a` and `b`, we have that `a.overlaps(b)` iff `b.overlaps(a)`. This is not the case with the containment operator: if `a` is contained in `b`, then `b` is not necessarily contained in `a` (the latter is true iff `b` = `a`).

This simple observation is already enough to understand that these two operators are different. But let's take a concrete example as well.

The two intervals `a = [2, 4)` and `b = (2, 5]` overlap but neither `a` contains `b` nor `b` contains `a`.

**Comment by venaturum** [comment]
You can find this functionality in [`piso`](https://piso.readthedocs.io) until it is implemented in `pandas`

https://piso.readthedocs.io/en/latest/reference/api/piso.interval.issuperset.html#piso.interval.issuperset

**Comment by tgy** [comment]
ah thanks @venaturum! that package fell under my radar. interesting.

**Comment by kapiliyer** [comment]
take
