### ISSUE TITLE
ENH: Add alias for `value_counts()` named `count_values()`

### ISSUE THREAD

**Issue by matiasandina** [pandas-dev/pandas#46614]
#### Is your feature request related to a problem?

I understand `There should be one-- and preferably only one --obvious way to do it.`
However, I believe pandas could provide "synonyms" for functions to provide better usability. 

#### Describe the solution you'd like

Creating an alias would suffice, `value_counts()` can function by calling `count_values()` without adding too much of a complication.

#### API breaking implications

I don't think this will affect the API in any form

#### Describe alternatives you've considered

I have considered it my fault every single time I failed to remember it and spent quite some time already searching for "pandas count values". I tend to default to `count()` and subset instead of doing `vaue_counts()`. Maybe I am the only person who has this issue, but for me, the "obvious" way to call it would be `count_values()`.

**Comment by jreback** [comment]
-1 on aliases in the api

**Comment by mroeschke** [comment]
Thanks for the suggestion, but since pandas API surface area is already quite large, it would be onerous to increase it more with aliases.

Since the team has been activate trying to reduce alias method names, closing as this will most likely not be pursued.
