### ISSUE TITLE
DOC: documentation on `.loc[]` needs some clarification

### ISSUE THREAD

**Issue by kwhkim** [pandas-dev/pandas#46620]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html

### Documentation problem

The Original documentation is as follows.

===
  ```
  tuples = [
     ('cobra', 'mark i'), ('cobra', 'mark ii'),
     ('sidewinder', 'mark i'), ('sidewinder', 'mark ii'),
     ('viper', 'mark ii'), ('viper', 'mark iii')
  ]
  index = pd.MultiIndex.from_tuples(tuples)
  values = [[12, 2], [0, 4], [10, 20],
          [1, 4], [7, 1], [16, 36]]
  ```
  Single index tuple. Note this returns a Series.
  
  ```
  df.loc[('cobra', 'mark ii')]
  max_speed    0
  shield       4
  Name: (cobra, mark ii), dtype: int64
  ```
  
  Single label for row and column. Similar to passing in a tuple, this returns a Series.
  
  ```
  df.loc['cobra', 'mark i']
  max_speed    12
  shield        2
  Name: (cobra, mark i), dtype: int64
  ```
===

But `df.loc['cobra', 'mark i']` is essentially the same as `df.loc[('cobra', 'mark i')]` because we can omit `(`, `)` inside `[`, `]`.
So the second example is not always about **single label for row and column** but can be also **multiple index label**.

In conclusion, `df.loc[A, B]` can be either `df.loc[(A, B),:]` or `df.loc[(A,),B]` but `pandas` seems to try the first one first

### Suggested fix for documentation

Single index tuple. Note this returns a Series.

```
df.loc[('cobra', 'mark ii')]
max_speed    0
shield       4
Name: (cobra, mark ii), dtype: int64
```

We can omit parentheses  from single index tuple. Single index tuple can mean either MultiIndex or single label for row and column. `pandas` tries multiple index first and it tries single label for row and column if it fails. Here is the example of this.

```
df.loc['cobra', 'mark ii']
max_speed    0
shield       4
Name: (cobra, mark ii), dtype: int64

df.loc['cobra', 'mark i']
max_speed    12
shield        2
Name: (cobra, mark i), dtype: int64
```

Let's make a DataFrame with the identical index and column labels.

```
df.columns=['mark i', 'mark ii']
```

Let's compare the below

```python
df.loc[('cobra', 'mark i')]
df.loc[('cobra',), 'mark i']
from pandas import IndexSlice as ix
df.loc[('cobra', ix[:]), 'mark i']
```

**Comment by simonjayhawkins** [comment]
Thanks @kwhkim for the report.

changing the current documentation may end up being more confusing

would not be adverse to adding a section after "Getting values with a MultiIndex" say "Getting values with a MultiIndex with overlapping index and column labels" though. Would need to check that this is not covered elsewhere in the docs, in Indexing, FAQs or other code samples as if this is the case could maybe just add a link instead.

**Comment by rhshadrach** [comment]
+1 with @simonjayhawkins; this is also covered in Advanced Indexing:

https://pandas.pydata.org/docs/user_guide/advanced.html#advanced-indexing-with-hierarchical-index

perhaps the loc page could be linked here.

**Comment by joybh98** [comment]
is anybody working on this issue ? If not I'll like to work on it

**Comment by Sumanth077** [comment]
@asherhe Are you currently working on this?

**Comment by Oliver-Looney** [comment]
Can I pick this issue up?

**Comment by tpackard1** [comment]
take
