### ISSUE TITLE
ENH: alias groupby to group_by.

### ISSUE THREAD

**Issue by RyanDoesMath** [pandas-dev/pandas#46626]
#### Describe the solution you'd like

I think it would make a lot of sense to allow users to use either groupby or group_by for the same method. First, it would align better with R's group_by function, and secondly it would be more consistent with already existing methods like sort_values(), drop_duplicates(), add_prefix(), add_suffix(), from_dict(), etc. There are other methods that use two words but don't contain an underscore that I think could also be changed, but this one makes the most sense to start at because of the way R names its group_by function.

#### API breaking implications

There is no other method by this name that I know of, and if we simply alias the method then it wouldn't affect already written code (at least in this version).

**Comment by jreback** [comment]
-1 on aliases generally 

i don't find the R argument compelling at all

**Comment by mroeschke** [comment]
Agreed, pandas is trying to generally eliminate aliases as there should be one clear way to do things: https://github.com/pandas-dev/pandas/issues/46614#issuecomment-1086743428=

Closing as there will not likely be support for alias feature requests

**Comment by RyanDoesMath** [comment]
If there should be one clear way of doing things, why are some methods that use two words separated with an underscore while others don't have any separation?

**Comment by mroeschke** [comment]
Historical development artifacts of a relatively old code base from hundreds of developers.

**Comment by RyanDoesMath** [comment]
Ah, so we just stuck picking between having aliases and having inconsistent method names. That kinda sucks.  
Any plans for changing this in the next major release?

**Comment by jreback** [comment]
it's not worth the churn
