### ISSUE TITLE
ENH: Join - Add a parameter to check for duplicates

### ISSUE THREAD

**Issue by jiri-kulik** [pandas-dev/pandas#46622]
#### Is your feature request related to a problem?

It is arguably more common than not to join dataframes on a unique index. Optional check for uniqueness would help to prevent hidden errors and time spent on debugging.

#### Describe the solution you'd like

`DataFrame.join` should get a new parameter `on_unique` that would, if set to True, check if the index/columns on which joining is performed have duplicates and raise error if yes. Default should be False to keep backward compatibility.

#### API breaking implications

Default set to False ensures no issues with compatibility.

**Comment by samukweku** [comment]
A workaround at the moment would be to use pandas merge and use the `validate` argument to check for uniques. Pass `left_index` and `right_index` as True. It would be nice though to have the `validate` argument in the join function

**Comment by jreback** [comment]
.join calls merge under the hood

so would accept a PR to add validate kwarg

i believe there is another issue about this - pls check

**Comment by gaotian98** [comment]
Hi @jreback , I submitted a PR. Would you please take a look?
