### ISSUE TITLE
DOC: simply method='bfill'?

### ISSUE THREAD

**Issue by kwhkim** [pandas-dev/pandas#46631]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/user_guide/cookbook.html#cookbook-missing-data

### Documentation problem

DOC says use `df.reindex(df.index[::-1]).ffill()`
but `df.bfill()` is available, maybe after some version? I don't know

Do we need to do `df.reindex(df.index[::-1]).bfill()` when index is alway sorted?

### Suggested fix for documentation

replace `df.reindex(df.index[::-1]).ffill()` with `df.bfill()`

**Comment by CloseChoice** [comment]
Looks good to me. Would you like to file a PR?

**Comment by kwhkim** [comment]
yes, i'll replace `df.reindex(df.index[::-1]).ffill()` with `df.bfill()`
