### ISSUE TITLE
BUG: Getting different column types for DataFrame with read_sql_query and read_sql_table

### ISSUE THREAD

**Issue by AfunAlex** [pandas-dev/pandas#46632]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
# If in postgres we create table with numeric column as follows:
#create table test_table(
#total  numeric
#);
#insert into test_table values(111.121);
#Example 1
connection_string = 'postgresql://{usr}:{pwd}@{host}:{port}/{db}'
engine = create_engine(connection_string)
query = '''
    select  *
    from test_table
'''
sample_df = pd.read_sql_query(query, con=engine, coerce_float=False)
sample_df.dtypes
## we get column total type object - object of Decimals as i understand
#Example 2 
sample_df2 = pd.read_sql_table('test_table', con=engine, coerce_float=False)
sample_df2.dtypes
## we get column total type float64 even though both functions should return the same thing
```

### Issue Description

If we use read_sql_query and read_sql_table we get different results types for Table with numeric column. In both examples i use parameter coerce_float=False that should prevent converting to float.

### Expected Behavior

Return DataFrame types should be the same and type conversion in second example should not take place 

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.4.0
Version          : Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.4.1
numpy            : 1.21.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : 0.29.28
pytest           : 6.2.5
hypothesis       : None
sphinx           : 4.4.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.2
lxml.etree       : 4.8.0
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.8.6
jinja2           : 2.11.3
IPython          : 8.1.1
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.4
fastparquet      : None
fsspec           : 2022.02.0
gcsfs            : None
matplotlib       : 3.5.1
numba            : 0.55.1
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : 0.17.4
pyarrow          : 4.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : 1.4.32
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None

**Comment by mroeschke** [comment]
Thanks for your report. Could you create a fully reproducible example from a console output inserting the data in Python and showing the result of these operations? That would mirror how we test these functions in our test suite

**Comment by mroeschke** [comment]
Closing for now, but can reopen you are able to provide a reproducible example.
