### ISSUE TITLE
should dot optionally handle nans?

### ISSUE THREAD

**Issue by cpcloud** [pandas-dev/pandas#4666]
related: https://github.com/pydata/pandas/issues/3513

[related SO question](http://stackoverflow.com/questions/18419657/dataframe-merge-in-pandas)

would probably have to write our own nan-handling dot since multiply-and-sum is inefficient for large frames.

cc @hayd

**Comment by ron819** [comment]
@cpcloud any progress with this?

**Comment by cpcloud** [comment]
@ron819 I am not working on this issue anymore.

**Comment by jbrockmendel** [comment]
i lean towards "no", closing since there hasn't been much interest in years, can reopen if that changes.
