### ISSUE TITLE
DOC: methods available only for `SeriesGroupBy` objects

### ISSUE THREAD

**Issue by kwhkim** [pandas-dev/pandas#46670]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/groupby.html

### Documentation problem

[SeriesGroupBy.nunique](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.SeriesGroupBy.nunique.html#pandas.core.groupby.SeriesGroupBy.nunique) is included in the table **methods available only for SeriesGroupBy objects** but it is also include in the table **methods available in both SeriesGroupBy and DataFrameGroupBy**. It is also true of `.value_counts()`

### Suggested fix for documentation

Delete `.value_counts()` and `.nunique()` from  the table **methods available only for SeriesGroupBy` objects**

**Comment by TarunRKaushik** [comment]
take
