### ISSUE TITLE
BUG: Incosistent handling of null types by PeriodIndex

### ISSUE THREAD

**Issue by jgmarcel** [pandas-dev/pandas#46673]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np
pd.PeriodIndex(["2022-04-06", "2022-04-07", None], freq='D')
pd.PeriodIndex(["2022-04-06", "2022-04-07", np.nan], freq='D')
pd.PeriodIndex(["2022-04-06", "2022-04-07", pd.NA], freq='D')
```

### Issue Description

The constructor of _PeriodIndex_ correctly handles `None` and `np.nan` values in the input data, but fails to handle `pd.NA` values. Given that the latter is automatically introduced into a _Series_ of which is called `astype('string')`, this poses a serious limitation to the initalization of _PeriodIndex_ objects from a _Series_ of dtype `string`.

### Expected Behavior

The return value of

`pd.PeriodIndex(["2022-04-06", "2022-04-07", pd.NA], freq='D')`

should be the same as

`pd.PeriodIndex(["2022-04-06", "2022-04-07", None], freq='D')`

that is:

`PeriodIndex(['2022-04-06', '2022-04-07', 'NaT'], dtype='period[D]')`

### Installed Versions

<details>

```
INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.9.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.60.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Aug 25 23:20:18 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.2
numpy            : 1.22.3
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 22.0.4
setuptools       : 57.4.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.9.2
jinja2           : None
IPython          : 7.26.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           :
fastparquet      : None
fsspec           : 2021.07.0
gcsfs            : None
markupsafe       : 2.0.1
matplotlib       : 3.4.3
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : 2021.07.0
scipy            : 1.8.0
snappy           : None
sqlalchemy       : 1.4.34
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : None
```

</details>

**Comment by kapiliyer** [comment]
take

**Comment by jgmarcel** [comment]
> take

Feel free to ask should you need any further information on this report. Thank you.
