### ISSUE TITLE
BUG: `SeriesGroupBy.value_counts` ignore NaNs of groupby column

### ISSUE THREAD

**Issue by xinrong-databricks** [pandas-dev/pandas#46676]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

pdf = pd.DataFrame({'A':[np.nan, 2, 2, 3, 3, 3], 'B':[1, 2, 2, 3, 3, np.nan]})

pdf.groupby("A")["B"].value_counts()
```

### Issue Description

The last statement of the reproducible example returns
```py
>>> pdf.groupby("A")["B"].value_counts()
A    B  
2.0  2.0    2
3.0  3.0    2
Name: B, dtype: int64
```
on pandas 1.4.2.

The NaN of column A is ignored.

Note that NaNs of groupby column are ignored no matter `dropna` is set True or not.

### Expected Behavior

```py
>>> pdf.groupby("A")["B"].value_counts()
A    B  
NaN  1.0    1
2.0  2.0    2
3.0  3.0    2
Name: B, dtype: int64
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.10.0.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.5.0
Version          : Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.2
numpy            : 1.21.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.2
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : None
matplotlib       : None
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by GYHHAHA** [comment]
Hi, can you check the following result? At least it works for me. @xinrong-databricks 

```python
>>> pdf.groupby("A", dropna=False)["B"].value_counts()
A    B
2.0  2.0    2
3.0  3.0    2
NaN  1.0    1
Name: B, dtype: int64
```

**Comment by phofl** [comment]
Yep, agreed. You have to set dropna

**Comment by xinrong-databricks** [comment]
Thanks @GYHHAHA and @phofl for the clarification!
