### ISSUE TITLE
BUG: index_col=False does not work

### ISSUE THREAD

**Issue by ZHANGGU** [pandas-dev/pandas#46678]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
azi1 = pd.read_csv(fp1, sep=';', skiprows=12, index_col=False)
```

### Issue Description

Pandas give index to columns with index_col=False
[temp.txt](https://github.com/pandas-dev/pandas/files/8440634/temp.txt)
![2022-04-07_09-33-01](https://user-images.githubusercontent.com/8365180/162147014-f92f35e2-367a-4281-9e0c-5455d4a0083c.png)

### Expected Behavior

column should not be indexed

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>
INSTALLED VERSIONS
------------------
commit           : b5958ee1999e9aead1938c0bba2b674378807b3d
python           : 3.7.0.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
machine          : AMD64
processor        : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.1.5
numpy            : 1.21.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 21.2.4
setuptools       : 41.6.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.19.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.0
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.3.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

**Comment by phofl** [comment]
``index_col`` means, that some columns are put in the index, not that your DataFrame columns do not get names. I think header=None might be what you are looking for, but please add a reproducible example, when you think this is a bug on the pandas side (see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports). It should be minimal (e.g. no more lines and columns than necessary) and copy and pasteable, Please also type down your expected output based on your input

**Comment by simonjayhawkins** [comment]
@ZHANGGU thanks for the report. closing but can reopen if you can provide a minimum reproducible example.
