### ISSUE TITLE
QST: pandas multi-level index How to add a new row index, not at the end, but at the original location

### ISSUE THREAD

**Issue by laohu123** [pandas-dev/pandas#46679]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

1

**Comment by MarcoGorelli** [comment]
please ask on stackoverflow and include a minimal reproducible example
