### ISSUE TITLE
custom formatters for to_csv

### ISSUE THREAD

**Issue by cpcloud** [pandas-dev/pandas#4668]
- [ ] date formatting #2583, PR #4313, #6797
- [ ] string spacing (justification?) #4158
- [ ] float format #2502, #2069
- [ ] int format, #6502
- [ ] timedelta fromat #6783 

[SO question](http://stackoverflow.com/questions/18425400/printing-to-csv-file-with-automatic-width)

something like

``` python
df.to_csv(format='%10.4f', sep=' ')
```

**Comment by drafter250** [comment]
I dont want to be a pain but This master issue looks like it has been holding the string spacing issue hostage for almost 3 years and I think is mostly unrelated to more complex issues like float and datetime formatting. just ran into it in version 17.1 Going to have to format entire table manualy.

**Comment by jreback** [comment]
@drafter250 well we have 1600 issues - which one shall be first? best way to get something in would be to put in a pull request

**Comment by VelizarVESSELINOV** [comment]
Suggestion to have float32_formatter different than the float64_formatter. Today force float32 and float64 types to have same formatter is far from optimal.

**Comment by drafter250** [comment]
@jreback re: extra spaces between columns in DataFrame.to_string. not long after my posting I dug into the pandas/core/format.py module where to_string is located under the DataFrameFormater class. I found that there are a few calls to a method "self.adj.adjoin" where the first argument should be an integer for the number of spaces between columns and the second are the columns themselves. most of the calls to this method are hardcoded and the col_space argument in the "to_string" method seems to actually go un-used. 

so I added these four lines to DataFrameFormatter.__init__()
```
    #set col_space to zero if custom formaters provided and
    #no col_space provided.
    self.col_space = col_space
    if formatters is not None and col_space is None:
        self.col_space = 0
    elif col_space is None:
        self.col_space = 1
```
then replaced the hard-coded values to self.adj.adjoin with self.col_space and it seemed to work both with formatters or specifying a number of spaces to the col_space argument

I just got a development environment setup for pandas per the user instructions and noticed that the format module is missing from pandas/core and is now in a subpackage called formatters. This would be my first pull request and I want to do things right and write my tests first.

Q1 Where would I find any tests related to the to_string functionality as I don't see a test folder under the new formatters sub-package?

Q2. Could the extra space issue #4158 be separated out from this bigger issue so it can be referenced from the pull request. (you can wait till I actually submit the request)?

Thanks!

**Comment by jreback** [comment]
rebase on master and you will see the ``pandas/formats`` where things moved in 0.18.0.
test are in ``tests/formats/``

ideally you DO separate out issues to as narrow as possible

**Comment by acrosby** [comment]
Was there any progress on this? Or a way to hack `to_space` to use commas as sep?

**Comment by drafter250** [comment]
I got hung up trying to find right spot to add/modify tests and think I
remember running into some corner cases that  i couldn't quite figure out.
After looking at the formatting code It seems very intertwined with other
bits and i can see why they wanted to revamp the API.

**Comment by simonjayhawkins** [comment]
perhaps reopen #16840 in preference to this, purely for consistency with to_string etc.

**Comment by jbrockmendel** [comment]
all but one of the issues in the OP are now closed.  is this still needed?

**Comment by mroeschke** [comment]
Agreed, the last issue doesn't need this master tracker anymore. Closing

**Comment by davetapley** [comment]
@mroeschke et al. care to weigh in on my comment here? 🙏🏻 
- https://github.com/pandas-dev/pandas/issues/9448#issuecomment-1577879552
