### ISSUE TITLE
CLN find stacklevel inside deprecate_nonkeyword_arguments

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#46687]
xref https://github.com/pandas-dev/pandas/pull/44896/files#r845356050

Rather than passing stacklevel to the decorator, e.g.

https://github.com/pandas-dev/pandas/blob/e1b95fa128203e6e21d3a1a6469c94e49f503e0c/pandas/io/parsers/readers.py#L831-L833

`find_stacklevel` should probably be called within `deprecate_nonkeyword_arguments`

**Comment by Anupam-USP** [comment]
Is this issue still open?

**Comment by MarcoGorelli** [comment]
Yup!

**Comment by Anupam-USP** [comment]
In short, do I have to remove `stacklevel` from within every decorator in the codebase?

**Comment by MarcoGorelli** [comment]
yeah exactly, but it should be used within the definition of `deprecate_nonkeyword_arguments` itself, rather than having to pass it when it's used

**Comment by Anupam-USP** [comment]
There are many definitions for this in the codebase, do I have to change all of them or only in the above-mentioned `readers.py`?

**Comment by MarcoGorelli** [comment]
search for `def deprecate_nonkeyword_arguments`, that's the one you'll want to change
