### ISSUE TITLE
PERF: 

### ISSUE THREAD

**Issue by jagpreet** [pandas-dev/pandas#46694]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this issue exists on the main branch of pandas.

### Reproducible Example

I'm using following line of code in my application.

```
        drawdown = lambda x: np.nanmax(1.0 - x / np.fmax.accumulate(x))
        return df.rolling(window=250, min_periods=1).apply(drawdown)
```
df a dataframe with 2000 columns and 3000 rows.
Execution of following code is taking around 50 minutes of time.
The same code get executes much faster with 0.23.x version in pandas.

data type of df is float with datetime as index.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.9.7.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252
pandas           : 1.3.4
numpy            : 1.20.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : 0.29.24
pytest           : 6.2.4
hypothesis       : None
sphinx           : 4.2.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.1
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.29.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fsspec           : 2021.10.1
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : 1.4.22
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.54.1

</details>

**Comment by phofl** [comment]
Please provide a reproducible example, see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

Also please provide a descriptive title

**Comment by simonjayhawkins** [comment]
Thanks @jagpreet for the report. closing for now. but if you are able to post a reproducible example here in the closed issue, can always reopen.
