### ISSUE TITLE
BUG: `DatetimeIndex.intersection` not working for localized indices

### ISSUE THREAD

**Issue by rwijtvliet** [pandas-dev/pandas#46702]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

# this works:
i1 = pd.date_range('2020-03-27', periods=5, freq='D')
i2 = pd.date_range('2020-03-30', periods=5, freq='D')
i1.intersection(i2)  # DatetimeIndex(['2020-03-30', '2020-03-31'], dtype='datetime64[ns]', freq='D')

# but this does not:
i1 = pd.date_range('2020-03-27', periods=5, freq='D', tz='Europe/Berlin')
i2 = pd.date_range('2020-03-30', periods=5, freq='D', tz='Europe/Berlin')
i1.intersection(i2) # DatetimeIndex([], dtype='datetime64[ns, Europe/Berlin]', freq='D')
# should be DatetimeIndex(['2020-03-30 00:00:00+02:00', '2020-03-31 00:00:00+02:00'], dtype='datetime64[ns, Europe/Berlin]', freq='D')
```

### Issue Description

`intersection` is not working correctly for timezone-aware `DatetimeIndex` instances.

### Expected Behavior

That all timestamps that are in both indices are kept.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.7.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : de_DE.cp1252

pandas           : 1.4.1
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : None
pytest           : 7.1.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.1.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
sqlalchemy       : 1.4.32
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
</details>

**Comment by rwijtvliet** [comment]
Current workaround:
```python
i1 = pd.date_range('2020-03-27', periods=5, freq='D', tz='Europe/Berlin')
i2 = pd.date_range('2020-03-30', periods=5, freq='D', tz='Europe/Berlin')
intersection = pd.Index([i for i in i1 if i in i2], freq=i1.freq)
```

**Comment by jreback** [comment]
can u try on master and see if these r working

**Comment by jreback** [comment]
these are only when the transition is happening right? or for all tz aware? (which i know we test so this is odd)

**Comment by rwijtvliet** [comment]
It's only when there's a DST transition

**Comment by rwijtvliet** [comment]
Just to make sure I'm doing it right: I created and activated a fresh virtual environment, `git clone https://github.com/pandas-dev/pandas.git newdir`, then `pip install -e .`, installed the missing 6GB C++ build tools, and run the above code - is that correct?

The result is the same:

```python
>>> i1 = pd.date_range('2020-03-27', periods=5, freq='D', tz='Europe/Berlin')
>>> i2 = pd.date_range('2020-03-30', periods=5, freq='D', tz='Europe/Berlin')
>>> i1.intersection(i2)
DatetimeIndex([], dtype='datetime64[ns, Europe/Berlin]', freq='D')
```

Whereas time periods not containing DST do work:

```python
>>> i1 = pd.date_range('2020-03-20', periods=5, freq='D', tz='Europe/Berlin')
>>> i2 = pd.date_range('2020-03-23', periods=5, freq='D', tz='Europe/Berlin')
>>> i1.intersection(i2)
DatetimeIndex(['2020-03-23 00:00:00+01:00', '2020-03-24 00:00:00+01:00'], dtype='datetime64[ns, Europe/Berlin]', freq='D')
```

**Comment by mroeschke** [comment]
Thanks for the report. The set-ops in general have issues dealing with DST transitions (`DatetimeIndex.union` issue https://github.com/pandas-dev/pandas/issues/45863)

**Comment by rwijtvliet** [comment]
My current workaround for anyone interested

```python
def intersection(*indices: pd.DatetimeIndex) -> pd.DatetimeIndex:
    """Intersect several DatetimeIndices.

    Parameters
    ----------
    *indices : pd.DatetimeIndex
        The indices to intersect.

    Returns
    -------
    pd.DatetimeIndex
        The intersection, i.e., datetimeindex with values that exist in each index.

    Notes
    -----
    If indices have distinct timezones or names, the values from the first index are used.
    """
    if len(indices) == 0:
        raise ValueError("Must specify at least one index.")

    distinct_freqs = set([i.freq for i in indices])
    if len(indices) > 1 and len(distinct_freqs) != 1:
        raise ValueError(
            f"Indices must not have equal frequencies; got {distinct_freqs}."
        )

    tznaive = [i.tz is None for i in indices]
    if any(tznaive) and not all(tznaive):
        raise ValueError(
            f"All indices must be either timezone-aware or timezone-naive; got {tznaive} naive from {len(indices)}."
        )

    freq, name, tz = indices[0].freq, indices[0].name, indices[0].tz

    # Calculation is cumbersome: pandas DatetimeIndex.intersection not working correctly on timezone-aware indices.
    values = set(indices[0])
    for idx in indices[1:]:
        values = values.intersection(set(idx))
    idx = pd.DatetimeIndex(sorted(list(values)), freq=freq, name=name, tz=tz)

    return idx
```

**Comment by simonjayhawkins** [comment]
> ### Expected Behavior
> That all timestamps that are in both indices are kept.

expected behavior in pandas-1.3.5

first bad commit: [ba6b4eb3454e6ac145faf1988f6c9b07fc3642f5] REF: dispatch DTI/TDI setops to RangeIndex (#44039)

cc @jbrockmendel

**Comment by simonjayhawkins** [comment]
moving to 1.4.4
