### ISSUE TITLE
DOC/CI: Docs build is broken

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#46706]
Seems like the docs build is failing. There are few of these errors in the build:

```
Exception in /home/runner/work/pandas/pandas/doc/source/user_guide/io.rst at block ending on line 3127
Specify :okexcept: as an option in the ipython:: block to suppress this message
Traceback (most recent call last):

  File ~/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3369 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Input In [339] in <cell line: 1>
    df = pd.read_xml(file_path, elems_only=True)

  File ~/work/pandas/pandas/pandas/util/_decorators.py:311 in wrapper
    return func(*args, **kwargs)

  File ~/work/pandas/pandas/pandas/io/xml.py:1208 in read_xml
    return _parse(

  File ~/work/pandas/pandas/pandas/io/xml.py:946 in _parse
    data_dicts = p.parse_data()

  File ~/work/pandas/pandas/pandas/io/xml.py:[527](https://github.com/pandas-dev/pandas/runs/5874947475?check_suite_focus=true#step:5:527) in parse_data
    self.xml_doc = XML(self._parse_doc(self.path_or_buffer))

  File ~/work/pandas/pandas/pandas/io/xml.py:755 in _parse_doc
    doc = fromstring(

  File src/lxml/etree.pyx:3252 in lxml.etree.fromstring

  File src/lxml/parser.pxi:1913 in lxml.etree._parseMemoryDocument

  File src/lxml/parser.pxi:1800 in lxml.etree._parseDoc

  File src/lxml/parser.pxi:1141 in lxml.etree._BaseParser._parseDoc

  File src/lxml/parser.pxi:615 in lxml.etree._ParserContext._handleParseResultDoc

  File src/lxml/parser.pxi:725 in lxml.etree._handleParseResult

  File src/lxml/parser.pxi:654 in lxml.etree._raiseParseError

  File <string>:1
XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
```
See: https://github.com/pandas-dev/pandas/runs/5874947475?check_suite_focus=true#step:5:569

Seems like it started failing [yesterday](https://github.com/pandas-dev/pandas/actions/workflows/docbuild-and-upload.yml?query=event%3Apush), #46674 is the first PR to fail. But not sure the changes there are the cause, or if anything else has changed. Feels more like an XML being downloaded from the Internet has changed from the error.

This is probably the failing line: https://github.com/pandas-dev/pandas/blame/main/doc/source/user_guide/io.rst#L3118

But the file being opened seems to be set here: https://github.com/pandas-dev/pandas/blame/main/doc/source/user_guide/io.rst#L3069, which seem to be [this one](https://github.com/pandas-dev/pandas/blob/main/pandas/tests/io/data/xml/books.xml), and doesn't seem it changed in months.

**Comment by rhshadrach** [comment]
The most recent commit on main (https://github.com/pandas-dev/pandas/pull/46701) passed. I'm not able to replicate locally; I think this points to an external source going down.

**Comment by datapythonista** [comment]
I see, maybe the file I was checking was broken for a while, but started working again when I checked then. Let's close, and we can have a look if this happens again in the future.
