### ISSUE TITLE
BUG: pser.mode() should not be set series name

### ISSUE THREAD

**Issue by Yikun** [pandas-dev/pandas#46737]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

After 1.4.x:
```python
import pandas as pd
pser = pd.Series([0, 0, 1, 1, 1])
pser.name = 'x'
pser.mode()

pser.mode()
0    1
Name: x, dtype: int64
```

### Issue Description

pser.mode() should not be set series name.

### Expected Behavior

Before 1.4:
```
pser.mode()
0    1
dtype: int64
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.9.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.4.0
Version          : Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : zh_CN.UTF-8
LOCALE           : zh_CN.UTF-8

pandas           : 1.4.2
numpy            : 1.22.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.0.4
setuptools       : 60.5.0
Cython           : None
pytest           : 7.1.0
hypothesis       : None
sphinx           : 3.0.4
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 8.1.1
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.0.1
matplotlib       : 3.2.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 7.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
snappy           : None
sqlalchemy       : 1.4.32
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by Yikun** [comment]
first bad commit: https://github.com/pandas-dev/pandas/commit/680e3723d9960aad15fcb9c3e12c829d6c615952

https://github.com/pandas-dev/pandas/blob/cec066d221cc48a858fcae650d254b5392dd1247/pandas/core/series.py#L2061-L2063

```
 return self._constructor( 
     res_values, index=range(len(res_values))
 ) 
```

**Comment by Yikun** [comment]
@samukweku I think it's only in mode after 1.4.x，so I think it's an unexpected change.

**Comment by henryh9n** [comment]
@Yikun @mroeschke I think the issue here is not that adding `name=self.name` fixed the bug, but that it was missing metadata propagation. I think it should be something like
```python
        return self._constructor(
            res_values, index=range(len(res_values))
        ).__finalize__(
            self, method="mode"
        )
```
similar to all of the other methods. This will not only preserve the name, but also the other attributes (if there are, or will be, any others)
