### ISSUE TITLE
DOC: API reference doesn't list documentation for some general and I/O functions

### ISSUE THREAD

**Issue by alexander3774** [pandas-dev/pandas#46749]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

Expected fiunctions URLs:

https://pandas.pydata.org/docs/dev/reference/api/pandas.to_pickle.html
https://pandas.pydata.org/docs/dev/reference/api/pandas.value_counts.html
https://pandas.pydata.org/docs/dev/reference/api/pandas.lreshape.html

### Documentation problem

I had recently found that pandas docs site doesn't show any documentation for `pd.to_pickle`, `pd.lreshape` and `pd.value_counts` (only for `DataFrame/Series` anologues in some cases). Is it expected behaviour? Is it planned to be added in the further pandas releases?

### Suggested fix for documentation

If it is not expected, these functions can be added in the [general_fucntions](https://github.com/pandas-dev/pandas/blob/main/doc/source/reference/general_functions.rst) and [io](https://github.com/pandas-dev/pandas/blob/main/doc/source/reference/io.rst) rst files.

**Comment by simonjayhawkins** [comment]
Thanks @alexander3774 for the report.

pd.value_counts was explicitly added to the public api in c6cee43ac0d0720958227ebddfb1f62652413436, #1392 so it should be documented. As the function only accepts 1d numpy arrays and not any pandas object then I would also be inclined to remove this for the public api in a future pandas version.

**Comment by simonjayhawkins** [comment]
There has been a suggestion to deprecate pd.lreshape #34313 so we could also consider deliberately leaving it out of the documentation to discourage new users finding it.

**Comment by alexander3774** [comment]
@simonjayhawkins thanks for reply! I think the ticket can be closed since noted functions are considered to be removed from high-level API.
