### ISSUE TITLE
BUG: pandas.testing.assert_frame_equal with check_dtype=False unexpectedly raises an exception

### ISSUE THREAD

**Issue by maciasbed** [pandas-dev/pandas#46756]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas
df1 = pandas.DataFrame({'a': [0, 0, 0]}) 
df2 = pandas.DataFrame({'a': ['0', '0', '0']})
pandas.testing.assert_frame_equal(df1, df2, check_dtype=False)
```

### Issue Description

Raises AssertionError where dataframes are identical, except ignored dtypes.

AssertionError: DataFrame.iloc[:, 0] (column name="a") are different

DataFrame.iloc[:, 0] (column name="a") values are different (100.0 %)
[index]: [0, 1, 2]
[left]:  [0, 0, 0]
[right]: [0, 0, 0]

### Expected Behavior

It should raise no exception as df1 and df2 are identical, except for dtypes.

### Installed Versions

<details>

python: 3.8.13.final0
python-bits: 64
OS: Linux
OS-release: 3.10.0-1160.31.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
pandas: 1.4.1
numpy: 1.21.2
pytz: 2021.3
dateutil: 2.8.2
pip: 21.2.4
setuptools: 58.0.4
bottleneck: 1.3.4

</details>

**Comment by simonjayhawkins** [comment]
Thanks @maciasbed for the report.

> It should raise no exception as df1 and df2 are identical, except for dtypes.

they are not identical, `"0" == 0` is `False`

the following code sample is identical , except for the dtype

```
df1 = pandas.DataFrame({"a": [0, 0, 0]})
df2 = df1.astype(object)
pandas.testing.assert_frame_equal(df1, df2, check_dtype=False)
```

**Comment by mroeschke** [comment]
Agreed, strings and numeric objects cannot be equivalent so this is the expected behavior. Closing
