### ISSUE TITLE
ENH: Partition CSV dataset in some way as PARQUET dataset

### ISSUE THREAD

**Issue by KayvanShah1** [pandas-dev/pandas#46762]
#### Is your feature request related to a problem?

It would be so much easy if we could directly partition CSV data just as parquet and other binary formats.

#### Describe the solution you'd like

`DataFrame.to_csv` should get a new parameter `partition_cols` that _Column names by which to partition the dataset. Columns are partitioned in the order they are given. Must be None if the path is not a string._

`read_csv` should also be made capable of reading partitioned data

#### Additional context

Have found this functionality [here](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.s3.to_csv.html#awswrangler.s3.to_csv)

**Comment by jreback** [comment]
-1 we are not reinventing a file format 

just use parquet
