### ISSUE TITLE
ENH:

### ISSUE THREAD

**Issue by brunorigal** [pandas-dev/pandas#46775]
#### Is your feature request related to a problem?

Currently plotly backend doesn't work for multiindex.

#### Describe the solution you'd like
An easy solution would be to map the multiindex to str before the plot if there is a plotly backend. line 902 of file `pandas/plotting/_core.py`

#### API breaking implications
Nothing as far as I can tell

#### Additional context

```python
df_ = df.copy()
if isinstance(df_.columns, pd.MultiIndex):
    df_.columns = df_.columns.map(lambda x: str(x))
if isinstance(df_.index, pd.MultiIndex):
    df_.index = df_.index.map(lambda x: str(x))
```

**Comment by mroeschke** [comment]
Your pre-processing work-around would be the appropriate solution as pandas does not depend on plotly and it's not scalable or maintainable in the long term to have dependency dependent processing logic in pandas. Thanks for the suggestion, but closing.
