### ISSUE TITLE
WEB: Use mambaforge for the getting started installation instructions?

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#46793]
We've got [this page](https://pandas.pydata.org/getting_started.html) in our website, that is helping users set up a working environment to use pandas. With Anaconda moving to libmamba is probably fine to leave it as it is, but I'd personally use mambaforge in the page, which I think is probably a better choice of tool (smaller, only conda-forge channel, faster, a bit nicer UI). Does anyone think it's better to stay with Anaconda?

**Comment by akaigraham** [comment]
Agree that the benefits of mamba are clear, especially when considering the speed improvements. That being said, I feel getting started with Anaconda is still easier than mamba for most beginners. If I'm not mistaken, mamba depends on conda already being installed.  At the very least, I think mamba should be added to the [advanced installations page](https://pandas.pydata.org/docs/getting_started/install.html) - this page also already includes miniconda instructions and outlines the size of installing via anaconda.

**Comment by datapythonista** [comment]
`mambaforge` can be downloaded as Anaconda, and while conda it's a dependency this is transparent to the user.

**Comment by akaigraham** [comment]
You're right, I agree, advantages are clear so makes sense to me.

**Comment by tjbai** [comment]
Hi! I'm a first-time contributor and noticed this issue was still open—I'd be willing to help add mambaforge installation instructions to the advanced installations page or consider other options if we can reach a consensus on what's best.

**Comment by MarcoGorelli** [comment]
I didn't know about this until coming across this issue, I just did
```
conda install mamba -n base -c conda-forge
mamba env create -f environment.yml 
conda activate pandas-dev
```
and it worked fine - I didn't time it, but it seemed much faster

Happy to have a PR @tjbai

**Comment by datapythonista** [comment]
Mamba started using the conda solver, so this is probably not as important, as the conda solver should stop being useless for environments with several dependencies.

Mamba can be downloaded from mambaforge directly, conda is not required. That's probably the best for the guide, since it's faster and simpler.

I'd still be +1 on replacing conda by mambaforge, even with the conda improvement.
