### ISSUE TITLE
BUG: inplace behavior changes after 1.4.x

### ISSUE THREAD

**Issue by Yikun** [pandas-dev/pandas#46800]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
pdf = pd.DataFrame({"A": range(1, 3), "B": range(4, 6), "C": range(7, 9)})
pser = pdf.A
pdf.eval("A = B + C", inplace=True)
```

### Issue Description

Before 1.4.0:
```
>>> pdf.A
0    11
1    13
Name: A, dtype: int64
>>> pser
0    11
1    13
Name: A, dtype: int64
```

After 1.4.0:
```
>>> pdf.A
0    11
1    13
Name: A, dtype: int64
>>> pser   # <== behavior changed here
0    1
1    2
Name: A, dtype: int64
```

### Expected Behavior

```
>>> pdf.A
0    11
1    13
Name: A, dtype: int64
>>> pser
0    11
1    13
Name: A, dtype: int64
```

### Installed Versions

<details>

1.4.x+

</details>

**Comment by Yikun** [comment]
```python
pdf = pd.DataFrame({"A": range(1, 3), "B": range(4, 6), "C": range(7, 9)})
pser = pdf.A
pdf["A"] = pdf["A"] + 10
pser
pdf.A
```

**Comment by Yikun** [comment]
first change commit: https://github.com/pandas-dev/pandas/commit/03dd698bc1e84c35aba8b51bdd45c472860b9ec3

**Comment by phofl** [comment]
Hi, thanks for your report.

This was wrong before 1.4.0 and works as expected now. This was also announced in the release notes. Setitem should always make a copy and never write into the existing array.
