### ISSUE TITLE
ENH: allow functions in `keep` parameter of `drop_duplicates` to select which data to keep

### ISSUE THREAD

**Issue by Neyri** [pandas-dev/pandas#46809]
#### Is your feature request related to a problem?

I have a dataframe with several duplicated rows and I want to be able to select some kind of aggregate function when dropping duplicates. For instance I would like to keep the mean of a column, the max of another and so on...
I figure this method would be more efficient than a `groupby().apply()` because the function would only be called on duplicates

#### Describe the solution you'd like

For me this would look like something like this :
```python
def func_apply(duplicated_subset):
    # This is just an example
    row = duplicated_subset.iloc[0]
    row["col1"] = duplicated_subset["col1"].mean()
    row["col2"] = duplicated_subset["col2"].max()
    return row

df.drop_duplicates(subset=[...], keep=func_apply)
```
The function passed in parameter would receive a dataframe of rows duplicated and would be called for every duplicates. The function would return a row of the dataframe.

#### API breaking implications

None

#### Describe alternatives you've considered

For now, to achieve this I use the following piece of code 
```python
rows_duplicated = df[df.duplicated(subset=subset, keep=False)]
rows_to_keep = df.drop_duplicates(subset=subset, keep=False)
rows_clean = (
    rows_duplicated.groupby(subset)
    .apply(drop_method)
    .reset_index(drop=True)
)
df_filtered = pd.concat([rows_to_keep, rows_clean]).sort_index()
```
where `drop_method` can vary between what I want to perform. Here are some examples :
```python
def drop_method(df_duplicates):
    row =df_duplicates.iloc[0]
    row["start_date"] = datetime_mean(
        df_duplicates["start_date"]
    )
    row["end_date"] = datetime_mean(
        df_duplicates["end_date"]
    )
    row["speed"] = df_duplicates["speed"].max()
    return row

def drop_method(df_duplicates):
    """
    Returns the row of the dataframe with
    the most number of values (not nan)
    """
    idx_most_values = df_duplicates.notna().sum(axis=1).idxmax()
    return df_duplicates.loc[idx_most_values]

```
#### Additional context

I believe this method could also answer [issue 25838](https://github.com/pandas-dev/pandas/issues/25838)

**Comment by jreback** [comment]
.groupby.apply seems the right answer here (not sure why you are actually doing a whole lot more a 1-liner should just do it here)

i don't really see an efficiency argument as this would likely be how it's implemented under the hood

**Comment by Neyri** [comment]
I am actually not sure because a groupby can return any dataframe schema. So in order get the exact same dataframe as previously without the duplicates, the apply function would have to be applied on every single row not duplicated and return the actual row. Whereas, here, you would only apply it on the (small) subset duplicated.

**Comment by mroeschke** [comment]
Thanks for the issue, but it appears this hasn't gotten traction in a while so closing
