### ISSUE TITLE
BUG: Inconsistent result of in-place Series.rename_index

### ISSUE THREAD

**Issue by xinrong-databricks** [pandas-dev/pandas#46807]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
index = pd.Index(["A", "B", "C"], name="index")]
pdf = pd.DataFrame({"x": [1.0, 2.0, 3.0]}, index=index)
pser = pdf.x
pser.rename_axis("index2", inplace=True)
pdf.x
pdf
```

### Issue Description

The last two statements return as below:
```py
>>> pdf.x
index2
A    1.0
B    2.0
C    3.0
Name: x, dtype: float64

>>> pdf
         x
index     
A      1.0
B      2.0
C      3.0
```

The results look inconsistent.

### Expected Behavior

`pdf` and `pdf.x` should have the same index name.

Or we should ban such operations with an error message
```py
ValueError: This Series is a view of some other array, to ... in-place you must create a copy
```

### Installed Versions

<details>

>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.10.0.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.5.0
Version          : Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.2
numpy            : 1.21.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.2
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : None
matplotlib       : None
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by phofl** [comment]
Hi, thanks for your report.

This is not how inplace works. Inplace does not actually do stuff inplace most of the times, it just reassigns the result so that your reference changes. In this case the change does not propagate back up

**Comment by mroeschke** [comment]
Thanks for the report. Closing as a usage question
