### ISSUE TITLE
ENH: `df.long_eval` wrapping around pivot, eval and melt

### ISSUE THREAD

**Issue by lucasjamar** [pandas-dev/pandas#46801]
#### Is your feature request related to a problem?

Data is often given from APIs in a long format. Groupby operations and plotting are also done with data in long format.
However, arithmethic between categories of a column requires data in wide format. Here is a basic example of what I often need to do:

```python
import pandas as pd
import plotly.express as px

df = pd.DataFrame({"Datetime": ["2020-01-01", "2020-01-02", "2020-01-03", "2020-01-01", "2020-01-02", "2020-01-03"], "Price": [1, 2, 3, 1, 3, 2], "Currency": ["JPY", "JPY", "JPY", "EUR", "EUR", "EUR"]})
df = df.pivot(index="Datetime", values="Price", columns="Currency").reset_index()
df = df.eval("EURvsJPY = EUR - JPY")
df = df.melt(id_vars="Datetime", value_vars=["EURvsJPY", "EUR", "JPY"], value_name="Price", var_name="Currency").reset_index()
df["month"] = df["Datetime"].dt.month
monthly_average = df.groupby("month").mean()
fig = px.line(
 x="month",
 y="Price",
 color="Currency"
)
```

#### Describe the solution you'd like

I would like to create a new functionality called `df.long_eval` which would leverage `df.eval` and wrap around `df.pivot` and `df.melt` as described in the example above. The functionality would look something like this:

```python
spreads = df.long_eval(
  expr="EURvsJPY = EUR - JPY",
  column="Currency",
  values="Price",
  index="Datetime",
  keep_original=True,
  error="raise",
  **kwargs
)
```
`keep_original` would determine whether the previous categories (EUR, JPY) should be kept in the new dataframe and error would be used to handle cases where the category does not exist in the categorical column or if the values are not unique for each index.

Please let me know what you make of this requirement and if this should be implemented differently. I could then try making a pull request :)

**Comment by mroeschke** [comment]
Agreed. Since this functionality is just a composition of existing functionality, this is best left has a custom helper function for users to implement. Closing
