### ISSUE TITLE
BUG: Runtime warning with groupby/tail when `None` appears in group column

### ISSUE THREAD

**Issue by ian-r-rose** [pandas-dev/pandas#46814]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas
df = pandas.DataFrame(
    [
        ["a", 1],
        ["a", 2],
        [None, 0],
        ["b", 2],
        ["b", 3],

    ],
    columns=["x", "y"],
)
df.groupby("x", dropna=False).tail(1)   # Succeeds
df.groupby("x", dropna=True).tail(1)   # Produces warning
```

### Issue Description

:wave: In pandas `main`, a groupby/tail on a DataFrame which contains nulls in the grouped column produces a `RuntimeWarning` suggesting a mishandled case in indexing logic:

```python-traceback
/lib/python3.8/site-packages/pandas/core/groupby/indexing.py:217: RuntimeWarning: invalid value encountered in remainder
  mask &= offset_array % step == 0
```
If I set `dropna=False`, the snippet succeeds without producing a warning.

Based on the warning location and git blame, it may be related to https://github.com/pandas-dev/pandas/pull/42947

### Expected Behavior

The above groupby should succeed without producing a warning.

### Installed Versions

Pandas `main`, as well as 1.4.

**Comment by rhshadrach** [comment]
I'm not seeing this on main or 1.4.x; can you post the output of `pd.show_versions()`.

<details>
<summary>versions</summary>

```
pandas           : 1.4.2+11.gd1717e98a2
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 22.0.4
setuptools       : 62.1.0
Cython           : 0.29.28
pytest           : 7.1.1
hypothesis       : 6.43.3
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.8.0
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.2.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.4
brotli           : 
fastparquet      : 0.8.0
fsspec           : 2021.11.0
gcsfs            : 2021.11.0
markupsafe       : 2.1.1
matplotlib       : 3.5.1
numba            : 0.53.1
numexpr          : 2.8.0
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 3.0.0
pyreadstat       : 1.1.4
pyxlsb           : None
s3fs             : 2021.11.0
scipy            : 1.8.0
snappy           : 
sqlalchemy       : 1.4.35
tables           : 3.7.0
tabulate         : 0.8.9
xarray           : 0.18.2
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None
```

</details>

**Comment by ian-r-rose** [comment]
Update: I ran a git bisect, and for me the warning starts to show up at 4d7a03a33bd46a2ada43c42e781ed0a0ec5ccb7e

**Comment by rhshadrach** [comment]
Thanks, I'm able to reproduce with numpy 1.21.6; no warning appears with numpy 1.22.0.This was a bug that fixed in 1.22.0:

https://github.com/numpy/numpy/issues/18170

We could add a workaround to avoid the warning for numpy < 1.22 by computing a Boolean mask where the array is null.

**Comment by ian-r-rose** [comment]
Thanks @rhshadrach! Upgrading numpy is a fine workaround from my perspective.

**Comment by mroeschke** [comment]
Closing as it seems this was a numpy isssue
