### ISSUE TITLE
DOC: write guide for how to replace append

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#46825]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

Probably as examples in `concat`?

### Documentation problem

There are some common use-cases for `append`, and it's not obvious to newcomers how to use `concat` instead

### Suggested fix for documentation

Include some examples of replacing common use-cases of `append`, such as https://github.com/pandas-dev/pandas/issues/35407#issuecomment-1092892819

**Comment by martinbrose** [comment]
take

**Comment by EwoutH** [comment]
Thanks for creating this issue, I would love some more examples how to replace (complex) cases of append!

**Comment by anetakahle** [comment]
@MarcoGorelli I've added concat<->append examples in #47061
could you take a look please?
