### ISSUE TITLE
REF: avoid passing `self` as arg from ExtensionArray methods

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#46843]
The following functions are called from ExtensionArray methods with `self` as the first argument:

- [ ] nargminmax
- [ ] format_object_summary
- [ ] rank
- [ ] mode

This implicitly means that these functions are depending on EA implementation details (or in some cases just casting to object), which is a code smell.  These should be refactored to use e.g. _values_for_argsort, _values_for_factorize, ...

<b>Update</b> Also in 

- [ ] NDArrayBackedExtensioNArray.argmin
- [ ] NDArrayBackedExtensioNArray.argmax

**Comment by brunocoutinhoo** [comment]
take

**Comment by jorisvandenbossche** [comment]
Specifically for `nargminmax` (didn't check the others), I think that's actually on purpose? The docstring of `nanargminmax` says that is an implementation for extension arrays, and so that is fine to use from the EA class?

**Comment by lucaslarios** [comment]
This issue still relevant?

**Comment by jbrockmendel** [comment]
no, closing.
