### ISSUE TITLE
BUG: ExcelWriter append mode='a' not work

### ISSUE THREAD

**Issue by AgustinPardo** [pandas-dev/pandas#46840]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
with pd.ExcelWriter('file.xlsx', mode='a') as writer:
    df1.to_excel(writer, sheet_name='sheet 1', index=False)

with pd.ExcelWriter('file.xlsx', mode='a') as writer:
    df2.to_excel(writer, sheet_name='sheet 2', index=False)
```

### Issue Description

Pandas version 0.19.2.

I'm trying to append a sheet to a .xlsx file. First I create the file with a sheet in it based on DataFrame df1 (This step works fine):

```python
with pd.ExcelWriter('file.xlsx', mode='a') as writer:
    df1.to_excel(writer, sheet_name='sheet 1', index=False)
```

Then I tried to append a new sheet:

```python
with pd.ExcelWriter('file.xlsx', mode='a') as writer:
    df2.to_excel(writer, sheet_name='sheet 2', index=False)
```

The result is the file.xlsx with only one sheet('sheet 2'). The file was overwrite based on the second step.

### Expected Behavior

I hope as a result to have 1 file ('file.xlsx') with two sheets inside, "sheet 1" and "sheet 2" with its respective info, df1 and df2.
I want to do it in this way because I need to load the existing file and append the new sheet at different point of my code workflow, is worthless to append the two sheets at the same time for my case.

### Installed Versions

<details>
 
 INSTALLED VERSIONS
 ------------------
 commit: None
 python: 3.6.2.final.0
 python-bits: 64
 OS: Linux
 OS-release: 5.10.104-linuxkit
 machine: x86_64
 processor: 
 byteorder: little
 LC_ALL: None
 LANG: C.UTF-8
 LOCALE: en_US.UTF-8
 
 pandas: 0.19.2
 nose: None
 pip: 21.3.1
 setuptools: 36.4.0
 Cython: None
 numpy: 1.11.1
 scipy: None
 statsmodels: None
 xarray: None
 IPython: None
 sphinx: None
 patsy: None
 dateutil: 2.7.3
 pytz: 2018.5
 blosc: None
 bottleneck: None
 tables: None
 numexpr: None
 matplotlib: None
 openpyxl: 2.3.2
 xlrd: 1.1.0
 xlwt: None
 xlsxwriter: None
 lxml: None
 bs4: None
 html5lib: None
 httplib2: 0.10.3
 apiclient: 1.6.2
 sqlalchemy: None
 pymysql: None
 psycopg2: 2.7.5 (dt dec pq3 ext lo64)
 jinja2: 2.10
 boto: None
 pandas_datareader: None

</details>

**Comment by jreback** [comment]
you need to check on a modern version - 1.4.2 is the current

**Comment by AgustinPardo** [comment]
@jreback Thanks for answer. I can't upgrade pandas versions since this is involved in a large protect. Do you know another way that i could do this?

**Comment by wegunterjr** [comment]
I have pandas 1.4.2 and am getting a different error:
`    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
`

**Comment by phofl** [comment]
```
df = pd.DataFrame({"a": [1, 2, 3]})

with pd.ExcelWriter('file.xlsx', engine="openpyxl") as writer:
    df.to_excel(writer, sheet_name='sheet 1', index=False)

with pd.ExcelWriter('file.xlsx', mode='a', engine="openpyxl") as writer:
    df.to_excel(writer, sheet_name='sheet 2', index=False)
```

works for me

**Comment by phofl** [comment]
No on main, we won’t fix anything for a Version that old

**Comment by LFBJC** [comment]
I'm having the same problem, even when using the most recent pandas version, first I tried:

with pd.ExcelWriter(path, mode='a', engine="openpyxl") as f:
            dataframe.to_excel(f, header=False, index=False)

and the code raise an error cause if_sheet_exists is by default set to 'error', then when I try

with pd.ExcelWriter(path, mode='a', engine="openpyxl", if_sheet_exists="replace") as f:
      dataframe.to_excel(f, header=False, index=False)
instead of adding lines to the end of the file it's writing the contents as if it was in write mode

**Comment by hi-nikola** [comment]
> I have pandas 1.4.2 and am getting a different error: ` raise BadZipFile("File is not a zip file") zipfile.BadZipFile: File is not a zip file`

how do u solve this error ?
