### ISSUE TITLE
ENH: Support multiple instances of styler object

### ISSUE THREAD

**Issue by bhishanpdl** [pandas-dev/pandas#46859]
# Feature request
```python
import numpy as np
import pandas as pd

np.random.seed(0)
pd.options.display.float_format = None


df = pd.DataFrame({'a': np.random.rand(1,10)[0],
                  'b': np.random.rand(1,10)[0]})

df_style = df.style.format({'a':"{:.2f}"})
df_style = df_style.format({'b':"{:.2f}"})
df_style # only column b is formatted
```

# What works
```python
df_style = df.style.format({'a':"{:.2f}",'b':"{:.2f}"})
```

# What is requested
```python
df_style = df.style.format({'a':"{:.2f}"})
df_style = df_style.format({'b':"{:.2f}"})
df_style # only column b is formatted
```

Sometimes we have long chain of methods in styler, we may want to additional format down the line for different columns. This might be helpful.

**Comment by attack68** [comment]
This is what is written in the docs:

>>> The `subset` argument defines which region to apply the formatting function to. If the `formatter` argument is given in dict form but does not include all columns within the `subset` then these columns will have the default formatter applied. Any columns in the formatter dict excluded from the subset will be ignored.

Therefore as described `df_style.format({'b':"{:.2f}"})` is reapplying the default formatter to column "a".

Do this instead.

```python
df_style = df.style.format({'a':"{:.2f}"})
df_style = df_style.format({'b':"{:.2f}"}, subset=["b"])
```

or this if you prefer,
```python
d_a = {'a':"{:.2f}"}
df_style = df.style.format(d_a, subset=list(d_a.keys()))
d_b = {'b':"{:.2f}"}
df_style = df_style.format(d_b, subset=list(d_b.keys()))
```

or just this,
```python
df_style = df.style.format("{:.2f}", subset=["a"])
df_style = df_style.format("{:.2f}", subset=["b"])
```
