### ISSUE TITLE
TST: Fix xfail for git component of `pd.show_version` tests on 32 bit builds

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#46856]
Two tests were xfailed in this PR that suddenly failed. https://github.com/pandas-dev/pandas/pull/46842

**Comment by jbrockmendel** [comment]
spitballing: i wonder if we can record when `xfail(strict=False)` tests xpass to try to track down patterns in the relevant conditions

**Comment by mroeschke** [comment]
Yeah possibly we could have an automation flow that reads the `test-data.xml` and when there are xpasses in the logs we can write to an issue

**Comment by simonjayhawkins** [comment]
These tests are also failing on pandas-wheels nightly linux builds https://dev.azure.com/pandas-dev/pandas-wheels/_build?definitionId=3&_a=summary

**Comment by simonjayhawkins** [comment]
skipped on pandas-wheels for now https://github.com/MacPython/pandas-wheels/pull/182 so that nightly builds for Linux are uploaded to https://anaconda.org/scipy-wheels-nightly/pandas/files

**Comment by lithomas1** [comment]
Marking as blocker for release. The wheel filenames will be messed up if this is not fixed(this may prevent pypi uploads).

**Comment by simonjayhawkins** [comment]
> The wheel filenames will be messed up

Thanks @lithomas1 the nightlies did upload but the the wrong prefix `pandas-0+unknown-` instead of `pandas-1.5.0.dev0+849.g3bf2cb1b22-` so were probably of no use. (we may need to delete these from the server)

**Comment by jbrockmendel** [comment]
> tzdata should also probably be added to the optional dependencies

+1
