### ISSUE TITLE
ENH: Dataframe constructor and DataFrame.from_records shoudl allow specifying column dtypes

### ISSUE THREAD

**Issue by jlumpe** [pandas-dev/pandas#46868]
#### Is your feature request related to a problem?

When creating a `DataFrame` from a list of row tuples using either the constructor or `DataFrame.from_rows()`, I often run into issues where the column data type is not inferred correctly. In my specific case I have a mix of `int`s and `None`s and would like to have an `object` dtype, but pandas wants to convert to `float`.

#### Describe the solution you'd like

`read_csv()` has a `dtype` argument that allows setting individual column data types, I think these two methods should have something similar. The constructor does already have a `dtype` argument but it accepts only a single value, and tabular data is very frequently not of a uniform data type. Because the `columns` argument is optional it should probably accept a list/sequence of `dtype`s instead of just a dict keyed by column names as in `read_csv()`.

#### API breaking implications

None, this would add a new optional argument to `DataFrame.from_records()` and expand the allowed values of the `dtype` argument to the constructor without changing the interpretation of currently accepted values.

#### Describe alternatives you've considered

```
df['A'] = df['A'].astype(dtype)
```

may work in a lot of cases, but mine requires an ugly list comprehension to undo the float conversion. Being able to manually specify the column data types seems like a no-brainer.

**Comment by mroeschke** [comment]
Thanks for the report. I think this was discussed in the past and was not moved forward with because `astype` has more thorough dtype conversion handling than the constructors. (`astype` also takes a dict of column label -> type such that a list comprehension is not needed)

**Comment by phofl** [comment]
Covered by #4464
