### ISSUE TITLE
PERF: numpy function like np.max called on DataFrame significantly slower than df.max

### ISSUE THREAD

**Issue by auderson** [pandas-dev/pandas#46874]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this issue exists on the main branch of pandas.

### Reproducible Example

related: #45099

```python
df = pd.DataFrame(np.random.randn(100, 100))
```
```python
%%time
_ = df.max()
```
CPU times: user 913 µs, sys: 1.6 ms, total: 2.52 ms
Wall time: 1.81 ms
```python
%%time
_ = np.max(df)
```
CPU times: user 13.8 ms, sys: 290 µs, total: 14.1 ms
Wall time: 12.8 ms
```python
%%pyinstrument
_ = np.max(df)
```

![image](https://user-images.githubusercontent.com/48577571/165252677-175a1f21-0a09-4ed2-829e-49279b32d848.png)

Looks like this is triggered by:
https://github.com/pandas-dev/pandas/blob/8980af7ce9d98713b0f8792e38f0fe43088e8780/pandas/core/generic.py#L10674-L10683

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.8.0-63-generic
Version          : #71-Ubuntu SMP Tue Jul 13 15:59:12 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.1
numpy            : 1.21.5
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : 0.29.28
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : 1.0.2
psycopg2         : 2.9.3
jinja2           : 3.0.3
IPython          : 8.1.1
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
fastparquet      : None
fsspec           : 2022.02.0
gcsfs            : None
matplotlib       : 3.5.1
numba            : 0.55.1
numexpr          : 2.8.0
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 7.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
sqlalchemy       : 1.4.32
tables           : 3.7.0
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
</details>

**Comment by auderson** [comment]
Maybe we can detect if warnings are filtered before calling `warnings.warn`.

**Comment by MarcoGorelli** [comment]
Well spotted - shouldn't the default value for `axis` be `lib.no_default`, rather than `None` here

https://github.com/pandas-dev/pandas/blob/8980af7ce9d98713b0f8792e38f0fe43088e8780/pandas/core/generic.py#L10657-L10666

?

cc @jbrockmendel looks like that was set in https://github.com/pandas-dev/pandas/pull/45072

**Comment by auderson** [comment]
> looks like the `None` is handed down directly from `numpy`, so the default value here wouldn't have an effect

Yes, that's in:
https://github.com/numpy/numpy/blob/fd646bd693400ce408566674f266407672248cad/numpy/core/fromnumeric.py#L69-L86

**Comment by lithomas1** [comment]
If find_stack_level is the issue here, we could try backporting #45247. Can you try benchmarking again on main?

**Comment by auderson** [comment]
Sorry, I forgot to update my local main branch with upstream.
Now on main this seems to have been fixed:
![image](https://user-images.githubusercontent.com/48577571/165428030-fae7c3f8-e64c-4572-b6f1-f8ab0f8002a0.png)

**Comment by jbrockmendel** [comment]
> cc @jbrockmendel looks like that was set in https://github.com/pandas-dev/pandas/pull/45072

IIRC we have imlpemented the deprecation for min/max but not the others, so weren't ready to change it over here. that may be out of date
