### ISSUE TITLE
BUG: DataFrame.select_dtypes(include='number') includes BooleanDtype columns

### ISSUE THREAD

**Issue by macks22** [pandas-dev/pandas#46870]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({
    'a': [1, 2, 3],
    'b': pd.Series([True, False, True], dtype=pd.BooleanDtype()),
})
print(df.select_dtypes(include='number').columns)
# Output: Index(['a', 'b'], dtype='object')
```

### Issue Description

The `DataFrame.select_dtypes` method includes columns with `dtype` of `BooleanDtype` when `include='number'` is given as a kwarg. This is different than the behavior for columns with `dtype` of `bool` and seems like a bug.

### Expected Behavior

The code above should output: `Index(['a'], dtype='object')`

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.9.12.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Tue Feb 22 21:10:41 PST 2022; root:xnu-7195.141.26~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.2
numpy            : 1.21.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 59.8.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.2.0
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.4
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : None
matplotlib       : None
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by MichaelRocchio** [comment]
take

**Comment by MichaelRocchio** [comment]
Hey @macks22 I am going to work on recreating this. I will let you know if I have any questions.

**Comment by MichaelRocchio** [comment]
So I think there is an issue with function differentiating between what it considers to be bool vs boolean datatypes which could be a larger issue. 

Here are my examples:

```python
import pandas as pd

df = pd.DataFrame({
'a': [1, 2, 3],
'b': [True, False, True],
'c': [1.0, 2.0,3.0]})

print(df.select_dtypes(include='number').columns)
print('')
print(df.info())
```
Index(['a', 'c'], dtype='object')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       3 non-null      int64  
 1   b       3 non-null      bool   
 2   c       3 non-null      float64
dtypes: bool(1), float64(1), int64(1)
memory usage: 179.0 bytes
None

```python
import pandas as pd

df = pd.DataFrame({
'a': [1, 2, 3, 4],
'b': pd.Series([True, False, True, False], dtype=pd.BooleanDtype()),
'c': [1.0, 2.0,3.0,4.0]})

print(df.select_dtypes(include='number').columns)
print('')
print(df.info())
```
Index(['a', 'b', 'c'], dtype='object')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       4 non-null      int64  
 1   b       4 non-null      boolean
 2   c       4 non-null      float64
dtypes: boolean(1), float64(1), int64(1)
memory usage: 200.0 bytes
None

I forked pandas and created the following branch for my debugging: 
https://github.com/MichaelRocchio/pandas/tree/issue_46870

**Comment by MichaelRocchio** [comment]
@simonjayhawkins - Thank you for the help, I will take a look at that milestone

**Comment by MichaelRocchio** [comment]
@simonjayhawkins 
I was able to solve this problem but I am unsure how to proceed. Do I create a pull request or does this being assigned to a milestone change something? 

The bug was in the following location:
pandas/core/arrays/boolean.py

my change is pushed to https://github.com/MichaelRocchio/pandas/tree/issue_46870 

It was pretty small:
```python
    @property
    def _is_numeric(self) -> bool:
        return True
```
changed to:

```python
    @property
    def _is_numeric(self) -> bool:
        return False
```

Additionally I will need help on how to test if my fix didn't cause other issues.

**Comment by simonjayhawkins** [comment]
moving to 1.4.4
