### ISSUE TITLE
Provide dtypes as args

### ISSUE THREAD

**Issue by MarioNavarrete** [pandas-dev/pandas#46872]
Is there any chance to be able to define the dtype we need for this operation?

https://github.com/pandas-dev/pandas/blob/4bfe3d07b4858144c219b9346329027024102ab6/pandas/core/reshape/util.py#L39

**Comment by mroeschke** [comment]
Thanks for the issue. Could you please fill out the `Feature Request` template here instead?: https://github.com/pandas-dev/pandas/issues/new/choose

It will help the triage team better understand the context for this inquiry. Thanks
