### ISSUE TITLE
ENH: How to keep going if the error has suggest config or modify?

### ISSUE THREAD

**Issue by showkeyjar** [pandas-dev/pandas#46887]
#### Is your feature request related to a problem?

I offten used those code:

se1 = pd.Series({'a1': 1, 'a2': 2})
df = df.append(se1)

and I always forgot add " ignore_index=True "

and then code run error, 

and I return edit it, and add it, waste a lot of time.

#### Describe the solution you'd like

I found that the error message can recognize the problem, and give me a suggest,

and the suggest always right, so I'm wondering, 

why not ignore this? is it throw errors is the simple the best way? 

so, I recommend add a feature: 

it can ignore the meaningless error or the error have suggests.

#### API breaking implications

for example:

give user a option: 

ignore_suggest_error=True

if set true, then keep running and not interupt by the meaningless error.

#### Describe alternatives you've considered

or user can recieve the warning message instead of error.

#### Additional context

```python
# Your code here, if applicable

```
Very grateful for your attention, hope this to be true!

**Comment by MarcoGorelli** [comment]
hi - `append` is deprecated, so new features to it won't be accepted
