### ISSUE TITLE
Leading zeros in data for read_excel vs read_csv

### ISSUE THREAD

**Issue by ppinkhasov** [pandas-dev/pandas#46895]
input file is 6 random zip codes. the first one being "02494" with a column header called 'Zip'

```
test_file = pd.read_excel("test_zips.xlsx", header=0, dtype={'Zip':object})
print(test_file)

print("\n")

test_file = pd.read_excel("test_zips.xlsx", header=0, converters = {'Zip': str})
print(test_file)
```

output
```

     Zip
0   2494
1  12010
2  97007
3  14224
4  80922
5  12205


     Zip
0   2494
1  12010
2  97007
3  14224
4  80922
5  12205`


```
-- but using read_csv works fine

as you can see leading 0 is there. 

![image.png](https://images.zenhubusercontent.com/61f81fdbdd773ff0fa4c9806/267c8a55-6e24-453f-8777-ab704fab6d81)

**Comment by rhshadrach** [comment]
Thanks for the report; I'm not able to reproduce on main. Can you include:

 - The excel file used (attach to the OP)
 - the output of `pd.show_versions()`
 - If you know, the reader you are using (it's most likely openpyxl)

**Comment by janetatomas12** [comment]
take

**Comment by janetatomas12** [comment]
Hi.
When I create excel file as suggested, I can not enter number starting with zero.
Is your cell in some specific format ? If not, then I think Excel automatically discards zero from the beggining.

I also checked with some python packages for parsing excell - same behaviour (xlrd, openpyxl).

Correct me. if I am wrong.
