### ISSUE TITLE
BUG: `MultiIndex.dtypes` index behavior changes after 1.4.x

### ISSUE THREAD

**Issue by Yikun** [pandas-dev/pandas#46900]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example
After 1.4.x:
```python
arrays​ ​=​ [[​1​, ​1​, ​2​, ​2​], [​"red"​, ​"blue"​, ​"red"​, ​"blue"​]]
pmidx = pd.MultiIndex.from_arrays(arrays, names=[("zero", "first"), ("one", "second")])
>>> pmidx.dtypes.index
Index([('zero', 'first'), ('one', 'second')], dtype='object')
```

### Issue Description

dtypes index behavior changes.

### Expected Behavior
```
pmidx = pd.MultiIndex.from_arrays(arrays, names=[("zero", "first"), ("one", "second")])
>>> pmidx.dtypes.index
MultiIndex([('zero',  'first'),
            ( 'one', 'second')],
           )
```
### Installed Versions

<details>

pandas 1.4.2

</details>

**Comment by Yikun** [comment]
https://github.com/pandas-dev/pandas/commit/d06fb912782834125f1c9b0baaea1d60f2151c69

cc @johnzangwill

**Comment by rhshadrach** [comment]
Thanks for the report - can you add the values of `arrays` to your example in the OP.

**Comment by Yikun** [comment]
@rhshadrach Sorry before, added.

**Comment by simonjayhawkins** [comment]
> [d06fb91](https://github.com/pandas-dev/pandas/commit/d06fb912782834125f1c9b0baaea1d60f2151c69)

xref #45175
