### ISSUE TITLE
CLN:  handling of categorical with dropna=False in Grouping._codes_and_uniques

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#46909]
#46601 fixed using categorical with dropna=False in groupby by avoiding the categorical-specific logic in Grouping._codes_and_uniques. While this allowed for correct results, it seems better to fix the categorical-specific logic to handle dropna=False.

Avoiding the categorical-specific logic may also have some performance impact, I plan to benchmark it shortly.

**Comment by phofl** [comment]
@rhshadrach Is there a quick fix that we can backport? This caused a couple of regressions it seems

**Comment by rhshadrach** [comment]
Thanks - ref: #48645. I'm looking into it.
