### ISSUE TITLE
BUG:  Groupby does not work with mean/sum function on columns

### ISSUE THREAD

**Issue by nilslacroix** [pandas-dev/pandas#46916]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
Just use
df.groupby("CategoricalFeature")["NumericalFeature"].mean()

or

df.groupby("CategoricalFeature")["NumericalFeature"].sum()

will return NaN over the whole index for me.
```

### Issue Description

When I try to group my dataframe by a categorical feature and take the mean of a numerical feature it returns NaN for all values. The Dataframe does not consist any NaN values, which I double checked. The problems seems to be the number of categories > 8000 since it does not happen with features which have a lower number. Converting the categorical features to a string solves the issue.

### Expected Behavior

I would expect the dataframe to be grouped by the categorical features while the respective mean for each unique feature is taken and applied

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.9.12.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : de_DE.cp1252

pandas           : 1.4.2
numpy            : 1.21.0
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 22.0.4
setuptools       : 62.1.0
Cython           : 0.29.28
pytest           : 7.1.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.1
IPython          : 8.2.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : 
fastparquet      : None
fsspec           : 2022.3.0
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : 3.5.1
numba            : 0.55.1
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by nilslacroix** [comment]
I can not reproduce this with a simple dataset. Is that maybe due to the fact that is use a categorical type column to groupby?

**Comment by nilslacroix** [comment]
I have this categorical column where the groupby statement works:
![image](https://user-images.githubusercontent.com/56065345/166151330-bc5b5682-8c3c-454b-8fcf-f2fff7dc8204.png)
But when I try it on this feature it does not work:
![image](https://user-images.githubusercontent.com/56065345/166151368-bbd568a9-260e-4900-b02e-828d44a5d108.png)

I am a bit clueless, as said before there are no NaN values, but it seems groupby does not work on the postcode column and only returns NaN values.

**Comment by attack68** [comment]
You need to provide a minimal reproducible example. It is not possible for developers to debug your code without data, and it is not pleasurably to have to become familiar with your data before solving any issues.

**Comment by phofl** [comment]
Closing. Please ping to reopen, if you can provide a reproducible example
