### ISSUE TITLE
BUG: importing Matplotlib failed on python 3.9 

### ISSUE THREAD

**Issue by naiborhujosua** [pandas-dev/pandas#46913]
I am using a windows 10 machine and using Anaconda 1.2.3. I attempted to Import matplotlib.pyplot and got an error. It has been working fine until yesterday. However, it did not work 

### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt
import xgboost as xgb
from xgboost import plot_importance, plot_tree
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.model_selection import RandomizedSearchCV
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingRandomSearchCV
# --- Set defaults of the notebook ---
``python
sns.set(font="'Source Code Pro', monospace")
plt.rcParams["font.family"] = "'Source Code Pro', monospace"
import warnings
warnings.filterwarnings("ignore")
# Color Palettes
treasure_colors = ["#703728", "#c86b25", "#dc9555", "#fed56f", "#c89a37"]
pirate_colors = ["#010307", "#395461", "#449FAF", "#B1F4FC", 
                 "#F4D499", "#835211"]
``
```

### Issue Description

I used python 3.9 and found this bug ImportError: cannot import name 'animation' from partially initialized module 'matplotlib' (most likely due to a circular import) when trying to install either matplotlib or seaborn 

### Expected Behavior

The import does not work as usual as I use python 3.9

### Installed Versions

<details>

Replace this line with the output of 

INSTALLED VERSIONS
------------------
commit           : f2c8480af2f25efdbd803218b9d87980f416563e
python           : 3.9.12.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.2.3
numpy            : 1.22.3
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.1
setuptools       : 58.1.0
Cython           : 0.29.23
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.2.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
sqlalchemy       : None
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : 2.0.1
xlwt             : None
numba            : None

</details>

**Comment by MarcoGorelli** [comment]
Hi - how is this related to pandas?

**Comment by naiborhujosua** [comment]
I just put in the wrong GitHub repo. it should have been put to matplotlib repo.
my apologies.
