### ISSUE TITLE
QST: Problem in output excel with big float numbers

### ISSUE THREAD

**Issue by BrenoJesusFernandes** [pandas-dev/pandas#46923]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/72069254/pandas-to-excel-output-float-point-is-not-right

### Question about pandas

I have some a weird situation trying to get the output in to_excel pandas function engine.

I tried to read a xlsx excel file with the number "21631706.9893399", but when a try to write in a new xlsx excel file gives me the output "21631706.98934". I tested with openpyxl and xlsxwriter but I got the same results, however if I tried to write a xls excel with xlwt engine it gives me the right answer, is there a way to read and write the same float number with these engines? I suspect there some float limitations in xlsx file, but in the xlsx input the number is fine. By the way, it is not a question about formating number, the ouput number is actually different from the original input.

My code:

```
import pandas as pd

df = pd.read_excel(r'input\sample.xlsx')

df.to_excel(r'output\excel xlsx - xlsxwriter.xlsx', engine='xlsxwriter', index=False)
df.to_excel(r'output\excel xlsx - openpyxl.xlsx', engine='openpyxl', index=False)
df.to_excel(r'output\excel xls - xlwt.xls', engine='xlwt', index=False)
```
[Github Example](https://github.com/brenojesusfernandes/pandas-to-excel-test)

Dependencies:

python = "3.7.4"
pandas = "1.3.5"
XlsxWriter = "3.0.3"
openpyxl = "3.0.9"
xlwt = "1.3.0"

**Comment by RyuuOujiXS** [comment]
Are you sure it's not your IDE shortening the number for display purposes? Is the number still cutoff when you print that specific value (ie print(DataFrame[label][index]))?
