### ISSUE TITLE
ENH: pandas.Series.dt.tz_convert does not handle numpy.nan() values

### ISSUE THREAD

**Issue by aditya-shirke** [pandas-dev/pandas#46927]
#### Is your feature request related to a problem?

I wish I could use pandas to do:
pandas.Series.dt.tz_convert to handle numpy.nan values
If the data is from Google Bigquery, it does not return None (handled in 1.4.2) as type. It sends numpy.nan if you took the data into dataframe. Thus, it would be awesome to handle this condition as well.

#### Describe the solution you'd like

pandas.Series.dt.tz_convert handling numpy.nan values in the input

#### Describe alternatives you've considered

I think workaround for this would be to change np.nan() values to None in the dataframe column as None is handled by tz_convert. 

#### Additional context

Please find following code to replicate this. This should be an easy fix.

```python
import pandas as pd
import numpy as np
# just to create a sample dataframe
dti = pd.date_range(start='2014-08-01 09:00',
                    freq='H', periods=3, tz='Europe/Berlin')
# following line will give you error: "TypeError: 'float' object is not callable"
dti.tz_convert(np.nan())
```

**Comment by mroeschke** [comment]
Please review the documentation for np.nan: https://numpy.org/doc/stable/reference/constants.html?#numpy.nan

Additionally, it sounds like you want `astype`: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.astype.html

`tz_convert` converts between _timezones_, not data types.

**Comment by aditya-shirke** [comment]
Ohh, I might be not formulating the question in right way.

Kindly look for following test code

```python
import pandas as pd
import numpy as np

# given
input_test = {
     "default_timestamp": [1640173169789, 1640194564227, 1649045713742, 1647797086010, 164779708880],
     "location_timezone": ["Asia/Baku", "Asia/Baku", "America/Argentina/Rio_Gallegos", "Asia/Baku", np.nan]
}

it = pd.DataFrame(input_test)

# then
it["is_weekend"] = it.apply(lambda row: 0 if \
                          pd.to_datetime(row['default_timestamp'], unit='ms')\
                          .tz_localize('UTC') \
                          .tz_convert(row['location_timezone']) \
                          .dayofweek < 5 else 1 , axis=1)

```

**Comment by mroeschke** [comment]
As the tz_convert docstring details, this function only takes a string or tzinfo object: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.tz_convert.html

I don't think it's sensible for this function to handle `np.nan` as it's not clear what that would represent. I suggest preprocessing your timezone data to fill `np.nan` with your desired alternative behavior.
