### ISSUE TITLE
string getitem methods are slow

### ISSUE THREAD

**Issue by hayd** [pandas-dev/pandas#4694]
related #2802

It seems that str[1] is significantly slower than `.apply(lambda x: x[1])`

See this So answer http://stackoverflow.com/a/18473330/1240268

**Comment by brandon-rhodes** [comment]
Is anyone working on this currently? Would I be duplicating effort if I were to look into possible quick wins for at least getting these slow `str` routines a bit faster?

**Comment by jreback** [comment]
@brandon-rhodes don't think so. would be great!

prob DO need some asv benchmarks for these.

**Comment by 3vts** [comment]
Is this still an ongoing effort? I would like to give it a try

**Comment by brandon-rhodes** [comment]
@3vts Feel free to give it a try! I did not wind up with time to make progress on it, and my guess is that the project I was on that needed the extra performance found a workaround. To be honest, I had, alas, forgotten all about it in the intervening years.

**Comment by mroeschke** [comment]
This is fairly fast with the new pyarrow string type which have a lot of benefits over the string object implementation so closing for now. Can reopen if there are specific hotspots that are addressable
