### ISSUE TITLE
BUG: pd.DataFrame.sum with min_count changes dtype if result contains NaNs

### ISSUE THREAD

**Issue by kdebrab** [pandas-dev/pandas#46947]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
>>> import numpy as np
>>> import pandas as pd
>>> df = pd.DataFrame({'a': [1., 2.3, 4.4], 'b': [2.2, 3, np.nan]}, dtype='float32')
>>> df.sum(axis=1, min_count=1).dtype
dtype('float32')  # OK
>>> df.sum(axis=1, min_count=2).dtype
dtype('float64')  # not OK
>>> df.sum(axis=1, skipna=False).dtype
dtype('float32')  # OK
```

### Issue Description

When using min_count, the dtype of the result depends on whether the result contains a NaN or not.

### Expected Behavior

The resulting dtype should be the same as the dtype of the original DataFrame, also when the result contains NaNs.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.10.2.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19043
machine          : AMD64
processor        : Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252
pandas           : 1.4.2
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 22.0.4
setuptools       : 58.1.0
Cython           : None
pytest           : 7.0.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.8.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.1
IPython          : 8.1.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.4
brotli           : None
fastparquet      : None
fsspec           : 2022.02.0
gcsfs            : None
markupsafe       : 2.1.0
matplotlib       : 3.5.1
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 7.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
snappy           : None
sqlalchemy       : 1.4.32
tables           : None
tabulate         : 0.8.9
xarray           : 2022.3.0
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by Anupam-USP** [comment]
I want to take this issue. Is there any reference to take help?

**Comment by simonjayhawkins** [comment]
thanks @Anupam-USP 

things look good upto the `_maybe_null_out` call from `nansum` in pandas/core/nanops.py

https://github.com/pandas-dev/pandas/blob/f7dda79c5d2569790f5aa887d158e54010386173/pandas/core/nanops.py#L626-L629

where the code sample for the failing case gets cast to float64 here

https://github.com/pandas-dev/pandas/blob/f7dda79c5d2569790f5aa887d158e54010386173/pandas/core/nanops.py#L1475
