### ISSUE TITLE
ENH: print location of input error when reading file

### ISSUE THREAD

**Issue by ifly6** [pandas-dev/pandas#46956]
#### Is your feature request related to a problem?

I wish Pandas would tell you where a parse error occurred when trying to read a delimited file.

#### Describe the solution you'd like

When reading a file, for example, `pd.read_csv(io.StringIO('1\n2\na'), names=['A'], dtype={'A': 'float'})` should give an error more descriptive than, paraphrasing, `ValueError: a is not a number` and should instead return information as to the location of the input the the file that gave rise to the error (line 3, column 1, if in natural numbers).

#### API breaking implications

As far as I can tell, it should be something within the file handling code that would change no API parameters etc.

#### Describe alternatives you've considered

Looking at the input file is an alterative. It is also an alternative that is not feasible when the data you are dealing with has a billion rows and 300 columns.

**Comment by phofl** [comment]
This is not done in the same place. We parse the input file and store the data in arrays. Afterwards we are casting the dtypes, where the error happens. Indices are not readily available there and might also be wrong, if for example bad lines were skipped.

**Comment by mroeschke** [comment]
Thanks for the request but as mentioned this really isn't too feasible given how `read_csv` works. Your best bet is to use `on_bad_lines` to log these lines somehow so closing
