### ISSUE TITLE
ENH: Dictionary based hatch for df.plot

### ISSUE THREAD

**Issue by Wheest** [pandas-dev/pandas#46965]
#### Is your feature request related to a problem?

When using `df.plot`, we can set the colors of bars using a dictionary, e.g.:

```python
df = pd.DataFrame(np.random.rand(10, 4), columns=["a", "b", "c", "d"])

colors = {"a": "red", "b": "blue", "c": "green", "d": "red"}
df.plot(kind="bar", color=colors, hatch="/");
```
![image](https://user-images.githubusercontent.com/16022573/167262584-1c58723b-8ebf-42d6-8ae5-d3439cdd6940.png)

However, we cannot do the same with hatches.  This can only be set on a global level as far as I can tell.

#### Describe the solution you'd like

`DataFrame.plot()` should be able to take a dictionary of hatches, and set them in the same way as `color`.

E.g., 

```python
df = pd.DataFrame(np.random.rand(10, 4), columns=["a", "b", "c", "d"])

colors = {"a": "red", "b": "blue", "c": "green", "d": "red"}
hatches = {"a": "/", "b": "o", "c": "", "d": "x"}

df.plot(kind="bar", color=colors, hatch=hatches);
```

#### Describe alternatives you've considered

There are [StackOverflow discussions](https://stackoverflow.com/questions/22833404/how-do-i-plot-hatched-bars-using-pandas#22836353) of this feature, where users have suggested hacks and workarounds to this, using native matplotlib.

E.g. [this answer](https://stackoverflow.com/a/48507993/6267719)

```python
bars = ax.patches
patterns =('-', '+', 'x','/','//','O','o','\\','\\\\')
hatches = [p for p in patterns for i in range(len(df))]
for bar, hatch in zip(bars, hatches):
    bar.set_hatch(hatch)

```

However, having it integrated in pandas, with the advantages of using a dictionary of column names would be preferable.

**Comment by brurosa** [comment]
take

**Comment by brurosa** [comment]
take

**Comment by mroeschke** [comment]
Thanks for the issue, but it appears this hasn't gotten traction in a while so closing
