### ISSUE TITLE
merge.py 

### ISSUE THREAD

**Issue by qsdcfd** [pandas-dev/pandas#46968]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

 from pandas._typing import

### Installation Method

pip install

### pandas Version

1.3.5

### Python Version

3.73

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by mroeschke** [comment]
Thanks for the report but doesn't look like there's enough information to reproduce. If you're still experiencing issue with a fresh environment, please fill out the `Installation Logs` section with the traceback
