### ISSUE TITLE
ENH: Support conditional selection for DataFrame.at

### ISSUE THREAD

**Issue by EmreAtes** [pandas-dev/pandas#46977]
#### Is your feature request related to a problem?

If I'm trying to get a single element from a dataframe, I usually use `df.values[0]`, because a selection returns a cell with a single element:
```python
>>> df = pd.DataFrame({'a': [1,2,2], 'b': [4,5,6]})
>>> df
   a  b
0  1  4
1  2  5
2  2  6
>>> df.loc[df['a'] == 1, 'b']  # Can't be passed to most other functions that expect an int
0    4
Name: b, dtype: int64
>>> df.loc[df['a'] == 1, 'b'].values[0]
4
```
However, this can be error-prone when a selection returns multiple rows:
```python
>>> df.loc[df['a'] == 2, 'b'].values[0] # User doesn't know that 6 is also a valid result for this query
5
>>> df.loc[df['a'] == 2, 'b']
1    5
2    6
Name: b, dtype: int64
```

#### Describe the solution you'd like
Supporting `.at` for conditional selections would help get rid of a subset of bugs that `.values[0]` pattern causes:
```python
>>> df.at[df['a'] == 1, 'b']
4
>>> df.at[df['a'] == 2, 'b']
KeyError: '2 rows match the selection'
```

#### API breaking implications

Currently, using `.at` in the proposed way raises an exception, but it will no longer be the case if the FR is implemented:
```python
>>> df.at[df['a'] == 1, 'b']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pandas/core/indexing.py", line 2275, in __getitem__
    return super().__getitem__(key)
  File "/usr/lib/python3/dist-packages/pandas/core/indexing.py", line 2222, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/usr/lib/python3/dist-packages/pandas/core/frame.py", line 3579, in _get_value
    loc = engine.get_loc(index)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 82, in pandas._libs.index.IndexEngine.get_loc
TypeError: '0     True
1    False
2    False
Name: a, dtype: bool' is an invalid key
```

#### Describe alternatives you've considered

1. A new API instead of `.at` that does the same thing would also work, but since C++ already uses `.at` for a similar thing it seems reasonable to expand it.

2. Another alternative is to write helper methods that do the same thing, but it's much easier to just reach for `.loc` instead of doing this:
```python
>>> def get_single_value(df, row_selector, col_selector):
...   tmp = df.loc[row_selector, col_selector]
...   assert tmp.shape == (1,)
...   return tmp.values[0]
... 
>>> get_single_value(df, df['a'] == 1, 'b')
4
>>> get_single_value(df, df['a'] == 2, 'b')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in get_single_value
AssertionError
```
#### Additional Considerations
I can try to work on the implementation as well if the API seems reasonable.

**Comment by attack68** [comment]
If the objective is to error trap when the your conditional has multiple results I think the easiest thing to do is a refactor:

```python
cond = df.index[df['a'] == 1]
if len(cond) > 1:
    raise KeyError("more than one element satisfy condition")
df.loc[cond[0], "col"]  # <- returns single element
```

But the suggestion to `.at` in my opinion merits a look. Particulalrly when an `Index` object contains only a single object it might be worth expecting `.at` to operate:

E.g.

```python 
cond = df.index[df['b'] == 5]  # <- is an index object with only 1 element
df.at[cond, "a"]  # InvalidIndexError: Int64Index([1], dtype='int64') -  should return a scalar ??
```

**Comment by jreback** [comment]
.at is a pair of scalars to select 

-1 on anything thing else - indexing is already too complicated

**Comment by EmreAtes** [comment]
Wow! I didn't know about `.item()`, but it perfectly solves my problem. I wish it was better documented (I mentioned it here https://stackoverflow.com/questions/16729574/how-to-get-a-value-from-a-cell-of-a-dataframe, but maybe recommending it in the docs for `.at` or `.values` could be a good idea.). 

Feel free to close the issue since `.item()` is just as elegant as `.at`.

**Comment by simonjayhawkins** [comment]
> but it perfectly solves my problem

ok. closing this.
