### ISSUE TITLE
BUG: to_pydatetime not effective if some values are NaT

### ISSUE THREAD

**Issue by rafalkrupinski** [pandas-dev/pandas#46975]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
a = pd.Series(pd.date_range('20180310', periods=2)).to_frame()
b=pd.Series([None], dtype=object)
df=pd.concat([a, b])
df=df.astype('datetime64[ns]')
df[0]=df[0].dt.to_pydatetime()
df.info()
```

### Issue Description

When called df.dt.to_pydatetime() on a DataFrame column with NaT values, the result is immediately converted back to Timestamp upon assignment.

### Expected Behavior

The Series should remain of time datetime.datetime after assignment

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.0-14-amd64
Version          : #1 SMP Debian 5.10.113-1 (2022-04-29)
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : pl_PL.UTF-8
LOCALE           : pl_PL.UTF-8

pandas           : 1.4.1
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.0.4
setuptools       : 62.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.1.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 7.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

~/.local/pipx/shared/lib/python3.9/site-packages/_distutils_hack/__init__.py:17: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
~/.local/pipx/shared/lib/python3.9/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

</details>

**Comment by simonjayhawkins** [comment]
Thanks @rafalkrupinski for the report.

> When called df.dt.to_pydatetime() on a DataFrame column with NaT values, the result is immediately converted back to Timestamp upon assignment.

IIRC we may have some other issues concerning the coercion of datetime objects to pandas Timestamp and that it is a design choice.

I think you need to be more explicit in the assignment to get a series of object dtype containing datetime objects, `df[0] = pd.Series(df[0].dt.to_pydatetime(), dtype=object, index=df.index)`

**Comment by mroeschke** [comment]
Agreed, `datetime.datetime` objects are generally always converted into `pandas.Timestamp` unless `dtype=object` is specified. Closing as this is the intentional behavior
