### ISSUE TITLE
BUG: Style.set_sticky() doesn’t work with dark mode

### ISSUE THREAD

**Issue by flying-sheep** [pandas-dev/pandas#46984]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.
- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

In Jupyterlab, with dark mode active:

```python
import pandas as pd

display(pd.DataFrame(dict(a=[1])).style.set_sticky())
```

### Issue Description

Calling this makes the row/column headers disappear (white text on white background)

### Expected Behavior

Background color should adapt to theme or at least foreground color should also be set

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.8.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.181-99.354.amzn2.x86_64
Version          : #1 SMP Wed Mar 2 18:50:46 UTC 2022
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.0
numpy            : 1.21.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.0.3
setuptools       : 59.8.0
Cython           : None
pytest           : 7.0.0
hypothesis       : None
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.2
lxml.etree       : 4.8.0
html5lib         : None
pymysql          : None
psycopg2         : 2.9.3
jinja2           : 3.0.3
IPython          : 8.0.1
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
fastparquet      : 0.8.1
fsspec           : 2022.01.0
gcsfs            : None
matplotlib       : 3.5.1
numba            : 0.55.1
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
sqlalchemy       : 1.4.31
tables           : 3.7.0
tabulate         : 0.8.9
xarray           : None
xlrd             : 1.2.0
xlwt             : None
zstandard        : None

</details>

**Comment by attack68** [comment]
suggestions how to make this compatible in a more general sense are welcome

**Comment by attack68** [comment]
The above PR generally works but causes the issue when scrolling if cells are transparent. This is visible in the new 1.5.0 dev docs..

Before this PR..
![Screenshot 2022-06-22 at 10 23 03](https://user-images.githubusercontent.com/24256554/174980860-22fe87a9-5e46-4767-83e2-e14d0a2f40a6.png)

After the PR..
![Screenshot 2022-06-22 at 10 23 48](https://user-images.githubusercontent.com/24256554/174981039-fc172b48-9bd7-43ff-98d4-3b7d91c7b339.png)

**Comment by attack68** [comment]
@ShawnZhong you proposed the original solution to this problem. Any ideas on the new problem here?
