### ISSUE TITLE
ENH: `pd.DataFrame.groupby().sample()` to support groups with `n` smaller than group size when `replaec=False`

### ISSUE THREAD

**Issue by zhangyilun** [pandas-dev/pandas#46989]
#### Is your feature request related to a problem?

Encountered issue when using `pd.DataFrame.groupby().sample()` with `replace=False`. The issue is when specified `n` is larger than some of the groups, the sampling will fail since I specified `replace=False`. Is it possible to have extra argument to allow such sampling by keeping all rows in that group if `n` is larger than group size?

#### Describe the solution you'd like

Request to have `pd.DataFrame.groupby().sample()` to allow `replace=False` when `n` larger than some of the groups and keep the entire group.

A parameter called something like `error_if_n_greater_than_group_size=True/False` to be used together with `replace=False` to handle groups smaller than specified sample size `n`.

#### API breaking implications

With default value of `True` and it will have no change to the API and return error needed. But when specified `False`, will return filtered df without error.

#### Describe alternatives you've considered

Alternatively without this option, user has to split the data into 2 parts, one df with entries that can form groups larger than the specified `n`, another with entries that can form groups smaller than the specified `n`. Run `groupby().sample()` on the first df, and combine result with second df.

**Comment by mroeschke** [comment]
Thanks for the request but it appears there hasn't been much interest in this issue from the core team and community over the years so closing.
