### ISSUE TITLE
BUG: pandas date_range does not work with start/end having timezone information

### ISSUE THREAD

**Issue by chris-hermans** [pandas-dev/pandas#46996]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import datetime as dt
import pytz

print("Unexpected range:")
print(pd.date_range(start=dt.datetime(2020, 1, 1, 0, 0, 0, tzinfo=pytz.timezone("Europe/Kiev")),
                    end=dt.datetime(2020, 1, 1, 20, 0, 0, tzinfo=pytz.timezone("Europe/Kiev")),
                    freq="1H", closed="left"))
```

### Issue Description

Providing the start and end arguments in the pandas date_range function as time-aware timestamps will not result in the expected behavior. Some additional minutes (not only hours) are added/subtracted from the provided start/end points, depending on the provided time-zone.

Providing time-naive start and end arguments with the timezone information provided separately in the tz argument works as expected.

### Expected Behavior

```
print("Expected range:")
print(pd.date_range(start=dt.datetime(2020, 1, 1, 0, 0, 0),
                    end=dt.datetime(2020, 1, 1, 20, 0, 0),
                    tz=pytz.timezone("Europe/Kiev"),
                    freq="1H", closed="left"))
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_Belgium.1252
pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.8.3
fastparquet      : None
gcsfs            : None
matplotlib       : 3.5.1
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : 1.3.20
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.51.2

</details>

**Comment by mroeschke** [comment]
Thanks for the report. Please refer to the pytz documentation on how to localize `datetime.datetime` objects (in your start & end) https://pythonhosted.org/pytz/#example-usage

```
In [12]: tz = pytz.timezone("Europe/Kiev")

In [13]: start = tz.localize(dt.datetime(2020, 1, 1, 0, 0, 0,))

In [14]: end = tz.localize(dt.datetime(2020, 1, 1, 20, 0, 0,))

In [15]: pd.date_range(start=start, end=end, freq="1H", closed="left")
Out[15]:
DatetimeIndex(['2020-01-01 00:00:00+02:00', '2020-01-01 01:00:00+02:00',
               '2020-01-01 02:00:00+02:00', '2020-01-01 03:00:00+02:00',
               '2020-01-01 04:00:00+02:00', '2020-01-01 05:00:00+02:00',
               '2020-01-01 06:00:00+02:00', '2020-01-01 07:00:00+02:00',
               '2020-01-01 08:00:00+02:00', '2020-01-01 09:00:00+02:00',
               '2020-01-01 10:00:00+02:00', '2020-01-01 11:00:00+02:00',
               '2020-01-01 12:00:00+02:00', '2020-01-01 13:00:00+02:00',
               '2020-01-01 14:00:00+02:00', '2020-01-01 15:00:00+02:00',
               '2020-01-01 16:00:00+02:00', '2020-01-01 17:00:00+02:00',
               '2020-01-01 18:00:00+02:00', '2020-01-01 19:00:00+02:00'],
              dtype='datetime64[ns, Europe/Kiev]', freq='H')
```
