### ISSUE TITLE
DOC: 

### ISSUE THREAD

**Issue by enzedonline** [pandas-dev/pandas#47000]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/getting_started/intro_tutorials/04_plotting.html

### Documentation problem

The final example calls an undeclared object `plt`:

`fig, axs = plt.subplots(figsize=(12, 4))`

### Suggested fix for documentation

Add the declaration for plt, the code doesn't run as is:

`import matplotlib.pyplot as plt`

**Comment by MarcoGorelli** [comment]
isn't it declared right at the top of the page?
