### ISSUE TITLE
BUG: The column label '**' is not unique. but it is unique

### ISSUE THREAD

**Issue by ShanshanBiNovelis** [pandas-dev/pandas#47008]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
df_res_comp = pd.DataFrame(ls_res, columns = [['Component', 'Plant_component', 'Workcenter_component']])
df_res_mat = pd.DataFrame(ls_res, columns = [['Material_route', 'Plant', 'Workcenter_material']])

#%%
df_pro_bom_temp1 = df_pro_bom_c1.merge(df_res_mat, left_on = ['Material', 'Plant - Key'], right_on = ['Material_route', 'Plant'], how = 'left')
```

### Issue Description

![image](https://user-images.githubusercontent.com/99674221/168132361-9725cab9-57c0-40b1-8221-c8123dbcb093.png)
I check the Material route is unique. But somehow, it is still showing me it is not unique.

### Expected Behavior

Fix the bug, or find a way around.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.9.7.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en
LOCALE           : English_United States.1252

pandas           : 1.4.2
numpy            : 1.20.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : 0.29.24
pytest           : 6.2.4
hypothesis       : None
sphinx           : 4.2.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.1
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.29.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
brotli           : 
fastparquet      : None
fsspec           : 2021.10.1
gcsfs            : None
markupsafe       : 1.1.1
matplotlib       : 3.4.3
numba            : 0.54.1
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 7.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
snappy           : None
sqlalchemy       : 1.4.22
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None

</details>

**Comment by MarcoGorelli** [comment]
Hi @ShanshanBiNovelis - could you make your example reproducible please?
