### ISSUE TITLE
DOC: DataFrame.rename Method

### ISSUE THREAD

**Issue by MischaDy** [pandas-dev/pandas#47030]
### Pandas version checks

- [x] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.rename.html#pandas.DataFrame.rename

### Documentation problem

The docs for the `inplace` parameter state: "Whether to return a new `DataFrame`. (...)". However, it is clear that the boolean has the opposite meaning: If  `inplace=True`, *no* new `DataFrame` will be returned and vice versa.

### Suggested fix for documentation

Something along the lines of: "Whether not to return a new `DataFrame`. (...)"
Or, perhaps more intuitively: "Whether to modify the `DataFrame` passed as input. (...)"
Possibly with an enhancing addition: "Whether to modify the `DataFrame` passed as input, rather than creating a new one."

These suggestions improve the docs, because the boolean value of `inplace` then corresponds to rather than opposes the actual actions taken by the result. Skimming the docs, one might think that the parameter does the opposite of what the docs say, despite its name. Or, alternatively, one might stumble when reading it, and get the intended meaning afterwards. In any case, it is an unneeded distraction.

**Comment by simonjayhawkins** [comment]
Thanks @MischaDy for the report.

> Possibly with an enhancing addition: "Whether to modify the `DataFrame` passed as input, rather than creating a new one."

This is the most explicit but the DataFrame is not technically passed by the user, only internally as self?

so maybe just "Whether to modify the `DataFrame` rather than creating a new one."

we use the inplace parameter in several methods, so any changes should be consistent across all methods.

contributions and PRs welcome.

**Comment by MischaDy** [comment]
Thanks @simonjayhawkins for the super-quick reply! 

> This is the most explicit but the DataFrame is not technically passed by the user, only internally as self?

Yes, that's correct, my bad.

> so maybe just "Whether to modify the `DataFrame` rather than creating a new one."

Yes, I think that's the best option!

> we use the inplace parameter in several methods, so any changes should be consistent across all methods.

I totally agree, this was just the first method I noticed this for.

> contributions and PRs welcome.

Oh, I can directly modify the docs and then do a pull request? If so, I'll be happy to do so :)

**Comment by simonjayhawkins** [comment]
> Oh, I can directly modify the docs and then do a pull request? If so, I'll be happy to do so :)

see https://pandas.pydata.org/pandas-docs/dev/development/contributing_documentation.html#contributing-to-the-documentation

**Comment by Sumanth077** [comment]
Hi @MischaDy @simonjayhawkins I would like to Contribute, is this Issue still open?

**Comment by rohit18115** [comment]
take
