### ISSUE TITLE
DOC: `ddof` in `cov` when `nan`s present

### ISSUE THREAD

**Issue by attack68** [pandas-dev/pandas#47042]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.cov.html

### Documentation problem

The `ddof` argument is applicable only when `nan`s are not present in the dataframe.
It can be quite common to calculate a covariance matrix from financial data where the last row might be `nan` since the difference is taken between values. One might expect that since the result is given the `ddof` is adhered to. But it is not. I think this should be explicitly stated in the argument documentation, rather than hidden in the notes.

### Suggested fix for documentation

.

**Comment by whooolemilk** [comment]
@attack68 @topper-123 
May I add the following text?

**The ddof argument is applicable only when nans are not present in the dataframe.**

**Comment by topper-123** [comment]
I think that's a good line to add.
