### ISSUE TITLE
DOC: Improve documentation for mode parameter in to_csv() method

### ISSUE THREAD

**Issue by kevinxperese** [pandas-dev/pandas#47058]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.to_csv.html

### Documentation problem

The description for the mode parameter is too sparse. Additional information on other acceptable values would be helpful, especially mode='a'.

### Suggested fix for documentation

Proposed change: 
**mode : str,** ***default 'w'***
String character(s) to indicate the mode in which the file is opened for writing. Valid values include: 'w' for "write" access, 'w+' or 'r+' for read and write access, 'x' or 'x+' for exclusive creation access, and 'a' or 'a+' for append access. All strings have an implied 't' for text access; binary access is not permitted.

**Comment by MaruthiKo** [comment]
Hi, I am new to Open source and I am looking forward to working on this issue, this would be my first open-source contribution.
Can you please tell me how I can help in this issue

**Comment by MaruthiKo** [comment]
> I think linking to Python's `open` docstring which describes the standard `mode` options that pandas dispatches to would be best: https://docs.python.org/3/library/functions.html#open

I guess you are right will do that.

**Comment by kevinxperese** [comment]
> I think linking to Python's `open` docstring which describes the standard `mode` options that pandas dispatches to would be best: https://docs.python.org/3/library/functions.html#open

That crossed my mind, but I haven't seen such links in documentation elsewhere, so I wasn't sure if that would be a non-standard practice. 

Also, adding just a link would not solve the problem of someone coming to the page looking for the appropriate parameter to use to append content to a file. (Searching the page for the word "append" will still turn up nothing; this is what I did when I was looking for the parameter to use.)
