### ISSUE TITLE
BUG: formulae from xls files that result in strings get replaced with 0

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#47060]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
# The following code creates the file in a reproducible way,
# ... but it is easy to create it by hand:
import xlwt
wb = xlwt.Workbook()
ws = wb.add_sheet('First')

for i in range(5):
    ws.write(i, 0, i)
    ws.write(i, 1, xlwt.Formula(f'IF(A{i+1}<2;A{i+1};"more")'))

wb.save('/tmp/test.xls')

# Now open the file (e.g. with LibreOffice) and re-save it,
# so that cells get evaluated

import pandas as pd
pd.read_excel('/tmp/test.xls')
```

### Issue Description

```
  | 0 | 0.1
-- | -- | --
1 | 0
2 | 0
3 | 0
4 | 0
```

### Expected Behavior

```
  | 0 | 0
-- | -- | --
1 | 1
2 | 2
3 | "more"
4 | "more"
```

Notice that this is not a problem with ``xlwt``; the same behavior arises if the file is created with LibreOffice.

Instead, the problem does not arise with ``xlsx`` files.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.9.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.16.0-0.bpo.4-amd64
Version          : #1 SMP PREEMPT Debian 5.16.12-1~bpo11+1 (2022-03-08)
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : it_IT.UTF-8
LOCALE           : it_IT.UTF-8

pandas           : 1.4.2
numpy            : 1.19.5
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 20.3.4
setuptools       : 52.0.0
Cython           : 0.29.28
pytest           : 6.0.2
hypothesis       : 5.43.3
sphinx           : 3.4.3
blosc            : 1.9.2
feather          : None
xlsxwriter       : 1.1.2
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.8.6
jinja2           : 2.11.3
IPython          : 7.20.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.4
brotli           : 1.0.9
fastparquet      : None
fsspec           : 0.8.4
gcsfs            : None
markupsafe       : 1.1.1
matplotlib       : 3.3.4
numba            : None
numexpr          : 2.7.2
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pyreadstat       : 1.1.0
pyxlsb           : None
s3fs             : None
scipy            : 1.6.0
snappy           : None
sqlalchemy       : 1.3.22
tables           : 3.6.1
tabulate         : None
xarray           : 0.16.1
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report! If I open the file with LibreOffice, copy the formulae, delete them, and add them back, I then get 1, 2, and "more" appearing when reading with pandas as expected. Also doing this causes the binary file to change. Looking at the values that pandas gets from calling `sheet.row_values(i)` using xlrd for each row `i`, I get:

```
[0.0, 0.0, '']
[1.0, 1.0, 'a']
[2.0, 0.0, '']
[3.0, 0.0, '']
[4.0, 0.0, '']
```

In short, I do not believe this is an issue with pandas, but rather either xlrd or LibreOffice.

**Comment by toobaz** [comment]
> In short, I do not believe this is an issue with pandas, but rather either xlrd or LibreOffice.

Ouch, you're right... I noticed that if I open the file with gnumeric, I get the zeros - while they become "more" if I edit the formulae in place. But given that pandas doesn't have the formula evaluation functionality, there's not much to be done here I guess.
