### ISSUE TITLE
BUG: accessing df column with df.columns result type mismatch

### ISSUE THREAD

**Issue by Malachov** [pandas-dev/pandas#47063]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame([[1, 2, 3]], columns=["a", "b", "c"])

column = df.columns[0]

a = df[column]

print(a)
```

### Issue Description

First sorry if this should be in Questions instead of bug. It may be my misunderstanding and it may be by design.

Pylance in VS Code attended Reproducible example complains about type as in this printscreen

![image](https://user-images.githubusercontent.com/39381691/169394180-428a1357-7bea-4acb-b057-84df4745994e.png)

This may be also problem of pylance of course.

### Expected Behavior

I'd expect that used code is formally OK (it's not usual way of iterating as iloc for example, but sometimes this may be the way).

It shows that result of `df.columns[0]` is hashable. Yes it is, but maybe that it is particular type that implements same interface as hashable?

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.10.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22000
machine          : AMD64
processor        : AMD64 Family 23 Model 104 Stepping 1, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : Czech_Czechia.1252

pandas           : 1.4.2
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 22.0.4
setuptools       : 58.1.0
Cython           : None
pytest           : 7.1.1
hypothesis       : None
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.1
IPython          : 8.2.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : 3.5.1
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 7.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
snappy           : None
sqlalchemy       : 1.4.36
tables           : 3.7.0
tabulate         : 0.8.9
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : None

**Comment by simonjayhawkins** [comment]
Thanks @Malachov for the report. I assume this is not an issue with pandas but with the stubs shipped with VSCode.

cc @Dr-Irv

**Comment by Malachov** [comment]
I understand, I thought that stubs are maintained directly by pandas - My bad sorry. I know that there was stubs implemented separately, but I thought it was finally implemented directly in repo. Maybe I'd heard it about numpy and then forgot it's not pandas (and maybe also numpy uses still external stubs :) ). Closing the issue and reporting on place where the stubs was made...

**Comment by simonjayhawkins** [comment]
> I understand, I thought that stubs are maintained directly by pandas

The next release of the stubs will be. reopening and awaiting feedback from @Dr-Irv where this should now be reported.

**Comment by Malachov** [comment]
Actually I found the reason... VS Code uses Pylance which probably uses it's own stubs for some libraries (it's not 'data-science-types' nor new 'pandas-stubs')...

I've already even find issue related to this on these stubs... [https://github.com/microsoft/python-type-stubs/issues/199](https://github.com/microsoft/python-type-stubs/issues/199)

I think that this **should be closed** as no changes on this repo can solve shown error as it's not on pandas side

There are many ways how to type do hinting in the future (but old versions compatibility will make it harder). Maybe the official stub would be the way (or adopting existing one), but this is out of scope of this issue...

**Comment by Malachov** [comment]
Just a small spam here - As I turned on static type checker and refactored old code with pandas - I've found some edge cases and potential errors, so I love this feature...

**Comment by Dr-Irv** [comment]
I was on vacation last week - sorry for the late reply.  Issues like these should be reported at https://github.com/pandas-dev/pandas-stubs .  I'll look at the one reported here and fix it there, but Microsoft has to do some work to start pulling these stubs over to the VS Code distribution.

**Comment by Dr-Irv** [comment]
This is now fixed in the `pandas-stubs` repo via https://github.com/pandas-dev/pandas-stubs/pull/15
