### ISSUE TITLE
BUG: Reset index regression

### ISSUE THREAD

**Issue by znicholls** [pandas-dev/pandas#47071]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
from pandas import DataFrame, Index
import xarray

df = DataFrame(
    [[1, 2], [3, 4]],
    columns=xarray.cftime_range("0001", periods=2),
    index=Index(["hi", "bye"], name="string"),
)
# currently fails with TypeError
res = df.reset_index()
```

### Issue Description

The above leads to a type error.

### Expected Behavior

Reset index. I would guess that the columns should be downcast from `CFTimeIndex` to `Index` with object type but maybe there's a better option.

### Installed Versions

<details>

miniconda3/envs/pandas-dev/lib/python3.8/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit           : 1def8d9f3f0690ae93cbf611246f80f79a0faeaa
python           : 3.8.13.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
Version          : Darwin Kernel Version 19.6.0: Mon Apr 18 21:50:40 PDT 2022; root:xnu-6153.141.62~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_AU.UTF-8
LOCALE           : en_AU.UTF-8

pandas           : 1.5.0.dev0+798.g1def8d9f3f
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 22.0.4
setuptools       : 62.3.2
Cython           : 0.29.30
pytest           : 7.1.2
hypothesis       : 6.46.7
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.8.0
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.3.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.4
brotli           : 
fastparquet      : 0.8.1
fsspec           : 2021.11.0
gcsfs            : 2021.11.0
matplotlib       : 3.5.2
numba            : 0.53.1
numexpr          : 2.8.0
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 8.0.0
pyreadstat       : 1.1.6
pyxlsb           : None
s3fs             : 2021.11.0
scipy            : 1.8.0
snappy           : 
sqlalchemy       : 1.4.36
tables           : 3.7.0
tabulate         : 0.8.9
xarray           : 2022.3.0
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None

</details>

**Comment by znicholls** [comment]
Looks like this was caused as a result of #43933

682187225059cbf8e93df04042ee04bf498d6cc4 is the first bad commit
commit 682187225059cbf8e93df04042ee04bf498d6cc4
Author: jbrockmendel <jbrockmendel@gmail.com>
Date:   Fri Oct 8 17:17:40 2021 -0700

    BUG: NumericIndex.insert (#43933)

 pandas/core/indexes/base.py    |  7 ++++---
 pandas/tests/indexes/common.py | 19 +++++++++++++++++++
 2 files changed, 23 insertions(+), 3 deletions(-)
bisect run success

**Comment by znicholls** [comment]
The xarray version is 2022.3.0

**Comment by simonjayhawkins** [comment]
cc @jbrockmendel

**Comment by jbrockmendel** [comment]
Looks like `CFTImeIndex.__new__` is getting called in a place it shouldn't be.  IIUC the use of self._constructor in Index.insert will be unnecessary in 2.0 at which point this might start working again on its own

**Comment by simonjayhawkins** [comment]
moving to 1.4.4

**Comment by jorisvandenbossche** [comment]
This should be an easy fix to keep using `Index(..)` instead of `_constructor` for non-NumericIndex cases. Opened a PR at https://github.com/pandas-dev/pandas/pull/48058
