### ISSUE TITLE
BUG: pd.Series.mode failed to give expected result when it is embedded inside groupby.transform

### ISSUE THREAD

**Issue by Fanghaozhi-Liang** [pandas-dev/pandas#47094]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                          'foo', 'bar'],
                   'B' : ['one', 'one', 'two', 'three',
                          'two', 'two'],
                   'C' : [1, 5, 5, 2, 5, 5],
                   'D' : [2.0, 5., 8., 1., 2., 9.]})

df.groupby(['A'])['C'].transform(pd.Series.mode)
```

### Issue Description

The result includes unexpected NA value.

### Expected Behavior

import statistics
import pandas as pd

df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                          'foo', 'bar'],
                   'B' : ['one', 'one', 'two', 'three',
                          'two', 'two'],
                   'C' : [1, 5, 5, 2, 5, 5],
                   'D' : [2.0, 5., 8., 1., 2., 9.]})

df.groupby(['A'])['C'].transform(statistics.mode)

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.8.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22000
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Simplified)_China.1252

pandas           : 1.4.2
numpy            : 1.21.5
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 22.1.1
setuptools       : 62.1.0
Cython           : 0.29.23
pytest           : 6.2.3
hypothesis       : None
...
xarray           : 0.21.1
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None

</details>

**Comment by simonjayhawkins** [comment]
Thanks @Fanghaozhi-Liang for the report.

Does statistics.mode give the expected result when then is more that one mode?

`pd.Series.mode` returns a Series of the modes of the Series in sorted order and zero-indexed by that sort order

groupby.transform expects a call function producing a like-indexed Series on each group and return a Series having the same indexes as the original object filled with the transformed values.

`pd.Series.mode` does not fulfil the requirements of a `grouby.transform` callable.

```python
for _, ser in df.groupby(["A"])["C"]:
    print(pd.Series.mode(ser))
```
```
0    5
Name: C, dtype: int64
0    5
Name: C, dtype: int64
```

**Comment by phofl** [comment]
Closing for now. Feel free to ping to reopen, if you think this is a bug on the pandas side
