### ISSUE TITLE
Issue template versions command no longer works

### ISSUE THREAD

**Issue by vyasr** [pandas-dev/pandas#47106]
setuptools version 60.0.0 made [the local copy of distutils the default](https://setuptools.pypa.io/en/latest/history.html#id179). Due to this change, certain import orders of distutils and setuptools seem to cause problems, cf. https://github.com/pypa/pip/issues/10809 and https://github.com/pypa/setuptools/issues/3089. Current `pandas.show_versions` suffers from the same problem, and as a result cannot report versions when opening issues.

Users can get around this by setting the environment variable `SETUPTOOLS_USE_DISTUTILS=stdlib`, but they may not know to do so. One option would just be to just change the issue template to ask users to execute `SETUPTOOLS_USE_DISTUTILS=stdlib python -c "import pandas; pandas.show_versions()"`, but I don't know if this error is persistent across all Python versions, or if it will be an issue until Python 3.12 (when distutils is officially removed).

**Comment by mroeschke** [comment]
Thanks for the report. I think this might be the same issue as https://github.com/pandas-dev/pandas/issues/44980 and is being worked on at https://github.com/pandas-dev/pandas/pull/47096
