### ISSUE TITLE
BUG: RangeIndex problem

### ISSUE THREAD

**Issue by hosseinrasekhi** [pandas-dev/pandas#47128]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
A = pd.DataFrame({'a':[False,True]}) # index=[0,1] vs index=range(2)
A['i'] = A.index
A.loc[A['a'],'i'] = -2
print(A.loc[A['a'],:])
```

### Issue Description

when assign index(RangeIndex) to new column then change this column by loc, index will change unexpectedly. this issue exists in 1.4.x but not in 1.1.1

<output>
<html>
<body>

  | a | i
-- | -- | --
-2|True | -2

</body>
</html>
</output>

### Expected Behavior

<html>
<body>

  | a | i
-- | -- | --
1|True | -2

</body>
</html>

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.9.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-110-generic
Version          : #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.0
numpy            : 1.22.2
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 21.2.3
setuptools       : 49.2.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.8.0
html5lib         : None
pymysql          : None
psycopg2         : 2.9.1
jinja2           : 3.1.2
IPython          : 7.33.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.4.3
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : 1.4.23
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
None

</details>

**Comment by nishithshowri006** [comment]
I think the behavior is different using integers and booleans, I think it is the reason you might be not getting the expected results.
![image](https://user-images.githubusercontent.com/58651995/170541297-3dc56a9d-8fe2-48b3-8163-6637321056de.png)

**Comment by phofl** [comment]
Thanks for the report.

This worked on 1.3.5 too

**Comment by simonjayhawkins** [comment]
> This worked on 1.3.5 too

failed? worked in 1.1.5 but not 1.2.5. will bisect to shed more light.

**Comment by simonjayhawkins** [comment]
> This is what I am getting on 1.3.5

ok so must be a dependency issue. I've started the bisect but it'll probably fail then.

**Comment by phofl** [comment]
Yeah probably, numpy would be my first guess.

**Comment by simonjayhawkins** [comment]
> I've started the bisect but it'll probably fail then.

didn't fail. i'm getting

first bad commit: [b58ee5779583b31de513b3d5c12f5c69c035e920] PERF: Index._shallow_copy shares _cache with copies of self (#36840)

which seems plausible.
