### ISSUE TITLE
DOC: how to_datetime %S differs from strptime

### ISSUE THREAD

**Issue by mdavis-xyz** [pandas-dev/pandas#47134]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.to_datetime.html?highlight=to_datetime#pandas.to_datetime

### Documentation problem

The documentation says that the formatting strings used by `pandas.to_datetime` are the same as `datetime.strptime`, other than the number of digits `%f` handles.

This is not quite true, there is another difference. `pandas.to_datetime` with `%S` (without `%f`) will capture microseconds. `strptime` will throw an error. (Which makes pandas.to_datetime more useful than strptime)

```
import pandas as pd
import datetime as dt
fmt = "%Y/%m/%d %H:%M:%S"
s= "2021/01/01 12:01:01.123"
assert pd.to_datetime(s, format=fmt).microsecond > 0
dt.datetime.strptime(s, fmt)
```

The second-last line passes,
the last line throws `ValueError: unconverted data remains: .123`.

### Suggested fix for documentation

Change:

> Note that "%f" will parse all the way up to nanoseconds.

to:

> Note that "%S" without "%f" will capture fractional seconds up to nanoseconds,
> Note that "%f" will parse all the way up to nanoseconds.
> "%S" without "%f" will capture all the way up to nanoseconds if present as decimal places, but will also handle the case where the number of seconds is an integer.

**Comment by MaruthiKo** [comment]
Hi, I would to like work on this issue.

**Comment by MarcoGorelli** [comment]
Thanks for the suggestion, sounds good - as noted in https://github.com/pandas-dev/pandas/pull/47164/files#r884317700 , it would be good to include an example

**Comment by wooilkim** [comment]
Let me add an example on this.

**Comment by WooilKim** [comment]
@MarcoGorelli I think @mdavis-xyz required to revise the html document, not the pandas/core/tools/datetimes.py.
Is it possible to modify that html document?
By the way, if the documentation of datetimes.py needs modification, I'll do it including the example.
Thank you.

**Comment by ryuusama09** [comment]
Is this issue still open ?. If yes then I would like to work on it

**Comment by heroesIV** [comment]
I am interested in working on this issue.

**Comment by mdavis-xyz** [comment]
Yes I think this issue is still open. That PR was closed as stale. I think the reviewers wanted examples included.
