### ISSUE TITLE
BUG: Series.corr() returns nan for identical Series objects of length 1

### ISSUE THREAD

**Issue by jackgoldsmith4** [pandas-dev/pandas#47132]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
s = pd.Series([2])
s.corr(s)
```

### Issue Description

This should return `1.0` because the Series object is being compared to itself. However, this returns `nan`.

### Expected Behavior

Returning `1.0` is expected because the Series object is being compared to itself.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 8e522ebd4363bdc6709197a1175638ba98de9caa
python           : 3.8.13.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.47-linuxkit
Version          : #1 SMP Sat Jul 3 21:51:47 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : C.UTF-8
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0.dev0+823.g8e522ebd43
numpy            : 1.22.4
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 62.3.2
pip              : 22.0.4
Cython           : 0.29.30
pytest           : 7.1.2
hypothesis       : 6.46.9
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.8.0
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.3.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.4
brotli           : 
fastparquet      : 0.8.1
fsspec           : 2021.11.0
gcsfs            : 2021.11.0
matplotlib       : 3.5.2
numba            : 0.53.1
numexpr          : 2.8.0
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 8.0.0
pyreadstat       : 1.1.6
pyxlsb           : None
s3fs             : 2021.11.0
scipy            : 1.8.1
snappy           : 
sqlalchemy       : 1.4.36
tables           : 3.7.0
tabulate         : 0.8.9
xarray           : 2022.3.0
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None

</details>

**Comment by simonjayhawkins** [comment]
Thanks @jackgoldsmith4 for the report.

The nan result occurs with a Series of any length series of non varying values, not just with length 1.

from https://github.com/pandas-dev/pandas/issues/20954

> In general, the correlation between two Series is not defined when one Series does not have varying values, like e.g. s_a or s_c, as the denominator of the correlation function is evaluated to zero, resulting in a by-zero-division.

and https://github.com/pandas-dev/pandas/issues/20954#issuecomment-851553140 gives a more detailed explanation.

**Comment by jackgoldsmith4** [comment]
@simonjayhawkins I understand, thanks for clarifying that for me! Unless you think it would be useful to add to the docs for this function, I can go ahead and close this

**Comment by mroeschke** [comment]
I think it would be worth adding an example to the docs of a constant valued series returning nan

**Comment by fbourgey** [comment]
take

**Comment by fbourgey** [comment]
In the function `scipy.stats.pearsonr` [function](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearsonr.html), a `ConstantInputWarning` is raised if an input is a constant array and ` np.nan` is returned too.
