### ISSUE TITLE
DOC: unused Series axis parameter arbitrarily defaults to 0 or None

### ISSUE THREAD

**Issue by jackgoldsmith4** [pandas-dev/pandas#47146]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.Series.add.html - example of defaulting to 0
https://pandas.pydata.org/docs/reference/api/pandas.Series.argmin.html - example of defaulting to None

### Documentation problem

As a new user and contributor the Series axis parameter has been confusing to me. I now know it is not used for Series and only exists for compatibility with DataFrame. However, it is also confusing that it seems to arbitrarily default to either 0 or `None`. Does this difference matter for different methods?

### Suggested fix for documentation

Unless there is a reason why different methods have default `axis` as 0 or `None`, I propose changing all Series method `axis` parameters to default to either 0 or `None`. This will make the parameter and the docs more clear.

**Comment by phofl** [comment]
Does not matter, if it is not used, but might be helpful for the DataFrame method or something else.

One thing I realised: argmin and argmax don't have any implementation where axis is actually used, maybe we could deprecate there

**Comment by jackgoldsmith4** [comment]
@phofl in terms of the unused parameter for `Series` methods, would you prefer them to all default to 0 or `None`?

**Comment by phofl** [comment]
I would prefer keeping the defaults in line with the DataFrame methods

**Comment by jackgoldsmith4** [comment]
Closing because the Series axis parameter won't change. I now understand it is 0 or None solely based on the corresponding DataFrame method. I may open another issue or question about argmin and argmax more generally
