### ISSUE TITLE
API:  How much of the EA API can we commit to?

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#47148]
I am working with a commercial company that has a python API that they would like to extend to better support pandas.  I suggested using the `ExtensionArray` interface.  However, at https://pandas.pydata.org/docs/development/extending.html?highlight=extensionarray#extension-types we say this:

> The [pandas.api.extensions.ExtensionDtype](https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.ExtensionDtype.html#pandas.api.extensions.ExtensionDtype) and [pandas.api.extensions.ExtensionArray](https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.ExtensionArray.html#pandas.api.extensions.ExtensionArray) APIs are new and experimental. They may change between versions without warning.

This is making them wary of building something that would no longer work in the future.  I told them that we have lots of things in pandas that depend on the interface, so the likelihood of it going away is very small.

I see there is discussion in #32586 about revisiting the EA interface.

Can we say that parts of the EA API are "frozen" at this point?  Or could the entire API change in the future?  Can we now say that the API is no longer experimental?

Comments from @jbrockmendel and @jorisvandenbossche ?

**Comment by jbrockmendel** [comment]
For the most part, I'd be comfortable removing the "without warning" part and committing the same kind of deprecation policy we use elsewhere (will need to look at the API to determine whether the "for the most part" caveat can be dropped).

**Comment by jreback** [comment]
i agree this has been stable for a while 

that said we do want to make some changes to support arrow dtypes (in other PRs) so maybe we declare it stable in 2.0

**Comment by jorisvandenbossche** [comment]
Indeed, agreed that we can remove that "experimental" label, and apply the same deprecation policy as we use in general.

In case that might give some reassurance, https://github.com/geopandas/geopandas/ is implementing an ExtensionArray and is a widely used package (and I don't think we really had a significant issue with the stability of the EA interface the last years).

**Comment by Dr-Irv** [comment]
I'm willing to create a PR that changes this text:

> The [pandas.api.extensions.ExtensionDtype](https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.ExtensionDtype.html#pandas.api.extensions.ExtensionDtype) and [pandas.api.extensions.ExtensionArray](https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.ExtensionArray.html#pandas.api.extensions.ExtensionArray) APIs are new and experimental. They may change between versions without warning.

to

The [pandas.api.extensions.ExtensionDtype](https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.ExtensionDtype.html#pandas.api.extensions.ExtensionDtype) and [pandas.api.extensions.ExtensionArray](https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.ExtensionArray.html#pandas.api.extensions.ExtensionArray) APIs were experimental prior to pandas 1.4.  Starting with version 1.4, future changes will follow the [pandas deprecation policy](https://pandas.pydata.org/docs/development/policies.html#version-policy).

Can we agree on that text before I create the PR?

**Comment by jreback** [comment]
+1
