### ISSUE TITLE
BUG: Docker build without cache leads to error due to identity issues

### ISSUE THREAD

**Issue by iajoiner** [pandas-dev/pandas#47163]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
Step 7/11 : RUN mkdir "$pandas_home"     && git clone "https://github.com/$gh_username/pandas.git" "$pandas_home"     && cd "$pandas_home"     && git remote add upstream "https://github.com/pandas-dev/pandas.git"     && git pull upstream main
 ---> Running in b3a6d6a74285
Cloning into '/home/pandas'...
Updating files: 100% (2427/2427), done.
From https://github.com/pandas-dev/pandas
 * branch                  main       -> FETCH_HEAD
 * [new branch]            main       -> upstream/main

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@b3a6d6a74285.(none)')
```

### Issue Description

Due to Cython version bumping I rebuilt my development docker image using 
`docker build --no-cache --build-arg gh_username=iajoiner --tag pandas-iajoiner-env . `
This does not work because of the issue above

### Expected Behavior

The build should have worked.

### Installed Versions

1.5.0 test

**Comment by iajoiner** [comment]
Currently the workaround is to provide my username & email address in Step 7 prior to git clone.

**Comment by iajoiner** [comment]
I actually wonder whether we should add name & email as Docker build args if more people experience this issue.

**Comment by rendner** [comment]
Hi, I build a new docker image today and didn't run into the problem. 

My command looks like yours: `docker build --no-cache --build-arg gh_username=rendner  --tag pandas-rendner-env .`

Here is a shortened output of it:
```
Step 7/11 : RUN mkdir "$pandas_home"     && git clone "https://github.com/$gh_username/pandas.git" "$pandas_home"     && cd "$pandas_home"     && git remote add upstream "https://github.com/pandas-dev/pandas.git"     && git pull upstream main
 ---> Running in 050c43864d34
Cloning into '/home/pandas'...
From https://github.com/pandas-dev/pandas
 * branch                  main       -> FETCH_HEAD
 * [new branch]            main       -> upstream/main
Updating 47494a48ed..4fe2f312ce
Fast-forward
 .github/actions/build_pandas/action.yml            |   4 +-
...<REMOVED_TO_SHORTEN_OUTPUT>
Removing intermediate container 050c43864d34
 ---> fc8f97f1dc3b
Step 8/11 : RUN conda install -y mamba

```

**Comment by mroeschke** [comment]
Appears that this may have been fixed in the meantime, so closing. Can reopen if it resurfaces again
