### ISSUE TITLE
ENH: Add support for reading Stata 7 (non-SE) format dta files

### ISSUE THREAD

**Issue by cmjcharlton** [pandas-dev/pandas#47176]
#### Is your feature request related to a problem?

If I attempt to read in a dta file saved in Stata 7 format using the [`read_stata()`](https://pandas.pydata.org/docs/reference/api/pandas.read_stata.html) function I get the following error message:

> ValueError: Version of given Stata file is 110. pandas supports importing versions 105, 108, 111 (Stata 7SE), 113 (Stata 8/9), 114 (Stata 10/11), 115 (Stata 12), 117 (Stata 13), 118 (Stata 14/15/16),and 119 (Stata 15/16, over 32,767 variables).

This is unfortunate as this is the version of the format used by default by R's [`write.dta()`](https://stat.ethz.ch/R-manual/R-devel/library/foreign/html/write.dta.html) function in the `foreign` package.

#### Describe the solution you'd like

It would be nice if this version of the data format was supported, at least for reading, in the same manner as the other variants.

#### API breaking implications

None that I am aware of.

#### Describe alternatives you've considered

`write.dta` also supports saving to the versions 6, 8 and 10 of the dta format which are supported, so I could manually specify a different version instead. Alternatively I could save my data using the `readstata13` or `haven` packages which both support more recent versions of the Stata dta format.

Another option would be to use a different data format entirely that is also supported by both R and Pandas.

#### Additional context

It appears that to implement support for this additional variant the following two changes are required:

1. Edit the line:
https://github.com/pandas-dev/pandas/blob/8e94afb983cb51551f628567f819a07246e78bdf/pandas/io/stata.py#L1414

To:
```python
if self.format_version > 110:
```

2. Change the line:
https://github.com/pandas-dev/pandas/blob/8e94afb983cb51551f628567f819a07246e78bdf/pandas/io/stata.py#L1397

To include 110 in the list of supported variants, i.e.

```python
if self.format_version not in [104, 105, 108, 110, 111, 113, 114, 115]:
```

After making these changes locally my version 7 files appear to load correctly.

**Comment by bashtage** [comment]
Is the 110 format documented? I think we haven't supported 110 because there are no docs.

**Comment by bashtage** [comment]
Anyone want to share the relevant pages, which I think should fall under fair use?

**Comment by cmjcharlton** [comment]
Here's an OCRed version of the text. There may be transcription errors but on the whole the text is very similar to that of other versions of the format, e.g. [Stata 8](https://www.stata.com/help.cgi?dta_113).

[stata-dta110.txt](https://github.com/pandas-dev/pandas/files/10491512/stata-dta110.txt)

**Comment by cmjcharlton** [comment]
After some discussion with Stata technical support I now have documentation for all of the missing format versions. The 103, 105, 108 and 110 documents are all based on the descriptions from the corresponding Stata manuals. The 102 and 111 documents are my best guesses based on available information. I have however tested that I am able to use these format descriptions to read and write files that Stata 18 is happy to load.

[dta_102.txt](https://github.com/pandas-dev/pandas/files/14546989/dta_102.txt)
[dta_103.txt](https://github.com/pandas-dev/pandas/files/14546991/dta_103.txt)
[dta_104.txt](https://github.com/pandas-dev/pandas/files/14546994/dta_104.txt)
[dta_105.txt](https://github.com/pandas-dev/pandas/files/14546995/dta_105.txt)
[dta_108.txt](https://github.com/pandas-dev/pandas/files/14546997/dta_108.txt)
[dta_110.txt](https://github.com/pandas-dev/pandas/files/14546998/dta_110.txt)
[dta_111.txt](https://github.com/pandas-dev/pandas/files/14546999/dta_111.txt)

[dta-format changes.txt](https://github.com/pandas-dev/pandas/files/14547046/dta-format.changes.txt)

[sample-data.csv](https://github.com/pandas-dev/pandas/files/14547073/sample-data.csv)
