### ISSUE TITLE
BUG: json_normalize fails with empty arrays/lists

### ISSUE THREAD

**Issue by mateuszboryn** [pandas-dev/pandas#47182]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
# This works fine:
data = [ {
        "id": 1, "name": "Cole Volk", "fitness": [{"height": 130, "weight": 60}],
        "someList": []
    },
    {
        "id": 2, "name": "Faye Raker", "fitness": [{"height": 130, "weight": 60}],
        "someList": [1]
    },]

pd.json_normalize(data, "fitness", ["id", "name", "someList"])

# This doesn't work
data = [ {
        "id": 1, "name": "Cole Volk", "fitness": [{"height": 130, "weight": 60}],
        "someList": []
    },
    {
        "id": 2, "name": "Faye Raker", "fitness": [{"height": 130, "weight": 60}],
        "someList": []
    },]

pd.json_normalize(data, "fitness", ["id", "name", "someList"])

# fails with ValueError: operands could not be broadcast together with shape (0,) (2,)
```

### Issue Description

when normalizing nested lists, which are empty in all the objects, json_normalize fails with "ValueError: operands could not be broadcast together with shape".

It may be related to the behavior of np.repeat(), but I report the issue to pandas, because it looks like an overlooked corner case:
```
v = [ [], [], [234] ]
lengths = [1,1,3]
np.array(v, dtype=object).repeat(lengths)
``` 

and

```
v = [ [], [], [] ]
lengths = [1,1,3]
np.array(v, dtype=object).repeat(lengths)
```

### Expected Behavior

Return correct data structure and not fail.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.10.2.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8

</details>

**Comment by simonjayhawkins** [comment]
Thanks @mateuszboryn for the report.

This is the same underlying issue as #37782

i've posted a possible fix there https://github.com/pandas-dev/pandas/issues/37782#issuecomment-1146338699 that also fixes this issue.

PRs welcome.

**Comment by topper-123** [comment]
This works as expected now.

```python
>>> data = [ {
...        "id": 1, "name": "Cole Volk", "fitness": [{"height": 130, "weight": 60}],
...        "someList": []
...    },
...    {
...        "id": 2, "name": "Faye Raker", "fitness": [{"height": 130, "weight": 60}],
...        "someList": []
...    },]
>>> pd.json_normalize(data, record_path="fitness", meta=["id", "name", "someList"])
   height  weight id        name someList
0     130      60  1   Cole Volk       []
1     130      60  2  Faye Raker       []
```

Closing as fixed.
