### ISSUE TITLE
DOC: Broken URL link to Contributing Documentation on pandas Github wiki

### ISSUE THREAD

**Issue by kueperm** [pandas-dev/pandas#47201]
### Pandas version checks

- [ ] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://github.com/pandas-dev/pandas/wiki

### Documentation problem

As a potential first time contributor to pandas, I was looking through the contributing guidelines on the pandas GitHub wiki page and found the URL link for "Contributing" under the "For Documentation Authors" section is broken and results in a “404” error page being displayed when clicked:

https://github.com/pydata/pandas/blob/master/doc/README.rst

### Suggested fix for documentation

I believe I have found an appropriate update to the contributing to documentation URL link that is within the existing pandas repository: 

https://github.com/pandas-dev/pandas/blob/main/doc/source/development/contributing_documentation.rst

**Comment by mroeschke** [comment]
Thanks for the report. We're looking to disable the wiki eventually (https://github.com/pandas-dev/pandas/issues/30410) so don't think it's worth fixing this item. Closing.
