### ISSUE TITLE
BUG: standard deviation in aggregation is incorrect

### ISSUE THREAD

**Issue by jdpeiffer6** [pandas-dev/pandas#47213]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
# 1. Create dataset
import pandas as pd
import numpy as np

df = pd.DataFrame(
    {
        "A": [1, 1, 1, 1],
        "B": [1, 1, 2, 2],
        "C": [0.362838, 0.227877, 1.267767, -0.562860],
    }
)

# 2. Group by column A and B, then compute aggregate statistics
# The mean will be correct and the standard deviation will be wrong 
grouped_stats = df.groupby(['A','B'])['C'].agg(['mean','std'])
print('Ouput of groupby:')
print(grouped_stats)
print(f'\nGrouped std (wrong) is {grouped_stats.iloc[0,1]}')      #this will be incorrect
print(f'Grouped mean (right) is {grouped_stats.iloc[0,0]}')      #this will be correct

# 3. Subset the dataframe to get the data where A is 1 and B is 1
# Then compute mean and std
tmp = df[(df['A']==1) & (df['B'] ==1)]['C']
print(f'Actual std (right) is {np.std(tmp)}')
print(f'Actual mean (right) is {np.mean(tmp)}')

# 4. Lets make sure the data that secion 2 is computing std with is correct
tmp2 = df.groupby(['A','B'])['C'].apply(list)
print('\nData is correct when using groupby to make a list:')
print(tmp2)   #this is the right data
print(f'std of tmp2[1][1]: {np.std(tmp2[1][1])}')
```

### Issue Description

When using `.groupby` and `.agg` on a pandas dataframe as in `grouped_stats = df.groupby(['A','B'])['C'].agg(['mean','std'])
` the std returns the incorrect number while the mean is correct.

In the above example, the line `grouped_stats = df.groupby(['A','B'])['C'].agg(['mean','std'])` should return 0.067 as the std for A=1, B=1, but it does not. Section 4 shows the data both aggregations are operating on seems to be correct.

### Expected Behavior

The std should be correct.

### Installed Versions

'1.4.2'

**Comment by kwsp** [comment]
I can reproduce this on the main branch of pandas `'1.5.0.dev0+866.gb1b788fefc'` on macOS.

**Comment by jreback** [comment]
ddof=1 is the default this is not the same as np.std

https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.GroupBy.std.html?highlight=std#pandas.core.groupby.GroupBy.std

there are a few issues in thr tracker like this which are all closed

we would certainly take a doc update

**Comment by jdpeiffer6** [comment]
ah thanks. a note similar to the one on this page may be helpful? https://numpy.org/doc/stable/reference/generated/numpy.std.html
