### ISSUE TITLE
ENH: Pandas to_dict should allow the option of converting index to string from int

### ISSUE THREAD

**Issue by davepruitt** [pandas-dev/pandas#47210]
#### Is your feature request related to a problem?

In my current situation, I am using pandas in conjunction with MongoDB, but I'm sure this request is likely applicable to multiple situations.

Consider the following simple dataframe:

```
data = [["Hello", "World"], ["Second", "Row"]]
df = pandas.DataFrame(data, columns=["C1", "C2"])
```

Now let's say I want to convert this to a dictionary. That's simple enough. We just called `to_dict()`: 
`my_python_dictionary = df.to_dict()`

It results in the following Python dictionary:

`{'C1': {0: 'Hello', 1: 'Second'}, 'C2': {0: 'World', 1: 'Row'}}`

You'll notice that there are _integer_ dictionary keys. While using integer dictionary keys is valid in Python, MongoDB complains. To get around this, I currently have to do something like this before I can save this to MongoDB:

```
import json
my_python_dictionary_2 = json.loads(df.to_json())
```

Now, the dictionary's integer keys are strings:
`{'C1': {'0': 'Hello', '1': 'Second'}, 'C2': {'0': 'World', '1': 'Row'}}`

This latest dictionary is acceptable as output to MongoDB, which converts it to BSON.

It would be useful to not have to convert to JSON first and then convert to a Python dictionary. That's two steps. This should be able to be done in 1 step. Something like this:
`my_python_dictionary = df.to_dict(convert_index_to_string=True)`

It may even be useful to go back the other direction:
`df = pandas.DataFrame.from_dict(my_python_dictionary, convert_index_to_int=True)`

#### Describe the solution you'd like

The `to_dict` function should have an option to convert the index from an int to a string. Conversely, the `from_dict` function should have an option to convert the index from a string to an int.

```
my_python_dictionary = df.to_dict(convert_index_to_string=True)
df = pandas.DataFrame.from_dict(my_python_dictionary, convert_index_to_int=True)
```

#### API breaking implications

Since this would only be the introduction of an optional parameter to a function, it wouldn't really break any APIs.

#### Describe alternatives you've considered

The alternative is an undesirable two-step process:
`my_python_dictionary_2 = json.loads(df.to_json())`

#### Additional context

None needed.

**Comment by mroeschke** [comment]
Thanks for the request but I would be -1 on this feature as it's too specific toward the index and a data type.

One can just as easily convert the data index before exporting with `to_dict` e.g. `df.set_axis(df.index.astype("string"), axis="index").to_dict()`

**Comment by davepruitt** [comment]
I disagree with you for multiple reasons:

1. Sometimes specificity is okay. If you were to take a poll of everyone who uses pandas to see what datatypes are used as the index, I would be willing to bet that 99% of users just use the default integer indices. The other 1% likely use strings. I bet 0.1% use something else. It is also highly likely that if anyone _ever_ wants to convert the index to some other data type, it is highly likely to be for serialization purposes to/from string.

2. If you still don't like the specificity of it, then allow lambdas or something like this:

```
def index_conversion_function (idx):
    return str(idx)

my_python_dictionary = df.to_dict(index_conversion_function = my_function)
```

3. Your suggested solution is to use the `set_axis` function, but by my understanding that would actually change the index datatype of the dataframe in memory, whereas in my situation I want to keep the index as an integer for the dataframe in memory, and only convert indexes to strings in the output of the to_dict() function.

**Comment by jreback** [comment]
-1 as well

we already have methods to do this generally

i/o functions don't and should not have this ability - then this introduces yet more ways to do the same thing (more complexity and api surface area)

**Comment by phofl** [comment]
Closing as it seems there is no support for this
