### ISSUE TITLE
QST: mode for values where mode can't be calculated

### ISSUE THREAD

**Issue by PARODBE** [pandas-dev/pandas#47223]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/56310134/find-the-mode-across-multiple-columns-for-each-row-of-a-pandas-dataframe

### Question about pandas

Hi,

I have one simple question. Why is the reason for calculate mode when it shouldn't be calculated?. Example: 0,1. Pandas give me result 0, but it should be something like nan in my opinion, or 0,1,1,0 is the same situation, you can't obtain the mode. How could I solutionate this aspect?

Thanks
Pablo

**Comment by rhshadrach** [comment]
Your examples have multiple modes. In such cases, pandas should be returning all of the modes. Can you post the code where pandas produces the answer 0 for inputs 0, 1?

**Comment by PARODBE** [comment]
In this example you can see as the mode select the first argument:
![image](https://user-images.githubusercontent.com/62376157/172375253-ef108fca-77a7-4c04-bee6-5fbb1340ac26.png)

Why??? In my opinion if the mode can not be calculated, should appear something that a nan, no?

**Comment by PARODBE** [comment]
here you can see an example: 

![image](https://user-images.githubusercontent.com/62376157/172378667-7abd518d-9366-4417-b908-aff34b81f40e.png)

In my opinion when the mode can not be calculated since with two different values there are not a most frequent value, you should obtain a nan, no?

**Comment by rhshadrach** [comment]
Thanks for the example @PARODBE. By using `.iat[0]`, you are ignoring the other modes that pandas is returning. So it is incorrect to say

> Example: 0,1. Pandas give me result 0, ...

pandas is not giving you 0 as a result, but rather both 0 and 1.

> In my opinion when the mode can not be calculated since with two different values there are not a most frequent value, you should obtain a nan, no?

No, it is incorrect to say "the mode can not be calculated". The result of the mode function is to return all the modes.

You may desire to get the value NaN on multimodal data - it is certainly valid for some algorithms. pandas is able to do so:

```
def mymode(x):
    modes = x.mode()
    if len(modes) > 1:
        return np.nan
    else:
        return modes.iat[0]

df = pd.DataFrame({'a': [1, 1, 2, 2, 3], 'b': [4, 5, 6, 6, 7]})
gb = df.groupby('a')
result = gb.agg(mymode)
print(result)

# Gives
#      b
# a     
# 1  NaN
# 2  6.0
# 3  7.0
```

**Comment by rhshadrach** [comment]
@PARODBE - please let me know if you believe there is still an issue here, and can reopen.
