### ISSUE TITLE
DOC: 

### ISSUE THREAD

**Issue by mauriciomm7** [pandas-dev/pandas#47241]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

[/usr/local/lib/python3.7/dist-packages/pandas/core/reshape/concat.py](https://localhost:8080/#) in __init__(self, objs, axis, join, keys, levels, names, ignore_index, verify_integrity, copy, sort)
    328         if isinstance(objs, (ABCSeries, ABCDataFrame, str)):
    329             raise TypeError(
--> 330                 "first argument must be an iterable of pandas "
    331                 f'objects, you passed an object of type "{type(objs).__name__}"'
    332             )

### Documentation problem

the f-string is not working, so it does not print out the object type.

### Suggested fix for documentation

--> 330                 "first argument must be an iterable of pandas ", 
    331                 f"objects, you passed an object of type {type(objs).__name__}" 
    332             )

**Comment by MarcoGorelli** [comment]
works for me, can you show your full code please?
```>>> import pandas as pd
>>> pd.concat([1, 2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marco/pandas-marco/pandas/util/_decorators.py", line 317, in wrapper
    return func(*args, **kwargs)
  File "/home/marco/pandas-marco/pandas/core/reshape/concat.py", line 367, in concat
    op = _Concatenator(
  File "/home/marco/pandas-marco/pandas/core/reshape/concat.py", line 457, in __init__
    raise TypeError(msg)
TypeError: cannot concatenate object of type '<class 'int'>'; only Series and DataFrame objs are valid
>>> 

```

**Comment by mauriciomm7** [comment]
You are right!

it was a problem on my end. 
I was using it in google collab, so sometimes I just need to restart the runtime.
