### ISSUE TITLE
QST: What is a new pandas version going to be?

### ISSUE THREAD

**Issue by YarShev** [pandas-dev/pandas#47270]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/72527621/what-is-a-new-pandas-version-going-to-be

### Question about pandas

Hi,

I see the release notes for [1.4.3](https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.4.3.html) and [1.5.0](https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.5.0.html) pandas versions in the documentation. However, there is no any of these versions in PyPI. I am wondering what is a new pandas version going to be and when that is going to happen?

Many thanks!

**Comment by MarcoGorelli** [comment]
both should be released, you can track them at https://github.com/pandas-dev/pandas/issues/45223 and https://github.com/pandas-dev/pandas/issues/46610

closing for now

**Comment by YarShev** [comment]
@MarcoGorelli, thanks!
