### ISSUE TITLE
BLD: MacOS wheel missing PYI files in `_libs` and `_libs/tslibs` while conda has them

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#47288]
While debugging issues with respect to the new `pandas-stubs` and `pyright` compatibility, the `pyright` developers discovered that the PYI files on MacOS in `_libs` and `_libs/tslibs` are not delivered in the wheel that we supply on pypi.org.

Downloading the MacOS install wheel shows they are not there, while downloading the bz2 files in conda-forge for the conda installation shows that our conda distribution *does* include those `pyi` files.

I think the build procedure for MacOS needs to include those `pyi` files, as we do on Windows and Linux.  Certainly there should be consistency between the wheels and conda distributions.

**Comment by simonjayhawkins** [comment]
> I think the build procedure for MacOS needs to include those `pyi` files, as we do on Windows and Linux. Certainly there should be consistency between the wheels and conda distributions.

agreed there should be consistency.

I see from https://github.com/microsoft/pyright/issues/3540 that there is some overlay of the stubs and the package (pandas) types when the package is not py.typed.

Would it make sense to remove the pyi from the (linux and windows) distributions instead (until pandas becomes py.typed) so that users are only using the pandas-stubs typings or would that only make sense if we also stripped out the inline annotations too?

**Comment by simonjayhawkins** [comment]
cc @lithomas1

**Comment by Dr-Irv** [comment]
> Would it make sense to remove the pyi from the (linux and windows) distributions instead (until pandas becomes py.typed) so that users are only using the pandas-stubs typings or would that only make sense if we also stripped out the inline annotations too?

I'd be a little hesitant to remove the shipped PYI files only because people may be using a type checker with our current stubs that are shipped with pandas, and may not be aware of the "old" pandas-stubs project, or what was created by Microsoft and shipped with VS Code. Forcing them to use the new pandas-stubs project might cause some unneeded pain.

**Comment by lithomas1** [comment]
Something weird is going on. Nightlies have the pyi files. e.g. 
<img width="886" alt="image" src="https://user-images.githubusercontent.com/47963215/172940254-469db942-5255-4934-88ac-4716e4a78a8b.png">
Locally building also yields the pyi files.

**Comment by lithomas1** [comment]
The pandas wheels here for 1.4.2, in multibuild-staging are also fine.
https://anaconda.org/multibuild-wheels-staging/pandas/files.

This is now looking like either an issue with the uploading of wheels or a random build issue. I don't think it is serious enough to warrant re-uploading the wheels, so we can probably wait for 1.4.3 for this one.

**Comment by Dr-Irv** [comment]
Looking at the wheels, it seems that 1.4.1 has the PYI files for MacOS, but 1.4.2 does not.
