### ISSUE TITLE
BUG: renaming columns using df.columns causes different behavior without warning

### ISSUE THREAD

**Issue by jackgoldsmith4** [pandas-dev/pandas#47289]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({'a': [1,2], 'b': [3,4]})
df.columns = [['one', 'two']]
df[df['one'] == 1]

Output:
   one two
0  1.0 NaN
1  NaN NaN
```

### Issue Description

In the example above, the user is filtering the DF rows after "renaming" the columns, leading to a different result than if the user were to use `df.rename()`. I think I understand why `df.columns = [[...]]` doesn't change the underlying columns, but the following `df[df['one'] == 1]` is still able to correctly find the rows with a `1` in column `one`. I'm not really sure what's going on here, specifically why everything else in the correct row is NaN

### Expected Behavior

If this isn't a bug with `df.columns` because the columns aren't actually being renamed (#38547 looked similar), I still think something here should change to help users figure out how to properly rename the columns. A couple of options in my mind:

1.  Issue a warning when a user tries to set new columns using `df.columns = [[...]]`, suggesting use of `df.rename()`
2. Prevent the user from being able to modify the `columns` property of a DataFrame

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : fcd94b3a1e049495d1b7f6af21de261faeb4fa5f
python           : 3.8.13.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.47-linuxkit
Version          : #1 SMP Sat Jul 3 21:51:47 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : C.UTF-8
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0.dev0+916.gfcd94b3a1e
numpy            : 1.22.4
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 62.3.2
pip              : 22.0.4
Cython           : 0.29.30
pytest           : 7.1.2
hypothesis       : 6.46.9
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.8.0
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.3.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.4
brotli           : 
fastparquet      : 0.8.1
fsspec           : 2021.11.0
gcsfs            : 2021.11.0
matplotlib       : 3.5.2
numba            : 0.53.1
numexpr          : 2.8.0
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 8.0.0
pyreadstat       : 1.1.6
pyxlsb           : None
s3fs             : 2021.11.0
scipy            : 1.8.1
snappy           : 
sqlalchemy       : 1.4.36
tables           : 3.7.0
tabulate         : 0.8.9
xarray           : 2022.3.0
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None

</details>

**Comment by simonjayhawkins** [comment]
Thanks @jackgoldsmith4 for the report.

> I think I understand why `df.columns = [[...]]` doesn't change the underlying columns, but the following `df[df['one'] == 1]` is still able to correctly find the rows with a `1` in column `one`. I'm not really sure what's going on here

It is changing it to a single level MultiIndex. was that intentional?

```python
df = pd.DataFrame({"a": [1, 2], "b": [3, 4]})
df.columns = [["one", "two"]]
print(df.columns)
```

```
MultiIndex([('one',),
            ('two',)],
           )
```

the condition `df["one"] == 1`  with a multiIndex returns a DataFrame.

```
     one
0   True
1  False
```

`df[("one",)] == 1` returns a boolean series.

```
0     True
1    False
Name: (one,), dtype: bool
```

and returns the expected result when used as the indexer into the DataFrame?
```
  one two
0   1   3
```

**Comment by jackgoldsmith4** [comment]
@simonjayhawkins you are right, thanks for clarifying! No issue here then, I should have set the columns using `df.columns = [...]` to avoid creating a MultiIndex
