### ISSUE TITLE
TST: tzdata is a required dependency when testing

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#47332]
Nightlies are sadly still broken. 
On Windows, the failures are because tzdata is a required dependency when testing, because of a bug here.
https://github.com/pandas-dev/pandas/blob/259a15ce7e9c2f18cc6c1d37f1c670d413cd23bb/pandas/conftest.py#L1219-L1220
We need to create a dummy ZoneInfo object and check to see if that works as zoneinfo will not raise if tzdata is missing on import, only when creating the ZoneInfo object.

tzdata should also probably be added to the optional dependencies list in the docs and in pandas/compat/_optional.py. 
I dunno which minimum version we should support though.

cc @jbrockmendel (who added zoneinfo support)

_Originally posted by @lithomas1 in https://github.com/pandas-dev/pandas/issues/46856#issuecomment-1145366068_

**Comment by simonjayhawkins** [comment]
for the nightlies to upload, will just skip the test for now. If tests fail the wheel upload to staging is bypassed.

**Comment by simonjayhawkins** [comment]
added tzdata to TEST_DEPENDS for windows env for now. https://github.com/MacPython/pandas-wheels/pull/185

issue remains open to fix in pandas so that pd.test() always works.

**Comment by lithomas1** [comment]
The idea is probably to do something like
```
try:
    utc_zoneinfo = ZoneInfo("UTC")
except ZoneInfoNotFoundError:
    zoneinfo = None
```
in the conftest.
I don't have time to look into this this week, though, so someone else needs to put up a PR. Marked as blocker for rc, since  min deps builds should just work.

**Comment by lithomas1** [comment]
> > We need to create a dummy ZoneInfo object and check to see if that works as zoneinfo will not raise if tzdata is missing on import, only when creating the ZoneInfo object.
> 
> Would making tzdata required solve the issue? Seems easier.

Slightly off topic, but is the idea to replace pytz in the future with tzdata?

**Comment by jbrockmendel** [comment]
> Slightly off topic, but is the idea to replace pytz in the future with tzdata?

i suggested something similar at one point, but definitely not something decided upon
