### ISSUE TITLE
DOC: Breaking change for join, int to float type coercion

### ISSUE THREAD

**Issue by oxlade39** [pandas-dev/pandas#47384]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html

### Documentation problem

The behaviour of join appears to have changed somewhere between pandas version 1.2.4 and 1.4.2.

If if perform an inner join on a float col with a int col then in 1.2.4 the result is ant int64 column. In 1.42 it's a float64.
The below test passes in 1.2.4 but fails in 1.4.2.

I couldn't find any documentation of this behaviour although it seems reasonable it caused me a bit of pain to get to the bottom of and is a breaking change. Is this behaviour documented anywhere and if not could it be?

```python
import pandas as pd
from pandas.testing import assert_frame_equal


def test_join_type_coercion():
    left = [
        {"id": 1, "name": "Chase"},
        {"id": 2, "name": "Sky"},
        {"id": 3, "name": "Marhsall"},
        {"id": None, "name": "Daring Danny X"},
    ]
    right = [
        {"id": 1, "color": "Blue"},
        {"id": 2, "color": "Pink"},
        {"id": 3, "color": "Red"},
    ]

    left_df = pd.DataFrame(left)
    right_df = pd.DataFrame(right)

    joined = (
        left_df.set_index("id")
            .join(right_df.set_index("id"), how="inner")
            .reset_index()
    )
    assert_frame_equal(pd.DataFrame([
        {"id": 1, "name": "Chase", "color": "Blue"},
        {"id": 2, "name": "Sky", "color": "Pink"},
        {"id": 3, "name": "Marhsall", "color": "Red"},
    ]), joined)
```

### Suggested fix for documentation

I'm not too sure what the pattern is here but maybe a note to describe the change in behaviour and at what version it was introduced.

**Comment by guyrt** [comment]
The core problem is that numpy's int datatypes do not allow NaN, but float does. The dtype is coalesced into a numpy float64. This is covered explicitly in https://pandas.pydata.org/docs/user_guide/gotchas.html#support-for-integer-na. See in particular the "NA Type promotions" section in second link.

I'll defer to those with more experience in Pandas, docs, but this seems inappropriate to call out explicitly in the join documentation given it's well covered elsewhere.

**Comment by oxlade39** [comment]
> The core problem is that numpy's int datatypes do not allow NaN, but float does. The dtype is coalesced into a numpy float64. This is covered explicitly in https://pandas.pydata.org/docs/user_guide/gotchas.html#support-for-integer-na. See in particular the "NA Type promotions" section in second link.
> 
> I'll defer to those with more experience in Pandas, docs, but this seems inappropriate to call out explicitly in the join documentation given it's well covered elsewhere. I can see the argument for including in changelogs given it's changed behavior. Are those ever edited post hoc?

How has this changed in pandas 1.2.4 vs 1.4.2?
My point is really that the behaviour of `join` has changed in a breaking way. This (the change in behaviour) should surely be documented somewhere?

**Comment by guyrt** [comment]
Sorry for misreading that. This change happened between 1.2.5 and 1.3.0 and nothing in 1.3.0 change log would have obviously caused it. So, that's the right place to include a note on the breaking change. I'm happy to put together right message and submit PR (doing a little investigation first to understand when the change happens - e.g. I know it only occurs when you use indices in the underlying merge).

**Comment by oxlade39** [comment]
> Sorry for misreading that. This change happened between 1.2.5 and 1.3.0 and nothing in 1.3.0 change log would have obviously caused it. So, that's the right place to include a note on the breaking change. I'm happy to put together right message and submit PR (doing a little investigation first to understand when the change happens - e.g. I know it only occurs when you use indices in the underlying merge). 

That's awesome. Thanks. Let me know if I can help.

**Comment by guyrt** [comment]
I found the bottom of the rabbit hole, which is expressed here:
In v1.2.5 this line:
    c:\users\me\anaconda3\envs\pandas1_2_5\lib\site-packages\pandas\core\indexes\base.py(2869)_intersection()
       2868
    -> 2869         result = other.take(indexer).unique()._values
       2870

does the work of this line in v1.3:
    c:\users\me\anaconda3\envs\pandas1_3\lib\site-packages\pandas\core\indexes\base.py(3150)_intersection_via_get_indexer()
      3149         result = left_unique.take(taker)._values
 -> 3150         return result
      3151


In fact, if you swap the join to rightdf.join(leftdf) you can make 1.3 give what you expected and 1.2.5 give what you did not! 

      (pandas1_2_5) PS C:\Users\me\src> python .\pandas_47384.py
      Pandas version 1.2.5
      Original
         id      name color
      0   1     Chase  Blue
      1   2       Sky  Pink
      2   3  Marshall   Red
      int64
      Swapped
          id color      name
      0  1.0  Blue     Chase
      1  2.0  Pink       Sky
      2  3.0   Red  Marshall
      float64


Compared to

      (pandas1_3) PS C:\Users\riguy\src> python .\pandas_47384.py
      Pandas version 1.3.0
      Original
          id      name color
      0  1.0     Chase  Blue
      1  2.0       Sky  Pink
      2  3.0  Marshall   Red
      float64
      Swapped
         id color      name
      0   1  Blue     Chase
      1   2  Pink       Sky
      2   3   Red  Marshall
      int64
    

Upshot is that the join went from taking type info from right side to type info from left side. That's what I'll put in back ported change log with reference to this explanation.

**Comment by mroeschke** [comment]
Appears based on https://github.com/pandas-dev/pandas/pull/47441 there is no further action here so closing
