### ISSUE TITLE
BUG: Index.equals differs when comparing to object from numpy dtypes vs ea dtypes

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#47383]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
idx1 = pd.Index([1, 2], dtype="Int64")
idx2 = pd.Index([1, 2], dtype="object")
idx1.equals(idx2)

This returns False while

idx1 = pd.Index([1, 2], dtype="int64")
idx2 = pd.Index([1, 2], dtype="object")
idx1.equals(idx2)

returns True.
```

### Issue Description

This seems inconsistent, but not sure if this was an intended difference.

cc @jbrockmendel 

### Expected Behavior

I would expect both to return True, but not sure.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 696e9bd04f512d8286a3e9933e02d50f7fd03f56
python           : 3.8.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.13.0-48-generic
Version          : #54~20.04.1-Ubuntu SMP Thu Jun 2 23:37:17 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0.dev0+953.g696e9bd04f.dirty
numpy            : 1.22.0
pytz             : 2021.1
dateutil         : 2.8.2
setuptools       : 59.8.0
pip              : 21.3.1
Cython           : 0.29.30
pytest           : 7.1.1
hypothesis       : 6.23.1
sphinx           : 4.2.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.1
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.28.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
brotli           : 
fastparquet      : 0.7.1
fsspec           : 2021.11.0
gcsfs            : 2021.05.0
matplotlib       : 3.4.3
numba            : 0.53.1
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 5.0.0
pyreadstat       : 1.1.2
pyxlsb           : None
s3fs             : 2021.11.0
scipy            : 1.7.2
snappy           : 
sqlalchemy       : 1.4.25
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : 0.18.0
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None
None

Process finished with exit code 0

</details>

**Comment by jbrockmendel** [comment]
There's an issue about how strict we want .equals to be, in particular w/r/t dtype checks.

For internal usage in the Index code it is more useful to return False in these cases.  For users it should be consistent.  Maybe a stricter _equals and less strict equals?

**Comment by phofl** [comment]
Thx, #46164, closing this one
