### ISSUE TITLE
Is there a bug in pandas: "Cannot set a frame with no defined index and a value that cannot be converted to a Series"?

### ISSUE THREAD

**Issue by DonSeger** [pandas-dev/pandas#47386]
Trying to create a dataframe but getting this error: "Cannot set a frame with no defined index and a value that cannot be converted to a Series".

This is the line to create the DataFrame: df_open = pd.DataFrame(data = df["open"].values, index = df.index, columns=[t])

As shown below "df["open"].values" is a numpy ndarray with 1624 values. And the df.index is DatetimeIndex with 1624 values.

I have even tried to convert the numpy ndarray to a list, but getting the same error.

What is causing this error?

![pandas bug](https://user-images.githubusercontent.com/94080584/174067715-26dd479f-7486-424b-8819-ee162ad67d7a.png)

**Comment by phofl** [comment]
Hi,

thanks for your report. Could you please provide a minimal reproducible example? This is necessary for us to debug this. See https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by phofl** [comment]
Closing here. Feel free to ping, if you can provide a reproducible example
