### ISSUE TITLE
BUG: Unexpected keyword argument `maxsplit` on `rsplit` even though it is accepted in vanilla Python

### ISSUE THREAD

**Issue by paw-lu** [pandas-dev/pandas#47423]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
>>> import pandas as pd
>>> string = "foo,bar,lorep"
>>> string.rsplit(",", maxsplit=1)  # This works as expected
['foo,bar', 'lorep']
>>> pd.DataFrame({"a": [string]})["a"].str.rsplit(",", maxsplit=1)  # Use kwarg maxsplit
TypeError: rsplit() got an unexpected keyword argument 'maxsplit'
>>> pd.DataFrame({"a": [string]})["a"].str.rsplit(",", 1)  # Change kwarg to arg
0    [foo,bar, lorep]
Name: a, dtype: object
```

### Issue Description

When using `pd.Series.str.rsplit` in Pandas, the accepted kwargs are inconsistent with Python's.

Python's `str.rsplit` accepts the kwarg `maxsplit=`, while Panda's `pd.Series.str.rsplit` does not.

### Expected Behavior

I expect Panda's `pd.Series.str.rsplit` to behave identically to Python's `str.rsplit`, this includes accepting the same kwargs, namely `maxsplit=` in this case.

### Installed Versions

<details> <summary>pd.show_versions()</summary>

```txt
/Users/pawlu/.virtualenvs/pandas-debug-kqdr/lib/python3.9/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit           : 47494a48edf25d5a49b0fb5b896b454c15c83595
python           : 3.9.12.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.4.0
Version          : Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0.dev0+978.g47494a48e
numpy            : 1.22.4
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 62.2.0
pip              : 22.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.4.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
```

</details>

**Comment by MarcoGorelli** [comment]
Hey @paw-lu 

The parameter rpslit does accept (`n`), but it's a bit different to `maxsplits`, as it treats 0 and -1 the same way (split as much as possible):
```
>>> string
'foo,bar,lorep'
>>> string.rsplit(',', maxsplit=0)  # no splits
['foo,bar,lorep']
>>> pd.Series(string).str.rsplit(',', n=0)  # all splits
0    [foo, bar, lorep]
dtype: object
```

Another difference is that `n` can accept `None`, but `maxsplits` can't
```
>>> string.rsplit(',', None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object cannot be interpreted as an integer
>>> pd.Series(string).str.rsplit(',', n=None)
0    [foo, bar, lorep]
dtype: object
```

I'm not sure it's worth going through the effort of adding `maxsplits` and deprecating `n`, but to avoid confusion, I think it'd be good to deprecate non-keyword usage of `n`

i.e. to disallow
```
pd.Series(string).str.rsplit(',', 1)
```
in favour of
```
pd.Series(string).str.rsplit(',', n=1)
```

This would require using the `deprecate_nonkeyword_arguments` dedc3corat

**Comment by paw-lu** [comment]
> The parameter rpslit does accept (n), but it's a bit different to maxsplits, as it treats 0 and -1 the same way (split as much as possible)

> Another difference is that n can accept None, but maxsplits can't

Completeley missed both of these! Didn't know the Pandas implimentation had drifted from the standare library like this.

> I'm not sure it's worth going through a deprecation cycle to introduce maxsplits and remove `n`

Yeah now that I know some of the context (thanks btw) I agree with you.

> but I do think it'd be worthwhile to deprecate passing `n` as positional. This way, people won't confuse it with `maxsplits`

Good idea here. I agree on this one too.

I can take responsibility for implimenting this—but it will be a while until I get to it! It's all good if someone beats me to it!

**Comment by MrShevan** [comment]
Hi, Can I take on me? :)

**Comment by MarcoGorelli** [comment]
Yeah go ahead
