### ISSUE TITLE
REGR: DataFrame.eval not respecting inplace argument in pandas 1.4

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#47449]
```python
import pandas as pd
import numpy as np

# Example for eval
pdf = pd.DataFrame({"A": range(1, 6), "B": range(10, 0, -2), "C": range(11, 16)})
pser = pdf.A
pdf.eval("A = B + C", inplace=True)
# pser != pdf.A after 1.4
```

_Originally posted by @Yikun in https://github.com/pandas-dev/pandas/issues/47188#issuecomment-1148168713_

**Comment by Yikun** [comment]
Thanks!

**Comment by simonjayhawkins** [comment]
moving to 1.4.4

**Comment by CloseChoice** [comment]
first bad commit: [ [`03dd698`](https://github.com/pandas-dev/pandas/commit/03dd698bc1e84c35aba8b51bdd45c472860b9ec3) ] BUG: DataFrame.__setitem__ sometimes operating inplace (https://github.com/pandas-dev/pandas/pull/43406)

**Comment by jbrockmendel** [comment]
I'm unclear on the problem.  we want `(pser == pdf.A).all()`, right?  Thats what I see on main

**Comment by jbrockmendel** [comment]
In core.computation.eval L387 we do `target[assigner] = ret`.  Changing that to 

```
if inplace:
    target.loc[:, assigner] = ret
else:
    target[assigner] =ret
```

fixes the OP example.  Haven't run the test suite with this, or even looked that closely at the code to see if it is reasonable.

**Comment by jorisvandenbossche** [comment]
@Yikun we are fixing this in https://github.com/pandas-dev/pandas/pull/47550, but in general I would recommend to not rely on this too much (updating Series by performing inplace on the DataFrame). There are plans to change that behaviour (https://github.com/pandas-dev/pandas/issues/36195), and actually also to deprecate the inplace keyword (https://github.com/pandas-dev/pandas/issues/16529)

**Comment by Yikun** [comment]
@jorisvandenbossche Thanks for your info!
