### ISSUE TITLE
ENH: Add inplace argument for df.join() 

### ISSUE THREAD

**Issue by charizard-knows** [pandas-dev/pandas#47458]
#### Is your feature request related to a problem?

Adding `inplace` argument for `df.join()` will be more in line with Pandas environment. 

#### Describe the solution you'd like

Add an `inplace`  parameter in `df.join()` so that it becomes 
`df.join(obj,.... inplace=False)`

#### API breaking implications

None

#### Describe alternatives you've considered

Alternative is to assign the new df in place of old df by doing
`df = df.join(other_df)`

**Comment by phofl** [comment]
HI thanks for your report. We are currently discussing deprecating inplace. So this is unlikely to happen.
