### ISSUE TITLE
BUG: Wrong error message output for pd.DataFrame.from_dict

### ISSUE THREAD

**Issue by KianShah** [pandas-dev/pandas#47450]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame([1,2,3])
df_dict = df.to_dict(orient='tight')
df = pd.DataFrame.from_dict(df_dict, orient='abc')
```

### Issue Description

Error msg output is "ValueError: only recognize index or columns for orient"

### Expected Behavior

Error message should include that it can also recognize 'tight' as a valid value for the orient parameter, as of v1.4.0

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>
****

**Comment by phofl** [comment]
Hi, thanks for your report. Would you be interested in submitting a pr?
