### ISSUE TITLE
ENH: Add column_name parameter to DataFrame.reset_index

### ISSUE THREAD

**Issue by jachymb** [pandas-dev/pandas#47455]
#### Describe the solution you'd like

When I run DataFrame.reset_index and transform the index to a new column this way (using drop=False) the new column seems to be hardcoded to be called 'index'. But I want it to be named like 'MyTable_ID'. I suggest DataFrame.reset_index has an optional parameter column_name with the default value 'index'. 

#### API breaking implications

The proposed change introduces a new optional parameter and is fully backwards compatible. 

#### Describe alternatives you've considered

Can simply use df.rename('index', 'MyTable_ID', inplace=True) as a workaround.

#### Additional context

May need some extra care when dealing with multiindex.

**Comment by phofl** [comment]
Hi, thanks for your report. This was added in #46167
