### ISSUE TITLE
When setting levels via pd.set_levels order is not maintained

### ISSUE THREAD

**Issue by ikfdarba** [pandas-dev/pandas#47456]
pd.__version__ = '1.2.4'

I try to convert the column levels of a DataFrame with Multiple Column levels from string to int and reset the levels using set_levels. The levels are in incorrect order after setting using set_levels.

`#read the data`
`current_local_stats=pd.read_csv(output_path,header=[0,1,2],index_col=0)`
`current_local_stats.head()`
![image](https://user-images.githubusercontent.com/25511217/174990137-8006e1a4-8253-481b-aed5-89f1514d923c.png)

`#convert the hours column to int and reset the levels`
`converted_hours = list(map(lambda x: int(x), current_local_stats.columns.get_level_values("hour_LOCAL")))`
`#converted_hours=[4, 5, 3]`
`current_local_stats.columns.set_levels(converted_hours, "hour_LOCAL", inplace=True, verify_integrity=False)`
`current_local_stats.head()`
![image](https://user-images.githubusercontent.com/25511217/174990566-874ea0d7-9ba4-4459-b3f5-db464bbc8963.png)

Notice the hour_LOCAL levels are in incorrect order after resetting the levels. 

Was unable to reproduce bug with different dataset:
`current_local_stats=pd.DataFrame([[1,0,0]],index=["id1"],columns=[["2022-04-01","2022-04-01","2022-04-01"],["hours","hours","hours"],["3","4","5"]])`

**Comment by ikfdarba** [comment]
Hi, unfortunately I wasn't able to reproduce the issue in basic example, however I am confident there's an issue, it has already happend to me several time with set_levels, I dont think this method is useable...

**Comment by phofl** [comment]
We can not debug this, if we don’t have an example wo work with

**Comment by ikfdarba** [comment]
unfortunately I really cant reproduce it with a toy example, Im not sure what it depends on... but Im confident its there, I've seen it happen several times already - maybe check the logic

**Comment by phofl** [comment]
Closing then, feel free to ping to reopen if you can provide an example
