### ISSUE TITLE
BUG: `pd.period_range` ignores multiple of `start` frequency

### ISSUE THREAD

**Issue by jaheba** [pandas-dev/pandas#47465]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

start = pd.Period("2020", freq="3D")

a = pd.period_range(start, periods=2, freq=start.freq)
assert a[1] == start + 1

# Fails
b = pd.period_range(start, periods=2)
assert b[1] == start + 1
```

### Issue Description

The issue lies in `_get_ordinal_range`:

https://github.com/pandas-dev/pandas/blob/37d4c31c8e26a6af8eeb9780d252fab47a4ef57f/pandas/core/arrays/period.py#L1044-L1089

A fix could be to replace:

https://github.com/pandas-dev/pandas/blob/37d4c31c8e26a6af8eeb9780d252fab47a4ef57f/pandas/core/arrays/period.py#L1068-L1072

with

```py
   if freq is None:
        if is_start_per:
            freq = start.freq
            mult = freq.n
        elif is_end_per:
            freq = end.freq
            mult = freq.n
```

### Expected Behavior

Omitting the `freq` argument of `pd.period_range` should be the same as passing the `freq` of the start or end field to it via `freq=`.

### Installed Versions

Not relevant to issue.

**Comment by simonjayhawkins** [comment]
Thanks @jaheba for the report.

> ### Expected Behavior
> Omitting the `freq` argument of `pd.period_range` should be the same as passing the `freq` of the start or end field to it via `freq=`.

from the [docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.period_range.html)...

> freq: str or DateOffset, optional
Frequency alias. By default the freq is taken from start or end if those are Period objects. Otherwise, the default is "D" for daily frequency.

So this does indeed appear to be a bug.

```python
start = pd.Period("2020", freq="3D")
print(pd.period_range(start, periods=2))
# PeriodIndex(['2020-01-01', '2020-01-02'], dtype='period[3D]')
print(b.freq)
# <3 * Days>
```

Note : the `PeriodIndex` frequency is not the difference between any two consecutive elements. see #47227

but 
contributions and PRs welcome.

**Comment by jaheba** [comment]
Thanks @simonjayhawkins -- I have submitted a PR: #47598

**Comment by natmokval** [comment]
I think, PR https://github.com/pandas-dev/pandas/pull/53709 closes this issue.
If there is no objection, I close this issue.
