### ISSUE TITLE
BUG: Roundoff error in cumsum() of large array of float32

### ISSUE THREAD

**Issue by d-cogswell** [pandas-dev/pandas#47488]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import numpy as np
import pandas as pd

# Generate a long sequence of random numbers
np.random.seed(1)
series = pd.Series(np.random.randint(0, high=1e4, size=1000000)/1e4)

# The last element of cumsum() should be the same as sum()
print(f"cumsum(float64): {series.astype('float64').cumsum().iat[-1]}")
print(f"cumsum(float32): {series.astype('float32').cumsum().iat[-1]}")
print(f"   sum(float32): {series.astype('float32').sum()}")

# Sum series as float32
sum = np.float32(0)
for i in series:
    sum += np.float32(i)
sum
```

### Issue Description

I encountered this when working with a large DataFrame with float32. It appears that cumsum() is accumulating roundoff error (by operating on float32?),  while sum() apparently does not accumulate roundoff error. There are no warnings about precision in the documentation.

### Expected Behavior

I expected cumsum(float32) be as accurate as sum(float32), and to force the use of high precision if necessary.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.13.0-51-generic
Version          : #58~20.04.1-Ubuntu SMP Tue Jun 14 11:29:12 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.3
numpy            : 1.23.0
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 44.0.0
pip              : 20.0.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.4.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by phofl** [comment]
Hi, thanks for your report.

We are dispatching to numpy here. It looks like this is on the numpy side:

```
print(f"cumsum(float64): {np.cumsum(series.astype('float64').values)[-1]}")
print(f"cumsum(float32): {np.cumsum(series.astype('float32').values)[-1]}")
```

Could you check the issues at numpy?

**Comment by d-cogswell** [comment]
Ah, it's a numpy issue that was reported [here](https://github.com/numpy/numpy/issues/9329). Looks like they updated the documentation but didn't change anything else. Do you think it's worth sharing this example?

**Comment by phofl** [comment]
Don't think so, they seem to be aware of this. Closing here
