### ISSUE TITLE
DOC: Mention "StyleFrame" package in "DataFrame.to_excel()"

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [pandas-dev/pandas#47525]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_excel.html

### Documentation problem

It is not a "problem" but enhancement.

### Suggested fix for documentation

Do suggest the [StyleFrame](https://styleframe.readthedocs.io/) package to be more flexibel with formating the excel output.

btw: I won't suggest to integrate StyleFrame into pandas. Formatting export outputs is not the job of pandas and I assume you agree with this. But is is an often mentioned "problem" in the internet community that the pandas excel output lacks of the possibility to formatting.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Yes a note would be fine. That was what I mean.

**Comment by rhshadrach** [comment]
I'm not sure we want to be including third party libraries in the API docs unless it's necessary - it seems to be blurring the lines between ecosystem and API docs. +1 on adding to the ecosystem page.

**Comment by attack68** [comment]
The `StyleFrame` documentation does not make it clear to me the specific features, in particular the specific features beyond `pandas.Styler` own capabilities, which for example can already style:

- background colors,
- text colors,
- font styles,
- borders,
- number formats,

I think if we add a third party library to ecosystem, it would be worthwhile stating what it can do, extra, that pandas cannot.

**Comment by akshay-babbar** [comment]
Hi there, i am a user of pandas and want to contribute for the very first time. Can i take this issue?

**Comment by attack68** [comment]
the issue already has an open pull request. please find another issue to tackle.

**Comment by datapythonista** [comment]
From the discussion in #47533, it's unclear why pandas users would use `StyleFrame`, as the pandas `Styler` seems to provide the same functionality. We can surely be missing something, if someone knows in which cases `StyleFrame` should be preferred. please feel free to add a section about it in our Ecosystem page explaining it. But for the time being, closing this issue, as no action is expected.

**Comment by datapythonista** [comment]
Just realized that the original point here was to add the external `StyleFrame` class to `to_excel`, not to the Ecosystem page. While it doesn't seem a good idea to do that, looks like a good idea to add our pandas `Styler` to it. I created #48019 for it (I thought it was better to create a new issue better than reopen this).
