### ISSUE TITLE
WEB: JupyterLite terminal too slow

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#47530]
The `Try it in your browser` terminal in the https://pandas.pydata.org/getting_started.html page, seems to be too slow to me. I've got 10Mb download, and an i7 processor. Nothing too fancy, but quite reasonable to expect things to load not too slow. For me the terminal loads after **20 seconds**, and cells are executed and the terminal is ready to run commands **4 minutes** after the terminal is loaded.

Can someone else have a look and see if the times are similar? @jtpio is this what it needs to take? If this is what everybody is experiencing, and there is nothing we can do about it, I think we should remove the terminal from the website, until things can be faster.

**Comment by datapythonista** [comment]
I tried today with a faster connection, 80Mbps, and displaying the terminal took shorter, a bit less than ten seconds. But running the code took more than one minute.

I did a test to run `print(1)` instead of the pandas code, and the loading time is the same as expected, but running the print takes like 15 or 20 seconds.

I tried the numpy terminal. It loads much faster, like in 3 seconds. I'm using a new incognito session every time, I think caches shouldn't be used. But running the `import numpy` takes like 1m30s.

I'm using Brave on Linux. Would be good if someone else can give it a try, to see if those are the times everybody is experiencing.

**Comment by rhshadrach** [comment]
I got 23 seconds from incognito, 10 seconds when just refreshing the page. I'm using Chrome on Ubuntu.

If the experience isn't too bad for most users, I'm +1 on it remaining. In fact, I just used it while working on a PR to check 1.4.2 behavior and it was quite convenient.

**Comment by datapythonista** [comment]
That sounds more reasonable. Was it 23 seconds until the terminal finished the execution of the cells? What Browser are you using?

**Comment by rhshadrach** [comment]
I'm using Chrome on Ubuntu. That's correct; the terminal finished execution of the cells that are there when the page loads as well as one I provided (`1 + 1`)

**Comment by rhshadrach** [comment]
I recently tried this again, it seems to be hanging now. Even after 30 minutes, I don't get output from any commands in the terminal.

**Comment by datapythonista** [comment]
I tried two days ago from mobile and I couldn't get the default commands executed after couple of minutes. I thought it was a mobile only problem.

@jtpio maybe a problem with the last upgrade?

**Comment by jtpio** [comment]
Ah that looks odd and should have been fixed by https://github.com/pandas-dev/pandas/pull/48329.

I'll have another look to see what's happening.
