### ISSUE TITLE
BUG: incorrect result of applying iloc with slice

### ISSUE THREAD

**Issue by akasolace** [pandas-dev/pandas#47549]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

midx = pd.MultiIndex.from_product([['France','Germany'], ['S','W','T'], ['A','B','C']])
columns = ['vol']
dfmi = pd.DataFrame(np.arange(18).reshape((len(midx), len(columns))),
                    index=midx, columns=columns)
dfmi.sort_index(inplace=True)
dfmi.loc[("France", slice(None), slice("B")),:]


Rmq: the following is working
idx = pd.IndexSlice
dfmi.loc[idx["France", :, "B"], :]

```

### Issue Description

Output does not respect the slice on last index            
```
                   vol
France S A    0
               B    1
            T A    6
               B    7
           W A    3
              B    4
```

### Expected Behavior

       
```
                   vol
France S B    1
            T B    7
           W B    4
```

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.10.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : Intel64 Family 6 Model 167 Stepping 1, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252
pandas           : 1.4.2
numpy            : 1.21.5
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 61.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.3.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.4
brotli           : 
fastparquet      : None
fsspec           : 2022.3.0
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : 3.5.1
numba            : 0.55.1
numexpr          : 2.8.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 8.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 0.20.1
xlrd             : None
xlwt             : None
zstandard        : None

**Comment by d-s-dc** [comment]
Though not a contributor, I think multiIndex slice is misunderstood here. As in [documentation](https://pandas.pydata.org/docs/user_guide/advanced.html#using-slicers) slice refers to a range of values in that index level.
eg :- 
```
dfmi.loc[(slice("France"), slice("S"), slice("A", "C")),:]
```
will refer to all values from A to C at index level 3.

Similarly
```
dfmi.loc[(slice("France"), slice("S"), slice("A", "B")),:]
```
will refer to all values from B to C at index level 3

So when @akasolace put only single value in slice it produced a range from starting index to that value.
For what he wanted to do can be produced by writing `"B"` or `["B"]` which refers to a particular value(s) at a level.
```
dfmi.loc[(slice("France"), slice("S"), "B"),:]
```
or
```
dfmi.loc[(slice("France"), slice("S"), ["B"]),:]
```

**Comment by phofl** [comment]
Agreed with @d-s-dc 

slice(None, "B") selects everything up to this value, which is what I would have expected.

Closing as Usage Question

**Comment by akasolace** [comment]
I understand the explanation but in that case I would suggest to make it clearer in the documentation or even better to force the usage of a tuple (at least throw warning).
Thank you

**Comment by simonjayhawkins** [comment]
> Slicing works up to the given element in the slice. This is not really intuitive in my opinion, slicing multiple elements should be given as

Isn't this how the built-in `slice` works? if only a single value is passed, then that is the slice end https://docs.python.org/3/library/functions.html#slice

```python
[1, 2, 3, 4, 5][slice(3)]
# [1, 2, 3]
```

am I missing something here?
