### ISSUE TITLE
Having the axis variable in the .apply function match other functions

### ISSUE THREAD

**Issue by teddywaweru** [pandas-dev/pandas#47542]
Basically, every other function(that I have utilized), for the axis variable in functions, 0 represents 'index', while 1 represents 'columns'. But this is somehow reversed in the .apply function. Maybe this is by design? I stand to be advised. I personally find it confusing a bit:
![image](https://user-images.githubusercontent.com/57697272/176376109-0fbfb3d8-88df-4323-9bd7-6b3c006913f2.png)
For pandas.DataFrame.dropna()
![image](https://user-images.githubusercontent.com/57697272/176376208-8b9210ea-9923-4e2a-94f4-26a02c42a4aa.png)
For pandas.DataFrame.apply()

**Comment by mroeschke** [comment]
Thanks for the report. Agreed it's unfortunate that this is inconsistent, but I would say at least this is documented fairly clearly, and changing this would be a huge breaking change to make consistent.

**Comment by teddywaweru** [comment]
I'm fairly new to open source projects, so I assume it's a matter of whether the community favours future consistent performance, or ensuring compatibility with existing projects. I'd personally lean more towards future consistency.

**Comment by mroeschke** [comment]
I agree consistency is important, but significant consideration must be given towards use of this existing argument & convention over time. This functionality has existed for years and pandas has many users. Changing this through deprecation would disrupt a lot of users existing code which has to be weighed in the pros/cons.

**Comment by jreback** [comment]
-1 on any change to apply here as breaking the world 

in theory we could introduce a new function but would have to very well named & designed and is in likely to happen w/o major effort and support

**Comment by mroeschke** [comment]
Thanks for the suggestion but closing as this would be too much of an API change given it's ubiquity.
