### ISSUE TITLE
BUG: df.columns.name = 0 is not shown

### ISSUE THREAD

**Issue by ibiscp** [pandas-dev/pandas#47556]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({'test': [1]}, index=[0])

# df.columns.name will not be shown
df.columns.name = 0

# df.columns.name will be shown
df.columns.name = 1
```

### Issue Description

When `df.columns.name` is set to 0, it will not be shown when printing the dataframe.

### Expected Behavior

`df.columns.name = 0` should show `0` when printing the dataframe.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.8.13.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.2.0
Version          : Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.4.2
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 22.0.4
setuptools       : 62.0.0
Cython           : None
pytest           : 7.1.2
hypothesis       : None
sphinx           : 5.0.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.8.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.3.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : 3.5.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by mroeschke** [comment]
I can't reproduce this on main or 1.4.2 

```
>>> import pandas as pd
>>> df = pd.DataFrame({'test': [1]}, index=[0])
>>> df
   test
0     1
>>> df.columns.name = 0
>>> df
0  test
0     1
>>> print(df)
0  test
0     1
>>> pd.__version__
'1.4.2'
```

**Comment by ibiscp** [comment]
Interesting, yes, you are right, it is a jupyter problem.
Closing this issue.
