### ISSUE TITLE
BUG: Can't create column with

### ISSUE THREAD

**Issue by mosc9575** [pandas-dev/pandas#47567]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
dr = pd.date_range('2010-01-01', periods=2, freq='D')

df = pd.DataFrame(index=dr)
df['2009'] = [1,2]
df['2010'] = [1,2] # this line raises an ValueError: Must have equal len keys and value when setting with an iterable

# working code
df_working = pd.DataFrame(columns=['2009', '2010'], index=dr)
df_working ['2009'] = [1,2]
df_working ['2010'] = [1,2]
```

### Issue Description

I am not able to create a column in a pandas DataFrame if I have a DatetimeIndex and the new column name matches by accident part of the date strings.

If the column already exists, it is possible do set values using the same notation which also should create a new column.

### Expected Behavior

Right now it is not if the notation uses axis 0 or 1. This should be cleared.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.9.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.0-20-amd64
Version          : #1 SMP Debian 4.19.235-1 (2022-03-17)
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.3
numpy            : 1.21.2
pytz             : 2021.1
dateutil         : 2.8.2
setuptools       : 60.9.3
pip              : 22.0.3
Cython           : 0.29.28
pytest           : 7.0.1
hypothesis       : None
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.1.1
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : 
fastparquet      : None
fsspec           : 2022.02.0
gcsfs            : None
markupsafe       : 2.1.0
matplotlib       : 3.5.1
numba            : 0.55.1
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
snappy           : None
sqlalchemy       : 1.4.23
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by phofl** [comment]
Hi, thanks for your report.

I think this works as expected. The 2010 column is not really a column. If the column does not exist, we check if the value is in the index to set into a row. 2010 matches your index, hence it tries to set both values into one column, which results in the error. If you set 2011 instead of 2010 this works

**Comment by mroeschke** [comment]
Agreed this is the expected behavior. Closing as a usage question
