### ISSUE TITLE
BUG: Setting incompatible values into ea column raises instead of casting to object

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#47577]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
ser = pd.Series([1, 2], dtype="Int64")
ser[1] = "a"

This raises, while expanding casts to object

ser = pd.Series([1, 2], dtype="Int64")
ser[2] = "a"
```

### Issue Description

Numpy dtypes are casting to object while ea dtypes raise. Was this a deliberate descision?

cc @jorisvandenbossche 

### Expected Behavior

I would probably expect this to work.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 55d9dcf47dd982248c18237b6a09854ea83bc474
python           : 3.8.13.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.0-40-generic
Version          : #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0.dev0+1066.g55d9dcf47d
numpy            : 1.22.4
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 62.3.2
pip              : 22.1.2
Cython           : 0.29.30
pytest           : 7.1.2
hypothesis       : 6.47.0
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.9.0
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.4
brotli           : 
fastparquet      : 0.8.1
fsspec           : 2021.11.0
gcsfs            : 2021.11.0
matplotlib       : 3.5.2
numba            : 0.53.1
numexpr          : 2.8.0
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 8.0.0
pyreadstat       : 1.1.7
pyxlsb           : None
s3fs             : 2021.11.0
scipy            : 1.8.1
snappy           : 
sqlalchemy       : 1.4.37
tables           : 3.7.0
tabulate         : 0.8.9
xarray           : 0.18.2
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None
None

</details>

**Comment by simonjayhawkins** [comment]
> Numpy dtypes are casting to object while ea dtypes raise. Was this a deliberate descision?

#25383 somewhat related. categorical is also inconsistent imo. see https://github.com/pandas-dev/pandas/pull/34011#issuecomment-632150450.

I think assigning a value to the Series should not raise unlike assigning a value to the underlying array which would be expected to raise. So it's a bit more complex than dispatching to the underlying array (unless using `at`).

**Comment by jorisvandenbossche** [comment]
And of course, the fact that setitem with enlargement _does_ cast to object (because it goes through concat code, I think), is another inconsistency within the extension dtypes. 
But that is also an issue for Categorical dtype:

```
In [7]: s.loc[3] = 'd'

In [8]: s
Out[8]: 
0    a
1    b
2    c
3    d
dtype: object
```

**Comment by jbrockmendel** [comment]
Is this closed by the acceptance of PDEP6?

**Comment by phofl** [comment]
Yep, thx
