### ISSUE TITLE
QST: pd.read_sql how to process with null char '\0'

### ISSUE THREAD

**Issue by flyly0755** [pandas-dev/pandas#47593]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/60615623/problem-while-reading-sql-query-in-python-x00-added-after-each-character

### Question about pandas

with  pd.read_sql() method, occur result with null char '\0' show as 口(look like as this, the showed char in the issued page can't show here).
I am not sure it is a bug or not, maybe there is some method to control showed content.
like fillna('') can transfer the None in python to space.

**Comment by mroeschke** [comment]
Appears you have an answer on stackoverflow so closing  https://stackoverflow.com/a/60620926
