### ISSUE TITLE
BUG: Dataframe behaves differently depending on initialization

### ISSUE THREAD

**Issue by lolloz98** [pandas-dev/pandas#47599]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame([["hey_1", 1], ["hey_2", 2], ["hey_3", 3]], columns=[["s", "i"]])
df_2 = pd.DataFrame({"s": ["hey_1", "hey_2", "hey_3"], "i": [1, 2, 3]})

# EXPECTED RESULT
print(df_2[df_2["i"] > 1])

# UNEXPECTED RESULT
print(df[df["i"] > 1])

# UNEXPECTED RESULT -> generates ValueError
print(df == df_2)
```

### Issue Description

Dataframes seem to behave differently depending on their initialization: 
- `df = pd.DataFrame([["hey_1", 1], ["hey_2", 2], ["hey_3", 3]], columns=[["s", "i"]])`
- `df_2 = pd.DataFrame({"s": ["hey_1", "hey_2", "hey_3"], "i": [1, 2, 3]})`

If we apply operations to `df`, we obtain some unexpected results (different from the same operation applied to `df_2`):
```
print(df_2[df_2["i"] > 1])
#### OUTPUT:
       s       i
1  hey_2  2
2  hey_3  3
```

```
print(df[df["i"] > 1])
#### OUTPUT:
     s       i
0  NaN  NaN
1  NaN  2.0
2  NaN  3.0
```

Moreover if we try to compare the two dataframes `df == df_2`, we obtain:
```
ValueError: Can only compare identically-labeled DataFrame objects
```  

### Expected Behavior

What I would expect is that the operations applied to `df` have the same output of the operations applied to `df_2`. Moreover, the two dataframes should be comparable (`df == df_2` should not raise `ValueError`).

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.8.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : it_IT.UTF-8
LOCALE           : Italian_Italy.1252

pandas           : 1.4.3
numpy            : 1.21.4
pytz             : 2021.3
dateutil         : 2.8.2
setuptools       : 56.0.0
pip              : 22.1.2
Cython           : 0.29.23
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.1
IPython          : 7.29.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : 3.4.3
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.2
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by phofl** [comment]
Hi, thanks for your report.

your columns definition seems off. You are using brackets twice, which might lead to a MultiIndex (not sure). But nevertheless, if you want to reproduce the dict behavior, you can only use one bracket
