### ISSUE TITLE
DOC: sample codes should not override Python built-in functions

### ISSUE THREAD

**Issue by wany-oh** [pandas-dev/pandas#47606]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

For example, https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#transformation

> Alternatively, the built-in methods could be used to produce the same outputs.
> 
> ```python
> max = ts.groupby(lambda x: x.year).transform("max")
>
> min = ts.groupby(lambda x: x.year).transform("min")
> 
> max - min
> ```
>

### Documentation problem

It is not good that the user guide lists codes that override Python built-in functions.

This is the only part I happened to find, but others may exist in doc. If so, its should be revised as well.

### Suggested fix for documentation

In this case, `max`/`min` should rename like `max_ts`/`min_ts`.

**Comment by mroeschke** [comment]
Thanks for the report. Happy to have a pull request to adjust the docs here

**Comment by Transurgeon** [comment]
Sorry, for the duplicate pull request. I didn't know @wany-oh would take care of it, I just did it in case..

**Comment by Transurgeon** [comment]
I just added another commit. 

I made some changes relating to this issue with example code overriding built-in functions/parameters.

In this case, using a variable called "columns" for the type and name of each column can create confusion with [Dataframe Columns](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.columns.html). 

I learned that this was also known as a "schema" so I removed a few instances of this issue to rename it to "column_schema". 

I used Linux grep to find all instances of this issue, and manually went through all of them to make sure to differentiate between the actual Dataframe.columns = "[foo]" and column = "[foo]"

You will notice that all my changes have two small parts : 
1. I changed the variable declaration
2. I changed the assignment of the variable from "columns(df)=columns" to "columns=column_schema"

Please let me know if this is ok.

**Comment by phofl** [comment]
I disagree with that. Having a variable named the same as the argument name associates them with each other in my opinion
