### ISSUE TITLE
ENH: __iter__ method of a Series should be type annotated

### ISSUE THREAD

**Issue by diepala** [pandas-dev/pandas#47640]
#### Is your feature request related to a problem?

__iter__ method of pandas series should be type annotated.

#### Additional context

If I type check the code below, I do not get correct types:

```python
import pandas as pd

series = pd.Series([1, 2, 3], dtype=int)  # type = Series[int]
iterable = iter(series) # type = Unkown, type should be Iterable[int] 
```

**Comment by twoertwein** [comment]
It will take quite some time to fix this in pandas (Series isn't even a generic class here). Feel free to open an issue at [pandas-stubs](https://github.com/pandas-dev/pandas-stubs/issues).

**Comment by diepala** [comment]
I have opened the issue [here](https://github.com/pandas-dev/pandas-stubs/issues/119).

**Comment by phofl** [comment]
Can we close this then?
