### ISSUE TITLE
BUG: Failed to build pandas typed-ast

### ISSUE THREAD

**Issue by kzawad1** [pandas-dev/pandas#47681]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
In order to reproduce the following needs to be done:
1. Setup a Windows 11 Pro x86 Virtual Machine.
2. Install Visual Studio 2022 Dev Tools.
3. Install Python 3.10.5.
4. Create a requirements.txt file with "pandas==1.1.5".
5. From the command prompt, run command: "pip install -v -r requirements.txt".
6. Wait for the error to be displayed.
```

### Issue Description

Can't download or build **pandas** library on Windows 11 & Python 3.10.5.

When calling the PIP command as:

```
pip install -v -r requirements.txt
```

Getting the output:

```
Failed to build pandas typed-ast
ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects
```

Attachment has detailed output.
[pip_install_type-ast_error.txt](https://github.com/pandas-dev/pandas/files/9094550/pip_install_type-ast_error.txt)

### Expected Behavior

Expecting to be able to install **pandas** with **pip** command.

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

Pandas will not install on Windows 11 with Python 3.10.5, so can't get the version or call pd.show_versions().  This needs to be resolved for Windows 11.

**Comment by nascheme** [comment]
Is there some reason you are trying to use such an old version?  I suspect that 1.1.5 is not compatible with Python 3.10.  The current release seems to be 1.4.3.

**Comment by kzawad1** [comment]
Yes, I took on an existing project with an already created requirements.txt file.  Eventually by viewing the GitHub pages I saw it was very old, so I made the changes in requirements.txt file:

"pandas==1.1.5" -> "pandas" (took latest 1.4.3)
"typed-ast==1.4.2" -> remove this line

Now, it works just fine.  I am assuming since that pandas 1.1.5 was released in Dec 7, 2020 and that Windows 11 was some time at the end of 2021, this is why a binary does not exist for it.

**Comment by mroeschke** [comment]
Correct, support for pandas 1.1.x has ended, so compatibility with newer Python is not guaranteed. If compatibility is needed, the 1.1.x branch is still available for forking https://github.com/pandas-dev/pandas/tree/1.1.x

Closing as support for 1.1.x has ended
