### ISSUE TITLE
BUG: `groupby(dropna=True).bfill()`/`.ffill()` returns incorrect result

### ISSUE THREAD

**Issue by wany-oh** [pandas-dev/pandas#47693]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
df = pd.DataFrame({"A": [np.nan, 1, np.nan, 1], "B": [0, 1, 2, 3]})
df.groupby(["A"], dropna=True)["B"].bfill()
df.groupby(["A"], dropna=True).bfill()
```

### Issue Description

```python
df = pd.DataFrame({"A": [np.nan, 1, np.nan, 1], "B": [0, 1, 2, 3]})
#      A  B
# 0  NaN  0
# 1  1.0  1
# 2  NaN  2
# 3  1.0  3


df.groupby(["A"], dropna=True)["B"].bfill()
# 0    NaN
# 1    1.0
# 2    NaN
# 3    3.0
# Name: B, dtype: float64

df.groupby(["A"], dropna=False)["B"].bfill()  # is ok
# 0    0
# 1    1
# 2    2
# 3    3
# Name: B, dtype: int64


df.groupby(["A"], dropna=True).bfill()
#                      B
# 0 -9223372036854775808
# 1                    1
# 2 -9223372036854775808
# 3                    3
```

compare with `fillna(method="bfill")`:

```python
df.groupby(["A"], dropna=True)["B"].fillna("bfill")  # is ok
# 1    1
# 3    3
# Name: B, dtype: int64

df.groupby(["A"], dropna=False)["B"].fillna("bfill")  # is ok
# 0    0
# 1    1
# 2    2
# 3    3
# Name: B, dtype: int64
```

This bug occurs no matter what values or dtypes are in group key columns that have `np.nan`/`pd.NA`/`pd.NaT`.

### Expected Behavior

```python
df.groupby(["A"], dropna=True)["B"].bfill()
# 1    1
# 3    3
# Name: B, dtype: int64

df.groupby(["A"], dropna=True).bfill()
#    B
# 1  1
# 3  3
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.10.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Japanese_Japan.932

pandas           : 1.4.3
numpy            : 1.22.4
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 63.1.0
pip              : 22.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : 
fastparquet      : None
fsspec           : 2022.5.0
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : 3.5.2
numba            : 0.55.2
numexpr          : 2.8.0
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 8.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : 0.8.10
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by phofl** [comment]
cc @rhshadrach any idea here? The fillna case is a regression on main since 1.4 was released

**Comment by rhshadrach** [comment]
The result of a transform is always indexed the same as the input. In the case of dropna, we do indeed drop the nans, but then when the result is aligned to the input's index they reappear.

https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.5.0.html#using-dropna-true-with-groupby-transforms

If there is opposition to this behavior, I certainly welcome any thoughts. I agree the name "dropna" is not great when it comes to transforms with the current behavior (to be honest, I'd love dropna=False to be the default and dropna to not even be an option). 

My take: if we were to instead drop the rows, this blurs the line between transforms and filters. In other words, `fillna` could act as a transform, filter, or mix of both depending on the input. By always aligning to the input's index makes the output shape consistent.
