### ISSUE TITLE
BUILD: 

### ISSUE THREAD

**Issue by Karthikkamal22** [pandas-dev/pandas#47698]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

pip3 install pandas-1.3.2.tar.gz  Tar -xvf pandas-1.4.3.tar.gz 

### Installation Method

pip install

### pandas Version

pandas-1.4.3

### Python Version

3.8

### Installation Logs

We are trying to install Pandas library through commands PIP3 INSTALL and TAR -XVZF extracting in the site packages.

Note: We are trying to install pandas on USS On zOS mainframe.
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x480A295070>: Failed to establish a new connection: [Errno 1] EDC9501I The name does not resolve for the supplied parameters.')': /simple/setuptools/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x480A2955B0>: Failed to establish a new connection: [Errno 1] EDC9501I The name does not resolve for the supplied parameters.')': /simple/setuptools/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x480A295700>: Failed to establish a new connection: [Errno 1] EDC9501I The name does not resolve for the supplied parameters.')': /simple/setuptools/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x480A295850>: Failed to establish a new connection: [Errno 1] EDC9501I The name does not resolve for the supplied parameters.')': /simple/setuptools/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x480A2959A0>: Failed to establish a new connection: [Errno 1] EDC9501I The name does not resolve for the supplied parameters.')': /simple/setuptools/
  ERROR: Could not find a version that satisfies the requirement setuptools>=51.0.0 (from versions: none)
  ERROR: No matching distribution found for setuptools>=51.0.0
  ----------------------------------------
ERROR: Command errored out with exit status 1: /python/usr/lpp/IBM/cyp/v3r8/pyz/bin/python3.8 /python/usr/lpp/IBM/cyp/v3r8/pyz/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /S0W1/tmp/pip-build-env-8ftbn_7q/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=51.0.0' wheel 'Cython>=0.29.24,<3' 'oldest-supported-numpy>=0.10' Check the logs for full command output.
Logs2:
tar -xvzf pandas-1.4.3.tar.gz
tar: decompress: FSUM6636 not in compressed format
/u/ibmuser>

**Comment by rhshadrach** [comment]
Thanks for the report @Karthikkamal22 - it appears this is a connection error, not pandas. Are you able to get out to the wider internet from your machine (e.g. using `ping` or `wget`)?

**Comment by phofl** [comment]
Closing for now. Please ping to reopen, if you can answert the questions
