### ISSUE TITLE
BUG: unnecessary warning in scatterplot

### ISSUE THREAD

**Issue by mdruiter** [pandas-dev/pandas#47697]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme()
pd.DataFrame([[0, 1], [1, 0]]).plot.scatter(0, 1)
plt.show()
```

### Issue Description

I get this warning:

> `*c*` argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with `*x*` & `*y*`. Please use the `*color*` keyword-argument or provide a 2D array with a single row if you intend to specify the same RGB or RGBA value for all points.

I [thought](https://github.com/mwaskom/seaborn/issues/2901) seaborn is the one to blame, but all it does is set some colors in a standard way.

[Apparently](https://github.com/mwaskom/seaborn/issues/2901#issuecomment-1182552205) it's pandas who should use the `color=` kwarg instead of `c`.

### Expected Behavior

I would expect no warning.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.10.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Dutch_Netherlands.1252

pandas           : 1.4.3
numpy            : 1.23.1
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 58.1.0
pip              : 22.1.2
Cython           : 0.29.28
pytest           : 7.1.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : None
matplotlib       : 3.5.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.1
snappy           : None
sqlalchemy       : 1.4.36
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by mwaskom** [comment]
This is the relevant line in pandas: https://github.com/pandas-dev/pandas/blob/c711be009b470ce8686887e7324887d7dc87f533/pandas/plotting/_matplotlib/core.py#L1207

**Comment by gflores87** [comment]
Hi, have we addressed this issue yet? I still see this with pandas 1.3.5 and matplotlib 3.3.1. I'm not an expert but happy to help if needed

**Comment by lithomas1** [comment]
I don't get a warning on matplotlib 3.7.1, and seaborn 0.12.2.

Maybe this is fixed?

**Comment by mroeschke** [comment]
Since this isn't happening anymore, closing
