### ISSUE TITLE
BUG: df.columns.levels does not update correctly after removing a column

### ISSUE THREAD

**Issue by adiSilber** [pandas-dev/pandas#47704]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
channels             0            1       
original_columns first second first second
0                    1      5     2      6
1                    3      7     4      8
>>> new_table['added'] = [10, 20]
>>> new_table
channels             0            1        added
original_columns first second first second      
0                    1      5     2      6    10
1                    3      7     4      8    20
>>> new_table.columns.levels
FrozenList([[0, 1, 'added'], ['first', 'second', '']])
>>> new_table.drop(columns=['added'], level=0, inplace=True)
>>> new_table
channels             0            1       
original_columns first second first second
0                    1      5     2      6
1                    3      7     4      8
>>> new_table.columns.levels
FrozenList([[0, 1, 'added'], ['first', 'second', '']])
```

### Issue Description

columns.levels does not changes after removing column from the data frame

### Expected Behavior

>>> new_table.columns.levels
FrozenList([[0, 1], ['first', 'second', '']])

### Installed Versions

<details>

pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.4
fsspec           : 2022.5.0
fastparquet      : 0.8.1
gcsfs            : None
matplotlib       : 3.5.1
numexpr          : 2.8.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 2.0.0
pyxlsb           : None
s3fs             : 0.4.2
scipy            : 1.7.3
sqlalchemy       : 1.3.15
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.53.1

</details>

**Comment by phofl** [comment]
This is the expected behavior to improve performance. Only codes is updated when removing columns
