### ISSUE TITLE
BUG: index shape validation does not happening with Series input data

### ISSUE THREAD

**Issue by dbalabka** [pandas-dev/pandas#47722]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
a = pd.DataFrame({'a': range(5)})
pd.DataFrame({'b': pd.Series(range(10))}, index=a.index)
```

### Issue Description

Unexpectedly for us, we found that part of DataFrame in the production data pipeline was cut because of the incorrect index provided that contains fewer rows than input data. After investigation, we found that the DataFrame constructor does not validate index shape if column data is presented as a Series.

### Expected Behavior

```python
import pandas as pd
a = pd.DataFrame({'a': range(5)})
pd.DataFrame({'b': range(10)}, index=a.index)
```
```text
ValueError: Length of values (10) does not match length of index (5)
```

### Installed Versions

<details>

>>> pd.show_versions()
/home/torinaki/src/ecore-cart-recommender/.venv/lib/python3.8/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.17.4
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.3
setuptools       : 49.2.1
Cython           : None
pytest           : 5.4.3
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.3
numexpr          : None
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : 0.17.0
pytables         : None
pytest           : 5.4.3
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.16
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : 0.53.1

</details>

**Comment by phofl** [comment]
Hi,

thanks for your report. This is the expected behavior. The input data are reindexed with the provided index

**Comment by mroeschke** [comment]
Closing as the expected behavior

**Comment by dbalabka** [comment]
>  This is the expected behavior. The input data are reindexed with the provided index.

@phofl, I would like to emphasize that both examples have provided `index=a.index` parameter while the first example does reindex while second throws an exception:
1. `pd.DataFrame({'b': pd.Series(range(10))}, index=a.index)`
2.  `pd.DataFrame({'b': range(10)}, index=a.index)`
IMO it is inconsistent behavior that should be fixed. Please, pay attention that the difference is in column value types (`'b': pd.Series(range(10))}` and `{'b': range(10)}`), not in indexes!

// cc @mroeschke

**Comment by phofl** [comment]
Again, this is expected. 

When you provide a list with length ten your index has to have the same length.

when you provide an object with an index, e.g. a Series, it is reindexed with the provided index, hence no error

**Comment by dbalabka** [comment]
@phofl, thanks for the quick response. Now clear. An index is provided inside the Series object.
