### ISSUE TITLE
DOC: `pandsa.eval` main body text should cancle bold

### ISSUE THREAD

**Issue by Zeroto521** [pandas-dev/pandas#47735]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.eval.html
https://pandas.pydata.org/docs/reference/api/pandas.eval.html

### Documentation problem

![image](https://user-images.githubusercontent.com/25895405/179199993-e0935a6f-c7a4-471b-adad-7c69df345481.png)

'numexpr' and 'python' lines should not be bold

### Suggested fix for documentation

https://github.com/pandas-dev/pandas/blob/e8093ba372f9adfe79439d90fe74b0b5b6dea9d6/pandas/core/computation/eval.py#L207-L214

add spaces before `:`

```diff
-        - ``'numexpr'``: This default engine evaluates pandas objects using
+        - ``'numexpr'`` : This default engine evaluates pandas objects using
                          numexpr for large speed ups in complex expressions
                          with large frames.
-        - ``'python'``: Performs operations as if you had ``eval``'d in top
+        - ``'python'`` : Performs operations as if you had ``eval``'d in top
                         level python. This engine is generally not that useful.
```

**Comment by rhshadrach** [comment]
Thanks for the report! Would you be interested in putting up a PR to fix?

**Comment by Zeroto521** [comment]
Please check #47847
