### ISSUE TITLE
BUG: groupby transform functions ignore dropna

### ISSUE THREAD

**Issue by GYHHAHA** [pandas-dev/pandas#47743]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
>>> df = pd.DataFrame({"A": [np.nan, 1, np.nan, 1], "B": [4,5,6,7]})
>>> df.groupby(["A"], dropna=True)["B"].cumprod()
0     NaN
1     5.0
2     NaN
3    35.0
>>> df.groupby(["A"], dropna=True)["B"].ffill()
0    NaN
1    5.0
2    NaN
3    7.0
Name: B, dtype: float64
>>> df.groupby(["A"], dropna=True)["B"].rank()
0    1.0
1    1.0
2    2.0
3    2.0
Name: B, dtype: float64
```

### Issue Description

Dropna fails on transform kernel functions. Related issue #47693. (If fixed, close both.)
```
transformation_kernels = frozenset(
    [
        "backfill",
        "bfill",
        "cumcount",
        "cummax",
        "cummin",
        "cumprod",
        "cumsum",
        "diff",
        "ffill",
        "fillna",
        "ngroup",
        "pad",
        "pct_change",
        "rank",
        "shift",
        "tshift",
    ]
)
```

### Expected Behavior

Drop the NaN group.

### Installed Versions

1.4.3

**Comment by rhshadrach** [comment]
Thanks for the report! For cumprod/fillna, the behavior above is not ignoring dropna, rather it is enforcing it. Transforms produce results that have the same index as their input. In these examples we:

 1. dropna
 2. compute the transform op for any remaining data
 3. align with the input's index

It is the last step, alignment, that creates nan results.

For rank, I now get the expected results:

```
0    NaN
1    1.0
2    NaN
3    2.0
Name: B, dtype: float64
```

See also: https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.5.0.html#using-dropna-true-with-groupby-transforms

**Comment by GYHHAHA** [comment]
Thanks for clarification.
