### ISSUE TITLE
BUG: Interchange `Column.null_count` is a NumPy scalar, not a builtin `int`

### ISSUE THREAD

**Issue by honno** [pandas-dev/pandas#47789]
- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.
- [X] I have confirmed this bug exists on the main branch of pandas.

In `PandasColumn` used for the [dataframe interchange protocol](https://data-apis.org/dataframe-protocol/latest/API.html), `null_count` returns the result of `Series.sum()`, which defaults to returning a 0d `ndarray` of the default integer (specifically a NumPy scalar). This is opposed to `int`, which is [specified for `null_count` in the spec](
https://github.com/data-apis/dataframe-api/blob/4f7c1e0c425643d57120c5b73434d992b3e83595/protocol/dataframe_protocol.py#L216).

```python
>>> df = pd.DataFrame({"foo": [42]})
>>> interchange_df = df.__dataframe__()
>>> interchange_col = interchange_df.get_column_by_name("foo")
>>> interchange_col.null_count
0
>>> type(interchange_col.null_count)
numpy.int64  # should be Python's int
```

Relevant code

https://github.com/pandas-dev/pandas/blob/a7c5773d19819b750c719344143aa5b96102e124/pandas/core/exchange/column.py#L180-L184

This doesn't seem to be affecting interchange thus far, so might be a low-prio or wont-fix situation. I'd just add these 0d array situations has often tripped up logic assuming a Python `int` on the Array API side of things, and indeed there's currently a similiar issue for vaex's interchange implementation in https://github.com/vaexio/vaex/issues/2093.

Using local build of `main` upstream.

**Comment by jbrockmendel** [comment]
No idea if it's relevant, but a np.int64 object is a scalar, which is distinct from a 0d numpy ndarray
