### ISSUE TITLE
DOC: Potential issue with creating development environment

### ISSUE THREAD

**Issue by joshuabello2550** [pandas-dev/pandas#47786]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/development/contributing_environment.html

https://pandas.pydata.org/docs/dev/development/contributing.html

### Documentation problem

According to the documentation for contributing to pandas, [here](https://pandas.pydata.org/docs/dev/development/contributing_environment.html), in the section forking, it suggests to use 
```
git clone https://github.com/your-user-name/pandas.git pandas-yourname
```
to create a directory called `pandas-yourname`. However, when following the steps to create a development environment, [here](https://pandas.pydata.org/docs/dev/development/contributing.html) it tells the user to run the code below to use their own fork.
```
docker build --build-arg gh_username=yourname --tag pandas-yourname-env .
```
This leads to an error because in the Dockerfile, the code seen below, tries to clone from the user's fork called `pandas`, when the user was told earlier to create a fork called `pandas-yourname`
```
RUN mkdir "$pandas_home" \
    && git clone "https://github.com/$gh_username/pandas.git" "$pandas_home" \
    && cd "$pandas_home" \
    && git remote add upstream "https://github.com/pandas-dev/pandas.git" \
    && git pull upstream main
```

### Suggested fix for documentation

Clarify to the user that in the Dockerfile in the `RUN mkdir "$pandas_home"` section, the user should replace 
```
&& git clone "https://github.com/$gh_username/pandas.git" "$pandas_home" \
```
with 
```
&& git clone "https://github.com/$gh_username/pandas-yourname.git" "$pandas_home" \
```

**Comment by MarcoGorelli** [comment]
The fork should still be called pandas,  pandas-yourname would only be the name of the folder you clone the repo into locally

**Comment by phofl** [comment]
Closing for now. Please ping to reopen, if the response not solve your problems
