### ISSUE TITLE
DOC: Add sphinx-togglepromt for python code block examples

### ISSUE THREAD

**Issue by Transurgeon** [pandas-dev/pandas#47785]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

Example 1:
https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.groupby.html

Example 2:
https://pandas.pydata.org/docs/dev/reference/api/pandas.crosstab.html#pandas.crosstab

### Documentation problem

In the code blocks for the API examples, sometimes there are multiple outputs. This makes it cumbersome to copy the code for rapid conversion to local development. 

I was thinking it would be convenient if there was a way to hide the outputs of the code blocks.

### Suggested fix for documentation

I did some searching online and found an existing package that does the job.

[Repo of toggleprompt](https://github.com/jurasofish/sphinx-toggleprompt)

Additionally, we could add a similar javascript file under doc/source/_static that could take care of this issue, instead of downloading an additional package.

[Link to implementation of this feature](https://github.com/jurasofish/sphinx-toggleprompt/blob/develop/sphinx_toggleprompt/_static/toggleprompt.js_t)

**Comment by mroeschke** [comment]
Using `sphinx-toggleprompt` would be the preferred solution here (we also wanted to incorporate `sphinx-copybutton`). Pull requests welcome!
