### ISSUE TITLE
DOC: iloc docs should indicate a tuple is valid

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#47799]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html

### Documentation problem

In the docs, we say these are valid parameters:

- An integer, e.g. 5.
- A list or array of integers, e.g. [4, 3, 0].
- A slice object with ints, e.g. 1:7.
- A boolean array.
- A callable function with one argument (the calling Series or DataFrame) and that returns valid output for indexing (one of the above). This is useful in method chains, when you don’t have a reference to the calling object, but would like to base your selection on some value.

But a 2D tuple is valid as well, as shown in the example at the bottom of the page.  So this should be indicated in the docs.

Also, a 1D tuple like `df.iloc[0:2,]` works as well.

See discussion in pandas-stubs at https://github.com/pandas-dev/pandas-stubs/pull/152

### Suggested fix for documentation

Add tuple description to list at the top.

**Comment by roy840831** [comment]
Hi, I would to like work on this issue.

**Comment by berstearns** [comment]
Hi,

Could you give an example what would be a 2D-tuple call in this context ? You meant there's an example on the bottom of the page, but I could not find it. 

Thanks

**Comment by Dr-Irv** [comment]
```python
df.iloc[1:3, 0:3]
```

In python, that gets translated to `df.iloc.__getitem__(tuple(slice(1,3), slice(0,3)))`

You can also do things like ` df.iloc[0:1,1]`
