### ISSUE TITLE
BUG: type hint problem on read_csv

### ISSUE THREAD

**Issue by goldenbull** [pandas-dev/pandas#47798]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
content = """
key     value
node01  ubuntu
node02  windows
node03  mac
node04  android
"""

df: pd.DataFrame = pd.read_csv(io.StringIO(content), delim_whitespace=True)
print(df)
```

### Issue Description

this code runs well, but PyCharm shows a type hint warning:
`Expected type 'str | PathLike[str] | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', got 'StringIO' instead`

### Expected Behavior

I wondered how to use `ReadCsvBuffer` correctly?

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.10.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.17763
machine          : AMD64
processor        : Intel64 Family 6 Model 79 Stepping 1, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Simplified)_China.936

pandas           : 1.4.3
numpy            : 1.23.1
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 62.6.0
pip              : 22.1.2
Cython           : 0.29.30
pytest           : 7.1.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.9.3
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : 1.0.9
fastparquet      : None
fsspec           : 2022.5.0
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : 3.5.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : 8.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.1
snappy           : None
sqlalchemy       : 1.4.39
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : 0.18.0

</details>

**Comment by twoertwein** [comment]
Your example works perfectly fine on main with the inline type annotations of pandas.

I assume you might be using an old(er) version of [pandas-stubs](https://github.com/pandas-dev/pandas-stubs). Running your code with mypy/pyright code against the latest pandas-stubs shows no errors.

**Comment by phofl** [comment]
I think this is a Pycharm issue.

**Comment by mroeschke** [comment]
Sounds like this in an IDE issue therefore closing.
