### ISSUE TITLE
BUG: Series constructor does not work for numpy array-like object

### ISSUE THREAD

**Issue by mesejo** [pandas-dev/pandas#47800]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import numpy as np
import pandas as pd

class ArrayLike:
    def __array__(self, dtype=None):
        return np.asarray([0, 1])

a = ArrayLike()
print(pd.Series(a))

#  Output
#  0    <__main__.ArrayLike object at 0x7f8848211330>
#  dtype: object
```

### Issue Description

In numpy one of the meanings of "array-like" is:
* any object that supplies the [`__array__` function](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.__array__.html), 

As specified per the pandas documentation, the constructor of Series should accept an array-like, quote:

> **data** array-like, Iterable, dict, or scalar value
> Contains data stored in Series. If data is a dict, argument order is maintained. 

### Expected Behavior

For the code: 

```
class ArrayLike:
    def __array__(self, dtype=None):
        return np.asarray([0, 1])

a = ArrayLike()
print(pd.Series(a))
```

the expected output should be:
```
0    0
1    1
dtype: int64
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.10.4.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.5.0
Version          : Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8

pandas           : 1.4.3
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 61.2.0
pip              : 22.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.6
jinja2           : 3.0.3
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.5
brotli           : 
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : 3.5.1
numba            : None
numexpr          : 2.8.3
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 8.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by mesejo** [comment]
More information about the causes of this bug can be found [here](https://stackoverflow.com/a/73050962/4001592)

**Comment by mroeschke** [comment]
Thanks for the report but this is the expected behavior. `__array__` is numpy's array interface for converting an object to a numpy array. This does not mean pandas accepts objects with `__array__`. "Array-like" in pandas generally mean a 1-D container data type.

```
In [11]: import numpy as np
    ...: import pandas as pd
    ...:
    ...: class ArrayLike:
    ...:     def __array__(self, dtype=None):
    ...:         return np.asarray([0, 1])
    ...:

In [12]: np.array(ArrayLike())
Out[12]: array([0, 1])
```

Closing as the expected behavior.
