### ISSUE TITLE
DOC: clarify that assert_produces_warning can take multiple warnings

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#47829]
Noticed in https://github.com/pandas-dev/pandas/pull/47828#issuecomment-1193102806

Currently, it's possible to match multiple warnings, by passing them as a tuple. But, this isn't documented, nor do the types suggest it:

Example:
```python
import warnings
import pytest
import pandas._testing as tm

def me():
    warnings.warn('foo', FutureWarning)
    warnings.warn('bar', UserWarning)

def test_1():
    with tm.assert_produces_warning((FutureWarning, UserWarning), match=r'foo|bar'):
        me()
```

So, the issue would be:
- in https://github.com/pandas-dev/pandas/blob/8c7b0b268436cb4b3755de8d7cb9447957ec2bf8/pandas/_testing/_warnings.py#L19-L27, fix the annotation of `expected_warning` so it can also be `Tuple[Type[Warning], ...]`
- add a test to https://github.com/pandas-dev/pandas/blob/main/pandas/tests/util/test_assert_produces_warning.py for when matching multiple warnings

**Comment by Femme-js** [comment]
Hi, I want to take this forward. Can you help me proceed with it?

**Comment by MarcoGorelli** [comment]
hey @Femme-js - [here](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html)'s the contributing guide

what do you need help with?
