### ISSUE TITLE
DEPR: rolling, expanding, and ewm args and kwargs

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#47836]
See for example the [rolling.sum docs](https://pandas.pydata.org/docs/reference/api/pandas.core.window.rolling.Rolling.sum.html). These args and kwargs are not used for the computation. If any args are passed, these ops will raise. If the kwargs `axis`, `dtype`, or `out` is passed, they will also raise. Any other kwargs are ignored.

This was done to produce warning messages if one tries to use e.g. `np.sum` with a Window object. (ref: #12811, #12644)

```
r = Series(np.random.randn(100)).rolling(2)
np.sum(r)
# pandas.errors.UnsupportedFunctionCall: numpy operations are not valid with window objects. Use .rolling(...).sum() instead
```

If we are to remove these args / kwargs, the error message would instead be `TypeError: sum() got an unexpected keyword argument 'axis'`. While this error message may be more confusing to the user, I do not think we should be adding args / kwargs to our API to defend against a user trying to use pandas objects with NumPy functions.

Any functions where args and kwargs are used (e.g. apply) will not be deprecated.

cc @jreback @jorisvandenbossche @mroeschke for any thoughts.

**Comment by mroeschke** [comment]
+1 to remove *args/**kwargs here
