### ISSUE TITLE
BUG: Wrong representation of float while reading as str from csv file 

### ISSUE THREAD

**Issue by ravindrabajpai** [pandas-dev/pandas#47837]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
df = pd.read_csv('C:\Users\user1\file_with_many_col.csv',dtype=str)
print(df['col40'])
```

### Issue Description

I want to read CSV file with columns as string datatype and write parquet with all columns as string.
Read (turned off inferschema):
df = pd.read_csv('C:\\Users\\user1\\file_with_many_col.csv',dtype=str) 
print(df['col40'])

The original values in col40 inside the csv - 
5
6.251366
5.528543
6.527547
6.377049
5.378082

on printing the column - 
Ran 1 test in 0.007s

OK
0    5.0000000000000000
1    6.2513660000000000
2    5.5285430000000000
3    6.5275470000000002
4    6.3770490000000004
5    5.3780820000000000
Name: maturityBands, dtype: object

Same goes into the file upon saving this dataframe

I have already tried 'str', 'object', str, object etc.

### Expected Behavior

It should keep the values intact - 
5
6.251366
5.528543
6.527547
6.377049
5.378082

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d
python           : 3.7.1.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.3.5
numpy            : 1.21.6
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 10.0.1
setuptools       : 39.1.0
Cython           : None
pytest           : 7.1.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 2022.5.0
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 8.0.0
pyxlsb           : None
s3fs             : 0.4.2
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by ravindrabajpai** [comment]
Posted question on stackoverflow - 
https://stackoverflow.com/questions/73086993/python-pandas-incorrectly-reads-csv-having-decimal-values

And followed this article for solution - 
https://discuss.dizzycoding.com/pandas-read-csv-file-with-float-values-results-in-weird-rounding-and-decimal-digits/

**Comment by phofl** [comment]
Hi, thanks for your report. Could you please provide a minimal and reproducible example? It should be copy and pastebale, see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by phofl** [comment]
Closing for now. Please ping to reopen, if you can provide something reproducible
