### ISSUE TITLE
ENH: Add more "Offset aliases" to Timedelta function

### ISSUE THREAD

**Issue by windowshopr** [pandas-dev/pandas#47845]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I would LOVE to see Pandas.Timedelta allow for all of the Offset Abbreviations as denoted [here](https://pandas.pydata.org/pandas-docs/dev/user_guide/timeseries.html#offset-aliases), because right now it only includes `‘W’, ‘D’, ‘T’, ‘S’, ‘L’, ‘U’, or ‘N’` as possible values.

### Feature Description

As an example, I'm trying to subtract 1 business day (not calendar day) from a datetime value, however `"1B"` results in a `ValueError: invalid unit abbreviation: B` error.

### Alternative Solutions

A solution that works right now, is to shift the datetime index of the dataset by 1 freq value, something like:

```
df.index = df.index.shift(1, freq="1B")
```

and it works, however I would like to see it work in this context as well:

```
date_value = pd.to_datetime("2019-12-10 10:57:00")
new_date_value = date_value - pd.Timedelta("1min")
```

**Comment by jbrockmendel** [comment]
"B" is not a valid freq for Timedelta, only for DatetimeIndex.  Are there other's you have in mind?

**Comment by windowshopr** [comment]
I see. Well either way, it would be nice to see all of those values in the link I provided get implemented into timedelta as valid freq’s. My use case only called for business days, but I would imagine it might help others to incorporate all of them.

**Comment by jbrockmendel** [comment]
offsets and timedeltas are distinct objects/concepts.  the abbreviations in that link can be passed to `pd.offsets.to_offset`

**Comment by mroeschke** [comment]
Appears there not much appetite from the core team to proceed here so closing
