### ISSUE TITLE
BUG: The `nanoseconds` in pd.DateOffset was ignored when add to pd.Series

### ISSUE THREAD

**Issue by seanslma** [pandas-dev/pandas#47856]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

t = pd.Timestamp('2022-01-01')
s = pd.Series([t])

# Output is `2022-01-01 00:30:00`
s + pd.DateOffset(minutes=30)

# Output is `2022-01-01`, nanoseconds offset was ignored
s + pd.DateOffset(nanoseconds=1800000000000)

# Output is `2022-01-01 00:30:00`
s[0] + pd.DateOffset(nanoseconds=1800000000000)
```

### Issue Description

When a pandas date Series adding a DateOffset with component `nanoseconds` the offset was ignored.

### Expected Behavior

The offset component `nanoseconds` should be added to each value of the Series. So the result should be `2022-01-01 00:30:00`.

### Installed Versions

<details>

>>> pd.show_versions()
C:\Users\usr\conda-envs\my-env\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.9.13.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19043
machine          : AMD64
processor        : Intel64 Family 6 Model 58 Stepping 0, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_Australia.1252

pandas           : 1.4.3
numpy            : 1.22.4
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 62.6.0
pip              : 22.1.2
Cython           : 0.29.30
pytest           : 7.1.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           :
fastparquet      : None
fsspec           : 2022.5.0
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : 3.5.2
numba            : 0.55.2
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 7.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.1
snappy           : None
sqlalchemy       : 1.4.39
tables           : None
tabulate         : None
xarray           : 2022.3.0
xlrd             : None
xlwt             : None
zstandard        : None
>>>

</details>

**Comment by srotondo** [comment]
take
