### ISSUE TITLE
DOC: Plotting / Visualization without Jupyter

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [pandas-dev/pandas#47861]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/user_guide/visualization.html

### Documentation problem

All code examples about visualization (e.g. `plot()`) are using Jupyter notebook. This code only runs in such notebooks.
A "usual" python shell interpreter running in a DOS-Box or bash can not handle that code.

I am aware that notebooks are quit usual in the pandas and data science universe. It is kind of a standard by convention. But there are situations where it is not possible and not suited to use them.

### Suggested fix for documentation

Maybe you don't need to rewrite the whole docu.

But maybe it is easy (?) to add an extra section about how to modify such code examples in a way that hey run and work without a notebook also.

And link to that section in the beginning of the visualization part.

**Comment by nwoodweb** [comment]
Hello @Codeberg-AsGithubAlternative-buhtz , 

I am pretty sure that alternatives include MatPlotLibs `plt.show()` and `plt.savefig()` functions. Which can be found [here](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html) and [here](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.show.html?highlight=show#matplotlib.pyplot.show)

I can confirm that `plt.save('filename.png') ` does in fact work on the provided examples from the Python command line initiated in Bash, and can save a myriad of files including pdf, png, tiff, and jpeg. `plt.show()` will display the plot `ts` within whichever graphical interface is being use.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I know that. But it doesn't improve the pandas doc if you just link to the matplotlib doc here in that Issue.

My goal is not to get my own stuff done. My goal is to improve pandas (docu). Newbie users would help it a lot if you would point to the difference between jupyter-code and and how to do it without jupyter.

**Comment by MarcoGorelli** [comment]
Sure, a PR to add a note at the top of the page clarifying that the examples assume you're working in jupyter might be helpful, pull requests welcome

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
> , pull requests welcome

For me, too.

**Comment by nwoodweb** [comment]
I am willing to make a documentation PR.

**Comment by MarcoGorelli** [comment]
Cool, thanks @nwoodweb , [here](https://pandas.pydata.org/docs/development/contributing.html)'s the contributing guide, feel free to tag me in the PR when you open it and I'll review

**Comment by nwoodweb** [comment]
Hi @MarcoGorelli 
I have an issue with setting up the  [pandas development environment](https://pandas.pydata.org/pandas-docs/stable/development/contributing_environment.html), but when I begin

```
conda env create -f environment.yml
```
the installation has been at 'Solving environment: ..." for several hours, and I am not sure how to resolve this.

I have created my own conda environment named `panda-doc` and manually installed the dependencies mentioned in `environment.yaml`. However, when running `python make.py html` to generate the documentation, I run into the following error:
```
ImportError: cannot import name 'Union' from 'types' (/home/username/miniconda3/envs/panda-doc/lib/python3.10/types.py)

```

This error also manifests when running the continuous intergration tools and I am unsure as to how to resolve this.

Regardless I have made the edits to the document page responsible for chart visualization.

**Comment by MarcoGorelli** [comment]
> the installation has been at 'Solving environment: ..." for several hours, and I am not sure how to resolve this.

You might want to look into using `micromamba` instead of `conda` - there's an issue about adding that to the docs btw, it should be much faster to resolve

> However, when running python make.py html to generate the documentation, I run into the following error:

I don't know about that error, can you show the complete traceback? You wouldn't need to build the whole docs anyway, building a single page should be fine, see [here](https://pandas.pydata.org/docs/development/contributing_documentation.html#building-the-documentation) for an example
