### ISSUE TITLE
BUG: `to_sql` string to date and/or time conversion

### ISSUE THREAD

**Issue by VHElise** [pandas-dev/pandas#47874]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example
1. Create table in a MS SQL database.

```sql
USE [Test_Database]
GO
 
SET ANSI_NULLS ON
GO
 
SET QUOTED_IDENTIFIER ON
GO
 
CREATE TABLE [dbo].[mutation] (
	[Identifier] [int] IDENTITY(1, 1) NOT NULL,
	[Sample] [varchar](20) NULL,
	[RunName] [varchar](50) NULL,
	[Date] [datetime] NULL
) ON [PRIMARY]
GO
```

2. Execute the python code to insert data into this table
```python
import pandas as pd
from datetime import datetime
from sqlalchemy import create_engine

# Fill in the password and database
sql_pwd = ''
sql_database_ip = ''

SQL_Engine = create_engine('mssql+pyodbc://' + sql_pwd + '@' + sql_database_ip + '/Test_Database?driver=SQL+Server')
SQL_Conn = SQL_Engine.connect()

run1_date = '27072022, 16:00 +08:00 UTC'
run1_date_string = datetime.strptime(run1_date .replace(':', ''), '%d%m%Y, %H%M %z %Z')

run2_date = '20072022, 13:51 +08:00 UTC'
run2_date_string = datetime.strptime(run1_date .replace(':', ''), '%d%m%Y, %H%M %z %Z')

df = pd.DataFrame([['S1', 'TestRun1', run1_date_string],['S1', 'TestRun2', run2_date_string]], columns = ['Sample', 'RunName', 'Date'])

df.to_sql("mutation", SQL_Conn, if_exists = "append", index = False)
```

### Issue Description

When trying to insert data into a SQL database using pandas v1.4.3, the following error is thrown:
```python-traceback
pyodbc.DataError: ('22007', '[22007] [Microsoft][ODBC SQL Server Driver][SQL Server]Conversion failed when converting date and/or time from character string. (241) (SQLExecDirectW)')
```
#### Traceback

<details> 

```python-traceback
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
    insert_dataframe.to_sql("mutation", sql_conn, if_exists = "append", index = False)
  File "C:\Users\user\.conda\envs\test-env\lib\site-packages\pandas\core\generic.py", line 2951, in to_sql
    return sql.to_sql(
  File "C:\Users\user\.conda\envs\test-env\lib\site-packages\pandas\io\sql.py", line 697, in to_sql
    return pandas_sql.to_sql(
  File "C:\Users\user\.conda\envs\test-env\lib\site-packages\pandas\io\sql.py", line 1739, in to_sql
    total_inserted = sql_engine.insert_records(
  File "C:\Users\user\.conda\envs\test-env\lib\site-packages\pandas\io\sql.py", line 1332, in insert_records
  File "C:\Users\user\.conda\envs\test-env\lib\site-packages\pandas\io\sql.py", line 1322, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "C:\Users\user\.conda\envs\test-env\lib\site-packages\pandas\io\sql.py", line 950, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "C:\Users\user\.conda\envs\test-env\lib\site-packages\pandas\io\sql.py", line 857, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "C:\Users\user\.conda\envs\test-env\lib\site-packages\sqlalchemy\engine\base.py", line 1306, in execute
  File "C:\Users\user\.conda\envs\test-env\lib\site-packages\sqlalchemy\sql\elements.py", line 332, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\user\.conda\envs\test-env\lib\site-packages\sqlalchemy\engine\base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\user\.conda\envs\test-env\lib\site-packages\sqlalchemy\engine\base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\user\.conda\envs\test-env\lib\site-packages\sqlalchemy\engine\base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
    raise exception
  File "C:\Users\user\.conda\envs\test-env\lib\site-packages\sqlalchemy\engine\base.py", line 1799, in _execute_context
    self.dialect.do_executemany(
  File "C:\Users\user\.conda\envs\test-env\lib\site-packages\sqlalchemy\dialects\mssql\pyodbc.py", line 620, in do_executemany
    super(MSDialect_pyodbc, self).do_executemany(
  File "C:\Users\user\.conda\envs\test-env\lib\site-packages\sqlalchemy\engine\default.py", line 729, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.DataError: (pyodbc.DataError) ('22007', '[22007] [Microsoft][ODBC SQL Server Driver][SQL Server]Conversion failed when converting date and/or time from character string. (241) (SQLExecDirectW)')
[SQL: INSERT INTO mutation ([Sample], [RunName], [Date]) VALUES (?, ?, ?)]
[parameters: (('Sample001', 'Run_20Jul2022_1', '2022-07-20 15:25:00.000000 +08:00',))]
```

</details>

It appears to me that something changed in the to_sql function or in the code that it calls to convert a dataframe to SQL insert statement that's causing this issue to arise. The date in the dataframe that is being passed to the to_sql function contains no spaces, whereas the date in the insert SQL statements does contain a space between the time and the timezone. I'm not sure if this is where the issue lies? If any additional information is required, please let me know!

**Note:** In the example code, a connection to a SQL database is created using sqlalchemy and this connection is used in the to_sql function. The values of the database ip address and the password must be filled in in order to get the example to work.

### Expected Behavior

Two rows should be inserted into the database table, which was possible using pandas version 1.4.2.

### Installed Versions

The following snippet produces the output under `Details`.
```python 
import pandas as pd
pd.show_versions()
```

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.10.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.4.3
numpy            : 1.23.1
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 63.2.0
pip              : 22.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.9.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           :
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : 1.4.39
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : None

</details>

A conda environment was created containing Python 3.10, along with the following packages:
| package | version | installed using |
| --------- | -------- | ---------------- |
| pandas | 1.4.3 | pip |
| numpy | 1.23.1 | pip |
| sqlalchemy | 1.4.39=py310he2412df_0 | conda | 
| pyodbc | 4.0.34=py310h8a704f9_0 | conda |
| pytz | 2022.1=pyhd8ed1ab_0 | conda |

The entire environment was exported and can be viewed [here](https://github.com/pandas-dev/pandas/files/9198026/test_env.yml.txt).

**Comment by attack68** [comment]
Can I just check, firstly seems to be a bug in your example: `run2_date_string = datetime.strptime(run1_date .replace(':', ''), '%d%m%Y, %H%M %z %Z')`, you were probably intending `run2_date`.

Secondly, are you sure its not the definition of your column in SQL table setup? Do you need a DateTimeOffset type column instead of a DateTime column?
