### ISSUE TITLE
BUG: parameter "center" cannot be passed to weighted windows

### ISSUE THREAD

**Issue by rzpan** [pandas-dev/pandas#47873]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import scipy.signal

s = pd.Series(range(10))
s.rolling(window=5, win_type="exponential").mean(center=0, tau=1.0, sym=False)
```

### Issue Description

scipy.signal.windows.exponential takes "center" as an optional parameter but it cannot be passed through, likely due to the name being used already.

### Expected Behavior

s.rolling(window=5, win_type="exponential").mean(tau=1.0, sym=False) works fine, should take in parameter "center".

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : b5958ee1999e9aead1938c0bba2b674378807b3d
python           : 3.6.13.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-1160.el7.x86_64
Version          : #1 SMP Mon Oct 19 16:18:59 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.5
numpy            : 1.19.5
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.3
setuptools       : 52.0.0.post20210125
Cython           : None
pytest           : None
hypothesis       : None
...
xarray           : 0.16.2
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : None

</details>

**Comment by mroeschke** [comment]
Thanks for the report. Your version of pandas is fairly old, as I believe this was fixed in a more recent version, 1.2. Please upgrade to fix this particular issue. Closing
