### ISSUE TITLE
ENH/API: add numeric_only with a default of False to numerics

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#4787]
for:

`min,max,sum,var,std,kurt,median,mad,prod,skew`

The big reason to do this is a performance hit when you happen to have an object column. and you don't realize it.

See: http://stackoverflow.com/questions/18701569/pandas-dataframe-mean-very-slow-how-can-i-calculate-means-of-columns-faster

`_reduce` in Frame already supports this (and Series will ignore it), so should be trvial to implement

alternatively could just pass `**kwds` thru (I think we had an issue about this earlier)

**Comment by jbrockmendel** [comment]
-1.  Working in/around DataFrame._reduce and groupby operations that have numeric_only, it is a PITA and hides bugs.

**Comment by jreback** [comment]
yep we can just deprecate this i think; do we have an issue for that?
