### ISSUE TITLE
BUG: Unexpected results when adding offsets to periods stored in series.

### ISSUE THREAD

**Issue by asandeep** [pandas-dev/pandas#47883]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd


df = pd.DataFrame({
  "current_period": [pd.Period(year=2022, month=3, freq="2Q-MAR") for _ in range(3)], 
  "offset": list(range(3))
})

  current_period  offset
0         2022Q4       0
1         2022Q4       1
2         2022Q4       2


df.current_period + df.offset

0    2022Q4
1    2023Q1
2    2023Q2
dtype: period[2Q-MAR]


df.apply(lambda r: r.current_period + r.offset, axis=1)

0    2022Q4
1    2023Q2
2    2023Q4
dtype: period[2Q-MAR]
```

### Issue Description

I am storing half-yearly periods in a Dataframe. When some offset values are added to the periods using the offset series stored in same DataFrame, the periods won't shift as expected.

However, iterating over same DF and adding the offset individually returns the correct output.

### Expected Behavior

The periods should shift correctly irrespective of how offsets are added.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.0-41-generic
Version          : #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_IN
LOCALE           : en_IN.ISO8859-1

pandas           : 1.4.3
numpy            : 1.22.4
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 62.1.0
pip              : 22.0.4
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.9.3
jinja2           : 2.11.3
IPython          : 8.3.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2022.5.0
gcsfs            : None
markupsafe       : 2.0.1
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 7.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : 2022.5.0
scipy            : None
snappy           : None
sqlalchemy       : 1.3.24
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by jbrockmendel** [comment]
Can you check on main.  This looks similar to something i think was fixed recently.

**Comment by asandeep** [comment]
Hey @jbrockmendel ,

Thanks for your response. I just verified this on `main` branch as you said and it works as expected. 

Marking the issue as closed.
