### ISSUE TITLE
BUG: FutureWarning for timezone-naive date time shouldn't be raised when indexing with a date

### ISSUE THREAD

**Issue by mmiller-max** [pandas-dev/pandas#47882]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import datetime as dt
import pytz

index = pd.date_range(dt.datetime(2022,1,1), dt.datetime(2022,1,2), freq="h").tz_localize(pytz.timezone("Europe/Amsterdam"))
df = pd.DataFrame(index=index, data=range(0, len(index)))
df[dt.date(2022,1,1):dt.date(2022,1,2)]

# <stdin>:1: FutureWarning: Indexing a timezone-aware DatetimeIndex with a timezone-naive datetime is deprecated and will raise KeyError in a future version. Use a timezone-aware object instead.
```

### Issue Description

A `date` cannot have a timezone, but the `FutureWarning` shown in the example is still raised because it is converted to a timezone-naive datetime here:

https://github.com/pandas-dev/pandas/blob/9a2276fddc2e72b74a8bba1d50c862b3fb5a176c/pandas/core/indexes/datetimes.py#L747

### Expected Behavior

No `FutureWarning` should be displayed as `pandas` supports slicing with dates, which cannot be timezone-aware, and therefore should ensure that the `datetime`s it creates are in the correct timezone.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.9.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.104-linuxkit
Version          : #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022
machine          : aarch64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.3
numpy            : 1.23.1
pytz             : 2021.1
dateutil         : 2.8.2
setuptools       : 58.1.0
pip              : 22.2.1
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 5.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by mmiller-max** [comment]
I have confirmed this bug exists on `main` branch.

**Comment by jbrockmendel** [comment]
i'd have to double-check but i think we actually deprecated allowing date objects.  it should have a different warning/exception message though

**Comment by vanshtuli** [comment]
@jbrockmendel Is this fixed yet?

**Comment by jbrockmendel** [comment]
AFAIK the warning/exception has not been updated

**Comment by luke396** [comment]
For now, it will raise `TypeError: Cannot compare tz-naive and tz-aware datetime-like objects`

**Comment by mroeschke** [comment]
I think since this deprecation was enforced there's no action here anymore so closing
