### ISSUE TITLE
BUG: take with MultiIndex duplicating index

### ISSUE THREAD

**Issue by ibiscp** [pandas-dev/pandas#47893]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

arrays = [
    np.array(["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"]),
    np.array(["one", "two", "one", "two", "one", "two", "one", "two"]),
]

df = pd.DataFrame(np.random.randn(8, 1), index=pd.MultiIndex.from_arrays(arrays, names=['id1', 'id2']))

df.groupby(level=0, as_index=True).take([0])
```

### Issue Description

The output is duplicating the MultiIndex column:
```
                    0
id1 id1 id2          
bar bar one -0.882352
baz baz one  0.540726
foo foo one  0.075413
qux qux one  0.212060
```

### Expected Behavior

The expected output should be:
```
                0
id1 id2          
bar one -0.882352
baz one  0.540726
foo one  0.075413
qux one  0.212060
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.8.13.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.2.0
Version          : Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.3
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 62.0.0
pip              : 22.0.4
Cython           : None
pytest           : 7.1.2
hypothesis       : None
sphinx           : 5.0.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.8.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.3.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : 3.5.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by attack68** [comment]
The `take` method is documented to return a dataframe with the index, so when you perform this function on a groupby it returns a dataframe with the index for each of the groups, which is also has to list/index, therefore the duplication is expected and part of the mechanical process of your code.

Your code should simply be amended to:

```python
df.groupby(level=0, as_index=True).take([0]).droplevel([0])
```
This is the correct pattern for the desired result.

**Comment by mroeschke** [comment]
Agreed, closing as a usage question
