### ISSUE TITLE
BUG: Assigning multiple columns via .loc - expected to respect column index?

### ISSUE THREAD

**Issue by behrenhoff** [pandas-dev/pandas#47897]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

df_a = pd.DataFrame({"small": [1, 2, -1, -1], "large": [10, 20, -1, -1]})
df_b = pd.DataFrame({"large": [30, 40], "small": [3, 4]}, index=[2, 3])
df_c = pd.DataFrame({"large": [30, 40], "small": [3, 4], "dummy": "dummy"}, index=[2, 3])

def check(a, b):
    updated = a.copy()
    updated.loc[b.index] = b
    print(updated)
    assert (updated.large > updated.small).all()
    
check(df_a, df_c)  # succeeds due to the extra col
check(df_a, df_b)  # raises the assert
```

### Issue Description

When assigning certain rows from one DF to another DF, I expect pandas to respect the column index.

In the example code, there are three DFs, df_a with the columns "small", "large"; df_b with the columns "large" and "small" (in reverse order) and df_c (like df_b but with an additional "dummy" column). In the DFs, large is 10x greater than small. When assigning via updated.loc[b.index] = b, the column order is ignored by pandas and it happily mixes the columns - depending on the b DataFrame!

When doing the update with b=df_c, i.e. with an additional column, then the assignment respects column names. When the dummy column is absent (b=df_b), then large is assigned to small and vice versa.

This can cause bugs which are hard to find. Usually my df_b had extra columns - then the assignment works correctly. But when it doesn't, then it ignores column names.

I can work around this issue by using this:
```
a_extended.loc[df_b.index] = df_b[a_extended.columns]
```
(by the way, the only reason I am not using `update` is that `update` ignores nan values in df_b).

### Expected Behavior

Assignment should respect column names. Always.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.10.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.18.11-051811-generic
Version          : #202207121541 SMP PREEMPT_DYNAMIC Tue Jul 12 15:47:28 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : de_DE.UTF-8
LOCALE           : de_DE.UTF-8

pandas           : 1.4.3
numpy            : 1.23.1
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 59.6.0
pip              : 22.2.1
Cython           : 0.29.30
pytest           : 7.1.2
hypothesis       : None
sphinx           : 5.0.1
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.9.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : 1.0.9
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : 3.5.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.1
snappy           : None
sqlalchemy       : 1.4.37
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : None

</details>

**Comment by behrenhoff** [comment]
It gets weirder:

When using a float value in df_a, the whole thing works as expected!
```
df_a = pd.DataFrame({"small": [1, 2, -1, -1], "large": [10, 20, -1.0, -1]})
```

**Comment by attack68** [comment]
When you use `DataFrame.update` on master (1.5.0) this also gives a Warning:

```
/var/folders/1d/1pxykpz9471c8rlp7fvxtgj80000gn/T/ipykernel_7785/906827343.py:1: FutureWarning: 
In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of
 always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, 
if columns are non-unique, `df.isetitem(i, newvals)`
  updated.update(df_b)
```

Your comment about avoid using `DataFrame.update` warrants the potential enhancement of the method to treat NaNs better. For example:

```
overwrite: bool, default True
    How to handle non-NA values for overlapping keys:
        True: overwrite original DataFrame’s values with values from other.
        False: only update values that are NA in the original DataFrame.
```

should really be something like:

```
overwrite: str, default "left-not-na"
    How to handle values for overlapping keys:
        "left-not-na": overwrite original DataFrame’s values with values from other, except when other is NA.
        "left-all": overwrite original DataFRame's values with values from other in all cases, including NAs.        
        "na-only": only update values that are NA in the original DataFrame.
```

**Comment by behrenhoff** [comment]
Oh, I see! That's totally unexpected - and explains (hopefully) why I didn't find the other bug report, subscribed to that one!

I think that my example (coming from a DF with more columns that happened to have different dtypes) shows better how easily you can end up with an unexpected result. I can imagine that one can run into this problem in other ways as well.

**Comment by phofl** [comment]
Yes this is unfortunate. The single dtype case does not align, hence the weird behavior

**Comment by behrenhoff** [comment]
I just tried to to make the `dummy` column an `int` as you said. In that case I get a "shape mismatch" `ValueError`, so at least that one doesn't go unnoticed.
