### ISSUE TITLE
BUG: read_csv, usecols, header=1 unexpectedly doesn't count an empty first line

### ISSUE THREAD

**Issue by clearoak** [pandas-dev/pandas#47906]
import pandas
import io

#Make the lines with blank first line
a0="\n"
a1="Spam,Eggs,Sausages"
a2="3,2,2"

#Join them
aa=a0 + a1 +"\n" + a2 + "\n"

#Read in with header=1 (UNEXPECTED FAIL)
df_skippy = pd.read_csv(io.StringIO(aa), header=1, usecols=(['Spam','Eggs','Sausages']))

#UNEXPECTED result: ValueError: Usecols do not match columns, columns expected but not found: ['Sausages', 'Eggs', 'Spam']
#THIS IS THE PROBLEM.    THE COLUMN HEADERS ARE ON LINE 1 BUT THE BLANK FIRST LINE IS CAUSING 
#HEADER TO SIMPLY NOT COUNT THAT LINE. 
#(I stared at it and fiddled around for two hours and failed to spot this.  Got it in the morning!)

#But:

#Read in with header=0 (UNEXPECTED SUCCESS)
df_skippy = pd.read_csv(io.StringIO(aa), header=0, usecols=(['Spam','Eggs','Sausages']))

#UNEXPECTED result:
df_skippy.head()

#Spam  Eggs  Sausages
#0     3     2         2

#as desired. 

#=========================================
#But now change a0 :
a0="Beans"

#Join:
aa=a0 + "\n" + a1 +"\n" + a2 + "\n"

#Read in with header=1 (EXPECTED SUCCESS)
df_skippy = pd.read_csv(io.StringIO(aa), header=1, usecols=(['Spam','Eggs','Sausages']))

#EXPECTED result:
df_skippy.head()

#Spam  Eggs  Sausages
#0     3     2         2

#For completenesss use header=0 (EXPECTED FAIL)
df_skippy = pd.read_csv(io.StringIO(aa), header=0, usecols=(['Spam','Eggs','Sausages']))

#And as EXPECTED:
#ValueError: Number of passed names did not match number of header fields in the file

**Comment by MarcoGorelli** [comment]
Does
```
pd.read_csv(io.StringIO(aa), skiprows=1, usecols=(['Spam','Eggs','Sausages']))
```
work?

**Comment by clearoak** [comment]
Yes it does, but I'm talking about header=n here.   The code had worked fine for many file till I hit one with a blank first line, when its behaviour radically changed.  I don't think that can have been intended. 

I think the documentation around the interaction and ordering of skiprows, header, usecols, skip_blank_lines could be clarified, though, especially for those of us who will never need to use pandas every day, and for whom unexpected behaviour is a problem.

**Comment by MarcoGorelli** [comment]
The description for `header` reads

>  and the start of the data

so I think it's clear

However, if you feel the docs can be clarified, please do feel free to submit a PR, check the docs for the contributing guide

Closing for now then as I don't think there's a bug here

**Comment by phofl** [comment]
Yep correct, this is intended this way
