### ISSUE TITLE
ENH: pandas.rep() function similar to R rep() or numpy.repeat()

### ISSUE THREAD

**Issue by gvfarns** [pandas-dev/pandas#47904]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

A very common operation in data science is creating a vector of repeating values (NaN's, zeros, ones, or some other value). This functionality is resent in R via the `rep()` function.

```
> rep(10,5)
[1] 10 10 10 10 10
> rep("A",5)
[1] "A" "A" "A" "A" "A"
```

The usual proposed solution for this is to rely on numpy's `repeat()` function and then convert the result into a pandas series. This is a cumbersome solution for such a frequent operation, and not easily found by an inexperienced user. Pandas has special functions for many a less-frequently used operation. I therefore suggest that pandas implement a `rep()` function that creates a pandas series by repeating its argument.

```
>>> pd.rep(10,5))
0    10
1    10
2    10
3    10
4    10
dtype: int64
```

It should work with any kind of object input, similar to `np.repeat()`.

### Feature Description

```
rep = lambda a, repeats, axis=None: pd.Series(np.repeat(a,repeats,axis))
```

### Alternative Solutions

You can create a repeating series using `pandas.Series(x,index=range(50))` but it does not work for all object types. If a list, dictionary, or similar object is passed as `x`, we get an error about matching lengths.

If this could somehow be generalized so `x` could be any object that can be in a series, then this might be a feasible solution, although it woull still be one of those things many people doesn't know about. Also the solution would need to not break existing code.

### Additional Context

https://stackoverflow.com/questions/54103074/equivalent-rep-of-r-in-pandas-dataframe

https://stackoverflow.com/questions/12235552/r-function-rep-in-python-replicates-elements-of-a-list-vector

https://stackoverflow.com/questions/44688178/rs-replicate-and-do-call-functions-equivalent-in-python

* Numpy has a good function called `numpy.repeat()` that does exactly this, but returns an ndarray instead of a pandas series. 
* Also `numpy.zeros()` for the very common case where we want a vector of zeros.
* Pandas already has a `Series.repeat()` method, but it is not convenient to use for constructing a new series. We need a general function, either called `pandas.repeat()` or `pandas.rep()`.

**Comment by jreback** [comment]
-1 as this already exists in numpy

**Comment by gvfarns** [comment]
> -1 as this already exists in numpy

There are many functions and methods that exist in both numpy and pandas--most of them. In fact, there are very few operations we would like to do with pandas objects and functions/methods that can't be done by torturing our data into a numpy object or objects, getting the work done there, and then converting back. That is a poor user experience, though, and that mindset invalidates the purpose of pandas' existence.

There are always hard or roundabout ways to do things, but when a thing is very common it should also be easy and straightforward.

**Comment by MarcoGorelli** [comment]
Thanks for the suggestion - agreed that this doesn't need to be in pandas, the solutions in the stackoverflow link you posted seem fine

Closing for now then
