### ISSUE TITLE
DOC/TST: pandas.Series.str.get with dict elements supports passing hashable label

### ISSUE THREAD

**Issue by BeRT2me** [pandas-dev/pandas#47911]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.Series.str.get.html

### Documentation problem

The fact that `Series.str.get` also works with Non-Numerical `dict` types isn't clear in the documentation.

### Suggested fix for documentation

Parameters should be `int` or `str` and an example using a dictionary should be added.

**Comment by mroeschke** [comment]
I find it odd that arguments other than `int` are allowed in `get` since the value should indicate the position. I think instead, a `ValueError` should be raised if the value is not an int.

**Comment by phofl** [comment]
This does not work anyway, this returns an all nan series

```
s = pd.Series(["String",
              (1, 2, 3),
              ["a", "b", "c"],
              123,
              -456,
              {1: "Hello", "2": "World"}])

print(s.str.get({1: 1}))
```

**Comment by xr-chen** [comment]
> I find it odd that arguments other than `int` are allowed in `get` since the value should indicate the position. I think instead, a `ValueError` should be raised if the value is not an int.

Would `TypeError` be more suitable than `ValueError`?

**Comment by mroeschke** [comment]
Sure, `TypeError` makes sense here

**Comment by BeRT2me** [comment]
> This does not work anyway, this returns an all nan series
> 
> ```
> s = pd.Series(["String",
>               (1, 2, 3),
>               ["a", "b", "c"],
>               123,
>               -456,
>               {1: "Hello", "2": "World"}])
> 
> print(s.str.get({1: 1}))
> ```

I'm not sure where you managed to get that passing a dictionary is what I was referring to... 

This is what works just fine:
```
s = pd.Series([{"name": "Hello", "value": "World"}
              {"name": "Goodbye", "value": "Planet"}])

print(s.str.get('name'))
```
Raising an error would destroy functionality...

**Comment by phofl** [comment]
You should have made this significantly clearer in your initial post. 

Anyway, I don’t think this should be supported

**Comment by BeRT2me** [comment]
There's literally an example of it being used with a dictionary already in the existing documentation.

**Comment by xr-chen** [comment]
> ```
> s = pd.Series([{"name": "Hello", "value": "World"},
>               {"name": "Goodbye", "value": "Planet"}])
> 
> print(s.str.get('name'))
> ```
> 
> Raising an error would destroy functionality...

I just tried `s.str['name']` works well even if we raise an error when non-integer type passed in `Series.str.get`.

**Comment by BeRT2me** [comment]
What is the point of `.get` then? `s.str[0]` works just as well.

**Comment by BeRT2me** [comment]
[This is the current implementation](https://github.com/pandas-dev/pandas/blob/14de3fd9ca4178bfce5dd681fa5d0925e057c04d/pandas/core/strings/object_array.py#L249), it's obviously not meant to be `int` only...
```    
    def _str_get(self, i):
        def f(x):
            if isinstance(x, dict):
                return x.get(i)
            elif len(x) > i >= -len(x):
                return x[i]
            return self._str_na_value

        return self._str_map(f)
```
---
If anything, it should be:
```
    def _str_get(self, i, default=None):
        def f(x):
            if isinstance(x, dict):
                return x.get(i, default)
            elif len(x) > i >= -len(x):
                return x[i]
            return default

        return self._str_map(f)
```

**Comment by mroeschke** [comment]
Thanks @BeRT2me. Although I find this "odd usage" being under `str.get`, I suppose this should be supported and have better documentation.

**Comment by BeRT2me** [comment]
I agree that it's odd usage, but how Series.str works for anything (`list`, `tuple`, `dict`, `set`, etc.) that isn't a string hasn't made much sense logically for a while.
