### ISSUE TITLE
ENH: moving columns to first or last index of a dataframe

### ISSUE THREAD

**Issue by muhammadshoaib** [pandas-dev/pandas#47914]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish I can use a function to move a column in the start or end of a DataFrame using moveToStart and moveToEnd functions. 

### Feature Description

```
df.moreToStart("target")
df.moveToEne("target")
```

### Alternative Solutions

```
temp_cols=df.columns.tolist()
index=df.columns.get_loc("target")
new_cols= temp_cols[0:index] + temp_cols[index+1:] + temp_cols[index:index+1]
df=df[new_cols]
```

### Additional Context

Moving target variables in the end to make dataset more smooth for machine learning algorithms.

**Comment by muhammadshoaib** [comment]
It requires names of the first or last column that reduce the generalizability of the function.

**Comment by phofl** [comment]
You could use reindex?

**Comment by attack68** [comment]
-1 on this, since it is just too specific task to have its own function, when methods already exist for simply display:

```python
df = pd.DataFrame({"a": [1,2,3], "b": [4,5,6], "c": [6,7,8]})
df[["c", "a", "b"]]  # moves last to first
df[["c"] + [_ for _ in df.columns if _ != "c"]]  # same
df.reindex(["c", "a", "b"], axis=1)  # same
```

And any of the above are fully generalisable methods

**Comment by phofl** [comment]
Agree with @attack68 

Also -1 on adding this

**Comment by rhshadrach** [comment]
-1 as well; I don't think this is something we should be expanding the API for. Perhaps it'd be helpful to write your own utility function(s), something like:

```
def first_to_front(haystack, needle):
    idx = haystack.index(needle)
    result = [haystack[idx]] + haystack[:idx] + haystack[idx+1:]
    return result

def pd_first_to_front(df, needle):
    result = df[first_to_front(df.columns.tolist(), needle)]
    return result

df = pd.DataFrame({'a': [1], 'b': 2, 'c': 3, 'd': 4})
print(pd_first_to_front(df, 'c'))
```

**Comment by attack68** [comment]
Going to close as not planned for now after feedback.
