### ISSUE TITLE
ENH: read_zeek function to read zeek files into a DataFrame

### ISSUE THREAD

**Issue by jwackito** [pandas-dev/pandas#47915]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish I could open Zeek/Bro files into a DataFrame. Zeek files are mostly .tsv but with an extended header and a oneline footer. I already have a function that parse the header, interpret the separator character and offload the opening to the read_csv function. But I would like to be a native pandas feature so other security researchers and analysts can benefit of the code.

### Feature Description

Add a new read_zeek function into readers.py that interpret the zeek header and then call to read_csv with the proper parameters.

```
def read_zeek(
    filepath_or_buffer: FilePath
 -> DataFrame | TextFileReader:
    _read_zeek_header()
    read_csv()
    
```

### Alternative Solutions

You can use the zat python package to load zeek files into dataframes.
https://pypi.org/project/zat/

**Comment by mroeschke** [comment]
It seem like zat already provides a nice utility to convert a file to a DataFrame: https://supercowpowers.github.io/zat/large_dataframes.html

So I would be -1 to directly include this in pandas.

**Comment by jreback** [comment]
-1 on extending the api like this

we have rejected more common i/o formats in the past - this is way too niche

**Comment by jwackito** [comment]
Got it. Thanks!
