### ISSUE TITLE
BUG: groupby.shift not respecting as_index

### ISSUE THREAD

**Issue by pablojadz** [pandas-dev/pandas#47917]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({"A": ['a1', 'a2', 'a2'], 'B': ['a', 'a', 'b']}).astype('string')
df2 = df.groupby('A', as_index=False).shift()
assert 'A' in df2
```

### Issue Description

column 'A' should be kept in df2 when as_index=False in groupby operation

### Expected Behavior

column 'A' should be kept in df2 when as_index=False in groupby operation

### Installed Versions

pd.show_versions()
/Users/pablo/opt/miniconda3/envs/hr/lib/python3.8/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.8.13.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.5.0
Version          : Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8
pandas           : 1.4.3
numpy            : 1.20.1
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 61.2.0
pip              : 21.2.4
Cython           : None
pytest           : 7.1.2
hypothesis       : None
sphinx           : 5.0.2
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.1
html5lib         : None
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2022.02.0
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : 3.4.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : 4.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : 2022.02.0
scipy            : 1.6.1
snappy           : None
sqlalchemy       : 1.4.39
tables           : None
tabulate         : 0.8.10
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

**Comment by rhshadrach** [comment]
Thanks for the report! As documented:

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html

the `as_index` argument is only for aggregation operations. `shift` is not an aggregation.

**Comment by pablojadz** [comment]
Thanks for the response. I agree with your statement. Although not a bug in as_index, I still think the behavior is undesired because the grouping column is dropped (regardless of the value in `as_index`, you can try my example when `as_index=False`).

**Comment by rhshadrach** [comment]
Indeed - in my experience I typically use a transform like so:

    df['B_shifted'] = df.groupby('A')['B'].shift()

I'd be curious to hear if you have a use-case that isn't satisfied by this.

**Comment by pablojadz** [comment]
I guess that works. I was trying to avoid adding `B_shifted` to df since I don't need it there, but I guess I can always remove it after extracting ['A', 'B_shifted']

Thanks for looking at it

**Comment by rhshadrach** [comment]
Makes sense - you could also for example do:

```
result = df[['A']]  # And any other fields you may need
result['b_shifted'] = df.groupby('A')['B'].shift()
```

I think the key thing about transforms is they (should) return the same index as the input. So by not returning the group, we are avoiding copying data perhaps unnecessarily and it is easy (in my opinion) for the user to add on the groups if they sho choose.
