### ISSUE TITLE
ENH: Allowing more control over the asserion printing format

### ISSUE THREAD

**Issue by savente93** [pandas-dev/pandas#47910]
### Feature Type

- [X] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Within my company we use pandas quite extensively, and with it we use the testing part for our unit tests, more specifically the `assert_frame_equal` however, for the type of data frames we use the output of a failing assertion is completely unreadable. 

### Feature Description

Here is a MWE:
```python
In [1]: import pandas as pd
    ...: from pandas.testing import assert_frame_equal
    ...: from datetime import datetime
    ...: import numpy as np
    ...: df1 = pd.DataFrame(np.ones((365,3)),index=pd.date_range(datetime(2022,1,1),datetime(2022,12,31)),columns=['a','b','c'])
    ...: df2 = df1.copy(deep=True)
    ...: df2.iloc[-1,0] = 0
    ...: assert_frame_equal(df1,df2)
AssertionError: DataFrame.iloc[:, 0] (column name="a") are different

DataFrame.iloc[:, 0] (column name="a") values are different (0.27397 %)
[index]: [2022-01-01T00:00:00.000000000, 2022-01-02T00:00:00.000000000, 2022-01-03T00:00:00.000000000, 2022-01-04T00:00:00.000000000, 2022-01-05T00:00:00.000000000, 2022-01-06T00:00:00.000000000, 2022-01-07T00:00:00.000000000, 2022-01-08T00:00:00.000000000, 2022-01-09T00:00:00.000000000, 2022-01-10T00:00:00.000000000, 2022-01-11T00:00:00.000000000, 2022-01-12T00:00:00.000000000, 2022-01-13T00:00:00.000000000, 2022-01-14T00:00:00.000000000, 2022-01-15T00:00:00.000000000, 2022-01-16T00:00:00.000000000, 2022-01-17T00:00:00.000000000, 2022-01-18T00:00:00.000000000, 2022-01-19T00:00:00.000000000, 2022-01-20T00:00:00.000000000, 2022-01-21T00:00:00.000000000, 2022-01-22T00:00:00.000000000, 2022-01-23T00:00:00.000000000, 2022-01-24T00:00:00.000000000, 2022-01-25T00:00:00.000000000, 2022-01-26T00:00:00.000000000, 2022-01-27T00:00:00.000000000, 2022-01-28T00:00:00.000000000, 2022-01-29T00:00:00.000000000, 2022-01-30T00:00:00.000000000, 2022-01-31T00:00:00.000000000, 2022-02-01T00:00:00.000000000, 2022-02-02T00:00:00.000000000, 2022-02-03T00:00:00.000000000, 2022-02-04T00:00:00.000000000, 2022-02-05T00:00:00.000000000, 2022-02-06T00:00:00.000000000, 2022-02-07T00:00:00.000000000, 2022-02-08T00:00:00.000000000, 2022-02-09T00:00:00.000000000, 2022-02-10T00:00:00.000000000, 2022-02-11T00:00:00.000000000, 2022-02-12T00:00:00.000000000, 2022-02-13T00:00:00.000000000, 2022-02-14T00:00:00.000000000, 2022-02-15T00:00:00.000000000, 2022-02-16T00:00:00.000000000, 2022-02-17T00:00:00.000000000, 2022-02-18T00:00:00.000000000, 2022-02-19T00:00:00.000000000, 2022-02-20T00:00:00.000000000, 2022-02-21T00:00:00.000000000, 2022-02-22T00:00:00.000000000, 2022-02-23T00:00:00.000000000, 2022-02-24T00:00:00.000000000, 2022-02-25T00:00:00.000000000, 2022-02-26T00:00:00.000000000, 2022-02-27T00:00:00.000000000, 2022-02-28T00:00:00.000000000, 2022-03-01T00:00:00.000000000, 2022-03-02T00:00:00.000000000, 2022-03-03T00:00:00.000000000, 2022-03-04T00:00:00.000000000, 2022-03-05T00:00:00.000000000, 2022-03-06T00:00:00.000000000, 2022-03-07T00:00:00.000000000, 2022-03-08T00:00:00.000000000, 2022-03-09T00:00:00.000000000, 2022-03-10T00:00:00.000000000, 2022-03-11T00:00:00.000000000, 2022-03-12T00:00:00.000000000, 2022-03-13T00:00:00.000000000, 2022-03-14T00:00:00.000000000, 2022-03-15T00:00:00.000000000, 2022-03-16T00:00:00.000000000, 2022-03-17T00:00:00.000000000, 2022-03-18T00:00:00.000000000, 2022-03-19T00:00:00.000000000, 2022-03-20T00:00:00.000000000, 2022-03-21T00:00:00.000000000, 2022-03-22T00:00:00.000000000, 2022-03-23T00:00:00.000000000, 2022-03-24T00:00:00.000000000, 2022-03-25T00:00:00.000000000, 2022-03-26T00:00:00.000000000, 2022-03-27T00:00:00.000000000, 2022-03-28T00:00:00.000000000, 2022-03-29T00:00:00.000000000, 2022-03-30T00:00:00.000000000, 2022-03-31T00:00:00.000000000, 2022-04-01T00:00:00.000000000, 2022-04-02T00:00:00.000000000, 2022-04-03T00:00:00.000000000, 2022-04-04T00:00:00.000000000, 2022-04-05T00:00:00.000000000, 2022-04-06T00:00:00.000000000, 2022-04-07T00:00:00.000000000, 2022-04-08T00:00:00.000000000, 2022-04-09T00:00:00.000000000, 2022-04-10T00:00:00.000000000, ...]
[left]:  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...]
[right]: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...]
```

There are three things that I can think of that could make this problem more manageable in order of my preference: 
1. adding a parameter to only display the differences:
```python
assert_frame_equal(df1,df2,display_diff_only=True)

index_diff: ['2022-12-31T00:00:00.000000000]
left: [1.0]
right: [0.0]
``` 
I was unable to find where the printing code in pandas was located for this so I can't provide actual code examples but it would not involve much more than only passing the difference between the series/dataframes to the function that prints the assertions instead of the full objects. 
2. add a parameter that prints the output in column format rather than row. 
```python
assert_frame_equal(df1,df2,display_columnar=True)

index                               a           b
2022-01-01T00:00:00.000000000       1.0        1.0
2022-01-02T00:00:00.000000000       1.0        1.0
...
2022-12-31T00:00:00.000000000       0.0        1.0
```
3. The final suggestion is to have more options for printing the date times 
```python
assert_frame_equal(df1,df2,strftime="%d-%M-%Y")

index_diff: ['2022-01-01','2022-01-02',...]
left: [1.0,1.0,...]
right: [1.0,1.0,...]
```

As said, I couldn't find where these things live in the code base so I can't really provide implementation examples but they are simple/ similar enough to existing functionalities that I'm hoping my usage examples are clear enough. 

### Alternative Solutions

The only other solution I'm aware of something akin to this answer: https://stackoverflow.com/a/72452894 which is to write manual loops to do the comparison yourself so you can output the diff.

**Comment by MarcoGorelli** [comment]
Here's the part of the code that does the printing:

https://github.com/pandas-dev/pandas/blob/6e1a0401420bffd282f3cf8b57e653a39e373d3b/pandas/_testing/asserters.py#L641-L676

> adding a parameter to only display the differences:

I think this is a nice suggestion, though haven't yet look at how complicated that would be to implemented. Interested in having a look / investigating?

**Comment by attack68** [comment]
In the cases where unit tests are being written for pandas, this is likely to be quite bespoke for the user. Maybe a solution is to provide a `callback_on_error` argument, which accepts a user method which reads some of the data passed and prints it or processes it as the user demands in their test?

**Comment by savente93** [comment]
I find it hard to assess that solution. It would allow much more control but also increase complexity by a lot. Wouldn't it make sense at that point just to catch the exception and handle things from there yourself? I don't know how others feel about this, but I'm less keen on the callback solution myself. 

As for how complicated it is: I think not very for someone who knows their way around the code base. I looked into it a bit and had trouble propagating the arguments to the correct functions, more specifically I ran into trouble when I had to interact with the `.pyx` part. However the code itself I think is not _that_ complicated. Because the checking happens on a by column basis I also kind of assumed that columns and incides were check earlier and thus are equal. I imagined something like this: 

```python
col_name = lcol.name
full = pd.concat([lcol.rename(f"{col_name}_left"),rcol.rename(f"{col_name}_right")],axis=1)
msg = f"""objects are different

{message}"""
msg += repr(full[full.iloc[:,0] != full.iloc[:,1]])

raise AssertionError(msg)
```

Of course this is a bit simplified, but for my MWE this would show: 
```python
----> 1 raise AssertionError(msg)

AssertionError: objects are different

            a_left  a_right
2022-12-31     1.0      0.0
```

which I think is really nice. What do you all think? I'm happy to make a PR with this if it looks good to people, and someone can help me a bit with the .pyx, .pyi, etc. files.

**Comment by MarcoGorelli** [comment]
Personally I think that look nice

What interactions would be necessary with pyx / pyi files here? I wouldn't have thought it would be necessary to touch them here

@sinhrks I think you'd added `raise_assert_detail` - any thoughts on the suggestion here?

**Comment by savente93** [comment]
not quite sure, but when I tried to add the argument to the funtion I get the following error: 
```python
~/Documents/personal/projects/pandas/pandas/_libs/testing.pyx in pandas._libs.testing.assert_almost_equal()
     50 
     51 
---> 52 cpdef assert_almost_equal(a, b,
     53                           rtol=1.e-5, atol=1.e-8,
     54                           bint check_dtype=True,

TypeError: assert_almost_equal() got an unexpected keyword argument 'display_diff_only'

```

I assumed this wouldn't become the default hence the added keyword. If you're okay with this becoming the default behavior then this is a non issue of course

**Comment by MarcoGorelli** [comment]
closing as per https://github.com/pandas-dev/pandas/pull/48033#issuecomment-1214634801
