### ISSUE TITLE
BUG: Resampler.quantile produce inconsistent results when interpolation='nearest' and q=0.5

### ISSUE THREAD

**Issue by henrykwong** [pandas-dev/pandas#47942]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({'x': [i for i in range(100)]})
df.index = pd.to_datetime(df['x'], unit='s')

res1 = df.resample('{}S'.format(n)).apply(lambda x: x.quantile(0.5, interpolation='nearest')).iloc[0][0]
res2 = df.resample('{}S'.format(n)).quantile(0.5, interpolation='nearest').iloc[0][0]
print("result from Resample.apply(lambda x: x.quantile(0.5, interpolation='nearest'): \t{}".format(res1))
print("result from Resample.quantile(q=0.5, interpolation='nearest'): \t{}".format(res2))
```

### Issue Description

`Resample.quantile(q=0.5, interpolation='nearest)` and `Resample.apply(lambda x: x.quantile(0.5, interpolation='nearest)` produce different results. Behaviours were consistent when using other interpolation method, i.e. {‘linear’, ‘lower’, ‘higher’, ‘midpoint’} OR when `q!=0.5`

### Expected Behavior

Actual result:
result from `Resample.apply(lambda x: x.quantile(0.5, interpolation='nearest')`: 	50
result from `Resample.quantile(q=0.5, interpolation='nearest')`: 	49

Expected result:
result from `Resample.apply(lambda x: x.quantile(0.5, interpolation='nearest')`: 	50
result from `Resample.quantile(q=0.5, interpolation='nearest')`: 	50

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.8.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.0-41-generic
Version          : #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.4.3
numpy            : 1.22.3
pytz             : 2021.3
dateutil         : 2.8.2
setuptools       : 52.0.0.post20210125
pip              : 21.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.4.3
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.0.1
pandas_datareader: 0.10.0
bs4              : 4.10.0
bottleneck       : None
brotli           : 
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.0.1
matplotlib       : 3.4.3
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by attack68** [comment]
Can I ask if this is a case of up/downcasting. Similar issues were observed in discussion here: #46282

**Comment by rhshadrach** [comment]
This looks to be an inconsistency in groupby.quantile:

```
ser = pd.Series([0, 1, 2, 3])
print(ser.quantile(0.5, interpolation="nearest"))
# 2
print(ser.groupby([0, 0, 0, 0]).quantile(0.5, interpolation="nearest"))
# 0    1
# dtype: int64
```

due to this line:

https://github.com/pandas-dev/pandas/blob/612823e824805b97a2dbe258ba808dc572083d49/pandas/_libs/groupby.pyx#L1287

PRs to fix are welcome!
