### ISSUE TITLE
TYP: DataFrame constructor should allow for dict_items

### ISSUE THREAD

**Issue by jonashaag** [pandas-dev/pandas#47943]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
x = {"a": [1]}
pd.DataFrame(x)
pd.DataFrame(list(x.items()))
pd.DataFrame(x.items())
```

### Issue Description

Last line doesn't type check:

```
x.py:5: error: Argument 1 to "DataFrame" has incompatible type "dict_items[str, List[int]]"; expected
"Union[Union[ndarray[Any, Any], List[Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]]], Dict[str, ndarray[Any, Any]], Sequence[Any], Index, Series[Any]], DataFrame, Dict[Any, Any], None]"
    pd.DataFrame(x.items())
                 ^
Found 1 error in 1 file (checked 1 source file)
```

### Expected Behavior

Should support `dict_items`.

### Installed Versions

```
  pandas                   1.4.3               
  pandas-stubs             1.4.3.220801        
```

**Comment by twoertwein** [comment]
Can you please open an issue at [pandas-stubs](https://github.com/pandas-dev/pandas-stubs). pandas itself does not have annotations for the first argument so that seems to be an issue with pandas-stubs (and pandas for not having annotations).

I'm fine with having duplicate issues here and at pandas-stubs but I would not keep issues at pandas for missing annotations (then we would get too many issues).

**Comment by simonjayhawkins** [comment]
> I'm fine with having duplicate issues here and at pandas-stubs but I would not keep issues at pandas for missing annotations (then we would get too many issues).

I think we have other ideas for keeping the type annotations between the codebase and the stubs in sync so better to close and not have duplicate issues (imo) to avoid splitting the discussion. 

With regard to missing annotations, mypy (and pyright) offer many reports so again (imo) we don't need any issues for this.

so I have not looked at this issue in particular, but happy to close in principal.

**Comment by simonjayhawkins** [comment]
> so I have not looked at this issue in particular, but happy to close in principal.

and this could maybe apply to other open typing issues in the main pandas repo issue tracker.

**Comment by twoertwein** [comment]
Let's close this issue in favor of the one at pandas-stubs.
