### ISSUE TITLE
QST: How to locate data correctly in dataframe which read from csv？

### ISSUE THREAD

**Issue by forestbat** [pandas-dev/pandas#47969]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/73235561/how-to-locate-data-correctly-in-dataframe-which-read-from-csv

### Question about pandas

I have a csv file which has two colomns，the first column is WKT of Shapely's LineString(you only need to regard it as a string),the second is coord which is a tuple of float,this is my csv which name is "nearest_line_project_points.csv":

https://paste.ubuntu.com/p/mjDK2PHMp2/

Now I want to choose a string from 'nearest_line_wkt' column by a known coord, and my code is like this:

```
nearest_line_project_points: DataFrame = pd.read_csv('nearest_line_project_points.csv')
nearest_source_line_wkt = nearest_line_project_points['nearest_line_wkt'][nearest_line_project_points['nearest_point'] == nearest_source_point]
```

However it crashed and debug info told me this:

`nearest_source_line_wkt = {Series:(0,)}`

> TypeError: Only str is accepted.

So what's my problem and how to solve it?

**Comment by phofl** [comment]
Hi, thanks for your report. Please ask usage questions on stackoverflow. If you think this is a bug on our side, please ping to reopen
