### ISSUE TITLE
ENH: 

### ISSUE THREAD

**Issue by michaeldorner** [pandas-dev/pandas#47977]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish I could use pandas to anomyze a Series or DataFrame.

### Feature Description

Add a new method to Series `anonymize` or `hide` that hashes the input and overrides the column name by default: 

    df.column_one.anonymize()

Via further parameters you can specify the hashing algorithm and if the old table should be kept:

    DataFrame.anonymize(self, inplace=False, hash='md5', override=True)

I sketched (only sketched! :)) how a solution could look like:
```
def anonymize(self, column, replace=False, hash_algorithm=hashlib.md5):
    def hide(str: str):
        return hash_algorithm(str.encode('utf-8')).hexdigest()
          
    if replace:
        self[column] = self[column].apply(hide)
    else:
        self[replace] = self[column].apply(hide)
    return df 
```

### Alternative Solutions

The package [`anonymizedf`](https://pypi.org/project/anonymizedf/) does a similar job but is not integrated.

**Comment by MarcoGorelli** [comment]
Thanks for the suggestion, but the pandas API is already huge and the bar for adding new methods is quite high, and am not sure this meets it - closing for now then. The external package linked seems fine

**Comment by attack68** [comment]
I think what you are describing is the exact usecase for `DataFrame.apply`. That is a generic method that allows you to apply a function, i.e. mapping of a column value to another value.

The level of specificity that you are suggesting here is just to high. On going maintenance costs of this kind of development is too expensive.

Furthemore, the next coder that comes along will want to customise this function for his precise anonymise requirements, which may have different parameters to yours, so it becomes further unsustainable. `apply` is enough IMO.
