### ISSUE TITLE
ENH: Adding back lookup or value setting by indices

### ISSUE THREAD

**Issue by jasperhyp** [pandas-dev/pandas#47992]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

As [this](https://stackoverflow.com/questions/12100497/pandas-set-values-with-row-col-indices/73263079#73263079) discussion shows, there are use cases where we want specific loadings indexed by (row, col) pairs to be set to specific values.  Unlike using `.loc`, indexing a group of columns and a group of rows of the same length would return only the values at corresponding positions.

### Feature Description

This shouldn't be difficult...

### Alternative Solutions

In `numpy` or `pytorch` or any numerical packages this is the default.

**Comment by jreback** [comment]
pls look at prior discussions 
this is not a very common or useful operation in pandas

**Comment by jasperhyp** [comment]
> pls look at prior discussions this is not a very common or useful operation in pandas

Hi Jeff,  Thanks for the pointers.  I checked the previous discussions and I think there are some people requesting this functionality of `lookup` and the main reason for deprecation is more on the performance side.  My feature request arises more out of the need to **set values** for specific loadings indexed by (row, col) pairs rather than just looking them up, which I agree can be easily done by the current `factorize` functionality.  But setting values is a more delicate thing and would require mapping back and forth the columns & indices if doing manually by first transforming to NumPy then transform back.  Having a wrapper Pandas-native functionality around would be extremely helpful.
