### ISSUE TITLE
QST:  to_perioddelta

### ISSUE THREAD

**Issue by Leohanhart** [pandas-dev/pandas#48001]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

There is not. 

### Question about pandas

Dear development team, 

I make a lot of use of the function df.index.to_perioddelta("Y"/"M") to create seasonal data. 
Now i receive an warning: __main__:1: Future Warning: to_perioddelta is deprecated and will be removed in a future version.  Use `dtindex - dtindex.to_period(freq).to_timestamp()` instead. 

This function is NOT the same, there is NO function in to_periode that creates an index like that. There is no documentation of this feature so it probably doesnt exsits.
So please do not remove this function, don't do this, this is not adding any value in any way and it makes my life way harder. Or if so, please show me an alternative with the example above and a link where I can find this because it doesnt exists.

**Comment by jreback** [comment]
@Leohanhart please be respectful, constructive criticism is always welcome. see the https://github.com/pandas-dev/.github/blob/master/CODE_OF_CONDUCT.md

pandas is an all volunteer project.

**Comment by pratyushsharan** [comment]
Can you please provide with an example of what is broken?

**Comment by phofl** [comment]
Closing, please ping to reopen if you can adress questions

**Comment by Leohanhart** [comment]
I'm on holiday right now. I come back later. Please don't remove this
function.

Op zo 7 aug. 2022 18:21 schreef Jeff Reback ***@***.***>:
