### ISSUE TITLE
DOC: Mention styler in the to_excel documentation

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#48019]
xref #47525

In our [DataFrame.to_excel](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_excel.html) documentation we don't have any mention to [Styler.to_excel](https://pandas.pydata.org/docs/reference/api/pandas.io.formats.style.Styler.to_excel.html?highlight=to_excel#pandas.io.formats.style.Styler.to_excel) which is very relevant.

Users checking the documentation on how to export a `DataFrame` to Excel should be aware that they can use the `Styler` to format the exported file. Personally I'd add the class to `See Also`, and I'd add a very short example at the end of our examples, with a link to the `Styler.to_excel` page. I think that would be good for users who may be interested in that feature. But other ideas also welcome.

**Comment by rhshadrach** [comment]
I'm +1 on See Also and even an explicit note on when the Styler should be used (no surprise: adding styles to Excel output), but I don't think we should have examples of method A in the API docs of method B, even if they are closely related.

**Comment by Nikhil-Mudgal** [comment]
Hi is there anyway in which I can help with docs creation. I am new to open source and want to get started with a good beginner issue.

**Comment by datapythonista** [comment]
This is a quite simple issue to work on if you're new to contributing. Not much work to do here, so you can focus on learning. You should check the contributing section in the docs to know where to start.

**Comment by Nikhil-Mudgal** [comment]
Ok thanks @datapythonista.

**Comment by FrnRmn** [comment]
Hello there! I was trying to set everything up to try to give my first contribution as well but come here too late :)
Can I still ask if I was in the right direction with the current issue? Just for practice.
<details>
  <summary>In case Nikhil-Mudgal doesn't want to read</summary>

Is it all about modifying a single line of the to_excel() docstring in the generic.py file?

![image](https://user-images.githubusercontent.com/86249255/184505783-02a6e351-a43d-46b1-99fe-bca7d2c0dd4d.png)
This is what I see when I build the doc function with Sphinx. However, hyperlinks are not working there. Is it normal or I am not considering something else? 

ps: yep, forgot a space
   
</details>

**Comment by rhshadrach** [comment]
@FrnRmn - you're definitely on the right track here! The links should work, and for this issue we want to mention `Styler.to_excel` and not just `Styler`.

**Comment by FrnRmn** [comment]
Thank you for the feedback.
When you say "the links should work" do you mean all the links that were already there?
For example in the [DataFrame.to_latex ](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_latex.html) See Also section the _Styler.to_latex_ element has not an internal reference link. Is it normal or there is a problem also in this other doc?

**Comment by datapythonista** [comment]
Thanks for the heads up @FrnRmn. It's not expected that the `Styler.to_latex` link in https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_latex.html is broken. Do you mind creating an issue for it please? Links should work in the changes you did, and feel free to open a PR when you've got them ready.

**Comment by FrnRmn** [comment]
#48089 I hope this is done correctly

**Comment by samrao1997** [comment]
@FrnRmn Hey fixed #48089, I can do this issue too if you would like?

**Comment by FrnRmn** [comment]
@samrao1997 Hi, I have just seen your solution. I'll try your way and if I can't make it I'll tell you. Thanks
