### ISSUE TITLE
WEB: Standardize website/docs footer

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#48012]
At the moment we've got different footer notes for the website and the docs, and we're discussing adding our hosting sponsor there. Probably worth agreeing what footer we want to use, and standardize it all over.

**Current website footer:**

pandas is a fiscally sponsored project of [NumFOCUS.](https://numfocus.org/)

**Current docs footer:**

© Copyright 2008-2022, the pandas development team.
Created using [Sphinx](http://sphinx-doc.org/) 4.5.0.

**Proposal:**

© 2022 [NumFOCUS, Inc](https://numfocus.org/). Hosted by [OVH Cloud](https://us.ovhcloud.com/)

Personally I think this is as concise as possible, with the relevant information. For what I read, since many years it's not really required to have the copyright note in websites. But some sources still recommend it. While many projects use something like `Copyright 2022, the pandas team`, seems that doesn't make much sense from a legal point of view, as the pandas team is not an organization, and the copyright claim in this case is from NumFOCUS. I think it's nice to have them in the footer anyway.

Any better idea?

**Comment by mroeschke** [comment]
Maybe `© 2022 pandas development team via NumFOCUS, Inc. Hosted by OVH Cloud`?  IMO from a optics, non-legal, standpoint, just having NumFOCUS sounds like the project is owned by them.

Also for the docs footer, I think it would still be good to keep the Sphinx reference.

**Comment by datapythonista** [comment]
Fine with me too. But my preference would be to then use `pandas via NumFOCUS, Inc`. Same idea, but I think it's nice to have something shorter that a first sight seems like a simple copyright note more than something that seems like a full sentence. Maybe just a personal preference, but seems like it may add noise and distract.

**Comment by mroeschke** [comment]
Sure `pandas via NumFOCUS` sounds good as well.

**Comment by phofl** [comment]
Sounds good to me too

**Comment by FrnRmn** [comment]
Hello! I have updated the web footer as:

© 2022 pandas via [NumFOCUS.](https://numfocus.org/)

However, I can only partially update the docs footer as:

© Copyright 2022 pandas via NumFOCUS.
Created using [Sphinx](http://sphinx-doc.org/) 4.5.0.

I'm still trying to understand how to change the latter (quite inexperienced yet).
Should I PR only with the web footer changes, or is it better to wait for someone who performs both changes in one PR?

**Comment by datapythonista** [comment]
Feel free to update the website footer first if you want. We should be signing the agreement for the hosting with OVH very soon, and when it's signed we should also update the OVH part to the footer.

**Comment by partev** [comment]
Given that copyright notice is no longer required I think the footer would look better and more consice without it.
How about:

Sponsored by [NumFOCUS.](https://numfocus.org/) Hosted by [OVH Cloud.](https://us.ovhcloud.com/)
