### ISSUE TITLE
DEP: Add pip to environment.yml

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#48026]
I recreated my local dev environment with

    mamba env create -f environment.yml

and got the message

> Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.

I'm using mamba 0.24.0 and conda 4.13.0.

**Comment by MarcoGorelli** [comment]
same here, would be good to explicitly list it

**Comment by miguelcsilva** [comment]
Hey, I'm new to open source but would love to start contributing. Would this issue be ready for me to try and take it?

**Comment by MarcoGorelli** [comment]
go ahead thanks

**Comment by miguelcsilva** [comment]
take

**Comment by samrao1997** [comment]
@miguelcsilva are you still doing this one? otherwise can I take it?

**Comment by miguelcsilva** [comment]
Please take. I don't think I'll be able to contribute unfortunately, as trying to install mamba with conda resulted on missing DLLs error, and trying to install the requirements with conda itself resulted in conda spending over 6 hours on "Solving environment" until I cancelled it.
I'll unassign myself so you can take it.

**Comment by ambujpawar** [comment]
@samrao1997 I have never contributed to opensource. Can I please take it?

**Comment by samrao1997** [comment]
I haven't started work on it yet, so @ambujpawar go for it!

**Comment by ambujpawar** [comment]
take
