### ISSUE TITLE
Adding obvious type hints to pandas

### ISSUE THREAD

**Issue by pepelovesvim** [pandas-dev/pandas#48068]
For us that uses static type checkers religiously, it doesn't hurt to add type hints for parameters that are obvious
For example:

https://github.com/pandas-dev/pandas/blob/2f8d0a36703e81e4dca52ca9fe4f58c910c1b304/pandas/io/sql.py#L438

We can add `sql: str` without impacting anything. What does the community think? I can submit pull requests as I'm discovering them while using pandas.

**Comment by twoertwein** [comment]
> We can add `sql: str` without impacting anything. What does the community think? I can submit pull requests as I'm discovering them while using pandas.

You are welcome to add type annotations here (and also at [pandas-stubs](https://github.com/pandas-dev/pandas-stubs/))! About `sql` in `read_sql`, the documentation says `str or SQLAlchemy Selectable`.

**Comment by mroeschke** [comment]
Agreed, pull requests to generally add correct annotations are welcome. Since this issue is rather broad about typing closing.
