### ISSUE TITLE
ENH: Move column levels in multi column index to another position

### ISSUE THREAD

**Issue by andreas-vester** [pandas-dev/pandas#48079]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I am looking for a way to move a certain level within a multi column index to another position.

Let's say I have the following dataframe:

    unknown_level_name_0     a1            
    unknown_level_name_1     b1      b2    
    known_level_name         x1      x1    
    unknown_level_name_last  c1  c1  c1  c1
    0                        37  34  97  19
    1                        54  47  53  46
    2                        63  94  14  85
    3                        16  51  27  96
    4                        32  64  76  26

Usually, I would try to use ``reorder_levels`` or ``swaplevels``, however, this is not possible or at least somewhat complicated if you don't know the exact index position of the level that you want to move. The only thing you know is the name of the index level.

Let's assume, the desired outcome is to move the ``known_level_name`` to the very top. The result should then look like this:

    known_level_name         x1      x1    
    unknown_level_name_0     a1            
    unknown_level_name_1     b1      b2    
    unknown_level_name_last  c1  c1  c1  c1
    0                        37  34  97  19
    1                        54  47  53  46
    2                        63  94  14  85
    3                        16  51  27  96
    4                        32  64  76  26

### Feature Description

Right now, I am using the following function to solve this problem:

```
def move_level(df: pd.DataFrame, column_level: Union[str, int], new_pos: int=0) -> pd.DataFrame:
    """
    Moves column level to new position.

    Parameters
    ---------------
    df
        DataFrame with multi-column index
    column_level
        Column level to be moved.
    new_pos
        New column index level position.

    Returns
    -----------
    pd.DataFrame
        DataFrame with reordered multi column index.

    Raises
    ---------
    IndexError
        IndexError will be raised if `column_level` doesn't exist.

    """
    if column_level in df.columns.names:
        idx = df.columns.names.index(column_level)
    elif isinstance(column_level, int) and -len(df.columns.names) <= column_level < len(df.columns.names):
        idx = column_level
    else:
        raise IndexError(f"Invalid index '{column_level}'")

    order = list(range(len(df.columns.names)))

    # translate new_pos just in case it is a negative index
    new_pos = order.index(order[new_pos])

    # remove list element
    order.pop(idx)

    # insert list element to new position
    order.insert(new_pos, idx)

    # finally, sort multi column index according to 'order' and return
    return df.reorder_levels(order=order, axis=1)
```

### Alternative Solutions

I raised this question at https://stackoverflow.com/questions/71514091/move-column-level-to-top-in-multi-column-index-pandas-dataframe.

**Comment by attack68** [comment]
```python
>>> midx = pd.MultiIndex.from_arrays([[0, 0, 1, 1], [1, 2, 3, 4], [8, 9, 8, 9]], names=["a", "b", "c"])
>>> df = pd.DataFrame(data=[[1,2,3,4],[5,6,7,8]], columns=midx)
>>> df
Out[8]: 
a  0     1   
b  1  2  3  4
c  8  9  8  9
0  1  2  3  4
1  5  6  7  8

>>> df2 = df.stack([0,1,2]).unstack([3,1,2])
>>> df2
Out[12]: 
c    8    9    8    9
a    0    0    1    1
b    1    2    3    4
0  1.0  2.0  3.0  4.0
1  5.0  6.0  7.0  8.0

>>> df2.sort_index(axis=1)
c    8         9     
a    0    1    0    1
b    1    3    2    4
0  1.0  3.0  2.0  4.0
1  5.0  7.0  6.0  8.0
```

**Comment by attack68** [comment]
Alternatively

```python
>>> midx2 = pd.MultiIndex.from_arrays([
    midx.get_level_values(level=2), midx.get_level_values(level=1), midx.get_level_values(level=0)
])
>>> df.columns = midx2
>>> df
c  8  9  8  9
b  1  2  3  4
a  0  0  1  1
0  1  2  3  4
1  5  6  7  8

>>> df.sort_index(axis=1)
c  8     9   
b  1  3  2  4
a  0  1  0  1
0  1  3  2  4
1  5  7  6  8
```

**Comment by attack68** [comment]
And you mentioned `reorder_index`. SInce you know the names of the index what is wrong with:
```python
>>> df.reorder_levels(["c", "a", "b"], axis=1)
c  8  9  8  9
a  0  0  1  1
b  1  2  3  4
0  1  2  3  4
1  5  6  7  8
```

**Comment by andreas-vester** [comment]
@attack68 Thank you for these examples. However, I don't think they are a suitable solution. Why? - 
1. Using ``unstack`` or ``get_level_values`` requires you to know all level names. I do have a particular coding issue where I only know one level name for granted. All other level names will be determined dynamically.
2. Applying ``reorder_levels`` does work for the case where you want to move the known level to the very top (or to the very bottom), however, it doesen't work so easily if you want to move your index level to, let's say, the second position (or second last, etc.).
3. All the suggestions aren't that intuitive, in my view. Using the function, I outlined above, I can simply do the following:
`move_level(df=df, column_level="know_level", new_pos=2)`
I think this is pretty intuitive, don't you think so?

When implementing this feature request, an even better call would be:
`df.move_level(column_level="know_level", new_pos=2)`

**Comment by attack68** [comment]
Your 
`df.move_level(column_level="known_level", new_pos=2)`, 
is syntactically equivalent to the three liner,
```
reorder_ = [n for n in df.columns.names if n != "known_level"]
reorder_.insert(new_pos, "known_level")
df.reorder_levels(reorder_, axis=1)
```

in response to 2) I think this is the intended use of `reorder_levels`. And I think list comprehensions and composition are probably a fundamental skill of any python user using pandas.

in response to 3) I don't like it because there is a cost to every function that is added to the API. It requires maintenance, tests and documentation pages, making it harder for a user to know which is the best way to achieve their end result with a larger variety of options available. 

I'm -1 on adding any API for this, when the above performs the task, and a user already a has a variety of methods available depending on the precise circumstance, but thank you for floating the idea and provoking discussion

**Comment by MarcoGorelli** [comment]
agreed - let's close then, but thanks for the well-written suggestion!
