### ISSUE TITLE
BUG: subclassing `CustomBusinessDay` returns init error

### ISSUE THREAD

**Issue by attack68** [pandas-dev/pandas#48074]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
from pandas.tseries.holiday import AbstractHolidayCalendar, Holiday
from pandas.tseries.offsets import CustomBusinessDay

rules = [Holiday("MyHol", month=1, day=3)]
cal = CustomBusinessDay(calendar=AbstractHolidayCalendar(rules=rules))
print(cal.rollforward("2022-01-03"))
# 2022-01-04 00:00:00

class MyCal(CustomBusinessDay):
    def __init__(self, rules):
        super().__init__(calendar=AbstractHolidayCalendar(rules=rules))

cal = MyCal(rules=rules)
print(cal.rollforward("2022-01-03"))
# TypeError: __init__() got an unexpected keyword argument 'normalize'
```

### Issue Description

If I create a `CustomBusinessDay` calendar I can roll it forward without issue.

If I subclass it and initialise as, I perceive to be, the same structure it returns a `TypeError`.

### Expected Behavior

I expect the two construction routines to be identical.

### Installed Versions

<details>

pandas           : 1.5.0.dev0+1283.g03b4095f9d

</details>

**Comment by dizhouwu** [comment]
take taking a look

**Comment by dizhouwu** [comment]
Providing some triage: At line 640 https://github.com/pandas-dev/pandas/blob/v1.5.0.dev0/pandas/_libs/tslibs/offsets.pyx#L640, 
```
        if not self.is_on_offset(dt):
            dt = dt + type(self)(1, normalize=self.normalize, **self.kwds)
```
type(self) returns MyCal. MyCal does not have normalize as an argument in its __init__. I am new to this space and not sure this is a bug which needs addressing.

**Comment by attack68** [comment]
my point being the original construction works without any normalize argument. And if im invoking super() without normalize which I have shown to work in its own construction shouldn't this then work when subclassing?

**Comment by dizhouwu** [comment]
@attack68 subclass changes the MRO. Use print(MyCal.__mro__) to see that it's MyCal comes before any other class. So it's __init__ will be used. The below works perfectly:
```
class MyCal(CustomBusinessDay):
    pass

cal = MyCal()
print(MyCal.__mro__)
print(cal.rollforward("2022-03-01"))

```

**Comment by attack68** [comment]
Isn't the return of (sorry dont have a console) the second `print` when '2022-01-03'  is used not the same as my original use case, i.e. it wont roll to '2022-01-04'. The point of the subclass was to add specific holidays in the initialisation, and i would add instance and possible static methods to the class, but I cant currently do that.

**Comment by dizhouwu** [comment]
```
from pandas.tseries.holiday import AbstractHolidayCalendar, Holiday
from pandas.tseries.offsets import CustomBusinessDay

rules = [Holiday("MyHol", month=1, day=3)]

class MyCal(CustomBusinessDay):
    def __init__(self, *args, **kwargs):
        rules = kwargs.get("rules")
        super().__init__(calendar=AbstractHolidayCalendar(rules=rules))

cal = MyCal(rules=rules)
print(cal.rollforward("2022-01-03"))
```
This can get to '2022-01-04'.

**Comment by attack68** [comment]
yes, of course! excellent solution, many thanks.

**Comment by attack68** [comment]
Seems I spoke too soon.

Whilst the above works for `rollforward`, `rollback` also returns "2022-01-04".

Whereas if we do 
```
rules = [Holiday("MyHol", month=1, day=3)]
cal = CustomBusinessDay(calendar=AbstractHolidayCalendar(rules=rules))
print(cal.rollforward("2022-01-03"))
print(cal.rollback("2022-01-03"))
```
we get 
```
2022-01-04
2021-12-31
```

A bit weird.

**Comment by dizhouwu** [comment]
yea you are right. At this point, I want to encourage you to reconsider subclass CustomBusinessDay and try to use composition over inheritance. Otherwise, this will not be the last time you run into issues like this. Do you think pivoting to solving what you cannot achieve without subclassing make more sense here?

**Comment by attack68** [comment]
Yes I've already made the switch. I'm more used to subclassing, but here its just not worth it. Thanks for the help.
