### ISSUE TITLE
ENH: alleviate issues with inconsistent multi-level joining on a 0-column merge table

### ISSUE THREAD

**Issue by prhbrt** [pandas-dev/pandas#48084]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

    FutureWarning: merging between different levels is deprecated and will be removed in a future version. (`some number` levels on the left, 1 on the right)

When running:

    multilevel_columns = pd.DataFrame({('a', 'b'): np.random.randint(0,100, 10)})
    multilevel_columns.index.name = 'alpha'

    relations = pd.DataFrame({
        'alpha': np.random.randint(0,10, 10),
        'beta': np.random.randint(0,10, 10)
    }).set_index(['alpha', 'beta'])

    multilevel_columns.join(relations)

because the 0-column merge table `relations` only has 1 column-level, whereas `multilevel_columns` has two. However, it's irrelevant because `relations` has 0 columns anyway, and so concatenating them should be trivial.

### Feature Description

Allow merging inconsistent levels if one frame has 0 columns.

### Alternative Solutions

Change [this check](https://github.com/pandas-dev/pandas/blob/c8fc47ba714f9ac181905f4d9674b4a43772e833/pandas/core/reshape/merge.py#L665) with the added condition `and len(_left.columns) > 0 and len(_right.columns) > 0`

**Comment by phofl** [comment]
Hi, thanks for your report. I am -1 on this, we should avoid value dependent behavior. What are you trying to do here?

**Comment by mroeschke** [comment]
Thanks for the request but it appears there hasn't been much interest in this issue from the core team and community over the years so closing.
