### ISSUE TITLE
DOC: `is_float_dtype` meant to be an internal function??

### ISSUE THREAD

**Issue by MRyderOC** [pandas-dev/pandas#48101]
Seems like there is no function for public API to check the dtype of an array-like object. Either the documentation needs to be changed or a public function should be provided and treat this one as an internal one by adding underscore at the beginning of it.

P.S. To keep the consistency between "int" and "float" dtype functions, it's better to add another function like `is_float64_dtype` and keep the current one and triage the documentation.

https://github.com/pandas-dev/pandas/blob/e8093ba372f9adfe79439d90fe74b0b5b6dea9d6/pandas/core/dtypes/common.py#L1244

**Comment by mroeschke** [comment]
pandas documents that accessing anything in `core` is essentially private: https://pandas.pydata.org/pandas-docs/stable/reference/index.html

Depending on your use case, this function may work for you https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.api.types.is_float.html

**Comment by MRyderOC** [comment]
[API reference](https://pandas.pydata.org/pandas-docs/stable/reference/index.html) states that:

> `pandas.api.types` subpackage holds some public functions related to data types in pandas.

[pandas.api.types.is_float](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.api.types.is_float.html) is for checking a single object no the array-like objects. `is_float_dtype` is a function like [pandas.api.types.is_integer_dtype](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.api.types.is_integer_dtype.html).

**Comment by mroeschke** [comment]
Ah yes thanks for the correction. Yes then https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.api.types.is_float_dtype.html is meant to be a public function.

I guess since https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.api.types.is_int64_dtype.html is also public then `is_float64_type` should also be public too

**Comment by MRyderOC** [comment]
Just for clarification:
`pandas.api.types.is_integer_dtype` exists (for any int type)
`pandas.api.types.is_int64_dtype` exists (for int64 type)
`pandas.api.types.is_float_dtype` exists (for any float type) **have docs problem**
`pandas.api.types.is_float64_dtype` does **_NOT_** exist.

We can change this issue to an enhancement one and I'm pleased to take care of both the documentation and the new function.

**Comment by MRyderOC** [comment]
@mroeschke any updates on this?
Should we just clean the docs or should we implement the `is_float64_dtype`?

**Comment by phofl** [comment]
@MRyderOC Could you open a dedicated issue, if you think having a function ``if_float64_dtype`` is necessary/a good idea? Also adding a use case where this is helpful would be great. ``float32`` is not very well supported within pandas, this might be a reason why the function does not exist.
