### ISSUE TITLE
DOC: Deprecation of level keyword

### ISSUE THREAD

**Issue by amotzop** [pandas-dev/pandas#48162]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.all.html
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.any.html
https://pandas.pydata.org/docs/reference/api/pandas.Series.all.html
https://pandas.pydata.org/docs/reference/api/pandas.Series.any.html

### Documentation problem

It seems that the `level` keyword in the `all/any` methods of `Series/Dataframe` are deprecated (using them raises a `FutureWarning`), but don't appear to be deprecated in the documentation.

### Suggested fix for documentation

Add a deprecation warning comment for the `level` keyword in the relevant documentation.

**Comment by phofl** [comment]
They are missing everywhere. Thanks for pointing this out
