### ISSUE TITLE
CI: Circleci timing out regularly

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#48179]
We are pretty close to the 60min job limit right now. Jobs are timing out regularly.

Do we know how our plan with them is structured? We could update to Large, but this would cost 20 credits per minute instead of 10. I'll open a pr as doc to check, how this would speed up the ci

cc @pandas-dev/pandas-core

**Comment by phofl** [comment]
Job ran in 35 minutes instead of close to 60, so depending on our limits, switching might be worth it

**Comment by mroeschke** [comment]
Maybe @jreback or @lithomas1 know about the CircleCI plan?

**Comment by phofl** [comment]
Closing for now, pr was merged
