### ISSUE TITLE
BUG: pandas.read_csv does not parse CSV with missing values in a sane way

### ISSUE THREAD

**Issue by Ark-kun** [pandas-dev/pandas#48175]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
df3 = pandas.read_csv(
    io.StringIO("""int_col,float_col,str_col,bool_col
,,
1234567890123456789,3.14,aaa,True
"""))
print(df3)
print(df3.dtypes)
```
```
        int_col  float_col str_col bool_col
0           NaN        NaN     NaN      NaN
1  1.234568e+18       3.14     aaa     True
int_col      float64
float_col    float64
str_col       object
bool_col      object
dtype: object
```

### Issue Description

My code needs to parse and do simple operations with user-provided CSV files. Before reading the files, the code does not know the column names or their types.

The column types are: integer, float, string. Columns might have missing values.

I expect that `pandas.read_csv` uses the correct types when loading the CSV files: `Int64` for integer columns, `float64` for float columns, `string` for string columns.

Instead, `pandas.read_csv` uses `float64` for integer columns (corrupting some values) and `object` for string and boolean columns.

### Expected Behavior

Expected:
```
               int_col  float_col str_col  bool_col
0                 <NA>        NaN    <NA>      <NA>
1  1234567890123456789       3.14     aaa      True
int_col        Int64
float_col    float64
str_col       string
bool_col     boolean
```

Actual:
```
        int_col  float_col str_col bool_col
0           NaN        NaN     NaN      NaN
1  1.234568e+18       3.14     aaa     True
int_col      float64
float_col    float64
str_col       object
bool_col      object
dtype: object
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : f2ca0a2665b2d169c97de87b8e778dbed86aea07
python           : 3.7.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.0-10-cloud-amd64
Version          : #1 SMP Debian 4.19.132-1 (2020-07-24)
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.1
numpy            : 1.21.6
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 22.1.2
setuptools       : 49.6.0.post20200814
Cython           : 0.29.21
pytest           : 6.0.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.3
lxml.etree       : 4.5.2
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.17.0
pandas_datareader: None
bs4              : 4.9.1
bottleneck       : 1.3.2
fsspec           : 0.8.0
fastparquet      : None
gcsfs            : 0.7.0
matplotlib       : 3.3.1
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : 9.0.0
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.19
tables           : 3.6.1
tabulate         : 0.8.7
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.49.1

</details>

**Comment by phofl** [comment]
see #48173

**Comment by Ark-kun** [comment]
@phofl The issue you've linked is about `pandas.NA` vs `float.NaN`. I do not quite care about that as a user or a developer. This issue is about `read_csv` using incorrect types and mangling the data. It also does not round-trip in a sane way.

**Comment by phofl** [comment]
All your three issues are about the same topic. I’ve linked another issue there that explains you why this does not happen.

Feel free to open a pr and implement nullable dtypes for read_csv
