### ISSUE TITLE
Feature Request: regex for drop

### ISSUE THREAD

**Issue by jseabold** [pandas-dev/pandas#4818]
Don't have time to implement this, but I wanted to float the idea and park it. It's pretty trivial and you can achieve the same thing with filter, but it might be nice if drop had a regex keyword. E.g., these would be equivalent

```
df = df.filter(regex="^(?!var_start)")
df = df.drop(regex="^var_start", axis=1)
```

**Comment by tik0** [comment]
I just want to leave a simple one-liner (almost, if on emerges everything together) here, how one could do this. Drop all columns starting with "enc_":
```
import pandas as pd
import re
d = {'enc_1': [1, 2], 'enc_2': [3, 4], 'dec_2': [3, 4]}
df = pd.DataFrame(data=d)
regex = r'enc_.*'
matches = [match[0] for match in [re.findall( regex, col) for col in df.columns] if len(match)]
df.drop(matches, axis=1)
```

**Comment by WillAyd** [comment]
@tik0 you can use a regex to do that. Something like:

```python
df.filter(regex=r'^(?!enc_)')
```

@jreback this is a pretty old issue but I think it's duplicative of what's available already in filter. Any reason to keep this one open?

**Comment by MarcoGorelli** [comment]
closing as there hasn't been any uptake here (and I agree with the assessment that `df.filter(regex=r'^(?!enc_)')` is simple enough), though please do ping if you have use-case where that isn't practical
