### ISSUE TITLE
ENH: filter improvement

### ISSUE THREAD

**Issue by bibinvargheset** [pandas-dev/pandas#48192]
### Feature Type

- [X] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

pandas filtering with column names as kwargs and values 

``def df_filter(df, **kwargs):
    query_list = []
    for key, value in kwargs.items():
        if value is not None:
            query_list.append(f"{key}==@kwargs['{str(key)}']")
    query = ' & '.join(query_list)
    return df.query(query)

``

### Feature Description

pandas filtering with column names as kwargs and values 

### Alternative Solutions

```
def df_filter(df, **kwargs):
    query_list = []
    for key, value in kwargs.items():
        if value is not None:
            query_list.append(f"{key}==@kwargs['{str(key)}']")
    query = ' & '.join(query_list)
    return df.query(query)

```

**Comment by jreback** [comment]
-1 on any expansion of .query

**Comment by mroeschke** [comment]
Agreed, this this code looks small enough that it could be written as needed by the user. Thanks for the suggestion but closing.
