### ISSUE TITLE
ENH: 

### ISSUE THREAD

**Issue by goeb86** [pandas-dev/pandas#48206]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I'll preface this by stating that I'm not sure if this feature is really needed, or if it just adds unneeded complexity, but, the solution seems like it would be simple, and, it would be interesting to see if there was any support for it.

I was wondering if Pandas would be able to add functionality for Pandas to auto detect between csv and an Excel file so that we wouldn't have to add conditions to deal with both file types. This can be very valuable for users who get files in multiple formats but still plan on using the same arguments for each file type (csv/Excel files are a prime example, as at work, I can get data sources from either and cannot control whether the file type is consistent). 

For instance, it isn't too uncommon get file types from outside sources that could be either a csv or an Excel spreadsheet file. This would typically results in this type of function being needed:

```
def read_csv_or_excel (file_path: ntpath.Path, header=header, index_col):
    file_ext = ntpath.splitext(file_path)[1]
    if file_ext[:3] == 'xls':
        df = pd.read_excel(file_path, header=header, index_col=index_col)
    else:
        df = pd.read_csv(file_path, header=header, index_col=index_col)
    return df
```

In order to avoid creating such functionality that is somewhat duplicated (I know, it isn't a duplicate, but still, it is pretty close), I wish Pandas would be able to determine the file type by just splitting the file path and determining the extension. A '.csv' is assumed to be a 'csv', and a '.xls' or '.xlsx' is an Excel file. Based on the file extension, Pandas can determine whether to use the read_csv function, or, the read_excel function.

### Feature Description

I'm not sure of the best way to implement it but I think the example code I have shown above could work, with the same function name, but, obviously it would only keep common arguments.

The difficult part here, is that not ALL the parameters for read_excel and read_csv are the same. Which arguments are offered would have to be TBD. I am thinking this should be for more straightforward read-ins of both file types (again, we can discuss what 'straightforward' is if this request gets any traction)

### Alternative Solutions

I am sure there are alternatives, but, the one I suggested is a good and simplistic start. I'll be the first to admit that my OOP skills  are lacking.

**Comment by attack68** [comment]
-1. I think it would be better if pandas just focuses on the core functions and not adding this functionality which is really a user manipulation. 

Go one step further and suggest, why do you stop at the csv vs excel level, why not `read_data` that tries to detect between csv, json, html, excel, sas, etc.

But I think it would certainly be useful to add your example to the documentation or a cookbook to show how this is best implmented.

**Comment by goeb86** [comment]
> -1. I think it would be better if pandas just focuses on the core functions and not adding this functionality which is really a user manipulation.
> 
> Go one step further and suggest, why do you stop at the csv vs excel level, why not `read_data` that tries to detect between csv, json, html, excel, sas, etc.
> 
> But I think it would certainly be useful to add your example to the documentation or a cookbook to show how this is best implemented.

I'm in agreement with that. I am going to refine this code block and see how I can add it to the cookbook.

Thanks!
