### ISSUE TITLE
DOC: wrong question marks in tutorial

### ISSUE THREAD

**Issue by keithbriggs** [pandas-dev/pandas#48227]
At https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html, things like

`How to create plots in pandas `

are not questions, so should not have a question mark.

(If it was "How do I create plots in pandas?", then it is a question, of course.)

**Comment by samrao1997** [comment]
take

**Comment by Sohlar** [comment]
Would you rather have periods or no punctuation?

**Comment by keithbriggs** [comment]
They are headings so they don't need punctuation.

**Comment by samrao1997** [comment]
Made PR and ready for review. I essentially just got rid of the question marks in the headings of those files.

**Comment by keithbriggs** [comment]
~~LGBT~~ -  sorry,  LGTM.
