### ISSUE TITLE
BUG: Nullable int floordiv 0 result changed from 0 to inf

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#48223]
```
>>> import pandas as pd
>>> pd.__version__
'1.4.3'
>>> 1 // pd.Series([0], dtype='Int64')
0    0
dtype: Int64
```

vs

```
In [1]: pd.__version__
Out[1]: '1.6.0.dev0'  # essentially 1.5

In [2]: 1 // pd.Series([0], dtype='Int64')
Out[2]:
0    inf
dtype: Float64
```

Ran a bisect and found this was the commit that caused the change

```
57d7768c205d30cc50ba9b42d60d24d1e32eb249 is the first bad commit
commit 57d7768c205d30cc50ba9b42d60d24d1e32eb249
Author: jbrockmendel <jbrockmendel@gmail.com>
Date:   Thu Jan 27 16:33:24 2022 -0800

    BUG: NumericArray * td64_array (#45622)
```

While personally I think `inf` is a more sensible result than `0`, appears this was still being actively discussed in https://github.com/pandas-dev/pandas/issues/30188

**Comment by mroeschke** [comment]
Appears this was further refactored in https://github.com/pandas-dev/pandas/pull/45849 cc @jbrockmendel

**Comment by jbrockmendel** [comment]
The old behavior was the bug.

Should add tests for "masked behavior when there are no NAs matches non-masked behavior"
