### ISSUE TITLE
BUG: 0 = 0 not -0

### ISSUE THREAD

**Issue by flywire** [pandas-dev/pandas#48222]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
>>> import pandas as pd
>>> pd
<module 'pandas' from 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pandas\\__init__.py'>
>>> pd.__version__
'1.4.3'
>>> pd.Series([1,None,0])*-1
0   -1.0
1    NaN
2   -0.0
dtype: float64
>>>
```

### Issue Description

0 is being returned with a negative sign ie -0.0

### Expected Behavior

There should be no negative on zero ie 0 * -1 = 0

### Installed Versions

>>> pd.__version__
'1.4.3'

**Comment by sappersapper** [comment]
Without tracing the code, to my understanding, 
1) `None * -1` is invalid, so pandas converts `None` to `NaN`
2) `NaN` is float, so `pd.Series([1,None,0])` is converted to float: `pd.Series([1.0,NaN,0.0])`
3) `0.0 * -1` results to `-0.0`

**Comment by flywire** [comment]
```py
>>> pd.Series([1,0])*-1
0   -1
1    0
dtype: int64
```

> 3\. (there is a sign bit in a float number)

Maybe so but Pandas should respect there is no such thing as `-0.0`. Zero is neither positive nor negative so it's not suitable for public presentation.

**Comment by mroeschke** [comment]
This behavior mimics numpy

```
In [4]: np.array([1.0, np.nan, 0.0]) * -1
Out[4]: array([-1., nan, -0.])
```

Generally, -0 is defined by IEEE and essentially acts like 0/+0. https://stackoverflow.com/a/4083431

Nonetheless, if this behavior was undesirable, it would need to be fixed in numpy/CPython so closing as a potential upstream issue.

**Comment by flywire** [comment]
> it would need to be fixed in numpy/CPython

Not `https://github.com/numpy/numpy`? I want to raise a bug in the appropriate repo for _Display Arithmetic Zero not Signed Zero_.

**Comment by mroeschke** [comment]
Yes this behavior is in numpy, but I mention CPython because it's part of the core language

```
In [1]: 0.0 * -1.0
Out[1]: -0.0
```

**Comment by flywire** [comment]
> it would need to be fixed in numpy/CPython

https://github.com/numpy/CPython gives 404 error. Which repo are you suggesting?
