### ISSUE TITLE
read_excel parsing dates later than 2262-04-11 pandas.to_datetime cannot convert input with unit 'D'

### ISSUE THREAD

**Issue by petrdanecek** [pandas-dev/pandas#48243]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
works fine:
pandas.to_datetime(132320, unit='D', origin='1899-12-30')
>> Timestamp('2262-04-11 00:00:00')

results in exception:
pandas.to_datetime(132322, unit='D', origin='1899-12-30')
>> *** pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: cannot convert input with unit 'D'
```

### Issue Description

not able to process the xlsb with dates later than 2262-04-11

### Expected Behavior

pandas.to_datetime(132322, unit='D', origin='1899-12-30')

should return valid date

### Installed Versions

<details>

pd.show_versions()
*** NameError: name 'pd' is not defined
(Pdb) pandas.show_versions()

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.10.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.18.0-394.el8.x86_64
Version          : #1 SMP Tue May 31 16:19:11 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.3
numpy            : 1.22.4
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 62.6.0
pip              : 22.2.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.5
html5lib         : None
pymysql          : None
psycopg2         : 2.9.3
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : 1.0.9
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by phofl** [comment]
Hi, thanks for your report. This is a problem with the underlying representation of date times (ns). See https://numpy.org/doc/stable/reference/arrays.datetime.html#datetime-units

This is the maximum that can be represented.

**Comment by mroeschke** [comment]
This is further noted in https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timestamp-limitations

Additionally, this should hopefully change with non-nano support in the works: https://github.com/pandas-dev/pandas/issues/46587. Closing as it overlaps with the above issue
