### ISSUE TITLE
DOC: Pandas plot() function

### ISSUE THREAD

**Issue by vishhy** [pandas-dev/pandas#48247]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.html

### Documentation problem

![image](https://user-images.githubusercontent.com/76154791/186694844-754675e1-0282-454d-802f-aef53e6dd9d1.png)
In the above function call, there is no description for the argument 'alpha' in the official documentation of pandas.

### Suggested fix for documentation

Kindly add the details about that argument and the range of values that it supports.
This is better because, opacity is always a good feature in visualization and new comers won't be able to know that such an argument for reducing the opacity also exists.

**Comment by phofl** [comment]
Hi, thanks for your report. This is a matplotlib specific argument, correct? Plotly does not accept it when specifying the backend. 

In this case this is covered by kwargs in the docs

**Comment by MarcoGorelli** [comment]
Agreed, it says

> **kwargs
> 
>     Options to pass to matplotlib plotting method.
> 

Closing then
