### ISSUE TITLE
DOC:  1.5.0rc0 has issues in the whatsnew document

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#48248]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/version/1.5.0rc0/whatsnew/v1.5.0.html

### Documentation problem

Issues I see:

- Top header says "What's new in 1.5.0 (??)"
- At https://pandas.pydata.org/pandas-docs/version/1.5.0rc0/whatsnew/v1.5.0.html#backwards-incompatible-api-changes there are two subsections labeled `api_breaking_change1` and `api_breaking_change2`  (This seems to be fixed in the dev version of the docs)
- The contributors list at the bottom is empty.

### Suggested fix for documentation

Just need to clean those issues up!

**Comment by simonjayhawkins** [comment]
Thanks @Dr-Irv for opening this issue to keep track of the doc changes outstanding before release.

The release date gets added just before release

tidying the notes is ongoing between now and the release

adding the contributors list is trivial but must be remembered none the less. (I think maybe previously done at same time as adding release date)

It is important that whoever does the release does visually check the release notes just prior to release. (This is included in the pre-release checklist (on the release tracking issue) for the recent releases)

**Comment by mroeschke** [comment]
@jorisvandenbossche I noticed your CoW enhancement hasn't been included in the whatsnew yet. Do you have time to include it in the whatsnew before the 1.5 release or do you need help?
