### ISSUE TITLE
CI: test_round_sanity causing builds to fail

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#48244]
The failure is back. It breaks all of our builds that run this test now.

example:
https://github.com/pandas-dev/pandas/runs/8014709770?check_suite_focus=true

**Comment by simonjayhawkins** [comment]
#48242 is a backport PR and seeing these failures so need to at least milestone 1.5. We have a couple of PRs from @jorisvandenbossche that are ready to merge so if we see the failures on the backport of those can re-milestone 1.4.4

**Comment by mroeschke** [comment]
After we patch this temporarily, we can repurpose https://github.com/pandas-dev/pandas/issues/47823 to track this flaky test.

**Comment by mroeschke** [comment]
Since https://github.com/pandas-dev/pandas/pull/48245 patched over this temporarily, going to close in favor of https://github.com/pandas-dev/pandas/issues/47823
