### ISSUE TITLE
BUG: Memory leak in pd.MultiIndex

### ISSUE THREAD

**Issue by pnjun** [pandas-dev/pandas#48241]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import numpy as np
import pandas as pd

#Len of each trace
trace_len =2500

#Number of Bins
bin_num = 300

# Traces matrix dimensions
L1 = 70
L2 = 100

index = pd.MultiIndex.from_product([range(L1), range(L2)])
traces = np.random.random((L1*L2, trace_len))
traces_df = pd.DataFrame(traces, index=index)

#Lets make 300 random bins
bins = [index.to_frame().sample(frac=1, replace=True) for _ in range(bin_num)]
bins = [pd.MultiIndex.from_frame(bin) for bin in bins]

def bin_single(traces: pd.DataFrame, bin_idx:pd.Index) -> np.array:
    """ Cumulative sum of all shots that are both in traces and bin_idx"""
    bin_idx = bin_idx.intersection(traces.index)
    binned = traces.reindex(bin_idx, copy=False)
    return binned.sum(axis=0, skipna=False).to_numpy()

output = np.empty((bin_num, trace_len))
for n, bin in enumerate(bins):
    output[n] = bin_single(traces_df, bin)
```

### Issue Description

The code in the example produces an increasing memory usage as the final for loop runs. This is the memory allocation over time: [plot](https://i.stack.imgur.com/XFB8I.png).

The allocation increases by more than 200Mb over the 300 iterations, so this cannot be due to lazy allocation of the `output` array, since that is only 6Mb, as reported by `np.nbytes`. 

I suspect the problem might be due to the use of pd.MultiIndex, as changing the indexing of the `traces_df` dataframe solves the problem, as shown in this [question](https://stackoverflow.com/questions/73479358/memory-leak-in-pandas-multiindex-with-minmum-reproducible-example).

Some context:
The goal of the code is to average some number of time-traces into a certain number of bins. The traces are arranged in a matrix using two-level pd.MultiIndex. The snippet creates a random set of traces, generates a number of random bins for those traces, and subsequently iterates over each bin averaging the traces corresponding to that bin using the `bin_single()` function.

### Expected Behavior

Same behavior, but without the increasing memory demand.

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.8.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-1160.36.2.el7.x86_64
Version          : #1 SMP Wed Jul 21 11:57:15 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.3
numpy            : 1.20.3
pytz             : 2021.1
dateutil         : 2.8.2
setuptools       : 52.0.0.post20210125
pip              : 21.2.3
Cython           : 0.29.24
pytest           : 6.2.4
hypothesis       : None
sphinx           : 4.1.2
blosc            : None
feather          : None
xlsxwriter       : 3.0.1
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.26.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
brotli           : 
fastparquet      : None
fsspec           : 2021.07.0
gcsfs            : None
markupsafe       : 2.0.1
matplotlib       : 3.4.2
numba            : 0.53.1
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.2
snappy           : None
sqlalchemy       : 1.4.22
tables           : 3.6.1
tabulate         : None
xarray           : 2022.3.0
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None

</details>

**Comment by phofl** [comment]
Hi, thanks for your report. Can you narrow the reproducer down a bit?

**Comment by pnjun** [comment]
Hey! I will try to narrow it down more, but I have switched to a work around for my main codebase and I will need to do it in the spare time.

**Comment by phofl** [comment]
This is not a memory leak. You have lots of different index objects in your list. the intersection call populates their cache with a set of information. Since the index objects are kept in the list, they are not cleaned up and hence the cache stays around, causing the growing memory. Removing the intersection call removes the memory growth
