### ISSUE TITLE
ENH: Rename get_dummies to more inclusive language

### ISSUE THREAD

**Issue by davidcavazos** [pandas-dev/pandas#48250]
### Feature Type

- [ ] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

The word "dummy" from the [`pd.get_dummies`](https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html) function can be offensive to some people and should be renamed.

It's marked as a word that **should not be used** by [Google's inclusive language word list](https://developers.google.com/style/word-list#dummy-variable).

### Feature Description

A good alternative name could be renaming it to `pd.get_indicator_variables`, which would also be more explicit on what it does.

### Alternative Solutions

Alternatively, `pd.get_one_hot` or `pd.get_one_hot_encoded` could also be an option familiar to Machine Learning practitioners.

[Google trends show](https://trends.google.com/trends/explore?geo=US&q=indicator%20variable,one-hot%20encoding) "indicator variable" and "one-hot encoding" to be similarly popular, with "indicator variable" being slightly more popular.

**Comment by MarcoGorelli** [comment]
Closing for now then, if the world does converge on an alternative which would allow for https://github.com/pandas-dev/pandas/issues/35724 to be reconsidered then we can go with that

**Comment by davidcavazos** [comment]
The world won't converge on an alternative if we don't start doing the change. GitHub's `master` -> `main` only happened because they took the initiative.

**Comment by TheNeuralBit** [comment]
My takeaway from the previous discussion was that adding a separate `get_indicators` (or some other agreed upon alternative) would be amenable. From there we can either:
- Deprecate and ultimately remove `get_dummies`, or
- Prefer `get_indicators` in documentation to nudge users there

It seems the former was rejected, but the latter could be acceptable. Could we pursue that approach?

(Also, would you prefer for us to continue discussion in #35274?)

**Comment by TheNeuralBit** [comment]
A non-Google reference for "dummy" being non-inclusive: https://itconnect.uw.edu/guides-by-topic/identity-diversity-inclusion//inclusive-language-guide/

> The origin of the word, “dummy,” is a person who cannot speak. Because the use of this word is often negatively associated with a disability, implying a person is worthless, ineffective or incapable, an alternative word should be used.

**Comment by MarcoGorelli** [comment]
> A non-Google reference for "dummy" being non-inclusive: https://itconnect.uw.edu/guides-by-topic/identity-diversity-inclusion//inclusive-language-guide/
> 
> > The origin of the word, “dummy,” is a person who cannot speak. Because the use of this word is often negatively associated with a disability, implying a person is worthless, ineffective or incapable, an alternative word should be used.

That's a nice reference, thanks! 

> (Also, would you prefer for us to continue discussion in https://github.com/pandas-dev/pandas/pull/35274?)

Yes please, let's keep the discussion in one place - perhaps post the reference you linked above there?

**Comment by davidcavazos** [comment]
Thanks @TheNeuralBit. I think that either `get_indicators` (as per the previous discussion), or `get_indicator_variables` (longer, but more explicit), would work. For consistency with other pandas functions with usually shorter names, I think `get_indicators` might be more suitable.

I would personally create the new name and mark `get_dummies` as deprecated (but still usable), and finally remove it completely in a future release.

**Comment by davidcavazos** [comment]
The University of Delaware also has a similar (although shorter) list including to remove "dummy value":

http://www1.udel.edu/itwebdev/help/dei.html

**Comment by davidcavazos** [comment]
And here are some more examples:

* [University of Guelph](https://guides.uoguelph.ca/guides/style-guide/inclusive-language/inclusive-it-language-replacement-terms/)
* [Research and Education Networks](https://www.ren-isac.net/public-resources/Inclusive_Language_IT.html)
* [University of California](https://cpb-us-e2.wpmucdn.com/sites.oit.uci.edu/dist/c/2/files/2022/02/Inclusive-Language-Guide.pdf)

And even the [National Institute of Standards and Technology](https://nvlpubs.nist.gov/nistpubs/ir/2021/NIST.IR.8366.pdf)

**Comment by davidcavazos** [comment]
This [document](https://www.acohen.com/blog/wp-content/uploads/2020/11/inclusive-words.pdf) also mentions _how_ it causes harm:

> “Dummy” and similar terms stigmatize mental disabilities. The alternatives are clearer.

**Comment by MarcoGorelli** [comment]
Thanks @davidcavazos , appreciate the references - could you post them in https://github.com/pandas-dev/pandas/issues/35724 please so we keep the discussion in one place?

**Comment by davidcavazos** [comment]
Sure, I just posted a summary of the key points.
