### ISSUE TITLE
DOC: read_json should list `None` for `orient`

### ISSUE THREAD

**Issue by bashtage** [pandas-dev/pandas#48252]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.read_json.html

### Documentation problem

`None` is an acceptable type for `orient`.

### Suggested fix for documentation

Add `None` to the list of acceptable arguments, or maybe just an `, optional`

**Comment by bashtage** [comment]
xref pandas-dev/pandas-stubs#226

**Comment by ambujpawar** [comment]
take
