### ISSUE TITLE
CI: Improve warning when no pandas dev version installed when running stubtest

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#48260]
see https://github.com/pandas-dev/pandas/pull/48240#pullrequestreview-1086137999

**Comment by samrao1997** [comment]
@phofl Could you explain what the `#current condition` would be if pandas version is false?

**Comment by mroeschke** [comment]
`#current condition` just means the logic that already exists in that `if` block

**Comment by ambujpawar** [comment]
This looks something I can do. Can I take this up?

**Comment by phofl** [comment]
Sure

**Comment by ambujpawar** [comment]
take
