### ISSUE TITLE
CI: newer version of s3fs is pulled causing builds to fail

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#48271]
Looks like we are pulling 0.6.0 (which is way smaller than our minimum version btw) instead of 0.4.2. The 0.6.0 requires aiobotocore, but is not compatible with the new version.

Working build:
https://github.com/pandas-dev/pandas/runs/8026125010?check_suite_focus=true

Failed build:
https://github.com/pandas-dev/pandas/runs/8035127801?check_suite_focus=true

Lets try to force at least the minimum s3fs version.

**Comment by phofl** [comment]
Our minimum version of s3fs is not compatible with aiobotocore >= 2.0, so have to pin to lower than 2.0 till we bump s3fs

**Comment by simonjayhawkins** [comment]
milestoning as 1.5 for now. will backport to 1.4.x if needed.
