### ISSUE TITLE
ENH: Add ignore_index to Series.drop_duplicates

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#48304]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Appears in 1.0, `DataFrame.drop_duplicates` gained `ignore_index`: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html#pandas.DataFrame.drop_duplicates

Motivating issue: https://github.com/pandas-dev/pandas/issues/30114
xref: https://github.com/pandas-dev/pandas/issues/31725

For API consistency, `Series.drop_duplicates` should have an `ignore_index` argument too to perform a `reset_index(drop=False)`

### Feature Description

Probably similar to https://github.com/pandas-dev/pandas/pull/30405

### Alternative Solutions

Users can just call `reset_index(drop=True)`.

**Comment by kostyafarber** [comment]
Can this be closed now?
