### ISSUE TITLE
ENH: Add option to show number of changes made from loc

### ISSUE THREAD

**Issue by akald** [pandas-dev/pandas#48306]
Feature Type
- Adding new functionality to pandas

Please could it be possible to add an option to loc that shows the number of changes made? In the example below, it would quickly tell the user that for the technology group, I forgot to add ```case=False```.  In other datasets, it would require more investigation.

```
df.loc[df.s.tr.contains("apple"), "category"] = "fruit"
df.loc[df.s.tr.contains("banana"), "category"] = "fruit"
df.loc[df.s.tr.contains("Samsung|Sony"), "category"] = "Technology"

```
Desired Print Statements Output:
```
apple replacement yielded 30 changes
banana replacement yielded 57 changes
Samsung|Sony replacement yielded 0 changes

**Comment by phofl** [comment]
Hi, thanks for your report.

i am -1 on this, if this is really needed you could simply sum the mask used as indexer

**Comment by MarcoGorelli** [comment]
Agreed, thanks anyway for the suggestion

**Comment by akald** [comment]
Ideally there should be a way without typing all the conditions twice because if I have 30 conditions that would get really messy and confusing

**Comment by phofl** [comment]
This is probably out of scope for us
