### ISSUE TITLE
STYLE: upgrade codespell

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#48349]
Task here is:
- in https://github.com/pandas-dev/pandas/blob/10855f6b55dfb05b1e9a0186b8203bcf4bea7df6/.pre-commit-config.yaml#L24-L28, change the version to the latest available `v2.2.1`
- run `pre-commit run codespell --all-files`. you should see something like
```
codespell...............................................................................................Failed
- hook id: codespell
- exit code: 65

pandas/tests/arrays/string_/test_string.py:185: bu ==> by
pandas/tests/config/test_config.py:19: ro ==> to, row, rob, rod, roe, rot
pandas/tests/config/test_config.py:36: ro ==> to, row, rob, rod, roe, rot
web/pandas/about/governance.md:186: recuse ==> recurse
pandas/io/parsers/python_parser.py:1275: fromm ==> from
pandas/io/parsers/python_parser.py:1275: fromm ==> from
pandas/tests/arrays/categorical/test_constructors.py:453: Hastable ==> Hashtable
pandas/core/resample.py:1048: coulmns ==> columns
pandas/io/formats/style.py:831: highlighed ==> highlighted
```
- fixup these errors
- check that `pre-commit run codespell --all-files` passes
- open a PR

**Comment by jbrockmendel** [comment]
> web/pandas/about/governance.md:186: recuse ==> recurse

Looks like this one is correct as is

**Comment by lucasdamo** [comment]
take

**Comment by prakhar-198** [comment]
take

**Comment by lucasdamo** [comment]
This is my first pull request on pandas and on a large project like this one, if someone could double check it please, specially the commit message, formatting and so on...

I could not find a way to ignore errors on a per line/per file basis, if there is a way of doing so please tell me so I can improve this commit.
