### ISSUE TITLE
BUG: mypy assumes selecting from a DataFrame returns a Series but this is not the case for a DataFrame with MultiIndex columns

### ISSUE THREAD

**Issue by MichaelHarrison-CE** [pandas-dev/pandas#48366]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

df_data = pd.DataFrame({('outer', 'col1'): ['a', 'b', 'b', 'c', 'c', 'c'], 
                        ('outer', 'col2'): [1, 2, 2, 3, 3, 3],
                        })

df_inner: pd.DataFrame = df_data['outer']
print(df_inner.shape)
```

### Issue Description

Running mypy on the above code snippet gives the following error due to the `df_inner` definition:

> error: Incompatible types in assignment (expression has type "Series[Any]", variable has type "DataFrame"

However, `df_inner` _is_ a DataFrame since the columns of `df_data` are a MultiIndex and we're just selecting from the outer level.

For info, my python environment is:

<details>
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
</head>

<div style='display:inline-block'>

<body link="#0563C1" vlink="#954F72">

Package | Version
-- | --
mypy | 0.971
mypy-extensions | 0.4.3
nodeenv | 1.7.0
numpy | 1.23.2
pandas | 1.5.0rc0
pandas-stubs | 1.4.3.220829
pip | 22.2.2
pyright | 1.1.269
python-dateutil | 2.8.2
pytz | 2022.2.1
setuptools | 63.4.3
six | 1.16.0
tomli | 2.0.1
types-pytz | 2022.2.1.0
typing_extensions | 4.3.0
wheel | 0.37.1

</body>

</html>

</details>

### Expected Behavior

The mypy type check should succeed without error.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 224458ee25d92ccdf289d1ae2741d178df4f323e
python           : 3.8.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252

pandas           : 1.5.0rc0
numpy            : 1.23.2
pytz             : 2022.2.1
dateutil         : 2.8.2
setuptools       : 63.4.3
pip              : 22.2.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by phofl** [comment]
Hi, same as in the other issue. This is a known issue, but please also report in the other repository

**Comment by MichaelHarrison-CE** [comment]
Thanks, have posted it there.
