### ISSUE TITLE
ENH: change pandas.DataFrame.pct_change method default argument "fill_method" to None

### ISSUE THREAD

**Issue by nicolasakf** [pandas-dev/pandas#48371]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I think it is very confusing to have a default fill method implemented within another method whose sole purpose is not to fill null values. I understand that some users may want to fill null values before calculating percent changes in a series or df object. However, it is better to have the user do it consciously than to try to predict what the user's intentions is.

### Feature Description

_

### Alternative Solutions

_

**Comment by MarcoGorelli** [comment]
Thanks for the suggestion - without filling NAs, wouldn't every value after the first NA end up being NA?

I'd be -1 on changing this, don't think it'd be worth going through a deprecation cycle and am not convinced the new behaviour would be better

**Comment by mroeschke** [comment]
Agreed. This behavior has been documented for a while, and I also don't believe not filling NAs and propagating them would be inconvenient. Closing but can reopen if there is more buy in from the community and core team.
