### ISSUE TITLE
ENH: Expose `pandas._libs.missing.NAType`

### ISSUE THREAD

**Issue by randolf-scholz** [pandas-dev/pandas#48388]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

When typing hinting using `pandas-stubs`, using `type[pd.NA]` is not possible.

```
error: Variable "pandas._libs.missing.NA" is not valid as a type  [valid-type]
```

Instead, it needs to be annotated as `NAType` which is currently hidden in the private library `pandas._libs.missing`.

### Feature Description

Make `NAType` accessible through `from pandas import NAType`.

### Alternative Solutions

Rework how `padnas.NA` works such that `type[pandas.NA]` is a valid type hint.

### Additional Context

Example

```python
import pandas as pd

def first_negative(s: Series[float]) -> float | type[pd.NA]:
    """return the first negative number in s or pd.NA""""
    negs = s[s<0]
    return negs[0] if len(negs) else pd.NA
```

**Comment by twoertwein** [comment]
I belief/hope that `def first_negative(s: Series[float]) -> float | Literal[pd.NA]: ...` that least works with 1.5.rc0?

**Comment by twoertwein** [comment]
In the next major pandas release you will be able to do the following:

```py
import pandas as pd
from pandas.api.typing import NAType

def na() -> NAType:
    return pd.NA
```
xref #48577
