### ISSUE TITLE
DOC: Include SeriesGroupBy ops in API docs

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#48399]
https://pandas.pydata.org/pandas-docs/dev/reference/groupby.html

Currently we have documentation of various groupby methods on `GroupBy` for any methods of `SeriesGroupBy` and `DataFrameGroupBy` that share an implementation, on `DataFrameGroupBy` if they exist on both but do not share an implementation, or on `SeriesGroupBy` xor `DataFrameGroupBy` if they only exist on one. This can make locating the docs a bit tricky, and the documentation also contains the line:

> The following methods are available in both SeriesGroupBy and DataFrameGroupBy objects, but may differ slightly, usually in that the DataFrameGroupBy version usually permits the specification of an axis argument, and often an argument indicating whether to restrict application to columns of a specific data type.

I think it would be better to generate docs for all SeriesGroupBy methods and all DataFrameGroupBy methods individually, even if they entirely overlap.

This is somewhat related to #6944, as I think it would be then possible to treat `GroupBy` as an internal pandas object (at least from a documentation perspective). But this isn't logically necessary.

cc @jorisvandenbossche

**Comment by mroeschke** [comment]
> I think it would be better to generate docs for all SeriesGroupBy methods and all DataFrameGroupBy methods individually, even if they entirely overlap.

+1 for this suggestion. Ideally users shouldn't really need to know of `SeriesGroupBy` and `DataFrameGroupBy` objects either, but it appears the most straightforward way to indicate whether `Series` or `DataFrame` supports a groupby method.

**Comment by rhshadrach** [comment]
I was playing around with this a bit yesterday - I'm wondering what the best way to organize the documentation is. Two natural options, neither of which I personally love, but am finding I prefer the 2nd:

```
Computations / descriptive stats
--------------------------------
DataFrameGroupBy.mean
SeriesGroupBy.mean
DataFrameGroupBy.sum
SeriesGroupBy.sum
```

vs

```
DataFrameGroupBy computations / descriptive stats
-------------------------------------------------
DataFrameGroupBy.mean
DataFrameGroupBy.sum

SeriesGroupBy computations / descriptive stats
----------------------------------------------
SeriesGroupBy.mean
SeriesGroupBy.sum
```

Another option I considered was a table with two column - DataFrameGroupBy and SeriesGroupBy -  but I think this doesn't work with  autosummary.

**Comment by mroeschke** [comment]
The second looks better to me also IMO
