### ISSUE TITLE
BUG: Bug or documentation bug for pd.Index.shift(freq='W')

### ISSUE THREAD

**Issue by edschofield** [pandas-dev/pandas#48408]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
Minimal example:


import pandas as pd

dates = pd.date_range('2022-08-01', '2022-08-31')
print(dates.shift(freq='W'))
```

Output:
```
DatetimeIndex(['2022-08-07', '2022-08-07', '2022-08-07', '2022-08-07',
               '2022-08-07', '2022-08-07', '2022-08-14', '2022-08-14',
               '2022-08-14', '2022-08-14', '2022-08-14', '2022-08-14',
               '2022-08-14', '2022-08-21', '2022-08-21', '2022-08-21',
               '2022-08-21', '2022-08-21', '2022-08-21', '2022-08-21',
               '2022-08-28', '2022-08-28', '2022-08-28', '2022-08-28',
               '2022-08-28', '2022-08-28', '2022-08-28', '2022-09-04',
               '2022-09-04', '2022-09-04', '2022-09-04'],
              dtype='datetime64[ns]', freq=None)
```

### Issue Description

With this setup:
```python
dates = pd.date_range('2022-08-01', '2022-08-31')
series = pd.Series(range(31), index=dates)
```

... I am still mystified after reading the docs why these two function calls have such different behavior:

```python
a = series.shift(freq='7D')
b = series.shift(freq='W')
```

### Expected Behavior

I would expect the frequency of the shifted object `series.shift(freq='W')` to be `<Week>`. Instead it is `None`.

I also expected that the result of calling `series.shift(freq='7D')` would be substantially similar to calling `series.shift(freq='W')`. If the result is not buggy but expected, this is certainly not clear from the documentation on `series.shift`, which could benefit from an example of calling `series.shift(freq='W')` and explaining the output.

### Installed Versions

<details>

>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : ca60aab7340d9989d9428e11a51467658190bb6b
python           : 3.9.13.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_AU.UTF-8
LOCALE           : en_AU.UTF-8

pandas           : 1.4.4
numpy            : 1.23.2
pytz             : 2022.2.1
dateutil         : 2.8.2
setuptools       : 63.4.1
pip              : 22.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.4.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : None
matplotlib       : None
numba            : None
numexpr          : 2.8.3
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : 3.7.0
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by phofl** [comment]
Hi, thanks for your report.

The offset is automatically anchored to Sunday if nothing else Is provided, hence the difference. Freq is only kept if both are equal, but since D!=W, it is set to None

**Comment by mroeschke** [comment]
Thanks for the report, but closing as a usage question as described from the above explanation
