### ISSUE TITLE
CI: Numpydev causes some warnings in our test suite

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#48405]
https://numpy.org/devdocs/release/1.24.0-notes.html#numpy-now-gives-floating-point-errors-in-casts

This causes some warnings on our side. Should probably have a look. Captured one accidentally:

https://github.com/pandas-dev/pandas/runs/8194844501?check_suite_focus=true

**Comment by mroeschke** [comment]
I think we might have addressed this in the meantime so closing
