### ISSUE TITLE
BUG: inconsistent result of `Series.sum` and `groupby.sum`

### ISSUE THREAD

**Issue by mixilchenko** [pandas-dev/pandas#48433]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame({'val': [0.0093984958] * 20, 'id': [1] * 20})
s1 = df['val'].sum()
s2 = df.groupby('id')['val'].sum().iloc[0]
assert s1 == s2, f'{s1} != {s2}'
```

### Issue Description

Series sum and groupby sum give different result when there is only one group

### Expected Behavior

I expect my example won't raise `AssertionError`

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 58c124feb4dffe46a73a43fbe995421ea361dfee
python           : 3.9.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.5.0
Version          : Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : ru_RU.UTF-8
LOCALE           : ru_RU.UTF-8

pandas           : 1.6.0.dev0+75.g58c124feb4
numpy            : 1.23.2
pytz             : 2022.2.1
dateutil         : 2.8.2
setuptools       : 58.1.0
pip              : 21.2.4
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by phofl** [comment]
Hi, thanks for your report. This is kind of expected. Regular sum dispatches to numpy which uses pairwise summation. Our groupby altos use kahan summation that is more precise but slower. This is already known on the numpy issue tracker I think
