### ISSUE TITLE
CI: Pyarrow creates issues on macOS builds

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#48432]
https://pipelines.actions.githubusercontent.com/serviceHosts/e1fa798b-a3de-4f41-9248-cf5942f5881f/_apis/pipelines/1/runs/324147/signedlogcontent/7?urlExpires=2022-09-07T07%3A23%3A47.0723985Z&urlSigningMethod=HMACV1&urlSignature=GOXocyADbqtg0i0DMNBl3Gpy0wamSRm9KJIaClCkPg0%3D

This seems to be related to pyarrow somehow. I don't think that this is related to #48431

**Comment by phofl** [comment]
https://github.com/conda-forge/libprotobuf-feedstock/pull/128

**Comment by phofl** [comment]
Yeah but our builds are still pulling the broken ones. Not sure what's going on, maybe some caching related issue?

**Comment by mroeschke** [comment]
> Yeah but our builds are still pulling the broken ones. Not sure what's going on, maybe some caching related issue?

I think the CI environments are cached and invalidated once per day: https://github.com/mamba-org/provision-with-micromamba#cache-downloads-key

We can specify a cache key similar to the default with a bump number at the end to make it easier for us to invalidate: https://github.com/mamba-org/provision-with-micromamba#cache-env-key

**Comment by phofl** [comment]
Works today
