### ISSUE TITLE
CI: Docbuild started to fail

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#48431]
As far as I can see, this was unrelated to any changes we added

https://github.com/pandas-dev/pandas/runs/8218023423?check_suite_focus=true

**Comment by jorisvandenbossche** [comment]
This is complaining about a line in the docs that has already been there for many years:

```
 >>>-------------------------------------------------------------------------
Exception in /home/runner/work/pandas/pandas/doc/source/user_guide/timeseries.rst at block ending on line 2001
Specify :okexcept: as an option in the ipython:: block to suppress this message
  Cell In [360], line 2
    p == pd.Period("2012-01", freq="3M")
    ^
SyntaxError: invalid syntax
```

This is using an inline `@okexcept`. Since there was a new IPython release, that's my first guess.

**Comment by jorisvandenbossche** [comment]
The failing build is using IPython 8.5.0, released yesterday. Potentially related to https://github.com/ipython/ipython/pull/13612/
