### ISSUE TITLE
BUG: exeception on NDFrame.replace

### ISSUE THREAD

**Issue by NSH531** [pandas-dev/pandas#48461]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
@doc(NDFrame.replace, **dew)
        def replace(  # type: ignore[override]
            self,
            to_replace=None,
            value=lib.no_default,
            inplace: bool = False,
            limit: int | None = None,
            regex: bool = False,
            method: Literal["pad", "ffill", "bfill"] | lib.NoDefault = lib.no_default,
        ) -> DataFrame | None:
            return super().replace(
                to_replace=to_replace,
                value=value,
                inplace=inplace,
                limit=limit,
                regex=regex,
                method=method,
            )
```

### Issue Description

I attached screenshot :

![image](https://user-images.githubusercontent.com/5903577/189124495-94cedddf-6196-4cfe-a8f7-93d97f4c4c56.png)

### Expected Behavior

I got exception:
![image](https://user-images.githubusercontent.com/5903577/189124669-7f88a047-e8d4-4933-b232-fefeeacc9b53.png)

### Installed Versions

tnx,

nate

**Comment by phofl** [comment]
Hi, thanks for your report. Please provide a minimal and reproducible example. Screenshots don't help us when debugging

**Comment by phofl** [comment]
Closing for now, please ping to reopen when you can provide an example
