### ISSUE TITLE
BUG: [unit test] pandas/io/clipboard/__init__.py:300: PyperclipException

### ISSUE THREAD

**Issue by adrienpacifico** [pandas-dev/pandas#48483]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
# pytest pandas/tests/io/
============================================================================================ short test summary info =============================================================================================
FAILED pandas/tests/io/test_clipboard.py::TestClipboard::test_raw_roundtrip[\U0001f44d...] - pandas.errors.PyperclipException: 
FAILED pandas/tests/io/test_clipboard.py::TestClipboard::test_raw_roundtrip[\u03a9\u0153\u2211\xb4...] - pandas.errors.PyperclipException: 
FAILED pandas/tests/io/test_clipboard.py::TestClipboard::test_raw_roundtrip[abcd...] - pandas.errors.PyperclipException: 
========================================================================================= 3 failed, 232 passed in 1.55s ==========================================================================================
```

### Issue Description

The unit-test  https://github.com/pandas-dev/pandas/blob/047c11d7801ffd0cf679d606293af510e34d7b92/pandas/tests/io/test_clipboard.py#L398
does not pass.

I am using VSCode with the .devcontainer file (thus in a container), with a linux distribution (pop-os). 
Current commit I am on is 047c11d7801ffd0cf679d606293af510e34d7b92

I tried to do `apt-get install xclip` but it did not solve the issue. 

### Expected Behavior

The test should pass.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 047c11d7801ffd0cf679d606293af510e34d7b92
python           : 3.8.13.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.8.0-7630-generic
Version          : #32~1609193707~20.10~781bb80-Ubuntu SMP Tue Jan 5 21:29:56 UTC 2
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : C.UTF-8
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.6.0.dev0+89.g047c11d780.dirty
numpy            : 1.22.4
pytz             : 2022.2.1
dateutil         : 2.8.2
setuptools       : 65.3.0
pip              : 22.2.2
Cython           : 0.29.32
pytest           : 7.1.3
hypothesis       : 6.54.5
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.9.1
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : 2.9.3
jinja2           : 3.0.3
IPython          : 8.5.0
pandas_datareader: 0.10.0
bs4              : 4.11.1
bottleneck       : 1.3.5
brotli           : 
fastparquet      : 0.8.3
fsspec           : 2021.11.0
gcsfs            : 2021.11.0
matplotlib       : 3.5.3
numba            : 0.55.2
numexpr          : 2.8.3
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : 0.17.8
pyarrow          : 9.0.0
pyreadstat       : 1.1.9
pyxlsb           : 1.0.9
s3fs             : 2021.11.0
scipy            : 1.9.1
snappy           : 
sqlalchemy       : 1.4.41
tables           : 3.7.0
tabulate         : 0.8.10
xarray           : 2022.6.0
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : 0.18.0
tzdata           : None

</details>

**Comment by mroeschke** [comment]
What was the exception traceback for these tests?

**Comment by adrienpacifico** [comment]
@mroeschke it is a `PyperclipException`. Strangely enough, I can make the test pass in another shell on the same docker machine. What am I missing?

### Stacktrace
```python
self = <pandas.tests.io.test_clipboard.TestClipboard object at 0x7f479a61ca00>, data = '👍...'

    @pytest.mark.parametrize("data", ["\U0001f44d...", "Ωœ∑´...", "abcd..."])
    @pytest.mark.xfail(
        reason="Flaky test in multi-process CI environment: GH 44584",
        raises=AssertionError,
        strict=False,
    )
    def test_raw_roundtrip(self, data):
        # PR #25040 wide unicode wasn't copied correctly on PY3 on windows
>       clipboard_set(data)

pandas/tests/io/test_clipboard.py:400: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pandas/io/clipboard/__init__.py:640: in lazy_load_stub_copy
    return copy(text)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pandas.io.clipboard.init_no_clipboard.<locals>.ClipboardUnavailable object at 0x7f479a3c3460>, args = ('👍...',), kwargs = {}

    def __call__(self, *args, **kwargs):
>       raise PyperclipException(EXCEPT_MSG)
E       pandas.errors.PyperclipException: 
E           Pyperclip could not find a copy/paste mechanism for your system.
E           For more information, please visit
E           https://pyperclip.readthedocs.io/en/latest/#not-implemented-error

pandas/io/clipboard/__init__.py:300: PyperclipException
```


# Difference in execution: 
Strangely enough, I can make that test past of fail based on where I execute the notebook... 
I would be quite please to understand what makes the difference between the first screenshot and the second one...
The only one I found is that one the left pannel I have a box for the shell where the test fail, and a console logo for the test that pass. 
![image](https://user-images.githubusercontent.com/6614121/189647351-e3559ad4-dbd7-469c-8d46-8af2480d4329.png)



![image](https://user-images.githubusercontent.com/6614121/189643955-d153b1e8-d050-4fdc-95bc-216cc97a9cc2.png)
![image](https://user-images.githubusercontent.com/6614121/189647725-3d4f9c58-2160-46bc-b42b-f1a108632ab9.png)

**Comment by mroeschke** [comment]
Thanks. Do you get the same errors when you install `xsel`?

**Comment by adrienpacifico** [comment]
> Thanks. Do you get the same errors when you install xsel?

Yes it does. 

The issue is the following:
1. It goes through https://github.com/pandas-dev/pandas/blob/fe9e5d023e20304ad1bdfa1da53f3af452c72a00/pandas/io/clipboard/__init__.py#L511 with variable `HAS_DISPLAY == False`

it then executes https://github.com/pandas-dev/pandas/blob/fe9e5d023e20304ad1bdfa1da53f3af452c72a00/pandas/io/clipboard/__init__.py#L581

and thus calls https://github.com/pandas-dev/pandas/blob/fe9e5d023e20304ad1bdfa1da53f3af452c72a00/pandas/io/clipboard/__init__.py#L297

and raises the following exception:

```python
def init_no_clipboard():
    class ClipboardUnavailable:
        def __call__(self, *args, **kwargs):
            raise PyperclipException(EXCEPT_MSG)

        def __bool__(self) -> bool:
            return False

    return ClipboardUnavailable(), ClipboardUnavailable()
```

**Comment by mroeschke** [comment]
Maybe `DISPLAY` needs to be set as an environment variable? I see `HAS_DISPLAY = os.getenv("DISPLAY", False)`

**Comment by adrienpacifico** [comment]
There is no environment variable, however `os.getenv("DISPLAY", True)` will set `HAS_DISPLAY` to `False`

Changing `HAS_DISPLAY = os.getenv("DISPLAY", True)` (instead of False) will make the  3 tests as `xfailed`. 

As my environment has (I guess) no display, I feel that it is not what is supposed to be done.

**Comment by adrienpacifico** [comment]
I see that in the CI, tests are launched with `xvfb-run`, which probably explain why they are passing.  

However, if I try to intall xvfb ( `apt-get install xvfb` )  in the docker image, I get a strange error: 
```bash
(pandas-dev) root@61580073cc05:/workspaces/pandas# xvfb-run pandas/tests/io/test_clipboard.py 
/usr/bin/xvfb-run: 184: pandas/tests/io/test_clipboard.py: Permission denied
```

**Comment by adrienpacifico** [comment]
Moreover, if I 
```bash
Xvfb :99 &
export DISPLAY=:99
```

Then the value of `HAS_DISPLAY` becomes equal to `':99'`, and the tests now Xpass!

However, if I get it wright we should have:
- Tests launched without display --> should xfail
- Tests launched with display --> should pass

@mroeschke, I'll try to get that behavior by modifiying the tests and the maybe I should make a PR? 

Is there a way to see if this test pass somewhere in the CI? 

My proposition would be to :
- Run the test if a environment variable `DISPLAY` is set (current behavior is to xpass it)
- xfail the test if there is no environment variable

Code proposition: 
```python
    @pytest.mark.parametrize("data", ["\U0001f44d...", "Ωœ∑´...", "abcd..."])
    @pytest.mark.xfail(
        os.environ.get('DISPLAY') is None, 
        reason="Cannot be runned if a headless system is not put in place with ",
        strict=True,
    )
    def test_raw_roundtrip(self, data):
        # PR #25040 wide unicode wasn't copied correctly on PY3 on windows
        clipboard_set(data)
        assert data == clipboard_get()
```

**Comment by mroeschke** [comment]
Thanks for investigating. Yes a PR with that xfail would be fine. Since this modifies the test to work in "local" development environments, as long as the CI still passes (which doesn't use the container), should be a fine addition.
