### ISSUE TITLE
BUG: Groupby diff on a datetime64[ns] column of an empty DataFrame returns Series with wrong dtype

### ISSUE THREAD

**Issue by oliverhiggs** [pandas-dev/pandas#48516]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame({'a': pd.Series(dtype='int'), 'b': pd.Series(dtype='datetime64[ns]')})

# Produces expected result of an empty timedelta64[ns] series
df['b'].diff()

# BUG: produces unexpected result of an empty datetime64[ns] series
df.groupby('a')['b'].diff()
```

### Issue Description

Performing a groupby diff on a datetime64[ns] column of an empty DataFrame returns a Series with dtype datetime64[ns]. This is inconsistent with the (expected) behaviour when performing a diff without using groupby, which results in an empty timedelta64[ns] series.

### Expected Behavior

The groupby diff should produce a Series with a timedelta64[ns] dtype.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : ca60aab7340d9989d9428e11a51467658190bb6b
python           : 3.10.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.16.3-microsoft-standard-WSL2
Version          : #1 SMP Fri Apr 2 22:23:49 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.4
numpy            : 1.22.4
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 60.6.0
pip              : 22.0.3
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.9.3
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : 3.5.2
numba            : 0.56.0
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 9.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.0
snappy           : None
sqlalchemy       : 1.4.39
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by bsegot** [comment]
Hello oliver, this bug has been resolved since this commit, 
https://github.com/pandas-dev/pandas/commit/3408a61ff940900ed1aa5fb89ee92635938d2e94

the problem was how the corner case empty dataframe was handled, in the function def _wrap_applied_output,
of the file located at /pandas/pandas/core/groupby

For this corner case, it does not impose the type float64, but pass the type of the column direcly.
If you use a version of pandas >=1.3.0, this bug shouldn't appear.

I think we can close this bug report
