### ISSUE TITLE
WEB: Fix sponsor logos in mobile

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#48519]
The sponsor logos look pretty bad in mobile. CZI and Two sigma are significantly smaller than the others, and some padding would help see the logos better.

And it could probably look better if there were two logos per column, instead of just one (we're using bootstrap, that should be quite quick to implement).

![pandas_sponsors](https://user-images.githubusercontent.com/10058240/189749946-614716fe-e28b-4141-8182-8db97ebfb383.png)

**Comment by amay-patel** [comment]
Hi! Could I work on this issue?

**Comment by datapythonista** [comment]
> Hi! Could I work on this issue?

Absolutely, please do. Thank you!

**Comment by amay-patel** [comment]
I am currently working on the issue...will be submit a PR soon!

**Comment by amay-patel** [comment]
@datapythonista I am having issue with rate limit exceeding for GitHub API. Do you have a fix for this issue?

**Comment by datapythonista** [comment]
> @datapythonista I am having issue with rate limit exceeding for GitHub API. Do you have a fix for this issue?

You can call `pandas_web.py` with `--ignore-io-errors`.

**Comment by amay-patel** [comment]
Thank you. That has fixed the issue!
