### ISSUE TITLE
DOC: Fix styles for dark mode in docs home

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#48527]
xref: #42744

We'll be making the pandas documentation have a dark mode soon. But some boxes in the docs home seem to have a white background, instead of a transparent one:

![Screenshot_20220913_143553](https://user-images.githubusercontent.com/10058240/189917270-d613c001-ed12-4e21-aedf-2fe4d3cb8f20.png)

We should remove any custom style that is preventing the dark mode to work properly.

The changes can be tested against this branch to see if they work properly: #48285

**Comment by valanm22** [comment]
@datapythonista May I work on this issue?

**Comment by valanm22** [comment]
Do I replace the old svg images or do I upload them as new svg images?

**Comment by datapythonista** [comment]
Better replace the old images.

**Comment by valanm22** [comment]
Ok got it.

**Comment by datapythonista** [comment]
Looks like the problem are not the svg images, but the styles. I updated the description.

**Comment by thekavikumar** [comment]
I'm not able to run python make.py HTML showing error module not found: No module named 'pandas._libs.interval
any solution?

**Comment by datapythonista** [comment]
In the project root run `./setup.py build_ext --inplace` to compile pandas extensions, that should fix it. In the contributing documentation you have all the info.

**Comment by thekavikumar** [comment]
That works! Now I will work on the styles and please do close this issue

**Comment by seanjedi** [comment]
Is this issue still open? 
Seems to be resolved?

**Comment by datapythonista** [comment]
The only thing I see that still doesn't show well in the dark mode is this section: https://pandas.pydata.org/docs/dev/getting_started/index.html#intro-to-pandas

We can close this issue when the background of that block is set to dark, and we check that things look good with it.

**Comment by anushkabishnoi** [comment]
Hi I tried visiting the webpage you linked above, but since dark mode isn't released yet, it would be really helpful if you upload a screenshot of the portion to be modified. (willing to work on this issue :))

**Comment by datapythonista** [comment]
The dark mode is released. If you don't have your browser in dark mode, you can get it with the icon in the right top of the docs.

**Comment by anushkabishnoi** [comment]
oh okay, thanks 

Can I work on this issue?

**Comment by anushkabishnoi** [comment]
> oh okay, thanks
> 
> Can I work on this issue?

This is my first time working with open source, it would be really helpful if you could guide me to files that need modification. 

Thanks in advance :)

**Comment by datapythonista** [comment]
Sure, thanks for the help. I think this PR should be similar to https://github.com/pandas-dev/pandas/pull/48572/files

You can build the documentation after creating an environment (see https://pandas.pydata.org/docs/dev/development/contributing_environment.html) running the make.py script inside doc/. The development documentation I point to has more detailed information.

**Comment by PKNaveen** [comment]
is this issue closed or still open?

**Comment by datapythonista** [comment]
> is this issue closed or still open?

There is a PR open, it'll be merge shortly. But there is #51860, which is related and you can work on if you are looking for something to contribute.
