### ISSUE TITLE
Error gcc when I try to install pandas (ubuntu 20.04)

### ISSUE THREAD

**Issue by vinzinz1396** [pandas-dev/pandas#48523]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Ubuntu 20.04 on Parallels (macbook m1 pro)

### Installation Method

pip install

### pandas Version

~0.25.1

### Python Version

3.6.10

### Installation Logs

<details>

I'm trying to install pandas 0.25.1 in python3.6 (ubuntu 20.04) on a vm on parallels MacBook m1 pro, but I have this error:
`          | ^
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qfln1wsg/pandas_d9a8678992bd4c9abaccd19db522713a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qfln1wsg/pandas_d9a8678992bd4c9abaccd19db522713a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-w73_gplr/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/parallels/.local/include/python3.6m/pandas Check the logs for full command output.`

I post the entire error in a file txt. I have already installed gcc g++ python3.6-dev. I don't know how I can resolve this error. Is it an error for incompatibility with m1?
</details>
[pandas.zip](https://github.com/pandas-dev/pandas/files/9554996/pandas.zip)

**Comment by phofl** [comment]
Hi, thanks for your report. We don't support versions that old anymore.

**Comment by vinzinz1396** [comment]
But in an other ubuntu installation it works..

**Comment by phofl** [comment]
I don't doubt that, but you are on your own when debugging stuff for these versions
