### ISSUE TITLE
[Question] Why is test_fast.sh configured to work with only 4 cores ?

### ISSUE THREAD

**Issue by adrienpacifico** [pandas-dev/pandas#48535]
- [x] I have checked that the answer to this question is not present in any other issue, merge request comments, or the documentation.

test_fast.sh [is the recommended way](https://pandas.pydata.org/docs/development/contributing_codebase.html?highlight=test_fast%20sh#running-the-test-suite) to run the test suite in an efficient manner.
However, it is configure to run only on 4 cores? Why?

Many modern computer has more than 4 cores. I would suggest to replace `-n 4` to `-n0` on the following test_fast.sh line 

https://github.com/pandas-dev/pandas/blob/65af4ef2043a5f879dc42e009de1323fdcea225b/test_fast.sh#L8 

@mroeschke  was the last to commit on that file (https://github.com/pandas-dev/pandas/blame/main/test_fast.sh) (it case it changes something for triage).

**Comment by mroeschke** [comment]
Thanks for the report. IMO since these scripts are so short, I would recommend removing them and just documenting the command with the note on how `-n` can be adjusted to the number of cores on the user's machine.

**Comment by adrienpacifico** [comment]
Thank you!
I see your point.

Just to report my experience. When I tried to run the tests for the first time, I ran the test_fast.sh file before reading the documentation. If I had not find that file, I would probably have ran pytest without these interesting options. 

I think the -n0 option is improving most user situation without changing much their current workflow? 
However, that does not seem very important!

**Comment by mroeschke** [comment]
> I think the -n0 option is improving most user situation without changing much their current workflow?

I suppose so. I have just found local development to be just a broad topic that maintaining the documentation on guiding users on how to prepare their environment for contribution easier than maintaining several scripts & misc tools that are "opinionated" since a user setups can be widely varied.

**Comment by rhshadrach** [comment]
+1 for removal provided we're documenting the command in the contributing guide. I think it would be good to briefly describe what the options do (or at least link to pytest's documentation); I personally am not a fan of the `-r sxX` bit.

**Comment by WillAyd** [comment]
+1 to remove this script as well
