### ISSUE TITLE
ENH: Test development container

### ISSUE THREAD

**Issue by adrienpacifico** [pandas-dev/pandas#48537]
### Feature Type

- [ ] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I am currently trying to set en development environment on a X86 Linux system by passing all test on my machine with a the provided `Dockerfile`. 

The current development environment with this Dockerfile is not working since `fast_test.sh` is not passing. 

![image](https://user-images.githubusercontent.com/6614121/190011917-c7a3a181-a436-4806-bcf1-47fa0750a80a.png)

This Dockerfile is tested in the CI to validate that it builds, and that it print the pandas versions :  

https://github.com/pandas-dev/pandas/blob/78a5f7193cfc05640f83818cff0ee586a61ff3be/.github/workflows/code-checks.yml#L132

However, this dev environment is not tested to determine if it can run all the unit tests.

### Feature Description

The Docker dev environment test should be that it passes at least tests ran in the `test_fast.sh` file.

**Comment by theoniko** [comment]
Hello,
I had  a look to this issue. Does it mean we need to add add only the following in code-checks.yml
    - name: Test
      uses: ./.github/actions/run-tests
Does it need to run some other shell file called fast_test.sh? Btw such file does not exist...

**Comment by adrienpacifico** [comment]
@theoniko fast_test.sh has been deleted by https://github.com/pandas-dev/pandas/pull/48958

> Does it mean we need to add add only the following in code-checks.yml

I think that you need to do more than that, currently if I launch the devcontainer from the github URL, the test suite does not even start.

**Comment by theoniko** [comment]
You are right. I checked the logs and i see the problem
![image](https://user-images.githubusercontent.com/28800819/229692489-bbcb9a14-7ee4-4662-bc88-85108a16dd62.png)

**Comment by mroeschke** [comment]
> For the test suite you are right. I checked the logs and i see the problem

That indicates that the C extensions have not been built

As mentioned in https://github.com/pandas-dev/pandas/pull/52349#pullrequestreview-1369541866, the development container is just for development and is not used in our CI to set the environment and run tests necessarily so I think it would be overkill to also run the same tests in the container as the CI. I think the current check showing that the environment is available is sufficient so closing
