### ISSUE TITLE
DOC: Remove and merge docs/pandas-ecosystem to community/ecosystem

### ISSUE THREAD

**Issue by raybellwaves** [pandas-dev/pandas#48547]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/community/ecosystem.html (https://github.com/pandas-dev/pandas/blob/main/web/pandas/community/ecosystem.md)
https://pandas.pydata.org/docs/ecosystem.html#pandas-ecosystem (https://github.com/pandas-dev/pandas/blob/main/doc/source/ecosystem.rst)

### Documentation problem

Duplicated documentation pages. See https://github.com/pandas-dev/pandas/pull/48534#pullrequestreview-1107051254 for more reference

### Suggested fix for documentation

Remove https://pandas.pydata.org/docs/ecosystem.html#pandas-ecosystem and merge it into https://pandas.pydata.org/community/ecosystem.html

**Comment by datapythonista** [comment]
#43001 seems to be related

**Comment by Parth9187** [comment]
I'd love to help

**Comment by rootsmusic** [comment]
@raybellwaves The link for ecosystem.rst (under "Location of the documentation") seems to be wrong.

**Comment by sqali** [comment]
Hi @lithomas1 ,

I can see that the pandas documentation on the website *https://pandas.pydata.org/docs/ecosystem.html#pandas-ecosystem* has not been updated for issue #53451. What is the path of the file so I can correct it? Please see the below screenshot.

![image](https://github.com/pandas-dev/pandas/assets/66676360/396e6f0f-d6c1-4935-b22a-7d57d7130a6a)

Thanks & Regards

**Comment by lithomas1** [comment]
You can change the dropdown from 2.0.3 to dev.

The stable documentation is only updated on releases.

**Comment by rootsmusic** [comment]
@lithomas1 For the dev version, there's no doc as referenced in this issue.  Does that mean that this issue can be closed when the dev version replaces 2.0.3?

**Comment by lithomas1** [comment]
Never mind, 
it seems to be updated here https://pandas.pydata.org/community/ecosystem.html.

I think I see what's going on now. There used to be a file ecosystem.rst that got deleted in
https://github.com/pandas-dev/pandas/pull/52944/files
(which was merged for 2.1)

**Comment by rootsmusic** [comment]
@lithomas1  I see it at https://github.com/pandas-dev/pandas/blob/318bed9f7c16c3352178cbf68e8dddfaba32ed6d/doc/source/ecosystem.rst (which version?)

**Comment by lithomas1** [comment]
Since it got deleted, it doesn't need to be updated.

Right now, we're kind of in an awkward spot of where the old ecosystem.rst is in the stable docs still (since it did exist on the 2.0.x branch), but everything should fix itself when 2.1 gets released.
