### ISSUE TITLE
PERF: Reading a single parquet partition takes as much time as reading all partitions.

### ISSUE THREAD

**Issue by fny** [pandas-dev/pandas#48549]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this issue exists on the main branch of pandas.

### Reproducible Example

I expected to speed up a pipeline by reading a single partition instead of 100 for a 30GB data set... but oddly, it takes the same amount of time read in the whole data set as it does a single partition...

<img width="869" alt="image" src="https://user-images.githubusercontent.com/346068/190206560-f4929032-ef00-4490-8575-fdb084c2bf5b.png">

So I switched to using pyarrow directly, and the partition was read in 1.02s.

```
import pyarrow.parquet as pq
parquet_file = pq.ParquetDataset(cleaned_data_path('medications.parquet/partition=0'))
parquet_file.read().to_pandas()
```

Using pyarrow as the engine on pandas brought the read time down to 3s... but still... the default read_parquet should not take over a minute.

### Installed Versions

Okay I lied... I can only verify this happens on 1.4.2. I can't upgrade on the system where this happens, but reading through the changelog, it doesn't look like anything should have changed this up to 1.4.4. I am running the latest version of Arrow.

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.9.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-1160.76.1.el7.x86_64
Version          : #1 SMP Tue Jul 26 14:15:37 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.2
numpy            : 1.21.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 61.2.0
Cython           : 0.29.28
pytest           : 7.1.1
hypothesis       : 6.54.5
sphinx           : 4.4.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.8.0
html5lib         : None
pymysql          : None
psycopg2         : 2.9.3
jinja2           : 2.11.3
IPython          : 8.2.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.4
brotli           : 
fastparquet      : None
fsspec           : 2022.02.0
gcsfs            : None
markupsafe       : 2.0.1
matplotlib       : 3.5.1
numba            : 0.55.1
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 9.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
snappy           : 
sqlalchemy       : 1.4.32
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : 0.20.1
xlrd             : 2.0.1
xlwt             : None
zstandard        : None

</details>

**Comment by rhshadrach** [comment]
> So I switched to using pyarrow directly, and the partition was read in 1.02s.

> but still... the default read_parquet should not take over a minute.

I believe `read_parquet` either needs pyarrow or fastparquet. Am I correct in saying that by "the default" you mean when you use fastparquet? The packages in the OP list out None for fastparquet.

**Comment by fny** [comment]
Right now, I have pyarrow installed.  When I say by "default" I mean when the engine is not explicitly set.

 - `pd.read_parquet(cleaned_data_path('medications.parquet/partition=0'))` runs like a complete brick
 - `pd.read_parquet(cleaned_data_path('medications.parquet/partition=0'), engine="pyarrow")` runs fine

**Comment by rhshadrach** [comment]
Thanks for the reply. Looking through the code in 1.4.2, pandas only uses the `engine` argument `get_engine` to determine whether to use pyarrow or fastparquet. So this is puzzling indeed.

Is you data stored locally, or is it possibly a mounted network drive or remote resource? In either case, would you be able to confirm you're able to reproduce. Also, are you able to share the dataset? If you can reduce the partitions to where there is a reproducible difference in time (even if very small - I'd guess the expected difference between specifying engine and not is on the order of microseconds), that would help give the file size down.

**Comment by fny** [comment]
It's very sensitive data (hospital stuff), let me see if I can recreate the
issue.

**Comment by phofl** [comment]
Closing for now, please ping to reopen when you can provide an example
