### ISSUE TITLE
CI/TST: Enable `-W error:::pandas` in pytest during CI runs

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#48553]
In order to avoid introducing a warning originating from pandas that may be unwanted/false positive in another part of the API (https://github.com/pandas-dev/pandas/pull/48397), the test suite should run with `-W error:::pandas` to error such that they can be addressed. This will also help reduce the noise in the test run logs.

Might be good to add this all the way in `pyproject.toml` in `adopts`.

**Comment by phofl** [comment]
Sounds good! But we have a bunch of warnings right now we have to fix before enabling this

**Comment by theoniko** [comment]
Hello all,
could i work on it_

**Comment by phofl** [comment]
We have to fix the warnings before we can enable this. You have to run all tests to determine where the warnings are shown

**Comment by mroeschke** [comment]
Agreed, a good first step would be to catch or fix the tests where the warnings appear. Specifically you can view the logs of test runs in the CI and address the test warnings that appear e.g: https://github.com/pandas-dev/pandas/actions/runs/3558958743/jobs/5977992575

**Comment by mroeschke** [comment]
Yeah exactly

**Comment by theoniko** [comment]
How shall i fix /home/runner/micromamba/envs/test/lib/python3.8/site-packages/botocore/httpsession.py:41: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680 since it is from another python module?

**Comment by jorisvandenbossche** [comment]
@theoniko that's a warning that is generated by an external package, not by pandas itself. The goal here of this issue to ensure we have no warnings of pandas itself (and error for this if it happens, to ensure our own tests don't generate warnings). 

Now, also for external warnings, it is nice if they get fixed or suppressed (if we can't fix them ourselves in the tests).
