### ISSUE TITLE
BUG: Groupby for Series fails if an entry of the index of the Series is equal to the name of the index

### ISSUE THREAD

**Issue by sebklein** [pandas-dev/pandas#48567]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

# This works as expected.
series1 = pd.Series(data=[1.0, 2.0, 3.0, 4.0], name='values', index=pd.Index(['foo', 'foo', 'bar', 'baz'], name='blah'))
series1.groupby('blah').sum()

# This raises ValueError("Grouper for 'blah' not 1-dimensional")
series2 = pd.Series(data=[1.0, 2.0, 3.0, 4.0, 5.0], name='values', index=pd.Index(['foo', 'foo', 'bar', 'baz', 'blah'], name='blah'))
series2.groupby('blah').sum()

# This raises ValueError("cannot reindex on an axis with duplicate labels")
series3 = pd.Series(data=[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], name='values', index=pd.Index(['foo', 'foo', 'bar', 'baz', 'blah', 'blah'], name='blah'))
series3.groupby('blah').sum()
```

### Issue Description

Consider a pandas Series whose index consists of strings, and whose values are floats. We want to use groupby().sum() to sum up the entries which have the same index string. 

When one of the strings in the index is equal to the name of the index ('blah' in the Reproducible Example above), a ValueError() is raised. The error message that is raised with ValueError() is different, depending on whether there is exactly one row in the series whose index string matches the name of the index, or there are at least two such rows. If there is exactly one such row, as for series2 in the Reproducible Example above, the error message is "Grouper for 'blah' not 1-dimensional". If there are two or more such rows, as for series3 in the Reproducible Example above, the error message is "cannot reindex on an axis with duplicate labels". The example of series1 shows that when there are no rows where the index string matches the name of the index, the sums are properly calculated.

This error occurs both in the current version 1.5.0rc0 and in the earlier version 1.4.1.

### Expected Behavior

I would expect that the sums of groupby() index groups for a Series are computed correctly and without raising an exception, regardless of whether there are rows whose index value matches the name of the index, or not. 

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 224458ee25d92ccdf289d1ae2741d178df4f323e
python           : 3.9.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.0-8-amd64
Version          : #1 SMP Debian 5.10.46-2 (2021-07-20)
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : de_DE.UTF-8
LOCALE           : de_DE.UTF-8
pandas           : 1.5.0rc0
numpy            : 1.23.3
pytz             : 2021.1
dateutil         : 2.8.1
setuptools       : 57.0.0
pip              : 21.1.2
Cython           : 3.0.0a9
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.9.1
jinja2           : 3.1.2
IPython          : 7.26.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
brotli           : None
fastparquet      : 0.7.2
fsspec           : 2021.11.1
gcsfs            : None
matplotlib       : 3.4.2
numba            : 0.53.1
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 6.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
snappy           : None
sqlalchemy       : 1.4.22
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : 2021.5

</details>

**Comment by rhshadrach** [comment]
Thanks for the report @sebklein! Confirmed on main as well, agreed this is a bug. Further investigations and PRs to fix are most welcome.

**Comment by JanVHII** [comment]
Hi,
analyzing the bug, I think the following small change would solve the issue:

```
diff --git a/pandas/core/groupby/grouper.py b/pandas/core/groupby/grouper.py
index 5fc713d84e..9281040a79 100644
--- a/pandas/core/groupby/grouper.py
+++ b/pandas/core/groupby/grouper.py
@@ -875,7 +875,7 @@ def get_grouper(
             exclusions.add(gpr.name)
 
         elif is_in_axis(gpr):  # df.groupby('name')
-            if gpr in obj:
+            if not isinstance(obj, Series) and gpr in obj:
                 if validate:
                     obj._check_label_or_level_ambiguity(gpr, axis=axis)
                 in_axis, name, gpr = True, gpr, obj[gpr]
```
From my point of view "gpr in obj" does not make sense for series at this point. I think the if-statement is written for dataframes to look if gbr is one of the columns. Skipping the if-statement for series gives the correct results for the examples above. The testsuite for series and groupby runs without errors after the change. 

Since this is my first contribution to pandas, I would like to know if there are any other tests I should do before trying to commit the bugfix.
