### ISSUE TITLE
Add the OpenSSF Scorecard GitHub Action

### ISSUE THREAD

**Issue by pnacht** [pandas-dev/pandas#48566]
Hello, I'm working on behalf of Google and the [OpenSSF][ossf] to improve the supply-chain security of essential open-source projects. The OpenSSF is a non-profit foundation dedicated to improving the security of the open-source community. It counts GitHub as a founding [member][ossf-membership].

The [Scorecard][sc] system combines dozens of automated checks to let maintainers better understand their project's supply-chain security posture. It is developed by the OpenSSF, with [direct support from GitHub][sc-blog].

Given pandas' ubiquity within the Python data-science ecosystem, the OpenSSF has included it in its list of the 100 most critical open-source projects. I see Scorecards was already referenced in PR #47652, which improved one aspect of pandas' supply-chain security.

However, the OpenSSF has also developed the [Scorecard GitHub Action][sc-gha], which adds the results of its checks to the project's [security dashboard](https://github.com/pandas-dev/pandas/security), as well as suggestions on how to solve any issues (see examples below). Optionally, it can also publish your results to the OpenSSF REST API, which allows a [badge][badge] with the project's score to be added to its README.

This Action has been adopted by 1600+ projects already. But adding pandas would single-handedly be a step change to the entire Python data-analysis ecosystem's supply-chain security.

Would you be interested in a PR which adds this Action?

![Code scanning dashboard with multiple alerts, including Code-Review and Token-Permissions][img-security]

![Detail of a Token-Permissions alert, indicating the specific file and remediation steps][img-detail]

[badge]: https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/
[ossf]: https://openssf.org/
[ossf-membership]: https://openssf.org/about/members/
[sc]: https://github.com/ossf/scorecard
[sc-blog]: https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/
[sc-gha]: https://github.com/ossf/scorecard-action
[img-security]: https://user-images.githubusercontent.com/15221358/190419615-c2e7677f-e7a9-45f8-8004-a0c13ba848b4.png
[img-detail]: https://user-images.githubusercontent.com/15221358/190415254-4255587e-87fe-4ce9-ad64-955ad882b1b3.png

**Comment by mroeschke** [comment]
Sure a PR would be welcome.

**Comment by MarcoGorelli** [comment]
@pnacht this is currently failing on the builds on `main`, any idea why?

**Comment by fangchenli** [comment]
Reopening this to propose re-enabling OpenSSF Scorecard.
