### ISSUE TITLE
CI: Matplotlib 3.6 broke our builds

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#48602]
The version is only pulled on arm builds now, hence only those fail

https://app.circleci.com/pipelines/github/pandas-dev/pandas/16140/workflows/031dcf5b-bf77-40f0-9126-d32a20ba8863/jobs/46971

**Comment by rhshadrach** [comment]
In #48580 I saw the same failure on other builds

https://github.com/pandas-dev/pandas/actions/runs/3071594332/jobs/4965256242

**Comment by phofl** [comment]
Yep, looks like we are pulling the new matplotlib everywhere

Opened https://github.com/pandas-dev/pandas/pull/48601

**Comment by mroeschke** [comment]
Looks like we are successfully testing with matplotlib 3.6 now so closing
