### ISSUE TITLE
DOC: dev docs left side has no line breaks

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#48605]
https://pandas.pydata.org/pandas-docs/dev/reference/index.html

I'm seeing:

![image](https://user-images.githubusercontent.com/45562402/190860208-15785da3-25ff-41aa-8111-0e3d01cea660.png)

I presume this will impact the release, tagging as 1.5. Haven't had a chance to investigate what happened.

**Comment by rhshadrach** [comment]
Not sure if this is related, but there is also on odd checkbox appearing on certain pages:

https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.api.extensions.register_extension_dtype.html

![image](https://user-images.githubusercontent.com/45562402/190860311-af4bae86-f783-4f2a-ad18-74dc26dba768.png)

**Comment by foram-chandra** [comment]
@rhshadrach I would like to give it a shot :)

**Comment by rhshadrach** [comment]
I've verified that last built docs in #48285 have this issue (you can download the docs as an artifact from the docs build). Pinning back to pydata-sphinx-theme==0.9.0 and reverting the change to sidebar-nav-bs.html from that PR fixes the sidebar issues. I'm currently seeing if we can fix without the reverts.

**Comment by rhshadrach** [comment]
Thanks @foram-chandra! You're certainly welcome to, and please report any progress here or put up a PR. However, since this impact the release scheduled for tomorrow, I (and possibly others) will be working on this in tandem.

**Comment by foram-chandra** [comment]
@rhshadrach thanks for replying back. Since it is a high priority issue and I am new to pandas, I will find another issue to work on :)

**Comment by rhshadrach** [comment]
This issue seems to be sidebar-nav-bs.html; removing this file gives us the new pydata-sphinx-theme sidebar and a quick check looks great. Putting up a PR and doing more thorough checking.
