### ISSUE TITLE
DOC: `value_counts` description doesn't match code logic

### ISSUE THREAD

**Issue by maciejskorski** [pandas-dev/pandas#48635]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

[dev docs](https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.value_counts.html)

[last release docs](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.value_counts.html)

### Documentation problem

`value_counts` utility incorrectly claims counting "unique rows", respectively "unique combinations".

In reality, it only does `groupby` followed by `size`, no `nunique`:

https://github.com/pandas-dev/pandas/blob/ca60aab7340d9989d9428e11a51467658190bb6b/pandas/core/frame.py#L6468-L6592

### Suggested fix for documentation

Align the doc string to match the code logic.

I suggest not to mention "unique rows" or "unique combinations" and maybe mention the equivalence to `groupby`+`size` with the optional `normalization`.

Will be happy to submit a PR for that, or share my two cents in the discussion.

**Comment by maciejskorski** [comment]
Cool. I am reporting this as I have seen quite a few people confused by the behaviour. Let me know if I can be of any help (review, discuss).

**Comment by WooilKim** [comment]
@maciejskorski 
Thanks.
I'll share the progress soon.

**Comment by phofl** [comment]
I don't understand the issue here. Why do you think that value_counts does not count unique rows? That this is done via groupby is an implementation detail that should not be visible in the docs

**Comment by rhshadrach** [comment]
Thanks for the report! I think we should stick to a description that doesn't rely on other parts of pandas (e.g. groupby) as much as possible. Otherwise it may be difficult for new users to understand what this method should do.

> value_counts utility incorrectly claims counting "unique rows", respectively "unique combinations".

This is not how I read the docstring, but I can see that it can be interpreted that way! To me, `Return a Series containing counts of unique rows in the DataFrame.` means "For each unique row in the DataFrame, report the number of times it occurs".

What about something like:

> Return a Series containing the number of times each unique row occurs in the DataFrame.

**Comment by maciejskorski** [comment]
> Thanks for the report! I think we should stick to a description that doesn't rely on other parts of pandas (e.g. groupby) as much as possible. Otherwise it may be difficult for new users to understand what this method should do.
> 
> > value_counts utility incorrectly claims counting "unique rows", respectively "unique combinations".
> 
> This is not how I read the docstring, but I can see that it can be interpreted that way! To me, `Return a Series containing counts of unique rows in the DataFrame.` means "For each unique row in the DataFrame, report the number of times it occurs".
> 
> What about something like:
> 
> > Return a Series containing the number of times each unique row occurs in the DataFrame.

Better to my taste! This wording better separates “unique row” from “occurrences”.
Otherwise, it was too close to “unique occurrences” aka “count distinct”.

Maybe even "unique row -> unique row value". This. emphasizes counting of row values (tuples), rather than rows themselves (row can be seen unique by indexing).

**Comment by rhshadrach** [comment]
> Also, row value is a well-known term (from SQL standard).

But I don't believe it is used much in pandas - the two occurrences I see in the docs both explain the term. It seems better to me to indicate the index is ignored rather than using this terminology.

**Comment by maciejskorski** [comment]
> 

I don't insist. I acknowledge that `pandas` is used by people with different backgrounds.

So please re-read my request as asking for clearly decoupling “unique” and “count”, that would do the job.

Sorry for that verbose communication, but I come with research background where the choice of words means a lot :-)

**Comment by adejumoridwan** [comment]
I would like to take on this issue

**Comment by dbalagula** [comment]
Take, if still available

**Comment by adejumoridwan** [comment]
take

**Comment by adejumoridwan** [comment]
Take
