### ISSUE TITLE
DOC: Sticky Headers in Table Visualization is broken in v1.5.0

### ISSUE THREAD

**Issue by tehunter** [pandas-dev/pandas#48644]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/version/1.5.0/user_guide/style.html#Sticky-Headers

### Documentation problem

Here is how the DataFrame looks in v1.5.0 documentation:
![image](https://user-images.githubusercontent.com/7980666/191111779-c618f44a-3f8e-4735-84bc-a15bb16df0d1.png)

Here is how it looked in v1.4.4 documentation:
![image](https://user-images.githubusercontent.com/7980666/191111849-c4a606af-dccd-4063-96ae-d6f25fd6e1d1.png)

I'm using Firefox 104

### Suggested fix for documentation

It seems that `pydata-sphinx-theme.css`  is applying `width: fit-content;` to all tables. This should be overridden for this wide table.

This seems to be related to #48285

**Comment by WooilKim** [comment]
take

**Comment by WooilKim** [comment]
Let me handle this.

**Comment by WooilKim** [comment]
take

**Comment by WooilKim** [comment]
I have a question.
Where can I find the document file in the repository?
I can not find it in docs directory.
Thanks.

**Comment by attack68** [comment]
pandas/docs/source/user_guide/style.ipynb

**Comment by attack68** [comment]
It seems like the whole notebook is mishandled, not just `set_sticky`.

**Comment by WooilKim** [comment]
@attack68 
Thanks. I agree.

**Comment by WooilKim** [comment]
@attack68
I'm in hard time finding the css "fit-content". I think it is not in the style.ipynb file.
Can you give me an advice which file should I look into?
Thanks.

**Comment by attack68** [comment]
FWIW I have detected that if one removes the `width: fit-content;` CSS attribute value pair from the default `pydata-sphinx-theme.css` then this page all works as previously. The previous 1.4.x pydata-sphinx-theme.css did not seem to have this `width` value set.

![Screenshot 2022-11-20 at 15 21 58](https://user-images.githubusercontent.com/24256554/202907549-67cb5ad0-73cf-4997-83ee-6d737f181ab5.png)

An alternative solution to avoid tampering with the global pydata-sphinx-theme might be to try to encode an overwrite specifically on the userguide ipynb page. But I don't know how to do either of these at present
