### ISSUE TITLE
BUG: regression in read_csv reading from file stream with encoding

### ISSUE THREAD

**Issue by coroa** [pandas-dev/pandas#48646]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import tempfile

with tempfile.NamedTemporaryFile("wt", encoding="utf-8", delete=False) as f:
    f.write("### DATA\nkey,value\ntables,rectangular\n")

with open(f.name, 'r', encoding="utf-8") as fin:
    fin.readline()
    pd.read_csv(fin)
```

### Issue Description

Fails in `TextReader.__cinit__` with `EmptyDataError` in pandas `1.5.0`, while it completed correctly in `1.4.4`. Using the system default encoding of `"UTF-8"` (uppercase) completes correctly as well (as does omitting the `encoding` argument in `open`).

```python
File ~/.local/conda/envs/datatoolbox_test/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py:92, in CParserWrapper.__init__(self, src, **kwds)
     89     kwds.pop(key, None)
     91 kwds["dtype"] = ensure_dtype_objs(kwds.get("dtype", None))
---> 92 self._reader = parsers.TextReader(src, **kwds)
     94 self.unnamed_cols = self._reader.unnamed_cols
     96 # error: Cannot determine type of 'names'

File ~/.local/conda/envs/datatoolbox_test/lib/python3.8/site-packages/pandas/_libs/parsers.pyx:554, in pandas._libs.parsers.TextReader.__cinit__()

EmptyDataError: No columns to parse from file
```

### Expected Behavior

No raise. `pd.read_csv` reads in table.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763
python           : 3.8.13.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.6.0
Version          : Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.5.0
numpy            : 1.23.3
pytz             : 2022.2.1
dateutil         : 2.8.2
setuptools       : 65.3.0
pip              : 22.2.2
Cython           : None
pytest           : 7.1.3
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.5.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.0
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : 0.8.10
xarray           : 2022.6.0
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None
tzdata           : None

</details>

**Comment by twoertwein** [comment]
I can confirm that it works on 1.4.4 (`engine="c"` and `"python"`) and fails on 1.5.0  for `engine="c"` but works with `engine="python"`.

I must admit I slightly prefer the failure with the c-engine in 1.5.0. After `.readline()` the position of the file handle reached the end and should therefore correctly be empty. If you add `fin.seek(0)` before the `read_csv` call, it works.

**Comment by phofl** [comment]
Can confirm

commit 9292530c9eadd70fbff68a3e71c2fc2bea10b3d9
Author: Torsten Wörtwein <twoertwein@users.noreply.github.com>
Date:   Mon May 30 16:45:01 2022 -0400

    CLN: Simplify mmap code (#47175)

cc @twoertwein

**Comment by twoertwein** [comment]
I assume that this shortcut (to make `read_csv`+mmap faster) is causing an issue:
https://github.com/pandas-dev/pandas/blob/5550fd982d5e4a8bf17eced76179513be8ed8170/pandas/io/parsers/c_parser_wrapper.py#L79

In this example
```
(Pdb) src.tell()
9
(Pdb) src.buffer.tell()
38
```
`TextIOWrapper` seems to have read-ahead (since its internal buffer is already at the end).

The following seems to fix this issue `src.seek(src.tell())` but I don't know whether that is a good solution.
