### ISSUE TITLE
QST: pd.series indexing True auto 0 change

### ISSUE THREAD

**Issue by sc303030** [pandas-dev/pandas#48653]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/73783112/1-4-4-other-1-5-0-pd-series-indexing-true-auto-0-change

### Question about pandas

```python
test = pd.Series({True: 0, False: 0})

1.4.4
print(test[0])
> 0

but 
1.5.0
print(test[True])

> keyerror 0
```

1.4.4 and 1.5.0 What has changed?I can't find it

**Comment by phofl** [comment]
Hi, thanks for your report. ``test[True]`` works for me while ``test[0]`` does not. We are now supporting a boolean index, see #45061

@jbrockmendel I guess this is the correct behavior now?

**Comment by jbrockmendel** [comment]
test.loc[1] should definitely raise, but it may be that test.index._should_fallback_to_positional should be True, in which case the `__getitem__` call should still work (but would have different behavior on `test[::-1]`)
