### ISSUE TITLE
BUG: None value converted to NaN in Series

### ISSUE THREAD

**Issue by stephanecollot** [pandas-dev/pandas#48665]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
>>> import pandas as pd
>>> s = pd.Series(['a', 'b'])
>>> s
0    a
1    b
dtype: object
>>> s['a'] = None
>>> s
0      a
1      b
a    NaN
dtype: object
```

### Issue Description

In 1.5.0 there is a behaviour change, if you set a value on a Serie to None it is replaced with NaN.

Same thing with `s.loc['dd'] = None`

### Expected Behavior

It should stay None

### Installed Versions

<details>
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : 9a607e2afa549a9295db09ad05df6572c1a85542
python           : 3.8.13.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.6.0
Version          : Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.6.0.dev0+165.g9a607e2afa
numpy            : 1.22.3
pytz             : 2021.3
dateutil         : 2.8.2
setuptools       : 56.0.0
pip              : 22.0.4
Cython           : 0.29.32
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.16.1
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 0.8.7
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 3.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : 0.3.5
scipy            : 1.5.4
snappy           : None
sqlalchemy       : 1.4.32
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by phofl** [comment]
Can confirm (as I expected :))

```
commit bd9a6f09264c58ef402d4c7faf5fc9d48c159194
Author: Patrick Hoefler <61934744+phofl@users.noreply.github.com>
Date:   Sat Jul 2 00:18:05 2022 +0200

    BUG: Series.setitem losing precision when enlarging (#47342)
```

I'll look into this
