### ISSUE TITLE
ValueError: Could not convert object to NumPy datetime

### ISSUE THREAD

**Issue by Supriyapattar123** [pandas-dev/pandas#48679]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

ValueError                                Traceback (most recent call last) <ipython-input-57-dcd2f8448240> in <module>      33     vac_strt_end = [vdf.loc[vdf['CAREGIVERID'] == cg]["START_DATE"], vdf.loc[vdf['CAREGIVERID'] == cg]["END_DATE"]]      34     if not(vac_strt_end[0].empty) and not(vac_strt_end[1].empty) : ---> 35         vac_days = np.arange(vac_strt_end[0], vac_strt_end[1], dtype = 'datetime64[D]')      36         for d in np.union1d( schedule_days, vac_days):      37             idx = np.where(d = schedule_days)[0]  ValueError: Could not convert object to NumPy datetime

### Question about pandas

ValueError                                Traceback (most recent call last)
<ipython-input-57-dcd2f8448240> in <module>
     33     vac_strt_end = [vdf.loc[vdf['CAREGIVERID'] == cg]["START_DATE"], vdf.loc[vdf['CAREGIVERID'] == cg]["END_DATE"]]
     34     if not(vac_strt_end[0].empty) and not(vac_strt_end[1].empty) :
---> 35         vac_days = np.arange(vac_strt_end[0], vac_strt_end[1], dtype = 'datetime64[D]')
     36         for d in np.union1d( schedule_days, vac_days):
     37             idx = np.where(d = schedule_days)[0]

ValueError: Could not convert object to NumPy datetime

**Comment by MarcoGorelli** [comment]
Hi - please post a reproducible example, see

https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

for how

**Comment by MarcoGorelli** [comment]
closing, will reopen if you address the above
