### ISSUE TITLE
DOC: search is missing in the published 1.5 docs

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#48680]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/

### Documentation problem

The search functionality that appears in 1.4 docs is missing in the new styling for 1.5.
Here is 1.5:

![image](https://user-images.githubusercontent.com/15113894/191502295-51d5daaa-6073-4c7e-a83d-bc9229fd15c3.png)

Here is 1.4:
![image](https://user-images.githubusercontent.com/15113894/191502330-25225b5a-6b19-45f6-ace7-5d7ce574ece2.png)

### Suggested fix for documentation

No ideas here...

**Comment by Usama3627** [comment]
In 1.5, the search exists on the top-right side next to the version change dropdown.

Tested it and it performs the same search as the 1.4.

<img width="371" alt="Screenshot 2022-09-21 at 5 56 18 PM" src="https://user-images.githubusercontent.com/31164069/191509577-c056cb8a-1560-423c-85bd-06812dab5f63.png">

**Comment by Dr-Irv** [comment]
Thanks. I was so used to it being on the left!
