### ISSUE TITLE
pandas read int contain null will be float type

### ISSUE THREAD

**Issue by wonb168** [pandas-dev/pandas#48704]
```python
df=pd.read_sql(sql,conn)
df.dtypes
```
a    float64, and values:
0	NaN
1	3.0
2	2.0
and 3 changed to 3.0, then can't write back to db.
why pandas do this? another python package datatable also remain int ,
0 
1     3
2     2

**Comment by phofl** [comment]
Hi, thanks for your report. We don't support automatic conversion to nullable dtypes in every io function yet.
