### ISSUE TITLE
BUG: DataFrame.plot(kind='scatter') does not raise KeyError when unknown colormap is applied 

### ISSUE THREAD

**Issue by lisphilar** [pandas-dev/pandas#48726]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
iris = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
iris.plot(x='sepal_length', y='sepal_width', colormap='unknown')
# -> TypeError raised as expected
iris.plot(x='sepal_length', y='sepal_width', colormap='unknown', kind='scatter')
# -> TypeError is expected but not raised at version 1.5.0
```

### Issue Description

`.plot(..., colormap='unknown')` raises `TypeError` because the colormap is unknown, but `.plot(..., colormap='unknown', kind='scatter')` does raise `TypeError`.

### Expected Behavior

`.plot(..., cmap='unknown', kind='scatter')` will raise `TypeError`.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763
python           : 3.10.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.16.3-microsoft-standard-WSL2
Version          : #1 SMP Fri Apr 2 22:23:49 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0
numpy            : 1.23.3
pytz             : 2022.2.1
dateutil         : 2.8.2
setuptools       : 65.3.0
pip              : 22.2.2
Cython           : None
pytest           : 7.1.3
hypothesis       : None
sphinx           : 5.1.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.5.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.0
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 9.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.1
snappy           : None
sqlalchemy       : 1.4.41
tables           : None
tabulate         : 0.8.10
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by phofl** [comment]
This will raise a Waring with the newest matplotlib, since colormap has no effect in that scenario, even if a valid value is passed

**Comment by lisphilar** [comment]
Thank you for your information and pull request!
