### ISSUE TITLE
DOC: typo

### ISSUE THREAD

**Issue by x1001000** [pandas-dev/pandas#48727]
### Pandas version checks

- [x] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://github.com/pandas-dev/pandas/blob/main/pandas/core/groupby/groupby.py#L207)

### Location of the documentation

https://github.com/pandas-dev/pandas/blob/main/pandas/core/groupby/groupby.py#L207

### Documentation problem

typo

### Suggested fix for documentation

have -> and

**Comment by kamiwis** [comment]
take

**Comment by MarcoGorelli** [comment]
closed in #48731
