### ISSUE TITLE
STYLE: add pylint pre-commit hook

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#48737]
Having pylint in CI would've prevented a bug from entering 1.5.0 https://github.com/pandas-dev/pandas/pull/48736

So let's add pylint as a pre-commit hook

pylint has a _lot_ of options - some duplicative of what's already in `flake8`, others arguably too opinionated, others that we'd like to eventually enable but perhaps not all in one go

So, the task here is:
- add `pylint` to https://github.com/pandas-dev/pandas/blob/main/.pre-commit-config.yaml
- run `pre-commit run pylint --all-files`
- fixup any linting errors which come up. If some linting error would require big changes to lots of files, or refactoring, then it's OK to turn it off for now, see [pylint configuration](https://pylint.pycqa.org/en/latest/user_guide/configuration/index.html)
- once `pre-commit run pylint --all-files` passes, then stage, commit, and push! Feel free to tag me in the PR

**Comment by HebiKotei** [comment]
Would you mind if I took a look at this?

**Comment by MarcoGorelli** [comment]
go ahead, thanks

**Comment by HebiKotei** [comment]
Okay, so at the moment, I have disabled checks for Convention Checks, Refactoring Checks and general warnings (there are far too many to go through).

All that should appear are potential bugs (errors) and fatal errors. I will go through and see what I can do about the bugs that appear, does this sound fine?

**Comment by MarcoGorelli** [comment]
sounds good! can always just add the check with all but a few potential bugs / fatal errors turned off, and then we gradually turn the others on as we fix them in separate PRs

**Comment by HebiKotei** [comment]
Alright then, sounds good, I should be done soon then. I'll submit the PR when ready.

**Comment by HebiKotei** [comment]
https://github.com/pandas-dev/pandas/pull/48759
