### ISSUE TITLE
WEB: Add style for blockquote

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#48758]
Looks like when we have a `<blockquote>` tag in our website, our stylesheet doesn't have a specific style for it, and it's rendered as just a normal text.

Look at the second paragraph in the Implementation section in https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html

It probably makes sense to print it with a left padding, and with a brighter color (or use a bootstrap style, which is probably overwritten by mistake).

**Comment by Himanshuwagh** [comment]
Hey, I can work on this. Is it open? @datapythonista

**Comment by datapythonista** [comment]
Yes, go ahead. Thanks!

**Comment by Himanshuwagh** [comment]
@datapythonista  permission denied while pushing to private branch. Also what is the convention for naming the branch ( if any for this repo)

**Comment by datapythonista** [comment]
You need to fork the repo, push to a branch in your forl, and open a pull request. Name the branch whatever is useful for you.

**Comment by Himanshuwagh** [comment]
@datapythonista  created pull request : https://github.com/pandas-dev/pandas/pull/48770
