### ISSUE TITLE
DOC: Update color of icons for dark theme

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#48762]
The color of our icons in the docs don't look good with the dark theme:

![dark_theme_icons](https://user-images.githubusercontent.com/10058240/192112344-b8625171-cfb1-42a6-890a-8d62d05f134e.png)

It'd be good to edit the svg files and make the color the same as the titles for example, rgb(69, 157, 185).

In the [Getting started](https://pandas.pydata.org/docs/getting_started/index.html) there are couple of icons that don't look good either. For the sql, we could pick a gray that looks good with both the bright and dark themes. For the SAS we may need two images, one with black letters and one with white (the pydata sphinx theme supports having different images for each theme).

Not sure if there is any other part of the docs where images need to be updated, but would be good that docs look good with dark theme everywhere.

**Comment by lorenzovngl** [comment]
Could I be the assignees of this issue?

**Comment by lorenzovngl** [comment]
Could I be the assignee of this issue?

**Comment by datapythonista** [comment]
Sure, thanks for helping with this @lorenzovngl
