### ISSUE TITLE
BUG: `pd.to_datetime()` fails to parse nanoseconds

### ISSUE THREAD

**Issue by gtopper** [pandas-dev/pandas#48767]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

timestamp = '15/02/2020 02:03:04.123456789'
timestamp_format = '%d/%m/%Y %H:%M:%S.%f'
pd.to_datetime(timestamp, format=timestamp_format)
```

### Issue Description

New in 1.5.0 – the following error is raised
```
ValueError: unconverted data remains: 789
```

If dropping nanosecond support was intentional, [the documentation](https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html) was not updated accordingly.

### Expected Behavior

No error raised.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763
python           : 3.8.9.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.6.0
Version          : Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.5.0
numpy            : 1.22.4
pytz             : 2022.2.1
dateutil         : 2.8.2
setuptools       : 65.3.0
pip              : 22.2.2
Cython           : None
pytest           : 5.4.3
hypothesis       : None
sphinx           : 3.5.4
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.31.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2022.8.2
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 6.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : 0.6.0
scipy            : None
snappy           : None
sqlalchemy       : 1.4.29
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by MarcoGorelli** [comment]
Thanks for the report @gtopper - [from git bisect](https://www.kaggle.com/code/marcogorelli/pandas-regression-example?scriptVersionId=106475285), this was due to https://github.com/pandas-dev/pandas/pull/46736
cc @jbrockmendel

**Comment by AlexKirko** [comment]
We should also add test coverage for this. Weird that we missed it.

**Comment by anthonyaag** [comment]
Incidentally just rearranging the date seems to work 
```
timestamp = '2020/02/15 02:03:04.123456789'
timestamp_format = '%Y/%m/%d %H:%M:%S.%f'
pd.to_datetime(timestamp, format=timestamp_format)
```
> `Timestamp('2020-02-15 02:03:04.123456789')`

but fails again if one adds a time zone 
```
timestamp = '2020/02/15 02:03:04.123456789 America/New_York'
timestamp_format = '%Y/%m/%d %H:%M:%S.%f %Z'
pd.to_datetime(timestamp, format=timestamp_format)
```
>`ValueError: time data '2020/02/15 02:03:04.123456789 America/New_York' does not match format '%Y/%m/%d %H:%M:%S.%f %Z' (match)`

which again succeeds if we drop nanos 
```
timestamp = '2020/02/15 02:03:04.123456 America/New_York'
timestamp_format = '%Y/%m/%d %H:%M:%S.%f %Z'
pd.to_datetime(timestamp, format=timestamp_format)
```
> `Timestamp('2020-02-15 02:03:04.123456-0500', tz='America/New_York')`
