### ISSUE TITLE
BUG: `pd.core.algorithms.duplicated` fails with masked Series

### ISSUE THREAD

**Issue by tehunter** [pandas-dev/pandas#48786]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
>>> import pandas as pd
>>> data = pd.Series([0, 1, pd.NA, 1], dtype=pd.Int64Dtype())
>>> pd.core.algorithms.duplicated(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pandas/pandas/core/algorithms.py", line 1061, in duplicated
    return htable.duplicated(values._data, keep=keep, mask=values._mask)
  File "/home/pandas/pandas/core/generic.py", line 5941, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute '_mask'
>>>
```

### Issue Description

On the main branch, when #48150 was implemented to support a masked `ExtensionArray` in the `duplicated` algorithm, it broke the function when a masked `Series` is passed. I believe values should be cast to `values._values` in the case of a Series.

### Expected Behavior

`duplicated` succeeds for `values` of nd.array, ExtensionArray or Series type.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 6b93a0c6687ad1362ec58715b1751912783be411
python           : 3.8.13.final.0
python-bits      : 64
OS               : Linux
OS-release       : 
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : C.UTF-8
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.6.0.dev0+202.g6b93a0c668.dirty
numpy            : 1.22.4
pytz             : 2022.2.1
dateutil         : 2.8.2
setuptools       : 65.3.0
pip              : 22.2.2
Cython           : 0.29.32
pytest           : 7.1.3
hypothesis       : 6.54.6
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.9.1
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : 2.9.3
jinja2           : 3.0.3
IPython          : 8.5.0
pandas_datareader: 0.10.0
bs4              : 4.11.1
bottleneck       : 1.3.5
brotli           :
fastparquet      : 0.8.3
fsspec           : 2021.11.0
gcsfs            : 2021.11.0
matplotlib       : 3.6.0
numba            : 0.55.2
numexpr          : 2.8.3
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : 0.17.8
pyarrow          : 9.0.0
pyreadstat       : 1.1.9
pyxlsb           : 1.0.9
s3fs             : 2021.11.0
scipy            : 1.9.1
snappy           :
sqlalchemy       : 1.4.41
tables           : 3.7.0
tabulate         : 0.8.10
xarray           : 2022.6.0
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : 0.18.0
tzdata           : None

</details>

**Comment by phofl** [comment]
This is not supported according to the type hints there. A bit unfortunate that it is mentioned in the docstring, but I am not aware of a place where we call this as a Series.

**Comment by tehunter** [comment]
Thanks! I should have dug deeper into the type definition.
