### ISSUE TITLE
DEPR: inplace in DataFrameGroupBy.fillna and SeriesGroupBy.fillna

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#48792]
Specifying `inplace` returns an empty frame or a Series with all `None` values, and neither modifies the original input. Instead of fixing this, I think we should deprecate the `inplace` argument of these methods.

```
df = pd.DataFrame({'a': [1, 1, 2], 'b': [np.nan, 3, np.nan]})
gb = df.groupby('a')

print(gb.fillna(0, inplace=True))
# Empty DataFrame
# Columns: []
# Index: []

print(gb['b'].fillna(0, inplace=True))
# a
# 1    None
# 2    None
# Name: b, dtype: object

print(df)
#    a    b
# 0  1  NaN
# 1  1  3.0
# 2  2  NaN
```

**Comment by ambujpawar** [comment]
I am interested in picking up the issue.
Just a question though, how should this deprecation take place? Are we gonna give users warning when they are using inplace? Or inplace as a parameter should be competely removed from the code?

And shouldn't this change be applied to Series.fillna() and DataFrame.fillna() as well?

**Comment by rhshadrach** [comment]
> Are we gonna give users warning when they are using inplace? Or inplace as a parameter should be competely removed from the code?

Any time the user specifies the inplace parameter, a FutureWarning should be raised explaining that this argument will be removed in a future version of pandas with the default, False, being the behavior. You can do this by changing the default argument to `lib.no_default`. Also, a good source is other deprecation PRs: https://github.com/pandas-dev/pandas/pulls?q=is%3Apr+label%3ADeprecate+is%3Aclosed.

> And shouldn't this change be applied to Series.fillna() and DataFrame.fillna() as well?

That's currently being discussed in #16529 and is not in the scope here. The key difference is that `inplace=True` is completely broken in groupby. I can't imagine anyone using it, but there may be users who specify `inplace=False` and their code would break if we just removed it without a deprecation.

**Comment by ambujpawar** [comment]
Thanks! Thats more than enough to get me started.
Thanks a lot again!
