### ISSUE TITLE
DOC: Remove unsupported parameters in `Resampler.mean`

### ISSUE THREAD

**Issue by donghyyun** [pandas-dev/pandas#48803]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.core.resample.Resampler.mean.html

### Documentation problem

According to the [comment](https://github.com/pandas-dev/pandas/issues/48675#issuecomment-1255369994), numba engine hasn't be implemented for `resample`.

However, the reference document says that they are supporting the numba engine.

### Suggested fix for documentation

Please remove 'engine', 'engine_kwargs' in `parameters` section.

**Comment by mhaoda** [comment]
Hi, can I work on this issue ?

**Comment by Pro-Coder04** [comment]
take

**Comment by phofl** [comment]
Feel free, contributions welcome

**Comment by mhaoda** [comment]
> Feel free, contributions welcome

sure, then can you assign it to me?

**Comment by donghyyun** [comment]
@mhaoda
I just wanted to check with the pandas member if the documentation is actually wrong.
I will take this issue.

**Comment by donghyyun** [comment]
take
