### ISSUE TITLE
ENH: support negative axis

### ISSUE THREAD

**Issue by auderson** [pandas-dev/pandas#48802]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

It would be nice if pandas supports negative axis:
```python
pd.DataFrame(np.arange(5)).mean(axis=-1)
```

### Feature Description

This should be easy, only need to extend current `_AXIS_TO_AXIS_NUMBER` with {-1:1, -2:0}

### Alternative Solutions

.

**Comment by jreback** [comment]
we only have 2 axis - so i don't find this useful and somewhat confusing 

-0.5

**Comment by auderson** [comment]
I agree this will make pandas more sophisticated, but in certain cases this can help reduce the amount of code. 
For example, an obj may be a series or frame, and the user want the mean of the series or the row-wise mean of the dataframe, in the second case he can only use axis=1. But if negative axis allowed, he can use axis=-1 for both cases.
Another reason is that numpy supports negative axis as well, so this may not be that confusing for general users?

**Comment by mroeschke** [comment]
I've seen numpy use `axis=-1` to mean "infer", but generally I think pandas should generally move away from being too "smart" this way.

I would be -1 to add more semantics here. I think `isinstance` checking or checking `.ndim` is more explicit and prevents a negative axis from "working but not doing what you expect"

**Comment by MarcoGorelli** [comment]
agreed - let's close then, but thanks for the suggestion
