### ISSUE TITLE
BUG: differences in Series.map with defaultdict with different dtypes

### ISSUE THREAD

**Issue by asishm** [pandas-dev/pandas#48813]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np
from collections import defaultdict

s = pd.Series([1,2, np.nan])
s2 = pd.Series(['a', 'b', np.nan])
d = defaultdict(lambda: "missing", {1:'a', 2:'b', np.nan: 'c'})
d2 = defaultdict(lambda: -1, {'a': 1, 'b': 2, np.nan: 3})

s.map(d)

s2.map(d2)
```

### Issue Description

In the first case the `np.nan` is not replaced with `'c'` but is instead mapped to the default value. 

```python
>>> s.map(d)
0          a
1          b
2    missing
dtype: object
```

in the second case, `np.nan` is correctly replaced with `3` and not `-1`
```python
>>> s2.map(d2)
0    1
1    2
2    3
dtype: int64
```

### Expected Behavior

the first case to output

```python
>>> s.map(d)
0          a
1          b
2          c
dtype: object
```

I know I can use `.fillna` as a workaround - but this seems to be explicitly tested in the case of regular dicts here - https://github.com/pandas-dev/pandas/blob/49d4c075e015b5cec0c334554d9d980ae6bf0224/pandas/tests/apply/test_series_apply.py#L592-L598

but seems to be untested for defaultdicts / objects that implement `__missing__`

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : b3552c54be2d49d52e6c0ae90db23ccb13bbfe0d
python           : 3.8.13.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.128-microsoft-standard
Version          : #1 SMP Tue Jun 23 12:58:10 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0.dev0+1579.gb3552c54be
numpy            : 1.23.3
pytz             : 2022.2.1
dateutil         : 2.8.2
setuptools       : 65.4.0
pip              : 22.2.2
Cython           : 0.29.32
pytest           : 7.1.3
hypothesis       : 6.54.6
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.9.1
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : 2.9.3
jinja2           : 3.0.3
IPython          : 8.5.0
pandas_datareader: 0.10.0
bs4              : 4.11.1
bottleneck       : 1.3.5
brotli           :
fastparquet      : 0.8.3
fsspec           : 2021.11.0
gcsfs            : 2021.11.0
matplotlib       : 3.3.2
numba            : 0.53.1
numexpr          : 2.8.0
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : 0.15.0
pyarrow          : 2.0.0
pyreadstat       : 1.1.9
pyxlsb           : 1.0.9
s3fs             : 2021.11.0
scipy            : 1.9.1
snappy           :
sqlalchemy       : 1.4.41
tables           : 3.7.0
tabulate         : 0.8.10
xarray           : 2022.6.0
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : 0.18.0
tzdata           : None
</details>

**Comment by dannyi96** [comment]
take

**Comment by dannyi96** [comment]
Another observation - noticing that the defaultdict gets updated in the unexpected output example
```
import pandas as pd
import numpy as np
from collections import defaultdict

s = pd.Series([1,2, np.nan])
d = defaultdict(lambda: "missing", {1:'a', 2:'b', np.nan: 'c'})
d #  defaultdict(<function <lambda> at 0x7f5a5cfbb3a0>, {1: 'a', 2: 'b', nan: 'c'})
s.map(d)
d # defaultdict(<function <lambda> at 0x7f5a5cfbb3a0>, {1: 'a', 2: 'b', nan: 'c', nan: 'missing', nan: 'missing'})
```

**Comment by dannyi96** [comment]
This issue seems to be related to the ids of the `nan`, will debug further -

Example - 
```
import pandas as pd
import numpy as np

s = pd.Series([1,2, np.nan]) # dtype is float64
s2 = pd.Series([1,2, np.nan]) # dtype is object

id(s[2]) # 140643342164752
id(s2[2]) # 140643015621008
id(np.nan) # 140643015621008

# Note
id(s2[2]) == id(np.nan) 
id(s[2])  != id(s[2]) 
```

On manually setting `arr[i] = np.nan` here for elements having null --> we get expected result.
https://github.com/pandas-dev/pandas/blob/55dc32437ea43a238975439ddb6c9dda81b33020/pandas/_libs/lib.pyx#L2909-L2912

Am checking what is causing this different id issue for nans.

**Comment by dannyi96** [comment]
the delta in the addresses take place in this layer - 
`floats` and `complexes` are preallocated memory addresses and values are copied/set in it. Hence the different `np.nan` behaviour.

https://github.com/pandas-dev/pandas/blob/55dc32437ea43a238975439ddb6c9dda81b33020/pandas/_libs/lib.pyx#L2533-L2536


https://github.com/pandas-dev/pandas/blob/55dc32437ea43a238975439ddb6c9dda81b33020/pandas/_libs/lib.pyx#L2687-L2692

In other success cases (`pd.Series(['a', 'b', np.nan])` and `pd.Series([1,2, np.nan], dtype='object')` ), the assignment of `floats` to results does not hit, hence no issue there
