### ISSUE TITLE
BUG: `add_categories` does not honour `pd.StringDtype` of new categories (and downcasts to `object` instead)

### ISSUE THREAD

**Issue by bollard** [pandas-dev/pandas#48812]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd


c = pd.Categorical(pd.Series(["a", "b", "a"], dtype=pd.StringDtype()))
c.add_categories(pd.Series(["c", "d"], dtype=pd.StringDtype())).categories.dtype
>>> dtype('O')
```

### Issue Description

Hi,

I've noticed that when adding two different `pd.Categorical` objects (whose `.categories.dtype == pd.StringDtype()`), `add_categories`  will downcast back to `object`.

Interestingly, this doesn't seem to happen with, for example, `pd.Int64Dtype()`:

```python
d = pd.Categorical(pd.Series([1, 2, 1], dtype=pd.Int64Dtype()))
d.add_categories(pd.Series([3, 4], dtype=pd.Int64Dtype())).categories.dtype
>>> dtype('int64')
```

Thanks

### Expected Behavior

```python
import pandas as pd


c = pd.Categorical(pd.Series(["a", "b", "a"], dtype=pd.StringDtype()))
c.add_categories(pd.Series(["c", "d"], dtype=pd.StringDtype())).categories.dtype
>>> string[python]
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763
python           : 3.10.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252

pandas           : 1.5.0
numpy            : 1.23.1
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 63.4.1
pip              : 22.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.5
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : 2.8.3
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None
</details>

**Comment by bollard** [comment]
Have also just noticed similar behaviour with `rename_categories`

```python
c = pd.Categorical(pd.Series(["a", "b", "a"], dtype=pd.StringDtype()))
c.rename_categories({"a": "z"}).categories.dtype
>>> dtype('O')
```

Here I can understand the downcast if I passed, say `{"a": 1}`, but I would have hoped that as `"z"` is compatible with `pd.StringDtype()` a downcast wouldn't be necessary. Again `pd.Int64Dtype` doesn't seem to be affected:

```python
c = pd.Categorical(pd.Series([1, 2, 1], dtype=pd.Int64Dtype()))
c.rename_categories({1: 10}).categories.dtype
>>> dtype('int64')
```

**Comment by phofl** [comment]
Hi, thanks for your report. This does not work for "Int64". The correct result would be ``dtype("Int64")``

**Comment by bollard** [comment]
Ah yes of course it is. Apologies, staring at this for too long but clearly still not looking closely enough
