### ISSUE TITLE
API: what should float(pd.NA) return?

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#48864]
From https://github.com/pandas-dev/pandas/issues/32265, it seems there was broad agreement that pandas should do
```
In [4]: pd.Series([1, 2, pd.NA], dtype='Float64').to_numpy()
Out[4]: array([ 1.,  2., nan])
```

Should `float(pd.NA)` then return `np.nan`?

xref https://github.com/matplotlib/matplotlib/issues/23991#issuecomment-1256438568

**Comment by phofl** [comment]
Just to clarify: The alternative would be to raise for ``float(pd.NA)``? Anything else that should be considered?

**Comment by MarcoGorelli** [comment]
Yeah that's what currently happens
```
In [16]: float(pd.NA)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [16], line 1
----> 1 float(pd.NA)

TypeError: float() argument must be a string or a number, not 'NAType'
```

Not sure what other considerations there are, I'll give this a go and see what happens

**Comment by MarcoGorelli** [comment]
This breaks

https://github.com/pandas-dev/pandas/blob/1b2cc268e485158ca57d1630f558107b2bca725f/pandas/tests/indexes/test_base.py#L855-L862

, though `Float64Index` is deprecated anyway

**Comment by MarcoGorelli** [comment]
from the dev call: it's OK for `float(pd.NA)` to error, conversion to numpy should be handled in `__array__`
