### ISSUE TITLE
value_counts() return null values

### ISSUE THREAD

**Issue by lctammy** [pandas-dev/pandas#48881]
![Screenshot 2022-09-30 at 13 09 10](https://user-images.githubusercontent.com/43069373/193257183-074cdce7-cd41-4342-b303-f5f98a4e1664.png)
But the there is data in the data frame

**Comment by phofl** [comment]
Please provide a reproducible example, see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by MarcoGorelli** [comment]
closing for now, can reopen in you provide a reproducible example as requested above
