### ISSUE TITLE
to_json of df with multi-index header, followed by read_json results in incorrectly formatted column headers

### ISSUE THREAD

**Issue by jnorwood** [pandas-dev/pandas#4889]
cc @Komnomnomnom

I'm using a recent anaconda build on Windows, which includes v 0.12.0 pandas.  I'm attempting to use a multi-index header, write it out to a json file, import it and get the same formatted dataframe.  The column headers come out stacked vertically instead.

import numpy as np
import pandas as pd
pd.set_option('html',False)

index = pd.MultiIndex(levels=[['foo', 'bar', 'baz', 'qux'],
                           ['one', 'two', 'three']],
                   labels=[[0, 0, 0, 1, 1, 2, 2, 3, 3, 3],
                           [0, 1, 2, 0, 1, 1, 2, 0, 1, 2]],
                   names=['foo', 'bar'])
df = pd.DataFrame(np.random.randn(10, 3), index=index,
                  columns=['A', 'B', 'C'])
dft = df.transpose()
dft
dft.to_json('D:\xxmt.json',orient='split')
dftj=pd.read_json('D:\xxmt.json',orient='split')
dftj

**Comment by watsonix** [comment]
Last update to this was 2 years ago. I'm assuming its still open? I have a multi-index situation when I do:
    query_df = pd.read_sql_query(sql_text, db_conn, index_col=['user_id', 'mobile_time'])
and then output via:
    records_json = query_df.to_json(orient='split')    

but then
    pd.read_json(records_json, orient='split')
doesn't work

**Comment by jreback** [comment]
If you want a *more* round-trippable JSON format, this is in upcoming 0.20.0.: http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0200-enhancements-table-schema

**Comment by people-can-fly** [comment]
Or you can just write json with orient = 'table'

`df.to_json(path_or_buf='test.json', orient='table')`

read multi_index json

`pd.read_json('test.json', orient='table')`

**Comment by eddy-geek** [comment]
Here is a fancy hack if you have a good reason not to use `orient='table'` -- in my case it is 3x bigger than `orient='split'`.

Notes:
* index level names are lost by `orient='split'`, even with this
* it will probably break as soon as you use non-basic types (think: dates).

```python
def to_json_split_roundtrip(df):
    if isinstance(df.index, pd.MultiIndex):
        values = [repr(v) for v in df.index.ravel()]
        df = df.set_index(pd.Index(values))
    return df.to_json(orient="split")

def from_json_split_roundtrip(j):
    df = pd.read_json(j, orient="split")
    if df.index[0].startswith('('):
        df.index = pd.MultiIndex.from_tuples((ast.literal_eval(t) for t in df.index))
    return df
```

Example use
```python
df=pd.DataFrame([['1',2,3,4],['1',4,5,6],['7',4,9,10]],columns=["a","b","c","d"]).groupby(["a","b"]).sum()

display(df)
print(df.index)

as_json = to_json_split_roundtrip(df)
# send it around
r = from_json_split_roundtrip(as_json)
display(r)
print(r.index)
```
![image](https://user-images.githubusercontent.com/2772505/79488815-9c6b3c80-801a-11ea-986f-5744345ad363.png)

So, a built-in solution (and/or a more efficient `orient='table'`) is still sorely needed.

**Comment by Helgeb** [comment]
There seems to be a mixup in handling the multiindex columns of read_json and to_json. As a solution you can manually rearrange the multiindex column order in the json data:

```
>>> df = pd.DataFrame({'a':[1,2],'b':[3,4]})
>>> df.columns = pd.MultiIndex.from_tuples([('A','B',),('C','D',)])
>>> print(df)
   A  C
   B  D
0  1  3
1  2  4
>>> json_string = df.to_json(orient='split')
>>> print(json_string)
{"columns":[["A","B"],["C","D"]],"index":[0,1],"data":[[1,3],[2,4]]}
>>> wrong_df = pd.read_json(json_string,orient='split')
>>> print(wrong_df)
   A  B
   C  D
0  1  3
1  2  4
>>> correct_columns = pd.MultiIndex.from_tuples([tuple(c) for c in json.loads(json_string)['columns']])
>>> print(correct_columns)
MultiIndex(levels=[['A', 'C'], ['B', 'D']],
           labels=[[0, 1], [0, 1]])
>>> json_dict = json.loads(json_string)
>>> json_dict['columns'] = list(range(len(json_dict['columns'])))

>>> correct_df = pd.read_json(json.dumps(json_dict),orient='split')
>>> correct_df.columns = correct_columns
>>> print(correct_df)
   A  C
   B  D
0  1  3
1  2  4
```

**Comment by LarsHill** [comment]
The above solution from @Helgeb correctly decodes multi-index dataframes but seems to fail in handling normal single-index dataframes correctly.

I propose a different workaround to correctly decode multi-index dataframes from serialized json strings. Namely, `ast.literal_eval` allows for safely evaluating tuple strings to actual tuples, which lead to correcly decoded dataframes, since `pd.DataFrame` parses `Dict` objects with tuple keys correctly (with multi-index columns). 

```python
import ast
import json

import numpy as np
import pandas as pd


def create_dataframe_from_json(df: str) -> pd.DataFrame:
    """ Decode dataframe from serialized json string.
    Safely evaluates multi-index keys (tuple strings) as tuples before converting dict to dataframe.
    """

    df = json.loads(df)

    parsed_df = {}
    for k, v in df.items():
        try:
            parsed_key = ast.literal_eval(k)
            if not isinstance(parsed_key, tuple):
                parsed_key = k
        except (ValueError, SyntaxError):
            parsed_key = k
        parsed_df[parsed_key] = v

    return pd.DataFrame(parsed_df)


def main():

    inp = [{'c1': 10, 'c2': 100}, {'c1': 11, 'c2': 110}, {'c1': 12, 'c2': 120}]
    df1 = pd.DataFrame(inp)

    df2 = pd.DataFrame(np.random.random((4, 4)))
    df2.columns = pd.MultiIndex.from_product([[1, 2], ['A', 'B']])

    df3 = pd.DataFrame({'a': [1, 2], 'b': [3, 4]})
    df3.columns = pd.MultiIndex.from_tuples([('A', 1,), ('C', 'D',)])

    for df in [df1, df2, df3]:
        # original dataframe
        print(df)

        # serialize to json
        json_str = df.to_json()

        # wrong decoding for multi-index dataframes
        wrong_df = pd.read_json(json_str)
        print(wrong_df)

        # correct decoding from json (also for multi-index dataframes)
        correct_df = create_dataframe_from_json(json_str)
        print(correct_df)


if __name__ == '__main__':
    main()

```

**Comment by jocelyne8** [comment]
I'm not sure what the status is on this issue (I'm stuck on some older version of pandas here), but in case someone else runs into the same issue, I ended up using a variant of @Helgeb 's solution, which also checks both index and column, and supports both MultiIndex and Index. 
This was very minimally tested and does very minimal input checking. Notably:
* if you have both tuples and non-tuples in your index list, you'll end up with a single-level index containing tuples.
* if you have tuples of multiple lengths in your index list, it will probably die? (untested)
* if either index list is empty, it will probably die? (untested)
* if you didn't serialize with `orient="split"`, it will also probably die? (also untested)

```python
def deserialize_multiindex_dataframe(dataframe_json: str) -> pd.DataFrame:
    """Deserialize the dataframe json into a dataframe object.
    The dataframe json must be generated with DataFrame.to_json(orient="split")
    This function is to address the fact that `pd.read_json()` isn't behaving correctly (yet)
    https://github.com/pandas-dev/pandas/issues/4889
    """
    def convert_index(json_obj):
        to_tuples = [tuple(i) if isinstance(i, list) else i for i in json_obj]
        if all(isinstance(i, list) for i in json_obj):
            return pd.MultiIndex.from_tuples(to_tuples)
        else:
            return pd.Index(to_tuples)
    json_dict = json.loads(dataframe_json)
    columns = convert_index(json_dict['columns'])
    index = convert_index(json_dict['index'])
    dataframe = pd.DataFrame(json_dict["data"], index, columns)
    return dataframe
```
