### ISSUE TITLE
DOC: IntervalIndex.from_arrays() and IntervalIndex.from_breaks() and IntervalIndex.from_tuples() missing description of name parameter

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#48911]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

- https://pandas.pydata.org/docs/reference/api/pandas.IntervalIndex.from_arrays.html
- https://pandas.pydata.org/docs/reference/api/pandas.IntervalIndex.from_breaks.html
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.IntervalIndex.from_tuples.html

### Documentation problem

All 3 class methods are missing a description of the `name` parameter.

### Suggested fix for documentation

Add a description of the `name` parameter.

Probably happens because it is using the docs from `IntervalArray`, which has no `name` parameter.

**Comment by silviaovo** [comment]
take
