### ISSUE TITLE
ENH: Transparent Excel2Pandas import and reverse export.  Excel file editing through pandas and vice versa.

### ISSUE THREAD

**Issue by heijligers** [pandas-dev/pandas#48934]
### Feature Type

- [x] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I want to have a human readible and editable step in my pandas dataframe process.

For example. I have a dataframe. I save it to excel. Later in the software I recreate the pandas dataframe from that excel.
Now I can manually edit the information in the excel outside of python.

I am missing a to_excel method that manages to save as much of the metadata information as possible (if necessary in seperate additional sheets) so that when I later recreate the the dataframe from excel all my original structure (such as data types) is maintained.

### Feature Description

A to_excel method that manages to save as much of the metadata information as possible (if necessary in seperate additional sheets) so that when I later recreate the the dataframe from excel all my original structure (such as data types) is maintained.

### Alternative Solutions

Open to suggestions

**Comment by jbrockmendel** [comment]
Pls add an informative title

**Comment by rhshadrach** [comment]
This sounds too complex to support. Excel is a format which does not store different data types well, and we'd be trying to hack something in. -1

**Comment by heijligers** [comment]
May I Ask for a reconsideration? 
For example: 
The use case I am describing is a planning analysis framework with generally only numerical, string or categorical values.  To make the configuration of this tool also accessible to non-python users, an intermediate storage in excel's files would facility usability for legacy users.

I understand that storing complex data types would be quite a complex process. For numerical, string and categorical values this could be doable. Very similar to how I can import SPSS files with extended meta data into Pandas and (when I haven't changed the structure of data vs metadeta) can export it again to an equivalent SPSS file.

Alternatively:
When you take a PANDAS FIRST perspective I fully understand your position.
The second use case for my request would be a EXCEL First. In a heavy excel centric environment it would be great to transparently import an excel file, modify it's values and than export the excel again, maintaining EXCEL Style elements. (Formulas would be replaced by values at import)

**Comment by jreback** [comment]
this is too complex to put in main pandas - you are welcome to make a package that does this but it's ot for core

-1 on extending here

**Comment by phofl** [comment]
Agreed, this is out of scope for us. Closing for now
