### ISSUE TITLE
BUG: excel read from file

### ISSUE THREAD

**Issue by JMante1** [pandas-dev/pandas#48946]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

with open(excel_file_path) as f:
     pd.read_excel(f, sheet_name=None)
```

### Issue Description

I cannot get the code above to work. I have tried specifying the encoding when opening the file, specifying that it should be 'r' open, put in f.read() in the pandas function, and all combinations there of. I have received errors about character encodings, it not passing is instance(buf, byte), and it being a bad zip file.

### Expected Behavior

This example should work the same as pd.read_excel(excel_file_path, sheet_name=None)

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763
python           : 3.9.1.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : English_United States.1252

pandas           : 1.5.0
numpy            : 1.21.2
pytz             : 2022.4
dateutil         : 2.8.2
setuptools       : 51.3.3
pip              : 20.3.3
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.4.3
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : None
tzdata           : None

**Comment by phofl** [comment]
Hi, thanks for your report. Please post errors and make a reproducible example (https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)

**Comment by Pro-Coder04** [comment]
I would like to solve this issue if it still exists
Could someone assign it to me

**Comment by XiaoyuZZhou** [comment]
take

**Comment by JMante1** [comment]
I have attached an example file
[test.xlsx](https://github.com/pandas-dev/pandas/files/9759486/test.xlsx)

**Comment by phofl** [comment]
Excel is a binary file, you have to open it accordingly

**Comment by JMante1** [comment]
I have tried specifying the encoding when opening the file

**Comment by JMante1** [comment]
That doesn't actually solve the problem

**Comment by phofl** [comment]
Simply use rb in the open call
