### ISSUE TITLE
ENH: allow complex type inference in astype/convert_objects

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#4895]
`astype/convert_objects` should be able to do this type of coercion from string complex looking

```
In [45]: Series(['1.0+5j','1.5-3j']).apply(lambda x: np.complex(x))
Out[45]: 
0      (1+5j)
1    (1.5-3j)
dtype: complex128
```

http://stackoverflow.com/questions/18919699/python-pandas-complex-number/18919965#18919965

**Comment by mroeschke** [comment]
Looks to work on master. Could use a test

```
In [5]: pd.Series(['1.0+5j','1.5-3j']).apply(lambda x: np.complex(x))
Out[5]:
0    1.000000+5.000000j
1    1.500000-3.000000j
dtype: complex128

In [6]: pd.__version__
Out[6]: '1.1.0.dev0+1078.gb5092d877'
```

**Comment by abkosar** [comment]
This looks like a bit old, but is this still available to work on?

**Comment by rhshadrach** [comment]
Looks like this work on main:

```
print(Series(['1.0+5j', '1.5-3j']).astype(complex))
# 0    1.0+5.0j
# 1    1.5-3.0j
# dtype: complex128

print(DataFrame(['1.0+5j', '1.5-3j']).astype(complex))
#           0
# 0  1.0+5.0j
# 1  1.5-3.0j
```

Marking this as needs tests for now. Maybe this was reported in another (duplicate) issue and closed purposefully? I would recommend searching the issue tracker and/or tests before them.

**Comment by srkds** [comment]
take
