### ISSUE TITLE
API: Series[td64].astype("timedelta64[unsupported]")

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#48979]
```python
ser = pd.Series([1e15, 2e15, 3e15], dtype="m8[ns]")

first = ser.astype("m8[s]")
second = ser.astype("m8[D]")
```

ATM both `first` and `second` come back as float64.  In 2.0 with non-nanosecond (specifically s, us, ms) support, `first` will come back as the requested "m8[s]" (xref #48963).  The question here is: do we want to change the behavior for `second`?  I lean towards raising.  Could do a deprecation cycle.

<b>Update</b>Related: `Series(.., dtype="m8[D]")` currently just swaps out "m8[D]" for "m8[ns]" (and in 2.0 is planned to swap it out for "m8[s]").  Ideally the behavior should be consistent with astype.  i.e. I'd want to raise.

**Comment by mroeschke** [comment]
+1 to raising in the future. IMO ideally done with a deprecation cycle.

**Comment by jbrockmendel** [comment]
Current thought is that we should move to raising without a deprecation cycle.  Users who are passing non-supported dt64/td64 dtypes are going to have to update their code in 2.0, might as well have it be all-at-once.
