### ISSUE TITLE
BUG:  `rsplit` not behaving as expected with regex "\s" for whitespace

### ISSUE THREAD

**Issue by adesuwa-osagie** [pandas-dev/pandas#49006]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

s = pd.Series("this is a regular sentence")

s.str.rsplit("\s", n=1, expand=True) # <-- this produces the error
```

### Issue Description

Splitting is not done at the whitespace before the string "sentence" 

Also tried: `s.str.rsplit(r"\s", n=1, expand=True)`

What worked: `s.str.rsplit(" ", n=1, expand=True)`

### Expected Behavior

![expected-result](https://user-images.githubusercontent.com/64429121/194693375-3db7357a-dc49-4670-a031-f845d96f3713.png)

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763
python           : 3.10.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 167 Stepping 1, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.5.0
numpy            : 1.23.3
pytz             : 2022.4
dateutil         : 2.8.2
setuptools       : 58.1.0
pip              : 22.2.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.5.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None
</details>

**Comment by dannyi96** [comment]
**An observation -** Pandas `.str.split` supports `pat` argument to be of regex form but  `.str.rsplit` does not support `pat` to be a regex

split -
https://github.com/pandas-dev/pandas/blob/55dc32437ea43a238975439ddb6c9dda81b33020/pandas/core/strings/accessor.py#L858-L875

rsplit - 
https://github.com/pandas-dev/pandas/blob/55dc32437ea43a238975439ddb6c9dda81b33020/pandas/core/strings/accessor.py#L890-L894

I believe this is the expected behavior as per current pandas code 
but it can be enhanced so that rsplit supports regex based inputs as well

**Comment by MarcoGorelli** [comment]
>  it can be enhanced so that rsplit supports regex based inputs as well

I don't think this is possible - can you check the issue tracker for duplicates please? Pretty sure this is there

**Comment by MarcoGorelli** [comment]
Here it is https://github.com/pandas-dev/pandas/issues/46488

**Comment by MarcoGorelli** [comment]
Closing then, but thanks for the suggestion

**Comment by adesuwa-osagie** [comment]
@dannyi96 @MarcoGorelli Thank you for taking the time to look at it and providing the link to the issue that explains that regex not working regex is actually an expected behavior. I appreciate it!
