### ISSUE TITLE
BUG: .astype(int) in Window vs Mac

### ISSUE THREAD

**Issue by FeiLi1996** [pandas-dev/pandas#49003]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

Hypothetical example. I can't give an actual example because it is company stuff,
```python
ipdb> ids.astype(int) #on Mac
id(before)      id(after) 
1818726176      1818726176  
1881879486      1881879486  
2590366906      2590366906 

ipdb> ids.astype(int) #on Window
id(before)      id(after) 
1818726176      1818726176
1881879486      1881879486
2590366906     -1704600390
```

### Issue Description

I encounter an issue similiar to this one on stackoverflow
https://stackoverflow.com/questions/67796096/working-around-the-windows-numpy-astypeint-bug-in-pandas

The story is that my coworker was using Mac and I was using Window. We were getting different numbers in our report. Discrepancy of 179  counts vs 1730 counts of something.

I debugged everyline of code until I got the change at ".astype(int)". For some reason , Mac decided to turn it to int64 and Window turned it into int32. However, some of the ids number are over the cap of int32, so the computer changed the number to something else like you seen the example above 2590366906   >>> -1704600390 . Pandas didn't throw an error or give me a warning. So I  did a left join down the line on the id=id and lots of my data were gone.

### Expected Behavior

The expected behavior should be that Pandas throw an error or at least give me a warning that this happened.

### Installed Versions

<details>

commit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763
python           : 3.8.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.5.0
numpy            : 1.23.3
pytz             : 2022.2.1
dateutil         : 2.8.2
setuptools       : 41.2.0
pip              : 19.2.3
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.1
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.9.3
jinja2           : 3.1.2
IPython          : None
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : 1.0.9
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.0
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.1
snappy           : None
sqlalchemy       : 1.4.41
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by jbrockmendel** [comment]
This is happening in numpy.  I agree it’s annoying. It can be solve by passing “np.int64” instead of “int”

**Comment by phofl** [comment]
Agreed, you should specify the dtype precision if you want to be sure.
