### ISSUE TITLE
BUG: `pd.rename` creates duplicate columns when the target column is already present

### ISSUE THREAD

**Issue by david-fortini** [pandas-dev/pandas#49007]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame(dict(a=[1,2], b=[2,3]))
df = df.rename(columns={"a": "b"})

# I would expect this assert to pass
assert sum([x == 'b' for x in df.columns]) == 1, "more than 1 column `b` found!"
```

### Issue Description

The `rename` method calls works without raising a warning or error and its results is imho surprising. 

### Expected Behavior

I would expect one of the tree options:
1. raise an `error`.
2. replace the target column. This is what I would expect also reading the current documentation.
3. Otherwise, make it clear in the documentation that if the `rename` target name is present, a duplicate column will be created.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 55dc32437ea43a238975439ddb6c9dda81b33020
python           : 3.8.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.17.5-76051705-generic
Version          : #202204271406~1653440576~20.04~6277a18-Ubuntu SMP PREEMPT Thu Ma
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0+unknown
numpy            : 1.23.3
pytz             : 2022.4
dateutil         : 2.8.2
setuptools       : 63.4.1
pip              : None
Cython           : None
pytest           : 6.1.2
hypothesis       : None
sphinx           : 5.0.2
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.7.1
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.8.6
jinja2           : 3.0.3
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
brotli           : 
fastparquet      : 0.8.0
fsspec           : 2022.01.0
gcsfs            : None
matplotlib       : 3.3.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.0
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : 0.8.10
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report!

> replace the target column. This is what I would expect also reading the current documentation.

What part of the documentation are you referring to here that gives you that expectation?

One can set `DataFrame.flags.allows_duplicate_labels` to `False` and this should then raise if a duplicate column name occurs.

**Comment by phofl** [comment]
This is straightforward, there is no reason that this should work any different.

Closing, please ping to reopen if the allow_duplicate_labels flag does not work
