### ISSUE TITLE
REF: Define ops on Resampler as normal methods

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#49001]
Ref: https://github.com/pandas-dev/pandas/pull/48980#pullrequestreview-1134863343

Similar to #48400 with groupby, we should define methods on the `Resampler` class rather than setting them as attributes after the class definition. While this involves a little more boilerplate code, it is more straightforward to understand and easier to enhance or extend.

**Comment by erikcek** [comment]
take

**Comment by Pvlb1998** [comment]
Is this issue still possible do Take?

**Comment by rhshadrach** [comment]
@Pvlb1998 - yes, comment take and it will be assigned to you.

**Comment by lucaslarios** [comment]
take

**Comment by lucaslarios** [comment]
hello, could you specify a little better the purpose of the issue? in which file is this class found? Is there any solution suggestion?
