### ISSUE TITLE
BUG: Pandas `convert_dtypes` does not convert numerical strings to numerical values

### ISSUE THREAD

**Issue by jankaWIS** [pandas-dev/pandas#49026]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

x = pd.DataFrame({
    'int_col' : ['1', '2'],
    'float_col': ['1.1', '1.2'],
    'string_col': ['a', 'b'],
    'date': ['12/12/12', '1/1/14']
})

print(x.dtypes)
# int_col       object
# float_col     object
# string_col    object
# date          object
# dtype: object

print(x.convert_dtypes().dtypes)
# int_col       string
# float_col     string
# string_col    string
# date          string
# dtype: object
```

### Issue Description

If one has a dataframe with numbers (int or float) or other types (eg a datetime) entered for whatever reason as strings and tries to find the appropriate type using [`convert_dtypes()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.convert_dtypes.html), then it converts all the types into strings and not into the right and corresponding types.  Why is that, and what to do with that?

---
Some notes:

If one then does the following:
```python
x.to_json()
```
copies the string and loads it back:
```python
y = pd.read_json('{"int_col":{"0":"1","1":"2"},"float_col":{"0":"1.1","1":"1.2"},"string_col":{"0":"a","1":"b"},"date":{"0":"12\\/12\\/12","1":"1\\/1\\/14"}}')

print(y.dtypes)
# int_col                int64
# float_col            float64
# string_col            object
# date          datetime64[ns]
# dtype: object

print(y.convert_dtypes().dtypes)
# int_col                Int64
# float_col            Float64
# string_col            string
# date          datetime64[ns]
# dtype: object
```
Then one gets what is expected, so at least by loading it in form of a string as JSON seems to know how to handle this issue.

There is one more observation I have. Not even [`inder_objects()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.infer_objects.html#pandas.DataFrame.infer_objects) seems to know what is going on:
```python
x.infer_objects().dtypes
# int_col       object
# float_col     object
# string_col    object
# date          object
# dtype: object
```
---

Maybe related is this: https://stackoverflow.com/questions/65915048/pandas-convert-dtypes-not-working-on-numbers-marked-as-objects.

### Expected Behavior

It should convert floats and ints and datetimes types hidden in strings to those types and not to string.

I am also aware that I could go over the columns, try `pd.to_numeric` or try applying types I expect/assume but I feel like this function should do it for me.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763
python           : 3.8.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.6.0
Version          : Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0
numpy            : 1.23.3
pytz             : 2022.4
dateutil         : 2.8.2
setuptools       : 65.4.1
pip              : 22.2.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.5.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.0
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by phofl** [comment]
Hi, thanks for your report. This is not what ``convert_dtypes`` is for. We try to cast to extension array dtypes, but there is no string to int conversion going on. See https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.convert_dtypes.html

**Comment by jankaWIS** [comment]
Hi @phofl and thanks for your answer. I tend to disagree - it's not about the string to int conversion (again, I could use `pd.to_numeric`) but rather object to correct type conversion. The fact that the int is hidden in a string type should not matter, and nothing in the docs suggests it. And that is what this issue is about.

**Comment by phofl** [comment]
An int represented as a string, e.g. ``"2"`` is still a string, not an int.

**Comment by phofl** [comment]
No, this is not in scope for ``convert_dtypes``. The function uses numpy dtypes and looks for the best extension dtype, it does not convert the values itself.

**Comment by jankaWIS** [comment]
Sorry, so could you please explain what the difference is between loading it as a string (or object), eg. like in the JSON, and converting it when the dataframe has been already built (like intended in this bug report)?

And is there a way around it?

**Comment by phofl** [comment]
That's what ``to_numeric`` was build for.
