### ISSUE TITLE
DOC: Add entry to pandas extension list 

### ISSUE THREAD

**Issue by mocquin** [pandas-dev/pandas#49046]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/ecosystem.html#ecosystem-extensions

### Documentation problem

I worked on an extension to the [physipy](https://github.com/mocquin/physipy) package, that allows handling physical units. The extension provides dtype and accessor.
The extension is packaged in [physipandas](https://github.com/mocquin/physipandas).

As suggested in the doc, I propose to add the project to the documentation.
 Notice that the target package, [physipy](), aims kind of the same goals as `pint`, that is already in the extension list.

### Suggested fix for documentation

Add an entry to https://pandas.pydata.org/docs/ecosystem.html#ecosystem-extensions for the extension, and to https://pandas.pydata.org/docs/ecosystem.html#accessors for the accessor registered as `df.physipy.`.

**Comment by jbrockmendel** [comment]
PR welcome

**Comment by nidhiiiiii** [comment]
can i take up this issue as my first contribution?

**Comment by flotaro** [comment]
take

**Comment by flotaro** [comment]
@mocquin what do i have to add in the classes column while adding it in the docs? Series of DataFrame?

**Comment by rsm-23** [comment]
Taking up this stale PR. Hope that's fine.

**Comment by rsm-23** [comment]
take

**Comment by rsm-23** [comment]
@jbrockmendel can you please take up the PR review?
