### ISSUE TITLE
DOC: Typo of "DataFrame.iat()" in "10 minutes to pandas"

### ISSUE THREAD

**Issue by gau-nernst** [pandas-dev/pandas#49057]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/user_guide/10min.html#selection-by-position

### Documentation problem

Under Select by position section, it should be `DataFrame.iat()` instead of `DataFrame.at()`

> See more in [Selection by Position](https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-integer) using [DataFrame.iloc()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html#pandas.DataFrame.iloc) or **[DataFrame.iat()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iat.html#pandas.DataFrame.iat)**.

Later in this section, `.iat()` is used, not `.at()`. So it is probably a typo from my understanding.

### Suggested fix for documentation

Change `DataFrame.at()` to `DataFrame.iat()` under Select by position section.

**Comment by angularOcean** [comment]
Hi gua-nernst, I agree this likely seems to be a typo since `.iat()` selects based upon integer position and `.at()` selects based upon label and this is the select by position section. I am attempting a quick fix and pull request on this.
