### ISSUE TITLE
BUG: df.assign got unexpected output compared with df.apply

### ISSUE THREAD

**Issue by chAwater** [pandas-dev/pandas#49065]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame(
    {
        'X': [1, 2],
        'Y': [3, 4]
    },
    index=['A', 'B']
)

df.assign(
    result=lambda x: x['X'] + x['Y'],
    try1=lambda x: '{}+{}'.format(x['X'], x['Y']),  # unexpected
    try2=lambda x: str(x['X']) + '+' + str(x['Y']),  # unexpected
    try3=lambda x: x['X'].astype(str) + '+' + x['Y'].astype(str),  # expected
)
```

### Issue Description

Output:
```
Out[1]:
   X  Y  result                                               try1                                               try2 try3
A  1  3       4  A    1\nB    2\nName: X, dtype: int64+A    3\n...  A    1\nB    2\nName: X, dtype: int64+A    3\n...  1+3
B  2  4       6  A    1\nB    2\nName: X, dtype: int64+A    3\n...  A    1\nB    2\nName: X, dtype: int64+A    3\n...  2+4
```

### Expected Behavior

I expect to get the output as same as:

```python
df['try1'] = df.apply(lambda x: '{}+{}'.format(x['X'], x['Y']), axis=1)
df['try2'] = df.apply(lambda x: str(x['X']) + '+' + str(x['Y']), axis=1)
```

```
Out[3]:
   X  Y try1 try2
A  1  3  1+3  1+3
B  2  4  2+4  2+4
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763
python           : 3.10.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-957.el7.x86_64
Version          : #1 SMP Sat Dec 15 12:48:25 CST 2018
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0
numpy            : 1.23.3
pytz             : 2022.4
dateutil         : 2.8.2
setuptools       : 65.4.1
pip              : 22.2.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.4.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by Tiri1992** [comment]
hmm my guess would be its fallback `__str__` method. I'll take a look.

**Comment by Tiri1992** [comment]
Just having quick look, I see that Series class doesnt have a  `__str__` implementation and falls back use the `__repr__`

```
    def __repr__(self) -> str:
        """
        Return a string representation for a particular Series.
        """
        repr_params = fmt.get_series_repr_params()
        return self.to_string(**repr_params)
```
Having the behaviour str(`df['X']`) converting your data types to strings (similar to the method `.astype(str)`) would have unwanted side effects on other parts of the api. Wondering if anyone with more experience with the internal workings of pandas can add some more insight to this issue?

**Comment by asishm** [comment]
This is expected.

The first and last assigns go via the route of `Series.__add__` but the second and third assigns go via the route of `Series.__str__` and then the resulting strings get added.

`df.apply(..., axis=1)` passes in rows, so `x["X"]` gives you a single value instead of a series. `df.assign` passes in a dataframe so `x["X"]` is a Series instead of a single value (as opposed to the apply case)

**Comment by chAwater** [comment]
Thanks @asishm for the explanation, very clear.

Closing it, although I still feel a bit "counter-intuitive" 🤣
