### ISSUE TITLE
BUG: `USFederalHolidayCalendar.holidays` inconsistently returns Index and not DateTimeIndex

### ISSUE THREAD

**Issue by austinjpaul** [pandas-dev/pandas#49075]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
>>> import datetime
>>> from pandas.tseries.holiday import USFederalHolidayCalendar
>>> cal = USFederalHolidayCalendar()
>>> cal.holidays(start=datetime.date(2018,8,1), end=datetime.date(2018,8,31))
Index([], dtype='object')
```

### Issue Description

The returned result should be type `DatetimeIndex`.
Non-empty results are indeed of type `DatetimeIndex`. Furthermore, certain other empty results from other ranges (seen below in expected behavior) also have type `DatetimeIndex`.
The return type is inconsistent.

### Expected Behavior

```
>>> cal.holidays(start=datetime.date(2020,8,1), end=datetime.date(2020,8,31))
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
>>> cal.holidays(start=datetime.date(2019,8,1), end=datetime.date(2019,8,31))
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
```

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763
python           : 3.10.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0
numpy            : 1.23.3
pytz             : 2022.4
dateutil         : 2.8.2
setuptools       : 65.4.1
pip              : 22.2.2

</details>

**Comment by roadswitcher** [comment]
Same behavior seen for March (the other month with no US Federal holidays), but interestingly the behavior is consistent for 2019.

```>>> import datetime
>>> from pandas.tseries.holiday import USFederalHolidayCalendar
>>> cal = USFederalHolidayCalendar()
>>> cal.holidays(start=datetime.date(2018,8,1), end=datetime.date(2018,8,31))
Index([], dtype='object')
>>> cal.holidays(start=datetime.date(2018,3,1), end=datetime.date(2018,3,31))
Index([], dtype='object')
>>> cal.holidays(start=datetime.date(2019,8,1), end=datetime.date(2019,8,31))
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
>>> cal.holidays(start=datetime.date(2019,3,1), end=datetime.date(2019,3,31))
DatetimeIndex([], dtype='datetime64[ns]', freq=None)```

**Comment by roadswitcher** [comment]
Yeah, I missed some strange behavior that made my PR irrelevant.

Documenting for the record here:    
- submitters original issue can be replicated by picking any initial pair of dates that do not contain a holiday between them, and get an `Index` object.
- You can then call against the same calendar object with a date range that contains at least one holiday, and get the `DatetimeIndex` submitter expected
- Repeat the original request with a range of dates that do not contain a holiday, and you now get a `DatetimeIndex`. 

Example:   
```
In [3]: cal=USFederalHolidayCalendar()

In [4]: cal.holidays(start="2018-08-01", end="2018-08-31")
Out[4]: Index([], dtype='object')

In [5]: cal.holidays(start="2018-07-05", end="2018-08-31")
Out[5]: Index([], dtype='object')

In [6]: cal.holidays(start=datetime.date(2018,8,1), end=datetime.date(2018,8,31))
Out[6]: Index([], dtype='object')

In [7]: cal.holidays(start=datetime.date(2018,7,1), end=datetime.date(2018,8,31))
Out[7]: DatetimeIndex(['2018-07-04'], dtype='datetime64[ns]', freq=None)

In [8]: cal.holidays(start=datetime.date(2018,8,1), end=datetime.date(2018,8,31))
Out[8]: DatetimeIndex([], dtype='datetime64[ns]', freq=None)
```

**Comment by roadswitcher** [comment]
take
