### ISSUE TITLE
DOC: Typo on Dataframe.drop_duplicates() docstring

### ISSUE THREAD

**Issue by Vini-002** [pandas-dev/pandas#49071]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

pandas.DataFrame.drop_duplicates()

### Documentation problem

![Screenshot from 2022-10-13 13-45-07](https://user-images.githubusercontent.com/68878626/195656602-2bad5a9f-3127-4239-8346-b5a0636c048e.png)
The `inplace` and other parameters are on the text for the `False` option.

### Suggested fix for documentation

They should be in the next line, to make the correct separation of the parameters

**Comment by am1671** [comment]
Could i try this?

**Comment by rhshadrach** [comment]
I'm not seeing any issue in our dev docs:

https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.drop_duplicates.html

Nor in the source code:

https://github.com/pandas-dev/pandas/blob/bf5ee72d5b81962db91fa12f637b4369d3e30f77/pandas/core/frame.py#L6494-L6511

**Comment by phofl** [comment]
This was fixed since 1.5.0 was released, so should be good in 2.0.0 docs (works in dev docs)

**Comment by Vini-002** [comment]
Sorry for the inconvenience
