### ISSUE TITLE
QST: When will attrs be not experimental?

### ISSUE THREAD

**Issue by Bolognafingers** [pandas-dev/pandas#49085]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

N/A

### Question about pandas

When, if ever, can `DataFrame.attrs` be expected to be stabilized and not experimental? I'd really like to use this feature, but don't want to "invest" in it if it goes away.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.attrs.html

**Comment by phofl** [comment]
Hi, thanks for your interest.

This is basically blocked by #28283 and the related issues. We don't propagate the metadata in every method yet. Help is welcome there.
