### ISSUE TITLE
DOC: Fix versionchanged directive in DataFrame.plot

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#49117]
Looks like there is something wrong in the documentation of `DataFrame.plot`, and the `.. versionchanged` directive of the parameters `logx`, `logy` and `loglog` is not rendered correctly: https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.plot.html

It's probably a typo, a missing space or something. We should have a look and compare with another docstring where a parameter `versionchanged` is correctly rendered, see what's wrong, and fix it.

**Comment by Shikharishere** [comment]
Hey, @datapythonista shikhar here, can you guide me through this issue?

**Comment by mathpn** [comment]
It seems that the issue is caused by a lack of a blank new line. All others ".. versionchanged" occurrences have a blank line before. I've created a pull request with this tiny change. Considering how tiny it is, I haven't included anything in the changelog, please tell me if that's OK.
