### ISSUE TITLE
API: Series/DataFrame.mask(other) should default to lib.no_default instead of np.nan

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#49111]
In 1.4 (https://github.com/pandas-dev/pandas/pull/44697), `.where(other=)` was changed from `np.nan` to `lib.no_default`.

Since `mask` is the analogous method to `where`, it's `other` argument should also default to `lib.no_default`

**Comment by rhshadrach** [comment]
Just to be sure

> it's `other` argument should also default to ~`np.nan`~ `lib.no_default`

**Comment by mroeschke** [comment]
> Just to be sure
> 
> > it's `other` argument should also default to ~`np.nan`~ `lib.no_default`

Thanks for spotting my typo, edited my post above
