### ISSUE TITLE
BUG: Assigning column with tuple as name from groupby fails

### ISSUE THREAD

**Issue by misantroop** [pandas-dev/pandas#49121]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
from pandas import Timestamp

df = pd.DataFrame(
        {('T1', 'T2'): {('N', Timestamp('2022-10-10')): 19}}
)
df.index = df.index.set_names(['Symbol', 'Date'])

grp = df.groupby('Symbol')
col_name = df.columns[0]
df[col_name] = grp[[col_name]].shift()
```

### Issue Description

Assigning column from groups to a multiindex fails when column name is a tuple. No issues with non-tuple types. Seems to work normally with a single index.

```
File ~/.pyenv/versions/3.9.13/lib/python3.9/site-packages/pandas/core/frame.py:3968, in DataFrame.__setitem__(self, key, value)
   3966     self._setitem_array(key, value)
   3967 elif isinstance(value, DataFrame):
-> 3968     self._set_item_frame_value(key, value)
   3969 elif (
   3970     is_list_like(value)
   3971     and not self.columns.is_unique
   3972     and 1 < len(self.columns.get_indexer_for([key])) == len(value)
   3973 ):
   3974     # Column to set is duplicated
   3975     self._setitem_array([key], value)

File ~/.pyenv/versions/3.9.13/lib/python3.9/site-packages/pandas/core/frame.py:4098, in DataFrame._set_item_frame_value(self, key, value)
   4096 len_cols = 1 if is_scalar(cols) else len(cols)
   4097 if len_cols != len(value.columns):
-> 4098     raise ValueError("Columns must be same length as key")
   4100 # align right-hand-side columns if self.columns
   4101 # is multi-index and self[key] is a sub-frame
   4102 if isinstance(self.columns, MultiIndex) and isinstance(
   4103     loc, (slice, Series, np.ndarray, Index)
   4104 ):

ValueError: Columns must be same length as key
```

### Expected Behavior

No exception being thrown, column assigned normally.

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763
python           : 3.9.13.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.60-1-MANJARO
Version          : #1 SMP PREEMPT Thu Aug 11 13:14:05 UTC 2022
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.5.0 and 1.6.0.dev0+345.g90b4add77
numpy            : 1.22.4
pytz             : 2022.2.1
dateutil         : 2.8.2
setuptools       : 65.3.0
pip              : 22.2.2
Cython           : 3.0.0a11
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : 1.0.9
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.0
numba            : 0.56.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 9.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None
</details>

**Comment by phofl** [comment]
Hi, thanks for your report. this is independent of groupby. This is because your columns are a MultiIndex.

```
df = pd.DataFrame(
        {
            ('T1', 'T2'):
             {('N', pd.Timestamp('2022-10-10')): 19}}
)

col_name = ('T1', 'T2')
rhs = df[[col_name]]
df[col_name] = rhs
```

this raises as well
