### ISSUE TITLE
BUG: The behavior of DataFrame.corrwith against `Series` is changed?

### ISSUE THREAD

**Issue by itholic** [pandas-dev/pandas#49141]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

df_bool = pd.DataFrame({"A": [True, True, False, False], "B": [True, False, False, True]})
ser_bool = pd.Series([True, True, False, True])

df_bool.corrwith(ser_bool)
```

### Issue Description

In pandas < 1.5.0:

```python
>>> df_bool.corrwith(ser_bool)
B    0.57735
A    0.57735
dtype: float64
```

In pandas 1.5.0:

```python
>>> df_bool.corrwith(ser_bool)
Series([], dtype: float64)
```

So, I wonder this behavior change is intended, or a bug ?

### Expected Behavior

I expected the result is the same as pandas < 1.5.0 as below:

```python
>>> df_bool.corrwith(ser_bool)
B    0.57735
A    0.57735
dtype: float64
```

rather than returning the empty Series.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763
python           : 3.9.11.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.6.0
Version          : Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.5.0
numpy            : 1.22.3
pytz             : 2021.3
dateutil         : 2.8.2
setuptools       : 61.2.0
pip              : 22.2.2
Cython           : 0.29.24
pytest           : 6.2.5
hypothesis       : None
sphinx           : 3.0.4
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.29.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.4
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : 9.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.2
snappy           : None
sqlalchemy       : 1.4.26
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by MarcoGorelli** [comment]
is this different from https://github.com/pandas-dev/pandas/issues/48826 ? looks like it'd be solved by reverting the same PR
```
(pandas-dev) marcogorelli@DESKTOP-U8OKFP3:~/pandas-dev$ git branch --show-current 
revert-5efb570
(pandas-dev) marcogorelli@DESKTOP-U8OKFP3:~/pandas-dev$ . repl.sh 

In [1]: import pandas as pd
   ...: 
   ...: df_bool = pd.DataFrame({"A": [True, True, False, False], "B": [True, False, False, True]})
   ...: ser_bool = pd.Series([True, True, False, True])
   ...: 
   ...: df_bool.corrwith(ser_bool)
Out[1]: 
A    0.57735
B    0.57735
dtype: float64
```
