### ISSUE TITLE
DOC: replace "join Gitter chat" README badge with link to Slack channel

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#49143]
Let's replace this badge

https://github.com/pandas-dev/pandas/blob/464c10993c6ec76636a1335903f21baf8622c1e0/README.md#L16

with a custom one (e.g. https://gist.github.com/afig/be5ab20c50062dba7cb835e30206659a) which says "Join Slack" and which links to https://pandas.pydata.org/docs/dev/development/community.html?highlight=slack#community-slack

**Comment by roadswitcher** [comment]
take
