### ISSUE TITLE
ENH: Pandas wheels inclkuded tests (and test data)

### ISSUE THREAD

**Issue by rjungbeck** [pandas-dev/pandas#49150]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Pandas wheels are normally used to distribute pandas to end users (and not to people developing pandas. Developers would  need a source distribution). So why are tests (and test data) is included in them?

Disk requirements (after installation) would be 1/3 smaller if  tests were not included in wheels.

### Feature Description

Simply remove tests (and data) from the wheels

### Alternative Solutions

Have a own library containing the tests.

**Comment by MarcoGorelli** [comment]
thanks for the suggestion - closing as it looks like a duplicate of https://github.com/pandas-dev/pandas/issues/30741, but do correct me if I'm wrong
