### ISSUE TITLE
DOC: closed and dtype missing from TimedeltaIndex docs

### ISSUE THREAD

**Issue by bashtage** [pandas-dev/pandas#49153]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.TimedeltaIndex.html

### Documentation problem

Missing two parameters, closed and dtype

### Suggested fix for documentation

Add these two parameters with types ane explanation

xref pandas-dev/pandas-stubs#383

**Comment by zmwaris1** [comment]
Please assign me this issue I would like to fix it.

**Comment by bashtage** [comment]
@zmwaris1 You can just submit a PR and link to this issue.  We don't assign in general.

**Comment by zmwaris1** [comment]
Okay thank you.

**Comment by keiyanishio** [comment]
Hi @bashtage, I added the two missing parameters  in this PR:  https://github.com/pandas-dev/pandas/pull/49168
