### ISSUE TITLE
ENH: DataFrame.from_xy methods are duplicates

### ISSUE THREAD

**Issue by alefnula** [pandas-dev/pandas#4916]
Decide what to do with each of these
- [x] deprecate `from_csv` ~~/ change to be exactly like `read_csv`~~ -> https://github.com/pandas-dev/pandas/pull/17812
- [ ] from_dict
- [ ] from_records (see #8161)
- [x] from_items (#18529)

This is just a suggestion: `DataFrame` constructor already supports the things that `from_dict` and `from_records` do (`from_items` is not supported by the constructor, but maybe it should be?). Also `from_csv` does the same thing as `pd.read_csv`.

Since `There should be one-- and preferably only one --obvious way to do it.` maybe these methods should be removed/deprecated?

I know that this would cause backward incompatibility, so maybe just a deprecation warning could be displayed until a future major release that could remove them.

**Comment by maximilianr** [comment]
@jreback Merging some of these constructors would be great, and would give the main constructor some additional pieces of functionality. One of those is `orient` keyword, which the `from_dict` constructor offers.

I'm trying to come up with a ruleset for how the `DataFrame` should be oriented. For example, why does the alignment change depending on whether it's passed a `dict` or a list here? Is there an overarching principle here?

If we had an `orient` keyword is the main `DataFrame` constructor, would we have `columns`, `index`, and `default`?

```python

In [67]: pd.DataFrame({'a':pd.Series([1,2,3])})
Out[67]: 
   a
0  1
1  2
2  3

In [68]: pd.DataFrame([pd.Series([1,2,3], name='a')])
Out[68]: 
   0  1  2
a  1  2  3
```

**Comment by jreback** [comment]
orient only applies / matters for a dict

columns / index are what to extract so these are orthogonal


personally I think columns / index are actually confusing and one should simply reindex after buy might be difficult to change this

**Comment by maximilianr** [comment]
@jreback thanks; my question more fundamental - why a `DataFrame` is row orientated when list-like objects are passed in.
i.e. from `pd.DataFrame([pd.Series([1,2,3], name='a')])`, why do we get this:
```python
   0  1  2
a  1  2  3
```
rather than this:
```python
   a
0  1
1  2
2  3
```

**Comment by TomAugspurger** [comment]
It's because you're passing in a list of array-likes. e.g. a numpy array

```python
In [1]: x = np.array([[1, 2], [3, 4]])

In [2]: x
Out[2]:
array([[1, 2],
       [3, 4]])

In [3]: pd.DataFrame(x)
Out[3]:
   0  1
0  1  2
1  3  4
```

**Comment by maximilianr** [comment]
I see. Cheers @TomAugspurger

**Comment by jbrockmendel** [comment]
Is this still something people are interested in?  from_dict had a kwarg added in 0.23.0 which is much more recent than the OP here

**Comment by mroeschke** [comment]
I think `from_dict` and `from_records` have parameters that are more configurable than the default `DataFrame` constructor and have distinct use cases. Since the other methods have been addressed, going to close.
