### ISSUE TITLE
BUG: MultiIndex and its levels are inconsistent

### ISSUE THREAD

**Issue by benoit9126** [pandas-dev/pandas#49183]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

# Create a multiindex
index=pd.MultiIndex.from_frame(pd.DataFrame(data={"a":[1], "b":["a"]}))

# Create a data frame with this index
df=pd.DataFrame(data={"c":[1]}, index=index)

# Create a mask to select rows (here do not select the only row of `df`)
mask=pd.Series(False, index=index)

# The index of the selected data frame is good (empty dataframe so empty index)
df.loc[mask, :].index
# MultiIndex([], names=['a', 'b'])

# Try to get a level of the selected data frame
df.loc[mask, :].index.levels[0]
# Index([1], dtype='Int64', name='a') <---- should be empty as the index is empty

# The first level is not empty
df.loc[mask, :].index.levels[1]
# Index(['a'], dtype='object', name='b')
```

### Issue Description

There is an inconsistency between the index of a dataframe which has been "filtered" with a `loc` in such a way that the result is an empty data frame. The `index` property of the resulting empty data frame is empty but not its levels.

The problem arises when using an `assert_frame_equal`. The indexes are checked levels by levels.

### Expected Behavior

I would have expected the levels of the `MultiIndex` to be also empty

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 91111fd99898d9dcaa6bf6bedb662db4108da6e6
python           : 3.9.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.0-17-amd64
Version          : #1 SMP Debian 5.10.136-1 (2022-08-13)
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : fr_FR.UTF-8
LOCALE           : fr_FR.UTF-8
pandas           : 1.5.1
numpy            : 1.23.4
pytz             : 2022.5
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 22.3
Cython           : 0.29.32
pytest           : 7.1.3
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.2
snappy           : None
sqlalchemy       : 1.4.42
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by phofl** [comment]
Hi,
Thanks for your report. This behaves as intended. Only the codes are updated. You have to remove unused levels explicitly

**Comment by benoit9126** [comment]
Thanks for the quick answer. I didnot know that the `levels` were not updated with the main index class.

Nevertheless, it remains a problem when using a `assert_frame_equal` as there is a check on levels dtype based on the `levels` property (and not `codes` property)... As a consequence, in [`pandas._testing.assert_index_equal`](
https://github.com/pandas-dev/pandas/blob/b94f1a18d35ae516587ce9161eaaa5f9a16f505c/pandas/_testing/asserters.py#L393) the `_check_types` failed as the left `inferred_type` is `"empty"` and the other contains something which is not `"empty"`:

MWE:

```python
import pandas as pd
from pandas.testing import assert_frame_equal

index=pd.MultiIndex.from_frame(pd.DataFrame(data={"a":[1], "b":["a"]}))
df=pd.DataFrame(data={"c":[1]}, index=index)
mask=pd.Series([False], index=index)

index2=pd.MultiIndex.from_frame(pd.DataFrame(data={"a":[], "b":[]}).astype({"a":int, "b":object}))

assert_frame_equal(df.loc[mask,:], pd.DataFrame(data={"c":[]}, index=index2))
Traceback (most recent call last):
  File "/home/benoit/.pyenv/versions/3.9.6/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/benoit/.pyenv/versions/sirao_cli/lib/python3.9/site-packages/pandas/_testing/asserters.py", line 1290, in assert_frame_equal
    assert_index_equal(
  File "/home/benoit/.pyenv/versions/sirao_cli/lib/python3.9/site-packages/pandas/_testing/asserters.py", line 393, in assert_index_equal
    _check_types(left.levels[level], right.levels[level], obj=obj)
  File "/home/benoit/.pyenv/versions/sirao_cli/lib/python3.9/site-packages/pandas/_testing/asserters.py", line 318, in _check_types
    assert_attr_equal("inferred_type", left, right, obj=obj)
  File "/home/benoit/.pyenv/versions/sirao_cli/lib/python3.9/site-packages/pandas/_testing/asserters.py", line 496, in assert_attr_equal
    raise_assert_detail(obj, msg, left_attr, right_attr)
  File "/home/benoit/.pyenv/versions/sirao_cli/lib/python3.9/site-packages/pandas/_testing/asserters.py", line 679, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.index are different
Attribute "inferred_type" are different
[left]:  string
[right]: empty
```

**Comment by phofl** [comment]
This is not the same object. You have to do some postprocessing yourself for this

**Comment by benoit9126** [comment]
Thanks.
