### ISSUE TITLE
DOC: Improve the register_index_accessor Documentation

### ISSUE THREAD

**Issue by achapkowski** [pandas-dev/pandas#49202]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.register_index_accessor.html#pandas.api.extensions.register_index_accessor

### Documentation problem

There is no example showing how to create or what is required on the class to make an index accessor.

### Suggested fix for documentation

Add a link to an example or expand the topic to include a how to implement this.  Also document what is required to make a custom indexer.

**Comment by AnkitKashyap0709** [comment]
Hey, I've started recently on open-source contributions. And I want to help in contributing to the library pandas. I see already that no one is assigned here. I would like to get started on this.

**Comment by achapkowski** [comment]
@AnkitKashyap0709 go for it

**Comment by Mohit2758** [comment]
Hey, I'm new to open-source contributions and I want this to be my one of the first contributions. Can I work on this?

**Comment by vishallb** [comment]
take

**Comment by pranav-ravuri** [comment]
Hi @vishallb what's the status on this issue?

**Comment by SolOlga** [comment]
take

**Comment by SolOlga** [comment]
Hi, I saw that no one touched this issue for three months so I'll try to take it.

**Comment by TechnoShip123** [comment]
Hi, looks like this has been inactive for a few months so I'd like to try it

**Comment by TechnoShip123** [comment]
take
