### ISSUE TITLE
BUG: Reference leak in pandas/_libs/src/ujson/python/objToJSON.c

### ISSUE THREAD

**Issue by JelleZijlstra** [pandas-dev/pandas#49222]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
n/a
```

### Issue Description

Various code starting at https://github.com/pandas-dev/pandas/blob/890d09753492242bd30cc43c7ebd4e819ad89bf1/pandas/_libs/src/ujson/python/objToJSON.c#L154 calls `PyObject_GetAttrString`, but never DECREFs the values returned from the function. This means that these references are leaked, and the objects are never deallocated even if pandas is unimported.

I am happy to prepare a PR to fix this, but I'm not entirely sure what the code in question is even trying to do; it simply accesses these attributes and does nothing with the result.

Found via python/cpython#98253.

### Expected Behavior

No memory leaks

### Installed Versions

```
>>> pandas.show_versions()
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit           : 91111fd99898d9dcaa6bf6bedb662db4108da6e6
python           : 3.11.0.candidate.2
python-bits      : 64
OS               : Darwin
OS-release       : 21.6.0
Version          : Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.1
numpy            : 1.23.4
pytz             : 2022.5
dateutil         : 2.8.2
setuptools       : 63.2.0
pip              : 22.3
Cython           : 0.29.32
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.9.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.5.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : 0.8.10
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None
```

**Comment by jbrockmendel** [comment]
cc @WillAyd

**Comment by WillAyd** [comment]
Yea this is an init hook for the module when it is instantiated. I think could use a cleanup function attached to the module if you'd like to add

**Comment by WillAyd** [comment]
The code is assigning to a static object that gets referenced throughout actual usage of the program. This is arguably bad design so could refactor if more ambitious, but no expectations (there's a lot of spaghetti code)
