### ISSUE TITLE
BUG: to_string(header=False) should not shift the index w.r.t. the data

### ISSUE THREAD

**Issue by jondo** [pandas-dev/pandas#49230]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame([2,3])
df.index.name = 'a'
print(df.to_string(header=False))
```

### Issue Description

The code results in
```
a  2
0  3
1 
```

### Expected Behavior

```
a   
0  2
1  3
```

### Installed Versions

<details>
pd.show_versions() yields:

INSTALLED VERSIONS
------------------
commit           : 91111fd99898d9dcaa6bf6bedb662db4108da6e6
python           : 3.9.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.0-17-amd64
Version          : #1 SMP Debian 5.10.136-1 (2022-08-13)
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_DK.UTF-8
LOCALE           : en_DK.UTF-8

pandas           : 1.5.1
numpy            : 1.23.3
pytz             : 2022.4
dateutil         : 2.8.2
setuptools       : 44.1.1
pip              : 22.2.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.34.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None
</details>

**Comment by jondo** [comment]
Workaround: set `df.index.name = None` before calling `df.to_string`.

**Comment by vamsi-verma-s** [comment]
use `index_names=False` 

```python
print(df.to_string(header=False, index_names=False))
0  2
1  3
```

**Comment by jondo** [comment]
@vamsi-verma-s, in my case `df.to_string(header=False)` evaluates to the string `'a  2\n0  3\n1   '`, which nonsensically has the index name and the first value of the data column in the same row, and the rest of the index shifted w.r.t the data.

I expect `df.to_string(header=False)` to give `'a   \n0  2\n1  3'`, analogous to the `'   0\na   \n0  2\n1  3' of `df.to_string()`.

**Comment by andrewchen1216** [comment]
take

**Comment by attack68** [comment]
Note that `Styler.to_string` is also a workaround

```python
>>> print(df.style.hide(axis="columns").to_string())
a 
0 2
1 3

>>> print(df.style.hide(axis="columns").hide(axis="index", names=True).to_string())
0 2
1 3
```
