### ISSUE TITLE
ENH: shared, reusable vars for github actions

### ISSUE THREAD

**Issue by JMBurley** [pandas-dev/pandas#49294]
### Feature Type

- [X] Adding new functionality to pandas Github Actions

### Problem Description

The many github actions associated with pandas (seem to) individually declare variables that are conceptually common across  workflows e.g., minimum supported python version.

This is a maintenance headache which can be resolved by storing our environment variables in a file and utilising a GitHub Action to fetch those vars for GitHub workflows.

### Feature Description

Here is a good outline of how to implement a shared, reusable item across github workflows.

https://arinco.com.au/blog/github-actions-share-environment-variables-across-workflows/

### Alternative Solutions

 - Ignore best practice as too much effort.  Sounds snarky, but I do mean it as a viable solution.  This can remain a future maintainer's problem.

**Comment by lithomas1** [comment]
Hmmm, I'm not sure how I feel about this one. 

How about we push some of those variables(e.g. COVERAGE, PYTEST_TARGET, TARGET?) down into ci/run.tests.sh? We can set default values for those variables if unset, and then override if necessary in the Github Actions config.

**Comment by mroeschke** [comment]
Yeah I would be -0.5 refactoring env variables into separate env files (I haven't seen other pydata project use this approach). 

Another option would maybe create a github composite action to set env variables?

**Comment by mroeschke** [comment]
Thanks for the suggestion but since this issue hasn't had too much core dev buy-in closing for now
