### ISSUE TITLE
BUG: interpreting dt64 as utc in array_to_datetime/infer_to_datetimelike

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#49291]
```python
values = [pd.Timestamp(0, tz="UTC"), np.datetime64(1, "D").astype("M8[ns]")]

>>> pd.DatetimeIndex(values, tz="US/Pacific")[1:]
DatetimeIndex(['1970-01-01 16:00:00-08:00'], dtype='datetime64[ns, US/Pacific]', freq=None)

>>> pd.DatetimeIndex(values[1:], tz="US/Pacific")
DatetimeIndex(['1970-01-02 00:00:00-08:00'], dtype='datetime64[ns, US/Pacific]', freq=None)
```

In array_to_datetime if we see a dt64 object and a tz-aware datetime, we treat the dt64 as a UTC time.  But if we have dt64 objects and are passed a timezone, we treat them as wall times.  I'd expect the two DTIs above to match.

**Comment by jbrockmendel** [comment]
@MarcoGorelli youve been doing a lot of to_datetime work, i want to make sure this is on your radar

**Comment by MarcoGorelli** [comment]
sure, thanks for the ping

**Comment by jbrockmendel** [comment]
Closed by the implementation of array_to_datetime_with_tz
