### ISSUE TITLE
DOC: Update docs to indicate python 3.11 support

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#49301]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/getting_started/install.html

https://pypi.org/project/pandas/

### Documentation problem

We should update our docs, and the pypi page to indicate that python 3.11 is supported.

### Suggested fix for documentation

Update the docs page (and publish it!!) and pyproject.toml to show 3.11 support.

**Comment by vishallb** [comment]
take
