### ISSUE TITLE
DOC: No such file or directory: '/versions.json'

### ISSUE THREAD

**Issue by peterzhb** [pandas-dev/pandas#49336]
- [x] I have checked that the issue exists on the latest versions of the docs on main.
- [x] I have checked that there is no duplicate issue.

I was trying to build the doc from the latest pandas development version.

It shows error when I run `python make.py html` inside `doc/`

```
Extension error (pydata_sphinx_theme):
Handler <function update_config at 0x13b044040> for event 'env-updated' threw an exception (exception: [Errno 2] No such file or directory: '/versions.json')
```

Anyone could help me with this?

Thanks

Detail

pandas 2.0.0.dev0+450.gc368c320fc.dirty
python 3.9.13

**Comment by tianwen42** [comment]
You may have the [/versions.json] file in the make.py file, but the file is not found in the current directory. Check if the equivalent directory of the.py file contains the **versions.json** file

**Comment by MarcoGorelli** [comment]
Hey @peterzhb - do you get the same error if you build a single page? e.g.
```
python make.py html --single pandas.DataFrame.sum
```

This works fine for me, could you show your full traceback please?

**Comment by phofl** [comment]
Closing for now, please ping to reopen when you can answer the questions
