### ISSUE TITLE
Pandas DataFrame Hands on

### ISSUE THREAD

**Issue by Frazer-Nyambe** [pandas-dev/pandas#49396]
i have created a pandas dataframe, i'm currently facing a problem on how to extract specific strings from the dataframe. given that the dataframe below is my first row with index "0", from the pandas dataframe how do i extract the below statement. 

> I would like to specifically thank Cynthia Phiri for her tireless effort in processing the samples .

**index | 1.txt |
-- | -- | 
0 | ACKNOWLEDGEMENT This dissertation would not have been possible without the support of many individuals and departments. My special thanks go to the following; 1. Dr. Paul Kelly for invaluable practical guidance and encouragement before and during the study. 2. The TROPGAN- Zambia under Dr. Kelly for providing the CMV -PCR kit, the TROPGAN laboratory for storage, processing and some financial assistance. 3. The TROPGAN- Zambia group for the contribution they made to the success of this study. I would like to specifically thank Cynthia Phiri for her tireless effort in processing the samples . 4. Pathology Department for the assistance they provided by doing post -mortem and getting the liver and serum samples. Dr Victor Mudenda , the late Dr. Joseph Banda, Dr Dennis Musonda and Mr Rabson Mwanza were invaluable. 5. Medicine Department for the support and the critique they provided before and during the study. Doctors in this department identified and provided the cases and cont rols for the study as well. 6. The members of staff under UTH who**

**Comment by MarcoGorelli** [comment]
Hi - this is the kind of question you should ask on StackOverflow (with a reproducible example)

Closing for now then, but if you think there's a bug in pandas and have a reproducible example then we can reopen
