### ISSUE TITLE
BUG: "TODO(1.4): Change me into xfail at release time"

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#49411]
There's a bunch of these, some with slightly different wording.  I think they are all greppable with `TODO(1.4)`.  It isn't clear if these were missed at 1.4-release-time or if they were changed and then un-changed post release.  Either way, this is not a good pattern.

**Comment by roadswitcher** [comment]
take

**Comment by lithomas1** [comment]
This is for the Arrow CSV Parser right? 
I think I left a bunch in there, but didn't get around to fixing them.
(I think the plan was to not have skipped tests in the pyarrow parser by 1.4).

**Comment by rsm-23** [comment]
@MarcoGorelli Do we want to replace these skips with xfails? Can you please explain the task? TiA!

**Comment by rsm-23** [comment]
@MarcoGorelli can you please help me understand the task?

**Comment by MarcoGorelli** [comment]
I'm not sure, I didn't open the issue, but there's a few comments in the code such as
````
# TODO(1.4): Change these to xfails whenever parse_dates support(which was
# intentionally disable to keep small PR sizes) is added back
pytestmark = pytest.mark.usefixtures("pyarrow_skip")
```

the task is to address them (I've not looked into how yet)

**Comment by lithomas1** [comment]
I'd recommend looking at some other issues over this one.

This one is quite tedious, and some of the skips can't convert to xfails cleanly for whatever reason (e.g. reader hanging).

If you want to have a look at some other Arrow CSV reader issues, you could take a look at
https://github.com/pandas-dev/pandas/issues?q=is%3Aopen+is%3Aissue+label%3AArrow+label%3A%22IO+CSV%22
