### ISSUE TITLE
BUILD: 

### ISSUE THREAD

**Issue by BHARGAV2017** [pandas-dev/pandas#49433]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

aws lightsail

### Installation Method

pip install

### pandas Version

without specifying the version ie simply typing pip3 install pandas

### Python Version

python 3.7.5

### Installation Logs

No logs but it simply freezed for long hour.

**Comment by rhshadrach** [comment]
Thanks for the report. Is there any more information you can provide? Is there any indication this is an issue with pandas? 

As-is, I don't think this is actionable.

**Comment by MarcoGorelli** [comment]
thanks for the report - pandas doesn't support Python3.7 any more, closing for now then, but can reopen if you provide more info
