### ISSUE TITLE
TST: Refactor ``test_subtracting_two_series_with_unordered_index_and_all_nan_index``

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#49443]
The test is hard to read and hard to understand. We should refactor it to make it more straightforward without those parametrizations. Pending #49442

**Comment by shogohida** [comment]
Hi @phofl, I want to work on this! However, I'm not very sure how to refactor the test because I'm new to Pandas. Could you give me some advice? It would be really helpful

**Comment by phofl** [comment]
It would be helpful to remove the parametrisation and split the content into two tests so that it is easier to read. But would be good to wait till the linked pr is merged, because it changed the behavior of the test

**Comment by shogohida** [comment]
take

**Comment by shogohida** [comment]
Thanks for your comment! Now I understand that I need to separate `result` and `expected`. I will wait until the linked PR is merged

https://github.com/pandas-dev/pandas/blob/a551f1b7b0aeace5d3c6a1c629dce5442fcee85b/pandas/tests/indexing/multiindex/test_multiindex.py#L187-L215

**Comment by shogohida** [comment]
Some tests failed but I wanted to make sure if my understanding is correct at first. Can you have a look?

https://github.com/pandas-dev/pandas/pull/49698
