### ISSUE TITLE
CLN: Remove MultiIndex._get_grouper_for_level

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#49452]
#49373 removed its only use. Since it's implemented on `Index` as well (where it's still needed), I think we should raise NotImplementedError to prevent any hard-to-understand tracebacks.

**Comment by Himanshuwagh** [comment]
can get more description?

**Comment by natmokval** [comment]
take

**Comment by rhshadrach** [comment]
@Himanshuwagh - I'd be happy to - is there a part that is unclear?

@natmokval - I looks like @TaylorChaseHunter is already preparing a PR for this issue.

**Comment by TaylorChaseHunter** [comment]
Oh I'm sorry, I was just kind of practicing the process -- I didn't realize it notified here. @natmokval please feel free to take it and I'll remove my commit.

**Comment by rhshadrach** [comment]
Ah - no problem @TaylorChaseHunter. Thanks for letting us know!

**Comment by natmokval** [comment]
Oops, my mistake. I am quite new to the process too. @TaylorChaseHunter please take the issue and don’t remove your commit.

**Comment by codamuse** [comment]
take

**Comment by codamuse** [comment]
@rhshadrach I made changes off the main branch but tests failed.  Pretty sure your changes in #49373 are necessary?  If so, should I branch off your branch or wait for that to merge then cleanup?  Thanks!

**Comment by rhshadrach** [comment]
Exactly right @codamuse - that PR should be merged in the next few days, thanks for waiting.

**Comment by rhshadrach** [comment]
@codamuse - #49373 has been merged.

**Comment by codamuse** [comment]
> @codamuse - #49373 has been merged.

Thanks for the heads up, I'll PR the change tomorrow.

**Comment by ilaiyengar** [comment]
Hi! I am a first time contributor and would love to help. Is there anything that I could possibly be assigned to or help out with?

**Comment by codamuse** [comment]
@rhshadrach Sorry but I've been trying to get tests to pass locally and not having much success.  I cloned a fresh repo from `pandas-dev:main`, setup my docker environment, cythonized, then ran tests from the `panda-dev` environment in conda and I get lots of fails even when trying different options to pytest.  Could be something with my setup, I dug into a little bit but couldn't figure it out.  I've decided to setup a draft PR in my fork for the change and see how the checks go there in case there's something strange happening in my environment.  I'll keep checking locally, none of the tests are at all related to the change I made (removing that function in multi.py).  I'll keep you posted.

**Comment by codamuse** [comment]
> @rhshadrach Sorry but I've been trying to get tests to pass locally and not having much success. I cloned a fresh repo from `pandas-dev:main`, setup my docker environment, cythonized, then ran tests from the `panda-dev` environment in conda and I get lots of fails even when trying different options with pytest. Could be something with my setup, I dug into a little bit but couldn't figure it out. I've decided to setup a draft PR in my fork for the change and see how the checks go there in case there's something strange happening in my environment. I'll keep checking locally, none of the tests are at all related to the change I made (removing that function in multi.py). I'll keep you posted.

encouragingly the CI tests all passed...I'll try to sort out my local environment but I think this PR should be okay
