### ISSUE TITLE
BUG: pandas/tests/test_algos.py::TestValueCounts::test_value_counts_normalized failing on ARM tests

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#49468]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
pytest pandas/tests/test_algos.py::TestValueCounts::test_value_counts_normalized[M8[ns]]
```

### Issue Description

See https://app.circleci.com/pipelines/github/pandas-dev/pandas?branch=main - looks like since https://github.com/pandas-dev/pandas/pull/49361, this has been failing

### Expected Behavior

cc @jbrockmendel @mroeschke does that PR look related? The test hits

https://github.com/pandas-dev/pandas/blob/4e7ade7d3e50e2b04d2f9150b59cf6f2d1fefd6d/pandas/core/arrays/datetimes.py#L2235

which was modified in that PR

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by jbrockmendel** [comment]
mentioned in #49361, it is plausible that changing that line to `data = data.astype("M8[ns]").view("i8")` will fix the weird ARM behavior
