### ISSUE TITLE
CI: only run pylint in CI

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#49526]
pylint is helping unearth some issues, but it's quite slow, especially for local development

as brought up on Slack by @jorisvandenbossche , let's just run it in CI instead

Task would be:

1. in

https://github.com/pandas-dev/pandas/blob/57d8d3a7cc2c4afc8746bf774b5062fa70c0f5fd/.pre-commit-config.yaml#L62-L65

add
```
        language: system
        pass_filenames: false
        stages: [manual]
```
2. modify the name of https://github.com/pandas-dev/pandas/blob/e02133c6323ddfd886784d6a9d3a4e5c07c99557/.github/workflows/code-checks.yml#L89-L93 to "Typing + pylint"

**Comment by the-lazy-learner** [comment]
Could I attempt resolving this issue? I'm mostly a beginner as of now.
Also, for the part, do we need to add these to args?
Please point me in the right direction, it'd be a lot helpful if there was place to refer for the first yaml file's syntax.
Thank you @MarcoGorelli I look forward to many more future collaboration with the community.

**Comment by MarcoGorelli** [comment]
sure, PRs welcome, here's the contributing guide https://pandas.pydata.org/docs/development/contributing.html

**Comment by the-lazy-learner** [comment]
By the way is it `language_version` instead of language?

**Comment by MarcoGorelli** [comment]
no

**Comment by the-lazy-learner** [comment]
Oh sorry. I just realised that looking at https://pre-commit.com/

**Comment by the-lazy-learner** [comment]
Please provide feedback on the PR #49527 . I need to learn more about the processes I guess.
