### ISSUE TITLE
DOC replace gitter link in README

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#49545]
In this note

https://github.com/pandas-dev/pandas/blob/2a2daf787c5bf4015729f6660d189389d3d7dc47/README.md?plain=1#L169

let's replace the second link with one which links to Slack https://pandas.pydata.org/docs/dev/development/community.html?highlight=slack#community-slack

**Comment by Mohd-Farhan** [comment]
Hello,
I am interrested in it.
Can u assign this to me?

**Comment by radojicic23** [comment]
I am interested

**Comment by radojicic23** [comment]
take

**Comment by radojicic23** [comment]
I've fixed this issue.
