### ISSUE TITLE
ENH: refactor pandas.isnull to improve code quality

### ISSUE THREAD

**Issue by Fitree** [pandas-dev/pandas#49563]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

`pandas.isnull` is an alias of the `pandas.isna` as below.
However, there is no code-level docstring on `pandas.isnull`.

```python
# pandas/pandas/core/dtypes/missing.py
# below code describes line 108 ~ 188

...

def isna(obj: object) -> bool | npt.NDArray[np.bool_] | NDFrame:
    """
    Detect missing values for an array-like object.
    ...
    """
    ...
    return _isna(obj)


isnull = isna

...
```

We can find similar pattern on the relationship between `DataFrame.isnull` and `DataFrame.isna`.
In this case, `DataFrame.isnull` has right docstring and is defined as well-constructed method at the same time.

```python
# pandas/pandas/core/frame.py
# below code describes line 6224 ~ 6228

...

    @doc(NDFrame.isna, klass=_shared_doc_kwargs["klass"])
    def isnull(self) -> DataFrame:
        """
        DataFrame.isnull is an alias for DataFrame.isna.
        """
        return self.isna()

...

```

### Feature Description

Instead of `isnull = isna`, define `pandas.isnull` as a function with docstring.

```python
# on pandas/pandas/core/dtypes/missing.py

...

def isnull(obj: object) -> bool | npt.NDArray[np.bool_] | NDFrame:
    """
    pandas.isnull is an alias for pandas.isna.
    """
    return isna(obj)

...
```

### Alternative Solutions

An alternative solution is to indicate in the docstring that `pandas.isnull` is an alias of the `pandas.isna`.

**Comment by phofl** [comment]
Yes this is shared docstring and works as intended.
