### ISSUE TITLE
BUG: Dataframe.to_excel treats decimal.Decimal as string instead of numeric type, the data in the Excel cell is formatted as a string, not a number

### ISSUE THREAD

**Issue by rspocz** [pandas-dev/pandas#49598]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
# ----------------------------------
### imports

import pandas as pd
import decimal as dc

# ----------------------------------
### definitions

value_str = '2.445'

# ----------------------------------
### initialization

df_float = pd.DataFrame(data=[float(value_str)])
df_decimal = pd.DataFrame(data=[dc.Decimal(value_str)])

# ----------------------------------
### exports

# excel
df_float.to_excel('float.xlsx')
df_decimal.to_excel('decimal.xlsx')
```

### Issue Description

The code writes value to float.xlsx as number, but it is written as string in decimal.xlsx.

I identified that in the condition here https://github.com/pandas-dev/pandas/blob/d56f6e2bca75f10bc490aa320c4e1bc295e367bd/pandas/io/excel/_base.py#L1367 decimal.Decimal datatype is not treated, and it is converted to string. I'd propose to return decimal.Decimal without converting to string, but it will require testing if excel writing libraries can handle it.

This same issue was already raised, but it was closed with no solution (by error?) https://github.com/pandas-dev/pandas/issues/26277

### Expected Behavior

Values in both dataframes should be written to excel as number.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 91111fd99898d9dcaa6bf6bedb662db4108da6e6
python           : 3.9.13.final.0
python-bits      : 64
OS               : Linux
OS-release       : 6.0.5-200.fc36.x86_64
Version          : #1 SMP PREEMPT_DYNAMIC Wed Oct 26 15:55:21 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.5.1
numpy            : 1.23.4
pytz             : 2022.6
dateutil         : 2.8.2
setuptools       : 65.5.1
pip              : 22.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by alexanderwertman3** [comment]
Hi, I would like to resolve this issue.

**Comment by phofl** [comment]
Investigations welcome, but the other issue indicates that openpyxl can not handle decimal.

**Comment by rspocz** [comment]
For openpyxl, decimal should be supported from version 1.7.0 (2013-10-31) https://foss.heptapod.net/openpyxl/openpyxl/-/blob/branch/3.0/doc/changes.rst

For xlsxwriter, decimal should be supported from version 0.3.8 (August 23 2013) https://xlsxwriter.readthedocs.io/changes.html

I found out both by quickly looking at the change log, needs to be confirmed. But it seems like an optimistic start.

@alexanderwertman3 Do you have time to investigate in more detail the compatibility with openpyxl/xlsxwriter and, eventually, propose change in code? Otherwise, I can have a look in couple of weeks. Thanks

**Comment by alexanderwertman3** [comment]
@rspocz, I will begin investigating this week

**Comment by alexanderwertman3** [comment]
Yes, it seems based on the change logs for openpxyl and xlsxwriter, decimal should be supported. @phofl, was there a reason cited as to why openpyxl cannot handle decimal from the other [issue](https://github.com/pandas-dev/pandas/issues/26277)

**Comment by alexanderwertman3** [comment]
* In pandas/pandas/io/excel/_base.py, lines 49-54, is_bool, is_float, is_integer, etc. are imported from pandas.core.dtypes.common, which imports them from pandas.core.dtypes.inference, which imports them from pandas._libs.lib. 
* In pandas/_libs/lib.pyi, is_decimal is defined. 

I believe we just need to add is_decimal to the list of methods imported here  in pandas/pandas/io/excel/_base.py:
<img width="298" alt="Screen Shot 2022-11-28 at 12 54 34 PM" src="https://user-images.githubusercontent.com/56045351/204347133-384522b7-34a1-4689-bdaa-7ef408781c66.png">

and then call the method in an elif block here:
<img width="417" alt="Screen Shot 2022-11-28 at 12 55 23 PM" src="https://user-images.githubusercontent.com/56045351/204347263-9b1c708f-93b7-4515-998b-d1182a414beb.png">

so that we can return val as a decimal.Decimal type, rather than returning a string.
