### ISSUE TITLE
DOC add git fetch upstream to instructions

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#49638]
Seems like forks on GitHub no longer come with tags by default, and this is causing issues for a few new contributors

Let's just a line with `git fetch upstream` right after:

https://github.com/pandas-dev/pandas/blob/e23492800af4ca9e307b0f9430bcd6f354d6fcf2/doc/source/development/contributing.rst#L139

**Comment by ramvikrams** [comment]
Done sir
