### ISSUE TITLE
STYLE enable pylint's redefined-outer-name

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#49656]
This warning could potentially prevent bugs, so I'm pretty keen on putting in the effort to enable it.

Many people can work on this one together. To work on it, please:
1. choose 2-3 files
2. make sure you have `pylint` version 2.15.5 installed (`pip install pylint==2.15.5`) - check this is the same as the number in the `.pre-commit-config.yaml` file
3. for each file, run `pylint --disable=all --enable=redefined-outer-name <file>`
4. fix up the file until it passes
5. stage, commit, push, open pull request

For example, suppose you choose the file `pandas/io/json/_table_schema.py`. Running `pylint` on it, you get:
```
$ pylint --disable=all --enable=redefined-outer-name pandas/io/json/_table_schema.py
************* Module pandas.io.json._table_schema
pandas/io/json/_table_schema.py:314:23: W0621: Redefining name 'json' from outer scope (line 15) (redefined-outer-name)

-----------------------------------
Your code has been rated at 9.92/10
```

If we look at that file, we see that there's a function
```python
def parse_table_schema(json, precise_float):
```
which takes `json` as an argument, but the file also has
```python
from pandas._libs import json
```
at the top.

The simplest fix is probably to just modify the import to be
```python
from pandas._libs.json import loads
```
and then to remove

https://github.com/pandas-dev/pandas/blob/f9ff3796329e4bedb4a5477739f5eb8d2e40761d/pandas/io/json/_table_schema.py#L44

as `loads` is the only function used from `pandas._libs.json`.

---

Other notes:
1. multiple people can work on this issue at the same time, please don't comment 'take'
2. please choose no more than 3 files to work on in the same PR. Comment which files you'd like to take so we don't duplicate work

It's probably worth running `pylint` on a directory first to see what files need working on, e.g.
```
pylint --disable=all --enable=redefined-outer-name pandas/io/
```

---

Files that still need fixing:

- pandas/_version.py
- pandas/conftest.py
- pandas/core/generic.py
- pandas/core/internals/concat.py
- pandas/core/reshape/merge.py
- pandas/core/tools/datetimes.py
- pandas/io/formats/format.py
- pandas/io/formats/style.py
- pandas/io/json/_json.py
- pandas/io/xml.py
- pandas/util/_decorators.py
- pandas/util/_doctools.py

Let's ignore test files for now

**Comment by grtcoder** [comment]
Hey, I would like to work on this

**Comment by MarcoGorelli** [comment]
go ahead - as mentioned in the issue:

> please choose no more than 3 files to work on in the same PR. Comment which files you'd like to take so we don't duplicate work

**Comment by ramvikrams** [comment]
I'll take `pandas\core\algorithms.py` , `pandas\core\generic.py` , `pandas\core\resample.py` these three files

**Comment by grtcoder** [comment]
I'll take 

1. `pandas\core\accessor.py` 
2. `pandas\core\api.py`
3. `pandas\core\apply.py`

**Comment by giridhrubajyoti2002** [comment]
I'll take `pandas/core/internals/concat.py`, `pandas/core/reshape/merge.py`, `pandas/io/json/_json.py`.

**Comment by bhaveshrp** [comment]
I'll take

1. pandas\core\frame.py
2. pandas\core\dtypes\inference.py

**Comment by alphacrack** [comment]
I'll take:
pandas/core/dtypes/cast.py
pandas/core/dtypes/dtypes.py
pandas/core/indexes/base.py

**Comment by aditya-anulekh** [comment]
Added a pull request fixing the following files

* `pandas/core/indexes/datetimes.py`
* `pandas/io/formats/xml.py`
* `pandas/io/json/_table_schema.py`

**Comment by nandinimalik16** [comment]
I will take

1. pandas/_version.py
2. pandas/conftest.py
3. pandas/io/formats/format.py

**Comment by isaac-chung** [comment]
I'll take:

1. `pandas/io/formats/style.py`
2. `pandas/io/json/_json.py`
3. `pandas/io/xml.py`

**Comment by mshumayl** [comment]
Hi, I'd like to work on:
1. `pandas/util/_decorators.py`
2. `pandas/util/_doctools.py`
3. `pandas/util/_test_decorators.py`

**Comment by seanjedi** [comment]
Hi, I'd like to work on: 
1. `pandas/io/formats/style.py`
2. `pandas/io/json/_json.py`
3. `pandas/io/xml.py`

**Comment by zemnly** [comment]
Are there any files which haven't been taken so I can work on them?

**Comment by MarcoGorelli** [comment]
Yeah there's still some, I've updated the issue with an up-to-date list

Note that https://github.com/pandas-dev/pandas/pull/49668/files is already tackling some, but the rest should be up for grabs

Thanks all for your help with this one 🙏

**Comment by calhockemeyer** [comment]
I will take: `pandas/core/resample.py`. I think that's the only file that hasn't been taken

**Comment by bang128** [comment]
Can I also contribute to `pandas/core/algorithms.py`?

**Comment by ramvikrams** [comment]
> Can I also contribute to `pandas/core/algorithms.py`?

Yes you can i'll leave that file

**Comment by bang128** [comment]
> > Can I also contribute to `pandas/core/algorithms.py`?
> 
> Yes you can i'll leave that file

Thank you so much!

**Comment by zmwaris1** [comment]
Hey, I'd like to contribute to if anyone else is not already working on it:
`pandas/core/internals/concat.py`
`pandas/core/reshape/merge.py`
`pandas/io/json/_json.py`

Thanks.

**Comment by MarcoGorelli** [comment]
@zmwaris1 please do - I've updated the list of files which still need doing

**Comment by seanjedi** [comment]
@zmwaris1 I apologize for the lateness, been having a hectic past two days. 
I saw your post above, and I wanted you to know that I have been working on `pandas/io/json/_json.py` on my fork recently here: https://github.com/seanjedi/pandas/tree/seanjedi-49724_pylint's_redefined_outer_name
I just wanted you to know so that we don't duplicate work effort. 
Feel free to take a look at it and let me know if I made a mistake or if you have any suggestions on making it better.

**Comment by wchung42** [comment]
Hi, are there any files that still needs to be worked on?

**Comment by MarcoGorelli** [comment]
yup, check the issue description

**Comment by JasmandeepKaur** [comment]
Hi, I'll be working on these files:
```
pandas/util/_decorators.py
pandas/util/_doctools.py
pandas/util/_test_decorators.py
```

**Comment by MarcoGorelli** [comment]
let's leave out `pandas/util/_test_decorators.py`, but the other two are fine

**Comment by JasmandeepKaur** [comment]
> let's leave out `pandas/util/_test_decorators.py`, but the other two are fine

Will do.

**Comment by angularOcean** [comment]
Cross referencing the files that need fixing list with what people have commented on taking it, it looks like everything has/is being  handled, is there any other files that need working on?

**Comment by angularOcean** [comment]
Okay it doesn't look like a PR has been opened for `pandas/core/tools/datetimes.py` or `pandas/io/formats/format.py` so I will try taking on those two.

**Comment by MarcoGorelli** [comment]
We're almost done, there's just:

- pandas/io/formats/format.py
- pandas/core/generic.py

left

If anyone wants to take them, and then (in the same PR) remove these lines from `.pre-commit-config.yaml`, then we can close the issue

https://github.com/pandas-dev/pandas/blob/0429b648709de4af526c8a65313b60a8f7419f1d/.pre-commit-config.yaml#L81-L83

**Comment by Thextan** [comment]
I will make changes to pandas/core/generic.py and pandas/.pre-commit-config.yaml.
This is my first time contributing and I am not very familiar with git so, please help me out if I am doing anything wrong.

**Comment by angularOcean** [comment]
@Thextan I think we need to fix both format.py and generic.py before we can remove the lines from .pre-commit-config.yaml

**Comment by Thextan** [comment]
@angularOcean  when I ran my check it looked like someone had already fixed io/formats/format.py.  I could be mistaken about that.  And my changes are not passing the checks, so I may not even be ready for this simple beginner task.

**Comment by MarcoGorelli** [comment]
I'll take a look tomorrow,  but if you search for the pandas contributing guide you'll find instructions for how to run the precommit checks

**Comment by Thextan** [comment]
Please feel free to pick up the changes to core/generic.py, io/formats/format.py (if it still needs work), and .pre-commit-config.yaml.  I am reading through the contributing guide to make sure I am doing things correctly.

**Comment by MarcoGorelli** [comment]
@Thextan not sure what you mean, sorry - your PR has been reviewed, do you plan to address the review? If not, no worries, that's fine, but please close the PR so others can work on it

**Comment by MarieKMiko** [comment]
If there are still changes to be made to pandas/io/formats/format.py or pandas/core/generic.py, I'm happy to take these on

**Comment by MarcoGorelli** [comment]
Yup, they're still open, if you wanted to submit a PR that'd be great, feel free to reach out (here or on the slack) if anything trips you up

**Comment by antocommi** [comment]
i'll take `pandas/core/generic.py`

**Comment by bang128** [comment]
Have anyone taken pandas/io/formats/format.py yet? If not, can I take it?

**Comment by MarcoGorelli** [comment]
only generic is left, if anyone wants to finish off this issue

**Comment by bang128** [comment]
I can take it if no one is working on it

**Comment by MarcoGorelli** [comment]
go ahead thanks

**Comment by MarcoGorelli** [comment]
Looks like we forgot to remove this line

https://github.com/pandas-dev/pandas/blob/a955989e033a288a659c4eca46490e7c26aaf93a/.pre-commit-config.yaml#L97

anyone feel like opening a PR to remove it?
