### ISSUE TITLE
BUG: groupby.fillna reorders results when dropping a null value

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#49651]
```
df = pd.DataFrame({"a": [1, 2, 1, 1, None], "b": [0, 1, 2, 3, 4]})
gb = df.groupby(["a"], dropna=True)
print(gb.fillna(0))
#      b
# 0  0.0
# 1  3.0
# 2  1.0
# 3  2.0
# 4  NaN
```

When a null value is dropped, the output can get ordered incorrectly. The expected order of values for `b` is `[0.0, 1.0, 2.0, 3.0, np.nan]`.

**Comment by SiboXu** [comment]
I played around with the groupby dropna option, looks like when dropna=True, the groupby is ignoring the NaN key as the document stated. 

> By default NA values are excluded from group keys during the groupby operation. However, in case you want to include NA values in group keys.

However, when the fillna is being applied to the GroupBy object, it somehow keeps the Nan key and messes up the order. Without the dropna, the order was kept. Also, do you think the expect values for `b` should actually be `[0, 1, 2, 3]`?

```python
import pandas as pd

df = pd.DataFrame({"a": [1, 2, 1, 1, None], "b": [0, 1, 2, 3, 4]})
df_dropna = df.groupby(["a"], dropna=True)

for name, group in df_dropna:
    print(f'group name {name}')
    print(group)

# group name 1.0
#      a  b
# 0  1.0  0
# 2  1.0  2
# 3  1.0  3
# group name 2.0
#      a  b
# 1  2.0  1

# for comparison of keeping NaN key in the groupby
df = pd.DataFrame({"a": [1, 2, 1, 1, None], "b": [0, 1, 2, 3, 4]})
df_dropna = df.groupby(["a"], dropna=False)

for name, group in df_dropna:
    print(f'group name {name}')
    print(group)

# group name 1.0
#      a  b
# 0  1.0  0
# 2  1.0  2
# 3  1.0  3
# group name 2.0
#      a  b
# 1  2.0  1
# group name nan
#     a  b
# 4 NaN  4
```

**Comment by rhshadrach** [comment]
> Also, do you think the expect values for `b` should actually be `[0, 1, 2, 3]`?

No - I don't think so. That would be values-specific behavior which we generally stay away from. That is, pandas can't tell the difference between float values that are meant to be float but happen to be integral and float values that were integral but coerced to float because of `np.nan`. Instead of guessing, best to take no action and not downcast.

**Comment by rhshadrach** [comment]
groupby.dropna is now deprecated; closing.
