### ISSUE TITLE
REF: refactor tests.indexes.base_index::TestIndex

### ISSUE THREAD

**Issue by topper-123** [pandas-dev/pandas#49679]
A lot of the tests in `tests.indexes.base_index::TestIndex`look like they could like they could be improved to moving them to `tests.indexes.common.Base` and adapting subclasses as needed. This would give better test coverage.

See discussion in https://github.com/pandas-dev/pandas/pull/49678#discussion_r1020889176.

**Comment by mroeschke** [comment]
Looks like these tests have been refactored in the meantime so closing
