### ISSUE TITLE
ENH: Stop breaking stuff

### ISSUE THREAD

**Issue by spillz** [pandas-dev/pandas#49703]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Almost every new version of pandas breaks a lot of code, much more than version upgrades of all other libraries my team uses. It would be really beneficial to the community to have a much more stable, and planned out, API.

### Feature Description

Make API breaking changes every other major release. Developers should justify all API breaks and look for alternatives to breaking the API.

### Alternative Solutions

Add a backward compatibility support layer that when toggled on allows old version of code to continue to function.

**Comment by jreback** [comment]
if u have constructive comments then we are happy to hear about them

pandas is an open source package and you or anyone out there is welcome to contribute and make things better
