### ISSUE TITLE
DOC: cross missing in how set of params

### ISSUE THREAD

**Issue by debnathshoham** [pandas-dev/pandas#49733]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html

### Documentation problem

Although there is a bullet point added for cross, it's missing from the top set

### Suggested fix for documentation

add `cross` in the set of `how` params

![Screenshot 2022-11-16 at 10 35 13 PM](https://user-images.githubusercontent.com/6472290/202247201-37345c21-fd26-4dcb-adf6-e75fdacc648b.png)

**Comment by phofl** [comment]
Hi, thanks for your report. This is already added on the dev docs
