### ISSUE TITLE
Replace get_c_string_buf_and_size with PyUnicode_AsUTF8AndSize

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#49760]
We have a function in pandas/_libs/tslibs/util.pxd called `get_c_string_buf_and_size` . I think this served a purpose when we had Python 2/3 compat but at the moment it just wraps the standard `PyUnicode_AsUTF8AndSize` function, so it adds an unnecessary layer

**Comment by WillAyd** [comment]
On review I don't think this exists in Cython so needs to be added upstream first

**Comment by WillAyd** [comment]
This will depend on https://github.com/cython/cython/pull/5163

**Comment by mmc1718** [comment]
take

**Comment by WillAyd** [comment]
@mmc1718 thanks for offering. We need to wait a bit on this though until our minimum Cython version has this function. This was just added upstream in https://github.com/cython/cython/pull/5163

**Comment by mmc1718** [comment]
Ah ok, no worries. Thanks for explaining :)

**Comment by WillAyd** [comment]
The tooling is there now to do this, but looks like it was already solved. Thanks @mmc1718 for your offer
