### ISSUE TITLE
DOC: Creating development environment  - BT for Visual Studio version

### ISSUE THREAD

**Issue by honza26** [pandas-dev/pandas#49799]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/development/contributing_environment.html#option-1-creating-an-environment-without-docker

### Documentation problem

Installation guide points to installation of  Visual Studio 2019: 

'You will need [Build Tools for Visual Studio 2019](https://visualstudio.microsoft.com/downloads/).'

However on the linked website there already version 2022. While version 2019 could be find in 'Older downloads'. Therefore it is confusing for new users which version should be used.

### Suggested fix for documentation

Test whether setting environment using Build Tools for Visual Studio 2022 works well:

a) If yes, update it in documentation and provide correct link

b) In not, provide alternative link to 2019 version, and give warning that it is necessary to use specifically this version.

**Comment by natmokval** [comment]
take
