### ISSUE TITLE
DataFrame.rename renames wrong elements

### ISSUE THREAD

**Issue by fonnesbeck** [pandas-dev/pandas#4980]
When specifying a dictionary map for renaming the index of a DataFrame, the renaming ends up including column values as well, even when they are not of the same type. For example, in the screen shot below, I have demographic information on race coded as integers 1-7 that I am remapping to string representations, and boolean values for the column headers specifying case status. When I specify a dictionary of mappings from integers to strings as the `index` argument, it treats the `True` value in the column header as a 1 and substitutes it. 

![screen shot 2013-09-25 at 9 39 12 am](https://f.cloud.github.com/assets/81476/1209801/477a0822-25f0-11e3-8c54-42c48f6ea09a.png)

Even if I specify value for `columns` it does not change the behavior.

**Comment by DriesSchaumont** [comment]
take

**Comment by DriesSchaumont** [comment]
I am not able to reproduce this issue on current master. In the following example, only the index values are renamed, so that is correct. I will open a PR to add a test.
```python3
>>> import pandas as pd
>>> import numpy as np
>>> df = pd.DataFrame(np.arange(15).reshape(3,5),columns=[False,True,2, 3, 4])
>>> df
   False  True   2   3   4
0      0     1   2   3   4
1      5     6   7   8   9
2     10    11  12  13  14
>>> mapper = {0: 'foo', 1: 'bar', 2: 'bah'}
>>> df.rename(index=mapper)
     False  True   2   3   4
foo      0     1   2   3   4
bar      5     6   7   8   9
bah     10    11  12  13  14
```
