### ISSUE TITLE
BUG: transform("max") replaces all entries with NaN when applied after groupby with as_index=False

### ISSUE THREAD

**Issue by Verena1695** [pandas-dev/pandas#49834]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({"key": ["a", "b", "c", "b", "a"], "value": [False, False, True, False, True]}, index=[7, 2, 5, 3, 9])

df

Out[4]:
  key  value
7   a  False
2   b  False
5   c   True
3   b  False
9   a   True

df.groupby("key", as_index=False).transform("max")

Out[5]:
   key value
7  NaN   NaN
2  NaN   NaN
5  NaN   NaN
3  NaN   NaN
9  NaN   NaN

df.groupby("key", as_index=True).transform("max")

Out[6]:
   value
7   True
2  False
5   True
3  False
9   True
```

### Issue Description

When using _transform("max")_ after groupby with _as_index=False_, all entries in the original dataframe are converted to NaN. This is not only the case for "max" but also for "min" as well as "sum" or "mean" when having integers in the "value" column.

When using _as_index=True_ instead, the transform works as expected, however, the "key" column does not appear as an index but simply disappears from the dataframe.

### Expected Behavior

1. I would expect that when using _as_index=False_ only the entries in the "value" column change, i.e. change to

True
False
True
False
True

2. I would expect that when using _as_index=True_ the "key" column appears as an index.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 91111fd99898d9dcaa6bf6bedb662db4108da6e6
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.104-linuxkit
Version          : #1 SMP Thu Mar 17 17:08:06 UTC 2022
machine          : x86_64
processor        :
byteorder        : little
LC_ALL           : C.UTF-8
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.1
numpy            : 1.23.4
pytz             : 2022.4
dateutil         : 2.8.2
setuptools       : 58.1.0
pip              : 21.2.4
Cython           : None
pytest           : 7.2.0
hypothesis       : 5.23.7
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.6
jinja2           : 3.1.2
IPython          : 8.5.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2022.02.0
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 5.0.0.2
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.0
snappy           : None
sqlalchemy       : 1.3.24
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : 0.14.0
tzdata           : None

</details>

**Comment by asishm** [comment]
related : https://github.com/pandas-dev/pandas/issues/37093

**Comment by rhshadrach** [comment]
Thanks for the report! Haven't run a git bisect but it will undoubtedly point to one of my PRs. Should be able to get a fix in for 1.5.3.

@phofl

> I don't think that this should work. max is a reducer and should be used with agg and not transform.

When given a reducer, transform will compute the result and then broadcast it to each group. E.g.

```
df = pd.DataFrame({"a": [1, 1, 2, 2, 2], "b": range(5)})
result = df.groupby("a", as_index=True).transform("max")
print(result)

#    b
# 0  1
# 1  1
# 2  4
# 3  4
# 4  4
```

**Comment by rhshadrach** [comment]
@Verena1695 

> 2\. I would expect that when using _as_index=True_ the "key" column appears as an index.

`as_index` only has an effect when doing an aggregation, not a transform; see the documentation here: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html

The result you want can be achieved by 

```
df = pd.DataFrame({"key": ["a", "b", "c", "b", "a"], "value": [False, False, True, False, True]}, index=[7, 2, 5, 3, 9])
transformed = df.groupby("key").transform("max")
result = pd.concat([df["key"], transformed], axis=1)
```

**Comment by rhshadrach** [comment]
> I would expect that when using as_index=True the "key" column appears as an index.

@Verena1695 - we've been discussing if there should be an option in groupby for users to get the groups for a transform in the index (or columns) of the result. The question we have is if there are use cases for this - I've never had one in my experience. Do you have a use case where you want the keys in the result? If so, could you share any details on your use?

**Comment by Verena1695** [comment]
Thanks for your comments. I discussed with the team and we came to the conclusion that we don't have a use case for having the groups in the index/columns of the result.
