### ISSUE TITLE
REF: Move `to_dict` implementation to pandas.core.methods.to_dict

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#49845]
Ref: https://github.com/pandas-dev/pandas/pull/46487#pullrequestreview-1059398661

For code organization, it'd be good to get the implementation of these methods out of `frame.py` and to a more suitable location - `pandas.core.methods.to_dict`

**Comment by jbrockmendel** [comment]
i dont think the `to_*` heuristic works.  you wouldn't want to move `to_numpy` to pd.io would you?  Certainly not to_timestamp?

**Comment by jbrockmendel** [comment]
> I don't see a good location for something like this.

ive been thinking a core/methods/ directory might be good for files that are basically just individual refactored-out methods (e.g. describe.py)

**Comment by jreback** [comment]
+1 in @jbrockmendel idea

**Comment by kostyafarber** [comment]
Does this still need discussion, happy to have a stab at this if we want to go ahead with the refactor
