### ISSUE TITLE
json_normalize - incorrect removing separator from beginning of key 

### ISSUE THREAD

**Issue by iyonchev** [pandas-dev/pandas#49861]
```
print(pd.__version__)
jsn={'_id':{'a1':10,"l2":{"l3":0}}, "gg":4}
display(pd.json_normalize(jsn,sep='_'))
```
**Actual result:**
<html>
<body>
<div class="output_container" style="width: 1488px; color: rgb(212, 212, 212); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; position: absolute; overflow: hidden; max-height: 38px; top: 139px; height: 38px;"><div id="7476dd05-ca50-4023-8be0-d1bea8262b70" class="output" output-mime-type="application/vnd.code.notebook.stdout" style="font-size: var(--notebook-cell-output-font-size); width: var(--notebook-output-width); margin-left: var(--notebook-output-left-margin); padding-top: var(--notebook-output-node-padding); padding-right: var(--notebook-output-node-padding); padding-bottom: var(--notebook-output-node-padding); padding-left: var(--notebook-output-node-left-padding); box-sizing: border-box; border-right-color: ; border-right-style: ; border-right-width: ; border-bottom-color: ; border-bottom-style: ; border-bottom-width: ; border-left-color: ; border-left-style: ; border-left-width: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; background-color: var(--theme-notebook-output-background); border-top: none !important; overflow-x: auto; position: absolute; top: 0px; left: 0px;"><span class="output-stream" style="line-height: var(--notebook-cell-output-line-height); font-family: var(--notebook-cell-output-font-family); white-space: pre-wrap; overflow-wrap: break-word; font-size: var(--notebook-cell-output-font-size); user-select: text; cursor: auto; display: inline-block;"><span><span class="">1.5.2
</span></span></span></div></div><div class="output_container" style="width: 1488px; color: rgb(212, 212, 212); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; position: absolute; overflow: hidden; max-height: 69px; top: 177px; height: 69px;"><div id="986235ea-87ad-4f17-8396-4d675cccdcd3" class="output" style="font-size: var(--notebook-cell-output-font-size); width: var(--notebook-output-width); margin-left: var(--notebook-output-left-margin); padding-top: var(--notebook-output-node-padding); padding-right: var(--notebook-output-node-padding); padding-bottom: var(--notebook-output-node-padding); padding-left: var(--notebook-output-node-left-padding); box-sizing: border-box; border-right-color: ; border-right-style: ; border-right-width: ; border-bottom-color: ; border-bottom-style: ; border-bottom-width: ; border-left-color: ; border-left-style: ; border-left-width: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; background-color: var(--theme-notebook-output-background); border-top: none !important; overflow-x: auto; position: absolute; top: 0px; left: 0px;"><div><div>

  gg | id_a1 | id_l2_l3
-- | -- | --
4 | 10 | 0

</div></div></div></div>
</body>
</html>

**Expected result:**
the "_" prefix should not be removed from the beginning of the column names.
<html>
<body>
<div class="output_container" style="width: 1488px; color: rgb(212, 212, 212); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; position: absolute; overflow: hidden; max-height: 38px; top: 139px; height: 38px;"><div id="7ee93b6f-24e4-404a-9135-c8923ba9e795" class="output" output-mime-type="application/vnd.code.notebook.stdout" style="font-size: var(--notebook-cell-output-font-size); width: var(--notebook-output-width); margin-left: var(--notebook-output-left-margin); padding-top: var(--notebook-output-node-padding); padding-right: var(--notebook-output-node-padding); padding-bottom: var(--notebook-output-node-padding); padding-left: var(--notebook-output-node-left-padding); box-sizing: border-box; border-right-color: ; border-right-style: ; border-right-width: ; border-bottom-color: ; border-bottom-style: ; border-bottom-width: ; border-left-color: ; border-left-style: ; border-left-width: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; background-color: var(--theme-notebook-output-background); border-top: none !important; overflow-x: auto; position: absolute; top: 0px; left: 0px;"><span class="output-stream" style="line-height: var(--notebook-cell-output-line-height); font-family: var(--notebook-cell-output-font-family); white-space: pre-wrap; overflow-wrap: break-word; font-size: var(--notebook-cell-output-font-size); user-select: text; cursor: auto; display: inline-block;"><span><span class="">1.5.2
</span></span></span></div></div><div class="output_container" style="width: 1488px; color: rgb(212, 212, 212); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; position: absolute; overflow: hidden; max-height: 69px; top: 177px; height: 69px;"><div id="56804fb0-c639-49ca-8b68-c21d199c20c0" class="output" style="font-size: var(--notebook-cell-output-font-size); width: var(--notebook-output-width); margin-left: var(--notebook-output-left-margin); padding-top: var(--notebook-output-node-padding); padding-right: var(--notebook-output-node-padding); padding-bottom: var(--notebook-output-node-padding); padding-left: var(--notebook-output-node-left-padding); box-sizing: border-box; border-right-color: ; border-right-style: ; border-right-width: ; border-bottom-color: ; border-bottom-style: ; border-bottom-width: ; border-left-color: ; border-left-style: ; border-left-width: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; background-color: var(--theme-notebook-output-background); border-top: none !important; overflow-x: auto; position: absolute; top: 0px; left: 0px;"><div><div>

  gg | _id_a1 | _id_l2_l3
-- | -- | --
4 | 10 | 0

</div></div></div></div>
</body>
</html>

**This issue was introduced with the following change:**
https://github.com/pandas-dev/pandas/pull/40035/files

**Comment by iyonchev** [comment]
`display(pd.json_normalize(jsn,sep='_', max_level=5))`
passing max_level value could be used to prevent the execution of the new methods(from the change above) and execute the main one...

**Comment by jbrockmendel** [comment]
Cc @WillAyd
