### ISSUE TITLE
DOC: Update Benchmark Link

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#49871]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/development/maintaining.html#benchmark-machine

### Documentation problem

This points to an old asv site that is no longer maintained. Should be pointing to https://asv-runner.github.io/asv-collection/pandas/

### Suggested fix for documentation

Change link to https://asv-runner.github.io/asv-collection/pandas/

**Comment by etaylorcdp** [comment]
take

**Comment by Idilismiguzel** [comment]
take

**Comment by phofl** [comment]
#50006
