### ISSUE TITLE
ENH: inconsistent naming convention for read_csv and read_excel column selection

### ISSUE THREAD

**Issue by alefnula** [pandas-dev/pandas#4988]
`read_csv` uses the `usecols` parameter, and the `read_excel` function uses `parse_cols` parameter. Both parameter do basically the same thing:

```
usecols : array-like
    Return a subset of the columns.
    Results in much faster parsing time and lower memory usage.
```

```
parse_cols : int or list, default None
    * If None then parse all columns,
    * If int then indicates last column to be parsed
    * If list of ints then indicates list of column numbers to be parsed
    * If string then indicates comma separated list of column names and
      column ranges (e.g. "A:E" or "A,C,E:F")
```

Also maybe supporting the same thing that `parse_cols` does in `usecol` wouldn't be so bad?

**Comment by jreback** [comment]
If someone is interested in this, we should deprecate ``parse_cols`` in favor of ``usecols``

**Comment by abarber4gh** [comment]
taking a look at this, I plan to deprecate `parse_cols` for `read_excel()` in favor of `usecols` for consistency with other read functions.  plan for `usecols` to support current functionality of `read_excel()`'s `parse_cols` and other `usecols`.  Basically, @alefnula's points 2, 3, and 4 above.  point 1 (implement column selection functionality for all `read` functions probably should be another ENH.

**Comment by abarber4gh** [comment]
in the current release version (0.20.1), a list of columns returns an empty DF.  I.E. ``pandas.read_excel(test_inputexcel_file, parse_cols=['A','B','D']) `` results in 
````
Empty DataFrame
Columns: []
Index: []
````
rather than the expected DataFrame with columns A, B, and D.  I plan to address this as well to implement @alefnula's point 3.

**Comment by jreback** [comment]
@gfyoung anything worth changing for 0.21.0 for this? (prob in ``read_excel``) that isn't already done / in an issue?

**Comment by gfyoung** [comment]
@jreback : I agree with you <a href="https://github.com/pandas-dev/pandas/issues/4988#issuecomment-209714290">from a year ago</a> that `parse_cols` should be deprecated in favor of `usecols`.  I don't see why we shouldn't aim to do this in `0.21.0`.
