### ISSUE TITLE
BUG: `pd.DateOffset` only handles `milliseconds` keyword argument if other keyword args are shorter than `day/days`

### ISSUE THREAD

**Issue by wence-** [pandas-dev/pandas#49897]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
pd.DataOffset(milliseconds=1, days=1)
```

### Issue Description

```
TypeError                                 Traceback (most recent call last)
Input In [54], in <cell line: 1>()
----> 1 pd.DateOffset(milliseconds=1, days=1)

File ...pandas/_libs/tslibs/offsets.pyx:1233, in pandas._libs.tslibs.offsets.RelativeDeltaOffset.__init__()

File ...pandas/_libs/tslibs/offsets.pyx:325, in pandas._libs.tslibs.offsets._determine_offset()

TypeError: relativedelta.__init__() got an unexpected keyword argument 'milliseconds'
```

In contrast, if I pass `millisecond` (no plural) I get a more useful error:

```
NotImplementedError: Using DateOffset to replace `millisecond` component in datetime object is not supported. Use `microsecond=timestamp.microsecond % 1000 + ms * 1000` instead.
```

### Expected Behavior

Since `DateOffset` advertises that it takes `milliseconds` and `millisecond` as keyword arguments, it should be possible to construct a `DateOffset` using those arguments in combination with others.

[I would have a go at fixing this, but I cannot make head or tail of the intended logic in `_libs.tslibs.offset._determine_offset`. Comments don't appear to match the code behaviour, and I don't know how many moving parts there are here].

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e41b6d7827720df90a51ff05caa689333d7e02af
python           : 3.10.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.6.0
Version          : Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 2.0.0.dev0+643.ge41b6d7827.dirty
numpy            : 1.23.4
pytz             : 2022.6
dateutil         : 2.8.2
setuptools       : 65.5.1
pip              : 22.3.1
Cython           : 0.29.32
pytest           : 7.2.0
hypothesis       : 6.56.4
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.9.1
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : 2.9.3
jinja2           : 3.0.3
IPython          : 8.6.0
pandas_datareader: 0.10.0
bs4              : 4.11.1
bottleneck       : 1.3.5
brotli           : 
fastparquet      : 0.8.3
fsspec           : 2021.11.0
gcsfs            : 2021.11.0
matplotlib       : 3.6.2
numba            : 0.56.3
numexpr          : 2.8.3
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : 0.17.9
pyarrow          : 9.0.0
pyreadstat       : 1.2.0
pyxlsb           : 1.0.10
s3fs             : 2021.11.0
scipy            : 1.9.3
snappy           : 
sqlalchemy       : 1.4.43
tables           : 3.7.0
tabulate         : 0.9.0
xarray           : 2022.11.0
xlrd             : 2.0.1
zstandard        : 0.19.0
tzdata           : None
qtpy             : None
pyqt5            : None

</details>

**Comment by markopacak** [comment]
`milliseconds` (plur) is a valid arg for `timedelta` but not for `relativedelta`. E.g. `timedelta(days=1, milliseconds=1)`  executes normally. So, maybe the expected behavior is to have `timedelta` handle milliseconds (plur).

However, the _if-condition_ at line 315 catches anything that has `days` in kwds and forwards it to `relativedelta`, hence causing and Exception (line 323).

https://github.com/pandas-dev/pandas/blob/dc5e00d91dd515e7aeff1b84967afa0b4d39adca/pandas/_libs/tslibs/offsets.pyx#L298-L334

Perhaps, adding a check for `milliseconds` (plur) right before, is the right direction to take. Something like

    if "milliseconds" in kwds_no_nanos:  # plural
        offset = timedelta(**kwds_no_nanos)

at line 316.

`relativedelta` does not support `millisecond` (sing) either, and we have a special check in place for it, so I don't see why there shouldn't be one for `milliseconds` (plur).

**Comment by mroeschke** [comment]
Yeah maybe if millisecond or milliseconds (singular or plural) are always provided `DateOffset` should just always used the non-relativedelta internal configuration.

**Comment by markopacak** [comment]
take

**Comment by markopacak** [comment]
`millsecond` (singular) is not a valid argument for `datetime.timedelta` (nor for relativedelta).

This is handled by raising

    NotImplementedError( 
        "Using DateOffset to replace `millisecond` component in " 
        "datetime object is not supported. Use " 
        "`microsecond=timestamp.microsecond % 1000 + ms * 1000` " 
        "instead." 
    ) 

Maybe, that's a conversion we could be doing ourselves instead of throwing an error. 

In general, this function can be rewritten better, but don't know if I it should be done in this PR.

**Comment by markopacak** [comment]
I added this fix for now.
In the meantime, I'm testing a reworked implementation of `_determine_offset` separately.

**Comment by markopacak** [comment]
Here is my initial approach to the rework I had in mind. 
I only have 2 tests failing. Haven't run all tests suites yet (only `test_offsets.py` and `test_datetime64.py`), but I think I'm close.

IMO, is much more readable then before. I will probably open a separate issue for this soon. Any thoughts?

https://github.com/pandas-dev/pandas/blob/6b2a7e054409909cd6072f01ca0d138985b09a4d/pandas/_libs/tslibs/offsets.pyx#L300-L364

**Comment by wence-** [comment]
How about:
```python
def determine_offset(kwargs):
    if not kwargs:
        return timedelta(days=1), False

    nanos = {"nanosecond", "nanoseconds"}
    kwargs_no_nano = {k: v for k, v in kwargs.items() if k not in nanos}
    kwargs_no_nano["microsecond"] += kwargs_no_nano.pop("millisecond", 0) * 1000

    use_relativedelta = {
        "year",
        "month",
        "day",
        "hour",
        "minute",
        "second",
        "microsecond",
        "weekday",
        "years",
        "months",
        "weeks",
        "days",
        "hours",
        "minutes",
        "seconds",
        "microseconds",
    }

    if all(k in use_relativedelta for k in kwargs_no_nano):
        return relativedelta(**kwargs_no_nano), True
    else:
        return timedelta(**kwargs_no_nano), False
```

Minor changes: use early returns in all cases (which removes the need for the `use_relativedelta` flag); handle the singular "millisecond" case (correctly, unlike the message in the `NotImplementedError`); no need for the special-casing of only nanosecond kwargs, since both `timedelta(**{})` and `relativedelta(**{})` DTRT
