### ISSUE TITLE
DOC: A very small typo error

### ISSUE THREAD

**Issue by ramvikrams** [pandas-dev/pandas#49900]
### Pandas version checks

- [x] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/groupby.html#indexing-iteration

### Documentation problem

In the file it is written 

`GroupBy.get_group(name[, obj])`

### Suggested fix for documentation

wheras it should be
`GroupBy.get_group(name, [obj])`

**Comment by asishm** [comment]
Thanks for the report.

The documentation is correct - the `[, obj]` denotes `obj` is optional.

See here on how to interpret them.
https://stackoverflow.com/questions/1718903/what-do-square-brackets-mean-in-function-class-documentation

**Comment by attack68** [comment]
@asishm is correct

**Comment by ramvikrams** [comment]
> Thanks for the report.
> 
> The documentation is correct - the `[, obj]` denotes `obj` is optional.
> 
> See here on how to interpret them. https://stackoverflow.com/questions/1718903/what-do-square-brackets-mean-in-function-class-documentation

thanks I didn't know it
