### ISSUE TITLE
add_prefix / add_suffix - why not using list comprehension under the hood?

### ISSUE THREAD

**Issue by Marmeladenbrot** [pandas-dev/pandas#49903]
Hi,  since this is not a usage related question I did not ask this on SO.
While scrolling through some pandas code for learning I saw that the `add_prefix` (and `add_suffix`) methods use this code:

```
f = functools.partial("{prefix}{}".format, prefix=prefix)
mapper = {self._info_axis_name: f}
return self._rename(**mapper)
```
source: https://github.com/pandas-dev/pandas/blob/v1.5.2/pandas/core/generic.py#L4616-L4678
(which I don't really understand to be honest)

but then in the unit test it uses this code:
`[f"foo#{c}" for c in float_frame.columns]`
source: https://github.com/pandas-dev/pandas/blob/baf1d2c80f41c51454a07917a28e6d0535880a0a/pandas/tests/frame/methods/test_add_prefix_suffix.py

Why not use a list comprehension under the hood as well when it appears to be faster than functools?
![grafik](https://user-images.githubusercontent.com/9965585/203869035-abbbd197-ef75-4ea1-9743-1f5eb9274337.png)
source: https://www.youtube.com/watch?v=32a9KOQRECA at 04:43

**Comment by attack68** [comment]
I expect there may be a few examples in the code where list comprehension may be better. The number of columns is normally not large so I expect the performance increase here to be neglible. But if anyone would like to attempt a PR and see if the benchmarks are improved we welcome new contributors.

**Comment by jbrockmendel** [comment]
I’d have to double check, but I think the method makes a copy, which the pinning does not
