### ISSUE TITLE
"The following argument was not expected: create" when creating environment

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#49959]
Some people are reporting issues creating a development environment, and that
```
mamba env create
```
gives
```
The following argument was not expected: create
```

I don't know if this is platform-specific, but it works for me on mamba 1.0.0 on Linux (WSL2).

The following seems to be working for people
```
mamba create --file environment.yml
```

We'll see at the pydataglobal sprint if the above works for everyone, and then we'll update the docs - in the meantime, this might help anyone for whom `mamba env create` isn't working

cc @datapythonista in case this is something you've come across

**Comment by datapythonista** [comment]
I've been using the command in Linux for a long time without issues. No idea what the problem can be.

**Comment by mgotrik** [comment]
I had something like this happen to me recently. The problem was that I had multiple versions of conda (mamba or some other package in your case). One in my local environment and one in the global. Try cleaning/updating all your packages

**Comment by emma-carballal** [comment]
take

**Comment by MarcoGorelli** [comment]
hi @emma-carballal - did `mamba create --file environment.yml` work for you?

**Comment by emma-carballal** [comment]
hi @MarcoGorelli , I got this with the original:
```
(pandas-dev) ➜  pandas-carballal git:(main) mamba env create 

CondaValueError: prefix already exists: /Users/nineve/opt/miniconda3/envs/pandas-dev
```
`mamba create --file environment.yml` creates an environment successfully.
