### ISSUE TITLE
DOC:  Docs for `groupby.transform()` should mention that function parameter can be a string in `transform` 

### ISSUE THREAD

**Issue by ramvikrams** [pandas-dev/pandas#49961]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.DataFrameGroupBy.transform.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.SeriesGroupBy.transform.html

### Documentation problem

the current doc does not indicate that a string is accepted as a function parameter `transform` in `groupby.transform()`.

### Suggested fix for documentation

docs for `transform` need to indicate that the function parameter in `groupby.transform()` can be a string function name, and that an example should be included.

**Comment by PranshuKaushal** [comment]
I would like to work on this.Can any tell me what to do once I open the link..This is my first issue.

**Comment by PranshuKaushal** [comment]
I would like to work on this. Assign me this issue please.

**Comment by ramvikrams** [comment]
> I would like to work on this. Assign me this issue please.

you are free to create a pr

**Comment by yuvanist** [comment]
take

**Comment by seanjedi** [comment]
@ramvikrams I will take your word on this comment: https://github.com/pandas-dev/pandas/issues/49961#issuecomment-1332572617
I created a PR here that I believe should fix this in the docs: https://github.com/pandas-dev/pandas/pull/50002

**Comment by ramvikrams** [comment]
@WillAyd  do we not have to add any example for it.

**Comment by seanjedi** [comment]
@ramvikrams I added this PR here for the comment you made here: https://github.com/pandas-dev/pandas/issues/49961#issuecomment-1334671820
https://github.com/pandas-dev/pandas/pull/50029

Please review and approve if this is what you meant
