### ISSUE TITLE
DOC: Building & Testing Required Additional Modules: libhdf5-serial-dev & liblzma-dev [on wsl / ubuntu]

### ISSUE THREAD

**Issue by haleemur** [pandas-dev/pandas#49989]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/development/contributing_environment.html#installing-a-c-compiler

### Documentation problem

Building and testing pandas from source with python version 3.10.4 required the following packages on Windows 11 / WSL [Ubuntu], which can be installed easily. However, I noticed they were not mentioned in the development set up guide.

* libhdf5-serial-dev
* liblzma-dev

The specific errors that I encountered are:

**build error**
```
Collecting tables
  Downloading tables-3.6.1.tar.gz (4.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 1.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      /tmp/H5closexok1otq5.c: In function ‘main’:
      /tmp/H5closexok1otq5.c:2:5: warning: implicit declaration of function ‘H5close’ [-Wimplicit-function-declaration]
          2 |     H5close();
            |     ^~~~~~~
      /usr/bin/ld: cannot find -lhdf5
      collect2: error: ld returned 1 exit status
      * Using Python 3.10.4 (main, Nov 29 2022, 16:56:07) [GCC 9.4.0]
      * USE_PKGCONFIG: True
      .. ERROR:: Could not find a local HDF5 installation.
         You may need to explicitly state where your local HDF5 headers and
         library can be found by setting the ``HDF5_DIR`` environment
         variable or by using the ``--hdf5`` command-line option.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**pytest error**
```
ImportError while importing test module '/home/hal/pandas/pandas/tests/io/xml/test_xml.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.pyenv/versions/3.8.13/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/io/xml/test_xml.py:7: in <module>
    from lzma import LZMAError
../../.pyenv/versions/3.8.13/lib/python3.8/lzma.py:27: in <module>
    from _lzma import *
E   ModuleNotFoundError: No module named '_lzma'
```

### Suggested fix for documentation

In the section [[Installing a C compiler](https://pandas.pydata.org/docs/dev/development/contributing_environment.html#id2), we should add a sub-section for installing additional development dependencies, for the two most popular linux package managers (apt & dnf).

we should also rename `yum` -> `dnf`

**Comment by lithomas1** [comment]
Thanks for reporting this. 

For pytables, you seem to be installing an old version of pytables, shown by you picking up the .tar.gz.

Can you try installing tables==3.7.0? Also, can you give your pip version? 

We should also not be erroring if lzma is not found. If you want to submit a PR for this, I can give you some next steps on how to get started.

**Comment by sqali** [comment]
Hi @lithomas1 ,

I would love to work on this issue, Can you provide instructions on the next steps?

**Comment by sqali** [comment]
take

**Comment by lithomas1** [comment]
I don't think there's anything left to do here for this issue.

OP has not replied with whether he is able to install the latest tables, and the lzma issue should be fixed already.
