### ISSUE TITLE
BUILD: Development Build Requires psycopg2, which depends on postgresql headers. We could change the dependency to psycopg2-binary

### ISSUE THREAD

**Issue by haleemur** [pandas-dev/pandas#49990]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31

### Installation Method

Built from source

### pandas Version

Main Branch, Commit: e35c0c4d9522f114b2c495b3fecc738367b16434

### Python Version

3.10.4

### Installation Logs

`python -m pip install -r requirements-dev.txt` fails with the following

<details>

Collecting psycopg2
  Using cached psycopg2-2.9.5.tar.gz (384 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-76yw0psq/psycopg2.egg-info
      writing /tmp/pip-pip-egg-info-76yw0psq/psycopg2.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-76yw0psq/psycopg2.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-pip-egg-info-76yw0psq/psycopg2.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-76yw0psq/psycopg2.egg-info/SOURCES.txt'

      Error: pg_config executable not found.

      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:

          python setup.py build_ext --pg-config /path/to/pg_config build ...

      or with the pg_config option in 'setup.cfg'.

      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.

      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

</details>

Note that I found changing `psycopg2` to `psycopg2-binary` in `requirements-dev.txt` solves this issue. Alternatively, I could have installed the postgresql headers, but since that can be avoided, I think updating `requirements-dev.txt` should be preferred.

**Comment by mzeitlin11** [comment]
Thanks @haleemur - is this fixed by #49982?

**Comment by haleemur** [comment]
I believe so. What a quick turnaround!
