### ISSUE TITLE
ENH: Allow `convert_dtypes` to convert to `pd.ArrowDtype`

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#49997]
### Feature Type

- [x] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Currently `df.convert_dtypes()` will convert to nullable types (Int64, Boolean, etc), but it would be nice if there was an option to opt into the pyarrow-backed nullable types via `pd.ArrowDtype`

### Feature Description

Maybe either

* New keyword argument `nullable_type="pandas"|"pyarrow"`
* Refactor `io.nullable_backend` global setting to `mode.nullable_backend` and allow that global config to apply to `df.convert_dtypes`

### Alternative Solutions

For loop over the existing DataFrame object using `astype` and constructing `pd.ArrowDtype`?

**Comment by phofl** [comment]
I'd prefer the option solution I think, keeps us consistent with the I/O stuff

**Comment by seanjedi** [comment]
take

**Comment by mroeschke** [comment]
@seanjedi I would advise waiting until there are been a little more discussion regarding the direction of this issue.

**Comment by seanjedi** [comment]
@mroeschke Hmm alright, let me know when I should work on it. 
I am a bit new here, and this issue seems to be doable for my skill level, but if I am committing too much than I can handle, then feel free to let me know. 

Should I unassign myself?

**Comment by mroeschke** [comment]
Yeah additionally I was hoping to work on this myself in a few days after some discussion and consensus.

May I recommend some of these older issues with a lot of community interest? https://github.com/pandas-dev/pandas/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by seanjedi** [comment]
Alright, I will take a look then, thanks for the recommendation
