### ISSUE TITLE
DOC: Add tips on where to locate a test

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#50014]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests

### Documentation problem

NA

### Suggested fix for documentation

As a general tip, we should mention searching for the methods you want to add a test for using either grep or IDE search functionality. Also, I think it would be helpful to state that there is at times no clear location to put a test, take your best guess, and you may be requested by reviewers to move it.

**Comment by georgemunyoro** [comment]
take
