### ISSUE TITLE
BUG: Documentation display issue (maybe nbsphinx ?)

### ISSUE THREAD

**Issue by sahahn** [pandas-dev/pandas#50023]
### Pandas version checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
You can see on the current version of the live-documentation for pages that are converted from a notebook - e.g., https://pandas.pydata.org/docs/user_guide/style.html .
```

### Issue Description

It seems like the column spacing is messed up for displaying the table, so it just looks messed up, with text from columns overlapping. 

### Expected Behavior

Older versions of the documentation do not have this issue, e.g., compare:
https://pandas.pydata.org/pandas-docs/version/1.4/user_guide/style.html 
to current build: https://pandas.pydata.org/docs/user_guide/style.html

### Installed Versions

This is on live documentation for version 1.5.2

**Comment by phofl** [comment]
Hi, thanks for your report. This is fixed on the dev build

**Comment by sahahn** [comment]
Sorry for the duplicate!
