### ISSUE TITLE
API: Exception type for incorrect dtype keyword

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#50032]
In constructors and in `.astype`-like functions with a `dtype` keyword, if the passed dtype is invalid, sometimes we raise a TypeError and other times a ValueError.  e.g.

```
pd.Series(range(10), dtype="m8")  # <- ValueError
pd.Series(range(10), dtype="m8[h]")  # <- TypeError
```

We should try to be consistent about these.  cc @seberg would be nice to match numpy too.

**Comment by seberg** [comment]
Hmmm, I would lean towards both `ValueError` since both are about the value of the "unit" during conversion of the `dtype`.  I guess for some inputs (like an integer) a `TypeError` would be fine.

**Comment by jbrockmendel** [comment]
Non-unit examples would be cases where we support the style but don’t allow converting to it (eg datetime64ns to interval[timedelta64ns])

**Comment by jbrockmendel** [comment]
Closing as not actionable.
