### ISSUE TITLE
BUG: to_datetime with decimal number doesn't fail for %Y%m%d

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#50051]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
to_datetime(['19801212.0'], format='%Y%m%d', exact=True)
```

### Issue Description

This should fail, there's no interpretation of  `format` in which `19801212.0` matches `%Y%m%d`

### Expected Behavior

Probably something like
```
ValueError: unconverted data remains: .0
```
but certainly not that it passes without an error

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 732ad9f281bf6efffa12b8a872df98e18c11e3b7
python           : 3.8.15.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 2.0.0.dev0+838.g732ad9f281.dirty
numpy            : 1.23.5
pytz             : 2022.6
dateutil         : 2.8.2
setuptools       : 65.5.1
pip              : 22.3.1
Cython           : 0.29.32
pytest           : 7.2.0
hypothesis       : 6.59.0
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.9.1
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : 2.9.3
jinja2           : 3.0.3
IPython          : 8.7.0
pandas_datareader: 0.10.0
bs4              : 4.11.1
bottleneck       : 1.3.5
brotli           : 
fastparquet      : 2022.11.0
fsspec           : 2021.11.0
gcsfs            : 2021.11.0
matplotlib       : 3.6.2
numba            : 0.56.4
numexpr          : 2.8.3
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : 0.17.9
pyarrow          : 9.0.0
pyreadstat       : 1.2.0
pyxlsb           : 1.0.10
s3fs             : 2021.11.0
scipy            : 1.9.3
snappy           : 
sqlalchemy       : 1.4.44
tables           : 3.7.0
tabulate         : 0.9.0
xarray           : 2022.11.0
xlrd             : 2.0.1
zstandard        : 0.19.0
tzdata           : None
qtpy             : None
pyqt5            : None
None

</details>

**Comment by MarcoGorelli** [comment]
Pretty sure I disagree with this test:

https://github.com/pandas-dev/pandas/blob/2804681c45b5f748d0977e3998bbfc91d4653b10/pandas/tests/tools/test_to_datetime.py#L119-L135

These should raise, the inputs don't match the given format

I don't think the %Y%m%d special path serves any purpose, we should just remove it

**Comment by MarcoGorelli** [comment]
This doesn't look right:

https://github.com/pandas-dev/pandas/blob/073e48b7cfe85b7a1173a275296471b51276826d/pandas/tests/tools/test_to_datetime.py#L142-L148

If the input is invalid, errors='ignore' should return the input

**Comment by jorisvandenbossche** [comment]
Resolved by https://github.com/pandas-dev/pandas/pull/50242
