### ISSUE TITLE
BUG: Handling of NaN values in complex columns

### ISSUE THREAD

**Issue by fsoubelet** [pandas-dev/pandas#50069]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import numpy as np
import pandas as pd

s = pd.Series([np.nan, 2 + 3j], dtype=np.complex128)

print(s)
print(s.loc[0])
print(s.loc[0] - 1j)
```

### Issue Description

Hi,

I have run into an issue where operations that would give a `NaN` result would be messed up in the case where the column values are a complex `dtype`. The reproducible example linked shows this behavior. The output of this code snippet is:
```
0   N000a000N
1    2.0+3.0j
dtype: complex128
(nan+0j)
(nan-1j)
```

Several issues can be observed here:
1. The value at `s.loc[0]` is `nan +0j`, which is not the expected behavior. One would expect `nan` or `nan + nanj`.
2. The value, when displaying the entire Series (idem for a DataFrame) is displayed as `N000a000N`, which is very confusing at best.
3. The resulting complex number can be subtracted from, as seen in the last output line, giving `nan-1j` where one would still expect `nan` or `nan + nanj`.

It seems here that for a complex dtype entry that should be `nan`, only the real part is made `nan` and the display is messed up. Further down the line, calculations that would normally handle `nan`s will crash (or at least the ones I was running).

**Worth noting**: this is correctly treated as a simple `nan` when calling `s.dropna()`.

### Expected Behavior

The result from the provided code snippet should give `nan` or `nan + nanj`.
The display of the Series should not include any `N000a000N`.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 91111fd99898d9dcaa6bf6bedb662db4108da6e6
python           : 3.10.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.6.0
Version          : Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.5.1
numpy            : 1.23.4
pytz             : 2022.6
dateutil         : 2.8.2
setuptools       : 65.5.1
pip              : 22.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.6.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : 0.8.3
fsspec           : 2022.11.0
gcsfs            : None
matplotlib       : 3.6.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 10.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.3
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

This behavior has been reproduced on other systems.

</details>

**Comment by codestorm177** [comment]
take

**Comment by phofl** [comment]
The behavior is correct. This is how numpy works with complex dtypes, nan is a float, if you want to have the imaginary part as nan as well, then you have to use np.nan + np.nan*0j. 

The display of nan is off though.

**Comment by mroeschke** [comment]
This looks to have been fixed on main and IIRC we have tests for this case so closing
