### ISSUE TITLE
Add option for default_charset to sql.write_frame

### ISSUE THREAD

**Issue by aschilling** [pandas-dev/pandas#5008]
Hi everybody,

I worked today with a lot of unicode data and deeply missed the option to define a default_charset when writing a dataframe to a new sql table. I did not know that pandas uses "latin-1" as default and ran into various strange encoding problems such as "Data too long for column" when inserting my unicode data. The exception was raised despite the explicit definition of utf-8 in the connection object.

As a workaround I created the table myself and let pandas only append the DataFrame. However, it would be much better if pandas could create the tables itself.

Best regards

Andy

**Comment by kokes** [comment]
Hi, as this API has been replaced by [to_sql](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_sql.html), I have to ask if you can replicate this issue in this "new" API.

Thanks!

**Comment by mroeschke** [comment]
Not entirely clear on the feature request since it references an older API. Feel free to open a new issue as it pertains to `to_sql`.
