### ISSUE TITLE
ENH: Aligning values to the left in printing or writing to a file

### ISSUE THREAD

**Issue by dstone42** [pandas-dev/pandas#50095]
### Feature Type

- [X] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish I could print (console printing) or write a pandas data frame and have the values in each cell (not the column headers) aligned to the left.

### Feature Description

It is default aligning to the right, and you would just have to add an option for left aligning.

### Alternative Solutions

The Styler objects allow for this using CSS, but they aren't printable. If those could be printed or written to a file, that would also solve this issue.

**Comment by mwanink** [comment]
take

**Comment by mroeschke** [comment]
Thanks for the request, but it appears there hasn't been much traction for this request over the years so closing
