### ISSUE TITLE
DOC: styler docs don't render tables properly (chrome, safari)

### ISSUE THREAD

**Issue by alexlenail** [pandas-dev/pandas#50103]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/user_guide/style.html

### Documentation problem

<img width="701" alt="image" src="https://user-images.githubusercontent.com/2761597/206201236-a3b9c644-bc8a-4937-85e2-8a6a19f5c6fc.png">

### Suggested fix for documentation

probably some sort of width formatting

**Comment by attack68** [comment]
this has been fixed on main. maybe not backported

**Comment by attack68** [comment]
its has been backported actually. is fixed for 1.5.3

**Comment by alexlenail** [comment]
embarrassed to have blindly checked the checkbox. stable != main. Thanks
