### ISSUE TITLE
BUG: pd.to_csv() BUG

### ISSUE THREAD

**Issue by clemente0420** [pandas-dev/pandas#50101]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
print(pd_series)

StreamExecutor::run                                             6787.538
LazyGraphExecutor::SyncTensorsGraph                             6012.728
StepMarker_xla:0                                                5998.051
aten::_local_scalar_dense                                       3141.302
LazyGraphExecutor::SyncTensorsGraphInternal                     2061.676
LazyGraphExecutor::Compile                                      2015.125
```

BUT pd_series.to_csv(), get weire csv
```
,0
aten::_local_scalar_dense,3141.302
LazyGraphExecutor::SyncTensorsGraph,6012.728
```

ISSUE:
It seems to be truncated by "StepMarker_xla:"
```


### Issue Description

print(pd_series)
```
StreamExecutor::run                                             6787.538
LazyGraphExecutor::SyncTensorsGraph                             6012.728
StepMarker_xla:0                                                5998.051
aten::_local_scalar_dense                                       3141.302
LazyGraphExecutor::SyncTensorsGraphInternal                     2061.676
LazyGraphExecutor::Compile                                      2015.125
```

BUT pd_series.to_csv(), get weire csv
```
,0
aten::_local_scalar_dense,3141.302
LazyGraphExecutor::SyncTensorsGraph,6012.728
```

ISSUE:
It seems to be truncated by "StepMarker_xla:"


### Expected Behavior

CSV GET OUTPUT

```
StreamExecutor::run                                             6787.538
LazyGraphExecutor::SyncTensorsGraph                             6012.728
StepMarker_xla:0                                                5998.051
aten::_local_scalar_dense                                       3141.302
LazyGraphExecutor::SyncTensorsGraphInternal                     2061.676
LazyGraphExecutor::Compile                                      2015.125
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 8dab54d6573f7186ff0c3b6364d5e4dd635ff3e7
python           : 3.8.15.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.14.0_1-0-0-49
Version          : #1 SMP Tue Apr 12 17:13:25 CST 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.2
numpy            : 1.22.3
pytz             : 2022.6
dateutil         : 2.8.2
setuptools       : 65.6.3
pip              : 22.2.2
Cython           : None
pytest           : 7.2.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.6.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by MarcoGorelli** [comment]
Thanks for the report - could you make your example reproducible please?

**Comment by codestorm177** [comment]
take

**Comment by phofl** [comment]
Closing for now, please ping to reopen, when you can address questions
