### ISSUE TITLE
CI use ubuntu 22.04

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#50115]
xref https://github.com/pandas-dev/pandas/pull/50113#issuecomment-1341589258

Currently 20.04 is pinned to fix CI

**Comment by phofl** [comment]
I'd propose using 22.04, this has longer support than 22.10

**Comment by MarcoGorelli** [comment]
Sounds good

**Comment by MarcoGorelli** [comment]
closed in https://github.com/pandas-dev/pandas/pull/50117
