### ISSUE TITLE
CI: PY311 failures

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#50124]
Both on builds from `main` and `1.5.x`:

https://github.com/pandas-dev/pandas/actions/runs/3647663722/jobs/6160167738

```
2022-12-08T11:43:18.6188497Z FAILED pandas/tests/dtypes/test_missing.py::test_array_equivalent_series[abc] - AssertionError: Did not see expected warning of class 'FutureWarning'
2022-12-08T11:43:18.6189358Z FAILED pandas/tests/indexes/object/test_indexing.py::TestGetIndexerNonUnique::test_get_indexer_non_unique_np_nats[datetime640-datetime6410] - OverflowError: Integer overflow getting a common metadata divisor for NumPy datetime metadata [Y] and [ps].
2022-12-08T11:43:18.6190343Z FAILED pandas/tests/indexes/object/test_indexing.py::TestGetIndexerNonUnique::test_get_indexer_non_unique_np_nats[datetime640-datetime6411] - OverflowError: Integer overflow getting a common metadata divisor for NumPy datetime metadata [Y] and [fs].
2022-12-08T11:43:18.6191258Z FAILED pandas/tests/indexes/object/test_indexing.py::TestGetIndexerNonUnique::test_get_indexer_non_unique_np_nats[datetime640-datetime6412] - OverflowError: Integer overflow getting a common metadata divisor for NumPy datetime metadata [Y] and [as].
...
```

**Comment by MarcoGorelli** [comment]
Could be related to https://github.com/numpy/numpy/pull/22750 ?

**Comment by MarcoGorelli** [comment]
The test introduced in https://github.com/pandas-dev/pandas/pull/43870 is now failing

cc @jbrockmendel @alexhlim  (no blame)

I don't really understand why the deprecation warning was filtered out in that test - wasn't it warning us that this was going to fail?

```console
(.venv) (base) marcogorelli@DESKTOP-U8OKFP3:~/tmp$ cat t.py
import numpy as np

nat_1 = np.datetime64('NaT', 'Y')
nat_2 = np.datetime64('NaT', 'ps')
{nat_1}.add(nat_2)

(.venv) (base) marcogorelli@DESKTOP-U8OKFP3:~/tmp$ python t.py
t.py:5: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  {nat_1}.add(nat_2)
(.venv) (base) marcogorelli@DESKTOP-U8OKFP3:~/tmp$
```

**Comment by MarcoGorelli** [comment]
The following is also causing issues now:

https://github.com/pandas-dev/pandas/blob/0ca49fcf1e5d6a870f99624272a7e9332ea27593/pandas/core/arrays/masked.py#L722-L731

Test that hits this
```
pytest pandas/tests/frame/methods/test_compare.py::test_compare_ea_and_np_dtype
```

**Comment by jbrockmendel** [comment]
https://github.com/numpy/numpy/issues/13548 fixed a couple days ago probably related

**Comment by MarcoGorelli** [comment]
With numpy 1.23.5:
```python
In [1]: np.array([1, 3]) == np.array([4, pd.NA])
<ipython-input-1-b84677c04e2f>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  np.array([1, 3]) == np.array([4, pd.NA])
Out[1]: False
```

With the latest nightly:
```python
In [1]: np.array([1, 3]) == np.array([4, pd.NA])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 1
----> 1 np.array([1, 3]) == np.array([4, pd.NA])

File ~/pandas-dev/pandas/_libs/missing.pyx:413, in pandas._libs.missing.NAType.__bool__()
    411 
    412     def __bool__(self):
--> 413         raise TypeError("boolean value of NA is ambiguous")
    414 
    415     def __hash__(self):

TypeError: boolean value of NA is ambiguous
```

**Comment by seberg** [comment]
The change is that NumPy is now (not in the upcoming 1.24 release!) raising errors that occur during comparisons.
It is also returning arrays of all `False` or all `True` for DTypes that cannot be compared, like `np.array(["1"]) == 1`.

I would not love to undo that step, these deprecation/futurewarnings were a long pain-point.  The way specific cases are handled can definitely be tweaked of course!

**Comment by MarcoGorelli** [comment]
Thanks @seberg for stepping in!

Not really sure what to do here - @jbrockmendel @mroeschke thoughts on how to "save" `test_get_indexer_non_unique_np_nats`? Are we OK to skip it for the numpy nightly for now to get CI green again (as in https://github.com/pandas-dev/pandas/pull/50129)?

**Comment by MarcoGorelli** [comment]
Maybe it's OK to just let numpy error for this comparison? It only appears in a single test - and even then, [the original issue which motivated it](https://github.com/pandas-dev/pandas/issues/43869) had a comparison between `datetime64('NaT')` and `timedelta64('NaT')` (rather than between `datetime64('NaT' 'Y')` and `datetime64('NaT' 'ps')`)

**Comment by jbrockmendel** [comment]
im not firing on all cylinders today, will take a closer look in the AM

**Comment by mroeschke** [comment]
From a quick glance, I would think that a proper fix would involve `Index.get_indexer_non_unique` considering `np.datetime64('NaT')` with different units as still NA-like, so I would imagine the implementation needs to be adjusted (the set membership check is unfortunately no longer sufficient to check different `np.datetime64('NaT')`s with different units)

**Comment by MarcoGorelli** [comment]
What should
```python
Index([1, 2, np.datetime64('NaT', 'Y')]).get_indexer_non_unique(Index([np.datetime64('NaT', 'ps')], dtype=object))
```
return if `np.datetime64('NaT', 'Y')` and `np.datetime64('NaT', 'ps')` can't be compared?

I think we're doomed from the start trying to support this

**Comment by MarcoGorelli** [comment]
As the conversation's a bit scattered between here and the PR, I'll try to summarise

There's 3 issues:

1. `np.array([1, 3]) == 'abc'` no longer warns, and just returns `array([False, False])`
2. `np.array([1, 3]) == np.array([4, pd.NA])` now raises. I don't think there's much we can do about this, because `NA.__eq__(3)` returns `NA`, and then if `numpy` calls `bool` on the result, then we will reach the `TypeError` here:

    https://github.com/pandas-dev/pandas/blob/d6608313e211be0a44608252a3a31cf5220963f4/pandas/_libs/missing.pyx#L412-L413

3. `np.datetime64('NaT', 'Y')` and `np.datetime64('NaT', 'ps')` can no longer be compared - trying to do so with raise

What to do about this:

1. this fine, and non-controversial, so...all good 🥳 
2. `pd.NA` shoudn't really end up in a `numpy` array anyway, it's only meant to be used in pandas nullable types. So I think this is OK, it means https://github.com/pandas-dev/pandas/issues/48891 is now more urgent to be fixed
3. if these objects can't be compared, then there's no hope of distinguishing them in `get_indexer_non_unique` anyway, so I think it'd be fine to just let numpy raise

**Comment by MarcoGorelli** [comment]
@jorisvandenbossche @jreback sorry for the tags, just hoping to give this a bit more visibility

**Comment by jorisvandenbossche** [comment]
> 2\. `np.array([1, 3]) == np.array([4, pd.NA])` now raises. I don't think there's much we can do about this

Yes, numpy raising an error is the expected behaviour I would say (or at least a direct consequence of our choice to have comparisons with NA return NA, and to have the bool value of NA being ambiguous)

It's of course another case of object dtype arrays with NA not really being useful / working correctly (xref https://github.com/pandas-dev/pandas/issues/32931)

**Comment by jbrockmendel** [comment]
w/r/t different-unit `np.timedelta64("NaT")`s raising:

1) the `set` behavior should _not_ raise, but this will have to be fixed in numpy.
2) for `get_indexer` with object-dtype a similar problem shows up with non-nat timedelta64 objects when comparing against pd.Timedelta objects (i'll open an issue shortly-ish).  The upshot of this is that i think we'll end up having to handle some of this in the khash code
