### ISSUE TITLE
DOC: add docstring example to Index.get_indexer_non_unique.html

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#50132]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.get_indexer_non_unique.html

### Documentation problem

It's tricky to follow without an example

Check https://pandas.pydata.org/docs/development/contributing_docstring.html for the docstring guide

### Suggested fix for documentation

Let's add an example to the docstring

**Comment by natmokval** [comment]
take

**Comment by yuuun** [comment]
take
