### ISSUE TITLE
BUILD: No module named 'pandas._libs.interval' after building container from .devcontainer.json

### ISSUE THREAD

**Issue by Kerybas** [pandas-dev/pandas#50134]
I cloned the repo and used the `.devcontainer.json` with VS Code to build a dev docker, on my Linux laptop.    
It seemed to run well until I tried `import pandas` and got `ModuleNotFoundError: No module named 'pandas._libs.interval'`.  

I tried the commands recommended here: https://stackoverflow.com/a/68935982
It didnt work.  

The problem is easy to reproduce, because it also happens in Github Codespace, which, I suppose, also use  `.devcontainer.json`.

### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Linux-5.19.16-76051916-generic-x86_64-with-glibc2.31

### Installation Method

Built from source

### pandas Version

building from latest .devcontainer.json on main

### Python Version

3.10.8

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by Kerybas** [comment]
I cloned the repo and used the `.devcontainer.json` with VS Code to build a dev docker, on my Linux laptop.    
It seemed to run well until I tried `import pandas` and got `ModuleNotFoundError: No module named 'pandas._libs.interval'`.  

I tried the commands recommended here: https://stackoverflow.com/a/68935982
It didnt work.  

The problem is easy to reproduce, because it also appears in Github Codespace, which, I suppose, also use  `.devcontainer.json`.

**Comment by MarcoGorelli** [comment]
hey

you need to do
```
python setup.py build_ext -j 4
python -m pip install -e . --no-build-isolation --no-use-pep517
```
https://pandas.pydata.org/docs/dev/development/contributing_environment.html

**Comment by Kerybas** [comment]
Ha, thank you @MarcoGorelli !
Due to the structure of the instructions, I assumed that this part wasn't applicable to the Visual Studio Code paragraph.  
As a Docker newbie, there is something I don't understand: why are those commands not part of the build?  
Shouldn't they, if they are mandatory anyway?

**Comment by MarcoGorelli** [comment]
because you need to run them regularly when the C extensions change (which is quite often), they're not just a one-off process

I agree that it's not clear though. I'll try to rewrite this page, it's been on my mind for a while, there's too many irrelevant details and the overall process isn't clear enough
