### ISSUE TITLE
pyodbc.Error: ('07006', '[07006] [Microsoft][ODBC Driver 17 for SQL Server]Restricted data type attribute violation (0)

### ISSUE THREAD

**Issue by Edimo05** [pandas-dev/pandas#50189]
Hi there, I am trying to upload data from a csv file to sql using pandas.
this is part of the code:
df.to_sql("data_transactions_3", engine, index= False, if_exists= "append", schema= "dbo")
after run that code, the error in the title comes up:
pyodbc.Error: ('07006', '[07006] [Microsoft][ODBC Driver 17 for SQL Server]Restricted data type attribute violation (0) (SQLBindParameter)')

**Comment by phofl** [comment]
Hi, thanks for your report. Please always include reproducible examples, see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

This looks like an Alchemy/Database error on your side. Please ping to reopen, when you can provide an example that shows that the error is in pandas.
