### ISSUE TITLE
TYP: Make better type hints for using register_dataframe_accessor

### ISSUE THREAD

**Issue by alixtc** [pandas-dev/pandas#50206]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/74759969/how-to-have-documentation-and-type-hints-in-vs-code-from-methods-created-with-pa

### Question about pandas

I ran into some issues while trying to extend pandas dataframe API using the register_dataframe_accessor decorator. While I was able to create the class as indicated in the [documentation](https://pandas.pydata.org/docs/development/extending.html), and use properties and methods, I noticed that in VS Code, the doctrings and type hints were note available.

In contrast, while working inside the classic jupyter display, both docstrings and type hints were available.

I did the same test with type-hints in a dummy method, and again it worked in Jupyter but not in VS Code Jupyter.

Is it possible to make documentation and type hints available in VS Code for additional dataframe accessor ?

```
@pd.api.extensions.register_dataframe_accessor("geo")
class GeoAccessor:
    def __init__(self, pandas_obj):
        self._validate(pandas_obj)
        self._obj = pandas_obj

    @staticmethod
    def _validate(obj):
        # verify there is a column latitude and a column longitude
        if "latitude" not in obj.columns or "longitude" not in obj.columns:
            raise AttributeError("Must have 'latitude' and 'longitude'.")

    @property
    def center(self):
        # return the geographic center point of this DataFrame
        lat = self._obj.latitude
        lon = self._obj.longitude
        return (float(lon.mean()), float(lat.mean()))

    def plot(self, dataframe: pd.DataFrame) -> pd.DataFrame:
        """With docstring
        plot this array's data on a map, e.g., using Cartopy
        """
        return dataframe

ds = pd.DataFrame(
    {"longitude": np.linspace(0, 10), "latitude": np.linspace(0, 20)}
)
ds.geo.plot()
```

In particular I am wondering if that issue is related to pandas behavior or if it depends entirely on VS code. Here is the view of the documentation:
<img width="910" alt="Capture d’écran 2022-12-11 à 10 10 33" src="https://user-images.githubusercontent.com/56310501/207101705-6cbca9ce-5a98-4b3d-82fa-80b8a1b4ad5e.png">
<img width="663" alt="Capture d’écran 2022-12-11 à 10 14 14" src="https://user-images.githubusercontent.com/56310501/207101825-e32bf162-3735-48ac-960f-68e683d50e08.png">

Thanks in advance

**Comment by topper-123** [comment]
Good question.

On the Pandas side, maybe the ´register_*_accessor´ functions could be better typed. Investigations welcome (the functions are located in `pandas/core/accessor.py`).

**Comment by mroeschke** [comment]
Since it doesn't sound like there's much pandas can do in this case, closing
