### ISSUE TITLE
DOC: Supported Float dypes not documented

### ISSUE THREAD

**Issue by mcp292** [pandas-dev/pandas#50216]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/user_guide/basics.html#dtypes

### Documentation problem

In the [dtypes section](https://pandas.pydata.org/docs/user_guide/basics.html#dtypes) a list of integer types are given, but not floating point types. According to [`pandas.to_numeric()`](https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html#pandas.to_numeric) under the `downcast` argument, it appears `float32` is the smallest floating point type, which implies `float16` is not documented.

In addition, the integer types are listed with capitalization, but it appears that capitalization does not matter, which is not documented.

### Suggested fix for documentation

1. List supported floating point types. 
2. Mention `float16` not supported. (Could be implicitly solved by point 1.)
3. Mention entries are not case-sensitive.
4. Link to [NumPy types](https://numpy.org/doc/stable/reference/arrays.scalars.html#sized-aliases).

---

Resulting from https://github.com/pandas-dev/pandas/issues/50213.

**Comment by mcp292** [comment]
Thank you for clarifying. Can you please link to documentation?

**Comment by phofl** [comment]
The table listing all int dtypes in your link already has a link to nullable integer. One of the first sentences there clarifies the capital I at the beginning

**Comment by MarcoGorelli** [comment]
Do we just need to add a row with `FloatArray` then? I think this'd be fine - do you want to open a pull request? Here's the contributing guide https://pandas.pydata.org/docs/dev/development/contributing.html

**Comment by mcp292** [comment]
> The table listing all int dtypes in your link already has a link to nullable integer. One of the first sentences there clarifies the capital I at the beginning

I'm still not seeing the sentence you refer to. Can you please quote it?

**Comment by mcp292** [comment]
> Do we just need to add a row with `FloatArray` then? I think this'd be fine - do you want to open a pull request? Here's the contributing guide https://pandas.pydata.org/docs/dev/development/contributing.html

Sure! It'll be a few days before I can make time for this. Thank you for the link.

**Comment by MarcoGorelli** [comment]
> 

It's probably [this one](https://pandas.pydata.org/docs/user_guide/integer_na.html#construction)

> Or the string alias "Int64" (note the capital "I", to differentiate from NumPy’s 'int64' dtype:

(btw, looks like there's a missing closed bracket)

**Comment by mcp292** [comment]
Thank you! Would it be acceptable to add the closing parenthesis in the same PR?

**Comment by MarcoGorelli** [comment]
yup 😄

**Comment by mcp292** [comment]
Looks like [there's no entry](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.array.html) for `FloatingArray`.

I'm trying to track down a list of the available `FloatingArray` types. I'm looking first to track down the `IntegerArray` types listed on the [dtypes page](https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes), so that I may find the same for `FloatingArray`.

Do you know where I can find this documentation?

**Comment by mcp292** [comment]
I noticed that `UInt8` warns against information loss due to conversion to a shorter type, but `uint8` does not:
```py
import pandas as pd


data = [255, 256, 257, 258, 259]
df = pd.DataFrame(data)

df.astype("uint8")
df.astype("UInt8")
```

This advantage is not documented on the [nullable integer page](https://pandas.pydata.org/docs/user_guide/integer_na.html#integer-na). The only advantage listed there is the preservation of integer type in the presence of `NaN`s.

Is this worth a separate issue/PR?

**Comment by natmokval** [comment]
take

**Comment by mcp292** [comment]
> take

Thank you, I've been too busy to address this.

**Comment by vijaybirju** [comment]
Is this issue fixed?

**Comment by MarcoGorelli** [comment]
hey - there's already a PR open, could you find another issue to work on please?

**Comment by vijaybirju** [comment]
Ok thanks so in one issue only one person can do pull requests  at a single time
