### ISSUE TITLE
DOC: Incorrect link in StringArray and ArrowStringArray docs

### ISSUE THREAD

**Issue by ivirshup** [pandas-dev/pandas#50230]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.arrays.StringArray.html

https://pandas.pydata.org/docs/dev/reference/api/pandas.arrays.ArrowStringArray.html

### Documentation problem

<img width="620" alt="image" src="https://user-images.githubusercontent.com/8238804/207315110-d02ed7a6-1df4-42bd-bc5d-16e426fda40a.png">

This says it links to the `pandas.array` function, when it actually links to the [python array module](https://docs.python.org/3/library/array.html#module-array)

<img width="491" alt="image" src="https://user-images.githubusercontent.com/8238804/207315466-6556a74a-a5e8-497e-be47-3c608905febe.png">

<img width="882" alt="image" src="https://user-images.githubusercontent.com/8238804/207315799-185519ea-1ab3-4658-98d5-80fffebc88e2.png">

### Suggested fix for documentation

It should link to `pandas.array`, but I'm not completley sure what sphinx wants here. Maybe using a fully qualified identifier?

**Comment by MarcoGorelli** [comment]
thanks for the report

here's the code

https://github.com/pandas-dev/pandas/blob/f0d4694bf80fa9499880db34d5d3a13a8d073122/pandas/core/arrays/string_arrow.py#L86-L92

if anyone wants to have a go at fixing the link

**Comment by ramvikrams** [comment]
` [array](https://pandas.pydata.org/docs/dev/reference/api/pandas.arrays.ArrowStringArray.html) ` do we have to change it like this
