### ISSUE TITLE
BUG: out-of-bounds pydatetime with errors='coerce' and non-ISO format coerces all elements to NaT

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#50255]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
# non-ISO
In [1]: to_datetime(['2020-01-01', dt.datetime(9999, 1, 1)], format='%Y-%d-%m', errors='coerce')
Out[1]: DatetimeIndex(['NaT', 'NaT'], dtype='datetime64[ns]', freq=None)

# ISO
In [2]: to_datetime(['2020-01-01', dt.datetime(9999, 1, 1)], format='%Y-%m-%d', errors='coerce')
Out[2]: DatetimeIndex(['2020-01-01', 'NaT'], dtype='datetime64[ns]', freq=None)
```

### Issue Description

it shouldn't coerce all elements

### Expected Behavior

```
Out[2]: DatetimeIndex(['2020-01-01', 'NaT'], dtype='datetime64[ns]', freq=None)
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 113bdb37694e2849a15c390fddd8f28986bf1863
python           : 3.8.15.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 2.0.0.dev0+918.g113bdb3769
numpy            : 1.23.5
pytz             : 2022.6
dateutil         : 2.8.2
setuptools       : 65.5.1
pip              : 22.3.1
Cython           : 0.29.32
pytest           : 7.2.0
hypothesis       : 6.61.0
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.9.1
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : 2.9.3
jinja2           : 3.1.2
IPython          : 8.7.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.5
brotli           : 
fastparquet      : 2022.12.0
fsspec           : 2021.11.0
gcsfs            : 2021.11.0
matplotlib       : 3.6.2
numba            : 0.56.4
numexpr          : 2.8.3
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : 9.0.0
pyreadstat       : 1.2.0
pyxlsb           : 1.0.10
s3fs             : 2021.11.0
scipy            : 1.9.3
snappy           : 
sqlalchemy       : 1.4.45
tables           : 3.7.0
tabulate         : 0.9.0
xarray           : 2022.12.0
xlrd             : 2.0.1
zstandard        : 0.19.0
tzdata           : None
qtpy             : None
pyqt5            : None
None

</details>

**Comment by ShisuiUzumaki** [comment]
@MarcoGorelli Is this a bug?

**Comment by MarcoGorelli** [comment]
Gonna be completely honest - based on #50225, I'd suggest you become a bit more familiar with git / github first. I'd suggest the first 3 chapters of https://git-scm.com/book/en/v2

**Comment by ShisuiUzumaki** [comment]
> Gonna be completely honest - based on #50225, I'd suggest you become a bit more familiar with git / github first. I'd suggest the first 3 chapters of https://git-scm.com/book/en/v2

Ok! Actually, I made a little mistake and that was I used git rebase main, not sure what i was thinking. The thing is most of these issues originated from that. Anyway, I will get work on my git skills
