### ISSUE TITLE
ENH/DOC: stability guide

### ISSUE THREAD

**Issue by dengemann** [pandas-dev/pandas#5027]
I've had recently made the experience of implementing and maintaining different down-stream applications supporting or building upon pandas. One thing I've learned is that it's quite painful to write code that e.g. runs for pandas 0.7.3 up to current master. Although 0.7.3 seems rather old given the rapid dev-cycle and the vibrant community, one may not forget that 0.7.3 is not older than 1.5 - 2 years and hence still counts as stable version in quite a few distros (while user-studies show that many people, let alone institutions, are often years behind recent versions ...).
Which guidelines to follow to make life easier when supporting such use cases does not seem too well documented. What would people think about adding such a -- maybe growing -- collection of hints + tips to the docs?

**Comment by mroeschke** [comment]
I think this is relatively handled by the new policies doc.

https://github.com/pandas-dev/pandas/blob/master/doc/source/development/policies.rst

If there is anything not sufficiently described in that document, a new issue can be open clarifying points.
