### ISSUE TITLE
WARN fixup warning in pandas/tests/apply/test_frame_apply.py

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#50292]
We're not (yet) running all tests with `-W error`, so some warnings slip through to CI. On the way towards that, let's fixup this file.

Task here is:
1. make sure you've got your environment set up, see the [contributing guide](https://pandas.pydata.org/docs/dev/development/contributing.html)
2. make sure you can run this test: `pytest pandas/tests/apply/test_frame_apply.py`
3. fixup the warning (you just need to add `dayfirst=True` to the `to_datetime` call)
4. check that `pytest pandas/tests/apply/test_frame_apply.py` doesn't throw a warning
5. stage, commit, push, open pull request, celebrate 🎉 

Feel free to tag me for review

**Comment by tpackard1** [comment]
take
