### ISSUE TITLE
DEV add back boto3 and botocore to requirements-dev.txt

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#50300]
xref https://github.com/pandas-dev/pandas/pull/50295#issuecomment-1355335637

These packages are already brought in by `s3fs` and `moto`. By not listing them explicitly, the time it takes to `pip install -r requirements-dev.txt` goes from >54 minutes to <3 minutes.

It would be good, however, to list everything that's explicitly used - is there way to put them back without impacting pip install time?

**Comment by WillAyd** [comment]
I ran into a similar issue working on #50046 I think botocore has a ton of releases on pypi (almost nightly) and that takes a lot of package downloads for pip to resolve.

pip has some strategies for this, the easiest which may be to set a higher version floor for these libraries

https://pip.pypa.io/en/latest/topics/dependency-resolution/#possible-ways-to-reduce-backtracking

`--use-deprecated=legacy-resolver` also helps as a quick "fix"

**Comment by MarcoGorelli** [comment]
addressed by #50295
