### ISSUE TITLE
CLEAN dubious docstring

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#50344]
This looks odd - the docstring is broken in two, and there's an assignment in the middle?

https://github.com/pandas-dev/pandas/blob/22491dc041315d40e525b722a92202f656639957/pandas/_libs/tslibs/offsets.pyx#L369-L389

It looks like something might not have gone quite right during a merge conflict, and was kept in?

If anyone felt like having a look at `git blame` / `git log` to figure this out, that'd be helpful

No need to comment "can I work on this?" - if you know your way around `git` and figure this out, then go ahead and work on it - thanks 🙏

**Comment by keenborder786** [comment]
take

**Comment by MarcoGorelli** [comment]
thanks @asishm 

`self.normalize = normalize` should've come after the docstring, and that `Return boolean whether the frequency can align with midnight.` should've gone inside the `Parameters` section of the docstring

Do you want to submit a PR to fix it up?

**Comment by asishm** [comment]
The initial docstring also won't show up - it's already present after a code-block https://github.com/pandas-dev/pandas/blob/22491dc041315d40e525b722a92202f656639957/pandas/_libs/tslibs/offsets.pyx#L369-L375

n, normalize are not properties (so there can't be any docstrings) - they're plain attributes (unless i'm reading it wrong).

They are also documented here - https://github.com/pandas-dev/pandas/blob/22491dc041315d40e525b722a92202f656639957/pandas/_libs/tslibs/offsets.pyx#L1314 which shows up at https://pandas.pydata.org/docs/reference/offset_frequency.html

**Comment by MarcoGorelli** [comment]
> The initial docstring also won't show up - it's already present after a code-block 

yeah what I mean is to move the docstring to be directly under `__init__`

**Comment by luke396** [comment]
take
