### ISSUE TITLE
TST some tests in pandas/tests/io/json/test_readlines.py aren't being tested

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#50378]
We can see from the coverage report that they're not being run:

https://app.codecov.io/gh/pandas-dev/pandas/blob/main/pandas/tests/io/json/test_readlines.py

This is because their name doesn't start with `test_`

So, task here is:
- rename the tests so they start with `test_`
- run them, check if they pass
- stage, commit, push, pull request

**Comment by MarcoGorelli** [comment]
cc @SFuller4 just FYI

looks like the last two don't actually pass

**Comment by MarcoGorelli** [comment]
we probably need a pre-commit check for this: if a function is in pandas/tests, and if it contains `assert`, and if its name doesn't start with `test_`, then we should probably raise

**Comment by phershbe** [comment]
@MarcoGorelli I can do this if you'd like. I haven't worked as a programmer yet and am relatively new to open source, but this is easy enough, it's the last four tests I guess.

**Comment by MarcoGorelli** [comment]
that's right

**Comment by MarcoGorelli** [comment]
same this one

https://github.com/pandas-dev/pandas/blob/3b60759002fdc13edbbb1eab6c4bc5ec14d027ef/pandas/tests/series/methods/test_explode.py#L76-L81

**Comment by phershbe** [comment]
@MarcoGorelli Okay, great, thank you. I'm working on it and having trouble running the tests. This is a really important project that moves really fast so I didn't self-assign it with `take` because if anybody else jumps in and does it that's fine, I'm working on it though.

**Comment by MarcoGorelli** [comment]
no hurry 😄 

>  I'm working on it and having trouble running the tests

what trouble are you having? feel free to ask, either here or on the slack (see the readme for the link)

**Comment by labibdotc** [comment]
take

**Comment by phershbe** [comment]
@MarcoGorelli Awesome, thank you for mentioning the slack, I forgot about that. I'm starting now, I'll ask in a short time here if I'm still stuck.

**Comment by phershbe** [comment]
@MarcoGorelli The issue got taken, I'm still working on it for learning purposes and can submit it if the other person doesn't get it done. I'm looking at some other issues that you've opened too. Thank you.

**Comment by MarcoGorelli** [comment]
> 

Feel free to submit - @labibdotc please don't comment "take" when someone else has clearly expressed interest in working on an issue

**Comment by labibdotc** [comment]
I commented a take with the assumption no one has it assigned from the header. Will go over comments next time. @phershbe sorry for the hassle, take it now.

**Comment by phershbe** [comment]
take

**Comment by phershbe** [comment]
@labibdotc No problem. I also should have taken after expressing interest in order to avoid something like this.

**Comment by MarcoGorelli** [comment]
no worries, thanks both!

**Comment by MarcoGorelli** [comment]
Please make sure to remove this line

https://github.com/pandas-dev/pandas/blob/1b653b1c23f7a5f9fbaede993cf9370dba79b1fc/.pre-commit-config.yaml#L345

when you open your pull request

@labibdotc if you're interested, https://github.com/pandas-dev/pandas/issues/50380 is similar (though slightly harder)

**Comment by phershbe** [comment]
@MarcoGorelli Working on it now, have to get the two tests to pass like you mentioned before, if I get stuck I'll ask in a short time here.

**Comment by phershbe** [comment]
@MarcoGorelli Okay, I was working on it and got it mostly figured out. The `True` and `False` on line 388 and again on line 417 (https://github.com/pandas-dev/pandas/blob/main/pandas/tests/io/json/test_readlines.py) are getting turned into `1.0` and `0.0` when they go through `ensure_clean` and `to_json` and `read_json`. The tests pass by changing the booleans to numbers, but it seems like there should be a cleaner solution. Of course it could be done by making them the numbers and then commenting the code.

I'm learning a lot. I have some holiday stuff to do now and tomorrow so I may not be able to get it done until Monday morning.

**Comment by phershbe** [comment]
@MarcoGorelli Okay, it's because JSON turns booleans into 1s and 0s, probably that's pretty common knowledge but I don't have much experience so it took me a while. The best idea I've found so far is to put `int` in front of the booleans (`int(True)` and `int(False)`) in both cases where we define the `expected` variable so that `assert_frame_equal` can compare the two sets of data equally. I'm going to submit the pull request like that and then feel free to change it if you know of a better way.
