### ISSUE TITLE
CLN remove _assert_not_frame_equal_both?

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#50393]
Doesn't look like this is used anywhere

https://github.com/pandas-dev/pandas/blob/07b363ea8eee184df30b54bfae9acd04511e1cda/pandas/tests/util/test_assert_frame_equal.py#L55-L71

**Comment by MarcoGorelli** [comment]
Same with

https://github.com/pandas-dev/pandas/blob/50f19b6ed5f335d2396825ad5ec055f2607a39fa/pandas/tests/io/formats/test_format.py#L109-L111

**Comment by MarcoGorelli** [comment]
this one too

https://github.com/pandas-dev/pandas/blob/128832f85119428402bd0b0916abffb33e3ae29c/pandas/tests/frame/methods/test_dtypes.py#L18-L22

**Comment by ShashwatAgrawal20** [comment]
take

**Comment by ShashwatAgrawal20** [comment]
take

**Comment by ShashwatAgrawal20** [comment]
Hey @MarcoGorelli should these functions be directly removed ?

**Comment by MarcoGorelli** [comment]
yup
