### ISSUE TITLE
ENH: Use explicit arguments in DataFrameGroupBy.describe

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#50406]
Currently DataFrameGroupBy.describe uses `**kwargs` instead of explicit arguments. These eventually get passed to `DataFrame.describe`. We should use explicit arguments, those from `DataFrame.describe`, instead.

**Comment by dullibri** [comment]
take

**Comment by asadullahnaeem** [comment]
@dullibri if we are not working on this I would like to take it.

**Comment by dullibri** [comment]
Here you go!

**Comment by asadullahnaeem** [comment]
@rhshadrach I will be working on this issue so could you guide me through the process.

**Comment by dullibri** [comment]
I think I was actually pretty close. However, the signature would not change always showing kwargs.

**Comment by telferm57** [comment]
@dullibri could you 'take', so issue  shows as assigned ?

**Comment by dullibri** [comment]
@telferm57 read the message above pls.

**Comment by asadullahnaeem** [comment]
take

**Comment by asadullahnaeem** [comment]
@rhshadrach Could you please review the pull request?
