### ISSUE TITLE
BUG: inconsistent handling of exact=False case in to_datetime parsing

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#50412]
From https://github.com/pandas-dev/pandas/issues/50411#issuecomment-1363972775

The documentation of `to_datetime` says:

> exact : bool, default True
>      Control how `format` is used:
>
>    - If :const:`True`, require an exact `format` match.
>    - If :const:`False`, allow the `format` to match anywhere in the target string.

Based on that, I would expect we don't use anything else in the string that doesn't match the format. But it seems this currently depends on the exact format being used:

```
>>> pd.to_datetime(["19/may/11 01:00:00"], format="%d/%b/%y", exact=False)
DatetimeIndex(['2011-05-19'], dtype='datetime64[ns]', freq=None)

>>> pd.to_datetime(["2011-05-19 01:00:00"], format="%Y-%m-%d", exact=False)
DatetimeIndex(['2011-05-19 01:00:00'], dtype='datetime64[ns]', freq=None)
```

(happens both on current main and on 1.5)

**Comment by jorisvandenbossche** [comment]
On main, with %Y%m%d special case, the remainder is not taken into account:

```
>>> pd.to_datetime(["20110519 01:00:00"], format="%Y%m%d", exact=False)
DatetimeIndex(['2011-05-19'], dtype='datetime64[ns]', freq=None)
```

but with the changes of https://github.com/pandas-dev/pandas/pull/50242, it now actually also does (I suppose because the code path for this specific format was changed, cc @MarcoGorelli)

Another consequence of that the ISO? formats don't actually ignore the remainder of the string, is that it also raises if it is unparseable:

```
>>> pd.to_datetime(["2011-05-19 AAA"], format="%Y-%m-%d", exact=False)
...
ValueError: time data "2011-05-19 AAA" at position 0 doesn't match format "%Y-%m-%d"
```

So maybe it is just that the `exact=False` feature doesn't work / isn't implemented for ISO like formats?

**Comment by MarcoGorelli** [comment]
nice catch, thanks! this is indeed a bug:
```python
In [21]: pd.to_datetime(["2011-05-19 05:00:00"], format="%Y-%d-%m", exact=False)
Out[21]: DatetimeIndex(['2011-01-05'], dtype='datetime64[ns]', freq=None)

In [22]: pd.to_datetime(["2011-05-19 05:00:00"], format="%Y-%m-%d", exact=False)
Out[22]: DatetimeIndex(['2011-05-19 05:00:00'], dtype='datetime64[ns]', freq=None)
```

this needs fixing in the ISO path
