### ISSUE TITLE
Duplicate --- Suggestion

### ISSUE THREAD

**Issue by djjeremiahj** [pandas-dev/pandas#50446]
Add functinality to reference "False" item.

example:
bool_series = df.duplicated(keep='first', **reference=yes**)

1. Dog
2. Cat
3. Dog

output
1. False,NaN
2. False,NaN
3. True, 1

This would allow you to flag the "is duplicated items" (True), skip processing, but then at a later time, reference the output of the False items.

I need to keep the data integrity, but stop duplicate processing if it's a duplicate.

**Comment by MarcoGorelli** [comment]
Hi @djjeremiahj 

It's not clear what you're asking - could you open a new issue and fill in the template please?
