### ISSUE TITLE
ENH: Add decimal parameter to to_excel

### ISSUE THREAD

**Issue by serge2016** [pandas-dev/pandas#50457]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Hello! It would be great to have a chance to setup the `decimal` separator for `to_excel` function. Could you add this, please? It might be similar to https://github.com/pandas-dev/pandas/pull/44317

### Feature Description

It is needed to setup the decimal separator when generating XLSX files so that it should not be necessary to fix this when opening Excel

### Alternative Solutions

For now I have to convert floats to strings and replace '.' to ',' ...

**Comment by attack68** [comment]
Doesnt the decimal and thousands separator for an excel file change and depend on the region settings of the computer? At least in my experience the same file with the same floats displays differently on two computers with different region settings.
in which case this cannot be controlled from pandas unless you explicitly write strings and not floats which also doesnt sound like a good idea?

**Comment by phofl** [comment]
I think @attack68 is correct, closing for now. Please ping to reopen if you have other suggestions
