### ISSUE TITLE
BUG: DataFrameGroupBy.value_counts fails with a TimeGrouper

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#50486]
```
df = pd.DataFrame(
    {
        "Timestamp": [
            1565083561,
            1565083561 + 86400,
            1565083561 + 86500,
            1565083561 + 86400 * 2,
            1565083561 + 86400 * 3,
            1565083561 + 86500 * 3,
            1565083561 + 86400 * 4,
        ],
        "Food": ["apple", "apple", "banana", "banana", "orange", "orange", "pear"],
    }
).drop([3])

df["Datetime"] = to_datetime(df["Timestamp"].apply(lambda t: str(t)), unit="s")
gb = df.groupby(pd.Grouper(freq="1D", key="Datetime"))
print(gb.value_counts())
```

raises `ValueError: operands could not be broadcast together with shapes (5,) (6,) (5,)`

**Comment by AfolabiOlaoluwa** [comment]
I don't know what your environment looks like, but this is what I did to investigate the problem.

> It appears you are passing in an object for value_counts(). You Can't pass in an object on value_counts()

```
df["Datetime"] = pd.to_datetime(df["Timestamp"].apply(lambda t: str(t)), unit="s")
# note that I had to pass in the pd constructor to "to_datetime"
# print(df["Datetime"]) # Note that printing this returned properly 

gb = df.groupby(pd.Grouper(freq="1D", key="Datetime"))
# Note that the response was <pandas.core.groupby.generic.DataFrameGroupBy object at 0x3e58080>
# print(df.groupby(pd.Grouper(freq="1D", key="Datetime")))
```

If you look at the code below, it returns a TimeGrouper Class
```
print(pd.Grouper(freq="1D", key="Datetime")) 
>>> TimeGrouper(key='Datetime', freq=<Day>, axis=0, sort=True, closed='left', label='left', how='mean', convention='e', origin='start_day')
```

If you use a dot notation on the response, you can group by any item from the response. e.g. `pd.Grouper(freq="1D", key="Datetime").key`, which picks the value for the "key" which is "Datetime". 

I you call `.value_counts()` on that, you will have an output. See the code below and the output:

```
veee = df.groupby(pd.Grouper(freq="1D", key="Datetime").key)
print(veee)
print(veee.value_counts())
```

Your output will be:
```
Datetime             Timestamp   Food  
2019-08-06 09:26:01  1565083561  apple     1
2019-08-07 09:26:01  1565169961  apple     1
2019-08-07 09:27:41  1565170061  banana    1
2019-08-09 09:26:01  1565342761  orange    1
2019-08-09 09:31:01  1565343061  orange    1
2019-08-10 09:26:01  1565429161  pear      1
dtype: int64
```

**Comment by AfolabiOlaoluwa** [comment]
Also, note that if you leave your code untouched, you can `.count()` and `.size()`.

**Comment by rhshadrach** [comment]
Thanks @AfolabiOlaoluwa - however the code in the top comment (without any modification) should not raise an error.

**Comment by AfolabiOlaoluwa** [comment]
I totally agree it shouldn't fail!

It looks like we need to we need to `import` the `TimeGrouper` class and call `super()` function on it whether it is present or not to access its components. 

If we look at ["__new__"](https://github.com/pandas-dev/pandas/blob/fa613b3268f7b6ed6ec2d833f4e96ffe2e8659f1/pandas/core/groupby/grouper.py#L246:L251) function under grouper.py, even if `freq` is absent in the Grouper class, it works fine and your solutions work fine `freq`.
