### ISSUE TITLE
DOC: IO tools OpenDocument spreadsheets har wrong information on missing implementation for writing ODF-files

### ISSUE THREAD

**Issue by frodeseverin** [pandas-dev/pandas#50487]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

[IO tools OpenDocument spreadsheets](https://pandas.pydata.org/docs/user_guide/io.html#opendocument-spreadsheets)
Version 1.5.2 (stable)

### Documentation problem

The good news of support in pandas for writing OpenDocument spreadsheets has not propagated from the 'dev' branch of the documentation to applicable documentation versions, i.e from 1.1.0 onwards.

There is a dependency on the odfpy package, as mentioned here:
[https://stackoverflow.com/questions/58915626/write-dataframe-into-ods-format](https://stackoverflow.com/a/63221606)

I checked the functionality with pandas version 1.5.2 after manually installing odfpy, and it works like a snap.

The documentation for version 1.5.2 states:

> ! Note
> Currently pandas only supports reading OpenDocument spreadsheets. Writing is not implemented.

The documentation for dev states:

> ! New in version 1.1.0.
> Similarly, the to_excel() method can write OpenDocument spreadsheets
> 
> ```
> # Writes DataFrame to a .ods file
> df.to_excel("path_to_file.ods", engine="odf")
> ```

There is no mention of the dependency on odfpy.

### Suggested fix for documentation

! New in version 1.1.0.
Similarly, the to_excel() method can write OpenDocument spreadsheets

```
# Writes DataFrame to a .ods file
df.to_excel("path_to_file.ods", engine="odf")
```

This functionality depends on the odfpy package, which needs to be installed manyally with e.g. pip for the time being.

**Comment by phofl** [comment]
Hi, thanks for your report. This is fixed on the current version of our docs (dev).

**Comment by luke396** [comment]
take
