### ISSUE TITLE
EXPM: re-evaluate experimental

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#5049]
leave as experimental or change docs
- [ ] eval/query
- [ ] CustomBusinessDay
- [x] msgpack #27084 (deprecating)
- [ ] BigQuery
- [x] Panel4D -> deprecated
- [x] PanelND -> deprecated
- [ ] SQL changes
- [ ] r*flex methods
- [ ] get_options_data (#5602)
- [ ] DataFrame.style

**Comment by jorisvandenbossche** [comment]
> SQL changes

I don't think those changes are mentioned anywhere as experimental.

Regarding the first four (gbq, msgpack, eval/query, CustomBusinessDay), are there reasons to still keep them as experimental? (all more than three years old I think)

**Comment by mroeschke** [comment]
I think everything in the above issue has either been deprecated/removed or no longer experimental. Closing
