### ISSUE TITLE
BUG: the kind parameter of pandas.Series.resample contradicts the closed parameter

### ISSUE THREAD

**Issue by jiahe224** [pandas-dev/pandas#50522]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
df1 = pd.DataFrame({'mark':['A']*6,'date':['2021-02-01','2021-03-31','2021-04-01','2021-06-01','2021-09-30','2021-12-30'], 'prop':list(np.arange(0.1,0.7,0.1))})
df1['date'] = pd.to_datetime(df1['date'])

tmp = df1.copy()
tmp = tmp.set_index(['date'])
```

### Issue Description

The following results are not as expected.
```
tmp['prop'].resample('Q',closed='left',kind='period').first()
```

### Expected Behavior

The result of the above statement execution should be the same as the following statement.
```
tmp['prop'].resample('Q',closed='left').first().to_period()
```
### Installed Versions

<details>

commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.8.12.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Simplified)_China.936

pandas           : 1.5.3
numpy            : 1.23.3
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 63.4.1
pip              : 22.2.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.8.0
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.5
brotli           : 
fastparquet      : None
fsspec           : 2022.3.0
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : 2.8.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 4.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.1
snappy           : None
sqlalchemy       : 1.4.36
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by mroeschke** [comment]
The kind keyword in resample was deprecated in pandas 2.x and will be removed in 3.0 so I don't think there is any action here so closing
