### ISSUE TITLE
API add `date_format` to read_csv

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#50528]
From https://github.com/pandas-dev/pandas/issues/2586

Currently, once can to
```python
read_csv(path, parse_dates=True, date_parser=lambda x: to_datetime(x, format=fmt)
```
and the suggestion is to add a `date_format` argument such that you could do
```python
read_csv(path, parse_dates=True, date_format=fmt)
```
and have it do the same thing

**Comment by luke396** [comment]
take

**Comment by MarcoGorelli** [comment]
wait, this needs discussion

**Comment by luke396** [comment]
There is something wrong, when
```python
data = """a,b
27.03.2003 14:55:00.000,1
03.08.2003 15:20:00.000,2"""
fmt = "%d.%m.%Y %H:%M:%S.%f"
pd.read_csv(io.StringIO(data),
            index_col=0, date_parser=lambda x: pd.to_datetime(x, fmt), parse_dates=True,
            )
```
That will raise an `AssertionError`, but maybe because of my own problems, may be it has nothing with this issues. I just want to point it.

**Comment by MarcoGorelli** [comment]
please wait, this needs discussion about whether or not this keyword needs adding

**Comment by MarcoGorelli** [comment]
closing in favour of https://github.com/pandas-dev/pandas/issues/50601
