### ISSUE TITLE
BUG: when pd.nanops.nansum delegates to numpy.sum(), nans no longer treated as zeroes

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [pandas-dev/pandas#50564]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import numpy as np
import uncertainties as un
from uncertainties import unumpy as unp
import pandas as pd
import pint
import pint_pandas

from pint import Quantity as Q_
from pint_pandas import PintArray as PA_
from uncertainties import ufloat

udata = [ufloat(1.2, .3), ufloat(np.nan, 0), ufloat(4.5, .6)]

print(f"uncertainties input data: {udata}")
print(f"sum({udata}) = {sum(udata)}")

ser = pd.Series(PA_(unp.nominal_values(udata),
                    dtype='m'))
print("float64 series with NaNs sums to non-NaN result")
print(ser)
print(ser.sum())

print("uncertainties series with NaNs should sum to non-NaN result")
user = pd.Series(PA_(udata, dtype='m'))
print(user)
print(user.sum())

print("uncertainties series filling NaNs with zeros sums to non-NaN and expected result")
print(user.fillna(0))
print(user.fillna(0).sum())
```

### Issue Description

The `sum` function in Pandas treats NaN values as zero.  Extension arrays honor this, delegating "sum" to nanops.nansum and giving the extension array implementor the opportunity to follow that pattern.  When I use uncertainties (which wrap numpy functions) inside Pint Extension arrays (which implement nanops), wires get crossed and `sum` doesn't work as expected.  The problem is actually here, where pandas...:
```
pandas/core/nanops.py(631)nansum()
-> the_sum = values.sum(axis, dtype=dtype_sum)
```
calls to numpy...:
```
numpy/core/_methods.py(48)_sum()
-> return umr_sum(a, axis, dtype, out, keepdims, initial, where)
```
which takes what uncertainties told it to do FOR THE SUM FUNCTION, not for nansum:
```
uncertainties/core.py(659)f_with_affine_output()
-> pos_w_uncert = [index for (index, value) in enumerate(args)
```

Perhaps Pandas is to blame for calling values.sum instead of values.nansum?

### Expected Behavior

I expect that pandas nansum would delegate to numpy nansum, not numpy's sum.

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 8dab54d6573f7186ff0c3b6364d5e4dd635ff3e7
python           : 3.9.13.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.6.0
Version          : Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.2
numpy            : 1.23.4
pytz             : 2022.7
dateutil         : 2.8.2
setuptools       : 65.6.3
pip              : 22.3.1
Cython           : 0.29.32
pytest           : 7.2.0
hypothesis       : 6.56.3
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.7.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : 
fastparquet      : 0.8.3
fsspec           : 2022.11.0
gcsfs            : None
matplotlib       : 3.6.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : 2.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : 1.4.42
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : 0.19.0
tzdata           : None
</details>

**Comment by topper-123** [comment]
Hi @MichaelTiemannOSC. The pandas `nansum` works with a lot of different array types having nan-like using `np.sum` in the location that you point out. I'm not sure I understand why it doesn't work in your case even after your explanation.

Your example uses two external libraries. Is it possible to narrow your example down to just `pint_array`? That will make it easier for pandas developers to understand why/how this is problematic on pandas' end.

**Comment by MichaelTiemannOSC** [comment]
Hi @topper-123

The example I gave already demonstrates that when the pint_array is filled with float64, the code works as expected ("float64 series with NaNs sums to non-NaN result").  The whole point of this report is that failure is caused when we bring uncertainties into the mix.  Uncertainties, as a package, has two library modules that work in concert: uncertainties (which does the uncertainty math) and unumpy (which wraps everything).

Here is a simplified test case that removes pint_array from the mix.  It still fails in exactly the same way for the same reason: pandas is delegating to `sum` in `nansum` when it could be delegating to `nansum`.

```
import numpy as np
import uncertainties as un
from uncertainties import unumpy as unp
import pandas as pd
from uncertainties import ufloat

udata = [ufloat(1.2, .3), ufloat(np.nan, 0), ufloat(4.5, .6)]

f64data = unp.nominal_values(udata)

print(f"nominal input data: {f64data}")
print(f"sum({f64data}) = {sum(f64data)}")

nser = pd.Series(f64data)
print("float64 series with NaNs sums to non-NaN result")
print(nser)
print(nser.sum())

print(f"uncertainties input data: {udata}")
print(f"sum({udata}) = {sum(udata)}")

print("uncertainties series with NaNs should sum to non-NaN result")
user = pd.Series(udata)
print(user)
print(user.sum())

print("uncertainties series filling NaNs with zeros doesn't help, because fillna doesn't know about uncertainties.umath.isnan() and np.isnan() is wrong")
print(user.fillna(0))
print(user.fillna(0).sum())
```

**Comment by topper-123** [comment]
Ok thank you, I've looked into this.

The core issue here, from pandas perspective, is that it assess if something is nan-like by checking if it passes `pd.isna(val)`. In you second example file for example `pd.isna(user[0])` evaluates to False, i.e. pandas can't know it is nan-like.

The same issue is in your pint_pandas example (I think, haven't run the code), i.e. I'd wager that  in your first example `ser.array.isna())` also gives False for the value in the 1 position.

To make pandas support various external data structure, it is absolutely necessary that those data structures use and conforms to the `ExtensionArray` format. `Pint_Pandas` does, but (my guess, haven't checked) it doesn't support `uncertainties`, so Pandas can't either. We don't give guarantees about external data structures working in pandas beyond the ´ExtensionArray´, sorry.

My guess is that changing `sum` to ´nansum´ in the shown example will have some effects in pandas (either functionally or performancewise) that won't be acceptable. If you can show that the change will be backward compatible and not have adverse performance effects, we will of course  consider it.

**Comment by mroeschke** [comment]
Agreed it seems like this is not addressable outside the EA interface so closing for now
