### ISSUE TITLE
BUG: `to_numpy` is now failing given incompatible `na_value`

### ISSUE THREAD

**Issue by lbittarello** [pandas-dev/pandas#50600]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.
- [ ] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.
- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import numpy as np
import pandas as pd

pd.Series([1]).to_numpy(dtype="float", na_value=np.nan)
```

### Issue Description

`to_numpy` is currently failing when the `na_value` isn't compatible with the type of a series, even if we request casting to a suitable type. [This commit](https://github.com/pandas-dev/pandas/commit/60dc3f544178e83660796133302cecbd8da28b91) looks suspicious, as it removed a casting step (L534: `np.asarray(self._values, dtype=dtype)`).

### Expected Behavior

I would have expected the example to produce `np.array([1.0])` as it used to.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 92e458d8037057b73724d10badfe3afd4580a262
python           : 3.10.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252

pandas           : 2.0.0.dev0+1087.g92e458d803
numpy            : 1.23.5
pytz             : 2022.7
dateutil         : 2.8.2
setuptools       : 65.6.3
pip              : 22.3.1
Cython           : None
pytest           : 7.2.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.8.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : 
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : 0.56.4
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.0
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : 0.19.0
tzdata           : None
qtpy             : None
pyqt5            : None

</details>

**Comment by mroeschke** [comment]
cc @phofl

**Comment by phofl** [comment]
Thx, will take a look
