### ISSUE TITLE
BUG: agg ignores args/kwargs when giving a list-like argument

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#50624]
I think the expected value of `(a, b)` in the function below is `(5, 6)`.

```
def foo(x, a=1, b=2):
    print(a, b)
    return x

df = pd.DataFrame({'x': [1, 2, 3]})
# 0 is for the axis argument; 5 is the first (and only) in args
print(df.agg([foo], 0, 5, b=6))
# 1 2
# 1 2
# 1 2
```

This issue may also persist with apply and transform, in DataFrame, Series, DataFrameGroupBy, SeriesGroupBy, Rolling, and Resampler, and with other types of arguments (single and/or dict-likes). This should be fully investigated to determine where args / kwargs are ignored.

**Comment by luke396** [comment]
take

**Comment by luke396** [comment]
I have just resolved the issue for the given single-element function list. However, addressing the issue for a list containing multiple functions may require further considerations, such as potential naming conflicts and additional requirements. It may be necessary to have further discussions and potentially make adjustments to the original API design.
