### ISSUE TITLE
df.apply(...): better error messages in case of NaN

### ISSUE THREAD

**Issue by jankatins** [pandas-dev/pandas#5062]
I had to debug a problem which was caused by a NaN in a string column:

``` python
cit  = citations[1655:1660][["names"]]
print cit

             names
1655           A;B
1656          NaN
1657           C;D
1658           E;F
1659          G;H

s = cit.apply(lambda x: pandas.Series(x.split(';'))).stack()
[...]
C:\portabel\Python27\lib\site-packages\pandas\core\series.pyc in apply(self, func, convert_dtype, args, **kwds)
   1952             values = lib.map_infer(values, lib.Timestamp)
   1953 
-> 1954         mapped = lib.map_infer(values, f, convert=convert_dtype)
   1955         if len(mapped) and isinstance(mapped[0], Series):
   1956             from pandas.core.frame import DataFrame

C:\portabel\Python27\lib\site-packages\pandas\lib.pyd in pandas.lib.map_infer (pandas\lib.c:43742)()

<timed exec> in <lambda>(x)

AttributeError: 'float' object has no attribute 'split'
```

I would be nice if pandas could in that case spit out a more helpfull error messages or check if the error occured on a NaN cell and simple set that cell to NaN (Does R this?) or rethrow  the error as a "NaNError" or something like that.

**Comment by flyingmeatball** [comment]
@jtratner Was this ever implemented?  I'm on 0.17.0 and am getting this error:

    In [449]:
    combined_data['Status Date'].apply(lambda x: datetime.datetime.strptime(x, '%Y-%m-%d') )
    Out [449]:
   
     ...
    TypeError: must be string, not float

Looking at the records, causing it:

    In [460]:
    combined_data['Status Date'].apply (lambda x: type(x))
    Out[460]:
    0      <type 'unicode'>
    1      <type 'unicode'>
    2      <type 'unicode'>
    3      <type 'unicode'>
    4        <type 'float'>

Verifying that this is indeed caused by a NaN:

    In [462]:    
    combined_data[['Status Date']].ix[4]
    Out[462]:
    Status Date    NaN
    Name: 4, dtype: object

I agree with @JanSchulz that this behavior is a bit confusing, especially for users relatively new to Pandas (I've had to explain the same NaN float error three times to new Pandas users on my team).

**Comment by jreback** [comment]
@flyingmeatball the issue is still open, so not implemented.

I guess you could do something, but ``.apply`` is almost always the last possible way to do something in any event.

**Comment by flyingmeatball** [comment]
@jreback thanks for the reply.

I try and avoid .apply where possible, but there are many transformations I end up making where I can't find a better way to do something relatively simple, such as string transformations, or working with the series.shift() method.

I think it's also an easy error for someone who is not that familiar with Pandas to encounter.  .apply(lambda x: x...) is a straightforward construction for iterating over series values and using native python.  That's where the value of updating the error would be - for new(er) users, it becomes tedious to troubleshoot and the error message doesn't really describe what is happening.  

I appreciate that this is a small issue in the scheme of things. I'm not familiar enough with the underlying code base to submit a pull request for a change, but I may explore a bit when I have some time.

**Comment by jreback** [comment]
@flyingmeatball ok sure

**Comment by AbeHandler** [comment]
+1
