### ISSUE TITLE
DOC: tz_x functions do not include zoneinfo and tzinfo support in their documentation

### ISSUE THREAD

**Issue by aqeelat** [pandas-dev/pandas#50655]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

This is present in multiple places such as:

- https://pandas.pydata.org/docs/reference/api/pandas.DatetimeIndex.tz_localize.html
- https://pandas.pydata.org/docs/reference/api/pandas.Series.dt.tz_localize.html
- https://pandas.pydata.org/docs/reference/api/pandas.DatetimeIndex.tz_convert.html

### Documentation problem

The listed types for the parameter `tz` is `str, pytz.timezone, dateutil.tz.tzfile or None`, even though zoneinfo and tzinfo are supported.

### Suggested fix for documentation

I suggest adding updating the docs to include tzinfo.

We could probably skip zoneinfo.ZoneInfo since it is a subclass of tzinfo.

**Comment by luke396** [comment]
take
