### ISSUE TITLE
BUG: .max() gives wrong answer for non-nanosecond datetimeindex

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#50716]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
In [3]: DatetimeIndex(['2015-09-22 08:31:00', '2015-09-19 09:02:00','2015-09-19 14:14:00'], dtype='datetime64[s]').as_
   ...: unit('s').max()
Out[3]: Timestamp('1970-01-01 00:00:01')
```

### Issue Description

should give '2015-09-19 14:14:00' Timestamp

### Expected Behavior

should give '2015-09-19 14:14:00' Timestamp

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : ad91ead6de5d6b90747b10d365ba758dbbfd95a4
python           : 3.11.1.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 2.0.0.dev0+1157.gad91ead6de
numpy            : 1.25.0.dev0+363.gbb2769e12
pytz             : 2022.7
dateutil         : 2.8.2
setuptools       : 65.7.0
pip              : 22.3.1
Cython           : 0.29.33
pytest           : 7.2.0
hypothesis       : 6.52.1
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.8.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : None
qtpy             : None
pyqt5            : None
None

</details>

**Comment by jbrockmendel** [comment]
take

**Comment by MarcoGorelli** [comment]
@jbrockmendel have you already started this? I'd just started a PR, but happy to let it go if you're already on it
