### ISSUE TITLE
ADMIN: Remove pandas-core-inactive team

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#50815]
I guess it's happening to everybody else, when tagging @pandas-dev/pandas-core GitHub always recommends the pandas-core-inactive team instead. We created the pandas-core-inactive team just in case, but I don't think it's very helpful, and having it makes it very annoying every time we want to tag pandas-core. If there are no objections, can we please get rid of it?

I don't have permissions, can you take care of it @jreback please? Thank you!

**Comment by jreback** [comment]
hmm AFAICT pandas-core-inactive doesn't exist, where do you see it?

**Comment by MarcoGorelli** [comment]
here: https://github.com/orgs/pandas-dev/teams/pandas-core-inactive

**Comment by datapythonista** [comment]
It's here: https://github.com/orgs/pandas-dev/teams 

I guess you're checking the teams in the pandas repo, not in the pandas org? I guess it's not a permissions problem. I think I created that group, and I can add members and change the name, but I don't think I can delete it.

**Comment by datapythonista** [comment]
Thanks Jeff. Much better. It shows me some other groups first now, but at least pandas-core is in the list. Closing.
