### ISSUE TITLE
STYLE remove absolufy-imports, use ruff

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#50812]
Issue is:

1. remove

https://github.com/pandas-dev/pandas/blob/db8af0e767cb66a7b747984feec380822012cce9/.pre-commit-config.yaml#L22-L26

2. add the `ruff` check which checks the same thing (but faster)

https://github.com/pandas-dev/pandas/blob/5b6d6eba9ec372baa8c0755b59f72cfb9d4db873/pyproject.toml#L187-L206

(note: you may need `per-file-ignores` to ignore the `asv_bench` directory from the check)

check that `pre-commit run ruff --all-files` passes

**Comment by hisergiorojas** [comment]
take

**Comment by hisergiorojas** [comment]
The checks fails when I run the command:
`pre-commit run ruff --all-files`

Do I auto fix the formatting errors?

![Screenshot from 2023-01-18 22-10-43](https://user-images.githubusercontent.com/48057303/213368800-d292b43e-9317-4512-8eb7-f88f58d654a3.png)
