### ISSUE TITLE
DOC: DataFrame.count_values supports single label

### ISSUE THREAD

**Issue by mattf** [pandas-dev/pandas#50829]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.value_counts.html

### Documentation problem

documentation claims the `subset` must be `list-like, optional`

the [implementation](https://github.com/pandas-dev/pandas/blob/v1.5.2/pandas/core/frame.py#L7215) uses [`DataFrame.groupby`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html), which accepts `mapping, function, label, or list of labels`

the result is `value_counts` can accept a single label

```
In [1]: import pandas as pd

In [2]: pd.__version__
Out[2]: '1.5.2'

In [3]: df = pd.DataFrame({"XYZ": ["foo", "foo", "foo", "foo", "foo"]})

In [4]: df.value_counts("XYZ")
Out[4]: 
XYZ
foo    5
dtype: int64
```

### Suggested fix for documentation

1. change the `value_counts` documentation to reflect its capabilities
2. change the `value_counts` implementation to reflect the documentation

use of [groupby goes to value_count's inception](https://github.com/pandas-dev/pandas/pull/31247), and groupby's api has been [consistent since 1.0](https://pandas.pydata.org/pandas-docs/version/1.0/reference/api/pandas.DataFrame.groupby.html)

+1 option (1)

**Comment by mroeschke** [comment]
Thanks for the report. Additionally I don't see any testing of a single label `subset` so that would be good to add as well.

**Comment by tpackard1** [comment]
take

**Comment by jayam30** [comment]
Hey I want to start my contribution with this, could I be assigned this
