### ISSUE TITLE
DOC: Use rst instead of markdown in release instructions

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#50824]
Looks like when I moved the release procedure to the pandas docs I didn't realize I had the notes in markdown, and the docs are in rst. The formatting is all broken because of this: https://pandas.pydata.org/docs/dev/development/maintaining.html#release-process

We should replace the mardown with rst, so sphinx can render things correctly.

**Comment by tpackard1** [comment]
take

**Comment by datapythonista** [comment]
Those are the ones that I noticed, but I didn't check in detail. Feel free to start by those, and if we notice something else, we can take care in a follow up.
