### ISSUE TITLE
BUG: when start_time > end_time, between_time includes rows where index is null 

### ISSUE THREAD

**Issue by mvashishtha** [pandas-dev/pandas#50865]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import datetime
import pandas as pd

rng = pd.date_range(start="1/1/2000", periods=1)
ts = pd.DataFrame([1, 2], index=[None, *rng])
print(ts.between_time("23:00", "00:01"))
```

### Issue Description

I get rows where index is `NaT`, but I don't want them.

### Expected Behavior

Should drop `NaT` rows. The cause is that the index is comparing times with `self._get_time_micros()`, which converts null values to -1, which meets the [criterion](https://github.com/pandas-dev/pandas/blob/268bccd19d0d6e8d7448cd890b68cf6510246047/pandas/core/indexes/datetimes.py#L762-L778) of being `<= _time_to_micros(to_time("23:00"))` or `<= _time_to_micros(to_time("00:01"))`

### Installed Versions

<details>

/Users/maheshvashishtha/opt/anaconda3/envs/pandas-dev/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit           : 7cb7592523380133f552e258f272a5694e37957a
python           : 3.10.4.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.5.0
Version          : Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.0.dev0+1147.g7cb7592523
numpy            : 1.23.3
pytz             : 2022.2.1
dateutil         : 2.8.2
setuptools       : 63.4.1
pip              : 22.1.2
Cython           : 0.29.32
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.5.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : None
qtpy             : None
pyqt5            : None

</details>

**Comment by topper-123** [comment]
Yes, this is a bug. Thanks, @mvashishtha.

PR would be appreciated.

**Comment by mvashishtha** [comment]
@topper-123 I think we can close all the `first` and `last` issues because these methods are being deprecated: https://github.com/pandas-dev/pandas/issues/50884#issuecomment-1527415805

**Comment by topper-123** [comment]
Ok, I wasn't aware of that discussion. Thanks for the report though.

**Comment by mvashishtha** [comment]
@topper-123 I now realize that this issue was for `between_time`, not `first` or `last`. Should we reopen it?
