### ISSUE TITLE
Nightly builds failing since 1/20/2023

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#50898]
From slack discussion with @lithomas1 :

Due to tests we do with pandas-stubs, I found out that our nightly builds are not being done for all platforms.  Last one that exists is from January 12, but there are only Win32 nightly builds since then.

Take a look at https://pypi.anaconda.org/scipy-wheels-nightly/simple/pandas/ and search for `pandas-2.0.0.dev0+1147.g7cb7592523-cp39-cp39-macosx_10_9_x86_64.whl` to see that last build and then the ones that follow are only for win32.

@lithomas1 wrote :
Nightlies have been failing for a while now, unfortunately, and they don't get uploaded when the job fails.
(We don't test on win32, since no 32-bit Docker images, so that's why those are uploaded successfully).
The failure is
FAILED ../tmp/tmp.3kVb4tJ00H/venv/lib/python3.8/site-packages/pandas/tests/io/test_stata.py::TestStata::test_encoding_latin1_118

**Comment by mroeschke** [comment]
Maybe this is more appropriate for https://github.com/MacPython/pandas-wheels?

**Comment by Dr-Irv** [comment]
> Maybe this is more appropriate for https://github.com/MacPython/pandas-wheels?

But all the Linux and Win64 nightly builds are failing as well.  So it's not just a MacPython issue.

**Comment by lithomas1** [comment]
@Dr-Irv I can run them by manually for you.

**Comment by lithomas1** [comment]
@Dr-Irv Wheels are starting to trickle in. Should be all good in the next 30 minutes (unless something is _really_ slow)

Here is the URL to the run if you want to follow along.
https://github.com/pandas-dev/pandas/actions/runs/4019097996

**Comment by Dr-Irv** [comment]
> EDIT: All done. I'll let you close this one.

Yup, looks good.  Thanks!
