### ISSUE TITLE
REGR: SeriesGroupBy.value_counts failure on Windows

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#50920]
Ref: https://github.com/pandas-dev/pandas/pull/50761#issuecomment-1399236962

It appears there is a test failing that hasn't shown up on the CI. I'm guessing it might be because it's marked as slow and only fails on Windows.

Putting this on the 2.0 Milestone as it doesn't fail on 1.5.x.

**Comment by rhshadrach** [comment]
@mroeschke - I'm moving this to 2.0.1 since it's a regression from 1.5.x. Let me know if you think differently.

**Comment by lithomas1** [comment]
Pushing off of 2.0.3.

@rhshadrach 
Do you know if this is still failing on main/2.0.x?

I don't have Windows, so it's not convenient for me to check. If this is still open by 2.0.4, though, I boot up something on OVH and check by hand.

**Comment by rhshadrach** [comment]
I'm in the same situation @lithomas. But I think I can modify the tests to see if it still exists via our Windows runner. I'll take this up in the next day or two.

**Comment by rhshadrach** [comment]
No longer able to reproduce in #53943

**Comment by lithomas1** [comment]
Thanks for checking!
