### ISSUE TITLE
BUG: Reindexing a DataFrame with a list of columns leeds to duplicate column

### ISSUE THREAD

**Issue by abokey1** [pandas-dev/pandas#50924]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame()
df = df.reindex(columns=list(df.columns) + ['A'])
df = df.reindex(columns=list(df.columns) + ['A'])
print(df.columns)
# Output: Index(['A', 'A'], dtype='object')

# ------------------------------------------------

df = pd.DataFrame()
df.insert(0, 'A', None)
df.insert(0, 'A', None) # <- Raises ValueError: cannot insert A, already exists
```

### Issue Description

I am unsure if this behavior is intended or *(a bug?)*, and would appreciate any insight on the matter. It seems strange that the [`pandas.DataFrame.reindex`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reindex.html) method allows in the Reproducible Example the creation of a **duplicate** column, while the [`pandas.DataFrame.insert`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.insert.html) method raises an error when we try to insert the same column (i.e, `'A'`) two times in a row.

### Expected Behavior

I would expect pandas to raise an error when using [`pandas.DataFrame.reindex`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reindex.html) to conform a `pandas.core.frame.DataFrame` with a list of columns when at least one of those already exists in the dataframe.

In the documentation, we read : 

<img src="https://user-images.githubusercontent.com/113783165/213875966-b2b63ed6-8c88-4c5e-af8c-688fcbaa17b1.png" alt="drawing" width="600"/>

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
python           : 3.11.0.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
pandas           : 1.5.3

</details>

**Comment by phofl** [comment]
This behaves as intended, insert has an option to allow duplicates and the constructor allows you to create duplicated columns as well
