### ISSUE TITLE
The project is great. Is there a flutter version? Flutter is an open source mobile application software development kit developed by Google for developing applications for Android, iOS, Web, Windows, macOS, Linux Desktop, Google Fuchsia. Flutter is making efforts to games, Metaverse, and web3. ![flutter](https://user-images.githubusercontent.com/122947293/213731917-caf3dfd0-db1d-4b1c-ba21-85d8f0985396.png) https://github.com/flutter/flutter 项目非常棒 有flutter版本吗？Flutter是一个由谷歌开发的开源移动应用软件开发工具包，用于为Android、iOS、Web、We'bWindows、macOS、Linux Desktop、Google Fuchsia开发应用。 Flutter正在向游戏、元宇宙、web3发力。

### ISSUE THREAD

**Issue by swordbe** [pandas-dev/pandas#50935]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
The project is great. Is there a flutter version? Flutter is an open source mobile application software development kit developed by Google for developing applications for Android, iOS, Web, Windows, macOS, Linux Desktop, Google Fuchsia. Flutter is making efforts to games, Metaverse, and web3. ![flutter](https://user-images.githubusercontent.com/122947293/213731917-caf3dfd0-db1d-4b1c-ba21-85d8f0985396.png) https://github.com/flutter/flutter 项目非常棒 有flutter版本吗？Flutter是一个由谷歌开发的开源移动应用软件开发工具包，用于为Android、iOS、Web、We'bWindows、macOS、Linux Desktop、Google Fuchsia开发应用。 Flutter正在向游戏、元宇宙、web3发力。
```

### Issue Description

The project is great. Is there a flutter version? Flutter is an open source mobile application software development kit developed by Google for developing applications for Android, iOS, Web, Windows, macOS, Linux Desktop, Google Fuchsia. Flutter is making efforts to games, Metaverse, and web3. ![flutter](https://user-images.githubusercontent.com/122947293/213731917-caf3dfd0-db1d-4b1c-ba21-85d8f0985396.png) https://github.com/flutter/flutter 项目非常棒 有flutter版本吗？Flutter是一个由谷歌开发的开源移动应用软件开发工具包，用于为Android、iOS、Web、We'bWindows、macOS、Linux Desktop、Google Fuchsia开发应用。 Flutter正在向游戏、元宇宙、web3发力。

### Expected Behavior

The project is great. Is there a flutter version? Flutter is an open source mobile application software development kit developed by Google for developing applications for Android, iOS, Web, Windows, macOS, Linux Desktop, Google Fuchsia. Flutter is making efforts to games, Metaverse, and web3. ![flutter](https://user-images.githubusercontent.com/122947293/213731917-caf3dfd0-db1d-4b1c-ba21-85d8f0985396.png) https://github.com/flutter/flutter 项目非常棒 有flutter版本吗？Flutter是一个由谷歌开发的开源移动应用软件开发工具包，用于为Android、iOS、Web、We'bWindows、macOS、Linux Desktop、Google Fuchsia开发应用。 Flutter正在向游戏、元宇宙、web3发力。

### Installed Versions

The project is great. Is there a flutter version? Flutter is an open source mobile application software development kit developed by Google for developing applications for Android, iOS, Web, Windows, macOS, Linux Desktop, Google Fuchsia. Flutter is making efforts to games, Metaverse, and web3. ![flutter](https://user-images.githubusercontent.com/122947293/213731917-caf3dfd0-db1d-4b1c-ba21-85d8f0985396.png) https://github.com/flutter/flutter 项目非常棒 有flutter版本吗？Flutter是一个由谷歌开发的开源移动应用软件开发工具包，用于为Android、iOS、Web、We'bWindows、macOS、Linux Desktop、Google Fuchsia开发应用。 Flutter正在向游戏、元宇宙、web3发力。

**Comment by attack68** [comment]
closing as spam
