### ISSUE TITLE
BUG: query(engine='numexpr') not work correctly when column name is 'max' or 'min'.

### ISSUE THREAD

**Issue by bsdfan** [pandas-dev/pandas#50937]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({'max': [1, 2, 3]})
df.query('max == 1', engine='numexpr')
# Empty DataFrame
df.query('max < 2', engine='numexpr')
# TypeError: '<' not supported between instances of 'function' and 'int'
```

### Issue Description

DataFrame.query(engine='numexpr') does not work correctly when column name is 'max' or 'min'.

Because numexpr seems to have 'max' and 'min' as built-in reduction function though it is not officially documented, 
https://github.com/pydata/numexpr/issues/120

These keywords should be checked in pandas like 'sum' and 'prod'.
So REDUCTIONS in pandas/core/computation/ops.py may need to be updated.

### Expected Behavior

NumExprClobberingError should be raised.

```python
import pandas as pd

df = pd.DataFrame({'max': [1, 2, 3]})
df.query('max == 1', engine='numexpr')
# NumExprClobberingError: Variables in expression "(max) == (1)" overlap with builtins: ('max')
```

### Installed Versions

<details>
```
INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.9.16.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Japanese_Japan.932

pandas           : 1.5.3
numpy            : 1.22.3
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 66.1.1
pip              : 22.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.8.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : 0.56.3
numexpr          : 2.8.4
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 10.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None
```
</details>

**Comment by ShisuiUzumaki** [comment]
I am interested. Do I need to check whether the passed column is a reduction function and, if so, raise the error?

**Comment by bsdfan** [comment]
pandas already has a such feature.

_check_ne_builtin_clash() checks whether the column name is reserved. 
https://github.com/pandas-dev/pandas/blob/main/pandas/core/computation/engines.py#L28-L44

For example, if I use 'sum', 'sin' or 'exp' as column name, this function raise NumExprClobberingError.
But 'max' and 'min' pass this check because they are not listed as reduction function.
https://github.com/pandas-dev/pandas/blob/main/pandas/core/computation/ops.py#L38

On the latest numexpr document, only 'sum' and 'prod' are reduction operation,
but 'max' and 'min' seem to be introduced already.
https://numexpr.readthedocs.io/projects/NumExpr3/en/latest/user_guide.html#supported-reduction-operations

**Comment by ShisuiUzumaki** [comment]
> pandas already has a such feature.
> 
> _check_ne_builtin_clash() checks whether the column name is reserved. https://github.com/pandas-dev/pandas/blob/main/pandas/core/computation/engines.py#L28-L44
> 
> For example, if I use 'sum', 'sin' or 'exp' as column name, this function raise NumExprClobberingError. But 'max' and 'min' pass this check because they are not listed as reduction function. https://github.com/pandas-dev/pandas/blob/main/pandas/core/computation/ops.py#L38
> 
> On the latest numexpr document, only 'sum' and 'prod' are reduction operation, but 'max' and 'min' seem to be introduced already. https://numexpr.readthedocs.io/projects/NumExpr3/en/latest/user_guide.html#supported-reduction-operations

So, does that mean we only need to ensure that `min` and `max` are recognized as reduction operations?

**Comment by bsdfan** [comment]
> So, does that mean we only need to ensure that min and max are recognized as reduction operations?

Yes.

**Comment by ShisuiUzumaki** [comment]
> > So, does that mean we only need to ensure that min and max are recognized as reduction operations?
> 
> Yes.

Can you give me some pointer on how to do that?

**Comment by bsdfan** [comment]
I think this is all.
```diff
--- a/pandas/core/computation/ops.py
+++ b/pandas/core/computation/ops.py
@@ -35,7 +35,7 @@ from pandas.io.formats.printing import (
     pprint_thing_encoded,
 )
 
-REDUCTIONS = ("sum", "prod")
+REDUCTIONS = ("sum", "prod", "max", "min")
 
 _unary_math_ops = (
     "sin",
```

**Comment by ShisuiUzumaki** [comment]
> I think this is all.
> 
> ```diff
> --- a/pandas/core/computation/ops.py
> +++ b/pandas/core/computation/ops.py
> @@ -35,7 +35,7 @@ from pandas.io.formats.printing import (
>      pprint_thing_encoded,
>  )
>  
> -REDUCTIONS = ("sum", "prod")
> +REDUCTIONS = ("sum", "prod", "max", "min")
>  
>  _unary_math_ops = (
>      "sin",
> ```

We only need to make these changes in this file?

**Comment by ShisuiUzumaki** [comment]
take

**Comment by bsdfan** [comment]
Thanks for your comment.

According to numexpr source code (https://github.com/pydata/numexpr/blob/62cc05148fd6eb8bb32ed1bbcaf102149da6445e/numexpr/expressions.py#L334-L377), 
mean, median, var, std, skew, and kurt are not pre-defined functions.
So you don't need to add.

**Comment by ShisuiUzumaki** [comment]
> Thanks for your comment.
> 
> According to numexpr source code (https://github.com/pydata/numexpr/blob/62cc05148fd6eb8bb32ed1bbcaf102149da6445e/numexpr/expressions.py#L334-L377), mean, median, var, std, skew, and kurt are not pre-defined functions. So you don't need to add.

Ok, got it!
