### ISSUE TITLE
ENH: IntervalIndex.edges

### ISSUE THREAD

**Issue by yohplala** [pandas-dev/pandas#50944]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish I could have `pd.IntervalIndex` returning all interval edges.

### Feature Description

Add a new parameter `edges` to `IntervalIndex` to return all `Intervals` edges as an 1d array or an `Index`.

### Alternative Solutions

Write a custom function doing the job. Something like:

```python
import pandas as pd

def interval_index_to_edges(interval_index):
    return interval_index.left.append(pd.Index([interval_index[-1].right]))
```

**Comment by mroeschke** [comment]
Agreed, I would be -1 on adding a new API just for this so closing
