### ISSUE TITLE
ENH: .interpolate() with EA Dtypes

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#50950]
```python
ser = pd.Series([1, 2, None, 4], dtype="Int64")

>>> ser.interpolate()
[...]
ValueError: Invalid fill method. Expecting pad (ffill) or backfill (bfill). Got linear
```

EABackedBlock.interpolate dispatches to EA.fillna, which doesn't handle `method="linear"`.  Getting this right probably will require implementing something new at the EA level.

### Expected Behavior

`pd.Series([1, 2, 3, 4])`

**Comment by topper-123** [comment]
Yeah , I think this should be implemented.

**Comment by jbrockmendel** [comment]
@jorisvandenbossche any idea if pyarrow has/plans anything analogous to the numpy/scipy interpolation functions we call from core.missing?
