### ISSUE TITLE
DEPR: *args, **kwargs on resample methods

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#50977]
xref https://github.com/pandas-dev/pandas/pull/50913#discussion_r1086815567

Similar to https://github.com/pandas-dev/pandas/pull/50338, *args, **kwargs were deprecated and removed in 1.x for rolling-like methods, so the same should apply to resample methods as well.

**Comment by kostyafarber** [comment]
I could have a go at this if nobody is currently working on it.

**Comment by phofl** [comment]
Sounds good!
