### ISSUE TITLE
PERF: to_dict('list') method slow

### ISSUE THREAD

**Issue by 8FordPrefect8** [pandas-dev/pandas#50990]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this issue exists on the main branch of pandas.

### Reproducible Example

I want to transform pandas DataFrames to dictionaries in order to hand over data as python std lib object. I had the idea of using the to_dict method. My prior experience with pandas and numpy was that my custom few liners never can compete with the provided methods performance wise. But when I noticed that the to_dict method can become a bottle neck I tried out a rather simple attempt to achieve what I wanted. I measured something like a improvement of factor 5, which is very much noticeable to me, as the transformation with to_dict can take tens of seconds for me.

I wonder if this can be improved or whether my method has some draw backs I can't anticipate right now. 

```python
import pandas as pd
import time


data_frame = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn'
                        '-data/master/iris.csv')

t0 = time.perf_counter_ns()
dict_to_dict = data_frame.to_dict('list')
t1 = time.perf_counter_ns()

values = data_frame.values
dict_custom = {}
for i, col in enumerate(data_frame.columns):
    dict_custom[col] = values[:,i].tolist()

t2 = time.perf_counter_ns()

print(f"Time with to_dict('list'):\t{(t1-t0)/10**9},\n"
      f"Time with custom method:\t{(t2-t1)/10**9}"
      )
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.8.7.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.17763
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252
pandas           : 1.5.3
numpy            : 1.24.1
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 65.6.3
pip              : 22.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by phofl** [comment]
Hi, thanks for your report. Our implementation is similar, investigations are welcome

**Comment by 8FordPrefect8** [comment]
I tried to unterstand what the pandas code is doing. I am not really familar with the codebase. But it appears there are not too many paths to follow.

My first idea would be that it's related to the mapping with the `maybe_box_native` function.

**Comment by taytzehao** [comment]
It seems that this is because df.items() is being used to extract the column and the values. The values are `pd.Series` type as opposed to the optimized one that is a numpy type that was shown on top. I am looking whether it would be possible to use numpy rather than pd.Series too. 

Let's say if this theory is correct, this could be implmented on other orient too

**Comment by taytzehao** [comment]
@phofl
