### ISSUE TITLE
BUG: df.to_excel() makes some default formatting

### ISSUE THREAD

**Issue by Franky1** [pandas-dev/pandas#50991]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
data = {'col_1': [3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd']}
df = pd.DataFrame.from_dict(data)
df.to_excel('bug.xlsx', index=True)

# have a look at the generated bug.xlsx file
```

### Issue Description

Not really a bug, but a bit unexpected:
The index column and the header row is formatted in **bold** and with thin frame lines around.
The rest of the table data is not formatted.

### Expected Behavior

I would expect no formatting at all, unless specified.
But maybe this behaviour is intended?

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.9.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19045
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : de_DE.UTF-8
LOCALE           : de_DE.cp1252

pandas           : 1.5.3
numpy            : 1.24.1
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 64.0.2
pip              : 22.3.1
Cython           : None
pytest           : None
hypothesis       : None
...
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : 2022.7

</details>

**Comment by attack68** [comment]
https://github.com/pandas-dev/pandas/issues/50336#issuecomment-1361345962

**Comment by phofl** [comment]
Hi, thanks for your report. lets close this for the other issue
