### ISSUE TITLE
BUG: A trivial C++ module crashes if you import it after pandas

### ISSUE THREAD

**Issue by kapacuk** [pandas-dev/pandas#50994]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```bash
cat >spam.cpp <<END
```
```c++
#include <Python.h>
#include <filesystem>
PyMODINIT_FUNC PyInit_spam(void)
{
    std::filesystem::path p1("/usr/share/icons");
    std::filesystem::path p2("hicolor");
    auto x = p1 / p2;
    return NULL;
}
```
```bash
END
g++-12 -I/usr/include/python3.9 -g -fPIC -std=c++20 -fsanitize=address -shared -o spam.cpython-39-x86_64-linux-gnu.so spam.cpp
python -c "import pandas; import spam"
```

### Issue Description

The above example is a trivial python module with no classes or methods.  It does not even try to create a PyModule object, so if you import it on its own it throws this exception:
`SystemError: initialization of spam failed without raising an exception`
which is expected.

However, if you import this module after pandas it crashes printing a single error message:
`munmap_chunk(): invalid pointer`

I tried it with python3.9, 3.10, and 3.11, and with gcc-11 and gcc-12. It crashes consistently, although sometimes I get a different the error message.

### Expected Behavior

That example should throw the `SystemError` exception regardless of whether you import it before or after pandas.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.9.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.0-13-amd64
Version          : #1 SMP Debian 5.10.106-1 (2022-03-17)
machine          : x86_64
processor        :
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.24.1
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 66.1.1
pip              : 22.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None
None

</details>

**Comment by Jython1415** [comment]
I'm struggling to reproduce this, but I suspect it's due to problems on my end...

Would you mind elaborating on the other error you get sometimes, and under what conditions you get the other error message?

**Comment by kapacuk** [comment]
> Would you mind elaborating on the other error you get sometimes, and under what conditions you get the other error message?

I've just checked, I still get the `munmap_chunk(): invalid pointer` error with gcc-12 and gcc-13, but with gcc-10 the error is different:

```
$ python -c "import pandas; import spam"
double free or corruption (out)
Aborted
$

```

Please let me know if you still have problems reproducing it, I can build a Docker container for you.

**Comment by rhshadrach** [comment]
Cannot reproduce with Python 3.12. @kapacuk - are you having issues with Python >= 3.11?

**Comment by kapacuk** [comment]
> Cannot reproduce with Python 3.12. @kapacuk - are you having issues with Python >= 3.11?

I can't reproduce it myself any more. I tried various combinations of Python 3.10, 3.11, 3.12 and gcc 11, 12 and 13 - it works as expected now. It looks like this bug has been fixed already.
