### ISSUE TITLE
WARN read_table with infer_datetime_format doesn't show FutureWarning

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#51017]
Running
```python
import pandas as pd
import io

timestamp_format = '%Y-%d-%m %H:%M:%S'
date_index = pd.date_range(start='1900', end='2000')
dates_df = date_index.strftime(timestamp_format).to_frame(name='ts_col')
data = dates_df.to_csv()
df = pd.read_csv(
    io.StringIO(data),
    date_parser=lambda x: pd.to_datetime(x, format=timestamp_format),
    parse_dates=['ts_col'],
    infer_datetime_format=True,
    sep=',',
)
```
results in
```python
t.py:34: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df = pd.read_csv(
```

However,
```python
df = pd.read_table(
    io.StringIO(data),
    date_parser=lambda x: pd.to_datetime(x, format=timestamp_format),
    parse_dates=['ts_col'],
    infer_datetime_format=True,
    sep=',',
)
```
shows no warning

Task is just to add a warning to this function

https://github.com/pandas-dev/pandas/blob/1951b5117b22174abbc944b2e6efc41fe34f0a63/pandas/io/parsers/readers.py#L1151-L1209

similarly to how is already done here:

https://github.com/pandas-dev/pandas/blob/1951b5117b22174abbc944b2e6efc41fe34f0a63/pandas/io/parsers/readers.py#L887-L895

Finally, you'll need to add a test: you can duplicate

https://github.com/pandas-dev/pandas/blob/9991d5eb99d93a9d03368490379447ea6156a4c9/pandas/tests/io/parser/test_parse_dates.py#L1293-L1303

but for `read_table` (or parametrise over `parser.read_csv_check_warnings` and `parser.read_table_check_warnings`). Note that you'll need to add `sep=','`

**Comment by MarcoGorelli** [comment]
To parametrise, you  might want to use
```
@pytest.mark.parametrize( 'reader', [ 'read_csv_check_warnings', 'read_table_check_warnings' ])
```
and then use `getattr(parser, reader)` instead of `parser.read_csv_check_warnings`

**Comment by MarcoGorelli** [comment]
Also, this should be a `FutureWarning`

**Comment by kathleenhang** [comment]
take

**Comment by kathleenhang** [comment]
Running your first code snippet which should have produced a FutureWarning, I did not receive any warning. 

I tried figuring out how to enable warnings in pandas by running pd.reset_option('all'). 

This resulted in the appearance of other FutureWarnings but still, it didn't produce the same FutureWarning like the one you received: "FutureWarning: The argument 'date_parser' is deprecated..."

I'm using pandas v1.5.3. Do you know why this is the case?

For now, I'll work on adding in the warning for the second code snippet and seeing if that one appears properly.

**Comment by MarcoGorelli** [comment]
hey @kathleenhang , 

sorry, my bad, I was running that from a branch. updating now, sorry for the confusion, thanks for having asked

**Comment by kathleenhang** [comment]
@MarcoGorelli Hey there, I still don't receive any warning. I'm using Python 3.9.1 if that helps.

**Comment by MarcoGorelli** [comment]
Does it work if you run
```
pytest pandas/tests/io/parser/test_parse_dates.py -k test_parse_dates_infer_datetime_format_warning
```
?

**Comment by kathleenhang** [comment]
I ran it twice in two different folders. Here are the results:

<img width="1185" alt="Screen Shot 2023-01-27 at 1 10 56 PM" src="https://user-images.githubusercontent.com/2395780/215201004-5b1db1b1-6133-4138-a4b7-5feea9607550.png">
<img width="1109" alt="Screen Shot 2023-01-27 at 1 11 30 PM" src="https://user-images.githubusercontent.com/2395780/215201003-a9a3fd0b-c238-46de-99fa-978884fc18a8.png">

pandas-kathleenhang is my forked pandas repo
pandas-dev just contains a file called t.py

**Comment by MarcoGorelli** [comment]
looks like you need to rebuild the C extensions: https://pandas.pydata.org/docs/dev/development/contributing_environment.html#step-3-build-and-install-pandas

**Comment by kathleenhang** [comment]
I also was not inside of my Docker virtual environment. I just set that up yesterday, and I am still understanding how it works, its purpose, and when I should have it activated. 

I had built my C extensions inside of the Docker virtual environment, but since I was working outside of the virtual environment, it didn't have the updated C extensions.

I see the warning now. Thanks @MarcoGorelli !

**Comment by kathleenhang** [comment]
Since I have parametrised and am now using `getattr(parser, reader)` instead of `parser.read_csv_check_warnings`, how would I go about changing the warning type for `read_table()` from UserWarning to FutureWarning?

Would I have to edit the implementation within this function:

`def read_table_check_warnings(
        self, warn_type: type[Warning], warn_msg: str, *args, **kwargs
    ):`

From conftest.py?
