### ISSUE TITLE
BUG: >M8[ns] series from >M8[ns] numpy array fails on little endian system and vice versa

### ISSUE THREAD

**Issue by hroncok** [pandas-dev/pandas#51041]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import numpy, pandas
# on little endian system (e.g. x86_64):
pandas.Series(numpy.array([], dtype=numpy.dtype('>M8[ns]')), dtype=numpy.dtype('>M8[ns]'))
# on big endian system (e.g. s390x):
pandas.Series(numpy.array([], dtype=numpy.dtype('<M8[ns]')), dtype=numpy.dtype('<M8[ns]'))
```

### Issue Description

In Fedora Linux, we have started to observe hypothesis test failures on the s390x (big endian) architecture.

The failures looked like this:

```
=================================== FAILURES ===================================
___________________ test_data_frames_with_timestamp_columns ____________________
[gw1] linux -- Python 3.11.1 /usr/bin/python3
Traceback (most recent call last):
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.56.3/hypothesis-python/tests/pandas/test_data_frame.py", line 141, in test_data_frames_with_timestamp_columns
    def test_data_frames_with_timestamp_columns(df):
                   ^^^
  File "/builddir/build/BUILDROOT/python-hypothesis-6.56.3-1.fc38.noarch/usr/lib/python3.11/site-packages/hypothesis/core.py", line 1267, in wrapped_test
    raise the_error_hypothesis_found
  File "/usr/lib64/python3.11/site-packages/pandas/core/series.py", line 470, in __init__
    data = sanitize_array(data, index, dtype, copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/construction.py", line 597, in sanitize_array
    subarr = _try_cast(data, dtype, copy, raise_cast_failure)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/construction.py", line 827, in _try_cast
    return maybe_cast_to_datetime(arr, dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/dtypes/cast.py", line 1331, in maybe_cast_to_datetime
    dta = sequence_to_datetimes(value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/arrays/datetimes.py", line 1969, in sequence_to_datetimes
    result, tz, freq = _sequence_to_dt64ns(
                       ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/arrays/datetimes.py", line 2104, in _sequence_to_dt64ns
    assert data.dtype == DT64NS_DTYPE, data.dtype
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: <M8[ns]
```

Similar failures used to happen in the past so I re-reported that to https://github.com/HypothesisWorks/hypothesis/issues/2894

I have been trying to see what is going on and isolated the issue to:

#### Big endian system (s390x)

```pycon
>>> import numpy, pandas
>>> pandas.Series(numpy.array([], dtype=numpy.dtype('<M8[ns]')), dtype=numpy.dtype('<M8[ns]'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.11/site-packages/pandas/core/series.py", line 474, in __init__
    data = sanitize_array(data, index, dtype, copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/construction.py", line 597, in sanitize_array
    subarr = _try_cast(data, dtype, copy, raise_cast_failure)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/construction.py", line 827, in _try_cast
    return maybe_cast_to_datetime(arr, dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/dtypes/cast.py", line 1331, in maybe_cast_to_datetime
    dta = sequence_to_datetimes(value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/arrays/datetimes.py", line 1969, in sequence_to_datetimes
    result, tz, freq = _sequence_to_dt64ns(
                       ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/arrays/datetimes.py", line 2104, in _sequence_to_dt64ns
    assert data.dtype == DT64NS_DTYPE, data.dtype
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: <M8[ns]
```

#### Little endian system (x86_64)

```pycon
>>> import numpy, pandas
>>> pandas.Series(numpy.array([], dtype=numpy.dtype('>M8[ns]')), dtype=numpy.dtype('>M8[ns]'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.11/site-packages/pandas/core/series.py", line 470, in __init__
    data = sanitize_array(data, index, dtype, copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/construction.py", line 597, in sanitize_array
    subarr = _try_cast(data, dtype, copy, raise_cast_failure)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/construction.py", line 827, in _try_cast
    return maybe_cast_to_datetime(arr, dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/dtypes/cast.py", line 1331, in maybe_cast_to_datetime
    dta = sequence_to_datetimes(value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/arrays/datetimes.py", line 1969, in sequence_to_datetimes
    result, tz, freq = _sequence_to_dt64ns(
                       ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/arrays/datetimes.py", line 2104, in _sequence_to_dt64ns
    assert data.dtype == DT64NS_DTYPE, data.dtype
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: >M8[ns]
```

### Expected Behavior

With pandas 1.4.4 or 1.3.5:

```pycon
>>> import numpy, pandas
>>> pandas.Series(numpy.array([], dtype=numpy.dtype('>M8[ns]')), dtype=numpy.dtype('>M8[ns]'))
Series([], dtype: datetime64[ns])
>>> pandas.Series(numpy.array([], dtype=numpy.dtype('<M8[ns]')), dtype=numpy.dtype('<M8[ns]'))
Series([], dtype: datetime64[ns])
```

Looks like the endianness of the dtype used to be forced:

#### Big endian system (s390x)

```pycon
>>> pandas.Series(numpy.array([], dtype=numpy.dtype('<M8[ns]')), dtype=numpy.dtype('<M8[ns]')).dtype
dtype('>M8[ns]')
>>> pandas.Series(numpy.array([], dtype=numpy.dtype('>M8[ns]')), dtype=numpy.dtype('>M8[ns]')).dtype
dtype('>M8[ns]')
```

#### Little endian system (x86_64)

```pycon
>>> pandas.Series(numpy.array([], dtype=numpy.dtype('<M8[ns]')), dtype=numpy.dtype('<M8[ns]')).dtype
dtype('<M8[ns]')
>>> pandas.Series(numpy.array([], dtype=numpy.dtype('>M8[ns]')), dtype=numpy.dtype('>M8[ns]')).dtype
dtype('<M8[ns]')
```

### Installed Versions

<details>

INSTALLED VERSIONS (from a virtual environment where I can reproduce this on x86_64)
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.11.1.final.0
python-bits      : 64
OS               : Linux
OS-release       : 6.0.15-300.fc37.x86_64
Version          : #1 SMP PREEMPT_DYNAMIC Wed Dec 21 18:33:23 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : cs_CZ.utf8
LOCALE           : cs_CZ.UTF-8

pandas           : 1.5.3
numpy            : 1.24.1
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 62.6.0
pip              : 22.2.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

INSTALLED VERSIONS (from a s390x Fedora container)
------------------
commit           : 8dab54d6573f7186ff0c3b6364d5e4dd635ff3e7
python           : 3.11.1.final.0
python-bits      : 64
OS               : Linux
OS-release       : 6.0.5-200.fc36.s390x
Version          : #1 SMP Wed Oct 26 15:37:49 UTC 2022
machine          : s390x
processor        : 
byteorder        : big
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.2
numpy            : 1.23.5
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : None
pip              : None
Cython           : None
pytest           : None
hypothesis       : 6.62.1
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.8.0
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.2
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : 2.8.4
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by hroncok** [comment]
(Note that the `assert data.dtype == DT64NS_DTYPE, data.dtype` line is gone form that file in the main branch once again.)

**Comment by Zac-HD** [comment]
Proximate cause of confusion: https://github.com/numpy/numpy/issues/19059 also seems to apply to Pandas 😥

**Comment by mroeschke** [comment]
It seems like the upstream issue has been fixed by https://github.com/numpy/numpy/pull/23295 so I suspect this is no longer an issue in pandas (we don't test endianness in our CI so it's difficult to confirm). Closing but happy to have a new issue if there are still issues
