### ISSUE TITLE
BUG: Cannot connect to sql

### ISSUE THREAD

**Issue by Edimo05** [pandas-dev/pandas#51086]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import dask.dataframe as dd

engine = create_engine("mssql+pyodbc://{user}:{pw}@{sv}:1433/{db}?driver=ODBC+DRIVER+17+for+SQL+Server"
                       .format(user="sa",
                               pw="sa",
                               db="table",
                               sv='server.com'), pool_pre_ping=True)

# Get the list of CSV files in the folder
csv_files = [f for f in os.listdir(dir_folder) if f.endswith('.csv')]

# Loop through the CSV files in the folder
for file in csv_files:
    # Read the CSV file into a Dask DataFrame
    df = dd.read_csv(f'{dir_folder}/{file}', usecols = cols, dtype = converters)

	# Fill empty rows with 0
    df = df.fillna(0)

    # Rename the columns
    df = df.rename(columns = new_column_names)

    # Write the DataFrame to the SQL table
    df.to_sql(table, engine, if_exists='append', index=False)
```

### Issue Description

Issue related to connection, but as far as I know, I need t create the connection and send it through to_sql.

![image](https://user-images.githubusercontent.com/94873872/215818287-bfc45782-819d-4e72-9bf7-d22cb3926f0f.png)

### Expected Behavior

It supposed to connect the database and load the dataframe

### Installed Versions

<details>
python           : 3.10.4.final.0
pandas           : 1.4.2
</details>

**Comment by phofl** [comment]
Can you post in #40686?

**Comment by jbrockmendel** [comment]
isnt this a dask issue?

**Comment by leo-schick** [comment]
@jbrockmendel no, it is a issue with pandas not supporting SQLAlchemy>=2.0 yet

**Comment by phofl** [comment]
Dask only supports strings as uri, no engines. So this works as expected

**Comment by jlonge4** [comment]
@phofl thanks! I dug through and couldn't think of a single reason why not so that works 😂
