### ISSUE TITLE
DOC: GroupBy.rolling() not in docs

### ISSUE THREAD

**Issue by davidgilbertson** [pandas-dev/pandas#51097]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/groupby.html
https://pandas.pydata.org/docs/dev/reference/groupby.html

### Documentation problem

In the source code for `GroupBy` I see [rolling](https://github.com/pandas-dev/pandas/blob/main/pandas/core/groupby/groupby.py#L2781) and `ewm` and `expanding` but I don't see these in the docs.

I can't work out if they've been deprecated, or are very new, or if there's a bug in the documentation creation.

### Suggested fix for documentation

Depending on why they're not in the docs, either an update to the docstring to mention that these aren't part of the official API (and why, and what to use instead maybe, or maybe a deprecation warning) or update the docs to include them.

**Comment by rhshadrach** [comment]
Thanks for the report - agreed this should be in the API docs. They are mentioned in the User Guide here:

https://pandas.pydata.org/pandas-docs/dev/user_guide/groupby.html#window-and-resample-operations

For adding to the API docs, a few lines in doc/source/reference/groupby.rst would get them to appear, but I also think their docstrings should be improved if we are to add them.
