### ISSUE TITLE
DEPR: float/int(Series[single_element])?

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#51101]
```
In [1]: float(pd.Series([1]))
Out[1]: 1.0

In [2]: int(pd.Series([1]))
Out[2]: 1
```

Raises a `TypeError` if there's more than one element, but not sure the exact use case for the single element case. `int(ser.iloc[0])` should probably be preferred.

**Comment by jbrockmendel** [comment]
+1

**Comment by rhshadrach** [comment]
+1; tangentially related - I've wondered what `Series.bool` and `DataFrame.bool` were for. They have similar logic (raise if there is more than one element).
