### ISSUE TITLE
BUG: `df.to_csv("s3://bucket/location/file.csv")` requires broader permissions to execute than required

### ISSUE THREAD

**Issue by cotman** [pandas-dev/pandas#51121]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame(
    data={
        "col1": [1, 2],
        "col2": [3, 4]
    }
) 


df.to_csv(
    "s3://my_bucket/location/with/access/test_file.csv", 
    header=False, 
    index=False,
    storage_options={
        "key": "<REDACTED>",
        "secret": "<REDACTED>"
    }
)
```

### Issue Description

When using `to_csv()` to upload directly to S3, there's a `botocore exception `as an attempt is made to *create* the destination bucket: 

    botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied

The user's credentials are correct in the call, but their permissions are deliberately restricted to get/put/list permissions on **just** files under the `location/with/access/` prefix, not on the entire bucket.

Here's what the IAM policy looks like for that user:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::my_bucket",
            "Condition": {
                "StringLike": {
                    "s3:prefix": [
                        "location/with/access",
                        "location/with/access/",
                        "location/with/access/*"
                    ]
                }
            }
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:PutObject"
            ],
            "Resource": "arn:aws:s3:::my_bucket/location/with/access/*"
        }
    ]
}
```

I'm guessing that an existence/access check is happening, somewhere, by using `create_bucket` and checking the exception thrown?  In this case it will be "Access denied" (which is correct) but the bucket does exist and the location is accessible to the caller.

### Expected Behavior

`to_csv()` should support uploading to any location within an S3 bucket if the user has access to that location (even if they don't have wider permissions elsewhere in the bucket).

### Installed Versions

```
INSTALLED VERSIONS
------------------
commit           : 10c51ba02014d4caefa8dc2d2ed2874759693b14
python           : 3.10.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.0-58-generic
Version          : #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 2.0.0.dev0+1387.g10c51ba020
numpy            : 1.24.1
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 65.6.3
pip              : 22.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2023.1.0
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : 2023.1.0
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : None
qtpy             : None
pyqt5            : None
None```

**Comment by twoertwein** [comment]
Pandas uses fsspec for s3:
https://github.com/pandas-dev/pandas/blob/9277f93d37f207fe50d8318686fc59f637922fdd/pandas/io/common.py#L414

Do you have the same issue when using fsspec directly?

**Comment by cotman** [comment]
> Pandas uses fsspec for s3:
> 
> https://github.com/pandas-dev/pandas/blob/9277f93d37f207fe50d8318686fc59f637922fdd/pandas/io/common.py#L414
> 
> Do you have the same issue when using fsspec directly?

Ahhh, OK, thanks, didn't realise that.

So - it looks like this issue is actually with fsspec's use of s3fs.
There's an existing issue with s3fs here: https://github.com/fsspec/s3fs/issues/532 .

**Comment by cotman** [comment]
So, digging into this s3fs side, there's a workaround that I'll put here in case it's useful to anyone finding this.
If you use prefix-based permissions, then you can avoid the `CreateBucket` attempt by granting `GetBucketLocation` in your IAM policy.

So - the required minimal IAM policy becomes this sort of thing: 

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::my_bucket",
            "Condition": {
                "StringLike": {
                    "s3:prefix": [
                        "location/with/access",
                        "location/with/access/",
                        "location/with/access/*"
                    ]
                }
            }
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:PutObject"
            ],
            "Resource": "arn:aws:s3:::my_bucket/location/with/access/*"
        },
        {
            "Effect": "Allow",
            "Action": "s3:GetBucketLocation",
            "Resource": "arn:aws:s3:::my_bucket"
        }
    ]
}

**Comment by artc95** [comment]
had the same issue calling `df.to_csv` from AppRunner to S3, 
adding `s3:GetBucketLocation` permission to AppRunner Instance's IAM policy worked:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": "arn:aws:s3:::<bucket_name>/*"
        },
        {
            "Effect": "Allow",
            "Action": "s3:GetBucketLocation",
            "Resource": "arn:aws:s3:::<bucket_name>"
        }
    ]
}
```
thanks alot @cotman :)
