### ISSUE TITLE
REF/API: make pd.Grouper immutable

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#51134]
Grouper._set_grouper (called by Grouper._get_grouper) sets some of its own attributes.  It would be much easier to reason about this code if this were not the case.  An afternoon spent trying to disentangle this has not gotten me very far.  This may need a more invasive fix.

**Comment by topper-123** [comment]
+1.

**Comment by jbrockmendel** [comment]
xref #26564, #41930
