### ISSUE TITLE
ENH: Support file:// as fsspec URL

### ISSUE THREAD

**Issue by KeerthiYandaOS** [pandas-dev/pandas#51150]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Fsspec identifies as [file:// as protocol and uses LocalFileSystem](https://github.com/fsspec/filesystem_spec/blob/master/fsspec/registry.py#L57) as an entry point. But the Pandas is not supporting file:// as a fsspec protocol and utilizing the Python `open_local_file` API to read the file. Can we support `file://` as a fsspec URI so that the request reaches the fsspec driver to read the files from the local file system?

### Feature Description

We can exclude the 'file' from Valid_URL [here](https://github.com/pandas-dev/pandas/blob/main/pandas/io/common.py#L76) or we can add a parameter to read_xxx to consider the protocol as local or fsspec protocol.

### Alternative Solutions

As described above we can add a parameter to read/write API to acknowledge the protocol that needs to trigger like python or the fsspec APIs.

**Comment by twoertwein** [comment]
Using `pd.read_csv("file://absolute_path_to_the_file")` already works but (at least on linux) it is important that the absolute path still starts with an `/` (three in a row, not only two).

**Comment by topper-123** [comment]
You don't show any benefit to using fsspec, are there situations where that would improve pandas?

I'm not warm to add a fsspec parameter just for local file access, it seems inconsistent.

**Comment by mroeschke** [comment]
I think this just needs correct user input instead of pandas detecting this edge case so going to close
