### ISSUE TITLE
ENH: Access attributes of a dataframe in a case insensitive manner directly.

### ISSUE THREAD

**Issue by atharvabhide** [pandas-dev/pandas#51165]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish I could directly access pandas attribute names in a case insensitive manner directly without checking the casing of the attributes. Yes there exist some methods to do this indirectly but it would be great if pandas could do it implicitly.

### Feature Description

I don't exactly know in which part of the codebase this feature should be added but we could add some code which will convert the attribute name which the user is accessing and the original dataframe attribute and bring them to a similar case implicitly so that we don't get casing errors.

### Alternative Solutions

There exist few alternative solutions to this problem but they are indirect.
For example-
1) `df.columns = df.columns.str.lower()`
In this code we convert the dataframe columns to lower case.
2) `df.columns = df.columns.str.upper()`
Or in this example we convert the dataframe columns to upper case.
But all this is done explicitly, and what I am suggesting is a way to do it implicitly which will enhance accessing the attributes.

**Comment by MarcoGorelli** [comment]
thanks for the suggestion - `df.columns = df.columns.str.lower()` is indeed the way to do this, no need for pandas to do it implicitly

closing then, but thanks for the suggestion
