### ISSUE TITLE
pandas (8deae52ff6) test error on FreeBSD

### ISSUE THREAD

**Issue by hasandiwan** [pandas-dev/pandas#51179]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

FreeBSD-13.1-RELEASE-p3-amd64-64bit-ELF

### Installation Method

pip install

### pandas Version

8deae52ff6

### Python Version

3.9.16

### Installation Logs

I had to pip install versioneer and add a symlink from /usr/local/lib/libblis.so.4.0.0 to /usr/local/lib/libblis.so.3. 

To run the tests, I further installed hypothesis and asyncio, but still encountered "ERROR: Unknown config option: asyncio_mode". The tests then fail with "ERROR: Unknown config option: asyncio_mode".

**Comment by MarcoGorelli** [comment]
Thanks for the report - you need pytest-asyncio, please check the contributing guide

Closing for now then
