### ISSUE TITLE
BUG: apply() method throwing SettingWithCopyError on trying to perform in-place operation for a column

### ISSUE THREAD

**Issue by anupampatil44** [pandas-dev/pandas#51194]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df=pd.read_csv('abc.csv')

# using apply to perform some operation on a column:
df['columnname']=df.columnname.apply(lambda x: str(x).replace("original_value","new_value"))
```

### Issue Description

The Apply operation can't be performed on a column itself.
Provides the following error:
SettingWithCopyError: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

### Expected Behavior

Should allow me to explicitly perform the operation on the column itself and modify the dataframe.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.147+
Version          : #1 SMP Sat Dec 10 16:00:40 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.21.6
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 57.4.0
pip              : 22.0.4
Cython           : 0.29.33
pytest           : 3.6.4
hypothesis       : None
sphinx           : 3.5.4
blosc            : None
feather          : 0.4.1
xlsxwriter       : None
lxml.etree       : 4.9.2
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.9.5
jinja2           : 2.11.3
IPython          : 7.9.0
pandas_datareader: 0.9.0
bs4              : 4.6.3
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2023.1.0
gcsfs            : None
matplotlib       : 3.2.2
numba            : 0.56.4
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : 0.17.9
pyarrow          : 9.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
snappy           : None
sqlalchemy       : 2.0.0
tables           : 3.7.0
tabulate         : 0.8.10
xarray           : 2022.12.0
xlrd             : 1.2.0
xlwt             : 1.3.0
zstandard        : None
tzdata           : None

</details>

**Comment by phofl** [comment]
Hi, thanks for your report.

Please provide a reproducible example that is copy-paste able.

**Comment by phofl** [comment]
Closing for now, please ping to reopen when you can provide an example
