### ISSUE TITLE
DOC fix EX02 errors in docstrings

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#51236]
pandas has a script for validating docstrings

https://github.com/pandas-dev/pandas/blob/ced983358b06576af1a73c3e936171cc6dc98a6d/ci/code_checks.sh#L560-L568

which can be run with
```
./ci/code_checks.sh docstrings
```

Currently, many functions fail the EX02 check, and so are excluded from the check.

The task here is:
1. pick 2-3 functions
2. run `./ci/code_checks.sh docstrings`
3. fixup the docstrings according to whatever error is reported
4. stage, commit, push, open pull request 🚀 

**Please don't comment `take` as multiple people can work on this simultaneously**. You also don't need to ask for permission to work on this, feel free to just start 😄  Though if you're working on some set of functions you can comment that

If you're new here, please check the contributing guide https://pandas.pydata.org/docs/dev/development/contributing.html

TIP: `./ci/code_checks.sh docstrings` may take a while to run - you may want to comment-out the `docstrings` check which checks `EX01` and the part which checks all the other codes (these are currently lines 86 - 577)

**Comment by albuzenet** [comment]
take

**Comment by albuzenet** [comment]
Hi, currently working on :

`pandas.factorize`
`pandas.Index.factorize`
`pandas.Series.factorize`

**Comment by albuzenet** [comment]
For future Windows contributors. If you get a weird flake8 PermissionError when running scripts/validate_docstrings.py you can fix it by manually adding delete=False in the tempfile context manager (validate_docstrings.py, line 210). Note that you will need to manually delete the temporary file after this change. Also, do not push this change ! Related issue: [stackoverflow](https://stackoverflow.com/a/54768241/17386911)

**Comment by albuzenet** [comment]
Sure @MarcoGorelli. Should I open a new issue ?

**Comment by MarcoGorelli** [comment]
sure (or feel free to just submit a PR directly, thanks for having spotted this)

**Comment by DeaMariaLeon** [comment]
Working on:
pandas.api.types.is_bool_dtype
pandas.api.types.is_categorical_dtype
pandas.api.types.is_complex_dtype

**Comment by Ramyahkay** [comment]
Hello, I am currently working on:
`pandas.api.types.is_integer_dtype`
`pandas.api.types.is_string_dtype`

**Comment by natmokval** [comment]
Hi, I will work on:
`pandas.api.types.is_float_dtype`
`pandas.api.types.is_int64_dtype`

**Comment by natmokval** [comment]
I am working on:
`pandas.api.types.is_object_dtype`
`pandas.api.types.is_numeric_dtype`
`pandas.api.types.is_datetime64_dtype`

**Comment by natmokval** [comment]
I am working on:
`pandas.Period.strftime \`
`pandas.Series.floordiv \`
`pandas.Series.rfloordiv \`

**Comment by clewarne14** [comment]
Hi, I am currently working on:

pandas.api.types.is_interval_dtype
pandas.api.types.is_period_dtype
pandas.api.types.is_signed_integer_dtype

**Comment by natmokval** [comment]
I am working on:
`pandas.core.groupby.DataFrameGroupBy.take \`
`pandas.Timestamp.fromtimestamp \`

**Comment by jaideepmurkute** [comment]
Hi, I will take up the following set: 

```
pandas.io.formats.style.Styler.concat
pandas.io.formats.style.Styler.export
pandas.io.formats.style.Styler.set_td_classes 
pandas.io.formats.style.Styler.use
```

**Comment by phershbe** [comment]
I am working on:
`pandas.plotting.andrews_curves \ `
`pandas.plotting.autocorrelation_plot \ `
`pandas.plotting.lag_plot \ `

**Comment by natmokval** [comment]
I am working on:
`pandas.Series.sparse.density`
`pandas.Series.sparse.npoints`
`pandas.Series.sparse.sp_values`

**Comment by kindai321** [comment]
Hi, I am working on:
`pandas.api.types.is_datetime64_any_dtype` 
`pandas.api.types.is_datetime64_ns_dtype`  
`pandas.api.types.is_datetime64tz_dtype` 
This is going to be my first open source contribution and I might need some help :)

**Comment by natmokval** [comment]
I am working on:
`pandas.core.groupby.SeriesGroupBy.take`
`pandas.merge_ordered`
`pandas.option_context`

**Comment by natmokval** [comment]
I will work on:
`pandas.io.json.build_table_schema`
`pandas.api.types.is_timedelta64_dtype`
`pandas.api.types.is_timedelta64_ns_dtype`

**Comment by jaideepmurkute** [comment]
Hi, 
I won't be able to complete the following set that I had taken up earlier due to bandwidth issues: 
```
pandas.io.formats.style.Styler.concat
pandas.io.formats.style.Styler.export  
pandas.io.formats.style.Styler.set_td_classes
pandas.io.formats.style.Styler.use
```
Others can pick it up. Apologies for blocking the set.

**Comment by harshvardhan2707** [comment]
take

**Comment by natmokval** [comment]
Hi. I'll take functions
`pandas.io.formats.style.Styler.concat`
`pandas.io.formats.style.Styler.export`  
`pandas.io.formats.style.Styler.set_td_classes`
`pandas.io.formats.style.Styler.use`

**Comment by clewarne14** [comment]
Hello,
I won't be able to complete the following set that I had taken up earlier due to issues with my computer:

pandas.api.types.is_interval_dtype
pandas.api.types.is_period_dtype
pandas.api.types.is_signed_integer_dtype

Others can pick it up. Apologies for blocking the set. I will close my incomplete pull request for this issue.

**Comment by phershbe** [comment]
Hello,
I'll take the three methods from above:
`pandas.api.types.is_interval_dtype`
`pandas.api.types.is_period_dtype`
`pandas.api.types.is_signed_integer_dtype`
I also have three methods about `plotting` that I'm working on and have mentioned in another comment above, sorry for being greedy but I want to do these above because I spent some days on this with problems with the development environment ... https://github.com/pandas-dev/pandas/issues/48060 = not creating my fork properly ... and then trying to figure out what is going on with the `plotting` docstrings, and I didn't realize that a lot of the other methods were easier. I have the three methods from above done, all I need to do is send in the pull request, which I'll do later this evening when I have more free time.
If anybody wants to work with me on the plotting methods that I took before...
`pandas.plotting.andrews_curves`
`pandas.plotting.autocorrelation_plot`
`pandas.plotting.lag_plot`
...let me know, that could be interesting too.
 Thank you.

**Comment by phershbe** [comment]
The pull request above corrects the docstrings for:
`pandas.api.types.is_interval_dtype`
`pandas.api.types.is_period_dtype`
`pandas.api.types.is_signed_integer_dtype`

Sorry for not mentioning that I would take them in advance, they were dropped by somebody else a few hours ago and I did them to gain some confidence since I'm working on a few for `plotting` that are more difficult and wanted to use these for experience.

**Comment by natmokval** [comment]
I am working on:
`pandas.api.types.infer_dtype`
`pandas.api.types.is_sparse`
`pandas.api.types.is_unsigned_integer_dtype`

**Comment by lia2710** [comment]
Hi, I am working on:
`pandas.plotting.radviz`
`pandas.tseries.frequencies.to_offset`

**Comment by liang3zy22** [comment]
Hi, I am already working on:
```
 pandas.api.types.is_integer_dtype
 pandas.api.types.is_string_dtype
```
PR is as above.

**Comment by MarcoGorelli** [comment]
> Hi, I am already working on:
> 
> ```
>  pandas.api.types.is_integer_dtype
>  pandas.api.types.is_string_dtype
> ```
> 
> PR is as above. UPDATE: Just saw @Ramyahkay already took them. Should I delete my PR and wait for @Ramyahkay 's?

Thanks - what you've done is fine, if someone leaves a comment and then doesn't submit anything for 1-2 weeks it's perfectly fine to take over

**Comment by zgdjcls** [comment]
Hi I'm going to work on:
`pandas.plotting.parallel_coordinates
pandas.DataFrame.plot.line`

**Comment by Ramyahkay** [comment]
Hello everyone, I am going to work on the following:
`pandas.Series.sparse.density \ `
`pandas.Series.sparse.npoints \ `
`pandas.Series.sparse.sp_values \` 
This is my first time contributing to open source and I'm looking forward to learning and contributing to the community. I'll do my best to keep the issue up-to-date with my progress and communicate any questions I have.

**Comment by MarcoGorelli** [comment]
those are already done

there's only 6 left, we're close to closing this one off

**Comment by zgdjcls** [comment]
Sorry, due to some reason, I won't be able to fix 
pandas.plotting.parallel_coordinates
pandas.DataFrame.plot.line
anymore, so if anyone else wants to do this you can work on it.

**Comment by phershbe** [comment]
I'll take the methods mentioned directly above:
`pandas.plotting.parallel_coordinates`
`pandas.DataFrame.plot.line`

**Comment by MarcoGorelli** [comment]
cool, thanks

or feel free to take all the remaining ones, remove the partial EX02 check, and add EX02 to

https://github.com/pandas-dev/pandas/blob/ced983358b06576af1a73c3e936171cc6dc98a6d/ci/code_checks.sh#L82-L83

**Comment by phershbe** [comment]
Great, I'm working on them now!

**Comment by MarcoGorelli** [comment]
We did, thanks everyone!
