### ISSUE TITLE
BUG: Partial multiindex columns selection breaks categorical dtypes

### ISSUE THREAD

**Issue by epizut** [pandas-dev/pandas#51261]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame([('value')], columns=pd.Index([('A', 'B')], names=['lvl1', 'lvl2'])).astype('category')

# Broken object dtypes: 
df['A'].dtypes
# lvl2
# B    object

# Please note that an explicit full level selection works as expected:
df[[('A', 'B')]].dtypes
# lvl1  lvl2
# A     B       category
```

### Issue Description

When partially selecting the first level from a multiindex columns `catagorical` dataframe, dtpyes are upcasted to `object`.

### Expected Behavior

```python
# Expected categorical dtypes:
df['A'].dtypes
# lvl2
# B    category
```

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.9.12.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.5.3
numpy            : 1.23.5
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 65.3.0
pip              : 22.2.2
Cython           : 0.29.30
pytest           : 7.1.1
hypothesis       : None
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.0
html5lib         : None
pymysql          : None
psycopg2         : 2.9.3
jinja2           : 3.1.1
IPython          : 8.2.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2022.3.0
gcsfs            : None
matplotlib       : 3.5.1
numba            : 0.56.4
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 7.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.1
snappy           : None
sqlalchemy       : 1.4.41
tables           : None
tabulate         : 0.8.9
xarray           : 2022.3.0
xlrd             : 2.0.1
xlwt             : None
zstandard        : None
tzdata           : None
</details>

**Comment by m-richards** [comment]
Over in geopandas (https://github.com/geopandas/geopandas/pull/2088, https://github.com/geopandas/geopandas/issues/1763) we're seeing what I think is essentially the same issue, partial column selections do not preserve dtypes. Here's an analogue from that context where I've replace the geopandas dependency with a nullable float dtype:

```python
In [5]: df = pd.DataFrame(
   ...:             [[1, 0], [0, 1]],
   ...:             columns=[
   ...:                 ["foo", "foo"],
   ...:                 ["location", "location"],
   ...:                 ["x", "y"],
   ...:             ],
   ...:         )

In [6]: df['floats'] = pd.Series([1.1, 1.2], dtype='Float64')

In [7]: df.dtypes
Out[7]:
foo     location  x      int64
                  y      int64
floats                 Float64
dtype: object

In [8]: df['floats']
Out[8]:
0    1.1
1    1.2
Name: floats, dtype: object
# would expect this to be object dtype
```

**Comment by MarcoGorelli** [comment]
moving off the 2.0 milestone
