### ISSUE TITLE
API: Difference between GroupBy, DataframeGroupBy, and SeriesGroupBy

### ISSUE THREAD

**Issue by pyrito** [pandas-dev/pandas#51270]
Hi all

I couldn't find a good answer to this on StackOverflow, but I was trying to understand what the conceptual difference were between GroupBy, DataFrameGroupby, and SeriesGroupBy were given that they are mentioned separately in the pandas documentation. I looked through the source code and it looks like `GroupBy` has an overlap of methods that can be used for both Dataframes and Series objects? However, it seems like most SeriesGroupBy methods are only for Series objects. Likewise, `DataframeGroupBy` methods are only for Dataframe objects. There seems to be some overlap with `GroupBy` and `DataframeGroupBy` methods, but not with `SeriesGroupBy`, which is why I'm a little confused.

Thanks!

**Comment by jbrockmendel** [comment]
GroupBy is the parent class for SeriesGroupBy and DataFrameGroupBy.  Series.groupby(...) returns a SeriesGroupBy object. DataFrame.groupby(...) returns a DataFrameGroupBy object.  I don't think there's any way to get _just_ a GroupBy object.

Places in the docs that refer to GroupBy are probably using that as a shorthand for "SeriesGroupBy and/or DataFrameGroupBy".  Would welcome a PR to clarify that where relevant.

**Comment by jbrockmendel** [comment]
Yes

**Comment by rhshadrach** [comment]
> I was trying to understand what the conceptual difference were between GroupBy, DataFrameGroupby, and SeriesGroupBy were given that they are mentioned separately in the pandas documentation

Are you looking at the dev docs? This has been overhauled and will be updated in 2.0:

https://pandas.pydata.org/pandas-docs/dev/reference/groupby.html

**Comment by pyrito** [comment]
@rhshadrach this is awesome and a lot more clearer. I was looking at the pandas 1.5.3 docs.

**Comment by rhshadrach** [comment]
Sounds like this is resolved. Improvements to the docs are always welcome. If there is anything further you'd like to raise here, just comment and we can reopen.
