### ISSUE TITLE
BUG: pd.Series idxmax raises ValueError instead of returning <NA> when all values are <NA>

### ISSUE THREAD

**Issue by hchau630** [pandas-dev/pandas#51276]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

s = pd.Series([np.nan, np.nan]).convert_dtypes()
s.idxmax(skipna=True)
```

### Issue Description

According to documentation, when pd.Series contains all NaN values, calling idxmax with skipna=True should return NaN. However, in this case it raise "ValueError: attempt to get argmax of an empty sequence" instead. This issue only happens when I used convert_dtypes() on the Series before calling idxmax. Interestingly, the same issue does not appear for pd.DataFrame.

### Expected Behavior

Should return <NA> or NaN rather than raising ValueError.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.9.13.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.3.0
Version          : Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.23.4
pytz             : 2022.6
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 22.2.2
Cython           : None
pytest           : 7.2.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.2
numba            : None
numexpr          : 2.8.4
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.3
snappy           : None
sqlalchemy       : None
tables           : 3.7.0
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report! Confirmed on main; further investigations and PRs to fix are welcome.

**Comment by jbrockmendel** [comment]
Discussed in in last week's dev call, agreed that raising is the preferred eventual behavior, need a deprecation cycle to get consistent behavior across dtypes.
