### ISSUE TITLE
BUG: replace with inplace=True does not respect CoW

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#51277]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
df = DataFrame({"a": [1.5, 2, 3]})
arr_a = get_array(df, "a")
view = df[:]
df.replace(to_replace=[1.5], value=15.5, inplace=True)
print(arr_a)
```

Same with ``to_replace=1.5``

### Issue Description

arr_a should not get changed

the scalar case is addressed by #50918

### Expected Behavior

see above

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by phofl** [comment]
Should fix for 2.0

**Comment by lithomas1** [comment]
@phofl We should be checking everything else in group 2 of the PDEP as well right (adding tests if it works)?
(Still would need to check ``where``, ``fillna``(needs tests at the very least), ``mask``, ``clip``)

**Comment by phofl** [comment]
did not test clip (always forgetting about it), the other all respect cow, also have a pr for fillna

**Comment by lithomas1** [comment]
Opened a PR for the rest.
