### ISSUE TITLE
Instructions for checking typing of code cause pylint and autotyping to run

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#51313]
At https://pandas.pydata.org/docs/dev/development/contributing_codebase.html#validating-type-hints we tell people to validate the types of their code by doing:  `pre-commit run --hook-stage manual --all-files` .  The problem here is that this causes `autotyping` and `pylint` to run.

`pylint` takes a long time, so we should tell people to skip it.
Worse is that `autotyping` causes lots of files to change, so you end up with a bigger set of changed files.

I think we should modify the `.pre-commit-config.yaml` to define a `typing` stage that only runs `pyright` and `mypy`.

Even if we do that, I get a lot of typing errors on the code in `main` from both type checkers.  So that should be addressed as well.

**Comment by MarcoGorelli** [comment]
Hey

> Even if we do that, I get a lot of typing errors on the code in main from both type checkers. So that should be addressed as well.

CI is green - do you have the same version(s) of packages installed? I've sometimes had failures when I had, for example, a different numpy version

**Comment by twoertwein** [comment]
> I think we should modify the `.pre-commit-config.yaml` to define a `typing` stage that only runs `pyright` and `mypy`.

I think we can define only one manual stage (which started out to contain only mypy+pyright and then pylint+autotyping were moved there as well).

Could change the typing documentation to:

```
pre-commit run --hook-stage manual mypy
pre-commit run --hook-stage manual pyright
pre-commit run --hook-stage manual pyright_reportGeneralTypeIssues
```

**Comment by Dr-Irv** [comment]
> Could change the typing documentation to:
> 
> ```
> pre-commit run --hook-stage manual mypy
> pre-commit run --hook-stage manual pyright
> pre-commit run --hook-stage manual pyright_reportGeneralTypeIssues
> ```

Yes, and you have to add that you need to stage the changed files before doing the typing check.

**Comment by Dr-Irv** [comment]
> CI is green - do you have the same version(s) of packages installed? I've sometimes had failures when I had, for example, a different numpy version

So I had done `mamba env update -f environment.yml`, but because `pandas-dev` was activated, not all packages (including `mypy`) were updated.  So by deactivating the environment, then doing the `mamba update` command, everything got properly updated.

Maybe we need to put something in the contributing docs about how to update the environment when you merge with `upstream/main`.

**Comment by jayam30** [comment]
Hey I want to start my contribution with this, could I be assigned this

**Comment by Dr-Irv** [comment]
> Hey I want to start my contribution with this, could I be assigned this

Thanks for the offer, but we have an active PR #51352 that has the required changes.
