### ISSUE TITLE
ENH: to_numeric on dataframe

### ISSUE THREAD

**Issue by markxwang** [pandas-dev/pandas#51357]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I have a very long and wide string dataframe (e.g. 4 million rows * 1000 columns) that need to be `to_numeric`ed. 

The df contains invalid values that should be coerced as `NaN`. Currently the only approach is to use `apply`
```python
df.apply(pd.to_numeric, errors="coerce")
```
which takes a substantial amount time given the number of columns.

### Feature Description

Allow `pd.to_numeric` to take dataframe directly.

### Alternative Solutions

Alternatively, if `astype` can take `coerce`, if can also solve the issue.

**Comment by phofl** [comment]
There is no real advantage of having to_numeric taking a DataFrame, we would still have to iterate over all columns, e.g. same outcome.
Closing as there is another issue about astype already
