### ISSUE TITLE
PERF: DataFrame.from_records with DataFrame input

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#51353]
Speculative: DataFrame.from_records if passed a DataFrame goes through internals.construction.to_arrays and ends up splitting the frame into individual columns.  This can result in slower subsequent operations if that splitting turned out to be unnecessary.  Can we handle DataFrame input inside from_records and avoid this splitting?

This is also the only way we get to to_arrays with a DataFrame input, so the function could be simplified if that case could be ruled out.

**Comment by phofl** [comment]
Can we simply deprecate a DataFrame input? I might be missing something, but there seems to be no use-case that can't be achieved through calling other functions? e.g. set_index, reindex and drop

**Comment by jbrockmendel** [comment]
Agreed it seems like a really weird use case.
