### ISSUE TITLE
CI: matplotlib 3.7.0 broke ci

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#51394]
Started seeing this on the arm builds

https://app.circleci.com/pipelines/github/pandas-dev/pandas/24736/workflows/0c1b7766-2149-40ab-9130-18e134e87e4c/jobs/56289

**Comment by mroeschke** [comment]
Looks like https://github.com/matplotlib/matplotlib/pull/23573 impacted `pandas/tests/plotting/frame/test_frame.py::TestDataFramePlots::test_plain_axes`

**Comment by mroeschke** [comment]
Opened up https://github.com/matplotlib/matplotlib/issues/25219 for the other failures
