### ISSUE TITLE
CI: openpyxl 3.1.1 broke ci

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#51392]
https://foss.heptapod.net/openpyxl/openpyxl/-/issues/1963

https://app.circleci.com/pipelines/github/pandas-dev/pandas/24736/workflows/0c1b7766-2149-40ab-9130-18e134e87e4c/jobs/56289

**Comment by Dr-Irv** [comment]
openpyxl 3.1.2 fixes this.

**Comment by relativistic** [comment]
Looks like its on conda forge now.

https://anaconda.org/conda-forge/openpyxl shows v3.1.2 as of 5/5/2023
