### ISSUE TITLE
STYLE: replace unwanted-patterns-strings-to-concatenate with ruff

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#51406]
Task here is:

1. in 

  https://github.com/pandas-dev/pandas/blob/fe85cbfb20f3f360ebba62905b93a6f98bf655c1/pyproject.toml#L201-L215

  add
```
# implicit string concatenation
"ISC",
```

2. run `pre-commit run ruff --all-files`, and fix up everything it flags
3. remove 

  https://github.com/pandas-dev/pandas/blob/fe85cbfb20f3f360ebba62905b93a6f98bf655c1/.pre-commit-config.yaml#L348-L352

4. remove

https://github.com/pandas-dev/pandas/blob/73840ef221050af2588b079bd6ba45c8e291bcba/scripts/validate_unwanted_patterns.py#L235-L281

5. remove 

https://github.com/pandas-dev/pandas/blob/3a0db109390ddf9ab331cc86e63449c7445aa8a7/scripts/tests/test_validate_unwanted_patterns.py#L156-L195

6. if there's anything else related to this old script which `ruff` now supplants, feel free to remove that too

**Comment by natmokval** [comment]
I would like to work on this.

**Comment by jayam30** [comment]
Hey I want to start my contribution with this, could I be assigned this

**Comment by harsimran44** [comment]
i would like to work on this.

**Comment by MarcoGorelli** [comment]
there's already a PR open sorry, please look for another issue to work on (e.g. https://github.com/pandas-dev/pandas/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)
