### ISSUE TITLE
STYLE ruff: enable PIE

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#51407]
steps are:

1. add
```
# misc lints
"PIE",
```
to 

https://github.com/pandas-dev/pandas/blob/6db4c479d719a400ef39bc59adc831c4f5425ad7/pyproject.toml#L201-L215

2. run `pre-commit run ruff --all-files`
3. fixup all errors
4. stage, commit, push

**Comment by victorian177** [comment]
@MarcoGorelli The link posted is giving a 404 Not Found.

**Comment by MarcoGorelli** [comment]
apologies, fixed the link, thanks

and sure, feel free to work on this

**Comment by jayam30** [comment]
Hey I want to start my contribution with this, could I be assigned this
