### ISSUE TITLE
API: quantile with bool/boolean dtypes

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#51424]
```python
arr = np.random.randn(1000) < 0
ser = pd.Series(arr)

ser.quantile(0.5)  # <- raises

gb = ser.groupby([1] * len(ser))
gb.quantile(0.5)  # <- does not raise
```

Same behavior for the nullable boolean dtypes.

This should be the same for NDFrame and GroupBy.  I'm fine with either allowing or raising as long as we're consistent.

**Comment by jbrockmendel** [comment]
@mroeschke @phofl preferences here?  The mismatch is a blocker in fixing GroupBy.quantile perf #51385.

**Comment by mroeschke** [comment]
Looks like Series behavior raises the same error as the numpy behavior. I'm slightly leaning to matching that behavior.

Plus if this was supported, shouldn't the result be bool/boolean (gb looks to return float)?

**Comment by phofl** [comment]
I think I'd also prefer raising

**Comment by rhshadrach** [comment]
+1 on raising.
