### ISSUE TITLE
BUG: std with array_manager and NaT results

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#51446]
When a reduction results in NaT, the array manager reduction assumes the output dtype is the same as the input dtype. This is not correct for `std` (and from what I can tell, only `std` is incorrect).

```
df = pd.DataFrame({'a': ['2022-01-01', '2022-01-02', pd.NaT, '2022-01-03']})
df['a'] = pd.to_datetime(df['a'])

result = df.std(skipna=True)
print(result)
# a   1 days
# dtype: timedelta64[ns]

result2 = df.std(skipna=False)
print(result2)
# a   NaT
# dtype: datetime64[ns]
```

**Comment by jbrockmendel** [comment]
Looks like an xfail in test_std_datetime64_with_nat

**Comment by topper-123** [comment]
Just checked and this is not fixed by #52788 ATM so probably `std` needs some dtype info. I' pretty sure this is fixable after #52788, so can be done in a follow-up.

**Comment by jbrockmendel** [comment]
df.std() now raises ValueError with ArrayManager

**Comment by rhshadrach** [comment]
The ArrayManager is now deprecated. Closing.
