### ISSUE TITLE
API: ArrowExtensionArray.value_counts should return int64[pyarrow] instead of Int64

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#51462]
Currently this explicitly calls an astype

```
return Series(counts, index=index, name="count").astype("Int64")
```

But with `ArrowExtensionArray` now able to support all pyarrow types, this should preserve the pyarrow type and return `int64[pyarrow]`

**Comment by lukemanley** [comment]
Maybe somewhat related - do you think the `ArrowExtensionArray` comparison methods should preserve the pyarrow type and return `boolean[pyarrow]`?

**Comment by mroeschke** [comment]
Good catch. Agreed `_cmp_method` should be changed to return `"boolean[pyarrow]"` instead of `"Boolean"` type. Since `ArrowStringArray` and `ArrowExtensionArray` are both marked as experimental it should be okay to change it for 2.0 if you're interested.

**Comment by lukemanley** [comment]
Sounds good. I'll take a look
