### ISSUE TITLE
BUG: configparser.NoSectionError: No section: 'versioneer'

### ISSUE THREAD

**Issue by CAlexPac** [pandas-dev/pandas#51499]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
pip install --upgrade pip
pip install numpy cython
git clone https://github.com/pandas-dev/pandas.git
cd pandas
python setup.py install
```

### Issue Description

Cannot install pandas from source.

### Expected Behavior

To have the versioneer details in setup.cfg so it will install.

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by lithomas1** [comment]
What version of setuptools are you on?

I think you need at least setuptools 61

**Comment by MarcoGorelli** [comment]
you also need `versioneer[toml]` installed

**Comment by MarcoGorelli** [comment]
🤔 should the README still be recommending this actually? https://github.com/pandas-dev/pandas#installation-from-sources

**Comment by CAlexPac** [comment]
I have setuptools installed.
setuptools                          65.5.1

**Comment by MarcoGorelli** [comment]
I just tried this, and installing `versioneer[toml]` fixes it

**Comment by lithomas1** [comment]
> I just tried this, and installing `versioneer[toml]` fixes it

Ah, makes sense. setuptools vendors their own tomli, so that's why it wouldn't be installed.

I feel like maybe ``pip install .`` would fix this? `versioneer[toml]` is already listed in the requires there.

IIRC, ``python setup.py install`` is deprecated or something.

**Comment by CAlexPac** [comment]
Yes, that fixed it.

`
pip install "versioneer[toml]"
pip install .
`

Thank you very much.
