### ISSUE TITLE
BUG: Transpose changes dtype from object to timedelta/datetime

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#51546]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
df = DataFrame({"a": [pd.Timedelta("1 days"), pd.NaT, pd.Timedelta("2 days")]}, dtype=object)
df.T.dtypes


0    timedelta64[ns]
1     datetime64[ns]
2    timedelta64[ns]
dtype: object
```

### Issue Description

I'd expected this to return object, but this was changed in #26285

### Expected Behavior

The whatsnew looks like the fix was tailored to avoid raising an error, any other motivations?

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by jbrockmendel** [comment]
I'd expect object too
