### ISSUE TITLE
Pandas' EMA not matching the stock's EMA?QST: 

### ISSUE THREAD

**Issue by ZRT-1998** [pandas-dev/pandas#51551]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/55910760/how-do-i-correctly-calculate-ema-for-a-stock-using-ta-lib-or-pandas

### Question about pandas

Pandas' EMA not matching the stock's EMA?QST:

**Comment by phofl** [comment]
Hi, please provide a reproducible example and more context. See https://matthewrocklin.com/minimal-bug-reports

**Comment by AlexKirko** [comment]
If it's a persistent issue, showing us a stock with three dividend payments and then showing the discrepancy between the pandas calculation and  the explicit formula should be sufficient for us to be able to reproduce the problem.

**Comment by ZRT-1998** [comment]
https://stackoverflow.com/a/75540362/7482878

**Comment by ZRT-1998** [comment]
> If it's a persistent issue, showing us a stock with three dividend payments and then showing the discrepancy between the pandas calculation and the explicit formula should be sufficient for us to be able to reproduce the problem.
After the test, cycle index is calculated in the data set less than or equal to 2 times,the calculation error.May be in operation to some requirements in the face of data in the document.

**Comment by ZRT-1998** [comment]
> If it's a persistent issue, showing us a stock with three dividend payments and then showing the discrepancy between the pandas calculation and the explicit formula should be sufficient for us to be able to reproduce the problem.
When choosing limit = 20 is not accurate, when selecting limit = 100 is accurate
`import pandas as pd
import requests
import json
import time

#Data:OKX ETH-USDT-SWAP 1H
limit= 20 #When using limit = 100 data is normal
url = 'https://www.okx.com/api/v5/market/candles?instId=ETH-USDT-SWAP&bar=1H&limit={}'.format(limit)    
headers={'User-Agent' : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36'}
result =requests.get(url=url,headers=headers).json()
df=pd.DataFrame(result['data'])
df = df.rename(columns={0: 'open_time', 1: 'open', 2: 'high', 3: 'low',  4: 'close', 5: 'volz',6:'voleth',7:'volusdt',8:'KlineState'})
for i in list(df):
    df[i]=list(reversed(df[i]))   


#Pandas ema14 example:
'''
DataFrame.ewm(com=None, span=None, halflife=None, alpha=None, min_periods=0, adjust=True, ignore_na=False, 
axis=0, times=None, method='single')[source]
'''
period=14
while True:
    example_ema_1=df['close'].ewm(span=period).mean().values[-1].round(2)

    example_ema_2=df['close'].ewm(span=period, adjust=False).mean().values[-1].round(2)

    example_ema_3=df['close'].ewm(span=period, adjust=False,ignore_na=True).mean().values[-1].round(2)

    print('example_ema_1',example_ema_1)
    print('example_ema_2',example_ema_2)
    print('example_ema_3',example_ema_3)

    time.sleep(1)





`

**Comment by ZRT-1998** [comment]
> Hi, please provide a reproducible example and more context. See https://matthewrocklin.com/minimal-bug-reports

When choosing limit = 20 is not accurate, when selecting limit = 100 is accurate .I don't know what the underlying principle is, but hopefully the documentation will illustrate that.
my test code:
https://stackoverflow.com/a/75540362/7482878

**Comment by ZRT-1998** [comment]
> If it's a persistent issue, showing us a stock with three dividend payments and then showing the discrepancy between the pandas calculation and the explicit formula should be sufficient for us to be able to reproduce the problem.

After the test, cycle index is calculated in the data set less than or equal to 2 times,the calculation error.May be in operation to some requirements in the face of data in the document.

**Comment by ZRT-1998** [comment]
> > Hi, please provide a reproducible example and more context. See https://matthewrocklin.com/minimal-bug-reports
> 
> When choosing limit = 20 is not accurate, when selecting limit = 100 is accurate .I don't know what the underlying principle is, but hopefully the documentation will illustrate that. my test code: https://stackoverflow.com/a/75540362/7482878

OKX CHART:https://www.okx.com/trade-swap/eth-usdt-swap
