### ISSUE TITLE
ENH: Add `ScatterPlot._scatter()` 

### ISSUE THREAD

**Issue by AdamOrmondroyd** [pandas-dev/pandas#51560]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I am contributing to [`anesthetic`](https://github.com/williamjameshandley/anesthetic/), which extends pandas for plotting the results of nested sampling. It is very convenient that `HistPlot._makeplot()` calls the class method `self._plot()` which `KdePlot` overrides, as our histograms can do the same and not worry about handling the rest of the formatting in `_makeplot()`. It would be useful if `ScatterPlot` worked similarly, so we could insert our own scatter.

Perhaps `_scatter()` would be more appropriate than `_plot()` in this case.

### Feature Description

Extending ScatterPlot would look something like this:
```
from pandas.plotting._matplotlib.core import ScatterPlot

def my_scatter_method(ax, x, y, **kwds):
    # additional processing appropriate for nested sampling
    return ax.scatter(x, y, ...)
    

class MyScatterPlot(ScatterPlot):
    @classmethod
    def _scatter(cls, ax, x, y, **kwds):
        return my_scatter_method(ax, x, y, **kwds)
```

### Alternative Solutions

Currently we override `ScatterPlot._makeplot()`, so we have to deal again with handling all the e.g. color arguments.

**Comment by mroeschke** [comment]
Thanks for the request, but it appears this feature hasn't gotten much traction so closing
