### ISSUE TITLE
DOC: orient=table not documented in read_json

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#51588]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.read_json.html

### Documentation problem

table explanation is missing

### Suggested fix for documentation

Add explanation

**Comment by futureprogrammer360** [comment]
take
