### ISSUE TITLE
BUG?: Series.any / Series.all behavior for pyarrow vs. non-pyarrow empty/all-NA

### ISSUE THREAD

**Issue by lukemanley** [pandas-dev/pandas#51624]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

for dtype in ["bool", "boolean", "boolean[pyarrow]"]:
    ser = pd.Series([], dtype=dtype)
    print(dtype, ser.any(), ser.all())
```

### Issue Description

```
bool False True
boolean False True
boolean[pyarrow] <NA> <NA>
```

At the moment `Series.any` and `Series.all` have inconsistent behavior for pyarrow vs. non-pyarrow dtypes for empty or all null data. The pyarrow behavior is coming from `pyarrow.compute.any` and `pyarrow.compute.all` which return null in these cases. I suspect different behavior here within pandas is likely to be problematic and confusing. Is it OK to diverge from pyarrow here in order to be more consistent within pandas?

### Expected Behavior

Probably to match the behavior of non-pyarrow types

### Installed Versions

.

**Comment by rhshadrach** [comment]
I think the difference is in `min_count`; pyarrow defaults to 1 whereas pandas (where it exists) defaults to 0. I think pandas should use the pandas default when calling pyarrow.

**Comment by lukemanley** [comment]
> I think the difference is in `min_count`; pyarrow defaults to 1 whereas pandas (where it exists) defaults to 0. I think pandas should use the pandas default when calling pyarrow.

ah good point. That makes sense.
