### ISSUE TITLE
BUG: `sort_index` on a multiindex changes values of the index

### ISSUE THREAD

**Issue by erezinman** [pandas-dev/pandas#51647]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np
idx = pd.MultiIndex(levels=[['a', 'b', 'c'], [16., 32., 4.]], codes=[[0, 1, 2, 2], [-1, -1, 1, 1]])
df = pd.DataFrame(np.arange(16).reshape(4, 4), columns=idx)
df
#     a   b    c     
#   NaN NaN 32.0 32.0
# 0   0   1    2    3
# 1   4   5    6    7
# 2   8   9   10   11
# 3  12  13   14   15

df.sort_index(axis=1)

#      a    b    c     
#   4.0  4.0  32.0 32.0
# 0    0    1    2    3
# 1    4    5    6    7
# 2    8    9   10   11
```

### Issue Description

The empty values are filled with values that shouldn't be there.

### Expected Behavior

The value in the first and second column index after sorting should be `np.nan` but instead it's filled with `4.0`. This is quite severe!

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.9.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-139-generic
Version          : #156-Ubuntu SMP Fri Jan 20 17:27:18 UTC 2023
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8
pandas           : 1.5.3
numpy            : 1.22.0
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 61.2.0
pip              : 22.3.1
Cython           : 0.29.30
pytest           : 7.1.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.5.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.5
brotli           : 
fastparquet      : None
fsspec           : 2022.11.0
gcsfs            : None
matplotlib       : 3.6.2
numba            : 0.56.0
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : 6.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
snappy           : None
sqlalchemy       : 1.4.27
tables           : 3.7.0
tabulate         : 0.8.10
xarray           : 2022.10.0
xlrd             : 2.0.1
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by erezinman** [comment]
Sorry, this is probably the same as #25818. Didn't check well enough before. Regardless, I think mine is a simpler MWE if you want to use it.

**Comment by phofl** [comment]
No worries, closing as duplicate. Can you post your example there as well?
