### ISSUE TITLE
WEB: Improve the style of the code boxes in the website

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#51657]
xref https://github.com/pandas-dev/pandas/pull/51458#issuecomment-1445482466

In our website we've got a style for the boxes with source code. I don't think we've got many, but at least some PDEPs do, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html

It'd be good to get the formatting of the code blocks nicer, with padding, and maybe a border. Also the quote blocks can probably be improved.

The styles should be defined in `web/pandas/static/css`.

**Comment by dsamuel27** [comment]
Can I work on this issue?

**Comment by dsamuel27** [comment]
take

**Comment by sakethrajesh** [comment]
can I work on this issue as well

**Comment by datapythonista** [comment]
This has been fixed in #51665
