### ISSUE TITLE
WEB: Sorting of PDEPs

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#51662]
xref https://github.com/pandas-dev/pandas/pull/51656#issuecomment-1445523057

The list of PDEPs is growing, and we're likely to have a PDEP-10 soon. So far, we list PDEPs at https://pandas.pydata.org/about/roadmap.html, and we started sorting the PDEP list by title in #51656. As the numbers grow to 10, sorting naively by title will make that `PDEP-2 > PDEP-10`. To keep the list sorted, we have two main options, use a regex to extract the number, convert it to int, and sort by it, or use `PDEP-001`... in PDEP PR titles so the current sorting comes naturally. Personally I don't have a preference, I guess we can make the sort a bit more complex and make our life easier. But since there is some work on PDEPs, some discussion on moving to another repo... I prefer to ask, in case there are other ideas.

**Comment by kostyafarber** [comment]
Hey, I know this still needs discussion but I've put something together that extracts the number from the titles using regex and sorts on that. 

I can open a PR for it, and we can discuss if we want to go down this route, if not we can always close it.

My two cents, I think it looks cleaner if we use numbers like 1 as opposed to 001 etc. It also aligns to how PEPs are numbered for Python (https://peps.python.org/pep-0000/), which is nice I guess.

Let me know @datapythonista

**Comment by datapythonista** [comment]
I'm open to any approach, if you can open the PR that'd be great. Please ping me when you do, so I can have a look.

**Comment by kostyafarber** [comment]
@datapythonista cc
