### ISSUE TITLE
DEPR: use_inf_as_na

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#51684]
Support for use_inf_as_na isn't great, it performs poorly, and we don't have any way to make EAs respect it.  Is this worth keeping?

**Comment by mahmoudmarayef** [comment]
We can convert infinity values to NaN before processing: Instead of relying on the use_inf_as_na parameter, you can manually convert infinity values to NaN before processing the data. This can be done using the replace method in pandas.

**Comment by jbrockmendel** [comment]
Discussed on last week's dev call, consensus was +1 to deprecate.
