### ISSUE TITLE
PERF: groupbys much slower than on v1.5.2 

### ISSUE THREAD

**Issue by topper-123** [pandas-dev/pandas#51681]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this issue exists on the main branch of pandas.

### Reproducible Example

```python
>>> import pandas as pd
>>> cat = pd.Categorical(list("bac")*1_000_000)
>>> df = pd.DataFrame({"cat": cat, "codes": cat.codes})
>>> %timeit df.groupby("cat").sum()
120 ms ± 246 µs per loop. # v1.5.2
404 ms ± 2.24 ms per loop. # main
```

This is likely the same underlying perf bug as for #51680.

This is probably a blocker for v2.0.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : aeafdd66e4f224f7dee84c40b211595c582c4509
python           : 3.9.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 22.3.0
Version          : Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 2.0.0.dev0+1674.g259917c2ff.dirty
numpy            : 1.23.4
pytz             : 2022.7
dateutil         : 2.8.2
setuptools       : 65.6.3
pip              : 22.3.1
Cython           : 0.29.33
pytest           : 7.1.2
hypothesis       : 6.37.0
sphinx           : 5.0.2
blosc            : 1.10.6
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.9.1
html5lib         : None
pymysql          : 1.0.2
psycopg2         : 2.9.5
jinja2           : 3.1.2
IPython          : 8.9.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.5
brotli           :
fastparquet      : 0.8.3
fsspec           : 2022.11.0
gcsfs            : 2022.11.0
matplotlib       : 3.6.2
numba            : 0.56.4
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : 9.0.0
pyreadstat       : None
pyxlsb           : 1.0.10
s3fs             : 2022.11.0
scipy            : 1.9.1
snappy           : None
sqlalchemy       : 1.4.43
tables           : 3.7.0
tabulate         : 0.9.0
xarray           : None
xlrd             : 2.0.1
zstandard        : 0.18.0
tzdata           : None
qtpy             : 2.2.0
pyqt5            : None

</details>

**Comment by jbrockmendel** [comment]
I get within the margin of error of 22ms on both 1.5.3 and main

**Comment by rhshadrach** [comment]
I'm not seeing anything jump out in the categorical groupby ASVs either:

https://asv-runner.github.io/asv-collection/pandas/

**Comment by jbrockmendel** [comment]
im on mac

**Comment by phofl** [comment]
No, I have an m2 and not seeing it either

**Comment by phofl** [comment]
I guess something on @topper-123 machine is off? Not sure but mine is more than 10 times faster, this seems a bit odd, getting around 10ms for both

**Comment by topper-123** [comment]
Yeah, I had a build difference...

One was with `python setup.py build_ext --inplace --force -j4` while the slow version  was `python setup.py build_ext --inplace --force -j4 --with-debugging-symbols`. I can close this.
