### ISSUE TITLE
ENH/DOC: call for Timestamp

### ISSUE THREAD

**Issue by adamgreenhall** [pandas-dev/pandas#5168]
When you create a timestamp with a timezone and don't use a keyword argument, it fails silently:

```
>> pd.Timestamp('2012-01-01', 'US/Pacific')
Timestamp('2012-01-01 00:00:00', tz=None)
```

**Comment by jbrockmendel** [comment]
Is this handled by #17943, or is there a distinct issue?

**Comment by jreback** [comment]
yep, want to add a validation test to close this?
