### ISSUE TITLE
BUG: ewm.sum() gives incorrect values when used with halflife parameter

### ISSUE THREAD

**Issue by SmartLizard** [pandas-dev/pandas#51695]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame(
{"t": pd.to_datetime(["2023-02-28 12:00:00", "2023-02-28 12:00:05", "2023-02-28 12:00:15"]),
 "s": [1.0, 0.0, 0.0],
})

>>> print(df["s"].ewm(halflife="5 seconds", times=df["t"]).sum())
0    1.00
1    0.50
2    0.25

>>> print(df["s"].ewm(halflife="5 days", times=df["t"]).sum())
0    1.00
1    0.50
2    0.25
```

### Issue Description

pd.ewm.sum() does not use halflife parameter.

As I understand it, there are two series held inside ewm: the data values and the weights.  The .sum() function should contain the sum of the products of the data values with their weights.

### Expected Behavior

For the first example I expected:

1.0*1.0 = 1
1.0*0.5 + 0.0*1.0 = 0.5 (1 half life)
1.0*0.125 + 0.0 * 0.5 + 0.0 *1.0 = 0.125 (3 half lifes)  - here ewm returns 0.25 instead of 0.125

For the second example I expected:
1.0
0.9999
0.9999
since the half life is 5 days and only a few seconds have elapsed.

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.11.0.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Fri Dec 16 00:35:00 PST 2022; root:xnu-7195.141.49~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.5.3
numpy            : 1.24.2
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 65.6.3
pip              : 23.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None
</details>

**Comment by topper-123** [comment]
The docs say about `halflife`:

> If times is specified, a timedelta convertible unit over which an observation decays to half its value. Only applicable to mean(), and halflife value will not apply to the other functions.

It looks like in your example it just sets `halflife` to 1 and ignores `times`, which is definitely not great.  using something else than `mean` should raise. So I agree this is bug.

**Comment by sqali** [comment]
Hi @topper-123 ,

I would love to work on this issue. Going through the files and potential fix for it.

**Comment by sqali** [comment]
take

**Comment by sqali** [comment]
Hi @lithomas1 ,

Could you review and confirm if this is a bug worth working on? If yes, I will go ahead.

**Comment by lithomas1** [comment]
Sure, go for it.
