### ISSUE TITLE
STYLE enable ruff PLR5501

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#51709]
Task is:

1. check the [contributing guide](https://pandas.pydata.org/docs/dev/development/contributing_environment.html) for how to set up your environment
2. remove `PLR5501` from

https://github.com/pandas-dev/pandas/blob/4d18871d398248c5876035f5aa139292e6a05279/pyproject.toml#L274-L275

3. run `pre-commit run ruff --all-files`
4. fixup the errors it flags
5. stage, commit, push, open pull request

**Comment by ahmad2901** [comment]
Hi! can i help with this problem.

**Comment by MarcoGorelli** [comment]
go ahead

**Comment by ahmad2901** [comment]
How can  i run code to check for errors?

**Comment by MarcoGorelli** [comment]
step 3 from https://github.com/pandas-dev/pandas/issues/51709#issue-1604509032

**Comment by ahmad2901** [comment]
hey! soory to bother again.
i am having this issue i hav pre commit installed but whenever i use it this error comes up
pre-commit : The term 'pre-commit' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling 
of the name, or if a path was included, verify that the path is correct and try again


do u know solution??

**Comment by MarcoGorelli** [comment]
did you follow the contributing guide? https://pandas.pydata.org/docs/dev/development/contributing_environment.html

**Comment by ahmad2901** [comment]
Yes i did I installed with docker

**Comment by MarcoGorelli** [comment]
perhaps try gitpod then

**Comment by ahmad2901** [comment]
sure i will give it a try thanks for help

**Comment by ahmad2901** [comment]
does this issue want to remove "PLR5501" from whole code???

**Comment by MarcoGorelli** [comment]
you could add `pandas/core/*` to the `per-file-ignores` (in pyproject.toml) for this code and just do the rest if it's too much to do in one go. that might be better actually

**Comment by MarcoGorelli** [comment]
as in, to add
```
# to be enabled gradually
"pandas/core/*" = ["PLR5501"]
```
here in this section:

https://github.com/pandas-dev/pandas/blob/4d18871d398248c5876035f5aa139292e6a05279/pyproject.toml#L288-L290

Then there shouldn't be too many to fixup

**Comment by ahmad2901** [comment]
sure thanks

**Comment by ahmad2901** [comment]
ok so it says "Found 30 errors." should i start with this

**Comment by MarcoGorelli** [comment]
yup, thanks!

**Comment by ahmad2901** [comment]
Ok I will start tomorrow its 11pm rn.

**Comment by MarcoGorelli** [comment]
😄 sure thing, good night 🛌

**Comment by ahmad2901** [comment]
Take

**Comment by ahmad2901** [comment]
Hey, wanted to ask how can i use --fix

**Comment by MarcoGorelli** [comment]
i don't think you can for this particular code, you'll have to do it manually

**Comment by ahmad2901** [comment]
no i left some blank space i wanted to use it for that

**Comment by ahmad2901** [comment]
*] 4 potentially fixable with the --fix option.

**Comment by MarcoGorelli** [comment]
you can run it via the command line, just make sure you have the same version installed as is in the pre-commit-config.yaml file

**Comment by ahmad2901** [comment]
Hey, i passed those tests. should i fix rest of those errors now after removing  "pandas/core/*" = ["PLR5501"] ???

**Comment by MarcoGorelli** [comment]
you can open a PR

**Comment by ahmad2901** [comment]
ok

**Comment by ahmad2901** [comment]
my branch is few commit behind what sholud i do?

**Comment by MarcoGorelli** [comment]
you can just open a pr

**Comment by ahmad2901** [comment]
Done PR that took some time it was first PR ever.
