### ISSUE TITLE
STYLE enable ruff PLW2901

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#51708]
Task is:

1. check the [contributing guide](https://pandas.pydata.org/docs/dev/development/contributing_environment.html) for how to set up your environment
2. remove `PLW2901` from

https://github.com/pandas-dev/pandas/blob/2c10d93b8b2ccee79434c251ac9c1cd94513cc1e/pyproject.toml#L272-L273

3. run `pre-commit run ruff --all-files`
4. fixup the errors it flags - see https://beta.ruff.rs/docs/rules/redefined-loop-name/ for more info on this error
5. stage, commit, push, open pull request

**Comment by ErdiTk** [comment]
Hi Marco, may I help for this issue?

**Comment by MarcoGorelli** [comment]
sure, go ahead

**Comment by ErdiTk** [comment]
Take

**Comment by ErdiTk** [comment]
After removing it and running `pre-commit run ruff --all-files`, I found 125 errors. I will start tackling them by tomorrow. Shall I go over them one by one right? Seems like the issue is as described in your link.

**Comment by MarcoGorelli** [comment]
yeah sounds good - and feel free to ignore other folders too if the number of remaining issues is too many

**Comment by ErdiTk** [comment]
I grouped the issues under the "to be gradually enabled" section and resolved the isolated once. Unfortunately today I had limited time to dedicate to it. The changes seems to be a renaming of the variables which get overwritten. I can continue and do all of them if that's fine for you. For now I changed something like this:
`for foo in bar:
    foo = function_x()
return foo
`
Into this:

`for foo in bar:
    foo_new = function_x()
return foo_new
`

Please let me know if you think there is another approach for it.

**Comment by ErdiTk** [comment]
I generated the PR to show you the changes. If it's fine for you I can update the PR by continuing the resolution of "to be gradually enabled" items I added.

**Comment by DineshS92** [comment]
Hi Marco, can you please explain why this issue was reopened? I would like to help with it. Thanks!

**Comment by MarcoGorelli** [comment]
It was probably an accident - thanks!
