### ISSUE TITLE
BUG: bytes of special nan lost with .loc/.iloc

### ISSUE THREAD

**Issue by aileenboe** [pandas-dev/pandas#51721]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import numpy as np
import pandas as pd
import struct

def test_nans(arr):
    special_nan = "fffffffffffffffe"
    boo = []
    for i in arr:
        boo.append(bytes(struct.pack(">d", i)).hex() == special_nan)
    return boo

special_nan = struct.unpack(">d", bytes.fromhex("fffffffffffffffe"))[0]
 
arr = np.array([1.0, 1.0], dtype=np.float64)
df = pd.DataFrame(arr)

df.loc[0] = special_nan
print(f"test for special nan: {test_nans(df[0])}")
```

### Issue Description

We use special `nan` values to hold information.  When using `.loc` (or `.iloc`) as in the example above the original byte signature of the special `nan` value is destroyed. This appears in `1.5.3` and `2.0.0rc0`. But it used to work with `1.4.4`. If I run the example with `1.4.4` I get: `test for special nan:  [True, False]`. With `1.5.3` I get: `test for special nan:  [False, False]`.

This issue is related to #51675. 

### Expected Behavior

I would expect for `.loc`/`.iloc` to maintain the bytes of the special `nan` as in pandas version `1.4.4`.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.9.13.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : English_Germany.utf8

pandas           : 1.5.3
numpy            : 1.23.5
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 63.4.1
pip              : 22.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.7
lxml.etree       : 4.6.4
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : 1.3.5
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.3.4
numba            : None
numexpr          : 2.8.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.3
snappy           : None
sqlalchemy       : 1.4.39
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : 2021.5

</details>

**Comment by topper-123** [comment]
I've never heard of special nan values like this. Is there official numpy support for this? To my knowledge we don't support this in pandas. If there is official numpy support for this, we could take a discussion about this in pandas, else I don't think this can be supported, sorry. Else I'd suggest doing an ExtensionArray for your purpose.

**Comment by mroeschke** [comment]
Agreed with not being able to support without numpy supporting this so closing
