### ISSUE TITLE
CI: min versions timeouts

### ISSUE THREAD

**Issue by lukemanley** [pandas-dev/pandas#51733]
I didn't see an open issue, but the min versions job has been timing out for the past few days. 

Looking at the logs from a few different timeouts, it looks like they're all getting stopped during `test_orc_writer_dtypes_not_supported`. 

I haven't had a chance to look into it, but it looks like a few ORC related PRs were merged recently (#51623, #51604).

**Comment by jbrockmendel** [comment]
how are you checking for what test is stalled?  are we already doing something like #51409?

**Comment by lukemanley** [comment]
Nothing special, just saw that test in the stack trace in the logs when those jobs were canceled. In this case it was shown in the stack trace for multiple PRs, not sure if that's always the case.
