### ISSUE TITLE
DEPR: NDFrame.bool

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#51749]
We recently deprecated `Series.__int__` and `Series.__float__`, let's do `NFrame.bool` too.

xref #32923

**Comment by phofl** [comment]
+1 

This is funny, @rhshadrach and I talked about this while answering questions for the AMA yesterday :)

**Comment by MarcoGorelli** [comment]
yes, please

then we can get rid of the confusing `bool_t` in that file as well 😄

**Comment by topper-123** [comment]
+1

**Comment by jorisvandenbossche** [comment]
+1

**Comment by jorisvandenbossche** [comment]
For Series.bool, we can point to `Series.item()` as an alternative. The main difference is that `item()` will just in general give you the scalar value (if Series is length 1), while `bool()` will only do that if it's actually a boolean.
