### ISSUE TITLE
STYLE enable ruff TCH

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#51740]
This code actually may make a difference to performance: 

Task here is:
0. make sure you've followed the steps in https://pandas.pydata.org/docs/dev/development/contributing.html and have set up your development environment
1. remove 3-5 of the lines in

https://github.com/pandas-dev/pandas/blob/d3854657e1c9842b8264b6cc90488ccfed0cd6a2/pyproject.toml#L293-L326

2. run `pre-commit run ruff --all-files`, and fix up the issues it reports. You can see https://github.com/pandas-dev/pandas/pull/51687 for some examples of how to do this
3. if `pre-commit run ruff --all-files` passes, then stage, commit, push, open pull request, celebrate

Please don't comment "take" on this issue (as multiple people can be assigned), and don't ask for permission to work on it. Instead, just leave a comment letting people know which

**Comment by clarkwiththew** [comment]
I am working on it

**Comment by clarkwiththew** [comment]
Finished the task with PR

https://github.com/pandas-dev/pandas/pull/51754

**Comment by potap75** [comment]
I got this when trying to do a pull request: 
![Uploading Screenshot 2023-03-04 at 12.22.52 AM.png…]()

**Comment by luke396** [comment]
I am working on pandas/core/indexers/*

**Comment by luke396** [comment]
Continue to working on
```
"pandas/core/array_algos/*"
"pandas/core/dtypes/*"
"pandas/core/generic.py"
"pandas/core/frame.py"
"pandas/core/series.py"
```

**Comment by v-mcoutinho** [comment]
I did
```
 "pandas/_libs/*"
```

**Comment by DerTimonius** [comment]
I will try `pandas/core/common.py`!

**Comment by Rylie-W** [comment]
Trying pandas/core/resample.py

**Comment by DerTimonius** [comment]
I'll go for `pandas/core/util/*` next. Also @MarcoGorelli it looks like my PR closed this issue...

**Comment by luke396** [comment]
Working on 
```
"pandas/core/reshape/*"
"pandas/core/strings/*" 
"pandas/core/tools/*"
"pandas/core/window/*"
"pandas/io/*"
```

**Comment by ErdiTk** [comment]
Working on:
```
 "pandas/core/apply.py" = ["TCH"] 
 "pandas/core/base.py" = ["TCH"] 
 "pandas/core/algorithms.py" = ["TCH"] 
 "pandas/core/ops/*" = ["TCH"] 
 "pandas/core/sorting.py" = ["TCH"] 
```

**Comment by luke396** [comment]
Working on, and  @MarcoGorelli , maybe need to reopen this issue again, when #51827 merged.
```
"pandas/core/construction.py" = ["TCH"] 
"pandas/core/common.py" = ["TCH"] 
"pandas/core/missing.py" = ["TCH"] 
"pandas/core/util/*" = ["TCH"] 
"pandas/core/reshape/*" = ["TCH"]
```

**Comment by Ramyahkay** [comment]
Working on : `"pandas/core/nanops.py" = ["TCH"] `

**Comment by ahmad2901** [comment]
I am working on "pandas/util/*" = ["TCH"]

**Comment by ahmad2901** [comment]
hey @Ramyahkay are you working on "pandas/core/nanops.py" = ["TCH"]  ??

**Comment by Ramyahkay** [comment]
> hey @Ramyahkay are you working on "pandas/core/nanops.py" = ["TCH"] ??

Yes, I am still working on it.

**Comment by MarcoGorelli** [comment]
@ahmad2901 feel free to submit a PR and close off this issue

**Comment by ahmad2901** [comment]
Sure I will do it.
