### ISSUE TITLE
improve explanation of linear interpolation in `quantile`

### ISSUE THREAD

**Issue by goi42** [pandas-dev/pandas#51745]
Currently explained like
https://github.com/pandas-dev/pandas/blob/2e218d10984e9919f0296931d92ea851c6a6faf5/pandas/core/series.py#L2647-L2648

The phrase "the fractional part of the index surrounded by `i` and `j`" is not easy to parse and has no clear meaning.

**Comment by molsonkiko** [comment]
Maybe add example?
`For example, if the raw index is 9.6, and the elements at indices 9 and 10 are 3 and 4,
return 0.4 * 3 + 0.6 * 4 = 3.6`.

**Comment by goi42** [comment]
Forgive me, but I do not know what the “raw index” is.

**Comment by molsonkiko** [comment]
Good point. I'll try again.
`For example, if (len(self) - 1) * q is 9.6, and the elements at indices 9 and 10 are 3 and 4, return 0.4 * 3 + 0.6 * 4 = 3.6`

**Comment by TeoSkondras** [comment]
take

**Comment by Detoro** [comment]
take

**Comment by goi42** [comment]
> Good point. I'll try again.
> `For example, if (len(self) - 1) * q is 9.6, and the elements at indices 9 and 10 are 3 and 4, return 0.4 * 3 + 0.6 * 4 = 3.6`

Yes, I think this example would be a good addition. (Sorry for the long delay.)
