### ISSUE TITLE
DEPR: axis=1 in DataFrame.window, resample

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#51778]
xref #51203 we've deprecated groupby with axis=1 bc under the hood it does a transpose anyway, so might as well tell users to do that directly.  resample and window do the same thing.  Let's deprecate those too.

**Comment by rhshadrach** [comment]
+1

**Comment by dannyi96** [comment]
Can I attempt to work on this if possible / not started on by anyone else ?
@jbrockmendel  @rhshadrach

**Comment by jbrockmendel** [comment]
Wait until a consensus develops

**Comment by mroeschke** [comment]
+1

**Comment by jreback** [comment]
+1

**Comment by phofl** [comment]
Sounds good to me

**Comment by dannyi96** [comment]
take
