### ISSUE TITLE
DOC: extension array with arrow 

### ISSUE THREAD

**Issue by achapkowski** [pandas-dev/pandas#51789]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

With the new 2.0 improvements, is there anything that needs to be added to custom dtypes and extension arrays to allow them to take advantage of the 2.x speed ups?

I couldn't find doc on this.

### Documentation problem

Extension array documentation is light

### Suggested fix for documentation

Answer the question above on how to integrate with the arrow backend.

**Comment by phofl** [comment]
Hi, https://pandas.pydata.org/docs/dev/user_guide/pyarrow.html?

**Comment by achapkowski** [comment]
That covers the standard dtypes not the custom ones. 

It talks about how it's implemented but doesn't go into enough detail.  Also is there a way to always use the arrow backend or do you have to always set the global settings?

**Comment by mroeschke** [comment]
> is there anything that needs to be added to custom dtypes and extension arrays to allow them to take advantage of the 2.x speed ups?

Do you mean when using a `pyarrow.ExtensionType` or `pandas.ExtensionDtype`?

**Comment by jorisvandenbossche** [comment]
> With the new 2.0 improvements, is there anything that needs to be added to custom dtypes and extension arrays to allow them to take advantage of the 2.x speed ups?

The arrow-based data types are ExtensionArrays themselves. So if you are implementing your own custom extension array, that won't automatically make any use of that (different EA implementations are independent, and you EA can't be two EAs at the same time). So if you want to make use of pyarrow under the hood in your own custom EA, you currently need to implement that yourself. 

It's an interesting question how we can make this easier in the future, though. `pd.arrays.ArrowExtensionArray` is publicly exposed, so you could subclass that, but I am not sure if we would already recommend that right now (given that this is still quite experimental / moving fast).

**Comment by achapkowski** [comment]
@jorisvandenbossche thanks for that! I'll give it a whirl and report back just to check the feasibility.

**Comment by jbrockmendel** [comment]
Is there anything actionable here?

**Comment by mroeschke** [comment]
Closing as not sure if there's anything else needed, but feel free to open up a new issue if you find something

**Comment by mroeschke** [comment]
Not sure, from the issue it's not entirely clear which pandas doc page needs updating with what information

**Comment by achapkowski** [comment]
@mroeschke the doc for custom dtypes and arrow is lacking.  Can this be improve/updated with v2 released?

**Comment by mroeschke** [comment]
> Can this be improve/updated with v2 released?

Sure, could you point to which "custom dtype" doc should be updated?

**Comment by achapkowski** [comment]
The Arrow  and custom dtype integrations

**Comment by mroeschke** [comment]
Specifically which urls? For example, we have several docs now describing Arrow and Extension functionality so I'm not sure from a user's perspective which would be a good location

**Comment by rhshadrach** [comment]
This issue seems to have gone stale without a clear and actionable request. Closing for now. If there is something specific that could be improved, comment here is the details and we can reopen.
