### ISSUE TITLE
BUG: eval() method does not support some symbols in column name

### ISSUE THREAD

**Issue by RinnetenseiQ** [pandas-dev/pandas#51808]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import numpy as np
import pandas as pd

c_names = ["a.1", "b", "c", "d"]
df = pd.DataFrame(np.random.randn(100, 4), columns=c_names)
df.eval("f.1 = a.1 + 5")
```

### Issue Description

Raises following exception: 
```
f .1 =a .1 +5
SyntaxError: invalid syntax
```

this applies to all prohibited characters in variable names. I have some "bicycle" solution for this issue (for "." only) for now:

```
def apply_formulas(data, formulas):
    literal = "arxhdkl_wqmasmdvcalsnd"
    columns = [name.replace(".", literal) for name in data.columns]
    data.columns = columns

    for formula in formulas:
        f = formula.replace(".", literal)
        data.eval(f, inplace=True)

    columns = [name.replace(literal, ".") for name in data.columns]
    data.columns = columns
    return data
```

I think that the problem lies in the fact that something like this happens inside the method:
```
df.f.1 = df.a.1 + 5 
```
instead
```
df["f.1"] = df["a.1"] + 5
```

### Expected Behavior
```
df.eval("f.1 = a.1 + 5")
```

I hope DataFrame.eval() will supports equation like below

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.147+
Version          : #1 SMP Sat Dec 10 16:00:40 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.5
numpy            : 1.22.4
pytz             : 2022.7.1
dateutil         : 2.8.2
pip              : 22.0.4
setuptools       : 57.4.0
Cython           : 0.29.33
pytest           : 3.6.4
hypothesis       : None
sphinx           : 3.5.4
blosc            : None
feather          : 0.4.1
xlsxwriter       : None
lxml.etree       : 4.9.2
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.9.5 (dt dec pq3 ext lo64)
jinja2           : 3.1.2
IPython          : 7.9.0
pandas_datareader: 0.9.0
bs4              : 4.6.3
bottleneck       : None
fsspec           : 2023.1.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.5.3
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : 0.17.9
pyarrow          : 9.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
sqlalchemy       : 1.4.46
tables           : 3.7.0
tabulate         : 0.8.10
xarray           : 2022.12.0
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.56.4

</details>

**Comment by ritikBhandari** [comment]
Hi @RinnetenseiQ,

So the problem with the code is that the column name "a.1" contains a period (.) character, which is a special character in pandas when used in column names. The period is used to separate levels in a hierarchical index.

If you want to use such names in the column, you need to enclose the column name in backticks to indicate that it is a literal column name.

Like this 
```df.eval("`a.1`+5")```

And also, eval() method does not create new columns in the original DF unless the expression is explicitly designed to do so. You can use this expression for much clarity though:

`df["f.1"] = df["a.1"] + 5`

**Comment by topper-123** [comment]
Yes, like @ritikBhandari says, the dot is used to access attributes, so if it exists in a name, the fix is to  surround the name  by backticks.

I'm closing this issue as wontfix.
