### ISSUE TITLE
DOC: pandas.DataFrame.to_csv

### ISSUE THREAD

**Issue by AlbrechtProud** [pandas-dev/pandas#51807]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html

### Documentation problem

As noted on Twitter, the lineterminator argument appears to be wrong in the documentation. For Read csv, "lineterminator" does not work, while "line_terminator" does as expected. Hence, I think the documentation is missing the underscore. 

### Suggested fix for documentation

Replace "lineterminator" with "line_terminator" in the docs.

**Comment by DeaMariaLeon** [comment]
Thank you for your issue @AlbrechtProud. You may want to upgrade the pandas version you have. On the current stable verison (1.5.3) there is this note for that parameter:

_Changed in version 1.5.0: Previously was line_terminator, changed for consistency with read_csv and the standard library ‘csv’ module._

What version do you have?

**Comment by phofl** [comment]
Yep lineterminator is the correct keyword
