### ISSUE TITLE
STYLE: Add auto fix to ruff

### ISSUE THREAD

**Issue by luke396** [pandas-dev/pandas#51814]
How about add fix/autofix ruff?

I recently worked on [STYLE enable ruff TCH](https://github.com/pandas-dev/pandas/issues/51740) and found that ruff reports some error could (eg: Trailing whitespace, ) been easily autofixed, by adding `--fix` (or more specific flags) as argument to config. 

I must admit that these errors can also be fixed manually. However, if the automation does not significantly slow down the process, why not let them be fixed automatically? It is worth noting that automatic fixes are still being developed and modified, and whether they should be used or not may require further discussion.

Some maybe related:
[ruff-tried-to-fix-something-but-it-broke-my-code?](https://beta.ruff.rs/docs/faq/#ruff-tried-to-fix-something-but-it-broke-my-code)
[Usage - Ruff](https://beta.ruff.rs/docs/usage/)
[Configuration - Ruff](https://beta.ruff.rs/docs/configuration/#command-line-interface)

**Comment by MarcoGorelli** [comment]
sure, if there's a way to not auto-fix E721, I'm all for it

**Comment by twoertwein** [comment]
ruff allows to black-list unfixable rules

```toml
unfixable = ["E721"]
```

**Comment by MarcoGorelli** [comment]
awesome! is there anything ruff can't do? 😄

**Comment by MarcoGorelli** [comment]
sure go ahead
