### ISSUE TITLE
API: parakeet backend for eval

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#5184]
this might be interesting as it allows jit optimizations but w/o major deps (like blaze/numba).

could be useful as a back end for eval

potentially could be used in apply as well

http://www.parakeetpython.com/

http://www.phi-node.com/2013/01/just-in-time-compilers-for-number.html

**Comment by chris-b1** [comment]
Looks like the parakeet project was eventually abandoned - https://github.com/iskandr/parakeet
