### ISSUE TITLE
DOC: Change color of sample plots for dark mode

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#51860]
xref #50936

There are some sample plots in our [getting started](https://pandas.pydata.org/preview/50936/docs/getting_started/index.html) docs that don't show properly when the dark theme of our site is enabled:

![Screenshot_20230309_123509](https://user-images.githubusercontent.com/10058240/224025101-60a702d7-306c-46c3-8366-38c195d34d2a.png)

We should change the colors so it displays correctly in both the light and dark themes. I assume the image is a svg and the best approach is to simply change the colors in it. But maybe it's autogenerated from pandas somehow, and it's better to change at the generation. @stijnvanhoey thoughts on the best approach?

**Comment by NumanIjaz** [comment]
take

**Comment by stijnvanhoey** [comment]
> I assume the image is a svg

The images are indeed svg. I would indeed just adjust the figures so they work for both dark/light mode

**Comment by Prashantkhobragade** [comment]
If the sample plot does not work well with the dark theme, you can try using a different plotting library that is more compatible with dark themes. For example, the `seaborn` plotting library has several built-in color schemes that work well with dark backgrounds.

**Comment by Aryasarkar008** [comment]
we can just use the seaborn library for better visualization. I would love to help out on this.

**Comment by stijnvanhoey** [comment]
The illustrations in the [getting started section](https://pandas.pydata.org/preview/50936/docs/getting_started/index.html) are created in inkscape and stored as svg-images and not created using a plot-library. I do think the easiest way is to update these so they work in both light/dark theme. E.g. also the black arrows in the illustrations are not working in the dark theme. I'm certainly willing to adjust this myself in the coming weeks. 

@datapythonista in case it is hard to make illustrations both work in light and dark theme, is there an option/admonition/code-snippet... to provide two images and switch them together with the dark/light switch?

**Comment by datapythonista** [comment]
In theory is supported, but I think someone gave it a try and couldn't get it working. I didn't check the details of the theme, but even if it's using html in the markdown, or a custom directive, I guess shouldn't be difficult to implement. But I think it's doable to have a single image working well for both themes.

**Comment by stijnvanhoey** [comment]
I've checked the [pydata-sphinx theme](https://pydata-sphinx-theme.readthedocs.io/en/v0.12.0/user_guide/styling.html#color-variables) information:

- If images doe not have a background, the theme will provide one when switching to dark theme
![image](https://user-images.githubusercontent.com/754862/226476727-37305e49-b1e5-409c-a886-3bdfe9108578.png)
@datapythonista  I think this would suffice?

- The theme provides a number of [css-variables](https://pydata-sphinx-theme.readthedocs.io/en/v0.12.0/user_guide/styling.html#color-variables) to make sure the theme-switch can be handled. e.g.
![image](https://user-images.githubusercontent.com/754862/226476880-762c7d5f-4877-40a4-b2f5-1cf9099c277f.png)
can be switched to 
![image](https://user-images.githubusercontent.com/754862/226476966-4a798c4e-179b-4154-b653-d478cdcd4105.png)
by using the `--pst-color-on-surface` and `--pst-color-on-background` css color variables and this adjusts on the theme-switch
![image](https://user-images.githubusercontent.com/754862/226477165-5dc08e2b-cb94-4298-a9e3-61a731f00051.png)

I'll prepare a PR which:
- double checks the images and make sure the background is applied in dark-mode and not hiding schema-elements
- adjusts the getting-started theming to make sure the existing css-variables are used in the getting started section (and will make the color more consistent to the rest of the docs)
