### ISSUE TITLE
PERF: Casting as type `string[pyarrow]` is significantly slower than casting as type `string`

### ISSUE THREAD

**Issue by ParthivNaresh** [pandas-dev/pandas#51885]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this issue exists on the main branch of pandas.

### Reproducible Example

```
import pandas as pd
import time

obs = 10_000_000

df = pd.DataFrame()
df["strings"] = [f"Some words {i}" for i in range(obs)]
df["more_strings"] = [f"other words {i}" for i in range(obs)]
df["emails"] = [f"{i}@gmail.com" for i in range(obs)]

start_time = time.perf_counter()
for col in df.columns:
    df[col] = df[col].astype("string[pyarrow]")
end_time = time.perf_counter()

print(f"Time elapsed: {end_time - start_time:0.6f} seconds")
=================================
Time elapsed: 4.533467 seconds
```

```
import pandas as pd
import time

obs = 10_000_000

df = pd.DataFrame()
df["strings"] = [f"Some words {i}" for i in range(obs)]
df["more_strings"] = [f"other words {i}" for i in range(obs)]
df["emails"] = [f"{i}@gmail.com" for i in range(obs)]

start_time = time.perf_counter()
for col in df.columns:
    df[col] = df[col].astype("string")
end_time = time.perf_counter()

print(f"Time elapsed: {end_time - start_time:0.6f} seconds")
=================================
Time elapsed: 1.993949 seconds
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.8.16.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.6.0
Version          : Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.23.5
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 67.5.1
pip              : 23.0.1
Cython           : None
pytest           : 7.0.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2023.3.0
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by ParthivNaresh** [comment]
I don't know if this is a known issue or if this is a non-issue but I was hoping for more clarity around expected behaviour, thank you!

**Comment by phofl** [comment]
Can you try on the rc? This shows the same runtime (more or less) for me.

Also, you'd have to set pd.options.mode.string_storage = "pyarrow" to get the equivalent strings, without this you get python strings

**Comment by ParthivNaresh** [comment]
I'm getting similar numbers from `2.0rc` as well, around a 125% slowing down when `string[pyarrow]` is used

**Comment by jorisvandenbossche** [comment]
I see a considerable slowdown with `string[pyarrow]` as well:

```
obs = 1_000_000
df = pd.DataFrame({"strings": [f"Some words {i}" for i in range(obs)]})

In [11]: %timeit df["strings"].astype("string[pyarrow]")
77.8 ms ± 4.02 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [12]: %timeit df["strings"].astype("string")
34.9 ms ± 2.11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Now, the reason is that we call our `ensure_string_array` method in both cases (doing the "generic python object -> string objects" conversion), and that is what takes up most of the time. And in the pyarrow case, we additionally have the `pyarrow.array` constructor (doing the "python string objects -> pyarrow array (contiguous buffer for the strings)" conversion). 

The pyarrow.array constructor is strict about only accepting actual string values, while in general in pandas you can pass anything and we will convert it to a string (if you specify the string dtype). So I don't think it is easy to avoid this extra cost in the case of "string[pyarrow]" if we want to keep that behaviour.
So in

**Comment by ParthivNaresh** [comment]
@jorisvandenbossche Gotcha thanks for the explanation. It seems like there's no way around that behaviour. Even if the `pyarrow.array` constructor wasn't strict about accepting actual string values, additional conversions would need to be done to make the data compatible which seems like extra steps just to end up with the same performance. Should this issue be closed?

**Comment by eivinder** [comment]
how do i print a pandas row containing a certain value
