### ISSUE TITLE
DEPR: DataFrame.swapaxes

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#51946]
This is listed in the general deprecation issue https://github.com/pandas-dev/pandas/issues/18262. 

Now that we have a max dimension of 2, i.e. DataFrame (while before you could have a 3D Panel or NDFrame), I don't think there is any use case for `swapaxes` where it's not exactly the same as `transpose()`. 
It's still implemented independently from `transpose()`, but I _think_ that `df.swapaxes(0, 1)` and `df.swapaxes(1, 0)` are the only two valid options and that gives exactly the same as a `transpose()` (you can do eg `df.swapaxes(0, 0)` which is a no-op, but this generalization doesn't really seem worth keeping it as a separate method, I would say)

So let's deprecate it? (in favor of `transpose()`)

**Comment by phofl** [comment]
Yeah I don't see a real use case for this either. +1

**Comment by luke396** [comment]
take

**Comment by rhshadrach** [comment]
+1

**Comment by rhshadrach** [comment]
A potential reason for this is so that `np.swapaxes(df)` works. See #57351. But I'm not sure that needs to be supported - why can't users just do `df.T`?
