### ISSUE TITLE
BUG: Comparisons and equality with pyarrow backend return pandas extension typed booleans instead of pyarrow booleans.

### ISSUE THREAD

**Issue by rohanjain101** [pandas-dev/pandas#51980]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> pd.options.mode.dtype_backend = 'pyarrow'
>>> a = pd.Series([True], dtype="bool[pyarrow]")
>>> b = pd.Series([False], dtype="bool[pyarrow]")
>>> a
0    True
dtype: bool[pyarrow]
>>> b
0    False
dtype: bool[pyarrow]
>>> a == b
0    False
dtype: boolean
>>> c = a== b
>>> c.dtype
BooleanDtype
>>> c.dtype.__module__
'pandas.core.arrays.boolean'
```

### Issue Description

The returned series is using pandas extension boolean typed series instead of arrow typed.

### Expected Behavior

I expect the series returned to be using the arrow boolean data type instead of pandas extension type.

### Installed Versions

<details>

>>> pd.show_versions()
C:\ps_0310_is\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit           : 1a2e300170efc08cb509a0b4ff6248f8d55ae777
python           : 3.8.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 2.0.0rc0
numpy            : 1.24.2
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 67.2.0
pip              : 22.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : 2023.2.0
fsspec           : 2023.3.0
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : None
qtpy             : None
pyqt5            : None
</details>

**Comment by mroeschke** [comment]
https://github.com/pandas-dev/pandas/pull/51987 was merged so, this will be fixed in the RC2 release
