### ISSUE TITLE
TYP: Make NDFrame Generic?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#52004]
ATM NDFrameT is bound to NDFrame and mypy thinks that NDFrame subclasses other than Series/DataFrame are possible.  This means that things like defining `index: AxisProperty` on NDFrame breaks the world.  AFAICT a significant number of our "type: ignore"s are related to the NDFrameT vs "Series | DataFrame" mismatch.

Is there some Protocol or Generic or something magic we can do to indicate that NDFrame is a base class that is only ever instantiated as Series | DataFrame?

If so I think there are a few more ignores that could be fixed by doing something similar with the Manager subclasses.

cc @twoertwein @simonjayhawkins

**Comment by twoertwein** [comment]
> Is there some Protocol or Generic or something magic we can do to indicate that NDFrame is a base class that is only ever instantiated as Series | DataFrame?

We could go from `TypeVar("NDFrameT" bound=NDFrame)` to  `TypeVar("FrameSeriesT", DataFrame, Series)` which would still allow sub-classes of either DataFrame or Series (but type checkers know that the object has all methods of either a DataFrame or a Series). Would that help?

One limitation of that might be that mypy/pyright probably do not like using `FrameSeriesT` when annotating `NDFrame` itself.

**Comment by jbrockmendel** [comment]
Closing as not actionable.
