### ISSUE TITLE
C engine parsing problem with botocore StreamingResponse and ISO-8859-1 encoding

### ISSUE THREAD

**Issue by ekk-0tsu** [pandas-dev/pandas#52039]
When `pandas.read_csv` is reading CSV from boto3 stream ([StreamResponse](https://github.com/boto/botocore/blob/d50986776c3d04ec9c2e60b7280ce192c7851ba3/botocore/response.py#L38)) with content encoded in ISO-8859-1 it producing `UnicodeDecodeError`. It happens to files only with this encoding stored at S3, but it potentially could happen to files with similar encodings.

```
stream_response = boto3.Object(bucket, key).get()

# Error occurs after calling this block
with pandas.read_csv(
      stream_response,
      chunksize=500,
      na_filter=False,
      index_col=False,
      dtype=str,
      encoding="ISO-8859-1",
      # Delimiter can be different, does not affect on result
      delimiter="\t",
) as reader:
    for df in reader:
         print(df)
```
```
File "/Users/john.doe/project/.venv/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 820, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 890, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1037, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1068, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1230, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas/_libs/parsers.pyx", line 1246, in pandas._libs.parsers.TextReader._string_convert
  File "pandas/_libs/parsers.pyx", line 1444, in pandas._libs.parsers._string_box_utf8
```
I tried to change encoding to many of possible ones, but no success. Changing of parsing engine to "python" or "pyarrow"
did not bring positive results. The first requires byte chunks to be decoded, and the second is less feature compatible now. So, I have to stick to "C" engine only for now.
One work-around is to read the whole stream and write its content into `BytesIO`, but for large files it is not the optimal solution.

Also to note: chunk size used by pandas for reading from buffer is 262144 bytes, but my files are 1/3 of this value in size. 
So, probably there should be no difference whether pandas reading and parsing bytes from `StreamResponse`, or `BytesIO` object for files less than or equal to this size.

I wonder if changing decoding to "utf-16" at Cython parser level will change this behavior, [here](https://github.com/pandas-dev/pandas/blob/4ef638aa0923f59d943f85746964513949fff8a8/pandas/_libs/parsers.pyx#L1499).

Perhaps there is a problem with `StreamingResponse`, but w.r.t to its API and what it's inherited from it does not seem so.
But, in general, it seems to be a bug at Cython parsing level, or, there is an implicit incompatibility for this type of stream.
```

**Comment by phofl** [comment]
Can you please provide something that is reproducible?

**Comment by phofl** [comment]
Public file would be good, local reproducer would be even better
