### ISSUE TITLE
BUG: Different result with ẞ in Series.str.upper when using Arrow string dtype vs pd.StringDtype() 

### ISSUE THREAD

**Issue by rohanjain101** [pandas-dev/pandas#52037]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> a = pd.Series(["ß"], dtype="string[pyarrow]")
>>> a.str.upper()
0    ẞ
```

### Issue Description

The result does not match the result produced match the result of pd.StringDtype(), which would produce:

>>> a_str = pd.Series(["ß"], dtype=pd.StringDtype())
>>> a_str.str.upper()
0    SS

Is this difference in Series.str.upper between the arrow type and pandas extension type intentional?

### Expected Behavior

a_str = pd.Series(["ß"], dtype=pd.StringDtype())
>>> a_str.str.upper()
0    SS
dtype: string

### Installed Versions

<details>

>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : 1a2e300170efc08cb509a0b4ff6248f8d55ae777
python           : 3.8.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 2.0.0rc0
numpy            : 1.24.2
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 67.2.0
pip              : 22.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : 2023.2.0
fsspec           : 2023.3.0
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : None
qtpy             : None
pyqt5            : None
>>>

</details>

**Comment by rohanjain101** [comment]
FWIW, the python upper method would produce "SS" which matches the pandas extension type:

>>> char = "ß"
>>> char.upper()
'SS'
>>>

**Comment by rohanjain101** [comment]
@mroeschke do you mean creating an issue on the arrow github under the python category? Or is there a different (dedicated for pyarrow) place I should report this?

**Comment by mroeschke** [comment]
> do you mean creating an issue on the arrow github under the python category?

Correct, there is one tracker for all language implementations: https://github.com/apache/arrow/issues/new/choose

BTW thanks for all the pyarrow testing. We're really eager to see the use cases and also improve pyarrow so pandas gets the improvements as well.

**Comment by rohanjain101** [comment]
Created the issue: https://github.com/apache/arrow/issues/34599. And no problem,  happy to help and really excited to see pandas supporting arrow as a backend.

**Comment by rohanjain101** [comment]
Based on the issue, looks like the difference is intentional in the library arrow relies on, so not sure if maybe the docs should be updated that it might not necessarily match str.upper with the arrow type.

**Comment by randolf-scholz** [comment]
Python's `upper` is outdated here. `SS` is the old way of capitalizing `ß` in German. However, in 2008 the new unicode symbol `ẞ` was introduces and became a part of the [ISO/IEC 10646 standard](https://en.wikipedia.org/wiki/Universal_Coded_Character_Set). Since 2017, `ẞ` is the official capitalized version of `ß` according to official German Orthography. [wikipedia: Großes ß](https://de.wikipedia.org/wiki/Gro%C3%9Fes_%C3%9F#:~:text=Das%20gro%C3%9Fe%20%E1%BA%9E%20(auch%3A%20gro%C3%9Fes,%C3%9F%20durch%20SS%20(STRASSE).)

**Comment by mroeschke** [comment]
Seems like this is an upstream issue, going to close as special casing in pandas isn't appropriate
