### ISSUE TITLE
BUG: Cumprod failing with type float[pyarrow]

### ISSUE THREAD

**Issue by misantroop** [pandas-dev/pandas#52085]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
ser = pd.Series({
    1: 1.,
    2: 2.
})
ser = ser.astype('float[pyarrow]')
ser.cumprod()
```

### Issue Description

Cumprod failing, issue or cumprod only meant to be used with np?

```
File ~/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pandas/core/arrays/base.py:1406, in ExtensionArray._accumulate(self, name, skipna, **kwargs)
   1376 def _accumulate(
   1377     self, name: str, *, skipna: bool = True, **kwargs
   1378 ) -> ExtensionArray:
   1379     """
   1380     Return an ExtensionArray performing an accumulation operation.
   1381 
   (...)
   1404     NotImplementedError : subclass does not define accumulations
   1405     """
-> 1406     raise NotImplementedError(f"cannot perform {name} with type {self.dtype}")

NotImplementedError: cannot perform cumprod with type float[pyarrow]
```

### Expected Behavior

Cumprod result.

### Installed Versions

<details>
Built from latest from 4 hours ago (b5aec87d301b180a833bfb2860fb34313e1e9190)
</details>

**Comment by phofl** [comment]
Hi, thanks for your report. This isn't implemented on the arrow side yet.
