### ISSUE TITLE
BUG: AttributeError raised with pd.concat between a None and Timestamp

### ISSUE THREAD

**Issue by christensendaniel** [pandas-dev/pandas#52093]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
data = [{'A':None}]
df = pd.DataFrame(data)
data_2 = [{'A': pd.to_datetime("1990-12-20 00:00:00+00:00")}]
df_2 = pd.DataFrame(data_2)
pd.concat([df, df_2])
```

### Issue Description

When running `pd.concat` between two DataFrame: one with `None` as an object, and a second, with a timezone-enabled `pandas._libs.tslibs.timestamps.Timestamp` an `AttributeError` is raised.

```
AttributeError: 'NoneType' object has no attribute 'value'
```

### Expected Behavior

I expect this to return the same response when a non-timezone-enabled `pandas._libs.tslibs.timestamps.Timestamp`, which is the `None` changes to a `pd.NaT`

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : c2a7f1ae753737e589617ebaaff673070036d653
python           : 3.11.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        :
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.0rc1
numpy            : 1.24.2
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 65.5.1
pip              : 22.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : None
qtpy             : None
pyqt5            : None

**Comment by willjhenry** [comment]
ran into this bug this AM in pandas 2.0.1

**Comment by jbrockmendel** [comment]
PR to address this is welcome.

**Comment by srkds** [comment]
take

**Comment by SultanOrazbayev** [comment]
Hello, sorry, but a variation of this error [is still reproducible](https://stackoverflow.com/a/77857060/10693596):

Here's a small example to reproduce:

```python
from datetime import datetime, timezone

from pandas import DataFrame, concat

df1 = DataFrame({"c": [None, None]})
df2 = DataFrame({"c": [None, datetime.now(tz=timezone.utc)]})
concat([df1, df2], ignore_index=True)
```

The above raises `AttributeError`:
```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[173], line 7
      5 df1 = DataFrame({"c": [None, None]})
      6 df2 = DataFrame({"c": [None, datetime.now(tz=timezone.utc)]})
----> 7 concat([df1, df2], ignore_index=True)

File ~/python3.11/site-packages/pandas/core/reshape/concat.py:393, in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    378     copy = False
    380 op = _Concatenator(
    381     objs,
    382     axis=axis,
   (...)
    390     sort=sort,
    391 )
--> 393 return op.get_result()

File ~/python3.11/site-packages/pandas/core/reshape/concat.py:680, in _Concatenator.get_result(self)
    676             indexers[ax] = obj_labels.get_indexer(new_labels)
    678     mgrs_indexers.append((obj._mgr, indexers))
--> 680 new_data = concatenate_managers(
    681     mgrs_indexers, self.new_axes, concat_axis=self.bm_axis, copy=self.copy
    682 )
    683 if not self.copy and not using_copy_on_write():
    684     new_data._consolidate_inplace()
...
-> 2294         i8values = np.full(shape, fill_value._value)
   2295         return DatetimeArray(i8values, dtype=dtype)
   2297     elif is_1d_only_ea_dtype(dtype):

AttributeError: 'NoneType' object has no attribute '_value'
```

The solution is to explicitly assign dtype to the column containing all None values:

```python
from datetime import datetime, timezone

from pandas import DataFrame, concat

df1 = DataFrame({"c": [None, None]}).astype({"c": "datetime64[ns, UTC]"})
df2 = DataFrame({"c": [None, datetime.now(tz=timezone.utc)]})
concat([df1, df2], ignore_index=True)
```
