### ISSUE TITLE
DOC: MonthBegin suggestion to get start of current month not quite right?

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#52106]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.tseries.offsets.MonthBegin.html?highlight=monthbegin#pandas.tseries.offsets.MonthBegin

### Documentation problem

The docs for [MonthEnd](https://pandas.pydata.org/docs/dev/reference/api/pandas.tseries.offsets.MonthEnd.html?highlight=monthend#pandas.tseries.offsets.MonthEnd) say

> To get the end of the current month pass the parameter n equals 0.

This is correct:
```python
In [51]: pd.Timestamp('2023-03-21') + pd.offsets.MonthEnd(n=0)
Out[51]: Timestamp('2023-03-31 00:00:00')
```

But for `[MonthBegin](https://pandas.pydata.org/docs/dev/reference/api/pandas.tseries.offsets.MonthBegin.html?highlight=monthbegin#pandas.tseries.offsets.MonthBegin), it says

> To get the start of the current month pass the parameter n equals 0.

I think this is not quite right:
```python
In [58]: pd.Timestamp('2023-03-21') + pd.offsets.MonthBegin(n=0)
Out[58]: Timestamp('2023-04-01 00:00:00')
```

### Suggested fix for documentation

I would have expected `- pd.offsets.MonthBegin(n=0)` to go to the beginning of the current month, but it doesn't:
```python
In [64]: pd.Timestamp('2023-03-21') - pd.offsets.MonthBegin(n=0)
Out[64]: Timestamp('2023-04-01 00:00:00')
```

I'm not sure if this is a bug, I've not looked closely enough.

I think I'd suggest:
- removing the "To get the start of the current month pass the parameter n equals 0." suggestion
- adding an example of using `+ pd.offsets.MonthBegin() - pd.offsets.MonthBegin()` to get the start of the current month

cc @natmokval in case you wanted to make a PR (no blame of course! I should have noticed this when reviewing)

**Comment by MarcoGorelli** [comment]
Same story in https://github.com/pandas-dev/pandas/issues/52105

I'll take a look this week about whether `- MonthBegin(n=0)` doesn't go to the beginning of the current month is a bug or not, that'll inform which change needs making to the docs

**Comment by pranav-ravuri** [comment]
Hi, can I take up as my first issue to update the docs. Thankyou

**Comment by MarcoGorelli** [comment]
go ahead, thanks!

**Comment by pranav-ravuri** [comment]
Hi, @MarcoGorelli quick question, I have been reading the pandas contributor docs but I am unable to find a guideline to name my local (forked) branch to add this change, could you please help me with that. Thanks

**Comment by MarcoGorelli** [comment]
hey - it doesn't really matter what you name your branch, up to you

**Comment by pranav-ravuri** [comment]
Hi, I updated the `MonthBegin` docstring to
``` python
    """
    DateOffset of one month at beginning.

    MonthBegin goes to the next date which is a start of the month.

    See Also
    --------
    :class:`~pandas.tseries.offsets.DateOffset` : Standard kind of date increment.

    Examples
    --------
    >>> ts = pd.Timestamp(2022, 11, 30)
    >>> ts + pd.offsets.MonthBegin()
    Timestamp('2022-12-01 00:00:00')

    >>> ts = pd.Timestamp(2022, 12, 1)
    >>> ts + pd.offsets.MonthBegin()
    Timestamp('2023-01-01 00:00:00')

    If you want to get the start of the current month:

    >>> ts = pd.Timestamp(2022, 12, 1)
    >>> pd.offsets.MonthBegin().rollback(ts)
    Timestamp('2022-12-01 00:00:00')
    """
    _prefix = "MS"
    _day_opt = "start"
```

and `MonthEnd` docstring to 
``` python
    """
    DateOffset of one month end.

    MonthEnd goes to the next date which is an end of the month.

    See Also
    --------
    :class:`~pandas.tseries.offsets.DateOffset` : Standard kind of date increment.

    Examples
    --------
    >>> ts = pd.Timestamp(2022, 1, 30)
    >>> ts + pd.offsets.MonthEnd()
    Timestamp('2022-01-31 00:00:00')

    >>> ts = pd.Timestamp(2022, 1, 31)
    >>> ts + pd.offsets.MonthEnd()
    Timestamp('2022-02-28 00:00:00')

    If you want to get the end of the current month pass the parameter n equals 0:

    >>> ts = pd.Timestamp(2022, 1, 31)
    >>> pd.offsets.MonthEnd().rollforward(ts)
    Timestamp('2022-01-31 00:00:00')
    """
    _period_dtype_code = PeriodDtypeCode.M
    _prefix = "M"
    _day_opt = "end"
```

So, is this okay and are there any more docstrings I need to update. On a side note out of curiosity what is 
```
_period_dtype_code = PeriodDtypeCode.M
    _prefix = "M"
    _day_opt = "end"
```
at the end of docstring?

**Comment by MarcoGorelli** [comment]
>  If you want to get the end of the current month pass the parameter n equals 0:

This needs updating, but the rest looks good!

Those attributes are used internally in some other places (but there is an open PR to change `'M'` to `'ME'`, as `'M'` meaning "month end" is very confusing)

**Comment by pranav-ravuri** [comment]
> > If you want to get the end of the current month pass the parameter n equals 0:
> 
> This needs updating, but the rest looks good!
> 
> Those attributes are used internally in some other places (but there is an open PR to change `'M'` to `'ME'`, as `'M'` meaning "month end" is very confusing)

so, are they like aliases for some sorts? could you please direct me to the concept being used here internally. On the other note, I have updated `MonthBegin` and `MonthEnd` doc string, but as a sanity, I checked whether, `BMonthBegin` and `BMonthEnd` had the same issue at it has the same issue

``` Python console
>>> pd.Timestamp('2023-03-21') + pd.offsets.BMonthEnd(n=0)
>>> Timestamp('2023-03-31 00:00:00') # okay
>>> pd.Timestamp('2023-03-21') + pd.offsets.BMonthBegin(n=0)
>>> Timestamp('2023-04-03 00:00:00') # not okay
```
sould I update these docs also?

**Comment by MarcoGorelli** [comment]
> sould I update these docs also?

yes please! as well as any others which you find
