### ISSUE TITLE
Validate that MultiIndex labels are Int64 type when not called internally.

### ISSUE THREAD

**Issue by jtratner** [pandas-dev/pandas#5212]
Right now you could create MI with weird types and it doesn't error out. More difficult to do effectively when MI is an ndarray subclass (because there are so many different ways to instantiate a MultiIndex). Will fix in Index refactor (just want to remember to do so).

**Comment by toobaz** [comment]
@jtratner does #19074 change anything?

**Comment by mroeschke** [comment]
It appears that `codes` are dtyped resized internally 

```
In [69]: pd.MultiIndex(levels=mi.levels, codes=np.array([[0., 0., 1., 1.], [1., 0., 1., 0.]], dtype=np.in
    ...: t32)).codes[0]
Out[69]: array([0, 0, 1, 1], dtype=int8)
```

So this is probably not an issue anymore. Closing
