### ISSUE TITLE
BUG: Using set_levels with a Categorical on a mutliindex isn't preserving the dtype

### ISSUE THREAD

**Issue by caneff** [pandas-dev/pandas#52125]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
index = pd.MultiIndex.from_arrays([[1,2]])
index.set_levels(pd.Categorical([1,2]),level=0).levels[0]
```

### Issue Description

When I set the level of a MultiIndex I expect it to be the type I set it to. But it gets overwritten to a more basic class:

```python
In [24]: index = pd.MultiIndex.from_arrays([[1,2]])
    ...: index.set_levels(pd.Categorical([1,2]),level=0).levels[0]
Out[24]: Index([1, 2], dtype='int64')
```

Even overwriting with the exact same thing still does it:

```python
In [43]: index.set_levels(pd.Categorical([1,2]),level=0).levels[0]
Out[43]: Index([1, 2], dtype='int64')
```

### Expected Behavior

```python
index = pd.MultiIndex.from_arrays([pd.Categorical([1,2]),[3,4]])
index.set_levels(pd.Categorical([1,2]),level=0).levels[0]
```

Expected
```python
CategoricalIndex([1, 2], categories=[1, 2], ordered=False, dtype='category')
```

Actual
```python
Index([1, 2], dtype='int64')
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 5c155883fdc5059ee7e21b20604a021d3aa92b01
python           : 3.10.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.19.11-1rodete1-amd64
Version          : #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1rodete1 (2022-10-31)
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.1.0.dev0+284.g5c155883fd
numpy            : 1.21.5
pytz             : 2022.6
dateutil         : 2.8.2
setuptools       : 65.6.3
pip              : 22.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.10.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : 1.0.9
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None

</details>

**Comment by phofl** [comment]
Hi, thanks for your report. For now you can use ``pd.CategoricalIndex`` instead of ``pd.Categorical``
