### ISSUE TITLE
DOC: broken link in user guide/style

### ISSUE THREAD

**Issue by phlummox** [pandas-dev/pandas#52157]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/user_guide/style.html

### Documentation problem

The link to an online notebook-viewer, here –

https://github.com/pandas-dev/pandas/blob/3f2b18aed1468d3643bf638f7859cacf3141c8f4/doc/source/user_guide/style.ipynb?short_path=90e57ad#L10

and here –

https://github.com/pandas-dev/pandas/blob/3f2b18aed1468d3643bf638f7859cacf3141c8f4/doc/source/user_guide/style.ipynb?short_path=90e57ad#L32

– seems to be broken.

It points to the host nbviewer.ipython.org, which, though alive and responding to HTTP requests, keeps sending back 301 redirects which just point to itself, resulting in an endless loop.

### Suggested fix for documentation

I assume the correct URL should point to https://nbviewer.org, which is up and working.

So the new URL would be https://nbviewer.org/github/pandas-dev/pandas/blob/main/doc/source/user_guide/style.ipynb.

This URL would be better than the existing documentation's because it works.

**Comment by eirinikafourou** [comment]
take

**Comment by topper-123** [comment]
Yes, absolutely. We’re happy to receive contribtutions.
