### ISSUE TITLE
DOC: update SemiMonthEnd examples to not use (n=0)

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#52169]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.tseries.offsets.SemiMonthEnd.html

### Documentation problem

Similar to https://github.com/pandas-dev/pandas/issues/52106, `SemiMonthEnd` also needs updating

### Suggested fix for documentation

cc @pranav-ravuri in case you wanted to submit a PR for this one too

Else I'll do it tomorrow

**Comment by pranav-ravuri** [comment]
Appreciate the offer but unfortunately I don't have access to my laptop for a couple of days, so best you finish this yourself. I will be actively searching searching for new issues where I can contribute to once I am reunited with my laptop! Thank you

**Comment by MarcoGorelli** [comment]
sure will do, thanks for the quick reply
