### ISSUE TITLE
BUG: read_html reads <style> element text

### ISSUE THREAD

**Issue by m-ganko** [pandas-dev/pandas#52197]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

html_table = """
<table>
    <tr>
        <th>
            <style>.style</style>
            A
            </th>
        <th>B</th>
    </tr>
    <tr>
        <td>A1</td>
        <td>B1</td>
    </tr>
    <tr>
        <td>A2</td>
        <td>B2</td>
    </tr>
</table>
"""
pd.read_html(html_table)[0]

  .style  A   B
0        A1  B1
1        A2  B2
```

### Issue Description

When table cell contains `<style>` element pandas reads it into DataFrame.

### Expected Behavior

I think in most cases we don't want this behavior. I propose to control this using existing argument `displayed_only` (since `<style>` element is not displayed) or adding new one e.g. `skip_style_elements`.  

### Installed Versions

<details>
'2.1.0.dev0+280.g0755f22017.dirty'
</details>

**Comment by zbreger** [comment]
take
