### ISSUE TITLE
QST: The end of life for Pandas 1.4.4

### ISSUE THREAD

**Issue by kakiuchis** [pandas-dev/pandas#52244]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/75859346/the-end-of-life-for-pandas-1-4-4

### Question about pandas

Can you tell me when the end of life for Pandas 1.4.4 will be? If it has not been decided, I would appreciate it if you could let me know that it is undecided.

I looked in the official documentation but could not find any information. https://pandas.pydata.org/docs/dev/whatsnew/v1.4.4.html

**Comment by MarcoGorelli** [comment]
hi @kakiuchis 

the 1.4.x series is no longer going to be updated, if that's what you're asking

**Comment by jbrockmendel** [comment]
There are no more releases in the 1.4.x series planned.

**Comment by MarcoGorelli** [comment]
closing then

**Comment by kakiuchis** [comment]
Thank you very much  @MarcoGorelli @jbrockmendel 
Sorry, I didn't ask the question properly.
I want to know when support for Pandas 1.4.4 will expire.

**Comment by MarcoGorelli** [comment]
what do you mean by expire?

**Comment by kakiuchis** [comment]
I just realized that end-of-life means "no further changes can be pushed to it". 
You already taught me that.
Thank you!
Sorry for taking your time.
