### ISSUE TITLE
DOC: Inappropriate bolding in `pandas.DataFrame.agg`

### ISSUE THREAD

**Issue by luke396** [pandas-dev/pandas#52253]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.agg.html

### Documentation problem

<img width="512" alt="image" src="https://user-images.githubusercontent.com/77875500/228106644-b00fc62b-c993-4203-b5ee-46a265667d7f.png">

Here, it seems that the rendering is not appropriate (inappropriate bolding).

### Suggested fix for documentation

Perhaps the parts under `Return` that do not belong to it should be unbolded, or the paragraph layout should be adjusted accordingly.

Maybe related:
https://pandas.pydata.org/docs/dev/reference/api/pandas.Series.agg.html

**Comment by futureprogrammer360** [comment]
The bolding is also present in https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.aggregate.html

**Comment by futureprogrammer360** [comment]
I'm willing to work on this after the issue is confirmed and the desired behavior is determined.

**Comment by topper-123** [comment]
This does indeed look wrong, so can confirm. 

@futureprogrammer360, 👍 if you want to take this. The desired behavior is to have more sensibly bolded text. Now how to figure out this does it wrong...

**Comment by futureprogrammer360** [comment]
take
