### ISSUE TITLE
DOC: read_csv with skiprows parameter skips from current position, not from start of file

### ISSUE THREAD

**Issue by Black-Maille** [pandas-dev/pandas#52270]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.read_csv.html

### Documentation problem

According to documentation, skiprows parameter skips row from the beginning of the file, which is not the actual behaviour.
Actually, it skips from the current position within the file, so e.g. after a readline() command, skiprows=1 will lead to line 3 being the first to be read.
I checked this with Pandas 1.3 (unfortunately, I am stuck on this version for now), but the documentation has not changed in this regard to the current version.
I am assuming the header parameter has similar issues.

### Suggested fix for documentation

Current text:
Line numbers to skip (0-indexed) or number of lines to skip (int) at the start of the file.

Proposed change:
Line numbers to skip (0-indexed) or number of lines to skip (int) from the current position within the file (at the start of the file if freshly opened).

**Comment by DeaMariaLeon** [comment]
What commands are you using exactly? Normally you read your file with read_csv once, you get an object and that's it. You manipulate the DataFrame you get, and don't use read_csv again until you need to open another file.

**Comment by mroeschke** [comment]
Closing as a usage question
