### ISSUE TITLE
BUG: Cannot access Timedelta properties with Arrow Backend

### ISSUE THREAD

**Issue by rohanjain101** [pandas-dev/pandas#52284]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> td = pd.Series([pd.Timedelta(seconds=30)], dtype=pd.ArrowDtype(pa.duration("us")))
>>> td
0    0:00:30
dtype: duration[us][pyarrow]
>>> td.dt.seconds
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ps_0310_is\lib\site-packages\pandas\core\generic.py", line 5973, in __getattr__
    return object.__getattribute__(self, name)
  File "C:\ps_0310_is\lib\site-packages\pandas\core\accessor.py", line 224, in __get__
    accessor_obj = self._accessor(obj)
  File "C:\ps_0310_is\lib\site-packages\pandas\core\indexes\accessors.py", line 577, in __new__
    raise AttributeError("Can only use .dt accessor with datetimelike values")
AttributeError: Can only use .dt accessor with datetimelike values
>>>
```

### Issue Description

.dt should be supported with datetime and timedeltas. With numpy, the code above would work.

### Expected Behavior

```
>>> td = pd.Series([pd.Timedelta(seconds=30)])
>>> td.dt.seconds
0    30
dtype: int32
>>>
```

### Installed Versions

<details>

>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : 1a2e300170efc08cb509a0b4ff6248f8d55ae777
python           : 3.8.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 2.0.0rc0
numpy            : 1.24.2
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 67.2.0
pip              : 22.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : 2023.2.0
fsspec           : 2023.3.0
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : None
qtpy             : None
pyqt5            : None
>>>

</details>

**Comment by mroeschke** [comment]
Closing as awaiting an implementation in https://github.com/apache/arrow/issues/33962

**Comment by mattharrison** [comment]
Just going back through my bug list. Is it valid to close this as `.dt` is still missing in the 2.2rc0?

**Comment by mroeschke** [comment]
The project generally closes issues that are due to upstream issues (i.e. no pyarrow implementation) since there's no immediate pandas action. Once there's a pyarrow implementation, we can reopen to signal a pandas-actionable issue

**Comment by mattharrison** [comment]
Thanks for the clarification.

**Comment by mroeschke** [comment]
Actually, I can submit a PR to make this dispatch to numpy for now until there is this functionality on the pyarrow side.

Thanks for taking the time to test out pyarrow functionality for Effective Pandas
