### ISSUE TITLE
BUG: `pd.TimeStamp` & `pd.Timedelta` not always adhering to `unit` parameter in `pandas-2.0`

### ISSUE THREAD

**Issue by galipremsagar** [pandas-dev/pandas#52286]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> x = 340.3333333333333
>>> pd.Timestamp(x, unit='us')
Timestamp('1970-01-01 00:00:00.000340333')
>>> pd.Timestamp(x, unit='us').unit
'ns'
>>> pd.Timestamp(x, unit='us').as_unit('us')
Timestamp('1970-01-01 00:00:00.000340')
>>> pd.Timestamp(x, unit='us').as_unit('us').unit
'us'
```

### Issue Description

When creating a `pd.Timestamp` & `pd.Timedelta` with a specific `unit`, the resulting `Timestamp` seems to be always of unit `ns`. We are having to perform `as_unit('us')` to retrieve the desired result.

### Expected Behavior

```python
>>> pd.Timestamp(x, unit='us')
Timestamp('1970-01-01 00:00:00.000340')
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : c2a7f1ae753737e589617ebaaff673070036d653
python           : 3.10.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-76-generic
Version          : #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.0rc1
numpy            : 1.23.5
pytz             : 2023.2
dateutil         : 2.8.2
setuptools       : 67.6.0
pip              : 23.0.1
Cython           : 0.29.33
pytest           : 7.2.2
hypothesis       : 6.70.1
sphinx           : 5.3.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.11.0
pandas_datareader: None
bs4              : 4.12.0
bottleneck       : None
brotli           : 
fastparquet      : None
fsspec           : 2023.3.0
gcsfs            : None
matplotlib       : None
numba            : 0.56.4
numexpr          : None
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : 2023.3.0
scipy            : 1.10.1
snappy           : 
sqlalchemy       : 1.4.46
tables           : None
tabulate         : 0.9.0
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : None
qtpy             : None
pyqt5            : None

</details>

**Comment by jbrockmendel** [comment]
The "unit" keyword describes how the input is interpreted, not how the result is stored internally (which the .unit attribute represents).  The overlapping naming is unfortunate.

cc @MarcoGorelli

**Comment by mroeschke** [comment]
I forgot if this was discussed, but is it possible if a user passes a numeric + unit to automatically _also_ store the representation in that unit?

**Comment by jbrockmendel** [comment]
> is it possible if a user passes a numeric + unit to automatically also store the representation in that unit?

For units that we support, yes.  For minute and lower we'd default back to seconds.  I'd be on board with this.

**Comment by mroeschke** [comment]
> For units that we support, yes. For minute and lower we'd default back to seconds. I'd be on board with this.

Likewise, makes sense to me

**Comment by jbrockmendel** [comment]
OK with putting this in 2.0?

**Comment by mroeschke** [comment]
Yes definitely

**Comment by MarcoGorelli** [comment]
> OK with putting this in 2.0?

totally - marking as blocker then if that's OK?

**Comment by jbrockmendel** [comment]
Implementing this I now remember why we didn't do it already: it introduces possibly-unwanted rounding in float cases.  i.e `Timestamp(1.5, unit="s)` drops the half-second.  We have 6 tests `TestTimestamp::test_unit` that this breaks.

**Comment by mroeschke** [comment]
> totally - marking as blocker then if that's OK?

IMO I don't think this should be a strict blocker for 2.0 but a nice to fix/document
