### ISSUE TITLE
BUG: AttributeError: 'ArrowTemporalProperties' object has no attribute 'year'

### ISSUE THREAD

**Issue by char101** [pandas-dev/pandas#52321]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.
- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
from datetime import datetime

s = pd.Series([datetime.now()], dtype='date32[pyarrow]')
s.dt.day
Out[17]: 
0    31
dtype: int64[pyarrow]

s.dt.month
Out[18]: 
0    3
dtype: int64[pyarrow]

s.dt.year
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [19], line 1
----> 1 s.dt.year

AttributeError: 'ArrowTemporalProperties' object has no attribute 'year'
```

### Issue Description

Hi,

Why isn't `year` available as a property of `.dt` of a `date32`/`date64` pyarrow series, although `day` and `month` is available? I have checked and there is a compute pyarrow function for year.

### Expected Behavior

Can access `year` via `dt` of a `date32`/`date64` pyarrow series.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : ceef0da443a7bbb608fb0e251f06ae43a809b472
python           : 3.11.1.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19043
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_Indonesia.1252

pandas           : 2.1.0.dev0+368.gceef0da443
numpy            : 1.24.2
pytz             : 2022.6
dateutil         : 2.8.2
setuptools       : 65.6.3
pip              : 23.0.1
Cython           : 0.29.32
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.2
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.9.5
jinja2           : 3.1.2
IPython          : 8.6.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.7
brotli           : 1.0.9
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.1.0
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : 1.4.45
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
zstandard        : None
tzdata           : 2022.6
qtpy             : 2.3.0
pyqt5            : None

</details>

**Comment by char101** [comment]
Looks like these functions are implemented yet in the ArrowExtensionArray class

```
iso_week(values, /, *[, memory_pool])
iso_year(values, /, *[, memory_pool])
millisecond(values, /, *[, memory_pool])
subsecond(values, /, *[, memory_pool])
us_week(values, /, *[, memory_pool])
us_year(values, /, *[, memory_pool])
week(values, /, *[, week_starts_monday, ...])
year(values, /, *[, memory_pool])
year_month_day(values, /, *[, memory_pool])
```

**Comment by jdb78** [comment]
'days' etc are also missing for time deltas. Both should be easy to add and they are likely to break a lot of code if they are missing.

**Comment by MarcoGorelli** [comment]
thanks for the report 

> Why isn't year available as a property of .dt of a date32/date64 pyarrow series, although day and month is available? 

quite a lot still needs doing for pyarrow to be complete - if you're interested in helping out, that'd be fantastic, here's the contributing guide https://pandas.pydata.org/docs/dev/development/contributing.html

**Comment by mroeschke** [comment]
> Looks like these functions haven't been implemented yet in the ArrowExtensionArray class

Note not all pyarrow compute functions have related `dt` accessor methodes

> 'days' etc are also missing for time deltas. Both should be easy to add and they are likely to break a lot of code if they are missing.

Pyarrow compute functions don't work on duration types currently https://github.com/pandas-dev/pandas/issues/52284
