### ISSUE TITLE
BUG: Unexpected behauvior interpolate limit with time and direction "both"

### ISSUE THREAD

**Issue by bartvaneswhiffle** [pandas-dev/pandas#52322]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
from io import StringIO

import pandas as pd


csv = """time,a,b
2021-01-01 00:00:00,0,7
2021-01-01 01:00:00,4,11
2021-01-01 01:30:00,6,12"""

df = pd.read_csv(StringIO(csv), sep=",", parse_dates=["time"])
df = df.set_index("time")
print(df)
df = df.resample("15T").interpolate(
                method="time", limit=1, limit_direction="both"
            )

print(df)
```

### Issue Description

This does interpolate the gap bigger than 1 nan?

### Expected Behavior

                       a     b
time                          
2021-01-01 00:00:00  0.0   7.0
2021-01-01 00:15:00  NaN   NaN
2021-01-01 00:30:00  NaN   NaN
2021-01-01 00:45:00  NaN   NaN
2021-01-01 01:00:00  4.0  11.0
2021-01-01 01:15:00  5.0  11.5
2021-01-01 01:30:00  6.0  12.0

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.10.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.19.0-38-generic
Version          : #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.24.2
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 65.6.3
pip              : 23.0.1
Cython           : None
pytest           : 7.2.1
hypothesis       : None
sphinx           : 6.1.3
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.0
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.1.1
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 2022.11.0
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

**Comment by MarcoGorelli** [comment]
thanks for the report, could you put a descriptive title pleasE?

**Comment by liang3zy22** [comment]
I have run the reproducing steps. I have got following result:
```
In [9]: print(df)
                       a     b
time                          
2021-01-01 00:00:00  0.0   7.0
2021-01-01 00:15:00  1.0   8.0
2021-01-01 00:30:00  NaN   NaN
2021-01-01 00:45:00  3.0  10.0
2021-01-01 01:00:00  4.0  11.0
2021-01-01 01:15:00  5.0  11.5
2021-01-01 01:30:00  6.0  12.0
```

So the a, b values in 2-4 rows must be NaN?

**Comment by adityaraute** [comment]
What's the plan here??

**Comment by MarcoGorelli** [comment]
Not sure I follow the issue - isn't this expected? You've said that `limit=1`, and `direction='both'`, so one `nan` was interpolated in both directions

I may be misunderstanding though, so putting 'closing candidate' for now

**Comment by bartvaneswhiffle** [comment]
Allright, it is indeed not a bug. I now understand how this is implemented this way (not sure when this is usefull), the documentation could be more clear.. I would expect having a limit in a interpolation to skip gaps bigger than the limit.
