### ISSUE TITLE
DOC: fixup formatting of docstring of DateOffset

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#52325]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.tseries.offsets.DateOffset.html

### Documentation problem

The docstring formatting looks wrong, some of it should probably render as code, given how it's written

This is the part of code you need to modify:

https://github.com/pandas-dev/pandas/blob/2f8b190f9cf546dd62590259c4992462aaa213f6/pandas/_libs/tslibs/offsets.pyx#L1349-L1367

### Suggested fix for documentation

Render the code example as code

You should be able to build it by doing
```
python make.py --single pandas.tseries.offsets.DateOffset
```
from the `doc` folder

**Comment by choudharynishu** [comment]
Can I try taking on this issue?

**Comment by MarcoGorelli** [comment]
sure thing, thanks!
