### ISSUE TITLE
API: rename DataFrame.applymap -> DataFrame.map

### ISSUE THREAD

**Issue by topper-123** [pandas-dev/pandas#52353]
I propose deprecating `DataFrame.applymap` and move its functionality to a new `DataFrame.map` method. The name `map` will better communicate that this is the `DataFrame` equivalent of `Series.map`. The current name can IMO be a bit confusing because the name contains both `"apply"` and `"map"`, while just having `"map"` is clearer IMO.
 
See a discussion on this [here](https://github.com/pandas-dev/pandas/issues/52140#issuecomment-1482789939).

CC @rhshadrach

**Comment by TeoSkondras** [comment]
take

**Comment by topper-123** [comment]
Hi @TeoSkondras. Thanks for wanting take take this, but I've made a branch already that is about to be ready to push to the pandas repository, so maybe a not a good use of time to make a second pull requests om this.

**Comment by attack68** [comment]
If this gets picked up pls ping me, since Styler.applymap would probably be better off remaining synchronised.

**Comment by topper-123** [comment]
This has been merged now in #52364 @attack68.
