### ISSUE TITLE
ENH: add `engine_kwargs` to DataFrame.to_excel

### ISSUE THREAD

**Issue by rmhowe425** [pandas-dev/pandas#52368]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Currently the `DataFrame.to_excel` method does not allow users to pass keyword arguments directly to the Excel engine that is performing read / write operations on the users behalf. 

Passing keyword arguments to excel engines can be helpful for many reasons, as seen in issue  #40274

### Feature Description

The implementation would follow the same logic seen in PR #52214:

- Add `engine_kwargs` to the method to_excel
- engine_kwargs would be passed down to the ExcelWriter class and to all Excel engine _write_cells methods

### Alternative Solutions

N/A

**Comment by rmhowe425** [comment]
take

**Comment by rmhowe425** [comment]
@rhendric 

Created this enhancement request as discussed [here](https://github.com/pandas-dev/pandas/pull/52214#issuecomment-1490756956)

**Comment by rhendric** [comment]
I'm not the user you meant to ping.

**Comment by rmhowe425** [comment]
@rhshadrach
