### ISSUE TITLE
DOC: Documentation linking breakage for Float64Index

### ISSUE THREAD

**Issue by larsoner** [pandas-dev/pandas#52379]
Float64Index and Int64Index have been accessible for a while:

![Screenshot from 2023-04-03 12-24-13](https://user-images.githubusercontent.com/2365790/229569950-7604e8a0-b953-4074-a0f4-fc5e49de04f7.png)

Clicking this link is now a 404 (and cross-refrencing it in intersphinx, which is [how I found this bug](https://app.circleci.com/pipelines/github/mne-tools/mne-python/18589/workflows/37e0f311-e45f-4ddb-8892-e07b9061ed42/jobs/53752?invite=true#step-140-2035), is also broken):

![Screenshot from 2023-04-03 12-25-30](https://user-images.githubusercontent.com/2365790/229570235-1342907b-9e7f-4087-8b7f-18fcdd5c5250.png)

But timedeltaindex still exists:

https://pandas.pydata.org/docs/reference/api/pandas.TimedeltaIndex.html

Were these removed intentionally?

**Comment by asishm-wk** [comment]
They have been removed with pandas 2.0

See the first item under https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html#removal-of-prior-version-deprecations-changes

**Comment by mroeschke** [comment]
Correct, since pandas 2.0 was released today, Float64Index deprecation has been enforced and removed from the docs.

If you want a link to FloatIndex64 you can reference the 1.5 version of the docs: https://pandas.pydata.org/pandas-docs/version/1.5/reference/api/pandas.Float64Index.html

Closing

**Comment by larsoner** [comment]
Sorry I missed that, thanks for the quick correction!
