### ISSUE TITLE
DOC: Incorrect mention of dtype_backend_option in convert_dtypes docstring

### ISSUE THREAD

**Issue by paultiq** [pandas-dev/pandas#52390]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.convert_dtypes.html

### Documentation problem

Documentation references features that didn't ship in 2.0.0 (they were in RC1): pd.set_option("mode.dtype_backend", "pyarrow") 

> New in version 2.0: The nullable dtype implementation can be configured by calling pd.set_option("mode.dtype_backend", "pandas") to use numpy-backed nullable dtypes or pd.set_option("mode.dtype_backend", "pyarrow") to use pyarrow-backed nullable dtypes (using pd.ArrowDtype).

### Suggested fix for documentation

Remove or update reference to be consistent with https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html.

Instead of the mode.dtype_backend, reference this from the release notes:

> The following functions gained a new keyword dtype_backend ([GH36712](https://github.com/pandas-dev/pandas/issues/36712))

**Comment by datapythonista** [comment]
Thanks @paultiq, good catch. I opened #52399 to address it, do you mind having a look at it?

**Comment by paultiq** [comment]
Ah, thanks, didn't know etiquette. Looks good to me.
