### ISSUE TITLE
Empty KeyError when trying to merge Int32 and int32[pyarrow] columns

### ISSUE THREAD

**Issue by canutera** [pandas-dev/pandas#52406]
Hi, I'm using Pandas 2.0.0. When I tried to merge two int columns('int32', 'int32[pyarrow]') I recieved an empty KeyError.

When I try to merge columns of different dtypes like int and object the KeyError has an explicit message saying that you're trying to merge with two columns of different types.

But this does not happen for int32 and int32[pyarrow] or float for similar types between old format  and pyarrow new format.

Could you please update, so that this error can be identified more easily? I spent aproximately 4h figuring this out. 
Thanks

![merging_int_and_int pyarrow](https://user-images.githubusercontent.com/67880597/229828125-352845b0-9ea9-4e76-8577-f17394a79f88.png)
[code_to_reproduce_error.txt](https://github.com/pandas-dev/pandas/files/11149792/code_to_reproduce_error.txt)

**Comment by phofl** [comment]
Hi, thanks for your report. Please provide a minimal and reproducible example, see https://matthewrocklin.com/minimal-bug-reports

Your example is too large. Also please fill out our issue template in the future.

**Comment by phofl** [comment]
This is not a minimal example, this is way too much code

**Comment by canutera** [comment]
Do I send over here, or on issue page?

Em ter., 4 de abr. de 2023 14:53, Patrick Hoefler ***@***.***>
escreveu:

**Comment by canutera** [comment]
[error_example.txt](https://github.com/pandas-dev/pandas/files/11151673/error_example.txt)
