### ISSUE TITLE
BUG: String slicing produces different results with pyarrow string datatype compared to python string type

### ISSUE THREAD

**Issue by rohanjain101** [pandas-dev/pandas#52434]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> a = pd.Series(["abcdefghijklmnabcdefghijkln"], dtype=pd.ArrowDtype(pa.string()))
>>> a.str.slice(None, 8, -9)
0
dtype: string[pyarrow]
```

### Issue Description

The string above contains pure ascii characters, yet the result does not match the python string result.

```
>>> "abcdefghijklmnabcdefghijkln"[None:8:-9]
'nd'
>>>
```

### Expected Behavior

Behavior with python strings.
```
>>> a = pd.Series(["abcdefghijklmnabcdefghijkln"], dtype=pd.StringDtype())
>>> a.str.slice(None, 8, -9)
0    nd
dtype: string
>>>
```

### Installed Versions

<details>

>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : 478d340667831908b5b4bf09a2787a11a14560c9
python           : 3.8.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 2.0.0
numpy            : 1.24.2
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.5.1
pip              : 23.0.1
Cython           : None
pytest           : 7.0.1
hypothesis       : None
sphinx           : 4.2.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.12.0
pandas_datareader: None
bs4              : 4.12.0
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None
>>>

</details>

**Comment by rohanjain101** [comment]
Since pandas implementation is just delegating to pyarrow utf8_slice_codeunits, is this issue caused by  upstream issue? Is arrow slice intended to be different than python slice?

```
>>> pa.compute.utf8_slice_codeunits("abcdefghijklmnabcdefghijkln", start=0, stop=8, step=-9)
<pyarrow.StringScalar: ''>
>>>
```

**Comment by mroeschke** [comment]
Yeah looks like an issue with the upstream `utf8_slice_codeunits`, mind opening an issue with arrow and linking it here?

**Comment by rohanjain101** [comment]
@mroeschke I apologize for the confusion, my example was wrong, it seems arrow is producing the correct behavior, for the example:

```
>>> "abcdefghijklmnabcdefghijkln"[None:8:-9]
'nd'

>>> pa.compute.utf8_slice_codeunits("abcdefghijklmnabcdefghijkln", start=26, stop=8, step=-9)
<pyarrow.StringScalar: 'nd'>
>>>
```

It looks like pandas is not taking into account that if step is negative, start needs to be len - 1, seems like it's just passing 0. I don't believe this is an upstream issue. I think _str_slice in ArrowArray is not taking into account negative step value.

**Comment by mroeschke** [comment]
The difficulty is that you cannot specify `len - 1` for an array of strings with different lengths. 

xref https://github.com/apache/arrow/issues/28940

**Comment by rohanjain101** [comment]
Ah, I see. Is this still something that should be reported upstream? As the linked issue has been closed.

**Comment by mroeschke** [comment]
Yeah would be worth an issue in pyarrow. https://github.com/apache/arrow/issues/14991 is somewhat related in the sense that `utf8_slice_codeunits` doesn't seem to handle `None` start or end bounds of different lengths

**Comment by rohanjain101** [comment]
Opened https://github.com/apache/arrow/issues/34917

**Comment by mroeschke** [comment]
Closing as awaiting resolution in https://github.com/apache/arrow/issues/34917
