### ISSUE TITLE
BUILD: Pandas 2.0.0 Installation Issue

### ISSUE THREAD

**Issue by ZacksAmber** [pandas-dev/pandas#52460]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

macOS-13.3-arm64-arm-64bit; Linux-5.15.49-linuxkit-aarch64-with-glibc2.31

### Installation Method

pip install

### pandas Version

2.0.0

### Python Version

3.10.10, 3.11.2

### Installation Logs

Logs from my MacBook (M chip) macOS-13.3-arm64-arm-64bit:
- Python 3.10.10

<details>

(python3.10) ➜  python3.10 pipenv install "pandas[all]"
Installing pandas[all]...
Resolving pandas...
Installing...
⠹ Installing pandas...[31m[1mError: [0m An error occurred while installing [32mpandas[0m!
Error text: Requirement already satisfied: pandas in ./.venv/lib/python3.10/site-packages (from -r
/var/folders/bn/xnw38wz5697c2m0cykr9528m0000gn/T/pipenv-ixbqo97l-requirements/pipenv-g3sfef_s-requ
irement.txt (line 1)) (2.0.0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.10/site-packages (from 
pandas->-r 
/var/folders/bn/xnw38wz5697c2m0cykr9528m0000gn/T/pipenv-ixbqo97l-requirements/pipenv-g3sfef_s-requ
irement.txt (line 1)) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.10/site-packages 
(from pandas->-r 
/var/folders/bn/xnw38wz5697c2m0cykr9528m0000gn/T/pipenv-ixbqo97l-requirements/pipenv-g3sfef_s-requ
irement.txt (line 1)) (2.8.2)
Requirement already satisfied: numpy>=1.21.0 in ./.venv/lib/python3.10/site-packages (from 
pandas->-r 
/var/folders/bn/xnw38wz5697c2m0cykr9528m0000gn/T/pipenv-ixbqo97l-requirements/pipenv-g3sfef_s-requ
irement.txt (line 1)) (1.24.2)
Requirement already satisfied: tzdata>=2022.1 in ./.venv/lib/python3.10/site-packages (from 
pandas->-r 
/var/folders/bn/xnw38wz5697c2m0cykr9528m0000gn/T/pipenv-ixbqo97l-requirements/pipenv-g3sfef_s-requ
irement.txt (line 1)) (2023.3)
Collecting openpyxl>=3.0.7
  Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.0/250.0 kB 5.6 MB/s eta 0:00:00
Collecting pytest-xdist>=2.2.0
  Downloading pytest_xdist-3.2.1-py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.0/41.0 kB 201.9 MB/s eta 0:00:00
Collecting pytest-asyncio>=0.17.0
  Downloading pytest_asyncio-0.21.0-py3-none-any.whl (13 kB)
Collecting fastparquet>=0.6.3
  Downloading fastparquet-2023.2.0-cp310-cp310-macosx_11_0_arm64.whl (583 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 583.0/583.0 kB 17.1 MB/s eta 0:00:00
Collecting s3fs>=2021.08.0
  Downloading s3fs-2023.3.0-py3-none-any.whl (27 kB)
Collecting psycopg2>=2.8.6
  Downloading psycopg2-2.9.6.tar.gz (383 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 384.0/384.0 kB 31.3 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

[36m  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      /Users/zacks/Git/Projects/python3.10/.venv/lib/python3.10/site-packages/setuptools/config/se
tupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use 
license_files instead.
        warnings.warn(msg, warning_class)
      running egg_info
      creating 
/private/var/folders/bn/xnw38wz5697c2m0cykr9528m0000gn/T/pip-pip-egg-info-n38jh0zl/psycopg2.egg-in
fo
      writing 
/private/var/folders/bn/xnw38wz5697c2m0cykr9528m0000gn/T/pip-pip-egg-info-n38jh0zl/psycopg2.egg-in
fo/PKG-INFO
      writing dependency_links to 
/private/var/folders/bn/xnw38wz5697c2m0cykr9528m0000gn/T/pip-pip-egg-info-n38jh0zl/psycopg2.egg-in
fo/dependency_links.txt
      writing top-level names to 
/private/var/folders/bn/xnw38wz5697c2m0cykr9528m0000gn/T/pip-pip-egg-info-n38jh0zl/psycopg2.egg-in
fo/top_level.txt
      writing manifest file 
'/private/var/folders/bn/xnw38wz5697c2m0cykr9528m0000gn/T/pip-pip-egg-info-n38jh0zl/psycopg2.egg-i
nfo/SOURCES.txt'
      
      Error: pg_config executable not found.
      
      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:
      
          python setup.py build_ext --pg-config /path/to/pg_config build ...
      
      or with the pg_config option in 'setup.cfg'.
      
      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.
      
      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).
      
      
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
[0m
This is likely caused by a bug in [32mpandas[0m. Report this to its maintainers.
✘ Installation Failed

</details>

---

Logs from my MacBook (M chip) macOS-13.3-arm64-arm-64bit:
- Python 3.11.2

<details>

(python3.11) ➜  python3.11 pipenv install "pandas[all]"
Installing pandas[all]...
Resolving pandas...
Installing...
⠙ Installing pandas...[31m[1mError: [0m An error occurred while installing [32mpandas[0m!
Error text: Collecting pandas
  Downloading pandas-2.0.0-cp311-cp311-macosx_11_0_arm64.whl (10.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 15.2 MB/s eta 0:00:00
Collecting python-dateutil>=2.8.2
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 18.1 MB/s eta 0:00:00
Collecting pytz>=2020.1
  Downloading pytz-2023.3-py2.py3-none-any.whl (502 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.3/502.3 kB 17.6 MB/s eta 0:00:00
Collecting tzdata>=2022.1
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 24.3 MB/s eta 0:00:00
Collecting numpy>=1.21.0
  Downloading numpy-1.24.2-cp311-cp311-macosx_11_0_arm64.whl (13.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 16.6 MB/s eta 0:00:00
Collecting beautifulsoup4>=4.9.3
  Downloading beautifulsoup4-4.12.1-py3-none-any.whl (142 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.5/142.5 kB 33.2 MB/s eta 0:00:00
Collecting bottleneck>=1.3.2
  Downloading Bottleneck-1.3.7.tar.gz (103 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.1/103.1 kB 14.7 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting brotlipy>=0.7.0
  Downloading brotlipy-0.7.0.tar.gz (413 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.3/413.3 kB 16.8 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting fastparquet>=0.6.3
  Downloading fastparquet-2023.2.0-cp311-cp311-macosx_11_0_arm64.whl (579 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 579.2/579.2 kB 19.5 MB/s eta 0:00:00
Collecting fsspec>=2021.07.0
  Downloading fsspec-2023.3.0-py3-none-any.whl (145 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.4/145.4 kB 75.7 MB/s eta 0:00:00
Collecting gcsfs>=2021.07.0
  Downloading gcsfs-2023.3.0-py2.py3-none-any.whl (26 kB)
Collecting html5lib>=1.1
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 kB 39.6 MB/s eta 0:00:00
Collecting hypothesis>=6.34.2
  Downloading hypothesis-6.70.2-py3-none-any.whl (403 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 403.1/403.1 kB 28.4 MB/s eta 0:00:00
Collecting jinja2>=3.0.0
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 28.7 MB/s eta 0:00:00
Collecting lxml>=4.6.3
  Downloading lxml-4.9.2.tar.gz (3.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 14.6 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting matplotlib>=3.6.1
  Downloading matplotlib-3.7.1-cp311-cp311-macosx_11_0_arm64.whl (7.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 17.2 MB/s eta 0:00:00
Collecting numba>=0.53.1
  Downloading numba-0.56.4.tar.gz (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 19.3 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

[36m  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File 
"/private/var/folders/bn/xnw38wz5697c2m0cykr9528m0000gn/T/pip-install-4vociqex/numba_b3707aeb00494
f05bcaa9fb4aa7a8863/setup.py", line 51, in <module>
          _guard_py_ver()
        File 
"/private/var/folders/bn/xnw38wz5697c2m0cykr9528m0000gn/T/pip-install-4vociqex/numba_b3707aeb00494
f05bcaa9fb4aa7a8863/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.2; only versions >=3.7,<3.11 are 
supported.
      
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
[0m
This is likely caused by a bug in [32mpandas[0m. Report this to its maintainers.
✘ Installation Failed

</details>

---

Logs from Docker Python official image running on my MacBook (M chip) macOS-13.3-arm64-arm-64bit:
- Python 3.10.10
- Linux-5.15.49-linuxkit-aarch64-with-glibc2.31

<details>

root@983604b111bd:/# pip install "pandas[all]"
Collecting pandas[all]
  Using cached pandas-2.0.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (11.6 MB)
Collecting pytz>=2020.1
  Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
Collecting python-dateutil>=2.8.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting tzdata>=2022.1
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Collecting numpy>=1.21.0
  Using cached numpy-1.24.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.0 MB)
Collecting SQLAlchemy>=1.4.16
  Downloading SQLAlchemy-2.0.8-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (2.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 4.9 MB/s eta 0:00:00
Collecting html5lib>=1.1
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 kB 10.3 MB/s eta 0:00:00
Collecting numba>=0.53.1
  Using cached numba-0.56.4-cp310-cp310-manylinux2014_aarch64.manylinux_2_17_aarch64.whl (3.2 MB)
Collecting tabulate>=0.8.9
  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Collecting pytest-xdist>=2.2.0
  Downloading pytest_xdist-3.2.1-py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.0/41.0 kB 2.7 MB/s eta 0:00:00
Collecting pytest-asyncio>=0.17.0
  Using cached pytest_asyncio-0.21.0-py3-none-any.whl (13 kB)
Collecting gcsfs>=2021.07.0
  Downloading gcsfs-2023.3.0-py2.py3-none-any.whl (26 kB)
Collecting pytest>=7.0.0
  Downloading pytest-7.2.2-py3-none-any.whl (317 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.2/317.2 kB 6.5 MB/s eta 0:00:00
Collecting odfpy>=1.4.1
  Using cached odfpy-1.4.1.tar.gz (717 kB)
  Preparing metadata (setup.py) ... done
Collecting pymysql>=1.0.2
  Downloading PyMySQL-1.0.3-py3-none-any.whl (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 18.4 MB/s eta 0:00:00
Collecting hypothesis>=6.34.2
  Downloading hypothesis-6.70.2-py3-none-any.whl (403 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 403.1/403.1 kB 4.2 MB/s eta 0:00:00
Collecting qtpy>=2.2.0
  Downloading QtPy-2.3.1-py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.9/84.9 kB 6.2 MB/s eta 0:00:00
Collecting lxml>=4.6.3
  Downloading lxml-4.9.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.manylinux_2_24_aarch64.whl (6.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 6.5 MB/s eta 0:00:00
Collecting psycopg2>=2.8.6
  Using cached psycopg2-2.9.6.tar.gz (383 kB)
  Preparing metadata (setup.py) ... done
Collecting pyxlsb>=1.0.8
  Downloading pyxlsb-1.0.10-py2.py3-none-any.whl (23 kB)
Collecting pandas-gbq>=0.15.0
  Downloading pandas_gbq-0.19.1-py2.py3-none-any.whl (25 kB)
Collecting fsspec>=2021.07.0
  Downloading fsspec-2023.3.0-py3-none-any.whl (145 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.4/145.4 kB 6.6 MB/s eta 0:00:00
Collecting numexpr>=2.7.3
  Downloading numexpr-2.8.4-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (412 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 412.6/412.6 kB 6.2 MB/s eta 0:00:00
Collecting scipy>=1.7.1
  Downloading scipy-1.10.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (30.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.9/30.9 MB 7.2 MB/s eta 0:00:00
Collecting pyreadstat>=1.1.2
  Downloading pyreadstat-1.2.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (2.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 9.1 MB/s eta 0:00:00
Collecting xarray>=0.21.0
  Downloading xarray-2023.3.0-py3-none-any.whl (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.2/981.2 kB 10.5 MB/s eta 0:00:00
Collecting xlsxwriter>=1.4.3
  Downloading XlsxWriter-3.0.9-py3-none-any.whl (152 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.8/152.8 kB 7.5 MB/s eta 0:00:00
Collecting pyarrow>=7.0.0
  Downloading pyarrow-11.0.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (32.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 32.7/32.7 MB 8.7 MB/s eta 0:00:00
Collecting matplotlib>=3.6.1
  Downloading matplotlib-3.7.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (11.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 9.3 MB/s eta 0:00:00
Collecting tables>=3.6.1
  Downloading tables-3.8.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (6.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 10.6 MB/s eta 0:00:00
Collecting jinja2>=3.0.0
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 9.0 MB/s eta 0:00:00
Collecting python-snappy>=0.6.0
  Downloading python_snappy-0.6.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.3/53.3 kB 22.3 MB/s eta 0:00:00
Collecting fastparquet>=0.6.3
  Downloading fastparquet-2023.2.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 14.3 MB/s eta 0:00:00
Collecting bottleneck>=1.3.2
  Downloading Bottleneck-1.3.7.tar.gz (103 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.1/103.1 kB 14.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting s3fs>=2021.08.0
  Downloading s3fs-2023.3.0-py3-none-any.whl (27 kB)
Collecting beautifulsoup4>=4.9.3
  Downloading beautifulsoup4-4.12.1-py3-none-any.whl (142 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.5/142.5 kB 21.3 MB/s eta 0:00:00
Collecting PyQt5>=5.15.1
  Using cached PyQt5-5.15.9.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-exyuoi9v/overlay/lib/python3.10/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/tmp/pip-build-env-exyuoi9v/overlay/lib/python3.10/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/tmp/pip-build-env-exyuoi9v/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "/tmp/pip-install-2rn5o_dv/pyqt5_e75af343fa4b4d168f129f54bd7cf1eb/project.py", line 68, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-exyuoi9v/overlay/lib/python3.10/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-exyuoi9v/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/tmp/pip-build-env-exyuoi9v/overlay/lib/python3.10/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

</details>

---

Logs from Docker Python official image running on my MacBook (M chip) macOS-13.3-arm64-arm-64bit:
- Python 3.11.2
- Linux-5.15.49-linuxkit-aarch64-with-glibc2.31

<details>

root@3b89b123d122:/# pip install "pandas[all]"
Collecting pandas[all]
  Downloading pandas-2.0.0-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (11.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 18.7 MB/s eta 0:00:00
Collecting python-dateutil>=2.8.2
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 14.2 MB/s eta 0:00:00
Collecting pytz>=2020.1
  Downloading pytz-2023.3-py2.py3-none-any.whl (502 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.3/502.3 kB 26.1 MB/s eta 0:00:00
Collecting tzdata>=2022.1
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 27.1 MB/s eta 0:00:00
Collecting numpy>=1.21.0
  Downloading numpy-1.24.2-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 17.2 MB/s eta 0:00:00
Collecting beautifulsoup4>=4.9.3
  Downloading beautifulsoup4-4.12.1-py3-none-any.whl (142 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.5/142.5 kB 17.8 MB/s eta 0:00:00
Collecting bottleneck>=1.3.2
  Downloading Bottleneck-1.3.7.tar.gz (103 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.1/103.1 kB 10.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting brotlipy>=0.7.0
  Downloading brotlipy-0.7.0-cp35-abi3-manylinux2014_aarch64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 16.3 MB/s eta 0:00:00
Collecting fastparquet>=0.6.3
  Downloading fastparquet-2023.2.0-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 20.6 MB/s eta 0:00:00
Collecting fsspec>=2021.07.0
  Downloading fsspec-2023.3.0-py3-none-any.whl (145 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.4/145.4 kB 41.1 MB/s eta 0:00:00
Collecting gcsfs>=2021.07.0
  Downloading gcsfs-2023.3.0-py2.py3-none-any.whl (26 kB)
Collecting html5lib>=1.1
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 kB 40.9 MB/s eta 0:00:00
Collecting hypothesis>=6.34.2
  Downloading hypothesis-6.70.2-py3-none-any.whl (403 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 403.1/403.1 kB 18.1 MB/s eta 0:00:00
Collecting jinja2>=3.0.0
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 9.5 MB/s eta 0:00:00
Collecting lxml>=4.6.3
  Downloading lxml-4.9.2-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.manylinux_2_24_aarch64.whl (6.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 15.8 MB/s eta 0:00:00
Collecting matplotlib>=3.6.1
  Downloading matplotlib-3.7.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (11.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 17.6 MB/s eta 0:00:00
Collecting numba>=0.53.1
  Downloading numba-0.56.4.tar.gz (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 19.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-2u3w00i5/numba_6c875d89da9a4596b6083cc9ffb04d91/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/tmp/pip-install-2u3w00i5/numba_6c875d89da9a4596b6083cc9ffb04d91/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.2; only versions >=3.7,<3.11 are supported.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

</details>

**Comment by phofl** [comment]
Can you try specifying numba and numpy so that they are compatible with each other? Also numba won't work on python 3.11

**Comment by ZacksAmber** [comment]
> Can you try specifying numba and numpy so that they are compatible with each other? Also numba won't work on python 3.11
> 
> or use mamba which takes care of this for you

Thanks for your help.
According to [Pandas Installation Guide](https://pandas.pydata.org/docs/dev/getting_started/install.html), I tried most of the options. And I see there are a few options with the required dependencies that must be installed manually, such as `pandas[hdf5]`. That's why I cannot run `pip install pandas[all]` because there are no such dependencies.

It will be better if pandas 2.0 can solve the dependencies automatically.
