### ISSUE TITLE
BUG: pyarrow mean can overflows on timestamp[ns][pyarrow]

### ISSUE THREAD

**Issue by Braffolk** [pandas-dev/pandas#52464]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

date = pd.to_datetime("2021-01-01 00:00:00")

df_long = pd.DataFrame([{"date": date} for v in range(1000)])
df_short = pd.DataFrame([{"date": date} for v in range(3)])
df_long_pa = df_long.convert_dtypes(dtype_backend="pyarrow")
df_short_pa = df_short.convert_dtypes(dtype_backend="pyarrow")

print("timestamp[ns]:")
print("long  pyarrow mean", df_long_pa["date"].mean())  # Fails on over len 3 DF
print("short pyarrow mean", df_short_pa["date"].mean())
print("long  numpy mean", df_long["date"].mean())
print("short numpy mean", df_short["date"].mean())

print("timestamp[s]:")
df_long_pa["date"] = df_long_pa["date"].astype("timestamp[s][pyarrow]")
print("long pyarrow mean", df_long_pa["date"].mean())
```

### Issue Description

When calling .mean() on pyarrow timestamp[ns][pyarrow] type and the length of meaned data is over 3, the function fails and gives results close to start of unix time.

long - dataframe with 1k entries
short - dataframe with 3 entries

timestamp[ns]:
long  pyarrow mean 1970-02-23 03:41:05.587269009
short pyarrow mean 2021-01-01 00:00:00
long  numpy mean 2021-01-01 00:00:00
short numpy mean 2021-01-01 00:00:00

when using timestamp[s], the output is correct:
long pyarrow mean 2021-01-01 00:00:00

### Expected Behavior

.mean() should return 2021-01-01 00:00:00 in the example.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 478d340667831908b5b4bf09a2787a11a14560c9
python           : 3.10.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 22.1.0
Version          : Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8

pandas           : 2.0.0
numpy            : 1.24.2
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.6.1
pip              : 23.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : 
fastparquet      : None
fsspec           : 2021.07.0
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : 2021.08.0
scipy            : 1.10.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by mroeschke** [comment]
Thanks, I suspect this is an issue with pyarrow and opened https://github.com/apache/arrow/issues/34913

```
In [4]: import numpy as np; import pandas as pd; import pyarrow as pa

In [5]: data = [1609459200000000000] * 2

In [6]: pa.compute.mean(pa.array(data))
Out[6]: <pyarrow.DoubleScalar: 1.6094592e+18>

In [7]: data = [1609459200000000000] * 3

In [8]: pa.compute.mean(pa.array(data))
Out[8]: <pyarrow.DoubleScalar: 1.6094592e+18>

In [9]: data = [1609459200000000000] * 4

In [10]: pa.compute.mean(pa.array(data))
Out[10]: <pyarrow.DoubleScalar: 1.6094592e+18>

In [11]: data = [1609459200000000000] * 100

In [12]: pa.compute.mean(pa.array(data))
Out[12]: <pyarrow.DoubleScalar: -5.074776663385965e+16>

In [13]: data = [1609459200000000000] * 1000

In [14]: pa.compute.mean(pa.array(data))
Out[14]: <pyarrow.DoubleScalar: 4592465587269009.0>
```

**Comment by mroeschke** [comment]
This should have been fixed by https://github.com/apache/arrow/pull/37243 so closing
