### ISSUE TITLE
BUG: Writer.sheets= ExcelWorkbook cant set attribute 'sheets'

### ISSUE THREAD

**Issue by sabirjana** [pandas-dev/pandas#52483]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
writer = pd.ExcelWriter(filename, engine='openpyxl', mode='a')
writer.sheets= ExcelWorkbook cant set attribute 'sheets'
```

### Issue Description

I get an error AttributeError :can't set attribute 'sheets'

This issue is from version 1.5, I don't get this issue in version 1.4.4

### Expected Behavior

na

### Installed Versions

<details>

2.0

</details>

**Comment by phofl** [comment]
cc @rhshadrach 

IIRC this was intentional?

**Comment by Dr-Irv** [comment]
This may be an issue with `openpyxl`.  With `openpyxl` 3.1.1, I get errors in trying to read an Excel file.  With `openpyxl` 3.1.2, the error goes away.  Issue seems to be that the conda version on conda-forge is still at 3.1.1.

@sabirjana can you verify the version of `openpyxl` that you have installed in your environment.  You didn't provide the details in the issue.

**Comment by rhshadrach** [comment]
@Dr-Irv - this issue is about setting the `sheets` attribute, that sounds unrelated, no?

@phofl - Yes, IIRC you can't safely set the sheets attribute, this is deprecated, and then removed in 2.0. I'd like to leave this issue open until it's verified that users can't safely set the sheet attribute (I'd like to just double check).

**Comment by sabirjana** [comment]
Thanks for the response. My openpyxl version is '3.0.10'.

**Comment by DeaMariaLeon** [comment]
It works if mode='a' is removed (at least with the dev version). 

And if it was deprecated, it's still on the documentation.

**Comment by Dr-Irv** [comment]
> @Dr-Irv - this issue is about setting the `sheets` attribute, that sounds unrelated, no?

It might be.  I found this issue first, but the problem I was having is described in #51392

**Comment by rhshadrach** [comment]
> It works if mode='a' is removed (at least with the dev version).
> 
> And if it was deprecated, it's still on the documentation.

@DeaMariaLeon - I can't reproduce, can you provide an example?

I took a look, if we were to allow a user to set the `sheets` attribute, we'd also need to update `book` accordingly, otherwise unexpected behavior can occur. While this may be doable, without a compelling use case, I don't see a reason to add.

**Comment by rhshadrach** [comment]
Ah, I see. This issue is about setting the sheets property, not just accessing it. Something like `writer.sheets = []`. The sheets property itself was not deprecated, only setting it was.

**Comment by DeaMariaLeon** [comment]
Apologies then..

**Comment by sabirjana** [comment]
> 
@DeaMariaLeon Thanks for sharing the code snippet. Yes it works in this case however if I need to open the same excel and now add sheet3 then what's the way. I used following code but writer.book throws error for pandas 2.0

```
`path = "data1\PhD_data.xlsx"

book = load_workbook('nameagain.xlsx')
writer = pd.ExcelWriter(path, engine = 'openpyxl')
writer.book = book

x3 = np.random.randn(100, 2)
df3 = pd.DataFrame(x3)

x4 = np.random.randn(100, 2)
df4 = pd.DataFrame(x4)

df3.to_excel(writer, sheet_name = 'x6')
df4.to_excel(writer, sheet_name = 'x7')
writer.close()`

```

**Comment by DeaMariaLeon** [comment]
This added sheets x6 and 7 for me:
```
with pd.ExcelWriter("nameagain.xlsx", engine='openpyxl', mode='a') as writer:
    df3.to_excel(writer, sheet_name = "x6")
    df4.to_excel(writer, sheet_name = "x7")
```

**Comment by sabirjana** [comment]
@DeaMariaLeon It works with pandas 1.4.4. now let me upgrade to 2.0 and check it. Thanks!

**Comment by sabirjana** [comment]
It works, we can close the issue. Thanks for your help!!
