### ISSUE TITLE
BUG: `resample` on empty DataFrame leads to `ValueError`

### ISSUE THREAD

**Issue by ASchueddekopf** [pandas-dev/pandas#52484]
Before version 2.0.0 I was able to resample an empty DataFrame with DateTimeIndex. Now it leads to a `ValueError`. Is that on purpose or a bug?

**Comment by MarcoGorelli** [comment]
can you show a reproducible example please?

**Comment by MarcoGorelli** [comment]
thanks

looks like this was introduced by https://github.com/pandas-dev/pandas/pull/47672 cc @mroeschke @rhshadrach @ahmedibrhm 

https://www.kaggle.com/code/marcogorelli/pandas-regression-example/notebook?scriptVersionId=125373741
