### ISSUE TITLE
DOC: to_sql 能否增加 INSERT IGNORE  INTO

### ISSUE THREAD

**Issue by majormj** [pandas-dev/pandas#52485]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

pandas.to_sql

### Documentation problem

to_sql 能否增加 数据的 INSERT IGNORE  INTO， 遇到重复数据自动忽略。
另外就是to_sql  遇到有主键的表格，无法写入数据

### Suggested fix for documentation

1、 to_sql 增加   INSERT IGNORE  INTO  ，遇到重复数据自动忽略，不影响其他数据写入
2、to_sql 遇到有主键的表格无法写入
3、to_sql 能否根据 自动增加 SQL表格字段

**Comment by MarcoGorelli** [comment]
hi @majormj could you ask in english please?

**Comment by MarcoGorelli** [comment]
closing for now as I can't tell what you're asking, sorry

**Comment by MarcoGorelli** [comment]
could you open a new issue and fill in the issue template please?
