### ISSUE TITLE
Make pyarrow a required dependency

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#52509]
Right now we run into a bunch of problems because pyarrow is potentially missing. 

- It is pretty awkward to check for arrow inputs, e.g if we get an arrow array as input we have no good way of figuring this out (see https://github.com/pandas-dev/pandas/pull/52076/files)
- We can’t properly identify arrow scalars in all kinds of ops (e.g. indexing ops https://github.com/pandas-dev/pandas/issues/52235, https://github.com/pandas-dev/pandas/issues/52056)
- Proper constructor support is not possible right now without causing significant slowdowns

This is the next step in supporting arrow fully in pandas. There are some things we can’t implement properly without requiring arrow as dependency.
So I think we should do it soonish, so that we can move forward. 

cc @pandas-dev/pandas-core

**Comment by MarcoGorelli** [comment]
I'd be in favour

I've heard people raise objections because pyarrow is too heavy of a dependency - personally, I'd require it anyway, I don't think we should hold the project back because of this, just bringing it up for completeness

**Comment by jreback** [comment]
+1 from me - it's time

**Comment by datapythonista** [comment]
+1

I think main objections were not to do it yet as it was just fine to have it as a an optional dependency (see #50285). But if having it optional is an impediment.

Maybe PyArrow dependencies aren't ideal, but this should only be a temporary problem if PyArrow packages are expected to become more modular.

**Comment by lithomas1** [comment]
Are we planning on using Arrow Cython integration/C API stuff?

If not, requiring should be trivial on packaging side should be trivial (so no objections from me there).

Since from the few comments so far, most people seem to be in favor, 
we should really start figuring out the specifics of this, e.g.

1) What will be the min. version of pyarrow that we will support?
    a) Would it be OK to have certain parts of pandas depend on a higher min. version of pyarrow?
2) How many version of pyarrow will we commit to supporting(e.g. for numpy we support from 1.20-1.24, which is ~5 versions)?

**Comment by jorisvandenbossche** [comment]
As long as it is not actually required (at the moment, it's strictly speaking an optional dependency, as you can perfectly fine use pandas without needing pyarrow, if you don't use any IO method relying on it and if you don't use the arrow-based dtypes), I don't see a good reason to make it an actual hard dependency. 

The mentioned reasons that make it "awkward" to have it as an optional dependency don't sound that convincing to me, personally. I think it is quite easy to have helper methods that can check for pyarrow arrays and scalars (I commented on the mentioned PR: https://github.com/pandas-dev/pandas/pull/52076/files#r1160653924). That should already cover the first two points in the top post.

> Proper constructor support is not possible right now without causing significant slowdowns

Is there some discussion about somewhere?  I don't directly see why this would give a big slowdown.

---

When choosing to make it a hard requirement now, we have to be aware what the consequences are installation wise. For example, you can currently install pandas from source on most platforms as long as you have a compiler available (apart from that, we only have python dependencies / dependencies that can be installed by python in the same way as pandas). With pyarrow, that would no longer be true, as it cannot be installed from source. A typical example are docker images based on alpine linux (musl), for which there are no wheels at the moment.

**Comment by jbrockmendel** [comment]
+1

**Comment by MarcoGorelli** [comment]
agree - that, and the time bound on the voting period ensures we'll actually reach a decision rather than leaving the issue hanging around indefinitely. I think it'd be a good candidate

**Comment by mroeschke** [comment]
I would be +1 on making pyarrow a required dependency. Though not strictly necessary for default functionality at the moment, I think it would be a great "signal" for pandas to vouch for the arrow format & ecosystem.

I can see this change being significant enough for a PDEP, but as @MarcoGorelli alluded too I expect we could vote on this rather quickly given all the support in this thread already

**Comment by simonjayhawkins** [comment]
> I can see this change being significant enough for a PDEP, but as @MarcoGorelli alluded too I expect we could vote on this rather quickly given all the support in this thread already

yes. I think @jorisvandenbossche has convincing arguments to counter the issues in the OP and also partly the issues in older issue.

from the PDEP guidelines... "It is not always trivial to know which issue has enough scope to require the full PDEP process.
Some simple API changes have sufficient consensus among the core team, and minimal impact on the
community."

there does appear to be "sufficient consensus among the core team" but since requiring a new dependancy does not satisfy "minimal impact on the community.", I think a PDEP should be required for this change.

**Comment by attack68** [comment]
> Making a PDEP shifts decision-making away from people who actually work on development and towards people willing to throw up walls of text.
> 

I agree with @simonjayhawkins, PDEP-1 seems to indicate this is in scope.
I think PDEPs offer a lot of value, not only for audit but for the transparency of the project.

**Comment by mroeschke** [comment]
Just to clarify my comment, I do think it is a good idea that this is a PDEP such that we can lay out the pros/cons and discuss _and_ use voting to make a decision with clarity than let the decision be ambiguous and linger here in the issue.

Post the dev meeting on 2023-04-12, I will draft this PDEP

**Comment by datapythonista** [comment]
As the person who wrote PDEP-1, I'd personally wouldn't use it to decide if something requires a PDEP or not. I'm happy with both having this as a PDEP or not. But I think more important than how we interpret PDEP-1 exact sentences is what's useful, and in this case I'm not sure what part of the text of the possible PDEP would be to comment on. Seems like the decision is more of a preference.

Depending on pyarrow makes our life easier. And makes users who 1) want to install pandas from source 2) are not interested in the pyarrow feature, not be able to do it anymore.

I don't think Joris comment is a -1 (maybe that's his position but the comment is just a be aware of the consequences).

So, feels to me that we're all more or less in the same page. It's just a question of each person preference/priority. My vote is a clear +1, advantages of ensuring pyarrow is always available are more valuable than the limitations to the installation that I'm unsure any user will really face. This seems to be the most popular opinion based on above answers.

I'd say, if there is no proper objection let's just move forward. If people think it's still not clear enough what are tha advantages and disadvantages let's write a PDEP, so we're all in the same page, and then make a decision (is the new voting system already in place, or should we vote for that too?).

**Comment by Dr-Irv** [comment]
> I'd say, if there is no proper objection let's just move forward. If people think it's still not clear enough what are tha advantages and disadvantages let's write a PDEP, so we're all in the same page, and then make a decision (is the new voting system already in place, or should we vote for that too?).

The other reason to write a PDEP is that it makes it possible to get user feedback.  Since requiring pyarrow will impact users, we should see if our user community has an opinion on the matter.

**Comment by datapythonista** [comment]
Do you think a PDEP has a much more visibility than this issue? We have them listed in the roadmap, I guess maybe a bit, but wouldn't an email to pandas-dev about this be a better option if we want more feedback?

I'm surely happy with a PDEP, the only thing is the time it takes to write it. But I see that a PDEP/PR adds a lot of value when feedback about the specific text written in the PDEP is expected. And in this case, assuming everybody has already an understanding and an opinion about requiring pyartow, I don't expect so many useful comments for particular parts of the text, so discussing in normal issue comments seem as fine.

The blocker here seems to be how we make the final decision (votes...) and I don't think a PDEP is going to help, so I'd address that directly.

**Comment by lithomas1** [comment]
I don't think this should be a PDEP. It would make this process way more drawn out than it should be, and there's really not a lot to put in the PDEP (we would really just be talked about min. version of pyarrow, how many versions to support, etc., basically the stuff I listed above ).

I missed the dev meeting where this was agreed upon, but I think I would much rather have a PDEP explaining the rationale behind adding support for pyarrow to everything in general (which would explain this by proxy).

**Comment by lithomas1** [comment]
> When choosing to make it a hard requirement now, we have to be aware what the consequences are installation wise. For example, you can currently install pandas from source on most platforms as long as you have a compiler available (apart from that, we only have python dependencies / dependencies that can be installed by python in the same way as pandas). With pyarrow, that would no longer be true, as it cannot be installed from source. A typical example are docker images based on alpine linux (musl), for which there are no wheels at the moment.

FWIW, there are no numpy musllinux wheels either. 

While numpy can be installed no external (non-Python) deps other than the C compiler, I don't think anyone would actually install numpy like that, since you'll be missing things like the BLAS.

(I would probably guess that people are building a numpy wheel for themselves that is compiled with the BLAS, and then installing that).

**Comment by Dr-Irv** [comment]
> Do you think a PDEP has a much more visibility than this issue?

The PDEP would have a discussion period, and be broadcast to the pandas user community as "open for discussion".

We agreed at the dev meeting today that @mroeschke will draft a PDEP.  We can have discussion there, and then formalize the vote.

I have a concern about package bloat.  Adding pyarrow increases the sizes of containers used in Kubernetes that are dependent on pandas.  Not necessarily a reason to not require `pyarrow`, but I think these issues can be discussed in the PDEP better than here, and gets the team used to using PDEP's to discuss issues like these.

**Comment by jreback** [comment]
> I have a concern about package bloat

if u r using pandas you almost always are using parquet so likely you have pyarrow installed anyways

**Comment by WillAyd** [comment]
Ah the age old problem - to include or not to include? As things stand today, it doesn't appear (according to pypistats, for as good as that can be) that pyarrow and pandas are always bundled together. And from our user polls I vaguely recall excel / html being pretty popular formats, maybe moreso than parquet. So I am a bit wary of using "likeliness of bundled usage" as a guiding factor

As things stand now I am -1 on the issue and agree this should be a PDEP, for the following reasons:

  1. We haven't _really_ defined required. I assume you mean as a runtime dependency, but why not as a build time dependency?
  2. I don't understand the problem we are solving; we manage a lot of optional runtime dependencies and it isn't that clear in this issue what makes this harder than normal
  3. This has conceptual conflict with the Meson PDEP; one of the selling points of that was to expand our potential platforms via cross-compiling, but here it seems like we are OK to limit the platforms we can be built on
  4. I _thought_ our goal was to become backend agnostic, i.e. there may be a future where numpy is optional and you can pick either backend

There is a lot of nuance to this discussion and I agree a PDEP would make it easier to communicate and collaborate versus a huge wall of responses in this issue. Not everything needs to be a PDEP so definitely want to be cognizant of using it as a blocker to progress, but at the same time we just launched that process so I think we should be heavy on PDEPs the next few months, as frustrating as that can be

**Comment by jbrockmendel** [comment]
> I _thought_ our goal was to become backend agnostic, i.e. there may be a future where numpy is optional and you can pick either backend

On today's call there was a mostly-joking suggestion of making numpy optional.  If someone finds a reasonable path to get there that would be neat (in large part bc making the numpy import lazy would be awesome).  Until then, I think we should shy away from the term "backend", as I've seen multiple discussions (maybe reddit, HN, not sure) where people are confused by the proliferation of dtype options.  I don't have links on hand, but I recall the word "backend" coming up frequently in these threads.

> We haven't really defined required. I assume you mean as a runtime dependency, but why not as a build time dependency?

I've been assuming run-time.

Other misc thoughts:

The OP referenced gymnastics-free isinstance checks for construction.  I'm also eager to have `maybe_convert_objects` infer Decimals to `decimal[pyarrow]` dtype (which would make it easier to address #52011, #40685, #39098, #25168), and similarly for time (#22720) and date objects (#39703)`.  (And I'm very skeptical of having internal functions behave differently based on the presence of pyarrow).

If we _don't_ require pyarrow, I'd like to make the import lazy.

**Comment by phofl** [comment]
Agreed by @jbrockmendel, we have to be careful communication wise. There is a lot of confusion out there regarding our arrow dtypes.

> We haven't really defined required. I assume you mean as a runtime dependency, but why not as a build time dependency?

> > I've been assuming run-time.

Sorry for not clarifying, yes run-time for now. Build-dependency would be nice at some point I guess, but there are a couple of hurdles to clear to get there. 

> The OP referenced gymnastics-free isinstance checks for construction. I'm also eager to have maybe_convert_objects infer Decimals to decimal[pyarrow] dtype (which would make it easier to address https://github.com/pandas-dev/pandas/issues/52011, https://github.com/pandas-dev/pandas/issues/40685, https://github.com/pandas-dev/pandas/issues/39098, https://github.com/pandas-dev/pandas/issues/25168), and similarly for time (https://github.com/pandas-dev/pandas/issues/22720) and date objects (https://github.com/pandas-dev/pandas/issues/39703)`. (And I'm very skeptical of having internal functions behave differently based on the presence of pyarrow).

Having something like bytes inferring as ``"bytes[pyarrow]"`` would be nice as well. Also nested data structures (but support for those is poor right now).

> When choosing to make it a hard requirement now, we have to be aware what the consequences are installation wise.

This certainly isn't ideal, but it's not a blocker imo, especially if there are no NumPy wheels either.

**Comment by bashtage** [comment]
Another consideration of hard dependencies is their speed in releasing wheels on new platforms.  I just checked and from what I can see pyarrow only released the first wheels for 3.11 in late November, which was a full month after pandas had a release with 3.11 support baked in.  Building pyarrow on some platforms is very hard, at least compared to building pandas and its dependencies (incl NumPy which is easy to configure for OpenBlas even on Windows, and can be trivially compiled without Blas if not needed).

**Comment by phofl** [comment]
Quick search brought the following issue:

https://issues.apache.org/jira/browse/ARROW-17487

This looks more like a timing problem not like a general Python 3.11 support problem (like numba has right now)

**Comment by simonjayhawkins** [comment]
> It would also be nice to prune down to Just One String Dtype, and AFAICT pyarrow is the obvious choice there.

Thanks @jbrockmendel for some further justification as only the arguments in the OP at first did not appear strong enough and had IMO been countered by @jorisvandenbossche.

Maybe the choice of/ future plans for string dtype warrants a detailed discussion (separate issue) and consensus what to do here? As I could potentially see this being a strong justification. (If we were to somehow able to remove object dtype from pandas)

> part of the text of the possible PDEP would be to comment on. Seems like the decision is more of a preference.

My thinking was that we should not let preferences sway a (hasty) decision and have clear documented justification. Hence +1 for a PDEP.

> My vote is a clear +1, advantages of ensuring pyarrow is always available are more valuable than the limitations to the installation that I'm unsure any user will really face.

Fair point. A more objective, maybe quantative, definition of "more valuable" would surely strengthen the argument in favor?

For instance @WillAyd mentioned pypistats and my thinking, related to PDEP-9, is how many packages (and how important to the ecosystem) would say just use pandas to provide interoperability and not functionality?

**Comment by jbrockmendel** [comment]
> Having something like bytes inferring as "bytes[pyarrow]" would be nice as well. Also nested data structures (but support for those is poor right now).

xref #52429

**Comment by fangchenli** [comment]
> 4. I _thought_ our goal was to become backend agnostic, i.e. there may be a future where numpy is optional and you can pick either backend

Then adding a Jax backend would be awesome.

**Comment by adrinjalali** [comment]
We recently enabled jupyter lite on our examples on the scikit-learn side, and by default we're including pandas. Looking at the size of the wheels for pyarrow, they're somewhere between 20-35MB based on the platform. That's a significant increase for users who would be loading the example in their browser.

We also have been having trouble with the latest pandas when pip installed in a mamba environment, since conda-lock fails in this case, and that's because pandas=2.0 requires tzdata, and the env ends up with two tzdata. It's not a pandas bug per say, but it complicates workflows (we're sticking with an older pandas for now for that env). That is to say even a small dependency like tzdata which should be present in most environments anyway, complicates things.

Pandas is a library on which, other libraries depend, and any dependency added here adds to the dependency tree to those environments, and pyarrow is by far not a trivial dependency.

All of that is to say, from my perspective, it would be a pity if pyarrow becomes a mandatory dependency.

**Comment by MarcoGorelli** [comment]
thanks @adrinjalali for sharing your perspective! the conversation has mostly moved to https://github.com/pandas-dev/pandas/pull/52711, I'd suggest commenting there for visibility

**Comment by alippai** [comment]
Maybe something like "pyarrow compatible interface is runtime required" would make more sense? Eg using the Go Arrow implementation, Arrow Rust or Arrow2 Rust implementation as a drop in replacement could help with some of the issues (platform support, binary sizes). There is already an [Array API](https://data-apis.org/array-api/latest/) and [dataframe API](https://data-apis.org/dataframe-api/draft/index.html), specifying a "ColumnStorage API" which different backends can implement doesn't sound bad (while we can also mark the different Arrow backends so polars and other tools can have assumptions about the data layout over the more generic ColumnStorage API)

My understanding was that it is the design goal of Arrow to set a few reasonable assumptions (columnar storage, masked arrays) and provide a data format + data contract. 

Pyarrow provides definitely more than this: datasets, pyarrow.compute, pyarrow.parquet. Perhaps Pandas should start relying on the core functionality, but not the rest? This would require a `pyarrow-core` package ofc, but that would be smaller and easier to make installable by `pip install pyarrow-core` if no wheels are available

**Comment by jreback** [comment]
Part of the rationale for using pyarrow as a runtime dependency is to reduce pandas core development burdens - sure using just a core part of arrow might be nice but it's not that helpful in addressing one of the most important reasons to have a required dependency. The point is to take advantage of the eco system w/o have even more in built functionality in pandas.

**Comment by Dr-Irv** [comment]
> Part of the rationale for using pyarrow as a runtime dependency is to reduce pandas core development burdens

In the PDEP #52711 (where we really should be having this discussion), I have asked here to get a better understanding of that burden (see https://github.com/pandas-dev/pandas/pull/52711#pullrequestreview-1394681744)

**Comment by jjerphan** [comment]
For your information, installing pyarrow after pandas in a fresh conda environment increases its size by more than 700 MiB, totaling 1.1GiB of packages for the environment

<details>
<summary>Packages size breakdown</summary>

```
libgoogle-cloud-2.12.0-h840a212_1 :                 46106632 bytes,
python-3.11.4-hab00c5b_0_cpython :                  30679695 bytes,
libarrow-12.0.1-h10ac928_8_cpu :                    27696900 bytes,
ucx-1.14.1-h4a2ce2d_3 :                             15692979 bytes,
pandas-2.0.3-py311h320fe9a_1 :                      14711359 bytes,
numpy-1.25.2-py311h64a7726_0 :                      8139293 bytes,
libgrpc-1.56.2-h3905398_1 :                         6331805 bytes,
libopenblas-0.3.23-pthreads_h80387f5_0 :            5406072 bytes,
aws-sdk-cpp-1.10.57-h85b1a90_19 :                   4055495 bytes,
pyarrow-12.0.1-py311h39c9aba_8_cpu :                3989550 bytes,
libstdcxx-ng-13.1.0-hfd8a6a1_0 :                    3847887 bytes,
rdma-core-28.9-h59595ed_1 :                         3735644 bytes,
libthrift-0.18.1-h8fd135c_2 :                       3584078 bytes,
tk-8.6.12-h27826a3_0 :                              3456292 bytes,
openssl-3.1.2-hd590300_0 :                          2646546 bytes,
libprotobuf-4.23.3-hd1fb520_0 :                     2506133 bytes,
libgfortran5-13.1.0-h15d22d2_0 :                    1437388 bytes,
pip-23.2.1-pyhd8ed1ab_0 :                           1386212 bytes,
krb5-1.21.2-h659d440_0 :                            1371181 bytes,
libabseil-20230125.3-cxx17_h59595ed_0 :             1240376 bytes,
orc-1.9.0-h385abfd_1 :                              1020883 bytes,
ncurses-6.4-hcb278e6_0 :                            880967 bytes,
pygments-2.16.1-pyhd8ed1ab_0 :                      853439 bytes,
jedi-0.19.0-pyhd8ed1ab_0 :                          844518 bytes,
libsqlite-3.42.0-h2797004_0 :                       828910 bytes,
libgcc-ng-13.1.0-he5830b7_0 :                       776294 bytes,
ld_impl_linux-64-2.40-h41732ed_0 :                  704696 bytes,
libnghttp2-1.52.0-h61bc06f_0 :                      622366 bytes,
ipython-8.14.0-pyh41d4057_0 :                       583448 bytes,
bzip2-1.0.8-h7f98852_4 :                            495686 bytes,
setuptools-68.1.2-pyhd8ed1ab_0 :                    462324 bytes,
zstd-1.5.2-hfc55251_7 :                             431126 bytes,
libevent-2.1.12-hf998b51_1 :                        427426 bytes,
libgomp-13.1.0-he5830b7_0 :                         419184 bytes,
xz-5.2.6-h166bdaf_0 :                               418368 bytes,
libcurl-8.2.1-hca28451_0 :                          372511 bytes,
s2n-1.3.48-h06160fa_0 :                             369441 bytes,
aws-crt-cpp-0.21.0-hb942446_5 :                     320415 bytes,
readline-8.2-h8228510_1 :                           281456 bytes,
libssh2-1.11.0-h0841786_0 :                         271133 bytes,
prompt-toolkit-3.0.39-pyha770c72_0 :                269068 bytes,
libbrotlienc-1.0.9-h166bdaf_9 :                     265202 bytes,
python-dateutil-2.8.2-pyhd8ed1ab_0 :                245987 bytes,
re2-2023.03.02-h8c504da_0 :                         201211 bytes,
aws-c-common-0.9.0-hd590300_0 :                     197608 bytes,
aws-c-http-0.7.11-h00aa349_4 :                      194366 bytes,
pytz-2023.3-pyhd8ed1ab_0 :                          186506 bytes,
aws-c-mqtt-0.9.3-hb447be9_1 :                       162493 bytes,
aws-c-io-0.13.32-h4a1a131_0 :                       154523 bytes,
ca-certificates-2023.7.22-hbcca054_0 :              149515 bytes,
lz4-c-1.9.4-hcb278e6_0 :                            143402 bytes,
python-tzdata-2023.3-pyhd8ed1ab_0 :                 143131 bytes,
libedit-3.1.20191231-he28a2e2_2 :                   123878 bytes,
keyutils-1.6.1-h166bdaf_0 :                         117831 bytes,
tzdata-2023c-h71feb2d_0 :                           117580 bytes,
gflags-2.2.2-he1b5a44_1004 :                        116549 bytes,
glog-0.6.0-h6f12383_0 :                             114321 bytes,
c-ares-1.19.1-hd590300_0 :                          113362 bytes,
libev-4.33-h516909a_1 :                             106190 bytes,
aws-c-auth-0.7.3-h28f7589_1 :                       101677 bytes,
libutf8proc-2.8.0-h166bdaf_0 :                      101070 bytes,
traitlets-5.9.0-pyhd8ed1ab_0 :                      98443 bytes,
aws-c-s3-0.3.14-hf3aad02_1 :                        86553 bytes,
libexpat-2.5.0-hcb278e6_1 :                         77980 bytes,
libbrotlicommon-1.0.9-h166bdaf_9 :                  71065 bytes,
parso-0.8.3-pyhd8ed1ab_0 :                          71048 bytes,
libzlib-1.2.13-hd590300_5 :                         61588 bytes,
libffi-3.4.2-h7f98852_5 :                           58292 bytes,
wheel-0.41.1-pyhd8ed1ab_0 :                         57374 bytes,
aws-c-event-stream-0.3.1-h2e3709c_4 :               54050 bytes,
aws-c-sdkutils-0.1.12-h4d4d85c_1 :                  53123 bytes,
aws-c-cal-0.6.1-hc309b26_1 :                        50923 bytes,
aws-checksums-0.1.17-h4d4d85c_1 :                   50001 bytes,
pexpect-4.8.0-pyh1a96a4e_2 :                        48780 bytes,
libnuma-2.0.16-h0b41bf4_1 :                         41107 bytes,
snappy-1.1.10-h9fff704_0 :                          38865 bytes,
typing_extensions-4.7.1-pyha770c72_0 :              36321 bytes,
libuuid-2.38.1-h0b41bf4_0 :                         33601 bytes,
libbrotlidec-1.0.9-h166bdaf_9 :                     32567 bytes,
libnsl-2.0.0-h7f98852_0 :                           31236 bytes,
wcwidth-0.2.6-pyhd8ed1ab_0 :                        29133 bytes,
asttokens-2.2.1-pyhd8ed1ab_0 :                      27831 bytes,
stack_data-0.6.2-pyhd8ed1ab_0 :                     26205 bytes,
executing-1.2.0-pyhd8ed1ab_0 :                      25013 bytes,
_openmp_mutex-4.5-2_gnu :                           23621 bytes,
libgfortran-ng-13.1.0-h69a702a_0 :                  23182 bytes,
libcrc32c-1.1.2-h9c3ff4c_0 :                        20440 bytes,
aws-c-compression-0.2.17-h4d4d85c_2 :               19105 bytes,
ptyprocess-0.7.0-pyhd3deb0d_0 :                     16546 bytes,
pure_eval-0.2.2-pyhd8ed1ab_0 :                      14551 bytes,
libblas-3.9.0-17_linux64_openblas :                 14473 bytes,
liblapack-3.9.0-17_linux64_openblas :               14408 bytes,
libcblas-3.9.0-17_linux64_openblas :                14401 bytes,
six-1.16.0-pyh6c4a22f_0 :                           14259 bytes,
backcall-0.2.0-pyh9f0ad1d_0 :                       13705 bytes,
matplotlib-inline-0.1.6-pyhd8ed1ab_0 :              12273 bytes,
decorator-5.1.1-pyhd8ed1ab_0 :                      12072 bytes,
backports.functools_lru_cache-1.6.5-pyhd8ed1ab_0 :  11519 bytes,
pickleshare-0.7.5-py_1003 :                         9332 bytes,
prompt_toolkit-3.0.39-hd8ed1ab_0 :                  6731 bytes,
backports-1.0-pyhd8ed1ab_3 :                        5950 bytes,
python_abi-3.11-3_cp311 :                           5682 bytes,
_libgcc_mutex-0.1-conda_forge :                     2562 bytes,
```

</details>

Moreover `pyarrow` also depends on `libarrow` which itself depends on [several notable C and C++ libraries](https://github.com/conda-forge/arrow-cpp-feedstock/blob/main/recipe/meta.yaml#L99-L147). This constraints the installation of other packages whose dependencies might be incompatible with `libarrow`'s, making pandas potentially unusable in some context.

Have you considered those two observations as drawbacks before taking the decision?

I am afraid that making `pyarrow` a required dependency will come with costly consequences for users and downstream libraries' developers and maintainers. :confused:
