### ISSUE TITLE
BUG: Results of series `bitwise` ufunc operations are being casted to `bool` in `pandas-2.0`

### ISSUE THREAD

**Issue by galipremsagar** [pandas-dev/pandas#52500]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
In [1]: import pandas as pd

In [2]: import numpy as np

In [3]: np.bitwise_xor
Out[3]: <ufunc 'bitwise_xor'>

In [4]: a = pd.Series([1, 2, 3], index=[10, 11, 23], name="a")

In [5]: b = pd.Series([10, 20, 30], index=[11, 10, 23], name="a")

In [9]: np.bitwise_xor(a, b)
Out[9]: 
10    True
11    True
23    True
Name: a, dtype: bool

In [10]: np.bitwise_xor(a.to_frame(), b.to_frame())
Out[10]: 
     a
10  21
11   8
23  29
```

### Issue Description

`bitwise_xor` on `Series` & `DataFrame` are returning different results(i.e., `bool` & `int` respectively).

### Expected Behavior

Consistent output between `Series` & `DataFrame`:
```python
In [9]: np.bitwise_xor(a, b)
Out[9]: 
10    21
11    8
23    29
Name: a, dtype: int64
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : c2a7f1ae753737e589617ebaaff673070036d653
python           : 3.10.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-76-generic
Version          : #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.0rc1
numpy            : 1.23.5
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.6.1
pip              : 23.0.1
Cython           : 0.29.34
pytest           : 7.2.2
hypothesis       : 6.70.2
sphinx           : 5.3.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.12.0
pandas_datareader: None
bs4              : 4.12.0
bottleneck       : None
brotli           : 
fastparquet      : None
fsspec           : 2023.3.0
gcsfs            : None
matplotlib       : None
numba            : 0.56.4
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 10.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : 2023.3.0
scipy            : 1.10.1
snappy           : 
sqlalchemy       : 1.4.46
tables           : None
tabulate         : 0.9.0
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : None
qtpy             : None
pyqt5            : None

</details>

**Comment by mroeschke** [comment]
Looks like `maybe_dispatch_ufunc_to_dunder_op` is dispatching this to `a ^ b` which returns a boolean result. Index doesn't have this behavior

```
In [5]: a ^ b
Out[5]: 
10    True
11    True
23    True
Name: a, dtype: bool

In [6]: np.bitwise_xor(pd.Index(a), pd.Index(b))
Out[6]: Index([11, 22, 29], dtype='int64', name='a')
```

Not sure if that's intentional cc @jbrockmendel

**Comment by jbrockmendel** [comment]
Haven't looked too closely, but I expect the difference is related to the bespoke reindexing/casting logic in the Series logical op, xref #52538
