### ISSUE TITLE
BUG: The count() API does not consider inf as NA (with pandas.options.mode.use_inf_as_na = True) when dtype is "double[pyarrow]"

### ISSUE THREAD

**Issue by tinadu0806** [pandas-dev/pandas#52501]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>>import pandas as pd
>>>pd.options.mode.use_inf_as_na = True
>>>s = pd.Series([1.1, float("inf"), float("-inf"), 2.3], dtype="double[pyarrow]")
>>>s
0    1.1
1    NaN
2    NaN
3    2.3
dtype: double[pyarrow]
>>>s.count()
4
>>>type(s.count())
<class 'numpy.int64'>
```

### Issue Description

When create a pandas series with pyarrow type "double[pyarrow]", after setting pd.options.mode.use_inf_as_na = True, the inf values are still counted. Also it returns a numpy int64 type scalar instead of pyarrow double scalar.

### Expected Behavior

After setting pd.options.mode.use_inf_as_na = True, above s.count() should return 2 as result.

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by mroeschke** [comment]
Thanks for the report. Yeah generally no extension array types will respect this option.

We are also considering deprecating the `use_inf_as_na` option https://github.com/pandas-dev/pandas/issues/51684 in favor of replacing `inf` with `na` first.
