### ISSUE TITLE
DEPR: Deprecate Series.ravel

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#52511]
The methods looks quite unnecessary, the EAs are a no-op and for NumPy users can simply call ravel on the NumPy array.

**Comment by jorisvandenbossche** [comment]
+1 (I suppose this is mostly a left-over from Series subclassing np.ndarray initially (long time ago ;))

**Comment by jbrockmendel** [comment]
+1

**Comment by ramvikrams** [comment]
@phofl should I deprecate it ?
