### ISSUE TITLE
DEV: Upgrade Python development version to 3.9/3.10

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#52513]
We can drop Python 3.8 support soonish, but to get there we have to upgrade our development python version from 3.8. I'd prefer 3.10, but ran into a Doc problem when looking into this a couple of weeks ago (same for 3.9).

Just rebased the PR (https://github.com/pandas-dev/pandas/pull/51133), but would be great if someone else could take a look if the doc build is still failing.

We shouldn't upgrade to 3.11, because numba isn't yet compatible with 3.11.

**Comment by twoertwein** [comment]
Is 2.1 planned to release after Apr 05, 2024? I think pandas followed numpy in the past to determine the minimum python version https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table

**Comment by phofl** [comment]
NumPy already dropped 3.8 on main, and according to their table they officially drop it next week. I don't want to drop 3.9, but I would prefer using 3.10 as development version.

**Comment by mroeschke** [comment]
Looks to have been done with https://github.com/pandas-dev/pandas/pull/51133 so closing
