### ISSUE TITLE
DOC: Suggested `build_ext` command may fail on low-resource machines

### ISSUE THREAD

**Issue by cai-lw** [pandas-dev/pandas#52529]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/development/contributing_environment.html#step-3-build-and-install-pandas

### Documentation problem

On low resource machines `python setup.py build_ext -j 4` may fail due to concurrent compiling jobs exhausting memory.

I had this problem when developing in GitHub Codespace, in which the smallest (and default) machine has only 2 CPU cores and 4GB of memory.

### Suggested fix for documentation

Three options:
1. Add a comment `# The number after -j is the number of compiling jobs run in parallel. Change it according to your machine's hardware spec`.
2. Change the command to `python setup.py build_ext -j 2`.
3. [Setting a minimum specification for codespace machines](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/configuring-dev-containers/setting-a-minimum-specification-for-codespace-machines)

**Comment by phofl** [comment]
Thanks for your report. I'd prefer option 1
