### ISSUE TITLE
BUG: Either incorrect unit validation for 'T' in to_timedelta() or incorrect documentation

### ISSUE THREAD

**Issue by juliangall** [pandas-dev/pandas#52536]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
td = pd.to_timedelta(1, unit='t')  # success
td = pd.to_timedelta(1, unit='T')  # runs ok but fails type-checking in IDE
```

### Issue Description

The specification of the unit parameter for to_timedelta() in https://github.com/pandas-dev/pandas/tree/v2.0.0/pandas/core/tools/timedeltas.py is as follows:

`unit: UnitChoices | None = None`

The [documentation](https://pandas.pydata.org/docs/reference/api/pandas.to_timedelta.html) for to_timedelta() (and the comment in the code) allows for (among others):

> ‘m’ / ‘minute’ / ‘min’ / ‘minutes’ / ‘T’

The allowed values in UnitChoices (https://github.com/pandas-dev/pandas/tree/main/pandas/_libs/tslibs/timedeltas.pyi) include 't', but not 'T'.

### Expected Behavior

It seems to me that it is usual to allow upper case 'T' as a specifier for minute, but others may know better.

Either 'T' should be allowed in UnitChoices, or the to_timedelta() documentation should be updated to specify lower case 't'

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 478d340667831908b5b4bf09a2787a11a14560c9
python           : 3.9.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 22.4.0
Version          : Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_GB.UTF-8
pandas           : 2.0.0
numpy            : 1.24.2
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 65.5.1
pip              : 22.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : 1.4.47
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by topper-123** [comment]
If you look down the code path, you'll see that the code will be converted to lower case:

https://github.com/pandas-dev/pandas/blob/1bf3ff77174ec6448c94c2dd98882add9fecb33a/pandas/_libs/tslibs/timedeltas.pyx#L708-L730

So code-wise, the choice of case won't matter.

Now if you look into the type definition, you'll only see lowercase t, i.e. upper case T will fail.

https://github.com/pandas-dev/pandas/blob/1bf3ff77174ec6448c94c2dd98882add9fecb33a/pandas/_libs/tslibs/timedeltas.pyi#L22-L64

Upper case T should probably be in the `UnitChoices` list. A PR is welcome.

**Comment by ezqdavid** [comment]
Hi, i would like to take this issue if i can. It would be my first PR in an open source project.

**Comment by ezqdavid** [comment]
take

**Comment by topper-123** [comment]
👍

**Comment by natmokval** [comment]
Hi @ezqdavid, wouldn’t you mind,  if I create pr for this issue?

**Comment by jbrockmendel** [comment]
T and l seem really weird here.  i think we should deprecate them.

**Comment by natmokval** [comment]
> T and l seem really weird here. i think we should deprecate them.

Thank you, @jbrockmendel for the comment. I will update the documentation for `to_timedelta` and remove `"T"` from the list of units. I am not sure, if should we raise a deprecation warning in case a user tries to apply "`T"`. What's your opinion?

I have another question. I didn't find unit abbreviations `"I"` or `"i"`. There is `"i" `in _TYPE_MAP and `"I"` in _parse_code_table. Could you please explain, what you mean by `"I"`?

**Comment by topper-123** [comment]
+1 from me. The upper and lower t are synomous, so both can be deprecated.

**Comment by anttimc** [comment]
I haven't figured how 'H' for hour got deprecated after issue?

I'd just like to note that the deprecations in pandas cause huge amount of work in dependent projects.

**Comment by MarcoGorelli** [comment]
hi @anttimc - I'll find the issue, looks like the referenced issue was incorrect

> I'd just like to note that the deprecations in pandas cause huge amount of work in dependent projects.

sorry about that - which project are you referring to? if you use `'h'`, it should work across old and new pandas versions

**Comment by MarcoGorelli** [comment]
For 'H' in particular, it looks like I'd suggested it here - https://github.com/pandas-dev/pandas/pull/54061#discussion_r1301462802. There probably should have been more discussion to be fair, although it did seem in-line with the other renamings suggested here

With https://github.com/pandas-dev/pandas/pull/55502 in, the rule would then be that sub-daily frequencies (Ticks, fixed frequencies) are all lower-case, whereas daily and above upper-case

The issue with case-insensitivity is that then this happens:
```
In [6]: pandas.date_range('2000', periods=3, freq='NS')  # nanosecond, cool
Out[6]:
DatetimeIndex([          '2000-01-01 00:00:00',
               '2000-01-01 00:00:00.000000001',
               '2000-01-01 00:00:00.000000002'],
              dtype='datetime64[ns]', freq='N')

In [7]: pandas.date_range('2000', periods=3, freq='US')  # microsecond, cool
Out[7]:
DatetimeIndex([       '2000-01-01 00:00:00', '2000-01-01 00:00:00.000001',
               '2000-01-01 00:00:00.000002'],
              dtype='datetime64[ns]', freq='U')

In [8]: pandas.date_range('2000', periods=3, freq='MS')  # wait, this isn't millisecond?
Out[8]: DatetimeIndex(['2000-01-01', '2000-02-01', '2000-03-01'], dtype='datetime64[ns]', freq='MS')
```

An alternative would have been to keep case-insensitivity, but rename `'MS'` to `MB'`, but that got pushback too https://github.com/pandas-dev/pandas/issues/56840

Correcting historic issues is tricky - we either leaves things as they are and leave inconsistencies and issues around, or deprecate towards more consistent and predictable behaviour

I understand that this one is a pain for people building on top of pandas, but I thought a simple find-and-replace would be enough here - if that's not the case, please do report an issue, it's a sign that something may not be right. Thanks 🙏
