### ISSUE TITLE
ENH: Differing variable name for quantile vs rolling.quantile

### ISSUE THREAD

**Issue by BroadbentJim** [pandas-dev/pandas#52550]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

As of V2 in the code and in the documentation, the quantile method and the rolling quantile method take a different variable for the quantile to be calculated.
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.quantile.html
https://pandas.pydata.org/docs/reference/api/pandas.core.window.rolling.Rolling.quantile.html

where we have: 
q float for the former (quantile) and
quantile float for the latter (rolling.quantile).

I feel like this is unnecessary and provides a small mental overhead.
I propose that it should be changed to being consistent. Not sure which is better, perhaps q as used in quantile and is shorter but clear.

### Feature Description

def rolling.quantile(self,
      q,
     ....):

### Alternative Solutions

quantile = q

**Comment by jbrockmendel** [comment]
would accept a PR deprecating the Rolling version to match

**Comment by Charlie-XIAO** [comment]
Hi @jbrockmendel I would like to make a PR for this, but this is the first time I make deprecation. Just want to make sure in advance, is the following approach acceptable?
```python
def quantile(self, q=None, interpolation="linear", numeric_only=False, *, quantile=None):
        if quantile is not None:
            warnings.warn(
                "The 'quantile' argument in Rolling.quantile "
                "has been deprecated. Use 'q' instead.",
                FutureWarning,
                stacklevel=find_stack_level(),
            )
            q = quantile if q is None else q

        # ...
```

**Comment by jbrockmendel** [comment]
There's a decorator called def deprecate_kwarg.  Try using that.

**Comment by Charlie-XIAO** [comment]
Thanks @jbrockmendel! Here is the PR.
