### ISSUE TITLE
BUILD: 

### ISSUE THREAD

**Issue by Artista001** [pandas-dev/pandas#52609]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Windows-10-10.0.19043-SP0

### Installation Method

pip install

### pandas Version

0.21

### Python Version

3

### Installation Logs

I encountered an error while attempting to install pandas<0.21 using pip on Windows 10. Specifically, the error occurred during the preparation of metadata, with the following message:

Preparing metadata (pyproject.toml) ... error
error: subprocess-exited-with-error

  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      error in pandas setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          pytz >= 2011k
               ~~~~~~~^
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.


The error message suggests that there was a problem with the metadata generation process during installation. Specifically, there was an issue with the install_requires command in the setup.py file for pandas. The error message indicates that a valid version specifier was expected after the pytz >= 2011k requirement, but it was missing. This issue caused the metadata generation to fail, and subsequently the installation of the package failed.

**Comment by phofl** [comment]
Hi, thanks for your report. We don't support these old versions anymore.
