### ISSUE TITLE
Support for numpy strings

### ISSUE THREAD

**Issue by cancan101** [pandas-dev/pandas#5261]
This is more of a question than an issue:

why does Pandas use object type rather than the native fixed length numpy strings?

For example:

```
In [24]: np.array(["foo", "baz"])
Out[24]: 
array(['foo', 'baz'], 
      dtype='|S3')
```

but:

```
In [29]: pd.DataFrame({"a":np.array(["foo", "baz"])}).dtypes
Out[29]: 
a    object
dtype: object
```

**Comment by jreback** [comment]
see comments on #10351. In light of categoricals (and lack of nan support) this is a non-starter.

**Comment by jreback** [comment]
But will leave open as a specialized dtype option for a certain subset of analysis (e.g. its prob useful to the bio guys)

**Comment by frol** [comment]
That is unfortunate to me that Pandas cannot just do what I asked it to do. I know that I should exercise care using fixed width strings, but they are much faster than Python objects.

**Comment by kawing-chiu** [comment]
Another drawback to not having fixed-length numpy string: When using pyarrow, presence of columns with a dtype of 'object' will prevent pyarrow to (de)serialize in a zero-copy fashion. 

As the user of the data, often I can determine the maximum length of some text columns. The string routines can happily truncate my strings to the specified length.

**Comment by TomAugspurger** [comment]
I suspect that proper-string support will land sometime soon. Perhaps next year sometime.

In the meantime, you could write a simple extension array to convince pandas to not coerce your fixed-width ndarray of strings to object.

You shouldn't take this direct approach, since it's using private methods, but this is the basic idea:

```python
In [39]: class NumPyString(pd.core.arrays.PandasArray):
    ...:     _typ = 'extensionarray'

In [40]: arr = np.array(['a', 'b', 'c'])

In [41]: s = pd.Series(NumPyString(arr))

In [42]: s
Out[42]:
0    a
1    b
2    c
dtype: str32

In [46]: s.array._ndarray
Out[46]: array(['a', 'b', 'c'], dtype='<U1')
```

Things like string methods won't work either.

**Comment by rhshadrach** [comment]
With StringDType, I think this issue can be closed.

**Comment by TomAugspurger** [comment]
Agreed, thanks. xref https://github.com/pandas-dev/pandas/issues/35169 for those interested in following along.
