### ISSUE TITLE
QST: How to convert dtype from datetime64[ns] to datetime

### ISSUE THREAD

**Issue by ChillarAnand** [pandas-dev/pandas#52663]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/39207640/python-pandas-how-do-i-convert-from-datetime64ns-to-datetime

**Comment by MarcoGorelli** [comment]
dupe https://github.com/pandas-dev/pandas/issues/52663

**Comment by ChillarAnand** [comment]
Duplicate of https://github.com/pandas-dev/pandas/issues/52664
