### ISSUE TITLE
ENH: Avoid warnings causing code to crash

### ISSUE THREAD

**Issue by pettzilla1** [pandas-dev/pandas#52666]
### Feature Type

- [X] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [X] Removing existing functionality in pandas

### Problem Description

Hi I've looked over the code and am getting an issue with PYPDF2 data when the set with copy warning is being raised, would it be possible for warning code to be inside a try look so raising a warning doesn't break a process ?
  

### Feature Description

Nest Warnings in a try statement to avoid the raising of one causing an error

### Alternative Solutions

Having a default warning raised where the warning cant be produced in full

**Comment by MarcoGorelli** [comment]
hi @pettzilla1  - could you provide a reproducible example please?

**Comment by pettzilla1** [comment]
Hi @MarcoGorelli  unfortunately I cant send over an example,

It seems to be an issue when the warning tries to asses where the objects data has originally come from it recursively go's back and tries to access something it shouldn't be , 

needless to say however the warnings should ether be inside a try loop or something else to avoid a system falling over due to a warning trying to be raised and failing , especially if it is part of an update or process change

**Comment by MarcoGorelli** [comment]
no worries, if/when you can come up with a reproducible example we can take a look, at the moment there's just nothing to go off of
