### ISSUE TITLE
ENH: Add use_itertuples parameter to DataFrame.apply(axis=1) for improved performance

### ISSUE THREAD

**Issue by apuapaquola** [pandas-dev/pandas#52670]
### Feature Type

- [x] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I would like to propose a modification to the DataFrame.apply(axis=1) function to improve its performance. The current implementation of df.apply(axis=1) converts each row to a Series before applying the user-supplied function. This conversion can be computationally expensive, particularly for large DataFrames. (for a benchmark see 
https://www.kaggle.com/code/scgupta/efficient-alternatives-to-pandas-dataframe-apply)

When vectorization is not possible and the DataFrame is large and has rows with multiple types, applying a function using itertuples() is much faster than using apply(axis=1).

I would like to be able to use the intuitive syntax of apply(axis=1) with a faster underlying implementation provided by itertuples().

### Feature Description

The modified API for the DataFrame.apply method would look like this:

```
def apply(self, func, axis=0, raw=False, result_type=None, use_itertuples=False, args=(), **kwds):
    """
    ...
    use_itertuples : bool, default False
        Use itertuples() to iterate over the rows of the DataFrame when axis=1.
        This can improve performance by avoiding the conversion of rows to Series.
        Note that the user-supplied function should be compatible with the namedtuple
        representation of DataFrame rows.
    ...
    """

```
Benefits of this change include:

* Improved performance for certain use cases, particularly when working with large DataFrames.
* Providing users with greater flexibility when applying functions to DataFrames.
* Maintaining backward compatibility by defaulting to the existing behavior (use_itertuples=False).

Possible caveats: 
* Function compatibility: The user-supplied function must be compatible with the namedtuple representation of DataFrame rows that itertuples() generates. Users may need to modify their functions to work correctly with this representation, which could be an inconvenience.
* Conversion of column data types to native python: When using itertuples(), the data types of the columns may not be preserved, as they are converted to native Python types. This could cause issues for functions that rely on specific Pandas data types or behaviors.
* Inconsistency in behavior when modifying the DataFrame in place: When using the namedtuple representation, functions that modify the row data will not affect the original DataFrame, unlike when using the Series representation. This could lead to unexpected behavior for users who are not aware of this difference. However, this is an issue only if all row have the same data type. When rows have different data types, the current implementation of df.apply(axis=1) does not modify the original DataFrame anyway.

### Alternative Solutions

There are many ways to apply a function to DataFrame rows, but the apply() syntax is very intuitive and it would be great to use it with a faster implementation.

The proposed solution above maintains compatibility with current apply() behavior. A more general approach would be to 
use a "mode" argument instead (and deprecate the "raw" argument).

```
def apply(self, func, axis=0,  result_type=None, mode="Series", args=(), **kwds):
    """
    ...
    mode: str, default "Series"
       "Series" : passes each row or column as a Series to the function.
       "ndarray": the passed function will receive ndarray objects instead. (equivalent to raw=True).
       "tuple":  the passed function will receive tuples instead.
       "namedtuple":  the passed function will receive namedtuple objects instead.
       "dict": the passed function will receive dict objects instead.
    ...
    """

```

I would appreciate your feedback on this proposal. If there's interest in this change, I'm willing to work on it.

 Thank you!

**Comment by topper-123** [comment]
Hi @apuapaquola . Thanks for this suggestion.

You've touched on some points of pandas that are slow, almost as a limitation of the design of Pandas:

1: apply with axis=1 and 
2: operations on columns with dtype `object` and
3: iteratation through the DataFrame.

All  are likely slow for many operations for various reasons.

The recommended way to get better performance is first and foremost to use suitable dtypes rather than `object` and do vectorized operations on the data, rather than operate iteratively.

Pandas is already quite a complex package and I'm -1 on adding options to make working with ´object` dtypes faster.

If I misunderstood your proposal, feel free to add to the thread.

**Comment by apuapaquola** [comment]
Hi  @topper-123 ,

My proposal is to have a faster apply(axis=1) for situations in which vectorization is not possible.

I think you did misunderstand part of it when you said:
"Pandas is already quite a complex package and I'm -1 on adding options to make working with object dtypes faster."

This proposal is precisely to avoid using the object dtype and work with tuples instead, which is much faster, according to benchmarks.

I think that apply() is a great feature of pandas that encourages writing clean and expressive code, and having it be faster for axis=1 will encourage better code.

**Comment by topper-123** [comment]
You'd still need to create one tuple per row and unpack each value of each row, do ops in python code and put it back. That's still dog slow and you're optimizing for code that will be bad in most cases.

Why won't doing `apply(func, axis=1, raw=True)` be much faster? It that won't work, can you supply a working snippet of what you're trying to do and I'll look at it.

**Comment by mroeschke** [comment]
Thanks for the report but agreed that adding this option would not be appropriate for apply so closing
