### ISSUE TITLE
TST: Test dir of pandas.api.*

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#52688]
We currently do not test the `dir` of submodules of `pandas.api`. In #48578, a test is being added for `pandas.api.typing`. Tests like this should be added for each of the submodules - extensions, indexers, interchange, and types.

**Comment by Snehaaa18** [comment]
Hi I am a first time contributor and would like to contribute on this issue ,if open can you pls direct me on this issue ?

**Comment by Swarno-Coder** [comment]
Can I work on this? I can do this if you assign me for this issue, but I only need some of your guidance if needed. Could you do this?😊

**Comment by Aringopalan** [comment]
Hello  @rhshadrach sir , i am a first time contributor to this project and i  am willing to work on this issue.

**Comment by SecretLake** [comment]
take
