### ISSUE TITLE
DOC: `index_col` parameter of `pandas.read_excel` can be types other than `int`

### ISSUE THREAD

**Issue by function2-llx** [pandas-dev/pandas#52716]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

[pandas.read_excel](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html)

### Documentation problem

The doc states that the type of `index_col` is "int, list of int, default None", indicating the index of the column(s). However, using column name(s) also works.

### Suggested fix for documentation

Add string type for `index_col` and explain both column index(es) and name(s) work for `index_col`.

**Comment by NikolayBoev** [comment]
take
