### ISSUE TITLE
ENH: We need to have 'count' as default for aggfunc parameter under 'pivot_table'

### ISSUE THREAD

**Issue by Lokeshrathi** [pandas-dev/pandas#52725]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [X] Removing existing functionality in pandas

### Problem Description

Since we are using Pivot_table inspired from spreadsheet-style, we should include 'count' as the default aggregate function instead of numpy.mean.
'count' may be a more appropriate default because it is a simpler and more universal way to summarize data.

### Feature Description

Change the Default to Count instead of Mean

### Alternative Solutions

Change the Default to Count instead of Mean

**Comment by mroeschke** [comment]
Thanks for the suggestion but I would be -1 on this change. Count vs mean is a fairly arbitrary choice and would cause a lot of churn for existing users so closing
