### ISSUE TITLE
reset_index for columns

### ISSUE THREAD

**Issue by cancan101** [pandas-dev/pandas#5275]
Is there a reset_index equivalent for the column headings? In other words, if the column names are an MultiIndex, how would I drop one of the levels?

**Comment by rhshadrach** [comment]
If I'm understanding this, I think the following suffices:

```
df = pd.DataFrame([1, 2, 3], columns=pd.MultiIndex.from_tuples([(1, 2)]))
df.columns = df.columns.droplevel(0)
```

**Comment by MarcoGorelli** [comment]
closing as the above seems like the correct solution

**Comment by MarcoGorelli** [comment]
but please ping if you disagree / have an example with desired output
