### ISSUE TITLE
BUG: `round`, `ceil`, `floor` returning incorrect results with Division By Zero warning in `pandas-2.0`

### ISSUE THREAD

**Issue by galipremsagar** [pandas-dev/pandas#52761]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
In [1]: import pandas as pd

In [2]: s = pd.Series(["2020-05-31 08:00:00", "2000-12-31 04:00:05", "1800-03-14 07:30:20"], dtype='datetime64[ms]')

In [3]: s
Out[3]: 
0   2020-05-31 08:00:00
1   2000-12-31 04:00:05
2   1800-03-14 07:30:20
dtype: datetime64[ms]

In [4]: s.dt.round('U')
/nvme/0/pgali/envs/cudfdev/lib/python3.10/site-packages/pandas/core/arrays/datetimelike.py:2006: RuntimeWarning: divide by zero encountered in divmod
  result_i8 = round_nsint64(values, mode, nanos)
Out[4]: 
0   1970-01-01
1   1970-01-01
2   1970-01-01
dtype: datetime64[ms]
```

### Issue Description

Performing a rounding operation of resolution lesser than the dtype, or when there is sub-second data and the rounding resolution is a sub-second data should ideally be a no-op. Instead we seem to be running into division by zero scenario and returning incorrect results.

### Expected Behavior

```python
In [3]: s.dt.round('U')
Out[3]: 
0   2020-05-31 08:00:00
1   2000-12-31 04:00:05
2   1800-03-14 07:30:20
dtype: datetime64[ms]
```

### Installed Versions

<details>

In [5]: pd.show_versions()
/nvme/0/pgali/envs/cudfdev/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit           : 478d340667831908b5b4bf09a2787a11a14560c9
python           : 3.10.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-76-generic
Version          : #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.0
numpy            : 1.23.5
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.6.1
pip              : 23.1
Cython           : 0.29.34
pytest           : 7.3.1
hypothesis       : 6.72.0
sphinx           : 5.3.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.12.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : 
fastparquet      : None
fsspec           : 2023.4.0
gcsfs            : None
matplotlib       : None
numba            : 0.56.4
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : 2023.4.0
scipy            : 1.10.1
snappy           : 
sqlalchemy       : 1.4.46
tables           : None
tabulate         : 0.9.0
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by galipremsagar** [comment]
cc: @mroeschke

**Comment by jbrockmendel** [comment]
on main this raises ZeroDivisionError, which is at least slightly better than silently giving incorrect results.  PR to fix this would be welcome.

**Comment by Lokeshrathi** [comment]
If someone is working on this, can we please connect and work on this. As I am a newbie here and would love to learn and explore pandas, since I use it on a day-to-day basis.

I am fine with any hour of the day. :-)
