### ISSUE TITLE
Changed default regex value in pandas.Series.str.replace not fully updated in docs

### ISSUE THREAD

**Issue by juliangilbey** [pandas-dev/pandas#52779]
In the docstring, we have:
https://github.com/pandas-dev/pandas/blob/478d340667831908b5b4bf09a2787a11a14560c9/pandas/core/strings/accessor.py#L1379
the phrase "(the default)" should be removed here as it is no longer the case in 2.0.0.

**Comment by StefanieSenger** [comment]
take

**Comment by MarcoGorelli** [comment]
yup, thanks for the  report
