### ISSUE TITLE
ENH: read_excel is annoying -- prints all the sheet names

### ISSUE THREAD

**Issue by allisonmcampbell** [pandas-dev/pandas#52773]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

In the new implementation of read_excel, I have no control over the print to screen of the sheet names.  It's very visually cluttered, especially for debugging purposes.  PLEASE incorporate an option to allow "print_sheet_names=False").

### Feature Description

PLEASE incorporate an option to allow "print_sheet_names=False").

### Alternative Solutions

I've looked, and can't find it. The only thing I can find is selecting verbose=True, but that only prints "Reading sheet ...". I want *all the other sheets* to be muted.

**Comment by mroeschke** [comment]
This is an issue in openpyxl and will be fixed upstream https://github.com/pandas-dev/pandas/issues/51865. Closing
