### ISSUE TITLE
BUG: join resets index even when doing left join on empty dataframes

### ISSUE THREAD

**Issue by jeckst** [pandas-dev/pandas#52777]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

foo = pd.DataFrame([], index=pd.Index([], dtype="object"))
bar = foo.copy()

foo.join(bar).indexfoo.join(bar).index
```

### Issue Description

On Pandas 1.5.3 above example produces `Index([], dtype='object')` while on 2.0.0 it produces `RangeIndex(start=0, stop=0, step=1)`. I have not found this change in the [release notes](https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html) so I have to assume it is an unintended change and it causes unwanted consequences.

### Expected Behavior

I expect the same behavior as in version 1.5.3

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.10.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.19.0-38-generic
Version          : #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.24.1
pytz             : 2022.6
dateutil         : 2.8.2
setuptools       : 59.6.0
pip              : 23.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.7.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.3
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : 2023.3

</details>

**Comment by asishm-wk** [comment]
empty dataframes/series now default to a RangeIndex - https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html#empty-dataframes-series-will-now-default-to-have-a-rangeindex

**Comment by rhshadrach** [comment]
Thanks @asishm-wk - agreed this is a consequence of the change to the default index. This now seems more consistent, e.g.

```
df1 = pd.DataFrame({'b': [3, 4, 5]})
df2 = pd.DataFrame({'c': [10, 11]})
df1.join(df2).index
# RangeIndex(start=0, stop=3, step=1)
```

cc @topper-123 @jbrockmendel @mroeschke

**Comment by topper-123** [comment]
I would say that if the joined-on indexes are of dtype object, the joined index should also be an object dtype, also if empty. But that seems to be an issue with join, but the issue with the default dtype IMO.

**Comment by rhshadrach** [comment]
Thanks @topper-123 - I missed that the index is being specified as object in the OP. Agreed this should come out as object.

**Comment by jeckst** [comment]
>  I couldn't tell if you are assuming unwanted consequences or if you've experienced it.

@rhshadrach I experienced it, specifically I was doing something along the lines of `df.index.to_series().apply(…).str.get(…)` and ended up getting `AttributeError: Can only use .str accessor with string values!` when `df` was result of an empty join, which didn't use to happen in 1.5.3. It is obviously a pain when the code breaks based on whether the source DataFrames are empty or not (but now I can see that it's my fault).

I have obviously misdiagnosed the real reason for this and haven't noticed the connection to the changed default in release notes. What's worse, if my code relied on the index's `dtype` being something else, it wouldn't have worked even in 1.5.3, since the empty join used to reset the index to empty `Index([], dtype="object")`. So it behaves the same in 2.0.0 as in 1.5.3.

So at best, this is not a bug (apologies!), but an enhancement request — I would still argue that the empty join should probably keep the index type when reasonable.

**Comment by jbrockmendel** [comment]
> I would say that if the joined-on indexes are of dtype object, the joined index should also be an object dtype

this sounds right to me
