### ISSUE TITLE
BUG: dataframe equals method returns False when comparing identical data with numpy and arrow datatypes

### ISSUE THREAD

**Issue by lemurey** [pandas-dev/pandas#52791]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame({1: [10], 2: [20]})
different_column_type = pd.DataFrame({1: [10], 2: [20]}, dtype='int64[pyarrow]')
df.equals(different_column_type)
```

### Issue Description

The dataframe equals method returns False for identical data where one dataframe uses the arrow datatypes. Other similar methods such as `pandas.series.eq`  and `pandas.testing.assert_series_equal` (with `check_dtype=False`) do behave as expected.

### Expected Behavior

Expected behavior returns True for the above example rather than False. 

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : d91b04c30e39ee6cc1c776f60631e1c37be547ef
python           : 3.10.11.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 22.4.0
Version          : Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.1.0.dev0+548.gd91b04c30e
numpy            : 1.25.0.dev0+1126.gd2ae0e759
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.6.1
pip              : 23.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by mroeschke** [comment]
I am not sure that I agree with the conclusion, from the `DataFrame.equals` docstring example at the bottom: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.equals.html

> DataFrames df and different_data_type have different types for the same values for their elements, and will return False even though their column labels are the same values and types.

ArrowDtype is different than np.dtype, so I would expect this to be False

**Comment by lemurey** [comment]
You are absolutely correct, I misread the documentation, I will close.
