### ISSUE TITLE
BUG: numpy.timedelta64[M] not properly raising in pandas.Timedelta in 2.0.0

### ISSUE THREAD

**Issue by ClaudioSalvatoreArcidiacono** [pandas-dev/pandas#52806]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

In [1]: pd.Timedelta(np.timedelta64(1, "M"))
Out[1]: Timedelta('31 days 00:00:00')

In [2]: np.timedelta64(1, "M").astype('timedelta64[D]')
Out[2]: numpy.timedelta64(30,'D')
```

### Issue Description

A numpy `numpy.timedelta64(1,'M')` is converted by `pandas.Timedelta` as an interval of 31 days.

### Expected Behavior

It should be converted to an interval of 30 days.

In pandas 1.5.x it was converted to `Timedelta('30 days 10:29:06')`

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 478d340667831908b5b4bf09a2787a11a14560c9
python           : 3.11.1.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 22.4.0
Version          : Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 2.0.0
numpy            : 1.24.2
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 22.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.12.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None
</details>

**Comment by mroeschke** [comment]
`In [1]:` should probably raise a ValueError. The equivalent `pd.Timedelta(1, unit="M")` now raises a ValueError

 `.astype('timedelta64[D]')` has a default `casting='unsafe'`, the equivalent `np.timedelta64(np.timedelta64(1, "M"), "D")` would raise 

```
In [3]: np.timedelta64(np.timedelta64(1, "M"), "D")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 np.timedelta64(np.timedelta64(1, "M"), "D")

TypeError: Cannot cast NumPy timedelta64 scalar from metadata [M] to [D] according to the rule 'same_kind'
```

**Comment by mcgeestocks** [comment]
Going to jump on this

**Comment by mcgeestocks** [comment]
take
