### ISSUE TITLE
BUG: to_pydatetime() -> 'pyarrow.lib.DataType' object has no attribute 'unit'

### ISSUE THREAD

**Issue by s-banach** [pandas-dev/pandas#52812]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import polars as pl
import datetime

pl.Series([datetime.date(2022,12,31)]).to_pandas(use_pyarrow_extension_array=True).dt.to_pydatetime()

"""AttributeError: 'pyarrow.lib.DataType' object has no attribute 'unit'"""
```

### Issue Description

For context, I was feeding a pandas DataFrame with pyarrow dtypes into the `dash` package, which called `s.dt.to_pydatetime()` on a date series `s`. Maybe the problem is dash's fault, but this seems like a pandas bug.

### Expected Behavior

Return datetime objects as expected.

### Installed Versions

<details>

ModuleNotFoundError: No module named 'PySide6'

</details>

**Comment by mroeschke** [comment]
Can you post the pull traceback?

**Comment by s-banach** [comment]
```python
~/.local/lib/python3.9/site-packages/pandas/core/indexes/accessors.py in to_pydatetime(self)
    211 
    212     def to_pydatetime(self):
--> 213         return cast(ArrowExtensionArray, self._parent.array)._dt_to_pydatetime()
    214 
    215     def isocalendar(self):

~/.local/lib/python3.9/site-packages/pandas/core/arrays/arrow/array.py in _dt_to_pydatetime(self)
   2085     def _dt_to_pydatetime(self):
   2086         data = self._data.to_pylist()
-> 2087         if self._dtype.pyarrow_dtype.unit == "ns":
   2088             data = [None if ts is None else ts.to_pydatetime(warn=False) for ts in data]
   2089         return np.array(data, dtype=object)

AttributeError: 'pyarrow.lib.DataType' object has no attribute 'unit'
```

**Comment by mroeschke** [comment]
Okay here's a pandas reproducer

```
In [1]: import datetime

In [2]: import numpy as np; import pandas as pd; import pyarrow as pa

In [3]: pd.Series(pd.arrays.ArrowExtensionArray(pa.array([datetime.date.today()]))).dt.to_pydatetime()
AttributeError: 'pyarrow.lib.DataType' object has no attribute 'unit'
```

Not 100% that this should work, `datetime.date` and `datetime.datetime` are different objects. Probably should raise a better error message here that the pyarrow type should be `pa.timestamp` type specifically

**Comment by s-banach** [comment]
For more context, `dash` tries to convert to datetime after seeing that `dtype.kind == "M"`.
(I guess there aren't separate "kinds" for `date` and `datetime`.)
I have no idea why they're not just using `Series.to_numpy()`...

**Comment by jbrockmendel** [comment]
isnt this why we have `get_unit_from_pa_dtype`?

**Comment by mroeschke** [comment]
> get_unit_from_pa_dtype

Looks specifically used for `pa.time` types, but for a totally different application.

The issue here is `date[unit][pyarrow]` type working with a `to_pydatetime()` method

**Comment by phofl** [comment]
Labelling 2.0.1 for now, think it might make sense back porting a better error message
