### ISSUE TITLE
Binary operators between DataFrame and Series object doesn't seem to work

### ISSUE THREAD

**Issue by liori** [pandas-dev/pandas#5284]
related similar operation

http://stackoverflow.com/questions/19484344/how-do-i-use-a-specific-columns-value-in-a-pandas-dataframe-where-clause/19494873#19494873

http://stackoverflow.com/questions/19507088/filtering-a-pandas-dataframe-without-removing-rows/19516869#19516869

http://stackoverflow.com/q/21627926/190597

This should be a bit more intuitive

```
In [59]: data = """      A    B    C    D
1/1   0    1    0    1
1/2   2    1    1    1
1/3   3    0    1    0 
1/4   1    0    1    2
1/5   1    0    1    1
1/6   2    0    2    1
1/7   3    5    2    3"""

In [60]: df = read_csv(StringIO(data),sep='\s+')

In [61]: df
Out[61]: 
     A  B  C  D
1/1  0  1  0  1
1/2  2  1  1  1
1/3  3  0  1  0
1/4  1  0  1  2
1/5  1  0  1  1
1/6  2  0  2  1
1/7  3  5  2  3

In [62]: df.where((df>df.shift(1)).values & DataFrame(df.D==1).values)
Out[62]: 
      A   B   C   D
1/1 NaN NaN NaN NaN
1/2   2 NaN   1 NaN
1/3 NaN NaN NaN NaN
1/4 NaN NaN NaN NaN
1/5 NaN NaN NaN NaN
1/6   2 NaN   2 NaN
1/7 NaN NaN NaN NaN
```

Given that normal binary operators like addition or logical `and` work well between a pair of Series objects, or between a pair of DataFrame objects (returning a element-wise addition/conjuction), I found it surprising that I cannot do the same between a Series object and a DataFrame object.

Here's a demonstration of what doesn't work now and what would be the expected result: http://nbviewer.ipython.org/urls/dl.dropboxusercontent.com/u/52886258/000-qdoqud/Untitled0.ipynb

**Comment by jreback** [comment]
So this is causing a warning here: https://github.com/pydata/pandas/blob/master/pandas/tests/series/test_operators.py#L1200

because ``df & s`` raises a ``ValueError``, which is really doing: ``df.__and__(s, axis='columns')``

and the alignment should be ``df.__and__(s, axis='index')`` but of course ``&`` is going to default align this way.
