### ISSUE TITLE
BUG: DataFrameGroupBy.nunique fails with categorical, multiple groupings, and as_index=False

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#52848]
```
df = DataFrame({"a1": [0, 0, 1], "a2": [2, 3, 3], "b": [4, 5, 6]})
df = df.astype({"a1": "category", "a2": "category"})
gb = df.groupby(by=["a1", "a2"], as_index=False, observed=False)
gb.nunique()
```

raises `ValueError: Length of values (3) does not match length of index (4)`

**Comment by szczekulskij** [comment]
take

**Comment by szczekulskij** [comment]
This looks a bit hard, but I'll give it a try. If I won't be able to solve this within a week, I'll re-assign

**Comment by szczekulskij** [comment]
take

**Comment by szczekulskij** [comment]
Weirdly, It's the same "wrong" function that gets triggered as in this issue: https://github.com/pandas-dev/pandas/issues/52397 

The name of function: `self._insert_inaxis_grouper ` - in both issues we need to skip it so that as_index doesn't influence behaviour

**Comment by szczekulskij** [comment]
Is it okay if I force as_index = True using  `with com.temp_setattr(self, "as_index", True):` ?

With as_index=True forced, the output would always look like this:
```
#        b
# a1 a2   
# 0  2   1
#    3   1
# 1  2   0
#    3   1
```

I assume we want the behaviour to differ depending on as_index, but wanted to double check

@rhshadrach

**Comment by rhshadrach** [comment]
> I assume we want the behaviour to differ depending on as_index, but wanted to double check

Correct. Running the OP example without categorical data produces:

```
   a1  a2  b
0   0   2  1
1   0   3  1
2   1   3  1
```

**Comment by szczekulskij** [comment]
Hey, I'm sorry but I'll need to drop this issue. Pandas is a bit too much for me right now, I'll come back to this in the future
