### ISSUE TITLE
BUG: interchange protocol doesn't work with offsets

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#52845]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
In [7]: import pyarrow as pa

In [8]: table = pa.table({"a": pa.array([1,2,3])})

In [9]: from pandas.core.interchange.from_dataframe import from_dataframe

In [10]: from_dataframe(table.slice(1))
Out[10]:
   a
0  2
1  3
2  0
```

### Issue Description

The offset doesn't take effect, `from_dataframe` just returns something of the same length as the original

### Expected Behavior

```python
In [10]: from_dataframe(table.slice(1))
Out[10]:
   a
0  2
1  3
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 478d340667831908b5b4bf09a2787a11a14560c9
python           : 3.8.16.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 2.0.0
numpy            : 1.24.2
pytz             : 2022.6
dateutil         : 2.8.2
setuptools       : 65.5.1
pip              : 22.3.1
Cython           : 0.29.33
pytest           : 7.2.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.6.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : 0.9.0
xarray           : 2023.1.0
xlrd             : None
zstandard        : None
tzdata           : 2022.7
qtpy             : None
pyqt5            : None

</details>

**Comment by SecretLake** [comment]
take
