### ISSUE TITLE
BUG: Dataframe.groupby does not fail on a column name that doesn't exist

### ISSUE THREAD

**Issue by guitar-etc** [pandas-dev/pandas#52852]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({"age": [30]})
# should've raised KeyError since "abc" doesn't exist in df
dfgb = df.groupby(["abc"])
result = dfgb.count()
print(result)
#       age
# abc    1
```

### Issue Description

column "abc" obviously doesn't exist in `df`, but `groupby` succeeds.

This is because of the logic that sets `match_axis_length` in `pandas/core/groupby/grouper.py::get_grouper`
In the function `match_axis_length` evaluates to True because of the following reasons.
1. `key` (`["abc"]`) is a list of length 1,
2. `len(group_axis)` is 1 because `df` only has 1 row.

That causes the following `if` condition to evaluate to True.
```
if (
        not any_callable
        and not any_arraylike
        and not any_groupers
        and match_axis_length
        and level is None
    )
```
which then causes the following code to be executed, transforming `["abc"]` into a list of numpy array, effectively turning an `Iterable[str]` into `Iterable[Iterable[str]]`
```
        if not all_in_columns_index:
            keys = [com.asarray_tuplesafe(keys)]
```
Finally, that causes `is_in_axis` to receive a `key` which is actually a length-1 numpy array of "abc" so `_is_label_like` returns `False` and `is_in_axis` ends up returning `False` and pandas fail to raise the KeyError as expected. 

The scenario to trigger this bug is quite unique, but I think it's still a viable scenario.
I'm not so sure what `match_axis_length` is for nor why a grouper tries to replace the index.

```
    # is this an index replacement?
    if (
        not any_callable
        and not any_arraylike
        and not any_groupers
        and match_axis_length
        and level is None
    ):
```

Perhaps, this is an expected behavior, but I can't seem to find a documentation for it.

### Expected Behavior

I would expect a KeyError. The following is a pytest code that describes my expectations. The test passes
```
import pandas as pd
import pytest


def test_dataframe_groupby():
    df = pd.DataFrame({"age": [30]})
    with pytest.raises(KeyError):
        df.groupby("abc")
    with pytest.raises(KeyError):
        df.groupby(["abc", "def"])

    # should've raised KeyError since "abc" doesn't exist in df
    df.groupby(["abc"])

    df = pd.DataFrame({"age": [30, 31]})
    with pytest.raises(KeyError):
        df.groupby(["abc"])
    with pytest.raises(KeyError):
        df.groupby("abc")

    # should've raised KeyError since "abc" doesn't exist in df
    df.groupby(["abc", "def"])
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 478d340667831908b5b4bf09a2787a11a14560c9
python           : 3.11.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.16.3-microsoft-standard-WSL2
Version          : #1 SMP Fri Apr 2 22:23:49 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.0
numpy            : 1.24.2
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.1.0
pip              : 23.0
Cython           : None
pytest           : 7.2.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by phofl** [comment]
Hi, thanks for your report. this behaves as expected. Same as when you would pass a Series that has the same length as the df.

**Comment by guitar-etc** [comment]
@phofl Hi, thanks for the quick reply. I checked the documentation again and it does talk about `by` of same length as the selected axis.

Could you help me figure out how I can force `df[*column_names]` to raise a `KeyError` when I'm given `column_names` and `df` of random length and `column_names`, unexpectedly, has a name that does not exist in `df`?

I just randomly encountered a situation where the length of `df` and `column_names` were equal and had a typo in one of the `column_names`. So I added something like `label_name in df.columns` check for now, but I'm curious if there's some better way.

**Comment by jakobludewig** [comment]
@guitar-etc Encountered the same issue. The workaround I came up with is to use `groupby([pd.Grouper(key="column_1"), pd.Grouper(key="column_2")])`.
