### ISSUE TITLE
DOC: pandas.to_datetime dayfirst doc contains error

### ISSUE THREAD

**Issue by lordmuck2020** [pandas-dev/pandas#52871]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.to_datetime.html

### Documentation problem

The docs read:
`dayfirstbool, default False`
Specify a date parse order if arg is str or is list-like. If True, parses dates with the day first, e.g. `10/11/12` is parsed as `2012-11-10`.

However, this is parsing as year first. 

### Suggested fix for documentation

e.g. `04/31/23` is parsed as `31-04-2023`

**Comment by phofl** [comment]
This isn't parsing as ear first, otherwise it would be 2010 and not 2012

**Comment by lordmuck2020** [comment]
OK, misunderstood. Maybe worth clarifying that the incoming string has the day first?

**Comment by lordmuck2020** [comment]
Yep, I misunderstood. Thank you.
