### ISSUE TITLE
ENH: JAX backend in place of NumPy

### ISSUE THREAD

**Issue by rnarkk** [pandas-dev/pandas#52876]
### Feature Type

- [ ] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish I could use pandas on top of JAX instead of NumPy.

### Feature Description

Enable selectively to use JAX as the dependency for pandas.

```sh
pip3 install pandas[jax]
```

### Alternative Solutions

Use JAX by default.

**Comment by phofl** [comment]
This needs more context and explanations (advantages, disadvantages, ...). This would require major changes in pandas internals.

**Comment by rnarkk** [comment]
I’m super surprised and pleased to have found that there already exists what I had envisioned in the first place — Rust & Apache Arrow based dataframe having NumPy as only an option —: [polars](https://github.com/pola-rs/polars). The performance gain and dependency reduction is as I expected. So I’m closing this. Thanks.

**Comment by jbrockmendel** [comment]
We suggest implementing a Jax-backed ExtesnionArray

**Comment by rnarkk** [comment]
@pandas-dev Why you deleted my comment?

**Comment by MarcoGorelli** [comment]
@rnarkk 

1. this isn't an advertisment booth
2. please don't tag all of pandas-dev
