### ISSUE TITLE
BUG: Module `pandas._libs.json` has incorrect `__name__` attribute

### ISSUE THREAD

**Issue by shwina** [pandas-dev/pandas#52898]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> import pandas as pd
pd>>> pd.__version__
'2.0.0'
>>> pd._libs.json.__name__
'_libjson'
>>> pd._libs.missing.__name__
'pandas._libs.missing'
```

### Issue Description

The `__name__` attribute for the `pandas._libs.json` is set to `_libjson` [here](https://github.com/pandas-dev/pandas/blob/main/pandas/_libs/src/ujson/python/ujson.c#L86).

The [Python docs](https://docs.python.org/3/reference/import.html#name__) say that `__name__` should be set to the fully qualified name of the module, which I would expect to be `'pandas._libs.json'`.

In the code example above, you can see that other Pandas C-extensions like `pd._libs.missing` have the correct `__name__` attribute set.

### Expected Behavior

`__name__` should be set to the fully qualified name of the module, which I would expect to be `'pandas._libs.json'`.

### Installed Versions

2

**Comment by MarcoGorelli** [comment]
thanks for the report - +1 for changing, but just out of interest, how did you come across this, why do you need it?
