### ISSUE TITLE
Segmentation fault or UnicodeDecodeError when reading csv-file depending on chunksize.

### ISSUE THREAD

**Issue by Hedendahl** [pandas-dev/pandas#5291]
I have encountered an issue with the csv parser, pandas.io.parser.read_csv. I get segmentation fault or UnicodeDecodeError when reading a csv-file in chunks and it seems like that the problem depends on the size of the chunks.
Consider the following code:

``` python
import codecs
import csv
import pandas as pd


def create_csv_file(columns, rows):
    csv_file_name = 'csv_test_file.csv'
    with codecs.open(csv_file_name, mode='w', encoding='utf_8') as csv_file:
        csv_writer = csv.writer(csv_file, delimiter=',')

        for row in xrange(rows):
            csv_writer.writerow(
                [float(row)] * columns)

    return csv_file_name


def main():
    """
    """
    columns = 20
    rows = 10000
    chunksize = 999
    csv_file_name = create_csv_file(columns, rows)
    reader = pd.io.parsers.read_csv(csv_file_name,
                                    header=None,
                                    chunksize=chunksize,
                                    encoding='utf_8')

    for x, dataframe in enumerate(reader, 1):
        print x * chunksize


if __name__ == "__main__":
    main()
```

I get segmentation fault from the attached code, when the chunksize is 999 rows. If the chunksize is decreased to 998 rows, I instead get an UnicodeDecodeError. If the chunksize is increased to 1000 rows there are no problems of reading the csv-file. My first guess was that the problem appears when the last chunk include too few rows, but I was surprised when reading of the csv-file with the following setting,

``` python
    columns = 20
    rows = 1000
    chunksize = 99
```

worked properly.

**Comment by ivannz** [comment]
I believe PR #13788 could have solved this issue.

**Comment by jreback** [comment]
can you PR with some test based on this issue

**Comment by ivannz** [comment]
Yes, but is it necessary? This fault occurs on 0.18.1 only for **engine="c"** and even without **encoding='utf-8'** parameter (because the data is ASCII anyway). This code reproduces the issue:
```python
import pandas as pd
from cStringIO import StringIO
import pandas.util.testing as tm

def test_issue5291(self):
    # This test recreates the segfault in issue #5291
    n_rows, n_columns, chunksize = 10000, 20, 999
    expected = pd.DataFrame([[float(row)] * n_columns
                             for row in range(n_rows)],
                            dtype=float, columns=None, index=None)
    # Now read the same dataframe in chunks from a CSV
    data = "\r\n".join(",".join(["%.1f"%(r,)] * n_columns)
                       for r in range(n_rows)) + "\r\n"
    chunks_ = self.read_csv(StringIO(data), header=None,
                            chunksize=chunksize)
    result = pd.concat(chunks_, axis=0, ignore_index=True)
    # Check for data corruption if there was no segfault
    tm.assert_frame_equal(result, expected)

test_issue5291(pd)
```
It is identical to `test_parse_trim_buffers()` in [c_parser_only.py](https://github.com/pydata/pandas/blob/master/pandas/io/tests/parser/c_parser_only.py#L385), though I admit that it takes a slightly different path inside [_read_rows](https://github.com/pydata/pandas/blob/master/pandas/parser.pyx#L902)

**Comment by jreback** [comment]
why not add a test
just include it in the same whatsnew and put test right below other one

**Comment by jreback** [comment]
actually instead just take original test and use with and w/o encoding

**Comment by ivannz** [comment]
@jreback, should I include the extended test in the currently pending PR (#13819) or in the next one?

**Comment by jreback** [comment]
no separate things go in separate PR's
