### ISSUE TITLE
WEB: add links to the official mastodon account

### ISSUE THREAD

**Issue by mikix** [pandas-dev/pandas#52914]
It's been a [few months since](https://twitter.com/pandas_dev/status/1592479891496534016) you folks started your [mastodon account](https://fosstodon.org/@pandas_dev). How's that been going? If it's going well, I suggest that it should be bumped up in visibility.

It would be nice to add links to the account on the various pandas web sites. Here are spots I know about:
- Upper right of https://pandas.pydata.org/pandas-docs/stable/
- Bottom right of all pages at https://pandas.pydata.org/
- "Follow us" section on right of the home page at https://pandas.pydata.org/

Additionally, it would be nice to verify that your mastodon account is the official one, by proving that it is blessed by the pandas website (this is the [verification](https://joinmastodon.org/verification) that mastodon offers):
- Add the following to the `<head>` portion of the [home page](https://pandas.pydata.org/): `<link rel="me" href="https://fosstodon.org/@pandas_dev"/>` (and/or add `rel="me"` to the links you add above)
- On your mastodon account, add a profile metadata link back to the home page.

**Comment by MarcoGorelli** [comment]
thanks for the suggestion - interested in opening a PR to address the above?

**Comment by mikix** [comment]
Sure, I can look into it

**Comment by MarcoGorelli** [comment]
thanks @mikix 

> On your mastodon account, add a profile metadata link back to the home page.

sorry, do you have an example of this? what should I put where?

**Comment by mikix** [comment]
@MarcoGorelli in your client go to edit your profile. There should be an option for up to four “Profile metadata” fields. Fill out on of them as like, “Homepage” or something and add the URL as the value. That page will be checked for the links I added and mark your link as verified.

**Comment by MarcoGorelli** [comment]
thanks @mikix ! hopefully this is correct now 🤞

**Comment by mikix** [comment]
Beautiful!
<img width="364" alt="image" src="https://user-images.githubusercontent.com/1196901/235236141-936d8ef3-0ba7-4cb2-b7c2-446c166ae402.png">
