### ISSUE TITLE
DOC:  Series.dt currently not included in docs on main

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#52937]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.Series.dt.html

This site is currently not included in out toctree when building the docs with Python 3.10, which is the new default after removing 3.8 support

### Documentation problem

Should fix

Some discussion is here: https://github.com/pandas-dev/pandas/pull/51133

### Suggested fix for documentation

Figure out what's going wrong

cc @mroeschke

**Comment by Dr-Irv** [comment]
I think this is a bit worse than described, even with older versions of the docs.  What is missing is the list of `Series.dt` attributes, listed on the page.  For example, `dt.hour`, `dt.seconds`, `dt.as_unit()` etc.

**Comment by Dr-Irv** [comment]
> ? I can find them on this page: https://pandas.pydata.org/docs/dev/reference/series.html

OK, but I think the list should also be at https://pandas.pydata.org/docs/reference/api/pandas.Series.dt.html as well

**Comment by mroeschke** [comment]
Closed by https://github.com/pandas-dev/pandas/pull/54457
