### ISSUE TITLE
BUG: .to_csv treats empty strings and None the same way

### ISSUE THREAD

**Issue by alecstein** [pandas-dev/pandas#52948]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
With the latest version of pandas, fire up a terminal and do the following:

Python 3.11.3 (main, Apr  5 2023, 14:14:40) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.__version__
'2.0.1'
>>> pd.DataFrame([{'a':None, 'b': None}]).to_csv('test-none.csv')
>>> pd.DataFrame([{'a':'', 'b': ''}]).to_csv('test-empty.csv')
```

Then exit and check the files created:

```
~ ❯ less test-empty.csv                                                                                                                                          
,a,b
0,,
~ ❯ less test-none.csv                                                                                                                                                    
,a,b
0,,
```

They are the same, when they should not be.

### Issue Description

`to_csv()` treats None and empty string as the same when they are different.

`na_rep` does not solve the issue because it fills *all* `None`s with an empty string. I just want some columns filled with the empty string, and others to be None.

### Expected Behavior

The output for test-empty.csv should be:
```
~ ❯ less test-empty.csv                                                                                                                                          
,a,b
0,"",""
```
respecting the difference between None and the empty string.

### Installed Versions

pandas version '2.0.1'

**Comment by phofl** [comment]
You can configure the na representation through the keyword ``na_rep``
