### ISSUE TITLE
`read_sql_*()` methods have incorrect typing for `dtype` argument.

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#53046]
The `read_sql()` docs say for the new `dtype` argument:

dtype     Type name or dict of columns
Data type for data or columns. E.g. np.float64 or {‘a’: np.float64, ‘b’: np.int32, ‘c’: ‘Int64’}. The argument is ignored if a table is passed instead of a query.

But in the typing in the source code, the argument is `DtypeArg | None` which doesn't allow something like `{"c": "str"}` .  The implementation just passes `dtype` to `DataFrame.astype()`.

See https://github.com/pandas-dev/pandas-stubs/issues/676

NOTE:  In `pandas-stubs` we did work to create all the possible strings and dtypes for `astype()`, so maybe that should be copied over to the pandas source??

**Comment by Dr-Irv** [comment]
For pandas, I think the solution is to redefine https://github.com/pandas-dev/pandas/blob/042ebab0248193b343ede6d87397871bf8931fca/pandas/_typing.py#L169 to use `Mapping` instead of `Dict`

**Comment by teacherc** [comment]
take

**Comment by twoertwein** [comment]
> For pandas, I think the solution is to redefine
> 
> https://github.com/pandas-dev/pandas/blob/042ebab0248193b343ede6d87397871bf8931fca/pandas/_typing.py#L169
> to use `Mapping` instead of `Dict`

Closing this issue as the suggested change has been made:
https://github.com/pandas-dev/pandas/blob/de1131f84df511665640db1c2d11f76fdf66f82c/pandas/_typing.py#L221
