### ISSUE TITLE
BUG: Pandas 2.0 vs. 1.5.3 behavior change when inserting row of MultiIndex data

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [pandas-dev/pandas#53053]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

mi = pd.MultiIndex.from_tuples([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
mi.names=['i1', 'i2', 'i3']
xx = pd.DataFrame(data=[[10, 20, 30], [40, 50, 60], [70, 80, 90]], index=mi, columns =['A', 'B', 'C'])
print(xx.index.names)
xx.loc[(0, 0, 0)] = xx.loc[(1, 2, 3)] + xx.loc[(4, 5, 6)]
print(xx.index.names)
```

### Issue Description

The sample code above creates a multi-index dataframe with named columns `i1`, `i2`, `i3`.  When inserting a row in Pandas 1.5.3, the names of the MultiIndex remain intact.  When inserting a row in 2.0.1, the MultiIndex names are replaced with `None`, `None`, `None` (presumably because the unnamed tuple single-handedly overwrites the index names of the MultiIndex).

### Expected Behavior

I expect the names of the MultiIndex to be preserved across the insertion.

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 37ea63d540fd27274cad6585082c91b1283f963d
python           : 3.9.16.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 22.4.0
Version          : Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.1
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.7.2
pip              : 23.1.2
Cython           : 0.29.34
pytest           : 7.3.1
hypothesis       : 6.75.1
sphinx           : 6.2.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.13.1
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : 
fastparquet      : 2023.2.0
fsspec           : 2023.4.0
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : 1.4.46
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
zstandard        : 0.19.0
tzdata           : 2023.3
qtpy             : 2.3.1
pyqt5            : None
</details>

**Comment by MarcoGorelli** [comment]
thanks @MichaelTiemannOSC for the reporting, am running a bisect to see when this changed https://www.kaggle.com/code/marcogorelli/pandas-regression-example-5d1e8c?scriptVersionId=128179011
