### ISSUE TITLE
API: pd.array convert unsupported dt64/td64 to supported?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#53058]
```python
dtype = np.dtype("M8[h]")
arr = pd.array([], dtype=dtype)

>>> arr
<PandasArray>
[]
Length: 0, dtype: datetime64[h]
```

In most cases we'd like to align behavior across different constructors (pd.Series, pd.Index, pd.array).  One case where we currently don't do that is with an un-supported numpy dt64/td64 dtype.   pd.Series/pd.Index will raise on this, while pd.array will wrap it in a PandasArray.

I propose we deprecate that behavior and raise in pd.array like we would in Series/Index.

xref #27460

**Comment by rmhowe425** [comment]
@jbrockmendel @lithomas1 I can work this one.

Do we want to raise a warning to deprecate the current behavior before we raise an error?

**Comment by rmhowe425** [comment]
take

**Comment by jbrockmendel** [comment]
Will need to be a deprecation
