### ISSUE TITLE
How to display dataframe from csv file with OOP method

### ISSUE THREAD

**Issue by mhd-fauzan** [pandas-dev/pandas#53065]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

I can’t post new questions right now

### Question about pandas

Hi, I'm a novice programmer. I want to display a dataframe coming from a csv file using an object oriented programming method. Here I show the code.
```
import pandas as pd
import matplotlib.pyplot as plt

class csv2df():
    
    def __init__(self):
        df = pd.read_csv("RMS level.csv")
```
Explanation please. Thank You

**Comment by topper-123** [comment]
Hi @mhd-fauzan. It's great that you starting programming (we were all novice programmers once).

These github issue are however not for general usage questions, but are meant for bug reports and changes to the pandas source code, so I will need to close this issue, so the issue tracker can keep its focus. I wish you good luck in programming 👍 .
