### ISSUE TITLE
BUG: the library stores its state in an irreversible way

### ISSUE THREAD

**Issue by pomponchik** [pandas-dev/pandas#53068]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import installed

with installed('pandas==2.0.1') as pack_1:
    with installed('pandas==2.0.0') as pack_2:
        pd_1 = pack_1.import_here('pandas')
        pd_2 = pack_2.import_here('pandas')
        print(pd_1.__version__)
        print(pd_2.__version__)
```

### Issue Description

I am an author of [Instld](https://github.com/pomponchik/instld) - a library for runtime dependency management.

In the process of testing my library, I found that most libraries can be easily reinstalled in runtime. However, this does not apply to `pandas`. `Pandas` somehow caches its state, which cannot be bypassed either by deleting from `sys.modules` or by resetting the cache.

To run the code I have given, you need to install `instld`.

### Expected Behavior

The library should not store its state in an irreversible way. Ultimately, this complicates many aspects of its application, not only the ability to install it twice in runtime.

### Installed Versions

I tested it with 2.0.0 and 2.0.1 pandas.

**Comment by pomponchik** [comment]
I am not well versed in the internal structure of Pandas. However, I know that if you import this module once, and then remove it from sys.modules and install it again, the first module will still be available. I have presented the code that you can run and test it. Unfortunately, I can't say exactly how this happened in the case of Pandas, I'm interested to find out myself.

In the code I have given, at least the version tag is saved, as you can see.

**Comment by MarcoGorelli** [comment]
thanks for the report - could you make a self-contained reproducible example please? ideally we shouldn't need to install `instld` to reproduce and address this

**Comment by mroeschke** [comment]
Closing, but can reopen when we have a self-contained example
