### ISSUE TITLE
ENH: Add ``numeric_only`` to ``DataFrame.cum*`` methods

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#53072]
### Feature Type

- [x] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

The groupby methods all support numeric_only while regular transformations don't. Not sure if there is a reason for this.

cc @rhshadrach thoughts here?

More context: If you do an axis=1 transformation on groupby it dispatches to ``DataFrame.cum*`` and hence raises if ``numeric_only`` is given.

### Feature Description

Add the keyword.

### Alternative Solutions

Filter the DataFrame on your own, but this is mostly compatibility to groupby methods.

**Comment by rhshadrach** [comment]
+1 on adding.

**Comment by alexprincel** [comment]
Unless I misunderstood you, doing an axis=1 transformation on groupby returns a deprecation warning:

```
>>> df = pandas.DataFrame({'a': [1,2,3], 'b': [4,5,6], 'c': [7,8,9]})
>>> df.groupby('a', axis=1)
<stdin>:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7f13b7dafdc0>
```

Is there a use for this change given this is already deprecated ?

**Comment by rhshadrach** [comment]
@alexprincel - yes, it is generally useful to subset to numeric data, and exists in many other operations on groupby. Even with axis=1 deprecated it seems desirable to me to add from a consistency standpoint.

**Comment by rhshadrach** [comment]
For anyone looking into this as a good first issue, you can search the code for other uses of `numeric_only` in `pandas.core.groupby` and utilize the code the for these methods.

**Comment by matty5567** [comment]
Hi @rhshadrach I'm really keen to start contributing and would like to get involved with this issue please

**Comment by matty5567** [comment]
take

**Comment by matty5567** [comment]
@rhshadrach how about something like this?

```python
    @doc(make_doc("cummin", ndim=2))
    def cummin(self, axis: Axis | None = None, skipna: bool = True, numeric_only: bool = False, *args, **kwargs):
        data = self._get_numeric_data() if numeric_only else self
        return NDFrame.cummin(data, axis, skipna, *args, **kwargs)

    @doc(make_doc("cummax", ndim=2))
    def cummax(self, axis: Axis | None = None, skipna: bool = True, numeric_only: bool = False, *args, **kwargs):
        data = self._get_numeric_data() if numeric_only else self
        return NDFrame.cummax(data, axis, skipna, *args, **kwargs)

    @doc(make_doc("cumsum", ndim=2))
    def cumsum(self, axis: Axis | None = None, skipna: bool = True, numeric_only: bool = False, *args, **kwargs):
        data = self._get_numeric_data() if numeric_only else self
        return NDFrame.cumsum(data, axis, skipna, *args, **kwargs)

    @doc(make_doc("cumprod", 2))
    def cumprod(self, axis: Axis | None = None, skipna: bool = True, numeric_only: bool = False, *args, **kwargs):
        data = self._get_numeric_data() if numeric_only else self
        return NDFrame.cumprod(data, axis, skipna, *args, **kwargs)
```

**Comment by rhshadrach** [comment]
That looks correct to me.

**Comment by NikhilKumarM** [comment]
take
