### ISSUE TITLE
BUG: DataFrame.describe raises error for overlapping include/exclude even if there's no overlap

### ISSUE THREAD

**Issue by wirable23** [pandas-dev/pandas#53083]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
pd_df = pd.DataFrame({"A": [1,2,3]})
pd_df.describe(
        include=["float[pyarrow]"],
        exclude=["double[pyarrow]"],
    )

ValueError: include and exclude overlap on frozenset({<class 'float'>})
```

### Issue Description

The error raised pertains to an overlapping type between include/exclude. While they are both floating types, it seems they are different types and this should be allowed.

### Expected Behavior

```
>>> a = pd.DataFrame({"A": pd.Series([1,2,3], dtype="float32"), "B": pd.Series([1,2,3], dtype="float64")})
>>> a.describe(include="float32", exclude="float64")
         A
count  3.0
mean   2.0
std    1.0
min    1.0
25%    1.5
50%    2.0
75%    2.5
max    3.0
>>>
```

Expect numpy behavior, which allows this

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 37ea63d540fd27274cad6585082c91b1283f963d
python           : 3.8.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 2.0.1
numpy            : 1.23.4
pytz             : 2023.2
dateutil         : 2.8.2
setuptools       : 60.8.2
pip              : 23.1.1
Cython           : None
pytest           : 7.0.1
hypothesis       : None
sphinx           : 4.2.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.1.1
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
brotli           : None
fastparquet      : 2023.2.0
fsspec           : 2023.3.0
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 12.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None
>>>
</details>

**Comment by mroeschke** [comment]
Thanks for the report. To address this correctly something like https://github.com/pandas-dev/pandas/issues/52576#issuecomment-1536760318 will need to be addressed
