### ISSUE TITLE
DOC: pd.DataFrame.align() join parameter values are insufficiently explained

### ISSUE THREAD

**Issue by FlorinAndrei** [pandas-dev/pandas#53092]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.align.html

### Documentation problem

For the `join` parameter, only its values are mentioned. But what do the different values do? The current documentation provides no clue.

### Suggested fix for documentation

Please explain what the different values of the `join` parameter do.

**Comment by Antony-evm** [comment]
take
