### ISSUE TITLE
BUG: Equal input DataFrames but different results

### ISSUE THREAD

**Issue by seanslma** [pandas-dev/pandas#53093]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

d1 = pd.DataFrame({  
    'ref': ['ref', 'ref'],
    'date': pd.to_datetime(['2019-01-31', '2019-02-01']),         
    'value': [100.0, 100.0],
}).set_index(['ref', 'date'])
d2 = pd.DataFrame({
    'ref': ['ref', 'ref'],    
    'date': pd.to_datetime(['2019-02-01', '2019-02-01']),   
    'code': ['A', 'B'],
    'value': [0.75, 0.25],
}).set_index(['ref', 'date', 'code'])
d12 = d1 * d2
d21 = d2 * d1
print(d12)
print(d21)
print(d12.equals(d21))

code = ['A']
r12 = d12.query('code in @code').reset_index('ref', drop=True).get('value').loc[:'2019-01-31']
r21 = d21.query('code in @code').reset_index('ref', drop=True).get('value').loc[:'2019-01-31']
print(r12)
print(r21) #wrong result
```

### Issue Description

As d12 and d21 are equal to each other so the outputs from r12 and r21 should be the same. 

The result for r12 is correct
```
Series([], Name: value, dtype: float64)
```

But the result for r21 is wrong
```
date        code
2019-02-01  A       75.0
Name: value, dtype: float64
```

### Expected Behavior

r21 should also be an empty Series same as r12.

In pandas 1.5.3 both r12 and r21 are an empty Series.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 37ea63d540fd27274cad6585082c91b1283f963d
python           : 3.9.15.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 58 Stepping 0, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_Australia.1252

pandas           : 2.0.1
numpy            : 1.23.3
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 22.3.1
Cython           : 0.29.30
pytest           : 7.1.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.0
html5lib         : None
pymysql          : None
psycopg2         : 2.9.3
jinja2           : 3.0.3
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.5
brotli           : 
fastparquet      : None
fsspec           : 2022.5.0
gcsfs            : None
matplotlib       : 3.5.2
numba            : 0.53.0
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.1
snappy           : None
sqlalchemy       : 1.4.46
tables           : None
tabulate         : None
xarray           : 2022.3.0
xlrd             : None
zstandard        : None
tzdata           : 2022.1
qtpy             : None
pyqt5            : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report @seanslma. Can you narrow down the operation the first produces what you see as a wrong result? Currently you are chaining together many operations. You should be able to narrow this down to a single input and a single operation that you believe produces an incorrect result.

**Comment by seanslma** [comment]
Thanks @rhshadrach. 

I tried to simplify the example but not able to - good news is that I got some extra info that might be helpful for the investigation.

Input DataFrame 1 & 2
```
d1 = pd.DataFrame(
    [100.0, 100.0],
    columns=['value'],
    index=pd.MultiIndex.from_arrays([pd.to_datetime(['2019-01-31', '2019-02-01']),['ref', 'ref']], names=[ 'date', 'ref']),
)
d2 = pd.DataFrame(
    [0.75, 0.25],
    columns=['value'],
    index=pd.MultiIndex.from_arrays([pd.to_datetime(['2019-02-01', '2019-02-01']), ['ref', 'ref'], ['A', 'B']], names=['date', 'ref', 'code']),
)
```

Results DataFrame. Note that `d1 * d2` will produce correct results
```
d21 = d2 * d1
r21 = d21.query('code == "A"').loc[:'2019-01-31']
```

Also you can try slicing without chaining
```
idx = pd.IndexSlice
d21.loc[idx[:'2019-01-31',:,:],:]
```
UnsortedIndexError: 'MultiIndex slicing requires the index to be lexsorted: slicing on levels [0], lexsort depth 0'

**Comment by attack68** [comment]
The assertion here is that d1 * d2 and d2 * d1 should produce the same result.
But d1 and d2 have different indexes and are different objects. 
Is the operation of DataFrame multiplication defined to be communtative?
If not (and perhaps there is a reason that it is not), then your argument is invalid, otherwise this should be inspected further.

**Comment by phofl** [comment]
No it's not commutative. We do reindexing ops under the hood which probably cause the differences

**Comment by phofl** [comment]
The index is constructed incorrectly during alignment, everything else works as expected
