### ISSUE TITLE
DOC: Incorrect deprecation in Styler.applymap

### ISSUE THREAD

**Issue by bashtage** [pandas-dev/pandas#53097]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.io.formats.style.Styler.applymap.html

### Documentation problem

Should be specific to applymap. Instead is about applymap_index.

### Suggested fix for documentation

Remove the `_index` bits.

**Comment by Rajasvi** [comment]
take

**Comment by Kapil-chn7** [comment]
Hello there, I'm beginner in Opensource, can I work on this issue?
