### ISSUE TITLE
BUG: to_datetime ignores "AM" and "PM" unless format is explicitly set

### ISSUE THREAD

**Issue by juli4nb4dillo** [pandas-dev/pandas#53147]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
>>> df = pd.DataFrame(['4/21/2023 11:06:35 AM','4/21/2023 12:06:35 PM', '4/21/2023 1:00:48 PM', '4/21/2023 2:35:37 PM'])
>>> df
                       0
0  4/21/2023 11:06:35 AM
1  4/21/2023 12:06:35 PM
2   4/21/2023 1:00:48 PM
3   4/21/2023 2:35:37 PM
>>> pd.to_datetime(df[0])
0   2023-04-21 11:06:35
1   2023-04-21 12:06:35
2   2023-04-21 01:00:48  # PM is ignored, parsing as 01:00 instead of 13:00
3   2023-04-21 02:35:37
```

### Issue Description

`to_datetime` ignores the `AM` and `PM` particles, hence parsing both as 24H format.

### Expected Behavior

```python
>>> df = pd.DataFrame(['4/21/2023 11:06:35 AM','4/21/2023 12:06:35 PM', '4/21/2023 1:00:48 PM', '4/21/2023 2:35:37 PM'])
>>> df
                       0
0  4/21/2023 11:06:35 AM
1  4/21/2023 12:06:35 PM
2   4/21/2023 1:00:48 PM
3   4/21/2023 2:35:37 PM
>>> pd.to_datetime(df[0])
0   2023-04-21 11:06:35
1   2023-04-21 12:06:35
2   2023-04-21 13:00:48
3   2023-04-21 14:35:37
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 37ea63d540fd27274cad6585082c91b1283f963d
python           : 3.10.4.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.6.0
Version          : Darwin Kernel Version 21.6.0: Thu Mar  9 20:12:21 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.1
numpy            : 1.24.2
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.4.0
pip              : 23.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.9
lxml.etree       : 4.9.2
html5lib         : None
pymysql          : None
psycopg2         : 2.9.5
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : 0.9.0
xarray           : None
xlrd             : 2.0.1
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by juli4nb4dillo** [comment]
@rainman33 That's correct, it's not a big deal if I manually set the format. However it used to work (without format parameter) with pandas 1.5.3, hence it triggered a few hidden bugs in our software once we upgraded to pandas 2.x.
I suggest raising a warning in case of no format?

**Comment by lithomas1** [comment]
Hi @juli4nb4dillo,
Not at all an expert with our datetime code, but the code changes you're seeing might be a consequence of PDEP-4. 
You can read about it here https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html

If I pass in ``format="mixed"``, I get
```
>>> pd.to_datetime(df[0], format="mixed")
0   2023-04-21 11:06:35
1   2023-04-21 12:06:35
2   2023-04-21 13:00:48
3   2023-04-21 14:35:37
Name: 0, dtype: datetime64[ns]
```
which I think is what you expected. 

It's strange that the parsing didn't throw an error, though. cc @MarcoGorelli who probably knows whether this is a bug or not.

**Comment by MarcoGorelli** [comment]
This is the part of the code which would need changing

[pandas/_libs/tslibs/parsing.pyx](https://github.com/pandas-dev/pandas/blob/d389bd814b1fba0fd112f2cc40c8a915855e02bc/pandas/_libs/tslibs/parsing.pyx#L867-L1035)

Not sure whether to suggest special-casing '`%H'` to become `'%I'` if there's `%p`, or to just stop guessing `'%p'` for safety. Tempted to go with the latter

**Comment by MarcoGorelli** [comment]
cc @davesque @mroeschke

**Comment by mroeschke** [comment]
If AM/PM is in the guessing string, then switching to `%I` where relevant makes sense. Otherwise I don't think it's safe to ever guess `%p` if it's not

**Comment by MarcoGorelli** [comment]
so something like
- if %I is in the guessed format and %H is there too, replace %H with %I
- if %I is in the guessed format, and neither %H nor %I are, then return `None`

Anyone fancy making a PR?

**Comment by juli4nb4dillo** [comment]
@MarcoGorelli https://github.com/pandas-dev/pandas/pull/53244
Sorry it took me a while to setup my environment.
