### ISSUE TITLE
CI/BLD: Doc builds are failing

### ISSUE THREAD

**Issue by ngoldbaum** [pandas-dev/pandas#53167]
Starting in the last hour or so all doc builds on PRs are failing with the following error:

```
Theme error:
An error happened in rendering the page development/community.
Reason: UndefinedError("'logo' is undefined")
```

**Comment by mroeschke** [comment]
xref https://github.com/pydata/pydata-sphinx-theme/issues/1094

so I think it should be fixed by https://github.com/pandas-dev/pandas/pull/53029
