### ISSUE TITLE
QST: 

### ISSUE THREAD

**Issue by tarun18920** [pandas-dev/pandas#53162]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

ValueError: For argument "inplace" expected type bool, received type str.

### Question about pandas

![image](https://github.com/pandas-dev/pandas/assets/126071388/5e5194bd-dfe3-4b32-ba7a-fe02eeca528a)

**Comment by snorfyang** [comment]
Uppercase, ```True``` should be ok.

**Comment by topper-123** [comment]
Yes you need uppcase. Closing.
