### ISSUE TITLE
DOC: update the editable environment installation command

### ISSUE THREAD

**Issue by AlexKirko** [pandas-dev/pandas#53174]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/development/contributing_environment.html#step-3-build-and-install-pandas

### Documentation problem

We state that the proper command to install local pandas in editable mode is:
```
python -m pip install -e . --no-build-isolation --no-use-pep517
```
However, on the current version we are using msonpy as a backend and getting this error on attempted installation:
```
ERROR: Disabling PEP 517 processing is invalid: project specifies a build backend of mesonpy in pyproject.toml
```

### Suggested fix for documentation

Didn't dig too deep into the reasons for this, but looks like this works:
```
python -m pip install -e . --no-build-isolation
```
Any objections to the change?

**Comment by lithomas1** [comment]
I'll pin the meson-python tracker issue for more visibility.

**Comment by lithomas1** [comment]
Actually, the docs slider seems to be broken. Opening an issue for that.

**Comment by AlexKirko** [comment]
Thanks for the clarification.

**Comment by hamedgibago** [comment]
In new version I can not compile with `--no-use-pep517` and when compile without it and want to import pandas it hangs and CPU go to 100%.

**Comment by lithomas1** [comment]
The contributing docs might be outdated. With the new build backend, you can't build pandas with ``--no-use-pep517`` anymore.

Here are the instructions from the devdocs.
https://pandas.pydata.org/docs/dev/development/contributing_environment.html#step-3-build-and-install-pandas

**Comment by hamedgibago** [comment]
> The contributing docs might be outdated. With the new build backend, you can't build pandas with `--no-use-pep517` anymore.
> 
> Here are the instructions from the devdocs. https://pandas.pydata.org/docs/dev/development/contributing_environment.html#step-3-build-and-install-pandas

I compiled it through new documents, but every time I want to import pandas it takes 5-8 minutes with 100% CPU usage to import it. Is it really normal?

**Comment by hamedgibago** [comment]
Thank you, I'll compile and install again with this commands and will tell you the results.
