### ISSUE TITLE
PERF: reading large ods file with `nrows` option takes a long time

### ISSUE THREAD

**Issue by loikein** [pandas-dev/pandas#53185]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this issue exists on the main branch of pandas.

### Reproducible Example

The data file can be downloaded from the following link: https://www.cqc.org.uk/sites/default/files/2023-04/03_April_2023_Latest_ratings.ods (ods, 23.00MB, English)

Command used: (I was not able to come up with more params because my office software crashes when trying to open this file.)

```python
cqc_apr_23 = pd.read_excel(
    "03_April_2023_Latest_ratings.ods",
    nrows=100,
)
```

Time taken (reported by jupyterlab-execute-time): 22m 17.19s

In contrast, reading this csv file (https://www.cqc.org.uk/sites/default/files/2023-05/10_May_2023_CQC_directory.csv (csv, 16.35MB, English)) with `read_csv` and `nrows=100` only takes 154ms.

I cannot decide whether this is a performance issue or a bug. If anyone wants to help or suggest alternative methods, thank you very much.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 37ea63d540fd27274cad6585082c91b1283f963d
python           : 3.11.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
Version          : Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_GB.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 2.0.1
numpy            : 1.24.3
pytz             : 2023.2
dateutil         : 2.8.2
setuptools       : 67.6.0
pip              : 23.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.11.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by loikein** [comment]
Dear @mroeschke, thank you for your reply.

I took a look at odfpy's code, it seems that there is no param to load specific lines at all (https://github.com/eea/odfpy/blob/master/odf/opendocument.py#L975).

From one of their examples (https://github.com/eea/odfpy/blob/master/examples/loadsave.py) I tried the following code, it has been running for 30m and counting…

```python
from odf.opendocument import load
file = "03_April_2023_Latest_ratings.ods"
load(file[:100])
```

**Comment by mroeschke** [comment]
Thanks for checking. Unfortunately, this is an upstream performance issue in odfpy which pandas cannot do anything about. Going to close for now, but feel free to open an issue in the odfpy repo

**Comment by loikein** [comment]
Update: After some digging around, I have found that the [iuvbio/pandas_ods_reader](https://github.com/iuvbio/pandas_ods_reader/tree/master) is much much faster in reading huge ods files (1m 33.83s for reading the sheet 2, compared to 15m 53.26s with `pd.read_excel`).

It uses the [ezodf](https://github.com/T0ha/ezodf) as its engine. My setup has not changed, and it worked out of the box.

I know this is an old and less updated package compared to odfpy, but with such an example, would you consider adding ezodf to the engine lists for ods tables? Thank you very much.
