### ISSUE TITLE
BUG(?): can_hold_element(DTA, np.nan) returns True

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#53206]
```
In [12]: import pandas as pd

In [13]: import numpy as np

In [14]: arr = pd.arrays.DatetimeArray(np.array([np.datetime64("2020-01-01T00:01:01")]))

In [15]: pd.core.dtypes.cast.can_hold_element(arr, np.nan)
Out[15]: True
```

I think this is potentially the case for TDA, PeriodArray too.

Is this expected? cc @jbrockmendel 

I think this is the crux behind https://github.com/pandas-dev/pandas/issues/29024 where this looks buggy

```
In [17]: pd.Series([pd.NaT]).replace({np.nan: 0})
Out[17]: 
0    0
dtype: int64
```

**Comment by jbrockmendel** [comment]
This is expected.  You can do `DTA[0] = np.nan` without raising.

**Comment by mroeschke** [comment]
Cool thanks closing
