### ISSUE TITLE
BUG: Failure to Process 1 Billion Rows Parquet File Using Version 2.0.1

### ISSUE THREAD

**Issue by hkpeaks** [pandas-dev/pandas#53249]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import time
s = time.time()

table1 = pd.read_parquet('Input/1000MillionRows.parquet', engine='pyarrow')

table2 = table1[(
        (table1['Ledger'] == "L10") & (table1['Project'] == "B25"))]


print("filter_quantity(", len(table2.columns), "x", len(table2), ")")

table3 = table2[(
        (table2['Quantity'] >= 100) & (table2['Quantity'] <= 300)
        | (table2['Quantity'] >= 600) & (table2['Quantity'] <= 900))]


print("filter_ledger(", len(table3.columns), "x", len(table3), ")")

table4 = table3[(  
        (table3['Contact'] >= "C32") & (table3['Contact'] <= "C39"))]

table5 = table4[(  
        (table4['Contact'] != "C36"))]

print("filter_contact(", len(table5.columns), "x", len(table5), ")")


table5.to_csv('Output/Pandas-Filter.csv', index=False)

e = time.time()
print("Pandas Filter Time = {}".format(round(e-s,3)))


I use Polars to replicated the dataset https://github.com/hkpeaks/peaks-consolidation/blob/main/Polars-PeaksBenchmarking/Input/1MillionRows.7z to different size of csv and converted to parquet format.
```

### Issue Description

PS D:\Peaks> python pandas.py
Traceback (most recent call last):
  File "D:\Peaks\pandas.py", line 5, in <module>
    table1 = pd.read_parquet('Input/1000MillionRows.parquet', engine='pyarrow')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Peaks\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parquet.py", line 509, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "C:\Users\Peaks\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parquet.py", line 227, in read
    pa_table = self.api.parquet.read_table(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Peaks\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarrow\parquet\core.py", line 2986, in read_table
    return dataset.read(columns=columns, use_threads=use_threads,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Peaks\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarrow\parquet\core.py", line 2614, in read
    table = self._dataset.to_table(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow\_dataset.pyx", line 546, in pyarrow._dataset.Dataset.to_table
  File "pyarrow\_dataset.pyx", line 3449, in pyarrow._dataset.Scanner.to_table
  File "pyarrow\error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 117, in pyarrow.lib.check_status
pyarrow.lib.ArrowMemoryError: malloc of size 262144 failed

### Expected Behavior

if success, the processing result shall be:
PS D:\Peaks> python pandas.py
filter_quantity( 14 x 920000 )
filter_ledger( 14 x 456000 )
filter_contact( 14 x 308000 )

For success or fail operations of Pandas, Peaks and Polars, 
I recorded the whole process in this video https://youtu.be/1Kn665ADSck

For 100MillionRows.csv, if I reboot machine without prior processing, it can run successfully.
For 1000MillionRows.csv, it hang my machine.
If convert 1000MillionRows.parquet to 1000MillionRows.csv, it hang my machine.

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by hkpeaks** [comment]
I have test for import pyarrow.parquet as pq
pq.read_table('Input/1000MillionRows.parquet').to_pandas()

For 100MillionRows.parquet

D:\Peaks>python pandas.py
filter_quantity( 14 x 92000 )
filter_ledger( 14 x 45600 )
filter_contact( 14 x 30800 )
Pandas Filter Time = 37.799
Polars 12.415s for Parquet   Peaks 8.959s for CSV

For 1000MillionRows.parquet

Pandas and Polars are fail for parquet
Peaks 92.206s for csv
Polars 500.002 for csv

D:\Peaks>python pandas.py
Traceback (most recent call last):
  File "D:\Peaks\pandas.py", line 7, in <module>
    table1 = pq.read_table('Input/1000MillionRows.parquet').to_pandas()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\85292\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarrow\parquet\core.py", line 2973, in read_table
    return dataset.read(columns=columns, use_threads=use_threads,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\85292\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarrow\parquet\core.py", line 2601, in read
    table = self._dataset.to_table(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow\_dataset.pyx", line 369, in pyarrow._dataset.Dataset.to_table
  File "pyarrow\_dataset.pyx", line 2818, in pyarrow._dataset.Scanner.to_table
  File "pyarrow\error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 117, in pyarrow.lib.check_status
pyarrow.lib.ArrowMemoryError: malloc of size 114112 failed

-----------------------------------------------------------------------------

import pandas as pd
import pyarrow.parquet as pq

import time
s = time.time()

table1 = pq.read_table('Input/1000MillionRows.parquet').to_pandas()

##table1 = pd.read_csv('Input/10MillionRows.csv', engine='pyarrow')

table2 = table1[(
        (table1['Ledger'] == "L10") & (table1['Project'] == "B25"))]


print("filter_quantity(", len(table2.columns), "x", len(table2), ")")

table3 = table2[(
        (table2['Quantity'] >= 100) & (table2['Quantity'] <= 300)
        | (table2['Quantity'] >= 600) & (table2['Quantity'] <= 900))]


print("filter_ledger(", len(table3.columns), "x", len(table3), ")")

table4 = table3[(  
        (table3['Contact'] >= "C32") & (table3['Contact'] <= "C39"))]

table5 = table4[(  
        (table4['Contact'] != "C36"))]

print("filter_contact(", len(table5.columns), "x", len(table5), ")")


table5.to_csv('Output/Pandas-Filter.csv', index=False)

e = time.time()
print("Pandas Filter Time = {}".format(round(e-s,3)))

**Comment by hkpeaks** [comment]
Please suggest how to config Pandas to read data in chunks.

My Peaks app can determine how to deal with bigtable automatically.

Select{1000MillionRows.csv | Ledger(=L10)Project(=B25) ~ Table}
Select{Quantity(Float100..300,Float600..900)}
Select{Contact(C32..C39)}
Select{Contact(!=C37)}
WriteFile{Table ~ Peaks-Filter.csv}

Required time Peaks is 92.206s, Polars is 501.002s.

**Comment by hkpeaks** [comment]
Bing Chat reply how to config Pandas to read data in chunks:

import pandas as pd

chunksize = 1000
for chunk in pd.read_csv('your_file.csv', chunksize=chunksize):
    process(chunk)

But I don't think this code is useful to solve processing billions of rows within reasonable time.
It requires to work on many batch, and then to combine resulting dataset.
Python is one of very slow programming language.

**Comment by lithomas1** [comment]
Yes, that's the right idea. I don't know if the ``chunksize`` parameter can be passed through directly though.

This should be something like https://stackoverflow.com/questions/59098785/is-it-possible-to-read-parquet-files-in-chunks.

In general, pandas doesn't support out-of-core at all, and it is recommended that you use other libraries, such as Dask when your memory doesn't fit in RAM.

See this link https://pandas.pydata.org/docs/user_guide/scale.html#use-other-libraries.
