### ISSUE TITLE
ENH: default chunksize in mySql

### ISSUE THREAD

**Issue by Polandia94** [pandas-dev/pandas#53243]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

The method `to_sql(method="multi")`,write all rows at once if `chunksize` is not defined.
The default max_allowed_packet in mySql is 64 MB. If the quey is bigger the method will fail. 

### Feature Description

When the database is Mysql and chunksize isn't defined, i suggest to do:
`df.memory_usage(index=True).sum()` to estimate the size of the query (we can do a couple of test to check the relationship between size of the dataframe and the query). If the query will be bigger than 64 MB we can assign a safe chunksize.` (Length of dataframe/(Estimate Size of the Query/ 64MB))`

### Alternative Solutions

Another solution could be to change the error message, when the database return `disconnected during query` if the database is Mysql and the size of the dataframe is big, to sometime like `disconnected during query, maybe the query is too big. check the database logs and use chunksize if necesary`

### Additional Context

I only know of this problem in mySql, but probablly happen in another databases engines.

**Comment by lithomas1** [comment]
Hi, thanks for the bug report.

I don't work with the SQL code, but in general in pandas I believe we dispatch all the SQL handling to SQLAlchemy, so I'm not too keen about adding DB specific logic in pandas itself.

Have you tried raising an issue with SQLAlchemy for a better error message, or is there some flag/option there that already exists for this sort of issue?

**Comment by Polandia94** [comment]
Hi, i think this could be solved in SQLAlchemy, but it's more reasonable to do it in pandas.
In this file, the `insert` in line 1003 calculate the chunksize and execute. It could have a default chunksize if its none
https://github.com/pandas-dev/pandas/blob/main/pandas/io/sql.py

**Comment by lithomas1** [comment]
I think the default chunksize is the length of the dataframe (basically no chunking happens).

Is there a reason you want this handling in pandas itself? 

Googling online, the only issues I can seem to find related to ``max_allowed_packet`` are MySQL related.

**Comment by lithomas1** [comment]
Sorry, I misspoke. I meant to ask if there are any other DBs with this issue?

I don't think this is not easy to handle in pandas itself.

From my understanding, pandas would need to
1) Figure out where ``my.cnf`` is located and if max_allowed_packet is present as a config option, and then know what the default of MySQL for this value is.
    a) This doesn't seem to be exposed by SQLAlchemy, and I'm not sure how pandas is supposed to find ``my.cnf``.
2) Calculate memory usage of the DF and chunk accordingly.

Given this, I think I would much rather have this logic be pushed into SQLAlchemy if they're wiling to accept it. 

We don't have custom SQL logic for any DBs(sans the built in sqlite) in pandas, so I don't think we should add this heuristic unless its an issue with a bunch of DBs in general.

**Comment by mroeschke** [comment]
Closing as it seems that this is an upstream issue
