### ISSUE TITLE
API: ``bool_only`` in any/all still defaults to None

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#53258]
Shouldn't we change this to be consistent with ``numeric_only``?

cc @rhshadrach was this deliberately not changed before 2.0?

**Comment by rhshadrach** [comment]
Yep - this was missed when grepping for `numeric_only`. Thanks.

**Comment by phofl** [comment]
lets deprecate then and change in 3.0

**Comment by rhshadrach** [comment]
I believe `None` behaves the same as `False`, so there isn't any difference from a user perspective. I think we can target this for 2.1.
