### ISSUE TITLE
BUG: `loc` treating 0/1 as boolean with boolean elements in the index column 

### ISSUE THREAD

**Issue by Rylie-W** [pandas-dev/pandas#53267]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame({'a': [True, False, "Missing"], "b": [1, 2, 3]}).set_index("a")
df.loc[0]
"""
Output: 
b    2
Name: False, dtype: int64
"""
df.loc[[0,1]]
"""
Output:
       b
a       
False  2
True   1
"""

df2 = pd.DataFrame({'a': [0, 1, True, False, "Missing"], "b": [1, 2, 3, 4, 5]}).set_index("a")
df2.loc[True]
"""
Output:
KeyError: 'True: boolean label can not be used without a boolean index'
"""
```

### Issue Description

`_LocIndexer._getitem_iterable()` should distinguish boolean type from 0/1

### Expected Behavior

```
KeyError: 0
KeyError: "None of [Index([0, 1], dtype='int64', name='a')] are in the [index]"
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 37ea63d540fd27274cad6585082c91b1283f963d
python           : 3.9.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.6.0
Version          : Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8
pandas           : 2.0.1
numpy            : 1.23.5
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 67.6.0
pip              : 23.0.1
Cython           : 0.29.33
pytest           : 7.2.2
hypothesis       : 6.69.0
sphinx           : 5.3.0
blosc            : 1.11.1
feather          : None
xlsxwriter       : 3.0.9
lxml.etree       : 4.9.2
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : 2.9.5
jinja2           : 3.1.2
IPython          : 8.11.0
pandas_datareader: None
bs4              : 4.11.2
bottleneck       : 1.3.7
brotli           : 
fastparquet      : 2023.2.0
fsspec           : 2023.3.0
gcsfs            : 2023.3.0
matplotlib       : 3.6.3
numba            : 0.56.4
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.1.0
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : 1.2.1
pyxlsb           : 1.0.10
s3fs             : 2023.3.0
scipy            : 1.10.1
snappy           : 
sqlalchemy       : 2.0.6
tables           : 3.8.0
tabulate         : 0.9.0
xarray           : 2023.2.0
xlrd             : 2.0.1
zstandard        : 0.20.0
tzdata           : 2022.7
qtpy             : None
pyqt5            : None

</details>

**Comment by topper-123** [comment]
In python booleans are ints (`isinstance(True, int)` gives True), so that kind of behavior goes with the territory of using `object dtype`. The fix in pandas is to use a boolean dtype.

Your last example (`df2.loc[True]`) though looks wrong for me, that should not fail. A PR would be welcome, this is probably an easy fix (in `_LocIndexer._validate_key`).

**Comment by Charlie-XIAO** [comment]
Hi @topper-123 I'm pretty interested in this issue, but I wonder how this can be an easy fix. In the source code,
```python
if isinstance(key, bool) and not (
    is_bool_dtype(ax.dtype)
    or ax.dtype.name == "boolean"
    or isinstance(ax, MultiIndex)
    and is_bool_dtype(ax.get_level_values(0).dtype)
):
    raise KeyError(
        f"{key}: boolean label can not be used without a boolean index"
    )
```
it is stated that "boolean label cannot be used without a boolean index", which (I think) indicates that the last example should not be valid. Also, how can we know the dtype of a specific label when the dtype of the index is not boolean dtype?

**Comment by topper-123** [comment]
I would replace that conditional with something like: 
 
```python
if isinstance(key, bool) and not (
    ax.dtype.kind in ["b", "O"]
    or isinstance(ax, MultiIndex) and ax._levels[0].dtype.kind in ["b", "O"]
):
    raise KeyError(
        f"{key}: boolean label can not be used without a boolean index"
    )
```

I.e. add a check for object dtype there as well (I also refactored it a bit to make it faster). I think that should work correctly. Can you check this and make a PR if it works?

**Comment by Charlie-XIAO** [comment]
Sure, thanks for your suggestion! However my working environment is broken for some reason so I may need some time for that. I will try ASAP.

**Comment by Rylie-W** [comment]
> I would replace that conditional with something like:
> 
> ```python
> if isinstance(key, bool) and not (
>     ax.dtype.kind in ["b", "O"]
>     or isinstance(ax, MultiIndex) and ax._levels[0].dtype.kind in ["b", "O"]
> ):
>     raise KeyError(
>         f"{key}: boolean label can not be used without a boolean index"
>     )
> ```
> 
> I.e. add a check for object dtype there as well (I also refactored it a bit to make it faster). I think that should work correctly. Can you check this and make a PR if it works?

Hi @topper-123 ! The solution also works for issue [#52102] IMO, even though I haven't tried it due to the installation error I met with `python setup.py build_ext -j 4` and `python -m pip install -e . --no-build-isolation --no-use-pep517`:
```
ERROR: Disabling PEP 517 processing is invalid: project specifies a build backend of mesonpy in pyproject.toml
```

Since the two issues are essentially the same, so maybe we can close this one?

**Comment by topper-123** [comment]
Yeah it is the same, so I agree it can be closed. Discussion can continue in #52102.
