### ISSUE TITLE
BUG: MKL Warning with Pandas Import

### ISSUE THREAD

**Issue by jlandgre** [pandas-dev/pandas#53270]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
```

### Issue Description

When importing Pandas in a Python 3.11.3 Conda environment, I see (two, duplicate) warning messages:

 "Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions."

I can't find MKL documentation explaining this warning.

The messages are not suppressible with warnings.filterwarnings('ignore')

### Expected Behavior

Deprecation warning messages can be suppressed. Warning messages explain possible remediation actions by user (e.g. install a different version of package xyz etc.)

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : 37ea63d540fd27274cad6585082c91b1283f963d
python           : 3.11.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.6.0
Version          : Darwin Kernel Version 21.6.0: Thu Mar  9 20:12:21 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_ARM64_T6000
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.1
numpy            : 1.24.3
pytz             : 2022.7
dateutil         : 2.8.2
setuptools       : 66.0.0
pip              : 23.0.1
Cython           : None
pytest           : 7.3.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.13.2
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : 1.3.5
brotli           : 
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

**Comment by jbrockmendel** [comment]
Do you get the same warning with `import numpy as np`?

**Comment by jlandgre** [comment]
Just checked. Yes I do

**Comment by mroeschke** [comment]
Thanks for the report, but as mentioned this isn't directly a pandas issue so closing. You may want to raise this on the numpy issue tracker

**Comment by jlandgre** [comment]
Ok, I see your POV @mroeschke. I created [this numpy issue](https://github.com/numpy/numpy/issues/23775) that will look familiar. Given that this does reflect Pandas UI for users who do not use Numpy directly, appreciate if you comment there in support of getting it resolved. My POV is that there are many Pandas users who don't know/care how the Numpy sausage is made under the hood of Pandas. Thanks!
