### ISSUE TITLE
DOC: Change "Convention for examples" to use Series name as `ser` instead of `s` 

### ISSUE THREAD

**Issue by DeaMariaLeon** [pandas-dev/pandas#53271]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/development/contributing_docstring.html#conventions-for-the-examples

### Documentation problem

There's a general preference to use `ser =` instead of `s =`  in examples

Per @MarcoGorelli 

### Suggested fix for documentation

Change `s` to `ser` on paragraph:

"When illustrating examples with a single Series use the name `s`, and if illustrating with a single DataFrame use the name df. For indices, idx is the preferred name. If a set of homogeneous Series or DataFrame is used, name them `s1`, `s2`, `s3`"

**Comment by MarcoGorelli** [comment]
thanks - yeah I've seen people request non-single-letter-variables in reviews, but the docstring guide still advises to use them - looks like the preference changed but nobody codified it. Would be good to change it

**Comment by topper-123** [comment]
+1

**Comment by austinburnett** [comment]
Hello! I'd be happy to work on this issue.

**Comment by DeaMariaLeon** [comment]
Hi @austinburnett ! Great, please go ahead.

**Comment by austinburnett** [comment]
Hey @DeaMariaLeon it looks like I believed I finished up the issue! https://github.com/pandas-dev/pandas/pull/53312

**Comment by shreevaths1** [comment]
First time contribution to open source. Please guide me as to what is the first step I can take

**Comment by DeaMariaLeon** [comment]
@austinburnett we commented there, thanks.

@shreevaths1 : This issue is taken. But you can take a look at https://pandas.pydata.org/docs/development/contributing.html#where-to-start
