### ISSUE TITLE
BUG: read_csv parsing error with double pipe ("||") separator

### ISSUE THREAD

**Issue by inbal-afori** [pandas-dev/pandas#53285]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import io
import pandas as pd
lines = "col1||col2\nval1||val2\nval3||val4\n"

pd.read_csv(io.StringIO(lines), sep='||')

#
```

### Issue Description

when the separator is a double pipe, each letter in the first row is treated as a column-

`   Unnamed: 0  c  o  l  1  | |.1 c.1 o.1 l.1  2  Unnamed: 11`
`0         NaN  v  a  l  1  |   |   v   a   l  2          NaN`
`1         NaN  v  a  l  3  |   |   v   a   l  4          NaN`

### Expected Behavior

when escaped, works properly - 
In   [1] `pd.read_csv(io.StringIO(lines), sep='\|\|')`
Out[1] 
`   col1  col2`
`0  val1  val2`
`1  val3  val4`
maybe should be escaped :)

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 08604862bff7cd6f1c878e3f48e1485d0a8e071a
python           : 3.10.0.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 22.1.0
Version          : Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.1.0.dev0+782.g08604862bf
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 57.4.0
pip              : 21.2.3
Cython           : 0.29.33
pytest           : 7.3.1
hypothesis       : 6.75.3
sphinx           : 6.2.1
blosc            : 1.11.1
feather          : None
xlsxwriter       : 3.1.0
lxml.etree       : 4.9.2
html5lib         : 1.1
pymysql          : 1.0.3
psycopg2         : 2.9.6
jinja2           : 3.1.2
IPython          : 8.12.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : 1.3.7
brotli           :
fastparquet      : 2023.4.0
fsspec           : 2023.5.0
gcsfs            : 2023.5.0
matplotlib       : 3.7.1
numba            : 0.57.0
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : 12.0.0
pyreadstat       : 1.2.1
pyxlsb           : 1.0.10
s3fs             : 2023.5.0
scipy            : 1.10.1
snappy           :
sqlalchemy       : 2.0.13
tables           : 3.8.0
tabulate         : 0.9.0
xarray           : 2023.4.2
xlrd             : 2.0.1
zstandard        : 0.21.0
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by lithomas1** [comment]
Hi,
Thanks for opening an issue.

I don't think this is a bug, when I run your code, I get
```
<stdin>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
```

From this, you can tell that the separator is being interpreted as regex. It's also mentioned in the docs. 
(from the page for ``read_csv``)
![image](https://github.com/pandas-dev/pandas/assets/47963215/f938dff8-745d-4dcb-98f5-773b32eda899)


In regex, ``|`` is a special character, so you would have to escape it yourself.

Does this clarify the current behavior for you?

**Comment by topper-123** [comment]
Yes, I agree with @lithomas1. You can read that in by escaping in the sep argument: `pd.read_csv(io.StringIO(lines), sep='\|\|')`.

So I'm closing, but if there's any issue here that still needs to be discussed, just call out and I'll reopen.
