### ISSUE TITLE
NaNs during dataframe merge

### ISSUE THREAD

**Issue by DanielThedie** [pandas-dev/pandas#53303]
I have been trying to merge dataframes based on a common numercial column with different sampling (e.g. 1, 2, 3... against 1, 1.5, 2, 2.5, 3,...). this works when the indices of the larger dataframe start at 0, and/or when that dataframe is twice as large as the one it's merged to. However if the indices start at 1, and the dataframe is 10 times larger, the merge results in NaN values after the first row.

Sorry if this is not very clear, here is a minimal example to illustrate:
```python
import pandas as pd
import numpy as np

df1 = pd.DataFrame({'x': np.arange(1, 101, 0.5), 'y1': np.arange(1, 201, 1)})
df1b = pd.DataFrame({'x': np.arange(1, 101, 0.1), 'y1': np.arange(1, 1001, 1)})
df1c = pd.DataFrame({'x': np.arange(0, 100, 0.1), 'y1': np.arange(1, 1001, 1)})
df2 = pd.DataFrame({'x': np.arange(1, 101, 1.0), 'y2': np.arange(1, 101, 1)})

print(pd.merge(left=df1, right=df2, on='x', how='right').head(5))
print(pd.merge(left=df1b, right=df2, on='x', how='right').head(5))
print(pd.merge(left=df1c, right=df2, on='x', how='right').head(5))
```

Merging df2 with df1 or df1c works correctly, but merging df2 with df1b yields NaN values.

OS: Windows 10
Package versions:
- Python 3.9.13
- pandas 2.0.1
- numpy 1.24.3

**Comment by topper-123** [comment]
Look like you're merging on float, which inherently can give problems with values being close but not the same, for example:

```python
>>> df1b.iloc[10, 0] == df2.iloc[1, 0]
False
>>> df1b.iloc[10, 0], df2.iloc[1, 0]
(2.000000000000001, 2.0)
```

`pd.merge`  requires exact equality. If I misunderstood your question, feel free to follow up and I will respond and reopen, if so.

**Comment by DanielThedie** [comment]
That answers my question! Thank you for taking the time to explain.
