### ISSUE TITLE
asfreq_info has redundant fields / poor comments

### ISSUE THREAD

**Issue by cancan101** [pandas-dev/pandas#5333]
looking at the definition for the `asfreq_info` struct in `period.h`, I see the following lines:

```
int from_a_year_end; // month the year ends on in the "from" frequency
int from_q_year_end; // month the year ends on in the "from" frequency

int to_a_year_end;   // month the year ends on in the "to" frequency
int to_q_year_end;   // month the year ends on in the "to" frequency
```

As far as I can tell, the comments are wrong and a union could have been used for these values as they are never simultaneous set. 

Thoughts?

**Comment by jbrockmendel** [comment]
These attributes no longer exist.  Closeable?
