### ISSUE TITLE
ENH: Support for Numeric Indexing in DataFrameGroupBy Object

### ISSUE THREAD

**Issue by Kreijstal** [pandas-dev/pandas#53337]
### Feature Type

- [X] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

 Currently, a GroupBy object in pandas doesn't support indexing by numeric column index directly. Users need to apply an aggregation function first to make it a DataFrame, and then select the column. However, this doesn't necessarily provide the same result as `grouped['column_name']`, depending on the type of aggregation used.

### Feature Description

A method to select a column from a DataFrameGroupBy object by its numeric index. This method should work in such a way that it provides the same result as `grouped['column_name']`.

        ```python
        grouped = df.groupby('grouping_column')
        grouped.get_column(column_index)
        ```

        The `get_column` function is a new method that allows us to get a column by its numeric index from a DataFrameGroupBy object.
        
Or with the iloc attribute

### Alternative Solutions

An alternative way to achieve similar functionality is to apply an aggregation method (like `mean()`, `sum()`, `first()`, etc.) to make it a DataFrame, and then select the column.

        ```python
        grouped = df.groupby('grouping_column')
        grouped_df = grouped.mean()  # or any other aggregation method
        column_index = grouped_df.columns.get_loc('column_name')
        selected_column = grouped_df.iloc[:, column_index]
        ```

        This approach has a disadvantage that it requires an aggregation function first and might not provide the same result as `grouped['column_name']` depending on the type of aggregation used.

**Comment by rhshadrach** [comment]
Thanks for the request. I think my main hesitancy is whether this is a useful addition to the API. In my experience, using labels is far superior than numerical positions. Can you give more details on your use case as to why you prefer numerical positions?

The alternative I would recommend is

    df.iloc[:, column_index].groupby(df['grouping_column']).mean()

**Comment by mroeschke** [comment]
Agreed with the above comment, since there hasn't really been more support for this request going to closing for now
