### ISSUE TITLE
DEV: codeowners file?

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#53340]
GitHub now lets you define "codeowners" - all it means is that, if a pull request modifies a part of the codebase which you're a codeowner of, you'll automatically be notified for review.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

The rest is unchanged, you should still seek approval before merging PRs. Everything stays the same, it's just a way to manage review requests

Only people with write access can be codeowners. I suggest there not be any formal process for this - if there's a part of the codebase you'd like to be notified about when there's a PR targeting it, you can add yourself to the `.github/codeowners` file

I don't think there's any obligation to review - e.g. if there's two codeowners for the same path, it's not necessary that both of them review each PR touching that path (so, one codeowner going on holiday won't block PRs to their paths)

For example, I'd like to be requested for review for `pandas/_libs/tslibs/*` and `pandas/core/tools/datetimes.py`

Anyone else want to be added to the codeowners file? @pandas-dev/pandas-core 

I'll make a PR in a few days with whoever responds, anyone else can always make a PR to add themselves later

**Comment by datapythonista** [comment]
Sounds amazing. Can you add me to `web/` for now? Thanks!

**Comment by mroeschke** [comment]
I would like to be added to `ci/` and `.github/`

**Comment by WillAyd** [comment]
I can be added to _libs

**Comment by Dr-Irv** [comment]
Add me to `pandas/_typing.py` and `doc/cheatsheet`

-Irv

**Comment by rhshadrach** [comment]
For myself, `pandas/core/groupby/*` and `pandas/io/excel/*`

**Comment by attack68** [comment]
`pandas/io/formats/style.py`, `pandas/io/formats/style_render.py`, `pandas/io/formats/templates`, please.

**Comment by MarcoGorelli** [comment]
thanks all

marking as good first issue - I think https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners should be clear about what needs doing, feel free to tag me for review if you open a PR

**Comment by rhshadrach** [comment]
@MarcoGorelli - This is closed by #53484, right?

**Comment by MarcoGorelli** [comment]
yup, thanks!
