### ISSUE TITLE
DOC: 

### ISSUE THREAD

**Issue by bobir01** [pandas-dev/pandas#53350]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.read_html.html#pandas-read-html

### Documentation problem

URL in string docs of `pandas.read_html()` leads to the `404` page 
![image](https://github.com/pandas-dev/pandas/assets/68824641/50d07f94-8725-4043-a2d9-ee0bba61ea2b)

but the page is not found in the docs 
![image](https://github.com/pandas-dev/pandas/assets/68824641/1211098f-563d-4e58-8466-0d0f99be4a90)

### Suggested fix for documentation

just fix and replace the URL in the doc string of the source 
***I am using version 2.0.1***

**Comment by MarcoGorelli** [comment]
thanks for the report - sorry which is the link which doesn't work?

**Comment by bobir01** [comment]
> thanks for the report - sorry which is the link which doesn't work?

in pycharm, when I have hover,mouse over the function, it shows the formatted doc string and there is written "to learn more click the URL" I am sure that the link is assigned in doc string

**Comment by MarcoGorelli** [comment]
thanks - please report to pycharm, looks like a bug on their side

closing then
