### ISSUE TITLE
Pandas can not be added as a citation using Mendeley

### ISSUE THREAD

**Issue by TamerGezici** [pandas-dev/pandas#53376]
Using the DOI, 10.5281/zenodo.3509134

Pandas can not be added to Mendeley reference manager.

![image](https://github.com/pandas-dev/pandas/assets/11014942/fc757bfa-a154-4ff7-832e-86a63bb1ea0a)

**Comment by jbrockmendel** [comment]
im not clear on what you're asking for here.

**Comment by TamerGezici** [comment]
Sorry for the unclear explanation.

I am writing a journal article and I would like to cite pandas.

Mendeley is a reference (citation manager) which can receive metadata via a supplied DOI id.

The Pandas' DOI does not work on Mendeley, as the metadata is not available.

**Comment by topper-123** [comment]
Letting users of Mendeley being able to cite pandas does sound like something we'd want, but the pandas developers may not be familiar with this software  or how to suppy(?) meta data?

Can you explain how/what the pandas project can do to improve this situation? Is this something the pandas project should fix, or is this for users of Mandaley to fix?

**Comment by TamerGezici** [comment]
> Letting users of Mendeley being able to cite pandas does sound like something we'd want, but the pandas developers may not be familiar with this software or how to suppy(?) meta data?
> 
> Can you explain how/what the pandas project can do to improve this situation? Is this something the pandas project should fix, or is this for users of Mandaley to fix?

I think it is something that Pandas developers should fix, by contacting Zenodo because probably it is on their end (as the DOI seems to be supplied by Zenodo)

**Comment by TamerGezici** [comment]
I e-mailed Zenodo myself and told them their DOIs do not work at all because it seems like an issue that is not related to Pandas. Let's see what they say.

**Comment by topper-123** [comment]
> I e-mailed Zenodo myself.

Great. I don't use Mandaley myself, and I think the chances of this getting improved is highest if someone who is experiences a problem takes the lead in fixing it.

**Comment by phofl** [comment]
Agreed, closing for now if this is not on our side
