### ISSUE TITLE
ENH: Support explode for ArrowDtype 

### ISSUE THREAD

**Issue by csubhodeep** [pandas-dev/pandas#53373]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish for the functions that are still not supported an `Exception` is thrown. For instance, for the below snippet I try and use the [`explode`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.explode.html#pandas-dataframe-explode) method on two `DataFrame`s one having `pyarrow` backed data type and another `numpy`.
```python
import pyarrow as pa
import pyarrow.parquet as pq

pydict = {'x': [[1,2], [3]], 'y': ['a', 'b']}
table = pa.Table.from_pydict(pydict)
print(table.schema)
```
```shell
x: list<item: int64>
  child 0, item: int64
y: string
```
```python
pq.write_table(table, 'test.parquet')
df_pa = pd.read_parquet('test.parquet', dtype_backend='pyarrow')
df = pd.read_parquet('test.parquet')
```
I make the `DataFrame`s by reading from the `parquet` files because when doing in-memory using the [`convert_dtypes`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.convert_dtypes.html#pandas-dataframe-convert-dtypes) method it casts column `x` as `object`.

If I check schema
```python
df_pa.info()
```
```shell
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype                     
---  ------  --------------  -----                     
 0   x       2 non-null      list<item: int64>[pyarrow]
 1   y       2 non-null      string[pyarrow]           
dtypes: list<item: int64>[pyarrow](1), string[pyarrow](1)
memory usage: 170.0 bytes
```
```python
df.info()
```
```shell
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   x       2 non-null      object
 1   y       2 non-null      object
dtypes: object(2)
memory usage: 160.0+ bytes
```
If I try to extract one element from each
```python
df_pa.iloc[0].values
```
```shell
array([list([1, 2]), 'a'], dtype=object)
```
```python
df.iloc[0].values
```
```shell
array([array([1, 2]), 'a'], dtype=object)
```
I do note how the dtype is different in both.

FInally, if I try to call the `explode` method on:
1. The `numpy` backed dtype
```python
df.explode('x')
```
Output
```shell
   x  y
0  1  a
0  2  a
1  3  b
```
2. The `pyarrow` backed dtype
```python
df_pa.explode('x')
```
Output (without any error)
```shell
       x  y
0  [1 2]  a
1    [3]  b
```
So basically, this was not the result I was expecting.

P.S. I was not sure if this would rather qualify as a bug.

Platform details
```shell
Platform:    macOS-13.3.1-arm64-arm-64bit
Python:      3.9.16 (main, May 16 2023, 20:00:19) 
[Clang 14.0.3 (clang-1403.0.22.14.1)]
numpy:       1.24.3
pandas:      2.0.1
pyarrow:     10.0.1
```

### Feature Description

I don't know enough about the internals of pandas to propose anything here.

### Alternative Solutions

For the functions which are not natively supported for `pyarrow` backed data frames could we internally convert them to the `numpy` one, do the operation and convert them back? In this case a warning message would make sense.

But again since I don't know enough whether such a make-shift solution meets the standards wrt performance/api design etc I would not be able to make a suggestion here.

**Comment by csubhodeep** [comment]
Also please confirm if the operations listed [here](https://pandas.pydata.org/docs/user_guide/pyarrow.html#operations) are the only ones that are supported for the `pyarrow` backed dtypes. Thanks ! :-)

**Comment by phofl** [comment]
-1 on raising, falling back to numpy is a suitable alternative in a bunch of scenarios for now

**Comment by csubhodeep** [comment]
> -1 on raising, falling back to numpy is a suitable alternative in a bunch of scenarios for now

If I understood you correctly you mean that we should rather refrain from using `pyarrow` backed dtypes in most (if not all) operations?

**Comment by lithomas1** [comment]
Is it just ``explode`` where functionality is missing?

I think most of the methods should have Arrow implementations, so it's probably easier to just fix the ones that don't that can be fixed.

**Comment by csubhodeep** [comment]
@lithomas1 
> Is it just `explode` where functionality is missing?
> 
Sorry but haven't checked for all of them.

**Comment by mroeschke** [comment]
Going to change this issue to be explode specific. I don't think it's really feasible to warn on _every_ methods that don't support arrow now; and the time is better spent supporting the method instead

**Comment by lukemanley** [comment]
> Going to change this issue to be explode specific.

@mroeschke - With the scope reduced to `explode`, would you say #53602 closes it?

**Comment by mroeschke** [comment]
Ah right I believe https://github.com/pandas-dev/pandas/pull/53602 closes this
