### ISSUE TITLE
DOC:  Unexpected assignation of values in column.

### ISSUE THREAD

**Issue by MeliJuanmi** [pandas-dev/pandas#53377]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.Series.html
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html
https://pandas.pydata.org/docs/dev/user_guide/indexing.html#

### Documentation problem

Theres is no documentation of the assignament of values in a column dataframe when a pd.Series is passed. We found that assignement is done by index and not order. This can create huge problems when assignated values when transforming data.
Replication problem: 

df = pd.DataFrame([1,2], columns=['first_column'])
df.index = [2,1]
df2 = pd.Series([0,1,3])
print(df2)
df['second_column'] = df2
df

### Suggested fix for documentation

!Warning:

For assignation in a column of a pd.DataFrame based on a pd.series, take in consideration that assignation is done by index and not in order.  If thats the case remember to reset index or pass to_list() to assignement.

Replication warning:

```
df = pd.DataFrame([1,2], columns=['first_column'])
df.index = [2,1]
df2 = pd.Series([0,1,3])
print(df2)
df['second_column'] = df2
df
```

**Comment by mroeschke** [comment]
Thanks for the report. This is covered in the `warning` block in https://pandas.pydata.org/docs/user_guide/indexing.html#basics

> pandas aligns all AXES when setting Series and DataFrame from .loc, and .iloc.

**Comment by MeliJuanmi** [comment]
Just for the record, this was before the report ? Or was just added ?

**Comment by mroeschke** [comment]
It appears this note has been in the docs in previous versions
