### ISSUE TITLE
BUG: access pd.MultiIndex using index differs when converted to list and then accessed

### ISSUE THREAD

**Issue by hkad98** [pandas-dev/pandas#53386]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

index = pd.MultiIndex.from_tuples([('0', np.nan), ('1', np.nan), ('2', np.nan)])
index = index.set_levels(index.levels[1].astype("float64"), level=1)

print(index[0] == list(index)[0])
# False

index = index.set_levels(index.levels[1].astype("object"), level=1)

print(index[0] == list(index)[0])
# True
```

### Issue Description

I came across this issue during the update to 2.0.1 while during `df.rename(columns={pd.NA: np.nan}, inplace=True)` dtype of index level containing only np.nan changed to **float64** in version 1.5.3 dtype was **object**.

### Expected Behavior

I expect `index[0] == list(index)[0]` to return True in the case of **float64** dtype. 

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 37ea63d540fd27274cad6585082c91b1283f963d
python           : 3.11.1.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 22.3.0
Version          : Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8
pandas           : 2.0.1
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.8.0
pip              : 23.1.2
Cython           : 0.29.34
pytest           : 7.3.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : 0.57.0
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by topper-123** [comment]
This isn't reproducible currently, can you define `pivoted`.

**Comment by hkad98** [comment]
@topper-123 fixed

**Comment by topper-123** [comment]
Thanks for updating @hkad98.

Pandas only formally supports nan-comparisons through the `isna` method, which isn't implemented for `MultiIndex`. I recommend converting to a dataframe `index.to_frame().isna(param)`. A PR to make MI support isna would be welcome.

Having said that, I looked into your example, and in numpy object nan is not the same as numpy float64 nan:

```python
>>> x1 = np.array(np.nan, dtype="object")
>>> x2 = np.array(np.nan, dtype="float64")
>>> x1.item() is x2.item()
False
```

I don't think we are willing to paper over this difference in pandas (but we would like to get the `isna` method working for MultiIndex :-)).
