### ISSUE TITLE
BUG: Typo

### ISSUE THREAD

**Issue by Bhasha03** [pandas-dev/pandas#53395]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
titanic.iloc[0:3, 3] = "anonymous"
```

### Issue Description

In the section:
“How do I select specific rows and columns from a DataFrame?
 
In the following snippet, the value 3 means 4th column.:
 
In [26]: titanic.iloc[0:3, 3] = "anonymous"
 
But in the sentence “When selecting specific rows and/or columns with loc or iloc, new values can be assigned to the selected data. For example, to assign the name anonymous to the first 3 elements of the **third** column:” . The word highlighted in bold talks about 3rd column. Please correct it. Thank you.

### Expected Behavior

When selecting specific rows and/or columns with loc or iloc, new values can be assigned to the selected data. For example, to assign the name anonymous to the first 3 elements of the **fourth** column:

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.10.11.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.107+
Version          : #1 SMP Sat Apr 29 09:15:28 UTC 2023
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.22.4
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 67.7.2
pip              : 23.1.2
Cython           : 0.29.34
pytest           : 7.2.2
hypothesis       : None
sphinx           : 3.5.4
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.2
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.9.6
jinja2           : 3.1.2
IPython          : 7.34.0
pandas_datareader: 0.10.0
bs4              : 4.11.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2023.4.0
gcsfs            : None
matplotlib       : 3.7.1
numba            : 0.56.4
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : 0.17.9
pyarrow          : 9.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : 2.0.10
tables           : 3.8.0
tabulate         : 0.8.10
xarray           : 2022.12.0
xlrd             : 2.0.1
xlwt             : None
zstandard        : None
tzdata           : 2023.3

</details>

**Comment by punndcoder28** [comment]
Hey. Is this the same issue that can be seen [here](https://pandas.pydata.org/pandas-docs/version/1.3/getting_started/intro_tutorials/03_subset_data.html) in the docs? I will be able to work on the doc changes by submitting a PR

**Comment by MarcoGorelli** [comment]
thanks, PRs welcome

**Comment by UmbertoFasci** [comment]
Got the ball rolling on this doc issue. Thank you @Bhasha03 for giving attention to this.
