### ISSUE TITLE
DEPR: fillna 'method'

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#53394]
Seems like `obj.fillna(method="ffill")` is redundant with `obj.ffill()`.  If that is accurate, we should deprecate the method keyword in fillna.

**Comment by jreback** [comment]
+1 this is duplicative

**Comment by pierre-haessig** [comment]
I just came across this deprecation, a little late in the party. And I really don't get it: what's the point of `fillna()` if the two possible keyword values(*) are deprecated? In fact I had never heard of `ffill()` and `bfill()` before and I agree that there is an API redundancy, but I would put the blame on `ffill()` and `bfill()` instead.

(*) the None value is also possible, but I don't know what it is supposed to do...
