### ISSUE TITLE
DOC: pandas.NA repeated on website

### ISSUE THREAD

**Issue by DeaMariaLeon** [pandas-dev/pandas#53404]
The link to pandas.NA can be found 3 times on the [web's](https://pandas.pydata.org/docs/reference/api/pandas.NA.html#pandas.NA) leftsidebar - 
Please see pic.

It seems related to PR #48455 @mroeschke 

![pandas NA](https://github.com/pandas-dev/pandas/assets/11835246/bf1d721d-9fb7-474b-96ca-1edcfc7a0920)

@MarcoGorelli  FYI

**Comment by MarcoGorelli** [comment]
yup, that's right! maybe it's OK to make a separate section (say, called "Missing values") in which you just say that NA is the way to represent missing values for nullable dtypes (see below)? Then, in that section, you just include the link to NA

**Comment by jadelsoufi** [comment]
take

**Comment by jadelsoufi** [comment]
I tried to build the documentation locally with sphinx but I get this error :

```
WARNING: ources... [  1%] getting_started/intro_tutorials/04_plotting          ts
>>>-------------------------------------------------------------------------
Warning in C:\Users\jadel\Documents\myfirstcontribution\pandas\doc\source\getting_started\intro_tutorials\04_plotting.rst at block ending on line 70
Specify :okwarning: as an option in the ipython:: block to suppress this message
----------------------------------------------------------------------------
<ipython-input-6-1eb00ff78cf2>:1: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
<<<-------------------------------------------------------------------------

Exception occurred:
  File "C:\Users\jadel\micromamba\envs\pandas-dev\lib\site-packages\IPython\sphinxext\ipython_directive.py", line 600, in process_input
    raise RuntimeError('Non Expected warning in `{}` line {}'.format(filename, lineno))
RuntimeError: Non Expected warning in `C:\Users\jadel\Documents\myfirstcontribution\pandas\doc\source\getting_started\intro_tutorials\04_plotting.rst` line 70
```

Is this matplotlib error normal when building html with sphinx ? Should I change matplotlib backend or is there another solution ?
The error says "Specify :okwarning: as an option in the ipython:: block to suppress this message"  but I'm not really sure if changing the doc code is a good idea
