### ISSUE TITLE
DOC: Codes snippets in blog for "fundamental python debugging" maybe wrong

### ISSUE THREAD

**Issue by luke396** [pandas-dev/pandas#53402]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/development/debugging_extensions.html

https://willayd.com/fundamental-python-debugging-part-2-python-extensions.html

### Documentation problem

In the second blog post, specifically in the section titled "## Building our first extension," I believe there is an error in the provided code file, `debugging_demo.c`. It appears that the macro 'PyMODINIT_FUC' should actually be 'PyMODINIT_FUNC'  or perhaps there may be other errors as well.

As I am not well-versed in the C language, I just encountered an error when following blog and attempting to compile the code using `gcc -g3 -Wall -Werror -std=c17 -shared -fPIC -I/usr/local/include/python3.10d debugging_demo.c -o debugging_demo.so`.

```shell
root@e465e44c8425:/data# gcc -g3 -Wall -Werror -std=c17 -shared -fPIC -I/usr/local/include/python3.10d debugging_demo.c -o debugging_demo.so
debugging_demo.c:24:9: error: 'PyMODINIT_FUC' undeclared here (not in a function); did you mean 'PyMODINIT_FUNC'?
   24 |         PyMODINIT_FUC PyInit_debugging_demo(void){
      |         ^~~~~~~~~~~~~
      |         PyMODINIT_FUNC
debugging_demo.c:24:23: error: expected '}' before 'PyInit_debugging_demo'
   24 |         PyMODINIT_FUC PyInit_debugging_demo(void){
      |                       ^~~~~~~~~~~~~~~~~~~~~
debugging_demo.c:17:51: note: to match this '{'
   17 | static struct PyModuleDef debugging_demo_module = {
      |                                                   ^
debugging_demo.c:17:27: error: 'debugging_demo_module' defined but not used [-Werror=unused-variable]
   17 | static struct PyModuleDef debugging_demo_module = {
      |                           ^~~~~~~~~~~~~~~~~~~~~
debugging_demo.c:11:20: error: 'DebuggingDemoMethods' defined but not used [-Werror=unused-variable]
   11 | static PyMethodDef DebuggingDemoMethods[] = {
      |                    ^~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

### Suggested fix for documentation

I recognize that the issue could potentially be due to my own lack of understanding rather than an error in the code snippet itself. If that is the case, please provide me with any necessary insights. 

And I understand that it might be considered impolite or inappropriate to point out mistakes made by individual bloggers. If that is the case, please let me know. However, I would greatly appreciate any guidance or clarification on this matter.

**Comment by mroeschke** [comment]
cc @WillAyd

**Comment by WillAyd** [comment]
Thanks @luke396 for bringing this up. Looks like there were quite a few typos in that section which I have since fixed up. I really appreciate you opening an issue about this.

If you run into any other problems feel free to ping me on the pandas slack channel, or alternately you can open issues on the github repo that houses my blog https://github.com/WillAyd/willayd.github.io

**Comment by luke396** [comment]
Thank you  @WillAyd  very much for your prompt reply, apologize again for such reckless behavior, and if I need any help, I will go to the blog repository.
