### ISSUE TITLE
DOC: PDEP6 page doesn't render correctly

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#53414]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pdeps/0006-ban-upcasting.html

### Documentation problem

here, for example, it should be a bullet list:

![image](https://github.com/pandas-dev/pandas/assets/33491632/679e50c3-9099-48c1-ac57-df4289bb0dad)

### Suggested fix for documentation

fixup formatting

you may want to build the page locally first, please check https://github.com/pandas-dev/pandas/blob/main/web/README.md for how to do that, and the contributing guide https://pandas.pydata.org/docs/development/contributing.html for how to set up your environment

**Comment by flotaro** [comment]
@MarcoGorelli I would like to contribute to this issue. Can you please assign this issue to me?

**Comment by KetuPatel806** [comment]
take

**Comment by flotaro** [comment]
take

**Comment by UmbertoFasci** [comment]
take

**Comment by UmbertoFasci** [comment]
#53442 is now ready for review. Thank you for providing this issue to us!

**Comment by UmbertoFasci** [comment]
[ddf551a](https://github.com/UmbertoFasci/pandas/commit/ddf551a6fcdad4ae5205d57f975a6a8fcf9670b2) includes a full document format where bulleted lists are suggested including the provided example.
