### ISSUE TITLE
STYLE:  Add ruff check to avoid multiple `with` statements

### ISSUE THREAD

**Issue by DeaMariaLeon** [pandas-dev/pandas#53436]
Currently, it is possible to nest multiple consecutive context managers in the code.
It can be avoided by adding the following to ruff checks:

https://beta.ruff.rs/docs/rules/multiple-with-statements/ 

~~This should be added to .pre-commit-config.yaml~~

**Comment by snorfyang** [comment]
Maybe in ```pyproject.toml```?

**Comment by DeaMariaLeon** [comment]
Thank you for telling me @snorfyang. Since I'm not sure, I'm tagging @MarcoGorelli.

**Comment by MarcoGorelli** [comment]
yup, that's right, along with the other ruff codes - PRs welcome if this interests anyone! if you add the code for this check to `pyproject.toml`, and then can get `pre-commit run ruff --all-files` to pass, then you've done this correctly

**Comment by snorfyang** [comment]
take

**Comment by phofl** [comment]
Maybe a stupid question, but why would we want to disallow this globally? 2 with statements might have different scope

**Comment by DeaMariaLeon** [comment]
It would still be possible to have two or more scopes, it is just the way to write them that would change. Look at Marco's comment [here ](https://github.com/pandas-dev/pandas/pull/53419#:~:text=this%20is%20fine%2C%20though%20an%20alternative%20would%20be) if you wish. 
He avoids writing `with` twice but he is still managing the warning and the error.

**Comment by phofl** [comment]
They might refer to different  Code parts though, not all with statements might exactly have the same length.

**Comment by phofl** [comment]
I still have concerns about readability, imo we should at least escape tests from this, since this reads terrible, I highlighted one such occurrence in the pr that is linked here

**Comment by MarcoGorelli** [comment]
it's a matter of preference I guess, if you don't like it then let's leave this one out, no worries, we don't need to enable all of ruff's checks :smiley: let's close then, thanks all for the issue/discussion
