### ISSUE TITLE
Split Multiple Header into CSV file

### ISSUE THREAD

**Issue by mhd-fauzan** [pandas-dev/pandas#53433]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/76321019/split-multiple-header-into-csv-file/76322856?noredirect=1#comment134630374_76322856

### Question about pandas

I have a large csv file. Inside the csv file there are several headers. I've separated the three headers using code as below.
```
import pandas as pd
df = pd.read_csv("so_code.csv", header=None)

# find header rows
df_titles = ["Level and Distortion", "THD Ratio", "Reference Waveform"]
# create groups for each section
groupings = df.iloc[:, 0].str.contains("|".join(df_titles)).cumsum()

# split into new dataframes as dictionary
d = {}
for i, j in df.groupby(groupings):
    # define name of dictionary key as title, and set data of DF as values
    d[j.iloc[0, 0]] = pd.DataFrame(data=j.values[4:, :],
                                   # create MultiIndex from 3 header rows
                                   columns=pd.MultiIndex.from_arrays(
                                       j.iloc[1:4, :].ffill(axis=1).values))
    # suggested not to use, but you can set the variables directly (outside of the dictionary)
    globals()[j.iloc[0, 0]] = pd.DataFrame(data=j.values[4:, :],
                                           columns=pd.MultiIndex.from_arrays(
                                               j.iloc[1:4, :].ffill(axis=1).values))
```
`Level and Distortion`, `THD Ratio` and `Reference Waveform` are the types of measurements I've separated. But The type of measurement can change (increase or decrease) how to detect types of measurement without defining the type of measurement. This means that in the code above to find the header row, you must specify the names of the measurement types according to the csv that I display in the comments column. If the measurement types are different and increase, how do I find the header row without having to define the df_title variable.

here csv file
```
"Level and Distortion",,,,,,,,,,,,,,,
"Ch1 (F)",,"Ch1 (H2)",,"Ch1 (H3)",,"Ch1 (Total)",,"Ch2 (F)",,"Ch2 (H2)",,"Ch2 (H3)",,"Ch2 (Total)",
X,Y,X,Y,X,Y,X,Y,X,Y,X,Y,X,Y,X,Y
Hz,Vrms,Hz,Vrms,Hz,Vrms,Hz,Vrms,Hz,Vrms,Hz,Vrms,Hz,Vrms,Hz,Vrms
20,0.00772013164376534,20,5.60982648239952E-05,20,0.000389709733151927,20,0.011492581958802,20,0.00699792689186063,20,0.000151471712877565,20,0.000389940899485093,20,0.010080448380793
21.1179638886716,0.00747175133180212,21.1179638886716,8.83327496082501E-05,21.1179638886716,0.000426696028852445,21.1179638886716,0.0122462876404656,21.1179638886716,0.00756340531214287,21.1179638886716,0.000181697169530165,21.1179638886716,0.000443499862648762,21.1179638886716,0.0108494276048029
"THD Ratio",,,,,,,,,,,,,,,
Ch1,,Ch2,,,,,,,,,,,,,
X,Y,X,Y,,,,,,,,,,,,
Hz,%,Hz,%,,,,,,,,,,,,
20,83.009797319554,20,82.1460991930652,,,,,,,,,,,,
21.1179638886716,85.3656629417084,21.1179638886716,82.0338466400102,,,,,,,,,,,,
22.2984199401618,90.6674826441566,22.2984199401618,85.7190774666039,,,,,,,,,,,,
"Reference Waveform",,,,,,,,,,,,,,,
Ch1,,Ch2,,,,,,,,,,,,,
X,Y,X,Y,,,,,,,,,,,,
s,V,s,V,,,,,,,,,,,,
0,0,0,0,,,,,,,,,,,,
2.08333333333333E-05,6.47890208369956E-08,2.08333333333333E-05,6.47890208369956E-08,,,,,,,,,,,,
4.16666666666667E-05,5.18304721721536E-07,4.16666666666667E-05,5.18304721721536E-07,,,,,,,,,,,,
6.25E-05,1.74923655865586E-06,6.25E-05,1.74923655865586E-06,,,,,,,,,,,,
```
Can you please fix it as I need this for a project.
Thank You.

**Comment by topper-123** [comment]
I think your example code is about as good as it gets for your CSV file. Your example is not possible to do inside the `read_csv` currently.

If you want to do more advanced thing while reading data, the best approach would be to use a different file format, like sqlite, arrow or maybe hdf5 instesd of csv. Don't know if that's possible in your case though.

**Comment by rhshadrach** [comment]
Agreed with @topper-123. The issue here is the choice of data representation. It looks like you're attempting to store multiple tables in a single CSV file. I think that is bad practice. Why not use multiple files?

**Comment by jbrockmendel** [comment]
@topper-123 is correct.  Closing.

**Comment by mhd-fauzan** [comment]
@rhshadrach It is the output of the software and I have to plot it from the csv file. but first I have to take it apart.

**Comment by rhshadrach** [comment]
@mhd-fauzan Understood; I've had to deal with similar things myself. I would recommend writing a script take takes the CSV file and splits it up into multiple (one for each "proper" table that is contained in it). Then you should be able to use pd.read_csv on those.
