### ISSUE TITLE
ENH: Replace Numba decorator 

### ISSUE THREAD

**Issue by FrancescoMandru** [pandas-dev/pandas#53449]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Using pandas 2.0.1 I noticed that when I use the engine numba during apply operations, I encounter a warning:

```bash
C:\Users\XXXXXXX: NumbaDeprecationWarning: numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for more information and advice on a suitable replacement.
  warnings.warn(msg, NumbaDeprecationWarning)
```

Since the function that I'm using does not have any decorator relarted with numba but just use the numba engine in the pandas apply function, could it be something from your side to change for future versions?

### Feature Description

Based on the link of numba, just change the decorator type

### Alternative Solutions

No alternatives

**Comment by lithomas1** [comment]
Thanks for reporting this.
I'll have a look at this.
