### ISSUE TITLE
DOC: replace qgrid in Ecosystem

### ISSUE THREAD

**Issue by rootsmusic** [pandas-dev/pandas#53451]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://github.com/pandas-dev/pandas/blob/318bed9f7c16c3352178cbf68e8dddfaba32ed6d/doc/source/ecosystem.rst

### Documentation problem

qgrid has abandoned [releases](https://github.com/quantopian/qgrid/releases) and isn't compatible with the latest versions of its dependent packages.

### Suggested fix for documentation

Since this doc includes modin, qgrid should be replaced by modin-spreadsheet.  [modin-spreadsheet](https://github.com/modin-project/modin-spreadsheet) is forked from qgrid and being maintained by the modin project.

**Comment by sqali** [comment]
Hi @lithomas1 ,

I would love to work on this issue.

**Comment by lithomas1** [comment]
Sure, this looks good to me.

**Comment by sqali** [comment]
Hi @lithomas1 ,

I have updated the changes in my forked repository however it is failing the "Deprecations Bot / deprecation_update (push)" check. Can you please confirm if I can ignore this and proceed to raise the PR?

**Comment by rootsmusic** [comment]
Thanks @sqali, your merge has been accepted.  I've updated the "Location of the documentation" in my original issue, because ecosystem.rst also needs to be revised (due to #48547).
