### ISSUE TITLE
BUG: Incorrect result when `method!=None` for `MultiIndex.get_indexer`

### ISSUE THREAD

**Issue by galipremsagar** [pandas-dev/pandas#53452]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
In [1]: import pandas as pd

In [2]: idx = pd.MultiIndex.from_tuples(
   ...:             [(2, 1, 1), (1, 2, 3), (1, 2, 1), (1, 1, 10), (1, 1, 1), (2, 2, 1)]
   ...:         )

In [3]: idx.get_indexer(((1, 2, 3),))
Out[3]: array([1])

In [4]: idx.get_indexer(((1, 2, 3),), method='bfill')
Out[4]: array([0])

In [5]: idx.get_indexer(((1, 2, 3),), method='ffill')
Out[5]: array([-1])
```

### Issue Description

According to the docstring `method` should actually kick only when the element is not found(i.e., -1) in the result. So I expect results for this specific set of inputs to be `[1]` always.

### Expected Behavior

```python
In [4]: idx.get_indexer(((1, 2, 3),), method='bfill')
Out[4]: array([1])

In [5]: idx.get_indexer(((1, 2, 3),), method='ffill')
Out[5]: array([1])
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 965ceca9fd796940050d6fc817707bba1c4f9bff
python           : 3.10.11.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-76-generic
Version          : #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.2
numpy            : 1.23.5
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.7.2
pip              : 23.1.2
Cython           : 0.29.34
pytest           : 7.3.1
hypothesis       : 6.75.3
sphinx           : 5.3.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.13.2
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : 
fastparquet      : None
fsspec           : 2023.5.0
gcsfs            : None
matplotlib       : None
numba            : 0.56.4
numexpr          : None
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : 2023.5.0
scipy            : 1.10.1
snappy           : 
sqlalchemy       : 2.0.15
tables           : None
tabulate         : 0.9.0
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by galipremsagar** [comment]
cc: @mroeschke

**Comment by taytzehao** [comment]
take

**Comment by lukemanley** [comment]
Thanks for the report. The example in the OP is using a non-monotonic index which should actually raise when `method` is not None. I've opened https://github.com/pandas-dev/pandas/pull/55352 to raise in this case.
