### ISSUE TITLE
REF/API: EA.assert_equal

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#53460]
ATM in the extension tests we allow authors to override tm.assert_foo_equal at the test-class-level.   If this is something we want to be override-able (which I'm not sure ti is), it should be at the EA/EDtype level.

**Comment by andrewgsavage** [comment]
> which I'm not sure ti is

currently pint-pandas is xfailing tests where assert_almost_equal is used as it needs chaning a bit - see #48920  Should it be overriding this instead?

**Comment by jbrockmendel** [comment]
I don't think so.  ATM the tests allow you to override assert_equal, assert_series_equal, assert_frame_equal, assert_extension_array_equal, but not assert_almost_equal.

**Comment by jbrockmendel** [comment]
The pattern described in the OP has been removed from the tests.  Closing.
