### ISSUE TITLE
BUG: column selection in GroupBy NOT returning tuple when grouping by a list containing single element

### ISSUE THREAD

**Issue by GianlucaFicarelli** [pandas-dev/pandas#53500]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame({"a": [1,1,1,2,2], "b": [4,5,6,4,4], "c":[7,7,8,9,9]})

print("Each k is a tuple as expected")
for k, v in df.groupby(["a"]):
    print(type(k), k)
    print(v)

print()
print("Each k is an int, and it's not expected")
for k, v in df.groupby(["a"])[["a", "b", "c"]]:
    print(type(k), k)
    print(v)
```
Result:
```
Each k is a tuple as expected
<class 'tuple'> (1,)
   a  b  c
0  1  4  7
1  1  5  7
2  1  6  8
<class 'tuple'> (2,)
   a  b  c
3  2  4  9
4  2  4  9

Each k is an int, and it's not expected
<class 'int'> 1
   a  b  c
0  1  4  7
1  1  5  7
2  1  6  8
<class 'int'> 2
   a  b  c
3  2  4  9
4  2  4  9
```

### Issue Description

After the change in https://github.com/pandas-dev/pandas/pull/47761, when grouping by a list containing a single element, a tuple of one element is returned.

However, if a column selection is specified after groupby, a tuple is not returned (an int is returned in the previous example).

### Expected Behavior

For consistency, I would expect that a tuple is returned also in the second case.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 965ceca9fd796940050d6fc817707bba1c4f9bff
python           : 3.10.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-1160.42.2.el7.x86_64
Version          : #1 SMP Tue Aug 31 20:15:00 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.2
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.7.2
pip              : 23.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.11.0
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.7
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.1
numba            : 0.57.0
numexpr          : 2.8.4
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by tpackard1** [comment]
- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

**Installed Versions**

```
INSTALLED VERSIONS
------------------
commit           : b4e595f870a9ba7f117a6f83dd37bc13ba41e279
python           : 3.10.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.1.0.dev0+908.gb4e595f870
numpy            : 1.23.5
pytz             : 2022.6
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 22.3.1
Cython           : 0.29.35
pytest           : 7.2.0
hypothesis       : 6.61.0
sphinx           : 4.5.0
blosc            : 1.11.0
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.9.2
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : 2.9.5
jinja2           : 3.1.2
IPython          : 8.7.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.5
brotli           :
fastparquet      : 2022.12.0
fsspec           : 2021.11.0
gcsfs            : 2021.11.0
matplotlib       : 3.6.2
numba            : 0.56.4
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : 9.0.0
pyreadstat       : 1.2.0
pyxlsb           : 1.0.10
s3fs             : 2021.11.0
scipy            : 1.9.3
snappy           :
sqlalchemy       : 1.4.45
tables           : 3.7.0
tabulate         : 0.9.0
xarray           : 2022.12.0
xlrd             : 2.0.1
zstandard        : 0.19.0
tzdata           : 2022.7
qtpy             : None
pyqt5            : None
```

**Comment by topper-123** [comment]
Yeah, this looks like a bug. A PR would be welcome.

**Comment by Charlie-XIAO** [comment]
I believe this is because when doing `df.groupby(["a"])[["a", "b", "c"]]`, the keys are no longer a list but a BaseGrouper. However, #47761 is considering only a list. I can try to make a PR for this.

**Comment by Charlie-XIAO** [comment]
take
