### ISSUE TITLE
BUG: pandas is not being imported.

### ISSUE THREAD

**Issue by DuanBoomer** [pandas-dev/pandas#53516]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.
- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn as sk
```

### Issue Description
```cmd
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[C:\Users\CHIRAG](file:///C:/Users/CHIRAG)~1\AppData\Local\Temp/ipykernel_11644/2093057291.py in 
----> 1 import pandas as pd
      2 import matplotlib.pyplot as plt
      3 import numpy as np
      4 import sklearn as sk

[c:\Users\Chirag](file:///C:/Users/Chirag) Chetan\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\__init__.py in 
     20 
     21 # numpy compat
---> 22 from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
     23 
     24 try:

[c:\Users\Chirag](file:///C:/Users/Chirag) Chetan\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\compat\__init__.py in 
     14 import sys
     15 
---> 16 from pandas._typing import F
     17 from pandas.compat._constants import (
     18     IS64,

[c:\Users\Chirag](file:///C:/Users/Chirag) Chetan\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\_typing.py in 
     91 # array-like
     92 
---> 93 ArrayLike = Union["ExtensionArray", np.ndarray]
     94 AnyArrayLike = Union[ArrayLike, "Index", "Series"]
     95 TimeArrayLike = Union["DatetimeArray", "TimedeltaArray"]

AttributeError: module 'numpy' has no attribute 'ndarray'
```
### Expected Behavior

Successful import.

### Installed Versions

<details>

Name: pandas
Version: 2.0.2
Summary: Powerful data structures for data analysis, time series, and statistics     

</details>

**Comment by DuanBoomer** [comment]
cc @myles @jd @troels @lebigot

**Comment by twoertwein** [comment]
> AttributeError: module 'numpy' has no attribute 'ndarray'

Do you have a working version of numpy installed?

**Comment by DuanBoomer** [comment]
Sure the latest one

**Comment by topper-123** [comment]
Can you do `import numpy as np; np.ndarray`?

`np.ndarray` is such an often used function that this must be the installation. Do you have a dev version of numpy installed that may be built properly?

How did you install pandas/numpy? Can you describe your installation process in a reoeatable manner, so we can try the same  process.

**Comment by DuanBoomer** [comment]
Well let me give you some background.
I recently installed anaconda on my system and it was messed up.
So i uninstalled anaconda and now the system packages were messed up.
Hence the issue.
But now I have uninstalled everything including Python and all packages, and installed anaconda.
Now anaconda works but I have removed the packages which had the problem.
So I guess problem is solved?

**Comment by topper-123** [comment]
Installation issues are very stressful and annoying, but this does not sound like a pandas problem to me TBH. It sounds like something surprising has happened with your anaconda installation, but that's outside of scope for Pandas.

**Comment by DuanBoomer** [comment]
Ya must have been the anaconda.
But it's fixed now.
> Closing the issue
