### ISSUE TITLE
Unexplainable error when trying to run the following pandas code

### ISSUE THREAD

**Issue by Rehan587** [pandas-dev/pandas#53587]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
from datetime import datetime
from datetime import date
import os
import csv
import pandas as pd
import matplotlib.pyplot as pl
df = pd.DataFrame(columns=["First_Name","Last_Name","Aadhar_No.","city","DOB","Age","DOA","DOR",'sentence_indays',"sentence_inyears","crime"])
if os.path.exists("Criminaldb.csv"):
	print("Welcome back!")

else:
	print("Kindly please restart the program after this process is completed.")
	with open("Criminaldb.csv",'w') as file:
		pass
	df.to_csv("Criminaldb.csv",mode='a')
	exit()
print('''Welcome to Criminal prison DB record app! 
What do you wish to do today?
1) Add new entry
2) Update previous record
3) Find and sort old records
4) Delete a record
5) Exit the program''')

choice = int(input())

if choice == 1:
	print("Please fill out the asked details in the suggested formats only.")
	total_entries = int(input("How many entries are to be done?(Numeric values only)"))
	for i in range(1,total_entries+1):
		print("Entry no. ",i )
		first_name=input("First name ")
		last_name=input("Last name ")
		
		city = input("Enter the city name(First letter capital)")
		cmnl_ID = input("Crimimal ID assigned ")
		DOB = input("Date of Birth(YYYYMMDD format) ")
		year,month,day= DOB[:4],DOB[4:6],DOB[6:9]
		if month[0] == '0':
			month = month[1]
		if day[0]  == '0':
			day = day[1]
		else:
			pass
		ageindays = date(int(year),int(month),int(day))
		age = date.today() - ageindays
		age = int(age.days/365)

		DOA = input("Date of admission(Same format as before)")
		if DOA == '':
			DOA = date.today()
		else:
			yr_adm, mon_adm, day_adm = DOA[:4],DOA[4:6],DOA[6:9]
			if mon_adm[0] == '0':
				mon_adm = mon_adm[1]
			if yr_adm[0] == '0':
				yr_adm = yr_adm[1]
			else:
				pass
		DOA = date(int(yr_adm),int(mon_adm),int(day_adm))
		DOR = input("Date of Release(Same format as before,leave blank for life imprisonment) ")
		if DOR == '':
			DOR = 'N/A'
		else:
			yr_rel,mon_rel,day_rel = DOR[:4],DOR[4:6],DOR[6:9]
			if mon_rel[0] == '0':
				mon_rel = mon_rel[1]

			if day_rel[0] == '0':
				day_rel = day_rel[1]
		DOR = date(int(yr_rel),int(mon_rel),int(day_rel))
		total_sentence = DOR-DOA
		sentence_indays= total_sentence.days
		sentence_inyears= round(float(total_sentence.days)/365, 1)
		crime = input("Crime done by the criminal ")
		entrylist = {'First_Name':first_name,'Last_Name':last_name,'city':city,'DOB':DOB,'Age':age,'DOA':DOA,'DOR':DOR,'sentence_indays':sentence_indays,'sentence_inyears':sentence_inyears,'crime':crime}
		df.at[str(cmnl_ID),:] = entrylist
```

### Issue Description

After providing all the necessary input, the program gives the following error:

![Screenshot_2023_0610_154443](https://github.com/pandas-dev/pandas/assets/84271835/79647e7e-06a1-445a-a366-04e071518506)

### Expected Behavior

The code was expected to insert a new row after providing choice value as 1 and giving all the required inputs.

### Installed Versions

<details>

/data/data/com.termux/files/usr/lib/python3.11/site-packages/_diNoneils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit           : 965ceca9fd796940050d6fc817707bba1c4f9bff
python           : 3.11.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.14.186-g584a03637-dirty
Version          : #1 SMP PREEMPT Tue May 16 15:17:01 CST 2023
machine          : aarch64
processor        :
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.2
numpy            : 1.24.3
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 23.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 6.1.3
blosc            : None
feather          : None
xlsxwriter       : 3.0.8
lxml.etree       : 4.9.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : None
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : 0.9.0
xarray           : None
xlrd             : 2.0.1
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by MarcoGorelli** [comment]
Thanks for the report

Please make your example reproducible

**Comment by Rehan587** [comment]
> Thanks for the report
> 
> Please make your example reproducible

I've used Termux 0.118 and I have been running it on Android 12.

The code provided previously would work just as well, but I'll simplify it so that it would be easier to work with.


```
from datetime import datetime
from datetime import date
import os
import csv
import pandas as pd
df = pd.DataFrame(columns=["First_Name","Last_Name","city","crime"])
if os.path.exists("Criminaldb.csv"):
	print("Welcome back!")

else:
	print("Kindly please restart the program after this process is completed.")
	with open("Criminaldb.csv",'w') as file:
		pass
	df.to_csv("Criminaldb.csv",mode='a')
	exit()
print('''Welcome to Criminal prison DB record app.
1) Add new entry''')

choice = int(input())

if choice == 1:
	print("Please fill out the asked details in the suggested formats only.")
	for i in range(1,5):
		print("Entry no. ",i )
		first_name=input("First name ")
		last_name=input("Last name ")
		city = input("Enter the city name(First letter capital)")
		cmnl_ID = input("Crimimal ID assigned ")

    crime = input("Crime done by the criminal ")
		entrylist = {'First_Name':first_name,'Last_Name':last_name,'city':city,'crime':crime}
		df.at[str(cmnl_ID),:] = entrylist
		
```


The expected output for this code was that the data of the dictionary "entrylist" would be filled in the dataframe df as a row.

The error that was given out was:

`pandas.errors. Invalid IndexError: You can only assign a scalar value not a <class 'dict'>`

And in case this helps, I have tried using a plain list too, and an almost identical error is obtained in that case too, i.e:

`pandas.errors. Invalid IndexError: You can only assign a scalar value not a <class 'list'>`


Please let me know if any additional info is required. I'm a bit new around here, and I apologise for any inconvenience I may cause. (Kindly Please don't go by the age of my account, I don't use it too often.)

**Comment by MarcoGorelli** [comment]
can you please read https://matthewrocklin.com/minimal-bug-reports ? 

once you've done that, please open a new issue which an example that's actually reproducible

thanks
