### ISSUE TITLE
BUG: inconsistent treatment of `numpy.Inf` between `groupby.sum()` and `groupby.apply(lambda: _grp: _grp.sum())`

### ISSUE THREAD

**Issue by jrowley8013** [pandas-dev/pandas#53606]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> import numpy as np
>>> import pandas as pd
>>> s = pd.Series([np.Inf, np.Inf, np.Inf])
>>> s.groupby([0, 1, 1]).sum()  # np.Inf treated as NaN
0   inf
1   NaN
dtype: float64

>>> s.groupby([0, 1, 1]).apply(lambda _grp: _grp.sum()) # np.Inf + np.Inf = np.Inf
0   inf
1   inf
dtype: float64
```

### Issue Description

When summing together multiple `np.Inf` values, `groupby.sum()` appears to treat `np.Inf` as `NaN` while `groupby.apply(lambda _grp: _grp.sum())` does not.

### Call Tracing

I traced the calls used in `groupby.sum()`, and verified that the flag [`maybe_use_numba`](https://github.com/pandas-dev/pandas/blob/main/pandas/core/groupby/groupby.py#LL2783C36-L2784C1) evaluated to `False` when calling the [`GroupBy.sum`](https://github.com/pandas-dev/pandas/blob/main/pandas/core/groupby/groupby.py#LL2776) method.  Instead, we delegate to the pandas cython function [`group_sum`](https://github.com/pandas-dev/pandas/blob/main/pandas/_libs/groupby.pyx#L666).

As for `groupby,apply()`, we are just [iterating](https://github.com/pandas-dev/pandas/blob/main/pandas/core/groupby/ops.py#LL881) over each of the groups and calling a reduce operation on the pandas Series.  This delegates to the equivalent of `np.nansum`, which treats infinity in a different manner.

### Expected Behavior

Using either `groupby.sum()` or `groupby.apply()` should produce the same result.  I believe that the expected output should be equal to that obtained with `groupby.apply()`, which delegates to calling `np.nansum`:

```
>>> import numpy as np
>>> import pandas as pd
>>> s = pd.Series([np.Inf, np.Inf, np.Inf])
>>> s.groupby([0, 1, 1]).sum()
0   inf
1   inf
dtype: float64
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 965ceca9fd796940050d6fc817707bba1c4f9bff
python           : 3.10.11.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.19.0-42-generic
Version          : #43~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Apr 21 16:51:08 UTC 2
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.2
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 23.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.2
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.13.2
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 12.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None
</details>

**Comment by rhshadrach** [comment]
Thanks for the report. #50367 handled the mean case, I think something similar can be done for sum.

**Comment by Charlie-XIAO** [comment]
take
