### ISSUE TITLE
QST: 我没有指定engine，在本地read_excel好用，但是在airflow中就报错。当我指定之后，就会报这个，zipfile.BadZipFile: File is not a zip file，excel文件能正常打开在本地，没有问题。

### ISSUE THREAD

**Issue by chenxuedong1996** [pandas-dev/pandas#53615]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/68478097/pandas-glob-excel-file-format-cannot-be-determined-you-must-specify-an-engi

**Comment by MarcoGorelli** [comment]
> Question about pandas
> 
> _No response_

this is too low-effort, sorry - closing then

**Comment by chenxuedong1996** [comment]
？？？？没解决啊，。。。

**Comment by MarcoGorelli** [comment]
you provided a link to a stackoverflow question which already has an accepted an answer, and didn't explain why your question is different
