### ISSUE TITLE
BUG: `DataFrameGroupBy.apply` does not take into account the value of `as_index` field

### ISSUE THREAD

**Issue by anmyachev** [pandas-dev/pandas#53649]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

df = pd.DataFrame(
    {
        "col1": [0, 1, 2, 3],
        "col2": [4, 5, np.NaN, 7],
        "col3": [np.NaN, np.NaN, 12, 10],
        "col4": [17, 13, 16, 15],
        "col5": [-4, -5, -6, -7],
    }
)

print(df.groupby(by=[1,2,1,2], as_index=False).apply(lambda df: df.sum()))
print(df.groupby(by=[1,2,1,2], as_index=True).apply(lambda df: df.sum()))
```

### Issue Description

`as_index` parameter does not affect the result of `apply`.

### Expected Behavior

```python
>>> pandas_df.groupby(by=[1,2,1,2], as_index=True).apply(lambda df: df.sum())
   col1  col2  col3  col4  col5
1   2.0   4.0  12.0  33.0 -10.0
2   4.0  12.0  10.0  28.0 -12.0

>>> pandas_df.groupby(by=[1,2,1,2], as_index=False).apply(lambda df: df.sum())   # <- expected output
   index  col1  col2  col3  col4  col5
0      1   2.0   4.0  12.0  33.0 -10.0
1      2   4.0  12.0  10.0  28.0 -12.0
```

### Installed Versions

<details>

pandas 2.0.2
-- Replace this line with the output of pd.show_versions()

</details>

**Comment by rhshadrach** [comment]
Due to #52333 the following warning is now emitted on main on the `as_index=False` line:

> FutureWarning: A grouping was used that is not in the columns of the DataFrame and so was excluded from the result. This grouping will be included in a future version of pandas. Add the grouping as a column of the DataFrame to silence this warning.

This deprecation will appear in 2.1. Once the deprecation is enforced in pandas 3.0, this will be fixed.

**Comment by anmyachev** [comment]
> Thanks for the report! Due to #52333 the following warning is now emitted on the `as_index=False` line:
> 
> > FutureWarning: A grouping was used that is not in the columns of the DataFrame and so was excluded from the result. This grouping will be included in a future version of pandas. Add the grouping as a column of the DataFrame to silence this warning.
> 
> This deprecation will appear in 2.1. Once the deprecation is enforced in pandas 3.0, this will be fixed.

@rhshadrach thanks for the answer!
