### ISSUE TITLE
ENH: pd.to_numeric should have option to support converting currency strings such as $1.23 or $1,230.45 

### ISSUE THREAD

**Issue by jj-github-jj** [pandas-dev/pandas#53653]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

dataframe table having a mix of float series and strings series where string series are actually currency numbers. the pd.pd.to_numeric does not seem to support (sorry if I got this wrong and it is actually supported somehow)

### Feature Description
```python
def convert_currency_columns(df):
    # Iterate over each column in the dataframe
    for column in df.columns:
        if df[column].dtype == 'object':  # Only process columns with object/string type
            # Check if the string begins with $  should be expanded ot other currencies as well but $ for now
            if df[column].str.startswith('$').any():
                # Remove $ and commas from the values and convert to float with precision of 2
                df[column] = df[column].str.replace('$', '').str.replace(',', '').astype(float).round(2)
    return df
```

### Alternative Solutions

Possibly the pyjanitor may have this functionality?

### Additional Context

Tables with strings representing currency such as $1.23 or $1,234,567.89 should be a pretty common use case and was surprised to see that to_numeric doesnt natively handles it

**Comment by rhshadrach** [comment]
Can you first just strip any non-numeric and non-period character?

```
df = pd.DataFrame({'column': ['$1.25', '$100,000,000.99']})
print(df['column'].str.replace('[^0-9\.]', '', regex=True).astype(float))
```

**Comment by mroeschke** [comment]
I think https://github.com/pandas-dev/pandas/issues/53653#issuecomment-1590404573 is a reasonable solution so -1 on having this directly in `to_numeric`. pandas should be agnostic toward data meaning

**Comment by jj-github-jj** [comment]
Sure i can add regex string parsing and substitution but not a pythonic solution. In my opinion common use cases should not require additional coding

**Comment by rhshadrach** [comment]
> regex string parsing and substitution [is] not a pythonic solution

Can you explain what is not pythonic about it?

Agreed with @mroeschke - currency symbols and formats does not seem like something that belongs in pandas itself.

**Comment by mroeschke** [comment]
Closing as there seems to be not a lot of support for this feature
