### ISSUE TITLE
ENH: Python 3.12 support

### ISSUE THREAD

**Issue by EwoutH** [pandas-dev/pandas#53665]
### Feature Type
- [X] Adding platform support

### Problem Description

Currently, Python 3.12 isn't fully supported in the Pandas library.

### Feature Description

The solution we'd like to see is full support for Python 3.12, including testing in Continuous Integration (CI) and the publishing of compatible wheels to PyPI.

### Alternative Solutions

Not applicable in this case, as the goal is specific to supporting a new version of Python.

### Additional Context

Python 3.12 is expected to be released as stable later this year, bringing several new features and deprecations that can impact the Pandas library, including:

- New grammar features:
  - PEP 701: Syntactic formalization of f-strings
- New typing features:
  - PEP 688: Making the buffer protocol accessible in Python
  - PEP 692: Using TypedDict for more precise **kwargs typing
  - PEP 695: Type Parameter Syntax
  - PEP 698: Override Decorator for Static Typing
- Important deprecations, removals, or restrictions:
  - PEP 623: Remove wstr from Unicode
  - PEP 632: Remove the distutils package

These changes may have implications for the usage and operation of the Pandas library, making it necessary for the library to adapt to this new version.

Pandas is one of the most used packages and a package on which many other packages depend, so early support will help speed up Python 3.12 adoption. It would be beneficial to have full Python 3.12 support in Pandas by the time Python 3.12.0 beta 1 gets released. This includes testing in CI and publishing wheels to PyPI.

**Comment by lithomas1** [comment]
Hi,
Thanks for the bug report. 
We need at least numpy/Cython support before we can start on the pandas side, so gonna mark as blocked pending #23808 (need at least numpy wheels). This means wheels will be out a little later than usual, but hopefully we can still get some in before the 3.12 final release.

Cython side should be OK as far as I can tell.

**Comment by EwoutH** [comment]
Thanks! That should be https://github.com/numpy/numpy/issues/23808, right?

**Comment by lithomas1** [comment]
Thanks, updated.

**Comment by EwoutH** [comment]
NumPy wheels are incoming: https://github.com/numpy/numpy/pull/23991

**Comment by EwoutH** [comment]
Updates:

- The stable [NumPy 1.26.0](https://github.com/numpy/numpy/releases/tag/v1.26.0) has support for Python 3.12 and includes wheels on [PyPI](https://pypi.org/project/numpy/1.26.0/#files)
- [Python 3.12.0rc3](https://www.python.org/downloads/release/python-3120rc3/), the third and final release candidate, was released last week.

Planned release for Python 3.12.0 is in exactly a week, Monday 2023-10-02. It would be awesome if Pandas would have wheels deployed by then.

**Comment by mroeschke** [comment]
Closing as 3.12 support has been released
