### ISSUE TITLE
Trying to get data with a closed cursor

### ISSUE THREAD

**Issue by walterpl** [pandas-dev/pandas#53676]
https://github.com/pandas-dev/pandas/blob/66e3805b8cabe977f40c05259cc3fcf7ead5687d/pandas/io/sql.py#LL2083C6-L2083C6

Hi team, ím trying to read a bilion row table, to make fisible I'm trying to use chunksize with the read_sql function, include the necessary info do the DF and send to the destination table. The connection parameter I'm using is jaydebeapi connection, since I could make those DB2 connect with Sqlalchemy.

It loops on every chunk, process all the data but raise this Exception :

```
File /opt/conda/envs/Python-3.9-Premium/lib/python3.9/site-packages/pandas/io/sql.py:2083, in SQLiteDatabase._query_iterator(cursor, chunksize, columns, index_col, coerce_float, parse_dates, dtype)
   2081 has_read_data = False
   2082 while True:
-> 2083     data = cursor.fetchmany(chunksize)
   2084     if type(data) == tuple:
   2085         data = list(data)

File /opt/conda/envs/Python-3.9-Premium/lib/python3.9/site-packages/jaydebeapi/__init__.py:575, in Cursor.fetchmany(self, size)
    573     size = self.arraysize
    574 # TODO: handle SQLException if not supported by db
--> 575 self._rs.setFetchSize(size)
    576 rows = []
    577 row = None

com.ibm.db2.jcc.am.SqlException: com.ibm.db2.jcc.am.SqlException: [jcc][t4][10120][10898][4.31.10] Invalid operation: result set is closed. ERRORCODE=-4470, SQLSTATE=null
```

I looki at version 1.5.x and this block of code remain the same. 
One solution that I use here, is to check if the conn parameter is a jaydebeapi.Connection if so, check if the result is empty, if so break the while loop. Jaydebeapi connection send a empy tuple when there is nothing left to fetch, after that it raise an Exception

**Comment by mroeschke** [comment]
Thanks for the report but it looks like error is happening in the jaydebeapi package based on how it implements `fetchmany`. Since it's not clear this is a pandas issue going to close
