### ISSUE TITLE
API: rename PandasArray -> NumpyExtensionArray

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#53694]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
NA
```

### Issue Description

More neutral naming scheme analogous to ArrowExtensionArray.

### Expected Behavior

NA

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by SanjithChockan** [comment]
take

**Comment by jbrockmendel** [comment]
@TomAugspurger i think PandasArray was your idea initially.  any objection to renaming?

**Comment by TomAugspurger** [comment]
Works for me.
