### ISSUE TITLE
DEPR: deprecate DataFrame.last and Series.last

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#53692]
just opening this so it's not forgotten - xref https://github.com/pandas-dev/pandas/pull/53419

**Comment by rmhowe425** [comment]
take

**Comment by rmhowe425** [comment]
@MarcoGorelli I'll take this one unless you're already working on it. I see that you're involved with the PR that you referenced

**Comment by MarcoGorelli** [comment]
Go ahead thanks!
