### ISSUE TITLE
ENH: Replace s3fs dependency with awswrangler

### ISSUE THREAD

**Issue by DRKolev-code** [pandas-dev/pandas#53712]
### Feature Type

- [X] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [X] Removing existing functionality in pandas

### Problem Description

Currently, working with Amazon S3 requires installation of the s3fs library. This is straightforward and not necessarily an issue until you need to work with newer AWS services.

The issue:
1. Pandas relies on s3fs.
2. s3fs relines of aiobotocore. This library is a hack on botocore and relines on specific versions of botocore.
3. Installing the newest version of botocore, either because you want to, or because you want the newest boto3, or because you want the newest Sagemaker breaks your package management system because aiobotocore cannot coexist with newer versions of botocore.

Solution:
AWS Wrangler which was recently renamed to AWS SDK for pandas (awswrangler). This library has no issues with botocore versions and has no restrictions on what library a user should or should not install. 

### Feature Description

When a user wants to read and write from and to AWS the specific Pandas functions could internally use awswrangler to do the job.

### Alternative Solutions

I think awswrangler uses a custom implementation of s3fs. It could possibly be used to establish the connections rather than directly use the save and load functions of awswrangler.

**Comment by twoertwein** [comment]
Pandas uses `fsspec` which takes care of all the network protocols (except http/https - handled by `urllib`).

It might be good to open this issue at fsspec to ask for different aws-backends. When fsspec supports that, it should automatically work with pandas.

**Comment by DRKolev-code** [comment]
Pandas is the one that raises the "you do not have s3fs installed please install it" and s3fs is part of fsspec. If I understand you correctly the change should come from s3fs itself?

I think that could be a solution but I would suggest that a better approach is to simply not use s3fs as they are the ones to introduce this incompatibility. I think using the official AWS library is a much safer and future proof way of dealing with AWS.

awswrangler has direct connections to S3: https://aws-sdk-pandas.readthedocs.io/en/stable/

```
df = pd.DataFrame({"id": [1, 2], "value": ["foo", "boo"]})

wr.s3.to_parquet(
    df=df,
    path="s3://bucket/dataset/",
    dataset=True,
    database="my_db",
    table="my_table"
)

df = wr.s3.read_parquet("s3://bucket/dataset/", dataset=True)

```

**Comment by twoertwein** [comment]
I don't see any s3fs imports in pandas, except for the test: https://github.com/search?q=repo%3Apandas-dev%2Fpandas+s3fs&type=code&p=1

If there is really no s3fs code in pandas, we can probably remove s3fs as an optional dependency (any s3 calls will then fail inside fsspec).

**Comment by DRKolev-code** [comment]
Pushing the issue to s3fs is fine but it does not solve the problem. This is a long chain with the end user unwittingly stuck with a problematic implementation.

botocore <- aiobotocore (the issue) <- s3fs (<0.4) <- pandas <- everyone else who uses pandas

This affects only the users who use AWS and who need newer packages for botocore. I understand that the group that use pandas and AWS is smaller than the group who use pandas in general. The subgroup that needs newer botocore is even smaller but that will keep increasing as aiobotocore will continue to fall further behind.

Of course, there is a solution not requiring pandas involvement. Affected parties can to simply ignore pandas' save functionality and use awswrangler and wait until s3fs either switches away from aiobotocore or aiobotocore fixes itself. In this case maybe pandas could display a message explaining that either s3fs needs to be installed or to use awswrangler instead.

Having all that said, I think it is time for pandas to move away from s3fs as there is an official AWS library to deal with reading/writing to AWS.

**Comment by mroeschke** [comment]
Yeah I would be -1 switching to awswangler also. I think it would make sense to suggest this change in the s3fs repo so that pandas and other libraries could benefit from removing aiobotocore complexities.

Since this is an upstream issue with not too much support, closing

**Comment by twoertwein** [comment]
s3fs is currently an optional dependency of pandas but I don't see any s3fs-specific code in pandas (except the tests). Would it make sense to remove s3fs as an optional dependency? s3fs seems more like an "implementation detail" of fsspec. One reason to keep s3fs as an optional dependency: it is mentioned in the docs quite a bit.

**Comment by mroeschke** [comment]
But s3fs is the way fsspec gains S3 functionality so that make it an implicit optional dependency of pandas IIUC. If a user installs fsspec by itself they won't be able to access any 3rd party remote file systems out of the box
