### ISSUE TITLE
DOC: operator wrapper names do not match math operators

### ISSUE THREAD

**Issue by mk0417** [pandas-dev/pandas#53724]
### Pandas version checks

- [x] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://github.com/pandas-dev/pandas/blob/v2.0.2/pandas/core/ops/docstrings.py

### Documentation problem

Among flexible wrappers (`add`, `sub`, `mul`, `div`, `mod`, `pow`) to
arithmetic operators: `+`, `-`, `*`, `/`, `//`, `%`, `**`.

There are 6 wrapper names, but there are 7 operators

### Suggested fix for documentation

It is better to add `floordiv` after `div` so that the names can match the operators in order
```Among flexible wrappers (`add`, `sub`, `mul`, `div`, `floordiv`,`mod`, `pow`) to
arithmetic operators: `+`, `-`, `*`, `/`, `//`, `%`, `**`.```

**Comment by rsm-23** [comment]
Thoughts @MarcoGorelli ? If the suggestion is accepted, I can take it up.

**Comment by MarcoGorelli** [comment]
not sure I understand the feature request, but feel free to open a PR if you understand and think it would add value

**Comment by rsm-23** [comment]
take

**Comment by rhshadrach** [comment]
@mk0417 - can you give this issue a more informative title? Currently it is `DOC:`.

**Comment by rsm-23** [comment]
I think my PR fixes what OP is requesting. Also @mk0417 can you please update the title of this issue?
