### ISSUE TITLE
ENH: pct_change in a group by return groups

### ISSUE THREAD

**Issue by marcdelabarrera** [pandas-dev/pandas#53739]
### Feature Type

- [X] Adding new functionality to pandas

- [x] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I have a dataset with `date,` `industry,` `wage` and `price.` I want to compute the percentage increase in wages and prices by industry. I can do something like:

`data.set_index('date').groupby('industry')[['wage','price']].pct_change()`

But this will return me a pandas `dataframe` with `date` as an index and `wage` and `price` as columns, losing the `industry` column. 

### Feature Description

It would be nice to add an option to pct_change(), when applied to a groupby object, to also return the groups, maybe as an index as the `agg `function does. 

### Alternative Solutions

My current approach is:
`pd.concat([data.set_index('date')[['industry']],
data.set_index('date').groupby(['industry'])[['wage','price']].pct_change()],axis=1)`

Not a big deal but seems a common operation. Having a grouped dataframe and wanting to compute percentage changes for several columns.

**Comment by rhshadrach** [comment]
Does

```
result = data.set_index('date').groupby('industry')[['wage','price']].pct_change()
result['industry'] = data['industry']
```

work? Expanding the applicability of `as_index=False/True` to transformers is part of #49543

**Comment by jesse-sealand** [comment]
@marcdelabarrera does @rhshadrach solution work for you?

**Comment by marcdelabarrera** [comment]
Yes, it would. A two-line option but it works. Thx!

**Comment by rhshadrach** [comment]
Using `.assign(industry=data['industry'])` would make it one line if you so prefer! Thanks for the response, closing.
