### ISSUE TITLE
BUG: weekday incorrect for dates before 0000-03-01

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#53738]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
In [1]: pd.Timestamp('0000-03-01').weekday()
Out[1]: 2

In [2]: pd.Timestamp('0000-02-29').weekday()
Out[2]: 2
```

### Issue Description

pandas thinks that before Wednesday there was another Wednesday - my guess is that this was written by a French pupil trying to get an extra half-day off? 😄 

### Expected Behavior

I'd expect
```python
In [1]: pd.Timestamp('0000-03-01').weekday()
Out[1]: 2

In [2]: pd.Timestamp('0000-02-29').weekday()
Out[2]: 1
```

At least, that's what Rust's chrono gives:
```Rust
use chrono::{NaiveDate};

fn main() {
    let date_str = "0000-02-29";
    let date = NaiveDate::parse_from_str(date_str, "%Y-%m-%d").unwrap();
    let weekday_abbrev = date.format("%a").to_string();
    println!("date: {:?}", date);
    println!("Weekday (abbreviated): {}", weekday_abbrev);
}
```
outputs
```Rust
date: 0000-02-29
Weekday (abbreviated): Tue
```

Likewise, https://calculat.io/en/date/what-day-of-the-week-is/29-february-0000 gives it as Tuesday

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 965ceca9fd796940050d6fc817707bba1c4f9bff
python           : 3.10.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 2.0.2
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.6.1
pip              : 23.0.1
Cython           : None
pytest           : 7.3.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.13.2
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 12.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None
None

</details>

**Comment by MarcoGorelli** [comment]
From https://en.wikipedia.org/wiki/Determination_of_the_day_of_the_week#Sakamoto.27s_methods, it looks like the current method is only accurate if the year is greater than 1762

**Comment by mcgeestocks** [comment]
take

**Comment by jorisvandenbossche** [comment]
Just as confirmation with another tool, also Arrow (date.h) gives the same result as chrono:

```
In [69]: arr = pa.array(["0000-02-29", "0000-03-01"]).cast(pa.timestamp("us"))

In [70]: pc.day_of_week(arr)
Out[70]: 
<pyarrow.lib.Int64Array object at 0x7f01133a4b20>
[
  1,
  2
]
```
