### ISSUE TITLE
[DEPR]: Remove literal string/bytes input from `read_excel`, `read_html`, and `read_xml`

### ISSUE THREAD

**Issue by wence-** [pandas-dev/pandas#53767]
Following on from #52271 and #53409 (and to close out #5924), here is the state of play for IO routines in terms of what they accept as input 

- `read_clipboard`: doesn't take input argument
- `read_csv`: pathlike, BinaryIO, StringIO
- `read_excel`: pathlike, BinaryIO, engine-specific objects, literal bytes
- `read_feather`: pathlike, BinaryIO
- `read_fwf`: pathlike, BinaryIO, StringIO
- `read_gbq`: SQL query (str)
- `read_hdf`: pathlike, pytables.HDFStore
- `read_html`: pathlike, BinaryIO, StringIO, literal bytes, literal string
- `read_json`: pathlike, BinaryIO, StringIO, literal string (deprecated in #53409)
- `read_orc`: pathlike, BinaryIO
- `read_parquet`: pathlike, BinaryIO
- `read_pickle`: pathlike, BinaryIO
- `read_sas`: pathlike, BinaryIO
- `read_spss`: pathlike (pyreadstat doesn't allow reading from a buffer)
- `read_sql_query`: SQL query (str)
- `read_sql_table`: name of database table (str)
- `read_stata`: pathlike, BinaryIO
- `read_table`: pathlike, BinaryIO, StringIO
- `read_xml`: pathlike, BinaryIO, StringIO, literal bytes, literal string

So some, but not all, of the textual formats support reading literally, some support reading bytes as well as strings, and some of the binary formats support reading literal bytes.

Having deprecated literal input to `read_json` I suggest it makes sense to therefore also do so for:

- `read_excel`
- `read_html`
- `read_xml`

**Comment by rmhowe425** [comment]
take

**Comment by rmhowe425** [comment]
@wence- Does this issue still need to be discussed / triaged by repo maintainers?

**Comment by rmhowe425** [comment]
take

**Comment by jbrockmendel** [comment]
@mroeschke with this completed can we close #5924?
