### ISSUE TITLE
DOC: to_orc example doesn't render

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#53770]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.to_orc.html

### Documentation problem

The example doesn't render, see the example of the page

### Suggested fix for documentation

just need to add an empty line (with no whitespace!)

```diff
diff --git a/pandas/core/frame.py b/pandas/core/frame.py
index b411cfc4a4..352d353ef4 100644
--- a/pandas/core/frame.py
+++ b/pandas/core/frame.py
@@ -2981,6 +2981,7 @@ class DataFrame(NDFrame, OpsMixin):
         1     2     3
 
         If you want to get a buffer to the orc content you can write it to io.BytesIO
+
         >>> import io
         >>> b = io.BytesIO(df.to_orc())  # doctest: +SKIP
         >>> b.seek(0)  # doctest: +SKIP
```

**Comment by CYBWEBALI** [comment]
I can fix this Can you assign it to me?
