### ISSUE TITLE
CLN: use lib.no_default instead of lib.NoDefault in reshape.pivot

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#53826]
In core.reshape.pivot we have a couple places where a default kwarg is `lib.NoDefault` where the idiomatic usage would be `lib.no_default`.  I assumed this was just a typo, but when I tried changing it, some tests broke.  Need to track down what's going on there.

**Comment by Charlie-XIAO** [comment]
@jbrockmendel Seems that in `pandas/core/frame.py` there are also such typos, maybe this is the reason.
