### ISSUE TITLE
BUG: Series.str.extractall with arrow string returns object dtype

### ISSUE THREAD

**Issue by wirable23** [pandas-dev/pandas#53846]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> k = pd.Series(["abc", "ab"], dtype=pd.ArrowDtype(pa.string()))
>>> k.str.extractall("(ab)").dtypes
0    object
dtype: object
>>>
```

### Issue Description

Calling extractall on an arrow string series changes the type from "string[pyarrow]" to object.

### Expected Behavior

I would expect a column returned to be typed "string[pyarrow]", not object, or a not implemented error. For reference. Series.str.extract with the arrow string series raises a notimplemented:

`
>>> k.str.extract("(ab)")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ca2_ps_311_0515\Lib\site-packages\pandas\core\strings\accessor.py", line 129, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ca2_ps_311_0515\Lib\site-packages\pandas\core\strings\accessor.py", line 2611, in extract
    result_list = self._data.array._str_extract(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ca2_ps_311_0515\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 1959, in _str_extract
    raise NotImplementedError(
NotImplementedError: str.extract not supported with pd.ArrowDtype(pa.string()).
>>>

`

### Installed Versions

<details>

>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : 965ceca9fd796940050d6fc817707bba1c4f9bff
python           : 3.11.2.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 2.0.2
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.7.2
pip              : 23.1.2
Cython           : None
pytest           : 7.0.1
hypothesis       : None
sphinx           : 4.2.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.13.2
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 12.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None
>>>
</details>

**Comment by lithomas1** [comment]
Thanks for the bug report. 

I don't think this is implemented yet for the pyarrow string dtype.

**Comment by ABizzinotto** [comment]
@lithomas1 I'm happy to take this one. Just wanted to confirm the expected behaviour to close this particular issue. Should it just raise a NotImplementedError for now and is it ok to implement this for the pyarrow string dtype?

**Comment by ABizzinotto** [comment]
take

**Comment by lithomas1** [comment]
> @lithomas1 I'm happy to take this one. Just wanted to confirm the expected behaviour to close this particular issue. Should it just raise a NotImplementedError for now and is it ok to implement this for the pyarrow string dtype?

Yes, the expected result should be to have this be implemented, and return the same result as the numpy object dtype in a pyarrow string dtype.
