### ISSUE TITLE
DOC: test results link in asv benchmarks doc is broken

### ISSUE THREAD

**Issue by Charlie-XIAO** [pandas-dev/pandas#53851]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/development/contributing_codebase.html#running-the-performance-test-suite

### Documentation problem

> Performance matters and it is worth considering whether your code has introduced performance regressions. pandas is in the process of migrating to [asv benchmarks](https://github.com/airspeed-velocity/asv) to enable easy monitoring of the performance of critical pandas operations. These benchmarks are all found in the pandas/asv_bench directory, and the test results can be found [here](https://pandas.pydata.org/speed/pandas/).

The link in *the test results can be found [here](https://pandas.pydata.org/speed/pandas/)* leads to `404 not found`.

### Suggested fix for documentation

Use a valid link.

**Comment by lithomas1** [comment]
This is probably the correct link.
https://asv-runner.github.io/asv-collection/pandas/#/
The runner might have gone down though, everything I can see is from last month.

cc @rhshadrach

**Comment by rhshadrach** [comment]
Thanks @lithomas1 - agreed, looks like the machine restarted. I'll hopefully be able to get it back up in the next day or two.

**Comment by Charlie-XIAO** [comment]
> This is probably the correct link.
> https://asv-runner.github.io/asv-collection/pandas/#/

Then I'll make a PR using this link.

**Comment by rhshadrach** [comment]
Then benchmark machine is now back online.
