### ISSUE TITLE
BUG: Parameter `col_space` of `to_html` method not working with multi-level columns 

### ISSUE THREAD

**Issue by LucasHattoriCosta** [pandas-dev/pandas#53885]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
df = pd.DataFrame([[1,2],[3,4]])
df.columns = pd.MultiIndex.from_tuples([(1,1),(2,1)])
df.to_html(col_space=100)
```

### Issue Description

It only sets the first column with 100px:
```<table border="1" class="dataframe">
  <thead>
    <tr>
      <th style="min-width: 100px;"></th>
      <th>1</th>
      <th>2</th>
    </tr>
    <tr>
      <th style="min-width: 100px;"></th>
      <th>1</th>
      <th>1</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1</th>
      <td>3</td>
      <td>4</td>
    </tr>
  </tbody>
</table>
```

### Expected Behavior

It should set all columns with 100px: 
```
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th style="min-width: 100px;"></th>
      <th style="min-width: 100px;">1</th>
      <th style="min-width: 100px;">2</th>
    </tr>
    <tr>
      <th style="min-width: 100px;"></th>
      <th style="min-width: 100px;">1</th>
      <th style="min-width: 100px;">1</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1</th>
      <td>3</td>
      <td>4</td>
    </tr>
  </tbody>
</table>
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763
python           : 3.9.12.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 22.5.0
Version          : Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.5.0
numpy            : 1.23.0
pytz             : 2022.4
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : None
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.10.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           :
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by attack68** [comment]
`DataFrame.to_html()` is quite old and has not been extended in a number of years. It contains some deprecated HTML features as well as producing inline-styles which some modern CSPs (content security policies) do not allow.
I would recommend using `df.style.to_html()` where you can use CSS to control the size of any cell or group of cells.
One way of doing this would be to use:

`df.style.set_table_styles([{'selector': 'thead th', 'props': 'min-width: 100px;'}]).to_html()`

**Comment by dannyi96** [comment]
As per below code, The issues seems specific to the case when column's are MultiIndex.
https://github.com/pandas-dev/pandas/blob/1e90f9e3c5371bf65347bc1ea5e9b3cef9dfa189/pandas/io/formats/html.py#L71-L74

Can try giving this a shot

**Comment by dannyi96** [comment]
take
