### ISSUE TITLE
BUG: df.plot.scatter may cause UserWarning: No data for colormapping provided via 'c'. Parameters 'cmap' will be ignored

### ISSUE THREAD

**Issue by GianlucaFicarelli** [pandas-dev/pandas#53908]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import matplotlib.pyplot as plt

df = pd.DataFrame({"x": [10, 11, 12, 13], "y": [20, 21, 22, 23]})
fig, ax = plt.subplots(nrows=1, ncols=1)
df.plot.scatter(x="x", y="y", c="b", ax=ax)
```
Printed warning:
```
venv/lib/python3.11/site-packages/pandas/plotting/_matplotlib/core.py:1256: UserWarning: No data for colormapping provided via 'c'. Parameters 'cmap' will be ignored
  scatter = ax.scatter(
```

### Issue Description

If the color `b` (blue) is passed as parameter `c` to `df.plot.scatter`, a UserWarning is printed.

The UserWarning isn't printed when passing `c='blue'` or `c=['b']`.

Looking at the code, this is caused by https://github.com/pandas-dev/pandas/blob/6b7225a874b03e324948f5942d6a0f6c3c6134ae/pandas/plotting/_matplotlib/core.py#L1237-L1240
that is causing cmap to be set, because `is_integer_dtype('b')` is True, since `pandas_dtype('b')` is int8.

### Expected Behavior

The UserWarning shouldn't be generated when `c='b'`, since `'b'` is a valid color.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 965ceca9fd796940050d6fc817707bba1c4f9bff
python           : 3.11.1.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.6.0
Version          : Darwin Kernel Version 21.6.0: Mon Apr 24 21:10:53 PDT 2023; root:xnu-8020.240.18.701.5~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : None
LOCALE           : en_US.UTF-8

pandas           : 2.0.2
numpy            : 1.25.0
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 68.0.0
pip              : 23.1.2
Cython           : 0.29.35
pytest           : 7.3.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.14.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : 2023.4.0
fsspec           : 2023.6.0
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : 2.8.4
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 12.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : None
tables           : 3.8.0
tabulate         : None
xarray           : 2023.5.0
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by jlrodriguezp** [comment]
The UserWarning isn't printed when passing c=['cool'] or c=['b'].
