### ISSUE TITLE
BUG: TypeError: cannot safely cast non-equivalent object to uint32

### ISSUE THREAD

**Issue by ppt000** [pandas-dev/pandas#53928]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import numpy as np
import pandas as pd
dfr = pd.DataFrame({'col1': np.random.randint(0,100, size=100)})
dfr.dtypes
> col1    int32
> dtype: object
(dfr / 10).dtypes
> col1    float64
> dtype: object
(dfr / 10).astype(np.uint32).dtypes
> col1    uint32
> dtype: object
(dfr / 10).astype('UInt32').dtypes
> ... trace ...
> TypeError: cannot safely cast non-equivalent float64 to uint32
```

### Issue Description

Using the method astype with the pandas integer dtypes ('UInt32', 'UInt64', ...) allowing the null element (pandas.NA) fails whereas casting to the usual numpy dtypes ('uint32', 'uint64',...) works.

### Expected Behavior

Expected behaviour is to return the data with the 'UInt32' dtype so that future NA values do not change the dtype of the column.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 0f437949513225922d851e9581723d82120684a6
python           : 3.11.2.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : AMD64 Family 25 Model 68 Stepping 1, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252

pandas           : 2.0.3
numpy            : 1.25.0
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 67.6.0
pip              : 23.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.9
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.13.2
pandas_datareader: None
bs4              : 4.12.0
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by AlejandroFernandezLuces** [comment]
This is expected behaviour. The custom types of pandas don't allow casting to types that remove information. In this case, you are trying to cast a `float` type to custom `uint` pandas, so it won't be allowed.

**Comment by lithomas1** [comment]
Agreed, the nullable integer dtypes have enforced safe casting ever since they were implemented.
