### ISSUE TITLE
BUG: Categorical order lost after call to `remove_categories`

### ISSUE THREAD

**Issue by jinlow** [pandas-dev/pandas#53935]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

c = pd.Series(
    [
        "a",
        "b",
        "c",
        "d",
        "d",
        "a",
    ],
    dtype="category",
).cat.reorder_categories(["d", "c", "b", "a"], ordered=True)
print(c.cat.categories) # Index(['d', 'c', 'b', 'a'], dtype='object')
c = c.cat.remove_categories("c")
print(c.cat.categories) # Index(['a', 'b', 'd'], dtype='object')
```

### Issue Description

When `remove_categories` is called on an ordered categorical series, the returned series loses it's order.

### Expected Behavior

In the example, I would expect the new order to be to be `['d', 'b', 'a']` after "c" is removed, rather than `['a', 'b', 'd']`.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 0f437949513225922d851e9581723d82120684a6
python           : 3.10.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 2.0.3
numpy            : 1.25.0
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 68.0.0
pip              : 22.0.4
Cython           : None
pytest           : 7.4.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.1.2
lxml.etree       : 4.9.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.14.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : 12.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.11.0
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : 0.9.0
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None
</details>

**Comment by phofl** [comment]
Thanks! This looks odd, investigations welcome

**Comment by paulreece** [comment]
take

**Comment by paulreece** [comment]
I have found the root of this issue and will submit a PR later this evening.

**Comment by paulreece** [comment]
Here is a link to my PR with the fix, and detailing the logic behind it. https://github.com/pandas-dev/pandas/pull/54027
