### ISSUE TITLE
BUILD: can't create mamba isolated environment with latest environment.yml

### ISSUE THREAD

**Issue by liang3zy22** [pandas-dev/pandas#53978]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

macOS-13.4.1-arm64-arm-64bit

### Installation Method

Built from source

### pandas Version

latest main branch

### Python Version

3.10.6

### Installation Logs

<details>

(base) y@Laptop pandas % mamba env create --file environment.yml                
pkgs/main/noarch                                              No change
pkgs/main/osx-arm64                                           No change
pkgs/r/osx-arm64                                              No change
pkgs/r/noarch                                                 No change
conda-forge/osx-arm64                                6.8MB @   2.1MB/s  3.5s
conda-forge/noarch                                  13.2MB @   3.3MB/s  4.2s

Looking for: ['python=3.10', 'pip', 'versioneer', 'cython=0.29.33', 'meson=1.0.1', 'meson-python=0.13.1', "pytest[version='>=7.3.2']", 'pytest-cov', "pytest-xdist[version='>=2.2.0']", "pytest-asyncio[version='>=0.17.0']", "pytest-localserver[version='>=0.7.1']", 'coverage', 'python-dateutil', 'numpy', 'pytz', "beautifulsoup4[version='>=4.11.1']", 'blosc', "brotlipy[version='>=0.7.0']", "bottleneck[version='>=1.3.4']", "fastparquet[version='>=0.8.1']", "fsspec[version='>=2022.05.0']", "html5lib[version='>=1.1']", "hypothesis[version='>=6.46.1']", "gcsfs[version='>=2022.05.0']", 'ipython', "jinja2[version='>=3.1.2']", "lxml[version='>=4.8.0']", "matplotlib[version='>=3.6.1']", "numba[version='>=0.55.2']", "numexpr[version='>=2.8.0']", "openpyxl[version='>=3.0.10']", "odfpy[version='>=1.4.1']", 'py', "psycopg2[version='>=2.9.3']", "pyarrow[version='>=7.0.0']", "pymysql[version='>=1.0.2']", "pyreadstat[version='>=1.1.5']", "pytables[version='>=3.7.0']", "python-snappy[version='>=0.6.1']", "pyxlsb[version='>=1.0.9']", "s3fs[version='>=2022.05.0']", "scipy[version='>=1.8.1']", "sqlalchemy[version='>=1.4.36']", "tabulate[version='>=0.8.10']", "xarray[version='>=2022.03.0']", "xlrd[version='>=2.0.1']", "xlsxwriter[version='>=3.0.3']", "zstandard[version='>=0.17.0']", 'dask-core', 'seaborn-base', 'moto', 'flask', "asv[version='>=0.5.1']", 'c-compiler', 'cxx-compiler', 'black=23.3.0', 'cpplint', 'flake8=6.0.0', "isort[version='>=5.2.1']", 'mypy=1.2', "pre-commit[version='>=2.15.0']", 'pyupgrade', 'ruff=0.0.215', 'gitpython', 'gitdb', 'natsort', 'numpydoc', 'pydata-sphinx-theme', 'pytest-cython', 'sphinx', 'sphinx-design', 'sphinx-copybutton', 'types-python-dateutil', 'types-pymysql', 'types-pytz', 'types-pyyaml', 'types-setuptools', "nbconvert[version='>=6.4.5']", 'nbsphinx', 'pandoc', 'ipywidgets', 'nbformat', "notebook[version='>=6.0.3']", 'ipykernel', 'jinja2', 'markdown', 'feedparser', 'pyyaml', 'requests', 'pygments']

Encountered problems while solving:
  - nothing provides aiosmtpd needed by pytest-localserver-0.7.1-pyhd8ed1ab_0

</details>

**Comment by phofl** [comment]
see #53828
