### ISSUE TITLE
BUG: pd.DataFrame returns all NaNs when given a DataFrame and column names

### ISSUE THREAD

**Issue by DavidSiretMarques** [pandas-dev/pandas#54003]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np
n = 5
m = 0
M = 100

np.random.seed(1)
data_r = pd.DataFrame({'col1': np.random.random_integers(m,M,n),'col2': np.random.random_integers(m,M,n),'col3': np.random.random_integers(m,M,n)})

print(f"{pd.DataFrame(data_r, columns= ['c1','c2','c3'])}")
```

### Issue Description

If we have a DataFrame `df` and want to create another dataframe with a different set of column names, the obvious choice would be to do `pd.DataFrame(df, columns=new_cols)`.

This doesn't work, as shown in the example, it returns a bunch of NaNs.

### Expected Behavior

When using `pd.DataFrame` and giving it a df a new set of column names, it should return the new df with the column names changed and the values as is.

### Installed Versions

<details>
INSTALLED VERSIONS

------------------

commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.9.16.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19045
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : es_ES.cp1252

pandas           : 1.5.3
numpy            : 1.25.0
pytz             : 2022.7
dateutil         : 2.8.2
setuptools       : 67.8.0
pip              : 23.1.2
Cython           : None
pytest           : 7.3.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.12.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : 1.3.5
brotli           :
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : 0.19.0
tzdata           : None

</details>

**Comment by DavidSiretMarques** [comment]
Should be easy to fix, just doing df.values in the call seems to solve the problem, see the code

```python
import pandas as pd
import numpy as np

n = 5
m = 0
M = 100

np.random.seed(1)
data_r = pd.DataFrame({'col1': np.random.random_integers(m,M,n),'col2': np.random.random_integers(m,M,n),'col3': np.random.random_integers(m,M,n)})

print(f"{pd.DataFrame(data_r, columns= ['c1','c2','c3'])}") #Returns all NaNs
print(f"{pd.DataFrame(data_r.values, columns= ['c1','c2','c3'])}") #Returns things as should be
```

**Comment by rhshadrach** [comment]
This is documented here under the `columns` arugment:

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

> If data contains column labels, will perform column selection instead.

I suppose we could instead raise if the requested columns are not found. Not sure if returning NaN was a deliberate choice. 

cc @mroeschke @jbrockmendel @phofl

**Comment by phofl** [comment]
The question I would ask why you  would specify columns if you already have a DataFrame, doing nothing here would ignore the columns keyword

**Comment by DavidSiretMarques** [comment]
I have a dataframe created from a tensor from a ML model, and I have to rescale it (because the ML model gives it back scaled) so, for iterating throught the tensor I decided to create a dataframe, as the function I had was built to deal with dfs and I find it easier to deal with dfs than tensors, Then I want to change the column names to print it in a readable way, so it's not just 0,1,2,3,4,5 for the column names

**Comment by phofl** [comment]
df.columns = your columns

**Comment by DavidSiretMarques** [comment]
yeah, but I wanted a copy of the df to keep things separated, hence the thought of doing that

**Comment by rhshadrach** [comment]
DataFrame.rename will make a copy.

**Comment by phofl** [comment]
Just a FYI: Doing ``pd.DataFrame(df)`` doest __not__ copy ``df``. ``df.rename`` creates a deep copy of your data. Not sure if performance is relevant, but that's an important distinction without copy on write

**Comment by DavidSiretMarques** [comment]
Yeah, I deduced that when I saw the behavior of `pd.DataFrame(df, columns= column_names)`, but thanks for the info anyway
