### ISSUE TITLE
BUG: MultiIndex levels not updated on DataFrame from column subset

### ISSUE THREAD

**Issue by r4f** [pandas-dev/pandas#54007]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df_abc = pd.DataFrame({
  ("a", "a1"): [1],
  ("a", "a2"): [2],
  ("b", "b1"): [3],
  ("c", "c1"): [4],
})
df_ab = df_abc[["a", "b"]]

assert len(df_ab.columns.levels[0]) == 2 and all(df_ab.columns.levels[0] == ['a', 'b'])
assert len(df_ab.columns.levels[1]) == 3 and all(df_ab.columns.levels[1] == ['a1', 'a2', 'b1'])
```

### Issue Description

Creating a dataframe by subsetting columns of original dataframe yields incorrect `columns.levels`,
with the content of the original dataframe's MultiIndex.

In the example above `df_ab.columns.levels` wrongly is `FrozenList([['a', 'b', 'c'], ['a1', 'a2', 'b1', 'c1']])`.

Curiously the frozen sets are not identical objects, as
`df_abc.columns.levels is df_ab.columns.levels` does **not** hold true.

The example does not seem to depend on any particularity of the chosen MultiIndex, but is experienced across many examples.

### Expected Behavior

`df_ab.columns.levels` should be `FrozenList([['a', 'b'], ['a1', 'a2', 'b1']])`.

[Edit:] My current workaround is to use
`df_ab.columns.get_level_values(0).unique()` instead of
`df_ab.columns.levels[0])`, to produce the expected result.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 6cb37b6e050c374151a23e790a46ad8b822a0564
python           : 3.10.11.final.0
python-bits      : 64
OS               : Linux
OS-release       : 6.2.6-76060206-generic
Version          : #202303130630~1685473338~22.04~995127e SMP PREEMPT_DYNAMIC Tue M
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.1.0.dev0+1128.g6cb37b6e05
numpy            : 1.24.4
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 23.1.2
Cython           : 0.29.33
pytest           : 7.4.0
hypothesis       : 6.80.0
sphinx           : 6.2.1
blosc            : 1.11.1
feather          : None
xlsxwriter       : 3.1.2
lxml.etree       : 4.9.3
html5lib         : 1.1
pymysql          : 1.4.6
psycopg2         : 2.9.6
jinja2           : 3.1.2
IPython          : 8.14.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : 1.3.7
brotli           : 
fastparquet      : 2023.7.0
fsspec           : 2023.6.0
gcsfs            : 2023.6.0
matplotlib       : 3.7.1
numba            : 0.57.1
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : 12.0.1
pyreadstat       : 1.2.2
pyxlsb           : 1.0.10
s3fs             : 2023.6.0
scipy            : 1.11.1
snappy           : 
sqlalchemy       : 2.0.17
tables           : 3.8.0
tabulate         : 0.9.0
xarray           : 2023.6.0
xlrd             : 2.0.1
zstandard        : 0.21.0
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by phofl** [comment]
This is as expected to avoid triggering a copy (there are a bunch of closed issues).

there is removed_unused_levels if you want the set that is used

**Comment by r4f** [comment]
Thank you for replying.
Sorry that I didn't find the closed issues.

This was not obvious to me since there is no documentation to MultiIndex.levels.
[doc: api/pandas.MultiIndex.levels.html](https://pandas.pydata.org/docs/dev/reference/api/pandas.MultiIndex.levels.html) is currently empty.

Very curious that `df_abc.columns.levels is df_ab.columns.levels` still does not hold true, if supposedly no copy is triggered.
