### ISSUE TITLE
BUG: Inconsistent datetime dates dependent on specification of unit vs format

### ISSUE THREAD

**Issue by rsenne** [pandas-dev/pandas#54016]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
ex_1 = pd.to_datetime(["0", "12.12", "12.45"], unit="s")
ex_2 = pd.to_datetime(["0:00:0.0", "0:00:12.12", "0:00:12.45"], format='%H:%M:%S.%f')
```

### Issue Description

I have two different formats of timestamps I interact w. I recently noticed that when using "format" versus "unit" arguments  there is not consistent behavior in the date-portion. Unit uses 1970-01-01 as its default but format uses 1900-01-01.

### Expected Behavior

Equivalent default dates

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.10.11.final.0
python-bits      : 64
OS               : Linux
OS-release       : 6.2.6-76060206-generic
Version          : #202303130630~1685473338~22.04~995127e SMP PREEMPT_DYNAMIC Tue M
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.3
numpy            : 1.21.5
pytz             : 2022.7
dateutil         : 2.8.2
setuptools       : 66.0.0
pip              : 23.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.12.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : 1.3.5
brotli           : 
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.4.3
numba            : 0.55.1
numexpr          : 2.8.4
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by xzmeng** [comment]
When `unit` is present, `pd.to_datetime` treats the input as *Unix time*.

When `format` is present, `pd.to_datetime` parses the input with class method `strptime` of `datetime.datetime` in Python standard library. 

> For the [datetime.strptime()](https://docs.python.org/3/library/datetime.html#datetime.datetime.strptime) class method, the default value is 1900-01-01T00:00:00.000: any components not specified in the format string will be pulled from the default value. [4](https://docs.python.org/3/library/datetime.html#id8)

So, this inconsistent behavior should be expected, at least for current pandas' documentation.

**Comment by mroeschke** [comment]
Closing as the expected behavior according to the documentation
