### ISSUE TITLE
DOC: Improve SettingWithCopyWarning documentation

### ISSUE THREAD

**Issue by mcp292** [pandas-dev/pandas#54022]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

### Documentation problem

[It seems it used to suggest what to do](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#evaluation-order-matters):
> SettingWithCopyWarning:
> A value is trying to be set on a copy of a slice from a DataFrame. Try using .loc[row_index,col_indexer] = value instead

Now it just links to a caveats page (copied error locally on pandas 1.5.3):
> SettingWithCopyWarning:
> A value is trying to be set on a copy of a slice from a DataFrame
> 
> See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

I actually prefer linking to documentation, because the user is forced to reckon with and understand their mistake. The problem I have is the page it brings you to is not 100% clear on the solution. It does mention that `loc` is better, but only in the context of access, not assignment. 

Only two main sections and many subsections later, is [assignment with `loc` mentioned as a best practice](https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment), and there is nothing requiring the reader to continue that far in the documentation, when starting from the above error message.

The [Chained Assigment](https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment) section is very clear and concise. The example is straightforward and understandable and I am able to walk away having learned something I can put to use.

It also shows a more real-world attempt at what chained assignment looks like, and has the added benefit of allowing a user to compare the following and catch their out of order mistake, which neither errors or has lasting action on the dataframe:
```py
# df where bar is greater than five, set column foo to 100 [!WRONG ORDER!]
df[df["bar"] > 5]["foo"] = 100
```

### Suggested fix for documentation

The chained assignment section should either be combined with the returning view vs copy error, or the returning view vs copy error should link to chained assignment since returning view is what's linked in the error. 

The goal is to give the reader access to both sections, the combined reading of which makes for a complete explanation, and thus, understanding of the error encountered.

**Comment by phofl** [comment]
Contributions are certainly welcome, but this will become irrelevant when Copy-on-Write is the default.

**Comment by mcp292** [comment]
Can you explain how it will become irrelevant?

**Comment by phofl** [comment]
SettingWithCopyWarning won't be necessary with CoW. You can read up on it here; https://medium.com/towards-data-science/a-solution-for-inconsistencies-in-indexing-operations-in-pandas-b76e10719744

**Comment by mcp292** [comment]
Nice self-documenting examples. Thank you for linking your discussion, I enjoyed reading it.

I look forward to CoW being default, and hope some of your documentation makes it into the official docs. Especially the examples.

**Comment by phofl** [comment]
You can activate it now if you like.

We probably have to extend the user guide section in the Copy-on-Write part that explains how you can get rid of the ChainedAssignmentError we will raise. See https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html#chained-assignment

Happy to review if you are interested in contributing to the docs there

**Comment by mcp292** [comment]
I appreciate that. Right now my time is too limited to do a good job there.
