### ISSUE TITLE
DOC:  Add `NAType` and `NaTType` references in docs for `pandas.api.typing`

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#54028]
In #53934 I suggested we move `NAType` and `NaTType` into `pandas.api.typing`, which was done in #53958 .

But the PR did not include a docs update.

I think it would be worthwhile to add a sentence or two to https://pandas.pydata.org/docs/dev/user_guide/missing_data.html to describe these new public types and their purpose.

**Comment by oluwatonio** [comment]
take

**Comment by omar-elbaz** [comment]
take

**Comment by omar-elbaz** [comment]
take
