### ISSUE TITLE
ENH: series.is_constant

### ISSUE THREAD

**Issue by sbrugman** [pandas-dev/pandas#54033]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Pandas Series have a property [`is_unique`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.is_unique.html) that returns true iff all values are distinct. 

In practice, one often needs to know if a Series is constant. Getting a functional result when series do not contain nans is straight forward: `(series.values[0] == series.values).all()`. However, [in the wild](https://github.com/search?q=%22nunique%28%29+%3D%3D+1%22+language%3APython+&type=code) we observe that users often simply write `series.nunique() == 1`. This approach is more costly for larger series, as it first computes the number of unique values before comparing.

My assumption is that introducing a dedicated `is_constant` property will help users choose the more performant option. Another assumption is that its acceptable that all-nan series are somewhat slower.

![perf_short_circuit](https://github.com/pandas-dev/pandas/assets/9756388/88986548-b121-46ce-9dde-328ce2da92d6)

```python
def setup(n):
    return pd.Series(list(range(n)))
```

![perf_worst](https://github.com/pandas-dev/pandas/assets/9756388/0409dcd6-4d1c-4144-85f6-5a44c575ff27)

```python
def setup(n):
    return pd.Series([1] * (n - 1) + [2])
```

### Feature Description

```python
@property
def is_constant():
    if v.shape[0] == 0:
        return False
    return (v[0] == v).all()
```

(based on `is_unique` and `nunique`, in the absence of nans)

To extend to NA values:
If `dropna=True`: add `v = remove_na_arraylike(v)`
If  `dropna=False`: add `or not pd.notna(v).any()` (note: differs from `np.unique` for `pd.NA` and `np.nan` mixed series by lack of disambiguation between the two)

### Alternative Solutions

Recommend the approach above for `series.nunique() == 1` patterns in the documentation ([here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.nunique.html))

**Comment by lithomas1** [comment]
Is checking for a constant ever a bottleneck in a workflow?

This seems like something a user could easily do themselves.

Given the heavy usage of ``nunique()==1``, maybe this would be better as an example to add to the [pandas cookbook](https://pandas.pydata.org/docs/user_guide/cookbook.html)?

**Comment by sbrugman** [comment]
Adding an example to the pandas cookbook seems a good way of informing users to consider implementing a check that short-circuits. I will open a PR.

For completeness: Implementing `is_constant` (i.e. performant version of nunique() == 1) would be consistent with `is_unique` (i.e. nunique() == len(series)). The latter is also simple to achieve by the user and not expected to be a bottleneck.

**Comment by lithomas1** [comment]
> For completeness: Implementing `is_constant` (i.e. performant version of nunique() == 1) would be consistent with `is_unique` (i.e. nunique() == len(series)). The latter is also simple to achieve by the user and not expected to be a bottleneck.

I'll leave this open to see if others want this then.
