### ISSUE TITLE
BUG: version2.0.3  df.groupby('A').sum()  String type should not be concatenated

### ISSUE THREAD

**Issue by fenghualanglang** [pandas-dev/pandas#54031]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
# pandas==version2.0.3  
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': ['foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'foo'],
    'B': ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],
    'C': np.random.randn(8),
    'D': np.random.randn(8)
})

print(df.head())
print(df.groupby('A').sum())


    A      B         C         D
0  foo    one  0.161941  0.348251
1  bar    one -1.850115 -0.508695
2  foo    two  1.352457 -0.489330
3  bar  three -0.449750  0.215215
4  foo    two  0.373123 -0.223970



                     B         C         D
A                                         
bar        onethreetwo -2.381540 -0.045274
foo  onetwotwoonethree  3.095982  0.889978



error
df.groupby('A').agg([np.sum, np.mean, np.std])
```

### Issue Description

Df. groupby ('A '). sum() no  int, float types were add

### Expected Behavior

df.groupby('A').agg([np.sum, np.mean, np.std])

### Installed Versions

<details>

Replace this line with the output of pd.show_versions(2.0.3)
</details>

**Comment by phofl** [comment]
These are Python semantics, sum is defined for strings while mean is not. You can simply do

```
print(df.groupby('A').sum(numeric_only=True))
```

if you don't want strings
