### ISSUE TITLE
BUG: loss of precision when adding np.nan to int64 columns, e.g. join and replace

### ISSUE THREAD

**Issue by limwz01** [pandas-dev/pandas#54032]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

The following first sets up `left_df` and `right_df`, where `right_df` contains some values in `left_df` to be replaced. Then it joins `left_df` to `right_df` and replaces the corresponding values. However, the replacement is lossy because of this issue.

```python
import random
import pandas as pd
import numpy as np

left_df = pd.DataFrame(
    {"value": [random.randint(0, 2**63 - 1) for i in range(10)]})
right_df = left_df.loc[left_df.index % 2 == 0].set_index("value")
right_df["replaced_value"] = np.array(
    [random.randint(0, 2**63 - 1) for i in range(5)])
print(left_df)
print(right_df)

left_df = left_df.join(right_df, on="value")
print(left_df["replaced_value"])
left_df["replaced_value"].fillna(left_df["value"],
                                 downcast="infer",
                                 inplace=True)
print(left_df["replaced_value"])
assert left_df.iloc[0, 1] == right_df.iloc[0, 0]
```

### Issue Description

The assertion fails in the example provided. Columns should not be automatically casted to float64 from int64 as this would lose precision. This may happen as a result of a join operation, as seen in the example. Instead, the column should be casted to dtype Int64.

### Expected Behavior

The assert should not fail, and it should work like the following (where dtype is specified in `right_df`):
```python
left_df = pd.DataFrame(
    {"value": [random.randint(0, 2**63 - 1) for i in range(10)]})
right_df = left_df.loc[left_df.index % 2 == 0].set_index("value")
right_df["replaced_value"] = np.array(
    [random.randint(0, 2**63 - 1) for i in range(5)], dtype=pd.Int64Dtype)
print(left_df)
print(right_df)

left_df = left_df.join(right_df, on="value")
print(left_df["replaced_value"])
left_df["replaced_value"].fillna(left_df["value"],
                                 downcast="infer",
                                 inplace=True)
print(left_df["replaced_value"])
assert left_df.iloc[0, 1] == right_df.iloc[0, 0]
```

For anyone who wants a reasonably efficient workaround for this use-case, this is what you do:
```python
left_df["replaced_value"] = left_df["value"]
left_df.set_index("value", inplace=True)
left_df.loc[right_df.index, "replaced_value"] = right_df["replaced_value"]
left_df.reset_index(inplace=True)
assert left_df.iloc[0, 1] == right_df.iloc[0, 0]
```

### Installed Versions

<details>

pandas           : 2.0.2
numpy            : 1.23.5

</details>

**Comment by phofl** [comment]
This is how int64 works, it can not deal with missing values. You can either use ``Int64``, which is our own integer dtype that can have missing values or the pyarrow version ``int64[pyarrow]`` that can store missing values as well.

**Comment by limwz01** [comment]
Please show me where in the docs says that I cannot left join on an int64 column. If it is not even warned about in the docs, it should be considered a bug.

**Comment by phofl** [comment]
Please read up on the specifics of NumPys integer dtype, this is not a bug

**Comment by phofl** [comment]
Also here: https://pandas.pydata.org/docs/user_guide/missing_data.html#integer-dtypes-and-missing-data
