### ISSUE TITLE
DOC: Adding pandas to Code Library Help plugin 

### ISSUE THREAD

**Issue by mswoff** [pandas-dev/pandas#54050]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/getting_started/index.html#getting-started

### Documentation problem

I wanted to let the maintainers know that users of our Code Library Help Chatgpt plugin have requested we support pandas. Unless we hear otherwise from you, we’ll add support for pandas (free for open-source projects and no action required from your team).

The plugin let's users get library specific coding help by analyzing panda's codebase.

If you want to get in touch about any concerns or offering AI based support directly on panda's docs/website, please email me at mason@salv.ai.

### Suggested fix for documentation

No action needed unless you want to AI docs on pandas website.

**Comment by rhshadrach** [comment]
Thanks for letting us know!

cc @pandas-dev/pandas-core @pandas-dev/pandas-triage
