### ISSUE TITLE
BUG: Error when using Series.pow with fill_value

### ISSUE THREAD

**Issue by wirable23** [pandas-dev/pandas#54069]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> a = pd.Series([-78, -1, -99, -63, None], dtype="int8[pyarrow]")
>>> b = pd.Series([-0.0, 157916751531245592198949268791230464.0, 0.0, None, 13.431721], dtype="float[pyarrow]")
>>> df2 = pd.DataFrame({"Left": a, "Right": b, "Fill": a.copy()})
>>> df2["Left"].pow(df2["Right"], fill_value=df2["Fill"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\pss_env_311\Lib\site-packages\pandas\core\ops\__init__.py", line 189, in flex_wrapper
    return self._binop(other, op, level=level, fill_value=fill_value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pss_env_311\Lib\site-packages\pandas\core\series.py", line 3067, in _binop
    this_vals, other_vals = ops.fill_binop(this._values, other._values, fill_value)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pss_env_311\Lib\site-packages\pandas\core\ops\__init__.py", line 148, in fill_binop
    right[right_mask & mask] = fill_value
    ~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\pss_env_311\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 1402, in __setitem__
    data = self._replace_with_mask(self._data, key, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pss_env_311\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 1684, in _replace_with_mask
    result[mask] = replacements
    ~~~~~~^^^^^^
ValueError: NumPy boolean array indexing assignment cannot assign 5 input values to the 1 output values where the mask is true
>>>
```

### Issue Description

An error is raised, the example above should work.

### Expected Behavior

0    NaN
1    1.0
2    NaN
3    0.0
4    pd.NA
dtype: float[pyarrow]
>>>

I expect the series above to be returned.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 84d85fa8a002869ea3d2bcec5ff38c2280a15eca
python           : 3.11.2.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 2.1.0.dev0+850.g84d85fa8a0
numpy            : 1.25.0.dev0+1465.g126b46c7a
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.7.2
pip              : 23.1.2
Cython           : None
pytest           : 7.0.1
hypothesis       : None
sphinx           : 4.2.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.13.2
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 12.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : 0.9.0
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None
>>>
</details>

**Comment by wirable23** [comment]
I installed a nightly build, it returns 

0    NaN
1    1.0
2    NaN
3    0.0
4    NaN
dtype: float[pyarrow]

So the error is fixed, but I would expect at index 4, to be NA, not NaN.

**Comment by rhshadrach** [comment]
The documentation does not say that this method supports `fill_value` being a Series:

https://pandas.pydata.org/docs/dev/reference/api/pandas.Series.pow.html

This also appears to be the case looking at the implementation of this method.

**Comment by rhshadrach** [comment]
One can call `.fillna(...)` after this method with a Series to fill in values. However, this will not have quite the same behavior: using `fill_value` in the `pow` method will only fill values when exactly one of `self` and `other` is NA rather than all resulting NA values. If this is the behavior you desire (so `.fillna(...)` doesn't work for your use case), I'd be curious to learn more details. It seems like an odd choice to only fill NA values in such circumstances.

**Comment by wirable23** [comment]
Ah you are right, documentation mentions a scalar only.
