### ISSUE TITLE
BUG: groupby.shift.rolling produces wrong results when min_periods is smaller than the rolling window.

### ISSUE THREAD

**Issue by chulwoohan** [pandas-dev/pandas#54071]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

x = {'ret': {(Timestamp('1985-12-31 00:00:00'), 10000): nan,
  (Timestamp('1986-01-31 00:00:00'), 10000): nan,
  (Timestamp('1986-02-28 00:00:00'), 10000): -0.2571428716182709,
  (Timestamp('1986-03-31 00:00:00'), 10000): 0.36538460850715637,
  (Timestamp('1986-04-30 00:00:00'), 10000): -0.09859155118465424,
  (Timestamp('1986-05-30 00:00:00'), 10000): -0.22265625,
  (Timestamp('1986-06-30 00:00:00'), 10000): -0.005025125574320555,
  (Timestamp('1986-07-31 00:00:00'), 10000): -0.08080808073282242,
  (Timestamp('1986-08-29 00:00:00'), 10000): -0.6153846383094788,
  (Timestamp('1986-09-30 00:00:00'), 10000): -0.05714285746216774,
  (Timestamp('1986-10-31 00:00:00'), 10000): -0.24242424964904785,
  (Timestamp('1986-11-28 00:00:00'), 10000): 0.05999999865889549,
  (Timestamp('1986-12-31 00:00:00'), 10000): -0.37735849618911743,
  (Timestamp('1987-01-30 00:00:00'), 10000): -0.21212121844291687,
  (Timestamp('1987-02-27 00:00:00'), 10000): 0.0,
  (Timestamp('1987-03-31 00:00:00'), 10000): -0.38461539149284363,
  (Timestamp('1987-04-30 00:00:00'), 10000): -0.0625,
  (Timestamp('1987-05-29 00:00:00'), 10000): -0.06666667014360428,
  (Timestamp('1987-06-30 00:00:00'), 10000): 0.0,
  (Timestamp('1985-12-31 00:00:00'), 10001): nan,
  (Timestamp('1986-01-31 00:00:00'), 10001): nan,
  (Timestamp('1986-02-28 00:00:00'), 10001): 0.020408162847161293,
  (Timestamp('1986-03-31 00:00:00'), 10001): 0.025200003758072853,
  (Timestamp('1986-04-30 00:00:00'), 10001): 0.009900989942252636,
  (Timestamp('1986-05-30 00:00:00'), 10001): -0.009803921915590763,
  (Timestamp('1986-06-30 00:00:00'), 10001): -0.013069307431578636,
  (Timestamp('1986-07-31 00:00:00'), 10001): -0.010204081423580647,
  (Timestamp('1986-08-29 00:00:00'), 10001): 0.07216494530439377,
  (Timestamp('1986-09-30 00:00:00'), 10001): -0.003076923545449972,
  (Timestamp('1986-10-31 00:00:00'), 10001): 0.03921568766236305,
  (Timestamp('1986-11-28 00:00:00'), 10001): 0.056603774428367615,
  (Timestamp('1986-12-31 00:00:00'), 10001): 0.014999999664723873,
  (Timestamp('1987-01-30 00:00:00'), 10001): -0.0357142873108387,
  (Timestamp('1987-02-27 00:00:00'), 10001): -0.07407407462596893,
  (Timestamp('1987-03-31 00:00:00'), 10001): 0.03680000081658363,
  (Timestamp('1987-04-30 00:00:00'), 10001): -0.03921568766236305,
  (Timestamp('1987-05-29 00:00:00'), 10001): -0.0714285746216774,
  (Timestamp('1987-06-30 00:00:00'), 10001): 0.051428571343421936,
  (Timestamp('1987-07-31 00:00:00'), 10001): 0.021276595070958138,
  (Timestamp('1987-08-31 00:00:00'), 10001): 0.0833333358168602,
  (Timestamp('1987-09-30 00:00:00'), 10001): -0.02230769209563732,
  (Timestamp('1987-10-30 00:00:00'), 10001): 0.019999999552965164,
  (Timestamp('1987-11-30 00:00:00'), 10001): -0.029411764815449715,
  (Timestamp('1987-12-31 00:00:00'), 10001): -0.03353535383939743}}
df = pd.DataFrame.from_dict(x).sort_index(level=-1)
print(df.ret.groupby(level=-1).shift(2).rolling(10, min_periods=7).sum())
```

### Issue Description

The results of permno == 10001 should be Nan before '1986-10-31' but the first three elements have values from shifted 10000. It seems like when ``shift()`` is added, the rolling operation is applied to the entire data not to each group: with ``shift()``, the calculation is much faster.

### Expected Behavior

The values of 10001 until '1986-10-31' should be Nan.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 8dab54d6573f7186ff0c3b6364d5e4dd635ff3e7
python           : 3.10.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Korean_Korea.949
pandas           : 1.5.2
numpy            : 1.23.4
pytz             : 2022.7
dateutil         : 2.8.2
setuptools       : 59.8.0
pip              : 23.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 6.2.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : 1.4.6
psycopg2         : 2.9.3
jinja2           : 3.1.2
IPython          : 8.14.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : 1.3.5
brotli           : None
fastparquet      : None
fsspec           : 2023.5.0
gcsfs            : None
matplotlib       : 3.6.0
numba            : 0.57.1
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.1
snappy           : None
sqlalchemy       : 1.4.41
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report.

> It seems like when `shift()` is added, the rolling operation is applied to the entire data

When you do `.groupby(...).shift(...)` this produces a DataFrame. By adding `.rolling(...)` to this, you are no longer doing `.groupby(...).rolling(...)` as I think you are expecting. I think what you want to accomplish is something like:

`df.groupby(...).shift(...).groupby(...).rolling(...)`

**Comment by chulwoohan** [comment]
Thank you for the prompt reply. Yes, grouping one more time should solve the issue.
