### ISSUE TITLE
ENH: Add `Series#between` to `DatetimeIndex`

### ISSUE THREAD

**Issue by bollard** [pandas-dev/pandas#54094]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I would like to use [`Series#between`](https://pandas.pydata.org/docs/reference/api/pandas.Series.between.html) on `DatetimeIndex` instances. Presumably this could also be extended to other Index types, but I am specifically only considering the DatetimeIndex case

### Feature Description

```python
import pandas as pd

t = pd.Timestamp.today()
ser = pd.Series(range(10), index=pd.date_range(t, periods=10))

ser.loc[ser.between(t, t + pd.offsets.BDay(1))]
```

### Alternative Solutions

```python
import pandas as pd

t = pd.Timestamp.today()
ser = pd.Series(range(10), index=pd.date_range(t, periods=10))

# current option 1
ser.loc[(ser.index >= t) & (ser.index <= t + pd.offsets.BDay(1))]

# current option 2
ser.loc[ser.index.to_series().between(t, t + pd.offsets.BDay(1))]
```

### Additional Context

Purely convenience method / addition. Presumably could also be extended to the related `between_time` method.

**Comment by mroeschke** [comment]
Thanks for the request, but it appears this request hasn't gotten much traction so closing
