### ISSUE TITLE
DOC: squeeze cannot be used safely on a Series

### ISSUE THREAD

**Issue by wjandrea** [pandas-dev/pandas#54123]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.squeeze.html

and https://pandas.pydata.org/docs/dev/reference/api/pandas.Series.squeeze.html

> This method is most useful when you don’t know if your object is a Series or DataFrame, but you do know it has just a single column. In that case you can safely call squeeze to ensure you have a Series.

### Documentation problem

It's not safe if the Series only has one element:
```
>>> pd.Series(range(1)).squeeze()
0
```

If I try to make it safe by passing `axis='columns'`, I get a `ValueError`.
```
>>> pd.Series(range(1)).squeeze('columns')
    ...
ValueError: No axis named columns for object type Series
```

### Suggested fix for documentation

I'm not sure if the documentation needs to be changed to match the behaviour or vice-versa.

If the documentation needs to be changed, then I'd like to know how ensure I have a Series. Maybe this more explicit option?
```
ser = obj if isinstance(obj, Series) else obj.squeeze('columns')
```

**Comment by phofl** [comment]
This behaves as expected. It explicitly states that these are reduced to scalars

**Comment by wjandrea** [comment]
@phofl I'm specifically talking about the paragraph I quoted:

> This method is most useful when you don’t know if your object is a Series or DataFrame, but you do know it has just a single column. In that case you can safely call squeeze to ensure you have a Series.

Because squeeze isn't always safe
