### ISSUE TITLE
REF: Proposal: change `DataFrame.to_excel` to output unformatted excel file

### ISSUE THREAD

**Issue by attack68** [pandas-dev/pandas#54154]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

## TLDR;

Please indicate with a +1 if you are happy for the default `DataFrame.to_excel` to be changed to output an excel file **without** any bold or bordered style attached.

## Description

The current action of `DataFrame.to_excel` is to produce an excel file with default bold and bordered styles for column and row headers:
```python
df = pd.DataFrame([[1,2],[3,4]], index=["one", "two"], columns=["A", "B"])
df.to_excel("file.xlsx")
```
![image](https://user-images.githubusercontent.com/24256554/208918872-c616b449-b399-42e6-8a03-b3581063857a.png)

A number of issues are attempting to address this:
 - #50336 
 - #22758
 - #22773 
 - #52369
 - #50991

In a recent PR (#53973) it is proposed to remove the ability to format excel file styles with `DataFrame.to_excel` and instead document how users can use the `Styler.to_excel` to create styles excel files.

This has a number of advantages:

- Simplifies the code, since it is effectively a removal and additions of documentation.
- Creates a more consistent `Styler.to_excel` (which uses `DataFrame.to_excel`) since an unstyled `Styler` wont produce this bold bordering by default.
- Encourages users to use a more flexible tool for formatting.

@pandas-dev appreciate input to gain some form of concensus to proceed.
@WillAyd @rhshadrach @mroeschke

### Feature Description

-

### Alternative Solutions

-

### Additional Context

-

**Comment by rmhowe425** [comment]
take

**Comment by WillAyd** [comment]
+1

**Comment by rhshadrach** [comment]
+1

**Comment by mroeschke** [comment]
+1 on a deprecation of to_excel from producing a formatted excel file

**Comment by rhshadrach** [comment]
@mroeschke - would you be opposed to doing this in 3.0 without deprecation? I think to deprecate this, there would need to be a way to silence the warning - e.g. an argument or option added in and then that deprecated in 3.0. Since this can't break any code (it's just styling), that doesn't seem worth the effort to me.

**Comment by mroeschke** [comment]
Sure a 3.0 break sounds good too

**Comment by alimcmaster1** [comment]
+1

**Comment by attack68** [comment]
I would suggets we have enough support here to progress with at least the PR, @rmhowe425

**Comment by rmhowe425** [comment]
@attack68 Excellent! I'll get started on implementation
