### ISSUE TITLE
BUG: Inconsistent Shallow Copy Behavior in DataFrame with sample() Series

### ISSUE THREAD

**Issue by sergeiosipov** [pandas-dev/pandas#54152]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
from random import sample

import pandas as pd

df = pd.DataFrame({"a": range(1, 6), "b": range(5, 0, -1)})
view_df = df.copy(deep=False)
# True (as expected)
print(view_df.to_numpy().base is df.to_numpy().base)

df_sample = pd.DataFrame({"a": range(1, 6), "b": sample("1234567890", 5)})
view_df_sample = df_sample.copy(deep=False)
# False (True expected)
print(view_df_sample.to_numpy().base is df_sample.to_numpy().base)
```

### Issue Description

When comparing `.to_numpy().base` between original dataframe and its shallow copy (`.copy(deep=False`) I have unexpected result for the dataframe with a series generated with `sample()` function.

### Expected Behavior

I would expect the shallow copy behaviour to be consistent for both scenarios: 
`view_df_sample.to_numpy().base is df_sample.to_numpy().base` should also return `True`

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 0f437949513225922d851e9581723d82120684a6
python           : 3.11.1.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 2.0.3
numpy            : 1.25.1
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 68.0.0
pip              : 23.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.1.2
lxml.etree       : 4.9.3
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.14.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by lithomas1** [comment]
sample here is returning a string, so column b will be object dtype.
e.g.
```
>>> df_sample.dtypes
a     int64
b    object
dtype: object
```

This means that the to_numpy call has to make a copy (and create a new object array) every single time in order to get column A and column B in the same array.

**Comment by phofl** [comment]
That's in the first block of the docstring, closing
