### ISSUE TITLE
BUG: joining empty frame to multiindex frame no longer works

### ISSUE THREAD

**Issue by KIC** [pandas-dev/pandas#54249]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

if __name__ == '__main__':
    df = pd.DataFrame({1: range(10)})
    df.columns = pd.MultiIndex.from_tuples([(1,2)])
    df = df.join(pd.DataFrame({}, index=range(2, 12)), how='outer')
    print(df)
```

### Issue Description

Joining empty frames always worked and is needed to align the indexes (especially for outer join cases). But now errors with `Not allowed to merge between different levels.`. And it looks like there is not even a way to create an empty MultiIndex with the correct levels.

### Expected Behavior

joining empty columns should be allowed in any case

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 0f437949513225922d851e9581723d82120684a6
python           : 3.11.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 6.2.6-76060206-generic
Version          : #202303130630~1685473338~22.04~995127e SMP PREEMPT_DYNAMIC Tue M
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.3
numpy            : 1.24.4
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 65.5.1
pip              : 22.3.1
Cython           : None
pytest           : 7.4.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.14.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.2
numba            : 0.57.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.11.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : 0.9.0
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by JostBrand** [comment]
Seems like this was a conscious choice. I just run your code on 1.5.3 and got the following warning:

```
FutureWarning: merging between different levels is deprecated and will be removed in a future version. (2 levels on the left, 1 on the right)
  df = df.join(pd.DataFrame({}, index=range(2, 12)), how='outer')
```

**Comment by KIC** [comment]
it's about empty frames. and you can't create a n level empty multiindex.

**Comment by phofl** [comment]
Actually that's not correct, 

```
pd.MultiIndex.from_tuples([], names=["a", "b"])
```

**Comment by KIC** [comment]
Hmm ok. While I see the point of mixed level joins I still believe joining an empty frame should be possible as it was.

**Comment by phofl** [comment]
Not with mixed level joins, that would introduced unnecessary inconsistencies
