### ISSUE TITLE
ENH: Basic outlier detection methods

### ISSUE THREAD

**Issue by ndgigliotti** [pandas-dev/pandas#54262]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Often in data science work there are situations in which we don't care about the outliers, and want to ignore them. For example, suppose your company regularly documents complaints after receiving phone calls from customers. Suppose you want to determine the temporal window in which complaints are documented after a call comes in, and find that the writeup is almost always created during the phone call. However, in rare cases you find that it is (ostensibly) created years after the phone call. When dealing with large amounts of data, such anomalous cases merely get in the way of a clear analysis of the typical pattern, and it's better to throw them out.

Use cases like the one I've described are extremely common, and the lack of built-in methods for addressing them requires data scientists to implement their own solutions over and over again. I've done exactly that, over and over again, for years. And once I have those tools on a particular project, the work becomes much easier. Descriptive statistics and plots can sometimes immediately reveal the pattern I was looking for, which was previously distorted. The lack of such convenient methods has likely caused many data scientists to miss patterns in the data.

#### Overview

My proposed solution is to add two new (interdefined) methods: `DataFrame.inliers` and `DataFrame.outliers`. There are two classic univariate outlier detection algorithms which could easily be implemented in those methods: the IQR proximity rule and the standard score threshold.

#### IQR Proximity Rule

The interquartile range (IQR) proximity rule (developed by John Tukey) simply places fences at a margin of 1.5 * IQR on either side of the IQR (i.e. on either side of the first and third quartiles). Whatever falls within the fences is regarded as an inlier. You are probably familiar with this, as it is the box plot algorithm. This could be implemented using methods that are already available in Pandas, such as `DataFrame.quantile`, `DataFrame.where`, and various operators.

#### Standard Score Threshold

Although the IQR approach is my usual go-to due to its robustness to outliers, the standard score approach could be added as an alternative option for normally distributed data. This approach is to compute the z-score (i.e standard devaitions from the mean) for each point and classify points as outliers which have an absolute z-score greater than 3. This could be implemented using `scipy.stats.zscore`.

#### The Return Value

Both `DataFrame.outliers` and `DataFrame.inliers` would return a boolean mask. The reason for returning a boolean mask is so that the user can easily view the inliers or outliers with a locution like `df['my_feat'].loc[lambda x: x.outliers()]`. The user can also perform calculations or make plots this way.

Another convenient option would be to return the `DataFrame.where` result with a null fill value. Getting the `where` result would allow the user to immediately perform calculations on the inliers (or outliers), using something like `df.inliers(where=True).describe()`. Otherwise they could do `df.where(df.inliers(), np.nan).describe()`, which would be almost as convenient.

### Example Code

Here is an example implementation of the `DataFrame.inliers` method, including both the IQR and standard score options. The `DataFrame.outliers` method could be easily defined as the negation.

```py
import numpy as np
from scipy import stats
import pandas as pd

def inliers(
    self,
    method: str = "iqr",
    iqr_factor: float = 1.5,
    zscore_thresh: float = 3.0,
    where: bool = False,
    interpolation: str = "linear",
    axis: int = 0,
    numeric_only: bool = False,
) -> pd.DataFrame:
    data = self if not numeric_only else self.select_dtypes(np.number)
    # Transpose data if axis is 1
    if axis == 1:
        data = data.T
    if method == "iqr":
        # Get first and third quartile
        quartiles = data.quantile(
            [0.25, 0.75], axis=0, numeric_only=numeric_only, interpolation=interpolation
        )
        q1, q3 = quartiles.iloc[0], quartiles.iloc[1]
        # Calculate interquartile range
        iqr = q3 - q1
        # Calculate lower and upper fences
        margin = iqr_factor * iqr
        lower = q1 - margin
        upper = q3 + margin
        mask = (data >= lower) & (data <= upper)

    elif method == "zscore":
        # Calculate absolute z-scores
        zscores = stats.zscore(data).abs()
        mask = zscores <= zscore_thresh
    else:
        raise ValueError(f"Unknown method: {method}")

    # Transpose data and mask back again
    if axis == 1:
        data, mask = data.T, mask.T
    return data.where(mask, np.nan) if where else mask
```

### Alternative Solutions

The primary alternative is to implement something like the above code yourself, either as a function or a method attached to the `DataFrame` and `Series` classes. Indeed, if you search for Python outlier detection, you will find a variety of blog posts and how-to guides explaining how to implement something like the above code. It's fairly simple code, but time-consuming to reproduce over and over again. Why should millions of data scientists have to reinvent the wheel? Think of the millions of hours that could be saved, and all the insights that could be gained.

There are a variety of more sophisticated multivariate outlier detection methods, such as [Scikit-Learn](https://scikit-learn.org/stable/index.html)'s `LocalOutlierFactor` or `IsolationForest`. These are machine learning algorithms which operate on a vector space, and are thus not ideal for finding patterns in a single variable. [PyOD](https://github.com/yzhao062/pyod) offers an even wider array of (mostly multivariate) algorithms, and apparently includes the IQR approach. Nevertheless, it's a machine learning library, not that well documented, and overkill for basic exploratory data analysis. It would be easier to implement a custom function than to learn PyOD. Plus, unlike PyOD, Pandas is a core data science library found in many environments where package availability is limited.

### Additional Context

Basic outlier detection methods should be added to Pandas because they're powerful, easy to implement, and the use cases for them are extremely common. I'm sure data scientists often fail to notice patterns due to the inconvenience of outlier detection.

**Comment by attack68** [comment]
The pandas project has really reached a stage where its API is already quite large. Whilst I agree with you that these methods are fairly common for certain types of users they are not that common for data wrangling outside of a statistical domain. And for those cases pandas has methods such as dropna, which is not a parametrised algorithm but a binary determination of missing data or not. Pandas more aims to be a performant data wrangling tool for methods that are functional rather than subjective through parameters. E.g. it strives to provide performant map/reduce/filter/groupby/aggregate, with included In/Out operations.

In my opinion, which I think is shared by pandas dev team, is that parameterised outlier detection methods are better suited to other projects. Your comments about scikitlearn demonstate the scope of methods available for different cases of data. https://scikit-learn.org/stable/modules/outlier_detection.html

Scikit learn project is actually part of the NumFocus projects. What might be more valuable to users is to show/document how to integrate pandas and scikitlearn outlier detection methods to be able to seamlessly apply them to DataFrames. That way if new research leads to better algoritms that are implemented or changed in Scikit learn the applicability to pandas remains constant and pandas users can instantly benefit, without the need for a pandas maintainer updating the codebase.

**Comment by ndgigliotti** [comment]
Pandas has a lot of statistical features and is kind of a bread-and-butter library for data scientists. It seems to me that since Pandas already has a large API, it wouldn't be too big of a deal to add a couple new methods.

Regarding the parameters, they can simply be hardcoded into the methods if you prefer. I exposed them because that's my general habit, but the are rarely ever used at values other than the defaults. There is actually **already an instance of the IQR proximity algorithm in Pandas** in the form of the [boxplot](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.boxplot.html) method, so it's hardly beyond the scope of Pandas. If you read the description, you will see that it is exactly the algorithm I described, but the factor of 1.5 is non-configurable. The same approach could be taken here.

I try not to get too fixated on the details, and I'm certainly not suggesting we add the feature _exactly_ as I've described it. If it would be better to hardcode the factor of 1.5 and the threshold of 3.0, then that's fine with me. If it would be better to leave out the standard score approach entirely, that's also fine with me. If it would be better to implement the z-score algorithm independently of `scipy`, that's perfectly fine.

With regard to Scikit-Learn, I love it. It's one of my favorite libraries. However, the outlier detection algorithms offered by Scikit-Learn are not useful for univariate outlier detection. They are meant for outlier detection in vector spaces, or of a whole numeric `DataFrame`. That is not usually what you want for basic exploratory data analysis. The example I gave in my original post was one that came up for me at work this week, and it would not have made sense to use Scikit-Learn.

**Comment by MarcoGorelli** [comment]
thanks for the suggestion - this has been discussed before but it generally considered out-of-scope for pandas

**Comment by ndgigliotti** [comment]
Thanks for the consideration. Maybe I'll make a little monkey patch package that does this.

Why is the box plot method not out of scope though, if I may ask? It's the same algorithm but restricted to a plot. I don't mean to provoke, I just thought I had a pretty good point there. 

Pandas is one of my favorite libraries and I use it every day, so thank you all for the good work.

**Comment by mroeschke** [comment]
> Why is the box plot method not out of scope though, if I may ask?

Not sure. It was just added when matplotlib integration was added.
