### ISSUE TITLE
BUG: to_sql() insertion issue to Oracle DB

### ISSUE THREAD

**Issue by NKMatha** [pandas-dev/pandas#54274]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
from sqlalchemy import create_engine

connection_string = f"oracle+oracledb://{inst.usr}:{inst.passwd}@{inst.host}:{inst.port}/?service_name={inst.service}"
engine = create_engine(connection_string, thick_mode=True)

df = pd.read_csv('file/path.csv')


df.to_sql('table_name',engine,index = False)
```

### Issue Description

oracledb.exceptions.NotSupportedError: DPY-3013: unsupported Python type int for database type DB_TYPE_NVARCHAR

even tried for converting all columns to df.astype(str) which is inserting Nan string in table

### Expected Behavior

values to be inserted into tables with empty/null cells if Nan in df like df.to_csv() which does not save Nan in csv files.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 37ea63d540fd27274cad6585082c91b1283f963d
python           : 3.9.13.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19045
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

 

pandas           : 2.0.1
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 58.1.0
pip              : 22.0.4
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.13.2
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : 2.0.13
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by phofl** [comment]
We don't have testing for oracle, but investgations are welcome

This needs a proper reproducer though, without external dependencies

**Comment by mroeschke** [comment]
Closing as there isn't much of a way for pandas to test and confirm a fix for oracle
