### ISSUE TITLE
ENH: Interval(Timedelta, Timedelta) + Timestamp

### ISSUE THREAD

**Issue by whoknowsB** [pandas-dev/pandas#54270]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Works:
```python
pd.Interval(pd.Timestamp('20200101'), pd.Timestamp('20200102')) + pd.Timedelta(days=1)
```

Does not work:
```python
pd.Interval(pd.Timedelta(days=1), pd.Timedelta(days=2)) + pd.Timestamp('20200101')
```

### Feature Description

Add support for operand type(s) for +: 'pandas._libs.interval.Interval' and 'Timestamp'

### Alternative Solutions

not supported for now

**Comment by mroeschke** [comment]
Thanks for the support. The dunder arithmetic methods should also have a check for datetime-like objects. Interested in submitting a PR?

https://github.com/pandas-dev/pandas/blob/577bb7239cfb7ea301c9003b9fc1c7e43c0fbbfb/pandas/_libs/interval.pyx#L506

**Comment by jbrockmendel** [comment]
Related to #35908?

**Comment by mroeschke** [comment]
Yeah looks like essentially the same core issue so closing in favor of that one
