### ISSUE TITLE
DOC: `to_csv()` opens file with append if called in loop

### ISSUE THREAD

**Issue by mcp292** [pandas-dev/pandas#54280]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html

### Documentation problem

# MWE
```py
import pandas as pd


data = {"i": [], "i*i": []}

for i in range(10):
    data["i"].append(i)
    data["i*i"].append(i*i)

    df = pd.DataFrame(data)
    df.to_csv("test.csv")
```

At the end, `test.csv` contains all 10 entries. How and why? Is this intended?

### Suggested fix for documentation

I am filing this as a documentation improvement because I am not sure whether or not this is intended behavior. 

If it is intended, this would be nice to include in the documentation. How would the function know function call context though?

**Comment by lithomas1** [comment]
At the 10th iteration, doesn't data have 10 entries?

**Comment by mcp292** [comment]
100%. Makes sense now, thanks! Closing.
