### ISSUE TITLE
DOC: read_excel and read_csv have a new date_format parameter, but the format of this is not documented

### ISSUE THREAD

**Issue by johnmreynolds** [pandas-dev/pandas#54285]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.read_csv.html
https://pandas.pydata.org/docs/dev/reference/api/pandas.read_excel.html

### Documentation problem

In pandas 2.0 various data read functions have a new date_format parameter.

However, the documentation doesn't actually say what the format of this is.

I'm assuming it's supposed to be a strftime format, but it doesn't say.

(And separately, my testing suggests it doesn't work - but that's probably due to https://github.com/pandas-dev/pandas/issues/44284 )

### Suggested fix for documentation

Specify in the documentation what the format of the date_format parameter is.

**Comment by asishm-wk** [comment]
Thanks for the report.
The linked issue is unrelated - that is for writing excel files only.

> And separately, my testing suggests it doesn't work

Can you provide a reproducible example?

**Comment by johnmreynolds** [comment]
Ah, so it turns out that my issue with the functionality was that parse_dates=True doesn't do what I expected. The behavior does match the documentation, it was just a bit of a surprise. Passing the name(s) of the date columns into parse_dates does seem to work.

**Comment by johnmreynolds** [comment]
And indeed, the format of date_format does seem to be strftime, so the original issue can be summarized as "date_format parameter documentation should say that it uses strftime format"

**Comment by johnmreynolds** [comment]
It also seems to support "ISO8601" and "mixed" like to_datetime. So it could possibly just reference the format in that. It does already link to to_datetime, but in the context of an alternative to use.

**Comment by lithomas1** [comment]
Thanks for reporting this issue.

I had a look, and I think you're right about it being a strftime format (I think it should be the same as ``foramt`` in ``to_datetime`` but I don't use the date stuff in pandas a lot).

Would you like to raise a pull request to document this?

**Comment by rsm-23** [comment]
take

**Comment by brendan-m-murphy** [comment]
Any chance this could be sign-posted in the current 2.12 docs?
