### ISSUE TITLE
DOC: dataframe.drop return value description incorrect 

### ISSUE THREAD

**Issue by aliasgar55** [pandas-dev/pandas#54319]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html

### Documentation problem

Return value for the drop function says, 
`Returns
DataFrame or None
DataFrame without the removed index or column labels or None if inplace=True.`
Instead it returns the dataframe with the droped index and lables

### Suggested fix for documentation

documentation should says
`Returns
DataFrame or None
DataFrame with the index or column labels removed or None if inplace=True`

**Comment by lithomas1** [comment]
Thanks for finding this, I think your version is more clear.

If you'd like, a PR for this would be welcome.

I would add in the word specified before index in the suggested fix though to be extra clear, so:
``Returns DataFrame or None DataFrame with the specified index or column labels removed or None if inplace=True``

**Comment by aliasgar55** [comment]
Sure I will raise a PR
