### ISSUE TITLE
###     from _lzma import * ModuleNotFoundError: No module named '_lzma' :: Solution

### ISSUE THREAD

**Issue by defyingdemonprogram** [pandas-dev/pandas#54312]
### Solution
**frist**

```
yum install xz-devel
yum install python-backports-lzma
pip install backports.lzma
```
**second**

```
cd /usr/local/lib/python3.8
vi lzma.py 
```
**finally**
modify about line 27
```

try:
    from _lzma import *
    from _lzma import _encode_filter_properties, _decode_filter_properties
except ImportError:
    from backports.lzma import *
    from backports.lzma import _encode_filter_properties, _decode_filter_properties
```
it‘s work！I had to search for hours to get this problem to be solved. 

Credit: [Yolo5 issues](https://github.com/ultralytics/yolov5/issues/1298)

_Originally posted by @realsanjeev in https://github.com/pandas-dev/pandas/issues/27532#issuecomment-1657197045_

**Comment by phofl** [comment]
Hi, thanks for your report. This is not a pandas issue
