### ISSUE TITLE
DEPR: Are `pandas.plotting.deregister_matplotlib_converters` and `pandas.plotting.register_matplotlib_converters`still needed?

### ISSUE THREAD

**Issue by DeaMariaLeon** [pandas-dev/pandas#54326]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.plotting.register_matplotlib_converters.html

https://pandas.pydata.org/docs/reference/api/pandas.plotting.deregister_matplotlib_converters.html

### Documentation problem

I'm adding examples to the docs. I would like to make sure that these methods are still needed.

I understand that there were some [issues](https://github.com/pandas-dev/pandas/issues/27479) in the past. They were corrected and tests were added. 

@TomAugspurger do you have ideas about good/simple examples if these are still needed? 

### Suggested fix for documentation

@MarcoGorelli and I are thinking if it wouldn't be time to deprecate them... ?

**Comment by TomAugspurger** [comment]
Looks like https://github.com/pandas-dev/pandas/issues/27036 had some more context.

As for whether or not to deprecate them, I think that depends on whether matplotlib can correctly render all of our objects without our converters. I think that period was the main one, but I'm pretty sure we also did some custom stuff with datetime and datetime tz arrays.

**Comment by DeaMariaLeon** [comment]
Added examples
