### ISSUE TITLE
Merge a subset of columns only during pd.merge

### ISSUE THREAD

**Issue by susmitpy** [pandas-dev/pandas#54381]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish I could use pandas to pull / merge / keep only specific columns during pd.merge instead of performing a merge and then later dropping unnecessary columns. 
Usecase:
Often it happens that we have to perform a left join and while performing we only need a few columns from the right dataframe. 
But by default, everything is copied over (unnecessary memory consumed?) and then unnecessary columns have to be dropped. 
Also it's a pain if there are overlapping column names as then suffixes have to be provided and columns have to be dropped by passing column names with suffixes.
So pandas merge method can be modified by taking an inspiration from SQL where user can specify the columns that needs to be there in the result.

### Feature Description

Add a new parameter to pd.merge method that let's user optionally specify which all columns are needed to be preserved/ or need to be pulled for pd.merge
Example:
```
def merge(left_cols: Optional[list[str]]=None, right_cols: Optional[list[str]]= None, ... existing parameters):
"""
left_cols: If None, all columns from the left dataframe will be present in the result. If not none, only the columns specified will be present
right_cols: If None, all columns from the right dataframe will be present in the result. If not none, only the columns specified will be present
"""
```

### Alternative Solutions

SQL Join

**Comment by JostBrand** [comment]
Thank you for your suggestion. Could you please explain in more detail where the difference is to perform pd.merge with a smaller column selection?

e.g.: 
```
pd.merge(left=df,right=df2,how="left",on="Name")
vs.
pd.merge(left=df[["Name","Age"]],right=df2[["Name","Hobby"]],how="left",on="Name")
```

Toy dataset example:

```
import pandas as pd
import random

names = ["Alice", "Bob", "Charlie", "David", "Eva"]
cities = ["New York", "Los Angeles", "Chicago", "Houston", "Miami"]

data = {
    'Name': [random.choice(names) for _ in range(10)],
    'Age': [random.randint(20, 60) for _ in range(10)],
    'City': [random.choice(cities) for _ in range(10)],
    'Salary': [random.randint(40000, 100000) for _ in range(10)]
}

df = pd.DataFrame(data)

hobbies = ["Reading", "Swimming", "Gaming", "Hiking", "Cooking"]
education = ["High School", "Bachelor's", "Master's", "PhD"]

data2 = {
    'Name': random.sample(names, 5), 
    'Hobby': [random.choice(hobbies) for _ in range(5)],
    'Education': [random.choice(education) for _ in range(5)]
}

df2 = pd.DataFrame(data2)
```
