### ISSUE TITLE
BUG: to_datetime does not require leading zeroes when using format = '%Y%m%d'

### ISSUE THREAD

**Issue by LasseDamtoft** [pandas-dev/pandas#54402]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
timestamp = pd.to_datetime('202312', format='%Y%m%d')
```

### Issue Description

The issue is that %m and %d implies that the format requires leading zeros in month and day, but this is not the case. This is problematic for november and december as these will be passed without error even though they do not fit the format.

### Expected Behavior

Expectation would be for this to throw an error that can then be handled as this is a '%Y%m' formatted date.

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : 0f437949513225922d851e9581723d82120684a6
python           : 3.8.13.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_Denmark.1252
pandas           : 2.0.3
numpy            : 1.24.4
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 58.5.3
pip              : 21.3.1
Cython           : None
pytest           : 7.4.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

**Comment by MarcoGorelli** [comment]
thanks for your report - this is consistent with the python stdlib, so I'd say it's probably working as expected
```python
In [1]: dt.datetime.strptime('202312', '%Y%m%d')
Out[1]: datetime.datetime(2023, 1, 2, 0, 0)

In [2]: pd.to_datetime('202312', format='%Y%m%d')
Out[2]: Timestamp('2023-01-02 00:00:00')
```

**Comment by LasseDamtoft** [comment]
Sorry to bother, I guess the format '%Y%m' is just comes with this inherent danger then.

**Comment by MarcoGorelli** [comment]
that's right

closing then, but thanks for your issue!
