### ISSUE TITLE
DOC: 

### ISSUE THREAD

**Issue by IsmaelMiranda11** [pandas-dev/pandas#54439]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.json_normalize.html

### Documentation problem

Function json_normalize returns a dataframe with no relation with original dataframe.
In my use cases, I always need to join with previous.

### Suggested fix for documentation

I believe that the pipe using json_normalize could help users

df = ( 
    df
    .pipe(lambda df: df.join(pd.json_normalize(df['column_with_json'])))
)

**Comment by IsmaelMiranda11** [comment]
I've noticed that index won't keep the same, so

```
df = ( 
          df
          .pipe ( lambda df: df.join(pd.json_normalize(df['column_with_json']).set_index(df.index)))
)
```

**Comment by mroeschke** [comment]
Thanks for the issue but there's not enough context here to know what to add to the documentation. Closing but feel free to open a new issue with more context
