### ISSUE TITLE
Upload Python 3.12 wheel to scientific-python-nightly-wheels?

### ISSUE THREAD

**Issue by lesteve** [pandas-dev/pandas#54447]
Is there a chance that Python 3.12 wheels get uploaded to scientific-python-nightly-wheels i.e. 
https://anaconda.org/scientific-python-nightly-wheels/pandas/files?

This would be useful for scikit-learn as we would like to build and test Python 3.12 wheels and we currently install pandas when we test wheels (pandas is an optional scikit-learn dependency). Numpy and scipy already upload a Python 3.12 wheel, see https://anaconda.org/scientific-python-nightly-wheels/numpy/files and https://anaconda.org/scientific-python-nightly-wheels/scipy/files.

In #53743 a Python 3.12 entry was added but commented out:
https://github.com/pandas-dev/pandas/blob/b864b8eb54605124827e6af84aa7fbc816cfc1e0/.github/workflows/wheels.yml#L96-L97

I am willing to have a go at a PR, but I thought I would ask in an issue first.

**Comment by lithomas1** [comment]
Hi @lesteve,
Sorry for the wait. Currently, we're waiting on numpy 1.26 to release wheels for pandas.

I think the numpy folks promised us that 1.26 would come out when Python 3.12rc1 is out 
(that was yesterday I think, so 1.26 should be out any day now). 
https://github.com/numpy/numpy/issues/23808#issuecomment-1599686864

**Comment by lesteve** [comment]
OK thanks, it makes sense to wait for numpy 1.26 if it is happening soonish.

**Comment by maharris77** [comment]
numpy 1.26.0b1 is available.

**Comment by lithomas1** [comment]
Just put up #55010.

The plan is to have nightly wheels with that. We'll wait for numpy before officially putting out wheels in a release.
