### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by Tongzoou** [pandas-dev/pandas#54444]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import re
import os
import pandas as pd
import datetime
class DataProcessor:
    def __init__(self, input_file):
        self.input_file = input_file
    def CN_data_process(self):
        data_list = []
        data_dict = {}

        with open(self.input_file, 'r', encoding='utf-8') as file:
            lines = file.readlines()
            for line in lines:
                if line.startswith('T1'):
                    data_dict['Title'] = re.sub('T1 ', '', line.strip())
                elif line.startswith('A1'):
                    data_dict['Author'] = re.sub('A1 ', '', line.strip())
                elif line.startswith('YR'):
                    data_dict['Year'] = re.sub('YR ', '', line.strip())
                elif line.startswith('AB'):
                    data_dict['Abstract'] = re.sub('AB ', '', line.strip())
                elif line.startswith('vo'):
                    data_dict['Volume'] = re.sub('vo ', '', line.strip())
                elif line.startswith('IS'):
                    data_dict['Issue'] = re.sub('IS ', '', line.strip())
                elif line.startswith('JF'):
                    data_dict['Journal'] = re.sub('JF ', '', line.strip())
                elif line.startswith('RT'):
                    if data_dict:
                        data_list.append(data_dict)
                        data_dict = {}
        if data_dict:
            data_list.append(data_dict)
        columns_order = ['Title', 'Author', 'Year', 'Abstract', 'Volume', 'Issue', 'Journal']
        df = pd.DataFrame(data_list, columns=columns_order)
        folder_path = os.path.dirname(self.input_file)
        now = datetime.datetime.now()
        timestamp = now.strftime("%Y%m%d%H%M%S")
        output_filename = os.path.join(folder_path, f'{timestamp}_CNdata.xlsx')
        df.to_excel(output_filename, index=False)

if __name__ == '__main__':
    input_file = r"CNKI-20230806082607024.txt"
    process=DataProcessor(input_file)
    process.CN_data_process()
```

### Issue Description

When we run the code df.to_excel(output_filename, index=False), the text in the Abstract column is truncated.Here is an example of the data,Please store in a txt file.
=========================================example====================================

RT Journal Article
SR 1
A1 袁淳;肖土盛;耿春晓;盛誉;
AD 中央财经大学会计学院;中央财经大学会计学院、中国管理会计研究与发展中心;
T1 数字化转型与企业分工：专业化还是纵向一体化
JF 中国工业经济
YR 2021
IS 09
OP 137-155
K1 数字化转型;企业分工;专业化;纵向一体化;交易成本
 digital transformation;division of labor between enterprises;vertical specialization;vertical integration;transaction costs

AB 在"十四五"规划明确提出要加快数字化发展的背景下,由企业推动的数字化转型逐渐成为了学术界关注的重点。本文利用机器学习方法刻画微观企业数字化水平,并在构建数理模型的基础上实证考察了企业数字化转型对企业分工的影响及其机理。研究发现:企业数字化转型显著提升了中国上市企业专业化分工水平,并且该结论在考虑内生性问题以及一系列稳健性检验基础上仍然成立;机制分析表明,数字化转型对企业专业化分工的促进作用主要通过降低企业面临的外部交易成本来实现;数字化转型对企业专业化分工的影响具有明显的异质性,在内部管控成本较低的企业、制造业以及竞争性行业中促进效果更加显著;数字化通过促进企业专业化分工提高了企业全要素生产率。本文研究不仅揭示了数字技术的发展对企业边界的影响机理及经济后果,也为数字经济与实体经济的融合效果提供了微观证据,研究结论对于数字化相关政策的制定以及经济高质量发展具有重要的政策启示。
SN 1006-480X
CN 11-3536/F
LA 中文;
DS CNKI
IS 09
LK https://kns.cnki.net/kcms/detail/11.3536.f.20210924.1600.014.html
DO 10.19581/j.cnki.ciejournal.2021.09.007

RT Journal Article
SR 1
A1 李井林;阳镇;陈劲;崔文清;
AD 湖北经济学院会计学院;清华大学经济管理学院;清华大学技术创新研究中心;
T1 ESG促进企业绩效的机制研究——基于企业创新的视角
JF 科学学与科学技术管理
YR 2021
IS 09
vo 42
OP 71-89
K1 高质量发展;企业ESG表现;企业创新;可持续发展;企业绩效
 high quality development;ESG;corporate innovation;sustainable development;corporate performance

AB 企业如何基于可持续发展导向通过企业创新实现对多元利益相关方的价值创造成为学界关注的焦点议题。ESG是关于环境、社会以及公司治理在企业中如何实现可持续发展的一种全新理念,但是如何基于全新的可持续理念重塑企业的创新过程为企业绩效带来竞争价值的内在机理依然缺乏研究。以2010—2017年中国沪深交易所A股主板上市公司为研究样本,检验了企业ESG表现对企业绩效的影响效应,以及企业创新在企业ESG表现与企业绩效之间关系中的中介效应,并进一步检验了企业绩效水平、企业产权性质以及行业环境敏感性对企业ESG表现与企业绩效之间关系的调节效应。研究结果表明:(1)企业ESG表现及其3个维度均能显著提升企业绩效。(2)企业ESG表现及其3个维度均能显著提升企业创新水平。(3)内在机制检验结果表明企业创新在企业ESG表现及其3个维度与企业绩效之间关系存在中介效应。(4)异质性分析结果表明企业绩效水平较低的企业ESG表现及其3个维度对企业绩效的促进作用更大;非国有企业ESG表现及其3个维度对企业绩效的促进作用更大;高环境敏感性行业企业的ESG表现及其3个维度对企业绩效的影响效应更为明显。
SN 1002-0241
CN 12-1117/G3
LA 中文;
DS CNKI
IS 09

RT Journal Article
SR 1
A1 黄世忠;
AD 厦门国家会计学院;
T1 支撑ESG的三大理论支柱
JF 财会月刊
YR 2021
IS 19
OP 3-10
K1 ESG;可持续发展理论;经济外部性理论;企业社会责任理论
 

AB 随着投资者、债权人以及其他利益攸关者对ESG的信息需求与日俱增,企业提供的ESG报告呈快速增长态势。在ESG报告日益成为评价可持续发展重要信息来源的背景下,有必要梳理和研究支撑ESG的理论流派及其核心要义。近年来,与ESG相关的著述越来越多,但对于构成ESG理论基础的著述并不多见。本文认为,可持续发展理论、经济外部性理论、企业社会责任理论是共同支撑ESG的三大理论支柱。本文旨在对这三大理论支柱的核心思想进行综述,并分析它们对ESG的启示意义。
SN 1004-0994
CN 42-1290/F
LA 中文;
DS CNKI
IS 19
LK https://kns.cnki.net/kcms/detail/42.1290.F.20210831.1534.012.html
DO 10.19641/j.cnki.42-1290/f.2021.19.001

RT Journal Article
SR 1
A1 黄世忠;
AD 厦门国家会计学院;
T1 ESG理念与公司报告重构
JF 财会月刊
YR 2021
IS 17
OP 3-10
K1 环境保护;社会责任;公司治理;ESG报告;可持续发展报告;公司报告
 

AB 可持续发展近年来成为经济社会的热点问题。企业要保持可持续发展,既需要关注其经营活动对环境和社会的影响,也需要建立健全治理机制。环境、社会和治理即ESG逐渐成为评价企业可持续发展能力的核心理念和框架体系。本文在简要回顾ESG历史沿革的基础上,分析ESG报告的发展现状和存在的突出问题,并展望公司报告的发展趋势,分析ESG理念将如何重塑公司报告的架构,促使股东导向的财务报告与攸关者导向的可持续发展报告相互融合。
SN 1004-0994
CN 42-1290/F
LA 中文;
DS CNKI
IS 17
LK https://kns.cnki.net/kcms/detail/42.1290.F.20210810.1826.004.html
DO 10.19641/j.cnki.42-1290/f.2021.17.001

### Expected Behavior

i dont know。

### Installed Versions

pandas1.5.2
Python3.9.15

**Comment by Tongzoou** [comment]
![QQ图片20230807094759](https://github.com/pandas-dev/pandas/assets/116854062/f3dd71b3-3a7b-4b34-a010-ba81b9ce9c48)

**Comment by MarcoGorelli** [comment]
could you make a minimal reproducible example, set a descriptive title, and try again please? https://stackoverflow.com/help/minimal-reproducible-example

thanks - closing for now then
