### ISSUE TITLE
BUG: usecols in pandas.read_csv has incorrect behavior when using pyarrow engine

### ISSUE THREAD

**Issue by karlestira** [pandas-dev/pandas#54459]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas

df = pandas.read_csv(file, header=None, sep="\t", usecols=[0, 1, 2], dtype="string[pyarrow]", dtype_backend="pyarrow", engine="pyarrow")
```

### Issue Description

my file is like this(no header, tab delimiter):
chr1	11874	12227	chr1	11874	12227	DDX11L1:NR_046018.2:+:3:exon1
chr1	12228	12612	chr1	12228	12612	DDX11L1:NR_046018.2:+:3:intron1
chr1	12613	12721	chr1	12613	12721	DDX11L1:NR_046018.2:+:3:exon2
chr1	12722	13220	chr1	12722	13220	DDX11L1:NR_046018.2:+:3:intron2
chr1	13221	14829	chr1	14362	14829	WASH7P:NR_024540.1:-:11:exon11

when I use pyarrow engine:
df = pandas.read_csv(file, header=None, sep="\t", usecols=[0, 1, 2], dtype="string[pyarrow]", dtype_backend="pyarrow", engine="pyarrow")

I get:
TypeError: expected bytes, int found

when I use C engine: 
df = pandas.read_csv(file, header=None, sep="\t", usecols=[0, 1, 2])

I get a correct df.

I know we can use df.loc/df.iloc/df.drop or anything like these to get the same output. However, In some case, the col num in input file may be very big, so use "usecols" instead of "read all then drop some cols" is very important. 

### Expected Behavior

When using pyarrow engine, pandas.read_csv's behavior should consistent with C engine.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 0f437949513225922d851e9581723d82120684a6
python           : 3.10.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19045
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Simplified)_China.936

pandas           : 2.0.3
numpy            : 1.23.0
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 57.5.0
pip              : 22.0.4
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.9
lxml.etree       : None
html5lib         : None
pymysql          : 1.0.3
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : 12.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by hedeershowk** [comment]
take

**Comment by sjohns** [comment]
Same problem, df_temp = pd.read_csv(temp_file, usecols=[0, 1, 2, 3, 4], engine="pyarrow"), 
  File stringsource:15 in string.from_py.__pyx_convert_string_from_py_std__in_string

TypeError: expected bytes, int found
