### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by blackbox-tech** [pandas-dev/pandas#54481]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
pd.to_datetime("2023/04/27 12:33:24 BST")
```

### Issue Description

Since pandas >=2.0.0 the datetime conversion functions have stopped working as before.  If they are no longer supposed to work as before, or if new arguments can be passed to the functions to make them back them backwards compatible, it is not at all clear from the current documentation.

```python
import pandas as pd
pd.to_datetime("2023/04/27 12:33:24 BST")
```

Fails with the Exception:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paul/.conda/envs/pandas_test/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 1084, in to_datetime
    result = convert_listlike(np.array([arg]), format)[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/.conda/envs/pandas_test/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 455, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/.conda/envs/pandas_test/lib/python3.11/site-packages/pandas/core/arrays/datetimes.py", line 2177, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/tslib.pyx", line 402, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 527, in pandas._libs.tslib.array_to_datetime
AttributeError: 'NoneType' object has no attribute 'total_seconds'
```

I waited as I thought this bug might be related to another issue that was scheduled to be been fixed in v2.0.3, but this still appears to remain an issue in the latest code.

### Expected Behavior

```
Timestamp('2023-04-27 12:33:24+0100', tz='pytz.FixedOffset(60)')
```

### Installed Versions

```
pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : 0f437949513225922d851e9581723d82120684a6
python           : 3.11.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.17-2102.200.13.el8uek.x86_64
Version          : #2 SMP Sun Mar 28 14:48:36 PDT 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.3
numpy            : 1.25.2
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 68.0.0
pip              : 23.2.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None
```

**Comment by Cyddharth-Gupta** [comment]
@blackbox-tech The issue with the code pd.to_datetime("2023/04/27 12:33:24 BST") is that the pd.to_datetime() function does not directly support parsing time zone abbreviations like "BST." The pd.to_datetime() function requires a recognized format or a specified format string to parse datetime strings accurately.

To fix this issue, you should remove the time zone abbreviation before passing the string to pd.to_datetime(), and then specify the appropriate format. Here's an example of how you can do this:
`import pandas as pd

# Remove the time zone abbreviation
datetime_string = "2023/04/27 12:33:24 BST".replace(" BST", "")

# Specify the format and parse the datetime
result = pd.to_datetime(datetime_string, format='%Y/%m/%d %H:%M:%S', errors='coerce')
print(result)
`
In this example, the %Y/%m/%d %H:%M:%S format string is used to specify the expected format of the datetime string. The errors='coerce' parameter ensures that any parsing errors will result in a NaT (Not a Timestamp) value.

If you have a datetime string with time zone information, consider using the pytz library or other timezone-handling approaches to properly handle time zones during the parsing process.

**Comment by jenno-verdonck** [comment]
I tried the same code with pandas 2.0.3 on python 3.9.16 and got the following result.

```
UnknownTimezoneWarning: tzname BST identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  warnings.warn("tzname {tzname} identified but not understood.  "
Timestamp('2023-04-27 12:33:24')
```

**Comment by Cyddharth-Gupta** [comment]
@jenno-verdonck refer to my reply to @blackbox-tech

**Comment by jenno-verdonck** [comment]
@Cyddharth-Gupta It is just strange that I got a proper warning explaining the problem while @blackbox-tech got an `AttributeError`.

**Comment by Cyddharth-Gupta** [comment]
> @Cyddharth-Gupta It is just strange that I got a proper warning explaining the problem while @blackbox-tech got an `AttributeError`.

I doubt which version is being used by @blackbox-tech 
2.0.3 onwards it is supposed to give a warning as far as I remember.

**Comment by blackbox-tech** [comment]
I do see a warning saying it is deprecated and will raise in a future version, but the issue was that it raises an exception in >=2.0.0 despite the warning.  It's completely fair if this function is no longer intended to be backwards compatible as this issue occurred after pandas changed major version.  If this is the case I will implement another datetime conversion function.

I will close this issue, if this behaviour is intentional.

**Comment by jenno-verdonck** [comment]
@blackbox-tech The fact that you get an exception seems to already have been reported here #54479. Seems to be the same exception. Nobody seems to be able to reproduce it at the moment.

**Comment by blackbox-tech** [comment]
@jenno-verdonck I see, so this is in fact a bug because it should currently work, albeit with a warning.  I'm running on Linux, and I can reproduce the problem from a vanilla python 3.11 conda environment with ```conda install pandas=2.0.3"

My work around is to convert the to a datetime is:
```python
import zoneinfo
from dateutil.parser import parse

tzinfos = {tz: zoneinfo.ZoneInfo(tz) for tz in zoneinfo.available_timezones()}
parse("2023/04/27 12:33:24 BST", tzinfos=tzinfos)
```

**Comment by asishm-wk** [comment]
@blackbox-tech What Linux version/Architecture are you running on? On the other thread, people are having a hard time reproducing.

**Comment by blackbox-tech** [comment]
@asishm-wk I using a vanilla conda environment on Linux (so the distro should not make a difference). 

Looking at the stack-trace, I think the issue is most likely to either be related to the dateutil parser.  Essentially the issue is that the dateutil parser is not aware of the "BST" timezone and it's not passed in the tzinfos which provides additional timezones.

The version I have in my conda env is the latest ```dateutil 2.8.2```, but this release is stable and a couple years old now so I doubt its a change to the dateutil package that is the issue.  Also if I use the same version of datetutils with ```pandas 1.5.3```, I don't get this exception, its only appears to happen with ```pandas >=2.0.0```

I have implemented an alternative solution now, (as ultimately supporting timezones in this pandas function appears to be deprecated moving forward), so I'm happy if you want to ignore this issue.  However, I hope this information is useful if is affecting other users or if it is related to on-going investigating of another issue.
