### ISSUE TITLE
BUG: TypeError when try to type hint generic type `pd.Series`

### ISSUE THREAD

**Issue by Andy-Dihong-Luo** [pandas-dev/pandas#54494]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

def some_func(data: pd.Series[float]) -> None:
    return
```

### Issue Description

A TypeError when I try to type hint the input of function (a `pd.Series` with `float` dtype). CPython version is 3.11.4 (conda). 

```
TypeError                                 Traceback (most recent call last)
Cell In[16], line 1
----> 1 def some_func(data: pd.Series[float]) -> None:
      2     return

TypeError: type 'Series' is not subscriptable
```

### Expected Behavior

There should not be any errors. The type hint should be considered correct (at least to me, and also to Pylance, the type checking tool). 

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 0f437949513225922d851e9581723d82120684a6
python           : 3.11.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19045
machine          : AMD64
processor        : AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Simplified)_China.936

pandas           : 2.0.3
numpy            : 1.25.1
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 68.0.0
pip              : 23.2.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.1.2
lxml.etree       : 4.9.3
html5lib         : 1.1
pymysql          : 1.4.6
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.14.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : 1.0.9
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : 2.0.19
tables           : None
tabulate         : 0.9.0
xarray           : None
xlrd             : 2.0.1
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by thehsansaeed** [comment]
By using the Union type from the typing module to specify the type hint for the pd.Series parameter. Here's how you can modify your code:

import pandas as pd
from typing import Union

def some_func(data: Union[pd.Series[float]]) -> None:
    return

This workaround should allow you to specify the type hint for a pd.Series with a float dtype without encountering the TypeError.

**Comment by thehsansaeed** [comment]
By using the Union type from the typing module to specify the type hint for the pd.Series parameter. Here's how you can modify your code:

import pandas as pd
from typing import Union

def some_func(data: Union[pd.Series[float]]) -> None:
    return

**Comment by twoertwein** [comment]
[Pandas-stubs](https://github.com/pandas-dev/pandas-stubs) defines `pd.Series` as generic. The actual `pd.Series` in pandas is not generic.

I think you have three choices:

1. use "pd.Series[float]"
2. `from __future__ import annotations` that should prevent the runtime evaluation of your annotation
3. open a PR to make `pd.Series` generic (this will take quite a bit of effort&time)

**Comment by inad9300** [comment]
@andyluooo perhaps what @twoertwein meant was to use `"Series[float]"`, quotes included (see, for example, https://stackoverflow.com/a/77476173/2018219).
