### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'VisibleDeprecationWarning' (numpy 2.0.dev)

### ISSUE THREAD

**Issue by pllim** [pandas-dev/pandas#54505]
https://github.com/pandas-dev/pandas/blob/49ca01ba9023b677f2b2d1c42e99f45595258b74/pandas/core/common.py#L241

Numpy: 2.0.0.dev0+778.ga2bfa54f8

**Comment by lithomas1** [comment]
What pandas are you on?

This is fixed on main (and the 2.1rc I think)
by https://github.com/pandas-dev/pandas/pull/54405

**Comment by pllim** [comment]
Thanks for the clarification! I was using stable and I misunderstood the `if` right above that line. 

I will pull pandas from your dev wheel and see.
