### ISSUE TITLE
BUG: Changing dtype from pandas==2.0.1 to 2.0.2/2.0.3

### ISSUE THREAD

**Issue by AlexanderJuestel** [pandas-dev/pandas#54519]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
Installing GemPy using `pip install gempy` and installing pandas==2.0.2 separately. The code below will result in an error that is caused by the different values in the DataFrames shown below


import gempy as gp
geo_model = gp.create_model('Graben_Model')
geo_model
```

### Issue Description

Hello, 
I am one of the maintainers of the [GemPy](https://github.com/cgre-aachen/gempy) package. We noticed that our package breaks when using the two latest versions 2.0.2 and 2.0.3. Everything still works fine using 2.0.1. 

I have not been able to create a reproducible example yet. I, therefore, attached two screenshots where the change from the older to the newer version becomes apparent. Our package fails when using the displayed DataFrame. The API of GemPy has not changed between the different versions of pandas. The NumPy version is also identical (1.25.2). 

I would expect that our package would not break after these minor version changes. I also checked the Release Notes but could not find anything that would explain this change in behavior. 

Using pandas==2.0.1
![image](https://github.com/pandas-dev/pandas/assets/45469915/c0e30962-f26a-4943-a3f0-72a8da1934f8)

Using pandas==2.0.2
![image](https://github.com/pandas-dev/pandas/assets/45469915/2e16225a-5487-4c6c-b2d5-44ba21211a3b)

### Expected Behavior

I would pandas==2.0.2 expect not to break. 

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 965ceca9fd796940050d6fc817707bba1c4f9bff
python           : 3.10.12.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19045
machine          : AMD64
processor        : AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : de_DE.cp1252

pandas           : 2.0.2
numpy            : 1.25.2
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 68.0.0
pip              : 23.2.1
Cython           : None
pytest           : 7.4.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.14.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.11.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 2023.7.0
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : 2.3.1
pyqt5            : None

</details>

**Comment by AlexanderJuestel** [comment]
I narrowed the issue down to the following line of code (for the respective column): 

```
 self.df.at['values', 'len series surface_points'] = len_series_i
```

https://github.com/cgre-aachen/gempy/blob/f796e521ff631964cfbcd22a16959a81cbe7c346/gempy/core/structure.py#L110

I am going into the line with `len_series_i = np.array([0])`. With pandas==2.0.1, I am getting the same result (=`np.array([0])`). With pandas==2.0.2, I am getting `np.array(0)`. 

Is it possible that `df.at[...]` is changing the type or the shape somehow?

**Comment by mroeschke** [comment]
Thanks for the report, but unfortunately we would need a more minimal example in order to diagnose and potentially add a unit test to ensure the bug was fixed. Closing but feel free to open a new issue if you have the time to minimize.
