### ISSUE TITLE
ENH: merge inplace

### ISSUE THREAD

**Issue by s2t2** [pandas-dev/pandas#54531]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Given pandas provides an `inplace` parameter on many of its operations, I would like to merge inplace, like:

```py
df.merge(other_df, left_on="user_id", right_on="user_id", inplace=True)
```

But right now the `merge` function doesn't have an `inplace` parameter, so we currently need to do:

```py
df = df.merge(other_df, left_on="user_id", right_on="user_id")
```

I would like to propose we add an `inplace` parameter to the [`DataFrame.merge` function](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html).

### Feature Description

Desired invocation:

```py
df.merge(other_df, left_on="user_id", right_on="user_id", inplace=True)
```

### Alternative Solutions

Alternatively, if not possible, for example if there is some reason why adding this parameter is not performant, it would be helpful to know what the limitations are.

**Comment by jreback** [comment]
-1 inplace is depreciated an no expansion

**Comment by jorisvandenbossche** [comment]
The `inplace` keyword is not deprecated _yet_, but we are planning to do that soon. See the current proposal to do so at https://github.com/pandas-dev/pandas/pull/51466

> Alternatively, if not possible, for example if there is some reason why adding this parameter is not performant, it would be helpful to know what the limitations are.

Such a potential inplace keyword would not make it any more performant, it would just be syntactic sugar to not have to reassign it to the same variable name (it would do _exactly_ the same as `df = df.merge(other_df)` under the hood). While an inplace keyword might give the impression that it's better, it doesn't actually help.

**Comment by lithomas1** [comment]
closing, this can only be done inplace if it is a no-op (and that case is covered by Copy on Write).
