### ISSUE TITLE
DOC: axis=None does not aggregate along both axes for sum method

### ISSUE THREAD

**Issue by Ishticode** [pandas-dev/pandas#54547]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sum.html

### Documentation problem

The comment under axis parameter states:

_**`For DataFrames, specifying axis=None will apply the aggregation across both axes.`**_

However the following code seems to suggest otherwise.
``` python
import pandas as pd, numpy as np
a = np.arange(6).reshape((3, 2))
df = pd.DataFrame(a, index=list("abc"), columns=list("xy"))
print(df.sum(axis=None)) # or df.sum()
```
which returns

```
x    6
y    9
dtype: int64
```
and seems to sum just along the row as if we had specified `axis="index"`.

In additon to this, the return statement for the sum docs linked above says _**`scalar or series`**_. If the above case does not return a scalar then I can't see when it will be scalar otherwise.

Note: 
1) This behaviour is diffierent to numpy.ndarray.sum which would return a scalar value of 15.
2) This behaviour is also found amongst other similar df methods like `mean`.

### Suggested fix for documentation

remove 
`For DataFrames, specifying axis=None will apply the aggregation across both axes.`
or 
make the methods match numpy behaviour which is perhaps a breaking change.

**Comment by jbrockmendel** [comment]
The current behavior is deprecated; in 3.0 explicitly passing axis=None will sum across both axes.  A PR making the documentation more clear in the interim would be welcome.

**Comment by nox1134** [comment]
Hii ! I'm new to open source and would like to work on this issue. How do I get started?

**Comment by adnan2232** [comment]
take

**Comment by selehadin-cyber** [comment]
Hi @rhshadrach 

can you assign me this? can do a quick PR
thanks in advance

**Comment by Brooklynn29** [comment]
take

**Comment by nox1134** [comment]
I've set up the environment and installed all dependencies, but I'm unsure how to edit docstrings. Should i create a new function and override the the existing sum method?

**Comment by salujaditi14** [comment]
@Ishticode , @jbrockmendel , @Brooklynn29 ,  Do you guys would like to look into this PR?

https://github.com/pandas-dev/pandas/pull/54681

**Comment by haleematallat** [comment]
take

**Comment by natmokval** [comment]
I would like to work on it.
