### ISSUE TITLE
ENH: support using letters as column names in read_excel

### ISSUE THREAD

**Issue by wangxiya** [pandas-dev/pandas#54552]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

目前，如果head=None，则dataframe的column为1,2,3,4，……

Currently, if header=None, the column names are "1, 2, 3, 4, ......" by default.

### Feature Description

建议加入一个参数，在head=None时，可以将dataframe的column设置A,B,C,D，……

Add another parameter so that when header=None, users can set the column name to "A, B, C, D, ......"

### Alternative Solutions

无

None

**Comment by fangchenli** [comment]
I added the English translation but have no comments on the suggestion itself.

**Comment by fangchenli** [comment]
Use the `names` parameter?

**Comment by rmhowe425** [comment]
@rhshadrach Does this issue require further discussion or can I work on creating a PR?

**Comment by rhshadrach** [comment]
@rmhowe425 - what do you think proper resolution of this issue would entail?

**Comment by rhshadrach** [comment]
I'm currently -1 here, users are able to do this via:

```
def number_to_excel_name(idx):
    if idx < 0:
        raise ValueError("Index must be nonnegative")
    result = ""
    while idx > -1:
        idx, r = divmod(idx, 26)
        result = chr(r + ord('A')) + result
        idx -= 1
    return result


df = pd.DataFrame(columns=range(0, 100))
df.columns = [number_to_excel_name(idx) for idx in df.columns]
```

**Comment by phofl** [comment]
agree with @rhshadrach here, closing
