### ISSUE TITLE
BUG: df.iloc[(slice,)] changed behavior in pandas 2.1.0rc0

### ISSUE THREAD

**Issue by flying-sheep** [pandas-dev/pandas#54622]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.
- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd, numpy as np
df = pd.DataFrame(np.random.rand(10, 8))
print(df.iloc[(slice(None, None, 2),)].shape)
```

### Issue Description

Since 2.1.0rc0, the code above slices the second axis instead of the first, and prints:

```
(10, 4)
```

### Expected Behavior

I expect the code to slice the first axis and print:

```
(5, 8)
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : 6e194cf9eadedbf5506da5ba0939d700f46ba3ba
python              : 3.10.12.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 6.4.10-zen2-1-zen
Version             : #1 ZEN SMP PREEMPT_DYNAMIC Sun, 13 Aug 2023 01:33:59 +0000
machine             : x86_64
processor           : 
byteorder           : little
LC_ALL              : None
LANG                : de_DE.UTF-8
LOCALE              : de_DE.UTF-8

pandas              : 2.1.0rc0
numpy               : 1.24.4
pytz                : 2023.3
dateutil            : 2.8.2
setuptools          : 68.1.0
pip                 : 23.2.1
Cython              : None
pytest              : 7.4.0
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : None
pandas_datareader   : None
bs4                 : None
bottleneck          : None
brotli              : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : 2023.6.0
gcsfs               : None
matplotlib          : 3.7.2
numba               : 0.57.1
numexpr             : None
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.2
snappy              : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by rhshadrach** [comment]
git bisect shows

```
4f4184d90135c9e890d5124df547dcfff51bacec is the first bad commit
commit 4f4184d90135c9e890d5124df547dcfff51bacec
Author: Patrick Hoefler <61934744+phofl@users.noreply.github.com>
Date:   Thu May 4 19:43:38 2023 +0200
```

cc @phofl

**Comment by phofl** [comment]
I’ll take a look, can you link the pr number as well in the future?

**Comment by rhshadrach** [comment]
Updated.

**Comment by phofl** [comment]
I've got to say I am very confused that we don't have tests for this ourselves
