### ISSUE TITLE
BUG: Install error with Apple ARM and poetry

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [pandas-dev/pandas#54644]
I get error on Apple ARM with command `poetry add pandas`.

Switching terminal to Rosetta https://stackoverflow.com/a/65612610 and other answers do not work.

```
Using version ^2.0.3 for pandas

Updating dependencies
Resolving dependencies... (0.5s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing pandas (2.0.3): Failed

  RuntimeError

  Hash for pandas (2.0.3) from archive pandas-2.0.3-cp310-cp310-macosx_11_0_arm64.whl not found in known hashes (was: sha256:c5a43245e90381e5127a7740c7e9067078f83189f0ec770461c40e7513e494f7)

  at ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/executor.py:818 in _validate_archive_hash
      814│         archive_hash: str = "sha256:" + get_file_hash(archive)
      815│         known_hashes = {f["hash"] for f in package.files if f["file"] == archive.name}
      816│ 
      817│         if archive_hash not in known_hashes:
    → 818│             raise RuntimeError(
      819│                 f"Hash for {package} from archive {archive.name} not found in"
      820│                 f" known hashes (was: {archive_hash})"
      821│             )
      822│ 

```

Poetry (version 1.5.1)
Python 3.10.5

**Comment by lithomas1** [comment]
I don't use poetry but could you try clearing your cache and see if that helps?

**Comment by ValeryVerkhoturov** [comment]
> I don't use poetry but could you try clearing your cache and see if that helps?

The same error after `poetry cache clear --all .`

**Comment by lithomas1** [comment]
Hm,
maybe you can try opening an issue on the poetry project tracker?

The error message isn't too informative and googling isn't really showing anything helpful.

I would guess that there's something wrong with your local environment as opposed to the uploaded wheels on PyPI, but that's just speculation on my part.

**Comment by ValeryVerkhoturov** [comment]
It was fixed after poetry reinstall.
