### ISSUE TITLE
BUG: read_pickle omit timezone when reading old pickle

### ISSUE THREAD

**Issue by Itayazolay** [pandas-dev/pandas#54659]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
# In python 3.7, pandas==0.24.2
pd.to_pickle(pd.Timestamp('2023-01-01', tz='UTC'), '/tmp/ts.p')

# In python 3.10, pandas==2.0.3
pd.read_pickle('/tmp/ts.p')  # Timestamp('2023-01-01 00:00:00') - no timezone information
```

### Issue Description

Reading pickle from previous version doesn't keep timezone information

### Expected Behavior

timestamps should be deserialized with timezone information

### Installed Versions

3.7:
<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.12.final.0
python-bits: 64
OS: Linux
OS-release: 6.2.0-26-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 7.4.0
pip: 22.0.4
setuptools: 67.5.1
Cython: None
numpy: 1.17.0
scipy: 1.2.1
pyarrow: 2.0.0
xarray: 0.14.1
IPython: 7.32.0
sphinx: None
patsy: 0.5.2
dateutil: 2.8.2
pytz: 2022.1
blosc: None
bottleneck: None
tables: 3.6.1
numexpr: 2.7.0
feather: None
matplotlib: 3.3.2
openpyxl: 3.0.9
xlrd: 1.2.0
xlwt: None
xlsxwriter: None
lxml.etree: 4.8.0
bs4: 4.10.0
html5lib: 1.1
sqlalchemy: 0.7.10
pymysql: None
psycopg2: None
jinja2: 3.0.3
s3fs: None
fastparquet: None
pandas_gbq: 0.13.2
pandas_datareader: None
gcsfs: 0.7.1

</details>
3.10:
<details>
INSTALLED VERSIONS
------------------
commit           : 37ea63d540fd27274cad6585082c91b1283f963d
python           : 3.10.11.final.0
python-bits      : 64
OS               : Linux
OS-release       : 6.2.0-26-generic
Version          : #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8
pandas           : 2.0.1
numpy            : 1.25.2
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 57.5.0
pip              : 22.3.1
Cython           : 0.29.36
pytest           : 7.3.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.1.2
lxml.etree       : 4.9.3
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.13.2
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : 1.3.7
brotli           : 
fastparquet      : None
fsspec           : 2023.6.0
gcsfs            : 2023.6.0
matplotlib       : 3.7.2
numba            : None
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : 0.17.9
pyarrow          : 9.0.0
pyreadstat       : None
pyxlsb           : 1.0.10
s3fs             : None
scipy            : 1.10.1
snappy           : 
sqlalchemy       : None
tables           : 3.8.0
tabulate         : None
xarray           : 2023.6.0
xlrd             : 2.0.1
zstandard        : 0.21.0
tzdata           : 2023.3
qtpy             : None
pyqt5            : None
</details>

**Comment by twoertwein** [comment]
This might be a pandas version incompatibility (0.24.2 vs. 2.0.3)? I don't know how far pandas aims to be backward compatible, but 0.24.2 seems rather old.

**Comment by mroeschke** [comment]
I don't believe pandas guarantees backward compatibility for pickles that old unfortunately so closing
