### ISSUE TITLE
BUG: read_csv columns dtype retention

### ISSUE THREAD

**Issue by vijayakumarpattanashetti** [pandas-dev/pandas#54665]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.read_csv("numerals.csv")
df.drop_duplicates().count()
len(df['leading0_col'].unique().tolist())
```

### Issue Description

When a csv file containing one or more numeric datatype columns with leading zeros, the read_csv() method reads by trimming the leading zeros.

### Expected Behavior

When a csv file containing one or more numeric-castable datatype columns with leading zeros, the read_csv() method should read as str dtype without casting to numeric as it trims the leading zeros unless user specifies through an additional parameter(maybe a new feature - cast=True).

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 0f437949513225922d851e9581723d82120684a6
python           : 3.10.9.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 22.4.0
Version          : Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 2.0.3
numpy            : 1.23.5
pytz             : 2022.7
dateutil         : 2.8.2
setuptools       : 65.6.3
pip              : 22.3.1
Cython           : None
pytest           : 7.1.2
hypothesis       : None
sphinx           : 5.0.2
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.10.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.5
brotli           : 
fastparquet      : None
fsspec           : 2022.11.0
gcsfs            : None
matplotlib       : 3.7.0
numba            : 0.56.4
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.0
snappy           : 
sqlalchemy       : 1.4.39
tables           : 3.7.0
tabulate         : 0.8.10
xarray           : 2022.11.0
xlrd             : None
zstandard        : 0.19.0
tzdata           : 2023.3
qtpy             : 2.2.0
pyqt5            : None

</details>

**Comment by jesse-sealand** [comment]
Clarification: are you expecting the column dtype to remain nueric and keep leading zeroes?

**Comment by vijayakumarpattanashetti** [comment]
Expecting all the columns' dtype to remain str since the data is loaded from csv unless user wants (maybe with a new feature - read_csv(cast=True). Even then there is flexibility to cast later. But currently when read_csv reads a str dtype column with leading zeroes, it reads that column as numeric and trims the leading zeroes due to which there is no scope for recovering the exact raw data.

**Comment by DavidToneian** [comment]
You can use
`df = pd.read_csv("numerals.csv", dtype=str)`
to have all columns be interpreted as strings and avoid loss of leading zeroes.

Let me know whether this solves your issue. If it does not, please elaborate and supply an example csv file. Thanks!

**Comment by vijayakumarpattanashetti** [comment]
yes, this solves the issue. Thanks.
