### ISSUE TITLE
BUG: is_string_dtype(pd.Index([], dtype='O')) returns `False`

### ISSUE THREAD

**Issue by flying-sheep** [pandas-dev/pandas#54661]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.
- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
from pandas.api.types import is_string_dtype

assert is_string_dtype(pd.Index([], dtype='O'))
```

### Issue Description

For object arrays it tests if all objects are strings. That test should be successful when 0 items are tested.

### Expected Behavior

The assertion succeeds.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : 6e194cf9eadedbf5506da5ba0939d700f46ba3ba
python              : 3.10.12.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 6.4.10-zen2-1-zen
Version             : #1 ZEN SMP PREEMPT_DYNAMIC Sun, 13 Aug 2023 01:33:59 +0000
machine             : x86_64
processor           : 
byteorder           : little
LC_ALL              : None
LANG                : de_DE.UTF-8
LOCALE              : de_DE.UTF-8

pandas              : 2.1.0rc0
numpy               : 1.24.4
pytz                : 2023.3
dateutil            : 2.8.2
setuptools          : 68.1.0
pip                 : 23.2.1
Cython              : None
pytest              : 7.4.0
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : None
pandas_datareader   : None
bs4                 : None
bottleneck          : None
brotli              : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : 2023.6.0
gcsfs               : None
matplotlib          : 3.7.2
numba               : 0.57.1
numexpr             : None
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.2
snappy              : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by jesse-sealand** [comment]
Referring to:
https://github.com/pandas-dev/pandas/blob/61e54c2025ad8cbd63ad0919fb7447b25592d538/pandas/core/dtypes/common.py#L137

  is_object_dtype(np.array([], dtype=object))
  True

The Object dtype can be a mix of other dtypes. It's not exclusive to strings. "All strings are objects but not all objects are strings."

**Comment by flying-sheep** [comment]
I’m aware. As I said:

> For object arrays it tests if all objects are strings. That test should be successful when 0 items are tested.

**Comment by jesse-sealand** [comment]
Similar issue of #54656

**Comment by flying-sheep** [comment]
Only in that both are about `is_string_dtype`. I think the bug you linked is invalid. The issue author just didn’t realize that passing an actual string to it causes it to be interpreted as a dtype specification (like the argument passed to `dtype('O')`).

**Comment by natmokval** [comment]
I would like to work on this.

**Comment by Jamshaid1988** [comment]
df_temp['UsageBand'] = df_temp['UsageBand'].astype("string")
pd.api.types.is_string_dtype(df_temp['UsageBand'])

Hello, I am a student of data science.
Will this effect our model if we replace the object with the string?
