### ISSUE TITLE
DOC: 

### ISSUE THREAD

**Issue by sshourie** [pandas-dev/pandas#54715]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.melt.html

### Documentation problem

When ```value_name ``` is an existing column name, a ValueError is raised. The args documentation doesn't mention this.

### Suggested fix for documentation

Update the ```value_name``` documentation from:  
```
value_name: scalar, default ‘value’
Name to use for the ‘value’ column.
```

to something like 
```
value_name: scalar, default ‘value’
Name to use for the ‘value’ column. Can't be an existing column name
```

**Comment by thiagogquinto** [comment]
Hello, I'm new to the open-source contributing community, I know that this little change isn't much, but I think that by contributing with that change would help me to understand how to make contributions.  Therefore, if that's ok,  could you assign me to this issue?

**Comment by thiagogquinto** [comment]
take

**Comment by thiagogquinto** [comment]
Hello, I took this task because I am new in the open source community, therefore I thought that would be good to get a simple one, but I am not being able to find the doc to update, could you help me to find it? But only if you already know where to look.

**Comment by Moisan** [comment]
@thiagogquinto a search of `Name to use for the ‘value’ column.` in the repository will point you to [these lines](https://github.com/pandas-dev/pandas/blob/main/pandas/core/shared_docs.py#L215-L216).

**Comment by thiagogquinto** [comment]
Thanks @Moisan, but I made the change and the when I run `python scripts/validate_docstrings.py pandas.DataFrame.melt`, but the document is checked without my changes,  I have looked around and found nothing that could indicate the reason of that, could you help me?

**Comment by thiagogquinto** [comment]
Hey @Moisan, at your time, could you take a look in #54782, please?
