### ISSUE TITLE
DOC: `pandas.DataFrame.to_sql` does not document that it creates a table index for index columns

### ISSUE THREAD

**Issue by mattatark** [pandas-dev/pandas#54712]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.to_sql.html#pandas.DataFrame.to_sql

### Documentation problem

As far as I can tell, `pandas.DataFrame.to_sql` creates a table index when creating a table and including the index of the dataframe. This is unexpected, and undocumented. See [this line](https://github.com/pandas-dev/pandas/blob/a44a8e12d1cd7b99a63f68f9ae0f5b51cd867782/pandas/io/sql.py#L1208) that I believe is responsible for this. Here's [a link](https://docs.sqlalchemy.org/en/20/core/metadata.html#sqlalchemy.schema.Column.params.index) to the relevant SQLAlchemy docs for that constructor input.

### Suggested fix for documentation

I'd recommend updating the text field for the `index` input:

> Write DataFrame index as a column. Uses index_label as the column name in the table. Creates a table index for this column.

Or something like that. I DO think that this behavior is generally undesired and should be removed, or have an input that should default to False, but at least documenting it will save others from hours of time looking through the code base to figure this out.

**Comment by samukweku** [comment]
It has an `index=True` parameter by default and the doc states that it writes the index as a column

**Comment by pauluhlenbruck** [comment]
take

**Comment by pauluhlenbruck** [comment]
I will start working on this issue during the upcoming weekend.
