### ISSUE TITLE
ENH: make guess_datetime_format public

### ISSUE THREAD

**Issue by joefutrelle** [pandas-dev/pandas#54727]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Pandas can infer datetime formats when parsing datetimes, but does not provide access to the inferred format via a public API.

### Feature Description

Currently, `guess_datetime_format` is in `pandas.core.tools.datetimes` which is not public. Exporting it from a non-private module would address the issue.

### Alternative Solutions

As far as I can tell, no other Python library provides this requested feature.

### Additional Context

As discussed in https://github.com/dateutil/dateutil/issues/1138

**Comment by MarcoGorelli** [comment]
sounds good - fancy making a pull request?

**Comment by nikhilreddy2002** [comment]
take

**Comment by joefutrelle** [comment]
If I read this correctly, the export from `pandas.core.tools.datetimes` is [here](https://github.com/pandas-dev/pandas/blob/1ecfa6749d07a08d501d56b98ae60d483cf1078f/pandas/core/tools/datetimes.py#L36) and the implementation is [here](https://github.com/pandas-dev/pandas/blob/1ecfa6749d07a08d501d56b98ae60d483cf1078f/pandas/_libs/tslibs/parsing.pyx#L867).

**Comment by nikhilreddy2002** [comment]
Hey @joefutrelle ,
From what I understood the `guess_datetime_format` should be moved to `pandas.core.tools.datetimes`, is this correct or is there some other place it should be. Or should I create a wrapper in `pandas.core.tools.datetimes` which uses `guess_datetime_format`  internally?

**Comment by joefutrelle** [comment]
According to the docs, everything in `pandas.core.*` is private, so it would need to go somewhere else. `to_datetime` is at the top level and because this is related it could go there but I would defer to core developers on where the appropriate place for datetime utilities is.

> The pandas.core, pandas.compat, and pandas.util top-level modules are PRIVATE. Stable functionality in such modules is not guaranteed.

**Comment by MarcoGorelli** [comment]
How about adding `pandas.api.tools`, and putting this in there?

**Comment by MarcoGorelli** [comment]
As suggested on Slack by @mroeschke , `pandas.tseries` might be a better place

**Comment by Birger9** [comment]
Hi! Is see that @nikhilreddy2002 is assigned to this issue. But I can't see any activity the last week. I would like to start contributing to this project. I'm studying an open source course at University that requires us to get involved in an open source project. So I would love to contribute to Pandas codebase :) And this issue seems like a good start for me @joefutrelle

**Comment by MarcoGorelli** [comment]
Sure go ahead thanks

**Comment by nnlnr** [comment]
👋 Hi there @Birger9, I hope you're doing well. I noticed that this issue hasn't seen any recent activity, and was wondering if you were still working on it? If not, would it be alright if I picked it up?

**Comment by MarcoGorelli** [comment]
feel free to submit a pull request

**Comment by nnlnr** [comment]
ok great - thanks @MarcoGorelli!

**Comment by nnlnr** [comment]
take
