### ISSUE TITLE
Give DataFrame.diff the same optional arguments as DataFrame.pct_change

### ISSUE THREAD

**Issue by Beliavsky** [pandas-dev/pandas#54732]
I wish `DataFrame.diff` had the optional arguments that the similar method `DataFrame.pct_change` did, in particular `fill_method`, `limit`, `freq`, and `**kwargs`. Similarly, I wish `DataFrame.pct_change` had the axis argument that `DataFrame.diff` does.

Computing ratio differences as `pct_change` does or arithmetic differences as `diff` does are similar operations, and a user may wish to experiment with both methods of differencing. Having the same optional arguments for the two methods would facilitate this.

**Comment by mroeschke** [comment]
Thanks for the suggestion, but it doesn't seem that this idea hasn't gotten much support for the core team or interest in the community to implement so closing.
