### ISSUE TITLE
ENH: Replace oldest-supported-numpy with numpy 1.25.x since they guarantee ABI/API compatibility since 1.19.x

### ISSUE THREAD

**Issue by matejsp** [pandas-dev/pandas#54748]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

With 1.25 numpy it is not possible to build against latest numpy and retain compatibility from 1.19 forward: https://numpy.org/doc/stable/dev/depending_on_numpy.html 

It is getting hard to build old numpy on latest MacOSX:
https://github.com/scipy/oldest-supported-numpy/issues/77
https://github.com/numpy/numpy/issues/17987
https://github.com/pypa/wheel/issues/385

### Feature Description

Use latest version of numpy for all platforms since pandas and numpy now have minimum python of 3.9.

### Alternative Solutions

Alternative solution is to continue the battle with building unsupported versions of numpy.

**Comment by phofl** [comment]
I don't really know what you expect for us. We are already building against 1.25 IIRC, but we are following NEP29 in our NumPy support schedule as a runtime dependency, so we won't drop support for older versions

**Comment by matejsp** [comment]
I thought about changing https://github.com/pandas-dev/pandas/blob/main/pyproject.toml:

Just for build system: [build-system]

```
    # Note: numpy 1.25 has a backwards compatible C API by default
    # we don't want to force users to compile with 1.25 though
    # (Ideally, in the future, though, oldest-supported-numpy can be dropped when our min numpy is 1.25.x)
    "oldest-supported-numpy>=2022.8.16; python_version<'3.12'",
    "numpy>=1.22.4; python_version>='3.12'",
```

to:
```
    "oldest-supported-numpy>=2022.8.16; python_version<'3.9'",
    "numpy>=1.25.0; python_version>='3.9'",  # 1.25 is compatible numpy from 1.19 ...
```

**Comment by matejsp** [comment]
My problem is that when I want to build pandas (with pip wheel) it takes the oldest-supported-numpy in build-system and it forces me to use and build 1.17.3 for python 3.9 and the build fails on MacOSX because of too old wheel package in requirements of very old numpy ...

But I see :D you don't want to force user to compile it with 1.25.x ... :)
