### ISSUE TITLE
ENH: 

### ISSUE THREAD

**Issue by mikekeith52** [pandas-dev/pandas#54741]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

When using connection objects in `pd.read_sql()`, if non sqlalchemy engine objects are passed to the `con` argument, it raises this warning:
```
UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
```

### Feature Description

Get rid of the warning. It is clearly not relevant anymore. See #51015. I can use "untested" objects that work so I don't think this warning has any utility.

### Alternative Solutions

Fix `pd.read_sql()` so that the engine object from sqlalchemy > 2.0 works.

**Comment by phofl** [comment]
We don't have any test coverage for this, so there aren't any guarantees. You can use that but it's at your own risk.

We fixed compatibility months ago, we will need a reproducer if you think that something is still broken

**Comment by mikekeith52** [comment]
Sorry, you're right. I was having a very frustrating day yesterday (new work-issued laptop) and didn't realize my pandas had been downgraded to 1.5.6 or somewhere around there. I upgraded again to 2.0.3 and the engine object works. Thanks!
