### ISSUE TITLE
BUG: concat(axis=1) sorts by default for DatetimeIndex

### ISSUE THREAD

**Issue by lukemanley** [pandas-dev/pandas#54769]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

a = pd.Series(1, index=pd.to_datetime(['2000-01-01', '2000-01-03']))
b = pd.Series(2, index=pd.to_datetime(['2000-01-02', '2000-01-04']))

pd.concat([a, b], axis=1)
```

### Issue Description

`concat` documentation states concat will not sort by default. I believe the default sort behavior was deprecated some time ago. However, there is still a `sort=True` behavior for `DatetimeIndex`:

```
              0    1
2000-01-01  1.0  NaN
2000-01-02  NaN  2.0
2000-01-03  1.0  NaN
2000-01-04  NaN  2.0
```

The source of this behavior is a hard-coded special-casing in `pandas.core.indexes.api.union_indexes`. Making this not sort by default seems to break at least one test (`test_concat_datetime_timezone`) and possibly more. 

### Expected Behavior

Per the docs, I would expect no sort by default. But that might surprise users if changed. I suppose this either needs to be documented (if intentional) or deprecated (if not intentional).

### Installed Versions

.

**Comment by kshitiz305** [comment]
Hi I am a first time contributor would like to know if I shall update the docs or shall make changes to sort the bug

**Comment by lukemanley** [comment]
> Hi I am a first time contributor would like to know if I shall update the docs or shall make changes to sort the bug
> 
> 

Hey @kshitiz305, I think this needs a bit more discussion before determining which path to take.

**Comment by lukemanley** [comment]
@phofl - just noticed you had opened https://github.com/pandas-dev/pandas/pull/51683 for this issue. Any particular reason for closing it?
