### ISSUE TITLE
DOC: 

### ISSUE THREAD

**Issue by idealcrouch** [pandas-dev/pandas#54822]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/user_guide/io.html#io-read-html

### Documentation problem

This script in the documentation returns an error since the source material changed on Wikipedia. 
```
import pandas pd
url_mcc = "https://en.wikipedia.org/wiki/Mobile_country_code"
dfs = pd.read_html(
    url_mcc,
    match="Telekom Albania",
    header=0,
    converters={"MNC": str},
)
```

returns the error
ValueError: No tables found matching pattern 'Telekom Albania'

### Suggested fix for documentation

I believe the fix is to simply match on a different table name (not Telekom Albania). Even using "Albania" works for me.

```
import pandas as pd
url_mcc = "https://en.wikipedia.org/wiki/Mobile_country_code"
dfs = pd.read_html(
    url_mcc,
    match="Albania",
    header=0,
    converters={"MNC": str},
)
```

**Comment by DavidToneian** [comment]
Hi idealcrouch,

thanks for reporting this!

Your fix would indeed work, but the example may break again if the contents of the page would change in certain ways, e.g., Albania changed their name.

How about fixing the referenced version of the page instead to a known-working state, e.g. `https://en.wikipedia.org/wiki/Mobile_country_code?oldid=899173761`?

Would you like to open a PR for this?

**Comment by thiagogquinto** [comment]
Hay @DavidToneian, could I make the PR, if I am correct, [this](https://github.com/pandas-dev/pandas/blob/main/doc/source/user_guide/io.rst) is the location of the file, so could I make your suggested change and make a PR or do you prefer to wait for the response of @idealcrouch?

**Comment by DavidToneian** [comment]
As far as I'm concerned, feel free to create the PR, @thiagogquinto! The location you identified is correct.

**Comment by idealcrouch** [comment]
Hi everyone, apologies for the late reply. I'm totally happy to make the
change this afternoon if that's helpful. I haven't done a pull request in
pandas before, so I would just request a bit of time to make sure I'm doing
it right.

I see the background instructions here:
https://pandas.pydata.org/docs/dev/development/contributing.html Is there
anything else I should check out before trying it?

Thiago, if you prefer to get it done quickly, then definitely feel free.
Please just let me know if I should try it later.

Thanks a lot,
John

**Comment by thiagogquinto** [comment]
Thanks @idealcrouch, but you can make it, It's your issue.

**Comment by idealcrouch** [comment]
Cool. I'll tackle it this afternoon. Thanks everyone.
