### ISSUE TITLE
TST: Add tests for DataFrame/Series.value_counts with missing categories

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#54836]
From #54789, it seems to me we didn't have any test coverage for Series/DataFrame.value_counts with categoricals. We still don't have any test coverage for these methods where the categorical has missing categories, e.g. `pd.Categorical([1, 2, 4], categories=[1, 2, 3, 4])`. Tests for these cases should be added.

**Comment by rsm-23** [comment]
take

**Comment by KalaitziMaria** [comment]
Hello, thank you for the issue, i would like to contribute to pandas library, i saw that this is a good first issue, and i would like to help. Could you tell how i can help because its my first time contributing to an issue.
Thank you.
