### ISSUE TITLE
ENH: Leveraging StringZilla for 10x faster string-based sorting, partitioning, and search

### ISSUE THREAD

**Issue by ashvardanian** [pandas-dev/pandas#54867]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I recently worked with large textual datasets, which I hoped to process with Pandas and other standard Python tools. Still, I had to implement a new library with several SIMD and SWAR tricks to accelerate procedures involving large multi-gigabyte strings, and their chunks. Now that the __[StringZilla](https://github.com/ashvardanian/stringzilla)__ library is publicly available, I'd be open to contributing to Pandas, to make sure that no one else has to go down that path 😅 

Would that be helpful? If so, should I integrate it at the Python or C levels?  The underlying design is quite friendly to PyArrow structures and wouldn't be hard to adjust.

### Feature Description

On `sort`, `in`, and `groupby`, operations use StringZilla for 10x-100x better performance.

### Alternative Solutions

An alternative solution would be to keep things as they are.

**Comment by mroeschke** [comment]
Thanks for the request but given the lack of discussion it doesn't appear there is much interest at the moment. I think the appropriate path would be to create a separate package implementing an `ExtensionArray` that leverages that library so closing for now
