### ISSUE TITLE
ENH: Data Profile Report - Pull sample data at random rather than first 5 rows

### ISSUE THREAD

**Issue by claymcbride** [pandas-dev/pandas#54871]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish the pandas data profiling report would select sample data at random rather than displaying the first 5 records from the column. In its current state, profile reports on tables with personally identifiable information (PII) exposes this sensitive data. Adding the sensitivity=true attribute redacts too much useful information.

### Feature Description

When clicking on the "More details" button, the table that contains Sample Data would show 5 records pulled at random from the column. Same for the Sample Data section of the report.

### Alternative Solutions

Ability to hide just the sample data under "More details" (I can hide the Sample data tab

### Additional Context

With emerging data privacy regulations such as GDPR and CCPA/CPRA, this feature would allow the profiling tool to be used and not expose PII. Thank you!!!!!

**Comment by asishm-wk** [comment]
Thanks for the report. pandas-profiling (now renamed to ydata-profiling) is a separate project. You should raise this request there - https://github.com/ydataai/ydata-profiling

**Comment by mroeschke** [comment]
Closing as this is a feature in a different project
