### ISSUE TITLE
BUG: `Category pyarrow[large-string] column -> pyarrow Table` fails for `pyarrow<=11`

### ISSUE THREAD

**Issue by s-banach** [pandas-dev/pandas#54897]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pyarrow as pa
import pandas as pd

x = pd.Series(["A"], dtype=pd.ArrowDtype(pa.large_string())).astype("category")
x.to_frame().to_parquet("test.p")
```

### Issue Description

Works fine in `pyarrow>=12`.
Gives this error in `pyarrow==11`:
```
pyarrow.lib.ArrowInvalid: ("Could not convert <pyarrow.LargeStringScalar: 'A'> with type pyarrow.lib.LargeStringScalar: did not recognize Python value type when inferring an Arrow data type", 'Conversion failed for column 0 with type category')
```

### Expected Behavior

Don't raise exception.

Personally, I can't understand why `pandas==3.0` is only going to require `pyarrow==7.0`.
Especially when you're so aggressive about dropping support for older versions of python!

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : ba1cccd19da778f0c3a7d6a885685da16a072870
python              : 3.11.4.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.22621
machine             : AMD64
processor           : AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : English_United States.1252

pandas              : 2.1.0
numpy               : 1.25.0
pytz                : 2023.3
dateutil            : 2.8.2
setuptools          : 67.8.0
pip                 : 23.1.2
Cython              : None
pytest              : 7.4.0
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.14.0
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.7.2
numba               : None
numexpr             : 2.8.5
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : 11.0.0
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.1
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : 0.19.0
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by phofl** [comment]
Thanks for your report. This is an upstream issue, I don't see us fixing this since newer versions work
