### ISSUE TITLE
RLS 2.1.1

### ISSUE THREAD

**Issue by lithomas1** [pandas-dev/pandas#54901]
Currently scheduled for September 20, 2023.

**Comment by phofl** [comment]
We normally do the first release 3 weeks after the actual release, so around September 20th?

**Comment by lithomas1** [comment]
Yeah, that works for me.

cc @pandas-dev/pandas-core for thoughts/objections.

**Comment by lithomas1** [comment]
Hi @pandas-dev/pandas-core,

Just a friendly reminder that 2.1.1 is still scheduled for tomorrow. 
There are still 6 PRs open here,
https://github.com/pandas-dev/pandas/pulls?q=is%3Aopen+is%3Apr+milestone%3A2.1.1,
are we OK bumping those off?

(If not, the next available window for me to release is next Wednesday, since that's when I'll next have a decent chunk of time.)

I think we are mostly good from a build/CI POV. 
The only issue is that it looks like matplotlib 3.8.0 is popping up in the 2.1.x CI, making a couple jobs fail, but I will pin that myself if there are any issues.

**Comment by mroeschke** [comment]
IMO the remaining issues don't seem like blockers so OK bumping those to 2.1.2 and releasing tomorrow

**Comment by jorisvandenbossche** [comment]
@lithomas1 when are you planning to release exactly? (if it's not already done) There are several open PRs for regressions that I could finish up (eg https://github.com/pandas-dev/pandas/pull/55173 is actually a serious regression and might only need a whatsnew)

**Comment by lithomas1** [comment]
I'm planning on doing the release around 3-4 PM EST (19-20 UTC).
If you think the changes are small enough that you think you could get them merged/backported, you're welcome to put a couple more things into 2.1.1.

I don't think I'll release after 4pm (I try to avoid releasing when people are off from work in general), so unless there's something that should be blocking (in which case I'll release next Wednesday), anything not in by then goes onto 2.1.2.

**Comment by lithomas1** [comment]
@pandas-dev/pandas-core 
Starting the release now. Please don't merge anything to 2.1.x. right now.

**Comment by lithomas1** [comment]
Feel free to merge to 2.1.x again.

**Comment by lithomas1** [comment]
Release announced, closing this issue.
