### ISSUE TITLE
BUG: FutureWarning about pct_change()

### ISSUE THREAD

**Issue by xzy103** [pandas-dev/pandas#54953]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

arrays = [
    [1, 100],
    [2, 102],
    [],
    [],
    [3, 103],
    [4, 104]
]
df = pd.DataFrame(arrays)

df_new = df[1].pct_change(fill_method=None)
```

### Issue Description

When I use `fill_method=None` in `pct_change()`, it will warn: 
```
FutureWarning: The 'fill_method' and 'limit' keywords in Series.pct_change are deprecated and will be removed in a future version. 
Call ffill before calling pct_change instead.
```
Reading the [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pct_change.html)'s instructions and examples, I learned that I should write it like this:
```python
df_new = df[1].ffill().pct_change()
```

But how can I specify `fill_method=None` in `ffill()`?

### Expected Behavior

Perhaps the new approach should have a corresponding way to handle this issue.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : ba1cccd19da778f0c3a7d6a885685da16a072870
python              : 3.11.4.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.22621
machine             : AMD64
processor           : AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : Chinese (Simplified)_China.936

pandas              : 2.1.0
numpy               : 1.25.2
pytz                : 2023.3
dateutil            : 2.8.2
setuptools          : 65.5.1
pip                 : 22.3.1
Cython              : 3.0.2
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : None
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : 2.8.5
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : 3.8.0
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by phofl** [comment]
None is equal to not filling anything, you can simply remove the argument

**Comment by xzy103** [comment]
> None is equal to not filling anything, you can simply remove the argument

```python
df1 = df[1].pct_change(fill_method=None)
print(df1)
"""
0         NaN
1    0.020000
2         NaN
3         NaN
4         NaN
5    0.009709
"""

df2 = df[1].pct_change()
print(df2)
"""
0         NaN
1    0.020000
2    0.000000
3    0.000000
4    0.009804
5    0.009709
"""

df3 = df[1].ffill().pct_change()
print(df3)
"""
0         NaN
1    0.020000
2    0.000000
3    0.000000
4    0.009804
5    0.009709
"""
```

This doesn't seem feasible, The desired outcome I'm hoping for is `df1`.

**Comment by phofl** [comment]
Sorry bad wording on my side. I meant after the deprecation is enforced, not now. So starting with 3.0 you can remove that argument
