### ISSUE TITLE
Label etiquettes

### ISSUE THREAD

**Issue by tocr83** [pandas-dev/pandas#54963]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish pandas would add an etiquette row below the column headers/label that can hold explanatory information about the specific column. For example on a housing dataset a column might hold a price variable and an etiquette that says price per sqm would be nice that gives the user an easy access to descriptive information as column headers are typically short. It can be thought of as a dict where each column header key can have a value etiquette.

### Feature Description

-

### Alternative Solutions

-

**Comment by attack68** [comment]
I don't really see how this is any different to either:

A)

Creating a table and adding that info into a meta object such as a dict as you say.

```python
>>> meta = Series(
        ["Price paid for dwelling", "Living area m sq.", "Total area m sq."],
        index=["$", "L", "T"]
    )
>>> df = DataFrame([100, 25], columns=["$", "L"])
>>> meta.loc[df.columns]
Out[12]: 
$    Price paid for dwelling
L          Living area m sq.
dtype: object
```

B) 

```python
>>> df.columns = MultiIndex.from_arrays([df.columns, meta.loc[df.columns]])
>>> df
                        $                 L
  Price paid for dwelling Living area m sq.
0                     100                25
```

Thus I don't really recognise any real benefit of adding your suggestion on top of the existing API, and think users would probably find it more of an obfuscation and confusing element, tbh.

**Comment by mroeschke** [comment]
Thanks for the issue, but it appears this hasn't gotten traction in a while so closing
