### ISSUE TITLE
ENH: pyarrow backend zero-copy for multi-index dataframe 

### ISSUE THREAD

**Issue by mlkui** [pandas-dev/pandas#54990]
### Feature Type

- [X] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Zero-copy for multi-index dataframe.

Currently, there is a significant limitation for big dataframes when trying to convert multi-index dataframes from Arrow tables using zero copy (zero_copy_only=True). This limitation poses a major problem as it prevents converting the dataframe with zero copy.  You can reset_index() the dataframe, convert it to arrow table, and convert arrow table back to dataframe with zero copy, but after all, you must use call set_index() to the dataframe to get multi-index back, then copy happens.

As the the document says:
`Zero copy conversions from Array or ChunkedArray to NumPy arrays or pandas Series are possible in certain narrow cases:

The Arrow data is stored in an integer (signed or unsigned int8 through int64) or floating point type (float16 through float64). This includes many numeric types as well as timestamps.

The Arrow data has no null values (since these are represented using bitmaps which are not supported by pandas).

For ChunkedArray, the data consists of a single chunk, i.e. arr.num_chunks == 1. Multiple chunks will always require a copy because of pandas’s contiguousness requirement.

In these scenarios, to_pandas or to_numpy will be zero copy. In all other scenarios, a copy will be required.`

These three limitations can be easily addressed. However, since multi-index currently necessitates data structure construction, it appears that there is no straightforward solution available.

### Feature Description

    with pa.memory_map("d:\\pyarrow.arrow", 'r') as source:
        table= pa.ipc.RecordBatchFileReader(source).read_all()
        df = table.to_pandas(zero_copy_only=True)

### Alternative Solutions

No Alternative Solutions

**Comment by mroeschke** [comment]
You may also want to report this in arrow. I suspect this might be difficult as the concept of an index doesn't also exist in an arrow table

**Comment by mroeschke** [comment]
Closing as an upstream issue
