### ISSUE TITLE
BUG: `find_common_type` returning incorrect common type

### ISSUE THREAD

**Issue by galipremsagar** [pandas-dev/pandas#55012]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
In [2]: import pandas as pd
In [3]: from pandas.core.dtypes.cast import find_common_type
In [4]: import numpy as np
In [5]: find_common_type([np.dtype('int32'), np.dtype('bool')])
Out[5]: dtype('O')
In [6]: np.find_common_type([np.dtype('int32'), np.dtype('bool')], [])
Out[6]: dtype('int32')
In [7]: np.find_common_type([], [np.dtype('int32'), np.dtype('bool')])
Out[7]: dtype('int32')
In [8]: pd.__version__
Out[8]: '2.1.0'
```

### Issue Description

I expect the common type for `int32` & `bool` to be `int32` rather than `object` dtype. This results in incorrect behavior of some operations like:

```python
In [9]: idx = pd.Index([0, 1, 2, 3], dtype='int32')
In [10]: bool_idx = pd.Index([True, False, True])
In [11]: idx
Out[11]: Index([0, 1, 2, 3], dtype='int32')
In [12]: bool_idx
Out[12]: Index([True, False, True], dtype='bool')
In [13]: idx.union(bool_idx)
Out[13]: Index([0, 1, 1, 2, 3], dtype='object')
```

### Expected Behavior

```python
In [13]: idx.union(bool_idx)
Out[13]: Index([0, 1, 1, 2, 3], dtype='int32')
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : ba1cccd19da778f0c3a7d6a885685da16a072870
python              : 3.10.2.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 22.6.0
Version             : Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
machine             : arm64
processor           : arm
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : en_US.UTF-8
pandas              : 2.1.0
numpy               : 1.23.2
pytz                : 2022.2.1
dateutil            : 2.8.2
setuptools          : 60.2.0
pip                 : 21.3.1
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : 8.5.0
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : 2.8.4
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : 11.0.0
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by galipremsagar** [comment]
cc: @mroeschke

**Comment by mroeschke** [comment]
Since bools and ints are meant to be distinct in pandas, I think the expected behavior would be (sort may be incorrect)

```python
In [13]: idx.union(bool_idx)
Out[13]: Index([0, False, 1, True, 2, 3], dtype='object')
```

**Comment by mroeschke** [comment]
So the set ops issue is already known in https://github.com/pandas-dev/pandas/issues/44000

But I think the `find_common_type` dtype behavior is intended

**Comment by galipremsagar** [comment]
Thanks @mroeschke ! Closing in favor of https://github.com/pandas-dev/pandas/issues/44000
