### ISSUE TITLE
BUG: Rolling pd.date_range incorrect for `unit='s'`

### ISSUE THREAD

**Issue by JimHendySchroders** [pandas-dev/pandas#55026]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

WINDOW = pd.Timedelta(days=4)

def rolling_max(unit: str) -> pd.Series:
    start_date = "2023-01-01"
    end_date = "2023-01-10"

    dates = pd.date_range(start_date, end_date, unit=unit)
    series = pd.Series(0, index=dates)
    series.iloc[0] = 1

    return series.rolling(WINDOW).max()

pd.DataFrame(
    {
        f'{unit=}': rolling_max(unit)
        for unit in ('ns', 's')
    }
).plot(marker='s', grid=True);
```

### Issue Description

Hi,

We've noticed that a `pd.date_range` with `unit='s'` gives incorrect results when we apply a `rolling` function. It appears to return the `expanding` result rather than `rolling`.

### Expected Behavior

The expected result is the same as for `unit='ns'` in the above snippet, I.e. a max of 1 for the first 4 days and 0 beyond that.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : ba1cccd19da778f0c3a7d6a885685da16a072870
python              : 3.11.5.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.19044
machine             : AMD64
processor           : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : English_United Kingdom.1252

pandas              : 2.1.0
numpy               : 1.25.2
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.1.2
pip                 : 23.2.1
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : 8.15.0
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.7.2
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by hkhojasteh** [comment]
@jorisvandenbossche I can try to find the issue here :)

**Comment by JimHendySchroders** [comment]
> @jorisvandenbossche I can try to find the issue here :) Update: While debugging observed that this is related to storing the time with different values (eg /1000) for different types. I'm on it

Thanks @hkhojasteh, really appreciate your effort on this.

**Comment by hkhojasteh** [comment]
> > @jorisvandenbossche I can try to find the issue here :) Update: While debugging observed that this is related to storing the time with different values (eg /1000) for different types. I'm on it
> 
> Thanks @hkhojasteh, really appreciate your effort on this.

Welcome! You will have the fixes in the next release version soon :)
