### ISSUE TITLE
ENH: Add Index.normalize as a Series or DataFrame method

### ISSUE THREAD

**Issue by cancan101** [pandas-dev/pandas#5502]
Currently `normalize` does not work on a `Series` or a `DataFrame`:

```
pd.Series(range(5), index=pd.date_range('2013-1-1', periods=5,freq='D')).normalize()
AttributeError: 'Series' object has no attribute 'normalize'
```

However, changing the timezone, which I consider to be a similar type of operation, does work:

```
In [50]: pd.Series(range(5), index=pd.date_range('2013-1-1', periods=5,freq='D')).tz_localize('America/New_York')
Out[50]: 
2013-01-01 00:00:00-05:00    0
2013-01-02 00:00:00-05:00    1
2013-01-03 00:00:00-05:00    2
2013-01-04 00:00:00-05:00    3
2013-01-05 00:00:00-05:00    4
Freq: D, dtype: int64
```

My current workaround:

```
s = pd.Series(range(5), index=pd.date_range('2013-1-1', periods=5,freq='D'))
s.index = s.index.normalize()
```

**Comment by pwaller** [comment]
I just went looking for a normalize function, expecting `df.div(df.sum())` (as in @hayd's comment). The problem I have is that `df` is a chained pipe expression, so I went with (for a series) `s.pipe(lambda s: s.div(df.sum()))`. I did also try `df.div(lambda df: df.sum())`, but I don't know if that's in the right spirit or not.

**Comment by jbrockmendel** [comment]
-1, the API is too big as it is, plus it isn't obvious that it refers to the index and not the data

**Comment by jreback** [comment]
yep we already have .dt to direct this
