### ISSUE TITLE
BUG: Pandas reads "NA" string values as pd.nan when reading a CSV

### ISSUE THREAD

**Issue by chrisbvt** [pandas-dev/pandas#55032]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
data = [{'col1': 'NA'}]
df = pd.DataFrame.from_records(data)
print(type(df.iloc[0].col1))
# Type is string

df.to_csv('na_test.csv')

df_test = pd.read_csv('na_test.csv')
print(type(df_test.iloc[0].col1))
# This is type numpy.float64 as it reads in NA as np.nan
```

### Issue Description

Pandas reads in "NA" values in dataframes as np.nan vs their original string format of NA. This leads to weird interactions when writing and then reading new data.

### Expected Behavior

Ideally the string value of NA would be kept (this could cause for a number of issues with users which have become accustomed to this functionality if changed though). 

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.10.11.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 22.6.0
Version          : Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.4.3 ( have tested on 2.0.3 as well)
numpy            : 1.23.2
pytz             : 2022.2.1
dateutil         : 2.8.2
setuptools       : 67.6.1
pip              : 23.0.1
Cython           : None
pytest           : 7.1.3
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.1.2
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : 0.9.0
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None 

</details>

**Comment by mroeschke** [comment]
Thanks for the report, but this can be already be disabled with the `keep_default_na` keyword so closing

```python
In [4]: type(pd.read_csv('na_test.csv', keep_default_na=False).iloc[0].col1)
Out[4]: str
```
