### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by werowe** [pandas-dev/pandas#55047]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
# download these dataframes saved as pickle files
# https://www.dropbox.com/scl/fi/cgx78lg9jhvns0e64l98g/a.pkl?rlkey=h0rw5fg0ml1i7nh37qnlx6jqp&dl=0
# https://www.dropbox.com/scl/fi/fo09dj2tp2bmi4pajh7v6/c.pkl?rlkey=sjxxc5fzww6rirfz9dpp4r5af&dl=0

import pandas as pd

a=pd.read_pickle("a.pkl")

c=pd.read_pickle("c.pkl")

pd.concat([a,c],ignore_index=True)
```

### Issue Description

These two dataframes each have 1 row Both have index RangeIndex = 0.  One has 65 columns the other has 66.  pd.concat throws this error.  It's supposed to ignore the index and create a new one.

Note that if you use two dataframes with the same number of columns there is no error.

File ~/miniconda3/lib/python3.10/site-packages/pandas/util/_decorators.py:331, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    325 if len(args) > num_allow_args:
    326     warnings.warn(
    327         msg.format(arguments=_format_argument_list(allow_args)),
    328         FutureWarning,
    329         stacklevel=find_stack_level(),
    330     )
--> 331 return func(*args, **kwargs)

File ~/miniconda3/lib/python3.10/site-packages/pandas/core/reshape/concat.py:381, in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    159 """
    160 Concatenate pandas objects along a particular axis.
    161 
   (...)
    366 1   3   4
    367 """
    368 op = _Concatenator(
    369     objs,
    370     axis=axis,
   (...)
    378     sort=sort,
    379 )
--> 381 return op.get_result()

File ~/miniconda3/lib/python3.10/site-packages/pandas/core/reshape/concat.py:612, in _Concatenator.get_result(self)
    610         obj_labels = obj.axes[1 - ax]
    611         if not new_labels.equals(obj_labels):
--> 612             indexers[ax] = obj_labels.get_indexer(new_labels)
    614     mgrs_indexers.append((obj._mgr, indexers))
    616 new_data = concatenate_managers(
    617     mgrs_indexers, self.new_axes, concat_axis=self.bm_axis, copy=self.copy
    618 )

File ~/miniconda3/lib/python3.10/site-packages/pandas/core/indexes/base.py:3904, in Index.get_indexer(self, target, method, limit, tolerance)
   3901 self._check_indexing_method(method, limit, tolerance)
   3903 if not self._index_as_unique:
-> 3904     raise InvalidIndexError(self._requires_unique_msg)
   3906 if len(target) == 0:
   3907     return np.array([], dtype=np.intp)

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

### Expected Behavior

Should concatenate the two dataframes.

### Installed Versions

1.5.3

**Comment by KhadgaA** [comment]
The issue is with your dataframes containing duplicate column names like `name.lastName, name.firstName` , etc. If this is intentional you can use the following code to concat: 

```python
parser = pd.io.parsers.base_parser.ParserBase({'usecols': None})
pd.concat([df.set_axis(parser._maybe_dedup_names(df.columns), axis=1) for df in [a, c]], ignore_index=True)
```
which gives output something like this.
![image](https://github.com/pandas-dev/pandas/assets/88937070/438dcc20-49db-4daa-990e-382681767eb5)

**Comment by twoertwein** [comment]
As pointed out by @KhadgaA, your dataframes have duplicated columns. You can simply remove them with:

`pd.concat([a.loc[:,~a.columns.duplicated()], c.loc[:,~c.columns.duplicated()]])`

@KhadgaA  Please do not use/rely on `pd.io.parsers.base_parser.ParserBase` it is not part of the public API (and obviously also not `_maybe_dedup_names`)! See https://pandas.pydata.org/docs/reference/index.html#api
