### ISSUE TITLE
ENH: column nicknames or shorthands

### ISSUE THREAD

**Issue by tennlee** [pandas-dev/pandas#55060]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I often load data with complex column names. For example, in the source data, the column name might be "temp: method one" or some other longish string. I don't necessarily want to lose these complex names, but they are not convenient to use when indexing into data. The current options appear to be to rename the columns to something more convenient, to use numerical indexing, or to  create a dictionary which will map from a shorthand string to the full column name.

### Feature Description

Add a new method to a DataFrame to specify an alternative set of column names which would then be used by indexing methods if set.

e.g.

df.columns_nicknames = ['tmp', 'value', 'timeofday']

### Alternative Solutions

I don't have anything else in mind.

**Comment by attack68** [comment]
This has the same response as #54963 . I do not believe pandas should be responsible for dual labelled columns or any other form of short hand. Additional to that response pandas Styler also has `relabel_index` which handles displaying different labels but doesnt lose the indexing capability for the underlying dataframe. Examples are provided in the documentation.

**Comment by lithomas1** [comment]
This might be a good usecase for attrs.

xref #42582

(you might want to try using the shorthand names but keeping the long name as an attr 
https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.attrs.html)

**Comment by rhshadrach** [comment]
I think the complexity involved in maintaining a second set of names for columns is not worth the benefit.

**Comment by jbrockmendel** [comment]
There is an old issue about label aliases that I thought was interesting. The use case I had in mind was an index of US state names and doing lookups with abbreviations eg “CA”. I did something similar in a personal project 5ish years ago. IIRC I patched get_loc to do the alias lookup, stored the aliases on the index object. I doubt past-me dealt with get_indexer correctly or at all.

**Comment by tennlee** [comment]
Thanks all for considering the idea - I realise it might not be important or worth the complexity, so thanks for giving it your attention thus far. I'm happy if you do just want to close the issue. I'm not sure whether to go ahead and close this myself, so I'll leave it to the discretion of the pandas team for now.

@lithomas1 makes an excellect suggestion which seems quite practical and doesn't require any new functionality, although I do note that this functionality is marked as experimental in the docs.

**Comment by mroeschke** [comment]
Thanks for the suggestion but closing as the original proposal doesn't seem to have much support
