### ISSUE TITLE
BUG:  assigning dictionary as value for dataframe leads to inconsistent result

### ISSUE THREAD

**Issue by sofyakrainova** [pandas-dev/pandas#55087]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame([[1,2],[3,4]], columns=['a', 'b'], index=[0,1])
d = {0:{'x':5}, 1:{'y':6}}
for k in d:
    df.loc[k, 'c'] = [d[k]]
print(df)
```

### Issue Description

For the code above we have warning message and values for the column **c** have different types. Look at the printed result.
   a  b           c
0  1  2    {'x': 5}
1  3  4  [{'y': 6}]

This happens only with first element in the loop.

### Expected Behavior

Type should be the same for all rows:
   a  b           c
0  1  2    [{'x': 5}]
1  3  4  [{'y': 6}]

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : ba1cccd19da778f0c3a7d6a885685da16a072870
python              : 3.10.12.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.22621
machine             : AMD64
processor           : Intel64 Family 6 Model 154 Stepping 4, GenuineIntel
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : English_Sweden.1252

pandas              : 2.1.0
numpy               : 1.24.2
pytz                : 2022.7
dateutil            : 2.8.2
setuptools          : 68.0.0
pip                 : 23.2.1
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : 4.9.2
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.12.2
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.7.1
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.10.1
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : 0.19.0
tzdata              : 2023.3
qtpy                : 2.2.0
pyqt5               : None

</details>

**Comment by asishm-wk** [comment]
As a workaround,

Adding a `df['c'] = pd.Series()` before your for loop gives your expected result. I'm guessing somewhere in in the `.loc` logic, expanding and creating a new column defaults to a float column instead of a column with the `object` dtype.

This is further evidenced when adding a ``df['c'] = pd.Series(dtype='float64')` prior to the for loop exhibits the same behavior as the original post.

For completeness,

```py
import pandas as pd

df = pd.DataFrame([[1,2],[3,4]], columns=['a', 'b'], index=[0,1])
df['c'] = pd.Series() # works as expected, however changing this to df['c'] = pd.Series(dtype='float64') exhibits the same inconsistency
d = {0:{'x':5}, 1:{'y':6}}
for k in d:
    df.loc[k, 'c'] = [d[k]]
print(df)
```

**Comment by Aloqeely** [comment]
Thanks for the report! Sorry for the very late response but this is fixed on the main branch of pandas.
Going to close but feel free to reopen if you encounter this issue after pandas 3.0 is released.
