### ISSUE TITLE
BUG: `DatetimeIndex.weekofyear` gives `AttributeError`

### ISSUE THREAD

**Issue by this-josh** [pandas-dev/pandas#55092]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> import pandas as pd
>>> idx = pd.DatetimeIndex(["1/1/2020 10:00:00+00:00", "2/1/2020 11:00:00+00:00"])
>>> idx.week
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'DatetimeIndex' object has no attribute 'week'
>>> idx.weekday # sanity check
Index([2, 5], dtype='int32')
>>> idx.weekofyear
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'DatetimeIndex' object has no attribute 'weekofyear'
```

### Issue Description

[`weekofyear`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.html) doesn't seem to be working 

### Expected Behavior

The week `dt`s week of the year as an integer should be returned 

### Installed Versions

>>> pd.show_versions()
/private/tmp/envs/lib/python3.11/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit              : 723feb984e6516e3e1798d3c4440c844b12ea18f
python              : 3.11.5.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 22.6.0
Version             : Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
machine             : arm64
processor           : arm
byteorder           : little
LC_ALL              : None
LANG                : en_GB.UTF-8
LOCALE              : en_GB.UTF-8

pandas              : 2.2.0dev0+208.g723feb984
numpy               : 1.25.2
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.1.2
pip                 : 23.2.1
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : None
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

**Comment by mroeschke** [comment]
This was deprecated in 1.1.0 and now it's suggested to use `DatetimeIndex.isocalendar().week` instead

**Comment by this-josh** [comment]
> This was deprecated in 1.1.0 and now it's suggested to use `DatetimeIndex.isocalendar().week` instead

It should be removed from the docs if that is the case.

**Comment by mroeschke** [comment]
Could you share where this still exists in the docs?

**Comment by this-josh** [comment]
See the link in the initial comment.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.html

**Comment by tray3j** [comment]
@mroeschke The reference to week and weekofyear attributes still exists in the user gude, link here: [Time/date components](https://pandas.pydata.org/docs/user_guide/timeseries.html#time-date-components).

**Comment by tray3j** [comment]
I opened this issue: https://github.com/pandas-dev/pandas/issues/57887

**Comment by sorenwacker** [comment]
`df.col.dt.isocalendar().week` ?
