### ISSUE TITLE
ENH: Convert an HTML to a `Styler`

### ISSUE THREAD

**Issue by abokey1** [pandas-dev/pandas#55135]
### Feature Type

- [X] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish we could have something in the API to make a [`Styler`](https://pandas.pydata.org/docs/reference/api/pandas.io.formats.style.Styler.html) object from plain HTML text.
Additionnaly, if we can have a `with_styles` parameter in [`read_html`](https://pandas.pydata.org/docs/reference/api/pandas.read_html.html), that would be so cool.

### Feature Description

```
from pandas.io.formats.style import Styler

html = """<table>
  <thead>
    <tr>
      <th></th>
      <th>col1</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <td>2</td>
      <td style="background-color: yellow;">3</td>
    </tr>
  </tbody>
</table>"""

s = Styler.from_html(html)
```

![image](https://github.com/pandas-dev/pandas/assets/113783165/6d9a7169-79d8-41e6-80eb-9b34d6359598)

*Side note*:
Conversely, the actual pandas equivalent to the configuration above is : 
```
import pandas

s = pd.DataFrame({"col1": range(1, 4)}).style.highlight_max()
```

### Alternative Solutions

As of `2.0.1`, IMHO, I don't see any alternative solution.

**Comment by rhshadrach** [comment]
cc @attack68

**Comment by attack68** [comment]
I can describe to you why this won't work.

HTML CSS is a very broad language. They are many different ways of styling a table in HTML.

For example a table cell might be styled directly with **inline styles**:
```
<td style="color: red;"> 100 </td> 
```

Or it might be styled with `id` via a **stylesheet**:
```
<style> #myid {color: red;} </style>
...
<td id="myid"> 100 </td>
```

Or it might be styled with a `class` via a **stylesheet**
```
<style> .myclass {color: red;} </style>
...
<td class="myclass"> 100 </td>
```

Or it might be styled with pseudo-selectors of which there are bazillions (https://www.w3schools.com/cssref/css_selectors.php)

Then it might be styled with multiple of these and to correctly ascertain the color you have to imply CSS **inheritance** (https://pandas.pydata.org/docs/user_guide/style.html#CSS-Hierarchies)

So, whilst it may technically be possible to reverse engineer all of this probably with a very slim chance, it would be incredibly complicated and not worth the effort I don't think.
