### ISSUE TITLE
DOC: rolling axis parameter deprecated, but not in docs

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [pandas-dev/pandas#55133]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.rolling.html

### Documentation problem

Pandas 2.1.0 complains:

`The 'axis' keyword in DataFrame.rolling is deprecated and will be removed in a future version. Call the method without the axis keyword instead.`

But there is no deprecation version or comment in the documentation.

### Suggested fix for documentation

Add the deprecation information to the `axis` parameter documentation.

**Comment by rsm-23** [comment]
take
