### ISSUE TITLE
BUG: Multiple typing issue with the package

### ISSUE THREAD

**Issue by r-priyam** [pandas-dev/pandas#55143]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

def foo(timestamp: pd.Timestamp):
    return timestamp

foo(pd.Timestamp.now())
```

### Issue Description

Running `mypy` against this code gives:
```
🕙 12:32 ❯ mypy bug.py                                                                                                     
bug.py:3: error: Name "pd.Timestamp" is not defined  [name-defined]
bug.py:6: error: Module has no attribute "Timestamp"  [attr-defined]
Found 2 errors in 1 file (checked 1 source file)
```
Same issue with `pd.Timedelta`

### Expected Behavior

The code works fine so the static type checking should work fine too.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 0f437949513225922d851e9581723d82120684a6
python           : 3.11.1.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 22.6.0
Version          : Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.3
numpy            : 1.24.4
pytz             : 2023.3.post1
dateutil         : 2.8.2
setuptools       : 68.2.2
pip              : 22.3.1
Cython           : 3.0.2
pytest           : 7.4.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.3
html5lib         : None
pymysql          : None
psycopg2         : 2.9.7
jinja2           : 3.1.2
IPython          : None
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : 2023.8.0
fsspec           : 2023.3.0
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : 12.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : 2023.3.0
scipy            : 1.10.1
snappy           : None
sqlalchemy       : 1.4.49
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by twoertwein** [comment]
I cannot reproduce your issue (with pandas 2.1.0 and mypy 1.5.1 or pyright 1.1.323 and with/without py.typed). Do you have pandas-stubs or third-party stubs for pandas installed?

I can also not reproduce your issue with pandas-stubs.

**Comment by r-priyam** [comment]
Hi, thank you @twoertwein, after your response, I updated `pandas-stubs` to latest and it seems to be fixed now.
```py
  Attempting uninstall: pandas-stubs
    Found existing installation: pandas-stubs 2.0.2.230605
    Uninstalling pandas-stubs-2.0.2.230605:
      Successfully uninstalled pandas-stubs-2.0.2.230605
Successfully installed numpy-1.25.2 pandas-stubs-2.0.3.230814
```
Much thanks for the prompt response, I will close the issue.
