### ISSUE TITLE
DOCS: Unpin pydata-sphinx-theme

### ISSUE THREAD

**Issue by lithomas1** [pandas-dev/pandas#55164]
> The pydata-sphinx-theme has a new release, and that causes some issues with the top bar:
> 
> ![image](https://user-images.githubusercontent.com/1020496/268440338-c0f2a1ff-c2a4-46e8-9ed9-6ab43316c20c.png)
> 
> So we can maybe temporarily pin the theme until that is fixed

from #55159

**Comment by hkhojasteh** [comment]
@jorisvandenbossche I guess this is going to be fixed straightforwardly by changing the top bar search column style in the new theme version. It is similar to yesterday's sprint fix. So I will take care of it
