### ISSUE TITLE
 DOC: fix the dev version label in the version dropdown

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#55160]
Until recently, the label in the version dropwdown for the development docs was a simple "dev" (the label shown when being on the dev docs, not the label in the expanded dropdown list):

![image](https://github.com/pandas-dev/pandas/assets/1020496/f86d2874-7e89-45fd-97eb-f242af267f03)

But recently this changed to contain the full pandas version:

![image](https://github.com/pandas-dev/pandas/assets/1020496/836a9496-38d6-4287-b12b-0f0eb0704c8c)

Maybe it's nice that it includes the release number, but adding the whole commit hash is certainly unnecessary noise IMO (eg maybe "2.2.0.dev" would be sufficient if we want a number included?)

**Comment by hkhojasteh** [comment]
I'm working on it.
