### ISSUE TITLE
DOC: 

### ISSUE THREAD

**Issue by alexandermorgan** [pandas-dev/pandas#55187]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

pandas.Series.first_valid_index
https://github.com/pandas-dev/pandas/blob/ba1cccd19da778f0c3a7d6a885685da16a072870/pandas/core/generic.py#L12341

### Documentation problem

https://github.com/pandas-dev/pandas/blob/ba1cccd19da778f0c3a7d6a885685da16a072870/pandas/core/generic.py#L12341
The "Notes" passage reads: "If all elements are non-NA/null, returns None. Also returns None for empty Series/DataFrame."
but the "non-" should not be there.

### Suggested fix for documentation

The "non-" should be deleted from the "Notes" section, resulting in this:
"If all elements are NA/null, returns None. Also returns None for empty Series/DataFrame."

**Comment by jfadia** [comment]
take

**Comment by jfadia** [comment]
My understanding:
- The function is trying to return the first valid (i.e. non-NA and non-null) index in the series/frame
- The [docs](https://github.com/pandas-dev/pandas/blob/ba1cccd19da778f0c3a7d6a885685da16a072870/pandas/core/generic.py#L12341) say that if all elements are `non-NA/null, returns None`, which would imply that we would return `None` if all elements _are_ `non-null`, which I believe was not the intent

I will update this to remove the "non-" from that line. Thanks!
