### ISSUE TITLE
Install pandas 0.23.2, 0.23.3 .... 0.25.3 on python 3.7.6 failed with "error: ‘NUMPY_IMPORT_ARRAY_RETVAL’ undeclared (first use in this function); did you mean ‘NPY_INOUT_ARRAY’"

### ISSUE THREAD

**Issue by fulwang** [pandas-dev/pandas#55199]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Linux-4.18.0-477.21.1.el8_8.s390x-s390x-with-debian-10.3

### Installation Method

pip install

### pandas Version

0.23.3

### Python Version

3.7.6

### Installation Logs

<details>

Replace this line with the installation logs.

</details>
[pandas_install.log](https://github.com/pandas-dev/pandas/files/12659745/pandas_install.log)

**Comment by fulwang** [comment]
Hi there,

I'm trying to migrate an application from x86 container to s390x container and need to install pandas 0.23.3 on top of python 3.7.6 to keep the most of the runtime environment.  But unfortunately, it failed with above error. I also tried other closer versions such as 0.23.4 till 0.25.3, all gave me above errors.

What could be the reasons? 
Could anyone kindly give some clue?

Appreciate for the help!!!

**Comment by mroeschke** [comment]
Sorry, but the version of pandas you're running is not supported anymore so closing as not a current pandas issue. I would suggest asking on StackOverflow
