### ISSUE TITLE
Why doesn't the .at() function work for pandas?

### ISSUE THREAD

**Issue by EdwinVonLemberg** [pandas-dev/pandas#55215]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/77139899/why-doesnt-the-at-function-work-for-pandas

### Question about pandas

I have the following code in which I access a CSV file with multiple columns containing numbers and want to change a specific column under certain conditions:

import csv

import pandas

final_activities = pandas.read_csv("VPN2/VPN2_Final_Activities.csv", delimiter=';', names=['Timerels', 'ActivityClass_Ankle', 'ActivityClass_Hip', 'ActivityClass_Thigh', 'ActivityClass_Wrist', 'ActivityClass_Annotation'], skip_blank_lines=True, skipinitialspace=True, engine='python', header=0)

i = 0

while i < len(final_activities):

ankle_activity = final_activities.loc[i][1]

annotation_activity = final_activities.loc[i][5]

if(int(annotation_activity) == 9 and int(ankle_activity) == 2):

final_activities.at[i, 'ActivityClass_Ankle'] = 9
i += 1

In this case, nothing is being modified in the final_activities DataFrame due to the .at statement. It used to work for me before. Please help!

**Comment by jonodrew** [comment]
Hi!

This is my first time answering a question on this repo, so I hope I can help.

The link to your question goes to a different question

I've popped your code in a block below, to make it easier to read. I've just run it with some fake data and it seems to work (my version is 2.1.0). The only thing I can think of is that maybe your `if` statement never evaluates to true?

```python
import csv

import pandas

final_activities = pandas.read_csv("VPN2/VPN2_Final_Activities.csv", delimiter=';', names=['Timerels', 'ActivityClass_Ankle', 'ActivityClass_Hip', 'ActivityClass_Thigh', 'ActivityClass_Wrist', 'ActivityClass_Annotation'], skip_blank_lines=True, skipinitialspace=True, engine='python', header=0)

i = 0

while i < len(final_activities):
  ankle_activity = final_activities.loc[i][1]
  annotation_activity = final_activities.loc[i][5]
  if(int(annotation_activity) == 9 and int(ankle_activity) == 2):
    final_activities.at[i, 'ActivityClass_Ankle'] = 9
  i += 1
```

Lastly, iterating over rows in Pandas is generally an anti-pattern, though it doesn't matter so much with small datasets.

**Comment by MarcoGorelli** [comment]
closing as per https://stackoverflow.com/questions/20625582/how-to-deal-with-settingwithcopywarning-in-pandas

and thanks @jonodrew
