### ISSUE TITLE
BUG: Get deprecation warning from `Series` constructor

### ISSUE THREAD

**Issue by rikardn** [pandas-dev/pandas#55228]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

ind1 = pd.Series([1])
ind2 = pd.Series([2])
ser = pd.Series([1.23], index=[ind1, ind2])
print(ser)
```

### Issue Description

If trying to create a series with a multiindex from two series I get a deprecation warning with pandas 2.1.1

```
DeprecationWarning: Series._data is deprecated and will be removed in a future version. Use public APIs instead.
```

Since I am not using `_data` explicitly it must come from inside of pandas. The only place I have found where this could come from is in the `is_all_arraylike` function where there is a `hasattr(val, "_data")`  in the cython code.

### Expected Behavior

I expect no warning and at least in pandas 2.0.3 this was the case.

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by jbrockmendel** [comment]
The hasattr check is bad.  Changing it to `hasattr(type(val), "_data")` might avoid the warning for now?

**Comment by paulreece** [comment]
I can confirm that the deprecation warning occurs on the main development branch.

```Python
>>> import pandas as pd
>>> ind1 = pd.Series([1])
>>> ind2 = pd.Series([2])
>>> ser = pd.Series([1.23], index=[ind1, ind2])
<stdin>:1: DeprecationWarning: Series._data is deprecated and will be removed in a future version. Use public APIs instead.
```
