### ISSUE TITLE
BUG: Series.value_counts with sort=False returns result sorted on values for Series with string dtype

### ISSUE THREAD

**Issue by CynthiaLuijkx** [pandas-dev/pandas#55224]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

series = pd.Series(data=['a', 'b', 'c', 'b'])

series.astype('string').value_counts(sort=False)
```
which results in:
```python
b    2
a    1
c    1
Name: count, dtype: Int64
```

### Issue Description

Series.value_counts with `sort=False` returns result sorted on values for Series with `string` dtype. 

The output returned is sorted on values, while using `sort=False`, according to the documentation, should ensure that the result is ordered by the order in which the different categories are encountered. 

From a brief dive into the code I believe the error is found in `core\algorithms.py` in `value_couns_internal`;  on line 906, in case the values are an extension array

`result = Series(values, copy=False)._values.value_counts(dropna=dropna)`

is called and the `sort` keyword is not passed on. 

### Expected Behavior

The expected behavior is that the results are ordered by the order in which the categories were encountered, rather than by value, as stated in the `value_counts` documentation. This does happen correctly when the series still has the `object` dtype:

```python
import pandas as pd

series = pd.Series(data=['a', 'b', 'c', 'b'])

series.value_counts(sort=False)
```

which results in: 
```python
a    1
b    2
c    1
Name: count, dtype: int64
```

### Workaround

This code snippet does return the expected values:

```python
import pandas as pd

series = pd.Series(data=['a', 'b', 'c', 'b'])

series.groupby(series, sort=False).count()
```

Result:
```python
a    1
b    2
c    1
dtype: int64
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : e86ed377639948c64c429059127bcf5b359ab6be
python              : 3.10.8.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.19045
machine             : AMD64
processor           : Intel64 Family 6 Model 166 Stepping 0, GenuineIntel
byteorder           : little
LC_ALL              : en_US.UTF-8
LANG                : en_US.UTF-8
LOCALE              : Dutch_Netherlands.1252

pandas              : 2.1.1
numpy               : 1.24.3
pytz                : 2023.3
dateutil            : 2.8.2
setuptools          : 65.5.0
pip                 : 22.3.1
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : 1.1
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.15.0
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : 2023.8.0
fsspec              : 2023.9.0
gcsfs               : None
matplotlib          : 3.7.1
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : 13.0.0
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.2
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report! Confirmed on main. PRs to fix are most welcome.

**Comment by wangdong2023** [comment]
Hi, I'm a Pandas user but never contributed, I would like to take this issue, is it okay?

**Comment by yusharth** [comment]
take

**Comment by wangdong2023** [comment]
:D now I know how it works

**Comment by tirth-hihoriya** [comment]
@wangdong2023 Are you still working on it?

**Comment by wangdong2023** [comment]
@tirth-hihoriya I think @yusharth took the task

**Comment by yusharth** [comment]
I am working on it @tirth-hihoriya . Thanks for asking, will let you know if I need help.

**Comment by Divyansh3021** [comment]
Hey there maintainers! I want to resolve this issue. Can I ?

**Comment by tirth-hihoriya** [comment]
@Divyansh3021, I have already created PR #55260 and am waiting for a maintainer to follow up and help.

**Comment by Divyansh3021** [comment]
okay

**Comment by Chinmay-Bakhale** [comment]
@CynthiaLuijkx @Divyansh3021 @yusharth I'm taking this issue, is it okay?

**Comment by yusharth** [comment]
Thanks for asking @Chinmay-Bakhale. It's fine by me, but make sure you ain't stepping onto someone's toe because @tirth-hihoriya has deliberately linked a PR already.
