### ISSUE TITLE
BUG: AGAIN!!! pd.to_datetime with dayfirst=True error if 'Jun' in data

### ISSUE THREAD

**Issue by madeinjapan** [pandas-dev/pandas#55244]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

# It works correctly
datetime_str = ['01-Jun-2022 00:00:00', '01-Jun-2022 00:00:01', '01-Jun-2022 00:00:01', '01-Jun-2022 00:00:03', '01-Jun-2022 00:00:03', '01-Jun-2022 00:00:03']
pd.to_datetime(pd.Series(datetime_str), dayfirst=True)

0   2022-06-01 00:00:00
1   2022-06-01 00:00:01
2   2022-06-01 00:00:01
3   2022-06-01 00:00:03
4   2022-06-01 00:00:03
5   2022-06-01 00:00:03
dtype: datetime64[ns]

# It raise exception
datetime_str = ['24-May-2022 08:23:07', '24-May-2022 08:23:09', '24-May-2022 08:23:09', '01-Jun-2022 00:00:00', '01-Jun-2022 00:00:01', '01-Jun-2022 00:00:01', '01-Jun-2022 00:00:03', '01-Jun-2022 00:00:03', '01-Jun-2022 00:00:03']
pd.to_datetime(pd.Series(datetime_str), dayfirst=True)

ValueError: time data "01-Jun-2022 00:00:00" doesn't match format "%d-%B-%Y %H:%M:%S", at position 3. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
```

### Issue Description

If the format is not specified as a parameter but dayfirst=True and 'Jun' is included in the data, we get an esception. If the data contains only 'Jun', it works correctly.

Examining the data, the problem may be caused by the following:
```
pd.to_datetime(pd.Series(['24-05-2022 08:23:07']), dayfirst=True).dt.strftime('%B')
0    May
dtype: object

pd.to_datetime(pd.Series(['24-05-2022 08:23:07']), dayfirst=True).dt.strftime('%b')
0    May
dtype: object
```

so the error is not caused by Jun, but by May, because the short and long names are the same. For this reason, the "%d-%B-%Y %H:%M:%S" format fits it, which in other cases does not.

### Expected Behavior

Work with data correctly and quickly. I don't have data in a fixed format, what I know, the first value is always the day. So the format cannot be used. Only 'mixed' could be a solution, but it is very slow... It makes the to_datetime function unusable

### Installed Versions

<details>

pyxlsb              : None
s3fs                : None
scipy               : 1.11.1
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by MarcoGorelli** [comment]
> I don't have data in a fixed format, what I know, the first value is always the day. So the format cannot be used. Only 'mixed' could be a solution, but it is very slow

If you don't know the format and only know that the day comes first, then `format='mixed', dayfirst=True` is probably all you can do here

or loop over your potential formats and combine the results

**Comment by madeinjapan** [comment]
yes i realized that. But this requires a faster solution, because 'mixed' is very slow. Is this possible with pandas?

**Comment by MarcoGorelli** [comment]
do you have a list of potential formats? if so, you could loop over them with `errors='coerce'` and combine the non-null results

**Comment by madeinjapan** [comment]
No, unfortunately I don't have a list. If so, can I combine it with the pandas `where` function? If so, how?

I mean:
```
df[new_column] = my_custom_to_datetime(df[old_column]).where(condition, another_value)
```

**Comment by MarcoGorelli** [comment]
something like
```python
In [76]: datetime_str = ['24-May-2022', '25-May-2022 01:02:03']

In [77]: formats = ['%d-%b-%Y', '%d-%b-%Y %H:%M:%S', '%d-%b-%Y %H:%M'] # list all potential formats

In [78]: import functools

In [79]: arrs = [pd.Series(to_datetime(datetime_str, format=format, errors='coerce')) for format in formats]
    ...:

In [80]: result = arrs[0]


In [81]: for arr in arrs[1:]:
    ...:     result.update(arr)
    ...:

In [83]: result
Out[82]:
0   2022-05-24 00:00:00
1   2022-05-25 01:02:03
dtype: datetime64[ns]
```

Alternatively, if speed is really a concern, you may want to consider (temporarily? depends on your task) converting to polars and then converting back to pandas as an when necessary

**Comment by MarcoGorelli** [comment]
closing then, but thanks for the issue

**Comment by madeinjapan** [comment]
@MarcoGorelli last question:
If I paste this into my own function, how can I use the DataFrame.where function so that my function only runs on values that match the condition?
