### ISSUE TITLE
BUG: pd.merge returns different column order if dataframe contains 0 rows

### ISSUE THREAD

**Issue by rohanjain101** [pandas-dev/pandas#55250]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> df_a = pd.DataFrame({"Col0": pd.Series([], dtype="int32[pyarrow]"), "Col1": pd.Series([], dtype="int32[pyarrow]"), "Col2": pd.Series([], dtype="int32[pyarrow]")})
>>> df_b = pd.DataFrame({"Col0": pd.Series([], dtype="int32[pyarrow]"), "Col1": pd.Series([], dtype="int32[pyarrow]"), "Col2": pd.Series([], dtype="int32[pyarrow]")})
>>> pd.merge(df_a, df_b,left_on=["Col0", "Col2"], right_on=["Col1", "Col2"])
Empty DataFrame
Columns: [Col0_x, Col1_x, Col0_y, Col1_y, Col2]
Index: []

>>> df_a = pd.DataFrame({"Col0": pd.Series([1], dtype="int32[pyarrow]"), "Col1": pd.Series([1], dtype="int32[pyarrow]"), "Col2": pd.Series([1], dtype="int32[pyarrow]")})
>>> df_b = pd.DataFrame({"Col0": pd.Series([1], dtype="int32[pyarrow]"), "Col1": pd.Series([1], dtype="int32[pyarrow]"), "Col2": pd.Series([1], dtype="int32[pyarrow]")})
>>> pd.merge(df_a, df_b,left_on=["Col0", "Col2"], right_on=["Col1", "Col2"])
   Col0_x  Col1_x  Col2  Col0_y  Col1_y
0       1       1     1       1       1
>>>
```

### Issue Description

Above example performs 2 joins, both input schemas are the same, but the returned schema by pd.merge is different if there are 0 rows vs atleast 1 row, input schema for both dfs was [Col0, Col1, Col2]. When there are 0 rows, pd.merge returns schema as [Col0_x, Col1_x, Col0_y, Col1_y, Col2]

When there's atleast 1 row, schema is returned as [Col0_x, Col1_x, Col2, Col0_y, Col1_y]. The position of Col2 differs if df contain 0 rows vs atleast 1 row.

### Expected Behavior

I would expect output schema to always be returned as  [Col0_x, Col1_x, Col2, Col0_y, Col1_y].

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : e86ed377639948c64c429059127bcf5b359ab6be
python              : 3.11.2.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.22621
machine             : AMD64
processor           : Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : English_United States.1252

pandas              : 2.1.1
numpy               : 1.25.2
pytz                : 2023.3
dateutil            : 2.8.2
setuptools          : 68.0.0
pip                 : 23.2.1
Cython              : None
pytest              : 7.0.1
hypothesis          : None
sphinx              : 4.2.0
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.14.0
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : 13.0.0
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : 0.8.9
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None
>>>
</details>

**Comment by mroeschke** [comment]
Thanks for the report. Can reproduce this on main.

Noting that this is independent of the Arrow dtype in your example

**Comment by lukemanley** [comment]
> Thanks for the report. Can reproduce this on main.

@mroeschke - are you actually able to reproduce on main? I cannot reproduce and I think #55028 probably fixed this.

**Comment by rohanjain101** [comment]
Thanks @lukemanley, yes this looks fixed.
