### ISSUE TITLE
`ewm().var(bias=False)` accuracy

### ISSUE THREAD

**Issue by max-sixty** [pandas-dev/pandas#55274]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
def n_effective(**kwargs):
    s = pd.Series(np.arange(100)).ewm(**kwargs)

    # The ratio between the biased & unbiased var
    adjustment = s.var(bias=False) / s.var(bias=True)

    # Extract the `n` that's implied by the adjustment. `adjustment = n / (n-1)`, which rearranges to this
    n = adjustment / (adjustment - 1)

    # Take the final point
    return n[-1:]

# and then applied to a few values:

n_effective(span=2)
# 2.0

n_effective(span=5)
# 4.9999

n_effective(span=12)
# 11.999
```

### Issue Description

Hi there — I'm a maintainer of numbagg (and of xarray, which uses numbagg for its ewm routines). I've written a numba routine for calculating exponentially weighted moving variance in https://github.com/numbagg/numbagg/pull/106. I'm comparing it to the pandas cython version and:
- It matches for `bias=True`
- It's doesn't match `bias=False`

It's possible I'm misunderstanding, but I'm seeing outcomes I wouldn't expect. It looks like it's adjusting based on the value of `span`. But I would have thought it should adjust based on the number of effective data points.

I've included a quick function for figuring out what the adjustment is above and the results

Instead, of it matching `span`, I would have expected it to be using n_effective of `1/alpha` — i.e. if `alpha=0.5`, then there's "effectively" 2 points — it's a geometric sequence with a ratio of 0.5. That's the value `numbagg` [uses as the denominator in its ewma](https://github.com/numbagg/numbagg/blob/3beaf64c82d47d69be622a328fdc92cb078cb271/numbagg/moving.py#L27) (which does match the pandas version of ewma...).

I'm not sure the best way of resolving this — I'm trying to balance the logic here with the function being in pandas a long time, hence unlikely to be wrong. It's possible that I'm misunderstanding something, or that I've made a math mistake on a Sunday... Is there anyone who wrote the function / who knows enough to comment from the pandas side?

Thank you...

### Expected Behavior

As above

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 0f437949513225922d851e9581723d82120684a6
python           : 3.9.18.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 22.6.0
Version          : Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : None
LOCALE           : en_US.UTF-8

pandas           : 2.0.3
numpy            : 1.24.4
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 68.1.2
pip              : 23.2.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.14.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : 0.57.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.11.2
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 2023.8.0
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by torext** [comment]
@max-sixty The bias of a weighted variance estimator with weights $w_1,\ldots,w_n$ corresponds to a factor of $\left(1-\sum_iw_i^2\right)$, i.e. if you have i.i.d. random variables $X_1,\ldots,X_n$ with variance $\sigma^2$ then
$$E\left[\sum_iw_i\left(X_i-\sum_jw_jX_j\right)^2\right]=\left(1-\sum_iw_i^2\right)\sigma^2.$$
So going back to Pandas and applying the correspondence (by definition) of `alpha = 2 / (span + 1)`, we see that Pandas seems to be doing the right thing:
```python
import pandas as pd
import pandas._testing as tm


def bias_factor(span):
    a = 2 / (span + 1)
    return 1 - a**2 / (1 - (1 - a) ** 2)


s = pd.Series(np.arange(100))
for span in [2, 5, 12]:
    ewm = s.ewm(span=span, adjust=False)
    tm.assert_almost_equal(
        (ewm.var(bias=True) / ewm.var(bias=False)).iloc[-1],
        bias_factor(span),
        atol=1e-12,
        rtol=0,
    )
```
Of course here I'm setting `adjust=False` just so I can have a simple expression for the `bias_factor` as a function of the `span`. IIRC in the default case Pandas does bias adjustment based on the actual waits as stated generally above.

**Comment by max-sixty** [comment]
@torext thank you very much for the full & fast response. You're ofc completely correct re the weighing, and so the assumption above re using n-effective being incorrect.

Let me reflect on the best way to represent that in the numba routine — ideally we could maintain a `w^2` term...

**Comment by torext** [comment]
@max-sixty Sounds good, glad it was helpful!
