### ISSUE TITLE
BUILD: pandas[performance] doesn't limit numexpr to 2.8.4

### ISSUE THREAD

**Issue by rootsmusic** [pandas-dev/pandas#55285]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

win-64

### Installation Method

pip install

### pandas Version

2.1.1

### Python Version

3.10.11

### Installation Logs

`pip install pandas[performance]` installs numexpr 2.8.6.  However, its version is supposed to be [limited to 2.8.4](https://github.com/PyPSA/PyPSA/pull/714).

**Comment by mroeschke** [comment]
Thanks but I don't think pandas should be pinning a dependency because there's a particular bug being hit in a downstream library. I think it's more appropriate for the 3rd party libraries to pin as needed so closign
