### ISSUE TITLE
ENH: Change Where() function into Search functionality

### ISSUE THREAD

**Issue by speed650** [pandas-dev/pandas#55298]
### Feature Type

- [ ] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I am learning Pandas and going over the different functions. 
The Where() function is the one that seems to bug me the most. In most frameworks where is used for search. 
e.g Select * where name==bob;  

In pandas Where() takes in a function and replaces the value with another value when false, which takes one of the most popular functions from other languages / frameworks and basically makes it something you will never use.

### Feature Description

I suggest that the current functionality should be combined with the Mask() function. You can give it an additional property called MASK(,  Inverse=True) so it finds the false values.

The Where() function should work more like the Replace() function where you pass it a list or a search function and it returns the matching values. 

### Alternative Solutions

df['NAMES'].Where[ ['BOB', 'JANE']  ]
df.Where[ df.names=='Bob' ]

**Comment by mroeschke** [comment]
Thanks for the request but it appears this hasn't gotten traction in a while so closing
