### ISSUE TITLE
ENH: pandas.DataFrame.isin() should throw an error/warning when the list of columns is missing a comma.

### ISSUE THREAD

**Issue by sam-burck** [pandas-dev/pandas#55307]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

If I pass a list containing column names to .isin(), and I'm missing a comma between column names, .isin() appears to ignore those columns, based on observations taken afterwords using .value_counts()

### Feature Description

Pandas should check the formatting of this argument.

### Alternative Solutions

This could be implemented using regular expressions.

**Comment by mroeschke** [comment]
Thanks for the suggestion but I don't think this is a wise thing to do in pandas. `isin` takes the values as is as any value may be a valid match to search - another user may want to match a value without a comma. Thanks but closing
