### ISSUE TITLE
DOC: Issue triage updates

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#55311]
Documentation: https://pandas.pydata.org/pandas-docs/stable/development/maintaining.html#issue-triage

- Step 3: There is no milestone "No Action". This should be removed.
- Step 4: I think part of issue triage should be to ensure the issue exists on main, and that the "Needs Triage" tag should remain until it's been done. If the user is reporting a regression, a git bisect should also be run. These should be added.
- Step 5: For new feature requests, I think we should generally triage them as "Needs Discussion" until they are agreed upon. I think this should be added.
- Step 7: We no longer have a Contributions Welcome milestone, this should be removed.

I think an instruction at the top of this section to the effect of 

> Only remove the "Needs Triage" tag when you have completed all the steps below. However do not feel like you must complete every one - even partially triaging an issue is a great help to the maintenance of pandas.

cc @noatamir @MarcoGorelli @Dr-Irv for any thoughts

**Comment by Dr-Irv** [comment]
For Step 4, if you want to add a `git bisect` task as part of triage, then we have to provide instructions on how to do that.
For Step 5, agree on the "Needs Discussion" tag.  Should we add a tag related to "Possible PDEP" ?
For Step 7, maybe we should have a tag of "Contributions Welcome" instead?

**Comment by rhshadrach** [comment]
> For Step 4, if you want to add a `git bisect` task as part of triage, then we have to provide instructions on how to do that.

That's here: https://pandas.pydata.org/pandas-docs/stable/development/maintaining.html#investigating-regressions

> Should we add a tag related to "Possible PDEP" ?

I personally don't see how such a tag would be useful. Is there a use case you're thinking of?

> For Step 7, maybe we should have a tag of "Contributions Welcome" instead?

I'm not opposed, but that's more or less going back on removing the Milestone. Not sure what motivated that, but we should make sure we get those who removed it on board.

**Comment by mroeschke** [comment]
> Not sure what motivated that, but we should make sure we get those who removed it on board.

Originally I was motivated to remove it because

1. It was a milestone originally when milestones should be reserved for release versions
2. I feel like almost any issue not labeled `Needs *` welcomes contributions. Maybe that should be clarified in the contribution docs

I would also suggest disabling the `take` command if a `Needs *` label still exists to make it clear that an issue still needs a look & decision before moving forward with a PR

**Comment by rhshadrach** [comment]
> 2\. I feel like almost any issue not labeled `Needs *` welcomes contributions. Maybe that should be clarified in the contribution docs

This makes sense to me. I'm on board with not having a Contributions Welcome tag.

**Comment by Dr-Irv** [comment]
> > For Step 4, if you want to add a `git bisect` task as part of triage, then we have to provide instructions on how to do that.
> 
> That's here: https://pandas.pydata.org/pandas-docs/stable/development/maintaining.html#investigating-regressions

Looking at those instructions, they are still using `setup.py` .  Can they be modified to reflect using meson?  
> 
> > Should we add a tag related to "Possible PDEP" ?
> 
> I personally don't see how such a tag would be useful. Is there a use case you're thinking of?

If someone comes up with an idea for adding to the API, then we'd probably do a PDEP for that.  Step 4 reads "Encourage the submitter to include a proposed API for the new feature. Having them write a full docstring is a good way to pin down specifics.".  So to me that is something we would want to do a PDEP for.  That's why I wrote "Possible PDEP" as an additional label to "Needs discussion"

> 
> > For Step 7, maybe we should have a tag of "Contributions Welcome" instead?
> 
> I'm not opposed, but that's more or less going back on removing the Milestone. Not sure what motivated that, but we should make sure we get those who removed it on board.

Seeing discussion above, I'm fine with not adding that tag.

**Comment by rhshadrach** [comment]
> That's why I wrote "Possible PDEP" as an additional label to "Needs discussion"

I understand this is a scenario where an issue could possibly be turned into a PDEP. My question is only if it's useful to have a label signifying that. Labels are useful to me in searching and filtering - I have a hard time imagining a scenario where I'm looking for enhancements that could possibly be turned into a PDEP. That's why, for me, I don't think we need a label - Enhancement is enough.

**Comment by lithomas1** [comment]
> Looking at those instructions, they are still using `setup.py` . Can they be modified to reflect using meson?

@phofl Can you share what you ended up with? I remember you asking on slack about this.

**Comment by Dr-Irv** [comment]
> I understand this is a scenario where an issue could possibly be turned into a PDEP. My question is only if it's useful to have a label signifying that. Labels are useful to me in searching and filtering - I have a hard time imagining a scenario where I'm looking for enhancements that could possibly be turned into a PDEP. That's why, for me, I don't think we need a label - Enhancement and Needs Discussion is enough.

I was thinking of the label that says "if we're going to do this, then we have to determine whether a PDEP is required."  Without that label, someone might grab the issue and implement the enhancement, and then we'd reject the PR because we think a PDEP was warranted.

**Comment by rhshadrach** [comment]
> Without that label, someone might grab the issue and implement the enhancement, and then we'd reject the PR because we think a PDEP was warranted.

Isn't that what Needs Discussion is for?

**Comment by rhshadrach** [comment]
> Looking at those instructions, they are still using `setup.py` . Can they be modified to reflect using meson?

I've opened #55318

**Comment by Dr-Irv** [comment]
> > Without that label, someone might grab the issue and implement the enhancement, and then we'd reject the PR because we think a PDEP was warranted.
> 
> Isn't that what Needs Discussion is for?

Sure.  I'm OK with that if that's the meaning we all agree to.

**Comment by divyanshsharma2280** [comment]
Can i work on this issue ?

**Comment by buddhiraz** [comment]
take Can I work on this?
