### ISSUE TITLE
BUG: FutureWarning when creating column of tz aware datetime values using pandas.DataFrame.loc

### ISSUE THREAD

**Issue by OleFass** [pandas-dev/pandas#55317]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
from datetime import datetime as dt
from datetime import timezone

df = pd.DataFrame([{'id': 1},{'id': 2},{'id': 3}])
_time = dt.utcfromtimestamp(1695887042)
_time = _time.replace(tzinfo=timezone.utc)
df.loc[df.id>=2, 'time'] = _time
```

### Issue Description

When adding a column of tz aware datetime values using the `pandas.DataFrame.loc` method the following warning appears. The warning occurs for pandas version 2.1.1 and 2.2.0 but not for 2.0.3. When the timezone is not replaced the warning does not appear.

`FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '2023-09-28 07:44:10+00:00' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  df.loc[df.id>=2, 'time'] = _time`

### Expected Behavior

Adding a column of tz aware datetime values via `pandas.DataFrame.loc` shouldn't  raise a warning.

### Installed Versions

2.1.1 & 2.2.0

**Comment by MarcoGorelli** [comment]
The warning looks correct here - if you look at the resulting dtype, it's `object`, and not `datetime64[ns, UTC]` :
```python
df = pd.DataFrame([{'id': 1},{'id': 2},{'id': 3}])
_time = dt.utcfromtimestamp(1695887042)
_time = _time.replace(tzinfo=timezone.utc)
df.loc[df.id>=2, 'time'] = _time
print(df)
print(df.dtypes)
```

```python
   id                       time
0   1                        NaT
1   2  2023-09-28 07:44:02+00:00
2   3  2023-09-28 07:44:02+00:00
id       int64
time    object
dtype: object
```

Pandas columns can't handle multiple time zones - the warning is there to let you know that the resulting dtype will be `object`, and that in the future this will raise

I'd suggest first making a new column with your given time zone:
```python
df = pd.DataFrame([{'id': 1},{'id': 2},{'id': 3}])
_time = dt.utcfromtimestamp(1695887042)
_time = _time.replace(tzinfo=timezone.utc)
df['time'] = pd.NaT
df['time'] = df['time'].dt.tz_localize('UTC')
df.loc[df.id>=2, 'time'] = _time
print(df)
print(df.dtypes)
```

Then you'll get output that's `datetime[ns, UTC]` dtype and so it actually useful (unlike `object` which is just a "passenger")

```python
   id                      time
0   1                       NaT
1   2 2023-09-28 07:44:02+00:00
2   3 2023-09-28 07:44:02+00:00
id                    int64
time    datetime64[ns, UTC]
dtype: object
```

**Comment by MarcoGorelli** [comment]
closing in favour of https://github.com/pandas-dev/pandas/issues/55423 then - given that https://github.com/pandas-dev/pandas/issues/55423 exists, the warning is correct. but it would be nice if https://github.com/pandas-dev/pandas/issues/55423 didn't exist in the first place
