### ISSUE TITLE
DOC: Update contributing docs on git bisect

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#55318]
Ref: https://github.com/pandas-dev/pandas/issues/55311#issuecomment-1738132652

Documentation: https://pandas.pydata.org/pandas-docs/stable/development/maintaining.html#investigating-regressions

> Looking at those instructions, they are still using `setup.py` . Can they be modified to reflect using meson?

Not sure if we should keep the setup.py instructions and also have meson as well - or if we should switch to meson-only.

**Comment by KartikeyBartwal** [comment]
Starting to brawl with this issue

**Comment by suresh33661** [comment]
take

**Comment by Aloqeely** [comment]
#57917 switched to meson-only instructions, should this be closed?

**Comment by rhshadrach** [comment]
Yep - thanks @Aloqeely
