### ISSUE TITLE
ENH: Add list accessor for PyArrow list types to support __getitem__

### ISSUE THREAD

**Issue by PabloRuizCuevas** [pandas-dev/pandas#55323]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pyarrow as pa

# works
pd.Series(["tsht(thsat","gda(gr"]).str.split("(").str[0]
# works
pd.Series(["tsht(thsat","gda(gr"], dtype="string[pyarrow]").str.split("(").str[0]
# fails
pd.Series(["tsht(thsat","gda(gr"], dtype=pd.ArrowDtype(pa.string())).str.split("(").str[0]
```

### Issue Description

    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!

### Expected Behavior

pd.Series(["tsht(thsat","gda(gr"], dtype=pd.ArrowDtype(pa.string())).str.split("(").str[0]

should do the same as the rest, also i would not use pd.ArrowDtype(pa.string(), but it just happens to be the default datatype when reading a file using pd.read_excel.

### Installed Versions

<details>

DEBUG - matplotlib: matplotlib data path: C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\matplotlib\mpl-data
DEBUG - matplotlib: CONFIGDIR=C:\Users\PabloRuiz\.matplotlib
DEBUG - matplotlib: interactive is False
DEBUG - matplotlib: platform is win32
INSTALLED VERSIONS
------------------
commit              : e86ed377639948c64c429059127bcf5b359ab6be
python              : 3.11.1.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.19045
machine             : AMD64
processor           : Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : English_United States.1252
pandas              : 2.1.1
numpy               : 1.26.0
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.2.2
pip                 : 22.3.1
Cython              : None
pytest              : 7.4.2
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : 3.1.4
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.15.0
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.8.0
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : 3.1.3
pandas_gbq          : None
pyarrow             : 13.0.0
pyreadstat          : None
pyxlsb              : 1.0.10
s3fs                : None
scipy               : None
sqlalchemy          : 1.4.31
tables              : None
tabulate            : None
xarray              : None
xlrd                : 2.0.1
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by sawanthmythrey1** [comment]
@PabloRuizCuevas 

Please find the corrected code, "pd.ArrowDtype(pa.string())" is not recognised as string datatype, so you need to convert this into string before performing other operations
pd.Series(["tsht(thsat","gda(gr"], dtype=pd.ArrowDtype(pa.string())).**astype(str)**.str.split("(").str[0]

**Comment by mroeschke** [comment]
Thanks for the report @PabloRuizCuevas. The subtlety here is that the `str` accessor works on object types which is returned by  `dtype="string[pyarrow]")` or `dtype=object)` after the split call.

For `dtype=pd.ArrowDtype(pa.string()))`, pandas will probably need to develop a `list` accessor so we can support `__getitem__`, so going to repurpose as a enhancement request

**Comment by samukweku** [comment]
Is it ok to extend this with aggregation options, such as summing all entries in the list (homogenous lists)

**Comment by mroeschke** [comment]
> Is it ok to extend this with aggregation options

I would hold off on adding this functionality immediately; it would be useful to get more buy-in from the other core devs. While I see the utility, it doesn't strike me as a generic list operation

**Comment by Mohamad-fcz** [comment]
Encountered the same issue. Please enhance the pyarrow list accessor.

**Comment by rohanjain101** [comment]
I have initial implementation in https://github.com/pandas-dev/pandas/pull/55777, I am just working on adding docstrings + examples.
