### ISSUE TITLE
BUG: pd.Timestamp constructor sometimes ignores `unit` parameter

### ISSUE THREAD

**Issue by AdrianDAlessandro** [pandas-dev/pandas#55375]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
print(pd.Timestamp("1975-01-01", unit="D").unit) # <-- Returns 's'
print(pd.Timestamp(1975,1,1, unit="D").unit) # <-- Returns 'us'
print(pd.Timestamp(0, unit="D").unit) # <-- Returns 's'
```

### Issue Description

Using the `unit` parameter in the `pd.Timestamp` constructor appears to do nothing for some inputs, or incorrectly change the default for others

The three in the example above:
- string input -> remains unchanged from default of `'s'`
- y,m,d input -> remains unchanged from default of `'ms'`
- integer input -> changes incorrectly from default of `'ns'`

### Expected Behavior

The return value should have the requested unit type, or raise an error if the unit type is wrong/incompatible

It currently work with integer input for certain units (ie milliseconds):

```python
import pandas as pd
print(pd.Timestamp(0, unit="ms").unit) # <-- Returns 'ms'
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : 77bc67a3a794cc4d7cf3c318e70292fceb65eab7
python              : 3.11.1.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 22.6.0
Version             : Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
machine             : arm64
processor           : arm
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 0+untagged.33100.g77bc67a.dirty
numpy               : 1.24.4
pytz                : 2023.3
dateutil            : 2.8.2
setuptools          : 65.5.0
pip                 : 23.2.1
Cython              : 0.29.33
pytest              : 7.4.0
hypothesis          : 6.82.5
sphinx              : 6.2.1
blosc               : 1.11.1
feather             : None
xlsxwriter          : 3.1.2
lxml.etree          : 4.9.3
html5lib            : 1.1
pymysql             : 1.4.6
psycopg2            : 2.9.7
jinja2              : 3.1.2
IPython             : 8.14.0
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : 1.3.7
dataframe-api-compat: None
fastparquet         : 2023.7.0
fsspec              : 2023.6.0
gcsfs               : 2023.6.0
matplotlib          : 3.7.2
numba               : 0.57.1
numexpr             : 2.8.5
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : 12.0.1
pyreadstat          : 1.2.2
python-calamine     : None
pyxlsb              : 1.0.10
s3fs                : 2023.6.0
scipy               : 1.11.2
sqlalchemy          : 2.0.20
tables              : None
tabulate            : 0.9.0
xarray              : 2023.7.0
xlrd                : 2.0.1
zstandard           : 0.21.0
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by mroeschke** [comment]
Thanks for the report but this is working as intended based on the docs: https://pandas.pydata.org/docs/reference/api/pandas.Timestamp.html

```
Unit used for conversion if ts_input is of type int or float.

For float inputs, the result will be stored in nanoseconds, and the unit attribute will be set as 'ns'.
```

If you want to set the `.unit` attribute on the Timestamp, you should use `as_unit`

**Comment by AdrianDAlessandro** [comment]
The third example I gave was using integer input and it still wasn't consistent:

```python
import pandas as pd
print(pd.Timestamp(0, unit="D").unit) # <-- Returns 's'
```

If the intended behaviour is for `unit` to only be used with integer and float input, then shouldn't it raise an error or warning if used outside of that use case?

Thank you for the tip about using `as_unit`. Is this the recommended approach? Is there any need for the `unit` parameter to exist at all if its behaviour is inconsistent and it isn't the recommended approach?

**Comment by mroeschke** [comment]
The `unit` argument is just a convenience API to essentially convert ints/float into a duration and add to the epoch timestamp to create a `Timestamp`. It doesn't have any barring on the resulting unit. The resulting `unit` attribute is determined by inferring the resulting Timestamp based on the resolution of the components.

If you want to dictate the unit attributes, it's recommended to use `as_unit` after construction
