### ISSUE TITLE
BUG: DataFrame.to_json OverflowError with np.long* dtypes

### ISSUE THREAD

**Issue by nmacholl** [pandas-dev/pandas#55403]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import sys
import pandas as pd
import numpy as np

df = pd.DataFrame(
    np.random.randint(0, 100, size=(10, 1)),
    dtype=np.longdouble,
)

df.to_json(sys.stdout)
```

### Issue Description

Calling `DataFrame.to_json()` on a DataFrame with a `dtype=np.longdouble` or `dtype=np.longfloat` causes an `OverflowError: Maximum recursion level reached` error. This seems to be the result of the JSON serializer not handling these types; `DataFrame.to_csv()` is not affected by this issue.

### Expected Behavior

These types should be serialized as floats, or at a minimum, the recursion error should be fixed and a more appropriate serialization error should be raised.

### Installed Versions

INSTALLED VERSIONS
------------------
commit              : e86ed377639948c64c429059127bcf5b359ab6be
python              : 3.10.9.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 22.6.0
Version             : Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
machine             : arm64
processor           : arm
byteorder           : little
LC_ALL              : en_US.UTF-8
LANG                : None
LOCALE              : en_US.UTF-8

pandas              : 2.1.1
numpy               : 1.26.0
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.1.2
pip                 : 23.2.1
Cython              : None
pytest              : 7.4.2
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : None
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : 0.21.0
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

**Comment by paulreece** [comment]
I can confirm this bug occurs on the main development branch.  

```Python
>>> df = pd.DataFrame(
...     np.random.randint(0, 100, size=(10, 1)),
...     dtype=np.longdouble,
... )
>>> df.to_json(sys.stdout)
Traceback (most recent call last):
...
OverflowError: Maximum recursion level reached
>>> df = pd.DataFrame(
...     np.random.randint(0, 100, size=(10, 1)),
...     dtype=np.longfloat,
... )
>>> df.to_json(sys.stdout)
Traceback (most recent call last):
...
OverflowError: Maximum recursion level reached
```

**Comment by gupta-paras** [comment]
take
