### ISSUE TITLE
ENH: pandas.empty_like()

### ISSUE THREAD

**Issue by michaelbrundage** [pandas-dev/pandas#55404]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

`pandas` needs an `empty_like()` method comparable to [`numpy.empty_like()`](https://numpy.org/doc/stable/reference/generated/numpy.empty_like.html) to make it easy for users to create empty `DataFrame`, `Series`, etc with the same characteristics as another.

### Feature Description

```
import pandas as pd

# This seems to work in very limited testing.
# Probably fails on many edge cases and anyway doesn't handle
# `Series` or other `pandas` objects as input.
def empty_like(df: pd.DataFrame) -> pd.DataFrame:
    result = pd.DataFrame(columns=df.columns)
    for col, dtype in df.dtypes.items():
        if dtype == "object":
            dtype = "str"
        result[col] = result[col].astype(dtype)
    return result
```

### Alternative Solutions

That was my third try. These didn't work:

```
import numpy as np
import pandas as pd

# exception when `df` has string columns (`dtypes` outputs `object` which `dtype` input rejects)
def empty_like(df: pd.DataFrame) -> pd.DataFrame:
    return pd.DataFrame(columns=df.columns, dtype=df.dtypes)

# SEGV or all `object`-typed columns, depending on the `numpy` version
def empty_like(df: pd.DataFrame) -> pd.DataFrame:
    return pd.DataFrame(np.empty_like(df.values), columns=df.columns)
```

**Comment by phofl** [comment]
``df.iloc[:0]`` should do what you are looking for

**Comment by michaelbrundage** [comment]
Clever, thanks! Yes, `df.iloc[:0].copy()` seems to do the trick.
