### ISSUE TITLE
DEPR: Index.format?

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#55413]
Does anyone actually use this?  Internally we use it for some html/latex rendering but we don't use most of the keywords so it would be simpler to refactor to use a private method for those.

I've been trying to unravel the various EA formatting methods to try to use the same patterns everywhere, align keywords, etc.  Doing this for Index.format wouldn't be _that_ hard, but it would be easier to just deprecate it if it isn't used externally.

**Comment by lithomas1** [comment]
It's used externally.

Github code search shows at least catboost uses it

https://github.com/catboost/catboost/blob/922ad64b4f09a13be5e0310709833e1f63fa7140/contrib/python/pandas/py3/pandas/io/formats/format.py#L365-L374

There are a couple others too, see
https://github.com/search?q=index.format+language%3APython&type=code&l=Python

**Comment by jbrockmendel** [comment]
The catboost example looks like they just vendored all of pandas.  The others are look like largely matches on the word "format" which isn't using our Index.format.

**Comment by lithomas1** [comment]
My bad, there seem to be a lot of false positives from Github code search.

I think this one is an actual usage
https://github.com/couchbase/ns_server/blob/9a336e9ff90d7634807f1b8c513160e8bbe71793/scripts/pressure_from_stats.py#L186

(not that it's a widely used project, just pointing out the existence of code that uses format)

**Comment by lithomas1** [comment]
At any rate, I don't really care too much if this is deprecated, though.

**Comment by rhshadrach** [comment]
cc @attack68

**Comment by attack68** [comment]
This is used in one place in Styler rendering internally. This is code that predates me, but it's used to be able to get positions in an index so that Styler can display sparsified output.

```
    if isinstance(index, MultiIndex):
        levels = index.format(sparsify=lib.no_default, adjoin=False)
    else:
        levels = index.format()
```

**Comment by rhshadrach** [comment]
@attack - just in case you missed it, this is from the OP

> we don't use most of the keywords so it would be simpler to refactor to use a private method for those.

So I take it you have no objection to making it internal.

**Comment by attack68** [comment]
no objection at all to the refactor
