### ISSUE TITLE
BUILD: Pandas now install dependencies by default that have conflicting licensing with MIT

### ISSUE THREAD

**Issue by 12rambau** [pandas-dev/pandas#55424]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

N/A

### Installation Method

pip install

### pandas Version

2.1.1

### Python Version

3.11

### Installation Logs

I have a pipeline that started to break recently. I'm checking the compatibility of my tool licences and now pip installation of pandas depends on pyQT5 that is under GPL3. 

My first question is why has it changed ? is it by default using the [all] extra requires ? 
And then How can I go back to the previous simple installation, I definitely never need pyQT5 ?

**Comment by lithomas1** [comment]
pyqt5 is not a required or explicitly listed as an optional dependency of pandas. I guess one of the optional dependencies is pulling it in somehow.

Can you please provide more information on how you're installing pandas?

(If you're using [all], you can just install the optional dependencies you need by hand.)

**Comment by 12rambau** [comment]
After careful review of my issue I realized that the pyQT5 is effectively not installed. I guess the way LicenceCheck analyses the nested dependency is not friendly with the new extra dependencies.
I opened an issue on their side and I will update this issue with the related informations. Sorry for the noise.

**Comment by lithomas1** [comment]
No problem. Glad it all worked out.
