### ISSUE TITLE
DOC: Add docstrings for MultiIndex.levels and MultiIndex.codes

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#55435]
xref #55148

Seems like those docstrings are empty, we should create them.

See the attributes section here: https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html

The docstring for `MultiIndex.levels should include information to make clear that levels are preserved even if the dataframe using the index doesn't contain all levels. See this page in the docs: https://pandas.pydata.org/docs/user_guide/advanced.html#defined-levels and this comment: https://github.com/pandas-dev/pandas/pull/55433#pullrequestreview-1663040010

**Comment by shiersansi** [comment]
This is the second time I've brought up pr in an open source project, so I misunderstood what you meant, and I'll finish the issue again.

**Comment by datapythonista** [comment]
It's normal, and the issue was difficult to follow, since it was a discussion, but I think the new issue explains better what needs to be done. If you have any question or you need help we are here to help. Thank you!

**Comment by datapythonista** [comment]
We've got now the docstring for `MultiIndex.levels`, but the one for `MultiIndex.codes` is still missing. Labelling this as good first issue in case anyone wants to help.

**Comment by mileslow** [comment]
take

**Comment by Rollingterminator1** [comment]
Hi mileslow do you still need time for this task, or do you mind if I work on it?

**Comment by mileslow** [comment]
@Rollingterminator1 go for it.

**Comment by devanshi-jain** [comment]
Hi, is this issue already taken care of?

**Comment by sathyaanurag** [comment]
Hi, does this issue still need to be worked on?

**Comment by wasimtikki120** [comment]
class MultiIndex:
    """
    A multi-level, or hierarchical, index object for pandas DataFrame.

    ...

    Attributes
    ----------
    levels : list
        List of Index objects containing the unique values for each level of the MultiIndex.
    codes : list
        List of arrays containing the codes that indicate the position of each element in the levels.

    ...

    Examples
    --------
    >>> arrays = [['A', 'A', 'B', 'B'], [1, 2, 1, 2]]
    >>> tuples = list(zip(*arrays))
    >>> index = pd.MultiIndex.from_tuples(tuples, names=('first', 'second'))
    >>> index
    MultiIndex([('A', 1),
                ('A', 2),
                ('B', 1),
                ('B', 2)],
               names=['first', 'second'])

    >>> index.levels
    [Index(['A', 'B'], dtype='object', name='first'),
     Int64Index([1, 2], dtype='int64', name='second')]

    >>> index.codes
    [array([0, 0, 1, 1], dtype=int8),
     array([0, 1, 0, 1], dtype=int8)]
    """

    def __init__(self, levels, codes):
        """
        Parameters
        ----------
        levels : list
            List of Index objects containing the unique values for each level of the MultiIndex.
        codes : list
            List of arrays containing the codes that indicate the position of each element in the levels.
        """
        self.levels = levels
        self.codes = codes

**Comment by Arpan3323** [comment]
take

**Comment by chethanc1011** [comment]
take

**Comment by dwk601** [comment]
Hi, I would like to contribute.

**Comment by sjalkote** [comment]
Hi, looks like this has been inactive for a while so I'd like to try it

**Comment by sjalkote** [comment]
take

**Comment by sjalkote** [comment]
Ah it looks like there is already a docstring for `MultiIndex.codes` present in the main branch. Seems like this has already been fixed.
https://github.com/pandas-dev/pandas/blob/b1525c4a3788d161653b04a71a84e44847bedc1b/pandas/core/indexes/multi.py#L1080-L1102

**Comment by sam-baumann** [comment]
take

**Comment by sam-baumann** [comment]
Looks like #57601 fixed this - can we close this?

**Comment by sam-baumann** [comment]
@datapythonista can we close this? Looks like was solved by #57601

**Comment by GAuravY19** [comment]
is the issue still open ?

**Comment by Aloqeely** [comment]
> is the issue still open ?

The docstrings have been added, but there are many more issues labeled with 'Docs' that we would appreciate your help on
