### ISSUE TITLE
DOC: Move bug fixes in whatsnew for 2.2.0 into the appropriate subsection

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#55436]
We've started adding any bug fixes directly below the `Bug fixes` section rather than in the proper subsection they belong.

https://github.com/pandas-dev/pandas/blob/21689e5fabf1a75f66948d5da35aa4cef97af416/doc/source/whatsnew/v2.2.0.rst?plain=1#L279-L287

Each of the notes in the lines above should be moved to an appropriate subsection below.

**Comment by KalebMaraccini** [comment]
Take
