### ISSUE TITLE
ENH: reorder categories partially

### ISSUE THREAD

**Issue by kwhkim** [pandas-dev/pandas#55471]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

`x.cat.reorder_categories()` requires all categories in order. I want to reorder categories with only some of categories specified in desired order.

### Feature Description

I already implemented, sorta,

```
def reorder_cat_partial(x, orders_new):
    if isinstance(x, pd.Series):
        cat_remains = ~(x.cat.categories.isin(orders_new))
        cat_new = x.cat.categories.values.copy()
        cat_new[~cat_remains] = orders_new
        return x.cat.reorder_categories(cat_new)
    elif isinstance(x, pd.Categorical):
        cat_remains = ~(x.categories.isin(orders_new))
        cat_new = x.categories.values.copy()
        cat_new[~cat_remains] = orders_new
        return x.reorder_categories(cat_new)
```

Accord to the result of the following codes, it works just fine in the following cases,

```
x0 = pd.Series(['a', 'b', 3, 4], dtype = 'category')
reorder_cat_partial(x0, ['b',3])

x  = pd.Series(list('abbdeedfabcdef'), 
               dtype = 'category').cat.as_ordered()
x

reorder_cat_partial(x, ['f', 'b', 'd'])
```

### Alternative Solutions

May we can redefine `cat.reorder_categories()` to specify some of categories to be reordered

PS) I'd like to be assigned for this task

**Comment by mroeschke** [comment]
Thanks for the request but it appears this hasn't gotten traction in a while so closing
