### ISSUE TITLE
BUG: pandas.read_excel() with dtype=object is broken in pandas 2.1.1

### ISSUE THREAD

**Issue by VisualDev-FR** [pandas-dev/pandas#55489]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

Create an excel file nammed `xl_file.xlsx`, with one worksheet named ``Sheet1`` as following:

|    A    |      B      |   C    |
|---------|-------------|--------|
|    2    | 'dummy_str  |        |

Then save it and run this code in the directory where you created the excel file :

```python
import pandas as pd
from pathlib import Path

df = pd.read_excel(
    io=Path("xl_file.xlsx"),
    sheet_name="Sheet1",
    dtype=object,
)

dtypes_1 = df.dtypes
dtypes_2 = df.fillna("").dtypes
```

``` python
>>> print(dtypes_1)
0   A    object # <- expected int, or int64
1   B    object
2   C    object
```

``` python
>>> print(dtypes_2)
0   A     int64 # <- when we use df.fillna(""), we have the expected behavior
1   B    object
2   C    object
```

### Issue Description

The method ``pandas.read_excel()`` with argument ``dtypes=object`` does not prevent pandas from converting data types, as described on the [offical documentation page](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html)

### Expected Behavior

when we use the method ``pandas.read_excel()`` with argument ``dtypes=object``, on an Excel workbook which contains int values, the dtypes of this columns should be ``int64``

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit              : e86ed377639948c64c429059127bcf5b359ab6be
python              : 3.11.5.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.19044
machine             : AMD64
processor           : Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
byteorder           : little
LC_ALL              : None
LANG                : fr_FR.UTF-8
LOCALE              : fr_FR.cp1252

pandas              : 2.1.1
numpy               : 1.24.2
pytz                : 2023.3
dateutil            : 2.8.2
setuptools          : 65.5.0
pip                 : 23.2.1
Cython              : None
pytest              : 7.3.1
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : 3.1.7
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : None
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by asishm-wk** [comment]
Can you share the excel file directly or a way to generate the excel file, e.g. using `pd.DataFrame(...).to_excel(...)` , that reproduces the issue?

**Comment by rhshadrach** [comment]
Thanks for the report, is specifying `dtype=None` expected to be the same as `dtype=object`?

**Comment by rhshadrach** [comment]
cc @WillAyd

**Comment by rhshadrach** [comment]
This was added in https://github.com/pandas-dev/pandas/commit/588e29d23fa289916a8b057d093af62f35c6dcf6. I think this is behaving as expected.

```
df = pd.DataFrame({'a': [1, 1, 2], 'b': ['x', 'y', 'z']})
df.to_excel('test.xlsx')
print(type(pd.read_excel('test.xlsx', dtype=object).iloc[0, 1]))
# <class 'int'>
```

There is no inference done - _including_ inferring that the value is an integer! So we must store them as Python objects, but they are indeed Python ints.

I think the doc could be clarified better - explicitly mentioning that the result will be object dtype.

**Comment by aryanVanaik** [comment]
Hi, could I work on this, would you prefer to change the docs maybe perhaps pointing me in the right direction

**Comment by rhshadrach** [comment]
Certainly! See [the contributor guide](https://pandas.pydata.org/pandas-docs/dev/development/contributing_documentation.html).

For this particular issue, we're looking to better explain that specifying `dtype=object` will result in a DataFrame with object dtype. Perhaps just adding `This will necessarily result in ``object`` dtype` in the docstring?

**Comment by aryanVanaik** [comment]
perfect ill get that done :)

**Comment by gadeatric** [comment]
Hi, @rhshadrach ! As I saw that the issue was still open, [I decided to fix it considering the previous attempts](https://github.com/pandas-dev/pandas/pull/55757) , I hope that's OK - let me know if you have any questions or clarifications. Thanks! :)
