### ISSUE TITLE
ENH: add reader/writer for Apple Numbers

### ISSUE THREAD

**Issue by masaccio** [pandas-dev/pandas#55497]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Much like `pandas.read_excel()` and `pandas.write_excel()`, I'd like to be able to create and export a `DataFrame` from/to an Apple Numbers spreadsheet. The file format is undocumented, but I do have a stable package [numbers-parser](https://github.com/masaccio/numbers-parser) which can read and write files for Numbers.

### Feature Description

I am volunteering to implement this since I am the author of the library that supports this format.

Is there an established pattern for adding readers? I'd like to develop and contribute a new reader/writer for Apple Numbers spreadsheets. I am looking to avoid just dumping a full implementation (I have yet to start) as I expect that reviewing that against an alien API will be very time consuming.

I can see pandas uses xtests in pytest a lot, so I guess some stubs in `pandas.io` plus API tests in pytest with doc strings would be a start? Then incrementally add reader options.

Or would something else work better as an approach?

### Alternative Solutions

This is using a 3rd party package. I'd load with `import_optional_dependency()` and export `read_apple_numbers()` and `write_apple_numbers()` into the `pandas` namespace.

**Comment by phofl** [comment]
Any reason for not doing this as a 3rd party package? The pandas-gbq would be something that you can look at where this is done as well

**Comment by masaccio** [comment]
Given all the existing read_*() methods, I figured this was a typical integration. If that’s not how integrations happen these days with pandas, that’s fine by me. Closing as not planned.
