### ISSUE TITLE
BUG: ModuleNotFoundError: No module named 'pandas._libs.interval'

### ISSUE THREAD

**Issue by manyv** [pandas-dev/pandas#55517]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python310\lib\site-packages\pandas\__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "C:\Program Files\Python310\lib\site-packages\pandas\compat\__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "C:\Program Files\Python310\lib\site-packages\pandas\compat\numpy\__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "C:\Program Files\Python310\lib\site-packages\pandas\util\__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "C:\Program Files\Python310\lib\site-packages\pandas\util\_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "C:\Program Files\Python310\lib\site-packages\pandas\_libs\__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
ModuleNotFoundError: No module named 'pandas._libs.interval'
```

### Issue Description

I had installed pandas but when I import a problem occured.And I can't find 'setup.py'.

### Expected Behavior

ModuleNotFoundError: No module named 'pandas._libs.interval'

### Installed Versions

ModuleNotFoundError: No module named 'pandas._libs.interval'

**Comment by rhshadrach** [comment]
Can you detail how you are installing pandas.

**Comment by manyv** [comment]
'pip install pandas'

**Comment by manyv** [comment]
> Can you detail how you are installing pandas.

pip install pandas

**Comment by manyv** [comment]
> Can you detail how you are installing pandas.
you see:
pip install pandas
Requirement already satisfied: pandas in c:\program files\python310\lib\site-packages (1.5.3)

**Comment by rhshadrach** [comment]
Can you include the output of this command.

**Comment by manyv** [comment]
> Can you include the output of this command. You will need to uninstall `pip uninstall pandas` and then reinstall.

I just do it many times,but it doesn't work.

**Comment by fanyang1997** [comment]
Please refer to the solution in this link, it may be helpful for your issue.
https://stackoverflow.com/questions/54093020/no-module-named-pandas-libs-tslib

**Comment by manyv** [comment]
> Please refer to the solution in this link, it may be helpful for your issue. https://stackoverflow.com/questions/54093020/no-module-named-pandas-libs-tslib

Thank you so mush!I eventually solved this problem by reading the passage that you share.Thank you again.

**Comment by mroeschke** [comment]
Closing as this isn't an issue in pandas
