### ISSUE TITLE
BUG: Unexpected result for Series.pow

### ISSUE THREAD

**Issue by rohanjain101** [pandas-dev/pandas#55512]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> k = pd.Series([2, None], dtype="int64[pyarrow]")
>>> k.pow(pd.NA, fill_value=3)
0    <NA>
1    <NA>
dtype: int64[pyarrow]
>>>
```

### Issue Description

The documentation for Series.pow states that the fill_value will fill in missing values in 1 series, but result will be missing if the value is missing in both left and right for a given index. In this example, at index 0, the value is missing only in the right series, so I would have expected this to be filled in and produced a series with values [8, pd.NA]

### Expected Behavior

I would expect pd.Series([8, pd.NA]) as the result. 

Using a series with all null instead of a scalar also produces the expected result:

```
>>> s = pd.Series([2,None], dtype="int8[pyarrow]")
>>> k = pd.Series([None, None], dtype="int64[pyarrow]")
>>> s.pow(k, fill_value=3)
0       8
1    <NA>
dtype: int64[pyarrow]
>>>
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : e86ed377639948c64c429059127bcf5b359ab6be
python              : 3.11.2.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.22621
machine             : AMD64
processor           : Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : English_United States.1252

pandas              : 2.1.1
numpy               : 1.25.2
pytz                : 2023.3
dateutil            : 2.8.2
setuptools          : 68.0.0
pip                 : 23.2.1
Cython              : None
pytest              : 7.0.1
hypothesis          : None
sphinx              : 4.2.0
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.14.0
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : 13.0.0
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : 0.9.0
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report! Confirmed on main, further investigations and PRs to fix are welcome.

**Comment by gupta-paras** [comment]
Investigation: The possible cause of issue is in below function: https://github.com/pandas-dev/pandas/blob/main/pandas/core/ops/array_ops.py#L269

Here for dtype="int8[pyarrow]" type native pow is called, however for dtype="float", meth: _na_arithmetic_op is called, which handles special cases like : pow(1, NA) is 1, etc.

**Comment by hvsesha** [comment]
Hi 
I tried this 

import pandas as pd

s1 = pd.Series([1,None], dtype="int8[pyarrow]")
s2 = pd.Series([None, 2])

# Expected result: [1, pd.NA]
actual_result = s1.pow(pd.NA, fill_value=3)

print(actual_result)
