### ISSUE TITLE
VOTE: Voting issue for PDEP-7: Consistent copy/view semantics in pandas with Copy-on-Write

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#55511]
Issue to track the votes for PDEP-7: Consistent copy/view semantics in pandas with Copy-on-Write

Pull request with the PDEP discussion:  https://github.com/pandas-dev/pandas/pull/51463/ 
In this case, there is also the pre-PDEP discussion at https://github.com/pandas-dev/pandas/issues/36195, implementation PR at https://github.com/pandas-dev/pandas/pull/46958 and overview of follow-up issues and PRs at https://github.com/pandas-dev/pandas/issues/48998

Rendered PDEP for easy reading: https://github.com/pandas-dev/pandas/blob/3954d3666448ff313cab44bf09e15022c6b0d5d1/web/pandas/pdeps/0007-copy-on-write.md

Cast your vote in a comment below.
 * +1: approve.
* 0: abstain.
   * Reason: A one sentence reason is required.
* -1: disapprove
   * Reason: A one sentence reason is required.
       - A disapprove vote requires prior participation in the linked issues/PRs.

Voting will close in 15 days, i.e., on October 28, 2023.

@pandas-dev/pandas-core

**Comment by mroeschke** [comment]
+1

**Comment by Dr-Irv** [comment]
+1

**Comment by phofl** [comment]
+1

**Comment by bashtage** [comment]
+1

**Comment by jbrockmendel** [comment]
+1

**Comment by lithomas1** [comment]
+1

**Comment by WillAyd** [comment]
+1

**Comment by rhshadrach** [comment]
+1

**Comment by lukemanley** [comment]
+1

**Comment by jreback** [comment]
+1

**Comment by attack68** [comment]
+1

**Comment by simonjayhawkins** [comment]
+1

**Comment by phofl** [comment]
Final vote is 13/0/0, so this is accepted
