### ISSUE TITLE
BUG: KeyError: "['(first, last)'] not found in axis"

### ISSUE THREAD

**Issue by Kmalathkar1296** [pandas-dev/pandas#55526]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
people = {
    "first":['sima', 'riya', 'sam'],
    "last":['sharma','sharma', 'joseph'],
    "email":['sima.sharma@gmail.com', 'riya.sharma@gmail.com', 'sam.jospeh@gmail.com']
}
df = pd.DataFrame(people)
df['full name']=df['first']+' '+df['last']
df.drop(columns=['first','last'],inplace=True)
df['first','last']=df['full name'].str.split(' ')
df = df.drop(columns=["('first','last')"], axis=1)
```

### Issue Description

Hi Team,
I have found an issue while dropping this "(first, last)" column from dataframe using pandas. And I am not able to rename the column name as well. Please let me know if there is any way to delete the column which has special brackets in the label names.

Thank,
KM

### Expected Behavior

It should drop that column.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : e86ed377639948c64c429059127bcf5b359ab6be
python              : 3.10.9.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.22621
machine             : AMD64
processor           : Intel64 Family 6 Model 126 Stepping 5, GenuineIntel
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : English_United States.1252

pandas              : 2.1.1
numpy               : 1.23.5
pytz                : 2022.7
dateutil            : 2.8.2
setuptools          : 65.6.3
pip                 : 22.3.1
Cython              : None
pytest              : 7.1.2
hypothesis          : None
sphinx              : 5.0.2
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : 4.9.1
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.10.0
pandas_datareader   : None
bs4                 : 4.11.1
bottleneck          : 1.3.5
dataframe-api-compat: None
fastparquet         : None
fsspec              : 2022.11.0
gcsfs               : None
matplotlib          : 3.7.0
numba               : 0.56.4
numexpr             : 2.8.4
odfpy               : None
openpyxl            : 3.0.10
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.10.0
sqlalchemy          : 1.4.39
tables              : 3.7.0
tabulate            : 0.8.10
xarray              : 2022.11.0
xlrd                : None
zstandard           : 0.19.0
tzdata              : 2023.3
qtpy                : 2.2.0
pyqt5               : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report! When making an issue title, please try to describe the issue; just including the error message is not helpful to get an idea what the issue is about.

In your example, `df.columns` is 

    Index(['email', 'full name', ('first', 'last')], dtype='object')

This is what you want to specify to drop, namely `df.drop(columns=[('first','last')])`.

If this doesn't resolve your issue, leave a comment as to why and we can reopen.
