### ISSUE TITLE
MAINT: Drop Python 3.9 support, require Python 3.10 (following SPEC 0)

### ISSUE THREAD

**Issue by EwoutH** [pandas-dev/pandas#55528]
[NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) was superseded by the scientific python ecosystem coordination guideline [SPEC 0 — Minimum Supported Versions](https://scientific-python.org/specs/spec-0000/). Where NEP had a 42 month support windows (3.5 years) for each Python version, SPEC 0 recommends a 3 year support window.

If we were to follow SPEC 0, than Python 3.9 support can already be dropped, since it was released October 5th, 2020.

Requiring Python 3.10+ for future NumPy releases would allow to start use Structural Pattern Matching and new typing features. See [What’s New In Python 3.10](https://docs.python.org/3/whatsnew/3.10.html).

**Comment by jakirkham** [comment]
This appears to have happened in PR: https://github.com/pandas-dev/pandas/pull/58238

Should this be closed?

**Comment by mroeschke** [comment]
Yup. Closing
