### ISSUE TITLE
DEPR: read_gbq, DataFrame.to_gbq

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#55525]
1. These functions are a 1 line call to https://googleapis.dev/python/pandas-gbq/latest/api.html#pandas_gbq.read_gbq and https://googleapis.dev/python/pandas-gbq/latest/api.html#pandas_gbq.to_gbq, so pandas' signatures will always lag behind the full functionality of the underlying library call.
2. We don't have any tests for this functionality nor have the capability to test this
3. It's caused some testing headaches in the past https://github.com/pandas-dev/pandas/pull/53693 https://github.com/pandas-dev/pandas/pull/54200

I think it would be best if we direct user to just use the underlying library in our ecosystem/IO docs

**Comment by jbrockmendel** [comment]
> We don't have any tests for this functionality nor have the capability to test this

i find this reason compelling
