### ISSUE TITLE
BUG: Inconsistent behaviour of the `index` between `to_series` and `to_frame`

### ISSUE THREAD

**Issue by abokey1** [pandas-dev/pandas#55610]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Issue Description

Currently, when converting an `Index` object to a `Series` using [`to_series`](https://github.com/pandas-dev/pandas/blob/v2.1.1/pandas/core/indexes/base.py#L1529), we can't ask for a default index `(0, 1, ...)` unless we explicitly pass a range :

```
import pandas as pd

idx = pd.Index(["Ant", "Bear", "Cow"], name="animal")

print(idx.to_series(index=range(len(idx))))

0     Ant
1    Bear
2     Cow
Name: animal, dtype: object
```
Setting `index=False` triggers a `TypeError: Index(...) must be called with a collection of some kind, False was passed`. And on the other hand, while [`to_frame`](https://github.com/pandas-dev/pandas/blob/v2.1.1/pandas/core/indexes/base.py#L1592) allows to set `index=False` to get a default index `(0, 1, ...)`, it completely ignores any custom index :
```
import pandas as pd

idx = pd.Index(["Ant", "Bear", "Cow"], name="animal")

print(idx.to_frame(index=list("abc")))

       animal
animal       
Ant       Ant
Bear     Bear
Cow       Cow

print(idx.to_frame(index=["a"]))

       animal
animal       
Ant       Ant
Bear     Bear
Cow       Cow
```

To fix the former (*i.e* [`to_series`](https://github.com/pandas-dev/pandas/blob/v2.1.1/pandas/core/indexes/base.py#L1529)), I think the two lines below :

https://github.com/pandas-dev/pandas/blob/e86ed377639948c64c429059127bcf5b359ab6be/pandas/core/indexes/base.py#L1585-L1586

.. should be updated to :

```
        if index is False:
            index = None
        elif index is True or index is None:
            index = self._view()
        else:
            index = index
```

**Comment by ziadk** [comment]
`to_frame` as an Index object method has `index` typed to `bool`. So passing a `list` to it in the first place seems like a mistake to me. Don't you agree ?

**Comment by paulreece** [comment]
As was stated above see here:

https://github.com/pandas-dev/pandas/blob/e86ed377639948c64c429059127bcf5b359ab6be/pandas/core/indexes/base.py#L1592-L1633

And see here for Series:

https://github.com/pandas-dev/pandas/blob/e86ed377639948c64c429059127bcf5b359ab6be/pandas/core/indexes/base.py#L1529-L1559

**Comment by paulreece** [comment]
Series can take lists as its `index` argument but `to_frame` only takes booleans.  I don't think this is a bug.
