### ISSUE TITLE
HTML repr for empty dataframes is ugly

### ISSUE THREAD

**Issue by y-p** [pandas-dev/pandas#5562]
see https://github.com/pydata/pandas/pull/5550#issuecomment-28931094

related #6062

**Comment by TomAugspurger** [comment]
Let's keep an eye on https://github.com/jupyter/notebook/issues/1182 and maybe close in favor of that?

**Comment by TomAugspurger** [comment]
xref: https://github.com/jupyter/jupyterlab/pull/910 and specifically https://github.com/jupyter/jupyterlab/pull/910#issuecomment-248297851

Some items we can fix

> Ideally NaN would get styled slightly differently. That's particularly important for string column so you can distinguish missing values from the equivalent text.

Can add an extra class to `NaN` (maybe color, bold, or italicize?). Right now the HTML repr of `'NaN'` the string literal and `np.nan` are identical

> The fertility column has varying decimal places

This is python's string repr truncating `7.00` to just `7`. I think we have another issue about that, will dig it up.

> For columns like pop [large integer] you might want to consider adding commas every 3 digits.

This breaks copy-pastability, but thats pretty fragile, and we have `df.to_clipboard()` anyway.

**Comment by datapythonista** [comment]
Not sure in which exact Jupyter version the `DataFrame` is not "ugly" anymore, but now it's rendered as a table. Closing.
