### ISSUE TITLE
ENH: Provide musllinux build for aarch64 as well

### ISSUE THREAD

**Issue by der-eismann** [pandas-dev/pandas#55645]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

We usually build our container images based on `python-alpine` to reduce their size, however colleagues with Apple Silicon-based devices are unable to build these images, since there are no `musllinux` builds for aarch64, only x64. So analogue to https://github.com/numpy/numpy/issues/24934 I would kindly ask you to add these wheels as well.

### Feature Description

Just add a musllinux aarch64 target to your build pipelines.

### Alternative Solutions

None.

**Comment by lithomas1** [comment]
Sure, I'll mark this for 2.2, then.

**Comment by der-eismann** [comment]
Awesome, thank you very much to everyone involved!

**Comment by cdce8p** [comment]
It seems `musllinux_aarch64` were not uploaded with `2.3`.
https://pypi.org/project/pandas/2.3.0/#files

Might be related to the move from circleci to GHA. The build matrix only lists `manylinux_aarch64` now.
https://github.com/pandas-dev/pandas/blob/2cc37625532045f4ac55b27176454bbbc9baf213/.github/workflows/wheels.yml#L95-L98
