### ISSUE TITLE
ENH: How about adding a formatting parameter to the crosstab function?(like a heatmap function in seaborn)

### ISSUE THREAD

**Issue by SukJinKim** [pandas-dev/pandas#55646]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I think the result of normalizing crosstab has a problem that is **difficult to grasp** because the number of decimal places is too long. 
I made a simple example to help you understand.
```python
import pandas as pd

df = pd.DataFrame({
    'gender': ['male', 'male', 'female', 'female', 'male', 'female', 'male'],
    'education_level': ['high school', 'college', 'college', 'graduate', 'high school', 'graduate', 'college'],
    'score': [75, 82, 88, 95, 69, 92, 78]
})

ct_norm = pd.crosstab(df['gender'], df['education_level'], normalize=True, margins=True)
ct_norm
``` 
Output:
```python
education_level	college	graduate	high school	All
gender				
female	0.142857	0.285714	0.000000	0.428571
male	0.285714	0.000000	0.285714	0.571429
All	0.428571	0.285714	0.285714	1.000000
``` 

### Feature Description

How about making the results of normalizing crosstab visible at a glance with [Python's official formatting specification](https://docs.python.org/3/library/string.html#format-specification-mini-language) (e.g. .2f)?

In fact, this idea came up with reference to the [heatmap function of seaborn](https://seaborn.pydata.org/generated/seaborn.heatmap.html).

Like the above, I made an example to help you understand.
```python
import pandas as pd

df = pd.DataFrame({
    'gender': ['male', 'male', 'female', 'female', 'male', 'female', 'male'],
    'education_level': ['high school', 'college', 'college', 'graduate', 'high school', 'graduate', 'college'],
    'score': [75, 82, 88, 95, 69, 92, 78]
})

ct_norm = pd.crosstab(df['gender'], df['education_level'], normalize=True, margins=True, fmt='.2f')
ct_norm
``` 
Output:
```python
education_level	college	graduate	high school	All
gender				
female	0.14	0.29	0.00	0.42
male	0.29	0.00	0.29	0.57
All	0.43	0.29	0.29	1.00
``` 

Of course, as you can see in the example, some columns or row sums may not match perfectly (see that the sum of 'male' row is 0.58, not 0.57)

However, this problem is the same in previous examples (see that the sum of 'male' row is 0.571428, not 0.571429)

So I think this little problem is fine.

### Alternative Solutions

I can't think of it right now, but I'll mention it whenever I do

### Output of pd.show_versions()
<details><summary>Details</summary>
<p>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.10.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.120+
Version          : #1 SMP Wed Aug 30 11:19:59 UTC 2023
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.23.5
pytz             : 2023.3.post1
dateutil         : 2.8.2
setuptools       : 67.7.2
pip              : 23.1.2
Cython           : 3.0.4
pytest           : 7.4.2
hypothesis       : None
sphinx           : 5.0.2
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.3
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.9.9
jinja2           : 3.1.2
IPython          : 7.34.0
pandas_datareader: 0.10.0
bs4              : 4.11.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2023.6.0
gcsfs            : 2023.6.0
matplotlib       : 3.7.1
numba            : 0.56.4
numexpr          : 2.8.7
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : 0.17.9
pyarrow          : 9.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.11.3
snappy           : None
sqlalchemy       : 2.0.22
tables           : 3.8.0
tabulate         : 0.9.0
xarray           : 2023.7.0
xlrd             : 2.0.1
xlwt             : None
zstandard        : None
tzdata           : None

</p>
</details>

**Comment by mroeschke** [comment]
Thanks for the report, but one can simply call `round` after the crosstab operation so I don't think an API change is needed here so closing
