### ISSUE TITLE
ENH: Adding the append back

### ISSUE THREAD

**Issue by VictorGambarini** [pandas-dev/pandas#55659]
### Feature Type

- [ ] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I just want to append a row to a dataframe, it is making my life miserable when using pandas. 

### Feature Description

pd.append(row)

### Alternative Solutions

pd.concat, maybe? looks very hacky and always throws an error back.

### Additional Context

Please!

**Comment by mroeschke** [comment]
Thanks for the report but as stated in https://github.com/pandas-dev/pandas/issues/35407#issuecomment-1457939313 this is more-or-less a final decision. If you are experiencing a bug please use the bug report template.
