### ISSUE TITLE
DOC: pandas.DataFrame.resample

### ISSUE THREAD

**Issue by AnkitSingh-In** [pandas-dev/pandas#55664]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.resample.html

### Documentation problem

In explainer section of First example
![Screenshot 2023-10-24 195243](https://github.com/pandas-dev/pandas/assets/22295064/9ee9e1d9-39a6-449d-b288-68e41ae3a1d1)
timestamp _2000-01-01 00:03:00_ is incorrect.

### Suggested fix for documentation

The correct timestamp would be _2000-01-01 00:00:00_ .

**Comment by marcosquadross** [comment]
take

**Comment by MarcoGorelli** [comment]
thanks for the report - I think it's technically correct but worded very confusingly, have opened https://github.com/pandas-dev/pandas/pull/55708
