### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by Yin-1** [pandas-dev/pandas#55775]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
data = {'A': ['foo', 'bar', 'baz', 'foo', 'bar', 'baz'],
        'B': [1, 2, 3, 4, 5, 6],
        'C': [2.0, 3.0, 4.0, 5.0, 6.0, 7.0]}

df = pd.DataFrame(data)
df['grouped_list'] = df.groupby('A')['B'].transform(list)

I expect the result:
     A  B    C grouped_list
0  foo  1  2.0       [1, 4]
1  bar  2  3.0       [2, 5]
2  baz  3  4.0       [3, 6]
3  foo  4  5.0       [1, 4]
4  bar  5  6.0       [2, 5]
5  baz  6  7.0       [3, 6]
But actual result:
     A  B    C  grouped_list
0  foo  1  2.0             1
1  bar  2  3.0             2
2  baz  3  4.0             3
3  foo  4  5.0             4
4  bar  5  6.0             5
5  baz  6  7.0             6
```

### Issue Description

Using transform to summarize the results of each group, an unexpected result occurred when I tried to summarize the results of each group into a list. Why??

### Expected Behavior

     A  B    C grouped_list
0  foo  1  2.0       [1, 4]
1  bar  2  3.0       [2, 5]
2  baz  3  4.0       [3, 6]
3  foo  4  5.0       [1, 4]
4  bar  5  6.0       [2, 5]
5  baz  6  7.0       [3, 6]

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by Yin-1** [comment]
help!!!

**Comment by paulreece** [comment]
Please raise questions like this on our Slack in the future.

The reason this isn't working is because `transform` preserves the shape of the original DataFrame and returns a `Series` back to you.  

You can do this with a lambda using transform:
```Python
df['grouped_list'] = df.groupby('A')['B'].transform(lambda x: [x.tolist()]*len(x))
```

**Comment by Yin-1** [comment]
It feels like a design flaw, but I don't want to dwell on it, thank you
