### ISSUE TITLE
BUG: QuarterBegin Does not work with Period

### ISSUE THREAD

**Issue by cancan101** [pandas-dev/pandas#55785]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
pd.Period(year=2014, quarter=3, freq=pd.offsets.QuarterBegin(startingMonth=12))
```

### Issue Description

Unable to to create a Quarterly period as defined by the start of the quarter vs the end.

Might be related to this very old issue: https://github.com/pandas-dev/pandas/issues/5091

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File period.pyx:2839, in pandas._libs.tslibs.period.freq_to_dtype_code()

AttributeError: 'pandas._libs.tslibs.offsets.QuarterBegin' object has no attribute '_period_dtype_code'

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
File period.pyx:2841, in pandas._libs.tslibs.period.freq_to_dtype_code()

ValueError: Invalid frequency: <QuarterBegin: startingMonth=12>
Exception ignored in: 'pandas._libs.tslibs.period._ordinal_from_fields'
Traceback (most recent call last):
  File "period.pyx", line 2841, in pandas._libs.tslibs.period.freq_to_dtype_code
ValueError: Invalid frequency: <QuarterBegin: startingMonth=12>
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[14], line 1
----> 1 pd.Period(year=2014, quarter=3, freq=pd.offsets.QuarterBegin(startingMonth=12))

File period.pyx:2830, in pandas._libs.tslibs.period.Period.__new__()

File period.pyx:1779, in pandas._libs.tslibs.period._Period._from_ordinal()

File period.pyx:1742, in pandas._libs.tslibs.period._Period.__cinit__()

AttributeError: 'pandas._libs.tslibs.offsets.QuarterBegin' object has no attribute '_period_dtype_code'
```

### Expected Behavior

```
Period('2014Q3', 'QS-DEC')
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a60ad39b4a9febdea9a59d602dad44b1538b0ea5
python              : 3.12.0.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 22.1.0
Version             : Darwin Kernel Version 22.1.0: Sun Oct  9 20:19:12 PDT 2022; root:xnu-8792.41.9~3/RELEASE_ARM64_T6020
machine             : arm64
processor           : arm
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.2
numpy               : 1.26.1
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.2.2
pip                 : 23.3.1
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.17.2
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.8.0
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.3
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None
</details>

**Comment by hvsesha** [comment]
@cancan101 
Try this for quarter This is working

import pandas as pd
period=pd.Period(year=2014, month=3, freq="Q")

print (period)

**Comment by cancan101** [comment]
That is the same as using `QuarterEnd`. These are the same:
```
pd.Period(year=2014, month=3, freq="Q")
```
and
```
pd.Period(year=2014, quarter=3, freq=pd.offsets.QuarterEnd(startingMonth=12))
```
However, I want to use `QuarterBegin`.

**Comment by Dhayanidhi-M** [comment]
Hi ,

the above error says , "_period_dtype_code" attribute not found . Which means the class "QuarterBegin" does not have the attribute "_period_dtype_code" . 

I checked the code , in file "offset.pyx" , we have the class "QuarterBegin" and it does not have the attribute "_period_dtype_code" . Hence we are seeing the above error.

I think , this needs to be fixed in code . Is someone working on this ?.

**Comment by cancan101** [comment]
Yea it seems like that code should be fixed with either support or a better error message. and / or the [docs](https://pandas.pydata.org/docs/user_guide/timeseries.html#anchored-offsets) might need to be made more clear as the way I read them, QuarterBegin should work:
![image](https://github.com/pandas-dev/pandas/assets/51059/5589d8a9-28be-475c-8ce0-b27a4c6cee5b)
where the `S` is an optional modification to the alias string.

**Comment by jbrockmendel** [comment]
cc @natmokval maybe we should avoid having _period_dtype_code bubble up in the exception message?  we need to be more clear that some offsets are not supported as period `freq`s and that this is intentional

**Comment by natmokval** [comment]
Thank you @cancan101 for the report. 

We are working on renaming some offset aliases, e.g. 'M' to 'ME' (#52064), 'Q' to 'QE' ( #55553), 'Y' to 'YE' (#55792). The goal is to separate them from Period aliases: 'M', 'Q', 'Y'. These changes are on main so far and they will be in the next release. 

Expected Behavior is `Period('2014Q3', 'Q-DEC')` and it doesn't suppose to be `Period('2014Q3', 'QS-DEC') `or `Period('2014Q3', 'QE-DEC'`).

a valid frequency for Period can be either string `'Q'` or offsets class `pd.offsets.QuarterEnd`

**Comment by natmokval** [comment]
> That is the same as using `QuarterEnd`. These are the same:
> 
> ```
> pd.Period(year=2014, month=3, freq="Q")
> ```
> 
> and
> 
> ```
> pd.Period(year=2014, quarter=3, freq=pd.offsets.QuarterEnd(startingMonth=12))
> ```
> 
> However, I want to use `QuarterBegin`.

some offsets are not supported as period frequencies, e.g. offset class `QuarterBegin` and corresponding string `'QS'` are not valid for `Period`.

**Comment by natmokval** [comment]
> Yea it seems like that code should be fixed with either support or a better error message. and / or the [docs](https://pandas.pydata.org/docs/user_guide/timeseries.html#anchored-offsets) might need to be made more clear as the way I read them, QuarterBegin should work: ![image](https://user-images.githubusercontent.com/51059/279994346-5589d8a9-28be-475c-8ce0-b27a4c6cee5b.png) where the `S` is an optional modification to the alias string.


Thank you, @cancan101. I agree, we need a better error message and documentation might be more clear in this part. I think we should show an error message that some offsets are not supported as period frequencies and I will make PR for this.

Documentation for Time series is updated ([link](https://pandas.pydata.org/docs/dev/user_guide/timeseries.html#anchored-offsets)) . In the new version we point out that for Anchored offsets only frequencies like `"(B)Q(E)(S)\-DEC"` can be used:

```
"(B)Q(E)(S)\-DEC", "quarterly frequency, year ends in December. Same as 'QE'" 
```

**Comment by natmokval** [comment]
> cc @natmokval maybe we should avoid having _period_dtype_code bubble up in the exception message? we need to be more clear that some offsets are not supported as period `freq`s and that this is intentional

thank you, I agree, it would be better to raise a ValueError, with a message that some offsets are not supported as period frequencies. I will make PR.
cc @MarcoGorelli
