### ISSUE TITLE
ENH: iterdict -- like itertuples without implicitly casting dtypes

### ISSUE THREAD

**Issue by bretttully** [pandas-dev/pandas#55783]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

We need to iterate a dataframe without implicitly changing the data type

### Feature Description

Add new method to the dataframe. 

```python
def iterdict(self) -> Generator[tuple[int, dict], None, None]:
    """Iterate over rows of a dataframe in a manner that preserves data types"""
    columns = df.columns.tolist()
    for i, elements in enumerate(zip(*(df[c].to_numpy() for c in columns))):
        yield i, dict(zip(columns, elements))
```

Test
```python
import numpy as np
import pandas as pd


def test_type_preservation():
    n = 100
    rng = np.random.default_rng(0)
    df = pd.DataFrame(
        {
            **{
                str(d).split("'")[1].split(".")[-1]: rng.integers(np.iinfo(d).min, np.iinfo(d).max, n, dtype=d)
                for d in (np.uint8, np.uint64, np.int32, np.int64)
            },
            **{
                str(d).split("'")[1].split(".")[-1]: rng.uniform(np.finfo(d).min, np.finfo(d).max, n).astype(d)
                for d in (np.float16, np.float32)
            },
        },
    )
    types = {c: df[c].dtype for c in df.columns}
    for _, row in df.iterdict():
        for c in df.columns:
            assert type(row[c]) == types[c], f"{c}: {type(row[c])=} != {types[c]=}"
```

### Alternative Solutions

The suggestion above doesn't handle the index, but that could be done instead of returning `i`

**Comment by mroeschke** [comment]
Thanks for the report, but given the small amount of code needed i don't think this needs to be included and maintained within pandas and can be used in an ad-hoc fashion.

**Comment by phofl** [comment]
agree with @mroeschke 

we shouldn't provide more methods to iterate over data frames either
