### ISSUE TITLE
BUG: unexpected behaviour of `pandas.Series.isna`  on `Float64`

### ISSUE THREAD

**Issue by Fresh-Mint** [pandas-dev/pandas#55787]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

s0 = pd.Series([0.0 for _ in range(10)], dtype="Float64") / 0.0


# Unexpected behaviour
print(s0.isna())
# output
# 0    False
# 1    False
# 2    False
# 3    False
# 4    False
# 5    False
# 6    False
# 7    False
# 8    False
# 9    False
# dtype: bool

# Expected behaviour of Series.isna
print(s0.apply(pd.isna))
# output
# 0    True
# 1    True
# 2    True
# 3    True
# 4    True
# 5    True
# 6    True
# 7    True
# 8    True
# 9    True
# dtype: bool
```

### Issue Description

`pandas.Series.isna`  returns False on NaN resulted from `Float64`

### Expected Behavior

Expect True to be returned on NaN resulted from `Float64`

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a60ad39b4a9febdea9a59d602dad44b1538b0ea5
python              : 3.11.6.final.0
python-bits         : 64
OS                  : Linux
machine             : x86_64
processor           : x86_64
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.2
numpy               : 1.26.1
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.2.2
pip                 : 23.3.1
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : 8.17.2
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by paulreece** [comment]
Occurs on `main` and `2.1.x`.

It's because this function is expecting `np.ndarray` but instead receives `pandas.core.arrays.floating.FloatingArray`:
https://github.com/pandas-dev/pandas/blob/eedf0d5cc2801cc3849ec9abb4e8b3f509d91ee9/pandas/core/dtypes/missing.py#L261-L279

**Comment by mroeschke** [comment]
Thanks for the report. The core issue is being discussed in https://github.com/pandas-dev/pandas/issues/32265 so closing in favor of that issue
