### ISSUE TITLE
BUG: Not support pyarrow 14.0

### ISSUE THREAD

**Issue by doublessay** [pandas-dev/pandas#55799]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({"TI":[1,2,3]})
df.to_csv("test.csv")

df1 = pd.read_csv("test.csv") # It's ok
df2 = pd.read_csv("test.csv", dtype_backend="pyarrow") # Error occurred

ImportError: pyarrow>=7.0.0 is required for PyArrow backed ArrowExtensionArray.
```

### Issue Description

[Pyarrow](https://pypi.org/project/pyarrow/#history) released v14.0 on Nov 1, which is the start version to support Python 3.12.

It's not compatible with current pandas 2.1.2. Need to update the support range of pyarrow.

### Expected Behavior

Could support pyarrow 14.0

### Installed Versions

INSTALLED VERSIONS
------------------
commit              : a60ad39b4a9febdea9a59d602dad44b1538b0ea5
python              : 3.11.6.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 23.1.0
Version             : Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103
machine             : arm64
processor           : arm
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : None.UTF-8

pandas              : 2.1.2
numpy               : 1.26.1
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.2.2
pip                 : 23.3.1
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : 8.17.2
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : 14.0.0
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

**Comment by rhshadrach** [comment]
Thanks for the report - I can't reproduce on main nor 2.1.x. Can you try recreating your environment?

**Comment by doublessay** [comment]
Thank you for your timely reply.
Do you reproduce the example with pyarrow 14.0? 
But I quite encounter the bug on Mac, Python 3.11.6, pyarrow 14.0 and pandas 2.1.2

Maybe i can continue to use pyarrow 13.0, which works well with Python 3.11 and pandas 2.x, but this may hinder the progress for those projects requiring pyarrow to support Python 3.12

**Comment by rhshadrach** [comment]
> Do you reproduce the example with pyarrow 14.0?

Yes - but with Python 3.10 on Linux.

**Comment by doublessay** [comment]
I don't know what happened, but it works well now. And pass the tests with Python 3.12
