### ISSUE TITLE
BUG: inconsistency in Index.__getitem__ for Numpy and non-numpy dtypes

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#55820]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
ser = pd.Index([1, 2], dtype="Int64")
ser[np.array([], dtype=np.bool_)]

This raises while NumPy dtypes, e.g. "int64" works.

Traceback (most recent call last):
  File "/Users/patrick/Library/Application Support/JetBrains/PyCharm2023.2/scratches/scratch.py", line 477, in <module>
    ser[np.array([], dtype=np.bool_)]
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/indexes/base.py", line 5360, in __getitem__
    result = getitem(key)
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/arrays/masked.py", line 182, in __getitem__
    item = check_array_indexer(self, item)
  File "/Users/patrick/PycharmProjects/pandas/pandas/core/indexers/utils.py", line 539, in check_array_indexer
    raise IndexError(
IndexError: Boolean index has wrong length: 0 instead of 2
```

### Issue Description

Not sure what we want to expect here, the Series case raises for all dtypes

cc @jbrockmendel

### Expected Behavior

See above

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by jbrockmendel** [comment]
requiring matching length for a mask seems right to me, so the numpy version looks wrong

**Comment by jorisvandenbossche** [comment]
I suppose the underlying reason that this works for the numpy version, is because numpy arrays seem to allow this:

```
>>> arr = np.array([1, 2], dtype="int64")
>>> arr[np.array([], dtype=np.bool_)]
array([], dtype=int64)
```

I would have expected numpy to raise here, though. And I agree we can be more consistent here. 

If this is longstanding behaviour (and matching numpy), we might want to deprecate it first.
