### ISSUE TITLE
BUG: infinite recursion on inheritance and overloading __truediv__ in v2.1.2

### ISSUE THREAD

**Issue by AllenDowney** [pandas-dev/pandas#55826]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

class Pmf(pd.Series):

    def filldiv(self, x, **kwargs):
        """Override the / operator to set fill_value to 0.

        x: Distribution or sequence

        returns: Pmf
        """
        kwargs['fill_value'] = 0
        s = pd.Series.divide(self, x, **kwargs)
        return Pmf(s)

    __truediv__ = filldiv
    __rtruediv__ = filldiv

pmf = Pmf(1, [1,2,3])
pmf /= pmf.sum()
```

### Issue Description

The result is infinite recursion (see this Colab notebook https://colab.research.google.com/drive/1RaVKji95T7l3PcKXxFctyC5DOLvfuNCX?usp=sharing)

```
---------------------------------------------------------------------------

RecursionError                            Traceback (most recent call last)

[<ipython-input-6-7f4c4c39b2b9>](https://localhost:8080/#) in <cell line: 20>()
     18 
     19 pmf = Pmf(1, [1,2,3])
---> 20 pmf /= pmf.sum()

5 frames

... last 3 frames repeated, from the frame below ...

[<ipython-input-6-7f4c4c39b2b9>](https://localhost:8080/#) in filldiv(self, x, **kwargs)
     11         """
     12         kwargs['fill_value'] = 0
---> 13         s = pd.Series.divide(self, x, **kwargs)
     14         return Pmf(s)
     15 

RecursionError: maximum recursion depth exceeded in __instancecheck__
```

### Expected Behavior

Expected behavior (which was working in 2.1.1) is that the `/` operator runs `__truediv__`, which is an alias for `filldiv`, which calls `pd.Series.divide`, which should NOT call `__truediv__`. 

### Installed Versions

<details>

pandas                           2.1.2

</details>

**Comment by rhshadrach** [comment]
Thanks for the report. I can see this change being an annoyance in subclassing pandas, but I'm not sure I follow why `divide` (which is an alias for `truediv`) should not call `__truediv__`.

To ensure you're calling the pandas implementation, I recommend doing:

    s = pd.Series(self, copy=False).divide(x, **kwargs)

While there is some overhead in Series creation (6.5us on my machine), it is pretty cheap. This way you're ensuring you're not relying on how pandas implements its internals.

**Comment by AllenDowney** [comment]
That worked -- and I think I can spare 6.5 us.

Thank you for the quick reply!
