### ISSUE TITLE
BUG: rolling does not work with timestamp[ns][pyarrow] index type

### ISSUE THREAD

**Issue by mhabets** [pandas-dev/pandas#55849]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
ts = ['2019-01-03 05:11', '2019-01-03 05:23',
      '2019-01-03 05:28', '2019-01-03 05:32',
      '2019-01-03 05:36']
arr = [True, False, False, True, True]
df = pd.DataFrame({'arr': arr, 'ts': ts})
df["ts"] = pd.to_datetime(df["ts"])
df = df.convert_dtypes(dtype_backend="pyarrow").set_index("ts")
print(df.rolling('5min').sum())
```

### Issue Description

Error message: `ValueError: window must be an integer 0 or greater`

### Expected Behavior

No error message

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a60ad39b4a9febdea9a59d602dad44b1538b0ea5
python              : 3.11.6.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.22621
machine             : AMD64
processor           : Intel64 Family 6 Model 186 Stepping 2, GenuineIntel
byteorder           : little
LC_ALL              : None
LANG                : en
LOCALE              : English_United Kingdom.1252

pandas              : 2.1.2
numpy               : 1.26.0
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.2.2
pip                 : 23.3.1
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : 7.2.6
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : 2.9.7
jinja2              : 3.1.2
IPython             : 8.17.2
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.8.1
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : 13.0.0
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.3
sqlalchemy          : 2.0.23
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : 2.4.1
pyqt5               : None

</details>

**Comment by hvsesha** [comment]
@mhabets Rolling function is having window of datatype integer 
If you give string it will throw error as it is expected 

So Kindly give window =5 and it will work

**Comment by hvsesha** [comment]
@mhabets 
in rolling.py kindly find the validation 

  if not is_integer(self.window) or self.window < 0:
            raise ValueError("window must be an integer 0 or greater")

**Comment by mhabets** [comment]
@hvsesha - please note that the following code (with str) works like a charm as describe in the documentation:
``` python
ts = ['2019-01-03 05:11', '2019-01-03 05:23',
      '2019-01-03 05:28', '2019-01-03 05:32',
      '2019-01-03 05:36']
arr = [True, False, False, True, True]
df = pd.DataFrame({'arr': arr, 'ts': ts})
df["ts"] = pd.to_datetime(df["ts"])
df = df.set_index("ts")
print(df.rolling('5min').sum())
```
The issue is related to the type of the index (Arrow timestamp type not being covered as yet)

**Comment by hvsesha** [comment]
@mhabets Able to change in cast.py by adding arrow in convert_dtypes 

def convert_dtypes(
    input_array: ArrayLike,
    convert_string: bool = True,
    convert_integer: bool = True,
    convert_boolean: bool = True,
    convert_floating: bool = True,
    convert_pyarrow:bool= True,
    infer_objects: bool = False,
    dtype_backend: Literal["numpy_nullable"] = "numpy_nullable",
) -> DtypeObj:

Tested

**Comment by hvsesha** [comment]
@mroeschke Kindly review this fix .I am 20 years experienced in c++.Kindly let me know if this fix looks good
