### ISSUE TITLE
BUG: Dataframe doesn't maintain datetime format on midnight

### ISSUE THREAD

**Issue by JustinRush80** [pandas-dev/pandas#55867]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd 

df = pd.DataFrame({
        "col1": [pd.Timestamp(day=16, month=10, year=2023, hour=0, minute=0, second=0)],
    })
df2 = pd.DataFrame({
        "col1": [pd.Timestamp(day=16, month=10, year=2023, hour=0, minute=0, second=0), 0],
    })

print(df)
print(df2)
```

### Issue Description

The datatime format is not maintain if it is a single row of datatimes that occur on midnight 

```python
#df
         col1
 0  2023-10-16
``` 

```python
#df2
          col1
0  2023-10-16 00:00:00
1                    0

``` 

### Expected Behavior

The datatime format is maintain in any environment

```python
#df
         col1
0  2023-10-16 00:00:00
``` 

```python
#df2
          col1
0  2023-10-16 00:00:00
1                    0
``` 

 

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a60ad39b4a9febdea9a59d602dad44b1538b0ea5
python              : 3.9.6.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 22.6.0
Version             : Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
machine             : arm64
processor           : arm
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.2
numpy               : 1.26.1
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 56.0.0
pip                 : 21.1.3
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : None
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by JustinRush80** [comment]
take

**Comment by JustinRush80** [comment]
@Flytre 
Would it be okay if I could work on this if it's not a intended behavior?  I am very new to contributing to a open source project so this would be a huge learning opportunity for me!

**Comment by Flytre** [comment]
After investigating this is not actually a bug @JustinRush80 and should not be altered.

Pandas stores columns that represent dates as DatetimeArrays. When printing the dataframe, Panda recognizes all the values in this column correspond to dates and not times and omits the time info to print the data more concisely and prettily.

In the second dataframe, you provide a column that stores mixed types. So Pandas just knows this column stores objects of some type. The object column type doesn't understand date time specific formatting rules. Even if we attempted to applying this formatting, for consistency purposes we would want our output to accurately model the input (a timestamp) and wouldn't want to exclude the hour/min/sec. It would also reduce the time or memory efficiency of Pandas to do so as we'd have to search for date time values or cache which indices correspond to them. Ideally we'd want to avoid having mixed type columns in the first place when we design our data frames.

**Comment by JustinRush80** [comment]
@Flytre I definitely see what you mean in the **is_normalized()** function in the DatetimeArray class. Thanks
