### ISSUE TITLE
Nlargest %

### ISSUE THREAD

**Issue by tocr83** [pandas-dev/pandas#55869]
Hi pandas have a method largest. It would be useful to have a similar method where one can filter on nlargest/nsmallest in percentage terms, ie the largest 1% or 5% of values in a series

**Comment by michelkluger** [comment]
seems like a nice idea, should be easy to implement.

alternatively one could do:

series = pd.Series(data)
percentage_to_keep = 0.1  # Keep the top 10%
threshold = series.quantile(1 - percentage_to_keep)
top_x_percent = series[series >= threshold]

**Comment by tocr83** [comment]
Indeed I use such a solution today but it's a bit verbose, I would be more handy with built in method

**Comment by michelkluger** [comment]
> Indeed I use such a solution today but it's a bit verbose, I would be more handy with built in method

makes perfect sense to me

**Comment by mroeschke** [comment]
Thanks for the suggestion, but it doesn't seem that this idea hasn't gotten much support for the core team or interest in the community to implement so closing.
