### ISSUE TITLE
ENH: Merge with custom function

### ISSUE THREAD

**Issue by pwrose** [pandas-dev/pandas#55873]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Do a fuzzy merge of two dataframes. A custom function could be used to determine if there is a match.

### Feature Description

Here is an example how this might look like (this is actually a hallucination by ChatGPT!)

import pandas as pd

df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'C': [5, 6], 'D': [7, 8]})

def my_function(x, y):
  return x + y

df = pd.merge(df1, df2, left_on='A', right_on='C', custom_func=my_function)

print(df)

### Alternative Solutions

I'm not aware of a simple alternative.

**Comment by mroeschke** [comment]
Thanks for the request. A similar request has been made in https://github.com/pandas-dev/pandas/issues/8962 so closing in favor of that issue
