### ISSUE TITLE
BUILD: Installing pandas on armv7l python3.9

### ISSUE THREAD

**Issue by hzm74** [pandas-dev/pandas#55875]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Linux-5.15.0-1041-raspi-armv7l-with-glibc2.35

### Installation Method

pip install

### pandas Version

1.5.x

### Python Version

3.9

### Installation Logs

Trying to install pandas with `python3.9 -m pip install pandas`
But it fails on installing Numpy. I have Numpy 1.22.4 installed. That version should be ok for installing pandas. However pandas tries to install cached numpy-1.26.1.tar.gz . I know that version is not possible to run on armv7l. How can i point pandas to numpy 1.22.4 when installing ??

<details>

Collecting numpy>=1.20.3 (from pandas==1.5.2)
  Using cached numpy-1.26.1.tar.gz (15.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      + /home/hvn/intranet/intranetenv3_9/bin/python3.9 /tmp/pip-install-91dgjwm6/numpy_8dcd5f73edec4a728b85a9b3f4a17a27/vendored-meson/meson/meson.py setup /tmp/pip-install-91dgjwm6/numpy_8dcd5f73edec4a728b85a9b3f4a17a27 /tmp/pip-install-91dgjwm6/numpy_8dcd5f73edec4a728b85a9b3f4a17a27/.mesonpy-f_satlk6/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-install-91dgjwm6/numpy_8dcd5f73edec4a728b85a9b3f4a17a27/.mesonpy-f_satlk6/build/meson-python-native-file.ini
      The Meson build system
      Version: 1.2.99
      Source dir: /tmp/pip-install-91dgjwm6/numpy_8dcd5f73edec4a728b85a9b3f4a17a27
      Build dir: /tmp/pip-install-91dgjwm6/numpy_8dcd5f73edec4a728b85a9b3f4a17a27/.mesonpy-f_satlk6/build
      Build type: native build
      Project name: NumPy
      Project version: 1.26.1
      C compiler for the host machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
      C linker for the host machine: cc ld.bfd 2.38
      C++ compiler for the host machine: c++ (gcc 11.4.0 "c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
      C++ linker for the host machine: c++ ld.bfd 2.38
      Cython compiler for the host machine: cython (cython 3.0.5)
      Host machine cpu family: arm
      Host machine cpu: armv7l
      Program python found: YES (/home/hvn/intranet/intranetenv3_9/bin/python3.9)
      Did not find pkg-config by name 'pkg-config'
      Found Pkg-config: NO
      Run-time dependency python found: YES 3.9
      Has header "Python.h" with dependency python: YES
      Compiler for C supports arguments -fno-strict-aliasing: YES
      Message: During parsing cpu-dispatch: The following CPU features were ignored due to platform incompatibility or lack of support:
      "XOP FMA4"
      Test features "NEON" : Supported
      Test features "NEON_FP16" : Supported
      Test features "NEON_VFPV4" : Supported
      Test features "ASIMD" : Unsupported due to Compiler fails against the test code of "ASIMD"
      Test features "ASIMDHP" : Unsupported due to Implied feature "ASIMD" is not supported
      Test features "ASIMDFHM" : Unsupported due to Implied feature "ASIMD" is not supported
      Configuring npy_cpu_dispatch_config.h using configuration
      Message:
      CPU Optimization Options
        baseline:
          Requested : min
          Enabled   :
        dispatch:
          Requested : max -xop -fma4
          Enabled   : NEON NEON_FP16 NEON_VFPV4
      
      Library m found: YES
      Found CMake: /usr/bin/cmake (3.22.1)
      WARNING: CMake Toolchain: Failed to determine CMake compilers state
      Run-time dependency scipy-openblas found: NO (tried pkgconfig and cmake)
      Run-time dependency mkl found: NO (tried pkgconfig and system)
      Run-time dependency mkl found: NO (tried pkgconfig and system)
      Run-time dependency accelerate found: NO (tried system)
      Run-time dependency openblas found: NO (tried pkgconfig, pkgconfig, pkgconfig, system and cmake)
      Run-time dependency flexiblas found: NO (tried pkgconfig and cmake)
      Run-time dependency blis found: NO (tried pkgconfig and cmake)
      WARNING: CMake Toolchain: Failed to determine CMake compilers state
      Run-time dependency blas found: NO (tried pkgconfig and cmake)
      
      ../../numpy/meson.build:169:4: ERROR: Problem encountered: No BLAS library detected! Install one, or use the `allow-noblas` build option (note, this may be up to 100x slower for some linear algebra operations).
      
      A full log can be found at /tmp/pip-install-91dgjwm6/numpy_8dcd5f73edec4a728b85a9b3f4a17a27/.mesonpy-f_satlk6/build/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

</details>

**Comment by lithomas1** [comment]
Try explictly specifing ``numpy==1.22`` in the install command.

**Comment by hzm74** [comment]
Thnx, that did the job! Many thnx..
