### ISSUE TITLE
`merge_ordered()` doesn't validate `fill_method`

### ISSUE THREAD

**Issue by wjandrea** [pandas-dev/pandas#55884]
[The docs](https://pandas.pydata.org/docs/dev/reference/api/pandas.merge_ordered.html) say `fill_method` is the "Interpolation method for data", but I just tried `pd.merge_ordered(..., fill_method='linear')` and it didn't interpolate.

Looking closer at the docs, `fill_method` can only be either `'ffill'` or `None`, but apparently that's not actually checked; for example, `fill_method='carrot'` also works.

> **fill_method** : _{'ffill', None}, default None_
> Interpolation method for data.

Looks like this code is responsible:
https://github.com/pandas-dev/pandas/blob/a167f13876870067ba610b808919f6b85b6b761e/pandas/core/reshape/merge.py#L1859-L1868

It should probably be changed to something like:
```py
if self.fill_method == "ffill": 
    if left_indexer is None:
    ...
elif self.fill_method is None: 
    left_join_indexer = left_indexer
    right_join_indexer = right_indexer
else:
    raise ValueError(f"fill_method must be one of ['ffill']. Got '{self.fill_method}' instead.")
```

(ValueError text based on equivalent `df.interpolate` error)

**Comment by tshehadeh9** [comment]
Hi, new contributor here -- can I work on this task?

**Comment by lithomas1** [comment]
PRs would be welcome for this.
