### ISSUE TITLE
BUG: DataFrame.update not preserving dtype (actual issue is in pandas._lib.lib.infer_dtype?)

### ISSUE THREAD

**Issue by shawnboltz** [pandas-dev/pandas#55883]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df1 = pd.DataFrame([[1, 2, 3]], columns=["A", "B","C"], dtype="Int64")
# df1.dtypes returns:
# A    Int64
# B    Int64
# C    Int64
# dtype: object
df2 = pd.DataFrame([[4, 5, 6]], columns=["A", "B", "C"], dtype="Int64")
# df2.dtypes returns:
# A    Int64
# B    Int64
# C    Int64
# dtype: object
df1.update(df2) # This causes the problem. It *technically* works, but it gives a goofy event-loop traceback and changes the dtype
# df1 returns
#    A  B  C
# 0  4  5  6
# and df1.dtypes returns
# A    object
# B    object
# C    object
# dtype: object
```

### Issue Description

When you update a DataFrame with an `Int64` dtype with another DataFrame with an `Int64` dtype, it performs the update, but erroneously changes the dtype to `object`. Additionally, it puts out a traceback, but doesn't actually raise an exception (sorry, I've not seen this scenario before so I'm not quite sure what the correct terminology is). pytest caught it in one of my test suites as an "Exception caught in a Qt event loop".

```python-traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: len() of unsized object
Exception ignored in: 'pandas._libs.lib.is_integer_array'
Traceback (most recent call last):
  File "{python_environment}\lib\site-packages\pandas\core\arrays\numeric.py", line 162, in _coerce_to_data_and_mask
    inferred_type = lib.infer_dtype(values, skipna=True)
TypeError: len() of unsized object
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: len() of unsized object
Exception ignored in: 'pandas._libs.lib.is_integer_float_array'
Traceback (most recent call last):
  File "{python_environment}\lib\site-packages\pandas\core\arrays\numeric.py", line 162, in _coerce_to_data_and_mask
    inferred_type = lib.infer_dtype(values, skipna=True)
TypeError: len() of unsized object
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: len() of unsized object
Exception ignored in: 'pandas._libs.lib.is_integer_array'
Traceback (most recent call last):
  File "{python_environment}\lib\site-packages\pandas\core\arrays\numeric.py", line 162, in _coerce_to_data_and_mask
    inferred_type = lib.infer_dtype(values, skipna=True)
TypeError: len() of unsized object
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: len() of unsized object
Exception ignored in: 'pandas._libs.lib.is_integer_float_array'
Traceback (most recent call last):
  File "{python_environment}\lib\site-packages\pandas\core\arrays\numeric.py", line 162, in _coerce_to_data_and_mask
    inferred_type = lib.infer_dtype(values, skipna=True)
TypeError: len() of unsized object
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: len() of unsized object
Exception ignored in: 'pandas._libs.lib.is_integer_array'
Traceback (most recent call last):
  File "{python_environment}\lib\site-packages\pandas\core\arrays\numeric.py", line 162, in _coerce_to_data_and_mask
    inferred_type = lib.infer_dtype(values, skipna=True)
TypeError: len() of unsized object
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: len() of unsized object
Exception ignored in: 'pandas._libs.lib.is_integer_float_array'
Traceback (most recent call last):
  File "{python_environment}\lib\site-packages\pandas\core\arrays\numeric.py", line 162, in _coerce_to_data_and_mask
    inferred_type = lib.infer_dtype(values, skipna=True)
TypeError: len() of unsized object
```

### Expected Behavior

The expected behavior would be to preserve the dtype as `Int64`. Furthermore, if the current behavior is intended, the error message should be output in such a way that it does not cause pytest to register a "failure".

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a60ad39b4a9febdea9a59d602dad44b1538b0ea5
python              : 3.9.18.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.19045
machine             : AMD64
processor           : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : English_United States.1252

pandas              : 2.1.2
numpy               : 1.24.3
pytz                : 2022.1
dateutil            : 2.8.2
setuptools          : 63.4.1
pip                 : 22.2.2
Cython              : 0.29.32
pytest              : 7.1.2
hypothesis          : None
sphinx              : 5.0.2
blosc               : None
feather             : None
xlsxwriter          : 3.0.3
lxml.etree          : 4.9.3
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 2.11.3
IPython             : 7.31.1
pandas_datareader   : None
bs4                 : 4.11.1
bottleneck          : 1.3.5
dataframe-api-compat: None
fastparquet         : None
fsspec              : 2022.7.1
gcsfs               : None
matplotlib          : 3.5.2
numba               : 0.58.0
numexpr             : 2.8.3
odfpy               : None
openpyxl            : 3.0.10
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.3
sqlalchemy          : 1.4.39
tables              : 3.7.0
tabulate            : 0.8.10
xarray              : 0.20.1
xlrd                : 2.0.1
zstandard           : None
tzdata              : 2023.3
qtpy                : 2.2.0
pyqt5               : None

</details>

In addition to the provided versioning info, I was able to reproduce on Linux (Ubuntu 22), and the behavior first appears in pandas 2.0.2.

**Comment by tshehadeh9** [comment]
Hi, new contributor here -- could i work on this issue?

**Comment by shawnboltz** [comment]
Just following up: I tested this just now using pandas 2.2.0 and it appears that it has been fixed. Closing this for now.
