### ISSUE TITLE
BUG: Using .dt.isocalendar() on a timestamp[pyarrow] Series makes Python to crash

### ISSUE THREAD

**Issue by mhabets** [pandas-dev/pandas#55893]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
df = pd.DataFrame({'ts': ['2019-01-03 05:11']*4636})
df["ts"] = pd.to_datetime(df["ts"])
df = df.convert_dtypes(dtype_backend="pyarrow")
df["ts"].dt.isocalendar()[["year", "week"]] # last rows wrongly filled by 0
df["ts"].dt.isocalendar()[["year", "week"]] # Python crashes here
```

### Issue Description

Python kernel crashes after running `df["ts"].dt.isocalendar()[["year", "week"]]` **twice**.

Error message:
```
Windows fatal exception: access violation

Main thread:
Current thread 0x000056fc (most recent call first):
  File "...\Lib\site-packages\pyarrow\compute.py", line 245 in wrapper
  File "...\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 2362 in _dt_isocalendar
  File "...\Lib\site-packages\pandas\core\indexes\accessors.py", line 235 in isocalendar
```

### Expected Behavior

Code should return the year and the week without making Python crashing.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a60ad39b4a9febdea9a59d602dad44b1538b0ea5
python              : 3.11.6.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.22621
machine             : AMD64
processor           : Intel64 Family 6 Model 186 Stepping 2, GenuineIntel
byteorder           : little
LC_ALL              : None
LANG                : en
LOCALE              : English_United Kingdom.1252

pandas              : 2.1.2
numpy               : 1.26.0
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.2.2
pip                 : 23.3.1
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : 7.2.6
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : 2.9.7
jinja2              : 3.1.2
IPython             : 8.17.2
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.8.1
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : 13.0.0
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.3
sqlalchemy          : 2.0.23
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : 2.4.1
pyqt5               : None

</details>

**Comment by mroeschke** [comment]
Thanks for the report. Looks like and upstream issue in pyarrow so closing in favor of that issue https://github.com/apache/arrow/issues/38655
