### ISSUE TITLE
BUG: `FutureWarning` on `concat`

### ISSUE THREAD

**Issue by attack68** [pandas-dev/pandas#55928]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd  # version 2.1.3
df1 = pd.DataFrame([[None, 1.0], [None, 2.0]])
df2 = pd.DataFrame([[3.0, None], [4.0, None]])
df3 = pd.concat([df1, df2], keys=["D1", "D2"])
df3.dtypes #  0:f64, 1:f64
df3
#        0    1
# D1 0  NaN  1.0
#    1  NaN  2.0
# D2 0  3.0  NaN
#    1  4.0  NaN
```

### Issue Description

When moving to 2.1.0 a `FutureWarning` is created when concatenating DataFrames where columns in one may be empty.
The warning provided is:

```
FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
```

### Expected Behavior

If you run the above code on 2.0.3 you will obtain exactly the same DataFrame, but without the `Warning`.

If you perform some analysis to exclude empty columns on 2.1.3 you achieve exactly the same DataFrame (columns re-ordered) but without the `FutureWarning`:

```python
df3 = pd.concat([df1[[1]], df2[[0]]], keys=["D1", "D2"])
```

I cannot allow these `FutureWarnings` to propagate through to end users (pandas is internal working for my purposes), therefore I must either filter them out (which I dont want to add unneccessary code for) or perform checks to remove empty columns from DataFrames (which also adds code overhead, and actually can change the represenation of my output which I dont want). 

Is there anything else that can be done - is this really a bug?

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by mroeschke** [comment]
cc @jbrockmendel

**Comment by jbrockmendel** [comment]
i think the 3.0 behavior here will retain the object dtypes from the input dataframes.  The only way I can think to opt-in to the future behavior would be to implement a "future" option.

On your end, you could get the future behavior (and avoid the warning) by checking for object dtype and casting non-object entries to object.

**Comment by lithomas1** [comment]
This is closeable - unless we want to add that option?

**Comment by jbrockmendel** [comment]
@my-tien can you give an example?

**Comment by vladiscripts** [comment]
> Since the results seems to be same in all cases I opted for a simple short term solution
> 
> ```python
>         with warnings.catch_warnings():
>             # TODO: pandas 2.1.0 has a FutureWarning for concatenating DataFrames with Null entries
>             warnings.filterwarnings("ignore", category=FutureWarning)
>             _ = concat(dfs_filtered, keys=["leg1", "leg2"])
> ```

 @attack68, you need to use `.dropna(axis=1, how='all')` to remove all-NA columns.
```python
pd.concat([df.dropna(axis=1, how='all') for df in dfs])
```
It is not obvious from this warning, I spent the whole evening fighting with this warning.

You can also add a check that df is not empty: `[df for df in dfs if not df.empty]`.

**Comment by attack68** [comment]
Thanks @vladiscripts. This was suggested by @dcsaba89 who also noted a serious performance degradation in his use case.

**Comment by vladiscripts** [comment]
I tried to measure the performance. 
I have a list of dictionaries `listdicts`  which have nested lists. So I use the `pd.json_normalize()` method to create single row dfs which I then concatenate into a single df.

```python   
    import timeit

    # no `dropna`
    def measure_time():
        return pd.concat([pd.json_normalize(v).assign(symbol=k) for k, v in listdicts.items()], ignore_index=True)
    execution_time = timeit.timeit(measure_time, number=10)
    print(f"{execution_time / 10} seconds")
    # 20.996232765699823 seconds

    # use `dropna`
    def measure_time():
        return pd.concat([pd.json_normalize(v).dropna(axis=1, how='all').assign(symbol=k) for k, v in listdicts.items()], ignore_index=True)
    execution_time = timeit.timeit(measure_time, number=10)
    print(f"{execution_time / 10} seconds")
    # 22.85368502380006 seconds
```

Serious slowdown by 10%. But not "4x" as written above. For me, 2 seconds of difference is not critical.

**Comment by e-pet** [comment]
It is unclear to me what is the recommended pattern for fixing this warning if I actually do want/need to keep the all-NaN entries? I am concatenating a list of rows where some of them will be all-NA, but I do need to keep them for downstream analyses.

**Comment by ElrondL** [comment]
+1 I agree with @e-pet

**Comment by niltecedu** [comment]
@e-pet  Did you manage to find any solution?

**Comment by e-pet** [comment]
@niltecedu I used the filterwarnings approach described above by @attack68
