### ISSUE TITLE
DOC: Typo in the method "to_timedelta" doc

### ISSUE THREAD

**Issue by Shantanu25** [pandas-dev/pandas#55947]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_timedelta.html

### Documentation problem

The following line contains grammatical mistake:
Must not be specified when arg context strings and errors="raise".

The word "context" is wrong and does not mean anything in the sentence.

### Suggested fix for documentation

Corrected line:
Must not be specified when arg contains strings and errors="raise".

The word "contains" fits better in the sentence.

**Comment by lazarust** [comment]
take
