### ISSUE TITLE
QST: Pandas

### ISSUE THREAD

**Issue by wasimtikki120** [pandas-dev/pandas#55975]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/50459301/how-to-convert-dates-to-quarters-in-python

### Question about pandas

Suppose you have a DataFrame with a column named 'Dates' containing datetime values. How would you create a new column 'Quarter' that indicates the quarter of the year each date falls into? Additionally, how would you efficiently aggregate and display the average value of another column, let's call it 'Sales,' for each quarter?

**Comment by mroeschke** [comment]
Thanks for the issue but for usage questions like this we recommend asking on StackOverflow (the linked issue may help as a starting point)
