### ISSUE TITLE
QST:  Why Nullable integer data columns can not combine in one block?

### ISSUE THREAD

**Issue by Shanxce** [pandas-dev/pandas#55970]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/77486927/why-nullable-integer-data-columns-can-not-combine-in-one-block

### Question about pandas

As shown in [Nullable integer data type](https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html), the construction of it must be pandas.array.

And as shown in [pandas.array](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.array.html#pandas.array), it said 'It’s expected that data represents a 1-dimensional array of data.'. In that case, if i had multi columns of Nullable integer, it will all in different blocks so that they are discontinuity in memory.

Are there any way to construct continuity memory to store multi columns of Nullable integer?

If not, why pandas didn't support it?

**Comment by jbrockmendel** [comment]
> Are there any way to construct continuity memory to store multi columns of Nullable integer?

At the moment, no.

> If not, why pandas didn't support it?

There was a long-running debate about whether ExtensionArrays should support 2D (which would be more performant in cases like yours) or only 1D (which would be simpler for 3rd party authors).  At the sprint this past August we reached a tentative agreement that would involve adding 2D support, but it will be a while before that is implemented.

**Comment by lithomas1** [comment]
Closing since I think the question has been answered.

Feel free to leave a comment if you have more questions.
