### ISSUE TITLE
BUG: df1=df2.iloc[-1:] When a certain value of DF1 changes, the last line of DF2 follows DF1   on Pandas  2.1.3

### ISSUE THREAD

**Issue by zhangyuxiang12** [pandas-dev/pandas#55988]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
print(f'{day}日 初始Total_price2 {Stock_Holding_Total_Price_df}')
#day_Stock_Holding_Total_Price_df.loc[0]=Stock_Holding_Total_Price_df.iloc[-1]
day_Stock_Holding_Total_Price_df=Stock_Holding_Total_Price_df.iloc[-1:]
#day_Stock_Holding_Total_Price_df的date字段等于day
day_Stock_Holding_Total_Price_df.loc[0,'date']=day
print(f'{day}日 初始 day_Total_price{day_Stock_Holding_Total_Price_df}')
print(f'{day}日 赋值后的Total_price {Stock_Holding_Total_Price_df}')
```

### Issue Description

 When a certain value of DF1 changes, the last line of DF2 follows DF1  on Pandas  2.1.3

### Expected Behavior

DF2 will never change

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : 2a953cf80b77e4348bf50ed724f8abc0d814d9dd
python              : 3.10.8.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.22621
machine             : AMD64
processor           : AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : Chinese (Simplified)_China.936

pandas              : 2.1.3
numpy               : 1.26.1
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 63.2.0
pip                 : 23.3.1
Cython              : None
pytest              : None
hypothesis          : None
...
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by lithomas1** [comment]
What is df1 and df2, here?

Can you please craft a [minimal reproducible bug report](https://matthewrocklin.com/minimal-bug-reports)?

**Comment by zhangyuxiang12** [comment]
Sorry , This is my fault，This is because I did not understand Python's memory management mechanism for variable assignment。Close.
