### ISSUE TITLE
BUG: setitem using `loc` not aligning on index?

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#56024]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
In [5]: df = DataFrame({"a": [1, 2], "b": [3, 4]})

In [6]: other = pd.Series([200, 999], index=[1, 0])

In [7]: df
Out[7]:
   a  b
0  1  3
1  2  4

In [8]: other
Out[8]:
1    200
0    999
dtype: int64

In [9]: df.loc[:, 'a'] = other

In [10]: df
Out[10]:
     a  b
0  200  3
1  999  4
```

### Issue Description

When setting a column using `.loc`, and `value` is a `Series`, then the index is ignored

### Expected Behavior

I think operations like this one usually align automatically on the index?

@phofl @jbrockmendel do you know about this one?

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : 2a953cf80b77e4348bf50ed724f8abc0d814d9dd
python              : 3.10.12.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 5.10.102.1-microsoft-standard-WSL2
Version             : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine             : x86_64
processor           : x86_64
byteorder           : little
LC_ALL              : None
LANG                : en_GB.UTF-8
LOCALE              : en_GB.UTF-8

pandas              : 2.1.3
numpy               : 1.25.1
pytz                : 2023.3
dateutil            : 2.8.2
setuptools          : 67.6.1
pip                 : 23.1.2
Cython              : None
pytest              : 7.3.1
hypothesis          : 6.82.4
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.16.1
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : 2023.7.0
fsspec              : 2023.6.0
gcsfs               : None
matplotlib          : 3.7.1
numba               : 0.58.1
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : 12.0.1
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.0
sqlalchemy          : 2.0.20
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by MarcoGorelli** [comment]
It is respected, though, if doing the assignment horizontally:
```python
In [15]: df = pd.DataFrame({'a': [1,1,2], 'b': [4,5,6]})

In [16]: df.loc[0, :] = pd.Series({'b': 999, 'a': 888})

In [17]: df
Out[17]:
     a    b
0  888  999
1    1    5
2    2    6
```

**Comment by MarcoGorelli** [comment]
hey, the non-inplace version does actually respect the index 😄 

```python
In [25]: df = DataFrame({"a": [1, 2], "b": [3, 4]})

In [26]: other = pd.Series([200.5, 999], index=[1, 0])

In [27]: df.loc[:, 'a'] = other

In [28]: df
Out[28]:
       a  b
0  999.0  3
1  200.5  4
```

**Comment by phofl** [comment]
Can you check with df

```
df = DataFrame({"a": [1, 2], "b": [3, 4.5]})
```

we have code paths for single block and multi block.

You are correct, all of those should align

**Comment by MarcoGorelli** [comment]
that one works!

```python
In [38]: df = DataFrame({"a": [1, 2], "b": [3, 4.5]})

In [39]: other = pd.Series([200, 999], index=[1, 0])

In [40]:  df.loc[:, 'a'] = other

In [41]: df
Out[41]:
     a    b
0  999  3.0
1  200  4.5
```

**Comment by phofl** [comment]
Yeah that's what I thought, the single block code path is the culprit (as usual...)

**Comment by jbrockmendel** [comment]
possibly related: #51386, #37516.

my default opinion is "if its ambiguous, let's deprecate allowing it"

**Comment by phofl** [comment]
No it's not ambiguous, it should work in our current setup

**Comment by phofl** [comment]
FWIW my PR that was a precursor for @MarcoGorelli PR about the warning should have fixed this (could you add a test in your other pr @MarcoGorelli ?)

**Comment by MarcoGorelli** [comment]
thanks - looks fixed on `main`, so have added 'needs tests'

**Comment by DipanshiB** [comment]
Hi, is this issue still available to take? Would like to work on this as an open source beginner

**Comment by MarcoGorelli** [comment]
yup, go ahead

**Comment by DipanshiB** [comment]
take
