### ISSUE TITLE
ENH: DataFrame.assign equivalent for rows

### ISSUE THREAD

**Issue by MarkRotchell** [pandas-dev/pandas#56079]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

`DataFrame.assign` is great for adding columns on the fly when chaining, but it presents an asymmetry in functionality for columns compared to rows. It would be useful to have the ability to assign to rows while chaining. The difference is particularly noticeable in how different the API is for adding a total column compared to a total row.

For example, consider:
```python
>>> df = pd.DataFrame(data=
                      {'foo':[10,19,13],
                       'bar':[4,5,6],
                       'baz':[0,1,2]},
                      index=['spam','egg','chips'])
>>> print(df)
       foo  bar  baz
spam    10    4    0
egg     19    5    1
chips   13    6    2
```
We can easily add a total column with
```python
>>> df.assign(total=lambda x: x.sum(axis='columns'))
       foo  bar  baz  total
spam    10    4    0     14
egg     19    5    1     25
chips   13    6    2     21
```
or some other summary total, e.g.:
```python
>>> df.assign(b_total=lambda x: x.bar + x.baz)
       foo  bar  baz  b_total
spam    10    4    0        4
egg     19    5    1        6
chips   13    6    2        8
```
but the API doesn't present an equivalent way to do that for rows.

### Feature Description

Add a new `DataFrame.assign_rows` method to allow for code like:
```python
>>> df.assign_rows(total=lambda x: x.sum(axis='rows'))
       foo  bar  baz
spam    10    4    0
egg     19    5    1
chips   13    6    2
total   42   15    3
```
or :

```python
>>> df.assign_rows(veggie_total=lambda x: x.loc['egg'] + x.loc['chips'])
              foo  bar  baz
spam           10    4    0
egg            19    5    1
chips          13    6    2
veggie_total   32   11    3
```
Potentially it could be done by adding an `axis` parameter to `DataFrame.assign`, but that would break code with a column called "axis".

### Alternative Solutions

It's possible to get the same effect in a chaining context using two `DataFrame.transpose`s, e.g.:
```python
>>>df.transpose().assign(veggie_total=lambda x: x['egg'] + x['chips']).transpose()
              foo  bar  baz
spam           10    4    0
egg            19    5    1
chips          13    6    2
veggie_total   32   11    3
```
but transposing is a huge operation for such a simple thing. Alternatively, it can be done using `DataFrame.pipe` like:
```python
>>> def assign_rows(df, **kwargs):
        df = df.copy(deep=None)
        for key, item in kwargs.items():
            if callable(item):
                df.loc[key] = item(df)
            else:
                df.loc[key] = item
        return df
>>> df.pipe(assign_rows, veggie_total=lambda x: x.loc['egg'] + x.loc['chips'])
              foo  bar  baz
spam           10    4    0
egg            19    5    1
chips          13    6    2
veggie_total   32   11    3
```
but `pipe` isn't an obvious thing to find when searching the docs for a way to do this - I feel like `assign_rows` would be much more consistent and easier for users to find. Obviously it can be done by creating a new variable, but avoiding that is the whole reason that `assign` exists in the first place.

### Additional Context

[The code for](https://github.com/pandas-dev/pandas/blob/v2.1.3/pandas/core/frame.py#L4947-L5013) `DataFrame.assign` is particularly simple:
```python
def assign(self, **kwargs) -> DataFrame:
    # Doc String removed for brevity
        
    data = self.copy(deep=None)

    for k, v in kwargs.items():
        data[k] = com.apply_if_callable(v, data)
    return data
```
presumably the code for the row equivalent wouldn't be particularly more complicated, 

I'm happy to take this one if it has community support.

**Comment by phofl** [comment]
-1 on this

We deprecated append because it invited appending single rows which is very inefficient

**Comment by jreback** [comment]
-1 this is not idiomatic for column based layouts

**Comment by MarkRotchell** [comment]
What about for use cases where rows are just as semantically meaningful as columns, e.g. a table of revenue with products as rows and stores as columns (adding a new product makes as much sense as adding a new store), or a table of student grades with students as rows and classes as columns (adding a new student makes as much sense as adding a new class). Isn't that why pandas has a row index, rather than just a row number - so that rows can have meaning beyond just "an observation of some features"?

**Comment by phofl** [comment]
This still copies for every assign statement, which is definitely not what we want to encourage

**Comment by mroeschke** [comment]
> What about for use cases where rows are just as semantically meaningful as columns

You _can_ do this in pandas but as already mentioned it's not efficient. pandas operates more efficiently when you structure data by column, and you treat the index as row labels for selection/metadata. it's best to treat pandas DataFrames like sql tables e.g. a DataFrames of revenue and a DataFrames of stores joinable by a key

**Comment by phofl** [comment]
Closing, this is not something that we want
