### ISSUE TITLE
BUG: np.sign of double[pyarrow] NA

### ISSUE THREAD

**Issue by mdruiter** [pandas-dev/pandas#56097]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import numpy as np
import pandas as pd

np.sign(pd.Series([float('nan')], dtype='double[pyarrow]'))
```

### Issue Description

I'm trying to use pyarrow types in pandas. Most things just work. But np.sign does not, at least when nans/NAs exist. Is this something pandas should fix?

### Expected Behavior

I would expect np.sign to treat pd.NA just like np.nan instead of failing.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : 2a953cf80b77e4348bf50ed724f8abc0d814d9dd
python              : 3.11.6.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.22631
machine             : AMD64
processor           : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : Dutch_Netherlands.1252

pandas              : 2.1.3
numpy               : 1.26.2
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 65.5.0
pip                 : 23.3.1
Cython              : 3.0.5
pytest              : 7.4.2
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : 8.17.2
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : 1.3.7
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.8.1
numba               : None
numexpr             : 2.8.7
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : 14.0.1
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.3
sqlalchemy          : 2.0.23
tables              : None
tabulate            : None
xarray              : None
xlrd                : 2.0.1
zstandard           : 0.21.0
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by paulreece** [comment]
Confirmed that it raises a `TypeError` with this on `main`.

```python
>>> np.sign(pd.Series([float('nan')], dtype='double[pyarrow]'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/paulreece/python_projects/pandas-paulreece/pandas/core/generic.py", line 2119, in __array_ufunc__
    return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)
  File "/Users/paulreece/python_projects/pandas-paulreece/pandas/core/arraylike.py", line 399, in array_ufunc
    result = getattr(ufunc, method)(*inputs, **kwargs)
  File "/Users/paulreece/python_projects/pandas-paulreece/pandas/core/arrays/base.py", line 2283, in __array_ufunc__
    return arraylike.default_array_ufunc(self, ufunc, method, *inputs, **kwargs)
  File "/Users/paulreece/python_projects/pandas-paulreece/pandas/core/arraylike.py", line 492, in default_array_ufunc
    return getattr(ufunc, method)(*new_inputs, **kwargs)
  File "pandas/_libs/missing.pyx", line 392, in pandas._libs.missing.NAType.__bool__
    raise TypeError("boolean value of NA is ambiguous")
TypeError: boolean value of NA is ambiguous
```

**Comment by phofl** [comment]
This is not an upstream issue, that's on our side

**Comment by phofl** [comment]
We fixed this and also added tests for these cases, so closing
