### ISSUE TITLE
BUG: rolling standard deviation results are different to whats expected

### ISSUE THREAD

**Issue by Haaroon** [pandas-dev/pandas#56105]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
data = [123, 234, 343, 134, 546, 383, 785, 820, 909, 111]
data_pd = pd.Series(data)
data_pd.rolling(window=3).std()


## results

<details>

```python
0           NaN
1           NaN
2    110.001515
3    104.532292
4    206.007281
5    207.490562
6    202.193801
7    242.829844
8     63.929649
9    437.303480
dtype: float64
```
</details>
```
```

### Issue Description

I think the pandas.rolling.std result is giving an incorrect example and i have shown code examples

### Expected Behavior

The expected result should be as follows, 

# with talib

```python
import talib
talib.STDDEV(pd.Series(data), timeperiod=3)
```
## result 

<details>

```python
0           NaN
1           NaN
2     89.815861
3     85.350259
4    168.204241
5    169.415334
6    165.090548
7    198.269738
8     52.198340
9    357.056796
dtype: float64
```
</details>

# by hand

```python
def rolling_std_dev(data, window_size):
    if window_size > len(data):
        raise ValueError("Window size larger than data length")

    def std_dev(slice_data):
        mean = sum(slice_data) / len(slice_data)
        variance = sum((x - mean) ** 2 for x in slice_data) / len(slice_data)
        return variance ** 0.5

    rolling_std = [
        std_dev(data[i:i + window_size])
        for i in range(len(data) - window_size + 1)
    ]
    return rolling_std
rolling_std_dev(data, 3)
```
## result

<details>

```python
[89.81586100956162, 85.35025873813545, 168.20424092949222, 169.4153344758247, 165.09054754554813, 198.26973770318273, 52.19833969262496, 357.0567959800731]
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : 2a953cf80b77e4348bf50ed724f8abc0d814d9dd
python              : 3.10.13.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 23.1.0
Version             : Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:27 PDT 2023; root:xnu-10002.41.9~6/RELEASE_X86_64
machine             : x86_64
processor           : i386
byteorder           : little
LC_ALL              : None
LANG                : en_GB.UTF-8
LOCALE              : en_GB.UTF-8

pandas              : 2.1.3
numpy               : 1.23.5
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.2.2
pip                 : 23.3.1
Cython              : None
pytest              : 7.4.3
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : 3.1.9
lxml.etree          : 4.9.3
html5lib            : 1.1
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.17.2
pandas_datareader   : 0.10.0
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : 2023.10.0
gcsfs               : None
matplotlib          : 3.8.1
numba               : 0.56.4
numexpr             : 2.8.7
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : 14.0.1
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.3
sqlalchemy          : 2.0.23
tables              : 3.9.1
tabulate            : 0.9.0
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None
</pre></div>

</details>

**Comment by jrmylow** [comment]
Quick investigation, the results found are consistent with the denominator in variance being calculated with `len(slice_data) - 1`. This is consistent with the calculation for sample variance vs population variance (which uses `len(slice_data)`) - for the distinction see [0].
 
```python
def rolling_std_dev(data, window_size):
    if window_size > len(data):
        raise ValueError("Window size larger than data length")

    def std_dev(slice_data):
        mean = sum(slice_data) / len(slice_data)
        variance = sum((x - mean) ** 2 for x in slice_data) / (len(slice_data) - 1) # Denominator -1
        return variance ** 0.5

    rolling_std = [
        std_dev(data[i:i + window_size])
        for i in range(len(data) - window_size + 1)
    ]
    return rolling_std
rolling_std_dev(data, 3)
```

This produces the result:
```
[110.00151514108038, 104.53229166147655, 206.0072814247108, 207.49056203435694, 202.19380142163936, 242.82984440412864, 63.92964883369844, 437.30347967210747]
```

[0] https://stats.stackexchange.com/questions/17890/what-is-the-difference-between-n-and-n-1-in-calculating-population-variance

**Comment by Haaroon** [comment]
Thanks for clarifying, so pandas is using a different type of variance when compared to everyone else. I see.

**Comment by phofl** [comment]
You can easily set ddof to 0 to get your expected result (the default of 1 is documented as well)
