### ISSUE TITLE
BUG: append --> concat

### ISSUE THREAD

**Issue by celestinoxp** [pandas-dev/pandas#56119]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
https://github.com/pycaret/pycaret/blob/master/pycaret/containers/base_container.py
```

### Issue Description

I'm trying give support to pandas 2 on Pycaret, but something its not working, the change from append() to concat().
I need some help to my pull-request (change all append to concat) - https://github.com/pycaret/pycaret/pull/3824
(the pycaret team doesn't seem to have time to help me)

### Expected Behavior

someone help to support pandas 2, only needs change append to concat

### Installed Versions

<details>

2.0 or higer

</details>

**Comment by mroeschke** [comment]
> but something its not working

Could provide a minimal example, without pycaret, that demonstrates the issue?

**Comment by MarcoGorelli** [comment]
it's `DataFrame.append` that's been removed, not `list.append`, which is what you're changing in your PR

we don't really have resources to help with the PR to a different project, but if you post a minimal reproducible example we can take a look

closing for now then
