### ISSUE TITLE
DataFrame inspector GUI, df.inspect()

### ISSUE THREAD

**Issue by y-p** [pandas-dev/pandas#5611]
#5013 is in the sandbox, the functionality would be useful as `df.inspect()`,

popping up a gui grid view of the frame.
In the future, it's possible to detect ipnb and render a js grid instead, if the coming ipython 
js functionality is adequate, to cover the remote kernel use-case (less common).

cc @alefnula

**Comment by jorisvandenbossche** [comment]
I think this is out of scope for core pandas, therefore closing (but it would certainly be nice to see better plugins for jupyter notebooks / jupyterlab)
