### ISSUE TITLE
BUG: `pd.nlargest` with `keep='all'` does not return the correct result

### ISSUE THREAD

**Issue by psads-git** [pandas-dev/pandas#56221]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
technologies =  "A B C D E F G H I J".split()
duration     = [88,70,50,87,77,88,77,88,1,87]
columns      = ['technologies','duration']
df = pd.DataFrame(list(zip(technologies,duration)), columns=columns)
df.nlargest(3, 'duration', keep='all')
```

### Issue Description

According to the example that uses `keep='all'`, the 3 top values and their duplicates should show up in the result, but only the value `88` is returned.

### Expected Behavior

```
  technologies  duration
0            A        88
5            F        88
7            H        88
3            D        87
9            J        87
4            E        77
6            G        77

```

### Installed Versions

/home/x/myenv/lib64/python3.11/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit              : 2a953cf80b77e4348bf50ed724f8abc0d814d9dd
python              : 3.11.6.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 6.5.12-300.fc39.x86_64
Version             : #1 SMP PREEMPT_DYNAMIC Mon Nov 20 22:44:24 UTC 2023
machine             : x86_64
processor           : 
byteorder           : little
LC_ALL              : None
LANG                : en_US.utf8
LOCALE              : en_US.UTF-8

pandas              : 2.1.3
numpy               : 1.26.2
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 69.0.2
pip                 : 23.3.1
Cython              : 3.0.6
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : 4.9.3
html5lib            : 1.1
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.18.1
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : 2023.10.0
gcsfs               : None
matplotlib          : 3.8.2
numba               : 0.58.1
numexpr             : None
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.4
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

**Comment by samukweku** [comment]
You have three 88s in your data, so it rightly returns that. It returns only what is in your data

**Comment by psads-git** [comment]
Thanks, @samukweku, for your answer.

I guess that is not expected, considering the example given at, where more than 3 rows are returned:

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nlargest.html

```
>>> df.nlargest(3, 'population', keep='all')
          population      GDP alpha-2
France      65000000  2583560      FR
Italy       59000000  1937894      IT
Malta         434000    12011      MT
Maldives      434000     4520      MV
Brunei        434000    12128      BN

```

**Comment by asishm** [comment]
see #45041. From that I took it to mean that `nlargest` with `keep='all'` will only go beyond `n` if there happen to be duplicates that require going beyond `n`. In this case there are only 3 duplicates of the largest value. If you had 4 88s then you'd get all 4 with `keep='all'`.

**Comment by psads-git** [comment]
Thanks, @samukweku  and @asishm. In fact, this is the same issue reported at https://github.com/pandas-dev/pandas/issues/45041

I am going to mark this as duplicate.

**Comment by phofl** [comment]
Yep this behaves as expected, doc contributions are welcome. Closing as duplicate
