### ISSUE TITLE
BUG: background_gradient obviously has a problem with colormaps

### ISSUE THREAD

**Issue by JB-AM** [pandas-dev/pandas#56255]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
#code from https://github.com/pandas-dev/pandas/issues/47695 that was working then!
import itertools
import numpy as np
import pandas as pd

df_rand = pd.DataFrame(index=range(5), columns=range(5), dtype=float)

for idx1, idx2 in itertools.combinations_with_replacement(df_rand.index, 2):
    df_rand.loc[idx1, idx2] = np.random.randint(0, 100)

df_rand.style.format("{:.0f}", na_rep="").background_gradient()
```

### Issue Description

Long message error ending with:
`AttributeError: module 'matplotlib' has no attribute 'colormaps'`
`<pandas.io.formats.style.Styler at 0x29dc7abfa90>`

### Expected Behavior

Show the expected background_gradient

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit              : 2a953cf80b77e4348bf50ed724f8abc0d814d9dd
python              : 3.9.7.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.19045
machine             : AMD64
processor           : Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : fr_FR.cp1252

pandas              : 2.1.3
numpy               : 1.26.2
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 57.4.0
pip                 : 23.3.1
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.4.0
pandas_datareader   : None
bs4                 : 4.11.1
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.4.3
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : 3.0.9
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.4
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : 2.1.0
pyqt5               : None
</details>

**Comment by attack68** [comment]
Have you tied with a more recent version of matplotlib (>3.4.3 from 2021)?

**Comment by attack68** [comment]
Yes that is true but managing every sinlge one of pandas dependencies for all its functions in all pandas versions is a very difficult task.
