### ISSUE TITLE
BUG: new string dtype fails with >2 GB of data in a single column

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#56259]
(Patrick already opened PR https://github.com/pandas-dev/pandas/pull/56220 with a change that addresses this, but posting it here anyway to have an example reproducer and some context for one of the reasons to switch to large string)

With the new String dtype enabled, and creating a Series with string data that holds more than 2GB of data:

```python
import numpy as np
import string
data = ["".join(np.random.choice(list(string.ascii_letters), n)) for n in np.random.randint(10, 500, size=10_000)]

pd.options.future.infer_string = True
ser = pd.Series(data * 1000)
ser.memory_usage() / 1024**3
# 2.4261587597429752
```

then the `take` function fails:
```
In [28]: ser.take([0, 1, 2])
...
File ~/scipy/pandas/pandas/core/arrays/arrow/array.py:1199, in ArrowExtensionArray.take(self, indices, allow_fill, fill_value)
   1195         return result
   1196         # return type(self)(pc.fill_null(result, pa.scalar(fill_value)))
   1197     else:
   1198         # Nothing to fill
-> 1199         return type(self)(self._pa_array.take(indices))
   1200 else:  # allow_fill=False
   1201     # TODO(ARROW-9432): Treat negative indices as indices from the right.
   1202     if (indices_array < 0).any():
   1203         # Don't modify in-place

File ~/miniconda3/envs/dev311/lib/python3.11/site-packages/pyarrow/table.pxi:1029, in pyarrow.lib.ChunkedArray.take()

...

File ~/miniconda3/envs/dev311/lib/python3.11/site-packages/pyarrow/error.pxi:100, in pyarrow.lib.check_status()

ArrowInvalid: offset overflow while concatenating arrays
```

This is because of a current limitation of the `take` compute function in Arrow for ChunkedArrays that cannot be combined into a single Array (https://github.com/apache/arrow/issues/25822, https://github.com/apache/arrow/issues/33049). And this issue specifically comes up with the Arrow `string` type, which uses int32 offsets and thus has a max of 2147483647 (`(2 ** 32) / 2)`) characters for all values in a single array, which is around 2G of data. 
Arrow has a `large_string` type which uses int64 offsets instead, and essentially removes an upper limit (at least for pandas' use cases, it's in the petabytes).

And given that this happens in the `take` operation, this has a large consequence on various pandas operations (alignment, reindexing, joining, ...) that will fail with the current string dtype if you have a larger dataset.

xref https://github.com/pandas-dev/pandas/issues/54792

**Comment by jorisvandenbossche** [comment]
Another occurrence of the same underlying issue is when a string columns gets created from some operation, for example starting from a column that fits in a single pyarrow StringArray, but becomes too big through the operation. The error you then see:

```python
import numpy as np
import string
data = ["".join(np.random.choice(list(string.ascii_letters), 10)) for _ in range(1_000_000)]

pd.options.future.infer_string = True
ser = pd.Series(data * 100)  # <-- a bit more than 1GB, fits in a single chunk
```

```
>>> ser + "_some_suffix"
...
File ~/scipy/pandas/pandas/core/arrays/arrow/array.py:675, in ArrowExtensionArray._evaluate_op_method(self, other, op, arrow_funcs)
    673 sep = pa.scalar("", type=pa_type)
    674 if op is operator.add:
--> 675     result = pc.binary_join_element_wise(self._pa_array, other, sep)
    676 elif op is roperator.radd:
    677     result = pc.binary_join_element_wise(other, self._pa_array, sep)
...
ArrowCapacityError: array cannot contain more than 2147483646 bytes, have 2200000000
```

which fails because pyarrow currently hasn't any smart logic of splitting the result when needed (it's an element wise kernel, and so it preserves the input chunking).

**Comment by sqr00t** [comment]
Hiya, I notice that #56220 addressed the issue @jorisvandenbossche described, but I've encountered another occurance of `ArrowCapacityError: array cannot contain more than 2147483646 bytes`. Caused by reading a parquet produced with `pd.DataFrame.to_parquet(index=True)`

I have a ~6.9GB .parquet file, while rather unorthodox, includes an index column produced by `pd.DataFrame.to_parquet('file.parquet', index=True)`. The schema (col_name, dtype) is below, where `description` does contain some long strings from some webscraped data:
```
[
 ('id', Int64),
 ('description', String),
 ('__index_level_0__', Int64)
]
```
Reading this `file.parquet` with `pd.read_parquet('file.parquet')` causes the error.

1. I've instead tried using `polars.read_parquet('file.parquet')`, with default parameter `use_pyarrow=False` and all three columns loaded with no issue.
2. Switching to `use_pyarrow=True` surfaces the same issue.
3. Following 1.,
```
file_polars_df.select(['id', 'description']).write_parquet('file_fixed.parquet')

pd.read_parquet('file_fixed.parquet') # loads fine due to omitting `__index_level_0__`
```
4. However,
```
file_polars_df.select(['id', 'description']).to_pandas().to_parquet('file_with_index.parquet', index=True)

pd.read_parquet('file_with_index.parquet')
```
and I encounter the same ArrowCapacityError again.

Info on my system and env:
2021 MacBook Pro with M1 Pro 16GB RAM
Python: 3.8.18
pandas==2.0.3
pyarrow==14.0.1
polars==0.20.3

**Comment by phofl** [comment]
Can you provide a reproducer? We won't be able to help otherwise

It's possible that your DataFrame has arrow backed dtypes and that this uses pd.ArrowDtype(pa.string()) instead of large string, but this is outside of our control if your parquet file is saved like this

**Comment by jorisvandenbossche** [comment]
@sqr00t also, with which version of pandas and pyarrow are you reading this file? And did you enable certain pandas options? (because if you are not reading this with the latest pandas with the infer_string option set, it's probably not related to this issue, but an issue with pyarrow itself, given that the error comes from reading the parquet file itself with pyarrow before pandas is involved)

**Comment by sqr00t** [comment]
@phofl @jorisvandenbossche Thanks for both your replies and apologies for any confusion.

With pandas 2.1.4 (latest stable), and enable infer_string option with `pd.set_option("future.infer_string", True)` the file reads correctly. In my previous comment, I mentioned I was using pandas 2.0.3.

Appreciate the help!

**Comment by phofl** [comment]
We don't patch bugs in 2.0.x anymore, so the only thing you can do is upgrade
