### ISSUE TITLE
Restructure offset deprecation whatsnew

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#56299]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

Personally, I'd prefer having a table with for -> after instead of the text blocks, that might make it easier to use. 

Shorter headline would also be helpful I guess and direct folks more towards the direct mapping

thoughts @natmokval ?

### Documentation problem

see

### Suggested fix for documentation

see

**Comment by natmokval** [comment]
Thank you, @phofl, I agree, a table will look better than the text block.
I replaced offset deprecation text block with a table and made the headline shorter. Could you please take a look at my PR #56364?
