### ISSUE TITLE
BUG: df.mask with int df throws ValueError instead of TypeError

### ISSUE THREAD

**Issue by sfc-gh-rdurrani** [pandas-dev/pandas#56330]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame(["a", "b", "c"], ["d", "e", "f"])
df.mask(df)
```

### Issue Description

This should result in a ValueError that a boolean value must be passed, but instead, it throws a TypeError for `~` being applied to strings.

### Expected Behavior

ValueError: Boolean array expected for the condition, not object

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : 2a953cf80b77e4348bf50ed724f8abc0d814d9dd
python              : 3.10.13.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 23.1.0
Version             : Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020
machine             : arm64
processor           : arm
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.3
numpy               : 1.26.1
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.0.0
pip                 : 23.3
Cython              : None
pytest              : 7.4.3
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : 8.17.2
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : 2023.10.0
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : 10.0.1
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : 1.4.50
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None
</details>

Also present on pandas 1.5.3

**Comment by rhshadrach** [comment]
Thanks for the report. It seems to me the values of the string data is not the issue - there is no possible string value that won't raise. Thus, I don't think a `ValueError` would be appropriate here. From the Python docs on ValueError:

> Raised when an operation or function receives an argument that has the right type but an inappropriate value

 Rather, it's the type of the data being passed, and so `TypeError` is appropriate.

**Comment by phofl** [comment]
Yep agreed, closing

**Comment by sfc-gh-rdurrani** [comment]
Does this mean that the code should be changed to throw a TypeError for dfs with int columns as well then?

**Comment by rhshadrach** [comment]
Confirmed on main - yes, I think these should be TypeErrors. PR to fix is welcome!

**Comment by DarthKitten2130** [comment]
I created a PR for the issue. Check it out.

**Comment by DarthKitten2130** [comment]
Made a PR for this. Check it out.

**Comment by reshma045** [comment]
@rhshadrach which part of the code should be changed here? Could you please help?

**Comment by abhigyan631** [comment]
Is this issue still open? If yes, can I please work on it?

**Comment by TahirAlauddin** [comment]
**@rhshadrach** I wonder why is this issue is still open. Didn't **@DarthKitten2130** merged a PR already?

**Comment by rhshadrach** [comment]
Thanks @TahirAlauddin - confirmed #56495 closed this.
