### ISSUE TITLE
Whole JSON gets dumped from error in _pull_records()

### ISSUE THREAD

**Issue by wjandrea** [pandas-dev/pandas#56405]
This error message shows the entire JSON, then the erroring part, both of which can be very large.

https://github.com/pandas-dev/pandas/blob/68c1af5358561b4655861f99ac1dfb27ac5d4d56/pandas/io/json/_normalize.py#L429-L432

Example:

```python
url = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=5min&apikey=demo'
r = requests.get(url)
data = r.json()

meta = pd.json_normalize(data, 'Meta Data')
```

Error (clipped for readability):

```
Traceback (most recent call last):

  Cell In[50], line 1
    meta = pd.json_normalize(data, 'Meta Data')

  File pandas/io/json/_normalize.py:519 in json_normalize
    _recursive_extract(data, record_path, {}, level=0)

  File pandas/io/json/_normalize.py:501 in _recursive_extract
    recs = _pull_records(obj, path[0])

  File pandas/io/json/_normalize.py:431 in _pull_records
    raise TypeError(

TypeError: {'Meta Data': {'1. Information': 'Intraday (5min) open, high, low, close prices and volume', '2. Symbol': 'IBM', '3. Last Refreshed': '2023-12-07 19:55:00', '4. Interval': '5min', '5. Output Size': 'Compact', '6. Time Zone': 'US/Eastern'}, 'Time Series (5min)': ...} has non list value {'1. Information': 'Intraday (5min) open, high, low, close prices and volume', '2. Symbol': 'IBM', '3. Last Refreshed': '2023-12-07 19:55:00', '4. Interval': '5min', '5. Output Size': 'Compact', '6. Time Zone': 'US/Eastern'} for path Meta Data. Must be list or null.
```

(Here I've clipped the `'Time Series (5min)'` value, but it takes up an order of magnitude more space.)

I believe the error could be changed to simply:

```python
raise TypeError(f"non list value for path {spec}. Must be list or null.")
```

Then if you need more information, you can inspect `data[spec]`.

Although, that wouldn't be ideal for cases where you've inlined the data retrieval, like `pd.json_normalize(requests.get(url).json(), 'Meta Data')`.

**Comment by mroeschke** [comment]
Thanks for the report. Maybe

```python
raise TypeError(f"{spec} contains {type(result).__name__}. Must be list or null.")
```

to at least inform of the type present that isn't a list or null

**Comment by wjandrea** [comment]
While we're here, `spec` should probably be printed as `repr` instead of `str`, so:

```python
raise TypeError(f"{spec!r} contains {type(result).__name__}. Must be list or null.")
```

**Comment by mroeschke** [comment]
I think your suggestion in https://github.com/pandas-dev/pandas/issues/56405#issuecomment-1847775873 looks good. Happy to have a PR!

**Comment by rmhowe425** [comment]
take
