### ISSUE TITLE
BUG: Polars to Pandas conversion resets the column names to integers

### ISSUE THREAD

**Issue by Vincent-Maladiere** [pandas-dev/pandas#56433]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import polars as pl

X = pl.DataFrame(dict(a=[1, 2], b=[2, 4]))
print(X)
# shape: (2, 2)
# ┌─────┬─────┐
# │ a   ┆ b   │
# │ --- ┆ --- │
# │ i64 ┆ i64 │
# ╞═════╪═════╡
# │ 1   ┆ 2   │
# │ 2   ┆ 4   │
# └─────┴─────┘

print(pd.DataFrame(X))
#    0  1
# 0  1  2
# 1  2  4
```

### Issue Description

Converting a Polars dataframe into a Pandas dataframe resets the column names to integers.

### Expected Behavior

Keep the column names.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 8aa7a96765ff4f5e2e157fdbacedc442381292b4
python                : 3.10.13.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 20.6.0
Version               : Darwin Kernel Version 20.6.0: Thu Jul  6 22:12:47 PDT 2023; root:xnu-7195.141.49.702.12~1/RELEASE_X86_64
machine               : x86_64
processor             : i386
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : None.UTF-8

pandas                : 2.2.0.dev0+865.g8aa7a96765
numpy                 : 1.26.2
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 68.2.2
pip                   : 23.3.1
Cython                : None
pytest                : 7.4.3
hypothesis            : None
sphinx                : 7.2.6
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.2
IPython               : 8.18.1
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.2
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : 3.8.2
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 14.0.1
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.11.4
sqlalchemy            : None
tables                : None
tabulate              : 0.9.0
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2023.3
qtpy                  : None
pyqt5                 : None

</details>

**Comment by asishm** [comment]
thanks for the report. The current documentation for `pd.DataFrame` does not give any indication that this should work. `X.to_pandas()`  seems to be the expected way to convert.

**Comment by mroeschke** [comment]
Thanks for the report but this was already discussed in https://github.com/pandas-dev/pandas/issues/47368 and decided that `to_pandas` was sufficient so closing

**Comment by Vincent-Maladiere** [comment]
That sounds like a poor decision UX-wise but I leave that to you.
