### ISSUE TITLE
ENH: Support case insensitive for merge

### ISSUE THREAD

**Issue by belongwqz** [pandas-dev/pandas#56447]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Maybe the merge method should add a case parameter to identify case insensitive.

### Feature Description

```
def merge(self, other, on, case=False, ...):
    self.on_ = self.on.str.lower()
    other.on_ = other.on.str.lower()
    ...
```

### Alternative Solutions

Add a param `case` to the method merge of dataframe like:`a.merge(b, case=False)`，to identify case insensitive.

**Comment by mroeschke** [comment]
Thanks for the suggestion but I would be -1 on this enhancement. `on` can be any type (not just strings) and can be easily done before the merge

**Comment by phofl** [comment]
agree with @mroeschke 

there is no performance benefit of doing this within merge
