### ISSUE TITLE
BUG: sort_values() after multiple float operations

### ISSUE THREAD

**Issue by YuxiLing** [pandas-dev/pandas#56452]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
d=[ [35,13],[36,-30]]
columns=['c0','c1']
df1=pd.DataFrame(d,columns=columns)

df1=df1.div([10, 9],axis=0)
df1=df1.div(5)
df1=df1.mul([8, 7],axis=0)
df1=df1.sort_values(by=['c0', 'c1'],ascending=True)
```

### Issue Description

The output of the above example:
```
    c0        c1
0  5.6  2.080000
1  5.6 -4.666667
```
The order of the column `c1` is not correct. It should be ascending.

### Expected Behavior

```
    c0        c1
1  5.6 -4.666667
0  5.6  2.080000
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : b4c9df811a234d50646540f9b4dc92ad39d7c77b
python                : 3.11.5.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 21.5.0
Version               : Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
machine               : x86_64
processor             : i386
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : None.UTF-8

pandas                : 2.2.0.dev0+867.gb4c9df811a
numpy                 : 1.26.2
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 68.1.2
pip                   : 23.2.1
Cython                : 3.0.5
pytest                : 7.4.3
hypothesis            : 6.92.0
sphinx                : 6.2.1
blosc                 : 1.11.1
feather               : None
xlsxwriter            : 3.1.9
lxml.etree            : 4.9.3
html5lib              : 1.1
pymysql               : 1.4.6
psycopg2              : 2.9.9
jinja2                : 3.1.2
IPython               : 8.18.1
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.2
bottleneck            : 1.3.7
dataframe-api-compat  : None
fastparquet           : 2023.10.1
fsspec                : 2023.12.1
gcsfs                 : 2023.12.1
matplotlib            : 3.8.2
numba                 : 0.58.1
numexpr               : 2.8.7
odfpy                 : None
openpyxl              : 3.1.2
pandas_gbq            : None
pyarrow               : 14.0.1
pyreadstat            : 1.2.5
python-calamine       : None
pyxlsb                : 1.0.10
s3fs                  : 2023.12.1
scipy                 : 1.11.4
sqlalchemy            : 2.0.23
tables                : 3.9.2
tabulate              : 0.9.0
xarray                : 2023.12.0
xlrd                  : 2.0.1
zstandard             : 0.22.0
tzdata                : 2023.3
qtpy                  : None
pyqt5                 : None

</details>

**Comment by rob-sil** [comment]
Looks like rounding error in the floating-point operations. After those operations, the values in column `c0` are not exactly the same! They're close enough to both be displayed as 5.6, however the value in the index `0` row is ever-so-slightly larger. From the final (sorted) data frame: 

```python
>>> df1.iloc[0, 0]
5.6
>>> df1.iloc[0, 1]
5.6000000000000005
```

With distinct values in column `c0`, the ascending sort reorders the columns, swapping the rows. Then, as there are no duplicates in column `c0`, sorting doesn't proceed to column `c1`.

This kind of rounding error is a general property of floating-point arithmetic, so I don't think this is a bug in `pandas`. A decimal type might solve this specific problem.

**Comment by rhshadrach** [comment]
Agreed @rob-sil. One can also display more decimal values in your output using [`display.precision`](https://pandas.pydata.org/pandas-docs/dev/user_guide/options.html).
