### ISSUE TITLE
BUG: Division over ExtensionArrays does not set mask correctly

### ISSUE THREAD

**Issue by DavideCanton** [pandas-dev/pandas#56451]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

v = pd.Series([1.0, 0.0], dtype="Float64")
s = v / v

print(pd.isna(s)) # prints [False, False]
```

### Issue Description

The above code should print a series containing `[False, True]` since 0/0 should return a float nan, but prints `[False, False]`.

It seems that `s._values._mask` is `[False, False]`, since the nan is not converted to pd.NA, that is expected for the dtype Float64. Maybe there is some issue in the handling of the mask of the result of a binary operation?

### Expected Behavior

It should print `[False, True]`.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a671b5a8bf5dd13fb19f0e88edc679bc9e15c673
python              : 3.12.0.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.19045
machine             : AMD64
processor           : Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : Italian_Italy.1252

pandas              : 2.1.4
numpy               : 1.26.0
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.2.2
pip                 : 23.2.1
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : 8.16.1
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.8.0
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : 14.0.1
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by DavideCanton** [comment]
Probably it's a duplicate of #53887

**Comment by rhshadrach** [comment]
Agreed @DavideCanton - closing as a duplicate.
