### ISSUE TITLE
ENH: Feature Request - Add a method to DataFrame to retrieve unique values per column

### ISSUE THREAD

**Issue by ABDULLAH-HHH** [pandas-dev/pandas#56468]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I would like to propose the addition of a new method to the pandas DataFrame class that simplifies the process of retrieving unique values per column. Currently, users need to write custom code to achieve this, which can be repetitive and time-consuming.

### Feature Description

I suggest adding a method called get_unique_values() to the DataFrame class that automatically generates a new DataFrame containing the unique values for each column. This method would iterate over each column, retrieve the unique values using the unique() function, and store them in a new DataFrame. Additionally, any missing values could be filled with empty strings using the fillna() function.
Here is an example implementation of the proposed method:

def get_unique_values(dataframe):
    unique_values_per_column = {}
    for column in dataframe.columns:
        unique_values = dataframe[column].unique()
        unique_values_per_column[column] = pd.Series(unique_values)
    unique_df = pd.DataFrame(unique_values_per_column)
    return unique_df.fillna('')

**Comment by attack68** [comment]
The pandas API is quite large already. New functions have a high bar to be added. This does not really fit the bill becuase the data is so easily extracted in one line.

```
{col: df[col].unique() for col in df.columns}
```

Sure, thats not a DataFrame but it can be restructured into one and this depends on how the user wants to treat missing values for series of different lengths. That is a user decision and not always sensible to just assume the user wants empty strings.

**Comment by mroeschke** [comment]
Agreed with the reasons above - your proposed method seems straightforward enough to be handled on an as-need basis and doesn't appear to need maintenance in pandas.

Thanks for the suggestion but closing
