### ISSUE TITLE
BUG: Float64Dtype series become numpy arrays with "object" dtype

### ISSUE THREAD

**Issue by johentsch** [pandas-dev/pandas#56472]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
from scipy.stats import entropy
S = pd.Series([0.0, 1.1, 2.2], dtype=pd.Float64Dtype())
entropy(S)
```

Fails with

> TypeError: ufunc 'entr' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

### Issue Description

What happens in `scipy.stats.entropy()` is `np.asarray(S)`, yielding an array of dtype `'O'` (object). The internal `scipy.special.entr` rejects the input because of this. Funnily enough, it _does_ accept sequences containing `pd.NA` which it ignores, it's really the 'object' dtype which it dislikes:

```python
from scipy.special import entr
s = pd.Series([0.0, 1.1, pd.NA], dtype=pd.Float64Dtype())
entr(s) # passes
entr(np.asarray(s)) # fails
```

### Expected Behavior

I don't know if you folks think this should be fixed on the numpy or scipy side but I think it would be great if a floating series would translate to a floating array without trouble. Obviously this would mean that `pd.NA` would need to become `np.nan` and I don't now if this is feasible in pandas.

EDIT: The same thing happens for `Int64`.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a671b5a8bf5dd13fb19f0e88edc679bc9e15c673
python              : 3.11.5.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 6.1.66-1-MANJARO
Version             : #1 SMP PREEMPT_DYNAMIC Fri Dec  8 12:49:23 UTC 2023
machine             : x86_64
processor           : 
byteorder           : little
LC_ALL              : en_US.UTF-8
LANG                : en_US.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.4
numpy               : 1.26.2
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 69.0.2
pip                 : 23.3.1
Cython              : None
pytest              : 7.4.3
hypothesis          : None
sphinx              : 5.3.0
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : 4.9.3
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.18.1
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.8.2
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.4
sqlalchemy          : 2.0.23
tables              : None
tabulate            : 0.9.0
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

.../lib/python3.11/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

</details>

**Comment by mroeschke** [comment]
Thanks for the report. This will be fixed in 2.2 so closing https://pandas.pydata.org/docs/dev/whatsnew/v2.2.0.html#extensionarray-to-numpy-converts-to-suitable-numpy-dtype
