### ISSUE TITLE
DOC: Add note about `git fetch upstream --tags` to contributing guide

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#56475]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/development/contributing_environment.html#

### Documentation problem

If you are working from an old fork that doesn't sync tags with pandas upstream, versioneer will install pandas with a really old version tag which other dependencies like pyarrow don't like

### Suggested fix for documentation

Add a note that users may want to run `git fetch upstream --tags` before installing

**Comment by MaanavS16** [comment]
There already appears to be a note mentioning the need for `git fetch upstream --tags`

https://github.com/pandas-dev/pandas/commit/70f90b7020370fe257e308169bb9363fdadec215

**Comment by WillAyd** [comment]
Ah thanks @MaanavS16  I think that covers this
