### ISSUE TITLE
ENH: add limit_area argument to ffill() method as interpolate( method='ffill', limit_area='inside') as been deprecated

### ISSUE THREAD

**Issue by j-carson** [pandas-dev/pandas#56492]
### Feature Type

- [X] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I am trying to clean up my FutureWarnings and there is no obvious replacement for interpolate( method='ffill', limit_area ='inside')

### Feature Description

The limit_area argument to ffill() method would work as it does in the interpolate() method

### Alternative Solutions

Maybe you could find the first and last row of valid data using notna() on the column and then null-out the rows that were accidentally filled by fillna? 

### Additional Context

The interpolate(method='ffill') is deprecated in issue #53581, but there is no provision made for users who were using limit_area = 'inside' in that PR

**Comment by rhshadrach** [comment]
@jbrockmendel - any thoughts to expanding the keywords of `ffill` and `bfill`?

**Comment by jbrockmendel** [comment]
Looks like that might be necessary, yah

**Comment by rhshadrach** [comment]
I should have time to take this up, want to get it into 2.2 because the behavior elsewhere has already been deprecated.
