### ISSUE TITLE
CI: micromamba error 

### ISSUE THREAD

**Issue by twoertwein** [pandas-dev/pandas#56497]
All CI runs seems to fail with: "Error: You are using a condarc file that is not named '.condarc'. This is currently not supported by micromamba, see https://github.com/mamba-org/mamba/issues/1394"

https://github.com/pandas-dev/pandas/actions/runs/7209921420/job/19641945191?pr=56493
![image](https://github.com/pandas-dev/pandas/assets/6618166/ba0fdcac-6cd5-44e4-91db-8e1f1c22bde2)

**Comment by pavelzw** [comment]
Sorry, this is from the latest release of setup-micromamba 😅  I'll publish a fix that only prints this as a warning.
