### ISSUE TITLE
BUG: Did not expect new dtype datetime64[ns] to equal self.dtype datetime64[ns]

### ISSUE THREAD

**Issue by StefanFrey** [pandas-dev/pandas#56502]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
change_date["latest_change_at"].fillna(np.datetime64('2001-01-01T00:00:00'), inplace=True)


AssertionError: Did not expect new dtype datetime64[ns] to equal self.dtype datetime64[ns]. Please report a bug at https://github.com/pandas-dev/pandas/issues.
```

### Issue Description

Original code was:
change_date["latest_change_at"].fillna("2001-01-01T00:00:00Z", inplace=True)
This is my error:
Value '2001-01-01T00:00:00Z' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.

So I tried to change the values for the fillna to datetime64[ns] by running this:
change_date["latest_change_at"].fillna(np.datetime64('2001-01-01T00:00:00'), inplace=True)

### Expected Behavior

This should cast.

### Installed Versions

Pandas 2.1.4

**Comment by phofl** [comment]
Hi, thanks for your report. Can you give us a full reproducer that includes the construction of ``change_date``?

**Comment by mroeschke** [comment]
Closing as this issue needs more information to reproduce

**Comment by thecurve8** [comment]
```python
import pandas as pd

df = pd.DataFrame({
'datetime' : pd.date_range('1/1/2011', period=3, freq='H'),
'value' : [1,2,3]
})

df.iloc[0,0] = None
df.fillna(pd.Timestamp('0001-01-01'), inplace=True)
```
