### ISSUE TITLE
BUG: Chained comparison in `.where()` condition throws 

### ISSUE THREAD

**Issue by Lordfirespeed** [pandas-dev/pandas#56514]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
a = pd.Series(range(10))
a.where(lambda x: (4 < x) & (x < 7)) # succeeds
a.where(lambda x: 4 < x < 7) # throws
```

### Issue Description

The second `.where` throws a `ValueError: the truth value of a Series is ambiguous. ...` although the first `.where` succeeds.

### Expected Behavior

The second `.where` should not throw and should produce a similar result to the first `.where`. 

### Installed Versions

<details>

```
python              : 3.11.1.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.19045
machine             : AMD64
processor           : AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : English_United Kingdom.1252
pandas              : 2.1.4
numpy               : 1.26.2
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.2.0
pip                 : 23.2.1
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.18.1
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.8.2
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None
```

</details>

**Comment by rhshadrach** [comment]
The operation `4 < x < 7` is not supported. In short, Python's `4 < x < 7` does not behave will with respect to vectorized operations and so we raise here.

The details are: `4 < x < 7` is equivalent to `4 < x and x < 7`. The `4 < x` first returns a Boolean Series, and then the use of `and` tries to determine whether this Boolean Series is True or False. That's why you get that ValueError message.

**Comment by rhshadrach** [comment]
Closing for now - @Lordfirespeed if you think I missed anything comment here and we can reopen.

**Comment by Lordfirespeed** [comment]
I don't entirely understand why `4 < x` returns a Boolean Series?

Why can I do this:

```py
5 < a[3] < 7
```
with no problems?

**Comment by Lordfirespeed** [comment]
Oh, I'm getting it now. `.where()` doesn't execute for each component of the series, it asks for a function that returns a 'mask' series of `True` or `False` which will be applied to the original series.

**Comment by rhshadrach** [comment]
Yes - that's correct!
