### ISSUE TITLE
BUG: Large integer values corrupted after outer join due to missing values and float / int conversion

### ISSUE THREAD

**Issue by orionlee** [pandas-dev/pandas#56517]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
df1 = pd.DataFrame(data=dict(
    id=[1,2,3],
))
                  
df2 = pd.DataFrame(data=dict(
        id=[1, 2],
        Source=[8676220978733875968, 987, ],  # int64
))

df = pd.merge(df1, df2, on="id", how="outer")

print("\nAfter Outer Join:")
print(df)
# converted to float64, to accommodate missing values post join
print("Source column dtype:", df["Source"].dtype)
# the float and the int values are still considered equal   
print("\nAre the numbers preserved:", df2["Source"].iloc[0] == df["Source"].iloc[0])


df["Source"] = df["Source"].astype("Int64")
print("\nConvert float64 to Int64")
print(df)
print("Source column dtype:", df["Source"].dtype)

# the large integer gets corrupted after converting back to Int64
print("\nAre the numbers preserved:", df2["Source"].iloc[0] == df["Source"].iloc[0])
```

### Issue Description

Large integer values gets corrupted in some outer join operations when
1. the relevant column gets converted from int64 to float64 because of missing values after outer join
2. users convert the column to `float64` to `Int64`, which can handle missing value.
3. Sufficiently large integer values are corrupted.

One can avoid the problem if they convert the `int64` column to nullable `Int64` *before* doing the outer join, bypassing the float - int conversion.

This might not count as a bug. But if not, the scenario is at bug prone.

### Expected Behavior

Ultimately, the large integer values need to be preserved after the outer join. 
For1 the join operation, it might make sense if it converts `int64` column to nullable `Int64` (at least optionally, as Nullable integer type is still marked as experimental).

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : 2a953cf80b77e4348bf50ed724f8abc0d814d9dd
python              : 3.10.13.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.22621
machine             : AMD64
processor           : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : English_United States.1252

pandas              : 2.1.3
numpy               : 1.26.2
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.2.2
pip                 : 23.3.1
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.18.1
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None
</details>

**Comment by phofl** [comment]
Thanks for your report.

You can either use Int64 or int64[pyarrow] to get rid of this problem, int64 has suffered from this since forever and this is not expected to change

**Comment by orionlee** [comment]
The issue stems from that when doing left outer join, pandas converts integer columns to float to handle missing values.

Assuming this semantics is not going to change, would it make sense to provide an option in join methods that'll instruct pandas to use nullable integer instead of float instead? Something like:

```python
  pd.merge(df1, df2, on="id", how="outer", missing_values_dtypes="Int64")
```

It is almost a syntactic sugar, but for users facing similar scenarios, they are less likely to encounter the integer value corruption problem, if the option of conversion is provided at the method itself.
