### ISSUE TITLE
TST: assert_produces_warning multiple warnings/messages

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#56555]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
NA
```

### Issue Description

Sometimes when deprecating something I will find a test like:

```
def test_foo():
    with tm.assert_produces_warning(UnrelatedWarning, match=unrelated_msg):
        thing_that_i_am_deprecating()
```

When this happens, the only viable option I'm aware of is to change `UnrelatedWarning` to `(UnrelatedWarning, FutureWarning)`.  But this doesn't a) check that we get _both_ or b) check that we get a reasonable message for the FutureWarning.

The request here is for a way to specify a list of (warning, msg) pairs and check that we get all of them and no others.  _Or_ to make `@pytest.mark.filterwarnings("ignore:my_message:FutureWarning")` actually work in this context.

### Expected Behavior

NA

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by Jorewin** [comment]
take
