### ISSUE TITLE
BUG: pandas nightly wheel requires numpy<2

### ISSUE THREAD

**Issue by lesteve** [pandas-dev/pandas#56563]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```bash
conda create -n test-env python -y
conda activate test-env
dev_anaconda_url=https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
pip install --pre --upgrade --timeout=60 --extra-index $dev_anaconda_url numpy pandas 
python -c 'import numpy; print(numpy.__version__)'
```
Outputs:
```
1.26.2
```

### Issue Description

pandas nightly wheel from scientific-python-nightly-wheel requires numpy<2.

In scikit-learn we want to test against the development version of our dependencies for numpy, scipy, pandas, etc ... 

From the command we were using, we were expecting that numpy development version will be installed before closely looking at the CI log and realising that we actually get numpy latest release. More context from https://github.com/scikit-learn/scikit-learn/pull/27899.

I think our current approach in scikit-learn is to not pin numpy<2 in `main` but pin it on release branches.

### Expected Behavior

Installs numpy-2.0.0.dev0 from scientific-python-nightly-wheel

### Installed Versions

pandas-2.2.0.dev0+925.gac170fdc35

**Comment by rhshadrach** [comment]
cc @lithomas1

**Comment by lithomas1** [comment]
We are almost compatible with numpy 2.0 (I have some NEP 50 changes that still need to be made), so hopefully we should be able to unpin sometime by the end of this week.

**Comment by lesteve** [comment]
OK thanks, no real rush from the scikit-learn side, since there is an easy work-around.

**Comment by bsipocz** [comment]
This would be really nice to have for us over at `numpy-tutorials`, too. As currently I cannot easily test the material with numpy 2.0 as pandas blocks installing it.
