### ISSUE TITLE
ENH: Add an option/a parameter to set index name when initiating a data frame

### ISSUE THREAD

**Issue by mikbuch** [pandas-dev/pandas#56578]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

There is no option to set index name when creating/initiating the dataframe object. You have to do this by setting the index's attribute only after creating the DF.

### Feature Description

I wish to be able to specify index name when creating the data frame, i.e.:

```
import pandas as pd

# Creating a DataFrame with specified index labels and name
data = {'Column1': [1, 2, 3], 'Column2': ['A', 'B', 'C']}
index_labels = ['Row1', 'Row2', 'Row3']

df = pd.DataFrame(data, index=index_labels, index_name='MyIndexName')

print(df)
```

Instead of, as it is now:

```
import pandas as pd

# Creating a DataFrame with specified index labels and name
data = {'Column1': [1, 2, 3], 'Column2': ['A', 'B', 'C']}
index_labels = ['Row1', 'Row2', 'Row3']

df = pd.DataFrame(data, index=index_labels)
df.index.name = 'MyIndexName'

print(df)
```

Output in both should be:

```
             Column1 Column2
MyIndexName                 
Row1               1       A
Row2               2       B
Row3               3       C
```

### Alternative Solutions

Alternative is just to use the existing mechanism.

**Comment by mroeschke** [comment]
Thanks for the suggestion but this can also be done via `pd.DataFrame(index=pd.Index(..., name="MyIndexName"))`

pandas has a fairly high bar for API changes and unfortunately I don't think this feature will meet that given the alternative to set the index name

**Comment by mikbuch** [comment]
> Thanks for the suggestion but this can also be done via `pd.DataFrame(index=pd.Index(..., name="MyIndexName"))`
> 
> pandas has a fairly high bar for API changes and unfortunately I don't think this feature will meet that given the alternative to set the index name

@mroeschke , thank you for a prompt reply. Thank you for showing me the alternative way. I respect the decision not to include my request into API. Just thought I will share my opinion on this, that would be handy to have.

Have a good day
