### ISSUE TITLE
BUG: Series.str.startswith/endswith don't support tuple pattern for pd.ArrowDtype(pa.string())

### ISSUE THREAD

**Issue by rohanjain101** [pandas-dev/pandas#56579]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> s = pd.Series(["abc", "def"], dtype=pd.ArrowDtype(pa.string()))
>>> s.str.startswith(("a", "d"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\pandasdev\pandas\core\strings\accessor.py", line 137, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pandasdev\pandas\core\strings\accessor.py", line 2484, in startswith
    result = self._data.array._str_startswith(pat, na=na)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pandasdev\pandas\core\arrays\arrow\array.py", line 2178, in _str_startswith
    result = pc.starts_with(self._pa_array, pattern=pat)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pd_dev_1208\Lib\site-packages\pyarrow\compute.py", line 259, in wrapper
    options = _handle_options(func_name, options_class, options,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pd_dev_1208\Lib\site-packages\pyarrow\compute.py", line 222, in _handle_options
    return options_class(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow\_compute.pyx", line 1107, in pyarrow._compute.MatchSubstringOptions.__init__
  File "pyarrow\_compute.pyx", line 1090, in pyarrow._compute._MatchSubstringOptions._set_options
  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_std__in_string
TypeError: expected bytes, tuple found
>>>
```

### Issue Description

An error is raised, when the call should succeed.

### Expected Behavior

```
>>> s = pd.Series(["abc", "def"], dtype=pd.StringDtype())
>>> s.str.startswith(("a", "d"))
0    True
1    True
dtype: boolean
>>>
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : f0b61c561858da28d22a1df7c03787ce8f1b482f
python                : 3.11.4.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.22631
machine               : AMD64
processor             : Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : English_United States.1252

pandas                : 2.1.0.dev0+2318.gf0b61c5618
numpy                 : 1.26.2
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 68.2.2
pip                   : 23.3.1
Cython                : 3.0.5
pytest                : 7.4.3
hypothesis            : 6.91.1
sphinx                : 6.2.1
blosc                 : 1.11.1
feather               : None
xlsxwriter            : 3.1.9
lxml.etree            : 4.9.3
html5lib              : 1.1
pymysql               : 1.4.6
psycopg2              : 2.9.9
jinja2                : 3.1.2
IPython               : 8.18.1
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.2
bottleneck            : 1.3.7
dataframe-api-compat  : None
fastparquet           : 2023.10.1
fsspec                : 2023.12.1
gcsfs                 : 2023.12.1
matplotlib            : 3.8.2
numba                 : 0.58.1
numexpr               : 2.8.7
odfpy                 : None
openpyxl              : 3.1.2
pandas_gbq            : None
pyarrow               : 14.0.1
pyreadstat            : 1.2.5
python-calamine       : None
pyxlsb                : 1.0.10
s3fs                  : 2023.12.1
scipy                 : 1.11.4
sqlalchemy            : 2.0.23
tables                : 3.9.2
tabulate              : 0.9.0
xarray                : 2023.11.0
xlrd                  : 2.0.1
zstandard             : 0.22.0
tzdata                : 2023.3
qtpy                  : None
pyqt5                 : None
>>>
</details>

**Comment by rhshadrach** [comment]
Thanks for report! Confirmed on main, further investigations and PRs to fix are welcome!

**Comment by rohanjain101** [comment]
PR for fix: https://github.com/pandas-dev/pandas/pull/56580
