### ISSUE TITLE
ENH: to_sql to consider upsert on oracle

### ISSUE THREAD

**Issue by sarathsairam** [pandas-dev/pandas#56575]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I would like to have pandas to consider easy implementation of upsert with specific focus on Oracle databases

### Feature Description

https://github.com/pandas-dev/pandas/issues/14553

the above issue doesn't confirm if it is implemented for oracle

### Alternative Solutions

Alternate solutions include creating merge statements on the fly

**Comment by mroeschke** [comment]
Thanks for the suggestion but this is unlikely to be implemented in pandas as to_sql needs to be database flavor agnostic.

You can implement this by creating a function and passing it to the `method` parameter
