### ISSUE TITLE
BUG: TypeError when using convert_dtypes() and pyarrow engine

### ISSUE THREAD

**Issue by dxdc** [pandas-dev/pandas#56581]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import pyarrow
from io import StringIO

# Sample data
data = """
Date Arrived,Arrival Time
12/19/23,18:42
"""

df = pd.read_csv(StringIO(data), engine='pyarrow')
df = df.convert_dtypes()

## TypeError: cannot set astype for copy = [True] for dtype (object [(1, 1)]) to different shape (object [(1,)])
```

### Issue Description

With the latest dev pandas, convert_dtypes() is not usable. This issue is related to the pyarrow engine, as removing the engine works fine.

### Expected Behavior

Should not crash with a TypeError.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 98e1d2f8cec1593bb8bc6a8dbdd164372286ea09
python                : 3.11.7.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.5.11-linuxkit
Version               : #1 SMP PREEMPT_DYNAMIC Wed Dec  6 17:14:50 UTC 2023
machine               : x86_64
processor             : 
byteorder             : little
LC_ALL                : None
LANG                  : C.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.0.dev0+936.g98e1d2f8ce
numpy                 : 1.26.2
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 69.0.2
pip                   : 23.3.2
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : 3.1.9
lxml.etree            : 4.9.3
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : 1.3.7
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2023.12.2
gcsfs                 : None
matplotlib            : None
numba                 : 0.58.1
numexpr               : 2.8.8
odfpy                 : None
openpyxl              : 3.1.2
pandas_gbq            : None
pyarrow               : 14.0.2
pyreadstat            : None
python-calamine       : None
pyxlsb                : 1.0.10
s3fs                  : 0.4.2
scipy                 : None
sqlalchemy            : 2.0.23
tables                : None
tabulate              : None
xarray                : None
xlrd                  : 2.0.1
zstandard             : None
tzdata                : 2023.3
qtpy                  : None
pyqt5                 : None
</details>

**Comment by mroeschke** [comment]
cc @phofl looks potentially related to pushing convert dtypes to the block level recently
