### ISSUE TITLE
BUG: DataFrame.replace with regex on `StringDtype` column with NA values stops replacing after first NA

### ISSUE THREAD

**Issue by Timost** [pandas-dev/pandas#56599]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame({'old': ['my', 'test', pd.NA, 'word', 'to', 'replace']}, dtype="string")
# In [3]: df
# Out[3]:
#        old
# 0       my
# 1     test
# 2     <NA>
# 3     word
# 4       to     
# 5  replace

 df['old'].replace(regex={r't.*': 'replaced'})
# Out[4]:
# 0          my
# 1    replaced
# 2        <NA>
# 3        word
# 4          to    <---- *** should have replaced this one ***
# 5     replace
# Name: old, dtype: string

df['old'].astype('object').replace(regex={r't.*': 'replaced'})
# Out[5]:
# 0          my
# 1    replaced
# 2        <NA>
# 3        word
# 4    replaced  <---- *** properly replaced***
# 5     replace
# Name: old, dtype: object
```

### Issue Description

Hi, thank you for pandas ❤🙏

When using regex, [`pandas.DataFrame.replace`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.replace.html) on a [StringDtype](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.StringDtype.html#pandas.StringDtype) column containing `pd.NA` values, the replacement stops after the first `pd.NA` value is met.

The problem doesn't occur when using the `object` dtype.

### Expected Behavior

I would expect the replacement to ignore NA values and still replace all matching values for both the `object` and the `StringDtype` dtypes.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a671b5a8bf5dd13fb19f0e88edc679bc9e15c673
python              : 3.11.5.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 5.15.133.1-microsoft-standard-WSL2
Version             : #1 SMP Thu Oct 5 21:02:42 UTC 2023
machine             : x86_64
processor           : x86_64
byteorder           : little
LC_ALL              : None
LANG                : C.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.4
numpy               : 1.26.2
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 69.0.2
pip                 : 23.3.1
Cython              : None
pytest              : 7.4.3
hypothesis          : None
sphinx              : 7.2.6
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.18.1
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : 2023.12.2
gcsfs               : None
matplotlib          : 3.8.2
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : 10.0.1
pyreadstat          : None
pyxlsb              : None
s3fs                : 2023.12.2
scipy               : 1.11.4
sqlalchemy          : 2.0.23
tables              : None
tabulate            : 0.9.0
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by rootsmusic** [comment]
Maybe related to issue #32233

**Comment by rootsmusic** [comment]
Oops, pasting again.  Maybe related to issue #54399

**Comment by Timost** [comment]
Thank you for fixing this !
