### ISSUE TITLE
QST: Long term numpy support

### ISSUE THREAD

**Issue by Delengowski** [pandas-dev/pandas#56601]
Given that pyarrow is becoming the default backend coming 3.0, I'm wondering what the roadmap for continued numpy support is like? Does the Pandas community every plan on dropping numpy fully? If not will it continue to monitor for performance regressions, and keeping both backends feature complete?

I ask because my work primarily revolves around reading in HDF5 data. We use h5py which outputs numpy arrays. I am concerned about our future and the overhead we are going to incur for going from numpy -> arrow. My best efforts in finding benchmarks have only provided [arrow -> numpy conversions](https://github.com/apache/arrow/issues/26926), while that issue is from 2020, a 1 second conversion is very long, and I see no reason why the reverse would be any faster. 

This concern is doubled because some of our data from hdf5 comes in as compound types (or volatile in numpy terms) and pandas must split those fields into individual arrays already, which in and of itself incurs a lot of overhead (we are working on minimizing these datatypes). I'm afraid that being force to go into arrow format will double our data loading operations.

**Comment by phofl** [comment]
> Given that pyarrow is becoming the default backend coming 3.0,

This is only correct for strings, every other dtype will still be backed by NumPy, so nothing changes there

**Comment by Delengowski** [comment]
Oh thank you. I misunderstood some things I read greatly.

**Comment by phofl** [comment]
Can I ask where you read something similar? I'd like to avoid misunderstandings for others if possible
