### ISSUE TITLE
QST: need help  

### ISSUE THREAD

**Issue by naman8989** [pandas-dev/pandas#56602]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/77704604/need-help-in-pandas-library

### Question about pandas

Hi, I am new to opensource can anyone tell me how to run pandas after cloning it from github ?

**Comment by phofl** [comment]
I would recommend to read this chapter in our docs: https://pandas.pydata.org/docs/dev/development/contributing.html

Please open a new and more targeted issue if you still have issues after reading through the chapter
