### ISSUE TITLE
BUG: Series.apply with arrow integral types passes nan instead of pd.NA for missing values to udf

### ISSUE THREAD

**Issue by rohanjain101** [pandas-dev/pandas#56606]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> s = pd.Series([1, None], dtype="int16[pyarrow]")
>>> def my_udf(value):
...     return str(value)
...
>>> s.apply(my_udf)
0    1.0
1    nan
dtype: object
>>>
```

### Issue Description

NaN is passed to udf instead of pd.NA, NaN should be impossible for integral type to hold

### Expected Behavior

Expected behavior is behavior from pandas 2.1.4:

```
>>> s = pd.Series([1, None], dtype="int16[pyarrow]")
>>> def my_udf(value):
...     return str(value)
...
>>> s.apply(my_udf)
0       1
1    <NA>
dtype: object
>>>
```

UDF receives pd.NA instead of NaN

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d4c8d82b52045f49a0bb1d762968918a06886ae9
python                : 3.11.4.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.22631
machine               : AMD64
processor             : Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : English_United States.1252

pandas                : 2.2.0rc0
numpy                 : 1.26.2
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 69.0.2
pip                   : 23.3.1
Cython                : None
pytest                : 7.0.1
hypothesis            : None
sphinx                : 4.2.0
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.2
IPython               : 8.19.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.2
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : 3.8.2
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 14.0.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.11.4
sqlalchemy            : None
tables                : None
tabulate              : 0.9.0
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2023.3
qtpy                  : None
pyqt5                 : None
</details>

**Comment by rohanjain101** [comment]
Based on discussion in https://github.com/pandas-dev/pandas/pull/56290, it seems it may be an intentional change in 2.2.x compared to 2.1.x.

**Comment by rohanjain101** [comment]
```
>>> pd.Series(map(my_udf, s))
0       1
1    <NA>
dtype: object
>>>
```

This gives the expected result, it seems a bit odd, that using apply would give a different result and call the udf with different values.

**Comment by phofl** [comment]
Yes this was indeed an intentional change to get rid of the annoying behaviour of converting to NumPy object all the time
