### ISSUE TITLE
DOC: "Copy On Write: Patterns to avoid" confusion

### ISSUE THREAD

**Issue by avm19** [pandas-dev/pandas#56622]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html#patterns-to-avoid

### Documentation problem

This code snippet
```python
In [59]: df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
In [60]: df2 = df.reset_index()
In [61]: df2.iloc[0, 0] = 100
```
is intended to illustrate that a copy (on write) will be created, because `df` and `df2` reference the same data. In reality, no copy will be created because `df2.iloc[0, 0]` refers to the newly created integer column storing the reset index, which exists for `df2`, but not for `df`.

### Suggested fix for documentation

Replace the last line of the snippet, 
```python
In [61]: df2.iloc[0, 0] = 100
```
with:
```python
In [61]: df2.iloc[0, 1] = 100
```

**Comment by rhshadrach** [comment]
cc @phofl

**Comment by phofl** [comment]
Thx, very good catch
