### ISSUE TITLE
ENH: read_csv tz (Timezone) preservation and / or specification

### ISSUE THREAD

**Issue by bionicles** [pandas-dev/pandas#56631]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish I could trust the `pd.read_csv` `engine="pyarrow"` to preserve timezones and [optionally, but may be handy for helper methods] produce pd.DatetimeIndex when parse_date=True pass a `tz="EST"` kwarg into `pd.read_csv` with `engine="pyarrow"` because the loading is extremely fast with pyarrow (0.221s for a 40+mb csv) but then, unfortunately, the timezone is clobbered and converted to UTC, so then we need to run another line of code

`df.index = pd.to_datetime(df.index).tz_convert(env.TZ)`, which multiplies the impressively fast runtime of pyarrow reading compressed csvs like 10x and it winds up taking 2-3 seconds instead of less than half a second, which is noticeable latency in practice

Pyarrow is screeching fast and seems great, but for some reason it looks at data like this `2004-01-02 08:00:00-05:00` and converts the whole column to UTC, so then users have to convert the whole Index `to_datetime` (it's an Index of pyarrow and then `tz_convert` back to EST. maybe the UTC conversion is normal, however, I find it slows down pyarrow engine a lot, and requires users to research docs, do we localize or convert? seems weird to parse dates then still need to `df.index = pd.to_datetime(df.index).tz_convert(env.TZ)`

It is extremely likely that I as a pandas novice don't know some dumb trick to speed this up exponentially, in which case this enhancement request could be charitably interpreted as a docs issue instead.

### Feature Description

I'll admit to not knowing pandas internals well enough to offer great advice, but, would it be possible to

**1. Ideal solution (user does nothing and pandas just works):**
Preserve time zones of parse_date=True and make a DatetimeIndex with engine="pyarrow"

**2. Alternate solution (explicit timezone kwarg in read_csv)**
Add a new keyword argument for the desired timezone to pd.read_csv to automatically convert timezones. 
When the engine=pyarrow is selected, then we could try to use the pyarrow csv reader to use pyarrow.compute.assume_timezone if the timezone is not in the input timezone

when engine is otherwise, we could use pd.to_datetime(col) if the column isn't parsed; tz_convert(desired_tz) if the timezone isn't right, 

then noobs like me can **Solution 1.** do nothing except switch to pyarrow engine, and trust the pyarrow read_csv will see "-5:00" and return "-5:00" timezone data (avoids silent mutation) or **Solution 2.** add an explicit `tz="EST"` keyword argument to obtain the expected results 

### Alternative Solutions

df.index = pd.to_datetime(df.index).tz_convert(env.TZ)
works for the functionality but adds an order of magnitude to runtime just to change timezones which were already present in the input data

### Additional Context

`2004-01-02 08:00:00-05:00` is the first non-header date value
using `csv.zst` (zstandard)
to compress 3317074 rows of this spy 1m candle data with timezones
```csv
date,o,h,l,c,v
2004-01-02 08:00:00-05:00,111.85,111.85,111.85,111.85,800.0
2004-01-02 08:01:00-05:00,111.82,111.82,111.82,111.82,200.0
2004-01-02 08:03:00-05:00,111.83,111.83,111.83,111.83,200.0
2004-01-02 08:04:00-05:00,111.81,111.81,111.8,111.8,3300.0
2004-01-02 08:06:00-05:00,111.85,111.85,111.85,111.85,700.0
2004-01-02 08:07:00-05:00,111.85,111.85,111.85,111.85,300.0
2004-01-02 08:09:00-05:00,111.83,111.83,111.83,111.83,300.0
2004-01-02 08:13:00-05:00,111.86,111.86,111.86,111.86,200.0
2004-01-02 08:17:00-05:00,111.86,111.86,111.86,111.86,300.0
2004-01-02 08:18:00-05:00,111.85,111.85,111.85,111.85,200.0
```
here's a 20,000 line subset, maybe not enough to reproduce. I used yahoo finance and tiingo and also bought some of it, i don't even remember, i'd upload it all but it's too big for github
[mini_spy_1m.csv](https://github.com/pandas-dev/pandas/files/13778223/mini_spy_1m.csv)
cell 1
```
import pandas as pd
import functools
import time
import os

# here's a way to benchmark the function in question
def timed(fun, name=None, return_elapsed=False):
    @functools.wraps(fun)
    def a_wrapped_fun(*args, **kwargs):
        start = time.perf_counter()
        result = fun(*args, **kwargs)
        elapsed = time.perf_counter() - start
        log.info(f'"{name or fun.__name__}" took {elapsed:.03f}s')
        if return_elapsed:
            return (result, elapsed)
        return result

    return a_wrapped_fun

@timed
def extract_spy_mins_pyarrow():
    filepath = os.path.join("data", "spy", "1min.csv.zst") # toggle this off
    # filepath = os.path.join("path", "to", "mini_spy_1m.csv") # toggle this on

    spy_mins = pd.read_csv(
        filepath,
        index_col="date",
        parse_dates=True,
        date_format="%Y-%m-%d %H:%M:%S%z", # tried without this
        engine="pyarrow",
        dtype_backend="pyarrow",
    )
    # spy_mins.index = pd.to_datetime(spy_mins.index).tz_convert(env.TZ) # toggle
    return spy_mins
```
cell 2
```
dfa = extract_spy_mins_pyarrow()
```
```
[2023-12-27_05:46:43_EST] INFO: "extract_spy_mins_pyarrow" took 0.221s       [ramda.py]
```
cell 3
```
print("A:", type(dfa.index))
print(dfa.index)
print(dfa.index[0], ":", type(dfa.index[0]))

print("index methods or attributes:")
for i, m_or_a in enumerate(dir(dfa.index)):
    print(f"    1.{i} {m_or_a}")
print("index value methods or attributes:")
for i, m_or_a in enumerate(dir(dfa.index[0])):
    print(f"    2.{i} {m_or_a}")
```
result:
```
A: <class 'pandas.core.indexes.base.Index'>
Index([2004-01-02 13:00:00+00:00, 2004-01-02 13:01:00+00:00,
       2004-01-02 13:03:00+00:00, 2004-01-02 13:04:00+00:00,
       2004-01-02 13:06:00+00:00, 2004-01-02 13:07:00+00:00,
       2004-01-02 13:09:00+00:00, 2004-01-02 13:13:00+00:00,
       2004-01-02 13:17:00+00:00, 2004-01-02 13:18:00+00:00,
       ...
       2023-12-26 20:50:00+00:00, 2023-12-26 20:51:00+00:00,
       2023-12-26 20:52:00+00:00, 2023-12-26 20:53:00+00:00,
       2023-12-26 20:54:00+00:00, 2023-12-26 20:55:00+00:00,
       2023-12-26 20:56:00+00:00, 2023-12-26 20:57:00+00:00,
       2023-12-26 20:58:00+00:00, 2023-12-26 20:59:00+00:00],
      dtype='timestamp[s, tz=UTC][pyarrow]', name='date', length=3317074)
2004-01-02 13:00:00+00:00 : <class 'pandas._libs.tslibs.timestamps.Timestamp'>
```
as you can see, the dates are parsed, but not into a DatetimeIndex; that would probably be OK if not for the fact we lost our timezone information.

toggling the tz_convert line, rerunning the earlier cells 1,2:
```
[2023-12-27_06:20:46_EST] INFO: "extract_spy_mins_pyarrow" took 3.940s
```
(~17x slower)
output of cell 3:
```
A: <class 'pandas.core.indexes.datetimes.DatetimeIndex'>
DatetimeIndex(['2004-01-02 08:00:00-05:00', '2004-01-02 08:01:00-05:00',
               '2004-01-02 08:03:00-05:00', '2004-01-02 08:04:00-05:00',
               '2004-01-02 08:06:00-05:00', '2004-01-02 08:07:00-05:00',
               '2004-01-02 08:09:00-05:00', '2004-01-02 08:13:00-05:00',
               '2004-01-02 08:17:00-05:00', '2004-01-02 08:18:00-05:00',
               ...
               '2023-12-26 15:50:00-05:00', '2023-12-26 15:51:00-05:00',
               '2023-12-26 15:52:00-05:00', '2023-12-26 15:53:00-05:00',
               '2023-12-26 15:54:00-05:00', '2023-12-26 15:55:00-05:00',
               '2023-12-26 15:56:00-05:00', '2023-12-26 15:57:00-05:00',
               '2023-12-26 15:58:00-05:00', '2023-12-26 15:59:00-05:00'],
              dtype='datetime64[ns, EST]', name='date', length=3317074, freq=None)
2004-01-02 08:00:00-05:00 : <class 'pandas._libs.tslibs.timestamps.Timestamp'>
```

**Comment by mroeschke** [comment]
Thanks for the report. pandas gets this behavior from pyarrow's csv reader so this enhancement request would be better directed to an arrow enhancement request

```python
In [19]: import pyarrow.csv

In [20]: import io

In [21]: s = """date,o,h,l,c,v
    ...: 2004-01-02 08:00:00-05:00,111.85,111.85,111.85,111.85,800.0
    ...: 2004-01-02 08:01:00-05:00,111.82,111.82,111.82,111.82,200.0"""

In [22]: pyarrow.csv.read_csv(io.BytesIO(s.encode()))
Out[22]: 
pyarrow.Table
date: timestamp[s, tz=UTC]
o: double
h: double
l: double
c: double
v: double
----
date: [[2004-01-02 13:00:00,2004-01-02 13:01:00]]
o: [[111.85,111.82]]
h: [[111.85,111.82]]
l: [[111.85,111.82]]
c: [[111.85,111.82]]
v: [[800,200]]
```
