### ISSUE TITLE
BUG: precision losing in frame creation when data contains large integers and missing values

### ISSUE THREAD

**Issue by paralyzah** [pandas-dev/pandas#56678]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import numpy as np
import pandas as pd


pd.set_option("display.precision", 20)

# creating df with missing values
data = [
    4873214862074861312,
    None,
    4873214862074860545,
    4875446630161458944,
    5931984171702399518,
    np.iinfo(np.int64).max,
    np.iinfo(np.uint64).max
]
df = pd.DataFrame({"id": data})

df.head(10)
                       id
0   4873214862074861568.0
1                     NaN
2   4873214862074860544.0
3   4875446630161459200.0
4   5931984171702400000.0
5   9223372036854775808.0
6  18446744073709551616.0

df.dtypes
id    float64
dtype: object


# creating df without missing values
data = [
    4873214862074861312,
    0,
    4873214862074860545,
    4875446630161458944,
    5931984171702399518,
    np.iinfo(np.int64).max,
    np.iinfo(np.uint64).max
]
df = pd.DataFrame({"id": data})

df.head(10)
                     id
0   4873214862074861312
1                     0
2   4873214862074860545
3   4875446630161458944
4   5931984171702399518
5   9223372036854775807
6  18446744073709551615

df.dtypes
id    uint64
dtype: object
```

### Issue Description

Implicit cast to float64 loses precision for input data

### Expected Behavior

The large integer values precision need to be preserved

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a671b5a8bf5dd13fb19f0e88edc679bc9e15c673
python              : 3.10.8.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 23.2.0
Version             : Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64
machine             : x86_64
processor           : i386
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : ru_RU.UTF-8
pandas              : 2.1.4
numpy               : 1.26.2
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 69.0.3
pip                 : 23.3.2
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : None
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by rohanjain101** [comment]
I think this is expected, by default if no dtype is specified, numpy types are used where integral types with missing values converted to float64 because nan is used to represent missing data. If you want to preserve integral types with missing values, you could use pyarrow types:

```
data = [
    4873214862074861312,
    None,
    4873214862074860545,
    4875446630161458944,
    5931984171702399518,
    np.iinfo(np.int64).max,
    np.iinfo(np.uint64).max
]
df = pd.DataFrame({"id": pd.Series(data, dtype="uint64[pyarrow]")})
```

Or the nullable integer types:

```
df = pd.DataFrame({"id": pd.Series(data, dtype="UInt64")})
```

More info can be found [here](https://pandas.pydata.org/docs/user_guide/integer_na.html)

**Comment by paralyzah** [comment]
Your approach does not work with data for multiple series because you can not specify multiple dtypes in DataFrame constructor. For instance if we have data similar like this:

```python
data = [
    {"id": 1, "name": "Billy"},
    {"id": 5931984171702399518, "name": "Joe"},
    {"id": np.iinfo(np.int64).max, "name": "Alice"}
]
```
it will to much tricky to avoid this behavior and possibly will waste much more time.

**Comment by rohanjain101** [comment]
You can do:

```
data = {
    "id": pd.Series([1, None, np.iinfo(np.int64).max], dtype="uint64[pyarrow]"),
    "name": pd.Series(["Billy", "Joe", "Alice"], dtype=pd.ArrowDtype(pa.string()))
}
pd.DataFrame(data)
```

**Comment by paralyzah** [comment]
It's looking good in this toy example! But if you have a large dataset from external system with structure like above - you will need to create series with specified dtypes in advance at least, and this will be significally slower than just data bypassing to frame constructor, because this will happen on python side :(

**Comment by rohanjain101** [comment]
I don't think "just data bypassing to frame constructor" would be faster, if you don't specify datatypes, it has to be inferred from the data, which is expensive, especially for a large dataset. Also, I'm not sure what you mean by "because this will happen on python side".

**Comment by paralyzah** [comment]
I mean if you have a structure like list of dicts - you need prepare series in advance (through list comprehensions / generator expressions aka on python side)

**Comment by paralyzah** [comment]
By the way, this does not change the fact that the values in described case less than int64 max value and they corrupted as well, when implicit cast to float64 happens.

**Comment by phofl** [comment]
this can be avoided if we support dicts for the dtype argument (there are issues about this and PRs would be welcome), closing here since the behaviour is expected
