### ISSUE TITLE
BUG: Interchange protocol implementation does not allow for empty string columns

### ISSUE THREAD

**Issue by stinodego** [pandas-dev/pandas#56703]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.Series([], name="a", dtype=str).to_frame()
dfi = df.__dataframe__()
result = pd.api.interchange.from_dataframe(dfi)
# NotImplementedError: Non-string object dtypes are not supported yet
```

### Issue Description

Empty string columns raise an error.

### Expected Behavior

pandas does not support non-string object dtypes, so it can assume an empty object column is a string column. No error should be thrown and the result in the example should be equal to the original dataframe.

@MarcoGorelli FYI ( sorry for the spam)

### Installed Versions

<details>

commit : https://github.com/pandas-dev/pandas/commit/a671b5a8bf5dd13fb19f0e88edc679bc9e15c673
python : 3.12.0.final.0
python-bits : 64
OS : Linux
OS-release : 5.15.133.1-microsoft-standard-WSL2
Version : https://github.com/pandas-dev/pandas/issues/1 SMP Thu Oct 5 21:02:42 UTC 2023
machine : x86_64
processor : x86_64
byteorder : little
LC_ALL : None
LANG : en_US.UTF-8
LOCALE : en_US.UTF-8

pandas : 2.1.4
numpy : 1.26.2
pytz : 2023.3.post1
dateutil : 2.8.2
setuptools : 68.2.2
pip : 23.3.2
Cython : None
pytest : 7.4.0
hypothesis : 6.92.1
sphinx : 7.2.4
blosc : None
feather : None
xlsxwriter : 3.1.9
lxml.etree : 4.9.4
html5lib : 1.1
pymysql : None
psycopg2 : None
jinja2 : 3.1.2
IPython : 8.18.1
pandas_datareader : None
bs4 : 4.12.2
bottleneck : None
dataframe-api-compat: None
fastparquet : None
fsspec : 2023.12.2
gcsfs : None
matplotlib : 3.8.2
numba : None
numexpr : None
odfpy : None
openpyxl : 3.1.2
pandas_gbq : None
pyarrow : 14.0.2
pyreadstat : None
pyxlsb : 1.0.10
s3fs : 2023.12.2
scipy : None
sqlalchemy : 2.0.24
tables : None
tabulate : 0.9.0
xarray : None
xlrd : None
zstandard : 0.22.0
tzdata : 2023.3
qtpy : None
pyqt5 : None

</details>

**Comment by MarcoGorelli** [comment]
> @MarcoGorelli FYI ( sorry for the spam)

😄 don't apologies, I very much appreciate you digging in and finding these

**Comment by roadrollerdafjorst** [comment]
take
