### ISSUE TITLE
CLN: Use assert_produces_warning instead of pytest.raises to show FutureWarning

### ISSUE THREAD

**Issue by natmokval** [pandas-dev/pandas#56716]
In some places we raise `FutureWarning` using pytest:
```
with pytest.raises(FutureWarning, match=msg):
```
Find and replace it with tm.assert_produces_warning

**Comment by pmhatre1** [comment]
I could find this FutureWarning in test_xml.py under the method test_empty_stylesheet(val) only @natmokval @rhshadrach

**Comment by edydfang** [comment]
take

**Comment by pmhatre1** [comment]
Not sure why the checks are failing even before I replace the original code with tm.assert_produces_warning?

**Comment by natmokval** [comment]
> I could find this FutureWarning in test_xml.py under the method test_empty_stylesheet(val) only

Yes, it's correct

**Comment by natmokval** [comment]
> Not sure why the checks are failing even before I replace the original code with tm.assert_produces_warning?

thank you for working on it @pmhatre1.
Try this: 
`pytest pandas/tests/io/xml/test_xml.py -k test_empty_stylesheet`
the test should pass

**Comment by pmhatre1** [comment]
@natmokval  The checks are still failing. The main reason after debugging, I found is that the path to the stylesheet and xml is not correct. I had to give absolute path to open the xml. Also, the Future warning is not working in my case. There is no try catch if the path to stylesheet is not given. In case you want to correct me or am I missing something here?
