### ISSUE TITLE
ENH: Full display method

### ISSUE THREAD

**Issue by marctorsoc** [pandas-dev/pandas#56713]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Today, when someone wants to visualize a dataframe with long values, needs to write something like
```
x = pd.get_option("display.max_colwidth")
pd.set_option("display.max_colwidth", None)
display(df)
pd.option_context("display.max_colwidth", x)
```
or
```
with pd.set_option("display.max_colwidth", None):
    display(df)
```

While the latter is less verbose, I still find it too much for a so common use case (the same applies for many rows, many columns, etc).

### Feature Description

At my company, we wrote a very simple helper to handle this. We call it `full_display`

```
def full_display(
    df,
    max_rows=None,
    max_colwidth=None,
    max_columns=None,
):
    """
    Pass options or leave it as default to use
    [
        "display.max_rows", None,
        "display.max_colwidth", None,
        "display.max_columns", None,
    ]
    """
    # fmt: off
    options = [
        "display.max_rows", max_rows or None,
        "display.max_colwidth", max_colwidth or None,
        "display.max_columns", max_columns or None,
    ]
    # fmt: on
    with pd.option_context(*options):
        display(df)
```

(please ignore the `fmt: on` stuff for black)

I'd be happy to write a PR to add this, but before all the hassle of writing tests, etc. asking for feedback. And maybe there's something we missed out and pandas already has a solution

I'm open to make it more general so it supports any option in kwargs, or a special value to keep the current value (or other ideas)

### Alternative Solutions

Well, I can continue with our custom solution. But I think it's worth to have something like this directly into pandas tbh

**Comment by mroeschke** [comment]
Thanks for the suggestion but I would be -1 to have this directly in pandas. The library has been moving towards not having multiple ways to achieve the same task and I think your solution can be used in an ad-hoc fashion

**Comment by rhshadrach** [comment]
Agreed @mroeschke; @marctorsoc - it seems to me this is the type of function that can live on the users end.
