### ISSUE TITLE
BUILD: Pandas failed to install

### ISSUE THREAD

**Issue by oddbookworm** [pandas-dev/pandas#56710]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

N/A (ran in CI)

### Installation Method

pip install

### pandas Version

2.1.4

### Python Version

3.9

### Installation Logs

<details>

Collecting pandas
  Downloading pandas-2.1.4.tar.gz (4.3 MB)
     ---------------------------------------- 4.3/4.3 MB 18.2 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [23 lines of output]
  + meson setup C:\Users\appveyor\AppData\Local\Temp\1\pip-install-n8iqqdx6\pandas_53c0803[86](https://ci.appveyor.com/project/astanin/python-tabulate/builds/48868438/job/p51s5xjmxvdmbth1#L86)3da465b9d09bbbbe101663b C:\Users\appveyor\AppData\Local\Temp\1\pip-install-n8iqqdx6\pandas_53c0803863da465b9d09bbbbe101663b\.mesonpy-m8qwd8hd\build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=C:\Users\appveyor\AppData\Local\Temp\1\pip-install-n8iqqdx6\pandas_53c0803863da465b9d09bbbbe101663b\.mesonpy-m8qwd8hd\build\meson-python-native-file.ini
  The Meson build system
  Version: 1.2.1
  Source dir: C:\Users\appveyor\AppData\Local\Temp\1\pip-install-n8iqqdx6\pandas_53c0803863da465b9d09bbbbe101663b
  Build dir: C:\Users\appveyor\AppData\Local\Temp\1\pip-install-n8iqqdx6\pandas_53c0803863da465b9d09bbbbe101663b\.mesonpy-m8qwd8hd\build
  Build type: native build
  Project name: pandas
  Project version: 2.1.4
  Activating VS 17.8.2
  C compiler for the host machine: cl (msvc 19.38.33130 "Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33130 for x64")
  C linker for the host machine: link link 14.38.33130.0
  C++ compiler for the host machine: cl (msvc 19.38.33130 "Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33130 for x64")
  C++ linker for the host machine: link link 14.38.33130.0
  Cython compiler for the host machine: cython (cython 0.29.37)
  Host machine cpu family: x86_64
  Host machine cpu: x86_64
  Program python found: YES (C:\Python39\python.exe)
  Need python for x86_64, but found x86
  Run-time dependency python found: NO (tried sysconfig)
  
  ..\..\pandas\_libs\tslibs\meson.build:23:7: ERROR: Python dependency not found

</details>

**Comment by oddbookworm** [comment]
It was CI from [tabulate](https://github.com/astanin/python-tabulate). After looking at their [appveyor.yml](https://github.com/astanin/python-tabulate/blob/master/appveyor.yml), it looks like it's 32-bit python 3.9. Full build log from the failed CI run

<details>

Build started
git clone -q https://github.com/astanin/python-tabulate.git C:\projects\python-tabulate
git fetch -q origin +refs/pull/306/merge:
git checkout -qf FETCH_HEAD
Running Install scripts
%PYTHON%\python.exe -m pip install setuptools --upgrade
Requirement already satisfied: setuptools in c:\python39\lib\site-packages (58.1.0)
Collecting setuptools
  Obtaining dependency information for setuptools from https://files.pythonhosted.org/packages/55/3a/51[2](https://ci.appveyor.com/project/astanin/python-tabulate/builds/48868438/job/p51s5xjmxvdmbth1#L2)1b58b578a598b2695[3](https://ci.appveyor.com/project/astanin/python-tabulate/builds/48868438/job/p51s5xjmxvdmbth1#L3)7e09a316ad2a9[4](https://ci.appveyor.com/project/astanin/python-tabulate/builds/48868438/job/p51s5xjmxvdmbth1#L4)fdd[5](https://ci.appveyor.com/project/astanin/python-tabulate/builds/48868438/job/p51s5xjmxvdmbth1#L5)[6](https://ci.appveyor.com/project/astanin/python-tabulate/builds/48868438/job/p51s5xjmxvdmbth1#L6)1a2c6eb[7](https://ci.appveyor.com/project/astanin/python-tabulate/builds/48868438/job/p51s5xjmxvdmbth1#L7)5cd6[8](https://ci.appveyor.com/project/astanin/python-tabulate/builds/48868438/job/p51s5xjmxvdmbth1#L8)578cc6b/setuptools-69.0.3-py3-none-any.whl.metadata
  Downloading setuptools-69.0.3-py3-none-any.whl.metadata (6.3 kB)
Downloading setuptools-69.0.3-py3-none-any.whl (819 kB)
   ---------------------------------------- 819.5/819.5 kB 5.8 MB/s eta 0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 58.1.0
    Uninstalling setuptools-58.1.0:
      Successfully uninstalled setuptools-58.1.0
Successfully installed setuptools-69.0.3
[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: C:\Python39\python.exe -m pip install --upgrade pip
%PYTHON%\python.exe -m pip install wheel --upgrade
Collecting wheel
  Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/c7/c3/55076fc728723ef927521abaa1955213d094933dc36d4a2008d5101e1af5/wheel-0.42.0-py3-none-any.whl.metadata
  Downloading wheel-0.42.0-py3-none-any.whl.metadata (2.2 kB)
Downloading wheel-0.42.0-py3-none-any.whl (65 kB)
   ---------------------------------------- 65.4/65.4 kB 1.8 MB/s eta 0:00:00
Installing collected packages: wheel
  WARNING: The script wheel.exe is installed in 'C:\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed wheel-0.42.0
[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: C:\Python39\python.exe -m pip install --upgrade pip
%PYTHON%\python.exe -m pip install build setuptools_scm
Collecting build
  Obtaining dependency information for build from https://files.pythonhosted.org/packages/93/dd/b464b728b866aaa62785a609e0dd8c72201d62c5f7c53e7c20f4dceb085f/build-1.0.3-py3-none-any.whl.metadata
  Downloading build-1.0.3-py3-none-any.whl.metadata (4.2 kB)
Collecting setuptools_scm
  Obtaining dependency information for setuptools_scm from https://files.pythonhosted.org/packages/0e/a3/b[9](https://ci.appveyor.com/project/astanin/python-tabulate/builds/48868438/job/p51s5xjmxvdmbth1#L9)a8b0adfe672bf0df5901707aa929d30a97ee390ba6519[10](https://ci.appveyor.com/project/astanin/python-tabulate/builds/48868438/job/p51s5xjmxvdmbth1#L10)186776746d2/setuptools_scm-8.0.4-py3-none-any.whl.metadata
  Downloading setuptools_scm-8.0.4-py3-none-any.whl.metadata (6.4 kB)
Collecting packaging>=19.0 (from build)
  Obtaining dependency information for packaging>=19.0 from https://files.pythonhosted.org/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl.metadata
  Downloading packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pyproject_hooks (from build)
  Downloading pyproject_hooks-1.0.0-py3-none-any.whl (9.3 kB)
Collecting colorama (from build)
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting importlib-metadata>=4.6 (from build)
  Obtaining dependency information for importlib-metadata>=4.6 from https://files.pythonhosted.org/packages/c0/8b/d8427f023c081a8303e6ac7209c16e6878f2765d5b59667f3903fbcfd365/importlib_metadata-7.0.1-py3-none-any.whl.metadata
  Downloading importlib_metadata-7.0.1-py3-none-any.whl.metadata (4.9 kB)
Collecting tomli>=1.1.0 (from build)
  Downloading tomli-2.0.1-py3-none-any.whl ([12](https://ci.appveyor.com/project/astanin/python-tabulate/builds/48868438/job/p51s5xjmxvdmbth1#L12) kB)
Requirement already satisfied: setuptools in c:\python39\lib\site-packages (from setuptools_scm) (69.0.3)
Collecting typing-extensions (from setuptools_scm)
  Obtaining dependency information for typing-extensions from https://files.pythonhosted.org/packages/b7/f4/6a90020cd2d93349b442bfcb657d0dc91eee65491600b2cb1d388bc98e6b/typing_extensions-4.9.0-py3-none-any.whl.metadata
  Downloading typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
Collecting zipp>=0.5 (from importlib-metadata>=4.6->build)
  Obtaining dependency information for zipp>=0.5 from https://files.pythonhosted.org/packages/d9/66/48866fc6b158c81cc2bfecc04c480f105c6040e8b077bc54c634b4a67926/zipp-3.17.0-py3-none-any.whl.metadata
  Downloading zipp-3.17.0-py3-none-any.whl.metadata (3.7 kB)
Downloading build-1.0.3-py3-none-any.whl (18 kB)
Downloading setuptools_scm-8.0.4-py3-none-any.whl (42 kB)
   ---------------------------------------- 42.1/42.1 kB 2.0 MB/s eta 0:00:00
Downloading importlib_metadata-7.0.1-py3-none-any.whl (23 kB)
Downloading packaging-23.2-py3-none-any.whl (53 kB)
   ---------------------------------------- 53.0/53.0 kB 2.9 MB/s eta 0:00:00
Downloading typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Downloading zipp-3.17.0-py3-none-any.whl (7.4 kB)
Installing collected packages: zipp, typing-extensions, tomli, packaging, colorama, setuptools_scm, pyproject_hooks, importlib-metadata, build
  WARNING: The script pyproject-build.exe is installed in 'C:\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed build-1.0.3 colorama-0.4.6 importlib-metadata-7.0.1 packaging-23.2 pyproject_hooks-1.0.0 setuptools_scm-8.0.4 tomli-2.0.1 typing-extensions-4.9.0 zipp-3.17.0
[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: C:\Python39\python.exe -m pip install --upgrade pip
%PYTHON%\python.exe -m pip install pytest numpy pandas
Collecting pytest
  Obtaining dependency information for pytest from https://files.pythonhosted.org/packages/51/ff/f6e8b8f39e08547faece4bd80f89d5a8de68a38b2d179cc1c4490ffa3286/pytest-7.4.4-py3-none-any.whl.metadata
  Downloading pytest-7.4.4-py3-none-any.whl.metadata (7.9 kB)
Collecting numpy
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/4b/db/a625c63df0ad581b8c7bc170f5fbd3894d48af3ea75[13](https://ci.appveyor.com/project/astanin/python-tabulate/builds/48868438/job/p51s5xjmxvdmbth1#L13)38aa8044277cfe6/numpy-1.26.3-cp39-cp39-win32.whl.metadata
  Downloading numpy-1.26.3-cp39-cp39-win32.whl.metadata (61 kB)
     ---------------------------------------- 61.2/61.2 kB 1.6 MB/s eta 0:00:00
Collecting pandas
  Downloading pandas-2.1.4.tar.gz (4.3 MB)
     ---------------------------------------- 4.3/4.3 MB 18.2 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [23 lines of output]
  + meson setup C:\Users\appveyor\AppData\Local\Temp\1\pip-install-n8iqqdx6\pandas_53c0803863da465b9d09bbbbe101663b C:\Users\appveyor\AppData\Local\Temp\1\pip-install-n8iqqdx6\pandas_53c0803863da465b9d09bbbbe101663b\.mesonpy-m8qwd8hd\build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=C:\Users\appveyor\AppData\Local\Temp\1\pip-install-n8iqqdx6\pandas_53c0803863da465b9d09bbbbe101663b\.mesonpy-m8qwd8hd\build\meson-python-native-file.ini
  The Meson build system
  Version: 1.2.1
  Source dir: C:\Users\appveyor\AppData\Local\Temp\1\pip-install-n8iqqdx6\pandas_53c0803863da465b9d09bbbbe101663b
  Build dir: C:\Users\appveyor\AppData\Local\Temp\1\pip-install-n8iqqdx6\pandas_53c0803863da465b9d09bbbbe101663b\.mesonpy-m8qwd8hd\build
  Build type: native build
  Project name: pandas
  Project version: 2.1.4
  Activating VS 17.8.2
  C compiler for the host machine: cl (msvc 19.38.33130 "Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33130 for x64")
  C linker for the host machine: link link [14](https://ci.appveyor.com/project/astanin/python-tabulate/builds/48868438/job/p51s5xjmxvdmbth1#L14).38.33130.0
  C++ compiler for the host machine: cl (msvc 19.38.33130 "Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33130 for x64")
  C++ linker for the host machine: link link 14.38.33130.0
  Cython compiler for the host machine: cython (cython 0.29.37)
  Host machine cpu family: x86_64
  Host machine cpu: x86_64
  Program python found: YES (C:\Python39\python.exe)
  Need python for x86_64, but found x86
  Run-time dependency python found: NO (tried sysconfig)
  
  ..\..\pandas\_libs\tslibs\meson.build:23:7: ERROR: Python dependency not found
  
  A full log can be found at C:\Users\appveyor\AppData\Local\Temp\1\pip-install-n8iqqdx6\pandas_53c0803863da465b9d09bbbbe10[16](https://ci.appveyor.com/project/astanin/python-tabulate/builds/48868438/job/p51s5xjmxvdmbth1#L16)63b\.mesonpy-m8qwd8hd\build\meson-logs\meson-log.txt
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
Encountered error while generating package metadata.
See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: C:\Python39\python.exe -m pip install --upgrade pip
Command exited with code 1

</details>

**Comment by lithomas1** [comment]
Yeah, we don't build wheels for 32-bit Windows/Linux anymore (since no one really downloads them), and we only test to make sure that 32-bit. Linux works.
