### ISSUE TITLE
TST: test for Styler.applymap_index

### ISSUE THREAD

**Issue by natmokval** [pandas-dev/pandas#56717]
Currently we have deprecation warnings (for example in the method `applymap_index`) for which we don’t have tests. We need to find methods with a deprecation warning without a test and add the test for them.

**Comment by edydfang** [comment]
take

**Comment by jomorodi** [comment]
the applymap_index method has a future warning and not a  deprecation warning in it  can you please provide a little detail about what kind of test is expected e.g. should the test pass if it has a future warning inside it? Br

**Comment by edydfang** [comment]
https://github.com/pandas-dev/pandas/blob/778ab8234059059d77eb5d71442c959f8d15c1e0/pandas/tests/io/formats/style/test_html.py#L436
@natmokval I found the test for it in older verion branch. Do you have any idea why those tests were removed?

**Comment by natmokval** [comment]
> @natmokval I found the test for it in older verion branch. Do you have any idea why those tests were removed?

@edydfang could you please give hash identifier of the commit, so I can check

**Comment by natmokval** [comment]
> the applymap_index method has a future warning and not a deprecation warning in it can you please provide a little detail about what kind of test is expected e.g. should the test pass if it has a future warning inside it? Br

To clarify: the method `applymap_index` is deprecated (one can see it in warnings message) and the type of  the Warning is `FutureWarning`
If you grep for `FutureWarning` in pandas/tests/ you'll see a lot of tests for FutureWarning.

**Comment by edydfang** [comment]
> > @natmokval I found the test for it in older verion branch. Do you have any idea why those tests were removed?
> 
> @edydfang could you please give a hash identifier of the commit, so I can check

https://github.com/pandas-dev/pandas/pull/52708

looks like in this PR the old test for `applymap_index` was replaced with the test for new API. 

Maybe I misunderstood the intent here: Are we testing the functional behavior of the function or are we testing the warning?

Looks like @jomorodi wrote a test that is testing the warning behavior.

**Comment by natmokval** [comment]
> Maybe I misunderstood the intent here: Are we testing the functional behavior of the function or are we testing the warning?

The task here is to write a test for FutureWarning. In this case it means that the test should contain the message "Styler.applymap_index has been deprecated. Use Styler.map_index instead."
