### ISSUE TITLE
BUG: `loc.__setitem__` with a DataFrame with mismatched columns raises PDEP 6 warning

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#56714]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
In [1]: import pandas as pd

In [2]: pdf = pd.DataFrame({"x": [1, 2, 3], "y": [4, 5, 6]})

In [3]: pdf.loc[[0, 2], ["x", "y"]] = pd.DataFrame({"b": [10, 20], "y": [30, 40]}, index=pd.Index([0, 2]))
<ipython-input-3-8b9b5b29ae75>:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[[nan 30.]
 [nan 40.]]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  pdf.loc[[0, 2], ["x", "y"]] = pd.DataFrame({"b": [10, 20], "y": [30, 40]}, index=pd.Index([0, 2]))

In [4]: pdf
Out[4]: 
     x     y
0  NaN  30.0
1  2.0   5.0
2  NaN  40.0
```

### Issue Description

It appears that the "b" and "x" columns are aligning, and since they don't have the same label the "b" column upcasts the existing "x" column.

### Expected Behavior

1. Raise if the setting DataFrame do not have the same column labels as the existing DataFrame?
2. A no-op leaving the unmatched DataFrame untouched?
3. Something else?

cc @mar

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by phofl** [comment]
cc @MarcoGorelli

**Comment by phofl** [comment]
The behaviour is consistent with how aligning works in loc, so any change to this logic would need a depreciation cycle

**Comment by MarcoGorelli** [comment]
the same happens with Series, right?
```python

In [15]: s = pd.Series([1,2,3], name='a')

In [16]: s.loc[:] = pd.Series([4,5,6], name='b')

In [17]: s
Out[17]:
0    4
1    5
2    6
Name: a, dtype: int64
```

as far as I can't tell it's not a pdep6 false positive, but please let me know if I've misunderstood and I'll address it

**Comment by mroeschke** [comment]
OK I suppose before doing the assignment in this case, the original frame needs to be cast first before assignment if all labels are not perfectly aligned. I'll close this one
