### ISSUE TITLE
BUG: Interchange protocol uses `u` for string format code but offets are 8 bytes

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#56754]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
When inspecting the offsets buffer of a string sent via the interchange protocol the buffer uses 8 bytes per entry to store an offset even when the format code is "u"

LargeString should use 8 bytes per entry, but has a different format code of "U"
```

### Issue Description

see above

### Expected Behavior

u should have 4 byte offsets, U should have 8

### Installed Versions

main

**Comment by MarcoGorelli** [comment]
closed by https://github.com/pandas-dev/pandas/pull/56772
