### ISSUE TITLE
ENH/API: clarify groupby by to handle columns/index names

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#5677]
Referenced briefly in the OP at #3275

``` python
In [11]: idx = pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('a', 3), ('b', 1), ('b', 2), ('b', 3)])

In [12]: idx.names = ['outer', 'inner']

In [13]: df = pd.DataFrame({"A": np.arange(6), 'B': ['one', 'one', 'two', 'two', 'one', 'one']}, index=idx)
```

So the idea is to be able to call

``` python
df.groupby('B', level='inner')
```

instead of

``` python
In [15]: df.reset_index().groupby(['B', 'inner']).mean()
Out[15]: 
             A
B   inner     
one 1      0.0
    2      2.5
    3      5.0
two 1      3.0
    3      2.0

[5 rows x 1 columns]
```

Currently this raises `TypeError: 'numpy.ndarray' object is not callable`.  Mostly just syntactic sugar, but I've been having to do a lot of this lately and all the `reset_index`es are getting annoying. Thoughts?

**Comment by jmmease** [comment]
@jreback @TomAugspurger I'm interested in implementing this.  Has anything changed since this discussion that I should be aware of?  I'll likely use Tom's old PR (#7033) as a starting point.

**Comment by jreback** [comment]
http://pandas.pydata.org/pandas-docs/stable/groupby.html#grouping-with-a-grouper-specification implements this

though you could make sugar for non colliding names which could be a name of an index / multi index

**Comment by jmmease** [comment]
Ok, thanks.  So am I following that the way to accomplish the original example from this issue, without resetting the index, is the following?
```python
In [75]: df.groupby(['B', pd.Grouper(level='inner')]).mean()
Out [75]: 
             A
B   inner     
one 1      0.0
    2      2.5
    3      5.0
two 1      3.0
    3      2.0
```

Should this approach also work when the frame has a singe named index? e.g.
```python
In [76]: df2 = df.reset_index('outer')

In [77]: df2
Out [77]: 
      outer  A    B
inner              
1         a  0  one
2         a  1  one
3         a  2  two
1         b  3  two
2         b  4  one
3         b  5  one

In [79]: df2.groupby(['B', pd.Grouper(level='inner')]).mean()              
...
AttributeError: 'Int64Index' object has no attribute 'labels'
```

In this case I'm getting an Attribute Error (I'm on pandas 0.18.1 and happy to file a bug if this is one).

I would be interested in adding sugar in order to support
```python
df.groupby(['B', 'inner']).mean()
```
and
```python
df2.groupby(['B', 'inner']).mean()
```
where column names take precedence as discussed above.

**Comment by jorisvandenbossche** [comment]
> Should this approach also work when the frame has a singe named index?

Yes, I think it should work. For example, it works when only specifying the index in this way:

```
In [40]: df2.groupby(level='inner').mean()
Out[40]: 
         A
inner     
1      1.5
2      2.5
3      3.5

In [42]: df2.groupby(pd.Grouper(level='inner')).mean()
Out[42]: 
         A
inner     
1      1.5
2      2.5
3      3.5

```

So using it in a list to group by multiple columns/indexes should also work. Do you want to open a separate bug report for this?

**Comment by jmmease** [comment]
Yes, I'll open a separate bug report for this issue in a few hours.
