### ISSUE TITLE
ENH: Accept pd.NA as a float

### ISSUE THREAD

**Issue by mdruiter** [pandas-dev/pandas#56797]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

In `float[pyarrow]` data, missings values are `pd.NA`. I can easily convert these frames to floats:

`pd.Series([pd.NA], dtype='float[pyarrow]').astype('float')`

> 0   NaN
> dtype: float64

But in the `pd.Series` constructor, I cannot use `pd.NA`s:

`pd.Series([pd.NA], dtype='float')`

> TypeError: float() argument must be a string or a real number, not 'NAType'

Is this by design?

### Feature Description

It would be so much more convenient if `pd.NA` would 'just' be recognized as a `np.nan` in float context...

### Alternative Solutions

Using `.astype('float')` is a workaround but makes code less generic.

### Additional Context

I searched for issues like this or a design statement, but could not find anything about this specific thing, which surprised me as it feels like a common inconvenience.

**Comment by rhshadrach** [comment]
> It would be so much more convenient if `pd.NA` would 'just' be recognized as a `np.nan` in float context...

This is the essentially the direction pandas plans to head in.

cc @phofl @jorisvandenbossche - I think this issue is likely duplicative of others we have on np.nan, pd.NA. Good to close?

**Comment by phofl** [comment]
Yes
