### ISSUE TITLE
DOC: Imprecision in the type description of `pd.concat` parameter

### ISSUE THREAD

**Issue by kodimatrix** [pandas-dev/pandas#56845]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.concat.html

### Documentation problem

The `pd.concat()` function has a parameter `obj` with the typing hint:: `Iterable` (and other). It is possible to call this function with a generator, for example.  However, the documentation refers to it as "a _sequence_...".  According to the glossary (and `collections.abs` module, respectively), this is a small imprecision.

https://docs.python.org/3/glossary.html#term-iterable
https://docs.python.org/3/glossary.html#term-sequence

### Suggested fix for documentation

Replace "sequence" with "iterable".

**Comment by rhshadrach** [comment]
We convert any non-mapping argument to a list

https://github.com/pandas-dev/pandas/blob/78c79b9a143e12c696b4c92eb1d70e4eb6bc3686/pandas/core/reshape/concat.py#L502

I'd be okay with refining the documentation here but want to make sure we're okay explicitly supporting generators. cc @mroeschke @phofl

**Comment by mroeschke** [comment]
Yeah generally any constructor should accept generators.

**Comment by kodimatrix** [comment]
take
