### ISSUE TITLE
BUG: GroupBy.nth() loses the (multi)indices

### ISSUE THREAD

**Issue by roboguy222** [pandas-dev/pandas#56852]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

a={"a":[15,12,13,15, 12, 12],"b":[15,12,13,15, 12, 12],"c":[12,21,23,22,56,11]}
df=pd.DataFrame(a)

print(df.groupby(['a','b'])['c'].nth(0))
print(df.groupby(['a','b'])['c'].first())
```

### Issue Description

In the above example, using `nth()` loses the associated indices.  This is unlike using `first()`, which keeps the indices.

For `nth()`, we get the following output:
```
0    12
1    21
2    23
Name: c, dtype: int64
```

### Expected Behavior

The output should keep the indices, similar to `first()`:
```
a   b 
12  12    21
13  13    23
15  15    12
Name: c, dtype: int64
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : e86ed377639948c64c429059127bcf5b359ab6be
python              : 3.9.18.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 23.0.0
Version             : Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
machine             : arm64
processor           : arm
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : None.UTF-8

pandas              : 2.1.1
numpy               : 1.26.1
</details>

**Comment by rhshadrach** [comment]
Thanks for the report. This was purposefully changed in pandas 2.0.0. See https://pandas.pydata.org/pandas-docs/dev/whatsnew/v2.0.0.html#dataframegroupby-nth-and-seriesgroupby-nth-now-behave-as-filtrations
