### ISSUE TITLE
BUG: Strange behavior with read_csv when index_col is set

### ISSUE THREAD

**Issue by Jashanpreet2** [pandas-dev/pandas#56882]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
sample = pd.read_csv('file2.txt', names=['first_column','second_column','third_column'], header=0, index_col=2)
print(sample)



file2.txt
First Name,Family Name,Age
Anna,Smith,1
Bob,Jones,2
Maria,Williams,3
Jack,Brown,4
```

### Issue Description

The problem occurs when you set a custom column as index in a DataFrame but provide the same number of arguments to the names keyword as the total columns in the file that is read.
Prints the the column name that was assigned to the third column in an awkward position:
![image](https://github.com/pandas-dev/pandas/assets/128256855/1c8b6b11-fa3d-4f41-94e5-b4a72d1ccf6b)

(Apologies if there is any problems with this issue or if the "bug" is intentional, this is my first issue)

### Expected Behavior

Perhaps throw an error since the column is being used for indexing so there is no need for a column name? Or maybe do show it as the column name but format it better.

### Installed Versions

INSTALLED VERSIONS
------------------
commit              : a671b5a8bf5dd13fb19f0e88edc679bc9e15c673
python              : 3.9.13.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.22621
machine             : AMD64
processor           : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : English_United States.1252

pandas              : 2.1.4
numpy               : 1.26.3
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.2.0
pip                 : 23.3.2
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : None
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.4
qtpy                : None
pyqt5               : None

**Comment by rhshadrach** [comment]
Thanks for the report. @Jashanpreet2 - can you shorten the title? It should be a concise summary of the issue - try to aim for less than 90 characters.

**Comment by Jashanpreet2** [comment]
> Thanks for the report. @Jashanpreet2 - can you shorten the title? It should be a concise summary of the issue - try to aim for less than 90 characters.

Hello, thank you for the correction. I have edited it. I hope it is okay now.
