### ISSUE TITLE
BUG: Can't get hdf5 data exrport from .NET framework

### ISSUE THREAD

**Issue by chuongmep** [pandas-dev/pandas#56908]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

https://github.com/Apollo3zehn/PureHDF/issues/53

### Issue Description

When I'm try read file export from .NET, it show nothing : 

```py
import numpy as np
import pandas as pd
#%pip install tables -U
import warnings
import os
import time
from tables import NaturalNameWarning
warnings.filterwarnings('ignore', category=NaturalNameWarning)
filePath =r"file.h5"
store = pd.HDFStore(filePath)
store.open()
group  = store.groups()
group
```

### Expected Behavior

It can be return group name `my-group`

### Installed Versions

pandas                         2.1.1

**Comment by rhshadrach** [comment]
As mentioned in https://github.com/Apollo3zehn/PureHDF/issues/53, it sounds like you're expecting pandas to read a general hdf file, but pandas requires a particular schema. I believe it's only intended to support HDF files that were created via pandas.

**Comment by chuongmep** [comment]
Hi @rhshadrach , it make anoying because can't read general hdf format. I hope team should consider support because data not oonly export by pandas.

**Comment by phofl** [comment]
-1 on putting any effort in here to increase complexity, hdf is on the way out anyway

**Comment by chuongmep** [comment]
> -1 on putting any effort in here to increase complexity, hdf is on the way out anyway

your mean is libary, can I know detail what you are saying?

**Comment by phofl** [comment]
parquet is widely more popular these days and the modern alternativ

**Comment by chuongmep** [comment]
> parquet is widely more popular these days and the modern alternativ

But we can't keep mutiple dataframe in one file
