### ISSUE TITLE
DOC: Clarify `df.describe()` behavior with Timestamp columns

### ISSUE THREAD

**Issue by sfc-gh-joshi** [pandas-dev/pandas#56918]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html

### Documentation problem

The Notes section for `describe` states the following (emphasis mine):
> For object data (e.g. strings or timestamps), the result’s index will include `count`, `unique`, `top`, and `freq`. The `top` is the most common value. The `freq` is the most common value’s frequency. **Timestamps also include the `first` and `last` items.**

Since pandas 2.0 began treating Timestamps as numeric data, as far as I can tell, calling `describe` on a Series/DF with Timestamp data no longer yields the `first` or `last` rows. In fact, the example included in the documentation also has this behavior:
```python
>>> s = pd.Series([
...     np.datetime64("2000-01-01"),
...     np.datetime64("2010-01-01"),
...     np.datetime64("2010-01-01")
... ])
>>> s.describe()
count                      3
mean     2006-09-01 08:00:00
min      2000-01-01 00:00:00
25%      2004-12-31 12:00:00
50%      2010-01-01 00:00:00
75%      2010-01-01 00:00:00
max      2010-01-01 00:00:00
dtype: object
```

### Suggested fix for documentation

Assuming this behavior is intended: remove mention of the `first` and `last` columns, and of timestamps as object data.
> For object data (such as strings), the result’s index will include `count`, `unique`, `top`, and `freq`. The `top` is the most common value. The `freq` is the most common value’s frequency.

**Comment by rhshadrach** [comment]
In `pandas.core.methods.describe` there is the function `describe_timestamp_as_categorical_1d` that as far as I can tell isn't used anywhere. I'd guess that it went unused due to some refactors, but haven't checked.

Are `first` and `last` the same as `min`, `max`, or more like `.iloc[0]` and `.iloc[-1]`? In the former case, we can just update the documentation. In the latter case, I also think maybe we just update the documentation as well.

**Comment by rhshadrach** [comment]
It appears to me that `first` and `last` would give the same values as `min` and `max`:

https://github.com/pandas-dev/pandas/blob/9e0b6556b77b554f43067d06057dd05c6e8b8dc4/pandas/core/methods/describe.py#L322-L323

**Comment by alpakpinar** [comment]
take
