### ISSUE TITLE
ENH: Allow users to disable PerformanceWarning

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#56920]
Part of the way toward #55385. Even if we decide not to implement #55385 (i.e. performance warnings are disabled by default), I think this is a good option for users to have.

I propose adding an option, `mode.performance_warnings` defaulting to True, that users could set to False to disable all PerformanceWarnings from being raised. The difference between this and #55385 is just changing the default value.

I opened #56921 to show the implementation.

Would like to get feedback on the general idea and happy to bikeshed the option name. Since this is impacts many places, cc @pandas-dev/pandas-core.

**Comment by jorisvandenbossche** [comment]
Such an option sounds good to me!
