### ISSUE TITLE
BUG: to_dict inconsistency

### ISSUE THREAD

**Issue by moghadas76** [pandas-dev/pandas#56932]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df = ....
df.to_dict()
```

### Issue Description

to dict manipulate float values which could not be restored

### Expected Behavior

lossless deserialization 

### Installed Versions

2.1.4

**Comment by rhshadrach** [comment]
Thanks for the report! Could you include a reproducible example? See https://matthewrocklin.com/minimal-bug-reports for more details.

**Comment by mroeschke** [comment]
Closing since there's no reproducible example
