### ISSUE TITLE
QST: Why does it seem like importing pandas spawns a process per logical core of your CPU?

### ISSUE THREAD

**Issue by kszlim** [pandas-dev/pandas#56956]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/77844856/why-does-importing-pandas-seemingly-spawn-a-process-tree-one-per-logical-core

### Question about pandas

```
import pandas as pd
```

This applies on any version of pandas from 1.3.5 to 2.1.4.

**Comment by WillAyd** [comment]
I think the stackoverflow post you have answers this well - this is more of a numpy thing than pandas per se
