### ISSUE TITLE
BUG: Invalid value 'ffill' for dtype UInt32  / fillna("ffill") and .ffill() have different behaviours

### ISSUE THREAD

**Issue by MCRE-BE** [pandas-dev/pandas#56955]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(0, 100, size=(100, 1)), columns=list('y'))
df = df.astype("UInt32")
df.iloc[2:4] = pd.NA

df.fillna("ffill")

>>> raises TypeError: Invalid value 'ffill' for dtype UInt32
```

<details>

```python
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\testpandas\Lib\site-packages\pandas\core\internals\blocks.py", line 2002, in fillna
    new_values = self.values.fillna(
                 ^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\testpandas\Lib\site-packages\pandas\core\arrays\masked.py", line 244, in fillna
    new_values[mask] = value
    ~~~~~~~~~~^^^^^^
  File "C:\ProgramData\miniconda3\envs\testpandas\Lib\site-packages\pandas\core\arrays\masked.py", line 292, in __setitem__
    value = self._validate_setitem_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\testpandas\Lib\site-packages\pandas\core\arrays\masked.py", line 283, in _validate_setitem_value
    raise TypeError(f"Invalid value '{str(value)}' for dtype {self.dtype}")
TypeError: Invalid value 'ffill' for dtype UInt32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\miniconda3\envs\testpandas\Lib\site-packages\pandas\core\generic.py", line 7297, in fillna
    new_data = self._mgr.fillna(
               ^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\testpandas\Lib\site-packages\pandas\core\internals\base.py", line 173, in fillna
    return self.apply_with_block(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\testpandas\Lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\testpandas\Lib\site-packages\pandas\core\internals\blocks.py", line 2008, in fillna
    new_values = self.values.fillna(value=value, method=None, limit=limit)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\testpandas\Lib\site-packages\pandas\core\arrays\masked.py", line 244, in fillna
    new_values[mask] = value
    ~~~~~~~~~~^^^^^^
  File "C:\ProgramData\miniconda3\envs\testpandas\Lib\site-packages\pandas\core\arrays\masked.py", line 292, in __setitem__
    value = self._validate_setitem_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\testpandas\Lib\site-packages\pandas\core\arrays\masked.py", line 283, in _validate_setitem_value
    raise TypeError(f"Invalid value '{str(value)}' for dtype {self.dtype}")
TypeError: Invalid value 'ffill' for dtype UInt32
```
</details>

```python
df.fillna()
>> Fills nan's correctly
```

### Issue Description

I expected the nan's to be fill the same. I checked for : 

- Creates bug : "UInt8", "UInt32",
- No bug : "uint8", "uint32"

### Expected Behavior

Same behaviour for pd.DataFrame.fillna() and pd.DataFrame.ffill()

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a671b5a8bf5dd13fb19f0e88edc679bc9e15c673
python              : 3.11.7.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.19042
machine             : AMD64
processor           : AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : Dutch_Belgium.1252

pandas              : 2.1.4
numpy               : 1.26.3
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 69.0.3
pip                 : 23.3.2
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : None
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.4
qtpy                : None
pyqt5               : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report. The first parameter of `DataFrame.fillna` is `value`; you're looking to use `method`. You should be calling `df.fillna(method="ffill")` instead. Note that this is now deprecated in 2.2 and you should just be using `df.ffill()`.

**Comment by MCRE-BE** [comment]
oeps. Rookie mistake.
My bad
