### ISSUE TITLE
PERF: Execution Time Difference Between Scalar and Single Element Vector Addition in Pandas Series

### ISSUE THREAD

**Issue by Alexia-I** [pandas-dev/pandas#56951]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this issue exists on the main branch of pandas.

### Reproducible Example

Hello, I've encountered a performance difference between the execution time of adding a scalar versus adding a single element vector to a pandas.Series. 

I made a test for it, involving repeatedly adding either a scalar or a single-element pandas.Series to an existing Series object containing a range of integers (0 to 99). Each addition operation is performed one million times, and the total execution time is recorded. The test is repeated six times to ensure consistency in the results.

```
import pandas as pd
import time

series = pd.Series([i for i in range(100)])

scalar_input = 10
single_element_vector_input = pd.Series([10])

for i in range(6):

    start_time = time.time()
    #  scalar add
    for _ in range(1000000):
        series.add(scalar_input)

    scalar_add_time = time.time() - start_time

    start_time = time.time()
    # vector add
    for _ in range(1000000):
        series.add(single_element_vector_input)

    single_element_vector_add_time = time.time() - start_time

    print(f"Time for add() with scalar input: {scalar_add_time} seconds")
    print(f"Time for add() with single element vector input: {single_element_vector_add_time} seconds")
```

Results:

Seems that there is a 4 times perf difference between these equivalent operations.
```
Time for add() with scalar input: 21.000375032424927 seconds
Time for add() with single element vector input: 84.27741193771362 seconds
Time for add() with scalar input: 21.70480990409851 seconds
Time for add() with single element vector input: 82.8789930343628 seconds
Time for add() with scalar input: 21.428874015808105 seconds
Time for add() with single element vector input: 82.07445478439331 seconds
Time for add() with scalar input: 21.0909321308136 seconds
Time for add() with single element vector input: 81.53964805603027 seconds
Time for add() with scalar input: 21.011897087097168 seconds
Time for add() with single element vector input: 81.57252931594849 seconds
Time for add() with scalar input: 21.004963874816895 seconds
Time for add() with single element vector input: 81.47081112861633 seconds
```

### Installed Versions

<details>

------------------
commit                : d4c8d82b52045f49a0bb1d762968918a06886ae9
python                : 3.9.18.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 23.0.0
Version               : Darwin Kernel Version 23.0.0: Thu Aug 17 21:23:05 PDT 2023; root:xnu-10002.1.11~3/RELEASE_ARM64_T6000
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : None.UTF-8

pandas                : 2.2.0rc0
numpy                 : 1.26.0
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 68.0.0
pip                   : 23.3
Cython                : 3.0.5
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.3
IPython               : 8.15.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : 1.3.5
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2023.12.2
gcsfs                 : None
matplotlib            : 3.8.0
numba                 : None
numexpr               : 2.8.7
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2023.3
qtpy                  : None
pyqt5                 : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report. These are not equivalent operations - they do not produce the same result. pandas has to do more work when you supply a Series to ensure the indices are aligned, and align them if not.

**Comment by Alexia-I** [comment]
> Thanks for the report. These are not equivalent operations - they do not produce the same result. pandas has to do more work when you supply a Series to ensure the indices are aligned, and align them if not.

Thank you for your response. However, it's worth noting that a single-element array or list can be treated as a scalar in this case, and the index checking involved seems unnecessary, potentially resulting in significantly longer execution times. 
I think a fourfold time difference is significant in scenarios where this single-element operation needs to be accessed multiple times, and I believe it's worth optimizing.

**Comment by jorisvandenbossche** [comment]
> However, it's worth noting that a single-element array or list can be treated as a scalar in this case, and the index checking involved seems unnecessary

It could, but that is not how pandas is designed: when combining pandas objects (Series or DataFrame) in an operation like addition, the objects are _aligned_ on their labels, see https://pandas.pydata.org/docs/user_guide/dsintro.html#vectorized-operations-and-label-alignment-with-series

If you don't want that alignment, you can use an array instead of a Series (or in this case, a scalar).

**Comment by Alexia-I** [comment]
Thank you for your response. Btw, the result of the following case showed that creating a Series with a scalar value took almost twice as long as creating a Series with a NumPy array containing a single value. Is it also a feature of pandas?
```
import pandas as pd
import numpy as np
import timeit

scalar_value = 10
numpy_array = np.array([10])

print(pd.Series(scalar_value))
print(pd.Series(numpy_array))

scalar_time = timeit.timeit(lambda: pd.Series(scalar_value), number=1000000)
array_time = timeit.timeit(lambda: pd.Series(numpy_array), number=1000000)

print(f"Time for creating Series with scalar value: {scalar_time} seconds")
print(f"Time for creating Series with NumPy array containing a single value: {array_time} seconds")
```

result:
```
0    10
dtype: int64
0    10
dtype: int64
Time for creating Series with scalar value: 11.746772374999978 seconds
Time for creating Series with NumPy array containing a single value: 7.716082375000042 seconds
```

**Comment by jorisvandenbossche** [comment]
That's because under the hood, a Series stores a numpy array. So when passing an array, not much processing needs to be done by pandas, but when passing a scalar, this has to be detected and this scalar has to be converted into an array. So that's just a bit more work that has to be done in that case, explaining why this is a bit slower.

**Comment by Alexia-I** [comment]
Thanks for the clarification. I noticed that a similar issue was reported in the NumPy repository ([link](https://github.com/numpy/numpy/issues/19010#issue-891430566)) and optimizations were made. In this case, it's quite common for inexperienced users to construct a `Series` with a scalar value. Would it be possible to consider adding a user-friendly fast path for scalar creation, similar to what was done in NumPy?

**Comment by jorisvandenbossche** [comment]
> I noticed that a similar issue was reported in the NumPy repository ([link](https://github.com/numpy/numpy/issues/19010#issue-891430566)) and optimizations were made.

That's actually a different case (for a scalar vs tuple as argument denoting the shape of the data to create, not for the data itself). 

It's certainly welcome to profile the construction of a Series from a scalar, and to investigate whether there is some performance wins to be found (but so in general it will always be at least a bit slower compared to creation from data that is already an array, so I can't really expect if there would be much further optimization possible or not)

**Comment by rhshadrach** [comment]
Closing for now. @Alexia-I - if you think there are ways to increase performance, we're happy to have them! Comment any suggestions here and we can reopen.

**Comment by Alexia-I** [comment]
@jorisvandenbossche @rhshadrach Thank you for your response. I'll try to look into it. Since I'm not very familiar with pandas, do you have any suggestions on how to profile this issue?
