### ISSUE TITLE
ENH: Add option to ignore leap days when generating date ranges.

### ISSUE THREAD

**Issue by gbromley** [pandas-dev/pandas#56968]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

By default I remove leap days from datasets when doing an analysis. It would get rid of a lot of boiler plate code to add an option like 'ignore_leap' = True. Currently the date_range function includes leap days so one has to check if a year is a leap year,and remove the leap day every time a date range is generated. Current functionality:

```python
s = pd.date_range('2016-01-01', freq='D', periods = 5*365)
print(s[0])
print(s[-1])
```
```
out: Timestamp('2016-01-01 00:00:00')
out: Timestamp('2020-12-29 00:00:00')
```

### Feature Description

```python

s = pd.date_range('2016-01-01', freq='D', periods = 5*365, ignore_leap=True)
print(s[0])
print(s[-1])
```
```
out: Timestamp('2016-01-01 00:00:00')
out: Timestamp('2020-12-31 00:00:00')
```

### Alternative Solutions

This is currently how I solve this problem:

```python

start_year = 2016
end_year = 2020

s = pd.date_range(start=f'{start_year}-01-01', end=f'{end_year}-12-31', freq='D')

s = s[~((s.month == 2) & (s.day == 29))]
```

**Comment by gbromley** [comment]
I would be interested writing the changes to date_range this if it's agreed that this would make sense to add. I'd be a first time contributor though.

**Comment by AkashZalke** [comment]
Hello @gbromley I also liked the idea and would be interested to contribute to the same , I also tried doing it and it works

**Comment by MarcoGorelli** [comment]
thanks for the request but the workaround on the user's end is very simple here, I don't think another parameter is warranted
