### ISSUE TITLE
ENH: append method

### ISSUE THREAD

**Issue by samaanjafari** [pandas-dev/pandas#56975]
### Feature Type

- [x] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

i'm not exactly sure why dataframe.append method is not available anymore and i was using concat instead till today i figured out we can use _append that do the same as append so why u guys just not changing it back to it's original one and another issue is why u guys remove something from library just keep it and in run time tell user a pop up that is deprecated and use this as alternative.

### Feature Description

just plz keep it simple change _append to append and don't remove anything from pandas as new version released or u can just give us a pop up massage that its alternative so wouldn't waste my time to roam around browser to find solution.

### Alternative Solutions

just plz keep it simple change _append to append and don't remove anything from pandas as new version released or u can just give us a pop up massage that its alternative so wouldn't waste my time to roam around browser to find solution.

**Comment by vishwaraj14** [comment]
Append was good method for use, hope so they will bring it back
