### ISSUE TITLE
data loss in read_csv

### ISSUE THREAD

**Issue by gtakacs** [pandas-dev/pandas#5697]
The read_csv function gives strange results for certain input files
(pandas version: 0.12.0, Python version: 3.3.2, OS: Linux):

import io, pandas
f = io.StringIO("x\n\n1111111111111111111")
df = pandas.read_csv(f)
print(int(df.x[1])) # 1111111111111111168

We have data loss due to rounding! The correct behavior in my opinion would be to treat the column as string, if np.float64 is not enough to represent it exactly.

**Comment by TomAugspurger** [comment]
Seems to have been fixed somewhere along the way

```python
In [51]: f = io.StringIO("x\n\n1111111111111111111")
    ...: df = pandas.read_csv(f)
    ...:

In [52]: print(int(df.iloc[0, 0]))
1111111111111111111
```
