### ISSUE TITLE
DOC:  API doc missing for DataFrame.to_numpy()

### ISSUE THREAD

**Issue by dstansby** [pandas-dev/pandas#57016]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html

### Documentation problem

`DataFrame.to_numpy` API docs are missing on version 2.2 of the docs. In version 2.1 it's here: https://pandas.pydata.org/pandas-docs/version/2.1/reference/api/pandas.DataFrame.to_numpy.html, but on version 2.2 https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html doesn't have a link to a page documenting `to_numpy()`.

### Suggested fix for documentation

Add link on https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html to `to_numpy()` API docs.

**Comment by luke396** [comment]
take
