### ISSUE TITLE
BUILD: I install pandas on my google cloud shell but even when its already installed I can't import pandas as it give following error:"DeprecationWarning:  Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0), (to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries) but was not found to be installed on your system. If this would cause problems for you, please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466            import pandas as pd"

### ISSUE THREAD

**Issue by humzawaheed** [pandas-dev/pandas#57022]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Linux-6.1.58+-x86_64-with-glibc2.31

### Installation Method

pip install

### pandas Version

2.2.0

### Python Version

3.9.2

### Installation Logs

<details>

DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd

</details>

**Comment by mroeschke** [comment]
Thanks for the report, but this is just a warning and not an exception that should prevent your program from running. If is actually causing your program to crash please show the exception

**Comment by Sharip570** [comment]
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.

**Comment by mroeschke** [comment]
Closing as this is just a warning
