### ISSUE TITLE
This is an issue to collect feedback on the decision to make PyArrow a required dependency and to infer strings as PyArrow backed strings by default.QST: 

### ISSUE THREAD

**Issue by sonwaneajay228** [pandas-dev/pandas#57036]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

n

### Question about pandas

na

**Comment by sonwaneajay228** [comment]
nothing

**Comment by mroeschke** [comment]
Closing in favor of https://github.com/pandas-dev/pandas/issues/54466
