### ISSUE TITLE
BUG: TypeError for dataframe arithmetic combining empty and mixed type column indexes

### ISSUE THREAD

**Issue by doraut** [pandas-dev/pandas#57048]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd 

first = pd.DataFrame()
second = pd.DataFrame(columns=["test"])
third = pd.DataFrame(columns=["foo", ("bar", "baz")])

first + second  # works
second + third  # works
first + third   # raises TypeError: '<' not supported between instances of 'tuple' and 'str'
```

### Issue Description

Calling any arithmetic function with two DataFrames as input where one has an empty column index and the other one has a column index which is not sortable throws a TypeError. Error seems to come from the `argsort` call introduced [here](https://github.com/pandas-dev/pandas/commit/5b6723cdb8cbf591761756f5c6f181df820e780a#diff-c34a28314fc8cb12f0d2aa710f1c15f06cdfe3e48f03e658f01f99a43d4f5d09R4598)

### Expected Behavior

The expected output for the example would be:
```python
Empty DataFrame
Columns: [foo, (bar, baz)]
Index: []
```
This was the behavior in version 2.1.4.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : fd3f57170aa1af588ba877e8e28c158a20a4886d
python                : 3.11.0.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.7.0-arch3-1
Version               : #1 SMP PREEMPT_DYNAMIC Sat, 13 Jan 2024 14:37:14 +0000
machine               : x86_64
processor             : 
byteorder             : little
LC_ALL                : en_US.UTF-8
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.0
numpy                 : 1.26.3
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 69.0.3
pip                   : 23.2.1
Cython                : None
pytest                : 7.4.4
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.2
IPython               : 8.16.1
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : 3.8.2
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.2
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2023.4
qtpy                  : None
pyqt5                 : None

</details>

**Comment by VISWESWARAN1998** [comment]
In indexes/base.py:

I see argsort is performed in **two conditions**. 

### Condition 1:
It checks if the other Index is empty then it sorts the previous / self index

**example:**
third (self) + first (other)
self is sorted here using argsort

### Condition 2:
It checks if the self Index is empty then it sorts the other index

**example:**
first (self) + third (other)
other is sorted here using argsort

The sorting is not performed on other cases. 

I tried commenting out the specific sorting code for **1st condition**

```python
if len(self) == 0:
    if how in ("right", "outer"):
        if sort and not other.is_monotonic_increasing:
            # ridx = other.argsort()
            # join_index = other.take(ridx)
            ridx = None
            join_index = other._view()
        else:
            ridx = None
            join_index = other._view()
        lidx = np.broadcast_to(np.intp(-1), len(join_index))
        return join_index, lidx, ridx
    elif how in ("left", "inner", "cross"):
        join_index = self._view()
        ridx = np.array([], dtype=np.intp)
        return join_index, None, ridx
```

And I was able to get the expected results mentioned in the issue!

There is no information on code mentioning why sorting is done on these two conditions. Numpy Argsort (which pandas uses under the hood) however doesn't suite sorting objects to my knowledge. My initial thoughts was to wrap this around an exception handler but without knowing the specific use-case of this implementation I may break something. I am fairly a new contributor myself so I am willing to learn from someone who is very experienced in this repo!

**Comment by rhshadrach** [comment]
git bisect result:

```
Author: Luke Manley
Date:   Mon Dec 11 12:37:56 2023 -0500

    BUG: DataFrame.join with left or right empty not respecting sort=True (#56443)
```

cc @lukemanley
