### ISSUE TITLE
BUG: Inconsistent `to_datetime` behaviour

### ISSUE THREAD

**Issue by abhijeetbodas2001** [pandas-dev/pandas#57051]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> import pandas as pd

>>> pd.to_datetime("1704660000", unit="s", origin="unix")
<stdin>:1: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
Timestamp('2024-01-07 20:39:28')

>>> pd.to_datetime(1704660000, unit="s", origin="unix")
Timestamp('2024-01-07 20:40:00')
```

### Issue Description

Incorrect datetime object generated when unix timestamp is passed as string.

### Expected Behavior

The timestamp string should be converted to the correct datetime regarless of the `dtype` of the input (`string` or `int`). Or, raise error if `string` inputs are illegal.

The current depracation warning seems to imply that the behaviour is working as expected now, but won't be available in future versions.

### Installed Versions

```
[~] $ pip list | rg "pandas|numpy"
numpy                             1.26.1
pandas                            2.2.0
pandas-stubs                      2.1.4.231218
```

**Comment by MarcoGorelli** [comment]
> The current depracation warning seems to imply that the behaviour is working as expected now, but won't be available in future versions.

indeed, it'll error in the future

not sure what you're asking, sorry - could you clarify please? what's your expected output?

**Comment by abhijeetbodas2001** [comment]
Thanks for your response.

> not sure what you're asking, sorry - could you clarify please? what's your expected output?

`to_datetime` currently gives different outputs when the same unix timestamp is passed as a `string` vs as an `int`. Question is, should it not return the same `datetime` object in both the cases?

**Comment by MarcoGorelli** [comment]
thanks - sorry, I'd missed the minutes/seconds difference

I agree, but as the first one's deprecated this probably isn't worth fixing

**Comment by abhijeetbodas2001** [comment]
I had hoped a fix could have made it to the next minor release (ie, before it is removed), but I can understand if it does not make the cut. Anyways, thanks!

**Comment by QuLogic** [comment]
Do note that this was working correctly in 1.5.3; so while it is deprecated, this is a regression introduced in Pandas 2.0.0.
