### ISSUE TITLE
BUG:  Pandas >= 2.2.0and SQLALCHEMY does not work together

### ISSUE THREAD

**Issue by jkorsvik** [pandas-dev/pandas#57053]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
Python==3.10.12
pandas==2.2.0
SQLAlchemy==1.4.51
denodo-sqlalchemy==20230818

def sqlalch():
   connection_string = f"denodo://{username}:{urllib.parse.quote(password)}@{host}:{port}/{database}"
   denodo_engine = db.create_engine(connection_string, **kwargs)
   connection = denodo_engine.connect()
   return connection
conn = sqlalch()
pd.read_sql(query, conn)
```

### Issue Description

produces error:
2024-01-24T11:57:31     cursor = self.execute(sql, params)
2024-01-24T11:57:31   File "/usr/local/lib/python3.10/site-packages/pandas/io/sql.py", line 2673, in execute
2024-01-24T11:57:31     cur = self.con.cursor()
2024-01-24T11:57:31 AttributeError: 'Connection' object has no attribute 'cursor'

### Expected Behavior

Using odbc connection or pandas 2.0 works.
Using the denodo connection directly works.
might be related to: https://github.com/pandas-dev/pandas/issues/51015

### Installed Versions

<details>

commit                : fd3f57170aa1af588ba877e8e28c158a20a4886d
python                : 3.10.12.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 4.14.330-250.540.amzn2.x86_64
Version               : #1 SMP Tue Nov 21 09:57:48 UTC 2023
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : C.UTF-8
LANG                  : C.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.0
numpy                 : 1.25.2
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 59.6.0
pip                   : 23.3.2
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : 2.9.9
jinja2                : 3.1.3
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2023.9.1
gcsfs                 : None
matplotlib            : 3.7.3
numba                 : 0.58.1
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.2
pandas_gbq            : None
pyarrow               : 15.0.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : 2023.9.1
scipy                 : 1.11.4
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2023.4
qtpy                  : None
pyqt5                 : None

</details>

**Comment by lithomas1** [comment]
Let's track this in #57049

**Comment by VassilisVassiliadis** [comment]
I think this issue is related to https://github.com/pandas-dev/pandas/issues/43585

**Comment by juice-zohaa-qamar** [comment]
I was also facing the issue with to_sql, downgraded pandas to 1.5.3 and it was resolved. Really need to have this fixed in the latest release of pandas.

**Comment by ZenithClown** [comment]
<div align = "justify">

I ditched the traditional `pandas.to_sql(...)` method to achieve this, don't know if this is the recommended solution, but for PostgreSQL (using PsycoPG) I was able to do the same, check sharkutilities/forexrates@567dab9f04f749ad5105bb4760789b8d915b569b for full commit details.

```python
import pandas as pd
import sqlalchemy as sa

engine = sa.create_engine("postgresql+psycopg://...")

with engine.connect() as connection:
    metadata = sa.Table("table", sa.MetaData()), autoload_with = connection)
    connection.execute(
        metadata.insert(), dataframe.to_dict(orient = "records"))
    )
    connection.commit()
```
