### ISSUE TITLE
BUG: `is_datetime64_any_dtype` returns `False` for Series with pyarrow dtype

### ISSUE THREAD

**Issue by jmoralez** [pandas-dev/pandas#57055]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
s = pd.to_datetime(['2000-01-01']).astype('timestamp[ns][pyarrow]')
pd.api.types.is_datetime64_any_dtype(s.dtype)
# True
pd.api.types.is_datetime64_any_dtype(s)
# False
```

### Issue Description

This check
https://github.com/pandas-dev/pandas/blob/622f31c9c455c64751b03b18e357b8f7bd1af0fd/pandas/core/dtypes/common.py#L882-L884
Only enters if we provide a dtype, not array-like. I believe it should be similar to the one for ints
https://github.com/pandas-dev/pandas/blob/622f31c9c455c64751b03b18e357b8f7bd1af0fd/pandas/core/dtypes/common.py#L668-L672
I'd be happy to give it a go.

### Expected Behavior

The example should return `True` when passing both a Series and a dtype.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : ba1cccd19da778f0c3a7d6a885685da16a072870
python              : 3.11.5.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 5.15.0-91-generic
Version             : #101~20.04.1-Ubuntu SMP Thu Nov 16 14:22:28 UTC 2023
machine             : x86_64
processor           : x86_64
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.0
numpy               : 1.24.4
pytz                : 2023.3
dateutil            : 2.8.2
setuptools          : 68.1.2
pip                 : 23.2.1
Cython              : 3.0.2
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.14.0
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.7.2
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : 13.0.0
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.2
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report, confirmed on main. PRs to fix are welcome!

> This check
> ... 
> Only enters if we provide a dtype, not array-like. I believe it should be similar to the one for ints

The check you highlighted is a fastpath for dtypes, and I'm guessing we should leave it as such. The line to fix would be below:

https://github.com/pandas-dev/pandas/blob/622f31c9c455c64751b03b18e357b8f7bd1af0fd/pandas/core/dtypes/common.py#L893
