### ISSUE TITLE
DEP: Deprecate date_format="epoch" in to_json

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#57063]
### Feature Type

- [ ] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [X] Removing existing functionality in pandas

### Problem Description

While `date_format="epoch"` made sense when we exclusively handled ns-precision timestamps since the epoch, it has started to lose its meaning as we support other precisions. 

If you try to roundtrip JSON produced with this argument you just have to guess what the precision is

### Feature Description

See above

### Alternative Solutions

See above

**Comment by Aloqeely** [comment]
So after this change, `to_json` will only support the iso date format? Not sure how I feel about this, but I'm open to working on it as long as nobody's opposed

**Comment by WillAyd** [comment]
@Aloqeely that is correct
