### ISSUE TITLE
DOC: `DataFrame.any()` and `DataFrame.all()` documentation specifies the wrong return types

### ISSUE THREAD

**Issue by caneff** [pandas-dev/pandas#57088]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.any.html
https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.all.html

### Documentation problem

The documentation specifies that the return type is either a DataFrame or Series, but the [code](https://github.com/pandas-dev/pandas/blob/441f65df5c6dea850e6334ab770528184dfb0d33/pandas/core/frame.py#L11576) specifies a Series or bool.

`Series` or `bool` is correct, and the `level` argument mentioned in the code no longer exists.  

### Suggested fix for documentation

Returns:
DataFrame or scalar
If axis=None, then a scalar boolean is returned. Otherwise a `Series` is returned with index matching the `index` argument.

**Comment by rhshadrach** [comment]
Thanks for the report, agreed - cleaning this up would be most welcome!

**Comment by StephenLHChan** [comment]
take

**Comment by sammig7** [comment]
take

**Comment by sejalgolani2801** [comment]
Hey, I'm new to open source but my interests lie in ML. Can I work on this issue?

**Comment by mohmmadAyesh** [comment]
Hi is Can I Contribute to this issue please

**Comment by gboeker** [comment]
take

**Comment by pakshaljain05** [comment]
take

**Comment by lamprinikourou** [comment]
Hello! Can I contribute to this issue?
