### ISSUE TITLE
Community slack link broken

### ISSUE THREAD

**Issue by shriyakalakata** [pandas-dev/pandas#57099]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/development/community.html#community-slack

### Documentation problem

The link for the community Slack is no longer active.

### Suggested fix for documentation

Replace with the updated link.

**Comment by rhshadrach** [comment]
The link seems to work for me: it opens up the slack app to the pandas channel. When you say "no longer active", can you detail exactly what you get?

**Comment by jrmylow** [comment]
@rhshadrach you would need to use this in another browser/when logged out from slack. The message received is as per below:
![image](https://github.com/pandas-dev/pandas/assets/33999325/a9182fd3-f689-44f7-b723-5d56295a1ff3)

**Comment by rhshadrach** [comment]
Thanks @jrmylow - I was able to generate a new link. This should never expire:

https://join.slack.com/t/pandas-dev-community/shared_invite/zt-2blg6u9k3-K6_XvMRDZWeH7Id274UeIg

PR to update the link is welcome!

**Comment by jrmylow** [comment]
Take
