### ISSUE TITLE
DOC: `Series.interpolate` and `DataFrame.Interpolate` refer to methods that are no longer there.

### ISSUE THREAD

**Issue by caneff** [pandas-dev/pandas#57092]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.Series.interpolate.html
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.interpolate.html

### Documentation problem

There is documentation under the limit_direction argument that refers to 'backfill' 'pad' 'bfill' and 'ffill' methods, but those are not on the list of supported methods.

Also there is no mention of how someone would do something like `bfill` or `ffill` if they look up the interpolate doc instead.

### Suggested fix for documentation

Get rid of all parts that reference `bfill` `ffill` `pad` `backfill` as allowable methods. 

Consider adding `bfill` and `ffill` to the "See also" section if people have come to interpolate still looking for that.

**Comment by rhshadrach** [comment]
Thanks for the report- agree on all counts, PRs welcome!

**Comment by shriyakalakata** [comment]
take
