### ISSUE TITLE
BUILD: Installing Pandas with Poetry

### ISSUE THREAD

**Issue by gerardpc** [pandas-dev/pandas#57106]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Linux-5.19.0-46-generic-x86_64-with-glibc2.36

### Installation Method

Other

### pandas Version

2.2

### Python Version

3.11.1

### Installation Logs

I'm using poetry to install pandas, with `poetry add pandas`.
As of version 2.2, I'm getting the warning

/home/gerardpc/repositories/ie/news_project/news_project/main.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

`poetry add pandas[pyarrow]` specifies `pandas = {extras = ["pyarrow"], version = "^2.2.0"}` in the .toml file, but does not appear to install pyarrow. 

Is there anything I'm doing wrong to make pandas install and work with pyarrow?

**Comment by mroeschke** [comment]
`["pyarrow"]` is not a valid extra (yet) for pandas. You'll need to install pyarrow separately
