### ISSUE TITLE
BUILD: i am not able to install pandas or any other libraries

### ISSUE THREAD

**Issue by Tejaswini-pericharla** [pandas-dev/pandas#57110]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

import 

### Installation Method

pip install

### pandas Version

3.0

### Python Version

3.12

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by mroeschke** [comment]
pandas 3 is not out yet. You can find available versions on pypi here https://pypi.org/project/pandas/#history
