### ISSUE TITLE
BUG: Regression from 2.1 -> 2.2: df.to_dict produces int instead of timestamp

### ISSUE THREAD

**Issue by behrenhoff** [pandas-dev/pandas#57125]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame(data={"a": [pd.Timestamp(100)]})
d = df.to_dict(orient="list")

assert d["a"] == [pd.Timestamp(100)]
```

### Issue Description

The assertion fails in pandas 2.2, while it works in pandas 2.1.x

Instead, pandas 2.2 returns [100], i.e. `int` instead of `Timestamp`.

### Expected Behavior

No dtype change.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : e86ed377639948c64c429059127bcf5b359ab6be
python              : 3.10.12.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 6.5.0-15-generic
Version             : #15~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 12 18:54:30 UTC 2
machine             : x86_64
processor           : x86_64
byteorder           : little
LC_ALL              : None
LANG                : de_DE.UTF-8
LOCALE              : de_DE.UTF-8

pandas              : 2.1.1
numpy               : 1.26.1
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 59.6.0
pip                 : 23.3.1
Cython              : 3.0.4
pytest              : 7.4.3
hypothesis          : None
sphinx              : 7.2.6
blosc               : None
feather             : None
xlsxwriter          : 3.1.9
lxml.etree          : 4.9.3
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.16.1
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.8.0
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : 3.1.0
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.3
sqlalchemy          : 2.0.22
tables              : None
tabulate            : None
xarray              : None
xlrd                : 2.0.1
zstandard           : 0.21.0
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report. Result from a git bisect:

```
commit 18315c5830459535ea8471e66e82fafa4c538e08
Author: taytzehao 
Date:   Sat Sep 2 00:55:05 2023 +0800

    #50990 Increase to_dict('list') performance (#54824)
```

cc @taytzehao

**Comment by behrenhoff** [comment]
:+1: Thanks a lot for the quick fix!
