### ISSUE TITLE
 DeprecationWarning:  Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0), (to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries) but was not found to be installed on your system. If this would cause problems for youBUILD: 

### ISSUE THREAD

**Issue by manoj-datascience** [pandas-dev/pandas#57123]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

import pandas as pd

### Installation Method

pip install

### pandas Version

2.2.0

### Python Version

3.11.5

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by mroeschke** [comment]
If you have issue with this deprecation please report in https://github.com/pandas-dev/pandas/issues/54466

**Comment by magdielgutierrez** [comment]
solve problem

`pip install pyarrow`

**Comment by Mausy5043** [comment]
> solve problem
> 
> `pip install pyarrow`

If this is required by `pandas`, why doesn't `pandas` import it then instead of throwing a warning at the user?
