### ISSUE TITLE
ENH: Add 'dropna' setting to relplot

### ISSUE THREAD

**Issue by JmyL** [pandas-dev/pandas#57128]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Replot extends FacetGrid but it has no dropna option.

### Feature Description

Add new parameter to relplot like below and send it to FacetGrid

```python
def relplot(..., dropna=False):
   ...
```

### Alternative Solutions

I should've called dropna for my dataframe, before calling relplot to ignore rows with nan.

**Comment by rhshadrach** [comment]
Thanks for the request, but I don't believe pandas has a relplot method.

**Comment by JmyL** [comment]
You're right. It's a seaborn method. My mistake.
