### ISSUE TITLE
BUG: Regression in `.to_sql()` from 2.1 -> 2.2

### ISSUE THREAD

**Issue by Ealameda31** [pandas-dev/pandas#57137]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

I am trying to use `.to_sql()` function to insert rows into a postgres database. Before Pandas 2.2, I could pass the engine as follows:

```python
from sqlalchemy import create_engine

engine = create_engine(url_string)

df.to_sql(con=engine)
```

With the latest version of pandas, the same code gives me the following error:

```python
AttributeError: 'Engine' object has no attribute 'cursor'
```

Looking at the docs, it does not seem like the `con` argument has changed, but for some reason it no longer works. Why?

I have tried using `engine.connect()`, `engine.begin()` and other variations all to no avail. I get either the error above or this error:

```python
pandas.errors.DatabaseError: Execution failed on sql '
        SELECT
            name
        FROM
            sqlite_master
        WHERE
            type IN ('table', 'view')
            AND name=?;
        ': relation "sqlite_master" does not exist
LINE 5:             sqlite_master
                    ^
```

Can someone help me troubleshoot?

### Issue Description

Pandas 2.2 not working with `.to_sql()` function despite no major changes in documentation and source code.

### Expected Behavior

Would insert the rows into the data table.

### Installed Versions

<details>
Name: pandas
Version: 2.2.0

Name: SQLAlchemy
Version: 1.4.46

</details>

**Comment by Ealameda31** [comment]
Seems to be an issue with `2.2+`. Just tested on `2.1.4` and worked like a charm.

**Comment by mroeschke** [comment]
The minimum sqlalchemy version for pandas 2.2 is 2.0. I believe if you bump your sqlalchemy version this should be fixed: https://pandas.pydata.org/docs/whatsnew/v2.2.0.html#increased-minimum-versions-for-dependencies

Going to close but let me know if that doesn't solve your problem
