### ISSUE TITLE
PERF: Performance Discrepancy When Selecting Specific Columns in pd.read_csv

### ISSUE THREAD

**Issue by Alexia-I** [pandas-dev/pandas#57149]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this issue exists on the main branch of pandas.

### Reproducible Example

Hey there,

I noticed an interesting performance issue when using pd.read_csv to select specific columns. Specifically, when reading a large DataFrame and a small DataFrame with the same column using usecols, there's a significant performance difference. This difference seems to be related to the overall reading time of the DataFrame.

Here's a summary of what I observed:

Reading a specific column from a large DataFrame (df_needed) takes considerably longer compared to reading the same column from a small DataFrame (df_needed_small). Both DataFrames have the same column structure.
The time it takes to read specific columns appears to be highly correlated with the time it takes to read the entire DataFrame (df_all and df_all_small).
However, when reading specific rows using nrows, this performance issue doesn't seem to occur.

I thought it would be valuable to bring this issue to your attention and discuss potential optimizations or solutions. Your insights would be greatly appreciated!

Thanks for your time and expertise! 

```
import pandas as pd
import time
import numpy as np
import os

# Generate a sample DataFrame
data = {f'col{i}': np.random.rand(10000) for i in range(1, 21)}
data_small = {f'col{i}': np.random.rand(10000) for i in range(1, 3)}
df = pd.DataFrame(data)
df_small = pd.DataFrame(data_small)

# Save the DataFrame to a CSV file
file_path = 'test_01.csv'
df.to_csv(file_path, index=False)
file_path_small = 'test_01_small.csv'
df_small.to_csv(file_path_small, index=False)



%timeit df_all = pd.read_csv(file_path)
%timeit df_all_small = pd.read_csv(file_path_small)

%timeit df_needed = pd.read_csv(file_path, usecols=['col1'])
%timeit df_needed_small = pd.read_csv(file_path_small, usecols=['col1'])

n_rows_to_read = 1
%timeit df_specific_rows = pd.read_csv(file_path, nrows=n_rows_to_read)
%timeit df_specific_rows_small = pd.read_csv(file_path_small, nrows=n_rows_to_read)


17.6 ms ± 1.02 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.99 ms ± 56.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

12.3 ms ± 502 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
1.79 ms ± 128 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

674 µs ± 26.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
550 µs ± 14.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a671b5a8bf5dd13fb19f0e88edc679bc9e15c673
python              : 3.9.18.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 23.0.0
Version             : Darwin Kernel Version 23.0.0: Thu Aug 17 21:23:05 PDT 2023; root:xnu-10002.1.11~3/RELEASE_ARM64_T6000
machine             : arm64
processor           : arm
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : None.UTF-8

pandas              : 2.1.4
numpy               : 1.26.0
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.0.0
pip                 : 23.3
Cython              : 3.0.5
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.15.0
pandas_datareader   : None
bs4                 : 4.12.3
bottleneck          : 1.3.5
dataframe-api-compat: None
fastparquet         : None
fsspec              : 2023.10.0
gcsfs               : None
matplotlib          : 3.8.0
numba               : None
numexpr             : 2.8.7
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : 11.0.0
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.4
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report!

> The time it takes to read specific columns appears to be highly correlated with the time it takes to read the entire DataFrame (df_all and df_all_small).

I don't think one can know without reading the entire file where the values for a specific column will be. The argument for selecting specific columns is for convenience, not performance.

If you want a format that stores data in a columnar way (so you can read specific columns without reading the entire file), I recommend parquet.

**Comment by Alexia-I** [comment]
Thank you for your reply, I will give parquet a try.
