### ISSUE TITLE
BUG: Localizing Timestamp.min changes dtype to object

### ISSUE THREAD

**Issue by robert-schmidtke** [pandas-dev/pandas#57150]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

pd.Series([pd.Timestamp.min.tz_localize("utc")]).dtype
# dtype('O')

# not an issue when adding to it
pd.Series([(pd.Timestamp.min + pd.Timedelta(microseconds=1)).tz_localize("utc")]).dtype
# datetime64[ns, UTC]

# not an issue with pd.Timestamp.max
pd.Series([pd.Timestamp.max.tz_localize("utc")]).dtype
# datetime64[ns, UTC]

# not an issue with now
pd.Series([pd.Timestamp.utcnow()]).dtype
# datetime64[ns, UTC]
```

### Issue Description

When localizing `pd.Timestamp.min`, the `dtype` of a `pd.Series` holding just that value changes to `object`.

In pandas 2.1.4, this is not the case.

```python
import pandas as pd
pd.Series([pd.Timestamp.min.tz_localize("utc")]).dtype
# datetime64[ns, UTC]
```

### Expected Behavior

Keep the `datetime62[ns, UTC]` dtype.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : f538741432edf55c6b9fb5d0d496d2dd1d7c2457
python                : 3.11.7.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 5.15.133.1-microsoft-standard-WSL2
Version               : #1 SMP Thu Oct 5 21:02:42 UTC 2023
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : C.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.0
numpy                 : 1.26.3
pytz                  : 2023.4
dateutil              : 2.8.2
setuptools            : 69.0.3
pip                   : 23.3.2
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 14.0.2
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2023.4
qtpy                  : None
pyqt5                 : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report, confirmed on main. Further investigations and PRs to fix are welcome!

**Comment by robert-schmidtke** [comment]
I did a bisect and looks like this PR introduced that behavior change: https://github.com/pandas-dev/pandas/pull/55151

```
commit e477eee4916ab0a867f2755d008dde9cf006f671
Author: William Ayd <will_ayd@innobi.io>
Date:   Wed Nov 15 13:20:46 2023 -0500

    Remove undefined behavior from npy_datetimestruct_to_datetime (#55151)
```

@WillAyd would you have an idea what could be the cause of this? I have to admit I don't fully grasp the impact of that PR :)

**Comment by quangngd** [comment]
Shorter reproduce code

```py
from pandas import DatetimeIndex

DatetimeIndex([pd.Timestamp.min.tz_localize("utc")])
```

In the above Reproducible Example, the Series constructor eventually try to test for datetime at `pandas/_libs/lib.pyx:maybe_convert_objects` in the same way.

**Comment by WillAyd** [comment]
My guess is some of the algorithms were previously invoking undefined behavior at the very lower bounds and now we are explicitly catching that. Especially since adding a microsecond to the timestamp doesn't cause the problem, my guess is something at the nanosecond precision is overflowing

**Comment by robert-schmidtke** [comment]
I did some basic debugging and I believe the issue is that this overflows: `scaleMicrosecondsToNanoseconds(microseconds, &nanoseconds)` even though the next add of `dts->ps / 1000` would be within the `int64_t` range again.

```c
  if (base == NPY_FR_ns) {
    int64_t nanoseconds;

    // microseconds is -9223372036854776 here, so would scale to -9223372036854776000
    // but INT64_MIN is -9223372036854775808
    PD_CHECK_OVERFLOW(
        scaleMicrosecondsToNanoseconds(microseconds, &nanoseconds));

    // dts->ps is 193000 here, and adding 193 to -9223372036854776000 would be fine:
    // -9223372036854775807
    PD_CHECK_OVERFLOW(
        checked_int64_add(nanoseconds, dts->ps / 1000, &nanoseconds));

    return nanoseconds;
  }
```

**Comment by WillAyd** [comment]
Great find! Happy to accept any PRs you see to solve it
