### ISSUE TITLE
ENH: Remove value dependent dtype behavior for grouped aggregation for masked and pyarrow dtypes 

### ISSUE THREAD

**Issue by rohanjain101** [pandas-dev/pandas#57195]
### Feature Type

- [ ] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [X] Removing existing functionality in pandas

### Problem Description

```
>>> a = pd.DataFrame({"A": pd.Series([True, True], dtype=pd.BooleanDtype()), "B": pd.Series([1,2], dtype="Int8")})
>>> a.groupby("A").sum().dtypes
B    Int8
dtype: object
>>>
```

But if I increase the values in "B" such that the sum can't fit in an Int8:

```
>>> a = pd.DataFrame({"A": pd.Series([True, True], dtype=pd.BooleanDtype()), "B": pd.Series([124,126], dtype="Int8")})
>>> a.groupby("A").sum().dtypes
B    Int64
dtype: object
>>>
```

For the same input type (Int8), sum returns either an Int8 or an Int64 depending on the values in the original series.
I think value dependent type behavior should be avoided, and in this example, sum(Int8) should always return Int64, irrespective of the values in the series. This would have more predictable behavior for downstream consumers of the aggregate column, and also, probably would improve the performance of the aggregate itself, if it had a pre-determined return type.

### Feature Description

All aggregate should have a pre-determined return type for the given input type, and this behavior should not be affected by the values in the column.

### Alternative Solutions

None.

**Comment by phofl** [comment]
I think there is already an issue about this, a little bit older though
