### ISSUE TITLE
BUG: breaking type annotation of `format_percentiles` function in `io/formats/format.py`

### ISSUE THREAD

**Issue by FrostMegaByte** [pandas-dev/pandas#57248]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
Open `io/formats/format.py` file and see that the following:

def format_percentiles(
    percentiles: (np.ndarray | Sequence[float]),
) -> list[str]:
```

### Issue Description

The brackets of `(np.ndarray | Sequence[float])` should be removed as they break the libcst parser and they are unneccesary

### Expected Behavior

Removed brackets

### Installed Versions

<details>

...

</details>

**Comment by rhshadrach** [comment]
Since it's valid Python, it sounds like this should also be reported to libcst.
