### ISSUE TITLE
QST: How to become a Collaborator? 

### ISSUE THREAD

**Issue by MesumRaza** [pandas-dev/pandas#57244]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://

### Question about pandas

I want to contribute to documentation and docstrings for Real world examples

**Comment by phofl** [comment]
See https://pandas.pydata.org/docs/development/contributing.html
