### ISSUE TITLE
DOC: `CategoricalDtype` equality semantics aren't completely described

### ISSUE THREAD

**Issue by VladimirFokow** [pandas-dev/pandas#57259]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/user_guide/categorical.html#equality-semantics

https://github.com/pandas-dev/pandas/blob/main/pandas/core/dtypes/dtypes.py#L407

### Documentation problem

Problematic [statement 1](https://pandas.pydata.org/docs/user_guide/categorical.html#equality-semantics
):

> Two instances of `CategoricalDtype` compare equal whenever they have the same categories and order.

Problematic [statement 2](https://github.com/pandas-dev/pandas/blob/main/pandas/core/dtypes/dtypes.py#L407):

> 5) A CDT with ordered={False, None} is only equal to another CDT with
           ordered={False, None} and identical categories.

Counter-example:

```py
>>> a = pd.Categorical(np.full(2, np.nan, dtype=object))
>>> b = pd.Categorical(np.full(2, np.nan))

>>> a, b
([NaN, NaN]
 Categories (0, object): [],
 [NaN, NaN]
 Categories (0, float64): [])

>>> a.dtype, b.dtype
(CategoricalDtype(categories=[], ordered=False, categories_dtype=object),
 CategoricalDtype(categories=[], ordered=False, categories_dtype=float64))

>>> a.dtype == b.dtype
False
```

As we can see, they both have `ordered=False`, and their `categories` are same.
Following the documentation, they should be equal.

### Suggested fix for documentation

to have accurate and exhaustive descriptions

**Comment by luke396** [comment]
take

**Comment by VladimirFokow** [comment]
thanks @rhshadrach !
I don't think this is a good first issue, because someone with accurate and full conceptual understanding of `Categorical` and `CategoricalDtype` should edit these descriptions

**Comment by Mehnaz02** [comment]
![Capture2](https://github.com/pandas-dev/pandas/assets/140050845/9e0bf589-52bc-4c78-a7eb-2b43b14d4e9f)
#57259

**Comment by VladimirFokow** [comment]
@Mehnaz02 
dtype in `b` in my example is `float64`

**Comment by VladimirFokow** [comment]
I can try to fix it, but definitely much later.. 
and would need a double-check for accuracy.

**Comment by rhshadrach** [comment]
> I don't think this is a good first issue, because someone with an accurate and full conceptual understanding of `Categorical` and `CategoricalDtype` should help edit these descriptions.

I disagree with this assessment. I believe one just needs to modify the documentation to state that the categories must be the same as indexes, and that in particular includes their dtype. Am I missing something?

In addition, all PRs are reviewed, and so any help can be given as part of that review.

**Comment by luke396** [comment]
>  all PRs are reviewed, and so help can be given as part of that review.

As a regular contributor with experience in the pandas community, I've observed that the label 'good first issue' extends beyond mere simplicity in solving a problem. Typically, it's assigned to documentation-related tasks, serving as a helpful starting point for newcomers eager to engage with the community. 

However, this doesn't diminish the significance of documentation enhancements in the community's eyes. Every pull request, regardless of its nature, undergoes review and suggestions. Nevertheless, complex documentation improvements might demand more effort from reviewers, particularly as they often originate from contributors unfamiliar with the pandas community.

> I believe one just needs to modify the documentation to state that the categories must be the equal as indexes, and that in particular includes their dtype.

In issues #57273 and #57281, I believe @VladimirFokow intended to convey that not only this specific aspect of the documentation, but the documentation as a whole, seems somewhat perplexing to him.

**Comment by VladimirFokow** [comment]
thank you so much @luke396 !!

**Comment by eaedk** [comment]
Hey, I hope you're doing well team.
Looking for an interesting issue to contribute, any reco please?

**Comment by VladimirFokow** [comment]
Hello @eaedk !
How about this one?

**Comment by eaedk** [comment]
Hello @VladimirFokow, oh I thought it was solved. 
I would like to, of course I will ask questions for guidance.
