### ISSUE TITLE
DOC: DeprecationWarning:

### ISSUE THREAD

**Issue by goldenage75** [pandas-dev/pandas#57251]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

C:\Users\Lord\AppData\Local\Temp\ipykernel_10296\2035458946.py:1: DeprecationWarning

### Documentation problem

C:\Users\Lord\AppData\Local\Temp\ipykernel_10296\2035458946.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you

### Suggested fix for documentation

DeprecationWarning:

**Comment by simonjayhawkins** [comment]
Thanks @goldenage75 for the report. Please report in #54466. closing as duplicate
