### ISSUE TITLE
DOC: Wrong generalization about slice indexing

### ISSUE THREAD

**Issue by memeplex** [pandas-dev/pandas#57277]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/version/2.0.2/user_guide/indexing.html#slicing-ranges

### Documentation problem

> With Series, the syntax works exactly as with an ndarray, returning a slice of the values and the corresponding labels

And then shows examples of slice indexing `df[i:j]` where `i` and `j` are integers, and all of them behave as `df.iloc[i:j]` (that is, "exactly as with an ndarray").

But there is an exception (which I can't make sense of and fortunately is deprecated):

```
> pd.Series([1, 2, 3], [3., 2., 1.])[:3]

3.0    1
dtype: int64
```

So, when the index is float, integer slices behave loc-like. Please document this exception in a callout because it's dangerous to assume that the iloc-like behavior is general.

BTW, could someone give a rationale for this behavior? Is there a general rule that ends up in this weird situation, like "if index and slice are int -> iloc, if not then if slice is of the type of the index -> loc else if slice is int -> iloc else fail", and then an int slice is taken to be of the type of a float index?

### Suggested fix for documentation

Document this exception in a callout because it's dangerous to assume that the iloc-like behavior is general.

**Comment by memeplex** [comment]
> BTW, could someone give a rationale for this behavior?

I guess the convoluted history that https://github.com/pandas-dev/pandas/issues/49612 tells explains it.

1. Initially there was the intention to make all int-slice indexing label based but the deprecations weren't sufficient and at that point doing so would have broken many things.
2. So it was decided that it was ok if int-slice indexing was consistent per se (always position based) despite being somewhat inconsistent wrt to other types of indexing (s[i:j] iloc-like vs s[i] or s[[i,j]] loc-like).
3. But float indexes were/are an exception for some historical reason (out of curiosity, which one?). So this case was deprecated.

That said, I believe that the documentation should be explicit about this exception until the deprecation is actually enforced.

**Comment by shriyakalakata** [comment]
take

**Comment by memeplex** [comment]
The note added to the documentation is stating just the opposite to the actual behavior:

> When the [Series](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html#pandas.Series) has float indices, slicing will select by position.

In the original PR this is still more evident:

> However, there is an exception to this rule when the Series has float indices. 
> In such cases, integer slices behave more the ``.iloc`` method

As I stated in my report:

> So, when the index is float, integer slices behave loc-like. 

Indeed, it would be great that it behaved iloc-like, consistently with every other [slice] case, but it's the exception that has to be noted.

**Comment by memeplex** [comment]
The entire https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#slicing-ranges section would benefit from some explicit mention to its iloc-like behavior (except for the aforementioned case, of course).

There is the vague reference:

> The most robust and consistent way of slicing ranges along arbitrary axes is described in the [Selection by Position](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#indexing-integer) section detailing the .iloc method.

but it's not obvious from this that [slice] works positionally.
