### ISSUE TITLE
ENH: Series.range() and DF.range() methods

### ISSUE THREAD

**Issue by DarthKitten2130** [pandas-dev/pandas#57299]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I was wondering why pandas never had a range function in its statistics methods. Of course you can use `df.max() - df.min()` or `Series.max() - Series.min()`  to achieve the same effect, but for readability sake I think it would be a nice addition to the API.

### Feature Description

Adding a new method to both Series and DataFrame as shown in this example:

```
import pandas as pd

ser1 = pd.Series([1,2,3,4,5])
df1 = pd.DataFrame({

'x': [1,2,3,4,5],
'y': [10,20,30,40,50]
})

print(ser1.range())
print(df1.range())
```

Output:

```
4

x   4
y   40
```

### Alternative Solutions

You can always use `df.max() - df.min()` or `Series.max() - Series.min()`  to achieve the same effect, however it's not that readable

**Comment by mroeschke** [comment]
Thanks for the request, but we've had similar requests in the past which were rejected since `max - min` is sufficient and not worth adding a separate API for this. I would recommend adding this method locally to your `pandas.DataFrame` if needed so closing
