### ISSUE TITLE
DOC: CoW User Guide - Previous behavior is current

### ISSUE THREAD

**Issue by VladimirFokow** [pandas-dev/pandas#57290]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html#previous-behavior

https://github.com/pandas-dev/pandas/blob/main/doc/source/user_guide/copy_on_write.rst?plain=1#L32-L45

### Documentation problem

[This section](https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html#previous-behavior) is intended to show the previous behavior (`<3.0`), however now it runs with pandas 3.0, and thus doesn't demonstrate its intended point of what would happen PREVIOUSLY.

And also in the second block of code there, there is `pd.options.mode.copy_on_write = True` which would be unnecessary with pandas `3.0` so can be removed, right?

### Suggested fix for documentation

I don't know the correct way to fix it, but such ideas come to mind:

- manually write the output for the old behavior
- use an older pandas version to run that code when building documentation
- set some setting in pandas `>=3.0` that would simulate the old behavior

**Comment by phofl** [comment]
updated, so closing here
