### ISSUE TITLE
BUG: 2.2.0 nunique aggregation with numeric categories produces different results for `s.groupby(s).agg(pd.Series.nunique)` and `s.groupby(s).nunique()`

### ISSUE THREAD

**Issue by tamargrey** [pandas-dev/pandas#57317]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

s = pd.Series(pd.Categorical([0, 1, 2, 0, 1], categories=[0, 1, 2], ordered=True))

via_agg = s.groupby(s).agg(pd.Series.nunique)
direct = s.groupby(s).nunique()

assert str(via_agg.dtype) == 'category'
assert str(direct.dtype) == 'int64'

# My use-case that is now broken - performing another aggregation now raises TypeError: category type does not support sum operations
df = pd.DataFrame({'col1': via_agg, 'col2': ['a', 'b', 'c']})
df.groupby(['col2']).sum()
```

### Issue Description

`s.groupby(s).agg(pd.Series.nunique)` with numeric categories produces different results in pandas 2.2.0 than it did in earlier versions. Specifically, the resulting dtype is now `CategoricalDtype(categories=[0, 1, 2], ordered=True, categories_dtype=int64)` where it previously was just `int64`. 

Other things I've noticed
- The other ways of doing this calculation, `s.groupby(s).nunique()` and `s.groupby(s).unique().apply(len)` still produce `int64` dtypes, which leads me to think that that is the correct dtype here. 
- There are some instances where `int64` dtype still gets used. If `s` is `pd.Series(pd.Categorical([1, 2, 2, 2, 2, 2], categories=[1, 2, 3], ordered=True))`, this problem does not occur.
- If the categories aren't numeric, say `s` is `pd.Series(pd.Categorical(['a', 'b', 'c'], categories=["a", "b", "c"], ordered=True))` we still get the `int64` dtype, so this seems to only be a problem with numeric categories.

I am using `.agg` since I want to make the call to `pd.Series.nunique` along with other aggregation functions at the same time, so I do not currently have a good workaround other than converting these categorical columns to be `int64`. The category dtype is problematic, as I am performing another groupby aggregation on the results, and this is resulting in `TypeError: category type does not support sum operations` errors on the categorical columns which were previously `int64`.

### Expected Behavior

`s.groupby(s).agg(pd.Series.nunique)` should produce a series with the `int64` dtype that is equal to the other ways of performing this calculation. The following should run without problems: 

```python
import pandas as pd

s = pd.Series(pd.Categorical([0, 1, 2, 0, 1], categories=[0, 1, 2], ordered=True))

via_agg = s.groupby(s).agg(pd.Series.nunique)
direct = s.groupby(s).nunique()

pd.testing.assert_series_equal(via_agg, direct)

# My use-case should now work
df = pd.DataFrame({'col1': via_agg, 'col2': ['a', 'b', 'c']})
df.groupby(['col2']).sum()
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : fd3f57170aa1af588ba877e8e28c158a20a4886d
python                : 3.10.13.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 21.6.0
Version               : Darwin Kernel Version 21.6.0: Fri Sep 15 16:17:04 PDT 2023; root:xnu-8020.240.18.703.5~1/RELEASE_ARM64_T6000
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.0
numpy                 : 1.23.5
pytz                  : 2024.1
dateutil              : 2.8.2
setuptools            : 65.5.0
pip                   : 23.0.1
Cython                : None
pytest                : 8.0.0
hypothesis            : None
sphinx                : 5.1.1
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.3
IPython               : 8.4.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.2.0
gcsfs                 : None
matplotlib            : 3.7.2
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 12.0.1
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.12.0
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2023.4
qtpy                  : None
pyqt5                 : None

</details>

**Comment by tamargrey** [comment]
I'm guessing this is more likely coming from of `s.groupby(s).agg` than `pd.Series.nunique`,  because I can reproduce the same results by creating a wrapper function for `s.nunique()` and passing that into the `agg` method: 

```python
s = pd.Series(pd.Categorical([0, 1, 2, 0, 1], categories=[0, 1, 2], ordered=True))

def wrapper(s):
    return s.nunique()

via_agg = s.groupby(s).agg(wrapper)
direct = s.groupby(s).nunique()

assert str(via_agg.dtype) == 'category'
assert str(direct.dtype) == 'int64'

# My use-case that is now broken - performing another aggregation now raises TypeError: category type does not support sum operations
df = pd.DataFrame({'col1': via_agg, 'col2': ['a', 'b', 'c']})
df.groupby(['col2']).sum()

```

**Comment by rhshadrach** [comment]
Thanks for the report. `groupby.agg` with a callable knows nothing about the operation you're performing, and so has to guess at what you want the results to be. After the operation, we check if the values can be stored in the original dtype and covert it back when that's possible. This seems to me to be a desired behavior in many, but not all, situations.

Are you not able to use `.groupby(...).nunique()` or `.groupby(...).agg('nunique')`?

**Comment by tamargrey** [comment]
@rhshadrach Using `nunique` does indeed let us avoid the error, but it's not ideal, as we expect that value to be a function that takes a series as input. In Featuretools, we determine which aggregations can apply to which columns in a DataFrame in one step and then apply them all at once via `.groupby(...).agg(`. This is also why `.groupby(...).nunique()` doesn't work for us. `'nunique'`, though not a function, can be passed into `.agg`, so we may be able to use it as a workaround for now. 

I think I agree that `agg` maintaining the original dtype if possible does make sense in many cases, as you say, but `nunique` is a good exception to that rule. We know it will always produce integers, and for data science purposes, the resulting column being potentially a `category` with integer `categories` is a fairly large semantic difference. Is the plan to come up with a fix for the behavior in this bug? Or is it not something that can be handled given `agg`'s lack of information about the operations it's calling?

**Comment by rhshadrach** [comment]
> as we expect that value to be a function that takes a series as input

Why can't you expect a string or function?

**Comment by tamargrey** [comment]
In Featuretools, we define [Primitives](https://featuretools.alteryx.com/en/stable/getting_started/primitives.html) as the basic operations that we may want to apply to columns in a feature matrix (which, in this case, are pandas DataFrames) to produce features. 

The operations that primitives use to build these features are defined in their `get_function` method. The results of `get_function` can then be applied to data in two ways:
1. Directly, by instantiating and then calling the primitive on an individual series. This eventually attempts to call the result of the `get_function` method, assuming it is a function that takes in a series. ([link](https://github.com/alteryx/featuretools/blob/main/featuretools/primitives/base/primitive_base.py#L61-L62)).
2. Via Deep Feature Synthesis, by passing the primitive into `dfs`, where it will eventually be used on any relevant columns in your inputted DataFrame. Aggregation functions are passed in, en masse, to [s.groupby(...).agg(...)](https://github.com/alteryx/featuretools/blob/main/featuretools/computational_backends/feature_set_calculator.py#L824-L828). Simpler transform primitives call the result of the `get_function` method directly ([link](https://github.com/alteryx/featuretools/blob/main/featuretools/computational_backends/feature_set_calculator.py#L523-L529)).

The fact that returning strings from `get_function` happens to work for aggregation primitives in the second way above is more of an accident than anything else. But the second method is the more common use of primitives, so we do use strings when necessary, but it's not preferred. We don't currently have plans to add widespread support for strings being returned from `get_function`, so we try to not use strings when possible.

**Comment by rhshadrach** [comment]
Thanks @tamargrey - right before you call `.agg(...)`, why can't you just swap out the argument?

```
swaps = {pd.Series.nunique: "nunique"}
to_agg = {column: [swaps.get(func, func) for func in funcs] for column, funcs in to_agg.items()}
```

Right now agg takes the callable as provided, uses it, and does some (perhaps not well-documented) post-processing. By trying to identify certain functions and resorting to different behavior, it makes the method more complicated for pandas to maintain and users to predict. For this reason I'm opposed.

If we were to move forward with detecting which callable a user passed and resorted to different behavior, for API consistency I think it would need to be done for every method supported across `Series`, `DataFrame`, `SeriesGroupBy`, `DataFrameGroupBy`, `Rolling`, `Resample`, and the window variants like `ExponentialMovingWindow`, `ExponentialMovingWindowGroupBy`, `Expanding`, etc. It would also need to be done for `agg`, `apply`, `transform` and `map`. The current behavior would need to be deprecated, and then change upon the next major release. This is no small effort.

**Comment by tamargrey** [comment]
Got it, I think we have sufficient workarounds for now, so I am okay with not changing the behavior as long as using the string `'nunique'` keeps its current behavior!

**Comment by rhshadrach** [comment]
Thanks for getting back to us!
