### ISSUE TITLE
BUG: `fill_value` does not work with binary operations between a Series and an Index object.

### ISSUE THREAD

**Issue by sfc-gh-vbudati** [pandas-dev/pandas#57320]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

On the latest version of Pandas, performing the following raises a ValueError.
```python
import pandas as pd
s = pd.Series([100, None, None])
rhs = pd.Index([25.4, 175, None])
s.add(rhs, fill_value=10)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/anaconda3/envs/latestpandas/lib/python3.12/site-packages/pandas/core/series.py", line 6286, in add
    return self._flex_method(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/user/anaconda3/envs/latestpandas/lib/python3.12/site-packages/pandas/core/series.py", line 6236, in _flex_method
    if isna(other):
       ^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

### Issue Description

- Arithmetic binary operations have an optional parameter `fill_value` to replace any NaN values with the given `fill_value`. 
- The ideal behavior is that given the lhs (Series `s`) and rhs (Index `rhs`), if only one of them is NaN, that is replaced by the fill_value. However, in pandas 2.2.0, it raises a value error instead.

### Expected Behavior

The expected result is 
```
0    125.4
1    185.0
2      NaN
dtype: float64
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : f538741432edf55c6b9fb5d0d496d2dd1d7c2457
python                : 3.12.1.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 23.3.0
Version               : Darwin Kernel Version 23.3.0: Wed Dec 20 21:31:00 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6020
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : None.UTF-8

pandas                : 2.2.0
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.8.2
setuptools            : 69.0.3
pip                   : 24.0
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2023.4
qtpy                  : None
pyqt5                 : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report! [The documentation](https://pandas.pydata.org/docs/reference/api/pandas.Series.add.html) states this method only takes Series or scalar values. You can wrap your index in a Series:

```
s = pd.Series([100, None, None])
rhs = pd.Index([25.4, 175, None])
print(s.add(pd.Series(rhs), fill_value=10))
# 0    125.4
# 1    185.0
# 2      NaN
# dtype: float6
```

**Comment by rhshadrach** [comment]
It seems to me that allowing addition of an index confuses the role of index vs values. Closing.
