### ISSUE TITLE
BUG: assert_index_equal defaults to check_exact_index=False on integers

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#57386]
Ref: https://github.com/pandas-dev/pandas/pull/57341#discussion_r1486812938

**Comment by Aloqeely** [comment]
Sorry but I don't understand what the bug is from the title, looking at `assert_index_equal`'s parameters I can see that `check_exact` always defaults to `True`
Looking at the comment, maybe you meant that `check_exact_index` in `assert_series_equal` defaults to `False` for integers?

**Comment by rhshadrach** [comment]
> maybe you meant that `check_exact_index` in `assert_series_equal` defaults to `False` for integers?

Yes - thanks.
