### ISSUE TITLE
BUG: Excel URLs disappear after 65530

### ISSUE THREAD

**Issue by pickfire** [pandas-dev/pandas#57400]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
# pip install pandas xlsxwriter
import pandas as pd
df = pd.DataFrame({'url': ['https://google.com'] * 100000})
df.to_excel('hello.xlsx', index=False)
```

### Issue Description

Excel have a limit of 65530 URLs in a single sheet, once it is passed the URLs are gone. Upstream issue closed as won't fixed https://github.com/jmcnamara/XlsxWriter/issues/1043

### Expected Behavior

Number of URLs should be tracked and once it go past 65530 URLs, it should should still be visible but unclickable.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : fd3f57170aa1af588ba877e8e28c158a20a4886d
python                : 3.11.7.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.7.2-zen1-2-zen
Version               : #1 ZEN SMP PREEMPT_DYNAMIC Wed, 31 Jan 2024 09:22:18 +0000
machine               : x86_64
processor             : 
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.0
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.8.2
setuptools            : 65.5.0
pip                   : 23.2.1
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : 3.1.9
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : 8.21.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>

**Comment by mroeschke** [comment]
Thanks for the report, but as pandas just dispatches to the underlying library to parse excel. So closing as an upstream issue. Maybe you can try submitting a request to openpyxl?

**Comment by pickfire** [comment]
Looks like it works on openpyxl but none of the URLs are clickable.
