### ISSUE TITLE
BUG: to_csv and load_csv add columns

### ISSUE THREAD

**Issue by R3dan** [pandas-dev/pandas#57407]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame() #any data frame from list of lists
df.to_csv("file.csv")

df2=pd.load_csv("file.csv")

print(df2.columns)
print(df.columns)
print(df.columns == df2.columns)
```

### Issue Description

When you do as the example with any data frame created with a list of lists (only one I've tested) it returns what was the row ids as an extra column.

### Expected Behavior

I would expect that the DataFrame is returned identical. WIthout the row index as the row index and an extra column

### Installed Versions

pandas              : 2.1.4
numpy               : 1.26.2
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 69.0.2
pip                 : 23.3.2
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.16.1
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.8.2
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.4
sqlalchemy          : 2.0.23
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

**Comment by rhshadrach** [comment]
Thanks for the report. When submitting bug reports, please provide a full reproducible example if possible.

In this example, `DataFrame.to_csv` includes the index by default. You need to pass `index=False` if you do not want this to happen.

Closing for now. If you think there is still an issue with pandas, comment here and we can reopen.
