### ISSUE TITLE
BUG: conversion from Int64 to string introduces decimals in Pandas 2.2.0

### ISSUE THREAD

**Issue by mplatzer** [pandas-dev/pandas#57418]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
pd.Series([12, pd.NA], dtype="Int64[pyarrow]").astype("string[pyarrow]")
```
yields
```
0    12.0
1    <NA>
dtype: string
```

### Issue Description

Converting from Int64[pyarrow] to string[pyarrow] introduces float notation, if NAs are present. I.e. `12` will be converted to `"12.0"`. This bug got introduced in Pandas 2.2.0, is still present on Pandas 2.2.x branch, but is not present on Pandas main branch.

### Expected Behavior

import pandas as pd
x = pd.Series([12, pd.NA], dtype="Int64[pyarrow]").astype("string[pyarrow]")
assert x[0] == "12"

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : fd3f57170aa1af588ba877e8e28c158a20a4886d
python                : 3.11.7.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 23.2.0
Version               : Darwin Kernel Version 23.2.0: Wed Nov 15 21:59:33 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8112
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : None.UTF-8

pandas                : 2.2.0
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.8.2
setuptools            : 69.0.3
pip                   : 24.0
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 15.0.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report. @mplatzer - can you give this issue a meaningful title? Currently it is `BUG:`.

**Comment by mplatzer** [comment]
@rhshadrach sorry, my bad, I've overlooked that. A meaningful title has now been added.

**Comment by rhshadrach** [comment]
Confirmed on main. Further investigations and PRs to fix are welcome.

**Comment by mplatzer** [comment]
I suspect the issue is related to this change (taken from the 2.2.0 release notes):
> integer dtypes with missing values are cast to NumPy float dtypes and NaN is used as missing value indicator
but wouldn't know any further details

**Comment by rhshadrach** [comment]
> This bug... is not present on Pandas main branch.

I'm still seeing it on main. Can you recheck, make sure we're seeing the same thing?

**Comment by mplatzer** [comment]
yes, you are right, it's still happening for main
```
>>> import pandas as pd
>>> pd.__version__
'3.0.0.dev0+355.g92a52e231'
>>> pd.Series([12, pd.NA], dtype="Int64[pyarrow]").astype("string[pyarrow]")
0    12.0
1    <NA>
```
