### ISSUE TITLE
BUG: Subsetting a df can sometimes change pandas behaviour into thinking the removed values still exists

### ISSUE THREAD

**Issue by Chuck321123** [pandas-dev/pandas#57421]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
See below.
```

### Issue Description

So this is the weirdest bug i have came across. So i want to remove a group value from a group and i run this command: ```df = df[df["Ticker"] != "BTCUSDT"]``` After this any lines in Group columns containing BTCUSDT should not exist. However, when i run this: ```Ticker_Lengths = df.groupby('Ticker').size().reset_index()``` i get this:
![image](https://github.com/pandas-dev/pandas/assets/123987501/8f91b1f8-cab7-4217-a195-e6b3de520a00)
How is that even possible when there exist no groups named "BTCUSDT"? And worse of all, i cant replicate the error as i tried this:
 ```
import pandas as pd
import numpy as np

# Create random data
data = {"Group": ["A"] * 3 + ["BTCUSDT"] * 3 + ["C"] * 3,
       "Value": [1, 2, 3, 4, 5, 6, 7, 8, 9]}

# Create DataFrame
df = pd.DataFrame(data)

# Filter away BTCUSDT
df = df[df["Group"] != "BTCUSDT"]
    
# Find the tickers lengths
Ticker_Lengths = df.groupby('Group').size().reset_index()
```
Edit: Found the issue. It does this if Ticker/Group is a category dtype. Might want to fix this

### Expected Behavior

That BTCUSDT doesnt show up in the group lengths

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : f538741432edf55c6b9fb5d0d496d2dd1d7c2457
python                : 3.12.1.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.19045
machine               : AMD64
processor             : Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : en
LOCALE                : Norwegian Bokmål_Norway.1252

pandas                : 2.2.0
numpy                 : 1.26.3
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 68.2.2
pip                   : 23.3.1
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : 5.0.2
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.2
IPython               : 8.15.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.2
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : 3.8.2
numba                 : 0.59.0
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.2
pandas_gbq            : None
pyarrow               : 14.0.2
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.11.4
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : 0.19.0
tzdata                : 2023.4
qtpy                  : 2.4.1
pyqt5                 : None

</details>

**Comment by mroeschke** [comment]
Thanks for the report, but you can use `.cat.remove_unused_categories` https://pandas.pydata.org/docs/reference/api/pandas.Series.cat.remove_unused_categories.html

**Comment by Chuck321123** [comment]
@mroeschke Yes, i saw your comment as i updated my comment. That is also a solution

**Comment by rhshadrach** [comment]
You can also use `observed=True` in groupby. This will become the default in pandas 3.0.
