### ISSUE TITLE
API: json should be returning string (if possible) in py2 rather than unicode

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#5743]
http://stackoverflow.com/questions/20670370/pandas-and-unicode/20670901?noredirect=1#comment30966775_20670901

**Comment by jorisvandenbossche** [comment]
@jreback Is this still something we want to change?

**Comment by jreback** [comment]
IIRC this was an env problem. closing as that was a pretty old post. if it comes up again can open a new one.
