### ISSUE TITLE
ENH: DF alias for DataFrame

### ISSUE THREAD

**Issue by lcrmorin** [pandas-dev/pandas#57433]
### Feature Type

- [ ] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

In a very lazy fashion, I was bored from having to write DataFrame everytime. I was wondering if DF could be used as an alias. It would save time when writing and also improve readability. 
Any toughts on this? 

### Feature Description

pd.DF() would works exactly like pd.DataFrame()

### Alternative Solutions

Create a DF class that inherits for DataFrame? Seems like overkill.

**Comment by attack68** [comment]
You do not need pandas to do this for you.

```python
from pandas import DataFrame as DF
df = DF([[1,2], [3,4]])
```

**Comment by mroeschke** [comment]
Agreed. Thanks for the suggestion but closing
