### ISSUE TITLE
QST: How to encrypt pandas.DataFrame data with AES algorithm?

### ISSUE THREAD

**Issue by snowuyl** [pandas-dev/pandas#57498]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/78018229/how-to-encrypt-pandas-dataframe-data-with-aes-algorithm

### Question about pandas

I would like to encrypt pandas.DataFrame data with Advanced Encryption Standard (AES). Does Pandas team provide sample code?

**Comment by attack68** [comment]
This isn't very focused question. What is the purpose of doing such a task?

A Pandas DataFrame is a Python Object. Is your intent to apply an algorithm to encode every element within the DataFrame and return a DataFrame of encoded elements, which can be decoded at a later stage?

Or is your intent to compress the DataFrame and its contents to a string, then encode the string which is essentially encoding the entire DataFrame, and then decode and reconstitute the DataFrame later?

For what is its worth I have used option 2 previously to save a DataFrame in a database encrypted. You can convert a DataFrame (with custom Type formatters if necessary) to a JSON string. Then encode the JSON string and store. Then retrieve and decode the JSON string and reconstitute the DataFrame in memory.

Like this:

```python
import pandas as pd

def encrypt(s):  # your own AES encryption on a string
    return s[::-1]

def decrypt(s):
    return s[::-1]

df = pd.DataFrame([[1,"a",4.0],[2,"b",3.0]])
s = df.to_json()  #  '{"0":{"0":1,"1":2},"1":{"0":"a","1":"b"},"2":{"0":4.0,"1":3.0}}'
e = encrypt(s)   #  '}}0.3:"1",0.4:"0"{:"2",}"b":"1","a":"0"{:"1",}2:"1",1:"0"{:"0"{'
# Store e in Database
d = decrypt(e)
df = pd.read_json(d)
```

**Comment by mroeschke** [comment]
As already mentioned, this is out of scope for pandas. The best way to probably approach this is write the DataFrame to a file format and encrypt that so closing
