### ISSUE TITLE
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0), (to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries) but was not found to be installed on your system. If this would cause problems for you,BUILD: 

### ISSUE THREAD

**Issue by Athiyasyed** [pandas-dev/pandas#57506]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0), (to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries) but was not found to be installed on your system. If this would cause problems for you,

### Installation Method

pip install

### pandas Version

2.2.0

### Python Version

3.12.2

### Installation Logs

<details>

Replace this line with the installation logs.

</details>
!pip install pandas

**Comment by bileamScheuvens** [comment]
The warning is purely informational and tells you all you need to know: ignore or install pyarrow.
If your issue goes beyond just wanting the warning to disappear; see https://github.com/pandas-dev/pandas/issues/54466 

Also technically duplicate? #57501

**Comment by mroeschke** [comment]
Please review https://github.com/pandas-dev/pandas/issues/54466
