### ISSUE TITLE
Pyarrow will become a required dependency of pandas in the next major release of pandas

### ISSUE THREAD

**Issue by gbfsdelhi** [pandas-dev/pandas#57501]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this issue exists on the main branch of pandas.

### Reproducible Example

I am trying to [index my Website URL](https://www.growbusinessforsure.com/) on Google through Python but getting this warning… Please tell me how I can fix it.
![Capture](https://github.com/pandas-dev/pandas/assets/140062552/bbca08b2-1e26-425c-b81d-8e144360dec9)

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by bileamScheuvens** [comment]
It's a warning, so there's nothing to "fix" really.
But if you plan on updating to pandas 3.0 you'll need pyarrow

**Comment by jorisvandenbossche** [comment]
The warning message also points to https://github.com/pandas-dev/pandas/issues/54466 as a feedback issue. But as @bileamScheuvens mentioned, you can install pyarrow and you won't see the warning message anymore.
