### ISSUE TITLE
why the loss: 8.7021 >= 1 ? why the sparse_categorical_accuracy: 4.9620 >=1 ?

### ISSUE THREAD

**Issue by challenge2** [pandas-dev/pandas#57566]
Epoch 25/25
104/104 ━━━━━━━━━━━━━━━━━━━━ 73s 709ms/step - loss: 8.7021 - sparse_categorical_accuracy: 4.9620 - val_loss: 1.0865 - val_sparse_categorical_accuracy: 0.6331

**Comment by jbrockmendel** [comment]
There isn't enough information here to know what you're talking about.  Please provide more context.
