### ISSUE TITLE
BUG: GroupBy float16 indexes are not supported

### ISSUE THREAD

**Issue by BohdanBilonoh** [pandas-dev/pandas#57564]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "column1": np.array([0.1, 0.1, 0.1, 0.2, 0.2, 0.2], dtype=np.float16),
    "column2": [1,2,3,4,5,6]
})

df.groupby("column1").groups
```

### Issue Description

GroupBy fails with float16 key type

### Expected Behavior

GroupBy should support float16 key dtype

### Installed Versions

INSTALLED VERSIONS
------------------
commit                : fc37c83c2deb59253ae2d10ca631b6a1242cfdcb
python                : 3.11.8.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 5.15.0-94-generic
Version               : #104~20.04.1-Ubuntu SMP Tue Jan 16 13:34:09 UTC 2024
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : en_US.UTF-8
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 3.0.0.dev0+407.gfc37c83c2d
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.8.2
setuptools            : 69.1.0
pip                   : 24.0
Cython                : 3.0.0
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : 8.21.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pyarrow               : 15.0.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

**Comment by phofl** [comment]
float16 is not supported In pandas, you'll have a bad time using it

**Comment by BohdanBilonoh** [comment]
Thank you for clarification!
