### ISSUE TITLE
ENH: pd.series.sample when n > len

### ISSUE THREAD

**Issue by marctorsoc** [pandas-dev/pandas#57584]
### Feature Type

- [X] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Oftentimes, I have some code that samples from a df / series, as in
```
df.sample(sample_size, random_state=88)
```
and given new data, `sample_size > len(df)`, getting
```
...Cannot take a larger sample than population...
```

I'd like a way to specify that if `sample_size > len(df)`, I just want all elements back. This is already the case with `.head()`. So I don't really understand why the behaviour is not the same here.

### Feature Description

I can see two possible solutions

1. As in [here](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html), "If n is larger than the number of rows, this function returns all rows."

2. If keping back-compatibility is a must, then adding a parameter `errors`, with possible values `ignore` or `raise` (default being `raise`, again to keep back-compatibility).

I'd lean towards (1), but I'd be content with (2)

### Alternative Solutions

I proposed two solutions. Of course, one can always add a line
```
sample_size = min(len(df), sample_size)
```
before the call, but I honestly think pandas should provide support for this common case + being consistent with other methods e.g. `head`.

### Additional Context

Happy to contribute with this feature, but first checking here. Just making sure owners would consider it, and nobody is working on this atm.

**Comment by lithomas1** [comment]
IIRC the error comes from numpy.

This is what I get
```
  File "/Users/thomasli/pandas/pandas/core/sample.py", line 153, in sample
    return random_state.choice(obj_len, size=size, replace=replace, p=weights).astype(
  File "numpy/random/mtrand.pyx", line 1001, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False
```

In that case, in my opinion, I think it's probably best for you to add an if check in your code before the call to sample to restrict the sample size to the length of the dataframe.

**Comment by mroeschke** [comment]
Yeah especially since this  is an error from numpy, I don't think it's appropriate for pandas to work around this so closing
