### ISSUE TITLE
DOC: missed doc for `DataFrame.isetitem` in https://pandas.pydata.org/docs/search.html?q=isetitem

### ISSUE THREAD

**Issue by anmyachev** [pandas-dev/pandas#57602]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

N/A

### Documentation problem

Missing documentation for a public method.

### Suggested fix for documentation

Since the method is public, its documentation should appear in https://pandas.pydata.org/docs/search.html?q=isetitem search.

**Comment by luke396** [comment]
https://pandas.pydata.org/pandas-docs/version/2.1/reference/api/pandas.DataFrame.isetitem.html not in v2.2 and dev version.
