### ISSUE TITLE
pandas 2.2.1 introduce API changes, for example for `groupby().first`, `groupby().last` and `series.argsort`

### ISSUE THREAD

**Issue by anmyachev** [pandas-dev/pandas#57631]
This makes code written in Pandas 2.2.1 incompatible with 2.2.0.

Was this done by mistake or on purpose? As far as I know, Pandas follows the semver methodology and this change is unexpected for me.

**Comment by mroeschke** [comment]
Not sure about the `argsort` change. Would be great to see an example of the change.

The other change is expected as noted in https://pandas.pydata.org/docs/whatsnew/v2.2.1.html#other and detailed in https://github.com/pandas-dev/pandas/pull/57102 cc @rhshadrach

**Comment by anmyachev** [comment]
> Not sure about the argsort change. Would be great to see an example of the change.

In pandas 2.2.1 (in comparison with 2.2.0) https://pandas.pydata.org/docs/reference/api/pandas.Series.argsort.html#pandas.Series.argsort has a new `stable` parameter.

**Comment by mroeschke** [comment]
I see thanks for point that out.

This PR introduced that change and was meant to give pandas 2.2.x potential compatibility with Numpy 2.0 when it comes out: https://github.com/pandas-dev/pandas/pull/57057. Sorry for not documenting it in the what's new, but the new argument was made backward compatible and doesn't change the behavior of `argsort`

**Comment by anmyachev** [comment]
@mroeschke just to be sure, pandas patch releases only guarantee backward compatibility and not forward compatibility?

**Comment by mroeschke** [comment]
I'm a little confused what forward compatible means in this context, but these changes will also apply to the next minor/major release (3.0)

**Comment by anmyachev** [comment]
I mean a situation where, for example, the code is written with the new parameters existing for version 2.2.1, but the user encountered some kind of error and decided to run the same code on pandas 2.2.0 (where parameters may not yet exist). Can one expect the code to work?

**Comment by rhshadrach** [comment]
> As far as I know, Pandas follows the semver methodology and this change is unexpected for me.

[pandas uses a loose variant of semantic versioning SemVer to govern deprecations, API compatibility, and version numbering.](https://pandas.pydata.org/docs/dev/development/policies.html#version-policy)

In the case of groupby first/last, the decision to add in 2.2.1 was made because we accidentally removed the ability of users to achieve the result with `skipna=False` in 2.0, and this was only brought to our attention as part of the 2.2.x development.

**Comment by mroeschke** [comment]
> the code is written with the new parameters existing for version 2.2.1, but the user encountered some kind of error and decided to run the same code on pandas 2.2.0 (where parameters may not yet exist). Can one expect the code to work?

For this example, no `argsort` with `stable` usage written in 2.2.1 will not be expected to work in 2.2.0

**Comment by anmyachev** [comment]
@mroeschke @rhshadrach thanks for the clarification! I received answers to all the questions, I think the issue can be closed.
