### ISSUE TITLE
Potential regression induced by #57347

### ISSUE THREAD

**Issue by DeaMariaLeon** [pandas-dev/pandas#57640]
PR #57347 May have induced a regression.
Benchmark:
`frame_methods.AsType.time_astype` (Python) with copy=False, from_to_dtypes=('float64[pyarrow]', 'float64[pyarrow]')

@phofl 

<img width="1113" alt="Screenshot 2024-02-27 at 09 47 41" src="https://github.com/pandas-dev/pandas/assets/11835246/3081f142-7446-4537-99e9-d2736ca59379">

**Comment by phofl** [comment]
This is overhead that is generated by the warning that is raised now, so closing as expected. 

We should get back to the original runtime by removing the copy keyword
