### ISSUE TITLE
ENH: DataFrame.duplicated() should have default `keep` parameter as False

### ISSUE THREAD

**Issue by jackmappotion** [pandas-dev/pandas#57659]
### Feature Type

- [X] Changing existing functionality in pandas

### Problem Description

`df.duplicated()` should return all of duplicates in my opinion. 
Default parameter is now `first` but I think it's not proper.

### Feature Description

```
def duplicated(
        self,
        subset: Hashable | Sequence[Hashable] | None = None,
        keep: DropKeep = "first",
    ) -> Series: ...
```

### Alternative Solutions

```
def duplicated(
        self,
        subset: Hashable | Sequence[Hashable] | None = None,
        keep: DropKeep = False,
    ) -> Series: ...
```

### Additional Context

I made pull request, but I just closed it.

Need discussions!

**Comment by rhshadrach** [comment]
Thanks for the request. Given the list `[1, 1, 1]`, it seems to me one can argue that  either all three values or just the 2nd and 3rd values are duplicates. Depending on which stance you take determines what you think `df.duplicated()` should do by default. If it is indeed a matter of opinion, then I think we should maintain the status quo and not induce code churn by changing the default.

If it can be shown that similar libraries have a corresponding method which (fairly) consistently default to the equivalent of `keep=False`, then that would be a more compelling case that pandas should change.
