### ISSUE TITLE
BUG: List of years (as string) raises UserWarning with to_datetime

### ISSUE THREAD

**Issue by jrmylow** [pandas-dev/pandas#57672]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> pandas.to_datetime(["2019"])
DatetimeIndex(['2019-01-01'], dtype='datetime64[ns]', freq=None)
>>> pandas.to_datetime(["2030-01-01", "2020-01-01"]) 
DatetimeIndex(['2030-01-01', '2020-01-01'], dtype='datetime64[ns]', freq=None)

>>> pandas.to_datetime(["2019", "2020"]) 
<stdin>:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
DatetimeIndex(['2019-01-01', '2020-01-01'], dtype='datetime64[ns]', freq=None)
```

### Issue Description

List of years (as strings) provided to `to_datetime` raises UserWarning. For some reason, single years and lists of dates do not trigger this warning. This is breaking tests in CI.

### Expected Behavior

Expect no userwarning.

### Installed Versions

 N/A

**Comment by jrmylow** [comment]
Update: this is a cpython standard library bug in datetime. The calling chain is:

* `to_datetime` is called from `tests/series/methods/test_nlargest.py`
* Within `core/tools/datetimes.py` it calls:
    * `to_datetime`
    * `convert_listlike`
    * `_convert_listlike_datetimes`
    * `_guess_datetime_format_for_array`
    * `guess_datetime_format` which returns None
* Over in `_libs/tslibs/parsing.pyx`:
    * `guess_datetime_format`
    * `dateutil_parse` which raises `ValueError`
    * `default.replace(**repl)` raises `DateParseError`

When testing with python:
```python
import datetime as dt
a = dt.datetime.today()
a.replace(**{'year': 2003})

# alternatively
a.replace(year=2003)
```
Both will raise `ValueError: day is out of range for month`. I'll raise this as a bug there

**Comment by MarcoGorelli** [comment]
> For some reason, single years and lists of dates do not trigger this warning.

if there's only a single element, then there's nothing to be inconsistent with

I think this is expected
