### ISSUE TITLE
Breaking change in nightly wheels when assigning to `df.values`, no FutureWarning

### ISSUE THREAD

**Issue by rossbar** [pandas-dev/pandas#57687]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
df = pd.DataFrame(np.array([[1.]]), index=[1], columns[1])
df.values[np.diag_indices_from(df)] *= 2
```

### Issue Description

This is something that popped up in the [networkx tests with the pandas nightly wheels](https://github.com/rossbar/networkx/actions/runs/8034082386/job/21945242713) (cf. [SPEC 4](https://scientific-python.org/specs/spec-0004/)), so I figured we'd raise here for awareness.

There is an instance of in-place assignment to `df.values` in the NX examples that has begun failing with the pandas nightly wheels:

### On latest stable from pypi (2.2.1)

```python
>>> import numpy as np
>>> import pandas as pd
>>> pd.__version__
'2.2.1'
>>> df = pd.DataFrame(np.eye(2), index=[1, 2], columns=[1, 2])
>>> df.values[np.diag_indices_from(df)] *= 2
>>> df
     1    2
1  2.0  0.0
2  0.0  2.0
```

### On nightly wheels

```python
>>> import numpy as np
>>> import pandas as pd
>>> pd.__version__
'3.0.0.dev0+444.gaabc35abe0'
>>> df = pd.DataFrame(np.eye(2), index=[1, 2], columns=[1, 2])
>>> df.values[np.diag_indices_from(df)] *= 2
Traceback (most recent call last)
   ...
ValueError: assignment destination is read-only
```

### Expected Behavior

I assume the actual behavior change is expected as part of pandas-3.0; my goal was to raise awareness that there is no `FutureWarning`/`DeprecationWarning` for the assigning-to-values in the current version of pandas. It may be that this is intentional - if so, please close this issue! FWIW we have caught and fixed [other issues in the NX test suite](https://github.com/networkx/networkx/pull/7209) via deprecation/future warnings.

### Installed Versions

Version info included above. Additional context - I tried the same minimal example with a 2.3 dev nightly wheel (`2.3.0.dev0+34.g0c23e18c73`) and no warnings were raised there either.

**Comment by rhshadrach** [comment]
I wonder if this might be due to CoW - cc @phofl

**Comment by phofl** [comment]
Yes it is and the change was intentional

**Comment by rossbar** [comment]
> Yes it is and the change was intentional

Thanks @phofl , I figured it was. The core of this issue is whether or not pandas intends to add raise a warning when users try to assign to `.values` - I suspect this pattern exists in user code for others who are not testing against the pandas nightlies. If not please don't hesitate to close, there's no request/action item on our end!

**Comment by phofl** [comment]
We can't warn here, we don't have control over what you do with the returned numpy array and we don't want to warn every time a user asks for a numpy array back just in case they might assign to it. It's unfortunate but this will be a breaking change in 3.0 that is very hard to warn about
