### ISSUE TITLE
Read and write spss data format

### ISSUE THREAD

**Issue by benjello** [pandas-dev/pandas#5768]
It would be nice to be able to import spss dant with read_spss and export it using to_spss.

**Comment by ThinkOnData** [comment]
Hi All, 
any progress on this topic?  
I was searching a lot about this and dont found any answer so I use this small code to import sav's to pandas  but only works in Python 3.5 

```
import pandas as pd
import numpy as np
import savWriterReader as spss

with spss.SavReaderNp ("some_sav_file.sav") as reader:
    records = reader.all()
df = pd.DataFrame(records)
df.head()
```

Hope to work to someone. 

Have a great day!

**Comment by ozak** [comment]
Lots of data is made available in SPSS so this tool would be very useful, especially for social scientists and economists. If the solution of @ThinkOnData works, it seems it should be an easy improvement. I will try it out and may submit a PR.

**Comment by jukkahuhtamaki** [comment]
I second the usefulness of `read_spss` and `to_spss`. I am currently entering a collaboration with a team of Information Systems scholars that use SPSS and UI-based Structural Equation Modeling tools. 

Using SPSS to manage the master survey data seems to be a common approach (cf., [Gaskin, 2016](https://www.youtube.com/watch?v=AS7ZxOZgU4c)). As the first step in introducing a computational approach to the collaboration, I am writing a script that preprocesses the survey data we have collected. Being able to easily read and write SPSS would certainly be helpful here.

**Comment by jorisvandenbossche** [comment]
For those interested in this issue, I think contributing better pandas support (or suggesting it) to the https://bitbucket.org/fomcl/savreaderwriter would be a good first step. 
If the package would have direct support to read a file into a DataFrame, and advertise this, I think it would already help a lot of people without needing to directly add it to pandas itself.

**Comment by alexwbakker** [comment]
SPSS is the only file format that is exportable from common survey tools like Qualtrics, SurveyGizmo, and SurveyMonkey that allows you to preserve both the values and the labels for many variables. 

Survey data seems to always be represented as one row per response and one column per questions or question choice. For single select questions or Open ended , the values are usually coded as a single number per choice, so a column may have a 1, 2, or 3 for male, female, or 'prefer not to state'. If you can multi-select, most survey tools export questions like Q2_1, Q2_2, Q2_3... for each of the possible choices, and then each cell has a 1 for Selected and a null/SYSMIS/NaN value if it was not selected. Sometimes, that missing data is also coded as a -99 or other values. 

Finally, SPSS has 2 properties, VARIABLE LABELS and VALUE LABELS that contain the Strings that tend to correspond to question text/choice text. 

If you export a survey file as CSV from any of those tools, you are presented with the choice to either take the strings from each questions (e.g. "Strongly Agree" will be what is in each cell where that was selected) or, you can have a '5'. the trouble is that for many types of analysis you want both. In pandas, I think it would be easy to treat all of these as category labels with pd.categorical. 

The common use case for this is to see what the average scale rating is for a question - e.g. in a Disagree <---> Agree scale is to get a mean response / st dev. But, you may also want to produce a cross tab that shows you count/percent for each category column. SPSS can do this pretty well, but, it is expensive, slow, and has a really lame internal syntax language. 

If pandas had full support for SPSS files, and could write them out, it would be very helpful for doing both initial data exploration, question aggregation, data restructuring, text analysis, and then write out the new file to leverage other downstream tools like Wincross for reporting/analysis that require SPSS files and are easy for business/non-techncial people to use.

**Comment by ofajardo** [comment]
I have written a wrapper for the C library Readstat named pyreadstat which reads SPSS sav, zsav and por files: github.com/Roche/pyreadstat

**Comment by cbrnr** [comment]
It would be great if this functionality was available directly from Pandas, e.g. via `read_spss`. @TomAugspurger @jreback @jorisvandenbossche (sorry for the explicit mentions, I don't know how to at the whole dev team) would this be an option (given that this requires a C lib)? @ofajardo would you be willing to merge your code?

**Comment by TomAugspurger** [comment]
It’s more likely that we would have an optional dependency on that package that a read_spss would use. Similar to what we do with pyarrow and parquet.

**Comment by ofajardo** [comment]
@cbrnr I am willing to help and contribute

**Comment by cbrnr** [comment]
Great! So this could be as simple as adding `pandas/io/spss.py` and wrapping relevant functions of `pyreadstat` (and making sure to import it only within functions and not globally). Since only a data frame should be returned, some effort is probably be necessary in using the meta information for creating suitable column names, data types, and so on.

Also,`pyreadstat` can also read SAS and Stata files, which Pandas already supports natively (but `pyreadstat` is much faster). I don't know how you would like to handle these file formats (ignore for now, create separate modules/functions or integrate with existing readers), but I think for now just adding support for SPSS files would be a good plan.

**Comment by TomAugspurger** [comment]
> Also,pyreadstat can also read SAS and Stata files, which Pandas already supports natively (but pyreadstat is much faster). I don't know how you would like to handle these file formats (ignore for now, 

I think ignore for now, but we can certainly revisit once we have spss taken care of. Once there's interest we can add an `engine` keyword to `read_sas` and `read_stata`.

**Comment by allefeld** [comment]
This issue shouldn't have been closed, since https://github.com/pandas-dev/pandas/pull/26537 covers only the reading part.

**Comment by jreback** [comment]
there is no write support anywhere AFAIK -
