### ISSUE TITLE
BUILD: require `python-dateutil>=2.9.0`

### ISSUE THREAD

**Issue by bersbersbers** [pandas-dev/pandas#57688]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Any

### Installation Method

pip install

### pandas Version

2.2.1

### Python Version

3.12.2

### Installation Logs

Installing `pandas` installs `python-dateutil`. On Python 3.12, `python-dateutil<2.9.0` issues warnings, compare https://github.com/pandas-dev/pandas/issues/57262. I'd suggest enforcing `python-dateutil>=2.9.0` as a dependency, at least on Python 3.12.

**Comment by bersbersbers** [comment]
Related: https://github.com/matplotlib/matplotlib/issues/27841

**Comment by rhshadrach** [comment]
2.9.0 was release 19 hours ago. Agreeing with [matplotlib](https://github.com/matplotlib/matplotlib/issues/27841#issuecomment-1973256393), I think that's far too recent to require.

**Comment by phofl** [comment]
Yeah we can't do this yet
