### ISSUE TITLE
BUG: pandas can't detect matplotlib on nanoserver (works fine on servercore)

### ISSUE THREAD

**Issue by robin-deltares** [pandas-dev/pandas#57681]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
#FROM mcr.microsoft.com/windows/servercore:ltsc2022
FROM mcr.microsoft.com/windows/nanoserver:ltsc2022

ADD python C:/python
RUN setx path "C:\python;C:\python\scripts;%PATH%"
RUN python -m pip install matplotlib pandas

<< Then use pandas inside container >>
```

### Issue Description

Build a Docker container using mcr.microsoft.com/windows/nanoserver:ltsc2022 with python (identical behavior with 3.7 and 3.12) and any versions of pandas+matplotlib.

Use pandas library.

File "C:\python\Lib\site-packages\pandas\plotting\_core.py", line 1874, in _load_backend
raise ImportError(
ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

Works fine when running identical code on mcr.microsoft.com/windows/servercore:ltsc2022 Docker container.

### Expected Behavior

Should work with nanoserver too.

### Installed Versions

Tried with many versions of pandas and matplotlib.

**Comment by rhshadrach** [comment]
Thanks for the report. Why do you think this is an issue with pandas?

**Comment by phofl** [comment]
closing, please ping to reopen if you can provide more context
