### ISSUE TITLE
Failing benchmarks - About 3000 asv benchmark tests fail out of 7545

### ISSUE THREAD

**Issue by DeaMariaLeon** [pandas-dev/pandas#57694]
Is it normal that out of 7545 benchmark tests, 3014 fail? (these numbers are for Cython 3.0). It's more or less the same with 3.05.

For "test" I mean a benchmark with one combination of its parameters. For example this would be 1 test:

"ctors.SeriesConstructors.time_series_constructor('<function gen_of_str>', 'True', "'float'")".

All the failing tests are seen as blank [here](https://asv-runner.github.io/asv-collection/pandas/#summarylist?python=3.10&numpy=%5Bnone%5D&Cython=3.0.0&xlwt=%5Bnone%5D&meson=&meson-python=&python-build=&sort=1&dir=asc).

Is the command bellow being done somewhere in the workflow? As you might know, it's supposed to be done after a benchmark is updated/changed:
```
[asv update](https://asv.readthedocs.io/en/v0.6.1/commands.html?highlight=asv%20publish#id14)
usage: asv update [-h] [--verbose] [--config CONFIG] [--version]

Update the results and config files to the current version

options:
  -h, --help       show this help message and exit
  --verbose, -v    Increase verbosity
  --config CONFIG  Benchmark configuration file
  --version        Print program version
```

For "fail" I mean as in getting `NaN` or `null` as result. From asv docs:  
```
result:(param-list) contains the summarized result value(s) of the benchmark. The values are float, NaN or null.

The values are either numbers indicating result from successful run, null indicating a failed benchmark, 
or NaN indicating a benchmark explicitly skipped by the benchmark suite.
```

**Comment by lithomas1** [comment]
There should be a traceback if you do ``--show-stderr``. Usually NaN would mean that there was an error running the benchmarks.

There seems to be data recorded here, though https://github.com/asv-runner/asv-collection/blob/master/pandas/graphs/Cython-3.0.0/arch-x86_64/branch-main/cpu-Intel(R)%20Core(TM)%20i7-4980HQ%20CPU%20%40%202.80GHz/jinja2/machine-asv-runner/matplotlib/meson/meson-python/numba/numexpr/numpy-null/odfpy/openpyxl/os-Linux%203.13.0-116-generic/pyarrow/pytables/python-3.10/python-build/ram-501692/scipy/sqlalchemy/xlrd/xlsxwriter/xlwt-null/ctors.SeriesConstructors.time_series_constructor.json

Maybe it's a visual bug?

**Comment by DeaMariaLeon** [comment]
@lithomas1 Thanks, but it's not a visual bug. On the link you sent, some of the results are "null", meaning  it's a failed benchmark result. If you see the results in the middle:

![Screenshot 2024-03-01 at 16 59 10](https://github.com/pandas-dev/pandas/assets/11835246/f9093ef6-00bf-4bd3-98af-73f8faa52e82)

Plus I see the same with conbench. 
I think that benchmarks are being updated, but asv is not being "told" to update (the command I sent above: `asv update`). Look:
```
 params: contains a copy of the parameter values of the benchmark, as described above. If the user has modified the benchmark after the benchmark was run, these may differ from the current values. 
```

**Comment by rhshadrach** [comment]
For NaN I think this is expected. As far as I know, you can only use a full cartesian product when parametrize a benchmark with multiple parameters. In order to exclude certain (invalid) combinations of parameters, we `raise NotImplementedError` in the benchmarks. I believe this will result in a NaN.

How many `null` vs `NaN` do you see?

**Comment by DeaMariaLeon** [comment]
> How many null vs NaN do you see?

I see less than 3000 `NaN` vs 17888 `null` per commit. 

Do you know if the command `asv update` is being done somewhere? 

I also see a benchmark name (so being done) in the results, but the benchmark itself is not in the current code. Which would also be explained by asv  not being updated.

**Comment by DeaMariaLeon** [comment]
Thanks @rhshadrach. The results we need are all `NaN`. Some others are `null` but are not used.

The last thing is, do you perform the "asv update" command or is it done somewhere?
If you don't know never mind. I ask just because is in asv's documentation but if that's not a problem I'm good.

**Comment by rhshadrach** [comment]
No - I do not currently.

**Comment by DeaMariaLeon** [comment]
You have this on your [code](https://github.com/rhshadrach/asv-watcher/blob/10cec8096b5bb1d1ef7ef4b320bf8b2db482c98b/asv_watcher/_core/update_data.py#L19): 
```
# TODO: Why does this happen?
# print(benchmark, "has no data. Skipping.")
```

I have that when the result is `nan`. And I think you have another issue with the name of the benchmark not being found. It happened to me when the file "benchmarks.json" was not updated. 

Otherwise, sorry for the noise.

**Comment by rhshadrach** [comment]
Thanks! I had been wanting to spend some time investigating that for months now, and you just saved me the hassle!

> And I think you have another issue with the name of the benchmark not being found. It happened to me when the file "benchmarks.json" was not updated.

I see - I don't think I understand what update was doing, but it sounds like it will take old benchmark results and update time with the new benchmark suite (if it has changed). This will be very useful!

**Comment by DeaMariaLeon** [comment]
I'm glad to hear that! -  It [looks](https://github.com/airspeed-velocity/asv/releases#:~:text=you%20to%20run-,asv%20update,-once%20after%20upgrading) that sometimes that update is needed and sometimes it's not, depending how you run asv. 
And from the [docs](https://asv.readthedocs.io/en/v0.6.1/dev.html?highlight=version#benchmark-suite-layout-and-file-formats:~:text=params%3A%20contains%20a%20copy%20of%20the%20parameter%20values%20of%20the%20benchmark%2C%20as%20described%20above.%20If%20the%20user%20has%20modified%20the%20benchmark%20after%20the%20benchmark%20was%20run%2C%20these%20may%20differ%20from%20the%20current%20values.) it's clear that things can get out of sync. 

Closing this then, thanks.  :-)
