### ISSUE TITLE
ENH: Be able to set dtype before creating a new column

### ISSUE THREAD

**Issue by Chuck321123** [pandas-dev/pandas#57691]
### Feature Type

- [X] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

So one can do 
```
df["New_Col"] = 0
df["New_Col"] = df["New_Col"].astype("int8")
```
But its not possible to do 
```
df["New_Col"] = 0.astype("int8")
```

Would be nice to find a solution so one can set dtype before creating a new column.

### Feature Description

See problem descripion

### Alternative Solutions

Se problem description

**Comment by rohanjain101** [comment]
You could do:

` df["New_Col"] = np.int8(0)`

Not sure if there's a datatype that using a typed scalar wouldn't work for.

**Comment by rhshadrach** [comment]
You can also use pd.array for other dtypes, e.g. 

    df["New_Col"] = pd.array([0] * len(df), dtype="Int32")

 If you're concerned with creating a large Python list, you can also use NumPy here:

    df['b'] = pd.array(np.zeros(len(df), dtype="int8"), dtype="Int32")

**Comment by satyasri77** [comment]
You can use np.array for all data types
`df['New_Col'] = np.array([0]).astype("int8")`

**Comment by phofl** [comment]
> You can use np.array for all data types
df['New_Col'] = np.array([0]).astype("int8")

No you can't, that's incorrect for ea arrays

But agree with @rhshadrach, you can do this with pd.array
