### ISSUE TITLE
Inconsistent name for keyword that determines whether new object is generated

### ISSUE THREAD

**Issue by 8one6** [pandas-dev/pandas#5769]
If I understand this right, the syntax is:

``` python
df.sort_index(..., inplace=False)
```

but is 

``` python
df.reindex_axis(..., copy=True)
```

Any reason why we shouldn't just use the same keyword (either `copy` or `inplace`) in all functions to determine whether to modify the original object or make a new one?

**Comment by mroeschke** [comment]
`reindex_axis` has been deprecated and removed. Closing
