### ISSUE TITLE
Pandas Extension: Drop Duplicated Columns

### ISSUE THREAD

**Issue by kanhapatil** [pandas-dev/pandas#57716]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

When working with datasets in pandas, users often encounter the need to identify and handle duplicated columns. The presence of duplicated columns can complicate data analysis, lead to redundancy, and affect computational efficiency. Currently, pandas lacks a built-in method to easily drop duplicated columns from a DataFrame.

### Feature Description

The proposed feature introduces a new functionality to pandas, enabling users to drop duplicated columns from a DataFrame effortlessly. This is achieved through the addition of a drop_duplicated_columns method within a new class named DuplicateCols.

### Alternative Solutions

import pandas as pd

data = pd.DataFrame({
    'A' : [1,2,3,4,5],
    'B' : [10,20,30,40,50],
    'C' : [2,4,6,8,10],
    'D' : [10,20,30,40,50],
    'E' : [1,2,3,4,5],
    'F' : [1,2,3,4,5],
})

class DuplicateCols:
    def __init__(self, dataset):
        self.temp = set()
        self.dupCols = []
        self.nonDupCols = []
        self.compareCols = []
        self.dataset = dataset

    def duplicateColumns(self):
        for col in self.dataset.columns:
            col_data = tuple(self.dataset[col])
            if col_data in self.temp:
                self.dupCols.append(col)
            else:
                self.temp.add(col_data)
                self.nonDupCols.append(col)
        return self.dupCols

    def nonDuplicateColumns(self):
        self.duplicateColumns()
        return self.nonDupCols

    def dropDuplicateColumns(self):
        self.duplicateColumns()
        return self.dataset[self.nonDupCols]

# Example Usage:
duplicates = DuplicateCols(data)
print("Duplicated Columns:", duplicates.duplicateColumns())
print("Non-Duplicated Columns:", duplicates.nonDuplicateColumns())
result_df = duplicates.dropDuplicateColumns()
print("DataFrame after dropping duplicated columns:")
print(result_df)

**Comment by kanhapatil** [comment]
It seems like the current implementation of the feature focuses on detecting duplicated columns based on the values they contain, but it may not handle cases where columns have the same names.

**Comment by phofl** [comment]
You can simply do:

```
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=["a", "a", "c"])
df.loc[:, ~df.columns.duplicated(keep="first")]
```

-1 on adding this to the api
