### ISSUE TITLE
ENH: Assign for pandas Series

### ISSUE THREAD

**Issue by cbrummitt** [pandas-dev/pandas#57736]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I frequently use [`pd.DataFrame.assign`](https://github.com/pandas-dev/pandas/blob/v2.2.1/pandas/core/frame.py#L5161-L5227) in chains of statements, following the pattern in the blog post [Method Chaining](https://tomaugspurger.net/posts/method-chaining/) in Tom Augspurgers's series Modern Pandas. For example:
```python
df.assign(x=lambda df: df['y'] + 1).groupby('x').agg(['sum', 'mean'])
```
I wish there were an equivalent for Series.

### Feature Description

A new method on pandas Series would, given keyword arguments, assign them as rows, and return a pointer to itself (to enable chaining of statements). The implementation could look like this:
```python
    def assign(**kwargs) -> Series:
        new_ser = self.copy(deep=False)
        for k, v in kwargs.items():
            new_ser.__set_item__(k, v)
        return new_ser
```

### Alternative Solutions

An alternative is to do nothing, and users continue to break up statements into multiple statements. For example, rather than
```python
summary = series.assign(grand_total=lambda s: s.sum()).to_string()
```
the user breaks it up as:
```python
series.loc['grand_total'] = series.sum()
summary = series.to_string()
```
This simple example makes the alternative look not so bad, but when you have chains of multiple method calls involving one or more `assign` statements, when you use Series you have to break it up, while with DataFrames you can chain them all.

### Additional Context

I [searched issues for "series assign"](https://github.com/pandas-dev/pandas/issues?q=is%3Aissue+is%3Aopen+series+assign) and didn't find an issue that duplicates this one.

Something that may confuse readers is that DataFrame.assign makes new columns, while the proposed Series.assign makes new rows (provided that you think of Series as column vectors, which is natural since that's how they're displayed, they have an index, and that's what you get when you call `.to_frame()`).

**Comment by rhshadrach** [comment]
Thanks for the request. `Series.assign` would have to make a copy of the entire Series, whereas `DataFrame.assign` does not (now with Copy On Write). In general, expanding Series / DataFrame rows is something that should be avoided whenever possible for performance, and I think making this easier to do would encourage bad practices. For this reason, I'm currently opposed.

**Comment by cbrummitt** [comment]
Got it. Is there a way to implement it like [`dict.update`](https://docs.python.org/3/library/stdtypes.html#dict.update) that would make it perform quickly?

**Comment by phofl** [comment]
No, the memory layout prevents doing this efficiently

**Comment by phofl** [comment]
closing
