### ISSUE TITLE
ENH: interleave_columns function

### ISSUE THREAD

**Issue by raybellwaves** [pandas-dev/pandas#57731]
### Feature Type

- [x] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I would like do the equivalent in pandas as `interleave_columns` in cudf (https://docs.rapids.ai/api/cudf/legacy/user_guide/api_docs/api/cudf.dataframe.interleave_columns/)

### Feature Description

Similar to the cudf example

```
df = pd.DataFrame({0: ['A1', 'A2', 'A3'], 1: ['B1', 'B2', 'B3']})
df.interleave_columns()
0    A1
1    B1
2    A2
3    B2
4    A3
5    B3
dtype: object
```

### Alternative Solutions

https://github.com/rapidsai/cudf/blob/branch-24.04/cpp/src/lists/interleave_columns.cu#L350

I got working with some numpy code but it's currently custom to the number of columns
```
pd.Series(np.ravel(np.column_stack((df[0], df[1]))))
```

**Comment by asishm** [comment]
what about `df.T.melt()`? you can then either `set_index` the `variable` column or drop it altogether.

```py
In [10]: df = pd.DataFrame({0: ['A1', 'A2', 'A3'], 1: ['B1', 'B2', 'B3'], 2: ['C1', 'C2', 'C3']})

In [11]: df
Out[11]:
    0   1   2
0  A1  B1  C1
1  A2  B2  C2
2  A3  B3  C3

In [12]: df.T.melt()
Out[12]:
   variable value
0         0    A1
1         0    B1
2         0    C1
3         1    A2
4         1    B2
5         1    C2
6         2    A3
7         2    B3
8         2    C3
```

**Comment by phofl** [comment]
Yep agree that this should solve the problem

**Comment by raybellwaves** [comment]
I ended up finding out how to do this in the cudf test suite https://github.com/rapidsai/cudf/blob/branch-24.06/python/cudf/cudf/tests/test_reshape.py#L305 `pd.Series(np.vstack(pdf.to_numpy()).reshape((-1,)))` which is much faster than `df.T.melt()["value"]`. Thanks for tip though!
