### ISSUE TITLE
DOC: Incorrect Description For pd.concat sort Argument

### ISSUE THREAD

**Issue by Wikilicious** [pandas-dev/pandas#57753]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.concat.html#pandas.concat

### Documentation problem

The first part of the documentation for the `sort` argument in `pd.concat` is confusing and incorrect.
```
Sort non-concatenation axis if it is not already aligned. 
```
It wasn't clear to me if the result `df` would be sorted if the `df`'s being concatenated were already aligned (but not sorted). I had to manually confirm.

I suspect the wording originated from this bug #4588 
Which added `FutureWarning: Sorting because non-concatenation axis is not aligned. A future version of pandas will change to not sort by default.` 

### Suggested fix for documentation

Remove the `if it is not already aligned` part.

**Comment by rhshadrach** [comment]
Related: #57335

**Comment by rhshadrach** [comment]
Thanks for the report; confirmed alignment does not impact the result on main. Would you be interesting in submitting a PR to fix the docs @Wikilicious?

```
index = pd.Index(["a", "c", "b"])
df = pd.DataFrame({"a": [1, 1, 2], "b": [3, 4, 5]}, index=index)
ser = pd.Series([6, 7, 8], index=index)
print(pd.concat([df, ser], axis=1, sort=True))
#    a  b  0
# a  1  3  6
# b  2  5  8
# c  1  4  7
```

**Comment by Wikilicious** [comment]
Hi @rhshadrach 
Yes, I'm interested in submitting a PR with the suggested fix.

**Comment by Wikilicious** [comment]
take
