### ISSUE TITLE
ENH: DataFrame argument `columns` should accept dict/iterable type

### ISSUE THREAD

**Issue by 5j9** [pandas-dev/pandas#57798]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

It is convenient to pass a dict to `columns` argument of `DataFrame` and use the same dict for `astype` conversions later. The following sample code works fine, but it fails type checking:
```python
from pandas import DataFrame

columns = {"A": 'int64', "B": 'int32', "C": 'int16'}
df = DataFrame([[1,2,3],[4,5,6]], columns=columns)  # fails type check
df = df.astype(columns)

print(df.dtypes)
```

pyright output:
```bash
$ pyright 'filename.py'
filename.py
  filename.py:4:43 - error: Argument of type "dict[str, str]" cannot be assigned to parameter "columns" of type "Axes | None" in function "__init__"
    Type "dict[str, str]" cannot be assigned to type "Axes | None"
      "dict[str, str]" is incompatible with "ExtensionArray"
      "dict[str, str]" is incompatible with "ndarray[Unknown, Unknown]"
      "dict[str, str]" is incompatible with "Index"
      "dict[str, str]" is incompatible with "Series"
      "dict[str, str]" is incompatible with protocol "SequenceNotStr[Unknown]"
        "index" is not present
        "count" is not present
    ... (reportArgumentType)
1 error, 0 warnings, 0 informations
```

### Feature Description

Change type annotations for columns to accept dict/iterable type.

### Alternative Solutions

Convert columns value to a `Series` or numpy array or some other compatible type.

**Comment by asishm** [comment]
do you have `pandas-stubs` installed?

**Comment by 5j9** [comment]
> do you have `pandas-stubs` installed?
> 
> this only reproduces without `pandas-stubs` for me

I don't have pandas-stubs. You are right, works fine with stubs. I still think this should not raise error even without stubs given that pandas-stubs describes itself as "narrower than what is possibly allowed by pandas".

**Comment by twoertwein** [comment]
Would need to adjust

https://github.com/pandas-dev/pandas/blob/10f31f6a242fb01fdf37f5db2e8c6f4f82f5af16/pandas/core/frame.py#L681

to include `Mapping`.

**Comment by phofl** [comment]
It is completely conicidential that this works and nobody should rely on it. Closing

**Comment by twoertwein** [comment]
> It is completely conicidential that this works and nobody should rely on it. Closing

@Dr-Irv pandas-stubs currently declares that any `dict` would be okay

**Comment by Dr-Irv** [comment]
> > It is completely conicidential that this works and nobody should rely on it. Closing
> 
> @Dr-Irv pandas-stubs currently declares that any `dict` would be okay

I checked via Blame and I put that in there at some point without a test.  I just tested removing `dict` from `Axes` in pandas-stubs and it works fine, so maybe we should remove it??

**Comment by Dr-Irv** [comment]
> I don't have pandas-stubs. You are right, works fine with stubs. I still think this should not raise error even without stubs given that pandas-stubs describes itself as "narrower than what is possibly allowed by pandas".

Yes, but the typing in the pandas source is much wider than what is actually allowed by pandas.  Also, type checking is faster using the stubs than using the pandas source.
