### ISSUE TITLE
ENH: simple add row capactiy to dataframes

### ISSUE THREAD

**Issue by R3dan** [pandas-dev/pandas#57809]
### Feature Type

- [X] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish to be able to easily add a new row to a dataframe with a function like 'append' or 'new_row' etc. I am fairly sure that this is already accomplishable with additional code etc but I could not find it. If someone could tell me how to do it now that would be great but I also feel it could be made easier.

### Feature Description

An example could be: 
```python
def add_new_row(data):
    self.rows.append(data)
```
or something similar as I do not know how pandas store indexes etc and with additional checks and functionality

### Alternative Solutions

```python
import pandas as pd
df = pd.DataFrame(columns=["a", "b", "c", "d"])
df.iloc[0] = pd.Series([1,2,3,4])
```

### Additional Context

An in use example could be like:
```python
import pandas as pd
df = pd.DataFrame(columns=["a", "b", "c", "d"])
df.new([1,2,3,4)]
# or:
df.new(pd.Series([1,2,3,4]))
# etc
```

**Comment by attack68** [comment]
Googling `add new row to pandas dataframe` gives the first result: https://www.geeksforgeeks.org/how-to-add-one-row-in-an-existing-pandas-dataframe/

One of methods contained within demonstrates `DataFrame.append(data)` which is basically what you are proposing.

**Comment by mroeschke** [comment]
Thanks for the suggestion but agreed with above. You can achieve this currently with indexing or `pd.concat` so closing
