### ISSUE TITLE
read_csv date_format parameter should allow lambda as a value

### ISSUE THREAD

**Issue by hasandiwan** [pandas-dev/pandas#57836]
It's all well and good to deprecate date_parser and suggest using date_format or pd.to_datetime 
instead, but why I should need to read in the column and then convert to dates is beyond me? Hence, I would suggest that date_format be permitted to take a lambda as well.

If there are a few +1s to this issue, I will write a patch to sort the issue and attach it here.

**Comment by Aloqeely** [comment]
Thanks for the suggestion. The idea is that `read_csv` should not handle complicated parsing and that you should use `to_datetime` for that.

**Comment by Aloqeely** [comment]
But it is still possible to read the column as a date directly by using the `date_format` and `parse_dates` parameters.

Additionally it seems like not many people are interested in this feature so going to close unless you bring a good argument of why we should allow complex parsing directly
