### ISSUE TITLE
DOC: Remove Dask and Modin sections in `scale.rst` in favor of linking to ecosystem docs.

### ISSUE THREAD

**Issue by mroeschke** [pandas-dev/pandas#57831]
xref https://github.com/pandas-dev/pandas/pull/57586#pullrequestreview-1922295036

1. Remove `Use Dask` and `Use Modin` sections in `doc/source/user_guide/scale.rst`
2. Add a new section in  `doc/source/user_guide/scale.rst` (`Use Other Libraries`) and link to `Out-of-core` section in `web/pandas/community/ecosystem.md`
3. Remove `dask-expr` in `environment.yml` and `requirements.txt`
4. Remove version pinning on `dask` post https://github.com/pandas-dev/pandas/pull/57830

**Comment by yukikitayama** [comment]
take

**Comment by yukikitayama** [comment]
Hi @mroeschke I don't know which code I need to update regarding "4. Remove version pinnig on `dask` post". Sorry if I'm asking too basic. I'm new to contribution.

**Comment by mroeschke** [comment]
`environment.yml` and `requirements.txt`
