### ISSUE TITLE
ENH: Bring back append() on data frames

### ISSUE THREAD

**Issue by arencambre** [pandas-dev/pandas#57849]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I liked what the .append() method did for data frames. Please bring it back.

Per #35407, this was the tenth most sought after method in the Pandas API, per traffic on its documentation page. It makes sense as this was a sensible method whose name made clear what it does.

Concerns about performance of .append() could be true. That is an invitation to improve append().

Concerns about a poor name chosen for a method for a different class could be true. Fix the other class.

I am currently wrapping my head around switching my perfectly fine, performant code to use pandas.concat(). While I did it fine, this was not a good use of my time. Let's not make any others suffer through this.

### Feature Description

See **Problem Description** section.

### Alternative Solutions

See **Problem Description** section.

**Comment by phofl** [comment]
This was discussed and rejected a long time ago. Nothing changed with respect to the reasons that made us remove it
