### ISSUE TITLE
DOC: Reference to deprecated week and weekofyear attributes

### ISSUE THREAD

**Issue by tray3j** [pandas-dev/pandas#57887]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/user_guide/timeseries.html#time-date-components

### Documentation problem

Per this discussion: [https://github.com/pandas-dev/pandas/issues/55092](url) the week and weekofyear attributes are deprecated since 1.1.0 and DatetimeIndex.isocalendar().week is now recommended. 

### Suggested fix for documentation

We should update the user guide to reflect isocalendar().week funcitonality. We should delete the rows in the table relating to week and weekofyear attributes under .dt. A reference already exists to isocalendar() but it is currently not clear to the user that this is the only way to access week of year date information.

**Comment by lithomas1** [comment]
PRs would be welcome.
