### ISSUE TITLE
ENH: Allow args to be specified for the pivot_table aggfunc

### ISSUE THREAD

**Issue by j-kapp** [pandas-dev/pandas#57884]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Currently the `pivot_table` has an `aggfunc` parameter which is used to do a groupby aggregation [here](https://github.com/pandas-dev/pandas/blob/main/pandas/core/reshape/pivot.py#L170). However, no additional arguments can be passed into that `agg` call. I'm specifically referring to the `*args` which can be specified in (df/series) [groupby.agg](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.agg.html) function. It would be very useful if `pivot_table` could accept additional arguments for the `aggfunc`.

### Feature Description

I'm not 100% sure, but I think it would be something like this:
1. Add a `**aggfunc_args` or `aggfunc_args: dict` parameter to the `pivot_table` function.
2. Do the same for the `__internal_pivot_table` function
3. Change the line [here](https://github.com/pandas-dev/pandas/blob/main/pandas/core/reshape/pivot.py#L170), from `agged = grouped.agg(aggfunc)` to `agged = grouped.agg(aggfunc, **aggfunc_args)`.
4. Update the docs

### Alternative Solutions

The same functionality can currently be achieved by specifying a custom function as `aggfunc`, but using that is much slower. My use case is pretty much the same as [this](https://stackoverflow.com/questions/56890105/how-to-keep-nan-in-pivot-table).
Instead of using `pd.pivot_table(... , aggfunc=lambda x: x.sum(min_count=1))`, I would like to be able to do `pd.pivot_table(... , aggfunc=sum, min_count=1)` or similiar.

**Comment by rhshadrach** [comment]
Thanks for the request - it makes sense to me to support passing through kwargs here. The only question is how:

    def pivot_table(self, ..., **kwargs)
    def pivot_table(self, ..., kwargs)
    def pivot_table(self, ..., args, kwargs)

I do not think we should do

    def pivot_table(self, *args, ..., **kwargs)

If we want to agree with the current direction of apply/agg/transform, it would be the first of the above three options. Ref: https://github.com/pandas-dev/pandas/issues/40112

**Comment by PF2100** [comment]
take

**Comment by PF2100** [comment]
Hi, regarding that first option, would passing positional arguments to the aggfunc not be supported?
I must say I agree on the signature you proposed on the referenced issue ( `func, args, kwargs, other_arg`, sort of like the third option here) being the best overall, however, it seems like this is not the current standard for pandas.

**Comment by PF2100** [comment]
take

**Comment by PF2100** [comment]
> Hi, regarding that first option, would passing positional arguments to the aggfunc not be supported? I must say I agree on the signature you proposed on the referenced issue ( `func, args, kwargs, other_arg`, sort of like the third option here) being the best overall, however, it seems like this is not the current standard for pandas.

@rhshadrach Sorry to bother you, but could you share your thoughts on this matter?

**Comment by rhshadrach** [comment]
@PF2100 - thanks for the ping! 

> I must say I agree on the signature you proposed on the referenced issue ( `func, args, kwargs, other_arg`, sort of like the third option here) being the best overall, however, it seems like this is not the current standard for pandas.

Same here, but for consistency, it seems best to go with (1) for now. Changing from `**kwargs` to `kwargs` is likely to be quite noisy or users and I don't feel confident it will get enough support.
