### ISSUE TITLE
QST：pandas.groupby().diff()

### ISSUE THREAD

**Issue by zybmiximixi** [pandas-dev/pandas#57882]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/78178582/pandas-for-groupby-diff

### Question about pandas

The groupby().diff() operation of pandas does not comply with the default as_index=True parameter and does not use the keys in groupby as indexes. Is this what is the reason.

**Comment by rhshadrach** [comment]
Thanks for the report - the `as_index` argument [is documented](https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.groupby.html) as:

> This argument has no effect on filtrations (see the [filtrations in the user guide](https://pandas.pydata.org/docs/dev/user_guide/groupby.html#filtration)), such as head(), tail(), nth() and in transformations (see the [transformations in the user guide](https://pandas.pydata.org/docs/dev/user_guide/groupby.html#transformation)).

`.diff` is a transformation. Closing.
