### ISSUE TITLE
DOC: Getting started tutorial headings and buttons are not readable

### ISSUE THREAD

**Issue by SilvestriStefano** [pandas-dev/pandas#57912]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/getting_started/index.html

### Documentation problem

Hello,
I have found that the headings to the various Getting Started Tutorials are not readable in dark mode.
![image](https://github.com/pandas-dev/pandas/assets/18087952/d599117d-0072-41a4-82fb-f967773d68f9)
Also the text in the button is not readable in light mode
![image](https://github.com/pandas-dev/pandas/assets/18087952/121d9efd-cdc8-4914-b7ce-33227b0cc852)

### Suggested fix for documentation

I believe the issue with the heading is due to the fact that the CSS variable `--bs-card-cap-color` is not initialized
![image](https://github.com/pandas-dev/pandas/assets/18087952/01fee941-4a4b-46a0-b22e-a7637efd97bf)

I suggest to fix it as follows  
```diff
/* line 250 of the file pandas/doc/source/_static/css/getting_started.css */

.tutorial-card .card-header {
+ --bs-card-cap-color: var(--pst-color-text-base); 
  cursor: pointer;
  background-color: var(--pst-color-surface);
  border: 1px solid var(--pst-color-border)
}
```

It adjusts for either choice of theme 
![image](https://github.com/pandas-dev/pandas/assets/18087952/3901b088-9a21-4bcd-af93-66ef54999de8)
![image](https://github.com/pandas-dev/pandas/assets/18087952/49258d56-bd2c-410e-900d-564d65b7d9d5)

For the button instead I suggest the following change : 
```diff
/* line 271 of the file pandas/doc/source/_static/css/getting_started.css */

.tutorial-card .gs-badge-link a {
- color: var(--pst-color-text-base); 
+ color: var(--pst-color-primary-text);
  text-decoration: none;
}
```
It adjust for either choice of theme
![image](https://github.com/pandas-dev/pandas/assets/18087952/74a4b92e-e740-4b61-9c9c-4af0c557d2ef)
![image](https://github.com/pandas-dev/pandas/assets/18087952/0c66120b-480e-4352-b45b-0633d8a5a84d)

**Comment by Aloqeely** [comment]
Sounds good to me, I'm guessing you meant to link to https://pandas.pydata.org/docs/getting_started/index.html#intro-to-pandas
