### ISSUE TITLE
BUG: regression, is_unique is incorrect since pandas 2.1.0

### ISSUE THREAD

**Issue by morotti** [pandas-dev/pandas#57911]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
print("pandas version", pd.__version__)

values = [1, 1, 2, 3, 4]
index = pd.Index(values)

print("===========")
print(index)
print("is_unique=", index.is_unique)

filtered_index = index[2:].copy()

print("===========")
print(filtered_index)
print("is_unique=", filtered_index.is_unique)


index = pd.Index(values)
filtered_index = index[2:].copy()

print("===========")
print(filtered_index)
print("is_unique=", filtered_index.is_unique)
```

### Issue Description

Hello, 

We found a regression, `index.is_unique` is incorrect since pandas 2.1.0.

I looked for open issues but did not find any fix or existing discussion.
Having a look at the changelog, there were lots of changes in 2.1.0 to introduce copy-on-write optimizations on the index. 
I think the issue could be related to that, my best guess, maybe `index[2:]` cached something from the original `index` that is no longer correct?

Attaching a simple repro, it's very easy to reproduce. :)

Thank you.

### Expected Behavior

```
pandas version 1.5.3
===========
Int64Index([1, 1, 2, 3, 4], dtype='int64')
is_unique= False
===========
Int64Index([2, 3, 4], dtype='int64')
is_unique= True
===========
Int64Index([2, 3, 4], dtype='int64')
is_unique= True
```

```
pandas version 2.2.1
===========
Index([1, 1, 2, 3, 4], dtype='int64')
is_unique= False
===========
Index([2, 3, 4], dtype='int64')
is_unique= False    # <---------------- INCORRECT
===========
Index([2, 3, 4], dtype='int64')
is_unique= True
```

### Installed Versions

tested on:

* pandas 1.5.3: PASS
* pandas 2.0.0: PASS
* pandas 2.0.3: PASS
* pandas 2.1.0: INCORRECT
* pandas 2.1.4: INCORRECT
* pandas 2.2.1 (latest): INCORRECT

**Comment by Aloqeely** [comment]
> ### Reproducible Example
> ```python
> import pandas as pd
> print("pandas version", pd.__version__)
> 
> values = [1, 1, 2, 3, 4]
> index = pd.Index(values)
> 
> print("===========")
> print(index)
> print("is_unique=", index.is_unique)
> 
> filtered_index = index[2:].copy()
> 
> print("===========")
> print(filtered_index)
> print("is_unique=", filtered_index.is_unique)
> 
> 
> index = pd.Index(values)
> filtered_index = index[2:].copy()
> 
> print("===========")
> print(filtered_index)
> print("is_unique=", filtered_index.is_unique)
> ```

It's worth noting that performing a deep copy `index[2:].copy(deep=True)` during initial assignment to `filtered_index` results in `filtered_index.is_unique` returning True

**Comment by Aloqeely** [comment]
While this is a lazy fix, I've found that in `pandas/_libs/index.pyx` if we omit the functionality of `IndexEngine`'s  `_update_from_sliced` method (such that `self.need_unique_check` and `self.need_monotonic_check` = 1), it causes `is_unique` to work as expected and all related tests pass

**Comment by lithomas1** [comment]
Hi, I can reproduce this on main - tentatively marking as for 2.2.2.

I haven't looked into this further myself - but further investigation/PRs would be welcome.

**Comment by rob-sil** [comment]
take

**Comment by morotti** [comment]
thank you for working on a fix,

would it be possible to roll the fix to the 2.1.x branch as well? 
it would be really helpful since the regression was introduced with 2.1.0

**Comment by phofl** [comment]
We don't support the 2.1.x branch anymore, we will only release this on 2.2.x

**Comment by Aloqeely** [comment]
Thanks @morotti! There's an open PR for fixing this bug at #57958, but it has not been merged yet
