### ISSUE TITLE
BUG: Groupby median on timedelta column with NaT returns odd value

### ISSUE THREAD

**Issue by goto-loop** [pandas-dev/pandas#57926]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({"label": ["foo", "foo"], "timedelta": [pd.NaT, pd.Timedelta("1d")]})

print(df.groupby("label")["timedelta"].median())
```

### Issue Description

When calculating the median of a timedelta column in a grouped DataFrame, which contains a `NaT` value, Pandas returns a strange value:

```python
import pandas as pd

df = pd.DataFrame({"label": ["foo", "foo"], "timedelta": [pd.NaT, pd.Timedelta("1d")]})

print(df.groupby("label")["timedelta"].median())
```
```
label
foo   -53376 days +12:06:21.572612096
Name: timedelta, dtype: timedelta64[ns]
```

It looks to me like the same issue as described in #10040, but with groupby.

### Expected Behavior

If you calculate the median directly on the timedelta column, without the groupby, the output is as expected:

```python
import pandas as pd

df = pd.DataFrame({"label": ["foo", "foo"], "timedelta": [pd.NaT, pd.Timedelta("1d")]})

print(df["timedelta"].median())
```
```
1 days 00:00:00
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : bdc79c146c2e32f2cab629be240f01658cfb6cc2
python                : 3.12.2.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.5.0-26-generic
Version               : #26-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar  5 21:19:28 UTC 2024
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.1
numpy                 : 1.26.4
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 68.2.2
pip                   : 23.3.1
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.3
IPython               : 8.20.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.2
bottleneck            : 1.3.7
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : 3.8.0
numba                 : None
numexpr               : 2.8.7
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 15.0.1
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.12.0
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2023.3
qtpy                  : None
pyqt5                 : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report, confirmed on main. Further investigations and PRs to fix are welcome!
