### ISSUE TITLE
RFE: move away from deprecated `html5lib`

### ISSUE THREAD

**Issue by kloczek** [pandas-dev/pandas#57932]
### Feature Type

- [ ] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [X] Removing existing functionality in pandas

### Problem Description

**Is your feature request related to a problem? Please describe.**
It would be nice tu cut tail of some legacy modules decencies.
One of those modules is `html5lib`.

`pandas` only optionally depends on  `html5lib` but I think that ATM even that optional dependency can be removed like it has been done ~2 years ago wit pip https://github.com/pypa/pip/pull/11259

### Feature Description

Cut tail of some legacy modules dependenies.

### Alternative Solutions

N/A

**Comment by lithomas1** [comment]
Can you elaborate more?

Has Python's stdlib ``html.parser`` caught up to ``html5lib``?

Looking at bs4's docs, it looks like html5lib is more lenient than the stdlib/lxml (which might be one reason people want to use it)

<img width="822" alt="image" src="https://github.com/pandas-dev/pandas/assets/47963215/e48bb106-ef40-42a8-80a5-ec141e06befc">

**Comment by GAuravY19** [comment]
Can you clarify more clearly what is supposed to be done in this issue ?

**Comment by mroeschke** [comment]
Thanks for the suggestion, but it appears this suggestion hasn't gained much traction and html5lib still provides some utility for users so closing
