### ISSUE TITLE
DOC: Doc page for DataFrame.to_numpy missing only for 2.2

### ISSUE THREAD

**Issue by cjerdonek** [pandas-dev/pandas#57931]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html (scroll to `to_numpy` below and see that there is no hyperlink)

### Documentation problem

There is no doc page for `DataFrame.to_numpy` for 2.2 (but there is for 2.1 and dev). One way to see this is to go to the page for 2.1, and then use the pull-down at the top to toggle to 2.2: https://pandas.pydata.org/pandas-docs/version/2.1/reference/api/pandas.DataFrame.to_numpy.html
It results in a 404. This also causes 404's e.g. on StackOverflow posts that link to the page.

### Suggested fix for documentation

It looks like this PR needs to be backported: https://github.com/pandas-dev/pandas/pull/57029

**Comment by yukikitayama** [comment]
take

**Comment by lithomas1** [comment]
I opened #57940 to do the backport, but I'm not sure if it's actually necessary.

(I've asked another maintainer on there)

@yukikitayama 
Sorry for barging in here, I just wanted to do this personally since backporting is usually done with our automated backport bot - and is tricky/unnecessary to do by hand.

If you want, I can help you find another issue to work on.

**Comment by cjerdonek** [comment]
> I opened #57940 to do the backport, but I'm not sure if it's actually necessary.
> 
> (I've asked another maintainer on there)

I will just say, as an end-user, it was confusing that the doc page was 404-ing when toggling the API page to the stable release. It made it look like the method was removed in 2.2.

**Comment by yukikitayama** [comment]
@lithomas1 Sure, I will unassign me.
