### ISSUE TITLE
BUG: install pandas on embedded python 3.8 win32 successful, but failed to `import pandas`

### ISSUE THREAD

**Issue by l1t1** [pandas-dev/pandas#57963]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
pip install pandas


import pandas

or

import numpy

or

import duckdb
print(duckdb.sql("select 1 a").df())
```

### Issue Description

`pip install pandas` on embedded python 3.8 win32 successful, but failed to `import pandas`

import failed, it pops an error message box and exit. 
numpy also failed. 
even no import lines, other modules returns a dataframe, also failed. 

### Expected Behavior

```python
import pandas
```
it works as normal

### Installed Versions

<details>
pandas-2.0.3

</details>

**Comment by lithomas1** [comment]
Can you provide a traceback?

**Comment by l1t1** [comment]
how to  make a traceback?

**Comment by lithomas1** [comment]
What's the error that you get when you do ``import pandas``?

**Comment by phofl** [comment]
Please use the newest version of pandas (which will also require a newer python version). We don't support 2.0.3 anymore

**Comment by l1t1** [comment]
Python 3.8 is the latest version on Windows 7.
of course, the os is also out of support.

**Comment by phofl** [comment]
Interesting, I didn't know the windows python part. Thanks.

There is nothing we can do then. It is likely that it is somehow related to NumPy if it also failed, that needs to work first before worrying about pandas makes sense

**Comment by RicardoHzSz** [comment]
install Numpy 1.23.5, it works flawlessly
