### ISSUE TITLE
BUILD:  import pandas error (C extension: DLL load failed) in Python 2.7.15

### ISSUE THREAD

**Issue by 1990chs** [pandas-dev/pandas#57982]
### Installation check

- [x] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Windows-10-10.0.19041-SP0

### Installation Method

pip install

### pandas Version

0.24.2

### Python Version

2.7.15

### Installation Logs

<details>

C:\SIMULIA\pip_abaqus>abaqus python -m pip install pandas
:: WARNING: setvars.bat has already been run. Skipping re-execution.
   To force a re-execution of setvars.bat, use the '--force' option.
   Using '--force' can result in excessive use of your environment variables.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pandas
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/61/57/6c233cc63597c6aa6337e717bdeabf791e8b618e9c893922a223e4e41cf4/pandas-0.24.2-cp27-cp27m-win_amd64.whl (8.3 MB)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\simulia\estproducts\2020\win_b64\tools\smapy\python2.7\lib\site-packages (from pandas) (2.8.0)
Requirement already satisfied: pytz>=2011k in c:\simulia\estproducts\2020\win_b64\tools\smapy\python2.7\lib\site-packages (from pandas) (2018.9)
Requirement already satisfied: numpy>=1.12.0 in c:\simulia\estproducts\2020\win_b64\tools\smapy\python2.7\lib\site-packages (from pandas) (1.15.4)
Installing collected packages: pandas
Successfully installed pandas-0.24.2
</details>

After install , import pandas error:
```
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "SMAPython\SMAPytLibPy.m\src\site.py", line 120, in _numpyHook
  File "C:\SIMULIA\EstProducts\2020\win_b64\tools\SMApy\python2.7\lib\site-packages\pandas\__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: DLL load failed: The specified module could not be found. not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
```

**Comment by lithomas1** [comment]
Both pandas 0.24 and Python 2.7.15 have been out of support for a while, so I don't think we'll be able to help with this issue in particular

Are you able to use a new Python/pandas version?

**Comment by phofl** [comment]
agree with @lithomas1, we don't support those versions anymore.

**Comment by 1990chs** [comment]
> Both pandas 0.24 and Python 2.7.15 have been out of support for a while, so I don't think we'll be able to help with this issue in particular
> 
> Are you able to use a new Python/pandas version?

It's sad, this python version within in abaqus software, it can not update to python 3.

**Comment by SMubasshar** [comment]
Hi @1990chs, 
Did you get the issue resolved later? I am also having the same error. I have Abaqus 2021, and just started learning it. I installed previous version of pip and pandas and when i run .py files i also get the same error.
