### ISSUE TITLE
BUG: Performing groupby with `as_index=False` when `df.columns.name` is not None drops the name

### ISSUE THREAD

**Issue by sfc-gh-joshi** [pandas-dev/pandas#58024]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame(
    [[1, 2, 3]],
    columns=pd.Index(["A", "B", "C"], name="alpha")
)
df.groupby(by="A", as_index=False)["B"].sum()
```

### Issue Description

Output of the above example:
```
>>> df
alpha  A  B  C
0      1  2  3
>>> df.groupby(by="A", as_index=False)["B"].sum()
   A  B
0  1  2
```

The `name` field of the columns `Index` object is dropped after the groupby operation.
```
>>> df.groupby(by="A", as_index=False)["B"].sum().columns
Index(['A', 'B'], dtype='object')
```

In pandas 1.5, the name was retained:
```
>>> pd.__version__
'1.5.3'
>>> df.groupby(by="A", as_index=False)["B"].sum()
alpha  A  B
0      1  2
>>> df.groupby(by="A", as_index=False)["B"].sum().columns
Index(['A', 'B'], dtype='object', name='alpha')
```

### Expected Behavior

It is unclear whether this change was intentional between pandas 1.5/2.0; I could not find any mention of this in the issue tracker or release notes. If this was intentional, it should be mentioned briefly in groupby documentation; if not, then it should be fixed to preserve the name as before.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 7fe86b67d3782d0c35b9284900e4aa9dd827718a
python                : 3.11.7.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 23.4.0
Version               : Darwin Kernel Version 23.4.0: Wed Feb 21 21:45:49 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6020
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 3.0.0.dev0+263.g7fe86b67d3
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.8.2
setuptools            : 68.2.2
pip                   : 23.3.1
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 15.0.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2023.4
qtpy                  : None
pyqt5                 : None
</details>

**Comment by rhshadrach** [comment]
Thanks for the report! This was changed in https://github.com/pandas-dev/pandas/pull/50744 and should have been noted in a whatsnew. As noted in that PR, by dropping `name`, we get consistency between `df["B"].groupby(by=...).sum()` and `df.groupby(by=...)["B"].sum()` (with or without `as_index=False`). More explicitly, I think Series selection in groupby should act similar to Series selection for a DataFrame, and as such the current behavior appears correct to me.

Note that if you use `[["B"]]` instead, the name is preserved (same as doing `df[["B"]]`).

I don't believe there is a section detailing column selection in the groupby User Guide. I am in favor of a small section on this, and the name could be mentioned there.

**Comment by shriyakalakata** [comment]
take

**Comment by shriyakalakata** [comment]
Hey @rhshadrach! I wanted to clarify what's expected from this task. I see that there is a ['column selection in GroupBy'](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#dataframe-column-selection-in-groupby) in the groupby user guide already. I was thinking I could do the following:
* Add a note in this section about the `name`
* Include an example of grouping by a certain column and using another column for aggregation

**Comment by rhshadrach** [comment]
Thanks @shriyakalakata - indeed I missed this section!

> * Add a note in this section about the `name`

This sounds good.

> * Include an example of grouping by a certain column and using another column for aggregation

I don't think this is necessary - there are already examples of this throughout the groupby docs.
