### ISSUE TITLE
BUG: Numpy not directly usable in DataFrame.eval and DataFrame.query

### ISSUE THREAD

**Issue by domsmrz** [pandas-dev/pandas#58041]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import numpy as np
import pandas as pd

df = pd.Series([0.2, 1.5, 2.8], name="a").to_frame()
res = df.eval("@np.floor(a)")
```

### Issue Description

The evaluation of `@np.floor` will fail as `np.ndim` is a function.

### Expected Behavior

To floor be successfully computed.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.11.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 6.6.13-1rodete3-amd64
Version          : #1 SMP PREEMPT_DYNAMIC Debian 6.6.13-1rodete3 (2024-03-04)
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.24.2
pytz             : 2023.3.post1
dateutil         : 2.8.2
setuptools       : 68.1.2
pip              : 23.3
Cython           : 3.0.8
pytest           : 7.4.4
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 5.1.0
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.20.0
pandas_datareader: None
bs4              : 4.12.3
bottleneck       : 1.3.5
brotli           : 1.1.0
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.3
numba            : 0.57.1
numexpr          : 2.9.0
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : 
sqlalchemy       : None
tables           : 3.7.0
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by domsmrz** [comment]
FWIW I essentially have the fix ready if we want to fix the issue

**Comment by rhshadrach** [comment]
Do we currently document or test using functions via `@` here? If we do, then I believe this is a non-controversial fix. However if we don't, we'd be expanding the API and for that we'd need agreement, documentation, and tests. Still, even in such a case I'm very positive here. I've been toying around with it and it seems to behave quite well.

**Comment by rhshadrach** [comment]
eval contains explicit code for handling functions like this, so this is supported, even if documentation / tests are lacking. I do see one test added from https://github.com/pandas-dev/pandas/pull/32460 (might be missing others).

**Comment by domsmrz** [comment]
Thanks for taking a look.

Just for the completion sake, this is not really about allowing functions into `eval` as:
1. The same problem is with `np.inf` which is a constant
2. The problem can we worked around by intermediate assignment: `np_floor = np.floor; df.eval(@np_floor(a))`

But I digress; I've sent the PR.
