### ISSUE TITLE
DOC: Enforce Numpy Docstring Validation | pandas.Datetime

### ISSUE THREAD

**Issue by jordan-d-murphy** [pandas-dev/pandas#58066]
[DOC: Enforce Numpy Docstring Validation (Parent Issue) #58063](https://github.com/pandas-dev/pandas/issues/58063)

Pandas has a script for validating docstrings in code_checks.sh. Currently, some methods fail some of these checks.

### pandas.Datetime

https://github.com/pandas-dev/pandas/blob/c468028f5c2398c04d355cef7a8b6a3952620de2/ci/code_checks.sh#L135-L167

**The task is:**

1. take 1-5 methods

2. run: `scripts/validate_docstrings.py --format=actions <method-name>`

**example command:** `scripts/validate_docstrings.py --format=actions pandas.Categorical.__array__` 
**example output:** 
```
################################################################################
################################## Validation ##################################
################################################################################

2 Errors found for `pandas.Categorical.__array__`:
	ES01	No extended summary found
	SA01	See Also section not found
```

3. check if validation docstrings passes for those methods, and if it’s necessary fix the docstrings according to whatever error is reported. **Note:** We've chosen to ignore ES01 errors, these are not required to be fixed. 

4. remove those methods from code_checks.sh if all errors are cleared and the docstring is correct, otherwise, remove the specific error that was fixed from the list of errors for that method. 

5. commit, push, open pull request

Please don't comment `take` as multiple people can work on this issue. You also don't need to ask for permission to work on this, just comment on which methods are you going to work : ) 

If you're new contributor, please check the [contributing guide](https://pandas.pydata.org/docs/dev/development/contributing.html)

thanks @datapythonista for the inspiration for this issue!

**Comment by ThomasBur** [comment]
`--error` was removed as an argument of `scripts/validate_docstrings.py` in #57879 so the example command won't work.

People can exclude it, instead checking with:
`scripts/validate_docstrings.py --format=actions <method-name>`

**Comment by iridiium** [comment]
Taking:
```
pandas.DatetimeIndex.to_period
pandas.DatetimeIndex.to_pydatetime
```

**Comment by KeiOshima** [comment]
taking: 

pandas.DatetimeIndex.date
pandas.DatetimeIndex.day

**Comment by shriyakalakata** [comment]
Working on `pandas.DatetimeIndex.day_name`, `pandas.DatetimeIndex.month_name`

**Comment by KeiOshima** [comment]
working on 
```
pandas.DatetimeIndex.hour
pandas.DatetimeIndex.minute
pandas.DatetimeIndex.second
```

**Comment by KeiOshima** [comment]
working on 
```
pandas.DatetimeIndex.day 
pandas.DatetimeIndex.nanosecond
pandas.DatetimeIndex.microsecond 
```

**Comment by gboeker** [comment]
working on
```
pandas.DatetimeIndex.quarter
pandas.DatetimeIndex.round
pandas.DatetimeIndex.snap
pandas.DatetimeIndex.std
pandas.DatetimeIndex.time
pandas.DatetimeIndex.timetz
```

**Comment by KeiOshima** [comment]
working on 
```
pandas.DatetimeIndex.ceil
pandas.DatetimeIndex.floor
pandas.DatetimeIndex.tz
```

**Comment by KeiOshima** [comment]
Working on 
```
pandas.DatetimeIndex.day_of_year
pandas.DatetimeIndex.is_leap_year
pandas.DatetimeIndex.inferred_freq 
```

**Comment by tuhinsharma121** [comment]
Now working on 

```
 -i "pandas.DatetimeIndex.tz_convert RT03" \ 
-i "pandas.DatetimeIndex.indexer_between_time RT03" \
-i "pandas.DatetimeIndex.freqstr SA01" \
-i "pandas.DatetimeIndex.dayofyear SA01" \
```

**Comment by tuhinsharma121** [comment]
working on

```
        -i "pandas.DatetimeIndex.std PR01,RT03" \
        -i "pandas.DatetimeIndex.to_period RT03" \
        -i "pandas.DatetimeIndex.to_pydatetime RT03,SA01" \
```

**Comment by tuhinsharma121** [comment]
working on

```
        -i "pandas.DatetimeIndex.indexer_at_time PR01,RT03" \
        -i "pandas.DatetimeIndex.snap PR01,RT03" \
```
