### ISSUE TITLE
DOC: Enforce Numpy Docstring Validation | pandas.Categorical

### ISSUE THREAD

**Issue by jordan-d-murphy** [pandas-dev/pandas#58064]
[DOC: Enforce Numpy Docstring Validation (Parent Issue) #58063](https://github.com/pandas-dev/pandas/issues/58063)

Pandas has a script for validating docstrings in code_checks.sh. Currently, some methods fail some of these checks.

### pandas.Categorical

https://github.com/pandas-dev/pandas/blob/c468028f5c2398c04d355cef7a8b6a3952620de2/ci/code_checks.sh#L73-L81

**The task is:**

1. take 1-5 methods

2. run: `scripts/validate_docstrings.py --format=actions <method-name>`

**example command:** `scripts/validate_docstrings.py --format=actions pandas.Categorical.__array__` 
**example output:** 
```
################################################################################
################################## Validation ##################################
################################################################################

2 Errors found for `pandas.Categorical.__array__`:
	ES01	No extended summary found
	SA01	See Also section not found
```

3. check if validation docstrings passes for those methods, and if it’s necessary fix the docstrings according to whatever error is reported. **Note:** We've chosen to ignore ES01 errors, these are not required to be fixed. 

4. remove those methods from code_checks.sh if all errors are cleared and the docstring is correct, otherwise, remove the specific error that was fixed from the list of errors for that method. 

5. commit, push, open pull request

Please don't comment `take` as multiple people can work on this issue. You also don't need to ask for permission to work on this, just comment on which methods are you going to work : ) 

If you're new contributor, please check the [contributing guide](https://pandas.pydata.org/docs/dev/development/contributing.html)

thanks @datapythonista for the inspiration for this issue!

**Comment by Aloqeely** [comment]
Alright, I will attempt to work on all of these methods.

**Comment by jordan-d-murphy** [comment]
Awesome! Thank you for the help ☺️
