### ISSUE TITLE
DOC: Enforce Numpy Docstring Validation | pandas.DataFrame

### ISSUE THREAD

**Issue by jordan-d-murphy** [pandas-dev/pandas#58065]
[DOC: Enforce Numpy Docstring Validation (Parent Issue) #58063](https://github.com/pandas-dev/pandas/issues/58063)

Pandas has a script for validating docstrings in code_checks.sh. Currently, some methods fail some of these checks.

### pandas.DataFrame

https://github.com/pandas-dev/pandas/blob/c468028f5c2398c04d355cef7a8b6a3952620de2/ci/code_checks.sh#L82-L134

**The task is:**

1. take 1-5 methods

2. run: `scripts/validate_docstrings.py --format=actions <method-name>`

**example command:** `scripts/validate_docstrings.py --format=actions pandas.Categorical.__array__` 
**example output:** 
```
################################################################################
################################## Validation ##################################
################################################################################

2 Errors found for `pandas.Categorical.__array__`:
	ES01	No extended summary found
	SA01	See Also section not found
```

3. check if validation docstrings passes for those methods, and if it’s necessary fix the docstrings according to whatever error is reported. **Note:** We've chosen to ignore ES01 errors, these are not required to be fixed. 

4. remove those methods from code_checks.sh if all errors are cleared and the docstring is correct, otherwise, remove the specific error that was fixed from the list of errors for that method. 

5. commit, push, open pull request

Please don't comment `take` as multiple people can work on this issue. You also don't need to ask for permission to work on this, just comment on which methods are you going to work : ) 

If you're new contributor, please check the [contributing guide](https://pandas.pydata.org/docs/dev/development/contributing.html)

thanks @datapythonista for the inspiration for this issue!

**Comment by YashpalAhlawat** [comment]
opened a fix for pandas.DataFrame.where

**Comment by Aloqeely** [comment]
Going to remove `pandas.DataFrame.swapaxes`, `pandas.DataFrame.pad` and `pandas.DataFrame.backfill` which are all deprecated

**Comment by bergnerjonas** [comment]
Will work on `pandas.DataFrame.unstack RT03`, `pandas.DataFrame.value_counts` and  `pandas.DataFrame.var`

**Comment by bergnerjonas** [comment]
Continue with `pandas.DataFrame.to_period` ,`pandas.DataFrame.to_timestamp` ,`pandas.DataFrame.tz_convert`

**Comment by shriyakalakata** [comment]
Working on `pandas.DataFrame.assign`, `pandas.DataFrame.bfill`, and `pandas.DataFrame.ffill`

**Comment by shriyakalakata** [comment]
Will work on `pandas.DataFrame.get`, `pandas.DataFrame.hist`, `pandas.DataFrame.dtypes`

**Comment by shriyakalakata** [comment]
Will work on `pandas.DataFrame.copy`, `pandas.DataFrame.first_valid_index`,  and `pandas.DataFrame.keys`

**Comment by gboeker** [comment]
Working on `pandas.DataFrame.sparse`, `pandas.DataFrame.sparse.density`, `pandas.DataFrame.sparse.from_spmatrix`, `pandas.DataFrame.sparse.to_coo`, and `pandas.DataFrame.sparse.to_dense`

**Comment by KeiOshima** [comment]
Working on:
```
pandas.DataFrame.axes
pandas.DataFrame.columns
pandas.DataFrame.pop
```

**Comment by shriyakalakata** [comment]
Working on `pandas.DataFrame.kurt` and `pandas.DataFrame.kurtosis`

**Comment by KeiOshima** [comment]
working on: 
```
pandas.DataFrame.to_markdown
pandas.DataFrame.to_feather 
```

**Comment by gboeker** [comment]
working on
```
pandas.DataFrame.mean
pandas.DataFrame.median
pandas.DataFrame.plot
pandas.DataFrame.pop
```

**Comment by gboeker** [comment]
working on
```
pandas.DataFrame.__dataframe__
pandas.DataFrame.__iter__
pandas.DataFrame.columns
pandas.DataFrame.droplevel
```

**Comment by KeiOshima** [comment]
working on 
```
pandas.DataFrame.max
pandas.DataFrame.min
```

**Comment by shriyakalakata** [comment]
Working on         
```
-i "pandas.DataFrame.hist RT03" \
-i "pandas.DataFrame.infer_objects RT03" \
-i "pandas.DataFrame.reorder_levels SA01" \
-i "pandas.DataFrame.to_parquet RT03" \
```

**Comment by jordan-d-murphy** [comment]
Awesome! Thanks for all the work on these, I've been a bit busy lately but I'll open some new issues for the remaining ones

**Comment by tuhinsharma121** [comment]
I am working on 

```
        -i "pandas.DataFrame.__dataframe__ SA01" \
        -i "pandas.DataFrame.at_time PR01" \
        -i "pandas.DataFrame.kurt RT03,SA01" \
        -i "pandas.DataFrame.kurtosis RT03,SA01" \
```

**Comment by tuhinsharma121** [comment]
I am working on the following

```
        -i "pandas.DataFrame.max RT03" \
        -i "pandas.DataFrame.mean RT03,SA01" \
        -i "pandas.DataFrame.median RT03,SA01" \
        -i "pandas.DataFrame.min RT03" \
        -i "pandas.DataFrame.plot PR02,SA01" \
```

**Comment by tuhinsharma121** [comment]
working on 
```
        -i "pandas.DataFrame.std PR01,RT03,SA01" \
        -i "pandas.DataFrame.sum RT03" \
        -i "pandas.DataFrame.swaplevel SA01" \
        -i "pandas.DataFrame.to_markdown SA01" \
        -i "pandas.DataFrame.var PR01,RT03,SA01" \
```

**Comment by BDixon808** [comment]
I will check out:

        -i "pandas.DataFrame.max RT03" \
        -i "pandas.DataFrame.mean RT03,SA01" \
        -i "pandas.DataFrame.median RT03,SA01" \
        -i "pandas.DataFrame.min RT03" \

**Comment by anishfish2** [comment]
I'll check out: 

'''
        -i "pandas.DataFrame.plot PR02,SA01" \
'''

**Comment by shindelr** [comment]
I noticed that the following docstrings are still missing extended summaries:
 `pandas.DataFrame.bfill`
`pandas.DataFrame.columns`

I'll work on them

**Comment by enesyesil** [comment]
Hey, is this issue open? would like contribute as a beginner. Thank you

**Comment by Aloqeely** [comment]
Yes it's still open. Good luck!

**Comment by shriyase** [comment]
Hey, I'd like to contribute to this issue if it's still open

**Comment by Aloqeely** [comment]
Yes! You can see `ci/code_checks.sh` for all the docstrings that need to be fixed.

**Comment by shriyase** [comment]
I will work on:
`-i "pandas.DataFrame.max RT03" \
    -i "pandas.DataFrame.mean RT03,SA01" \
    -i "pandas.DataFrame.median RT03,SA01" \
    -i "pandas.DataFrame.min RT03" \`

**Comment by shriyase** [comment]
I will work on `-i "pandas.DataFrame.value_counts RT03" \`, 
       ` -i "pandas.DataFrame.var PR01,RT03,SA01" \`, 
        `-i "pandas.DataFrame.where RT03" \`,  ` -i "pandas.DataFrame.backfill PR01,SA01" \` and
   `     -i "pandas.DataFrame.bfill SA01" \`

**Comment by shriyase** [comment]
Is it only that the methods from the original issue post need to be checked? Or any methods in `ci/code_checks.sh`? Also when i check a few of the methods, I get additional errors that aren't listed in the documentation? Do I add those error codes too?

**Comment by Aloqeely** [comment]
You can fix any method in that file.

> Also when i check a few of the methods, I get additional errors that aren't listed in the documentation?

Not sure what you mean by additional errors.

**Comment by CollinClifford** [comment]
Does the validate_docstrings.py validation not work for anyone else?  I'm getting an error on line 217, stating that there isn't enough values to unpack (expected 4 got 1) for all of the docstrings I've checked.

**Comment by Aloqeely** [comment]
It works for me. Can you post the command you ran and the error message?

**Comment by deekapila** [comment]
take

**Comment by ktseng4096** [comment]
I'll work on  `pandas.Series.to_dict` and `pandas.Series.to_frame`

**Comment by Aditya060** [comment]
> Does the validate_docstrings.py validation not work for anyone else? I'm getting an error on line 217, stating that there isn't enough values to unpack (expected 4 got 1) for all of the docstrings I've checked.

Try to install flake8 in the virtual environment that you are working in. That fixed the issue for me.

**Comment by deekapila** [comment]
hi, I have a question. Is this issue only for pandas.DataFrame.xxxx methods or we can can use this to fix other as well. If there are no errors for pandas.DataFrame.xxx method, should we remove this from code_checks.sh ? e.g. pandas.DataFrae.copy says 'Docstring for "pandas.DataFrame.copy: correct. :)
