### ISSUE TITLE
ENH: Series.map() that works with a dictionary of key-list pairs

### ISSUE THREAD

**Issue by kbmorales** [pandas-dev/pandas#58108]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Dictionaries are perfect for mapping, but I often have the situation where I need to reassign multiple values to a single key value. However, Series.map() does the opposite, by searching through the keys and assigning the values.

### Feature Description

I use this currently:

```
def flip_map(col, dct):
    """
    Inverts a dictionary of key, value pairs where the values are lists
    """
    exp_dct = pd.Series(dct).explode()
    flip_dct = dict(zip(exp_dct,exp_dct.index))
   
    return col.map(flip_dct).fillna(col)
```

### Alternative Solutions

I think the above using base python and Series.explode() should do it

**Comment by Aloqeely** [comment]
Thanks for the request - I think there are many ways to modify your dictionary format before passing it to `Series.map` to get your desired result and I also don't think that dictionary format is particularly readable, so I'm not a fan of this

`flip_map` is one way to achieve your desired result, but a nested loop will do the job and I think is more readable:
```python
flipped = {}
for key, value_list in dictionary.items():
    for item in value_list:
        flipped[item] = key
```
And if you want a 1 liner, you can achieve that with a dict comprehension:
```python
flipped = {item: key for key, value_list in dictionary.items() for item in value_list}
```

**Comment by Aloqeely** [comment]
Closing as it seems not many people are interested in this feature.
