### ISSUE TITLE
ENH: function to concatenate columns with a separator

### ISSUE THREAD

**Issue by hutch3232** [pandas-dev/pandas#58113]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I am writing a script that will dynamically take a `list` of column names and I'd like to concatenate the `pandas.DataFrame` columns with a separator of my choice. 

For now, I opted to go with this approach: https://stackoverflow.com/a/59618989/9244371
```python
df[['Code', 'Period']].astype(str).agg('_'.join, axis=1)
```
This definitely works, but in my opinion it is a little verbose/round-about. It also felt quite slow compared to (if I had fixed columns) doing:
```python
df['Code'].astype(str) + "_" + df['Period'].astype(str)
```

### Feature Description

`polars` has a function that accomplish what I would like `pandas` to have:
https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.concat_str.html

### Alternative Solutions

Googling around it seems this is a very common question with an enormous number of possible solutions.

Here are a few pages of many:
https://stackoverflow.com/questions/33098383/merge-multiple-column-values-into-one-column-in-python-pandas
https://stackoverflow.com/questions/19377969/combine-two-columns-of-text-in-pandas-dataframe
https://stackoverflow.com/questions/59618562/concatenating-string-columns-in-pandas

**Comment by crogers2023** [comment]
Can I try to implement this?

**Comment by mroeschke** [comment]
Thanks for the issue, but it appears this hasn't gotten traction in a while so closing
