### ISSUE TITLE
ENH: pd.read_csv() does not reture back datetime dtypes after pd.to_csv()

### ISSUE THREAD

**Issue by weikhor** [pandas-dev/pandas#58196]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Code
```
# Write to file
filename = 'data.csv'
data_write_df = pd.DataFrame( pd.to_datetime(['1996-05-10', '1992-02-15', '1987-11-20']),columns=['date'])
print(data_write_df['date'])
data_write_df.to_csv(filename)

print('-----')

# Read from file
data_read_df = pd.read_csv(filename, index_col=0)
print(data_read_df['date'])
```
Result
```
0   1996-05-10
1   1992-02-15
2   1987-11-20
Name: date, dtype: datetime64[ns]
-----
0    1996-05-10
1    1992-02-15
2    1987-11-20
Name: date, dtype: object
```

Expected
The dataframe returned from pd.read_csv should be same as original dataframe

### Feature Description

pd.read_csv does not convert back datetime64[ns] type  after reading csv file  

### Alternative Solutions

None

**Comment by rhshadrach** [comment]
Thanks for the report - this is what the `parse_dates` argument is for.

 ```
data_read_df = pd.read_csv(filename, index_col=0, parse_dates=[1])
print(data_read_df['date'])
# 0   1996-05-10
# 1   1992-02-15
# 2   1987-11-20
# Name: date, dtype: datetime64[ns]
```

In general, CSV cannot preserve dtypes by default because that information is lost.

**Comment by weikhor** [comment]
Thank you.
