### ISSUE TITLE
BUILD: Pandas 2.2.2 install fails from Poetry (attempts meson build) 2.2.1 installs fine.

### ISSUE THREAD

**Issue by markclare1992** [pandas-dev/pandas#58219]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

macOS-14.3.1-arm64-arm-64bit

### Installation Method

Other

### pandas Version

2.2.2

### Python Version

3.10.12

### Installation Logs

<details>

[build:build] Building wheel...
  - Updating pandas (2.2.1 -> 2.2.2): Failed

  Stack trace:

  9  ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/executor.py:281 in _execute_operation
      279│ 
      280│             try:
    → 281│                 result = self._do_execute_operation(operation)
      282│             except EnvCommandError as e:
      283│                 if e.e.returncode == -2:

  8  ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/executor.py:391 in _do_execute_operation
      389│             return 0
      390│ 
    → 391│         result: int = getattr(self, f"_execute_{method}")(operation)
      392│ 
      393│         if result != 0:

  7  ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/executor.py:523 in _execute_update
      521│ 
      522│     def _execute_update(self, operation: Install | Update) -> int:
    → 523│         status_code = self._update(operation)
      524│ 
      525│         self._save_url_reference(operation)

  6  ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/executor.py:582 in _update
      580│ 
      581│     def _update(self, operation: Install | Update) -> int:
    → 582│         return self._install(operation)
      583│ 
      584│     def _remove(self, package: Package) -> int:

  5  ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/executor.py:554 in _install
      552│             archive = self._download_link(operation, Link(package.source_url))
      553│         else:
    → 554│             archive = self._download(operation)
      555│ 
      556│         operation_message = self.get_operation_message(operation)

  4  ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/executor.py:746 in _download
      744│             self._yanked_warnings.append(message)
      745│ 
    → 746│         return self._download_link(operation, link)
      747│ 
      748│     def _download_link(self, operation: Install | Update, link: Link) -> Path:

  3  ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/executor.py:781 in _download_link
      779│             self._write(operation, message)
      780│ 
    → 781│             archive = self._chef.prepare(archive, output_dir=original_archive.parent)
      782│ 
      783│         # Use the original archive to provide the correct hash.

  2  ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/chef.py:123 in prepare
      121│             return self._prepare(archive, destination=destination, editable=editable)
      122│ 
    → 123│         return self._prepare_sdist(archive, destination=output_dir)
      124│ 
      125│     def _prepare(

  1  ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/chef.py:194 in _prepare_sdist
      192│             destination.mkdir(parents=True, exist_ok=True)
      193│ 
    → 194│             return self._prepare(
      195│                 sdist_dir,
      196│                 destination,

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  + meson setup /private/var/folders/z2/z_frvr7j7f93m_vy3s4n21nh0000gq/T/tmp3nkj0luj/pandas-2.2.2 /private/var/folders/z2/z_frvr7j7f93m_vy3s4n21nh0000gq/T/tmp3nkj0luj/pandas-2.2.2/.mesonpy-wiidutn5/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=/private/var/folders/z2/z_frvr7j7f93m_vy3s4n21nh0000gq/T/tmp3nkj0luj/pandas-2.2.2/.mesonpy-wiidutn5/build/meson-python-native-file.ini
  The Meson build system
  Version: 1.2.1
  Source dir: /private/var/folders/z2/z_frvr7j7f93m_vy3s4n21nh0000gq/T/tmp3nkj0luj/pandas-2.2.2
  Build dir: /private/var/folders/z2/z_frvr7j7f93m_vy3s4n21nh0000gq/T/tmp3nkj0luj/pandas-2.2.2/.mesonpy-wiidutn5/build
  Build type: native build
  Project name: pandas
  Project version: 2.2.2
  C compiler for the host machine: cc (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.1.0.2.5)")
  C linker for the host machine: cc ld64 1022.1
  C++ compiler for the host machine: c++ (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.1.0.2.5)")
  C++ linker for the host machine: c++ ld64 1022.1
  Cython compiler for the host machine: cython (cython 3.0.5)
  Host machine cpu family: aarch64
  Host machine cpu: aarch64
  Program python found: YES (/var/folders/z2/z_frvr7j7f93m_vy3s4n21nh0000gq/T/tmpwfwrfo4z/.venv/bin/python)
  
  ../../pandas/meson.build:1:15: ERROR: Command `/var/folders/z2/z_frvr7j7f93m_vy3s4n21nh0000gq/T/tmpwfwrfo4z/.venv/bin/python -c '
  import os
  import numpy as np
  try:
      # Check if include directory is inside the pandas dir
      # e.g. a venv created inside the pandas dir
      # If so, convert it to a relative path
      incdir = os.path.relpath(np.get_include())
  except Exception:
      incdir = np.get_include()
  print(incdir)
       '` failed with status 1.
  
  A full log can be found at /private/var/folders/z2/z_frvr7j7f93m_vy3s4n21nh0000gq/T/tmp3nkj0luj/pandas-2.2.2/.mesonpy-wiidutn5/build/meson-logs/meson-log.txt

</details>

**Comment by joerick** [comment]
Looks like the macos arm64 wheel is missing for cp312 in the [pandas 2.2.2 release](https://pypi.org/project/pandas/2.2.2/#files). It is there in the [2.2.1 release](https://pypi.org/project/pandas/2.2.1/#files).

It appears some of the build jobs failed on Github Actions: https://github.com/pandas-dev/pandas/actions/runs/8635555477

**Comment by lithomas1** [comment]
Thanks for the report - the wheel should be uploaded now.

As @joerick pointed out, the upload phase on the wheels failed, so uploading the macos wheels was a manual process this time (and evidently, I forgot about 3.12 😅 ).

Let me know if there's anything else that's missing from the release.
