### ISSUE TITLE
BUG: When passing list of dataclasses mixing types to `pd.DataFrame()`, but `pd.DataFrame()` did not raise `TypeError`.

### ISSUE THREAD

**Issue by yuji38kwmt** [pandas-dev/pandas#58222]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
from dataclasses import make_dataclass

Point = make_dataclass("Point", [("x", int), ("y", int)])
Point3D = make_dataclass("Point3D", [("x", int), ("y", int), ("z", int)])

df = pd.DataFrame([Point(0, 0), Point3D(0, 0, 0)])
print(df)
```

### Issue Description

[The documentation](https://pandas.pydata.org/docs/user_guide/dsintro.html#from-a-list-of-dataclasses) said:

>Please be aware, that all values in the list should be dataclasses, mixing types in the list would result in a TypeError.

But in the above code, `pd.DataFrame()` does not raise `TypeError`.

### Expected Behavior

In the above code, `pd.DataFrame()` raise `TypeError` according to the documentation.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.1.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 5.15.146.1-microsoft-standard-WSL2
Version               : #1 SMP Thu Jan 11 04:09:03 UTC 2024
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : C.UTF-8
LOCALE                : C.UTF-8

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.8.2
setuptools            : 69.2.0
pip                   : 24.0
Cython                : None
pytest                : 8.0.2
hypothesis            : None
sphinx                : 7.2.6
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 5.1.0
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.3
IPython               : 8.21.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : 3.8.2
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.2
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2023.4
qtpy                  : None
pyqt5                 : None
</details>

**Comment by jtranquilli** [comment]
If anyone from the dev team sees this, I would love to be assigned this issue as  my first contribution to the pandas project if the triage result deems that as appropriate.

**Comment by Aloqeely** [comment]
Thanks for the report! Just to clarify, mixing dataclasses is allowed. `TypeError` is raised when mixing dataclasses with datatypes (e.g. `Point` and `string`)

**Comment by priyapandey26** [comment]
[patch](https://github.com/pandas-dev/pandas/pull/58276) create pull request and update the doc as shown in the comment!
