### ISSUE TITLE
BUG: Series.plot(kind="pie") does not respect ylabel argument

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#58239]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
ser = pd.Series([1, 2, 4], index=["a", "b", "c"], name="my_series")
ser.plot(kind="pie", ylabel=None)
```
```


### Issue Description

The plot will always show the label "my_series", regardless of if you pass ylabel=None or not.

The only way to fix this is to do:

```python
ax = ser.plot(kind="pie")
ax2.set_ylabel(None)
```

### Expected Behavior

ylabel argument should be respected

### Installed Versions

main

**Comment by abeltavares** [comment]
take

**Comment by abeltavares** [comment]
Hi @WillAyd since the default for ylabel is None, the pie will never show label if that is not defined. Will never get the name of the Series as the behavior now. Is that what is expected?

**Comment by WillAyd** [comment]
Yea I think that is correct. I don't think any of the other chart types do that, so would be good to make them all consistent

**Comment by abeltavares** [comment]
@WillAyd 
can you check the [PR](https://github.com/pandas-dev/pandas/pull/58254#event-12548506835) to close?
