### ISSUE TITLE
BUG: macOS ARM64 Binary wheels not published for v2.2.2

### ISSUE THREAD

**Issue by freakboy3742** [pandas-dev/pandas#58259]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
On Python 3.9 or Python 3.10, using an ARM64 macOS machine, attempt to `pip install pandas==2.2.2`.
```

### Issue Description

The 2.2.2 release of Pandas has not published ARM64 macOS wheels for Python 3.9 or Python 3.10. 

x86_64 macOS binary wheels for Python 3.9 and 3.10 exist.

### Expected Behavior

It should be possible to install Pandas 2.2.2 on Python 3.9 and 3.10.

### Installed Versions

N/A

**Comment by lithomas1** [comment]
Thanks, this should be uploaded now.
