### ISSUE TITLE
BUG: `read_csv` breaks on NaNs for dtype=np.float16

### ISSUE THREAD

**Issue by tscheburaschka** [pandas-dev/pandas#58264]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import io

import numpy as np
import pandas as pd

resp_text = """DATE;TIME;DATA
11.04.2024;00:00:00;-134,055
11.04.2024;00:00:01;-153,941
11.04.2024;00:00:02;-153,941
11.04.2024;00:00:03;-153,941
11.04.2024;00:00:04;nan
"""

csv_df = pd.read_csv(
    io.StringIO(resp_text),
    sep=";",
    decimal=",",
    header=0,
    dtype={"DATE": pd.StringDtype(), "TIME": pd.StringDtype(), "DATA": np.float16},
)

Traceback (most recent call last):
  File "C:\...\scratch_57.py", line 14, in <module>
    csv_df = pd.read_csv(
             ^^^^^^^^^^^^
  File "C:\...\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\Lib\site-packages\pandas\io\parsers\readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "C:\...\Lib\site-packages\pandas\io\parsers\readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 921, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 1083, in pandas._libs.parsers.TextReader._convert_column_data
  File "parsers.pyx", line 1447, in pandas._libs.parsers._maybe_upcast
KeyError: dtype('float16')



```

### Issue Description

The `read_csv()` function throws an error when dtype `np.float16` is given and the CSV-Text contains NaNs.
The error does not appear for `np.float32`. 

### Expected Behavior

The `read_csv()` function should parse NaNs fo rall numerical dtypes.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.11.7.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.14393
machine               : AMD64
processor             : Intel64 Family 6 Model 85 Stepping 0, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : de_DE.cp1252

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : 69.5.1
pip                   : 24.0
Cython                : None
pytest                : 8.1.1
hypothesis            : 6.100.1
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : 2.9.9
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 15.0.2
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>

**Comment by asishm** [comment]
Pandas does not support `float16` dtype. See https://github.com/pandas-dev/pandas/issues/56361

**Comment by mroeschke** [comment]
Thanks for the triage @asishm. Yes, float16 is not supported in pandas so this is expected not to work. Closing as a won't fix.
