### ISSUE TITLE
BUG: GroupBy.agg allows non-aggregating built-in functions

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#58284]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
In [38]: df = pd.DataFrame({"group": list("aab"), "val1": range(3)})

In [39]: df.groupby("group").agg("cumsum")
Out[39]: 
   val1
0     0
1     1
2     2

In [40]: df.groupby("group").agg(lambda x: x.cumsum())
ValueError: Must produce aggregated value
```

### Issue Description

The built-in transformation functions are allowed as arguments to `.agg`. Haven't checked yet that this is solved by @rhshadrach work in https://github.com/pandas-dev/pandas/pull/57706 

### Expected Behavior

Error for built-in functions

### Installed Versions

'3.0.0.dev0+681.g434fda08cf'

**Comment by rhshadrach** [comment]
I think of this as https://github.com/pandas-dev/pandas/issues/44845. I decided to keep it out of scope for #57706 since it could independently be done.

**Comment by WillAyd** [comment]
Ah thanks - sorry I didn't catch that. This is defintely a dupe
