### ISSUE TITLE
BUG: GroupBy.apply with as_index=False still produces a MultiIndex

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#58291]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

Assume we have this data:

```python
In [88]:   df = pd.DataFrame([
    ...:       ["group_a", 0],
    ...:       ["group_a", 2],
    ...:       ["group_b", 1],
    ...:       ["group_b", 3],
    ...:       ["group_b", 5],
    ...:   ], columns=["group", "value"])
    ...: 
    ...:   df
In [88]:   def up_to_two_rows(df: pd.DataFrame) -> pd.DataFrame:
    ...:       return df.head(2)

```

Calling .apply seems to always create a MultiIndex, even when you don't ask for the groups:

```
In [89]: df.groupby("group").apply(up_to_two_rows)
<ipython-input-89-e4954502d06d>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby("group").apply(up_to_two_rows)
Out[89]: 
             group  value
group                    
group_a 0  group_a      0
        1  group_a      2
group_b 2  group_b      1
        3  group_b      3
```

```
In [92]: df.groupby("group").apply(up_to_two_rows, include_groups=False)
Out[92]: 
           value
group           
group_a 0      0
        1      2
group_b 2      1
        3      3
```

```
In [93]: df.groupby("group", as_index=False).apply(up_to_two_rows, include_groups=False)
Out[93]: 
     value
0 0      0
  1      2
1 2      1
  3      3
```

### Issue Description

I am ultimately trying to get output that matches:

```
In [97]: df.groupby("group").apply(up_to_two_rows, include_groups=False).reset_index(level=0)
Out[97]: 
     group  value
0  group_a      0
1  group_a      2
2  group_b      1
3  group_b      3
```

But am not clear what combination of keywords is supposed to do that, if any

### Expected Behavior

```
In [97]: df.groupby("group").apply(up_to_two_rows, include_groups=False).reset_index(level=0)
Out[97]: 
     group  value
0  group_a      0
1  group_a      2
2  group_b      1
3  group_b      3
```

### Installed Versions

main

**Comment by WillAyd** [comment]
cc @rhshadrach in case you know the answer

**Comment by rhshadrach** [comment]
The code responsible for this behavior links back to https://github.com/pandas-dev/pandas/issues/5610, but this phenomenon was not discussed there. I'm +1 on your expected behavior.

More generally, there are a number of ways `as_index=False` behaves differently than `df.groupby(...as_index=True)...reset_index()`, and I think they should be the same. In fact, we should implement `as_index=False` as just a reset_index on the result. I also opened #58337 just now, which is another case where I know they can differ.

**Comment by undermyumbrella1** [comment]
According to the documention, ` as_index=False is effectively “SQL-style” grouped output`. In the case where grouping column is not explicitly selected/calculated, it will not be in the result. 
```
SELECT FLOOR(salary / 1000) AS salary_group, COUNT(*) AS employee_count
FROM employees
GROUP BY FLOOR(salary / 1000);
```

In the case of pandas, if the grouping is not direct, should the grouping be an additional column or not?
Consider the following df:
```
    A         B         C         D
2000-01-03  0.189053 -0.522748 -0.413064 -2.441467
2000-01-04  1.799707  1.144166 -0.325423  0.773807
2000-02-02  1.129228 -0.836085  1.428544 -0.667620
2000-02-03  0.153412 -0.836387 -0.222235  0.047404
```
Consider the operation on df:
```
gb = df.groupby(lambda x: x.month, as_index=False)
result = gb.apply(DataFrame.quantile, [0.4, 0.8])
```
Removing multiindex, and not having a column to indicate grouping, result is similar to
```
            A         B         C         D
0.4 -0.169760  0.073793 -0.076588 -0.421859
0.8  0.841465  1.128523  0.891656  0.410504
0.4 -0.317066 -0.809446  0.335177 -0.396717
0.8  0.839953  0.590891  0.926955  0.104461

**Comment by rhshadrach** [comment]
@WillAyd - are you comfortable calling this a bug fix so doesn't need deprecation?

**Comment by WillAyd** [comment]
Yea I would consider this a bug
