### ISSUE TITLE
ENH: An option to stop appending .0 to strings if null is present in json

### ISSUE THREAD

**Issue by Pontus-St** [pandas-dev/pandas#58306]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I sometimes deal with data that stores number-id's as integers and not as strings, and they also contain null values in that number-id column.  

When I load this data into pandas I would like to be able to specify "treat this column as string". Currently, if there is a null value present Pandas seems to interpret that whole column as float and add ".0" to the end of each number before returning it as a string valued column. 

example how it currently works: 
```
import json
import pandas as pd

print(pd.__version__) 

jsondata = '{"Column1":{"row1":1,"row2":2,"row3":null}}'
jdata = json.loads(jsondata)

df = pd.DataFrame(jdata,dtype=str)
print(df)

>>2.2.2
>>      Column1
>>row1  1.0
>>row2  2.0
>>row3  NaN
```
I would like it to return 1 and 2 instead of 1.0 and 2.0

### Feature Description

I perhaps missinterpreted the argument "dtype" in df = pd.DataFrame(jdata,dtype=str) 
So there could be "force_as_dtype" per column, which could stop the conversion into float before converting to string.

I tried tracing where the conversion between types is made, and from what I could find:
This "force_as_dtype" per column could be passed on through the "_homogenize" function in pandas/core/internals/construction.py ,and through the "fast multiget" function in pandas/_libs/lib, to finally be used to stop the conversion in the "mayby_convert_objects"  function in pandas/_libs/lib.

### Alternative Solutions

There exist methods to clean the data before entering it into pandas. And it is quite easy to remove the ".0" from the column after it has been created.

**Comment by WillAyd** [comment]
If using NumPy backend integers it is not possible to mix integral values and missing values. You can use pyarrow backed data types instead:

```python
>>> import io
>>> import pandas as pd

>>> jsondata = io.StringIO('{"Column1":{"row1":1,"row2":2,"row3":null}}')
>>> pd.read_json(jsondata, dtype_backend="pyarrow")
      Column1
row1        1
row2        2
row3     <NA>
```
