### ISSUE TITLE
DOC: Mailing list section has no link to subscribe to the mailing list

### ISSUE THREAD

**Issue by Aloqeely** [pandas-dev/pandas#58340]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/development/community.html#the-developer-mailing-list

### Documentation problem

The mailing list section does not explain how to subscribe to or view it

### Suggested fix for documentation

Add links to subscribe and view archives under that section

**Comment by lithomas1** [comment]
A PR to improve this would be welcome :)

**Comment by shriyakalakata** [comment]
take
