### ISSUE TITLE
DOC: Missing Source Links

### ISSUE THREAD

**Issue by shriyakalakata** [pandas-dev/pandas#58351]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.columns.html

### Documentation problem

There is no link pointing towards the source code

### Suggested fix for documentation

Link the source (https://github.com/pandas-dev/pandas/blob/main/pandas/core/apply.py/#L824-L826)

**Comment by giormala** [comment]
take

**Comment by fbourgey** [comment]
take
