### ISSUE TITLE
BUG: Assigning datetime to pa.date32() type array should raise

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#58420]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import pyarrow as pa

pa_arr = pa.array([
    datetime.date(2024, 1, 1),
    datetime.date(2024, 1, 2),
    datetime.date(2024, 1, 3),
])
ser = pd.Series(pa_arr, dtype=pd.ArrowDtype(pa.date32()))
ser.iloc[0] =  datetime.datetime(2024, 12, 31, 12, 20, 0)
```

### Issue Description

Assigning a datetime value to a pyarrow date array type seems to implicitly drop the time components

### Expected Behavior

Should raise TypeError

### Installed Versions

<details>

In [24]: pd.__version__
Out[24]: '3.0.0.dev0+681.g434fda08cf'

In [25]: pa.__version__
Out[25]: '15.0.0'

</details>

**Comment by udit5656** [comment]
take

**Comment by PedroVerardo** [comment]
take

**Comment by PedroVerardo** [comment]
Hi @WillAyd, I'm new to the pandas repository, and I think I've found the problem with this issue. However, I don't know exactly how to change this transformation in the code.

This happens in the ArrowExtensionArray, on the function _box_pa_scalar

`pa_scalar = pa.scalar(value, type=pa_type, from_pandas=True)`

The only possibility I see is to remove this and raise an error

**Comment by PedroVerardo** [comment]
I made a change that solves the issue specifically in the "Reproducible Example," but I think there are some similar problems that need to be solved. It is necessary to explore this problem more.

For example, if you do the opposite, as you do in this example, the same thing happens, but this time, 'ns' will be inferred.

```python

import pandas as pd
import pyarrow as pa
import datetime

pa_arr = pa.array([
    datetime.datetime(2024, 1, 1, 1, 1, 1),
    datetime.datetime(2024, 4, 5, 1, 1, 1),
    datetime.datetime(2024, 6, 7, 1, 1, 1),
])
ser = pd.Series(pa_arr, dtype=pd.ArrowDtype(pa.timestamp('ns')))
ser.iloc[0] = datetime.datetime(2024, 12, 31)
print(ser)
```

If needed, I would love to help @WillAyd.

**Comment by WillAyd** [comment]
Looks like this is an issue upstream in arrow - see https://github.com/apache/arrow/issues/41896
