### ISSUE TITLE
DOC: `read_csv` and parameter `date_format` add example of a dict of columns

### ISSUE THREAD

**Issue by BdR76** [pandas-dev/pandas#58462]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html#:~:text=str%20or%20dict%20of%20column

### Documentation problem

The `read_csv` has a parameter `date_format` which can can be "str or dict of columns" but it's not made clear dict of column.

When my csv file has 3 date columns and all are formatted as '%d-%m-%Y' then it's easy, I understand I can use `date_format='%d-%m-%Y'`. But when 2 columns are formatted as `%d-%m-%Y` and the last one is formatted `%d-%m-%Y %H:%M:%S` then not clear how the parametre should given?

### Suggested fix for documentation

Can someone add a dict example to the documentation of the `read_csv` and the `date_format` parameter? I understand the documentation is generated from the sourcecode. But I couldn't find where the source code for `read_csv` is located on github

**Comment by Aloqeely** [comment]
In general, I agree that `read_csv` does not have any useful examples which I think we should improve, but I don't think we should add an example for the usage of every parameter.
For this specific case, I think it's better to improve the docstring of `date_format`, maybe it should say: 'dict of column names', or maybe in the description of the parameter we could mention that the dict will be in the form of: `{column: format}`
