### ISSUE TITLE
BUG: pandas.api.types.is_integer_dtype evaluates 'P' and 'p' as integers

### ISSUE THREAD

**Issue by jacob-a-brown** [pandas-dev/pandas#58480]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
from pandas.api.types import is_integer_dtype
from string import ascii_lowercase, ascii_uppercase

for letter, LETTER in zip(list(ascii_lowercase), list(ascii_uppercase)):
    if is_integer_dtype(letter):
        print(letter)
    if is_integer_dtype(LETTER):
        print(LETTER)

# prints the following...
# b
# B
# h
# H
# i
# I
# l
# L
# p
# P
# q 
# Q
```

### Issue Description

`is_integer_dtype` evalutes to `True` for b, B, h, H, i, I, l, L, p, P, q, Q

### Expected Behavior

I expected `is_integer_dtype` to evaluate to `False` for b, B, h, H, i, I, l, L, p, P, q, Q

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.11.5.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.22631
machine               : AMD64
processor             : Intel64 Family 6 Model 154 Stepping 3, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : English_United States.1252

pandas                : 2.2.2
numpy                 : 1.26.3
pytz                  : 2024.1
dateutil              : 2.8.2
setuptools            : 65.5.0
pip                   : 24.0
Cython                : None
pytest                : 7.4.4
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : 2.0.29
tables                : None
tabulate              : None
xarray                : None
xlrd                  : 2.0.1
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>

**Comment by VISWESWARAN1998** [comment]
From pandas documentation (https://pandas.pydata.org/docs/reference/api/pandas.api.types.is_integer_dtype.html) `is_integer_dtype`  function is used to check whether an array or data-type belongs to integer data-type. 

So the function expects the parameter to be **array containing data-types or just a data type.**

b, B, h, etc., are representing data-types like signed byte, unsigned byte, 16-bit signed and unsigned integers etc.,

Under the hood pandas will be using `np.dtype` function provided by numpy which gives me the following output

![image](https://github.com/pandas-dev/pandas/assets/16797137/ef30bcf0-74cf-4842-92e5-268a95ab86a5)

So we can conclude that this function is expecting data-type which can be in string format not just regular strings. You may use `isdigit` provided by Python.

Thank you,
Visweswaran N
