### ISSUE TITLE
DOC: The conditions under which slicing with labels worked as expected were wrong.

### ISSUE THREAD

**Issue by yuji38kwmt** [pandas-dev/pandas#58583]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/user_guide/indexing.html#slicing-with-labels

### Documentation problem

The documentation says:

>If at least one of the two is absent, but the index is sorted, and can be compared against start and stop labels, then slicing will still work as expected, by selecting labels which rank between the two:

But slicing will work as expected even if both are not present.

```
In [157]: s = pd.Series(list('abcde'), index=[0, 3, 2, 5, 4])

In [158]: s.sort_index()
Out[158]:
0    a
2    c
3    b
4    e
5    d
dtype: object

In [159]: s.sort_index().loc[-1:6]
Out[159]:
0    a
2    c
3    b
4    e
5    d
dtype: object
```

### Suggested fix for documentation

I suggest the documentation.

>If the index is sorted, and can be compared against start and stop labels, then slicing will still work as expected, by selecting labels which rank between the two:

**Comment by Aloqeely** [comment]
I agree with your suggested fix, PRs are welcome

**Comment by pmhatre1** [comment]
Closed and deleted the branch for the PR 58598 due to unresolved merge errors due to rebase.
