### ISSUE TITLE
ENH: Allow `pd.set_option` to control the uuid4 seed used in `pd.io.formats.style.Renderer`

### ISSUE THREAD

**Issue by thisiswhereitype** [pandas-dev/pandas#58593]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

When running Notebooks with HTML output of tables, the uuid for each tables css class changes between runs creating uneeded diffing.

This it to prevent name collisions but results in a random uuid4 string for each table.

### Feature Description

The uuid instance could optionally be seeded: https://stackoverflow.com/a/41186895

A config option, say `styler.html.uuid_seed` would allow users to optionally set and reset it for reproducibility or otherwise.
This would be kept as module state to be shared by all Styler objects, resulting in import level reproducibility.

Already Styler's may be passed id's to use in place of uuids. Permitting the default to remain the same.

The [implementation](https://github.com/pandas-dev/pandas/blob/d9cdd2ee5a58015ef6f4d15c7226110c9aab8140/pandas/io/formats/style_render.py#L101) of StylerRenderer's init would be altered to share the uuid state.

### Alternative Solutions

Alternatively a StylerRenderer Singleton Factory might be implemented.

### Additional Context

https://stackoverflow.com/a/41186895 - UUID seeding.
[Relevant __init__ line](https://github.com/pandas-dev/pandas/blob/d9cdd2ee5a58015ef6f4d15c7226110c9aab8140/pandas/io/formats/style_render.py#L101)
[Describe config docs](https://pandas.pydata.org/docs/reference/api/pandas.describe_option.html#pandas.describe_option)

**Comment by attack68** [comment]
This is quite an esoteric use. Not particularly enthusiastic about adding a pandas option for this functionality.

You can directly instantiate a Styler with a specified `id` 

```python
from pandas.io.formats.style import Styler
styler = Styler(df, uuid="my_id")
```

can be used instead of:

```python
styler = df.style
```

Alernatively create a factory:

```python
def styler(df):
    return Styler(df, uuid="default_id")

styler(df)
```

**Comment by thisiswhereitype** [comment]
Okay thanks for the comments - I can use a factory.
