### ISSUE TITLE
BUG: passing non-trivial expressions to function within eval raises an error

### ISSUE THREAD

**Issue by domsmrz** [pandas-dev/pandas#58591]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

def func(x):
  return x + 1

s = pd.DataFrame({'foo': [1,2,3]})

s.eval('@func(foo)')         # works
s.eval('@func(@func(foo))')  # works
s.eval('1 + @func(foo)')     # works
s.eval('@func(-foo)')        # raises an exception
s.eval('@func(foo + 1)')     # raises an exception
```

### Issue Description

Last two expressions in the "Example section" raises an `AttributeException` with `UnaryOp` / `BinOp` not having `value` attribute.

Not sure if this should be considered ENH or BUG as the documentation is somewhat incomplete in this regard (leaned towards the "BUG" as the other expressions work) but I guess either way it would be nice to fix this.

### Expected Behavior

Expressions to be evaluated rather than raise an exception.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.11.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 6.6.15-2rodete2-amd64
Version          : #1 SMP PREEMPT_DYNAMIC Debian 6.6.15-2rodete2 (2024-03-19)
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.26.4
pytz             : 2024.1
dateutil         : 2.8.2
setuptools       : 68.1.2
pip              : 24.0
Cython           : 3.0.8
pytest           : 7.4.4
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 5.1.0
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.1.3
IPython          : 8.20.0
pandas_datareader: None
bs4              : 4.12.3
bottleneck       : 1.3.5
brotli           : 1.1.0
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.3
numba            : None
numexpr          : 2.9.0
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : 
sqlalchemy       : None
tables           : 3.7.0
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by Aloqeely** [comment]
You checked the box `I have confirmed this bug exists on the latest version of pandas.` but I am unable to reproduce this on version 2.2.2. It seems like you are on version 1.5.3, could you try updating to a newer version and see if the bug still occurs?

**Comment by domsmrz** [comment]
My apologies, I tested it on the wrong machine (i.e., I though I was using the newest pandas verions). Confirming that this is indeed fixed in newer version of pandas. Sorry for the inconvenience.
