### ISSUE TITLE
DEPR: Deprecate method argument of reindex_like 

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#58667]
### Feature Type

- [X] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [X] Removing existing functionality in pandas

### Problem Description

There is a bug report of this in https://github.com/pandas-dev/pandas/issues/34547 The current behavior of the method seems to work closer to DataFrame.update (whether intentional or not). Rather than try and fix I think it would be better to remove the parameter and have users call .fillna() or .update() to get the intended result

### Feature Description

Deprecate

### Alternative Solutions

N/A

**Comment by jasonmokk** [comment]
take

**Comment by PedroVerardo** [comment]
take

**Comment by PedroVerardo** [comment]
Hi, I'm wondering what the procedure is to deprecate a keyword argument of a method when there is no new name for it, just removing it. Should I change the code to remove the argument and add a deprecation warning, or should I simply add the deprecation warning?

**Comment by tomytp** [comment]
take

**Comment by Dr-Irv** [comment]
@WillAyd now that `method` has been deprecated, do we need to deprecate `tolerance` as well?

What about deprecating `method` in `reindex()` ?  and `tolerance` ?
