### ISSUE TITLE
Potential regression induced by "CLN: Simplify map_infer_mask (#58483)"

### ISSUE THREAD

**Issue by DeaMariaLeon** [pandas-dev/pandas#58678]
PR #58483

@lithomas1 

"`libs.InferDtype.time_infer_dtype` (Python) with dtype='np-object'": "http://57.128.112.95:5000/compare/benchmarks/0663e9b71ebe7ec480008ecf488c2a9d...0663e9c8c4e878d380005c8f93f092a4",
        "`strings.Methods.time_isalnum` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb685b71738000a56f64f75abe...0663e9ccf228726d8000696c63f3acb2",
        "`strings.Methods.time_islower` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb6f8b761c80009f510bc437fd...0663e9ccf90b7cc78000e9aac27035f5",
        "`strings.Methods.time_len` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb79db7e3c8000e44a7f9b8460...0663e9cd026a758e80006e8894de4e91",
        "`strings.Methods.time_isspace` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb735b7b6d80001191762afc4d...0663e9ccfc9b712e8000d65e509d7a01",
        "`strings.Methods.time_len` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb7a7c757a8000645b42dc6c98...0663e9cd03007147800064c0e5466f3e",
        "`strings.Methods.time_title` (Python) with dtype='string[pyarrow]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb93577f2880009f2ea0f2b30e...0663e9cd1b4c7a018000209b41fc4c8d",
        "`strings.Methods.time_isupper` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb77007ae580007196a8c0c149...0663e9ccffc6712780003cad0aeb138f",
        "`strings.Methods.time_isdigit` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb6da7791f800036b40783bd14...0663e9ccf73b76bf80009f644bb58f3e",
        "`strings.Methods.time_isupper` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb7675797f800085efa20f5fc4...0663e9ccff337e2f8000cfb57e6e9793",
        "`strings.Methods.time_istitle` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb74a77185800032d951fc1c20...0663e9ccfda279b48000e88e8c8003bd",
        "`strings.Methods.time_isalpha` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb6997739280006b6c2c7f213b...0663e9ccf3357b648000fa97bdba6484",
        "`strings.Methods.time_isalnum` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb67c67e508000cefeb1e20c8e...0663e9ccf1927be58000f0ef81ae359c",
        "`strings.Methods.time_isspace` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb72c47ce08000993375b8db78...0663e9ccfc1273df80005cdacaa3fdc3",
        "`strings.Methods.time_isdecimal` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb6b5473b480008a1b823df8f4...0663e9ccf4df7853800034a6d4ebecb4",
        "`strings.Methods.time_islower` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb6ee67bc98000221b7e081e31...0663e9ccf87177bc80006505c428b37d",
        "`strings.Methods.time_isnumeric` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb70e87aa280003604d2535c32...0663e9ccfa41795c80003836f9512a06",
        "`strings.Methods.time_isdigit` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb6d0d75ce800094c5a69e25bf...0663e9ccf67d770f8000725123c8a0ed",
        "`strings.Contains.time_contains` (Python) with dtype='string[python]', regex=False": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb50347fc98000089f398fc26e...0663e9ccdb337a898000c0832bdc56b6",
        "`strings.Methods.time_rstrip` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb8b9578c38000cbee3e130f2d...0663e9cd140178318000e7d56bc56799",
        "`strings.Methods.time_lower` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb7c2c732c800090d8f6a7fe8f...0663e9cd04a370938000dbd0f1e753aa",
        "`strings.Methods.time_lstrip` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb7de37bc88000ae2381ee573f...0663e9cd06567c10800084947600f1d1",
        "`strings.Methods.time_lower` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb7b9a7d5f80007a1cbab73959...0663e9cd041c774a8000e75ad3ee38c3",
        "`strings.Contains.time_contains` (Python) with dtype='str', regex=True": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb4e7b7c3080007a0a8ef52b60...0663e9ccd9a07d278000e5bdbc42526c",
        "`strings.Methods.time_title` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb92ca7dbd8000c4e136d8c29f...0663e9cd1ac875f3800064a82f41e97e",
        "`strings.Methods.time_isdecimal` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb6bd97be08000d1250a2c3359...0663e9ccf55e7e0d80005a9a2a9c7e00",
        "`strings.Methods.time_isalpha` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb6a3479b280004c002027773f...0663e9ccf3c075df8000f76589671025",
        "`strings.Methods.time_istitle` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb754b77c18000e300627cf560...0663e9ccfe2174508000a62ee2c69880",
        "`strings.Methods.time_slice` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb8cc77c5d80008cc88e9cda0a...0663e9cd15027914800044b8c792da3b",
        "`strings.Methods.time_fullmatch` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb647572578000482cbfb00100...0663e9cceece799c80003520efc7962a",
        "`strings.Methods.time_isnumeric` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb717c7d95800022187db0d25e...0663e9ccfad6751d80000025e8bef4d5",
        "`strings.Methods.time_rstrip` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb8af476098000d2e36efb62fe...0663e9cd1369792d80001a5ccd0a4104",
        "`strings.Methods.time_title` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb923b7cb4800031308eef70a4...0663e9cd1a33761580004a957e207582",
        "`strings.Split.time_rsplit` (Python) with dtype='string[python]', expand=False": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb9e7870f68000a6764dccbdc8...0663e9cd25ed72c38000458a730e6cc7",
        "`strings.Methods.time_startswith` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb8f5076808000eb863c291e04...0663e9cd17647b4480002daf16484279",
        "`strings.Methods.time_replace` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb866f7dcb800083da56f2c4e1...0663e9cd0edc770a800071300159bc4f",
        "`strings.Methods.time_match` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb7f7c7ee68000f4a28a89661a...0663e9cd07f5771280007d9efb4678ad",
        "`strings.Contains.time_contains` (Python) with dtype='string[python]', regex=True": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb4f9c75d180006d576c0a2b11...0663e9ccdaad7cd8800083d25e988e99",
        "`strings.Split.time_rsplit` (Python) with dtype='str', expand=False": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb9d467516800086b5198144fb...0663e9cd24d87f1e800020db8d213ce1",
        "`strings.Slice.time_vector_slice` (Python)": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb9bef77db8000f5fe4a58d56d...0663e9cd23d37cc280001fc31084257a",
        "`strings.Methods.time_lstrip` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb7d6077d6800003ea93e42bdb...0663e9cd05ca748c80000b328bc4b29e",
        "`strings.Methods.time_endswith` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb5cda74ad80001b36a6cc436d...0663e9cce79c7e048000892e35b2f2a5",
        "`strings.Methods.time_find` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb60d97b57800016009a4a15df...0663e9cceb897d028000e833a3d00a03",
        "`strings.Methods.time_strip` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb909375a78000abd216bc0654...0663e9cd18707e7c800067a3cc2108c2",
        "`io.hdf.HDFStoreDataFrame.time_write_store_table` (Python)": "http://57.128.112.95:5000/compare/benchmarks/0663e9b5de0e73698000d9f1e1860e34...0663e9c77a2c7b4d8000b4a55c932400",
        "`io.hdf.HDFStoreDataFrame.time_write_store` (Python)": "http://57.128.112.95:5000/compare/benchmarks/0663e9b5dcff7e08800097a92ba97ab6...0663e9c778fe7ab58000ed2bf6692764",
        "`strings.Methods.time_replace` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb85b87d6b8000ca05582d86b2...0663e9cd0e4c704280009f3e22751701",
        "`strings.Methods.time_slice` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb8d6b711d8000871c90a5bd24...0663e9cd159a767c8000198d5b8bf97f",
        "`strings.Methods.time_count` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb5ba6706a80001db7b917f0a0...0663e9cce66078f8800013fd05d36c26",
        "`strings.Methods.time_zfill` (Python) with dtype='string[pyarrow]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb9a1c7b258000700c5d7feaff...0663e9cd22387e7280007185f5baecd6",
        "`strings.Contains.time_contains` (Python) with dtype='str', regex=False": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb4f0978908000443e0e5fb840...0663e9ccda267846800054b12dc5044d",
        "`strings.Methods.time_startswith` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb8eb378dc8000cb993192bc79...0663e9cd16d97dc9800030bbb31f7f93",
        "`strings.Methods.time_endswith` (Python) with dtype='string[python]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb5d5d777d80000fb8735d5978...0663e9cce8347e82800080157163e4a4",
        "`strings.Methods.time_rfind` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb87707fdd8000d4a8ed34158e...0663e9cd100d759f8000802da16acc92",
        "`strings.Methods.time_rfind` (Python) with dtype='string[pyarrow]'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb88b674fc80003468cafb1191...0663e9cd11387c368000aa2d4d9546f5",
        "`strings.Methods.time_find` (Python) with dtype='str'": "http://57.128.112.95:5000/compare/benchmarks/0663e9bb602f72688000b5dee2e110e4...0663e9cceaf277aa8000858a12e0dd2b"

<img width="793" alt="Screenshot 2024-05-12 at 11 03 21" src="https://github.com/pandas-dev/pandas/assets/11835246/0f4352cb-1da8-47a4-9b38-44a160a23b10">

**Comment by lithomas1** [comment]
Thanks, I'll take a look.

Looking at the overview on the other asv website, it looks like most of the regression is < 10% and there are a couple of benchmarks that regressed by 20%. 

I'll see what can be done for those.
