### ISSUE TITLE
ENH: Also apply formatters to the index in `to_latex`

### ISSUE THREAD

**Issue by cherrywoods** [pandas-dev/pandas#58681]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I would like to also format the index when exporting a `DataFrame` to a LaTeX table using `DataFrame.to_latex`.
This does not seem to be the case, at least when using a `MultiIndex` as index.

### Feature Description

Apply the `formatters` argument of `DataFrame.to_latex` to the generated index columns or change the signature of `DataFrame.to_latex` to include another argument, `index_formatters for index-specific formatters.

### Alternative Solutions

Add the index as columns to the `DataFrame` so that `to_latex` applies the `formatters` to these columns.
Then, reorder the columns and export using `to_latex(..., index=False)`.
However, this does not produce the nice multirow formatting that a `MultiLevel` index provides.

Second alternative: Replace the levels of the `MultiIndex` by the formatted values of the levels.

**Comment by rhshadrach** [comment]
cc @attack68

**Comment by attack68** [comment]
For advanced features such as this you should not use `DataFrame.to_latex`.
As documented when requiring advanced customisation of output you should use the `Styler` implementation of `to_latex`.

In particular to do what you require you should use:
```
df.style.format_index(..).to_latex`
```

**Comment by rhshadrach** [comment]
Thanks @attack68 - agreed. `to_latex` provides some basic functionality for common cases, but if users want more control they can turn to the Styler.

Closing.
