### ISSUE TITLE
BUG: edge case when masking "null[pyarrow]" pd.Series

### ISSUE THREAD

**Issue by lukaszkolodziejczyk** [pandas-dev/pandas#58696]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
pd.Series([pd.NA], dtype="null[pyarrow]").mask([True], pd.NA)
```

### Issue Description

It fails in the following way: 
```
/Users/runner/work/crossbow/crossbow/arrow/cpp/src/arrow/result.cc:28: Constructed with a non-error status: OK

Process finished with exit code 134 (interrupted by signal 6:SIGABRT)
```

### Expected Behavior

I'd expect it to return:
`pd.Series([pd.NA], dtype="null[pyarrow]")`

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.11.0.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 23.1.0
Version               : Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : None.UTF-8

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : 69.5.1
pip                   : 24.0
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 16.0.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None
</details>

**Comment by rob-sil** [comment]
Could this be an upstream bug in PyArrow? I get the same error when running the no-pandas version:
```python
import pyarrow as pa
import pyarrow.compute as pc

mask = pa.array([True])
values = pa.array([None])
pc.replace_with_mask(values, mask, pa.NA)
```

**Comment by mroeschke** [comment]
Yes this appears to be an upstream issue. Feel free to report this issue to Arrow Github. Closing as an upstream issue
