### ISSUE TITLE
BUG: "styler.format.thousands" option doesn't work for integers

### ISSUE THREAD

**Issue by vladpy8** [pandas-dev/pandas#58737]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas
pandas.set_option('styler.format.thousands', ',')

data = pandas.DataFrame(data=[{'field': 1234567890}], dtype='int64',)

# Doesn't output integer field with comma separator
data

# Does output integer field with comma separator
data.style.format(thousands=',')
```

### Issue Description

Printing data **without** `.style` in jupyter cell displays huge integer number without comma separator, inspite of the option set
Printing data **with** `.style` in jupyter cell displays integers with commas

### Expected Behavior

Outputs must be same

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.11.9.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 23.4.0
Version               : Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : None.UTF-8

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : 69.5.1
pip                   : 24.0
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.4
IPython               : 8.24.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.5.0
gcsfs                 : None
matplotlib            : 3.9.0
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 10.0.1
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : 2024.5.0
scipy                 : 1.13.0
sqlalchemy            : None
tables                : None
tabulate              : 0.9.0
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>

**Comment by attack68** [comment]
Agreed. This needs fixing, also for `decimal` option.

The solution, I believe, is in `style_render`:

```python
precision = (
    get_option("styler.format.precision") if precision is None else precision
)
self._display_funcs: DefaultDict[  # maps (row, col) -> format func
    tuple[int, int], Callable[[Any], str]
] = defaultdict(lambda: partial(_default_formatter, precision=precision))
```

change to:

```python
_is_decimal_thousands = (
    get_option("styler.format.thousands") is not None or 
    get_option("styler.format.decimal") != "."
)
precision = (
    get_option("styler.format.precision") if precision is None else precision
)
dfunc = partial(_default_formatter, precision=precision)
if _is_decimal_thousands:
    ddict = defaultdict(lambda: _wrap_decimal_thousands(
            formatter=dfunc, 
            thousands=get_option("styler.format.thousands"), 
            decimal=get_option("styler.format.decimal"),
        )
    )
else:
    ddict = defaultdict(lambda: dfunc)
```
and replace all the `defaultdicts` with the new `ddict`.

Needs tests.

**Comment by attack68** [comment]
The above was not correct. The following works:
```python
pd.set_option('styler.format.precision', 3)
pd.set_option('styler.format.thousands', "+")
pd.set_option('styler.format.decimal', "-")
df = pd.DataFrame([
    [10000.0, 20000],
    [30000.0, 40000]
])
df.style
```
![Screenshot 2024-05-18 at 07 43 45](https://github.com/pandas-dev/pandas/assets/24256554/582d2a11-ec7a-4310-9138-a4918c05ee51)

as does
```python
pd.set_option('styler.format.precision', 3)
pd.set_option('styler.format.thousands', "+")
pd.set_option('styler.format.decimal', "-") 
df = pd.DataFrame(data=[{'field': 1234567890}], dtype='int64',)
df.style
```
![Screenshot 2024-05-18 at 07 46 10](https://github.com/pandas-dev/pandas/assets/24256554/36e155a0-add2-41b7-bb3c-7852278af4b2)


I misread your issue. The `styler` pandas options only impact the `Styler` class. These options are available for people who regularly use Styler. They do not impact `DataFrame` and the options associated with that class and any of its data input, wrangling, or (in your case) **output** methods. This is desired behaviour.
If your do not call `.style` you will not produce a `Styler` and these options **will not** apply.

**Comment by mroeschke** [comment]
Yeah given the above it seems like the OP is the expected behavior so closing

**Comment by vladpy8** [comment]
> The styler pandas options only impact the Styler class. 

> They do not impact DataFrame and the options associated with that class and any of its data input, wrangling, or (in your case) output methods. 

I see, thank you!
