### ISSUE TITLE
BUG: pd.to_datetime fails to identify actual date format

### ISSUE THREAD

**Issue by RedHeadphone** [pandas-dev/pandas#58747]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

data = [
  "May-16-2024",
  "May-17-2024",
  "May-18-2024",
  "May-20-2024",
  "May-24-2024",
  "May-27-2024",
  "May-28-2024",
  "Jun-05-2024"
]

ser = pd.Series(data)
ser = pd.to_datetime(ser)

print(ser)
```

### Issue Description

Problem:
When converting a list of date strings to datetime using pd.to_datetime, it raises an error if the month format is inconsistent (i.e., some months are in full form and others are abbreviated). This issue arises even when the data is not mixed but misinterpreted by pandas due to the nature of certain month abbreviations.

Error:
```
ValueError: time data "Jun-05-2024" doesn't match format "%B-%d-%Y", at position 7. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
```

Analysis:

- The input format "%B-%d-%Y" (full month name) is inferred from the first element "May-16-2024".
- This format works for "May-16-2024" through "May-28-2024" because "May" has the same abbreviation as its full form.
- The problem arises when it encounters "Jun-05-2024", where "Jun" is the abbreviated form and does not match the inferred full month name format.

Current Workaround:
Specifying the format as format='mixed' or format='%b-%d-%Y' solves the issue, but this should ideally be handled by pandas automatically.

### Expected Behavior

pd.to_datetime should correctly parse the dates without raising an error.

Output should be:
```
0   2024-05-16
1   2024-05-17
2   2024-05-18
3   2024-05-20
4   2024-05-24
5   2024-05-27
6   2024-05-28
7   2024-06-05
dtype: datetime64[ns]
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.10.14.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.5.0-1020-gcp
Version               : #20~22.04.1-Ubuntu SMP Wed May  1 02:03:24 UTC 2024
machine               : x86_64
processor             : 
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : 69.5.1.post0
pip                   : 24.0
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>

**Comment by Aloqeely** [comment]
Thanks for the report! This is a duplicate of #58328

But, your analysis is correct and if you have an idea for a fix feel free to submit a PR!

**Comment by RedHeadphone** [comment]
Not sure if it is right, but my idea for the fix would be as below

1. checking if the first element has 'May' in the date string
2. if so then get the date format as usual. Suppose the date format we got is "%B-%d-%Y"
3. then try converting all dates with "%B-%d-%Y" and "%b-%d-%Y" (replace capital B with small b) . If one of them doesn't work, continue with the other format.

@Aloqeely what do you think of this approach?

**Comment by Aloqeely** [comment]
That would work, could you please discuss it in the original issue and get input from pandas devs?

**Comment by RedHeadphone** [comment]
Sure closing this issue
