### ISSUE TITLE
BUG: read_parquet converts all digits strings to int

### ISSUE THREAD

**Issue by tfardet** [pandas-dev/pandas#58771]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({"a": ["a", "b", "c"], "b": ["1", "2", "3"]})
df.to_parquet("df.parquet")
df2 = pd.read_parquet("df.parquet")
"1" in df2.b  # returns False
1 in df2.b  # returns True

from pyarrow.parquet import read_table
read_table("df.parquet")  # returns the proper string types
```

### Issue Description

Reading parquet files converts all-digit strings to integers despite ``pyarrow`` properly returning the string type of the column.

Potentially related to #31821

### Expected Behavior

The column is properly typed as strings

### Installed Versions

commit                : a3e751c6b435575de96c4a83bf67797e4a989771
python                : 3.12.3.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.8.9-300.fc40.x86_64
Version               : #1 SMP PREEMPT_DYNAMIC Thu May  2 18:59:06 UTC 2024
machine               : x86_64
processor             : 
byteorder             : little
LC_ALL                : None
LANG                  : fr_FR.UTF-8
LOCALE                : fr_FR.UTF-8

pandas                : 3.0.0.dev0+991.ga3e751c6b
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.8.2
setuptools            : 69.0.3
pip                   : 23.3.2
Cython                : 3.0.10
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 5.1.0
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.3
IPython               : 8.24.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
bottleneck            : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : 3.8.4
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pyarrow               : 16.0.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.13.0
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : 2024.3.0
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

**Comment by Aloqeely** [comment]
Thanks for the report. `read_parquet` does preserve the numbers as strings, it's just that the `in` operator checks for the items in the index rather than the Series data. You can instead use the `in` operator on  `Series.values` to see if an item exists in the Series data, e.g.
```python
"1" in df2.b.values  # True
```

**Comment by tfardet** [comment]
Ah, I see, sorry, I did not realize this was how Series worked.
Closing!
