### ISSUE TITLE
DOC: Insufficient Project Background Information

### ISSUE THREAD

**Issue by kevinliu249** [pandas-dev/pandas#58816]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://github.com/pandas-dev/pandas/blob/main/README.md

### Documentation problem

The issue that I found was in the README file. The background section of the README file was kept short, and additional information had to be found in external sources. 

### Suggested fix for documentation

I suggest adding a short paragraph regarding the project origin and its history. It would be an improvement made to help contributors and users to better understand the project and increase recognition of the author. It would also be more convenient and efficient for users to receive this information from README as opposed to going to a separate website.

**Comment by rhshadrach** [comment]
Thanks for the suggestion. I do not think the same - I am of the opinion that a good readme should be short and point to where users can find more information. Asking users to click on a link is not onerous.

**Comment by mroeschke** [comment]
I agree with the assessment above. Additionally, it's best that information is not duplicated as it's hard to ensure both or several are in sync - a point to a link ensures that.

Thanks for the suggestion but closing
