### ISSUE TITLE
Allow no returns from expanding_apply

### ISSUE THREAD

**Issue by jseabold** [pandas-dev/pandas#5881]
related #4130

I haven't looked at the code at how easy this is to do, but it looks like things like expanding_apply (moving_apply too I suspect) expects a float returned from the function. It might make sense to have an optional no_return flag (or just be smart about it, though perhaps it makes sense to have a flag as a sanity check for the user.) 

Use case, I'm using expanding_apply to run some code in a subprocess and write to disk. I'm able to get around the expectation by having my function return 0.0 or something, but it's a bit of a hack.

**Comment by mroeschke** [comment]
Dtypes for window ops is covered in https://github.com/pandas-dev/pandas/issues/11446 so closing in favor of that issue
