### ISSUE TITLE
BUG: Lookup by datetime in timestamp index does not work

### ISSUE THREAD

**Issue by sam-s** [pandas-dev/pandas#58815]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
d0 = datetime.date(2024,5,5)
d1 = datetime.date(2024,5,10)
df0 = pd.DataFrame({"a":[1,2],"b":[10,None],"c":list("xy")}, index=[d0,d1])
df0.loc[d0]  # works, but non of df0.loc[str(d0)] & c do
df1 = df0.reindex(pd.date_range(d0,d1))
df1.loc[d0]  # raises KeyError: datetime.date(2024, 5, 5)
df1.loc[str(d0)]  # works
df1.loc[pd.Timestamp(d0)]  # works
df1.loc[datetime.datetime.combine(d0,datetime.time.min)]  # works
```

### Issue Description

[As discussed](https://stackoverflow.com/q/78519636/850781), for _consistency_, whenever an implicit cast to `Timestamp` is done, `datetime.date` should be acceptable along with `str` and `datetime.datetime`.

In the example above, `df0` only accepts a `datetime.date` (which is fine),
while `df1` accepts a few "timestamp designators" (`pd.Timestamp`, `str`, `datetime.datetime`) but **not** `datetime.date` which seems inconsistent.

### Expected Behavior

`df1.loc[d0]` should work alongside with `df1.loc[pd.Timestamp(d0)]`. `df1.loc[str(d0)]`, and `df1.loc[datetime.datetime.combine(d0,datetime.time.min)]`.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.1.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.19045
machine               : AMD64
processor             : Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : English_United States.1252

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.8.2
setuptools            : 69.5.1
pip                   : 24.0
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 5.2.2
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.4
IPython               : 8.24.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.5.0
gcsfs                 : None
matplotlib            : 3.8.4
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.2
pandas_gbq            : None
pyarrow               : 15.0.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.13.0
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : 2.4.1
pyqt5                 : None

</details>

**Comment by Aloqeely** [comment]
Thanks for the report! 
It seems to me that this is intended after reading [this comment](https://github.com/pandas-dev/pandas/issues/35466#issuecomment-735286839), the argument is: "Since the stdlib datetime doesnt consider `datetime(2020, 9, 4) == date(2020, 9, 4)`, this follows the stdlib and considers them never equal."

Going to mark this as a duplicate report of #35466, feel free to continue the discussion in the original issue
