### ISSUE TITLE
BUG: Importing Pandas takes 30 seconds

### ISSUE THREAD

**Issue by carbon-starlight** [pandas-dev/pandas#58820]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
print('Importing pandas...')
timestamp1 = time.time()
import pandas as pd
print(f"Importing took {time.time() - timestamp1}{' f#cking' if time.time() - timestamp1 > 10 else ''} seconds")
```

### Issue Description

It takes around 30 seconds to import (installed) pandas on my old netbook and 18 seconds on my modern gaming laptop. Sometimes importing pandas doesn't even finish (it prints "Importing pandas", struggles for around 50 seconds and returnes a `ModuleNotFoundError: No module named 'pandas'` error).

All other libraries (except `openmeteo_requests` that also struggles this way but in a lighter fashion) are being imported just fine.

### Expected Behavior

Pandas should be imported.

### Installed Versions

<details>

Pandas installed yesterday, it should be of the latest version in pip

</details>

**Comment by mroeschke** [comment]
Thanks for the report. Investigation around this issue is going on in https://github.com/pandas-dev/pandas/issues/53488 so closing in favor of that issue. If you have any insights why this is happening happy to have that feedback in that issue
