### ISSUE TITLE
BUG: Pandas Styler HTML not rendering properly

### ISSUE THREAD

**Issue by trendyllama** [pandas-dev/pandas#58872]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import numpy as np
import pandas as pd


matrix = np.random.randint(10000, size=(40, 30))

df = pd.DataFrame(matrix)


style = df.style.highlight_between(left=8000, inclusive='neither')
style = style.hide(axis='index')
style = style.format(precision=2)
html_str = style.to_html()

or...

style = df.style.background_gradient(cmap = cm,axis=None)
html_str = style.to_html()


fix...

import textwrap
html_str = textwrap.fill(html_str, width=200)
```

### Issue Description

When using pandas styler objects the HTML they render has lines that extend beyond 1000 characters causing ids to truncate unexpectedly and break formatting styles. This is fine for most browsers but can cause problems for emails - there should be an option to control this from within the styler framework.

I use pandas 1,4 as my daily driver, but this behavior occurs on 2.2 as well.

## Here is an example of the truncation at line column 1000 of an email message.

```html

#T_4858f_row14_col16, #T!
f_row18_col21, #T_4858f_!

```

## Here is the trucation at line column 1

```html
_4858f_row14_col17,
 row18_col22, #T_48

```

As you can see the ids are being cut off, thus breaking the color background formatting.

## Fix 

The temporary fix is using the textwrap module to trucate the lines properly at a lower character threshold - 200 and 250 characters seemed to work for me. 

### Expected Behavior

I would expect every line of the render  html to not extend beyond a certain character limit and truncate each line effectively without breaking mid word.

### Installed Versions

<details>

1.4.4

</details>

**Comment by rhshadrach** [comment]
Thanks for the report - is it the email program that is doing the truncation, or pandas? In case it's the former,

> there should be an option to control this from within the styler framework.

What do you mean by "this"? What control are you seeking?

**Comment by trendyllama** [comment]
Hey!

For context, I am using outlook.

I think outlook is probably doing the truncating - comparing the dataframe html string generated in outlook to the same string being generated on chrome. So modern browsers seem to handle lines of cell IDs being longer than one to two thousand characters.

As for control, I would like to have the functionality of the textwrap package be optional in the Styler.to_html(). By "this" I mean to be able to tell Styler to generate HTML with a character limit per line or a supported way to ensure the cell IDs are not being prematurely chopped off when rendered. Maybe having a new line character or something that tells outlook/ browser to start a new line after a set amount of cell IDs.

Mostly raising the issue so that there is a community supported and documented way to avoid the styling becoming inconsistent.

I am not an expert on how outlook renders HTML or the encoding/ decoding that is going on behind the scenes so maybe the community knows something I don't.

**Comment by rhshadrach** [comment]
It seems to me pandas is producing the expected output, and that Python string parsing utilities allow convenient modification of that result in this case. Adding the functionality into pandas means the additional logic, API, docs, and testing, and that overhead results in no new additional features users couldn't do before, other than perhaps save a few keystrokes. With this, I'm against it's inclusion in pandas.

cc @attack68

**Comment by attack68** [comment]
Agreed this is not a problem with pandas, but with the external application. There are numerous ways to tackle your external problem and you have indeed found one solution. Others might include shortening the id references in pandas which is also possible.

Pandas should not subjectively choose a text shortening method and implement it for this problem.

But this is a useful issue report for users who encounter similar.
