### ISSUE TITLE
ENH: skiprows after header in read_csv

### ISSUE THREAD

**Issue by davetapley** [pandas-dev/pandas#58870]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

There isn't a way to tell `read_csv` to `skiprows` **after** the specified `header` row.

### Feature Description

To avoid breaking existing logic, I think a new argument would be required, perhaps `skiprows_after`?

So one could, parse, for example:

```
ignore,me
foo,bar
ignore,me
123,1
456,2
```

with `read_csv(f, header=1, skiprows_after=1)` and get:

```
   foo  bar
0  123    1
1  456    2
```

### Alternative Solutions

Workaround:

```py
header = read_csv(f, skiprows=1, nrows=1)
names = header.columns.to_list()
read_csv(f, skiprows=4, names=names)
```

**Comment by Aloqeely** [comment]
Thanks for the suggestion! CSV reading is already too complicated in pandas with many options for skipping certain rows (rows, skipfooter, iterator, etc.) and so introducing another parameter will complicate `read_csv` even further.

However, I think you can implement this in a prettier way using `iterator=True`, e.g.
```python
import pandas as pd

chunker = pd.read_csv("test.csv", header=1, iterator=True)
chunker.get_chunk(1)  # skip 1 row after header
df = chunker.get_chunk()  # the rest of the file
```

**Comment by mroeschke** [comment]
Thanks for the report but agreed that the snippet above would be a sufficient workaround and not worth the complexity to add another keyword argument to `read_csv` so closing
