### ISSUE TITLE
BUG: potential unexpected side-effects of "copy-on-write" in case of multiple imports of pandas

### ISSUE THREAD

**Issue by jxrossel** [pandas-dev/pandas#58901]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
Not necessary
```

### Issue Description

If I understand correctly https://pandas.pydata.org/docs/user_guide/copy_on_write.html#copy-on-write-enabling, setting the "copy-on-write" mode through `pd.set_option("mode.copy_on_write", True)` will activate the mode globally. Am I correct to understand that:
1. If pandas is imported elsewhere, e.g. in another library on which my library depends, that library will also be affected by this setting, with potentially unpredictable effect on that library outputs?
2. In the same spirit, if that library also sets this mode, the mode actually used in my code will depend on the import order?

### Expected Behavior

If I am correct, would there be a way to at least ensure this mode is not overwritten if it has been explicitly set once? So that if pandas is imported twice with conflicting mode setting, an error is raised

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.9.13.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.19045
machine               : AMD64
processor             : Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : French_Switzerland.1252

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : None
pip                   : None
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : 8.18.1
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : 1.3.8
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : 0.59.1
numexpr               : 2.10.0
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>

**Comment by mroeschke** [comment]
(Note that this affects any configurable option, not just the `copy_on_write` option)

> If pandas is imported elsewhere, e.g. in another library on which my library depends, that library will also be affected by this setting, with potentially unpredictable effect on that library outputs?

Yes, these pandas options are global settings. So any other library that uses pandas are affected by these settings

> In the same spirit, if that library also sets this mode, the mode actually used in my code will depend on the import order?

It doesn't depend on import order, it depends on who set the option last. Imports in Python are "cached"

> would there be a way to at least ensure this mode is not overwritten if it has been explicitly set once? So that if pandas is imported twice with conflicting mode setting, an error is raised

This is not really feasible as the configuration options are designed since there's no tracking on "who set what option". The best way to responsibly set options in case multiple libraries use pandas is to use the `option_context` context manager to set options where exactly needed https://pandas.pydata.org/docs/reference/api/pandas.option_context.html

Thanks for the issue. Closing as a usage question.

**Comment by jxrossel** [comment]
Hi @mroeschke , thanks for the quick response! And sorry for having conflated pandas import and option setting. So I guess, the best approach would be to turn https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.option_context.html into a decorator and use it on all functions/methods that call pandas.
