### ISSUE TITLE
Inconsistent "index"/"name" property referring to both rows and columns based on iloc selection

### ISSUE THREAD

**Issue by u3Izx9ql7vW4** [pandas-dev/pandas#58965]
Depending on how the Dataframe is selected, Pandas does a transpose of what `name` and `index` refer to. 

Namely given `df.index`, it would naturally follow that selecting the index of the first element, `df.iloc[0].index` would return `df.index[0]`, but this isn't the case. Instead it returns the columns.

```python
print(df.index)
# RangeIndex(start=0, stop=3, step=1)

print(df.iloc[0].index) 
# Index(['a', 'b', 'c'], dtype='object')
```

See a more general example below:

```python
import pandas as pd
import numpy as np

df = pd.DataFrame(np.arange(9).reshape(3,3), columns=['a', 'b', 'c'])

print(df.iloc[:, 0].index)  
# output: RangeIndex(start=0, stop=3, step=1)

print(df.iloc[0, :].index) 
# output: Index(['a', 'b', 'c'], dtype='object')

print(df.iloc[:, 0].name)
# output: a
print(df.iloc[0, :].name)
# output: 0
```

I think one should expect that `index` should always refer to one thing and `name` another regardless of how selection is made. The following may be more inline with expectation:

```python
print(df.iloc[:, 0].index)  
# output: RangeIndex(start=0, stop=3, step=1)

print(df.iloc[0, :].index) 
# output: RangeIndex(start=0, stop=1, step=1)

print(df.iloc[:, 0].name)
# output: Index(['a'], dtype='object')
print(df.iloc[0, :].name)
# output: Index(['a', 'b', 'c'], dtype='object')
```

**Comment by samukweku** [comment]
When you select a single row, pandas returns a Series, with the columns transformed into the index. this is why you think it is off. If however, you select a single row with a list, then pandas returns a DataFrame. Using your example data:

```py
df.iloc[:, 0] # scalar value
Out[22]:
0    0
1    3
2    6
Name: a, dtype: int64
```
```
df.iloc[[0]] # list selection
Out[27]:
   a  b  c
0  0  1  2

In [28]: df.iloc[[0]].index
Out[28]: Index([0], dtype='int64')
```

**Comment by mroeschke** [comment]
Thanks for the issue but as explained above this is the expected behavior based on whether a column or row is selected so closing as a usage question
