### ISSUE TITLE
BUG: pandas.read_parquet fails to read parquet files with "file://" prefix on Windows

### ISSUE THREAD

**Issue by hyounggyu** [pandas-dev/pandas#58993]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
# Place the following files in E:\tmp:
# 
# - ab.parquet
# - a b.parquet


import pandas

p0 = "E:/tmp/a b.parquet" 
p1 = "file://E:/tmp/a b.parquet"
p2 = "file://E:/tmp/ab.parquet"
p3 = "file://E:/tmp/a%20b.parquet"

pandas.read_parquet(p0)  # Should succeed
pandas.read_parquet(p1)  # Should succeed
pandas.read_parquet(p2)  # Fails
pandas.read_parquet(p3)  # Fails
```

### Issue Description

When attempting to read Parquet files using pandas.read_parquet with a "file://" prefix in the file path, the function raises a FileNotFoundError. This issue occurs specifically when using paths with the "file://" prefix, regardless of whether the space character is URL encoded or not.

### Expected Behavior

All paths (p0, p1, p2, and p3) should be read successfully without any exceptions.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.11.9.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.22631
machine               : AMD64
processor             : Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : Korean_Korea.949

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : 70.0.0
pip                   : 24.0
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.6.0
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 16.1.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>

**Comment by Aloqeely** [comment]
Thanks for the report! The number of slashes should be 1 or 3 (e.g. `"file:/"` or `"file:///"` but not `"file://"`)
For more information, see [File URI scheme (Wikipedia)](https://en.wikipedia.org/wiki/File_URI_scheme)

**Comment by hyounggyu** [comment]
It works well! Thank you!!
