### ISSUE TITLE
BUG: csv date inconsistencies

### ISSUE THREAD

**Issue by rdeteix** [pandas-dev/pandas#58996]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
from io import BytesIO

csv_data = """name,date
Alice,13/06/2024
Bob,11/05/2017"""

pd.read_csv(
    BytesIO(csv_data.encode('utf-8')), parse_dates=['date'], dtype=str
)
```

### Issue Description

with version 2.1.3 I have:

name,date
Alice,13/06/2024
Bob,11/05/2017

and with 2.2.1:

name,date
Alice, 1718236800000000000
Bob, 1494460800000000000

### Expected Behavior

name,date
Alice,13/06/2024
Bob,11/05/2017

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : bdc79c146c2e32f2cab629be240f01658cfb6cc2
python                : 3.12.1.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 22.6.0
Version               : Darwin Kernel Version 22.6.0: Mon Apr 22 20:54:28 PDT 2024; root:xnu-8796.141.3.705.2~1/RELEASE_X86_64
machine               : x86_64
processor             : i386
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : None.UTF-8

pandas                : 2.2.1
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : 69.5.1
pip                   : 24.0
Cython                : None
pytest                : 7.4.4
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : 3.1.1
lxml.etree            : 5.1.0
html5lib              : 1.1
pymysql               : None
psycopg2              : None
jinja2                : 3.1.4
IPython               : 8.21.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.2
bottleneck            : 1.3.7
dataframe-api-compat  : None
fastparquet           : 2024.2.0
fsspec                : 2023.12.2
gcsfs                 : None
matplotlib            : 3.8.4
numba                 : None
numexpr               : 2.8.7
odfpy                 : None
openpyxl              : 3.1.2
pandas_gbq            : None
pyarrow               : 14.0.2
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : 2024.2.0
scipy                 : 1.13.0
sqlalchemy            : 2.0.25
tables                : None
tabulate              : 0.9.0
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2023.3
qtpy                  : None
pyqt5                 : None
</details>

**Comment by rdeteix** [comment]
Though it works with `dtype='string[pyarrow]'`

**Comment by Aloqeely** [comment]
Thanks for the report! I believe this is fixed on main, this is the output for me: 
```python
    name                 date
0  Alice  2024-06-13 00:00:00
1    Bob  2017-05-11 00:00:00
```
