### ISSUE TITLE
DOC: punctuation of titles in Titanic data

### ISSUE THREAD

**Issue by tanyabouman** [pandas-dev/pandas#58990]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html

### Documentation problem

In the example data of the Titanic passengers, the titles are all listed with a period after them.  For Miss and Master, this is incorrect because these titles aren't short for anything.

References:
https://www.scribbr.com/effective-communication/ms-mrs-miss/
https://www.grammarly.com/blog/ms-mrs-miss-difference/
https://www.merriam-webster.com/dictionary/Mrs.

### Suggested fix for documentation

Replace Miss. with Miss and Master. with Master

Places to make changes:
- the tutorial text
- the csv file
- the screenshot of a spreadsheet containing the data

I don't see an option to assign the issue to myself, but I can do it.

**Comment by Aloqeely** [comment]
Thanks for spotting that! I have assigned the issue to you.
