### ISSUE TITLE
ENH: Pivot Table

### ISSUE THREAD

**Issue by maurovmorais** [pandas-dev/pandas#59005]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

To create a dynamic table, is it possible to make the generated table editable when saved in an excel file? In other words, when I click on the result of the dynamic table, will the Excel table edit field open?
![pandas](https://github.com/pandas-dev/pandas/assets/25842043/22c88e8b-50fa-44a4-9c47-76707da34cb1)

### Feature Description

Maybe leave a boolean option

### Alternative Solutions

pivot_tab = pd.pivot_table(editable=True,...)

**Comment by rhshadrach** [comment]
Thanks for the request. pandas uses third party packages to read / write Excel files, and I think this is well outside the scope. I will say it does sound like an interesting third party package.

Closing as out of scope.
