### ISSUE TITLE
BUG: docker build on windows fails; need eol=lf in .gitattributes

### ISSUE THREAD

**Issue by pwm1234-sri** [pandas-dev/pandas#59000]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
``python -m pip install -ve . --no-build-isolation --config-settings editable-verbose=true`` fails when run in a docker container on a windows host.
```

### Issue Description

I followed Option 3 Using Docker instructions to set up a pandas build environment. When I ran the pip install command in my container on a windows host, the build failed because ``generate_version.py`` has CRLF line endings. (I checked, my ``~/.gitconfig`` and it has autocrlf=false.) But CRLF line endings are not allowed in a shebang script. When I added ``eol=lf`` to line 1 of ``.gitattributes`` the problem went away. So, I think [line 1 of .gitattributes](https://github.com/pandas-dev/pandas/blob/main/.gitattributes#L1) should be

```text
* text=auto eol=lf
```

### Expected Behavior

For ``python -m pip install -ve . --no-build-isolation --config-settings editable-verbose=true`` to succeed.

### Installed Versions

2.2.2

**Comment by Aloqeely** [comment]
Thanks for the report! There's an open issue to track bug reports related to meson in #49683, could you report there instead?

I also have had that issue when building using Docker on Windows and have posted there.

**Comment by pwm1234-sri** [comment]
Yes, this looks to be the exact same error as you mention in https://github.com/pandas-dev/pandas/issues/49683#issuecomment-2069359651. Since there is already this link that shows up, is there anything else I should do?
