### ISSUE TITLE
DOC: Link to SPEC 0 instead of NEP 29

### ISSUE THREAD

**Issue by Aloqeely** [pandas-dev/pandas#59010]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/development/policies.html#python-support 

### Documentation problem

NEP 29 has been superseded by SPEC 0

### Suggested fix for documentation

We should link to [SPEC 0](https://scientific-python.org/specs/spec-0000/#description) instead.

**Comment by tilovashahrin** [comment]
Hello, I want to tackle this issue and see if I can contribute!

**Comment by Aloqeely** [comment]
@tilovashahrin sure!
