### ISSUE TITLE
BUG: `to_parquet(engine="fastparquet")` can't handle DataFrame with NumPy array values

### ISSUE THREAD

**Issue by whitphx** [pandas-dev/pandas#59012]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
# Run `pip install -U numpy pyarrow fastparquet` first

import pandas as pd
import numpy as np

df = pd.DataFrame({"a": [np.array([0.0])]})

df.to_parquet(engine="pyarrow") # Works
df.to_parquet(engine="fastparquet") # Error
```

### Issue Description

`df.to_parquet` with `engine="fastparquet"` raises an error as below when the DataFrame includes NumPy array values
while `engine="pyarrow"` (default) works fine.

```
>>> df.to_parquet(engine="fastparquet") # Error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/.venv/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.venv/lib/python3.12/site-packages/pandas/core/frame.py", line 3113, in to_parquet
    return to_parquet(
           ^^^^^^^^^^^
  File "/workspace/.venv/lib/python3.12/site-packages/pandas/io/parquet.py", line 480, in to_parquet
    impl.write(
  File "/workspace/.venv/lib/python3.12/site-packages/pandas/io/parquet.py", line 349, in write
    self.api.write(
  File "/workspace/.venv/lib/python3.12/site-packages/fastparquet/writer.py", line 1304, in write
    fmd = make_metadata(data, has_nulls=has_nulls, ignore_columns=ignore,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.venv/lib/python3.12/site-packages/fastparquet/writer.py", line 904, in make_metadata
    se, type = find_type(data[column], fixed_text=fixed,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.venv/lib/python3.12/site-packages/fastparquet/writer.py", line 122, in find_type
    object_encoding = infer_object_encoding(data)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.venv/lib/python3.12/site-packages/fastparquet/writer.py", line 357, in infer_object_encoding
    raise ValueError("Can't infer object conversion type: %s" % data)
ValueError: Can't infer object conversion type: 0    [0.0]
Name: a, dtype: object
```

### Expected Behavior

The `fastparquet` engine can deal with NumPy array values.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.1.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 23.4.0
Version               : Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:41 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8103
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : None.UTF-8

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : None
pip                   : 23.2.1
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : 2024.5.0
fsspec                : 2024.6.0
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 16.1.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>

**Comment by mroeschke** [comment]
Thanks for the report, but the traceback points this to being an issue in `fastparquet` so I would recommend raising an issue in the fastparquet repo so closing
