### ISSUE TITLE
Suggestion: Warning for DataFrame colname-methodname clash

### ISSUE THREAD

**Issue by michaelaye** [pandas-dev/pandas#5904]
Would it be costly to issue a warning when one adds a column to a DataFrame that has the same name as a built-in DataFrame method?
As you know, in that case I can not do Dataframe.name to access the column but instead I get a method pointer. 
But if I'm unaware (or it's late and I forgot.. ;) ) that a method with that name exists, I could be confused for quite a while before I find out what's going on.

Example I just had:

s = Series(somedata)
Investigating the difference with
s.diff()
Looks interesting, so for easier management I want to put things in a dataframe now.
df = DataFrame(s)
df['diff'] = s.diff()

And then I tried to filter the df for some values in diff and got this:

df[df.diff > 10]
KeyError: u'no item named True'

That somehow didn't make me at all think about a name clash. In this case I eventually guessed what was wrong, but if I wouldn't know that a fancy method with a fancy name exists and I picked it as well, I guess I never would find out, what's going on.

So, if it isn't too much costs in terms of performance a name check against core methods would be really nice, I think.

**Comment by jbrockmendel** [comment]
Would it make sense to use `_internal_names_set` for this?  It'd be nice to apply similar warnings to `_accessors`.  Or in a perfect world, `self.index.names, self.columns.names`.

**Comment by gfyoung** [comment]
@jbrockmendel : I think that would be an option worth exploring.

**Comment by jreback** [comment]
see #16951 this is already an active PR
