### ISSUE TITLE
ENH: Allow to plot weighted KDEs.

### ISSUE THREAD

**Issue by LucaMingarelli** [pandas-dev/pandas#59087]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

The current implementation does not currently allow to plot weighted KDEs.

### Feature Description

Estimation of the PDF is currently done via [scipy.stats.gaussian_kde](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gaussian_kde.html#scipy.stats.gaussian_kde) which allows for a parameter `weights`.
[pandas.DataFrame.plot.kde](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.kde.html) should accept this parameter as well.

### Alternative Solutions

[Here](https://github.com/pandas-dev/pandas/blob/d9cdd2ee5a58015ef6f4d15c7226110c9aab8140/pandas/plotting/_core.py#L1411-L1522) allow to pass a parameter `weights` to [`scipy.stats.gaussian_kde`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gaussian_kde.html#scipy.stats.gaussian_kde).

**Comment by fbourgey** [comment]
I updated the following

https://github.com/fbourgey/pandas/blob/feature-plot-weighted-kde/pandas/plotting/_core.py#L1449
https://github.com/fbourgey/pandas/blob/feature-plot-weighted-kde/pandas/plotting/_matplotlib/hist.py#L266

The code works. 

Should we add one example in the function `kde` with the parameter `weights`?
Does this [function](https://github.com/fbourgey/pandas/blob/feature-plot-weighted-kde/pandas/plotting/_matplotlib/hist.py#L287) need to be updated as well?

**Comment by fbourgey** [comment]
The following code gives

```python 
s = pd.Series([1, 2, 2.5, 3, 3.5, 4, 5])
ax = s.plot.kde()
```

![Figure_0](https://github.com/user-attachments/assets/d0513d48-8e20-4a29-8a52-5c84383663d4)

Replacing with some `weights` produces
```python
weights = pd.Series([0.1, 0.0, 0.0, 0.2, 0.3, 0.4, 0.9])
ax = s.plot.kde(weights=weights)
```

![Figure_1](https://github.com/user-attachments/assets/25ef71f8-7743-4d32-9173-cfb6192dd490)


Using a Numpy Array works as well
```python 
weights = np.array([0.1, 0.4, 0.0, 0.2, 0.3, 0.4, 0.2])
```

However, passing a `list` instead 
```python 
weights = [0.1, 0.4, 0.0, 0.2, 0.3, 0.4, 0.2]
```
raises the following error
```python
  File "/Users/florianbourgey/projects/misc/pandas_gaussian_kde.py", line 7, in <module>
    ax = s.plot.kde(weights=weights)
  File "/Users/florianbourgey/projects/pandas/pandas/plotting/_core.py", line 1567, in kde
    return self(kind="kde", bw_method=bw_method, weights=weights, ind=ind, **kwargs)
  File "/Users/florianbourgey/projects/pandas/pandas/plotting/_core.py", line 1049, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
  File "/Users/florianbourgey/projects/pandas/pandas/plotting/_matplotlib/__init__.py", line 71, in plot
    plot_obj.generate()
  File "/Users/florianbourgey/projects/pandas/pandas/plotting/_matplotlib/core.py", line 500, in generate
    self._make_plot(fig)
  File "/Users/florianbourgey/projects/pandas/pandas/plotting/_matplotlib/hist.py", line 168, in _make_plot
    kwds["weights"] = type(self)._get_column_weights(self.weights, i, y)
  File "/Users/florianbourgey/projects/pandas/pandas/plotting/_matplotlib/hist.py", line 202, in _get_column_weights
    weights = weights[~isna(y)]
```
