### ISSUE TITLE
BUG: Don't apply function to grouper

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#5908]
This came up in https://github.com/pydata/pandas/issues/5264, especially [here](https://github.com/pydata/pandas/issues/5264#issuecomment-30571813), [here](https://github.com/pydata/pandas/issues/5264#issuecomment-32101503), and this [SO post](http://stackoverflow.com/questions/21057397/possible-bug-in-pandas-groupby-agg).

Essentially, there are cases now where the `agg` or `transform` or `apply` function is applied to the grouper. This can cause failures in some very odd ways. As a simple example:

``` python
In [25]: df = pd.DataFrame({"A": ['a', 'b', 'a', 'b'], 'B': [1, 2, 3, 4]})

In [26]: df
Out[26]: 
   A  B
0  a  1
1  b  2
2  a  3
3  b  4

[4 rows x 2 columns]

In [28]: df.groupby('A').apply(lambda x: x+1)

TypeError: Could not operate 1 with block values cannot concatenate 'str' and 'int' objects
```

The example in the SO post linked above is especially subtle because the path the code follows depends on whether or not the aggfunc is successfully applied to the `group`ing column.

I'm going to poke around the code and see what breaks. I'd propose that we apply the function to the grouper in fewer (possibly zero) cases.

**Comment by mroeschke** [comment]
This looks tested and fixed. Closing
