### ISSUE TITLE
DOC: to_sql docs should mention ADBC

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#59095]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_sql.html

### Documentation problem

The to_sql documentation does not mention anything about supporting ADBC connections. By contrast the read_sql function does:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_sql.html

### Suggested fix for documentation

Add mention / example of ADBC usage with the to_sql method

**Comment by gosuchoi** [comment]
taken

**Comment by wooseogchoi** [comment]
take
