### ISSUE TITLE
set_columns() equivalent of set_index() ?

### ISSUE THREAD

**Issue by tyarkoni** [pandas-dev/pandas#5909]
Unless I'm missing something, there's no DataFrame method analogous to set_index() for setting column values. One can directly manipulate the .columns attribute of the DF, but it's often convenient to be able to alter columns in-line after some other operation--e.g.,

`data = pd.concat([df_a, df_b], axis=1).set_columns(['a', 'b', 'c'])`

Even if there's already some equivalent longer way to do this, it might be nice to add set_columns for convenience; I've now caught myself trying to call set_columns() on a DF several times.

**Comment by ankostis** [comment]
@jtratner asked:
> Are you thinking of something like setting row label X as the columns?

Yes, it is the exact symmetrical operations of ``set_index()/reset_index()`` but for columns.
Something that today we can accomplish with:

```dft = df.T.set_index(...).T```

**Comment by ningchi** [comment]
Hi, I notice that `set_index() / reset_index()` still miss `axis` parameter.
So would you add the support in the future?

**Comment by jreback** [comment]
this is still an open issue - pull requests accepted

**Comment by ningchi** [comment]
Ok, I'd like to take a try, as `axis` is useful for me and `df.T.set_index().T` is a little hacky.

**Comment by ningchi** [comment]
Which function might be a good example/reference for the modification? 
Any advice/suggestion are appreciated.

**Comment by ningchi** [comment]
Sorry, I misunderstand the post.      
`df.columns = ` is the function I need.

By the way,
add `axis` for `set_index / reset_index` might be not a good idea, as it will introduce the problem as said by @jtratner.

**Comment by mwiebusch78** [comment]
I think an `axis` argument to `set_index` would be a good idea since for the `df.columns = ` method you have to create a new variable. A common case is where you want to rename the columns of a data frame before joining it to another one:

```
df.join(df2.set_index(['X', 'Y', 'Z'], axis=1))
```

This is much more elegant than

```
df3 = df2.copy()
df3.columns = ['X', 'Y', 'Z']
df.join(df3)
```

and still better than

```
df.join(df2.rename(columns={'A': 'X', 'B': 'Y', 'C': 'Z'}))
```

**Comment by JohanKahrstrom** [comment]
I agree with @mwiebusch78. I work as a Data Scientist, and I often have a dataframe with some data that I want to aggregate in several different ways in a notebook. I'd prefer to not have to litter the namespace with temporary variable names just to change the column names.

A made up example would be the following, where I do a groupby and aggregate each column in several ways and end up with a multi-index, which I'd like to flatten. Today I'd have to do something like this:

```
import pandas as pd
import seaborn as sns

iris = sns.load_dataset('iris')

df = (
    iris
    .groupby('species')
    .aggregate({
        'sepal_length': ['min', 'mean', 'median', 'max'],
        'sepal_width': ['min', 'mean', 'median', 'max']
    })
)

df.columns = ['_'.join(col) for col in df.columns]
df
```

But I'd *much* prefer if something like this was available:

```
(
    iris
    .groupby('species')
    .aggregate({
        'sepal_length': ['min', 'mean', 'median', 'max'],
        'sepal_width': ['min', 'mean', 'median', 'max']
    })
    .pipe(lambda df: df.set_index(['_'join(col) for col in df.columns]))
)
```

Agreed, the pipe isn't very pretty, but it lets me avoid naming the resulting dataframe.

**Comment by jreback** [comment]
+1 on adding api here have been resistant for a long time but this makes sense

**Comment by rhshadrach** [comment]
How is `set_columns` different from `set_axis` with `axis="columns"`?

```
df = pd.DataFrame({'a': [1, 1, 2], 'b': [3, 4, 5]})
print(df.set_axis(['e', 'f'], axis='columns'))
#    e  f
# 0  1  3
# 1  1  4
# 2  2  5
```

**Comment by jorisvandenbossche** [comment]
I wanted to mention that in this specific case one could also use `rename` with passing a function (so you can do this in method chaining without having to know the exact names to pass but based on the names of the previous step in the chain), like:

```
df = (
    iris
    .groupby('species')
    .aggregate({
        'sepal_length': ['min', 'mean', 'median', 'max'],
        'sepal_width': ['min', 'mean', 'median', 'max']
    })
    .rename(columns=lambda col: '_'.join(col))
)
```

But that actually doesn't work, as it seems we pass individual labels per level to the rename function, and not the full column name as a tuple .. (so the lambda function is called with `"sepal_length"` and with `"min"`, instead of once with `("sepal_length", "min")` for that column). I found that a unexpected though .. (didn't directly find an issue about it)

**Comment by JohanKahrstrom** [comment]
@rhshadrach Wonderful, didn't know about that function, solves my use case! 👍

**Comment by rhshadrach** [comment]
One other reason to oppose `.set_columns(['a', 'b', 'c'])`; this makes the column labels themselves be 'a', 'b', and 'c'. On the other hand, this is not how `.set_index(['a', 'b', 'c'])` behaves. `set_index` uses the values in the columns 'a', 'b', and 'c' to set the labels. I would therefore find the name `set_columns` to be confusing.

I am wondering if there are other use cases of setting column labels that `set_axis` does not cover.

**Comment by MarcoGorelli** [comment]
shall we close? doesn't look like anything needs adding on top of set_axis?

**Comment by mroeschke** [comment]
Agreed, I think set_axis should be sufficient so closing

**Comment by MarkRotchell** [comment]
Can we re-open this discussion for the use case of setting columns based on (row) index labels? `set_index` accepts either column labels or array-like, whereas `set_axis` doesn't accept labels, so can't necessarily be used to set columns based on data in the DataFrame when chaining. For example, consider:

```
>>> df = pd.DataFrame({'a':['foo','bar','baz'], 'b':['spam','eggs','chips']}, index=pd.Index(['red','blue','green'],name='color'))
>>> print(df)
         a      b
color            
red    foo   spam
blue   bar   eggs
green  baz  chips
```

we can chain a `set_index` and use a column label like:

```
>>> df.set_index('a')
         a      b
color            
red    foo   spam
blue   bar   eggs
green  baz  chips
```

but no equivalent for columns, so we can't do:
```
>>> df.set_columns('blue')
blue   bar   eggs
color            
red    foo   spam
green  baz  chips
```

Using `set_axis` with `axis='columns'` requires passing in a list-like or index, which might be fine, e.g.:

```
>>> df.set_axis(df.loc['blue'], axis='columns').drop(index='blue')
blue   bar   eggs
color            
red    foo   spam
green  baz  chips
```
but not if you're chaining, i.e. the below doesn't make sense
```
>>> df.assign(c=['very','naughty','boy']).set_axis(df.loc['blue'], axis='columns').drop(index='blue')
```
It can be achieved with transposition, but this is clunky, and `transpose` requires copies on mixed-dtype arrays

```
>>> df.assign(c=['very','naughty','boy']).transpose().set_index('blue').transpose()
blue   bar   eggs naughty
color                    
red    foo   spam    very
green  baz  chips     boy
```

Obviously it can be done if you're willing to stop chaining and create a new temporary variable, but I always feel annoyed having to break a chain for something that seems so natural for the API to be able to do.

Are there any other ways to do it?

If, not, some possible options to address this use case:

- a new `set_columns` method in the API. 
- adding an `axis` parameter to `set_index`
- allowing `set_axis` to accept labels like `set_index`

**Comment by rhshadrach** [comment]
Reopened. I'm curious as to what use-case you run into where you set the column labels based off of values in a single row? Can you share any details here?

For implementation, columns and rows do not behave the same. In particular, to remove a row from a DataFrame we must copy all the data. This is not the case with a column.

**Comment by phofl** [comment]
Closing again, I don't think that we want to encourage use-cases like this since as @rhshadrach mentioned this copies all the data every time you do this. Please ping to reopen if you can provide use-cases where this would be helpful
