### ISSUE TITLE
DOC: "Accelerated operations" talks about speedup in obsolete versions of Pandas

### ISSUE THREAD

**Issue by wjandrea** [pandas-dev/pandas#59130]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/user_guide/basics.html#accelerated-operations

Permalink to specific line:

https://github.com/pandas-dev/pandas/blob/a89f20853591516b4ba45a1fbadbf645247d133e/doc/source/user_guide/basics.rst?plain=1#L161

### Documentation problem

0.11.0 is more than 10 years old and, of course, before the first stable release.

### Suggested fix for documentation

If the important thing is the speedup you get from enabling a feature, then just talk about the speedup instead of when the feature first became available.

Something like this:

```rst
    :header: "Operation", "With speedup (ms)", "Without speedup (ms)", "Ratio"
```

**Comment by Aloqeely** [comment]
Thanks for the suggestion! While this change would in fact portray the speed difference, the problem with it is that the speeds may become inaccurate overtime, so I think keeping the version number is necessary.

How about updating it with something like: `v2.2.0 with speedup (ms)` and `v2.2.0 without speedup (ms)`

**Comment by mroeschke** [comment]
I would recommend just removing that timing table section and just linking to https://pandas.pydata.org/pandas-docs/stable/user_guide/enhancingperf.html#eval-performance-comparison instead

**Comment by TheRockStarDBA** [comment]
Is this still up .. as first time contributor, I would like to work on this if possible ?

**Comment by TheRockStarDBA** [comment]
@BadakalaYashwanth or @mroeschke can I take over this issue ? seems like [BadakalaYashwanth](https://github.com/BadakalaYashwanth) has not seen this update.

**Comment by BadakalaYashwanth** [comment]
> @BadakalaYashwanth or @mroeschke can I take over this issue ? seems like [BadakalaYashwanth](https://github.com/BadakalaYashwanth) has not seen this update.

Hi @TheRockStarDBA,

Apologies for missing your update. You can certainly take over the issue. Please let me know if there’s anything specific you need from me or if there are any additional details I should be aware of.

Thanks for stepping in!

Best,
Badakala Yaswanth

**Comment by TheRockStarDBA** [comment]
take

**Comment by KevsterAmp** [comment]
@TheRockStarDBA are you still working on this?

**Comment by TheRockStarDBA** [comment]
@KevsterAmp yes .. submitting a PR soon.

**Comment by anuk909** [comment]
@TheRockStarDBA Hey, I tried to play a little bit with devin and open source and he chose this issue out of the many "easy" issues that exists in this repo. He solved the problem by removing it but if you have better solution it will probably be better.
