### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by Happiness-in-Danger** [pandas-dev/pandas#59149]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/3172929/operationalerror-database-is-locked

### Question about pandas

![Image_1719753762358](https://github.com/pandas-dev/pandas/assets/45912561/07e22cab-0072-40e8-a396-bb4cee3abfa2)

The picture is error log

My program transfers the downloaded data to the database by to_sql.The programe is closed like Ctrl+C and closed terminal ，and when I restart my programe，the datebase is locked.Even though I've tried to delay retrying.I close the cursor and connection of the data through the atexit module when the program is closed.But The problem remains.
I don't know how to solve this problem. She has been bothering me for a long time.Thanks

**Comment by MarcoGorelli** [comment]
thanks for the report

not sure what to do here, nor whether it's related to pandas - closing for now then to reduce the issue queue, but happy to reopen if you provide more details
