### ISSUE TITLE
VOTE: Voting issue for PDEP-14: Dedicated string data type for pandas 3.0 

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#59160]
### PDEP number and title

PDEP-14: Dedicated string data type for pandas 3.0

### Pull request with discussion

#58551

### Rendered PDEP for easy reading

https://jorisvandenbossche.github.io/pandas-website-preview/pdeps/0014-string-dtype.html

### Voting will close in 15 days.

July 16

### Vote

Cast your vote in a comment below.
* +1: approve.
* 0: abstain.
    * Reason: A one sentence reason is required.
* -1: disapprove
    * Reason: A one sentence reason is required.
A disapprove vote requires prior participation in the linked discussion PR.

@pandas-dev/pandas-core

**Comment by jorisvandenbossche** [comment]
+1

**Comment by WillAyd** [comment]
+1

**Comment by Dr-Irv** [comment]
+1

one small note - the PDEP talks about the "future" numpy 2.0, but now numpy 2.0 has been released....

**Comment by bashtage** [comment]
+1

**Comment by phofl** [comment]
+1

**Comment by jbrockmendel** [comment]
+1

**Comment by mroeschke** [comment]
+1

**Comment by jreback** [comment]
+1

**Comment by lukemanley** [comment]
+1

**Comment by MarcoGorelli** [comment]
+1

**Comment by attack68** [comment]
+1

**Comment by phofl** [comment]
Result: 13-0-0-8

The PDEP was accepted
