### ISSUE TITLE
ENH: In pd.cut(), allow bins='auto' (leveraging `np.histogram_bin_edges`)

### ISSUE THREAD

**Issue by Hari-Shankar-Karthik** [pandas-dev/pandas#59165]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

While converting a quantitative variable into a qualitative one, `pd.cut()` comes in clutch. However, it requires the user to specify `bins` as either an integer or a list of bin edges. I wish it was allowed to specify `bins='auto'` similar to how `np.histogram` allows it. It internally leverages `np.histogram_bin_edges` to compute these. Thank you.

### Expectation
Instead of coding 
`pd.cut(df['x1'], bins=np.histogram_bin_edges(df['x1'], bins='auto'))`
Allow for coding
`pd.cut(df['x1'], bins='auto')`

### Additional Context

Calculation of bin edges is already done via `np.histogram_bin_edges`. Reference: https://numpy.org/doc/stable/reference/generated/numpy.histogram_bin_edges.html#numpy-histogram-bin-edges

**Comment by Aloqeely** [comment]
Thanks for the suggestion! It appears there was an effort to allow string bins in `pd.cut` in #23567 but that PR got stale.
PRs are welcomed to add string bins support, dispatching the string to `np.histogram_bin_edges`.

**Comment by chaarvii** [comment]
Hey, I'd like to work on this. Available to pick up?

**Comment by chaarvii** [comment]
Take

**Comment by chaarvii** [comment]
Hey, for this ENH, do we wish to support only "auto" or all modes supported by `np.histogram_bin_edges`. I believe adding support for all would be better but not sure if I am missing something.

**Comment by chaarvii** [comment]
It was discussed that since the implementation is fairly straight-forward, its better to just add in documentation explaining how to use `np.histogram_bin_edges` with `pd.cut`

Hence, opened a new PR #59281  and closing previous one i.e. #59241
