### ISSUE TITLE
BUG: incorrect cummax() results when applied to PyArrow dtypes

### ISSUE THREAD

**Issue by Lorenzo-R** [pandas-dev/pandas#59174]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
s = pd.Series([-5, -2, -3, 1, 4, 3.0], dtype="float64")

s.cummax()
# 0   -5.0
# 1   -2.0
# 2   -2.0
# 3    1.0
# 4    4.0
# 5    4.0
# dtype: float64


s.astype("double[pyarrow]").cummax()
# 0    0.0
# 1    0.0
# 2    0.0
# 3    1.0
# 4    4.0
# 5    4.0
# dtype: double[pyarrow]


s.cummax().iat[0]
# -5.0

s.astype("double[pyarrow]").cummax().iat[0]
# 2.2250738585072014e-308

float.hex(s.astype("double[pyarrow]").cummax().iat[0])
# '0x1.0000000000000p-1022'
```

### Issue Description

Series.cummax() results are wrong when the Series has a PyArrow floating point dtype (either `double[pyarrow]` or `float[pyarrow]` ) and the first elements are negative.

When the correct cummax value would be negative, cummax actually returns the subnormal number: `2.2250738585072014e-308` (for `double[pyarrow]` dtypes)

### Expected Behavior

cummax() results are the same regardless of the dtype.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.4.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 5.15.146.1-microsoft-standard-WSL2
Version               : #1 SMP Thu Jan 11 04:09:03 UTC 2024
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : C.UTF-8
LOCALE                : C.UTF-8

pandas                : 2.2.2
numpy                 : 2.0.0
pytz                  : 2024.1
dateutil              : 2.9.0
setuptools            : 70.1.1
pip                   : 24.0
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : 8.26.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 16.1.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>

**Comment by mroeschke** [comment]
Thanks for the report, but this looks like an upstream issue in pyarrow. Mind raising an issue in the arrow repo?

```python
In [1]: import pyarrow as pa

In [2]: pa.__version__
Out[2]: '15.0.1'

In [3]: import pyarrow.compute as pc

In [4]: pc.cumulative_max(pa.array([-5, -2, -3, 1, 4, 3.0], type=pa.float64()))
Out[4]: 
<pyarrow.lib.DoubleArray object at 0x1599830a0>
[
  2.2250738585072014e-308,
  2.2250738585072014e-308,
  2.2250738585072014e-308,
  1,
  4,
  4
]

In [5]: import numpy as np

In [6]: np.maximum.accumulate(np.array([-5, -2, -3, 1, 4, 3.0], dtype=np.float64))
Out[6]: array([-5., -2., -2.,  1.,  4.,  4.])
```

Closing as an upstream issue.
