### ISSUE TITLE
ENH: Add Dict type to pd.concat objs

### ISSUE THREAD

**Issue by JulienManulife1** [pandas-dev/pandas#59176]
### Feature Type

- [X] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Pandas append allowed dict type and since deprecating append, concat has not been amended to follow suite

### Feature Description

Add dict-like object to concat method to mimic append functionality

### Alternative Solutions

If you would rather document here the recommended methodology for converting a dict like object to a dataframe

**Comment by Aloqeely** [comment]
Thanks for the suggestion! If I understood you correctly, you want another way of doing `append(dict)` since append is now deprecated? You can create a `DataFrame` from the dictionary and then use `concat`, something like: 
```python
df = ...
dictionary_df = pd.DataFrame([dictionary])  #  assuming the dictionary is 1 row of values
pd.concat([df, dictionary_df])
```
Does this work for your case?

**Comment by JulienManulife1** [comment]
Thanks for the quick reply
I tried something along those lines-- I used pd.DataFrame.from_dict(d) but I get 
AttributeError: 'dict' object has no attribute 'index'
And couldn't figure that one out

**Comment by JulienManulife1** [comment]
Hey,

Sorry for the trouble. Turns out the error is unrelated to this and from some other code afterwards. Thanks for your help!

**Comment by JulienManulife1** [comment]
Oh, this was the error, not the one above. 
ValueError: If using all scalar values, you must pass an index
but I was able to solve by including square brackets as per your example. so 
pd.concat([df,pd.DataFrame.from_dict([d])],
instead of 
pd.concat([df,pd.DataFrame.from_dict(d)],

**Comment by Aloqeely** [comment]
Yep, if the dictionary is for values of 1 row only then you should put square brackets around it. Glad I could help you!
