### ISSUE TITLE
ENH: Follow dict color in pandas plotting

### ISSUE THREAD

**Issue by maddytae** [pandas-dev/pandas#59199]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Should it not be more intuitive that plot color strictly follows the color dict and not depend on the order in which col appears in the dataframe? 

```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Create sample data
np.random.seed(0)
df = pd.DataFrame({
    'x': np.random.rand(50),
    'y': np.random.rand(50),
})

# Create bar plot with x in red and y in green using pandas.plot
ax = df[['y','x']].plot(kind='bar', color={'x':'red', 'y':'green','z':'brown'},stacked=True, figsize=(12, 6))

# Customize the plot
plt.title('Bar Plot with X in Red and Y in Green')
plt.xlabel('Index')
plt.ylabel('Values')
plt.legend(['x', 'y'])

# Adjust layout to prevent cutting off labels
plt.tight_layout()

# Show the plot
plt.show()
```

### Feature Description

Also looks like pandas plot is heavily geared towards wide data format and it can be very useful if the approach changes towards the long data format.

### Alternative Solutions

Make color follow the color dict.

### Additional Context

NA

**Comment by maddytae** [comment]
```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Create sample data
np.random.seed(0)
df = pd.DataFrame({
    'x': np.random.rand(20),
    'y': np.random.rand(20),
})

k=df[['y','x']].copy()
# Create bar plot with x in red and y in green using pandas.plot
ax1=k.plot( kind='bar', color={'x':'blue', 'y':'green','z':'brown'},stacked=True, figsize=(12, 6))
ax2=df.plot( kind='bar', color={'y':'green', 'x':'blue','z':'brown'},stacked=True, figsize=(12, 6))

```

notice that ax2 plots correct x and y color regardless of the order in dict while ax1 does not.

**Comment by ritwizsinha** [comment]
@maddytae  Thanks for submitting the issue !
It seems like there is some mistake in the legend part of matlplotlib instead of any problem from pandas side. Here is an example
```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Create sample data
np.random.seed(0)
df = pd.DataFrame({
    'x': [0.1,0.2,0.3],
    'y': [1,2,3],
    'z': [10,20,30]
})
# Create bar plot with x in red and y in green using pandas.plot
ax = df[['z', 'x', 'y']].plot(kind='bar', color={'x':'blue', 'y':'green','z':'red'},stacked=True, figsize=(12, 6))

# Customize the plot
plt.title('Bar Plot with X in Red and Y in Green and z in Blue')
plt.xlabel('Index')
plt.ylabel('Values')
plt.legend(['x', 'y', 'z'])

# Adjust layout to prevent cutting off labels
plt.tight_layout()

# # Show the plot
plt.show()
```
I have taken non random values for scaling.
This produces the following map.
![image](https://github.com/pandas-dev/pandas/assets/43509699/8018597b-b796-4c12-94c7-f0a3f8f36e8c)
- x is blue which is the smallest part
- y is green which is bigger part
- z is red which is the biggest part.
The bar is correct, its the legend which labels it wrong, it creates labels as x, y, z whereas labels should be z, x, y because that is what was plotted.

Please correct me if I am wrong
Thanks!

**Comment by ritwizsinha** [comment]
take
