### ISSUE TITLE
BUG: Series constructor with category dtype does not raise with unknown categories

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#59204]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
Assignment fails as expected:


>>> cat = pd.CategoricalDtype(["foo", "bar", "baz"])
>>> ser = pd.Series(["foo", "baz", "baz"], dtype=cat)
>>> ser.iloc[2] = "qux"
TypeError: Cannot setitem on a Categorical with a new category (qux), set the categories first


But the constructor just maps this to a missing value:
```python
>>> pd.Series(["foo", "baz", "baz", "qux"], dtype=cat)
Out[13]: 
0    foo
1    baz
2    baz
3    NaN
dtype: category
Categories (3, object): ['foo', 'bar', 'baz']
```
```


### Issue Description

The Series constructor allows you to use values that are not part of the categorical values, mapping them to missing

### Expected Behavior

I think the constructor should fail just like assignment does

### Installed Versions

main

**Comment by WillAyd** [comment]
This might be another one of those constructors quirks @Aloqeely and I were chatting about on Slack recently

**Comment by WillAyd** [comment]
Though our documentation does rely on this behavior https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.cat.set_categories.html

Maybe it is considered a feature?

**Comment by jbrockmendel** [comment]
Xref #40996

**Comment by WillAyd** [comment]
Ah thanks - this is a dupe then

**Comment by jbrockmendel** [comment]
I like your framing of it as a bug, would be happy to keep this one and
close the other.
