### ISSUE TITLE
BUG: `pandas.tseries.frequencies.to_offset()` raises `ValueError` when parsing a `LastWeekOfMonth` frequency string

### ISSUE THREAD

**Issue by ypsah** [pandas-dev/pandas#59218]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
pd.tseries.frequencies.to_offset(pd.offsets.LastWeekOfMonth().freqstr)
```

### Issue Description

The code above raises the following exception:
```python-traceback
Traceback (most recent call last):
  File "offsets.pyx", line 4776, in pandas._libs.tslibs.offsets._get_offset
KeyError: 'LWOM'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "offsets.pyx", line 4946, in pandas._libs.tslibs.offsets.to_offset
  File "offsets.pyx", line 4782, in pandas._libs.tslibs.offsets._get_offset
ValueError: Invalid frequency: LWOM-MON, failed to parse with error message: KeyError('LWOM')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "offsets.pyx", line 4791, in pandas._libs.tslibs.offsets.to_offset
  File "offsets.pyx", line 4954, in pandas._libs.tslibs.offsets.to_offset
ValueError: Invalid frequency: LWOM-MON, failed to parse with error message: ValueError("Invalid frequency: LWOM-MON, failed to parse with error message: KeyError('LWOM')")
```

I've tracked down the issue to `LastWeekOfMonth` not being present here: https://github.com/pandas-dev/pandas/blob/d96646219618e007f64ee49e0a6e20f4aea761b5/pandas/_libs/tslibs/offsets.pyx#L4647.

### Expected Behavior

`pd.tseries.frequencies.to_offset` can parse any `LastWeekOfMonth` frequency string.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.4.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.9.7-arch1-1
Version               : #1 SMP PREEMPT_DYNAMIC Fri, 28 Jun 2024 04:32:50 +0000
machine               : x86_64
processor             : 
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 2.0.0
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : None
pip                   : 24.0
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None
None

</details>

**Comment by aram-cinnamon** [comment]
take

**Comment by ypsah** [comment]
Thanks
