### ISSUE TITLE
ENH: is it worth fixing a warning from a third party library here

### ISSUE THREAD

**Issue by quant12345** [pandas-dev/pandas#59226]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wanted to fix a warning in another library:
`FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use ser.iloc[pos]`

As it turns out, these lines are from pandas.

### Feature Description

pandas/tests/extension/base/getitem.py  row --- 276
pandas/tests/extension/base/setitem.py row --- 244

Does this need to be fixed?

I also wanted to run this test directly, but I couldn’t:
`pytest pandas/tests/extension/base/getitem.py::test_getitem_series_integer_with_missing_raises`

It is launched only like this (repeatedly everywhere where it is):
`pytest pandas -k test_getitem_series_integer_with_missing_raises `

But I can't get the warning that I get in tests of another library.

### Alternative Solutions

Use iloc.

pandas/tests/extension/base/getitem.py:
before  `ser[idx]`
after s`ser.iloc[idx]`

pandas/tests/extension/base/setitem.py:
before  `arr[idx] = arr[0]`
after s`arr[idx] = arr.iloc[0]`

**Comment by mroeschke** [comment]
Thanks for the issue. How is the third party library calling pandas? Usually this indicates that the third party library needs to adjust their usage of pandas to avoid the warning

**Comment by quant12345** [comment]
@mroeschke geopandas. I wanted to fix this, but as I said, it turned out to be pandas rows.

**Comment by mroeschke** [comment]
If you could share an entire traceback of where this warning happens that would be helpful

**Comment by quant12345** [comment]
for example, I run a test:
`pytest geopandas/tests/test_extension_array.py::TestSetitem::test_setitem_integer_with_missing_raises[list-True]`

I get a warning:
```
/home/runner/micromamba/envs/test/lib/python3.12/site-packages/pandas/tests/extension/base/setitem.py:227: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
    arr[idx] = arr[0]
```

**Comment by mroeschke** [comment]
I see thanks. 

As you can see on the pandas main branch this has been addressed so I think this should go away from the geopandas test suite once pandas 3.0 comes out

https://github.com/pandas-dev/pandas/blob/1165859bd147a0b4afa66663ad66078beb91f4fe/pandas/tests/extension/base/setitem.py#L244
