### ISSUE TITLE
NON-BUG: `to_csv()` argument `float_format` has no effect, always saves with format of "%.2g"

### ISSUE THREAD

**Issue by jack5github** [pandas-dev/pandas#59220]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
from pandas import Series

series: Series = Series(name="Bug", data=[1 / 3])
series.to_csv("float_format_bug.csv", index=False, float_format="%.6f")
# | Bug  |
# | 0.33 |
```

### Issue Description

Attempting to save `float64` values (and potentially other floating point numbers) to a .csv file with `to_csv()` causes them to forcibly be truncated to two decimal places, no matter what preventative measures are taken to circumvent this behaviour (for example, converting the numbers to strings before saving with `series.astype(str)`). The bug continues to occur if no name is given to the Series, but does not occur when `to_csv()` is given the argument `header=False`, yet this behaviour should be universal.

### Expected Behavior

Floating point numbers should be formatted according to the specification in `float_format` when saving using `to_csv()`.

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.2.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 11
Version               : 10.0.22631
machine               : AMD64
processor             : Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : English_Australia.1252

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : None
pip                   : 24.1.1
Cython                : None
pytest                : 8.2.1
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.4
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.6.1
gcsfs                 : None
matplotlib            : 3.9.1
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.3
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.14.0
sqlalchemy            : 2.0.31
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None
</details>

**Comment by Anurag-Varma** [comment]
I ran the give code:

It seems I am able to get the correct output:
```
Bug
0.333333
```

INSTALLED VERSIONS
```
------------------
commit                : f3ad4d50aee360092c54b918b28c2cba90c90f20
python                : 3.10.14
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.26120
machine               : AMD64
processor             : AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : English_United States.1252

pandas                : 3.0.0.dev0+1176.gf3ad4d50ae
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
pip                   : 24.0
Cython                : 3.0.10
sphinx                : 7.3.7
IPython               : 8.18.1
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
blosc                 : None
bottleneck            : None
fastparquet           : None
fsspec                : 2024.6.1
html5lib              : 1.1
hypothesis            : 6.105.0
gcsfs                 : 2024.6.1
jinja2                : 3.1.4
lxml.etree            : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.5
psycopg2              : None
pymysql               : 1.4.6
pyarrow               : None
pyreadstat            : None
pytest                : 8.2.2
python-calamine       : None
pyxlsb                : 1.0.10
s3fs                  : 2024.6.1
scipy                 : None
sqlalchemy            : 2.0.31
tables                : None
tabulate              : 0.9.0
xarray                : 2024.6.0
xlrd                  : 2.0.1
xlsxwriter            : 3.2.0
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None
```

**Comment by jack5github** [comment]
Discovered that this is not an issue with pandas, but rather the software being used to read the file after it has been created.
