### ISSUE TITLE
BUG: json_normalize KeyError Key not found 

### ISSUE THREAD

**Issue by Opostol** [pandas-dev/pandas#59233]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.json_normalize(data={'meta1':{'meta2':'meta_val'}, 'record1':{'record2':[{'rec1':'rec_val1'},{'rec1':'rec_val2'}]}}, meta=[['meta1','meta2']], record_path=['record1','record2'])
```

### Issue Description

fact behaviour: ` KeyError: "Key 'meta2' not found.`

### Expected Behavior

expected df = 
       rec1                  meta1.meta2
0  rec_val1  meta_val
1  rec_val2  meta_val

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.4.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.19045
machine               : AMD64
processor             : AMD64 Family 16 Model 4 Stepping 2, AuthenticAMD
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : Russian_Russia.1251

pandas                : 2.2.2
numpy                 : 2.0.0
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : None
pip                   : 24.0
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>

**Comment by Opostol** [comment]
issue raised to describe pull request
https://github.com/pandas-dev/pandas/pull/59225

**Comment by rhshadrach** [comment]
The current design requires `meta` fields to be part of the records. The example in the OP does not meet this requirement. Am I right in saying that you desire to be able to specify meta fields that are not part of the records?

**Comment by rhshadrach** [comment]
Closing in favor of #60254
