### ISSUE TITLE
API: allow read_pickle to read from strings (and not just files)

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#5924]
brought up in #5661 , #5894

**Comment by jakirkham** [comment]
FWIW with [pickle protocol 5]( https://docs.python.org/3/library/pickle.html#pickle-oob ) one can do the following...

```python
In [1]: import pickle
   ...: 
   ...: import pandas as pd

In [2]: df = pd.DataFrame({"i": [1, 2, 3], "f": [0.0, 0.5, 1.0]})

In [3]: L = []
   ...: h = pickle.dumps(df, protocol=5, buffer_callback=L.append)

In [4]: pickle.loads(h, buffers=L)
Out[4]: 
   i    f
0  1  0.0
1  2  0.5
2  3  1.0
```

So it should be possible to feed in a series of buffers this way

**Comment by mroeschke** [comment]
Closed related to https://github.com/pandas-dev/pandas/issues/53767#issuecomment-1721399821
