### ISSUE TITLE
DOC: New contributor meeting, clarify or remove

### ISSUE THREAD

**Issue by nevencaplar** [pandas-dev/pandas#59267]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/development/community.html#new-contributor-meeting

### Documentation problem

The documentation advertises new contributor meeting, but last input in the notes documentation is from November 15, 2023 and the meeting does not seem to be happening, as verified today (July 17, 2024). 

### Suggested fix for documentation

Either remove the entry or clarify that this meeting is hibernated. This would be better than the existing statement which seems to be inaccurate.

**Comment by Aloqeely** [comment]
Thanks for the report! I believe the new contributor meeting is still being held as it can be seen on the calendar.

But, it does seem like the notes are not being taken for recent meetings, my guess is that there is not much benefit to save notes for this type of meeting but I'm not sure.

**Comment by nevencaplar** [comment]
I believe this is not true. Even though it was on calendar, nobody was there yesterday, July 17. This combined with the lack of notes is why I opened this issue.

**Comment by Aloqeely** [comment]
Ah. Last time I attended the meeting was a few months ago so I'm not sure who attends these meetings from the core team.
cc @jorisvandenbossche

**Comment by WillAyd** [comment]
@pandas-dev/pandas-core has anyone been attending these lately?

**Comment by rhshadrach** [comment]
I have been attending, but missed the last one. We will announce whether there will be a core developer present ahead of time in the New Contributors slack channel ([see here](https://pandas.pydata.org/docs/dev/development/community.html#community-slack)).

I've added a line to the [meeting notes](https://hackmd.io/HKzJoy22QqSqte834QEr1A) that notes are no longer being kept but that the meeting is still active.

I don't believe there is anything else to do here, closing for now. If there are further actions to take, comment below and we can reopen.
