### ISSUE TITLE
BUILD: 

### ISSUE THREAD

**Issue by Praba0502** [pandas-dev/pandas#59260]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

import pandas as pd

### Installation Method

pip install

### pandas Version

pandas 3.0

### Python Version

3.12.1

### Installation Logs

<details>

Replace this line with the installation logs.
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
</details>

**Comment by mroeschke** [comment]
Thanks for the report, but the logs is just a warning and should not affect the ability to use pandas.

This warning was removed and will not been seen if you install pandas 2.2.2. Closing
