### ISSUE TITLE
ENH: Support right hand side operations with Series and custom classes

### ISSUE THREAD

**Issue by tm-slavik57** [pandas-dev/pandas#59263]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish I could add a custom class to pandas series and to "hint" the series object to use the `__radd__` method of the custom class with the series.

I have a class:
```
class DataWrapper:
  def __init__(data: List[float]):
    self.data=data

  def __radd__(self, other):
    return DataWrapper(self.data + other)
```

I perform the following operation:
```
series = pd.Series([1,2])
data = DataWrapper([3,4])

result = series + data
```

This will call the `__radd__` method per item in the underlying numpy array (1 and 2) and return a `pd.Series`
Adding the `__array_ufunc__ = None` (taken from numpy) will result in a call to `__radd__` with the entire underlying numpy array but still the result will be `pd.Series`.
I would like pandas to either use the `__array_ufunc__ = None` as a hint to return `NotImplemented` from it's `__add__` method and allowing the `__radd__` method to be called with the series.
If using the `__array_ufunc__ = None` will break previous behaviour, there could be another option of doing it.

### Feature Description

A few options:
1. look for `__array_ufunc__` property on the `other` class of the operation, and if it's `None` return `NotImplemented`.
2. add another flag for it with similar behaviour to `__array_ufunc__` that can be used specifically for the pandas series. This can be global for all the operations (like numpy) or flag per operation

### Alternative Solutions

I'm not aware of any alternative solution

### Additional Context

The feature is for operations for units and quantities. I have a `Unit` and a `Quantity` classes, the `Quantity` class holds either a single value or numpy array or pandas series of numbers with a binding of a unit.

Some examples:
* `pd.Series([1,2]) * Units.meter` - should be same as `Quantity(pd.Series([1,2]), Units.meter)`. It works for numpy arrays
* `pd.Series([1,2]) * Quantity(3, Units.meter)` - should be similar to `Quantity(pd.Series([1,2]) * 3, Units.meter)`

**Comment by mroeschke** [comment]
Thanks for the report. This is already supported by defining the `__pandas_priority__` attribute on your class. See https://pandas.pydata.org/docs/development/extending.html#arithmetic-with-3rd-party-types

Closing as a usage question.
