### ISSUE TITLE
BUG: Error on to_datetime() after running multiple times in jupyter notebook

### ISSUE THREAD

**Issue by CoderTom314** [pandas-dev/pandas#59277]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
# issue cannot be reproduced directly as this occurs in Juputer Notebook: after parent function main is modified (but not directly related to the error), OR when the cell where main function is located is run several times

import pandas as pd
from datetime import timezone, timedelta
df = pd.DataFrame({'col1': ["2 January 2020 12:39 GMT", "3 January 2020 12:39 GMT"], 'col2': [3, 4]}, index=[0, 1])
def create_datetime_object_GMT(row):
    return pd.to_datetime(f'{df.loc[0,"col1"]}', format="%d %B %Y %H:%M %Z", exact=True).tz_convert(tz=timezone(timedelta(hours=0)))
    
#in a new cell
def main():
    ...
    df.insert(loc=0, column='Datetime Object GMT', value=df.apply(
                create_datetime_object_GMT, axis=1), allow_duplicates=False)
    ...
print(df)
```

### Issue Description

ValueError: time data "2 January 2020 12:39 GMT" doesn't match format "%d %B %Y %H:%M %Z", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

### Expected Behavior

expected behavior is without error correctly convert to datetime

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.10.4.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.19045
machine               : AMD64
processor             : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : Chinese (Traditional)

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : 67.6.1
pip                   : 24.1.2
Cython                : None
pytest                : 8.2.2
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 5.2.2
html5lib              : 1.1
pymysql               : 1.4.6
psycopg2              : 2.9.9
jinja2                : 3.1.4
IPython               : 8.25.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.5.0
gcsfs                 : None
matplotlib            : 3.9.0
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.4
pandas_gbq            : None
pyarrow               : 16.1.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.13.1
sqlalchemy            : 2.0.31
tables                : None
tabulate              : 0.9.0
xarray                : None
xlrd                  : 2.0.1
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>

**Comment by MarcoGorelli** [comment]
thanks for the report

`%Z` is meant to be used for `Z`, which means "UTC" - `'GMT'`

I'd suggest replacing `'GMT'` with `'Z'`
```
In [18]: pd.to_datetime(df['col1'].str.replace('GMT', 'Z'))
Out[18]:
0   2020-01-02 12:39:00+00:00
1   2020-01-03 12:39:00+00:00
Name: col1, dtype: datetime64[ns, UTC]
```

closing then, but thanks for the issue
