### ISSUE TITLE
Surprising behavior: set_index cannot set a MultiIndex from a tuple, only a list 

### ISSUE THREAD

**Issue by tadamcz** [pandas-dev/pandas#59294]
I ran into the following surprising behavior:

We can set a MultiIndex with a list of column names:
```python
import pandas as pd
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4], 'C': [5, 6]})
# Works fine
df = df.set_index(['A', 'B'])
```

However, attempting to set a MultiIndex with a tuple of column names raises a KeyError:
```python
import pandas as pd
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4], 'C': [5, 6]})
# Raises KeyError: "None of [('A', 'B')] are in the columns"
df = df.set_index(('A', 'B'))
```

This is technically consistent with the documentation of the `keys` parameter (my emphasis):

> This parameter can be either a single column key, a single array of the same length as the calling DataFrame, or a **list** containing an arbitrary combination of column keys and arrays.

But nonetheless, this is quite surprising behavior in Python.

(This occurs in the latest release as well as on the main branch)

----

The culprit appears to be this isinstance check at the beginning of the set_index method:

```python
if not isinstance(keys, list):
    keys = [keys]
```

My suggestion would be to use the pandas `is_list_like` helper function instead. 
```python
if not is_list_like(keys):
    keys = [keys]
```

To unambiguously demonstrate what I mean, I've put up a branch for this with tests: https://github.com/pandas-dev/pandas/compare/main...tadamcz:pandas:tadamcz/set-index-multiindex-from-tuple?expand=1.

If you think this would indeed be an improvement, I'd be happy to see this turned into a PR. But since I can't promise I'll have time to shepherd this through to the finish line, I thought I'd hold off on officially opening a PR?

**Comment by tadamcz** [comment]
I've created a draft PR, but only because this seemed the easiest way (?) to have your CI checks run on it: https://github.com/pandas-dev/pandas/pull/59295

**Comment by rhshadrach** [comment]
Thanks for the report. pandas treats lists vs tuples differently throughout its API. I'm quite negative on a change here.

**Comment by tadamcz** [comment]
No problem. I didn't know that.

**Comment by mroeschke** [comment]
Agreed. tuples can have specific indexing semantics so I don't think it's safe to make it a act like a collection here. Thanks for the suggestion so closing
