### ISSUE TITLE
DOC: Typo in docs for na_values parameter in pandas.read_csv function

### ISSUE THREAD

**Issue by rxu17** [pandas-dev/pandas#59314]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

### Documentation problem

Hi,
I was looking through the pandas documentation for the `na_values` parameter under `pandas.read_csv` and I noticed that there's a typo in the section:

>   By default the following values are interpreted as NaN: “ “, “#N/A”, “#N/A N/A”, “#NA”, “-1.#IND”, “-1.#QNAN”, “-NaN”, “-nan”, “1.#IND”, “1.#QNAN”, “<NA>”, “N/A”, “NA”, “NULL”, “NaN”, “None”, “n/a”, “nan”, “null “.

The `" "` is included in the list of default string to NAs starting in pandas 2.1 all the way to the current version of the docs. However, [in the code for the list of default string to NAs](https://github.com/pandas-dev/pandas/blob/main/pandas/_libs/parsers.pyx#L1373-L1393), I'm seeing `""` instead.

### Suggested fix for documentation

I think the fix should be to remove `" "` and replace with `""` in the  list of default string to NAs in the pandas docs for the versions 2.1 and up to the current version so it's consistent with the code.

Thanks for all your help!

**Comment by kushagr96** [comment]
take
