### ISSUE TITLE
DOC: Website opens search when I press Caps Lock

### ISSUE THREAD

**Issue by HiPhish** [pandas-dev/pandas#59334]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

Every page is affected.

### Documentation problem

I have the Caps Lock key remapped to CTRL on my computer (using the keyboard settings in KDE Plasma), and every time I press the Caps Lock key because I want to use the CTRL key (e.g. CTRL-C to copy text) the search box opens as if I had pressed CTRL-K. This is really annoying because it means I cannot use any shortcuts of the browser.

### Suggested fix for documentation

The issue is that the keyboard event handler of the the web page uses `/k/i.test(event.key)` to test whether the key contains `k` or `K`, and in my case the `event.key` of the browser event is the string `CapsLock`, which contains the letter `k`. And since my Caps Lock is remapped to CTRL the browser also reports that `event.ctrlKey` is `true`. Together this produces a false positive.

A simple fix would be to change the regex to `/^k$/` or to use a string comparison test like `event.key === 'k' || event.key === 'K' `.

**Comment by Aloqeely** [comment]
Thanks for the report! This looks like an issue with `pydata-sphinx-theme` which is addressed in https://github.com/pydata/pydata-sphinx-theme/issues/1645. cc @datapythonista

**Comment by mroeschke** [comment]
Thanks for the report so closing as an upstream issue. This will be fixed once we bump our sphinx theme
