### ISSUE TITLE
DOC: Make usage of `rtol` and `atol` arguments in `pd.testing.assert_frame_equal` clearer

### ISSUE THREAD

**Issue by conorhamill36** [pandas-dev/pandas#59344]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.testing.assert_frame_equal.html

### Documentation problem

When `atol` and `rtol` are used, the check of equality between two dataframes is of the form `absolute(a - b) <= (atol + rtol * absolute(b))`.

It's not clear that `atol` and `rtol` are used together like this, resulting in it being unclear what exact is being checked.

### Suggested fix for documentation

Expand the explanation of `atol` and `rtol` in the documentation, possibly explicitly including the equation that is testing equality.

**Comment by omaraliii** [comment]
assign it to me

**Comment by conorhamill36** [comment]
@omaraliii I don't seem to have the cog beside the assignees, does someone with more authorisation in this repo need to do that?

**Comment by rhshadrach** [comment]
@omaraliii - I think it would be good to review the contributor documentation. See here:

https://pandas.pydata.org/docs/dev/development/contributing.html#finding-an-issue-to-contribute-to

**Comment by tan-i-ham** [comment]
May I take this?

I will add the description near here and maybe add the example if possible
https://github.com/pandas-dev/pandas/blob/70bb855cbbc75b52adcb127c84e0a35d2cd796a9/pandas/_testing/asserters.py#L1161

**Comment by tan-i-ham** [comment]
take
