### ISSUE TITLE
QST: How does pandas ensure backward compatibility with numpy and other deps

### ISSUE THREAD

**Issue by maxkoretskyi** [pandas-dev/pandas#59351]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/78808646

### Question about pandas

If I check pandas [dependencies requirements](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#dependencies), I see the following:

```
+-------------------+--------------------------+
|     Package       | Minimum supported version|
+-------------------+--------------------------+
| NumPy             | 1.22.4                   |
+-------------------+--------------------------+
| python-dateutil   | 2.8.2                    |
+-------------------+--------------------------+
| pytz              | 2020.1                   |
+-------------------+--------------------------+
| tzdata            | 2022.7                   |
+-------------------+--------------------------+
```

I'm wondering how does pandas ensure that they are backward compatible with all the versions that were released after those specified in the table? I'm sure there are lots of tests, but it's not feasible to run tests against all possible permutations of those libs.

**Comment by mroeschke** [comment]
> I'm wondering how does pandas ensure that they are backward compatible with all the versions that were released after those specified in the table?

There is no official CI testing with all the intermediate versions of these dependencies since as you mentioned it's not feasible. pandas only tests with these dependencies pinned to the minimum versions and unpinned (presumably the latest versions of these libraries).
