### ISSUE TITLE
DOC: Low priority code smells found in "core/sorting.py"

### ISSUE THREAD

**Issue by johnyu013** [pandas-dev/pandas#59358]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://github.com/pandas-dev/pandas/blob/main/pandas/core/sorting.py

### Documentation problem

The documentation for the function get_group_index_sorter in the pandas/core/sorting.py file could be improved. The current documentation does not fully adhere to Section 2 of the documentation guidelines concerning the extended summary. Additionally, there is an issue with the naming convention for internal helper functions, specifically the maybe_lift function, which should be prefixed with an underscore.

### Suggested fix for documentation

Extended Summary Issue:
The current extended summary of the get_group_index_sorter function includes details about the parameters and implementation notes, which should be placed in other sections according to Section 2 of the documentation guidelines (https://pandas.pydata.org/docs/development/contributing_docstring.html). Furthermore, this block of comments is almost as long as the function itself, which adds unnecessary verbosity. The extended summary should focus on why the function is useful and its use cases, providing a clear and concise explanation.

Current extended summary:
https://github.com/pandas-dev/pandas/blob/7acd629fea2a32d1ace93ceab2b62d5f5f9b2d47/pandas/core/sorting.py#L629-L651

Suggested extended summary:
This function sorts group indices efficiently using a combination of counting sort and merge sort. The sorting is stable, ensuring the correctness of groupby operations, which is crucial for operations like transforming the first value of a grouped column.

Naming Convention Issue:
https://github.com/pandas-dev/pandas/blob/7acd629fea2a32d1ace93ceab2b62d5f5f9b2d47/pandas/core/sorting.py#L164C5-L164C6
The helper function maybe_lift should be renamed to _maybe_lift to indicate that it is intended for internal use only. This naming convention aligns with the project's existing practices and supports consistency in the codebase. It is also good for Python coding practices, as it clearly distinguishes internal functions from those meant for public use.

**Comment by MarcoGorelli** [comment]
thanks for the report

You're welcome to submit improvements, please check the contributing guide for how to get started - closing though as it's not really feasible to have an open issue for every potential minor internal improvement
