### ISSUE TITLE
Code smells in pandas/core/computation/pytables.py

### ISSUE THREAD

**Issue by robert-brumleve** [pandas-dev/pandas#59362]
[pandas/core/computation/pytables.py](https://github.com/pandas-dev/pandas/blob/main/pandas/core/computation/pytables.py) has a few code smells. Here is what I've found.

- Most function names use snake_case, but some function names combine mixedCase and snake_case. PEP8 suggests only using snake_case.
visit_UnaryOp
visit_Index
visit_Assign
visit_Subscript
visit_Attribute
translate_In

- The function 'convert_value' has a lot going on with few comments and a short docstring. I would suggest at least listing what is accepted by pytables (integer, float, bool, etc.) in the docstring.
- In the function 'convert_value', the variable name 'v' is too vague. I assume it means value, but perhaps changing the variable name or just adding a comment to specify this would help.
- The function 'convert_values' doesn't do anything. Can it be removed?

Thank you for reading my issue. I can work on a pull request, if necessary, after receiving feedback.

**Comment by MarcoGorelli** [comment]
thanks for the report

> visit_UnaryOp

that's just how subclassing ast works: https://docs.python.org/3/library/ast.html#ast.NodeVisitor.visit

You're welcome to submit improvements - closing though as it's not really feasible to have an open issue for every potential minor internal improvement
