### ISSUE TITLE
DOC: Link to Numpy's Git Resources in developer guide is no longer active

### ISSUE THREAD

**Issue by josh-tan-bt** [pandas-dev/pandas#59386]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/development/contributing.html

### Documentation problem

Link to Numpy's Git resources tutorial (https://numpy.org/doc/stable/dev/gitwash/git_resources.html) leads to a 404 "file not found" error

Looking at historical versions of numpy documentation, this page used to exist but was removed in version 2.0.

### Suggested fix for documentation

Remove link as it is no longer supported by NumPy, and leave link to existing Git documentation as sufficient.

**Comment by fbourgey** [comment]
take
