### ISSUE TITLE
ENH: DataFrame.info() returns a DataFrame rather than printing a table

### ISSUE THREAD

**Issue by jpeacock29** [pandas-dev/pandas#59387]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish I could use Pandas to get the information provided by DataFrame.info() in a more usable format. For example, this function currently prints a table describing each column in the DataFrame, info on Index, memory usage, etc. However, since this information is returned as string, it is difficult to use downstream. Perhaps we could add a flag like `return_info` set to False by default, but when True would return a dictionary containing the above information.

### Feature Description
```python
class DataFrame:
...
def info(return_info=False, [other existing params]):
  # existing implementation that calculates the below values
  if return_info:
    return {
      'Column summary': pd.DataFrame({'#': [0, 1, 2], 'Column': [nameCol1, nameCol2, nameCol3], 'Non-Null count': [4,2,5],...}),
      'Memory usage': 248
      'Index type': 'RangeIndex',
      'Index entries': 5,
      ...}  
```

### Alternative Solutions

I suppose you could either gather all the information manually by calling other functions and then make the JSON yourself. Or you could parse the string output of .info().

**Comment by rhshadrach** [comment]
Thanks for the feature request. It seems readily achievable to create the this in a simple function. Even better, that would give you full control over what is collected (so you could collect more or less depending on your use case). An alternative would be to vendor the code here:

https://github.com/pandas-dev/pandas/blob/642d2446060afb11f9860c79a7339eb6ec96fea7/pandas/io/formats/info.py#L442

**Comment by GuglielmoCerri** [comment]
take

**Comment by mroeschke** [comment]
Agreed that this feature is probably not worth including in pandas. Thanks for the suggestion but closing
