### ISSUE TITLE
DOC: std() delta degree of freedom vs. degree of freedom

### ISSUE THREAD

**Issue by YudiXie** [pandas-dev/pandas#59405]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.std.html#pandas.core.groupby.DataFrameGroupBy.std

### Documentation problem

I think the ddof parameter should mean "Delta Degrees of Freedom" instead of "Degrees of freedom", which is a bit confusing since "Degrees of freedom" = N - "Delta Degrees of Freedom"

### Suggested fix for documentation

change the documentation of ddof parameter to "Delta Degrees of Freedom". Like that of the numpy documentation: https://numpy.org/doc/stable/reference/generated/numpy.std.html

**Comment by KevsterAmp** [comment]
I'd like to work on this

**Comment by KevsterAmp** [comment]
take
