### ISSUE TITLE
Unit Test/CI failing for multiple PRs

### ISSUE THREAD

**Issue by kirill-bash** [pandas-dev/pandas#59420]
Looks like there are issues with several of the unit tests. Below are just some examples of PRs affected. 

[https://github.com/pandas-dev/pandas/actions/runs/10222022864](file:///private/var/containers/Bundle/Application/F7D0D6DA-C7B8-499B-ADB0-0D5334DE3F46/Bloomberg_Professional.app/msgweb/mobile_rich_text/mobile_rich_text.html#)
[https://github.com/pandas-dev/pandas/actions/runs/10252584958](file:///private/var/containers/Bundle/Application/F7D0D6DA-C7B8-499B-ADB0-0D5334DE3F46/Bloomberg_Professional.app/msgweb/mobile_rich_text/mobile_rich_text.html#)
[https://github.com/pandas-dev/pandas/actions/runs/10230701585](file:///private/var/containers/Bundle/Application/F7D0D6DA-C7B8-499B-ADB0-0D5334DE3F46/Bloomberg_Professional.app/msgweb/mobile_rich_text/mobile_rich_text.html#)
[https://github.com/pandas-dev/pandas/actions/runs/10239338109](file:///private/var/containers/Bundle/Application/F7D0D6DA-C7B8-499B-ADB0-0D5334DE3F46/Bloomberg_Professional.app/msgweb/mobile_rich_text/mobile_rich_text.html#)

**Comment by WillAyd** [comment]
Looks to be failing for a while now. At a quick glance a lot of the failures seem to be about wrong error messages, which I'm guessing have to do with a NumPy upgrade or something else. Not sure if @mroeschke has looked already

**Comment by mroeschke** [comment]
Yeah the failures are also being discussed in https://github.com/pandas-dev/pandas/issues/59372 so going to centralize the discussion there.

Hoping to look into it today or tomorrow
