### ISSUE TITLE
Python 3.13 wheel builds are failing

### ISSUE THREAD

**Issue by EwoutH** [pandas-dev/pandas#59426]
When testing the wheels, about 80 of these types of errors happen, on Python 3.13 only:
      
```
  >       assert isinstance(left, ExtensionArray), "left is not an ExtensionArray"
  E       AssertionError: left is not an ExtensionArray
```
See any [recent build on the main branch](https://github.com/pandas-dev/pandas/actions/workflows/wheels.yml?query=branch%3Amain) (like [this one](https://github.com/pandas-dev/pandas/actions/runs/10259795788/job/28384829134), full [raw log](https://productionresultssa3.blob.core.windows.net/actions-results/df87c058-0456-4e3f-9980-f00d7633a7e9/workflow-job-run-02e0c0ba-cd95-5520-7c99-3c9504ffc697/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-08-06T07%3A20%3A17Z&sig=N5PpHUCBAn%2BmLmrOwCcI4i0MV0%2BWqnBgel8jiiXZXb8%3D&ske=2024-08-06T17%3A46%3A09Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-08-06T05%3A46%3A09Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-08-06T07%3A10%3A12Z&sv=2024-05-04)) for more details.

It might be something to do with the `ExtensionArray`, since that seems to be the common theme in the errors.

It seems this was the [last passing wheel build](https://github.com/pandas-dev/pandas/actions/runs/10105253109), which ran on July 26th. It did include successful Python 3.13 wheel builds.

**Comment by lysnikolaou** [comment]
This is a duplicate of https://github.com/pandas-dev/pandas/issues/59372.

**Comment by EwoutH** [comment]
Sorry, didn't see that one.
