### ISSUE TITLE
QST: How to use 'numba' for group by sum

### ISSUE THREAD

**Issue by acmilannesta** [pandas-dev/pandas#59445]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/78845935/qst-how-to-use-numba-for-group-by-sum

### Question about pandas

```
import numba

@numba.njit
def sum_func(index, values):
    return pd.Series(np.sum(values), index=index)

df_long_control[['user_id', 'reward_type', 'reward']].groupby(['user_id', 'reward_type'], as_index=False).apply(sum_func, engine='numba')
```
I'm trying to group by `user_id` and `reward_type` and apply sum function using numba, but got an error
```
TypeError: sum_func() got an unexpected keyword argument 'engine'
```

**Comment by mroeschke** [comment]
You'll need to use 

```python
df_long_control[['user_id', 'reward_type', 'reward']].groupby(['user_id', 'reward_type'], as_index=False).sum(engine='numba')
```

instead. See https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.sum.html
