### ISSUE TITLE
ENH: resample to conjoin ohlc with other fields

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#5946]
Since ohlc produces a multi-index and other aggregations an index,
should promote the index to multi-index and conjoin

http://stackoverflow.com/questions/21140630/resampling-trade-data-into-ohlcv-with-pandas

e.g.
`df.resample('30s',how={'price' : 'ohlc', 'volume' : 'sum'})`

**Comment by mroeschke** [comment]
This works but the resample API has changed beyond this point. Closing
