### ISSUE TITLE
DOC: document pd.match in main docs section

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#5949]
`pd.match` is a lurking function.....would be nice to add a short blurb to the main docs, maybe in `factorize` section 

https://github.com/pydata/pandas/blob/master/doc/source/reshaping.rst#factorizing-values

used here in docs: https://github.com/pydata/pandas/pull/5875/files

**Comment by jorisvandenbossche** [comment]
`pandas.match` is deprecated in the meantime, so closing this.
