### ISSUE TITLE
ENH: Adding `skipna:bool` to Rolling.sum

### ISSUE THREAD

**Issue by alexbaretta** [pandas-dev/pandas#59498]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

There is an inconsistency between the APIs of `pd.DataFrame.sum`/`pd.Series.sum` and the API of `pandas.core.window.rolling.Rolling.sum`. The former two functions support `skipna` to let the user decide whether to silently ignore NaNs or let the presence of NaNs cause the result to be NaN. The second function lacks this parameter. I happen to have a use case where I may not ignore NaNs, so currently I have to essentially reimplement rolling windows in my own high-level code, which makes my code slow to a crawl.

### Feature Description

I suggest adding a `skipna:bool = True` to the signature of Rolling.sum:

```
    def sum(
        self,
        skipna: bool = True,
        numeric_only: bool = False,
        engine: Literal["cython", "numba"] | None = None,
        engine_kwargs: dict[str, bool] | None = None,
    ):
    ...
```

### Alternative Solutions

My current very slow approach is to create a sequence of Index objects, each representing a window. I then iterate on the sequence of index objects, extracting the series corresponding to that window, and I call `window_as_series.sum(skipna=False)`. This works, but repeated indexing to extract a series is inordinately slow compared to a bona fide pandas windowed sum.

**Comment by Liam3851** [comment]
Rolling, currently, specifies the number of nan values allowed within the rolling window using the `min_periods` parameter to `rolling`. If `min_periods` is not specified, `rolling` defaults to requiring the full rolling window to be non-null, which is effectively skipna=False:

```python3
import numpy as np
import pandas as pd
ser = pd.RangeIndex(20).to_series()
ser.loc[10] = np.nan

In [11]: ser.rolling(5).sum()
Out[11]:
0      NaN
1      NaN
2      NaN
3      NaN
4     10.0
5     15.0
6     20.0
7     25.0
8     30.0
9     35.0
10     NaN
11     NaN
12     NaN
13     NaN
14     NaN
15    65.0
16    70.0
17    75.0
18    80.0
19    85.0
dtype: float64
```

I'm thus not sure how you're getting skipna=True behavior... Perhaps you are specifying min_periods=1 in your rolling calculation, to include the "ramp-up" period before the window is full? If so a performant solution is something like:

```python3
In [18]: ser.rolling(5, min_periods=1).sum().where(ser.isnull().rolling(5, min_periods=1).sum() == 0)
Out[18]:
0      0.0
1      1.0
2      3.0
3      6.0
4     10.0
5     15.0
6     20.0
7     25.0
8     30.0
9     35.0
10     NaN
11     NaN
12     NaN
13     NaN
14     NaN
15    65.0
16    70.0
17    75.0
18    80.0
19    85.0
dtype: float64
```

**Comment by mroeschke** [comment]
Thanks for the suggestion but as mentioned, the `min_periods` parameter is equivalent functionality as `skipna` for `rolling`, so I think it would be redundant to add `skipna` to rolling methods, so closing
