### ISSUE TITLE
PERF: Excessive memory consumption in pd.read_parquet

### ISSUE THREAD

**Issue by cotZhong** [pandas-dev/pandas#59494]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this issue exists on the main branch of pandas.

### Reproducible Example

During read a parquet file (Only 30M), I got a very high memory consumption, when checking memory usage with memory_profiler

`3690.5 MiB   3401.4 MiB           1       df = pd.read_parquet(file_path)`

how can I solve it

thx!!

### Installed Versions

<details>

pandas                : 2.2.2
numpy                 : 1.23.1
pytz                  : 2023.3
dateutil              : 2.8.2
setuptools            : 50.3.2
pip                   : 23.1.2
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.2
IPython               : 8.14.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.2
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.5.0
gcsfs                 : None
matplotlib            : None
numba                 : 0.57.1
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 16.1.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None
None

</details>

**Comment by cotZhong** [comment]
And, Maybe important, My DataFrame contains another nested DataFrame.

**Comment by rhshadrach** [comment]
Thanks for the report. Please provide a reproducible example.

**Comment by cotZhong** [comment]
Sorry for late. I'm busy this days. I'll add an example a few days later. If someone want to reproduce this issue, he/she can save a nested dataframe(the value of df is also a df) and load it
