### ISSUE TITLE
DOC: Incorrect Documentation: pd.Dataframe.dropna

### ISSUE THREAD

**Issue by SMAntony** [pandas-dev/pandas#59510]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html

### Documentation problem

![image](https://github.com/user-attachments/assets/b3a93dff-dca7-466f-9544-b36fdf6211b8)

 Keyword Argument 'how' is defined as "_NoDefault.no_default" but it has a default value 'any'

### Suggested fix for documentation

Change the value of the keyword arg 'how' to 'any'

**Comment by sgysherry** [comment]
take

**Comment by rhshadrach** [comment]
> Keyword Argument 'how' is defined as "_NoDefault.no_default" but it has a default value 'any'

`DataFrame.dropna(thresh=2)` is not the same as `DataFrame.dropna(how="any", thresh=2)`. Therefore, it is not correct to say that "any" is the default.
