### ISSUE TITLE
DOC: Wrong bug number in what's new v3.0.0

### ISSUE THREAD

**Issue by matsidzi** [pandas-dev/pandas#59532]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/whatsnew/v3.0.0.html

### Documentation problem

There is a sentence in the `Bug Fixes > Datetimelike` section:

"Bug in date_range() where using a negative frequency value would not include all points between the start and end values (GH 56382)"

The "56382" is a wrong number which is not related to the fixed issue.

The correct PR is #56832.
The correct issue is #56147.

### Suggested fix for documentation

Fix "56382" to "56147" in the mentioned line in what's new v3.0.0.

**Comment by matsidzi** [comment]
I'm not sure if this is a problem or not, but I decided to add it here as a comment. Maybe these bugs:
#56147 
#56134
need to be closed, because related PRs are merged.

**Comment by Aloqeely** [comment]
Thanks for the report. PRs are welcome!

**Comment by matsidzi** [comment]
take
