### ISSUE TITLE
DOC: read_csv: date_format

### ISSUE THREAD

**Issue by igurin-invn** [pandas-dev/pandas#59557]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.read_csv.html

### Documentation problem

When using `read_csv`, I came across a `UserWarning: Could not infer format...`. I tried to resolve it by providing a `date_format`, but the warning wouldn't go away. Then I realized that my problem was that I was providing specifically the *date format* but not the *time format*. 

The documentation for this parameter is confusing. It starts with what appear to be two alternate and contradictory definitions of the parameter:
* "Format to use for parsing dates when used in conjunction with `parse_dates`."
* "The `strftime` to parse time, e.g. `"%d/%m/%Y"`."

### Suggested fix for documentation

Say something like this:

"Format to use for parsing dates and/or times. Used in conjunction with `parse_dates`. See `strftime` documentation for more information on choices..."

**Comment by rhshadrach** [comment]
Thanks for the report. Does this always result in a datetime, or can it result in a date and/or time? I think that would determine whether the documentation should be refined to say `datetime` or `date/time/datetime`.

> It looks like someone didn't proofread enough.

Reports and contributions are welcome, this is not.

**Comment by igurin-invn** [comment]
> Does this always result in a datetime, or can it result in a date and/or time? I think that would determine whether the documentation should be refined to say `datetime` or `date/time/datetime`.

Looks like the result is always a `DatetimeIndex`.
```python
>>> from io import StringIO
>>> import pandas as pd
>>> pd.read_csv(StringIO(',A\n7/12/2024 5:40:41 PM,0\n7/12/2024 5:41:41 PM,0'), # date and time
        parse_dates=True, index_col=0).index
DatetimeIndex(['2024-07-12 17:40:41', '2024-07-12 17:41:41'], dtype='datetime64[ns]', freq=None)
>>> pd.read_csv(StringIO(',A\n7/12/2024,0\n7/12/2024,0'),                 # date only
        parse_dates=True, index_col=0).index
DatetimeIndex(['2024-07-12', '2024-07-12'], dtype='datetime64[ns]', freq=None)
>>> pd.read_csv(StringIO(',A\n5:40:41 PM,0\n5:41:41 PM,0'),               # time only
        parse_dates=True, index_col=0).index
DatetimeIndex(['2024-08-20 17:40:41', '2024-08-20 17:41:41'], dtype='datetime64[ns]', freq=None)
```

> Reports and contributions are welcome, this is not.

Sorry. No offense intended. I took it out.
