### ISSUE TITLE
ENH: Breakpoint method for dataframes

### ISSUE THREAD

**Issue by benrutter** [pandas-dev/pandas#59559]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Pandas chaining is very popular, it's often handy, especially when debugging, to add breakpoints mid-chain.

This simple-ish to do manually:

```python
def trace_chain(df: pd.DataFrame) -> pd.DataFrame:
    breakpoint()
    return df

some_chained_df = (
    pd.read_csv("cool-csv.csv")
    .dropna(subset=["col1", "col2"])
    .assign(col3=lambda df: df["col1"] * df["col2"])
    .pipe(trace_chain)
    .astype({"col1": "float"})
)
```

Not sure if I'm alone, but I find this super helpful and think it'd be awesome (and easy to maintain) if pandas supported this natively!

### Feature Description

Essentially, add in a `breakpoint` method that's something like this:

```python
class DataFrame:
    ...
    def breakpoint(self) -> self:
        breakpoint()  # noqa
        return self
```

That's make the above example something like this:

```python
some_chained_df = (
    pd.read_csv("cool-csv.csv")
    .dropna(subset=["col1", "col2"])
    .assign(col3=lambda df: df["col1"] * df["col2"])
    .breakpoint()
    .astype({"col1": "float"})
)
```

### Alternative Solutions

I think the alternative is just not to include it natively. It is easy enough to do as a user defined function passed in to `pipe`, so would just be a handy convenience (especially for beginners) if it was included.

**Comment by mroeschke** [comment]
Thanks for the suggestion but we have had a similar request in the past that was rejected because, as you mentioned, the simplicity to make this method and therefore not worth a maintenance burden in pandas. Thanks but closing
