### ISSUE TITLE
BUG: StringDtype conversion to bool changes False to True

### ISSUE THREAD

**Issue by snaumann42** [pandas-dev/pandas#59575]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas
from pandas import StringDtype

df1 = pandas.DataFrame({
    "field": [True, False]
}, dtype=StringDtype())
df1
df1.dtypes
df1["field"] = df1["field"].astype("bool")
df1
df1.dtypes

df2 = pandas.DataFrame({
    "field": [True, False]
})
df2
df2.dtypes
df2["field"] = df2["field"].astype("bool")
df2
df2.dtypes
```

### Issue Description

StringDtype with "False" values convert to True values when casted to bool, object converts "False" to False.

It's possible we want empty string = False and populated/non-empty string = True, while object operates under different logic. My current understanding is the pandas (numpy) uses objects for strings which would mean the logic for StringDtype -> bool differs from object -> bool, while both represent string -> bool conversions.

### Expected Behavior

when converting "False" with a StringDtype type with astype to bool results in a False

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.4.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 23.1.0
Version               : Darwin Kernel Version 23.1.0: Mon Oct  9 21:32:11 PDT 2023; root:xnu-10002.41.9~7/RELEASE_ARM64_T6030
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 2.0.1
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : None
pip                   : 24.0
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>

**Comment by jorisvandenbossche** [comment]
I think this is the expected behaviour. When constructing the dataframe, the True/False values get converted to their string representation because of specifying the `dtype` as string dtype. But then when casting this column with string dtype to bool dtype, it indeed follows the rules of Python about "truthiness" of python objects, where an empty string evaluates to False, and any non-empty string is True:

```python
>>> bool("")
False
>>> bool("True")
True
>>> bool("False")
True
```

> It's possible we want empty string = False and populated/non-empty string = True, while object operates under different logic.

I am not entirely sure what you mean with "object" here in the last sentence, and what this different logic is and what uses that.

**Comment by jorisvandenbossche** [comment]
Essentially what you want here is something that "parses" strings into boolean values, very similarly like we have `pd.to_numeric` that parses strings into numbers (integers or floats).  
(but I don't think we have something like that at the moment directly exposed, except for using that under the hood in the readers like `read_csv`)

**Comment by snaumann42** [comment]
Thank you @jorisvandenbossche, I appreciate the confirmation! Sorry about my misunderstanding.

As for the "object" I was talking about, we can disregard that, I got confused some where.
