### ISSUE TITLE
2.3 release dates

### ISSUE THREAD

**Issue by asishm** [pandas-dev/pandas#59612]
I see that there is a 2.3 release that will happen. From the items currently milestoned with 2.3, it appears they are exclusively for PDEP-14 string dtype implementation. Is that the scope for the 2.3 release?

There are many bug-fixes that are currently milestoned 3.0. I'm guessing backporting them to the 2.3 branch will be a big task. It might be helpful to get some dates (just estimates are probably ok) for the 2.3 (and any plans for patch versions) and 3.0 release dates

**Comment by jorisvandenbossche** [comment]
For future reference, this is discussed at the 2.3 release issue now -> https://github.com/pandas-dev/pandas/issues/59664
