### ISSUE TITLE
ENH: read_md() and to_md()

### ISSUE THREAD

**Issue by dstone42** [pandas-dev/pandas#59645]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish I could read from markdown (md) files and write to md files. I use Obsidian (a md based note-taking app) to create tables that document a process that I will follow, but I want to be able to automate the rest of the process by reading those tables directly from md into a pandas data frame.

### Feature Description

Add new functions for reading data frames from md and writing data frames to md.

### Alternative Solutions

Since md is a superset of html, I have an add-on in Obsidian that allows me to export a md file to an html file. Every time I edit the md file, I re-export it to html then I use the read_html() function to read the tables in. It's totally a functionality of convenience. It takes out a manual step that I have to do every time. 

I'm sure I could find an automatic way to turn md into html as well, but I it would definitely be more seamless if I could read the tables straight from md. I don't know a ton about how an md file would be read into python, but seeing as it's a superset of html, I'm assuming it shouldn't be that different from the read_html() parser that already exists.

I could make my own function to parse a markdown file and turn it into a data frame, but at this point, it's easier for me to press a button to convert to html than to write that whole python function.

**Comment by AntiKnot** [comment]
Tools like Pandoc Tabulate maybe helpful.
In pandas, there are some features and interfaces solve this Enhancement.
https://stackoverflow.com/questions/60154404/is-there-the-equivalent-of-to-markdown-to-read-data
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_markdown.html

**Comment by mroeschke** [comment]
Thanks for the request. As mentioned there already exists a `to_markdown` method and based on the stackoverflow answer to ready markdown, the solution is minimal enough not needed to be maintained in pandas. Closing
