### ISSUE TITLE
BUG: Pandas incompatibility with Numpy 2.1.0

### ISSUE THREAD

**Issue by edensweden1** [pandas-dev/pandas#59668]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import numpy
import pandas
```

### Issue Description

<img width="1470" alt="Screenshot 2024-08-30 at 12 31 42" src="https://github.com/user-attachments/assets/ace331c8-1f6d-434b-a258-508f90a72102">

Note: Some sensitive information has been censored

### Expected Behavior

>>> import pandas

### Installed Versions

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.11.9.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 5.15.0-117-generic
Version               : #127~20.04.1-Ubuntu SMP Thu Jul 11 15:36:12 UTC 2024
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0
setuptools            : 72.1.0
pip                   : 24.2
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : 8.0.2
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.4
IPython               : 8.26.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.6.1
gcsfs                 : None
matplotlib            : 3.9.2
numba                 : None
numexpr               : 2.8.7
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.14.0
sqlalchemy            : None
tables                : 3.10.1
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

**Comment by mroeschke** [comment]
Thanks for the issue but from the traceback this appears like an issue with numexpr. Additionally, pandas does not have a released version that officially supports numpy 2.1. 

Unfortunately I would either recommend downgrading numpy or modifying your numexpr version, so closing
