### ISSUE TITLE
DOC: Document that DataFrame.from_records()'s columns argument also acts as "include"

### ISSUE THREAD

**Issue by cjerdonek** [pandas-dev/pandas#59670]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.from_records.html

### Documentation problem

Currently, it's not clear from the `DataFrame.from_records()` docs that the `columns` argument to `from_records()` also has the effect of what an `include` argument (or `usecols`) would do. Indeed, the current wording once led someone to file a feature request asking for an `include` argument to be added: https://github.com/pandas-dev/pandas/issues/15319
However, the request was later closed when the maintainers realized the `columns` argument already does this (but it's not documented, hence this issue).

### Suggested fix for documentation

Add a sentence or phrase to the documentation of the `columns` argument that the  argument also has the effect of limiting the DataFrame to including only the columns specified. This isn't implied by the current wording, or it's at least a little ambiguous.

**Comment by rhshadrach** [comment]
Thanks for the report! PRs to improve the docs here are welcome!

**Comment by ammar-qazi** [comment]
take

**Comment by ammar-qazi** [comment]
@rhshadrach 
Unfortunately, the `columns` parameter behaves differently than expected with various input types. While I encountered the intended behavior as described in the other thread with dictionaries, the results were different when I used Numpy's structured array or a list of tuples. 

- **Numpy's structred array**: The `Columns` parameter doesn't appear to have any filtering effect on a structured array. All columns are included in the original order, regardless of what's specified in columns.

![image](https://github.com/user-attachments/assets/373e6213-fb2b-4364-b23b-b09b7f1fb044)


- **List of tuples**: The `Columns` parameter only assigns names to the columns. It doesn't filter or reorder the data. Additionally, it raises an error if fewer column names are provided than the number of columns in the input data.

![image](https://github.com/user-attachments/assets/393e2167-cf6f-4279-89a0-0c0a361844cd)
![image](https://github.com/user-attachments/assets/882aed38-1bb5-400c-9800-50a636dfa09a)

For documentation purposes, I'm considering treating the dictionary-based input as the ideal case and instructing users to convert their data into dictionaries if they want to filter or reorder columns using the columns parameter. 

However, as this is my first time contributing to the documentation, I'd greatly appreciate your guidance on the best approach to document these nuances.

**Comment by cjerdonek** [comment]
> Numpy's structred array: The Columns parameter doesn't appear to have any filtering effect on a structured array. All columns are included in the original order, regardless of what's specified in columns.

It seems like this could be a bug because it seems to contradict the current documentation (that the argument reorders the columns if column names are provided).

> List of tuples: The Columns parameter only assigns names to the columns. It doesn't filter or reorder the data. Additionally, it raises an error if fewer column names are provided than the number of columns in the input data.

This seems to be consistent with the current documentation because the documentation only says that reordering occurs if names are provided (and this limitation can be the same for filtering). As for raising an error when fewer names are provided, the documentation doesn't explicitly say an error will happen in that case, but it's not surprising it would, IMO.

**Comment by ammar-qazi** [comment]
Yeah, that's understandable. If the bug is fixed, we can say that the `columns` parameter reorders data in dict and Numpy array. And for a list of tuples, it behaves as a names parameter, which should be clear because a list of tuples doesn't have existing column names. 

Thanks for the insights, @cjerdonek.
