### ISSUE TITLE
DOC: broken link for governance in the team web page

### ISSUE THREAD

**Issue by strayMat** [pandas-dev/pandas#59693]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/about/team.html

### Documentation problem

The link to the governance page seems broken : `[project governance page]({{ base_url }}governance.html)` resulting in `https://pandas.pydata.org/governance.html` yielding a 404.  The proper url seems to be  `https://pandas.pydata.org/about/governance.html`. 

### Suggested fix for documentation

Changing  `[project governance page]({{ base_url }}governance.html)` to  `[project governance page]({{ base_url }}about/governance.html)` in the `https://github.com/pandas-dev/pandas/blob/main/web/pandas/about/team.md`

**Comment by doshi-kevin** [comment]
@strayMat  I have made changes to the link. Please check it, if helps, hope the PR gets merged.

**Comment by strayMat** [comment]
Many thanks, it seems to work with the website zip archive :)

**Comment by doshi-kevin** [comment]
Can you merge this PR ?

**Comment by strayMat** [comment]
I am not able to merge it. It requires write access.

**Comment by doshi-kevin** [comment]
So maybe we can tag someone who can ? I am new to open source 😁.

**Comment by strayMat** [comment]
You required review from two core developpers. Let's wait for approval a little bit :)

**Comment by KevsterAmp** [comment]
take
