### ISSUE TITLE
DOC: methods in see also section in the pandas.core.groupby.DataFrameGroupBy.agg are not hyperlinks

### ISSUE THREAD

**Issue by specialkapa** [pandas-dev/pandas#59695]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

[pandas.core.groupby.DataFrameGroupBy.agg](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.agg.html#pandas.core.groupby.DataFrameGroupBy.agg)

### Documentation problem

In the see also section the `DataFrame.groupby.apply`, `DataFrame.groupby.transform` and DataFrame..aggregate` methods though listed, they are not hyperlinks and thus the reader cannot navigate with ease but has to look for them instead 

### Suggested fix for documentation

I am not very familiar with the `sphinx` setup in `pandas` and thus cannot suggest an approach for fixing this. Perhaps there is a good reason that these methods are not hyperlinked, note sure

**Comment by rhshadrach** [comment]
Thanks for the report. The `_agg_template_frame` and `_agg_template_series` strings in `pandas.core.groupby.groupby` both have things like:

> {klass}.groupby.apply : Apply function func group-wise
    and combine the results together.

I think if we change this to `{klass}GroupBy.apply`, the link will resolve.

Further investigations and PRs to fix are welcome!

**Comment by BobChuckyJoe** [comment]
take

**Comment by doshi-kevin** [comment]
take

**Comment by doshi-kevin** [comment]
Hey @rhshadrach @specialkapa I have changed to GroupBy...please check once if it works and please merge this PR if it does. I am new to open source and eager to contribute. Open to changes and suggestions.
