### ISSUE TITLE
BUG: Inconsistent behavior of `min()` when `NaT` is present

### ISSUE THREAD

**Issue by gozwei** [pandas-dev/pandas#59740]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
print(f"{pd. __version__=}")

L = []

L.append({"date": "2024-01-01"})
L.append({"date": "2025-01-01"})
L.append({"date": ""})

dfA = pd.DataFrame(L)
dfA["date"] = pd.to_datetime(dfA["date"])

print("dfA:")
print(dfA)
print(f"{min(dfA['date'])=}")
print(f"{dfA['date'].min()=}")

print()
print("dfB:")
dfB = dfA.iloc[::-1]
print(dfB)
print(f"{min(dfB['date'])=}")
print(f"{dfB['date'].min()=}")
```

### Issue Description

The result of the Python `min()` function depends on the order of items in the DataFrame.

### Expected Behavior

`min(dfB["date"])` should behave the same as `dfB["date"].min()`

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.2.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 5.15.0-101-generic
Version               : #111-Ubuntu SMP Tue Mar 5 20:16:58 UTC 2024
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : C.UTF-8
LOCALE                : C.UTF-8

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : None
pip                   : 24.1.2
Cython                : None
pytest                : 8.1.1
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : 3.2.0
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : 2.9.9
jinja2                : 3.1.3
IPython               : 8.23.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : 2024.2.0
fsspec                : 2024.2.0
gcsfs                 : None
matplotlib            : 3.9.0
numba                 : 0.59.0
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.2
pandas_gbq            : None
pyarrow               : 15.0.1
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.12.0
sqlalchemy            : None
tables                : None
tabulate              : 0.9.0
xarray                : 2024.2.0
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>

**Comment by gdowdy3** [comment]
From my perspective, the most unintuitive thing about this example is that `min(dfA['date'])` does not return the same result as `min(dfB['date'])`.

**Comment by mroeschke** [comment]
Thanks for the report but I think this is the expected behavior.

`NaT` is like `nan` where all comparison operators always evaluate to `False`, and since `min` just iterates over each value and performs a comparison it's equivalent to this

```python
In [3]: min([float("nan"), 1.0, 2.0])
Out[3]: nan

In [4]: min([1.0, 2.0, float("nan")])
Out[4]: 1.0
```

Additionally `Series.min` has a `skipna=True` default value so this method ignores `NaT` by default

**Comment by gozwei** [comment]
Ok, I see your argument. This is an example without pandas:
```import numpy as np

a = [1,2,3,np.nan]
b = [np.nan,1,2,3]
print(min(a))
print(min(b))
```

While this does not seem like pandas issue, I find it counterintuitive. 

I'm ok to close this issue.
