### ISSUE TITLE
BUG: Ambigious behaviour of multiplication assignment operator for series of type integer

### ISSUE THREAD

**Issue by juwoha** [pandas-dev/pandas#59779]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame(data={"spam": [1, 2, 3, 4], "eggs": [1.0, 2.0, 3.0, 4.0]})
cols2scale = [df.spam, df.eggs]
scale = 2.0
for series in cols2scale:
    series *= scale

print(df)
print(df.spam)
print(df.mean())
```

### Issue Description

When attempting to scale multiple Series in a pandas DataFrame using a multiplication assignment operator (in-place modification), the changes are not reflected in the DataFrame for the series of dtype "int64". Looking at the print statements (df.spam) shows the correct values.

In my application i have a class holding multiple pandas dataframes as attributes. I thought looping over the attributes in a list is a good idea. However i am a beginner, so please point out to me if i am to blame for this issue. What confuses me, is that it works for float columns but not for integers.

### Expected Behavior

Both the spam and eggs columns in the DataFrame should be scaled by the specified factor (2.0), and the output should reflect the updated values.

### Installed Versions

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.5.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.19045
machine               : AMD64
processor             : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : de_DE.cp1252

pandas                : 2.2.2
numpy                 : 2.1.1
pytz                  : 2024.2
dateutil              : 2.9.0
setuptools            : 72.1.0
pip                   : 24.2
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : 8.27.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

**Comment by rhshadrach** [comment]
Thanks for the report! The data in `df.eggs` and the data in `df` are shared. When you do `*= 2.0`, since `df.eggs` is float64, the data can be modified inplace and pandas does so. As such, the values in `df` are updated as well. However, for `df.spam` pandas needs to change the dtype from int64 to float64. This is not done inplace, new memory is needed. As a result, while `series` is updated in the for loop, the data in the original `df` is not.

With [Copy-on-Write](https://pandas.pydata.org/pdeps/0007-copy-on-write.html) enabled, `df.spam` and `df.eggs` are both treated as a copy, giving pandas consistent behavior.

```python
pd.set_option("copy_on_write", True)

df = pd.DataFrame(data={"spam": [1, 2, 3, 4], "eggs": [1.0, 2.0, 3.0, 4.0]})
cols2scale = [df.spam, df.eggs]
scale = 2.0
for series in cols2scale:
    series *= scale
print(df)
#    spam  eggs
# 0     1   1.0
# 1     2   2.0
# 2     3   3.0
# 3     4   4.0
```

Since both are treated as a copy, the data in `df` remains unchanged.

This will be the default behavior in pandas 3.0. Closing since this inconsistency is fixed.
