### ISSUE TITLE
DOC: Questions on Usage of *args, **kwargs, and inplace parameters in pandas.Series.cat methods

### ISSUE THREAD

**Issue by saldanhad** [pandas-dev/pandas#59783]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.Series.cat.remove_categories.html#pandas.Series.cat.remove_categories

https://pandas.pydata.org/docs/reference/api/pandas.Series.cat.rename_categories.html#pandas.Series.cat.rename_categories

### Documentation problem

I am currently trying to work on the issue #59592, specifically for the remove_categories and rename_categories methods. Before finalizing my changes, I need some clarification on a few points regarding the documentation:

1. `*args` and `**kwargs` Usage: 
- For remove_categories, the method only seems to use the removals parameter. 
- Similarly, for rename_categories, `*args` and `**kwargs` are mentioned but not utilized in the method implementation. Could you clarify whether the inclusion of `*args` and `**kwargs` in the documentation for methods is by design? 
- I have noticed this pattern across many methods and wanted to confirm if this is intentional or if the documentation should be updated to reflect actual usage.

 2. `inplace` Parameter: The `inplace` parameter for methods is included in the error codes of the validation docstring. However, it is not explicitly mentioned in the current documentation, nor is it included as part of the method definition for both methods.

### Suggested fix for documentation

Verify usage of ` **args`, `**kwargs`, and 'inplace' if not make changes to the `pandas.Series.cat` methods in docs.

**Comment by rhshadrach** [comment]
Thanks for the report! In the pandas code, the signature of the function is

    def remove_categories(self, removals) -> Self:

I believe when we wrap it for adding it to the `cat` accessor, the signature gets changed to `*args, **kwargs` as these are passed through by `_create_delegator_method`:

https://github.com/pandas-dev/pandas/blob/73c4fce2fe8c8893b1d370ce04211c59c8182d61/pandas/core/accessor.py#L119

I wonder if we should be using `functools.wraps` here. E.g.

```python
import functools as ft
import inspect

def foo(a, b, c=5):
    return 100 * a + 10 * b + c

def modify_func(func):
    @ft.wraps(func)
    def wrapper(*args, **kwargs):
        args = (args[0]+1, *args[1:])
        return func(*args, **kwargs)
    return wrapper

@modify_func
def bar(a, b, c=6):
    return 100 * a + 10 * b + c

print(bar(1, 2))
# 226

print(inspect.signature(bar))
# <Signature (a, b, c=6)>
```

Without `@ft.wraps(func)`, you get the signature `*args, **kwargs`.

**Comment by saldanhad** [comment]
take
