### ISSUE TITLE
DOC: Separate Examples for String Methods (str.isalnum(), str.isalpha(), etc.) in docs

### ISSUE THREAD

**Issue by saldanhad** [pandas-dev/pandas#59806]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.Series.str.isalnum.html

### Documentation problem

In the current documentation for pandas string methods `(e.g., str.isalnum(), str.isalpha(), str.isdigit(), etc.)`, the examples for all string methods are grouped together in a way that makes it difficult to interpret which example corresponds to which method. This can be confusing for users who are looking for examples for a specific method, and it reduces the clarity of the documentation.

### Suggested fix for documentation

I suggest updating the documentation to have distinct examples for each string method. Each method should have its own section with a description and example specific to that method, which would improve clarity and make it easier to navigate.

If this is deemed valid, I would be happy to work on resolving it. Could this issue be assigned to me?

**Comment by rhshadrach** [comment]
Thanks for the report, agreed separating these out would be desired. PRs welcome!

> Could this issue be assigned to me?

If you haven't yet seen our contributor documentation, it might be worth a look at, in particular this section:

https://pandas.pydata.org/docs/dev/development/contributing.html#finding-an-issue-to-contribute-to

**Comment by saldanhad** [comment]
take
