### ISSUE TITLE
BUG: df.MultiIndex.levels continues to return the index of the original df after mutation

### ISSUE THREAD

**Issue by lawrencefchan** [pandas-dev/pandas#59829]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame([[1, 'a', 'foo'], [2, 'b', 'bar']]).set_index([1, 2])
print(df)
print(df.index.levels[0])  # returns [1, 2]

d1 = df.head(1)
print(d1)
print(d1.index.levels[0])  # returns [1, 2]

d2 = df.drop(('b', 'bar'))
print(d2)
print(d2.index.levels[0])  # returns [1, 2]
```

### Issue Description

`df.MultiIndex.levels` continues to return the index of the original df, even after mutation. 

### Expected Behavior

```
d3 = df.head(1).reset_index().set_index([0, 1])
print(d3)
print(d3.index.levels[0])  # returns [1] as expected
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.11.6.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.19045
machine               : AMD64
processor             : Intel64 Family 6 Model 154 Stepping 4, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : English_Australia.1252

pandas                : 2.2.2
numpy                 : 2.1.1
pytz                  : 2024.2
dateutil              : 2.9.0.post0
setuptools            : 65.5.0
pip                   : 23.2.1
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None
</details>

**Comment by rhshadrach** [comment]
Thanks for the report, each level only stores the set of possible values in the index. When you subset a DataFrame, pandas keeps the same level to avoid having to recode the index for performance. This is expected behavior.
