### ISSUE TITLE
BUG: `None` values are not processed when applying `pd.isnull` to a Series with dtype `category`

### ISSUE THREAD

**Issue by StephanMertel** [pandas-dev/pandas#59832]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

# Create a Series with dtype category which contains a None value
my_series = pd.Series([1, None], dtype="category")

my_series.apply(pd.isnull)
# This will output
# 0    False
# 1      NaN   <------------------ I would expect this to be True
# dtype: category
# Categories (1, bool): [False]
```

### Issue Description

When applying `pd.isnull` to a Series of dtype `category` which contains `None` like values (`None`, `np.nan`, `pd.NA`, etc.), the output doesn't contain a boolean but a float `nan` instead.

### Expected Behavior

The output should contain only boolean values and all `None`, `pd.NA` etc. values should be evaluated as `True`.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.11.3.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 23.6.0
Version               : Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:21 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8103
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : None.UTF-8

pandas                : 2.2.2
numpy                 : 1.24.3
pytz                  : 2023.3
dateutil              : 2.8.2
setuptools            : 67.6.1
pip                   : 23.0.1
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : 8.13.2
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.2
pandas_gbq            : None
pyarrow               : 12.0.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2023.3
qtpy                  : None
pyqt5                 : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report. Agreed this is a bug and on the expectation, but for performance you should prefer `my_series.isnull()` to using `apply`. Using `apply` is very slow.

**Comment by StephanMertel** [comment]
@rhshadrach thanks for your answer and the hint! Will do.

**Comment by tyqiangz** [comment]
take

**Comment by tyqiangz** [comment]
@rhshadrach I believe this issue is already solved in this PR https://github.com/pandas-dev/pandas/pull/59966.

**Comment by rhshadrach** [comment]
Agreed, thanks @tyqiangz
