### ISSUE TITLE
BUILD: no linux-aarch64 wheels for v2.2.3?

### ISSUE THREAD

**Issue by njzjz** [pandas-dev/pandas#59851]
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Linux-5.15.0-104.119.4.2.el8uek.aarch64-aarch64-with-glibc2.28

### Installation Method

pip install

### pandas Version

2.2.3

### Python Version

3.10.13

### Installation Logs

```sh
pip install pandas==2.2.3 --only-binary=:all:
```

<details>

ERROR: Could not find a version that satisfies the requirement pandas==2.2.3 (from versions: 1.3.3, 1.3.4, 1.3.5, 1.4.0rc0, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.5.0rc0, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0rc0, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0rc0, 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for pandas==2.2.3

</details>

**Comment by sharathsamala** [comment]
@lithomas1  how long this gonna take for you to re-upload these new wheels ?

**Comment by lithomas1** [comment]
OK, I've re-uploaded wheels so things should be working now.

I don't have an aarch64 box, though, so I have no way to telling whether the uploaded wheels are correct
(I did have to go and manually patch the versions in the wheels)

@sharathsamala @njzjz 
Can you let me know whether the new wheels work?

**Comment by njzjz** [comment]
I restarted the CI job that previously failed and it passed now.

**Comment by lithomas1** [comment]
Thanks and sorry for the hassle again!

**Comment by sharathsamala** [comment]
Same with our jobs. @lithomas1 Its working as expected now.
