### ISSUE TITLE
BUG: `pd.options.display.float_format` did not follow left side or before decimal places format 

### ISSUE THREAD

**Issue by yasirroni** [pandas-dev/pandas#59876]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

# Set the global float format
pd.options.display.float_format = '{:6.3f}'.format

# Example DataFrame
df = pd.DataFrame({
    'A': [123.456, 789.1011],
    'B': [2.71828, 3.14159]
})

df
```

### Issue Description

Pandas `pd.options.display.float_format` did not follow left side or before decimal places format.

### Expected Behavior

If also follows the left side or before decimal places format. 

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.10.11.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 23.6.0
Version               : Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:21 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8103
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : None.UTF-8

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : 69.1.0
pip                   : 24.0
Cython                : None
pytest                : 8.1.1
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.3
IPython               : 8.23.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : 3.8.4
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.2
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.11.4
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report. Can you include what output you currently get and the output you expect to get.

**Comment by yasirroni** [comment]
Current output:

<img width="119" alt="image" src="https://github.com/user-attachments/assets/9a808933-1374-44f2-84b1-6a010f026b98">

Expected output:

The width of all column should be the same based on the allocated space by "format".

<img width="180" alt="image" src="https://github.com/user-attachments/assets/dcc04949-f77b-4c23-88ec-08de73e5c253">

Example code to generate my output:

```python
import pandas as pd

# Set the global float format
fmt = '{:6.3f}'.format
pd.options.display.float_format = fmt

df = pd.DataFrame({
    'A': [123.456, 789.1011],
    'B': [2.71828, 3.14159]
})

for index, row in df.iterrows():
    formatted_row = [fmt(value) for value in row]  # Format each value in the row
    print(f"Col {index}: {formatted_row}")
```

**Comment by rhshadrach** [comment]
Thanks for the information. It appears to me you are using something akin to Juptyer's `display` which is a different method than printing.

```python
pd.options.display.float_format = '{:12.3f}'.format

# Example DataFrame
df = pd.DataFrame({
    'A': [123.456, 789.1011],
    'B': [2.71828, 3.14159]
})

print(df)
#              A            B
# 0      123.456        2.718
# 1      789.101        3.142
```

You can see the option is having the expected impact on printed DataFrames. It's not clear to me whether this is due to a limitation on the Jupyter (or other notebooks) side. Further investigations are welcome!

**Comment by yasirroni** [comment]
Thank you. I'm using VSCode Jupyter Notebook and I can confirm that print is working as expected but display is not. Using jupeyter lab also works the same.

```python
import pandas as pd

from IPython.display import display

pd.options.display.float_format = '{:.3f}'.format

# Example DataFrame
df = pd.DataFrame({
    'A': [123.456, 789.1011],
    'B': [2.71828, 3.14159]
})
print(df)
display(df)

pd.options.display.float_format = '{:12.3f}'.format

# Example DataFrame
df = pd.DataFrame({
    'A': [123.456, 789.1011],
    'B': [2.71828, 3.14159]
})
print(df)
display(df)
```

<img width="391" alt="image" src="https://github.com/user-attachments/assets/7a97b71d-b8f8-47d4-86d6-860e1a794047">

**Comment by yasirroni** [comment]
So, I think we should close this and pass it to jupyter developer? Please give me feedback on where is the best place to bring this (is it pandas or jupyter).

**Comment by yasirroni** [comment]
After some investigation, even string format didn't respected by display.

```python
pd.options.display.float_format = '{:.3f}'.format.  # if float, use .3f
df_formatted = df.map(lambda x: str(f'{x:12.3f}')).astype('string').  # change to string to ignore float_format
display(df_formatted)
print(df_formatted).  # correctly using str(f'{x:12.3f}')
```

The workaround is to directly change Styler:

```python
styled_df = df_formatted.style.set_table_styles(
    [{'selector': 'td', 'props': [('min-width', '80px')]}]
)

display(styled_df)
```

**Comment by rhshadrach** [comment]
Thanks for the investigation - I think your investigation suggests this is an issue with HTML formatting. We still control the HTML that is produced by `display(df)`, so I suspect we may be able to fix it. Even if that is the case, perhaps we should consider having some formatting options only for printed DataFrames.

Leaving this open for now. I plan to investigate it in the near future.

**Comment by rhshadrach** [comment]
Two things need to change in order to implement this. First, is passing `get_option("display.float_format")` to `DataFrameFormatter` in `frame.DataFrame._repr_html`. The 2nd is adding `" ": "&nbsp;"` to `esc` in `io.formats.html.HTMLFormatter._write_cell`.

For the 2nd, we also fix other issues with multiple spaces in strings, e.g.

    df = pd.DataFrame({"A": ["foo      foo", "bar"]})
    display(df)

fixed:

![image](https://github.com/user-attachments/assets/70c75b09-d2c8-4149-8cdb-6ad5cd3bfded)

main:

![image](https://github.com/user-attachments/assets/38ba465f-1ad7-4872-8a09-b0eb9d99ff39)

I think each of these are not controversial, marking as a good first issue for now. But cc @pandas-dev/pandas-core for any thoughts.

**Comment by saldanhad** [comment]
Are you expecting a pytest script to cover this change?

**Comment by rhshadrach** [comment]
Yes - I think something along the lines of `test_info_repr_html` would be sufficient.

**Comment by saldanhad** [comment]
take

**Comment by saldanhad** [comment]
For the 2nd implementation is it ok if the html output is `<td>&nbsp;foo&nbsp;&nbsp;&nbsp;&nbsp;foo</td> `  or should it have to be of the form ` <td>foo&nbsp;&nbsp;&nbsp;&nbsp;foo</td>`

**Comment by rhshadrach** [comment]
@saldanhad - offhand I'm not sure; it may be that another section of code is adding `&nbsp;` prior to `foo` outside of where I indicated in https://github.com/pandas-dev/pandas/issues/59876#issuecomment-2381351682. If that's occurring, I think it should remain.

**Comment by saldanhad** [comment]
Thanks for clarifying. The leading `&nbsp` was not there before and it seems to be appearing after adding it to `esc`, so I am assuming this is not expected.

**Comment by rhshadrach** [comment]
Interesting - I'll take a deeper look.

**Comment by saldanhad** [comment]
Meanwhile I was able to implement the `float formatting` with unit tests passed, if you don't mind can I make the PR for review for completion of this part ?

**Comment by rhshadrach** [comment]
Sure, that sounds fine.

**Comment by rhshadrach** [comment]
The issue with the extra space is the use of strip here:

https://github.com/pandas-dev/pandas/blob/f598670353311a6fff4e6e1e96074ccf0737e6b7/pandas/io/formats/html.py#L197

By replacing spaces with `&nbsp`, that strip no longer does anything. This goes back to https://github.com/pandas-dev/pandas/issues/4987.

I think the solution is to use `rs = rs.replace(" ", "&nbsp")` after the call to `pprint_thing`.

**Comment by saldanhad** [comment]
Thanks for your help on this. Implementing it, this way, does give the desired outcome now. My understanding prior was to have replace come inside the if conditional before pretty print and it wasn't getting implemented. 

However still a few tests are failing and further investigation is needed:
```
FAILED pandas/tests/io/formats/test_to_html.py::test_to_html_escaped[kwargs0-<type 'str'>-escaped] - AssertionError
FAILED pandas/tests/io/formats/test_to_html.py::test_to_html_escaped[kwargs1-<b>bold</b>-escape_disabled] - AssertionError
FAILED pandas/tests/io/formats/test_to_html.py::test_ignore_display_max_colwidth[10-to_html-<lambda>] - AssertionError
FAILED pandas/tests/io/formats/test_to_html.py::test_ignore_display_max_colwidth[10-_repr_html_-<lambda>] - AssertionError
FAILED pandas/tests/io/formats/test_to_html.py::test_ignore_display_max_colwidth[20-to_html-<lambda>] - AssertionError
FAILED pandas/tests/io/formats/test_to_html.py::test_ignore_display_max_colwidth[20-_repr_html_-<lambda>] - AssertionError
FAILED pandas/tests/io/formats/test_to_html.py::test_ignore_display_max_colwidth[50-to_html-<lambda>] - AssertionError
FAILED pandas/tests/io/formats/test_to_html.py::test_ignore_display_max_colwidth[50-_repr_html_-<lambda>] - AssertionError
FAILED pandas/tests/io/formats/test_to_html.py::test_ignore_display_max_colwidth[100-to_html-<lambda>] - AssertionError
FAILED pandas/tests/io/formats/test_to_html.py::test_ignore_display_max_colwidth[100-_repr_html_-<lambda>] - AssertionError
FAILED pandas/tests/io/formats/test_to_html.py::test_to_html_na_rep_non_scalar_data - AssertionError
FAILED pandas/tests/io/formats/test_to_html.py::test_to_html_tuple_col_with_colspace - AssertionError
```

**Comment by rhshadrach** [comment]
Perhaps it's better to use `rs.replace("  ", "&nbsp;&nbsp;")`. In the case there is 1 space, this would leave it alone. In the case of an odd number of spaces greater than 1, it would give the slightly odd result of something like `foo&nbsp;&nbsp;&nbsp;&nbsp; foo`. However this still produces correct HTML, with the added benefit of leaving single spaces alone. This should reduce (eliminate?) the number of test failures you're seeing.

**Comment by saldanhad** [comment]
Thanks, this worked, raising PR to close this issue.
