### ISSUE TITLE
BUG: `isna` doesn't detect `pyarrow.NA` produced by 0/0 

### ISSUE THREAD

**Issue by vkhodygo** [pandas-dev/pandas#59891]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
#%%
df = pd.DataFrame({"A": [0, 1, 2, pd.NA, 1, 2], "B": [0, pd.NA, 2, pd.NA, 2, 4]}, dtype="float[pyarrow]")

df["rate"] = df["A"]/df["B"]

df.info()
df["rate"].isna()

#%%
df = pd.DataFrame([1, 2, np.nan])
df.info()
df.isna()

#%%
pd.Series([pa.NA], dtype="float[pyarrow]").isna()
```

### Issue Description

I deal with tables with a lot of missing data, and using `pyarrow` backend is a must. However, I recently noticed that some intermediate results are not processed as they should be: applying `isna`  to the `rate` column above results in `pyarrow.NaN` being see as a regular number, whereas `numpy.nan` is processed like expected. Creating a dataframe from scratch though behaves like it should. 

### Expected Behavior

The documentation says the following:

https://github.com/pandas-dev/pandas/blob/0691c5cf90477d3503834d983f69350f250a6ff7/pandas/core/dtypes/missing.py#L101-L178

and I'd expect `NaN` to be seen the same regardless of the actual dtype; this is a well-defined `IEEE 754` object. There is a hint to what might be causing it here: https://github.com/apache/arrow/issues/35535#issuecomment-1543482341

> That's because pyarrow does not set that the NaN is the missing value indicator, and thus NaNs in the input are preserved.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 0691c5cf90477d3503834d983f69350f250a6ff7
python                : 3.12.6
python-bits           : 64
OS                    : Linux
OS-release            : 6.10.10-arch1-1
Version               : #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000
machine               : x86_64
processor             : 
byteorder             : little
LC_ALL                : en_US.UTF-8
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.3
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
pip                   : 24.1.2
Cython                : None
sphinx                : None
IPython               : 8.26.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
blosc                 : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.3.1
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : 3.1.4
lxml.etree            : None
matplotlib            : 3.9.1
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.5
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : 17.0.0
pyreadstat            : None
pytest                : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.14.0
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>

**Comment by WillAyd** [comment]
Thanks for the report - we already have a few open issues about this (see https://github.com/pandas-dev/pandas/issues/32265 and https://github.com/pandas-dev/pandas/issues/53887) so going to close this one and try to keep the discussions consolidated in those.

Appreciate you bringing this up!

**Comment by vkhodygo** [comment]
Thanks, I did search for open issues, but for some reason didn't see these ones.
