### ISSUE TITLE
BUG: "Columns must be same length as key" exception when .apply() per row on an empty DataFrame.

### ISSUE THREAD

**Issue by Zhdanovich** [pandas-dev/pandas#59915]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

MAPPING = {"a": 1, "b": 2}

df = pd.DataFrame(columns=['hour', 'value', 'zone'])

df["updated_hour"] = pd.to_datetime(df["hour"])
df["updated_value"] = df["value"].apply(lambda x: x - x % 100_000)

# This line will fail since there are no rows to apply the lambda on
df["updated_value"] = df.apply(lambda row: min(row["updated_value"], MAPPING[row["zone"]]), axis=1)
```

### Issue Description

Above code raises exception: "Columns must be same length as key.".

### Expected Behavior

Return and Assign an empty Series without raising errors (if no rows are present).

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.11.9.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 23.1.0
Version               : Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : en_US.UTF-8
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 2.1.0
pytz                  : 2024.1
dateutil              : 2.9.0
setuptools            : 72.2.0
pip                   : 24.2
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.4
IPython               : 8.26.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : 3.9.2
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 17.0.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.14.1
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : 0.23.0
tzdata                : 2024.1
qtpy                  : 2.4.1
pyqt5                 : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the request. `apply` has to infer the shape of the output from the results of applying it to rows, and is also not performant. You will get better behavior by using built-in ops rather than supplying `apply` a user-defined function. E.g.

    pd.concat([df["updated_value"], df["zone"].map(MAPPING)], axis=1).min(axis=1)

Without any rows to evaluate on, `apply` has no idea what the lambda you pass to it is returning, so it cannot determine the shape of the output you desire. We try to evaluate that on an empty Series, which is why your first usage of `apply` succeeds, but when that raises (because you try to access `updated_value`), pandas has no information to go off of. In such cases, we return the original DataFrame as-is.

There isn't sufficient information for pandas to do what you ask for.
