### ISSUE TITLE
Potential performance regression with "BUG (string): ArrowEA comparisons with mismatched types" 

### ISSUE THREAD

**Issue by DeaMariaLeon** [pandas-dev/pandas#59927]
PR #59089

@mroeschke 

edit: changed the PR (maybe) causing these. 

 "`timeseries.DatetimeIndex.time_normalize` (Python) with index_type='tz_aware'": "http://57.128.112.95:5000/compare/benchmarks/066f645062ef701180006acc763ff04b...066f672246ca708480008caae7fcae98",
        "`timeseries.DatetimeIndex.time_timeseries_is_month_start` (Python) with index_type='tz_aware'": "http://57.128.112.95:5000/compare/benchmarks/066f6450656d7a338000261fcdf27aa5...066f672249d0743880006ea312170a5e",
        "`timeseries.DatetimeAccessor.time_dt_accessor_normalize` (Python) with t='US/Eastern'": "http://57.128.112.95:5000/compare/benchmarks/066f645054697fc68000c1b0f2cf30ef...066f672236e0765f80000d2a5a7495c5",
        "`timeseries.DatetimeIndex.time_to_time` (Python) with index_type='tz_aware'": "http://57.128.112.95:5000/compare/benchmarks/066f64506d23794c8000b694ac8c3ee8...066f6722555478a380001de21300bc86",
        "`timeseries.DatetimeAccessor.time_dt_accessor_time` (Python) with t='US/Eastern'": "http://57.128.112.95:5000/compare/benchmarks/066f645056a470f4800002bd73ddfb6f...066f672239377fff8000d46f40374267",
        "`indexing.SortedAndUnsortedDatetimeIndexLoc.time_loc_sorted` (Python)": "http://57.128.112.95:5000/compare/benchmarks/066f6449250f782680001f3c602cd479...066f671b60217a4f800001cf43cda62c",
        "`timeseries.DatetimeAccessor.time_dt_accessor_year` (Python) with t='US/Eastern'": "http://57.128.112.95:5000/compare/benchmarks/066f645058b571e9800066b9e2e7653d...066f67223b8179528000f64eb905c640",
        "`timeseries.TzLocalize.time_infer_dst` (Python) with t='US/Eastern'": "http://57.128.112.95:5000/compare/benchmarks/066f6450803972f08000381401641f77...066f672273de7fb380000854185e3419",
        "`timeseries.DatetimeIndex.time_to_date` (Python) with index_type='tz_aware'": "http://57.128.112.95:5000/compare/benchmarks/066f645067d178d280002bb4fbffe23a...066f67224f3d761c800064699af09ede",
        "`timeseries.DatetimeAccessor.time_dt_accessor_date` (Python) with t='US/Eastern'": "http://57.128.112.95:5000/compare/benchmarks/066f64504e167d0480003af47296ee52...066f67222dc274798000cbfdf7925327",
        "`timeseries.DatetimeAccessor.time_dt_accessor_month_name` (Python) with t='US/Eastern'": "http://57.128.112.95:5000/compare/benchmarks/066f6450526679df800020c024151d73...066f672231ec7dc38000a7d42004efd7",
        "`timeseries.DatetimeAccessor.time_dt_accessor_day_name` (Python) with t='US/Eastern'": "http://57.128.112.95:5000/compare/benchmarks/066f6450504e7a3b8000bc019968733e...066f67222fc67757800086752033493c"

<img width="810" alt="Screenshot 2024-09-30 at 14 28 07" src="https://github.com/user-attachments/assets/b00a794d-800c-47ef-b052-427509026ac4">

**Comment by mroeschke** [comment]
Thanks for the issue, but these regressions are expected with the switch from pytz to zoneinfo so closing
