### ISSUE TITLE
ENH: read_excel, read_csv, to_csv, to_excel ... pandas read, write files with progress bar

### ISSUE THREAD

**Issue by ganbaaelmer** [pandas-dev/pandas#59949]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

read_excel, read_csv, to_csv, to_excel ... pandas read, write files with progress bar
we need progress bar for Large data readings

### Feature Description

read_excel, read_csv, to_csv, to_excel ... pandas read, write files with progress bar
we need progress bar for Large data readings

### Alternative Solutions

read_excel, read_csv, to_csv, to_excel ... pandas read, write files with progress bar
we need progress bar for Large data readings

### Additional Context

read_excel, read_csv, to_csv, to_excel ... pandas read, write files with progress bar
we need progress bar for Large data readings

**Comment by mroeschke** [comment]
Thanks for the request but this has been deemed out of scope for pandas so closing

https://github.com/pandas-dev/pandas/issues/28126
https://github.com/pandas-dev/pandas/issues/34249

**Comment by ganbaaelmer** [comment]
this 
[https://github.com/pandas-dev/pandas/issues/28126](url)
[https://github.com/pandas-dev/pandas/issues/34249](url)

those posts still not useful in my case:
because they needed to change my data. so i don't want to touch on my data.

tried to use both methods but gets this error:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 15: invalid continuation byte

**Comment by ganbaaelmer** [comment]
i also need pandas to_sql with native progress bar
