### ISSUE TITLE
BUG: convert_dtypes does not always convert numpy.nan to pd.NA

### ISSUE THREAD

**Issue by carlocastoldi** [pandas-dev/pandas#59961]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import numpy as np
import pandas as pd

x = pd.Series([np.nan, 0.0, 1.2, pd.NA]).convert_dtypes()
y = pd.Series([np.nan, 0.0, 30.2, 10]).convert_dtypes()
z = pd.Series([np.nan, 0.0, 15.2, 9.2]).convert_dtypes()
(z**2 / (x*y)).convert_dtypes()
```

### Issue Description

`numpy.nan` resulting from an arithmetic operation (e.g., division by zero) is not being converted to `pd.NA`. The above examples outputs:

```
0        <NA>
1         NaN
2    6.375276
3        <NA>
dtype: Float64
```

### Expected Behavior

I expect all `np.nan` present in the Series are converted to `pd.NA`:

```
0        <NA>
1        <NA>
2    6.375276
3        <NA>
dtype: Float64

```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 139def2145b83d40364235c6297e1833eab7bb05
python                : 3.12.3
python-bits           : 64
OS                    : Linux
OS-release            : 6.8.0-41-generic
Version               : #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : en_GB.UTF-8
LOCALE                : en_GB.UTF-8

pandas                : 3.0.0.dev0+1545.g139def2145
numpy                 : 2.2.0.dev0+git20240930.3ee9e6a
dateutil              : 2.9.0.post0
pip                   : 24.0
Cython                : None
sphinx                : None
IPython               : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
blosc                 : None
bottleneck            : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : None
lxml.etree            : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
psycopg2              : None
pymysql               : None
pyarrow               : None
pyreadstat            : None
pytest                : None
python-calamine       : None
pytz                  : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2024.2
qtpy                  : None
pyqt5                 : None

</details>

**Comment by asishm** [comment]
Thanks for the report, what you are seeing is discussed in https://github.com/pandas-dev/pandas/issues/32265

`np.nan` gets converted to `pd.NA` in the `x,y,z` lines because the dtype of the series before the conversion is numpy dtypes (object, float64, float64 respectively).

However, once you have Float64 Series (which are nullable EA dtypes), convert_dtypes does not have any further effect. It is the `pd.NA / pd.NA` operation which generates the `NaN`. The current behavior of nullable EA dtypes treats `pd.NA` as missing and `NaN` as not a number.

**Comment by saiteja-yadav** [comment]
Ya! I want to solve this...

**Comment by carlocastoldi** [comment]
Mmh okay, i understand the reasoning of using two different symbols for identifying missing data and invalid results.
A small clarification: `pd.NA / pd.NA` correctly generates another `pd.NA`. It's `0/0` that generates `np.NaN`.

That said: is there an "efficient" way for substitute `NaN`s with `pd.NA`? I can only think about:
```python
series[np.isnan(series)] = pd.NA
```

**Comment by carlocastoldi** [comment]
Thank you! I just read that thread. Very interesting!
