### ISSUE TITLE
DOC: Pandas 2.2.3 pyproject.toml missing "Python 3.13" in classifiers -- but Pandas supports this Python version

### ISSUE THREAD

**Issue by surfaceowl** [pandas-dev/pandas#59978]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

This does not directly impact Pandas behavior, so Docs is the best fit for issue from what I can see.  On searching docs, this is the closest ref:  [https://pandas.pydata.org/docs/dev/getting_started/install.html](https://pandas.pydata.org/docs/dev/getting_started/install.html)<br>

I also searched:
https://pandas.pydata.org/docs/dev/search.html?q=3.13

### Documentation problem

Pandas 2.2.3 `pyproject.toml` file does not include `Python 3.13` in the list of classifiers.<br>

Although Pandas 2.2.3 is broadly compatible with `Python 3.13`, that fact is not documented in `pyproject.toml` causing Pandas version support to be shown incorrectly on on PyPi and other python sources.<br>

The Pandas release announcement on 20 Sept 2024 [https://pandas.pydata.org/docs/whatsnew/v2.2.3.html](https://pandas.pydata.org/docs/whatsnew/v2.2.3.html) states: *"Pandas 2.2.3 is the first version of pandas that is generally compatible with the upcoming Python 3.13, and both wheels for free-threaded and normal `Python 3.13` will be uploaded for this release."*  In addition, I have tested Pandas 2.2.3 with `Python 3.13.0rc3` and not found issues.  

No documentation on current active docs reference Python 3.13:  https://pandas.pydata.org/docs/dev/search.html?q=3.13<br>

*Impact -- People do not know Pandas is compatible with Python 3.13**
- on PyPi -- Pandas 2.2.3 does not show Python 3.13 Programming Language Classifier.
- on pyreadiness.org for Python 3.13 - Pandas does not show up as compatible with 3.13 [https://pyreadiness.org/3.13/](https://pyreadiness.org/3.13/)

### Suggested fix for documentation

**Suggested fix:**
- in [pandas main branch](https://github.com/pandas-dev/pandas/tree/main)<br>
- Add the following line to `pandas/pyproject.toml`  in the `classifiers` block: <br> ```'Programming Language :: Python :: 3.13',```<br>

 **Why it's better:**
Adding this change would populate the Programming Language section of the Classifiers on PyPi, which would then flow through to other sites like pyreadiness.org.

**Comment by rhshadrach** [comment]
cc @lithomas1

**Comment by nahcol10** [comment]
Add the line Programming Language :: Python :: 3.13 in the classifiers section of pandas/pyproject.toml to officially mark Python 3.13 compatibility.

**Comment by rhshadrach** [comment]
Do we need to cut a new 2.2.4 release with perhaps just this fix? cc @pandas-dev/pandas-core

**Comment by mroeschke** [comment]
IMO I'd say no since this appears to be just a documentation issue (but an unfortunate oversight). I see the 3.13 wheels on conda forge and pypi so if pip and conda are able to grab those wheels I don't think it's worth releasing the same wheel to update documenting metadata

**Comment by dhelms33** [comment]
Take

**Comment by dhelms33** [comment]
@mroeschke Hello, I began work on this 36 minutes ago and am new to Pandas! Is this issue still available to contribute to? I opened a pull request, but fear that somebody beat me to it.
 
 https://github.com/pandas-dev/pandas/pull/60007

**Comment by mroeschke** [comment]
Yes sorry, it appears someone else has already opened a pull request. I would recommend finding another issue labeled `good first issue`
