### ISSUE TITLE
DOC: document that DataFrame and Series round() only affect numeric columns

### ISSUE THREAD

**Issue by sfc-gh-mvashishtha** [pandas-dev/pandas#60009]
[DataFrame.round](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.round.html) and `Series.round` seem to ignore non-numeric columns, but their documentation doesn't mention that.

**Comment by sfc-gh-mvashishtha** [comment]
edit: round() seem to ignore all non-numeric columns, which is fine. However, we should document that. I was a little surprised by this behavior for `Timedelta` columns because [Timedelta.round](https://pandas.pydata.org/docs/reference/api/pandas.Timedelta.round.html) does something different than `Series.round`.

**Comment by rhshadrach** [comment]
Thanks for the report. Makes sense to me - PRs to improve the docs here are welcome!
