### ISSUE TITLE
DOC: Update contributing documentation with code coverage details

### ISSUE THREAD

**Issue by d33bs** [pandas-dev/pandas#60010]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/development/contributing_codebase.html

### Documentation problem

Thanks for the great work on Pandas! I was interested in finding out how Pandas measures code coverage and found that there doesn't seem to be much content yet on how to do this for the project. There's a dead link at https://pandas-coverage-12d2130077bc.herokuapp.com/ for the link mentioned in the content `(tip: you can use the [pandas-coverage app](https://pandas-coverage-12d2130077bc.herokuapp.com/))`. 

I also noticed there's a `codecov.yml` file in the project so I looked this up manually by viewing: https://app.codecov.io/github/pandas-dev/pandas . This looks like a nice way to measure code coverage for the project which has already been configured, but isn't already mentioned within documentation (perhaps in addition to the already mentioned tool, once the link is fixed).

### Suggested fix for documentation

I suggest adding the Codecov link somewhere in the contributing documentation and fixing the broken link for the `pandas-coverage app` (multiple measurements / perspectives could be helpful).

**Comment by mroeschke** [comment]
The dead link was removed in https://github.com/pandas-dev/pandas/pull/59536 (the docs will update during the next minor release), but sure a link to the codecov dashboard would be OK.

**Comment by d33bs** [comment]
Thanks @mroeschke ! Apologies about not catching that the dead link was removed in the latest docs.

May I work towards adding content for the Codecov mention through a PR? If so, as a double check, would it make sense to mention any special patterns with concerns to how this impacts development for Pandas specifically?

**Comment by mroeschke** [comment]
> May I work towards adding content for the Codecov mention through a PR?

Sure

>  If so, as a double check, would it make sense to mention any special patterns with concerns to how this impacts development for Pandas specifically?

The Codecov report doesn't impact the development workflow currently (it would be nice to eventually enforce a minimum coverage). Linking to this would just be purely informational
