### ISSUE TITLE
QST: how can I save my sparse dataframe with indexes and columns to a format other than .pkl?

### ISSUE THREAD

**Issue by michelkluger** [pandas-dev/pandas#60017]
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/60956268/save-sparse-pandas-dataframe-to-different-file-types

### Question about pandas

I want have sparse dataframe structure saved in one file (to avoid proliferation of files)

how can I write and read and get the same sparse df? any alternative to pickle?

**Comment by rhshadrach** [comment]
Is your goal just to save disk space? If you can convert the sparse DataFrame to dense in memory, then you can use parquet which is very efficient on sparse data. In the example that you gave in SO, I'm seeing the dense DataFrame take up 18 megabytes in memory but only 1.5 megabytes on disk.

**Comment by michelkluger** [comment]
> Is your goal just to save disk space? If you can convert the sparse DataFrame to dense in memory, then you can use parquet which is very efficient on sparse data. In the example that you gave in SO, I'm seeing the dense DataFrame take up 18 megabytes in memory but only 1.5 megabytes on disk.

Ideally I would like a way / format, to_,format method that is easy to read end write from sparse. If my matrix is too big, converting to dense will cause memory errors

**Comment by rhshadrach** [comment]
Makes sense - it seems to me that hdf would be the most appropriate, and for that there is #42070. Closing in favor of that issue.

**Comment by michelkluger** [comment]
> it seems to me that hdf would be the most appropriate,

why?

**Comment by rhshadrach** [comment]
I do not believe any other file format can support it.
