### ISSUE TITLE
BUG: pandas.series.str.replace() fails on compiled regex pattern for `pat`

### ISSUE THREAD

**Issue by a-ma72** [pandas-dev/pandas#60026]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import regex as re

df = pd.DataFrame({"col": ["foo_this", "bar_this"]})
pattern = re.compile(r"(foo|bar)_.*")
df.col = df.col.str.replace(pat=pattern, repl=r"\1_that", regex=True)
```

### Issue Description

pandas.series.str.replace() works fine, if `pat` is a pattern string, but for compiled patterns, a `TypeError` is risen.

### Expected Behavior

col
=====
foo_that
bar_that

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 0691c5cf90477d3503834d983f69350f250a6ff7
python                : 3.11.9
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.22631
machine               : AMD64
processor             : Intel64 Family 6 Model 140 Stepping 2, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : de_DE.cp1252

pandas                : 2.2.3
numpy                 : 1.26.4
pytz                  : 2024.2
dateutil              : 2.9.0.post0
pip                   : 24.2
Cython                : 3.0.11
sphinx                : 8.0.2
IPython               : 8.27.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
blosc                 : None
bottleneck            : 1.4.0
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.9.0
html5lib              : 1.1
hypothesis            : 6.112.1
gcsfs                 : None
jinja2                : 3.1.4
lxml.etree            : 5.3.0
matplotlib            : 3.8.4
numba                 : 0.60.0
numexpr               : 2.10.1
odfpy                 : None
openpyxl              : 3.1.5
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : 16.1.0
pyreadstat            : None
pytest                : 8.3.3
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.14.1
sqlalchemy            : 2.0.35
tables                : 3.10.1
tabulate              : 0.9.0
xarray                : 2024.9.0
xlrd                  : 2.0.1
xlsxwriter            : 3.2.0
zstandard             : 0.23.0
tzdata                : 2024.1
qtpy                  : 2.4.1
pyqt5                 : None

</details>

**Comment by asishm** [comment]
Thanks for the report. The docs state that it is equivalent to `re.sub` which is the stdlib `re` library (and hyperlinks to the same). You're using a third package library `regex` which is not documented to be supported.

Note: `pandas` internally calls `from re import Pattern; isinstance(pat, Pattern)` to determine if the pattern provided is a compiled pattern which `regex.compile` compiled patterns don't pass.

```py
In [1]: import regex as re2

In [2]: import re

In [3]: isinstance(re.compile('.'), re.Pattern)
Out[3]: True

In [4]: isinstance(re2.compile('.'), re.Pattern)
Out[4]: False
```

**Comment by rhshadrach** [comment]
Agreed @asishm - and I do not think we should be supporting third-party packages here. Closing.
