### ISSUE TITLE
BUG: pyxlsb fails to parse datetime-like data

### ISSUE THREAD

**Issue by MCRE-BE** [pandas-dev/pandas#60062]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example
When trying to build some new tests, I found a strange behavior.
- My apologies, but I can't simply have a copy/paste code answer as we can't export to `xlsb `and `xlsm `directly in pandas if I'm not mistaken. 
- Data can be found with test environment in pandas\tests\io\data\excel
- A local copy : [07. Pandas tests.zip](https://github.com/user-attachments/files/17407021/07.Pandas.tests.zip)

```python
import pandas as pd
from pathlib import Path

files = Path(".").glob("test1*")
files = list(files)
files
>>> [WindowsPath('test1.ods'),
>>>  WindowsPath('test1.xls'),
>>> WindowsPath('test1.xlsb'),
>>> WindowsPath('test1.xlsm'),
>>> WindowsPath('test1.xlsx')]

for f in files:
    print(f)
    display(pd.read_excel(f))
```

### Issue Description

<img width="282" alt="image" src="https://github.com/user-attachments/assets/fa55a5ec-df5e-4548-b0a6-99fc3479c2ce">

### Expected Behavior

All dataframes should be read the same

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.6.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.19042
machine               : AMD64
processor             : AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : Dutch_Belgium.1252

pandas                : 2.2.2
numpy                 : 2.0.2
pytz                  : 2024.2
dateutil              : 2.9.0
setuptools            : 75.1.0
pip                   : 24.2
Cython                : None
pytest                : 8.3.3
hypothesis            : None
sphinx                : 7.4.7
blosc                 : None
feather               : None
xlsxwriter            : 3.2.0
lxml.etree            : 5.3.0
html5lib              : 1.1
pymysql               : None
psycopg2              : None
jinja2                : 3.1.4
IPython               : 8.21.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
bottleneck            : 1.4.0
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.9.0
gcsfs                 : None
matplotlib            : 3.9.1
numba                 : 0.60.0
numexpr               : 2.10.0
odfpy                 : None
openpyxl              : 3.1.5
pandas_gbq            : None
pyarrow               : 17.0.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : 1.0.10
s3fs                  : None
scipy                 : 1.14.1
sqlalchemy            : None
tables                : None
tabulate              : 0.9.0
xarray                : None
xlrd                  : 2.0.1
zstandard             : 0.23.0
tzdata                : 2024.2
qtpy                  : 2.4.1
pyqt5                 : None

</details>

**Comment by asishm** [comment]
This is a limitation of the pyxlsb library. Their docs note that
>Do note that dates will appear as floats. You must use the convert_date(date) method from the pyxlsb module to turn them into datetime instances.

**Comment by MCRE-BE** [comment]
@asishm : Thanks for the information. So it's a "feature" / "chosen limitation" (I don't know how to express this better) instead of an oversight that Pandas does convert float to dates for pyxlsb ? 
If it's the case, we can indeed close this issue as it's not a bug.

**Comment by asishm** [comment]
Pandas relies on other libraries to do most of the heavy lifting in parsing excel files. In case of xlsb files, pandas relies on `pyxlsb`. It looks like results returned by the library don't differentiate between dates and floats (unlike other libraries like openpyxl for xlsx files). Therefore, pandas has no way to know which columns are date columns.

If you know which columns are dates, you can pass in the `convert_date` function in the `converters` paramter of `pd.read_excel`.

I guess a note indicating this limitation might be good.
