### ISSUE TITLE
BUG: DataFrame(data=[None, 1], dtype='timedelta64[ns]') raises ValueError: Buffer has wrong number of dimensions

### ISSUE THREAD

**Issue by sfc-gh-mvashishtha** [pandas-dev/pandas#60064]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame([None, 1], dtype='timedelta64[ns]')
```

### Issue Description

The error message doesn't tell the user what to do differently. Also, it's possible that there shouldn't be an error at all.

### Expected Behavior

I think this should be allowed, in which case the resulting series would look like

```
                          0
0                       NaT
1 0 days 00:00:00.000000001
```

If it's not allowed, the error message should be clearer.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 0691c5cf90477d3503834d983f69350f250a6ff7
python                : 3.9.18
python-bits           : 64
OS                    : Darwin
OS-release            : 23.6.0
Version               : Darwin Kernel Version 23.6.0: Wed Jul 31 20:48:52 PDT 2024; root:xnu-10063.141.1.700.5~1/RELEASE_ARM64_T6020
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.3
numpy                 : 1.26.3
pytz                  : 2023.3.post1
dateutil              : 2.8.2
pip                   : 23.3.1
Cython                : None
sphinx                : None
IPython               : 8.18.1
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
blosc                 : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : None
lxml.etree            : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : None
pyreadstat            : None
pytest                : 8.3.2
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2023.4
qtpy                  : None
pyqt5                 : None

</details>

**Comment by yuanx749** [comment]
I can confirm on main. Seems `cast_from_unit_vectorized` only accepts 1d array as input, but the data become 2d somehow.
```Python traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xiao/pandas/pandas/core/frame.py", line 843, in __init__
    mgr = ndarray_to_mgr(
  File "/home/xiao/pandas/pandas/core/internals/construction.py", line 271, in ndarray_to_mgr
    values = sanitize_array(
  File "/home/xiao/pandas/pandas/core/construction.py", line 624, in sanitize_array
    subarr = _try_cast(data, dtype, copy)
  File "/home/xiao/pandas/pandas/core/construction.py", line 810, in _try_cast
    return maybe_cast_to_datetime(arr, dtype)
  File "/home/xiao/pandas/pandas/core/dtypes/cast.py", line 1228, in maybe_cast_to_datetime
    res = TimedeltaArray._from_sequence(value, dtype=dtype)
  File "/home/xiao/pandas/pandas/core/arrays/timedeltas.py", line 232, in _from_sequence
    data, freq = sequence_to_td64ns(data, copy=copy, unit=None)
  File "/home/xiao/pandas/pandas/core/arrays/timedeltas.py", line 1114, in sequence_to_td64ns
    data = cast_from_unit_vectorized(data, unit or "ns")
  File "conversion.pyx", line 138, in pandas._libs.tslibs.conversion.cast_from_unit_vectorized
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)
```
