### ISSUE TITLE
BUG: unable to insert 64-bit integers into dataframe.

### ISSUE THREAD

**Issue by dominiquegarmier** [pandas-dev/pandas#60101]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df1 = pd.DataFrame(index=range(1), columns=['foo','bar'], dtype='Int64')
df2 = df1.copy()

# insert using a dict
df1.loc[0] = {'foo': 1729509695129311113}

# insert normally
df2.loc[0, 'foo'] = 1729509695129311113

assert df1.equals(df2), 'oops'
```

### Issue Description

when trying to insert an int into a (nullable) `Int64` column, depending on the method used, the integer is first coereced to a `float64` and therefore loses some of its precision.

### Expected Behavior

both methods should work without losing precsion, i.e., like `df2`.

### Installed Versions

INSTALLED VERSIONS
------------------
commit                : 0691c5cf90477d3503834d983f69350f250a6ff7
python                : 3.12.3
python-bits           : 64
OS                    : Darwin
OS-release            : 23.5.0
Version               : Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.3
numpy                 : 2.0.2
pytz                  : 2024.2
dateutil              : 2.9.0.post0
pip                   : 24.2
Cython                : None
sphinx                : None
IPython               : 8.28.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
blosc                 : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : None
lxml.etree            : None
matplotlib            : None
numba                 : 0.60.0
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : 17.0.0
pyreadstat            : None
pytest                : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2024.2
qtpy                  : None
pyqt5                 : None

**Comment by rhshadrach** [comment]
Thanks for the report.

    df1.loc[0] = {'foo': 1729509695129311113}

In this, you are setting all of row 0 in `df1`, providing no values for other columns. pandas aligns with the remaining columns, filling in NA values as necessary. Because this is a dictionary and there is no type information (`int64` vs `Int64)`, pandas defaults to NumPy dtypes, and the alignment results in float64 with `np.nan` as the missing value.

Both of these produce the expected behavior:

```python
df1 = pd.DataFrame(index=range(1), columns=['foo','bar'], dtype='Int64')
df1.loc[0] = {'foo': 1_729_509_695_129_311_113, 'bar': 0}

df1 = pd.DataFrame(index=range(1), columns=['foo','bar'], dtype='Int64')
df1.loc[0] = pd.Series({'foo': 1_729_509_695_129_311_113}, dtype='Int64')
```

When pandas switches to nullable dtypes by default, this issue would be automatically resolved. As such, I'd suggest keeping the current behavior as-is.

**Comment by dominiquegarmier** [comment]
Thanks for the response.

I assumed that something like this was happening. Sadly the solution you provided does not work in my case as it would be too costly to create a dict filled with default values.

I found another solution since then.
