### ISSUE TITLE
VOTE: Voting issue for PDEP-17: Backwards compatibility and deprecation policy

### ISSUE THREAD

**Issue by Aloqeely** [pandas-dev/pandas#60126]
### Locked issue

- [X] I locked this voting issue so that only voting members are able to cast their votes or comment on this issue.

### PDEP number and title

PDEP-17: Backwards compatibility and deprecation policy

### Pull request with discussion

https://github.com/pandas-dev/pandas/pull/59125

### Rendered PDEP for easy reading

https://github.com/Aloqeely/pandas/blob/pdep-17/web/pandas/pdeps/0017-backwards-compatibility-and-deprecation-policy.md

### Voting will close in 15 days.

on November 13

### Vote

Cast your vote in a comment below.
* +1: approve.
* 0: abstain.
    * Reason: A one sentence reason is required.
* -1: disapprove
    * Reason: A one sentence reason is required.
A disapprove vote requires prior participation in the linked discussion PR.

**Comment by Aloqeely** [comment]
@pandas-dev/pandas-core 
+1

**Comment by rhshadrach** [comment]
+1

**Comment by lithomas1** [comment]
+1

**Comment by WillAyd** [comment]
+1

**Comment by bashtage** [comment]
+1 since an improvement over the status quo

One thing that still feel strange is that the second statement in the abstract appears to limit removal to only major releases, which has not always been the case. Not sure if this an intended restriction.

**Comment by MarcoGorelli** [comment]
big +1, future warnings everywhere are disruptive imo

> the second statement in the abstract appears to limit removal to only major releases, which has not always been the case

i wasn't aware of that having happened since 1.0, could you clarify which remove you're referring to please?

**Comment by attack68** [comment]
+1

**Comment by Dr-Irv** [comment]
+1

Worth mentioning that the following statement will require some care on the part of the core team:
> Deprecations should initially use `DeprecationWarning`, and then be switched to `FutureWarning` for broader visibility in the last minor release before the major release they are planned to be removed in.

Let's say we believe a version 3.3 will be the last minor version prior to a major release of 4.0.  So the switch is made to change all the `DeprecationWarning` in 3.2 to `FutureWarning` in 3.3.  But then something happens and there is a decision to release a 3.4. The `FutureWarning` has now existed for 2 minor releases.  I think this is OK, but we should be aware that this might happen.

**Comment by jorisvandenbossche** [comment]
+1

**Comment by jreback** [comment]
+1

**Comment by mroeschke** [comment]
+1

**Comment by simonjayhawkins** [comment]
+1

**Comment by rhshadrach** [comment]
Results: 13-0-0-8

The PDEP is accepted.
