### ISSUE TITLE
ENH: To add an `inplace` option for pd.DataFrame.reindex

### ISSUE THREAD

**Issue by blue-cat-whale** [pandas-dev/pandas#60199]
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish I could update the index of a dataframe inplace.

### Feature Description

Functions `pd.DataFrame.set_index()` and `pd.DataFrame.reset_index()` both have an option of `inplace=True`. I hope function `pd.DataFrame.reindex()` add it as well. This might lead to adding another option of `drop=True`.

### Alternative Solutions

N/A

**Comment by jorisvandenbossche** [comment]
Given that we are planning to remove the `inplace` keyword in most cases (see https://github.com/pandas-dev/pandas/pull/51466, rendered view of the PDEP at https://jorisvandenbossche.github.io/pandas-website-preview/pdeps/0008-inplace-methods-in-pandas.html), I think we won't add it in new places.

Specifically for `reindex`, this is an example of method that in practice can never be done in-place, so the `inplace=True` option would just be the same as doing `df = df.reindex(..)` under the hood.

**Comment by WillAyd** [comment]
Agree with @jorisvandenbossche here - we have been moving away from this API
