### ISSUE TITLE
BUG: `pprint_thing(..., quote_strings=True)` fails for strings with embedded single-quotes

### ISSUE THREAD

**Issue by zpincus** [pandas-dev/pandas#60190]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
from pandas.io.formats.printing import pprint_thing

print(pprint_thing("'510", quote_strings=True))
```

### Issue Description

The code above produces the incorrect `''510'` as output, instead of `"'510"` as python does, or even `'\'510'`.

In the [current master](https://github.com/pandas-dev/pandas/blob/main/pandas/io/formats/printing.py#L240C1-L242C1) the cause is clear enough:
```python
    elif isinstance(thing, str) and quote_strings:
        result = f"'{as_escaped_string(thing)}'"
```
Either python's string `repr` could be used (assuming the rest of its behavior is fit for the purpose), or single-quotes could be explicitly backslash-escaped.

### Expected Behavior

As above.

### Installed Versions

As above, but is present in GitHub master as of right now.

**Comment by rhshadrach** [comment]
Thanks for the report. While this method is not public, the issue can manifest in e.g.

```python
df = pd.DataFrame({"'a": [1, 1, 2], "b": [3, 4, 5], "c": 6}).set_index(["'a", "b"])
print(df.index.names)
# [''a', 'b']
```

PRs to fix are welcome!

**Comment by thedataninja1786** [comment]
This can be addressed by changing in `..\core\indexes\frozen.py` the `__str__` to include single quotes also `def __str__(self) -> str:
        return pprint_thing(self, quote_strings=True, escape_chars=("\t", "\r", "\n","'"))`  and extending pprint_thing's to `translate = {"\t": r"\t", "\n": r"\n", "\r": r"\r","'":""}` in ..\printing.py to remove them. I believe escaping single quotes does not work here since the output itself is wrapped in single quotes.
