### ISSUE TITLE
DOC: Improve documentation df.interpolate() for methods   ‘time’, ‘index’ and ‘values’

### ISSUE THREAD

**Issue by aleksejs-fomins** [pandas-dev/pandas#60227]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.interpolate.html

### Documentation problem

It is not possible to understand what exactly the method `interpolate` does from reading the documentation. See e.g. this SE post for more details

https://stackoverflow.com/questions/65511992/pandas-interpolation-type-when-method-index

### Suggested fix for documentation

Rewrite doctstring and documentation page for the method

**Comment by rhshadrach** [comment]
Thanks for the report, agreed this could use clarification. PRs to improve are welcome!

**Comment by anishkarki** [comment]
take
