### ISSUE TITLE
BUG: dropna throws error with arguments axis=1 and subset not None

### ISSUE THREAD

**Issue by ochabloz** [pandas-dev/pandas#60244]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'], "toy": [np.nan, 'Batmobile', 'Bullwhip'], "born": [pd.NaT, pd.NaT,pd.NaT]})
df.dropna(axis=1, subset=['born'])
```

### Issue Description

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 6670, in dropna
    raise KeyError(np.array(subset)[check].tolist())
KeyError: ['born']

### Expected Behavior

dropna should return the dataframe without the `born` column.

### Installed Versions

<details>

commit                : 0691c5cf90477d3503834d983f69350f250a6ff7
python                : 3.10.15
python-bits           : 64
OS                    : Linux
OS-release            : 6.11.5
Version               : #1-NixOS SMP PREEMPT_DYNAMIC Tue Oct 22 13:51:37 UTC 2024
machine               : x86_64
processor             : 
byteorder             : little
LC_ALL                : None
LANG                  : C.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.3
numpy                 : 1.26.4
pytz                  : 2024.2
dateutil              : 2.9.0.post0
pip                   : 23.0.1
Cython                : None
sphinx                : None
IPython               : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
blosc                 : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : 3.1.4
lxml.etree            : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : None
pyreadstat            : None
pytest                : 8.3.3
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.14.1
sqlalchemy            : 2.0.36
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2024.2
qtpy                  : None
pyqt5                 : None

</details>

**Comment by asishm** [comment]
Thanks for the report. The error is accurate.

The documentation for the `subset` argument states:
> subset : column label or sequence of labels, optional
    Labels along other axis to consider, e.g. if you are dropping rows
    these would be a list of columns to include.

Note that it mentions **other axis**. In this case you specify `axis=1` i.e. columns, therefore for `subset` you need to provide row labels (but that doesn't sound like what you're after).

`df.dropna(axis=1, how='all')` will drop all columns where every value is na

**Comment by rhshadrach** [comment]
Agreed @asishm - closing.
