### ISSUE TITLE
BUG: `from pandas.core.tools.datetimes import parsing` no longer works since pandas 2.2.0, not documented

### ISSUE THREAD

**Issue by corneliusroemer** [pandas-dev/pandas#60276]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas
from pandas.core.tools.datetimes import parsing  # since pandas 2.2.0 raises ImportError: cannot import name 'parsing' from 'pandas.core.tools.datetimes'
```

### Issue Description

Since pandas v2.2.0, `from pandas.core.tools.datetimes import parsing` raises `ImportError: cannot import name 'parsing' from 'pandas.core.tools.datetimes'`

This is not documented in the changelog, so maybe it is an accident?

### Expected Behavior

I can import successfully

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : f538741432edf55c6b9fb5d0d496d2dd1d7c2457
python                : 3.12.7.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 24.1.0
Version               : Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : en_GB.UTF-8
LOCALE                : en_GB.UTF-8

pandas                : 2.2.0
numpy                 : 1.26.4
pytz                  : 2024.2
dateutil              : 2.9.0
setuptools            : 75.3.0
pip                   : 24.3.1
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.2
qtpy                  : None
pyqt5                 : None
</details>

**Comment by asishm** [comment]
Thanks for the report. I don't think that this was ever documented in the public api reference (https://pandas.pydata.org/docs/reference/index.html)  in the past (if yes, could you please link the to the docs?)

pandas generally treats undocumented methods/modules as private. The relevant import was removed in https://github.com/pandas-dev/pandas/pull/55652

**Comment by corneliusroemer** [comment]
Thanks, I misunderstood the following part of the docs:
>This page gives an overview of all public pandas objects, functions and methods. All classes and functions exposed in pandas.* namespace are public.

In particular, `pandas.*` means "with only one but not more than one periods", maybe this could be stated more explicitly.

When rereading, I see that core is explicitly mentioned as private, but this is quite a bit down the page:
>The pandas.core, pandas.compat, and pandas.util top-level modules are PRIVATE. Stable functionality in such modules is not guaranteed.

https://pandas.pydata.org/docs/reference/index.html
