### ISSUE TITLE
DOC: Document merge_cells="columns" in to_excel

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas#60275]
https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.to_excel.html

The `merge_cells` argument can also take `"columns"` due to #35384. This should be added to the docstring.

**Comment by ZKaoChi** [comment]
take

**Comment by ZKaoChi** [comment]
I found it was added once, but then overwritten.
