### ISSUE TITLE
DOC: Update URL in web/pandas/about/index.md

### ISSUE THREAD

**Issue by setbit123** [pandas-dev/pandas#60361]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://github.com/pandas-dev/pandas/blob/main/web/pandas/about/index.md

### Documentation problem

I discovered that the URL pointing to "all of our contributors" on line 9 in the `pandas/web/pandas/about/index.md` file is invalid, and I would like to address this issue. This problem might be due to an incomplete URL. It works fine when accessed from https://pandas.pydata.org/about/, but it causes problems when clicked from the source code on GitHub.

Current state:
Thank you to [all of our contributors](https://github.com/pandas-dev/pandas/blob/main/web/pandas/about/team.html).
(Due to the original URL leading to different pages when navigating from the issue interface and the source code interface, I have modified the URL to direct to the page for source code navigation instead.)

What I propose:
Thank you to [all of our contributors](https://pandas.pydata.org/about/team.html).

If you agree with my suggestion, I will submit a PR myself.

### Suggested fix for documentation

Removed the invalid URL, replaced it with a new URL.

**Comment by setbit123** [comment]
If there are any grammatical errors or if you have a better way of phrasing it, please let me know, and I will adjust the content for the upcoming PR.

**Comment by rhshadrach** [comment]
Thanks for the report!

It appears all links to pages within the pandas website are relative. This makes it so they do not have to be changed if the website is moved. It also makes it so that previewing a dev build of the website functions appropriately. I do not think this should be changed.

**Comment by setbit123** [comment]
Thank you for your response. I will close the issue and make no changes.
