### ISSUE TITLE
DOC: methods in see also section in the  pandas.DataFrame.size  are not hyperlinks

### ISSUE THREAD

**Issue by Shubhank-Gyawali** [pandas-dev/pandas#60368]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.size.html

### Documentation problem

In the see also section the `ndarray.size` method is listed, but it is not hyperlinks and thus the reader cannot navigate with ease but has to look for them instead. 

### Suggested fix for documentation

Add numpy.ndarray.size in the docstring.

**Comment by lfffkh** [comment]
take

**Comment by Shubhank-Gyawali** [comment]
take
