### ISSUE TITLE
DOC: Add missing links to optional dependencies in getting_started/install.html

### ISSUE THREAD

**Issue by bluestarunderscore** [pandas-dev/pandas#60364]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/getting_started/install.html

### Documentation problem

On the “Installation” page, links are provided to the GitHub pages for the required dependencies and some of the optional dependencies, but the optional dependencies in the tables from “Visualization” onward do not link to the GitHub pages of the projects. Links are provided to the optional HTML-related dependencies are present, but not in the dependency table.

### Suggested fix for documentation

Add links to the library names which link to their respective repositories to make the page more consistent.

**Comment by rhshadrach** [comment]
Thanks for the report. PRs welcome!

**Comment by jmalp** [comment]
take

**Comment by jmalp** [comment]
@Yuvraj-Pradhan-27 Yes, I will ping you if I unassign.

**Comment by Yuvraj-Pradhan-27** [comment]
Sure, thanks.

**Comment by Yuvraj-Pradhan-27** [comment]
@jmalp, Could you please provide an update on the status of the issue? If it's alright with you, would you mind if I addressed the issue?

**Comment by jmalp** [comment]
@Yuvraj-Pradhan-27 Sure, you can go ahead an assign yourself.

**Comment by Yuvraj-Pradhan-27** [comment]
@jmalp Thank you, I will go ahead with it.

**Comment by Uvi-27** [comment]
take
