### ISSUE TITLE
DOC: Missing type hint for squeeze method

### ISSUE THREAD

**Issue by JessJohn0** [pandas-dev/pandas#60384]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://github.com/pandas-dev/pandas/blob/main/pandas/core/generic.py

### Documentation problem

The squeeze method is missing a type hint. 

### Suggested fix for documentation

Adding a type hint to the squeeze method to be consistent with the rest of the code.

**Comment by KevsterAmp** [comment]
Can confirm, specifically this line: https://github.com/pandas-dev/pandas/blob/1c986d6213904fd7d9acc5622dc91d029d3f1218/pandas/core/generic.py#L841

**Comment by jasonmokk** [comment]
take
