### ISSUE TITLE
DOC: Missing 'pickleshare' package when running 'sphinx-build' command

### ISSUE THREAD

**Issue by hwhsu1231** [pandas-dev/pandas#60429]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://github.com/pandas-dev/pandas/blob/106f33cfce16f4e08f6ca5bd0e6e440ec9a94867/requirements-dev.txt#L26

### Documentation problem

After installing `requirements-dev.txt` and `pandas` from sources, I tried to run `sphinx-build` command to build pandas docs. However, I noticed that there are lots of such warnings:

```bash
UserWarning: This is now an optional IPython functionality, using bookmarks requires you to install the `pickleshare` library.
  bkms = self.shell.db.get('bookmarks',{})
UsageError: %bookmark -d: Can't delete bookmark 'ipy_savedir'
```

The followings are the commands I used:

```bash
git clone --branch=main https://github.com/pandas-dev/pandas.git pandas-main
cd pandas-main
git log -1 --pretty=format:"%H%n%s"
conda create --prefix ./.venv --channel conda-forge --yes
conda activate ./.venv
conda install python=3.10 --yes
export PYTHONNOUSERSITE=1
python -m pip install --requirement=requirements-dev.txt --progress-bar=off --verbose
python -m pip install . --no-build-isolation --no-deps -Csetup-args=--werror --progress-bar=off --verbose
export LANG=en_US.UTF-8
sphinx-build -b html -v -j 4 -c doc/source doc/source doc/build/html
```

Log file of the above commands:

[log-sphinx-build-pandas-docs.txt](https://github.com/user-attachments/files/17928982/log-sphinx-build-pandas-docs.txt)

### Suggested fix for documentation

It seems that this issue is caused by https://github.com/ipython/ipython/issues/14237. Therefore, my suggested fix is to add `pickleshare` requirement in `environment.yml` and `requirements-dev.txt`. 

Just like NumPy demonstrated here: [requirements/doc_requirements.txt#L12-L14](https://github.com/numpy/numpy/blob/4e8f724fbc136b1bac1c43e24d189ebc45e056eb/requirements/doc_requirements.txt#L12-L14)

### Versions and Platforms

- OS version: Kubuntu 24.04
- Current Branch: [`main`](https://github.com/numpy/numpy/tree/main)
- Latest Commit: 106f33cfce16f4e08f6ca5bd0e6e440ec9a94867
- Conda version: `24.9.2`
- Python version: `3.10.15`
- iPython version: `8.29.0`

**Comment by rhshadrach** [comment]
Thanks for the report, PRs to fix are welcome!

**Comment by lfffkh** [comment]
take

**Comment by hwhsu1231** [comment]
Will PR #60468 be backported to as many previous versions as possible?

Suppose that those PRs merged into the default branch are backported to branches like [2.2.x](https://github.com/pandas-dev/pandas/tree/2.2.x), [2.1.x](https://github.com/pandas-dev/pandas/tree/2.1.x), [2.0.x](https://github.com/pandas-dev/pandas/tree/2.0.x),...etc. Will tags be added for those backports? (For example, `v2.0.3` -> `v2.0.4`)

Simply curious about the project management policy of pandas.

**Comment by rhshadrach** [comment]
In only truly exceptional circumstances will we backport beyond the last minor version (2.2 right now). For this, I do not believe we will backport at all, this only impacts development of pandas.
