### ISSUE TITLE
BUG: timestamp value is different with pd.Timestamp and regular python datetime (tz naive with same value)

### ISSUE THREAD

**Issue by nicknolt** [pandas-dev/pandas#60425]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

ori_ts = 1719850245.23
pd_date = pd.Timestamp(ori_ts, unit='s')
py_date = pd_date.to_pydatetime()

pd_ts = pd_date.timestamp()
py_ts = py_date.timestamp()

delta = abs(pd_ts - py_ts)

print(delta)
```

### Issue Description

with the same tz and time values the given timestamp is not the same.
I'm in France and the delta between both is 7200 seconds corresponding to the GMT+2 tz

### Expected Behavior

In the documentation pd.Timestamp will behave like the datetime, i was expecting to have the same value

### Installed Versions

I have installed the 2.2.2 version and i have tried with older version and also with the 1.x version and the result is the same

**Comment by yuanx749** [comment]
Hmm, according to the doc of datetime [here](https://docs.python.org/3/library/datetime.html#datetime.datetime.timestamp):

> There is no method to obtain the POSIX timestamp directly from a naive [datetime](https://docs.python.org/3/library/datetime.html#datetime.datetime) instance representing UTC time. If your application uses this convention and your system time zone is not set to UTC, you can obtain the POSIX timestamp by supplying tzinfo=timezone.utc:

seems `py_ts = py_date.replace(tzinfo=timezone.utc).timestamp()` can get the same value as pd.Timestamp.

**Comment by nicknolt** [comment]
It seems that python datetime use local tz to convert into timestamp when the date is naive.
If this is the normal behavior for the pd.Timestamp to nor proceed like python datetime, it's not a bug then i close this issue.
Thanks for the response and for all the team of pandas
