### ISSUE TITLE
BUG: Incorrect casting of int to float when np.nan assigned to Series with nullable boolean index

### ISSUE THREAD

**Issue by DhruvBShetty** [pandas-dev/pandas#60439]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

abc=pd.Series([1,2,3],index=np.array([False,True,pd.NA], dtype=pd.BooleanDtype),dtype="int64")
abc
Out[1]:
False    1
True     2
<NA>     3
dtype: int64

abc.loc[[True,False,False]]=np.NaN
abc
Out[2]:
False    NaN
True     2.0
<NA>     3.0
dtype: float64

```

### Issue Description

A Series with Nullable Boolean dtype index casts the entire series to float64 when it's originally int64.

### Expected Behavior

Everything else remains the same besides NaN.
```
import pandas as pd
import numpy as np

abc=pd.Series([1,2,3],index=np.array([False,True,pd.NA], dtype=pd.BooleanDtype),dtype="int64")
abc
Out[1]:
False    1
True     2
<NA>     3
dtype: int64

abc.loc[[True,False,False]]=np.NaN
abc
Out[2]:
False    NaN
True     2
<NA>     3
dtype: int64
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 0691c5cf90477d3503834d983f69350f250a6ff7
python                : 3.10.5
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.19045
machine               : AMD64
processor             : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : English_United States.1252

pandas                : 2.2.3
numpy                 : 1.24.3
pytz                  : 2023.3
dateutil              : 2.8.2
pip                   : 22.1.2
Cython                : None
sphinx                : None
IPython               : 8.13.2
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.2
blosc                 : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.6.0
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : 3.1.2
lxml.etree            : None
matplotlib            : 3.8.2
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : None
pyreadstat            : None
pytest                : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.11.4
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2023.3
qtpy                  : None
pyqt5                 : None

</details>

**Comment by asishm** [comment]
Thanks for the report. pandas `int64` series cannot hold `np.nan`, so it gets upcasted to `float64` series

**Comment by DhruvBShetty** [comment]
@asishm The problem still persists and I have tried "Int64" with pd.array() too, it's in version 2.2.3, what version are you on?
```
import pandas as pd
import numpy as np

abc=pd.Series([1,2,3],index=np.array([False,True,pd.NA],dtype=pd.Int64Dtype))
abc
Out[1]:
False    1
True     2
<NA>     3
dtype: int64

abc.loc[[True,False,False]]=np.NaN
abc
Out[2]:
False    NaN
True     2.0
<NA>     3.0
dtype: float64
```

**Comment by asishm** [comment]
I meant the dtype of your series, not of the index. i.e. 

`abc=pd.Series([1,2,3],index=np.array([False,True,pd.NA], dtype=pd.BooleanDtype),dtype="Int64")`

unless I'm misunderstanding the issue.

**Comment by DhruvBShetty** [comment]
@asishm Apologies for that, yes you you are right
