### ISSUE TITLE
DOC: DeprecationWarning on "Intro to data structures" user guide

### ISSUE THREAD

**Issue by Ezrio1** [pandas-dev/pandas#60490]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/user_guide/dsintro.html

### Documentation problem

I got warning at `In [48]: data = np.zeros((2,), dtype=[("A", "i4"), ("B", "f4"), ("C", "a10")])`. Warning is

>  "DeprecationWarning: Data type alias 'a' was deprecated in NumPy 2.0. Use the 'S' alias instead."

### Suggested fix for documentation

Following the warning's instructions, I changed `("C","a10")` to `("C","S10")`, and the warning resolved.

**Comment by asdkfjsd** [comment]
Hello！Have you already submitted a pull request? If not, I'd be happy to help resolve this issue.

**Comment by Ezrio1** [comment]
Hello, no I didn't. You can create one

**Comment by asdkfjsd** [comment]
take
