### ISSUE TITLE
DOC: Fix the navigation bar

### ISSUE THREAD

**Issue by easternsun7** [pandas-dev/pandas#60492]
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html#

### Documentation problem

pandas.DataFrame.head and pandas.DataFrame.tail appear twice in the navigation bar, and they jump to the same location.

### Suggested fix for documentation

I think the duplication in the navigation bar is a small bug, consider removing duplicate links in the documentation.

**Comment by easternsun7** [comment]
If you think it should be removed, I can submit a PR to change it.

**Comment by owengrimaldi** [comment]
take
