### ISSUE TITLE
BUG: Presence of `pd.NA` value in `pd.Series` prevents values from being rounded

### ISSUE THREAD

**Issue by mijalapenos** [pandas-dev/pandas#60499]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
pd.Series([1.123, 2.123, pd.NA]).round(0)
```

### Issue Description

Presence of `pd.NA` value in `pd.Series` prevents values from being rounded.
```
>>> pd.Series([1.123, 2.123, pd.NA]).round(0)
0    1.123
1    2.123
2     <NA>
dtype: object
```

### Expected Behavior

I would expect the same behavior as with `np.nan` values:
```
>>> pd.Series([1.123, 2.123, np.nan]).round(0)
0    1.0
1    2.0
2    NaN
dtype: float64
```

### Installed Versions

<details>

/Users/<USER>/miniforge3/envs/nlp/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.9.16.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 24.1.0
Version               : Darwin Kernel Version 24.1.0: Thu Oct 10 21:05:14 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8103
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : None.UTF-8

pandas                : 2.2.2
numpy                 : 1.25.2
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 68.2.2
pip                   : 23.2.1
Cython                : None
pytest                : 7.4.0
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 4.9.3
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.2
IPython               : 8.16.1
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.2
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2023.10.0
gcsfs                 : None
matplotlib            : 3.8.0
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 14.0.1
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.11.3
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2023.3
qtpy                  : None
pyqt5                 : None

</details>

**Comment by rhshadrach** [comment]
Thanks for the report. When you do not specify a dtype, pandas results in object dtype here. `round()` does not impact object dtype.

```python
res = pd.Series([1.123, 2.123, pd.NA], dtype="Float64").round(0)
print(res)
# 0     1.0
# 1     2.0
# 2    <NA>
# dtype: Float64
```

That pandas does not infer Float64 without the dtype is #33662.

Closing.
