### ISSUE TITLE
BUG:  concatenation is allowing duplicate columns when axis=1

### ISSUE THREAD

**Issue by Sakethsreeram7** [pandas-dev/pandas#60504]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df1=pd.DataFrame({'a':1,'b':2},index=[0])
df2=pd.DataFrame({'a':1,'b':2},index=[0])
df_new=pd.concat([df1,df2],axis=1)
```

### Issue Description

When concatenation is done by axis=1 the duplicate columns are added up without raising an error then this will be very confusing as these are not identified as different 

### Expected Behavior

If the columns are the same before concatenating then in new df these should be some unique identifier 
let's say: a(1), b(1) like this 

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by kevkle** [comment]
i would like to contribute. 

The question is whether an error should be raised or the columns should be renamed ?

**Comment by Sakethsreeram7** [comment]
columns should be renamed , Thanks!

**Comment by quantresearch1** [comment]
Hi, in terms of renaming scheme, I assume we would the usual _x and _y  default suffixes that we see in merges ?

**Comment by asishm** [comment]
This already exists with the `verify_integrity` param. `pd.concat([df1, df2], axis=1, verify_integrity=True)` raises with `ValueError: Indexes have overlapping values: Index(['a', 'b'], dtype='object')`

**Comment by kevkle** [comment]
But isn't it good if the columns are updated by themselves

**Comment by kevkle** [comment]
Or that it should be fixed with another parameter directly ?

**Comment by yuanx749** [comment]
Seems `join` is more suitable in this case, or you can `DataFrame.add_suffix` before `concat`.

**Comment by rhshadrach** [comment]
Thanks for the report! As mentioned above there are already suitable arguments / methods if one wants to raise or suffix the columns. I'm negative on adding more complexity to `concat` as these alternatives already exist. Closing.
