### ISSUE TITLE
ENH: 3D Dataframe

### ISSUE THREAD

**Issue by R5dan** [pandas-dev/pandas#60500]
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish I had a 3rd dimension for data

### Feature Description

Create a new class that could handle this. Similar to the existing Dataframe just allowing a third dimension

### Alternative Solutions

Put it into a list or Series like object and require the "coordinate" of the dataframe you want to get

### Additional Context

- `__str__` would return the foremost Dataframe
- `print(x,y,z)` would print like how it currently does, would work like `print(dataframe.get_coord(x,y,z))`
- `to_*` and `from_*` would then allow for the data to be responded in various ways e.g. [{x1:y1, x2:y2} for row in z] etc
- `get_coord(x,y,z)` would return the data at that coordinate with a `None` working as a return that dataframe e.g. `get_coord(1,5,None)` would return the series of x=1 y=5

**Comment by mroeschke** [comment]
Thanks for the suggestion but a third dimension is out of scope for pandas. You may be interested in xarray instead https://docs.xarray.dev/en/stable/

**Comment by R5dan** [comment]
Thought as much, just wanted to check.
