### ISSUE TITLE
BUG: read multi-index column csv with index_col=False borks

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#6051]
http://stackoverflow.com/questions/21318865/read-multi-index-on-the-columns-from-csv-file

**Comment by Licht-T** [comment]
@jreback @gfyoung This seems fixed. We need to close this issue.

**Comment by jreback** [comment]
are there tests covering this case? if not can u put one up

**Comment by Licht-T** [comment]
@jreback Okay. I'll check.

**Comment by Licht-T** [comment]
@jreback Seems that https://github.com/pandas-dev/pandas/pull/17060 fixed this bug. But there is no test for multi-index columns.

**Comment by jreback** [comment]
cc @gfyoung
