### ISSUE TITLE
BUG: Reading Excel File - unsupported operand type(s) for +: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by Pandas-Unimpressed** [pandas-dev/pandas#60578]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
LakehousePath = f'abfss://{Workspace}@onelake.dfs.fabric.microsoft.com/Bronze.Lakehouse/'

if len(SourceFileList) > 0:
    for SourceFile in SourceFileList:
        LakeHouseFilePath = LakehousePath + SourceFile

        PandasDataFrame = pandas.read_excel(LakeHouseFilePath, engine='openpyxl', sheet_name=0, header=None, skiprows=0, usecols='B,C,D', dtype={'B:str','C:np.float32','D:np.float32'}, na_filter=False)
```

### Issue Description

If its a valid excel spreadsheet then it should load - there shouldnt be any need to any fiddling about - at the very least to STR

Just because a CELL has a formula in it that points to a BLANK cell should NOT cause a failure

Just because a CELL has  a DIV/0 Error in it should NOT cause failure

### Expected Behavior

The Excel file loads 

### Installed Versions

Whatever is the latest in Fabric

**Comment by asishm** [comment]
Thanks for the report.

Can you please create a minimal reproducible example? (preferably create the excel file via openpyxl/pandas/xlsxwriter, or if not attach the offending excel file). Please see https://matthewrocklin.com/minimal-bug-reports.html

You're also missing the traceback which can help debug where the issue is coming from. Pandas for the most part, delegates reading excel files to the underlying excel engine (openpyxl in your case).

**Comment by Pandas-Unimpressed** [comment]
Traceback - not sure how I can provide the data - anonymising it isn’t easy - but quite frankly - this error should NEVER occur - if I have asked for STR data types I should get a data frame with STR data types containing the data that resides in each cell - exactly as I would if I saved the spreadsheet to Excel

TypeError Traceback (most recent call last) Cell In[14], line 47 43 LakeHouseFilePath = LakehousePath + SourceFile 45 #PandasDataFrame = pandas.read_excel(LakeHouseFilePath) 46 #PandasDataFrame = pandas.read_excel(LakeHouseFilePath, sheet_name=0, header=None, skiprows=0, usecols='B,C,D', dtype={'B:str','C:float32','D:float32'}) ---> 47 PandasDataFrame = pandas.read_excel(LakeHouseFilePath, engine='openpyxl', sheet_name=0, header=None, skiprows=0, usecols='B,C,D', dtype={'B:str','C:np.float32','D:np.float32'}, na_filter=False) 48 display(PandasDataFrame) 49 bork File ~/cluster-env/trident_env/lib/python3.10/site-packages/pandas/io/excel/_base.py:478, in read_excel(io, sheet_name, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, date_format, thousands, decimal, comment, skipfooter, storage_options, dtype_backend) 476 if not isinstance(io, ExcelFile): 477 should_close = True --> 478 io = ExcelFile(io, storage_options=storage_options, engine=engine) 479 elif engine and engine != io.engine: 480 raise ValueError( 481 "Engine should not be specified when passing " 482 "an ExcelFile - ExcelFile already has the engine set" 483 ) File ~/cluster-env/trident_env/lib/python3.10/site-packages/pandas/io/excel/_base.py:1513, in ExcelFile.__init__(self, path_or_buffer, engine, storage_options) 1510 self.engine = engine 1511 self.storage_options = storage_options -> 1513 self._reader = self._engines[engine](self._io, storage_options=storage_options) File ~/cluster-env/trident_env/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py:549, in OpenpyxlReader.__init__(self, filepath_or_buffer, storage_options) 539 """ 540 Reader using openpyxl engine. 541 (...) 546 {storage_options} 547 """ 548 import_optional_dependency("openpyxl") --> 549 super().__init__(filepath_or_buffer, storage_options=storage_options) File ~/cluster-env/trident_env/lib/python3.10/site-packages/pandas/io/excel/_base.py:540, in BaseExcelReader.__init__(self, filepath_or_buffer, storage_options) 538 self.handles.handle.seek(0) 539 try: --> 540 self.book = self.load_workbook(self.handles.handle) 541 except Exception: 542 self.close() File ~/cluster-env/trident_env/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py:560, in OpenpyxlReader.load_workbook(self, filepath_or_buffer) 557 def load_workbook(self, filepath_or_buffer: FilePath | ReadBuffer[bytes]): 558 from openpyxl import load_workbook --> 560 return load_workbook( 561 filepath_or_buffer, read_only=True, data_only=True, keep_links=False 562 ) File ~/cluster-env/trident_env/lib/python3.10/site-packages/openpyxl/reader/excel.py:344, in load_workbook(filename, read_only, keep_vba, data_only, keep_links, rich_text) 314 def load_workbook(filename, read_only=False, keep_vba=KEEP_VBA, 315 data_only=False, keep_links=True, rich_text=False): 316 """Open the given filename and return the workbook 317 318 :param filename: the path to open or a file-like object (...) 342 343 """ --> 344 reader = ExcelReader(filename, read_only, keep_vba, 345 data_only, keep_links, rich_text) 346 reader.read() 347 return reader.wb File ~/cluster-env/trident_env/lib/python3.10/site-packages/openpyxl/reader/excel.py:123, in ExcelReader.__init__(self, fn, read_only, keep_vba, data_only, keep_links, rich_text) 121 def __init__(self, fn, read_only=False, keep_vba=KEEP_VBA, 122 data_only=False, keep_links=True, rich_text=False): --> 123 self.archive = _validate_archive(fn) 124 self.valid_files = self.archive.namelist() 125 self.read_only = read_only File ~/cluster-env/trident_env/lib/python3.10/site-packages/openpyxl/reader/excel.py:95, in _validate_archive(filename) 88 msg = ('openpyxl does not support %s file format, ' 89 'please check you can open ' 90 'it with Excel first. ' 91 'Supported formats are: %s') % (file_format, 92 ','.join(SUPPORTED_FORMATS)) 93 raise InvalidFileException(msg) ---> 95 archive = ZipFile(filename, 'r') 96 return archive File ~/cluster-env/trident_env/lib/python3.10/zipfile.py:1269, in ZipFile.__init__(self, file, mode, compression, allowZip64, compresslevel, strict_timestamps) 1267 try: 1268 if mode == 'r': -> 1269 self._RealGetContents() 1270 elif mode in ('w', 'x'): 1271 # set the modified flag so central directory gets written 1272 # even if no files are added to the archive 1273 self._didModify = True File ~/cluster-env/trident_env/lib/python3.10/zipfile.py:1332, in ZipFile._RealGetContents(self) 1330 fp = self.fp 1331 try: -> 1332 endrec = _EndRecData(fp) 1333 except OSError: 1334 raise BadZipFile("File is not a zip file") File ~/cluster-env/trident_env/lib/python3.10/zipfile.py:266, in _EndRecData(fpin) 260 """Return data from the "End of Central Directory" record, or None. 261 262 The data is a list of the nine items in the ZIP "End of central dir" 263 record followed by a tenth item, the file seek offset of this record.""" 265 # Determine file size --> 266 fpin.seek(0, 2) 267 filesize = fpin.tell() 269 # Check to see if this is ZIP file with no archive comment (the 270 # "end of central directory" structure should be the last item in the 271 # file if this is the case). File ~/cluster-env/trident_env/lib/python3.10/site-packages/fsspec/spec.py:1743, in AbstractBufferedFile.seek(self, loc, whence) 1741 nloc = self.loc + loc 1742 elif whence == 2: -> 1743 nloc = self.size + loc 1744 else: 1745 raise ValueError(f"invalid whence ({whence}, should be 0, 1 or 2)") TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'



Regards,

Mark Whitehead
Data and Analytics Manager

M 04-2336-2422

J.J. Richards & Sons Pty Ltd t/as JJ’s Waste & Recycling

**Comment by asishm** [comment]
> not sure how I can provide the data - anonymising it isn’t easy 

Are you able to create a hand-crafted excel file with the symptoms you've noticed, that reproduce the issue?

---

Thanks, unfortunately the traceback formatting got lost when replying via email.

However I do see that (formatted using an LLM so I haven't validated every line) openpyxl fails to open the file. As mentioned earlier, pandas relies on the underlying excel library (openpyxl / calamine etc.) to parse the excel files.

Can you try opening loading the file directly via `openpyxl`?

Also it would help if you can pase the output of `pd.show_versions()`. 
> Whatever is the latest in Fabric
Others might, but I don't have easy access to such 3rd party platforms.

```py
   558     from openpyxl import load_workbook
--> 560     return load_workbook(
   561         filepath_or_buffer, read_only=True, data_only=True, keep_links=False
   562     )
```

**Formatted traceback below:**
<details>

```python
TypeError                                 Traceback (most recent call last)
Cell In[14], line 47
    43 LakeHouseFilePath = LakehousePath + SourceFile
    45 #PandasDataFrame = pandas.read_excel(LakeHouseFilePath)
    46 #PandasDataFrame = pandas.read_excel(LakeHouseFilePath, sheet_name=0, header=None, skiprows=0, usecols='B,C,D', dtype={'B:str','C:float32','D:float32'})
---> 47 PandasDataFrame = pandas.read_excel(LakeHouseFilePath, engine='openpyxl', sheet_name=0, header=None, skiprows=0, usecols='B,C,D', dtype={'B:str','C:np.float32','D:np.float32'}, na_filter=False)
    48 display(PandasDataFrame)
    49 bork

File ~/cluster-env/trident_env/lib/python3.10/site-packages/pandas/io/excel/_base.py:478, in read_excel(io, sheet_name, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, date_format, thousands, decimal, comment, skipfooter, storage_options, dtype_backend)
   476 if not isinstance(io, ExcelFile):
   477     should_close = True
--> 478     io = ExcelFile(io, storage_options=storage_options, engine=engine)
   479 elif engine and engine != io.engine:
   480     raise ValueError(
   481         "Engine should not be specified when passing "
   482         "an ExcelFile - ExcelFile already has the engine set"
   483     )

File ~/cluster-env/trident_env/lib/python3.10/site-packages/pandas/io/excel/_base.py:1513, in ExcelFile.__init__(self, path_or_buffer, engine, storage_options)
   1510 self.engine = engine
   1511 self.storage_options = storage_options
--> 1513 self._reader = self._engines[engine](self._io, storage_options=storage_options)

File ~/cluster-env/trident_env/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py:549, in OpenpyxlReader.__init__(self, filepath_or_buffer, storage_options)
   539 """
   540 Reader using openpyxl engine.
   541 
   542 Parameters
   543 ----------
   544 filepath_or_buffer: string, path object or Workbook
   545     Object to be parsed.
   546 {storage_options}
   547 """
   548 import_optional_dependency("openpyxl")
--> 549 super().__init__(filepath_or_buffer, storage_options=storage_options)

File ~/cluster-env/trident_env/lib/python3.10/site-packages/pandas/io/excel/_base.py:540, in BaseExcelReader.__init__(self, filepath_or_buffer, storage_options)
   538 self.handles.handle.seek(0)
   539 try:
--> 540     self.book = self.load_workbook(self.handles.handle)
   541 except Exception:
   542     self.close()

File ~/cluster-env/trident_env/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py:560, in OpenpyxlReader.load_workbook(self, filepath_or_buffer)
   557 def load_workbook(self, filepath_or_buffer: FilePath | ReadBuffer[bytes]):
   558     from openpyxl import load_workbook
--> 560     return load_workbook(
   561         filepath_or_buffer, read_only=True, data_only=True, keep_links=False
   562     )

File ~/cluster-env/trident_env/lib/python3.10/site-packages/openpyxl/reader/excel.py:344, in load_workbook(filename, read_only, keep_vba, data_only, keep_links, rich_text)
   314 def load_workbook(filename, read_only=False, keep_vba=KEEP_VBA,
   315                   data_only=False, keep_links=True, rich_text=False):
   316     """Open the given filename and return the workbook
   317     
   318     :param filename: the path to open or a file-like object
   319     :type filename: string
   320     
   321     :param read_only: optimised for reading, content cannot be edited
   322     :type read_only: bool
   323     
   324     :param keep_vba: preseve vba content (this does NOT mean you can use it)
   325     :type keep_vba: bool
   326     
   327     :param data_only: controls whether cells with formulae have either the
   328     formula (default) or the value stored the last time Excel read the sheet
   329     :type data_only: bool
   330     
   331     :param keep_links: whether links to external workbooks should be preserved.
   332     The default is True
   333     :type keep_links: bool
   334     
   335     :param rich_text: if True, return cells with rich text as strings
   336     :type rich_text: bool
   337     
   338     :rtype: :class:`openpyxl.workbook.Workbook`
   339     
   340     .. note::
   341     
   342     When using this function to read an xlsx generated by another application
   343     """
--> 344     reader = ExcelReader(filename, read_only, keep_vba,
   345                         data_only, keep_links, rich_text)
   346     reader.read()
   347     return reader.wb

File ~/cluster-env/trident_env/lib/python3.10/site-packages/openpyxl/reader/excel.py:123, in ExcelReader.__init__(self, fn, read_only, keep_vba, data_only, keep_links, rich_text)
   121 def __init__(self, fn, read_only=False, keep_vba=KEEP_VBA,
   122              data_only=False, keep_links=True, rich_text=False):
--> 123     self.archive = _validate_archive(fn)
   124     self.valid_files = self.archive.namelist()
   125     self.read_only = read_only

File ~/cluster-env/trident_env/lib/python3.10/site-packages/openpyxl/reader/excel.py:95, in _validate_archive(filename)
    88 msg = ('openpyxl does not support %s file format, '
    89        'please check you can open '
    90        'it with Excel first. '
    91        'Supported formats are: %s') % (file_format,
    92                                        ','.join(SUPPORTED_FORMATS))
    93 raise InvalidFileException(msg)
---> 95 archive = ZipFile(filename, 'r')
    96 return archive

File ~/cluster-env/trident_env/lib/python3.10/zipfile.py:1269, in ZipFile.__init__(self, file, mode, compression, allowZip64, compresslevel, strict_timestamps)
   1267 try:
   1268     if mode == 'r':
-> 1269         self._RealGetContents()
   1270     elif mode in ('w', 'x'):
   1271         # set the modified flag so central directory gets written
   1272         # even if no files are added to the archive
   1273         self._didModify = True

File ~/cluster-env/trident_env/lib/python3.10/zipfile.py:1332, in ZipFile._RealGetContents(self)
   1330 fp = self.fp
   1331 try:
-> 1332     endrec = _EndRecData(fp)
   1333 except OSError:
   1334     raise BadZipFile("File is not a zip file")

File ~/cluster-env/trident_env/lib/python3.10/zipfile.py:266, in _EndRecData(fpin)
   260 """Return data from the "End of Central Directory" record, or None.
   261 
   262 The data is a list of the nine items in the ZIP "End of central dir"
   263 record followed by a tenth item, the file seek offset of this record."""
   265 # Determine file size
--> 266 fpin.seek(0, 2)
   267 filesize = fpin.tell()
   269 # Check to see if this is ZIP file with no archive comment (the
   270 # "end of central directory" structure should be the last item in the
   271 # file if this is the case).

File ~/cluster-env/trident_env/lib/python3.10/site-packages/fsspec/spec.py:1743, in AbstractBufferedFile.seek(self, loc, whence)
   1741     nloc = self.loc + loc
   1742 elif whence == 2:
-> 1743     nloc = self.size + loc
   1744 else:
   1745     raise ValueError(f"invalid whence ({whence}, should be 0, 1 or 2)")

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

</details>

**Comment by Pandas-Unimpressed** [comment]
Hi there

I have tried to create a file - but it loads - so I am not 100% sure what the issue is

The file is created out of Tech One Finance One via a Report - I will have to get the users to manually save as a CSV for now

Thanks for you assistance - but unless I can recreate the issue for you you will be chasing your tail - I am happy for this to be parked for now

Regards,

Mark Whitehead
Data and Analytics Manager

M 04-2336-2422

J.J. Richards & Sons Pty Ltd t/as JJ’s Waste & Recycling

**Comment by rhshadrach** [comment]
dtype={'B:str','C:np.float32','D:np.float32'}

I think you're meaning to be passing a dictionary here? Currently you're passing a set of strings.

**Comment by Pandas-Unimpressed** [comment]
OH - thank you- the documentation on the web is abysmal

Regards,

Mark Whitehead
Data and Analytics Manager

M 04-2336-2422

J.J. Richards & Sons Pty Ltd t/as JJ’s Waste & Recycling
