### ISSUE TITLE
BUG: when I assign value of 1-dim np.array holding single instance, it results in 0-dim array instance

### ISSUE THREAD

**Issue by kcerniauskas3** [pandas-dev/pandas#60580]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
arr = np.array(['one'], dtype="object")
df = pd.DataFrame({'col1': [None]}, index=[100])
df.at[100, 'col1'] = arr
```

### Issue Description

when I assign value of 1-dim np.array holding single instance, it results in 0-dim array instance:

>>> df.at[100, 'col1']
array('one', dtype=object)

### Expected Behavior

>>> df.at[100, 'col1']
array(['one'], dtype=object)

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 0691c5cf90477d3503834d983f69350f250a6ff7
python                : 3.12.7
python-bits           : 64
OS                    : Windows
OS-release            : 11
Version               : 10.0.26100
machine               : AMD64
processor             : AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : English_United States.1252

pandas                : 2.2.3
numpy                 : 2.2.0
pytz                  : 2024.2
dateutil              : 2.9.0.post0
pip                   : 24.3.1
Cython                : None
sphinx                : None
IPython               : 8.28.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
blosc                 : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.6.1
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : 3.1.4
lxml.etree            : 5.3.0
matplotlib            : 3.9.2
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : 17.0.0
pyreadstat            : None
pytest                : 8.3.3
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.14.1
sqlalchemy            : None
tables                : None
tabulate              : 0.9.0
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2024.2
qtpy                  : None
pyqt5                 : None

</details>

**Comment by QuentinFuxa** [comment]
The single-element array is being “unboxed” by pandas when assigned to a single cell. This is a known quirk rather than a newly-introduced bug I think : Pandas stores single-element object arrays as scalar objects internally

If preserving the shape is critical, you may need to store arrays-of-arrays (e.g. 2D arrays or lists containing your 1D arrays) or assign these arrays in a way that the entire column ends up typed as “object of array.”

**Comment by kcerniauskas3** [comment]
Thanks.
I ended up converting to list, saving in .parquet, and reloading dataset. Parquet saves list as np.array, and loads back correctly in 1-dim.
Although df.at[100, 'col1'] = [arr] worked for this case, it did not work for arrays with more than 1 element. Also, assigning entire column should have worked, but my case was update by index.

**Comment by kcerniauskas3** [comment]
Seems to be a known quirk.
