### ISSUE TITLE
BUG: OutOfBoundsDatetime for large future dates like 9990-12-31

### ISSUE THREAD

**Issue by maneranjit4** [pandas-dev/pandas#60587]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame({
    'account-start': ['2017-02-03', '2017-03-03', "9990-12-31"],
    'client': ['Alice Anders', 'Bob Baker', 'Charlie Chaplin'],
    'balance': [-1432.32, 10.43, 30000.00],
    'rank': [52, 525, 32],
})
df["account-start"] = pd.to_datetime(df["account-start"], format="%Y-%m-%d")
```

### Issue Description

Getting an error as OutOfBoundsDatetime

### Expected Behavior

it should parse the date and covert the '9990-12-31' to datetime dtype

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.9.13.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.22631
machine               : AMD64
processor             : Intel64 Family 6 Model 154 Stepping 4, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : English_United States.1252

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : 58.1.0
pip                   : 24.3.1
Cython                : None
pytest                : 8.2.2
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 5.2.2
html5lib              : 1.1
pymysql               : None
psycopg2              : None
jinja2                : 3.1.4
IPython               : 8.18.1
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.5.0
gcsfs                 : None
matplotlib            : 3.9.0
numba                 : 0.60.0
numexpr               : 2.10.1
odfpy                 : None
openpyxl              : 3.1.5
pandas_gbq            : None
pyarrow               : 16.1.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.13.1
sqlalchemy            : 2.0.31
tables                : None
tabulate              : 0.9.0
xarray                : 2024.6.0
xlrd                  : None
zstandard             : 0.22.0
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>

**Comment by sai-srinivasan-v** [comment]
Hi, I have manually tested the main branch and this issue does not occur.

**Comment by snitish** [comment]
Agree with @sai-srinivasan-v. This bug is present in 2.2.3 but not in main anymore.

**Comment by MarcoGorelli** [comment]
yup - this is part of an intentional change that's being tested for, so I think it's OK to close this- thanks for the report!
