### ISSUE TITLE
BUG: Single Index of Tuples as Output on Tuple Groupings

### ISSUE THREAD

**Issue by RahimD** [pandas-dev/pandas#60604]
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
df = pandas.DataFrame({"A" : [1,2,3,1,2,3], "B": [4,5,6,4,5,6], "C" : [7,8,9,7,8,9]})
df = df.set_index(['A', 'B'])
df.groupby(lambda x : (x[0], x[1])).aggregate('sum')
```

### Issue Description

This issue appears to be similar to #24786 except that here a lambda is used to create the tuples. The [User Guide for Pandas](https://pandas.pydata.org/docs/user_guide/groupby.html) states that 
> The result of the aggregation will have the group names as the new index. In the case of multiple keys, the result is a MultiIndex by default.

Thus I was expecting the tuples to be automatically combined to form a ```MultiIndex``` as opposed to an ```Index``` with tuples as indices. Internally, the ```Index.map()``` [call](https://github.com/pandas-dev/pandas/blob/8a5344742c5165b2595f7ccca9e17d5eff7f7886/pandas/core/groupby/grouper.py#L511) converts the produced list of tuples to a ```MultiIndex```, but when it [produces the aggregation index](https://github.com/pandas-dev/pandas/blob/8a5344742c5165b2595f7ccca9e17d5eff7f7886/pandas/core/groupby/ops.py#L753), it appears to produce a single ``Index``` instead.

I wasn't sure if this was intended behaviour, or a bug; I apologize if it is the former!

### Expected Behavior

```python
df = pandas.DataFrame({"A" : [1,2,3,1,2,3], "B": [4,5,6,4,5,6], "C" : [7,8,9,7,8,9]})
df = df.set_index(['A', 'B'])
df.groupby(['A', 'B']).aggregate('sum')
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 0691c5cf90477d3503834d983f69350f250a6ff7
python                : 3.13.1
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.18363
machine               : AMD64
processor             : AMD64 Family 21 Model 96 Stepping 1, AuthenticAMD
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : English_Canada.1252

pandas                : 2.2.3
numpy                 : 2.2.1
pytz                  : 2024.2
dateutil              : 2.9.0.post0
pip                   : 24.3.1
Cython                : None
sphinx                : None
IPython               : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
blosc                 : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : None
lxml.etree            : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : None
pyreadstat            : None
pytest                : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2024.2
qtpy                  : None
pyqt5                 : None</details>

**Comment by rhshadrach** [comment]
Thanks for the report. If you want to have multiple keys, you need to supply a list to groupby.

    df.groupby([lambda x : x[0], lambda x: x[1]]).aggregate('sum')

This gives the expected MultiIndex. I believe this resolves your issue. If not, comment here as to why and we can reopen.
