### ISSUE TITLE
Missing ellipsis cells in pivot_table.to_html when limited by max_cols and len(rows) > 1

### ISSUE THREAD

**Issue by BertrandBordage** [pandas-dev/pandas#6131]
``` python
import pandas
df = pandas.DataFrame([
    {'a': 'aa', 'b': 'ba', 'c': 'ca', 'd': 1},
    {'a': 'ab', 'b': 'bb', 'c': 'cc', 'd': 2},
    {'a': 'ac', 'b': 'bc', 'c': 'cc', 'd': 3}
])

df.pivot_table(cols=['a'], rows=['b', 'c']).to_html(max_cols=2)
```

This renders like this:
![broken_output](https://f.cloud.github.com/assets/1119169/2011357/c4149c0e-8779-11e3-952d-05499dd1e2e1.png)

while this:

``` python
df.pivot_table(cols=['a'], rows=['b']).to_html(max_cols=2)
```

renders like this:
![slection_656](https://f.cloud.github.com/assets/1119169/2011374/f7d9935a-8779-11e3-99c2-ddffa6537456.png)

As you can see in the first table, there are no ellipsis cells like in the second one.
I inspected the code to find the reason for this bug but couldn't find…

**Comment by mroeschke** [comment]
If you're up for contributing a test @simonjayhawkins to confirm this behavior, it would be much appreciated!

**Comment by mroeschke** [comment]
Sure thing; you can open a new issue. Please use code snippets and not pictures of code as it's harder to reproduce.

**Comment by simonjayhawkins** [comment]
Opened #22579 for the column misalignment.

**Comment by simonjayhawkins** [comment]
@mroeschke  currently in `pandas\tests\io\formats\test_to_html.py` there is a test:

```python
    def test_to_html_truncate_multi_index(self):
        pytest.skip("unreliable on travis")
        arrays = [['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
                  ['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two']]
        df = DataFrame(index=arrays, columns=arrays)
        fmt.set_option('display.max_rows', 7)
        fmt.set_option('display.max_columns', 7)
        result = df._repr_html_()
        expected = '''\
...
```

which tests that:

![image](https://user-images.githubusercontent.com/13159005/45027622-d3553000-b039-11e8-9a78-192ce39d1dd3.png)

produces:

![image](https://user-images.githubusercontent.com/13159005/45027649-e831c380-b039-11e8-907d-85754e1189b2.png)

which I think covers this issue. so i'm thinking that adding another test is not necessary?

**Comment by mroeschke** [comment]
Although these tests look similar, it would still be good to confirm that the `to_html` pathway is tested. The test uses a private method `_repr_html_` which users should not normally be accessing.
