### ISSUE TITLE
ENH: Add a pep8-radius script

### ISSUE THREAD

**Issue by y-p** [pandas-dev/pandas#6248]
We've been stuck on how to handle PEP8 cleanups for a while.
On the one hand PEP8 storms break PRs and git blame, OTOH
the back and forth on code review about whitespace fixes drives some
maintainers (me) crazy.

But:
- Autopep8 accepts a line-range argument which tells it to only fix problems in a given area.
- git diff tells you which lines on which file were altered between two points in history.

So:
- write a script "pep8-radius.py" that takes a commit hash `h` as input, find altered lines
  between HEAD and `h` and then invokes autopep8 on a given radius around those
  altered lines to locally cleanup where things changed.
- Do one last pep8 storm.
- Get contributors to run the script and include/squash the cleanups in the PR.

This is a fun little hack which might become quite handy outside pandas.
would appreciate someone picking this idea up and making it happen as I'm 
a little burned out on this sort of work.

**Comment by jorisvandenbossche** [comment]
PEP8 is in the meantime checked for during CI testing for all lines, so closing this
