### ISSUE TITLE
Improve testing coverage

### ISSUE THREAD

**Issue by y-p** [pandas-dev/pandas#6251]
Pandas coverage is currently at 78%, not bad but could be better.
Open issue for first-time contributors: find some ill-tested corner
and bring it into the light.

**Comment by jreback** [comment]
should be pretty straightforward to add this as @jorisvandenbossche PR almost there.

any takers?

I can turn on the github service so we get notifications of this.

**Comment by gliptak** [comment]
@jreback Was coveralls enabled? I see ```codecov``` but not ```coveralls``` in ```.travis.yml```

There also doesn't seem to be https://coveralls.io/github/pydata/pandas?branch=master

**Comment by jreback** [comment]
no why would we need more than one?

**Comment by gliptak** [comment]
They offer a bit different organization of the same coverage data, so we do not need to have both ...

**Comment by mroeschke** [comment]
We have coverage tools installed and coverage it up to 91%. Respectable progress for now; closing.
