### ISSUE TITLE
date_range should take timedelta as freq

### ISSUE THREAD

**Issue by hayd** [pandas-dev/pandas#6307]
http://stackoverflow.com/questions/21643407/define-a-pandas-tseries-index-datetimeindex-using-2-datetimes-dt-start-and-dt-s/21651263#21651263

**Comment by jbrockmendel** [comment]
This works in 0.21.1

```
>>> td = pd.Timedelta(days=3, hours=4)
pd.date_range('2016-01-01', periods=4, freq=td)
DatetimeIndex(['2016-01-01 00:00:00', '2016-01-04 04:00:00',
               '2016-01-07 08:00:00', '2016-01-10 12:00:00'],
              dtype='datetime64[ns]', freq='76H')
```

This can probably be closed.

**Comment by jreback** [comment]
yes this is well tested

@jschendel did a PR. awhile back on this iirc
