### ISSUE TITLE
BUG: reset_index with NaN in MultiIndex

### ISSUE THREAD

**Issue by wangshun98** [pandas-dev/pandas#6322]
This is related to the following commit.
https://github.com/jreback/pandas/commit/625ee94a31e4011b677785f12dfd204591cadfcf

When one level in the MultiIndex is all NaN, line 2819 in DataFrame.reset_index() and subfunction _maybe_cast, will have a problem, because values is empty.
2819:    values = values.take(labels)
IndexError: cannot do a non-empty take from an empty axes

A possible fix is to add the following lines before 2819:
                if mask.all():
                    values = labels \* np.nan
                    return values

**Comment by gryBox** [comment]
The code below returns the error: `IndexError: cannot do a non-empty take from an empty axes.`

```
import pandas as pd
import numpy as np
import random
import string



# Create 12 random strings 3 char long 
rndm_strgs = [''.join(random.SystemRandom().choice(string.ascii_uppercase + string.digits) for _ in range(3)) for i in range(12)]            
rndm_strgs[0] = None
rndm_strgs[5] = None

# Make Dataframe
df = pd.DataFrame({'A' : list('pandasisgood'),
                   'B' : np.nan,
                   'C' : rndm_strgs,
                   'D' : np.random.rand(12)})

# Set an Index -> Columns have Nans
df_w_idx = df.set_index(['A','B','C'])

# This is where it fails
df_w_idx.reset_index()
```

This is the desired result:

```
for clmNm in df_w_idx.index.names:
    print(clmNm)

    print(clmNm)

    df_w_idx[clmNm] = df_w_idx.index.get_level_values(clmNm)

    
df_w_idx = df_w_idx.reset_index(drop=True).copy()
df_w_idx

**Comment by tzinckgraf** [comment]
@jreback I have the same issue and was playing around with a solution.

The `reset_index` function in `frame.py` function has the following code
```
            # if we have the labels, extract the values with a mask
            if labels is not None:
                mask = labels == -1
                values = values.take(labels)
```
see [here](https://github.com/pandas-dev/pandas/blob/5710947759e13f54a5bf896768fb7f9c214f245d/pandas/core/frame.py#L2938).

The mask variable is all `True` only if all the labels are -1. Assuming this means all the values were `np.nan`, one solution I was playing with is as follows
```
            # if we have the labels, extract the values with a mask
            if labels is not None:
                mask = labels == -1
                if mask.all():
                    values = (np.nan * mask).values()
                else:
                    values = values.take(labels)
```

Please advise. More than happy to create a pull request and create all appropriate test cases.

**Comment by jreback** [comment]
@tzinckgraf you can just do the take if ``len(values)``; ``.take()`` is picky :>

sure why don't you put up a PR with a test (you can use the above example).
