### ISSUE TITLE
Slicing on Multi Index Performs Oddly With Duplicates

### ISSUE THREAD

**Issue by cancan101** [pandas-dev/pandas#6334]
Using:

```
from cStringIO import StringIO
df1 = pd.read_csv(StringIO("""s,date,v\nQ,2013-11-21 00:00:00,1\nQ,2013-11-22 00:00:00,2\nQ,2013-11-22 00:00:00,3"""),
            index_col=[0,1])
df2 = pd.read_csv(StringIO("""s,date,v\nQ,2013-11-21 00:00:00,1\nQ,2013-11-22 00:00:00,2\nQ,2013-11-23 00:00:00,3"""),
            index_col=[0,1])
```

Observer how slicing performs very different and non intuitively in these cases:

```
In [4]: df1.ix[["Q"]]
Out[4]:
    v
Q NaN

[1 rows x 1 columns]

In [5]: df2.ix[["Q"]]
Out[5]:
                       v
s date
Q 2013-11-21 00:00:00  1
  2013-11-22 00:00:00  2
  2013-11-23 00:00:00  3

[3 rows x 1 columns]
```

I feel that a warning like this: http://pandas.pydata.org/pandas-docs/stable/indexing.html?highlight=sort#the-need-for-sortedness-with-multiindex should happen when there are duplicates in the index.

**Comment by mroeschke** [comment]
This looks fixed although `ix` might be on its way out the door. Could use an additional test.

**Comment by simonjayhawkins** [comment]
@mroeschke Are you happy if this gets closed?

**Comment by mroeschke** [comment]
Fine by me since `ix` is deprecated.
