### ISSUE TITLE
ENH: merge multi-index with a multi-index

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#6360]
#3662 is about merging a single-level index with a mi

This is is about a multi-multi merge

```
# example described there:
In [11]: df = pd.DataFrame(np.random.randn(10,5))
    ...: df1 = df[range(0, 3)].set_index([0, 2])
    ...: df2 = df[range(2, 5)].set_index([2, 4])
    ...: res = df1.join(df2, how='inner')  # empty. Do I need to specify something here?
    ...: exp = pd.DataFrame({1: df[1], 3: df[3]})
    ...: exp.index = df[2]
```

**Comment by gandhis1** [comment]
Question on this for anyone involved with this? As I understand it, as of 0.19.0, this still hasn't made it in, and one still has to do the manually steps of `reset_index()`, `pd.merge` on specific columns, and then `set_index()`. Is that correct?
