### ISSUE TITLE
Allow multibyte separator / delimiter in read_csv() & read_table()

### ISSUE THREAD

**Issue by dlcmh** [pandas-dev/pandas#6369]
Assume we have a file `test.txt` which uses `§` (double-S) as a separator and has a header row in the first line followed by 1 line of data:

```
Name§Age
Jane Jones§33
```

Using pandas to read the file...

```
import pandas as pd
records = pd.read_table('test.txt', sep='§')
```

... the following is displayed:

```
OverflowError: value too large to convert to char.
```

I'd like to make a request for pandas to be able to handle such delimiters.

Thank you.

**Comment by smcinerney** [comment]
Confirm this works in 3.10:

`records = pd.read_table('test.txt', sep='§', engine='python')`
