### ISSUE TITLE
BUG: to_datetime ignores utc=True when arg is Series 

### ISSUE THREAD

**Issue by michaelaye** [pandas-dev/pandas#6415]
Is this a bug or a feature that I don't understand:

``` python
data = ['20100102 121314', '20100102 121315']
print (pd.to_datetime(data, format='%Y%m%d %H%M%S', 
                      utc=True)[0]).__repr__()
print (pd.to_datetime(pd.Series(data), format='%Y%m%d %H%M%S', 
                      utc=True)[0]).__repr__()
print (pd.to_datetime(pd.TimeSeries(data), format='%Y%m%d %H%M%S', 
                     utc=True)[0]).__repr__()
```

results in

``` bash
Timestamp('2010-01-02 12:13:14+0000', tz='UTC')
Timestamp('2010-01-02 12:13:14', tz=None)
Timestamp('2010-01-02 12:13:14', tz=None)
```

Using version '0.13.1'

---

Other example in https://github.com/pandas-dev/pandas/issues/15760

**Comment by tacaswell** [comment]
bump on this, just caused me a whole bunch of trouble :disappointed:

**Comment by jorisvandenbossche** [comment]
In any case, what I said above:

> This is not a feature, but a limitation of the current implementation. The difference is that in the first case the result is a DatetimeIndex and in the second and third case the result is a Series with a column with datetime64 values. 

is no longer the case. Series now supports tz aware data, so there is no reason to ignore `utc=True` when the input/output is a Series.
