### ISSUE TITLE
in read_csv, warn_bad_lines and error_bad_lines have misleading names

### ISSUE THREAD

**Issue by rcompton** [pandas-dev/pandas#6478]
read_csv will still fail if *_bad_lines=False. *_bad_lines only applies when the number of delimiters is wrong. This is misleading, a line with a poorly formatted date is what I would think of as a "bad_line" that should be ignored  (cf https://stackoverflow.com/questions/22026181 )

**Comment by jorisvandenbossche** [comment]
Not sure there is an enhancement here. Renaming the `*_bad_lines` is best done in a reworked API to better deal with such "bad lines", see eg https://github.com/pandas-dev/pandas/issues/9549#issuecomment-76498787
