### ISSUE TITLE
Speed up for groupby filter for special case of len(x) < n  ?

### ISSUE THREAD

**Issue by hayd** [pandas-dev/pandas#6556]
@dsm054 posted ridiculous fast version for this, perhaps we can wrap it in an API with filter?

http://stackoverflow.com/questions/22208562/replace-rarely-occurring-values-in-a-pandas-dataframe#comment33717682_22208838

cc @danielballan

**Comment by mroeschke** [comment]
The indexing shortcut is no longer valid as indexing as changed. Closing
