### ISSUE TITLE
Plot issue, timeseries always honored,

### ISSUE THREAD

**Issue by arippbbc** [pandas-dev/pandas#6586]
When work with tick data, and the density of data is not time evenly distributed. When I use dataframe plot function, the default plot always honor by time, not by the number of data points. I have to convert the datetimeindex back to string, and plot correspondingly, isn't it handy to make an extra flag to plot with number of data evenly spaced and still locate the right time label on x axis? For example
the 3rd and 4th graph in this link which plot with the same data

http://stackoverflow.com/questions/22258162/python-pandas-plot-with-uneven-timeseries-index-with-count-evenly-distributed

**Comment by jorisvandenbossche** [comment]
Closing as out of scope for pandas, I think the stackoverflow accepted answer provides a good workaround.
