### ISSUE TITLE
PERF: Cython or C implementation for reading fixed-width files (read_fwf)

### ISSUE THREAD

**Issue by stevenmanton** [pandas-dev/pandas#6706]
As I understand it, read_csv and read_table both use the C parser, but read_fwf uses a pure Python parser. As such, the latter is significantly slower and there doesn't seem to be any workaround. Is there any plan to add an optimized fwf reader?

See: https://groups.google.com/forum/#!topic/pystatsmodels/0DVBmCsDrVI

**Comment by mroeschke** [comment]
Looks like this never got traction so closing. Can reopen if there's more interest
