### ISSUE TITLE
read_table fails with MultiIndex input and delim_whitespace=True

### ISSUE THREAD

**Issue by mcwitt** [pandas-dev/pandas#6893]
Related #6889

Example:

``` python
In [4]: text = """                      A       B       C       D        E
one two three   four
a   b   10.0032 5    -0.5109 -2.3358 -0.4645  0.05076  0.3640
a   q   20      4     0.4473  1.4152  0.2834  1.00661  0.1744
x   q   30      3    -0.6662 -0.5243 -0.3580  0.89145  2.5838"""

In [5]: pd.read_table(StringIO(text), delim_whitespace=True)
---------------------------------------------------------------------------
CParserError                              Traceback (most recent call last)
. . .
CParserError: Error tokenizing data. C error: Expected 6 fields in line 3, saw 9
```

This (partially) works if `delim_whitespace=True` is replaced with `sep='\s+', engine='python'` (although columns A-D are lost):

``` python
In [6]: pd.read_table(StringIO(text), sep='\s+', engine='python')
Out[6]: 
                           E
one two three   four        
a   b   10.0032 5     0.3640
    q   20.0000 4     0.1744
x   q   30.0000 3     2.5838

[3 rows x 1 columns]
```

**Comment by rmsilva1973** [comment]
Hey @jreback . Just received this bug for triage. It's still a reproducible issue as of '1.1.0.dev0+1247.g9c317322f'

**Comment by jreback** [comment]
and it’s an open issue if you want to submit a PR

**Comment by rmsilva1973** [comment]
So, I've been the last 4 days trying to figure out how this tokenizer function works. I've initially narrowed down the test case to a simples one:

**import pandas as pd
from io import StringIO
text = """ A
one
c   -13"""
pd.read_table(StringIO(text),delim_whitespace=True)**

@jreback  it doesn't seem related to MultiIndex specifically. Any ammount of indexes included on the data (is it called "implicit indexes"?) hits the bug. Do you think it's reasonable to change the bug title to something more appropriate?

When we call **tokenizer.c:tokenize_nrows(self, parser, nrows)** with nrows greater than 2 (i.e. at the parsing actual data - not header - phase) the tokenizer barfs. Trying to debug the inner workings of **tokenizer.c::tokenize_bytes** I've traced something odd on the **switch(self->state)** statement which I simply cannot get past. Adding some traces, I've found out the state changes in the following order when parsing the first character: _WHITESPACE_LINE->EAT_WHITSPACE->START-RECORD->START-FIELD_ however I simply cannot understand how on the function logic can the state transition from WHITESPACE-LINE to EAT-WHITESPACE. Here's the trace snippet:

__tokenize_helper: Asked to tokenize 3 rows, datapos=0, datalen=0
Estado inicial: 0
tokenize_bytes - Iter: 0 Char: 0x20 Line 1 field_count 0, state 0
START_RECORD
tokenize_bytes - Iter: 1 Char: 0x41 Line 1 field_count 0, state 12
WHITESPACE_LINE
FALLTHROUGH
EAT_WHITESPACE
START_RECORD
START_FIELD
PUSH_CHAR: Pushing A, slen= 0, stream_cap=64, stream_len=0_

And here's the case WHITESPACE_LINE statement:

![image](https://user-images.githubusercontent.com/28487379/80202309-cbc21080-85fb-11ea-813e-d40d9381c872.png)

(yes... I've been suffering from some old age related eye fatigue lately.. lol...)

The state isn't changed at all on this case clause.

Anyone has a clue on this?

**Comment by mroeschke** [comment]
`delim_whitespace` is deprecated and will be removed in pandas 3.0 so closing as wont fix
