### ISSUE TITLE
ENH: Aggregate to data with error range

### ISSUE THREAD

**Issue by toddrjen** [pandas-dev/pandas#6898]
As mentioned in issue #6897, working with data with error ranges is pretty much universal in science, as well as many other fields.  There are python packages, like `uncertainties`, for working with this sort of data.  However, pandas has no built-in tools for creating or working with data with error ranges, leaving users to create their own columns or a separate pandas object to hold error ranges (see, e.g. #5638) or manually creating and using `uncertainties` objects.

I think it would be very helpful if there was an aggregate method that would aggregate data to data with an error range (such as an `uncertanties` array).  By default, it could use `mean` to get the center values and and `sem` (standard error of the mean) or `std` to get the error ranges, but it would probably be good for users to be able to specify their own functions for calculating the center values and/or the error ranges.

**Comment by mroeschke** [comment]
Yeah this would be best implemented by a 3rd party library using uncertainties as an EA data dtype. Closing
