### ISSUE TITLE
DOC: provide more inline examples for cookbook.rst

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#6918]
In-line examples when not too long are nice (as well as the link)

for example: https://github.com/pydata/pandas/commit/6fe9539b1c9c5f097d64d72af2c2f26e85dfc0b1

**Comment by mroeschke** [comment]
https://pandas.pydata.org/pandas-docs/stable/user_guide/cookbook.html has a lot of examples now. Can reopen if we want to add specific examples
