### ISSUE TITLE
Series/DataFrame.rank() doesn't handle np.inf properly

### ISSUE THREAD

**Issue by nspies** [pandas-dev/pandas#6945]
The `rank()` function converts `np.nan` to `np.inf` or `-np.inf`, and therefore can't properly rank existing `np.inf`. See here: https://github.com/pydata/pandas/pull/6886#issuecomment-40773964.

Test for this issue here: https://github.com/pydata/pandas/blob/master/pandas/tests/test_series.py#L4071

**Comment by peterpanmj** [comment]
I'm using pandas '0.20.1'. Ranking series with np.inf still yields np.nan. Will this be fixed ?
```
s= pd.Series(data = np.array([1,2,3,math.inf,4,4,4,5,5]))
s.rank(method="average")
```
```
0    1.0
1    2.0
2    3.0
3    NaN
4    5.0
5    5.0
6    5.0
7    7.5
8    7.5
dtype: float64
```

**Comment by jreback** [comment]
@peterpanmj pull request for this are welcome, its pretty straightforward to fix.
