### ISSUE TITLE
BUG: concat on axis with both different and duplicate labels raising error

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#6963]
When concatting two dataframes where there are a) there are duplicate columns in one of the dataframes, and b) there are non-overlapping column names in both, then you get a IndexError:

```
In [9]: df1 = pd.DataFrame(np.random.randn(3,3), columns=['A', 'A', 'B1'])
   ...: df2 = pd.DataFrame(np.random.randn(3,3), columns=['A', 'A', 'B2'])

In [10]: pd.concat([df1, df2])

Traceback (most recent call last):
  File "<ipython-input-10-f61a1ab4009e>", line 1, in <module>
    pd.concat([df1, df2])
...
  File "c:\users\vdbosscj\scipy\pandas-joris\pandas\core\index.py", line 765, in take
    taken = self.view(np.ndarray).take(indexer)
IndexError: index 3 is out of bounds for axis 0 with size 3
```

I don't know if it should work (although I suppose it should, as with only the duplicate columns it does work), but at least the error message is not really helpfull.

**Comment by jorisvandenbossche** [comment]
Some more example from #17552 (with `axis=1`, different error messages, but the idea is the same: you only get the error when there are duplicate + different labels):

```
In [113]: df1 = pd.DataFrame(np.zeros((2,2)), index=[0, 1], columns=['a', 'b'])
     ...: df2 = pd.DataFrame(np.ones((2,2)), index=[2, 2], columns=['c', 'd'])

In [114]: pd.concat([df1, df2], axis=1)
...
ValueError: Shape of passed values is (4, 6), indices imply (4, 4)

In [115]: df1 = pd.DataFrame(np.zeros((2,2)), index=[0, 1], columns=['a', 'b'])
     ...: df2 = pd.DataFrame(np.ones((2,2)), index=pd.DatetimeIndex([2, 2]), columns=['c', 'd'])

In [116]: pd.concat([df1, df2], axis=1)
...
TypeError: 'NoneType' object is not iterable
```

**Comment by xuancong84** [comment]
In general, for maximum usage compatibility, we should treat a table as a symmetric rank-2 tensor, (except for axis labels, e.g., 1st direction called 'column', 2nd direction called 'row'). And thus, no matter whether there are duplicate row indices or duplicate column names or both, we should always be able to perform concatenation along either axis without throwing any errors.

Below is a very elegant design that can grant maximum compatibility, suppose there are duplicate names in both row indices and column names:
<img width="772" alt="image" src="https://user-images.githubusercontent.com/10172392/72241299-697f6a00-3621-11ea-930d-08eb8678af1e.png">
1. For concatenation along axis 0, (`pd.concat([df1, df2], axis=0)`, i.e., vertical concatenation of rows), the first 2 columns named 'A' should align to each other, leaving empty values (or NaN) for the 3rd column named 'A'
<img width="892" alt="image" src="https://user-images.githubusercontent.com/10172392/72241321-7bf9a380-3621-11ea-8997-4fd5260f5194.png">

2. For concatenation along axis 1, (`pd.concat([df1, df2], axis=1)`, i.e., horizontal concatenation of columns), the first 2 rows indexed by 0 should align to each other, leaving empty values for the 3rd row indexed by 0
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/10172392/72241329-887dfc00-3621-11ea-97e1-f55a8e657fe3.png">

3. So in the most generic case, for concatenation along any axis, duplicate indices along that axis are kept and appended (e.g., 2 'A' plus 3 'A' = 5 'A'), duplicate indices along other axis are merged with multiplicity count consistency (e.g., 2 'A' merge with 3 'A', the first 2 'A' corresponds to each other, the last 'A' get empty/NaN values)

**Comment by jreback** [comment]
@xuancong84 this is anti pandas philosophy 

having order dependencies is extremely fragile and would work unexpectedly if you happened to reorder columns or not

we must align columns on the labels; aligning some of them is just really odd

if you want to treat this as a tensor then drop the labels

-1 on this proposal

**Comment by xuancong84** [comment]
@jreback Sorry, could not get what you mean? Would you be more specific by illustration with examples?

Regardless of how you feel, currently when I am developing the omnipotent data plotter for pandas (https://github.com/xuancong84/beiwe-visualizer ), I am experiencing lots of frustrating limitations of pandas. A lot of situations that could be handled easily could not be handled very well. You might want to take a look at my code to how troublesome I work around those to get things work.

Regarding order dependencies, I know it is not ideal

**Comment by gitPrinz** [comment]
I understand, it is not easy to fix?
Because we don't know how to order the columns?
I don't get it really, but i can image it is a problem.

Could there maybe be at least an Exception with a helpful message?

I stumbled on it today and took some time to understand the problem.
And [others](https://stackoverflow.com/questions/53853826/concat-two-dataframes-with-duplicated-index-that-are-in-datetime-format/60723153#60723153) seem to have the same problem.

**Comment by immerrr** [comment]
Notificactions keep bringing me here :) I haven't touched pandas codebase for a while, so take my 2¢ with a grain of salt.

> having order dependencies is extremely fragile

I agree with that: they are fragile and unreliable. And as a maintainer of other projects I get the sentiment of not adding stuff unless really necessary, even if it is conceptual stuff, like "in case of indexing non-unique indexes with non-unique indexer _(re-reading this sentence hurts)_, matching is performed according to the order of the labels".

But from pandas end-user perspective I do see this as a UX papercut. Yes, most of the time you shouldn't care about the ordering of columns or rows, but there are cases where there is no way around. At which point you either verify the existing ordering, or sort by a given criterion, and then for a short period of time you can rely on a specific order to perform a specific operation.

A good example of this would be forward-/backward-filling of NAs: ordering among the filling axis will directly influence the outcome, so before applying that I would need to make sure that the data is ordered as I want it to be. The same approach could be applicable here: if you need to concatenate dataframes with non-unique labels and they are not in the order you want them to be, it's up to you to sort them in whatever order you like.

**Comment by ivirshup** [comment]
I have a few more cases of the error messages being much less helpful than they could be:

```python
pd.concat([  # One dataframe has repeated column names
    pd.DataFrame(np.ones((4, 4)), columns=list("aabc")),
    pd.DataFrame(np.ones((4, 3)), columns=list("abc")),
])
```
```pytb
ValueError: Plan shapes are not aligned
```

```python
pd.concat([  # Repeated columns (same amount) different column ordering
    pd.DataFrame(np.ones((2, 4)), columns=list("aabc")),
    pd.DataFrame(np.ones((2, 4)), columns=list("abca")),
])
```
```pytb
AssertionError: Number of manager items must equal union of block items
```

<details>
<summary> Full tracebacks</summary>

```python
>>> import pandas as pd, numpy as np
>>> pd.concat([  # One dataframe has repeated column names
...     pd.DataFrame(np.ones((4, 4)), columns=list("aabc")),
...     pd.DataFrame(np.ones((4, 3)), columns=list("abc")),
... ])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 287, in concat
    return op.get_result()
  File "/usr/local/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 502, in get_result
    new_data = concatenate_block_managers(
  File "/usr/local/lib/python3.8/site-packages/pandas/core/internals/concat.py", line 54, in concatenate_block_managers
    for placement, join_units in concat_plan:
  File "/usr/local/lib/python3.8/site-packages/pandas/core/internals/concat.py", line 561, in _combine_concat_plans
    raise ValueError("Plan shapes are not aligned")
ValueError: Plan shapes are not aligned
>>> pd.concat([  # Repeated columns (same amount) different column ordering
...     pd.DataFrame(np.ones((4, 4)), columns=list("aabc")),
...     pd.DataFrame(np.ones((4, 4)), columns=list("abca")),
... ])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 287, in concat
    return op.get_result()
  File "/usr/local/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 502, in get_result
    new_data = concatenate_block_managers(
  File "/usr/local/lib/python3.8/site-packages/pandas/core/internals/concat.py", line 84, in concatenate_block_managers
    return BlockManager(blocks, axes)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 149, in __init__
    self._verify_integrity()
  File "/usr/local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 331, in _verify_integrity
    raise AssertionError(
AssertionError: Number of manager items must equal union of block items
# manager items: 3, # tot_items: 4
```

</details>

I think it's a little strange that the following works, but the previous example don't:

```python
>>> pd.concat([  # Repeated columns, same ordering
...     pd.DataFrame(np.ones((2, 4)), columns=list("aabc")),
...     pd.DataFrame(np.ones((2, 4)), columns=list("aabc")),
... ])
     a    a    b    c
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
```

Could there be a check for this in concatenation which throws a better error?

If non-unique column names are to be disallowed it could be something simple, like this other error pandas throws:

```
InvalidIndexError: Reindexing only valid with uniquely valued Index objects
```

It could even be more specific and even name some of the repeated elements, if you wanted to get fancy.

If the case where ordering is preserved will be kept, it could be something like:

```
InvalidIndexError: Repeated column names {non-unique-columns} could not be uniquely aligned between DataFrames
```

**Comment by jreback** [comment]
@ivirshup hapoy to take a PR to have better error message

yeha duplicates along the same axis of concatenation are almost always an error

**Comment by ivirshup** [comment]
I'd be happy to make a PR. I feel like there might be code in pandas that does checks like these already. Any chance you could point me to places these might be?

Also, I'm assuming you want to keep the existing behaviour of the following working for now?

```python
pd.concat([  # Repeated columns, same order
    pd.DataFrame(np.ones((2, 4)), columns=list("aabc")),
    pd.DataFrame(np.ones((2, 5)), columns=list("aabc")),
])
```

**Comment by ivirshup** [comment]
@jreback, I think this conflicts pretty directly with #36290, which allows duplicate items.

Also, I think there are some bugs in that implementation. Using the current release candidate:

```python
import pandas as pd
import numpy as np

from string import ascii_lowercase
letters =  np.array(list(ascii_lowercase))

a_int = pd.DataFrame(np.arange(5), index=[0,1,2,3,3], columns=['a'])
b_int = pd.DataFrame(np.arange(5), index=[0,1,2,2,4], columns=['b'])

a_str = a_int.set_index(letters[a_int.index])
b_str = b_int.set_index(letters[b_int.index])
```

This works (the purpose of the PR, and the example in it's linked issue):

```python
pd.concat([a_int, b_int], axis=1)
```

```
     a    b
0  0.0  0.0
1  1.0  1.0
2  2.0  2.0
2  2.0  3.0
3  3.0  NaN
3  4.0  NaN
4  NaN  4.0
```

This does not work, though I believe it's pretty equivalent to the previous example:

```python
pd.concat([a_str, b_str], axis=1)
```

```pytb
----> 1 pd.concat([a_str, b_str], axis=1)

~/miniconda3/envs/pandas-1.2/lib/python3.8/site-packages/pandas/core/reshape/concat.py in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    297     )
    298 
--> 299     return op.get_result()
    300 
    301 

~/miniconda3/envs/pandas-1.2/lib/python3.8/site-packages/pandas/core/reshape/concat.py in get_result(self)
    526                 mgrs_indexers.append((obj._mgr, indexers))
    527 
--> 528             new_data = concatenate_block_managers(
    529                 mgrs_indexers, self.new_axes, concat_axis=self.bm_axis, copy=self.copy
    530             )

~/miniconda3/envs/pandas-1.2/lib/python3.8/site-packages/pandas/core/internals/concat.py in concatenate_block_managers(mgrs_indexers, axes, concat_axis, copy)
     87         blocks.append(b)
     88 
---> 89     return BlockManager(blocks, axes)
     90 
     91 

~/miniconda3/envs/pandas-1.2/lib/python3.8/site-packages/pandas/core/internals/managers.py in __init__(self, blocks, axes, do_integrity_check)
    141 
    142         if do_integrity_check:
--> 143             self._verify_integrity()
    144 
    145         # Populate known_consolidate, blknos, and blklocs lazily

~/miniconda3/envs/pandas-1.2/lib/python3.8/site-packages/pandas/core/internals/managers.py in _verify_integrity(self)
    321         for block in self.blocks:
    322             if block.shape[1:] != mgr_shape[1:]:
--> 323                 raise construction_error(tot_items, block.shape[1:], self.axes)
    324         if len(self.items) != tot_items:
    325             raise AssertionError(

ValueError: Shape of passed values is (6, 2), indices imply (5, 2)
```

--------------------------

As an overall point, I think the target behaviour of that PR is wrong. Here's an example of why:

```python
# Using pandas 1.2.0rc0
df1 = pd.DataFrame(np.arange(3), index=[0,1,1], columns=['a'])
df2 = pd.DataFrame(np.arange(3), index=[1,0,1], columns=['b'])

pd.concat([df1, df2], axis=1)
```

```
   a  b
0  0  1
1  1  0
1  2  2
```

The results here rely on the ordering of the labels, (https://github.com/pandas-dev/pandas/issues/6963#issuecomment-573619524) which I agree is brittle.

I think there are two more reasonable option for the behaviour.

* Union the indices, duplicates cause errors (my suggestion)
* Mimic merge, take actually have the outer product of indices. 

I'd note the current behaviour of `concat` interprets `"inner"` / `"outer"`  much more like `"intersection"`/ `"union"` compared to `merge`s `"inner"`/ `"outer"` operations. Mimicking merge could be a larger behaviour change.

`1.2.0rc0` is doing something else

<details>
<summary> merge behaviour </summary>

`merge` behaviour compared with `concat` in `1.2.0rc0`

#### merge "inner" and "outer" are equivalent for common repeated indices

```python
In [11]: pd.merge(df1, df2, left_index=True, right_index=True, how="inner")                         
Out[11]: 
   a  b
0  0  1
1  1  0
1  1  2
1  2  0
1  2  2

In [12]: pd.merge(df1, df2, left_index=True, right_index=True, how="outer")                         
Out[12]: 
   a  b
0  0  1
1  1  0
1  1  2
1  2  0
1  2  2
```

and do not match current behaviour of `concat`

#### Current implementation otherwise basically works for outer joins if indices are only repeated in one DataFrame

Using definitions from above, e.g.:

```python
a_int = pd.DataFrame(np.random.randn(5), index=[0,1,2,3,3], columns=['a'])
b_int = pd.DataFrame(np.random.randn(5), index=[0,1,2,2,4], columns=['b'])
```

```python
In [4]: pd.merge(a_int, b_int, left_index=True, right_index=True, how="outer")                      
Out[4]: 
     a    b
0  0.0  0.0
1  1.0  1.0
2  2.0  2.0
2  2.0  3.0
3  3.0  NaN
3  4.0  NaN
4  NaN  4.0

In [89]: pd.concat([a_int, b_int], axis=1, join="outer")
Out[89]: 
     a    b
0  0.0  0.0
1  1.0  1.0
2  2.0  2.0
2  2.0  3.0
3  3.0  NaN
3  4.0  NaN
4  NaN  4.0
```

#### But not for inner joins

```python
In [8]: pd.merge(a_int, b_int, left_index=True, right_index=True, how="inner")                      
Out[8]: 
   a  b
0  0  0
1  1  1
2  2  2
2  2  3

In [9]:  pd.concat([a_int, b_int], axis=1, join="inner")                                            
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-03adb33c977d> in <module>
----> 1 pd.concat([a_int, b_int], axis=1, join="inner")

~/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/pandas/core/reshape/concat.py in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    297     )
    298 
--> 299     return op.get_result()
    300 
    301 

~/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/pandas/core/reshape/concat.py in get_result(self)
    526                 mgrs_indexers.append((obj._mgr, indexers))
    527 
--> 528             new_data = concatenate_block_managers(
    529                 mgrs_indexers, self.new_axes, concat_axis=self.bm_axis, copy=self.copy
    530             )

~/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/pandas/core/internals/concat.py in concatenate_block_managers(mgrs_indexers, axes, concat_axis, copy)
     87         blocks.append(b)
     88 
---> 89     return BlockManager(blocks, axes)
     90 
     91 

~/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/pandas/core/internals/managers.py in __init__(self, blocks, axes, do_integrity_check)
    141 
    142         if do_integrity_check:
--> 143             self._verify_integrity()
    144 
    145         # Populate known_consolidate, blknos, and blklocs lazily

~/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/pandas/core/internals/managers.py in _verify_integrity(self)
    321         for block in self.blocks:
    322             if block.shape[1:] != mgr_shape[1:]:
--> 323                 raise construction_error(tot_items, block.shape[1:], self.axes)
    324         if len(self.items) != tot_items:
    325             raise AssertionError(

ValueError: Shape of passed values is (4, 2), indices imply (3, 2)
```

</details>

**Comment by jreback** [comment]
@ivirshup ahh i remember now. yeah handling duplicates is hard. so we can handle some of them. i am actually ok with raising on duplicates in either axis, but would have to see how much would break.
