### ISSUE TITLE
Feature request: add median, mode & number of unique entries to pandas.DataFrame.describe()

### ISSUE THREAD

**Issue by tantrev** [pandas-dev/pandas#7014]
Would come in handy for a number of a different applications from basic statistics, to understanding one's data, to estimating machine learning algorithmic load.

dupe of #2749

**Comment by soupault** [comment]
`median` out-of-the-box would really be a great thing to have!

**Comment by jorisvandenbossche** [comment]
Note that median is already in describe, as in ``50%``

**Comment by soupault** [comment]
@jorisvandenbossche indeed! Sorry, my bad. :baby:

**Comment by TomAugspurger** [comment]
Hijacking this issue to propose a variant (and steal more from dplyr)

Why not have a `DataFrame.agg` that is identical to `DataFrame.groupby.agg`, but with a "single group"? This also goes along with the new `.resample.agg`, yay for synergy. Basically it takes a function/str or list of functions/strs or a dict of column names to functions/str and aggregates accordingly.

**Comment by jorisvandenbossche** [comment]
Related to https://github.com/pydata/pandas/issues/1623
