### ISSUE TITLE
Lifting limits on display options: None vs 0 vs Inf ?

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [pandas-dev/pandas#7018]
When lifting limits on display options, for some of them one can use `None`:

```
display.max_columns = None
display.display.max_rows = None
display.width = None
```

but for other options, Pandas complains if you use `None` returning `ValueError: Value must have type '<type 'int'>'`, so you have to use 0

```
display.max_col_width = 0
```

Is this intentional? If so, what is the rationale behind it?

**Comment by mroeschke** [comment]
Thanks for the request, but it appears this hasn't gain traction in a while so closing
