### ISSUE TITLE
Create Holiday Calendar for NYSE Stock Market

### ISSUE THREAD

**Issue by cancan101** [pandas-dev/pandas#7070]
Using new code in #6719

See: http://www.nyx.com/holidays-and-hours/nyse
and with some guidlines: http://www.investmentcontrarians.com/nyse-2013-stock-market-holidays/

**Comment by native-api** [comment]
IMO country-specific stuff belongs in optional addons unless support for all countries is a goal.

**Comment by rsheftel** [comment]
I had a need for market and exchange calendars and was lead to this thread. Inspired by it I made a fork of the Zipline project to just extract the trading calendar information and put it into a new project that creates pandas objects for holidays, date_range and DatetimeIndex. I hope people find it useful:

https://pypi.python.org/pypi/pandas-market-calendars

https://github.com/rsheftel/pandas_market_calendars

**Comment by jreback** [comment]
closing. this could be an external package.
