### ISSUE TITLE
Adding YQL (Yahoo Query Language) to io

### ISSUE THREAD

**Issue by wawrzek** [pandas-dev/pandas#7104]
Browsing through  'Python for Data Analysts' I expected pandas used YQL to get finance data, but going though it more deeply it seems not be a case. I think it might be nice to have YQL as additional 'reader' in the io sub-module. There is documentation here: https://developer.yahoo.com/yql/

**Comment by jorisvandenbossche** [comment]
Closing this as out of scope for core pandas. It would certainly make for a nice standalone extension package or as an addition to pandas-datareader, if someone is interested.
