### ISSUE TITLE
API: add "show_counts" arg to info

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#7132]
From https://github.com/pydata/pandas/issues/6939, @jorisvandenbossche made the suggestion that

> we could add a keyword argument like show_counts (or another name) to specify if you want to show the non-null counts (to be able to override the max_info_rows option for a specific info call)

scheduling for .14.1 unless someone gets to it before then.

**Comment by MarcoGorelli** [comment]
there's no uptake on this in nearly a decade, let's close
