### ISSUE TITLE
ENH: support coordinate access for indexing

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#7138]
`df.iloc[[0,1],[0,1]]` means return the square 0-1 rows and 0-1 columns

might be nice to have a way to mean return the _coordinates_ `(0,0),(0,1)`

related #7522

http://stackoverflow.com/questions/23686561/slice-a-pandas-dataframe-by-an-array-of-indices-and-column-names/23686855#23686855

**Comment by jbrockmendel** [comment]
we have lookup, i think this can be closed
