### ISSUE TITLE
read_fwf does not support dtype argument

### ISSUE THREAD

**Issue by brendon9x** [pandas-dev/pandas#7141]
The documentation implies that you can supply a `dtype` dict to `read_fwf`, but in reality this option is silently dropped as it looks like it's only supported by the c parser.  My specific use case is loading Triple-S files which are fairly prolific in the market research world.  The Triple-S standard is basically an XML file which describes a fixed width file.  It's fairly trivial to get this to work in Pandas in a few lines of code which is great.

The problem arises when these files become really large.  I tried using chunked conversion to HDF5 using `append_to_multiple` but ran into a baffling problem of certain chunks failing on append.  Stepping through the code, it looked like the underlying block layouts where different per chunk.  And this in turn was caused by the fact that column inference is applied per chunk and dtypes are ignored.  I suspect this is caused by data being missing in some chunks and not in others.

The lowest hanging fruit is to update that docs and I'm happy to do a PR for this.  But it would be awesome if the c parser could be tweaked to allow reading fixed width files as this issue would go away and we'd get a huge speed boost.  This initially looked hard, but then started to look like adding a simpler statemachine might be possible if colspecs could be passed in.  I could possibly do this as a PR, but would probably need some PR hand holding.  Finally, if you could point out a simple place to apply the dtype argument in the read_fwf parser, I can give it a go as a second best case PR.

**Comment by gfyoung** [comment]
@jreback : Is it just that simple that we do `try-except` for each specified `dtype`?  Why can it be that simple compared to the C engine?  I didn't quite follow your explanation above.

**Comment by jreback** [comment]
In python I think it IS that simple. The c-engine does all of this in cython (basically the same thing); though it does it with much more c-code, which happens to not hold the GIL (though it wasn't that way to start). I don't know why it was not done with ``try-except``; could be efficiency actually; though most of the c-code is doing ``.astype``

**Comment by gfyoung** [comment]
Fair enough.  Will give it a shot and see what happens.

**Comment by jreback** [comment]
btw there *might* be more issues (that are open) w.r.t. dtype handling by python engine. IIRC

**Comment by gfyoung** [comment]
Perhaps.  The more I keep looking at this, the more complicated the issue _seems_ to be because of that inconsistent handling of converters, dtypes, and coerced casting.  I could put the attempted `dtype` casting where you had initially put it, but it isn't consistent with what the C engine does because currently the C engine doesn't respect `dtype` if there are converters involved (similar to #13302).  The casting behaviour on both engines is not aligned in fact, and it's surprising to an extent how consistent their behaviour has been in testing.

**Comment by gfyoung** [comment]
@chris-b1 : Does #14295 resolve this issue?

**Comment by chris-b1** [comment]
It should, although I didn't add any docs or tests for that case - I'll do a follow-up PR, thanks for noticing this.
