### ISSUE TITLE
GOTCHA: You can't use dot notation to add a column to a DataFrame

### ISSUE THREAD

**Issue by AllenDowney** [pandas-dev/pandas#7175]
I ran into a nasty gotcha I have not seen mentioned in the documentation.  In general, you can refer to DataFrame columns like a dictionary key or like an object attribute.  But the behavior is inconsistent.  In particular, you can modify an existing column using dot notation, but you can't add a new column.

The following example demonstrates.

```
d = {'one' : pd.Series([1., 2., 3.], index=['a', 'b', 'c']),
     'two' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)

# this adds a column to df
df['three'] = df.two + 1

# this successfully modifies an existing column
df.one += 1

# this seems to work but does not add a column to df
df.four = df.two + 2

print df.three
print df.four
print df
```

Is this behavior unavoidable?

**Comment by bkomboz** [comment]
+1 for a warning (pandas user here which just run into this issue).

**Comment by paulwasit** [comment]
Has the warning been implemented ? The milestone says 0.18.2, but on 0.19.0 it doesn't seem to appear.

**Comment by jreback** [comment]
no, it says Next Major Release, and this issue is still open. pull-requests to implement are welcome.

**Comment by paulwasit** [comment]
Ah ok. I would gladly give it a try, but I am not sure where to start looking :/

**Comment by jreback** [comment]
right [here](https://github.com/pandas-dev/pandas/blob/master/pandas/core/generic.py#L2746)

easy enough to see if one is setting using a pandas object but the column is not defined, then could show a warning

**Comment by paulwasit** [comment]
Thanks @jreback ! I will have a look and see what I can do.
