### ISSUE TITLE
ERR: more helpful error message on invalid access with a timestamp-like

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#7211]
related https://github.com/pydata/pandas/issues/7209

Might be a nicer error message (gist of this)

Hey you are trying to access a single element on AXIS 1, you can do it with a slice if you want, or use .loc to access the frame by row

```
In [3]: df = DataFrame(1,index=pd.date_range('20130101',periods=5),columns=['value'])

In [4]: df['20130102']
KeyError: '20130102'

In [5]: df['20130102':]
Out[5]: 
            value
2013-01-02      1
2013-01-03      1
2013-01-04      1
2013-01-05      1
```

**Comment by ryankarlos** [comment]
I would like to take this but is there a link to a script where the original error message is being generated from ?

**Comment by jreback** [comment]
see https://github.com/pandas-dev/pandas/issues/7209#issuecomment-43936867 and comment above

**Comment by dsm2173** [comment]
Hey Jeff, @jmp392 and I are taking a stab at this. We traced the error to a .pxi file and were able to edit what the raised exception stated to be more informative but .pxi files are listed in gitignore, this is our first PR, we assume these filetypes are in the gitignore for a reason, should we remove the .pxi from the gitignore and submit a PR? we do not see any other way to bypass this issue

**Comment by jreback** [comment]
edit the .pxi.in as the .pxi are generated from these

**Comment by MomIsBestFriend** [comment]
take

**Comment by jbrockmendel** [comment]
This type of indexing is deprecated, not sure this is worth the trouble

**Comment by mroeschke** [comment]
Agreed, closing
