### ISSUE TITLE
DOC: add to ecosytem (in sql-interface category?)

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#7249]
no particular order, prob need a bit of description; these are suggestions, if people think they don't belong ok then

https://bitbucket.org/zzzeek/calchipan

https://github.com/keeganmccallum/sql4pandas

https://github.com/yhat/pandasql/

**Comment by jorisvandenbossche** [comment]
None of those listed projects have seen activity the last year, so closing this. If somebody cares about them, of course still welcome to add them to the ecosystem page, but we don't need an open issue for it :)
