### ISSUE TITLE
API: allow multiple indices in Index.insert

### ISSUE THREAD

**Issue by sinhrks** [pandas-dev/pandas#7384]
Derived from #7299. `numpy.insert` can accept multiple elements / indices as of v1.8.
http://docs.scipy.org/doc/numpy/reference/generated/numpy.insert.html

Allow `Index` to accept multiple elements / indices. Currently, it raises `IndexError`.

```
import pandas as pd
idx1 = pd.Index([1, 2, 3, 4, 5])
idx1.insert([1, 2], 0)
# IndexError: invalid slice
```

**Comment by mroeschke** [comment]
Look to work on main and I believe we have a test for this so closing
