### ISSUE TITLE
Conditional Join (merge) in pandas

### ISSUE THREAD

**Issue by ywhcuhk** [pandas-dev/pandas#7480]
I wonder if it possible to implement conditional join (merge) between pandas dataframes. Basically, I am thinking some conditional SQL-like joins:

```
  select a.id, a.date, a.var1, a.var2, 
      b.var3 
      from data1 as a  left join data2 as b
      on (a.id<b.key+2 and a.id>b.key-3) and (a.date>b.date-10 and a.date<b.date+10);
```

Above code is just a made up example to show the purpose. 

---

http://stackoverflow.com/questions/23508351/how-to-do-a-conditional-join-in-python-pandas 

This question on stackoverflow is ask for the same purpose. The answer provided in the question solves the problem, but it's quite ad hoc. 

Can we have something like:

```
conditions= " (a.id<b.key+2 and a.id>b.key-3) and (a.date>b.date-10 and a.date<b.date+10)"
df=pd.merge(left, right, on= "conditions", how="left (or right...) ")
```

It seems until now, the SQL statements are still way more flexible than pandas "merge" or "join". It would be nice to have it in pandas itself.

**Comment by mroeschke** [comment]
I think https://github.com/pandas-dev/pandas/issues/8962 is the generalize version of this request. Will link this issue over on that issue.
