### ISSUE TITLE
combine_first not retaining dtypes

### ISSUE THREAD

**Issue by altaurog** [pandas-dev/pandas#7509]
I found a number of issues that seemed related, all closed over a year ago, but there still seem to be some inconsistencies here:

``` python
In [1]: from datetime import datetime
In [2]: import pandas as pd
In [3]: pd.__version__
Out[3]: '0.13.1'
In [4]: dfa = pd.DataFrame([[datetime.now(), 2]], columns=['a','b'])
In [5]: dfb = pd.DataFrame([[4],[5]], columns=['b'])
In [6]: dfa.dtypes
Out[6]: 
a    datetime64[ns]
b             int64
dtype: object
In [7]: dfb.dtypes
Out[7]: 
b    int64
dtype: object
In [8]: # int64 becomes float64 when combining the two frames
In [9]: dfa.combine_first(dfb).dtypes
Out[9]: 
a    datetime64[ns]
b           float64
dtype: object
In [10]: # datetime64[ns] becomes float64 if the first frame is empty
In [11]: dfa.iloc[:0].combine_first(dfb).dtypes
Out[11]: 
a    float64
b      int64
dtype: object
```

**Comment by VelizarVESSELINOV** [comment]
When you combine_first the original float32 column is transformed to float64:

```python
"""Example of Pandas bug."""
from pandas import DataFrame
from numpy import float32

print('-' * 15)
d1 = DataFrame(index=[0])
d1['A'] = [3.5]
d1['A'] = d1['A'].astype(float32)
print(d1.dtypes)
print('-' * 15)
d2 = DataFrame(index=[0])
d2['B'] = [35]  # if uncomment this line the result is correct, nonsense for me
d2 = d2.combine_first(d1)
print(d2.dtypes)
```

Current output:
```
---------------
A    float32
dtype: object
---------------
A    float64
B      int64
dtype: object
```
Expected output:
```
---------------
A    float32
dtype: object
---------------
A    float32
B      int64
dtype: object
```

**Comment by lsorber** [comment]
This is still a bug in 2020:

```python
>>> dfa = pd.DataFrame({"A": [0, 1, 2]}, index=[0, 1, 2])
>>> dfb = pd.DataFrame({"A": [7, 8, 9]}, index=[1, 2, 3])
>>> dfa.combine_first(dfb).dtypes  # Expect to see int64
A    float64
dtype: object
```

Any plans on addressing this issue?

**Comment by jreback** [comment]
pandas is an all volunteer project.

if you would like to submit a PR then one of the volunteers would be able to code review

**Comment by danielhrisca** [comment]
> pandas is an all volunteer project.
> 
> if you would like to submit a PR then one of the volunteers would be able to code review

I think think this is a serious issue. If I had the knowledge to fix it myself I would. Maybe someone from the core developers can have a look

**Comment by jreback** [comment]
@danielhrisca there are many 'serious issues' again pandas is all volunteer and there are quite a number of open issues
i cannot instruct anyone to look at anything in particular

**Comment by danielhrisca** [comment]
There is a dtype promotion going on in [take_nd](https://github.com/pandas-dev/pandas/blob/master/pandas/core/algorithms.py#L1674) 

Does it make sense to try there to apply the older dtype or just before returning from ``combine_first``?

**Comment by danielhrisca** [comment]
On a second look the root cause seems to be that the alignment is done with ``fill_value=None`` (here https://github.com/pandas-dev/pandas/blob/master/pandas/core/frame.py#L6368) which promotes all numeric columns to ``f8``. 

I think that if we check that the two dataframe have identical columns, then we can provide a better ``fill_value`` (here https://github.com/pandas-dev/pandas/blob/master/pandas/core/frame.py#L6485) which then should be applied at the above mentioned line. This reasoning is valid since we can be sure that in the end there will be no newly inserted ``nan`` values after combining the dataframes.

@jreback what do you think?

**Comment by jreback** [comment]
sure can check if they have identical columns then no action, also `find_common_dtype` (the pandas one would be useful here).

**Comment by danielhrisca** [comment]
@jreback 
#39051 is my first stab at trying to preserved dtypes for DataFrame with the same columns. I'll add some test today
