### ISSUE TITLE
PERF/API: alias len/size in groupby.transform

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#7570]
alias `len/size` to `groupby.transform` speedup table (as these are already implemented as `size`,`count`` in cython, just  a matter of transforming them

see here: http://stackoverflow.com/questions/24438273/aggregation-on-pandas-datetime-series-only-returns-as-datetime-series/24438366#24438366
(`len` is suspect for `.agg`  as well)

so 

```
g = df.groupby(...)

g.transform(len)
g.transform('size')
g.transform('len')
```

will do the same

**Comment by jreback** [comment]
needs to be added to the built-ins table in ``pandas/core/base.py``

**Comment by rhshadrach** [comment]
@jreback - is there still a desire to alias len with size? If going this route, I think we'd also want to add e.g. DataFrameGroupBy.len.

**Comment by jreback** [comment]
kind of 0 on this as .len() method is non pythonic

**Comment by rhshadrach** [comment]
Didn't think about that - but agreed. I don't see any users asking for this and don't love the idea of expanding the API makes me lean toward -1 here.

**Comment by mroeschke** [comment]
Agree with @rhshadrach. I'd like to see less aliasing in the API as well.

I think we can close due to lack of enthusiasm for this API.
