### ISSUE TITLE
ENH: Categorical serialized

### ISSUE THREAD

**Issue by jankatins** [pandas-dev/pandas#7621]
Currently df which include a categorical can be written to a hdf store and other on disc storage formats. For formats which include factors/categoricals, also ensure that such data is read into a categorical.
- [ ] CSV #7217, #7444 (just testing, not a completely fungible format)
- [x] HDF5 #7217, #7444 / #8793 
- [x] msgpack #8632 (closed by #12573)
- [x] stata #8633 / #8767

**Comment by jreback** [comment]
closing, you cannot directly serialize a Categroical in csv, but you can specify the dtype when reading.
