### ISSUE TITLE
Proposal: New Index type for binned data (IntervalIndex)

### ISSUE THREAD

**Issue by shoyer** [pandas-dev/pandas#7640]
### Design

The idea is to have a natural representation of the grids that ubiquitously appear in simulations and measurements of physical systems. Instead of referencing a single value, a grid cell references a _range_ of values, based on the chosen discretization. Typically, cells boundaries would be specified by floating point numbers. In one dimension, a grid cell corresponds to an _interval_, the name we use here.

The key feature of `IntervalIndex` is that looking up an indexer should return all intervals in which the indexer's values fall. `FloatIndex` is a poor substitute, because of [floating point precision issues](https://groups.google.com/d/topic/pydata/8aTLVKrPJfs/discussion), and because I don't want to label values by a single point.

A `IntervalIndex` is uniquely identified by its `intervals` and `closed` (`'left'` or `'right'`) properties, an ndarray of shape `(len(idx), 2)`, indicating each interval. Other useful properties for `IntervalIndex` would include `left`, `right` and `mid`, which should return arrays (indexes?) corresponding to the left, right or mid-points of each interval.

The constructor should allow the optional keyword argument `breaks` (an array of length `len(idx) + 1`) to specified instead of `intervals`.

It's not entirely obvious what `idx.values` should be (`idx.mid`? strings like `'(0, 1]'`? an array of tuples or `Interval` objects?). I think the most useful choice for cross compatibility would probably be to an ndarray like `idx.mid`.

`IntervalIndex` _should_ support mathematical operations (e.g., `idx + 1`), which are calculated by vectorizing the operation over the breaks.
### Examples

An example already in pandas that should be a `IntervalIndex` is the `levels` property of categorical returned by `cut`, which is currently an object array of strings:

```
>>> pd.cut([], [0, 5, 10]).levels
Index([u'(0, 5]', u'(5, 10]'], dtype='object')
```

Example usage:

``` python
>>> # should be equivalent to pd.cut([], [0, 1, 2]).levels
>>> idx = IntervalIndex(intervals=[(0, 1), (1, 2)]) 
>>> idx2 = IntervalIndex(breaks=[0, 1, 2]) # equivalent
>>> idx
IntervalIndex([(0, 1), (1, 2)], closed='right')
>>> idx.left
np.array([0, 1]) 
>>> idx.right
np.array([1, 2]) 
>>> idx.mid
np.array([0.5, 1.5]) 
>>> s = pd.Series([1, 2], idx)
(0, 1]    1
(1, 2]    2
dtype: int64
>>> s.loc[1]
1
>>> s.loc[0.5]
1
>>> s.loc[0]
KeyError
```
### Implementation

A `IntervalIndex` would be a monotonic and non-overlapping one-dimensional array of intervals. It is _not_ required to be contiguous. A scalar `Interval` would correspond to a contiguous interval between start and stop values (e.g., given by integers, floating point numbers or datetimes).

For index lookups, I propose to do a binary search (`np.searchsorted`) on `idx.left`. If we add the constraint that all intervals must have a fixed width, we could calculate the bin using a formula in constant time, but I'm not sure the loss in flexibility would be worth the speedup.

`IntervalIndex` should play nicely when used as the levels for `Categorical` variable (#7217), but it is _not_ the same as a `CategoricalIndex` (#7629). For example, a `IntervalIndex` should not allow for redundant values. To represent redundant or non-continuous intervals, you would need to make in a `Categorical` or `CategoricalIndex` which uses a `IntervalIndex` for the levels. Calling `df.reset_index()` on an `DataFrame` with an `IntervalIndex` would create a new `Categorical` column.

---

Note: I'm not entirely sure if this design doc belongs here or on mailing list (I'm happy to post it there if requested).

Here is the comment where I brought this up previously: https://github.com/pydata/pandas/issues/5460#issuecomment-44474502

CC @hugadams -- I expect `IntervalIndex` would be very handy for your [pyuvvis](https://github.com/hugadams/pyuvvis).

**Comment by shoyer** [comment]
For those of you not following along in #901 (which is honestly a dup of this issue), I am now thinking that the implementation here should probably use an actual interval-tree rather than relying on sortedness.

Also, for future reference: a suitable data-structure for an index of multi-dimensional intervals  (an `NDIntervalIndex`) is an ["R-tree"](http://en.wikipedia.org/wiki/R-tree). And in fact, this is quite a handy data-structure for GIS queries -- there is an R-tree now implemented in Geopandas: https://github.com/geopandas/geopandas/issues/140

**Comment by bla1089** [comment]
I'm not sure if this belongs here or elsewhere. However, I'm trying to not clutter everything uselessly by just adding to the ever growing list of issues. If this belongs elsewhere, I'm happy to move it.

Is there a reason `pd.cut` returns a `CategoricalIndex` instead of an `IntervalIndex`? The current behavior is

```python
>>> pd.cut(np.linspace(0,` 100), bins=np.linspace(0, 101, 10)).value_counts().sort_index().index
CategoricalIndex([   (0.0, 11.222], (11.222, 22.444], (22.444, 33.667],
                  (33.667, 44.889], (44.889, 56.111], (56.111, 67.333],
                  (67.333, 78.556], (78.556, 89.778],  (89.778, 101.0]],
                 categories=[(0.0, 11.222], (11.222, 22.444], (22.444, 33.667], (33.667, 44.889], (44.889, 56.111], (56.111, 67.333], (67.333, 78.556], (78.556, 89.778], ...], ordered=True, dtype='category')
```

instead of the following.
```python
IntervalIndex([(0.0, 11.222], (11.222, 22.444], (22.444, 33.667], (33.667, 44.889], (44.889, 56.111], (56.111, 67.333], (67.333, 78.556], (78.556, 89.778], (89.778, 101.0]]
              closed='right',
              dtype='interval[float64]')
```

I would naively think that an `IntervalIndex` would make more sense here. It might also allow simplified plotting behavior such that 

```python
cut = pd.cut(np.linspace(0, 100), bins=np.linspace(0, 101, 10)).value_counts().sort_index()
cut.plot(index_part="mid")
```
would plot the counts vs. the index mid point.

**Comment by bla1089** [comment]
I understand. However, a categorical index does not have the same methods
and properties available as an interval index. Is it at all reasonable to
return an interval index when the categories are purely numeric? Are there
reasons to use a categorical over an interval?

Ben

---------------------
B. L. Alterman
Candidate, Applied Physics
Solar and Heliospheric Research Group
Climate and Space Sciences and Engineering
University of Michigan
balterma@umich.edu

**Comment by jreback** [comment]
@bla1089 I did consider return an ``IntervalIndex`` from cut/qcut. But rejected as:

- it broken backward compat in a big way
- the implementation of II is not efficient when stored in a Series (going to better in 0.24 with ExtensionArray)
- indexing is quite a bit simpler

So in theory it is possible, but I don't really see a compelling reason to switch. cats are a nicer holder type of data like this. What exactly is the issue?

**Comment by bla1089** [comment]
@jreback I find myself doing the following type of thing rather often:

```python
cut = pd.cut(np.linspace(0, 100), bins=np.linspace(0, 101, 10)).value_counts().sort_index()
cut.index = pd.IntervalIndex(cut.index).mid.astype(float)
cut.plot(drawstyle="steps-mid")
```

I hadn't seen a particular issue for it and I was wondering if I was missing something. The backwards compat issue is certainly relevant.
