### ISSUE TITLE
read_csv/to_csv sep/delimiter inconsistency

### ISSUE THREAD

**Issue by dsm054** [pandas-dev/pandas#7662]
related #7615

Bit of a UI problem here (although it's behaving as the docstring says it does, so it doesn't quite qualify as a bug):

```
>>> df = pd.DataFrame({"A": [1,2,3], "B": [4,5,6]})
>>> df.to_csv("tmp.csv", sep=";")
>>> !cat tmp.csv
;A;B
0;1;4
1;2;5
2;3;6
>>> df.to_csv("tmp.csv", delimiter=";")
>>> !cat tmp.csv
,A,B
0,1,4
1,2,5
2,3,6
```

`read_csv` accepts both `sep` and `delimiter` but `to_csv` silently ignores `delimiter`.  Someone was recently tripped up by this on SO.  I'm fine with either teaching `to_csv` to behave the same way `read_csv` does or, alternatively, raising if `delimiter` is found as a keyword.  

That is, I'm less bothered by the inconsistency than the silent unexpected behaviour.

**Comment by indera** [comment]
👍   Spent about an hour trying to figure out why passing "delimiter" does not affect the "to_csv" call ...

**Comment by indera** [comment]
Will try to fix this if nobody started.

Relevant code:

to_csv => https://github.com/pandas-dev/pandas/blob/ee374ee3bc49b82754e8269f69cf8f79d488bd5e/pandas/core/frame.py#L1303

read_csv => https://github.com/pandas-dev/pandas/blob/master/pandas/io/parsers.py#L565

**Comment by gfyoung** [comment]
@indera : Just what are you trying to fix exactly?  The `**kw` option has been removed in `to_csv`, so are you trying to add `delimiter` to `to_csv`?

**Comment by jreback** [comment]
@dsm054 @gfyoung is right, this *used* to be a problem, but no-longer.

**Comment by indera** [comment]
Yes, this is fixed in pandas==0.19.0 

I get an error as expected:

TypeError: to_csv() got an unexpected keyword argument 'delimiter'

**Comment by indera** [comment]
@gfyoung - we should probably now remove support for "delimiter" in read_csv for consistency ;)

**Comment by jorisvandenbossche** [comment]
@indera the difference is that for `read_csv` the `delimeter` keyword actually works, so not sure if deprecating/removing is worth it. For `to_csv` it never worked, so that is another situation.

**Comment by gfyoung** [comment]
@jorisvandenbossche : It wouldn't be that hard to incorporate into the `to_csv` signature though, so that's one way to go about it to make things consistent.

**Comment by jorisvandenbossche** [comment]
Consistency is nice, but the recommended one `sep` is already consistent for both, so IMO not needed to make the duplication consistent :-)

**Comment by gfyoung** [comment]
That's fair, though we could consider deprecating `delimiter` at some point...:smile:

**Comment by indera** [comment]
@gfyoung deprecating `delimiter` sounds good... removing code in general feels good 😄

**Comment by gfyoung** [comment]
@jorisvandenbossche @jreback : Thoughts?

**Comment by dahlbaek** [comment]
@gfyoung wrote:

> That's fair, though we could consider deprecating delimiter at some point, just not now...

Any update on this? Is 'not now' now?

**Comment by gfyoung** [comment]
@jorisvandenbossche @jreback : Thoughts?

**Comment by jandren** [comment]
The above pull request was closed due to stalling and never merged. The inconsistency remains, which I just encountered. Used `delimiter` on read_csv and then got errors when I later tried to use to_csv with `delimiter` again.

**Comment by jreback** [comment]
@jandren happy to take a new PR to deprecate

**Comment by jandren** [comment]
Thanks for the opportunity @jreback! My intention was to just give updated feedback and poke the issue as still alive. I have to little knowledge about the pros and cons of `sep` vs `delimiter`, so I will leave it to people familiar with the code base.
