### ISSUE TITLE
YearOffset() raises AttributeError

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#7706]
From https://github.com/pydata/pandas/pull/7375#issuecomment-48467303:
related: https://github.com/pydata/pandas/issues/4804
xref: #7705 (MonthOffset)

```
In [55]: offsets.YearOffset()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-55-b53e59b753d1> in <module>()
----> 1 offsets.YearOffset()

c:\users\vdbosscj\scipy\pandas-joris\pandas\tseries\offsets.pyc in __init__(self
, n, normalize, **kwds)
   1331
   1332     def __init__(self, n=1, normalize=False, **kwds):
-> 1333         self.month = kwds.get('month', self._default_month)
   1334
   1335         if self.month < 1 or self.month > 12:

AttributeError: 'YearOffset' object has no attribute '_default_month'
```

**Comment by jbrockmendel** [comment]
My understanding is that MonthOffset, YearOffset, SemiMonthOffset are base classes not indeed to be directly used. Possibly should be privatized?

**Comment by jorisvandenbossche** [comment]
> My understanding is that MonthOffset, YearOffset, SemiMonthOffset are base classes not indeed to be directly used. Possibly should be privatized?

I am not familiar with offsets, but if that is the case: yes, then we should privatize them.

**Comment by jbrockmendel** [comment]
These should also be removed from the doc offset_frequency.rst file right?

**Comment by mroeschke** [comment]
Looks like this has been effectively privatized.

```
In [2]: pd.offsets.YearOffset()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-6487f32a8b3a> in <module>
----> 1 pd.offsets.YearOffset()

AttributeError: module 'pandas.tseries.offsets' has no attribute 'YearOffset'
```

And I don't see it in offset_frequency. Closing
