### ISSUE TITLE
qcut() should make sure the bins bounderies are unique before passing them to _bins_to_cuts

### ISSUE THREAD

**Issue by yonil7** [pandas-dev/pandas#7751]
xref #8309

for example:

``` python
pd.qcut([1,1,1,1,1,1,1,1,1,1,1,1,1,5,5,5], [0.00001, 0.5])
```

will raise "ValueError: Bin edges must be unique: array([ 1.,  1.])" exception

Fix suggestion - add one new line:

``` python
def qcut(x, q, labels=None, retbins=False, precision=3):
    if com.is_integer(q):
        quantiles = np.linspace(0, 1, q + 1)
    else:
        quantiles = q
    bins = algos.quantile(x, quantiles)
--->bins = np.unique(bins)
    return _bins_to_cuts(x, bins, labels=labels, retbins=retbins,
        precision=precision, include_lowest=True)
```

**Comment by dukebody** [comment]
See http://stackoverflow.com/questions/20158597/how-to-qcut-with-non-unique-bin-edges for a discussion about this. 

@edjoesu I agree with your proposal, but I foresee that the implementation won't be trivial, since the way the current code assigns values to bins I think some bins would become empty if duplicates are allowed.

**Comment by dukebody** [comment]
I think we could add a "duplicate_edges" parameter, with the following options:

 * 'raise' (default). Raise an error if duplicate bin edges are found.
 * 'drop'. Delete duplicate edges, adding the `bins = np.unique(bins)` line as in https://github.com/pydata/pandas/issues/7751#issue-37814702. This would result in less bins than specified, and some larger (with more elements) than others.
 * 'unique'. Perform the binning based on the unique values present in the input array. This is essentialy the first solution in http://stackoverflow.com/questions/20158597/how-to-qcut-with-non-unique-bin-edges and would imply unevenly sized bins, without altering the total number of bins.

Does it look reasonable? What do you think?

**Comment by rainjacket** [comment]
dukebody's suggestion looks good to me.

For my use case, I would prefer for qcut to just return the (non-unique) bin list, and let me handle it.

**Comment by randomgambit** [comment]
hi guys let me jump in and push for that to happen as well.  Solutions already exist in many other languages, its just a matter of choosing one of them.  See also https://stackoverflow.com/questions/38594277/how-to-compute-quantile-bins-in-pandas-when-there-are-ties-in-the-data/38596578?noredirect=1#comment64582414_38596578

**Comment by randomgambit** [comment]
see for instance here for a possible solution adopted in SAS

https://support.sas.com/documentation/cdl/en/proc/61895/HTML/default/viewer.htm#a000146840.htm

**Comment by jreback** [comment]
@randomgambit its not about a soln. This is quite straightforward. Its about someone actually implementing it. There are many many many issues. If someone wants to submit a PR that moves things WAY faster.

**Comment by randomgambit** [comment]
i get it jeff, no worries. unfortunately i dont have the python skills to help you and get the jerb done

**Comment by ashishsingal1** [comment]
#14455
Potential fix
