### ISSUE TITLE
Rapid Concurrent Access Breaks HDFStore

### ISSUE THREAD

**Issue by yikelu** [pandas-dev/pandas#7838]
There are several errors associated with this. One of them is that the HDFStore fails to load some tables inside the store file, but fails silently. Another error is a loud HDF5 error that gives a full traceback. Both should be visible in the following code.

```
import pandas as pd
import multiprocessing as mp

def f(x):
    tt = pd.HDFStore('storage.h5', mode = 'r')
    print tt

p = mp.Pool()
p.map(f, range(50))
```

**Comment by jreback** [comment]
docs already look pretty good. closing.
