### ISSUE TITLE
MultiIndex.tostring() produces empty string for non-empty index

### ISSUE THREAD

**Issue by lebedov** [pandas-dev/pandas#7841]
With pandas 0.14.1, the following code produces an empty string:

```
import pandas
idx = pandas.MultiIndex(levels=[['a'],[0,1,2,3,4,4]], 
                        labels=[[0,0,0,0,0],[0,1,2,3,4]],
                        names=[0,1])
print idx.tostring()
```

Is this behavior correct? `Index.tostring()` appears to produce a non-empty string for a non-empty index.

**Comment by dsm054** [comment]
Since there _is_ no (Multi)Index.tostring these days, I don't think this applies any more.

**Comment by jreback** [comment]
agreed.
