### ISSUE TITLE
API: should allow setting with enlargement with list-likes

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#7887]
from #7867 

```
In [1]: s = pd.Series([1,2,3])

In [2]: s
Out[2]: 
0    1
1    2
2    3
dtype: int64

# this is de-facto: s.reindex([[1,2,3]])
In [3]: s.loc[[1,2,3]]
Out[3]: 
1     2
2     3
3   NaN
dtype: float64
```

should this work?

```
In [4]: s.loc[[1,2,3]] = 4
KeyError: '[3] not in index'
```

(Doing this with only included labels works)

**Comment by hgilde** [comment]
did this turn out to be harder than it seems?

**Comment by jreback** [comment]
@hgilde no-one has worked on this (and we might eliminate this behavior going forward anyhow).

**Comment by hgilde** [comment]
hmm, link to the discussion about changing indexing behavior?

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/issues/15747

**Comment by jbrockmendel** [comment]
having spent most of the last couple days on the relevant code in ILoc._setitem_with_indexer, I lean towards "no".  figuring out when we need to do expansion is a PITA

**Comment by jreback** [comment]
even better we should deprecate this entirely

**Comment by mroeschke** [comment]
Sounds like generally we dont want to do this anymore. Closing
