### ISSUE TITLE
iterrows, itertuples, and using np.nditer for a new iterator?

### ISSUE THREAD

**Issue by apapanico** [pandas-dev/pandas#7958]
I'm building a simulation tool that essentially requires iterating through some fairly large DataFrames with iterrows (ie. the tool cannot be vectorized).  I've looked into converting it to Cython but I'm just not that skilled with Cython to make it work.  Also, I don't quite get why it's such a no-no to iterate on rows (other than it's slow) but for my purpose I have to since each row is a record in time.

However, I _did_ build my own iterator for the DataFrame using np.nditer that is a whole lot faster than iterrows and can give dict-like objects unlike itertuples.  Is there a desire for something like this?

**Comment by kidrahahjo** [comment]
I think this can be closed now!
