### ISSUE TITLE
ExcelFile.parse() does not return TextFileReader object, but rather a DataFrame

### ISSUE THREAD

**Issue by rkyleg** [pandas-dev/pandas#8011]
When specifying a chunksize during the ExcelFile.parse() method, I should be back an iterable object, but instead a DataFrame is returned. 

If you return just the TextParser (change parser.read() to just parser) in the code block below, then iterating over the parsed ExcelFile works and returns the specified number of chunks. 

The code block is taken from pandas.io.excel.py line 334

Hopefully I didn't make that confusing. 

``` python
parser = TextParser(data, header=header, index_col=index_col,
                            has_index_names=has_index_names,
                            na_values=na_values,
                            thousands=thousands,
                            parse_dates=parse_dates,
                            date_parser=date_parser,
                            skiprows=skiprows,
                            skip_footer=skip_footer,
                            chunksize=chunksize,
                            **kwds)
return parser.read()
```

**Comment by mroeschke** [comment]
Looks like TextParser doesn't exist anymore. And looks like there there isn't a complete, reproducible example. Happy to reopen if this issue gains more context
