### ISSUE TITLE
BUG/ENH: categorical returned during a transform

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#8065]
http://stackoverflow.com/questions/25372877/python-pandas-groupby-and-qcut-doesnt-work-in-0-14-1

```
df = pd.DataFrame({'x': np.random.rand(20), 'grp': ['a'] * 10 + ['b'] * 10})
```

worked in 0.13 (but returns a 2 element series with a list)

```
df.groupby('grp')['x'].transform(pd.qcut, 3)
```

much cleaner.

```
df.groupby('grp')['x'].apply(lambda x: pd.Series(pd.qcut(x,3), index=x.index))
```

**Comment by TomAugspurger** [comment]
This now returns an object series of Intervals (soon to be an IntervalArray).

I think the original issue is fixed.
