### ISSUE TITLE
BUG: improve error message for negative window argument to rolling_*()

### ISSUE THREAD

**Issue by seth-p** [pandas-dev/pandas#8072]
Currently (in v0.14.1) `rolling_mean(s, window=-1)` produces (the somewhat inelegant) error message `ValueError: min_periods must be >= 0`. It would be better to test explicitly for negative (non-positive?) `window`, and produce a more direct error message.

**Comment by dsm054** [comment]
This seems to work in current master, presumably as part of the window functions rewrite:

```
In [30]: pd.rolling_mean(df, window=-1) # yes, I know, deprecated
[...]
ValueError: window must be non-negative

In [31]: df.rolling(window=-1)
[...]
ValueError: window must be non-negative
```

The only thing which seems a little surprising to me is that we catch the negative window at construction but the negative min_periods at evaluation:

```
In [45]: df.rolling(window=1)
Out[45]: Rolling [window=1,center=False,axis=0]

In [46]: df.rolling(window=1, min_periods=-2)
Out[46]: Rolling [window=1,min_periods=-2,center=False,axis=0]

In [47]: df.rolling(window=1, min_periods=-2).sum()
[...]
ValueError: min_periods must be >= 0
```

but it's hard to get too worked up about that.

**Comment by jreback** [comment]
yeah min_periods is a function of the called function e.g. kurt,skew,var have different min values that sum/mean

**Comment by jreback** [comment]
closing as already fixed
