### ISSUE TITLE
Series of just None not converted to NaN 

### ISSUE THREAD

**Issue by hayd** [pandas-dev/pandas#8136]
I was a little surprised by this

```
In [11]: pd.Series([])
Out[11]: Series([], dtype: float64)

In [12]: pd.Series([None])  # should be NaN / float ?
Out[12]:
0    None
dtype: object

In [13]: pd.Series([None, 1])
Out[13]:
0   NaN
1     1
dtype: float64
```

**Comment by jorisvandenbossche** [comment]
We recently discussed this in https://github.com/pandas-dev/pandas/pull/13894, where we sort of decided to not change this at the moment. 
So closing this, although we should maybe reconsider this somewhere for pandas 2.0 how to handle 'None'.
