### ISSUE TITLE
BENCH: put in np.random.seed on vbenches

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#8144]
all of the groupby vbenches need a `np.random.seed(1234)` to make them consistent from run-to-run (where they don't have them now).

Possibly should do this on other benches as well.

**Comment by RafalSkolasinski** [comment]
I am working on that now

**Comment by RafalSkolasinski** [comment]
Ok, that looks like already handles. There is `np.random.seed(1234)` on `vbanches` and also new `asv_banches`.

**Comment by jreback** [comment]
need to remove any randoms from existing benchmarks, and ensure that they still run. E.g. we always want to use a single seed for the entire run (unless for some reason a benchmark uses a very specific seed)
