### ISSUE TITLE
Importing Datetime values from SQL Server with SQL Alchemy

### ISSUE THREAD

**Issue by oetcoleman** [pandas-dev/pandas#8156]
I'm using the following code to import datetimes from a SQL Server database into Pandas:
`data = pd.read_sql('select top 10 timestamp from mytable',db)`
'MyTable' contains a column 'Timestamp', which is of type DateTime2.

If `db` is a pyodbc database connection this works fine, and my timestamps are returned as data type 'datetime64[ns]'. However if `db` an SQL Alchemy engine created using `create_engine('mssql+pyodbc://...')` then the timestamps returned in data are of type 'object' and cause problems later on in my code.

I'm using pandas version 0.14.1, pyodbc version 3.0.7 and SQL alchemy version 0.9.4. I'd like the default behaviour with the SQL Alchemy engine to be the same as pyodbc, i.e. to import all datetimes as datetime64[ns].

Originally from: http://stackoverflow.com/questions/25607775/datetime-import-using-pandas-sqlalchemy

**Comment by TomAugspurger** [comment]
Closing, though improvements to the docs are always welcome.
