### ISSUE TITLE
DOC: {Series,DataFrame}.dot() not listed under API Reference

### ISSUE THREAD

**Issue by seth-p** [pandas-dev/pandas#8163]
Any reason `{Series,DataFrame}.dot()` are not listed under http://pandas.pydata.org/pandas-docs/stable/api.html?

They are documented:
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.dot.html
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.dot.html

**Comment by jorisvandenbossche** [comment]
There are listed now.
