### ISSUE TITLE
Passing a dictionary of columns names and colors 

### ISSUE THREAD

**Issue by DataSwede** [pandas-dev/pandas#8193]
Related to this question:

http://stackoverflow.com/questions/25689558/pandas-bar-plot-specify-bar-color-by-column

Having the ability to natively pass in a dictionary of the column names and the desired color could be a nice addition to simplify specifying what color you want each line/bar to be.

**Comment by mattayes** [comment]
+1

**Comment by sinhrks** [comment]
I thinks this is not difficult, as ``style`` kw already accepts ``dict``. PR is welcome:)

**Comment by TomAugspurger** [comment]
@DataSwede could you update the original post with a small example (just two columns) and the desired behavior? Maybe a unit test?

**Comment by Leostayner** [comment]
Can we work on this issue?
@elisamalzoni
