### ISSUE TITLE
pandas.stats.ols.MovingOLS._calc_betas incompatibility issue with newer numpy

### ISSUE THREAD

**Issue by wangshun98** [pandas-dev/pandas#8243]
numpy version 1.8.2
pandas version 0.14.1

In pandas/stats/ols.py:821, we have:
        mask = -np.isnan(betas).any(axis=1)

This causes problem with newer numpy which deprecated negative unary operator (-) on boolean arrays. I got this following error when running into this line:
DeprecationWarning: numpy boolean negative (the unary `-` operator) is deprecated, use the bitwise_xor (the `^` operator) or the logical_xor function instead.

When I change "-" to "~", the problem goes away. It's minor, but hope we can incorporate this into next pandas update.  Thanks.

**Comment by Ludovicus** [comment]
Just saw this in 0.16.2 .   I'll do a pull request for this shortly.

**Comment by mroeschke** [comment]
I believe this issue can be closed from this PR. 
https://github.com/pandas-dev/pandas/commit/2113672040a884e8a3b18881e9608fed795e1129#diff-1e25b8d60d53005c3c7cb6612f2b41a6

**Comment by jreback** [comment]
yep
