### ISSUE TITLE
CLN/TST: move consoliate sort_index to core/generic.py

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#8283]
xref #8282
xref #8239 (this issue won't touch the API per se)

expand extend: `core/generic.py/NDFrame.sort_index`: https://github.com/pydata/pandas/blob/master/pandas/core/generic.py#L1606

with the frame version.
https://github.com/pydata/pandas/blob/master/pandas/core/frame.py#L2689

needs generic docs (e.g. look how reindex is done)

as prob best to start with the frame version that handles ndim=2. Need tests for added capabilities to Series/Panel, e.g. mainly supporting sort_index on a multi-level index.

**Comment by chrisaycock** [comment]
`DataFrame.sort_index()` has a deprecated `by` parameter. This parameter doesn't even exist in `Series` or `NDFrame`. Is it ok to just remove this altogether?

**Comment by jreback** [comment]
so what you can do is provide the impl in ``core/generic.py``, then for ``DataFrame`` provide the current signature (with the by depr message as is), and just call super.
