### ISSUE TITLE
ENH: allow axis argument to append / move append code to generic.py

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#8295]
http://stackoverflow.com/questions/25896241/creating-columns-dynamically-assigning-them-a-constant-row-vector/25896504#25896504

e.g. 

Instead of 
`pd.concat([df,DataFrame([[1,2,3,4]],columns=list('ABCD'),index=df.index)],axis=1)`

allow as a convience feature
`df.append(DataFrame([[1,2,3,4]],columns=list('ABCD'),index=df.index),axis=1)`

**Comment by TomAugspurger** [comment]
Closing.

This would have confusing performance implications, as appending to the columns is cheap, but appending to rows is expensive.
