### ISSUE TITLE
categorical fixup 3

### ISSUE THREAD

**Issue by jankatins** [pandas-dev/pandas#8375]
- [ ] check that plot does the right thing, i.e. ordering of the categories 
- [ ] Make a utils.testing.makeCategorical() `Series(np.array(list('abcdefghij')).take(np.random.randint(0,10,size=len(df)))).astype('category')` + NaN + type + size + unique kword? 
- [ ] check for `self.values.xxx` in `Series` and check that the methods using such call work when values is a `Categorical`. See https://github.com/pydata/pandas/pull/7447
- [ ] Apply and Categoricals: https://github.com/pydata/pandas/issues/8065
- [ ] Categorical.searchsorted() #8420
- [x] docs: "[...] number of possible values (categories; -categories-+levels+ in R). " https://github.com/pydata/pandas/pull/8561
- [x] move assert_categorical_equal to testing.py and fix "categories" failure msg
- [x] check whatsnew: In the note change "levels" to "categories" and `s/Schultz/Schulz/`
- [x]  docstring in #8077 (comment)
- [x] add a link to "comparison with R" section from http://pandas-docs.github.io/pandas-docs-travis/comparison_with_r.html 
- [x] check that the memory info is doing the right thing for categorical (https://github.com/pydata/pandas/pull/7619)

**Comment by TomAugspurger** [comment]
Most of these have been addressed / aren't a priority now.
