### ISSUE TITLE
TST: Remove skip for mpl 1.5 / current dev

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#8402]
Follow up to https://github.com/pydata/pandas/pull/8398

This can be done now.

Remove https://github.com/pandas-dev/pandas/blob/30eb48cc485bb7c7c47a4e7e26f87e469fbd8b8a/pandas/tests/plotting/test_boxplot_method.py#L24-L31

and its use in

https://github.com/pandas-dev/pandas/blob/30eb48cc485bb7c7c47a4e7e26f87e469fbd8b8a/pandas/tests/plotting/test_boxplot_method.py#L158

Keep an eye on https://github.com/matplotlib/matplotlib/pull/3571 and https://github.com/matplotlib/matplotlib/issues/3544
- [x] Number of fliers (https://github.com/pydata/pandas/pull/8429)
- [ ] Empty col / all NaN

**Comment by jreback** [comment]
this code has been removed as we now require mpl > 2

@TomAugspurger anything left in this issue?

**Comment by TomAugspurger** [comment]
Should be good.
