### ISSUE TITLE
date_range treats '.5s' as '5s'

### ISSUE THREAD

**Issue by keszybz** [pandas-dev/pandas#8419]
I'm new to pandas, so maybe I'm missing something, but I'd expected freq='.5s' to give me 500ms intervals, not 5s intervals:

> > > pd.date_range(0, periods=5, freq='.5s')[1]
> > > Timestamp('1970-01-01 00:00:05', offset='5S')
> > > pd.date_range(0, periods=5, freq='500ms')[1]
> > > Timestamp('1970-01-01 00:00:00.500000', offset='500L')
> > > pd.**version**
> > > '0.14.1'
> > > import sys; sys.version
> > > '3.4.1 (default, Jul  6 2014, 20:01:46) \n[GCC 4.9.0]'

Behaviour is the same under Python 2 and 3.

**Comment by sinhrks** [comment]
I think fix should be 2 parts:

#### 1. ``offsets.Tick`` support fraction

Currently, ``Tick`` and ``DateOffset`` coerces input to ``int`` implicitly. I think ``Tick`` can return smaller tick to based on fraction, and ``DateOffset`` should explicitly raise.

```
pd.tseries.offsets.Hour(0.5)
# <0 * Hours>

pd.tseries.offsets.MonthEnd(0.5)
# <0 * MonthEnds>
```

#### 2. ``to_offset`` support fraction

After ``Tick`` support fraction, it can be done with a slight change of regex.
