### ISSUE TITLE
BUG: groupby.first/last with nans

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#8427]
This is incorrect, as this is applied column by column (as they are different dtypes)
so `_first_compat` should first compute the mask then use it.

from [SO](http://stackoverflow.com/questions/26108181/selecting-first-row-with-groupby-and-nan-columns)

```
In [18]: df = pd.DataFrame([{'id':"a",'val':np.nan, 'val2':-1},{'id':"a",'val':'TREE','val2':15}])

In [19]: df
Out[19]: 
  id   val  val2
0  a   NaN    -1
1  a  TREE    15

In [20]: df.groupby('id').first()
Out[20]: 
     val  val2
id            
a   TREE    -1
```

**Comment by TomAugspurger** [comment]
So the documented behavior of Groupby.first / Groupby.last is the first / last non-NA value? Anything to do here?

**Comment by WillAyd** [comment]
There's some inconsistency between `first` and `nth(0)` that needs to be addressed here:

```python
In [10]: df.groupby('id').nth(0)
Out[10]: 
    val  val2
id           
a   NaN    -1
```

**Comment by rhshadrach** [comment]
@WillAyd - first is designed to work column by column whereas nth selects a single row. So it seems to me this inconsistency is purposeful (but agree it's confusing).

To me an ideal solution would allow a user to

 - get the nth value, either selecting a single row or column-by-column (note: this is different than using axis=1 in the grouby(...) call)
 - first/last as a shortcut for nth(0) and nth(-1) as these are very common, again by either selecting a single row or column-by-column

If we had this, then it'd be best to align nth/first so the default behavior of nth(0) is the same as first, and similarly with last.

**Comment by WillAyd** [comment]
I think your second bullet feels right, and might have the added bonus of simplifying our code paths

**Comment by NumberPiOso** [comment]
take

**Comment by NumberPiOso** [comment]
@rhshadrach , I understand that modifying _first_ and _last_ methods to point to _nth_ would be the way to go. This would cause this behaviour.

```
In [10]: df.groupby('id').nth(0)
Out[10]: 
    val  val2
id           
a   NaN    -1

In [10]: df.groupby('id').first()
Out[10]: 
    val  val2
id           
a   NaN    -1
```

Then, we would include another parameter to decide if it is the nth value by row or column-by-column.

**Comment by rhshadrach** [comment]
@NumberPiOso - Certainly we should include the parameter first if going that route before changing the default behavior of first/last. However, I do not feel certain that is the correct approach. I would have to guess that first/last are common operations, at least more so than nth. Is changing the default of first to mean "first row" more useful than "first value in each column"? That is very unclear to me. It's at this point that I wonder if changing the behavior here is more disruptive than helpful.

As a tangential aside, I've always found treating nans differently in first/last/etc more surprising than beneficial, but perhaps that's just my use case. However this is pretty consistent across pandas and I certainly don't find it sever enough to merit a change to the default behavior (or at the very least, merit me arguing for a change!).

**Comment by NumberPiOso** [comment]
This is true.
As a user, I tend to use _first_ and _last_ a lot more than _nth_ and by themselves each one of this methods are consistent. So I would not change the methods either.
