### ISSUE TITLE
DOC: boxplot docs do not explain what the plot shows at all

### ISSUE THREAD

**Issue by keszybz** [pandas-dev/pandas#8447]
Extensive documentation is probably not needed, but at a minimum, the docstring should say
- what the red line is (median)
- what the box shows (quartiles)
- what the whiskers show (?)
- by what rules the outliers are shown or not

A link to wikipedia and/or matplotlib docs would be nice too.

I could try to contribute this, if it is deemed useful.

**Comment by Tych0n** [comment]
Hi! Do whiskers show +-1.5IQ? Cause i have asymmetrical whiskers:
![figure_1](https://user-images.githubusercontent.com/3283584/35152914-617bf8cc-fd35-11e7-9dcd-aff6c0a582cd.png)

**Comment by TomAugspurger** [comment]
A link to https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.boxplot.html#matplotlib-axes-axes-boxplot would explain that the whiskers show:

> In other words, where IQR is the interquartile range (Q3-Q1), the upper whisker will extend to last datum less than Q3 + whis*IQR). Similarly, the lower whisker will extend to the first datum greater than Q1 - whis*IQR.

**Comment by jorisvandenbossche** [comment]
Closed by #20152
