### ISSUE TITLE
CI: Add durations to tests

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#8450]
https://docs.pytest.org/en/latest/usage.html#profiling-test-execution-duration

Can add `--durations=10` or something to list the 10 slowest tests.

We could add this to our setup.cfg so it's used by default.

**Comment by jreback** [comment]
i think this is still worth doing to see if we have any long tests that are too long

**Comment by TomAugspurger** [comment]
We have durations now: https://travis-ci.org/pandas-dev/pandas/jobs/446018323#L2867

Right now it's hardcoded in `addopts` of `setup.cfg`. We may want to move it to the actual test scripts, so that it doesn't show up under, e.g. the doctests.
