### ISSUE TITLE
PeriodIndex cannot infer frequency in cases where Period can

### ISSUE THREAD

**Issue by diogocp** [pandas-dev/pandas#8466]
xref #6771

> Period("2000-01")
> Period('2000-01', 'M')
> 
> PeriodIndex(["2000-01"])
> ValueError: freq not specified and cannot be inferred from first element

Same problem with 2000-Jan and Jan-2000. Works fine if I pass freq="M".

**Comment by TomAugspurger** [comment]
> You have to do full subtractions, then it STILL may be ambiguous.

This seems very fragile... I think we'll close this, unless someone can provide a clear example and proposed API.
