### ISSUE TITLE
Zero counts in Series.value_counts for categoricals

### ISSUE THREAD

**Issue by fkaufer** [pandas-dev/pandas#8559]
`Series.value_counts()` also shows categories with count 0.

Thought this would be a bug but according to [doc](http://pandas.pydata.org/pandas-docs/version/0.15.0/categorical.html#operations) it is intentional.

This makes the output of value_counts inconsistent when switching between category and non-category dtype. Apart from that it blows up the value_counts output for series with many categories.

I would prefer to hide counts (i.e. zero) for non-occuring categories by default and rather consider a parameter `dropzero=True` similar to `dropna` (see also #5569).

**Comment by jreback** [comment]
@JanSchulz can you revisit. See what we need from this issue.

**Comment by quantumds** [comment]
I believe that the output of value_counts when applied to categorical variables, shouldn't print values that are inexistent/not assigned for that variable in the current dataframe. This issue would benefit a lot Pandas users in data Analysis. Do we have an estimation of when this improvement will be included? Thanks!

**Comment by wesm** [comment]
In the absence of clear guidance about whether to change anything, I'm closing this as Won't Fix.

Note: R maintains the empty categories when tabulating factor counts

```
> values <- c(1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4)
> values
 [1] 1 1 1 2 2 2 3 3 3 4 4 4
> values <- factor(values)
> values
 [1] 1 1 1 2 2 2 3 3 3 4 4 4
Levels: 1 2 3 4
> values == 2
 [1] FALSE FALSE FALSE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE
> (values == 2) | (values == 4)
 [1] FALSE FALSE FALSE  TRUE  TRUE  TRUE FALSE FALSE FALSE  TRUE  TRUE  TRUE
> values[(values == 2) | (values == 4)]
[1] 2 2 2 4 4 4
Levels: 1 2 3 4
> values2 <- values[(values == 2) | (values == 4)]
> values2
[1] 2 2 2 4 4 4
Levels: 1 2 3 4
> table(values2)
values2
1 2 3 4 
0 3 0 3 
```

**Comment by codenigma1** [comment]
> ```python
> s = pd.Series(['a','b','a','c','d','c'])
> count_str = s[s.isin(['a','u'])].value_counts()
> count_cat = s.astype('category')[s.isin(['a','u'])].value_counts()
> ```
> 
> ```
> count_str
> a    2
> ```
> 
> ```
> count_cat
> a    2
> d    0
> c    0
> b    0
> ```
> 
> ```
> assert count_str==count_cat
> ...
> ValueError: Series lengths must match to compare
> ```

we can avoid the series zero by simply : `series[series!=0] ` or `series[series > 0]`

**Comment by NumberPiOso** [comment]
In case anyone is reading this issue 8 years later...

You should follow https://github.com/pandas-dev/pandas/issues/14942 and https://github.com/pandas-dev/pandas/pull/20583

The default behavior of _value_counts_ and _group_by_ changed.

**Comment by crypdick** [comment]
also necroposting... if you need to drop categoricals with zero counts, do

`df.col_name = df.col_name.cat.remove_unused_categories()`
