### ISSUE TITLE
ENH: Use multiindex levels for function arguments in apply

### ISSUE THREAD

**Issue by toddrjen** [pandas-dev/pandas#8574]
Currently it is easy to apply functions to the data in a row or column using apply.  However, when important parameters for the analysis is contained in the multiindex for the row or column being analyzed (that is, the column index when analyzing along a column or the row index when analyzing along a row), there is currently no easy way to make use of these parameters.  

I think it would be useful if users could provide a dictionary that maps index levels to function arguments to use when applying a function to a pandas Series, DataFrame, Panel, or Grouper.

Some specific examples:
1. One of the multiindex levels is sampling frequency, which varies across rows.  You want to do the fft of each row, but you need the sampling frequency for that.
2. One of the multiindex levels is the total duration of each recording, and you want to do a count of events per unit of time.
3. Each element is a time point.  One of the multiindex levels is the minimum allow of the recording and another is the stop time, and you want to slice the results to only include values between the start and stop.

These are all easy if the values are the same for all rows or columns, but become much harder currently if they vary.

**Comment by tetmin** [comment]
I've been searching and haven't found any new functionality which would achieve what was originally requested. I'm having the same problem as @toddrjen but need to use the second approach since referencing names by their level name (not integer index) is an essential requirement:

`df.apply(lambda x: x.clip(x.name['t_start'],x.name['t_stop']))`

Unfortunately, it seems that pandas Series objects drops level names & just flattens their values into a tuple. What would be the potential implications of transitioning to a NamedTuple?

**Comment by jreback** [comment]
@tetmin you would have to show a more concrete example.

**Comment by tetmin** [comment]
Sure, let's say I have a DataFrame where each column is a time series, i'm storing metadata for each time series as a column MultiIndex, e.g. country, lag, series name etc. I want to apply a shift to each column depending on the value stored at a certain MultiIndex level e.g. imagine 'lag' is level 5, I can do the following:

`df.apply(lambda x: x.shift(-x.name[5]))`

This works, but now imagine I drop one of my index levels, or come along with data which has more/fewer metadata levels, 5 is no longer appropriate, I need to index by the name of the level as you can with a DataFrame. I could do the following, but this seems like an extremely ugly solution to me:

```
labels = df.columns.names
mapper = dict(zip(labels, range(len(labels))))
df.apply(lambda x: x.shift(-x.name[mapper['lag']]))
```

**Comment by jreback** [comment]
@tetmin can you give an actual (mini) example, e.g. construct a frame programatically.

**Comment by wesm** [comment]
Closing as this issue is underspecified. PRs or concrete proposal how to fix welcome
