### ISSUE TITLE
API: cut interval formatting

### ISSUE THREAD

**Issue by fancychildren** [pandas-dev/pandas#8595]
it would be nice to have number in front of all labels. put number like 00, 01, 02 in front of labels so that it would order appropriately.

Lib\site-packages\pandas\tools\tile.py

```
def _format_levels(bins, prec, right=True,
                   include_lowest=False):
    fmt = lambda v: _format_label(v, precision=prec)
    cnter=0
    if right:
        levels = []
        for a, b in zip(bins, bins[1:]):
            fa, fb = fmt(a), fmt(b)

            if a != b and fa == fb:
                raise ValueError('precision too low')

            formatted = '%02d: (%s, %s]' % (cnter, fa, fb)
            cnter=cnter +1
            levels.append(formatted)

        if include_lowest:
            levels[0] = '[' + levels[0][1:]
    else:
        levels = ['[%s, %s)' % (fmt(a), fmt(b))
                  for a, b in zip(bins, bins[1:])]

    return levels
```

**Comment by 8one6** [comment]
I'd offer one potential direction to go with this.  I think it would be great to find a way to allow users to specify the formatting of the bin labels returned by `cut`.  As things stand now, I need to call `cut` twice to get the result I want.  First I call `cut` to find the bin edges.  Then I format the bin edges into appropriately formatted labels.  Then finally I call `cut` again specifying the `labels` parameter.

One approach would be to allow `labels` to take a function as its argument.  If it does, then it could be presumed to accept the list of bin edges and return a list of bin labels.  Or, alternatively, the function could expect the lower and upper limits of a bin and return the label for that bin.

Here's the situation I've got in mind:

```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

np.random.seed(0)
x = pd.DataFrame(np.random.rand(1000, 2) * 10, columns=list('xy'))
df['y'] = (df['x'] * 3) + 5 + np.random.randn(1000) * 2
df['x_bin'], edges = pd.cut(df['x'], bins=5, retbins=True)
nice_names = ['{b:0.1f} : {t:0.1f}'.format(b=edges[i], t=edges[i+1]) for i in range(len(edges)-1)]
df['x_bin_better'] = pd.cut(df['x'], bins=5, labels=nice_names)

fig, axes = plt.subplots(3, 1, figsize=(10, 10))
axes[0].plot(df['x'], df['y'], linestyle='None', marker='o', mew=1, alpha=0.25)
sns.violinplot('x_bin', 'y', data=df, ax=axes[1], palette='Blues')
sns.violinplot('x_bin_better', 'y', data=df, ax=axes[2], palette='Reds')
fig.tight_layout()
```

![image](https://cloud.githubusercontent.com/assets/4360170/11282759/fcb39246-8ece-11e5-8fe0-d86a5f7a3f1b.png)

**Comment by jreback** [comment]
this is pretty much solved by #7640 when ``pd.cut`` will return an ``IntervalIndex`` which can then be easily formatted. :pushpin: to @shoyer

**Comment by 8one6** [comment]
Would you be open to accepting a pull request for adding the ability for `labels` to accept a function while we wait for `IntervalIndex` to be fleshed out?  If so, do you prefer the function operate on the list of endpoints or on a pair of endpoints?

**Comment by jreback** [comment]
sure

I would have a 2 arg callable returning a string

**Comment by shoyer** [comment]
Yeah, I like the idea of accepting a function that acts on scalars for the left and right bounds. Eventually we could add this option as a method on IntervalIndex.

**Comment by wesm** [comment]
Now that `pd.cut` returns Categorical this can be resolved
