### ISSUE TITLE
API/PERF: add a performance string-object memory computation

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#8600]
xref #8599, #8578 

allow a nice UX and a more correct estimate of memory usage for object (string) columns
prob will require a cythonized evaluation

this would replace the need for the '+' on object dtypes for mem usage

**Comment by mroeschke** [comment]
I think my moving to pyarrow for string ops this becomes irrelevant. Closing but happy to reopen if i misunderstodd
