### ISSUE TITLE
API/ENH: add support for integer NA with dynd-python dep

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#8643]
this should actually be relatively straightforward.

Incorporating this library: https://github.com/libdydn/dynd-python
as an optional dep, allows native Integer NA support (implemented
very similarly to how NaT is represented in `datetime64[ns]` dtypes ATM.

`dynd-python` are the python bindings for `libdynd` and have an almost 100% numpy
compatibility (they use the buffer interface so should be perf-wise pretty costless to do this).

tangentially related to #8350 

cc @mwiebe 
cc @shoyer
cc @jorisvandenbossche 
cc @cpcloud

**Comment by datnamer** [comment]
Is this still planned?

**Comment by jreback** [comment]
at some point

**Comment by jorisvandenbossche** [comment]
@jreback  Let's close this issue in favor of discussions in the pandas2 repo?
