### ISSUE TITLE
df.info() ignores index hashtable memory usage

### ISSUE THREAD

**Issue by kay1793** [pandas-dev/pandas#8775]
another problem with memory report (#7619) in df.info() like #8578 (locked) and fix to multindex hidden in #8456 (see [whatsnew](http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#enhancements)). it count the space used by index hashtable. for each entry the klib hashtable keeps a copy of the index data as well as a key. for strings that is a copy of the string + pointer.  in worst case there is `2*next_power_of_2(len(index))` entries and problem exists whatever dtype the index use.

```
x.index._engine.mapping
Out[13]: <pandas.hashtable.PyObjectHashTable at 0x7fb92f32bef0>
```

cc @shoyer, @njsmith
cc @asobrien

**Comment by TomAugspurger** [comment]
@jreback was this closed by https://github.com/pandas-dev/pandas/pull/15237?

**Comment by jreback** [comment]
yep
