### ISSUE TITLE
ENH: Add Series.to_list, alias for tolist

### ISSUE THREAD

**Issue by scls19fr** [pandas-dev/pandas#8826]
Hello,

IPython autocomplete (tab) shows

```
In [1]: ts.to
ts.to_clipboard  ts.to_frame      ts.to_period     ts.to_string
ts.to_csv        ts.to_hdf        ts.to_pickle     ts.to_timestamp
ts.to_dense      ts.to_json       ts.to_sparse     ts.tolist
ts.to_dict       ts.to_msgpack    ts.to_sql
```

maybe `tolist` should be named `to_list`
and `tolist` should be marked as deprecated
because it seems that other methods follow
an implicit naming convention (`to_...`) . 

Kind regards

**Comment by gagejustins** [comment]
Hey would y'all be cool if I work on this? Would be my first contribution
