### ISSUE TITLE
Inconsistent behavior when accessing None value

### ISSUE THREAD

**Issue by jorenvs** [pandas-dev/pandas#8871]
I'm working with OpenStreetMap data queried from a postgresql database. When I extract one row and try to access the name column, the resulting value is inconsistent based on the access method:

the row:

```
osm_id                 1895277228
name                         None
admin_level                    -1
leisure                      None
building                     None
brand                       Total
operator                     None
amenity                      fuel
shop                         None
sport                        None
aeroway                      None
office                       None
public_transport             None
railway                      None
tourism                      None
```

Then using the dot-attribute way (poi.name) returns value 0, while (poi["name"]) returns the original None value. This behavior is not happening with other columns.

**Comment by mroeschke** [comment]
Closing as a stale usage question
