### ISSUE TITLE
ERR: bytes partially converted with convert_objects(convert_numeric=True)

### ISSUE THREAD

**Issue by arijun** [pandas-dev/pandas#8873]
If you have a series of binary strings containing numbers in a DataFrame, if you try to convert it using `convert_objects`, the first will show up as `NaN`.

```
In [3]: df = pd.DataFrame([b'1',b'1'])

In [4]: df.convert_objects(convert_numeric=True)
Out[4]: 
    0
0 NaN
1   1
```

Python 3, obviously; happens on Windows and Linux.

**Comment by mroeschke** [comment]
`convert_objects` has been removed. Closing
