### ISSUE TITLE
API: Index should support __inverse__ ops

### ISSUE THREAD

**Issue by sinhrks** [pandas-dev/pandas#8875]
-  [ ] Add `__inverse__` to Index.
- [x] Change duplicated to return np.array (PR #9112) 

Related to #7979

Because `Index` is no more the subclass of `np.array`,  `Index.duplicated` returns `Index` with `dtype=object`. And `Index` don't accepts logical not.

```
idx = pd.Index([1, 2, 1, 3])

idx.duplicated()
# Index([False, False, True, False], dtype='object')

~idx.duplicated()
# TypeError: bad operand type for unary ~: 'Index'
```

As a result, it is impossible to drop data which have duplicated index using expression like `df[~df.index.duplicated()]`. This expression was worked at the timing of #7979.

Does `Index.duplicated` should return `np.array` with `dtype=bool`? Or `Index` should accept logical not?

**Comment by mroeschke** [comment]
This look to work on master now. Could use a test for the `inverse` behavior

```
In [2]: idx = pd.Index([1, 2, 1, 3])
   ...:
   ...: idx.duplicated()
Out[2]: array([False, False,  True, False])

In [3]: ~idx.duplicated()
Out[3]: array([ True,  True, False,  True])

In [4]: pd.__version__
Out[4]: '1.1.0.dev0+1466.ga3477c769.dirty'
```

**Comment by simonjayhawkins** [comment]
> This look to work on master now. Could use a test for the `inverse` behavior

see https://github.com/pandas-dev/pandas/issues/8875#issuecomment-64796203

Index.duplicated() has been changed to return an array, but the other part of the issue is to add \_inverse_ to Index. This has not yet been done.

```
>>> pd.__version__
'1.1.0.dev0+1748.g0bd1f6f6f'
>>>
>>> idx = pd.Index([1, 2, 1, 3])
>>>
>>> pd.Index(idx.duplicated())
Index([False, False, True, False], dtype='object')
>>>
>>> ~pd.Index(idx.duplicated())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: bad operand type for unary ~: 'Index'
>>>
```

**Comment by YuRenee** [comment]
take
