### ISSUE TITLE
PERF/API/BUG: index memory not releasing when manipulated by numpy functions

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#8880]
http://stackoverflow.com/questions/27074469/memory-leak-in-python-pandas-reshuffling-index

```
In [1]: df = DataFrame(np.random.randn(10000))

In [2]: def f(df):
   ...:     for dfi in np.array_split(df,100):
   ...:         shuffle = dfi.reindex(np.random.permutation(dfi.index))
   ...:         one = shuffle.iloc[:50]
   ...:         two = shuffle.iloc[50:]
```

so the `np.random.permutation` seems to be shuffling the index in a weird way
this doesn't leak with `dfi.index.values`

**Comment by mroeschke** [comment]
Don't see this on main anymore so it must have been fixed. Closing
