### ISSUE TITLE
shouldn't mangle_dupe_cols add an underscore rather than a dot in read_csv?

### ISSUE THREAD

**Issue by mbakker7** [pandas-dev/pandas#8908]
When I use read_csv to read a file which has columns with the same name, the names are amended with .1, .2, etc, when mangle_dupe_cols=True in read_csv.

Wouldn't it make more sense to amend them as _1, _2, etc., so that columns of a dataframe can still be accessed with the dot syntax: df.name_1 works fine, but df.name.1 doesn't work.

Just a suggestion,

Mark

**Comment by phofl** [comment]
Closing here, the argument is gone and I don't think that we can or should change the default
