### ISSUE TITLE
TST/BUG: Improve error handling when parsing iso 8601 strings

### ISSUE THREAD

**Issue by broessli** [pandas-dev/pandas#8910]
xref #8832 

Parsing of datetime strings ending with `Z0`or `Z00`should raise (this is currently only the case with `Z0`).
This is due to the fact that the parser in `np_datetime_strings.c` cannot raise its own errors since in tslib.pyx, function convert_ts_tsobject(), any ValueError is catched and then a fallback external parser (dateutil) is called.

**Comment by jorisvandenbossche** [comment]
I currently get a clear error message that the string cannot be converted:

```
In [16]: pd.Timestamp('2014-11-02 01:00Z')
Out[16]: Timestamp('2014-11-02 01:00:00+0000', tz='UTC')

In [17]: pd.Timestamp('2014-11-02 01:00Z00')
---------------------------------------------------------------------------
...
ValueError: Unable to parse b'2014-11-02 01:00Z00'

During handling of the above exception, another exception occurred:
...
ValueError: Unknown string format

During handling of the above exception, another exception occurred:
...
ValueError: could not convert string to Timestamp
```

What is the desired improvement in this issue? (possibly that it also has changed since reporting)
