### ISSUE TITLE
Timestamp.tz_localize() NonExistentTimeError handling

### ISSUE THREAD

**Issue by mskrajnowski** [pandas-dev/pandas#8917]
I'm trying to use pandas to speed up timezone conversions on many datetimes and I can't get around `NonExistentTimeErrors`. Pandas `tz_localize()` seems to ignore the `ambiguous` argument for the non existent time case.

Example:

``` python
import pytz
import pandas

tz = pytz.timezone('Europe/Warsaw')
non_existent = datetime.datetime(2015, 3, 29, 2, 30)

tz.normalize(tz.localize(non_existent))
#2015-03-29 03:30:00+02:00

tz.normalize(tz.localize(non_existent, is_dst=False))
#2015-03-29 03:30:00+02:00

pandas.Timestamp(non_existent).tz_localize(tz)
# NonExistentTimeError: 2015-03-29 02:30:00

pandas.Timestamp(non_existent).tz_localize(tz, ambiguous=0)
# NonExistentTimeError: 2015-03-29 02:30:00
```

It would be nice if the `ambiguous` argument worked the same as `is_dst` in pytz. As it is now, it's impossible afaik to reliably localize a series of datetimes using pandas, since any of them might cause a `NonExistentTimeError` and there's no way of guiding pandas what to do with such datetimes.

```
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.5.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-39-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.15.1
nose: 1.3.4
Cython: None
numpy: 1.9.1
scipy: None
statsmodels: None
IPython: 2.3.1
sphinx: 1.2.2
patsy: None
dateutil: 2.2
pytz: 2013.9
bottleneck: None
tables: None
numexpr: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: 0.9
apiclient: 1.3.1
rpy2: None
sqlalchemy: None
pymysql: None
psycopg2: 2.5.4 (dt dec pq3 ext)
```

**Comment by esvhd** [comment]
Hi guys - Was this released in 0.20.2 yet? I'm seeing the same problem here.
thanks.

**Comment by jorisvandenbossche** [comment]
This issue is still open, so no, this has not been fixed in 0.20.2. Contributions are welcome.

**Comment by randomgambit** [comment]
@jorisvandenbossche @esvhd same problem here. Got some timestamps in central time, and try to localize in EST give me this error. Is there a quick and dirty fix for that? Thanks!

**Comment by rockg** [comment]
There should be nothing wrong converting to EST as that does not have DST offsets.  Can you post your example?

```
In [10]: ts = pd.Timestamp("2017-03-12 02:30")

In [11]: ts.tz_localize("EST")
Out[11]: Timestamp('2017-03-12 02:30:00-0500', tz='EST')
```

**Comment by randomgambit** [comment]
@rockg No I mean I convert from Central time to EST.

`df.timestamp.map(lambda x: x.tz_localize('US/Central', ambiguous = 'NaT').tz_convert('US/Eastern').tz_localize(None))`

**Comment by randomgambit** [comment]
@jorisvandenbossche @mskrajnowski woud this be the `pytz`- equivalent (and correct) way to convert from `US/Central` to `US/Eastern` in a Pandas dataframe? 

Assume `df.timestamp` is a naive `pd.to_datetime()` timestamp
 

```
import pytz

tz_est = pytz.timezone('US/Eastern')
tz_central = pytz.timezone('US/Central')

df.timestamp.map(lambda x: tz_central.localize(x).astimezone(tz_est))
```

**Comment by randomgambit** [comment]
@jorisvandenbossche @mskrajnowski @rockg any ideas? sorry for the spam but this is an important question in my humble opinion :D

**Comment by carlotardivo** [comment]
Inside the generate_dates pandas date_range is called (for example with arguments:  start = 2019-01-31 00:00:00+01:00, end= 2021-12-01 00:00:00+01:00, freq='M'). The date 2021-10-31 00:00:00+02:00 is then generated as one of the other month ends. Everything is localized to Europe/Rome.
At a certain point something similar to this must happen:
```python
(
    pd.Timestamp('2021-10-31 00:00:00', tz='Europe/Rome')
    .tz_localize(None)   # -> '2021-10-31 00:00:00' naive
    .tz_localize('UTC')  # ->  '2021-10-31 00:00:00' UTC
    .tz_convert('Europe/Rome')  # '2021-10-31 00:02:00' Europe/Rome
    .tz_localize(None)  # '2021-10-31 00:02:00' naive
    .tz_localize('Europe/Rome')  # ERROR: this datetime is ambiguous
)
```
why / when is this happening??
