### ISSUE TITLE
FrozenNDArray cannot repr scalars

### ISSUE THREAD

**Issue by behzadnouri** [pandas-dev/pandas#9031]
on master:

```
>>> from pandas.core.base import FrozenNDArray
>>> a = FrozenNDArray(1)
>>> a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/pandas-0.15.1_192_g7bd1b24-py3.4-linux-x86_64.egg/pandas/core/base.py", line 65, in __repr__
    return str(self)
  File "/usr/lib/python3.4/site-packages/pandas-0.15.1_192_g7bd1b24-py3.4-linux-x86_64.egg/pandas/core/base.py", line 44, in __str__
    return self.__unicode__()
  File "/usr/lib/python3.4/site-packages/pandas-0.15.1_192_g7bd1b24-py3.4-linux-x86_64.egg/pandas/core/base.py", line 268, in __unicode__
...
...
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

keeps going back and forth between `__str__` and `__unicode__`. a workaround would be to change `self` on [this line](https://github.com/pydata/pandas/blob/e51eb9eca56f31055309d83c592cbefa4a14e42c/pandas/core/base.py#L267) to `self if self.ndim else self.item()`.

I ran into this bug while taking `.max` on the array:

```
>>> xs
FrozenNDArray([1, 2, 3], dtype='int64')
>>> xs.max()
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

it is kind of unusual to me that here `.max` returns a zero dimensional array, whereas numpy returns a scalar:

```
>>> xs
FrozenNDArray([1, 2, 3], dtype='int64')
>>> type(xs.max())
<class 'pandas.core.base.FrozenNDArray'>
>>> type(np.array([1, 2, 3]).max())
<class 'numpy.int64'>
```

in particular, `np.isscalar` returns differently for the two:

```
>>> np.isscalar(np.array([1, 2, 3]).max())
True
>>> np.isscalar(FrozenNDArray([1, 2, 3]).max())
False
```

**Comment by dsm054** [comment]
Can we yank FrozenNDArray now, then?  I guess we'd need to make sure that pickles would still work, but apart from that, as you note, all the references seem very shallow now.

**Comment by jreback** [comment]
@dsm054 yes as I said a while back its not necessary. pickle compat is 'easy', just follow the pattern in ``pandas.compat.pickle_compat.py`` (might need a slight modification as this is not a rename but shouldn't be too hard).

**Comment by jreback** [comment]
xref https://github.com/pandas-dev/pandas/pull/15477 and this https://github.com/pandas-dev/pandas/pull/15506 (last was reverted, something odd changed in making the doc build take way longer).
